PX4 Firmware: rpi_rc_in Namespace Reference
rpi_rc_in Namespace Reference
Classes
class RcInput
Functions
static void usage (const char *reason)
Print the correct usage.
Variables
static RcInput * rc_input = nullptr
Function Documentation
static void rpi_rc_in::usage (const char * reason) static
Print the correct usage.
Definition at line 231 of file batt_smbus_main.cpp.
References PRINT_MODULE_DESCRIPTION(), PRINT_MODULE_USAGE_ARG(), PRINT_MODULE_USAGE_COMMAND, PRINT_MODULE_USAGE_COMMAND_DESCR(), PRINT_MODULE_USAGE_NAME(), PRINT_MODULE_USAGE_PARAM_STRING(), PX4_INFO, and PX4_WARN.
Referenced by rpi_rc_in::RcInput::_measure(), batt_smbus_main(), commander_main(), gpssim_main(), rpi_rc_in_main(), and px4flow::start().
Variable Documentation
RcInput* rpi_rc_in::rc_input = nullptr static
Definition at line 103 of file rpi_rc_in.h.
Referenced by rpi_rc_in_main().