PX4 Firmware: src/drivers/boards/aerocore2/init.c File Reference
init.c File Reference
#include <px4_config.h>
#include <px4_tasks.h>
#include <stdbool.h>
#include <stdio.h>
#include <debug.h>
#include <errno.h>
#include "platform/cxxinitialize.h"
#include <nuttx/board.h>
#include <nuttx/spi/spi.h>
#include <nuttx/i2c/i2c_master.h>
#include <nuttx/analog/adc.h>
#include <stm32.h>
#include "board_config.h"
#include <stm32_uart.h>
#include <arch/board/board.h>
#include <drivers/drv_hrt.h>
#include <drivers/drv_board_led.h>
#include <systemlib/cpuload.h>
#include <perf/perf_counter.h>
#include <systemlib/err.h>
#include <parameters/param.h>
Macros
#define message printf
Functions
__BEGIN_DECLS void led_init (void)
void led_on (int led)
void led_off (int led)
__END_DECLS __EXPORT void board_peripheral_reset (int ms)
__EXPORT void stm32_boardinitialize (void)
__EXPORT int board_app_initialize (uintptr_t arg)
Variables
static struct spi_dev_s * spi3
static struct spi_dev_s * spi4
Macro Definition Documentation
#define message printf
Definition at line 95 of file init.c.
Referenced by board_app_initialize(), Simulator::pollForMAVLinkMessages(), px4::Replay::readAndAddSubscription(), px4::Replay::readAndApplyParameter(), px4::Replay::readFlagBits(), px4::logger::Logger::run(), and Simulator::send_controls().
Function Documentation
__EXPORT int board_app_initialize (uintptr_t arg)
Definition at line 207 of file init.c.
References board_autoled_on(), board_dma_alloc_init, drv_led_start(), hrt_call_every(), hrt_init(), LED_AMBER, led_off(), message, OK, param_init(), PX4_SPIDEV_ACCEL_MAG, PX4_SPIDEV_BARO, PX4_SPIDEV_GYRO, spi3, spi4, and ts_to_abstime().
Referenced by uavcannode_start().
__END_DECLS __EXPORT void board_peripheral_reset (int ms)
Definition at line 124 of file init.c.
__EXPORT void led_init (void)
Definition at line 72 of file led.c.
Referenced by Commander::run().
__EXPORT void led_off (int led)
Definition at line 97 of file led.c.
Referenced by board_app_initialize(), and control_status_leds().
__EXPORT void led_on (int led)
Definition at line 92 of file led.c.
Referenced by board_app_initialize(), and control_status_leds().
__EXPORT void stm32_boardinitialize (void)
Definition at line 151 of file init.c.
References board_autoled_initialize(), GPIO_CAN1_RX, GPIO_CAN1_TX, GPIO_POWER_MUX_SENSE, GPIO_SPEKTRUM_PWR_EN, and stm32_spiinitialize().
Variable Documentation
struct spi_dev_s* spi3 static
Definition at line 204 of file init.c.
Referenced by board_app_initialize().
struct spi_dev_s* spi4 static
Definition at line 205 of file init.c.
Referenced by board_app_initialize().