PX4 Firmware: mpl3115a2 Namespace Reference
mpl3115a2 Namespace Reference
Local functions in support of the shell command.
Classes
struct mpl3115a2_bus_option
Functions
bool start_bus (struct mpl3115a2_bus_option &bus)
Start the driver.
struct mpl3115a2_bus_option & find_bus (enum MPL3115A2_BUS busid)
find a bus structure for a busid
void start (enum MPL3115A2_BUS busid)
Start the driver.
void test (enum MPL3115A2_BUS busid)
Perform some basic functional tests on the driver; make sure we can collect data from the sensor in polled and automatic modes.
void reset (enum MPL3115A2_BUS busid)
Reset the driver.
void info ()
Print a little info about the driver.
void usage ()
Prints info about the driver argument usage.
Variables
struct mpl3115a2::mpl3115a2_bus_option bus_options []
Detailed Description
Local functions in support of the shell command.
Function Documentation
struct mpl3115a2_bus_option & mpl3115a2::find_bus (enum MPL3115A2_BUS busid)
find a bus structure for a busid
Definition at line 815 of file mpl3115a2.cpp.
References bus_options, errx, MPL3115A2_BUS_ALL, and NUM_BUS_OPTIONS.
Referenced by reset(), and test().
void mpl3115a2::info ()
Print a little info about the driver.
Definition at line 924 of file mpl3115a2.cpp.
References bus_options, mpl3115a2::mpl3115a2_bus_option::dev, mpl3115a2::mpl3115a2_bus_option::devpath, NUM_BUS_OPTIONS, MPL3115A2::print_info(), and warnx.
Referenced by mpl3115a2_main().
void mpl3115a2::reset (enum MPL3115A2_BUS busid)
Reset the driver.
Definition at line 898 of file mpl3115a2.cpp.
References mpl3115a2::mpl3115a2_bus_option::devpath, err, fd, find_bus(), MPL3115A2::ioctl(), device::CDev::open(), SENSOR_POLLRATE_DEFAULT, SENSORIOCRESET, and SENSORIOCSPOLLRATE.
Referenced by mpl3115a2_main().
void mpl3115a2::start (enum MPL3115A2_BUS busid)
Start the driver.
This function call only returns once the driver is either successfully up and running or failed to start.
Definition at line 784 of file mpl3115a2.cpp.
References bus_options, MPL3115A2_BUS_ALL, NUM_BUS_OPTIONS, and start_bus().
Referenced by mpl3115a2_main().
bool mpl3115a2::start_bus (struct mpl3115a2_bus_option & bus)
Start the driver.
Definition at line 738 of file mpl3115a2.cpp.
References device::CDev::close(), mpl3115a2::mpl3115a2_bus_option::dev, errx, fd, MPL3115A2::ioctl(), MPL3115A2::MPL3115A2(), OK, device::CDev::open(), SENSOR_POLLRATE_DEFAULT, SENSORIOCSPOLLRATE, and warnx.
Referenced by start().
void mpl3115a2::test (enum MPL3115A2_BUS busid)
Perform some basic functional tests on the driver; make sure we can collect data from the sensor in polled and automatic modes.
Definition at line 833 of file mpl3115a2.cpp.
References baro_report, device::CDev::close(), mpl3115a2::mpl3115a2_bus_option::devpath, err, errx, fd, find_bus(), MPL3115A2::ioctl(), OK, device::CDev::open(), device::CDev::poll(), MPL3115A2::read(), SENSORIOCSPOLLRATE, and SENSORIOCSQUEUEDEPTH.
Referenced by mpl3115a2_main().
void mpl3115a2::usage (void)
Prints info about the driver argument usage.
Definition at line 939 of file mpl3115a2.cpp.
References warnx.
Referenced by mpl3115a2_main().
Variable Documentation
struct mpl3115a2::mpl3115a2_bus_option mpl3115a2::bus_options[]
Initial value:
= {
}
Referenced by find_bus(), info(), and start().