PX4 Firmware: src/lib/mixer/load_mixer_file.cpp File Reference
load_mixer_file.cpp File Reference
#include <string.h>
#include <stdio.h>
#include <ctype.h>
#include "mixer_load.h"
Functions
int load_mixer_file (const char *fname, char *buf, unsigned maxlen)
Function Documentation
load_mixer_file()
int load_mixer_file (const char * fname, char * buf, unsigned maxlen)
Definition at line 46 of file load_mixer_file.cpp.
References f().
Referenced by linux_pwm_out::initialize_mixer(), df_bebop_bus_wrapper::initialize_mixers(), load(), and MixerTest::load_mixer().