PX4 Firmware: px4::logger::LogWriterMavlink Class Reference
px4::logger::LogWriterMavlink Class Reference
Writes logging data to uORB, and then sent via mavlink.
#include <log_writer_mavlink.h>
Public Member Functions
LogWriterMavlink (unsigned int queue_size)
~LogWriterMavlink ()
bool init ()
void start_log ()
void stop_log ()
bool is_started () const
int write_message (void *ptr, size_t size)
void set_need_reliable_transfer (bool need_reliable)
bool need_reliable_transfer () const
Private Member Functions
int publish_message ()
publish message, wait for ack if needed & reset message
Private Attributes
ulog_stream_s _ulog_stream_data
orb_advert_t _ulog_stream_pub = nullptr
int _ulog_stream_ack_sub = -1
bool _need_reliable_transfer = false
bool _is_started = false
const unsigned int _queue_size
Detailed Description
Writes logging data to uORB, and then sent via mavlink.
Definition at line 49 of file log_writer_mavlink.h.
Constructor & Destructor Documentation
px4::logger::LogWriterMavlink::LogWriterMavlink (unsigned int queue_size)
Definition at line 49 of file log_writer_mavlink.cpp.
References _ulog_stream_data, and ulog_stream_s::length.
px4::logger::LogWriterMavlink::~LogWriterMavlink ()
Definition at line 60 of file log_writer_mavlink.cpp.
References _ulog_stream_ack_sub, _ulog_stream_pub, orb_unadvertise(), and orb_unsubscribe().
Member Function Documentation
bool px4::logger::LogWriterMavlink::init ()
Definition at line 55 of file log_writer_mavlink.cpp.
Referenced by px4::logger::LogWriter::init().
bool px4::logger::LogWriterMavlink::is_started () const inline
Definition at line 61 of file log_writer_mavlink.h.
References _is_started, set_need_reliable_transfer(), and write_message().
Referenced by px4::logger::LogWriter::is_started(), and write_message().
bool px4::logger::LogWriterMavlink::need_reliable_transfer () const inline
Definition at line 68 of file log_writer_mavlink.h.
References _need_reliable_transfer, and publish_message().
Referenced by px4::logger::LogWriter::need_reliable_transfer().
int px4::logger::LogWriterMavlink::publish_message () private
publish message, wait for ack if needed & reset message
Definition at line 141 of file log_writer_mavlink.cpp.
References _need_reliable_transfer, _queue_size, _ulog_stream_ack_sub, _ulog_stream_data, _ulog_stream_pub, ulog_stream_s::first_message_offset, ulog_stream_s::flags, hrt_absolute_time(), hrt_abstime, hrt_elapsed_time(), ulog_stream_s::length, orb_advertise_queue(), orb_copy(), ORB_ID, orb_publish(), PX4_DEBUG, PX4_ERR, px4_poll(), ulog_stream_s::sequence, ulog_stream_ack_s::sequence, stop_log(), timeout_ms, and ulog_stream_s::timestamp.
Referenced by need_reliable_transfer(), set_need_reliable_transfer(), and write_message().
void px4::logger::LogWriterMavlink::set_need_reliable_transfer (bool need_reliable)
Definition at line 129 of file log_writer_mavlink.cpp.
References _need_reliable_transfer, _ulog_stream_data, ulog_stream_s::length, and publish_message().
Referenced by is_started(), and px4::logger::LogWriter::set_need_reliable_transfer().
void px4::logger::LogWriterMavlink::start_log ()
Definition at line 71 of file log_writer_mavlink.cpp.
References _is_started, _queue_size, _ulog_stream_ack_sub, _ulog_stream_data, _ulog_stream_pub, ulog_stream_s::first_message_offset, ulog_stream_s::length, orb_advertise_queue(), orb_copy(), ORB_ID, orb_subscribe(), and ulog_stream_s::sequence.
Referenced by px4::logger::LogWriter::start_log_mavlink().
void px4::logger::LogWriterMavlink::stop_log ()
Definition at line 93 of file log_writer_mavlink.cpp.
References _is_started, _ulog_stream_data, and ulog_stream_s::length.
Referenced by publish_message(), and px4::logger::LogWriter::stop_log_mavlink().
int px4::logger::LogWriterMavlink::write_message (void * ptr, size_t size)
See also
LogWriter::write_message()
Definition at line 99 of file log_writer_mavlink.cpp.
References _ulog_stream_data, ulog_stream_s::data, ulog_stream_s::first_message_offset, is_started(), ulog_stream_s::length, math::min(), and publish_message().
Referenced by is_started(), and px4::logger::LogWriter::write_message().
Member Data Documentation
bool px4::logger::LogWriterMavlink::_is_started = false private
Definition at line 82 of file log_writer_mavlink.h.
Referenced by is_started(), start_log(), and stop_log().
bool px4::logger::LogWriterMavlink::_need_reliable_transfer = false private
Definition at line 81 of file log_writer_mavlink.h.
Referenced by need_reliable_transfer(), publish_message(), and set_need_reliable_transfer().
const unsigned int px4::logger::LogWriterMavlink::_queue_size private
Definition at line 83 of file log_writer_mavlink.h.
Referenced by publish_message(), and start_log().
int px4::logger::LogWriterMavlink::_ulog_stream_ack_sub = -1 private
Definition at line 80 of file log_writer_mavlink.h.
Referenced by publish_message(), start_log(), and ~LogWriterMavlink().
ulog_stream_s px4::logger::LogWriterMavlink::_ulog_stream_data private
Definition at line 78 of file log_writer_mavlink.h.
Referenced by LogWriterMavlink(), publish_message(), set_need_reliable_transfer(), start_log(), stop_log(), and write_message().
orb_advert_t px4::logger::LogWriterMavlink::_ulog_stream_pub = nullptr private
Definition at line 79 of file log_writer_mavlink.h.
Referenced by publish_message(), start_log(), and ~LogWriterMavlink().
The documentation for this class was generated from the following files:
src/modules/logger/log_writer_mavlink.h
src/modules/logger/log_writer_mavlink.cpp