PX4 Firmware: src/lib/ecl/geo_lookup/geo_mag_declination.h File Reference
geo_mag_declination.h File Reference
Calculation / lookup table for Earth's magnetic field declination, inclination and strength.
Functions
float get_mag_declination (float lat, float lon)
float get_mag_inclination (float lat, float lon)
float get_mag_strength (float lat, float lon)
Detailed Description
Calculation / lookup table for Earth's magnetic field declination, inclination and strength.
Data generated by https://www.ngdc.noaa.gov/geomag-web/#igrfgrid IGRF calculator on 22 Jan 2018
Definition in file geo_mag_declination.h.
Function Documentation
get_mag_declination()
float get_mag_declination (float lat, float lon)
Definition at line 165 of file geo_mag_declination.cpp.
References declination_table, and get_table_data().
Referenced by AutoDeclinationTest::autodeclination_check(), Ekf::collect_gps(), and AttitudeEstimatorQ::Run().
get_mag_inclination()
float get_mag_inclination (float lat, float lon)
Definition at line 170 of file geo_mag_declination.cpp.
References get_table_data(), and inclination_table.
Referenced by Ekf::collect_gps().
get_mag_strength()
float get_mag_strength (float lat, float lon)
Definition at line 175 of file geo_mag_declination.cpp.
References get_table_data(), and strength_table.
Referenced by Ekf::collect_gps().