PX4 Firmware: src/lib/ecl/test/test_EKF_basics.cpp File Reference
test_EKF_basics.cpp File Reference
#include <gtest/gtest.h>
#include <math.h>
#include "EKF/ekf.h"
Classes
class EkfInitializationTest
Functions
TEST_F (EkfInitializationTest, tiltAlign)
TEST_F (EkfInitializationTest, initialControlMode)
TEST_F (EkfInitializationTest, convergesToZero)
TEST_F (EkfInitializationTest, gpsFusion)
TEST_F (EkfInitializationTest, accleBiasEstimation)
Function Documentation
TEST_F() [1/5]
TEST_F (EkfInitializationTest , tiltAlign)
Definition at line 163 of file test_EKF_basics.cpp.
References EkfInitializationTest::_ekf, and EstimatorInterface::attitude_valid().
TEST_F() [2/5]
TEST_F (EkfInitializationTest , initialControlMode)
Definition at line 170 of file test_EKF_basics.cpp.
References EkfInitializationTest::_ekf, estimator::filter_control_status_u::baro_hgt, estimator::filter_control_status_u::ev_hgt, estimator::filter_control_status_u::ev_pos, estimator::filter_control_status_u::ev_vel, estimator::filter_control_status_u::ev_yaw, estimator::filter_control_status_u::fixed_wing, estimator::filter_control_status_u::flags, estimator::filter_control_status_u::fuse_beta, EstimatorInterface::get_control_mode(), estimator::filter_control_status_u::gnd_effect, estimator::filter_control_status_u::gps, estimator::filter_control_status_u::gps_hgt, estimator::filter_control_status_u::gps_yaw, estimator::filter_control_status_u::in_air, estimator::filter_control_status_u::mag_3D, estimator::filter_control_status_u::mag_aligned_in_flight, estimator::filter_control_status_u::mag_dec, estimator::filter_control_status_u::mag_fault, estimator::filter_control_status_u::mag_field_disturbed, estimator::filter_control_status_u::mag_hdg, estimator::filter_control_status_u::opt_flow, estimator::filter_control_status_u::rng_hgt, estimator::filter_control_status_u::rng_stuck, estimator::filter_control_status_u::synthetic_mag_z, estimator::filter_control_status_u::tilt_align, estimator::filter_control_status_u::value, estimator::filter_control_status_u::wind, and estimator::filter_control_status_u::yaw_align.
TEST_F() [3/5]
TEST_F (EkfInitializationTest , convergesToZero)
Definition at line 204 of file test_EKF_basics.cpp.
References EkfInitializationTest::_ekf, f(), Ekf::get_accel_bias(), Ekf::get_gyro_bias(), EstimatorInterface::get_position(), EstimatorInterface::get_velocity(), and EkfInitializationTest::update_with_const_sensors().
TEST_F() [4/5]
TEST_F (EkfInitializationTest , gpsFusion)
Definition at line 229 of file test_EKF_basics.cpp.
References EkfInitializationTest::_ekf, EkfInitializationTest::_fuse_gps, CONSTANTS_ONE_G, EstimatorInterface::get_control_mode(), and EkfInitializationTest::update_with_const_sensors().
TEST_F() [5/5]
TEST_F (EkfInitializationTest , accleBiasEstimation)
Definition at line 267 of file test_EKF_basics.cpp.
References EkfInitializationTest::_ekf, EkfInitializationTest::_fuse_gps, CONSTANTS_ONE_G, f(), Ekf::get_accel_bias(), Ekf::get_gyro_bias(), EstimatorInterface::get_position(), EstimatorInterface::get_velocity(), and EkfInitializationTest::update_with_const_sensors().