PX4 Firmware: spektrum_rc Namespace Reference
spektrum_rc Namespace Reference
Functions
int start ()
Attempt to start driver on all available I2C busses.
int stop ()
Stop the driver.
int info ()
Print a little info about the driver.
void usage ()
Prints info about the driver argument usage.
void task_main (int argc, char *argv[])
void fill_input_rc (uint16_t raw_rc_count, uint16_t raw_rc_values[input_rc_s::RC_INPUT_MAX_CHANNELS], hrt_abstime now, bool frame_drop, bool failsafe, unsigned frame_drops, int rssi, input_rc_s &input_rc)
int start (int argc, char *argv[])
Variables
volatile bool _task_should_exit = false
static bool _is_running = false
static px4_task_t _task_handle = -1
Function Documentation
void spektrum_rc::fill_input_rc (uint16_t raw_rc_count, uint16_t raw_rc_values[input_rc_s::RC_INPUT_MAX_CHANNELS], hrt_abstime now, bool frame_drop, bool failsafe, unsigned frame_drops, int rssi, input_rc_s & input_rc)
Definition at line 163 of file spektrum_rc.cpp.
References input_rc_s::channel_count, input_rc_s::input_source, input_rc_s::rc_failsafe, input_rc_s::rc_lost, input_rc_s::rc_lost_frame_count, input_rc_s::rc_ppm_frame_length, input_rc_s::rc_total_frame_count, input_rc_s::rssi, input_rc_s::timestamp, input_rc_s::timestamp_last_signal, and input_rc_s::values.
Referenced by task_main().
int spektrum_rc::info ()
Print a little info about the driver.
Print a little info about the driver.
Definition at line 252 of file spektrum_rc.cpp.
References PX4_INFO.
Referenced by spektrum_rc_main().
int spektrum_rc::start ()
Attempt to start driver on all available I2C busses.
This function will return as soon as the first sensor is detected on one of the available busses or if no sensors are detected.
Attempt to start driver on all available I2C busses.
Definition at line 257 of file ets_airspeed.cpp.
References ACCEL_DEVICE_PATH, BMA180::BMA180(), DfBebopBusWrapper::DfBebopBusWrapper(), DfBebopRangeFinderWrapper::DfBebopRangeFinderWrapper(), DfBmp280Wrapper::DfBmp280Wrapper(), DfISL29501Wrapper::DfISL29501Wrapper(), DfLtc2946Wrapper::DfLtc2946Wrapper(), DfMS5607Wrapper::DfMS5607Wrapper(), DfMS5611Wrapper::DfMS5611Wrapper(), errx, fd, hc_sr04::g_dev, bma180::g_dev, HC_SR04::HC_SR04(), I2C_ADDRESS_MS4525DO, i2c_bus_options, HC_SR04::init(), BMA180::init(), HC_SR04::ioctl(), BMA180::ioctl(), OK, device::CDev::open(), PX4_ERR, PX4_ERROR, PX4_INFO, PX4_OK, PX4_SPIDEV_BMA, px4_task_spawn_cmd(), PX4_WARN, RGBLED::RGBLED(), SCHED_DEFAULT, SCHED_PRIORITY_MAX, SENSOR_POLLRATE_DEFAULT, SENSORIOCSPOLLRATE, SR04_DEVICE_PATH, RGBLED::start(), VideoDevice::start(), Syslink::start(), DfLtc2946Wrapper::start(), DfBebopBusWrapper::start(), DfMS5611Wrapper::start(), DfMS5607Wrapper::start(), DfBmp280Wrapper::start(), DfBebopRangeFinderWrapper::start(), DfISL29501Wrapper::start(), sdp3x_airspeed::start_bus(), ms5525_airspeed::start_bus(), ets_airspeed::start_bus(), meas_airspeed::start_bus(), Syslink::Syslink(), bebop_flow::task_main(), df_bebop_bus_wrapper::task_main(), uart_esc::task_main_trampoline(), mpu9x50::task_main_trampoline(), usleep(), warn, and warnx.
Referenced by bebop_flow_main(), bma180_main(), df_bebop_bus_wrapper_main(), df_bebop_rangefinder_wrapper_main(), df_bmp280_wrapper_main(), df_isl29501_wrapper_main(), df_ltc2946_wrapper_main(), df_ms5607_wrapper_main(), df_ms5611_wrapper_main(), ets_airspeed_main(), hc_sr04_main(), mpu9x50_main(), ms4525_airspeed_main(), ms5525_airspeed_main(), navio_rgbled_main(), sdp3x_airspeed_main(), spektrum_rc_main(), and syslink_main().
int spektrum_rc::start (int argc, char * argv[])
Definition at line 208 of file spektrum_rc.cpp.
References PX4_ERR, px4_task_spawn_cmd(), PX4_WARN, SCHED_DEFAULT, and task_main().
int spektrum_rc::stop ()
Stop the driver.
Stop the driver.
Definition at line 234 of file spektrum_rc.cpp.
References PX4_INFO, PX4_WARN, and usleep().
Referenced by spektrum_rc_main().
void spektrum_rc::task_main (int argc, char * argv[])
Definition at line 78 of file spektrum_rc.cpp.
References DSM_BUFFER_SIZE, dsm_deinit(), dsm_init(), dsm_parse(), fill_input_rc(), hrt_absolute_time(), hrt_abstime, orb_advert_t, orb_advertise(), ORB_ID, orb_publish(), orb_unadvertise(), PX4_ERR, px4_getopt(), PX4_WARN, read(), rx_buf, SPEKTRUM_UART_DEVICE_PATH, UNUSED, and usleep().
Referenced by start().
void spektrum_rc::usage (void)
Prints info about the driver argument usage.
Prints info about the driver argument usage.
Definition at line 260 of file spektrum_rc.cpp.
References PX4_INFO.
Referenced by spektrum_rc_main().
Variable Documentation
bool spektrum_rc::_is_running = false static
Definition at line 65 of file spektrum_rc.cpp.
px4_task_t spektrum_rc::_task_handle = -1 static
Definition at line 66 of file spektrum_rc.cpp.
volatile bool spektrum_rc::_task_should_exit = false
Definition at line 64 of file spektrum_rc.cpp.