PX4 Firmware: src/lib/parameters/param_shmem.c File Reference
param_shmem.c File Reference
#include <px4_defines.h>
#include <px4_posix.h>
#include <px4_shutdown.h>
#include <string.h>
#include <stdbool.h>
#include <stdlib.h>
#include <fcntl.h>
#include <unistd.h>
#include <systemlib/err.h>
#include <errno.h>
#include <px4_sem.h>
#include <sys/stat.h>
#include <drivers/drv_hrt.h>
#include "param.h"
#include "systemlib/uthash/utarray.h"
#include "tinybson/tinybson.h"
#include "uORB/uORB.h"
#include "uORB/topics/parameter_update.h"
#include <parameters/px4_parameters.h>
#include <crc32.h>
#include "shmem.h"
#include <px4_workqueue.h>
Classes
struct param_wbuf_s
Storage for modified parameters.
struct param_import_state
Macros
#define debug(fmt, args...) do { } while(0)
#define PARAM_OPEN open
#define PARAM_CLOSE close
#define param_info_count px4_parameters.param_count
Functions
int get_shmem_lock (const char *caller_file_name, int caller_line_number)
void release_shmem_lock (const char *caller_file_name, int caller_line_number)
struct param_wbuf_s * param_find_changed (param_t param)
Locate the modified parameter structure for a parameter, if it exists.
void init_params (void)
void init_shared_memory (void)
void copy_params_to_shmem (struct param_info_s *param_info_base)
void update_to_shmem (param_t param, union param_value_u value)
int update_from_shmem (param_t param, union param_value_u *value)
void update_index_from_shmem (void)
static int param_set_internal (param_t param, const void *val, bool mark_saved, bool notify_changes)
static int param_load_default_no_notify (void)
static unsigned get_param_info_count (void)
static void param_set_used_internal (param_t param)
static param_t param_find_internal (const char *name, bool notification)
static void param_lock (void)
lock the parameter store
static void param_unlock (void)
unlock the parameter store
static void param_assert_locked (void)
assert that the parameter store is locked
void param_init (void)
Initialize the param backend.
bool handle_in_range (param_t param)
Test whether a param_t is value.
static int param_compare_values (const void *a, const void *b)
Compare two modifid parameter structures to determine ordering.
static void _param_notify_changes (void)
void param_notify_changes (void)
Notify the system about parameter changes.
param_t param_find (const char *name)
Look up a parameter by name.
param_t param_find_no_notification (const char *name)
Look up a parameter by name.
unsigned param_count (void)
Return the total number of parameters.
unsigned param_count_used (void)
Return the actually used number of parameters.
param_t param_for_index (unsigned index)
Look up a parameter by index.
param_t param_for_used_index (unsigned index)
Look up an used parameter by index.
int param_get_index (param_t param)
Look up the index of a parameter.
int param_get_used_index (param_t param)
Look up the index of an used parameter.
const char * param_name (param_t param)
Obtain the name of a parameter.
bool param_value_is_default (param_t param)
Test whether a parameter's value has changed from the default.
bool param_value_unsaved (param_t param)
Test whether a parameter's value has been changed but not saved.
param_type_t param_type (param_t param)
Obtain the type of a parameter.
size_t param_size (param_t param)
Determine the size of a parameter.
static const void * param_get_value_ptr (param_t param)
Obtain a pointer to the storage allocated for a parameter.
int param_get (param_t param, void *val)
Copy the value of a parameter.
static void autosave_worker (void *arg)
worker callback method to save the parameters
static void param_autosave (void)
Automatically save the parameters after a timeout and limited rate.
void param_control_autosave (bool enable)
Enable/disable the param autosaving.
int param_set (param_t param, const void *val)
Set the value of a parameter.
int param_set_no_notification (param_t param, const void *val)
Set the value of a parameter, but do not notify the system about the change.
bool param_used (param_t param)
Wether a parameter is in use in the system.
void param_set_used (param_t param)
Mark a parameter as used.
int param_reset (param_t param)
Reset a parameter to its default value.
static void param_reset_all_internal (bool auto_save)
void param_reset_all (void)
Reset all parameters to their default values.
void param_reset_excludes (const char *excludes[], int num_excludes)
Reset all parameters to their default values except for excluded parameters.
int param_set_default_file (const char *filename)
Set the default parameter file name.
const char * param_get_default_file (void)
Get the default parameter file name.
int param_save_default (void)
Save parameters to the default file.
int param_load_default (void)
Load parameters from the default parameter file.
int param_export (int fd, bool only_unsaved)
Export changed parameters to a file.
static int param_import_callback (bson_decoder_t decoder, void *private, bson_node_t node)
static int param_import_internal (int fd, bool mark_saved)
int param_import (int fd)
Import parameters from a file, discarding any unrecognized parameters.
int param_load (int fd)
Load parameters from a file.
void param_foreach (void(*func)(void *arg, param_t param), void *arg, bool only_changed, bool only_used)
Apply a function to each parameter.
uint32_t param_hash_check (void)
Generate the hash of all parameters and their values.
Variables
static const char * param_default_file = "/usr/share/data/adsp/params"
static char * param_user_file = NULL
static hrt_abstime last_autosave_timestamp = 0
static struct work_s autosave_work
static bool autosave_scheduled = false
static bool autosave_disabled = false
static struct param_info_s * param_info_base = (struct param_info_s *) &px4_parameters
Array of static parameter info.
uint8_t * param_changed_storage = 0
int size_param_changed_storage_bytes = 0
const int bits_per_allocation_unit = (sizeof(*param_changed_storage) * 8)
struct shmem_info * shmem_info_p
uint64_t sync_other_prev_time = 0
uint64_t sync_other_current_time = 0
int param_instance = 0
unsigned char set_called_from_get = 0
static int param_import_done
UT_array * param_values
flexible array holding modified parameter values
const UT_icd param_icd = {sizeof(struct param_wbuf_s), NULL, NULL, NULL}
array info for the modified parameters array
static orb_advert_t param_topic = NULL
parameter update topic handle
Macro Definition Documentation
#define debug (fmt, args...) do { } while(0)
Definition at line 80 of file param_shmem.c.
Referenced by param_set_internal().
#define PARAM_CLOSE close
Definition at line 88 of file param_shmem.c.
Referenced by param_load_default(), and param_save_default().
#define param_info_count px4_parameters.param_count
Definition at line 101 of file param_shmem.c.
Referenced by get_param_info_count().
#define PARAM_OPEN open
Definition at line 86 of file param_shmem.c.
Referenced by param_load_default(), and param_save_default().
Function Documentation
static void _param_notify_changes (void) static
Definition at line 271 of file param_shmem.c.
References hrt_absolute_time(), orb_advertise(), ORB_ID, orb_publish(), param_instance, and parameter_update_s::timestamp.
Referenced by param_notify_changes(), param_reset(), param_reset_all_internal(), param_reset_excludes(), and param_set_internal().
static void autosave_worker (void * arg) static
worker callback method to save the parameters
Parameters
arg unused
Definition at line 596 of file param_shmem.c.
References autosave_disabled, autosave_scheduled, hrt_absolute_time(), last_autosave_timestamp, param_lock(), param_save_default(), param_unlock(), PX4_DEBUG, and PX4_ERR.
Referenced by param_autosave().
void copy_params_to_shmem (struct param_info_s * param_info_base)
Referenced by init_params().
static unsigned get_param_info_count (void) static
Definition at line 146 of file param_shmem.c.
References bits_per_allocation_unit, param_changed_storage, param_info_count, and size_param_changed_storage_bytes.
Referenced by handle_in_range(), param_count(), param_count_used(), param_for_index(), and param_for_used_index().
int get_shmem_lock (const char * caller_file_name, int caller_line_number)
bool handle_in_range (param_t param)
Test whether a param_t is value.
Parameters
param The parameter handle to test.
Returns
True if the handle is valid.
Definition at line 217 of file param_shmem.c.
References get_param_info_count().
Referenced by param_find_internal(), param_foreach(), param_get(), param_get_index(), param_get_value_ptr(), param_hash_check(), param_name(), param_reset(), param_reset_excludes(), param_set_internal(), param_size(), and param_type().
void init_params (void)
Definition at line 1347 of file param_shmem.c.
References shmem_info::adsp_changed_index, copy_params_to_shmem(), init_shared_memory(), shmem_info::krait_changed_index, param_import_done, param_load_default_no_notify(), shmem_info::params_val, and PX4_INFO.
void init_shared_memory (void)
Referenced by init_params().
static void param_assert_locked (void) static
assert that the parameter store is locked
Definition at line 198 of file param_shmem.c.
Referenced by param_find_changed(), and param_get_value_ptr().
static void param_autosave (void) static
Automatically save the parameters after a timeout and limited rate.
This needs to be called with the writer lock held (it's not necessary that it's the writer lock, but it needs to be the same lock as autosave_worker() and param_control_autosave() use).
Definition at line 624 of file param_shmem.c.
References autosave_disabled, autosave_scheduled, autosave_work, autosave_worker(), hrt_abstime, hrt_elapsed_time(), and last_autosave_timestamp.
Referenced by param_reset(), param_reset_all_internal(), and param_set_internal().
static int param_compare_values (const void * a, const void * b) static
Compare two modifid parameter structures to determine ordering.
This function is suitable for passing to qsort or bsearch.
Definition at line 229 of file param_shmem.c.
References param_wbuf_s::param.
Referenced by param_set_internal().
void param_control_autosave (bool enable)
Enable/disable the param autosaving.
Re-enabling with changed params will not cause an autosave.
Parameters
enable true: enable autosaving, false: disable autosaving
Definition at line 648 of file param_shmem.c.
References autosave_disabled, autosave_scheduled, autosave_work, param_lock(), param_lock_writer(), param_unlock(), and param_unlock_writer().
unsigned param_count (void)
Return the total number of parameters.
Returns
The number of parameters.
Definition at line 327 of file param_shmem.c.
References get_param_info_count().
unsigned param_count_used (void)
Return the actually used number of parameters.
Returns
The number of parameters.
Definition at line 333 of file param_shmem.c.
References bits_per_allocation_unit, get_param_info_count(), param_changed_storage, and size_param_changed_storage_bytes.
int param_export (int fd, bool only_unsaved)
Export changed parameters to a file.
Note: this method requires a large amount of stack size!
Parameters
fd File descriptor to export to.
only_unsaved Only export changed parameters that have not yet been exported.
Returns
Zero on success, nonzero on failure.
Definition at line 1041 of file param_shmem.c.
References BSON_BIN_BINARY, bson_encoder_append_binary(), bson_encoder_append_double(), bson_encoder_append_int(), bson_encoder_fini(), bson_encoder_init_buf_file(), bson_encoder_init_file(), debug, f(), param_value_u::f, fsync(), param_value_u::i, name, param_wbuf_s::param, param_get_value_ptr(), param_lock(), param_lock_reader(), param_name(), param_size(), param_type(), PARAM_TYPE_FLOAT, PARAM_TYPE_INT32, PARAM_TYPE_STRUCT, PARAM_TYPE_STRUCT_MAX, param_unlock(), param_unlock_reader(), param_values, perf_begin(), perf_end(), PX4_DEBUG, PX4_ERR, PX4_OK, px4_sem_post, px4_sem_wait, px4_shutdown_lock(), px4_shutdown_unlock(), param_wbuf_s::unsaved, update_from_shmem(), update_index_from_shmem(), utarray_next, and param_wbuf_s::val.
Referenced by param_save_default().
param_t param_find (const char * name)
Look up a parameter by name.
Parameters
name The canonical name of the parameter being looked up.
Returns
A handle to the parameter, or PARAM_INVALID if the parameter does not exist. This call will also set the parameter as "used" in the system, which is used to e.g. show the parameter via the RC interface
Definition at line 315 of file param_shmem.c.
References param_find_internal().
struct param_wbuf_s * param_find_changed (param_t param)
Locate the modified parameter structure for a parameter, if it exists.
Parameters
param The parameter being searched.
Returns
The structure holding the modified value, or NULL if the parameter has not been modified.
Definition at line 253 of file param_shmem.c.
References param_wbuf_s::param, param_assert_locked(), and utarray_next.
Referenced by param_foreach(), param_get_value_ptr(), param_reset(), param_set_internal(), param_value_is_default(), and param_value_unsaved().
param_t param_find_internal (const char * name, bool notification) static
Definition at line 295 of file param_shmem.c.
References handle_in_range(), param_wbuf_s::param, PARAM_INVALID, and param_set_used_internal().
Referenced by param_find(), and param_find_no_notification().
param_t param_find_no_notification (const char * name)
Look up a parameter by name.
Parameters
name The canonical name of the parameter being looked up.
Returns
A handle to the parameter, or PARAM_INVALID if the parameter does not exist.
Definition at line 321 of file param_shmem.c.
References param_find_internal().
Referenced by param_import_callback().
param_t param_for_index (unsigned index)
Look up a parameter by index.
Parameters
index An index from 0 to n, where n is param_count()-1.
Returns
A handle to the parameter, or PARAM_INVALID if the index is out of range.
Definition at line 358 of file param_shmem.c.
References get_param_info_count(), and PARAM_INVALID.
Referenced by param_for_used_index().
param_t param_for_used_index (unsigned index)
Look up an used parameter by index.
Parameters
index The parameter to obtain the index for.
Returns
The index of the parameter in use, or -1 if the parameter does not exist.
Definition at line 370 of file param_shmem.c.
References bits_per_allocation_unit, get_param_info_count(), param_changed_storage, param_for_index(), PARAM_INVALID, and size_param_changed_storage_bytes.
void param_foreach (void(*)(void *arg, param_t param) func, void * arg, bool only_changed, bool only_used)
Apply a function to each parameter.
Note that the parameter set is not locked during the traversal. It also does not hold an internal state, so the callback function can block or sleep between parameter callbacks.
Parameters
func The function to invoke for each parameter.
arg Argument passed to the function.
only_changed If true, the function is only called for parameters whose values have been changed from the default.
only_changed If true, the function is only called for parameters which have been used in one of the running applications.
Definition at line 1305 of file param_shmem.c.
References handle_in_range(), param_wbuf_s::param, param_find_changed(), and param_used().
int param_get (param_t param, void * val)
Copy the value of a parameter.
Parameters
param A handle returned by param_find or passed by param_foreach.
val Where to return the value, assumed to point to suitable storage for the parameter type. For structures, a bitwise copy of the structure is performed to this address.
Returns
Zero if the parameter's value could be returned, nonzero otherwise.
Definition at line 544 of file param_shmem.c.
References f(), handle_in_range(), param_value_u::i, param_get_value_ptr(), param_lock(), param_lock_reader(), param_name(), param_set_internal(), param_size(), param_type(), PARAM_TYPE_FLOAT, PARAM_TYPE_INT32, param_unlock(), param_unlock_reader(), perf_begin(), perf_end(), PX4_INFO, set_called_from_get, and update_from_shmem().
const char* param_get_default_file (void)
Get the default parameter file name.
Returns
The path to the current default parameter file; either as a result of a call to param_set_default_file, or the built-in default.
Definition at line 929 of file param_shmem.c.
References param_default_file, and param_user_file.
Referenced by param_load_default(), param_load_default_no_notify(), and param_save_default().
int param_get_index (param_t param)
Look up the index of a parameter.
Parameters
param The parameter to obtain the index for.
Returns
The index, or -1 if the parameter does not exist.
Definition at line 403 of file param_shmem.c.
References handle_in_range(), and param_wbuf_s::param.
Referenced by param_set_used_internal(), and param_used().
int param_get_used_index (param_t param)
Look up the index of an used parameter.
Parameters
param The parameter to obtain the index for.
Returns
The index of the parameter in use, or -1 if the parameter does not exist.
Definition at line 413 of file param_shmem.c.
References bits_per_allocation_unit, param_wbuf_s::param, param_changed_storage, param_used(), and size_param_changed_storage_bytes.
static const void* param_get_value_ptr (param_t param) static
Obtain a pointer to the storage allocated for a parameter.
Parameters
param The parameter whose storage is sought.
Returns
A pointer to the parameter value, or NULL if the parameter does not exist.
Definition at line 510 of file param_shmem.c.
References handle_in_range(), param_value_u::p, param_wbuf_s::param, param_assert_locked(), param_find_changed(), param_type(), PARAM_TYPE_STRUCT, PARAM_TYPE_STRUCT_MAX, param_wbuf_s::val, and param_info_s::val.
Referenced by param_export(), param_get(), and param_hash_check().
uint32_t param_hash_check (void)
Generate the hash of all parameters and their values.
Returns
CRC32 hash of all param_ids and values
Definition at line 1324 of file param_shmem.c.
References handle_in_range(), name, param_wbuf_s::param, param_get_value_ptr(), param_is_volatile(), param_lock(), param_lock_reader(), param_name(), param_size(), param_unlock(), param_unlock_reader(), param_used(), and param_wbuf_s::val.
int param_import (int fd)
Import parameters from a file, discarding any unrecognized parameters.
This function merges the imported parameters with the current parameter set.
Parameters
fd File descriptor to import from. (Currently expected to be a file.)
Returns
Zero on success, nonzero if an error occurred during import. Note that in the failure case, parameters may be inconsistent.
Definition at line 1292 of file param_shmem.c.
References flash_param_import(), and param_import_internal().
Referenced by param_load_default_no_notify().
static int param_import_callback (bson_decoder_t decoder, void * private, bson_node_t node) static
Definition at line 1150 of file param_shmem.c.
References BSON_BIN_BINARY, BSON_BINDATA, bson_decoder_copy_data(), bson_decoder_data_pending(), BSON_DOUBLE, BSON_EOO, BSON_INT32, bson_node_s::d, f(), bson_node_s::i, param_import_state::mark_saved, bson_node_s::name, param_wbuf_s::param, param_find_no_notification(), PARAM_INVALID, param_name(), param_set_internal(), param_size(), param_type(), PARAM_TYPE_FLOAT, PARAM_TYPE_INT32, PX4_DEBUG, PX4_WARN, state, bson_node_s::subtype, and bson_node_s::type.
Referenced by param_import_internal().
static int param_import_internal (int fd, bool mark_saved) static
Definition at line 1264 of file param_shmem.c.
References bson_decoder_init_file(), bson_decoder_next(), param_import_state::mark_saved, param_import_callback(), and PX4_DEBUG.
Referenced by param_import(), and param_load().
void param_init (void)
Initialize the param backend.
Call this on startup before calling any other methods.
Definition at line 204 of file param_shmem.c.
References PC_ELAPSED, perf_alloc, and px4_sem_init.
int param_load (int fd)
Load parameters from a file.
This function resets all parameters to their default values, then loads new values from a file.
Parameters
fd File descriptor to import from. (Currently expected to be a file.)
Returns
Zero on success, nonzero if an error occurred during import. Note that in the failure case, parameters may be inconsistent.
Definition at line 1298 of file param_shmem.c.
References param_import_internal(), and param_reset_all_internal().
Referenced by param_load_default().
int param_load_default (void)
Load parameters from the default parameter file.
Returns
0 on success, 1 if all params have not yet been stored, -1 if device open failed, -2 if writing parameters failed
Definition at line 978 of file param_shmem.c.
References flash_param_load(), PARAM_CLOSE, param_get_default_file(), param_load(), PARAM_OPEN, and PX4_ERR.
static int param_load_default_no_notify (void) static
Returns
0 on success, 1 if all params have not yet been stored, -1 if device open failed, -2 if writing parameters failed
Definition at line 1008 of file param_shmem.c.
References param_get_default_file(), param_import(), PX4_DEBUG, PX4_WARN, and release_shmem_lock().
Referenced by init_params().
static void param_lock (void) static
lock the parameter store
Definition at line 182 of file param_shmem.c.
Referenced by autosave_worker(), param_control_autosave(), param_export(), param_get(), param_hash_check(), param_reset(), param_reset_all_internal(), param_set_internal(), param_value_is_default(), and param_value_unsaved().
const char* param_name (param_t param)
Obtain the name of a parameter.
Parameters
param A handle returned by param_find or passed by param_foreach.
Returns
The name assigned to the parameter, or NULL if the handle is invalid.
Definition at line 447 of file param_shmem.c.
References handle_in_range(), param_info_s::name, and param_wbuf_s::param.
Referenced by param_export(), param_get(), param_hash_check(), param_import_callback(), param_reset_excludes(), and param_set_internal().
void param_notify_changes (void)
Notify the system about parameter changes.
Can be used for example after several calls to param_set_no_notification() to avoid unnecessary system notifications.
Definition at line 288 of file param_shmem.c.
References _param_notify_changes().
int param_reset (param_t param)
Reset a parameter to its default value.
This function frees any storage used by struct parameters, and returns the parameter to its default value.
Parameters
param A handle returned by param_find or passed by param_foreach.
Returns
Zero on success, nonzero on failure
Definition at line 826 of file param_shmem.c.
References _param_notify_changes(), handle_in_range(), param_autosave(), param_find_changed(), param_lock(), param_lock_writer(), param_unlock(), param_unlock_writer(), param_values, utarray_eltidx, and utarray_erase.
Referenced by param_reset_excludes().
void param_reset_all (void)
Reset all parameters to their default values.
This function also releases the storage used by struct parameters.
Definition at line 879 of file param_shmem.c.
References param_reset_all_internal().
static void param_reset_all_internal (bool auto_save) static
Definition at line 858 of file param_shmem.c.
References _param_notify_changes(), param_autosave(), param_lock(), param_unlock(), and utarray_free.
Referenced by param_load(), and param_reset_all().
void param_reset_excludes (const char * excludes[], int num_excludes)
Reset all parameters to their default values except for excluded parameters.
This function also releases the storage used by struct parameters.
Parameters
excludes Array of param names to exclude from resetting. Use a wildcard at the end to exclude parameters with a certain prefix.
num_excludes The number of excludes provided.
Definition at line 885 of file param_shmem.c.
References _param_notify_changes(), handle_in_range(), name, param_wbuf_s::param, param_name(), and param_reset().
int param_save_default (void)
Save parameters to the default file.
Note: this method requires a large amount of stack size!
This function saves all parameters with non-default values.
Returns
Zero on success.
Definition at line 935 of file param_shmem.c.
References fd, flash_param_save(), OK, PARAM_CLOSE, param_export(), param_get_default_file(), param_lock_writer(), PARAM_OPEN, param_unlock_writer(), PX4_DEBUG, PX4_ERR, PX4_ERROR, and PX4_OK.
Referenced by autosave_worker().
int param_set (param_t param, const void * val)
Set the value of a parameter.
Parameters
param A handle returned by param_find or passed by param_foreach.
val The value to set; assumed to point to a variable of the parameter type. For structures, the pointer is assumed to point to a structure to be copied.
Returns
Zero if the parameter's value could be set from a scalar, nonzero otherwise.
Definition at line 781 of file param_shmem.c.
References param_set_internal().
int param_set_default_file (const char * filename)
Set the default parameter file name.
Parameters
filename Path to the default parameter file. The file is not require to exist.
Returns
Zero on success.
Definition at line 913 of file param_shmem.c.
References param_user_file.
static int param_set_internal (param_t param, const void * val, bool mark_saved, bool notify_changes) static
Definition at line 662 of file param_shmem.c.
References _param_notify_changes(), debug, f(), param_value_u::f, handle_in_range(), param_value_u::i, param_value_u::p, param_wbuf_s::param, param_autosave(), param_compare_values(), param_find_changed(), param_import_done, param_lock(), param_name(), param_size(), param_type(), PARAM_TYPE_FLOAT, PARAM_TYPE_INT32, PARAM_TYPE_STRUCT, PARAM_TYPE_STRUCT_MAX, param_unlock(), PX4_DEBUG, PX4_INFO, set_called_from_get, param_wbuf_s::unsaved, update_to_shmem(), utarray_new, utarray_push_back, utarray_sort, and param_wbuf_s::val.
Referenced by param_get(), param_import_callback(), param_set(), and param_set_no_notification().
int param_set_no_notification (param_t param, const void * val)
Set the value of a parameter, but do not notify the system about the change.
Parameters
param A handle returned by param_find or passed by param_foreach.
val The value to set; assumed to point to a variable of the parameter type. For structures, the pointer is assumed to point to a structure to be copied.
Returns
Zero if the parameter's value could be set from a scalar, nonzero otherwise.
Definition at line 787 of file param_shmem.c.
References param_set_internal().
void param_set_used (param_t param)
Mark a parameter as used.
Only marked parameters will be sent to a GCS. A call to param_find() will mark a param as used as well.
Parameters
param A handle returned by param_find or passed by param_foreach.
Definition at line 808 of file param_shmem.c.
References param_set_used_internal().
void param_set_used_internal (param_t param) static
Definition at line 813 of file param_shmem.c.
References bits_per_allocation_unit, param_changed_storage, and param_get_index().
Referenced by param_find_internal(), and param_set_used().
size_t param_size (param_t param)
Determine the size of a parameter.
Parameters
param A handle returned by param_find or passed by param_foreach.
Returns
The size of the parameter's value.
Definition at line 480 of file param_shmem.c.
References handle_in_range(), param_type(), PARAM_TYPE_FLOAT, PARAM_TYPE_INT32, PARAM_TYPE_STRUCT, and PARAM_TYPE_STRUCT_MAX.
Referenced by param_export(), param_get(), param_import_callback(), and param_set_internal().
param_type_t param_type (param_t param)
Obtain the type of a parameter.
Parameters
param A handle returned by param_find or passed by param_foreach.
Returns
The type assigned to the parameter.
Definition at line 474 of file param_shmem.c.
References handle_in_range(), param_wbuf_s::param, PARAM_TYPE_UNKNOWN, and param_info_s::type.
Referenced by param_export(), param_get(), param_get_value_ptr(), param_import_callback(), param_set_internal(), and param_size().
static void param_unlock (void) static
unlock the parameter store
Definition at line 190 of file param_shmem.c.
Referenced by autosave_worker(), param_control_autosave(), param_export(), param_get(), param_hash_check(), param_reset(), param_reset_all_internal(), param_set_internal(), param_value_is_default(), and param_value_unsaved().
bool param_used (param_t param)
Wether a parameter is in use in the system.
Returns
True if it has been written or read
Definition at line 793 of file param_shmem.c.
References bits_per_allocation_unit, param_changed_storage, and param_get_index().
Referenced by param_foreach(), param_get_used_index(), and param_hash_check().
bool param_value_is_default (param_t param)
Test whether a parameter's value has changed from the default.
Returns
If true, the parameter's value has not been changed from the default.
Definition at line 453 of file param_shmem.c.
References param_find_changed(), param_lock(), param_lock_reader(), param_unlock(), and param_unlock_reader().
bool param_value_unsaved (param_t param)
Test whether a parameter's value has been changed but not saved.
Returns
If true, the parameter's value has not been saved.
Definition at line 463 of file param_shmem.c.
References param_find_changed(), param_lock(), param_lock_reader(), param_unlock(), param_unlock_reader(), and param_wbuf_s::unsaved.
void release_shmem_lock (const char * caller_file_name, int caller_line_number)
Referenced by param_load_default_no_notify().
int update_from_shmem (param_t param, union param_value_u * value)
Referenced by param_export(), and param_get().
void update_index_from_shmem (void)
Referenced by param_export().
void update_to_shmem (param_t param, union param_value_u value)
Referenced by param_set_internal().
Variable Documentation
bool autosave_disabled = false static
Definition at line 95 of file param_shmem.c.
Referenced by autosave_worker(), param_autosave(), and param_control_autosave().
bool autosave_scheduled = false static
Definition at line 94 of file param_shmem.c.
Referenced by autosave_worker(), param_autosave(), and param_control_autosave().
struct work_s autosave_work static
Definition at line 93 of file param_shmem.c.
Referenced by param_autosave(), and param_control_autosave().
const int bits_per_allocation_unit = (sizeof(*param_changed_storage) * 8)
Definition at line 115 of file param_shmem.c.
Referenced by get_param_info_count(), param_count_used(), param_for_used_index(), param_get_used_index(), param_set_used_internal(), and param_used().
hrt_abstime last_autosave_timestamp = 0 static
Definition at line 92 of file param_shmem.c.
Referenced by autosave_worker(), and param_autosave().
uint8_t* param_changed_storage = 0
Definition at line 113 of file param_shmem.c.
Referenced by get_param_info_count(), param_count_used(), param_for_used_index(), param_get_used_index(), param_set_used_internal(), and param_used().
const char* param_default_file = "/usr/share/data/adsp/params" static
Definition at line 76 of file param_shmem.c.
Referenced by param_get_default_file().
const UT_icd param_icd = {sizeof(struct param_wbuf_s), NULL, NULL, NULL}
array info for the modified parameters array
Definition at line 168 of file param_shmem.c.
int param_import_done static
Initial value:
=
    0
Definition at line 140 of file param_shmem.c.
Referenced by init_params(), and param_set_internal().
struct param_info_s* param_info_base = (struct param_info_s *) &px4_parameters static
Array of static parameter info.
Definition at line 100 of file param_shmem.c.
int param_instance = 0
Definition at line 131 of file param_shmem.c.
Referenced by _param_notify_changes().
orb_advert_t param_topic = NULL static
parameter update topic handle
Definition at line 171 of file param_shmem.c.
char* param_user_file = NULL static
Definition at line 78 of file param_shmem.c.
Referenced by param_get_default_file(), and param_set_default_file().
UT_array* param_values
flexible array holding modified parameter values
Definition at line 165 of file param_shmem.c.
Referenced by param_export_internal().
unsigned char set_called_from_get = 0
Definition at line 138 of file param_shmem.c.
Referenced by param_get(), and param_set_internal().
struct shmem_info* shmem_info_p
int size_param_changed_storage_bytes = 0
Definition at line 114 of file param_shmem.c.
Referenced by get_param_info_count(), param_count_used(), param_for_used_index(), and param_get_used_index().
uint64_t sync_other_current_time = 0
Definition at line 130 of file param_shmem.c.
uint64_t sync_other_prev_time = 0
Definition at line 130 of file param_shmem.c.