PX4 Firmware: MathlibTest Class Reference
MathlibTest Class Reference
Public Member Functions
virtual bool run_tests ()
Override to run your unit tests.
Public Member Functions inherited from UnitTest
UnitTest ()=default
virtual ~UnitTest ()=default
void print_results ()
Prints results from running of unit tests.
Private Member Functions
bool testVector2 ()
bool testVector3 ()
bool testVector10 ()
bool testMatrix3x3 ()
bool testMatrix10x10 ()
bool testMatrixNonsymmetric ()
bool testRotationMatrixQuaternion ()
bool testQuaternionfrom_dcm ()
bool testQuaternionfrom_euler ()
bool testQuaternionRotate ()
bool testFinite ()
Additional Inherited Members
Protected Member Functions inherited from UnitTest
virtual void _init (void)
Run before each unit test. Override to provide custom behavior.
virtual void _cleanup (void)
Run after each unit test. Override to provide custom behavior.
void _print_assert (const char *msg, const char *test, const char *file, int line)
void _print_compare (const char *msg, const char *v1_text, int v1, const char *v2_text, int v2, const char *file, int line)
Protected Attributes inherited from UnitTest
int _tests_run {0}
The number of individual unit tests run.
int _tests_failed {0}
The number of unit tests which failed.
int _tests_passed {0}
The number of unit tests which passed.
int _assertions {0}
Total number of assertions tested by all unit tests.
Detailed Description
Definition at line 65 of file test_mathlib.cpp.
Member Function Documentation
run_tests()
bool MathlibTest::run_tests () virtual
Override to run your unit tests.
Unit tests should be called using ut_run_test macro.
Returns
true: all unit tests succeeded, false: one or more unit tests failed
Implements UnitTest.
Definition at line 393 of file test_mathlib.cpp.
References UnitTest::_tests_failed, test_mathlib(), testFinite(), testMatrix3x3(), testMatrixNonsymmetric(), testQuaternionfrom_dcm(), testQuaternionfrom_euler(), testQuaternionRotate(), testRotationMatrixQuaternion(), testVector2(), testVector3(), ut_declare_test_c, and ut_run_test.
testFinite()
bool MathlibTest::testFinite () private
Definition at line 375 of file test_mathlib.cpp.
References f(), and ut_assert.
Referenced by run_tests().
testMatrix10x10()
bool MathlibTest::testMatrix10x10 () private
testMatrix3x3()
bool MathlibTest::testMatrix3x3 () private
Definition at line 145 of file test_mathlib.cpp.
References f(), matrix::Matrix< Type, M, N >::identity(), and TEST_OP.
Referenced by run_tests().
testMatrixNonsymmetric()
bool MathlibTest::testMatrixNonsymmetric () private
Definition at line 160 of file test_mathlib.cpp.
References matrix::Matrix< Type, M, N >::print(), and ut_assert.
Referenced by run_tests().
testQuaternionfrom_dcm()
bool MathlibTest::testQuaternionfrom_dcm () private
Definition at line 255 of file test_mathlib.cpp.
References matrix::Quaternion< Type >::from_dcm(), matrix::Matrix< Type, M, N >::identity(), and ut_assert.
Referenced by run_tests().
testQuaternionfrom_euler()
bool MathlibTest::testQuaternionfrom_euler () private
Definition at line 274 of file test_mathlib.cpp.
References f(), matrix::Quaternion< Type >::from_dcm(), matrix::Matrix< Type, M, N >::identity(), M_PI_F, and ut_assert.
Referenced by run_tests().
testQuaternionRotate()
bool MathlibTest::testQuaternionRotate () private
Definition at line 309 of file test_mathlib.cpp.
References matrix::Quaternion< Type >::conjugate(), f(), M_PI_F, and ut_assert.
Referenced by run_tests().
testRotationMatrixQuaternion()
bool MathlibTest::testRotationMatrixQuaternion () private
Definition at line 224 of file test_mathlib.cpp.
References M_PI_F, and ut_assert.
Referenced by run_tests().
testVector10()
bool MathlibTest::testVector10 () private
testVector2()
bool MathlibTest::testVector2 () private
Definition at line 88 of file test_mathlib.cpp.
References data, f(), TEST_OP, ut_assert_true, and matrix::Matrix< Type, M, N >::zero().
Referenced by run_tests().
testVector3()
bool MathlibTest::testVector3 () private
Definition at line 110 of file test_mathlib.cpp.
References data, f(), TEST_OP, ut_assert_true, and matrix::Matrix< Type, M, N >::zero().
Referenced by run_tests().
The documentation for this class was generated from the following file:
src/systemcmds/tests/test_mathlib.cpp