PX4 Firmware: src/lib/parameters/ParameterTest.cpp File Reference
ParameterTest.cpp File Reference
#include <px4_platform_common/module_params.h>
#include <uORB/Subscription.hpp>
#include <uORB/topics/obstacle_distance.h>
#include <uORB/uORBManager.hpp>
#include <gtest/gtest.h>
Classes
class ParameterTest
Functions
TEST_F (ParameterTest, testParamReadWrite)
TEST_F (ParameterTest, testUorbSendReceive)
Function Documentation
TEST_F() [1/2]
TEST_F (ParameterTest , testParamReadWrite)
Definition at line 51 of file ParameterTest.cpp.
References f(), param_get(), param_set(), and status.
TEST_F() [2/2]
TEST_F (ParameterTest , testUorbSendReceive)
Definition at line 81 of file ParameterTest.cpp.
References obstacle_distance_s::max_distance, obstacle_distance_s::min_distance, orb_advert_t, orb_advertise(), ORB_ID, and obstacle_distance_s::timestamp.