PX4 Firmware: battery_status Namespace Reference
battery_status Namespace Reference
Classes
struct ParameterHandles
struct Parameters
Functions
void initialize_parameter_handles (ParameterHandles &parameter_handles)
initialize ParameterHandles struct
int update_parameters (const ParameterHandles &parameter_handles, Parameters &parameters)
Read out the parameters using the handles into the parameters struct.
Function Documentation
initialize_parameter_handles()
void battery_status::initialize_parameter_handles (ParameterHandles & parameter_handles)
initialize ParameterHandles struct
Definition at line 49 of file parameters.cpp.
References battery_status::ParameterHandles::battery_a_per_v, battery_status::ParameterHandles::battery_adc_channel, battery_status::ParameterHandles::battery_current_offset, battery_status::ParameterHandles::battery_current_scaling, battery_status::ParameterHandles::battery_source, battery_status::ParameterHandles::battery_v_div, battery_status::ParameterHandles::battery_voltage_scaling, and param_find().
Referenced by BatteryStatus::BatteryStatus(), and Sensors::Sensors().
update_parameters()
int battery_status::update_parameters (const ParameterHandles & parameter_handles, Parameters & parameters)
Read out the parameters using the handles into the parameters struct.
Returns
0 on success, <0 on error
Definition at line 60 of file parameters.cpp.
References battery_status::Parameters::battery_a_per_v, battery_status::ParameterHandles::battery_a_per_v, battery_status::Parameters::battery_adc_channel, battery_status::ParameterHandles::battery_adc_channel, battery_status::Parameters::battery_current_offset, battery_status::ParameterHandles::battery_current_offset, battery_status::Parameters::battery_current_scaling, battery_status::ParameterHandles::battery_current_scaling, battery_status::Parameters::battery_source, battery_status::ParameterHandles::battery_source, battery_status::Parameters::battery_v_div, battery_status::ParameterHandles::battery_v_div, battery_status::Parameters::battery_voltage_scaling, battery_status::ParameterHandles::battery_voltage_scaling, OK, param_get(), param_set_no_notification(), and px4_arch_adc_dn_fullcount().
Referenced by Sensors::parameters_update(), and BatteryStatus::parameters_update().