PX4 Firmware: BATT_SMBUS Class Reference
BATT_SMBUS Class Reference
#include <batt_smbus.h>
Public Member Functions
BATT_SMBUS (device::Device *interface, const char *path)
Default Constructor.
virtual ~BATT_SMBUS ()
Default Destructor.
int block_read (const uint8_t cmd_code, void *data, const unsigned length)
Sends a block read command.
int block_write (const uint8_t cmd_code, void *data, const unsigned length)
Sends a block write command.
int dataflash_read (uint16_t &address, void *data)
Reads data from flash.
int dataflash_write (uint16_t &address, void *data, const unsigned length)
Writes data to flash.
uint8_t get_pec (uint8_t *buffer, const uint8_t length)
Calculates the PEC from the data.
uint16_t get_serial_number ()
Returns the SBS serial number of the battery device.
int get_startup_info ()
Read info from battery on startup.
int info ()
Prints the latest report.
virtual int init ()
Initializes the smart battery device.
int manufacture_date (void *man_date)
Gets the SBS manufacture date of the battery.
int manufacturer_name (uint8_t *manufacturer_name, const uint8_t length)
Gets the SBS manufacturer name of the battery device.
int manufacturer_read (const uint16_t cmd_code, void *data, const unsigned length)
Performs a ManufacturerBlockAccess() read command.
int manufacturer_write (const uint16_t cmd_code, void *data, const unsigned length)
Performs a ManufacturerBlockAccess() write command.
int read_word (const uint8_t cmd_code, void *data)
Sends a read-word command with cmd_code as the command.
int search_addresses ()
Search all possible slave addresses for a smart battery.
void start ()
Starts periodic reads from the battery.
void stop ()
Stops periodic reads from the battery.
int unseal ()
Unseals the battery to allow writing to restricted flash.
Public Member Functions inherited from device::CDev
CDev (const char *name, const char *devname)
Constructor.
virtual ~CDev ()
virtual int open (file_t *filep)
Handle an open of the device.
virtual int close (file_t *filep)
Handle a close of the device.
virtual ssize_t read (file_t *filep, char *buffer, size_t buflen)
Perform a read from the device.
virtual ssize_t write (file_t *filep, const char *buffer, size_t buflen)
Perform a write to the device.
virtual off_t seek (file_t *filep, off_t offset, int whence)
Perform a logical seek operation on the device.
virtual int ioctl (file_t *filep, int cmd, unsigned long arg)
Perform an ioctl operation on the device.
virtual int poll (file_t *filep, px4_pollfd_struct_t *fds, bool setup)
Perform a poll setup/teardown operation.
Public Member Functions inherited from device::Device
virtual ~Device ()=default
Destructor.
virtual int read (unsigned address, void *data, unsigned count)
Read directly from the device.
virtual int write (unsigned address, void *data, unsigned count)
Write directly to the device.
virtual int ioctl (unsigned operation, unsigned &arg)
Perform a device-specific operation.
uint8_t get_device_bus ()
Return the bus ID the device is connected to.
DeviceBusType get_device_bus_type ()
Return the bus type the device is connected to.
uint8_t get_device_address ()
Return the bus address of the device.
void set_device_address (int address)
void set_device_type (uint8_t devtype)
Set the device type.
virtual bool external ()
Protected Attributes
Device * _interface
Protected Attributes inherited from device::CDev
px4_sem_t _lock
lock to protect access to all class members (also for derived classes)
bool _pub_blocked {false}
true if publishing should be blocked
Protected Attributes inherited from device::Device
union DeviceId _device_id
device identifier information
const char * _name
driver name
bool _debug_enabled {false}
if true, debug messages are printed
Private Member Functions
void cycle ()
The loop that continually generates new reports.
BATT_SMBUS (const BATT_SMBUS &)
BATT_SMBUS operator= (const BATT_SMBUS &)
Static Private Member Functions
static void cycle_trampoline (void *arg)
Static function that is called by worker queue.
Private Attributes
work_s _work = work_s{}
battery_status_s _last_report = battery_status_s{}
orb_advert_t _batt_topic
orb_id_t _batt_orb_id
uint16_t _batt_capacity
uint16_t _batt_startup_capacity
uint16_t _cycle_count
uint16_t _serial_number
float _crit_thr
float _emergency_thr
float _low_thr
char * _manufacturer_name
Additional Inherited Members
Public Types inherited from device::Device
enum DeviceBusType { DeviceBusType_UNKNOWN = 0, DeviceBusType_I2C = 1, DeviceBusType_SPI = 2, DeviceBusType_UAVCAN = 3 }
Device bus types for DEVID.
Protected Member Functions inherited from device::CDev
virtual pollevent_t poll_state (file_t *filep)
Check the current state of the device for poll events from the perspective of the file.
virtual void poll_notify (pollevent_t events)
Report new poll events.
virtual void poll_notify_one (px4_pollfd_struct_t *fds, pollevent_t events)
Internal implementation of poll_notify.
virtual int open_first (file_t *filep)
Notification of the first open.
virtual int close_last (file_t *filep)
Notification of the last close.
virtual int register_class_devname (const char *class_devname)
Register a class device name, automatically adding device class instance suffix if need be.
virtual int unregister_class_devname (const char *class_devname, unsigned class_instance)
Register a class device name, automatically adding device class instance suffix if need be.
const char * get_devname ()
Get the device name.
void lock ()
Take the driver lock.
void unlock ()
Release the driver lock.
Protected Member Functions inherited from device::Device
Device (const char *name)
Device (DeviceBusType bus_type, uint8_t bus, uint8_t address, uint8_t devtype=0)
Device (const Device &)=delete
Device & operator= (const Device &)=delete
Device (Device &&)=delete
Device & operator= (Device &&)=delete
Static Protected Attributes inherited from device::CDev
static const px4_file_operations_t fops = {}
Pointer to the default cdev file operations table; useful for registering clone devices etc.
Detailed Description
Definition at line 122 of file batt_smbus.h.
Constructor & Destructor Documentation
BATT_SMBUS::BATT_SMBUS (device::Device * interface, const char * path)
Default Constructor.
Parameters
interface The device communication interface (i2c)
path The device i2c address
Definition at line 50 of file batt_smbus.cpp.
References device::Device::_device_id, _interface, device::Device::DeviceStructure::address, device::Device::DeviceStructure::bus, device::Device::DeviceStructure::bus_type, and device::Device::DeviceId::devid_s.
BATT_SMBUS::~BATT_SMBUS () virtual
Default Destructor.
Definition at line 70 of file batt_smbus.cpp.
References _manufacturer_name, param_find(), param_set(), PX4_WARN, and stop().
BATT_SMBUS::BATT_SMBUS (const BATT_SMBUS &) private
Member Function Documentation
int BATT_SMBUS::block_read (const uint8_t cmd_code, void * data, const unsigned length)
Sends a block read command.
Parameters
cmd_code The command code.
data The returned data.
length The number of bytes being read
Returns
Returns PX4_OK on success, PX4_ERROR on failure.
Definition at line 85 of file batt_smbus.cpp.
References _interface, BATT_SMBUS_MANUFACTURER_BLOCK_ACCESS, DATA_BUFFER_SIZE, device::Device::get_device_address(), get_pec(), PX4_ERROR, PX4_INFO, and PX4_OK.
Referenced by batt_smbus_main(), dataflash_read(), manufacturer_name(), and manufacturer_read().
int BATT_SMBUS::block_write (const uint8_t cmd_code, void * data, const unsigned length)
Sends a block write command.
Parameters
cmd_code The command code.
data The data to be written.
length The number of bytes being written.
Returns
Returns PX4_OK on success, PX4_ERROR on failure.
Definition at line 132 of file batt_smbus.cpp.
References _interface, get_pec(), PX4_ERROR, PX4_OK, PX4_WARN, and usleep().
Referenced by batt_smbus_main(), dataflash_read(), dataflash_write(), manufacturer_read(), and manufacturer_write().
void BATT_SMBUS::cycle () private
The loop that continually generates new reports.
Definition at line 161 of file batt_smbus.cpp.
References _batt_capacity, _batt_orb_id, _batt_startup_capacity, _batt_topic, _crit_thr, _cycle_count, _emergency_thr, _last_report, _low_thr, _serial_number, battery_status_s::average_current_a, battery_status_s::average_time_to_empty, BATT_SMBUS_AVERAGE_CURRENT, BATT_SMBUS_AVERAGE_TIME_TO_EMPTY, BATT_SMBUS_CURRENT, BATT_SMBUS_MEASUREMENT_INTERVAL_US, BATT_SMBUS_REMAINING_CAPACITY, BATT_SMBUS_RUN_TIME_TO_EMPTY, BATT_SMBUS_TEMP, BATT_SMBUS_VOLTAGE, battery_status_s::capacity, battery_status_s::connected, CONSTANTS_ABSOLUTE_NULL_CELSIUS, battery_status_s::current_a, battery_status_s::current_filtered_a, battery_status_s::cycle_count, cycle_trampoline(), battery_status_s::discharged_mah, f(), hrt_absolute_time(), orb_advertise(), orb_publish(), PX4_ERR, PX4_INFO, PX4_OK, PX4_WARN, read_word(), battery_status_s::remaining, battery_status_s::run_time_to_empty, battery_status_s::serial_number, battery_status_s::temperature, battery_status_s::timestamp, battery_status_s::voltage_filtered_v, battery_status_s::voltage_v, and battery_status_s::warning.
Referenced by cycle_trampoline().
void BATT_SMBUS::cycle_trampoline (void * arg) static private
Static function that is called by worker queue.
Definition at line 310 of file batt_smbus.cpp.
References cycle().
Referenced by cycle(), and start().
int BATT_SMBUS::dataflash_read (uint16_t & address, void * data)
Reads data from flash.
Parameters
address The address to start the read from.
data The returned data.
Returns
Returns PX4_OK on success, PX4_ERROR on failure.
Definition at line 316 of file batt_smbus.cpp.
References BATT_SMBUS_MANUFACTURER_BLOCK_ACCESS, block_read(), block_write(), DATA_BUFFER_SIZE, PX4_INFO, and PX4_OK.
Referenced by batt_smbus_main().
int BATT_SMBUS::dataflash_write (uint16_t & address, void * data, const unsigned length)
Writes data to flash.
Parameters
address The start address of the write.
data The data to be written.
length The number of bytes being written.
Returns
Returns PX4_OK on success, PX4_ERROR on failure.
Definition at line 334 of file batt_smbus.cpp.
References BATT_SMBUS_MANUFACTURER_BLOCK_ACCESS, block_write(), DATA_BUFFER_SIZE, PX4_OK, and tx_buf.
Referenced by batt_smbus_main().
uint8_t BATT_SMBUS::get_pec (uint8_t * buffer, const uint8_t length)
Calculates the PEC from the data.
Parameters
buff The buffer that stores the data.
length The number of bytes being written.
Returns
Returns PX4_OK on success, PX4_ERROR on failure.
Definition at line 351 of file batt_smbus.cpp.
References BATT_SMBUS_PEC_POLYNOMIAL.
Referenced by block_read(), block_write(), and read_word().
uint16_t BATT_SMBUS::get_serial_number ()
Returns the SBS serial number of the battery device.
Returns
Returns the SBS serial number of the battery device.
Definition at line 432 of file batt_smbus.cpp.
References BATT_SMBUS_SERIAL_NUMBER, PX4_ERROR, PX4_OK, and read_word().
Referenced by batt_smbus::serial_number().
int BATT_SMBUS::get_startup_info ()
Read info from battery on startup.
Returns
Returns PX4_OK on success, PX4_ERROR on failure.
Definition at line 378 of file batt_smbus.cpp.
References _batt_capacity, _batt_startup_capacity, _crit_thr, _cycle_count, _emergency_thr, _low_thr, _manufacturer_name, _serial_number, BATT_SMBUS_CYCLE_COUNT, BATT_SMBUS_FULL_CHARGE_CAPACITY, BATT_SMBUS_REMAINING_CAPACITY, BATT_SMBUS_SERIAL_NUMBER, manufacturer_name(), param_find(), param_get(), PX4_ERROR, PX4_OK, PX4_WARN, and read_word().
Referenced by init().
int BATT_SMBUS::info ()
Prints the latest report.
Returns
Returns PX4_OK on success, PX4_ERROR on failure.
Definition at line 443 of file batt_smbus.cpp.
References _last_report, and PX4_OK.
Referenced by batt_smbus_main().
int BATT_SMBUS::init () virtual
Initializes the smart battery device.
Calls probe() to check for device on bus.
Returns
Returns PX4_OK on success, PX4_ERROR on failure.
Reimplemented from device::CDev.
Definition at line 449 of file batt_smbus.cpp.
References _batt_orb_id, get_startup_info(), lis3mdl::init(), ORB_ID, PX4_ERR, PX4_ERROR, PX4_OK, search_addresses(), and start().
int BATT_SMBUS::manufacture_date (void * man_date)
Gets the SBS manufacture date of the battery.
Returns
Returns PX4_OK on success, PX4_ERROR on failure.
Definition at line 483 of file batt_smbus.cpp.
References BATT_SMBUS_MANUFACTURE_DATE, PX4_ERROR, PX4_OK, PX4_WARN, and read_word().
Referenced by batt_smbus::manufacture_date().
int BATT_SMBUS::manufacturer_name (uint8_t * manufacturer_name, const uint8_t length)
Gets the SBS manufacturer name of the battery device.
Parameters
manufacturer_name Pointer to a buffer into which the manufacturer name is to be written.
max_length The maximum number of bytes to attempt to read from the manufacturer name register, including the null character that is appended to the end.
Returns
Returns PX4_OK on success, PX4_ERROR on failure.
Definition at line 497 of file batt_smbus.cpp.
References BATT_SMBUS_MANUFACTURER_NAME, block_read(), PX4_ERROR, PX4_OK, PX4_WARN, and rx_buf.
Referenced by get_startup_info(), and batt_smbus::manufacturer_name().
int BATT_SMBUS::manufacturer_read (const uint16_t cmd_code, void * data, const unsigned length)
Performs a ManufacturerBlockAccess() read command.
Parameters
cmd_code The command code.
data The returned data.
length The number of bytes being written.
Returns
Returns PX4_OK on success, PX4_ERROR on failure.
Definition at line 517 of file batt_smbus.cpp.
References BATT_SMBUS_MANUFACTURER_BLOCK_ACCESS, block_read(), block_write(), DATA_BUFFER_SIZE, PX4_INFO, PX4_OK, and rx_buf.
Referenced by batt_smbus_main().
int BATT_SMBUS::manufacturer_write (const uint16_t cmd_code, void * data, const unsigned length)
Performs a ManufacturerBlockAccess() write command.
Parameters
cmd_code The command code.
data The sent data.
length The number of bytes being written.
Returns
Returns PX4_OK on success, PX4_ERROR on failure.
Definition at line 539 of file batt_smbus.cpp.
References BATT_SMBUS_MANUFACTURER_BLOCK_ACCESS, block_write(), DATA_BUFFER_SIZE, PX4_OK, and tx_buf.
Referenced by unseal().
BATT_SMBUS BATT_SMBUS::operator= (const BATT_SMBUS &) private
int BATT_SMBUS::read_word (const uint8_t cmd_code, void * data)
Sends a read-word command with cmd_code as the command.
Parameters
cmd_code The command code.
data The returned data.
Returns
Returns PX4_OK on success, PX4_ERROR on failure.
Definition at line 556 of file batt_smbus.cpp.
References _interface, device::Device::get_device_address(), get_pec(), PX4_ERROR, and PX4_OK.
Referenced by batt_smbus_main(), cycle(), get_serial_number(), get_startup_info(), manufacture_date(), and search_addresses().
int BATT_SMBUS::search_addresses ()
Search all possible slave addresses for a smart battery.
Returns
Returns PX4_OK on success, PX4_ERROR on failure.
Definition at line 583 of file batt_smbus.cpp.
References BATT_SMBUS_ADDR, BATT_SMBUS_ADDR_MAX, BATT_SMBUS_ADDR_MIN, BATT_SMBUS_VOLTAGE, device::Device::get_device_address(), PX4_ERROR, PX4_INFO, PX4_OK, PX4_WARN, read_word(), and device::Device::set_device_address().
Referenced by init().
void BATT_SMBUS::start ()
Starts periodic reads from the battery.
Definition at line 613 of file batt_smbus.cpp.
References cycle_trampoline().
Referenced by batt_smbus_main(), and init().
void BATT_SMBUS::stop ()
Stops periodic reads from the battery.
Definition at line 619 of file batt_smbus.cpp.
Referenced by batt_smbus_main(), and ~BATT_SMBUS().
int BATT_SMBUS::unseal ()
Unseals the battery to allow writing to restricted flash.
Returns
Returns PX4_OK on success, PX4_ERROR on failure.
Definition at line 625 of file batt_smbus.cpp.
References manufacturer_write(), PX4_ERROR, PX4_INFO, and PX4_OK.
Referenced by batt_smbus_main().
Member Data Documentation
uint16_t BATT_SMBUS::_batt_capacity private
Parameters
_batt_capacity Battery design capacity in mAh (0 means unknown).
Definition at line 296 of file batt_smbus.h.
Referenced by cycle(), and get_startup_info().
orb_id_t BATT_SMBUS::_batt_orb_id private
Parameters
_batt_orb_id uORB battery topic ID.
Definition at line 293 of file batt_smbus.h.
Referenced by cycle(), and init().
uint16_t BATT_SMBUS::_batt_startup_capacity private
Parameters
_batt_startup_capacity Battery remaining capacity in mAh on startup.
Definition at line 299 of file batt_smbus.h.
Referenced by cycle(), and get_startup_info().
orb_advert_t BATT_SMBUS::_batt_topic private
Parameters
_batt_topic uORB battery topic.
Definition at line 290 of file batt_smbus.h.
Referenced by cycle().
float BATT_SMBUS::_crit_thr private
Parameters
_crit_thr Critical battery threshold param.
Definition at line 308 of file batt_smbus.h.
Referenced by cycle(), and get_startup_info().
uint16_t BATT_SMBUS::_cycle_count private
Parameters
_cycle_count The number of cycles the battery has experienced.
Definition at line 302 of file batt_smbus.h.
Referenced by cycle(), and get_startup_info().
float BATT_SMBUS::_emergency_thr private
Parameters
_emergency_thr Emergency battery threshold param.
Definition at line 311 of file batt_smbus.h.
Referenced by cycle(), and get_startup_info().
Device* BATT_SMBUS::_interface protected
Definition at line 269 of file batt_smbus.h.
Referenced by BATT_SMBUS(), block_read(), block_write(), and read_word().
battery_status_s BATT_SMBUS::_last_report = battery_status_s{} private
Parameters
_last_report Last published report, used for test().
Definition at line 287 of file batt_smbus.h.
Referenced by cycle(), and info().
float BATT_SMBUS::_low_thr private
Parameters
_low_thr Low battery threshold param.
Definition at line 314 of file batt_smbus.h.
Referenced by cycle(), and get_startup_info().
char* BATT_SMBUS::_manufacturer_name private
Parameters
_manufacturer_name Name of the battery manufacturer.
Definition at line 317 of file batt_smbus.h.
Referenced by get_startup_info(), and ~BATT_SMBUS().
uint16_t BATT_SMBUS::_serial_number private
Parameters
_serial_number Serial number register.
Definition at line 305 of file batt_smbus.h.
Referenced by cycle(), and get_startup_info().
work_s BATT_SMBUS::_work = work_s{} private
Definition at line 284 of file batt_smbus.h.
The documentation for this class was generated from the following files:
src/drivers/batt_smbus/batt_smbus.h
src/drivers/batt_smbus/batt_smbus.cpp