PX4 Firmware: FollowTarget Class Reference
FollowTarget Class Reference
#include <follow_target.h>
Public Member Functions
FollowTarget (Navigator *navigator)
~FollowTarget ()=default
void on_inactive () override
This function is called while the mode is inactive.
void on_activation () override
This function is called one time when mode becomes active, pos_sp_triplet must be initialized here.
void on_active () override
This function is called while the mode is active.
Public Member Functions inherited from MissionBlock
MissionBlock (Navigator *navigator)
Constructor.
virtual ~MissionBlock ()=default
MissionBlock (const MissionBlock &)=delete
MissionBlock & operator= (const MissionBlock &)=delete
Public Member Functions inherited from NavigatorMode
NavigatorMode (Navigator *navigator)
virtual ~NavigatorMode ()=default
NavigatorMode (const NavigatorMode &)=delete
NavigatorMode operator= (const NavigatorMode &)=delete
void run (bool active)
virtual void on_inactivation ()
This function is called one time when mode becomes inactive.
Public Member Functions inherited from ModuleParams
ModuleParams (ModuleParams *parent)
void setParent (ModuleParams *parent)
Set the parent module.
virtual ~ModuleParams ()=default
ModuleParams (const ModuleParams &)=delete
ModuleParams & operator= (const ModuleParams &)=delete
ModuleParams (ModuleParams &&)=delete
ModuleParams & operator= (ModuleParams &&)=delete
Public Member Functions inherited from ListNode< ModuleParams * >
ListNode ()
ListNode (const ListNode &)=delete
ListNode (ListNode &&)=delete
virtual ~ListNode ()=default
ListNode & operator= (const ListNode &)=delete
ListNode & operator= (ListNode &&)=delete
void setSibling (ModuleParams *sibling)
const ModuleParams * getSibling ()
Private Types
enum FollowTargetState { TRACK_POSITION, TRACK_VELOCITY, SET_WAIT_FOR_TARGET_POSITION, WAIT_FOR_TARGET_POSITION }
enum { FOLLOW_FROM_RIGHT, FOLLOW_FROM_BEHIND, FOLLOW_FROM_FRONT, FOLLOW_FROM_LEFT }
enum { POS = 0, VEL = 1, ACCEL = 2, ATT_RATES = 3 }
Private Member Functions
DEFINE_PARAMETERS ((ParamFloat< px4::params::NAV_MIN_FT_HT >) _param_min_alt,(ParamFloat< px4::params::NAV_FT_DST >) _param_tracking_dist,(ParamInt< px4::params::NAV_FT_FS >) _param_tracking_side,(ParamFloat< px4::params::NAV_FT_RS >) _param_tracking_resp) FollowTargetState _follow_target_state
void track_target_position ()
void track_target_velocity ()
bool target_velocity_valid ()
bool target_position_valid ()
void reset_target_validity ()
void update_position_sp (bool velocity_valid, bool position_valid, float yaw_rate)
void update_target_motion ()
void update_target_velocity ()
void set_follow_target_item (struct mission_item_s *item, float min_clearance, follow_target_s &target, float yaw)
Set follow_target item.
Private Attributes
int _follow_target_position {FOLLOW_FROM_BEHIND}
int _follow_target_sub {-1}
float _step_time_in_ms {0.0f}
float _follow_offset {OFFSET_M}
uint64_t _target_updates {0}
uint64_t _last_update_time {0}
matrix::Vector3f _current_vel
matrix::Vector3f _step_vel
matrix::Vector3f _est_target_vel
matrix::Vector3f _target_distance
matrix::Vector3f _target_position_offset
matrix::Vector3f _target_position_delta
matrix::Vector3f _filtered_target_position_delta
follow_target_s _current_target_motion {}
follow_target_s _previous_target_motion {}
float _yaw_rate {0.0f}
float _responsiveness {0.0f}
float _yaw_angle {0.0f}
matrix::Dcmf _rot_matrix
Static Private Attributes
static constexpr int TARGET_TIMEOUT_MS = 2500
static constexpr int TARGET_ACCEPTANCE_RADIUS_M = 5
static constexpr int INTERPOLATION_PNTS = 20
static constexpr float FF_K = .25F
static constexpr float OFFSET_M = 8
static constexpr float _follow_position_matricies [4][9]
Additional Inherited Members
Static Public Member Functions inherited from MissionBlock
static bool item_contains_position (const mission_item_s &item)
Protected Member Functions inherited from MissionBlock
bool is_mission_item_reached ()
Check if mission item has been reached.
void reset_mission_item_reached ()
Reset all reached flags.
bool mission_item_to_position_setpoint (const mission_item_s &item, position_setpoint_s *sp)
Convert a mission item to a position setpoint.
void set_loiter_item (struct mission_item_s *item, float min_clearance=-1.0f)
Set a loiter mission item, if possible reuse the position setpoint, otherwise take the current position.
void set_takeoff_item (struct mission_item_s *item, float abs_altitude, float min_pitch=0.0f)
Set a takeoff mission item.
void set_land_item (struct mission_item_s *item, bool at_current_location)
Set a land mission item.
void set_idle_item (struct mission_item_s *item)
Set idle mission item.
void set_vtol_transition_item (struct mission_item_s *item, const uint8_t new_mode)
Set vtol transition item.
void mission_apply_limitation (mission_item_s &item)
General function used to adjust the mission item based on vehicle specific limitations.
void issue_command (const mission_item_s &item)
float get_time_inside (const struct mission_item_s &item)
float get_absolute_altitude_for_item (struct mission_item_s &mission_item) const
Protected Member Functions inherited from ModuleParams
virtual void updateParams ()
Call this whenever the module gets a parameter change notification.
virtual void updateParamsImpl ()
The implementation for this is generated with the macro DEFINE_PARAMETERS()
Protected Attributes inherited from MissionBlock
mission_item_s _mission_item {}
bool _waypoint_position_reached {false}
bool _waypoint_yaw_reached {false}
hrt_abstime _time_first_inside_orbit {0}
hrt_abstime _action_start {0}
hrt_abstime _time_wp_reached {0}
orb_advert_t _actuator_pub {nullptr}
Protected Attributes inherited from NavigatorMode
Navigator * _navigator {nullptr}
Protected Attributes inherited from ListNode< ModuleParams * >
ModuleParams * _sibling
Detailed Description
Definition at line 52 of file follow_target.h.
Member Enumeration Documentation
anonymous enum private
Enumerator
FOLLOW_FROM_RIGHT
FOLLOW_FROM_BEHIND
FOLLOW_FROM_FRONT
FOLLOW_FROM_LEFT
Definition at line 78 of file follow_target.h.
anonymous enum private
Enumerator
POS
VEL
ACCEL
ATT_RATES
Definition at line 125 of file follow_target.h.
enum FollowTarget::FollowTargetState private
Enumerator
TRACK_POSITION
TRACK_VELOCITY
SET_WAIT_FOR_TARGET_POSITION
WAIT_FOR_TARGET_POSITION
Definition at line 71 of file follow_target.h.
Constructor & Destructor Documentation
FollowTarget::FollowTarget (Navigator * navigator)
Definition at line 63 of file follow_target.cpp.
References _current_vel, _est_target_vel, _step_vel, _target_distance, _target_position_delta, _target_position_offset, and matrix::Matrix< Type, M, N >::zero().
FollowTarget::~FollowTarget () default
Member Function Documentation
FollowTarget::DEFINE_PARAMETERS ((ParamFloat< px4::params::NAV_MIN_FT_HT >) _param_min_alt, (ParamFloat< px4::params::NAV_FT_DST >) _param_tracking_dist, (ParamInt< px4::params::NAV_FT_FS >) _param_tracking_side, (ParamFloat< px4::params::NAV_FT_RS >) _param_tracking_resp) inline private
Definition at line 92 of file follow_target.h.
References SET_WAIT_FOR_TARGET_POSITION.
void FollowTarget::on_activation () override virtual
This function is called one time when mode becomes active, pos_sp_triplet must be initialized here.
Reimplemented from NavigatorMode.
Definition at line 80 of file follow_target.cpp.
References _follow_offset, _follow_position_matricies, _follow_target_position, _follow_target_sub, _responsiveness, _rot_matrix, math::constrain(), FOLLOW_FROM_BEHIND, FOLLOW_FROM_LEFT, FOLLOW_FROM_RIGHT, follow_target, ORB_ID, and orb_subscribe().
void FollowTarget::on_active () override virtual
This function is called while the mode is active.
Reimplemented from NavigatorMode.
Definition at line 99 of file follow_target.cpp.
References _current_target_motion, _current_vel, _est_target_vel, _follow_offset, _follow_target_sub, _last_update_time, MissionBlock::_mission_item, NavigatorMode::_navigator, _previous_target_motion, _responsiveness, _rot_matrix, _step_time_in_ms, _step_vel, _target_distance, _target_position_delta, _target_position_offset, _target_updates, _yaw_angle, _yaw_rate, follow_target_s::alt, f(), FF_K, follow_target, get_bearing_to_next_waypoint(), Navigator::get_global_position(), hrt_absolute_time(), INTERPOLATION_PNTS, MissionBlock::is_mission_item_reached(), vehicle_global_position_s::lat, follow_target_s::lat, matrix::Vector< Type, M >::length(), follow_target_s::lon, vehicle_global_position_s::lon, map_projection_init(), map_projection_project(), map_projection_reproject(), matrix::Vector3< Type >::normalized(), orb_check(), orb_copy(), ORB_ID, math::radians(), reset_target_validity(), set_follow_target_item(), SET_WAIT_FOR_TARGET_POSITION, TARGET_ACCEPTANCE_RADIUS_M, target_position_valid(), TARGET_TIMEOUT_MS, target_velocity_valid(), follow_target_s::timestamp, TRACK_POSITION, TRACK_VELOCITY, update_position_sp(), WAIT_FOR_TARGET_POSITION, matrix::wrap_pi(), and vehicle_global_position_s::yaw.
void FollowTarget::on_inactive () override virtual
This function is called while the mode is inactive.
Reimplemented from NavigatorMode.
Definition at line 75 of file follow_target.cpp.
References reset_target_validity().
void FollowTarget::reset_target_validity () private
Definition at line 346 of file follow_target.cpp.
References _current_target_motion, _current_vel, _est_target_vel, _previous_target_motion, _step_vel, _target_distance, _target_position_offset, _target_updates, _yaw_rate, MissionBlock::reset_mission_item_reached(), SET_WAIT_FOR_TARGET_POSITION, and matrix::Matrix< Type, M, N >::zero().
Referenced by on_active(), and on_inactive().
void FollowTarget::set_follow_target_item (struct mission_item_s * item, float min_clearance, follow_target_s & target, float yaw) private
Set follow_target item.
Definition at line 374 of file follow_target.cpp.
References NavigatorMode::_navigator, mission_item_s::acceptance_radius, home_position_s::alt, mission_item_s::altitude, mission_item_s::altitude_is_relative, mission_item_s::autocontinue, f(), Navigator::get_acceptance_radius(), Navigator::get_home_position(), Navigator::get_land_detected(), Navigator::get_loiter_radius(), vehicle_land_detected_s::landed, follow_target_s::lat, mission_item_s::lat, mission_item_s::loiter_radius, follow_target_s::lon, mission_item_s::lon, mission_item_s::nav_cmd, NAV_CMD_DO_FOLLOW_REPOSITION, NAV_CMD_IDLE, mission_item_s::origin, ORIGIN_ONBOARD, mission_item_s::time_inside, and mission_item_s::yaw.
Referenced by on_active().
bool FollowTarget::target_position_valid () private
Definition at line 367 of file follow_target.cpp.
References _target_updates.
Referenced by on_active().
bool FollowTarget::target_velocity_valid () private
Definition at line 361 of file follow_target.cpp.
References _target_updates.
Referenced by on_active().
void FollowTarget::track_target_position () private
void FollowTarget::track_target_velocity () private
void FollowTarget::update_position_sp (bool velocity_valid, bool position_valid, float yaw_rate) private
Definition at line 323 of file follow_target.cpp.
References _current_vel, MissionBlock::_mission_item, NavigatorMode::_navigator, position_setpoint_triplet_s::current, Navigator::get_position_setpoint_triplet(), MissionBlock::mission_apply_limitation(), MissionBlock::mission_item_to_position_setpoint(), position_setpoint_triplet_s::next, position_setpoint_s::position_valid, position_setpoint_triplet_s::previous, Navigator::set_position_setpoint_triplet_updated(), position_setpoint_s::type, position_setpoint_s::valid, position_setpoint_s::velocity_valid, position_setpoint_s::vx, position_setpoint_s::vy, position_setpoint_s::yawspeed, and position_setpoint_s::yawspeed_valid.
Referenced by on_active().
void FollowTarget::update_target_motion () private
void FollowTarget::update_target_velocity () private
Member Data Documentation
follow_target_s FollowTarget::_current_target_motion {} private
Definition at line 117 of file follow_target.h.
Referenced by on_active(), and reset_target_validity().
matrix::Vector3f FollowTarget::_current_vel private
Definition at line 109 of file follow_target.h.
Referenced by FollowTarget(), on_active(), reset_target_validity(), and update_position_sp().
matrix::Vector3f FollowTarget::_est_target_vel private
Definition at line 111 of file follow_target.h.
Referenced by FollowTarget(), on_active(), and reset_target_validity().
matrix::Vector3f FollowTarget::_filtered_target_position_delta private
Definition at line 115 of file follow_target.h.
float FollowTarget::_follow_offset {OFFSET_M} private
Definition at line 104 of file follow_target.h.
Referenced by on_activation(), and on_active().
constexpr float FollowTarget::_follow_position_matricies static private
Initial value:
= {
        { 1.0F, -1.0F, 0.0F,  1.0F,  1.0F, 0.0F, 0.0F, 0.0F, 1.0F},
        {-1.0F,  0.0F, 0.0F,  0.0F, -1.0F, 0.0F, 0.0F, 0.0F, 1.0F},
        { 1.0F,  0.0F, 0.0F,  0.0F,  1.0F, 0.0F, 0.0F, 0.0F, 1.0F},
        { 1.0F,  1.0F, 0.0F, -1.0F,  1.0F, 0.0F, 0.0F, 0.0F, 1.0F}
    }
Definition at line 85 of file follow_target.h.
Referenced by on_activation().
int FollowTarget::_follow_target_position {FOLLOW_FROM_BEHIND} private
Definition at line 100 of file follow_target.h.
Referenced by on_activation().
int FollowTarget::_follow_target_sub {-1} private
Definition at line 102 of file follow_target.h.
Referenced by on_activation(), and on_active().
uint64_t FollowTarget::_last_update_time {0} private
Definition at line 107 of file follow_target.h.
Referenced by on_active().
follow_target_s FollowTarget::_previous_target_motion {} private
Definition at line 118 of file follow_target.h.
Referenced by on_active(), and reset_target_validity().
float FollowTarget::_responsiveness {0.0f} private
Definition at line 121 of file follow_target.h.
Referenced by on_activation(), and on_active().
matrix::Dcmf FollowTarget::_rot_matrix private
Definition at line 132 of file follow_target.h.
Referenced by on_activation(), and on_active().
float FollowTarget::_step_time_in_ms {0.0f} private
Definition at line 103 of file follow_target.h.
Referenced by on_active().
matrix::Vector3f FollowTarget::_step_vel private
Definition at line 110 of file follow_target.h.
Referenced by FollowTarget(), on_active(), and reset_target_validity().
matrix::Vector3f FollowTarget::_target_distance private
Definition at line 112 of file follow_target.h.
Referenced by FollowTarget(), on_active(), and reset_target_validity().
matrix::Vector3f FollowTarget::_target_position_delta private
Definition at line 114 of file follow_target.h.
Referenced by FollowTarget(), and on_active().
matrix::Vector3f FollowTarget::_target_position_offset private
Definition at line 113 of file follow_target.h.
Referenced by FollowTarget(), on_active(), and reset_target_validity().
uint64_t FollowTarget::_target_updates {0} private
Definition at line 106 of file follow_target.h.
Referenced by on_active(), reset_target_validity(), target_position_valid(), and target_velocity_valid().
float FollowTarget::_yaw_angle {0.0f} private
Definition at line 122 of file follow_target.h.
Referenced by on_active().
float FollowTarget::_yaw_rate {0.0f} private
Definition at line 120 of file follow_target.h.
Referenced by on_active(), and reset_target_validity().
constexpr float FollowTarget::FF_K = .25F static private
Definition at line 68 of file follow_target.h.
Referenced by on_active().
constexpr int FollowTarget::INTERPOLATION_PNTS = 20 static private
Definition at line 67 of file follow_target.h.
Referenced by on_active().
constexpr float FollowTarget::OFFSET_M = 8 static private
Definition at line 69 of file follow_target.h.
constexpr int FollowTarget::TARGET_ACCEPTANCE_RADIUS_M = 5 static private
Definition at line 66 of file follow_target.h.
Referenced by on_active().
constexpr int FollowTarget::TARGET_TIMEOUT_MS = 2500 static private
Definition at line 65 of file follow_target.h.
Referenced by on_active().
The documentation for this class was generated from the following files:
src/modules/navigator/follow_target.h
src/modules/navigator/follow_target.cpp