PX4 Firmware: batt_smbus Namespace Reference
batt_smbus Namespace Reference
Local functions in support of the shell command.
Classes
struct batt_smbus_bus_option
Functions
int start (enum BATT_SMBUS_BUS busid)
Start the driver.
bool start_bus (struct batt_smbus_bus_option &bus)
start driver for a specific bus option
struct batt_smbus_bus_option & find_bus (enum BATT_SMBUS_BUS busid)
Find a bus structure for a busid.
int reset (enum BATT_SMBUS_BUS busid)
int info ()
Print a little info about the driver.
void usage (const char *reason)
int manufacture_date ()
Nuttshell accessible method to return the battery manufacture date.
int manufacturer_name ()
Nuttshell accessible method to return the battery manufacturer name.
int serial_number ()
Nuttshell accessible method to return the battery serial number.
Variables
struct batt_smbus::batt_smbus_bus_option bus_options []
Detailed Description
Local functions in support of the shell command.
Function Documentation
struct batt_smbus_bus_option & batt_smbus::find_bus (enum BATT_SMBUS_BUS busid)
Find a bus structure for a busid.
Definition at line 144 of file batt_smbus_main.cpp.
References BATT_SMBUS_BUS_ALL, bus_options, batt_smbus::batt_smbus_bus_option::dev, errx, and NUM_BUS_OPTIONS.
Referenced by batt_smbus_main().
int batt_smbus::info ()
Print a little info about the driver.
Print a little info about the driver.
Definition at line 820 of file bmp280.cpp.
int batt_smbus::manufacture_date ()
Nuttshell accessible method to return the battery manufacture date.
Returns
Returns PX4_OK on success, PX4_ERROR on failure.
Definition at line 160 of file batt_smbus_main.cpp.
References bus_options, batt_smbus::batt_smbus_bus_option::dev, batt_smbus::batt_smbus_bus_option::devpath, BATT_SMBUS::manufacture_date(), NUM_BUS_OPTIONS, PX4_ERROR, PX4_INFO, PX4_OK, and PX4_WARN.
Referenced by batt_smbus_main().
int batt_smbus::manufacturer_name ()
Nuttshell accessible method to return the battery manufacturer name.
Returns
Returns PX4_OK on success, PX4_ERROR on failure.
Definition at line 189 of file batt_smbus_main.cpp.
References bus_options, batt_smbus::batt_smbus_bus_option::dev, batt_smbus::batt_smbus_bus_option::devpath, BATT_SMBUS::manufacturer_name(), NUM_BUS_OPTIONS, PX4_ERROR, PX4_INFO, PX4_OK, and PX4_WARN.
Referenced by batt_smbus_main().
int batt_smbus::reset (enum BATT_SMBUS_BUS busid)
int batt_smbus::serial_number ()
Nuttshell accessible method to return the battery serial number.
Returns
Returns PX4_OK on success, PX4_ERROR on failure.
Definition at line 213 of file batt_smbus_main.cpp.
References bus_options, batt_smbus::batt_smbus_bus_option::dev, batt_smbus::batt_smbus_bus_option::devpath, BATT_SMBUS::get_serial_number(), NUM_BUS_OPTIONS, PX4_INFO, and PX4_OK.
Referenced by batt_smbus_main(), and ADIS16448::probe().
int batt_smbus::start (enum BATT_SMBUS_BUS busid)
Start the driver.
This function call only returns once the driver is either successfully up and running or failed to start.
Definition at line 116 of file batt_smbus_main.cpp.
References BATT_SMBUS_BUS_ALL, bus_options, batt_smbus::batt_smbus_bus_option::dev, NUM_BUS_OPTIONS, PX4_ERROR, PX4_INFO, PX4_OK, and start_bus().
Referenced by batt_smbus_main().
bool batt_smbus::start_bus (struct batt_smbus_bus_option & bus)
start driver for a specific bus option
Definition at line 81 of file batt_smbus_main.cpp.
References batt_smbus::batt_smbus_bus_option::dev, batt_smbus::batt_smbus_bus_option::devpath, OK, PX4_INFO, PX4_OK, and PX4_WARN.
Referenced by start().
void batt_smbus::usage (const char * reason)
Definition at line 231 of file batt_smbus_main.cpp.
Referenced by batt_smbus_main().
Variable Documentation
struct batt_smbus::batt_smbus_bus_option batt_smbus::bus_options[]
Initial value:
= {
    { BATT_SMBUS_BUS_I2C_EXTERNAL, "/dev/batt_smbus_ext", &BATT_SMBUS_I2C_interface, PX4_I2C_BUS_EXPANSION, nullptr },
}
Referenced by find_bus(), manufacture_date(), manufacturer_name(), serial_number(), and start().