PX4 Firmware: control Namespace Reference
control Namespace Reference
Classes
class Block
class BlockDelay
class BlockDerivative
A simple derivative approximation.
class BlockHighPass
A high pass filter as described here: http://en.wikipedia.org/wiki/High-pass_filter.
class BlockIntegral
A rectangular integrator.
class BlockIntegralTrap
A trapezoidal integrator.
class BlockLimit
A limiter/ saturation.
class BlockLimitSym
A symmetric limiter/ saturation.
class BlockLowPass
A low pass filter as described here: http://en.wikipedia.org/wiki/Low-pass_filter.
class BlockLowPass2
A 2nd order low pass filter block which uses the default px4 2nd order low pass filter.
class BlockLowPassVector
class BlockOutput
An output trim/ saturation block.
class BlockP
A proportional controller.
class BlockParam
class BlockParamBase
class BlockPD
A proportional-derivative controller.
class BlockPI
A proportional-integral controller.
class BlockPID
A proportional-integral-derivative controller.
class BlockRandGauss
class BlockRandUniform
A uniform random number generator.
class BlockStats
class SuperBlock
Typedefs
typedef BlockParam< float > BlockParamFloat
typedef BlockParam< int32_t > BlockParamInt
typedef BlockParam< bool > BlockParamBool
typedef BlockParam< float & > BlockParamExtFloat
typedef BlockParam< int32_t & > BlockParamExtInt
Functions
int basicBlocksTest ()
int blockLimitTest ()
int blockLimitSymTest ()
int blockLowPassTest ()
int blockHighPassTest ()
int blockLowPass2Test ()
int blockIntegralTest ()
int blockIntegralTrapTest ()
int blockDerivativeTest ()
int blockPTest ()
int blockPITest ()
int blockPDTest ()
int blockPIDTest ()
int blockOutputTest ()
int blockRandUniformTest ()
int blockRandGaussTest ()
int blockStatsTest ()
int blockDelayTest ()
Variables
static constexpr uint8_t maxChildrenPerBlock = 100
static constexpr uint8_t maxParamsPerBlock = 110
static constexpr uint8_t blockNameLengthMax = 40
Typedef Documentation
BlockParamBool
typedef BlockParam<bool> control::BlockParamBool
Definition at line 109 of file BlockParam.hpp.
BlockParamExtFloat
typedef BlockParam<float &> control::BlockParamExtFloat
Definition at line 110 of file BlockParam.hpp.
BlockParamExtInt
typedef BlockParam<int32_t &> control::BlockParamExtInt
Definition at line 111 of file BlockParam.hpp.
BlockParamFloat
typedef BlockParam<float> control::BlockParamFloat
Definition at line 107 of file BlockParam.hpp.
BlockParamInt
typedef BlockParam<int32_t> control::BlockParamInt
Definition at line 108 of file BlockParam.hpp.
Function Documentation
basicBlocksTest()
int basicBlocksTest ()
Definition at line 70 of file blocks.cpp.
References blockDelayTest(), blockDerivativeTest(), blockHighPassTest(), blockIntegralTest(), blockIntegralTrapTest(), blockLimitSymTest(), blockLimitTest(), blockLowPass2Test(), blockLowPassTest(), blockOutputTest(), blockPDTest(), blockPIDTest(), blockPITest(), blockPTest(), and blockStatsTest().
Referenced by controllib_test_main().
blockDelayTest()
int blockDelayTest ()
Definition at line 502 of file blocks.cpp.
References ASSERT_CL, equal(), and control::BlockDelay< Type, M, N, LEN >::update().
Referenced by basicBlocksTest(), and basicBlocksTest().
blockDerivativeTest()
int blockDerivativeTest ()
Definition at line 291 of file blocks.cpp.
References ASSERT_CL, equal(), f(), control::Block::getDt(), control::BlockDerivative::getLP(), control::BlockDerivative::getU(), control::SuperBlock::setDt(), control::BlockDerivative::setU(), and control::BlockDerivative::update().
Referenced by basicBlocksTest(), and basicBlocksTest().
blockHighPassTest()
int blockHighPassTest ()
Definition at line 152 of file blocks.cpp.
References ASSERT_CL, equal(), f(), control::Block::getDt(), control::BlockHighPass::getFCut(), control::BlockHighPass::getU(), control::BlockHighPass::getY(), control::Block::setDt(), control::BlockHighPass::setU(), control::BlockHighPass::setY(), and control::BlockHighPass::update().
Referenced by basicBlocksTest(), and basicBlocksTest().
blockIntegralTest()
int blockIntegralTest ()
Definition at line 211 of file blocks.cpp.
References ASSERT_CL, equal(), f(), control::Block::getDt(), control::BlockIntegral::getMax(), control::BlockIntegral::getY(), control::SuperBlock::setDt(), control::BlockIntegral::setY(), and control::BlockIntegral::update().
Referenced by basicBlocksTest(), and basicBlocksTest().
blockIntegralTrapTest()
int blockIntegralTrapTest ()
Definition at line 248 of file blocks.cpp.
References ASSERT_CL, equal(), f(), control::Block::getDt(), control::BlockIntegralTrap::getMax(), control::BlockIntegralTrap::getU(), control::BlockIntegralTrap::getY(), control::SuperBlock::setDt(), control::BlockIntegralTrap::setU(), control::BlockIntegralTrap::setY(), and control::BlockIntegralTrap::update().
Referenced by basicBlocksTest(), and basicBlocksTest().
blockLimitSymTest()
int blockLimitSymTest ()
Definition at line 109 of file blocks.cpp.
References ASSERT_CL, equal(), f(), control::Block::getDt(), control::BlockLimitSym::getMax(), and control::BlockLimitSym::update().
Referenced by basicBlocksTest(), and basicBlocksTest().
blockLimitTest()
int blockLimitTest ()
Definition at line 93 of file blocks.cpp.
References ASSERT_CL, equal(), f(), control::Block::getDt(), control::BlockLimit::getMax(), control::BlockLimit::getMin(), and control::BlockLimit::update().
Referenced by basicBlocksTest(), and basicBlocksTest().
blockLowPass2Test()
int blockLowPass2Test ()
Definition at line 183 of file blocks.cpp.
References ASSERT_CL, equal(), f(), control::Block::getDt(), control::BlockLowPass2::getFCutParam(), control::BlockLowPass2::getState(), control::Block::setDt(), control::BlockLowPass2::setState(), and control::BlockLowPass2::update().
Referenced by basicBlocksTest(), and basicBlocksTest().
blockLowPassTest()
int blockLowPassTest ()
Definition at line 124 of file blocks.cpp.
References ASSERT_CL, equal(), f(), control::Block::getDt(), control::BlockLowPass::getFCut(), control::BlockLowPass::getState(), control::Block::setDt(), control::BlockLowPass::setState(), and control::BlockLowPass::update().
Referenced by basicBlocksTest(), and basicBlocksTest().
blockOutputTest()
int blockOutputTest ()
Definition at line 407 of file blocks.cpp.
References ASSERT_CL, equal(), f(), control::BlockOutput::get(), control::Block::getDt(), control::BlockOutput::getMax(), control::BlockOutput::getMin(), and control::BlockOutput::update().
Referenced by basicBlocksTest(), and basicBlocksTest().
blockPDTest()
int blockPDTest ()
Definition at line 352 of file blocks.cpp.
References ASSERT_CL, equal(), f(), control::BlockPD::getDerivative(), control::Block::getDt(), control::BlockPD::getKD(), control::BlockPD::getKP(), control::BlockDerivative::getLP(), control::BlockDerivative::getU(), control::SuperBlock::setDt(), control::BlockDerivative::setU(), control::BlockPD::update(), and control::BlockDerivative::update().
Referenced by basicBlocksTest(), and basicBlocksTest().
blockPIDTest()
int blockPIDTest ()
Definition at line 377 of file blocks.cpp.
References ASSERT_CL, equal(), f(), control::BlockPID::getDerivative(), control::Block::getDt(), control::BlockPID::getIntegral(), control::BlockPID::getKD(), control::BlockPID::getKI(), control::BlockPID::getKP(), control::BlockDerivative::getLP(), control::BlockIntegral::getMax(), control::BlockDerivative::getU(), control::BlockIntegral::getY(), control::SuperBlock::setDt(), control::BlockDerivative::setU(), control::BlockIntegral::setY(), control::BlockPID::update(), and control::BlockDerivative::update().
Referenced by basicBlocksTest(), and basicBlocksTest().
blockPITest()
int blockPITest ()
Definition at line 330 of file blocks.cpp.
References ASSERT_CL, equal(), f(), control::Block::getDt(), control::BlockPI::getIntegral(), control::BlockPI::getKI(), control::BlockPI::getKP(), control::BlockIntegral::getMax(), control::BlockIntegral::getY(), control::SuperBlock::setDt(), control::BlockIntegral::setY(), and control::BlockPI::update().
Referenced by basicBlocksTest(), and basicBlocksTest().
blockPTest()
int blockPTest ()
Definition at line 314 of file blocks.cpp.
References ASSERT_CL, equal(), f(), control::Block::getDt(), control::BlockP::getKP(), control::Block::setDt(), and control::BlockP::update().
Referenced by basicBlocksTest(), and basicBlocksTest().
blockRandGaussTest()
int blockRandGaussTest ()
Definition at line 455 of file blocks.cpp.
References ASSERT_CL, equal(), f(), control::Block::getDt(), control::BlockRandGauss::getMean(), control::BlockRandGauss::getStdDev(), matrix::sqrt(), and control::BlockRandGauss::update().
Referenced by basicBlocksTest().
blockRandUniformTest()
int blockRandUniformTest ()
Definition at line 429 of file blocks.cpp.
References ASSERT_CL, equal(), f(), control::Block::getDt(), control::BlockRandUniform::getMax(), control::BlockRandUniform::getMin(), greater_than_or_equal(), less_than_or_equal(), and control::BlockRandUniform::update().
Referenced by basicBlocksTest().
blockStatsTest()
int blockStatsTest ()
Definition at line 485 of file blocks.cpp.
References ASSERT_CL, equal(), f(), control::BlockStats< Type, M >::getMean(), control::BlockStats< Type, M >::getStdDev(), control::BlockStats< Type, M >::reset(), and control::BlockStats< Type, M >::update().
Referenced by basicBlocksTest(), and basicBlocksTest().
Variable Documentation
blockNameLengthMax
constexpr uint8_t control::blockNameLengthMax = 40 static
Definition at line 51 of file Block.hpp.
Referenced by control::BlockParamBase::BlockParamBase(), control::Block::getName(), control::SuperBlock::setDt(), control::SuperBlock::updateChildParams(), and control::Block::updateParams().
maxChildrenPerBlock
constexpr uint8_t control::maxChildrenPerBlock = 100 static
Definition at line 49 of file Block.hpp.
Referenced by control::SuperBlock::setDt(), and control::SuperBlock::updateChildParams().
maxParamsPerBlock
constexpr uint8_t control::maxParamsPerBlock = 110 static
Definition at line 50 of file Block.hpp.
Referenced by control::Block::updateParams().