PX4 Firmware: src/lib/pwm_limit/pwm_limit.h File Reference
pwm_limit.h File Reference
#include <stdint.h>
#include <stdbool.h>
Classes
struct pwm_limit_t
Macros
#define INIT_TIME_US 50000
#define RAMP_TIME_US 500000
Enumerations
enum pwm_limit_state { PWM_LIMIT_STATE_OFF = 0, PWM_LIMIT_STATE_INIT, PWM_LIMIT_STATE_RAMP, PWM_LIMIT_STATE_ON }
Functions
__EXPORT void pwm_limit_init (pwm_limit_t *limit)
__EXPORT void pwm_limit_calc (const bool armed, const bool pre_armed, const unsigned num_channels, const uint16_t reverse_mask, const uint16_t *disarmed_pwm, const uint16_t *min_pwm, const uint16_t *max_pwm, const float *output, uint16_t *effective_pwm, pwm_limit_t *limit)
Macro Definition Documentation
#define INIT_TIME_US 50000
Definition at line 54 of file pwm_limit.h.
Referenced by MixerTest::mixerTest(), and pwm_limit_calc().
#define RAMP_TIME_US 500000
Definition at line 58 of file pwm_limit.h.
Referenced by MixerTest::mixerTest(), and pwm_limit_calc().
Enumeration Type Documentation
enum pwm_limit_state
Enumerator
PWM_LIMIT_STATE_OFF
PWM_LIMIT_STATE_INIT
PWM_LIMIT_STATE_RAMP
PWM_LIMIT_STATE_ON
Definition at line 60 of file pwm_limit.h.
Function Documentation
__EXPORT void pwm_limit_calc (const bool armed, const bool pre_armed, const unsigned num_channels, const uint16_t reverse_mask, const uint16_t * disarmed_pwm, const uint16_t * min_pwm, const uint16_t * max_pwm, const float * output, uint16_t * effective_pwm, pwm_limit_t * limit)
Definition at line 59 of file pwm_limit.cpp.
References hrt_absolute_time(), hrt_abstime, hrt_elapsed_time(), INIT_TIME_US, PROGRESS_INT_SCALING, PWM_LIMIT_STATE_INIT, PWM_LIMIT_STATE_OFF, PWM_LIMIT_STATE_ON, PWM_LIMIT_STATE_RAMP, RAMP_TIME_US, pwm_limit_t::state, and pwm_limit_t::time_armed.
Referenced by PX4FMU::cycle(), mixer_tick(), MixerTest::mixerTest(), linux_pwm_out::task_main(), and snapdragon_pwm::task_main().
__EXPORT void pwm_limit_init (pwm_limit_t * limit)
Definition at line 53 of file pwm_limit.cpp.
References PWM_LIMIT_STATE_INIT, pwm_limit_t::state, and pwm_limit_t::time_armed.
Referenced by PX4FMU::init(), MixerTest::mixerTest(), linux_pwm_out::task_main(), snapdragon_pwm::task_main(), and user_start().