PX4 Firmware: DfISL29501Wrapper Class Reference
DfISL29501Wrapper Class Reference
Public Member Functions
DfISL29501Wrapper ()
~DfISL29501Wrapper ()
int start ()
Start automatic measurement.
int stop ()
Stop automatic measurement.
Private Member Functions
int _publish (struct range_sensor_data &data)
Private Attributes
orb_advert_t _range_topic
int _orb_class_instance
Detailed Description
Definition at line 76 of file df_isl29501_wrapper.cpp.
Constructor & Destructor Documentation
DfISL29501Wrapper()
DfISL29501Wrapper::DfISL29501Wrapper ()
Definition at line 108 of file df_isl29501_wrapper.cpp.
Referenced by df_isl29501_wrapper::start().
~DfISL29501Wrapper()
DfISL29501Wrapper::~DfISL29501Wrapper ()
Definition at line 115 of file df_isl29501_wrapper.cpp.
Member Function Documentation
_publish()
int DfISL29501Wrapper::_publish (struct range_sensor_data & data) private
Definition at line 152 of file df_isl29501_wrapper.cpp.
References _orb_class_instance, _range_topic, distance_sensor_s::current_distance, hrt_absolute_time(), distance_sensor_s::id, distance_sensor_s::max_distance, distance_sensor_s::min_distance, orb_advertise_multi(), ORB_ID, ORB_PRIO_DEFAULT, orb_publish(), distance_sensor_s::signal_quality, distance_sensor_s::timestamp, distance_sensor_s::type, and distance_sensor_s::variance.
start()
int DfISL29501Wrapper::start ()
Start automatic measurement.
Returns
0 on success
Definition at line 119 of file df_isl29501_wrapper.cpp.
References ToneAlarmInterface::init(), and start().
Referenced by df_isl29501_wrapper::calibration(), df_isl29501_wrapper::probe(), and df_isl29501_wrapper::start().
stop()
int DfISL29501Wrapper::stop ()
Stop automatic measurement.
Returns
0 on success
Definition at line 139 of file df_isl29501_wrapper.cpp.
References stop().
Referenced by df_isl29501_wrapper::stop().
Member Data Documentation
_orb_class_instance
int DfISL29501Wrapper::_orb_class_instance private
Definition at line 102 of file df_isl29501_wrapper.cpp.
Referenced by _publish().
_range_topic
orb_advert_t DfISL29501Wrapper::_range_topic private
Definition at line 100 of file df_isl29501_wrapper.cpp.
Referenced by _publish().
The documentation for this class was generated from the following file:
src/drivers/driver_framework_wrapper/df_isl29501_wrapper/df_isl29501_wrapper.cpp