PX4 Firmware: DataValidator Class Reference
DataValidator Class Reference
#include <data_validator.h>
Public Member Functions
DataValidator ()=default
~DataValidator ()=default
void put (uint64_t timestamp, float val, uint64_t error_count, int priority)
Put an item into the validator.
void put (uint64_t timestamp, const float val[dimensions], uint64_t error_count, int priority)
Put a 3D item into the validator.
DataValidator * sibling ()
Get the next sibling in the group.
void setSibling (DataValidator *new_sibling)
Set the sibling to the next node in the group.
float confidence (uint64_t timestamp)
Get the confidence of this validator.
uint64_t error_count () const
Get the error count of this validator.
float * value ()
Get the values of this validator.
bool used () const
Get the used status of this validator.
int priority () const
Get the priority of this validator.
uint32_t state () const
Get the error state of this validator.
void reset_state ()
Reset the error state of this validator.
float * rms ()
Get the RMS values of this validator.
float * vibration_offset ()
Get the vibration offset.
void print ()
Print the validator value.
void set_timeout (uint32_t timeout_interval_us)
Set the timeout value.
void set_equal_value_threshold (uint32_t threshold)
Set the equal count threshold.
uint32_t get_timeout () const
Get the timeout value.
Static Public Attributes
static const unsigned dimensions = 3
static constexpr uint32_t ERROR_FLAG_NO_ERROR = (0x00000000U)
Data validator error states.
static constexpr uint32_t ERROR_FLAG_NO_DATA = (0x00000001U)
static constexpr uint32_t ERROR_FLAG_STALE_DATA = (0x00000001U << 1)
static constexpr uint32_t ERROR_FLAG_TIMEOUT = (0x00000001U << 2)
static constexpr uint32_t ERROR_FLAG_HIGH_ERRCOUNT = (0x00000001U << 3)
static constexpr uint32_t ERROR_FLAG_HIGH_ERRDENSITY = (0x00000001U << 4)
Private Member Functions
DataValidator (const DataValidator &)=delete
DataValidator operator= (const DataValidator &)=delete
Private Attributes
uint32_t _error_mask {ERROR_FLAG_NO_ERROR}
sensor error state
uint32_t _timeout_interval {20000}
interval in which the datastream times out in us
uint64_t _time_last {0}
last timestamp
uint64_t _event_count {0}
total data counter
uint64_t _error_count {0}
error count
int _error_density {0}
ratio between successful reads and errors
int _priority {0}
sensor nominal priority
float _mean [dimensions] {}
mean of value
float _lp [dimensions] {}
low pass value
float _M2 [dimensions] {}
RMS component value.
float _rms [dimensions] {}
root mean square error
float _value [dimensions] {}
last value
float _vibe [dimensions] {}
vibration level, in sensor unit
unsigned _value_equal_count {0}
equal values in a row
unsigned _value_equal_count_threshold {VALUE_EQUAL_COUNT_DEFAULT}
when to consider an equal count as a problem
DataValidator * _sibling {nullptr}
sibling in the group
Static Private Attributes
static const constexpr unsigned NORETURN_ERRCOUNT = 10000
if the error count reaches this value, return sensor as invalid
static const constexpr float ERROR_DENSITY_WINDOW = 100.0f
window in measurement counts for errors
static const constexpr unsigned VALUE_EQUAL_COUNT_DEFAULT = 100
if the sensor value is the same (accumulated also between axes) this many times, flag it
Detailed Description
Definition at line 47 of file data_validator.h.
Constructor & Destructor Documentation
DataValidator::DataValidator () default
DataValidator::~DataValidator () default
DataValidator::DataValidator (const DataValidator &) private delete
Member Function Documentation
float DataValidator::confidence (uint64_t timestamp)
Get the confidence of this validator.
Returns
the confidence between 0 and 1
Definition at line 103 of file data_validator.cpp.
References _error_count, _error_density, _error_mask, _time_last, _timeout_interval, _value_equal_count, _value_equal_count_threshold, ERROR_DENSITY_WINDOW, ERROR_FLAG_HIGH_ERRCOUNT, ERROR_FLAG_HIGH_ERRDENSITY, ERROR_FLAG_NO_DATA, ERROR_FLAG_NO_ERROR, ERROR_FLAG_STALE_DATA, ERROR_FLAG_TIMEOUT, f(), and NORETURN_ERRCOUNT.
Referenced by Sensors::diff_pres_poll(), DataValidatorGroup::get_best(), DataValidatorGroup::get_vibration_factor(), DataValidatorGroup::get_vibration_offset(), print(), and setSibling().
uint64_t DataValidator::error_count () const inline
Get the error count of this validator.
Returns
the error count
Definition at line 92 of file data_validator.h.
References _error_count.
uint32_t DataValidator::get_timeout () const inline
Get the timeout value.
Returns
The timeout interval in microseconds
Definition at line 160 of file data_validator.h.
References _timeout_interval.
Referenced by DataValidatorGroup::DataValidatorGroup().
DataValidator DataValidator::operator= (const DataValidator &) private delete
void DataValidator::print ()
Print the validator value.
Definition at line 148 of file data_validator.cpp.
References _lp, _mean, _rms, _time_last, _value, confidence(), dimensions, ecl_absolute_time, and ECL_INFO.
Referenced by DataValidatorGroup::print(), Sensors::print_status(), and vibration_offset().
int DataValidator::priority () const inline
Get the priority of this validator.
Returns
the stored priority
Definition at line 110 of file data_validator.h.
References _priority.
Referenced by DataValidatorGroup::get_best(), and DataValidatorGroup::print().
void DataValidator::put (uint64_t timestamp, float val, uint64_t error_count, int priority)
Put an item into the validator.
Parameters
val Item to put
Definition at line 47 of file data_validator.cpp.
References data, and dimensions.
Referenced by Sensors::diff_pres_poll(), and DataValidatorGroup::put().
void DataValidator::put (uint64_t timestamp, const float val[dimensions], uint64_t error_count, int priority)
Put a 3D item into the validator.
Parameters
val Item to put
Definition at line 55 of file data_validator.cpp.
References _error_count, _error_density, _event_count, _lp, _M2, _mean, _priority, _rms, _time_last, _value, _value_equal_count, _vibe, dimensions, and f().
void DataValidator::reset_state () inline
Reset the error state of this validator.
Definition at line 121 of file data_validator.h.
References _error_mask, and ERROR_FLAG_NO_ERROR.
Referenced by DataValidatorGroup::get_best().
float* DataValidator::rms () inline
Get the RMS values of this validator.
Returns
the stored RMS
Definition at line 127 of file data_validator.h.
References _rms.
Referenced by DataValidatorGroup::get_vibration_factor().
void DataValidator::set_equal_value_threshold (uint32_t threshold) inline
Set the equal count threshold.
Parameters
threshold The number of equal values before considering the sensor stale
Definition at line 153 of file data_validator.h.
References _value_equal_count_threshold.
Referenced by Sensors::Sensors(), and DataValidatorGroup::set_equal_value_threshold().
void DataValidator::set_timeout (uint32_t timeout_interval_us) inline
Set the timeout value.
Parameters
timeout_interval_us The timeout interval in microseconds
Definition at line 146 of file data_validator.h.
References _timeout_interval.
Referenced by DataValidatorGroup::add_new_validator(), Sensors::Sensors(), and DataValidatorGroup::set_timeout().
void DataValidator::setSibling (DataValidator * new_sibling) inline
Set the sibling to the next node in the group.
Definition at line 80 of file data_validator.h.
References _sibling, and confidence().
Referenced by DataValidatorGroup::add_new_validator(), and DataValidatorGroup::DataValidatorGroup().
DataValidator* DataValidator::sibling () inline
Get the next sibling in the group.
Returns
the next sibling
Definition at line 74 of file data_validator.h.
References _sibling.
Referenced by DataValidatorGroup::failover_index(), DataValidatorGroup::failover_state(), DataValidatorGroup::get_best(), DataValidatorGroup::get_vibration_factor(), DataValidatorGroup::get_vibration_offset(), DataValidatorGroup::print(), DataValidatorGroup::put(), DataValidatorGroup::set_equal_value_threshold(), DataValidatorGroup::set_timeout(), and DataValidatorGroup::~DataValidatorGroup().
uint32_t DataValidator::state () const inline
Get the error state of this validator.
Returns
the bitmask with the error status
Definition at line 116 of file data_validator.h.
References _error_mask.
Referenced by DataValidatorGroup::failover_index(), DataValidatorGroup::failover_state(), and DataValidatorGroup::print().
bool DataValidator::used () const inline
Get the used status of this validator.
Returns
true if this validator ever saw data
Definition at line 104 of file data_validator.h.
References _time_last.
Referenced by DataValidatorGroup::failover_index(), DataValidatorGroup::failover_state(), and DataValidatorGroup::print().
float* DataValidator::value () inline
Get the values of this validator.
Returns
the stored value
Definition at line 98 of file data_validator.h.
References _value.
Referenced by DataValidatorGroup::get_best().
float* DataValidator::vibration_offset () inline
Get the vibration offset.
Returns
the stored vibration offset
Definition at line 133 of file data_validator.h.
References _vibe, and print().
Referenced by DataValidatorGroup::get_vibration_offset().
Member Data Documentation
uint64_t DataValidator::_error_count {0} private
error count
Definition at line 179 of file data_validator.h.
Referenced by confidence(), error_count(), and put().
int DataValidator::_error_density {0} private
ratio between successful reads and errors
Definition at line 181 of file data_validator.h.
Referenced by confidence(), and put().
uint32_t DataValidator::_error_mask {ERROR_FLAG_NO_ERROR} private
sensor error state
Definition at line 173 of file data_validator.h.
Referenced by confidence(), reset_state(), and state().
uint64_t DataValidator::_event_count {0} private
total data counter
Definition at line 178 of file data_validator.h.
Referenced by put().
float DataValidator::_lp[dimensions] {} private
low pass value
Definition at line 186 of file data_validator.h.
Referenced by print(), and put().
float DataValidator::_M2[dimensions] {} private
RMS component value.
Definition at line 187 of file data_validator.h.
Referenced by put().
float DataValidator::_mean[dimensions] {} private
mean of value
Definition at line 185 of file data_validator.h.
Referenced by print(), and put().
int DataValidator::_priority {0} private
sensor nominal priority
Definition at line 183 of file data_validator.h.
Referenced by priority(), and put().
float DataValidator::_rms[dimensions] {} private
root mean square error
Definition at line 188 of file data_validator.h.
Referenced by print(), put(), and rms().
DataValidator* DataValidator::_sibling {nullptr} private
sibling in the group
Definition at line 195 of file data_validator.h.
Referenced by setSibling(), and sibling().
uint64_t DataValidator::_time_last {0} private
last timestamp
Definition at line 177 of file data_validator.h.
Referenced by confidence(), print(), put(), and used().
uint32_t DataValidator::_timeout_interval {20000} private
interval in which the datastream times out in us
Definition at line 175 of file data_validator.h.
Referenced by confidence(), get_timeout(), and set_timeout().
float DataValidator::_value[dimensions] {} private
last value
Definition at line 189 of file data_validator.h.
Referenced by print(), put(), and value().
unsigned DataValidator::_value_equal_count {0} private
equal values in a row
Definition at line 192 of file data_validator.h.
Referenced by confidence(), and put().
unsigned DataValidator::_value_equal_count_threshold {VALUE_EQUAL_COUNT_DEFAULT} private
when to consider an equal count as a problem
Definition at line 193 of file data_validator.h.
Referenced by confidence(), and set_equal_value_threshold().
float DataValidator::_vibe[dimensions] {} private
vibration level, in sensor unit
Definition at line 190 of file data_validator.h.
Referenced by put(), and vibration_offset().
const unsigned DataValidator::dimensions = 3 static
Definition at line 50 of file data_validator.h.
Referenced by print(), and put().
const constexpr float DataValidator::ERROR_DENSITY_WINDOW = 100.0f static private
window in measurement counts for errors
Definition at line 198 of file data_validator.h.
Referenced by confidence().
constexpr uint32_t DataValidator::ERROR_FLAG_HIGH_ERRCOUNT = (0x00000001U << 3) static
Definition at line 169 of file data_validator.h.
Referenced by sensors::VotedSensorsUpdate::check_failover(), confidence(), and DataValidatorGroup::print().
constexpr uint32_t DataValidator::ERROR_FLAG_HIGH_ERRDENSITY = (0x00000001U << 4) static
Definition at line 170 of file data_validator.h.
Referenced by sensors::VotedSensorsUpdate::check_failover(), confidence(), and DataValidatorGroup::print().
constexpr uint32_t DataValidator::ERROR_FLAG_NO_DATA = (0x00000001U) static
Definition at line 166 of file data_validator.h.
Referenced by sensors::VotedSensorsUpdate::check_failover(), confidence(), and DataValidatorGroup::print().
constexpr uint32_t DataValidator::ERROR_FLAG_NO_ERROR = (0x00000000U) static
Data validator error states.
Definition at line 165 of file data_validator.h.
Referenced by sensors::VotedSensorsUpdate::check_failover(), confidence(), DataValidatorGroup::failover_index(), DataValidatorGroup::failover_state(), DataValidatorGroup::print(), and reset_state().
constexpr uint32_t DataValidator::ERROR_FLAG_STALE_DATA = (0x00000001U << 1) static
Definition at line 167 of file data_validator.h.
Referenced by sensors::VotedSensorsUpdate::check_failover(), confidence(), and DataValidatorGroup::print().
constexpr uint32_t DataValidator::ERROR_FLAG_TIMEOUT = (0x00000001U << 2) static
Definition at line 168 of file data_validator.h.
Referenced by sensors::VotedSensorsUpdate::check_failover(), confidence(), and DataValidatorGroup::print().
const constexpr unsigned DataValidator::NORETURN_ERRCOUNT = 10000 static private
if the error count reaches this value, return sensor as invalid
Definition at line 197 of file data_validator.h.
Referenced by confidence().
const constexpr unsigned DataValidator::VALUE_EQUAL_COUNT_DEFAULT = 100 static private
if the sensor value is the same (accumulated also between axes) this many times, flag it
Definition at line 199 of file data_validator.h.
The documentation for this class was generated from the following files:
src/lib/ecl/validation/data_validator.h
src/lib/ecl/validation/data_validator.cpp