PX4 Firmware: BMP280 Class Reference
BMP280 Class Reference
#include <BMP280.hpp>
Public Member Functions
BMP280 (bmp280::IBMP280 *interface)
virtual ~BMP280 ()
int init ()
void print_info ()
Private Member Functions
void Run () override
void Start ()
void Stop ()
int measure ()
int collect ()
Private Attributes
PX4Barometer _px4_baro
bmp280::IBMP280 * _interface
bool _collect_phase {false}
perf_counter_t _sample_perf
perf_counter_t _measure_perf
perf_counter_t _comms_errors
bmp280::calibration_s * _cal {nullptr}
bmp280::fcalibration_s _fcal {}
Static Private Attributes
static constexpr uint8_t _curr_ctrl {BMP280_CTRL_P16 | BMP280_CTRL_T2}
static constexpr uint32_t _measure_interval {BMP280_MT_INIT + BMP280_MT *(16 - 1 + 2 - 1)}
Detailed Description
Definition at line 44 of file BMP280.hpp.
Constructor & Destructor Documentation
BMP280()
BMP280::BMP280 (bmp280::IBMP280 * interface)
Definition at line 36 of file BMP280.cpp.
~BMP280()
BMP280::~BMP280 () virtual
Definition at line 46 of file BMP280.cpp.
References _comms_errors, _interface, _measure_perf, _sample_perf, perf_free(), and Stop().
Member Function Documentation
collect()
int BMP280::collect () private
Definition at line 151 of file BMP280.cpp.
References _collect_phase, _comms_errors, _fcal, _interface, _px4_baro, _sample_perf, BMP280_ADDR_DATA, data, bmp280::IBMP280::get_data(), hrt_absolute_time(), hrt_abstime, OK, P, bmp280::fcalibration_s::p1, bmp280::fcalibration_s::p2, bmp280::fcalibration_s::p3, bmp280::fcalibration_s::p4, bmp280::fcalibration_s::p5, bmp280::fcalibration_s::p6, bmp280::fcalibration_s::p7, bmp280::fcalibration_s::p8, bmp280::fcalibration_s::p9, bmp280::data_s::p_lsb, bmp280::data_s::p_msb, bmp280::data_s::p_xlsb, perf_begin(), perf_cancel(), perf_count(), perf_end(), perf_event_count(), PX4Barometer::set_error_count(), PX4Barometer::set_temperature(), bmp280::fcalibration_s::t1, bmp280::fcalibration_s::t2, bmp280::fcalibration_s::t3, bmp280::data_s::t_lsb, bmp280::data_s::t_msb, bmp280::data_s::t_xlsb, and PX4Barometer::update().
Referenced by Run().
init()
int BMP280::init ()
Definition at line 60 of file BMP280.cpp.
References _cal, _curr_ctrl, _fcal, _interface, BMP280_ADDR_CAL, BMP280_ADDR_CONFIG, BMP280_ADDR_CTRL, BMP280_ADDR_ID, BMP280_ADDR_RESET, BMP280_CONFIG_F16, BMP280_VALUE_ID, BMP280_VALUE_RESET, bmp280::IBMP280::get_calibration(), bmp280::IBMP280::get_reg(), OK, bmp280::calibration_s::p1, bmp280::fcalibration_s::p1, bmp280::calibration_s::p2, bmp280::fcalibration_s::p2, bmp280::calibration_s::p3, bmp280::fcalibration_s::p3, bmp280::calibration_s::p4, bmp280::fcalibration_s::p4, bmp280::calibration_s::p5, bmp280::fcalibration_s::p5, bmp280::calibration_s::p6, bmp280::fcalibration_s::p6, bmp280::calibration_s::p7, bmp280::fcalibration_s::p7, bmp280::calibration_s::p8, bmp280::fcalibration_s::p8, bmp280::calibration_s::p9, bmp280::fcalibration_s::p9, bmp280::IBMP280::set_reg(), Start(), bmp280::calibration_s::t1, bmp280::fcalibration_s::t1, bmp280::calibration_s::t2, bmp280::fcalibration_s::t2, bmp280::calibration_s::t3, and bmp280::fcalibration_s::t3.
Referenced by DfBmp280Wrapper::start(), and bmp280::start_bus().
measure()
int BMP280::measure () private
Definition at line 130 of file BMP280.cpp.
References _collect_phase, _comms_errors, _curr_ctrl, _interface, _measure_perf, BMP280_ADDR_CTRL, BMP280_CTRL_MODE_FORCE, OK, perf_begin(), perf_cancel(), perf_count(), perf_end(), and bmp280::IBMP280::set_reg().
Referenced by Run().
print_info()
void BMP280::print_info ()
Definition at line 196 of file BMP280.cpp.
References _comms_errors, _measure_perf, _px4_baro, _sample_perf, perf_print_counter(), and PX4Barometer::print_status().
Referenced by bmp280::status().
Run()
void BMP280::Run () override private
Definition at line 117 of file BMP280.cpp.
References _collect_phase, _measure_interval, collect(), and measure().
Start()
void BMP280::Start () private
Definition at line 101 of file BMP280.cpp.
References _collect_phase.
Referenced by init().
Stop()
void BMP280::Stop () private
Definition at line 111 of file BMP280.cpp.
Referenced by ~BMP280().
Member Data Documentation
_cal
bmp280::calibration_s* BMP280::_cal {nullptr} private
Definition at line 75 of file BMP280.hpp.
Referenced by init().
_collect_phase
bool BMP280::_collect_phase {false} private
Definition at line 69 of file BMP280.hpp.
Referenced by collect(), measure(), Run(), and Start().
_comms_errors
perf_counter_t BMP280::_comms_errors private
Definition at line 73 of file BMP280.hpp.
Referenced by collect(), measure(), print_info(), and ~BMP280().
_curr_ctrl
constexpr uint8_t BMP280::_curr_ctrl {BMP280_CTRL_P16 | BMP280_CTRL_T2} static private
Definition at line 66 of file BMP280.hpp.
Referenced by init(), and measure().
_fcal
bmp280::fcalibration_s BMP280::_fcal {} private
Definition at line 76 of file BMP280.hpp.
Referenced by collect(), and init().
_interface
bmp280::IBMP280* BMP280::_interface private
Definition at line 63 of file BMP280.hpp.
Referenced by collect(), init(), measure(), and ~BMP280().
_measure_interval
constexpr uint32_t BMP280::_measure_interval {BMP280_MT_INIT + BMP280_MT *(16 - 1 + 2 - 1)} static private
Definition at line 67 of file BMP280.hpp.
Referenced by Run().
_measure_perf
perf_counter_t BMP280::_measure_perf private
Definition at line 72 of file BMP280.hpp.
Referenced by measure(), print_info(), and ~BMP280().
_px4_baro
PX4Barometer BMP280::_px4_baro private
Definition at line 61 of file BMP280.hpp.
Referenced by collect(), and print_info().
_sample_perf
perf_counter_t BMP280::_sample_perf private
Definition at line 71 of file BMP280.hpp.
Referenced by collect(), print_info(), and ~BMP280().
The documentation for this class was generated from the following files:
src/drivers/barometer/bmp280/BMP280.hpp
src/drivers/barometer/bmp280/BMP280.cpp