PX4 Firmware: src/drivers/spektrum_rc/spektrum_rc.cpp File Reference
spektrum_rc.cpp File Reference
This is a driver for a Spektrum satellite receiver connected to a Snapdragon on the serial port.
#include <string.h>
#include <px4_platform_common/tasks.h>
#include <px4_platform_common/posix.h>
#include <px4_platform_common/getopt.h>
#include <lib/rc/dsm.h>
#include <drivers/drv_rc_input.h>
#include <drivers/drv_hrt.h>
#include <uORB/uORB.h>
#include <uORB/topics/input_rc.h>
Namespaces
spektrum_rc
Macros
#define SPEKTRUM_UART_DEVICE_PATH "/dev/tty-3"
#define UNUSED(x) (void)(x)
Functions
__EXPORT int spektrum_rc_main (int argc, char *argv[])
int spektrum_rc::start ()
Attempt to start driver on all available I2C busses.
int spektrum_rc::stop ()
Stop the driver.
int spektrum_rc::info ()
Print a little info about the driver.
void spektrum_rc::usage ()
Prints info about the driver argument usage.
void spektrum_rc::task_main (int argc, char *argv[])
void spektrum_rc::fill_input_rc (uint16_t raw_rc_count, uint16_t raw_rc_values[input_rc_s::RC_INPUT_MAX_CHANNELS], hrt_abstime now, bool frame_drop, bool failsafe, unsigned frame_drops, int rssi, input_rc_s &input_rc)
int spektrum_rc::start (int argc, char *argv[])
Variables
volatile bool spektrum_rc::_task_should_exit = false
static bool spektrum_rc::_is_running = false
static px4_task_t spektrum_rc::_task_handle = -1
Detailed Description
This is a driver for a Spektrum satellite receiver connected to a Snapdragon on the serial port.
By default port J12 (next to J13, power module side) is used.
Definition in file spektrum_rc.cpp.
Macro Definition Documentation
SPEKTRUM_UART_DEVICE_PATH
#define SPEKTRUM_UART_DEVICE_PATH "/dev/tty-3"
Definition at line 56 of file spektrum_rc.cpp.
Referenced by spektrum_rc::task_main().
UNUSED
#define UNUSED (x) (void)(x)
Definition at line 58 of file spektrum_rc.cpp.
Referenced by genfault(), uavcan_kinetis::CanIface::handleRxInterrupt(), and spektrum_rc::task_main().
Function Documentation
spektrum_rc_main()
int spektrum_rc_main (int argc, char * argv[])
Definition at line 268 of file spektrum_rc.cpp.
References spektrum_rc::info(), spektrum_rc::start(), spektrum_rc::stop(), and spektrum_rc::usage().