PX4 Firmware: src/drivers/boards/common/stm32/board_identity.c File Reference
board_identity.c File Reference
#include <px4_config.h>
#include <stdio.h>
#include <string.h>
Macros
#define CPU_UUID_BYTE_FORMAT_ORDER {3, 2, 1, 0, 7, 6, 5, 4, 11, 10, 9, 8}
#define SWAP_UINT32(x) (((x) >> 24) | (((x) & 0x00ff0000) >> 8) | (((x) & 0x0000ff00) << 8) | ((x) << 24))
Typedefs
typedef const uint8_t uuid_uint8_reorder_t[PX4_CPU_UUID_BYTE_LENGTH]
Functions
void board_get_uuid (uuid_byte_t uuid_bytes)
__EXPORT void board_get_uuid32 (uuid_uint32_t uuid_words)
int board_get_uuid32_formated (char *format_buffer, int size, const char *format, const char *seperator)
int board_get_mfguid (mfguid_t mfgid)
int board_get_mfguid_formated (char *format_buffer, int size)
Macro Definition Documentation
#define CPU_UUID_BYTE_FORMAT_ORDER {3, 2, 1, 0, 7, 6, 5, 4, 11, 10, 9, 8}
Definition at line 44 of file board_identity.c.
Referenced by board_get_uuid().
#define SWAP_UINT32 (x) (((x) >> 24) | (((x) & 0x00ff0000) >> 8) | (((x) & 0x0000ff00) << 8) | ((x) << 24))
Definition at line 45 of file board_identity.c.
Referenced by board_get_mfguid().
Typedef Documentation
typedef const uint8_t uuid_uint8_reorder_t[PX4_CPU_UUID_BYTE_LENGTH]
Definition at line 50 of file board_identity.c.
Function Documentation
int board_get_mfguid (mfguid_t mfgid)
Definition at line 102 of file board_identity.c.
References SWAP_UINT32.
Referenced by UavcanEsc::fill_node_info(), and UavcanNode::getHardwareVersion().
int board_get_mfguid_formated (char * format_buffer, int size)
Definition at line 114 of file board_identity.c.
References board_get_mfguid().
Referenced by ver_main().
void board_get_uuid (uuid_byte_t uuid_bytes)
Definition at line 53 of file board_identity.c.
References board_get_uuid32(), CPU_UUID_BYTE_FORMAT_ORDER, and reorder().
__EXPORT void board_get_uuid32 (uuid_uint32_t uuid_words)
Definition at line 72 of file board_identity.c.
Referenced by Mavlink::send_autopilot_capabilites().
int board_get_uuid32_formated (char * format_buffer, int size, const char * format, const char * seperator)
Definition at line 81 of file board_identity.c.
References board_get_uuid32().
Referenced by ver_main(), and px4::logger::Logger::write_version().