PX4 Firmware: do_not_explicitly_use_this_namespace::Param< int32_t, p > Class Template Reference
do_not_explicitly_use_this_namespace::Param< int32_t, p > Class Template Reference
#include <px4_param.h>
Public Member Functions
Param ()
int32_t get () const
const int32_t & reference () const
bool commit () const
Store the parameter value to the parameter storage (.
bool commit_no_notification () const
Store the parameter value to the parameter storage, w/o notifying the system (.
void set (int32_t val)
bool update ()
param_t handle () const
Private Attributes
int32_t _val
Detailed Description
template<px4::params p>
class do_not_explicitly_use_this_namespace::Param< int32_t, p >
Definition at line 177 of file px4_param.h.
Constructor & Destructor Documentation
template<px4::params p> do_not_explicitly_use_this_namespace::Param< int32_t, p >::Param () inline
Definition at line 183 of file px4_param.h.
References param_set_used().
Member Function Documentation
template<px4::params p> bool do_not_explicitly_use_this_namespace::Param< int32_t, p >::commit () const inline
Store the parameter value to the parameter storage (.
See also
param_set())
Definition at line 194 of file px4_param.h.
References param_set().
template<px4::params p> bool do_not_explicitly_use_this_namespace::Param< int32_t, p >::commit_no_notification () const inline
Store the parameter value to the parameter storage, w/o notifying the system (.
See also
param_set_no_notification())
Definition at line 197 of file px4_param.h.
References param_set_no_notification().
template<px4::params p> int32_t do_not_explicitly_use_this_namespace::Param< int32_t, p >::get () const inline
Definition at line 189 of file px4_param.h.
template<px4::params p> param_t do_not_explicitly_use_this_namespace::Param< int32_t, p >::handle () const inline
Definition at line 203 of file px4_param.h.
References param_handle().
template<px4::params p> const int32_t& do_not_explicitly_use_this_namespace::Param< int32_t, p >::reference () const inline
Definition at line 191 of file px4_param.h.
template<px4::params p> void do_not_explicitly_use_this_namespace::Param< int32_t, p >::set (int32_t val) inline
Definition at line 199 of file px4_param.h.
template<px4::params p> bool do_not_explicitly_use_this_namespace::Param< int32_t, p >::update () inline
Definition at line 201 of file px4_param.h.
References param_get().
Member Data Documentation
template<px4::params p> int32_t do_not_explicitly_use_this_namespace::Param< int32_t, p >::_val private
Definition at line 205 of file px4_param.h.
The documentation for this class was generated from the following file:
src/platforms/px4_param.h