PX4 Firmware: pmw3901 Namespace Reference
pmw3901 Namespace Reference
Local functions in support of the shell command.
Functions
void start (uint8_t rotation)
Start the driver.
void stop ()
Stop the driver.
void test ()
Perform some basic functional tests on the driver; make sure we can collect data from the sensor in polled and automatic modes.
void reset ()
Reset the driver.
void info ()
Print a little info about the driver.
Variables
PMW3901 * g_dev
Detailed Description
Local functions in support of the shell command.
Function Documentation
void pmw3901::info ()
Print a little info about the driver.
Print a little info about the driver.
Definition at line 828 of file pmw3901.cpp.
References errx, and PMW3901::print_info().
Referenced by pmw3901_main().
void pmw3901::reset ()
Reset the driver.
Reset the driver.
Definition at line 341 of file ets_airspeed.cpp.
References ACCEL_DEVICE_PATH, ADIS16448_DEVICE_PATH_ACCEL, ADIS16477_DEVICE_PATH_ACCEL, device::CDev::close(), err, ETS_PATH, fd, FXAS21002C_DEVICE_PATH_GYRO, FXOS8701C_DEVICE_PATH_ACCEL, FXOS8701C_DEVICE_PATH_MAG, LidarLite::get_dev_name(), GPSSIM_DEVICE_PATH, AirspeedSim::ioctl(), SF0X::ioctl(), HC_SR04::ioctl(), SF1XX::ioctl(), MB12XX::ioctl(), SRF02::ioctl(), TERARANGER::ioctl(), PX4FLOW::ioctl(), BMA180::ioctl(), L3GD20::ioctl(), FXAS21002C::ioctl(), FXOS8701CQ_mag::ioctl(), ADIS16448_mag::ioctl(), LSM303D_mag::ioctl(), L3GD20_DEVICE_PATH, LSM303D_DEVICE_PATH_ACCEL, LSM303D_DEVICE_PATH_MAG, MB12XX_DEVICE_PATH, MPU_DEVICE_PATH_ACCEL, device::CDev::open(), PATH_MS4525, PATH_MS5525, PATH_SDP3X, px4_close(), PX4_ERR, PX4_ERROR, px4_ioctl(), PX4_OK, px4_open(), PX4_WARN, PX4FLOW0_DEVICE_PATH, RANGE_FINDER0_DEVICE_PATH, SENSOR_POLLRATE_DEFAULT, SENSORIOCRESET, SENSORIOCSPOLLRATE, SF1XX_DEVICE_PATH, SR04_DEVICE_PATH, SRF02_DEVICE_PATH, and TERARANGER_DEVICE_PATH.
Referenced by adis16448_main(), adis16477_main(), bma180_main(), ets_airspeed_main(), fxas21002c_main(), fxos8701cq_main(), gpssim_main(), gyrosim_main(), hc_sr04_main(), l3gd20_main(), ll40ls_main(), lsm303d_main(), mb12xx_main(), measairspeedsim_main(), ms4525_airspeed_main(), ms5525_airspeed_main(), px4flow_main(), sdp3x_airspeed_main(), sf0x_main(), sf1xx_main(), srf02_main(), teraranger_main(), adis16477::test(), bma180::test(), gyrosim::test(), fxos8701cq::test(), adis16448::test(), lsm303d::test(), and tfmini_main().
void pmw3901::start (uint8_t rotation)
Start the driver.
Definition at line 733 of file pmw3901.cpp.
References errx, fd, g_dev, PMW3901::init(), PMW3901::ioctl(), OK, PMW3901::PMW3901(), PMW3901_BUS, PMW3901_DEVICE_PATH, SENSOR_POLLRATE_DEFAULT, and SENSORIOCSPOLLRATE.
Referenced by pmw3901_main().
void pmw3901::stop ()
Stop the driver.
Stop the driver.
Definition at line 778 of file pmw3901.cpp.
References errx, and g_dev.
Referenced by pmw3901_main().
void pmw3901::test ()
Perform some basic functional tests on the driver; make sure we can collect data from the sensor in polled and automatic modes.
Definition at line 798 of file pmw3901.cpp.
References err, errx, fd, PMW3901_DEVICE_PATH, PX4_ERR, and PMW3901::read().
Referenced by pmw3901_main().
Variable Documentation
PMW3901* pmw3901::g_dev
Definition at line 720 of file pmw3901.cpp.
Referenced by start(), and stop().