PX4 Firmware: src/systemcmds/motor_test/motor_test.c File Reference
motor_test.c File Reference
Tool for drive testing.
#include <px4_config.h>
#include <px4_getopt.h>
#include <px4_log.h>
#include <px4_module.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <unistd.h>
#include <arch/board/board.h>
#include <drivers/drv_hrt.h>
#include <uORB/topics/test_motor.h>
Functions
__EXPORT int motor_test_main (int argc, char *argv[])
static void motor_test (unsigned channel, float value)
static void usage (const char *reason)
Variables
static orb_advert_t _test_motor_pub = NULL
Detailed Description
Tool for drive testing.
Definition in file motor_test.c.
Function Documentation
void motor_test (unsigned channel, float value) static
Definition at line 65 of file motor_test.c.
References _test_motor_pub, hrt_absolute_time(), test_motor_s::motor_number, orb_advertise_queue(), ORB_ID, orb_publish(), test_motor_s::timestamp, and test_motor_s::value.
Referenced by motor_test_main().
int motor_test_main (int argc, char * argv[])
Definition at line 105 of file motor_test.c.
References f(), motor_test(), px4_getopt(), usage(), usleep(), and test_motor_s::value.
static void usage (const char * reason) static
Definition at line 85 of file motor_test.c.
References PRINT_MODULE_DESCRIPTION(), PRINT_MODULE_USAGE_COMMAND_DESCR(), PRINT_MODULE_USAGE_NAME(), PRINT_MODULE_USAGE_PARAM_INT(), and PX4_WARN.
Referenced by motor_test_main().
Variable Documentation
orb_advert_t _test_motor_pub = NULL static
Definition at line 63 of file motor_test.c.
Referenced by motor_test().