PX4 Firmware: BMI055_accel Class Reference
BMI055_accel Class Reference
#include <BMI055_accel.hpp>
Public Member Functions
BMI055_accel (int bus, const char *path_accel, uint32_t device, enum Rotation rotation)
virtual ~BMI055_accel ()
virtual int init ()
virtual ssize_t read (struct file *filp, char *buffer, size_t buflen)
virtual int ioctl (struct file *filp, int cmd, unsigned long arg)
void print_info ()
Diagnostics - print some basic information about the driver.
void print_registers ()
void test_error ()
Public Member Functions inherited from BMI055
BMI055 (const char *name, const char *devname, int bus, uint32_t device, enum spi_mode_e mode, uint32_t frequency, enum Rotation rotation)
virtual ~BMI055 ()=default
Protected Member Functions
virtual int probe ()
Protected Member Functions inherited from BMI055
uint8_t read_reg (unsigned reg)
Read a register from the BMI055.
uint16_t read_reg16 (unsigned reg)
void write_reg (unsigned reg, uint8_t value)
Write a register in the BMI055.
BMI055 (const BMI055 &)
BMI055 operator= (const BMI055 &)
Private Member Functions
void start ()
Start automatic measurement.
void stop ()
Stop automatic measurement.
int reset ()
Reset chip.
void measure ()
Fetch measurements from the sensor and update the report buffers.
void modify_reg (unsigned reg, uint8_t clearbits, uint8_t setbits)
Modify a register in the BMI055_accel.
void write_checked_reg (unsigned reg, uint8_t value)
Write a register in the BMI055_accel, updating _checked_values.
int set_accel_range (unsigned max_g)
Set the BMI055_accel measurement range.
int self_test ()
Measurement self test.
int accel_set_sample_rate (float desired_sample_rate_hz)
void check_registers (void)
BMI055_accel (const BMI055_accel &)
BMI055_accel operator= (const BMI055_accel &)
Static Private Member Functions
static void measure_trampoline (void *arg)
Static trampoline from the hrt_call context; because we don't have a generic hrt wrapper yet.
Private Attributes
perf_counter_t _sample_perf
perf_counter_t _measure_interval
perf_counter_t _bad_transfers
perf_counter_t _bad_registers
perf_counter_t _duplicates
ringbuffer::RingBuffer * _accel_reports
struct accel_calibration_s _accel_scale
float _accel_range_scale
float _accel_range_m_s2
orb_advert_t _accel_topic
int _accel_orb_class_instance
int _accel_class_instance
float _accel_sample_rate
math::LowPassFilter2p _accel_filter_x
math::LowPassFilter2p _accel_filter_y
math::LowPassFilter2p _accel_filter_z
Integrator _accel_int
uint8_t _checked_values [BMI055_ACCEL_NUM_CHECKED_REGISTERS]
uint8_t _checked_bad [BMI055_ACCEL_NUM_CHECKED_REGISTERS]
float _last_temperature
bool _got_duplicate
Static Private Attributes
static const uint8_t _checked_registers [BMI055_ACCEL_NUM_CHECKED_REGISTERS]
Additional Inherited Members
Protected Attributes inherited from BMI055
uint8_t _whoami
struct hrt_call _call
whoami result
unsigned _call_interval
unsigned _dlpf_freq
uint8_t _register_wait
uint64_t _reset_wait
enum Rotation _rotation
uint8_t _checked_next
Detailed Description
Definition at line 151 of file BMI055_accel.hpp.
Constructor & Destructor Documentation
BMI055_accel::BMI055_accel (int bus, const char * path_accel, uint32_t device, enum Rotation rotation)
Definition at line 49 of file BMI055_accel.cpp.
References _accel_class_instance, _accel_filter_x, _accel_filter_y, _accel_filter_z, _accel_int, _accel_orb_class_instance, _accel_range_m_s2, _accel_range_scale, _accel_sample_rate, _accel_scale, _accel_topic, BMI055::_call, _got_duplicate, _last_temperature, BMI055_ACCEL_DEFAULT_DRIVER_FILTER_FREQ, BMI055_ACCEL_DEFAULT_RATE, BMI055_ACCEL_MAX_PUBLISH_RATE, DRV_ACC_DEVTYPE_BMI055, f(), accel_calibration_s::x_offset, accel_calibration_s::x_scale, accel_calibration_s::y_offset, accel_calibration_s::y_scale, accel_calibration_s::z_offset, and accel_calibration_s::z_scale.
BMI055_accel::~BMI055_accel () virtual
Definition at line 84 of file BMI055_accel.cpp.
References _accel_class_instance, _accel_reports, _bad_registers, _bad_transfers, _duplicates, _measure_interval, _sample_perf, ACCEL_BASE_DEVICE_PATH, perf_free(), and stop().
BMI055_accel::BMI055_accel (const BMI055_accel &) private
Member Function Documentation
int BMI055_accel::accel_set_sample_rate (float desired_sample_rate_hz) private
Definition at line 215 of file BMI055_accel.cpp.
References _accel_sample_rate, BMI055_ACC_BW, BMI055_ACCEL_BW_1000, BMI055_ACCEL_BW_125, BMI055_ACCEL_BW_15_63, BMI055_ACCEL_BW_250, BMI055_ACCEL_BW_31_25, BMI055_ACCEL_BW_500, BMI055_ACCEL_BW_62_5, BMI055_ACCEL_BW_7_81, modify_reg(), and OK.
Referenced by ioctl(), and reset().
void BMI055_accel::check_registers (void) private
Definition at line 559 of file BMI055_accel.cpp.
References _bad_registers, _checked_bad, BMI055::_checked_next, _checked_registers, _checked_values, BMI055::_register_wait, BMI055::_reset_wait, BMI055_ACC_SOFTRESET, BMI055_ACCEL_NUM_CHECKED_REGISTERS, BMI055_SOFT_RESET, hrt_absolute_time(), perf_count(), BMI055::read_reg(), and BMI055::write_reg().
Referenced by measure().
int BMI055_accel::init () virtual
Definition at line 107 of file BMI055_accel.cpp.
References _accel_class_instance, _accel_orb_class_instance, _accel_reports, _accel_scale, _accel_topic, ACCEL_BASE_DEVICE_PATH, accel_report, DEVICE_DEBUG, lis3mdl::init(), measure(), OK, orb_advertise_multi(), ORB_ID, ORB_PRIO_HIGH, ORB_PRIO_MAX, reset(), warnx, accel_calibration_s::x_offset, accel_calibration_s::x_scale, accel_calibration_s::y_offset, accel_calibration_s::y_scale, accel_calibration_s::z_offset, and accel_calibration_s::z_scale.
int BMI055_accel::ioctl (struct file * filp, int cmd, unsigned long arg) virtual
Definition at line 323 of file BMI055_accel.cpp.
References _accel_filter_x, _accel_filter_y, _accel_filter_z, _accel_range_m_s2, _accel_reports, _accel_sample_rate, _accel_scale, BMI055::_call, BMI055::_call_interval, accel_set_sample_rate(), ACCELIOCGRANGE, ACCELIOCGSAMPLERATE, ACCELIOCGSCALE, ACCELIOCSRANGE, ACCELIOCSSAMPLERATE, ACCELIOCSSCALE, BMI055_ACCEL_DEFAULT_RATE, BMI055_ACCEL_MAX_RATE, BMI055_TIMER_REDUCTION, CONSTANTS_ONE_G, f(), math::LowPassFilter2p::get_cutoff_freq(), OK, hrt_call::period, reset(), SENSOR_POLLRATE_DEFAULT, SENSOR_POLLRATE_EXTERNAL, SENSOR_POLLRATE_MANUAL, SENSOR_POLLRATE_MAX, SENSORIOCGPOLLRATE, SENSORIOCRESET, SENSORIOCSPOLLRATE, SENSORIOCSQUEUEDEPTH, set_accel_range(), math::LowPassFilter2p::set_cutoff_frequency(), start(), stop(), accel_calibration_s::x_scale, accel_calibration_s::y_scale, and accel_calibration_s::z_scale.
void BMI055_accel::measure () private
Fetch measurements from the sensor and update the report buffers.
Definition at line 602 of file BMI055_accel.cpp.
References _accel_filter_x, _accel_filter_y, _accel_filter_z, _accel_int, _accel_range_scale, _accel_reports, _accel_scale, _accel_topic, _bad_registers, _bad_transfers, _duplicates, _got_duplicate, _last_temperature, _measure_interval, BMI055::_register_wait, BMI055::_reset_wait, BMI055::_rotation, _sample_perf, accel_report, math::LowPassFilter2p::apply(), BMI055_ACC_TEMP, BMI055_ACC_X_L, BMI055_NEW_DATA_MASK, check_registers(), DIR_READ, hrt_absolute_time(), OK, ORB_ID, orb_publish(), perf_begin(), perf_count(), perf_end(), perf_event_count(), Integrator::put(), BMI055::read_reg(), rotate_3f(), accel_calibration_s::x_offset, accel_calibration_s::x_scale, accel_calibration_s::y_offset, accel_calibration_s::y_scale, accel_calibration_s::z_offset, and accel_calibration_s::z_scale.
Referenced by init(), measure_trampoline(), read(), and self_test().
void BMI055_accel::measure_trampoline (void * arg) static private
Static trampoline from the hrt_call context; because we don't have a generic hrt wrapper yet.
Called by the HRT in interrupt context at the specified rate if automatic polling is enabled.
Parameters
arg Instance pointer for the driver that is polling.
Definition at line 550 of file BMI055_accel.cpp.
References measure().
Referenced by start().
void BMI055_accel::modify_reg (unsigned reg, uint8_t clearbits, uint8_t setbits) private
Modify a register in the BMI055_accel.
Bits are cleared before bits are set.
Parameters
reg The register to modify.
clearbits Bits in the register to clear.
setbits Bits in the register to set.
Definition at line 459 of file BMI055_accel.cpp.
References BMI055::read_reg(), and write_checked_reg().
Referenced by accel_set_sample_rate(), and set_accel_range().
BMI055_accel BMI055_accel::operator= (const BMI055_accel &) private
void BMI055_accel::print_info ()
Diagnostics - print some basic information about the driver.
Definition at line 767 of file BMI055_accel.cpp.
References _accel_reports, _bad_registers, _bad_transfers, _checked_bad, BMI055::_checked_next, _checked_registers, _checked_values, _duplicates, _last_temperature, _measure_interval, _sample_perf, BMI055_ACCEL_NUM_CHECKED_REGISTERS, perf_print_counter(), PX4_INFO, and BMI055::read_reg().
void BMI055_accel::print_registers ()
Definition at line 803 of file BMI055_accel.cpp.
References _checked_registers, and BMI055::read_reg().
Referenced by test_error().
int BMI055_accel::probe () protected virtual
Definition at line 195 of file BMI055_accel.cpp.
References _checked_bad, _checked_values, BMI055::_whoami, BMI055_ACC_CHIP_ID, BMI055_ACC_WHO_AM_I, DEVICE_DEBUG, OK, and BMI055::read_reg().
ssize_t BMI055_accel::read (struct file * filp, char * buffer, size_t buflen) virtual
Definition at line 263 of file BMI055_accel.cpp.
References _accel_reports, BMI055::_call_interval, accel_report, and measure().
int BMI055_accel::reset () private
Reset chip.
Resets the chip and measurements ranges, but not scale and offset.
Definition at line 157 of file BMI055_accel.cpp.
References _checked_registers, _checked_values, accel_set_sample_rate(), BMI055_ACC_BW, BMI055_ACC_DRDY_INT1, BMI055_ACC_DRDY_INT_EN, BMI055_ACC_INT_EN_1, BMI055_ACC_INT_MAP_1, BMI055_ACC_PMU_LPW, BMI055_ACC_RANGE, BMI055_ACC_SOFTRESET, BMI055_ACCEL_BW_1000, BMI055_ACCEL_DEFAULT_RANGE_G, BMI055_ACCEL_DEFAULT_RATE, BMI055_ACCEL_NORMAL, BMI055_ACCEL_NUM_CHECKED_REGISTERS, BMI055_ACCEL_RANGE_2_G, BMI055_SOFT_RESET, OK, BMI055::read_reg(), set_accel_range(), write_checked_reg(), and BMI055::write_reg().
Referenced by init(), ioctl(), and start().
int BMI055_accel::self_test () private
Measurement self test.
Returns
0 on success, 1 on failure
Definition at line 301 of file BMI055_accel.cpp.
References _sample_perf, measure(), and perf_event_count().
int BMI055_accel::set_accel_range (unsigned max_g) private
Set the BMI055_accel measurement range.
Parameters
max_g The maximum G value the range must support.
Returns
OK if the value can be supported, -EINVAL otherwise.
Definition at line 483 of file BMI055_accel.cpp.
References _accel_range_m_s2, _accel_range_scale, BMI055_ACC_RANGE, BMI055_ACCEL_RANGE_16_G, BMI055_ACCEL_RANGE_2_G, BMI055_ACCEL_RANGE_4_G, BMI055_ACCEL_RANGE_8_G, CONSTANTS_ONE_G, modify_reg(), and OK.
Referenced by ioctl(), and reset().
void BMI055_accel::start () private
Start automatic measurement.
Definition at line 527 of file BMI055_accel.cpp.
References _accel_reports, BMI055::_call, BMI055::_call_interval, BMI055_TIMER_REDUCTION, hrt_call_every(), measure_trampoline(), reset(), and stop().
Referenced by ioctl().
void BMI055_accel::stop () private
Stop automatic measurement.
Definition at line 544 of file BMI055_accel.cpp.
References BMI055::_call, and hrt_cancel().
Referenced by ioctl(), start(), and ~BMI055_accel().
void BMI055_accel::test_error ()
Definition at line 315 of file BMI055_accel.cpp.
References BMI055_ACC_SOFTRESET, BMI055_SOFT_RESET, print_registers(), and BMI055::write_reg().
void BMI055_accel::write_checked_reg (unsigned reg, uint8_t value) private
Write a register in the BMI055_accel, updating _checked_values.
Parameters
reg The register to write.
value The new value to write.
Definition at line 470 of file BMI055_accel.cpp.
References _checked_bad, _checked_registers, _checked_values, BMI055_ACCEL_NUM_CHECKED_REGISTERS, and BMI055::write_reg().
Referenced by modify_reg(), and reset().
Member Data Documentation
int BMI055_accel::_accel_class_instance private
Definition at line 192 of file BMI055_accel.hpp.
Referenced by BMI055_accel(), init(), and ~BMI055_accel().
math::LowPassFilter2p BMI055_accel::_accel_filter_x private
Definition at line 196 of file BMI055_accel.hpp.
Referenced by BMI055_accel(), ioctl(), and measure().
math::LowPassFilter2p BMI055_accel::_accel_filter_y private
Definition at line 197 of file BMI055_accel.hpp.
Referenced by BMI055_accel(), ioctl(), and measure().
math::LowPassFilter2p BMI055_accel::_accel_filter_z private
Definition at line 198 of file BMI055_accel.hpp.
Referenced by BMI055_accel(), ioctl(), and measure().
Integrator BMI055_accel::_accel_int private
Definition at line 200 of file BMI055_accel.hpp.
Referenced by BMI055_accel(), and measure().
int BMI055_accel::_accel_orb_class_instance private
Definition at line 191 of file BMI055_accel.hpp.
Referenced by BMI055_accel(), and init().
float BMI055_accel::_accel_range_m_s2 private
Definition at line 188 of file BMI055_accel.hpp.
Referenced by BMI055_accel(), ioctl(), and set_accel_range().
float BMI055_accel::_accel_range_scale private
Definition at line 187 of file BMI055_accel.hpp.
Referenced by BMI055_accel(), measure(), and set_accel_range().
ringbuffer::RingBuffer* BMI055_accel::_accel_reports private
Definition at line 184 of file BMI055_accel.hpp.
Referenced by init(), ioctl(), measure(), print_info(), read(), start(), and ~BMI055_accel().
float BMI055_accel::_accel_sample_rate private
Definition at line 194 of file BMI055_accel.hpp.
Referenced by accel_set_sample_rate(), BMI055_accel(), and ioctl().
struct accel_calibration_s BMI055_accel::_accel_scale private
Definition at line 186 of file BMI055_accel.hpp.
Referenced by BMI055_accel(), init(), ioctl(), and measure().
orb_advert_t BMI055_accel::_accel_topic private
Definition at line 190 of file BMI055_accel.hpp.
Referenced by BMI055_accel(), init(), and measure().
perf_counter_t BMI055_accel::_bad_registers private
Definition at line 181 of file BMI055_accel.hpp.
Referenced by check_registers(), measure(), print_info(), and ~BMI055_accel().
perf_counter_t BMI055_accel::_bad_transfers private
Definition at line 180 of file BMI055_accel.hpp.
Referenced by measure(), print_info(), and ~BMI055_accel().
uint8_t BMI055_accel::_checked_bad[BMI055_ACCEL_NUM_CHECKED_REGISTERS] private
Definition at line 208 of file BMI055_accel.hpp.
Referenced by check_registers(), print_info(), probe(), and write_checked_reg().
const uint8_t BMI055_accel::_checked_registers static private
Initial value:
= {    BMI055_ACC_CHIP_ID,
                                              BMI055_ACC_BW,
                                              BMI055_ACC_RANGE,
                                              BMI055_ACC_INT_EN_1,
                                              BMI055_ACC_INT_MAP_1,
                                             }
Definition at line 206 of file BMI055_accel.hpp.
Referenced by check_registers(), print_info(), print_registers(), reset(), and write_checked_reg().
uint8_t BMI055_accel::_checked_values[BMI055_ACCEL_NUM_CHECKED_REGISTERS] private
Definition at line 207 of file BMI055_accel.hpp.
Referenced by check_registers(), print_info(), probe(), reset(), and write_checked_reg().
perf_counter_t BMI055_accel::_duplicates private
Definition at line 182 of file BMI055_accel.hpp.
Referenced by measure(), print_info(), and ~BMI055_accel().
bool BMI055_accel::_got_duplicate private
Definition at line 213 of file BMI055_accel.hpp.
Referenced by BMI055_accel(), and measure().
float BMI055_accel::_last_temperature private
Definition at line 211 of file BMI055_accel.hpp.
Referenced by BMI055_accel(), measure(), and print_info().
perf_counter_t BMI055_accel::_measure_interval private
Definition at line 179 of file BMI055_accel.hpp.
Referenced by measure(), print_info(), and ~BMI055_accel().
perf_counter_t BMI055_accel::_sample_perf private
Definition at line 178 of file BMI055_accel.hpp.
Referenced by measure(), print_info(), self_test(), and ~BMI055_accel().
The documentation for this class was generated from the following files:
src/drivers/imu/bmi055/BMI055_accel.hpp
src/drivers/imu/bmi055/BMI055_accel.cpp