PX4 Firmware: src/systemcmds/bl_update/bl_update.c File Reference
bl_update.c File Reference
STM32F4 bootloader update tool.
#include <px4_config.h>
#include <px4_log.h>
#include <px4_module.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <stdbool.h>
#include <unistd.h>
#include <fcntl.h>
#include <sys/stat.h>
#include <arch/board/board.h>
#include <nuttx/progmem.h>
Macros
#define BL_FILE_SIZE_LIMIT 16384
Functions
__EXPORT int bl_update_main (int argc, char *argv[])
Detailed Description
STM32F4 bootloader update tool.
Definition in file bl_update.c.
Macro Definition Documentation
#define BL_FILE_SIZE_LIMIT 16384
Definition at line 57 of file bl_update.c.
Referenced by bl_update_main().
Function Documentation
int bl_update_main (int argc, char * argv[])
Definition at line 81 of file bl_update.c.
References BL_FILE_SIZE_LIMIT, fd, print_usage(), PX4_ERR, PX4_INFO, PX4_WARN, read(), and usleep().