PX4 Firmware: src/drivers/stm32/drv_io_timer.h File Reference
drv_io_timer.h File Reference
#include <px4_config.h>
#include <nuttx/arch.h>
#include <nuttx/irq.h>
#include <drivers/drv_hrt.h>
Classes
struct io_timers_t
struct timer_io_channels_t
Macros
#define MAX_IO_TIMERS 5
#define MAX_TIMER_IO_CHANNELS 8
#define MAX_LED_TIMERS 2
#define MAX_TIMER_LED_CHANNELS 6
#define IO_TIMER_ALL_MODES_CHANNELS 0
Typedefs
typedef enum io_timer_channel_mode_t io_timer_channel_mode_t
typedef uint8_t io_timer_channel_allocation_t
typedef struct io_timers_t io_timers_t
typedef struct timer_io_channels_t timer_io_channels_t
typedef void(* channel_handler_t) (void *context, const io_timers_t *timer, uint32_t chan_index, const timer_io_channels_t *chan, hrt_abstime isrs_time, uint16_t isrs_rcnt)
Enumerations
enum io_timer_channel_mode_t {
IOTimerChanMode_NotUsed = 0, IOTimerChanMode_PWMOut = 1, IOTimerChanMode_PWMIn = 2, IOTimerChanMode_Capture = 3,
IOTimerChanMode_OneShot = 4, IOTimerChanMode_Trigger = 5, IOTimerChanModeSize, IOTimerChanMode_NotUsed = 0,
IOTimerChanMode_PWMOut = 1, IOTimerChanMode_PWMIn = 2, IOTimerChanMode_Capture = 3, IOTimerChanMode_OneShot = 4,
IOTimerChanMode_Trigger = 5, IOTimerChanModeSize, IOTimerChanMode_NotUsed = 0, IOTimerChanMode_PWMOut = 1,
IOTimerChanMode_PWMIn = 2, IOTimerChanMode_Capture = 3, IOTimerChanMode_OneShot = 4, IOTimerChanMode_Trigger = 5,
IOTimerChanModeSize
}
Functions
__EXPORT int io_timer_handler0 (int irq, void *context, void *arg)
__EXPORT int io_timer_handler1 (int irq, void *context, void *arg)
__EXPORT int io_timer_handler2 (int irq, void *context, void *arg)
__EXPORT int io_timer_handler3 (int irq, void *context, void *arg)
__EXPORT int io_timer_handler4 (int irq, void *context, void *arg)
__EXPORT int io_timer_channel_init (unsigned channel, io_timer_channel_mode_t mode, channel_handler_t channel_handler, void *context)
__EXPORT int io_timer_init_timer (unsigned timer)
__EXPORT int io_timer_set_rate (unsigned timer, unsigned rate)
__EXPORT int io_timer_set_enable (bool state, io_timer_channel_mode_t mode, io_timer_channel_allocation_t masks)
__EXPORT uint16_t io_channel_get_ccr (unsigned channel)
__EXPORT int io_timer_set_ccr (unsigned channel, uint16_t value)
__EXPORT uint32_t io_timer_get_group (unsigned timer)
__EXPORT int io_timer_validate_channel_index (unsigned channel)
__EXPORT int io_timer_is_channel_free (unsigned channel)
__EXPORT int io_timer_free_channel (unsigned channel)
__EXPORT int io_timer_get_channel_mode (unsigned channel)
__EXPORT int io_timer_get_mode_channels (io_timer_channel_mode_t mode)
__EXPORT void io_timer_trigger (void)
Variables
__EXPORT const io_timers_t io_timers [MAX_IO_TIMERS]
__EXPORT const timer_io_channels_t timer_io_channels [MAX_TIMER_IO_CHANNELS]
__EXPORT const io_timers_t led_pwm_timers [MAX_LED_TIMERS]
__EXPORT const timer_io_channels_t led_pwm_channels [MAX_TIMER_LED_CHANNELS]
__EXPORT io_timer_channel_allocation_t allocations [IOTimerChanModeSize]
Macro Definition Documentation
#define IO_TIMER_ALL_MODES_CHANNELS 0
Definition at line 54 of file drv_io_timer.h.
#define MAX_IO_TIMERS 5
Definition at line 48 of file drv_io_timer.h.
#define MAX_LED_TIMERS 2
Definition at line 51 of file drv_io_timer.h.
#define MAX_TIMER_IO_CHANNELS 8
Definition at line 49 of file drv_io_timer.h.
#define MAX_TIMER_LED_CHANNELS 6
Definition at line 52 of file drv_io_timer.h.
Typedef Documentation
typedef void(* channel_handler_t) (void *context, const io_timers_t *timer, uint32_t chan_index, const timer_io_channels_t *chan, hrt_abstime isrs_time, uint16_t isrs_rcnt)
Definition at line 98 of file drv_io_timer.h.
typedef uint8_t io_timer_channel_allocation_t
Definition at line 66 of file drv_io_timer.h.
typedef enum io_timer_channel_mode_t io_timer_channel_mode_t
typedef struct io_timers_t io_timers_t
typedef struct timer_io_channels_t timer_io_channels_t
Enumeration Type Documentation
enum io_timer_channel_mode_t
Enumerator
IOTimerChanMode_NotUsed
IOTimerChanMode_PWMOut
IOTimerChanMode_PWMIn
IOTimerChanMode_Capture
IOTimerChanMode_OneShot
IOTimerChanMode_Trigger
IOTimerChanModeSize
IOTimerChanMode_NotUsed
IOTimerChanMode_PWMOut
IOTimerChanMode_PWMIn
IOTimerChanMode_Capture
IOTimerChanMode_OneShot
IOTimerChanMode_Trigger
IOTimerChanModeSize
IOTimerChanMode_NotUsed
IOTimerChanMode_PWMOut
IOTimerChanMode_PWMIn
IOTimerChanMode_Capture
IOTimerChanMode_OneShot
IOTimerChanMode_Trigger
IOTimerChanModeSize
Definition at line 56 of file drv_io_timer.h.
Function Documentation
__EXPORT uint16_t io_channel_get_ccr (unsigned channel)
Definition at line 870 of file drv_io_timer.c.
References channels_timer(), io_timer_get_channel_mode(), io_timer_validate_channel_index(), IOTimerChanMode_OneShot, IOTimerChanMode_PWMOut, IOTimerChanMode_Trigger, REG, and timer_io_channels.
Referenced by up_pwm_servo_get().
__EXPORT int io_timer_channel_init (unsigned channel, io_timer_channel_mode_t mode, channel_handler_t channel_handler, void * context)
Definition at line 645 of file drv_io_timer.c.
References allocate_channel(), channel_handler_entry::callback, CCER_C1_INIT, CCER_C1_NUM_BITS, CCMR_C1_CAPTURE_INIT, CCMR_C1_NUM_BITS, CCMR_C1_PWMIN_INIT, CCMR_C1_PWMOUT_INIT, CCMR_C1_RESET, channel_handlers, channels_timer(), CnSC_CAPTURE_INIT, CnSC_PWMOUT_INIT, CnSC_RESET, channel_handler_entry::context, timer_io_channels_t::gpio_in, io_timer_init_timer(), IOTimerChanMode_Capture, IOTimerChanMode_NotUsed, IOTimerChanMode_OneShot, IOTimerChanMode_PWMIn, IOTimerChanMode_PWMOut, IOTimerChanMode_Trigger, rCCER, rDIER, REG, timer_io_channels_t::timer_channel, timer_io_channels, and UNUSED.
Referenced by up_input_capture_set(), up_pwm_servo_init(), up_pwm_trigger_deinit(), and up_pwm_trigger_init().
__EXPORT int io_timer_free_channel (unsigned channel)
Definition at line 423 of file drv_io_timer.c.
References free_channel_resource(), io_timer_get_channel_mode(), io_timer_set_enable(), io_timer_validate_channel_index(), and IOTimerChanMode_NotUsed.
Referenced by up_input_capture_set(), up_pwm_servo_init(), and up_pwm_trigger_init().
__EXPORT int io_timer_get_channel_mode (unsigned channel)
Definition at line 357 of file drv_io_timer.c.
References channel_allocations, IOTimerChanMode_NotUsed, and IOTimerChanModeSize.
Referenced by free_channel_resource(), io_channel_get_ccr(), io_timer_free_channel(), io_timer_set_ccr(), up_input_capture_get_callback(), up_input_capture_get_filter(), up_input_capture_get_trigger(), up_input_capture_set_callback(), up_input_capture_set_filter(), and up_input_capture_set_trigger().
__EXPORT uint32_t io_timer_get_group (unsigned timer)
Definition at line 887 of file drv_io_timer.c.
References get_timer_channels().
Referenced by up_pwm_servo_get_rate_group().
__EXPORT int io_timer_get_mode_channels (io_timer_channel_mode_t mode)
Definition at line 348 of file drv_io_timer.c.
References channel_allocations, and IOTimerChanModeSize.
Referenced by io_timer_trigger(), up_pwm_servo_get_rate_group(), up_pwm_servo_init(), and up_pwm_trigger_deinit().
__EXPORT int io_timer_handler0 (int irq, void * context, void * arg)
Definition at line 217 of file drv_io_timer.c.
References io_timer_handler().
__EXPORT int io_timer_handler1 (int irq, void * context, void * arg)
Definition at line 223 of file drv_io_timer.c.
References io_timer_handler().
__EXPORT int io_timer_handler2 (int irq, void * context, void * arg)
Definition at line 229 of file drv_io_timer.c.
References io_timer_handler().
__EXPORT int io_timer_handler3 (int irq, void * context, void * arg)
Definition at line 235 of file drv_io_timer.c.
References io_timer_handler().
__EXPORT int io_timer_handler4 (int irq, void * context, void * arg)
Definition at line 235 of file drv_io_timer.c.
References io_timer_handler().
__EXPORT int io_timer_init_timer (unsigned timer)
Definition at line 535 of file drv_io_timer.c.
References _REG, io_timers_t::clock_bit, io_timer_set_PWM_mode(), io_timers, is_timer_uninitalized(), rBDTR, rCCER, rCCMR1, rCCMR2, rCCR1, rCCR2, rCCR3, rCCR4, rCNT, rCONF, rCR1, rCR2, rDCR, rDIER, rMODE, rSC, rSMCR, rSYNCONF, set_timer_initalized(), and timer_set_rate().
Referenced by io_timer_channel_init().
__EXPORT int io_timer_is_channel_free (unsigned channel)
Definition at line 315 of file drv_io_timer.c.
References channel_allocations, io_timer_validate_channel_index(), and IOTimerChanMode_NotUsed.
Referenced by allocate_channel_resource(), up_input_capture_set(), up_pwm_servo_init(), and up_pwm_trigger_init().
__EXPORT int io_timer_set_ccr (unsigned channel, uint16_t value)
Definition at line 835 of file drv_io_timer.c.
References channels_timer(), io_timer_get_channel_mode(), io_timer_validate_channel_index(), IOTimerChanMode_OneShot, IOTimerChanMode_PWMOut, IOTimerChanMode_Trigger, REG, rSC, and timer_io_channels.
Referenced by up_pwm_servo_set(), and up_pwm_trigger_set().
__EXPORT int io_timer_set_enable (bool state, io_timer_channel_mode_t mode, io_timer_channel_allocation_t masks)
Definition at line 715 of file drv_io_timer.c.
References _REG, _REG32, arraySize, io_timers_t::base, CCER_C1_INIT, CCER_C1_NUM_BITS, channel_allocations, channels_timer(), CnSC_PWMOUT_INIT, FTM_SYNC, timer_io_channels_t::gpio_out, IO_TIMER_ALL_MODES_CHANNELS, io_timer_validate_channel_index(), io_timers, IOTimerChanMode_Capture, IOTimerChanMode_NotUsed, IOTimerChanMode_OneShot, IOTimerChanMode_PWMIn, IOTimerChanMode_PWMOut, IOTimerChanMode_Trigger, MAX_CHANNELS_PER_TIMER, MAX_IO_TIMERS, MAX_TIMER_IO_CHANNELS, rCR1, rEGR, timer_io_channels_t::timer_channel, and timer_io_channels.
Referenced by io_timer_free_channel(), up_input_capture_set(), up_pwm_servo_arm(), and up_pwm_trigger_arm().
__EXPORT int io_timer_set_rate (unsigned timer, unsigned rate)
Definition at line 592 of file drv_io_timer.c.
References channel_allocations, get_timer_channels(), io_timer_set_oneshot_mode(), io_timer_set_PWM_mode(), IOTimerChanMode_NotUsed, IOTimerChanMode_OneShot, IOTimerChanMode_PWMOut, OK, reallocate_channel_resources(), and timer_set_rate().
Referenced by up_pwm_servo_set_rate_group_update().
__EXPORT void io_timer_trigger (void)
Definition at line 506 of file drv_io_timer.c.
References _REG32, io_timers_t::base, FTM_SYNC, get_timer_channels(), io_timer_get_mode_channels(), io_timers, IOTimerChanMode_OneShot, MAX_IO_TIMERS, and validate_timer_index().
Referenced by up_pwm_update().
__EXPORT int io_timer_validate_channel_index (unsigned channel)
Definition at line 328 of file drv_io_timer.c.
References io_timers, MAX_TIMER_IO_CHANNELS, timer_io_channels_t::timer_index, and timer_io_channels.
Referenced by allocate_channel(), io_channel_get_ccr(), io_timer_free_channel(), io_timer_is_channel_free(), io_timer_set_ccr(), io_timer_set_enable(), up_input_capture_get_callback(), up_input_capture_get_filter(), up_input_capture_get_stats(), up_input_capture_get_trigger(), up_input_capture_set(), up_input_capture_set_callback(), up_input_capture_set_filter(), and up_input_capture_set_trigger().
Variable Documentation
__EXPORT io_timer_channel_allocation_t allocations[IOTimerChanModeSize]
__EXPORT const io_timers_t io_timers[MAX_IO_TIMERS]
Definition at line 53 of file timer_config.c.
Referenced by get_timer_channels(), get_timers_firstchannels(), io_timer_handler(), io_timer_init_timer(), io_timer_set_enable(), io_timer_set_oneshot_mode(), io_timer_set_PWM_mode(), io_timer_trigger(), io_timer_validate_channel_index(), up_pwm_servo_set_rate_group_update(), and validate_timer_index().
__EXPORT const timer_io_channels_t led_pwm_channels[MAX_TIMER_LED_CHANNELS]
Definition at line 65 of file timer_config.c.
__EXPORT const io_timers_t led_pwm_timers[MAX_LED_TIMERS]
Definition at line 62 of file timer_config.c.
__EXPORT const timer_io_channels_t timer_io_channels[MAX_TIMER_IO_CHANNELS]
Definition at line 77 of file timer_config.c.
Referenced by channels_timer(), get_timers_firstchannels(), io_channel_get_ccr(), io_timer_channel_init(), io_timer_handler(), io_timer_set_ccr(), io_timer_set_enable(), io_timer_validate_channel_index(), up_input_capture_get_filter(), up_input_capture_get_trigger(), up_input_capture_set(), up_input_capture_set_filter(), and up_input_capture_set_trigger().