PX4 Firmware: src/systemcmds/tests/tests_main.c File Reference
tests_main.c File Reference
Tests main file, loads individual tests.
#include "tests_main.h"
#include <px4_config.h>
#include <stdio.h>
#include <string.h>
#include <fcntl.h>
#include <errno.h>
Macros
#define TESTS_EIGEN_DISABLE
#define OPT_NOHELP (1<<0)
#define OPT_NOALLTEST (1<<1)
#define OPT_NOJIGTEST (1<<2)
#define NTESTS (sizeof(tests) / sizeof(tests[0]))
Functions
static int test_help (int argc, char *argv[])
static int test_runner (unsigned option)
static int test_all (int argc, char *argv[])
static int test_jig (int argc, char *argv[])
__EXPORT int tests_main (int argc, char *argv[])
Executes system tests.
Variables
struct {
const char * name
int(* fn)(int argc, char *argv[])
unsigned options
} tests []
Detailed Description
Tests main file, loads individual tests.
Author
Lorenz Meier lm@in.nosp@m.f.et.nosp@m.hz.ch
Definition in file tests_main.c.
Macro Definition Documentation
#define NTESTS (sizeof(tests) / sizeof(tests[0]))
Definition at line 141 of file tests_main.c.
Referenced by test_runner().
#define OPT_NOALLTEST (1<<1)
Definition at line 74 of file tests_main.c.
Referenced by test_all().
#define OPT_NOHELP (1<<0)
Definition at line 73 of file tests_main.c.
#define OPT_NOJIGTEST (1<<2)
Definition at line 75 of file tests_main.c.
Referenced by test_jig().
#define TESTS_EIGEN_DISABLE
Definition at line 51 of file tests_main.c.
Function Documentation
static int test_all (int argc, char * argv[]) static
Definition at line 158 of file tests_main.c.
References OPT_NOALLTEST, and test_runner().
static int test_help (int argc, char * argv[]) static
Definition at line 144 of file tests_main.c.
References name, and tests.
static int test_jig (int argc, char * argv[]) static
Definition at line 164 of file tests_main.c.
References OPT_NOJIGTEST, and test_runner().
static int test_runner (unsigned option) static
Definition at line 170 of file tests_main.c.
References fn, name, NTESTS, tests, and tests_main().
Referenced by test_all(), and test_jig().
int tests_main (int argc, char * argv[])
Executes system tests.
Definition at line 268 of file tests_main.c.
References fn, name, and tests.
Referenced by test_runner().
Variable Documentation
int(* fn) (int argc, char *argv[])
Definition at line 71 of file tests_main.c.
Referenced by px4io_main(), test_runner(), and tests_main().
const char* name
Definition at line 70 of file tests_main.c.
Referenced by test_help(), test_runner(), and tests_main().
unsigned options
Definition at line 72 of file tests_main.c.
const { ... } tests[]
Referenced by test_help(), test_runner(), and tests_main().