PX4 Firmware: src/drivers/power_monitor/voxlpm/voxlpm_main.cpp File Reference
voxlpm_main.cpp File Reference
#include <px4_platform_common/getopt.h>
#include <px4_platform_common/module.h>
#include "voxlpm.hpp"
Classes
struct voxlpm::voxlpm_chan
struct voxlpm::voxlpm_bus_option
Namespaces
voxlpm
Local functions in support of the shell command.
Macros
#define NUM_BUS_OPTIONS (sizeof(bus_options)/sizeof(bus_options[0]))
Enumerations
enum VOXLPM_BUS { VOXLPM_BUS_I2C_EXTERNAL, VOXLPM_BUS_I2C_EXTERNAL1, VOXLPM_BUS_I2C_EXTERNAL2 }
Functions
bool voxlpm::start_bus (struct voxlpm_bus_option &bus)
Start the driver.
void voxlpm::start (enum VOXLPM_BUS busid)
void voxlpm::info ()
Print a little info about the driver.
void voxlpm::usage ()
Prints info about the driver argument usage.
__EXPORT int voxlpm_main (int argc, char *argv[])
Variables
struct voxlpm::voxlpm_bus_option voxlpm::bus_options []
Macro Definition Documentation
NUM_BUS_OPTIONS
#define NUM_BUS_OPTIONS (sizeof(bus_options)/sizeof(bus_options[0]))
Definition at line 85 of file voxlpm_main.cpp.
Referenced by voxlpm::info(), and voxlpm::start().
Enumeration Type Documentation
VOXLPM_BUS
enum VOXLPM_BUS
Enumerator
VOXLPM_BUS_I2C_EXTERNAL
VOXLPM_BUS_I2C_EXTERNAL1
VOXLPM_BUS_I2C_EXTERNAL2
Definition at line 39 of file voxlpm_main.cpp.
Function Documentation
voxlpm_main()
__EXPORT int voxlpm_main (int argc, char * argv[])
Definition at line 179 of file voxlpm_main.cpp.
References voxlpm::info(), voxlpm::start(), voxlpm::usage(), VOXLPM_BUS_I2C_EXTERNAL, VOXLPM_BUS_I2C_EXTERNAL1, and VOXLPM_BUS_I2C_EXTERNAL2.