PX4 Firmware: src/lib/matrix/test/dual.cpp File Reference
dual.cpp File Reference
#include "test_macros.hpp"
#include <matrix/math.hpp>
#include <iostream>
Functions
template<typename Scalar , size_t N>
bool isEqualAll (Dual< Scalar, N > a, Dual< Scalar, N > b)
template<typename T >
T testFunction (const Vector< T, 3 > &point)
template<typename Scalar >
Vector< Scalar, 3 > positionError (const Vector< Scalar, 3 > &positionState, const Vector< Scalar, 3 > &velocityStateBody, const Quaternion< Scalar > &bodyOrientation, const Vector< Scalar, 3 > &positionMeasurement, Scalar dt)
int main ()
Function Documentation
isEqualAll()
template<typename Scalar , size_t N> bool isEqualAll (Dual< Scalar, N > a, Dual< Scalar, N > b)
Definition at line 8 of file dual.cpp.
References matrix::Dual< Scalar, N >::derivative, matrix::isEqualF(), and matrix::Dual< Scalar, N >::value.
Referenced by main().
main()
int main ()
Definition at line 33 of file dual.cpp.
References matrix::abs(), matrix::acos(), matrix::asin(), matrix::atan(), matrix::atan2(), matrix::ceil(), matrix::Matrix< Type, M, N >::col(), matrix::collectDerivatives(), matrix::collectReals(), matrix::cos(), matrix::Dual< Scalar, N >::derivative, dt, f(), matrix::floor(), matrix::fmod(), matrix::isEqual(), isEqualAll(), matrix::isEqualF(), matrix::IsFinite(), matrix::IsInf(), matrix::IsNan(), matrix::max(), matrix::min(), positionError(), matrix::sin(), matrix::sqrt(), matrix::tan(), TEST, testFunction(), and matrix::Dual< Scalar, N >::value.
positionError()
template<typename Scalar > Vector<Scalar, 3> positionError (const Vector< Scalar, 3 > & positionState, const Vector< Scalar, 3 > & velocityStateBody, const Quaternion< Scalar > & bodyOrientation, const Vector< Scalar, 3 > & positionMeasurement, Scalar dt)
Definition at line 23 of file dual.cpp.
References matrix::Quaternion< Type >::conjugate(), and dt.
Referenced by main().
testFunction()
template<typename T > T testFunction (const Vector< T, 3 > & point)
Definition at line 14 of file dual.cpp.
Referenced by main().