PX4 Firmware: OcpocADC Class Reference
OcpocADC Class Reference
Public Member Functions
OcpocADC ()
virtual ~OcpocADC ()
virtual int init ()
virtual ssize_t devRead (void *buf, size_t count) override
virtual int devIOCTL (unsigned long request, unsigned long arg) override
Protected Member Functions
virtual void _measure () override
Private Member Functions
int read (px4_adc_msg_t(*buf)[PX4_MAX_ADC_CHANNELS], unsigned int len)
Private Attributes
pthread_mutex_t _samples_lock
px4_adc_msg_t _samples
Detailed Description
Definition at line 62 of file ocpoc_adc.cpp.
Constructor & Destructor Documentation
OcpocADC::OcpocADC ()
Definition at line 83 of file ocpoc_adc.cpp.
References _samples_lock, and pthread_mutex_init().
Referenced by ocpoc_adc_main().
OcpocADC::~OcpocADC () virtual
Definition at line 89 of file ocpoc_adc.cpp.
References _samples_lock, and pthread_mutex_destroy().
Member Function Documentation
void OcpocADC::_measure (void) override protected virtual
Definition at line 94 of file ocpoc_adc.cpp.
References _samples, _samples_lock, pthread_mutex_lock(), pthread_mutex_unlock(), px4_adc_msg_t, PX4_ERR, PX4_MAX_ADC_CHANNELS, and read().
int OcpocADC::devIOCTL (unsigned long request, unsigned long arg) override virtual
Definition at line 123 of file ocpoc_adc.cpp.
ssize_t OcpocADC::devRead (void * buf, size_t count) override virtual
Definition at line 128 of file ocpoc_adc.cpp.
References _samples, _samples_lock, and pthread_mutex_unlock().
Referenced by ocpoc_adc_main().
int OcpocADC::init () virtual
Definition at line 109 of file ocpoc_adc.cpp.
References lis3mdl::init(), PX4_ERR, and PX4_OK.
Referenced by ocpoc_adc_main().
int OcpocADC::read (px4_adc_msg_t(*) buf[PX4_MAX_ADC_CHANNELS], unsigned int len) private
Definition at line 149 of file ocpoc_adc.cpp.
References ADC_BATTERY_VOLTAGE_CHANNEL, and ADC_VOLTAGE_PATH.
Referenced by _measure().
Member Data Documentation
px4_adc_msg_t OcpocADC::_samples private
Definition at line 80 of file ocpoc_adc.cpp.
Referenced by _measure(), and devRead().
pthread_mutex_t OcpocADC::_samples_lock private
Definition at line 79 of file ocpoc_adc.cpp.
Referenced by _measure(), devRead(), OcpocADC(), and ~OcpocADC().
The documentation for this class was generated from the following file:
src/drivers/ocpoc_adc/ocpoc_adc.cpp