PX4 Firmware: MixingOutput::Command Struct Reference
MixingOutput::Command Struct Reference
Public Types
enum Type : int { Type::None, Type::resetMixer, Type::loadMixer }
Public Attributes
px4::atomic< int > command {(int)Type::None}
const char * mixer_buf
unsigned mixer_buf_length
int result
Detailed Description
Definition at line 205 of file mixer_module.hpp.
Member Enumeration Documentation
Type
enum MixingOutput::Command::Type : int strong
Enumerator
None
resetMixer
loadMixer
Definition at line 206 of file mixer_module.hpp.
Member Data Documentation
command
px4::atomic<int> MixingOutput::Command::command {(int)Type::None}
Definition at line 211 of file mixer_module.hpp.
Referenced by MixingOutput::handleCommands(), MixingOutput::loadMixerThreadSafe(), and MixingOutput::resetMixerThreadSafe().
mixer_buf
const char* MixingOutput::Command::mixer_buf
Definition at line 212 of file mixer_module.hpp.
Referenced by MixingOutput::handleCommands(), and MixingOutput::loadMixerThreadSafe().
mixer_buf_length
unsigned MixingOutput::Command::mixer_buf_length
Definition at line 213 of file mixer_module.hpp.
Referenced by MixingOutput::handleCommands(), and MixingOutput::loadMixerThreadSafe().
result
int MixingOutput::Command::result
Definition at line 214 of file mixer_module.hpp.
Referenced by MixingOutput::handleCommands(), and MixingOutput::loadMixerThreadSafe().
The documentation for this struct was generated from the following file:
src/lib/mixer_module/mixer_module.hpp