PX4 Firmware: src/lib/mathlib/math/test/test.hpp File Reference
test.hpp File Reference
Controller library code.
Functions
bool equal (float a, float b, float eps=1e-5)
bool greater_than (float a, float b)
bool less_than (float a, float b)
bool greater_than_or_equal (float a, float b)
bool less_than_or_equal (float a, float b)
void float2SigExp (const float &num, float &sig, int &exp)
Detailed Description
Controller library code.
Definition in file test.hpp.
Function Documentation
bool equal (float a, float b, float eps = 1e-5)
Definition at line 48 of file test.cpp.
Referenced by control::blockDelayTest(), blockDelayTest(), control::blockDerivativeTest(), blockDerivativeTest(), control::blockHighPassTest(), blockHighPassTest(), blockIntegralTest(), control::blockIntegralTest(), blockIntegralTrapTest(), control::blockIntegralTrapTest(), control::blockLimitSymTest(), blockLimitSymTest(), control::blockLimitTest(), blockLimitTest(), control::blockLowPass2Test(), blockLowPass2Test(), blockLowPassTest(), control::blockLowPassTest(), control::blockOutputTest(), blockOutputTest(), control::blockPDTest(), blockPDTest(), control::blockPIDTest(), blockPIDTest(), control::blockPITest(), blockPITest(), blockPTest(), control::blockPTest(), blockRandGaussTest(), control::blockRandGaussTest(), blockRandUniformTest(), control::blockRandUniformTest(), control::blockStatsTest(), blockStatsTest(), matrix::isEqual(), and matrix::isEqualF().
void float2SigExp (const float & num, float & sig, int & exp)
Definition at line 103 of file test.cpp.
References f().
bool greater_than (float a, float b)
Definition at line 59 of file test.cpp.
bool greater_than_or_equal (float a, float b)
Definition at line 81 of file test.cpp.
Referenced by control::blockRandUniformTest(), and blockRandUniformTest().
bool less_than (float a, float b)
Definition at line 70 of file test.cpp.
bool less_than_or_equal (float a, float b)
Definition at line 92 of file test.cpp.
Referenced by control::blockRandUniformTest(), and blockRandUniformTest().