PX4 Firmware: ReadBuffer Class Reference
ReadBuffer Class Reference
Public Member Functions
int read (int fd)
void move (void *dest, size_t pos, size_t n)
Public Attributes
uint8_t buffer [512] = {}
size_t buf_size = 0
Static Public Attributes
static const size_t BUFFER_THRESHOLD = sizeof(buffer) * 0.8
Detailed Description
Definition at line 72 of file protocol_splitter.cpp.
Member Function Documentation
move()
void ReadBuffer::move (void * dest, size_t pos, size_t n)
Definition at line 109 of file protocol_splitter.cpp.
Referenced by Mavlink2Dev::read(), and RtpsDev::read().
read()
int ReadBuffer::read (int fd)
Definition at line 84 of file protocol_splitter.cpp.
References read().
Referenced by Mavlink2Dev::read(), and RtpsDev::read().
Member Data Documentation
buf_size
size_t ReadBuffer::buf_size = 0
Definition at line 79 of file protocol_splitter.cpp.
Referenced by Mavlink2Dev::read(), and RtpsDev::read().
buffer
uint8_t ReadBuffer::buffer[512] = {}
Definition at line 78 of file protocol_splitter.cpp.
Referenced by Mavlink2Dev::read(), and RtpsDev::read().
BUFFER_THRESHOLD
const size_t ReadBuffer::BUFFER_THRESHOLD = sizeof(buffer) * 0.8 static
Definition at line 81 of file protocol_splitter.cpp.
The documentation for this class was generated from the following file:
src/drivers/protocol_splitter/protocol_splitter.cpp