PX4 Firmware: src/modules/mavlink/mavlink_bridge_header.h File Reference
mavlink_bridge_header.h File Reference
#include <v2.0/mavlink_types.h>
#include <unistd.h>
#include <v2.0/standard/mavlink.h>
Macros
#define MAVLINK_NO_CONVERSION_HELPERS
#define MAVLINK_USE_CONVENIENCE_FUNCTIONS
#define MAVLINK_SEND_UART_BYTES mavlink_send_uart_bytes
#define MAVLINK_START_UART_SEND mavlink_start_uart_send
#define MAVLINK_END_UART_SEND mavlink_end_uart_send
#define MAVLINK_GET_CHANNEL_BUFFER mavlink_get_channel_buffer
#define MAVLINK_GET_CHANNEL_STATUS mavlink_get_channel_status
Functions
void mavlink_send_uart_bytes (mavlink_channel_t chan, const uint8_t *ch, int length)
Send multiple chars (uint8_t) over a comm channel.
void mavlink_start_uart_send (mavlink_channel_t chan, int length)
void mavlink_end_uart_send (mavlink_channel_t chan, int length)
mavlink_status_t * mavlink_get_channel_status (uint8_t chan)
mavlink_message_t * mavlink_get_channel_buffer (uint8_t chan)
Variables
__BEGIN_DECLS mavlink_system_t mavlink_system
Macro Definition Documentation
MAVLINK_END_UART_SEND
#define MAVLINK_END_UART_SEND mavlink_end_uart_send
Definition at line 53 of file mavlink_bridge_header.h.
MAVLINK_GET_CHANNEL_BUFFER
#define MAVLINK_GET_CHANNEL_BUFFER mavlink_get_channel_buffer
Definition at line 55 of file mavlink_bridge_header.h.
MAVLINK_GET_CHANNEL_STATUS
#define MAVLINK_GET_CHANNEL_STATUS mavlink_get_channel_status
Definition at line 56 of file mavlink_bridge_header.h.
MAVLINK_NO_CONVERSION_HELPERS
#define MAVLINK_NO_CONVERSION_HELPERS
Definition at line 45 of file mavlink_bridge_header.h.
MAVLINK_SEND_UART_BYTES
#define MAVLINK_SEND_UART_BYTES mavlink_send_uart_bytes
Definition at line 50 of file mavlink_bridge_header.h.
MAVLINK_START_UART_SEND
#define MAVLINK_START_UART_SEND mavlink_start_uart_send
Definition at line 52 of file mavlink_bridge_header.h.
MAVLINK_USE_CONVENIENCE_FUNCTIONS
#define MAVLINK_USE_CONVENIENCE_FUNCTIONS
Definition at line 47 of file mavlink_bridge_header.h.
Function Documentation
mavlink_end_uart_send()
void mavlink_end_uart_send (mavlink_channel_t chan, int length)
Definition at line 116 of file mavlink_main.cpp.
References Mavlink::get_instance(), and Mavlink::send_packet().
mavlink_get_channel_buffer()
mavlink_message_t* mavlink_get_channel_buffer (uint8_t chan)
Definition at line 146 of file mavlink_main.cpp.
References Mavlink::_boot_complete, Mavlink::_first_start_time, Mavlink::get_buffer(), Mavlink::get_instance(), hrt_abstime, and usage().
mavlink_get_channel_status()
mavlink_status_t* mavlink_get_channel_status (uint8_t chan)
Definition at line 131 of file mavlink_main.cpp.
References Mavlink::get_instance(), and Mavlink::get_status().
mavlink_send_uart_bytes()
void mavlink_send_uart_bytes (mavlink_channel_t chan, const uint8_t * ch, int length)
Send multiple chars (uint8_t) over a comm channel.
Parameters
chan MAVLink channel to use, usually MAVLINK_COMM_0 = UART0
ch Character to send
Definition at line 88 of file mavlink_main.cpp.
References Mavlink::get_instance(), and Mavlink::send_bytes().
mavlink_start_uart_send()
void mavlink_start_uart_send (mavlink_channel_t chan, int length)
Definition at line 104 of file mavlink_main.cpp.
References Mavlink::begin_send(), and Mavlink::get_instance().
Variable Documentation
mavlink_system
__BEGIN_DECLS mavlink_system_t mavlink_system
Definition at line 49 of file mavlink.c.
Referenced by MavlinkReceiver::evaluate_target_ok(), Mavlink::get_component_id(), Mavlink::get_system_id(), MavlinkParametersManager::handle_message(), MavlinkReceiver::handle_message(), MavlinkReceiver::handle_message_battery_status(), MavlinkReceiver::handle_message_command_both(), MavlinkReceiver::handle_message_heartbeat(), MavlinkReceiver::handle_message_ping(), MavlinkReceiver::handle_message_play_tune(), MavlinkReceiver::handle_message_set_actuator_control_target(), MavlinkReceiver::handle_message_set_attitude_target(), MavlinkReceiver::handle_message_set_position_target_global_int(), MavlinkReceiver::handle_message_set_position_target_local_ned(), MavlinkReceiver::handle_message_statustext(), Mavlink::Mavlink(), MavlinkStreamCameraTrigger::send(), MavlinkStreamManualControl::send(), Mavlink::send_autopilot_capabilites(), MavlinkParametersManager::send_param(), and MavlinkParametersManager::send_uavcan().