PX4 Firmware: src/modules/micrortps_bridge/micrortps_client/microRTPS_client.h File Reference
microRTPS_client.h File Reference
#include "microRTPS_transport.h"
#include <cinttypes>
#include <cstdio>
#include <ctime>
#include <pthread.h>
#include <termios.h>
#include <microcdr/microcdr.h>
#include <px4_config.h>
#include <px4_getopt.h>
#include <px4_posix.h>
#include <px4_tasks.h>
#include <px4_time.h>
#include <uORB/uORB.h>
Classes
struct baudtype
struct options
Macros
#define BUFFER_SIZE 1024
#define UPDATE_TIME_MS 0
#define LOOPS -1
#define SLEEP_MS 1
#define BAUDRATE B460800
#define BAUDRATE_VAL 460800
#define B460800 460800
#define B921600 921600
#define DEVICE "/dev/ttyACM0"
#define POLL_MS 1
#define DEFAULT_RECV_PORT 2019
#define DEFAULT_SEND_PORT 2020
Functions
void * send (void *data)
void micrortps_start_topics (struct timespec &begin, int &total_read, uint32_t &received, int &loop)
Variables
struct options _options
bool _should_exit_task
Transport_node * transport_node
Macro Definition Documentation
#define B460800 460800
Definition at line 58 of file microRTPS_client.h.
#define B921600 921600
Definition at line 61 of file microRTPS_client.h.
#define BAUDRATE B460800
Definition at line 55 of file microRTPS_client.h.
#define BAUDRATE_VAL 460800
Definition at line 56 of file microRTPS_client.h.
#define BUFFER_SIZE 1024
Definition at line 51 of file microRTPS_client.h.
#define DEFAULT_RECV_PORT 2019
Definition at line 65 of file microRTPS_client.h.
#define DEFAULT_SEND_PORT 2020
Definition at line 66 of file microRTPS_client.h.
#define DEVICE "/dev/ttyACM0"
Definition at line 63 of file microRTPS_client.h.
#define LOOPS -1
Definition at line 53 of file microRTPS_client.h.
#define POLL_MS 1
Definition at line 64 of file microRTPS_client.h.
#define SLEEP_MS 1
Definition at line 54 of file microRTPS_client.h.
#define UPDATE_TIME_MS 0
Definition at line 52 of file microRTPS_client.h.
Function Documentation
void micrortps_start_topics (struct timespec & begin, int & total_read, uint32_t & received, int & loop)
Referenced by micrortps_start().
void* send (void * data)
Referenced by __EXPORT::I2C::probe(), __EXPORT::SPI::probe(), test_hott_telemetry(), and __EXPORT::I2C::transfer().
Variable Documentation
struct options _options
Definition at line 54 of file microRTPS_client_main.cpp.
Referenced by micrortps_start(), and parse_options().
bool _should_exit_task
Definition at line 52 of file microRTPS_client_main.cpp.
Referenced by micrortps_client_main().
Transport_node* transport_node
Definition at line 53 of file microRTPS_client_main.cpp.
Referenced by micrortps_client_main(), and micrortps_start().