PX4 Firmware: SF0X Class Reference
SF0X Class Reference
Public Member Functions
SF0X (const char *port=SF0X_DEFAULT_PORT, uint8_t rotation=distance_sensor_s::ROTATION_DOWNWARD_FACING)
virtual ~SF0X ()
virtual int init ()
Initialise the driver and make it ready for use.
virtual ssize_t read (device::file_t *filp, char *buffer, size_t buflen)
Perform a read from the device.
virtual int ioctl (device::file_t *filp, int cmd, unsigned long arg)
Perform an ioctl operation on the device.
void print_info ()
Diagnostics - print some basic information about the driver.
Public Member Functions inherited from device::CDev
CDev (const char *name, const char *devname)
Constructor.
virtual ~CDev ()
virtual int open (file_t *filep)
Handle an open of the device.
virtual int close (file_t *filep)
Handle a close of the device.
virtual ssize_t write (file_t *filep, const char *buffer, size_t buflen)
Perform a write to the device.
virtual off_t seek (file_t *filep, off_t offset, int whence)
Perform a logical seek operation on the device.
virtual int poll (file_t *filep, px4_pollfd_struct_t *fds, bool setup)
Perform a poll setup/teardown operation.
Public Member Functions inherited from device::Device
virtual ~Device ()=default
Destructor.
virtual int read (unsigned address, void *data, unsigned count)
Read directly from the device.
virtual int write (unsigned address, void *data, unsigned count)
Write directly to the device.
virtual int ioctl (unsigned operation, unsigned &arg)
Perform a device-specific operation.
uint8_t get_device_bus ()
Return the bus ID the device is connected to.
DeviceBusType get_device_bus_type ()
Return the bus type the device is connected to.
uint8_t get_device_address ()
Return the bus address of the device.
void set_device_address (int address)
void set_device_type (uint8_t devtype)
Set the device type.
virtual bool external ()
Protected Member Functions
virtual int probe ()
Protected Member Functions inherited from device::CDev
virtual pollevent_t poll_state (file_t *filep)
Check the current state of the device for poll events from the perspective of the file.
virtual void poll_notify (pollevent_t events)
Report new poll events.
virtual void poll_notify_one (px4_pollfd_struct_t *fds, pollevent_t events)
Internal implementation of poll_notify.
virtual int open_first (file_t *filep)
Notification of the first open.
virtual int close_last (file_t *filep)
Notification of the last close.
virtual int register_class_devname (const char *class_devname)
Register a class device name, automatically adding device class instance suffix if need be.
virtual int unregister_class_devname (const char *class_devname, unsigned class_instance)
Register a class device name, automatically adding device class instance suffix if need be.
const char * get_devname ()
Get the device name.
void lock ()
Take the driver lock.
void unlock ()
Release the driver lock.
Protected Member Functions inherited from device::Device
Device (const char *name)
Device (DeviceBusType bus_type, uint8_t bus, uint8_t address, uint8_t devtype=0)
Device (const Device &)=delete
Device & operator= (const Device &)=delete
Device (Device &&)=delete
Device & operator= (Device &&)=delete
Private Member Functions
void start ()
Initialise the automatic measurement state machine and start it.
void stop ()
Stop the automatic measurement state machine.
void set_minimum_distance (float min)
Set the min and max distance thresholds if you want the end points of the sensors range to be brought in at all, otherwise it will use the defaults SF0X_MIN_DISTANCE and SF0X_MAX_DISTANCE.
void set_maximum_distance (float max)
float get_minimum_distance ()
float get_maximum_distance ()
void cycle ()
Perform a poll cycle; collect from the previous measurement and start a new one.
int measure ()
int collect ()
Static Private Member Functions
static void cycle_trampoline (void *arg)
Static trampoline from the workq context; because we don't have a generic workq wrapper yet.
Private Attributes
char _port [20]
uint8_t _rotation
float _min_distance
float _max_distance
int _conversion_interval
work_s _work
ringbuffer::RingBuffer * _reports
int _measure_ticks
bool _collect_phase
int _fd
char _linebuf [10]
unsigned _linebuf_index
enum SF0X_PARSE_STATE _parse_state
hrt_abstime _last_read
int _class_instance
int _orb_class_instance
orb_advert_t _distance_sensor_topic
unsigned _consecutive_fail_count
perf_counter_t _sample_perf
perf_counter_t _comms_errors
Additional Inherited Members
Public Types inherited from device::Device
enum DeviceBusType { DeviceBusType_UNKNOWN = 0, DeviceBusType_I2C = 1, DeviceBusType_SPI = 2, DeviceBusType_UAVCAN = 3 }
Device bus types for DEVID.
Protected Attributes inherited from device::CDev
px4_sem_t _lock
lock to protect access to all class members (also for derived classes)
bool _pub_blocked {false}
true if publishing should be blocked
Protected Attributes inherited from device::Device
union DeviceId _device_id
device identifier information
const char * _name
driver name
bool _debug_enabled {false}
if true, debug messages are printed
Static Protected Attributes inherited from device::CDev
static const px4_file_operations_t fops = {}
Pointer to the default cdev file operations table; useful for registering clone devices etc.
Detailed Description
Definition at line 84 of file sf0x.cpp.
Constructor & Destructor Documentation
SF0X::SF0X (const char * port = SF0X_DEFAULT_PORT, uint8_t rotation = distance_sensor_s::ROTATION_DOWNWARD_FACING)
Definition at line 175 of file sf0x.cpp.
References device::Device::_debug_enabled, _fd, _port, device::CDev::open(), and warnx.
Referenced by sf0x::start().
SF0X::~SF0X () virtual
Definition at line 242 of file sf0x.cpp.
References _class_instance, _comms_errors, _reports, _sample_perf, perf_free(), RANGE_FINDER_BASE_DEVICE_PATH, stop(), and device::CDev::unregister_class_devname().
Member Function Documentation
int SF0X::collect () private
Definition at line 560 of file sf0x.cpp.
References _comms_errors, _conversion_interval, _distance_sensor_topic, _fd, _last_read, _linebuf, _linebuf_index, _parse_state, _reports, _rotation, _sample_perf, distance_sensor_s::covariance, distance_sensor_s::current_distance, DEVICE_DEBUG, get_maximum_distance(), get_minimum_distance(), hrt_absolute_time(), hrt_elapsed_time(), distance_sensor_s::id, distance_sensor_s::max_distance, distance_sensor_s::min_distance, OK, ORB_ID, orb_publish(), distance_sensor_s::orientation, perf_begin(), perf_count(), perf_end(), device::CDev::poll_notify(), read(), sf0x_parser(), distance_sensor_s::signal_quality, distance_sensor_s::timestamp, and distance_sensor_s::type.
Referenced by cycle(), and read().
void SF0X::cycle () private
Perform a poll cycle; collect from the previous measurement and start a new one.
Definition at line 664 of file sf0x.cpp.
References _collect_phase, _consecutive_fail_count, _conversion_interval, _fd, _measure_ticks, _port, collect(), cycle_trampoline(), DEVICE_LOG, hrt_absolute_time(), measure(), OK, device::CDev::open(), and start().
Referenced by cycle_trampoline().
void SF0X::cycle_trampoline (void * arg) static private
Static trampoline from the workq context; because we don't have a generic workq wrapper yet.
Parameters
arg Instance pointer for the driver that is polling.
Definition at line 656 of file sf0x.cpp.
References cycle().
Referenced by cycle(), and start().
float SF0X::get_maximum_distance () private
Definition at line 372 of file sf0x.cpp.
References _max_distance.
Referenced by collect().
float SF0X::get_minimum_distance () private
Definition at line 366 of file sf0x.cpp.
References _min_distance.
Referenced by collect().
int SF0X::init () virtual
Initialise the driver and make it ready for use.
Returns
OK if the driver initialized OK, negative errno otherwise;
Reimplemented from device::CDev.
Definition at line 261 of file sf0x.cpp.
References _class_instance, _conversion_interval, _distance_sensor_topic, _fd, _max_distance, _min_distance, _orb_class_instance, _reports, device::CDev::close(), DEVICE_LOG, lis3mdl::init(), OK, orb_advertise_multi(), ORB_ID, ORB_PRIO_HIGH, param_find(), param_get(), RANGE_FINDER_BASE_DEVICE_PATH, device::CDev::register_class_devname(), and warnx.
Referenced by sf0x::start().
int SF0X::ioctl (device::file_t * filep, int cmd, unsigned long arg) virtual
Perform an ioctl operation on the device.
The default implementation handles DIOC_GETPRIV, and otherwise returns -ENOTTY. Subclasses should call the default implementation for any command they do not handle themselves.
Parameters
filep Pointer to the NuttX file structure.
cmd The ioctl command value.
arg The ioctl argument value.
Returns
OK on success, or -errno otherwise.
Reimplemented from device::CDev.
Definition at line 378 of file sf0x.cpp.
References _conversion_interval, _measure_ticks, _reports, ATOMIC_ENTER, ATOMIC_LEAVE, OK, SENSOR_POLLRATE_DEFAULT, SENSOR_POLLRATE_EXTERNAL, SENSOR_POLLRATE_MANUAL, SENSOR_POLLRATE_MAX, SENSORIOCGPOLLRATE, SENSORIOCRESET, SENSORIOCSPOLLRATE, SENSORIOCSQUEUEDEPTH, start(), and stop().
Referenced by sf0x::reset(), sf0x::start(), and sf0x::test().
int SF0X::measure () private
Definition at line 538 of file sf0x.cpp.
References _comms_errors, _fd, DEVICE_LOG, OK, perf_count(), SF0X_TAKE_RANGE_REG, and device::CDev::write().
Referenced by cycle(), probe(), and read().
void SF0X::print_info ()
Diagnostics - print some basic information about the driver.
Definition at line 742 of file sf0x.cpp.
References _comms_errors, _measure_ticks, _reports, _sample_perf, and perf_print_counter().
Referenced by sf0x::info().
int SF0X::probe () protected virtual
Definition at line 348 of file sf0x.cpp.
References measure().
ssize_t SF0X::read (device::file_t * filep, char * buffer, size_t buflen) virtual
Perform a read from the device.
The default implementation returns -ENOSYS.
Parameters
filep Pointer to the NuttX file structure.
buffer Pointer to the buffer into which data should be placed.
buflen The number of bytes to be read.
Returns
The number of bytes read or -errno otherwise.
Reimplemented from device::CDev.
Definition at line 478 of file sf0x.cpp.
References _conversion_interval, _measure_ticks, _reports, collect(), measure(), OK, and usleep().
Referenced by collect(), and sf0x::test().
void SF0X::set_maximum_distance (float max) private
Definition at line 360 of file sf0x.cpp.
References _max_distance, and max().
void SF0X::set_minimum_distance (float min) private
Set the min and max distance thresholds if you want the end points of the sensors range to be brought in at all, otherwise it will use the defaults SF0X_MIN_DISTANCE and SF0X_MAX_DISTANCE.
Definition at line 354 of file sf0x.cpp.
References _min_distance, and min().
void SF0X::start () private
Initialise the automatic measurement state machine and start it.
Note
This function is called at open and error time. It might make sense to make it more aggressive about resetting the bus in case of errors.
Definition at line 638 of file sf0x.cpp.
References _collect_phase, _reports, and cycle_trampoline().
Referenced by cycle(), and ioctl().
void SF0X::stop () private
Stop the automatic measurement state machine.
Definition at line 650 of file sf0x.cpp.
Referenced by ioctl(), and ~SF0X().
Member Data Documentation
int SF0X::_class_instance private
Definition at line 119 of file sf0x.cpp.
Referenced by init(), and ~SF0X().
bool SF0X::_collect_phase private
Definition at line 112 of file sf0x.cpp.
Referenced by cycle(), and start().
perf_counter_t SF0X::_comms_errors private
Definition at line 127 of file sf0x.cpp.
Referenced by collect(), measure(), print_info(), and ~SF0X().
unsigned SF0X::_consecutive_fail_count private
Definition at line 124 of file sf0x.cpp.
Referenced by cycle().
int SF0X::_conversion_interval private
Definition at line 108 of file sf0x.cpp.
Referenced by collect(), cycle(), init(), ioctl(), and read().
orb_advert_t SF0X::_distance_sensor_topic private
Definition at line 122 of file sf0x.cpp.
Referenced by collect(), and init().
int SF0X::_fd private
Definition at line 113 of file sf0x.cpp.
Referenced by collect(), cycle(), init(), measure(), and SF0X().
hrt_abstime SF0X::_last_read private
Definition at line 117 of file sf0x.cpp.
Referenced by collect().
char SF0X::_linebuf[10] private
Definition at line 114 of file sf0x.cpp.
Referenced by collect().
unsigned SF0X::_linebuf_index private
Definition at line 115 of file sf0x.cpp.
Referenced by collect().
float SF0X::_max_distance private
Definition at line 107 of file sf0x.cpp.
Referenced by get_maximum_distance(), init(), and set_maximum_distance().
int SF0X::_measure_ticks private
Definition at line 111 of file sf0x.cpp.
Referenced by cycle(), ioctl(), print_info(), and read().
float SF0X::_min_distance private
Definition at line 106 of file sf0x.cpp.
Referenced by get_minimum_distance(), init(), and set_minimum_distance().
int SF0X::_orb_class_instance private
Definition at line 120 of file sf0x.cpp.
Referenced by init().
enum SF0X_PARSE_STATE SF0X::_parse_state private
Definition at line 116 of file sf0x.cpp.
Referenced by collect().
char SF0X::_port[20] private
Definition at line 104 of file sf0x.cpp.
Referenced by cycle(), and SF0X().
ringbuffer::RingBuffer* SF0X::_reports private
Definition at line 110 of file sf0x.cpp.
Referenced by collect(), init(), ioctl(), print_info(), read(), start(), and ~SF0X().
uint8_t SF0X::_rotation private
Definition at line 105 of file sf0x.cpp.
Referenced by collect().
perf_counter_t SF0X::_sample_perf private
Definition at line 126 of file sf0x.cpp.
Referenced by collect(), print_info(), and ~SF0X().
work_s SF0X::_work private
Definition at line 109 of file sf0x.cpp.
The documentation for this class was generated from the following file:
src/drivers/distance_sensor/sf0x/sf0x.cpp