PX4 Firmware: DfTROneWrapper Class Reference
DfTROneWrapper Class Reference
Public Member Functions
DfTROneWrapper (uint8_t rotation=distance_sensor_s::ROTATION_DOWNWARD_FACING)
~DfTROneWrapper ()
int start ()
Start automatic measurement.
int stop ()
Stop automatic measurement.
Private Member Functions
int _publish (struct range_sensor_data &data)
Private Attributes
uint8_t _rotation
orb_advert_t _range_topic
int _orb_class_instance
Detailed Description
Definition at line 75 of file df_trone_wrapper.cpp.
Constructor & Destructor Documentation
DfTROneWrapper()
DfTROneWrapper::DfTROneWrapper (uint8_t rotation = distance_sensor_s::ROTATION_DOWNWARD_FACING)
Definition at line 109 of file df_trone_wrapper.cpp.
Referenced by df_trone_wrapper::start().
~DfTROneWrapper()
DfTROneWrapper::~DfTROneWrapper ()
Definition at line 117 of file df_trone_wrapper.cpp.
Member Function Documentation
_publish()
int DfTROneWrapper::_publish (struct range_sensor_data & data) private
Definition at line 156 of file df_trone_wrapper.cpp.
References _orb_class_instance, _range_topic, _rotation, distance_sensor_s::current_distance, hrt_absolute_time(), distance_sensor_s::id, distance_sensor_s::max_distance, distance_sensor_s::min_distance, orb_advertise_multi(), ORB_ID, ORB_PRIO_DEFAULT, orb_publish(), distance_sensor_s::orientation, distance_sensor_s::signal_quality, distance_sensor_s::timestamp, distance_sensor_s::type, and distance_sensor_s::variance.
start()
int DfTROneWrapper::start ()
Start automatic measurement.
Returns
0 on success
Definition at line 121 of file df_trone_wrapper.cpp.
References ToneAlarmInterface::init(), and start().
Referenced by df_trone_wrapper::probe(), and df_trone_wrapper::start().
stop()
int DfTROneWrapper::stop ()
Stop automatic measurement.
Returns
0 on success
Definition at line 143 of file df_trone_wrapper.cpp.
References stop().
Referenced by df_trone_wrapper::stop().
Member Data Documentation
_orb_class_instance
int DfTROneWrapper::_orb_class_instance private
Definition at line 103 of file df_trone_wrapper.cpp.
Referenced by _publish().
_range_topic
orb_advert_t DfTROneWrapper::_range_topic private
Definition at line 101 of file df_trone_wrapper.cpp.
Referenced by _publish().
_rotation
uint8_t DfTROneWrapper::_rotation private
Definition at line 99 of file df_trone_wrapper.cpp.
Referenced by _publish().
The documentation for this class was generated from the following file:
src/drivers/driver_framework_wrapper/df_trone_wrapper/df_trone_wrapper.cpp