PX4 Firmware: px4::NodeHandle Class Reference
px4::NodeHandle Class Reference
#include <px4_nodehandle.h>
Public Member Functions
NodeHandle (AppState &a)
~NodeHandle ()
template<typename T >
Subscriber< T > * subscribe (void(*fp)(const T &), unsigned interval)
Subscribe with callback to function.
template<typename T , typename C >
Subscriber< T > * subscribe (void(C::*fp)(const T &), C *obj, unsigned interval)
Subscribe with callback to class method.
template<typename T >
Subscriber< T > * subscribe (unsigned interval)
Subscribe without callback to function.
template<typename T >
Publisher< T > * advertise ()
Advertise topic.
void spinOnce ()
Calls all callback waiting to be called.
void spin ()
Keeps calling callbacks for incoming messages, returns when module is terminated.
Protected Member Functions
template<typename T >
void update_sub_min_interval (unsigned interval, SubscriberUORB< T > *sub)
Check if this is the smallest interval so far and update _sub_min_interval.
Protected Attributes
List< SubscriberNode * > _subs
Subcriptions of node.
List< PublisherNode * > _pubs
Publications of node.
SubscriberNode * _sub_min_interval
Points to the sub with the smallest interval of all Subscriptions in _subs.
AppState & _appState
Static Protected Attributes
static const uint16_t kMaxSubscriptions = 100
static const uint16_t kMaxPublications = 100
Detailed Description
Definition at line 147 of file px4_nodehandle.h.
Constructor & Destructor Documentation
px4::NodeHandle::NodeHandle (AppState & a) inline
Definition at line 150 of file px4_nodehandle.h.
px4::NodeHandle::~NodeHandle () inline
Definition at line 157 of file px4_nodehandle.h.
References _pubs, _subs, ListNode< T >::getSibling(), kMaxPublications, kMaxSubscriptions, and PX4_WARN.
Member Function Documentation
template<typename T > Publisher<T>* px4::NodeHandle::advertise () inline
Advertise topic.
Definition at line 240 of file px4_nodehandle.h.
References _pubs.
void px4::NodeHandle::spin () inline
Keeps calling callbacks for incoming messages, returns when module is terminated.
Definition at line 270 of file px4_nodehandle.h.
References _appState, _sub_min_interval, px4::AppState::exitRequested(), px4::SubscriberNode::getUORBHandle(), px4_poll(), spinOnce(), timeout_ms, and usleep().
void px4::NodeHandle::spinOnce () inline
Calls all callback waiting to be called.
Definition at line 250 of file px4_nodehandle.h.
References _subs, ListNode< T >::getSibling(), kMaxSubscriptions, PX4_WARN, and px4::SubscriberNode::update().
Referenced by spin().
template<typename T > Subscriber<T>* px4::NodeHandle::subscribe (void(*)(const T &) fp, unsigned interval) inline
Subscribe with callback to function.
Parameters
fp Callback, executed on receiving a new message
interval Minimal interval between calls to callback
Definition at line 197 of file px4_nodehandle.h.
References _subs, and update_sub_min_interval().
template<typename T , typename C > Subscriber<T>* px4::NodeHandle::subscribe (void(C::*)(const T &) fp, C * obj, unsigned interval) inline
Subscribe with callback to class method.
Parameters
fb Callback, executed on receiving a new message
obj pointer class instance
Definition at line 212 of file px4_nodehandle.h.
References _subs, and update_sub_min_interval().
template<typename T > Subscriber<T>* px4::NodeHandle::subscribe (unsigned interval) inline
Subscribe without callback to function.
Parameters
interval Minimal interval between data fetches from orb
Definition at line 227 of file px4_nodehandle.h.
References _subs, and update_sub_min_interval().
template<typename T > void px4::NodeHandle::update_sub_min_interval (unsigned interval, SubscriberUORB< T > * sub) inline protected
Check if this is the smallest interval so far and update _sub_min_interval.
Definition at line 303 of file px4_nodehandle.h.
References px4::SubscriberNode::get_interval().
Referenced by subscribe().
Member Data Documentation
AppState& px4::NodeHandle::_appState protected
Definition at line 297 of file px4_nodehandle.h.
Referenced by spin().
List<PublisherNode *> px4::NodeHandle::_pubs protected
Publications of node.
Definition at line 293 of file px4_nodehandle.h.
Referenced by advertise(), and ~NodeHandle().
SubscriberNode* px4::NodeHandle::_sub_min_interval protected
Points to the sub with the smallest interval of all Subscriptions in _subs.
Definition at line 294 of file px4_nodehandle.h.
Referenced by spin().
List<SubscriberNode *> px4::NodeHandle::_subs protected
Subcriptions of node.
Definition at line 292 of file px4_nodehandle.h.
Referenced by spinOnce(), subscribe(), and ~NodeHandle().
const uint16_t px4::NodeHandle::kMaxPublications = 100 static protected
Definition at line 291 of file px4_nodehandle.h.
Referenced by ~NodeHandle().
const uint16_t px4::NodeHandle::kMaxSubscriptions = 100 static protected
Definition at line 290 of file px4_nodehandle.h.
Referenced by spinOnce(), and ~NodeHandle().
The documentation for this class was generated from the following file:
src/platforms/px4_nodehandle.h