PX4 Firmware: df_lsm9ds1_wrapper Namespace Reference
df_lsm9ds1_wrapper Namespace Reference
Functions
int start (bool mag_enabled, enum Rotation rotation)
int stop ()
Stop the driver.
int info ()
Print a little info about the driver.
void usage ()
Prints info about the driver argument usage.
Variables
DfLsm9ds1Wrapper * g_dev = nullptr
Function Documentation
info()
int df_lsm9ds1_wrapper::info ()
Print a little info about the driver.
Definition at line 806 of file df_lsm9ds1_wrapper.cpp.
References DfLsm9ds1Wrapper::info().
Referenced by df_lsm9ds1_wrapper_main().
start()
int df_lsm9ds1_wrapper::start (bool mag_enabled, enum Rotation rotation)
Definition at line 743 of file df_lsm9ds1_wrapper.cpp.
References DfLsm9ds1Wrapper::DfLsm9ds1Wrapper(), and DfLsm9ds1Wrapper::start().
Referenced by df_lsm9ds1_wrapper_main().
stop()
int df_lsm9ds1_wrapper::stop ()
Stop the driver.
Stop the driver.
Definition at line 783 of file df_lsm9ds1_wrapper.cpp.
References g_dev, and DfLsm9ds1Wrapper::stop().
Referenced by df_lsm9ds1_wrapper_main().
usage()
void df_lsm9ds1_wrapper::usage (void)
Prints info about the driver argument usage.
Prints info about the driver argument usage.
Definition at line 820 of file df_lsm9ds1_wrapper.cpp.
Referenced by df_lsm9ds1_wrapper_main().
Variable Documentation
g_dev
DfLsm9ds1Wrapper* df_lsm9ds1_wrapper::g_dev = nullptr
Definition at line 736 of file df_lsm9ds1_wrapper.cpp.
Referenced by stop().