PX4 Firmware: MEASAirspeed Class Reference
MEASAirspeed Class Reference
Public Member Functions
MEASAirspeed (int bus, int address=I2C_ADDRESS_MS4525DO, const char *path=PATH_MS4525)
Public Member Functions inherited from Airspeed
Airspeed (int bus, int address, unsigned conversion_interval, const char *path)
virtual ~Airspeed ()
virtual int init ()
virtual int ioctl (device::file_t *filp, int cmd, unsigned long arg)
Protected Member Functions
virtual void cycle ()
Perform a poll cycle; collect from the previous measurement and start a new one.
virtual int measure ()
virtual int collect ()
void voltage_correction (float &diff_pres_pa, float &temperature)
Correct for 5V rail voltage variations.
Protected Member Functions inherited from Airspeed
virtual int probe ()
void start ()
Initialise the automatic measurement state machine and start it.
void stop ()
Stop the automatic measurement state machine.
void new_report (const differential_pressure_s &report)
add a new report to the reports queue
Protected Attributes
math::LowPassFilter2p _filter {MEAS_RATE, MEAS_DRIVER_FILTER_FREQ}
int _t_system_power {-1}
system_power_s system_power {}
Protected Attributes inherited from Airspeed
work_s _work
bool _sensor_ok
int _measure_ticks
bool _collect_phase
float _diff_pres_offset
orb_advert_t _airspeed_pub
int _airspeed_orb_class_instance
int _class_instance
unsigned _conversion_interval
perf_counter_t _sample_perf
perf_counter_t _comms_errors
Additional Inherited Members
Static Protected Member Functions inherited from Airspeed
static void cycle_trampoline (void *arg)
Static trampoline from the workq context; because we don't have a generic workq wrapper yet.
Detailed Description
Definition at line 91 of file ms4525_airspeed.cpp.
Constructor & Destructor Documentation
MEASAirspeed::MEASAirspeed (int bus, int address = I2C_ADDRESS_MS4525DO, const char * path = PATH_MS4525)
Definition at line 122 of file ms4525_airspeed.cpp.
References DRV_DIFF_PRESS_DEVTYPE_MS4525.
Referenced by meas_airspeed::start_bus().
Member Function Documentation
int MEASAirspeed::collect () protected virtual
Implements Airspeed.
Definition at line 142 of file ms4525_airspeed.cpp.
References Airspeed::_airspeed_pub, Airspeed::_comms_errors, Airspeed::_diff_pres_offset, _filter, Airspeed::_sample_perf, math::LowPassFilter2p::apply(), differential_pressure_s::device_id, differential_pressure_s::differential_pressure_filtered_pa, differential_pressure_s::differential_pressure_raw_pa, differential_pressure_s::error_count, hrt_absolute_time(), OK, ORB_ID, orb_publish(), perf_begin(), perf_count(), perf_end(), perf_event_count(), status, differential_pressure_s::temperature, differential_pressure_s::timestamp, and voltage_correction().
Referenced by cycle().
void MEASAirspeed::cycle () protected virtual
Perform a poll cycle; collect from the previous measurement and start a new one.
Implements Airspeed.
Definition at line 241 of file ms4525_airspeed.cpp.
References Airspeed::_collect_phase, Airspeed::_measure_ticks, Airspeed::_sensor_ok, collect(), CONVERSION_INTERVAL, Airspeed::cycle_trampoline(), DEVICE_DEBUG, measure(), OK, and Airspeed::start().
int MEASAirspeed::measure () protected virtual
Implements Airspeed.
Definition at line 128 of file ms4525_airspeed.cpp.
References Airspeed::_comms_errors, OK, and perf_count().
Referenced by cycle().
void MEASAirspeed::voltage_correction (float & diff_press_pa, float & temperature) protected
Correct for 5V rail voltage variations.
correct for 5V rail voltage if the system_power ORB topic is available
See http://uav.tridgell.net/MS4525/MS4525-offset.png for a graph of offset versus voltage for 3 sensors
Definition at line 305 of file ms4525_airspeed.cpp.
References _t_system_power, f(), orb_check(), orb_copy(), ORB_ID, orb_subscribe(), system_power, and system_power_s::voltage5v_v.
Referenced by collect().
Member Data Documentation
math::LowPassFilter2p MEASAirspeed::_filter {MEAS_RATE, MEAS_DRIVER_FILTER_FREQ} protected
Definition at line 106 of file ms4525_airspeed.cpp.
Referenced by collect().
int MEASAirspeed::_t_system_power {-1} protected
Definition at line 113 of file ms4525_airspeed.cpp.
Referenced by voltage_correction().
system_power_s MEASAirspeed::system_power {} protected
Definition at line 114 of file ms4525_airspeed.cpp.
Referenced by voltage_correction().
The documentation for this class was generated from the following file:
src/drivers/differential_pressure/ms4525/ms4525_airspeed.cpp