PX4 Firmware: syslink Namespace Reference
syslink Namespace Reference
Functions
void usage ()
Prints info about the driver argument usage.
void start ()
Attempt to start driver on all available I2C busses.
void status ()
void test ()
void attached (int pid)
Function Documentation
void syslink::attached (int pid)
Definition at line 827 of file syslink_main.cpp.
References DECK_DEVICE_PATH, DECKIOGNUM, DECKIOSNUM, and read().
Referenced by mtd_main(), and syslink_main().
void syslink::start ()
Attempt to start driver on all available I2C busses.
This function will return as soon as the first sensor is detected on one of the available busses or if no sensors are detected.
Attempt to start driver on all available I2C busses.
Definition at line 748 of file syslink_main.cpp.
References Syslink::start(), Syslink::Syslink(), usleep(), and warnx.
Referenced by syslink_main().
void syslink::status ()
Definition at line 767 of file syslink_main.cpp.
References DECK_DEVICE_PATH, DECKIOGNUM, DECKIOID, DECKIOSNUM, Syslink::is_good(), Syslink::nullrate, Syslink::pktrate, read(), Syslink::rxrate, and Syslink::txrate.
Referenced by syslink_main().
void syslink::test ()
Definition at line 852 of file syslink_main.cpp.
Referenced by syslink_main().
void syslink::usage (void)
Prints info about the driver argument usage.
Prints info about the driver argument usage.
Definition at line 743 of file syslink_main.cpp.
References warnx.
Referenced by syslink_main().