PX4 Firmware: src/platforms/posix/drivers/bebop_flow/bebop_flow.cpp File Reference
bebop_flow.cpp File Reference
This is a wrapper around the Parrot Bebop's downward-facing camera and integrates an optical flow computation.
#include <stdint.h>
#include <px4_tasks.h>
#include <px4_getopt.h>
#include <px4_posix.h>
#include "video_device.h"
#include "dump_pgm.h"
#include <mt9v117/MT9V117.hpp>
Namespaces
bebop_flow
Functions
__EXPORT int bebop_flow_main (int argc, char *argv[])
int bebop_flow::start ()
Attempt to start driver on all available I2C busses.
int bebop_flow::stop ()
Stop the driver.
int bebop_flow::info ()
Print a little info about the driver.
int bebop_flow::trigger (int count)
int bebop_flow::clear_errors ()
Clear errors present on the Bebop hardware.
void bebop_flow::usage ()
Prints info about the driver argument usage.
void bebop_flow::task_main (int argc, char *argv[])
Variables
MT9V117 * bebop_flow::image_sensor = nullptr
VideoDevice * bebop_flow::g_dev = nullptr
volatile bool bebop_flow::_task_should_exit = false
static bool bebop_flow::_is_running = false
static px4_task_t bebop_flow::_task_handle = -1
volatile unsigned int bebop_flow::_trigger = 0
const char * bebop_flow::dev_name = "/dev/video0"
Detailed Description
This is a wrapper around the Parrot Bebop's downward-facing camera and integrates an optical flow computation.
Definition in file bebop_flow.cpp.
Function Documentation
int bebop_flow_main (int argc, char * argv[])
Definition at line 272 of file bebop_flow.cpp.
References bebop_flow::info(), px4_getopt(), bebop_flow::start(), bebop_flow::stop(), bebop_flow::trigger(), and bebop_flow::usage().