PX4 Firmware: IST8310 Class Reference
IST8310 Class Reference
Classes
struct _scale
Public Member Functions
IST8310 (int bus_number, int address, const char *path, enum Rotation rotation)
virtual ~IST8310 ()
virtual int init ()
virtual ssize_t read (struct file *filp, char *buffer, size_t buflen)
virtual int ioctl (struct file *filp, int cmd, unsigned long arg)
void print_info ()
Diagnostics - print some basic information about the driver.
Protected Member Functions
virtual int probe ()
Private Member Functions
void start ()
Initialise the automatic measurement state machine and start it.
void stop ()
Stop the automatic measurement state machine.
int reset ()
Reset the device.
int calibrate (struct file *filp, unsigned enable)
Perform the on-sensor scale calibration routine.
void check_conf (void)
check the sensor configuration.
void cycle ()
Perform a poll cycle; collect from the previous measurement and start a new one.
int write_reg (uint8_t reg, uint8_t val)
Write a register.
int write (unsigned address, void *data, unsigned count)
Write to a register block.
int read_reg (uint8_t reg, uint8_t &val)
Read a register.
int read (unsigned address, void *data, unsigned count)
read register block.
int measure ()
Issue a measurement command.
int collect ()
Collect the result of the most recent measurement.
float meas_to_float (uint8_t in[2])
Convert a big-endian signed 16-bit value to a float.
int check_scale ()
Check the current scale calibration.
int check_offset ()
Check the current offset calibration.
int set_selftest (unsigned enable)
Place the device in self test mode.
IST8310 (const IST8310 &)
IST8310 operator= (const IST8310 &)
Static Private Member Functions
static void cycle_trampoline (void *arg)
Static trampoline from the workq context; because we don't have a generic workq wrapper yet.
Private Attributes
work_s _work {}
unsigned _measure_ticks {0}
ringbuffer::RingBuffer * _reports {nullptr}
float _range_scale {0.003f}
bool _collect_phase {false}
int _class_instance {-1}
int _orb_class_instance {-1}
orb_advert_t _mag_topic {nullptr}
perf_counter_t _sample_perf
perf_counter_t _comms_errors
perf_counter_t _range_errors
perf_counter_t _conf_errors
bool _sensor_ok {false}
sensor was found and reports ok
bool _calibrated {false}
the calibration is valid
bool _ctl_reg_mismatch {false}
control register value mismatch after checking
enum Rotation _rotation
sensor_mag_s _last_report {}
used for info()
uint8_t _ctl3_reg {0}
uint8_t _ctl4_reg {0}
Detailed Description
Definition at line 190 of file ist8310.cpp.
Constructor & Destructor Documentation
IST8310::IST8310 (int bus_number, int address, const char * path, enum Rotation rotation)
Definition at line 392 of file ist8310.cpp.
References DRV_MAG_DEVTYPE_IST8310.
IST8310::~IST8310 () virtual
Definition at line 411 of file ist8310.cpp.
References _class_instance, _comms_errors, _conf_errors, _range_errors, _reports, _sample_perf, MAG_BASE_DEVICE_PATH, perf_free(), and stop().
IST8310::IST8310 (const IST8310 &) private
Member Function Documentation
int IST8310::calibrate (struct file * filp, unsigned enable) private
Perform the on-sensor scale calibration routine.
Note
The sensor will continue to provide measurements, these will however reflect the uncalibrated sensor state until the calibration routine has been completed.
Parameters
enable set to 1 to enable self-test strap, 0 to disable
Definition at line 980 of file ist8310.cpp.
References check_scale(), fd, ioctl(), mag_report, MAGIOCEXSTRAP, MAGIOCGSCALE, MAGIOCSSCALE, OK, PX4_ERR, PX4_ERROR, PX4_WARN, read(), SENSORIOCSPOLLRATE, mag_calibration_s::x_offset, mag_calibration_s::x_scale, mag_calibration_s::y_offset, mag_calibration_s::y_scale, mag_calibration_s::z_offset, and mag_calibration_s::z_scale.
Referenced by ioctl(), and ist8310_main().
void IST8310::check_conf (void) private
check the sensor configuration.
check that the configuration register has the right value.
checks that the config of the sensor is correctly set, to cope with communication errors causing the configuration to change
This is done periodically to cope with I2C bus noise causing the configuration of the compass to change.
Definition at line 490 of file ist8310.cpp.
References _comms_errors, _conf_errors, _ctl3_reg, _ctl4_reg, _ctl_reg_mismatch, ADDR_CTRL3, ADDR_CTRL4, OK, perf_count(), read_reg(), and write_reg().
Referenced by collect().
int IST8310::check_offset () private
Check the current offset calibration.
Returns
0 if offset calibration is ok, 1 else
Definition at line 1114 of file ist8310.cpp.
References f().
int IST8310::check_scale () private
Check the current scale calibration.
Returns
0 if scale calibration is ok, 1 else
Definition at line 1109 of file ist8310.cpp.
References OK.
Referenced by calibrate().
int IST8310::collect () private
Collect the result of the most recent measurement.
Definition at line 847 of file ist8310.cpp.
References _comms_errors, _last_report, _mag_topic, _orb_class_instance, _range_errors, _range_scale, _reports, _rotation, _sample_perf, ADDR_DATA_OUT_X_LSB, check_conf(), DEVICE_DEBUG, hrt_absolute_time(), IST8310_MAX_VAL_XY, IST8310_MAX_VAL_Z, IST8310_MIN_VAL_XY, IST8310_MIN_VAL_Z, mag_report, OK, orb_advertise_multi(), ORB_ID, ORB_PRIO_HIGH, ORB_PRIO_MAX, orb_publish(), perf_begin(), perf_count(), perf_end(), perf_event_count(), read(), and rotate_3f().
Referenced by cycle(), and read().
void IST8310::cycle () private
Perform a poll cycle; collect from the previous measurement and start a new one.
This is the heart of the measurement state machine. This function alternately starts a measurement, or collects the data from the previous measurement.
When the interval between measurements is greater than the minimum measurement interval, a gap is inserted between collection and measurement to provide the most recent measurement possible at the next interval.
Definition at line 781 of file ist8310.cpp.
References _collect_phase, _measure_ticks, collect(), cycle_trampoline(), DEVICE_DEBUG, IST8310_CONVERSION_INTERVAL, measure(), OK, and start().
Referenced by cycle_trampoline().
void IST8310::cycle_trampoline (void * arg) static private
Static trampoline from the workq context; because we don't have a generic workq wrapper yet.
Parameters
arg Instance pointer for the driver that is polling.
Definition at line 751 of file ist8310.cpp.
References cycle().
Referenced by cycle(), and start().
int IST8310::init () virtual
Definition at line 432 of file ist8310.cpp.
References _class_instance, _reports, _sensor_ok, DEVICE_DEBUG, lis3mdl::init(), MAG_BASE_DEVICE_PATH, mag_report, OK, PX4_ERROR, and reset().
int IST8310::ioctl (struct file * filp, int cmd, unsigned long arg) virtual
Definition at line 593 of file ist8310.cpp.
References _measure_ticks, _reports, calibrate(), IST8310_CONVERSION_INTERVAL, MAGIOCCALIBRATE, MAGIOCEXSTRAP, MAGIOCGEXTERNAL, MAGIOCGSAMPLERATE, MAGIOCGSCALE, MAGIOCSSAMPLERATE, MAGIOCSSCALE, OK, reset(), SENSOR_POLLRATE_DEFAULT, SENSOR_POLLRATE_EXTERNAL, SENSOR_POLLRATE_MANUAL, SENSOR_POLLRATE_MAX, SENSORIOCGPOLLRATE, SENSORIOCRESET, SENSORIOCSPOLLRATE, SENSORIOCSQUEUEDEPTH, set_selftest(), start(), and stop().
Referenced by calibrate(), ist8310::calibrate(), ist8310::reset(), ist8310::start_bus(), and ist8310::test().
float IST8310::meas_to_float (uint8_t in[2]) private
Convert a big-endian signed 16-bit value to a float.
Parameters
in A signed 16-bit big-endian value.
Returns
The floating-point representation of the value.
Definition at line 1180 of file ist8310.cpp.
int IST8310::measure () private
Issue a measurement command.
Returns
OK if the measurement command was successful.
Definition at line 830 of file ist8310.cpp.
References _comms_errors, ADDR_CTRL1, CTRL1_MODE_SINGLE, OK, perf_count(), and write_reg().
Referenced by cycle(), and read().
IST8310 IST8310::operator= (const IST8310 &) private
void IST8310::print_info ()
Diagnostics - print some basic information about the driver.
Definition at line 1194 of file ist8310.cpp.
References _comms_errors, _last_report, _measure_ticks, _reports, _sample_perf, and perf_print_counter().
Referenced by ist8310::info().
int IST8310::probe () protected virtual
Definition at line 759 of file ist8310.cpp.
References ADDR_WAI, data, DEVICE_DEBUG, OK, read(), and WAI_EXPECTED_VALUE.
ssize_t IST8310::read (struct file * filp, char * buffer, size_t buflen) virtual
Definition at line 535 of file ist8310.cpp.
References _measure_ticks, _reports, collect(), IST8310_CONVERSION_INTERVAL, mag_report, measure(), OK, and usleep().
Referenced by calibrate(), collect(), probe(), read_reg(), and ist8310::test().
int IST8310::read (unsigned address, void * data, unsigned count) private
read register block.
Parameters
address The register address to read from.
data The buffer to read into.
count The number of bytes to read.
Returns
OK on write success.
Definition at line 478 of file ist8310.cpp.
int IST8310::read_reg (uint8_t reg, uint8_t & val) private
Read a register.
Parameters
reg The register to read.
val The value read.
Returns
OK on read success.
Definition at line 1171 of file ist8310.cpp.
References read().
Referenced by check_conf(), and set_selftest().
int IST8310::reset () private
Reset the device.
Definition at line 734 of file ist8310.cpp.
References _ctl3_reg, _ctl4_reg, ADDR_CTRL2, ADDR_CTRL3, ADDR_CTRL4, CTRL2_SRST, CTRL3_SAMPLEAVG_16, CTRL4_SRPD, OK, and write_reg().
Referenced by init(), and ioctl().
int IST8310::set_selftest (unsigned enable) private
Place the device in self test mode.
Returns
0 if mode is set, 1 else
Definition at line 1133 of file ist8310.cpp.
References _comms_errors, ADDR_STR, OK, perf_count(), read_reg(), STR_SELF_TEST_ON, and write_reg().
Referenced by ioctl().
void IST8310::start () private
Initialise the automatic measurement state machine and start it.
Note
This function is called at open and error time. It might make sense to make it more aggressive about resetting the bus in case of errors.
Definition at line 717 of file ist8310.cpp.
References _collect_phase, _reports, and cycle_trampoline().
Referenced by cycle(), and ioctl().
void IST8310::stop () private
Stop the automatic measurement state machine.
Definition at line 728 of file ist8310.cpp.
Referenced by ioctl(), and ~IST8310().
int IST8310::write (unsigned address, void * data, unsigned count) private
Write to a register block.
Parameters
address The register address to write to.
data The buffer to write from.
count The number of bytes to write.
Returns
OK on write success.
Definition at line 463 of file ist8310.cpp.
Referenced by write_reg().
int IST8310::write_reg (uint8_t reg, uint8_t val) private
Write a register.
Parameters
reg The register to write.
val The value to write.
Returns
OK on write success.
Definition at line 1164 of file ist8310.cpp.
References write().
Referenced by check_conf(), measure(), reset(), and set_selftest().
Member Data Documentation
bool IST8310::_calibrated {false} private
the calibration is valid
Definition at line 231 of file ist8310.cpp.
int IST8310::_class_instance {-1} private
Definition at line 219 of file ist8310.cpp.
Referenced by init(), and ~IST8310().
bool IST8310::_collect_phase {false} private
Definition at line 218 of file ist8310.cpp.
Referenced by cycle(), and start().
perf_counter_t IST8310::_comms_errors private
Definition at line 225 of file ist8310.cpp.
Referenced by check_conf(), collect(), measure(), print_info(), set_selftest(), and ~IST8310().
perf_counter_t IST8310::_conf_errors private
Definition at line 227 of file ist8310.cpp.
Referenced by check_conf(), and ~IST8310().
uint8_t IST8310::_ctl3_reg {0} private
Definition at line 238 of file ist8310.cpp.
Referenced by check_conf(), and reset().
uint8_t IST8310::_ctl4_reg {0} private
Definition at line 239 of file ist8310.cpp.
Referenced by check_conf(), and reset().
bool IST8310::_ctl_reg_mismatch {false} private
control register value mismatch after checking
Definition at line 232 of file ist8310.cpp.
Referenced by check_conf().
sensor_mag_s IST8310::_last_report {} private
used for info()
Definition at line 236 of file ist8310.cpp.
Referenced by collect(), and print_info().
orb_advert_t IST8310::_mag_topic {nullptr} private
Definition at line 222 of file ist8310.cpp.
Referenced by collect().
unsigned IST8310::_measure_ticks {0} private
Definition at line 211 of file ist8310.cpp.
Referenced by cycle(), ioctl(), print_info(), and read().
int IST8310::_orb_class_instance {-1} private
Definition at line 220 of file ist8310.cpp.
Referenced by collect().
perf_counter_t IST8310::_range_errors private
Definition at line 226 of file ist8310.cpp.
Referenced by collect(), and ~IST8310().
float IST8310::_range_scale {0.003f} private
Definition at line 216 of file ist8310.cpp.
Referenced by collect().
ringbuffer::RingBuffer* IST8310::_reports {nullptr} private
Definition at line 213 of file ist8310.cpp.
Referenced by collect(), init(), ioctl(), print_info(), read(), start(), and ~IST8310().
enum Rotation IST8310::_rotation private
Definition at line 234 of file ist8310.cpp.
Referenced by collect().
perf_counter_t IST8310::_sample_perf private
Definition at line 224 of file ist8310.cpp.
Referenced by collect(), print_info(), and ~IST8310().
bool IST8310::_sensor_ok {false} private
sensor was found and reports ok
Definition at line 230 of file ist8310.cpp.
Referenced by init().
work_s IST8310::_work {} private
Definition at line 210 of file ist8310.cpp.
The documentation for this class was generated from the following file:
src/drivers/magnetometer/ist8310/ist8310.cpp