PX4 Firmware: IBMP388 Class Reference
IBMP388 Class Reference abstract
#include <bmp388.h>
Public Member Functions
virtual ~IBMP388 ()=default
virtual int init ()=0
virtual uint8_t get_reg (uint8_t addr)=0
virtual int get_reg_buf (uint8_t addr, uint8_t *buf, uint8_t len)=0
virtual int set_reg (uint8_t value, uint8_t addr)=0
virtual data_s * get_data (uint8_t addr)=0
virtual calibration_s * get_calibration (uint8_t addr)=0
virtual uint32_t get_device_id () const =0
Detailed Description
Definition at line 284 of file bmp388.h.
Constructor & Destructor Documentation
~IBMP388()
virtual IBMP388::~IBMP388 () virtual default
Member Function Documentation
get_calibration()
virtual calibration_s* IBMP388::get_calibration (uint8_t addr) pure virtual
Referenced by BMP388::init().
get_data()
virtual data_s* IBMP388::get_data (uint8_t addr) pure virtual
get_device_id()
virtual uint32_t IBMP388::get_device_id () const pure virtual
get_reg()
virtual uint8_t IBMP388::get_reg (uint8_t addr) pure virtual
Referenced by BMP388::init(), BMP388::set_op_mode(), BMP388::soft_reset(), and BMP388::validate_trimming_param().
get_reg_buf()
virtual int IBMP388::get_reg_buf (uint8_t addr, uint8_t * buf, uint8_t len) pure virtual
Referenced by BMP388::get_sensor_data().
init()
virtual int IBMP388::init () pure virtual
set_reg()
virtual int IBMP388::set_reg (uint8_t value, uint8_t addr) pure virtual
Referenced by BMP388::set_op_mode(), BMP388::set_sensor_settings(), and BMP388::soft_reset().
The documentation for this class was generated from the following file:
src/drivers/barometer/bmp388/bmp388.h