PX4 Firmware: src/systemcmds/mtd/mtd.c File Reference
mtd.c File Reference
mtd service and utility app.
#include <px4_platform_common/px4_config.h>
#include <px4_platform_common/log.h>
#include <px4_platform_common/module.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <stdbool.h>
#include <unistd.h>
#include <fcntl.h>
#include <sys/mount.h>
#include <sys/ioctl.h>
#include <sys/stat.h>
#include <nuttx/spi/spi.h>
#include <nuttx/mtd/mtd.h>
#include <nuttx/fs/nxffs.h>
#include <nuttx/fs/ioctl.h>
#include <nuttx/drivers/drivers.h>
#include <arch/board/board.h>
#include "systemlib/px4_macros.h"
#include <parameters/param.h>
#include <board_config.h>
Functions
__EXPORT int mtd_main (int argc, char *argv[])
Detailed Description
mtd service and utility app.
Author
Lorenz Meier lm@in.nosp@m.f.et.nosp@m.hz.ch
Definition in file mtd.c.
Function Documentation
mtd_main()
int mtd_main (int argc, char * argv[])
Definition at line 74 of file mtd.c.
References arraySize, at24c_initialize(), fd, nblocks, OK, print_usage(), read(), SPIDEV_MODE3, and write().