PX4 Firmware: src/modules/position_estimator_inav/position_estimator_inav_params.h File Reference
position_estimator_inav_params.h File Reference
#include <parameters/param.h>
Classes
struct position_estimator_inav_params
struct position_estimator_inav_param_handles
Macros
#define CBRK_NO_VISION_KEY 328754
Functions
int inav_parameters_init (struct position_estimator_inav_param_handles *h)
Initialize all parameter handles and values.
int inav_parameters_update (const struct position_estimator_inav_param_handles *h, struct position_estimator_inav_params *p)
Update all parameters.
Macro Definition Documentation
#define CBRK_NO_VISION_KEY 328754
Definition at line 108 of file position_estimator_inav_params.h.
Referenced by position_estimator_inav_thread_main().
Function Documentation
int inav_parameters_init (struct position_estimator_inav_param_handles * h)
Initialize all parameter handles and values.
Definition at line 1440 of file position_estimator_inav_main.cpp.
References position_estimator_inav_param_handles::att_ext_hdg_m, position_estimator_inav_param_handles::delay_gps, position_estimator_inav_param_handles::disable_mocap, position_estimator_inav_param_handles::enable_lidar_alt_est, position_estimator_inav_param_handles::flow_k, position_estimator_inav_param_handles::flow_module_offset_x, position_estimator_inav_param_handles::flow_module_offset_y, position_estimator_inav_param_handles::flow_q_min, position_estimator_inav_param_handles::land_disp, position_estimator_inav_param_handles::land_t, position_estimator_inav_param_handles::land_thr, position_estimator_inav_param_handles::lidar_calibration_offset, position_estimator_inav_param_handles::lidar_err, position_estimator_inav_param_handles::no_vision, param_find(), position_estimator_inav_param_handles::w_acc_bias, position_estimator_inav_param_handles::w_gps_flow, position_estimator_inav_param_handles::w_mocap_p, position_estimator_inav_param_handles::w_xy_flow, position_estimator_inav_param_handles::w_xy_gps_p, position_estimator_inav_param_handles::w_xy_gps_v, position_estimator_inav_param_handles::w_xy_res_v, position_estimator_inav_param_handles::w_xy_vision_p, position_estimator_inav_param_handles::w_xy_vision_v, position_estimator_inav_param_handles::w_z_baro, position_estimator_inav_param_handles::w_z_gps_p, position_estimator_inav_param_handles::w_z_gps_v, position_estimator_inav_param_handles::w_z_lidar, and position_estimator_inav_param_handles::w_z_vision_p.
Referenced by position_estimator_inav_thread_main().
int inav_parameters_update (const struct position_estimator_inav_param_handles * h, struct position_estimator_inav_params * p)
Update all parameters.
Definition at line 1474 of file position_estimator_inav_main.cpp.
References position_estimator_inav_params::att_ext_hdg_m, position_estimator_inav_param_handles::att_ext_hdg_m, position_estimator_inav_params::delay_gps, position_estimator_inav_param_handles::delay_gps, position_estimator_inav_params::disable_mocap, position_estimator_inav_param_handles::disable_mocap, position_estimator_inav_params::enable_lidar_alt_est, position_estimator_inav_param_handles::enable_lidar_alt_est, position_estimator_inav_params::flow_k, position_estimator_inav_param_handles::flow_k, position_estimator_inav_params::flow_module_offset_x, position_estimator_inav_param_handles::flow_module_offset_x, position_estimator_inav_params::flow_module_offset_y, position_estimator_inav_param_handles::flow_module_offset_y, position_estimator_inav_params::flow_q_min, position_estimator_inav_param_handles::flow_q_min, position_estimator_inav_params::land_disp, position_estimator_inav_param_handles::land_disp, position_estimator_inav_params::land_t, position_estimator_inav_param_handles::land_t, position_estimator_inav_params::land_thr, position_estimator_inav_param_handles::land_thr, position_estimator_inav_params::lidar_calibration_offset, position_estimator_inav_param_handles::lidar_calibration_offset, position_estimator_inav_params::lidar_err, position_estimator_inav_param_handles::lidar_err, position_estimator_inav_params::no_vision, position_estimator_inav_param_handles::no_vision, param_get(), position_estimator_inav_params::w_acc_bias, position_estimator_inav_param_handles::w_acc_bias, position_estimator_inav_params::w_gps_flow, position_estimator_inav_param_handles::w_gps_flow, position_estimator_inav_params::w_mocap_p, position_estimator_inav_param_handles::w_mocap_p, position_estimator_inav_params::w_xy_flow, position_estimator_inav_param_handles::w_xy_flow, position_estimator_inav_params::w_xy_gps_p, position_estimator_inav_param_handles::w_xy_gps_p, position_estimator_inav_params::w_xy_gps_v, position_estimator_inav_param_handles::w_xy_gps_v, position_estimator_inav_params::w_xy_res_v, position_estimator_inav_param_handles::w_xy_res_v, position_estimator_inav_params::w_xy_vision_p, position_estimator_inav_param_handles::w_xy_vision_p, position_estimator_inav_params::w_xy_vision_v, position_estimator_inav_param_handles::w_xy_vision_v, position_estimator_inav_params::w_z_baro, position_estimator_inav_param_handles::w_z_baro, position_estimator_inav_params::w_z_gps_p, position_estimator_inav_param_handles::w_z_gps_p, position_estimator_inav_params::w_z_gps_v, position_estimator_inav_param_handles::w_z_gps_v, position_estimator_inav_params::w_z_lidar, position_estimator_inav_param_handles::w_z_lidar, position_estimator_inav_params::w_z_vision_p, and position_estimator_inav_param_handles::w_z_vision_p.
Referenced by position_estimator_inav_thread_main().