PX4 Firmware: CDevNode Class Reference
CDevNode Class Reference
Public Member Functions
CDevNode ()
~CDevNode () override=default
int open (cdev::file_t *handlep) override
Handle an open of the device.
int close (cdev::file_t *handlep) override
Handle a close of the device.
ssize_t write (cdev::file_t *handlep, const char *buffer, size_t buflen) override
Perform a write to the device.
ssize_t read (cdev::file_t *handlep, char *buffer, size_t buflen) override
Perform a read from the device.
Public Member Functions inherited from cdev::CDev
CDev (const char *devname)
Constructor.
CDev (const CDev &)=delete
CDev & operator= (const CDev &)=delete
CDev (CDev &&)=delete
CDev & operator= (CDev &&)=delete
virtual ~CDev ()
virtual int init ()
virtual off_t seek (file_t *filep, off_t offset, int whence)
Perform a logical seek operation on the device.
virtual int ioctl (file_t *filep, int cmd, unsigned long arg)
Perform an ioctl operation on the device.
virtual int poll (file_t *filep, px4_pollfd_struct_t *fds, bool setup)
Perform a poll setup/teardown operation.
const char * get_devname () const
Get the device name.
Private Attributes
bool _is_open_for_write
size_t _write_offset
char _buf [1000]
Additional Inherited Members
Protected Member Functions inherited from cdev::CDev
virtual pollevent_t poll_state (file_t *filep)
Check the current state of the device for poll events from the perspective of the file.
virtual void poll_notify (pollevent_t events)
Report new poll events.
virtual void poll_notify_one (px4_pollfd_struct_t *fds, pollevent_t events)
Internal implementation of poll_notify.
virtual int open_first (file_t *filep)
Notification of the first open.
virtual int close_last (file_t *filep)
Notification of the last close.
virtual int register_class_devname (const char *class_devname)
Register a class device name, automatically adding device class instance suffix if need be.
virtual int unregister_class_devname (const char *class_devname, unsigned class_instance)
Register a class device name, automatically adding device class instance suffix if need be.
void lock ()
Take the driver lock.
void unlock ()
Release the driver lock.
int unregister_driver_and_memory ()
First, unregisters the driver.
Protected Attributes inherited from cdev::CDev
px4_sem_t _lock
lock to protect access to all class members (also for derived classes)
Static Protected Attributes inherited from cdev::CDev
static const px4_file_operations_t fops = {}
Pointer to the default cdev file operations table; useful for registering clone devices etc.
Detailed Description
Definition at line 101 of file cdevtest_example.cpp.
Constructor & Destructor Documentation
CDevNode()
CDevNode::CDevNode () inline
Definition at line 104 of file cdevtest_example.cpp.
References read(), and write().
~CDevNode()
CDevNode::~CDevNode () override default
Member Function Documentation
close()
int CDevNode::close (cdev::file_t * filep) override virtual
Handle a close of the device.
This function is called for every close of the device. The default implementation maintains _open_count and returns OK as long as it is not zero.
Parameters
filep Pointer to the NuttX file structure.
Returns
OK if the close was successful, -errno otherwise.
Reimplemented from cdev::CDev.
Definition at line 144 of file cdevtest_example.cpp.
References cdev::file_t::f_oflags, and cdev::file_t::f_priv.
open()
int CDevNode::open (cdev::file_t * filep) override virtual
Handle an open of the device.
This function is called for every open of the device. The default implementation maintains _open_count and always returns OK.
Parameters
filep Pointer to the NuttX file structure.
Returns
OK if the open is allowed, -errno otherwise.
Reimplemented from cdev::CDev.
Definition at line 121 of file cdevtest_example.cpp.
References cdev::file_t::f_oflags, cdev::file_t::f_priv, and PrivData::PrivData().
read()
ssize_t CDevNode::read (cdev::file_t * filep, char * buffer, size_t buflen) override virtual
Perform a read from the device.
The default implementation returns -ENOSYS.
Parameters
filep Pointer to the NuttX file structure.
buffer Pointer to the buffer into which data should be placed.
buflen The number of bytes to be read.
Returns
The number of bytes read or -errno otherwise.
Reimplemented from cdev::CDev.
Definition at line 171 of file cdevtest_example.cpp.
References _buf, PrivData::_read_offset, and cdev::file_t::f_priv.
write()
ssize_t CDevNode::write (cdev::file_t * filep, const char * buffer, size_t buflen) override virtual
Perform a write to the device.
The default implementation returns -ENOSYS.
Parameters
filep Pointer to the NuttX file structure.
buffer Pointer to the buffer from which data should be read.
buflen The number of bytes to be written.
Returns
The number of bytes written or -errno otherwise.
Reimplemented from cdev::CDev.
Definition at line 158 of file cdevtest_example.cpp.
References _buf.
Member Data Documentation
_buf
char CDevNode::_buf[1000] private
Definition at line 118 of file cdevtest_example.cpp.
_is_open_for_write
bool CDevNode::_is_open_for_write private
Definition at line 116 of file cdevtest_example.cpp.
_write_offset
size_t CDevNode::_write_offset private
Definition at line 117 of file cdevtest_example.cpp.
The documentation for this class was generated from the following file:
src/lib/cdev/test/cdevtest_example.cpp