PX4 Firmware: src/systemcmds/ver/ver.c File Reference
ver.c File Reference
Version command, unifies way of showing versions of HW, SW, Build, GCC In case you want to add new version just extend version_main function.
#include <px4_config.h>
#include <px4_module.h>
#include <stdio.h>
#include <stdbool.h>
#include <string.h>
#include <version/version.h>
Macros
#define CPU_UUID_FORMAT "%X"
#define CPU_UUID_SEPARATOR ":"
Functions
static void usage (const char *reason)
__EXPORT int ver_main (int argc, char *argv[])
Variables
static const char sz_ver_hw_str [] = "hw"
static const char sz_ver_hwcmp_str [] = "hwcmp"
static const char sz_ver_hwtypecmp_str [] = "hwtypecmp"
static const char sz_ver_git_str [] = "git"
static const char sz_ver_bdate_str [] = "bdate"
static const char sz_ver_buri_str [] = "uri"
static const char sz_ver_gcc_str [] = "gcc"
static const char sz_ver_all_str [] = "all"
static const char mcu_ver_str [] = "mcu"
static const char mcu_uid_str [] = "uid"
static const char mfg_uid_str [] = "mfguid"
Detailed Description
Version command, unifies way of showing versions of HW, SW, Build, GCC In case you want to add new version just extend version_main function.
Author
Vladimir Kulla ufon@.nosp@m.kull.nosp@m.aonli.nosp@m.ne.n.nosp@m.et
Definition in file ver.c.
Macro Definition Documentation
#define CPU_UUID_FORMAT "%X"
Definition at line 67 of file ver.c.
Referenced by ver_main().
#define CPU_UUID_SEPARATOR ":"
Definition at line 73 of file ver.c.
Referenced by ver_main().
Function Documentation
static void usage (const char * reason) static
Definition at line 76 of file ver.c.
References PRINT_MODULE_DESCRIPTION(), PRINT_MODULE_USAGE_ARG(), PRINT_MODULE_USAGE_COMMAND_DESCR(), PRINT_MODULE_USAGE_NAME(), and ver_main().
Referenced by ver_main().
int ver_main (int argc, char * argv[])
Definition at line 106 of file ver.c.
References board_get_mfguid_formated(), board_get_uuid32_formated(), board_mcu_version(), BOARD_OVERRIDE_MFGUID, BOARD_OVERRIDE_UUID, CPU_UUID_FORMAT, CPU_UUID_SEPARATOR, mcu_uid_str, mcu_ver_str, mfg_uid_str, px4_board_hw_revision(), px4_board_hw_version(), px4_board_name(), px4_board_sub_type(), px4_build_uri(), PX4_ERR, px4_firmware_version(), px4_firmware_version_string(), px4_os_name(), px4_os_version(), px4_os_version_string(), px4_toolchain_name(), px4_toolchain_version(), sz_ver_all_str, sz_ver_bdate_str, sz_ver_buri_str, sz_ver_gcc_str, sz_ver_git_str, sz_ver_hw_str, sz_ver_hwcmp_str, sz_ver_hwtypecmp_str, and usage().
Referenced by usage().
Variable Documentation
const char mcu_uid_str[] = "uid" static
Definition at line 60 of file ver.c.
Referenced by ver_main().
const char mcu_ver_str[] = "mcu" static
Definition at line 59 of file ver.c.
Referenced by ver_main().
const char mfg_uid_str[] = "mfguid" static
Definition at line 61 of file ver.c.
Referenced by ver_main().
const char sz_ver_all_str[] = "all" static
Definition at line 58 of file ver.c.
Referenced by ver_main().
const char sz_ver_bdate_str[] = "bdate" static
Definition at line 55 of file ver.c.
Referenced by ver_main().
const char sz_ver_buri_str[] = "uri" static
Definition at line 56 of file ver.c.
Referenced by ver_main().
const char sz_ver_gcc_str[] = "gcc" static
Definition at line 57 of file ver.c.
Referenced by ver_main().
const char sz_ver_git_str[] = "git" static
Definition at line 54 of file ver.c.
Referenced by ver_main().
const char sz_ver_hw_str[] = "hw" static
Definition at line 51 of file ver.c.
Referenced by ver_main().
const char sz_ver_hwcmp_str[] = "hwcmp" static
Definition at line 52 of file ver.c.
Referenced by ver_main().
const char sz_ver_hwtypecmp_str[] = "hwtypecmp" static
Definition at line 53 of file ver.c.
Referenced by ver_main().