PX4 Firmware: SyslinkMemory Class Reference
SyslinkMemory Class Reference
#include <syslink_main.h>
Public Member Functions
SyslinkMemory (Syslink *link)
virtual ~SyslinkMemory ()
virtual int init ()
Initialise the driver and make it ready for use.
virtual ssize_t read (struct file *filp, char *buffer, size_t buflen)
virtual ssize_t write (struct file *filp, const char *buffer, size_t buflen)
virtual int ioctl (struct file *filp, int cmd, unsigned long arg)
Public Member Functions inherited from device::CDev
CDev (const char *name, const char *devname)
Constructor.
virtual ~CDev ()
virtual int open (file_t *filep)
Handle an open of the device.
virtual int close (file_t *filep)
Handle a close of the device.
virtual ssize_t read (file_t *filep, char *buffer, size_t buflen)
Perform a read from the device.
virtual ssize_t write (file_t *filep, const char *buffer, size_t buflen)
Perform a write to the device.
virtual off_t seek (file_t *filep, off_t offset, int whence)
Perform a logical seek operation on the device.
virtual int ioctl (file_t *filep, int cmd, unsigned long arg)
Perform an ioctl operation on the device.
virtual int poll (file_t *filep, px4_pollfd_struct_t *fds, bool setup)
Perform a poll setup/teardown operation.
Public Member Functions inherited from device::Device
virtual ~Device ()=default
Destructor.
virtual int read (unsigned address, void *data, unsigned count)
Read directly from the device.
virtual int write (unsigned address, void *data, unsigned count)
Write directly to the device.
virtual int ioctl (unsigned operation, unsigned &arg)
Perform a device-specific operation.
uint8_t get_device_bus ()
Return the bus ID the device is connected to.
DeviceBusType get_device_bus_type ()
Return the bus type the device is connected to.
uint8_t get_device_address ()
Return the bus address of the device.
void set_device_address (int address)
void set_device_type (uint8_t devtype)
Set the device type.
virtual bool external ()
Private Member Functions
uint8_t scan ()
void getinfo (int i)
int read (int i, uint16_t addr, char *buf, int length)
int write (int i, uint16_t addr, const char *buf, int length)
void sendAndWait ()
Private Attributes
Syslink * _link
int _activeI
syslink_message_t msgbuf
Friends
class Syslink
Additional Inherited Members
Public Types inherited from device::Device
enum DeviceBusType { DeviceBusType_UNKNOWN = 0, DeviceBusType_I2C = 1, DeviceBusType_SPI = 2, DeviceBusType_UAVCAN = 3 }
Device bus types for DEVID.
Protected Member Functions inherited from device::CDev
virtual pollevent_t poll_state (file_t *filep)
Check the current state of the device for poll events from the perspective of the file.
virtual void poll_notify (pollevent_t events)
Report new poll events.
virtual void poll_notify_one (px4_pollfd_struct_t *fds, pollevent_t events)
Internal implementation of poll_notify.
virtual int open_first (file_t *filep)
Notification of the first open.
virtual int close_last (file_t *filep)
Notification of the last close.
virtual int register_class_devname (const char *class_devname)
Register a class device name, automatically adding device class instance suffix if need be.
virtual int unregister_class_devname (const char *class_devname, unsigned class_instance)
Register a class device name, automatically adding device class instance suffix if need be.
const char * get_devname ()
Get the device name.
void lock ()
Take the driver lock.
void unlock ()
Release the driver lock.
Protected Member Functions inherited from device::Device
Device (const char *name)
Device (DeviceBusType bus_type, uint8_t bus, uint8_t address, uint8_t devtype=0)
Device (const Device &)=delete
Device & operator= (const Device &)=delete
Device (Device &&)=delete
Device & operator= (Device &&)=delete
Protected Attributes inherited from device::CDev
px4_sem_t _lock
lock to protect access to all class members (also for derived classes)
bool _pub_blocked {false}
true if publishing should be blocked
Protected Attributes inherited from device::Device
union DeviceId _device_id
device identifier information
const char * _name
driver name
bool _debug_enabled {false}
if true, debug messages are printed
Static Protected Attributes inherited from device::CDev
static const px4_file_operations_t fops = {}
Pointer to the default cdev file operations table; useful for registering clone devices etc.
Detailed Description
Definition at line 190 of file syslink_main.h.
Constructor & Destructor Documentation
SyslinkMemory::SyslinkMemory (Syslink * link)
Definition at line 42 of file syslink_memory.cpp.
SyslinkMemory::~SyslinkMemory () virtual
Definition at line 51 of file syslink_memory.cpp.
Member Function Documentation
void SyslinkMemory::getinfo (int i) private
Definition at line 124 of file syslink_memory.cpp.
References data, msgbuf, sendAndWait(), and SYSLINK_OW_GETINFO.
Referenced by ioctl().
int SyslinkMemory::init () virtual
Initialise the driver and make it ready for use.
Returns
OK if the driver initialized OK, negative errno otherwise;
Reimplemented from device::CDev.
Definition at line 58 of file syslink_memory.cpp.
References DEVICE_DEBUG, lis3mdl::init(), and OK.
Referenced by Syslink::task_main().
int SyslinkMemory::ioctl (struct file * filp, int cmd, unsigned long arg) virtual
Definition at line 87 of file syslink_memory.cpp.
References _activeI, data, DECKIOGNUM, DECKIOID, DECKIOSNUM, getinfo(), msgbuf, and scan().
ssize_t SyslinkMemory::read (struct file * filp, char * buffer, size_t buflen) virtual
Definition at line 73 of file syslink_memory.cpp.
References _activeI.
int SyslinkMemory::read (int i, uint16_t addr, char * buf, int length) private
Definition at line 134 of file syslink_memory.cpp.
References data, MIN, msgbuf, sendAndWait(), and SYSLINK_OW_READ.
uint8_t SyslinkMemory::scan () private
Definition at line 113 of file syslink_memory.cpp.
References data, msgbuf, sendAndWait(), and SYSLINK_OW_SCAN.
Referenced by ioctl().
void SyslinkMemory::sendAndWait () private
Definition at line 172 of file syslink_memory.cpp.
References _link, Syslink::_queue, Syslink::memory_sem, msgbuf, and px4_sem_wait.
Referenced by getinfo(), read(), and scan().
ssize_t SyslinkMemory::write (struct file * filp, const char * buffer, size_t buflen) virtual
Definition at line 79 of file syslink_memory.cpp.
int SyslinkMemory::write (int i, uint16_t addr, const char * buf, int length) private
Definition at line 165 of file syslink_memory.cpp.
Friends And Related Function Documentation
friend class Syslink friend
Definition at line 204 of file syslink_main.h.
Member Data Documentation
int SyslinkMemory::_activeI private
Definition at line 208 of file syslink_main.h.
Referenced by ioctl(), and read().
Syslink* SyslinkMemory::_link private
Definition at line 206 of file syslink_main.h.
Referenced by sendAndWait().
syslink_message_t SyslinkMemory::msgbuf private
Definition at line 210 of file syslink_main.h.
Referenced by getinfo(), Syslink::handle_message(), ioctl(), read(), scan(), and sendAndWait().
The documentation for this class was generated from the following files:
src/modules/syslink/syslink_main.h
src/modules/syslink/syslink_memory.cpp