PX4 Firmware: src/lib/parameters/flashparams/flashfs.c File Reference
flashfs.c File Reference
#include <px4_defines.h>
#include <px4_posix.h>
#include <crc32.h>
#include <stddef.h>
#include <string.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdlib.h>
#include <errno.h>
#include "flashfs.h"
#include <nuttx/compiler.h>
#include <nuttx/progmem.h>
Classes
struct flash_entry_header_t
Typedefs
typedef uint32_t h_magic_t
typedef uint16_t h_size_t
typedef uint16_t h_flag_t
typedef uint16_t data_size_t
typedef enum flash_config_t flash_config_t
typedef enum flash_flags_t flash_flags_t
typedef begin_packed_struct struct flash_entry_header_t flash_entry_header_t
Enumerations
enum flash_config_t { LargestBlock = 2 * 1024, MagicSig = 0xaa553cc3, BlankSig = 0xffffffff }
enum flash_flags_t {
SizeMask = 0x0003, MaskEntry = ~SizeMask, BlankEntry = (h_flag_t)BlankSig, ValidEntry = (0xa5ac & ~SizeMask),
ErasedEntry = 0x0000
}
Functions
void parameter_flashfs_free (void)
static int blank_flash (uint32_t *pf)
static bool blank_check (flash_entry_header_t *pf, size_t new_size)
static int valid_magic (h_magic_t *pm)
static int blank_magic (h_magic_t *pm)
static int erased_entry (flash_entry_header_t *fi)
static int blank_entry (flash_entry_header_t *fi)
static int valid_entry (flash_entry_header_t *fi)
static int entry_size_adjust (flash_entry_header_t *fi)
static flash_entry_header_t * next_entry (flash_entry_header_t *fi)
static uint8_t * entry_data (flash_entry_header_t *fi)
static data_size_t entry_data_length (flash_entry_header_t *fi)
static const uint8_t * entry_crc_start (flash_entry_header_t *fi)
static data_size_t entry_crc_length (flash_entry_header_t *fi)
static flash_entry_header_t * find_entry (flash_file_token_t token)
static flash_entry_header_t * find_free (data_size_t required)
static sector_descriptor_t * get_next_sector_descriptor (sector_descriptor_t *current)
static sector_descriptor_t * get_sector_info (flash_entry_header_t *current)
static int erase_sector (sector_descriptor_t *sm, flash_entry_header_t *pf)
static int erase_entry (flash_entry_header_t *pf)
static sector_descriptor_t * check_free_space_in_sector (flash_entry_header_t *pf, size_t new_size)
int parameter_flashfs_read (flash_file_token_t token, uint8_t **buffer, size_t *buf_size)
int parameter_flashfs_write (flash_file_token_t token, uint8_t *buffer, size_t buf_size)
int parameter_flashfs_alloc (flash_file_token_t token, uint8_t **buffer, size_t *buf_size)
int parameter_flashfs_erase (void)
int parameter_flashfs_init (sector_descriptor_t *fconfig, uint8_t *buffer, uint16_t size)
Variables
static uint8_t * working_buffer
static uint16_t working_buffer_size
static bool working_buffer_static
static sector_descriptor_t * sector_map
static int last_erased
const flash_file_token_t parameters_token
Typedef Documentation
typedef uint16_t data_size_t
Definition at line 69 of file flashfs.c.
typedef enum flash_config_t flash_config_t
typedef begin_packed_struct struct flash_entry_header_t flash_entry_header_t
typedef enum flash_flags_t flash_flags_t
typedef uint16_t h_flag_t
Definition at line 68 of file flashfs.c.
typedef uint32_t h_magic_t
Definition at line 66 of file flashfs.c.
typedef uint16_t h_size_t
Definition at line 67 of file flashfs.c.
Enumeration Type Documentation
enum flash_config_t
Enumerator
LargestBlock
MagicSig
BlankSig
Definition at line 71 of file flashfs.c.
enum flash_flags_t
Enumerator
SizeMask
MaskEntry
BlankEntry
ValidEntry
ErasedEntry
Definition at line 77 of file flashfs.c.
Function Documentation
static bool blank_check (flash_entry_header_t * pf, size_t new_size) static
Definition at line 184 of file flashfs.c.
References blank_flash().
Referenced by find_free(), and parameter_flashfs_write().
static int blank_entry (flash_entry_header_t * fi) inline static
Definition at line 276 of file flashfs.c.
References BlankEntry, BlankSig, flash_entry_header_t::flag, and flash_entry_header_t::magic.
Referenced by find_entry(), and find_free().
static int blank_flash (uint32_t * pf) inline static
Definition at line 164 of file flashfs.c.
References BlankSig.
Referenced by blank_check().
static int blank_magic (h_magic_t * pm) inline static
Definition at line 237 of file flashfs.c.
References BlankSig.
Referenced by find_free().
static sector_descriptor_t* check_free_space_in_sector (flash_entry_header_t * pf, size_t new_size) static
Definition at line 702 of file flashfs.c.
References sector_descriptor_t::address, get_sector_info(), next_entry(), sector_descriptor_t::size, and valid_magic().
Referenced by parameter_flashfs_write().
static data_size_t entry_crc_length (flash_entry_header_t * fi) inline static
Definition at line 420 of file flashfs.c.
References flash_entry_header_t::size.
Referenced by find_entry(), find_free(), and parameter_flashfs_write().
static const uint8_t* entry_crc_start (flash_entry_header_t * fi) inline static
Definition at line 399 of file flashfs.c.
References flash_entry_header_t::size.
Referenced by find_entry(), find_free(), and parameter_flashfs_write().
static uint8_t* entry_data (flash_entry_header_t * fi) inline static
Definition at line 358 of file flashfs.c.
Referenced by parameter_flashfs_read().
static data_size_t entry_data_length (flash_entry_header_t * fi) inline static
Definition at line 378 of file flashfs.c.
References entry_size_adjust(), and flash_entry_header_t::size.
Referenced by parameter_flashfs_read().
static int entry_size_adjust (flash_entry_header_t * fi) inline static
Definition at line 316 of file flashfs.c.
References flash_entry_header_t::flag, and SizeMask.
Referenced by entry_data_length().
static int erase_entry (flash_entry_header_t * pf) static
Definition at line 678 of file flashfs.c.
References data, ErasedEntry, flash_entry_header_t::flag, and flash_entry_header_t::size.
Referenced by parameter_flashfs_write().
static int erase_sector (sector_descriptor_t * sm, flash_entry_header_t * pf) static
Definition at line 645 of file flashfs.c.
References sector_descriptor_t::page, flash_entry_header_t::size, and sector_descriptor_t::size.
Referenced by parameter_flashfs_erase(), and parameter_flashfs_write().
static int erased_entry (flash_entry_header_t * fi) inline static
Definition at line 256 of file flashfs.c.
References ErasedEntry, flash_entry_header_t::flag, and MaskEntry.
static flash_entry_header_t* find_entry (flash_file_token_t token) static
Definition at line 440 of file flashfs.c.
References sector_descriptor_t::address, blank_entry(), flash_entry_header_t::crc, entry_crc_length(), entry_crc_start(), flash_entry_header_t::file_token, next_entry(), sector_descriptor_t::size, flash_file_token_t::t, valid_entry(), and valid_magic().
Referenced by parameter_flashfs_init(), parameter_flashfs_read(), and parameter_flashfs_write().
static flash_entry_header_t* find_free (data_size_t required) static
Definition at line 515 of file flashfs.c.
References sector_descriptor_t::address, blank_check(), blank_entry(), blank_magic(), flash_entry_header_t::crc, entry_crc_length(), entry_crc_start(), next_entry(), sector_descriptor_t::size, and valid_magic().
Referenced by parameter_flashfs_init(), and parameter_flashfs_write().
static sector_descriptor_t* get_next_sector_descriptor (sector_descriptor_t * current) static
Definition at line 576 of file flashfs.c.
References sector_descriptor_t::address.
Referenced by parameter_flashfs_write().
static sector_descriptor_t* get_sector_info (flash_entry_header_t * current) static
Definition at line 612 of file flashfs.c.
References sector_descriptor_t::address, and sector_descriptor_t::size.
Referenced by check_free_space_in_sector().
static flash_entry_header_t* next_entry (flash_entry_header_t * fi) inline static
Definition at line 337 of file flashfs.c.
References flash_entry_header_t::size.
Referenced by check_free_space_in_sector(), find_entry(), find_free(), and parameter_flashfs_write().
int parameter_flashfs_alloc (flash_file_token_t token, uint8_t ** buffer, size_t * buf_size)
Definition at line 915 of file flashfs.c.
Referenced by param_export_internal(), and parameter_flashfs_init().
int parameter_flashfs_erase (void)
Definition at line 964 of file flashfs.c.
References sector_descriptor_t::address, erase_sector(), and sector_descriptor_t::size.
Referenced by parameter_flashfs_init().
void parameter_flashfs_free (void)
Definition at line 139 of file flashfs.c.
Referenced by param_export_internal(), and parameter_flashfs_init().
int parameter_flashfs_init (sector_descriptor_t * fconfig, uint8_t * buffer, uint16_t size)
Definition at line 1013 of file flashfs.c.
References find_entry(), find_free(), parameter_flashfs_alloc(), parameter_flashfs_erase(), parameter_flashfs_free(), parameter_flashfs_init(), parameter_flashfs_read(), parameter_flashfs_write(), read(), flash_entry_header_t::size, and test.
Referenced by board_app_initialize(), and parameter_flashfs_init().
int parameter_flashfs_read (flash_file_token_t token, uint8_t ** buffer, size_t * buf_size)
Definition at line 740 of file flashfs.c.
References entry_data(), entry_data_length(), and find_entry().
Referenced by param_export_internal(), param_import_internal(), and parameter_flashfs_init().
int parameter_flashfs_write (flash_file_token_t token, uint8_t * buffer, size_t buf_size)
Definition at line 780 of file flashfs.c.
References sector_descriptor_t::address, blank_check(), BlankSig, check_free_space_in_sector(), flash_entry_header_t::crc, entry_crc_length(), entry_crc_start(), erase_entry(), erase_sector(), flash_entry_header_t::file_token, find_entry(), find_free(), flash_entry_header_t::flag, get_next_sector_descriptor(), flash_entry_header_t::magic, MagicSig, next_entry(), flash_entry_header_t::size, sector_descriptor_t::size, flash_file_token_t::t, and ValidEntry.
Referenced by param_export_internal(), and parameter_flashfs_init().
static int valid_entry (flash_entry_header_t * fi) inline static
Definition at line 296 of file flashfs.c.
References flash_entry_header_t::flag, MaskEntry, and ValidEntry.
Referenced by find_entry().
static int valid_magic (h_magic_t * pm) inline static
Definition at line 216 of file flashfs.c.
References MagicSig.
Referenced by check_free_space_in_sector(), find_entry(), and find_free().
Variable Documentation
int last_erased static
Definition at line 116 of file flashfs.c.
const flash_file_token_t parameters_token
Initial value:
= {
    .n = {'p', 'a', 'r', 'm'},
}
Definition at line 122 of file flashfs.c.
Referenced by param_export_internal(), and param_import_internal().
sector_descriptor_t* sector_map static
Definition at line 115 of file flashfs.c.
Referenced by board_app_initialize().
uint8_t* working_buffer static
Definition at line 112 of file flashfs.c.
uint16_t working_buffer_size static
Definition at line 113 of file flashfs.c.
bool working_buffer_static static
Definition at line 114 of file flashfs.c.