PX4 Firmware: src/drivers/magnetometer/ak09916/ak09916.cpp File Reference
ak09916.cpp File Reference
#include <px4_platform_common/px4_config.h>
#include <px4_platform_common/log.h>
#include <px4_platform_common/time.h>
#include <lib/perf/perf_counter.h>
#include <drivers/drv_hrt.h>
#include <lib/conversion/rotation.h>
#include <px4_platform_common/getopt.h>
#include "ak09916.hpp"
Namespaces
ak09916
Functions
__EXPORT int ak09916_main (int argc, char *argv[])
Driver for the standalone AK09916 magnetometer.
void ak09916::start (bool, enum Rotation)
void ak09916::info (bool)
void ak09916::usage ()
Prints info about the driver argument usage.
void ak09916::stop (bool external_bus)
Variables
AK09916 * ak09916::g_dev_ext
AK09916 * ak09916::g_dev_int
Function Documentation
ak09916_main()
int ak09916_main (int argc, char * argv[])
Driver for the standalone AK09916 magnetometer.
Definition at line 340 of file ak09916.cpp.
References ak09916::info(), ROTATION_NONE, ak09916::start(), ak09916::stop(), and ak09916::usage().