PX4 Firmware: Sensors Class Reference
Sensors Class Reference
Public Member Functions
Sensors (bool hil_enabled)
~Sensors ()=default
void run () override
int print_status () override
Public Member Functions inherited from ModuleParams
ModuleParams (ModuleParams *parent)
void setParent (ModuleParams *parent)
Set the parent module.
virtual ~ModuleParams ()=default
ModuleParams (const ModuleParams &)=delete
ModuleParams & operator= (const ModuleParams &)=delete
ModuleParams (ModuleParams &&)=delete
ModuleParams & operator= (ModuleParams &&)=delete
Public Member Functions inherited from ListNode< ModuleParams * >
ListNode ()
ListNode (const ListNode &)=delete
ListNode (ListNode &&)=delete
virtual ~ListNode ()=default
ListNode & operator= (const ListNode &)=delete
ListNode & operator= (ListNode &&)=delete
void setSibling (ModuleParams *sibling)
const ModuleParams * getSibling ()
Static Public Member Functions
static int task_spawn (int argc, char *argv[])
static Sensors * instantiate (int argc, char *argv[])
static int custom_command (int argc, char *argv[])
static int print_usage (const char *reason=nullptr)
Private Member Functions
int parameters_update ()
Update our local parameter cache.
int adc_init ()
Do adc-related initialisation.
void diff_pres_poll (const vehicle_air_data_s &airdata)
Poll the differential pressure sensor for updated data.
void vehicle_control_mode_poll ()
Check for changes in vehicle control mode.
void parameter_update_poll (bool forced=false)
Check for changes in parameters.
void adc_poll ()
Poll the ADC and update readings to suit.
Private Attributes
DevHandle _h_adc
ADC driver handle.
hrt_abstime _last_adc {0}
last time we took input from the ADC
const bool _hil_enabled
if true, HIL is active
bool _armed {false}
arming status of the vehicle
int _actuator_ctrl_0_sub {-1}
attitude controls sub
int _diff_pres_sub {-1}
raw differential pressure subscription
int _vcontrol_mode_sub {-1}
vehicle control mode subscription
int _params_sub {-1}
notification of parameter updates
orb_advert_t _sensor_pub {nullptr}
combined sensor data topic
orb_advert_t _airdata_pub {nullptr}
combined sensor data topic
orb_advert_t _magnetometer_pub {nullptr}
combined sensor data topic
orb_advert_t _airspeed_pub {nullptr}
airspeed
orb_advert_t _sensor_preflight {nullptr}
sensor preflight topic
perf_counter_t _loop_perf
loop performance counter
DataValidator _airspeed_validator
data validator to monitor airspeed
Parameters _parameters {}
local copies of interesting parameters
ParameterHandles _parameter_handles {}
handles for interesting parameters
RCUpdate _rc_update
VotedSensorsUpdate _voted_sensors_update
Additional Inherited Members
Protected Member Functions inherited from ModuleParams
virtual void updateParams ()
Call this whenever the module gets a parameter change notification.
virtual void updateParamsImpl ()
The implementation for this is generated with the macro DEFINE_PARAMETERS()
Protected Attributes inherited from ListNode< ModuleParams * >
ModuleParams * _sibling
Detailed Description
Definition at line 135 of file sensors.cpp.
Constructor & Destructor Documentation
Sensors::Sensors (bool hil_enabled)
Definition at line 243 of file sensors.cpp.
References _airspeed_validator, _parameter_handles, BOARD_NUMBER_BRICKS, sensors::initialize_parameter_handles(), DataValidator::set_equal_value_threshold(), and DataValidator::set_timeout().
Referenced by instantiate().
Sensors::~Sensors () default
Member Function Documentation
int Sensors::adc_init () private
Do adc-related initialisation.
Definition at line 286 of file sensors.cpp.
References _h_adc, ADC0_DEVICE_PATH, OK, PX4_ERR, and PX4_ERROR.
Referenced by run().
void Sensors::adc_poll () private
Poll the ADC and update readings to suit.
Parameters
raw Combined sensor data structure into which data should be returned.
Definition at line 415 of file sensors.cpp.
References _actuator_ctrl_0_sub, _armed, _h_adc, _hil_enabled, _last_adc, _parameters, ADC_AIRSPEED_VOLTAGE_CHANNEL, sensors::Parameters::battery_a_per_v, sensors::Parameters::battery_adc_channel, sensors::Parameters::battery_current_offset, sensors::Parameters::battery_current_scaling, sensors::Parameters::battery_source, sensors::Parameters::battery_v_div, sensors::Parameters::battery_voltage_scaling, BOARD_ADC_OPEN_CIRCUIT_V, BOARD_BATT_I_LIST, BOARD_BATT_V_LIST, BOARD_BRICK_VALID_LIST, BOARD_NUMBER_BRICKS, BOARD_VALID_UV, actuator_controls_s::control, sensors::Parameters::diff_pres_offset_pa, f(), hrt_absolute_time(), hrt_abstime, instance, orb_advert_t, orb_copy(), ORB_ID, ORB_PRIO_DEFAULT, orb_publish_auto(), px4_adc_msg_t, and PX4_MAX_ADC_CHANNELS.
Referenced by run().
int Sensors::custom_command (int argc, char * argv[]) static
See also
ModuleBase
Definition at line 767 of file sensors.cpp.
References print_usage().
void Sensors::diff_pres_poll (const vehicle_air_data_s & airdata) private
Poll the differential pressure sensor for updated data.
Parameters
raw Combined sensor data structure into which data should be returned.
Definition at line 299 of file sensors.cpp.
References _airspeed_pub, _airspeed_validator, _diff_pres_sub, _parameters, sensors::Parameters::air_cmodel, airspeed_s::air_temperature_celsius, sensors::Parameters::air_tube_diameter_mm, sensors::Parameters::air_tube_length, AIRSPEED_SENSOR_MODEL_MEMBRANE, AIRSPEED_SENSOR_MODEL_SDP3X, vehicle_air_data_s::baro_pressure_pa, vehicle_air_data_s::baro_temp_celcius, calc_indicated_airspeed_corrected(), calc_true_airspeed_from_indicated(), airspeed_s::confidence, DataValidator::confidence(), differential_pressure_s::device_id, differential_pressure_s::differential_pressure_filtered_pa, differential_pressure_s::differential_pressure_raw_pa, DRV_DIFF_PRESS_DEVTYPE_SDP31, DRV_DIFF_PRESS_DEVTYPE_SDP32, DRV_DIFF_PRESS_DEVTYPE_SDP33, differential_pressure_s::error_count, hrt_absolute_time(), airspeed_s::indicated_airspeed_m_s, instance, orb_check(), orb_copy(), ORB_ID, ORB_PRIO_DEFAULT, ORB_PRIO_HIGH, orb_publish_auto(), PCB_TEMP_ESTIMATE_DEG, DataValidator::put(), PX4_OK, differential_pressure_s::temperature, differential_pressure_s::timestamp, airspeed_s::timestamp, and airspeed_s::true_airspeed_m_s.
Referenced by run().
Sensors * Sensors::instantiate (int argc, char * argv[]) static
See also
ModuleBase
Definition at line 811 of file sensors.cpp.
References px4_getopt(), PX4_WARN, and Sensors().
void Sensors::parameter_update_poll (bool forced = false) private
Check for changes in parameters.
Definition at line 380 of file sensors.cpp.
References _parameters, _params_sub, AIRSPEED0_DEVICE_PATH, AIRSPEEDIOCSSCALE, sensors::Parameters::diff_pres_offset_pa, fd, OK, orb_check(), orb_copy(), ORB_ID, parameters_update(), px4_close(), px4_ioctl(), px4_open(), ModuleParams::updateParams(), and warn.
Referenced by run().
int Sensors::parameters_update () private
Update our local parameter cache.
Definition at line 265 of file sensors.cpp.
References _armed, _parameter_handles, _parameters, _rc_update, _voted_sensors_update, sensors::VotedSensorsUpdate::parameters_update(), sensors::update_parameters(), and sensors::RCUpdate::update_rc_functions().
Referenced by parameter_update_poll().
int Sensors::print_status () override
See also
ModuleBase::print_status()
Definition at line 757 of file sensors.cpp.
References _airspeed_validator, _voted_sensors_update, DataValidator::print(), sensors::VotedSensorsUpdate::print_status(), and PX4_INFO.
int Sensors::print_usage (const char * reason = nullptr) static
See also
ModuleBase
Definition at line 772 of file sensors.cpp.
References PRINT_MODULE_DESCRIPTION(), PRINT_MODULE_USAGE_COMMAND, PRINT_MODULE_USAGE_DEFAULT_COMMANDS, PRINT_MODULE_USAGE_NAME(), PRINT_MODULE_USAGE_PARAM_FLAG(), and PX4_WARN.
Referenced by custom_command().
void Sensors::run () override
See also
ModuleBase::run()
Definition at line 583 of file sensors.cpp.
References _actuator_ctrl_0_sub, _airdata_pub, _armed, _diff_pres_sub, _hil_enabled, _loop_perf, _magnetometer_pub, _parameter_handles, _params_sub, _rc_update, _sensor_preflight, _sensor_pub, _vcontrol_mode_sub, _voted_sensors_update, adc_init(), adc_poll(), sensors::VotedSensorsUpdate::best_gyro_fd(), sensors::VotedSensorsUpdate::calc_accel_inconsistency(), sensors::VotedSensorsUpdate::calc_gyro_inconsistency(), sensors::VotedSensorsUpdate::calc_mag_inconsistency(), sensors::VotedSensorsUpdate::check_failover(), sensors::RCUpdate::deinit(), sensors::VotedSensorsUpdate::deinit(), diff_pres_poll(), hrt_absolute_time(), hrt_elapsed_time(), sensors::RCUpdate::init(), sensors::VotedSensorsUpdate::init(), sensors::VotedSensorsUpdate::initialize_sensors(), instance, sensors::VotedSensorsUpdate::num_gyros(), orb_advertise(), ORB_ID, ORB_PRIO_DEFAULT, orb_publish(), orb_publish_auto(), orb_subscribe(), orb_unadvertise(), orb_unsubscribe(), parameter_update_poll(), perf_begin(), perf_end(), px4_poll(), sensors::RCUpdate::rc_parameter_map_poll(), sensors::RCUpdate::rc_poll(), sensors::VotedSensorsUpdate::sensors_poll(), sensors::VotedSensorsUpdate::set_relative_timestamps(), vehicle_air_data_s::timestamp, sensor_preflight_s::timestamp, vehicle_magnetometer_s::timestamp, sensor_combined_s::timestamp, usleep(), and vehicle_control_mode_poll().
int Sensors::task_spawn (int argc, char * argv[]) static
See also
ModuleBase
Definition at line 739 of file sensors.cpp.
References px4_task_spawn_cmd(), SCHED_DEFAULT, and SCHED_PRIORITY_SENSOR_HUB.
void Sensors::vehicle_control_mode_poll () private
Check for changes in vehicle control mode.
Definition at line 365 of file sensors.cpp.
References _armed, _vcontrol_mode_sub, vehicle_control_mode_s::flag_armed, orb_check(), orb_copy(), and ORB_ID.
Referenced by run().
Member Data Documentation
int Sensors::_actuator_ctrl_0_sub {-1} private
attitude controls sub
Definition at line 167 of file sensors.cpp.
Referenced by adc_poll(), and run().
orb_advert_t Sensors::_airdata_pub {nullptr} private
combined sensor data topic
Definition at line 173 of file sensors.cpp.
Referenced by run().
orb_advert_t Sensors::_airspeed_pub {nullptr} private
airspeed
Definition at line 186 of file sensors.cpp.
Referenced by diff_pres_poll().
DataValidator Sensors::_airspeed_validator private
data validator to monitor airspeed
Definition at line 191 of file sensors.cpp.
Referenced by diff_pres_poll(), print_status(), and Sensors().
bool Sensors::_armed {false} private
arming status of the vehicle
Definition at line 165 of file sensors.cpp.
Referenced by adc_poll(), parameters_update(), run(), and vehicle_control_mode_poll().
int Sensors::_diff_pres_sub {-1} private
raw differential pressure subscription
Definition at line 168 of file sensors.cpp.
Referenced by diff_pres_poll(), and run().
DevHandle Sensors::_h_adc private
ADC driver handle.
Definition at line 160 of file sensors.cpp.
Referenced by adc_init(), and adc_poll().
const bool Sensors::_hil_enabled private
if true, HIL is active
Definition at line 164 of file sensors.cpp.
Referenced by adc_poll(), and run().
hrt_abstime Sensors::_last_adc {0} private
last time we took input from the ADC
Definition at line 162 of file sensors.cpp.
Referenced by adc_poll().
perf_counter_t Sensors::_loop_perf private
loop performance counter
Definition at line 189 of file sensors.cpp.
Referenced by run().
orb_advert_t Sensors::_magnetometer_pub {nullptr} private
combined sensor data topic
Definition at line 174 of file sensors.cpp.
Referenced by run().
ParameterHandles Sensors::_parameter_handles {} private
handles for interesting parameters
Definition at line 200 of file sensors.cpp.
Referenced by parameters_update(), run(), and Sensors().
Parameters Sensors::_parameters {} private
local copies of interesting parameters
Definition at line 199 of file sensors.cpp.
Referenced by adc_poll(), diff_pres_poll(), parameter_update_poll(), and parameters_update().
int Sensors::_params_sub {-1} private
notification of parameter updates
Definition at line 170 of file sensors.cpp.
Referenced by parameter_update_poll(), and run().
RCUpdate Sensors::_rc_update private
Definition at line 202 of file sensors.cpp.
Referenced by parameters_update(), and run().
orb_advert_t Sensors::_sensor_preflight {nullptr} private
sensor preflight topic
Definition at line 187 of file sensors.cpp.
Referenced by run().
orb_advert_t Sensors::_sensor_pub {nullptr} private
combined sensor data topic
Definition at line 172 of file sensors.cpp.
Referenced by run().
int Sensors::_vcontrol_mode_sub {-1} private
vehicle control mode subscription
Definition at line 169 of file sensors.cpp.
Referenced by run(), and vehicle_control_mode_poll().
VotedSensorsUpdate Sensors::_voted_sensors_update private
Definition at line 203 of file sensors.cpp.
Referenced by parameters_update(), print_status(), and run().
The documentation for this class was generated from the following file:
src/modules/sensors/sensors.cpp