PX4 Firmware: src/drivers/boards/zubaxgnss-v1/gnss_init.c File Reference
gnss_init.c File Reference
#include <px4_config.h>
#include <stdbool.h>
#include <stdio.h>
#include <debug.h>
#include <errno.h>
#include "platform/cxxinitialize.h"
#include <nuttx/board.h>
#include <nuttx/spi/spi.h>
#include <nuttx/i2c/i2c_master.h>
#include <nuttx/mmcsd.h>
#include <nuttx/analog/adc.h>
#include <stm32.h>
#include "board_config.h"
#include "stm32_uart.h"
#include <arch/board/board.h>
#include <drivers/drv_hrt.h>
#include <drivers/drv_board_led.h>
#include <systemlib/cpuload.h>
Functions
__BEGIN_DECLS void led_off (int led)
__END_DECLS __EXPORT void stm32_boardinitialize (void)
__EXPORT void board_initialize (void)
__EXPORT int board_app_initialize (uintptr_t arg)
Function Documentation
__EXPORT int board_app_initialize (uintptr_t arg)
Definition at line 147 of file gnss_init.c.
References hrt_call_every(), hrt_init(), OK, and ts_to_abstime().
__EXPORT void board_initialize (void)
Definition at line 117 of file gnss_init.c.
__BEGIN_DECLS void led_off (int led)
Definition at line 97 of file led.c.
__END_DECLS __EXPORT void stm32_boardinitialize (void)
Definition at line 110 of file gnss_init.c.
References board_autoled_initialize().