PX4 Firmware: px4::Mavlink Class Reference
px4::Mavlink Class Reference
#include <mavlink.h>
Public Member Functions
Mavlink (std::string mavlink_fcu_url)
~Mavlink ()
Protected Member Functions
void VehicleAttitudeCallback (const vehicle_attitudeConstPtr &msg)
Simulates output of attitude data from the FCU Equivalent to the mavlink stream ATTITUDE_QUATERNION.
void VehicleLocalPositionCallback (const vehicle_local_positionConstPtr &msg)
Simulates output of local position data from the FCU Equivalent to the mavlink stream LOCAL_POSITION_NED.
void handle_msg (const mavlink_message_t *mmsg, uint8_t sysid, uint8_t compid)
Handle incoming mavlink messages ant publish them to ROS ("Mavlink Receiver")
void handle_msg_set_attitude_target (const mavlink_message_t *mmsg)
Handle SET_ATTITUDE_TARGET mavlink messages.
void handle_msg_set_position_target_local_ned (const mavlink_message_t *mmsg)
Handle SET_POSITION_TARGET_LOCAL_NED mavlink messages.
Protected Attributes
ros::NodeHandle _n
mavconn::MAVConnInterface::Ptr _link
ros::Subscriber _v_att_sub
ros::Subscriber _v_local_pos_sub
ros::Publisher _v_att_sp_pub
ros::Publisher _pos_sp_triplet_pub
ros::Publisher _offboard_control_mode_pub
ros::Publisher _force_sp_pub
vehicle_attitude_setpoint _att_sp
offboard_control_mode _offboard_control_mode
Detailed Description
Definition at line 56 of file mavlink.h.
Constructor & Destructor Documentation
Mavlink::Mavlink (std::string mavlink_fcu_url)
Definition at line 49 of file mavlink.cpp.
References _att_sp, _link, _offboard_control_mode, and handle_msg().
px4::Mavlink::~Mavlink () inline
Definition at line 61 of file mavlink.h.
Member Function Documentation
void Mavlink::handle_msg (const mavlink_message_t * mmsg, uint8_t sysid, uint8_t compid) protected
Handle incoming mavlink messages ant publish them to ROS ("Mavlink Receiver")
Definition at line 112 of file mavlink.cpp.
References handle_msg_set_attitude_target(), and handle_msg_set_position_target_local_ned().
Referenced by Mavlink().
void Mavlink::handle_msg_set_attitude_target (const mavlink_message_t * mmsg) protected
Handle SET_ATTITUDE_TARGET mavlink messages.
Definition at line 132 of file mavlink.cpp.
References _att_sp, _offboard_control_mode, _offboard_control_mode_pub, _v_att_sp_pub, and px4::get_time_micros().
Referenced by handle_msg().
void Mavlink::handle_msg_set_position_target_local_ned (const mavlink_message_t * mmsg) protected
Handle SET_POSITION_TARGET_LOCAL_NED mavlink messages.
Definition at line 198 of file mavlink.cpp.
References _offboard_control_mode_pub, _pos_sp_triplet_pub, px4::get_time_micros(), offboard_control_mode_s::ignore_position, offboard_control_mode, and PX4_WARN.
Referenced by handle_msg().
void Mavlink::VehicleAttitudeCallback (const vehicle_attitudeConstPtr & msg) protected
Simulates output of attitude data from the FCU Equivalent to the mavlink stream ATTITUDE_QUATERNION.
Definition at line 75 of file mavlink.cpp.
References _link, and px4::get_time_micros().
void Mavlink::VehicleLocalPositionCallback (const vehicle_local_positionConstPtr & msg) protected
Simulates output of local position data from the FCU Equivalent to the mavlink stream LOCAL_POSITION_NED.
Definition at line 94 of file mavlink.cpp.
References _link, and px4::get_time_micros().
Member Data Documentation
vehicle_attitude_setpoint px4::Mavlink::_att_sp protected
Definition at line 73 of file mavlink.h.
Referenced by handle_msg_set_attitude_target(), and Mavlink().
ros::Publisher px4::Mavlink::_force_sp_pub protected
Definition at line 72 of file mavlink.h.
mavconn::MAVConnInterface::Ptr px4::Mavlink::_link protected
Definition at line 66 of file mavlink.h.
Referenced by Mavlink(), VehicleAttitudeCallback(), and VehicleLocalPositionCallback().
ros::NodeHandle px4::Mavlink::_n protected
Definition at line 65 of file mavlink.h.
offboard_control_mode px4::Mavlink::_offboard_control_mode protected
Definition at line 74 of file mavlink.h.
Referenced by handle_msg_set_attitude_target(), and Mavlink().
ros::Publisher px4::Mavlink::_offboard_control_mode_pub protected
Definition at line 71 of file mavlink.h.
Referenced by handle_msg_set_attitude_target(), and handle_msg_set_position_target_local_ned().
ros::Publisher px4::Mavlink::_pos_sp_triplet_pub protected
Definition at line 70 of file mavlink.h.
Referenced by handle_msg_set_position_target_local_ned().
ros::Publisher px4::Mavlink::_v_att_sp_pub protected
Definition at line 69 of file mavlink.h.
Referenced by handle_msg_set_attitude_target().
ros::Subscriber px4::Mavlink::_v_att_sub protected
Definition at line 67 of file mavlink.h.
ros::Subscriber px4::Mavlink::_v_local_pos_sub protected
Definition at line 68 of file mavlink.h.
The documentation for this class was generated from the following files:
src/platforms/ros/nodes/mavlink/mavlink.h
src/platforms/ros/nodes/mavlink/mavlink.cpp