PX4 Firmware: src/drivers/boards/px4fmu-v5/led.c File Reference
led.c File Reference
#include <px4_config.h>
#include <stdbool.h>
#include "chip.h"
#include "stm32_gpio.h"
#include "board_config.h"
#include <nuttx/board.h>
#include <arch/board/board.h>
Macros
#define xlat(p) (p)
Functions
__BEGIN_DECLS void led_init (void)
Ideally we'd be able to get these from up_internal.h, but since we want to be able to disable the NuttX use of leds for system indication at will and there is no separate switch, we need to build independent of the CONFIG_ARCH_LEDS configuration switch.
void led_on (int led)
void led_off (int led)
void led_toggle (int led)
static void phy_set_led (int led, bool state)
static bool phy_get_led (int led)
Variables
static uint32_t g_ledmap []
Macro Definition Documentation
#define xlat (p) (p)
Definition at line 80 of file led.c.
Referenced by led_off(), led_on(), and led_toggle().
Function Documentation
__BEGIN_DECLS void led_init (void)
Ideally we'd be able to get these from up_internal.h, but since we want to be able to disable the NuttX use of leds for system indication at will and there is no separate switch, we need to build independent of the CONFIG_ARCH_LEDS configuration switch.
Definition at line 90 of file led.c.
References g_ledmap, GPIO_nSAFETY_SWITCH_LED_OUT, PX4_MFT_HW_SUPPORTED, and PX4_MFT_PX4IO.
void led_off (int led)
Definition at line 120 of file led.c.
References phy_set_led(), and xlat.
void led_on (int led)
Definition at line 115 of file led.c.
References phy_set_led(), and xlat.
void led_toggle (int led)
Definition at line 125 of file led.c.
References board_autoled_initialize(), board_autoled_off(), board_autoled_on(), LED_ASSERTION, LED_HEAPALLOCATE, LED_INIRQ, led_init(), LED_IRQSENABLED, LED_PANIC, LED_SIGNAL, LED_STACKCREATED, phy_get_led(), phy_set_led(), and xlat.
static bool phy_get_led (int led) static
Definition at line 109 of file led.c.
References g_ledmap.
Referenced by led_toggle().
static void phy_set_led (int led, bool state) static
Definition at line 102 of file led.c.
References g_ledmap.
Referenced by led_off(), led_on(), and led_toggle().
Variable Documentation
uint32_t g_ledmap[] static
Initial value:
= {
    GPIO_nLED_BLUE,
    GPIO_nLED_RED,
    GPIO_nSAFETY_SWITCH_LED_OUT_INIT,
    GPIO_nLED_GREEN,
}
Definition at line 81 of file led.c.
Referenced by led_init(), phy_get_led(), and phy_set_led().