PX4 Firmware: barosim Namespace Reference
barosim Namespace Reference
Functions
static int start ()
Start the driver.
static int info ()
Print a little info about the driver.
static void usage ()
Function Documentation
static int barosim::info () static
Print a little info about the driver.
Definition at line 306 of file baro.cpp.
References BAROSIM_DEV_PATH, BAROSIM::print_info(), and PX4_INFO.
Referenced by barosim_main().
static int barosim::start () static
Start the driver.
This function call only returns once the driver is either successfully up and running or failed to start.
Definition at line 288 of file baro.cpp.
References BAROSIM::BAROSIM(), BAROSIM_DEV_PATH, g_barosim, BAROSIM::init(), OK, and PX4_ERR.
Referenced by barosim_main().
static void barosim::usage (void) static
Definition at line 317 of file baro.cpp.
References PX4_WARN.
Referenced by barosim_main().