PX4 Firmware: src/drivers/distance_sensor/cm8jl65/cm8jl65_main.cpp File Reference
cm8jl65_main.cpp File Reference
#include <px4_platform_common/cli.h>
#include <px4_platform_common/getopt.h>
#include "CM8JL65.hpp"
Namespaces
cm8jl65
Local functions in support of the shell command.
Functions
int cm8jl65::reset (const char *port)
Reset the driver.
int cm8jl65::start (const char *port, const uint8_t rotation)
Start the driver.
int cm8jl65::status ()
Print the driver status.
int cm8jl65::stop ()
Stop the driver.
int cm8jl65::usage ()
Prints info about the driver argument usage.
__EXPORT int cm8jl65_main (int argc, char *argv[])
Driver 'main' command.
Variables
CM8JL65 * cm8jl65::g_dev
Function Documentation
cm8jl65_main()
__EXPORT int cm8jl65_main (int argc, char * argv[])
Driver 'main' command.
Definition at line 147 of file cm8jl65_main.cpp.
References cm8jl65::reset(), cm8jl65::start(), cm8jl65::status(), cm8jl65::stop(), and cm8jl65::usage().