PX4 Firmware: px4::Rate Class Reference
px4::Rate Class Reference
Linux needs to have globally unique checks for thread/task status.
#include <px4_middleware.h>
Public Member Functions
Rate (unsigned rate_hz)
Construct the Rate object and set rate.
void sleep ()
Sleep for 1/rate_hz s.
Private Attributes
uint64_t sleep_interval
Detailed Description
Linux needs to have globally unique checks for thread/task status.
Definition at line 72 of file px4_middleware.h.
Constructor & Destructor Documentation
px4::Rate::Rate (unsigned rate_hz) inline explicit
Construct the Rate object and set rate.
Parameters
rate_hz rate from which sleep time is calculated in Hz
Definition at line 79 of file px4_middleware.h.
References sleep_interval.
Member Function Documentation
void px4::Rate::sleep () inline
Sleep for 1/rate_hz s.
Definition at line 84 of file px4_middleware.h.
References sleep_interval, and usleep().
Referenced by DemoOffboardAttitudeSetpoints::main(), and DemoOffboardPositionSetpoints::main().
Member Data Documentation
uint64_t px4::Rate::sleep_interval private
Definition at line 87 of file px4_middleware.h.
Referenced by Rate(), and sleep().
The documentation for this class was generated from the following file:
src/platforms/px4_middleware.h