PX4 Firmware: px4::AppState Class Reference
px4::AppState Class Reference
#include <px4_app.h>
Public Member Functions
~AppState ()
AppState ()
bool exitRequested ()
void requestExit ()
bool isRunning ()
void setRunning (bool running)
Protected Attributes
bool _exitRequested
bool _isRunning
Private Member Functions
AppState (const AppState &)
const AppState & operator= (const AppState &)
Detailed Description
Definition at line 46 of file px4_app.h.
Constructor & Destructor Documentation
px4::AppState::~AppState () inline
Definition at line 49 of file px4_app.h.
References AppState(), exitRequested(), and requestExit().
px4::AppState::AppState () inline
Definition at line 57 of file px4_app.h.
Referenced by ~AppState().
px4::AppState::AppState (const AppState &) private
Member Function Documentation
bool px4::AppState::exitRequested () inline
Definition at line 59 of file px4_app.h.
References _exitRequested.
Referenced by MuorbTestExample::DefaultTest(), HelloExample::main(), QShell::main(), WQueueTest::main(), MuorbTestExample::PingPongTest(), px4::NodeHandle::spin(), and ~AppState().
bool px4::AppState::isRunning () inline
Definition at line 62 of file px4_app.h.
References _isRunning.
const AppState& px4::AppState::operator= (const AppState &) private
void px4::AppState::requestExit () inline
Definition at line 60 of file px4_app.h.
References _exitRequested.
Referenced by hello_main(), hrt_test_main(), muorb_test_main(), qshell_main(), vcdev_test_main(), wqueue_test_main(), and ~AppState().
void px4::AppState::setRunning (bool running) inline
Definition at line 63 of file px4_app.h.
References _isRunning, and running.
Referenced by HelloExample::main(), HRTTest::main(), MuorbTestExample::main(), QShell::main(), and WQueueTest::main().
Member Data Documentation
bool px4::AppState::_exitRequested protected
Definition at line 66 of file px4_app.h.
Referenced by exitRequested(), and requestExit().
bool px4::AppState::_isRunning protected
Definition at line 67 of file px4_app.h.
Referenced by isRunning(), and setRunning().
The documentation for this class was generated from the following file:
src/platforms/px4_app.h