PX4 Firmware: VersioningTest Class Reference
VersioningTest Class Reference
Public Member Functions
virtual bool run_tests ()
Override to run your unit tests.
Public Member Functions inherited from UnitTest
UnitTest ()=default
virtual ~UnitTest ()=default
void print_results ()
Prints results from running of unit tests.
Private Member Functions
bool _test_tag_to_version_number (const char *version_tag, uint32_t flight_version_target, uint32_t vendor_version_target)
Additional Inherited Members
Protected Member Functions inherited from UnitTest
virtual void _init (void)
Run before each unit test. Override to provide custom behavior.
virtual void _cleanup (void)
Run after each unit test. Override to provide custom behavior.
void _print_assert (const char *msg, const char *test, const char *file, int line)
void _print_compare (const char *msg, const char *v1_text, int v1, const char *v2_text, int v2, const char *file, int line)
Protected Attributes inherited from UnitTest
int _tests_run {0}
The number of individual unit tests run.
int _tests_failed {0}
The number of unit tests which failed.
int _tests_passed {0}
The number of unit tests which passed.
int _assertions {0}
Total number of assertions tested by all unit tests.
Detailed Description
Definition at line 42 of file test_versioning.cpp.
Member Function Documentation
_test_tag_to_version_number()
bool VersioningTest::_test_tag_to_version_number (const char * version_tag, uint32_t flight_version_target, uint32_t vendor_version_target) private
Definition at line 52 of file test_versioning.cpp.
References version_tag_to_number(), and version_tag_to_vendor_version_number().
Referenced by run_tests().
run_tests()
bool VersioningTest::run_tests () virtual
Override to run your unit tests.
Unit tests should be called using ut_run_test macro.
Returns
true: all unit tests succeeded, false: one or more unit tests failed
Implements UnitTest.
Definition at line 75 of file test_versioning.cpp.
References _test_tag_to_version_number(), UnitTest::_tests_failed, test_versioning(), ut_assert_true, and ut_declare_test_c().
The documentation for this class was generated from the following file:
src/systemcmds/tests/test_versioning.cpp