PX4 Firmware: mb12xx Namespace Reference
mb12xx Namespace Reference
Local functions in support of the shell command.
Functions
int start (uint8_t rotation)
Attempt to start driver on all available I2C busses.
int start_bus (uint8_t rotation, int i2c_bus)
Start the driver on a specific bus.
int stop ()
Stop the driver.
int test ()
Perform some basic functional tests on the driver; make sure we can collect data from the sensor in polled and automatic modes.
int reset ()
Reset the driver.
int info ()
Print a little info about the driver.
Variables
MB12XX * g_dev
Detailed Description
Local functions in support of the shell command.
Function Documentation
int mb12xx::info ()
Print a little info about the driver.
Print a little info about the driver.
Definition at line 894 of file mb12xx.cpp.
References MB12XX::print_info(), PX4_ERR, PX4_ERROR, and PX4_OK.
Referenced by mb12xx_main().
int mb12xx::reset ()
Reset the driver.
Reset the driver.
Definition at line 867 of file mb12xx.cpp.
References fd, MB12XX::ioctl(), MB12XX_DEVICE_PATH, px4_close(), PX4_ERR, PX4_ERROR, PX4_OK, px4_open(), SENSOR_POLLRATE_DEFAULT, SENSORIOCRESET, and SENSORIOCSPOLLRATE.
Referenced by mb12xx_main().
int mb12xx::start (uint8_t rotation)
Attempt to start driver on all available I2C busses.
This function will return as soon as the first sensor is detected on one of the available busses or if no sensors are detected.
Definition at line 704 of file mb12xx.cpp.
References i2c_bus_options, PX4_ERR, PX4_ERROR, PX4_OK, and start_bus().
Referenced by mb12xx_main().
int mb12xx::start_bus (uint8_t rotation, int i2c_bus)
Start the driver on a specific bus.
This function only returns if the sensor is up and running or could not be detected successfully.
Definition at line 727 of file mb12xx.cpp.
References fd, g_dev, MB12XX::init(), MB12XX::ioctl(), MB12XX::MB12XX(), MB12XX_DEVICE_PATH, OK, px4_close(), PX4_ERR, PX4_ERROR, PX4_OK, px4_open(), SENSOR_POLLRATE_DEFAULT, and SENSORIOCSPOLLRATE.
Referenced by mb12xx_main(), and start().
int mb12xx::stop ()
Stop the driver.
Stop the driver.
Definition at line 779 of file mb12xx.cpp.
References g_dev, PX4_ERR, PX4_ERROR, and PX4_OK.
Referenced by mb12xx_main().
int mb12xx::test ()
Perform some basic functional tests on the driver; make sure we can collect data from the sensor in polled and automatic modes.
Definition at line 799 of file mb12xx.cpp.
References fd, MB12XX::ioctl(), MB12XX_DEVICE_PATH, OK, PX4_ERR, PX4_ERROR, PX4_INFO, PX4_OK, px4_open(), MB12XX::read(), SENSOR_POLLRATE_DEFAULT, and SENSORIOCSPOLLRATE.
Referenced by mb12xx_main().
Variable Documentation
MB12XX* mb12xx::g_dev
Definition at line 685 of file mb12xx.cpp.
Referenced by start_bus(), and stop().