PX4 Firmware: bmi055 Namespace Reference
bmi055 Namespace Reference
Functions
void start (bool external_bus, enum Rotation rotation, enum sensor_type sensor)
Start the driver.
void stop (bool, enum sensor_type)
void test (bool external_bus, enum sensor_type sensor)
Perform some basic functional tests on the driver; make sure we can collect data from the sensor in polled and automatic modes.
void reset (bool external_bus, enum sensor_type sensor)
Reset the driver.
void info (bool external_bus, enum sensor_type sensor)
Print a little info about the driver.
void regdump (bool external_bus, enum sensor_type sensor)
Dump the register information.
void testerror (bool external_bus, enum sensor_type sensor)
deliberately produce an error to test recovery
void usage ()
Prints info about the driver argument usage.
Variables
BMI055_accel * g_acc_dev_int
BMI055_accel * g_acc_dev_ext
BMI055_gyro * g_gyr_dev_int
BMI055_gyro * g_gyr_dev_ext
Function Documentation
void bmi055::info (bool external_bus, enum sensor_type sensor)
Print a little info about the driver.
Definition at line 357 of file bmi055_main.cpp.
References BMI055_ACCEL, BMI055_GYRO, errx, g_acc_dev_int, and g_gyr_dev_int.
Referenced by bmi055_main().
void bmi055::regdump (bool external_bus, enum sensor_type sensor)
Dump the register information.
Definition at line 387 of file bmi055_main.cpp.
References BMI055_ACCEL, BMI055_GYRO, errx, g_acc_dev_int, and g_gyr_dev_int.
Referenced by bmi055_main().
void bmi055::reset (bool external_bus, enum sensor_type sensor)
Reset the driver.
Definition at line 308 of file bmi055_main.cpp.
References BMI055_ACCEL, BMI055_DEVICE_PATH_ACCEL, BMI055_DEVICE_PATH_ACCEL_EXT, BMI055_DEVICE_PATH_GYRO, BMI055_DEVICE_PATH_GYRO_EXT, BMI055_GYRO, err, SENSOR_POLLRATE_DEFAULT, SENSORIOCRESET, and SENSORIOCSPOLLRATE.
Referenced by bmi055_main(), and test().
void bmi055::start (bool external_bus, enum Rotation rotation, enum sensor_type sensor)
Start the driver.
This function only returns if the driver is up and running or failed to detect the sensor.
Definition at line 73 of file bmi055_main.cpp.
References BMI055_ACCEL, BMI055_DEVICE_PATH_ACCEL, BMI055_DEVICE_PATH_ACCEL_EXT, BMI055_DEVICE_PATH_GYRO, BMI055_DEVICE_PATH_GYRO_EXT, BMI055_GYRO, errx, g_acc_dev_int, g_gyr_dev_int, OK, PX4_ERROR, PX4_OK, PX4_SPI_BUS_EXT, PX4_SPI_BUS_SENSORS, PX4_SPIDEV_BMI055_ACC, PX4_SPIDEV_BMI055_GYR, PX4_SPIDEV_EXT_BMI, PX4_WARN, SENSOR_POLLRATE_DEFAULT, and SENSORIOCSPOLLRATE.
Referenced by bmi055_main().
void bmi055::stop (bool external_bus, enum sensor_type sensor)
Definition at line 187 of file bmi055_main.cpp.
References BMI055_ACCEL, BMI055_GYRO, g_acc_dev_int, g_gyr_dev_int, and warnx.
Referenced by bmi055_main().
void bmi055::test (bool external_bus, enum sensor_type sensor)
Perform some basic functional tests on the driver; make sure we can collect data from the sensor in polled and automatic modes.
Definition at line 224 of file bmi055_main.cpp.
References accel_report, BMI055_ACCEL, BMI055_DEVICE_PATH_ACCEL, BMI055_DEVICE_PATH_ACCEL_EXT, BMI055_DEVICE_PATH_GYRO, BMI055_DEVICE_PATH_GYRO_EXT, BMI055_GYRO, err, errx, gyro_report, read(), reset(), SENSOR_POLLRATE_DEFAULT, SENSOR_POLLRATE_MANUAL, SENSORIOCSPOLLRATE, and warnx.
Referenced by bmi055_main().
void bmi055::testerror (bool external_bus, enum sensor_type sensor)
deliberately produce an error to test recovery
Definition at line 417 of file bmi055_main.cpp.
References BMI055_ACCEL, BMI055_GYRO, errx, g_acc_dev_int, and g_gyr_dev_int.
Referenced by bmi055_main().
void bmi055::usage (void)
Prints info about the driver argument usage.
Prints info about the driver argument usage.
Definition at line 442 of file bmi055_main.cpp.
References warnx.
Referenced by bmi055_main().
Variable Documentation
BMI055_accel* bmi055::g_acc_dev_ext
Definition at line 53 of file bmi055_main.cpp.
BMI055_accel* bmi055::g_acc_dev_int
Definition at line 52 of file bmi055_main.cpp.
Referenced by info(), regdump(), start(), stop(), and testerror().
BMI055_gyro* bmi055::g_gyr_dev_ext
Definition at line 55 of file bmi055_main.cpp.
BMI055_gyro* bmi055::g_gyr_dev_int
Definition at line 54 of file bmi055_main.cpp.
Referenced by info(), regdump(), start(), stop(), and testerror().