PX4 Firmware: BMI055 Class Reference
BMI055 Class Reference
#include <BMI055.hpp>
Public Member Functions
BMI055 (const char *name, const char *devname, int bus, uint32_t device, enum spi_mode_e mode, uint32_t frequency, enum Rotation rotation)
virtual ~BMI055 ()=default
Protected Member Functions
uint8_t read_reg (unsigned reg)
Read a register from the BMI055.
uint16_t read_reg16 (unsigned reg)
void write_reg (unsigned reg, uint8_t value)
Write a register in the BMI055.
BMI055 (const BMI055 &)
BMI055 operator= (const BMI055 &)
Protected Attributes
uint8_t _whoami
struct hrt_call _call
whoami result
unsigned _call_interval
unsigned _dlpf_freq
uint8_t _register_wait
uint64_t _reset_wait
enum Rotation _rotation
uint8_t _checked_next
Detailed Description
Definition at line 54 of file BMI055.hpp.
Constructor & Destructor Documentation
BMI055::BMI055 (const BMI055 &) protected
BMI055::BMI055 (const char * name, const char * devname, int bus, uint32_t device, enum spi_mode_e mode, uint32_t frequency, enum Rotation rotation)
Definition at line 455 of file bmi055_main.cpp.
References _call_interval, _checked_next, _dlpf_freq, _register_wait, _reset_wait, and _rotation.
virtual BMI055::~BMI055 () virtual default
Member Function Documentation
BMI055 BMI055::operator= (const BMI055 &) protected
uint8_t BMI055::read_reg (unsigned reg) protected
Read a register from the BMI055.
Parameters
The register to read.
Returns
The value that was read.
Definition at line 470 of file bmi055_main.cpp.
References DIR_READ.
Referenced by BMI055_gyro::check_registers(), BMI055_accel::check_registers(), BMI055_gyro::measure(), BMI055_accel::measure(), BMI055_gyro::modify_reg(), BMI055_accel::modify_reg(), BMI055_gyro::print_info(), BMI055_accel::print_info(), BMI055_gyro::print_registers(), BMI055_accel::print_registers(), BMI055_gyro::probe(), BMI055_accel::probe(), BMI055_gyro::reset(), and BMI055_accel::reset().
uint16_t BMI055::read_reg16 (unsigned reg) protected
Definition at line 480 of file bmi055_main.cpp.
References DIR_READ.
void BMI055::write_reg (unsigned reg, uint8_t value) protected
Write a register in the BMI055.
Parameters
reg The register to write.
value The new value to write.
Definition at line 490 of file bmi055_main.cpp.
References DIR_WRITE.
Referenced by BMI055_gyro::check_registers(), BMI055_accel::check_registers(), BMI055_gyro::reset(), BMI055_accel::reset(), BMI055_gyro::test_error(), BMI055_accel::test_error(), BMI055_gyro::write_checked_reg(), and BMI055_accel::write_checked_reg().
Member Data Documentation
struct hrt_call BMI055::_call protected
whoami result
Definition at line 61 of file BMI055.hpp.
Referenced by BMI055_accel::BMI055_accel(), BMI055_gyro::BMI055_gyro(), BMI055_gyro::ioctl(), BMI055_accel::ioctl(), BMI055_gyro::start(), BMI055_accel::start(), BMI055_gyro::stop(), and BMI055_accel::stop().
unsigned BMI055::_call_interval protected
Definition at line 62 of file BMI055.hpp.
Referenced by BMI055(), BMI055_gyro::ioctl(), BMI055_accel::ioctl(), BMI055_gyro::read(), BMI055_accel::read(), BMI055_gyro::start(), and BMI055_accel::start().
uint8_t BMI055::_checked_next protected
Definition at line 71 of file BMI055.hpp.
Referenced by BMI055(), BMI055_gyro::check_registers(), BMI055_accel::check_registers(), BMI055_gyro::print_info(), and BMI055_accel::print_info().
unsigned BMI055::_dlpf_freq protected
Definition at line 64 of file BMI055.hpp.
Referenced by BMI055().
uint8_t BMI055::_register_wait protected
Definition at line 66 of file BMI055.hpp.
Referenced by BMI055(), BMI055_gyro::check_registers(), BMI055_accel::check_registers(), BMI055_gyro::measure(), and BMI055_accel::measure().
uint64_t BMI055::_reset_wait protected
Definition at line 67 of file BMI055.hpp.
Referenced by BMI055(), BMI055_gyro::check_registers(), BMI055_accel::check_registers(), BMI055_gyro::measure(), and BMI055_accel::measure().
enum Rotation BMI055::_rotation protected
Definition at line 69 of file BMI055.hpp.
Referenced by BMI055(), BMI055_gyro::measure(), and BMI055_accel::measure().
uint8_t BMI055::_whoami protected
Definition at line 59 of file BMI055.hpp.
Referenced by BMI055_gyro::probe(), and BMI055_accel::probe().
The documentation for this class was generated from the following files:
src/drivers/imu/bmi055/BMI055.hpp
src/drivers/imu/bmi055/bmi055_main.cpp