PX4 Firmware: MavlinkStreamWind Class Reference
MavlinkStreamWind Class Reference
Public Member Functions
const char * get_name () const override
uint16_t get_id () override
unsigned get_size () override
Get maximal total messages size on update.
Public Member Functions inherited from MavlinkStream
MavlinkStream (Mavlink *mavlink)
virtual ~MavlinkStream ()=default
MavlinkStream (const MavlinkStream &)=delete
MavlinkStream & operator= (const MavlinkStream &)=delete
MavlinkStream (MavlinkStream &&)=delete
MavlinkStream & operator= (MavlinkStream &&)=delete
void set_interval (const int interval)
Get the interval.
int get_interval ()
Get the interval.
int update (const hrt_abstime &t)
Update subscriptions and send message if necessary.
virtual bool const_rate ()
virtual unsigned get_size_avg ()
Get the average message size.
bool first_message_sent () const
void reset_last_sent ()
Reset the time of last sent to 0.
Public Member Functions inherited from ListNode< MavlinkStream *>
void setSibling (MavlinkStream * sibling)
const MavlinkStream * getSibling () const
Static Public Member Functions
static const char * get_name_static ()
static uint16_t get_id_static ()
static MavlinkStream * new_instance (Mavlink *mavlink)
Protected Member Functions
MavlinkStreamWind (Mavlink *mavlink)
bool send (const hrt_abstime t) override
Protected Member Functions inherited from MavlinkStream
virtual void update_data ()
Function to collect/update data for the streams at a high rate independant of actual stream rate.
Private Member Functions
MavlinkStreamWind (MavlinkStreamWind &)=delete
MavlinkStreamWind & operator= (const MavlinkStreamWind &)=delete
Private Attributes
MavlinkOrbSubscription * _wind_estimate_sub
uint64_t _wind_estimate_time
MavlinkOrbSubscription * _local_pos_sub
Additional Inherited Members
Protected Attributes inherited from MavlinkStream
Mavlink *const _mavlink
int _interval {1000000}
if set to negative value = unlimited rate
Protected Attributes inherited from ListNode< MavlinkStream *>
MavlinkStream * _list_node_sibling
Detailed Description
Definition at line 4607 of file mavlink_messages.cpp.
Constructor & Destructor Documentation
MavlinkStreamWind() [1/2]
MavlinkStreamWind::MavlinkStreamWind (MavlinkStreamWind &) private delete
MavlinkStreamWind() [2/2]
MavlinkStreamWind::MavlinkStreamWind (Mavlink * mavlink) inline explicit protected
Definition at line 4651 of file mavlink_messages.cpp.
Member Function Documentation
get_id()
uint16_t MavlinkStreamWind::get_id () inline override virtual
Implements MavlinkStream.
Definition at line 4625 of file mavlink_messages.cpp.
References MavlinkStreamHeartbeat::get_id_static().
get_id_static()
static uint16_t MavlinkStreamWind::get_id_static () inline static
Definition at line 4620 of file mavlink_messages.cpp.
get_name()
const char* MavlinkStreamWind::get_name () const inline override virtual
Implements MavlinkStream.
Definition at line 4610 of file mavlink_messages.cpp.
References get_name_static().
get_name_static()
static const char* MavlinkStreamWind::get_name_static () inline static
Definition at line 4615 of file mavlink_messages.cpp.
Referenced by get_name().
get_size()
unsigned MavlinkStreamWind::get_size () inline override virtual
Get maximal total messages size on update.
Implements MavlinkStream.
Definition at line 4635 of file mavlink_messages.cpp.
new_instance()
static MavlinkStream* MavlinkStreamWind::new_instance (Mavlink * mavlink) inline static
Definition at line 4630 of file mavlink_messages.cpp.
operator=()
MavlinkStreamWind& MavlinkStreamWind::operator= (const MavlinkStreamWind &) private delete
send()
bool MavlinkStreamWind::send (const hrt_abstime t) inline override protected virtual
Implements MavlinkStream.
Definition at line 4657 of file mavlink_messages.cpp.
References MavlinkStream::_mavlink, Mavlink::get_channel(), msg, vehicle_local_position_s::ref_alt, wind_estimate_s::timestamp, MavlinkOrbSubscription::update(), wind_estimate_s::variance_east, wind_estimate_s::variance_north, wind_estimate_s::windspeed_east, wind_estimate_s::windspeed_north, vehicle_local_position_s::z, vehicle_local_position_s::z_global, and vehicle_local_position_s::z_valid.
Member Data Documentation
_local_pos_sub
MavlinkOrbSubscription* MavlinkStreamWind::_local_pos_sub private
Definition at line 4644 of file mavlink_messages.cpp.
_wind_estimate_sub
MavlinkOrbSubscription* MavlinkStreamWind::_wind_estimate_sub private
Definition at line 4641 of file mavlink_messages.cpp.
_wind_estimate_time
uint64_t MavlinkStreamWind::_wind_estimate_time private
Definition at line 4642 of file mavlink_messages.cpp.
The documentation for this class was generated from the following file:
src/modules/mavlink/mavlink_messages.cpp