PX4 Firmware: VtolAttitudeControl Class Reference
VtolAttitudeControl Class Reference
#include <vtol_att_control_main.h>
Public Member Functions
VtolAttitudeControl ()
~VtolAttitudeControl ()
void Run () override
bool init ()
int print_status () override
bool is_fixed_wing_requested ()
void abort_front_transition (const char *reason)
struct actuator_controls_s * get_actuators_fw_in ()
struct actuator_controls_s * get_actuators_mc_in ()
struct actuator_controls_s * get_actuators_out0 ()
struct actuator_controls_s * get_actuators_out1 ()
struct airspeed_validated_s * get_airspeed ()
struct position_setpoint_triplet_s * get_pos_sp_triplet ()
struct tecs_status_s * get_tecs_status ()
struct vehicle_attitude_s * get_att ()
struct vehicle_attitude_setpoint_s * get_att_sp ()
struct vehicle_attitude_setpoint_s * get_fw_virtual_att_sp ()
struct vehicle_attitude_setpoint_s * get_mc_virtual_att_sp ()
struct vehicle_control_mode_s * get_control_mode ()
struct vehicle_land_detected_s * get_land_detected ()
struct vehicle_local_position_s * get_local_pos ()
struct vehicle_local_position_setpoint_s * get_local_pos_sp ()
struct vtol_vehicle_status_s * get_vtol_vehicle_status ()
struct Params * get_params ()
Static Public Member Functions
static int task_spawn (int argc, char *argv[])
static int custom_command (int argc, char *argv[])
static int print_usage (const char *reason=nullptr)
Private Member Functions
void vehicle_cmd_poll ()
Check for command updates.
int parameters_update ()
void handle_command ()
Check received command.
Private Attributes
uORB::SubscriptionCallbackWorkItem _actuator_inputs_fw {this, ORB_ID(actuator_controls_virtual_fw)}
uORB::SubscriptionCallbackWorkItem _actuator_inputs_mc {this, ORB_ID(actuator_controls_virtual_mc)}
uORB::Subscription _airspeed_validated_sub {ORB_ID(airspeed_validated)}
uORB::Subscription _fw_virtual_att_sp_sub {ORB_ID(fw_virtual_attitude_setpoint)}
uORB::Subscription _land_detected_sub {ORB_ID(vehicle_land_detected)}
uORB::Subscription _local_pos_sp_sub {ORB_ID(vehicle_local_position_setpoint)}
uORB::Subscription _local_pos_sub {ORB_ID(vehicle_local_position)}
uORB::Subscription _manual_control_sp_sub {ORB_ID(manual_control_setpoint)}
uORB::Subscription _mc_virtual_att_sp_sub {ORB_ID(mc_virtual_attitude_setpoint)}
uORB::Subscription _parameter_update_sub {ORB_ID(parameter_update)}
uORB::Subscription _pos_sp_triplet_sub {ORB_ID(position_setpoint_triplet)}
uORB::Subscription _tecs_status_sub {ORB_ID(tecs_status)}
uORB::Subscription _v_att_sub {ORB_ID(vehicle_attitude)}
uORB::Subscription _v_control_mode_sub {ORB_ID(vehicle_control_mode)}
uORB::Subscription _vehicle_cmd_sub {ORB_ID(vehicle_command)}
uORB::Publication< actuator_controls_s > _actuators_0_pub {ORB_ID(actuator_controls_0)}
uORB::Publication< actuator_controls_s > _actuators_1_pub {ORB_ID(actuator_controls_1)}
uORB::Publication< vehicle_attitude_setpoint_s > _v_att_sp_pub {ORB_ID(vehicle_attitude_setpoint)}
uORB::Publication< vtol_vehicle_status_s > _vtol_vehicle_status_pub {ORB_ID(vtol_vehicle_status)}
orb_advert_t _mavlink_log_pub {nullptr}
vehicle_attitude_setpoint_s _v_att_sp {}
vehicle_attitude_setpoint_s _fw_virtual_att_sp {}
vehicle_attitude_setpoint_s _mc_virtual_att_sp {}
actuator_controls_s _actuators_fw_in {}
actuator_controls_s _actuators_mc_in {}
actuator_controls_s _actuators_out_0 {}
actuator_controls_s _actuators_out_1 {}
airspeed_validated_s _airspeed_validated {}
manual_control_setpoint_s _manual_control_sp {}
position_setpoint_triplet_s _pos_sp_triplet {}
tecs_status_s _tecs_status {}
vehicle_attitude_s _v_att {}
vehicle_command_s _vehicle_cmd {}
vehicle_control_mode_s _v_control_mode {}
vehicle_land_detected_s _land_detected {}
vehicle_local_position_s _local_pos {}
vehicle_local_position_setpoint_s _local_pos_sp {}
vtol_vehicle_status_s _vtol_vehicle_status {}
Params _params {}
struct {
param_t idle_pwm_mc
param_t vtol_motor_id
param_t vtol_fw_permanent_stab
param_t vtol_type
param_t elevons_mc_lock
param_t fw_min_alt
param_t fw_alt_err
param_t fw_qc_max_pitch
param_t fw_qc_max_roll
param_t front_trans_time_openloop
param_t front_trans_time_min
param_t front_trans_duration
param_t back_trans_duration
param_t transition_airspeed
param_t front_trans_throttle
param_t back_trans_throttle
param_t airspeed_blend
param_t airspeed_mode
param_t front_trans_timeout
param_t mpc_xy_cruise
param_t fw_motors_off
param_t diff_thrust
param_t diff_thrust_scale
} _params_handles
int _transition_command {vtol_vehicle_status_s::VEHICLE_VTOL_STATE_MC}
bool _abort_front_transition {false}
VtolType * _vtol_type {nullptr}
bool _initialized {false}
perf_counter_t _loop_perf
loop performance counter
Detailed Description
Definition at line 89 of file vtol_att_control_main.h.
Constructor & Destructor Documentation
VtolAttitudeControl()
VtolAttitudeControl::VtolAttitudeControl ()
Definition at line 55 of file vtol_att_control_main.cpp.
References _params, _params_handles, _vtol_type, _vtol_vehicle_status, Params::idle_pwm_mc, param_find(), parameters_update(), PWM_DEFAULT_MIN, STANDARD, TAILSITTER, TILTROTOR, vtol_vehicle_status_s::vtol_in_rw_mode, Params::vtol_motor_id, and Params::vtol_type.
Referenced by task_spawn().
~VtolAttitudeControl()
VtolAttitudeControl::~VtolAttitudeControl ()
Definition at line 106 of file vtol_att_control_main.cpp.
References _loop_perf, and perf_free().
Member Function Documentation
abort_front_transition()
void VtolAttitudeControl::abort_front_transition (const char * reason)
Definition at line 200 of file vtol_att_control_main.cpp.
References _abort_front_transition, _mavlink_log_pub, _vtol_vehicle_status, mavlink_log_critical, and vtol_vehicle_status_s::vtol_transition_failsafe.
Referenced by VtolType::check_quadchute_condition(), and Standard::update_transition_state().
custom_command()
int VtolAttitudeControl::custom_command (int argc, char * argv[]) static
See also
ModuleBase
Definition at line 460 of file vtol_att_control_main.cpp.
References print_usage().
get_actuators_fw_in()
struct actuator_controls_s* VtolAttitudeControl::get_actuators_fw_in () inline
Definition at line 115 of file vtol_att_control_main.h.
References _actuators_fw_in.
Referenced by VtolType::VtolType().
get_actuators_mc_in()
struct actuator_controls_s* VtolAttitudeControl::get_actuators_mc_in () inline
Definition at line 116 of file vtol_att_control_main.h.
References _actuators_mc_in.
Referenced by VtolType::VtolType().
get_actuators_out0()
struct actuator_controls_s* VtolAttitudeControl::get_actuators_out0 () inline
Definition at line 117 of file vtol_att_control_main.h.
References _actuators_out_0.
Referenced by VtolType::VtolType().
get_actuators_out1()
struct actuator_controls_s* VtolAttitudeControl::get_actuators_out1 () inline
Definition at line 118 of file vtol_att_control_main.h.
References _actuators_out_1.
Referenced by VtolType::VtolType().
get_airspeed()
struct airspeed_validated_s* VtolAttitudeControl::get_airspeed () inline
Definition at line 119 of file vtol_att_control_main.h.
References _airspeed_validated.
Referenced by VtolType::VtolType().
get_att()
struct vehicle_attitude_s* VtolAttitudeControl::get_att () inline
Definition at line 122 of file vtol_att_control_main.h.
References _v_att.
Referenced by VtolType::VtolType().
get_att_sp()
struct vehicle_attitude_setpoint_s* VtolAttitudeControl::get_att_sp () inline
Definition at line 123 of file vtol_att_control_main.h.
References _v_att_sp.
Referenced by VtolType::VtolType().
get_control_mode()
struct vehicle_control_mode_s* VtolAttitudeControl::get_control_mode () inline
Definition at line 126 of file vtol_att_control_main.h.
References _v_control_mode.
Referenced by VtolType::VtolType().
get_fw_virtual_att_sp()
struct vehicle_attitude_setpoint_s* VtolAttitudeControl::get_fw_virtual_att_sp () inline
Definition at line 124 of file vtol_att_control_main.h.
References _fw_virtual_att_sp.
Referenced by VtolType::VtolType().
get_land_detected()
struct vehicle_land_detected_s* VtolAttitudeControl::get_land_detected () inline
Definition at line 127 of file vtol_att_control_main.h.
References _land_detected.
Referenced by VtolType::VtolType().
get_local_pos()
struct vehicle_local_position_s* VtolAttitudeControl::get_local_pos () inline
Definition at line 128 of file vtol_att_control_main.h.
References _local_pos.
Referenced by VtolType::VtolType().
get_local_pos_sp()
struct vehicle_local_position_setpoint_s* VtolAttitudeControl::get_local_pos_sp () inline
Definition at line 129 of file vtol_att_control_main.h.
References _local_pos_sp.
Referenced by VtolType::VtolType().
get_mc_virtual_att_sp()
struct vehicle_attitude_setpoint_s* VtolAttitudeControl::get_mc_virtual_att_sp () inline
Definition at line 125 of file vtol_att_control_main.h.
References _mc_virtual_att_sp.
Referenced by VtolType::VtolType().
get_params()
struct Params* VtolAttitudeControl::get_params () inline
Definition at line 132 of file vtol_att_control_main.h.
References _params.
Referenced by VtolType::VtolType().
get_pos_sp_triplet()
struct position_setpoint_triplet_s* VtolAttitudeControl::get_pos_sp_triplet () inline
Definition at line 120 of file vtol_att_control_main.h.
References _pos_sp_triplet.
Referenced by Standard::update_mc_state().
get_tecs_status()
struct tecs_status_s* VtolAttitudeControl::get_tecs_status () inline
Definition at line 121 of file vtol_att_control_main.h.
References _tecs_status.
Referenced by VtolType::VtolType().
get_vtol_vehicle_status()
struct vtol_vehicle_status_s* VtolAttitudeControl::get_vtol_vehicle_status () inline
Definition at line 130 of file vtol_att_control_main.h.
References _vtol_vehicle_status.
Referenced by Standard::update_mc_state(), and VtolType::VtolType().
handle_command()
void VtolAttitudeControl::handle_command () private
Check received command.
Definition at line 143 of file vtol_att_control_main.cpp.
References _transition_command, _vehicle_cmd, vehicle_command_s::command, vehicle_command_s::from_external, hrt_absolute_time(), ORB_ID, vehicle_command_s::param1, vehicle_command_s::source_component, vehicle_command_s::source_system, and vehicle_command_ack_s::timestamp.
Referenced by vehicle_cmd_poll().
init()
bool VtolAttitudeControl::init ()
Definition at line 112 of file vtol_att_control_main.cpp.
References _actuator_inputs_fw, _actuator_inputs_mc, and uORB::SubscriptionCallback::registerCallback().
Referenced by task_spawn().
is_fixed_wing_requested()
bool VtolAttitudeControl::is_fixed_wing_requested ()
Definition at line 171 of file vtol_att_control_main.cpp.
References _abort_front_transition, _manual_control_sp, _transition_command, _v_control_mode, _vtol_vehicle_status, vehicle_control_mode_s::flag_control_manual_enabled, manual_control_setpoint_s::transition_switch, and vtol_vehicle_status_s::vtol_transition_failsafe.
Referenced by Tiltrotor::update_vtol_state(), Tailsitter::update_vtol_state(), and Standard::update_vtol_state().
parameters_update()
int VtolAttitudeControl::parameters_update () private
Definition at line 210 of file vtol_att_control_main.cpp.
References _params, _params_handles, _vtol_type, _vtol_vehicle_status, Params::airspeed_blend, Params::airspeed_disabled, Params::back_trans_duration, Params::back_trans_throttle, math::constrain(), Params::diff_thrust, Params::diff_thrust_scale, Params::elevons_mc_lock, f(), Params::front_trans_duration, Params::front_trans_throttle, Params::front_trans_time_min, Params::front_trans_time_openloop, Params::front_trans_timeout, Params::fw_alt_err, Params::fw_min_alt, Params::fw_motors_off, vtol_vehicle_status_s::fw_permanent_stab, Params::fw_qc_max_pitch, Params::fw_qc_max_roll, Params::idle_pwm_mc, math::min(), Params::mpc_xy_cruise, OK, param_get(), VtolType::parameters_update(), Params::transition_airspeed, Params::vtol_motor_id, and Params::vtol_type.
Referenced by Run(), and VtolAttitudeControl().
print_status()
int VtolAttitudeControl::print_status () override
See also
ModuleBase::print_status()
Definition at line 466 of file vtol_att_control_main.cpp.
References _loop_perf, and perf_print_counter().
print_usage()
int VtolAttitudeControl::print_usage (const char * reason = nullptr) static
See also
ModuleBase
Definition at line 474 of file vtol_att_control_main.cpp.
Referenced by custom_command().
Run()
void VtolAttitudeControl::Run () override
Definition at line 287 of file vtol_att_control_main.cpp.
References _actuator_inputs_fw, _actuator_inputs_mc, _actuators_0_pub, _actuators_1_pub, _actuators_fw_in, _actuators_mc_in, _actuators_out_0, _actuators_out_1, _airspeed_validated, _airspeed_validated_sub, _fw_virtual_att_sp, _fw_virtual_att_sp_sub, _initialized, _land_detected, _land_detected_sub, _local_pos, _local_pos_sp, _local_pos_sp_sub, _local_pos_sub, _loop_perf, _manual_control_sp, _manual_control_sp_sub, _mc_virtual_att_sp, _mc_virtual_att_sp_sub, _parameter_update_sub, _pos_sp_triplet, _pos_sp_triplet_sub, _tecs_status, _tecs_status_sub, _transition_command, _v_att, _v_att_sp, _v_att_sp_pub, _v_att_sub, _v_control_mode, _v_control_mode_sub, _vtol_type, _vtol_vehicle_status, _vtol_vehicle_status_pub, uORB::Subscription::copy(), VtolType::fill_actuator_outputs(), FIXED_WING, vehicle_control_mode_s::flag_control_manual_enabled, VtolType::get_mode(), hrt_absolute_time(), vtol_vehicle_status_s::in_transition_to_fw, VtolType::init(), parameters_update(), perf_begin(), perf_end(), uORB::Publication< T >::publish(), ROTARY_WING, vtol_vehicle_status_s::timestamp, TRANSITION_TO_FW, TRANSITION_TO_MC, uORB::SubscriptionCallback::unregisterCallback(), uORB::SubscriptionInterval::update(), uORB::Subscription::update(), VtolType::update_fw_state(), VtolType::update_mc_state(), VtolType::update_transition_state(), VtolType::update_vtol_state(), uORB::Subscription::updated(), vehicle_cmd_poll(), vtol_vehicle_status_s::vtol_in_rw_mode, and vtol_vehicle_status_s::vtol_in_trans_mode.
task_spawn()
int VtolAttitudeControl::task_spawn (int argc, char * argv[]) static
See also
ModuleBase
Definition at line 436 of file vtol_att_control_main.cpp.
References init(), ll40ls::instance, and VtolAttitudeControl().
vehicle_cmd_poll()
void VtolAttitudeControl::vehicle_cmd_poll () private
Check for command updates.
Definition at line 131 of file vtol_att_control_main.cpp.
References _vehicle_cmd, _vehicle_cmd_sub, uORB::Subscription::copy(), handle_command(), and uORB::Subscription::updated().
Referenced by Run().
Member Data Documentation
_abort_front_transition
bool VtolAttitudeControl::_abort_front_transition {false} private
Definition at line 213 of file vtol_att_control_main.h.
Referenced by abort_front_transition(), and is_fixed_wing_requested().
_actuator_inputs_fw
uORB::SubscriptionCallbackWorkItem VtolAttitudeControl::_actuator_inputs_fw {this, ORB_ID(actuator_controls_virtual_fw)} private
Definition at line 136 of file vtol_att_control_main.h.
Referenced by init(), and Run().
_actuator_inputs_mc
uORB::SubscriptionCallbackWorkItem VtolAttitudeControl::_actuator_inputs_mc {this, ORB_ID(actuator_controls_virtual_mc)} private
Definition at line 137 of file vtol_att_control_main.h.
Referenced by init(), and Run().
_actuators_0_pub
uORB::Publication<actuator_controls_s> VtolAttitudeControl::_actuators_0_pub {ORB_ID(actuator_controls_0)} private
Definition at line 153 of file vtol_att_control_main.h.
Referenced by Run().
_actuators_1_pub
uORB::Publication<actuator_controls_s> VtolAttitudeControl::_actuators_1_pub {ORB_ID(actuator_controls_1)} private
Definition at line 154 of file vtol_att_control_main.h.
Referenced by Run().
_actuators_fw_in
actuator_controls_s VtolAttitudeControl::_actuators_fw_in {} private
Definition at line 164 of file vtol_att_control_main.h.
Referenced by get_actuators_fw_in(), and Run().
_actuators_mc_in
actuator_controls_s VtolAttitudeControl::_actuators_mc_in {} private
Definition at line 165 of file vtol_att_control_main.h.
Referenced by get_actuators_mc_in(), and Run().
_actuators_out_0
actuator_controls_s VtolAttitudeControl::_actuators_out_0 {} private
Definition at line 166 of file vtol_att_control_main.h.
Referenced by get_actuators_out0(), and Run().
_actuators_out_1
actuator_controls_s VtolAttitudeControl::_actuators_out_1 {} private
Definition at line 167 of file vtol_att_control_main.h.
Referenced by get_actuators_out1(), and Run().
_airspeed_validated
airspeed_validated_s VtolAttitudeControl::_airspeed_validated {} private
Definition at line 169 of file vtol_att_control_main.h.
Referenced by get_airspeed(), and Run().
_airspeed_validated_sub
uORB::Subscription VtolAttitudeControl::_airspeed_validated_sub {ORB_ID(airspeed_validated)} private
Definition at line 139 of file vtol_att_control_main.h.
Referenced by Run().
_fw_virtual_att_sp
vehicle_attitude_setpoint_s VtolAttitudeControl::_fw_virtual_att_sp {} private
Definition at line 161 of file vtol_att_control_main.h.
Referenced by get_fw_virtual_att_sp(), and Run().
_fw_virtual_att_sp_sub
uORB::Subscription VtolAttitudeControl::_fw_virtual_att_sp_sub {ORB_ID(fw_virtual_attitude_setpoint)} private
Definition at line 140 of file vtol_att_control_main.h.
Referenced by Run().
_initialized
bool VtolAttitudeControl::_initialized {false} private
Definition at line 217 of file vtol_att_control_main.h.
Referenced by Run().
_land_detected
vehicle_land_detected_s VtolAttitudeControl::_land_detected {} private
Definition at line 176 of file vtol_att_control_main.h.
Referenced by get_land_detected(), and Run().
_land_detected_sub
uORB::Subscription VtolAttitudeControl::_land_detected_sub {ORB_ID(vehicle_land_detected)} private
Definition at line 141 of file vtol_att_control_main.h.
Referenced by Run().
_local_pos
vehicle_local_position_s VtolAttitudeControl::_local_pos {} private
Definition at line 177 of file vtol_att_control_main.h.
Referenced by get_local_pos(), and Run().
_local_pos_sp
vehicle_local_position_setpoint_s VtolAttitudeControl::_local_pos_sp {} private
Definition at line 178 of file vtol_att_control_main.h.
Referenced by get_local_pos_sp(), and Run().
_local_pos_sp_sub
uORB::Subscription VtolAttitudeControl::_local_pos_sp_sub {ORB_ID(vehicle_local_position_setpoint)} private
Definition at line 142 of file vtol_att_control_main.h.
Referenced by Run().
_local_pos_sub
uORB::Subscription VtolAttitudeControl::_local_pos_sub {ORB_ID(vehicle_local_position)} private
Definition at line 143 of file vtol_att_control_main.h.
Referenced by Run().
_loop_perf
perf_counter_t VtolAttitudeControl::_loop_perf private
loop performance counter
Definition at line 219 of file vtol_att_control_main.h.
Referenced by print_status(), Run(), and ~VtolAttitudeControl().
_manual_control_sp
manual_control_setpoint_s VtolAttitudeControl::_manual_control_sp {} private
Definition at line 170 of file vtol_att_control_main.h.
Referenced by is_fixed_wing_requested(), and Run().
_manual_control_sp_sub
uORB::Subscription VtolAttitudeControl::_manual_control_sp_sub {ORB_ID(manual_control_setpoint)} private
Definition at line 144 of file vtol_att_control_main.h.
Referenced by Run().
_mavlink_log_pub
orb_advert_t VtolAttitudeControl::_mavlink_log_pub {nullptr} private
Definition at line 158 of file vtol_att_control_main.h.
Referenced by abort_front_transition().
_mc_virtual_att_sp
vehicle_attitude_setpoint_s VtolAttitudeControl::_mc_virtual_att_sp {} private
Definition at line 162 of file vtol_att_control_main.h.
Referenced by get_mc_virtual_att_sp(), and Run().
_mc_virtual_att_sp_sub
uORB::Subscription VtolAttitudeControl::_mc_virtual_att_sp_sub {ORB_ID(mc_virtual_attitude_setpoint)} private
Definition at line 145 of file vtol_att_control_main.h.
Referenced by Run().
_parameter_update_sub
uORB::Subscription VtolAttitudeControl::_parameter_update_sub {ORB_ID(parameter_update)} private
Definition at line 146 of file vtol_att_control_main.h.
Referenced by Run().
_params
Params VtolAttitudeControl::_params {} private
Definition at line 181 of file vtol_att_control_main.h.
Referenced by get_params(), parameters_update(), and VtolAttitudeControl().
_params_handles
struct { ... } VtolAttitudeControl::_params_handles
Referenced by parameters_update(), and VtolAttitudeControl().
_pos_sp_triplet
position_setpoint_triplet_s VtolAttitudeControl::_pos_sp_triplet {} private
Definition at line 171 of file vtol_att_control_main.h.
Referenced by get_pos_sp_triplet(), and Run().
_pos_sp_triplet_sub
uORB::Subscription VtolAttitudeControl::_pos_sp_triplet_sub {ORB_ID(position_setpoint_triplet)} private
Definition at line 147 of file vtol_att_control_main.h.
Referenced by Run().
_tecs_status
tecs_status_s VtolAttitudeControl::_tecs_status {} private
Definition at line 172 of file vtol_att_control_main.h.
Referenced by get_tecs_status(), and Run().
_tecs_status_sub
uORB::Subscription VtolAttitudeControl::_tecs_status_sub {ORB_ID(tecs_status)} private
Definition at line 148 of file vtol_att_control_main.h.
Referenced by Run().
_transition_command
int VtolAttitudeControl::_transition_command {vtol_vehicle_status_s::VEHICLE_VTOL_STATE_MC} private
Definition at line 212 of file vtol_att_control_main.h.
Referenced by handle_command(), is_fixed_wing_requested(), and Run().
_v_att
vehicle_attitude_s VtolAttitudeControl::_v_att {} private
Definition at line 173 of file vtol_att_control_main.h.
Referenced by get_att(), and Run().
_v_att_sp
vehicle_attitude_setpoint_s VtolAttitudeControl::_v_att_sp {} private
Definition at line 160 of file vtol_att_control_main.h.
Referenced by get_att_sp(), and Run().
_v_att_sp_pub
uORB::Publication<vehicle_attitude_setpoint_s> VtolAttitudeControl::_v_att_sp_pub {ORB_ID(vehicle_attitude_setpoint)} private
Definition at line 155 of file vtol_att_control_main.h.
Referenced by Run().
_v_att_sub
uORB::Subscription VtolAttitudeControl::_v_att_sub {ORB_ID(vehicle_attitude)} private
Definition at line 149 of file vtol_att_control_main.h.
Referenced by Run().
_v_control_mode
vehicle_control_mode_s VtolAttitudeControl::_v_control_mode {} private
Definition at line 175 of file vtol_att_control_main.h.
Referenced by get_control_mode(), is_fixed_wing_requested(), and Run().
_v_control_mode_sub
uORB::Subscription VtolAttitudeControl::_v_control_mode_sub {ORB_ID(vehicle_control_mode)} private
Definition at line 150 of file vtol_att_control_main.h.
Referenced by Run().
_vehicle_cmd
vehicle_command_s VtolAttitudeControl::_vehicle_cmd {} private
Definition at line 174 of file vtol_att_control_main.h.
Referenced by handle_command(), and vehicle_cmd_poll().
_vehicle_cmd_sub
uORB::Subscription VtolAttitudeControl::_vehicle_cmd_sub {ORB_ID(vehicle_command)} private
Definition at line 151 of file vtol_att_control_main.h.
Referenced by vehicle_cmd_poll().
_vtol_type
VtolType* VtolAttitudeControl::_vtol_type {nullptr} private
Definition at line 215 of file vtol_att_control_main.h.
Referenced by parameters_update(), Run(), and VtolAttitudeControl().
_vtol_vehicle_status
vtol_vehicle_status_s VtolAttitudeControl::_vtol_vehicle_status {} private
Definition at line 179 of file vtol_att_control_main.h.
Referenced by abort_front_transition(), get_vtol_vehicle_status(), is_fixed_wing_requested(), parameters_update(), Run(), and VtolAttitudeControl().
_vtol_vehicle_status_pub
uORB::Publication<vtol_vehicle_status_s> VtolAttitudeControl::_vtol_vehicle_status_pub {ORB_ID(vtol_vehicle_status)} private
Definition at line 156 of file vtol_att_control_main.h.
Referenced by Run().
airspeed_blend
param_t VtolAttitudeControl::airspeed_blend
Definition at line 200 of file vtol_att_control_main.h.
airspeed_mode
param_t VtolAttitudeControl::airspeed_mode
Definition at line 201 of file vtol_att_control_main.h.
back_trans_duration
param_t VtolAttitudeControl::back_trans_duration
Definition at line 196 of file vtol_att_control_main.h.
back_trans_throttle
param_t VtolAttitudeControl::back_trans_throttle
Definition at line 199 of file vtol_att_control_main.h.
diff_thrust
param_t VtolAttitudeControl::diff_thrust
Definition at line 205 of file vtol_att_control_main.h.
diff_thrust_scale
param_t VtolAttitudeControl::diff_thrust_scale
Definition at line 206 of file vtol_att_control_main.h.
elevons_mc_lock
param_t VtolAttitudeControl::elevons_mc_lock
Definition at line 188 of file vtol_att_control_main.h.
front_trans_duration
param_t VtolAttitudeControl::front_trans_duration
Definition at line 195 of file vtol_att_control_main.h.
front_trans_throttle
param_t VtolAttitudeControl::front_trans_throttle
Definition at line 198 of file vtol_att_control_main.h.
front_trans_time_min
param_t VtolAttitudeControl::front_trans_time_min
Definition at line 194 of file vtol_att_control_main.h.
front_trans_time_openloop
param_t VtolAttitudeControl::front_trans_time_openloop
Definition at line 193 of file vtol_att_control_main.h.
front_trans_timeout
param_t VtolAttitudeControl::front_trans_timeout
Definition at line 202 of file vtol_att_control_main.h.
fw_alt_err
param_t VtolAttitudeControl::fw_alt_err
Definition at line 190 of file vtol_att_control_main.h.
fw_min_alt
param_t VtolAttitudeControl::fw_min_alt
Definition at line 189 of file vtol_att_control_main.h.
fw_motors_off
param_t VtolAttitudeControl::fw_motors_off
Definition at line 204 of file vtol_att_control_main.h.
fw_qc_max_pitch
param_t VtolAttitudeControl::fw_qc_max_pitch
Definition at line 191 of file vtol_att_control_main.h.
fw_qc_max_roll
param_t VtolAttitudeControl::fw_qc_max_roll
Definition at line 192 of file vtol_att_control_main.h.
idle_pwm_mc
param_t VtolAttitudeControl::idle_pwm_mc
Definition at line 184 of file vtol_att_control_main.h.
mpc_xy_cruise
param_t VtolAttitudeControl::mpc_xy_cruise
Definition at line 203 of file vtol_att_control_main.h.
transition_airspeed
param_t VtolAttitudeControl::transition_airspeed
Definition at line 197 of file vtol_att_control_main.h.
vtol_fw_permanent_stab
param_t VtolAttitudeControl::vtol_fw_permanent_stab
Definition at line 186 of file vtol_att_control_main.h.
vtol_motor_id
param_t VtolAttitudeControl::vtol_motor_id
Definition at line 185 of file vtol_att_control_main.h.
vtol_type
param_t VtolAttitudeControl::vtol_type
Definition at line 187 of file vtol_att_control_main.h.
The documentation for this class was generated from the following files:
src/modules/vtol_att_control/vtol_att_control_main.h
src/modules/vtol_att_control/vtol_att_control_main.cpp