PX4 Firmware: src/lib/ecl/EKF/tests/base/base.cpp File Reference
base.cpp File Reference
Tests for the estimator base class.
#include <EKF/ekf.h>
#include <cstdio>
#include <random>
Functions
int main (int argc, char *argv[])
Detailed Description
Tests for the estimator base class.
Definition in file base.cpp.
Function Documentation
int main (int argc, char * argv[])
Definition at line 45 of file base.cpp.
References estimator::gps_message::alt, baro(), estimator::gps_message::eph, estimator::gps_message::epv, f(), estimator::gps_message::fix_type, estimator::gps_message::lat, estimator::gps_message::lon, mag(), EstimatorInterface::setAirspeedData(), EstimatorInterface::setBaroData(), EstimatorInterface::setGpsData(), EstimatorInterface::setIMUData(), EstimatorInterface::setMagData(), estimator::gps_message::time_usec, and estimator::gps_message::vel_ned_valid.