PX4 Firmware: vmount::InputMavlinkROI Class Reference
vmount::InputMavlinkROI Class Reference
class InputMavlinkROI Input based on the vehicle_roi topic
#include <input_mavlink.h>
Public Member Functions
InputMavlinkROI ()=default
virtual ~InputMavlinkROI ()
virtual void print_status ()
report status to stdout
Public Member Functions inherited from vmount::InputBase
virtual ~InputBase ()
virtual int update (unsigned int timeout_ms, ControlData **control_data, bool already_active)
Wait for an input update, with a timeout.
Protected Member Functions
virtual int update_impl (unsigned int timeout_ms, ControlData **control_data, bool already_active)
virtual int initialize ()
Protected Member Functions inherited from vmount::InputBase
void control_data_set_lon_lat (double lon, double lat, float altitude, float roll_angle=0.f, float pitch_fixed_angle=-10.f)
Private Member Functions
void _read_control_data_from_position_setpoint_sub ()
Private Attributes
int _vehicle_roi_sub = -1
int _position_setpoint_triplet_sub = -1
uint8_t _cur_roi_mode = vehicle_roi_s::ROI_NONE
Additional Inherited Members
Protected Attributes inherited from vmount::InputBase
ControlData _control_data
Detailed Description
class InputMavlinkROI Input based on the vehicle_roi topic
Definition at line 55 of file input_mavlink.h.
Constructor & Destructor Documentation
InputMavlinkROI()
vmount::InputMavlinkROI::InputMavlinkROI () default
~InputMavlinkROI()
vmount::InputMavlinkROI::~InputMavlinkROI () virtual
Definition at line 56 of file input_mavlink.cpp.
References _position_setpoint_triplet_sub, _vehicle_roi_sub, and orb_unsubscribe().
Member Function Documentation
_read_control_data_from_position_setpoint_sub()
void vmount::InputMavlinkROI::_read_control_data_from_position_setpoint_sub () private
Definition at line 163 of file input_mavlink.cpp.
References vmount::InputBase::_control_data, _position_setpoint_triplet_sub, position_setpoint_s::alt, vmount::ControlData::TypeData::TypeLonLat::altitude, position_setpoint_triplet_s::current, position_setpoint_s::lat, vmount::ControlData::TypeData::TypeLonLat::lat, position_setpoint_s::lon, vmount::ControlData::TypeData::TypeLonLat::lon, vmount::ControlData::TypeData::lonlat, orb_copy(), ORB_ID, and vmount::ControlData::type_data.
Referenced by update_impl().
initialize()
int vmount::InputMavlinkROI::initialize () protected virtual
Reimplemented from vmount::InputBase.
Definition at line 67 of file input_mavlink.cpp.
References _position_setpoint_triplet_sub, _vehicle_roi_sub, ORB_ID, and orb_subscribe().
print_status()
void vmount::InputMavlinkROI::print_status () virtual
report status to stdout
Implements vmount::InputBase.
Definition at line 172 of file input_mavlink.cpp.
update_impl()
int vmount::InputMavlinkROI::update_impl (unsigned int timeout_ms, ControlData ** control_data, bool already_active) protected virtual
Implements vmount::InputBase.
Definition at line 84 of file input_mavlink.cpp.
References vmount::InputBase::_control_data, _cur_roi_mode, _position_setpoint_triplet_sub, _read_control_data_from_position_setpoint_sub(), _vehicle_roi_sub, vehicle_roi_s::alt, vmount::InputBase::control_data_set_lon_lat(), vmount::ControlData::gimbal_shutter_retract, vehicle_roi_s::lat, vehicle_roi_s::lon, vmount::ControlData::LonLat, vmount::ControlData::TypeData::lonlat, vehicle_roi_s::mode, vmount::ControlData::Neutral, orb_copy(), ORB_ID, vmount::ControlData::TypeData::TypeLonLat::pitch_angle_offset, vmount::ControlData::TypeData::TypeLonLat::pitch_fixed_angle, vehicle_roi_s::pitch_offset, px4_poll(), vmount::ControlData::TypeData::TypeLonLat::roll_angle, vehicle_roi_s::roll_offset, vmount::ControlData::stabilize_axis, vmount::ControlData::type, vmount::ControlData::type_data, vmount::ControlData::TypeData::TypeLonLat::yaw_angle_offset, and vehicle_roi_s::yaw_offset.
Member Data Documentation
_cur_roi_mode
uint8_t vmount::InputMavlinkROI::_cur_roi_mode = vehicle_roi_s::ROI_NONE private
Definition at line 72 of file input_mavlink.h.
Referenced by update_impl().
_position_setpoint_triplet_sub
int vmount::InputMavlinkROI::_position_setpoint_triplet_sub = -1 private
Definition at line 71 of file input_mavlink.h.
Referenced by _read_control_data_from_position_setpoint_sub(), initialize(), update_impl(), and ~InputMavlinkROI().
_vehicle_roi_sub
int vmount::InputMavlinkROI::_vehicle_roi_sub = -1 private
Definition at line 70 of file input_mavlink.h.
Referenced by initialize(), update_impl(), and ~InputMavlinkROI().
The documentation for this class was generated from the following files:
src/modules/vmount/input_mavlink.h
src/modules/vmount/input_mavlink.cpp