PX4 Firmware: DfLtc2946Wrapper Class Reference
DfLtc2946Wrapper Class Reference
Public Member Functions
DfLtc2946Wrapper ()
~DfLtc2946Wrapper ()
int start ()
int stop ()
Private Member Functions
int _publish (const struct ltc2946_sensor_data &data)
Private Attributes
orb_advert_t _battery_pub {nullptr}
battery_status_s _battery_status {}
Battery _battery {}
int _actuator_ctrl_0_sub {-1}
int _vcontrol_mode_sub {-1}
Detailed Description
Definition at line 61 of file df_ltc2946_wrapper.cpp.
Constructor & Destructor Documentation
DfLtc2946Wrapper::DfLtc2946Wrapper ()
Definition at line 82 of file df_ltc2946_wrapper.cpp.
References _actuator_ctrl_0_sub, _battery, _battery_status, _vcontrol_mode_sub, ORB_ID, orb_subscribe(), and Battery::reset().
Referenced by df_ltc2946_wrapper::start().
DfLtc2946Wrapper::~DfLtc2946Wrapper ()
Definition at line 92 of file df_ltc2946_wrapper.cpp.
References _actuator_ctrl_0_sub, _vcontrol_mode_sub, and orb_unsubscribe().
Member Function Documentation
int DfLtc2946Wrapper::_publish (const struct ltc2946_sensor_data & data) private
Definition at line 134 of file df_ltc2946_wrapper.cpp.
References _actuator_ctrl_0_sub, _battery, _battery_pub, _battery_status, _vcontrol_mode_sub, BOARD_ADC_OPEN_CIRCUIT_V, actuator_controls_s::control, vehicle_control_mode_s::flag_armed, hrt_absolute_time(), hrt_abstime, instance, orb_copy(), ORB_ID, ORB_PRIO_DEFAULT, orb_publish_auto(), and Battery::updateBatteryStatus().
int DfLtc2946Wrapper::start ()
Definition at line 98 of file df_ltc2946_wrapper.cpp.
References lis3mdl::init(), PX4_ERR, and start().
Referenced by df_ltc2946_wrapper::start().
int DfLtc2946Wrapper::stop ()
Definition at line 121 of file df_ltc2946_wrapper.cpp.
References PX4_ERR, and stop().
Referenced by df_ltc2946_wrapper::stop().
Member Data Documentation
int DfLtc2946Wrapper::_actuator_ctrl_0_sub {-1} private
Definition at line 77 of file df_ltc2946_wrapper.cpp.
Referenced by _publish(), DfLtc2946Wrapper(), and ~DfLtc2946Wrapper().
Battery DfLtc2946Wrapper::_battery {} private
Definition at line 75 of file df_ltc2946_wrapper.cpp.
Referenced by _publish(), and DfLtc2946Wrapper().
orb_advert_t DfLtc2946Wrapper::_battery_pub {nullptr} private
Definition at line 73 of file df_ltc2946_wrapper.cpp.
Referenced by _publish().
battery_status_s DfLtc2946Wrapper::_battery_status {} private
Definition at line 74 of file df_ltc2946_wrapper.cpp.
Referenced by _publish(), and DfLtc2946Wrapper().
int DfLtc2946Wrapper::_vcontrol_mode_sub {-1} private
Definition at line 78 of file df_ltc2946_wrapper.cpp.
Referenced by _publish(), DfLtc2946Wrapper(), and ~DfLtc2946Wrapper().
The documentation for this class was generated from the following file:
src/platforms/posix/drivers/df_ltc2946_wrapper/df_ltc2946_wrapper.cpp