PX4 Firmware: src/modules/simulator/barosim/baro.cpp File Reference
baro.cpp File Reference
#include <inttypes.h>
#include <px4_config.h>
#include <px4_defines.h>
#include <px4_time.h>
#include <px4_getopt.h>
#include <sys/types.h>
#include <stdint.h>
#include <stdbool.h>
#include <stdlib.h>
#include <semaphore.h>
#include <string.h>
#include <fcntl.h>
#include <errno.h>
#include <stdio.h>
#include <math.h>
#include <unistd.h>
#include <arch/board/board.h>
#include <board_config.h>
#include <drivers/device/device.h>
#include <drivers/drv_baro.h>
#include <drivers/drv_hrt.h>
#include <drivers/device/ringbuffer.h>
#include <simulator/simulator.h>
#include <perf/perf_counter.h>
#include <systemlib/err.h>
#include "barosim.h"
#include "VirtDevObj.hpp"
Classes
class BAROSIM
Namespaces
barosim
Macros
#define POW2(_x) ((_x) * (_x))
#define BAROSIM_DEV_PATH "/dev/barosim"
#define BAROSIM_MEASURE_INTERVAL_US (10000)
Functions
__EXPORT int barosim_main (int argc, char *argv[])
static int barosim::start ()
Start the driver.
static int barosim::info ()
Print a little info about the driver.
static void barosim::usage ()
Variables
static BAROSIM * g_barosim = nullptr
Macro Definition Documentation
#define BAROSIM_DEV_PATH "/dev/barosim"
Definition at line 76 of file baro.cpp.
Referenced by barosim::info(), and barosim::start().
#define BAROSIM_MEASURE_INTERVAL_US (10000)
Definition at line 78 of file baro.cpp.
#define POW2 (_x) ((_x) * (_x))
Definition at line 74 of file baro.cpp.
Function Documentation
int barosim_main (int argc, char * argv[])
Definition at line 325 of file baro.cpp.
References barosim::info(), barosim::start(), and barosim::usage().
Variable Documentation
BAROSIM* g_barosim = nullptr static
Definition at line 125 of file baro.cpp.
Referenced by barosim::start().