PX4 Firmware: src/lib/drivers/device/posix/cdev_platform.cpp File Reference
cdev_platform.cpp File Reference
#include "cdev_platform.hpp"
#include <string>
#include <map>
#include "vfile.h"
#include "../CDev.hpp"
#include <px4_log.h>
#include <px4_posix.h>
#include <px4_time.h>
#include "DevMgr.hpp"
Macros
#define PX4_MAX_FD 350
Functions
static device::CDev * getDev (const char *path)
static device::CDev * get_vdev (int fd)
int register_driver (const char *name, const device::px4_file_operations_t *fops, device::mode_t mode, void *data)
int unregister_driver (const char *name)
int px4_open (const char *path, int flags,...)
int px4_close (int fd)
ssize_t px4_read (int fd, void *buffer, size_t buflen)
ssize_t px4_write (int fd, const void *buffer, size_t buflen)
int px4_ioctl (int fd, int cmd, unsigned long arg)
int px4_poll (px4_pollfd_struct_t *fds, nfds_t nfds, int timeout)
int px4_fsync (int fd)
int px4_access (const char *pathname, int mode)
void px4_show_devices ()
void px4_show_topics ()
void px4_show_files ()
void px4_enable_sim_lockstep ()
void px4_sim_start_delay ()
void px4_sim_stop_delay ()
bool px4_sim_delay_enabled ()
Variables
pthread_mutex_t devmutex = PTHREAD_MUTEX_INITIALIZER
pthread_mutex_t filemutex = PTHREAD_MUTEX_INITIALIZER
px4_sem_t lockstep_sem
bool sim_lockstep = false
volatile bool sim_delay = false
static map< string, void * > devmap
static device::file_t filemap [PX4_MAX_FD] = {}
int px4_errno
Macro Definition Documentation
#define PX4_MAX_FD 350
Definition at line 66 of file cdev_platform.cpp.
Referenced by px4_open().
Function Documentation
static device::CDev* get_vdev (int fd) static
Definition at line 92 of file cdev_platform.cpp.
References fd, filemutex, pthread_mutex_lock(), pthread_mutex_unlock(), and device::file_t::vdev.
Referenced by px4_close(), px4_ioctl(), px4_poll(), px4_read(), and px4_write().
static device::CDev* getDev (const char * path) static
Definition at line 74 of file cdev_platform.cpp.
References devmutex, pthread_mutex_lock(), pthread_mutex_unlock(), and PX4_DEBUG.
Referenced by px4_access(), and px4_open().
int px4_access (const char * pathname, int mode)
Definition at line 453 of file cdev_platform.cpp.
References getDev().
Referenced by uORB::Manager::orb_exists().
int px4_close (int fd)
Definition at line 226 of file cdev_platform.cpp.
References device::CDev::close(), fd, filemutex, get_vdev(), pthread_mutex_lock(), pthread_mutex_unlock(), PX4_DEBUG, PX4_ERROR, and device::file_t::vdev.
Referenced by accel(), VtolType::apply_pwm_limits(), baro(), blinkm_main(), calibrate_from_orientation(), commander_low_prio_loop(), do_accel_calibration(), do_accel_calibration_measurements(), do_airspeed_calibration(), do_esc_calibration(), do_gyro_calibration(), do_mag_calibration(), do_trim_calibration(), gyro(), MavlinkReceiver::handle_message_play_tune(), VtolType::init(), mag(), mag_calibrate_all(), mag_calibration_worker(), VCDevExample::main(), motor_ramp_thread_main(), uORB::Manager::node_advertise(), Syslink::open_serial(), uORB::Manager::orb_advertise_multi(), uORB::Manager::orb_exists(), uORB::Manager::orb_unsubscribe(), Sensors::parameter_update_poll(), adis16477::reset(), ll40ls::reset(), sf1xx::reset(), mb12xx::reset(), srf02::reset(), teraranger::reset(), Commander::run(), adis16477::start(), lsm303agr::start(), ll40ls::start(), lps22hb::start_bus(), sf1xx::start_bus(), mb12xx::start_bus(), srf02::start_bus(), teraranger::start_bus(), vl53lxx::start_bus(), adis16477::test(), ll40ls::test(), sf1xx::test(), teraranger::test(), vl53lxx::test(), test_adc(), test_file(), test_gpio(), test_mount(), test_tone(), and writer_main().
void px4_enable_sim_lockstep ()
Definition at line 525 of file cdev_platform.cpp.
References lockstep_sem, px4_sem_init, px4_sem_setprotocol, SEM_PRIO_NONE, sim_delay, and sim_lockstep.
Referenced by simulator_main().
int px4_fsync (int fd)
Definition at line 448 of file cdev_platform.cpp.
int px4_ioctl (int fd, int cmd, unsigned long arg)
Definition at line 297 of file cdev_platform.cpp.
References get_vdev(), device::CDev::ioctl(), and PX4_DEBUG.
Referenced by VtolType::apply_pwm_limits(), blinkm_main(), do_accel_calibration(), do_airspeed_calibration(), do_esc_calibration(), do_gyro_calibration(), do_mag_calibration(), VtolType::init(), load(), mag_calibrate_all(), VCDevExample::main(), uORB::Manager::node_advertise(), uORB::Manager::orb_advertise_multi(), uORB::Manager::orb_check(), uORB::Manager::orb_exists(), uORB::Manager::orb_get_interval(), uORB::Manager::orb_priority(), uORB::Manager::orb_set_interval(), uORB::Manager::orb_stat(), Sensors::parameter_update_poll(), prepare(), pwm_main(), sdp3x_airspeed::reset(), ms5525_airspeed::reset(), adis16477::reset(), lps22hb::reset(), ll40ls::reset(), meas_airspeed::reset(), tfmini::reset(), pmw3901::reset(), set_min_pwm(), adis16477::start(), lsm303agr::start(), ll40ls::start(), meas_airspeed_sim::start(), tfmini::start(), sdp3x_airspeed::start_bus(), ms5525_airspeed::start_bus(), lps22hb::start_bus(), ets_airspeed::start_bus(), meas_airspeed::start_bus(), ll40ls::test(), meas_airspeed_sim::test(), tfmini::test(), test_gpio(), test_led(), test_pub_block(), and test_tone().
int px4_open (const char * path, int flags, ...)
Definition at line 157 of file cdev_platform.cpp.
References device::VFile::createFile(), filemutex, getDev(), device::CDev::open(), pthread_mutex_lock(), pthread_mutex_unlock(), pthread_self(), PX4_BACKTRACE, PX4_DEBUG, PX4_F_WRONLY, PX4_MAX_FD, and PX4_WARN.
Referenced by accel(), VtolType::apply_pwm_limits(), baro(), blinkm_main(), do_accel_calibration(), do_airspeed_calibration(), do_esc_calibration(), do_gyro_calibration(), do_mag_calibration(), gyro(), MavlinkReceiver::handle_message_play_tune(), VtolType::init(), load(), mag(), mag_calibrate_all(), VCDevExample::main(), motor_ramp_thread_main(), uORB::Manager::node_advertise(), uORB::Manager::node_open(), Syslink::open_serial(), uORB::Manager::orb_exists(), Sensors::parameter_update_poll(), pwm_main(), sdp3x_airspeed::reset(), ms5525_airspeed::reset(), adis16477::reset(), ll40ls::reset(), meas_airspeed::reset(), sf1xx::reset(), mb12xx::reset(), srf02::reset(), tfmini::reset(), pmw3901::reset(), teraranger::reset(), adis16477::start(), lsm303agr::start(), ll40ls::start(), meas_airspeed_sim::start(), tfmini::start(), sdp3x_airspeed::start_bus(), ms5525_airspeed::start_bus(), lps22hb::start_bus(), ets_airspeed::start_bus(), meas_airspeed::start_bus(), sf1xx::start_bus(), mb12xx::start_bus(), srf02::start_bus(), teraranger::start_bus(), vl53lxx::start_bus(), adis16477::test(), ll40ls::test(), meas_airspeed_sim::test(), sf1xx::test(), mb12xx::test(), srf02::test(), tfmini::test(), teraranger::test(), vl53lxx::test(), test_adc(), test_file(), test_gpio(), test_led(), test_mount(), test_tone(), and writer_main().
int px4_poll (px4_pollfd_struct_t * fds, nfds_t nfds, int timeout)
Definition at line 318 of file cdev_platform.cpp.
References fd, get_vdev(), device::CDev::poll(), pthread_self(), px4_clock_gettime, PX4_DEBUG, px4_sem_destroy, px4_sem_init, px4_sem_setprotocol, px4_sem_t, px4_sem_timedwait, px4_sem_wait, PX4_WARN, SEM_PRIO_NONE, sim_delay, and usleep().
Referenced by calibrate_cancel_check(), commander_low_prio_loop(), TAP_ESC::cycle(), PX4FMU::cycle(), detect_orientation(), do_airspeed_calibration(), do_level_calibration(), VCDevExample::do_poll(), gyro_calibration_worker(), px4::ReplayEkf2::handleTopicUpdate(), mag_calibration_worker(), QShell::main(), position_estimator_inav_thread_main(), px4::logger::LogWriterMavlink::publish_message(), uORBTest::UnitTest::pubsublatency_main(), read_accelerometer_avg(), PWMSim::run(), MulticopterAttitudeControl::run(), FixedwingAttitudeControl::run(), Navigator::run(), Ekf2::run(), px4::logger::Logger::run(), FixedwingPositionControl::run(), Sensors::run(), Simulator::send(), px4::NodeHandle::spin(), TemperatureCalibration::task_main(), AttitudeEstimatorQ::task_main(), uart_esc::task_main(), CameraFeedback::task_main(), linux_pwm_out::task_main(), snapdragon_pwm::task_main(), GroundRoverAttitudeControl::task_main(), Syslink::task_main(), GroundRoverPositionControl::task_main(), VtolAttitudeControl::task_main(), MulticopterPositionControl::task_main(), df_bebop_bus_wrapper::task_main(), ll40ls::test(), tfmini::test(), uORBTest::UnitTest::test_queue_poll_notify(), BlockLocalPositionEstimator::update(), vmount::InputMavlinkROI::update_impl(), vmount::InputRC::update_impl(), and vmount::InputMavlinkCmdMount::update_impl().
ssize_t px4_read (int fd, void * buffer, size_t buflen)
Definition at line 253 of file cdev_platform.cpp.
References get_vdev(), PX4_DEBUG, PX4_ERROR, and device::CDev::read().
Referenced by accel(), baro(), VCDevExample::do_poll(), gyro(), mag(), uORB::Manager::orb_copy(), adis16477::test(), ll40ls::test(), meas_airspeed_sim::test(), tfmini::test(), and test_adc().
void px4_show_devices (void)
Definition at line 464 of file cdev_platform.cpp.
References devmutex, pthread_mutex_lock(), pthread_mutex_unlock(), and PX4_INFO.
void px4_show_files (void)
Definition at line 509 of file cdev_platform.cpp.
References devmutex, pthread_mutex_lock(), pthread_mutex_unlock(), and PX4_INFO.
void px4_show_topics (void)
Definition at line 494 of file cdev_platform.cpp.
References devmutex, pthread_mutex_lock(), pthread_mutex_unlock(), and PX4_INFO.
bool px4_sim_delay_enabled ()
Definition at line 546 of file cdev_platform.cpp.
References sim_delay.
Referenced by uORB::DeviceNode::appears_updated().
void px4_sim_start_delay ()
Definition at line 536 of file cdev_platform.cpp.
References sim_delay.
Referenced by Simulator::handle_message(), and Simulator::pollForMAVLinkMessages().
void px4_sim_stop_delay ()
Definition at line 541 of file cdev_platform.cpp.
References sim_delay.
Referenced by Simulator::handle_message(), and Simulator::pollForMAVLinkMessages().
ssize_t px4_write (int fd, const void * buffer, size_t buflen)
Definition at line 275 of file cdev_platform.cpp.
References get_vdev(), PX4_DEBUG, PX4_ERROR, and device::CDev::write().
Referenced by MavlinkReceiver::handle_message_play_tune(), and writer_main().
int register_driver (const char * name, const device::px4_file_operations_t * fops, device::mode_t mode, void * data)
Definition at line 109 of file cdev_platform.cpp.
References devmutex, name, pthread_mutex_lock(), pthread_mutex_unlock(), and PX4_DEBUG.
Referenced by device::VFile::createFile(), device::file_t::file_t(), device::CDev::init(), PX4IO::init(), MK::init(), and device::CDev::register_class_devname().
int unregister_driver (const char * name)
Definition at line 136 of file cdev_platform.cpp.
References devmutex, pthread_mutex_lock(), pthread_mutex_unlock(), and PX4_DEBUG.
Referenced by device::file_t::file_t(), PX4IO::task_main(), device::CDev::unregister_class_devname(), device::CDev::~CDev(), and MK::~MK().
Variable Documentation
map<string, void *> devmap static
Definition at line 67 of file cdev_platform.cpp.
pthread_mutex_t devmutex = PTHREAD_MUTEX_INITIALIZER
Definition at line 59 of file cdev_platform.cpp.
Referenced by getDev(), px4_show_devices(), px4_show_files(), px4_show_topics(), register_driver(), and unregister_driver().
device::file_t filemap[PX4_MAX_FD] = {} static
Definition at line 68 of file cdev_platform.cpp.
pthread_mutex_t filemutex = PTHREAD_MUTEX_INITIALIZER
Definition at line 60 of file cdev_platform.cpp.
Referenced by get_vdev(), px4_close(), and px4_open().
px4_sem_t lockstep_sem
Definition at line 62 of file cdev_platform.cpp.
Referenced by px4_enable_sim_lockstep().
int px4_errno
Definition at line 72 of file cdev_platform.cpp.
Referenced by VCDevExample::do_poll(), VCDevExample::main(), test_pub_block(), and writer_main().
volatile bool sim_delay = false
Definition at line 64 of file cdev_platform.cpp.
Referenced by Simulator::pollForMAVLinkMessages(), px4_enable_sim_lockstep(), px4_poll(), px4_sim_delay_enabled(), px4_sim_start_delay(), and px4_sim_stop_delay().
bool sim_lockstep = false
Definition at line 63 of file cdev_platform.cpp.
Referenced by px4_enable_sim_lockstep().