PX4 Firmware: AttitudeEstimator Class Reference
AttitudeEstimator Class Reference
#include <attitude_estimator.h>
Public Member Functions
AttitudeEstimator ()
~AttitudeEstimator ()
Protected Member Functions
void ModelStatesCallback (const gazebo_msgs::ModelStatesConstPtr &msg)
void ImuCallback (const sensor_msgs::ImuConstPtr &msg)
Protected Attributes
ros::NodeHandle _n
ros::Subscriber _sub_modelstates
ros::Subscriber _sub_imu
ros::Publisher _vehicle_attitude_pub
Detailed Description
Definition at line 47 of file attitude_estimator.h.
Constructor & Destructor Documentation
AttitudeEstimator::AttitudeEstimator ()
Definition at line 48 of file attitude_estimator.cpp.
References _n, _sub_imu, and ImuCallback().
AttitudeEstimator::~AttitudeEstimator () inline
Definition at line 52 of file attitude_estimator.h.
References ImuCallback(), ModelStatesCallback(), and msg.
Member Function Documentation
void AttitudeEstimator::ImuCallback (const sensor_msgs::ImuConstPtr & msg) protected
Definition at line 87 of file attitude_estimator.cpp.
References _vehicle_attitude_pub, and px4::get_time_micros().
Referenced by AttitudeEstimator(), and ~AttitudeEstimator().
void AttitudeEstimator::ModelStatesCallback (const gazebo_msgs::ModelStatesConstPtr & msg) protected
Definition at line 58 of file attitude_estimator.cpp.
References _vehicle_attitude_pub, and px4::get_time_micros().
Referenced by ~AttitudeEstimator().
Member Data Documentation
ros::NodeHandle AttitudeEstimator::_n protected
Definition at line 58 of file attitude_estimator.h.
Referenced by AttitudeEstimator().
ros::Subscriber AttitudeEstimator::_sub_imu protected
Definition at line 60 of file attitude_estimator.h.
Referenced by AttitudeEstimator().
ros::Subscriber AttitudeEstimator::_sub_modelstates protected
Definition at line 59 of file attitude_estimator.h.
ros::Publisher AttitudeEstimator::_vehicle_attitude_pub protected
Definition at line 61 of file attitude_estimator.h.
Referenced by ImuCallback(), and ModelStatesCallback().
The documentation for this class was generated from the following files:
src/platforms/ros/nodes/attitude_estimator/attitude_estimator.h
src/platforms/ros/nodes/attitude_estimator/attitude_estimator.cpp