PX4 Firmware: uORB::PublicationData< T > Class Template Reference
uORB::PublicationData< T > Class Template Reference
The publication class with data embedded.
#include <Publication.hpp>
Public Member Functions
PublicationData (const orb_metadata *meta)
Constructor.
~PublicationData ()=default
T & get ()
void set (const T &data)
bool update ()
bool update (const T &data)
Public Member Functions inherited from uORB::Publication< T >
Publication (const orb_metadata *meta)
Constructor.
~Publication ()
bool publish (const T &data)
Publish the struct.
Private Attributes
T _data {}
Additional Inherited Members
Protected Attributes inherited from uORB::Publication< T >
const orb_metadata * _meta
orb_advert_t _handle {nullptr}
Detailed Description
template<typename T>
class uORB::PublicationData< T >
The publication class with data embedded.
Definition at line 95 of file Publication.hpp.
Constructor & Destructor Documentation
PublicationData()
template<typename T> uORB::PublicationData< T >::PublicationData (const orb_metadata * meta) inline
Constructor.
Parameters
meta The uORB metadata (usually from the ORB_ID() macro) for the topic.
Definition at line 103 of file Publication.hpp.
~PublicationData()
template<typename T> uORB::PublicationData< T >::~PublicationData () default
Member Function Documentation
get()
template<typename T> T& uORB::PublicationData< T >::get () inline
Definition at line 106 of file Publication.hpp.
Referenced by BlockLocalPositionEstimator::flowCorrect(), BlockLocalPositionEstimator::gpsCorrect(), Commander::handle_command(), DShotOutput::handleNewTelemetryData(), BlockLocalPositionEstimator::landCorrect(), BlockLocalPositionEstimator::lidarCorrect(), BlockLocalPositionEstimator::mocapCorrect(), BlockLocalPositionEstimator::publishEstimatorStatus(), BlockLocalPositionEstimator::publishGlobalPos(), BlockLocalPositionEstimator::publishLocalPos(), BlockLocalPositionEstimator::publishOdom(), Commander::run(), Ekf2::Run(), BlockLocalPositionEstimator::Run(), Commander::set_home_position_alt_only(), BlockLocalPositionEstimator::sonarCorrect(), and BlockLocalPositionEstimator::visionCorrect().
set()
template<typename T> void uORB::PublicationData< T >::set (const T & data) inline
Definition at line 107 of file Publication.hpp.
update() [1/2]
template<typename T> bool uORB::PublicationData< T >::update () inline
Definition at line 110 of file Publication.hpp.
Referenced by Commander::handle_command(), DShotOutput::handleNewTelemetryData(), BlockLocalPositionEstimator::publishEstimatorStatus(), BlockLocalPositionEstimator::publishGlobalPos(), BlockLocalPositionEstimator::publishLocalPos(), BlockLocalPositionEstimator::publishOdom(), Ekf2::Run(), BlockLocalPositionEstimator::Run(), Commander::set_home_position(), and Commander::set_home_position_alt_only().
update() [2/2]
template<typename T> bool uORB::PublicationData< T >::update (const T & data) inline
Definition at line 111 of file Publication.hpp.
Member Data Documentation
_data
template<typename T> T uORB::PublicationData< T >::_data {} private
Definition at line 118 of file Publication.hpp.
The documentation for this class was generated from the following file:
src/modules/uORB/Publication.hpp