PX4 Firmware: EkfInitializationTest Class Reference
EkfInitializationTest Class Reference
Public Member Functions
void SetUp () override
void update_with_const_sensors (uint32_t duration_us, Vector3f ang_vel=Vector3f{0.0f, 0.0f, 0.0f}, Vector3f accel=Vector3f{0.0f, 0.0f,-CONSTANTS_ONE_G}, Vector3f mag_data=Vector3f{0.2f, 0.0f, 0.4f}, float baro_data=122.2f)
void TearDown () override
Public Attributes
Ekf _ekf {}
const uint32_t _imu_dt_us {4000}
const uint32_t _baro_dt_us {12500}
const uint32_t _mag_dt_us {12500}
const uint32_t _gps_dt_us {200000}
bool _fuse_imu {true}
bool _fuse_baro {true}
bool _fuse_mag {true}
bool _fuse_gps {false}
gps_message _gps_message {}
uint32_t _update_dt_us {}
const uint32_t _init_duration_us {2000000}
uint32_t _counter_imu {0}
uint32_t _counter_baro {0}
uint32_t _counter_mag {0}
uint32_t _t_us {0}
Detailed Description
Definition at line 38 of file test_EKF_basics.cpp.
Member Function Documentation
SetUp()
void EkfInitializationTest::SetUp () inline override
Definition at line 69 of file test_EKF_basics.cpp.
References _ekf, _gps_message, _init_duration_us, estimator::gps_message::alt, estimator::gps_message::eph, estimator::gps_message::epv, estimator::gps_message::fix_type, Ekf::init(), estimator::gps_message::lat, estimator::gps_message::lon, estimator::gps_message::nsats, estimator::gps_message::pdop, estimator::gps_message::sacc, estimator::gps_message::time_usec, update_with_const_sensors(), estimator::gps_message::vel_m_s, estimator::gps_message::vel_ned, estimator::gps_message::vel_ned_valid, estimator::gps_message::yaw, and estimator::gps_message::yaw_offset.
TearDown()
void EkfInitializationTest::TearDown () inline override
Definition at line 156 of file test_EKF_basics.cpp.
update_with_const_sensors()
void EkfInitializationTest::update_with_const_sensors (uint32_t duration_us, Vector3f ang_vel = Vector3f{0.0f,0.0f,0.0f}, Vector3f accel = Vector3f{0.0f,0.0f,-CONSTANTS_ONE_G}, Vector3f mag_data = Vector3f{0.2f, 0.0f, 0.4f}, float baro_data = 122.2f) inline
Definition at line 103 of file test_EKF_basics.cpp.
References _baro_dt_us, _counter_baro, _counter_imu, _counter_mag, _ekf, _fuse_baro, _fuse_gps, _fuse_imu, _fuse_mag, _gps_dt_us, _gps_message, _imu_dt_us, _mag_dt_us, _t_us, _update_dt_us, CONSTANTS_ONE_G, estimator::imuSample::delta_ang, estimator::imuSample::delta_ang_dt, estimator::imuSample::delta_vel, estimator::imuSample::delta_vel_dt, f(), EstimatorInterface::setBaroData(), EstimatorInterface::setGpsData(), EstimatorInterface::setIMUData(), EstimatorInterface::setMagData(), estimator::imuSample::time_us, estimator::gps_message::time_usec, and Ekf::update().
Referenced by SetUp(), and TEST_F().
Member Data Documentation
_baro_dt_us
const uint32_t EkfInitializationTest::_baro_dt_us {12500}
Definition at line 45 of file test_EKF_basics.cpp.
Referenced by update_with_const_sensors().
_counter_baro
uint32_t EkfInitializationTest::_counter_baro {0}
Definition at line 63 of file test_EKF_basics.cpp.
Referenced by update_with_const_sensors().
_counter_imu
uint32_t EkfInitializationTest::_counter_imu {0}
Definition at line 62 of file test_EKF_basics.cpp.
Referenced by update_with_const_sensors().
_counter_mag
uint32_t EkfInitializationTest::_counter_mag {0}
Definition at line 64 of file test_EKF_basics.cpp.
Referenced by update_with_const_sensors().
_ekf
Ekf EkfInitializationTest::_ekf {}
Definition at line 41 of file test_EKF_basics.cpp.
Referenced by SetUp(), TEST_F(), and update_with_const_sensors().
_fuse_baro
bool EkfInitializationTest::_fuse_baro {true}
Definition at line 51 of file test_EKF_basics.cpp.
Referenced by update_with_const_sensors().
_fuse_gps
bool EkfInitializationTest::_fuse_gps {false}
Definition at line 53 of file test_EKF_basics.cpp.
Referenced by TEST_F(), and update_with_const_sensors().
_fuse_imu
bool EkfInitializationTest::_fuse_imu {true}
Definition at line 50 of file test_EKF_basics.cpp.
Referenced by update_with_const_sensors().
_fuse_mag
bool EkfInitializationTest::_fuse_mag {true}
Definition at line 52 of file test_EKF_basics.cpp.
Referenced by update_with_const_sensors().
_gps_dt_us
const uint32_t EkfInitializationTest::_gps_dt_us {200000}
Definition at line 47 of file test_EKF_basics.cpp.
Referenced by update_with_const_sensors().
_gps_message
gps_message EkfInitializationTest::_gps_message {}
Definition at line 56 of file test_EKF_basics.cpp.
Referenced by SetUp(), and update_with_const_sensors().
_imu_dt_us
const uint32_t EkfInitializationTest::_imu_dt_us {4000}
Definition at line 44 of file test_EKF_basics.cpp.
Referenced by update_with_const_sensors().
_init_duration_us
const uint32_t EkfInitializationTest::_init_duration_us {2000000}
Definition at line 59 of file test_EKF_basics.cpp.
Referenced by SetUp().
_mag_dt_us
const uint32_t EkfInitializationTest::_mag_dt_us {12500}
Definition at line 46 of file test_EKF_basics.cpp.
Referenced by update_with_const_sensors().
_t_us
uint32_t EkfInitializationTest::_t_us {0}
Definition at line 66 of file test_EKF_basics.cpp.
Referenced by update_with_const_sensors().
_update_dt_us
uint32_t EkfInitializationTest::_update_dt_us {}
Definition at line 58 of file test_EKF_basics.cpp.
Referenced by update_with_const_sensors().
The documentation for this class was generated from the following file:
src/lib/ecl/test/test_EKF_basics.cpp