PX4 Firmware: uORB::FastRpcChannel::Semaphore Class Reference
uORB::FastRpcChannel::Semaphore Class Reference
Public Member Functions
Semaphore ()
~Semaphore ()
void post ()
void wait ()
Private Member Functions
Semaphore (const Semaphore &)
Semaphore & operator= (const Semaphore &)
Private Attributes
sem_t _Sem
Detailed Description
Definition at line 250 of file uORBFastRpcChannel.hpp.
Constructor & Destructor Documentation
uORB::FastRpcChannel::Semaphore::Semaphore () inline
Definition at line 253 of file uORBFastRpcChannel.hpp.
References px4_sem_setprotocol, sem_init(), and SEM_PRIO_NONE.
uORB::FastRpcChannel::Semaphore::~Semaphore () inline
Definition at line 259 of file uORBFastRpcChannel.hpp.
References sem_destroy().
uORB::FastRpcChannel::Semaphore::Semaphore (const Semaphore &) private
Member Function Documentation
Semaphore& uORB::FastRpcChannel::Semaphore::operator= (const Semaphore &) private
void uORB::FastRpcChannel::Semaphore::post () inline
Definition at line 263 of file uORBFastRpcChannel.hpp.
References sem_post().
Referenced by uORB::FastRpcChannel::control_msg_queue_add(), uORB::FastRpcChannel::send_message(), and uORB::FastRpcChannel::unblock_get_data_method().
void uORB::FastRpcChannel::Semaphore::wait () inline
Definition at line 267 of file uORBFastRpcChannel.hpp.
References sem_wait().
Referenced by uORB::FastRpcChannel::get_bulk_data(), and uORB::FastRpcChannel::get_data().
Member Data Documentation
sem_t uORB::FastRpcChannel::Semaphore::_Sem private
Definition at line 272 of file uORBFastRpcChannel.hpp.
The documentation for this class was generated from the following file:
src/modules/muorb/adsp/uORBFastRpcChannel.hpp