PX4 Firmware: uavcan_stm32::CanDriver Class Reference
uavcan_stm32::CanDriver Class Reference
CAN driver, incorporates all available CAN ifaces.
#include <can.hpp>
Public Member Functions
template<unsigned RxQueueCapacity>
CanDriver (CanRxItem(&rx_queue_storage)[UAVCAN_STM32_NUM_IFACES][RxQueueCapacity])
uavcan::CanSelectMasks makeSelectMasks (const uavcan::CanFrame *(&pending_tx)[uavcan::MaxCanIfaces]) const
This function returns select masks indicating which interfaces are available for read/write.
bool hasReadableInterfaces () const
Whether there's at least one interface where receive() would return a frame.
int init (const uavcan::uint32_t bitrate, const CanIface::OperatingMode mode)
Returns zero if OK.
virtual CanIface * getIface (uavcan::uint8_t iface_index)
virtual uavcan::uint8_t getNumIfaces () const
bool hadActivity ()
Whether at least one iface had at least one successful IO since previous call of this method.
BusEvent & updateEvent ()
Private Member Functions
virtual uavcan::int16_t select (uavcan::CanSelectMasks &inout_masks, const uavcan::CanFrame *(&pending_tx)[uavcan::MaxCanIfaces], uavcan::MonotonicTime blocking_deadline)
Static Private Member Functions
static void initOnce ()
Private Attributes
BusEvent update_event_
CanIface if0_
Detailed Description
CAN driver, incorporates all available CAN ifaces.
Please avoid direct use, prefer CanInitHelper instead.
Definition at line 230 of file can.hpp.
Constructor & Destructor Documentation
CanDriver()
template<unsigned RxQueueCapacity> uavcan_stm32::CanDriver::CanDriver (CanRxItem(&) rx_queue_storage[UAVCAN_STM32_NUM_IFACES][RxQueueCapacity]) inline
Definition at line 246 of file can.hpp.
References ToneAlarmInterface::init().
Member Function Documentation
getIface()
CanIface * uavcan_stm32::CanDriver::getIface (uavcan::uint8_t iface_index) virtual
Definition at line 973 of file uc_stm32_can.cpp.
Referenced by uavcan_stm32::CanInitHelper< RxQueueCapacity >::init().
getNumIfaces()
virtual uavcan::uint8_t uavcan_stm32::CanDriver::getNumIfaces () const inline virtual
Definition at line 274 of file can.hpp.
Referenced by uavcan_stm32::CanInitHelper< RxQueueCapacity >::init().
hadActivity()
bool uavcan_stm32::CanDriver::hadActivity ()
Whether at least one iface had at least one successful IO since previous call of this method.
This is designed for use with iface activity LEDs.
Definition at line 982 of file uc_stm32_can.cpp.
References UAVCAN_STM32_IRQ_HANDLER().
hasReadableInterfaces()
bool uavcan_stm32::CanDriver::hasReadableInterfaces () const
Whether there's at least one interface where receive() would return a frame.
Definition at line 824 of file uc_stm32_can.cpp.
init()
int uavcan_stm32::CanDriver::init (const uavcan::uint32_t bitrate, const CanIface::OperatingMode mode)
Returns zero if OK.
Returns negative value if failed (e.g. invalid bitrate).
Definition at line 920 of file uc_stm32_can.cpp.
References UAVCAN_STM32_LOG.
Referenced by uavcan_stm32::CanInitHelper< RxQueueCapacity >::init().
initOnce()
void uavcan_stm32::CanDriver::initOnce () static private
Definition at line 869 of file uc_stm32_can.cpp.
References IRQ_ATTACH, and MicroBenchHRT::lock().
makeSelectMasks()
uavcan::CanSelectMasks uavcan_stm32::CanDriver::makeSelectMasks (const uavcan::CanFrame *(&) pending_tx[uavcan::MaxCanIfaces]) const
This function returns select masks indicating which interfaces are available for read/write.
Definition at line 796 of file uc_stm32_can.cpp.
select()
uavcan::int16_t uavcan_stm32::CanDriver::select (uavcan::CanSelectMasks & inout_masks, const uavcan::CanFrame *(&) pending_tx[uavcan::MaxCanIfaces], uavcan::MonotonicTime blocking_deadline) private virtual
Definition at line 835 of file uc_stm32_can.cpp.
References uavcan_stm32::clock::getMonotonic(), and uavcan_stm32::CanIface::update_event_.
updateEvent()
BusEvent& uavcan_stm32::CanDriver::updateEvent () inline
Definition at line 282 of file can.hpp.
Referenced by UavcanEsc::start().
Member Data Documentation
if0_
CanIface uavcan_stm32::CanDriver::if0_ private
Definition at line 233 of file can.hpp.
update_event_
BusEvent uavcan_stm32::CanDriver::update_event_ private
Definition at line 232 of file can.hpp.
The documentation for this class was generated from the following files:
src/drivers/uavcan/uavcan_drivers/stm32/driver/include/uavcan_stm32/can.hpp
src/drivers/uavcan/uavcan_drivers/stm32/driver/src/uc_stm32_can.cpp