PX4 Firmware: tfmini Namespace Reference
tfmini Namespace Reference
Local functions in support of the shell command.
Functions
void start (const char *port, uint8_t rotation)
Start the driver.
void stop ()
Stop the driver.
void test ()
Perform some basic functional tests on the driver; make sure we can collect data from the sensor in polled and automatic modes.
void reset ()
Reset the driver.
void info ()
Print a little info about the driver.
void usage ()
Print a little info on how to use the driver.
Variables
TFMINI * g_dev
Detailed Description
Local functions in support of the shell command.
Function Documentation
void tfmini::info ()
Print a little info about the driver.
Print a little info about the driver.
Definition at line 880 of file tfmini.cpp.
References errx, and TFMINI::print_info().
Referenced by tfmini_main().
void tfmini::reset ()
Reset the driver.
Reset the driver.
Definition at line 857 of file tfmini.cpp.
References err, fd, px4_ioctl(), px4_open(), RANGE_FINDER0_DEVICE_PATH, SENSOR_POLLRATE_DEFAULT, SENSORIOCRESET, and SENSORIOCSPOLLRATE.
Referenced by tfmini_main().
void tfmini::start (const char * port, uint8_t rotation)
Start the driver.
Definition at line 728 of file tfmini.cpp.
References errx, fd, g_dev, TFMINI::init(), OK, px4_ioctl(), px4_open(), RANGE_FINDER0_DEVICE_PATH, SENSOR_POLLRATE_DEFAULT, SENSORIOCSPOLLRATE, TFMINI::TFMINI(), and warnx.
Referenced by tfmini_main().
void tfmini::stop ()
Stop the driver.
Stop the driver.
Definition at line 774 of file tfmini.cpp.
References errx, g_dev, and warnx.
Referenced by tfmini_main().
void tfmini::test ()
Perform some basic functional tests on the driver; make sure we can collect data from the sensor in polled and automatic modes.
Definition at line 795 of file tfmini.cpp.
References err, errx, fd, OK, px4_ioctl(), px4_open(), px4_poll(), px4_read(), RANGE_FINDER0_DEVICE_PATH, SENSOR_POLLRATE_DEFAULT, SENSORIOCSPOLLRATE, and warnx.
Referenced by tfmini_main().
void tfmini::usage (void)
Print a little info on how to use the driver.
Prints info about the driver argument usage.
Definition at line 896 of file tfmini.cpp.
Referenced by tfmini_main().
Variable Documentation
TFMINI* tfmini::g_dev
Definition at line 715 of file tfmini.cpp.
Referenced by start(), and stop().