PX4 Firmware: VirtualCanDriver::Event Class Reference
VirtualCanDriver::Event Class Reference
Public Member Functions
int init ()
int deinit ()
Event ()
~Event ()
void waitFor (uavcan::MonotonicDuration duration)
void signal ()
Private Attributes
FAR px4_sem_t sem
Detailed Description
Definition at line 345 of file uavcan_virtual_can_driver.hpp.
Constructor & Destructor Documentation
VirtualCanDriver::Event::Event () inline
Definition at line 369 of file uavcan_virtual_can_driver.hpp.
VirtualCanDriver::Event::~Event () inline
Definition at line 373 of file uavcan_virtual_can_driver.hpp.
Member Function Documentation
int VirtualCanDriver::Event::deinit () inline
Definition at line 363 of file uavcan_virtual_can_driver.hpp.
References px4_sem_destroy.
Referenced by VirtualCanDriver::~VirtualCanDriver().
int VirtualCanDriver::Event::init () inline
Definition at line 352 of file uavcan_virtual_can_driver.hpp.
References px4_sem_init, px4_sem_setprotocol, and SEM_PRIO_NONE.
Referenced by VirtualCanDriver::VirtualCanDriver().
void VirtualCanDriver::Event::signal () inline
Definition at line 401 of file uavcan_virtual_can_driver.hpp.
References px4_sem_getvalue, and px4_sem_post.
Referenced by VirtualCanDriver::handleRxFrame(), and VirtualCanDriver::injectTxFramesInto().
void VirtualCanDriver::Event::waitFor (uavcan::MonotonicDuration duration) inline
Definition at line 381 of file uavcan_virtual_can_driver.hpp.
References clock_gettime(), and px4_sem_timedwait.
Referenced by VirtualCanDriver::select().
Member Data Documentation
FAR px4_sem_t VirtualCanDriver::Event::sem private
Definition at line 347 of file uavcan_virtual_can_driver.hpp.
The documentation for this class was generated from the following file:
src/modules/uavcan/uavcan_virtual_can_driver.hpp