PX4 Firmware: src/lib/systemlib/mavlink_log.cpp File Reference
mavlink_log.cpp File Reference
#include <drivers/drv_hrt.h>
#include <px4_platform_common/posix.h>
#include <string.h>
#include <stdlib.h>
#include <stdio.h>
#include <stdarg.h>
#include <uORB/topics/mavlink_log.h>
#include "mavlink_log.h"
Functions
__EXPORT void mavlink_vasprintf (int severity, orb_advert_t *mavlink_log_pub, const char *fmt,...)
Function Documentation
mavlink_vasprintf()
__EXPORT void mavlink_vasprintf (int severity, orb_advert_t * mavlink_log_pub, const char * fmt, ...)
Definition at line 51 of file mavlink_log.cpp.
References hrt_absolute_time(), orb_advertise_queue(), ORB_ID, orb_publish(), mavlink_log_s::severity, mavlink_log_s::text, and mavlink_log_s::timestamp.