PX4 Firmware: src/lib/ecl/geo/geo.h File Reference
geo.h File Reference
Definition of geo / math functions to perform geodesic calculations.
#include <stdbool.h>
#include <stdint.h>
Classes
struct crosstrack_error_s
struct map_projection_reference_s
struct globallocal_converter_reference_s
Functions
bool map_projection_global_initialized ()
Checks if global projection was initialized.
bool map_projection_initialized (const struct map_projection_reference_s *ref)
Checks if projection given as argument was initialized.
uint64_t map_projection_global_timestamp (void)
Get the timestamp of the global map projection.
uint64_t map_projection_timestamp (const struct map_projection_reference_s *ref)
Get the timestamp of the map projection given by the argument.
int map_projection_global_reference (double *ref_lat_rad, double *ref_lon_rad)
Writes the reference values of the global projection to ref_lat and ref_lon.
int map_projection_reference (const struct map_projection_reference_s *ref, double *ref_lat_rad, double *ref_lon_rad)
Writes the reference values of the projection given by the argument to ref_lat and ref_lon.
int map_projection_global_init (double lat_0, double lon_0, uint64_t timestamp)
Initializes the global map transformation.
int map_projection_init_timestamped (struct map_projection_reference_s *ref, double lat_0, double lon_0, uint64_t timestamp)
Initializes the map transformation given by the argument.
int map_projection_init (struct map_projection_reference_s *ref, double lat_0, double lon_0)
Initializes the map transformation given by the argument and sets the timestamp to now.
int map_projection_global_project (double lat, double lon, float *x, float *y)
Transforms a point in the geographic coordinate system to the local azimuthal equidistant plane using the global projection.
int map_projection_project (const struct map_projection_reference_s *ref, double lat, double lon, float *x, float *y)
int map_projection_global_reproject (float x, float y, double *lat, double *lon)
Transforms a point in the local azimuthal equidistant plane to the geographic coordinate system using the global projection.
int map_projection_reproject (const struct map_projection_reference_s *ref, float x, float y, double *lat, double *lon)
Transforms a point in the local azimuthal equidistant plane to the geographic coordinate system using the projection given by the argument.
int map_projection_global_getref (double *lat_0, double *lon_0)
Get reference position of the global map projection.
int globallocalconverter_init (double lat_0, double lon_0, float alt_0, uint64_t timestamp)
Initialize the global mapping between global position (spherical) and local position (NED).
bool globallocalconverter_initialized (void)
Checks if globallocalconverter was initialized.
int globallocalconverter_tolocal (double lat, double lon, float alt, float *x, float *y, float *z)
Convert from global position coordinates to local position coordinates using the global reference.
int globallocalconverter_toglobal (float x, float y, float z, double *lat, double *lon, float *alt)
Convert from local position coordinates to global position coordinates using the global reference.
int globallocalconverter_getref (double *lat_0, double *lon_0, float *alt_0)
Get reference position of the global to local converter.
float get_distance_to_next_waypoint (double lat_now, double lon_now, double lat_next, double lon_next)
Returns the distance to the next waypoint in meters.
void create_waypoint_from_line_and_dist (double lat_A, double lon_A, double lat_B, double lon_B, float dist, double *lat_target, double *lon_target)
Creates a new waypoint C on the line of two given waypoints (A, B) at certain distance from waypoint A.
void waypoint_from_heading_and_distance (double lat_start, double lon_start, float bearing, float dist, double *lat_target, double *lon_target)
Creates a waypoint from given waypoint, distance and bearing see http://www.movable-type.co.uk/scripts/latlong.html.
float get_bearing_to_next_waypoint (double lat_now, double lon_now, double lat_next, double lon_next)
Returns the bearing to the next waypoint in radians.
void get_vector_to_next_waypoint (double lat_now, double lon_now, double lat_next, double lon_next, float *v_n, float *v_e)
void get_vector_to_next_waypoint_fast (double lat_now, double lon_now, double lat_next, double lon_next, float *v_n, float *v_e)
void add_vector_to_global_position (double lat_now, double lon_now, float v_n, float v_e, double *lat_res, double *lon_res)
int get_distance_to_line (struct crosstrack_error_s *crosstrack_error, double lat_now, double lon_now, double lat_start, double lon_start, double lat_end, double lon_end)
int get_distance_to_arc (struct crosstrack_error_s *crosstrack_error, double lat_now, double lon_now, double lat_center, double lon_center, float radius, float arc_start_bearing, float arc_sweep)
float get_distance_to_point_global_wgs84 (double lat_now, double lon_now, float alt_now, double lat_next, double lon_next, float alt_next, float *dist_xy, float *dist_z)
float mavlink_wpm_distance_to_point_local (float x_now, float y_now, float z_now, float x_next, float y_next, float z_next, float *dist_xy, float *dist_z)
Variables
static constexpr float CONSTANTS_ONE_G = 9.80665f
static constexpr float CONSTANTS_STD_PRESSURE_PA = 101325.0f
static constexpr float CONSTANTS_STD_PRESSURE_KPA = CONSTANTS_STD_PRESSURE_PA / 1000.0f
static constexpr float CONSTANTS_STD_PRESSURE_MBAR = CONSTANTS_STD_PRESSURE_PA / 100.0f
static constexpr float CONSTANTS_AIR_DENSITY_SEA_LEVEL_15C = 1.225f
static constexpr float CONSTANTS_AIR_GAS_CONST = 287.1f
static constexpr float CONSTANTS_ABSOLUTE_NULL_CELSIUS = -273.15f
static constexpr double CONSTANTS_RADIUS_OF_EARTH = 6371000
static constexpr float CONSTANTS_RADIUS_OF_EARTH_F = CONSTANTS_RADIUS_OF_EARTH
static constexpr float CONSTANTS_EARTH_SPIN_RATE = 7.2921150e-5f
Detailed Description
Definition of geo / math functions to perform geodesic calculations.
Author
Thomas Gubler thoma.nosp@m.sgub.nosp@m.ler@s.nosp@m.tude.nosp@m.nt.et.nosp@m.hz.c.nosp@m.h
Julian Oes joes@.nosp@m.stud.nosp@m.ent.e.nosp@m.thz..nosp@m.ch
Lorenz Meier lm@in.nosp@m.f.et.nosp@m.hz.ch
Anton Babushkin anton.nosp@m..bab.nosp@m.ushki.nosp@m.n@me.nosp@m..com Additional functions -
Doug Weibel dougl.nosp@m.as.w.nosp@m.eibel.nosp@m.@col.nosp@m.orado.nosp@m..edu
Definition in file geo.h.
Function Documentation
add_vector_to_global_position()
void add_vector_to_global_position (double lat_now, double lon_now, float v_n, float v_e, double * lat_res, double * lon_res)
Definition at line 364 of file geo.cpp.
References CONSTANTS_RADIUS_OF_EARTH, matrix::cos(), math::degrees(), and math::radians().
Referenced by Ekf2::apply_gps_offsets(), Ekf2::calc_gps_blend_output(), and Ekf2::update_gps_blend_states().
create_waypoint_from_line_and_dist()
void create_waypoint_from_line_and_dist (double lat_A, double lon_A, double lat_B, double lon_B, float dist, double * lat_target, double * lon_target)
Creates a new waypoint C on the line of two given waypoints (A, B) at certain distance from waypoint A.
Parameters
lat_A waypoint A latitude in degrees (47.1234567°, not 471234567°)
lon_A waypoint A longitude in degrees (8.1234567°, not 81234567°)
lat_B waypoint B latitude in degrees (47.1234567°, not 471234567°)
lon_B waypoint B longitude in degrees (8.1234567°, not 81234567°)
dist distance of target waypoint from waypoint A in meters (can be negative)
lat_target latitude of target waypoint C in degrees (47.1234567°, not 471234567°)
lon_target longitude of target waypoint C in degrees (47.1234567°, not 471234567°)
Definition at line 285 of file geo.cpp.
References FLT_EPSILON, get_bearing_to_next_waypoint(), M_PI_F, waypoint_from_heading_and_distance(), and matrix::wrap_2pi().
Referenced by FixedwingPositionControl::control_landing(), and FixedwingPositionControl::get_waypoint_heading_distance().
get_bearing_to_next_waypoint()
float get_bearing_to_next_waypoint (double lat_now, double lon_now, double lat_next, double lon_next)
Returns the bearing to the next waypoint in radians.
Parameters
lat_now current position in degrees (47.1234567°, not 471234567°)
lon_now current position in degrees (8.1234567°, not 81234567°)
lat_next next waypoint position in degrees (47.1234567°, not 471234567°)
lon_next next waypoint position in degrees (8.1234567°, not 81234567°)
Definition at line 320 of file geo.cpp.
References matrix::cos(), math::radians(), matrix::sin(), and matrix::wrap_pi().
Referenced by vmount::OutputBase::_handle_position_update(), build_gps_response(), FixedwingPositionControl::control_landing(), create_waypoint_from_line_and_dist(), get_distance_to_arc(), get_distance_to_line(), Mission::heading_sp_update(), MissionBlock::is_mission_item_reached(), ECL_L1_Pos_Controller::navigate_loiter(), ECL_L1_Pos_Controller::navigate_waypoints(), FollowTarget::on_active(), Mission::set_align_mission_item(), Mission::set_mission_items(), and RTL::set_rtl_item().
get_distance_to_arc()
int get_distance_to_arc (struct crosstrack_error_s * crosstrack_error, double lat_now, double lon_now, double lat_center, double lon_center, float radius, float arc_start_bearing, float arc_sweep)
Definition at line 419 of file geo.cpp.
References crosstrack_error_s::bearing, matrix::cos(), crosstrack_error_s::distance, f(), get_bearing_to_next_waypoint(), get_distance_to_next_waypoint(), M_PI_F, crosstrack_error_s::past_end, matrix::sin(), and matrix::wrap_pi().
get_distance_to_line()
int get_distance_to_line (struct crosstrack_error_s * crosstrack_error, double lat_now, double lon_now, double lat_start, double lon_start, double lat_end, double lon_end)
Definition at line 375 of file geo.cpp.
References crosstrack_error_s::bearing, crosstrack_error_s::distance, f(), get_bearing_to_next_waypoint(), get_distance_to_next_waypoint(), crosstrack_error_s::past_end, and matrix::wrap_pi().
Referenced by Navigator::check_traffic().
get_distance_to_next_waypoint()
float get_distance_to_next_waypoint (double lat_now, double lon_now, double lat_next, double lon_next)
Returns the distance to the next waypoint in meters.
Parameters
lat_now current position in degrees (47.1234567°, not 471234567°)
lon_now current position in degrees (8.1234567°, not 81234567°)
lat_next next waypoint position in degrees (47.1234567°, not 471234567°)
lon_next next waypoint position in degrees (8.1234567°, not 81234567°)
Definition at line 270 of file geo.cpp.
References matrix::atan2(), CONSTANTS_RADIUS_OF_EARTH, matrix::cos(), math::radians(), matrix::sin(), and matrix::sqrt().
Referenced by Mission::altitude_sp_foh_update(), build_gps_response(), RTL::calculate_return_alt_from_cone_half_angle(), MissionFeasibilityChecker::checkDistancesBetweenWaypoints(), MissionFeasibilityChecker::checkDistanceToFirstWaypoint(), MissionFeasibilityChecker::checkFixedWingLanding(), FixedwingPositionControl::control_landing(), RoverPositionControl::control_position(), FixedwingPositionControl::control_position(), Mission::do_need_move_to_land(), Mission::do_need_move_to_takeoff(), get_distance_to_arc(), get_distance_to_line(), Mission::heading_sp_update(), MissionBlock::is_mission_item_reached(), RoverPositionControl::run(), PrecLand::run_state_start(), Mission::set_mission_items(), RTL::set_rtl_item(), and FixedwingPositionControl::status_publish().
get_distance_to_point_global_wgs84()
float get_distance_to_point_global_wgs84 (double lat_now, double lon_now, float alt_now, double lat_next, double lon_next, float alt_next, float * dist_xy, float * dist_z)
Definition at line 523 of file geo.cpp.
References matrix::atan2(), CONSTANTS_RADIUS_OF_EARTH, matrix::cos(), M_PI, matrix::sin(), and matrix::sqrt().
Referenced by Navigator::check_traffic(), Geofence::checkAll(), Mission::index_closest_mission_item(), and MissionBlock::is_mission_item_reached().
get_vector_to_next_waypoint()
void get_vector_to_next_waypoint (double lat_now, double lon_now, double lat_next, double lon_next, float * v_n, float * v_e)
Definition at line 337 of file geo.cpp.
References CONSTANTS_RADIUS_OF_EARTH, matrix::cos(), math::radians(), and matrix::sin().
Referenced by Ekf2::calc_gps_blend_output(), Ekf2::update_gps_blend_states(), and Ekf2::update_gps_offsets().
get_vector_to_next_waypoint_fast()
void get_vector_to_next_waypoint_fast (double lat_now, double lon_now, double lat_next, double lon_next, float * v_n, float * v_e)
Definition at line 349 of file geo.cpp.
References CONSTANTS_RADIUS_OF_EARTH, matrix::cos(), and math::radians().
globallocalconverter_getref()
int globallocalconverter_getref (double * lat_0, double * lon_0, float * alt_0)
Get reference position of the global to local converter.
Definition at line 253 of file geo.cpp.
References globallocal_converter_reference_s::alt, map_projection_global_getref(), and map_projection_global_initialized().
Referenced by BlockLocalPositionEstimator::mocapInit(), and BlockLocalPositionEstimator::visionInit().
globallocalconverter_init()
int globallocalconverter_init (double lat_0, double lon_0, float alt_0, uint64_t timestamp)
Initialize the global mapping between global position (spherical) and local position (NED).
Definition at line 211 of file geo.cpp.
References globallocal_converter_reference_s::alt, globallocal_converter_reference_s::init_done, and map_projection_global_init().
Referenced by FlightTask::_evaluateVehicleLocalPosition(), MavlinkReceiver::handle_message_gps_global_origin(), MavlinkReceiver::handle_message_set_position_target_global_int(), RoverPositionControl::run(), and FixedwingPositionControl::Run().
globallocalconverter_initialized()
bool globallocalconverter_initialized (void)
Checks if globallocalconverter was initialized.
Returns
true if map was initialized before, false else
Definition at line 224 of file geo.cpp.
References globallocal_converter_reference_s::init_done, and map_projection_global_initialized().
Referenced by MavlinkReceiver::handle_message_gps_global_origin(), MavlinkReceiver::handle_message_set_position_target_global_int(), BlockLocalPositionEstimator::mocapInit(), RoverPositionControl::run(), FixedwingPositionControl::Run(), and BlockLocalPositionEstimator::visionInit().
globallocalconverter_toglobal()
int globallocalconverter_toglobal (float x, float y, float z, double * lat, double * lon, float * alt)
Convert from local position coordinates to global position coordinates using the global reference.
Definition at line 241 of file geo.cpp.
References globallocal_converter_reference_s::alt, map_projection_global_initialized(), and map_projection_global_reproject().
Referenced by RoverPositionControl::run(), FixedwingPositionControl::Run(), and FlightTaskOrbit::sendTelemetry().
globallocalconverter_tolocal()
int globallocalconverter_tolocal (double lat, double lon, float alt, float * x, float * y, float * z)
Convert from global position coordinates to local position coordinates using the global reference.
Definition at line 229 of file geo.cpp.
References globallocal_converter_reference_s::alt, map_projection_global_initialized(), and map_projection_global_project().
Referenced by FlightTaskOrbit::applyCommandParameters(), and MavlinkReceiver::handle_message_set_position_target_global_int().
map_projection_global_getref()
int map_projection_global_getref (double * lat_0, double * lon_0)
Get reference position of the global map projection.
Definition at line 194 of file geo.cpp.
References math::degrees(), map_projection_reference_s::lat_rad, map_projection_reference_s::lon_rad, map_projection_global_initialized(), and mp_ref.
Referenced by globallocalconverter_getref().
map_projection_global_init()
int map_projection_global_init (double lat_0, double lon_0, uint64_t timestamp)
Initializes the global map transformation.
Initializes the transformation between the geographic coordinate system and the azimuthal equidistant plane
Parameters
lat in degrees (47.1234567°, not 471234567°)
lon in degrees (8.1234567°, not 81234567°)
Definition at line 84 of file geo.cpp.
References map_projection_init_timestamped(), and mp_ref.
Referenced by globallocalconverter_init().
map_projection_global_initialized()
bool map_projection_global_initialized ()
Checks if global projection was initialized.
Returns
true if map was initialized before, false else
Definition at line 63 of file geo.cpp.
References map_projection_initialized(), and mp_ref.
Referenced by globallocalconverter_getref(), globallocalconverter_initialized(), globallocalconverter_toglobal(), globallocalconverter_tolocal(), and map_projection_global_getref().
map_projection_global_project()
int map_projection_global_project (double lat, double lon, float * x, float * y)
Transforms a point in the geographic coordinate system to the local azimuthal equidistant plane using the global projection.
Parameters
x north
y east
lat in degrees (47.1234567°, not 471234567°)
lon in degrees (8.1234567°, not 81234567°)
Returns
0 if map_projection_init was called before, -1 else
Definition at line 127 of file geo.cpp.
References map_projection_project(), and mp_ref.
Referenced by globallocalconverter_tolocal().
map_projection_global_reference()
int map_projection_global_reference (double * ref_lat_rad, double * ref_lon_rad)
Writes the reference values of the global projection to ref_lat and ref_lon.
Returns
0 if map_projection_init was called before, -1 else
Definition at line 110 of file geo.cpp.
References map_projection_reference(), and mp_ref.
map_projection_global_reproject()
int map_projection_global_reproject (float x, float y, double * lat, double * lon)
Transforms a point in the local azimuthal equidistant plane to the geographic coordinate system using the global projection.
Parameters
x north
y east
lat in degrees (47.1234567°, not 471234567°)
lon in degrees (8.1234567°, not 81234567°)
Returns
0 if map_projection_init was called before, -1 else
Definition at line 161 of file geo.cpp.
References map_projection_reproject(), and mp_ref.
Referenced by globallocalconverter_toglobal().
map_projection_global_timestamp()
uint64_t map_projection_global_timestamp (void)
Get the timestamp of the global map projection.
Returns
the timestamp of the map_projection
Definition at line 73 of file geo.cpp.
References map_projection_timestamp(), and mp_ref.
map_projection_init()
int map_projection_init (struct map_projection_reference_s * ref, double lat_0, double lon_0)
Initializes the map transformation given by the argument and sets the timestamp to now.
Initializes the transformation between the geographic coordinate system and the azimuthal equidistant plane
Parameters
lat in degrees (47.1234567°, not 471234567°)
lon in degrees (8.1234567°, not 81234567°)
Definition at line 105 of file geo.cpp.
References ecl_absolute_time, and map_projection_init_timestamped().
Referenced by vmount::OutputBase::_calculate_pitch(), FlightTaskAuto::_evaluateGlobalReference(), BlockLocalPositionEstimator::gpsInit(), Commander::handle_command(), MavlinkReceiver::handle_message_hil_state_quaternion(), Simulator::handle_message_hil_state_quaternion(), Geofence::insideCircle(), BlockLocalPositionEstimator::mocapInit(), PrecLand::on_activation(), FollowTarget::on_active(), BlockLocalPositionEstimator::Run(), and BlockLocalPositionEstimator::visionInit().
map_projection_init_timestamped()
int map_projection_init_timestamped (struct map_projection_reference_s * ref, double lat_0, double lon_0, uint64_t timestamp)
Initializes the map transformation given by the argument.
Initializes the transformation between the geographic coordinate system and the azimuthal equidistant plane
Parameters
lat in degrees (47.1234567°, not 471234567°)
lon in degrees (8.1234567°, not 81234567°)
Definition at line 90 of file geo.cpp.
References matrix::cos(), map_projection_reference_s::cos_lat, map_projection_reference_s::init_done, map_projection_reference_s::lat_rad, map_projection_reference_s::lon_rad, math::radians(), matrix::sin(), map_projection_reference_s::sin_lat, and map_projection_reference_s::timestamp.
Referenced by Ekf::collect_gps(), Ekf::gps_is_good(), map_projection_global_init(), and map_projection_init().
map_projection_initialized()
bool map_projection_initialized (const struct map_projection_reference_s * ref)
Checks if projection given as argument was initialized.
Returns
true if map was initialized before, false else
Definition at line 68 of file geo.cpp.
References map_projection_reference_s::init_done.
Referenced by vmount::OutputBase::_calculate_pitch(), Geofence::insideCircle(), map_projection_global_initialized(), map_projection_project(), map_projection_reference(), map_projection_reproject(), and PrecLand::on_activation().
map_projection_project()
int map_projection_project (const struct map_projection_reference_s * ref, double lat, double lon, float * x, float * y)
Definition at line 132 of file geo.cpp.
References matrix::acos(), CONSTANTS_RADIUS_OF_EARTH, math::constrain(), matrix::cos(), map_projection_reference_s::cos_lat, map_projection_reference_s::lon_rad, map_projection_initialized(), math::radians(), matrix::sin(), and map_projection_reference_s::sin_lat.
Referenced by vmount::OutputBase::_calculate_pitch(), FlightTaskAuto::_evaluateTriplets(), Ekf::gps_is_good(), BlockLocalPositionEstimator::gpsCorrect(), Commander::handle_command(), MavlinkReceiver::handle_message_hil_state_quaternion(), Simulator::handle_message_hil_state_quaternion(), Geofence::insideCircle(), map_projection_global_project(), FollowTarget::on_active(), EstimatorInterface::setGpsData(), and PrecLand::slewrate().
map_projection_reference()
int map_projection_reference (const struct map_projection_reference_s * ref, double * ref_lat_rad, double * ref_lon_rad)
Writes the reference values of the projection given by the argument to ref_lat and ref_lon.
Returns
0 if map_projection_init was called before, -1 else
Definition at line 115 of file geo.cpp.
References map_projection_reference_s::lat_rad, map_projection_reference_s::lon_rad, and map_projection_initialized().
Referenced by map_projection_global_reference().
map_projection_reproject()
int map_projection_reproject (const struct map_projection_reference_s * ref, float x, float y, double * lat, double * lon)
Transforms a point in the local azimuthal equidistant plane to the geographic coordinate system using the projection given by the argument.
Parameters
x north
y east
lat in degrees (47.1234567°, not 471234567°)
lon in degrees (8.1234567°, not 81234567°)
Returns
0 if map_projection_init was called before, -1 else
Definition at line 166 of file geo.cpp.
References matrix::asin(), matrix::atan2(), CONSTANTS_RADIUS_OF_EARTH, matrix::cos(), map_projection_reference_s::cos_lat, math::degrees(), map_projection_reference_s::lat_rad, map_projection_reference_s::lon_rad, map_projection_initialized(), matrix::sin(), map_projection_reference_s::sin_lat, and matrix::sqrt().
Referenced by Ekf::collect_gps(), BlockLocalPositionEstimator::gpsInit(), map_projection_global_reproject(), FollowTarget::on_active(), BlockLocalPositionEstimator::publishGlobalPos(), Ekf2::Run(), PrecLand::run_state_descend_above_target(), and PrecLand::run_state_horizontal_approach().
map_projection_timestamp()
uint64_t map_projection_timestamp (const struct map_projection_reference_s * ref)
Get the timestamp of the map projection given by the argument.
Returns
the timestamp of the map_projection
Definition at line 78 of file geo.cpp.
References map_projection_reference_s::timestamp.
Referenced by map_projection_global_timestamp().
mavlink_wpm_distance_to_point_local()
float mavlink_wpm_distance_to_point_local (float x_now, float y_now, float z_now, float x_next, float y_next, float z_next, float * dist_xy, float * dist_z)
Definition at line 547 of file geo.cpp.
Referenced by Commander::run().
waypoint_from_heading_and_distance()
void waypoint_from_heading_and_distance (double lat_start, double lon_start, float bearing, float dist, double * lat_target, double * lon_target)
Creates a waypoint from given waypoint, distance and bearing see http://www.movable-type.co.uk/scripts/latlong.html.
Parameters
lat_start latitude of starting waypoint in degrees (47.1234567°, not 471234567°)
lon_start longitude of starting waypoint in degrees (8.1234567°, not 81234567°)
bearing in rad
distance in meters
lat_target latitude of target waypoint in degrees (47.1234567°, not 471234567°)
lon_target longitude of target waypoint in degrees (47.1234567°, not 471234567°)
Definition at line 303 of file geo.cpp.
References matrix::asin(), matrix::atan2(), CONSTANTS_RADIUS_OF_EARTH, matrix::cos(), math::degrees(), math::radians(), matrix::sin(), and matrix::wrap_2pi().
Referenced by Navigator::check_traffic(), create_waypoint_from_line_and_dist(), Navigator::fake_traffic(), Mission::generate_waypoint_from_heading(), FixedwingPositionControl::get_waypoint_heading_distance(), and MissionBlock::is_mission_item_reached().
Variable Documentation
CONSTANTS_ABSOLUTE_NULL_CELSIUS
constexpr float CONSTANTS_ABSOLUTE_NULL_CELSIUS = -273.15f static
Definition at line 59 of file geo.h.
Referenced by sensors::VotedSensorsUpdate::baroPoll(), get_air_density(), Sih::reconstruct_sensors_signals(), and BATT_SMBUS::Run().
CONSTANTS_AIR_DENSITY_SEA_LEVEL_15C
constexpr float CONSTANTS_AIR_DENSITY_SEA_LEVEL_15C = 1.225f static
Definition at line 57 of file geo.h.
Referenced by calc_EAS_from_TAS(), calc_IAS(), calc_IAS_corrected(), calc_TAS(), and calc_TAS_from_EAS().
CONSTANTS_AIR_GAS_CONST
constexpr float CONSTANTS_AIR_GAS_CONST = 287.1f static
Definition at line 58 of file geo.h.
Referenced by sensors::VotedSensorsUpdate::baroPoll(), get_air_density(), and Sih::reconstruct_sensors_signals().
CONSTANTS_EARTH_SPIN_RATE
constexpr float CONSTANTS_EARTH_SPIN_RATE = 7.2921150e-5f static
Definition at line 64 of file geo.h.
Referenced by Ekf::calcEarthRateNED().
CONSTANTS_ONE_G
constexpr float CONSTANTS_ONE_G = 9.80665f static
Definition at line 51 of file geo.h.
Referenced by TECS::_update_energy_estimates(), TECS::_update_pitch_setpoint(), TECS::_update_STE_rate_lim(), FXOS8701CQ::accel_set_range(), LSM303D::accel_set_range(), ADIS16477::ADIS16477(), ADIS16497::ADIS16497(), sensors::VotedSensorsUpdate::baroPoll(), Ekf::calculateOutputStates(), ECL_YawController::control_attitude_impl_openloop(), Ekf::controlOpticalFlowFusion(), detect_orientation(), do_accel_calibration_measurements(), Ekf::fixCovarianceErrors(), MavlinkReceiver::handle_message_hil_sensor(), MavlinkReceiver::handle_message_hil_state_quaternion(), Sih::parameters_updated(), TerrainEstimator::predict(), BlockLocalPositionEstimator::predict(), Ekf::predictState(), Sih::reconstruct_sensors_signals(), Ekf2::Run(), MavlinkStreamScaledIMU::send(), MavlinkStreamScaledIMU2::send(), MavlinkStreamScaledIMU3::send(), BMI055_accel::set_accel_range(), BMI088_accel::set_accel_range(), BMI160::set_accel_range(), MPU9250::set_accel_range(), MPU6000::set_accel_range(), ICM20948::set_accel_range(), BMA180::set_range(), TEST_F(), AttitudeEstimatorQ::update(), ECL_L1_Pos_Controller::update_roll_setpoint(), TECS::update_vehicle_state_estimates(), and EkfInitializationTest::update_with_const_sensors().
CONSTANTS_RADIUS_OF_EARTH
constexpr double CONSTANTS_RADIUS_OF_EARTH = 6371000 static
Definition at line 61 of file geo.h.
Referenced by add_vector_to_global_position(), get_distance_to_next_waypoint(), get_distance_to_point_global_wgs84(), ECL_L1_Pos_Controller::get_local_planar_vector(), get_vector_to_next_waypoint(), get_vector_to_next_waypoint_fast(), map_projection_project(), map_projection_reproject(), Sih::reconstruct_sensors_signals(), and waypoint_from_heading_and_distance().
CONSTANTS_RADIUS_OF_EARTH_F
constexpr float CONSTANTS_RADIUS_OF_EARTH_F = CONSTANTS_RADIUS_OF_EARTH static
Definition at line 62 of file geo.h.
CONSTANTS_STD_PRESSURE_KPA
constexpr float CONSTANTS_STD_PRESSURE_KPA = CONSTANTS_STD_PRESSURE_PA / 1000.0f static
Definition at line 54 of file geo.h.
CONSTANTS_STD_PRESSURE_MBAR
constexpr float CONSTANTS_STD_PRESSURE_MBAR = CONSTANTS_STD_PRESSURE_PA / 100.0f static
Definition at line 55 of file geo.h.
Referenced by Sih::reconstruct_sensors_signals(), and FixedwingPositionControl::tecs_update_pitch_throttle().
CONSTANTS_STD_PRESSURE_PA
constexpr float CONSTANTS_STD_PRESSURE_PA = 101325.0f static
Definition at line 53 of file geo.h.