var dir_f696c229fe92b12fffa452a8a0da93d0 =
[
    [ "vehicle_acceleration", "dir_b5d316b56d914b486dc21adc7862fb63.html", "dir_b5d316b56d914b486dc21adc7862fb63" ],
    [ "vehicle_angular_velocity", "dir_c1a8c3ff4ab765820b7a47a98b6e3c50.html", "dir_c1a8c3ff4ab765820b7a47a98b6e3c50" ],
    [ "common.h", "d1/d27/modules_2sensors_2common_8h.html", "d1/d27/modules_2sensors_2common_8h" ],
    [ "parameters.cpp", "de/d9e/modules_2sensors_2parameters_8cpp.html", "de/d9e/modules_2sensors_2parameters_8cpp" ],
    [ "parameters.h", "df/d3b/sensors_2parameters_8h.html", "df/d3b/sensors_2parameters_8h" ],
    [ "pwm_params_aux.c", "de/d41/pwm__params__aux_8c.html", "de/d41/pwm__params__aux_8c" ],
    [ "pwm_params_main.c", "dd/dcc/pwm__params__main_8c.html", "dd/dcc/pwm__params__main_8c" ],
    [ "sensor_params_acc0.c", "d8/dc5/sensor__params__acc0_8c.html", "d8/dc5/sensor__params__acc0_8c" ],
    [ "sensor_params_acc1.c", "d1/d2c/sensor__params__acc1_8c.html", "d1/d2c/sensor__params__acc1_8c" ],
    [ "sensor_params_acc2.c", "df/dd9/sensor__params__acc2_8c.html", "df/dd9/sensor__params__acc2_8c" ],
    [ "sensor_params_accel.c", "d6/dd3/sensor__params__accel_8c.html", "d6/dd3/sensor__params__accel_8c" ],
    [ "sensor_params_battery.c", "d6/d08/sensors_2sensor__params__battery_8c.html", "d6/d08/sensors_2sensor__params__battery_8c" ],
    [ "sensor_params_flow.c", "db/da2/sensor__params__flow_8c.html", "db/da2/sensor__params__flow_8c" ],
    [ "sensor_params_gyro.c", "d4/dfa/sensor__params__gyro_8c.html", "d4/dfa/sensor__params__gyro_8c" ],
    [ "sensor_params_gyro0.c", "d4/d41/sensor__params__gyro0_8c.html", "d4/d41/sensor__params__gyro0_8c" ],
    [ "sensor_params_gyro1.c", "db/d92/sensor__params__gyro1_8c.html", "db/d92/sensor__params__gyro1_8c" ],
    [ "sensor_params_gyro2.c", "de/da1/sensor__params__gyro2_8c.html", "de/da1/sensor__params__gyro2_8c" ],
    [ "sensor_params_mag.c", "d8/dda/sensor__params__mag_8c.html", "d8/dda/sensor__params__mag_8c" ],
    [ "sensor_params_mag0.c", "d6/de8/sensor__params__mag0_8c.html", "d6/de8/sensor__params__mag0_8c" ],
    [ "sensor_params_mag1.c", "dd/d60/sensor__params__mag1_8c.html", "dd/d60/sensor__params__mag1_8c" ],
    [ "sensor_params_mag2.c", "de/d2b/sensor__params__mag2_8c.html", "de/d2b/sensor__params__mag2_8c" ],
    [ "sensor_params_mag3.c", "d8/d08/sensor__params__mag3_8c.html", "d8/d08/sensor__params__mag3_8c" ],
    [ "sensors.cpp", "d4/d34/sensors_8cpp.html", "d4/d34/sensors_8cpp" ],
    [ "temp_comp_params_accel.c", "df/dbd/temp__comp__params__accel_8c.html", "df/dbd/temp__comp__params__accel_8c" ],
    [ "temp_comp_params_baro.c", "d5/d05/temp__comp__params__baro_8c.html", "d5/d05/temp__comp__params__baro_8c" ],
    [ "temp_comp_params_gyro.c", "de/d17/temp__comp__params__gyro_8c.html", "de/d17/temp__comp__params__gyro_8c" ],
    [ "temperature_compensation.cpp", "d4/d05/temperature__compensation_8cpp.html", null ],
    [ "temperature_compensation.h", "d1/d63/temperature__compensation_8h.html", [
      [ "TemperatureCompensation", "d3/ded/classsensors_1_1_temperature_compensation.html", "d3/ded/classsensors_1_1_temperature_compensation" ],
      [ "SensorCalData1D", "da/d60/structsensors_1_1_temperature_compensation_1_1_sensor_cal_data1_d.html", "da/d60/structsensors_1_1_temperature_compensation_1_1_sensor_cal_data1_d" ],
      [ "SensorCalHandles1D", "db/dae/structsensors_1_1_temperature_compensation_1_1_sensor_cal_handles1_d.html", "db/dae/structsensors_1_1_temperature_compensation_1_1_sensor_cal_handles1_d" ],
      [ "SensorCalData3D", "d7/dda/structsensors_1_1_temperature_compensation_1_1_sensor_cal_data3_d.html", "d7/dda/structsensors_1_1_temperature_compensation_1_1_sensor_cal_data3_d" ],
      [ "SensorCalHandles3D", "db/d33/structsensors_1_1_temperature_compensation_1_1_sensor_cal_handles3_d.html", "db/d33/structsensors_1_1_temperature_compensation_1_1_sensor_cal_handles3_d" ],
      [ "Parameters", "d8/dab/structsensors_1_1_temperature_compensation_1_1_parameters.html", "d8/dab/structsensors_1_1_temperature_compensation_1_1_parameters" ],
      [ "ParameterHandles", "d8/df6/structsensors_1_1_temperature_compensation_1_1_parameter_handles.html", "d8/df6/structsensors_1_1_temperature_compensation_1_1_parameter_handles" ],
      [ "PerSensorData", "d5/dec/structsensors_1_1_temperature_compensation_1_1_per_sensor_data.html", "d5/dec/structsensors_1_1_temperature_compensation_1_1_per_sensor_data" ]
    ] ],
    [ "voted_sensors_update.cpp", "d3/d2f/voted__sensors__update_8cpp.html", "d3/d2f/voted__sensors__update_8cpp" ],
    [ "voted_sensors_update.h", "dd/d59/voted__sensors__update_8h.html", [
      [ "VotedSensorsUpdate", "d9/dc3/classsensors_1_1_voted_sensors_update.html", "d9/dc3/classsensors_1_1_voted_sensors_update" ],
      [ "SensorData", "dc/dfc/structsensors_1_1_voted_sensors_update_1_1_sensor_data.html", "dc/dfc/structsensors_1_1_voted_sensors_update_1_1_sensor_data" ]
    ] ]
];