PX4 Firmware: IUavcanSensorBridge Class Reference
IUavcanSensorBridge Class Reference abstract
A sensor bridge class must implement this interface.
#include <sensor_bridge.hpp>
Public Member Functions
virtual ~IUavcanSensorBridge ()
virtual const char * get_name () const =0
Returns ASCII name of the bridge.
virtual int init ()=0
Starts the bridge.
virtual unsigned get_num_redundant_channels () const =0
Returns number of active redundancy channels.
virtual void print_status () const =0
Prints current status in a human readable format to stdout.
Public Member Functions inherited from ListNode< IUavcanSensorBridge * >
ListNode ()
ListNode (const ListNode &)=delete
ListNode (ListNode &&)=delete
virtual ~ListNode ()=default
ListNode & operator= (const ListNode &)=delete
ListNode & operator= (ListNode &&)=delete
void setSibling (IUavcanSensorBridge *sibling)
const IUavcanSensorBridge * getSibling ()
Static Public Member Functions
static void make_all (uavcan::INode &node, List< IUavcanSensorBridge * > &list)
Sensor bridge factory.
Static Public Attributes
static constexpr unsigned MAX_NAME_LEN = 20
Additional Inherited Members
Protected Attributes inherited from ListNode< IUavcanSensorBridge * >
IUavcanSensorBridge * _sibling
Detailed Description
A sensor bridge class must implement this interface.
Author
Pavel Kirienko pavel.nosp@m..kir.nosp@m.ienko.nosp@m.@gma.nosp@m.il.co.nosp@m.m
Definition at line 48 of file sensor_bridge.hpp.
Constructor & Destructor Documentation
virtual IUavcanSensorBridge::~IUavcanSensorBridge () inline virtual
Definition at line 53 of file sensor_bridge.hpp.
References get_name(), get_num_redundant_channels(), init(), make_all(), and print_status().
Member Function Documentation
virtual const char* IUavcanSensorBridge::get_name () const pure virtual
Returns ASCII name of the bridge.
Implemented in UavcanGnssBridge, UavcanBarometerBridge, and UavcanMagnetometerBridge.
Referenced by ~IUavcanSensorBridge().
virtual unsigned IUavcanSensorBridge::get_num_redundant_channels () const pure virtual
Returns number of active redundancy channels.
Implemented in UavcanCDevSensorBridgeBase, and UavcanGnssBridge.
Referenced by UavcanCDevSensorBridgeBase::UavcanCDevSensorBridgeBase(), and ~IUavcanSensorBridge().
virtual int IUavcanSensorBridge::init () pure virtual
Starts the bridge.
Returns
Non-negative value on success, negative on error.
Implemented in UavcanGnssBridge, UavcanBarometerBridge, and UavcanMagnetometerBridge.
Referenced by ~IUavcanSensorBridge().
void IUavcanSensorBridge::make_all (uavcan::INode & node, List< IUavcanSensorBridge * > & list) static
Sensor bridge factory.
Creates all known sensor bridges and puts them in the linked list.
Author
Pavel Kirienko pavel.nosp@m..kir.nosp@m.ienko.nosp@m.@gma.nosp@m.il.co.nosp@m.m
Definition at line 48 of file sensor_bridge.cpp.
Referenced by UavcanNode::init(), and ~IUavcanSensorBridge().
virtual void IUavcanSensorBridge::print_status () const pure virtual
Prints current status in a human readable format to stdout.
Implemented in UavcanCDevSensorBridgeBase, and UavcanGnssBridge.
Referenced by UavcanCDevSensorBridgeBase::UavcanCDevSensorBridgeBase(), and ~IUavcanSensorBridge().
Member Data Documentation
constexpr unsigned IUavcanSensorBridge::MAX_NAME_LEN = 20 static
Definition at line 51 of file sensor_bridge.hpp.
The documentation for this class was generated from the following files:
src/modules/uavcan/sensors/sensor_bridge.hpp
src/modules/uavcan/sensors/sensor_bridge.cpp