PX4 Firmware: src/modules/gpio_led/gpio_led.c File Reference
gpio_led.c File Reference
Status LED via GPIO driver.
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <fcntl.h>
#include <stdbool.h>
#include <px4_module.h>
#include <px4_log.h>
#include <nuttx/wqueue.h>
#include <nuttx/clock.h>
#include <systemlib/err.h>
#include <uORB/uORB.h>
#include <uORB/topics/vehicle_status.h>
#include <uORB/topics/battery_status.h>
#include <poll.h>
#include <drivers/drv_gpio.h>
#include <modules/px4iofirmware/protocol.h>
Classes
struct gpio_led_s
Macros
#define CYCLE_RATE_HZ 5
#define PIN_NAME "AUX OUT 1"
#define GPIO_MIN_SERVO_PIN 1
Enumerations
enum { Stopped = 0, Running = 1, Falied = 2, Stopping = 3 }
Functions
__EXPORT int gpio_led_main (int argc, char *argv[])
void gpio_led_start (FAR void *arg)
void gpio_led_cycle (FAR void *arg)
static void print_usage (const char *reason)
Variables
static struct gpio_led_s * gpio_led_data
static enum { ... } gpio_led_state = Stopped
Detailed Description
Status LED via GPIO driver.
Author
Anton Babushkin anton.nosp@m..bab.nosp@m.ushki.nosp@m.n@me.nosp@m..com
Definition in file gpio_led.c.
Macro Definition Documentation
#define CYCLE_RATE_HZ 5
Definition at line 61 of file gpio_led.c.
Referenced by gpio_led_cycle(), and gpio_led_main().
#define GPIO_MIN_SERVO_PIN 1
Definition at line 66 of file gpio_led.c.
Referenced by gpio_led_main().
#define PIN_NAME "AUX OUT 1"
Definition at line 63 of file gpio_led.c.
Referenced by gpio_led_main().
Enumeration Type Documentation
anonymous enum
Enumerator
Stopped
Running
Falied
Stopping
Definition at line 113 of file gpio_led.c.
Function Documentation
void gpio_led_cycle (FAR void * arg)
Definition at line 285 of file gpio_led.c.
References vehicle_status_s::arming_state, gpio_led_s::battery_status, BATTERY_STATUS_BATTERY_WARNING_NONE, gpio_led_s::battery_status_sub, gpio_led_s::counter, CYCLE_RATE_HZ, vehicle_status_s::failsafe, GPIO_CLEAR, gpio_led_s::gpio_fd, gpio_led_state, GPIO_SET, gpio_led_s::led_state, orb_check(), orb_copy(), ORB_ID, orb_unsubscribe(), gpio_led_s::pin, Running, Stopped, gpio_led_s::vehicle_status, VEHICLE_STATUS_ARMING_STATE_ARMED, VEHICLE_STATUS_ARMING_STATE_STANDBY, VEHICLE_STATUS_ARMING_STATE_STANDBY_ERROR, gpio_led_s::vehicle_status_sub, battery_status_s::warning, and gpio_led_s::work.
Referenced by gpio_led_start().
int gpio_led_main (int argc, char * argv[])
Definition at line 158 of file gpio_led.c.
References CYCLE_RATE_HZ, gpio_led_start(), gpio_led_state, GPIO_MIN_SERVO_PIN, gpio_led_s::pin, PIN_NAME, print_usage(), PX4_ERR, PX4_INFO, PX4_WARN, Running, Stopped, Stopping, usleep(), and gpio_led_s::work.
void gpio_led_start (FAR void * arg)
Definition at line 242 of file gpio_led.c.
References gpio_led_s::battery_status, gpio_led_s::battery_status_sub, Falied, gpio_led_s::gpio_fd, gpio_led_cycle(), gpio_led_state, GPIO_SET_OUTPUT, ORB_ID, orb_subscribe(), gpio_led_s::pin, PX4_ERR, PX4FMU_DEVICE_PATH, Running, gpio_led_s::vehicle_status, gpio_led_s::vehicle_status_sub, and gpio_led_s::work.
Referenced by gpio_led_main().
static void print_usage (const char * reason) static
Definition at line 126 of file gpio_led.c.
References PRINT_MODULE_DESCRIPTION(), PRINT_MODULE_USAGE_COMMAND, PRINT_MODULE_USAGE_COMMAND_DESCR(), PRINT_MODULE_USAGE_NAME(), PRINT_MODULE_USAGE_PARAM_FLAG(), and PX4_WARN.
Referenced by bl_update_main(), px4::logger::Logger::custom_command(), gpio_led_main(), and mtd_main().
Variable Documentation
struct gpio_led_s* gpio_led_data static
Definition at line 112 of file gpio_led.c.
enum { ... } gpio_led_state
Referenced by gpio_led_cycle(), gpio_led_main(), and gpio_led_start().