PX4 Firmware: WindEstimatorModule Class Reference
WindEstimatorModule Class Reference
Public Member Functions
WindEstimatorModule ()
~WindEstimatorModule ()
void cycle ()
int print_status () override
Public Member Functions inherited from ModuleParams
ModuleParams (ModuleParams *parent)
void setParent (ModuleParams *parent)
Set the parent module.
virtual ~ModuleParams ()=default
ModuleParams (const ModuleParams &)=delete
ModuleParams & operator= (const ModuleParams &)=delete
ModuleParams (ModuleParams &&)=delete
ModuleParams & operator= (ModuleParams &&)=delete
Public Member Functions inherited from ListNode< ModuleParams * >
ListNode ()
ListNode (const ListNode &)=delete
ListNode (ListNode &&)=delete
virtual ~ListNode ()=default
ListNode & operator= (const ListNode &)=delete
ListNode & operator= (ListNode &&)=delete
void setSibling (ModuleParams *sibling)
const ModuleParams * getSibling ()
Static Public Member Functions
static int task_spawn (int argc, char *argv[])
static int custom_command (int argc, char *argv[])
static int print_usage (const char *reason=nullptr)
Private Member Functions
DEFINE_PARAMETERS ((ParamFloat< px4::params::WEST_W_P_NOISE >) wind_p_noise,(ParamFloat< px4::params::WEST_SC_P_NOISE >) tas_scale_p_noise,(ParamFloat< px4::params::WEST_TAS_NOISE >) tas_noise,(ParamFloat< px4::params::WEST_BETA_NOISE >) beta_noise,(ParamInt< px4::params::WEST_TAS_GATE >) airspeed_gate,(ParamInt< px4::params::WEST_BETA_GATE >) sideslip_gate) static void cycle_trampoline(void *arg)
int start ()
void update_params ()
bool subscribe_topics ()
Private Attributes
WindEstimator _wind_estimator
orb_advert_t _wind_est_pub {nullptr}
wind estimate topic
int _vehicle_attitude_sub {-1}
int _vehicle_local_position_sub {-1}
int _airspeed_sub {-1}
int _param_sub {-1}
perf_counter_t _perf_elapsed {}
perf_counter_t _perf_interval {}
int _instance {-1}
Static Private Attributes
static struct work_s _work = {}
Additional Inherited Members
Protected Member Functions inherited from ModuleParams
virtual void updateParams ()
Call this whenever the module gets a parameter change notification.
virtual void updateParamsImpl ()
The implementation for this is generated with the macro DEFINE_PARAMETERS()
Protected Attributes inherited from ListNode< ModuleParams * >
ModuleParams * _sibling
Detailed Description
Definition at line 59 of file wind_estimator_main.cpp.
Constructor & Destructor Documentation
WindEstimatorModule::WindEstimatorModule ()
Definition at line 116 of file wind_estimator_main.cpp.
References _airspeed_sub, _param_sub, _perf_elapsed, _perf_interval, _vehicle_attitude_sub, _vehicle_local_position_sub, ORB_ID, orb_subscribe(), PC_ELAPSED, PC_INTERVAL, perf_alloc_once(), and update_params().
Referenced by task_spawn().
WindEstimatorModule::~WindEstimatorModule ()
Definition at line 131 of file wind_estimator_main.cpp.
References _airspeed_sub, _param_sub, _perf_elapsed, _perf_interval, _vehicle_attitude_sub, _vehicle_local_position_sub, _wind_est_pub, orb_unadvertise(), orb_unsubscribe(), and perf_free().
Member Function Documentation
int WindEstimatorModule::custom_command (int argc, char * argv[]) static
See also
ModuleBase
Definition at line 287 of file wind_estimator_main.cpp.
References is_running(), print_usage(), and task_spawn().
void WindEstimatorModule::cycle ()
Definition at line 185 of file wind_estimator_main.cpp.
References _airspeed_sub, _instance, _param_sub, _perf_elapsed, _perf_interval, _vehicle_attitude_sub, _vehicle_local_position_sub, _wind_est_pub, _wind_estimator, wind_estimate_s::beta_innov, wind_estimate_s::beta_innov_var, vehicle_local_position_s::evh, vehicle_local_position_s::evv, WindEstimator::fuse_airspeed(), WindEstimator::fuse_beta(), WindEstimator::get_beta_innov(), WindEstimator::get_beta_innov_var(), WindEstimator::get_tas_innov(), WindEstimator::get_tas_innov_var(), WindEstimator::get_tas_scale(), WindEstimator::get_wind(), WindEstimator::get_wind_var(), hrt_absolute_time(), hrt_abstime, airspeed_s::indicated_airspeed_m_s, orb_check(), orb_copy(), ORB_ID, ORB_PRIO_DEFAULT, orb_publish_auto(), perf_begin(), perf_count(), perf_end(), PX4_OK, vehicle_attitude_s::q, SCHEDULE_INTERVAL, wind_estimate_s::tas_innov, wind_estimate_s::tas_innov_var, wind_estimate_s::tas_scale, vehicle_local_position_s::timestamp, wind_estimate_s::timestamp, airspeed_s::timestamp, vehicle_attitude_s::timestamp, WindEstimator::update(), update_params(), vehicle_local_position_s::v_xy_valid, wind_estimate_s::variance_east, wind_estimate_s::variance_north, vehicle_local_position_s::vx, vehicle_local_position_s::vy, vehicle_local_position_s::vz, wind_estimate_s::windspeed_east, and wind_estimate_s::windspeed_north.
Referenced by task_spawn().
WindEstimatorModule::DEFINE_PARAMETERS ((ParamFloat< px4::params::WEST_W_P_NOISE >) wind_p_noise, (ParamFloat< px4::params::WEST_SC_P_NOISE >) tas_scale_p_noise, (ParamFloat< px4::params::WEST_TAS_NOISE >) tas_noise, (ParamFloat< px4::params::WEST_BETA_NOISE >) beta_noise, (ParamInt< px4::params::WEST_TAS_GATE >) airspeed_gate, (ParamInt< px4::params::WEST_BETA_GATE >) sideslip_gate) private
int WindEstimatorModule::print_status () override
Definition at line 324 of file wind_estimator_main.cpp.
References _instance, _perf_elapsed, _perf_interval, instance, ORB_ID, perf_print_counter(), PX4_INFO, and wind_estimator_main().
int WindEstimatorModule::print_usage (const char * reason = nullptr) static
See also
ModuleBase
Definition at line 300 of file wind_estimator_main.cpp.
References PRINT_MODULE_DESCRIPTION(), PRINT_MODULE_USAGE_COMMAND, PRINT_MODULE_USAGE_DEFAULT_COMMANDS, PRINT_MODULE_USAGE_NAME(), and PX4_WARN.
Referenced by custom_command().
int WindEstimatorModule::start () private
bool WindEstimatorModule::subscribe_topics () private
int WindEstimatorModule::task_spawn (int argc, char * argv[]) static
See also
ModuleBase
Definition at line 145 of file wind_estimator_main.cpp.
References cycle(), PX4_ERR, PX4_ERROR, PX4_OK, and WindEstimatorModule().
Referenced by custom_command().
void WindEstimatorModule::update_params () private
Definition at line 274 of file wind_estimator_main.cpp.
References _wind_estimator, WindEstimator::set_beta_gate(), WindEstimator::set_beta_noise(), WindEstimator::set_tas_gate(), WindEstimator::set_tas_noise(), WindEstimator::set_tas_scale_p_noise(), WindEstimator::set_wind_p_noise(), and ModuleParams::updateParams().
Referenced by cycle(), and WindEstimatorModule().
Member Data Documentation
int WindEstimatorModule::_airspeed_sub {-1} private
Definition at line 89 of file wind_estimator_main.cpp.
Referenced by cycle(), WindEstimatorModule(), and ~WindEstimatorModule().
int WindEstimatorModule::_instance {-1} private
Definition at line 95 of file wind_estimator_main.cpp.
Referenced by cycle(), and print_status().
int WindEstimatorModule::_param_sub {-1} private
Definition at line 90 of file wind_estimator_main.cpp.
Referenced by cycle(), WindEstimatorModule(), and ~WindEstimatorModule().
perf_counter_t WindEstimatorModule::_perf_elapsed {} private
Definition at line 92 of file wind_estimator_main.cpp.
Referenced by cycle(), print_status(), WindEstimatorModule(), and ~WindEstimatorModule().
perf_counter_t WindEstimatorModule::_perf_interval {} private
Definition at line 93 of file wind_estimator_main.cpp.
Referenced by cycle(), print_status(), WindEstimatorModule(), and ~WindEstimatorModule().
int WindEstimatorModule::_vehicle_attitude_sub {-1} private
Definition at line 87 of file wind_estimator_main.cpp.
Referenced by cycle(), WindEstimatorModule(), and ~WindEstimatorModule().
int WindEstimatorModule::_vehicle_local_position_sub {-1} private
Definition at line 88 of file wind_estimator_main.cpp.
Referenced by cycle(), WindEstimatorModule(), and ~WindEstimatorModule().
orb_advert_t WindEstimatorModule::_wind_est_pub {nullptr} private
wind estimate topic
Definition at line 85 of file wind_estimator_main.cpp.
Referenced by cycle(), and ~WindEstimatorModule().
WindEstimator WindEstimatorModule::_wind_estimator private
Definition at line 84 of file wind_estimator_main.cpp.
Referenced by cycle(), and update_params().
work_s WindEstimatorModule::_work = {} static private
Definition at line 82 of file wind_estimator_main.cpp.
The documentation for this class was generated from the following file:
src/modules/wind_estimator/wind_estimator_main.cpp