PX4 Firmware: MavlinkStreamHeartbeat Class Reference
MavlinkStreamHeartbeat Class Reference
Public Member Functions
const char * get_name () const override
uint16_t get_id () override
unsigned get_size () override
Get maximal total messages size on update.
bool const_rate () override
Public Member Functions inherited from MavlinkStream
MavlinkStream (Mavlink *mavlink)
virtual ~MavlinkStream ()=default
MavlinkStream (const MavlinkStream &)=delete
MavlinkStream & operator= (const MavlinkStream &)=delete
MavlinkStream (MavlinkStream &&)=delete
MavlinkStream & operator= (MavlinkStream &&)=delete
void set_interval (const int interval)
Get the interval.
int get_interval ()
Get the interval.
int update (const hrt_abstime &t)
Update subscriptions and send message if necessary.
virtual unsigned get_size_avg ()
Get the average message size.
bool first_message_sent () const
void reset_last_sent ()
Reset the time of last sent to 0.
Public Member Functions inherited from ListNode< MavlinkStream *>
void setSibling (MavlinkStream * sibling)
const MavlinkStream * getSibling () const
Static Public Member Functions
static const char * get_name_static ()
static uint16_t get_id_static ()
static MavlinkStream * new_instance (Mavlink *mavlink)
Protected Member Functions
MavlinkStreamHeartbeat (Mavlink *mavlink)
bool send (const hrt_abstime t) override
Protected Member Functions inherited from MavlinkStream
virtual void update_data ()
Function to collect/update data for the streams at a high rate independant of actual stream rate.
Private Member Functions
MavlinkStreamHeartbeat (MavlinkStreamHeartbeat &)=delete
MavlinkStreamHeartbeat & operator= (const MavlinkStreamHeartbeat &)=delete
Private Attributes
MavlinkOrbSubscription * _status_sub
Additional Inherited Members
Protected Attributes inherited from MavlinkStream
Mavlink *const _mavlink
int _interval {1000000}
if set to negative value = unlimited rate
Protected Attributes inherited from ListNode< MavlinkStream *>
MavlinkStream * _list_node_sibling
Detailed Description
Definition at line 306 of file mavlink_messages.cpp.
Constructor & Destructor Documentation
MavlinkStreamHeartbeat() [1/2]
MavlinkStreamHeartbeat::MavlinkStreamHeartbeat (MavlinkStreamHeartbeat &) private delete
Referenced by new_instance().
MavlinkStreamHeartbeat() [2/2]
MavlinkStreamHeartbeat::MavlinkStreamHeartbeat (Mavlink * mavlink) inline explicit protected
Definition at line 352 of file mavlink_messages.cpp.
Member Function Documentation
const_rate()
bool MavlinkStreamHeartbeat::const_rate () inline override virtual
Returns
true if steam rate shouldn't be adjusted
Reimplemented from MavlinkStream.
Definition at line 339 of file mavlink_messages.cpp.
get_id()
uint16_t MavlinkStreamHeartbeat::get_id () inline override virtual
Implements MavlinkStream.
Definition at line 324 of file mavlink_messages.cpp.
References get_id_static().
get_id_static()
static uint16_t MavlinkStreamHeartbeat::get_id_static () inline static
Definition at line 319 of file mavlink_messages.cpp.
Referenced by get_id(), MavlinkStreamStatustext::get_id(), MavlinkStreamCommandLong::get_id(), MavlinkStreamSysStatus::get_id(), MavlinkStreamBatteryStatus::get_id(), MavlinkStreamHighresIMU::get_id(), MavlinkStreamScaledIMU::get_id(), MavlinkStreamScaledIMU2::get_id(), MavlinkStreamScaledIMU3::get_id(), MavlinkStreamAttitude::get_id(), MavlinkStreamAttitudeQuaternion::get_id(), MavlinkStreamVFRHUD::get_id(), MavlinkStreamGPSRawInt::get_id(), MavlinkStreamGPS2Raw::get_id(), MavlinkStreamSystemTime::get_id(), MavlinkStreamTimesync::get_id(), MavlinkStreamADSBVehicle::get_id(), MavlinkStreamUTMGlobalPosition::get_id(), MavlinkStreamCollision::get_id(), MavlinkStreamCameraTrigger::get_id(), MavlinkStreamCameraImageCaptured::get_id(), MavlinkStreamGlobalPositionInt::get_id(), MavlinkStreamOdometry::get_id(), MavlinkStreamLocalPositionNED::get_id(), MavlinkStreamEstimatorStatus::get_id(), MavlinkStreamAttPosMocap::get_id(), MavlinkStreamHomePosition::get_id(), MavlinkStreamServoOutputRaw< N >::get_id(), MavlinkStreamActuatorControlTarget< N >::get_id(), MavlinkStreamHILActuatorControls::get_id(), MavlinkStreamPositionTargetGlobalInt::get_id(), MavlinkStreamLocalPositionSetpoint::get_id(), MavlinkStreamAttitudeTarget::get_id(), MavlinkStreamRCChannels::get_id(), MavlinkStreamManualControl::get_id(), MavlinkStreamTrajectoryRepresentationWaypoints::get_id(), MavlinkStreamOpticalFlowRad::get_id(), MavlinkStreamNamedValueFloat::get_id(), MavlinkStreamDebug::get_id(), MavlinkStreamDebugVect::get_id(), MavlinkStreamDebugFloatArray::get_id(), MavlinkStreamNavControllerOutput::get_id(), MavlinkStreamCameraCapture::get_id(), MavlinkStreamDistanceSensor::get_id(), MavlinkStreamExtendedSysState::get_id(), MavlinkStreamAltitude::get_id(), MavlinkStreamWind::get_id(), MavlinkStreamMountOrientation::get_id(), MavlinkStreamGroundTruth::get_id(), MavlinkStreamPing::get_id(), MavlinkStreamOrbitStatus::get_id(), and MavlinkStreamObstacleDistance::get_id().
get_name()
const char* MavlinkStreamHeartbeat::get_name () const inline override virtual
Implements MavlinkStream.
Definition at line 309 of file mavlink_messages.cpp.
References get_name_static().
get_name_static()
static const char* MavlinkStreamHeartbeat::get_name_static () inline static
Definition at line 314 of file mavlink_messages.cpp.
Referenced by get_name().
get_size()
unsigned MavlinkStreamHeartbeat::get_size () inline override virtual
Get maximal total messages size on update.
Implements MavlinkStream.
Definition at line 334 of file mavlink_messages.cpp.
new_instance()
static MavlinkStream* MavlinkStreamHeartbeat::new_instance (Mavlink * mavlink) inline static
Definition at line 329 of file mavlink_messages.cpp.
References MavlinkStreamHeartbeat().
operator=()
MavlinkStreamHeartbeat& MavlinkStreamHeartbeat::operator= (const MavlinkStreamHeartbeat &) private delete
Referenced by MavlinkStreamStatustext::get_size(), MavlinkStreamSystemTime::get_size(), and MavlinkStreamTimesync::get_size().
send()
bool MavlinkStreamHeartbeat::send (const hrt_abstime t) inline override protected virtual
Implements MavlinkStream.
Definition at line 356 of file mavlink_messages.cpp.
References MavlinkStream::_mavlink, Mavlink::get_channel(), get_mavlink_mode_state(), Mavlink::get_system_type(), and MavlinkOrbSubscription::update().
Member Data Documentation
_status_sub
MavlinkOrbSubscription* MavlinkStreamHeartbeat::_status_sub private
Definition at line 345 of file mavlink_messages.cpp.
The documentation for this class was generated from the following file:
src/modules/mavlink/mavlink_messages.cpp