PX4 Firmware: src/drivers/boards/aerofc-v1/led.c File Reference
led.c File Reference
#include <px4_config.h>
#include <stdbool.h>
#include "stm32.h"
#include "board_config.h"
#include <arch/board/board.h>
Functions
__BEGIN_DECLS void led_init (void)
Ideally we'd be able to get these from up_internal.h, but since we want to be able to disable the NuttX use of leds for system indication at will and there is no separate switch, we need to build independent of the CONFIG_ARCH_LEDS configuration switch.
void led_on (int led)
void led_off (int led)
void led_toggle (int led)
static uint32_t _led_param_get (int led)
Function Documentation
static uint32_t _led_param_get (int led) static
Definition at line 74 of file led.c.
References GPIO_LED0, GPIO_LED1, GPIO_LED2, and GPIO_LED3.
Referenced by led_off(), led_on(), and led_toggle().
__BEGIN_DECLS void led_init (void)
Ideally we'd be able to get these from up_internal.h, but since we want to be able to disable the NuttX use of leds for system indication at will and there is no separate switch, we need to build independent of the CONFIG_ARCH_LEDS configuration switch.
Definition at line 64 of file led.c.
References GPIO_LED0, GPIO_LED1, GPIO_LED2, and GPIO_LED3.
void led_off (int led)
Definition at line 103 of file led.c.
References _led_param_get().
void led_on (int led)
Definition at line 94 of file led.c.
References _led_param_get().
void led_toggle (int led)
Definition at line 112 of file led.c.
References _led_param_get().