PX4 Firmware: src/drivers/batt_smbus/batt_smbus_main.cpp File Reference
batt_smbus_main.cpp File Reference
#include "batt_smbus.h"
#include <px4_module.h>
Classes
struct batt_smbus::batt_smbus_bus_option
Namespaces
batt_smbus
Local functions in support of the shell command.
Macros
#define NUM_BUS_OPTIONS (sizeof(bus_options)/sizeof(bus_options[0]))
Enumerations
enum BATT_SMBUS_BUS { BATT_SMBUS_BUS_ALL = 0, BATT_SMBUS_BUS_I2C_INTERNAL, BATT_SMBUS_BUS_I2C_EXTERNAL }
Functions
__EXPORT int batt_smbus_main (int argc, char *argv[])
int batt_smbus::start (enum BATT_SMBUS_BUS busid)
Start the driver.
bool batt_smbus::start_bus (struct batt_smbus_bus_option &bus)
start driver for a specific bus option
struct batt_smbus_bus_option & batt_smbus::find_bus (enum BATT_SMBUS_BUS busid)
Find a bus structure for a busid.
int batt_smbus::reset (enum BATT_SMBUS_BUS busid)
int batt_smbus::info ()
Print a little info about the driver.
void batt_smbus::usage (const char *reason)
int batt_smbus::manufacture_date ()
Nuttshell accessible method to return the battery manufacture date.
int batt_smbus::manufacturer_name ()
Nuttshell accessible method to return the battery manufacturer name.
int batt_smbus::serial_number ()
Nuttshell accessible method to return the battery serial number.
Variables
struct batt_smbus::batt_smbus_bus_option batt_smbus::bus_options []
Macro Definition Documentation
#define NUM_BUS_OPTIONS (sizeof(bus_options)/sizeof(bus_options[0]))
Definition at line 65 of file batt_smbus_main.cpp.
Referenced by batt_smbus::find_bus(), batt_smbus::manufacture_date(), batt_smbus::manufacturer_name(), batt_smbus::serial_number(), and batt_smbus::start().
Enumeration Type Documentation
enum BATT_SMBUS_BUS
Enumerator
BATT_SMBUS_BUS_ALL
BATT_SMBUS_BUS_I2C_INTERNAL
BATT_SMBUS_BUS_I2C_EXTERNAL
Definition at line 39 of file batt_smbus_main.cpp.
Function Documentation
int batt_smbus_main (int argc, char * argv[])
Definition at line 285 of file batt_smbus_main.cpp.
References BATT_SMBUS_BUS_ALL, BATT_SMBUS_BUS_I2C_EXTERNAL, BATT_SMBUS_BUS_I2C_INTERNAL, BATT_SMBUS::block_read(), BATT_SMBUS::block_write(), batt_smbus::batt_smbus_bus_option::busid, data, BATT_SMBUS::dataflash_read(), BATT_SMBUS::dataflash_write(), batt_smbus::batt_smbus_bus_option::dev, batt_smbus::find_bus(), BATT_SMBUS::info(), batt_smbus::manufacture_date(), batt_smbus::manufacturer_name(), BATT_SMBUS::manufacturer_read(), PX4_INFO, PX4_OK, PX4_WARN, BATT_SMBUS::read_word(), rx_buf, batt_smbus::serial_number(), batt_smbus::start(), BATT_SMBUS::start(), BATT_SMBUS::stop(), tx_buf, BATT_SMBUS::unseal(), batt_smbus::usage(), and usleep().