PX4 Firmware: matrix::Matrix< Type, M, N > Class Template Reference
matrix::Matrix< Type, M, N > Class Template Reference
#include <Matrix.hpp>
Public Member Functions
Matrix ()=default
Matrix (const Type data_[M *N])
Matrix (const Type data_[M][N])
Matrix (const Matrix &other)
template<size_t P, size_t Q>
Matrix (const Slice< Type, M, N, P, Q > &in_slice)
Type operator() (size_t i, size_t j) const
Accessors/ Assignment etc.
Type & operator() (size_t i, size_t j)
Matrix< Type, M, N > & operator= (const Matrix< Type, M, N > &other)
void copyTo (Type dst[M *N]) const
void copyToColumnMajor (Type dst[M *N]) const
template<size_t P>
Matrix< Type, M, P > operator* (const Matrix< Type, N, P > &other) const
Matrix Operations.
Matrix< Type, M, N > emult (const Matrix< Type, M, N > &other) const
Matrix< Type, M, N > edivide (const Matrix< Type, M, N > &other) const
Matrix< Type, M, N > operator+ (const Matrix< Type, M, N > &other) const
Matrix< Type, M, N > operator- (const Matrix< Type, M, N > &other) const
Matrix< Type, M, N > operator- () const
void operator+= (const Matrix< Type, M, N > &other)
void operator-= (const Matrix< Type, M, N > &other)
template<size_t P>
void operator*= (const Matrix< Type, N, P > &other)
Matrix< Type, M, N > operator* (Type scalar) const
Scalar Operations.
Matrix< Type, M, N > operator/ (Type scalar) const
Matrix< Type, M, N > operator+ (Type scalar) const
Matrix< Type, M, N > operator- (Type scalar) const
void operator*= (Type scalar)
void operator/= (Type scalar)
void operator+= (Type scalar)
void operator-= (Type scalar)
bool operator== (const Matrix< Type, M, N > &other) const
bool operator!= (const Matrix< Type, M, N > &other) const
void write_string (char *buf, size_t n) const
Misc.
void print (FILE *stream=stdout) const
Matrix< Type, N, M > transpose () const
Matrix< Type, N, M > T () const
template<size_t P, size_t Q>
const Slice< Type, P, Q, M, N > slice (size_t x0, size_t y0) const
template<size_t P, size_t Q>
Slice< Type, P, Q, M, N > slice (size_t x0, size_t y0)
const Slice< Type, 1, N, M, N > row (size_t i) const
Slice< Type, 1, N, M, N > row (size_t i)
const Slice< Type, M, 1, M, N > col (size_t j) const
Slice< Type, M, 1, M, N > col (size_t j)
void setRow (size_t i, const Matrix< Type, N, 1 > &row_in)
void setCol (size_t j, const Matrix< Type, M, 1 > &column)
void setZero ()
void zero ()
void setAll (Type val)
void setOne ()
void setNaN ()
void setIdentity ()
void identity ()
void swapRows (size_t a, size_t b)
void swapCols (size_t a, size_t b)
Matrix< Type, M, N > abs () const
Type max () const
Type min () const
bool isAllNan () const
Private Attributes
Type _data [M][N] {}
Detailed Description
template<typename Type, size_t M, size_t N>
class matrix::Matrix< Type, M, N >
Definition at line 36 of file Matrix.hpp.
Constructor & Destructor Documentation
Matrix() [1/5]
template<typename Type, size_t M, size_t N> matrix::Matrix< Type, M, N >::Matrix () default
Matrix() [2/5]
template<typename Type, size_t M, size_t N> matrix::Matrix< Type, M, N >::Matrix (const Type data_[M *N]) inline explicit
Definition at line 66 of file Matrix.hpp.
Matrix() [3/5]
template<typename Type, size_t M, size_t N> matrix::Matrix< Type, M, N >::Matrix (const Type data_[M][N]) inline explicit
Definition at line 71 of file Matrix.hpp.
Matrix() [4/5]
template<typename Type, size_t M, size_t N> matrix::Matrix< Type, M, N >::Matrix (const Matrix< Type, M, N > & other) inline
Definition at line 76 of file Matrix.hpp.
Matrix() [5/5]
template<typename Type, size_t M, size_t N> template<size_t P, size_t Q> matrix::Matrix< Type, M, N >::Matrix (const Slice< Type, M, N, P, Q > & in_slice) inline
Definition at line 82 of file Matrix.hpp.
Member Function Documentation
abs()
template<typename Type, size_t M, size_t N> Matrix<Type, M, N> matrix::Matrix< Type, M, N >::abs () const inline
Definition at line 492 of file Matrix.hpp.
col() [1/2]
template<typename Type, size_t M, size_t N> const Slice<Type, M, 1, M, N> matrix::Matrix< Type, M, N >::col (size_t j) const inline
Definition at line 395 of file Matrix.hpp.
Referenced by main(), and MatrixTest::matrixAssignmentTests().
col() [2/2]
template<typename Type, size_t M, size_t N> Slice<Type, M, 1, M, N> matrix::Matrix< Type, M, N >::col (size_t j) inline
Definition at line 400 of file Matrix.hpp.
copyTo()
template<typename Type, size_t M, size_t N> void matrix::Matrix< Type, M, N >::copyTo (Type dst[M *N]) const inline
Definition at line 115 of file Matrix.hpp.
Referenced by MulticopterAttitudeControl::generate_attitude_setpoint(), FlightTask::getPositionSetpoint(), MavlinkReceiver::handle_message_hil_state_quaternion(), Simulator::handle_message_hil_state_quaternion(), MavlinkReceiver::handle_message_odometry(), MavlinkReceiver::handle_message_set_attitude_target(), MavlinkReceiver::handle_message_vision_position_estimate(), main(), CollisionPrevention::modifySetpoint(), Simulator::publish_odometry_topic(), BlockLocalPositionEstimator::publishOdom(), Ekf2::Run(), MavlinkStreamAttitudeQuaternion::send(), ControlMath::thrustToAttitude(), Standard::update_mc_state(), Tailsitter::update_transition_state(), Standard::update_transition_state(), ObstacleAvoidance::updateAvoidanceDesiredSetpoints(), and ObstacleAvoidance::updateAvoidanceDesiredWaypoints().
copyToColumnMajor()
template<typename Type, size_t M, size_t N> void matrix::Matrix< Type, M, N >::copyToColumnMajor (Type dst[M *N]) const inline
Definition at line 120 of file Matrix.hpp.
Referenced by main().
edivide()
template<typename Type, size_t M, size_t N> Matrix<Type, M, N> matrix::Matrix< Type, M, N >::edivide (const Matrix< Type, M, N > & other) const inline
Definition at line 171 of file Matrix.hpp.
Referenced by main().
emult()
template<typename Type, size_t M, size_t N> Matrix<Type, M, N> matrix::Matrix< Type, M, N >::emult (const Matrix< Type, M, N > & other) const inline
Definition at line 157 of file Matrix.hpp.
Referenced by main(), MatrixTest::matrixMultTests(), MulticopterRateControl::parameters_updated(), MulticopterRateControl::Run(), AttitudeControl::update(), and RateControl::update().
identity()
template<typename Type, size_t M, size_t N> void matrix::Matrix< Type, M, N >::identity () inline
Definition at line 457 of file Matrix.hpp.
Referenced by main(), MathlibTest::testMatrix3x3(), MathlibTest::testQuaternionfrom_dcm(), MathlibTest::testQuaternionfrom_euler(), and landing_target_estimator::KalmanFilter::update().
isAllNan()
template<typename Type, size_t M, size_t N> bool matrix::Matrix< Type, M, N >::isAllNan () const inline
Definition at line 531 of file Matrix.hpp.
Referenced by main().
max()
template<typename Type, size_t M, size_t N> Type matrix::Matrix< Type, M, N >::max () const inline
Definition at line 503 of file Matrix.hpp.
Referenced by matrix::max().
min()
template<typename Type, size_t M, size_t N> Type matrix::Matrix< Type, M, N >::min () const inline
Definition at line 517 of file Matrix.hpp.
Referenced by main(), MatrixTest::matrixAssignmentTests(), and matrix::min().
operator!=()
template<typename Type, size_t M, size_t N> bool matrix::Matrix< Type, M, N >::operator!= (const Matrix< Type, M, N > & other) const inline
Definition at line 321 of file Matrix.hpp.
operator()() [1/2]
template<typename Type, size_t M, size_t N> Type matrix::Matrix< Type, M, N >::operator() (size_t i, size_t j) const inline
Accessors/ Assignment etc.
Definition at line 97 of file Matrix.hpp.
operator()() [2/2]
template<typename Type, size_t M, size_t N> Type& matrix::Matrix< Type, M, N >::operator() (size_t i, size_t j) inline
Definition at line 102 of file Matrix.hpp.
operator*() [1/2]
template<typename Type, size_t M, size_t N> template<size_t P> Matrix<Type, M, P> matrix::Matrix< Type, M, N >::operator* (const Matrix< Type, N, P > & other) const inline
Matrix Operations.
Definition at line 140 of file Matrix.hpp.
Referenced by matrix::Vector3< Type >::operator*().
operator*() [2/2]
template<typename Type, size_t M, size_t N> Matrix<Type, M, N> matrix::Matrix< Type, M, N >::operator* (Type scalar) const inline
Scalar Operations.
Definition at line 251 of file Matrix.hpp.
operator*=() [1/2]
template<typename Type, size_t M, size_t N> template<size_t P> void matrix::Matrix< Type, M, N >::operator*= (const Matrix< Type, N, P > & other) inline
Definition at line 241 of file Matrix.hpp.
operator*=() [2/2]
template<typename Type, size_t M, size_t N> void matrix::Matrix< Type, M, N >::operator*= (Type scalar) inline
Definition at line 289 of file Matrix.hpp.
operator+() [1/2]
template<typename Type, size_t M, size_t N> Matrix<Type, M, N> matrix::Matrix< Type, M, N >::operator+ (const Matrix< Type, M, N > & other) const inline
Definition at line 185 of file Matrix.hpp.
Referenced by matrix::Vector3< Type >::operator+().
operator+() [2/2]
template<typename Type, size_t M, size_t N> Matrix<Type, M, N> matrix::Matrix< Type, M, N >::operator+ (Type scalar) const inline
Definition at line 270 of file Matrix.hpp.
operator+=() [1/2]
template<typename Type, size_t M, size_t N> void matrix::Matrix< Type, M, N >::operator+= (const Matrix< Type, M, N > & other) inline
Definition at line 228 of file Matrix.hpp.
operator+=() [2/2]
template<typename Type, size_t M, size_t N> void matrix::Matrix< Type, M, N >::operator+= (Type scalar) inline
Definition at line 306 of file Matrix.hpp.
operator-() [1/3]
template<typename Type, size_t M, size_t N> Matrix<Type, M, N> matrix::Matrix< Type, M, N >::operator- (const Matrix< Type, M, N > & other) const inline
Definition at line 199 of file Matrix.hpp.
operator-() [2/3]
template<typename Type, size_t M, size_t N> Matrix<Type, M, N> matrix::Matrix< Type, M, N >::operator- () const inline
Definition at line 214 of file Matrix.hpp.
Referenced by matrix::Vector3< Type >::operator-().
operator-() [3/3]
template<typename Type, size_t M, size_t N> Matrix<Type, M, N> matrix::Matrix< Type, M, N >::operator- (Type scalar) const inline
Definition at line 284 of file Matrix.hpp.
operator-=() [1/2]
template<typename Type, size_t M, size_t N> void matrix::Matrix< Type, M, N >::operator-= (const Matrix< Type, M, N > & other) inline
Definition at line 234 of file Matrix.hpp.
operator-=() [2/2]
template<typename Type, size_t M, size_t N> void matrix::Matrix< Type, M, N >::operator-= (Type scalar) inline
Definition at line 311 of file Matrix.hpp.
operator/()
template<typename Type, size_t M, size_t N> Matrix<Type, M, N> matrix::Matrix< Type, M, N >::operator/ (Type scalar) const inline
Definition at line 265 of file Matrix.hpp.
operator/=()
template<typename Type, size_t M, size_t N> void matrix::Matrix< Type, M, N >::operator/= (Type scalar) inline
Definition at line 300 of file Matrix.hpp.
operator=()
template<typename Type, size_t M, size_t N> Matrix<Type, M, N>& matrix::Matrix< Type, M, N >::operator= (const Matrix< Type, M, N > & other) inline
Definition at line 107 of file Matrix.hpp.
Referenced by matrix::SquareMatrix< Type, 3 >::operator=().
operator==()
template<typename Type, size_t M, size_t N> bool matrix::Matrix< Type, M, N >::operator== (const Matrix< Type, M, N > & other) const inline
Definition at line 316 of file Matrix.hpp.
print()
template<typename Type, size_t M, size_t N> void matrix::Matrix< Type, M, N >::print (FILE * stream = stdout) const inline
Definition at line 343 of file Matrix.hpp.
Referenced by main(), and MathlibTest::testMatrixNonsymmetric().
row() [1/2]
template<typename Type, size_t M, size_t N> const Slice<Type, 1, N, M, N> matrix::Matrix< Type, M, N >::row (size_t i) const inline
Definition at line 385 of file Matrix.hpp.
Referenced by matrix::collectDerivatives(), MatrixTest::dcmRenormTests(), AttitudeEstimatorQ::init_attq(), main(), MatrixTest::matrixAssignmentTests(), and matrix::Dcm< float >::renormalize().
row() [2/2]
template<typename Type, size_t M, size_t N> Slice<Type, 1, N, M, N> matrix::Matrix< Type, M, N >::row (size_t i) inline
Definition at line 390 of file Matrix.hpp.
setAll()
template<typename Type, size_t M, size_t N> void matrix::Matrix< Type, M, N >::setAll (Type val) inline
Definition at line 426 of file Matrix.hpp.
Referenced by FlightTaskAuto::_evaluateTriplets(), FlightTask::_evaluateVehicleLocalPosition(), FlightTask::_resetSetpoints(), FlightTaskAuto::_set_heading_from_mode(), FlightTaskManualPosition::_updateSetpoints(), FlightTaskTransition::activate(), matrix::Matrix< float, n_x, n_u >::setNaN(), matrix::Matrix< float, n_x, n_u >::setOne(), and FlightTaskTransition::updateAccelerationEstimate().
setCol()
template<typename Type, size_t M, size_t N> void matrix::Matrix< Type, M, N >::setCol (size_t j, const Matrix< Type, M, 1 > & column) inline
Definition at line 411 of file Matrix.hpp.
Referenced by main().
setIdentity()
template<typename Type, size_t M, size_t N> void matrix::Matrix< Type, M, N >::setIdentity () inline
Definition at line 447 of file Matrix.hpp.
Referenced by MatrixTest::filterTests(), matrix::Matrix< float, n_x, n_u >::identity(), main(), MatrixTest::matrixMultTests(), MatrixTest::setIdentityTests(), and TerrainEstimator::TerrainEstimator().
setNaN()
template<typename Type, size_t M, size_t N> void matrix::Matrix< Type, M, N >::setNaN () inline
Definition at line 442 of file Matrix.hpp.
Referenced by matrix::constrain(), StraightLine::generateSetpoints(), ObstacleAvoidance::injectAvoidanceSetpoints(), main(), matrix::nans(), and ObstacleAvoidance::ObstacleAvoidance().
setOne()
template<typename Type, size_t M, size_t N> void matrix::Matrix< Type, M, N >::setOne () inline
Definition at line 437 of file Matrix.hpp.
Referenced by matrix::ones().
setRow()
template<typename Type, size_t M, size_t N> void matrix::Matrix< Type, M, N >::setRow (size_t i, const Matrix< Type, N, 1 > & row_in) inline
Definition at line 405 of file Matrix.hpp.
Referenced by main().
setZero()
template<typename Type, size_t M, size_t N> void matrix::Matrix< Type, M, N >::setZero () inline
Definition at line 416 of file Matrix.hpp.
Referenced by BlockLocalPositionEstimator::baroCorrect(), BlockLocalPositionEstimator::BlockLocalPositionEstimator(), Sih::equations_of_motion(), BlockLocalPositionEstimator::flowCorrect(), BlockLocalPositionEstimator::gpsCorrect(), WindEstimator::initialise(), BlockLocalPositionEstimator::initP(), BlockLocalPositionEstimator::initSS(), BlockLocalPositionEstimator::landCorrect(), BlockLocalPositionEstimator::landingTargetCorrect(), BlockLocalPositionEstimator::lidarCorrect(), main(), MatrixTest::matrixAssignmentTests(), TerrainEstimator::measurement_update(), BlockLocalPositionEstimator::mocapCorrect(), matrix::Matrix< float, n_x, n_u >::operator*(), TerrainEstimator::predict(), matrix::Matrix< float, n_x, n_u >::setIdentity(), BlockLocalPositionEstimator::sonarCorrect(), BlockLocalPositionEstimator::updateSSParams(), BlockLocalPositionEstimator::visionCorrect(), matrix::Matrix< float, n_x, n_u >::zero(), and matrix::zeros().
slice() [1/2]
template<typename Type, size_t M, size_t N> template<size_t P, size_t Q> const Slice<Type, P, Q, M, N> matrix::Matrix< Type, M, N >::slice (size_t x0, size_t y0) const inline
Definition at line 374 of file Matrix.hpp.
Referenced by main().
slice() [2/2]
template<typename Type, size_t M, size_t N> template<size_t P, size_t Q> Slice<Type, P, Q, M, N> matrix::Matrix< Type, M, N >::slice (size_t x0, size_t y0) inline
Definition at line 380 of file Matrix.hpp.
swapCols()
template<typename Type, size_t M, size_t N> void matrix::Matrix< Type, M, N >::swapCols (size_t a, size_t b) inline
Definition at line 477 of file Matrix.hpp.
Referenced by main(), and MatrixTest::matrixAssignmentTests().
swapRows()
template<typename Type, size_t M, size_t N> void matrix::Matrix< Type, M, N >::swapRows (size_t a, size_t b) inline
Definition at line 462 of file Matrix.hpp.
Referenced by main(), and MatrixTest::matrixAssignmentTests().
T()
template<typename Type, size_t M, size_t N> Matrix<Type, N, M> matrix::Matrix< Type, M, N >::T () const inline
Definition at line 368 of file Matrix.hpp.
Referenced by matrix::kalman_correct(), and main().
transpose()
template<typename Type, size_t M, size_t N> Matrix<Type, N, M> matrix::Matrix< Type, M, N >::transpose () const inline
Definition at line 353 of file Matrix.hpp.
Referenced by BlockLocalPositionEstimator::baroCorrect(), do_accel_calibration(), BlockLocalPositionEstimator::flowCorrect(), WindEstimator::fuse_airspeed(), WindEstimator::fuse_beta(), matrix::geninv(), BlockLocalPositionEstimator::gpsCorrect(), WindEstimator::initialise(), BlockLocalPositionEstimator::landCorrect(), BlockLocalPositionEstimator::landingTargetCorrect(), BlockLocalPositionEstimator::lidarCorrect(), main(), TerrainEstimator::measurement_update(), BlockLocalPositionEstimator::mocapCorrect(), TerrainEstimator::predict(), landing_target_estimator::KalmanFilter::predict(), BlockLocalPositionEstimator::predict(), Sih::reconstruct_sensors_signals(), MavlinkStreamOdometry::send(), matrix::Matrix< float, n_x, n_u >::setRow(), BlockLocalPositionEstimator::sonarCorrect(), matrix::Matrix< float, n_x, n_u >::T(), MatrixTest::transposeTests(), and BlockLocalPositionEstimator::visionCorrect().
write_string()
template<typename Type, size_t M, size_t N> void matrix::Matrix< Type, M, N >::write_string (char * buf, size_t n) const inline
Misc.
Functions
Definition at line 331 of file Matrix.hpp.
Referenced by main(), and matrix::Matrix< float, n_x, n_u >::print().
zero()
template<typename Type, size_t M, size_t N> void matrix::Matrix< Type, M, N >::zero () inline
Definition at line 421 of file Matrix.hpp.
Referenced by Integrator::_reset(), FlightTaskFailsafe::activate(), FollowTarget::FollowTarget(), main(), TerrainEstimator::measurement_update(), FollowTarget::reset_target_validity(), RateControl::resetIntegral(), math::LowPassFilter2pVector3f::set_cutoff_frequency(), VehicleAcceleration::Start(), VehicleAngularVelocity::Start(), TerrainEstimator::TerrainEstimator(), TEST(), MathlibTest::testVector2(), MathlibTest::testVector3(), ControlMath::thrustToAttitude(), and landing_target_estimator::LandingTargetEstimator::update().
Member Data Documentation
_data
template<typename Type, size_t M, size_t N> Type matrix::Matrix< Type, M, N >::_data[M][N] {} private
Definition at line 47 of file Matrix.hpp.
Referenced by matrix::Matrix< float, n_x, n_u >::Matrix(), and matrix::Matrix< float, n_x, n_u >::operator=().
The documentation for this class was generated from the following file:
src/lib/matrix/matrix/Matrix.hpp