PX4 Firmware: src/drivers/barometer/ms5611/ms5611.cpp File Reference
ms5611.cpp File Reference
Driver for the MS5611 and MS6507 barometric pressure sensor connected via I2C or SPI.
#include <px4_config.h>
#include <sys/types.h>
#include <stdint.h>
#include <stdbool.h>
#include <stdlib.h>
#include <semaphore.h>
#include <string.h>
#include <fcntl.h>
#include <poll.h>
#include <errno.h>
#include <stdio.h>
#include <math.h>
#include <unistd.h>
#include <nuttx/arch.h>
#include <nuttx/wqueue.h>
#include <nuttx/clock.h>
#include <arch/board/board.h>
#include <board_config.h>
#include <drivers/device/device.h>
#include <drivers/drv_baro.h>
#include <drivers/drv_hrt.h>
#include <drivers/device/ringbuffer.h>
#include <perf/perf_counter.h>
#include <systemlib/err.h>
#include <platforms/px4_getopt.h>
#include "ms5611.h"
Classes
class MS5611
struct ms5611::ms5611_bus_option
Namespaces
ms5611
Local functions in support of the shell command.
Macros
#define INCREMENT(_x, _lim) do { __typeof__(_x) _tmp = _x+1; if (_tmp >= _lim) _tmp = 0; _x = _tmp; } while(0)
#define POW2(_x) ((_x) * (_x))
#define ADDR_CMD_CONVERT_D1_OSR256 0x40 /* write to this address to start pressure conversion */
#define ADDR_CMD_CONVERT_D1_OSR512 0x42 /* write to this address to start pressure conversion */
#define ADDR_CMD_CONVERT_D1_OSR1024 0x44 /* write to this address to start pressure conversion */
#define ADDR_CMD_CONVERT_D1_OSR2048 0x46 /* write to this address to start pressure conversion */
#define ADDR_CMD_CONVERT_D1_OSR4096 0x48 /* write to this address to start pressure conversion */
#define ADDR_CMD_CONVERT_D2_OSR256 0x50 /* write to this address to start temperature conversion */
#define ADDR_CMD_CONVERT_D2_OSR512 0x52 /* write to this address to start temperature conversion */
#define ADDR_CMD_CONVERT_D2_OSR1024 0x54 /* write to this address to start temperature conversion */
#define ADDR_CMD_CONVERT_D2_OSR2048 0x56 /* write to this address to start temperature conversion */
#define ADDR_CMD_CONVERT_D2_OSR4096 0x58 /* write to this address to start temperature conversion */
#define ADDR_CMD_CONVERT_D1 ADDR_CMD_CONVERT_D1_OSR1024
#define ADDR_CMD_CONVERT_D2 ADDR_CMD_CONVERT_D2_OSR1024
#define MS5611_CONVERSION_INTERVAL 10000 /* microseconds */
#define MS5611_MEASUREMENT_RATIO 3 /* pressure measurements per temperature measurement */
#define MS5611_BARO_DEVICE_PATH_EXT "/dev/ms5611_ext"
#define MS5611_BARO_DEVICE_PATH_INT "/dev/ms5611_int"
#define NUM_BUS_OPTIONS (sizeof(bus_options)/sizeof(bus_options[0]))
Enumerations
enum MS56XX_DEVICE_TYPES { MS56XX_DEVICE = 0, MS5611_DEVICE = 5611, MS5607_DEVICE = 5607 }
enum MS5611_BUS {
MS5611_BUS_ALL = 0, MS5611_BUS_I2C_INTERNAL, MS5611_BUS_I2C_EXTERNAL, MS5611_BUS_SPI_INTERNAL,
MS5611_BUS_SPI_EXTERNAL
}
Functions
__EXPORT int ms5611_main (int argc, char *argv[])
bool ms5611::start_bus (struct ms5611_bus_option &bus, enum MS56XX_DEVICE_TYPES device_type)
Start the driver.
struct ms5611_bus_option & ms5611::find_bus (enum MS5611_BUS busid)
find a bus structure for a busid
void ms5611::start (enum MS5611_BUS busid, enum MS56XX_DEVICE_TYPES device_type)
Start the driver.
void ms5611::test (enum MS5611_BUS busid)
Perform some basic functional tests on the driver; make sure we can collect data from the sensor in polled and automatic modes.
void ms5611::reset (enum MS5611_BUS busid)
Reset the driver.
void ms5611::info ()
Print a little info about the driver.
void ms5611::usage ()
Prints info about the driver argument usage.
bool ms5611::crc4 (uint16_t *n_prom)
MS5611 crc4 cribbed from the datasheet.
Variables
struct ms5611::ms5611_bus_option ms5611::bus_options []
Detailed Description
Driver for the MS5611 and MS6507 barometric pressure sensor connected via I2C or SPI.
Definition in file ms5611.cpp.
Macro Definition Documentation
#define ADDR_CMD_CONVERT_D1 ADDR_CMD_CONVERT_D1_OSR1024
Definition at line 116 of file ms5611.cpp.
Referenced by MS5611::measure().
#define ADDR_CMD_CONVERT_D1_OSR1024 0x44 /* write to this address to start pressure conversion */
Definition at line 101 of file ms5611.cpp.
#define ADDR_CMD_CONVERT_D1_OSR2048 0x46 /* write to this address to start pressure conversion */
Definition at line 102 of file ms5611.cpp.
#define ADDR_CMD_CONVERT_D1_OSR256 0x40 /* write to this address to start pressure conversion */
Definition at line 99 of file ms5611.cpp.
#define ADDR_CMD_CONVERT_D1_OSR4096 0x48 /* write to this address to start pressure conversion */
Definition at line 103 of file ms5611.cpp.
#define ADDR_CMD_CONVERT_D1_OSR512 0x42 /* write to this address to start pressure conversion */
Definition at line 100 of file ms5611.cpp.
#define ADDR_CMD_CONVERT_D2 ADDR_CMD_CONVERT_D2_OSR1024
Definition at line 117 of file ms5611.cpp.
Referenced by MS5611::measure().
#define ADDR_CMD_CONVERT_D2_OSR1024 0x54 /* write to this address to start temperature conversion */
Definition at line 106 of file ms5611.cpp.
#define ADDR_CMD_CONVERT_D2_OSR2048 0x56 /* write to this address to start temperature conversion */
Definition at line 107 of file ms5611.cpp.
#define ADDR_CMD_CONVERT_D2_OSR256 0x50 /* write to this address to start temperature conversion */
Definition at line 104 of file ms5611.cpp.
#define ADDR_CMD_CONVERT_D2_OSR4096 0x58 /* write to this address to start temperature conversion */
Definition at line 108 of file ms5611.cpp.
#define ADDR_CMD_CONVERT_D2_OSR512 0x52 /* write to this address to start temperature conversion */
Definition at line 105 of file ms5611.cpp.
#define INCREMENT (_x, _lim) do { __typeof__(_x) _tmp = _x+1; if (_tmp >= _lim) _tmp = 0; _x = _tmp; } while(0)
Definition at line 91 of file ms5611.cpp.
Referenced by MS5611::collect().
#define MS5611_BARO_DEVICE_PATH_EXT "/dev/ms5611_ext"
Definition at line 126 of file ms5611.cpp.
#define MS5611_BARO_DEVICE_PATH_INT "/dev/ms5611_int"
Definition at line 127 of file ms5611.cpp.
#define MS5611_CONVERSION_INTERVAL 10000 /* microseconds */
Definition at line 124 of file ms5611.cpp.
Referenced by MS5611::cycle(), MS5611::init(), MS5611::ioctl(), and MS5611::read().
#define MS5611_MEASUREMENT_RATIO 3 /* pressure measurements per temperature measurement */
Definition at line 125 of file ms5611.cpp.
Referenced by MS5611::collect().
#define NUM_BUS_OPTIONS (sizeof(bus_options)/sizeof(bus_options[0]))
Definition at line 879 of file ms5611.cpp.
Referenced by ms5611::find_bus(), ms5611::info(), and ms5611::start().
#define POW2 (_x) ((_x) * (_x))
Definition at line 94 of file ms5611.cpp.
Referenced by MS5611::collect().
Enumeration Type Documentation
enum MS5611_BUS
Enumerator
MS5611_BUS_ALL
MS5611_BUS_I2C_INTERNAL
MS5611_BUS_I2C_EXTERNAL
MS5611_BUS_SPI_INTERNAL
MS5611_BUS_SPI_EXTERNAL
Definition at line 78 of file ms5611.cpp.
enum MS56XX_DEVICE_TYPES
Enumerator
MS56XX_DEVICE
MS5611_DEVICE
MS5607_DEVICE
Definition at line 72 of file ms5611.cpp.
Function Documentation
int ms5611_main (int argc, char * argv[])
Definition at line 1158 of file ms5611.cpp.
References ms5611::info(), MS5607_DEVICE, MS5611_BUS_ALL, MS5611_BUS_I2C_EXTERNAL, MS5611_BUS_I2C_INTERNAL, MS5611_BUS_SPI_EXTERNAL, MS5611_BUS_SPI_INTERNAL, MS5611_DEVICE, MS56XX_DEVICE, PX4_ERR, px4_getopt(), ms5611::reset(), ms5611::start(), ms5611::test(), and ms5611::usage().