PX4 Firmware: src/platforms/posix/drivers/df_bebop_bus_wrapper/df_bebop_bus_wrapper.cpp File Reference
df_bebop_bus_wrapper.cpp File Reference
This is a wrapper around the Parrot Bebop bus driver of the DriverFramework.
#include <stdint.h>
#include <px4_tasks.h>
#include <px4_getopt.h>
#include <px4_posix.h>
#include <errno.h>
#include <string.h>
#include <uORB/topics/actuator_outputs.h>
#include <uORB/topics/actuator_controls.h>
#include <uORB/topics/actuator_armed.h>
#include <uORB/topics/battery_status.h>
#include <uORB/topics/esc_status.h>
#include <lib/mixer/mixer.h>
#include <battery/battery.h>
#include <bebop_bus/BebopBus.hpp>
#include <DevMgr.hpp>
Classes
class DfBebopBusWrapper
Namespaces
df_bebop_bus_wrapper
Functions
__EXPORT int df_bebop_bus_wrapper_main (int argc, char *argv[])
int df_bebop_bus_wrapper::start ()
Attempt to start driver on all available I2C busses.
int df_bebop_bus_wrapper::stop ()
Stop the driver.
int df_bebop_bus_wrapper::info ()
Print a little info about the driver.
int df_bebop_bus_wrapper::clear_errors ()
Clear errors present on the Bebop hardware.
void df_bebop_bus_wrapper::usage ()
Prints info about the driver argument usage.
void df_bebop_bus_wrapper::task_main (int argc, char *argv[])
int df_bebop_bus_wrapper::initialize_mixers (const char *mixers_filename)
int df_bebop_bus_wrapper::mixers_control_callback (uintptr_t handle, uint8_t control_group, uint8_t control_index, float &input)
Variables
DfBebopBusWrapper * df_bebop_bus_wrapper::g_dev = nullptr
volatile bool df_bebop_bus_wrapper::_task_should_exit = false
static bool df_bebop_bus_wrapper::_is_running = false
static bool df_bebop_bus_wrapper::_motors_running = false
static px4_task_t df_bebop_bus_wrapper::_task_handle = -1
static const char * df_bebop_bus_wrapper::MIXER_FILENAME = "/home/root/bebop.main.mix"
int df_bebop_bus_wrapper::_controls_sub
int df_bebop_bus_wrapper::_armed_sub
orb_advert_t df_bebop_bus_wrapper::_outputs_pub = nullptr
orb_advert_t df_bebop_bus_wrapper::_rc_pub = nullptr
actuator_controls_s df_bebop_bus_wrapper::_controls [1]
actuator_outputs_s df_bebop_bus_wrapper::_outputs
actuator_armed_s df_bebop_bus_wrapper::_armed
MixerGroup * df_bebop_bus_wrapper::_mixers = nullptr
Detailed Description
This is a wrapper around the Parrot Bebop bus driver of the DriverFramework.
It sends the motor and contol commands to the Bebop and reads its status and informations.
Definition in file df_bebop_bus_wrapper.cpp.
Function Documentation
int df_bebop_bus_wrapper_main (int argc, char * argv[])
Definition at line 589 of file df_bebop_bus_wrapper.cpp.
References df_bebop_bus_wrapper::clear_errors(), df_bebop_bus_wrapper::info(), df_bebop_bus_wrapper::start(), df_bebop_bus_wrapper::stop(), and df_bebop_bus_wrapper::usage().