PX4 Firmware: src/drivers/px4io/px4io_uploader.cpp File Reference
px4io_uploader.cpp File Reference
#include <px4_config.h>
#include <sys/types.h>
#include <stdlib.h>
#include <stdint.h>
#include <stdbool.h>
#include <assert.h>
#include <errno.h>
#include <string.h>
#include <stdio.h>
#include <stdarg.h>
#include <unistd.h>
#include <fcntl.h>
#include <poll.h>
#include <termios.h>
#include <sys/stat.h>
#include <nuttx/arch.h>
#include <crc32.h>
#include "uploader.h"
#include <board_config.h>
Functions
static int read_with_retry (int fd, void *buf, size_t n)
Function Documentation
static int read_with_retry (int fd, void * buf, size_t n) static
Definition at line 412 of file px4io_uploader.cpp.
References read().
Referenced by PX4IO_Uploader::program(), PX4IO_Uploader::verify_rev2(), and PX4IO_Uploader::verify_rev3().