PX4 Firmware: src/drivers/imu/fxos8701cq/fxos8701cq_main.cpp File Reference
fxos8701cq_main.cpp File Reference
#include "FXOS8701CQ.hpp"
#include <px4_platform_common/getopt.h>
Namespaces
fxos8701cq
Local functions in support of the shell command.
Functions
int fxos8701cq::start (bool external_bus, enum Rotation rotation)
Start the driver.
int fxos8701cq::info ()
Print a little info about the driver.
int fxos8701cq::stop ()
Stop the driver.
int fxos8701cq::regdump ()
dump registers from device
int fxos8701cq::usage ()
Prints info about the driver argument usage.
int fxos8701cq::test_error ()
trigger an error
__EXPORT int fxos8701cq_main (int argc, char *argv[])
Variables
FXOS8701CQ * fxos8701cq::g_dev {nullptr}
Function Documentation
fxos8701cq_main()
int fxos8701cq_main (int argc, char * argv[])
Definition at line 185 of file fxos8701cq_main.cpp.
References fxos8701cq::info(), fxos8701cq::regdump(), ROTATION_NONE, fxos8701cq::start(), fxos8701cq::stop(), fxos8701cq::test_error(), and fxos8701cq::usage().
Referenced by fxos8701cq::usage().