PX4 Firmware: IntrusiveQueue< T > Class Template Reference
IntrusiveQueue< T > Class Template Reference
#include <IntrusiveQueue.hpp>
Classes
struct Iterator
Public Member Functions
bool empty () const
T front () const
T back () const
size_t size () const
void push (T newNode)
T pop ()
bool remove (T removeNode)
Iterator begin ()
Iterator end ()
Private Attributes
T _head {nullptr}
T _tail {nullptr}
Detailed Description
template<class T>
class IntrusiveQueue< T >
Definition at line 39 of file IntrusiveQueue.hpp.
Member Function Documentation
back()
template<class T> T IntrusiveQueue< T >::back () const inline
Definition at line 46 of file IntrusiveQueue.hpp.
References IntrusiveQueue< T >::_tail.
Referenced by IntrusiveQueueTest::test_push_duplicate().
begin()
template<class T> Iterator IntrusiveQueue< T >::begin () inline
Definition at line 147 of file IntrusiveQueue.hpp.
References IntrusiveQueue< T >::_head, and IntrusiveQueue< T >::Iterator::Iterator().
empty()
template<class T> bool IntrusiveQueue< T >::empty () const inline
Definition at line 43 of file IntrusiveQueue.hpp.
References IntrusiveQueue< T >::_head.
Referenced by IntrusiveQueue< T >::pop(), IntrusiveQueueTest::test_pop(), IntrusiveQueueTest::test_push(), IntrusiveQueueTest::test_push_duplicate(), and IntrusiveQueueTest::test_remove().
end()
template<class T> Iterator IntrusiveQueue< T >::end () inline
Definition at line 148 of file IntrusiveQueue.hpp.
References IntrusiveQueue< T >::Iterator::Iterator().
front()
template<class T> T IntrusiveQueue< T >::front () const inline
Definition at line 45 of file IntrusiveQueue.hpp.
References IntrusiveQueue< T >::_head.
Referenced by IntrusiveQueue< T >::size(), IntrusiveQueueTest::test_pop(), IntrusiveQueueTest::test_push(), and IntrusiveQueueTest::test_push_duplicate().
pop()
template<class T> T IntrusiveQueue< T >::pop () inline
Definition at line 77 of file IntrusiveQueue.hpp.
References IntrusiveQueue< T >::_head, IntrusiveQueue< T >::_tail, and IntrusiveQueue< T >::empty().
Referenced by IntrusiveQueueTest::test_pop(), IntrusiveQueueTest::test_push(), IntrusiveQueueTest::test_push_duplicate(), and IntrusiveQueueTest::test_remove().
push()
template<class T> void IntrusiveQueue< T >::push (T newNode) inline
Definition at line 59 of file IntrusiveQueue.hpp.
References IntrusiveQueue< T >::_head, and IntrusiveQueue< T >::_tail.
Referenced by IntrusiveQueueTest::test_pop(), IntrusiveQueueTest::test_push(), IntrusiveQueueTest::test_push_duplicate(), and IntrusiveQueueTest::test_remove().
remove()
template<class T> bool IntrusiveQueue< T >::remove (T removeNode) inline
Definition at line 98 of file IntrusiveQueue.hpp.
References IntrusiveQueue< T >::_head.
size()
template<class T> size_t IntrusiveQueue< T >::size () const inline
Definition at line 48 of file IntrusiveQueue.hpp.
References IntrusiveQueue< T >::front().
Referenced by IntrusiveQueueTest::test_pop(), IntrusiveQueueTest::test_push(), IntrusiveQueueTest::test_push_duplicate(), and IntrusiveQueueTest::test_remove().
Member Data Documentation
_head
template<class T> T IntrusiveQueue< T >::_head {nullptr} private
Definition at line 152 of file IntrusiveQueue.hpp.
Referenced by IntrusiveQueue< T >::begin(), IntrusiveQueue< T >::empty(), IntrusiveQueue< T >::front(), IntrusiveQueue< T >::pop(), IntrusiveQueue< T >::push(), and IntrusiveQueue< T >::remove().
_tail
template<class T> T IntrusiveQueue< T >::_tail {nullptr} private
Definition at line 153 of file IntrusiveQueue.hpp.
Referenced by IntrusiveQueue< T >::back(), IntrusiveQueue< T >::pop(), and IntrusiveQueue< T >::push().
The documentation for this class was generated from the following file:
src/include/containers/IntrusiveQueue.hpp