PX4 Firmware: BMI055_gyro Class Reference
BMI055_gyro Class Reference
#include <BMI055_gyro.hpp>
Classes
struct BMI_GyroReport
Report conversation within the BMI055_gyro, including command byte and interrupt status.
Public Member Functions
BMI055_gyro (int bus, const char *path_gyro, uint32_t device, enum Rotation rotation)
virtual ~BMI055_gyro ()
virtual int init ()
virtual ssize_t read (struct file *filp, char *buffer, size_t buflen)
virtual int ioctl (struct file *filp, int cmd, unsigned long arg)
void print_info ()
Diagnostics - print some basic information about the driver.
void print_registers ()
void test_error ()
Public Member Functions inherited from BMI055
BMI055 (const char *name, const char *devname, int bus, uint32_t device, enum spi_mode_e mode, uint32_t frequency, enum Rotation rotation)
virtual ~BMI055 ()=default
Protected Member Functions
virtual int probe ()
Protected Member Functions inherited from BMI055
uint8_t read_reg (unsigned reg)
Read a register from the BMI055.
uint16_t read_reg16 (unsigned reg)
void write_reg (unsigned reg, uint8_t value)
Write a register in the BMI055.
BMI055 (const BMI055 &)
BMI055 operator= (const BMI055 &)
Private Member Functions
void start ()
Start automatic measurement.
void stop ()
Stop automatic measurement.
int reset ()
Reset chip.
void measure ()
Fetch measurements from the sensor and update the report buffers.
void modify_reg (unsigned reg, uint8_t clearbits, uint8_t setbits)
Modify a register in the BMI055_gyro.
void write_checked_reg (unsigned reg, uint8_t value)
Write a register in the BMI055_gyro, updating _checked_values.
int set_gyro_range (unsigned max_dps)
Set the BMI055_gyro measurement range.
int self_test ()
Measurement self test.
int gyro_set_sample_rate (float desired_sample_rate_hz)
void check_registers (void)
BMI055_gyro (const BMI055_gyro &)
BMI055_gyro operator= (const BMI055_gyro &)
Static Private Member Functions
static void measure_trampoline (void *arg)
Static trampoline from the hrt_call context; because we don't have a generic hrt wrapper yet.
Private Attributes
perf_counter_t _sample_perf
perf_counter_t _measure_interval
perf_counter_t _bad_transfers
perf_counter_t _bad_registers
ringbuffer::RingBuffer * _gyro_reports
struct gyro_calibration_s _gyro_scale
float _gyro_range_scale
float _gyro_range_rad_s
orb_advert_t _gyro_topic
int _gyro_orb_class_instance
int _gyro_class_instance
float _gyro_sample_rate
math::LowPassFilter2p _gyro_filter_x
math::LowPassFilter2p _gyro_filter_y
math::LowPassFilter2p _gyro_filter_z
Integrator _gyro_int
uint8_t _checked_values [BMI055_GYRO_NUM_CHECKED_REGISTERS]
uint8_t _checked_bad [BMI055_GYRO_NUM_CHECKED_REGISTERS]
float _last_temperature
Static Private Attributes
static const uint8_t _checked_registers [BMI055_GYRO_NUM_CHECKED_REGISTERS]
Additional Inherited Members
Protected Attributes inherited from BMI055
uint8_t _whoami
struct hrt_call _call
whoami result
unsigned _call_interval
unsigned _dlpf_freq
uint8_t _register_wait
uint64_t _reset_wait
enum Rotation _rotation
uint8_t _checked_next
Detailed Description
Definition at line 143 of file BMI055_gyro.hpp.
Constructor & Destructor Documentation
BMI055_gyro::BMI055_gyro (int bus, const char * path_gyro, uint32_t device, enum Rotation rotation)
Definition at line 50 of file BMI055_gyro.cpp.
References BMI055::_call, _gyro_class_instance, _gyro_filter_x, _gyro_filter_y, _gyro_filter_z, _gyro_int, _gyro_orb_class_instance, _gyro_range_rad_s, _gyro_range_scale, _gyro_sample_rate, _gyro_scale, _gyro_topic, _last_temperature, BMI055_GYRO_DEFAULT_DRIVER_FILTER_FREQ, BMI055_GYRO_DEFAULT_RATE, BMI055_GYRO_MAX_PUBLISH_RATE, DRV_GYR_DEVTYPE_BMI055, f(), gyro_calibration_s::x_offset, gyro_calibration_s::x_scale, gyro_calibration_s::y_offset, gyro_calibration_s::y_scale, gyro_calibration_s::z_offset, and gyro_calibration_s::z_scale.
BMI055_gyro::~BMI055_gyro () virtual
Definition at line 83 of file BMI055_gyro.cpp.
References _bad_registers, _bad_transfers, _gyro_class_instance, _gyro_reports, _measure_interval, _sample_perf, GYRO_BASE_DEVICE_PATH, perf_free(), and stop().
BMI055_gyro::BMI055_gyro (const BMI055_gyro &) private
Member Function Documentation
void BMI055_gyro::check_registers (void) private
Definition at line 539 of file BMI055_gyro.cpp.
References _bad_registers, _checked_bad, BMI055::_checked_next, _checked_registers, _checked_values, BMI055::_register_wait, BMI055::_reset_wait, BMI055_GYR_SOFTRESET, BMI055_GYRO_NUM_CHECKED_REGISTERS, BMI055_SOFT_RESET, hrt_absolute_time(), perf_count(), BMI055::read_reg(), and BMI055::write_reg().
Referenced by measure().
int BMI055_gyro::gyro_set_sample_rate (float desired_sample_rate_hz) private
Definition at line 218 of file BMI055_gyro.cpp.
References _gyro_sample_rate, BMI055_GYR_BW, BMI055_GYRO_BW_MASK, BMI055_GYRO_RATE_100, BMI055_GYRO_RATE_1000, BMI055_GYRO_RATE_2000, BMI055_GYRO_RATE_400, modify_reg(), and OK.
Referenced by ioctl(), and reset().
int BMI055_gyro::init () virtual
Definition at line 105 of file BMI055_gyro.cpp.
References _gyro_class_instance, _gyro_orb_class_instance, _gyro_reports, _gyro_scale, _gyro_topic, DEVICE_DEBUG, GYRO_BASE_DEVICE_PATH, gyro_report, lis3mdl::init(), measure(), OK, orb_advertise_multi(), ORB_ID, ORB_PRIO_HIGH, ORB_PRIO_MAX, reset(), warnx, gyro_calibration_s::x_offset, gyro_calibration_s::x_scale, gyro_calibration_s::y_offset, gyro_calibration_s::y_scale, gyro_calibration_s::z_offset, and gyro_calibration_s::z_scale.
int BMI055_gyro::ioctl (struct file * filp, int cmd, unsigned long arg) virtual
Definition at line 309 of file BMI055_gyro.cpp.
References BMI055::_call, BMI055::_call_interval, _gyro_filter_x, _gyro_filter_y, _gyro_filter_z, _gyro_range_rad_s, _gyro_reports, _gyro_sample_rate, _gyro_scale, BMI055_GYRO_DEFAULT_RATE, BMI055_GYRO_MAX_RATE, BMI055_TIMER_REDUCTION, math::LowPassFilter2p::get_cutoff_freq(), gyro_set_sample_rate(), GYROIOCGRANGE, GYROIOCGSAMPLERATE, GYROIOCGSCALE, GYROIOCSRANGE, GYROIOCSSAMPLERATE, GYROIOCSSCALE, M_PI_F, OK, hrt_call::period, reset(), SENSOR_POLLRATE_DEFAULT, SENSOR_POLLRATE_EXTERNAL, SENSOR_POLLRATE_MANUAL, SENSOR_POLLRATE_MAX, SENSORIOCGPOLLRATE, SENSORIOCRESET, SENSORIOCSPOLLRATE, SENSORIOCSQUEUEDEPTH, math::LowPassFilter2p::set_cutoff_frequency(), set_gyro_range(), start(), and stop().
void BMI055_gyro::measure () private
Fetch measurements from the sensor and update the report buffers.
Definition at line 582 of file BMI055_gyro.cpp.
References _bad_registers, _bad_transfers, _gyro_filter_x, _gyro_filter_y, _gyro_filter_z, _gyro_int, _gyro_range_scale, _gyro_reports, _gyro_scale, _gyro_topic, _last_temperature, _measure_interval, BMI055::_register_wait, BMI055::_reset_wait, BMI055::_rotation, _sample_perf, math::LowPassFilter2p::apply(), BMI055_ACC_TEMP, BMI055_GYR_X_L, check_registers(), BMI055_gyro::BMI_GyroReport::cmd, DIR_READ, gyro_report, BMI055_gyro::BMI_GyroReport::gyro_x, BMI055_gyro::BMI_GyroReport::gyro_y, BMI055_gyro::BMI_GyroReport::gyro_z, hrt_absolute_time(), OK, ORB_ID, orb_publish(), perf_begin(), perf_count(), perf_end(), perf_event_count(), Integrator::put(), BMI055::read_reg(), rotate_3f(), gyro_calibration_s::x_offset, gyro_calibration_s::x_scale, gyro_calibration_s::y_offset, gyro_calibration_s::y_scale, gyro_calibration_s::z_offset, and gyro_calibration_s::z_scale.
Referenced by init(), measure_trampoline(), read(), and self_test().
void BMI055_gyro::measure_trampoline (void * arg) static private
Static trampoline from the hrt_call context; because we don't have a generic hrt wrapper yet.
Called by the HRT in interrupt context at the specified rate if automatic polling is enabled.
Parameters
arg Instance pointer for the driver that is polling.
Definition at line 530 of file BMI055_gyro.cpp.
References measure().
Referenced by start().
void BMI055_gyro::modify_reg (unsigned reg, uint8_t clearbits, uint8_t setbits) private
Modify a register in the BMI055_gyro.
Bits are cleared before bits are set.
Parameters
reg The register to modify.
clearbits Bits in the register to clear.
setbits Bits in the register to set.
Definition at line 434 of file BMI055_gyro.cpp.
References BMI055::read_reg(), and write_checked_reg().
Referenced by gyro_set_sample_rate(), and set_gyro_range().
BMI055_gyro BMI055_gyro::operator= (const BMI055_gyro &) private
void BMI055_gyro::print_info ()
Diagnostics - print some basic information about the driver.
Definition at line 721 of file BMI055_gyro.cpp.
References _bad_registers, _bad_transfers, _checked_bad, BMI055::_checked_next, _checked_registers, _checked_values, _gyro_reports, _last_temperature, _measure_interval, _sample_perf, BMI055_GYRO_NUM_CHECKED_REGISTERS, perf_print_counter(), PX4_INFO, and BMI055::read_reg().
void BMI055_gyro::print_registers ()
Definition at line 756 of file BMI055_gyro.cpp.
References _checked_registers, and BMI055::read_reg().
Referenced by test_error().
int BMI055_gyro::probe () protected virtual
Definition at line 198 of file BMI055_gyro.cpp.
References _checked_bad, _checked_values, BMI055::_whoami, BMI055_GYR_CHIP_ID, BMI055_GYR_WHO_AM_I, DEVICE_DEBUG, OK, and BMI055::read_reg().
ssize_t BMI055_gyro::read (struct file * filp, char * buffer, size_t buflen) virtual
Definition at line 271 of file BMI055_gyro.cpp.
References BMI055::_call_interval, _gyro_reports, gyro_report, and measure().
int BMI055_gyro::reset () private
Reset chip.
Resets the chip and measurements ranges, but not scale and offset.
Definition at line 161 of file BMI055_gyro.cpp.
References _checked_registers, _checked_values, BMI055_GYR_BW, BMI055_GYR_DRDY_INT1, BMI055_GYR_DRDY_INT_EN, BMI055_GYR_INT_EN_0, BMI055_GYR_INT_MAP_1, BMI055_GYR_LPM1, BMI055_GYR_RANGE, BMI055_GYR_SOFTRESET, BMI055_GYRO_DEFAULT_RANGE_DPS, BMI055_GYRO_DEFAULT_RATE, BMI055_GYRO_NORMAL, BMI055_GYRO_NUM_CHECKED_REGISTERS, BMI055_SOFT_RESET, gyro_set_sample_rate(), OK, BMI055::read_reg(), set_gyro_range(), usleep(), write_checked_reg(), and BMI055::write_reg().
Referenced by init(), ioctl(), and start().
int BMI055_gyro::self_test () private
Measurement self test.
Returns
0 on success, 1 on failure
Definition at line 249 of file BMI055_gyro.cpp.
References _sample_perf, measure(), and perf_event_count().
int BMI055_gyro::set_gyro_range (unsigned max_dps) private
Set the BMI055_gyro measurement range.
Parameters
max_dps The maximum DPS value the range must support.
Returns
OK if the value can be supported, -EINVAL otherwise.
Definition at line 458 of file BMI055_gyro.cpp.
References _gyro_range_rad_s, _gyro_range_scale, BMI055_GYR_RANGE, BMI055_GYRO_RANGE_1000_DPS, BMI055_GYRO_RANGE_125_DPS, BMI055_GYRO_RANGE_2000_DPS, BMI055_GYRO_RANGE_250_DPS, BMI055_GYRO_RANGE_500_DPS, M_PI_F, modify_reg(), and OK.
Referenced by ioctl(), and reset().
void BMI055_gyro::start () private
Start automatic measurement.
Definition at line 507 of file BMI055_gyro.cpp.
References BMI055::_call, BMI055::_call_interval, _gyro_reports, BMI055_TIMER_REDUCTION, hrt_call_every(), measure_trampoline(), reset(), and stop().
Referenced by ioctl().
void BMI055_gyro::stop () private
Stop automatic measurement.
Definition at line 524 of file BMI055_gyro.cpp.
References BMI055::_call, and hrt_cancel().
Referenced by ioctl(), start(), and ~BMI055_gyro().
void BMI055_gyro::test_error ()
Definition at line 263 of file BMI055_gyro.cpp.
References BMI055_GYR_SOFTRESET, BMI055_SOFT_RESET, print_registers(), and BMI055::write_reg().
void BMI055_gyro::write_checked_reg (unsigned reg, uint8_t value) private
Write a register in the BMI055_gyro, updating _checked_values.
Parameters
reg The register to write.
value The new value to write.
Definition at line 445 of file BMI055_gyro.cpp.
References _checked_bad, _checked_registers, _checked_values, BMI055_GYRO_NUM_CHECKED_REGISTERS, and BMI055::write_reg().
Referenced by modify_reg(), and reset().
Member Data Documentation
perf_counter_t BMI055_gyro::_bad_registers private
Definition at line 173 of file BMI055_gyro.hpp.
Referenced by check_registers(), measure(), print_info(), and ~BMI055_gyro().
perf_counter_t BMI055_gyro::_bad_transfers private
Definition at line 172 of file BMI055_gyro.hpp.
Referenced by measure(), print_info(), and ~BMI055_gyro().
uint8_t BMI055_gyro::_checked_bad[BMI055_GYRO_NUM_CHECKED_REGISTERS] private
Definition at line 199 of file BMI055_gyro.hpp.
Referenced by check_registers(), print_info(), probe(), and write_checked_reg().
const uint8_t BMI055_gyro::_checked_registers static private
Initial value:
= {    BMI055_GYR_CHIP_ID,
                                            BMI055_GYR_LPM1,
                                            BMI055_GYR_BW,
                                            BMI055_GYR_RANGE,
                                            BMI055_GYR_INT_EN_0,
                                            BMI055_GYR_INT_EN_1,
                                            BMI055_GYR_INT_MAP_1
                                           }
Definition at line 197 of file BMI055_gyro.hpp.
Referenced by check_registers(), print_info(), print_registers(), reset(), and write_checked_reg().
uint8_t BMI055_gyro::_checked_values[BMI055_GYRO_NUM_CHECKED_REGISTERS] private
Definition at line 198 of file BMI055_gyro.hpp.
Referenced by check_registers(), print_info(), probe(), reset(), and write_checked_reg().
int BMI055_gyro::_gyro_class_instance private
Definition at line 183 of file BMI055_gyro.hpp.
Referenced by BMI055_gyro(), init(), and ~BMI055_gyro().
math::LowPassFilter2p BMI055_gyro::_gyro_filter_x private
Definition at line 187 of file BMI055_gyro.hpp.
Referenced by BMI055_gyro(), ioctl(), and measure().
math::LowPassFilter2p BMI055_gyro::_gyro_filter_y private
Definition at line 188 of file BMI055_gyro.hpp.
Referenced by BMI055_gyro(), ioctl(), and measure().
math::LowPassFilter2p BMI055_gyro::_gyro_filter_z private
Definition at line 189 of file BMI055_gyro.hpp.
Referenced by BMI055_gyro(), ioctl(), and measure().
Integrator BMI055_gyro::_gyro_int private
Definition at line 191 of file BMI055_gyro.hpp.
Referenced by BMI055_gyro(), and measure().
int BMI055_gyro::_gyro_orb_class_instance private
Definition at line 182 of file BMI055_gyro.hpp.
Referenced by BMI055_gyro(), and init().
float BMI055_gyro::_gyro_range_rad_s private
Definition at line 179 of file BMI055_gyro.hpp.
Referenced by BMI055_gyro(), ioctl(), and set_gyro_range().
float BMI055_gyro::_gyro_range_scale private
Definition at line 178 of file BMI055_gyro.hpp.
Referenced by BMI055_gyro(), measure(), and set_gyro_range().
ringbuffer::RingBuffer* BMI055_gyro::_gyro_reports private
Definition at line 175 of file BMI055_gyro.hpp.
Referenced by init(), ioctl(), measure(), print_info(), read(), start(), and ~BMI055_gyro().
float BMI055_gyro::_gyro_sample_rate private
Definition at line 185 of file BMI055_gyro.hpp.
Referenced by BMI055_gyro(), gyro_set_sample_rate(), and ioctl().
struct gyro_calibration_s BMI055_gyro::_gyro_scale private
Definition at line 177 of file BMI055_gyro.hpp.
Referenced by BMI055_gyro(), init(), ioctl(), and measure().
orb_advert_t BMI055_gyro::_gyro_topic private
Definition at line 181 of file BMI055_gyro.hpp.
Referenced by BMI055_gyro(), init(), and measure().
float BMI055_gyro::_last_temperature private
Definition at line 202 of file BMI055_gyro.hpp.
Referenced by BMI055_gyro(), measure(), and print_info().
perf_counter_t BMI055_gyro::_measure_interval private
Definition at line 171 of file BMI055_gyro.hpp.
Referenced by measure(), print_info(), and ~BMI055_gyro().
perf_counter_t BMI055_gyro::_sample_perf private
Definition at line 170 of file BMI055_gyro.hpp.
Referenced by measure(), print_info(), self_test(), and ~BMI055_gyro().
The documentation for this class was generated from the following files:
src/drivers/imu/bmi055/BMI055_gyro.hpp
src/drivers/imu/bmi055/BMI055_gyro.cpp