PX4 Firmware: MavlinkStreamServoOutputRaw< N > Class Template Reference
MavlinkStreamServoOutputRaw< N > Class Template Reference
Public Member Functions
const char * get_name () const
uint16_t get_id ()
unsigned get_size ()
Get maximal total messages size on update.
Public Member Functions inherited from MavlinkStream
MavlinkStream (Mavlink *mavlink)
virtual ~MavlinkStream ()=default
MavlinkStream (const MavlinkStream &)=delete
MavlinkStream & operator= (const MavlinkStream &)=delete
MavlinkStream (MavlinkStream &&)=delete
MavlinkStream & operator= (MavlinkStream &&)=delete
void set_interval (const int interval)
Get the interval.
int get_interval ()
Get the interval.
int update (const hrt_abstime &t)
Update subscriptions and send message if necessary.
virtual bool const_rate ()
virtual unsigned get_size_avg ()
Get the average message size.
bool first_message_sent () const
void reset_last_sent ()
Reset the time of last sent to 0.
Static Public Member Functions
static uint16_t get_id_static ()
static const char * get_name_static ()
static MavlinkStream * new_instance (Mavlink *mavlink)
Protected Member Functions
MavlinkStreamServoOutputRaw (Mavlink *mavlink)
bool send (const hrt_abstime t)
Protected Member Functions inherited from MavlinkStream
virtual void update_data ()
Function to collect/update data for the streams at a high rate independant of actual stream rate.
Private Member Functions
MavlinkStreamServoOutputRaw (MavlinkStreamServoOutputRaw &)=delete
MavlinkStreamServoOutputRaw & operator= (const MavlinkStreamServoOutputRaw &)=delete
Private Attributes
MavlinkOrbSubscription * _act_sub
uint64_t _act_time
Additional Inherited Members
Public Attributes inherited from MavlinkStream
MavlinkStream * next {nullptr}
Protected Attributes inherited from MavlinkStream
Mavlink *const _mavlink
int _interval {1000000}
if set to negative value = unlimited rate
Detailed Description
template<int N>
class MavlinkStreamServoOutputRaw< N >
Definition at line 2459 of file mavlink_messages.cpp.
Constructor & Destructor Documentation
template<int N> MavlinkStreamServoOutputRaw< N >::MavlinkStreamServoOutputRaw (MavlinkStreamServoOutputRaw< N > &) private delete
template<int N> MavlinkStreamServoOutputRaw< N >::MavlinkStreamServoOutputRaw (Mavlink * mavlink) inline explicit protected
Definition at line 2513 of file mavlink_messages.cpp.
Member Function Documentation
template<int N> uint16_t MavlinkStreamServoOutputRaw< N >::get_id () inline virtual
Implements MavlinkStream.
Definition at line 2472 of file mavlink_messages.cpp.
References MavlinkStreamHeartbeat::get_id_static().
template<int N> static uint16_t MavlinkStreamServoOutputRaw< N >::get_id_static () inline static
Definition at line 2467 of file mavlink_messages.cpp.
template<int N> const char* MavlinkStreamServoOutputRaw< N >::get_name () const inline virtual
Implements MavlinkStream.
Definition at line 2462 of file mavlink_messages.cpp.
References MavlinkStreamServoOutputRaw< N >::get_name_static().
template<int N> static const char* MavlinkStreamServoOutputRaw< N >::get_name_static () inline static
Definition at line 2477 of file mavlink_messages.cpp.
Referenced by MavlinkStreamServoOutputRaw< N >::get_name().
template<int N> unsigned MavlinkStreamServoOutputRaw< N >::get_size () inline virtual
Get maximal total messages size on update.
Implements MavlinkStream.
Definition at line 2499 of file mavlink_messages.cpp.
template<int N> static MavlinkStream* MavlinkStreamServoOutputRaw< N >::new_instance (Mavlink * mavlink) inline static
Definition at line 2494 of file mavlink_messages.cpp.
template<int N> MavlinkStreamServoOutputRaw& MavlinkStreamServoOutputRaw< N >::operator= (const MavlinkStreamServoOutputRaw< N > &) private delete
template<int N> bool MavlinkStreamServoOutputRaw< N >::send (const hrt_abstime t) inline protected virtual
Implements MavlinkStream.
Definition at line 2518 of file mavlink_messages.cpp.
References MavlinkStream::_mavlink, Mavlink::get_channel(), msg, actuator_outputs_s::output, actuator_outputs_s::timestamp, and MavlinkOrbSubscription::update().
Member Data Documentation
template<int N> MavlinkOrbSubscription* MavlinkStreamServoOutputRaw< N >::_act_sub private
Definition at line 2505 of file mavlink_messages.cpp.
template<int N> uint64_t MavlinkStreamServoOutputRaw< N >::_act_time private
Definition at line 2506 of file mavlink_messages.cpp.
The documentation for this class was generated from the following file:
src/modules/mavlink/mavlink_messages.cpp