PX4 Firmware: src/modules/commander/health_flag_helper.cpp File Reference
health_flag_helper.cpp File Reference
Contains helper functions to efficiently set the system health flags from commander and preflight check.
#include "health_flag_helper.h"
Functions
void set_health_flags (uint64_t subsystem_type, bool present, bool enabled, bool ok, vehicle_status_s &status)
void set_health_flags_present_healthy (uint64_t subsystem_type, bool present, bool healthy, vehicle_status_s &status)
void set_health_flags_healthy (uint64_t subsystem_type, bool healthy, vehicle_status_s &status)
Detailed Description
Contains helper functions to efficiently set the system health flags from commander and preflight check.
Author
Philipp Oettershagen (phili.nosp@m.pp.o.nosp@m.etter.nosp@m.shag.nosp@m.en@ma.nosp@m.vt.e.nosp@m.thz.c.nosp@m.h)
Definition in file health_flag_helper.cpp.
Function Documentation
void set_health_flags (uint64_t subsystem_type, bool present, bool enabled, bool ok, vehicle_status_s & status)
Definition at line 44 of file health_flag_helper.cpp.
References vehicle_status_s::onboard_control_sensors_enabled, vehicle_status_s::onboard_control_sensors_health, vehicle_status_s::onboard_control_sensors_present, and PX4_DEBUG.
Referenced by Preflight::accelerometerCheck(), Preflight::airspeedCheck(), Preflight::baroCheck(), Preflight::ekf2Check(), Preflight::gyroCheck(), Preflight::magnometerCheck(), Preflight::preflightCheck(), Commander::run(), set_health_flags_healthy(), and set_health_flags_present_healthy().
void set_health_flags_healthy (uint64_t subsystem_type, bool healthy, vehicle_status_s & status)
Definition at line 76 of file health_flag_helper.cpp.
References vehicle_status_s::onboard_control_sensors_enabled, vehicle_status_s::onboard_control_sensors_present, and set_health_flags().
Referenced by Commander::estimator_check(), Preflight::imuConsistencyCheck(), and Preflight::magConsistencyCheck().
void set_health_flags_present_healthy (uint64_t subsystem_type, bool present, bool healthy, vehicle_status_s & status)
Definition at line 70 of file health_flag_helper.cpp.
References vehicle_status_s::onboard_control_sensors_enabled, and set_health_flags().
Referenced by Commander::estimator_check().