PX4 Firmware: CameraFeedback Class Reference
CameraFeedback Class Reference
#include <camera_feedback.hpp>
Public Member Functions
CameraFeedback ()
Constructor.
~CameraFeedback ()
Destructor, also kills task.
int start ()
Start the task.
void stop ()
Stop the task.
Private Member Functions
void task_main ()
Static Private Member Functions
static int task_main_trampoline (int argc, char *argv[])
Shim for calling task_main from task_create.
Private Attributes
bool _task_should_exit
if true, task should exit
int _main_task
handle for task
int _trigger_sub
int _gpos_sub
int _att_sub
orb_advert_t _capture_pub
param_t _p_camera_capture_feedback
int32_t _camera_capture_feedback
Detailed Description
Definition at line 65 of file camera_feedback.hpp.
Constructor & Destructor Documentation
CameraFeedback()
CameraFeedback::CameraFeedback ()
Constructor.
Definition at line 49 of file camera_feedback.cpp.
References _camera_capture_feedback, _p_camera_capture_feedback, param_find(), and param_get().
Referenced by camera_feedback_main().
~CameraFeedback()
CameraFeedback::~CameraFeedback ()
Destructor, also kills task.
Definition at line 66 of file camera_feedback.cpp.
References _main_task, _task_should_exit, and camera_feedback::g_camera_feedback.
Member Function Documentation
start()
int CameraFeedback::start ()
Start the task.
Returns
OK on success.
Definition at line 93 of file camera_feedback.cpp.
References _main_task, OK, task_main_trampoline(), and warn.
Referenced by camera_feedback_main().
stop()
void CameraFeedback::stop ()
Stop the task.
Definition at line 114 of file camera_feedback.cpp.
References camera_feedback::g_camera_feedback.
Referenced by camera_feedback_main().
task_main()
void CameraFeedback::task_main () private
Definition at line 123 of file camera_feedback.cpp.
References _att_sub, _camera_capture_feedback, _capture_pub, _gpos_sub, _main_task, _task_should_exit, _trigger_sub, vehicle_global_position_s::alt, camera_capture_s::alt, f(), camera_capture_s::ground_distance, vehicle_global_position_s::lat, camera_capture_s::lat, vehicle_global_position_s::lon, camera_capture_s::lon, orb_check(), orb_copy(), ORB_ID, ORB_PRIO_DEFAULT, orb_publish_auto(), orb_subscribe(), orb_unsubscribe(), px4_poll(), vehicle_attitude_s::q, camera_capture_s::q, camera_capture_s::result, camera_trigger_s::seq, camera_capture_s::seq, vehicle_global_position_s::terrain_alt, vehicle_global_position_s::terrain_alt_valid, camera_capture_s::timestamp, vehicle_attitude_s::timestamp, camera_trigger_s::timestamp, vehicle_global_position_s::timestamp, camera_trigger_s::timestamp_utc, and camera_capture_s::timestamp_utc.
Referenced by task_main_trampoline().
task_main_trampoline()
int CameraFeedback::task_main_trampoline (int argc, char * argv[]) static private
Shim for calling task_main from task_create.
Definition at line 232 of file camera_feedback.cpp.
References camera_feedback::g_camera_feedback, and task_main().
Referenced by start().
Member Data Documentation
_att_sub
int CameraFeedback::_att_sub private
Definition at line 97 of file camera_feedback.hpp.
Referenced by task_main().
_camera_capture_feedback
int32_t CameraFeedback::_camera_capture_feedback private
Definition at line 103 of file camera_feedback.hpp.
Referenced by CameraFeedback(), and task_main().
_capture_pub
orb_advert_t CameraFeedback::_capture_pub private
Definition at line 99 of file camera_feedback.hpp.
Referenced by task_main().
_gpos_sub
int CameraFeedback::_gpos_sub private
Definition at line 96 of file camera_feedback.hpp.
Referenced by task_main().
_main_task
int CameraFeedback::_main_task private
handle for task
Definition at line 93 of file camera_feedback.hpp.
Referenced by start(), task_main(), and ~CameraFeedback().
_p_camera_capture_feedback
param_t CameraFeedback::_p_camera_capture_feedback private
Definition at line 101 of file camera_feedback.hpp.
Referenced by CameraFeedback().
_task_should_exit
bool CameraFeedback::_task_should_exit private
if true, task should exit
Definition at line 92 of file camera_feedback.hpp.
Referenced by task_main(), and ~CameraFeedback().
_trigger_sub
int CameraFeedback::_trigger_sub private
Definition at line 95 of file camera_feedback.hpp.
Referenced by task_main().
The documentation for this class was generated from the following files:
src/modules/camera_feedback/camera_feedback.hpp
src/modules/camera_feedback/camera_feedback.cpp