PX4 Firmware: MavlinkStreamGPSRawInt Class Reference
MavlinkStreamGPSRawInt Class Reference
Public Member Functions
const char * get_name () const override
uint16_t get_id () override
unsigned get_size () override
Get maximal total messages size on update.
Public Member Functions inherited from MavlinkStream
MavlinkStream (Mavlink *mavlink)
virtual ~MavlinkStream ()=default
MavlinkStream (const MavlinkStream &)=delete
MavlinkStream & operator= (const MavlinkStream &)=delete
MavlinkStream (MavlinkStream &&)=delete
MavlinkStream & operator= (MavlinkStream &&)=delete
void set_interval (const int interval)
Get the interval.
int get_interval ()
Get the interval.
int update (const hrt_abstime &t)
Update subscriptions and send message if necessary.
virtual bool const_rate ()
virtual unsigned get_size_avg ()
Get the average message size.
bool first_message_sent () const
void reset_last_sent ()
Reset the time of last sent to 0.
Public Member Functions inherited from ListNode< MavlinkStream *>
void setSibling (MavlinkStream * sibling)
const MavlinkStream * getSibling () const
Static Public Member Functions
static const char * get_name_static ()
static uint16_t get_id_static ()
static MavlinkStream * new_instance (Mavlink *mavlink)
Protected Member Functions
MavlinkStreamGPSRawInt (Mavlink *mavlink)
bool send (const hrt_abstime t) override
Protected Member Functions inherited from MavlinkStream
virtual void update_data ()
Function to collect/update data for the streams at a high rate independant of actual stream rate.
Private Member Functions
MavlinkStreamGPSRawInt (MavlinkStreamGPSRawInt &)=delete
MavlinkStreamGPSRawInt & operator= (const MavlinkStreamGPSRawInt &)=delete
Private Attributes
MavlinkOrbSubscription * _gps_sub
uint64_t _gps_time
Additional Inherited Members
Protected Attributes inherited from MavlinkStream
Mavlink *const _mavlink
int _interval {1000000}
if set to negative value = unlimited rate
Protected Attributes inherited from ListNode< MavlinkStream *>
MavlinkStream * _list_node_sibling
Detailed Description
Definition at line 1485 of file mavlink_messages.cpp.
Constructor & Destructor Documentation
MavlinkStreamGPSRawInt() [1/2]
MavlinkStreamGPSRawInt::MavlinkStreamGPSRawInt (MavlinkStreamGPSRawInt &) private delete
MavlinkStreamGPSRawInt() [2/2]
MavlinkStreamGPSRawInt::MavlinkStreamGPSRawInt (Mavlink * mavlink) inline explicit protected
Definition at line 1527 of file mavlink_messages.cpp.
Member Function Documentation
get_id()
uint16_t MavlinkStreamGPSRawInt::get_id () inline override virtual
Implements MavlinkStream.
Definition at line 1503 of file mavlink_messages.cpp.
References MavlinkStreamHeartbeat::get_id_static().
get_id_static()
static uint16_t MavlinkStreamGPSRawInt::get_id_static () inline static
Definition at line 1498 of file mavlink_messages.cpp.
get_name()
const char* MavlinkStreamGPSRawInt::get_name () const inline override virtual
Implements MavlinkStream.
Definition at line 1488 of file mavlink_messages.cpp.
References get_name_static().
get_name_static()
static const char* MavlinkStreamGPSRawInt::get_name_static () inline static
Definition at line 1493 of file mavlink_messages.cpp.
Referenced by get_name().
get_size()
unsigned MavlinkStreamGPSRawInt::get_size () inline override virtual
Get maximal total messages size on update.
Implements MavlinkStream.
Definition at line 1513 of file mavlink_messages.cpp.
new_instance()
static MavlinkStream* MavlinkStreamGPSRawInt::new_instance (Mavlink * mavlink) inline static
Definition at line 1508 of file mavlink_messages.cpp.
operator=()
MavlinkStreamGPSRawInt& MavlinkStreamGPSRawInt::operator= (const MavlinkStreamGPSRawInt &) private delete
send()
bool MavlinkStreamGPSRawInt::send (const hrt_abstime t) inline override protected virtual
Implements MavlinkStream.
Definition at line 1532 of file mavlink_messages.cpp.
References MavlinkStream::_mavlink, vehicle_gps_position_s::alt, vehicle_gps_position_s::alt_ellipsoid, vehicle_gps_position_s::c_variance_rad, cm_uint16_from_m_float(), vehicle_gps_position_s::cog_rad, math::degrees(), vehicle_gps_position_s::eph, vehicle_gps_position_s::epv, vehicle_gps_position_s::fix_type, Mavlink::get_channel(), gps, vehicle_gps_position_s::hdop, vehicle_gps_position_s::lat, vehicle_gps_position_s::lon, msg, vehicle_gps_position_s::s_variance_m_s, vehicle_gps_position_s::satellites_used, vehicle_gps_position_s::timestamp, MavlinkOrbSubscription::update(), vehicle_gps_position_s::vdop, vehicle_gps_position_s::vel_m_s, and matrix::wrap_2pi().
Member Data Documentation
_gps_sub
MavlinkOrbSubscription* MavlinkStreamGPSRawInt::_gps_sub private
Definition at line 1519 of file mavlink_messages.cpp.
_gps_time
uint64_t MavlinkStreamGPSRawInt::_gps_time private
Definition at line 1520 of file mavlink_messages.cpp.
The documentation for this class was generated from the following file:
src/modules/mavlink/mavlink_messages.cpp