PX4 Firmware: src/lib/parameters/param.h File Reference
param.h File Reference
Global flash based parameter store.
#include <stdint.h>
#include <stdbool.h>
#include <sys/types.h>
Classes
union param_value_u
Parameter value union.
struct param_info_s
Static parameter definition structure.
Macros
#define PARAM_FILE_MAXSIZE 4096
Maximum size of the parameter backing file.
#define PARAM_TYPE_INT32 0
Parameter types.
#define PARAM_TYPE_FLOAT 1
#define PARAM_TYPE_STRUCT 100
#define PARAM_TYPE_STRUCT_MAX (16384 + PARAM_TYPE_STRUCT)
#define PARAM_TYPE_UNKNOWN (0xffff)
#define PARAM_INVALID ((uint32_t)0xffffffff)
Handle returned when a parameter cannot be found.
#define PARAM_HASH ((uint32_t)INT32_MAX)
Magic handle for hash check param.
#define PARAM_DEFINE_INT32(_name, _default)
define an int32 parameter
#define PARAM_DEFINE_FLOAT(_name, _default)
define a float parameter
#define PARAM_DEFINE_STRUCT(_name, _default)
define a parameter that points to a structure
Typedefs
typedef uint16_t param_type_t
typedef uint32_t param_t
Parameter handle.
Functions
__EXPORT void param_init (void)
Initialize the param backend.
__EXPORT param_t param_find (const char *name)
Look up a parameter by name.
__EXPORT param_t param_find_no_notification (const char *name)
Look up a parameter by name.
__EXPORT unsigned param_count (void)
Return the total number of parameters.
__EXPORT unsigned param_count_used (void)
Return the actually used number of parameters.
__EXPORT bool param_used (param_t param)
Wether a parameter is in use in the system.
__EXPORT param_t param_for_index (unsigned index)
Look up a parameter by index.
__EXPORT param_t param_for_used_index (unsigned index)
Look up an used parameter by index.
__EXPORT int param_get_index (param_t param)
Look up the index of a parameter.
__EXPORT int param_get_used_index (param_t param)
Look up the index of an used parameter.
__EXPORT const char * param_name (param_t param)
Obtain the name of a parameter.
__EXPORT bool param_is_volatile (param_t param)
Obtain the volatile state of a parameter.
__EXPORT bool param_value_is_default (param_t param)
Test whether a parameter's value has changed from the default.
__EXPORT bool param_value_unsaved (param_t param)
Test whether a parameter's value has been changed but not saved.
__EXPORT param_type_t param_type (param_t param)
Obtain the type of a parameter.
__EXPORT size_t param_size (param_t param)
Determine the size of a parameter.
__EXPORT int param_get (param_t param, void *val)
Copy the value of a parameter.
__EXPORT int param_set (param_t param, const void *val)
Set the value of a parameter.
__EXPORT void param_set_used (param_t param)
Mark a parameter as used.
__EXPORT int param_set_no_notification (param_t param, const void *val)
Set the value of a parameter, but do not notify the system about the change.
__EXPORT void param_notify_changes (void)
Notify the system about parameter changes.
__EXPORT int param_reset (param_t param)
Reset a parameter to its default value.
__EXPORT void param_reset_all (void)
Reset all parameters to their default values.
__EXPORT void param_reset_excludes (const char *excludes[], int num_excludes)
Reset all parameters to their default values except for excluded parameters.
__EXPORT int param_export (int fd, bool only_unsaved)
Export changed parameters to a file.
__EXPORT int param_import (int fd)
Import parameters from a file, discarding any unrecognized parameters.
__EXPORT int param_load (int fd)
Load parameters from a file.
__EXPORT void param_foreach (void(*func)(void *arg, param_t param), void *arg, bool only_changed, bool only_used)
Apply a function to each parameter.
__EXPORT int param_set_default_file (const char *filename)
Set the default parameter file name.
__EXPORT const char * param_get_default_file (void)
Get the default parameter file name.
__EXPORT int param_save_default (void)
Save parameters to the default file.
__EXPORT int param_load_default (void)
Load parameters from the default parameter file.
__EXPORT uint32_t param_hash_check (void)
Generate the hash of all parameters and their values.
__EXPORT void param_control_autosave (bool enable)
Enable/disable the param autosaving.
Detailed Description
Global flash based parameter store.
Global parameter store.
This provides the mechanisms to interface to the PX4 parameter system but replace the IO with non file based flash i/o routines. So that the code my be implemented on a SMALL memory foot print device.
Note that a number of API members are marked const or pure; these assume that the set of parameters cannot change, or that a parameter cannot change type or size over its lifetime. If any of these assumptions are invalidated, the attributes should be re-evaluated.
Definition in file param.h.
Macro Definition Documentation
#define PARAM_DEFINE_FLOAT (_name, _default)
define a float parameter
Definition at line 423 of file param.h.
#define PARAM_DEFINE_INT32 (_name, _default)
define an int32 parameter
Definition at line 420 of file param.h.
#define PARAM_DEFINE_STRUCT (_name, _default)
define a parameter that points to a structure
Definition at line 426 of file param.h.
#define PARAM_FILE_MAXSIZE 4096
Maximum size of the parameter backing file.
Definition at line 53 of file param.h.
#define PARAM_HASH ((uint32_t)INT32_MAX)
Magic handle for hash check param.
Definition at line 108 of file param.h.
Referenced by MavlinkParametersManager::handle_message(), and MavlinkParametersManager::send_one().
#define PARAM_INVALID ((uint32_t)0xffffffff)
Handle returned when a parameter cannot be found.
Definition at line 103 of file param.h.
Referenced by control::BlockParamBase::BlockParamBase(), Preflight::check_calibration(), px4::logger::Logger::check_free_space(), DfMpu9250Wrapper::DfMpu9250Wrapper(), do_compare(), do_find(), do_set(), do_show_index(), ParameterTest::exportImportAll(), FixedwingPositionControl::FixedwingPositionControl(), px4::logger::Logger::get_log_time(), get_parameter_value(), get_params(), CameraInterface::get_pins(), MavlinkParametersManager::handle_message(), PX4FLOW::init(), PX4IO::init(), MPU6000::init(), MPU9250::init(), GPS::initializeCommunicationDump(), vmount::InputMavlinkCmdMount::InputMavlinkCmdMount(), load_mon::LoadMon::LoadMon(), Mavlink::Mavlink(), param_find_internal(), param_for_index(), param_for_used_index(), param_import_callback(), FixedwingPositionControl::parameters_update(), rc_calibration_check(), px4::Replay::readAndApplyParameter(), px4::logger::Logger::run(), GPS::run(), MavlinkReceiver::send_flight_information(), MavlinkParametersManager::send_one(), MavlinkParametersManager::send_param(), MavlinkParametersManager::send_untransmitted(), ParameterTest::SimpleFind(), PX4IO::task_main(), test_param(), AttitudeEstimatorQ::update_parameters(), linux_pwm_out::update_params(), PWMSim::update_params(), snapdragon_pwm::update_params(), UavcanNode::update_params(), PX4FMU::update_params(), PX4FMU::update_pwm_rev_mask(), PX4FMU::update_pwm_trims(), px4::logger::Logger::write_changed_parameters(), px4::logger::Logger::write_parameters(), and px4::logger::Logger::write_version().
#define PARAM_TYPE_FLOAT 1
Definition at line 61 of file param.h.
Referenced by do_compare(), do_set(), do_show_index(), do_show_print(), ParameterTest::exportImport(), ParameterTest::exportImportAll(), param_export(), param_export_internal(), param_get(), param_import_callback(), param_set_internal(), param_size(), MavlinkParametersManager::send_param(), px4::Replay::setUserParams(), px4::logger::Logger::write_changed_parameters(), and px4::logger::Logger::write_parameters().
#define PARAM_TYPE_INT32 0
Parameter types.
Definition at line 60 of file param.h.
Referenced by do_compare(), do_set(), do_show_index(), do_show_print(), ParameterTest::exportImport(), ParameterTest::exportImportAll(), param_export(), param_export_internal(), param_get(), param_import_callback(), param_set_internal(), param_size(), MavlinkParametersManager::send_param(), px4::Replay::setUserParams(), test_param(), px4::logger::Logger::write_changed_parameters(), and px4::logger::Logger::write_parameters().
#define PARAM_TYPE_STRUCT 100
Definition at line 62 of file param.h.
Referenced by do_show_print(), param_export(), param_export_internal(), param_get_value_ptr(), param_set_internal(), and param_size().
#define PARAM_TYPE_STRUCT_MAX (16384 + PARAM_TYPE_STRUCT)
Definition at line 63 of file param.h.
Referenced by do_show_print(), param_export(), param_export_internal(), param_get_value_ptr(), param_set_internal(), and param_size().
#define PARAM_TYPE_UNKNOWN (0xffff)
Definition at line 64 of file param.h.
Referenced by param_type().
Typedef Documentation
typedef uint32_t param_t
Parameter handle.
Parameters are represented by parameter handles, which can be obtained by looking up parameters. They are an offset into a global constant parameter array.
Definition at line 98 of file param.h.
typedef uint16_t param_type_t
Definition at line 66 of file param.h.
Function Documentation
__EXPORT void param_control_autosave (bool enable)
Enable/disable the param autosaving.
Re-enabling with changed params will not cause an autosave.
Parameters
enable true: enable autosaving, false: disable autosaving
Definition at line 674 of file param.c.
References autosave_disabled, autosave_scheduled, autosave_work, param_lock(), param_lock_writer(), param_unlock(), and param_unlock_writer().
Referenced by ParameterTest::run_tests(), and TemperatureCalibration::task_main().
__EXPORT unsigned param_count (void)
Return the total number of parameters.
Returns
The number of parameters.
Definition at line 383 of file param.c.
References get_param_info_count().
Referenced by do_show(), ParameterTest::exportImportAll(), MavlinkParametersManager::send_one(), MavlinkParametersManager::send_untransmitted(), px4::logger::Logger::write_changed_parameters(), and px4::logger::Logger::write_parameters().
__EXPORT unsigned param_count_used (void)
Return the actually used number of parameters.
Returns
The number of parameters.
Definition at line 389 of file param.c.
References bits_per_allocation_unit, get_param_info_count(), param_changed_storage, and size_param_changed_storage_bytes.
Referenced by do_show(), MavlinkParametersManager::handle_message(), MavlinkParametersManager::send_one(), and MavlinkParametersManager::send_param().
__EXPORT int param_export (int fd, bool only_unsaved)
Export changed parameters to a file.
Note: this method requires a large amount of stack size!
Parameters
fd File descriptor to export to.
only_unsaved Only export changed parameters that have not yet been exported.
Returns
Zero on success, nonzero on failure.
Definition at line 1033 of file param.c.
References BSON_BIN_BINARY, bson_encoder_append_binary(), bson_encoder_append_double(), bson_encoder_append_int(), bson_encoder_fini(), bson_encoder_init_buf_file(), bson_encoder_init_file(), debug, f(), param_value_u::f, fsync(), param_value_u::i, name, param_wbuf_s::param, param_get_value_ptr(), param_lock(), param_lock_reader(), param_name(), param_size(), param_type(), PARAM_TYPE_FLOAT, PARAM_TYPE_INT32, PARAM_TYPE_STRUCT, PARAM_TYPE_STRUCT_MAX, param_unlock(), param_unlock_reader(), param_values, perf_begin(), perf_end(), PX4_DEBUG, PX4_ERR, PX4_OK, px4_sem_post, px4_sem_wait, px4_shutdown_lock(), px4_shutdown_unlock(), param_wbuf_s::unsaved, update_from_shmem(), update_index_from_shmem(), utarray_next, and param_wbuf_s::val.
Referenced by do_save(), ParameterTest::exportImportAll(), and param_save_default().
__EXPORT param_t param_find (const char * name)
Look up a parameter by name.
Parameters
name The canonical name of the parameter being looked up.
Returns
A handle to the parameter, or PARAM_INVALID if the parameter does not exist. This call will also set the parameter as "used" in the system, which is used to e.g. show the parameter via the RC interface
Definition at line 371 of file param.c.
References param_find_internal().
Referenced by land_detector::LandDetector::_cycle(), DfMPU6050Wrapper::_update_accel_calibration(), DfLsm9ds1Wrapper::_update_accel_calibration(), DfMpu9250Wrapper::_update_accel_calibration(), DfMPU6050Wrapper::_update_gyro_calibration(), DfLsm9ds1Wrapper::_update_gyro_calibration(), DfMpu9250Wrapper::_update_gyro_calibration(), DfAK8963Wrapper::_update_mag_calibration(), DfHmc5883Wrapper::_update_mag_calibration(), DfLsm9ds1Wrapper::_update_mag_calibration(), DfMpu9250Wrapper::_update_mag_calibration(), arm_auth_init(), AttitudeEstimatorQ::AttitudeEstimatorQ(), control::BlockParamBase::BlockParamBase(), CameraFeedback::CameraFeedback(), CameraTrigger::CameraTrigger(), Preflight::check_calibration(), DfMpu9250Wrapper::DfMpu9250Wrapper(), do_accel(), do_accel_calibration(), do_airspeed_calibration(), do_compare(), do_gyro(), do_gyro_calibration(), do_level_calibration(), do_mag(), do_mag_calibration(), do_reset_nostart(), do_set(), do_trim_calibration(), Preflight::ekf2Check(), TemperatureCalibrationAccel::finish(), TemperatureCalibrationGyro::finish(), TemperatureCalibrationBaro::finish(), TemperatureCalibrationAccel::finish_sensor_instance(), TemperatureCalibrationGyro::finish_sensor_instance(), TemperatureCalibrationBaro::finish_sensor_instance(), FixedwingAttitudeControl::FixedwingAttitudeControl(), land_detector::FixedwingLandDetector::FixedwingLandDetector(), FixedwingPositionControl::FixedwingPositionControl(), get_parameter_value(), get_params(), CameraInterface::get_pins(), BATT_SMBUS::get_startup_info(), GroundRoverAttitudeControl::GroundRoverAttitudeControl(), GroundRoverPositionControl::GroundRoverPositionControl(), MavlinkReceiver::handle_message_optical_flow_rad(), hil_state_transition(), Preflight::imuConsistencyCheck(), inav_parameters_init(), TFMINI::init(), SF0X::init(), SF1XX::init(), TERARANGER::init(), PX4FLOW::init(), PX4IO::init(), MK::init(), MPU6000::init(), UavcanNode::init(), MPU9250::init(), sensors::initialize_parameter_handles(), sensors::TemperatureCompensation::initialize_parameter_handles(), GPS::initializeCommunicationDump(), vmount::InputMavlinkCmdMount::InputMavlinkCmdMount(), PX4IO::io_set_rc_config(), landing_target_estimator::LandingTargetEstimator::LandingTargetEstimator(), linux_pwm_out_main(), load_mon::LoadMon::LoadMon(), px4::logger::Logger::Logger(), mag_calibrate_all(), Preflight::magConsistencyCheck(), IridiumSBD::main_loop(), Mavlink::mavlink_update_system(), MavlinkReceiver::MavlinkReceiver(), land_detector::MulticopterLandDetector::MulticopterLandDetector(), uart_esc::parameters_init(), rc_receiver::parameters_init(), mpu9x50::parameters_init(), sensors::VotedSensorsUpdate::parameters_update(), ParameterTest::ParameterTest(), Simulator::pollForMAVLinkMessages(), Preflight::preflightCheck(), Simulator::publish_flow_topic(), rc_calibration_check(), sensors::RCUpdate::rc_parameter_map_poll(), read_accelerometer_avg(), px4::Replay::readAndApplyParameter(), Commander::run(), GPS::run(), MavlinkReceiver::send_flight_information(), TemperatureCalibrationBase::set_parameter(), px4::Replay::setUserParams(), ParameterTest::SimpleFind(), Simulator::Simulator(), snapdragon_pwm_out_main(), Standard::Standard(), Tailsitter::Tailsitter(), TemperatureCalibration::task_main(), PX4IO::task_main(), task_main(), test_param(), Tiltrotor::Tiltrotor(), uavcan_main(), uavcannode_start(), Syslink::update_params(), RGBLED::update_params(), linux_pwm_out::update_params(), PWMSim::update_params(), snapdragon_pwm::update_params(), UavcanNode::update_params(), PX4FMU::update_params(), PX4FMU::update_pwm_rev_mask(), PX4FMU::update_pwm_trims(), FixedwingAttitudeControl::vehicle_status_poll(), FixedwingPositionControl::vehicle_status_poll(), VtolAttitudeControl::VtolAttitudeControl(), land_detector::VtolLandDetector::VtolLandDetector(), wind_estimator_main(), px4::logger::Logger::write_version(), and BATT_SMBUS::~BATT_SMBUS().
__EXPORT param_t param_find_no_notification (const char * name)
Look up a parameter by name.
Parameters
name The canonical name of the parameter being looked up.
Returns
A handle to the parameter, or PARAM_INVALID if the parameter does not exist.
Definition at line 377 of file param.c.
References param_find_internal().
Referenced by do_find(), MavlinkParametersManager::handle_message(), and param_import_callback().
__EXPORT param_t param_for_index (unsigned index)
Look up a parameter by index.
Parameters
index An index from 0 to n, where n is param_count()-1.
Returns
A handle to the parameter, or PARAM_INVALID if the index is out of range.
Definition at line 409 of file param.c.
References get_param_info_count(), and PARAM_INVALID.
Referenced by do_show_index(), ParameterTest::exportImportAll(), param_for_used_index(), MavlinkParametersManager::send_one(), MavlinkParametersManager::send_untransmitted(), px4::logger::Logger::write_changed_parameters(), and px4::logger::Logger::write_parameters().
__EXPORT param_t param_for_used_index (unsigned index)
Look up an used parameter by index.
Parameters
index The parameter to obtain the index for.
Returns
The index of the parameter in use, or -1 if the parameter does not exist.
Definition at line 421 of file param.c.
References bits_per_allocation_unit, get_param_info_count(), param_changed_storage, param_for_index(), PARAM_INVALID, and size_param_changed_storage_bytes.
Referenced by do_show_index(), MavlinkParametersManager::handle_message(), and sensors::RCUpdate::rc_parameter_map_poll().
__EXPORT void param_foreach (void(*)(void *arg, param_t param) func, void * arg, bool only_changed, bool only_used)
Apply a function to each parameter.
Note that the parameter set is not locked during the traversal. It also does not hold an internal state, so the callback function can block or sleep between parameter callbacks.
Parameters
func The function to invoke for each parameter.
arg Argument passed to the function.
only_changed If true, the function is only called for parameters whose values have been changed from the default.
only_changed If true, the function is only called for parameters which have been used in one of the running applications.
Definition at line 1318 of file param.c.
References handle_in_range(), param_wbuf_s::param, param_find_changed(), and param_used().
Referenced by do_show().
__EXPORT int param_get (param_t param, void * val)
Copy the value of a parameter.
Parameters
param A handle returned by param_find or passed by param_foreach.
val Where to return the value, assumed to point to suitable storage for the parameter type. For structures, a bitwise copy of the structure is performed to this address.
Returns
Zero if the parameter's value could be returned, nonzero otherwise.
Definition at line 590 of file param.c.
References f(), handle_in_range(), param_value_u::i, param_get_value_ptr(), param_lock(), param_lock_reader(), param_name(), param_set_internal(), param_size(), param_type(), PARAM_TYPE_FLOAT, PARAM_TYPE_INT32, param_unlock(), param_unlock_reader(), perf_begin(), perf_end(), PX4_INFO, set_called_from_get, and update_from_shmem().
Referenced by ParameterTest::_assert_parameter_float_value(), ParameterTest::_assert_parameter_int_value(), land_detector::LandDetector::_check_params(), DfMPU6050Wrapper::_update_accel_calibration(), DfLsm9ds1Wrapper::_update_accel_calibration(), DfMpu9250Wrapper::_update_accel_calibration(), DfMPU6050Wrapper::_update_gyro_calibration(), DfLsm9ds1Wrapper::_update_gyro_calibration(), DfMpu9250Wrapper::_update_gyro_calibration(), DfAK8963Wrapper::_update_mag_calibration(), DfHmc5883Wrapper::_update_mag_calibration(), DfLsm9ds1Wrapper::_update_mag_calibration(), DfMpu9250Wrapper::_update_mag_calibration(), land_detector::VtolLandDetector::_update_params(), land_detector::FixedwingLandDetector::_update_params(), land_detector::MulticopterLandDetector::_update_params(), landing_target_estimator::LandingTargetEstimator::_update_params(), arm_auth_update(), CameraFeedback::CameraFeedback(), CameraTrigger::CameraTrigger(), Preflight::check_calibration(), px4::logger::Logger::check_free_space(), DfMpu9250Wrapper::DfMpu9250Wrapper(), do_accel(), do_accel_calibration(), do_airspeed_calibration(), do_compare(), do_gyro(), do_gyro_calibration(), do_level_calibration(), do_mag(), do_reset_nostart(), do_set(), do_show_index(), do_show_print(), do_trim_calibration(), Preflight::ekf2Check(), ParameterTest::exportImport(), ParameterTest::exportImportAll(), px4::logger::Logger::get_log_time(), get_parameter_value(), CameraInterface::get_pins(), BATT_SMBUS::get_startup_info(), MavlinkParametersManager::handle_message(), MavlinkReceiver::handle_message_battery_status(), MavlinkReceiver::handle_message_optical_flow_rad(), hil_state_transition(), Preflight::imuConsistencyCheck(), inav_parameters_update(), TFMINI::init(), SF0X::init(), SF1XX::init(), TERARANGER::init(), PX4FLOW::init(), PX4IO::init(), MPU6000::init(), UavcanNode::init(), MPU9250::init(), sensors::TemperatureCompensation::initialize_parameter_handles(), GPS::initializeCommunicationDump(), vmount::InputMavlinkCmdMount::InputMavlinkCmdMount(), PX4IO::io_set_rc_config(), linux_pwm_out_main(), load_mon::LoadMon::LoadMon(), mag_calibrate_all(), Preflight::magConsistencyCheck(), IridiumSBD::main_loop(), Mavlink::mavlink_update_system(), sensors::TemperatureCompensation::parameters_update(), Tailsitter::parameters_update(), Standard::parameters_update(), Tiltrotor::parameters_update(), sensors::VotedSensorsUpdate::parameters_update(), rc_receiver::parameters_update(), uart_esc::parameters_update(), GroundRoverAttitudeControl::parameters_update(), mpu9x50::parameters_update(), GroundRoverPositionControl::parameters_update(), VtolAttitudeControl::parameters_update(), FixedwingAttitudeControl::parameters_update(), FixedwingPositionControl::parameters_update(), Simulator::pollForMAVLinkMessages(), Preflight::preflightCheck(), Simulator::publish_flow_topic(), rc_calibration_check(), read_accelerometer_avg(), Commander::run(), px4::logger::Logger::run(), GPS::run(), MavlinkReceiver::send_flight_information(), MavlinkParametersManager::send_param(), ParameterTest::SimpleFind(), Simulator::Simulator(), snapdragon_pwm_out_main(), TemperatureCalibration::task_main(), MK::task_main(), PX4IO::task_main(), task_main(), test_param(), uavcan_main(), uavcannode_start(), control::BlockParam< T >::update(), control::BlockParam< float >::update(), do_not_explicitly_use_this_namespace::Param< float, p >::update(), do_not_explicitly_use_this_namespace::Param< float &, p >::update(), do_not_explicitly_use_this_namespace::Param< int32_t, p >::update(), do_not_explicitly_use_this_namespace::Param< int32_t &, p >::update(), do_not_explicitly_use_this_namespace::Param< bool, p >::update(), AttitudeEstimatorQ::update_parameters(), sensors::update_parameters(), Syslink::update_params(), RGBLED::update_params(), linux_pwm_out::update_params(), PWMSim::update_params(), snapdragon_pwm::update_params(), update_params(), UavcanNode::update_params(), PX4FMU::update_params(), PX4FMU::update_pwm_rev_mask(), PX4FMU::update_pwm_trims(), wind_estimator_main(), px4::logger::Logger::write_changed_parameters(), px4::logger::Logger::write_parameters(), and px4::logger::Logger::write_version().
__EXPORT const char* param_get_default_file (void)
Get the default parameter file name.
Returns
The path to the current default parameter file; either as a result of a call to param_set_default_file, or the built-in default.
Definition at line 950 of file param.c.
References param_default_file, and param_user_file.
Referenced by param_load_default(), param_load_default_no_notify(), param_main(), and param_save_default().
__EXPORT int param_get_index (param_t param)
Look up the index of a parameter.
Parameters
param The parameter to obtain the index for.
Returns
The index, or -1 if the parameter does not exist.
Definition at line 450 of file param.c.
References handle_in_range(), and param_wbuf_s::param.
Referenced by do_show_index(), do_show_print(), param_set_used_internal(), and param_used().
__EXPORT int param_get_used_index (param_t param)
Look up the index of an used parameter.
Parameters
param The parameter to obtain the index for.
Returns
The index of the parameter in use, or -1 if the parameter does not exist.
Definition at line 460 of file param.c.
References bits_per_allocation_unit, param_wbuf_s::param, param_changed_storage, param_used(), and size_param_changed_storage_bytes.
Referenced by do_show_index(), do_show_print(), and MavlinkParametersManager::send_param().
__EXPORT uint32_t param_hash_check (void)
Generate the hash of all parameters and their values.
Returns
CRC32 hash of all param_ids and values
Definition at line 1337 of file param.c.
References handle_in_range(), name, param_wbuf_s::param, param_get_value_ptr(), param_is_volatile(), param_lock(), param_lock_reader(), param_name(), param_size(), param_unlock(), param_unlock_reader(), param_used(), and param_wbuf_s::val.
Referenced by MavlinkParametersManager::handle_message(), and MavlinkParametersManager::send_one().
__EXPORT int param_import (int fd)
Import parameters from a file, discarding any unrecognized parameters.
This function merges the imported parameters with the current parameter set.
Parameters
fd File descriptor to import from. (Currently expected to be a file.)
Returns
Zero on success, nonzero if an error occurred during import. Note that in the failure case, parameters may be inconsistent.
Definition at line 1299 of file param.c.
References flash_param_import(), and param_import_internal().
Referenced by do_import(), ParameterTest::exportImportAll(), param_load_default_no_notify(), and param_main().
__EXPORT void param_init (void)
Initialize the param backend.
Call this on startup before calling any other methods.
Definition at line 230 of file param.c.
References PC_ELAPSED, perf_alloc, and px4_sem_init.
Referenced by board_app_initialize().
__EXPORT bool param_is_volatile (param_t param)
Obtain the volatile state of a parameter.
Parameters
param A handle returned by param_find or passed by param_foreach.
Returns
true if the parameter is volatile
Definition at line 493 of file param.c.
References handle_in_range(), param_wbuf_s::param, and param_info_s::volatile_param.
Referenced by param_hash_check().
__EXPORT int param_load (int fd)
Load parameters from a file.
This function resets all parameters to their default values, then loads new values from a file.
Parameters
fd File descriptor to import from. (Currently expected to be a file.)
Returns
Zero on success, nonzero if an error occurred during import. Note that in the failure case, parameters may be inconsistent.
Definition at line 1311 of file param.c.
References param_import_internal(), and param_reset_all_internal().
Referenced by do_load(), and param_load_default().
__EXPORT int param_load_default (void)
Load parameters from the default parameter file.
Returns
Zero on success.
0 on success, 1 if all params have not yet been stored, -1 if device open failed, -2 if writing parameters failed
Definition at line 1001 of file param.c.
References flash_param_load(), PARAM_CLOSE, param_get_default_file(), param_load(), PARAM_OPEN, and PX4_ERR.
Referenced by commander_low_prio_loop(), ParameterTest::exportImport(), ParameterTest::exportImportAll(), and param_main().
__EXPORT const char* param_name (param_t param)
Obtain the name of a parameter.
Parameters
param A handle returned by param_find or passed by param_foreach.
Returns
The name assigned to the parameter, or NULL if the handle is invalid.
Definition at line 487 of file param.c.
References handle_in_range(), param_info_s::name, and param_wbuf_s::param.
Referenced by do_compare(), do_set(), do_show_index(), do_show_print(), control::BlockParamBase::getName(), param_export(), param_export_internal(), param_get(), param_hash_check(), param_import_callback(), param_reset_excludes(), param_set_internal(), px4::Replay::readAndApplyParameter(), MavlinkParametersManager::send_param(), MavlinkParametersManager::send_untransmitted(), px4::Replay::setUserParams(), px4::logger::Logger::write_changed_parameters(), and px4::logger::Logger::write_parameters().
__EXPORT void param_notify_changes (void)
Notify the system about parameter changes.
Can be used for example after several calls to param_set_no_notification() to avoid unnecessary system notifications.
Definition at line 324 of file param.c.
References _param_notify_changes().
Referenced by do_accel_calibration(), do_gyro_calibration(), do_level_calibration(), do_mag_calibration(), and TemperatureCalibration::task_main().
__EXPORT int param_reset (param_t param)
Reset a parameter to its default value.
This function frees any storage used by struct parameters, and returns the parameter to its default value.
Parameters
param A handle returned by param_find or passed by param_foreach.
Returns
Zero on success, nonzero on failure
Definition at line 846 of file param.c.
References _param_notify_changes(), handle_in_range(), param_autosave(), param_find_changed(), param_lock(), param_lock_writer(), param_unlock(), param_unlock_writer(), param_values, utarray_eltidx, and utarray_erase.
Referenced by param_reset_excludes(), and test_param().
__EXPORT void param_reset_all (void)
Reset all parameters to their default values.
This function also releases the storage used by struct parameters.
Definition at line 899 of file param.c.
References param_reset_all_internal().
Referenced by commander_low_prio_loop(), do_reset(), do_reset_nostart(), ParameterTest::exportImportAll(), flash_param_load(), and ParameterTest::ResetAll().
__EXPORT void param_reset_excludes (const char * excludes[], int num_excludes)
Reset all parameters to their default values except for excluded parameters.
This function also releases the storage used by struct parameters.
Parameters
excludes Array of param names to exclude from resetting. Use a wildcard at the end to exclude parameters with a certain prefix.
num_excludes The number of excludes provided.
Definition at line 905 of file param.c.
References _param_notify_changes(), handle_in_range(), name, param_wbuf_s::param, param_name(), and param_reset().
Referenced by do_reset(), do_reset_nostart(), ParameterTest::ResetAllExcludesBoundaryCheck(), ParameterTest::ResetAllExcludesOne(), ParameterTest::ResetAllExcludesTwo(), and ParameterTest::ResetAllExcludesWildcard().
__EXPORT int param_save_default (void)
Save parameters to the default file.
Note: this method requires a large amount of stack size!
This function saves all parameters with non-default values.
Returns
Zero on success.
Definition at line 956 of file param.c.
References fd, flash_param_save(), OK, PARAM_CLOSE, param_export(), param_get_default_file(), param_lock_writer(), PARAM_OPEN, param_unlock_writer(), PX4_DEBUG, PX4_ERR, PX4_ERROR, and PX4_OK.
Referenced by autosave_worker(), commander_low_prio_loop(), do_airspeed_calibration(), do_save_default(), ParameterTest::exportImport(), ParameterTest::exportImportAll(), param_main(), and TemperatureCalibration::task_main().
__EXPORT int param_set (param_t param, const void * val)
Set the value of a parameter.
Parameters
param A handle returned by param_find or passed by param_foreach.
val The value to set; assumed to point to a variable of the parameter type. For structures, the pointer is assumed to point to a structure to be copied.
Returns
Zero if the parameter's value could be set from a scalar, nonzero otherwise.
Definition at line 803 of file param.c.
References param_set_internal().
Referenced by ParameterTest::_set_all_int_parameters_to(), control::BlockParam< float >::commit(), do_not_explicitly_use_this_namespace::Param< float, p >::commit(), do_not_explicitly_use_this_namespace::Param< float &, p >::commit(), do_not_explicitly_use_this_namespace::Param< int32_t, p >::commit(), do_not_explicitly_use_this_namespace::Param< int32_t &, p >::commit(), do_not_explicitly_use_this_namespace::Param< bool, p >::commit(), do_airspeed_calibration(), do_reset_nostart(), do_set(), do_trim_calibration(), MavlinkParametersManager::handle_message(), PX4IO::init(), mag_calibrate_all(), sensors::VotedSensorsUpdate::parameters_update(), px4::Replay::readAndApplyParameter(), sensors::RCUpdate::set_params_from_rc(), px4::Replay::setUserParams(), test_param(), and BATT_SMBUS::~BATT_SMBUS().
__EXPORT int param_set_default_file (const char * filename)
Set the default parameter file name.
Parameters
filename Path to the default parameter file. The file is not require to exist.
Returns
Zero on success.
Definition at line 934 of file param.c.
References param_user_file.
Referenced by param_main().
__EXPORT int param_set_no_notification (param_t param, const void * val)
Set the value of a parameter, but do not notify the system about the change.
Parameters
param A handle returned by param_find or passed by param_foreach.
val The value to set; assumed to point to a variable of the parameter type. For structures, the pointer is assumed to point to a structure to be copied.
Returns
Zero if the parameter's value could be set from a scalar, nonzero otherwise.
Definition at line 809 of file param.c.
References param_set_internal().
Referenced by land_detector::LandDetector::_cycle(), CameraTrigger::CameraTrigger(), Mavlink::check_radio_config(), control::BlockParam< float >::commit_no_notification(), do_not_explicitly_use_this_namespace::Param< float, p >::commit_no_notification(), do_not_explicitly_use_this_namespace::Param< float &, p >::commit_no_notification(), do_not_explicitly_use_this_namespace::Param< int32_t, p >::commit_no_notification(), do_not_explicitly_use_this_namespace::Param< int32_t &, p >::commit_no_notification(), do_not_explicitly_use_this_namespace::Param< bool, p >::commit_no_notification(), CameraTrigger::cycle_trampoline(), do_accel_calibration(), do_gyro_calibration(), do_level_calibration(), do_mag_calibration(), ParameterTest::exportImport(), ParameterTest::exportImportAll(), TemperatureCalibrationAccel::finish(), TemperatureCalibrationGyro::finish(), TemperatureCalibrationBaro::finish(), TemperatureCalibrationAccel::finish_sensor_instance(), TemperatureCalibrationGyro::finish_sensor_instance(), TemperatureCalibrationBaro::finish_sensor_instance(), PX4IO::init(), mag_calibrate_all(), sensors::VotedSensorsUpdate::parameters_update(), Commander::run(), TemperatureCalibrationBase::set_parameter(), and sensors::update_parameters().
__EXPORT void param_set_used (param_t param)
Mark a parameter as used.
Only marked parameters will be sent to a GCS. A call to param_find() will mark a param as used as well.
Parameters
param A handle returned by param_find or passed by param_foreach.
Definition at line 827 of file param.c.
References param_set_used_internal().
Referenced by do_not_explicitly_use_this_namespace::Param< float, p >::Param(), do_not_explicitly_use_this_namespace::Param< float &, p >::Param(), do_not_explicitly_use_this_namespace::Param< int32_t, p >::Param(), do_not_explicitly_use_this_namespace::Param< int32_t &, p >::Param(), and do_not_explicitly_use_this_namespace::Param< bool, p >::Param().
__EXPORT size_t param_size (param_t param)
Determine the size of a parameter.
Parameters
param A handle returned by param_find or passed by param_foreach.
Returns
The size of the parameter's value.
Definition at line 526 of file param.c.
References handle_in_range(), param_type(), PARAM_TYPE_FLOAT, PARAM_TYPE_INT32, PARAM_TYPE_STRUCT, and PARAM_TYPE_STRUCT_MAX.
Referenced by do_show_print(), param_export(), param_export_internal(), param_get(), param_hash_check(), param_import_callback(), and param_set_internal().
__EXPORT param_type_t param_type (param_t param)
Obtain the type of a parameter.
Parameters
param A handle returned by param_find or passed by param_foreach.
Returns
The type assigned to the parameter.
Definition at line 520 of file param.c.
References handle_in_range(), param_wbuf_s::param, PARAM_TYPE_UNKNOWN, and param_info_s::type.
Referenced by do_compare(), do_set(), do_show_index(), do_show_print(), ParameterTest::exportImport(), ParameterTest::exportImportAll(), MavlinkParametersManager::handle_message(), param_export(), param_export_internal(), param_get(), param_get_value_ptr(), param_import_callback(), param_set_internal(), param_size(), MavlinkParametersManager::send_param(), px4::Replay::setUserParams(), test_param(), px4::logger::Logger::write_changed_parameters(), and px4::logger::Logger::write_parameters().
__EXPORT bool param_used (param_t param)
Wether a parameter is in use in the system.
Returns
True if it has been written or read
Definition at line 815 of file param.c.
References bits_per_allocation_unit, param_changed_storage, and param_get_index().
Referenced by do_show_index(), do_show_print(), param_foreach(), param_get_used_index(), param_hash_check(), MavlinkParametersManager::send_one(), MavlinkParametersManager::send_untransmitted(), px4::logger::Logger::write_changed_parameters(), and px4::logger::Logger::write_parameters().
__EXPORT bool param_value_is_default (param_t param)
Test whether a parameter's value has changed from the default.
Returns
If true, the parameter's value has not been changed from the default.
Definition at line 499 of file param.c.
References param_find_changed(), param_lock(), param_lock_reader(), param_unlock(), and param_unlock_reader().
Referenced by do_compare(), do_set(), do_show_index(), and do_show_print().
__EXPORT bool param_value_unsaved (param_t param)
Test whether a parameter's value has been changed but not saved.
Returns
If true, the parameter's value has not been saved.
Definition at line 509 of file param.c.
References param_find_changed(), param_lock(), param_lock_reader(), param_unlock(), param_unlock_reader(), and param_wbuf_s::unsaved.
Referenced by do_compare(), do_set(), do_show_index(), do_show_print(), MavlinkParametersManager::send_untransmitted(), and px4::logger::Logger::write_changed_parameters().