PX4 Firmware: src/modules/events/temperature_calibration/temperature_calibration.h File Reference
temperature_calibration.h File Reference
Functions
int run_temperature_calibration (bool accel, bool baro, bool gyro)
start temperature calibration in a new task for one or multiple sensors
Function Documentation
int run_temperature_calibration (bool accel, bool baro, bool gyro)
start temperature calibration in a new task for one or multiple sensors
Returns
0 on success, <0 error otherwise
Definition at line 361 of file task.cpp.
References temperature_calibration::instance, PX4_ERR, PX4_INFO, TemperatureCalibration::start(), and TemperatureCalibration::TemperatureCalibration().
Referenced by events::SendEvent::process_commands().