PX4 Firmware: TemperatureCalibrationAccel Class Reference
TemperatureCalibrationAccel Class Reference
#include <accel.h>
Public Member Functions
TemperatureCalibrationAccel (float min_temperature_rise, float min_start_temperature, float max_start_temperature)
virtual ~TemperatureCalibrationAccel ()
int finish ()
void reset_calibration ()
Public Member Functions inherited from TemperatureCalibrationCommon< 3, 3 >
TemperatureCalibrationCommon (float min_temperature_rise, float min_start_temperature, float max_start_temperature)
virtual ~TemperatureCalibrationCommon ()=default
int update ()
Public Member Functions inherited from TemperatureCalibrationBase
TemperatureCalibrationBase (float min_temperature_rise, float min_start_temperature, float max_start_temperature)
virtual ~TemperatureCalibrationBase ()
Private Member Functions
virtual int update_sensor_instance (PerSensorData &data, int sensor_sub)
update a single sensor instance
int finish_sensor_instance (PerSensorData &data, int sensor_index)
Additional Inherited Members
Protected Member Functions inherited from TemperatureCalibrationBase
int set_parameter (const char *format_str, unsigned index, const void *value)
set a system parameter (without system notification) and print an error if it fails
Protected Attributes inherited from TemperatureCalibrationCommon< 3, 3 >
PerSensorData _data [SENSOR_COUNT_MAX]
unsigned _num_sensor_instances
int _sensor_subs [SENSOR_COUNT_MAX]
Protected Attributes inherited from TemperatureCalibrationBase
float _min_temperature_rise
minimum difference in temperature before the process finishes
float _min_start_temperature
minimum temperature before the process starts
float _max_start_temperature
maximum temperature above which the process does not start and an error is declared
Detailed Description
Definition at line 39 of file accel.h.
Constructor & Destructor Documentation
TemperatureCalibrationAccel()
TemperatureCalibrationAccel::TemperatureCalibrationAccel (float min_temperature_rise, float min_start_temperature, float max_start_temperature)
Definition at line 48 of file accel.cpp.
References TemperatureCalibrationCommon< 3, 3 >::_num_sensor_instances, TemperatureCalibrationCommon< 3, 3 >::_sensor_subs, orb_group_count(), ORB_ID, orb_subscribe_multi(), and SENSOR_COUNT_MAX.
~TemperatureCalibrationAccel()
TemperatureCalibrationAccel::~TemperatureCalibrationAccel () virtual
Definition at line 65 of file accel.cpp.
References TemperatureCalibrationCommon< 3, 3 >::_num_sensor_instances, TemperatureCalibrationCommon< 3, 3 >::_sensor_subs, and orb_unsubscribe().
Member Function Documentation
finish()
int TemperatureCalibrationAccel::finish () virtual
See also
TemperatureCalibrationBase::finish()
Implements TemperatureCalibrationBase.
Definition at line 169 of file accel.cpp.
References TemperatureCalibrationCommon< 3, 3 >::_data, TemperatureCalibrationCommon< 3, 3 >::_num_sensor_instances, finish_sensor_instance(), param_find(), and param_set_no_notification().
finish_sensor_instance()
int TemperatureCalibrationAccel::finish_sensor_instance (PerSensorData & data, int sensor_index) inline private
Definition at line 185 of file accel.cpp.
References param_find(), param_set_no_notification(), and TemperatureCalibrationBase::set_parameter().
Referenced by finish().
reset_calibration()
void TemperatureCalibrationAccel::reset_calibration () virtual
See also
TemperatureCalibrationBase::reset_calibration()
Implements TemperatureCalibrationBase.
Definition at line 72 of file accel.cpp.
References TemperatureCalibrationBase::set_parameter().
update_sensor_instance()
int TemperatureCalibrationAccel::update_sensor_instance (PerSensorData & data, int sensor_sub) inline private virtual
update a single sensor instance
Returns
0 when done, 1 not finished yet, <0 for an error
Implements TemperatureCalibrationCommon< 3, 3 >.
Definition at line 88 of file accel.cpp.
References TemperatureCalibrationBase::_max_start_temperature, TemperatureCalibrationBase::_min_start_temperature, TemperatureCalibrationBase::_min_temperature_rise, TemperatureCalibrationCommon< 3, 3 >::_sensor_subs, sensor_accel_s::device_id, hrt_absolute_time(), orb_check(), orb_copy(), ORB_ID, TC_DEBUG, TC_ERROR_INITIAL_TEMP_TOO_HIGH, sensor_accel_s::temperature, sensor_accel_s::x, sensor_accel_s::y, and sensor_accel_s::z.
The documentation for this class was generated from the following files:
src/modules/events/temperature_calibration/accel.h
src/modules/events/temperature_calibration/accel.cpp