PX4 Firmware: src/lib/matrix/test/integration.cpp File Reference
integration.cpp File Reference
#include "test_macros.hpp"
#include <matrix/integration.hpp>
Functions
Vector< float, 6 > f (float t, const Matrix< float, 6, 1 > &, const Matrix< float, 3, 1 > &)
int main ()
Function Documentation
f()
Vector< float, 6 > f (float t, const Matrix< float, 6, 1 > & y, const Matrix< float, 3, 1 > & u)
Definition at line 8 of file integration.cpp.
References matrix::sin().
Referenced by CollisionPrevention::_addDistanceSensorData(), CollisionPrevention::_calculateConstrainedSetpoint(), FlightTaskAutoLineSmoothVel::_constrainOneSide(), TECS::_detect_uncommanded_descent(), TECS::_detect_underspeed(), FlightTaskManual::_evaluateSticks(), FlightTaskAuto::_evaluateTriplets(), FlightTaskAutoLine::_generateAltitudeSetpoints(), FlightTaskAutoLine::_generateSetpoints(), FlightTaskAutoLineSmoothVel::_generateTrajectory(), FlightTaskAutoLine::_generateXYsetpoints(), BezierQuadTest::_get_arc_length(), land_detector::MulticopterLandDetector::_get_ground_contact_state(), land_detector::MulticopterLandDetector::_get_max_altitude(), BezierQuadTest::_get_states_from_time(), FlightTaskAuto::_getCurrentState(), ManualSmoothingXY::_getHeadingToWorldFrame(), ManualSmoothingXY::_getIntention(), FlightTaskAutoMapper2::_getLandSpeed(), FlightTaskAutoLineSmoothVel::_getSpeedAtTarget(), ManualSmoothingXY::_getWorldToHeadingFrame(), land_detector::MulticopterLandDetector::_has_minimal_thrust(), LogListHelper::_init(), SearchMinTest::_init_inputs(), SearchMinTest::_init_inputs_flipped(), SearchMinTest::_init_inputs_negative(), SearchMinTest::_init_tol_larger_than_range(), SearchMinTest::_init_tol_larger_than_range_flipped(), PositionControl::_interfaceMapping(), linux_sbus::RcInput::_measure(), FlightTaskAutoLineSmoothVel::_prepareSetpoints(), _quadratic_function(), vmount::InputRC::_read_control_data_from_subscription(), FlightTaskManualAltitude::_respectMaxAltitude(), FlightTaskManualAltitude::_rotateIntoHeadingFrame(), FlightTaskManualPosition::_scaleSticks(), RoboClaw::_sendSigned16Bit(), RoboClaw::_sendUnsigned7Bit(), BezierQuadTest::_set_bez_from_vel(), FlightTaskAutoLine::_setSpeedAtTarget(), TECS::_update_height_setpoint(), TECS::_update_pitch_setpoint(), TECS::_update_speed_states(), TECS::_update_throttle_setpoint(), PositionControl::_velocityController(), LSM303D::accel_set_range(), SmoothZTest::accelerateDownwardFromBrake(), SmoothZTest::accelerateUpwardFromBrake(), PreFlightCheck::accelerometerCheck(), FlightTaskDescend::activate(), FlightTaskFailsafe::activate(), FlightTaskManualAltitude::activate(), FlightTaskTransition::activate(), Sensors::adc_poll(), ADIS16477::ADIS16477(), ADIS16497::ADIS16497(), ICM20948_mag::ak09916_read_adjustments(), MPU9250_mag::ak8963_read_adjustments(), FlightTaskOrbit::applyCommandParameters(), AttitudeControlConvergenceTest::AttitudeControlConvergenceTest(), matrix::AxisAngle< Type >::AxisAngle(), Ekf2::blend_gps_data(), blockDerivativeTest(), control::blockDerivativeTest(), control::blockHighPassTest(), blockHighPassTest(), control::blockIntegralTest(), blockIntegralTest(), control::blockIntegralTrapTest(), blockIntegralTrapTest(), control::blockLimitSymTest(), blockLimitSymTest(), control::blockLimitTest(), blockLimitTest(), control::blockLowPass2Test(), blockLowPass2Test(), control::blockLowPassTest(), blockLowPassTest(), blockOutputTest(), control::blockOutputTest(), blockPDTest(), control::blockPDTest(), blockPIDTest(), control::blockPIDTest(), blockPITest(), control::blockPITest(), blockPTest(), control::blockPTest(), blockRandGaussTest(), control::blockRandGaussTest(), blockRandUniformTest(), control::blockRandUniformTest(), blockStatsTest(), control::blockStatsTest(), SmoothZTest::brakeDownward(), SmoothZTest::brakeUpward(), build_gps_response(), Ekf2::calc_gps_blend_output(), calc_IAS(), calc_IAS_corrected(), calc_TAS(), Ekf::calcExtVisRotMat(), Ekf::calcOptFlowBodyRateComp(), Ekf::calcOptFlowMeasVar(), Ekf::calcRotVecVariances(), PGA460::calculate_object_distance(), RTL::calculate_return_alt_from_cone_half_angle(), Ekf::calculate_synthetic_mag_z_measurement(), Ekf::calculateOutputStates(), HMC5883::calibrate(), LIS3MDL::calibrate(), CameraTrigger::CameraTrigger(), PAW3902::changeMode(), AirspeedValidator::check_airspeed_innovation(), check_calibration_result(), AirspeedValidator::check_load_factor(), LIS3MDL::check_offset(), HMC5883::check_offset(), IST8310::check_offset(), VtolType::check_quadchute_condition(), Mavlink::check_requested_subscriptions(), LIS3MDL::check_scale(), HMC5883::check_scale(), ObstacleAvoidance::checkAvoidanceProgress(), AttitudeControlConvergenceTest::checkConvergence(), PositionControlBasicDirectionTest::checkDirection(), MissionFeasibilityChecker::checkDistancesBetweenWaypoints(), MissionFeasibilityChecker::checkDistanceToFirstWaypoint(), PreFlightChecker::checkInnov2DFailed(), Ekf::checkMagBiasObservability(), MissionFeasibilityChecker::checkTakeoff(), CM8JL65::CM8JL65(), cm_uint16_from_m_float(), TFMINI::collect(), SRF02::collect(), TERARANGER::collect(), CM8JL65::collect(), LidarLiteI2C::collect(), Radar::collect(), MB12XX::collect(), MPL3115A2::collect(), SF1XX::collect(), LeddarOne::collect(), PX4FLOW::collect(), MS5611::collect(), MappyDot::collect(), Ekf::collect_gps(), Ekf::collect_imu(), commander_main(), InnovationLpf::computeAlphaFromDtAndTauInv(), math::trajectory::computeMaxSpeedFromDistance(), math::trajectory::computeMaxSpeedInWaypoint(), Battery::computeScale(), VelocitySmoothing::computeT1(), VelocitySmoothing::computeT2(), VelocitySmoothing::computeT3(), DataValidator::confidence(), Mavlink::configure_stream(), Mavlink::configure_streams_to_default(), Ekf::constrainStates(), ControlMath::constrainXY(), ECL_WheelController::control_attitude(), RoverPositionControl::control_attitude(), ECL_YawController::control_bodyrate(), ECL_RollController::control_bodyrate(), ECL_WheelController::control_bodyrate(), ECL_PitchController::control_bodyrate(), TAP_ESC::control_callback(), FixedwingAttitudeControl::control_flaps(), FixedwingPositionControl::control_landing(), RoverPositionControl::control_position(), FixedwingPositionControl::control_position(), FixedwingPositionControl::control_takeoff(), RoverPositionControl::control_velocity(), MixingOutput::controlCallback(), Ekf::controlExternalVisionFusion(), Ekf::controlFusionModes(), Ekf::controlHeightFusion(), Ekf::controlOpticalFlowFusion(), controls_tick(), convert_channel_value(), ControlMath::cross_sphere_line(), Navigator::custom_command(), RCInput::cycle(), detect_orientation(), do_airspeed_calibration(), do_compare(), do_level_calibration(), do_set(), do_show_print(), FixedwingPositionControl::do_takeoff_help(), RCTest::dsmTest(), dumpfile_main(), Battery::estimateRemaining(), ParameterTest::exportImport(), MPU6000::factory_self_test(), RCInput::fill_rc_in(), Ekf2::filter_altitude_ellipsoid(), Ekf::fixCovarianceErrors(), float2SigExp(), BlockLocalPositionEstimator::flowMeasure(), matrix::Quaternion< Type >::from_axis_angle(), MultirotorMixer::from_text(), frsky_format_gps(), frsky_send_frame2(), frsky_telemetry_thread_main(), WindEstimator::fuse_airspeed(), WindEstimator::fuse_beta(), Ekf::fuseAirspeed(), Ekf::fuseDeclination(), Ekf::fuseDrag(), Ekf::fuseFlowForTerrain(), Ekf::fuseGpsAntYaw(), Ekf::fuseHagl(), Ekf::fuseHeading(), Ekf::fuseMag(), Ekf::fuseOptFlow(), Ekf::fuseSideslip(), Ekf::fuseVelPosHeight(), FXOS8701CQ::FXOS8701CQ(), MulticopterAttitudeControl::generate_attitude_setpoint(), Sih::generate_force_and_torques(), Sih::generate_wgn(), Takeoff::generateInitialRampValue(), StraightLine::generateSetpoints(), FixedwingAttitudeControl::get_airspeed_and_update_scaling(), DataValidatorGroup::get_best(), Mavlink::get_channel(), Navigator::get_cruising_speed(), get_distance_to_arc(), get_distance_to_line(), Ekf::get_ekf_ctrl_limits(), Ekf::get_ekf_soln_status(), LogListHelper::get_entry(), Navigator::get_loiter_radius(), get_table_data(), PGA460::get_temperature(), DataValidatorGroup::get_vibration_offset(), FixedwingPositionControl::get_waypoint_heading_distance(), WeatherVane::get_weathervane_yawrate(), BlockLocalPositionEstimator::getDelayPeriods(), Landingslope::getFlareCurveRelativeAltitudeSave(), Landingslope::getLandingSlopeRelativeAltitudeSave(), Ekf::gps_is_good(), MavlinkReceiver::handle_message_command_both(), MavlinkReceiver::handle_message_distance_sensor(), MavlinkReceiver::handle_message_gps_global_origin(), MavlinkReceiver::handle_message_hil_gps(), MavlinkReceiver::handle_message_hil_optical_flow(), Simulator::handle_message_hil_sensor(), MavlinkReceiver::handle_message_hil_state_quaternion(), MavlinkReceiver::handle_message_optical_flow_rad(), MavlinkReceiver::handle_message_ping(), GPSDriverEmlidReach::handleErbSentence(), GPSDriverAshtech::handleMessage(), GPSDriverMTK::handleMessage(), HMC5883::HMC5883(), Ekf::increaseQuatYawErrVariance(), TFMINI::init(), FixedwingPositionControl::init(), AttitudeEstimatorQ::init_attq(), Sih::init_variables(), Ekf::initHagl(), WindEstimator::initialise(), Ekf::initialiseCovariance(), Ekf::initialiseFilter(), Ekf::initialiseQuatCovariances(), vmount::InputBase::initialize(), Sih::inner_loop(), insert_values_around_mean(), matrix::integrate_rk4(), matrix::inv(), inverse4x4(), PX4IO::io_get_raw_rc_input(), PX4IO::io_handle_vservo(), TerrainEstimator::is_distance_valid(), MissionBlock::is_mission_item_reached(), math::isZero(), BlockLocalPositionEstimator::lidarCorrect(), Ekf::limitDeclination(), LIS3MDL::LIS3MDL(), load_mixer_file(), LSM303D::mag_set_range(), main(), mat_mul(), LidarLitePWM::measure(), ADIS16448::measure(), ADIS16497::measure(), BMI088_accel::measure(), MPU9250::measure(), ICM20948::measure(), MultirotorMixer::minimize_saturation(), HelicopterMixer::mix(), MultirotorMixer::mix(), MultirotorMixer::mix_airmode_disabled(), MultirotorMixer::mix_yaw(), mixer_callback(), mixer_tick(), MixerTest::mixerTest(), motor_ramp_thread_main(), motor_test_main(), ECL_L1_Pos_Controller::navigate_heading(), ECL_L1_Pos_Controller::navigate_loiter(), ECL_L1_Pos_Controller::navigate_waypoints(), Tunes::note_to_frequency(), FollowTarget::on_active(), Parameters::operator!=(), param_export(), param_export_internal(), param_get(), param_import_callback(), param_set_internal(), Standard::parameters_update(), VtolAttitudeControl::parameters_update(), Sih::parameters_updated(), GPSDriverSBF::payloadRxDone(), GPSDriverUBX::payloadRxDone(), PositionControlBasicTest::PositionControlBasicTest(), PreFlightCheck::powerCheck(), Ekf::predictState(), px4::logger::Logger::print_statistics(), RCInput::print_status(), Simulator::publish_distance_topic(), uORBTest::UnitTest::pubsublatency_main(), DataValidator::put(), Integrator::put(), QMC5883::QMC5883(), matrix::Quaternion< Type >::Quaternion(), FlightTaskManualAltitudeSmoothVel::reActivate(), FlightTaskAutoLineSmoothVel::reActivate(), FlightTaskManualPositionSmoothVel::reActivate(), Ekf::realignYawGPS(), GPSSIM::receive(), Sih::reconstruct_sensors_signals(), reject_sample(), MicroBenchMath::MicroBenchMath::reset(), HMC5883::reset(), MPU6000::reset(), Ekf::resetExtVisRotMat(), Ekf::resetGpsAntYaw(), Ekf::resetHeight(), Ekf::resetMagHeading(), Ekf::resetVelocity(), Ekf::resetWindCovariance(), RM3100::RM3100(), MulticopterRateControl::Run(), MulticopterAttitudeControl::Run(), RCUpdate::RCUpdate::Run(), AttitudeEstimatorQ::Run(), FixedwingAttitudeControl::Run(), PAW3902::Run(), Ekf2::Run(), GPS::run(), FXOS8701CQ::Run(), PMW3901::Run(), PCA9685::Run(), Heater::Run(), BlockLocalPositionEstimator::Run(), BATT_SMBUS::Run(), Ekf::run3DMagAndDeclFusions(), WindEstimator::run_sanity_checks(), PositionControlBasicTest::runController(), Ekf::runTerrainEstimator(), sbus1_output(), RCTest::sbus2Test(), sbus_decode(), SimpleMixer::scale(), MavlinkStreamHighLatency2::send(), MavlinkStreamBatteryStatus::send(), MavlinkStreamADSBVehicle::send(), MavlinkStreamGlobalPositionInt::send(), MavlinkStreamHomePosition::send(), Sih::send_gps(), RGBLED::send_led_rgb(), MPU6000::set_accel_range(), AirspeedValidator::set_airspeed_scale_manual(), math::LowPassFilter2p::set_cutoff_frequency(), math::LowPassFilter2pVector3f::set_cutoff_frequency(), FollowTarget::set_follow_target_item(), ADIS16448::set_gyro_dyn_range(), BMI055_gyro::set_gyro_range(), BMI088_gyro::set_gyro_range(), BMI160::set_gyro_range(), Mavlink::set_hil_enabled(), ECL_L1_Pos_Controller::set_l1_period(), MissionBlock::set_loiter_item(), MavlinkReceiver::set_message_interval(), UavcanNode::set_param(), FXAS21002C::set_range(), HMC5883::set_range(), L3GD20::set_range(), Takeoff::set_takeoff_position(), MultirotorMixer::set_thrust_factor(), ECL_Controller::set_time_constant(), MixerGroup::set_trims(), MulticopterPositionControl::set_vehicle_states(), RateControl::setDTermCutoff(), EstimatorInterface::setGpsData(), EstimatorInterface::setIMUData(), ManualSmoothingZ::setMaxAcceleration(), EstimatorInterface::setOpticalFlowData(), AttitudeControl::setProportionalGain(), PCA9685::setPWMFreq(), ObstacleAvoidanceTest::SetUp(), setup_base_group(), SF0XTest::sf0xTest(), FloatTest::singlePrecisionTests(), BlockLocalPositionEstimator::sonarCorrect(), sphere_fit_least_squares(), st24_decode(), RCTest::st24Test(), FixedwingPositionControl::status_publish(), Mavlink::stream_command(), Battery::sumDischarged(), RCTest::sumdTest(), task_main(), CameraFeedback::task_main(), linux_pwm_out::task_main(), df_bebop_bus_wrapper::task_main(), Mavlink::task_main(), FixedwingPositionControl::tecs_update_pitch_throttle(), TEST(), test_conv(), test_error_tracking(), TEST_F(), test_init(), TEST_P(), test_put(), test_rms_calculation(), test_sensor_failure(), test_stale_detector(), test_vibration(), MathlibTest::testFinite(), MathlibTest::testMatrix3x3(), MathlibTest::testQuaternionfrom_euler(), MathlibTest::testQuaternionRotate(), MathlibTest::testVector2(), MathlibTest::testVector3(), MulticopterAttitudeControl::throttle_curve(), ControlMath::thrustToAttitude(), MicroBenchMath::MicroBenchMath::time_single_precision_float_trig(), Mavlink::try_start_ulog_streaming(), FlightTaskAutoFollowMe::update(), WindEstimator::update(), launchdetection::CatapultLaunchMethod::update(), AlphaFilter< Vector3f >::update(), control::BlockRandGauss::update(), control::BlockIntegralTrap::update(), landing_target_estimator::LandingTargetEstimator::update(), AttitudeControl::update(), control::BlockDerivative::update(), AttitudeEstimatorQ::update(), landing_target_estimator::KalmanFilter::update(), TemperatureCalibrationCommon< 3, 3 >::update(), MavlinkStreamHighLatency2::update_data(), Ekf2::update_gps_blend_states(), Ekf2::update_gps_offsets(), Ekf2::update_mag_bias(), AttitudeEstimatorQ::update_mag_declination(), Standard::update_mc_state(), AttitudeEstimatorQ::update_parameters(), RCUpdate::update_parameters(), AirspeedModule::update_params(), TECS::update_pitch_throttle(), Mavlink::update_rate_mult(), RCUpdate::RCUpdate::update_rc_functions(), ECL_L1_Pos_Controller::update_roll_setpoint(), MultirotorMixer::update_saturation_status(), Tiltrotor::update_transition_state(), Tailsitter::update_transition_state(), Standard::update_transition_state(), TECS::update_vehicle_state_estimates(), MavlinkStreamHighLatency2::update_vehicle_status(), Tiltrotor::update_vtol_state(), Tailsitter::update_vtol_state(), Standard::update_vtol_state(), EkfInitializationTest::update_with_const_sensors(), FlightTaskTransition::updateAccelerationEstimate(), Battery::updateBatteryStatus(), RateControl::updateIntegral(), MixingOutput::updateOutputSlewrate(), MixingOutput::updateParams(), Ekf::updateRangeDataStuck(), VelocitySmoothing::updateTraj(), ManualVelocitySmoothingZ::updateTrajConstraints(), usage(), user_start(), BlockLocalPositionEstimator::visionCorrect(), MEASAirspeed::voltage_correction(), and RoverPositionControl::~RoverPositionControl().
main()
int main ()
Definition at line 13 of file integration.cpp.
References matrix::cos(), f(), matrix::integrate_rk4(), matrix::isEqual(), and TEST.