PX4 Firmware: src/systemcmds/tune_control/tune_control.cpp File Reference
tune_control.cpp File Reference
Command-line tool to control & test the (external) tunes.
#include <px4_platform_common/getopt.h>
#include <px4_platform_common/log.h>
#include <stdlib.h>
#include <string.h>
#include <unistd.h>
#include <errno.h>
#include <px4_platform_common/module.h>
#include <lib/tunes/tunes.h>
#include <uORB/topics/tune_control.h>
#include <drivers/drv_hrt.h>
Macros
#define MAX_NOTE_ITERATION 50
Functions
static void usage ()
__EXPORT int tune_control_main (int argc, char *argv[])
static void publish_tune_control (tune_control_s &tune_control)
Variables
static orb_advert_t tune_control_pub = nullptr
Detailed Description
Command-line tool to control & test the (external) tunes.
To use it make sure there's a driver running, which handles the tune_control uorb topic.
Definition in file tune_control.cpp.
Macro Definition Documentation
MAX_NOTE_ITERATION
#define MAX_NOTE_ITERATION 50
Definition at line 56 of file tune_control.cpp.
Referenced by tune_control_main().
Function Documentation
publish_tune_control()
static void publish_tune_control (tune_control_s & tune_control) static
Definition at line 66 of file tune_control.cpp.
References hrt_absolute_time(), orb_advertise_queue(), ORB_ID, orb_publish(), tune_control_s::timestamp, and tune_control_pub.
Referenced by tune_control_main().
tune_control_main()
int tune_control_main (int argc, char * argv[])
Definition at line 80 of file tune_control.cpp.
References tune_control_s::duration, tune_control_s::frequency, Tunes::get_default_tunes_size(), Tunes::get_maximum_update_interval(), Tunes::get_next_note(), MAX_NOTE_ITERATION, publish_tune_control(), Tunes::set_control(), Tunes::set_string(), tune_control_s::silence, tune_control, tune_control_s::tune_id, tune_control_s::tune_override, usage(), and tune_control_s::volume.
usage()
static void usage (void) static
Definition at line 239 of file tune_control.cpp.
Referenced by tune_control_main().
Variable Documentation
tune_control_pub
orb_advert_t tune_control_pub = nullptr static
Definition at line 60 of file tune_control.cpp.
Referenced by publish_tune_control().