PX4 Firmware: src/drivers/distance_sensor/sf1xx/sf1xx.cpp File Reference
sf1xx.cpp File Reference
#include <px4_platform_common/px4_config.h>
#include <px4_platform_common/defines.h>
#include <px4_platform_common/getopt.h>
#include <px4_platform_common/px4_work_queue/ScheduledWorkItem.hpp>
#include <px4_platform_common/module.h>
#include <drivers/device/i2c.h>
#include <sys/types.h>
#include <stdint.h>
#include <stdlib.h>
#include <stdbool.h>
#include <semaphore.h>
#include <string.h>
#include <fcntl.h>
#include <poll.h>
#include <stdio.h>
#include <math.h>
#include <unistd.h>
#include <lib/parameters/param.h>
#include <perf/perf_counter.h>
#include <drivers/drv_hrt.h>
#include <drivers/drv_range_finder.h>
#include <drivers/device/ringbuffer.h>
#include <uORB/uORB.h>
#include <uORB/topics/distance_sensor.h>
#include <board_config.h>
Classes
class SF1XX
Namespaces
sf1xx
Local functions in support of the shell command.
Macros
#define SF1XX_BUS_DEFAULT PX4_I2C_BUS_EXPANSION
#define SF1XX_BASEADDR 0x66
#define SF1XX_DEVICE_PATH "/dev/sf1xx"
Functions
__EXPORT int sf1xx_main (int argc, char *argv[])
int sf1xx::start (uint8_t rotation)
Attempt to start driver on all available I2C busses.
int sf1xx::start_bus (uint8_t rotation, int i2c_bus)
Start the driver on a specific bus.
int sf1xx::stop ()
Stop the driver.
int sf1xx::test ()
Perform some basic functional tests on the driver; make sure we can collect data from the sensor in polled and automatic modes.
int sf1xx::reset ()
Reset the driver.
int sf1xx::info ()
Print a little info about the driver.
static void sf1xx_usage ()
Variables
SF1XX * sf1xx::g_dev
Detailed Description
Author
ecmnet ecm@g.nosp@m.mx.d.nosp@m.e
Vasily Evseenko svpco.nosp@m.m@gm.nosp@m.ail.c.nosp@m.om
Driver for the Lightware SF1xx lidar range finder series. Default I2C address 0x66 is used.
Definition in file sf1xx.cpp.
Macro Definition Documentation
SF1XX_BASEADDR
#define SF1XX_BASEADDR 0x66
Definition at line 78 of file sf1xx.cpp.
Referenced by SF1XX::init().
SF1XX_BUS_DEFAULT
#define SF1XX_BUS_DEFAULT PX4_I2C_BUS_EXPANSION
Definition at line 77 of file sf1xx.cpp.
Referenced by sf1xx_main().
SF1XX_DEVICE_PATH
#define SF1XX_DEVICE_PATH "/dev/sf1xx"
Definition at line 79 of file sf1xx.cpp.
Referenced by sf1xx::reset(), sf1xx::start_bus(), and sf1xx::test().
Function Documentation
sf1xx_main()
int sf1xx_main (int argc, char * argv[])
Definition at line 824 of file sf1xx.cpp.
References sf1xx::info(), sf1xx::reset(), SF1XX_BUS_DEFAULT, sf1xx_usage(), sf1xx::start(), sf1xx::start_bus(), sf1xx::stop(), and sf1xx::test().
sf1xx_usage()
static void sf1xx_usage () static
Definition at line 792 of file sf1xx.cpp.
Referenced by sf1xx_main().