PX4 Firmware: src/modules/uavcanesc/commands/rpm/esc_rpm.cpp File Reference
esc_rpm.cpp File Reference
#include <px4_config.h>
#include <px4_log.h>
#include <stdint.h>
#include <cstdlib>
#include "esc_rpm.hpp"
Functions
static void print_usage ()
__EXPORT int rpm_main (int argc, char *argv[])
Function Documentation
static void print_usage (void) static
Definition at line 42 of file esc_rpm.cpp.
References PX4_INFO, and rpm_main().
Referenced by rpm_main().
int rpm_main (int argc, char * argv[])
Definition at line 49 of file esc_rpm.cpp.
References print_usage().
Referenced by print_usage().