PX4 Firmware: src/drivers/px4io/px4io_serial.cpp File Reference
px4io_serial.cpp File Reference
Serial interface for PX4IO.
#include "px4io_driver.h"
#include <px4_arch/px4io_serial.h>
Functions
device::Device * PX4IO_serial_interface ()
Variables
static PX4IO_serial * g_interface
Detailed Description
Serial interface for PX4IO.
Definition in file px4io_serial.cpp.
Function Documentation
PX4IO_serial_interface()
device::Device* PX4IO_serial_interface ()
Definition at line 47 of file px4io_serial.cpp.
References crc_packet(), data, g_interface, ToneAlarmInterface::init(), OK, PC_COUNT, PC_ELAPSED, perf_alloc, perf_count(), perf_free(), PKT_CODE, PKT_CODE_ERROR, PKT_CODE_READ, PKT_CODE_WRITE, PKT_COUNT, PKT_MAX_REGS, read(), and write().
Referenced by PX4IO::set_update_rate().
Variable Documentation
g_interface
PX4IO_serial* g_interface static
Definition at line 44 of file px4io_serial.cpp.
Referenced by PX4IO_serial_interface().