PX4 Firmware: src/modules/syslink/syslink_main.cpp File Reference
syslink_main.cpp File Reference
Entry point for syslink module used to communicate with the NRF module on a Crazyflie.
#include <px4_config.h>
#include <px4_tasks.h>
#include <px4_posix.h>
#include <px4_defines.h>
#include <unistd.h>
#include <stdio.h>
#include <poll.h>
#include <string.h>
#include <fcntl.h>
#include <sys/ioctl.h>
#include <termios.h>
#include <sys/types.h>
#include <sys/stat.h>
#include <mqueue.h>
#include <drivers/drv_rc_input.h>
#include <drivers/drv_board_led.h>
#include <systemlib/err.h>
#include <uORB/topics/parameter_update.h>
#include <uORB/topics/battery_status.h>
#include <uORB/topics/input_rc.h>
#include <board_config.h>
#include "crtp.h"
#include "syslink_main.h"
#include "drv_deck.h"
Namespaces
syslink
Macros
#define B1000000 1000000
Functions
__BEGIN_DECLS void led_init (void)
Ideally we'd be able to get these from up_internal.h, but since we want to be able to disable the NuttX use of leds for system indication at will and there is no separate switch, we need to build independent of the CONFIG_ARCH_LEDS configuration switch.
void led_on (int led)
void led_off (int led)
void led_toggle (int led)
__END_DECLS __EXPORT int syslink_main (int argc, char *argv[])
void syslink::usage ()
Prints info about the driver argument usage.
void syslink::start ()
Attempt to start driver on all available I2C busses.
void syslink::status ()
void syslink::test ()
void syslink::attached (int pid)
Variables
Syslink * g_syslink = nullptr
Detailed Description
Entry point for syslink module used to communicate with the NRF module on a Crazyflie.
Definition in file syslink_main.cpp.
Macro Definition Documentation
#define B1000000 1000000
Referenced by Syslink::open_serial().
Function Documentation
__BEGIN_DECLS void led_init (void)
Ideally we'd be able to get these from up_internal.h, but since we want to be able to disable the NuttX use of leds for system indication at will and there is no separate switch, we need to build independent of the CONFIG_ARCH_LEDS configuration switch.
Definition at line 72 of file led.c.
References arraySize, blink_msg_end, g_ledmap, GPIO_BLUE_LED, GPIO_LED0, GPIO_LED1, GPIO_LED2, GPIO_LED3, GPIO_nSAFETY_SWITCH_LED_OUT, GPIO_RED_LED, h_leds, hrt_absolute_time(), LED0_DEVICE_PATH, LED_AMBER, LED_BLUE, led_control_pub, LED_GREEN, led_control_s::led_mask, led_off(), LED_ON, LED_UORB_QUEUE_LENGTH, led_control_s::mode, orb_advertise_queue(), ORB_ID, led_control_s::priority, PX4_DEBUG, PX4_ERROR, PX4_MFT_HW_SUPPORTED, PX4_MFT_PX4IO, PX4_WARN, and led_control_s::timestamp.
Referenced by board_autoled_initialize(), and led_toggle().
void led_off (int led)
Definition at line 97 of file led.c.
References _led_param_get(), _led_state, g_ledmap, GPIO_BLUE_LED, GPIO_LED1, GPIO_RED_LED, h_leds, LED_OFF, phy_set_led(), PX4_DEBUG, and xlat.
Referenced by Syslink::handle_message(), and led_init().
void led_on (int led)
Definition at line 92 of file led.c.
References _led_param_get(), _led_state, g_ledmap, GPIO_BLUE_LED, GPIO_LED1, GPIO_RED_LED, h_leds, LED_ON, phy_set_led(), PX4_DEBUG, and xlat.
Referenced by Syslink::handle_message().
void led_toggle (int led)
Definition at line 102 of file led.c.
References _led_param_get(), _led_state, board_autoled_initialize(), board_autoled_off(), board_autoled_on(), g_ledmap, GPIO_BLUE_LED, GPIO_LED1, GPIO_RED_LED, h_leds, LED_ASSERTION, LED_HEAPALLOCATE, LED_INIRQ, led_init(), LED_IRQSENABLED, LED_PANIC, LED_SIGNAL, LED_STACKCREATED, LED_TOGGLE, phy_get_led(), phy_set_led(), PX4_DEBUG, and xlat.
Referenced by control_status_leds().
int syslink_main (int argc, char * argv[])
Definition at line 865 of file syslink_main.cpp.
References syslink::attached(), errx, syslink::start(), syslink::status(), syslink::test(), and syslink::usage().
Variable Documentation
Syslink* g_syslink = nullptr
Definition at line 83 of file syslink_main.cpp.