PX4 Firmware: TemperatureCalibration Class Reference
TemperatureCalibration Class Reference
Public Member Functions
TemperatureCalibration (bool accel, bool baro, bool gyro)
Constructor.
~TemperatureCalibration ()=default
Destructor.
int start ()
Start task.
void task_main ()
void exit_task ()
Static Public Member Functions
static int do_temperature_calibration (int argc, char *argv[])
Private Member Functions
void publish_led_control (led_control_s &led_control)
Private Attributes
uORB::PublicationQueued< led_control_s > _led_control_pub {ORB_ID(led_control)}
bool _force_task_exit = false
int _control_task = -1
bool _accel
enable accel calibration?
bool _baro
enable baro calibration?
bool _gyro
enable gyro calibration?
Detailed Description
Definition at line 67 of file task.cpp.
Constructor & Destructor Documentation
TemperatureCalibration()
TemperatureCalibration::TemperatureCalibration (bool accel, bool baro, bool gyro)
Constructor.
Definition at line 106 of file task.cpp.
Referenced by run_temperature_calibration().
~TemperatureCalibration()
TemperatureCalibration::~TemperatureCalibration () default
Destructor.
Member Function Documentation
do_temperature_calibration()
int TemperatureCalibration::do_temperature_calibration (int argc, char * argv[]) static
Definition at line 324 of file task.cpp.
References temperature_calibration::instance, and task_main().
Referenced by start().
exit_task()
void TemperatureCalibration::exit_task () inline
Definition at line 91 of file task.cpp.
References led_control, and publish_led_control().
publish_led_control()
void TemperatureCalibration::publish_led_control (led_control_s & led_control) private
Definition at line 350 of file task.cpp.
References _led_control_pub, hrt_absolute_time(), uORB::PublicationQueued< T >::publish(), and led_control_s::timestamp.
Referenced by task_main().
start()
int TemperatureCalibration::start ()
Start task.
Returns
OK on success.
Definition at line 330 of file task.cpp.
References _control_task, do_temperature_calibration(), and temperature_calibration::instance.
Referenced by run_temperature_calibration().
task_main()
void TemperatureCalibration::task_main ()
Definition at line 111 of file task.cpp.
References _accel, _baro, _force_task_exit, _gyro, BOARD_MAX_LEDS, led_control_s::color, TemperatureCalibrationBase::finish(), hrt_absolute_time(), hrt_abstime, temperature_calibration::instance, led_control, led_control_s::led_mask, led_control_s::mode, led_control_s::num_blinks, orb_copy(), orb_group_count(), ORB_ID, orb_subscribe_multi(), orb_unsubscribe(), param_control_autosave(), param_find(), param_get(), param_notify_changes(), param_save_default(), led_control_s::priority, publish_led_control(), px4_poll(), TemperatureCalibrationBase::reset_calibration(), SENSOR_COUNT_MAX, TC_ERROR_COMMUNICATION, TC_ERROR_INITIAL_TEMP_TOO_HIGH, and TemperatureCalibrationBase::update().
Referenced by do_temperature_calibration().
Member Data Documentation
_accel
bool TemperatureCalibration::_accel private
enable accel calibration?
Definition at line 101 of file task.cpp.
Referenced by task_main().
_baro
bool TemperatureCalibration::_baro private
enable baro calibration?
Definition at line 102 of file task.cpp.
Referenced by task_main().
_control_task
int TemperatureCalibration::_control_task = -1 private
Definition at line 99 of file task.cpp.
Referenced by start().
_force_task_exit
bool TemperatureCalibration::_force_task_exit = false private
Definition at line 98 of file task.cpp.
Referenced by task_main().
_gyro
bool TemperatureCalibration::_gyro private
enable gyro calibration?
Definition at line 103 of file task.cpp.
Referenced by task_main().
_led_control_pub
uORB::PublicationQueued<led_control_s> TemperatureCalibration::_led_control_pub {ORB_ID(led_control)} private
Definition at line 96 of file task.cpp.
Referenced by publish_led_control().
The documentation for this class was generated from the following file:
src/modules/events/temperature_calibration/task.cpp