PX4 Firmware: MavlinkStreamAltitude Class Reference
MavlinkStreamAltitude Class Reference
Public Member Functions
const char * get_name () const override
uint16_t get_id () override
unsigned get_size () override
Get maximal total messages size on update.
Public Member Functions inherited from MavlinkStream
MavlinkStream (Mavlink *mavlink)
virtual ~MavlinkStream ()=default
MavlinkStream (const MavlinkStream &)=delete
MavlinkStream & operator= (const MavlinkStream &)=delete
MavlinkStream (MavlinkStream &&)=delete
MavlinkStream & operator= (MavlinkStream &&)=delete
void set_interval (const int interval)
Get the interval.
int get_interval ()
Get the interval.
int update (const hrt_abstime &t)
Update subscriptions and send message if necessary.
virtual bool const_rate ()
virtual unsigned get_size_avg ()
Get the average message size.
bool first_message_sent () const
void reset_last_sent ()
Reset the time of last sent to 0.
Public Member Functions inherited from ListNode< MavlinkStream *>
void setSibling (MavlinkStream * sibling)
const MavlinkStream * getSibling () const
Static Public Member Functions
static const char * get_name_static ()
static uint16_t get_id_static ()
static MavlinkStream * new_instance (Mavlink *mavlink)
Protected Member Functions
MavlinkStreamAltitude (Mavlink *mavlink)
bool send (const hrt_abstime t) override
Protected Member Functions inherited from MavlinkStream
virtual void update_data ()
Function to collect/update data for the streams at a high rate independant of actual stream rate.
Private Member Functions
MavlinkStreamAltitude (MavlinkStreamAltitude &)=delete
MavlinkStreamAltitude & operator= (const MavlinkStreamAltitude &)=delete
Private Attributes
MavlinkOrbSubscription * _local_pos_sub
MavlinkOrbSubscription * _home_sub
MavlinkOrbSubscription * _air_data_sub
uint64_t _local_pos_time {0}
Additional Inherited Members
Protected Attributes inherited from MavlinkStream
Mavlink *const _mavlink
int _interval {1000000}
if set to negative value = unlimited rate
Protected Attributes inherited from ListNode< MavlinkStream *>
MavlinkStream * _list_node_sibling
Detailed Description
Definition at line 4484 of file mavlink_messages.cpp.
Constructor & Destructor Documentation
MavlinkStreamAltitude() [1/2]
MavlinkStreamAltitude::MavlinkStreamAltitude (MavlinkStreamAltitude &) private delete
MavlinkStreamAltitude() [2/2]
MavlinkStreamAltitude::MavlinkStreamAltitude (Mavlink * mavlink) inline explicit protected
Definition at line 4529 of file mavlink_messages.cpp.
Member Function Documentation
get_id()
uint16_t MavlinkStreamAltitude::get_id () inline override virtual
Implements MavlinkStream.
Definition at line 4502 of file mavlink_messages.cpp.
References MavlinkStreamHeartbeat::get_id_static().
get_id_static()
static uint16_t MavlinkStreamAltitude::get_id_static () inline static
Definition at line 4497 of file mavlink_messages.cpp.
get_name()
const char* MavlinkStreamAltitude::get_name () const inline override virtual
Implements MavlinkStream.
Definition at line 4487 of file mavlink_messages.cpp.
References get_name_static().
get_name_static()
static const char* MavlinkStreamAltitude::get_name_static () inline static
Definition at line 4492 of file mavlink_messages.cpp.
Referenced by get_name().
get_size()
unsigned MavlinkStreamAltitude::get_size () inline override virtual
Get maximal total messages size on update.
Implements MavlinkStream.
Definition at line 4512 of file mavlink_messages.cpp.
new_instance()
static MavlinkStream* MavlinkStreamAltitude::new_instance (Mavlink * mavlink) inline static
Definition at line 4507 of file mavlink_messages.cpp.
operator=()
MavlinkStreamAltitude& MavlinkStreamAltitude::operator= (const MavlinkStreamAltitude &) private delete
send()
bool MavlinkStreamAltitude::send (const hrt_abstime t) inline override protected virtual
Implements MavlinkStream.
Definition at line 4535 of file mavlink_messages.cpp.
References MavlinkStream::_mavlink, vehicle_air_data_s::baro_alt_meter, vehicle_local_position_s::dist_bottom, vehicle_local_position_s::dist_bottom_valid, Mavlink::get_channel(), hrt_absolute_time(), hrt_elapsed_time(), msg, vehicle_local_position_s::ref_alt, vehicle_air_data_s::timestamp, MavlinkOrbSubscription::update(), home_position_s::valid_alt, vehicle_local_position_s::z, home_position_s::z, vehicle_local_position_s::z_global, and vehicle_local_position_s::z_valid.
Member Data Documentation
_air_data_sub
MavlinkOrbSubscription* MavlinkStreamAltitude::_air_data_sub private
Definition at line 4520 of file mavlink_messages.cpp.
_home_sub
MavlinkOrbSubscription* MavlinkStreamAltitude::_home_sub private
Definition at line 4519 of file mavlink_messages.cpp.
_local_pos_sub
MavlinkOrbSubscription* MavlinkStreamAltitude::_local_pos_sub private
Definition at line 4518 of file mavlink_messages.cpp.
_local_pos_time
uint64_t MavlinkStreamAltitude::_local_pos_time {0} private
Definition at line 4522 of file mavlink_messages.cpp.
The documentation for this class was generated from the following file:
src/modules/mavlink/mavlink_messages.cpp