PX4 Firmware: src/drivers/distance_sensor/teraranger/teraranger.cpp File Reference
teraranger.cpp File Reference
#include <px4_config.h>
#include <px4_defines.h>
#include <px4_getopt.h>
#include <px4_workqueue.h>
#include <drivers/device/i2c.h>
#include <sys/types.h>
#include <stdint.h>
#include <stdlib.h>
#include <stdbool.h>
#include <semaphore.h>
#include <string.h>
#include <fcntl.h>
#include <poll.h>
#include <stdio.h>
#include <math.h>
#include <unistd.h>
#include <perf/perf_counter.h>
#include <drivers/drv_hrt.h>
#include <drivers/drv_range_finder.h>
#include <drivers/device/ringbuffer.h>
#include <uORB/uORB.h>
#include <uORB/topics/distance_sensor.h>
#include <board_config.h>
Classes
class TERARANGER
Namespaces
teraranger
Local functions in support of the shell command.
Macros
#define TERARANGER_BUS_DEFAULT PX4_I2C_BUS_EXPANSION
#define TRONE_BASEADDR 0x30 /* 7-bit address */
#define TREVO_BASEADDR 0x31 /* 7-bit address */
#define TERARANGER_DEVICE_PATH "/dev/teraranger"
#define TERARANGER_MEASURE_REG 0x00 /* Measure range register */
#define TERARANGER_WHO_AM_I_REG 0x01 /* Who am I test register */
#define TERARANGER_WHO_AM_I_REG_VAL 0xA1
#define TRONE_MIN_DISTANCE (0.20f)
#define TRONE_MAX_DISTANCE (14.00f)
#define TREVO_60M_MIN_DISTANCE (0.50f)
#define TREVO_60M_MAX_DISTANCE (60.0f)
#define TREVO_600HZ_MIN_DISTANCE (0.75f)
#define TREVO_600HZ_MAX_DISTANCE (8.0f)
#define TERARANGER_CONVERSION_INTERVAL 50000 /* 50ms */
Functions
static uint8_t crc8 (uint8_t *p, uint8_t len)
__EXPORT int teraranger_main (int argc, char *argv[])
int teraranger::start (uint8_t rotation)
Attempt to start driver on all available I2C busses.
int teraranger::start_bus (uint8_t rotation, int i2c_bus)
Start the driver on a specific bus.
int teraranger::stop ()
Stop the driver.
int teraranger::test ()
Perform some basic functional tests on the driver; make sure we can collect data from the sensor in polled and automatic modes.
int teraranger::reset ()
Reset the driver.
int teraranger::info ()
Print a little info about the driver.
static void teraranger_usage ()
Variables
static const uint8_t crc_table []
TERARANGER * teraranger::g_dev
Detailed Description
Author
Luis Rodrigues
Driver for the TeraRanger One range finders connected via I2C.
Definition in file teraranger.cpp.
Macro Definition Documentation
#define TERARANGER_BUS_DEFAULT PX4_I2C_BUS_EXPANSION
Definition at line 72 of file teraranger.cpp.
Referenced by teraranger_main(), and teraranger_usage().
#define TERARANGER_CONVERSION_INTERVAL 50000 /* 50ms */
Definition at line 92 of file teraranger.cpp.
Referenced by TERARANGER::cycle(), TERARANGER::ioctl(), and TERARANGER::read().
#define TERARANGER_DEVICE_PATH "/dev/teraranger"
Definition at line 75 of file teraranger.cpp.
Referenced by teraranger::reset(), teraranger::start_bus(), and teraranger::test().
#define TERARANGER_MEASURE_REG 0x00 /* Measure range register */
Definition at line 79 of file teraranger.cpp.
Referenced by TERARANGER::measure().
#define TERARANGER_WHO_AM_I_REG 0x01 /* Who am I test register */
Definition at line 80 of file teraranger.cpp.
Referenced by TERARANGER::probe().
#define TERARANGER_WHO_AM_I_REG_VAL 0xA1
Definition at line 81 of file teraranger.cpp.
Referenced by TERARANGER::probe().
#define TREVO_600HZ_MAX_DISTANCE (8.0f)
Definition at line 90 of file teraranger.cpp.
Referenced by TERARANGER::init().
#define TREVO_600HZ_MIN_DISTANCE (0.75f)
Definition at line 89 of file teraranger.cpp.
Referenced by TERARANGER::init().
#define TREVO_60M_MAX_DISTANCE (60.0f)
Definition at line 88 of file teraranger.cpp.
Referenced by TERARANGER::init().
#define TREVO_60M_MIN_DISTANCE (0.50f)
Definition at line 87 of file teraranger.cpp.
Referenced by TERARANGER::init().
#define TREVO_BASEADDR 0x31 /* 7-bit address */
Definition at line 74 of file teraranger.cpp.
Referenced by TERARANGER::init().
#define TRONE_BASEADDR 0x30 /* 7-bit address */
Definition at line 73 of file teraranger.cpp.
Referenced by TERARANGER::init().
#define TRONE_MAX_DISTANCE (14.00f)
Definition at line 86 of file teraranger.cpp.
Referenced by DfTROneWrapper::_publish(), and TERARANGER::init().
#define TRONE_MIN_DISTANCE (0.20f)
Definition at line 85 of file teraranger.cpp.
Referenced by DfTROneWrapper::_publish(), and TERARANGER::init().
Function Documentation
static uint8_t crc8 (uint8_t * p, uint8_t len) static
Definition at line 211 of file teraranger.cpp.
References crc_table, and teraranger_main().
Referenced by TERARANGER::collect(), and px4::bst::BST::send_packet().
int teraranger_main (int argc, char * argv[])
Definition at line 989 of file teraranger.cpp.
References teraranger::info(), PX4_ERROR, px4_getopt(), PX4_WARN, teraranger::reset(), teraranger::start(), teraranger::start_bus(), teraranger::stop(), TERARANGER_BUS_DEFAULT, teraranger_usage(), and teraranger::test().
Referenced by crc8().
static void teraranger_usage () static
Definition at line 977 of file teraranger.cpp.
References PX4_INFO, and TERARANGER_BUS_DEFAULT.
Referenced by teraranger_main().
Variable Documentation
const uint8_t crc_table[] static
Initial value:
= {
    0x00, 0x07, 0x0e, 0x09, 0x1c, 0x1b, 0x12, 0x15, 0x38, 0x3f, 0x36, 0x31,
    0x24, 0x23, 0x2a, 0x2d, 0x70, 0x77, 0x7e, 0x79, 0x6c, 0x6b, 0x62, 0x65,
    0x48, 0x4f, 0x46, 0x41, 0x54, 0x53, 0x5a, 0x5d, 0xe0, 0xe7, 0xee, 0xe9,
    0xfc, 0xfb, 0xf2, 0xf5, 0xd8, 0xdf, 0xd6, 0xd1, 0xc4, 0xc3, 0xca, 0xcd,
    0x90, 0x97, 0x9e, 0x99, 0x8c, 0x8b, 0x82, 0x85, 0xa8, 0xaf, 0xa6, 0xa1,
    0xb4, 0xb3, 0xba, 0xbd, 0xc7, 0xc0, 0xc9, 0xce, 0xdb, 0xdc, 0xd5, 0xd2,
    0xff, 0xf8, 0xf1, 0xf6, 0xe3, 0xe4, 0xed, 0xea, 0xb7, 0xb0, 0xb9, 0xbe,
    0xab, 0xac, 0xa5, 0xa2, 0x8f, 0x88, 0x81, 0x86, 0x93, 0x94, 0x9d, 0x9a,
    0x27, 0x20, 0x29, 0x2e, 0x3b, 0x3c, 0x35, 0x32, 0x1f, 0x18, 0x11, 0x16,
    0x03, 0x04, 0x0d, 0x0a, 0x57, 0x50, 0x59, 0x5e, 0x4b, 0x4c, 0x45, 0x42,
    0x6f, 0x68, 0x61, 0x66, 0x73, 0x74, 0x7d, 0x7a, 0x89, 0x8e, 0x87, 0x80,
    0x95, 0x92, 0x9b, 0x9c, 0xb1, 0xb6, 0xbf, 0xb8, 0xad, 0xaa, 0xa3, 0xa4,
    0xf9, 0xfe, 0xf7, 0xf0, 0xe5, 0xe2, 0xeb, 0xec, 0xc1, 0xc6, 0xcf, 0xc8,
    0xdd, 0xda, 0xd3, 0xd4, 0x69, 0x6e, 0x67, 0x60, 0x75, 0x72, 0x7b, 0x7c,
    0x51, 0x56, 0x5f, 0x58, 0x4d, 0x4a, 0x43, 0x44, 0x19, 0x1e, 0x17, 0x10,
    0x05, 0x02, 0x0b, 0x0c, 0x21, 0x26, 0x2f, 0x28, 0x3d, 0x3a, 0x33, 0x34,
    0x4e, 0x49, 0x40, 0x47, 0x52, 0x55, 0x5c, 0x5b, 0x76, 0x71, 0x78, 0x7f,
    0x6a, 0x6d, 0x64, 0x63, 0x3e, 0x39, 0x30, 0x37, 0x22, 0x25, 0x2c, 0x2b,
    0x06, 0x01, 0x08, 0x0f, 0x1a, 0x1d, 0x14, 0x13, 0xae, 0xa9, 0xa0, 0xa7,
    0xb2, 0xb5, 0xbc, 0xbb, 0x96, 0x91, 0x98, 0x9f, 0x8a, 0x8d, 0x84, 0x83,
    0xde, 0xd9, 0xd0, 0xd7, 0xc2, 0xc5, 0xcc, 0xcb, 0xe6, 0xe1, 0xe8, 0xef,
    0xfa, 0xfd, 0xf4, 0xf3
}
Definition at line 186 of file teraranger.cpp.
Referenced by crc8().