PX4 Firmware: LPS22HB_I2C Class Reference
LPS22HB_I2C Class Reference
Public Member Functions
LPS22HB_I2C (int bus)
virtual ~LPS22HB_I2C ()=default
virtual int read (unsigned address, void *data, unsigned count)
virtual int write (unsigned address, void *data, unsigned count)
Protected Member Functions
virtual int probe ()
Detailed Description
Definition at line 55 of file LPS22HB_I2C.cpp.
Constructor & Destructor Documentation
LPS22HB_I2C::LPS22HB_I2C (int bus)
Definition at line 75 of file LPS22HB_I2C.cpp.
Referenced by LPS22HB_I2C_interface().
virtual LPS22HB_I2C::~LPS22HB_I2C () virtual default
Member Function Documentation
int LPS22HB_I2C::probe () protected virtual
Definition at line 81 of file LPS22HB_I2C.cpp.
References DEVICE_DEBUG, LPS22HB_ID_WHO_AM_I, OK, read(), and WHO_AM_I.
int LPS22HB_I2C::read (unsigned address, void * data, unsigned count) virtual
Definition at line 118 of file LPS22HB_I2C.cpp.
Referenced by probe().
int LPS22HB_I2C::write (unsigned address, void * data, unsigned count) virtual
Definition at line 103 of file LPS22HB_I2C.cpp.
The documentation for this class was generated from the following file:
src/drivers/barometer/lps22hb/LPS22HB_I2C.cpp