PX4 Firmware: bmp388 Namespace Reference
bmp388 Namespace Reference
Classes
struct bmp388_bus_option
Functions
static struct bmp388_bus_option * find_bus (BMP388_BUS busid)
static bool start_bus (bmp388_bus_option &bus)
static int start (BMP388_BUS busid)
static int stop (BMP388_BUS busid)
static int status (BMP388_BUS busid)
static int usage ()
Variables
struct bmp388::bmp388_bus_option bus_options []
Function Documentation
find_bus()
static struct bmp388_bus_option* bmp388::find_bus (BMP388_BUS busid) static
Definition at line 81 of file bmp388_main.cpp.
References ALL, and bus_options.
Referenced by status(), and stop().
start()
static int bmp388::start (BMP388_BUS busid) static
Definition at line 118 of file bmp388_main.cpp.
References ALL, bus_options, and start_bus().
Referenced by bmp388_main().
start_bus()
static bool bmp388::start_bus (bmp388_bus_option & bus) static
Definition at line 94 of file bmp388_main.cpp.
References BMP388::init().
Referenced by start().
status()
static int bmp388::status (BMP388_BUS busid) static
Definition at line 156 of file bmp388_main.cpp.
References bmp388::bmp388_bus_option::dev, find_bus(), and BMP388::print_info().
Referenced by bmp388_main().
stop()
static int bmp388::stop (BMP388_BUS busid) static
Definition at line 140 of file bmp388_main.cpp.
References bmp388::bmp388_bus_option::dev, and find_bus().
Referenced by bmp388_main().
usage()
static int bmp388::usage (void) static
Definition at line 169 of file bmp388_main.cpp.
Referenced by bmp388_main().
Variable Documentation
bus_options
struct bmp388::bmp388_bus_option bmp388::bus_options[]
Initial value:
= {
}
Referenced by find_bus(), and start().