PX4 Firmware: MavlinkStreamAttitude Class Reference
MavlinkStreamAttitude Class Reference
Public Member Functions
const char * get_name () const override
uint16_t get_id () override
unsigned get_size () override
Get maximal total messages size on update.
Public Member Functions inherited from MavlinkStream
MavlinkStream (Mavlink *mavlink)
virtual ~MavlinkStream ()=default
MavlinkStream (const MavlinkStream &)=delete
MavlinkStream & operator= (const MavlinkStream &)=delete
MavlinkStream (MavlinkStream &&)=delete
MavlinkStream & operator= (MavlinkStream &&)=delete
void set_interval (const int interval)
Get the interval.
int get_interval ()
Get the interval.
int update (const hrt_abstime &t)
Update subscriptions and send message if necessary.
virtual bool const_rate ()
virtual unsigned get_size_avg ()
Get the average message size.
bool first_message_sent () const
void reset_last_sent ()
Reset the time of last sent to 0.
Public Member Functions inherited from ListNode< MavlinkStream *>
void setSibling (MavlinkStream * sibling)
const MavlinkStream * getSibling () const
Static Public Member Functions
static const char * get_name_static ()
static uint16_t get_id_static ()
static MavlinkStream * new_instance (Mavlink *mavlink)
Protected Member Functions
MavlinkStreamAttitude (Mavlink *mavlink)
bool send (const hrt_abstime t) override
Protected Member Functions inherited from MavlinkStream
virtual void update_data ()
Function to collect/update data for the streams at a high rate independant of actual stream rate.
Private Member Functions
MavlinkStreamAttitude (MavlinkStreamAttitude &)=delete
MavlinkStreamAttitude & operator= (const MavlinkStreamAttitude &)=delete
Private Attributes
MavlinkOrbSubscription * _att_sub
MavlinkOrbSubscription * _angular_velocity_sub
uint64_t _att_time {0}
Additional Inherited Members
Protected Attributes inherited from MavlinkStream
Mavlink *const _mavlink
int _interval {1000000}
if set to negative value = unlimited rate
Protected Attributes inherited from ListNode< MavlinkStream *>
MavlinkStream * _list_node_sibling
Detailed Description
Definition at line 1178 of file mavlink_messages.cpp.
Constructor & Destructor Documentation
MavlinkStreamAttitude() [1/2]
MavlinkStreamAttitude::MavlinkStreamAttitude (MavlinkStreamAttitude &) private delete
MavlinkStreamAttitude() [2/2]
MavlinkStreamAttitude::MavlinkStreamAttitude (Mavlink * mavlink) inline explicit protected
Definition at line 1222 of file mavlink_messages.cpp.
Member Function Documentation
get_id()
uint16_t MavlinkStreamAttitude::get_id () inline override virtual
Implements MavlinkStream.
Definition at line 1196 of file mavlink_messages.cpp.
References MavlinkStreamHeartbeat::get_id_static().
get_id_static()
static uint16_t MavlinkStreamAttitude::get_id_static () inline static
Definition at line 1191 of file mavlink_messages.cpp.
get_name()
const char* MavlinkStreamAttitude::get_name () const inline override virtual
Implements MavlinkStream.
Definition at line 1181 of file mavlink_messages.cpp.
References get_name_static().
get_name_static()
static const char* MavlinkStreamAttitude::get_name_static () inline static
Definition at line 1186 of file mavlink_messages.cpp.
Referenced by get_name().
get_size()
unsigned MavlinkStreamAttitude::get_size () inline override virtual
Get maximal total messages size on update.
Implements MavlinkStream.
Definition at line 1206 of file mavlink_messages.cpp.
new_instance()
static MavlinkStream* MavlinkStreamAttitude::new_instance (Mavlink * mavlink) inline static
Definition at line 1201 of file mavlink_messages.cpp.
operator=()
MavlinkStreamAttitude& MavlinkStreamAttitude::operator= (const MavlinkStreamAttitude &) private delete
send()
bool MavlinkStreamAttitude::send (const hrt_abstime t) inline override protected virtual
Implements MavlinkStream.
Definition at line 1227 of file mavlink_messages.cpp.
References MavlinkStream::_mavlink, Mavlink::get_channel(), msg, matrix::Euler< Type >::phi(), matrix::Euler< Type >::psi(), vehicle_attitude_s::q, matrix::Euler< Type >::theta(), vehicle_attitude_s::timestamp, and MavlinkOrbSubscription::update().
Member Data Documentation
_angular_velocity_sub
MavlinkOrbSubscription* MavlinkStreamAttitude::_angular_velocity_sub private
Definition at line 1213 of file mavlink_messages.cpp.
_att_sub
MavlinkOrbSubscription* MavlinkStreamAttitude::_att_sub private
Definition at line 1212 of file mavlink_messages.cpp.
_att_time
uint64_t MavlinkStreamAttitude::_att_time {0} private
Definition at line 1214 of file mavlink_messages.cpp.
The documentation for this class was generated from the following file:
src/modules/mavlink/mavlink_messages.cpp