PX4 Firmware: MavlinkStreamOpticalFlowRad Class Reference
MavlinkStreamOpticalFlowRad Class Reference
Public Member Functions
const char * get_name () const override
uint16_t get_id () override
unsigned get_size () override
Get maximal total messages size on update.
Public Member Functions inherited from MavlinkStream
MavlinkStream (Mavlink *mavlink)
virtual ~MavlinkStream ()=default
MavlinkStream (const MavlinkStream &)=delete
MavlinkStream & operator= (const MavlinkStream &)=delete
MavlinkStream (MavlinkStream &&)=delete
MavlinkStream & operator= (MavlinkStream &&)=delete
void set_interval (const int interval)
Get the interval.
int get_interval ()
Get the interval.
int update (const hrt_abstime &t)
Update subscriptions and send message if necessary.
virtual bool const_rate ()
virtual unsigned get_size_avg ()
Get the average message size.
bool first_message_sent () const
void reset_last_sent ()
Reset the time of last sent to 0.
Public Member Functions inherited from ListNode< MavlinkStream *>
void setSibling (MavlinkStream * sibling)
const MavlinkStream * getSibling () const
Static Public Member Functions
static const char * get_name_static ()
static uint16_t get_id_static ()
static MavlinkStream * new_instance (Mavlink *mavlink)
Protected Member Functions
MavlinkStreamOpticalFlowRad (Mavlink *mavlink)
bool send (const hrt_abstime t) override
Protected Member Functions inherited from MavlinkStream
virtual void update_data ()
Function to collect/update data for the streams at a high rate independant of actual stream rate.
Private Member Functions
MavlinkStreamOpticalFlowRad (MavlinkStreamOpticalFlowRad &)=delete
MavlinkStreamOpticalFlowRad & operator= (const MavlinkStreamOpticalFlowRad &)=delete
Private Attributes
MavlinkOrbSubscription * _flow_sub
uint64_t _flow_time
Additional Inherited Members
Protected Attributes inherited from MavlinkStream
Mavlink *const _mavlink
int _interval {1000000}
if set to negative value = unlimited rate
Protected Attributes inherited from ListNode< MavlinkStream *>
MavlinkStream * _list_node_sibling
Detailed Description
Definition at line 3767 of file mavlink_messages.cpp.
Constructor & Destructor Documentation
MavlinkStreamOpticalFlowRad() [1/2]
MavlinkStreamOpticalFlowRad::MavlinkStreamOpticalFlowRad (MavlinkStreamOpticalFlowRad &) private delete
MavlinkStreamOpticalFlowRad() [2/2]
MavlinkStreamOpticalFlowRad::MavlinkStreamOpticalFlowRad (Mavlink * mavlink) inline explicit protected
Definition at line 3809 of file mavlink_messages.cpp.
Member Function Documentation
get_id()
uint16_t MavlinkStreamOpticalFlowRad::get_id () inline override virtual
Implements MavlinkStream.
Definition at line 3785 of file mavlink_messages.cpp.
References MavlinkStreamHeartbeat::get_id_static().
get_id_static()
static uint16_t MavlinkStreamOpticalFlowRad::get_id_static () inline static
Definition at line 3780 of file mavlink_messages.cpp.
get_name()
const char* MavlinkStreamOpticalFlowRad::get_name () const inline override virtual
Implements MavlinkStream.
Definition at line 3770 of file mavlink_messages.cpp.
References get_name_static().
get_name_static()
static const char* MavlinkStreamOpticalFlowRad::get_name_static () inline static
Definition at line 3775 of file mavlink_messages.cpp.
Referenced by get_name().
get_size()
unsigned MavlinkStreamOpticalFlowRad::get_size () inline override virtual
Get maximal total messages size on update.
Implements MavlinkStream.
Definition at line 3795 of file mavlink_messages.cpp.
new_instance()
static MavlinkStream* MavlinkStreamOpticalFlowRad::new_instance (Mavlink * mavlink) inline static
Definition at line 3790 of file mavlink_messages.cpp.
operator=()
MavlinkStreamOpticalFlowRad& MavlinkStreamOpticalFlowRad::operator= (const MavlinkStreamOpticalFlowRad &) private delete
send()
bool MavlinkStreamOpticalFlowRad::send (const hrt_abstime t) inline override protected virtual
Implements MavlinkStream.
Definition at line 3814 of file mavlink_messages.cpp.
References MavlinkStream::_mavlink, Mavlink::get_channel(), optical_flow_s::ground_distance_m, optical_flow_s::gyro_temperature, optical_flow_s::gyro_x_rate_integral, optical_flow_s::gyro_y_rate_integral, optical_flow_s::gyro_z_rate_integral, optical_flow_s::integration_timespan, msg, optical_flow_s::pixel_flow_x_integral, optical_flow_s::pixel_flow_y_integral, optical_flow_s::quality, optical_flow_s::sensor_id, optical_flow_s::time_since_last_sonar_update, optical_flow_s::timestamp, and MavlinkOrbSubscription::update().
Member Data Documentation
_flow_sub
MavlinkOrbSubscription* MavlinkStreamOpticalFlowRad::_flow_sub private
Definition at line 3801 of file mavlink_messages.cpp.
_flow_time
uint64_t MavlinkStreamOpticalFlowRad::_flow_time private
Definition at line 3802 of file mavlink_messages.cpp.
The documentation for this class was generated from the following file:
src/modules/mavlink/mavlink_messages.cpp