PX4 Firmware: ADIS16448 Class Reference
ADIS16448 Class Reference
Classes
struct ADISReport
Report conversation with in the ADIS16448, including command byte and interrupt status.
Public Member Functions
ADIS16448 (int bus, const char *path_accel, const char *path_gyro, const char *path_mag, uint32_t device, enum Rotation rotation)
virtual ~ADIS16448 ()
virtual int init ()
virtual ssize_t read (struct file *filp, char *buffer, size_t buflen)
virtual int ioctl (struct file *filp, int cmd, unsigned long arg)
void print_info ()
Diagnostics - print some basic information about the driver and sensor.
void print_calibration_data ()
Protected Member Functions
virtual int probe ()
virtual ssize_t gyro_read (struct file *filp, char *buffer, size_t buflen)
virtual int gyro_ioctl (struct file *filp, int cmd, unsigned long arg)
virtual ssize_t mag_read (struct file *filp, char *buffer, size_t buflen)
virtual int mag_ioctl (struct file *filp, int cmd, unsigned long arg)
Private Member Functions
void start ()
Start automatic measurement.
void stop ()
Stop automatic measurement.
int reset ()
Reset chip.
int measure ()
Fetch measurements from the sensor and update the report buffers.
uint16_t read_reg16 (unsigned reg)
Read a register from the ADIS16448.
void write_reg16 (unsigned reg, uint16_t value)
Write a register in the ADIS16448.
void modify_reg16 (unsigned reg, uint16_t clearbits, uint16_t setbits)
Modify a register in the ADIS16448.
uint16_t swap16 (uint16_t val)
Swap a 16-bit value read from the ADIS16448 to native byte order.
int16_t convert12BitToINT16 (int16_t word)
convert 12 bit integer format to int16.
int self_test ()
Measurement self test.
void _set_dlpf_filter (uint16_t frequency_hz)
void _set_factory_default ()
void _set_sample_rate (uint16_t desired_sample_rate_hz)
void _set_gyro_dyn_range (uint16_t desired_gyro_dyn_range)
ADIS16448 (const ADIS16448 &)
ADIS16448 operator= (const ADIS16448 &)
Static Private Member Functions
static void measure_trampoline (void *arg)
Static trampoline from the hrt_call context; because we don't have a generic hrt wrapper yet.
Private Attributes
ADIS16448_gyro * _gyro
ADIS16448_mag * _mag
uint16_t _product
struct hrt_call _call
product code
unsigned _call_interval
ringbuffer::RingBuffer * _gyro_reports
struct gyro_calibration_s _gyro_scale
float _gyro_range_scale
float _gyro_range_rad_s
ringbuffer::RingBuffer * _accel_reports
struct accel_calibration_s _accel_scale
float _accel_range_scale
float _accel_range_m_s2
orb_advert_t _accel_topic
int _accel_orb_class_instance
int _accel_class_instance
ringbuffer::RingBuffer * _mag_reports
struct mag_calibration_s _mag_scale
float _mag_range_scale
float _mag_range_mgauss
unsigned _sample_rate
perf_counter_t _accel_reads
perf_counter_t _gyro_reads
perf_counter_t _mag_reads
perf_counter_t _sample_perf
perf_counter_t _bad_transfers
math::LowPassFilter2p _gyro_filter_x
math::LowPassFilter2p _gyro_filter_y
math::LowPassFilter2p _gyro_filter_z
math::LowPassFilter2p _accel_filter_x
math::LowPassFilter2p _accel_filter_y
math::LowPassFilter2p _accel_filter_z
math::LowPassFilter2p _mag_filter_x
math::LowPassFilter2p _mag_filter_y
math::LowPassFilter2p _mag_filter_z
Integrator _accel_int
Integrator _gyro_int
enum Rotation _rotation
Friends
class ADIS16448_gyro
class ADIS16448_mag
Detailed Description
Definition at line 188 of file adis16448.cpp.
Constructor & Destructor Documentation
ADIS16448::ADIS16448 (int bus, const char * path_accel, const char * path_gyro, const char * path_mag, uint32_t device, enum Rotation rotation)
Definition at line 471 of file adis16448.cpp.
References _accel_class_instance, _accel_filter_x, _accel_filter_y, _accel_filter_z, _accel_int, _accel_orb_class_instance, _accel_range_m_s2, _accel_range_scale, _accel_reads, _accel_reports, _accel_scale, _accel_topic, _bad_transfers, _call, _call_interval, device::Device::_device_id, _gyro, _gyro_filter_x, _gyro_filter_y, _gyro_filter_z, _gyro_int, _gyro_range_rad_s, _gyro_range_scale, _gyro_reads, _gyro_reports, _gyro_scale, _mag, _mag_filter_x, _mag_filter_y, _mag_filter_z, _mag_range_mgauss, _mag_range_scale, _mag_reads, _mag_reports, _mag_scale, _rotation, _sample_perf, _sample_rate, ADIS16448_ACCEL_DEFAULT_DRIVER_FILTER_FREQ, ADIS16448_ACCEL_DEFAULT_RATE, ADIS16448_ACCEL_MAX_OUTPUT_RATE, ADIS16448_GYRO_DEFAULT_DRIVER_FILTER_FREQ, ADIS16448_GYRO_DEFAULT_RATE, ADIS16448_GYRO_MAX_OUTPUT_RATE, ADIS16448_MAG_DEFAULT_DRIVER_FILTER_FREQ, ADIS16448_MAG_DEFAULT_RATE, device::Device::DeviceId::devid, device::Device::DeviceId::devid_s, device::Device::DeviceStructure::devtype, DRV_ACC_DEVTYPE_ADIS16448, DRV_GYR_DEVTYPE_ADIS16448, DRV_MAG_DEVTYPE_ADIS16448, f(), PC_COUNT, PC_ELAPSED, perf_alloc, mag_calibration_s::x_offset, accel_calibration_s::x_offset, gyro_calibration_s::x_offset, mag_calibration_s::x_scale, accel_calibration_s::x_scale, gyro_calibration_s::x_scale, mag_calibration_s::y_offset, accel_calibration_s::y_offset, gyro_calibration_s::y_offset, mag_calibration_s::y_scale, gyro_calibration_s::y_scale, accel_calibration_s::y_scale, mag_calibration_s::z_offset, accel_calibration_s::z_offset, gyro_calibration_s::z_offset, mag_calibration_s::z_scale, accel_calibration_s::z_scale, and gyro_calibration_s::z_scale.
Referenced by swap16().
ADIS16448::~ADIS16448 () virtual
Definition at line 551 of file adis16448.cpp.
References _accel_class_instance, _accel_reads, _accel_reports, _bad_transfers, _gyro, _gyro_reads, _gyro_reports, _mag, _mag_reads, _mag_reports, _sample_perf, ACCEL_BASE_DEVICE_PATH, perf_free(), and stop().
ADIS16448::ADIS16448 (const ADIS16448 &) private
Member Function Documentation
void ADIS16448::_set_dlpf_filter (uint16_t frequency_hz) private
Definition at line 791 of file adis16448.cpp.
References ADIS16448_SENS_AVG, DEVICE_DEBUG, modify_reg16(), and read_reg16().
Referenced by reset(), and swap16().
void ADIS16448::_set_factory_default () private
Definition at line 805 of file adis16448.cpp.
References ADIS16448_GLOB_CMD, and write_reg16().
Referenced by swap16().
void ADIS16448::_set_gyro_dyn_range (uint16_t desired_gyro_dyn_range) private
Definition at line 812 of file adis16448.cpp.
References _gyro_range_rad_s, _gyro_range_scale, ADIS16448_SENS_AVG, BITS_GYRO_DYN_RANGE_1000_CFG, BITS_GYRO_DYN_RANGE_250_CFG, BITS_GYRO_DYN_RANGE_500_CFG, DEVICE_DEBUG, M_PI_F, modify_reg16(), and read_reg16().
Referenced by gyro_ioctl(), reset(), and swap16().
void ADIS16448::_set_sample_rate (uint16_t desired_sample_rate_hz) private
Definition at line 761 of file adis16448.cpp.
References ADIS16448_SMPL_PRD, BITS_SMPL_PRD_16_TAP_CFG, BITS_SMPL_PRD_2_TAP_CFG, BITS_SMPL_PRD_4_TAP_CFG, BITS_SMPL_PRD_8_TAP_CFG, BITS_SMPL_PRD_NO_TAP_CFG, DEVICE_DEBUG, modify_reg16(), and read_reg16().
Referenced by gyro_ioctl(), ioctl(), mag_ioctl(), reset(), and swap16().
int16_t ADIS16448::convert12BitToINT16 (int16_t word) private
convert 12 bit integer format to int16.
Definition at line 1276 of file adis16448.cpp.
Referenced by measure(), and swap16().
int ADIS16448::gyro_ioctl (struct file * filp, int cmd, unsigned long arg) protected virtual
Definition at line 1116 of file adis16448.cpp.
References _gyro_range_rad_s, _gyro_reports, _gyro_scale, _sample_rate, _set_gyro_dyn_range(), _set_sample_rate(), ADIS16448_Product, GYROIOCGRANGE, GYROIOCGSAMPLERATE, GYROIOCGSCALE, GYROIOCSRANGE, GYROIOCSSAMPLERATE, GYROIOCSSCALE, GYROIOCTYPE, ioctl(), M_PI_F, OK, SENSORIOCGPOLLRATE, SENSORIOCRESET, SENSORIOCSPOLLRATE, and SENSORIOCSQUEUEDEPTH.
Referenced by ADIS16448_gyro::ioctl().
ssize_t ADIS16448::gyro_read (struct file * filp, char * buffer, size_t buflen) protected virtual
Definition at line 893 of file adis16448.cpp.
References _call_interval, _gyro_reads, _gyro_reports, gyro_report, measure(), and perf_count().
Referenced by ADIS16448_gyro::read().
int ADIS16448::init () virtual
Definition at line 586 of file adis16448.cpp.
References _accel_class_instance, _accel_orb_class_instance, _accel_reports, _accel_scale, _accel_topic, _gyro, ADIS16448_gyro::_gyro_orb_class_instance, _gyro_reports, _gyro_scale, ADIS16448_gyro::_gyro_topic, _mag, ADIS16448_mag::_mag_orb_class_instance, _mag_reports, _mag_scale, ADIS16448_mag::_mag_topic, ACCEL_BASE_DEVICE_PATH, accel_report, DEVICE_DEBUG, gyro_report, lis3mdl::init(), ADIS16448_gyro::init(), ADIS16448_mag::init(), mag_report, measure(), OK, orb_advertise_multi(), ORB_ID, ORB_PRIO_MAX, reset(), warnx, mag_calibration_s::x_offset, gyro_calibration_s::x_offset, accel_calibration_s::x_offset, mag_calibration_s::x_scale, gyro_calibration_s::x_scale, accel_calibration_s::x_scale, mag_calibration_s::y_offset, gyro_calibration_s::y_offset, accel_calibration_s::y_offset, mag_calibration_s::y_scale, gyro_calibration_s::y_scale, accel_calibration_s::y_scale, mag_calibration_s::z_offset, accel_calibration_s::z_offset, gyro_calibration_s::z_offset, mag_calibration_s::z_scale, gyro_calibration_s::z_scale, and accel_calibration_s::z_scale.
int ADIS16448::ioctl (struct file * filp, int cmd, unsigned long arg) virtual
Definition at line 973 of file adis16448.cpp.
References _accel_filter_x, _accel_filter_y, _accel_filter_z, _accel_range_m_s2, _accel_reports, _accel_scale, _call, _call_interval, _gyro_filter_x, _gyro_filter_y, _gyro_filter_z, _mag_filter_x, _mag_filter_y, _mag_filter_z, _sample_rate, _set_sample_rate(), ACCELIOCGRANGE, ACCELIOCGSAMPLERATE, ACCELIOCGSCALE, ACCELIOCSRANGE, ACCELIOCSSAMPLERATE, ACCELIOCSSCALE, ACCELIOCTYPE, ADIS16448_ACCEL_DEFAULT_RATE, ADIS16448_Product, CONSTANTS_ONE_G, f(), math::LowPassFilter2p::get_cutoff_freq(), OK, hrt_call::period, reset(), SENSOR_POLLRATE_DEFAULT, SENSOR_POLLRATE_EXTERNAL, SENSOR_POLLRATE_MANUAL, SENSOR_POLLRATE_MAX, SENSORIOCGPOLLRATE, SENSORIOCRESET, SENSORIOCSPOLLRATE, SENSORIOCSQUEUEDEPTH, math::LowPassFilter2p::set_cutoff_frequency(), start(), stop(), accel_calibration_s::x_scale, accel_calibration_s::y_scale, and accel_calibration_s::z_scale.
Referenced by gyro_ioctl(), and mag_ioctl().
int ADIS16448::mag_ioctl (struct file * filp, int cmd, unsigned long arg) protected virtual
Definition at line 1178 of file adis16448.cpp.
References _mag_range_mgauss, _mag_reports, _mag_scale, _sample_rate, _set_sample_rate(), ADIS16448_Product, ioctl(), MAGIOCGRANGE, MAGIOCGSAMPLERATE, MAGIOCGSCALE, MAGIOCSSAMPLERATE, MAGIOCSSCALE, MAGIOCTYPE, OK, SENSORIOCGPOLLRATE, SENSORIOCRESET, SENSORIOCSPOLLRATE, and SENSORIOCSQUEUEDEPTH.
Referenced by ADIS16448_mag::ioctl().
ssize_t ADIS16448::mag_read (struct file * filp, char * buffer, size_t buflen) protected virtual
Definition at line 933 of file adis16448.cpp.
References _call_interval, _mag_reads, _mag_reports, mag_report, measure(), and perf_count().
Referenced by ADIS16448_mag::read().
int ADIS16448::measure () private
Fetch measurements from the sensor and update the report buffers.
Definition at line 1325 of file adis16448.cpp.
References _accel_filter_x, _accel_filter_y, _accel_filter_z, _accel_int, _accel_range_scale, _accel_reports, _accel_scale, _accel_topic, _bad_transfers, device::Device::_device_id, _gyro, _gyro_filter_x, _gyro_filter_y, _gyro_filter_z, _gyro_int, _gyro_range_scale, _gyro_reports, _gyro_scale, ADIS16448_gyro::_gyro_topic, _mag, _mag_filter_x, _mag_filter_y, _mag_filter_z, _mag_range_scale, _mag_reports, _mag_scale, ADIS16448_mag::_mag_topic, _rotation, _sample_perf, accel_report, ADIS16448_GLOB_CMD, math::LowPassFilter2p::apply(), baro(), ADIS16448::ADISReport::cmd, convert12BitToINT16(), device::Device::DeviceId::devid, DIR_READ, f(), FW_FILTER, gyro_report, hrt_absolute_time(), M_PI_F, mag_report, OK, ORB_ID, orb_publish(), ADIS16448_gyro::parent_poll_notify(), ADIS16448_mag::parent_poll_notify(), perf_begin(), perf_count(), perf_end(), perf_event_count(), Integrator::put(), rotate_3f(), mag_calibration_s::x_offset, gyro_calibration_s::x_offset, accel_calibration_s::x_offset, mag_calibration_s::x_scale, gyro_calibration_s::x_scale, accel_calibration_s::x_scale, mag_calibration_s::y_offset, accel_calibration_s::y_offset, gyro_calibration_s::y_offset, mag_calibration_s::y_scale, accel_calibration_s::y_scale, gyro_calibration_s::y_scale, mag_calibration_s::z_offset, gyro_calibration_s::z_offset, accel_calibration_s::z_offset, mag_calibration_s::z_scale, gyro_calibration_s::z_scale, and accel_calibration_s::z_scale.
Referenced by ADIS16448::ADISReport::ADISReport(), gyro_read(), init(), mag_read(), measure_trampoline(), read(), and self_test().
void ADIS16448::measure_trampoline (void * arg) static private
Static trampoline from the hrt_call context; because we don't have a generic hrt wrapper yet.
Called by the HRT in interrupt context at the specified rate if automatic polling is enabled.
Parameters
arg Instance pointer for the driver that is polling.
Definition at line 1316 of file adis16448.cpp.
References measure().
Referenced by ADIS16448::ADISReport::ADISReport(), and start().
void ADIS16448::modify_reg16 (unsigned reg, uint16_t clearbits, uint16_t setbits) private
Modify a register in the ADIS16448.
Bits are cleared before bits are set.
Parameters
reg The register to modify.
clearbits Bits in the register to clear.
setbits Bits in the register to set.
Definition at line 1265 of file adis16448.cpp.
References read_reg16(), and write_reg16().
Referenced by _set_dlpf_filter(), _set_gyro_dyn_range(), _set_sample_rate(), ADIS16448::ADISReport::ADISReport(), and probe().
ADIS16448 ADIS16448::operator= (const ADIS16448 &) private
Referenced by swap16().
void ADIS16448::print_calibration_data ()
Definition at line 1535 of file adis16448.cpp.
References ADIS16448_XACCL_OFF, ADIS16448_XGYRO_OFF, ADIS16448_XMAGN_HIC, ADIS16448_XMAGN_SIC, ADIS16448_YACCL_OFF, ADIS16448_YGYRO_OFF, ADIS16448_YMAGN_HIC, ADIS16448_YMAGN_SIC, ADIS16448_ZACCL_OFF, ADIS16448_ZGYRO_OFF, ADIS16448_ZMAGN_HIC, ADIS16448_ZMAGN_SIC, read_reg16(), and warnx.
Referenced by adis16448::info_cal().
void ADIS16448::print_info ()
Diagnostics - print some basic information about the driver and sensor.
Definition at line 1566 of file adis16448.cpp.
References _accel_reads, _accel_reports, _bad_transfers, device::Device::_device_id, _gyro, _gyro_reads, _gyro_reports, _mag, _mag_reads, _mag_reports, _sample_perf, device::Device::DeviceId::devid, and perf_print_counter().
Referenced by adis16448::info().
int ADIS16448::probe () protected virtual
Definition at line 730 of file adis16448.cpp.
References _product, ADIS16334_SERIAL_NUMBER, ADIS16448_GPIO_CTRL, ADIS16448_Product, ADIS16448_PRODUCT_ID, DEVICE_DEBUG, modify_reg16(), OK, read_reg16(), and serial_number().
ssize_t ADIS16448::read (struct file * filp, char * buffer, size_t buflen) virtual
Definition at line 842 of file adis16448.cpp.
References _accel_reads, _accel_reports, _call_interval, accel_report, measure(), and perf_count().
uint16_t ADIS16448::read_reg16 (unsigned reg) private
Read a register from the ADIS16448.
Parameters
The register to read.
Returns
The value that was read.
Definition at line 1237 of file adis16448.cpp.
References DIR_READ, and T_STALL.
Referenced by _set_dlpf_filter(), _set_gyro_dyn_range(), _set_sample_rate(), ADIS16448::ADISReport::ADISReport(), modify_reg16(), print_calibration_data(), and probe().
int ADIS16448::reset () private
Reset chip.
Resets the chip and measurements ranges, but not scale and offset.
Definition at line 705 of file adis16448.cpp.
References _accel_range_m_s2, _accel_range_scale, _mag_range_mgauss, _mag_range_scale, _sample_rate, _set_dlpf_filter(), _set_gyro_dyn_range(), _set_sample_rate(), ACCELDYNAMICRANGE, ACCELINITIALSENSITIVITY, BITS_FIR_16_TAP_CFG, CONSTANTS_ONE_G, GYROINITIALSENSITIVITY, MAGDYNAMICRANGE, MAGINITIALSENSITIVITY, and OK.
Referenced by ADIS16448::ADISReport::ADISReport(), init(), and ioctl().
int ADIS16448::self_test () private
Measurement self test.
Returns
0 on success, 1 on failure
Definition at line 882 of file adis16448.cpp.
References _sample_perf, measure(), and perf_event_count().
Referenced by swap16().
void ADIS16448::start () private
Start automatic measurement.
Definition at line 1292 of file adis16448.cpp.
References _accel_reports, _call, _call_interval, _gyro_reports, _mag_reports, hrt_call_every(), measure_trampoline(), and stop().
Referenced by ADIS16448::ADISReport::ADISReport(), and ioctl().
void ADIS16448::stop () private
Stop automatic measurement.
Definition at line 1310 of file adis16448.cpp.
References _call, and hrt_cancel().
Referenced by ADIS16448::ADISReport::ADISReport(), ioctl(), start(), and ~ADIS16448().
uint16_t ADIS16448::swap16 (uint16_t val) inline private
Swap a 16-bit value read from the ADIS16448 to native byte order.
Definition at line 373 of file adis16448.cpp.
References _set_dlpf_filter(), _set_factory_default(), _set_gyro_dyn_range(), _set_sample_rate(), ADIS16448(), convert12BitToINT16(), operator=(), and self_test().
void ADIS16448::write_reg16 (unsigned reg, uint16_t value) private
Write a register in the ADIS16448.
Parameters
reg The register to write.
value The new value to write.
Definition at line 1251 of file adis16448.cpp.
References DIR_WRITE, and T_STALL.
Referenced by _set_factory_default(), ADIS16448::ADISReport::ADISReport(), and modify_reg16().
Friends And Related Function Documentation
friend class ADIS16448_gyro friend
Definition at line 210 of file adis16448.cpp.
friend class ADIS16448_mag friend
Definition at line 211 of file adis16448.cpp.
Member Data Documentation
int ADIS16448::_accel_class_instance private
Definition at line 243 of file adis16448.cpp.
Referenced by ADIS16448(), init(), and ~ADIS16448().
math::LowPassFilter2p ADIS16448::_accel_filter_x private
Definition at line 262 of file adis16448.cpp.
Referenced by ADIS16448(), ioctl(), and measure().
math::LowPassFilter2p ADIS16448::_accel_filter_y private
Definition at line 263 of file adis16448.cpp.
Referenced by ADIS16448(), ioctl(), and measure().
math::LowPassFilter2p ADIS16448::_accel_filter_z private
Definition at line 264 of file adis16448.cpp.
Referenced by ADIS16448(), ioctl(), and measure().
Integrator ADIS16448::_accel_int private
Definition at line 269 of file adis16448.cpp.
Referenced by ADIS16448(), and measure().
int ADIS16448::_accel_orb_class_instance private
Definition at line 242 of file adis16448.cpp.
Referenced by ADIS16448(), and init().
float ADIS16448::_accel_range_m_s2 private
Definition at line 240 of file adis16448.cpp.
Referenced by ADIS16448(), ioctl(), and reset().
float ADIS16448::_accel_range_scale private
Definition at line 239 of file adis16448.cpp.
Referenced by ADIS16448(), measure(), and reset().
perf_counter_t ADIS16448::_accel_reads private
Definition at line 252 of file adis16448.cpp.
Referenced by ADIS16448(), print_info(), read(), and ~ADIS16448().
ringbuffer::RingBuffer* ADIS16448::_accel_reports private
Definition at line 236 of file adis16448.cpp.
Referenced by ADIS16448(), init(), ioctl(), measure(), print_info(), read(), start(), and ~ADIS16448().
struct accel_calibration_s ADIS16448::_accel_scale private
Definition at line 238 of file adis16448.cpp.
Referenced by ADIS16448(), init(), ioctl(), and measure().
orb_advert_t ADIS16448::_accel_topic private
Definition at line 241 of file adis16448.cpp.
Referenced by ADIS16448(), init(), and measure().
perf_counter_t ADIS16448::_bad_transfers private
Definition at line 256 of file adis16448.cpp.
Referenced by ADIS16448(), measure(), print_info(), and ~ADIS16448().
struct hrt_call ADIS16448::_call private
product code
Definition at line 227 of file adis16448.cpp.
Referenced by ADIS16448(), ioctl(), start(), and stop().
unsigned ADIS16448::_call_interval private
Definition at line 228 of file adis16448.cpp.
Referenced by ADIS16448(), gyro_read(), ioctl(), mag_read(), read(), and start().
ADIS16448_gyro* ADIS16448::_gyro private
Definition at line 222 of file adis16448.cpp.
Referenced by ADIS16448(), init(), measure(), print_info(), and ~ADIS16448().
math::LowPassFilter2p ADIS16448::_gyro_filter_x private
Definition at line 259 of file adis16448.cpp.
Referenced by ADIS16448(), ioctl(), and measure().
math::LowPassFilter2p ADIS16448::_gyro_filter_y private
Definition at line 260 of file adis16448.cpp.
Referenced by ADIS16448(), ioctl(), and measure().
math::LowPassFilter2p ADIS16448::_gyro_filter_z private
Definition at line 261 of file adis16448.cpp.
Referenced by ADIS16448(), ioctl(), and measure().
Integrator ADIS16448::_gyro_int private
Definition at line 270 of file adis16448.cpp.
Referenced by ADIS16448(), and measure().
float ADIS16448::_gyro_range_rad_s private
Definition at line 234 of file adis16448.cpp.
Referenced by _set_gyro_dyn_range(), ADIS16448(), and gyro_ioctl().
float ADIS16448::_gyro_range_scale private
Definition at line 233 of file adis16448.cpp.
Referenced by _set_gyro_dyn_range(), ADIS16448(), and measure().
perf_counter_t ADIS16448::_gyro_reads private
Definition at line 253 of file adis16448.cpp.
Referenced by ADIS16448(), gyro_read(), print_info(), and ~ADIS16448().
ringbuffer::RingBuffer* ADIS16448::_gyro_reports private
Definition at line 230 of file adis16448.cpp.
Referenced by ADIS16448(), gyro_ioctl(), gyro_read(), init(), measure(), print_info(), start(), and ~ADIS16448().
struct gyro_calibration_s ADIS16448::_gyro_scale private
Definition at line 232 of file adis16448.cpp.
Referenced by ADIS16448(), gyro_ioctl(), init(), and measure().
ADIS16448_mag* ADIS16448::_mag private
Definition at line 223 of file adis16448.cpp.
Referenced by ADIS16448(), init(), measure(), print_info(), and ~ADIS16448().
math::LowPassFilter2p ADIS16448::_mag_filter_x private
Definition at line 265 of file adis16448.cpp.
Referenced by ADIS16448(), ioctl(), and measure().
math::LowPassFilter2p ADIS16448::_mag_filter_y private
Definition at line 266 of file adis16448.cpp.
Referenced by ADIS16448(), ioctl(), and measure().
math::LowPassFilter2p ADIS16448::_mag_filter_z private
Definition at line 267 of file adis16448.cpp.
Referenced by ADIS16448(), ioctl(), and measure().
float ADIS16448::_mag_range_mgauss private
Definition at line 249 of file adis16448.cpp.
Referenced by ADIS16448(), mag_ioctl(), and reset().
float ADIS16448::_mag_range_scale private
Definition at line 248 of file adis16448.cpp.
Referenced by ADIS16448(), measure(), and reset().
perf_counter_t ADIS16448::_mag_reads private
Definition at line 254 of file adis16448.cpp.
Referenced by ADIS16448(), mag_read(), print_info(), and ~ADIS16448().
ringbuffer::RingBuffer* ADIS16448::_mag_reports private
Definition at line 245 of file adis16448.cpp.
Referenced by ADIS16448(), init(), mag_ioctl(), mag_read(), measure(), print_info(), start(), and ~ADIS16448().
struct mag_calibration_s ADIS16448::_mag_scale private
Definition at line 247 of file adis16448.cpp.
Referenced by ADIS16448(), init(), mag_ioctl(), and measure().
uint16_t ADIS16448::_product private
Definition at line 225 of file adis16448.cpp.
Referenced by probe().
enum Rotation ADIS16448::_rotation private
Definition at line 272 of file adis16448.cpp.
Referenced by ADIS16448(), and measure().
perf_counter_t ADIS16448::_sample_perf private
Definition at line 255 of file adis16448.cpp.
Referenced by ADIS16448(), measure(), print_info(), self_test(), and ~ADIS16448().
unsigned ADIS16448::_sample_rate private
Definition at line 251 of file adis16448.cpp.
Referenced by ADIS16448(), gyro_ioctl(), ioctl(), mag_ioctl(), and reset().
The documentation for this class was generated from the following file:
src/drivers/imu/adis16448/adis16448.cpp