PX4 Firmware: frsky_subscription_data_s Struct Reference
frsky_subscription_data_s Struct Reference
Public Attributes
uORB::SubscriptionData< battery_status_s > battery_status_sub {ORB_ID(battery_status)}
uORB::SubscriptionData< sensor_combined_s > sensor_combined_sub {ORB_ID(sensor_combined)}
uORB::SubscriptionData< vehicle_air_data_s > vehicle_air_data_sub {ORB_ID(vehicle_air_data)}
uORB::SubscriptionData< vehicle_global_position_s > vehicle_global_position_sub {ORB_ID(vehicle_global_position)}
uORB::SubscriptionData< vehicle_gps_position_s > vehicle_gps_position_sub {ORB_ID(vehicle_gps_position)}
uORB::SubscriptionData< vehicle_status_s > vehicle_status_sub {ORB_ID(vehicle_status)}
Detailed Description
Definition at line 66 of file frsky_data.cpp.
Member Data Documentation
battery_status_sub
uORB::SubscriptionData<battery_status_s> frsky_subscription_data_s::battery_status_sub {ORB_ID(battery_status)}
Definition at line 68 of file frsky_data.cpp.
Referenced by frsky_send_frame1(), frsky_send_frame2(), and frsky_update_topics().
sensor_combined_sub
uORB::SubscriptionData<sensor_combined_s> frsky_subscription_data_s::sensor_combined_sub {ORB_ID(sensor_combined)}
Definition at line 69 of file frsky_data.cpp.
Referenced by frsky_send_frame1(), and frsky_update_topics().
vehicle_air_data_sub
uORB::SubscriptionData<vehicle_air_data_s> frsky_subscription_data_s::vehicle_air_data_sub {ORB_ID(vehicle_air_data)}
Definition at line 70 of file frsky_data.cpp.
Referenced by frsky_send_frame1(), and frsky_update_topics().
vehicle_global_position_sub
uORB::SubscriptionData<vehicle_global_position_s> frsky_subscription_data_s::vehicle_global_position_sub {ORB_ID(vehicle_global_position)}
Definition at line 71 of file frsky_data.cpp.
Referenced by frsky_send_frame2(), and frsky_update_topics().
vehicle_gps_position_sub
uORB::SubscriptionData<vehicle_gps_position_s> frsky_subscription_data_s::vehicle_gps_position_sub {ORB_ID(vehicle_gps_position)}
Definition at line 72 of file frsky_data.cpp.
Referenced by frsky_send_frame1(), frsky_send_frame2(), frsky_send_frame3(), and frsky_update_topics().
vehicle_status_sub
uORB::SubscriptionData<vehicle_status_s> frsky_subscription_data_s::vehicle_status_sub {ORB_ID(vehicle_status)}
Definition at line 73 of file frsky_data.cpp.
Referenced by frsky_send_frame1(), and frsky_update_topics().
The documentation for this struct was generated from the following file:
src/drivers/telemetry/frsky_telemetry/frsky_data.cpp