PX4 Firmware: src/platforms/qurt/stubs/stubs_posix.c File Reference
stubs_posix.c File Reference
#include <semaphore.h>
#include <unistd.h>
#include <pthread.h>
#include <signal.h>
#include <time.h>
Functions
int sem_init (sem_t *sem, int pshared, unsigned int value)
int sem_wait (sem_t *sem)
int sem_destroy (sem_t *sem)
int sem_post (sem_t *sem)
int sem_getvalue (sem_t *sem, int *sval)
int usleep (useconds_t usec)
pthread_t pthread_self (void)
int pthread_kill (pthread_t thread, int sig)
void pthread_exit (void *retval)
int pthread_join (pthread_t thread, void **retval)
int pthread_cancel (pthread_t thread)
int pthread_attr_init (pthread_attr_t *attr)
int pthread_attr_setstacksize (pthread_attr_t *attr, size_t stacksize)
int pthread_attr_getstacksize (const pthread_attr_t *attr, size_t *stacksize)
int pthread_attr_setschedparam (pthread_attr_t *attr, const struct sched_param *param)
int pthread_create (pthread_t *thread, const pthread_attr_t *attr, void *(*start_routine)(void *), void *arg)
int pthread_attr_getschedparam (const pthread_attr_t *attr, struct sched_param *param)
int pthread_attr_destroy (pthread_attr_t *attr)
int clock_gettime (clockid_t clk_id, struct timespec *tp)
int pthread_mutex_lock (pthread_mutex_t *mutex)
int pthread_mutex_unlock (pthread_mutex_t *mutex)
int pthread_cond_signal (pthread_cond_t *cond)
int pthread_mutex_destroy (pthread_mutex_t *mutex)
int pthread_mutex_init (pthread_mutex_t *mutex, const pthread_mutexattr_t *attr)
int pthread_cond_wait (pthread_cond_t *cond, pthread_mutex_t *mutex)
int pthread_cond_timedwait (pthread_cond_t *cond, pthread_mutex_t *mutex, const struct timespec *abstime)
int pthread_cond_init (pthread_cond_t *cond, const pthread_condattr_t *attr)
int pthread_mutexattr_init (pthread_mutexattr_t *attr)
int pthread_mutexattr_destroy (pthread_mutexattr_t *attr)
int pthread_mutexattr_settype (pthread_mutexattr_t *attr, int type)
int pthread_condattr_init (pthread_condattr_t *attr)
int fsync (int fd)
Function Documentation
int clock_gettime (clockid_t clk_id, struct timespec * tp)
Definition at line 96 of file stubs_posix.c.
Referenced by board_button_irq(), calc_timer_diff_to_dsp_us(), and VirtualCanDriver::Event::waitFor().
int fsync (int fd)
Definition at line 156 of file stubs_posix.c.
Referenced by _file_clear(), _file_initialize(), _file_restart(), _file_write(), check_user_abort(), dumpfile_main(), GPS::injectData(), param_export(), position_estimator_inav_main(), px4::logger::LogWriterFile::run(), test_corruption(), test_file(), test_mount(), and time_fsync().
int pthread_attr_destroy (pthread_attr_t * attr)
Definition at line 91 of file stubs_posix.c.
Referenced by Simulator::pollForMAVLinkMessages(), MavlinkReceiver::receive_start(), Commander::run(), uORB::KraitFastRpcChannel::Start(), and px4::logger::LogWriterFile::thread_start().
int pthread_attr_getschedparam (const pthread_attr_t * attr, struct sched_param * param)
Definition at line 86 of file stubs_posix.c.
Referenced by Simulator::pollForMAVLinkMessages(), MavlinkReceiver::receive_start(), Commander::run(), UavcanServers::start(), and uORB::KraitFastRpcChannel::Start().
int pthread_attr_getstacksize (const pthread_attr_t * attr, size_t * stacksize)
Definition at line 72 of file stubs_posix.c.
int pthread_attr_init (pthread_attr_t * attr)
Definition at line 62 of file stubs_posix.c.
Referenced by Simulator::pollForMAVLinkMessages(), MavlinkReceiver::receive_start(), Commander::run(), UavcanServers::start(), uORB::KraitFastRpcChannel::Start(), and px4::logger::LogWriterFile::thread_start().
int pthread_attr_setschedparam (pthread_attr_t * attr, const struct sched_param * param)
Definition at line 77 of file stubs_posix.c.
Referenced by Simulator::pollForMAVLinkMessages(), MavlinkReceiver::receive_start(), Commander::run(), UavcanServers::start(), uORB::KraitFastRpcChannel::Start(), and px4::logger::LogWriterFile::thread_start().
int pthread_attr_setstacksize (pthread_attr_t * attr, size_t stacksize)
Definition at line 67 of file stubs_posix.c.
Referenced by Simulator::pollForMAVLinkMessages(), MavlinkReceiver::receive_start(), Commander::run(), uORB::KraitFastRpcChannel::Start(), and px4::logger::LogWriterFile::thread_start().
int pthread_cancel (pthread_t thread)
Definition at line 58 of file stubs_posix.c.
int pthread_cond_init (pthread_cond_t * cond, const pthread_condattr_t * attr)
Definition at line 134 of file stubs_posix.c.
Referenced by px4::logger::LogWriterFile::LogWriterFile().
int pthread_cond_signal (pthread_cond_t * cond)
Definition at line 111 of file stubs_posix.c.
int pthread_cond_timedwait (pthread_cond_t * cond, pthread_mutex_t * mutex, const struct timespec * abstime)
Definition at line 129 of file stubs_posix.c.
int pthread_cond_wait (pthread_cond_t * cond, pthread_mutex_t * mutex)
Definition at line 124 of file stubs_posix.c.
Referenced by px4::logger::LogWriterFile::run().
int pthread_condattr_init (pthread_condattr_t * attr)
Definition at line 151 of file stubs_posix.c.
int pthread_create (pthread_t * thread, const pthread_attr_t * attr, void *(*)(void *) start_routine, void * arg)
Definition at line 82 of file stubs_posix.c.
Referenced by Simulator::pollForMAVLinkMessages(), MavlinkReceiver::receive_start(), Commander::run(), UavcanServers::start(), uORB::KraitFastRpcChannel::Start(), test_uart_console(), and px4::logger::LogWriterFile::thread_start().
void pthread_exit (void * retval)
Definition at line 49 of file stubs_posix.c.
int pthread_join (pthread_t thread, void ** retval)
Definition at line 53 of file stubs_posix.c.
Referenced by Commander::run(), UavcanServers::stop(), uORB::KraitFastRpcChannel::Stop(), Mavlink::task_main(), test_uart_console(), and px4::logger::LogWriterFile::thread_stop().
int pthread_kill (pthread_t thread, int sig)
Definition at line 44 of file stubs_posix.c.
int pthread_mutex_destroy (pthread_mutex_t * mutex)
Definition at line 115 of file stubs_posix.c.
Referenced by Lock::deinit(), Mavlink::task_main(), BBBlueADC::~BBBlueADC(), px4::logger::LogWriterFile::~LogWriterFile(), NavioADC::~NavioADC(), OcpocADC::~OcpocADC(), and UavcanNode::~UavcanNode().
int pthread_mutex_init (pthread_mutex_t * mutex, const pthread_mutexattr_t * attr)
Definition at line 119 of file stubs_posix.c.
Referenced by AEROFC_ADC::AEROFC_ADC(), BBBlueADC::BBBlueADC(), Lock::init(), px4::logger::LogWriterFile::LogWriterFile(), IridiumSBD::main_loop(), NavioADC::NavioADC(), OcpocADC::OcpocADC(), Mavlink::task_main(), UavcanEsc::UavcanEsc(), and UavcanNode::UavcanNode().
int pthread_mutex_lock (pthread_mutex_t * mutex)
Definition at line 101 of file stubs_posix.c.
Referenced by OcpocADC::_measure(), BBBlueADC::_measure(), NavioADC::_measure(), Mavlink::begin_send(), AEROFC_ADC::cycle(), get_vdev(), getDev(), RestartRequestHandler::handleRestartRequest(), UavcanNode::hardpoint_controller_set(), Lock::Lock(), px4::logger::LogWriterFile::lock(), Mavlink::lockMessageBufferMutex(), Mavlink::pass_message(), perf_alloc(), perf_alloc_once(), perf_free(), perf_iterate_all(), perf_print_all(), perf_reset_all(), UavcanEsc::print_info(), UavcanNode::print_info(), px4_close(), px4_open(), px4_register_shutdown_hook(), px4_show_devices(), px4_show_files(), px4_show_topics(), px4_shutdown_lock(), px4_shutdown_unlock(), px4_unregister_shutdown_hook(), AEROFC_ADC::read(), IridiumSBD::read(), IridiumSBD::read_rx_buf(), register_driver(), UavcanEsc::run(), px4::logger::LogWriterFile::run(), UavcanNode::run(), UavcanNode::shrink(), shutdown_worker(), IridiumSBD::start_sbd_session(), Mavlink::task_main(), unregister_driver(), IridiumSBD::write(), and IridiumSBD::write_tx_buf().
int pthread_mutex_unlock (pthread_mutex_t * mutex)
Definition at line 106 of file stubs_posix.c.
Referenced by OcpocADC::_measure(), BBBlueADC::_measure(), NavioADC::_measure(), AEROFC_ADC::cycle(), OcpocADC::devRead(), BBBlueADC::devRead(), NavioADC::devRead(), get_vdev(), getDev(), RestartRequestHandler::handleRestartRequest(), UavcanNode::hardpoint_controller_set(), Mavlink::pass_message(), perf_alloc(), perf_alloc_once(), perf_free(), perf_iterate_all(), perf_print_all(), perf_reset_all(), UavcanEsc::print_info(), UavcanNode::print_info(), px4_close(), px4_open(), px4_register_shutdown_hook(), px4_show_devices(), px4_show_files(), px4_show_topics(), px4_shutdown_lock(), px4_shutdown_unlock(), px4_unregister_shutdown_hook(), AEROFC_ADC::read(), IridiumSBD::read(), IridiumSBD::read_rx_buf(), register_driver(), UavcanEsc::run(), px4::logger::LogWriterFile::run(), UavcanNode::run(), IridiumSBD::sbdsession_loop(), Mavlink::send_packet(), UavcanNode::shrink(), shutdown_worker(), Mavlink::task_main(), px4::logger::LogWriterFile::unlock(), Mavlink::unlockMessageBufferMutex(), unregister_driver(), IridiumSBD::write(), IridiumSBD::write_tx_buf(), and Lock::~Lock().
int pthread_mutexattr_destroy (pthread_mutexattr_t * attr)
Definition at line 142 of file stubs_posix.c.
int pthread_mutexattr_init (pthread_mutexattr_t * attr)
Definition at line 138 of file stubs_posix.c.
int pthread_mutexattr_settype (pthread_mutexattr_t * attr, int type)
Definition at line 146 of file stubs_posix.c.
pthread_t pthread_self (void)
Definition at line 37 of file stubs_posix.c.
Referenced by Simulator::pollForMAVLinkMessages(), px4_open(), px4_poll(), and Simulator::send().
int sem_destroy (sem_t * sem)
Definition at line 17 of file stubs_posix.c.
Referenced by protocol_splitter_main(), uORB::FastRpcChannel::Mutex::~Mutex(), and uORB::FastRpcChannel::Semaphore::~Semaphore().
int sem_getvalue (sem_t * sem, int * sval)
Definition at line 27 of file stubs_posix.c.
int sem_init (sem_t * sem, int pshared, unsigned int value)
Definition at line 7 of file stubs_posix.c.
Referenced by uORB::FastRpcChannel::Mutex::Mutex(), protocol_splitter_main(), and uORB::FastRpcChannel::Semaphore::Semaphore().
int sem_post (sem_t * sem)
Definition at line 22 of file stubs_posix.c.
Referenced by uORB::FastRpcChannel::Semaphore::post(), DevCommon::unlock(), and uORB::FastRpcChannel::Mutex::unlock().
int sem_wait (sem_t * sem)
Definition at line 12 of file stubs_posix.c.
Referenced by DevCommon::lock(), uORB::FastRpcChannel::Mutex::lock(), and uORB::FastRpcChannel::Semaphore::wait().
int usleep (useconds_t usec)
Definition at line 32 of file stubs_posix.c.
Referenced by _auth_method_arm_req_check(), HysteresisTest::_change_after_multiple_sets(), HysteresisTest::_change_after_time(), HysteresisTest::_hysteresis_changed(), linux_sbus::RcInput::_measure(), MS5611_I2C::_read_prom(), HysteresisTest::_take_change_back(), QShell::_wait_for_retval(), HysteresisTest::_zero_case(), accel(), MPU9250_mag::ak8963_read_adjustments(), uORB::DeviceNode::appears_updated(), at24c_bread(), at24c_bwrite(), at24c_eraseall(), baro(), batt_smbus_main(), bl_update_main(), BATT_SMBUS::block_write(), board_app_initialize(), board_peripheral_reset(), board_spi_reset(), OREOLED::bootloader_app_reset(), OREOLED::bootloader_boot(), OREOLED::bootloader_flash(), LIS3MDL::calibrate(), calibrate_from_orientation(), Mavlink::check_radio_config(), commander_low_prio_loop(), commander_main(), GPSDriverMTK::configure(), GPSDriverUBX::configure(), Mavlink::configure_stream_threadsafe(), RCInput::cycle(), Mavlink::destroy_all_instances(), detect_orientation(), do_accel_calibration(), do_airspeed_calibration(), do_esc_calibration(), do_gyro_calibration(), do_mag_calibration(), VCDevExample::do_poll(), do_trim_calibration(), esc_calib_main(), frsky_telemetry_main(), frsky_telemetry_thread_main(), UavcanNode::get_set_param(), gnd_att_control_main(), gnd_pos_control_main(), gpio_led_main(), gyro(), Simulator::handle_message(), RestartRequestHandler::handleRestartRequest(), px4::Replay::handleTopicDelay(), px4::ReplayEkf2::handleTopicUpdate(), hott_sensors_thread_main(), hrt_work_process(), linux_pwm_out::PCA9685::init(), HC_SR04::init(), BMP280::init(), MB12XX::init(), SRF02::init(), TAP_ESC::init(), MPL3115A2::init(), leddar_one::init(), BMA180::init(), MS5611::init(), PX4IO::init(), MK::init(), VideoDevice::init_format(), MS5525::init_ms5525(), SDP3X::init_sdp3x(), GPS::instantiate(), PX4IO::ioctl(), landing_target_estimator::landing_target_estimator_thread_main(), uORBTest::UnitTest::latency_test(), linux_sbus_main(), listener(), load(), mag(), mag_calibrate_all(), mag_calibration_worker(), HRTTest::main(), QShell::main(), IridiumSBD::main_loop(), Mavlink::mavlink_open_uart(), md25Sine(), md25Test(), HC_SR04::measure(), PX4IO::mixer_send(), MixerTest::mixerTest(), motor_ramp_thread_main(), motor_test_main(), navio_sysfs_rc_in::navio_sysfs_rc_in_main(), nshterm_main(), oreoled_main(), param_import_internal(), MPU9250_mag::passthrough_read(), MPU9250_mag::passthrough_write(), pca8574_main(), pca9685_main(), MuorbTestExample::PingPongTest(), MK::play_beep(), Simulator::pollForMAVLinkMessages(), GPS::pollOrRead(), prepare(), PX4IO::print_debug(), GPSSIM::print_info(), LidarLiteI2C::print_registers(), AEROFC_ADC::probe(), uORBTest::UnitTest::pub_test_multi2_main(), uORBTest::UnitTest::pub_test_queue_main(), pwm_main(), pwmin_test(), px4_poll(), rc_calibration_check(), AirspeedSim::read(), LidarLiteI2C::read(), TFMINI::read(), SF0X::read(), HC_SR04::read(), SF1XX::read(), BMP280::read(), SRF02::read(), MB12XX::read(), TERARANGER::read(), MPL3115A2::read(), LIS3MDL::read(), MS5611::read(), HMC5883::read(), IST8310::read(), BMM150::read(), LPS25H::read(), RoboClaw::readEncoder(), reboot_main(), UBX_SIM::receive(), GPSDriverMTK::receive(), GPSSIM::receive(), MavlinkReceiver::receive_thread(), MPL3115A2_I2C::reset(), BMI055_gyro::reset(), LPS25H::reset(), MPU6000::reset(), MPU9250::reset(), MPU9250::reset_mpu(), UavcanNode::reset_node(), LidarLiteI2C::reset_sensor(), RGBLED::RGBLED(), roboclawTest(), rpi_rc_in_main(), Commander::run(), MulticopterAttitudeControl::run(), Navigator::run(), Ekf2::run(), GPS::run(), Sensors::run(), run_led_test1(), UavcanNode::save_params(), LSM303AGR::self_test(), send_data(), send_poll(), PMW3901::sensorInit(), PX4IO::set_update_rate(), MD25::setDeviceAddress(), linux_pwm_out::PCA9685::setPWMFreq(), PCA9685::setPWMFreq(), uORB::DeviceMaster::showTop(), simulator_main(), px4::Rate::sleep(), px4::NodeHandle::spin(), Mavlink::start(), IridiumSBD::start(), px4flow::start(), syslink::start(), bebop_flow::stop(), spektrum_rc::stop(), linux_pwm_out::stop(), snapdragon_pwm::stop(), df_bebop_bus_wrapper::stop(), task_main(), spektrum_rc::task_main(), bebop_flow::task_main(), TemperatureCalibration::task_main(), AttitudeEstimatorQ::task_main(), uart_esc::task_main(), linux_pwm_out::task_main(), ulanding::Radar::task_main(), snapdragon_pwm::task_main(), MK::task_main(), VtolAttitudeControl::task_main(), df_bebop_bus_wrapper::task_main(), Mavlink::task_main(), IRLOCK::test(), test_adc(), test_hott_telemetry(), test_hrt(), test_led(), test_mount(), uORBTest::UnitTest::test_multi2(), test_ppm_loopback(), test_rc(), test_servo(), test_sleep(), test_time(), test_uart_break(), top_main(), tune_control_main(), PX4IO_Uploader::upload(), MuorbTestExample::uSleepTest(), vmount_main(), vmount_thread_main(), px4::logger::LogWriterFile::write_message(), AttitudeEstimatorQ::~AttitudeEstimatorQ(), CameraFeedback::~CameraFeedback(), GPS::~GPS(), GPSSIM::~GPSSIM(), GroundRoverAttitudeControl::~GroundRoverAttitudeControl(), GroundRoverPositionControl::~GroundRoverPositionControl(), Mavlink::~Mavlink(), MK::~MK(), MulticopterPositionControl::~MulticopterPositionControl(), PX4IO::~PX4IO(), ulanding::Radar::~Radar(), RGBLED_PWM::~RGBLED_PWM(), ToneAlarm::~ToneAlarm(), UavcanEsc::~UavcanEsc(), UavcanNode::~UavcanNode(), and VtolAttitudeControl::~VtolAttitudeControl().