PX4 Firmware: FixedwingAttitudeControl Class Reference
FixedwingAttitudeControl Class Reference final
#include <FixedwingAttitudeControl.hpp>
Public Member Functions
FixedwingAttitudeControl ()
~FixedwingAttitudeControl () override
void run () override
int print_status () override
Static Public Member Functions
static int task_spawn (int argc, char *argv[])
static FixedwingAttitudeControl * instantiate (int argc, char *argv[])
static int custom_command (int argc, char *argv[])
static int print_usage (const char *reason=nullptr)
Private Member Functions
void control_flaps (const float dt)
int parameters_update ()
Update our local parameter cache.
void vehicle_control_mode_poll ()
void vehicle_manual_poll ()
void vehicle_setpoint_poll ()
void global_pos_poll ()
void vehicle_status_poll ()
void vehicle_land_detected_poll ()
Private Attributes
int _att_sub {-1}
vehicle attitude
int _att_sp_sub {-1}
vehicle attitude setpoint
int _battery_status_sub {-1}
battery status subscription
int _global_pos_sub {-1}
global position subscription
int _manual_sub {-1}
notification of manual control updates
int _params_sub {-1}
notification of parameter updates
int _vcontrol_mode_sub {-1}
vehicle status subscription
int _vehicle_land_detected_sub {-1}
vehicle land detected subscription
int _vehicle_status_sub {-1}
vehicle status subscription
orb_advert_t _rate_sp_pub {nullptr}
rate setpoint publication
orb_advert_t _attitude_sp_pub {nullptr}
attitude setpoint point
orb_advert_t _actuators_0_pub {nullptr}
actuator control group 0 setpoint
orb_advert_t _actuators_2_pub {nullptr}
actuator control group 1 setpoint (Airframe)
orb_advert_t _rate_ctrl_status_pub {nullptr}
rate controller status publication
orb_id_t _rates_sp_id {nullptr}
orb_id_t _actuators_id {nullptr}
orb_id_t _attitude_setpoint_id {nullptr}
actuator_controls_s _actuators {}
actuator control inputs
actuator_controls_s _actuators_airframe {}
actuator control inputs
manual_control_setpoint_s _manual {}
r/c channel data
vehicle_attitude_s _att {}
vehicle attitude setpoint
vehicle_attitude_setpoint_s _att_sp {}
vehicle attitude setpoint
vehicle_control_mode_s _vcontrol_mode {}
vehicle control mode
vehicle_global_position_s _global_pos {}
global position
vehicle_rates_setpoint_s _rates_sp {}
vehicle_status_s _vehicle_status {}
vehicle status
Subscription< airspeed_s > _airspeed_sub
perf_counter_t _loop_perf
loop performance counter
perf_counter_t _nonfinite_input_perf
performance counter for non finite input
perf_counter_t _nonfinite_output_perf
performance counter for non finite output
float _flaps_applied {0.0f}
float _flaperons_applied {0.0f}
bool _landed {true}
float _battery_scale {1.0f}
bool _flag_control_attitude_enabled_last {false}
struct {
float p_tc
float p_p
float p_i
float p_ff
float p_rmax_pos
float p_rmax_neg
float p_integrator_max
float r_tc
float r_p
float r_i
float r_ff
float r_integrator_max
float r_rmax
float y_p
float y_i
float y_ff
float y_integrator_max
float roll_to_yaw_ff
float y_rmax
bool w_en
float w_p
float w_i
float w_ff
float w_integrator_max
float w_rmax
float airspeed_min
float airspeed_trim
float airspeed_max
float trim_roll
float trim_pitch
float trim_yaw
float dtrim_roll_vmin
float dtrim_pitch_vmin
float dtrim_yaw_vmin
float dtrim_roll_vmax
float dtrim_pitch_vmax
float dtrim_yaw_vmax
float dtrim_roll_flaps
float dtrim_pitch_flaps
float rollsp_offset_deg
Roll Setpoint Offset in deg.
float pitchsp_offset_deg
Pitch Setpoint Offset in deg.
float rollsp_offset_rad
Roll Setpoint Offset in rad.
float pitchsp_offset_rad
Pitch Setpoint Offset in rad.
float man_roll_max
Max Roll in rad.
float man_pitch_max
Max Pitch in rad.
float man_roll_scale
scale factor applied to roll actuator control in pure manual mode
float man_pitch_scale
scale factor applied to pitch actuator control in pure manual mode
float man_yaw_scale
scale factor applied to yaw actuator control in pure manual mode
float acro_max_x_rate_rad
float acro_max_y_rate_rad
float acro_max_z_rate_rad
float flaps_scale
Scale factor for flaps.
float flaps_takeoff_scale
Scale factor for flaps on take-off.
float flaperon_scale
Scale factor for flaperons.
float rattitude_thres
int32_t vtol_type
VTOL type: 0 = tailsitter, 1 = tiltrotor.
int32_t bat_scale_en
Battery scaling enabled.
bool airspeed_disabled
} _parameters
local copies of interesting parameters
struct {
param_t p_tc
param_t p_p
param_t p_i
param_t p_ff
param_t p_rmax_pos
param_t p_rmax_neg
param_t p_integrator_max
param_t r_tc
param_t r_p
param_t r_i
param_t r_ff
param_t r_integrator_max
param_t r_rmax
param_t y_p
param_t y_i
param_t y_ff
param_t y_integrator_max
param_t roll_to_yaw_ff
param_t y_rmax
param_t w_en
param_t w_p
param_t w_i
param_t w_ff
param_t w_integrator_max
param_t w_rmax
param_t airspeed_min
param_t airspeed_trim
param_t airspeed_max
param_t trim_roll
param_t trim_pitch
param_t trim_yaw
param_t dtrim_roll_vmin
param_t dtrim_pitch_vmin
param_t dtrim_yaw_vmin
param_t dtrim_roll_vmax
param_t dtrim_pitch_vmax
param_t dtrim_yaw_vmax
param_t dtrim_roll_flaps
param_t dtrim_pitch_flaps
param_t rollsp_offset_deg
param_t pitchsp_offset_deg
param_t man_roll_max
param_t man_pitch_max
param_t man_roll_scale
param_t man_pitch_scale
param_t man_yaw_scale
param_t acro_max_x_rate
param_t acro_max_y_rate
param_t acro_max_z_rate
param_t flaps_scale
param_t flaps_takeoff_scale
param_t flaperon_scale
param_t rattitude_thres
param_t vtol_type
param_t bat_scale_en
param_t airspeed_mode
} _parameter_handles
handles for interesting parameters
ECL_RollController _roll_ctrl
ECL_PitchController _pitch_ctrl
ECL_YawController _yaw_ctrl
ECL_WheelController _wheel_ctrl
Detailed Description
Definition at line 70 of file FixedwingAttitudeControl.hpp.
Constructor & Destructor Documentation
FixedwingAttitudeControl::FixedwingAttitudeControl ()
Definition at line 43 of file FixedwingAttitudeControl.cpp.
References _parameter_handles, _parameters, param_find(), and parameters_update().
Referenced by instantiate().
FixedwingAttitudeControl::~FixedwingAttitudeControl () override
Definition at line 124 of file FixedwingAttitudeControl.cpp.
References _loop_perf, _nonfinite_input_perf, _nonfinite_output_perf, and perf_free().
Member Function Documentation
void FixedwingAttitudeControl::control_flaps (const float dt) private
Definition at line 869 of file FixedwingAttitudeControl.cpp.
References _att_sp, _flaperons_applied, _flaps_applied, _manual, _parameters, _vcontrol_mode, vehicle_attitude_setpoint_s::apply_flaps, manual_control_setpoint_s::aux2, f(), vehicle_control_mode_s::flag_control_auto_enabled, vehicle_control_mode_s::flag_control_manual_enabled, and manual_control_setpoint_s::flaps.
Referenced by run().
int FixedwingAttitudeControl::custom_command (int argc, char * argv[]) static
See also
ModuleBase
Definition at line 947 of file FixedwingAttitudeControl.cpp.
References print_usage().
void FixedwingAttitudeControl::global_pos_poll () private
Definition at line 350 of file FixedwingAttitudeControl.cpp.
References _global_pos, _global_pos_sub, orb_check(), orb_copy(), and ORB_ID.
Referenced by run().
FixedwingAttitudeControl * FixedwingAttitudeControl::instantiate (int argc, char * argv[]) static
See also
ModuleBase
Definition at line 925 of file FixedwingAttitudeControl.cpp.
References FixedwingAttitudeControl().
int FixedwingAttitudeControl::parameters_update () private
Update our local parameter cache.
Definition at line 132 of file FixedwingAttitudeControl.cpp.
References _parameter_handles, _parameters, _pitch_ctrl, _roll_ctrl, _vehicle_status, _wheel_ctrl, _yaw_ctrl, vehicle_status_s::is_vtol, param_get(), PX4_OK, math::radians(), ECL_Controller::set_integrator_max(), ECL_Controller::set_k_ff(), ECL_Controller::set_k_i(), ECL_Controller::set_k_p(), ECL_Controller::set_max_rate(), and ECL_Controller::set_time_constant().
Referenced by FixedwingAttitudeControl(), run(), and vehicle_status_poll().
int FixedwingAttitudeControl::print_status () override
See also
ModuleBase::print_status()
Definition at line 974 of file FixedwingAttitudeControl.cpp.
References PX4_INFO.
int FixedwingAttitudeControl::print_usage (const char * reason = nullptr) static
See also
ModuleBase
Definition at line 952 of file FixedwingAttitudeControl.cpp.
References PRINT_MODULE_DESCRIPTION(), PRINT_MODULE_USAGE_COMMAND, PRINT_MODULE_USAGE_DEFAULT_COMMANDS, PRINT_MODULE_USAGE_NAME(), and PX4_WARN.
Referenced by custom_command().
void FixedwingAttitudeControl::run () override
See also
ModuleBase::run()
Definition at line 407 of file FixedwingAttitudeControl.cpp.
References _actuators, _actuators_0_pub, _actuators_2_pub, _actuators_airframe, _actuators_id, _airspeed_sub, _att, _att_sp, _att_sp_sub, _att_sub, _battery_scale, _battery_status_sub, _flag_control_attitude_enabled_last, _flaperons_applied, _flaps_applied, _global_pos, _global_pos_sub, _landed, _loop_perf, _manual, _manual_sub, _nonfinite_input_perf, _nonfinite_output_perf, _parameters, _params_sub, _pitch_ctrl, _rate_ctrl_status_pub, _rate_sp_pub, _rates_sp, _rates_sp_id, _roll_ctrl, _vcontrol_mode, _vcontrol_mode_sub, _vehicle_land_detected_sub, _vehicle_status, _vehicle_status_sub, _wheel_ctrl, _yaw_ctrl, rate_ctrl_status_s::additional_integ1, ECL_ControlData::airspeed, ECL_ControlData::airspeed_max, ECL_ControlData::airspeed_min, manual_control_setpoint_s::aux1, manual_control_setpoint_s::aux3, ECL_ControlData::body_x_rate, ECL_ControlData::body_y_rate, ECL_ControlData::body_z_rate, math::constrain(), actuator_controls_s::control, ECL_YawController::control_attitude(), ECL_RollController::control_attitude(), ECL_WheelController::control_attitude(), ECL_PitchController::control_attitude(), ECL_YawController::control_bodyrate(), ECL_RollController::control_bodyrate(), ECL_WheelController::control_bodyrate(), ECL_PitchController::control_bodyrate(), ECL_YawController::control_euler_rate(), ECL_RollController::control_euler_rate(), ECL_PitchController::control_euler_rate(), control_flaps(), vehicle_status_s::engine_failure, f(), vehicle_control_mode_s::flag_control_attitude_enabled, vehicle_control_mode_s::flag_control_auto_enabled, vehicle_control_mode_s::flag_control_manual_enabled, vehicle_control_mode_s::flag_control_rates_enabled, vehicle_control_mode_s::flag_control_termination_enabled, vehicle_attitude_setpoint_s::fw_control_yaw, uORB::Subscription< T >::get(), ECL_Controller::get_desired_bodyrate(), ECL_Controller::get_desired_rate(), ECL_Controller::get_integrator(), global_pos_poll(), math::gradual(), ECL_ControlData::groundspeed, ECL_ControlData::groundspeed_scaler, hrt_absolute_time(), hrt_elapsed_time(), vehicle_status_s::in_transition_mode, airspeed_s::indicated_airspeed_m_s, instance, vehicle_status_s::is_rotary_wing, vehicle_status_s::is_vtol, ECL_ControlData::lock_integrator, math::max(), orb_advertise(), orb_check(), orb_copy(), ORB_ID, ORB_PRIO_DEFAULT, orb_publish(), orb_publish_auto(), orb_subscribe(), parameters_update(), perf_begin(), perf_count(), perf_end(), matrix::Euler< Type >::phi(), ECL_ControlData::pitch, vehicle_rates_setpoint_s::pitch, vehicle_attitude_setpoint_s::pitch_body, ECL_ControlData::pitch_rate_setpoint, vehicle_attitude_setpoint_s::pitch_reset_integral, ECL_ControlData::pitch_setpoint, rate_ctrl_status_s::pitchspeed, vehicle_attitude_s::pitchspeed, rate_ctrl_status_s::pitchspeed_integ, matrix::Euler< Type >::psi(), PX4_OK, px4_poll(), PX4_WARN, vehicle_attitude_s::q, manual_control_setpoint_s::r, math::radians(), ECL_Controller::reset_integrator(), ECL_ControlData::roll, vehicle_rates_setpoint_s::roll, vehicle_attitude_setpoint_s::roll_body, ECL_ControlData::roll_rate_setpoint, vehicle_attitude_setpoint_s::roll_reset_integral, ECL_ControlData::roll_setpoint, vehicle_attitude_s::rollspeed, rate_ctrl_status_s::rollspeed, rate_ctrl_status_s::rollspeed_integ, battery_status_s::scale, ECL_ControlData::scaler, ECL_PitchController::set_bodyrate_setpoint(), ECL_Controller::set_bodyrate_setpoint(), ECL_Controller::set_max_rate(), ECL_PitchController::set_max_rate_neg(), ECL_PitchController::set_max_rate_pos(), TAILSITTER, matrix::Euler< Type >::theta(), vehicle_rates_setpoint_s::thrust, vehicle_attitude_setpoint_s::thrust, airspeed_s::timestamp, rate_ctrl_status_s::timestamp, vehicle_attitude_s::timestamp, vehicle_rates_setpoint_s::timestamp, actuator_controls_s::timestamp, actuator_controls_s::timestamp_sample, trim_pitch, trim_roll, trim_yaw, uORB::Subscription< T >::update(), vehicle_control_mode_poll(), vehicle_land_detected_poll(), vehicle_manual_poll(), vehicle_setpoint_poll(), vehicle_status_poll(), vehicle_global_position_s::vel_e, vehicle_global_position_s::vel_n, ECL_ControlData::yaw, vehicle_rates_setpoint_s::yaw, vehicle_attitude_setpoint_s::yaw_body, ECL_ControlData::yaw_rate_setpoint, vehicle_attitude_setpoint_s::yaw_reset_integral, ECL_ControlData::yaw_setpoint, vehicle_attitude_s::yawspeed, rate_ctrl_status_s::yawspeed, and rate_ctrl_status_s::yawspeed_integ.
int FixedwingAttitudeControl::task_spawn (int argc, char * argv[]) static
See also
ModuleBase
Definition at line 930 of file FixedwingAttitudeControl.cpp.
References px4_task_spawn_cmd(), SCHED_DEFAULT, and SCHED_PRIORITY_ATTITUDE_CONTROL.
void FixedwingAttitudeControl::vehicle_control_mode_poll () private
Definition at line 250 of file FixedwingAttitudeControl.cpp.
References _vcontrol_mode, _vcontrol_mode_sub, orb_check(), orb_copy(), and ORB_ID.
Referenced by run().
void FixedwingAttitudeControl::vehicle_land_detected_poll () private
Definition at line 392 of file FixedwingAttitudeControl.cpp.
References _landed, _vehicle_land_detected_sub, orb_check(), orb_copy(), ORB_ID, and PX4_OK.
Referenced by run().
void FixedwingAttitudeControl::vehicle_manual_poll () private
Definition at line 264 of file FixedwingAttitudeControl.cpp.
References _actuators, _att_sp, _attitude_setpoint_id, _attitude_sp_pub, _manual, _manual_sub, _parameters, _rate_sp_pub, _rates_sp, _rates_sp_id, _vcontrol_mode, math::constrain(), actuator_controls_s::control, vehicle_control_mode_s::flag_control_attitude_enabled, vehicle_control_mode_s::flag_control_climb_rate_enabled, vehicle_control_mode_s::flag_control_manual_enabled, vehicle_control_mode_s::flag_control_offboard_enabled, vehicle_control_mode_s::flag_control_rates_enabled, vehicle_control_mode_s::flag_control_rattitude_enabled, hrt_absolute_time(), orb_advertise(), orb_copy(), ORB_ID, orb_publish(), vehicle_rates_setpoint_s::pitch, vehicle_attitude_setpoint_s::pitch_body, PX4_OK, vehicle_attitude_setpoint_s::q_d, vehicle_attitude_setpoint_s::q_d_valid, manual_control_setpoint_s::r, vehicle_rates_setpoint_s::roll, vehicle_attitude_setpoint_s::roll_body, vehicle_rates_setpoint_s::thrust, vehicle_attitude_setpoint_s::thrust, vehicle_rates_setpoint_s::timestamp, vehicle_attitude_setpoint_s::timestamp, manual_control_setpoint_s::x, manual_control_setpoint_s::y, vehicle_rates_setpoint_s::yaw, vehicle_attitude_setpoint_s::yaw_body, and manual_control_setpoint_s::z.
Referenced by run().
void FixedwingAttitudeControl::vehicle_setpoint_poll () private
Definition at line 338 of file FixedwingAttitudeControl.cpp.
References _att_sp, _att_sp_sub, orb_check(), orb_copy(), and ORB_ID.
Referenced by run().
void FixedwingAttitudeControl::vehicle_status_poll () private
Definition at line 362 of file FixedwingAttitudeControl.cpp.
References _actuators_id, _attitude_setpoint_id, _parameter_handles, _rates_sp_id, _vehicle_status, _vehicle_status_sub, vehicle_status_s::is_vtol, orb_check(), orb_copy(), ORB_ID, param_find(), and parameters_update().
Referenced by run().
Member Data Documentation
actuator_controls_s FixedwingAttitudeControl::_actuators {} private
actuator control inputs
Definition at line 116 of file FixedwingAttitudeControl.hpp.
Referenced by run(), and vehicle_manual_poll().
orb_advert_t FixedwingAttitudeControl::_actuators_0_pub {nullptr} private
actuator control group 0 setpoint
Definition at line 108 of file FixedwingAttitudeControl.hpp.
Referenced by run().
orb_advert_t FixedwingAttitudeControl::_actuators_2_pub {nullptr} private
actuator control group 1 setpoint (Airframe)
Definition at line 109 of file FixedwingAttitudeControl.hpp.
Referenced by run().
actuator_controls_s FixedwingAttitudeControl::_actuators_airframe {} private
actuator control inputs
Definition at line 117 of file FixedwingAttitudeControl.hpp.
Referenced by run().
orb_id_t FixedwingAttitudeControl::_actuators_id {nullptr} private
Definition at line 113 of file FixedwingAttitudeControl.hpp.
Referenced by run(), and vehicle_status_poll().
Subscription<airspeed_s> FixedwingAttitudeControl::_airspeed_sub private
Definition at line 126 of file FixedwingAttitudeControl.hpp.
Referenced by run().
vehicle_attitude_s FixedwingAttitudeControl::_att {} private
vehicle attitude setpoint
Definition at line 119 of file FixedwingAttitudeControl.hpp.
Referenced by run().
vehicle_attitude_setpoint_s FixedwingAttitudeControl::_att_sp {} private
vehicle attitude setpoint
Definition at line 120 of file FixedwingAttitudeControl.hpp.
Referenced by control_flaps(), run(), vehicle_manual_poll(), and vehicle_setpoint_poll().
int FixedwingAttitudeControl::_att_sp_sub {-1} private
vehicle attitude setpoint
Definition at line 97 of file FixedwingAttitudeControl.hpp.
Referenced by run(), and vehicle_setpoint_poll().
int FixedwingAttitudeControl::_att_sub {-1} private
vehicle attitude
Definition at line 96 of file FixedwingAttitudeControl.hpp.
Referenced by run().
orb_id_t FixedwingAttitudeControl::_attitude_setpoint_id {nullptr} private
Definition at line 114 of file FixedwingAttitudeControl.hpp.
Referenced by vehicle_manual_poll(), and vehicle_status_poll().
orb_advert_t FixedwingAttitudeControl::_attitude_sp_pub {nullptr} private
attitude setpoint point
Definition at line 107 of file FixedwingAttitudeControl.hpp.
Referenced by vehicle_manual_poll().
float FixedwingAttitudeControl::_battery_scale {1.0f} private
Definition at line 137 of file FixedwingAttitudeControl.hpp.
Referenced by run().
int FixedwingAttitudeControl::_battery_status_sub {-1} private
battery status subscription
Definition at line 98 of file FixedwingAttitudeControl.hpp.
Referenced by run().
bool FixedwingAttitudeControl::_flag_control_attitude_enabled_last {false} private
Definition at line 139 of file FixedwingAttitudeControl.hpp.
Referenced by run().
float FixedwingAttitudeControl::_flaperons_applied {0.0f} private
Definition at line 133 of file FixedwingAttitudeControl.hpp.
Referenced by control_flaps(), and run().
float FixedwingAttitudeControl::_flaps_applied {0.0f} private
Definition at line 132 of file FixedwingAttitudeControl.hpp.
Referenced by control_flaps(), and run().
vehicle_global_position_s FixedwingAttitudeControl::_global_pos {} private
global position
Definition at line 122 of file FixedwingAttitudeControl.hpp.
Referenced by global_pos_poll(), and run().
int FixedwingAttitudeControl::_global_pos_sub {-1} private
global position subscription
Definition at line 99 of file FixedwingAttitudeControl.hpp.
Referenced by global_pos_poll(), and run().
bool FixedwingAttitudeControl::_landed {true} private
Definition at line 135 of file FixedwingAttitudeControl.hpp.
Referenced by run(), and vehicle_land_detected_poll().
perf_counter_t FixedwingAttitudeControl::_loop_perf private
loop performance counter
Definition at line 128 of file FixedwingAttitudeControl.hpp.
Referenced by run(), and ~FixedwingAttitudeControl().
manual_control_setpoint_s FixedwingAttitudeControl::_manual {} private
r/c channel data
Definition at line 118 of file FixedwingAttitudeControl.hpp.
Referenced by control_flaps(), run(), and vehicle_manual_poll().
int FixedwingAttitudeControl::_manual_sub {-1} private
notification of manual control updates
Definition at line 100 of file FixedwingAttitudeControl.hpp.
Referenced by run(), and vehicle_manual_poll().
perf_counter_t FixedwingAttitudeControl::_nonfinite_input_perf private
performance counter for non finite input
Definition at line 129 of file FixedwingAttitudeControl.hpp.
Referenced by run(), and ~FixedwingAttitudeControl().
perf_counter_t FixedwingAttitudeControl::_nonfinite_output_perf private
performance counter for non finite output
Definition at line 130 of file FixedwingAttitudeControl.hpp.
Referenced by run(), and ~FixedwingAttitudeControl().
struct { ... } FixedwingAttitudeControl::_parameter_handles
handles for interesting parameters
Referenced by FixedwingAttitudeControl(), parameters_update(), and vehicle_status_poll().
struct { ... } FixedwingAttitudeControl::_parameters
local copies of interesting parameters
Referenced by control_flaps(), FixedwingAttitudeControl(), parameters_update(), run(), and vehicle_manual_poll().
int FixedwingAttitudeControl::_params_sub {-1} private
notification of parameter updates
Definition at line 101 of file FixedwingAttitudeControl.hpp.
Referenced by run().
ECL_PitchController FixedwingAttitudeControl::_pitch_ctrl private
Definition at line 281 of file FixedwingAttitudeControl.hpp.
Referenced by parameters_update(), and run().
orb_advert_t FixedwingAttitudeControl::_rate_ctrl_status_pub {nullptr} private
rate controller status publication
Definition at line 110 of file FixedwingAttitudeControl.hpp.
Referenced by run().
orb_advert_t FixedwingAttitudeControl::_rate_sp_pub {nullptr} private
rate setpoint publication
Definition at line 106 of file FixedwingAttitudeControl.hpp.
Referenced by run(), and vehicle_manual_poll().
vehicle_rates_setpoint_s FixedwingAttitudeControl::_rates_sp {} private
Definition at line 123 of file FixedwingAttitudeControl.hpp.
Referenced by run(), and vehicle_manual_poll().
orb_id_t FixedwingAttitudeControl::_rates_sp_id {nullptr} private
Definition at line 112 of file FixedwingAttitudeControl.hpp.
Referenced by run(), vehicle_manual_poll(), and vehicle_status_poll().
ECL_RollController FixedwingAttitudeControl::_roll_ctrl private
Definition at line 280 of file FixedwingAttitudeControl.hpp.
Referenced by parameters_update(), and run().
vehicle_control_mode_s FixedwingAttitudeControl::_vcontrol_mode {} private
vehicle control mode
Definition at line 121 of file FixedwingAttitudeControl.hpp.
Referenced by control_flaps(), run(), vehicle_control_mode_poll(), and vehicle_manual_poll().
int FixedwingAttitudeControl::_vcontrol_mode_sub {-1} private
vehicle status subscription
Definition at line 102 of file FixedwingAttitudeControl.hpp.
Referenced by run(), and vehicle_control_mode_poll().
int FixedwingAttitudeControl::_vehicle_land_detected_sub {-1} private
vehicle land detected subscription
Definition at line 103 of file FixedwingAttitudeControl.hpp.
Referenced by run(), and vehicle_land_detected_poll().
vehicle_status_s FixedwingAttitudeControl::_vehicle_status {} private
vehicle status
Definition at line 124 of file FixedwingAttitudeControl.hpp.
Referenced by parameters_update(), run(), and vehicle_status_poll().
int FixedwingAttitudeControl::_vehicle_status_sub {-1} private
vehicle status subscription
Definition at line 104 of file FixedwingAttitudeControl.hpp.
Referenced by run(), and vehicle_status_poll().
ECL_WheelController FixedwingAttitudeControl::_wheel_ctrl private
Definition at line 283 of file FixedwingAttitudeControl.hpp.
Referenced by parameters_update(), and run().
ECL_YawController FixedwingAttitudeControl::_yaw_ctrl private
Definition at line 282 of file FixedwingAttitudeControl.hpp.
Referenced by parameters_update(), and run().
param_t FixedwingAttitudeControl::acro_max_x_rate
Definition at line 263 of file FixedwingAttitudeControl.hpp.
float FixedwingAttitudeControl::acro_max_x_rate_rad
Definition at line 194 of file FixedwingAttitudeControl.hpp.
param_t FixedwingAttitudeControl::acro_max_y_rate
Definition at line 264 of file FixedwingAttitudeControl.hpp.
float FixedwingAttitudeControl::acro_max_y_rate_rad
Definition at line 195 of file FixedwingAttitudeControl.hpp.
param_t FixedwingAttitudeControl::acro_max_z_rate
Definition at line 265 of file FixedwingAttitudeControl.hpp.
float FixedwingAttitudeControl::acro_max_z_rate_rad
Definition at line 196 of file FixedwingAttitudeControl.hpp.
bool FixedwingAttitudeControl::airspeed_disabled
Definition at line 207 of file FixedwingAttitudeControl.hpp.
float FixedwingAttitudeControl::airspeed_max
Definition at line 171 of file FixedwingAttitudeControl.hpp.
param_t FixedwingAttitudeControl::airspeed_max
Definition at line 242 of file FixedwingAttitudeControl.hpp.
float FixedwingAttitudeControl::airspeed_min
Definition at line 169 of file FixedwingAttitudeControl.hpp.
param_t FixedwingAttitudeControl::airspeed_min
Definition at line 240 of file FixedwingAttitudeControl.hpp.
param_t FixedwingAttitudeControl::airspeed_mode
Definition at line 276 of file FixedwingAttitudeControl.hpp.
float FixedwingAttitudeControl::airspeed_trim
Definition at line 170 of file FixedwingAttitudeControl.hpp.
param_t FixedwingAttitudeControl::airspeed_trim
Definition at line 241 of file FixedwingAttitudeControl.hpp.
int32_t FixedwingAttitudeControl::bat_scale_en
Battery scaling enabled.
Definition at line 206 of file FixedwingAttitudeControl.hpp.
param_t FixedwingAttitudeControl::bat_scale_en
Definition at line 275 of file FixedwingAttitudeControl.hpp.
float FixedwingAttitudeControl::dtrim_pitch_flaps
Definition at line 183 of file FixedwingAttitudeControl.hpp.
param_t FixedwingAttitudeControl::dtrim_pitch_flaps
Definition at line 254 of file FixedwingAttitudeControl.hpp.
float FixedwingAttitudeControl::dtrim_pitch_vmax
Definition at line 180 of file FixedwingAttitudeControl.hpp.
param_t FixedwingAttitudeControl::dtrim_pitch_vmax
Definition at line 251 of file FixedwingAttitudeControl.hpp.
float FixedwingAttitudeControl::dtrim_pitch_vmin
Definition at line 177 of file FixedwingAttitudeControl.hpp.
param_t FixedwingAttitudeControl::dtrim_pitch_vmin
Definition at line 248 of file FixedwingAttitudeControl.hpp.
float FixedwingAttitudeControl::dtrim_roll_flaps
Definition at line 182 of file FixedwingAttitudeControl.hpp.
param_t FixedwingAttitudeControl::dtrim_roll_flaps
Definition at line 253 of file FixedwingAttitudeControl.hpp.
float FixedwingAttitudeControl::dtrim_roll_vmax
Definition at line 179 of file FixedwingAttitudeControl.hpp.
param_t FixedwingAttitudeControl::dtrim_roll_vmax
Definition at line 250 of file FixedwingAttitudeControl.hpp.
float FixedwingAttitudeControl::dtrim_roll_vmin
Definition at line 176 of file FixedwingAttitudeControl.hpp.
param_t FixedwingAttitudeControl::dtrim_roll_vmin
Definition at line 247 of file FixedwingAttitudeControl.hpp.
float FixedwingAttitudeControl::dtrim_yaw_vmax
Definition at line 181 of file FixedwingAttitudeControl.hpp.
param_t FixedwingAttitudeControl::dtrim_yaw_vmax
Definition at line 252 of file FixedwingAttitudeControl.hpp.
float FixedwingAttitudeControl::dtrim_yaw_vmin
Definition at line 178 of file FixedwingAttitudeControl.hpp.
param_t FixedwingAttitudeControl::dtrim_yaw_vmin
Definition at line 249 of file FixedwingAttitudeControl.hpp.
float FixedwingAttitudeControl::flaperon_scale
Scale factor for flaperons.
Definition at line 200 of file FixedwingAttitudeControl.hpp.
param_t FixedwingAttitudeControl::flaperon_scale
Definition at line 269 of file FixedwingAttitudeControl.hpp.
float FixedwingAttitudeControl::flaps_scale
Scale factor for flaps.
Definition at line 198 of file FixedwingAttitudeControl.hpp.
param_t FixedwingAttitudeControl::flaps_scale
Definition at line 267 of file FixedwingAttitudeControl.hpp.
float FixedwingAttitudeControl::flaps_takeoff_scale
Scale factor for flaps on take-off.
Definition at line 199 of file FixedwingAttitudeControl.hpp.
param_t FixedwingAttitudeControl::flaps_takeoff_scale
Definition at line 268 of file FixedwingAttitudeControl.hpp.
float FixedwingAttitudeControl::man_pitch_max
Max Pitch in rad.
Definition at line 189 of file FixedwingAttitudeControl.hpp.
param_t FixedwingAttitudeControl::man_pitch_max
Definition at line 258 of file FixedwingAttitudeControl.hpp.
float FixedwingAttitudeControl::man_pitch_scale
scale factor applied to pitch actuator control in pure manual mode
Definition at line 191 of file FixedwingAttitudeControl.hpp.
param_t FixedwingAttitudeControl::man_pitch_scale
Definition at line 260 of file FixedwingAttitudeControl.hpp.
float FixedwingAttitudeControl::man_roll_max
Max Roll in rad.
Definition at line 188 of file FixedwingAttitudeControl.hpp.
param_t FixedwingAttitudeControl::man_roll_max
Definition at line 257 of file FixedwingAttitudeControl.hpp.
float FixedwingAttitudeControl::man_roll_scale
scale factor applied to roll actuator control in pure manual mode
Definition at line 190 of file FixedwingAttitudeControl.hpp.
param_t FixedwingAttitudeControl::man_roll_scale
Definition at line 259 of file FixedwingAttitudeControl.hpp.
float FixedwingAttitudeControl::man_yaw_scale
scale factor applied to yaw actuator control in pure manual mode
Definition at line 192 of file FixedwingAttitudeControl.hpp.
param_t FixedwingAttitudeControl::man_yaw_scale
Definition at line 261 of file FixedwingAttitudeControl.hpp.
float FixedwingAttitudeControl::p_ff
Definition at line 145 of file FixedwingAttitudeControl.hpp.
param_t FixedwingAttitudeControl::p_ff
Definition at line 216 of file FixedwingAttitudeControl.hpp.
float FixedwingAttitudeControl::p_i
Definition at line 144 of file FixedwingAttitudeControl.hpp.
param_t FixedwingAttitudeControl::p_i
Definition at line 215 of file FixedwingAttitudeControl.hpp.
float FixedwingAttitudeControl::p_integrator_max
Definition at line 148 of file FixedwingAttitudeControl.hpp.
param_t FixedwingAttitudeControl::p_integrator_max
Definition at line 219 of file FixedwingAttitudeControl.hpp.
float FixedwingAttitudeControl::p_p
Definition at line 143 of file FixedwingAttitudeControl.hpp.
param_t FixedwingAttitudeControl::p_p
Definition at line 214 of file FixedwingAttitudeControl.hpp.
float FixedwingAttitudeControl::p_rmax_neg
Definition at line 147 of file FixedwingAttitudeControl.hpp.
param_t FixedwingAttitudeControl::p_rmax_neg
Definition at line 218 of file FixedwingAttitudeControl.hpp.
float FixedwingAttitudeControl::p_rmax_pos
Definition at line 146 of file FixedwingAttitudeControl.hpp.
param_t FixedwingAttitudeControl::p_rmax_pos
Definition at line 217 of file FixedwingAttitudeControl.hpp.
float FixedwingAttitudeControl::p_tc
Definition at line 142 of file FixedwingAttitudeControl.hpp.
param_t FixedwingAttitudeControl::p_tc
Definition at line 213 of file FixedwingAttitudeControl.hpp.
float FixedwingAttitudeControl::pitchsp_offset_deg
Pitch Setpoint Offset in deg.
Definition at line 185 of file FixedwingAttitudeControl.hpp.
param_t FixedwingAttitudeControl::pitchsp_offset_deg
Definition at line 256 of file FixedwingAttitudeControl.hpp.
float FixedwingAttitudeControl::pitchsp_offset_rad
Pitch Setpoint Offset in rad.
Definition at line 187 of file FixedwingAttitudeControl.hpp.
float FixedwingAttitudeControl::r_ff
Definition at line 152 of file FixedwingAttitudeControl.hpp.
param_t FixedwingAttitudeControl::r_ff
Definition at line 223 of file FixedwingAttitudeControl.hpp.
float FixedwingAttitudeControl::r_i
Definition at line 151 of file FixedwingAttitudeControl.hpp.
param_t FixedwingAttitudeControl::r_i
Definition at line 222 of file FixedwingAttitudeControl.hpp.
float FixedwingAttitudeControl::r_integrator_max
Definition at line 153 of file FixedwingAttitudeControl.hpp.
param_t FixedwingAttitudeControl::r_integrator_max
Definition at line 224 of file FixedwingAttitudeControl.hpp.
float FixedwingAttitudeControl::r_p
Definition at line 150 of file FixedwingAttitudeControl.hpp.
param_t FixedwingAttitudeControl::r_p
Definition at line 221 of file FixedwingAttitudeControl.hpp.
float FixedwingAttitudeControl::r_rmax
Definition at line 154 of file FixedwingAttitudeControl.hpp.
param_t FixedwingAttitudeControl::r_rmax
Definition at line 225 of file FixedwingAttitudeControl.hpp.
float FixedwingAttitudeControl::r_tc
Definition at line 149 of file FixedwingAttitudeControl.hpp.
param_t FixedwingAttitudeControl::r_tc
Definition at line 220 of file FixedwingAttitudeControl.hpp.
float FixedwingAttitudeControl::rattitude_thres
Definition at line 202 of file FixedwingAttitudeControl.hpp.
param_t FixedwingAttitudeControl::rattitude_thres
Definition at line 271 of file FixedwingAttitudeControl.hpp.
float FixedwingAttitudeControl::roll_to_yaw_ff
Definition at line 159 of file FixedwingAttitudeControl.hpp.
param_t FixedwingAttitudeControl::roll_to_yaw_ff
Definition at line 230 of file FixedwingAttitudeControl.hpp.
float FixedwingAttitudeControl::rollsp_offset_deg
Roll Setpoint Offset in deg.
Definition at line 184 of file FixedwingAttitudeControl.hpp.
param_t FixedwingAttitudeControl::rollsp_offset_deg
Definition at line 255 of file FixedwingAttitudeControl.hpp.
float FixedwingAttitudeControl::rollsp_offset_rad
Roll Setpoint Offset in rad.
Definition at line 186 of file FixedwingAttitudeControl.hpp.
float FixedwingAttitudeControl::trim_pitch
Definition at line 174 of file FixedwingAttitudeControl.hpp.
Referenced by run().
param_t FixedwingAttitudeControl::trim_pitch
Definition at line 245 of file FixedwingAttitudeControl.hpp.
float FixedwingAttitudeControl::trim_roll
Definition at line 173 of file FixedwingAttitudeControl.hpp.
Referenced by run().
param_t FixedwingAttitudeControl::trim_roll
Definition at line 244 of file FixedwingAttitudeControl.hpp.
float FixedwingAttitudeControl::trim_yaw
Definition at line 175 of file FixedwingAttitudeControl.hpp.
Referenced by run().
param_t FixedwingAttitudeControl::trim_yaw
Definition at line 246 of file FixedwingAttitudeControl.hpp.
int32_t FixedwingAttitudeControl::vtol_type
VTOL type: 0 = tailsitter, 1 = tiltrotor.
Definition at line 204 of file FixedwingAttitudeControl.hpp.
param_t FixedwingAttitudeControl::vtol_type
Definition at line 273 of file FixedwingAttitudeControl.hpp.
bool FixedwingAttitudeControl::w_en
Definition at line 162 of file FixedwingAttitudeControl.hpp.
param_t FixedwingAttitudeControl::w_en
Definition at line 233 of file FixedwingAttitudeControl.hpp.
float FixedwingAttitudeControl::w_ff
Definition at line 165 of file FixedwingAttitudeControl.hpp.
param_t FixedwingAttitudeControl::w_ff
Definition at line 236 of file FixedwingAttitudeControl.hpp.
float FixedwingAttitudeControl::w_i
Definition at line 164 of file FixedwingAttitudeControl.hpp.
param_t FixedwingAttitudeControl::w_i
Definition at line 235 of file FixedwingAttitudeControl.hpp.
float FixedwingAttitudeControl::w_integrator_max
Definition at line 166 of file FixedwingAttitudeControl.hpp.
param_t FixedwingAttitudeControl::w_integrator_max
Definition at line 237 of file FixedwingAttitudeControl.hpp.
float FixedwingAttitudeControl::w_p
Definition at line 163 of file FixedwingAttitudeControl.hpp.
param_t FixedwingAttitudeControl::w_p
Definition at line 234 of file FixedwingAttitudeControl.hpp.
float FixedwingAttitudeControl::w_rmax
Definition at line 167 of file FixedwingAttitudeControl.hpp.
param_t FixedwingAttitudeControl::w_rmax
Definition at line 238 of file FixedwingAttitudeControl.hpp.
float FixedwingAttitudeControl::y_ff
Definition at line 157 of file FixedwingAttitudeControl.hpp.
param_t FixedwingAttitudeControl::y_ff
Definition at line 228 of file FixedwingAttitudeControl.hpp.
float FixedwingAttitudeControl::y_i
Definition at line 156 of file FixedwingAttitudeControl.hpp.
param_t FixedwingAttitudeControl::y_i
Definition at line 227 of file FixedwingAttitudeControl.hpp.
float FixedwingAttitudeControl::y_integrator_max
Definition at line 158 of file FixedwingAttitudeControl.hpp.
param_t FixedwingAttitudeControl::y_integrator_max
Definition at line 229 of file FixedwingAttitudeControl.hpp.
float FixedwingAttitudeControl::y_p
Definition at line 155 of file FixedwingAttitudeControl.hpp.
param_t FixedwingAttitudeControl::y_p
Definition at line 226 of file FixedwingAttitudeControl.hpp.
float FixedwingAttitudeControl::y_rmax
Definition at line 160 of file FixedwingAttitudeControl.hpp.
param_t FixedwingAttitudeControl::y_rmax
Definition at line 231 of file FixedwingAttitudeControl.hpp.
The documentation for this class was generated from the following files:
src/modules/fw_att_control/FixedwingAttitudeControl.hpp
src/modules/fw_att_control/FixedwingAttitudeControl.cpp