PX4 Firmware: DemoOffboardPositionSetpoints Class Reference
DemoOffboardPositionSetpoints Class Reference
#include <demo_offboard_position_setpoints.h>
Public Member Functions
DemoOffboardPositionSetpoints ()
~DemoOffboardPositionSetpoints ()
int main ()
Protected Attributes
ros::NodeHandle _n
ros::Publisher _local_position_sp_pub
Detailed Description
Definition at line 47 of file demo_offboard_position_setpoints.h.
Constructor & Destructor Documentation
DemoOffboardPositionSetpoints::DemoOffboardPositionSetpoints ()
Definition at line 47 of file demo_offboard_position_setpoints.cpp.
DemoOffboardPositionSetpoints::~DemoOffboardPositionSetpoints () inline
Definition at line 52 of file demo_offboard_position_setpoints.h.
References main().
Member Function Documentation
int DemoOffboardPositionSetpoints::main ()
Definition at line 54 of file demo_offboard_position_setpoints.cpp.
References _local_position_sp_pub, and px4::Rate::sleep().
Referenced by main(), and ~DemoOffboardPositionSetpoints().
Member Data Documentation
ros::Publisher DemoOffboardPositionSetpoints::_local_position_sp_pub protected
Definition at line 58 of file demo_offboard_position_setpoints.h.
Referenced by main().
ros::NodeHandle DemoOffboardPositionSetpoints::_n protected
Definition at line 57 of file demo_offboard_position_setpoints.h.
The documentation for this class was generated from the following files:
src/platforms/ros/nodes/demo_offboard_position_setpoints/demo_offboard_position_setpoints.h
src/platforms/ros/nodes/demo_offboard_position_setpoints/demo_offboard_position_setpoints.cpp