PX4 Firmware: src/drivers/boards/crazyflie/init.c File Reference
init.c File Reference
#include <px4_config.h>
#include <px4_tasks.h>
#include <stdbool.h>
#include <stdio.h>
#include <string.h>
#include <debug.h>
#include <errno.h>
#include "platform/cxxinitialize.h"
#include <nuttx/board.h>
#include <nuttx/analog/adc.h>
#include <nuttx/spi/spi.h>
#include "board_config.h"
#include <stm32_uart.h>
#include <arch/board/board.h>
#include <drivers/drv_hrt.h>
#include <drivers/drv_board_led.h>
#include <systemlib/px4_macros.h>
#include <systemlib/cpuload.h>
#include <systemlib/err.h>
#include <systemlib/hardfault_log.h>
#include <parameters/param.h>
Macros
#define message printf
Functions
__BEGIN_DECLS void led_init (void)
void led_on (int led)
void led_off (int led)
__END_DECLS __EXPORT void stm32_boardinitialize (void)
__EXPORT int board_app_initialize (uintptr_t arg)
Macro Definition Documentation
#define message printf
Definition at line 94 of file init.c.
Referenced by board_app_initialize().
Function Documentation
__EXPORT int board_app_initialize (uintptr_t arg)
Definition at line 151 of file init.c.
References BBSRAM_PATH, BSRAM_FILE_SIZES, drv_led_start(), hardfault_check_status(), HARDFAULT_DISPLAY_FORMAT, hardfault_increment_reboot(), hardfault_rearm(), hardfault_write(), hrt_call_every(), hrt_init(), LED_BLUE, LED_GREEN, led_off(), LED_RED, LED_RX, LED_TX, message, OK, param_init(), stm32_spi_bus_initialize(), and ts_to_abstime().
__BEGIN_DECLS void led_init (void)
Definition at line 72 of file led.c.
void led_off (int led)
Definition at line 97 of file led.c.
void led_on (int led)
Definition at line 92 of file led.c.
__END_DECLS __EXPORT void stm32_boardinitialize (void)
Definition at line 130 of file init.c.
References board_autoled_initialize(), stm32_spiinitialize(), and stm32_usbinitialize().