PX4 Firmware: src/drivers/imu/adis16477/ADIS16477_main.cpp File Reference
ADIS16477_main.cpp File Reference
#include "ADIS16477.hpp"
Namespaces
adis16477
Local functions in support of the shell command.
Macros
#define ADIS16477_DEVICE_PATH_ACCEL "/dev/adis16477_accel"
#define ADIS16477_DEVICE_PATH_GYRO "/dev/adis16477_gyro"
Functions
__EXPORT int adis16477_main (int argc, char *argv[])
void adis16477::start (enum Rotation rotation)
Start the driver.
void adis16477::test ()
Perform some basic functional tests on the driver; make sure we can collect data from the sensor in polled and automatic modes.
void adis16477::reset ()
Reset the driver.
void adis16477::info ()
Print a little info about the driver.
void adis16477::usage ()
Prints info about the driver argument usage.
Variables
ADIS16477 * adis16477::g_dev
Macro Definition Documentation
#define ADIS16477_DEVICE_PATH_ACCEL "/dev/adis16477_accel"
Definition at line 36 of file ADIS16477_main.cpp.
Referenced by adis16477::reset(), adis16477::start(), and adis16477::test().
#define ADIS16477_DEVICE_PATH_GYRO "/dev/adis16477_gyro"
Definition at line 37 of file ADIS16477_main.cpp.
Referenced by adis16477::start(), and adis16477::test().
Function Documentation
int adis16477_main (int argc, char * argv[])
Definition at line 215 of file ADIS16477_main.cpp.
References adis16477::info(), adis16477::reset(), ROTATION_NONE, adis16477::start(), adis16477::test(), and adis16477::usage().