PX4 Firmware: cdev Namespace Reference
cdev Namespace Reference
Classes
class CDev
Abstract class for any character device.
struct cdev
Character device indirection table.
struct file_operations
struct file_t
class VFile
Typedefs
using px4_file_operations_t = struct file_operations
using file_t = struct file
using mode_t = uint32_t
Functions
static int cdev_open (file_t *filp)
static int cdev_close (file_t *filp)
static ssize_t cdev_read (file_t *filp, char *buffer, size_t buflen)
static ssize_t cdev_write (file_t *filp, const char *buffer, size_t buflen)
static off_t cdev_seek (file_t *filp, off_t offset, int whence)
static int cdev_ioctl (file_t *filp, int cmd, unsigned long arg)
static int cdev_poll (file_t *filp, px4_pollfd_struct_t *fds, bool setup)
Typedef Documentation
file_t
using cdev::file_t = typedef struct file
Definition at line 17 of file cdev_platform.hpp.
mode_t
using cdev::mode_t = typedef uint32_t
Definition at line 18 of file cdev_platform.hpp.
px4_file_operations_t
typedef struct file_operations cdev::px4_file_operations_t
Definition at line 16 of file cdev_platform.hpp.
Function Documentation
cdev_close()
static int cdev::cdev_close (file_t * filp) static
Definition at line 96 of file cdev_platform.cpp.
References cdev::CDev::close().
cdev_ioctl()
static int cdev::cdev_ioctl (file_t * filp, int cmd, unsigned long arg) static
Definition at line 128 of file cdev_platform.cpp.
References cdev::CDev::ioctl().
cdev_open()
static int cdev::cdev_open (file_t * filp) static
Definition at line 88 of file cdev_platform.cpp.
References cdev::CDev::open().
cdev_poll()
static int cdev::cdev_poll (file_t * filp, px4_pollfd_struct_t * fds, bool setup) static
Definition at line 136 of file cdev_platform.cpp.
References cdev::CDev::poll().
cdev_read()
static ssize_t cdev::cdev_read (file_t * filp, char * buffer, size_t buflen) static
Definition at line 104 of file cdev_platform.cpp.
References cdev::CDev::read().
cdev_seek()
static off_t cdev::cdev_seek (file_t * filp, off_t offset, int whence) static
Definition at line 120 of file cdev_platform.cpp.
References cdev::CDev::seek().
cdev_write()
static ssize_t cdev::cdev_write (file_t * filp, const char * buffer, size_t buflen) static
Definition at line 112 of file cdev_platform.cpp.
References cdev::CDev::write().