PX4 Firmware: px4flow Namespace Reference
px4flow Namespace Reference
Local functions in support of the shell command.
Functions
int start (int argc, char *argv[])
Start the driver.
void stop ()
Stop the driver.
void test ()
Perform some basic functional tests on the driver; make sure we can collect data from the sensor in polled and automatic modes.
void reset ()
Reset the driver.
void info ()
Print a little info about the driver.
void usage ()
Prints info about the driver argument usage.
Variables
PX4FLOW * g_dev = nullptr
bool start_in_progress = false
const int START_RETRY_COUNT = 5
const int START_RETRY_TIMEOUT = 1000
Detailed Description
Local functions in support of the shell command.
Function Documentation
void px4flow::info ()
Print a little info about the driver.
Print a little info about the driver.
Definition at line 963 of file px4flow.cpp.
References errx, and PX4FLOW::print_info().
Referenced by px4flow_main().
void px4flow::reset ()
Reset the driver.
Reset the driver.
Definition at line 940 of file px4flow.cpp.
References err, fd, PX4FLOW::ioctl(), PX4FLOW0_DEVICE_PATH, SENSOR_POLLRATE_DEFAULT, SENSORIOCRESET, and SENSORIOCSPOLLRATE.
Referenced by px4flow_main().
int px4flow::start (int argc, char * argv[])
Start the driver.
Definition at line 695 of file px4flow.cpp.
References fd, g_dev, I2C_FLOW_ADDRESS_DEFAULT, I2C_FLOW_ADDRESS_MAX, PX4FLOW::init(), PX4FLOW::ioctl(), OK, PX4_ERROR, px4_getopt(), PX4_I2C_BUS_ESC, PX4_I2C_BUS_EXPANSION, PX4_I2C_BUS_EXPANSION1, PX4_I2C_BUS_EXPANSION2, PX4_I2C_BUS_ONBOARD, PX4_INFO, PX4_WARN, PX4FLOW::PX4FLOW(), PX4FLOW0_DEVICE_PATH, PX4FLOW_CONVERSION_INTERVAL_DEFAULT, PX4FLOW_CONVERSION_INTERVAL_MAX, SENSOR_POLLRATE_MAX, SENSORIOCSPOLLRATE, usage(), and usleep().
Referenced by px4flow_main().
void px4flow::stop ()
Stop the driver.
Stop the driver.
Definition at line 862 of file px4flow.cpp.
References errx, and g_dev.
Referenced by px4flow_main().
void px4flow::test ()
Perform some basic functional tests on the driver; make sure we can collect data from the sensor in polled and automatic modes.
Definition at line 883 of file px4flow.cpp.
References err, errx, fd, PX4FLOW::ioctl(), OK, PX4_WARN, PX4FLOW0_DEVICE_PATH, PX4FLOW::read(), and SENSORIOCSPOLLRATE.
Referenced by px4flow_main().
void px4flow::usage (void)
Prints info about the driver argument usage.
Prints info about the driver argument usage.
Definition at line 975 of file px4flow.cpp.
References PX4_INFO.
Referenced by px4flow_main().
Variable Documentation
PX4FLOW* px4flow::g_dev = nullptr
Definition at line 678 of file px4flow.cpp.
Referenced by start(), and stop().
bool px4flow::start_in_progress = false
Definition at line 679 of file px4flow.cpp.
const int px4flow::START_RETRY_COUNT = 5
Definition at line 681 of file px4flow.cpp.
const int px4flow::START_RETRY_TIMEOUT = 1000
Definition at line 682 of file px4flow.cpp.