PX4 Firmware: uORB::DeviceMaster Class Reference
uORB::DeviceMaster Class Reference
Master control device for ObjDev.
#include <uORBDevices.hpp>
Classes
struct DeviceNodeStatisticsData
Public Member Functions
virtual int ioctl (device::file_t *filp, int cmd, unsigned long arg)
Perform an ioctl operation on the device.
uORB::DeviceNode * getDeviceNode (const char *node_name)
Public interface for getDeviceNodeLocked().
void printStatistics (bool reset)
Print statistics for each existing topic.
void showTop (char **topic_filter, int num_filters)
Continuously print statistics, like the unix top command for processes.
Public Member Functions inherited from device::CDev
CDev (const char *name, const char *devname)
Constructor.
virtual ~CDev ()
virtual int init ()
Initialise the driver and make it ready for use.
virtual int open (file_t *filep)
Handle an open of the device.
virtual int close (file_t *filep)
Handle a close of the device.
virtual ssize_t read (file_t *filep, char *buffer, size_t buflen)
Perform a read from the device.
virtual ssize_t write (file_t *filep, const char *buffer, size_t buflen)
Perform a write to the device.
virtual off_t seek (file_t *filep, off_t offset, int whence)
Perform a logical seek operation on the device.
virtual int poll (file_t *filep, px4_pollfd_struct_t *fds, bool setup)
Perform a poll setup/teardown operation.
Public Member Functions inherited from device::Device
virtual ~Device ()=default
Destructor.
virtual int read (unsigned address, void *data, unsigned count)
Read directly from the device.
virtual int write (unsigned address, void *data, unsigned count)
Write directly to the device.
virtual int ioctl (unsigned operation, unsigned &arg)
Perform a device-specific operation.
uint8_t get_device_bus ()
Return the bus ID the device is connected to.
DeviceBusType get_device_bus_type ()
Return the bus type the device is connected to.
uint8_t get_device_address ()
Return the bus address of the device.
void set_device_address (int address)
void set_device_type (uint8_t devtype)
Set the device type.
virtual bool external ()
Private Member Functions
DeviceMaster ()
virtual ~DeviceMaster ()=default
void addNewDeviceNodes (DeviceNodeStatisticsData **first_node, int &num_topics, size_t &max_topic_name_length, char **topic_filter, int num_filters)
uORB::DeviceNode * getDeviceNodeLocked (const char *node_name)
Find a node give its name.
Private Attributes
std::map< std::string, uORB::DeviceNode * > _node_map
hrt_abstime _last_statistics_output
Friends
class uORB::Manager
Additional Inherited Members
Public Types inherited from device::Device
enum DeviceBusType { DeviceBusType_UNKNOWN = 0, DeviceBusType_I2C = 1, DeviceBusType_SPI = 2, DeviceBusType_UAVCAN = 3 }
Device bus types for DEVID.
Protected Member Functions inherited from device::CDev
virtual pollevent_t poll_state (file_t *filep)
Check the current state of the device for poll events from the perspective of the file.
virtual void poll_notify (pollevent_t events)
Report new poll events.
virtual void poll_notify_one (px4_pollfd_struct_t *fds, pollevent_t events)
Internal implementation of poll_notify.
virtual int open_first (file_t *filep)
Notification of the first open.
virtual int close_last (file_t *filep)
Notification of the last close.
virtual int register_class_devname (const char *class_devname)
Register a class device name, automatically adding device class instance suffix if need be.
virtual int unregister_class_devname (const char *class_devname, unsigned class_instance)
Register a class device name, automatically adding device class instance suffix if need be.
const char * get_devname ()
Get the device name.
void lock ()
Take the driver lock.
void unlock ()
Release the driver lock.
Protected Member Functions inherited from device::Device
Device (const char *name)
Device (DeviceBusType bus_type, uint8_t bus, uint8_t address, uint8_t devtype=0)
Device (const Device &)=delete
Device & operator= (const Device &)=delete
Device (Device &&)=delete
Device & operator= (Device &&)=delete
Protected Attributes inherited from device::CDev
px4_sem_t _lock
lock to protect access to all class members (also for derived classes)
bool _pub_blocked {false}
true if publishing should be blocked
Protected Attributes inherited from device::Device
union DeviceId _device_id
device identifier information
const char * _name
driver name
bool _debug_enabled {false}
if true, debug messages are printed
Static Protected Attributes inherited from device::CDev
static const px4_file_operations_t fops = {}
Pointer to the default cdev file operations table; useful for registering clone devices etc.
Detailed Description
Master control device for ObjDev.
Used primarily to create new objects via the ORBIOCCREATE ioctl.
Definition at line 275 of file uORBDevices.hpp.
Constructor & Destructor Documentation
uORB::DeviceMaster::DeviceMaster () private
Definition at line 830 of file uORBDevices.cpp.
References _last_statistics_output, and hrt_absolute_time().
virtual uORB::DeviceMaster::~DeviceMaster () private virtual default
Member Function Documentation
void uORB::DeviceMaster::addNewDeviceNodes (DeviceNodeStatisticsData ** first_node, int & num_topics, size_t & max_topic_name_length, char ** topic_filter, int num_filters) private
Definition at line 976 of file uORBDevices.cpp.
References uORB::DeviceNode::get_meta(), INIT_NODE_MAP_VARS, uORB::DeviceMaster::DeviceNodeStatisticsData::instance, ITERATE_NODE_MAP, uORB::DeviceMaster::DeviceNodeStatisticsData::last_lost_msg_count, uORB::DeviceMaster::DeviceNodeStatisticsData::last_pub_msg_count, uORB::DeviceNode::lost_message_count(), uORB::DeviceMaster::DeviceNodeStatisticsData::next, uORB::DeviceMaster::DeviceNodeStatisticsData::node, orb_metadata::o_name, uORB::DeviceNode::published_message_count(), and PX4_ERR.
Referenced by showTop().
uORB::DeviceNode * uORB::DeviceMaster::getDeviceNode (const char * node_name)
Public interface for getDeviceNodeLocked().
Takes care of synchronization.
Returns
node if exists, nullptr otherwise
Definition at line 1188 of file uORBDevices.cpp.
References _node_map, getDeviceNodeLocked(), device::CDev::lock(), and device::CDev::unlock().
Referenced by uORB::Manager::node_open().
uORB::DeviceNode * uORB::DeviceMaster::getDeviceNodeLocked (const char * node_name) private
Find a node give its name.
_lock must already be held when calling this.
Returns
node if exists, nullptr otherwise
Definition at line 1213 of file uORBDevices.cpp.
References _node_map.
Referenced by getDeviceNode(), and ioctl().
int uORB::DeviceMaster::ioctl (device::file_t * filep, int cmd, unsigned long arg) virtual
Perform an ioctl operation on the device.
The default implementation handles DIOC_GETPRIV, and otherwise returns -ENOTTY. Subclasses should call the default implementation for any command they do not handle themselves.
Parameters
filep Pointer to the NuttX file structure.
cmd The ioctl command value.
arg The ioctl argument value.
Returns
OK on success, or -errno otherwise.
Reimplemented from device::CDev.
Definition at line 837 of file uORBDevices.cpp.
References device::CDev::_lock, _node_map, getDeviceNodeLocked(), device::CDev::init(), uORB::orb_advertdata::instance, uORB::DeviceNode::is_published(), uORB::orb_advertdata::meta, uORB::Utils::node_mkpath(), orb_metadata::o_name, uORB::orb_maxpath, ORB_MULTI_MAX_INSTANCES, ORBIOCADVERTISE, uORB::orb_advertdata::priority, PX4_ERROR, PX4_OK, and uORB::DeviceNode::set_priority().
void uORB::DeviceMaster::printStatistics (bool reset)
Print statistics for each existing topic.
Parameters
reset if true, reset statistics afterwards
Definition at line 950 of file uORBDevices.cpp.
References _last_statistics_output, hrt_absolute_time(), hrt_abstime, INIT_NODE_MAP_VARS, ITERATE_NODE_MAP, device::CDev::lock(), PX4_INFO, and device::CDev::unlock().
Referenced by uorb_main().
void uORB::DeviceMaster::showTop (char ** topic_filter, int num_filters)
Continuously print statistics, like the unix top command for processes.
Exited when the user presses the enter key.
Parameters
topic_filter list of topic filters: if set, each string can be a substring for topics to match. Or it can be '-a', which means to print all topics instead of only currently publishing ones.
num_filters
Definition at line 1049 of file uORBDevices.cpp.
References _node_map, addNewDeviceNodes(), CLEAR_LINE, dt, uORB::DeviceNode::get_meta(), uORB::DeviceNode::get_queue_size(), hrt_absolute_time(), hrt_abstime, uORB::DeviceMaster::DeviceNodeStatisticsData::instance, uORB::DeviceMaster::DeviceNodeStatisticsData::last_lost_msg_count, uORB::DeviceMaster::DeviceNodeStatisticsData::last_pub_msg_count, device::CDev::lock(), uORB::DeviceNode::lost_message_count(), uORB::DeviceMaster::DeviceNodeStatisticsData::lost_msg_delta, uORB::DeviceMaster::DeviceNodeStatisticsData::next, uORB::DeviceMaster::DeviceNodeStatisticsData::node, num_runs, orb_metadata::o_name, device::CDev::poll(), uORB::DeviceMaster::DeviceNodeStatisticsData::pub_msg_delta, uORB::DeviceNode::published_message_count(), PX4_INFO, PX4_INFO_RAW, device::CDev::read(), uORB::DeviceNode::subscriber_count(), device::CDev::unlock(), and usleep().
Referenced by uorb_main().
Friends And Related Function Documentation
friend class uORB::Manager friend
Definition at line 318 of file uORBDevices.hpp.
Member Data Documentation
hrt_abstime uORB::DeviceMaster::_last_statistics_output private
Definition at line 332 of file uORBDevices.hpp.
Referenced by DeviceMaster(), and printStatistics().
std::map<std::string, uORB::DeviceNode *> uORB::DeviceMaster::_node_map private
Definition at line 330 of file uORBDevices.hpp.
Referenced by getDeviceNode(), getDeviceNodeLocked(), ioctl(), and showTop().
The documentation for this class was generated from the following files:
src/modules/uORB/uORBDevices.hpp
src/modules/uORB/uORBDevices.cpp