PX4 Firmware: MD25 Class Reference
MD25 Class Reference
This is a driver for the MD25 motor controller utilizing the I2C interface.
#include <md25.hpp>
Public Types
enum e_mode { MODE_UNSIGNED_SPEED = 0, MODE_SIGNED_SPEED, MODE_UNSIGNED_SPEED_TURN, MODE_SIGNED_SPEED_TURN }
modes
enum e_cmd {
CMD_RESET_ENCODERS = 32, CMD_DISABLE_SPEED_REGULATION = 48, CMD_ENABLE_SPEED_REGULATION = 49, CMD_DISABLE_TIMEOUT = 50,
CMD_ENABLE_TIMEOUT = 51, CMD_CHANGE_I2C_SEQ_0 = 160, CMD_CHANGE_I2C_SEQ_1 = 170, CMD_CHANGE_I2C_SEQ_2 = 165
}
commands
enum e_channels { CH_SPEED_LEFT = 0, CH_SPEED_RIGHT }
control channels
Public Member Functions
MD25 (const char *deviceName, int bus, uint16_t address, uint32_t speed=100000)
constructor
virtual ~MD25 ()=default
deconstructor
uint8_t getVersion ()
float getMotor1Speed ()
float getMotor2Speed ()
float getRevolutions1 ()
float getRevolutions2 ()
float getBatteryVolts ()
float getMotor1Current ()
float getMotor2Current ()
uint8_t getMotorAccel ()
e_mode getMode ()
e_cmd getCommand ()
int resetEncoders ()
resets the encoders
int setSpeedRegulation (bool enable)
enable/disable speed regulation
int setTimeout (bool enable)
set the timeout for the motors enable/disable timeout (motor stop) after 2 sec of no i2c messages
int setDeviceAddress (uint8_t address)
sets the device address can only be done with one MD25 on the bus
int setMotorAccel (uint8_t accel)
set motor acceleration
int setMotor1Speed (float normSpeed)
set motor 1 speed
int setMotor2Speed (float normSpeed)
set motor 2 speed
void update ()
main update loop that updates MD25 motor speeds based on actuator publication
virtual int probe ()
probe for device
int search ()
search for device
int readData ()
read data from i2c
void status (char *string, size_t n)
print status
Private Member Functions
int _writeUint8 (uint8_t reg, uint8_t value)
int _writeInt8 (uint8_t reg, int8_t value)
float _uint8ToNorm (uint8_t value)
uint8_t _normToUint8 (float value)
int _setMode (e_mode)
set motor control mode, this driver assumed we are always in mode 0 so we don't let the user change the mode
Private Attributes
struct pollfd _controlPoll
poll structure for control packets
uORB::Subscription< actuator_controls_s > _actuators
actuator controls subscription
uint8_t _version
float _motor1Speed
float _motor2Speed
float _revolutions1
float _revolutions2
float _batteryVoltage
float _motor1Current
float _motor2Current
uint8_t _motorAccel
e_mode _mode
e_cmd _command
Detailed Description
This is a driver for the MD25 motor controller utilizing the I2C interface.
Definition at line 56 of file md25.hpp.
Member Enumeration Documentation
enum MD25::e_channels
control channels
Enumerator
CH_SPEED_LEFT
CH_SPEED_RIGHT
Definition at line 103 of file md25.hpp.
enum MD25::e_cmd
commands
Enumerator
CMD_RESET_ENCODERS
CMD_DISABLE_SPEED_REGULATION
CMD_ENABLE_SPEED_REGULATION
CMD_DISABLE_TIMEOUT
CMD_ENABLE_TIMEOUT
CMD_CHANGE_I2C_SEQ_0
CMD_CHANGE_I2C_SEQ_1
CMD_CHANGE_I2C_SEQ_2
Definition at line 91 of file md25.hpp.
enum MD25::e_mode
modes
NOTE: this driver assumes we are always in mode 0!
seprate speed mode: motor speed1 = speed1 motor speed2 = speed2 turn speed mode: motor speed1 = speed1 + speed2 motor speed2 = speed2 - speed2 unsigned: full rev (0), stop(128), full fwd (255) signed: full rev (-127), stop(0), full fwd (128)
modes numbers: 0 : unsigned separate (default) 1 : signed separate 2 : unsigned turn 3 : signed turn
Enumerator
MODE_UNSIGNED_SPEED
MODE_SIGNED_SPEED
MODE_UNSIGNED_SPEED_TURN
MODE_SIGNED_SPEED_TURN
Definition at line 83 of file md25.hpp.
Constructor & Destructor Documentation
MD25::MD25 (const char * deviceName, int bus, uint16_t address, uint32_t speed = 100000)
constructor
Parameters
deviceName the name of the device e.g. "/dev/md25"
bus the I2C bus
address the adddress on the I2C bus
speed the speed of the I2C communication
Definition at line 85 of file md25.cpp.
References _actuators, _controlPoll, _setMode(), uORB::SubscriptionBase::getHandle(), lis3mdl::init(), MODE_UNSIGNED_SPEED, OK, resetEncoders(), setMotor1Speed(), setMotor2Speed(), setMotorAccel(), setSpeedRegulation(), and setTimeout().
virtual MD25::~MD25 () virtual default
deconstructor
Member Function Documentation
uint8_t MD25::_normToUint8 (float value) private
Definition at line 448 of file md25.cpp.
Referenced by setMotor1Speed(), and setMotor2Speed().
int MD25::_setMode (e_mode mode) private
set motor control mode, this driver assumed we are always in mode 0 so we don't let the user change the mode
Returns
non-zero -> error
Definition at line 242 of file md25.cpp.
References _writeUint8(), and REG_MODE_RW.
Referenced by MD25().
float MD25::_uint8ToNorm (uint8_t value) private
Definition at line 441 of file md25.cpp.
Referenced by readData().
int MD25::_writeInt8 (uint8_t reg, int8_t value) private
Definition at line 432 of file md25.cpp.
int MD25::_writeUint8 (uint8_t reg, uint8_t value) private
Definition at line 423 of file md25.cpp.
Referenced by _setMode(), resetEncoders(), setMotor1Speed(), setMotor2Speed(), setMotorAccel(), setSpeedRegulation(), and setTimeout().
float MD25::getBatteryVolts ()
Returns
battery voltage, volts
Definition at line 207 of file md25.cpp.
References _batteryVoltage.
Referenced by status().
MD25::e_cmd MD25::getCommand ()
Returns
current command register value
Definition at line 231 of file md25.cpp.
References _command.
Referenced by status().
MD25::e_mode MD25::getMode ()
Returns
motor output mode
Definition at line 226 of file md25.cpp.
References _mode.
Referenced by status().
float MD25::getMotor1Current ()
Returns
motor 1 current, amps
Definition at line 212 of file md25.cpp.
References _motor1Current.
Referenced by status().
float MD25::getMotor1Speed ()
Returns
speed of motor, normalized (-1, 1)
Definition at line 187 of file md25.cpp.
References _motor1Speed.
Referenced by status().
float MD25::getMotor2Current ()
Returns
motor 2 current, amps
Definition at line 216 of file md25.cpp.
References _motor2Current.
Referenced by status().
float MD25::getMotor2Speed ()
Returns
speed of motor 2, normalized (-1, 1)
Definition at line 192 of file md25.cpp.
References _motor2Speed.
Referenced by status().
uint8_t MD25::getMotorAccel ()
Returns
the motor acceleration controls motor speed change (1-10) accel rate | time for full fwd. to full rev. 1 | 6.375 s 2 | 1.6 s 3 | 0.675 s 5(default) | 1.275 s 10 | 0.65 s
Definition at line 221 of file md25.cpp.
References _motorAccel.
Referenced by status().
float MD25::getRevolutions1 ()
Returns
number of rotations since reset
Definition at line 197 of file md25.cpp.
References _revolutions1.
Referenced by md25Sine(), md25Test(), and status().
float MD25::getRevolutions2 ()
Returns
number of rotations since reset
Definition at line 202 of file md25.cpp.
References _revolutions2.
Referenced by md25Test(), and status().
uint8_t MD25::getVersion ()
Returns
software version
Definition at line 182 of file md25.cpp.
References _version.
Referenced by status().
int MD25::probe () virtual
probe for device
Definition at line 342 of file md25.cpp.
References OK, and readData().
Referenced by md25_main().
int MD25::readData ()
read data from i2c
Definition at line 124 of file md25.cpp.
References _batteryVoltage, _command, _mode, _motor1Current, _motor1Speed, _motor2Current, _motor2Speed, _motorAccel, _revolutions1, _revolutions2, _uint8ToNorm(), _version, OK, REG_ACCEL_RATE_RW, REG_BATTERY_VOLTS_R, REG_COMMAND_RW, REG_ENC1A_R, REG_ENC1B_R, REG_ENC1C_R, REG_ENC1D_R, REG_ENC2A_R, REG_ENC2B_R, REG_ENC2C_R, REG_ENC2D_R, REG_MODE_RW, REG_MOTOR1_CURRENT_R, REG_MOTOR2_CURRENT_R, REG_SPEED1_RW, REG_SPEED2_RW, and REG_SW_VERSION_R.
Referenced by md25Sine(), md25Test(), probe(), and search().
int MD25::resetEncoders ()
resets the encoders
Returns
non-zero -> error
Definition at line 236 of file md25.cpp.
References _writeUint8(), CMD_RESET_ENCODERS, and REG_COMMAND_RW.
Referenced by MD25(), md25Sine(), and md25Test().
int MD25::search ()
search for device
Definition at line 384 of file md25.cpp.
References OK, and readData().
Referenced by md25_main().
int MD25::setDeviceAddress (uint8_t address)
sets the device address can only be done with one MD25 on the bus
Returns
non-zero -> error
Definition at line 272 of file md25.cpp.
References CMD_CHANGE_I2C_SEQ_0, CMD_CHANGE_I2C_SEQ_1, CMD_CHANGE_I2C_SEQ_2, OK, and usleep().
Referenced by md25_main().
int MD25::setMotor1Speed (float normSpeed)
set motor 1 speed
Parameters
normSpeed normalize speed between -1 and 1
Returns
non-zero -> error
Definition at line 314 of file md25.cpp.
References _normToUint8(), _writeUint8(), and REG_SPEED1_RW.
Referenced by MD25(), md25Sine(), md25Test(), and update().
int MD25::setMotor2Speed (float normSpeed)
set motor 2 speed
Parameters
normSpeed normalize speed between -1 and 1
Returns
non-zero -> error
Definition at line 320 of file md25.cpp.
References _normToUint8(), _writeUint8(), and REG_SPEED2_RW.
Referenced by MD25(), md25Test(), and update().
int MD25::setMotorAccel (uint8_t accel)
set motor acceleration
Parameters
accel controls motor speed change (1-10) accel rate | time for full fwd. to full rev. 1 | 6.375 s 2 | 1.6 s 3 | 0.675 s 5(default) | 1.275 s 10 | 0.65 s
Definition at line 308 of file md25.cpp.
References _writeUint8(), and REG_ACCEL_RATE_RW.
Referenced by MD25().
int MD25::setSpeedRegulation (bool enable)
enable/disable speed regulation
Returns
non-zero -> error
Definition at line 248 of file md25.cpp.
References _writeUint8(), CMD_DISABLE_SPEED_REGULATION, CMD_ENABLE_SPEED_REGULATION, and REG_COMMAND_RW.
Referenced by MD25(), md25Sine(), and md25Test().
int MD25::setTimeout (bool enable)
set the timeout for the motors enable/disable timeout (motor stop) after 2 sec of no i2c messages
Returns
non-zero -> error
Definition at line 260 of file md25.cpp.
References _writeUint8(), CMD_DISABLE_TIMEOUT, CMD_ENABLE_TIMEOUT, and REG_COMMAND_RW.
Referenced by MD25(), md25Sine(), and md25Test().
void MD25::status (char * string, size_t n)
print status
Definition at line 155 of file md25.cpp.
References getBatteryVolts(), getCommand(), getMode(), getMotor1Current(), getMotor1Speed(), getMotor2Current(), getMotor2Speed(), getMotorAccel(), getRevolutions1(), getRevolutions2(), and getVersion().
Referenced by md25_main(), md25Sine(), and md25Test().
void MD25::update ()
main update loop that updates MD25 motor speeds based on actuator publication
Definition at line 326 of file md25.cpp.
References _actuators, _controlPoll, CH_SPEED_LEFT, CH_SPEED_RIGHT, setMotor1Speed(), setMotor2Speed(), uORB::Subscription< T >::update(), and uORB::SubscriptionBase::updated().
Referenced by md25_thread_main().
Member Data Documentation
uORB::Subscription<actuator_controls_s> MD25::_actuators private
actuator controls subscription
Definition at line 273 of file md25.hpp.
Referenced by MD25(), and update().
float MD25::_batteryVoltage private
Definition at line 281 of file md25.hpp.
Referenced by getBatteryVolts(), and readData().
e_cmd MD25::_command private
Definition at line 286 of file md25.hpp.
Referenced by getCommand(), and readData().
struct pollfd MD25::_controlPoll private
poll structure for control packets
Definition at line 270 of file md25.hpp.
Referenced by MD25(), and update().
e_mode MD25::_mode private
Definition at line 285 of file md25.hpp.
Referenced by getMode(), and readData().
float MD25::_motor1Current private
Definition at line 282 of file md25.hpp.
Referenced by getMotor1Current(), and readData().
float MD25::_motor1Speed private
Definition at line 277 of file md25.hpp.
Referenced by getMotor1Speed(), and readData().
float MD25::_motor2Current private
Definition at line 283 of file md25.hpp.
Referenced by getMotor2Current(), and readData().
float MD25::_motor2Speed private
Definition at line 278 of file md25.hpp.
Referenced by getMotor2Speed(), and readData().
uint8_t MD25::_motorAccel private
Definition at line 284 of file md25.hpp.
Referenced by getMotorAccel(), and readData().
float MD25::_revolutions1 private
Definition at line 279 of file md25.hpp.
Referenced by getRevolutions1(), and readData().
float MD25::_revolutions2 private
Definition at line 280 of file md25.hpp.
Referenced by getRevolutions2(), and readData().
uint8_t MD25::_version private
Definition at line 276 of file md25.hpp.
Referenced by getVersion(), and readData().
The documentation for this class was generated from the following files:
src/drivers/md25/md25.hpp
src/drivers/md25/md25.cpp