PX4 Firmware: src/systemcmds/esc_calib/esc_calib.c File Reference
esc_calib.c File Reference
#include <px4_config.h>
#include <px4_getopt.h>
#include <px4_module.h>
#include <px4_defines.h>
#include <px4_log.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <stdbool.h>
#include <unistd.h>
#include <fcntl.h>
#include <poll.h>
#include <sys/mount.h>
#include <sys/ioctl.h>
#include <sys/stat.h>
#include <arch/board/board.h>
#include "drivers/drv_pwm_output.h"
#include <uORB/topics/actuator_controls.h>
Functions
static void usage (const char *reason)
__EXPORT int esc_calib_main (int argc, char *argv[])
Function Documentation
int esc_calib_main (int argc, char * argv[])
Definition at line 92 of file esc_calib.c.
References fd, OK, orb_check(), orb_copy(), ORB_ID_VEHICLE_ATTITUDE_CONTROLS, orb_subscribe(), PWM_DEFAULT_MAX, PWM_DEFAULT_MIN, PWM_HIGHEST_MAX, PWM_HIGHEST_MIN, PWM_LOWEST_MAX, PWM_LOWEST_MIN, PWM_OUTPUT0_DEVICE_PATH, PWM_OUTPUT_MAX_CHANNELS, PWM_SERVO_ARM, PWM_SERVO_DISARM, PWM_SERVO_GET_COUNT, PWM_SERVO_SET, PWM_SERVO_SET_ARM_OK, PX4_ERR, px4_getopt(), read(), usage(), and usleep().
static void usage (const char * reason) static
Definition at line 66 of file esc_calib.c.
References PRINT_MODULE_DESCRIPTION(), PRINT_MODULE_USAGE_NAME_SIMPLE(), PRINT_MODULE_USAGE_PARAM_FLAG(), PRINT_MODULE_USAGE_PARAM_INT(), PRINT_MODULE_USAGE_PARAM_STRING(), and PX4_ERR.
Referenced by esc_calib_main().