PX4 Firmware: dm_operations_t Struct Reference
dm_operations_t Struct Reference
Public Attributes
ssize_t(* write)(dm_item_t item, unsigned index, dm_persitence_t persistence, const void *buf, size_t count)
ssize_t(* read)(dm_item_t item, unsigned index, void *buf, size_t count)
int(* clear)(dm_item_t item)
int(* restart)(dm_reset_reason reason)
int(* initialize)(unsigned max_offset)
void(* shutdown)()
int(* wait)(px4_sem_t *sem)
Detailed Description
Definition at line 99 of file dataman.cpp.
Member Data Documentation
clear
int(* dm_operations_t::clear) (dm_item_t item)
Definition at line 102 of file dataman.cpp.
Referenced by _file_clear(), and task_main().
initialize
int(* dm_operations_t::initialize) (unsigned max_offset)
Definition at line 104 of file dataman.cpp.
Referenced by _ram_initialize(), and task_main().
read
ssize_t(* dm_operations_t::read) (dm_item_t item, unsigned index, void *buf, size_t count)
Definition at line 101 of file dataman.cpp.
Referenced by _file_clear(), _file_initialize(), _file_read(), _file_restart(), _ram_initialize(), and task_main().
restart
int(* dm_operations_t::restart) (dm_reset_reason reason)
Definition at line 103 of file dataman.cpp.
Referenced by _file_restart(), and task_main().
shutdown
void(* dm_operations_t::shutdown) ()
Definition at line 105 of file dataman.cpp.
Referenced by _ram_shutdown(), and task_main().
wait
int(* dm_operations_t::wait) (px4_sem_t *sem)
Definition at line 106 of file dataman.cpp.
Referenced by task_main().
write
ssize_t(* dm_operations_t::write) (dm_item_t item, unsigned index, dm_persitence_t persistence, const void *buf, size_t count)
Definition at line 100 of file dataman.cpp.
Referenced by _file_clear(), _file_initialize(), _file_restart(), _file_write(), _ram_initialize(), and task_main().
The documentation for this struct was generated from the following file:
src/modules/dataman/dataman.cpp