PX4 Firmware: LinuxGPIO Class Reference
LinuxGPIO Class Reference
#include <linux_gpio.h>
Public Types
enum Direction { Direction::IN = 0, Direction::OUT = 1 }
enum Value { Value::LOW = 0, Value::HIGH = 1 }
Public Member Functions
LinuxGPIO (unsigned int pin)
~LinuxGPIO ()
int exportPin ()
int unexportPin ()
int setDirection (LinuxGPIO::Direction dir)
int readValue ()
int writeValue (LinuxGPIO::Value value)
Private Attributes
int _pin
int _fd
Detailed Description
Definition at line 46 of file linux_gpio.h.
Member Enumeration Documentation
enum LinuxGPIO::Direction strong
Enumerator
IN
OUT
Definition at line 52 of file linux_gpio.h.
enum LinuxGPIO::Value strong
Enumerator
LOW
HIGH
Definition at line 57 of file linux_gpio.h.
Constructor & Destructor Documentation
LinuxGPIO::LinuxGPIO (unsigned int pin)
Definition at line 44 of file linux_gpio.cpp.
LinuxGPIO::~LinuxGPIO ()
Definition at line 50 of file linux_gpio.cpp.
References _fd.
Member Function Documentation
int LinuxGPIO::exportPin ()
Definition at line 57 of file linux_gpio.cpp.
References _fd, _pin, err, fd, PIN_INDEX_BUFFER_MAX, PIN_VALUE_BUFFER_MAX, PX4_ERR, and write().
Referenced by RGBLED::start().
int LinuxGPIO::readValue ()
Definition at line 198 of file linux_gpio.cpp.
References _fd, _pin, err, PX4_ERR, and read().
int LinuxGPIO::setDirection (LinuxGPIO::Direction dir)
Definition at line 162 of file linux_gpio.cpp.
References _pin, err, fd, IN, path, PIN_DIRECTION_BUFFER_MAX, PX4_ERR, and write().
Referenced by RGBLED::start().
int LinuxGPIO::unexportPin ()
Definition at line 121 of file linux_gpio.cpp.
References _fd, _pin, err, fd, PIN_INDEX_BUFFER_MAX, PX4_ERR, and write().
Referenced by RGBLED::start(), and RGBLED::stop().
int LinuxGPIO::writeValue (LinuxGPIO::Value value)
Definition at line 216 of file linux_gpio.cpp.
References _fd, _pin, err, HIGH, LOW, PX4_ERR, and write().
Referenced by RGBLED::_measure().
Member Data Documentation
int LinuxGPIO::_fd private
Definition at line 70 of file linux_gpio.h.
Referenced by exportPin(), readValue(), unexportPin(), writeValue(), and ~LinuxGPIO().
int LinuxGPIO::_pin private
Definition at line 69 of file linux_gpio.h.
Referenced by exportPin(), readValue(), setDirection(), unexportPin(), and writeValue().
The documentation for this class was generated from the following files:
src/drivers/linux_gpio/linux_gpio.h
src/drivers/linux_gpio/linux_gpio.cpp