PX4 Firmware: QMC5883_I2C Class Reference
QMC5883_I2C Class Reference
Public Member Functions
QMC5883_I2C (int bus)
virtual ~QMC5883_I2C ()=default
virtual int read (unsigned address, void *data, unsigned count)
virtual int write (unsigned address, void *data, unsigned count)
virtual int ioctl (unsigned operation, unsigned &arg)
Protected Member Functions
virtual int probe ()
Detailed Description
Definition at line 66 of file qmc5883_i2c.cpp.
Constructor & Destructor Documentation
QMC5883_I2C()
QMC5883_I2C::QMC5883_I2C (int bus)
Definition at line 88 of file qmc5883_i2c.cpp.
References DRV_MAG_DEVTYPE_QMC5883.
Referenced by QMC5883_I2C_interface().
~QMC5883_I2C()
virtual QMC5883_I2C::~QMC5883_I2C () virtual default
Member Function Documentation
ioctl()
int QMC5883_I2C::ioctl (unsigned operation, unsigned & arg) virtual
Definition at line 95 of file qmc5883_i2c.cpp.
References MAGIOCGEXTERNAL.
probe()
int QMC5883_I2C::probe () protected virtual
Definition at line 115 of file qmc5883_i2c.cpp.
References ADDR_ID_A, ADDR_ID_B, data, DEVICE_DEBUG, ID_A_WHO_AM_I, ID_B_WHO_AM_I, OK, and read().
read()
int QMC5883_I2C::read (unsigned address, void * data, unsigned count) virtual
Definition at line 176 of file qmc5883_i2c.cpp.
Referenced by probe().
write()
int QMC5883_I2C::write (unsigned address, void * data, unsigned count) virtual
Definition at line 161 of file qmc5883_i2c.cpp.
The documentation for this class was generated from the following file:
src/drivers/magnetometer/qmc5883/qmc5883_i2c.cpp