PX4 Firmware: src/drivers/boards/nxphlite-v3/init.c File Reference
init.c File Reference
#include <px4_config.h>
#include <stdbool.h>
#include <stdio.h>
#include <string.h>
#include <debug.h>
#include <errno.h>
#include "platform/cxxinitialize.h"
#include <nuttx/board.h>
#include <nuttx/spi/spi.h>
#include <nuttx/i2c/i2c_master.h>
#include <nuttx/sdio.h>
#include <nuttx/mmcsd.h>
#include <nuttx/analog/adc.h>
#include <kinetis.h>
#include <chip/kinetis_uart.h>
#include "board_config.h"
#include "up_arch.h"
#include <arch/board/board.h>
#include <drivers/drv_hrt.h>
#include <drivers/drv_board_led.h>
#include <systemlib/px4_macros.h>
#include <systemlib/cpuload.h>
#include <perf/perf_counter.h>
#include <systemlib/err.h>
Macros
#define message printf
Functions
__BEGIN_DECLS void led_init (void)
void led_on (int led)
void led_off (int led)
__END_DECLS void board_on_reset (int status)
int board_read_VBUS_state (void)
__EXPORT void board_rc_input (bool invert_on, uint32_t uxart_base)
__EXPORT void board_peripheral_reset (int ms)
__EXPORT void kinetis_boardinitialize (void)
int up_rtc_getdatetime (FAR struct tm *tp)
static void kinetis_serial_dma_poll (void)
__EXPORT int board_app_initialize (uintptr_t arg)
Macro Definition Documentation
#define message printf
Definition at line 102 of file init.c.
Referenced by board_app_initialize().
Function Documentation
__EXPORT int board_app_initialize (uintptr_t arg)
Definition at line 297 of file init.c.
References BBSRAM_PATH, board_autoled_on(), board_dma_alloc_init, BSRAM_FILE_SIZES, drv_led_start(), hardfault_check_status(), HARDFAULT_DISPLAY_FORMAT, hardfault_increment_reboot(), hardfault_rearm(), hardfault_write(), hrt_call_every(), hrt_init(), kinetis_serial_dma_poll(), LED_BLUE, LED_GREEN, led_off(), LED_RED, message, nxphlite_sdhc_initialize(), nxphlite_spi_bus_initialize(), nxphlite_spidev_initialize(), OK, param_init(), ts_to_abstime(), VDD_3V3_SD_CARD_EN, VDD_3V3_SENSORS_EN, and VDD_ETH_EN.
__END_DECLS void board_on_reset (int status)
Definition at line 137 of file init.c.
References arraySize, board_gpio_init(), and PX4_GPIO_PWM_INIT_LIST.
__EXPORT void board_peripheral_reset (int ms)
Definition at line 207 of file init.c.
References usleep(), and warnx.
__EXPORT void board_rc_input (bool invert_on, uint32_t uxart_base)
Definition at line 176 of file init.c.
int board_read_VBUS_state (void)
Definition at line 161 of file init.c.
References BOARD_ADC_USB_CONNECTED.
Referenced by usb_connected_main().
__EXPORT void kinetis_boardinitialize (void)
Definition at line 231 of file init.c.
References arraySize, board_autoled_initialize(), board_gpio_init(), board_on_reset(), nxphlite_timer_initialize(), PX4_GPIO_INIT_LIST, up_rtc_getdatetime(), and VDD_3V3_SPEKTRUM_POWER_EN.
static void kinetis_serial_dma_poll (void) static
Definition at line 265 of file init.c.
Referenced by board_app_initialize().
__BEGIN_DECLS void led_init (void)
Definition at line 72 of file led.c.
void led_off (int led)
Definition at line 97 of file led.c.
void led_on (int led)
Definition at line 92 of file led.c.
int up_rtc_getdatetime (FAR struct tm * tp)
Definition at line 251 of file init.c.
Referenced by kinetis_boardinitialize().