PX4 Firmware: teraranger Namespace Reference
teraranger Namespace Reference
Local functions in support of the shell command.
Functions
int start (uint8_t rotation)
Attempt to start driver on all available I2C busses.
int start_bus (uint8_t rotation, int i2c_bus)
Start the driver on a specific bus.
int stop ()
Stop the driver.
int test ()
Perform some basic functional tests on the driver; make sure we can collect data from the sensor in polled and automatic modes.
int reset ()
Reset the driver.
int info ()
Print a little info about the driver.
Variables
TERARANGER * g_dev
Detailed Description
Local functions in support of the shell command.
Function Documentation
int teraranger::info ()
Print a little info about the driver.
Print a little info about the driver.
Definition at line 960 of file teraranger.cpp.
References TERARANGER::print_info(), PX4_ERR, PX4_ERROR, and PX4_OK.
Referenced by teraranger_main().
int teraranger::reset ()
Reset the driver.
Reset the driver.
Definition at line 933 of file teraranger.cpp.
References fd, TERARANGER::ioctl(), px4_close(), PX4_ERR, PX4_ERROR, PX4_OK, px4_open(), SENSOR_POLLRATE_DEFAULT, SENSORIOCRESET, SENSORIOCSPOLLRATE, and TERARANGER_DEVICE_PATH.
Referenced by teraranger_main().
int teraranger::start (uint8_t rotation)
Attempt to start driver on all available I2C busses.
This function will return as soon as the first sensor is detected on one of the available busses or if no sensors are detected.
Definition at line 767 of file teraranger.cpp.
References i2c_bus_options, PX4_ERR, PX4_ERROR, PX4_OK, and start_bus().
Referenced by teraranger_main().
int teraranger::start_bus (uint8_t rotation, int i2c_bus)
Start the driver on a specific bus.
This function only returns if the sensor is up and running or could not be detected successfully.
Definition at line 790 of file teraranger.cpp.
References fd, g_dev, TERARANGER::init(), TERARANGER::ioctl(), OK, px4_close(), PX4_ERR, PX4_ERROR, PX4_OK, px4_open(), SENSOR_POLLRATE_DEFAULT, SENSORIOCSPOLLRATE, TERARANGER::TERARANGER(), and TERARANGER_DEVICE_PATH.
Referenced by start(), and teraranger_main().
int teraranger::stop ()
Stop the driver.
Stop the driver.
Definition at line 843 of file teraranger.cpp.
References g_dev, PX4_ERR, PX4_ERROR, and PX4_OK.
Referenced by teraranger_main().
int teraranger::test ()
Perform some basic functional tests on the driver; make sure we can collect data from the sensor in polled and automatic modes.
Definition at line 863 of file teraranger.cpp.
References fd, TERARANGER::ioctl(), OK, px4_close(), PX4_ERR, PX4_ERROR, PX4_INFO, PX4_OK, px4_open(), TERARANGER::read(), SENSOR_POLLRATE_DEFAULT, SENSORIOCSPOLLRATE, and TERARANGER_DEVICE_PATH.
Referenced by teraranger_main().
Variable Documentation
TERARANGER* teraranger::g_dev
Definition at line 748 of file teraranger.cpp.
Referenced by start_bus(), and stop().