PX4 Firmware: DfMPU6050Wrapper Class Reference
DfMPU6050Wrapper Class Reference
Classes
struct accel_calibration_s
struct gyro_calibration_s
Public Member Functions
DfMPU6050Wrapper (enum Rotation rotation)
~DfMPU6050Wrapper ()
int start ()
Start automatic measurement.
int stop ()
Stop automatic measurement.
void info ()
Print some debug info.
Private Member Functions
int _publish (struct imu_sensor_data &data)
void _update_accel_calibration ()
void _update_gyro_calibration ()
Private Attributes
orb_advert_t _accel_topic
orb_advert_t _gyro_topic
orb_advert_t _mavlink_log_pub
int _param_update_sub
struct DfMPU6050Wrapper::accel_calibration_s _accel_calibration
struct DfMPU6050Wrapper::gyro_calibration_s _gyro_calibration
matrix::Dcmf _rotation_matrix
int _accel_orb_class_instance
int _gyro_orb_class_instance
Integrator _accel_int
Integrator _gyro_int
unsigned _publish_count
perf_counter_t _read_counter
perf_counter_t _error_counter
perf_counter_t _fifo_overflow_counter
perf_counter_t _fifo_corruption_counter
perf_counter_t _gyro_range_hit_counter
perf_counter_t _accel_range_hit_counter
perf_counter_t _publish_perf
hrt_abstime _last_accel_range_hit_time
uint64_t _last_accel_range_hit_count
Detailed Description
Definition at line 77 of file df_mpu6050_wrapper.cpp.
Constructor & Destructor Documentation
DfMPU6050Wrapper::DfMPU6050Wrapper (enum Rotation rotation)
Definition at line 157 of file df_mpu6050_wrapper.cpp.
References _accel_calibration, _accel_int, _accel_orb_class_instance, _accel_range_hit_counter, _error_counter, _fifo_corruption_counter, _fifo_overflow_counter, _gyro_calibration, _gyro_int, _gyro_orb_class_instance, _gyro_range_hit_counter, _last_accel_range_hit_count, _last_accel_range_hit_time, _publish_count, _publish_perf, _read_counter, _rotation_matrix, get_rot_matrix(), MPU6050_NEVER_AUTOPUBLISH_US, PC_COUNT, PC_ELAPSED, perf_alloc, DfMPU6050Wrapper::accel_calibration_s::x_offset, DfMPU6050Wrapper::gyro_calibration_s::x_offset, DfMPU6050Wrapper::accel_calibration_s::x_scale, DfMPU6050Wrapper::gyro_calibration_s::x_scale, DfMPU6050Wrapper::accel_calibration_s::y_offset, DfMPU6050Wrapper::gyro_calibration_s::y_offset, DfMPU6050Wrapper::accel_calibration_s::y_scale, DfMPU6050Wrapper::gyro_calibration_s::y_scale, DfMPU6050Wrapper::accel_calibration_s::z_offset, DfMPU6050Wrapper::gyro_calibration_s::z_offset, DfMPU6050Wrapper::accel_calibration_s::z_scale, and DfMPU6050Wrapper::gyro_calibration_s::z_scale.
Referenced by df_mpu6050_wrapper::start().
DfMPU6050Wrapper::~DfMPU6050Wrapper ()
Definition at line 199 of file df_mpu6050_wrapper.cpp.
References _accel_range_hit_counter, _error_counter, _fifo_corruption_counter, _fifo_overflow_counter, _gyro_range_hit_counter, _publish_perf, _read_counter, and perf_free().
Member Function Documentation
int DfMPU6050Wrapper::_publish (struct imu_sensor_data & data) private
Definition at line 418 of file df_mpu6050_wrapper.cpp.
References _accel_calibration, _accel_int, _accel_orb_class_instance, _accel_range_hit_counter, _accel_topic, _error_counter, _fifo_corruption_counter, _fifo_overflow_counter, _gyro_calibration, _gyro_int, _gyro_orb_class_instance, _gyro_range_hit_counter, _gyro_topic, _last_accel_range_hit_count, _last_accel_range_hit_time, _mavlink_log_pub, _param_update_sub, _publish_count, _publish_perf, _read_counter, _rotation_matrix, _update_accel_calibration(), _update_gyro_calibration(), accel_report, Integrator::get_and_filtered(), gyro_report, hrt_absolute_time(), hrt_elapsed_time(), mavlink_log_critical, orb_advertise_multi(), orb_check(), orb_copy(), ORB_ID, ORB_PRIO_DEFAULT, orb_publish(), perf_begin(), perf_end(), perf_set_count(), Integrator::put(), DfMPU6050Wrapper::accel_calibration_s::x_offset, DfMPU6050Wrapper::gyro_calibration_s::x_offset, DfMPU6050Wrapper::accel_calibration_s::x_scale, DfMPU6050Wrapper::gyro_calibration_s::x_scale, DfMPU6050Wrapper::accel_calibration_s::y_offset, DfMPU6050Wrapper::gyro_calibration_s::y_offset, DfMPU6050Wrapper::accel_calibration_s::y_scale, DfMPU6050Wrapper::gyro_calibration_s::y_scale, DfMPU6050Wrapper::accel_calibration_s::z_offset, DfMPU6050Wrapper::gyro_calibration_s::z_offset, DfMPU6050Wrapper::accel_calibration_s::z_scale, and DfMPU6050Wrapper::gyro_calibration_s::z_scale.
void DfMPU6050Wrapper::_update_accel_calibration () private
Definition at line 342 of file df_mpu6050_wrapper.cpp.
References _accel_calibration, device_id, OK, param_find(), param_get(), PX4_ERR, DfMPU6050Wrapper::accel_calibration_s::x_offset, DfMPU6050Wrapper::accel_calibration_s::x_scale, DfMPU6050Wrapper::accel_calibration_s::y_offset, DfMPU6050Wrapper::accel_calibration_s::y_scale, DfMPU6050Wrapper::accel_calibration_s::z_offset, and DfMPU6050Wrapper::accel_calibration_s::z_scale.
Referenced by _publish(), and start().
void DfMPU6050Wrapper::_update_gyro_calibration () private
Definition at line 267 of file df_mpu6050_wrapper.cpp.
References _gyro_calibration, device_id, OK, param_find(), param_get(), PX4_ERR, DfMPU6050Wrapper::gyro_calibration_s::x_offset, DfMPU6050Wrapper::gyro_calibration_s::x_scale, DfMPU6050Wrapper::gyro_calibration_s::y_offset, DfMPU6050Wrapper::gyro_calibration_s::y_scale, DfMPU6050Wrapper::gyro_calibration_s::z_offset, and DfMPU6050Wrapper::gyro_calibration_s::z_scale.
Referenced by _publish(), and start().
void DfMPU6050Wrapper::info ()
Print some debug info.
Definition at line 255 of file df_mpu6050_wrapper.cpp.
References _accel_range_hit_counter, _error_counter, _fifo_corruption_counter, _fifo_overflow_counter, _gyro_range_hit_counter, _publish_perf, _read_counter, and perf_print_counter().
Referenced by df_mpu6050_wrapper::info().
int DfMPU6050Wrapper::start ()
Start automatic measurement.
Returns
0 on success
Definition at line 211 of file df_mpu6050_wrapper.cpp.
References _param_update_sub, _update_accel_calibration(), _update_gyro_calibration(), lis3mdl::init(), ORB_ID, orb_subscribe(), PX4_DEBUG, PX4_ERR, and start().
Referenced by df_mpu6050_wrapper::start().
int DfMPU6050Wrapper::stop ()
Stop automatic measurement.
Returns
0 on success
Definition at line 242 of file df_mpu6050_wrapper.cpp.
References PX4_ERR, and stop().
Referenced by df_mpu6050_wrapper::stop().
Member Data Documentation
struct DfMPU6050Wrapper::accel_calibration_s DfMPU6050Wrapper::_accel_calibration private
Referenced by _publish(), _update_accel_calibration(), and DfMPU6050Wrapper().
Integrator DfMPU6050Wrapper::_accel_int private
Definition at line 139 of file df_mpu6050_wrapper.cpp.
Referenced by _publish(), and DfMPU6050Wrapper().
int DfMPU6050Wrapper::_accel_orb_class_instance private
Definition at line 136 of file df_mpu6050_wrapper.cpp.
Referenced by _publish(), and DfMPU6050Wrapper().
perf_counter_t DfMPU6050Wrapper::_accel_range_hit_counter private
Definition at line 149 of file df_mpu6050_wrapper.cpp.
Referenced by _publish(), DfMPU6050Wrapper(), info(), and ~DfMPU6050Wrapper().
orb_advert_t DfMPU6050Wrapper::_accel_topic private
Definition at line 109 of file df_mpu6050_wrapper.cpp.
Referenced by _publish().
perf_counter_t DfMPU6050Wrapper::_error_counter private
Definition at line 145 of file df_mpu6050_wrapper.cpp.
Referenced by _publish(), DfMPU6050Wrapper(), info(), and ~DfMPU6050Wrapper().
perf_counter_t DfMPU6050Wrapper::_fifo_corruption_counter private
Definition at line 147 of file df_mpu6050_wrapper.cpp.
Referenced by _publish(), DfMPU6050Wrapper(), info(), and ~DfMPU6050Wrapper().
perf_counter_t DfMPU6050Wrapper::_fifo_overflow_counter private
Definition at line 146 of file df_mpu6050_wrapper.cpp.
Referenced by _publish(), DfMPU6050Wrapper(), info(), and ~DfMPU6050Wrapper().
struct DfMPU6050Wrapper::gyro_calibration_s DfMPU6050Wrapper::_gyro_calibration private
Referenced by _publish(), _update_gyro_calibration(), and DfMPU6050Wrapper().
Integrator DfMPU6050Wrapper::_gyro_int private
Definition at line 140 of file df_mpu6050_wrapper.cpp.
Referenced by _publish(), and DfMPU6050Wrapper().
int DfMPU6050Wrapper::_gyro_orb_class_instance private
Definition at line 137 of file df_mpu6050_wrapper.cpp.
Referenced by _publish(), and DfMPU6050Wrapper().
perf_counter_t DfMPU6050Wrapper::_gyro_range_hit_counter private
Definition at line 148 of file df_mpu6050_wrapper.cpp.
Referenced by _publish(), DfMPU6050Wrapper(), info(), and ~DfMPU6050Wrapper().
orb_advert_t DfMPU6050Wrapper::_gyro_topic private
Definition at line 110 of file df_mpu6050_wrapper.cpp.
Referenced by _publish().
uint64_t DfMPU6050Wrapper::_last_accel_range_hit_count private
Definition at line 153 of file df_mpu6050_wrapper.cpp.
Referenced by _publish(), and DfMPU6050Wrapper().
hrt_abstime DfMPU6050Wrapper::_last_accel_range_hit_time private
Definition at line 152 of file df_mpu6050_wrapper.cpp.
Referenced by _publish(), and DfMPU6050Wrapper().
orb_advert_t DfMPU6050Wrapper::_mavlink_log_pub private
Definition at line 112 of file df_mpu6050_wrapper.cpp.
Referenced by _publish().
int DfMPU6050Wrapper::_param_update_sub private
Definition at line 114 of file df_mpu6050_wrapper.cpp.
Referenced by _publish(), and start().
unsigned DfMPU6050Wrapper::_publish_count private
Definition at line 142 of file df_mpu6050_wrapper.cpp.
Referenced by _publish(), and DfMPU6050Wrapper().
perf_counter_t DfMPU6050Wrapper::_publish_perf private
Definition at line 150 of file df_mpu6050_wrapper.cpp.
Referenced by _publish(), DfMPU6050Wrapper(), info(), and ~DfMPU6050Wrapper().
perf_counter_t DfMPU6050Wrapper::_read_counter private
Definition at line 144 of file df_mpu6050_wrapper.cpp.
Referenced by _publish(), DfMPU6050Wrapper(), info(), and ~DfMPU6050Wrapper().
matrix::Dcmf DfMPU6050Wrapper::_rotation_matrix private
Definition at line 134 of file df_mpu6050_wrapper.cpp.
Referenced by _publish(), and DfMPU6050Wrapper().
The documentation for this class was generated from the following file:
src/platforms/posix/drivers/df_mpu6050_wrapper/df_mpu6050_wrapper.cpp