PX4 Firmware: GYROSIM Class Reference
GYROSIM Class Reference
Classes
struct MPUReport
Report conversation within the GYROSIM, including command byte and interrupt status.
Public Member Functions
GYROSIM (const char *path_accel, const char *path_gyro, enum Rotation rotation)
virtual ~GYROSIM ()
int init ()
virtual int start ()
virtual ssize_t devRead (void *buffer, size_t buflen)
virtual int devIOCTL (unsigned long cmd, unsigned long arg)
int transfer (uint8_t *send, uint8_t *recv, unsigned len)
void print_info ()
Diagnostics - print some basic information about the driver.
void print_registers ()
Protected Member Functions
virtual ssize_t gyro_read (void *buffer, size_t buflen)
virtual int gyro_ioctl (unsigned long cmd, unsigned long arg)
Private Member Functions
int reset ()
Reset chip.
virtual void _measure ()
Fetch measurements from the sensor and update the report buffers.
uint8_t read_reg (unsigned reg)
Read a register from the GYROSIM.
void write_reg (unsigned reg, uint8_t value)
Write a register in the GYROSIM.
int set_accel_range (unsigned max_g)
Set the GYROSIM measurement range.
uint16_t swap16 (uint16_t val)
Swap a 16-bit value read from the GYROSIM to native byte order.
int self_test ()
Measurement self test.
void _set_sample_rate (unsigned desired_sample_rate_hz)
GYROSIM (const GYROSIM &)=delete
GYROSIM operator= (const GYROSIM &)=delete
Private Attributes
GYROSIM_gyro * _gyro
uint8_t _product
unsigned _call_interval
product code
ringbuffer::RingBuffer * _accel_reports
struct accel_calibration_s _accel_scale
float _accel_range_scale
float _accel_range_m_s2
orb_advert_t _accel_topic
int _accel_orb_class_instance
ringbuffer::RingBuffer * _gyro_reports
struct gyro_calibration_s _gyro_scale
float _gyro_range_scale
float _gyro_range_rad_s
perf_counter_t _accel_reads
perf_counter_t _gyro_reads
perf_counter_t _sample_perf
perf_counter_t _good_transfers
perf_counter_t _reset_retries
Integrator _accel_int
Integrator _gyro_int
float _last_temperature
uint8_t _regdata [108]
bool _pub_blocked = true
Friends
class GYROSIM_gyro
Detailed Description
Definition at line 119 of file gyrosim.cpp.
Constructor & Destructor Documentation
GYROSIM::GYROSIM (const char * path_accel, const char * path_gyro, enum Rotation rotation)
Definition at line 288 of file gyrosim.cpp.
References _accel_int, _accel_orb_class_instance, _accel_range_m_s2, _accel_range_scale, _accel_reads, _accel_scale, _accel_topic, _good_transfers, _gyro, _gyro_int, _gyro_range_rad_s, _gyro_range_scale, _gyro_reads, _gyro_reports, _gyro_scale, _last_temperature, _reset_retries, _sample_perf, DRV_ACC_DEVTYPE_GYROSIM, DRV_GYR_DEVTYPE_GYROSIM, f(), GYROSIM_ACCEL_DEFAULT_RATE, GYROSIM_GYRO_DEFAULT_RATE, PC_COUNT, PC_ELAPSED, perf_alloc, gyro_calibration_s::x_offset, accel_calibration_s::x_offset, accel_calibration_s::x_scale, gyro_calibration_s::x_scale, accel_calibration_s::y_offset, gyro_calibration_s::y_offset, gyro_calibration_s::y_scale, accel_calibration_s::y_scale, gyro_calibration_s::z_offset, accel_calibration_s::z_offset, gyro_calibration_s::z_scale, and accel_calibration_s::z_scale.
GYROSIM::~GYROSIM () virtual
Definition at line 336 of file gyrosim.cpp.
References _accel_reads, _accel_reports, _good_transfers, _gyro, _gyro_reads, _gyro_reports, _sample_perf, perf_free(), and stop().
GYROSIM::GYROSIM (const GYROSIM &) private delete
Member Function Documentation
void GYROSIM::_measure (void) private virtual
Fetch measurements from the sensor and update the report buffers.
Definition at line 883 of file gyrosim.cpp.
References _accel_int, _accel_range_scale, _accel_reports, _accel_topic, _gyro, _gyro_int, _gyro_range_scale, _gyro_reports, GYROSIM_gyro::_gyro_topic, _last_temperature, _pub_blocked, _sample_perf, accel_report, GYROSIM::MPUReport::accel_x, GYROSIM::MPUReport::accel_y, GYROSIM::MPUReport::accel_z, GYROSIM::MPUReport::cmd, DIR_READ, gyro_report, GYROSIM::MPUReport::gyro_x, GYROSIM::MPUReport::gyro_y, GYROSIM::MPUReport::gyro_z, hrt_absolute_time(), MPUREG_INT_STATUS, OK, ORB_ID, orb_publish(), perf_begin(), perf_end(), Integrator::put(), PX4_INFO, GYROSIM::MPUReport::temp, and transfer().
Referenced by devRead(), gyro_read(), init(), and self_test().
void GYROSIM::_set_sample_rate (unsigned desired_sample_rate_hz) private
Definition at line 511 of file gyrosim.cpp.
References _gyro, ACCEL_SAMPLERATE_DEFAULT, GYRO_SAMPLERATE_DEFAULT, GYROSIM_GYRO_DEFAULT_RATE, MPUREG_SMPLRT_DIV, PX4_DEBUG, and write_reg().
Referenced by devIOCTL(), and gyro_ioctl().
int GYROSIM::devIOCTL (unsigned long cmd, unsigned long arg) virtual
Definition at line 629 of file gyrosim.cpp.
References _accel_range_m_s2, _accel_reports, _accel_scale, _call_interval, _set_sample_rate(), ACCELIOCGRANGE, ACCELIOCGSAMPLERATE, ACCELIOCGSCALE, ACCELIOCSRANGE, ACCELIOCSSAMPLERATE, ACCELIOCSSCALE, CONSTANTS_ONE_G, f(), GYROSIM_ACCEL_DEFAULT_RATE, OK, reset(), SENSOR_POLLRATE_DEFAULT, SENSOR_POLLRATE_EXTERNAL, SENSOR_POLLRATE_MANUAL, SENSOR_POLLRATE_MAX, SENSORIOCGPOLLRATE, SENSORIOCRESET, SENSORIOCSPOLLRATE, SENSORIOCSQUEUEDEPTH, set_accel_range(), start(), stop(), accel_calibration_s::x_scale, accel_calibration_s::y_scale, and accel_calibration_s::z_scale.
Referenced by gyro_ioctl().
ssize_t GYROSIM::devRead (void * buffer, size_t buflen) virtual
Definition at line 538 of file gyrosim.cpp.
References _accel_reads, _accel_reports, _call_interval, _measure(), accel_report, and perf_count().
int GYROSIM::gyro_ioctl (unsigned long cmd, unsigned long arg) protected virtual
Definition at line 745 of file gyrosim.cpp.
References _gyro_range_rad_s, _gyro_reports, _gyro_scale, _set_sample_rate(), devIOCTL(), GYROIOCGRANGE, GYROIOCGSAMPLERATE, GYROIOCGSCALE, GYROIOCSRANGE, GYROIOCSSAMPLERATE, GYROIOCSSCALE, M_PI_F, OK, SENSORIOCGPOLLRATE, SENSORIOCRESET, SENSORIOCSPOLLRATE, and SENSORIOCSQUEUEDEPTH.
Referenced by GYROSIM_gyro::devIOCTL().
ssize_t GYROSIM::gyro_read (void * buffer, size_t buflen) protected virtual
Definition at line 589 of file gyrosim.cpp.
References _call_interval, _gyro_reads, _gyro_reports, _measure(), gyro_report, and perf_count().
Referenced by GYROSIM_gyro::devRead().
int GYROSIM::init ()
Definition at line 361 of file gyrosim.cpp.
References _accel_orb_class_instance, _accel_reports, _accel_scale, _accel_topic, _gyro, GYROSIM_gyro::_gyro_orb_class_instance, _gyro_reports, _gyro_scale, GYROSIM_gyro::_gyro_topic, _measure(), _pub_blocked, accel_report, gyro_report, lis3mdl::init(), GYROSIM_gyro::init(), OK, orb_advertise_multi(), ORB_ID, ORB_PRIO_HIGH, PX4_DEBUG, PX4_ERR, PX4_WARN, reset(), start(), gyro_calibration_s::x_offset, accel_calibration_s::x_offset, gyro_calibration_s::x_scale, accel_calibration_s::x_scale, gyro_calibration_s::y_offset, accel_calibration_s::y_offset, gyro_calibration_s::y_scale, accel_calibration_s::y_scale, accel_calibration_s::z_offset, gyro_calibration_s::z_offset, accel_calibration_s::z_scale, and gyro_calibration_s::z_scale.
GYROSIM GYROSIM::operator= (const GYROSIM &) private delete
void GYROSIM::print_info (void)
Diagnostics - print some basic information about the driver.
Definition at line 1019 of file gyrosim.cpp.
References _accel_reads, _accel_reports, _good_transfers, _gyro_reads, _gyro_reports, _last_temperature, _reset_retries, _sample_perf, perf_print_counter(), and PX4_INFO.
void GYROSIM::print_registers ()
Definition at line 1032 of file gyrosim.cpp.
References MPUREG_PRODUCT_ID, PX4_INFO, and read_reg().
uint8_t GYROSIM::read_reg (unsigned reg) private
Read a register from the GYROSIM.
Parameters
The register to read.
Returns
The value that was read.
Definition at line 802 of file gyrosim.cpp.
References DIR_READ, and transfer().
Referenced by print_registers().
int GYROSIM::reset (void) private
Reset chip.
Resets the chip and measurements ranges, but not scale and offset.
Definition at line 463 of file gyrosim.cpp.
References OK.
Referenced by devIOCTL(), and init().
int GYROSIM::self_test (void) private
Measurement self test.
Returns
0 on success, 1 on failure
Definition at line 578 of file gyrosim.cpp.
References _measure(), _sample_perf, and perf_event_count().
int GYROSIM::set_accel_range (unsigned max_g) private
Set the GYROSIM measurement range.
Parameters
max_g The maximum G value the range must support.
Returns
OK if the value can be supported, -ERANGE otherwise.
Definition at line 825 of file gyrosim.cpp.
References _accel_range_m_s2, _accel_range_scale, _product, CONSTANTS_ONE_G, GYROSIMES_REV_C4, MPUREG_ACCEL_CONFIG, OK, and write_reg().
Referenced by devIOCTL().
int GYROSIM::start () virtual
Definition at line 869 of file gyrosim.cpp.
References _accel_reports, _gyro_reports, start(), and stop().
Referenced by devIOCTL(), and init().
uint16_t GYROSIM::swap16 (uint16_t val) inline private
Swap a 16-bit value read from the GYROSIM to native byte order.
Definition at line 216 of file gyrosim.cpp.
int GYROSIM::transfer (uint8_t * send, uint8_t * recv, unsigned len)
Definition at line 469 of file gyrosim.cpp.
References _regdata, DIR_READ, Simulator::getInstance(), Simulator::getMPUReport(), MPUREG_INT_STATUS, MPUREG_PRODUCT_ID, PX4_DEBUG, PX4_OK, and PX4_WARN.
Referenced by _measure(), read_reg(), and write_reg().
void GYROSIM::write_reg (unsigned reg, uint8_t value) private
Write a register in the GYROSIM.
Parameters
reg The register to write.
value The new value to write.
Definition at line 813 of file gyrosim.cpp.
References DIR_WRITE, and transfer().
Referenced by _set_sample_rate(), and set_accel_range().
Friends And Related Function Documentation
friend class GYROSIM_gyro friend
Definition at line 140 of file gyrosim.cpp.
Member Data Documentation
Integrator GYROSIM::_accel_int private
Definition at line 171 of file gyrosim.cpp.
Referenced by _measure(), and GYROSIM().
int GYROSIM::_accel_orb_class_instance private
Definition at line 157 of file gyrosim.cpp.
Referenced by GYROSIM(), and init().
float GYROSIM::_accel_range_m_s2 private
Definition at line 155 of file gyrosim.cpp.
Referenced by devIOCTL(), GYROSIM(), and set_accel_range().
float GYROSIM::_accel_range_scale private
Definition at line 154 of file gyrosim.cpp.
Referenced by _measure(), GYROSIM(), and set_accel_range().
perf_counter_t GYROSIM::_accel_reads private
Definition at line 165 of file gyrosim.cpp.
Referenced by devRead(), GYROSIM(), print_info(), and ~GYROSIM().
ringbuffer::RingBuffer* GYROSIM::_accel_reports private
Definition at line 151 of file gyrosim.cpp.
Referenced by _measure(), devIOCTL(), devRead(), init(), print_info(), start(), and ~GYROSIM().
struct accel_calibration_s GYROSIM::_accel_scale private
Definition at line 153 of file gyrosim.cpp.
Referenced by devIOCTL(), GYROSIM(), and init().
orb_advert_t GYROSIM::_accel_topic private
Definition at line 156 of file gyrosim.cpp.
Referenced by _measure(), GYROSIM(), and init().
unsigned GYROSIM::_call_interval private
product code
Definition at line 149 of file gyrosim.cpp.
Referenced by devIOCTL(), devRead(), and gyro_read().
perf_counter_t GYROSIM::_good_transfers private
Definition at line 168 of file gyrosim.cpp.
Referenced by GYROSIM(), print_info(), and ~GYROSIM().
GYROSIM_gyro* GYROSIM::_gyro private
Definition at line 146 of file gyrosim.cpp.
Referenced by _measure(), _set_sample_rate(), GYROSIM(), init(), and ~GYROSIM().
Integrator GYROSIM::_gyro_int private
Definition at line 172 of file gyrosim.cpp.
Referenced by _measure(), and GYROSIM().
float GYROSIM::_gyro_range_rad_s private
Definition at line 163 of file gyrosim.cpp.
Referenced by gyro_ioctl(), and GYROSIM().
float GYROSIM::_gyro_range_scale private
Definition at line 162 of file gyrosim.cpp.
Referenced by _measure(), and GYROSIM().
perf_counter_t GYROSIM::_gyro_reads private
Definition at line 166 of file gyrosim.cpp.
Referenced by gyro_read(), GYROSIM(), print_info(), and ~GYROSIM().
ringbuffer::RingBuffer* GYROSIM::_gyro_reports private
Definition at line 159 of file gyrosim.cpp.
Referenced by _measure(), gyro_ioctl(), gyro_read(), GYROSIM(), init(), print_info(), start(), and ~GYROSIM().
struct gyro_calibration_s GYROSIM::_gyro_scale private
Definition at line 161 of file gyrosim.cpp.
Referenced by gyro_ioctl(), GYROSIM(), and init().
float GYROSIM::_last_temperature private
Definition at line 175 of file gyrosim.cpp.
Referenced by _measure(), GYROSIM(), and print_info().
uint8_t GYROSIM::_product private
Definition at line 147 of file gyrosim.cpp.
Referenced by set_accel_range().
bool GYROSIM::_pub_blocked = true private
Definition at line 254 of file gyrosim.cpp.
Referenced by _measure(), and init().
uint8_t GYROSIM::_regdata[108] private
Definition at line 252 of file gyrosim.cpp.
Referenced by transfer().
perf_counter_t GYROSIM::_reset_retries private
Definition at line 169 of file gyrosim.cpp.
Referenced by GYROSIM(), and print_info().
perf_counter_t GYROSIM::_sample_perf private
Definition at line 167 of file gyrosim.cpp.
Referenced by _measure(), GYROSIM(), print_info(), self_test(), and ~GYROSIM().
The documentation for this class was generated from the following file:
src/modules/simulator/gyrosim/gyrosim.cpp