PX4 Firmware: MicroBenchHRT Namespace Reference
MicroBenchHRT Namespace Reference
Classes
class MicroBenchHRT
Functions
void lock ()
void unlock ()
template<typename T >
T random (T min, T max)
ut_declare_test_c (test_microbench_hrt, MicroBenchHRT) bool MicroBenchHRT
Function Documentation
lock()
void MicroBenchHRT::lock ()
Definition at line 58 of file test_microbench_hrt.cpp.
Referenced by VirtualCanIface::addRxFrame(), uavcan_stm32::CanIface::canAcceptNewTxFrame(), uavcan_kinetis::CanIface::canAcceptNewTxFrame(), uavcan_stm32::CanIface::configureFilters(), uavcan_kinetis::CanIface::configureFilters(), uavcan_stm32::CanIface::discardTimedOutTxMailboxes(), uavcan_kinetis::CanIface::discardTimedOutTxMailboxes(), VirtualCanIface::flushTxQueueTo(), uavcan_stm32::CanIface::getErrorCount(), uavcan_kinetis::CanIface::getErrorCount(), uavcan_stm32::CanIface::getRxQueueLength(), uavcan_kinetis::CanIface::getRxQueueLength(), uavcan_stm32::CanIface::hadActivity(), uavcan_kinetis::CanIface::hadActivity(), VirtualCanIface::hasDataInRxQueue(), uavcan_stm32::CanIface::init(), uavcan_stm32::CanDriver::initOnce(), uavcan_kinetis::CanDriver::initOnce(), uavcan_stm32::CanIface::isRxBufferEmpty(), uavcan_kinetis::CanIface::isRxBufferEmpty(), MK::pwm_ioctl(), uavcan_stm32::CanIface::receive(), uavcan_kinetis::CanIface::receive(), VirtualCanIface::receive(), UavcanServers::run(), UavcanNode::run(), uavcan_stm32::CanIface::send(), uavcan_kinetis::CanIface::send(), VirtualCanIface::send(), and uavcan_kinetis::CanIface::setFreeze().
random()
template<typename T > T MicroBenchHRT::random (T min, T max)
Definition at line 125 of file test_microbench_hrt.cpp.
References math::min().
unlock()
void MicroBenchHRT::unlock ()
Definition at line 65 of file test_microbench_hrt.cpp.
Referenced by MK::pwm_ioctl(), and UavcanNode::run().
ut_declare_test_c()
MicroBenchHRT::ut_declare_test_c (test_microbench_hrt , MicroBenchHRT)
Definition at line 140 of file test_microbench_hrt.cpp.
References hrt_absolute_time(), hrt_elapsed_time_atomic(), and PERF.