PX4 Firmware: cm8jl65 Namespace Reference
cm8jl65 Namespace Reference
Local functions in support of the shell command.
Functions
int reset (const char *port)
Reset the driver.
int start (const char *port, const uint8_t rotation)
Start the driver.
int status ()
Print the driver status.
int stop ()
Stop the driver.
int usage ()
Prints info about the driver argument usage.
Variables
CM8JL65 * g_dev
Detailed Description
Local functions in support of the shell command.
Function Documentation
reset()
int cm8jl65::reset (const char * port)
Reset the driver.
Definition at line 57 of file cm8jl65_main.cpp.
References start(), and stop().
Referenced by cm8jl65_main().
start()
int cm8jl65::start (const char * port, const uint8_t rotation = distance_sensor_s::ROTATION_DOWNWARD_FACING)
Start the driver.
Definition at line 70 of file cm8jl65_main.cpp.
References g_dev, and CM8JL65::init().
Referenced by cm8jl65_main(), and reset().
status()
int cm8jl65::status ()
Print the driver status.
Definition at line 104 of file cm8jl65_main.cpp.
References CM8JL65::print_info().
Referenced by cm8jl65_main().
stop()
int cm8jl65::stop ()
Stop the driver.
Definition at line 119 of file cm8jl65_main.cpp.
References g_dev.
Referenced by cm8jl65_main(), and reset().
usage()
int cm8jl65::usage (void)
Prints info about the driver argument usage.
Definition at line 130 of file cm8jl65_main.cpp.
Referenced by cm8jl65_main().
Variable Documentation
g_dev
CM8JL65* cm8jl65::g_dev
Definition at line 45 of file cm8jl65_main.cpp.
Referenced by start(), and stop().