PX4 Firmware: src/lib/ecl/test/test_EKF_imuSampling.cpp File Reference
test_EKF_imuSampling.cpp File Reference
#include <gtest/gtest.h>
#include <math.h>
#include "EKF/ekf.h"
Classes
class EkfSamplingTestParametrized
Functions
TEST_P (EkfSamplingTestParametrized, imuSamplingAtMultipleRates)
INSTANTIATE_TEST_CASE_P (imuSamplingAtMultipleRates, EkfSamplingTestParametrized, ::testing::Values(std::make_tuple< float, float >(1.0f, 1.0f), std::make_tuple< float, float >(1.6f, 1.6f), std::make_tuple< float, float >(0.333f, 1.0f)))
Function Documentation
INSTANTIATE_TEST_CASE_P()
INSTANTIATE_TEST_CASE_P (imuSamplingAtMultipleRates , EkfSamplingTestParametrized , ::testing::Values(std::make_tuple< float, float >(1.0f, 1.0f), std::make_tuple< float, float >(1.6f, 1.6f), std::make_tuple< float, float >(0.333f, 1.0f)))
Referenced by TEST_P().
TEST_P()
TEST_P (EkfSamplingTestParametrized , imuSamplingAtMultipleRates)
Definition at line 59 of file test_EKF_imuSampling.cpp.
References EkfSamplingTestParametrized::_ekf, EkfSamplingTestParametrized::_t_us, estimator::imuSample::delta_ang, estimator::imuSample::delta_ang_dt, estimator::imuSample::delta_vel, estimator::imuSample::delta_vel_dt, f(), EstimatorInterface::FILTER_UPDATE_PERIOD_MS, EstimatorInterface::get_imu_sample_delayed(), INSTANTIATE_TEST_CASE_P(), EstimatorInterface::setIMUData(), and estimator::imuSample::time_us.