PX4 Firmware: control::Block Class Reference
control::Block Class Reference
#include <Block.hpp>
Public Member Functions
Block (SuperBlock *parent, const char *name)
virtual ~Block ()=default
Block (const Block &)=delete
Block & operator= (const Block &)=delete
Block (Block &&)=delete
Block & operator= (Block &&)=delete
void getName (char *name, size_t n)
virtual void updateParams ()
virtual void setDt (float dt)
float getDt ()
Public Member Functions inherited from ListNode< Block *>
void setSibling (Block * sibling)
const Block * getSibling () const
Protected Member Functions
virtual void updateParamsSubclass ()
SuperBlock * getParent ()
List< BlockParamBase * > & getParams ()
Protected Attributes
const char * _name
SuperBlock * _parent
float _dt {0.0f}
List< BlockParamBase * > _params
Protected Attributes inherited from ListNode< Block *>
Block * _list_node_sibling
Friends
class BlockParamBase
Detailed Description
Definition at line 59 of file Block.hpp.
Constructor & Destructor Documentation
Block() [1/3]
control::Block::Block (SuperBlock * parent, const char * name)
Definition at line 48 of file Block.cpp.
References control::SuperBlock::getChildren(), and getParent().
~Block()
virtual control::Block::~Block () virtual default
Block() [2/3]
control::Block::Block (const Block &) delete
Block() [3/3]
control::Block::Block (Block &&) delete
Member Function Documentation
getDt()
float control::Block::getDt () inline
Definition at line 78 of file Block.hpp.
Referenced by control::blockDerivativeTest(), blockDerivativeTest(), blockHighPassTest(), control::blockHighPassTest(), control::blockIntegralTest(), blockIntegralTest(), control::blockIntegralTrapTest(), blockIntegralTrapTest(), control::blockLimitSymTest(), blockLimitSymTest(), blockLimitTest(), control::blockLimitTest(), control::blockLowPass2Test(), blockLowPass2Test(), control::blockLowPassTest(), blockLowPassTest(), blockOutputTest(), control::blockOutputTest(), control::blockPDTest(), blockPDTest(), control::blockPIDTest(), blockPIDTest(), control::blockPITest(), blockPITest(), blockPTest(), control::blockPTest(), control::blockRandGaussTest(), blockRandGaussTest(), control::blockRandUniformTest(), blockRandUniformTest(), BlockLocalPositionEstimator::predict(), control::BlockIntegral::update(), control::BlockHighPass::update(), control::BlockLowPass::update(), control::BlockIntegralTrap::update(), and control::BlockDerivative::update().
getName()
void control::Block::getName (char * name, size_t n)
Definition at line 57 of file Block.cpp.
References _name, control::blockNameLengthMax, getName(), and getParent().
Referenced by control::BlockParamBase::BlockParamBase(), getName(), control::SuperBlock::setDt(), control::SuperBlock::updateChildParams(), and updateParams().
getParams()
List<BlockParamBase *>& control::Block::getParams () inline protected
Definition at line 85 of file Block.hpp.
Referenced by control::BlockParamBase::BlockParamBase(), and updateParams().
getParent()
SuperBlock* control::Block::getParent () inline protected
Definition at line 84 of file Block.hpp.
Referenced by Block(), and getName().
operator=() [1/2]
Block& control::Block::operator= (const Block &) delete
operator=() [2/2]
Block& control::Block::operator= (Block &&) delete
setDt()
virtual void control::Block::setDt (float dt) inline virtual
Reimplemented in control::SuperBlock.
Definition at line 77 of file Block.hpp.
References dt.
Referenced by control::blockHighPassTest(), blockHighPassTest(), control::blockLowPass2Test(), blockLowPass2Test(), control::blockLowPassTest(), blockLowPassTest(), blockPTest(), control::blockPTest(), and control::SuperBlock::setDt().
updateParams()
void control::Block::updateParams () virtual
Reimplemented in control::SuperBlock.
Definition at line 79 of file Block.cpp.
References control::blockNameLengthMax, getName(), getParams(), ListNode< T >::getSibling(), control::maxParamsPerBlock, name, control::BlockParamBase::update(), and updateParamsSubclass().
Referenced by control::SuperBlock::updateChildParams(), and control::SuperBlock::updateParams().
updateParamsSubclass()
virtual void control::Block::updateParamsSubclass () inline protected virtual
Definition at line 82 of file Block.hpp.
Referenced by updateParams().
Friends And Related Function Documentation
BlockParamBase
friend class BlockParamBase friend
Definition at line 62 of file Block.hpp.
Member Data Documentation
_dt
float control::Block::_dt {0.0f} protected
Definition at line 89 of file Block.hpp.
Referenced by MulticopterPositionControl::Run().
_name
const char* control::Block::_name protected
Definition at line 87 of file Block.hpp.
Referenced by getName().
_params
List<BlockParamBase *> control::Block::_params protected
Definition at line 91 of file Block.hpp.
_parent
SuperBlock* control::Block::_parent protected
Definition at line 88 of file Block.hpp.
The documentation for this class was generated from the following files:
src/lib/controllib/block/Block.hpp
src/lib/controllib/block/Block.cpp