PX4 Firmware: src/platforms/common/work_queue/queue.c File Reference
queue.c File Reference
#include <queue.h>
#include <stddef.h>
Functions
__EXPORT void sq_rem (sq_entry_t *node, sq_queue_t *queue)
sq_entry_t * sq_remafter (sq_entry_t *node, sq_queue_t *queue)
__EXPORT void sq_addfirst (sq_entry_t *node, sq_queue_t *queue)
Function Documentation
void sq_addfirst (sq_entry_t * node, sq_queue_t * queue)
Definition at line 87 of file queue.c.
Referenced by create_work_item(), destroy_work_item(), perf_alloc(), and sq_remafter().
void sq_rem (sq_entry_t * node, sq_queue_t * queue)
Definition at line 43 of file queue.c.
References sq_remafter().
Referenced by perf_free().
sq_entry_t * sq_remafter (sq_entry_t * node, sq_queue_t * queue)
Definition at line 67 of file queue.c.
References sq_addfirst().
Referenced by sq_rem().