PX4 Firmware: src/drivers/uavcanesc/uavcanesc_main.cpp File Reference
uavcanesc_main.cpp File Reference
#include <px4_platform_common/px4_config.h>
#include <px4_platform_common/log.h>
#include <px4_platform_common/tasks.h>
#include <cstdlib>
#include <cstring>
#include <fcntl.h>
#include <systemlib/err.h>
#include <parameters/param.h>
#include <lib/mixer/MixerGroup.hpp>
#include <version/version.h>
#include <arch/board/board.h>
#include <arch/chip/chip.h>
#include <drivers/drv_hrt.h>
#include <drivers/drv_pwm_output.h>
#include "uavcanesc_main.hpp"
#include "led.hpp"
#include "indication_controller.hpp"
#include "boot_app_shared.h"
Classes
class RestartRequestHandler
Functions
static void cb_reboot (const uavcan::TimerEvent &)
static void signal_callback (void *arg)
static void print_usage ()
__EXPORT int uavcannode_start (int argc, char *argv[])
__EXPORT int uavcanesc_main (int argc, char *argv[])
Variables
boot_app_shared_section app_descriptor_t AppDescriptor
Implements basic functionality of UAVCAN esc.
RestartRequestHandler restart_request_handler
Function Documentation
cb_reboot()
static void cb_reboot (const uavcan::TimerEvent &) static
Definition at line 233 of file uavcanesc_main.cpp.
Referenced by UavcanEsc::cb_beginfirmware_update().
print_usage()
static void print_usage (void) static
Definition at line 426 of file uavcanesc_main.cpp.
References uavcannode_start().
Referenced by uavcanesc_main().
signal_callback()
static void signal_callback (void * arg) static
Definition at line 317 of file uavcanesc_main.cpp.
Referenced by UavcanEsc::busevent_signal_trampoline(), and UavcanEsc::run().
uavcanesc_main()
int uavcanesc_main (int argc, char * argv[])
Definition at line 475 of file uavcanesc_main.cpp.
References errx, UavcanEsc::instance(), UavcanEsc::print_info(), print_usage(), and uavcannode_start().
Referenced by uavcannode_start().
uavcannode_start()
int uavcannode_start (int argc, char * argv[])
Definition at line 434 of file uavcanesc_main.cpp.
References BootLoader, bootloader_app_shared_invalidate(), bootloader_app_shared_read(), bootloader_app_shared_t::bus_speed, bootloader_app_shared_t::node_id, param_find(), param_get(), UavcanEsc::start(), and uavcanesc_main().
Referenced by print_usage(), and uavcanesc_main().
Variable Documentation
AppDescriptor
boot_app_shared_section app_descriptor_t AppDescriptor
Initial value:
= {
    .signature = {APP_DESCRIPTOR_SIGNATURE},
    .image_crc = 0,
    .image_size = 0,
    .vcs_commit = 0,
    .major_version = APP_VERSION_MAJOR,
    .minor_version = APP_VERSION_MINOR,
    .reserved = {0xff, 0xff, 0xff, 0xff, 0xff, 0xff }
}
Implements basic functionality of UAVCAN esc.
Definition at line 75 of file uavcanesc_main.cpp.
Referenced by UavcanEsc::fill_node_info().
restart_request_handler
RestartRequestHandler restart_request_handler
Referenced by RestartRequestHandler::handleRestartRequest(), and UavcanEsc::run().