PX4 Firmware: src/drivers/differential_pressure/ets/ets_airspeed.cpp File Reference
ets_airspeed.cpp File Reference
#include <cfloat>
#include <px4_config.h>
#include <drivers/device/i2c.h>
#include <systemlib/err.h>
#include <parameters/param.h>
#include <perf/perf_counter.h>
#include <px4_getopt.h>
#include <drivers/drv_airspeed.h>
#include <drivers/drv_hrt.h>
#include <drivers/device/ringbuffer.h>
#include <uORB/uORB.h>
#include <uORB/topics/differential_pressure.h>
#include <drivers/airspeed/airspeed.h>
Classes
class ETSAirspeed
Namespaces
ets_airspeed
Local functions in support of the shell command.
Macros
#define I2C_ADDRESS 0x75 /* 7-bit address. 8-bit address is 0xEA */
#define ETS_PATH "/dev/ets_airspeed"
#define READ_CMD 0x07 /* Read the data */
#define MIN_ACCURATE_DIFF_PRES_PA 0
The Eagle Tree Airspeed V3 cannot provide accurate reading below speeds of 15km/h.
#define CONVERSION_INTERVAL (1000000 / 100) /* microseconds */
Functions
__EXPORT int ets_airspeed_main (int argc, char *argv[])
int ets_airspeed::start ()
Attempt to start driver on all available I2C busses.
int ets_airspeed::start_bus (int i2c_bus)
Start the driver on a specific bus.
int ets_airspeed::stop ()
Stop the driver.
int ets_airspeed::reset ()
Reset the driver.
int ets_airspeed::info ()
Print a little info about the driver.
static void ets_airspeed_usage ()
Variables
ETSAirspeed * ets_airspeed::g_dev = nullptr
Detailed Description
Author
Simon Wilks
Driver for the Eagle Tree Airspeed V3 connected via I2C.
Author
Simon Wilks
Mark Charlebois (simulator)
Roman Bapst (simulator) Driver for the Simulated AirspeedSim Sensor based on Eagle Tree AirspeedSim V3.
Definition in file ets_airspeed.cpp.
Macro Definition Documentation
#define CONVERSION_INTERVAL (1000000 / 100) /* microseconds */
Definition at line 74 of file ets_airspeed.cpp.
Referenced by MS5525::cycle(), ETSAirspeed::cycle(), and SDP3X::cycle().
#define ETS_PATH "/dev/ets_airspeed"
Definition at line 62 of file ets_airspeed.cpp.
Referenced by pmw3901::reset().
#define I2C_ADDRESS 0x75 /* 7-bit address. 8-bit address is 0xEA */
Definition at line 61 of file ets_airspeed.cpp.
#define MIN_ACCURATE_DIFF_PRES_PA 0
The Eagle Tree Airspeed V3 cannot provide accurate reading below speeds of 15km/h.
You can set this value to 12 if you want a zero reading below 15km/h.
Definition at line 71 of file ets_airspeed.cpp.
#define READ_CMD 0x07 /* Read the data */
Definition at line 65 of file ets_airspeed.cpp.
Referenced by ETSAirspeed::measure().
Function Documentation
int ets_airspeed_main (int argc, char * argv[])
Definition at line 378 of file ets_airspeed.cpp.
References ets_airspeed_usage(), px4_getopt(), PX4_I2C_BUS_DEFAULT, ets_airspeed::reset(), ets_airspeed::start(), ets_airspeed::start_bus(), and ets_airspeed::stop().
static void ets_airspeed_usage () static
Definition at line 367 of file ets_airspeed.cpp.
References PX4_I2C_BUS_DEFAULT, and PX4_INFO.
Referenced by ets_airspeed_main().