PX4 Firmware: src/drivers/imu/adis16497/adis16497_main.cpp File Reference
adis16497_main.cpp File Reference
#include "ADIS16497.hpp"
#include <px4_platform_common/getopt.h>
Namespaces
adis16497
Functions
static int adis16497::start (enum Rotation rotation)
static int adis16497::stop ()
static int adis16497::status ()
static int adis16497::usage ()
int adis16497_main (int argc, char *argv[])
Variables
ADIS16497 * adis16497::g_dev {nullptr}
Function Documentation
adis16497_main()
int adis16497_main (int argc, char * argv[])
Definition at line 108 of file adis16497_main.cpp.
References ROTATION_NONE, adis16497::start(), adis16497::status(), adis16497::stop(), and adis16497::usage().