PX4 Firmware: src/modules/mavlink/mavlink_main.cpp File Reference
mavlink_main.cpp File Reference
MAVLink 1.0 protocol implementation.
#include <px4_config.h>
#include <px4_defines.h>
#include <px4_getopt.h>
#include <px4_module.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <stdbool.h>
#include <unistd.h>
#include <fcntl.h>
#include <errno.h>
#include <assert.h>
#include <math.h>
#include <poll.h>
#include <termios.h>
#include <time.h>
#include <sys/ioctl.h>
#include <sys/types.h>
#include <sys/stat.h>
#include <drivers/device/device.h>
#include <drivers/drv_hrt.h>
#include <arch/board/board.h>
#include <parameters/param.h>
#include <systemlib/err.h>
#include <perf/perf_counter.h>
#include <systemlib/mavlink_log.h>
#include <lib/ecl/geo/geo.h>
#include <dataman/dataman.h>
#include <version/version.h>
#include <uORB/topics/parameter_update.h>
#include <uORB/topics/vehicle_command_ack.h>
#include <uORB/topics/vehicle_command.h>
#include <uORB/topics/mavlink_log.h>
#include "mavlink_bridge_header.h"
#include "mavlink_main.h"
#include "mavlink_messages.h"
#include "mavlink_receiver.h"
#include "mavlink_rate_limiter.h"
#include "mavlink_command_sender.h"
Macros
#define DEFAULT_REMOTE_PORT_UDP 14550
GCS port per MAVLink spec.
#define DEFAULT_DEVICE_NAME "/dev/ttyS1"
#define MAX_DATA_RATE 10000000
max data rate in bytes/s
#define MAIN_LOOP_DELAY 10000
100 Hz @ 1000 bytes/s data rate
#define FLOW_CONTROL_DISABLE_THRESHOLD 40
picked so that some messages still would fit it.
#define B460800 460800
#define B500000 500000
#define B921600 921600
#define B1000000 1000000
Functions
__EXPORT int mavlink_main (int argc, char *argv[])
mavlink app start / stop handling function
void mavlink_send_uart_bytes (mavlink_channel_t chan, const uint8_t *ch, int length)
Send multiple chars (uint8_t) over a comm channel.
void mavlink_start_uart_send (mavlink_channel_t chan, int length)
void mavlink_end_uart_send (mavlink_channel_t chan, int length)
mavlink_status_t * mavlink_get_channel_status (uint8_t channel)
mavlink_message_t * mavlink_get_channel_buffer (uint8_t channel)
static void usage ()
Variables
static Mavlink * _mavlink_instances = nullptr
mavlink_system_t mavlink_system
Detailed Description
MAVLink 1.0 protocol implementation.
Author
Lorenz Meier lm@in.nosp@m.f.et.nosp@m.hz.ch
Julian Oes julia.nosp@m.n@oe.nosp@m.s.ch
Anton Babushkin anton.nosp@m..bab.nosp@m.ushki.nosp@m.n@me.nosp@m..com
Definition in file mavlink_main.cpp.
Macro Definition Documentation
#define B1000000 1000000
Referenced by Mavlink::mavlink_open_uart().
#define B460800 460800
Referenced by Mavlink::mavlink_open_uart(), and Simulator::pollForMAVLinkMessages().
#define B500000 500000
Referenced by Mavlink::mavlink_open_uart().
#define B921600 921600
Referenced by Mavlink::mavlink_open_uart(), and Simulator::pollForMAVLinkMessages().
#define DEFAULT_DEVICE_NAME "/dev/ttyS1"
Definition at line 99 of file mavlink_main.cpp.
Referenced by Mavlink::stream_command().
#define DEFAULT_REMOTE_PORT_UDP 14550
GCS port per MAVLink spec.
Definition at line 98 of file mavlink_main.cpp.
Referenced by Mavlink::Mavlink().
#define FLOW_CONTROL_DISABLE_THRESHOLD 40
picked so that some messages still would fit it.
Definition at line 102 of file mavlink_main.cpp.
Referenced by Mavlink::get_free_tx_buf().
#define MAIN_LOOP_DELAY 10000
100 Hz @ 1000 bytes/s data rate
Definition at line 101 of file mavlink_main.cpp.
Referenced by Mavlink::configure_stream_threadsafe(), and Mavlink::task_main().
#define MAX_DATA_RATE 10000000
max data rate in bytes/s
Definition at line 100 of file mavlink_main.cpp.
Referenced by Mavlink::task_main().
Function Documentation
void mavlink_end_uart_send (mavlink_channel_t chan, int length)
Definition at line 144 of file mavlink_main.cpp.
References Mavlink::get_instance(), and Mavlink::send_packet().
mavlink_message_t* mavlink_get_channel_buffer (uint8_t channel)
Definition at line 174 of file mavlink_main.cpp.
References Mavlink::_boot_complete, Mavlink::_config_link_on, Mavlink::get_buffer(), Mavlink::get_instance(), and usage().
mavlink_status_t* mavlink_get_channel_status (uint8_t channel)
Definition at line 159 of file mavlink_main.cpp.
References Mavlink::get_instance(), and Mavlink::get_status().
int mavlink_main (int argc, char * argv[])
mavlink app start / stop handling function
Definition at line 3050 of file mavlink_main.cpp.
References Mavlink::destroy_all_instances(), Mavlink::get_status_all_instances(), PX4_WARN, Mavlink::set_boot_complete(), Mavlink::start(), Mavlink::stream_command(), and usage().
void mavlink_send_uart_bytes (mavlink_channel_t chan, const uint8_t * ch, int length)
Send multiple chars (uint8_t) over a comm channel.
Parameters
chan MAVLink channel to use, usually MAVLINK_COMM_0 = UART0
ch Character to send
Definition at line 116 of file mavlink_main.cpp.
References Mavlink::get_instance(), and Mavlink::send_bytes().
void mavlink_start_uart_send (mavlink_channel_t chan, int length)
Definition at line 132 of file mavlink_main.cpp.
References Mavlink::begin_send(), and Mavlink::get_instance().
static void usage (void) static
Definition at line 2980 of file mavlink_main.cpp.
References f(), PRINT_MODULE_DESCRIPTION(), PRINT_MODULE_USAGE_ARG(), PRINT_MODULE_USAGE_COMMAND_DESCR(), PRINT_MODULE_USAGE_NAME(), PRINT_MODULE_USAGE_PARAM_FLAG(), PRINT_MODULE_USAGE_PARAM_FLOAT(), PRINT_MODULE_USAGE_PARAM_INT(), and PRINT_MODULE_USAGE_PARAM_STRING().
Referenced by mavlink_get_channel_buffer(), mavlink_main(), Mavlink::stream_command(), and Mavlink::task_main().
Variable Documentation
Mavlink* _mavlink_instances = nullptr static
Definition at line 105 of file mavlink_main.cpp.
Referenced by Mavlink::destroy_all_instances(), Mavlink::get_status_all_instances(), and Mavlink::instance_exists().
mavlink_system_t mavlink_system
Definition at line 49 of file mavlink.c.
Referenced by MavlinkReceiver::evaluate_target_ok(), Mavlink::get_component_id(), Mavlink::get_system_id(), MavlinkParametersManager::handle_message(), MavlinkReceiver::handle_message(), MavlinkReceiver::handle_message_command_both(), MavlinkReceiver::handle_message_heartbeat(), MavlinkReceiver::handle_message_ping(), MavlinkReceiver::handle_message_play_tune(), MavlinkReceiver::handle_message_set_actuator_control_target(), MavlinkReceiver::handle_message_set_attitude_target(), MavlinkReceiver::handle_message_set_position_target_local_ned(), Mavlink::mavlink_update_system(), MavlinkStreamCameraTrigger::send(), MavlinkStreamRCChannels::send(), MavlinkStreamManualControl::send(), Mavlink::send_autopilot_capabilites(), MavlinkParametersManager::send_param(), and MavlinkParametersManager::send_uavcan().