PX4 Firmware: s_port_subscription_data_s Struct Reference
s_port_subscription_data_s Struct Reference
Public Attributes
uORB::SubscriptionData< battery_status_s > battery_status_sub {ORB_ID(battery_status)}
uORB::SubscriptionData< sensor_combined_s > sensor_combined_sub {ORB_ID(sensor_combined)}
uORB::SubscriptionData< vehicle_air_data_s > vehicle_air_data_sub {ORB_ID(vehicle_air_data)}
uORB::SubscriptionData< vehicle_global_position_s > vehicle_global_position_sub {ORB_ID(vehicle_global_position)}
uORB::SubscriptionData< vehicle_gps_position_s > vehicle_gps_position_sub {ORB_ID(vehicle_gps_position)}
uORB::SubscriptionData< vehicle_local_position_s > vehicle_local_position_sub {ORB_ID(vehicle_local_position)}
uORB::SubscriptionData< vehicle_status_s > vehicle_status_sub {ORB_ID(vehicle_status)}
Detailed Description
Definition at line 67 of file sPort_data.cpp.
Member Data Documentation
battery_status_sub
uORB::SubscriptionData<battery_status_s> s_port_subscription_data_s::battery_status_sub {ORB_ID(battery_status)}
Definition at line 68 of file sPort_data.cpp.
Referenced by sPort_send_BATV(), sPort_send_CUR(), sPort_send_FUEL(), and sPort_update_topics().
sensor_combined_sub
uORB::SubscriptionData<sensor_combined_s> s_port_subscription_data_s::sensor_combined_sub {ORB_ID(sensor_combined)}
Definition at line 69 of file sPort_data.cpp.
Referenced by sPort_update_topics().
vehicle_air_data_sub
uORB::SubscriptionData<vehicle_air_data_s> s_port_subscription_data_s::vehicle_air_data_sub {ORB_ID(vehicle_air_data)}
Definition at line 70 of file sPort_data.cpp.
Referenced by sPort_send_ALT(), and sPort_update_topics().
vehicle_global_position_sub
uORB::SubscriptionData<vehicle_global_position_s> s_port_subscription_data_s::vehicle_global_position_sub {ORB_ID(vehicle_global_position)}
Definition at line 71 of file sPort_data.cpp.
Referenced by sPort_send_GPS_SPD(), sPort_send_SPD(), and sPort_update_topics().
vehicle_gps_position_sub
uORB::SubscriptionData<vehicle_gps_position_s> s_port_subscription_data_s::vehicle_gps_position_sub {ORB_ID(vehicle_gps_position)}
Definition at line 72 of file sPort_data.cpp.
Referenced by sPort_send_GPS_ALT(), sPort_send_GPS_FIX(), sPort_send_GPS_info(), sPort_send_GPS_LAT(), sPort_send_GPS_LON(), sPort_send_GPS_TIME(), and sPort_update_topics().
vehicle_local_position_sub
uORB::SubscriptionData<vehicle_local_position_s> s_port_subscription_data_s::vehicle_local_position_sub {ORB_ID(vehicle_local_position)}
Definition at line 73 of file sPort_data.cpp.
Referenced by sPort_send_GPS_CRS(), and sPort_update_topics().
vehicle_status_sub
uORB::SubscriptionData<vehicle_status_s> s_port_subscription_data_s::vehicle_status_sub {ORB_ID(vehicle_status)}
Definition at line 74 of file sPort_data.cpp.
Referenced by sPort_send_flight_mode(), sPort_send_NAV_STATE(), and sPort_update_topics().
The documentation for this struct was generated from the following file:
src/drivers/telemetry/frsky_telemetry/sPort_data.cpp