PX4 Firmware: fxos8701cq Namespace Reference
fxos8701cq Namespace Reference
Local functions in support of the shell command.
Functions
void start (bool external_bus, enum Rotation rotation, unsigned range)
Start the driver.
void test ()
Perform some basic functional tests on the driver; make sure we can collect data from the sensor in polled and automatic modes.
void reset ()
Reset the driver.
void info ()
Print a little info about the driver.
void stop ()
Stop the driver.
void regdump ()
dump registers from device
void usage ()
Prints info about the driver argument usage.
void test_error ()
trigger an error
Variables
FXOS8701CQ * g_dev
Detailed Description
Local functions in support of the shell command.
Function Documentation
void fxos8701cq::info ()
Print a little info about the driver.
Print a little info about the driver.
Definition at line 1854 of file fxos8701cq.cpp.
References FXOS8701CQ::print_info(), and PX4_ERR.
Referenced by fxos8701cq_main().
void fxos8701cq::regdump (void)
dump registers from device
Definition at line 1885 of file fxos8701cq.cpp.
References FXOS8701CQ::print_registers(), and PX4_ERR.
Referenced by fxos8701cq_main().
void fxos8701cq::reset ()
Reset the driver.
Reset the driver.
Definition at line 1808 of file fxos8701cq.cpp.
References device::CDev::close(), fd, FXOS8701C_DEVICE_PATH_ACCEL, FXOS8701C_DEVICE_PATH_MAG, FXOS8701CQ_mag::ioctl(), device::CDev::open(), PX4_ERR, SENSOR_POLLRATE_DEFAULT, SENSORIOCRESET, and SENSORIOCSPOLLRATE.
Referenced by fxos8701cq_main(), and test().
void fxos8701cq::start (bool external_bus, enum Rotation rotation, unsigned range)
Start the driver.
This function call only returns once the driver is up and running or failed to detect the sensor.
Definition at line 1638 of file fxos8701cq.cpp.
References ACCELIOCSRANGE, device::CDev::close(), errx, fd, FXOS8701C_DEVICE_PATH_ACCEL, FXOS8701C_DEVICE_PATH_MAG, FXOS8701CQ_mag::FXOS8701CQ, g_dev, FXOS8701CQ::init(), FXOS8701CQ_mag::ioctl(), OK, device::CDev::open(), PX4_ERR, PX4_INFO, PX4_SPI_BUS_EXT, PX4_SPI_BUS_SENSORS, PX4_SPIDEV_ACCEL_MAG, PX4_SPIDEV_EXT_ACCEL_MAG, SENSOR_POLLRATE_DEFAULT, and SENSORIOCSPOLLRATE.
Referenced by fxos8701cq_main().
void fxos8701cq::stop ()
Stop the driver.
Stop the driver.
Definition at line 1868 of file fxos8701cq.cpp.
References g_dev, and PX4_ERR.
Referenced by fxos8701cq_main().
void fxos8701cq::test ()
Perform some basic functional tests on the driver; make sure we can collect data from the sensor in polled and automatic modes.
Definition at line 1713 of file fxos8701cq.cpp.
References accel_report, device::CDev::close(), FXOS8701C_DEVICE_PATH_ACCEL, FXOS8701C_DEVICE_PATH_MAG, FXOS8701CQ_mag::ioctl(), mag_report, MAGIOCGEXTERNAL, device::CDev::open(), PX4_ERR, PX4_INFO, FXOS8701CQ_mag::read(), reset(), SENSOR_POLLRATE_DEFAULT, and SENSORIOCSPOLLRATE.
Referenced by fxos8701cq_main().
void fxos8701cq::test_error (void)
trigger an error
Definition at line 1902 of file fxos8701cq.cpp.
References PX4_ERR, and FXOS8701CQ::test_error().
Referenced by fxos8701cq_main().
void fxos8701cq::usage (void)
Prints info about the driver argument usage.
Prints info about the driver argument usage.
Definition at line 1915 of file fxos8701cq.cpp.
References PX4_INFO.
Referenced by fxos8701cq_main().
Variable Documentation
FXOS8701CQ* fxos8701cq::g_dev
Definition at line 1620 of file fxos8701cq.cpp.
Referenced by start(), and stop().