PX4 Firmware: AEROFC_ADC Class Reference
AEROFC_ADC Class Reference
Public Member Functions
AEROFC_ADC (uint8_t bus)
virtual ~AEROFC_ADC ()
virtual int init ()
virtual int ioctl (file *filp, int cmd, unsigned long arg)
virtual ssize_t read (file *filp, char *buffer, size_t len)
Private Member Functions
virtual int probe ()
void cycle ()
Static Private Member Functions
static void cycle_trampoline (void *arg)
Private Attributes
struct work_s _work
px4_adc_msg_t _sample
pthread_mutex_t _sample_mutex
Detailed Description
Definition at line 82 of file aerofc_adc.cpp.
Constructor & Destructor Documentation
AEROFC_ADC::AEROFC_ADC (uint8_t bus)
Definition at line 211 of file aerofc_adc.cpp.
References _sample, _sample_mutex, and pthread_mutex_init().
AEROFC_ADC::~AEROFC_ADC () virtual
Definition at line 219 of file aerofc_adc.cpp.
Member Function Documentation
void AEROFC_ADC::cycle () private
Definition at line 298 of file aerofc_adc.cpp.
References _sample, _sample_mutex, ADC_CHANNEL_REG, CYCLE_TICKS_DELAY, cycle_trampoline(), pthread_mutex_lock(), pthread_mutex_unlock(), PX4_OK, and warn.
Referenced by cycle_trampoline().
void AEROFC_ADC::cycle_trampoline (void * arg) static private
Definition at line 292 of file aerofc_adc.cpp.
References cycle().
Referenced by cycle(), and init().
int AEROFC_ADC::init () virtual
Definition at line 224 of file aerofc_adc.cpp.
References CYCLE_TICKS_DELAY, cycle_trampoline(), lis3mdl::init(), and PX4_OK.
Referenced by aerofc_adc_main().
int AEROFC_ADC::ioctl (file * filp, int cmd, unsigned long arg) virtual
Definition at line 270 of file aerofc_adc.cpp.
int AEROFC_ADC::probe () private virtual
Definition at line 238 of file aerofc_adc.cpp.
References ADC_CHANNEL_REG, ADC_ENABLE_REG, PX4_OK, and usleep().
ssize_t AEROFC_ADC::read (file * filp, char * buffer, size_t len) virtual
Definition at line 275 of file aerofc_adc.cpp.
References _sample, _sample_mutex, pthread_mutex_lock(), and pthread_mutex_unlock().
Member Data Documentation
px4_adc_msg_t AEROFC_ADC::_sample private
Definition at line 99 of file aerofc_adc.cpp.
Referenced by AEROFC_ADC(), cycle(), and read().
pthread_mutex_t AEROFC_ADC::_sample_mutex private
Definition at line 100 of file aerofc_adc.cpp.
Referenced by AEROFC_ADC(), cycle(), and read().
struct work_s AEROFC_ADC::_work private
Definition at line 98 of file aerofc_adc.cpp.
The documentation for this class was generated from the following file:
src/drivers/aerofc_adc/aerofc_adc.cpp