PX4 Firmware: MavlinkStreamVisionPositionEstimate Class Reference
MavlinkStreamVisionPositionEstimate Class Reference
Public Member Functions
const char * get_name () const
uint16_t get_id ()
unsigned get_size ()
Get maximal total messages size on update.
Public Member Functions inherited from MavlinkStream
MavlinkStream (Mavlink *mavlink)
virtual ~MavlinkStream ()=default
MavlinkStream (const MavlinkStream &)=delete
MavlinkStream & operator= (const MavlinkStream &)=delete
MavlinkStream (MavlinkStream &&)=delete
MavlinkStream & operator= (MavlinkStream &&)=delete
void set_interval (const int interval)
Get the interval.
int get_interval ()
Get the interval.
int update (const hrt_abstime &t)
Update subscriptions and send message if necessary.
virtual bool const_rate ()
virtual unsigned get_size_avg ()
Get the average message size.
bool first_message_sent () const
void reset_last_sent ()
Reset the time of last sent to 0.
Static Public Member Functions
static const char * get_name_static ()
static uint16_t get_id_static ()
static MavlinkStream * new_instance (Mavlink *mavlink)
Protected Member Functions
MavlinkStreamVisionPositionEstimate (Mavlink *mavlink)
bool send (const hrt_abstime t)
Protected Member Functions inherited from MavlinkStream
virtual void update_data ()
Function to collect/update data for the streams at a high rate independant of actual stream rate.
Private Member Functions
MavlinkStreamVisionPositionEstimate (MavlinkStreamVisionPositionEstimate &)=delete
MavlinkStreamVisionPositionEstimate & operator= (const MavlinkStreamVisionPositionEstimate &)=delete
Private Attributes
MavlinkOrbSubscription * _pos_sub
uint64_t _pos_time
MavlinkOrbSubscription * _att_sub
uint64_t _att_time
Additional Inherited Members
Public Attributes inherited from MavlinkStream
MavlinkStream * next {nullptr}
Protected Attributes inherited from MavlinkStream
Mavlink *const _mavlink
int _interval {1000000}
if set to negative value = unlimited rate
Detailed Description
Definition at line 1986 of file mavlink_messages.cpp.
Constructor & Destructor Documentation
MavlinkStreamVisionPositionEstimate::MavlinkStreamVisionPositionEstimate (MavlinkStreamVisionPositionEstimate &) private delete
MavlinkStreamVisionPositionEstimate::MavlinkStreamVisionPositionEstimate (Mavlink * mavlink) inline explicit protected
Definition at line 2031 of file mavlink_messages.cpp.
Member Function Documentation
uint16_t MavlinkStreamVisionPositionEstimate::get_id () inline virtual
Implements MavlinkStream.
Definition at line 2004 of file mavlink_messages.cpp.
References MavlinkStreamHeartbeat::get_id_static().
static uint16_t MavlinkStreamVisionPositionEstimate::get_id_static () inline static
Definition at line 1999 of file mavlink_messages.cpp.
const char* MavlinkStreamVisionPositionEstimate::get_name () const inline virtual
Implements MavlinkStream.
Definition at line 1989 of file mavlink_messages.cpp.
References get_name_static().
static const char* MavlinkStreamVisionPositionEstimate::get_name_static () inline static
Definition at line 1994 of file mavlink_messages.cpp.
Referenced by get_name().
unsigned MavlinkStreamVisionPositionEstimate::get_size () inline virtual
Get maximal total messages size on update.
Implements MavlinkStream.
Definition at line 2014 of file mavlink_messages.cpp.
static MavlinkStream* MavlinkStreamVisionPositionEstimate::new_instance (Mavlink * mavlink) inline static
Definition at line 2009 of file mavlink_messages.cpp.
MavlinkStreamVisionPositionEstimate& MavlinkStreamVisionPositionEstimate::operator= (const MavlinkStreamVisionPositionEstimate &) private delete
bool MavlinkStreamVisionPositionEstimate::send (const hrt_abstime t) inline protected virtual
Implements MavlinkStream.
Definition at line 2038 of file mavlink_messages.cpp.
References MavlinkStream::_mavlink, Mavlink::get_channel(), matrix::Euler< Type >::phi(), matrix::Euler< Type >::psi(), vehicle_attitude_s::q, matrix::Euler< Type >::theta(), vehicle_local_position_s::timestamp, MavlinkOrbSubscription::update(), vehicle_local_position_s::x, vehicle_local_position_s::y, and vehicle_local_position_s::z.
Member Data Documentation
MavlinkOrbSubscription* MavlinkStreamVisionPositionEstimate::_att_sub private
Definition at line 2023 of file mavlink_messages.cpp.
uint64_t MavlinkStreamVisionPositionEstimate::_att_time private
Definition at line 2024 of file mavlink_messages.cpp.
MavlinkOrbSubscription* MavlinkStreamVisionPositionEstimate::_pos_sub private
Definition at line 2020 of file mavlink_messages.cpp.
uint64_t MavlinkStreamVisionPositionEstimate::_pos_time private
Definition at line 2021 of file mavlink_messages.cpp.
The documentation for this class was generated from the following file:
src/modules/mavlink/mavlink_messages.cpp