PX4 Firmware: Preflight Namespace Reference
Preflight Namespace Reference
Functions
static int check_calibration (DevHandle &h, const char *param_template, int &devid)
static bool magnometerCheck (orb_advert_t *mavlink_log_pub, vehicle_status_s &status, unsigned instance, bool optional, int &device_id, bool report_fail)
static bool imuConsistencyCheck (orb_advert_t *mavlink_log_pub, vehicle_status_s &status, bool report_status)
static bool magConsistencyCheck (orb_advert_t *mavlink_log_pub, vehicle_status_s &status, bool report_status)
static bool accelerometerCheck (orb_advert_t *mavlink_log_pub, vehicle_status_s &status, unsigned instance, bool optional, bool dynamic, int &device_id, bool report_fail)
static bool gyroCheck (orb_advert_t *mavlink_log_pub, vehicle_status_s &status, unsigned instance, bool optional, int &device_id, bool report_fail)
static bool baroCheck (orb_advert_t *mavlink_log_pub, vehicle_status_s &status, unsigned instance, bool optional, int &device_id, bool report_fail)
static bool airspeedCheck (orb_advert_t *mavlink_log_pub, vehicle_status_s &status, bool optional, bool report_fail, bool prearm)
static bool powerCheck (orb_advert_t *mavlink_log_pub, vehicle_status_s &status, bool report_fail, bool prearm)
static bool ekf2Check (orb_advert_t *mavlink_log_pub, vehicle_status_s &vehicle_status, bool optional, bool report_fail, bool enforce_gps_required)
bool preflightCheck (orb_advert_t *mavlink_log_pub, vehicle_status_s &status, vehicle_status_flags_s &status_flags, bool checkGNSS, bool reportFailures, bool prearm, const hrt_abstime &time_since_boot)
Runs a preflight check on all sensors to see if they are properly calibrated and healthy.
Variables
static constexpr unsigned max_mandatory_gyro_count = 1
static constexpr unsigned max_optional_gyro_count = 3
static constexpr unsigned max_mandatory_accel_count = 1
static constexpr unsigned max_optional_accel_count = 3
static constexpr unsigned max_mandatory_mag_count = 1
static constexpr unsigned max_optional_mag_count = 4
static constexpr unsigned max_mandatory_baro_count = 1
static constexpr unsigned max_optional_baro_count = 1
Function Documentation
static bool Preflight::accelerometerCheck (orb_advert_t * mavlink_log_pub, vehicle_status_s & status, unsigned instance, bool optional, bool dynamic, int & device_id, bool report_fail) static
Definition at line 240 of file PreflightCheck.cpp.
References ACCEL_BASE_DEVICE_PATH, accel_report, check_calibration(), f(), mavlink_log_critical, and set_health_flags().
Referenced by preflightCheck().
static bool Preflight::airspeedCheck (orb_advert_t * mavlink_log_pub, vehicle_status_s & status, bool optional, bool report_fail, bool prearm) static
Check if differential pressure is off by more than 15Pa which equals ~5m/s when measuring no airspeed. Negative and positive offsets are considered. Do not check anymore while arming because pitot cover might have been removed.
Definition at line 392 of file PreflightCheck.cpp.
References airspeed_s::confidence, differential_pressure_s::differential_pressure_filtered_pa, hrt_elapsed_time(), mavlink_log_critical, orb_copy(), ORB_ID, orb_subscribe(), orb_unsubscribe(), PX4_OK, set_health_flags(), airspeed_s::timestamp, and differential_pressure_s::timestamp.
Referenced by preflightCheck().
static bool Preflight::baroCheck (orb_advert_t * mavlink_log_pub, vehicle_status_s & status, unsigned instance, bool optional, int & device_id, bool report_fail) static
Definition at line 356 of file PreflightCheck.cpp.
References BARO_BASE_DEVICE_PATH, mavlink_log_critical, and set_health_flags().
Referenced by preflightCheck().
static int Preflight::check_calibration (DevHandle & h, const char * param_template, int & devid) static
Definition at line 75 of file PreflightCheck.cpp.
References instance, param_find(), param_get(), and PARAM_INVALID.
Referenced by accelerometerCheck(), gyroCheck(), and magnometerCheck().
static bool Preflight::ekf2Check (orb_advert_t * mavlink_log_pub, vehicle_status_s & vehicle_status, bool optional, bool report_fail, bool enforce_gps_required) static
Definition at line 507 of file PreflightCheck.cpp.
References estimator_status_s::control_mode_flags, estimator_status_s::gps_check_fail_flags, estimator_status_s::hgt_test_ratio, estimator_status_s::mag_test_ratio, mavlink_log_critical, orb_copy(), ORB_ID, orb_subscribe(), orb_unsubscribe(), param_find(), param_get(), estimator_status_s::pos_test_ratio, estimator_status_s::pre_flt_fail, PX4_OK, set_health_flags(), estimator_status_s::states, status, and estimator_status_s::vel_test_ratio.
Referenced by preflightCheck().
static bool Preflight::gyroCheck (orb_advert_t * mavlink_log_pub, vehicle_status_s & status, unsigned instance, bool optional, int & device_id, bool report_fail) static
Definition at line 315 of file PreflightCheck.cpp.
References check_calibration(), GYRO_BASE_DEVICE_PATH, mavlink_log_critical, and set_health_flags().
Referenced by preflightCheck().
static bool Preflight::imuConsistencyCheck (orb_advert_t * mavlink_log_pub, vehicle_status_s & status, bool report_status) static
Definition at line 153 of file PreflightCheck.cpp.
References sensor_preflight_s::accel_inconsistency_m_s_s, sensor_preflight_s::gyro_inconsistency_rad_s, mavlink_log_critical, mavlink_log_info, orb_copy(), ORB_ID, orb_subscribe(), orb_unsubscribe(), param_find(), param_get(), PX4_OK, and set_health_flags_healthy().
Referenced by preflightCheck().
static bool Preflight::magConsistencyCheck (orb_advert_t * mavlink_log_pub, vehicle_status_s & status, bool report_status) static
Definition at line 210 of file PreflightCheck.cpp.
References sensor_preflight_s::mag_inconsistency_ga, mavlink_log_critical, orb_copy(), ORB_ID, orb_subscribe(), orb_unsubscribe(), param_find(), param_get(), and set_health_flags_healthy().
Referenced by preflightCheck().
static bool Preflight::magnometerCheck (orb_advert_t * mavlink_log_pub, vehicle_status_s & status, unsigned instance, bool optional, int & device_id, bool report_fail) static
Definition at line 112 of file PreflightCheck.cpp.
References check_calibration(), MAG_BASE_DEVICE_PATH, mavlink_log_critical, and set_health_flags().
Referenced by preflightCheck().
static bool Preflight::powerCheck (orb_advert_t * mavlink_log_pub, vehicle_status_s & status, bool report_fail, bool prearm) static
Definition at line 459 of file PreflightCheck.cpp.
References f(), hrt_elapsed_time(), mavlink_log_critical, orb_copy(), ORB_ID, orb_subscribe(), orb_unsubscribe(), PX4_OK, system_power_s::timestamp, and system_power_s::voltage5v_v.
Referenced by preflightCheck().
bool Preflight::preflightCheck (orb_advert_t * mavlink_log_pub, vehicle_status_s & status, vehicle_status_flags_s & status_flags, bool checkGNSS, bool reportFailures, bool prearm, const hrt_abstime & time_since_boot)
Runs a preflight check on all sensors to see if they are properly calibrated and healthy.
The function won't fail the test if optional sensors are not found, however, it will fail the test if optional sensors are found but not in working condition.
Parameters
mavlink_log_pub Mavlink output orb handle reference for feedback when a sensor fails
checkMag true if the magneteometer should be checked
checkAcc true if the accelerometers should be checked
checkGyro true if the gyroscopes should be checked
checkBaro true if the barometer should be checked
checkAirspeed true if the airspeed sensor should be checked
checkRC true if the Remote Controller should be checked
checkGNSS true if the GNSS receiver should be checked
checkPower true if the system power should be checked
Definition at line 654 of file PreflightCheck.cpp.
References accelerometerCheck(), airspeedCheck(), baroCheck(), vehicle_status_flags_s::circuit_breaker_engaged_airspd_check, vehicle_status_flags_s::circuit_breaker_engaged_power_check, vehicle_status_flags_s::condition_calibration_enabled, vehicle_status_flags_s::condition_power_input_valid, vehicle_status_flags_s::condition_system_hotplug_timeout, device_id, ekf2Check(), gyroCheck(), vehicle_status_s::hil_state, imuConsistencyCheck(), vehicle_status_s::is_rotary_wing, vehicle_status_s::is_vtol, magConsistencyCheck(), magnometerCheck(), mavlink_log_critical, max_mandatory_accel_count, max_mandatory_baro_count, max_mandatory_gyro_count, max_mandatory_mag_count, max_optional_accel_count, max_optional_baro_count, max_optional_gyro_count, max_optional_mag_count, OK, param_find(), param_get(), powerCheck(), PX4_WARN, rc_calibration_check(), vehicle_status_flags_s::rc_calibration_valid, vehicle_status_s::rc_input_mode, vehicle_status_flags_s::rc_signal_found_once, vehicle_status_s::rc_signal_lost, and set_health_flags().
Referenced by arming_state_transition(), and Commander::preflight_check().
Variable Documentation
constexpr unsigned Preflight::max_mandatory_accel_count = 1 static
Definition at line 82 of file PreflightCheck.h.
Referenced by preflightCheck().
constexpr unsigned Preflight::max_mandatory_baro_count = 1 static
Definition at line 88 of file PreflightCheck.h.
Referenced by preflightCheck().
constexpr unsigned Preflight::max_mandatory_gyro_count = 1 static
Definition at line 79 of file PreflightCheck.h.
Referenced by preflightCheck().
constexpr unsigned Preflight::max_mandatory_mag_count = 1 static
Definition at line 85 of file PreflightCheck.h.
Referenced by preflightCheck().
constexpr unsigned Preflight::max_optional_accel_count = 3 static
Definition at line 83 of file PreflightCheck.h.
Referenced by preflightCheck().
constexpr unsigned Preflight::max_optional_baro_count = 1 static
Definition at line 89 of file PreflightCheck.h.
Referenced by preflightCheck().
constexpr unsigned Preflight::max_optional_gyro_count = 3 static
Definition at line 80 of file PreflightCheck.h.
Referenced by preflightCheck().
constexpr unsigned Preflight::max_optional_mag_count = 4 static
Definition at line 86 of file PreflightCheck.h.
Referenced by preflightCheck().