PX4 Firmware: VideoDevice Class Reference
VideoDevice Class Reference
#include <video_device.h>
Public Member Functions
VideoDevice (char const *dev_name, uint32_t n_buffers)
~VideoDevice ()=default
int start ()
Start the device.
int stop ()
Stop the device.
int print_info ()
Print various infos.
int get_frame (struct frame_data &frame)
Non-blocking call to fetch an image.
int put_frame (struct frame_data &frame)
Return a frame when the data is not needed any more.
Private Member Functions
int open_device ()
int close_device ()
int init_device ()
int init_buffers ()
int init_crop ()
int init_format ()
int start_capturing ()
int stop_capturing ()
Private Attributes
int _fd
const char * _dev_name
uint32_t _n_buffers
struct buffer * _buffers
Detailed Description
Definition at line 55 of file video_device.h.
Constructor & Destructor Documentation
VideoDevice::VideoDevice (char const * dev_name, uint32_t n_buffers) inline
Definition at line 58 of file video_device.h.
References start(), and stop().
VideoDevice::~VideoDevice () default
Member Function Documentation
int VideoDevice::close_device () private
Definition at line 133 of file video_device.cpp.
References _dev_name, _fd, OK, and PX4_ERR.
Referenced by stop().
int VideoDevice::get_frame (struct frame_data & frame)
Non-blocking call to fetch an image.
Returns 0 if the images was read, -1 on error and 1 no new image is ready.
Definition at line 349 of file video_device.cpp.
References _buffers, _fd, frame_data::bytes, frame_data::data, frame_data::index, PX4_ERR, PX4_INFO, frame_data::seq, buffer::start, and frame_data::timestamp.
Referenced by bebop_flow::task_main().
int VideoDevice::init_buffers () private
Definition at line 252 of file video_device.cpp.
References _buffers, _dev_name, _fd, _n_buffers, buffer::length, OK, PX4_ERR, buffer::start, and start().
Referenced by init_device().
int VideoDevice::init_crop () private
Definition at line 178 of file video_device.cpp.
References _fd, init_format(), and PX4_WARN.
Referenced by init_device().
int VideoDevice::init_device () private
Definition at line 145 of file video_device.cpp.
References _dev_name, _fd, init_buffers(), init_crop(), and PX4_ERR.
Referenced by start().
int VideoDevice::init_format () private
Definition at line 204 of file video_device.cpp.
References _fd, OK, PX4_ERR, PX4_INFO, usleep(), VIDEO_DEVICE_IMAGE_HEIGHT, and VIDEO_DEVICE_IMAGE_WIDTH.
Referenced by init_crop().
int VideoDevice::open_device () private
Definition at line 105 of file video_device.cpp.
References _dev_name, _fd, OK, and PX4_ERR.
Referenced by start().
int VideoDevice::print_info (void)
Print various infos.
Definition at line 99 of file video_device.cpp.
References _dev_name, and PX4_INFO.
Referenced by bebop_flow::info().
int VideoDevice::put_frame (struct frame_data & frame)
Return a frame when the data is not needed any more.
Definition at line 383 of file video_device.cpp.
References _buffers, _fd, frame_data::index, buffer::length, OK, and PX4_ERR.
Referenced by bebop_flow::task_main().
int VideoDevice::start ()
Start the device.
Definition at line 53 of file video_device.cpp.
References init_device(), open_device(), and start_capturing().
Referenced by init_buffers(), bebop_flow::start(), and stop().
int VideoDevice::start_capturing () private
Definition at line 304 of file video_device.cpp.
References _dev_name, _fd, _n_buffers, OK, PX4_ERR, and PX4_INFO.
Referenced by start().
int VideoDevice::stop ()
Stop the device.
Definition at line 70 of file video_device.cpp.
References _buffers, _n_buffers, close_device(), OK, PX4_ERR, start(), and stop_capturing().
Referenced by bebop_flow::stop().
int VideoDevice::stop_capturing () private
Definition at line 335 of file video_device.cpp.
References _dev_name, _fd, OK, PX4_ERR, and PX4_INFO.
Referenced by stop().
Member Data Documentation
struct buffer* VideoDevice::_buffers private
Definition at line 83 of file video_device.h.
Referenced by get_frame(), init_buffers(), put_frame(), and stop().
const char* VideoDevice::_dev_name private
Definition at line 81 of file video_device.h.
Referenced by close_device(), init_buffers(), init_device(), open_device(), print_info(), start_capturing(), and stop_capturing().
int VideoDevice::_fd private
Definition at line 80 of file video_device.h.
Referenced by close_device(), get_frame(), init_buffers(), init_crop(), init_device(), init_format(), open_device(), put_frame(), start_capturing(), and stop_capturing().
uint32_t VideoDevice::_n_buffers private
Definition at line 82 of file video_device.h.
Referenced by init_buffers(), start_capturing(), and stop().
The documentation for this class was generated from the following files:
src/platforms/posix/drivers/bebop_flow/video_device.h
src/platforms/posix/drivers/bebop_flow/video_device.cpp