PX4 Firmware: uORB::DeviceNode::SubscriberData Struct Reference
uORB::DeviceNode::SubscriberData Struct Reference
Public Member Functions
~SubscriberData ()
int priority () const
void set_priority (uint8_t prio)
bool update_reported () const
void set_update_reported (bool update_reported_flag)
Public Attributes
unsigned generation
last generation the subscriber has seen
int flags
lowest 8 bits: priority of publisher, 9.
UpdateIntervalData * update_interval
if null, no update interval
Detailed Description
Definition at line 204 of file uORBDevices.hpp.
Constructor & Destructor Documentation
uORB::DeviceNode::SubscriberData::~SubscriberData () inline
Definition at line 205 of file uORBDevices.hpp.
References update_interval.
Member Function Documentation
int uORB::DeviceNode::SubscriberData::priority () const inline
Definition at line 211 of file uORBDevices.hpp.
Referenced by uORB::DeviceNode::ioctl().
void uORB::DeviceNode::SubscriberData::set_priority (uint8_t prio) inline
Definition at line 212 of file uORBDevices.hpp.
Referenced by uORB::DeviceNode::open(), and uORB::DeviceNode::read().
void uORB::DeviceNode::SubscriberData::set_update_reported (bool update_reported_flag) inline
Definition at line 215 of file uORBDevices.hpp.
Referenced by uORB::DeviceNode::appears_updated(), uORB::DeviceNode::poll_notify_one(), and uORB::DeviceNode::read().
bool uORB::DeviceNode::SubscriberData::update_reported () const inline
Definition at line 214 of file uORBDevices.hpp.
Referenced by uORB::DeviceNode::appears_updated(), and uORB::DeviceNode::poll_notify_one().
Member Data Documentation
int uORB::DeviceNode::SubscriberData::flags
lowest 8 bits: priority of publisher, 9.
bit: update_reported bit
Definition at line 208 of file uORBDevices.hpp.
unsigned uORB::DeviceNode::SubscriberData::generation
last generation the subscriber has seen
Definition at line 207 of file uORBDevices.hpp.
Referenced by uORB::DeviceNode::appears_updated(), uORB::DeviceNode::open(), uORB::DeviceNode::poll_notify_one(), and uORB::DeviceNode::read().
UpdateIntervalData* uORB::DeviceNode::SubscriberData::update_interval
if null, no update interval
Definition at line 209 of file uORBDevices.hpp.
Referenced by uORB::DeviceNode::appears_updated(), uORB::DeviceNode::close(), uORB::DeviceNode::ioctl(), and uORB::DeviceNode::poll_notify_one().
The documentation for this struct was generated from the following file:
src/modules/uORB/uORBDevices.hpp