PX4 Firmware: src/lib/matrix/test/vector.cpp File Reference
vector.cpp File Reference
#include "test_macros.hpp"
#include <matrix/math.hpp>
Functions
int main ()
Function Documentation
main()
int main ()
Definition at line 7 of file vector.cpp.
References matrix::Vector< Type, M >::dot(), f(), matrix::isEqual(), matrix::isEqualF(), matrix::Vector< Type, M >::length(), matrix::Vector< Type, M >::longerThan(), matrix::Vector< Type, M >::norm(), matrix::Vector< Type, M >::norm_squared(), matrix::Vector< Type, M >::normalize(), matrix::Vector< Type, M >::sqrt(), TEST, matrix::Vector< Type, M >::unit(), and matrix::Vector< Type, M >::unit_or_zero().