PX4 Firmware: AlphaFilter< T > Class Template Reference
AlphaFilter< T > Class Template Reference final
First order "alpha" IIR digital filter.
#include <AlphaFilter.hpp>
Public Member Functions
AlphaFilter ()=default
~AlphaFilter ()=default
void reset (const T &val)
void update (const T &input, float tau, float dt)
void update (const T &input, float alpha)
void update (const T &input)
const T & getState () const
Private Attributes
T _x {}
current state of the filter
Detailed Description
template<typename T>
class AlphaFilter< T >
First order "alpha" IIR digital filter.
Author
Mathieu Bresciani bresc.nosp@m.iani.nosp@m.mathi.nosp@m.eu@g.nosp@m.mail..nosp@m.com
Definition at line 42 of file AlphaFilter.hpp.
Constructor & Destructor Documentation
AlphaFilter()
template<typename T> AlphaFilter< T >::AlphaFilter () default
~AlphaFilter()
template<typename T> AlphaFilter< T >::~AlphaFilter () default
Member Function Documentation
getState()
template<typename T> const T& AlphaFilter< T >::getState () const inline
Definition at line 67 of file AlphaFilter.hpp.
Referenced by Ekf::controlFusionModes(), Ekf::controlGpsFusion(), Ekf::controlOpticalFlowFusion(), Ekf::initialiseFilter(), Ekf::realignYawGPS(), Ekf::runInAirYawReset(), Ekf::runOnGroundYawReset(), and TEST_F().
reset()
template<typename T> void AlphaFilter< T >::reset (const T & val) inline
Definition at line 48 of file AlphaFilter.hpp.
Referenced by Ekf::initialiseFilter(), and TEST_F().
update() [1/3]
template<typename T> void AlphaFilter< T >::update (const T & input, float tau, float dt) inline
Definition at line 50 of file AlphaFilter.hpp.
Referenced by Ekf::initialiseFilter(), TEST_F(), AlphaFilter< Vector3f >::update(), and Ekf::updateMagFilter().
update() [2/3]
template<typename T> void AlphaFilter< T >::update (const T & input, float alpha) inline
Definition at line 56 of file AlphaFilter.hpp.
update() [3/3]
template<typename T> void AlphaFilter< T >::update (const T & input) inline
Definition at line 62 of file AlphaFilter.hpp.
Member Data Documentation
_x
template<typename T> T AlphaFilter< T >::_x {} private
current state of the filter
Definition at line 70 of file AlphaFilter.hpp.
Referenced by AlphaFilter< Vector3f >::getState(), AlphaFilter< Vector3f >::reset(), and AlphaFilter< Vector3f >::update().
The documentation for this class was generated from the following file:
src/lib/ecl/EKF/AlphaFilter.hpp