PX4 Firmware: ToneAlarmInterface Namespace Reference
ToneAlarmInterface Namespace Reference
Functions
void init ()
Activates/configures the hardware registers.
void start_note (unsigned frequency)
Starts playing the note.
void stop_note ()
Stops playing the current note and makes the player 'safe'.
Function Documentation
init()
void ToneAlarmInterface::init ()
Activates/configures the hardware registers.
Referenced by RoboClaw::_calcCRC(), LED::_measure(), UavcanNode::attachITxQueueInjector(), uavcan_stm32::CanDriver::CanDriver(), uavcan_kinetis::CanDriver::CanDriver(), uavcan_stm32::CanIface::CanIface(), uavcan_kinetis::CanIface::CanIface(), PX4IO::detect(), MPL3115A2_I2C::init(), FXAS21002C::init(), Airspeed::init(), ADIS16477::init(), LED::init(), ToneAlarm::init(), ADC::init(), RGBLED::init(), MPL3115A2::init(), RGBLED_NPC5623C::init(), __EXPORT::SPI::init(), PX4FLOW::init(), SF0X::init(), LidarLiteI2C::init(), OSDatxxxx::init(), AK09916::init(), TERARANGER::init(), LPS22HB::init(), SF1XX::init(), GPSSIM::init(), ADIS16497::init(), PMW3901::init(), PAW3902::init(), SRF02::init(), VL53LXX::init(), MB12XX::init(), LSM303AGR::init(), MS5611::init(), TAP_ESC::init(), IRLOCK::init(), ADIS16448::init(), LeddarOne::init(), px4::bst::BST::init(), UavcanEsc::init(), LIS3MDL::init(), Radar::init(), HMC5883::init(), FXOS8701CQ::init(), PCA9685::init(), BlinkM::init(), RM3100::init(), BMA180::init(), BMI088_gyro::init(), MK::init(), BMI055_gyro::init(), DShotOutput::init(), QMC5883::init(), PX4FMU::init(), PX4IO::init(), BMI055_accel::init(), LSM303D::init(), VOXLPM::init(), INA226::init(), MappyDot::init(), LPS25H::init(), BMI088_accel::init(), UavcanNode::init(), L3GD20::init(), PWMIN::init(), IST8310::init(), BMM150::init(), BMI160::init(), IridiumSBD::main_loop(), MK::mk_check_for_blctrl(), muorb_test_entry(), uavcan_kinetis::Mutex::Mutex(), PWMSim::PWMSim(), PX4_MAIN(), PX4IO_serial_interface(), qshell_entry(), AirspeedModule::Run(), __EXPORT::I2C::set_bus_clock(), DfLtc2946Wrapper::start(), DfBebopBusWrapper::start(), DfMS5607Wrapper::start(), DfBebopRangeFinderWrapper::start(), DfAK8963Wrapper::start(), DfTROneWrapper::start(), DfISL29501Wrapper::start(), DfMPU6050Wrapper::start(), DfLsm9ds1Wrapper::start(), and AirspeedModule::task_spawn().
start_note()
void ToneAlarmInterface::start_note (unsigned frequency)
Starts playing the note.
Referenced by ToneAlarm::start_note().
stop_note()
void ToneAlarmInterface::stop_note ()
Stops playing the current note and makes the player 'safe'.
Referenced by ToneAlarm::stop_note().