PX4 Firmware: MavlinkStream Class Reference
MavlinkStream Class Reference abstract
#include <mavlink_stream.h>
Public Member Functions
MavlinkStream (Mavlink *mavlink)
virtual ~MavlinkStream ()=default
MavlinkStream (const MavlinkStream &)=delete
MavlinkStream & operator= (const MavlinkStream &)=delete
MavlinkStream (MavlinkStream &&)=delete
MavlinkStream & operator= (MavlinkStream &&)=delete
void set_interval (const int interval)
Get the interval.
int get_interval ()
Get the interval.
int update (const hrt_abstime &t)
Update subscriptions and send message if necessary.
virtual const char * get_name () const =0
virtual uint16_t get_id ()=0
virtual bool const_rate ()
virtual unsigned get_size ()=0
Get maximal total messages size on update.
virtual unsigned get_size_avg ()
Get the average message size.
bool first_message_sent () const
void reset_last_sent ()
Reset the time of last sent to 0.
Public Attributes
MavlinkStream * next {nullptr}
Protected Member Functions
virtual bool send (const hrt_abstime t)=0
virtual void update_data ()
Function to collect/update data for the streams at a high rate independant of actual stream rate.
Protected Attributes
Mavlink *const _mavlink
int _interval {1000000}
if set to negative value = unlimited rate
Private Attributes
hrt_abstime _last_sent {0}
bool _first_message_sent {false}
Detailed Description
Definition at line 48 of file mavlink_stream.h.
Constructor & Destructor Documentation
MavlinkStream::MavlinkStream (Mavlink * mavlink)
Definition at line 47 of file mavlink_stream.cpp.
References _last_sent, and hrt_absolute_time().
virtual MavlinkStream::~MavlinkStream () virtual default
MavlinkStream::MavlinkStream (const MavlinkStream &) delete
MavlinkStream::MavlinkStream (MavlinkStream &&) delete
Member Function Documentation
virtual bool MavlinkStream::const_rate () inline virtual
Returns
true if steam rate shouldn't be adjusted
Reimplemented in MavlinkStreamPing, MavlinkStreamCameraImageCaptured, MavlinkStreamCameraTrigger, MavlinkStreamADSBVehicle, MavlinkStreamHeartbeat, and MavlinkStreamHighLatency2.
Definition at line 87 of file mavlink_stream.h.
References get_size().
Referenced by Mavlink::display_status_streams(), update(), and Mavlink::update_rate_mult().
bool MavlinkStream::first_message_sent () const inline
Returns
true if the first message of this stream has been sent
Definition at line 107 of file mavlink_stream.h.
References _first_message_sent.
Referenced by Mavlink::task_main().
virtual uint16_t MavlinkStream::get_id () pure virtual
Implemented in MavlinkStreamPing, MavlinkStreamGroundTruth, MavlinkStreamMountOrientation, MavlinkStreamWind, MavlinkStreamAltitude, MavlinkStreamExtendedSysState, MavlinkStreamDistanceSensor, MavlinkStreamCameraCapture, MavlinkStreamNavControllerOutput, MavlinkStreamDebugVect, MavlinkStreamDebug, MavlinkStreamNamedValueFloat, MavlinkStreamOpticalFlowRad, MavlinkStreamTrajectoryRepresentationWaypoints, MavlinkStreamManualControl, MavlinkStreamRCChannels, MavlinkStreamAttitudeTarget, MavlinkStreamLocalPositionSetpoint, MavlinkStreamPositionTargetGlobalInt, MavlinkStreamHILActuatorControls, MavlinkStreamActuatorControlTarget< N >, MavlinkStreamServoOutputRaw< N >, MavlinkStreamHomePosition, MavlinkStreamAttPosMocap, MavlinkStreamEstimatorStatus, MavlinkStreamLocalPositionNEDCOV, MavlinkStreamLocalPositionNED, MavlinkStreamVisionPositionEstimate, MavlinkStreamGlobalPositionInt, MavlinkStreamCameraImageCaptured, MavlinkStreamCameraTrigger, MavlinkStreamCollision, MavlinkStreamADSBVehicle, MavlinkStreamTimesync, MavlinkStreamSystemTime, MavlinkStreamGPSRawInt, MavlinkStreamVFRHUD, MavlinkStreamAttitudeQuaternion, MavlinkStreamAttitude, MavlinkStreamScaledIMU3, MavlinkStreamScaledIMU2, MavlinkStreamScaledIMU, MavlinkStreamHighresIMU, MavlinkStreamSysStatus, MavlinkStreamCommandLong, MavlinkStreamStatustext, MavlinkStreamHeartbeat, and MavlinkStreamHighLatency2.
Referenced by get_interval(), MavlinkReceiver::get_message_interval(), and Mavlink::task_main().
int MavlinkStream::get_interval () inline
Get the interval.
Returns
the inveral in microseconds (us) between messages
Definition at line 75 of file mavlink_stream.h.
References _interval, get_id(), get_name(), hrt_abstime, and update().
Referenced by Mavlink::adjust_stream_rates(), Mavlink::display_status_streams(), MavlinkReceiver::get_message_interval(), and Mavlink::update_rate_mult().
virtual const char* MavlinkStream::get_name () const pure virtual
Implemented in MavlinkStreamPing, MavlinkStreamGroundTruth, MavlinkStreamMountOrientation, MavlinkStreamWind, MavlinkStreamAltitude, MavlinkStreamExtendedSysState, MavlinkStreamDistanceSensor, MavlinkStreamCameraCapture, MavlinkStreamNavControllerOutput, MavlinkStreamDebugVect, MavlinkStreamDebug, MavlinkStreamNamedValueFloat, MavlinkStreamOpticalFlowRad, MavlinkStreamTrajectoryRepresentationWaypoints, MavlinkStreamManualControl, MavlinkStreamRCChannels, MavlinkStreamAttitudeTarget, MavlinkStreamLocalPositionSetpoint, MavlinkStreamPositionTargetGlobalInt, MavlinkStreamHILActuatorControls, MavlinkStreamActuatorControlTarget< N >, MavlinkStreamServoOutputRaw< N >, MavlinkStreamHomePosition, MavlinkStreamAttPosMocap, MavlinkStreamEstimatorStatus, MavlinkStreamLocalPositionNEDCOV, MavlinkStreamLocalPositionNED, MavlinkStreamVisionPositionEstimate, MavlinkStreamGlobalPositionInt, MavlinkStreamCameraImageCaptured, MavlinkStreamCameraTrigger, MavlinkStreamCollision, MavlinkStreamADSBVehicle, MavlinkStreamTimesync, MavlinkStreamSystemTime, MavlinkStreamGPSRawInt, MavlinkStreamVFRHUD, MavlinkStreamAttitudeQuaternion, MavlinkStreamAttitude, MavlinkStreamScaledIMU3, MavlinkStreamScaledIMU2, MavlinkStreamScaledIMU, MavlinkStreamHighresIMU, MavlinkStreamSysStatus, MavlinkStreamCommandLong, MavlinkStreamStatustext, MavlinkStreamHeartbeat, and MavlinkStreamHighLatency2.
Referenced by Mavlink::configure_stream(), Mavlink::display_status_streams(), and get_interval().
virtual unsigned MavlinkStream::get_size () pure virtual
Get maximal total messages size on update.
Implemented in MavlinkStreamPing, MavlinkStreamGroundTruth, MavlinkStreamMountOrientation, MavlinkStreamWind, MavlinkStreamAltitude, MavlinkStreamExtendedSysState, MavlinkStreamDistanceSensor, MavlinkStreamCameraCapture, MavlinkStreamNavControllerOutput, MavlinkStreamDebugVect, MavlinkStreamDebug, MavlinkStreamNamedValueFloat, MavlinkStreamOpticalFlowRad, MavlinkStreamTrajectoryRepresentationWaypoints, MavlinkStreamManualControl, MavlinkStreamRCChannels, MavlinkStreamAttitudeTarget, MavlinkStreamLocalPositionSetpoint, MavlinkStreamPositionTargetGlobalInt, MavlinkStreamHILActuatorControls, MavlinkStreamActuatorControlTarget< N >, MavlinkStreamServoOutputRaw< N >, MavlinkStreamHomePosition, MavlinkStreamAttPosMocap, MavlinkStreamEstimatorStatus, MavlinkStreamLocalPositionNEDCOV, MavlinkStreamLocalPositionNED, MavlinkStreamVisionPositionEstimate, MavlinkStreamGlobalPositionInt, MavlinkStreamCameraImageCaptured, MavlinkStreamCameraTrigger, MavlinkStreamCollision, MavlinkStreamADSBVehicle, MavlinkStreamTimesync, MavlinkStreamSystemTime, MavlinkStreamGPSRawInt, MavlinkStreamVFRHUD, MavlinkStreamAttitudeQuaternion, MavlinkStreamAttitude, MavlinkStreamScaledIMU3, MavlinkStreamScaledIMU2, MavlinkStreamScaledIMU, MavlinkStreamHighresIMU, MavlinkStreamSysStatus, MavlinkStreamCommandLong, MavlinkStreamStatustext, MavlinkStreamHeartbeat, and MavlinkStreamHighLatency2.
Referenced by const_rate(), Mavlink::display_status_streams(), and get_size_avg().
virtual unsigned MavlinkStream::get_size_avg () inline virtual
Get the average message size.
For a normal stream this equals the message size, for something like a parameter or mission message this equals usually zero, as no bandwidth needs to be reserved
Definition at line 102 of file mavlink_stream.h.
References get_size().
Referenced by Mavlink::update_rate_mult().
MavlinkStream& MavlinkStream::operator= (const MavlinkStream &) delete
MavlinkStream& MavlinkStream::operator= (MavlinkStream &&) delete
void MavlinkStream::reset_last_sent () inline
Reset the time of last sent to 0.
Can be used if a message over this stream needs to be sent immediately.
Definition at line 113 of file mavlink_stream.h.
References _last_sent.
Referenced by MavlinkStreamHighLatency2::MavlinkStreamHighLatency2().
virtual bool MavlinkStream::send (const hrt_abstime t) protected pure virtual
Implemented in MavlinkStreamPing, MavlinkStreamGroundTruth, MavlinkStreamMountOrientation, MavlinkStreamWind, MavlinkStreamAltitude, MavlinkStreamExtendedSysState, MavlinkStreamDistanceSensor, MavlinkStreamCameraCapture, MavlinkStreamNavControllerOutput, MavlinkStreamDebugVect, MavlinkStreamDebug, MavlinkStreamNamedValueFloat, MavlinkStreamOpticalFlowRad, MavlinkStreamTrajectoryRepresentationWaypoints, MavlinkStreamManualControl, MavlinkStreamRCChannels, MavlinkStreamAttitudeTarget, MavlinkStreamLocalPositionSetpoint, MavlinkStreamPositionTargetGlobalInt, MavlinkStreamHILActuatorControls, MavlinkStreamActuatorControlTarget< N >, MavlinkStreamServoOutputRaw< N >, MavlinkStreamHomePosition, MavlinkStreamAttPosMocap, MavlinkStreamEstimatorStatus, MavlinkStreamLocalPositionNEDCOV, MavlinkStreamLocalPositionNED, MavlinkStreamVisionPositionEstimate, MavlinkStreamGlobalPositionInt, MavlinkStreamCameraImageCaptured, MavlinkStreamCameraTrigger, MavlinkStreamCollision, MavlinkStreamADSBVehicle, MavlinkStreamTimesync, MavlinkStreamSystemTime, MavlinkStreamGPSRawInt, MavlinkStreamVFRHUD, MavlinkStreamAttitudeQuaternion, MavlinkStreamAttitude, MavlinkStreamScaledIMU3, MavlinkStreamScaledIMU2, MavlinkStreamScaledIMU, MavlinkStreamHighresIMU, MavlinkStreamSysStatus, MavlinkStreamCommandLong, MavlinkStreamStatustext, MavlinkStreamHeartbeat, and MavlinkStreamHighLatency2.
Referenced by update().
void MavlinkStream::set_interval (const int interval) inline
Get the interval.
Parameters
interval the interval in microseconds (us) between messages
Definition at line 68 of file mavlink_stream.h.
References _interval.
Referenced by Mavlink::adjust_stream_rates(), and Mavlink::configure_stream().
int MavlinkStream::update (const hrt_abstime & t)
Update subscriptions and send message if necessary.
Returns
0 if updated / sent, -1 if unchanged
Definition at line 57 of file mavlink_stream.cpp.
References _first_message_sent, _interval, _last_sent, _mavlink, const_rate(), dt, Mavlink::get_main_loop_delay(), Mavlink::get_rate_mult(), hrt_absolute_time(), send(), and update_data().
Referenced by get_interval(), and Mavlink::task_main().
virtual void MavlinkStream::update_data () inline protected virtual
Function to collect/update data for the streams at a high rate independant of actual stream rate.
This function is called at every iteration of the mavlink module.
Reimplemented in MavlinkStreamHighLatency2.
Definition at line 127 of file mavlink_stream.h.
Referenced by update().
Member Data Documentation
bool MavlinkStream::_first_message_sent {false} private
Definition at line 131 of file mavlink_stream.h.
Referenced by first_message_sent(), and update().
int MavlinkStream::_interval {1000000} protected
if set to negative value = unlimited rate
Definition at line 117 of file mavlink_stream.h.
Referenced by get_interval(), set_interval(), and update().
hrt_abstime MavlinkStream::_last_sent {0} private
Definition at line 130 of file mavlink_stream.h.
Referenced by MavlinkStream(), reset_last_sent(), and update().
Mavlink* const MavlinkStream::_mavlink protected
Definition at line 116 of file mavlink_stream.h.
Referenced by MavlinkStreamStatustext::get_size(), MavlinkStreamActuatorControlTarget< N >::MavlinkStreamActuatorControlTarget(), MavlinkStreamHighLatency2::send(), MavlinkStreamHeartbeat::send(), MavlinkStreamStatustext::send(), MavlinkStreamCommandLong::send(), MavlinkStreamSysStatus::send(), MavlinkStreamHighresIMU::send(), MavlinkStreamScaledIMU::send(), MavlinkStreamScaledIMU2::send(), MavlinkStreamScaledIMU3::send(), MavlinkStreamAttitude::send(), MavlinkStreamAttitudeQuaternion::send(), MavlinkStreamVFRHUD::send(), MavlinkStreamGPSRawInt::send(), MavlinkStreamSystemTime::send(), MavlinkStreamTimesync::send(), MavlinkStreamADSBVehicle::send(), MavlinkStreamCollision::send(), MavlinkStreamCameraTrigger::send(), MavlinkStreamCameraImageCaptured::send(), MavlinkStreamGlobalPositionInt::send(), MavlinkStreamVisionPositionEstimate::send(), MavlinkStreamLocalPositionNED::send(), MavlinkStreamLocalPositionNEDCOV::send(), MavlinkStreamEstimatorStatus::send(), MavlinkStreamAttPosMocap::send(), MavlinkStreamHomePosition::send(), MavlinkStreamServoOutputRaw< N >::send(), MavlinkStreamActuatorControlTarget< N >::send(), MavlinkStreamHILActuatorControls::send(), MavlinkStreamPositionTargetGlobalInt::send(), MavlinkStreamLocalPositionSetpoint::send(), MavlinkStreamAttitudeTarget::send(), MavlinkStreamRCChannels::send(), MavlinkStreamManualControl::send(), MavlinkStreamTrajectoryRepresentationWaypoints::send(), MavlinkStreamOpticalFlowRad::send(), MavlinkStreamNamedValueFloat::send(), MavlinkStreamDebug::send(), MavlinkStreamDebugVect::send(), MavlinkStreamNavControllerOutput::send(), MavlinkStreamCameraCapture::send(), MavlinkStreamDistanceSensor::send(), MavlinkStreamExtendedSysState::send(), MavlinkStreamAltitude::send(), MavlinkStreamWind::send(), MavlinkStreamMountOrientation::send(), MavlinkStreamGroundTruth::send(), MavlinkStreamPing::send(), and update().
MavlinkStream* MavlinkStream::next {nullptr}
Definition at line 52 of file mavlink_stream.h.
Referenced by Mavlink::task_main().
The documentation for this class was generated from the following files:
src/modules/mavlink/mavlink_stream.h
src/modules/mavlink/mavlink_stream.cpp