PX4 Firmware: meas_airspeed Namespace Reference
meas_airspeed Namespace Reference
Local functions in support of the shell command.
Functions
int start ()
Attempt to start driver on all available I2C busses.
int start_bus (int i2c_bus, int address)
Start the driver on a specific bus.
int stop ()
Stop the driver.
int reset ()
Reset the driver.
Variables
MEASAirspeed * g_dev = nullptr
Detailed Description
Local functions in support of the shell command.
Function Documentation
int meas_airspeed::reset ()
Reset the driver.
Definition at line 471 of file ms4525_airspeed.cpp.
References fd, PATH_MS4525, PX4_ERR, PX4_ERROR, px4_ioctl(), PX4_OK, px4_open(), SENSOR_POLLRATE_DEFAULT, SENSORIOCRESET, and SENSORIOCSPOLLRATE.
Referenced by ms4525_airspeed_main().
int meas_airspeed::start ()
Attempt to start driver on all available I2C busses.
This function will return as soon as the first sensor is detected on one of the available busses or if no sensors are detected.
Definition at line 386 of file ms4525_airspeed.cpp.
References I2C_ADDRESS_MS4525DO, i2c_bus_options, PX4_ERROR, PX4_OK, and start_bus().
Referenced by ms4525_airspeed_main().
int meas_airspeed::start_bus (int i2c_bus, int address)
Start the driver on a specific bus.
This function call only returns once the driver is up and running or failed to detect the sensor.
Definition at line 405 of file ms4525_airspeed.cpp.
References fd, g_dev, Airspeed::init(), MEASAirspeed::MEASAirspeed(), OK, PATH_MS4525, PX4_ERR, PX4_ERROR, px4_ioctl(), PX4_OK, px4_open(), SENSOR_POLLRATE_DEFAULT, and SENSORIOCSPOLLRATE.
Referenced by ms4525_airspeed_main(), and start().
int meas_airspeed::stop ()
Stop the driver.
Definition at line 453 of file ms4525_airspeed.cpp.
References g_dev, PX4_ERR, PX4_ERROR, and PX4_OK.
Referenced by ms4525_airspeed_main().
Variable Documentation
MEASAirspeed* meas_airspeed::g_dev = nullptr
Definition at line 370 of file ms4525_airspeed.cpp.
Referenced by start_bus(), and stop().