PX4 Firmware: src/lib/parameters/param.c File Reference
param.c File Reference
Global parameter store.
#include "param.h"
#include <parameters/px4_parameters.h>
#include "tinybson/tinybson.h"
#include <crc32.h>
#include <float.h>
#include <math.h>
#include <drivers/drv_hrt.h>
#include <px4_config.h>
#include <px4_defines.h>
#include <px4_posix.h>
#include <px4_sem.h>
#include <px4_shutdown.h>
#include <perf/perf_counter.h>
#include <systemlib/uthash/utarray.h>
#include "uORB/uORB.h"
#include "uORB/topics/parameter_update.h"
#include <px4_workqueue.h>
Classes
struct param_wbuf_s
Storage for modified parameters.
struct param_import_state
Macros
#define FLASH_PARAMS_EXPOSE
#define debug(fmt, args...) do { } while(0)
#define PARAM_OPEN open
#define PARAM_CLOSE close
#define param_info_count px4_parameters.param_count
Functions
static unsigned get_param_info_count (void)
static void param_set_used_internal (param_t param)
static param_t param_find_internal (const char *name, bool notification)
static void param_lock_reader (void)
lock the parameter store for read access
static void param_lock_writer (void)
lock the parameter store for write access
static void param_unlock_reader (void)
unlock the parameter store
static void param_unlock_writer (void)
unlock the parameter store
static void param_assert_locked (void)
assert that the parameter store is locked
void param_init (void)
Initialize the param backend.
static bool handle_in_range (param_t param)
Test whether a param_t is value.
static int param_compare_values (const void *a, const void *b)
Compare two modifid parameter structures to determine ordering.
static struct param_wbuf_s * param_find_changed (param_t param)
Locate the modified parameter structure for a parameter, if it exists.
static void _param_notify_changes (void)
void param_notify_changes (void)
Notify the system about parameter changes.
param_t param_find (const char *name)
Look up a parameter by name.
param_t param_find_no_notification (const char *name)
Look up a parameter by name.
unsigned param_count (void)
Return the total number of parameters.
unsigned param_count_used (void)
Return the actually used number of parameters.
param_t param_for_index (unsigned index)
Look up a parameter by index.
param_t param_for_used_index (unsigned index)
Look up an used parameter by index.
int param_get_index (param_t param)
Look up the index of a parameter.
int param_get_used_index (param_t param)
Look up the index of an used parameter.
const char * param_name (param_t param)
Obtain the name of a parameter.
bool param_is_volatile (param_t param)
Obtain the volatile state of a parameter.
bool param_value_is_default (param_t param)
Test whether a parameter's value has changed from the default.
bool param_value_unsaved (param_t param)
Test whether a parameter's value has been changed but not saved.
param_type_t param_type (param_t param)
Obtain the type of a parameter.
size_t param_size (param_t param)
Determine the size of a parameter.
static const void * param_get_value_ptr (param_t param)
Obtain a pointer to the storage allocated for a parameter.
int param_get (param_t param, void *val)
Copy the value of a parameter.
static void autosave_worker (void *arg)
worker callback method to save the parameters
static void param_autosave (void)
Automatically save the parameters after a timeout and limited rate.
void param_control_autosave (bool enable)
Enable/disable the param autosaving.
static int param_set_internal (param_t param, const void *val, bool mark_saved, bool notify_changes)
int param_set (param_t param, const void *val)
Set the value of a parameter.
int param_set_no_notification (param_t param, const void *val)
Set the value of a parameter, but do not notify the system about the change.
bool param_used (param_t param)
Wether a parameter is in use in the system.
void param_set_used (param_t param)
Mark a parameter as used.
int param_reset (param_t param)
Reset a parameter to its default value.
static void param_reset_all_internal (bool auto_save)
void param_reset_all (void)
Reset all parameters to their default values.
void param_reset_excludes (const char *excludes[], int num_excludes)
Reset all parameters to their default values except for excluded parameters.
int param_set_default_file (const char *filename)
Set the default parameter file name.
const char * param_get_default_file (void)
Get the default parameter file name.
int param_save_default (void)
Save parameters to the default file.
int param_load_default (void)
Load parameters from the default parameter file.
int param_export (int fd, bool only_unsaved)
Export changed parameters to a file.
static int param_import_callback (bson_decoder_t decoder, void *private, bson_node_t node)
static int param_import_internal (int fd, bool mark_saved)
int param_import (int fd)
Import parameters from a file, discarding any unrecognized parameters.
int param_load (int fd)
Load parameters from a file.
void param_foreach (void(*func)(void *arg, param_t param), void *arg, bool only_changed, bool only_used)
Apply a function to each parameter.
uint32_t param_hash_check (void)
Generate the hash of all parameters and their values.
Variables
static const char * param_default_file = PX4_ROOTFSDIR"/eeprom/parameters"
static char * param_user_file = NULL
static hrt_abstime last_autosave_timestamp = 0
static struct work_s autosave_work
static bool autosave_scheduled = false
static bool autosave_disabled = false
static const struct param_info_s * param_info_base = (const struct param_info_s *) &px4_parameters
Array of static parameter info.
uint8_t * param_changed_storage = NULL
int size_param_changed_storage_bytes = 0
const int bits_per_allocation_unit = (sizeof(*param_changed_storage) * 8)
FLASH_PARAMS_EXPOSE UT_array * param_values
flexible array holding modified parameter values
FLASH_PARAMS_EXPOSE const UT_icd param_icd = {sizeof(struct param_wbuf_s), NULL, NULL, NULL}
array info for the modified parameters array
static orb_advert_t param_topic = NULL
parameter update topic handle
static unsigned int param_instance = 0
static px4_sem_t param_sem
this protects against concurrent access to param_values
static int reader_lock_holders = 0
static px4_sem_t reader_lock_holders_lock
this protects against concurrent access to reader_lock_holders
static perf_counter_t param_export_perf
static perf_counter_t param_find_perf
static perf_counter_t param_get_perf
static perf_counter_t param_set_perf
static px4_sem_t param_sem_save
this protects against concurrent param saves (file or flash access).
Detailed Description
Global parameter store.
Note that it might make sense to convert this into a driver. That would offer some interesting options regarding state for e.g. ORB advertisements and background parameter saving.
Definition in file param.c.
Macro Definition Documentation
#define debug (fmt, args...) do { } while(0)
Definition at line 82 of file param.c.
Referenced by param_export(), and param_import_callback().
#define FLASH_PARAMS_EXPOSE
Definition at line 71 of file param.c.
#define PARAM_CLOSE close
Definition at line 90 of file param.c.
Referenced by param_load_default(), and param_save_default().
#define param_info_count px4_parameters.param_count
Definition at line 106 of file param.c.
Referenced by get_param_info_count().
#define PARAM_OPEN open
Definition at line 89 of file param.c.
Referenced by param_load_default(), and param_save_default().
Function Documentation
static void _param_notify_changes (void) static
Definition at line 301 of file param.c.
References hrt_absolute_time(), orb_advertise(), ORB_ID, orb_publish(), and parameter_update_s::timestamp.
Referenced by param_notify_changes(), param_reset(), param_reset_all_internal(), param_reset_excludes(), and param_set_internal().
static void autosave_worker (void * arg) static
worker callback method to save the parameters
Parameters
arg unused
Definition at line 617 of file param.c.
References autosave_disabled, autosave_scheduled, hrt_absolute_time(), last_autosave_timestamp, param_lock_writer(), param_save_default(), param_unlock_writer(), PX4_DEBUG, and PX4_ERR.
Referenced by param_autosave().
static unsigned get_param_info_count (void) static
Definition at line 124 of file param.c.
References bits_per_allocation_unit, param_changed_storage, param_info_count, and size_param_changed_storage_bytes.
Referenced by handle_in_range(), param_count(), param_count_used(), param_find_internal(), param_for_index(), and param_for_used_index().
static bool handle_in_range (param_t param) static
Test whether a param_t is value.
Parameters
param The parameter handle to test.
Returns
True if the handle is valid.
Definition at line 249 of file param.c.
References get_param_info_count().
Referenced by param_foreach(), param_get_index(), param_get_value_ptr(), param_hash_check(), param_is_volatile(), param_name(), param_reset(), param_reset_excludes(), param_set_internal(), param_size(), and param_type().
static void param_assert_locked (void) static
assert that the parameter store is locked
Definition at line 224 of file param.c.
Referenced by param_find_changed(), and param_get_value_ptr().
static void param_autosave (void) static
Automatically save the parameters after a timeout and limited rate.
This needs to be called with the writer lock held (it's not necessary that it's the writer lock, but it needs to be the same lock as autosave_worker() and param_control_autosave() use).
Definition at line 647 of file param.c.
References autosave_disabled, autosave_scheduled, autosave_work, autosave_worker(), hrt_abstime, hrt_elapsed_time(), and last_autosave_timestamp.
Referenced by param_reset(), param_reset_all_internal(), and param_set_internal().
static int param_compare_values (const void * a, const void * b) static
Compare two modifid parameter structures to determine ordering.
This function is suitable for passing to qsort or bsearch.
Definition at line 261 of file param.c.
References param_wbuf_s::param.
Referenced by param_find_changed(), and param_set_internal().
void param_control_autosave (bool enable)
Enable/disable the param autosaving.
Re-enabling with changed params will not cause an autosave.
Parameters
enable true: enable autosaving, false: disable autosaving
Definition at line 674 of file param.c.
Referenced by ParameterTest::run_tests(), and TemperatureCalibration::task_main().
unsigned param_count (void)
Return the total number of parameters.
Returns
The number of parameters.
Definition at line 383 of file param.c.
Referenced by do_show(), ParameterTest::exportImportAll(), MavlinkParametersManager::send_one(), MavlinkParametersManager::send_untransmitted(), px4::logger::Logger::write_changed_parameters(), and px4::logger::Logger::write_parameters().
unsigned param_count_used (void)
Return the actually used number of parameters.
Returns
The number of parameters.
Definition at line 389 of file param.c.
Referenced by do_show(), MavlinkParametersManager::handle_message(), MavlinkParametersManager::send_one(), and MavlinkParametersManager::send_param().
int param_export (int fd, bool only_unsaved)
Export changed parameters to a file.
Note: this method requires a large amount of stack size!
Parameters
fd File descriptor to export to.
only_unsaved Only export changed parameters that have not yet been exported.
Returns
Zero on success, nonzero on failure.
Definition at line 1033 of file param.c.
Referenced by do_save(), ParameterTest::exportImportAll(), and param_save_default().
param_t param_find (const char * name)
Look up a parameter by name.
Parameters
name The canonical name of the parameter being looked up.
Returns
A handle to the parameter, or PARAM_INVALID if the parameter does not exist. This call will also set the parameter as "used" in the system, which is used to e.g. show the parameter via the RC interface
Definition at line 371 of file param.c.
Referenced by land_detector::LandDetector::_cycle(), DfMPU6050Wrapper::_update_accel_calibration(), DfLsm9ds1Wrapper::_update_accel_calibration(), DfMpu9250Wrapper::_update_accel_calibration(), DfMPU6050Wrapper::_update_gyro_calibration(), DfLsm9ds1Wrapper::_update_gyro_calibration(), DfMpu9250Wrapper::_update_gyro_calibration(), DfAK8963Wrapper::_update_mag_calibration(), DfHmc5883Wrapper::_update_mag_calibration(), DfLsm9ds1Wrapper::_update_mag_calibration(), DfMpu9250Wrapper::_update_mag_calibration(), arm_auth_init(), AttitudeEstimatorQ::AttitudeEstimatorQ(), control::BlockParamBase::BlockParamBase(), CameraFeedback::CameraFeedback(), CameraTrigger::CameraTrigger(), Preflight::check_calibration(), DfMpu9250Wrapper::DfMpu9250Wrapper(), do_accel(), do_accel_calibration(), do_airspeed_calibration(), do_compare(), do_gyro(), do_gyro_calibration(), do_level_calibration(), do_mag(), do_mag_calibration(), do_reset_nostart(), do_set(), do_trim_calibration(), Preflight::ekf2Check(), TemperatureCalibrationAccel::finish(), TemperatureCalibrationGyro::finish(), TemperatureCalibrationBaro::finish(), TemperatureCalibrationAccel::finish_sensor_instance(), TemperatureCalibrationGyro::finish_sensor_instance(), TemperatureCalibrationBaro::finish_sensor_instance(), FixedwingAttitudeControl::FixedwingAttitudeControl(), land_detector::FixedwingLandDetector::FixedwingLandDetector(), FixedwingPositionControl::FixedwingPositionControl(), get_parameter_value(), get_params(), CameraInterface::get_pins(), BATT_SMBUS::get_startup_info(), GroundRoverAttitudeControl::GroundRoverAttitudeControl(), GroundRoverPositionControl::GroundRoverPositionControl(), MavlinkReceiver::handle_message_optical_flow_rad(), hil_state_transition(), Preflight::imuConsistencyCheck(), inav_parameters_init(), TFMINI::init(), SF0X::init(), SF1XX::init(), TERARANGER::init(), PX4FLOW::init(), PX4IO::init(), MK::init(), MPU6000::init(), UavcanNode::init(), MPU9250::init(), sensors::initialize_parameter_handles(), sensors::TemperatureCompensation::initialize_parameter_handles(), GPS::initializeCommunicationDump(), vmount::InputMavlinkCmdMount::InputMavlinkCmdMount(), PX4IO::io_set_rc_config(), landing_target_estimator::LandingTargetEstimator::LandingTargetEstimator(), linux_pwm_out_main(), load_mon::LoadMon::LoadMon(), px4::logger::Logger::Logger(), mag_calibrate_all(), Preflight::magConsistencyCheck(), IridiumSBD::main_loop(), Mavlink::mavlink_update_system(), MavlinkReceiver::MavlinkReceiver(), land_detector::MulticopterLandDetector::MulticopterLandDetector(), uart_esc::parameters_init(), rc_receiver::parameters_init(), mpu9x50::parameters_init(), sensors::VotedSensorsUpdate::parameters_update(), ParameterTest::ParameterTest(), Simulator::pollForMAVLinkMessages(), Preflight::preflightCheck(), Simulator::publish_flow_topic(), rc_calibration_check(), sensors::RCUpdate::rc_parameter_map_poll(), read_accelerometer_avg(), px4::Replay::readAndApplyParameter(), Commander::run(), GPS::run(), MavlinkReceiver::send_flight_information(), TemperatureCalibrationBase::set_parameter(), px4::Replay::setUserParams(), ParameterTest::SimpleFind(), Simulator::Simulator(), snapdragon_pwm_out_main(), Standard::Standard(), Tailsitter::Tailsitter(), TemperatureCalibration::task_main(), PX4IO::task_main(), task_main(), test_param(), Tiltrotor::Tiltrotor(), uavcan_main(), uavcannode_start(), Syslink::update_params(), RGBLED::update_params(), linux_pwm_out::update_params(), PWMSim::update_params(), snapdragon_pwm::update_params(), UavcanNode::update_params(), PX4FMU::update_params(), PX4FMU::update_pwm_rev_mask(), PX4FMU::update_pwm_trims(), FixedwingAttitudeControl::vehicle_status_poll(), FixedwingPositionControl::vehicle_status_poll(), VtolAttitudeControl::VtolAttitudeControl(), land_detector::VtolLandDetector::VtolLandDetector(), wind_estimator_main(), px4::logger::Logger::write_version(), and BATT_SMBUS::~BATT_SMBUS().
static struct param_wbuf_s* param_find_changed (param_t param) static
Locate the modified parameter structure for a parameter, if it exists.
Parameters
param The parameter being searched.
Returns
The structure holding the modified value, or NULL if the parameter has not been modified.
Definition at line 285 of file param.c.
References param_wbuf_s::param, param_assert_locked(), param_compare_values(), param_values, and utarray_find.
Referenced by param_foreach(), param_get_value_ptr(), param_reset(), param_set_internal(), param_value_is_default(), and param_value_unsaved().
param_t param_find_internal (const char * name, bool notification) static
Definition at line 330 of file param.c.
References get_param_info_count(), PARAM_INVALID, param_set_used_internal(), perf_begin(), and perf_end().
Referenced by param_find(), and param_find_no_notification().
param_t param_find_no_notification (const char * name)
Look up a parameter by name.
Parameters
name The canonical name of the parameter being looked up.
Returns
A handle to the parameter, or PARAM_INVALID if the parameter does not exist.
Definition at line 377 of file param.c.
Referenced by do_find(), MavlinkParametersManager::handle_message(), and param_import_callback().
param_t param_for_index (unsigned index)
Look up a parameter by index.
Parameters
index An index from 0 to n, where n is param_count()-1.
Returns
A handle to the parameter, or PARAM_INVALID if the index is out of range.
Definition at line 409 of file param.c.
Referenced by do_show_index(), ParameterTest::exportImportAll(), MavlinkParametersManager::send_one(), MavlinkParametersManager::send_untransmitted(), px4::logger::Logger::write_changed_parameters(), and px4::logger::Logger::write_parameters().
param_t param_for_used_index (unsigned index)
Look up an used parameter by index.
Parameters
index The parameter to obtain the index for.
Returns
The index of the parameter in use, or -1 if the parameter does not exist.
Definition at line 421 of file param.c.
Referenced by do_show_index(), MavlinkParametersManager::handle_message(), and sensors::RCUpdate::rc_parameter_map_poll().
void param_foreach (void(*)(void *arg, param_t param) func, void * arg, bool only_changed, bool only_used)
Apply a function to each parameter.
Note that the parameter set is not locked during the traversal. It also does not hold an internal state, so the callback function can block or sleep between parameter callbacks.
Parameters
func The function to invoke for each parameter.
arg Argument passed to the function.
only_changed If true, the function is only called for parameters whose values have been changed from the default.
only_changed If true, the function is only called for parameters which have been used in one of the running applications.
Definition at line 1318 of file param.c.
Referenced by do_show().
int param_get (param_t param, void * val)
Copy the value of a parameter.
Parameters
param A handle returned by param_find or passed by param_foreach.
val Where to return the value, assumed to point to suitable storage for the parameter type. For structures, a bitwise copy of the structure is performed to this address.
Returns
Zero if the parameter's value could be returned, nonzero otherwise.
Definition at line 590 of file param.c.
Referenced by ParameterTest::_assert_parameter_float_value(), ParameterTest::_assert_parameter_int_value(), land_detector::LandDetector::_check_params(), DfMPU6050Wrapper::_update_accel_calibration(), DfLsm9ds1Wrapper::_update_accel_calibration(), DfMpu9250Wrapper::_update_accel_calibration(), DfMPU6050Wrapper::_update_gyro_calibration(), DfLsm9ds1Wrapper::_update_gyro_calibration(), DfMpu9250Wrapper::_update_gyro_calibration(), DfAK8963Wrapper::_update_mag_calibration(), DfHmc5883Wrapper::_update_mag_calibration(), DfLsm9ds1Wrapper::_update_mag_calibration(), DfMpu9250Wrapper::_update_mag_calibration(), land_detector::VtolLandDetector::_update_params(), land_detector::FixedwingLandDetector::_update_params(), land_detector::MulticopterLandDetector::_update_params(), landing_target_estimator::LandingTargetEstimator::_update_params(), arm_auth_update(), CameraFeedback::CameraFeedback(), CameraTrigger::CameraTrigger(), Preflight::check_calibration(), px4::logger::Logger::check_free_space(), DfMpu9250Wrapper::DfMpu9250Wrapper(), do_accel(), do_accel_calibration(), do_airspeed_calibration(), do_compare(), do_gyro(), do_gyro_calibration(), do_level_calibration(), do_mag(), do_reset_nostart(), do_set(), do_show_index(), do_show_print(), do_trim_calibration(), Preflight::ekf2Check(), ParameterTest::exportImport(), ParameterTest::exportImportAll(), px4::logger::Logger::get_log_time(), get_parameter_value(), CameraInterface::get_pins(), BATT_SMBUS::get_startup_info(), MavlinkParametersManager::handle_message(), MavlinkReceiver::handle_message_battery_status(), MavlinkReceiver::handle_message_optical_flow_rad(), hil_state_transition(), Preflight::imuConsistencyCheck(), inav_parameters_update(), TFMINI::init(), SF0X::init(), SF1XX::init(), TERARANGER::init(), PX4FLOW::init(), PX4IO::init(), MPU6000::init(), UavcanNode::init(), MPU9250::init(), sensors::TemperatureCompensation::initialize_parameter_handles(), GPS::initializeCommunicationDump(), vmount::InputMavlinkCmdMount::InputMavlinkCmdMount(), PX4IO::io_set_rc_config(), linux_pwm_out_main(), load_mon::LoadMon::LoadMon(), mag_calibrate_all(), Preflight::magConsistencyCheck(), IridiumSBD::main_loop(), Mavlink::mavlink_update_system(), sensors::TemperatureCompensation::parameters_update(), Tailsitter::parameters_update(), Standard::parameters_update(), Tiltrotor::parameters_update(), sensors::VotedSensorsUpdate::parameters_update(), rc_receiver::parameters_update(), uart_esc::parameters_update(), GroundRoverAttitudeControl::parameters_update(), mpu9x50::parameters_update(), GroundRoverPositionControl::parameters_update(), VtolAttitudeControl::parameters_update(), FixedwingAttitudeControl::parameters_update(), FixedwingPositionControl::parameters_update(), Simulator::pollForMAVLinkMessages(), Preflight::preflightCheck(), Simulator::publish_flow_topic(), rc_calibration_check(), read_accelerometer_avg(), Commander::run(), px4::logger::Logger::run(), GPS::run(), MavlinkReceiver::send_flight_information(), MavlinkParametersManager::send_param(), ParameterTest::SimpleFind(), Simulator::Simulator(), snapdragon_pwm_out_main(), TemperatureCalibration::task_main(), MK::task_main(), PX4IO::task_main(), task_main(), test_param(), uavcan_main(), uavcannode_start(), control::BlockParam< T >::update(), control::BlockParam< float >::update(), do_not_explicitly_use_this_namespace::Param< float, p >::update(), do_not_explicitly_use_this_namespace::Param< float &, p >::update(), do_not_explicitly_use_this_namespace::Param< int32_t, p >::update(), do_not_explicitly_use_this_namespace::Param< int32_t &, p >::update(), do_not_explicitly_use_this_namespace::Param< bool, p >::update(), AttitudeEstimatorQ::update_parameters(), sensors::update_parameters(), Syslink::update_params(), RGBLED::update_params(), linux_pwm_out::update_params(), PWMSim::update_params(), snapdragon_pwm::update_params(), update_params(), UavcanNode::update_params(), PX4FMU::update_params(), PX4FMU::update_pwm_rev_mask(), PX4FMU::update_pwm_trims(), wind_estimator_main(), px4::logger::Logger::write_changed_parameters(), px4::logger::Logger::write_parameters(), and px4::logger::Logger::write_version().
const char* param_get_default_file (void)
Get the default parameter file name.
Returns
The path to the current default parameter file; either as a result of a call to param_set_default_file, or the built-in default.
Definition at line 950 of file param.c.
Referenced by param_load_default(), param_main(), and param_save_default().
int param_get_index (param_t param)
Look up the index of a parameter.
Parameters
param The parameter to obtain the index for.
Returns
The index, or -1 if the parameter does not exist.
Definition at line 450 of file param.c.
Referenced by do_show_index(), do_show_print(), param_set_used_internal(), and param_used().
int param_get_used_index (param_t param)
Look up the index of an used parameter.
Parameters
param The parameter to obtain the index for.
Returns
The index of the parameter in use, or -1 if the parameter does not exist.
Definition at line 460 of file param.c.
Referenced by do_show_index(), do_show_print(), and MavlinkParametersManager::send_param().
static const void* param_get_value_ptr (param_t param) static
Obtain a pointer to the storage allocated for a parameter.
Parameters
param The parameter whose storage is sought.
Returns
A pointer to the parameter value, or NULL if the parameter does not exist.
Definition at line 556 of file param.c.
References handle_in_range(), param_value_u::p, param_wbuf_s::param, param_assert_locked(), param_find_changed(), param_type(), PARAM_TYPE_STRUCT, PARAM_TYPE_STRUCT_MAX, param_wbuf_s::val, and param_info_s::val.
Referenced by param_export(), param_get(), param_hash_check(), and param_set_internal().
uint32_t param_hash_check (void)
Generate the hash of all parameters and their values.
Returns
CRC32 hash of all param_ids and values
Definition at line 1337 of file param.c.
Referenced by MavlinkParametersManager::handle_message(), and MavlinkParametersManager::send_one().
int param_import (int fd)
Import parameters from a file, discarding any unrecognized parameters.
This function merges the imported parameters with the current parameter set.
Parameters
fd File descriptor to import from. (Currently expected to be a file.)
Returns
Zero on success, nonzero if an error occurred during import. Note that in the failure case, parameters may be inconsistent.
Definition at line 1299 of file param.c.
Referenced by do_import(), ParameterTest::exportImportAll(), and param_main().
static int param_import_callback (bson_decoder_t decoder, void * private, bson_node_t node) static
Definition at line 1153 of file param.c.
References BSON_BIN_BINARY, BSON_BINDATA, bson_decoder_copy_data(), bson_decoder_data_pending(), BSON_DOUBLE, BSON_EOO, BSON_INT32, bson_node_s::d, debug, f(), bson_node_s::i, param_import_state::mark_saved, bson_node_s::name, param_find_no_notification(), PARAM_INVALID, param_set_internal(), param_size(), param_type(), PARAM_TYPE_FLOAT, PARAM_TYPE_INT32, PX4_ERR, PX4_WARN, state, bson_node_s::subtype, and bson_node_s::type.
Referenced by param_import_internal().
static int param_import_internal (int fd, bool mark_saved) static
Definition at line 1276 of file param.c.
References bson_decoder_init_file(), bson_decoder_next(), param_import_state::mark_saved, param_import_callback(), PX4_ERR, and usleep().
Referenced by param_import(), and param_load().
void param_init (void)
Initialize the param backend.
Call this on startup before calling any other methods.
Definition at line 230 of file param.c.
Referenced by board_app_initialize().
bool param_is_volatile (param_t param)
Obtain the volatile state of a parameter.
Parameters
param A handle returned by param_find or passed by param_foreach.
Returns
true if the parameter is volatile
Definition at line 493 of file param.c.
References handle_in_range(), param_wbuf_s::param, and param_info_s::volatile_param.
Referenced by param_hash_check().
int param_load (int fd)
Load parameters from a file.
This function resets all parameters to their default values, then loads new values from a file.
Parameters
fd File descriptor to import from. (Currently expected to be a file.)
Returns
Zero on success, nonzero if an error occurred during import. Note that in the failure case, parameters may be inconsistent.
Definition at line 1311 of file param.c.
Referenced by do_load(), and param_load_default().
int param_load_default (void)
Load parameters from the default parameter file.
Returns
0 on success, 1 if all params have not yet been stored, -1 if device open failed, -2 if writing parameters failed
Definition at line 1001 of file param.c.
Referenced by commander_low_prio_loop(), ParameterTest::exportImport(), ParameterTest::exportImportAll(), and param_main().
static void param_lock_reader (void) static
lock the parameter store for read access
Definition at line 178 of file param.c.
References px4_sem_post, px4_sem_wait, and reader_lock_holders.
Referenced by param_export(), param_get(), param_hash_check(), param_value_is_default(), and param_value_unsaved().
static void param_lock_writer (void) static
lock the parameter store for write access
Definition at line 194 of file param.c.
References px4_sem_wait.
Referenced by autosave_worker(), param_control_autosave(), param_reset(), param_reset_all_internal(), param_save_default(), and param_set_internal().
const char* param_name (param_t param)
Obtain the name of a parameter.
Parameters
param A handle returned by param_find or passed by param_foreach.
Returns
The name assigned to the parameter, or NULL if the handle is invalid.
Definition at line 487 of file param.c.
Referenced by do_compare(), do_set(), do_show_index(), do_show_print(), control::BlockParamBase::getName(), param_export(), param_export_internal(), param_hash_check(), param_reset_excludes(), px4::Replay::readAndApplyParameter(), MavlinkParametersManager::send_param(), MavlinkParametersManager::send_untransmitted(), px4::Replay::setUserParams(), px4::logger::Logger::write_changed_parameters(), and px4::logger::Logger::write_parameters().
void param_notify_changes (void)
Notify the system about parameter changes.
Can be used for example after several calls to param_set_no_notification() to avoid unnecessary system notifications.
Definition at line 324 of file param.c.
Referenced by do_accel_calibration(), do_gyro_calibration(), do_level_calibration(), do_mag_calibration(), and TemperatureCalibration::task_main().
int param_reset (param_t param)
Reset a parameter to its default value.
This function frees any storage used by struct parameters, and returns the parameter to its default value.
Parameters
param A handle returned by param_find or passed by param_foreach.
Returns
Zero on success, nonzero on failure
Definition at line 846 of file param.c.
Referenced by param_reset_excludes(), and test_param().
void param_reset_all (void)
Reset all parameters to their default values.
This function also releases the storage used by struct parameters.
Definition at line 899 of file param.c.
Referenced by commander_low_prio_loop(), do_reset(), do_reset_nostart(), ParameterTest::exportImportAll(), flash_param_load(), and ParameterTest::ResetAll().
static void param_reset_all_internal (bool auto_save) static
Definition at line 878 of file param.c.
References _param_notify_changes(), param_autosave(), param_lock_writer(), param_unlock_writer(), param_values, and utarray_free.
Referenced by param_load(), and param_reset_all().
void param_reset_excludes (const char * excludes[], int num_excludes)
Reset all parameters to their default values except for excluded parameters.
This function also releases the storage used by struct parameters.
Parameters
excludes Array of param names to exclude from resetting. Use a wildcard at the end to exclude parameters with a certain prefix.
num_excludes The number of excludes provided.
Definition at line 905 of file param.c.
Referenced by do_reset(), do_reset_nostart(), ParameterTest::ResetAllExcludesBoundaryCheck(), ParameterTest::ResetAllExcludesOne(), ParameterTest::ResetAllExcludesTwo(), and ParameterTest::ResetAllExcludesWildcard().
int param_save_default (void)
Save parameters to the default file.
Note: this method requires a large amount of stack size!
This function saves all parameters with non-default values.
Returns
Zero on success.
Definition at line 956 of file param.c.
Referenced by autosave_worker(), commander_low_prio_loop(), do_airspeed_calibration(), do_save_default(), ParameterTest::exportImport(), ParameterTest::exportImportAll(), param_main(), and TemperatureCalibration::task_main().
int param_set (param_t param, const void * val)
Set the value of a parameter.
Parameters
param A handle returned by param_find or passed by param_foreach.
val The value to set; assumed to point to a variable of the parameter type. For structures, the pointer is assumed to point to a structure to be copied.
Returns
Zero if the parameter's value could be set from a scalar, nonzero otherwise.
Definition at line 803 of file param.c.
Referenced by ParameterTest::_set_all_int_parameters_to(), control::BlockParam< float >::commit(), do_not_explicitly_use_this_namespace::Param< float, p >::commit(), do_not_explicitly_use_this_namespace::Param< float &, p >::commit(), do_not_explicitly_use_this_namespace::Param< int32_t, p >::commit(), do_not_explicitly_use_this_namespace::Param< int32_t &, p >::commit(), do_not_explicitly_use_this_namespace::Param< bool, p >::commit(), do_airspeed_calibration(), do_reset_nostart(), do_set(), do_trim_calibration(), MavlinkParametersManager::handle_message(), PX4IO::init(), mag_calibrate_all(), sensors::VotedSensorsUpdate::parameters_update(), px4::Replay::readAndApplyParameter(), sensors::RCUpdate::set_params_from_rc(), px4::Replay::setUserParams(), test_param(), and BATT_SMBUS::~BATT_SMBUS().
int param_set_default_file (const char * filename)
Set the default parameter file name.
Parameters
filename Path to the default parameter file. The file is not require to exist.
Returns
Zero on success.
Definition at line 934 of file param.c.
Referenced by param_main().
static int param_set_internal (param_t param, const void * val, bool mark_saved, bool notify_changes) static
Definition at line 690 of file param.c.
References _param_notify_changes(), param_value_u::f, handle_in_range(), param_value_u::i, param_value_u::p, param_wbuf_s::param, param_autosave(), param_compare_values(), param_find_changed(), param_get_value_ptr(), param_get_value_ptr_external(), param_icd, param_lock_writer(), param_set_external(), param_size(), param_type(), PARAM_TYPE_FLOAT, PARAM_TYPE_INT32, PARAM_TYPE_STRUCT, PARAM_TYPE_STRUCT_MAX, param_unlock_writer(), param_values, perf_begin(), perf_end(), PX4_ERR, param_wbuf_s::unsaved, utarray_new, utarray_push_back, utarray_sort, and param_wbuf_s::val.
Referenced by param_import_callback(), param_set(), and param_set_no_notification().
int param_set_no_notification (param_t param, const void * val)
Set the value of a parameter, but do not notify the system about the change.
Parameters
param A handle returned by param_find or passed by param_foreach.
val The value to set; assumed to point to a variable of the parameter type. For structures, the pointer is assumed to point to a structure to be copied.
Returns
Zero if the parameter's value could be set from a scalar, nonzero otherwise.
Definition at line 809 of file param.c.
Referenced by land_detector::LandDetector::_cycle(), CameraTrigger::CameraTrigger(), Mavlink::check_radio_config(), control::BlockParam< float >::commit_no_notification(), do_not_explicitly_use_this_namespace::Param< float, p >::commit_no_notification(), do_not_explicitly_use_this_namespace::Param< float &, p >::commit_no_notification(), do_not_explicitly_use_this_namespace::Param< int32_t, p >::commit_no_notification(), do_not_explicitly_use_this_namespace::Param< int32_t &, p >::commit_no_notification(), do_not_explicitly_use_this_namespace::Param< bool, p >::commit_no_notification(), CameraTrigger::cycle_trampoline(), do_accel_calibration(), do_gyro_calibration(), do_level_calibration(), do_mag_calibration(), ParameterTest::exportImport(), ParameterTest::exportImportAll(), TemperatureCalibrationAccel::finish(), TemperatureCalibrationGyro::finish(), TemperatureCalibrationBaro::finish(), TemperatureCalibrationAccel::finish_sensor_instance(), TemperatureCalibrationGyro::finish_sensor_instance(), TemperatureCalibrationBaro::finish_sensor_instance(), PX4IO::init(), mag_calibrate_all(), sensors::VotedSensorsUpdate::parameters_update(), Commander::run(), TemperatureCalibrationBase::set_parameter(), and sensors::update_parameters().
void param_set_used (param_t param)
Mark a parameter as used.
Only marked parameters will be sent to a GCS. A call to param_find() will mark a param as used as well.
Parameters
param A handle returned by param_find or passed by param_foreach.
Definition at line 827 of file param.c.
Referenced by do_not_explicitly_use_this_namespace::Param< float, p >::Param(), do_not_explicitly_use_this_namespace::Param< float &, p >::Param(), do_not_explicitly_use_this_namespace::Param< int32_t, p >::Param(), do_not_explicitly_use_this_namespace::Param< int32_t &, p >::Param(), and do_not_explicitly_use_this_namespace::Param< bool, p >::Param().
void param_set_used_internal (param_t param) static
Definition at line 832 of file param.c.
References bits_per_allocation_unit, param_changed_storage, and param_get_index().
Referenced by param_find_internal(), and param_set_used().
size_t param_size (param_t param)
Determine the size of a parameter.
Parameters
param A handle returned by param_find or passed by param_foreach.
Returns
The size of the parameter's value.
Definition at line 526 of file param.c.
Referenced by do_show_print(), param_export(), param_export_internal(), param_get(), param_hash_check(), param_import_callback(), and param_set_internal().
param_type_t param_type (param_t param)
Obtain the type of a parameter.
Parameters
param A handle returned by param_find or passed by param_foreach.
Returns
The type assigned to the parameter.
Definition at line 520 of file param.c.
Referenced by do_compare(), do_set(), do_show_index(), do_show_print(), ParameterTest::exportImport(), ParameterTest::exportImportAll(), MavlinkParametersManager::handle_message(), param_export(), param_export_internal(), param_get_value_ptr(), param_import_callback(), param_set_internal(), param_size(), MavlinkParametersManager::send_param(), px4::Replay::setUserParams(), test_param(), px4::logger::Logger::write_changed_parameters(), and px4::logger::Logger::write_parameters().
static void param_unlock_reader (void) static
unlock the parameter store
Definition at line 201 of file param.c.
References px4_sem_post, px4_sem_wait, and reader_lock_holders.
Referenced by param_export(), param_get(), param_hash_check(), param_value_is_default(), and param_value_unsaved().
static void param_unlock_writer (void) static
unlock the parameter store
Definition at line 217 of file param.c.
References px4_sem_post.
Referenced by autosave_worker(), param_control_autosave(), param_reset(), param_reset_all_internal(), param_save_default(), and param_set_internal().
bool param_used (param_t param)
Wether a parameter is in use in the system.
Returns
True if it has been written or read
Definition at line 815 of file param.c.
Referenced by do_show_index(), do_show_print(), param_foreach(), param_get_used_index(), param_hash_check(), MavlinkParametersManager::send_one(), MavlinkParametersManager::send_untransmitted(), px4::logger::Logger::write_changed_parameters(), and px4::logger::Logger::write_parameters().
bool param_value_is_default (param_t param)
Test whether a parameter's value has changed from the default.
Returns
If true, the parameter's value has not been changed from the default.
Definition at line 499 of file param.c.
Referenced by do_compare(), do_set(), do_show_index(), and do_show_print().
bool param_value_unsaved (param_t param)
Test whether a parameter's value has been changed but not saved.
Returns
If true, the parameter's value has not been saved.
Definition at line 509 of file param.c.
Referenced by do_compare(), do_set(), do_show_index(), do_show_print(), MavlinkParametersManager::send_untransmitted(), and px4::logger::Logger::write_changed_parameters().
Variable Documentation
bool autosave_disabled = false static
Definition at line 99 of file param.c.
Referenced by autosave_worker(), param_autosave(), and param_control_autosave().
bool autosave_scheduled = false static
Definition at line 98 of file param.c.
Referenced by autosave_worker(), param_autosave(), and param_control_autosave().
struct work_s autosave_work static
Definition at line 97 of file param.c.
Referenced by param_autosave(), and param_control_autosave().
const int bits_per_allocation_unit = (sizeof(*param_changed_storage) * 8)
Definition at line 120 of file param.c.
Referenced by get_param_info_count(), param_count_used(), param_for_used_index(), param_get_used_index(), param_set_used_internal(), and param_used().
hrt_abstime last_autosave_timestamp = 0 static
Definition at line 96 of file param.c.
Referenced by autosave_worker(), and param_autosave().
uint8_t* param_changed_storage = NULL
Definition at line 118 of file param.c.
Referenced by get_param_info_count(), param_count_used(), param_for_used_index(), param_get_used_index(), param_set_used_internal(), and param_used().
const char* param_default_file = PX4_ROOTFSDIR"/eeprom/parameters" static
Definition at line 76 of file param.c.
Referenced by param_get_default_file().
perf_counter_t param_export_perf static
Definition at line 166 of file param.c.
perf_counter_t param_find_perf static
Definition at line 167 of file param.c.
perf_counter_t param_get_perf static
Definition at line 168 of file param.c.
FLASH_PARAMS_EXPOSE const UT_icd param_icd = {sizeof(struct param_wbuf_s), NULL, NULL, NULL}
array info for the modified parameters array
Definition at line 147 of file param.c.
Referenced by param_set_internal().
const struct param_info_s* param_info_base = (const struct param_info_s *) &px4_parameters static
Array of static parameter info.
Definition at line 105 of file param.c.
unsigned int param_instance = 0 static
Definition at line 152 of file param.c.
px4_sem_t param_sem static
this protects against concurrent access to param_values
Definition at line 162 of file param.c.
px4_sem_t param_sem_save static
this protects against concurrent param saves (file or flash access).
we use a separate lock to allow concurrent param reads and saves. a param_set could still be blocked by a param save, because it needs to take the reader lock
Definition at line 171 of file param.c.
perf_counter_t param_set_perf static
Definition at line 169 of file param.c.
orb_advert_t param_topic = NULL static
parameter update topic handle
Definition at line 151 of file param.c.
char* param_user_file = NULL static
Definition at line 77 of file param.c.
Referenced by param_get_default_file(), and param_set_default_file().
FLASH_PARAMS_EXPOSE UT_array* param_values
flexible array holding modified parameter values
Definition at line 144 of file param.c.
Referenced by param_export(), param_find_changed(), param_reset(), param_reset_all_internal(), and param_set_internal().
int reader_lock_holders = 0 static
Definition at line 163 of file param.c.
Referenced by param_lock_reader(), and param_unlock_reader().
px4_sem_t reader_lock_holders_lock static
this protects against concurrent access to reader_lock_holders
Definition at line 164 of file param.c.
int size_param_changed_storage_bytes = 0
Definition at line 119 of file param.c.
Referenced by get_param_info_count(), param_count_used(), param_for_used_index(), and param_get_used_index().