PX4 Firmware: src/systemcmds/led_control/led_control.cpp File Reference
led_control.cpp File Reference
#include <px4_platform_common/getopt.h>
#include <px4_platform_common/module.h>
#include <px4_platform_common/log.h>
#include <stdlib.h>
#include <unistd.h>
#include <drivers/drv_hrt.h>
#include <drivers/drv_led.h>
#include <uORB/PublicationQueued.hpp>
#include <uORB/topics/led_control.h>
Functions
static void usage ()
__EXPORT int led_control_main (int argc, char *argv[])
static void publish_led_control (led_control_s &led_control)
static void run_led_test1 ()
Function Documentation
led_control_main()
int led_control_main (int argc, char * argv[])
Definition at line 113 of file led_control.cpp.
References led_control_s::color, led_control, led_control_s::led_mask, led_control_s::mode, led_control_s::num_blinks, led_control_s::priority, publish_led_control(), run_led_test1(), and usage().
publish_led_control()
static void publish_led_control (led_control_s & led_control) static
Definition at line 57 of file led_control.cpp.
References hrt_absolute_time(), led_control_pub, ORB_ID, and led_control_s::timestamp.
Referenced by TemperatureCalibration::exit_task(), led_control_main(), and run_led_test1().
run_led_test1()
static void run_led_test1 () static
Definition at line 65 of file led_control.cpp.
References BOARD_MAX_LEDS, led_control_s::color, led_control, led_control_s::led_mask, led_control_s::mode, led_control_s::priority, and publish_led_control().
Referenced by led_control_main().
usage()
static void usage (void) static
Definition at line 239 of file led_control.cpp.
Referenced by led_control_main().