PX4 Firmware: src/modules/simulator/ledsim/led.cpp File Reference
led.cpp File Reference
#include <px4_platform_common/px4_config.h>
#include <drivers/drv_board_led.h>
#include <stdio.h>
#include "VirtDevObj.hpp"
Classes
class LED
Functions
__BEGIN_DECLS void led_init ()
void led_on (int led)
void led_off (int led)
void led_toggle (int led)
void drv_led_start (void)
Function Documentation
drv_led_start()
void drv_led_start (void)
Definition at line 126 of file led.cpp.
References LED::init().
Referenced by Simulator::start().
led_init()
__BEGIN_DECLS void led_init ()
Definition at line 288 of file commander_helper.cpp.
References blink_msg_end, h_leds, hrt_absolute_time(), LED0_DEVICE_PATH, LED_AMBER, LED_BLUE, led_control, led_control_pub, LED_GREEN, led_control_s::led_mask, led_off(), LED_ON, led_control_s::mode, orb_advertise_queue(), ORB_ID, led_control_s::priority, and led_control_s::timestamp.
led_off()
void led_off (int led)
Definition at line 343 of file commander_helper.cpp.
References h_leds, and LED_OFF.
Referenced by led_init().
led_on()
void led_on (int led)
Definition at line 338 of file commander_helper.cpp.
References h_leds, and LED_ON.
led_toggle()
void led_toggle (int led)
Definition at line 333 of file commander_helper.cpp.
References h_leds, and LED_TOGGLE.