PX4 Firmware: icm20948 Namespace Reference
icm20948 Namespace Reference
Local functions in support of the shell command.
Classes
struct icm20948_bus_option
Functions
bool start_bus (icm20948_bus_option &bus, enum Rotation rotation)
start driver for a specific bus option
icm20948_bus_option * find_bus (enum ICM20948_BUS busid)
find a bus structure for a busid
int start (enum ICM20948_BUS busid, enum Rotation rotation)
Start the driver.
int stop (enum ICM20948_BUS busid)
int info (enum ICM20948_BUS busid)
Print a little info about the driver.
int usage ()
Prints info about the driver argument usage.
Variables
struct icm20948::icm20948_bus_option bus_options []
Detailed Description
Local functions in support of the shell command.
Function Documentation
find_bus()
struct icm20948_bus_option * icm20948::find_bus (enum ICM20948_BUS busid)
find a bus structure for a busid
Definition at line 105 of file icm20948_main.cpp.
References bus_options, icm20948::icm20948_bus_option::dev, ICM20948_BUS_ALL, and NUM_BUS_OPTIONS.
Referenced by info(), and stop().
info()
int icm20948::info (enum ICM20948_BUS busid)
Print a little info about the driver.
Definition at line 237 of file icm20948_main.cpp.
References icm20948::icm20948_bus_option::dev, find_bus(), and ICM20948::print_info().
Referenced by icm20948_main().
start()
int icm20948::start (enum ICM20948_BUS busid, enum Rotation rotation)
Start the driver.
This function only returns if the driver is up and running or failed to detect the sensor.
Definition at line 193 of file icm20948_main.cpp.
References bus_options, icm20948::icm20948_bus_option::dev, ICM20948_BUS_ALL, NUM_BUS_OPTIONS, and start_bus().
Referenced by icm20948_main().
start_bus()
bool icm20948::start_bus (icm20948_bus_option & bus, enum Rotation rotation)
start driver for a specific bus option
Definition at line 122 of file icm20948_main.cpp.
References AK09916_I2C_interface(), icm20948::icm20948_bus_option::busid, icm20948::icm20948_bus_option::dev, ICM20948_BUS_I2C_EXTERNAL, ICM20948_BUS_I2C_INTERNAL, and OK.
Referenced by start().
stop()
int icm20948::stop (enum ICM20948_BUS busid)
Definition at line 217 of file icm20948_main.cpp.
References icm20948::icm20948_bus_option::dev, and find_bus().
Referenced by icm20948_main().
usage()
int icm20948::usage (void)
Prints info about the driver argument usage.
Prints info about the driver argument usage.
Definition at line 252 of file icm20948_main.cpp.
Referenced by icm20948_main().
Variable Documentation
bus_options
struct icm20948::icm20948_bus_option icm20948::bus_options[]
Initial value:
= {
}
Referenced by find_bus(), and start().