PX4 Firmware: src/platforms/px4_tasks.h File Reference
px4_tasks.h File Reference
#include <stdbool.h>
Macros
#define SCHED_PRIORITY_FAST_DRIVER (SCHED_PRIORITY_MAX - 0)
#define SCHED_PRIORITY_ATTITUDE_CONTROL (SCHED_PRIORITY_MAX - 4)
#define SCHED_PRIORITY_ACTUATOR_OUTPUTS (SCHED_PRIORITY_MAX - 4)
#define SCHED_PRIORITY_POSITION_CONTROL (SCHED_PRIORITY_MAX - 5)
#define SCHED_PRIORITY_ESTIMATOR (SCHED_PRIORITY_MAX - 5)
#define SCHED_PRIORITY_SENSOR_HUB (SCHED_PRIORITY_MAX - 6)
#define SCHED_PRIORITY_LOG_CAPTURE (SCHED_PRIORITY_MAX - 10)
#define SCHED_PRIORITY_SLOW_DRIVER (SCHED_PRIORITY_MAX - 35)
#define SCHED_PRIORITY_NAVIGATION (SCHED_PRIORITY_DEFAULT + 5)
#define SCHED_PRIORITY_LOG_WRITER (SCHED_PRIORITY_DEFAULT - 10)
#define SCHED_PRIORITY_PARAMS (SCHED_PRIORITY_DEFAULT - 15)
Typedefs
typedef int(* px4_main_t) (int argc, char *argv[])
Functions
__BEGIN_DECLS __EXPORT void px4_systemreset (bool to_bootloader) noreturn_function
Reboots the board (without waiting for clean shutdown).
__EXPORT px4_task_t px4_task_spawn_cmd (const char *name, int scheduler, int priority, int stack_size, px4_main_t entry, char *const argv[])
Starts a task and performs any specific accounting, scheduler setup, etc.
__EXPORT int px4_task_delete (px4_task_t pid)
Deletes a task - does not do resource cleanup.
__EXPORT int px4_task_kill (px4_task_t pid, int sig)
Send a signal to a task.
__EXPORT void px4_task_exit (int ret)
Exit current task with return value.
__EXPORT void px4_show_tasks (void)
Show a list of running tasks.
__EXPORT bool px4_task_is_running (const char *taskname)
See if a task is running.
__EXPORT const char * px4_get_taskname (void)
return the name of the current task
Detailed Description
Author
Lorenz Meier loren.nosp@m.z@px.nosp@m.4.io
Mark Charlebois (2015) charl.nosp@m.ebm@.nosp@m.gmail.nosp@m..com
Preserve existing task API call signature with OS abstraction
Definition in file px4_tasks.h.
Macro Definition Documentation
#define SCHED_PRIORITY_ACTUATOR_OUTPUTS (SCHED_PRIORITY_MAX - 4)
Definition at line 119 of file px4_tasks.h.
Referenced by PX4IO::init(), UavcanEsc::start(), UavcanNode::start(), PWMSim::task_spawn(), TAP_ESC::task_spawn(), and PX4FMU::task_spawn().
#define SCHED_PRIORITY_ATTITUDE_CONTROL (SCHED_PRIORITY_MAX - 4)
Definition at line 115 of file px4_tasks.h.
Referenced by VtolAttitudeControl::start(), MulticopterAttitudeControl::task_spawn(), and FixedwingAttitudeControl::task_spawn().
#define SCHED_PRIORITY_ESTIMATOR (SCHED_PRIORITY_MAX - 5)
Definition at line 132 of file px4_tasks.h.
Referenced by AttitudeEstimatorQ::start(), LocalPositionEstimatorModule::task_spawn(), and Ekf2::task_spawn().
#define SCHED_PRIORITY_FAST_DRIVER (SCHED_PRIORITY_MAX - 0)
Definition at line 109 of file px4_tasks.h.
#define SCHED_PRIORITY_LOG_CAPTURE (SCHED_PRIORITY_MAX - 10)
Definition at line 141 of file px4_tasks.h.
Referenced by px4::logger::Logger::task_spawn().
#define SCHED_PRIORITY_LOG_WRITER (SCHED_PRIORITY_DEFAULT - 10)
Definition at line 150 of file px4_tasks.h.
#define SCHED_PRIORITY_NAVIGATION (SCHED_PRIORITY_DEFAULT + 5)
Definition at line 148 of file px4_tasks.h.
Referenced by Navigator::task_spawn().
#define SCHED_PRIORITY_PARAMS (SCHED_PRIORITY_DEFAULT - 15)
Definition at line 151 of file px4_tasks.h.
#define SCHED_PRIORITY_POSITION_CONTROL (SCHED_PRIORITY_MAX - 5)
Definition at line 125 of file px4_tasks.h.
Referenced by GroundRoverPositionControl::start(), MulticopterPositionControl::start(), and FixedwingPositionControl::task_spawn().
#define SCHED_PRIORITY_SENSOR_HUB (SCHED_PRIORITY_MAX - 6)
Definition at line 137 of file px4_tasks.h.
Referenced by Sensors::task_spawn().
#define SCHED_PRIORITY_SLOW_DRIVER (SCHED_PRIORITY_MAX - 35)
Definition at line 145 of file px4_tasks.h.
Referenced by IridiumSBD::start(), RCInput::task_spawn(), and GPS::task_spawn().
Typedef Documentation
typedef int(* px4_main_t) (int argc, char *argv[])
Definition at line 154 of file px4_tasks.h.
Function Documentation
__EXPORT const char* px4_get_taskname (void)
return the name of the current task
Referenced by uORB::Manager::orb_advertise_multi().
__EXPORT void px4_show_tasks (void)
Show a list of running tasks.
__BEGIN_DECLS __EXPORT void px4_systemreset (bool to_bootloader)
Reboots the board (without waiting for clean shutdown).
Modules should use px4_shutdown_request() in most cases.
Referenced by cb_reboot(), RestartRequestHandler::handleRestartRequest(), px4_shutdown_unlock(), shutdown_main(), shutdown_worker(), and test_mount().
__EXPORT int px4_task_delete (px4_task_t pid)
Deletes a task - does not do resource cleanup.
Referenced by simulator_main(), AttitudeEstimatorQ::~AttitudeEstimatorQ(), CameraFeedback::~CameraFeedback(), GPSSIM::~GPSSIM(), GroundRoverAttitudeControl::~GroundRoverAttitudeControl(), GroundRoverPositionControl::~GroundRoverPositionControl(), MulticopterPositionControl::~MulticopterPositionControl(), ulanding::Radar::~Radar(), and VtolAttitudeControl::~VtolAttitudeControl().
__EXPORT void px4_task_exit (int ret)
Exit current task with return value.
Referenced by Mavlink::Mavlink(), and Commander::run().
__EXPORT bool px4_task_is_running (const char * taskname)
See if a task is running.
__EXPORT int px4_task_kill (px4_task_t pid, int sig)
Send a signal to a task.
Referenced by mpu9x50::data_ready_isr(), and hrt_work_queue().
__EXPORT px4_task_t px4_task_spawn_cmd (const char * name, int scheduler, int priority, int stack_size, px4_main_t entry, char *const argv[])
Starts a task and performs any specific accounting, scheduler setup, etc.
Referenced by frsky_telemetry_main(), hello_main(), hott_sensors_main(), hott_telemetry_main(), hrt_test_main(), hrt_work_queue_init(), GPSSIM::init(), PX4IO::init(), MK::init(), landing_target_estimator::landing_target_estimator_main(), uORBTest::UnitTest::latency_test(), VCDevExample::main(), md25_main(), micrortps_client_main(), motor_ramp_main(), muorb_test_main(), position_estimator_inav_main(), qshell_main(), roboclaw_main(), simulator_main(), MavlinkShell::start(), Syslink::start(), bebop_flow::start(), GroundRoverAttitudeControl::start(), TemperatureCalibration::start(), GroundRoverPositionControl::start(), CameraFeedback::start(), AttitudeEstimatorQ::start(), MulticopterPositionControl::start(), VtolAttitudeControl::start(), rc_receiver::start(), UavcanEsc::start(), Mavlink::start(), linux_pwm_out::start(), ulanding::Radar::start(), IridiumSBD::start(), UavcanNode::start(), snapdragon_pwm::start(), spektrum_rc::start(), df_bebop_bus_wrapper::start(), uart_esc::start(), mpu9x50::start(), start(), LocalPositionEstimatorModule::task_spawn(), px4::Replay::task_spawn(), RCInput::task_spawn(), PWMSim::task_spawn(), MulticopterAttitudeControl::task_spawn(), Commander::task_spawn(), FixedwingAttitudeControl::task_spawn(), Navigator::task_spawn(), TAP_ESC::task_spawn(), Ekf2::task_spawn(), px4::logger::Logger::task_spawn(), GPS::task_spawn(), PX4FMU::task_spawn(), FixedwingPositionControl::task_spawn(), Sensors::task_spawn(), test_dataman(), uORBTest::UnitTest::test_multi2(), uORBTest::UnitTest::test_queue_poll_notify(), vcdev_test_main(), vmount_main(), and wqueue_test_main().