PX4 Firmware: src/modules/syslink/syslink.c File Reference
syslink.c File Reference
Crazyflie Syslink protocol implementation.
#include <px4_defines.h>
#include <fcntl.h>
#include <stdio.h>
#include <sys/ioctl.h>
#include <systemlib/err.h>
#include <poll.h>
#include <termios.h>
#include "syslink.h"
Functions
void syslink_parse_init (syslink_parse_state *state)
int syslink_parse_char (syslink_parse_state *state, char c, syslink_message_t *msg)
void syslink_compute_cksum (syslink_message_t *msg)
Variables
const char * syslink_magic = "\xbc\xcf"
Detailed Description
Crazyflie Syslink protocol implementation.
Author
Dennis Shtatnov densh.nosp@m.t@gm.nosp@m.ail.c.nosp@m.om
Definition in file syslink.c.
Function Documentation
void syslink_compute_cksum (syslink_message_t * msg)
Definition at line 140 of file syslink.c.
Referenced by Syslink::send_message(), and syslink_parse_char().
int syslink_parse_char (syslink_parse_state * state, char c, syslink_message_t * msg)
Definition at line 64 of file syslink.c.
References syslink_parse_state::index, PX4_INFO, syslink_parse_state::state, syslink_compute_cksum(), syslink_magic, SYSLINK_MAX_DATA_LEN, SYSLINK_STATE_CKSUM, SYSLINK_STATE_DATA, SYSLINK_STATE_LENGTH, SYSLINK_STATE_START, and SYSLINK_STATE_TYPE.
Referenced by Syslink::task_main().
void syslink_parse_init (syslink_parse_state * state)
Definition at line 57 of file syslink.c.
References syslink_parse_state::index, syslink_parse_state::state, and SYSLINK_STATE_START.
Referenced by Syslink::task_main().
Variable Documentation
const char* syslink_magic = "\xbc\xcf"
Definition at line 55 of file syslink.c.
Referenced by Syslink::send_message(), and syslink_parse_char().