PX4 Firmware: MavlinkStreamGroundTruth Class Reference
MavlinkStreamGroundTruth Class Reference
Public Member Functions
const char * get_name () const override
uint16_t get_id () override
unsigned get_size () override
Get maximal total messages size on update.
Public Member Functions inherited from MavlinkStream
MavlinkStream (Mavlink *mavlink)
virtual ~MavlinkStream ()=default
MavlinkStream (const MavlinkStream &)=delete
MavlinkStream & operator= (const MavlinkStream &)=delete
MavlinkStream (MavlinkStream &&)=delete
MavlinkStream & operator= (MavlinkStream &&)=delete
void set_interval (const int interval)
Get the interval.
int get_interval ()
Get the interval.
int update (const hrt_abstime &t)
Update subscriptions and send message if necessary.
virtual bool const_rate ()
virtual unsigned get_size_avg ()
Get the average message size.
bool first_message_sent () const
void reset_last_sent ()
Reset the time of last sent to 0.
Public Member Functions inherited from ListNode< MavlinkStream *>
void setSibling (MavlinkStream * sibling)
const MavlinkStream * getSibling () const
Static Public Member Functions
static const char * get_name_static ()
static uint16_t get_id_static ()
static MavlinkStream * new_instance (Mavlink *mavlink)
Protected Member Functions
MavlinkStreamGroundTruth (Mavlink *mavlink)
bool send (const hrt_abstime t) override
Protected Member Functions inherited from MavlinkStream
virtual void update_data ()
Function to collect/update data for the streams at a high rate independant of actual stream rate.
Private Member Functions
MavlinkStreamGroundTruth (MavlinkStreamGroundTruth &)=delete
MavlinkStreamGroundTruth & operator= (const MavlinkStreamGroundTruth &)=delete
Private Attributes
MavlinkOrbSubscription * _angular_velocity_sub
MavlinkOrbSubscription * _att_sub
MavlinkOrbSubscription * _gpos_sub
MavlinkOrbSubscription * _lpos_sub
uint64_t _angular_velocity_time {0}
uint64_t _att_time {0}
uint64_t _gpos_time {0}
uint64_t _lpos_time {0}
Additional Inherited Members
Protected Attributes inherited from MavlinkStream
Mavlink *const _mavlink
int _interval {1000000}
if set to negative value = unlimited rate
Protected Attributes inherited from ListNode< MavlinkStream *>
MavlinkStream * _list_node_sibling
Detailed Description
Definition at line 4756 of file mavlink_messages.cpp.
Constructor & Destructor Documentation
MavlinkStreamGroundTruth() [1/2]
MavlinkStreamGroundTruth::MavlinkStreamGroundTruth (MavlinkStreamGroundTruth &) private delete
MavlinkStreamGroundTruth() [2/2]
MavlinkStreamGroundTruth::MavlinkStreamGroundTruth (Mavlink * mavlink) inline explicit protected
Definition at line 4806 of file mavlink_messages.cpp.
Member Function Documentation
get_id()
uint16_t MavlinkStreamGroundTruth::get_id () inline override virtual
Implements MavlinkStream.
Definition at line 4774 of file mavlink_messages.cpp.
References MavlinkStreamHeartbeat::get_id_static().
get_id_static()
static uint16_t MavlinkStreamGroundTruth::get_id_static () inline static
Definition at line 4769 of file mavlink_messages.cpp.
get_name()
const char* MavlinkStreamGroundTruth::get_name () const inline override virtual
Implements MavlinkStream.
Definition at line 4759 of file mavlink_messages.cpp.
References get_name_static().
get_name_static()
static const char* MavlinkStreamGroundTruth::get_name_static () inline static
Definition at line 4764 of file mavlink_messages.cpp.
Referenced by get_name().
get_size()
unsigned MavlinkStreamGroundTruth::get_size () inline override virtual
Get maximal total messages size on update.
Implements MavlinkStream.
Definition at line 4784 of file mavlink_messages.cpp.
new_instance()
static MavlinkStream* MavlinkStreamGroundTruth::new_instance (Mavlink * mavlink) inline static
Definition at line 4779 of file mavlink_messages.cpp.
operator=()
MavlinkStreamGroundTruth& MavlinkStreamGroundTruth::operator= (const MavlinkStreamGroundTruth &) private delete
send()
bool MavlinkStreamGroundTruth::send (const hrt_abstime t) inline override protected virtual
Implements MavlinkStream.
Definition at line 4813 of file mavlink_messages.cpp.
References MavlinkStream::_mavlink, Mavlink::get_channel(), msg, and MavlinkOrbSubscription::update().
Member Data Documentation
_angular_velocity_sub
MavlinkOrbSubscription* MavlinkStreamGroundTruth::_angular_velocity_sub private
Definition at line 4791 of file mavlink_messages.cpp.
_angular_velocity_time
uint64_t MavlinkStreamGroundTruth::_angular_velocity_time {0} private
Definition at line 4796 of file mavlink_messages.cpp.
_att_sub
MavlinkOrbSubscription* MavlinkStreamGroundTruth::_att_sub private
Definition at line 4792 of file mavlink_messages.cpp.
_att_time
uint64_t MavlinkStreamGroundTruth::_att_time {0} private
Definition at line 4797 of file mavlink_messages.cpp.
_gpos_sub
MavlinkOrbSubscription* MavlinkStreamGroundTruth::_gpos_sub private
Definition at line 4793 of file mavlink_messages.cpp.
_gpos_time
uint64_t MavlinkStreamGroundTruth::_gpos_time {0} private
Definition at line 4798 of file mavlink_messages.cpp.
_lpos_sub
MavlinkOrbSubscription* MavlinkStreamGroundTruth::_lpos_sub private
Definition at line 4794 of file mavlink_messages.cpp.
_lpos_time
uint64_t MavlinkStreamGroundTruth::_lpos_time {0} private
Definition at line 4799 of file mavlink_messages.cpp.
The documentation for this class was generated from the following file:
src/modules/mavlink/mavlink_messages.cpp