PX4 Firmware: MavlinkStreamLocalPositionNEDCOV Class Reference
MavlinkStreamLocalPositionNEDCOV Class Reference
Public Member Functions
const char * get_name () const
uint16_t get_id ()
unsigned get_size ()
Get maximal total messages size on update.
Public Member Functions inherited from MavlinkStream
MavlinkStream (Mavlink *mavlink)
virtual ~MavlinkStream ()=default
MavlinkStream (const MavlinkStream &)=delete
MavlinkStream & operator= (const MavlinkStream &)=delete
MavlinkStream (MavlinkStream &&)=delete
MavlinkStream & operator= (MavlinkStream &&)=delete
void set_interval (const int interval)
Get the interval.
int get_interval ()
Get the interval.
int update (const hrt_abstime &t)
Update subscriptions and send message if necessary.
virtual bool const_rate ()
virtual unsigned get_size_avg ()
Get the average message size.
bool first_message_sent () const
void reset_last_sent ()
Reset the time of last sent to 0.
Static Public Member Functions
static const char * get_name_static ()
static uint16_t get_id_static ()
static MavlinkStream * new_instance (Mavlink *mavlink)
Protected Member Functions
MavlinkStreamLocalPositionNEDCOV (Mavlink *mavlink)
bool send (const hrt_abstime t)
Protected Member Functions inherited from MavlinkStream
virtual void update_data ()
Function to collect/update data for the streams at a high rate independant of actual stream rate.
Private Member Functions
MavlinkStreamLocalPositionNEDCOV (MavlinkStreamLocalPositionNEDCOV &)=delete
MavlinkStreamLocalPositionNEDCOV & operator= (const MavlinkStreamLocalPositionNEDCOV &)=delete
Private Attributes
MavlinkOrbSubscription * _est_sub
uint64_t _est_time
Additional Inherited Members
Public Attributes inherited from MavlinkStream
MavlinkStream * next {nullptr}
Protected Attributes inherited from MavlinkStream
Mavlink *const _mavlink
int _interval {1000000}
if set to negative value = unlimited rate
Detailed Description
Definition at line 2137 of file mavlink_messages.cpp.
Constructor & Destructor Documentation
MavlinkStreamLocalPositionNEDCOV::MavlinkStreamLocalPositionNEDCOV (MavlinkStreamLocalPositionNEDCOV &) private delete
MavlinkStreamLocalPositionNEDCOV::MavlinkStreamLocalPositionNEDCOV (Mavlink * mavlink) inline explicit protected
Definition at line 2179 of file mavlink_messages.cpp.
Member Function Documentation
uint16_t MavlinkStreamLocalPositionNEDCOV::get_id () inline virtual
Implements MavlinkStream.
Definition at line 2155 of file mavlink_messages.cpp.
References MavlinkStreamHeartbeat::get_id_static().
static uint16_t MavlinkStreamLocalPositionNEDCOV::get_id_static () inline static
Definition at line 2150 of file mavlink_messages.cpp.
const char* MavlinkStreamLocalPositionNEDCOV::get_name () const inline virtual
Implements MavlinkStream.
Definition at line 2140 of file mavlink_messages.cpp.
References get_name_static().
static const char* MavlinkStreamLocalPositionNEDCOV::get_name_static () inline static
Definition at line 2145 of file mavlink_messages.cpp.
Referenced by get_name().
unsigned MavlinkStreamLocalPositionNEDCOV::get_size () inline virtual
Get maximal total messages size on update.
Implements MavlinkStream.
Definition at line 2165 of file mavlink_messages.cpp.
static MavlinkStream* MavlinkStreamLocalPositionNEDCOV::new_instance (Mavlink * mavlink) inline static
Definition at line 2160 of file mavlink_messages.cpp.
MavlinkStreamLocalPositionNEDCOV& MavlinkStreamLocalPositionNEDCOV::operator= (const MavlinkStreamLocalPositionNEDCOV &) private delete
bool MavlinkStreamLocalPositionNEDCOV::send (const hrt_abstime t) inline protected virtual
Implements MavlinkStream.
Definition at line 2184 of file mavlink_messages.cpp.
References MavlinkStream::_mavlink, estimator_status_s::covariances, Mavlink::get_channel(), estimator_status_s::health_flags, msg, estimator_status_s::states, estimator_status_s::timeout_flags, estimator_status_s::timestamp, and MavlinkOrbSubscription::update().
Member Data Documentation
MavlinkOrbSubscription* MavlinkStreamLocalPositionNEDCOV::_est_sub private
Definition at line 2171 of file mavlink_messages.cpp.
uint64_t MavlinkStreamLocalPositionNEDCOV::_est_time private
Definition at line 2172 of file mavlink_messages.cpp.
The documentation for this class was generated from the following file:
src/modules/mavlink/mavlink_messages.cpp