PX4 Firmware: src/systemcmds/mixer/mixer.cpp File Reference
mixer.cpp File Reference
#include <px4_config.h>
#include <px4_module.h>
#include <px4_posix.h>
#include <string.h>
#include <stdlib.h>
#include <stdio.h>
#include <unistd.h>
#include <fcntl.h>
#include <errno.h>
#include <ctype.h>
#include <lib/mixer/mixer.h>
#include <uORB/topics/actuator_controls.h>
Functions
__EXPORT int mixer_main (int argc, char *argv[])
Mixer utility for loading mixer files to devices.
static void usage (const char *reason)
static int load (const char *devname, const char *fname, bool append)
Function Documentation
static int load (const char * devname, const char * fname, bool append) static
Definition at line 131 of file mixer.cpp.
References load_mixer_file(), MIXERIOCLOADBUF, MIXERIOCRESET, PX4_ERR, px4_ioctl(), px4_open(), and usleep().
Referenced by mixer_main().
int mixer_main (int argc, char * argv[])
Mixer utility for loading mixer files to devices.
Definition at line 65 of file mixer.cpp.
References load(), PX4_ERR, and usage().
static void usage (const char * reason) static
Definition at line 107 of file mixer.cpp.
References PRINT_MODULE_DESCRIPTION(), PRINT_MODULE_USAGE_ARG(), PRINT_MODULE_USAGE_COMMAND, PRINT_MODULE_USAGE_NAME(), and PX4_INFO.
Referenced by mixer_main().