PX4 Firmware: src/platforms/px4_module.h File Reference
px4_module.h File Reference
#include <pthread.h>
#include <unistd.h>
#include <stdbool.h>
#include <px4_log.h>
#include <px4_tasks.h>
#include <systemlib/px4_macros.h>
Macros
#define PRINT_MODULE_USAGE_COMMAND(name) PRINT_MODULE_USAGE_COMMAND_DESCR(name, NULL);
#define PRINT_MODULE_USAGE_DEFAULT_COMMANDS()
print the default commands: stop & status
Functions
__BEGIN_DECLS __EXPORT void PRINT_MODULE_DESCRIPTION (const char *description)
Print module documentation (will also be used for online documentation).
__EXPORT void PRINT_MODULE_USAGE_NAME (const char *executable_name, const char *category)
Print the command name.
__EXPORT void PRINT_MODULE_USAGE_NAME_SIMPLE (const char *executable_name, const char *category)
Print the name for a command without any sub-commands (.
__EXPORT void PRINT_MODULE_USAGE_COMMAND_DESCR (const char *name, const char *description)
Print a command with a short description what it does.
__EXPORT void PRINT_MODULE_USAGE_PARAM_INT (char option_char, int default_val, int min_val, int max_val, const char *description, bool is_optional)
print an integer parameter
__EXPORT void PRINT_MODULE_USAGE_PARAM_FLOAT (char option_char, float default_val, float min_val, float max_val, const char *description, bool is_optional)
print a float parameter
__EXPORT void PRINT_MODULE_USAGE_PARAM_FLAG (char option_char, const char *description, bool is_optional)
print a flag parameter, without any value
__EXPORT void PRINT_MODULE_USAGE_PARAM_STRING (char option_char, const char *default_val, const char *values, const char *description, bool is_optional)
print a string parameter
__EXPORT void PRINT_MODULE_USAGE_PARAM_COMMENT (const char *comment)
print a comment, that applies to the next arguments or parameters.
__EXPORT void PRINT_MODULE_USAGE_ARG (const char *values, const char *description, bool is_optional)
print definition for an argument, which does not have the typical -p <val> form, but for example 'param set '
Macro Definition Documentation
#define PRINT_MODULE_USAGE_COMMAND (name) PRINT_MODULE_USAGE_COMMAND_DESCR(name, NULL);
Definition at line 425 of file px4_module.h.
Referenced by LocalPositionEstimatorModule::print_usage(), WindEstimatorModule::print_usage(), MulticopterAttitudeControl::print_usage(), FixedwingAttitudeControl::print_usage(), Navigator::print_usage(), Ekf2::print_usage(), px4::logger::Logger::print_usage(), print_usage(), PX4FMU::print_usage(), GPS::print_usage(), FixedwingPositionControl::print_usage(), Sensors::print_usage(), usage(), and rpi_rc_in::usage().
#define PRINT_MODULE_USAGE_DEFAULT_COMMANDS ()
Value:
PRINT_MODULE_USAGE_COMMAND("stop"); \
    PRINT_MODULE_USAGE_COMMAND_DESCR("status", "print status info");
print the default commands: stop & status
Definition at line 431 of file px4_module.h.
Referenced by events::SendEvent::print_usage(), LocalPositionEstimatorModule::print_usage(), WindEstimatorModule::print_usage(), px4::Replay::print_usage(), RCInput::print_usage(), land_detector::LandDetector::print_usage(), PWMSim::print_usage(), MulticopterAttitudeControl::print_usage(), FixedwingAttitudeControl::print_usage(), load_mon::LoadMon::print_usage(), Navigator::print_usage(), Ekf2::print_usage(), px4::logger::Logger::print_usage(), PX4FMU::print_usage(), GPS::print_usage(), FixedwingPositionControl::print_usage(), Sensors::print_usage(), and usage().
Function Documentation
__BEGIN_DECLS __EXPORT void PRINT_MODULE_DESCRIPTION (const char * description)
Print module documentation (will also be used for online documentation).
It uses Markdown syntax and should include these sections:
### Description Provided functionality of the module and potentially the most important parameters.
### Implementation High-level implementation overview
### Examples Examples how to use the CLI interface (if it's non-trivial)
In addition to the Markdown syntax, a line beginning with '$ ' can be used to mark a command: $ module start -p param
Definition at line 46 of file module.cpp.
References PX4_INFO_RAW.
Referenced by mtd_main(), events::SendEvent::print_usage(), LocalPositionEstimatorModule::print_usage(), WindEstimatorModule::print_usage(), px4::Replay::print_usage(), RCInput::print_usage(), land_detector::LandDetector::print_usage(), PWMSim::print_usage(), MulticopterAttitudeControl::print_usage(), FixedwingAttitudeControl::print_usage(), load_mon::LoadMon::print_usage(), Navigator::print_usage(), TAP_ESC::print_usage(), Ekf2::print_usage(), px4::logger::Logger::print_usage(), print_usage(), PX4FMU::print_usage(), GPS::print_usage(), FixedwingPositionControl::print_usage(), Sensors::print_usage(), usage(), and rpi_rc_in::usage().
__EXPORT void PRINT_MODULE_USAGE_ARG (const char * values, const char * description, bool is_optional)
print definition for an argument, which does not have the typical -p <val> form, but for example 'param set '
Parameters
values eg. "<file>", "<param> <value>" or "<value1> [<value2>]"
description
is_optional true if this parameter is optional
Definition at line 142 of file module.cpp.
References PX4_INFO_RAW.
Referenced by mtd_main(), print_usage(), land_detector::LandDetector::print_usage(), PX4FMU::print_usage(), usage(), and rpi_rc_in::usage().
__EXPORT void PRINT_MODULE_USAGE_COMMAND_DESCR (const char * name, const char * description)
Print a command with a short description what it does.
Definition at line 67 of file module.cpp.
References PX4_INFO_RAW.
Referenced by mtd_main(), events::SendEvent::print_usage(), px4::Replay::print_usage(), RCInput::print_usage(), land_detector::LandDetector::print_usage(), PWMSim::print_usage(), load_mon::LoadMon::print_usage(), Navigator::print_usage(), TAP_ESC::print_usage(), px4::logger::Logger::print_usage(), print_usage(), PX4FMU::print_usage(), usage(), and rpi_rc_in::usage().
__EXPORT void PRINT_MODULE_USAGE_NAME (const char * executable_name, const char * category)
Print the command name.
Parameters
executable_name command name used in scripts & CLI
category one of: driver, estimator, controller, system, communication, command, template
Definition at line 56 of file module.cpp.
References PX4_INFO_RAW.
Referenced by mtd_main(), events::SendEvent::print_usage(), LocalPositionEstimatorModule::print_usage(), WindEstimatorModule::print_usage(), px4::Replay::print_usage(), RCInput::print_usage(), land_detector::LandDetector::print_usage(), PWMSim::print_usage(), MulticopterAttitudeControl::print_usage(), FixedwingAttitudeControl::print_usage(), load_mon::LoadMon::print_usage(), Navigator::print_usage(), TAP_ESC::print_usage(), Ekf2::print_usage(), px4::logger::Logger::print_usage(), print_usage(), PX4FMU::print_usage(), GPS::print_usage(), FixedwingPositionControl::print_usage(), Sensors::print_usage(), usage(), and rpi_rc_in::usage().
__EXPORT void PRINT_MODULE_USAGE_NAME_SIMPLE (const char * executable_name, const char * category)
Print the name for a command without any sub-commands (.
See also
PRINT_MODULE_USAGE_NAME())
Definition at line 62 of file module.cpp.
References PX4_INFO_RAW.
Referenced by print_usage(), and usage().
__EXPORT void PRINT_MODULE_USAGE_PARAM_COMMENT (const char * comment)
print a comment, that applies to the next arguments or parameters.
For example to indicate that a parameter applies to several or all commands.
Parameters
comment
Definition at line 77 of file module.cpp.
References PX4_INFO_RAW.
Referenced by mtd_main(), print_usage(), PWMSim::print_usage(), PX4FMU::print_usage(), and usage().
__EXPORT void PRINT_MODULE_USAGE_PARAM_FLAG (char option_char, const char * description, bool is_optional)
print a flag parameter, without any value
See also
PRINT_MODULE_USAGE_PARAM_INT()
Definition at line 106 of file module.cpp.
References PX4_INFO_RAW.
Referenced by events::SendEvent::print_usage(), RCInput::print_usage(), Ekf2::print_usage(), px4::logger::Logger::print_usage(), print_usage(), PX4FMU::print_usage(), GPS::print_usage(), Sensors::print_usage(), and usage().
__EXPORT void PRINT_MODULE_USAGE_PARAM_FLOAT (char option_char, float default_val, float min_val, float max_val, const char * description, bool is_optional)
print a float parameter
See also
PRINT_MODULE_USAGE_PARAM_INT()
Definition at line 94 of file module.cpp.
References PX4_INFO_RAW.
Referenced by usage().
__EXPORT void PRINT_MODULE_USAGE_PARAM_INT (char option_char, int default_val, int min_val, int max_val, const char * description, bool is_optional)
print an integer parameter
Parameters
option_char option character
default_val
min_val
max_val
description
is_optional true if this parameter is optional
Definition at line 82 of file module.cpp.
References PX4_INFO_RAW.
Referenced by TAP_ESC::print_usage(), px4::logger::Logger::print_usage(), and usage().
__EXPORT void PRINT_MODULE_USAGE_PARAM_STRING (char option_char, const char * default_val, const char * values, const char * description, bool is_optional)
print a string parameter
Parameters
option_char option character
default_val default value, can be nullptr
values valid values, it has one of the following forms:
nullptr: leave unspecified, or any value is valid
"<file>" or "<file:dev>": a file or more specifically a device file (eg. serial device)
"<topic_name>": uORB topic name
"<value1> [<value2>]": a list of values
"on|off": a concrete set of valid strings separated by |
description
is_optional true if this parameter is optional
Definition at line 116 of file module.cpp.
References PX4_INFO_RAW.
Referenced by TAP_ESC::print_usage(), px4::logger::Logger::print_usage(), GPS::print_usage(), usage(), and rpi_rc_in::usage().