PX4 Firmware: uavcan_kinetis::BusEvent Class Reference
uavcan_kinetis::BusEvent Class Reference
All bus events are reported as POLLIN.
#include <thread.hpp>
Public Member Functions
BusEvent (CanDriver &can_driver)
~BusEvent ()
void registerSignalCallback (SignalCallbackHandler handler)
bool wait (uavcan::MonotonicDuration duration)
void signalFromInterrupt ()
Private Types
using SignalCallbackHandler = void(*)()
Private Attributes
SignalCallbackHandler signal_cb_ {nullptr}
sem_t sem_
Detailed Description
All bus events are reported as POLLIN.
Definition at line 29 of file thread.hpp.
Member Typedef Documentation
SignalCallbackHandler
using uavcan_kinetis::BusEvent::SignalCallbackHandler = void(*)() private
Definition at line 31 of file thread.hpp.
Constructor & Destructor Documentation
BusEvent()
uavcan_kinetis::BusEvent::BusEvent (CanDriver & can_driver)
Definition at line 14 of file uc_kinetis_thread.cpp.
References sem_.
~BusEvent()
uavcan_kinetis::BusEvent::~BusEvent ()
Definition at line 20 of file uc_kinetis_thread.cpp.
References sem_.
Member Function Documentation
registerSignalCallback()
void uavcan_kinetis::BusEvent::registerSignalCallback (SignalCallbackHandler handler) inline
Definition at line 40 of file thread.hpp.
References signal_cb_, signalFromInterrupt(), and wait().
signalFromInterrupt()
void uavcan_kinetis::BusEvent::signalFromInterrupt ()
Definition at line 52 of file uc_kinetis_thread.cpp.
References sem_, and signal_cb_.
Referenced by registerSignalCallback().
wait()
bool uavcan_kinetis::BusEvent::wait (uavcan::MonotonicDuration duration)
Definition at line 25 of file uc_kinetis_thread.cpp.
References sem_.
Referenced by registerSignalCallback().
Member Data Documentation
sem_
sem_t uavcan_kinetis::BusEvent::sem_ private
Definition at line 34 of file thread.hpp.
Referenced by BusEvent(), signalFromInterrupt(), wait(), and ~BusEvent().
signal_cb_
SignalCallbackHandler uavcan_kinetis::BusEvent::signal_cb_ {nullptr} private
Definition at line 33 of file thread.hpp.
Referenced by registerSignalCallback(), and signalFromInterrupt().
The documentation for this class was generated from the following files:
src/drivers/uavcan/uavcan_drivers/kinetis/driver/include/uavcan_kinetis/thread.hpp
src/drivers/uavcan/uavcan_drivers/kinetis/driver/src/uc_kinetis_thread.cpp