PX4 Firmware: src/drivers/boards/bbblue/board_config.h File Reference
board_config.h File Reference
#include <system_config.h>
#include "../common/board_common.h"
Macros
#define BOARD_CONFIG_H
#define BOARD_OVERRIDE_UUID "BBBLUEID "
#define BOARD_OVERRIDE_MFGUID BOARD_OVERRIDE_UUID
#define BOARD_NAME "BBBLUE"
#define BOARD_BATTERY1_V_DIV (11.0f)
#define ADC_BATTERY_VOLTAGE_CHANNEL 5
#define ADC_BATTERY_CURRENT_CHANNEL ((uint8_t)(-1))
#define ADC_AIRSPEED_VOLTAGE_CHANNEL ((uint8_t)(-1))
#define BOARD_HAS_NO_BOOTLOADER
#define BOARD_MAX_LEDS 4
#define PX4_I2C_BUS_EXPANSION 1
#define PX4_NUMBER_I2C_BUSES 1
Functions
int rc_init (void)
void rc_cleaning (void)
Macro Definition Documentation
#define ADC_AIRSPEED_VOLTAGE_CHANNEL ((uint8_t)(-1))
Definition at line 56 of file board_config.h.
#define ADC_BATTERY_CURRENT_CHANNEL ((uint8_t)(-1))
Definition at line 55 of file board_config.h.
#define ADC_BATTERY_VOLTAGE_CHANNEL 5
Definition at line 54 of file board_config.h.
#define BOARD_BATTERY1_V_DIV (11.0f)
Definition at line 50 of file board_config.h.
#define BOARD_CONFIG_H
Definition at line 43 of file board_config.h.
#define BOARD_HAS_NO_BOOTLOADER
Definition at line 58 of file board_config.h.
#define BOARD_MAX_LEDS 4
Definition at line 60 of file board_config.h.
Referenced by LedController::get_control_data(), run_led_test1(), TemperatureCalibration::task_main(), and LedController::update().
#define BOARD_NAME "BBBLUE"
Definition at line 48 of file board_config.h.
#define BOARD_OVERRIDE_MFGUID BOARD_OVERRIDE_UUID
Definition at line 46 of file board_config.h.
Referenced by ver_main().
#define BOARD_OVERRIDE_UUID "BBBLUEID "
Definition at line 45 of file board_config.h.
Referenced by ver_main().
#define PX4_I2C_BUS_EXPANSION 1
Definition at line 65 of file board_config.h.
#define PX4_NUMBER_I2C_BUSES 1
Definition at line 66 of file board_config.h.
Function Documentation
void rc_cleaning (void)
Definition at line 121 of file init.c.
References data.
Referenced by BBBlueADC::~BBBlueADC().
int rc_init (void)
Definition at line 47 of file init.c.
References f(), PX4_ERR, and PX4_INFO.
Referenced by BBBlueADC::init().