PX4 Firmware: src/drivers/test_ppm/test_ppm.cpp File Reference
test_ppm.cpp File Reference
#include <nuttx/config.h>
#include <sys/types.h>
#include <stdint.h>
#include <stdbool.h>
#include <stddef.h>
#include <stdlib.h>
#include <semaphore.h>
#include <string.h>
#include <fcntl.h>
#include <poll.h>
#include <errno.h>
#include <stdio.h>
#include <math.h>
#include <unistd.h>
#include <perf/perf_counter.h>
#include <systemlib/err.h>
#include <systemlib/conversions.h>
#include <nuttx/arch.h>
#include <nuttx/clock.h>
#include <board_config.h>
#include <drivers/drv_hrt.h>
Classes
class TEST_PPM
Namespaces
test_ppm
Macros
#define TEST_PPM_PIN (GPIO_OUTPUT|GPIO_PUSHPULL|GPIO_SPEED_2MHz|GPIO_OUTPUT_SET|GPIO_PORTE|GPIO_PIN15)
Functions
__EXPORT int test_ppm_main (int argc, char *argv[])
driver 'main' command
void test_ppm::start (unsigned channels)
Start the driver.
void test_ppm::stop ()
Stop the driver.
void test_ppm::usage ()
Prints info about the driver argument usage.
void test_ppm::set (unsigned ch, unsigned value)
Variables
TEST_PPM * test_ppm::g_test = nullptr
Macro Definition Documentation
TEST_PPM_PIN
#define TEST_PPM_PIN (GPIO_OUTPUT|GPIO_PUSHPULL|GPIO_SPEED_2MHz|GPIO_OUTPUT_SET|GPIO_PORTE|GPIO_PIN15)
Definition at line 66 of file test_ppm.cpp.
Referenced by TEST_PPM::do_out(), and TEST_PPM::init().
Function Documentation
test_ppm_main()
int test_ppm_main (int argc, char * argv[])
driver 'main' command
Definition at line 249 of file test_ppm.cpp.
References errx, test_ppm::set(), test_ppm::start(), test_ppm::stop(), and test_ppm::usage().