PX4 Firmware: src/modules/dataman/dataman.cpp File Reference
dataman.cpp File Reference
DATAMANAGER driver.
#include <px4_config.h>
#include <px4_defines.h>
#include <px4_module.h>
#include <px4_posix.h>
#include <px4_tasks.h>
#include <stdio.h>
#include <stdbool.h>
#include <stdlib.h>
#include <errno.h>
#include <fcntl.h>
#include <systemlib/err.h>
#include <queue.h>
#include <string.h>
#include <semaphore.h>
#include <unistd.h>
#include <platforms/px4_getopt.h>
#include <drivers/drv_hrt.h>
#include "dataman.h"
#include <parameters/param.h>
Classes
struct dm_operations_t
struct work_q_item_t
Work task work item.
struct work_q_t
Macros
#define DM_SECTOR_HDR_SIZE 4 /* data manager per item header overhead */
Typedefs
typedef struct dm_operations_t dm_operations_t
Enumerations
enum dm_function_t {
dm_write_func = 0, dm_read_func, dm_clear_func, dm_restart_func,
dm_number_of_funcs
}
Types of function calls supported by the worker task.
enum { BACKEND_NONE = 0, BACKEND_FILE, BACKEND_RAM, BACKEND_LAST }
Functions
__BEGIN_DECLS __EXPORT int dataman_main (int argc, char *argv[])
static __END_DECLS ssize_t _file_write (dm_item_t item, unsigned index, dm_persitence_t persistence, const void *buf, size_t count)
static ssize_t _file_read (dm_item_t item, unsigned index, void *buf, size_t count)
static int _file_clear (dm_item_t item)
static int _file_restart (dm_reset_reason reason)
static int _file_initialize (unsigned max_offset)
static void _file_shutdown ()
static ssize_t _ram_write (dm_item_t item, unsigned index, dm_persitence_t persistence, const void *buf, size_t count)
static ssize_t _ram_read (dm_item_t item, unsigned index, void *buf, size_t count)
static int _ram_clear (dm_item_t item)
static int _ram_restart (dm_reset_reason reason)
static int _ram_initialize (unsigned max_offset)
static void _ram_shutdown ()
static void init_q (work_q_t *q)
static void destroy_q (work_q_t *q)
static void lock_queue (work_q_t *q)
static void unlock_queue (work_q_t *q)
static work_q_item_t * create_work_item ()
static void destroy_work_item (work_q_item_t *item)
static work_q_item_t * dequeue_work_item ()
static int enqueue_work_item_and_wait_for_result (work_q_item_t *item)
static bool is_running ()
static int calculate_offset (dm_item_t item, unsigned index)
__EXPORT ssize_t dm_write (dm_item_t item, unsigned index, dm_persitence_t persistence, const void *buf, size_t count)
Write to the data manager file.
__EXPORT ssize_t dm_read (dm_item_t item, unsigned index, void *buf, size_t count)
Retrieve from the data manager file.
__EXPORT int dm_clear (dm_item_t item)
Clear a data Item.
__EXPORT int dm_lock (dm_item_t item)
Lock all items of a type.
__EXPORT int dm_trylock (dm_item_t item)
Try to lock all items of a type (.
__EXPORT void dm_unlock (dm_item_t item)
Unlock a data Item.
__EXPORT int dm_restart (dm_reset_reason reason)
Tell the data manager about the type of the last reset.
static int task_main (int argc, char *argv[])
static int start ()
static void status ()
static void stop ()
static void usage ()
static int backend_check ()
Variables
static constexpr dm_operations_t dm_file_operations
static constexpr dm_operations_t dm_ram_operations
static const dm_operations_t * g_dm_ops
struct {
union {
struct {
int fd
} file
struct {
uint8_t * data
uint8_t * data_end
} ram
}
bool running
} dm_operations_data
const size_t k_work_item_allocation_chunk_size = 8
static unsigned g_func_counts [dm_number_of_funcs]
static const unsigned g_per_item_max_index [DM_KEY_NUM_KEYS]
static constexpr size_t g_per_item_size [DM_KEY_NUM_KEYS]
static unsigned int g_key_offsets [DM_KEY_NUM_KEYS]
static px4_sem_t * g_item_locks [DM_KEY_NUM_KEYS]
static px4_sem_t g_sys_state_mutex_mission
static px4_sem_t g_sys_state_mutex_fence
static const char * default_device_path = PX4_STORAGEDIR "/dataman"
static char * k_data_manager_device_path = nullptr
static enum { ... } backend = BACKEND_NONE
static work_q_t g_free_q
static work_q_t g_work_q
static px4_sem_t g_work_queued_sema
static px4_sem_t g_init_sema
static bool g_task_should_exit
if true, dataman task should exit
Detailed Description
DATAMANAGER driver.
Author
Jean Cyr
Lorenz Meier
Julian Oes
Thomas Gubler
David Sidrane
Definition in file dataman.cpp.
Macro Definition Documentation
#define DM_SECTOR_HDR_SIZE 4 /* data manager per item header overhead */
Definition at line 227 of file dataman.cpp.
Referenced by _file_write().
Typedef Documentation
typedef struct dm_operations_t dm_operations_t
Enumeration Type Documentation
anonymous enum
Enumerator
BACKEND_NONE
BACKEND_FILE
BACKEND_RAM
BACKEND_LAST
Definition at line 256 of file dataman.cpp.
enum dm_function_t
Types of function calls supported by the worker task.
Enumerator
dm_write_func
dm_read_func
dm_clear_func
dm_restart_func
dm_number_of_funcs
Definition at line 173 of file dataman.cpp.
Function Documentation
static int _file_clear (dm_item_t item) static
Definition at line 700 of file dataman.cpp.
References calculate_offset(), dm_operations_t::clear, dm_operations_data, dm_ram_operations, fsync(), g_per_item_max_index, g_per_item_size, dm_operations_t::read, and dm_operations_t::write.
static int _file_initialize (unsigned max_offset) static
Definition at line 885 of file dataman.cpp.
References DM_COMPAT_KEY, DM_KEY_COMPAT, dm_operations_data, DM_PERSIST_POWER_ON_RESET, fsync(), dataman_compat_s::key, PX4_ERR, px4_sem_post, PX4_WARN, dm_operations_t::read, and dm_operations_t::write.
static ssize_t _file_read (dm_item_t item, unsigned index, void * buf, size_t count) static
Definition at line 609 of file dataman.cpp.
References calculate_offset(), DM_KEY_NUM_KEYS, dm_operations_data, dm_ram_operations, g_per_item_size, and dm_operations_t::read.
static int _file_restart (dm_reset_reason reason) static
Definition at line 805 of file dataman.cpp.
References DM_INIT_REASON_POWER_ON, DM_KEY_NUM_KEYS, DM_KEY_SAFE_POINTS, dm_operations_data, DM_PERSIST_IN_FLIGHT_RESET, DM_PERSIST_POWER_ON_RESET, dm_ram_operations, fsync(), g_per_item_max_index, g_per_item_size, dm_operations_t::read, dm_operations_t::restart, and dm_operations_t::write.
static void _file_shutdown () static
Definition at line 999 of file dataman.cpp.
References dm_operations_data.
static ssize_t _file_write (dm_item_t item, unsigned index, dm_persitence_t persistence, const void * buf, size_t count) static
Definition at line 495 of file dataman.cpp.
References calculate_offset(), dm_operations_data, DM_PERSIST_POWER_ON_RESET, dm_ram_operations, DM_SECTOR_HDR_SIZE, fsync(), g_per_item_size, hrt_absolute_time(), and dm_operations_t::write.
static int _ram_clear (dm_item_t item) static
Definition at line 670 of file dataman.cpp.
References calculate_offset(), dm_operations_data, g_per_item_max_index, and g_per_item_size.
static int _ram_initialize (unsigned max_offset) static
Definition at line 942 of file dataman.cpp.
References DM_COMPAT_KEY, DM_KEY_COMPAT, dm_operations_data, DM_PERSIST_POWER_ON_RESET, dm_ram_operations, dm_operations_t::initialize, dataman_compat_s::key, px4_sem_post, PX4_WARN, dm_operations_t::read, and dm_operations_t::write.
static ssize_t _ram_read (dm_item_t item, unsigned index, void * buf, size_t count) static
Definition at line 569 of file dataman.cpp.
References calculate_offset(), dm_operations_data, and g_per_item_size.
static int _ram_restart (dm_reset_reason reason) static
Definition at line 765 of file dataman.cpp.
References DM_INIT_REASON_POWER_ON, DM_KEY_NUM_KEYS, DM_KEY_SAFE_POINTS, dm_operations_data, DM_PERSIST_IN_FLIGHT_RESET, DM_PERSIST_POWER_ON_RESET, g_per_item_max_index, and g_per_item_size.
static void _ram_shutdown () static
Definition at line 1006 of file dataman.cpp.
References dm_operations_data, dm_ram_operations, hrt_absolute_time(), px4_sem_t, px4_sem_timedwait, px4_sem_wait, PX4_WARN, and dm_operations_t::shutdown.
static ssize_t _ram_write (dm_item_t item, unsigned index, dm_persitence_t persistence, const void * buf, size_t count) static
Definition at line 456 of file dataman.cpp.
References calculate_offset(), dm_operations_data, and g_per_item_size.
static int backend_check () static
Definition at line 1526 of file dataman.cpp.
References BACKEND_NONE, PX4_WARN, and usage().
Referenced by dataman_main().
static int calculate_offset (dm_item_t item, unsigned index) static
Definition at line 427 of file dataman.cpp.
References DM_KEY_NUM_KEYS, g_per_item_max_index, and g_per_item_size.
Referenced by _file_clear(), _file_read(), _file_write(), _ram_clear(), _ram_read(), and _ram_write().
static work_q_item_t* create_work_item () static
Definition at line 309 of file dataman.cpp.
References work_q_item_t::first, k_work_item_allocation_chunk_size, lock_queue(), work_q_t::max_size, px4_sem_init, px4_sem_setprotocol, work_q_t::q, SEM_PRIO_NONE, work_q_t::size, sq_addfirst(), sq_remfirst(), unlock_queue(), and work_q_item_t::wait_sem.
Referenced by dm_clear(), dm_read(), dm_restart(), and dm_write().
int dataman_main (int argc, char * argv[])
Definition at line 1538 of file dataman.cpp.
References backend_check(), BACKEND_FILE, BACKEND_NONE, BACKEND_RAM, DM_INIT_REASON_IN_FLIGHT, DM_INIT_REASON_POWER_ON, dm_restart(), is_running(), PX4_ERR, px4_getopt(), PX4_INFO, PX4_WARN, start(), status(), stop(), and usage().
static work_q_item_t* dequeue_work_item () inline static
Definition at line 378 of file dataman.cpp.
References lock_queue(), work_q_t::q, work_q_t::size, sq_remfirst(), and unlock_queue().
Referenced by task_main().
static void destroy_q (work_q_t * q) inline static
Definition at line 291 of file dataman.cpp.
References work_q_t::mutex, and px4_sem_destroy.
Referenced by task_main().
static void destroy_work_item (work_q_item_t * item) inline static
Definition at line 362 of file dataman.cpp.
References work_q_item_t::link, lock_queue(), work_q_t::max_size, px4_sem_destroy, work_q_t::q, work_q_t::size, sq_addfirst(), unlock_queue(), and work_q_item_t::wait_sem.
Referenced by enqueue_work_item_and_wait_for_result().
__EXPORT int dm_clear (dm_item_t item)
Clear a data Item.
Erase all items of this type.
Definition at line 1136 of file dataman.cpp.
References work_q_item_t::clear_params, create_work_item(), dm_clear_func, enqueue_work_item_and_wait_for_result(), work_q_item_t::func, and is_running().
Referenced by Geofence::clearDm().
__EXPORT int dm_lock (dm_item_t item)
Lock all items of a type.
Can be used for atomic updates of multiple items (single items are always updated atomically). Note that this lock is independent from dm_read & dm_write calls.
Returns
0 on success and lock taken, -1 on error (lock not taken, errno set)
Definition at line 1158 of file dataman.cpp.
References DM_KEY_NUM_KEYS, is_running(), and px4_sem_wait.
Referenced by MavlinkMissionManager::handle_mission_count(), MavlinkMissionManager::init_offboard_mission(), Mission::on_inactive(), Mission::reset_offboard_mission(), Mission::save_offboard_mission_state(), MavlinkMissionManager::update_active_mission(), and Geofence::updateFence().
__EXPORT ssize_t dm_read (dm_item_t item, unsigned index, void * buf, size_t count)
Retrieve from the data manager file.
Retrieve from the data manager store.
Definition at line 1110 of file dataman.cpp.
References create_work_item(), dm_read_func, enqueue_work_item_and_wait_for_result(), work_q_item_t::func, is_running(), and work_q_item_t::read_params.
Referenced by Geofence::_updateFence(), Mission::advance_mission(), MissionFeasibilityChecker::checkDistancesBetweenWaypoints(), MissionFeasibilityChecker::checkDistanceToFirstWaypoint(), MissionFeasibilityChecker::checkFixedWingLanding(), MissionFeasibilityChecker::checkFixedWingTakeoff(), MissionFeasibilityChecker::checkGeofence(), MissionFeasibilityChecker::checkHomePositionAltitude(), MissionFeasibilityChecker::checkMissionItemValidity(), Geofence::checkPolygons(), MissionFeasibilityChecker::checkRotarywing(), Mission::find_offboard_land_start(), Mission::index_closest_mission_item(), MavlinkMissionManager::init_offboard_mission(), Geofence::insideCircle(), Geofence::insidePolygon(), MavlinkMissionManager::load_geofence_stats(), MavlinkMissionManager::load_safepoint_stats(), Geofence::loadFromFile(), Commander::mission_init(), Mission::on_inactive(), Mission::read_mission_item(), Mission::reset_offboard_mission(), Mission::save_offboard_mission_state(), MavlinkMissionManager::send_mission_item(), task_main(), and test_dataman().
__EXPORT int dm_restart (dm_reset_reason reason)
Tell the data manager about the type of the last reset.
Definition at line 1221 of file dataman.cpp.
References create_work_item(), dm_restart_func, enqueue_work_item_and_wait_for_result(), work_q_item_t::func, is_running(), and work_q_item_t::restart_params.
Referenced by dataman_main(), and test_dataman().
__EXPORT int dm_trylock (dm_item_t item)
Try to lock all items of a type (.
See also
sem_trywait()).
Returns
0 if lock is taken, -1 otherwise (on error or if already locked. errno is set accordingly)
Definition at line 1180 of file dataman.cpp.
References DM_KEY_NUM_KEYS, is_running(), and px4_sem_trywait.
Referenced by Geofence::checkPolygons().
__EXPORT void dm_unlock (dm_item_t item)
Unlock a data Item.
Unlock all items of a type.
Definition at line 1203 of file dataman.cpp.
References DM_KEY_NUM_KEYS, is_running(), and px4_sem_post.
Referenced by Geofence::checkPolygons(), MavlinkMissionManager::init_offboard_mission(), Mission::on_inactive(), Mission::reset_offboard_mission(), Mission::save_offboard_mission_state(), MavlinkMissionManager::switch_to_idle_state(), MavlinkMissionManager::update_active_mission(), and Geofence::updateFence().
__EXPORT ssize_t dm_write (dm_item_t item, unsigned index, dm_persitence_t persistence, const void * buf, size_t count)
Write to the data manager file.
write to the data manager store
Definition at line 1083 of file dataman.cpp.
References create_work_item(), dm_write_func, enqueue_work_item_and_wait_for_result(), work_q_item_t::func, is_running(), and work_q_item_t::write_params.
Referenced by MavlinkMissionManager::handle_mission_item_both(), Geofence::loadFromFile(), Commander::mission_init(), Mission::read_mission_item(), Mission::reset_offboard_mission(), Mission::save_offboard_mission_state(), task_main(), MavlinkMissionManager::update_active_mission(), MavlinkMissionManager::update_geofence_count(), and MavlinkMissionManager::update_safepoint_count().
static int enqueue_work_item_and_wait_for_result (work_q_item_t * item) static
Definition at line 394 of file dataman.cpp.
References destroy_work_item(), work_q_item_t::link, lock_queue(), work_q_t::max_size, px4_sem_post, px4_sem_wait, work_q_t::q, work_q_item_t::result, work_q_t::size, sq_addlast(), unlock_queue(), and work_q_item_t::wait_sem.
Referenced by dm_clear(), dm_read(), dm_restart(), and dm_write().
static void init_q (work_q_t * q) static
Definition at line 283 of file dataman.cpp.
References work_q_t::max_size, work_q_t::mutex, px4_sem_init, work_q_t::q, and work_q_t::size.
Referenced by task_main().
static bool is_running () static
Definition at line 420 of file dataman.cpp.
References dm_operations_data.
Referenced by events::SendEvent::custom_command(), WindEstimatorModule::custom_command(), RCInput::custom_command(), PWMSim::custom_command(), Navigator::custom_command(), px4::logger::Logger::custom_command(), PX4FMU::custom_command(), dataman_main(), dm_clear(), dm_lock(), dm_read(), dm_restart(), dm_trylock(), dm_unlock(), dm_write(), PX4FMU::fmu_new_mode(), px4::logger::Logger::request_stop_static(), and events::SendEvent::start().
static void lock_queue (work_q_t * q) inline static
Definition at line 297 of file dataman.cpp.
References work_q_t::mutex, and px4_sem_wait.
Referenced by create_work_item(), dequeue_work_item(), destroy_work_item(), and enqueue_work_item_and_wait_for_result().
static int start () static
Definition at line 1444 of file dataman.cpp.
References PX4_ERR, px4_sem_destroy, px4_sem_init, px4_sem_setprotocol, px4_sem_wait, px4_task_spawn_cmd(), SCHED_DEFAULT, SEM_PRIO_NONE, and task_main().
Referenced by attitude_estimator_q_main(), dataman_main(), do_level_calibration(), BAROSIM::init(), motor_ramp_thread_main(), uORB::Manager::node_open(), px4io_main(), px4::logger::LogWriterFile::run(), Simulator::sample::sample(), PX4IO::set_update_rate(), RGBLED::start(), DfLtc2946Wrapper::start(), DfBebopBusWrapper::start(), DfMS5607Wrapper::start(), DfMS5611Wrapper::start(), DfBmp280Wrapper::start(), DfBebopRangeFinderWrapper::start(), DfAK8963Wrapper::start(), DfTROneWrapper::start(), DfISL29501Wrapper::start(), DfMPU6050Wrapper::start(), DfLsm9ds1Wrapper::start(), GYROSIM::start(), ACCELSIM::start(), ACCELSIM_mag::start(), test_file(), VideoDevice::VideoDevice(), vtol_att_control_main(), and write_test().
static void status () static
Definition at line 1469 of file dataman.cpp.
References dm_clear_func, dm_read_func, dm_restart_func, dm_write_func, g_func_counts, work_q_t::max_size, and PX4_INFO.
Referenced by dataman_main().
static void stop () static
Definition at line 1480 of file dataman.cpp.
References px4_sem_post.
Referenced by dataman_main(), GYROSIM::devIOCTL(), ll40ls::start(), GYROSIM::start(), RGBLED::stop(), DfLtc2946Wrapper::stop(), DfBebopBusWrapper::stop(), DfMS5611Wrapper::stop(), DfMS5607Wrapper::stop(), DfBmp280Wrapper::stop(), DfAK8963Wrapper::stop(), DfBebopRangeFinderWrapper::stop(), DfTROneWrapper::stop(), DfISL29501Wrapper::stop(), DfMPU6050Wrapper::stop(), DfLsm9ds1Wrapper::stop(), ACCELSIM::stop(), ACCELSIM_mag::stop(), VideoDevice::VideoDevice(), px4::bst::BST::work_ptr(), BAROSIM::~BAROSIM(), and GYROSIM::~GYROSIM().
static int task_main (int argc, char * argv[]) static
Definition at line 1252 of file dataman.cpp.
References BACKEND_FILE, BACKEND_NONE, BACKEND_RAM, dm_operations_t::clear, work_q_item_t::clear_params, dequeue_work_item(), destroy_q(), dm_clear_func, dm_file_operations, DM_INIT_REASON_IN_FLIGHT, DM_INIT_REASON_POWER_ON, DM_KEY_FENCE_POINTS, DM_KEY_MISSION_STATE, DM_KEY_NUM_KEYS, dm_number_of_funcs, dm_ram_operations, dm_read_func, dm_restart_func, dm_write_func, work_q_item_t::first, work_q_item_t::func, g_func_counts, g_per_item_max_index, g_per_item_size, g_sys_state_mutex_fence, g_sys_state_mutex_mission, init_q(), dm_operations_t::initialize, OK, param_find(), param_get(), PX4_INFO, px4_sem_destroy, px4_sem_init, px4_sem_post, px4_sem_setprotocol, PX4_WARN, work_q_t::q, dm_operations_t::read, work_q_item_t::read_params, dm_operations_t::restart, work_q_item_t::restart_params, work_q_item_t::result, SEM_PRIO_NONE, dm_operations_t::shutdown, sq_remfirst(), dm_operations_t::wait, work_q_item_t::wait_sem, dm_operations_t::write, and work_q_item_t::write_params.
Referenced by start().
static void unlock_queue (work_q_t * q) inline static
Definition at line 303 of file dataman.cpp.
References work_q_t::mutex, and px4_sem_post.
Referenced by create_work_item(), dequeue_work_item(), destroy_work_item(), and enqueue_work_item_and_wait_for_result().
static void usage (void) static
Definition at line 1488 of file dataman.cpp.
References PRINT_MODULE_DESCRIPTION(), PRINT_MODULE_USAGE_COMMAND, PRINT_MODULE_USAGE_COMMAND_DESCR(), PRINT_MODULE_USAGE_DEFAULT_COMMANDS, PRINT_MODULE_USAGE_NAME(), PRINT_MODULE_USAGE_PARAM_COMMENT(), PRINT_MODULE_USAGE_PARAM_FLAG(), and PRINT_MODULE_USAGE_PARAM_STRING().
Referenced by backend_check(), and dataman_main().
Variable Documentation
enum { ... } backend
Referenced by px4::logger::Logger::instantiate().
uint8_t* data
Definition at line 157 of file dataman.cpp.
Referenced by MavlinkFTP::__attribute__(), px4::Replay::CompatSensorCombinedDtType::apply(), batt_smbus_main(), BMP280::collect(), EstimatorInterface::collect_gps(), erase_entry(), uORB::KraitFastRpcChannel::fastrpc_recv_thread(), device::file_t::file_t(), MatrixTest::filterTests(), frsky_parse_host(), frsky_send_data(), SyslinkMemory::getinfo(), uORB::FastRpcChannel::GetInstance(), px4::SubscriberUORB< T >::getUORBData(), hx_stream_start(), BMM150::init_trim_registers(), MatrixTest::inverseTests(), SyslinkMemory::ioctl(), uORB::KraitFastRpcChannel::isInstance(), main(), MatrixTest::matrixAssignmentTests(), MatrixTest::matrixMultTests(), MatrixTest::matrixScalarMultTests(), uORB::Manager::node_open(), px4::Replay::onSubscriptionAdded(), uORB::Manager::orb_advertise(), print_load_callback(), HMC5883_I2C::probe(), PMW3901::probe(), IST8310::probe(), DataValidator::put(), linux_pwm_out::NavioSysfsPWMOut::pwm_write_sysfs(), rc_cleaning(), PX4IO_serial::read(), MPU9250_SPI::read(), SyslinkMemory::read(), PMW3901::readMotionCount(), uORB::DeviceNode::remove_internal_subscriber(), SyslinkMemory::scan(), linux_pwm_out::NavioSysfsPWMOut::send_output_pwm(), px4::bst::BST::send_packet(), PMW3901::sensorInit(), EstimatorInterface::setAuxVelData(), EstimatorInterface::setBaroData(), EstimatorInterface::setMagData(), EstimatorInterface::setRangeData(), MatrixTest::sliceTests(), sPort_send_data(), MatrixTest::squareMatrixTests(), test(), test_adc(), MPU6000::test_error(), MPU9250::test_error(), test_jig_voltages(), test_servo(), MathlibTest::testVector2(), MathlibTest::testVector3(), timer_callback(), MatrixTest::transposeTests(), MatrixTest::vector2Tests(), MatrixTest::vector3Tests(), PX4IO_serial::write(), linux_pwm_out::PCA9685::write_byte(), PMW3901::writeRegister(), px4::Publisher< T >::~Publisher(), and TemperatureCalibrationGyro::~TemperatureCalibrationGyro().
uint8_t* data_end
Definition at line 158 of file dataman.cpp.
const char* default_device_path = PX4_STORAGEDIR "/dataman" static
Definition at line 249 of file dataman.cpp.
constexpr dm_operations_t dm_file_operations static
Initial value:
= {
    .write   = _file_write,
    .read    = _file_read,
    .clear   = _file_clear,
    .restart = _file_restart,
    .initialize = _file_initialize,
    .shutdown = _file_shutdown,
    .wait = px4_sem_wait,
}
Definition at line 117 of file dataman.cpp.
Referenced by task_main().
struct { ... } dm_operations_data
Referenced by _file_clear(), _file_initialize(), _file_read(), _file_restart(), _file_shutdown(), _file_write(), _ram_clear(), _ram_initialize(), _ram_read(), _ram_restart(), _ram_shutdown(), _ram_write(), and is_running().
constexpr dm_operations_t dm_ram_operations static
Initial value:
= {
    .write   = _ram_write,
    .read    = _ram_read,
    .clear   = _ram_clear,
    .restart = _ram_restart,
    .initialize = _ram_initialize,
    .shutdown = _ram_shutdown,
    .wait = px4_sem_wait,
}
Definition at line 127 of file dataman.cpp.
Referenced by _file_clear(), _file_read(), _file_restart(), _file_write(), _ram_initialize(), _ram_shutdown(), and task_main().
int fd
Definition at line 154 of file dataman.cpp.
Referenced by MavlinkFtpTest::_burst_test(), MavlinkFtpTest::_read_test(), MavlinkFtpTest::_removedirectory_test(), MavlinkFtpTest::_removefile_test(), MavlinkFTP::_workCalcFileCRC32(), MavlinkFTP::_workOpen(), MavlinkFTP::_workTruncateFile(), accel(), UavcanEsc::add_poll_fd(), UavcanNode::add_poll_fd(), px4::logger::Logger::add_topic(), VtolType::apply_pwm_limits(), UavcanNode::attachITxQueueInjector(), baro(), bl_update_main(), blinkm_main(), OREOLED::bootloader_flash(), OREOLED::bootloader_fw_checksum(), bson_decoder_init_file(), bson_encoder_init_buf_file(), bson_encoder_init_file(), calc_timer_diff_to_dsp_us(), lis3mdl::calibrate(), LIS3MDL::calibrate(), HMC5883::calibrate(), IST8310::calibrate(), ist8310::calibrate(), hmc5883::calibrate(), LidarLitePWM::collect(), do_accel(), do_accel_calibration(), do_airspeed_calibration(), do_device(), do_esc_calibration(), do_gyro(), do_gyro_calibration(), do_import(), do_load(), do_mag(), do_mag_calibration(), VCDevExample::do_poll(), do_save(), dump_pgm(), esc_calib_main(), ParameterTest::exportImportAll(), LinuxGPIO::exportPin(), get_vdev(), gyro(), MavlinkReceiver::handle_message_play_tune(), RestartRequestHandler::handleRestartRequest(), hardfault_append_to_ulog(), hardfault_check_status(), hardfault_commit(), hardfault_get_desc(), hardfault_increment_reboot(), px4::logger::LogWriterFile::hardfault_store_filename(), lis3mdl::init(), ulanding::Radar::init(), VtolType::init(), leddar_one_main(), mag(), VCDevExample::main(), motor_ramp_thread_main(), mtd_main(), navio_sysfs_rc_in::RcInput::navio_rc_init(), uORB::Manager::node_advertise(), uORB::Manager::node_open(), nshterm_main(), linux_pwm_out::PCA9685::open_fd(), Syslink::open_serial(), uORB::Manager::orb_advertise_multi(), uORB::Manager::orb_exists(), oreoled_main(), param_save_default(), Sensors::parameter_update_poll(), pca8574_main(), pca9685_main(), pwm_main(), linux_pwm_out::NavioSysfsPWMOut::pwm_write_sysfs(), pwmin_reset(), pwmin_test(), px4_close(), px4_poll(), MavlinkReceiver::receive_thread(), Mavlink::request_stop_ulog_streaming(), bmi160::reset(), sdp3x_airspeed::reset(), ms5525_airspeed::reset(), adis16477::reset(), bmm150::reset(), lps22hb::reset(), ll40ls::reset(), lis3mdl::reset(), mpu9250::reset(), meas_airspeed_sim::reset(), meas_airspeed::reset(), bmp280::reset(), sf1xx::reset(), px4flow::reset(), mb12xx::reset(), hc_sr04::reset(), srf02::reset(), tfmini::reset(), pmw3901::reset(), mpl3115a2::reset(), teraranger::reset(), sf0x::reset(), bma180::reset(), lps25h::reset(), ms5611::reset(), l3gd20::reset(), fxas21002c::reset(), ist8310::reset(), hmc5883::reset(), fxos8701cq::reset(), adis16448::reset(), lsm303d::reset(), mpu6000::reset(), LidarLitePWM::reset_sensor(), px4::logger::Logger::run(), PX4IO::set_update_rate(), LinuxGPIO::setDirection(), bmi160::start(), adis16477::start(), bmm150::start(), ll40ls::start(), meas_airspeed_sim::start(), px4flow::start(), hc_sr04::start(), tfmini::start(), pmw3901::start(), sf0x::start(), bma180::start(), l3gd20::start(), fxas21002c::start(), fxos8701cq::start(), adis16448::start(), lsm303d::start(), sdp3x_airspeed::start_bus(), ms5525_airspeed::start_bus(), lps22hb::start_bus(), mpu9250::start_bus(), ets_airspeed::start_bus(), meas_airspeed::start_bus(), bmp280::start_bus(), sf1xx::start_bus(), mb12xx::start_bus(), srf02::start_bus(), mpl3115a2::start_bus(), teraranger::start_bus(), lps25h::start_bus(), ms5611::start_bus(), vl53lxx::start_bus(), ist8310::start_bus(), hmc5883::start_bus(), mpu6000::start_bus(), rc_receiver::task_main(), ulanding::Radar::task_main(), hmc5883::temp_enable(), bmi160::test(), adis16477::test(), bmm150::test(), ll40ls::test(), test(), lis3mdl::test(), PX4FMU::test(), mpu9250::test(), meas_airspeed_sim::test(), bmp280::test(), sf1xx::test(), px4flow::test(), mb12xx::test(), hc_sr04::test(), srf02::test(), tfmini::test(), pmw3901::test(), mpl3115a2::test(), teraranger::test(), sf0x::test(), bma180::test(), lps25h::test(), ms5611::test(), vl53lxx::test(), ist8310::test(), hmc5883::test(), adis16448::test(), mpu6000::test(), test_adc(), test_corruption(), test_file(), test_gpio(), test_hott_telemetry(), test_jig_voltages(), test_led(), test_mount(), test_servo(), test_tone(), tone_alarm_main(), LinuxGPIO::unexportPin(), ToneAlarm::write(), and writer_main().
struct { ... } file
Referenced by MavlinkFtpTest::_read_badsession_test(), MavlinkFtpTest::_removefile_test(), MavlinkFtpTest::_terminate_badsession_test(), PX4FMU::arm_nothrottle(), LogListHelper::get_entry(), UavcanMagnetometerBridge::get_name(), UavcanBarometerBridge::get_name(), RestartRequestHandler::handleRestartRequest(), px4::Replay::onSubscriptionAdded(), Mavlink2Dev::~Mavlink2Dev(), and RtpsDev::~RtpsDev().
const dm_operations_t* g_dm_ops static
Definition at line 149 of file dataman.cpp.
work_q_t g_free_q static
Definition at line 275 of file dataman.cpp.
unsigned g_func_counts[dm_number_of_funcs] static
Definition at line 214 of file dataman.cpp.
Referenced by status(), and task_main().
px4_sem_t g_init_sema static
Definition at line 279 of file dataman.cpp.
px4_sem_t* g_item_locks[DM_KEY_NUM_KEYS] static
Definition at line 244 of file dataman.cpp.
unsigned int g_key_offsets[DM_KEY_NUM_KEYS] static
Definition at line 241 of file dataman.cpp.
const unsigned g_per_item_max_index[DM_KEY_NUM_KEYS] static
Initial value:
= {
    DM_KEY_SAFE_POINTS_MAX,
    DM_KEY_FENCE_POINTS_MAX,
    DM_KEY_WAYPOINTS_OFFBOARD_0_MAX,
    DM_KEY_WAYPOINTS_OFFBOARD_1_MAX,
    DM_KEY_WAYPOINTS_ONBOARD_MAX,
    DM_KEY_MISSION_STATE_MAX,
    DM_KEY_COMPAT_MAX
}
Definition at line 217 of file dataman.cpp.
Referenced by _file_clear(), _file_restart(), _ram_clear(), _ram_restart(), calculate_offset(), and task_main().
constexpr size_t g_per_item_size[DM_KEY_NUM_KEYS] static
Initial value:
= {
    sizeof(struct mission_save_point_s) + DM_SECTOR_HDR_SIZE,
    sizeof(struct mission_fence_point_s) + DM_SECTOR_HDR_SIZE,
    sizeof(struct mission_item_s) + DM_SECTOR_HDR_SIZE,
    sizeof(struct mission_item_s) + DM_SECTOR_HDR_SIZE,
    sizeof(struct mission_item_s) + DM_SECTOR_HDR_SIZE,
    sizeof(struct mission_s) + DM_SECTOR_HDR_SIZE,
    sizeof(struct dataman_compat_s) + DM_SECTOR_HDR_SIZE
}
Definition at line 230 of file dataman.cpp.
Referenced by _file_clear(), _file_read(), _file_restart(), _file_write(), _ram_clear(), _ram_read(), _ram_restart(), _ram_write(), calculate_offset(), and task_main().
px4_sem_t g_sys_state_mutex_fence static
Definition at line 246 of file dataman.cpp.
Referenced by task_main().
px4_sem_t g_sys_state_mutex_mission static
Definition at line 245 of file dataman.cpp.
Referenced by task_main().
bool g_task_should_exit static
if true, dataman task should exit
Definition at line 281 of file dataman.cpp.
work_q_t g_work_q static
Definition at line 276 of file dataman.cpp.
px4_sem_t g_work_queued_sema static
Definition at line 278 of file dataman.cpp.
char* k_data_manager_device_path = nullptr static
Definition at line 250 of file dataman.cpp.
const size_t k_work_item_allocation_chunk_size = 8
Definition at line 211 of file dataman.cpp.
Referenced by create_work_item().
struct { ... } ram
bool running
Definition at line 169 of file dataman.cpp.
Referenced by px4::AppState::setRunning().