PX4 Firmware: MuorbTestExample Class Reference
MuorbTestExample Class Reference
#include <muorb_test_example.h>
Public Member Functions
MuorbTestExample ()
~MuorbTestExample ()
int main ()
MuorbTestExample ()
~MuorbTestExample ()
int main ()
Static Public Attributes
static px4::AppState appState
Private Member Functions
int DefaultTest ()
int PingPongTest ()
int DefaultTest ()
int PingPongTest ()
int FileReadTest ()
int uSleepTest ()
Private Attributes
struct esc_status_s m_esc_status
struct vehicle_command_s m_vc = {}
Detailed Description
Definition at line 46 of file muorb_test_example.h.
Constructor & Destructor Documentation
MuorbTestExample::MuorbTestExample () inline
Definition at line 49 of file muorb_test_example.h.
MuorbTestExample::~MuorbTestExample () inline
Definition at line 51 of file muorb_test_example.h.
References main().
MuorbTestExample::MuorbTestExample () inline
Definition at line 43 of file muorb_test_example.h.
MuorbTestExample::~MuorbTestExample () inline
Definition at line 44 of file muorb_test_example.h.
References appState, DefaultTest(), FileReadTest(), main(), PingPongTest(), and uSleepTest().
Member Function Documentation
int MuorbTestExample::DefaultTest () private
int MuorbTestExample::DefaultTest () private
Definition at line 58 of file muorb_test_example.cpp.
References appState, px4::AppState::exitRequested(), m_esc_status, m_vc, orb_advert_t, orb_advertise(), orb_check(), orb_copy(), ORB_ID, orb_publish(), orb_subscribe(), PX4_DEBUG, PX4_ERR, and PX4_ERROR.
Referenced by ~MuorbTestExample().
int MuorbTestExample::FileReadTest () private
Definition at line 181 of file muorb_test_example.cpp.
References OK, PX4_ERROR, PX4_INFO, and PX4_WARN.
Referenced by ~MuorbTestExample().
int MuorbTestExample::main ()
int MuorbTestExample::main ()
Definition at line 49 of file muorb_test_example.cpp.
References appState, PingPongTest(), and px4::AppState::setRunning().
Referenced by muorb_test_entry(), PX4_MAIN(), and ~MuorbTestExample().
int MuorbTestExample::PingPongTest () private
int MuorbTestExample::PingPongTest () private
Definition at line 127 of file muorb_test_example.cpp.
References appState, px4::AppState::exitRequested(), m_esc_status, m_vc, orb_advert_t, orb_advertise(), orb_check(), orb_copy(), ORB_ID, orb_publish(), orb_subscribe(), PX4_ERR, PX4_ERROR, PX4_INFO, and usleep().
Referenced by main(), and ~MuorbTestExample().
int MuorbTestExample::uSleepTest () private
Definition at line 165 of file muorb_test_example.cpp.
References hrt_absolute_time(), PX4_INFO, PX4_WARN, and usleep().
Referenced by ~MuorbTestExample().
Member Data Documentation
static px4::AppState MuorbTestExample::appState static
Definition at line 55 of file muorb_test_example.h.
Referenced by DefaultTest(), main(), muorb_test_main(), PingPongTest(), and ~MuorbTestExample().
struct esc_status_s MuorbTestExample::m_esc_status private
Definition at line 59 of file muorb_test_example.h.
Referenced by DefaultTest(), and PingPongTest().
struct vehicle_command_s MuorbTestExample::m_vc = {} private
Definition at line 60 of file muorb_test_example.h.
Referenced by DefaultTest(), and PingPongTest().
The documentation for this class was generated from the following files:
src/platforms/posix/tests/muorb/muorb_test_example.h
src/platforms/posix/tests/muorb/muorb_test_example.cpp