PX4 Firmware: src/drivers/imu/mpu6000/mpu6000_main.cpp File Reference
mpu6000_main.cpp File Reference
#include "MPU6000.hpp"
Classes
struct mpu6000::mpu6000_bus_option
Namespaces
mpu6000
Local functions in support of the shell command.
Macros
#define NUM_BUS_OPTIONS (sizeof(bus_options)/sizeof(bus_options[0]))
Functions
void mpu6000::start (enum MPU6000_BUS busid, enum Rotation rotation, int device_type)
Start the driver.
bool mpu6000::start_bus (struct mpu6000_bus_option &bus, enum Rotation rotation, int device_type)
start driver for a specific bus option
void mpu6000::stop (enum MPU6000_BUS busid)
static struct mpu6000_bus_option & mpu6000::find_bus (enum MPU6000_BUS busid)
find a bus structure for a busid
void mpu6000::reset (enum MPU6000_BUS busid)
Reset the driver.
void mpu6000::info (enum MPU6000_BUS busid)
Print a little info about the driver.
void mpu6000::regdump (enum MPU6000_BUS busid)
Dump the register information.
void mpu6000::testerror (enum MPU6000_BUS busid)
deliberately produce an error to test recovery
void mpu6000::factorytest (enum MPU6000_BUS busid)
Dump the register information.
void mpu6000::usage ()
Prints info about the driver argument usage.
__EXPORT int mpu6000_main (int argc, char *argv[])
driver 'main' command
Variables
struct mpu6000::mpu6000_bus_option mpu6000::bus_options []
Macro Definition Documentation
NUM_BUS_OPTIONS
#define NUM_BUS_OPTIONS (sizeof(bus_options)/sizeof(bus_options[0]))
Definition at line 95 of file mpu6000_main.cpp.
Referenced by mpu6000::find_bus(), and mpu6000::start().
Function Documentation
mpu6000_main()
int mpu6000_main (int argc, char * argv[])
driver 'main' command
Definition at line 342 of file mpu6000_main.cpp.
References mpu6000::mpu6000_bus_option::busid, mpu6000::mpu6000_bus_option::device_type, mpu6000::factorytest(), mpu6000::info(), MPU6000_BUS_ALL, MPU6000_BUS_I2C_EXTERNAL, MPU6000_BUS_I2C_INTERNAL, MPU6000_BUS_SPI_EXTERNAL1, MPU6000_BUS_SPI_EXTERNAL2, MPU6000_BUS_SPI_INTERNAL1, MPU6000_BUS_SPI_INTERNAL2, MPU_DEVICE_TYPE_MPU6000, mpu6000::regdump(), mpu6000::reset(), ROTATION_NONE, mpu6000::start(), mpu6000::stop(), mpu6000::testerror(), and mpu6000::usage().
Referenced by mpu6000::usage().