PX4 Firmware: src/drivers/pca8574/pca8574.cpp File Reference
pca8574.cpp File Reference
Driver for an 8 I/O controller (PC8574) connected via I2C.
#include <px4_config.h>
#include <drivers/device/i2c.h>
#include <sys/types.h>
#include <stdint.h>
#include <string.h>
#include <stdlib.h>
#include <stdbool.h>
#include <fcntl.h>
#include <unistd.h>
#include <stdio.h>
#include <ctype.h>
#include <nuttx/wqueue.h>
#include <perf/perf_counter.h>
#include <systemlib/err.h>
#include <board_config.h>
#include <drivers/drv_io_expander.h>
Classes
class PCA8574
Macros
#define PCA8574_ONTIME 120
#define PCA8574_OFFTIME 120
#define PCA8574_DEVICE_PATH "/dev/pca8574"
#define ADDR 0x20
I2C adress of PCA8574 (default, A0-A2 pulled to GND)
Functions
void pca8574_usage ()
__EXPORT int pca8574_main (int argc, char *argv[])
Detailed Description
Driver for an 8 I/O controller (PC8574) connected via I2C.
Author
Lorenz Meier lm@in.nosp@m.f.et.nosp@m.hz.ch
Julian Oes joes@.nosp@m.stud.nosp@m.ent.e.nosp@m.thz..nosp@m.ch
Anton Babushkin anton.nosp@m..bab.nosp@m.ushki.nosp@m.n@me.nosp@m..com
Definition in file pca8574.cpp.
Macro Definition Documentation
#define ADDR 0x20
I2C adress of PCA8574 (default, A0-A2 pulled to GND)
Definition at line 71 of file pca8574.cpp.
Referenced by pca8574_main(), and pca8574_usage().
#define PCA8574_DEVICE_PATH "/dev/pca8574"
Definition at line 69 of file pca8574.cpp.
Referenced by pca8574_main().
#define PCA8574_OFFTIME 120
Definition at line 68 of file pca8574.cpp.
#define PCA8574_ONTIME 120
Definition at line 67 of file pca8574.cpp.
Function Documentation
int pca8574_main (int argc, char * argv[])
Definition at line 369 of file pca8574.cpp.
References ADDR, errx, fd, PCA8574::ioctl(), IOX_MODE_OFF, IOX_MODE_TEST_OUT, IOX_SET_MODE, IOX_SET_VALUE, OK, PCA8574::PCA8574(), PCA8574_DEVICE_PATH, pca8574_usage(), PX4_I2C_BUS_EXPANSION, PX4_I2C_BUS_LED, usleep(), and warnx.
void pca8574_usage ()
Definition at line 360 of file pca8574.cpp.
References ADDR, PX4_I2C_BUS_LED, and warnx.
Referenced by pca8574_main().