PX4 Firmware: navio_sysfs_rc_in Namespace Reference
navio_sysfs_rc_in Namespace Reference
Classes
class RcInput
Functions
__EXPORT int navio_sysfs_rc_in_main (int argc, char *argv[])
static void usage (const char *reason)
Print the correct usage.
Variables
static RcInput * rc_input = nullptr
Function Documentation
int navio_sysfs_rc_in::navio_sysfs_rc_in_main (int argc, char * argv[])
Definition at line 230 of file navio_sysfs_rc_in.cpp.
References navio_sysfs_rc_in::RcInput::isRunning(), PX4_ERR, PX4_INFO, PX4_WARN, rc_input, navio_sysfs_rc_in::RcInput::RcInput(), navio_sysfs_rc_in::RcInput::start(), navio_sysfs_rc_in::RcInput::stop(), usage(), and usleep().
static void navio_sysfs_rc_in::usage (const char * reason) static
Print the correct usage.
Definition at line 219 of file navio_sysfs_rc_in.cpp.
References PX4_ERR, and PX4_INFO.
Referenced by navio_sysfs_rc_in::RcInput::_measure(), and navio_sysfs_rc_in_main().
Variable Documentation
RcInput* navio_sysfs_rc_in::rc_input = nullptr static
Definition at line 228 of file navio_sysfs_rc_in.cpp.
Referenced by navio_sysfs_rc_in_main().