PX4 Firmware: vmount::InputMavlinkCmdMount Class Reference
vmount::InputMavlinkCmdMount Class Reference
class InputMavlinkCmdMount Input based on the VEHICLE_CMD_DO_MOUNT_CONTROL mavlink command
#include <input_mavlink.h>
Public Member Functions
InputMavlinkCmdMount (bool stabilize)
virtual ~InputMavlinkCmdMount ()
virtual void print_status ()
report status to stdout
Public Member Functions inherited from vmount::InputBase
virtual ~InputBase ()
virtual int update (unsigned int timeout_ms, ControlData **control_data, bool already_active)
Wait for an input update, with a timeout.
Protected Member Functions
virtual int update_impl (unsigned int timeout_ms, ControlData **control_data, bool already_active)
virtual int initialize ()
Protected Member Functions inherited from vmount::InputBase
void control_data_set_lon_lat (double lon, double lat, float altitude, float roll_angle=0.f, float pitch_fixed_angle=-10.f)
Private Member Functions
void _ack_vehicle_command (vehicle_command_s *cmd)
Private Attributes
int _vehicle_command_sub = -1
bool _stabilize [3] = { false, false, false }
int32_t _mav_sys_id {1}
our mavlink system id
int32_t _mav_comp_id {1}
our mavlink component id
Additional Inherited Members
Protected Attributes inherited from vmount::InputBase
ControlData _control_data
Detailed Description
class InputMavlinkCmdMount Input based on the VEHICLE_CMD_DO_MOUNT_CONTROL mavlink command
Definition at line 80 of file input_mavlink.h.
Constructor & Destructor Documentation
InputMavlinkCmdMount()
vmount::InputMavlinkCmdMount::InputMavlinkCmdMount (bool stabilize)
Definition at line 178 of file input_mavlink.cpp.
References _mav_comp_id, _mav_sys_id, param_find(), param_get(), and PARAM_INVALID.
~InputMavlinkCmdMount()
vmount::InputMavlinkCmdMount::~InputMavlinkCmdMount () virtual
Definition at line 194 of file input_mavlink.cpp.
References _vehicle_command_sub, and orb_unsubscribe().
Member Function Documentation
_ack_vehicle_command()
void vmount::InputMavlinkCmdMount::_ack_vehicle_command (vehicle_command_s * cmd) private
Definition at line 334 of file input_mavlink.cpp.
References vehicle_command_s::command, hrt_absolute_time(), ORB_ID, vehicle_command_s::source_component, vehicle_command_s::source_system, and vehicle_command_ack_s::timestamp.
Referenced by update_impl().
initialize()
int vmount::InputMavlinkCmdMount::initialize () protected virtual
Reimplemented from vmount::InputBase.
Definition at line 201 of file input_mavlink.cpp.
References _vehicle_command_sub, ORB_ID, orb_set_interval(), and orb_subscribe().
print_status()
void vmount::InputMavlinkCmdMount::print_status () virtual
report status to stdout
Implements vmount::InputBase.
Definition at line 348 of file input_mavlink.cpp.
update_impl()
int vmount::InputMavlinkCmdMount::update_impl (unsigned int timeout_ms, ControlData ** control_data, bool already_active) protected virtual
Implements vmount::InputBase.
Definition at line 216 of file input_mavlink.cpp.
References _ack_vehicle_command(), vmount::InputBase::_control_data, _mav_comp_id, _mav_sys_id, _stabilize, _vehicle_command_sub, vmount::ControlData::Angle, vmount::ControlData::TypeData::angle, vmount::ControlData::TypeData::TypeAngle::angles, vehicle_command_s::command, vmount::InputBase::control_data_set_lon_lat(), vmount::ControlData::gimbal_shutter_retract, hrt_absolute_time(), hrt_abstime, vmount::ControlData::TypeData::TypeAngle::is_speed, M_PI_F, vmount::ControlData::Neutral, orb_copy(), ORB_ID, vehicle_command_s::param1, vehicle_command_s::param2, vehicle_command_s::param3, vehicle_command_s::param4, vehicle_command_s::param7, px4_poll(), vmount::ControlData::stabilize_axis, vehicle_command_s::target_component, vehicle_command_s::target_system, vmount::ControlData::type, and vmount::ControlData::type_data.
Member Data Documentation
_mav_comp_id
int32_t vmount::InputMavlinkCmdMount::_mav_comp_id {1} private
our mavlink component id
Definition at line 99 of file input_mavlink.h.
Referenced by InputMavlinkCmdMount(), and update_impl().
_mav_sys_id
int32_t vmount::InputMavlinkCmdMount::_mav_sys_id {1} private
our mavlink system id
Definition at line 98 of file input_mavlink.h.
Referenced by InputMavlinkCmdMount(), and update_impl().
_stabilize
bool vmount::InputMavlinkCmdMount::_stabilize[3] = { false, false, false } private
Definition at line 96 of file input_mavlink.h.
Referenced by update_impl().
_vehicle_command_sub
int vmount::InputMavlinkCmdMount::_vehicle_command_sub = -1 private
Definition at line 95 of file input_mavlink.h.
Referenced by initialize(), update_impl(), and ~InputMavlinkCmdMount().
The documentation for this class was generated from the following files:
src/modules/vmount/input_mavlink.h
src/modules/vmount/input_mavlink.cpp