PX4 Firmware: src/drivers/kinetis/drv_io_timer.c File Reference
drv_io_timer.c File Reference
#include <px4_config.h>
#include <systemlib/px4_macros.h>
#include <nuttx/arch.h>
#include <nuttx/irq.h>
#include <sys/types.h>
#include <stdbool.h>
#include <assert.h>
#include <debug.h>
#include <time.h>
#include <queue.h>
#include <errno.h>
#include <string.h>
#include <stdio.h>
#include <arch/board/board.h>
#include <drivers/drv_pwm_output.h>
#include "drv_io_timer.h"
#include <kinetis.h>
#include "chip/kinetis_sim.h"
#include "chip/kinetis_ftm.h"
Classes
struct channel_stat_t
struct channel_handler_entry
Macros
#define BOARD_PWM_FREQ 1000000
#define BOARD_ONESHOT_FREQ 8000000
#define FTM_SRC_CLOCK_FREQ 16000000
#define MAX_CHANNELS_PER_TIMER 8
#define _REG(_addr) (*(volatile uint32_t *)(_addr))
#define _REG32(_base, _reg) (*(volatile uint32_t *)(_base + _reg))
#define REG(_tmr, _reg) _REG32(io_timers[_tmr].base, _reg)
#define rSC(_tmr) REG(_tmr,KINETIS_FTM_SC_OFFSET)
#define rCNT(_tmr) REG(_tmr,KINETIS_FTM_CNT_OFFSET)
#define rMOD(_tmr) REG(_tmr,KINETIS_FTM_MOD_OFFSET)
#define rC0SC(_tmr) REG(_tmr,KINETIS_FTM_C0SC_OFFSET)
#define rC0V(_tmr) REG(_tmr,KINETIS_FTM_C0V_OFFSET)
#define rC1SC(_tmr) REG(_tmr,KINETIS_FTM_C1SC_OFFSET)
#define rC1V(_tmr) REG(_tmr,KINETIS_FTM_C1V_OFFSET)
#define rC2SC(_tmr) REG(_tmr,KINETIS_FTM_C2SC_OFFSET)
#define rC2V(_tmr) REG(_tmr,KINETIS_FTM_C2V_OFFSET)
#define rC3SC(_tmr) REG(_tmr,KINETIS_FTM_C3SC_OFFSET)
#define rC3V(_tmr) REG(_tmr,KINETIS_FTM_C3V_OFFSET)
#define rC4SC(_tmr) REG(_tmr,KINETIS_FTM_C4SC_OFFSET)
#define rC4V(_tmr) REG(_tmr,KINETIS_FTM_C4V_OFFSET)
#define rC5SC(_tmr) REG(_tmr,KINETIS_FTM_C5SC_OFFSET)
#define rC5V(_tmr) REG(_tmr,KINETIS_FTM_C5V_OFFSET)
#define rC6SC(_tmr) REG(_tmr,KINETIS_FTM_C6SC_OFFSET)
#define rC6V(_tmr) REG(_tmr,KINETIS_FTM_C6V_OFFSET)
#define rC7SC(_tmr) REG(_tmr,KINETIS_FTM_C7SC_OFFSET)
#define rC7V(_tmr) REG(_tmr,KINETIS_FTM_C7V_OFFSET)
#define rCNTIN(_tmr) REG(_tmr,KINETIS_FTM_CNTIN_OFFSET)
#define rSTATUS(_tmr) REG(_tmr,KINETIS_FTM_STATUS_OFFSET)
#define rMODE(_tmr) REG(_tmr,KINETIS_FTM_MODE_OFFSET)
#define rSYNC(_tmr) REG(_tmr,KINETIS_FTM_SYNC_OFFSET)
#define rOUTINIT(_tmr) REG(_tmr,KINETIS_FTM_OUTINIT_OFFSET)
#define rOUTMASK(_tmr) REG(_tmr,KINETIS_FTM_OUTMASK_OFFSET)
#define rCOMBINE(_tmr) REG(_tmr,KINETIS_FTM_COMBINE_OFFSET)
#define rDEADTIME(_tmr) REG(_tmr,KINETIS_FTM_DEADTIME_OFFSET)
#define rEXTTRIG(_tmr) REG(_tmr,KINETIS_FTM_EXTTRIG_OFFSET)
#define rPOL(_tmr) REG(_tmr,KINETIS_FTM_POL_OFFSET)
#define rFMS(_tmr) REG(_tmr,KINETIS_FTM_FMS_OFFSET)
#define rFILTER(_tmr) REG(_tmr,KINETIS_FTM_FILTER_OFFSET)
#define rFLTCTRL(_tmr) REG(_tmr,KINETIS_FTM_FLTCTRL_OFFSET)
#define rQDCTRL(_tmr) REG(_tmr,KINETIS_FTM_QDCTRL_OFFSET)
#define rCONF(_tmr) REG(_tmr,KINETIS_FTM_CONF_OFFSET)
#define rFLTPOL(_tmr) REG(_tmr,KINETIS_FTM_FLTPOL_OFFSET)
#define rSYNCONF(_tmr) REG(_tmr,KINETIS_FTM_SYNCONF_OFFSET)
#define rINVCTRL(_tmr) REG(_tmr,KINETIS_FTM_INVCTRL_OFFSET)
#define rSWOCTRL(_tmr) REG(_tmr,KINETIS_FTM_SWOCTRL_OFFSET)
#define rPWMLOAD(_tmr) REG(_tmr,KINETIS_FTM_PWMLOAD_OFFSET)
#define CnSC_RESET (FTM_CSC_CHF|FTM_CSC_CHIE|FTM_CSC_MSB|FTM_CSC_MSA|FTM_CSC_ELSB|FTM_CSC_ELSA|FTM_CSC_DMA)
#define CnSC_CAPTURE_INIT (FTM_CSC_CHIE|FTM_CSC_ELSB|FTM_CSC_ELSA)
#define CnSC_PWMOUT_INIT (FTM_CSC_MSB|FTM_CSC_ELSB)
#define FTM_SYNC (FTM_SYNC_SWSYNC)
#define CnSC_PWMIN_INIT 0
Typedefs
typedef uint8_t io_timer_allocation_t
typedef struct channel_stat_t channel_stat_t
Functions
static int io_timer_handler (uint16_t timer_index)
int io_timer_handler0 (int irq, void *context, void *arg)
int io_timer_handler1 (int irq, void *context, void *arg)
int io_timer_handler2 (int irq, void *context, void *arg)
int io_timer_handler3 (int irq, void *context, void *arg)
static int validate_timer_index (unsigned timer)
static int is_timer_uninitalized (unsigned timer)
static void set_timer_initalized (unsigned timer)
static void set_timer_deinitalized (unsigned timer)
static int channels_timer (unsigned channel)
static int get_timers_firstchannels (unsigned timer)
static uint32_t get_timer_channels (unsigned timer)
static int is_channels_timer_uninitalized (unsigned channel)
int io_timer_is_channel_free (unsigned channel)
int io_timer_validate_channel_index (unsigned channel)
int io_timer_get_mode_channels (io_timer_channel_mode_t mode)
int io_timer_get_channel_mode (unsigned channel)
static int reallocate_channel_resources (uint32_t channels, io_timer_channel_mode_t mode, io_timer_channel_mode_t new_mode)
static int allocate_channel_resource (unsigned channel, io_timer_channel_mode_t mode)
static int free_channel_resource (unsigned channel)
int io_timer_free_channel (unsigned channel)
static int allocate_channel (unsigned channel, io_timer_channel_mode_t mode)
static int timer_set_rate (unsigned timer, unsigned rate)
static uint32_t div2psc (int div)
static void io_timer_set_oneshot_mode (unsigned timer)
static void io_timer_set_PWM_mode (unsigned timer)
void io_timer_trigger (void)
int io_timer_init_timer (unsigned timer)
int io_timer_set_rate (unsigned timer, unsigned rate)
int io_timer_channel_init (unsigned channel, io_timer_channel_mode_t mode, channel_handler_t channel_handler, void *context)
int io_timer_set_enable (bool state, io_timer_channel_mode_t mode, io_timer_channel_allocation_t masks)
int io_timer_set_ccr (unsigned channel, uint16_t value)
uint16_t io_channel_get_ccr (unsigned channel)
uint32_t io_timer_get_group (unsigned timer)
Variables
io_timer_channel_allocation_t channel_allocations [IOTimerChanModeSize] = { UINT16_MAX, 0, 0, 0, 0, 0 }
static io_timer_allocation_t once = 0
static channel_stat_t io_timer_channel_stats [MAX_TIMER_IO_CHANNELS]
static struct channel_handler_entry channel_handlers [MAX_TIMER_IO_CHANNELS]
Macro Definition Documentation
#define _REG (_addr) (*(volatile uint32_t *)(_addr))
Definition at line 84 of file drv_io_timer.c.
Referenced by io_timer_init_timer(), and io_timer_set_enable().
#define _REG32 (_base, _reg) (*(volatile uint32_t *)(_base + _reg))
Definition at line 85 of file drv_io_timer.c.
Referenced by io_timer_handler(), io_timer_set_enable(), and io_timer_trigger().
#define BOARD_ONESHOT_FREQ 8000000
Definition at line 77 of file drv_io_timer.c.
Referenced by io_timer_set_oneshot_mode().
#define BOARD_PWM_FREQ 1000000
Definition at line 73 of file drv_io_timer.c.
Referenced by io_timer_set_PWM_mode(), and timer_set_rate().
#define CnSC_CAPTURE_INIT (FTM_CSC_CHIE|FTM_CSC_ELSB|FTM_CSC_ELSA)
Definition at line 133 of file drv_io_timer.c.
Referenced by io_timer_channel_init().
#define CnSC_PWMIN_INIT 0
Definition at line 143 of file drv_io_timer.c.
#define CnSC_PWMOUT_INIT (FTM_CSC_MSB|FTM_CSC_ELSB)
Definition at line 138 of file drv_io_timer.c.
Referenced by io_timer_channel_init(), and io_timer_set_enable().
#define CnSC_RESET (FTM_CSC_CHF|FTM_CSC_CHIE|FTM_CSC_MSB|FTM_CSC_MSA|FTM_CSC_ELSB|FTM_CSC_ELSA|FTM_CSC_DMA)
Definition at line 132 of file drv_io_timer.c.
Referenced by io_timer_channel_init().
#define FTM_SRC_CLOCK_FREQ 16000000
Definition at line 80 of file drv_io_timer.c.
Referenced by io_timer_set_oneshot_mode(), and io_timer_set_PWM_mode().
#define FTM_SYNC (FTM_SYNC_SWSYNC)
Definition at line 141 of file drv_io_timer.c.
Referenced by io_timer_set_enable(), io_timer_trigger(), and timer_set_rate().
#define MAX_CHANNELS_PER_TIMER 8
Definition at line 82 of file drv_io_timer.c.
Referenced by io_timer_set_enable().
#define rC0SC (_tmr) REG(_tmr,KINETIS_FTM_C0SC_OFFSET)
Definition at line 94 of file drv_io_timer.c.
#define rC0V (_tmr) REG(_tmr,KINETIS_FTM_C0V_OFFSET)
Definition at line 95 of file drv_io_timer.c.
#define rC1SC (_tmr) REG(_tmr,KINETIS_FTM_C1SC_OFFSET)
Definition at line 96 of file drv_io_timer.c.
#define rC1V (_tmr) REG(_tmr,KINETIS_FTM_C1V_OFFSET)
Definition at line 97 of file drv_io_timer.c.
#define rC2SC (_tmr) REG(_tmr,KINETIS_FTM_C2SC_OFFSET)
Definition at line 98 of file drv_io_timer.c.
#define rC2V (_tmr) REG(_tmr,KINETIS_FTM_C2V_OFFSET)
Definition at line 99 of file drv_io_timer.c.
#define rC3SC (_tmr) REG(_tmr,KINETIS_FTM_C3SC_OFFSET)
Definition at line 100 of file drv_io_timer.c.
#define rC3V (_tmr) REG(_tmr,KINETIS_FTM_C3V_OFFSET)
Definition at line 101 of file drv_io_timer.c.
#define rC4SC (_tmr) REG(_tmr,KINETIS_FTM_C4SC_OFFSET)
Definition at line 102 of file drv_io_timer.c.
#define rC4V (_tmr) REG(_tmr,KINETIS_FTM_C4V_OFFSET)
Definition at line 103 of file drv_io_timer.c.
#define rC5SC (_tmr) REG(_tmr,KINETIS_FTM_C5SC_OFFSET)
Definition at line 104 of file drv_io_timer.c.
#define rC5V (_tmr) REG(_tmr,KINETIS_FTM_C5V_OFFSET)
Definition at line 105 of file drv_io_timer.c.
#define rC6SC (_tmr) REG(_tmr,KINETIS_FTM_C6SC_OFFSET)
Definition at line 106 of file drv_io_timer.c.
#define rC6V (_tmr) REG(_tmr,KINETIS_FTM_C6V_OFFSET)
Definition at line 107 of file drv_io_timer.c.
#define rC7SC (_tmr) REG(_tmr,KINETIS_FTM_C7SC_OFFSET)
Definition at line 108 of file drv_io_timer.c.
#define rC7V (_tmr) REG(_tmr,KINETIS_FTM_C7V_OFFSET)
Definition at line 109 of file drv_io_timer.c.
#define rCNT (_tmr) REG(_tmr,KINETIS_FTM_CNT_OFFSET)
Definition at line 92 of file drv_io_timer.c.
Referenced by io_timer_handler(), and io_timer_init_timer().
#define rCNTIN (_tmr) REG(_tmr,KINETIS_FTM_CNTIN_OFFSET)
Definition at line 111 of file drv_io_timer.c.
#define rCOMBINE (_tmr) REG(_tmr,KINETIS_FTM_COMBINE_OFFSET)
Definition at line 117 of file drv_io_timer.c.
#define rCONF (_tmr) REG(_tmr,KINETIS_FTM_CONF_OFFSET)
Definition at line 125 of file drv_io_timer.c.
Referenced by io_timer_init_timer().
#define rDEADTIME (_tmr) REG(_tmr,KINETIS_FTM_DEADTIME_OFFSET)
Definition at line 118 of file drv_io_timer.c.
#define REG (_tmr, _reg) _REG32(io_timers[_tmr].base, _reg)
Definition at line 86 of file drv_io_timer.c.
Referenced by io_channel_get_ccr(), io_timer_channel_init(), and io_timer_set_ccr().
#define rEXTTRIG (_tmr) REG(_tmr,KINETIS_FTM_EXTTRIG_OFFSET)
Definition at line 119 of file drv_io_timer.c.
#define rFILTER (_tmr) REG(_tmr,KINETIS_FTM_FILTER_OFFSET)
Definition at line 122 of file drv_io_timer.c.
#define rFLTCTRL (_tmr) REG(_tmr,KINETIS_FTM_FLTCTRL_OFFSET)
Definition at line 123 of file drv_io_timer.c.
#define rFLTPOL (_tmr) REG(_tmr,KINETIS_FTM_FLTPOL_OFFSET)
Definition at line 126 of file drv_io_timer.c.
#define rFMS (_tmr) REG(_tmr,KINETIS_FTM_FMS_OFFSET)
Definition at line 121 of file drv_io_timer.c.
#define rINVCTRL (_tmr) REG(_tmr,KINETIS_FTM_INVCTRL_OFFSET)
Definition at line 128 of file drv_io_timer.c.
#define rMOD (_tmr) REG(_tmr,KINETIS_FTM_MOD_OFFSET)
Definition at line 93 of file drv_io_timer.c.
Referenced by io_timer_set_oneshot_mode(), and timer_set_rate().
#define rMODE (_tmr) REG(_tmr,KINETIS_FTM_MODE_OFFSET)
Definition at line 113 of file drv_io_timer.c.
Referenced by io_timer_init_timer().
#define rOUTINIT (_tmr) REG(_tmr,KINETIS_FTM_OUTINIT_OFFSET)
Definition at line 115 of file drv_io_timer.c.
#define rOUTMASK (_tmr) REG(_tmr,KINETIS_FTM_OUTMASK_OFFSET)
Definition at line 116 of file drv_io_timer.c.
#define rPOL (_tmr) REG(_tmr,KINETIS_FTM_POL_OFFSET)
Definition at line 120 of file drv_io_timer.c.
#define rPWMLOAD (_tmr) REG(_tmr,KINETIS_FTM_PWMLOAD_OFFSET)
Definition at line 130 of file drv_io_timer.c.
#define rQDCTRL (_tmr) REG(_tmr,KINETIS_FTM_QDCTRL_OFFSET)
Definition at line 124 of file drv_io_timer.c.
#define rSC (_tmr) REG(_tmr,KINETIS_FTM_SC_OFFSET)
Definition at line 91 of file drv_io_timer.c.
Referenced by io_timer_init_timer(), io_timer_set_ccr(), io_timer_set_oneshot_mode(), io_timer_set_PWM_mode(), and timer_set_rate().
#define rSTATUS (_tmr) REG(_tmr,KINETIS_FTM_STATUS_OFFSET)
Definition at line 112 of file drv_io_timer.c.
Referenced by io_timer_handler().
#define rSWOCTRL (_tmr) REG(_tmr,KINETIS_FTM_SWOCTRL_OFFSET)
Definition at line 129 of file drv_io_timer.c.
#define rSYNC (_tmr) REG(_tmr,KINETIS_FTM_SYNC_OFFSET)
Definition at line 114 of file drv_io_timer.c.
Referenced by timer_set_rate().
#define rSYNCONF (_tmr) REG(_tmr,KINETIS_FTM_SYNCONF_OFFSET)
Definition at line 127 of file drv_io_timer.c.
Referenced by io_timer_init_timer().
Typedef Documentation
typedef struct channel_stat_t channel_stat_t
typedef uint8_t io_timer_allocation_t
Definition at line 148 of file drv_io_timer.c.
Function Documentation
static int allocate_channel (unsigned channel, io_timer_channel_mode_t mode) static
Definition at line 441 of file drv_io_timer.c.
References allocate_channel_resource(), io_timer_validate_channel_index(), and IOTimerChanMode_NotUsed.
Referenced by io_timer_channel_init().
static int allocate_channel_resource (unsigned channel, io_timer_channel_mode_t mode) inline static
Definition at line 396 of file drv_io_timer.c.
References channel_allocations, io_timer_is_channel_free(), and IOTimerChanMode_NotUsed.
Referenced by allocate_channel().
static int channels_timer (unsigned channel) inline static
Definition at line 267 of file drv_io_timer.c.
References timer_io_channels_t::timer_index, and timer_io_channels.
Referenced by io_channel_get_ccr(), io_timer_channel_init(), io_timer_set_ccr(), io_timer_set_enable(), and is_channels_timer_uninitalized().
static uint32_t div2psc (int div) inline static
Definition at line 476 of file drv_io_timer.c.
Referenced by io_timer_set_oneshot_mode(), and io_timer_set_PWM_mode().
static int free_channel_resource (unsigned channel) inline static
Definition at line 410 of file drv_io_timer.c.
References channel_allocations, io_timer_get_channel_mode(), and IOTimerChanMode_NotUsed.
Referenced by io_timer_free_channel().
static uint32_t get_timer_channels (unsigned timer) static
Definition at line 283 of file drv_io_timer.c.
References io_timers_t::first_channel_index, io_timers, MAX_IO_TIMERS, and validate_timer_index().
Referenced by io_timer_get_group(), io_timer_set_rate(), and io_timer_trigger().
static int get_timers_firstchannels (unsigned timer) inline static
Definition at line 272 of file drv_io_timer.c.
References io_timers_t::first_channel_index, io_timers, timer_io_channels_t::timer_channel, timer_io_channels, and validate_timer_index().
uint16_t io_channel_get_ccr (unsigned channel)
Definition at line 870 of file drv_io_timer.c.
Referenced by up_pwm_servo_get().
int io_timer_channel_init (unsigned channel, io_timer_channel_mode_t mode, channel_handler_t channel_handler, void * context)
Definition at line 645 of file drv_io_timer.c.
Referenced by up_input_capture_set(), up_pwm_servo_init(), up_pwm_trigger_deinit(), and up_pwm_trigger_init().
int io_timer_free_channel (unsigned channel)
Definition at line 423 of file drv_io_timer.c.
Referenced by up_input_capture_set(), up_pwm_servo_init(), and up_pwm_trigger_init().
int io_timer_get_channel_mode (unsigned channel)
Definition at line 357 of file drv_io_timer.c.
Referenced by free_channel_resource(), io_channel_get_ccr(), io_timer_free_channel(), io_timer_set_ccr(), up_input_capture_get_callback(), up_input_capture_get_filter(), up_input_capture_get_trigger(), up_input_capture_set_callback(), up_input_capture_set_filter(), and up_input_capture_set_trigger().
uint32_t io_timer_get_group (unsigned timer)
Definition at line 887 of file drv_io_timer.c.
Referenced by up_pwm_servo_get_rate_group().
int io_timer_get_mode_channels (io_timer_channel_mode_t mode)
Definition at line 348 of file drv_io_timer.c.
Referenced by io_timer_trigger(), up_pwm_servo_get_rate_group(), up_pwm_servo_init(), and up_pwm_trigger_deinit().
static int io_timer_handler (uint16_t timer_index) static
Definition at line 165 of file drv_io_timer.c.
References _REG32, io_timers_t::base, channel_handler_entry::callback, channel_handlers, io_timers_t::first_channel_index, hrt_absolute_time(), hrt_abstime, io_timers, channel_stat_t::isr_cout, channel_stat_t::overflows, rCNT, rSTATUS, and timer_io_channels.
Referenced by io_timer_handler0(), io_timer_handler1(), io_timer_handler2(), and io_timer_handler3().
int io_timer_handler0 (int irq, void * context, void * arg)
Definition at line 217 of file drv_io_timer.c.
int io_timer_handler1 (int irq, void * context, void * arg)
Definition at line 223 of file drv_io_timer.c.
int io_timer_handler2 (int irq, void * context, void * arg)
Definition at line 229 of file drv_io_timer.c.
int io_timer_handler3 (int irq, void * context, void * arg)
Definition at line 235 of file drv_io_timer.c.
int io_timer_init_timer (unsigned timer)
Definition at line 535 of file drv_io_timer.c.
Referenced by io_timer_channel_init().
int io_timer_is_channel_free (unsigned channel)
Definition at line 315 of file drv_io_timer.c.
Referenced by allocate_channel_resource(), up_input_capture_set(), up_pwm_servo_init(), and up_pwm_trigger_init().
int io_timer_set_ccr (unsigned channel, uint16_t value)
Definition at line 835 of file drv_io_timer.c.
Referenced by up_pwm_servo_set(), and up_pwm_trigger_set().
int io_timer_set_enable (bool state, io_timer_channel_mode_t mode, io_timer_channel_allocation_t masks)
Definition at line 715 of file drv_io_timer.c.
Referenced by io_timer_free_channel(), up_input_capture_set(), up_pwm_servo_arm(), and up_pwm_trigger_arm().
static void io_timer_set_oneshot_mode (unsigned timer) inline static
Definition at line 481 of file drv_io_timer.c.
References BOARD_ONESHOT_FREQ, div2psc(), FTM_SRC_CLOCK_FREQ, rMOD, and rSC.
Referenced by io_timer_set_rate().
static void io_timer_set_PWM_mode (unsigned timer) inline static
Definition at line 498 of file drv_io_timer.c.
References BOARD_PWM_FREQ, div2psc(), FTM_SRC_CLOCK_FREQ, and rSC.
Referenced by io_timer_init_timer(), and io_timer_set_rate().
__EXPORT int io_timer_set_rate (unsigned timer, unsigned rate)
Definition at line 592 of file drv_io_timer.c.
Referenced by up_pwm_servo_set_rate_group_update().
void io_timer_trigger (void)
Definition at line 506 of file drv_io_timer.c.
Referenced by up_pwm_update().
int io_timer_validate_channel_index (unsigned channel)
Definition at line 328 of file drv_io_timer.c.
Referenced by allocate_channel(), io_channel_get_ccr(), io_timer_free_channel(), io_timer_is_channel_free(), io_timer_set_ccr(), io_timer_set_enable(), up_input_capture_get_callback(), up_input_capture_get_filter(), up_input_capture_get_stats(), up_input_capture_get_trigger(), up_input_capture_set(), up_input_capture_set_callback(), up_input_capture_set_filter(), and up_input_capture_set_trigger().
static int is_channels_timer_uninitalized (unsigned channel) inline static
Definition at line 310 of file drv_io_timer.c.
References channels_timer(), and is_timer_uninitalized().
static int is_timer_uninitalized (unsigned timer) inline static
Definition at line 246 of file drv_io_timer.c.
References once.
Referenced by io_timer_init_timer(), and is_channels_timer_uninitalized().
static int reallocate_channel_resources (uint32_t channels, io_timer_channel_mode_t mode, io_timer_channel_mode_t new_mode) static
Definition at line 370 of file drv_io_timer.c.
References channel_allocations, and IOTimerChanMode_NotUsed.
Referenced by io_timer_set_rate().
static void set_timer_deinitalized (unsigned timer) inline static
Definition at line 262 of file drv_io_timer.c.
References once.
static void set_timer_initalized (unsigned timer) inline static
Definition at line 257 of file drv_io_timer.c.
References once.
Referenced by io_timer_init_timer().
static int timer_set_rate (unsigned timer, unsigned rate) static
Definition at line 456 of file drv_io_timer.c.
References BOARD_PWM_FREQ, FTM_SYNC, rMOD, rSC, and rSYNC.
Referenced by io_timer_init_timer(), and io_timer_set_rate().
static int validate_timer_index (unsigned timer) inline static
Definition at line 241 of file drv_io_timer.c.
References io_timers, and MAX_IO_TIMERS.
Referenced by get_timer_channels(), get_timers_firstchannels(), and io_timer_trigger().
Variable Documentation
io_timer_channel_allocation_t channel_allocations[IOTimerChanModeSize] = { UINT16_MAX, 0, 0, 0, 0, 0 }
Definition at line 146 of file drv_io_timer.c.
Referenced by allocate_channel_resource(), free_channel_resource(), io_timer_get_channel_mode(), io_timer_get_mode_channels(), io_timer_is_channel_free(), io_timer_set_enable(), io_timer_set_rate(), and reallocate_channel_resources().
struct channel_handler_entry channel_handlers[MAX_TIMER_IO_CHANNELS] static
Referenced by io_timer_channel_init(), and io_timer_handler().
channel_stat_t io_timer_channel_stats[MAX_TIMER_IO_CHANNELS] static
Definition at line 157 of file drv_io_timer.c.
io_timer_allocation_t once = 0 static
Definition at line 150 of file drv_io_timer.c.
Referenced by is_timer_uninitalized(), set_timer_deinitalized(), and set_timer_initalized().