PX4 Firmware: src/platforms/common/shutdown.cpp File Reference
shutdown.cpp File Reference
Implementation of the API declared in px4_shutdown.h.
#include <board_config.h>
#include <px4_log.h>
#include <px4_workqueue.h>
#include <px4_shutdown.h>
#include <px4_tasks.h>
#include <stdint.h>
#include <errno.h>
#include <pthread.h>
Macros
#define SHUTDOWN_ARG_IN_PROGRESS (1<<0)
#define SHUTDOWN_ARG_REBOOT (1<<1)
#define SHUTDOWN_ARG_TO_BOOTLOADER (1<<2)
Functions
int px4_shutdown_lock ()
Grab the shutdown lock.
int px4_shutdown_unlock ()
Release the shutdown lock.
static void shutdown_worker (void *arg)
work queue callback method to shutdown.
int px4_register_shutdown_hook (shutdown_hook_t hook)
Register a method that should be called when powering off (and also on reboot).
int px4_unregister_shutdown_hook (shutdown_hook_t hook)
Unregister a shutdown hook.
int px4_shutdown_request (bool reboot, bool to_bootloader)
Request the system to shut down or reboot.
Variables
static pthread_mutex_t shutdown_mutex
static uint8_t shutdown_lock_counter = 0
static struct work_s shutdown_work = {}
static uint16_t shutdown_counter = 0
count how many times the shutdown worker was executed
static uint8_t shutdown_args = 0
static const int max_shutdown_hooks = 1
static shutdown_hook_t shutdown_hooks [max_shutdown_hooks] = {}
static const int shutdown_timeout_ms = 5000
force shutdown after this time if modules do not respond in time
Detailed Description
Implementation of the API declared in px4_shutdown.h.
Definition in file shutdown.cpp.
Macro Definition Documentation
#define SHUTDOWN_ARG_IN_PROGRESS (1<<0)
Definition at line 118 of file shutdown.cpp.
Referenced by px4_shutdown_request().
#define SHUTDOWN_ARG_REBOOT (1<<1)
Definition at line 119 of file shutdown.cpp.
Referenced by px4_shutdown_request(), and shutdown_worker().
#define SHUTDOWN_ARG_TO_BOOTLOADER (1<<2)
Definition at line 120 of file shutdown.cpp.
Referenced by px4_shutdown_request(), and shutdown_worker().
Function Documentation
int px4_register_shutdown_hook (shutdown_hook_t hook)
Register a method that should be called when powering off (and also on reboot).
Parameters
hook callback method. It must not block, but return immediately. When the system is requested to shutdown, the registered hooks will be called regularily until either all of them return true, or a timeout is reached.
Returns
0 on success, <0 on error
Definition at line 138 of file shutdown.cpp.
References max_shutdown_hooks, pthread_mutex_lock(), pthread_mutex_unlock(), shutdown_hooks, and shutdown_mutex.
Referenced by px4_shutdown_unlock(), and px4::logger::Logger::run().
int px4_shutdown_lock (void)
Grab the shutdown lock.
It will prevent the system from shutting down until the lock is released. It is safe to call this recursively.
Returns
0 on success, <0 on error
Definition at line 52 of file shutdown.cpp.
References pthread_mutex_lock(), pthread_mutex_unlock(), shutdown_lock_counter, and shutdown_mutex.
Referenced by param_export(), param_export_internal(), and reboot_main().
int px4_shutdown_request (bool reboot, bool to_bootloader)
Request the system to shut down or reboot.
Note the following:
The system might not support to shutdown (or reboot). In that case -EINVAL will be returned.
The system might not shutdown immediately, so expect this method to return even on success.
Parameters
reboot perform a reboot instead of a shutdown
to_bootloader reboot into bootloader mode (only used if reboot is true)
Returns
0 on success, <0 on error
Definition at line 205 of file shutdown.cpp.
References SHUTDOWN_ARG_IN_PROGRESS, SHUTDOWN_ARG_REBOOT, SHUTDOWN_ARG_TO_BOOTLOADER, shutdown_args, and shutdown_worker().
Referenced by commander_low_prio_loop(), px4_shutdown_unlock(), reboot_main(), and Commander::run().
int px4_shutdown_unlock (void)
Release the shutdown lock.
Returns
0 on success, <0 on error
Definition at line 64 of file shutdown.cpp.
References board_shutdown(), pthread_mutex_lock(), pthread_mutex_unlock(), PX4_ERR, px4_register_shutdown_hook(), px4_shutdown_request(), px4_systemreset(), px4_unregister_shutdown_hook(), shutdown_hook_t, shutdown_lock_counter, and shutdown_mutex.
Referenced by param_export(), param_export_internal(), and reboot_main().
int px4_unregister_shutdown_hook (shutdown_hook_t hook)
Unregister a shutdown hook.
Parameters
hook callback method to be removed
Returns
0 on success, <0 on error
Definition at line 154 of file shutdown.cpp.
References max_shutdown_hooks, pthread_mutex_lock(), pthread_mutex_unlock(), shutdown_hooks, and shutdown_mutex.
Referenced by px4_shutdown_unlock(), and px4::logger::Logger::run().
void shutdown_worker (void * arg) static
work queue callback method to shutdown.
Parameters
arg unused
Definition at line 172 of file shutdown.cpp.
References board_shutdown(), max_shutdown_hooks, pthread_mutex_lock(), pthread_mutex_unlock(), PX4_DEBUG, px4_systemreset(), PX4_WARN, SHUTDOWN_ARG_REBOOT, SHUTDOWN_ARG_TO_BOOTLOADER, shutdown_args, shutdown_counter, shutdown_hooks, shutdown_lock_counter, shutdown_mutex, shutdown_timeout_ms, and shutdown_work.
Referenced by px4_shutdown_request().
Variable Documentation
const int max_shutdown_hooks = 1 static
Definition at line 124 of file shutdown.cpp.
Referenced by px4_register_shutdown_hook(), px4_unregister_shutdown_hook(), and shutdown_worker().
uint8_t shutdown_args = 0 static
Definition at line 121 of file shutdown.cpp.
Referenced by px4_shutdown_request(), and shutdown_worker().
uint16_t shutdown_counter = 0 static
count how many times the shutdown worker was executed
Definition at line 116 of file shutdown.cpp.
Referenced by shutdown_worker().
shutdown_hook_t shutdown_hooks[max_shutdown_hooks] = {} static
Definition at line 125 of file shutdown.cpp.
Referenced by px4_register_shutdown_hook(), px4_unregister_shutdown_hook(), and shutdown_worker().
uint8_t shutdown_lock_counter = 0 static
Definition at line 50 of file shutdown.cpp.
Referenced by px4_shutdown_lock(), px4_shutdown_unlock(), and shutdown_worker().
pthread_mutex_t shutdown_mutex static
Initial value:
=
    PTHREAD_MUTEX_INITIALIZER
Definition at line 48 of file shutdown.cpp.
Referenced by px4_register_shutdown_hook(), px4_shutdown_lock(), px4_shutdown_unlock(), px4_unregister_shutdown_hook(), and shutdown_worker().
const int shutdown_timeout_ms = 5000 static
force shutdown after this time if modules do not respond in time
Definition at line 128 of file shutdown.cpp.
Referenced by shutdown_worker().
struct work_s shutdown_work = {} static
Definition at line 115 of file shutdown.cpp.
Referenced by shutdown_worker().