PX4 Firmware: DfMpu9250Wrapper Class Reference
DfMpu9250Wrapper Class Reference
Classes
struct accel_calibration_s
struct gyro_calibration_s
struct mag_calibration_s
Public Member Functions
DfMpu9250Wrapper (bool mag_enabled, enum Rotation rotation)
~DfMpu9250Wrapper ()
int start ()
Start automatic measurement.
int stop ()
Stop automatic measurement.
void info ()
Print some debug info.
Public Member Functions inherited from MPU9250
MPU9250 (device::Device *interface, device::Device *mag_interface, const char *path_accel, const char *path_gyro, const char *path_mag, enum Rotation rotation)
virtual ~MPU9250 ()
virtual int init ()
Initialise the driver and make it ready for use.
virtual ssize_t read (struct file *filp, char *buffer, size_t buflen)
virtual int ioctl (struct file *filp, int cmd, unsigned long arg)
void print_info ()
Diagnostics - print some basic information about the driver.
void print_registers ()
void test_error ()
Public Member Functions inherited from device::CDev
CDev (const char *name, const char *devname)
Constructor.
virtual ~CDev ()
virtual int open (file_t *filep)
Handle an open of the device.
virtual int close (file_t *filep)
Handle a close of the device.
virtual ssize_t read (file_t *filep, char *buffer, size_t buflen)
Perform a read from the device.
virtual ssize_t write (file_t *filep, const char *buffer, size_t buflen)
Perform a write to the device.
virtual off_t seek (file_t *filep, off_t offset, int whence)
Perform a logical seek operation on the device.
virtual int ioctl (file_t *filep, int cmd, unsigned long arg)
Perform an ioctl operation on the device.
virtual int poll (file_t *filep, px4_pollfd_struct_t *fds, bool setup)
Perform a poll setup/teardown operation.
Public Member Functions inherited from device::Device
virtual ~Device ()=default
Destructor.
virtual int read (unsigned address, void *data, unsigned count)
Read directly from the device.
virtual int write (unsigned address, void *data, unsigned count)
Write directly to the device.
virtual int ioctl (unsigned operation, unsigned &arg)
Perform a device-specific operation.
uint8_t get_device_bus ()
Return the bus ID the device is connected to.
DeviceBusType get_device_bus_type ()
Return the bus type the device is connected to.
uint8_t get_device_address ()
Return the bus address of the device.
void set_device_address (int address)
void set_device_type (uint8_t devtype)
Set the device type.
virtual bool external ()
Private Member Functions
int _publish (struct imu_sensor_data &data)
void _update_accel_calibration ()
void _update_gyro_calibration ()
void _update_mag_calibration ()
Private Attributes
orb_advert_t _accel_topic
orb_advert_t _gyro_topic
orb_advert_t _mag_topic
orb_advert_t _mavlink_log_pub
int _param_update_sub
struct DfMpu9250Wrapper::accel_calibration_s _accel_calibration
struct DfMpu9250Wrapper::gyro_calibration_s _gyro_calibration
struct DfMpu9250Wrapper::mag_calibration_s _mag_calibration
int _accel_orb_class_instance
int _gyro_orb_class_instance
int _mag_orb_class_instance
Integrator _accel_int
Integrator _gyro_int
math::LowPassFilter2p _accel_filter_x
math::LowPassFilter2p _accel_filter_y
math::LowPassFilter2p _accel_filter_z
math::LowPassFilter2p _gyro_filter_x
math::LowPassFilter2p _gyro_filter_y
math::LowPassFilter2p _gyro_filter_z
perf_counter_t _read_counter
perf_counter_t _error_counter
perf_counter_t _fifo_overflow_counter
perf_counter_t _fifo_corruption_counter
perf_counter_t _gyro_range_hit_counter
perf_counter_t _accel_range_hit_counter
perf_counter_t _mag_fifo_overflow_counter
perf_counter_t _publish_perf
hrt_abstime _last_accel_range_hit_time
uint64_t _last_accel_range_hit_count
bool _mag_enabled
enum Rotation _rotation
Additional Inherited Members
Public Types inherited from device::Device
enum DeviceBusType { DeviceBusType_UNKNOWN = 0, DeviceBusType_I2C = 1, DeviceBusType_SPI = 2, DeviceBusType_UAVCAN = 3 }
Device bus types for DEVID.
Protected Member Functions inherited from MPU9250
virtual int probe ()
virtual ssize_t gyro_read (struct file *filp, char *buffer, size_t buflen)
virtual int gyro_ioctl (struct file *filp, int cmd, unsigned long arg)
Protected Member Functions inherited from device::CDev
virtual pollevent_t poll_state (file_t *filep)
Check the current state of the device for poll events from the perspective of the file.
virtual void poll_notify (pollevent_t events)
Report new poll events.
virtual void poll_notify_one (px4_pollfd_struct_t *fds, pollevent_t events)
Internal implementation of poll_notify.
virtual int open_first (file_t *filep)
Notification of the first open.
virtual int close_last (file_t *filep)
Notification of the last close.
virtual int register_class_devname (const char *class_devname)
Register a class device name, automatically adding device class instance suffix if need be.
virtual int unregister_class_devname (const char *class_devname, unsigned class_instance)
Register a class device name, automatically adding device class instance suffix if need be.
const char * get_devname ()
Get the device name.
void lock ()
Take the driver lock.
void unlock ()
Release the driver lock.
Protected Member Functions inherited from device::Device
Device (const char *name)
Device (DeviceBusType bus_type, uint8_t bus, uint8_t address, uint8_t devtype=0)
Device (const Device &)=delete
Device & operator= (const Device &)=delete
Device (Device &&)=delete
Device & operator= (Device &&)=delete
Protected Attributes inherited from MPU9250
Device * _interface
Protected Attributes inherited from device::CDev
px4_sem_t _lock
lock to protect access to all class members (also for derived classes)
bool _pub_blocked {false}
true if publishing should be blocked
Protected Attributes inherited from device::Device
union DeviceId _device_id
device identifier information
const char * _name
driver name
bool _debug_enabled {false}
if true, debug messages are printed
Static Protected Attributes inherited from device::CDev
static const px4_file_operations_t fops = {}
Pointer to the default cdev file operations table; useful for registering clone devices etc.
Detailed Description
Definition at line 86 of file df_mpu9250_wrapper.cpp.
Constructor & Destructor Documentation
DfMpu9250Wrapper::DfMpu9250Wrapper (bool mag_enabled, enum Rotation rotation)
Definition at line 185 of file df_mpu9250_wrapper.cpp.
References _accel_calibration, _accel_filter_x, _accel_filter_y, _accel_filter_z, _accel_int, _accel_orb_class_instance, _accel_range_hit_counter, _error_counter, _fifo_corruption_counter, _fifo_overflow_counter, _gyro_calibration, _gyro_filter_x, _gyro_filter_y, _gyro_filter_z, _gyro_int, _gyro_orb_class_instance, _gyro_range_hit_counter, _last_accel_range_hit_count, _last_accel_range_hit_time, _mag_calibration, _mag_enabled, _mag_fifo_overflow_counter, _mag_orb_class_instance, _publish_perf, _read_counter, _rotation, MPU9250_ACCEL_DEFAULT_DRIVER_FILTER_FREQ, MPU9250_ACCEL_DEFAULT_RATE, MPU9250_GYRO_DEFAULT_DRIVER_FILTER_FREQ, MPU9250_GYRO_DEFAULT_RATE, MPU9250_PUB_RATE, param_find(), param_get(), param_handle(), PARAM_INVALID, PC_COUNT, PC_ELAPSED, perf_alloc, PX4_ERR, PX4_OK, math::LowPassFilter2p::set_cutoff_frequency(), DfMpu9250Wrapper::accel_calibration_s::x_offset, DfMpu9250Wrapper::gyro_calibration_s::x_offset, DfMpu9250Wrapper::mag_calibration_s::x_offset, DfMpu9250Wrapper::accel_calibration_s::x_scale, DfMpu9250Wrapper::gyro_calibration_s::x_scale, DfMpu9250Wrapper::mag_calibration_s::x_scale, DfMpu9250Wrapper::accel_calibration_s::y_offset, DfMpu9250Wrapper::gyro_calibration_s::y_offset, DfMpu9250Wrapper::mag_calibration_s::y_offset, DfMpu9250Wrapper::accel_calibration_s::y_scale, DfMpu9250Wrapper::gyro_calibration_s::y_scale, DfMpu9250Wrapper::mag_calibration_s::y_scale, DfMpu9250Wrapper::accel_calibration_s::z_offset, DfMpu9250Wrapper::gyro_calibration_s::z_offset, DfMpu9250Wrapper::mag_calibration_s::z_offset, DfMpu9250Wrapper::accel_calibration_s::z_scale, DfMpu9250Wrapper::gyro_calibration_s::z_scale, and DfMpu9250Wrapper::mag_calibration_s::z_scale.
Referenced by df_mpu9250_wrapper::start().
DfMpu9250Wrapper::~DfMpu9250Wrapper ()
Definition at line 269 of file df_mpu9250_wrapper.cpp.
References _accel_range_hit_counter, _error_counter, _fifo_corruption_counter, _fifo_overflow_counter, _gyro_range_hit_counter, _mag_enabled, _mag_fifo_overflow_counter, _publish_perf, _read_counter, and perf_free().
Member Function Documentation
int DfMpu9250Wrapper::_publish (struct imu_sensor_data & data) private
Definition at line 600 of file df_mpu9250_wrapper.cpp.
References _accel_calibration, _accel_filter_x, _accel_filter_y, _accel_filter_z, _accel_int, _accel_range_hit_counter, _accel_topic, _error_counter, _fifo_corruption_counter, _fifo_overflow_counter, _gyro_calibration, _gyro_filter_x, _gyro_filter_y, _gyro_filter_z, _gyro_int, _gyro_range_hit_counter, _gyro_topic, _last_accel_range_hit_count, _last_accel_range_hit_time, _mag_calibration, _mag_enabled, _mag_fifo_overflow_counter, _mag_orb_class_instance, _mag_topic, _mavlink_log_pub, _param_update_sub, _publish_perf, _read_counter, _rotation, _update_accel_calibration(), _update_gyro_calibration(), _update_mag_calibration(), accel_report, math::LowPassFilter2p::apply(), gyro_report, hrt_absolute_time(), hrt_elapsed_time(), mag_report, mavlink_log_critical, orb_advertise_multi(), orb_check(), orb_copy(), ORB_ID, ORB_PRIO_LOW, orb_publish(), perf_begin(), perf_end(), perf_set_count(), Integrator::put(), rotate_3f(), DfMpu9250Wrapper::accel_calibration_s::x_offset, DfMpu9250Wrapper::gyro_calibration_s::x_offset, DfMpu9250Wrapper::mag_calibration_s::x_offset, DfMpu9250Wrapper::accel_calibration_s::x_scale, DfMpu9250Wrapper::gyro_calibration_s::x_scale, DfMpu9250Wrapper::mag_calibration_s::x_scale, DfMpu9250Wrapper::accel_calibration_s::y_offset, DfMpu9250Wrapper::gyro_calibration_s::y_offset, DfMpu9250Wrapper::mag_calibration_s::y_offset, DfMpu9250Wrapper::accel_calibration_s::y_scale, DfMpu9250Wrapper::gyro_calibration_s::y_scale, DfMpu9250Wrapper::mag_calibration_s::y_scale, DfMpu9250Wrapper::accel_calibration_s::z_offset, DfMpu9250Wrapper::gyro_calibration_s::z_offset, DfMpu9250Wrapper::mag_calibration_s::z_offset, DfMpu9250Wrapper::accel_calibration_s::z_scale, DfMpu9250Wrapper::gyro_calibration_s::z_scale, and DfMpu9250Wrapper::mag_calibration_s::z_scale.
void DfMpu9250Wrapper::_update_accel_calibration () private
Definition at line 444 of file df_mpu9250_wrapper.cpp.
References _accel_calibration, device_id, OK, param_find(), param_get(), PX4_ERR, DfMpu9250Wrapper::accel_calibration_s::x_offset, DfMpu9250Wrapper::accel_calibration_s::x_scale, DfMpu9250Wrapper::accel_calibration_s::y_offset, DfMpu9250Wrapper::accel_calibration_s::y_scale, DfMpu9250Wrapper::accel_calibration_s::z_offset, and DfMpu9250Wrapper::accel_calibration_s::z_scale.
Referenced by _publish(), and start().
void DfMpu9250Wrapper::_update_gyro_calibration () private
Definition at line 369 of file df_mpu9250_wrapper.cpp.
References _gyro_calibration, device_id, OK, param_find(), param_get(), PX4_ERR, DfMpu9250Wrapper::gyro_calibration_s::x_offset, DfMpu9250Wrapper::gyro_calibration_s::x_scale, DfMpu9250Wrapper::gyro_calibration_s::y_offset, DfMpu9250Wrapper::gyro_calibration_s::y_scale, DfMpu9250Wrapper::gyro_calibration_s::z_offset, and DfMpu9250Wrapper::gyro_calibration_s::z_scale.
Referenced by _publish(), and start().
void DfMpu9250Wrapper::_update_mag_calibration () private
Definition at line 520 of file df_mpu9250_wrapper.cpp.
References _mag_calibration, _mag_enabled, device_id, OK, param_find(), param_get(), PX4_ERR, DfMpu9250Wrapper::mag_calibration_s::x_offset, DfMpu9250Wrapper::mag_calibration_s::x_scale, DfMpu9250Wrapper::mag_calibration_s::y_offset, DfMpu9250Wrapper::mag_calibration_s::y_scale, DfMpu9250Wrapper::mag_calibration_s::z_offset, and DfMpu9250Wrapper::mag_calibration_s::z_scale.
Referenced by _publish(), and start().
void DfMpu9250Wrapper::info ()
Print some debug info.
Definition at line 353 of file df_mpu9250_wrapper.cpp.
References _accel_range_hit_counter, _error_counter, _fifo_corruption_counter, _fifo_overflow_counter, _gyro_range_hit_counter, _mag_enabled, _mag_fifo_overflow_counter, _publish_perf, _read_counter, and perf_print_counter().
Referenced by df_mpu9250_wrapper::info().
int DfMpu9250Wrapper::start ()
Start automatic measurement.
Returns
0 on success
Definition at line 285 of file df_mpu9250_wrapper.cpp.
References _accel_orb_class_instance, _accel_topic, _gyro_orb_class_instance, _gyro_topic, _mag_enabled, _param_update_sub, _update_accel_calibration(), _update_gyro_calibration(), _update_mag_calibration(), accel_report, gyro_report, MPU9250::init(), orb_advertise_multi(), ORB_ID, ORB_PRIO_DEFAULT, orb_subscribe(), PX4_DEBUG, PX4_ERR, and MPU9250::start().
Referenced by df_mpu9250_wrapper::start().
int DfMpu9250Wrapper::stop ()
Stop automatic measurement.
Returns
0 on success
Definition at line 340 of file df_mpu9250_wrapper.cpp.
References PX4_ERR, and MPU9250::stop().
Referenced by df_mpu9250_wrapper::stop().
Member Data Documentation
struct DfMpu9250Wrapper::accel_calibration_s DfMpu9250Wrapper::_accel_calibration private
Referenced by _publish(), _update_accel_calibration(), and DfMpu9250Wrapper().
math::LowPassFilter2p DfMpu9250Wrapper::_accel_filter_x private
Definition at line 161 of file df_mpu9250_wrapper.cpp.
Referenced by _publish(), and DfMpu9250Wrapper().
math::LowPassFilter2p DfMpu9250Wrapper::_accel_filter_y private
Definition at line 162 of file df_mpu9250_wrapper.cpp.
Referenced by _publish(), and DfMpu9250Wrapper().
math::LowPassFilter2p DfMpu9250Wrapper::_accel_filter_z private
Definition at line 163 of file df_mpu9250_wrapper.cpp.
Referenced by _publish(), and DfMpu9250Wrapper().
Integrator DfMpu9250Wrapper::_accel_int private
Definition at line 158 of file df_mpu9250_wrapper.cpp.
Referenced by _publish(), and DfMpu9250Wrapper().
int DfMpu9250Wrapper::_accel_orb_class_instance private
Definition at line 154 of file df_mpu9250_wrapper.cpp.
Referenced by DfMpu9250Wrapper(), and start().
perf_counter_t DfMpu9250Wrapper::_accel_range_hit_counter private
Definition at line 173 of file df_mpu9250_wrapper.cpp.
Referenced by _publish(), DfMpu9250Wrapper(), info(), and ~DfMpu9250Wrapper().
orb_advert_t DfMpu9250Wrapper::_accel_topic private
Definition at line 119 of file df_mpu9250_wrapper.cpp.
Referenced by _publish(), and start().
perf_counter_t DfMpu9250Wrapper::_error_counter private
Definition at line 169 of file df_mpu9250_wrapper.cpp.
Referenced by _publish(), DfMpu9250Wrapper(), info(), and ~DfMpu9250Wrapper().
perf_counter_t DfMpu9250Wrapper::_fifo_corruption_counter private
Definition at line 171 of file df_mpu9250_wrapper.cpp.
Referenced by _publish(), DfMpu9250Wrapper(), info(), and ~DfMpu9250Wrapper().
perf_counter_t DfMpu9250Wrapper::_fifo_overflow_counter private
Definition at line 170 of file df_mpu9250_wrapper.cpp.
Referenced by _publish(), DfMpu9250Wrapper(), info(), and ~DfMpu9250Wrapper().
struct DfMpu9250Wrapper::gyro_calibration_s DfMpu9250Wrapper::_gyro_calibration private
Referenced by _publish(), _update_gyro_calibration(), and DfMpu9250Wrapper().
math::LowPassFilter2p DfMpu9250Wrapper::_gyro_filter_x private
Definition at line 164 of file df_mpu9250_wrapper.cpp.
Referenced by _publish(), and DfMpu9250Wrapper().
math::LowPassFilter2p DfMpu9250Wrapper::_gyro_filter_y private
Definition at line 165 of file df_mpu9250_wrapper.cpp.
Referenced by _publish(), and DfMpu9250Wrapper().
math::LowPassFilter2p DfMpu9250Wrapper::_gyro_filter_z private
Definition at line 166 of file df_mpu9250_wrapper.cpp.
Referenced by _publish(), and DfMpu9250Wrapper().
Integrator DfMpu9250Wrapper::_gyro_int private
Definition at line 159 of file df_mpu9250_wrapper.cpp.
Referenced by _publish(), and DfMpu9250Wrapper().
int DfMpu9250Wrapper::_gyro_orb_class_instance private
Definition at line 155 of file df_mpu9250_wrapper.cpp.
Referenced by DfMpu9250Wrapper(), and start().
perf_counter_t DfMpu9250Wrapper::_gyro_range_hit_counter private
Definition at line 172 of file df_mpu9250_wrapper.cpp.
Referenced by _publish(), DfMpu9250Wrapper(), info(), and ~DfMpu9250Wrapper().
orb_advert_t DfMpu9250Wrapper::_gyro_topic private
Definition at line 120 of file df_mpu9250_wrapper.cpp.
Referenced by _publish(), and start().
uint64_t DfMpu9250Wrapper::_last_accel_range_hit_count private
Definition at line 178 of file df_mpu9250_wrapper.cpp.
Referenced by _publish(), and DfMpu9250Wrapper().
hrt_abstime DfMpu9250Wrapper::_last_accel_range_hit_time private
Definition at line 177 of file df_mpu9250_wrapper.cpp.
Referenced by _publish(), and DfMpu9250Wrapper().
struct DfMpu9250Wrapper::mag_calibration_s DfMpu9250Wrapper::_mag_calibration private
Referenced by _publish(), _update_mag_calibration(), and DfMpu9250Wrapper().
bool DfMpu9250Wrapper::_mag_enabled private
Definition at line 180 of file df_mpu9250_wrapper.cpp.
Referenced by _publish(), _update_mag_calibration(), DfMpu9250Wrapper(), info(), start(), and ~DfMpu9250Wrapper().
perf_counter_t DfMpu9250Wrapper::_mag_fifo_overflow_counter private
Definition at line 174 of file df_mpu9250_wrapper.cpp.
Referenced by _publish(), DfMpu9250Wrapper(), info(), and ~DfMpu9250Wrapper().
int DfMpu9250Wrapper::_mag_orb_class_instance private
Definition at line 156 of file df_mpu9250_wrapper.cpp.
Referenced by _publish(), and DfMpu9250Wrapper().
orb_advert_t DfMpu9250Wrapper::_mag_topic private
Definition at line 121 of file df_mpu9250_wrapper.cpp.
Referenced by _publish().
orb_advert_t DfMpu9250Wrapper::_mavlink_log_pub private
Definition at line 123 of file df_mpu9250_wrapper.cpp.
Referenced by _publish().
int DfMpu9250Wrapper::_param_update_sub private
Definition at line 125 of file df_mpu9250_wrapper.cpp.
Referenced by _publish(), and start().
perf_counter_t DfMpu9250Wrapper::_publish_perf private
Definition at line 175 of file df_mpu9250_wrapper.cpp.
Referenced by _publish(), DfMpu9250Wrapper(), info(), and ~DfMpu9250Wrapper().
perf_counter_t DfMpu9250Wrapper::_read_counter private
Definition at line 168 of file df_mpu9250_wrapper.cpp.
Referenced by _publish(), DfMpu9250Wrapper(), info(), and ~DfMpu9250Wrapper().
enum Rotation DfMpu9250Wrapper::_rotation private
Definition at line 182 of file df_mpu9250_wrapper.cpp.
Referenced by _publish(), and DfMpu9250Wrapper().
The documentation for this class was generated from the following file:
src/platforms/posix/drivers/df_mpu9250_wrapper/df_mpu9250_wrapper.cpp