PX4 Firmware: src/drivers/boards/px4fmu-v4/spi.c File Reference
spi.c File Reference
#include <px4_config.h>
#include <stdint.h>
#include <stdbool.h>
#include <debug.h>
#include <unistd.h>
#include <nuttx/spi/spi.h>
#include <arch/board/board.h>
#include <up_arch.h>
#include <chip.h>
#include <stm32.h>
#include "board_config.h"
#include <systemlib/err.h>
Functions
__EXPORT void stm32_spiinitialize (int mask)
__EXPORT void stm32_spi1select (FAR struct spi_dev_s *dev, uint32_t devid, bool selected)
__EXPORT uint8_t stm32_spi1status (FAR struct spi_dev_s *dev, uint32_t devid)
__EXPORT void board_spi_reset (int ms)
Function Documentation
__EXPORT void board_spi_reset (int ms)
disable SPI bus 1 DRDY */
Definition at line 183 of file spi.c.
References GPIO_DRDY_OFF_PORTC_PIN14, GPIO_DRDY_OFF_PORTD_PIN15, GPIO_DRDY_OFF_PORTE_PIN12, GPIO_SPI1_CS_OFF_PORTC_PIN15, GPIO_SPI1_CS_OFF_PORTC_PIN2, GPIO_SPI1_CS_OFF_PORTE_PIN15, GPIO_SPI1_MISO_OFF, GPIO_SPI1_MOSI_OFF, GPIO_SPI1_SCK_OFF, GPIO_VDD_3V3_SENSORS_EN, PX4_SPI_BUS_SENSORS, stm32_spiinitialize(), usleep(), and warnx.
__EXPORT void stm32_spi1select (FAR struct spi_dev_s * dev, uint32_t devid, bool selected)
Definition at line 102 of file spi.c.
References GPIO_SPI1_CS_PORTC_PIN15, GPIO_SPI1_CS_PORTC_PIN2, GPIO_SPI1_CS_PORTE_PIN15, PX4_SPIDEV_BMI, PX4_SPIDEV_BMI055_ACC, PX4_SPIDEV_BMI055_GYR, PX4_SPIDEV_HMC, PX4_SPIDEV_ICM, PX4_SPIDEV_ICM_20602, PX4_SPIDEV_ICM_20608, PX4_SPIDEV_LIS, PX4_SPIDEV_MPU, and PX4_SPIDEV_MPU2.
__EXPORT uint8_t stm32_spi1status (FAR struct spi_dev_s * dev, uint32_t devid)
Definition at line 147 of file spi.c.
References GPIO_SPI2_CS_FRAM, GPIO_SPI2_CS_MS5611, PX4_SPIDEV_BARO, stm32_spi2select(), and stm32_spi2status().
__EXPORT void stm32_spiinitialize (int mask)
Definition at line 75 of file spi.c.
References GPIO_DRDY_PORTC_PIN14, GPIO_DRDY_PORTD_PIN15, GPIO_DRDY_PORTE_PIN12, GPIO_SPI1_CS_PORTC_PIN15, GPIO_SPI1_CS_PORTC_PIN2, GPIO_SPI1_CS_PORTE_PIN15, GPIO_SPI2_CS_FRAM, GPIO_SPI2_CS_MS5611, PX4_SPI_BUS_BARO, PX4_SPI_BUS_RAMTRON, and PX4_SPI_BUS_SENSORS.