PX4 Firmware: src/drivers/driver_framework_wrapper/df_bmp280_wrapper/df_bmp280_wrapper.cpp File Reference
df_bmp280_wrapper.cpp File Reference
Lightweight driver to access the BMP280 of the DriverFramework.
#include <px4_platform_common/px4_config.h>
#include <sys/types.h>
#include <sys/stat.h>
#include <stdint.h>
#include <stddef.h>
#include <stdlib.h>
#include <string.h>
#include <math.h>
#include <unistd.h>
#include <px4_platform_common/getopt.h>
#include <errno.h>
#include <perf/perf_counter.h>
#include <systemlib/err.h>
#include <drivers/drv_hrt.h>
#include <drivers/drv_baro.h>
#include <board_config.h>
#include <bmp280/BMP280.hpp>
#include <DevMgr.hpp>
Classes
class DfBmp280Wrapper
Namespaces
df_bmp280_wrapper
Functions
__EXPORT int df_bmp280_wrapper_main (int argc, char *argv[])
int df_bmp280_wrapper::start ()
Attempt to start driver on all available I2C busses.
int df_bmp280_wrapper::stop ()
Stop the driver.
int df_bmp280_wrapper::info ()
Print a little info about the driver.
void df_bmp280_wrapper::usage ()
Prints info about the driver argument usage.
Variables
DfBmp280Wrapper * df_bmp280_wrapper::g_dev = nullptr
Detailed Description
Lightweight driver to access the BMP280 of the DriverFramework.
Author
Julian Oes julia.nosp@m.n@oe.nosp@m.s.ch
Definition in file df_bmp280_wrapper.cpp.
Function Documentation
df_bmp280_wrapper_main()
int df_bmp280_wrapper_main (int argc, char * argv[])
Definition at line 269 of file df_bmp280_wrapper.cpp.
References df_bmp280_wrapper::info(), df_bmp280_wrapper::start(), df_bmp280_wrapper::stop(), and df_bmp280_wrapper::usage().