PX4 Firmware: src/modules/logger/logger.cpp File Reference
logger.cpp File Reference
#include <px4_config.h>
#include "logger.h"
#include "messages.h"
#include "watchdog.h"
#include <dirent.h>
#include <sys/stat.h>
#include <errno.h>
#include <string.h>
#include <stdlib.h>
#include <time.h>
#include <uORB/uORB.h>
#include <uORB/uORBTopics.h>
#include <uORB/Subscription.hpp>
#include <uORB/topics/log_message.h>
#include <uORB/topics/parameter_update.h>
#include <uORB/topics/vehicle_status.h>
#include <uORB/topics/vehicle_gps_position.h>
#include <uORB/topics/vehicle_command_ack.h>
#include <drivers/drv_hrt.h>
#include <px4_includes.h>
#include <px4_getopt.h>
#include <px4_log.h>
#include <px4_posix.h>
#include <px4_sem.h>
#include <px4_shutdown.h>
#include <px4_tasks.h>
#include <systemlib/mavlink_log.h>
#include <replay/definitions.hpp>
#include <version/version.h>
#include <sys/statfs.h>
Classes
struct timer_callback_data_s
struct px4::logger::perf_callback_data_t
Namespaces
px4
px4::logger
Macros
#define GPS_EPOCH_SECS ((time_t)1234567890ULL)
Functions
static void timer_callback (void *arg)
int logger_main (int argc, char *argv[])
Variables
decltype(statfs::f_bavail) typedef px4_statfs_buf_f_bavail_t
Macro Definition Documentation
#define GPS_EPOCH_SECS ((time_t)1234567890ULL)
Definition at line 76 of file logger.cpp.
Referenced by px4::logger::Logger::get_log_time().
Function Documentation
int logger_main (int argc, char * argv[])
Definition at line 130 of file logger.cpp.
References main(), and PX4_ERR.
static void timer_callback (void * arg) static
Definition at line 103 of file logger.cpp.
References data, px4_sem_getvalue, px4_sem_post, timer_callback_data_s::semaphore, timer_callback_data_s::watchdog_data, timer_callback_data_s::watchdog_triggered, and px4::logger::watchdog_update().
Referenced by px4::logger::Logger::run().
Variable Documentation
decltype(statfs::f_bavail) typedef px4_statfs_buf_f_bavail_t
Definition at line 74 of file logger.cpp.