PX4 Firmware: MPL3115A2 Class Reference
MPL3115A2 Class Reference
Public Member Functions
MPL3115A2 (device::Device *interface, const char *path)
~MPL3115A2 ()
virtual int init ()
Initialise the driver and make it ready for use.
virtual ssize_t read (struct file *filp, char *buffer, size_t buflen)
virtual int ioctl (struct file *filp, int cmd, unsigned long arg)
void print_info ()
Diagnostics - print some basic information about the driver.
Public Member Functions inherited from device::CDev
CDev (const char *name, const char *devname)
Constructor.
virtual ~CDev ()
virtual int open (file_t *filep)
Handle an open of the device.
virtual int close (file_t *filep)
Handle a close of the device.
virtual ssize_t read (file_t *filep, char *buffer, size_t buflen)
Perform a read from the device.
virtual ssize_t write (file_t *filep, const char *buffer, size_t buflen)
Perform a write to the device.
virtual off_t seek (file_t *filep, off_t offset, int whence)
Perform a logical seek operation on the device.
virtual int ioctl (file_t *filep, int cmd, unsigned long arg)
Perform an ioctl operation on the device.
virtual int poll (file_t *filep, px4_pollfd_struct_t *fds, bool setup)
Perform a poll setup/teardown operation.
Public Member Functions inherited from device::Device
virtual ~Device ()=default
Destructor.
virtual int read (unsigned address, void *data, unsigned count)
Read directly from the device.
virtual int write (unsigned address, void *data, unsigned count)
Write directly to the device.
virtual int ioctl (unsigned operation, unsigned &arg)
Perform a device-specific operation.
uint8_t get_device_bus ()
Return the bus ID the device is connected to.
DeviceBusType get_device_bus_type ()
Return the bus type the device is connected to.
uint8_t get_device_address ()
Return the bus address of the device.
void set_device_address (int address)
void set_device_type (uint8_t devtype)
Set the device type.
virtual bool external ()
Protected Member Functions
void start_cycle (unsigned delay_ticks=1)
Initialize the automatic measurement state machine and start it.
void stop_cycle ()
Stop the automatic measurement state machine.
void cycle ()
Perform a poll cycle; collect from the previous measurement and start a new one.
virtual int measure ()
Issue a measurement command for the current state.
virtual int collect ()
Collect the result of the most recent measurement.
Protected Member Functions inherited from device::CDev
virtual pollevent_t poll_state (file_t *filep)
Check the current state of the device for poll events from the perspective of the file.
virtual void poll_notify (pollevent_t events)
Report new poll events.
virtual void poll_notify_one (px4_pollfd_struct_t *fds, pollevent_t events)
Internal implementation of poll_notify.
virtual int open_first (file_t *filep)
Notification of the first open.
virtual int close_last (file_t *filep)
Notification of the last close.
virtual int register_class_devname (const char *class_devname)
Register a class device name, automatically adding device class instance suffix if need be.
virtual int unregister_class_devname (const char *class_devname, unsigned class_instance)
Register a class device name, automatically adding device class instance suffix if need be.
const char * get_devname ()
Get the device name.
void lock ()
Take the driver lock.
void unlock ()
Release the driver lock.
Protected Member Functions inherited from device::Device
Device (const char *name)
Device (DeviceBusType bus_type, uint8_t bus, uint8_t address, uint8_t devtype=0)
Device (const Device &)=delete
Device & operator= (const Device &)=delete
Device (Device &&)=delete
Device & operator= (Device &&)=delete
Static Protected Member Functions
static void cycle_trampoline (void *arg)
Static trampoline from the workq context; because we don't have a generic workq wrapper yet.
Protected Attributes
Device * _interface
struct work_s _work
unsigned _measure_ticks
ringbuffer::RingBuffer * _reports
bool _collect_phase
float _P
float _T
orb_advert_t _baro_topic
int _orb_class_instance
int _class_instance
perf_counter_t _sample_perf
perf_counter_t _measure_perf
perf_counter_t _comms_errors
Protected Attributes inherited from device::CDev
px4_sem_t _lock
lock to protect access to all class members (also for derived classes)
bool _pub_blocked {false}
true if publishing should be blocked
Protected Attributes inherited from device::Device
union DeviceId _device_id
device identifier information
const char * _name
driver name
bool _debug_enabled {false}
if true, debug messages are printed
Additional Inherited Members
Public Types inherited from device::Device
enum DeviceBusType { DeviceBusType_UNKNOWN = 0, DeviceBusType_I2C = 1, DeviceBusType_SPI = 2, DeviceBusType_UAVCAN = 3 }
Device bus types for DEVID.
Static Protected Attributes inherited from device::CDev
static const px4_file_operations_t fops = {}
Pointer to the default cdev file operations table; useful for registering clone devices etc.
Detailed Description
Definition at line 107 of file mpl3115a2.cpp.
Constructor & Destructor Documentation
MPL3115A2::MPL3115A2 (device::Device * interface, const char * path)
Definition at line 201 of file mpl3115a2.cpp.
References device::Device::_device_id, _interface, device::Device::DeviceStructure::address, device::Device::DeviceStructure::bus, device::Device::DeviceStructure::bus_type, device::Device::DeviceId::devid_s, device::Device::DeviceStructure::devtype, and DRV_BARO_DEVTYPE_MPL3115A2.
Referenced by mpl3115a2::start_bus().
MPL3115A2::~MPL3115A2 ()
Definition at line 226 of file mpl3115a2.cpp.
References _class_instance, _comms_errors, _interface, _measure_perf, _reports, _sample_perf, device::CDev::get_devname(), perf_free(), stop_cycle(), and device::CDev::unregister_class_devname().
Member Function Documentation
int MPL3115A2::collect () protected virtual
Collect the result of the most recent measurement.
Definition at line 611 of file mpl3115a2.cpp.
References _baro_topic, _comms_errors, device::Device::_device_id, _interface, _P, device::CDev::_pub_blocked, _reports, _sample_perf, _T, MPL3115A2_data_t::b, baro_report, CTRL_REG1_OST, device::Device::DeviceId::devid, f(), hrt_absolute_time(), MPL3115A2_CTRL_REG1, OK, ORB_ID, orb_publish(), OUT_P_MSB, perf_begin(), perf_count(), perf_end(), perf_event_count(), device::CDev::poll_notify(), MPL3115A2_data_t::pressure, MPL3115A2_data_t::q, and MPL3115A2_data_t::temperature.
Referenced by cycle(), init(), and read().
void MPL3115A2::cycle () protected
Perform a poll cycle; collect from the previous measurement and start a new one.
This is the heart of the measurement state machine. This function alternately starts a measurement, or collects the data from the previous measurement.
When the interval between measurements is greater than the minimum measurement interval, a gap is inserted between collection and measurement to provide the most recent measurement possible at the next interval.
Definition at line 527 of file mpl3115a2.cpp.
References _collect_phase, _interface, collect(), cycle_trampoline(), IOCTL_RESET, measure(), MPL3115A2_CONVERSION_INTERVAL, and start_cycle().
Referenced by cycle_trampoline().
void MPL3115A2::cycle_trampoline (void * arg) static protected
Static trampoline from the workq context; because we don't have a generic workq wrapper yet.
Parameters
arg Instance pointer for the driver that is polling.
Definition at line 519 of file mpl3115a2.cpp.
References cycle().
Referenced by cycle(), and start_cycle().
int MPL3115A2::init () virtual
Initialise the driver and make it ready for use.
Returns
OK if the driver initialized OK, negative errno otherwise;
Reimplemented from device::CDev.
Definition at line 249 of file mpl3115a2.cpp.
References _baro_topic, _class_instance, device::Device::_device_id, _orb_class_instance, _reports, BARO_BASE_DEVICE_PATH, baro_report, collect(), DEVICE_DEBUG, device::Device::DeviceId::devid, device::Device::external(), lis3mdl::init(), measure(), OK, orb_advertise_multi(), ORB_ID, ORB_PRIO_DEFAULT, ORB_PRIO_HIGH, device::CDev::register_class_devname(), usleep(), and warnx.
int MPL3115A2::ioctl (struct file * filp, int cmd, unsigned long arg) virtual
Definition at line 394 of file mpl3115a2.cpp.
References _interface, _measure_ticks, _reports, IOCTL_RESET, MPL3115A2_CONVERSION_INTERVAL, OK, SENSOR_POLLRATE_DEFAULT, SENSOR_POLLRATE_EXTERNAL, SENSOR_POLLRATE_MANUAL, SENSOR_POLLRATE_MAX, SENSORIOCGPOLLRATE, SENSORIOCRESET, SENSORIOCSPOLLRATE, SENSORIOCSQUEUEDEPTH, start_cycle(), and stop_cycle().
Referenced by mpl3115a2::reset(), mpl3115a2::start_bus(), and mpl3115a2::test().
int MPL3115A2::measure () protected virtual
Issue a measurement command for the current state.
Returns
OK if the measurement command was successful.
Definition at line 589 of file mpl3115a2.cpp.
References _comms_errors, _interface, _measure_perf, IOCTL_MEASURE, MPL3115A2_CTRL_REG1, MPL3115A2_CTRL_TRIGGER, perf_begin(), perf_count(), perf_end(), and PX4_OK.
Referenced by cycle(), init(), and read().
void MPL3115A2::print_info ()
Diagnostics - print some basic information about the driver.
Definition at line 677 of file mpl3115a2.cpp.
References _comms_errors, _measure_ticks, _reports, _sample_perf, and perf_print_counter().
Referenced by mpl3115a2::info().
ssize_t MPL3115A2::read (struct file * filp, char * buffer, size_t buflen) virtual
Definition at line 330 of file mpl3115a2.cpp.
References _measure_ticks, _reports, baro_report, collect(), measure(), OK, and usleep().
Referenced by mpl3115a2::test().
void MPL3115A2::start_cycle (unsigned delay_ticks = 1) protected
Initialize the automatic measurement state machine and start it.
Parameters
delay_ticks the number of queue ticks before executing the next cycle
Note
This function is called at open and error time. It might make sense to make it more aggressive about resetting the bus in case of errors.
Definition at line 501 of file mpl3115a2.cpp.
References _collect_phase, _reports, and cycle_trampoline().
Referenced by cycle(), and ioctl().
void MPL3115A2::stop_cycle () protected
Stop the automatic measurement state machine.
Definition at line 513 of file mpl3115a2.cpp.
Referenced by ioctl(), and ~MPL3115A2().
Member Data Documentation
orb_advert_t MPL3115A2::_baro_topic protected
Definition at line 136 of file mpl3115a2.cpp.
Referenced by collect(), and init().
int MPL3115A2::_class_instance protected
Definition at line 138 of file mpl3115a2.cpp.
Referenced by init(), and ~MPL3115A2().
bool MPL3115A2::_collect_phase protected
Definition at line 130 of file mpl3115a2.cpp.
Referenced by cycle(), and start_cycle().
perf_counter_t MPL3115A2::_comms_errors protected
Definition at line 142 of file mpl3115a2.cpp.
Referenced by collect(), measure(), print_info(), and ~MPL3115A2().
Device* MPL3115A2::_interface protected
Definition at line 124 of file mpl3115a2.cpp.
Referenced by collect(), cycle(), ioctl(), measure(), MPL3115A2(), and ~MPL3115A2().
perf_counter_t MPL3115A2::_measure_perf protected
Definition at line 141 of file mpl3115a2.cpp.
Referenced by measure(), and ~MPL3115A2().
unsigned MPL3115A2::_measure_ticks protected
Definition at line 127 of file mpl3115a2.cpp.
Referenced by ioctl(), print_info(), and read().
int MPL3115A2::_orb_class_instance protected
Definition at line 137 of file mpl3115a2.cpp.
Referenced by init().
float MPL3115A2::_P protected
Definition at line 133 of file mpl3115a2.cpp.
Referenced by collect().
ringbuffer::RingBuffer* MPL3115A2::_reports protected
Definition at line 129 of file mpl3115a2.cpp.
Referenced by collect(), init(), ioctl(), print_info(), read(), start_cycle(), and ~MPL3115A2().
perf_counter_t MPL3115A2::_sample_perf protected
Definition at line 140 of file mpl3115a2.cpp.
Referenced by collect(), print_info(), and ~MPL3115A2().
float MPL3115A2::_T protected
Definition at line 134 of file mpl3115a2.cpp.
Referenced by collect().
struct work_s MPL3115A2::_work protected
Definition at line 126 of file mpl3115a2.cpp.
The documentation for this class was generated from the following file:
src/drivers/barometer/mpl3115a2/mpl3115a2.cpp