PX4 Firmware: src/modules/micrortps_bridge/micrortps_client/microRTPS_client_main.cpp File Reference
microRTPS_client_main.cpp File Reference
#include "microRTPS_transport.h"
#include "microRTPS_client.h"
#include <cinttypes>
#include <cstdio>
#include <cstdlib>
#include <ctime>
#include <termios.h>
#include <px4_config.h>
#include <px4_getopt.h>
#include <px4_module.h>
#include <px4_posix.h>
#include <px4_tasks.h>
#include <px4_time.h>
Functions
__EXPORT int micrortps_client_main (int argc, char *argv[])
baudtype getbaudrate (const char *valstr)
static void usage (const char *name)
static int parse_options (int argc, char *argv[])
static int micrortps_start (int argc, char *argv[])
Variables
static int _rtps_task = -1
bool _should_exit_task = false
Transport_node * transport_node = nullptr
struct options _options
const baudtype baudlist []
Function Documentation
baudtype getbaudrate (const char * valstr)
Definition at line 91 of file microRTPS_client_main.cpp.
References baudlist.
Referenced by parse_options().
__EXPORT int micrortps_client_main (int argc, char * argv[])
Definition at line 215 of file microRTPS_client_main.cpp.
References _rtps_task, _should_exit_task, micrortps_start(), PX4_INFO, px4_task_spawn_cmd(), PX4_WARN, SCHED_DEFAULT, transport_node, and usage().
static int micrortps_start (int argc, char * argv[]) static
Definition at line 149 of file microRTPS_client_main.cpp.
References _options, _rtps_task, options::baudrate, baudtype::code, options::device, micrortps_start_topics(), parse_options(), options::poll_ms, px4_clock_gettime, PX4_INFO, options::recv_port, options::send_port, options::sleep_ms, options::transport, transport_node, options::UART, options::UDP, and baudtype::val.
Referenced by micrortps_client_main().
static int parse_options (int argc, char * argv[]) static
Definition at line 102 of file microRTPS_client_main.cpp.
References _options, options::baudrate, options::device, getbaudrate(), options::loops, options::poll_ms, PX4_ERR, px4_getopt(), options::recv_port, options::send_port, options::sleep_ms, options::transport, options::UART, options::UDP, options::update_time_ms, and usage().
Referenced by micrortps_start().
static void usage (const char * name) static
Definition at line 70 of file microRTPS_client_main.cpp.
References PRINT_MODULE_USAGE_COMMAND, PRINT_MODULE_USAGE_NAME(), PRINT_MODULE_USAGE_PARAM_INT(), and PRINT_MODULE_USAGE_PARAM_STRING().
Referenced by micrortps_client_main(), and parse_options().
Variable Documentation
struct options _options
Definition at line 54 of file microRTPS_client_main.cpp.
Referenced by micrortps_start(), and parse_options().
int _rtps_task = -1 static
Definition at line 51 of file microRTPS_client_main.cpp.
Referenced by micrortps_client_main(), and micrortps_start().
bool _should_exit_task = false
Definition at line 52 of file microRTPS_client_main.cpp.
Referenced by micrortps_client_main().
const baudtype baudlist[]
Initial value:
= {
    [0] = {.code = B0, .val = 0},
    [1] = {.code = B9600, .val = 9600},
    [2] = {.code = B19200, .val = 19200},
    [3] = {.code = B38400, .val = 38400},
    [4] = {.code = B57600, .val = 57600},
    [5] = {.code = B115200, .val = 115200},
    [6] = {.code = B230400, .val = 230400},
    [7] = {.code = B460800, .val = 460800},
    [8] = {.code = B921600, .val = 921600}
}
Definition at line 56 of file microRTPS_client_main.cpp.
Referenced by getbaudrate().
Transport_node* transport_node = nullptr
Definition at line 53 of file microRTPS_client_main.cpp.
Referenced by micrortps_client_main(), and micrortps_start().