PX4 Firmware: control::BlockDelay< Type, M, N, LEN > Class Template Reference
control::BlockDelay< Type, M, N, LEN > Class Template Reference
#include <BlockDelay.hpp>
Public Member Functions
BlockDelay (SuperBlock *parent, const char *name)
virtual ~BlockDelay ()
matrix::Matrix< Type, M, N > update (const matrix::Matrix< Type, M, N > &u)
matrix::Matrix< Type, M, N > get (size_t delay)
Public Member Functions inherited from control::Block
Block (SuperBlock *parent, const char *name)
virtual ~Block ()=default
Block (const Block &)=delete
Block & operator= (const Block &)=delete
Block (Block &&)=delete
Block & operator= (Block &&)=delete
void getName (char *name, size_t n)
virtual void updateParams ()
virtual void updateSubscriptions ()
virtual void updatePublications ()
virtual void setDt (float dt)
float getDt ()
Public Member Functions inherited from ListNode< Block * >
ListNode ()
ListNode (const ListNode &)=delete
ListNode (ListNode &&)=delete
virtual ~ListNode ()=default
ListNode & operator= (const ListNode &)=delete
ListNode & operator= (ListNode &&)=delete
void setSibling (Block *sibling)
const Block * getSibling ()
Private Attributes
matrix::Matrix< Type, M, N > _h [LEN]
size_t _index
int _delay
Additional Inherited Members
Protected Member Functions inherited from control::Block
virtual void updateParamsSubclass ()
SuperBlock * getParent ()
List< uORB::SubscriptionNode * > & getSubscriptions ()
List< uORB::PublicationNode * > & getPublications ()
List< BlockParamBase * > & getParams ()
Protected Attributes inherited from control::Block
const char * _name
SuperBlock * _parent
float _dt {0.0f}
List< uORB::SubscriptionNode * > _subscriptions
List< uORB::PublicationNode * > _publications
List< BlockParamBase * > _params
Protected Attributes inherited from ListNode< Block * >
Block * _sibling
Detailed Description
template<class Type, size_t M, size_t N, size_t LEN>
class control::BlockDelay< Type, M, N, LEN >
Definition at line 59 of file BlockDelay.hpp.
Constructor & Destructor Documentation
template<class Type, size_t M, size_t N, size_t LEN> control::BlockDelay< Type, M, N, LEN >::BlockDelay (SuperBlock * parent, const char * name) inline
Definition at line 63 of file BlockDelay.hpp.
template<class Type, size_t M, size_t N, size_t LEN> virtual control::BlockDelay< Type, M, N, LEN >::~BlockDelay () inline virtual
Definition at line 69 of file BlockDelay.hpp.
Member Function Documentation
template<class Type, size_t M, size_t N, size_t LEN> matrix::Matrix<Type, M, N> control::BlockDelay< Type, M, N, LEN >::get (size_t delay) inline
Definition at line 99 of file BlockDelay.hpp.
Referenced by BlockLocalPositionEstimator::getDelayPeriods(), BlockLocalPositionEstimator::gpsCorrect(), and BlockLocalPositionEstimator::visionCorrect().
template<class Type, size_t M, size_t N, size_t LEN> matrix::Matrix<Type, M, N> control::BlockDelay< Type, M, N, LEN >::update (const matrix::Matrix< Type, M, N > & u) inline
Definition at line 70 of file BlockDelay.hpp.
Referenced by control::blockDelayTest(), blockDelayTest(), and BlockLocalPositionEstimator::update().
Member Data Documentation
template<class Type, size_t M, size_t N, size_t LEN> int control::BlockDelay< Type, M, N, LEN >::_delay private
Definition at line 111 of file BlockDelay.hpp.
template<class Type, size_t M, size_t N, size_t LEN> matrix::Matrix<Type, M, N> control::BlockDelay< Type, M, N, LEN >::_h[LEN] private
Definition at line 109 of file BlockDelay.hpp.
template<class Type, size_t M, size_t N, size_t LEN> size_t control::BlockDelay< Type, M, N, LEN >::_index private
Definition at line 110 of file BlockDelay.hpp.
The documentation for this class was generated from the following file:
src/lib/controllib/BlockDelay.hpp