PX4 Firmware: src/modules/commander/Commander.cpp File Reference
Commander.cpp File Reference
#include "Commander.hpp"
#include "accelerometer_calibration.h"
#include "airspeed_calibration.h"
#include "arm_auth.h"
#include "baro_calibration.h"
#include "calibration_routines.h"
#include "commander_helper.h"
#include "esc_calibration.h"
#include "gyro_calibration.h"
#include "mag_calibration.h"
#include "PreflightCheck.h"
#include "px4_custom_mode.h"
#include "rc_calibration.h"
#include "state_machine_helper.h"
#include "health_flag_helper.h"
#include <dataman/dataman.h>
#include <drivers/drv_hrt.h>
#include <drivers/drv_tone_alarm.h>
#include <lib/ecl/geo/geo.h>
#include <mathlib/mathlib.h>
#include <navigator/navigation.h>
#include <px4_config.h>
#include <px4_defines.h>
#include <px4_posix.h>
#include <px4_shutdown.h>
#include <px4_tasks.h>
#include <px4_time.h>
#include <circuit_breaker/circuit_breaker.h>
#include <systemlib/err.h>
#include <systemlib/hysteresis/hysteresis.h>
#include <systemlib/mavlink_log.h>
#include <parameters/param.h>
#include <cmath>
#include <cfloat>
#include <cstring>
#include <uORB/topics/actuator_armed.h>
#include <uORB/topics/actuator_controls.h>
#include <uORB/topics/battery_status.h>
#include <uORB/topics/cpuload.h>
#include <uORB/topics/geofence_result.h>
#include <uORB/topics/home_position.h>
#include <uORB/topics/manual_control_setpoint.h>
#include <uORB/topics/mavlink_log.h>
#include <uORB/topics/mission.h>
#include <uORB/topics/mission_result.h>
#include <uORB/topics/offboard_control_mode.h>
#include <uORB/topics/parameter_update.h>
#include <uORB/topics/power_button_state.h>
#include <uORB/topics/safety.h>
#include <uORB/topics/subsystem_info.h>
#include <uORB/topics/system_power.h>
#include <uORB/topics/telemetry_status.h>
#include <uORB/topics/vehicle_command.h>
#include <uORB/topics/vehicle_command_ack.h>
#include <uORB/topics/vehicle_global_position.h>
#include <uORB/topics/vehicle_land_detected.h>
#include <uORB/topics/vehicle_local_position.h>
#include <uORB/topics/vehicle_status_flags.h>
#include <uORB/topics/vtol_vehicle_status.h>
#include <uORB/uORB.h>
Macros
#define COMMANDER_MONITORING_LOOPSPERMSEC (1/(COMMANDER_MONITORING_INTERVAL/1000.0f))
Typedefs
typedef enum VEHICLE_MODE_FLAG VEHICLE_MODE_FLAG
Enumerations
enum VEHICLE_MODE_FLAG {
VEHICLE_MODE_FLAG_CUSTOM_MODE_ENABLED =1, VEHICLE_MODE_FLAG_TEST_ENABLED =2, VEHICLE_MODE_FLAG_AUTO_ENABLED =4, VEHICLE_MODE_FLAG_GUIDED_ENABLED =8,
VEHICLE_MODE_FLAG_STABILIZE_ENABLED =16, VEHICLE_MODE_FLAG_HIL_ENABLED =32, VEHICLE_MODE_FLAG_MANUAL_INPUT_ENABLED =64, VEHICLE_MODE_FLAG_SAFETY_ARMED =128,
VEHICLE_MODE_FLAG_ENUM_END =129
}
Functions
__EXPORT int commander_main (int argc, char *argv[])
The daemon app only briefly exists to start the background job.
void usage (const char *reason)
Print the correct usage.
void control_status_leds (vehicle_status_s *status_local, const actuator_armed_s *actuator_armed, bool changed, battery_status_s *battery_local, const cpuload_s *cpuload_local)
void get_circuit_breaker_params ()
void set_control_mode ()
bool stabilization_required ()
void print_reject_mode (const char *msg)
void print_reject_arm (const char *msg)
void print_status ()
transition_result_t arm_disarm (bool arm, orb_advert_t *mavlink_log_pub, const char *armedBy)
void * commander_low_prio_loop (void *arg)
Loop that runs at a lower rate and priority for calibration and parameter tasks.
static void answer_command (const vehicle_command_s &cmd, unsigned result, orb_advert_t &command_ack_pub)
static int power_button_state_notification_cb (board_power_button_state_notification_e request)
static bool send_vehicle_command (uint16_t cmd, float param1=NAN, float param2=NAN)
Variables
static constexpr uint64_t COMMANDER_MONITORING_INTERVAL = 10_ms
static constexpr float STICK_ON_OFF_LIMIT = 0.9f
static constexpr uint64_t OFFBOARD_TIMEOUT = 500_ms
static constexpr uint64_t HOTPLUG_SENS_TIMEOUT = 8_s
wait for hotplug sensors to come online for upto 8 seconds
static constexpr uint64_t PRINT_MODE_REJECT_INTERVAL = 500_ms
static constexpr uint64_t INAIR_RESTART_HOLDOFF_INTERVAL = 500_ms
static orb_advert_t mavlink_log_pub = nullptr
static orb_advert_t power_button_state_pub = nullptr
static volatile bool thread_should_exit = false
daemon exit flag
static volatile bool thread_running = false
daemon status flag
static hrt_abstime commander_boot_timestamp = 0
static unsigned int leds_counter
static uint64_t last_print_mode_reject_time = 0
static systemlib::Hysteresis auto_disarm_hysteresis (false)
static float min_stick_change = 0.25f
static struct vehicle_status_s status = {}
static struct battery_status_s battery = {}
static struct actuator_armed_s armed = {}
static struct safety_s safety = {}
static struct vehicle_control_mode_s control_mode = {}
static struct offboard_control_mode_s offboard_control_mode = {}
static struct home_position_s _home = {}
static int32_t _flight_mode_slots [manual_control_setpoint_s::MODE_SLOT_MAX]
static struct commander_state_s internal_state = {}
static uint8_t main_state_before_rtl = commander_state_s::MAIN_STATE_MAX
static manual_control_setpoint_s sp_man = {}
the current manual control setpoint
static manual_control_setpoint_s _last_sp_man = {}
the manual control setpoint valid at the last mode switch
static uint8_t _last_sp_man_arm_switch = 0
static struct vtol_vehicle_status_s vtol_status = {}
static struct cpuload_s cpuload = {}
static bool warning_action_on = false
static bool last_overload = false
static struct vehicle_status_flags_s status_flags = {}
static uint64_t rc_signal_lost_timestamp
static uint8_t arm_requirements = ARM_REQ_NONE
static bool _last_condition_global_position_valid = false
static struct vehicle_land_detected_s land_detector = {}
static float _eph_threshold_adj = INFINITY
maximum allowable horizontal position uncertainty after adjustment for flight condition
static bool _skip_pos_accuracy_check = false
static orb_advert_t status_pub
Macro Definition Documentation
#define COMMANDER_MONITORING_LOOPSPERMSEC (1/(COMMANDER_MONITORING_INTERVAL/1000.0f))
Definition at line 127 of file Commander.cpp.
Referenced by Commander::run().
Typedef Documentation
typedef enum VEHICLE_MODE_FLAG VEHICLE_MODE_FLAG
Enumeration Type Documentation
enum VEHICLE_MODE_FLAG
Enumerator
VEHICLE_MODE_FLAG_CUSTOM_MODE_ENABLED
VEHICLE_MODE_FLAG_TEST_ENABLED
VEHICLE_MODE_FLAG_AUTO_ENABLED
VEHICLE_MODE_FLAG_GUIDED_ENABLED
VEHICLE_MODE_FLAG_STABILIZE_ENABLED
VEHICLE_MODE_FLAG_HIL_ENABLED
VEHICLE_MODE_FLAG_MANUAL_INPUT_ENABLED
VEHICLE_MODE_FLAG_SAFETY_ARMED
VEHICLE_MODE_FLAG_ENUM_END
Definition at line 112 of file Commander.cpp.
Function Documentation
void answer_command (const vehicle_command_s & cmd, unsigned result, orb_advert_t & command_ack_pub) static
Definition at line 3518 of file Commander.cpp.
References vehicle_command_ack_s::command, vehicle_command_s::command, hrt_absolute_time(), orb_advertise_queue(), ORB_ID, orb_publish(), vehicle_command_ack_s::result, vehicle_command_s::source_component, vehicle_command_s::source_system, vehicle_command_ack_s::target_component, vehicle_command_ack_s::target_system, vehicle_command_ack_s::timestamp, tune_negative(), and tune_positive().
Referenced by commander_low_prio_loop(), and Commander::handle_command().
transition_result_t arm_disarm (bool arm, orb_advert_t * mavlink_log_pub, const char * armedBy)
Definition at line 518 of file Commander.cpp.
References arm_requirements, arming_state_transition(), commander_boot_timestamp, hrt_elapsed_time(), mavlink_log_info, TRANSITION_CHANGED, TRANSITION_DENIED, TRANSITION_NOT_CHANGED, and tune_negative().
Referenced by commander_main(), Commander::handle_command(), and Commander::run().
void * commander_low_prio_loop (void * arg)
Loop that runs at a lower rate and priority for calibration and parameter tasks.
Definition at line 3561 of file Commander.cpp.
References answer_command(), arm_requirements, arming_state_transition(), vehicle_command_s::command, commander_boot_timestamp, vehicle_status_flags_s::condition_calibration_enabled, do_accel_calibration(), do_airspeed_calibration(), do_esc_calibration(), do_gyro_calibration(), do_level_calibration(), do_mag_calibration(), do_trim_calibration(), hrt_elapsed_time(), is_safe(), mavlink_log_critical, mavlink_log_info, mavlink_log_pub, OK, orb_advert_t, orb_copy(), ORB_ID, orb_subscribe(), vehicle_command_s::param1, vehicle_command_s::param2, vehicle_command_s::param3, vehicle_command_s::param4, vehicle_command_s::param5, vehicle_command_s::param6, vehicle_command_s::param7, param_load_default(), param_reset_all(), param_save_default(), Commander::preflight_check(), px4_close(), PX4_ERROR, px4_poll(), px4_shutdown_request(), vehicle_status_flags_s::rc_input_blocked, thread_should_exit, TRANSITION_DENIED, tune_negative(), tune_positive(), usleep(), and warn.
Referenced by Commander::run().
int commander_main (int argc, char * argv[])
The daemon app only briefly exists to start the background job.
The stack size assigned in the Makefile does only apply to this management task.
The actual stack size should be set in the call to task_create().
Definition at line 285 of file Commander.cpp.
References arm_disarm(), arm_requirements, commander_boot_timestamp, vehicle_status_flags_s::condition_local_position_valid, do_accel_calibration(), do_airspeed_calibration(), do_esc_calibration(), do_gyro_calibration(), do_level_calibration(), do_mag_calibration(), f(), hrt_elapsed_time(), vehicle_status_s::is_rotary_wing, main(), main_state_transition(), mavlink_log_pub, OK, prearm_check(), Commander::preflight_check(), print_status(), PX4_ERR, PX4_INFO, PX4_WARN, send_vehicle_command(), thread_running, thread_should_exit, TRANSITION_CHANGED, TRANSITION_DENIED, usage(), and usleep().
void control_status_leds (vehicle_status_s * status_local, const actuator_armed_s * actuator_armed, bool changed, battery_status_s * battery_local, const cpuload_s * cpuload_local)
Definition at line 2670 of file Commander.cpp.
References actuator_armed_s::armed, vehicle_status_s::arming_state, vehicle_status_flags_s::condition_global_position_valid, vehicle_status_flags_s::condition_home_position_valid, vehicle_status_flags_s::condition_system_hotplug_timeout, vehicle_status_flags_s::condition_system_sensors_initialized, vehicle_status_s::failsafe, hrt_absolute_time(), hrt_abstime, hrt_elapsed_time(), last_overload, LED_AMBER, LED_BLUE, LED_GREEN, led_off(), led_on(), led_toggle(), leds_counter, cpuload_s::load, cpuload_s::ram_usage, actuator_armed_s::ready_to_arm, rgbled_set_color_and_mode(), and battery_status_s::warning.
Referenced by Commander::run().
void get_circuit_breaker_params ()
Definition at line 2646 of file Commander.cpp.
References CBRK_AIRSPD_CHK_KEY, CBRK_ENGINEFAIL_KEY, CBRK_FLIGHTTERM_KEY, CBRK_GPSFAIL_KEY, CBRK_SUPPLY_CHK_KEY, CBRK_USB_CHK_KEY, CBRK_VELPOSERR_KEY, circuit_breaker_enabled(), vehicle_status_flags_s::circuit_breaker_engaged_airspd_check, vehicle_status_flags_s::circuit_breaker_engaged_enginefailure_check, vehicle_status_flags_s::circuit_breaker_engaged_gpsfailure_check, vehicle_status_flags_s::circuit_breaker_engaged_posfailure_check, vehicle_status_flags_s::circuit_breaker_engaged_power_check, vehicle_status_flags_s::circuit_breaker_engaged_usb_check, and vehicle_status_flags_s::circuit_breaker_flight_termination_disabled.
Referenced by Commander::run().
static int power_button_state_notification_cb (board_power_button_state_notification_e request) static
Definition at line 230 of file Commander.cpp.
References power_button_state_s::event, hrt_absolute_time(), ORB_ID, orb_publish(), power_button_state_pub, PWR_BUTTON_DOWN, PWR_BUTTON_IDEL, PWR_BUTTON_REQUEST_SHUT_DOWN, PWR_BUTTON_RESPONSE_SHUT_DOWN_PENDING, PWR_BUTTON_UP, PX4_ERR, and power_button_state_s::timestamp.
Referenced by Commander::run().
void print_reject_arm (const char * msg)
Definition at line 3507 of file Commander.cpp.
References hrt_absolute_time(), hrt_abstime, last_print_mode_reject_time, mavlink_log_critical, mavlink_log_pub, PRINT_MODE_REJECT_INTERVAL, and tune_negative().
Referenced by Commander::run().
void print_reject_mode (const char * msg)
Definition at line 3492 of file Commander.cpp.
References actuator_armed_s::armed, hrt_absolute_time(), hrt_abstime, last_print_mode_reject_time, mavlink_log_critical, mavlink_log_pub, PRINT_MODE_REJECT_INTERVAL, and tune_negative().
Referenced by Commander::handle_command(), and Commander::set_main_state_rc().
void print_status ()
Definition at line 503 of file Commander.cpp.
References home_position_s::alt, vehicle_status_s::arming_state, arming_state_names, vehicle_status_flags_s::condition_power_input_valid, vehicle_status_s::data_link_lost, vehicle_status_s::high_latency_data_link_active, vehicle_status_s::is_rotary_wing, home_position_s::lat, home_position_s::lon, commander_state_s::main_state, vehicle_status_s::nav_state, PX4_INFO, vehicle_status_flags_s::usb_connected, home_position_s::x, home_position_s::y, home_position_s::yaw, and home_position_s::z.
Referenced by commander_main(), EstimatorInterface::get_baro_sample_delayed(), and Ekf2::set_replay_mode().
static bool send_vehicle_command (uint16_t cmd, float param1 = NAN, float param2 = NAN) static
Definition at line 265 of file Commander.cpp.
References vehicle_command_s::command, vehicle_status_s::component_id, hrt_absolute_time(), orb_advert_t, orb_advertise_queue(), ORB_ID, vehicle_command_s::param1, vehicle_command_s::param2, vehicle_command_s::param3, vehicle_command_s::param4, vehicle_command_s::param5, vehicle_command_s::param6, vehicle_command_s::param7, vehicle_status_s::system_id, vehicle_command_s::target_component, vehicle_command_s::target_system, and vehicle_command_s::timestamp.
Referenced by commander_main().
void set_control_mode ()
Definition at line 3273 of file Commander.cpp.
References actuator_armed_s::armed, vehicle_control_mode_s::flag_armed, vehicle_control_mode_s::flag_control_acceleration_enabled, vehicle_control_mode_s::flag_control_altitude_enabled, vehicle_control_mode_s::flag_control_attitude_enabled, vehicle_control_mode_s::flag_control_auto_enabled, vehicle_control_mode_s::flag_control_climb_rate_enabled, vehicle_control_mode_s::flag_control_manual_enabled, vehicle_control_mode_s::flag_control_offboard_enabled, vehicle_control_mode_s::flag_control_position_enabled, vehicle_control_mode_s::flag_control_rates_enabled, vehicle_control_mode_s::flag_control_rattitude_enabled, vehicle_control_mode_s::flag_control_termination_enabled, vehicle_control_mode_s::flag_control_velocity_enabled, vehicle_control_mode_s::flag_external_manual_override_ok, vehicle_control_mode_s::flag_system_hil_enabled, vehicle_status_s::hil_state, offboard_control_mode_s::ignore_acceleration_force, offboard_control_mode_s::ignore_attitude, offboard_control_mode_s::ignore_bodyrate, offboard_control_mode_s::ignore_position, offboard_control_mode_s::ignore_velocity, vehicle_status_s::in_transition_mode, vehicle_status_s::is_rotary_wing, vehicle_status_s::is_vtol, vehicle_status_s::nav_state, and stabilization_required().
Referenced by Commander::run().
bool stabilization_required ()
Definition at line 3483 of file Commander.cpp.
References vehicle_status_s::is_rotary_wing, vehicle_status_s::vtol_fw_permanent_stab, and vtol_vehicle_status_s::vtol_in_trans_mode.
Referenced by set_control_mode().
static __END_DECLS void usage (const char * reason)
Print the correct usage.
Definition at line 494 of file Commander.cpp.
References PX4_INFO.
Referenced by commander_main(), and px4flow::start().
Variable Documentation
float _eph_threshold_adj = INFINITY static
maximum allowable horizontal position uncertainty after adjustment for flight condition
Definition at line 186 of file Commander.cpp.
Referenced by Commander::estimator_check(), and Commander::reset_posvel_validity().
int32_t _flight_mode_slots[manual_control_setpoint_s::MODE_SLOT_MAX] static
Definition at line 161 of file Commander.cpp.
Referenced by Commander::run(), and Commander::set_main_state_rc().
struct home_position_s _home = {} static
Definition at line 160 of file Commander.cpp.
bool _last_condition_global_position_valid = false static
Definition at line 182 of file Commander.cpp.
Referenced by Commander::estimator_check(), Commander::run(), and Commander::set_main_state_rc().
manual_control_setpoint_s _last_sp_man = {} static
the manual control setpoint valid at the last mode switch
Definition at line 167 of file Commander.cpp.
uint8_t _last_sp_man_arm_switch = 0 static
Definition at line 168 of file Commander.cpp.
Referenced by Commander::run().
bool _skip_pos_accuracy_check = false static
Definition at line 187 of file Commander.cpp.
Referenced by Commander::estimator_check(), and Commander::reset_posvel_validity().
uint8_t arm_requirements = ARM_REQ_NONE static
Definition at line 180 of file Commander.cpp.
Referenced by arm_disarm(), commander_low_prio_loop(), commander_main(), Commander::preflight_check(), and Commander::run().
struct actuator_armed_s armed = {} static
Definition at line 156 of file Commander.cpp.
Referenced by StateMachineHelperTest::armingStateTransitionTest(), Battery::full_cell_voltage(), Simulator::handle_message(), PX4IO::io_set_arming_state(), Simulator::pack_actuator_message(), px4::logger::Logger::run(), and MavlinkStreamVFRHUD::send().
systemlib::Hysteresis auto_disarm_hysteresis(false) static
Referenced by Commander::run().
struct battery_status_s battery = {} static
Definition at line 155 of file Commander.cpp.
Referenced by MavlinkStreamHighLatency2::update_battery_status().
hrt_abstime commander_boot_timestamp = 0 static
Definition at line 144 of file Commander.cpp.
Referenced by arm_disarm(), commander_low_prio_loop(), commander_main(), Commander::handle_command(), Commander::poll_telemetry_status(), Commander::preflight_check(), and Commander::run().
constexpr uint64_t COMMANDER_MONITORING_INTERVAL = 10_ms static
Definition at line 126 of file Commander.cpp.
Referenced by Commander::run().
struct vehicle_control_mode_s control_mode = {} static
Definition at line 158 of file Commander.cpp.
Referenced by PX4IO::io_set_arming_state(), MavlinkStreamPositionTargetGlobalInt::send(), and MavlinkStreamExtendedSysState::send().
struct cpuload_s cpuload = {} static
Definition at line 171 of file Commander.cpp.
Referenced by load_mon::LoadMon::_compute(), events::status::StatusDisplay::check_for_updates(), MavlinkStreamSysStatus::send(), and events::SubscriberHandler::subscribe().
constexpr uint64_t HOTPLUG_SENS_TIMEOUT = 8_s static
wait for hotplug sensors to come online for upto 8 seconds
Definition at line 132 of file Commander.cpp.
Referenced by Commander::run().
constexpr uint64_t INAIR_RESTART_HOLDOFF_INTERVAL = 500_ms static
Definition at line 134 of file Commander.cpp.
Referenced by Commander::handle_command(), and Commander::run().
struct commander_state_s internal_state = {} static
Definition at line 162 of file Commander.cpp.
struct vehicle_land_detected_s land_detector = {} static
Definition at line 184 of file Commander.cpp.
bool last_overload = false static
Definition at line 174 of file Commander.cpp.
Referenced by control_status_leds().
uint64_t last_print_mode_reject_time = 0 static
Definition at line 148 of file Commander.cpp.
Referenced by print_reject_arm(), and print_reject_mode().
unsigned int leds_counter static
Definition at line 146 of file Commander.cpp.
Referenced by control_status_leds().
uint8_t main_state_before_rtl = commander_state_s::MAIN_STATE_MAX static
Definition at line 164 of file Commander.cpp.
Referenced by Commander::run().
orb_advert_t mavlink_log_pub = nullptr static
Definition at line 137 of file Commander.cpp.
Referenced by commander_low_prio_loop(), commander_main(), Commander::data_link_checks(), Commander::estimator_check(), Commander::handle_command(), Commander::poll_telemetry_status(), Commander::preflight_check(), print_reject_arm(), print_reject_mode(), and Commander::run().
float min_stick_change = 0.25f static
Definition at line 152 of file Commander.cpp.
Referenced by Commander::run().
struct offboard_control_mode_s offboard_control_mode = {} static
Definition at line 159 of file Commander.cpp.
Referenced by MavlinkReceiver::handle_message_set_attitude_target(), px4::Mavlink::handle_msg_set_position_target_local_ned(), and Commander::~Commander().
constexpr uint64_t OFFBOARD_TIMEOUT = 500_ms static
Definition at line 131 of file Commander.cpp.
Referenced by Commander::run().
orb_advert_t power_button_state_pub = nullptr static
Definition at line 138 of file Commander.cpp.
Referenced by power_button_state_notification_cb(), and Commander::run().
constexpr uint64_t PRINT_MODE_REJECT_INTERVAL = 500_ms static
Definition at line 133 of file Commander.cpp.
Referenced by print_reject_arm(), and print_reject_mode().
uint64_t rc_signal_lost_timestamp static
Definition at line 178 of file Commander.cpp.
Referenced by Commander::run().
struct safety_s safety = {} static
Definition at line 157 of file Commander.cpp.
Referenced by PX4FMU::cycle(), PX4FMU::init(), and BlinkM::led().
manual_control_setpoint_s sp_man = {} static
the current manual control setpoint
Definition at line 166 of file Commander.cpp.
Referenced by Commander::set_main_state_rc().
struct vehicle_status_s status = {} static
Definition at line 154 of file Commander.cpp.
Referenced by ACCELSIM::_measure(), board_app_initialize(), MEASAirspeed::collect(), MEASAirspeedSim::collect(), BAROSIM::collect(), LSM303AGR::collect(), BMM150::collect(), LPS25H::collect(), GPSDriverAshtech::configure(), Preflight::ekf2Check(), F_write_byte(), free_getprogmeminfo(), frsky_telemetry_thread_main(), Battery::full_cell_voltage(), EstimatorInterface::get_filter_fault_status(), Ekf::get_quat_reset(), uORB::FastRpcChannel::GetInstance(), PX4IO::io_handle_status(), ACCELSIM::mag_measure(), LSM303D::mag_measure(), FXOS8701CQ::measure(), L3GD20::measure(), FXAS21002C::measure(), LSM303D::measure(), BMI160::measure(), MK::mk_servo_arm(), GPSDriverUBX::payloadRxDone(), pwmin_tim_isr(), IRLOCK::read_device_block(), IRLOCK::read_device_word(), RoboClaw::readEncoder(), MicroBenchORB::MicroBenchORB::reset(), Ekf2::run(), MavlinkStreamSysStatus::send(), MavlinkStreamHILActuatorControls::send(), MavlinkStreamCameraCapture::send(), MavlinkStreamExtendedSysState::send(), uORB::KraitFastRpcChannel::send_message(), GPSDriverAshtech::sendSurveyInStatusUpdate(), StreamListItem::StreamListItem(), TemperatureCalibrationCommon< 3, 3 >::update(), MavlinkStreamHighLatency2::update_vehicle_status(), and MicroBenchORB::ut_declare_test_c().
struct vehicle_status_flags_s status_flags = {} static
Definition at line 176 of file Commander.cpp.
Referenced by Commander::run().
orb_advert_t status_pub static
Definition at line 516 of file Commander.cpp.
Referenced by Commander::handle_command(), and Commander::run().
constexpr float STICK_ON_OFF_LIMIT = 0.9f static
Definition at line 129 of file Commander.cpp.
Referenced by Commander::run().
volatile bool thread_running = false static
daemon status flag
Definition at line 142 of file Commander.cpp.
Referenced by commander_main(), and Commander::run().
volatile bool thread_should_exit = false static
daemon exit flag
Definition at line 141 of file Commander.cpp.
Referenced by commander_low_prio_loop(), commander_main(), and Commander::run().
struct vtol_vehicle_status_s vtol_status = {} static
Definition at line 170 of file Commander.cpp.
bool warning_action_on = false static
Definition at line 173 of file Commander.cpp.
Referenced by Commander::run(), and Commander::set_main_state_rc().