PX4 Firmware: src/systemcmds/tests/test_search_min.cpp File Reference
test_search_min.cpp File Reference
#include <unit_test.h>
#include <float.h>
#include <math.h>
#include <mathlib/math/SearchMin.hpp>
Classes
class SearchMinTest
Functions
float _linear_function (float x)
float _linear_function_flat (float x)
float _quadratic_function (float x)
Function Documentation
_linear_function()
float _linear_function (float x)
Definition at line 46 of file test_search_min.cpp.
Referenced by SearchMinTest::_init_inputs(), SearchMinTest::_init_inputs_flipped(), SearchMinTest::_init_inputs_negative(), SearchMinTest::_init_tol_larger_than_range(), and SearchMinTest::_init_tol_larger_than_range_flipped().
_linear_function_flat()
float _linear_function_flat (float x)
Definition at line 54 of file test_search_min.cpp.
Referenced by SearchMinTest::_no_extremum().
_quadratic_function()
float _quadratic_function (float x)
Definition at line 60 of file test_search_min.cpp.
References f().
Referenced by SearchMinTest::_init_inputs(), SearchMinTest::_init_inputs_flipped(), SearchMinTest::_init_inputs_negative(), SearchMinTest::_init_tol_larger_than_range(), and SearchMinTest::_init_tol_larger_than_range_flipped().