PX4 Firmware: src/platforms/posix/drivers/df_isl29501_wrapper/df_isl29501_wrapper.cpp File Reference
df_isl29501_wrapper.cpp File Reference
Driver to access the ISL29501 of the DriverFramework.
#include <px4_config.h>
#include <sys/types.h>
#include <sys/stat.h>
#include <stdint.h>
#include <stddef.h>
#include <stdlib.h>
#include <string.h>
#include <math.h>
#include <unistd.h>
#include <px4_getopt.h>
#include <errno.h>
#include <string>
#include <perf/perf_counter.h>
#include <systemlib/err.h>
#include <drivers/drv_range_finder.h>
#include <drivers/drv_hrt.h>
#include <uORB/uORB.h>
#include <uORB/topics/distance_sensor.h>
#include <board_config.h>
#include <isl29501/isl29501.hpp>
#include <DevMgr.hpp>
Classes
class DfISL29501Wrapper
Namespaces
df_isl29501_wrapper
Functions
__EXPORT int df_isl29501_wrapper_main (int argc, char *argv[])
int df_isl29501_wrapper::start ()
Attempt to start driver on all available I2C busses.
int df_isl29501_wrapper::stop ()
Stop the driver.
int df_isl29501_wrapper::info ()
Print a little info about the driver.
int df_isl29501_wrapper::probe ()
Who am i.
int df_isl29501_wrapper::calibration ()
Calibration runs calibration routine for ISL29501 TODO: implement calibration user interface and parameter system to store calib Note: Currently only serves debugging purpose, user is required to manually set offset inside code.
void df_isl29501_wrapper::usage ()
Prints info about the driver argument usage.
Variables
DfISL29501Wrapper * df_isl29501_wrapper::g_dev = nullptr
Detailed Description
Driver to access the ISL29501 of the DriverFramework.
Author
Zach Lovett zach..nosp@m.love.nosp@m.tt@3d.nosp@m.robo.nosp@m.tics..nosp@m.com
Siddharth B Purohit sid@3.nosp@m.drob.nosp@m.otics.nosp@m..com
Definition in file df_isl29501_wrapper.cpp.
Function Documentation
int df_isl29501_wrapper_main (int argc, char * argv[])
Definition at line 338 of file df_isl29501_wrapper.cpp.
References df_isl29501_wrapper::calibration(), df_isl29501_wrapper::info(), df_isl29501_wrapper::probe(), df_isl29501_wrapper::start(), df_isl29501_wrapper::stop(), and df_isl29501_wrapper::usage().