PX4 Firmware: RingBuffer< data_type > Class Template Reference
RingBuffer< data_type > Class Template Reference
#include <RingBuffer.h>
Public Member Functions
RingBuffer ()
~RingBuffer ()
RingBuffer (const RingBuffer &)=delete
RingBuffer & operator= (const RingBuffer &)=delete
RingBuffer (RingBuffer &&)=delete
RingBuffer & operator= (RingBuffer &&)=delete
bool allocate (uint8_t size)
void unallocate ()
void push (const data_type &sample)
uint8_t get_length () const
data_type & operator[] (const uint8_t index)
const data_type & get_newest ()
const data_type & get_oldest ()
uint8_t get_oldest_index () const
bool pop_first_older_than (const uint64_t &timestamp, data_type *sample)
int get_total_size ()
Private Attributes
data_type * _buffer {nullptr}
uint8_t _head {0}
uint8_t _tail {0}
uint8_t _size {0}
bool _first_write {true}
Detailed Description
template<typename data_type>
class RingBuffer< data_type >
Definition at line 45 of file RingBuffer.h.
Constructor & Destructor Documentation
RingBuffer() [1/3]
template<typename data_type> RingBuffer< data_type >::RingBuffer () inline
Definition at line 48 of file RingBuffer.h.
Referenced by RingBuffer< gpsSample >::~RingBuffer().
~RingBuffer()
template<typename data_type> RingBuffer< data_type >::~RingBuffer () inline
Definition at line 56 of file RingBuffer.h.
RingBuffer() [2/3]
template<typename data_type> RingBuffer< data_type >::RingBuffer (const RingBuffer< data_type > &) delete
RingBuffer() [3/3]
template<typename data_type> RingBuffer< data_type >::RingBuffer (RingBuffer< data_type > &&) delete
Member Function Documentation
allocate()
template<typename data_type> bool RingBuffer< data_type >::allocate (uint8_t size) inline
Definition at line 64 of file RingBuffer.h.
Referenced by EstimatorInterface::initialise_interface(), RingBuffer< gpsSample >::RingBuffer(), EstimatorInterface::setAirspeedData(), EstimatorInterface::setAuxVelData(), EstimatorInterface::setBaroData(), EstimatorInterface::setExtVisionData(), EstimatorInterface::setGpsData(), EstimatorInterface::setIMUData(), EstimatorInterface::setMagData(), EstimatorInterface::setOpticalFlowData(), and EstimatorInterface::setRangeData().
get_length()
template<typename data_type> uint8_t RingBuffer< data_type >::get_length () const inline
Definition at line 117 of file RingBuffer.h.
Referenced by Ekf::alignOutputFilter(), Ekf::calculateOutputStates(), Ekf::controlExternalVisionFusion(), EstimatorInterface::print_status(), Ekf::realignYawGPS(), Ekf::resetGpsAntYaw(), Ekf::resetHeight(), Ekf::resetMagHeading(), Ekf::resetPosition(), Ekf::resetVelocity(), EstimatorInterface::setAirspeedData(), EstimatorInterface::setAuxVelData(), EstimatorInterface::setBaroData(), EstimatorInterface::setExtVisionData(), EstimatorInterface::setGpsData(), EstimatorInterface::setIMUData(), EstimatorInterface::setMagData(), EstimatorInterface::setOpticalFlowData(), and EstimatorInterface::setRangeData().
get_newest()
template<typename data_type> const data_type& RingBuffer< data_type >::get_newest () inline
Definition at line 121 of file RingBuffer.h.
Referenced by Ekf::calculateOutputStates(), Ekf::controlExternalVisionFusion(), Ekf::controlFusionModes(), Ekf::controlHeightSensorTimeouts(), Ekf::initHagl(), Ekf::initialiseFilter(), and Ekf::resetHeight().
get_oldest()
template<typename data_type> const data_type& RingBuffer< data_type >::get_oldest () inline
Definition at line 122 of file RingBuffer.h.
Referenced by Ekf::calculateOutputStates(), and Ekf::collect_imu().
get_oldest_index()
template<typename data_type> uint8_t RingBuffer< data_type >::get_oldest_index () const inline
Definition at line 124 of file RingBuffer.h.
Referenced by Ekf::calculateOutputStates().
get_total_size()
template<typename data_type> int RingBuffer< data_type >::get_total_size () inline
Definition at line 161 of file RingBuffer.h.
Referenced by EstimatorInterface::print_status().
operator=() [1/2]
template<typename data_type> RingBuffer& RingBuffer< data_type >::operator= (const RingBuffer< data_type > &) delete
Referenced by RingBuffer< gpsSample >::~RingBuffer().
operator=() [2/2]
template<typename data_type> RingBuffer& RingBuffer< data_type >::operator= (RingBuffer< data_type > &&) delete
operator[]()
template<typename data_type> data_type& RingBuffer< data_type >::operator[] (const uint8_t index) inline
Definition at line 119 of file RingBuffer.h.
pop_first_older_than()
template<typename data_type> bool RingBuffer< data_type >::pop_first_older_than (const uint64_t & timestamp, data_type * sample) inline
Definition at line 126 of file RingBuffer.h.
Referenced by Ekf::controlAuxVelFusion(), Ekf::controlDragFusion(), Ekf::controlFusionModes(), and Ekf::initialiseFilter().
push()
template<typename data_type> void RingBuffer< data_type >::push (const data_type & sample) inline
Definition at line 97 of file RingBuffer.h.
Referenced by Ekf::calculateOutputStates(), Ekf::collect_imu(), RingBuffer< gpsSample >::RingBuffer(), EstimatorInterface::setAirspeedData(), EstimatorInterface::setAuxVelData(), EstimatorInterface::setBaroData(), EstimatorInterface::setExtVisionData(), EstimatorInterface::setGpsData(), EstimatorInterface::setIMUData(), EstimatorInterface::setMagData(), EstimatorInterface::setOpticalFlowData(), and EstimatorInterface::setRangeData().
unallocate()
template<typename data_type> void RingBuffer< data_type >::unallocate () inline
Definition at line 91 of file RingBuffer.h.
Referenced by EkfRingBufferTest::TearDown(), and EstimatorInterface::unallocate_buffers().
Member Data Documentation
_buffer
template<typename data_type> data_type* RingBuffer< data_type >::_buffer {nullptr} private
Definition at line 164 of file RingBuffer.h.
Referenced by RingBuffer< gpsSample >::allocate(), RingBuffer< gpsSample >::get_newest(), RingBuffer< gpsSample >::get_oldest(), RingBuffer< gpsSample >::operator[](), RingBuffer< gpsSample >::pop_first_older_than(), RingBuffer< gpsSample >::push(), RingBuffer< gpsSample >::unallocate(), and RingBuffer< gpsSample >::~RingBuffer().
_first_write
template<typename data_type> bool RingBuffer< data_type >::_first_write {true} private
Definition at line 170 of file RingBuffer.h.
Referenced by RingBuffer< gpsSample >::allocate(), RingBuffer< gpsSample >::pop_first_older_than(), and RingBuffer< gpsSample >::push().
_head
template<typename data_type> uint8_t RingBuffer< data_type >::_head {0} private
Definition at line 166 of file RingBuffer.h.
Referenced by RingBuffer< gpsSample >::allocate(), RingBuffer< gpsSample >::get_newest(), RingBuffer< gpsSample >::pop_first_older_than(), and RingBuffer< gpsSample >::push().
_size
template<typename data_type> uint8_t RingBuffer< data_type >::_size {0} private
Definition at line 168 of file RingBuffer.h.
Referenced by RingBuffer< gpsSample >::allocate(), RingBuffer< gpsSample >::get_length(), RingBuffer< gpsSample >::get_total_size(), RingBuffer< gpsSample >::pop_first_older_than(), and RingBuffer< gpsSample >::push().
_tail
template<typename data_type> uint8_t RingBuffer< data_type >::_tail {0} private
Definition at line 167 of file RingBuffer.h.
Referenced by RingBuffer< gpsSample >::allocate(), RingBuffer< gpsSample >::get_oldest(), RingBuffer< gpsSample >::get_oldest_index(), RingBuffer< gpsSample >::pop_first_older_than(), and RingBuffer< gpsSample >::push().
The documentation for this class was generated from the following files:
src/lib/ecl/EKF/RingBuffer.h
src/lib/drivers/device/ringbuffer.cpp