PX4 Firmware: UavcanEscController Class Reference
UavcanEscController Class Reference
#include <esc.hpp>
Public Member Functions
UavcanEscController (uavcan::INode &node)
~UavcanEscController ()
int init ()
void update_outputs (float *outputs, unsigned num_outputs)
void arm_all_escs (bool arm)
void arm_single_esc (int num, bool arm)
void enable_idle_throttle_when_armed (bool value)
Private Types
typedef uavcan::MethodBinder< UavcanEscController *, void(UavcanEscController::*)(const uavcan::ReceivedDataStructure< uavcan::equipment::esc::Status > &)> StatusCbBinder
typedef uavcan::MethodBinder< UavcanEscController *, void(UavcanEscController::*)(const uavcan::TimerEvent &)> TimerCbBinder
Private Member Functions
void esc_status_sub_cb (const uavcan::ReceivedDataStructure< uavcan::equipment::esc::Status > &msg)
ESC status message reception will be reported via this callback.
void orb_pub_timer_cb (const uavcan::TimerEvent &event)
ESC status will be published to ORB from this callback (fixed rate).
Private Attributes
bool _armed = false
bool _run_at_idle_throttle_when_armed = false
esc_status_s _esc_status = {}
orb_advert_t _esc_status_pub = nullptr
orb_advert_t _actuator_outputs_pub = nullptr
uavcan::MonotonicTime _prev_cmd_pub
rate limiting
uavcan::INode & _node
uavcan::Publisher< uavcan::equipment::esc::RawCommand > _uavcan_pub_raw_cmd
uavcan::Subscriber< uavcan::equipment::esc::Status, StatusCbBinder > _uavcan_sub_status
uavcan::TimerEventForwarder< TimerCbBinder > _orb_timer
uint32_t _armed_mask = 0
uint8_t _max_number_of_nonzero_outputs = 0
perf_counter_t _perfcnt_invalid_input = perf_alloc(PC_COUNT, "uavcan_esc_invalid_input")
perf_counter_t _perfcnt_scaling_error = perf_alloc(PC_COUNT, "uavcan_esc_scaling_error")
Static Private Attributes
static constexpr unsigned MAX_RATE_HZ = 200
XXX make this configurable.
static constexpr unsigned ESC_STATUS_UPDATE_RATE_HZ = 10
static constexpr unsigned UAVCAN_COMMAND_TRANSFER_PRIORITY = 5
0..31, inclusive, 0 - highest, 31 - lowest
Detailed Description
Definition at line 55 of file esc.hpp.
Member Typedef Documentation
typedef uavcan::MethodBinder<UavcanEscController *, void (UavcanEscController::*)(const uavcan::ReceivedDataStructure<uavcan::equipment::esc::Status>&)> UavcanEscController::StatusCbBinder private
Definition at line 88 of file esc.hpp.
typedef uavcan::MethodBinder<UavcanEscController *, void (UavcanEscController::*)(const uavcan::TimerEvent &)> UavcanEscController::TimerCbBinder private
Definition at line 91 of file esc.hpp.
Constructor & Destructor Documentation
UavcanEscController::UavcanEscController (uavcan::INode & node)
Definition at line 46 of file esc.cpp.
References _perfcnt_invalid_input, _perfcnt_scaling_error, _uavcan_pub_raw_cmd, errx, and UAVCAN_COMMAND_TRANSFER_PRIORITY.
UavcanEscController::~UavcanEscController ()
Definition at line 63 of file esc.cpp.
References _perfcnt_invalid_input, _perfcnt_scaling_error, and perf_free().
Member Function Documentation
void UavcanEscController::arm_all_escs (bool arm)
Definition at line 182 of file esc.cpp.
References _armed_mask.
Referenced by UavcanNode::arm_actuators().
void UavcanEscController::arm_single_esc (int num, bool arm)
Definition at line 192 of file esc.cpp.
References _armed_mask, and MOTOR_BIT.
Referenced by UavcanNode::run().
void UavcanEscController::enable_idle_throttle_when_armed (bool value) inline
Definition at line 68 of file esc.hpp.
References _run_at_idle_throttle_when_armed, esc_status_sub_cb(), msg, and orb_pub_timer_cb().
Referenced by UavcanNode::init(), and UavcanNode::run().
void UavcanEscController::esc_status_sub_cb (const uavcan::ReceivedDataStructure< uavcan::equipment::esc::Status > & msg) private
ESC status message reception will be reported via this callback.
Definition at line 202 of file esc.cpp.
References _esc_status, esc_status_s::esc, esc_report_s::esc_address, esc_status_s::esc_count, and esc_status_s::timestamp.
Referenced by enable_idle_throttle_when_armed(), and init().
int UavcanEscController::init ()
Definition at line 69 of file esc.cpp.
References _orb_timer, _uavcan_sub_status, esc_status_sub_cb(), ESC_STATUS_UPDATE_RATE_HZ, orb_pub_timer_cb(), and warnx.
Referenced by UavcanNode::init().
void UavcanEscController::orb_pub_timer_cb (const uavcan::TimerEvent & event) private
ESC status will be published to ORB from this callback (fixed rate).
Definition at line 221 of file esc.cpp.
References _esc_status, _esc_status_pub, esc_status_s::counter, esc_status_s::esc_connectiontype, orb_advertise(), ORB_ID, and orb_publish().
Referenced by enable_idle_throttle_when_armed(), and init().
void UavcanEscController::update_outputs (float * outputs, unsigned num_outputs)
Definition at line 86 of file esc.cpp.
References _actuator_outputs_pub, _armed_mask, _esc_status, _max_number_of_nonzero_outputs, _node, _perfcnt_invalid_input, _perfcnt_scaling_error, _prev_cmd_pub, _run_at_idle_throttle_when_armed, _uavcan_pub_raw_cmd, esc_status_s::esc, esc_report_s::esc_setpoint_raw, hrt_absolute_time(), instance, max(), MAX_RATE_HZ, MOTOR_BIT, msg, actuator_outputs_s::noutputs, orb_advertise_multi(), ORB_ID, ORB_PRIO_DEFAULT, orb_publish(), actuator_outputs_s::output, perf_count(), and actuator_outputs_s::timestamp.
Referenced by UavcanNode::run().
Member Data Documentation
orb_advert_t UavcanEscController::_actuator_outputs_pub = nullptr private
Definition at line 97 of file esc.hpp.
Referenced by update_outputs().
bool UavcanEscController::_armed = false private
Definition at line 93 of file esc.hpp.
uint32_t UavcanEscController::_armed_mask = 0 private
Definition at line 111 of file esc.hpp.
Referenced by arm_all_escs(), arm_single_esc(), and update_outputs().
esc_status_s UavcanEscController::_esc_status = {} private
Definition at line 95 of file esc.hpp.
Referenced by esc_status_sub_cb(), orb_pub_timer_cb(), and update_outputs().
orb_advert_t UavcanEscController::_esc_status_pub = nullptr private
Definition at line 96 of file esc.hpp.
Referenced by orb_pub_timer_cb().
uint8_t UavcanEscController::_max_number_of_nonzero_outputs = 0 private
Definition at line 112 of file esc.hpp.
Referenced by update_outputs().
uavcan::INode& UavcanEscController::_node private
Definition at line 103 of file esc.hpp.
Referenced by update_outputs().
uavcan::TimerEventForwarder<TimerCbBinder> UavcanEscController::_orb_timer private
Definition at line 106 of file esc.hpp.
Referenced by init().
perf_counter_t UavcanEscController::_perfcnt_invalid_input = perf_alloc(PC_COUNT, "uavcan_esc_invalid_input") private
Definition at line 117 of file esc.hpp.
Referenced by UavcanEscController(), update_outputs(), and ~UavcanEscController().
perf_counter_t UavcanEscController::_perfcnt_scaling_error = perf_alloc(PC_COUNT, "uavcan_esc_scaling_error") private
Definition at line 118 of file esc.hpp.
Referenced by UavcanEscController(), update_outputs(), and ~UavcanEscController().
uavcan::MonotonicTime UavcanEscController::_prev_cmd_pub private
rate limiting
Definition at line 102 of file esc.hpp.
Referenced by update_outputs().
bool UavcanEscController::_run_at_idle_throttle_when_armed = false private
Definition at line 94 of file esc.hpp.
Referenced by enable_idle_throttle_when_armed(), and update_outputs().
uavcan::Publisher<uavcan::equipment::esc::RawCommand> UavcanEscController::_uavcan_pub_raw_cmd private
Definition at line 104 of file esc.hpp.
Referenced by UavcanEscController(), and update_outputs().
uavcan::Subscriber<uavcan::equipment::esc::Status, StatusCbBinder> UavcanEscController::_uavcan_sub_status private
Definition at line 105 of file esc.hpp.
Referenced by init().
constexpr unsigned UavcanEscController::ESC_STATUS_UPDATE_RATE_HZ = 10 static private
Definition at line 83 of file esc.hpp.
Referenced by init().
constexpr unsigned UavcanEscController::MAX_RATE_HZ = 200 static private
XXX make this configurable.
Definition at line 82 of file esc.hpp.
Referenced by update_outputs().
constexpr unsigned UavcanEscController::UAVCAN_COMMAND_TRANSFER_PRIORITY = 5 static private
0..31, inclusive, 0 - highest, 31 - lowest
Definition at line 84 of file esc.hpp.
Referenced by UavcanEscController().
The documentation for this class was generated from the following files:
src/modules/uavcan/actuators/esc.hpp
src/modules/uavcan/actuators/esc.cpp