PX4 Firmware: voxlpm Namespace Reference
voxlpm Namespace Reference
Local functions in support of the shell command.
Classes
struct voxlpm_bus_option
struct voxlpm_chan
Functions
bool start_bus (struct voxlpm_bus_option &bus)
Start the driver.
void start (enum VOXLPM_BUS busid)
void info ()
Print a little info about the driver.
void usage ()
Prints info about the driver argument usage.
Variables
struct voxlpm::voxlpm_bus_option bus_options []
Detailed Description
Local functions in support of the shell command.
Function Documentation
info()
void voxlpm::info ()
Print a little info about the driver.
Definition at line 148 of file voxlpm_main.cpp.
References NUM_BUS_OPTIONS.
Referenced by voxlpm_main().
start()
void voxlpm::start (enum VOXLPM_BUS busid)
Definition at line 126 of file voxlpm_main.cpp.
References NUM_BUS_OPTIONS, and start_bus().
Referenced by voxlpm_main().
start_bus()
bool voxlpm::start_bus (struct voxlpm_bus_option & bus)
Start the driver.
Definition at line 92 of file voxlpm_main.cpp.
References voxlpm::voxlpm_bus_option::busnum, voxlpm::voxlpm_chan::dev, voxlpm::voxlpm_chan::device, voxlpm::voxlpm_chan::devpath, VOXLPM::init(), OK, voxlpm::voxlpm_bus_option::vbat, VOXLPM_CH_TYPE_P5VDC, VOXLPM_CH_TYPE_VBATT, and voxlpm::voxlpm_bus_option::vpwr.
Referenced by start().
usage()
void voxlpm::usage (void)
Prints info about the driver argument usage.
Prints info about the driver argument usage.
Definition at line 166 of file voxlpm_main.cpp.
Referenced by voxlpm_main().
Variable Documentation
bus_options
struct voxlpm::voxlpm_bus_option voxlpm::bus_options[]
Initial value:
= {
}