PX4 Firmware: adis16477 Namespace Reference
adis16477 Namespace Reference
Local functions in support of the shell command.
Functions
void start (enum Rotation rotation)
Start the driver.
void test ()
Perform some basic functional tests on the driver; make sure we can collect data from the sensor in polled and automatic modes.
void reset ()
Reset the driver.
void info ()
Print a little info about the driver.
void usage ()
Prints info about the driver argument usage.
Variables
ADIS16477 * g_dev
Detailed Description
Local functions in support of the shell command.
Function Documentation
void adis16477::info ()
Print a little info about the driver.
Print a little info about the driver.
Definition at line 191 of file ADIS16477_main.cpp.
References errx, and ADIS16477::print_info().
Referenced by adis16477_main().
void adis16477::reset ()
Reset the driver.
Reset the driver.
Definition at line 166 of file ADIS16477_main.cpp.
References ADIS16477_DEVICE_PATH_ACCEL, err, fd, px4_close(), px4_ioctl(), px4_open(), SENSOR_POLLRATE_DEFAULT, SENSORIOCRESET, and SENSORIOCSPOLLRATE.
Referenced by adis16477_main(), and test().
void adis16477::start (enum Rotation rotation)
Start the driver.
Definition at line 58 of file ADIS16477_main.cpp.
References ADIS16477_DEVICE_PATH_ACCEL, ADIS16477_DEVICE_PATH_GYRO, errx, fd, g_dev, lis3mdl::init(), OK, px4_close(), PX4_ERR, px4_ioctl(), px4_open(), PX4_SPI_BUS_SENSOR1, PX4_SPIDEV_ADIS16477, SENSOR_POLLRATE_DEFAULT, and SENSORIOCSPOLLRATE.
Referenced by adis16477_main().
void adis16477::test ()
Perform some basic functional tests on the driver; make sure we can collect data from the sensor in polled and automatic modes.
Definition at line 114 of file ADIS16477_main.cpp.
References accel_report, ADIS16477_DEVICE_PATH_ACCEL, ADIS16477_DEVICE_PATH_GYRO, err, errx, fd, gyro_report, px4_close(), PX4_ERR, px4_open(), px4_read(), read(), reset(), and warnx.
Referenced by adis16477_main().
void adis16477::usage (void)
Prints info about the driver argument usage.
Prints info about the driver argument usage.
Definition at line 204 of file ADIS16477_main.cpp.
References PX4_INFO.
Referenced by adis16477_main().
Variable Documentation
ADIS16477* adis16477::g_dev
Definition at line 47 of file ADIS16477_main.cpp.
Referenced by start().