PX4 Firmware: px4 Namespace Reference
px4 Namespace Reference
Namespaces
bst
logger
replay
Classes
class AppState
class Array
class Mavlink
class NodeHandle
class Publisher
Publisher base class, templated with the message type.
class PublisherBase
Untemplated publisher base class.
class PublisherNode
Because we maintain a list of publishers we need a node class.
class PublisherUORB
class PX4Message
class Rate
Linux needs to have globally unique checks for thread/task status.
class Replay
Parses an ULog file and replays it in 'real-time'.
class ReplayEkf2
replay specialization for Ekf2 replay
class Subscriber
Subscriber class which is used by nodehandle.
class SubscriberBase
Untemplated subscriber base class.
class SubscriberNode
Because we maintain a list of subscribers we need a node class.
class SubscriberUORB
Subscriber class that is templated with the uorb subscription message type.
class SubscriberUORBCallback
Functions
__EXPORT void init (int argc, char *argv[], const char *process_name)
__EXPORT uint64_t get_time_micros ()
Function Documentation
uint64_t px4::get_time_micros ()
Definition at line 50 of file px4_ros_impl.cpp.
Referenced by px4::Mavlink::handle_msg_set_attitude_target(), px4::Mavlink::handle_msg_set_position_target_local_ned(), AttitudeEstimator::ImuCallback(), ManualInput::JoyCallback(), DemoOffboardAttitudeSetpoints::main(), Commander::ManualControlInputCallback(), AttitudeEstimator::ModelStatesCallback(), PositionEstimator::ModelStatesCallback(), Commander::OffboardControlModeCallback(), px4::Mavlink::VehicleAttitudeCallback(), and px4::Mavlink::VehicleLocalPositionCallback().
void px4::init (int argc, char * argv[], const char * process_name)
Definition at line 45 of file px4_ros_impl.cpp.
References lis3mdl::init().
Referenced by muorb_test_entry(), PX4_MAIN(), and qshell_entry().