PX4 Firmware: meas_airspeed_sim Namespace Reference
meas_airspeed_sim Namespace Reference
Local functions in support of the shell command.
Functions
int start (int i2c_bus)
Start the driver.
int stop ()
Stop the driver.
int test ()
Perform some basic functional tests on the driver; make sure we can collect data from the sensor in polled and automatic modes.
int reset ()
Reset the driver.
int info ()
Print a little info about the driver.
Variables
MEASAirspeedSim * g_dev = nullptr
Detailed Description
Local functions in support of the shell command.
Function Documentation
int meas_airspeed_sim::info ()
Print a little info about the driver.
Print a little info about the driver.
Definition at line 471 of file meas_airspeed_sim.cpp.
References AirspeedSim::print_info(), and PX4_WARN.
Referenced by measairspeedsim_main().
int meas_airspeed_sim::reset ()
Reset the driver.
Reset the driver.
Definition at line 441 of file meas_airspeed_sim.cpp.
References device::CDev::close(), fd, AirspeedSim::ioctl(), device::CDev::open(), PATH_MS4525, PX4_ERR, SENSOR_POLLRATE_DEFAULT, SENSORIOCRESET, and SENSORIOCSPOLLRATE.
Referenced by measairspeedsim_main().
int meas_airspeed_sim::start (int i2c_bus)
Start the driver.
This function call only returns once the driver is up and running or failed to detect the sensor.
Definition at line 296 of file meas_airspeed_sim.cpp.
References fd, g_dev, I2C_ADDRESS_MS4525DO, I2C_ADDRESS_MS5525DSO, MEASAirspeedSim::MEASAirspeedSim(), OK, PATH_MS4525, PATH_MS5525, PX4_ERR, px4_ioctl(), px4_open(), PX4_WARN, SENSOR_POLLRATE_DEFAULT, and SENSORIOCSPOLLRATE.
Referenced by measairspeedsim_main().
int meas_airspeed_sim::stop ()
Stop the driver.
Stop the driver.
Definition at line 356 of file meas_airspeed_sim.cpp.
References g_dev, and PX4_ERR.
Referenced by measairspeedsim_main().
int meas_airspeed_sim::test ()
Perform some basic functional tests on the driver; make sure we can collect data from the sensor in polled and automatic modes.
Definition at line 375 of file meas_airspeed_sim.cpp.
References fd, AirspeedSim::ioctl(), OK, PATH_MS4525, device::CDev::poll(), PX4_ERR, px4_ioctl(), px4_open(), px4_read(), PX4_WARN, AirspeedSim::read(), SENSOR_POLLRATE_DEFAULT, SENSORIOCSPOLLRATE, and warnx.
Referenced by measairspeedsim_main().
Variable Documentation
MEASAirspeedSim* meas_airspeed_sim::g_dev = nullptr
Definition at line 281 of file meas_airspeed_sim.cpp.
Referenced by start(), and stop().