PX4 Firmware: SRF02 Class Reference
SRF02 Class Reference
Public Member Functions
SRF02 (uint8_t rotation=distance_sensor_s::ROTATION_DOWNWARD_FACING, int bus=SRF02_BUS_DEFAULT, int address=SRF02_BASEADDR)
virtual ~SRF02 ()
virtual int init ()
virtual ssize_t read (device::file_t *filp, char *buffer, size_t buflen)
virtual int ioctl (device::file_t *filp, int cmd, unsigned long arg)
void print_info ()
Diagnostics - print some basic information about the driver.
Protected Member Functions
virtual int probe ()
Private Member Functions
int probe_address (uint8_t address)
Test whether the device supported by the driver is present at a specific address.
void start ()
Initialise the automatic measurement state machine and start it.
void stop ()
Stop the automatic measurement state machine.
void set_minimum_distance (float min)
Set the min and max distance thresholds if you want the end points of the sensors range to be brought in at all, otherwise it will use the defaults SRF02_MIN_DISTANCE and SRF02_MAX_DISTANCE.
void set_maximum_distance (float max)
float get_minimum_distance ()
float get_maximum_distance ()
void cycle ()
Perform a poll cycle; collect from the previous measurement and start a new one.
int measure ()
int collect ()
Static Private Member Functions
static void cycle_trampoline (void *arg)
Static trampoline from the workq context; because we don't have a generic workq wrapper yet.
Private Attributes
uint8_t _rotation
float _min_distance
float _max_distance
work_s _work
ringbuffer::RingBuffer * _reports
bool _sensor_ok
int _measure_ticks
bool _collect_phase
int _class_instance
int _orb_class_instance
orb_advert_t _distance_sensor_topic
perf_counter_t _sample_perf
perf_counter_t _comms_errors
uint8_t _cycle_counter
int _cycling_rate
uint8_t _index_counter
std::vector< uint8_t > addr_ind
std::vector< float > _latest_sonar_measurements
Detailed Description
Definition at line 94 of file srf02.cpp.
Constructor & Destructor Documentation
SRF02::SRF02 (uint8_t rotation = distance_sensor_s::ROTATION_DOWNWARD_FACING, int bus = SRF02_BUS_DEFAULT, int address = SRF02_BASEADDR)
Definition at line 194 of file srf02.cpp.
Referenced by srf02::start_bus().
SRF02::~SRF02 () virtual
Definition at line 220 of file srf02.cpp.
References _class_instance, _comms_errors, _reports, _sample_perf, perf_free(), RANGE_FINDER_BASE_DEVICE_PATH, and stop().
Member Function Documentation
int SRF02::collect () private
Definition at line 532 of file srf02.cpp.
References _comms_errors, _distance_sensor_topic, _reports, _rotation, _sample_perf, distance_sensor_s::covariance, distance_sensor_s::current_distance, DEVICE_DEBUG, f(), get_maximum_distance(), get_minimum_distance(), hrt_absolute_time(), distance_sensor_s::id, distance_sensor_s::max_distance, distance_sensor_s::min_distance, OK, ORB_ID, orb_publish(), distance_sensor_s::orientation, perf_begin(), perf_count(), perf_end(), distance_sensor_s::signal_quality, distance_sensor_s::timestamp, and distance_sensor_s::type.
Referenced by cycle(), and read().
void SRF02::cycle () private
Perform a poll cycle; collect from the previous measurement and start a new one.
Definition at line 611 of file srf02.cpp.
References _collect_phase, _cycle_counter, _cycling_rate, _index_counter, _measure_ticks, addr_ind, collect(), cycle_trampoline(), DEVICE_DEBUG, measure(), OK, and start().
Referenced by cycle_trampoline().
void SRF02::cycle_trampoline (void * arg) static private
Static trampoline from the workq context; because we don't have a generic workq wrapper yet.
Parameters
arg Instance pointer for the driver that is polling.
Definition at line 601 of file srf02.cpp.
References cycle().
Referenced by cycle(), and start().
float SRF02::get_maximum_distance () private
Definition at line 339 of file srf02.cpp.
References _max_distance.
Referenced by collect().
float SRF02::get_minimum_distance () private
Definition at line 333 of file srf02.cpp.
References _min_distance.
Referenced by collect().
int SRF02::init () virtual
Definition at line 240 of file srf02.cpp.
References _class_instance, _cycling_rate, _distance_sensor_topic, _index_counter, _latest_sonar_measurements, _orb_class_instance, _reports, _sensor_ok, addr_ind, counter, DEVICE_DEBUG, DEVICE_LOG, lis3mdl::init(), MB12XX_MAX_RANGEFINDERS, measure(), OK, orb_advertise_multi(), ORB_ID, ORB_PRIO_LOW, PX4_ERROR, RANGE_FINDER_BASE_DEVICE_PATH, SRF02_BASEADDR, SRF02_CONVERSION_INTERVAL, TICKS_BETWEEN_SUCCESIVE_FIRES, and usleep().
Referenced by srf02::start_bus().
int SRF02::ioctl (device::file_t * filp, int cmd, unsigned long arg) virtual
Definition at line 345 of file srf02.cpp.
References _cycling_rate, _measure_ticks, _reports, ATOMIC_ENTER, ATOMIC_LEAVE, OK, SENSOR_POLLRATE_DEFAULT, SENSOR_POLLRATE_EXTERNAL, SENSOR_POLLRATE_MANUAL, SENSOR_POLLRATE_MAX, SENSORIOCGPOLLRATE, SENSORIOCRESET, SENSORIOCSPOLLRATE, SENSORIOCSQUEUEDEPTH, start(), and stop().
Referenced by srf02::reset(), srf02::start_bus(), and srf02::test().
int SRF02::measure () private
Definition at line 506 of file srf02.cpp.
References _comms_errors, DEVICE_DEBUG, OK, perf_count(), and SRF02_TAKE_RANGE_REG.
Referenced by cycle(), init(), probe(), and read().
void SRF02::print_info ()
Diagnostics - print some basic information about the driver.
Definition at line 674 of file srf02.cpp.
References _comms_errors, _measure_ticks, _reports, _sample_perf, and perf_print_counter().
Referenced by srf02::info().
int SRF02::probe () protected virtual
Definition at line 315 of file srf02.cpp.
References measure().
int SRF02::probe_address (uint8_t address) private
Test whether the device supported by the driver is present at a specific address.
Parameters
address The I2C bus address to probe.
Returns
True if the device is present.
ssize_t SRF02::read (device::file_t * filp, char * buffer, size_t buflen) virtual
Definition at line 445 of file srf02.cpp.
References _cycling_rate, _measure_ticks, _reports, collect(), measure(), OK, and usleep().
Referenced by srf02::test().
void SRF02::set_maximum_distance (float max) private
Definition at line 327 of file srf02.cpp.
References _max_distance, and max().
void SRF02::set_minimum_distance (float min) private
Set the min and max distance thresholds if you want the end points of the sensors range to be brought in at all, otherwise it will use the defaults SRF02_MIN_DISTANCE and SRF02_MAX_DISTANCE.
Definition at line 321 of file srf02.cpp.
References _min_distance, and min().
void SRF02::start () private
Initialise the automatic measurement state machine and start it.
Note
This function is called at open and error time. It might make sense to make it more aggressive about resetting the bus in case of errors.
Definition at line 583 of file srf02.cpp.
References _collect_phase, _reports, and cycle_trampoline().
Referenced by cycle(), and ioctl().
void SRF02::stop () private
Stop the automatic measurement state machine.
Definition at line 595 of file srf02.cpp.
Referenced by ioctl(), and ~SRF02().
Member Data Documentation
int SRF02::_class_instance private
Definition at line 123 of file srf02.cpp.
Referenced by init(), and ~SRF02().
bool SRF02::_collect_phase private
Definition at line 122 of file srf02.cpp.
Referenced by cycle(), and start().
perf_counter_t SRF02::_comms_errors private
Definition at line 129 of file srf02.cpp.
Referenced by collect(), measure(), print_info(), and ~SRF02().
uint8_t SRF02::_cycle_counter private
Definition at line 131 of file srf02.cpp.
Referenced by cycle().
int SRF02::_cycling_rate private
Definition at line 132 of file srf02.cpp.
Referenced by cycle(), init(), ioctl(), and read().
orb_advert_t SRF02::_distance_sensor_topic private
Definition at line 126 of file srf02.cpp.
Referenced by collect(), and init().
uint8_t SRF02::_index_counter private
Definition at line 133 of file srf02.cpp.
Referenced by cycle(), and init().
std::vector<float> SRF02::_latest_sonar_measurements private
Definition at line 136 of file srf02.cpp.
Referenced by init().
float SRF02::_max_distance private
Definition at line 117 of file srf02.cpp.
Referenced by get_maximum_distance(), and set_maximum_distance().
int SRF02::_measure_ticks private
Definition at line 121 of file srf02.cpp.
Referenced by cycle(), ioctl(), print_info(), and read().
float SRF02::_min_distance private
Definition at line 116 of file srf02.cpp.
Referenced by get_minimum_distance(), and set_minimum_distance().
int SRF02::_orb_class_instance private
Definition at line 124 of file srf02.cpp.
Referenced by init().
ringbuffer::RingBuffer* SRF02::_reports private
Definition at line 119 of file srf02.cpp.
Referenced by collect(), init(), ioctl(), print_info(), read(), start(), and ~SRF02().
uint8_t SRF02::_rotation private
Definition at line 115 of file srf02.cpp.
Referenced by collect().
perf_counter_t SRF02::_sample_perf private
Definition at line 128 of file srf02.cpp.
Referenced by collect(), print_info(), and ~SRF02().
bool SRF02::_sensor_ok private
Definition at line 120 of file srf02.cpp.
Referenced by init().
work_s SRF02::_work private
Definition at line 118 of file srf02.cpp.
std::vector<uint8_t> SRF02::addr_ind private
Definition at line 134 of file srf02.cpp.
Referenced by cycle(), and init().
The documentation for this class was generated from the following file:
src/drivers/distance_sensor/srf02/srf02.cpp