PX4 Firmware: MavlinkStreamOdometry Class Reference
MavlinkStreamOdometry Class Reference
Public Member Functions
const char * get_name () const override
uint16_t get_id () override
unsigned get_size () override
Get maximal total messages size on update.
Public Member Functions inherited from MavlinkStream
MavlinkStream (Mavlink *mavlink)
virtual ~MavlinkStream ()=default
MavlinkStream (const MavlinkStream &)=delete
MavlinkStream & operator= (const MavlinkStream &)=delete
MavlinkStream (MavlinkStream &&)=delete
MavlinkStream & operator= (MavlinkStream &&)=delete
void set_interval (const int interval)
Get the interval.
int get_interval ()
Get the interval.
int update (const hrt_abstime &t)
Update subscriptions and send message if necessary.
virtual bool const_rate ()
virtual unsigned get_size_avg ()
Get the average message size.
bool first_message_sent () const
void reset_last_sent ()
Reset the time of last sent to 0.
Public Member Functions inherited from ListNode< MavlinkStream *>
void setSibling (MavlinkStream * sibling)
const MavlinkStream * getSibling () const
Static Public Member Functions
static const char * get_name_static ()
static uint16_t get_id_static ()
static MavlinkStream * new_instance (Mavlink *mavlink)
Protected Member Functions
MavlinkStreamOdometry (Mavlink *mavlink)
bool send (const hrt_abstime t) override
Protected Member Functions inherited from MavlinkStream
virtual void update_data ()
Function to collect/update data for the streams at a high rate independant of actual stream rate.
Private Member Functions
MavlinkStreamOdometry (MavlinkStreamOdometry &)=delete
MavlinkStreamOdometry & operator= (const MavlinkStreamOdometry &)=delete
Private Attributes
MavlinkOrbSubscription * _odom_sub
uint64_t _odom_time
MavlinkOrbSubscription * _vodom_sub
uint64_t _vodom_time
Additional Inherited Members
Protected Attributes inherited from MavlinkStream
Mavlink *const _mavlink
int _interval {1000000}
if set to negative value = unlimited rate
Protected Attributes inherited from ListNode< MavlinkStream *>
MavlinkStream * _list_node_sibling
Detailed Description
Definition at line 2424 of file mavlink_messages.cpp.
Constructor & Destructor Documentation
MavlinkStreamOdometry() [1/2]
MavlinkStreamOdometry::MavlinkStreamOdometry (MavlinkStreamOdometry &) private delete
MavlinkStreamOdometry() [2/2]
MavlinkStreamOdometry::MavlinkStreamOdometry (Mavlink * mavlink) inline explicit protected
Definition at line 2469 of file mavlink_messages.cpp.
Member Function Documentation
get_id()
uint16_t MavlinkStreamOdometry::get_id () inline override virtual
Implements MavlinkStream.
Definition at line 2442 of file mavlink_messages.cpp.
References MavlinkStreamHeartbeat::get_id_static().
get_id_static()
static uint16_t MavlinkStreamOdometry::get_id_static () inline static
Definition at line 2437 of file mavlink_messages.cpp.
get_name()
const char* MavlinkStreamOdometry::get_name () const inline override virtual
Implements MavlinkStream.
Definition at line 2427 of file mavlink_messages.cpp.
References get_name_static().
get_name_static()
static const char* MavlinkStreamOdometry::get_name_static () inline static
Definition at line 2432 of file mavlink_messages.cpp.
Referenced by get_name().
get_size()
unsigned MavlinkStreamOdometry::get_size () inline override virtual
Get maximal total messages size on update.
Implements MavlinkStream.
Definition at line 2452 of file mavlink_messages.cpp.
new_instance()
static MavlinkStream* MavlinkStreamOdometry::new_instance (Mavlink * mavlink) inline static
Definition at line 2447 of file mavlink_messages.cpp.
operator=()
MavlinkStreamOdometry& MavlinkStreamOdometry::operator= (const MavlinkStreamOdometry &) private delete
send()
bool MavlinkStreamOdometry::send (const hrt_abstime t) inline override protected virtual
Implements MavlinkStream.
Definition at line 2476 of file mavlink_messages.cpp.
References MavlinkStream::_mavlink, Mavlink::get_channel(), msg, Mavlink::odometry_loopback_enabled(), vehicle_odometry_s::pitchspeed, vehicle_odometry_s::pose_covariance, vehicle_odometry_s::q, vehicle_odometry_s::rollspeed, vehicle_odometry_s::timestamp, matrix::Matrix< Type, M, N >::transpose(), MavlinkOrbSubscription::update(), vehicle_odometry_s::velocity_covariance, vehicle_odometry_s::vx, vehicle_odometry_s::vy, vehicle_odometry_s::vz, vehicle_odometry_s::x, vehicle_odometry_s::y, vehicle_odometry_s::yawspeed, and vehicle_odometry_s::z.
Member Data Documentation
_odom_sub
MavlinkOrbSubscription* MavlinkStreamOdometry::_odom_sub private
Definition at line 2458 of file mavlink_messages.cpp.
_odom_time
uint64_t MavlinkStreamOdometry::_odom_time private
Definition at line 2459 of file mavlink_messages.cpp.
_vodom_sub
MavlinkOrbSubscription* MavlinkStreamOdometry::_vodom_sub private
Definition at line 2461 of file mavlink_messages.cpp.
_vodom_time
uint64_t MavlinkStreamOdometry::_vodom_time private
Definition at line 2462 of file mavlink_messages.cpp.
The documentation for this class was generated from the following file:
src/modules/mavlink/mavlink_messages.cpp