PX4 Firmware: HRTTest Class Reference
HRTTest Class Reference
#include <hrt_test.h>
Public Member Functions
HRTTest ()
~HRTTest ()
int main ()
Static Public Attributes
static px4::AppState appState
Detailed Description
Definition at line 44 of file hrt_test.h.
Constructor & Destructor Documentation
HRTTest::HRTTest () inline
Definition at line 47 of file hrt_test.h.
HRTTest::~HRTTest () inline
Definition at line 49 of file hrt_test.h.
References main().
Member Function Documentation
int HRTTest::main ()
Definition at line 66 of file hrt_test.cpp.
References appState, hrt_absolute_time(), hrt_abstime, hrt_call_after(), hrt_called(), hrt_cancel(), hrt_elapsed_time(), PX4_INFO, px4::AppState::setRunning(), t1, timer_expired(), update_interval, and usleep().
Referenced by PX4_MAIN(), and ~HRTTest().
Member Data Documentation
px4::AppState HRTTest::appState static
Definition at line 53 of file hrt_test.h.
Referenced by hrt_test_main(), and main().
The documentation for this class was generated from the following files:
src/platforms/posix/tests/hrt_test/hrt_test.h
src/platforms/posix/tests/hrt_test/hrt_test.cpp