PX4 Firmware: LPS25H Class Reference
LPS25H Class Reference
Public Member Functions
LPS25H (device::Device *interface, const char *path)
virtual ~LPS25H ()
virtual int init ()
Initialise the driver and make it ready for use.
virtual ssize_t read (struct file *filp, char *buffer, size_t buflen)
virtual int ioctl (struct file *filp, int cmd, unsigned long arg)
void print_info ()
Diagnostics - print some basic information about the driver.
Public Member Functions inherited from device::CDev
CDev (const char *name, const char *devname)
Constructor.
virtual ~CDev ()
virtual int open (file_t *filep)
Handle an open of the device.
virtual int close (file_t *filep)
Handle a close of the device.
virtual ssize_t read (file_t *filep, char *buffer, size_t buflen)
Perform a read from the device.
virtual ssize_t write (file_t *filep, const char *buffer, size_t buflen)
Perform a write to the device.
virtual off_t seek (file_t *filep, off_t offset, int whence)
Perform a logical seek operation on the device.
virtual int ioctl (file_t *filep, int cmd, unsigned long arg)
Perform an ioctl operation on the device.
virtual int poll (file_t *filep, px4_pollfd_struct_t *fds, bool setup)
Perform a poll setup/teardown operation.
Public Member Functions inherited from device::Device
virtual ~Device ()=default
Destructor.
virtual int read (unsigned address, void *data, unsigned count)
Read directly from the device.
virtual int write (unsigned address, void *data, unsigned count)
Write directly to the device.
virtual int ioctl (unsigned operation, unsigned &arg)
Perform a device-specific operation.
uint8_t get_device_bus ()
Return the bus ID the device is connected to.
DeviceBusType get_device_bus_type ()
Return the bus type the device is connected to.
uint8_t get_device_address ()
Return the bus address of the device.
void set_device_address (int address)
void set_device_type (uint8_t devtype)
Set the device type.
virtual bool external ()
Protected Attributes
Device * _interface
Protected Attributes inherited from device::CDev
px4_sem_t _lock
lock to protect access to all class members (also for derived classes)
bool _pub_blocked {false}
true if publishing should be blocked
Protected Attributes inherited from device::Device
union DeviceId _device_id
device identifier information
const char * _name
driver name
bool _debug_enabled {false}
if true, debug messages are printed
Private Member Functions
void start ()
Initialise the automatic measurement state machine and start it.
void stop ()
Stop the automatic measurement state machine.
int reset ()
Reset the device.
void cycle ()
Perform a poll cycle; collect from the previous measurement and start a new one.
int write_reg (uint8_t reg, uint8_t val)
Write a register.
int read_reg (uint8_t reg, uint8_t &val)
Read a register.
int measure ()
Issue a measurement command.
int collect ()
Collect the result of the most recent measurement.
LPS25H (const LPS25H &)
LPS25H operator= (const LPS25H &)
Static Private Member Functions
static void cycle_trampoline (void *arg)
Static trampoline from the workq context; because we don't have a generic workq wrapper yet.
Private Attributes
work_s _work {}
unsigned _measure_ticks {0}
ringbuffer::RingBuffer * _reports {nullptr}
bool _collect_phase {false}
orb_advert_t _baro_topic {nullptr}
int _orb_class_instance {-1}
int _class_instance {-1}
perf_counter_t _sample_perf
perf_counter_t _comms_errors
sensor_baro_s _last_report {}
used for info()
Additional Inherited Members
Public Types inherited from device::Device
enum DeviceBusType { DeviceBusType_UNKNOWN = 0, DeviceBusType_I2C = 1, DeviceBusType_SPI = 2, DeviceBusType_UAVCAN = 3 }
Device bus types for DEVID.
Protected Member Functions inherited from device::CDev
virtual pollevent_t poll_state (file_t *filep)
Check the current state of the device for poll events from the perspective of the file.
virtual void poll_notify (pollevent_t events)
Report new poll events.
virtual void poll_notify_one (px4_pollfd_struct_t *fds, pollevent_t events)
Internal implementation of poll_notify.
virtual int open_first (file_t *filep)
Notification of the first open.
virtual int close_last (file_t *filep)
Notification of the last close.
virtual int register_class_devname (const char *class_devname)
Register a class device name, automatically adding device class instance suffix if need be.
virtual int unregister_class_devname (const char *class_devname, unsigned class_instance)
Register a class device name, automatically adding device class instance suffix if need be.
const char * get_devname ()
Get the device name.
void lock ()
Take the driver lock.
void unlock ()
Release the driver lock.
Protected Member Functions inherited from device::Device
Device (const char *name)
Device (DeviceBusType bus_type, uint8_t bus, uint8_t address, uint8_t devtype=0)
Device (const Device &)=delete
Device & operator= (const Device &)=delete
Device (Device &&)=delete
Device & operator= (Device &&)=delete
Static Protected Attributes inherited from device::CDev
static const px4_file_operations_t fops = {}
Pointer to the default cdev file operations table; useful for registering clone devices etc.
Detailed Description
Definition at line 194 of file lps25h.cpp.
Constructor & Destructor Documentation
LPS25H::LPS25H (device::Device * interface, const char * path)
Definition at line 311 of file lps25h.cpp.
References device::Device::_device_id, _interface, device::Device::DeviceStructure::address, device::Device::DeviceStructure::bus, device::Device::DeviceStructure::bus_type, device::Device::DeviceId::devid_s, device::Device::DeviceStructure::devtype, and DRV_BARO_DEVTYPE_LPS25H.
Referenced by lps25h::start_bus().
LPS25H::~LPS25H () virtual
Definition at line 324 of file lps25h.cpp.
References _class_instance, _comms_errors, _interface, _reports, _sample_perf, BARO_BASE_DEVICE_PATH, perf_free(), stop(), and device::CDev::unregister_class_devname().
LPS25H::LPS25H (const LPS25H &) private
Member Function Documentation
int LPS25H::collect () private
Collect the result of the most recent measurement.
Definition at line 653 of file lps25h.cpp.
References _baro_topic, _comms_errors, device::Device::_device_id, _interface, _last_report, _orb_class_instance, device::CDev::_pub_blocked, _reports, _sample_perf, ADDR_STATUS_REG, baro_report, DEVICE_DEBUG, device::Device::DeviceId::devid, hrt_absolute_time(), OK, orb_advertise_multi(), ORB_ID, ORB_PRIO_HIGH, ORB_PRIO_MAX, orb_publish(), perf_begin(), perf_count(), perf_end(), perf_event_count(), device::CDev::poll_notify(), and status.
Referenced by cycle(), and read().
void LPS25H::cycle () private
Perform a poll cycle; collect from the previous measurement and start a new one.
This is the heart of the measurement state machine. This function alternately starts a measurement, or collects the data from the previous measurement.
When the interval between measurements is greater than the minimum measurement interval, a gap is inserted between collection and measurement to provide the most recent measurement possible at the next interval.
Definition at line 587 of file lps25h.cpp.
References _collect_phase, _measure_ticks, collect(), cycle_trampoline(), DEVICE_DEBUG, LPS25H_CONVERSION_INTERVAL, measure(), OK, and start().
Referenced by cycle_trampoline().
void LPS25H::cycle_trampoline (void * arg) static private
Static trampoline from the workq context; because we don't have a generic workq wrapper yet.
Parameters
arg Instance pointer for the driver that is polling.
Definition at line 579 of file lps25h.cpp.
References cycle().
Referenced by cycle(), and start().
int LPS25H::init () virtual
Initialise the driver and make it ready for use.
Returns
OK if the driver initialized OK, negative errno otherwise;
Reimplemented from device::CDev.
Definition at line 345 of file lps25h.cpp.
References _class_instance, _reports, BARO_BASE_DEVICE_PATH, DEVICE_DEBUG, lis3mdl::init(), OK, device::CDev::register_class_devname(), and reset().
int LPS25H::ioctl (struct file * filp, int cmd, unsigned long arg) virtual
Definition at line 438 of file lps25h.cpp.
References _interface, _measure_ticks, _reports, LPS25H_CONVERSION_INTERVAL, OK, reset(), SENSOR_POLLRATE_DEFAULT, SENSOR_POLLRATE_EXTERNAL, SENSOR_POLLRATE_MANUAL, SENSOR_POLLRATE_MAX, SENSORIOCGPOLLRATE, SENSORIOCRESET, SENSORIOCSPOLLRATE, SENSORIOCSQUEUEDEPTH, start(), and stop().
Referenced by lps25h::reset(), lps25h::start_bus(), and lps25h::test().
int LPS25H::measure () private
Issue a measurement command.
Returns
OK if the measurement command was successful.
Definition at line 636 of file lps25h.cpp.
References _comms_errors, ADDR_CTRL_REG2, CTRL_REG2_ONE_SHOT, OK, perf_count(), and write_reg().
Referenced by cycle(), and read().
LPS25H LPS25H::operator= (const LPS25H &) private
void LPS25H::print_info ()
Diagnostics - print some basic information about the driver.
Definition at line 751 of file lps25h.cpp.
References _comms_errors, _last_report, _measure_ticks, _reports, _sample_perf, and perf_print_counter().
Referenced by lps25h::info().
ssize_t LPS25H::read (struct file * filp, char * buffer, size_t buflen) virtual
Definition at line 379 of file lps25h.cpp.
References _measure_ticks, _reports, baro_report, collect(), LPS25H_CONVERSION_INTERVAL, measure(), OK, and usleep().
Referenced by lps25h::test().
int LPS25H::read_reg (uint8_t reg, uint8_t & val) private
Read a register.
Parameters
reg The register to read.
val The value read.
Returns
OK on read success.
Definition at line 742 of file lps25h.cpp.
References _interface.
int LPS25H::reset () private
Reset the device.
Definition at line 556 of file lps25h.cpp.
References ADDR_CTRL_REG1, ADDR_CTRL_REG2, CTRL_REG1_PD, CTRL_REG2_BOOT, CTRL_REG2_SWRESET, usleep(), and write_reg().
Referenced by init(), and ioctl().
void LPS25H::start () private
Initialise the automatic measurement state machine and start it.
Note
This function is called at open and error time. It might make sense to make it more aggressive about resetting the bus in case of errors.
Definition at line 539 of file lps25h.cpp.
References _collect_phase, _reports, and cycle_trampoline().
Referenced by cycle(), and ioctl().
void LPS25H::stop () private
Stop the automatic measurement state machine.
Definition at line 550 of file lps25h.cpp.
Referenced by ioctl(), and ~LPS25H().
int LPS25H::write_reg (uint8_t reg, uint8_t val) private
Write a register.
Parameters
reg The register to write.
val The value to write.
Returns
OK on write success.
Definition at line 735 of file lps25h.cpp.
References _interface.
Referenced by measure(), and reset().
Member Data Documentation
orb_advert_t LPS25H::_baro_topic {nullptr} private
Definition at line 220 of file lps25h.cpp.
Referenced by collect().
int LPS25H::_class_instance {-1} private
Definition at line 222 of file lps25h.cpp.
Referenced by init(), and ~LPS25H().
bool LPS25H::_collect_phase {false} private
Definition at line 218 of file lps25h.cpp.
Referenced by cycle(), and start().
perf_counter_t LPS25H::_comms_errors private
Definition at line 225 of file lps25h.cpp.
Referenced by collect(), measure(), print_info(), and ~LPS25H().
Device* LPS25H::_interface protected
Definition at line 211 of file lps25h.cpp.
Referenced by collect(), ioctl(), LPS25H(), read_reg(), write_reg(), and ~LPS25H().
sensor_baro_s LPS25H::_last_report {} private
used for info()
Definition at line 227 of file lps25h.cpp.
Referenced by collect(), and print_info().
unsigned LPS25H::_measure_ticks {0} private
Definition at line 215 of file lps25h.cpp.
Referenced by cycle(), ioctl(), print_info(), and read().
int LPS25H::_orb_class_instance {-1} private
Definition at line 221 of file lps25h.cpp.
Referenced by collect().
ringbuffer::RingBuffer* LPS25H::_reports {nullptr} private
Definition at line 217 of file lps25h.cpp.
Referenced by collect(), init(), ioctl(), print_info(), read(), start(), and ~LPS25H().
perf_counter_t LPS25H::_sample_perf private
Definition at line 224 of file lps25h.cpp.
Referenced by collect(), print_info(), and ~LPS25H().
work_s LPS25H::_work {} private
Definition at line 214 of file lps25h.cpp.
The documentation for this class was generated from the following file:
src/drivers/barometer/lps25h/lps25h.cpp