PX4 Firmware: FXOS8701CQ Class Reference
FXOS8701CQ Class Reference
Public Member Functions
FXOS8701CQ (int bus, const char *path, uint32_t device, enum Rotation rotation)
virtual ~FXOS8701CQ ()
virtual int init ()
virtual ssize_t read (struct file *filp, char *buffer, size_t buflen)
virtual int ioctl (struct file *filp, int cmd, unsigned long arg)
void print_info ()
Diagnostics - print some basic information about the driver.
void print_registers ()
dump register values
void test_error ()
deliberately trigger an error
Protected Member Functions
virtual int probe ()
virtual ssize_t mag_read (struct file *filp, char *buffer, size_t buflen)
virtual int mag_ioctl (struct file *filp, int cmd, unsigned long arg)
Private Member Functions
void start ()
Start automatic measurement.
void stop ()
Stop automatic measurement.
void reset ()
Reset chip.
void disable_i2c ()
disable I2C on the chip
void check_registers (void)
check key registers for correct values
void measure ()
Fetch accel measurements from the sensor and update the report ring.
void mag_measure ()
Fetch mag measurements from the sensor and update the report ring.
uint8_t read_reg (unsigned reg)
Read a register from the FXOS8701C.
void write_reg (unsigned reg, uint8_t value)
Write a register in the FXOS8701C.
void modify_reg (unsigned reg, uint8_t clearbits, uint8_t setbits)
Modify a register in the FXOS8701C.
void write_checked_reg (unsigned reg, uint8_t value)
Write a register in the FXOS8701C, updating _checked_values.
int accel_set_range (unsigned max_g)
Set the FXOS8701C accel measurement range.
int mag_set_range (unsigned max_g)
Set the FXOS8701C mag measurement range.
int accel_set_onchip_lowpass_filter_bandwidth (unsigned bandwidth)
Set the FXOS8701C on-chip anti-alias filter bandwith.
int accel_set_driver_lowpass_filter (float samplerate, float bandwidth)
Set the driver lowpass filter bandwidth.
int accel_set_samplerate (unsigned frequency)
Set the FXOS8701C internal accel and mag sampling frequency.
int mag_set_samplerate (unsigned frequency)
Set the FXOS8701CQ internal mag sampling frequency.
FXOS8701CQ (const FXOS8701CQ &)
FXOS8701CQ operator= (const FXOS8701CQ &)
Static Private Member Functions
static void measure_trampoline (void *arg)
Static trampoline from the hrt_call context; because we don't have a generic hrt wrapper yet.
static void mag_measure_trampoline (void *arg)
Static trampoline for the mag because it runs at a lower rate.
Private Attributes
FXOS8701CQ_mag * _mag
struct hrt_call _accel_call
struct hrt_call _mag_call
unsigned _call_accel_interval
unsigned _call_mag_interval
ringbuffer::RingBuffer * _accel_reports
ringbuffer::RingBuffer * _mag_reports
struct accel_calibration_s _accel_scale
unsigned _accel_range_m_s2
float _accel_range_scale
unsigned _accel_samplerate
unsigned _accel_onchip_filter_bandwith
struct mag_calibration_s _mag_scale
unsigned _mag_range_ga
float _mag_range_scale
unsigned _mag_samplerate
orb_advert_t _accel_topic
int _accel_orb_class_instance
int _accel_class_instance
unsigned _accel_read
unsigned _mag_read
perf_counter_t _accel_sample_perf
perf_counter_t _mag_sample_perf
perf_counter_t _bad_registers
perf_counter_t _bad_values
perf_counter_t _accel_duplicates
uint8_t _register_wait
math::LowPassFilter2p _accel_filter_x
math::LowPassFilter2p _accel_filter_y
math::LowPassFilter2p _accel_filter_z
Integrator _accel_int
enum Rotation _rotation
float _last_accel [3]
uint8_t _constant_accel_count
float _last_temperature
int16_t _last_raw_mag_x
int16_t _last_raw_mag_y
int16_t _last_raw_mag_z
uint8_t _checked_values [FXOS8701C_NUM_CHECKED_REGISTERS]
uint8_t _checked_next
Static Private Attributes
static const uint8_t _checked_registers [FXOS8701C_NUM_CHECKED_REGISTERS]
Friends
class FXOS8701CQ_mag
Detailed Description
Definition at line 155 of file fxos8701cq.cpp.
Constructor & Destructor Documentation
FXOS8701CQ::FXOS8701CQ (int bus, const char * path, uint32_t device, enum Rotation rotation)
Definition at line 454 of file fxos8701cq.cpp.
References _accel_class_instance, _accel_duplicates, _accel_filter_x, _accel_filter_y, _accel_filter_z, _accel_int, _accel_onchip_filter_bandwith, _accel_orb_class_instance, _accel_range_m_s2, _accel_range_scale, _accel_read, _accel_reports, _accel_sample_perf, _accel_samplerate, _accel_scale, _accel_topic, _bad_registers, _bad_values, _call_accel_interval, _call_mag_interval, _checked_next, _constant_accel_count, device::Device::_device_id, _last_raw_mag_x, _last_raw_mag_y, _last_raw_mag_z, _last_temperature, _mag, _mag_call, _mag_range_ga, _mag_range_scale, _mag_read, _mag_reports, _mag_sample_perf, _mag_samplerate, _mag_scale, _register_wait, _rotation, device::Device::DeviceId::devid, device::Device::DeviceId::devid_s, device::Device::DeviceStructure::devtype, DRV_ACC_DEVTYPE_FXOS8701C, DRV_MAG_DEVTYPE_FXOS8701C, f(), FXOS8701C_ACCEL_DEFAULT_DRIVER_FILTER_FREQ, FXOS8701C_ACCEL_DEFAULT_RATE, FXOS8701C_ACCEL_MAX_OUTPUT_RATE, PC_COUNT, PC_ELAPSED, perf_alloc, mag_calibration_s::x_offset, accel_calibration_s::x_offset, mag_calibration_s::x_scale, accel_calibration_s::x_scale, mag_calibration_s::y_offset, accel_calibration_s::y_offset, mag_calibration_s::y_scale, accel_calibration_s::y_scale, mag_calibration_s::z_offset, accel_calibration_s::z_offset, mag_calibration_s::z_scale, and accel_calibration_s::z_scale.
FXOS8701CQ::~FXOS8701CQ () virtual
Definition at line 522 of file fxos8701cq.cpp.
References _accel_class_instance, _accel_duplicates, _accel_reports, _accel_sample_perf, _bad_registers, _bad_values, _mag, _mag_reports, _mag_sample_perf, ACCEL_BASE_DEVICE_PATH, perf_free(), and stop().
FXOS8701CQ::FXOS8701CQ (const FXOS8701CQ &) private
Member Function Documentation
int FXOS8701CQ::accel_set_driver_lowpass_filter (float samplerate, float bandwidth) private
Set the driver lowpass filter bandwidth.
Parameters
bandwidth The anti-alias filter bandwidth in Hz Zero selects the highest bandwidth
Returns
OK if the value can be supported, -ERANGE otherwise.
Definition at line 1092 of file fxos8701cq.cpp.
References _accel_filter_x, _accel_filter_y, _accel_filter_z, OK, and math::LowPassFilter2p::set_cutoff_frequency().
Referenced by ioctl(), and reset().
int FXOS8701CQ::accel_set_onchip_lowpass_filter_bandwidth (unsigned bandwidth) private
Set the FXOS8701C on-chip anti-alias filter bandwith.
Parameters
bandwidth The anti-alias filter bandwidth in Hz Zero selects the highest bandwidth
Returns
OK if the value can be supported, -ERANGE otherwise.
Definition at line 1086 of file fxos8701cq.cpp.
References OK.
Referenced by reset().
int FXOS8701CQ::accel_set_range (unsigned max_g) private
Set the FXOS8701C accel measurement range.
Parameters
max_g The measurement range of the accel is in g (9.81m/s^2) Zero selects the maximum supported range.
Returns
OK if the value can be supported, -ERANGE otherwise.
Definition at line 1041 of file fxos8701cq.cpp.
References _accel_range_m_s2, _accel_range_scale, CONSTANTS_ONE_G, FXOS8701CQ_XYZ_DATA_CFG, modify_reg(), OK, XYZ_DATA_CFG_FS_2G, XYZ_DATA_CFG_FS_4G, XYZ_DATA_CFG_FS_8G, and XYZ_DATA_CFG_FS_MASK.
Referenced by ioctl(), and reset().
int FXOS8701CQ::accel_set_samplerate (unsigned frequency) private
Set the FXOS8701C internal accel and mag sampling frequency.
Parameters
frequency The internal accel and mag sampling frequency is set to not less than this value. Zero selects the maximum rate supported.
Returns
OK if the value can be supported.
Definition at line 1102 of file fxos8701cq.cpp.
References _accel_samplerate, ACCEL_SAMPLERATE_DEFAULT, CTRL_REG1_ACTIVE, CTRL_REG1_DR, CTRL_REG1_DR_MASK, FXOS8701C_ACCEL_DEFAULT_RATE, FXOS8701CQ_CTRL_REG1, modify_reg(), OK, and read_reg().
Referenced by ioctl(), and reset().
void FXOS8701CQ::check_registers (void) private
check key registers for correct values
Definition at line 1225 of file fxos8701cq.cpp.
References _bad_registers, _checked_next, _checked_registers, _checked_values, _register_wait, FXOS8701C_NUM_CHECKED_REGISTERS, perf_count(), read_reg(), and write_reg().
Referenced by measure().
void FXOS8701CQ::disable_i2c () private
disable I2C on the chip
int FXOS8701CQ::init () virtual
Definition at line 551 of file fxos8701cq.cpp.
References _accel_class_instance, _accel_orb_class_instance, _accel_reports, _accel_topic, _mag, FXOS8701CQ_mag::_mag_orb_class_instance, _mag_reports, FXOS8701CQ_mag::_mag_topic, ACCEL_BASE_DEVICE_PATH, accel_report, lis3mdl::init(), FXOS8701CQ_mag::init(), mag_report, measure(), OK, orb_advertise_multi(), ORB_ID, ORB_PRIO_DEFAULT, ORB_PRIO_LOW, ORB_PRIO_VERY_HIGH, PX4_ERR, PX4_ERROR, and reset().
Referenced by fxos8701cq::start().
int FXOS8701CQ::ioctl (struct file * filp, int cmd, unsigned long arg) virtual
Definition at line 752 of file fxos8701cq.cpp.
References _accel_call, _accel_filter_x, _accel_range_m_s2, _accel_reports, _accel_samplerate, _accel_scale, _call_accel_interval, accel_set_driver_lowpass_filter(), accel_set_range(), accel_set_samplerate(), ACCELIOCGRANGE, ACCELIOCGSAMPLERATE, ACCELIOCGSCALE, ACCELIOCSRANGE, ACCELIOCSSAMPLERATE, ACCELIOCSSCALE, CONSTANTS_ONE_G, f(), FXOS8701C_ACCEL_DEFAULT_RATE, FXOS8701C_TIMER_REDUCTION, math::LowPassFilter2p::get_cutoff_freq(), OK, hrt_call::period, reset(), SENSOR_POLLRATE_DEFAULT, SENSOR_POLLRATE_EXTERNAL, SENSOR_POLLRATE_MANUAL, SENSOR_POLLRATE_MAX, SENSORIOCGPOLLRATE, SENSORIOCRESET, SENSORIOCSPOLLRATE, SENSORIOCSQUEUEDEPTH, start(), stop(), accel_calibration_s::x_scale, accel_calibration_s::y_scale, and accel_calibration_s::z_scale.
int FXOS8701CQ::mag_ioctl (struct file * filp, int cmd, unsigned long arg) protected virtual
Definition at line 880 of file fxos8701cq.cpp.
References _call_mag_interval, _mag_call, _mag_reports, _mag_samplerate, _mag_scale, mag_set_samplerate(), MAGIOCGEXTERNAL, MAGIOCGSAMPLERATE, MAGIOCGSCALE, MAGIOCSSAMPLERATE, MAGIOCSSCALE, OK, hrt_call::period, reset(), SENSOR_POLLRATE_DEFAULT, SENSOR_POLLRATE_EXTERNAL, SENSOR_POLLRATE_MANUAL, SENSOR_POLLRATE_MAX, SENSORIOCGPOLLRATE, SENSORIOCRESET, SENSORIOCSPOLLRATE, SENSORIOCSQUEUEDEPTH, start(), and stop().
Referenced by FXOS8701CQ_mag::ioctl().
void FXOS8701CQ::mag_measure () private
Fetch mag measurements from the sensor and update the report ring.
Definition at line 1424 of file fxos8701cq.cpp.
References _bad_registers, _bad_values, device::Device::_device_id, _last_raw_mag_x, _last_raw_mag_y, _last_raw_mag_z, _last_temperature, _mag, _mag_range_scale, _mag_read, _mag_reports, _mag_sample_perf, _mag_scale, FXOS8701CQ_mag::_mag_topic, _rotation, device::Device::DeviceId::devid, hrt_absolute_time(), mag_report, ORB_ID, orb_publish(), perf_begin(), perf_end(), perf_event_count(), rotate_3f(), mag_calibration_s::x_offset, mag_calibration_s::x_scale, mag_calibration_s::y_offset, mag_calibration_s::y_scale, mag_calibration_s::z_offset, and mag_calibration_s::z_scale.
Referenced by mag_measure_trampoline(), and FXOS8701CQ_mag::measure().
void FXOS8701CQ::mag_measure_trampoline (void * arg) static private
Static trampoline for the mag because it runs at a lower rate.
Parameters
arg Instance pointer for the driver that is polling.
Definition at line 1216 of file fxos8701cq.cpp.
References mag_measure().
Referenced by FXOS8701CQ_mag::measure_trampoline(), and start().
ssize_t FXOS8701CQ::mag_read (struct file * filp, char * buffer, size_t buflen) protected virtual
Definition at line 711 of file fxos8701cq.cpp.
References _call_mag_interval, _mag, _mag_reports, mag_report, and FXOS8701CQ_mag::measure().
Referenced by FXOS8701CQ_mag::read().
int FXOS8701CQ::mag_set_range (unsigned max_g) private
Set the FXOS8701C mag measurement range.
Parameters
max_ga The measurement range of the mag is in Ga Zero selects the maximum supported range.
Returns
OK if the value can be supported, -ERANGE otherwise.
Definition at line 1077 of file fxos8701cq.cpp.
References _mag_range_ga, _mag_range_scale, and OK.
Referenced by reset().
int FXOS8701CQ::mag_set_samplerate (unsigned frequency) private
Set the FXOS8701CQ internal mag sampling frequency.
Parameters
frequency The mag reporting frequency is set to not less than this value. (sampling is all way the same as accel Zero selects the maximum rate supported.
Returns
OK if the value can be supported.
Definition at line 1145 of file fxos8701cq.cpp.
References _mag_samplerate, and OK.
Referenced by mag_ioctl().
void FXOS8701CQ::measure () private
Fetch accel measurements from the sensor and update the report ring.
Definition at line 1256 of file fxos8701cq.cpp.
References _accel_duplicates, _accel_filter_x, _accel_filter_y, _accel_filter_z, _accel_int, _accel_range_scale, _accel_read, _accel_reports, _accel_sample_perf, _accel_scale, _accel_topic, _bad_registers, _bad_values, _constant_accel_count, _last_accel, _last_raw_mag_x, _last_raw_mag_y, _last_raw_mag_z, _last_temperature, _register_wait, _rotation, accel_report, ADDR_7, math::LowPassFilter2p::apply(), check_registers(), DIR_READ, DR_STATUS_ZYXDR, f(), FXOS8701CQ_DR_STATUS, FXOS8701CQ_TEMP, hrt_absolute_time(), ORB_ID, orb_publish(), perf_begin(), perf_count(), perf_end(), perf_event_count(), Integrator::put(), read_reg(), rotate_3f(), status, swap16, swap16RightJustify14, accel_calibration_s::x_offset, accel_calibration_s::x_scale, accel_calibration_s::y_offset, accel_calibration_s::y_scale, accel_calibration_s::z_offset, and accel_calibration_s::z_scale.
Referenced by init(), measure_trampoline(), and read().
void FXOS8701CQ::measure_trampoline (void * arg) static private
Static trampoline from the hrt_call context; because we don't have a generic hrt wrapper yet.
Called by the HRT in interrupt context at the specified rate if automatic polling is enabled.
Parameters
arg Instance pointer for the driver that is polling.
Definition at line 1207 of file fxos8701cq.cpp.
References measure().
Referenced by start().
void FXOS8701CQ::modify_reg (unsigned reg, uint8_t clearbits, uint8_t setbits) private
Modify a register in the FXOS8701C.
Bits are cleared before bits are set.
Parameters
reg The register to modify.
clearbits Bits in the register to clear.
setbits Bits in the register to set.
Definition at line 1030 of file fxos8701cq.cpp.
References read_reg(), and write_checked_reg().
Referenced by accel_set_range(), and accel_set_samplerate().
FXOS8701CQ FXOS8701CQ::operator= (const FXOS8701CQ &) private
void FXOS8701CQ::print_info ()
Diagnostics - print some basic information about the driver.
Definition at line 1488 of file fxos8701cq.cpp.
References _accel_duplicates, _accel_read, _accel_reports, _accel_sample_perf, _bad_registers, _bad_values, _checked_next, _checked_registers, _checked_values, _last_temperature, _mag_read, _mag_reports, _mag_sample_perf, FXOS8701C_NUM_CHECKED_REGISTERS, perf_print_counter(), and read_reg().
Referenced by fxos8701cq::info().
void FXOS8701CQ::print_registers ()
dump register values
Definition at line 1516 of file fxos8701cq.cpp.
References DEF_REG, FXOS8701CQ_CTRL_REG1, FXOS8701CQ_CTRL_REG2, FXOS8701CQ_DR_STATUS, FXOS8701CQ_M_CTRL_REG1, FXOS8701CQ_M_CTRL_REG2, FXOS8701CQ_M_CTRL_REG3, FXOS8701CQ_M_DR_STATUS, FXOS8701CQ_M_OUT_X_MSB, FXOS8701CQ_OUT_X_MSB, FXOS8701CQ_WHOAMI, FXOS8701CQ_XYZ_DATA_CFG, name, and read_reg().
Referenced by fxos8701cq::regdump().
int FXOS8701CQ::probe () protected virtual
Definition at line 657 of file fxos8701cq.cpp.
References _checked_values, FXOS8700CQ_WHOAMI_VAL, FXOS8701CQ_WHOAMI, FXOS8701CQ_WHOAMI_VAL, OK, and read_reg().
ssize_t FXOS8701CQ::read (struct file * filp, char * buffer, size_t buflen) virtual
Definition at line 672 of file fxos8701cq.cpp.
References _accel_reports, _call_accel_interval, accel_report, and measure().
uint8_t FXOS8701CQ::read_reg (unsigned reg) private
Read a register from the FXOS8701C.
Parameters
The register to read.
Returns
The value that was read.
Definition at line 992 of file fxos8701cq.cpp.
References ADDR_7, and DIR_READ.
Referenced by accel_set_samplerate(), check_registers(), measure(), modify_reg(), print_info(), print_registers(), and probe().
void FXOS8701CQ::reset () private
Reset chip.
Resets the chip and measurements ranges, but not scale and offset.
Definition at line 620 of file fxos8701cq.cpp.
References _accel_read, _mag_read, accel_set_driver_lowpass_filter(), accel_set_onchip_lowpass_filter_bandwidth(), accel_set_range(), accel_set_samplerate(), CTRL_REG1_ACTIVE, CTRL_REG1_DR, CTRL_REG2_AUTO_INC, FXOS8701C_ACCEL_DEFAULT_DRIVER_FILTER_FREQ, FXOS8701C_ACCEL_DEFAULT_ONCHIP_FILTER_FREQ, FXOS8701C_ACCEL_DEFAULT_RANGE_G, FXOS8701C_ACCEL_DEFAULT_RATE, FXOS8701C_MAG_DEFAULT_RANGE_GA, FXOS8701CQ_CTRL_REG1, FXOS8701CQ_M_CTRL_REG1, FXOS8701CQ_M_CTRL_REG2, FXOS8701CQ_XYZ_DATA_CFG, M_CTRL_REG1_HMS_AM, M_CTRL_REG1_OS, mag_set_range(), and write_checked_reg().
Referenced by init(), ioctl(), and mag_ioctl().
void FXOS8701CQ::start () private
Start automatic measurement.
Definition at line 1175 of file fxos8701cq.cpp.
References _accel_call, _accel_reports, _call_accel_interval, _call_mag_interval, _mag_call, _mag_reports, FXOS8701C_TIMER_REDUCTION, hrt_call_every(), mag_measure_trampoline(), measure_trampoline(), and stop().
Referenced by ioctl(), and mag_ioctl().
void FXOS8701CQ::stop () private
Stop automatic measurement.
Definition at line 1193 of file fxos8701cq.cpp.
References _accel_call, _accel_reports, _last_accel, _mag_call, _mag_reports, and hrt_cancel().
Referenced by ioctl(), mag_ioctl(), start(), and ~FXOS8701CQ().
void FXOS8701CQ::test_error ()
deliberately trigger an error
Definition at line 1541 of file fxos8701cq.cpp.
References FXOS8701CQ_CTRL_REG1, and write_reg().
Referenced by fxos8701cq::test_error().
void FXOS8701CQ::write_checked_reg (unsigned reg, uint8_t value) private
Write a register in the FXOS8701C, updating _checked_values.
Parameters
reg The register to write.
value The new value to write.
Definition at line 1018 of file fxos8701cq.cpp.
References _checked_registers, _checked_values, FXOS8701C_NUM_CHECKED_REGISTERS, and write_reg().
Referenced by modify_reg(), and reset().
void FXOS8701CQ::write_reg (unsigned reg, uint8_t value) private
Write a register in the FXOS8701C.
Parameters
reg The register to write.
value The new value to write.
Definition at line 1006 of file fxos8701cq.cpp.
References ADDR_7, and DIR_WRITE.
Referenced by check_registers(), test_error(), and write_checked_reg().
Friends And Related Function Documentation
friend class FXOS8701CQ_mag friend
Definition at line 184 of file fxos8701cq.cpp.
Member Data Documentation
struct hrt_call FXOS8701CQ::_accel_call private
Definition at line 193 of file fxos8701cq.cpp.
Referenced by ioctl(), start(), and stop().
int FXOS8701CQ::_accel_class_instance private
Definition at line 215 of file fxos8701cq.cpp.
Referenced by FXOS8701CQ(), init(), and ~FXOS8701CQ().
perf_counter_t FXOS8701CQ::_accel_duplicates private
Definition at line 224 of file fxos8701cq.cpp.
Referenced by FXOS8701CQ(), measure(), print_info(), and ~FXOS8701CQ().
math::LowPassFilter2p FXOS8701CQ::_accel_filter_x private
Definition at line 228 of file fxos8701cq.cpp.
Referenced by accel_set_driver_lowpass_filter(), FXOS8701CQ(), ioctl(), and measure().
math::LowPassFilter2p FXOS8701CQ::_accel_filter_y private
Definition at line 229 of file fxos8701cq.cpp.
Referenced by accel_set_driver_lowpass_filter(), FXOS8701CQ(), and measure().
math::LowPassFilter2p FXOS8701CQ::_accel_filter_z private
Definition at line 230 of file fxos8701cq.cpp.
Referenced by accel_set_driver_lowpass_filter(), FXOS8701CQ(), and measure().
Integrator FXOS8701CQ::_accel_int private
Definition at line 232 of file fxos8701cq.cpp.
Referenced by FXOS8701CQ(), and measure().
unsigned FXOS8701CQ::_accel_onchip_filter_bandwith private
Definition at line 206 of file fxos8701cq.cpp.
Referenced by FXOS8701CQ().
int FXOS8701CQ::_accel_orb_class_instance private
Definition at line 214 of file fxos8701cq.cpp.
Referenced by FXOS8701CQ(), and init().
unsigned FXOS8701CQ::_accel_range_m_s2 private
Definition at line 203 of file fxos8701cq.cpp.
Referenced by accel_set_range(), FXOS8701CQ(), and ioctl().
float FXOS8701CQ::_accel_range_scale private
Definition at line 204 of file fxos8701cq.cpp.
Referenced by accel_set_range(), FXOS8701CQ(), and measure().
unsigned FXOS8701CQ::_accel_read private
Definition at line 217 of file fxos8701cq.cpp.
Referenced by FXOS8701CQ(), measure(), print_info(), and reset().
ringbuffer::RingBuffer* FXOS8701CQ::_accel_reports private
Definition at line 199 of file fxos8701cq.cpp.
Referenced by FXOS8701CQ(), init(), ioctl(), measure(), print_info(), read(), start(), stop(), and ~FXOS8701CQ().
perf_counter_t FXOS8701CQ::_accel_sample_perf private
Definition at line 220 of file fxos8701cq.cpp.
Referenced by FXOS8701CQ(), measure(), print_info(), and ~FXOS8701CQ().
unsigned FXOS8701CQ::_accel_samplerate private
Definition at line 205 of file fxos8701cq.cpp.
Referenced by accel_set_samplerate(), FXOS8701CQ(), and ioctl().
struct accel_calibration_s FXOS8701CQ::_accel_scale private
Definition at line 202 of file fxos8701cq.cpp.
Referenced by FXOS8701CQ(), ioctl(), and measure().
orb_advert_t FXOS8701CQ::_accel_topic private
Definition at line 213 of file fxos8701cq.cpp.
Referenced by FXOS8701CQ(), init(), and measure().
perf_counter_t FXOS8701CQ::_bad_registers private
Definition at line 222 of file fxos8701cq.cpp.
Referenced by check_registers(), FXOS8701CQ(), mag_measure(), measure(), print_info(), and ~FXOS8701CQ().
perf_counter_t FXOS8701CQ::_bad_values private
Definition at line 223 of file fxos8701cq.cpp.
Referenced by FXOS8701CQ(), mag_measure(), measure(), print_info(), and ~FXOS8701CQ().
unsigned FXOS8701CQ::_call_accel_interval private
Definition at line 196 of file fxos8701cq.cpp.
Referenced by FXOS8701CQ(), ioctl(), read(), and start().
unsigned FXOS8701CQ::_call_mag_interval private
Definition at line 197 of file fxos8701cq.cpp.
Referenced by FXOS8701CQ(), mag_ioctl(), mag_read(), and start().
uint8_t FXOS8701CQ::_checked_next private
Definition at line 252 of file fxos8701cq.cpp.
Referenced by check_registers(), FXOS8701CQ(), and print_info().
const uint8_t FXOS8701CQ::_checked_registers static private
Initial value:
= {
    FXOS8701CQ_WHOAMI,
    FXOS8701CQ_XYZ_DATA_CFG,
    FXOS8701CQ_CTRL_REG1,
    FXOS8701CQ_M_CTRL_REG1,
    FXOS8701CQ_M_CTRL_REG2,
}
Definition at line 250 of file fxos8701cq.cpp.
Referenced by check_registers(), print_info(), and write_checked_reg().
uint8_t FXOS8701CQ::_checked_values[FXOS8701C_NUM_CHECKED_REGISTERS] private
Definition at line 251 of file fxos8701cq.cpp.
Referenced by check_registers(), print_info(), probe(), and write_checked_reg().
uint8_t FXOS8701CQ::_constant_accel_count private
Definition at line 238 of file fxos8701cq.cpp.
Referenced by FXOS8701CQ(), and measure().
float FXOS8701CQ::_last_accel[3] private
Definition at line 237 of file fxos8701cq.cpp.
Referenced by measure(), and stop().
int16_t FXOS8701CQ::_last_raw_mag_x private
Definition at line 242 of file fxos8701cq.cpp.
Referenced by FXOS8701CQ(), mag_measure(), and measure().
int16_t FXOS8701CQ::_last_raw_mag_y private
Definition at line 243 of file fxos8701cq.cpp.
Referenced by FXOS8701CQ(), mag_measure(), and measure().
int16_t FXOS8701CQ::_last_raw_mag_z private
Definition at line 244 of file fxos8701cq.cpp.
Referenced by FXOS8701CQ(), mag_measure(), and measure().
float FXOS8701CQ::_last_temperature private
Definition at line 241 of file fxos8701cq.cpp.
Referenced by FXOS8701CQ(), mag_measure(), measure(), and print_info().
FXOS8701CQ_mag* FXOS8701CQ::_mag private
Definition at line 191 of file fxos8701cq.cpp.
Referenced by FXOS8701CQ(), init(), mag_measure(), mag_read(), and ~FXOS8701CQ().
struct hrt_call FXOS8701CQ::_mag_call private
Definition at line 194 of file fxos8701cq.cpp.
Referenced by FXOS8701CQ(), mag_ioctl(), start(), and stop().
unsigned FXOS8701CQ::_mag_range_ga private
Definition at line 209 of file fxos8701cq.cpp.
Referenced by FXOS8701CQ(), and mag_set_range().
float FXOS8701CQ::_mag_range_scale private
Definition at line 210 of file fxos8701cq.cpp.
Referenced by FXOS8701CQ(), mag_measure(), and mag_set_range().
unsigned FXOS8701CQ::_mag_read private
Definition at line 218 of file fxos8701cq.cpp.
Referenced by FXOS8701CQ(), mag_measure(), print_info(), and reset().
ringbuffer::RingBuffer* FXOS8701CQ::_mag_reports private
Definition at line 200 of file fxos8701cq.cpp.
Referenced by FXOS8701CQ(), init(), mag_ioctl(), mag_measure(), mag_read(), print_info(), start(), stop(), and ~FXOS8701CQ().
perf_counter_t FXOS8701CQ::_mag_sample_perf private
Definition at line 221 of file fxos8701cq.cpp.
Referenced by FXOS8701CQ(), mag_measure(), print_info(), and ~FXOS8701CQ().
unsigned FXOS8701CQ::_mag_samplerate private
Definition at line 211 of file fxos8701cq.cpp.
Referenced by FXOS8701CQ(), mag_ioctl(), and mag_set_samplerate().
struct mag_calibration_s FXOS8701CQ::_mag_scale private
Definition at line 208 of file fxos8701cq.cpp.
Referenced by FXOS8701CQ(), mag_ioctl(), and mag_measure().
uint8_t FXOS8701CQ::_register_wait private
Definition at line 226 of file fxos8701cq.cpp.
Referenced by check_registers(), FXOS8701CQ(), and measure().
enum Rotation FXOS8701CQ::_rotation private
Definition at line 234 of file fxos8701cq.cpp.
Referenced by FXOS8701CQ(), mag_measure(), and measure().
The documentation for this class was generated from the following file:
src/drivers/imu/fxos8701cq/fxos8701cq.cpp