PX4 Firmware: src/drivers/roboclaw/RoboClaw.cpp File Reference
RoboClaw.cpp File Reference
RoboClaw Motor Driver.
#include "RoboClaw.hpp"
#include <poll.h>
#include <stdio.h>
#include <math.h>
#include <string.h>
#include <fcntl.h>
#include <termios.h>
#include <systemlib/err.h>
#include <systemlib/mavlink_log.h>
#include <arch/board/board.h>
#include <uORB/Publication.hpp>
#include <uORB/topics/debug_key_value.h>
#include <drivers/drv_hrt.h>
Functions
int roboclawTest (const char *deviceName, uint8_t address, uint16_t pulsesPerRev)
Detailed Description
RoboClaw Motor Driver.
references: http://downloads.orionrobotics.com/downloads/datasheets/motor_controller_robo_claw_R0401.pdf
Definition in file RoboClaw.cpp.
Function Documentation
int roboclawTest (const char * deviceName, uint8_t address, uint16_t pulsesPerRev)
Definition at line 345 of file RoboClaw.cpp.
References RoboClaw::MOTOR_1, RoboClaw::MOTOR_2, RoboClaw::printStatus(), RoboClaw::readEncoder(), RoboClaw::setMotorDutyCycle(), and usleep().
Referenced by roboclaw_main().