PX4 Firmware: DfAK8963Wrapper Class Reference
DfAK8963Wrapper Class Reference
Classes
struct mag_calibration_s
Public Member Functions
DfAK8963Wrapper (enum Rotation rotation)
~DfAK8963Wrapper ()
int start ()
Start automatic measurement.
int stop ()
Stop automatic measurement.
void print_calibration ()
Private Member Functions
int _publish (struct mag_sensor_data &data)
void _update_mag_calibration ()
Private Attributes
orb_advert_t _mag_topic
int _param_update_sub
struct DfAK8963Wrapper::mag_calibration_s _mag_calibration
matrix::Dcmf _rotation_matrix
int _mag_orb_class_instance
perf_counter_t _mag_sample_perf
Detailed Description
Definition at line 73 of file df_ak8963_wrapper.cpp.
Constructor & Destructor Documentation
DfAK8963Wrapper::DfAK8963Wrapper (enum Rotation rotation)
Definition at line 122 of file df_ak8963_wrapper.cpp.
References _mag_calibration, _mag_orb_class_instance, _mag_sample_perf, _rotation_matrix, get_rot_matrix(), PC_ELAPSED, perf_alloc, DfAK8963Wrapper::mag_calibration_s::x_offset, DfAK8963Wrapper::mag_calibration_s::x_scale, DfAK8963Wrapper::mag_calibration_s::y_offset, DfAK8963Wrapper::mag_calibration_s::y_scale, DfAK8963Wrapper::mag_calibration_s::z_offset, and DfAK8963Wrapper::mag_calibration_s::z_scale.
Referenced by df_ak8963_wrapper::start().
DfAK8963Wrapper::~DfAK8963Wrapper ()
Definition at line 142 of file df_ak8963_wrapper.cpp.
References _mag_sample_perf, and perf_free().
Member Function Documentation
int DfAK8963Wrapper::_publish (struct mag_sensor_data & data) private
Definition at line 263 of file df_ak8963_wrapper.cpp.
References _mag_calibration, _mag_orb_class_instance, _mag_sample_perf, _mag_topic, _param_update_sub, _rotation_matrix, _update_mag_calibration(), hrt_absolute_time(), mag_report, orb_advertise_multi(), orb_check(), orb_copy(), ORB_ID, ORB_PRIO_HIGH, orb_publish(), perf_begin(), perf_end(), DfAK8963Wrapper::mag_calibration_s::x_offset, DfAK8963Wrapper::mag_calibration_s::x_scale, DfAK8963Wrapper::mag_calibration_s::y_offset, DfAK8963Wrapper::mag_calibration_s::y_scale, DfAK8963Wrapper::mag_calibration_s::z_offset, and DfAK8963Wrapper::mag_calibration_s::z_scale.
void DfAK8963Wrapper::_update_mag_calibration () private
Definition at line 188 of file df_ak8963_wrapper.cpp.
References _mag_calibration, device_id, OK, param_find(), param_get(), PX4_ERR, DfAK8963Wrapper::mag_calibration_s::x_offset, DfAK8963Wrapper::mag_calibration_s::x_scale, DfAK8963Wrapper::mag_calibration_s::y_offset, DfAK8963Wrapper::mag_calibration_s::y_scale, DfAK8963Wrapper::mag_calibration_s::z_offset, and DfAK8963Wrapper::mag_calibration_s::z_scale.
Referenced by _publish(), and start().
void DfAK8963Wrapper::print_calibration ()
Definition at line 253 of file df_ak8963_wrapper.cpp.
References _mag_calibration, PX4_INFO, DfAK8963Wrapper::mag_calibration_s::x_offset, DfAK8963Wrapper::mag_calibration_s::x_scale, DfAK8963Wrapper::mag_calibration_s::y_offset, DfAK8963Wrapper::mag_calibration_s::y_scale, DfAK8963Wrapper::mag_calibration_s::z_offset, and DfAK8963Wrapper::mag_calibration_s::z_scale.
Referenced by df_ak8963_wrapper::info().
int DfAK8963Wrapper::start ()
Start automatic measurement.
Returns
0 on success
Definition at line 147 of file df_ak8963_wrapper.cpp.
References _param_update_sub, _update_mag_calibration(), lis3mdl::init(), ORB_ID, orb_subscribe(), PX4_ERR, and start().
Referenced by df_ak8963_wrapper::start().
int DfAK8963Wrapper::stop ()
Stop automatic measurement.
Returns
0 on success
Definition at line 175 of file df_ak8963_wrapper.cpp.
References PX4_ERR, and stop().
Referenced by df_ak8963_wrapper::stop().
Member Data Documentation
struct DfAK8963Wrapper::mag_calibration_s DfAK8963Wrapper::_mag_calibration private
Referenced by _publish(), _update_mag_calibration(), DfAK8963Wrapper(), and print_calibration().
int DfAK8963Wrapper::_mag_orb_class_instance private
Definition at line 116 of file df_ak8963_wrapper.cpp.
Referenced by _publish(), and DfAK8963Wrapper().
perf_counter_t DfAK8963Wrapper::_mag_sample_perf private
Definition at line 118 of file df_ak8963_wrapper.cpp.
Referenced by _publish(), DfAK8963Wrapper(), and ~DfAK8963Wrapper().
orb_advert_t DfAK8963Wrapper::_mag_topic private
Definition at line 101 of file df_ak8963_wrapper.cpp.
Referenced by _publish().
int DfAK8963Wrapper::_param_update_sub private
Definition at line 103 of file df_ak8963_wrapper.cpp.
Referenced by _publish(), and start().
matrix::Dcmf DfAK8963Wrapper::_rotation_matrix private
Definition at line 114 of file df_ak8963_wrapper.cpp.
Referenced by _publish(), and DfAK8963Wrapper().
The documentation for this class was generated from the following file:
src/platforms/posix/drivers/df_ak8963_wrapper/df_ak8963_wrapper.cpp