PX4 Firmware: px4::bst::BST Class Reference
px4::bst::BST Class Reference
Public Member Functions
BST (int bus)
virtual ~BST ()
virtual int init ()
virtual int probe ()
virtual int info ()
virtual int ioctl (device::file_t *filp, int cmd, unsigned long arg)
work_s * work_ptr ()
void stop ()
Static Public Member Functions
static void start_trampoline (void *arg)
Private Member Functions
void start ()
void cycle ()
template<typename T >
void send_packet (BSTPacket< T > &packet)
template<typename T_SEND , typename T_RECV >
void send_packet (BSTPacket< T_SEND > &packet_send, BSTPacket< T_RECV > &packet_recv)
uint16_t swap_uint16 (uint16_t val)
Byte swap unsigned short.
int16_t swap_int16 (int16_t val)
Byte swap short.
uint32_t swap_uint32 (uint32_t val)
Byte swap unsigned int.
int32_t swap_int32 (int32_t val)
Byte swap int.
Static Private Member Functions
static void cycle_trampoline (void *arg)
static uint8_t crc8 (uint8_t *data, size_t len)
Private Attributes
work_s _work = {}
bool _should_run = false
unsigned _interval = 100
int _gps_sub
int _attitude_sub
int _battery_sub
Detailed Description
Definition at line 114 of file bst.cpp.
Constructor & Destructor Documentation
px4::bst::BST::BST (int bus)
Definition at line 198 of file bst.cpp.
Referenced by bst_main().
px4::bst::BST::~BST () virtual
Definition at line 207 of file bst.cpp.
References _should_run.
Member Function Documentation
uint8_t px4::bst::BST::crc8 (uint8_t * data, size_t len) static private
Definition at line 347 of file bst.cpp.
Referenced by probe().
void px4::bst::BST::cycle () private
Definition at line 286 of file bst.cpp.
References _attitude_sub, _battery_sub, _gps_sub, _interval, _should_run, vehicle_gps_position_s::alt, px4::bst::BSTGPSPosition::alt, px4::bst::BSTBattery::capacity, vehicle_gps_position_s::cog_rad, px4::bst::BSTBattery::current, battery_status_s::current_a, cycle_trampoline(), battery_status_s::discharged_mah, vehicle_gps_position_s::eph, vehicle_gps_position_s::fix_type, gps, px4::bst::BSTGPSPosition::gs, px4::bst::BSTGPSPosition::heading, vehicle_gps_position_s::lat, px4::bst::BSTGPSPosition::lat, vehicle_gps_position_s::lon, px4::bst::BSTGPSPosition::lon, M_PI_F, orb_check(), orb_copy(), ORB_ID, px4::bst::BSTPacket< T >::payload, matrix::Euler< Type >::phi(), px4::bst::BSTAttitude::pitch, matrix::Euler< Type >::psi(), vehicle_attitude_s::q, px4::bst::BSTAttitude::roll, vehicle_gps_position_s::satellites_used, px4::bst::BSTGPSPosition::sats, send_packet(), swap_int16(), swap_int32(), swap_uint16(), matrix::Euler< Type >::theta(), px4::bst::BSTPacket< T >::type, vehicle_gps_position_s::vel_m_s, px4::bst::BSTBattery::voltage, battery_status_s::voltage_v, and px4::bst::BSTAttitude::yaw.
Referenced by cycle_trampoline().
void px4::bst::BST::cycle_trampoline (void * arg) static private
Definition at line 281 of file bst.cpp.
References cycle().
Referenced by cycle(), and start().
virtual int px4::bst::BST::info () inline virtual
Definition at line 125 of file bst.cpp.
int px4::bst::BST::init () virtual
Definition at line 249 of file bst.cpp.
References lis3mdl::init(), OK, and start_trampoline().
Referenced by bst_main().
virtual int px4::bst::BST::ioctl (device::file_t * filp, int cmd, unsigned long arg) inline virtual
Definition at line 127 of file bst.cpp.
int px4::bst::BST::probe () virtual
Definition at line 214 of file bst.cpp.
References px4::bst::BSTDeviceInfoRequest::cmd, crc8(), px4::bst::BSTDeviceInfoReply::dev_name, px4::bst::BSTDeviceInfoReply::dev_name_len, px4::bst::BSTDeviceInfoReply::fw_id, px4::bst::BSTDeviceInfoReply::hw_id, px4::bst::BSTPacket< T >::length, OK, px4::bst::BSTPacket< T >::payload, send_packet(), swap_uint16(), swap_uint32(), px4::bst::BSTPacket< T >::type, and warnx.
template<typename T > void px4::bst::BST::send_packet (BSTPacket< T > & packet) inline private
Definition at line 150 of file bst.cpp.
References px4::bst::BSTPacket< T >::crc, crc8(), px4::bst::BSTPacket< T >::length, and px4::bst::BSTPacket< T >::type.
Referenced by cycle(), and probe().
template<typename T_SEND , typename T_RECV > void px4::bst::BST::send_packet (BSTPacket< T_SEND > & packet_send, BSTPacket< T_RECV > & packet_recv) inline private
Definition at line 159 of file bst.cpp.
References px4::bst::BSTPacket< T >::crc, crc8(), data, px4::bst::BSTPacket< T >::length, and px4::bst::BSTPacket< T >::type.
void px4::bst::BST::start () private
Definition at line 268 of file bst.cpp.
References _attitude_sub, _battery_sub, _gps_sub, _should_run, cycle_trampoline(), ORB_ID, and orb_subscribe().
Referenced by start_trampoline().
void px4::bst::BST::start_trampoline (void * arg) static
Definition at line 263 of file bst.cpp.
References start().
Referenced by init().
void px4::bst::BST::stop ()
int16_t px4::bst::BST::swap_int16 (int16_t val) inline private
Byte swap short.
Definition at line 176 of file bst.cpp.
Referenced by cycle().
int32_t px4::bst::BST::swap_int32 (int32_t val) inline private
Byte swap int.
Definition at line 189 of file bst.cpp.
Referenced by cycle().
uint16_t px4::bst::BST::swap_uint16 (uint16_t val) inline private
Byte swap unsigned short.
Definition at line 170 of file bst.cpp.
Referenced by cycle(), and probe().
uint32_t px4::bst::BST::swap_uint32 (uint32_t val) inline private
Byte swap unsigned int.
Definition at line 182 of file bst.cpp.
Referenced by probe().
work_s* px4::bst::BST::work_ptr () inline
Definition at line 129 of file bst.cpp.
References stop().
Member Data Documentation
int px4::bst::BST::_attitude_sub private
Definition at line 140 of file bst.cpp.
Referenced by cycle(), and start().
int px4::bst::BST::_battery_sub private
Definition at line 141 of file bst.cpp.
Referenced by cycle(), and start().
int px4::bst::BST::_gps_sub private
Definition at line 139 of file bst.cpp.
Referenced by cycle(), and start().
unsigned px4::bst::BST::_interval = 100 private
Definition at line 138 of file bst.cpp.
Referenced by cycle().
bool px4::bst::BST::_should_run = false private
Definition at line 137 of file bst.cpp.
Referenced by cycle(), start(), and ~BST().
work_s px4::bst::BST::_work = {} private
Definition at line 136 of file bst.cpp.
The documentation for this class was generated from the following file:
src/drivers/telemetry/bst/bst.cpp