PX4 Firmware: AirspeedSim Class Reference
AirspeedSim Class Reference abstract
#include <airspeedsim.h>
Public Member Functions
AirspeedSim (int bus, int address, unsigned conversion_interval, const char *path)
virtual ~AirspeedSim ()
virtual int init ()
Initialise the driver and make it ready for use.
virtual ssize_t read (device::file_t *filp, char *buffer, size_t buflen)
Perform a read from the device.
virtual int ioctl (device::file_t *filp, int cmd, unsigned long arg)
Perform an ioctl operation on the device.
virtual void print_info ()
Diagnostics - print some basic information about the driver.
Public Member Functions inherited from device::CDev
CDev (const char *name, const char *devname)
Constructor.
virtual ~CDev ()
virtual int open (file_t *filep)
Handle an open of the device.
virtual int close (file_t *filep)
Handle a close of the device.
virtual ssize_t write (file_t *filep, const char *buffer, size_t buflen)
Perform a write to the device.
virtual off_t seek (file_t *filep, off_t offset, int whence)
Perform a logical seek operation on the device.
virtual int poll (file_t *filep, px4_pollfd_struct_t *fds, bool setup)
Perform a poll setup/teardown operation.
Public Member Functions inherited from device::Device
virtual ~Device ()=default
Destructor.
virtual int read (unsigned address, void *data, unsigned count)
Read directly from the device.
virtual int write (unsigned address, void *data, unsigned count)
Write directly to the device.
virtual int ioctl (unsigned operation, unsigned &arg)
Perform a device-specific operation.
uint8_t get_device_bus ()
Return the bus ID the device is connected to.
DeviceBusType get_device_bus_type ()
Return the bus type the device is connected to.
uint8_t get_device_address ()
Return the bus address of the device.
void set_device_address (int address)
void set_device_type (uint8_t devtype)
Set the device type.
virtual bool external ()
Protected Member Functions
virtual int probe ()
virtual void cycle ()=0
Perform a poll cycle; collect from the previous measurement and start a new one.
virtual int measure ()=0
virtual int collect ()=0
virtual int transfer (const uint8_t *send, unsigned send_len, uint8_t *recv, unsigned recv_len)
int probe_address (uint8_t address)
Test whether the device supported by the driver is present at a specific address.
void start ()
Initialise the automatic measurement state machine and start it.
void stop ()
Stop the automatic measurement state machine.
void new_report (const differential_pressure_s &report)
add a new report to the reports queue
Protected Member Functions inherited from device::CDev
virtual pollevent_t poll_state (file_t *filep)
Check the current state of the device for poll events from the perspective of the file.
virtual void poll_notify (pollevent_t events)
Report new poll events.
virtual void poll_notify_one (px4_pollfd_struct_t *fds, pollevent_t events)
Internal implementation of poll_notify.
virtual int open_first (file_t *filep)
Notification of the first open.
virtual int close_last (file_t *filep)
Notification of the last close.
virtual int register_class_devname (const char *class_devname)
Register a class device name, automatically adding device class instance suffix if need be.
virtual int unregister_class_devname (const char *class_devname, unsigned class_instance)
Register a class device name, automatically adding device class instance suffix if need be.
const char * get_devname ()
Get the device name.
void lock ()
Take the driver lock.
void unlock ()
Release the driver lock.
Protected Member Functions inherited from device::Device
Device (const char *name)
Device (DeviceBusType bus_type, uint8_t bus, uint8_t address, uint8_t devtype=0)
Device (const Device &)=delete
Device & operator= (const Device &)=delete
Device (Device &&)=delete
Device & operator= (Device &&)=delete
Static Protected Member Functions
static void cycle_trampoline (void *arg)
Static trampoline from the workq context; because we don't have a generic workq wrapper yet.
Protected Attributes
struct work_s _work
bool _sensor_ok
int _measure_ticks
bool _collect_phase
float _diff_pres_offset
orb_advert_t _airspeed_pub
int _class_instance
int _conversion_interval
perf_counter_t _sample_perf
perf_counter_t _comms_errors
Protected Attributes inherited from device::CDev
px4_sem_t _lock
lock to protect access to all class members (also for derived classes)
bool _pub_blocked {false}
true if publishing should be blocked
Protected Attributes inherited from device::Device
union DeviceId _device_id
device identifier information
const char * _name
driver name
bool _debug_enabled {false}
if true, debug messages are printed
Private Member Functions
AirspeedSim (const AirspeedSim &)
AirspeedSim & operator= (const AirspeedSim &)
Private Attributes
ringbuffer::RingBuffer * _reports
unsigned _retries
Additional Inherited Members
Public Types inherited from device::Device
enum DeviceBusType { DeviceBusType_UNKNOWN = 0, DeviceBusType_I2C = 1, DeviceBusType_SPI = 2, DeviceBusType_UAVCAN = 3 }
Device bus types for DEVID.
Static Protected Attributes inherited from device::CDev
static const px4_file_operations_t fops = {}
Pointer to the default cdev file operations table; useful for registering clone devices etc.
Detailed Description
Definition at line 79 of file airspeedsim.h.
Constructor & Destructor Documentation
AirspeedSim::AirspeedSim (int bus, int address, unsigned conversion_interval, const char * path)
Definition at line 72 of file airspeedsim.cpp.
References device::Device::_debug_enabled.
AirspeedSim::~AirspeedSim () virtual
Definition at line 93 of file airspeedsim.cpp.
References _class_instance, _comms_errors, _reports, _sample_perf, AIRSPEED_BASE_DEVICE_PATH, perf_free(), stop(), and device::CDev::unregister_class_devname().
AirspeedSim::AirspeedSim (const AirspeedSim &) private
Member Function Documentation
virtual int AirspeedSim::collect () protected pure virtual
Implemented in MEASAirspeedSim.
Referenced by read().
virtual void AirspeedSim::cycle () protected pure virtual
Perform a poll cycle; collect from the previous measurement and start a new one.
Implemented in MEASAirspeedSim.
Referenced by cycle_trampoline().
void AirspeedSim::cycle_trampoline (void * arg) static protected
Static trampoline from the workq context; because we don't have a generic workq wrapper yet.
Parameters
arg Instance pointer for the driver that is polling.
Definition at line 360 of file airspeedsim.cpp.
References cycle().
Referenced by MEASAirspeedSim::cycle(), and start().
int AirspeedSim::init () virtual
Initialise the driver and make it ready for use.
Returns
OK if the driver initialized OK, negative errno otherwise;
Reimplemented from device::CDev.
Definition at line 113 of file airspeedsim.cpp.
References _airspeed_pub, _class_instance, _reports, AIRSPEED_BASE_DEVICE_PATH, CLASS_DEVICE_PRIMARY, DEVICE_DEBUG, lis3mdl::init(), measure(), OK, orb_advertise(), ORB_ID, PX4_WARN, and device::CDev::register_class_devname().
int AirspeedSim::ioctl (device::file_t * filep, int cmd, unsigned long arg) virtual
Perform an ioctl operation on the device.
The default implementation handles DIOC_GETPRIV, and otherwise returns -ENOTTY. Subclasses should call the default implementation for any command they do not handle themselves.
Parameters
filep Pointer to the NuttX file structure.
cmd The ioctl command value.
arg The ioctl argument value.
Returns
OK on success, or -errno otherwise.
Reimplemented from device::CDev.
Definition at line 171 of file airspeedsim.cpp.
References _conversion_interval, _diff_pres_offset, _measure_ticks, _reports, AIRSPEEDIOCGSCALE, AIRSPEEDIOCSSCALE, airspeed_scale::offset_pa, OK, airspeed_scale::scale, SENSOR_POLLRATE_DEFAULT, SENSOR_POLLRATE_EXTERNAL, SENSOR_POLLRATE_MANUAL, SENSOR_POLLRATE_MAX, SENSORIOCGPOLLRATE, SENSORIOCRESET, SENSORIOCSPOLLRATE, SENSORIOCSQUEUEDEPTH, start(), and stop().
Referenced by meas_airspeed_sim::reset(), and meas_airspeed_sim::test().
virtual int AirspeedSim::measure () protected pure virtual
Implemented in MEASAirspeedSim.
Referenced by init(), probe(), and read().
void AirspeedSim::new_report (const differential_pressure_s & report) protected
add a new report to the reports queue
Parameters
report differential_pressure_s report
Definition at line 377 of file airspeedsim.cpp.
References _reports.
Referenced by MEASAirspeedSim::collect().
AirspeedSim& AirspeedSim::operator= (const AirspeedSim &) private
void AirspeedSim::print_info (void) virtual
Diagnostics - print some basic information about the driver.
Definition at line 368 of file airspeedsim.cpp.
References _comms_errors, _measure_ticks, _reports, _sample_perf, perf_print_counter(), and PX4_INFO.
Referenced by meas_airspeed_sim::info().
int AirspeedSim::probe () protected virtual
Definition at line 156 of file airspeedsim.cpp.
References _retries, and measure().
int AirspeedSim::probe_address (uint8_t address) protected
Test whether the device supported by the driver is present at a specific address.
Parameters
address The I2C bus address to probe.
Returns
True if the device is present.
ssize_t AirspeedSim::read (device::file_t * filep, char * buffer, size_t buflen) virtual
Perform a read from the device.
The default implementation returns -ENOSYS.
Parameters
filep Pointer to the NuttX file structure.
buffer Pointer to the buffer into which data should be placed.
buflen The number of bytes to be read.
Returns
The number of bytes read or -errno otherwise.
Reimplemented from device::CDev.
Definition at line 283 of file airspeedsim.cpp.
References _conversion_interval, _measure_ticks, _reports, collect(), measure(), OK, and usleep().
Referenced by meas_airspeed_sim::test().
void AirspeedSim::start () protected
Initialise the automatic measurement state machine and start it.
Note
This function is called at open and error time. It might make sense to make it more aggressive about resetting the bus in case of errors.
Definition at line 343 of file airspeedsim.cpp.
References _collect_phase, _reports, and cycle_trampoline().
Referenced by MEASAirspeedSim::cycle(), and ioctl().
void AirspeedSim::stop () protected
Stop the automatic measurement state machine.
Definition at line 354 of file airspeedsim.cpp.
Referenced by ioctl(), and ~AirspeedSim().
int AirspeedSim::transfer (const uint8_t * send, unsigned send_len, uint8_t * recv, unsigned recv_len) protected virtual
Definition at line 383 of file airspeedsim.cpp.
References Simulator::getAirspeedSample(), Simulator::getInstance(), PX4_DEBUG, and PX4_ERR.
Referenced by MEASAirspeedSim::collect(), and MEASAirspeedSim::measure().
Member Data Documentation
orb_advert_t AirspeedSim::_airspeed_pub protected
Definition at line 124 of file airspeedsim.h.
Referenced by MEASAirspeedSim::collect(), and init().
int AirspeedSim::_class_instance protected
Definition at line 126 of file airspeedsim.h.
Referenced by init(), and ~AirspeedSim().
bool AirspeedSim::_collect_phase protected
Definition at line 121 of file airspeedsim.h.
Referenced by MEASAirspeedSim::cycle(), and start().
perf_counter_t AirspeedSim::_comms_errors protected
Definition at line 131 of file airspeedsim.h.
Referenced by MEASAirspeedSim::collect(), MEASAirspeedSim::measure(), print_info(), and ~AirspeedSim().
int AirspeedSim::_conversion_interval protected
Definition at line 128 of file airspeedsim.h.
Referenced by ioctl(), and read().
float AirspeedSim::_diff_pres_offset protected
Definition at line 122 of file airspeedsim.h.
Referenced by ioctl().
int AirspeedSim::_measure_ticks protected
Definition at line 120 of file airspeedsim.h.
Referenced by MEASAirspeedSim::cycle(), ioctl(), print_info(), and read().
ringbuffer::RingBuffer* AirspeedSim::_reports private
Definition at line 96 of file airspeedsim.h.
Referenced by init(), ioctl(), new_report(), print_info(), read(), start(), and ~AirspeedSim().
unsigned AirspeedSim::_retries private
Definition at line 98 of file airspeedsim.h.
Referenced by probe().
perf_counter_t AirspeedSim::_sample_perf protected
Definition at line 130 of file airspeedsim.h.
Referenced by MEASAirspeedSim::collect(), print_info(), and ~AirspeedSim().
bool AirspeedSim::_sensor_ok protected
Definition at line 119 of file airspeedsim.h.
Referenced by MEASAirspeedSim::cycle().
struct work_s AirspeedSim::_work protected
Definition at line 118 of file airspeedsim.h.
The documentation for this class was generated from the following files:
src/modules/simulator/airspeedsim/airspeedsim.h
src/modules/simulator/airspeedsim/airspeedsim.cpp