PX4 Firmware: MavlinkStreamAttPosMocap Class Reference
MavlinkStreamAttPosMocap Class Reference
Public Member Functions
const char * get_name () const
uint16_t get_id ()
unsigned get_size ()
Get maximal total messages size on update.
Public Member Functions inherited from MavlinkStream
MavlinkStream (Mavlink *mavlink)
virtual ~MavlinkStream ()=default
MavlinkStream (const MavlinkStream &)=delete
MavlinkStream & operator= (const MavlinkStream &)=delete
MavlinkStream (MavlinkStream &&)=delete
MavlinkStream & operator= (MavlinkStream &&)=delete
void set_interval (const int interval)
Get the interval.
int get_interval ()
Get the interval.
int update (const hrt_abstime &t)
Update subscriptions and send message if necessary.
virtual bool const_rate ()
virtual unsigned get_size_avg ()
Get the average message size.
bool first_message_sent () const
void reset_last_sent ()
Reset the time of last sent to 0.
Static Public Member Functions
static const char * get_name_static ()
static uint16_t get_id_static ()
static MavlinkStream * new_instance (Mavlink *mavlink)
Protected Member Functions
MavlinkStreamAttPosMocap (Mavlink *mavlink)
bool send (const hrt_abstime t)
Protected Member Functions inherited from MavlinkStream
virtual void update_data ()
Function to collect/update data for the streams at a high rate independant of actual stream rate.
Private Member Functions
MavlinkStreamAttPosMocap (MavlinkStreamAttPosMocap &)=delete
MavlinkStreamAttPosMocap & operator= (const MavlinkStreamAttPosMocap &)=delete
Private Attributes
MavlinkOrbSubscription * _mocap_sub
uint64_t _mocap_time
Additional Inherited Members
Public Attributes inherited from MavlinkStream
MavlinkStream * next {nullptr}
Protected Attributes inherited from MavlinkStream
Mavlink *const _mavlink
int _interval {1000000}
if set to negative value = unlimited rate
Detailed Description
Definition at line 2299 of file mavlink_messages.cpp.
Constructor & Destructor Documentation
MavlinkStreamAttPosMocap::MavlinkStreamAttPosMocap (MavlinkStreamAttPosMocap &) private delete
MavlinkStreamAttPosMocap::MavlinkStreamAttPosMocap (Mavlink * mavlink) inline explicit protected
Definition at line 2341 of file mavlink_messages.cpp.
Member Function Documentation
uint16_t MavlinkStreamAttPosMocap::get_id () inline virtual
Implements MavlinkStream.
Definition at line 2317 of file mavlink_messages.cpp.
References MavlinkStreamHeartbeat::get_id_static().
static uint16_t MavlinkStreamAttPosMocap::get_id_static () inline static
Definition at line 2312 of file mavlink_messages.cpp.
const char* MavlinkStreamAttPosMocap::get_name () const inline virtual
Implements MavlinkStream.
Definition at line 2302 of file mavlink_messages.cpp.
References get_name_static().
static const char* MavlinkStreamAttPosMocap::get_name_static () inline static
Definition at line 2307 of file mavlink_messages.cpp.
Referenced by get_name().
unsigned MavlinkStreamAttPosMocap::get_size () inline virtual
Get maximal total messages size on update.
Implements MavlinkStream.
Definition at line 2327 of file mavlink_messages.cpp.
static MavlinkStream* MavlinkStreamAttPosMocap::new_instance (Mavlink * mavlink) inline static
Definition at line 2322 of file mavlink_messages.cpp.
MavlinkStreamAttPosMocap& MavlinkStreamAttPosMocap::operator= (const MavlinkStreamAttPosMocap &) private delete
bool MavlinkStreamAttPosMocap::send (const hrt_abstime t) inline protected virtual
Implements MavlinkStream.
Definition at line 2346 of file mavlink_messages.cpp.
References MavlinkStream::_mavlink, Mavlink::get_channel(), msg, att_pos_mocap_s::q, att_pos_mocap_s::timestamp, MavlinkOrbSubscription::update(), att_pos_mocap_s::x, att_pos_mocap_s::y, and att_pos_mocap_s::z.
Member Data Documentation
MavlinkOrbSubscription* MavlinkStreamAttPosMocap::_mocap_sub private
Definition at line 2333 of file mavlink_messages.cpp.
uint64_t MavlinkStreamAttPosMocap::_mocap_time private
Definition at line 2334 of file mavlink_messages.cpp.
The documentation for this class was generated from the following file:
src/modules/mavlink/mavlink_messages.cpp