PX4 Firmware: src/drivers/boards/mindpx-v2/spi.c File Reference
spi.c File Reference
#include <px4_config.h>
#include <stdint.h>
#include <stdbool.h>
#include <debug.h>
#include <nuttx/spi/spi.h>
#include <arch/board/board.h>
#include <up_arch.h>
#include <chip.h>
#include <stm32.h>
#include "board_config.h"
#include <systemlib/err.h>
Functions
__EXPORT void weak_function stm32_spiinitialize (void)
__EXPORT void stm32_spi4select (FAR struct spi_dev_s *dev, uint32_t devid, bool selected)
__EXPORT uint8_t stm32_spi4status (FAR struct spi_dev_s *dev, uint32_t devid)
__EXPORT void stm32_spi1select (FAR struct spi_dev_s *dev, uint32_t devid, bool selected)
__EXPORT uint8_t stm32_spi1status (FAR struct spi_dev_s *dev, uint32_t devid)
__EXPORT void board_spi_reset (int ms)
Function Documentation
__EXPORT void board_spi_reset (int ms)
Definition at line 173 of file spi.c.
References GPIO_ACCEL_DRDY_OFF, GPIO_EXTI_MPU_DRDY_OFF, GPIO_GYRO_DRDY_OFF, GPIO_MAG_DRDY_OFF, GPIO_SPI4_MISO_OFF, GPIO_SPI4_MOSI_OFF, GPIO_SPI4_SCK_OFF, GPIO_SPI_CS_ACCEL_MAG, GPIO_SPI_CS_ACCEL_MAG_OFF, GPIO_SPI_CS_BARO, GPIO_SPI_CS_BARO_OFF, GPIO_SPI_CS_FRAM, GPIO_SPI_CS_GYRO, GPIO_SPI_CS_GYRO_OFF, GPIO_SPI_CS_MPU, GPIO_SPI_CS_MPU_OFF, usleep(), and warnx.
__EXPORT void stm32_spi1select (FAR struct spi_dev_s * dev, uint32_t devid, bool selected)
Definition at line 148 of file spi.c.
References GPIO_SPI_CS_FRAM.
__EXPORT uint8_t stm32_spi1status (FAR struct spi_dev_s * dev, uint32_t devid)
Definition at line 154 of file spi.c.
References GPIO_SPI_CS_EXT0, stm32_spi2select(), and stm32_spi2status().
__EXPORT void stm32_spi4select (FAR struct spi_dev_s * dev, uint32_t devid, bool selected)
Definition at line 100 of file spi.c.
References GPIO_SPI_CS_ACCEL_MAG, GPIO_SPI_CS_BARO, GPIO_SPI_CS_GYRO, GPIO_SPI_CS_MPU, PX4_SPIDEV_ACCEL_MAG, PX4_SPIDEV_BARO, PX4_SPIDEV_GYRO, and PX4_SPIDEV_MPU.
__EXPORT uint8_t stm32_spi4status (FAR struct spi_dev_s * dev, uint32_t devid)
Definition at line 143 of file spi.c.
__EXPORT void weak_function stm32_spiinitialize (void)
Definition at line 71 of file spi.c.
References GPIO_EXTI_ACCEL_DRDY, GPIO_EXTI_GYRO_DRDY, GPIO_EXTI_MAG_DRDY, GPIO_EXTI_MPU_DRDY, GPIO_SPI_CS_ACCEL_MAG, GPIO_SPI_CS_BARO, GPIO_SPI_CS_EXT0, GPIO_SPI_CS_FRAM, GPIO_SPI_CS_GYRO, and GPIO_SPI_CS_MPU.