PX4 Firmware: MPU9250_mag Class Reference
MPU9250_mag Class Reference
Helper class implementing the magnetometer driver node.
#include <mag.h>
Public Member Functions
MPU9250_mag (MPU9250 *parent, device::Device *interface, const char *path)
~MPU9250_mag ()
virtual ssize_t read (struct file *filp, char *buffer, size_t buflen)
virtual int ioctl (struct file *filp, int cmd, unsigned long arg)
virtual int init ()
Initialise the driver and make it ready for use.
void set_passthrough (uint8_t reg, uint8_t size, uint8_t *out=NULL)
void passthrough_read (uint8_t reg, uint8_t *buf, uint8_t size)
void passthrough_write (uint8_t reg, uint8_t val)
void read_block (uint8_t reg, uint8_t *val, uint8_t count)
int ak8963_reset (void)
int ak8963_setup (void)
int ak8963_setup_master_i2c (void)
bool ak8963_check_id (uint8_t &id)
bool ak8963_read_adjustments (void)
Public Member Functions inherited from device::CDev
CDev (const char *name, const char *devname)
Constructor.
virtual ~CDev ()
virtual int open (file_t *filep)
Handle an open of the device.
virtual int close (file_t *filep)
Handle a close of the device.
virtual ssize_t read (file_t *filep, char *buffer, size_t buflen)
Perform a read from the device.
virtual ssize_t write (file_t *filep, const char *buffer, size_t buflen)
Perform a write to the device.
virtual off_t seek (file_t *filep, off_t offset, int whence)
Perform a logical seek operation on the device.
virtual int ioctl (file_t *filep, int cmd, unsigned long arg)
Perform an ioctl operation on the device.
virtual int poll (file_t *filep, px4_pollfd_struct_t *fds, bool setup)
Perform a poll setup/teardown operation.
Public Member Functions inherited from device::Device
virtual ~Device ()=default
Destructor.
virtual int read (unsigned address, void *data, unsigned count)
Read directly from the device.
virtual int write (unsigned address, void *data, unsigned count)
Write directly to the device.
virtual int ioctl (unsigned operation, unsigned &arg)
Perform a device-specific operation.
uint8_t get_device_bus ()
Return the bus ID the device is connected to.
DeviceBusType get_device_bus_type ()
Return the bus type the device is connected to.
uint8_t get_device_address ()
Return the bus address of the device.
void set_device_address (int address)
void set_device_type (uint8_t devtype)
Set the device type.
virtual bool external ()
Protected Member Functions
void measure ()
void _measure (struct ak8963_regs data)
uint8_t read_reg (unsigned reg)
void write_reg (unsigned reg, uint8_t value)
bool is_passthrough ()
int self_test (void)
Protected Member Functions inherited from device::CDev
virtual pollevent_t poll_state (file_t *filep)
Check the current state of the device for poll events from the perspective of the file.
virtual void poll_notify (pollevent_t events)
Report new poll events.
virtual void poll_notify_one (px4_pollfd_struct_t *fds, pollevent_t events)
Internal implementation of poll_notify.
virtual int open_first (file_t *filep)
Notification of the first open.
virtual int close_last (file_t *filep)
Notification of the last close.
virtual int register_class_devname (const char *class_devname)
Register a class device name, automatically adding device class instance suffix if need be.
virtual int unregister_class_devname (const char *class_devname, unsigned class_instance)
Register a class device name, automatically adding device class instance suffix if need be.
const char * get_devname ()
Get the device name.
void lock ()
Take the driver lock.
void unlock ()
Release the driver lock.
Protected Member Functions inherited from device::Device
Device (const char *name)
Device (DeviceBusType bus_type, uint8_t bus, uint8_t address, uint8_t devtype=0)
Device (const Device &)=delete
Device & operator= (const Device &)=delete
Device (Device &&)=delete
Device & operator= (Device &&)=delete
Protected Attributes
Device * _interface
Protected Attributes inherited from device::CDev
px4_sem_t _lock
lock to protect access to all class members (also for derived classes)
bool _pub_blocked {false}
true if publishing should be blocked
Protected Attributes inherited from device::Device
union DeviceId _device_id
device identifier information
const char * _name
driver name
bool _debug_enabled {false}
if true, debug messages are printed
Private Member Functions
bool check_duplicate (uint8_t *mag_data)
MPU9250_mag (const MPU9250_mag &)
MPU9250_mag operator= (const MPU9250_mag &)
Private Attributes
MPU9250 * _parent
orb_advert_t _mag_topic
int _mag_orb_class_instance
int _mag_class_instance
bool _mag_reading_data
ringbuffer::RingBuffer * _mag_reports
struct mag_calibration_s _mag_scale
float _mag_range_scale
perf_counter_t _mag_reads
perf_counter_t _mag_errors
perf_counter_t _mag_overruns
perf_counter_t _mag_overflows
perf_counter_t _mag_duplicates
float _mag_asa_x
float _mag_asa_y
float _mag_asa_z
uint8_t _last_mag_data [6]
Friends
class MPU9250
Additional Inherited Members
Public Types inherited from device::Device
enum DeviceBusType { DeviceBusType_UNKNOWN = 0, DeviceBusType_I2C = 1, DeviceBusType_SPI = 2, DeviceBusType_UAVCAN = 3 }
Device bus types for DEVID.
Static Protected Attributes inherited from device::CDev
static const px4_file_operations_t fops = {}
Pointer to the default cdev file operations table; useful for registering clone devices etc.
Detailed Description
Helper class implementing the magnetometer driver node.
Definition at line 92 of file mag.h.
Constructor & Destructor Documentation
MPU9250_mag::MPU9250_mag (MPU9250 * parent, device::Device * interface, const char * path)
Definition at line 74 of file mag.cpp.
References _last_mag_data, _mag_asa_x, _mag_asa_y, _mag_asa_z, _mag_duplicates, _mag_errors, _mag_overflows, _mag_overruns, _mag_range_scale, _mag_reads, _mag_scale, MPU9250_MAG_RANGE_GA, PC_COUNT, perf_alloc, mag_calibration_s::x_offset, mag_calibration_s::x_scale, mag_calibration_s::y_offset, mag_calibration_s::y_scale, mag_calibration_s::z_offset, and mag_calibration_s::z_scale.
MPU9250_mag::~MPU9250_mag ()
Definition at line 106 of file mag.cpp.
References _mag_class_instance, _mag_duplicates, _mag_errors, _mag_overflows, _mag_overruns, _mag_reads, _mag_reports, _mag_topic, MAG_BASE_DEVICE_PATH, orb_unadvertise(), perf_free(), and device::CDev::unregister_class_devname().
MPU9250_mag::MPU9250_mag (const MPU9250_mag &) private
Member Function Documentation
void MPU9250_mag::_measure (struct ak8963_regs data) protected
Definition at line 184 of file mag.cpp.
References device::Device::_device_id, MPU9250::_last_temperature, MPU9250::_mag, _mag_asa_x, _mag_asa_y, _mag_asa_z, _mag_duplicates, _mag_errors, _mag_overflows, _mag_overruns, _mag_range_scale, _mag_reports, _mag_scale, _mag_topic, _parent, device::CDev::_pub_blocked, MPU9250::_rotation, check_duplicate(), device::Device::DeviceId::devid, hrt_absolute_time(), mag_report, ORB_ID, orb_publish(), perf_count(), perf_event_count(), device::CDev::poll_notify(), rotate_3f(), ak8963_regs::st1, ak8963_regs::st2, ak8963_regs::x, mag_calibration_s::x_offset, mag_calibration_s::x_scale, ak8963_regs::y, mag_calibration_s::y_offset, mag_calibration_s::y_scale, ak8963_regs::z, mag_calibration_s::z_offset, and mag_calibration_s::z_scale.
Referenced by measure(), and MPU9250::measure().
bool MPU9250_mag::ak8963_check_id (uint8_t & id)
Definition at line 438 of file mag.cpp.
References AK8963_DEVICE_ID, AK8963REG_WIA, and read_reg().
Referenced by ak8963_setup().
bool MPU9250_mag::ak8963_read_adjustments (void)
Definition at line 493 of file mag.cpp.
References _interface, _mag_asa_x, _mag_asa_y, _mag_asa_z, AK8963_16BIT_ADC, AK8963_FUZE_MODE, AK8963_POWERDOWN_MODE, AK8963REG_ASAX, AK8963REG_CNTL1, f(), passthrough_read(), usleep(), and write_reg().
Referenced by ak8963_setup().
int MPU9250_mag::ak8963_reset (void)
Definition at line 474 of file mag.cpp.
References AK8963_RESET, ak8963_setup(), AK8963REG_CNTL2, OK, and write_reg().
Referenced by MPU9250::init(), ioctl(), and MPU9250::reset().
int MPU9250_mag::ak8963_setup (void)
Definition at line 544 of file mag.cpp.
References _interface, _parent, AK8963_16BIT_ADC, ak8963_check_id(), AK8963_CONTINUOUS_MODE2, ak8963_read_adjustments(), AK8963_RESET, ak8963_setup_master_i2c(), AK8963REG_CNTL1, AK8963REG_CNTL2, AK8963REG_ST1, BIT_I2C_MST_EN, BIT_I2C_MST_RST, MPU9250::modify_checked_reg(), MPU9250::modify_reg(), MPUREG_I2C_MST_CTRL, MPUREG_USER_CTRL, OK, PX4_ERR, set_passthrough(), write_reg(), and MPU9250::write_reg().
Referenced by ak8963_reset().
int MPU9250_mag::ak8963_setup_master_i2c (void)
Definition at line 527 of file mag.cpp.
References _interface, _parent, BIT_I2C_MST_EN, BIT_I2C_MST_P_NSR, BIT_I2C_MST_WAIT_FOR_ES, BITS_I2C_MST_CLOCK_400HZ, MPU9250::modify_checked_reg(), MPUREG_I2C_MST_CTRL, MPUREG_USER_CTRL, OK, and MPU9250::write_reg().
Referenced by ak8963_setup().
bool MPU9250_mag::check_duplicate (uint8_t * mag_data) private
Definition at line 161 of file mag.cpp.
References _last_mag_data.
Referenced by _measure().
int MPU9250_mag::init () virtual
Initialise the driver and make it ready for use.
Returns
OK if the driver initialized OK, negative errno otherwise;
Reimplemented from device::CDev.
Definition at line 126 of file mag.cpp.
References _mag_class_instance, _mag_orb_class_instance, _mag_reports, _mag_topic, DEVICE_DEBUG, lis3mdl::init(), MAG_BASE_DEVICE_PATH, mag_report, OK, orb_advertise_multi(), ORB_ID, ORB_PRIO_LOW, PX4_ERR, and device::CDev::register_class_devname().
Referenced by MPU9250::init().
int MPU9250_mag::ioctl (struct file * filp, int cmd, unsigned long arg) virtual
Definition at line 291 of file mag.cpp.
References _mag_reports, _mag_scale, ak8963_reset(), MAGIOCGSAMPLERATE, MAGIOCGSCALE, MAGIOCSSAMPLERATE, MAGIOCSSCALE, MPU9250_AK8963_SAMPLE_RATE, OK, SENSOR_POLLRATE_DEFAULT, SENSOR_POLLRATE_EXTERNAL, SENSOR_POLLRATE_MANUAL, SENSOR_POLLRATE_MAX, SENSORIOCGPOLLRATE, SENSORIOCRESET, SENSORIOCSPOLLRATE, and SENSORIOCSQUEUEDEPTH.
bool MPU9250_mag::is_passthrough () inline protected
Definition at line 129 of file mag.h.
References MPU9250::self_test().
Referenced by MPU9250::init(), MPU9250::measure(), and MPU9250::reset_mpu().
void MPU9250_mag::measure () protected
Definition at line 174 of file mag.cpp.
References _interface, _measure(), AK8963REG_ST1, and OK.
Referenced by MPU9250::measure().
MPU9250_mag MPU9250_mag::operator= (const MPU9250_mag &) private
void MPU9250_mag::passthrough_read (uint8_t reg, uint8_t * buf, uint8_t size)
Definition at line 413 of file mag.cpp.
References _parent, MPUREG_EXT_SENS_DATA_00, MPUREG_I2C_SLV0_CTRL, read_block(), set_passthrough(), usleep(), and MPU9250::write_reg().
Referenced by ak8963_read_adjustments(), and read_reg().
void MPU9250_mag::passthrough_write (uint8_t reg, uint8_t val)
Definition at line 449 of file mag.cpp.
References _parent, MPUREG_I2C_SLV0_CTRL, set_passthrough(), usleep(), and MPU9250::write_reg().
Referenced by write_reg().
ssize_t MPU9250_mag::read (struct file * filp, char * buffer, size_t buflen) virtual
Definition at line 248 of file mag.cpp.
References MPU9250::_call_interval, _mag_reads, _mag_reports, _parent, mag_report, MPU9250::measure(), and perf_count().
void MPU9250_mag::read_block (uint8_t reg, uint8_t * val, uint8_t count)
Definition at line 407 of file mag.cpp.
References MPU9250::_interface, and _parent.
Referenced by passthrough_read().
uint8_t MPU9250_mag::read_reg (unsigned reg) protected
Definition at line 422 of file mag.cpp.
References _interface, and passthrough_read().
Referenced by ak8963_check_id().
int MPU9250_mag::self_test (void) protected
void MPU9250_mag::set_passthrough (uint8_t reg, uint8_t size, uint8_t * out = NULL)
Definition at line 387 of file mag.cpp.
References _parent, AK8963_I2C_ADDR, BIT_I2C_READ_FLAG, BIT_I2C_SLV0_EN, MPUREG_I2C_SLV0_ADDR, MPUREG_I2C_SLV0_CTRL, MPUREG_I2C_SLV0_D0, MPUREG_I2C_SLV0_REG, and MPU9250::write_reg().
Referenced by ak8963_setup(), passthrough_read(), and passthrough_write().
void MPU9250_mag::write_reg (unsigned reg, uint8_t value) protected
Definition at line 459 of file mag.cpp.
References _interface, MPU9250_LOW_SPEED_OP, and passthrough_write().
Referenced by ak8963_read_adjustments(), ak8963_reset(), and ak8963_setup().
Friends And Related Function Documentation
friend class MPU9250 friend
Definition at line 116 of file mag.h.
Member Data Documentation
Device* MPU9250_mag::_interface protected
Definition at line 114 of file mag.h.
Referenced by ak8963_read_adjustments(), ak8963_setup(), ak8963_setup_master_i2c(), MPU9250::init(), measure(), read_reg(), and write_reg().
uint8_t MPU9250_mag::_last_mag_data[6] private
Definition at line 154 of file mag.h.
Referenced by check_duplicate(), and MPU9250_mag().
float MPU9250_mag::_mag_asa_x private
Definition at line 147 of file mag.h.
Referenced by _measure(), ak8963_read_adjustments(), and MPU9250_mag().
float MPU9250_mag::_mag_asa_y private
Definition at line 148 of file mag.h.
Referenced by _measure(), ak8963_read_adjustments(), and MPU9250_mag().
float MPU9250_mag::_mag_asa_z private
Definition at line 149 of file mag.h.
Referenced by _measure(), ak8963_read_adjustments(), and MPU9250_mag().
int MPU9250_mag::_mag_class_instance private
Definition at line 137 of file mag.h.
Referenced by init(), and ~MPU9250_mag().
perf_counter_t MPU9250_mag::_mag_duplicates private
Definition at line 146 of file mag.h.
Referenced by _measure(), MPU9250_mag(), and ~MPU9250_mag().
perf_counter_t MPU9250_mag::_mag_errors private
Definition at line 143 of file mag.h.
Referenced by _measure(), MPU9250_mag(), and ~MPU9250_mag().
int MPU9250_mag::_mag_orb_class_instance private
Definition at line 136 of file mag.h.
Referenced by init().
perf_counter_t MPU9250_mag::_mag_overflows private
Definition at line 145 of file mag.h.
Referenced by _measure(), MPU9250_mag(), and ~MPU9250_mag().
perf_counter_t MPU9250_mag::_mag_overruns private
Definition at line 144 of file mag.h.
Referenced by _measure(), MPU9250_mag(), and ~MPU9250_mag().
float MPU9250_mag::_mag_range_scale private
Definition at line 141 of file mag.h.
Referenced by _measure(), and MPU9250_mag().
bool MPU9250_mag::_mag_reading_data private
Definition at line 138 of file mag.h.
perf_counter_t MPU9250_mag::_mag_reads private
Definition at line 142 of file mag.h.
Referenced by MPU9250_mag(), read(), and ~MPU9250_mag().
ringbuffer::RingBuffer* MPU9250_mag::_mag_reports private
Definition at line 139 of file mag.h.
Referenced by _measure(), init(), ioctl(), MPU9250::print_info(), read(), MPU9250::start(), and ~MPU9250_mag().
struct mag_calibration_s MPU9250_mag::_mag_scale private
Definition at line 140 of file mag.h.
Referenced by _measure(), ioctl(), and MPU9250_mag().
orb_advert_t MPU9250_mag::_mag_topic private
Definition at line 135 of file mag.h.
Referenced by _measure(), init(), and ~MPU9250_mag().
MPU9250* MPU9250_mag::_parent private
Definition at line 134 of file mag.h.
Referenced by _measure(), ak8963_setup(), ak8963_setup_master_i2c(), passthrough_read(), passthrough_write(), read(), read_block(), and set_passthrough().
The documentation for this class was generated from the following files:
src/drivers/imu/mpu9250/mag.h
src/drivers/imu/mpu9250/mag.cpp