PX4 Firmware: radar Namespace Reference
radar Namespace Reference
Functions
int reset (const char *port)
Reset the driver.
int start (const char *port, const uint8_t rotation)
Start the driver.
int status ()
Print the driver status.
int stop ()
Stop the driver.
int test (const char *port)
Perform some basic functional tests on the driver; make sure we can collect data from the sensor in polled and automatic modes.
int usage ()
Prints info about the driver argument usage.
Variables
Radar * g_dev
Function Documentation
reset()
int radar::reset (const char * port = RADAR_DEFAULT_PORT)
Reset the driver.
Definition at line 416 of file ulanding.cpp.
References Radar::start(), and Radar::stop().
Referenced by ulanding_radar_main().
start()
int radar::start (const char * port = RADAR_DEFAULT_PORT, const uint8_t rotation = distance_sensor_s::ROTATION_DOWNWARD_FACING)
Start the driver.
Definition at line 429 of file ulanding.cpp.
References g_dev, Radar::init(), and Radar::Radar().
Referenced by ulanding_radar_main().
status()
int radar::status ()
Print the driver status.
Definition at line 458 of file ulanding.cpp.
References Radar::print_info().
Referenced by ulanding_radar_main().
stop()
int radar::stop ()
Stop the driver.
Stop the driver.
Definition at line 474 of file ulanding.cpp.
References g_dev.
Referenced by ulanding_radar_main().
test()
int radar::test (const char * port = RADAR_DEFAULT_PORT)
Perform some basic functional tests on the driver; make sure we can collect data from the sensor in polled and automatic modes.
Definition at line 490 of file ulanding.cpp.
References fd, cdev::CDev::open(), and cdev::CDev::read().
Referenced by ulanding_radar_main().
usage()
int radar::usage (void)
Prints info about the driver argument usage.
Prints info about the driver argument usage.
Definition at line 513 of file ulanding.cpp.
Referenced by ulanding_radar_main().
Variable Documentation
g_dev
Radar* radar::g_dev
Definition at line 402 of file ulanding.cpp.
Referenced by start(), and stop().