PX4 Firmware: LSM303AGR Class Reference
LSM303AGR Class Reference
#include <LSM303AGR.hpp>
Public Member Functions
LSM303AGR (int bus, const char *path, uint32_t device, enum Rotation rotation)
virtual ~LSM303AGR ()
virtual int init ()
virtual int ioctl (struct file *filp, int cmd, unsigned long arg)
void print_info ()
Diagnostics - print some basic information about the driver.
Protected Member Functions
virtual int probe ()
Private Member Functions
void start ()
Start automatic measurement.
void stop ()
Stop automatic measurement.
int reset ()
Reset chip.
bool self_test ()
void measure ()
Issue a measurement command.
int collect ()
Collect the result of the most recent measurement.
void cycle ()
Perform a poll cycle; collect from the previous measurement and start a new one.
uint8_t read_reg (unsigned reg)
Read a register from the LSM303AGR.
void write_reg (unsigned reg, uint8_t value)
Write a register in the LSM303AGR.
LSM303AGR (const LSM303AGR &)
LSM303AGR operator= (const LSM303AGR &)
Static Private Member Functions
static void cycle_trampoline (void *arg)
Static trampoline from the workq context; because we don't have a generic workq wrapper yet.
Private Attributes
work_s _work {}
bool _collect_phase {false}
unsigned _measure_ticks {0}
unsigned _call_mag_interval {0}
mag_calibration_s _mag_scale {}
int _class_instance {-1}
unsigned _mag_samplerate {100}
perf_counter_t _mag_sample_perf
perf_counter_t _bad_registers
perf_counter_t _bad_values
enum Rotation _rotation
orb_advert_t _mag_topic {nullptr}
int _mag_orb_class_instance {-1}
Static Private Attributes
static constexpr float _mag_range_scale {1.5f / 1000.0f}
static constexpr float _mag_range_ga {49.152f}
Detailed Description
Definition at line 90 of file LSM303AGR.hpp.
Constructor & Destructor Documentation
LSM303AGR::LSM303AGR (int bus, const char * path, uint32_t device, enum Rotation rotation)
Definition at line 64 of file LSM303AGR.cpp.
References _mag_scale, DRV_MAG_DEVTYPE_LSM303AGR, mag_calibration_s::x_offset, mag_calibration_s::x_scale, mag_calibration_s::y_offset, mag_calibration_s::y_scale, mag_calibration_s::z_offset, and mag_calibration_s::z_scale.
LSM303AGR::~LSM303AGR () virtual
Definition at line 83 of file LSM303AGR.cpp.
References _bad_registers, _bad_values, _class_instance, _mag_sample_perf, MAG_BASE_DEVICE_PATH, perf_free(), and stop().
LSM303AGR::LSM303AGR (const LSM303AGR &) private
Member Function Documentation
int LSM303AGR::collect () private
Collect the result of the most recent measurement.
Definition at line 453 of file LSM303AGR.cpp.
References _bad_registers, _bad_values, _mag_orb_class_instance, _mag_range_scale, _mag_sample_perf, _mag_scale, _mag_topic, _rotation, DEVICE_DEBUG, hrt_absolute_time(), mag_report, OK, orb_advertise_multi(), ORB_ID, ORB_PRIO_HIGH, ORB_PRIO_MAX, orb_publish(), OUTX_H_REG_M, OUTX_L_REG_M, OUTY_H_REG_M, OUTY_L_REG_M, OUTZ_H_REG_M, OUTZ_L_REG_M, perf_begin(), perf_end(), perf_event_count(), read_reg(), rotate_3f(), status, STATUS_REG_M, STATUS_REG_M_Zyxda, mag_calibration_s::x_offset, mag_calibration_s::x_scale, mag_calibration_s::y_offset, mag_calibration_s::y_scale, mag_calibration_s::z_offset, and mag_calibration_s::z_scale.
Referenced by cycle().
void LSM303AGR::cycle () private
Perform a poll cycle; collect from the previous measurement and start a new one.
This is the heart of the measurement state machine. This function alternately starts a measurement, or collects the data from the previous measurement.
When the interval between measurements is greater than the minimum measurement interval, a gap is inserted between collection and measurement to provide the most recent measurement possible at the next interval.
Definition at line 395 of file LSM303AGR.cpp.
References _collect_phase, _measure_ticks, collect(), CONVERSION_INTERVAL, cycle_trampoline(), DEVICE_DEBUG, measure(), OK, and start().
Referenced by cycle_trampoline().
void LSM303AGR::cycle_trampoline (void * arg) static private
Static trampoline from the workq context; because we don't have a generic workq wrapper yet.
Parameters
arg Instance pointer for the driver that is polling.
Definition at line 387 of file LSM303AGR.cpp.
References cycle().
Referenced by cycle(), and start().
int LSM303AGR::init () virtual
Definition at line 99 of file LSM303AGR.cpp.
References _class_instance, lis3mdl::init(), MAG_BASE_DEVICE_PATH, measure(), OK, PX4_ERR, PX4_ERROR, PX4_OK, reset(), and self_test().
Referenced by lsm303agr::start().
int LSM303AGR::ioctl (struct file * filp, int cmd, unsigned long arg) virtual
Definition at line 242 of file LSM303AGR.cpp.
References _mag_scale, _measure_ticks, CONVERSION_INTERVAL, MAGIOCGEXTERNAL, MAGIOCGSAMPLERATE, MAGIOCGSCALE, MAGIOCSSAMPLERATE, MAGIOCSSCALE, OK, reset(), SENSOR_POLLRATE_DEFAULT, SENSOR_POLLRATE_EXTERNAL, SENSOR_POLLRATE_MANUAL, SENSOR_POLLRATE_MAX, SENSORIOCGPOLLRATE, SENSORIOCRESET, SENSORIOCSPOLLRATE, start(), and stop().
void LSM303AGR::measure () private
Issue a measurement command.
Returns
OK if the measurement command was successful.
Definition at line 444 of file LSM303AGR.cpp.
References CFG_REG_A_M, CFG_REG_A_M_MD0, CFG_REG_A_M_ODR0, CFG_REG_A_M_ODR1, and write_reg().
Referenced by cycle(), and init().
LSM303AGR LSM303AGR::operator= (const LSM303AGR &) private
void LSM303AGR::print_info ()
Diagnostics - print some basic information about the driver.
Definition at line 515 of file LSM303AGR.cpp.
References _bad_registers, _bad_values, _mag_sample_perf, and perf_print_counter().
Referenced by lsm303agr::info().
int LSM303AGR::probe () protected virtual
Definition at line 229 of file LSM303AGR.cpp.
References LSM303AGR_WHO_AM_I_M, OK, read_reg(), and WHO_AM_I_M.
uint8_t LSM303AGR::read_reg (unsigned reg) private
Read a register from the LSM303AGR.
Parameters
The register to read.
Returns
The value that was read.
Definition at line 343 of file LSM303AGR.cpp.
References DIR_READ.
Referenced by collect(), probe(), and self_test().
int LSM303AGR::reset () private
Reset chip.
Resets the chip and measurements ranges, but not scale and offset.
Definition at line 124 of file LSM303AGR.cpp.
References CFG_REG_A_M, CFG_REG_A_M_MD0, CFG_REG_A_M_ODR0, CFG_REG_A_M_ODR1, CFG_REG_B_M, CFG_REG_B_M_OFF_CANC, CFG_REG_B_M_OFF_LPF, CFG_REG_C_M, CFG_REG_C_M_I2C_DIS, PX4_OK, and write_reg().
Referenced by init(), and ioctl().
bool LSM303AGR::self_test (void) private
Definition at line 140 of file LSM303AGR.cpp.
References CFG_REG_A_M, CFG_REG_B_M, CFG_REG_C_M, OUTX_H_REG_M, OUTX_L_REG_M, OUTY_H_REG_M, OUTY_L_REG_M, OUTZ_H_REG_M, OUTZ_L_REG_M, PX4_ERR, PX4_INFO, read_reg(), STATUS_REG_M, usleep(), and write_reg().
Referenced by init().
void LSM303AGR::start () private
Start automatic measurement.
Definition at line 367 of file LSM303AGR.cpp.
References _collect_phase, and cycle_trampoline().
Referenced by cycle(), and ioctl().
void LSM303AGR::stop () private
Stop automatic measurement.
Definition at line 377 of file LSM303AGR.cpp.
References _measure_ticks.
Referenced by ioctl(), and ~LSM303AGR().
void LSM303AGR::write_reg (unsigned reg, uint8_t value) private
Write a register in the LSM303AGR.
Parameters
reg The register to write.
value The new value to write.
Definition at line 356 of file LSM303AGR.cpp.
References DIR_WRITE.
Referenced by measure(), reset(), and self_test().
Member Data Documentation
perf_counter_t LSM303AGR::_bad_registers private
Definition at line 127 of file LSM303AGR.hpp.
Referenced by collect(), print_info(), and ~LSM303AGR().
perf_counter_t LSM303AGR::_bad_values private
Definition at line 128 of file LSM303AGR.hpp.
Referenced by collect(), print_info(), and ~LSM303AGR().
unsigned LSM303AGR::_call_mag_interval {0} private
Definition at line 115 of file LSM303AGR.hpp.
int LSM303AGR::_class_instance {-1} private
Definition at line 122 of file LSM303AGR.hpp.
Referenced by init(), and ~LSM303AGR().
bool LSM303AGR::_collect_phase {false} private
Definition at line 111 of file LSM303AGR.hpp.
Referenced by cycle(), and start().
int LSM303AGR::_mag_orb_class_instance {-1} private
Definition at line 133 of file LSM303AGR.hpp.
Referenced by collect().
constexpr float LSM303AGR::_mag_range_ga {49.152f} static private
Definition at line 120 of file LSM303AGR.hpp.
constexpr float LSM303AGR::_mag_range_scale {1.5f / 1000.0f} static private
Definition at line 119 of file LSM303AGR.hpp.
Referenced by collect().
perf_counter_t LSM303AGR::_mag_sample_perf private
Definition at line 126 of file LSM303AGR.hpp.
Referenced by collect(), print_info(), and ~LSM303AGR().
unsigned LSM303AGR::_mag_samplerate {100} private
Definition at line 124 of file LSM303AGR.hpp.
mag_calibration_s LSM303AGR::_mag_scale {} private
Definition at line 117 of file LSM303AGR.hpp.
Referenced by collect(), ioctl(), and LSM303AGR().
orb_advert_t LSM303AGR::_mag_topic {nullptr} private
Definition at line 132 of file LSM303AGR.hpp.
Referenced by collect().
unsigned LSM303AGR::_measure_ticks {0} private
Definition at line 113 of file LSM303AGR.hpp.
Referenced by cycle(), ioctl(), and stop().
enum Rotation LSM303AGR::_rotation private
Definition at line 130 of file LSM303AGR.hpp.
Referenced by collect().
work_s LSM303AGR::_work {} private
Definition at line 110 of file LSM303AGR.hpp.
The documentation for this class was generated from the following files:
src/drivers/magnetometer/lsm303agr/LSM303AGR.hpp
src/drivers/magnetometer/lsm303agr/LSM303AGR.cpp