PX4 Firmware: adis16497 Namespace Reference
adis16497 Namespace Reference
Functions
static int start (enum Rotation rotation)
static int stop ()
static int status ()
static int usage ()
Variables
ADIS16497 * g_dev {nullptr}
Function Documentation
start()
static int adis16497::start (enum Rotation rotation) static
Definition at line 42 of file adis16497_main.cpp.
References g_dev, and ADIS16497::init().
Referenced by adis16497_main().
status()
static int adis16497::status () static
Definition at line 85 of file adis16497_main.cpp.
References g_dev, and ADIS16497::print_info().
Referenced by adis16497_main().
stop()
static int adis16497::stop () static
Definition at line 72 of file adis16497_main.cpp.
References g_dev.
Referenced by adis16497_main().
usage()
static int adis16497::usage (void) static
Definition at line 97 of file adis16497_main.cpp.
Referenced by adis16497_main().
Variable Documentation
g_dev
ADIS16497* adis16497::g_dev {nullptr}
Definition at line 40 of file adis16497_main.cpp.
Referenced by start(), status(), and stop().