PX4 Firmware: MavlinkStreamUTMGlobalPosition Class Reference
MavlinkStreamUTMGlobalPosition Class Reference
Public Member Functions
const char * get_name () const override
uint16_t get_id () override
bool const_rate () override
unsigned get_size () override
Get maximal total messages size on update.
Public Member Functions inherited from MavlinkStream
MavlinkStream (Mavlink *mavlink)
virtual ~MavlinkStream ()=default
MavlinkStream (const MavlinkStream &)=delete
MavlinkStream & operator= (const MavlinkStream &)=delete
MavlinkStream (MavlinkStream &&)=delete
MavlinkStream & operator= (MavlinkStream &&)=delete
void set_interval (const int interval)
Get the interval.
int get_interval ()
Get the interval.
int update (const hrt_abstime &t)
Update subscriptions and send message if necessary.
virtual unsigned get_size_avg ()
Get the average message size.
bool first_message_sent () const
void reset_last_sent ()
Reset the time of last sent to 0.
Public Member Functions inherited from ListNode< MavlinkStream *>
void setSibling (MavlinkStream * sibling)
const MavlinkStream * getSibling () const
Static Public Member Functions
static const char * get_name_static ()
static uint16_t get_id_static ()
static MavlinkStream * new_instance (Mavlink *mavlink)
Protected Member Functions
MavlinkStreamUTMGlobalPosition (Mavlink *mavlink)
bool send (const hrt_abstime t) override
Protected Member Functions inherited from MavlinkStream
virtual void update_data ()
Function to collect/update data for the streams at a high rate independant of actual stream rate.
Private Member Functions
MavlinkStreamUTMGlobalPosition (MavlinkStreamUTMGlobalPosition &)=delete
MavlinkStreamUTMGlobalPosition & operator= (const MavlinkStreamUTMGlobalPosition &)=delete
Private Attributes
MavlinkOrbSubscription * _local_pos_sub
uint64_t _local_pos_time = 0
vehicle_local_position_s _local_position = {}
MavlinkOrbSubscription * _global_pos_sub
uint64_t _global_pos_time = 0
vehicle_global_position_s _global_position = {}
MavlinkOrbSubscription * _position_setpoint_triplet_sub
uint64_t _setpoint_triplet_time = 0
position_setpoint_triplet_s _setpoint_triplet = {}
MavlinkOrbSubscription * _vehicle_status_sub
uint64_t _vehicle_status_time = 0
vehicle_status_s _vehicle_status = {}
MavlinkOrbSubscription * _land_detected_sub
uint64_t _land_detected_time = 0
vehicle_land_detected_s _land_detected = {}
Additional Inherited Members
Protected Attributes inherited from MavlinkStream
Mavlink *const _mavlink
int _interval {1000000}
if set to negative value = unlimited rate
Protected Attributes inherited from ListNode< MavlinkStream *>
MavlinkStream * _list_node_sibling
Detailed Description
Definition at line 1855 of file mavlink_messages.cpp.
Constructor & Destructor Documentation
MavlinkStreamUTMGlobalPosition() [1/2]
MavlinkStreamUTMGlobalPosition::MavlinkStreamUTMGlobalPosition (MavlinkStreamUTMGlobalPosition &) private delete
MavlinkStreamUTMGlobalPosition() [2/2]
MavlinkStreamUTMGlobalPosition::MavlinkStreamUTMGlobalPosition (Mavlink * mavlink) inline explicit protected
Definition at line 1919 of file mavlink_messages.cpp.
Member Function Documentation
const_rate()
bool MavlinkStreamUTMGlobalPosition::const_rate () inline override virtual
Returns
true if steam rate shouldn't be adjusted
Reimplemented from MavlinkStream.
Definition at line 1883 of file mavlink_messages.cpp.
get_id()
uint16_t MavlinkStreamUTMGlobalPosition::get_id () inline override virtual
Implements MavlinkStream.
Definition at line 1873 of file mavlink_messages.cpp.
References MavlinkStreamHeartbeat::get_id_static().
get_id_static()
static uint16_t MavlinkStreamUTMGlobalPosition::get_id_static () inline static
Definition at line 1868 of file mavlink_messages.cpp.
get_name()
const char* MavlinkStreamUTMGlobalPosition::get_name () const inline override virtual
Implements MavlinkStream.
Definition at line 1858 of file mavlink_messages.cpp.
References get_name_static().
get_name_static()
static const char* MavlinkStreamUTMGlobalPosition::get_name_static () inline static
Definition at line 1863 of file mavlink_messages.cpp.
Referenced by get_name().
get_size()
unsigned MavlinkStreamUTMGlobalPosition::get_size () inline override virtual
Get maximal total messages size on update.
Implements MavlinkStream.
Definition at line 1888 of file mavlink_messages.cpp.
new_instance()
static MavlinkStream* MavlinkStreamUTMGlobalPosition::new_instance (Mavlink * mavlink) inline static
Definition at line 1878 of file mavlink_messages.cpp.
operator=()
MavlinkStreamUTMGlobalPosition& MavlinkStreamUTMGlobalPosition::operator= (const MavlinkStreamUTMGlobalPosition &) private delete
send()
bool MavlinkStreamUTMGlobalPosition::send (const hrt_abstime t) inline override protected virtual
Implements MavlinkStream.
Definition at line 1927 of file mavlink_messages.cpp.
References MavlinkStream::_mavlink, vehicle_global_position_s::alt, position_setpoint_s::alt, vehicle_global_position_s::alt_ellipsoid, vehicle_status_s::arming_state, position_setpoint_triplet_s::current, vehicle_local_position_s::dist_bottom, vehicle_local_position_s::dist_bottom_valid, vehicle_global_position_s::eph, vehicle_global_position_s::epv, vehicle_local_position_s::evh, vehicle_local_position_s::evv, Mavlink::get_channel(), vehicle_land_detected_s::landed, vehicle_global_position_s::lat, position_setpoint_s::lat, vehicle_global_position_s::lon, position_setpoint_s::lon, msg, vehicle_status_s::nav_state, MavlinkOrbSubscription::update(), vehicle_local_position_s::v_xy_valid, vehicle_local_position_s::v_z_valid, position_setpoint_s::valid, vehicle_local_position_s::vx, vehicle_local_position_s::vy, and vehicle_local_position_s::vz.
Member Data Documentation
_global_pos_sub
MavlinkOrbSubscription* MavlinkStreamUTMGlobalPosition::_global_pos_sub private
Definition at line 1898 of file mavlink_messages.cpp.
_global_pos_time
uint64_t MavlinkStreamUTMGlobalPosition::_global_pos_time = 0 private
Definition at line 1899 of file mavlink_messages.cpp.
_global_position
vehicle_global_position_s MavlinkStreamUTMGlobalPosition::_global_position = {} private
Definition at line 1900 of file mavlink_messages.cpp.
_land_detected
vehicle_land_detected_s MavlinkStreamUTMGlobalPosition::_land_detected = {} private
Definition at line 1912 of file mavlink_messages.cpp.
_land_detected_sub
MavlinkOrbSubscription* MavlinkStreamUTMGlobalPosition::_land_detected_sub private
Definition at line 1910 of file mavlink_messages.cpp.
_land_detected_time
uint64_t MavlinkStreamUTMGlobalPosition::_land_detected_time = 0 private
Definition at line 1911 of file mavlink_messages.cpp.
_local_pos_sub
MavlinkOrbSubscription* MavlinkStreamUTMGlobalPosition::_local_pos_sub private
Definition at line 1894 of file mavlink_messages.cpp.
_local_pos_time
uint64_t MavlinkStreamUTMGlobalPosition::_local_pos_time = 0 private
Definition at line 1895 of file mavlink_messages.cpp.
_local_position
vehicle_local_position_s MavlinkStreamUTMGlobalPosition::_local_position = {} private
Definition at line 1896 of file mavlink_messages.cpp.
_position_setpoint_triplet_sub
MavlinkOrbSubscription* MavlinkStreamUTMGlobalPosition::_position_setpoint_triplet_sub private
Definition at line 1902 of file mavlink_messages.cpp.
_setpoint_triplet
position_setpoint_triplet_s MavlinkStreamUTMGlobalPosition::_setpoint_triplet = {} private
Definition at line 1904 of file mavlink_messages.cpp.
_setpoint_triplet_time
uint64_t MavlinkStreamUTMGlobalPosition::_setpoint_triplet_time = 0 private
Definition at line 1903 of file mavlink_messages.cpp.
_vehicle_status
vehicle_status_s MavlinkStreamUTMGlobalPosition::_vehicle_status = {} private
Definition at line 1908 of file mavlink_messages.cpp.
_vehicle_status_sub
MavlinkOrbSubscription* MavlinkStreamUTMGlobalPosition::_vehicle_status_sub private
Definition at line 1906 of file mavlink_messages.cpp.
_vehicle_status_time
uint64_t MavlinkStreamUTMGlobalPosition::_vehicle_status_time = 0 private
Definition at line 1907 of file mavlink_messages.cpp.
The documentation for this class was generated from the following file:
src/modules/mavlink/mavlink_messages.cpp