PX4 Firmware: __EXPORT::SPI Class Reference
__EXPORT::SPI Class Reference
Abstract class for character device on SPI.
#include <SPI.hpp>
Protected Types
enum LockMode { LOCK_PREEMPTION, LOCK_THREADS, LOCK_NONE }
Locking modes supported by the driver.
Protected Member Functions
SPI (const char *name, const char *devname, int bus, uint32_t device, enum spi_mode_e mode, uint32_t frequency)
Constructor.
virtual ~SPI ()
virtual int init ()
virtual int probe ()
Check for the presence of the device on the bus.
int transfer (uint8_t *send, uint8_t *recv, unsigned len)
Perform a SPI transfer.
int transferhword (uint16_t *send, uint16_t *recv, unsigned len)
Perform a SPI 16 bit transfer.
void set_frequency (uint32_t frequency)
Set the SPI bus frequency This is used to change frequency on the fly.
void set_lockmode (enum LockMode mode)
Set the SPI bus locking mode.
int _transfer (uint8_t *send, uint8_t *recv, unsigned len)
int _transferhword (uint16_t *send, uint16_t *recv, unsigned len)
bool external ()
Protected Attributes
LockMode locking_mode
selected locking mode
Private Member Functions
SPI (const SPI &)
SPI operator= (const SPI &)
Private Attributes
uint32_t _device
enum spi_mode_e _mode
uint32_t _frequency
struct spi_dev_s * _dev
Detailed Description
Abstract class for character device on SPI.
Definition at line 53 of file SPI.hpp.
Member Enumeration Documentation
enum __EXPORT::SPI::LockMode protected
Locking modes supported by the driver.
Enumerator
LOCK_PREEMPTION
the default; lock against all forms of preemption.
LOCK_THREADS
lock only against other threads, using SPI_LOCK
LOCK_NONE
perform no locking, only safe if the bus is entirely private
Definition at line 77 of file SPI.hpp.
Constructor & Destructor Documentation
SPI::SPI (const char * name, const char * devname, int bus, uint32_t device, enum spi_mode_e mode, uint32_t frequency) protected
Constructor.
Parameters
name Driver name
devname Device node name
bus SPI bus on which the device lives
device Device handle (used by SPI_SELECT)
mode SPI clock/data mode
frequency SPI clock frequency
Definition at line 60 of file SPI.cpp.
SPI::~SPI () protected virtual
Definition at line 85 of file SPI.cpp.
__EXPORT::SPI::SPI (const SPI &) private
Member Function Documentation
int SPI::_transfer (uint8_t * send, uint8_t * recv, unsigned len) protected
Definition at line 168 of file SPI.cpp.
References _dev, _device, _frequency, _mode, and OK.
Referenced by transfer().
int SPI::_transferhword (uint16_t * send, uint16_t * recv, unsigned len) protected
Definition at line 220 of file SPI.cpp.
References _dev, _device, _frequency, _mode, and OK.
Referenced by transferhword().
bool __EXPORT::SPI::external () inline protected
Definition at line 170 of file SPI.hpp.
References px4_spi_bus_external().
int SPI::init () protected virtual
Definition at line 91 of file SPI.cpp.
References _dev, _device, _frequency, DEVICE_DEBUG, DEVICE_LOG, lis3mdl::init(), OK, probe(), and PX4_SPI_DEV_ID.
SPI __EXPORT::SPI::operator= (const SPI &) private
virtual int __EXPORT::SPI::probe () inline protected virtual
Check for the presence of the device on the bus.
Definition at line 88 of file SPI.hpp.
References PX4_OK, and send().
Referenced by init().
void __EXPORT::SPI::set_frequency (uint32_t frequency) inline protected
Set the SPI bus frequency This is used to change frequency on the fly.
Some sensors (such as the MPU6000) need a lower frequency for setup registers and can handle higher frequency for sensor value registers
Parameters
frequency Frequency to set (Hz)
Definition at line 141 of file SPI.hpp.
void __EXPORT::SPI::set_lockmode (enum LockMode mode) inline protected
Set the SPI bus locking mode.
This set the SPI locking mode. For devices competing with NuttX SPI drivers on a bus the right lock mode is LOCK_THREADS.
Parameters
mode Locking mode
Definition at line 151 of file SPI.hpp.
int SPI::transfer (uint8_t * send, uint8_t * recv, unsigned len) protected
Perform a SPI transfer.
If called from interrupt context, this interface does not lock the bus and may interfere with non-interrupt-context callers.
Clients in a mixed interrupt/non-interrupt configuration must ensure appropriate interlocking.
At least one of send or recv must be non-null.
Parameters
send Bytes to send to the device, or nullptr if no data is to be sent.
recv Buffer for receiving bytes from the device, or nullptr if no bytes are to be received.
len Number of bytes to transfer.
Returns
OK if the exchange was successful, -errno otherwise.
Definition at line 133 of file SPI.cpp.
References _dev, _transfer(), LOCK_NONE, LOCK_PREEMPTION, LOCK_THREADS, locking_mode, and state.
int SPI::transferhword (uint16_t * send, uint16_t * recv, unsigned len) protected
Perform a SPI 16 bit transfer.
If called from interrupt context, this interface does not lock the bus and may interfere with non-interrupt-context callers.
Clients in a mixed interrupt/non-interrupt configuration must ensure appropriate interlocking.
At least one of send or recv must be non-null.
Parameters
send Words to send to the device, or nullptr if no data is to be sent.
recv Words for receiving bytes from the device, or nullptr if no bytes are to be received.
len Number of words to transfer.
Returns
OK if the exchange was successful, -errno otherwise.
Definition at line 185 of file SPI.cpp.
References _dev, _transferhword(), LOCK_NONE, LOCK_PREEMPTION, LOCK_THREADS, locking_mode, and state.
Member Data Documentation
struct spi_dev_s* __EXPORT::SPI::_dev private
Definition at line 159 of file SPI.hpp.
Referenced by _transfer(), _transferhword(), init(), transfer(), and transferhword().
uint32_t __EXPORT::SPI::_device private
Definition at line 156 of file SPI.hpp.
Referenced by _transfer(), _transferhword(), and init().
uint32_t __EXPORT::SPI::_frequency private
Definition at line 158 of file SPI.hpp.
Referenced by _transfer(), _transferhword(), and init().
enum spi_mode_e __EXPORT::SPI::_mode private
Definition at line 157 of file SPI.hpp.
Referenced by _transfer(), and _transferhword().
LockMode __EXPORT::SPI::locking_mode protected
selected locking mode
Definition at line 153 of file SPI.hpp.
Referenced by transfer(), and transferhword().
The documentation for this class was generated from the following files:
src/lib/drivers/device/nuttx/SPI.hpp
src/lib/drivers/device/nuttx/SPI.cpp