PX4 Firmware: src/modules/commander/airspeed_calibration.cpp File Reference
airspeed_calibration.cpp File Reference
Airspeed sensor calibration routine.
#include "airspeed_calibration.h"
#include "calibration_messages.h"
#include "calibration_routines.h"
#include "commander_helper.h"
#include <px4_defines.h>
#include <px4_posix.h>
#include <px4_time.h>
#include <stdio.h>
#include <unistd.h>
#include <fcntl.h>
#include <poll.h>
#include <cmath>
#include <drivers/drv_hrt.h>
#include <drivers/drv_airspeed.h>
#include <uORB/topics/differential_pressure.h>
#include <systemlib/mavlink_log.h>
#include <parameters/param.h>
#include <systemlib/err.h>
Functions
static void feedback_calibration_failed (orb_advert_t *mavlink_log_pub)
int do_airspeed_calibration (orb_advert_t *mavlink_log_pub)
Variables
static const char * sensor_name = "airspeed"
Detailed Description
Airspeed sensor calibration routine.
Definition in file airspeed_calibration.cpp.
Function Documentation
int do_airspeed_calibration (orb_advert_t * mavlink_log_pub)
Definition at line 67 of file airspeed_calibration.cpp.
References AIRSPEED0_DEVICE_PATH, AIRSPEEDIOCSSCALE, CAL_ERROR_SET_PARAMS_MSG, CAL_QGC_DONE_MSG, CAL_QGC_PROGRESS_MSG, CAL_QGC_STARTED_MSG, calibrate_cancel_check(), calibrate_cancel_subscribe(), calibrate_cancel_unsubscribe(), calibration_log_critical, calibration_log_info, differential_pressure_s::differential_pressure_filtered_pa, differential_pressure_s::differential_pressure_raw_pa, differential_pressure_s::error_count, f(), fd, feedback_calibration_failed(), airspeed_scale::offset_pa, orb_copy(), ORB_ID, orb_subscribe(), param_find(), param_get(), param_save_default(), param_set(), px4_close(), PX4_ERROR, px4_ioctl(), PX4_OK, px4_open(), px4_poll(), sensor_name, tune_neutral(), and usleep().
Referenced by commander_low_prio_loop(), and commander_main().
static void feedback_calibration_failed (orb_advert_t * mavlink_log_pub) static
Definition at line 61 of file airspeed_calibration.cpp.
References CAL_QGC_FAILED_MSG, calibration_log_critical, and sensor_name.
Referenced by do_airspeed_calibration().
Variable Documentation
const char* sensor_name = "airspeed" static
Definition at line 59 of file airspeed_calibration.cpp.
Referenced by do_airspeed_calibration(), and feedback_calibration_failed().