PX4 Firmware: LidarLiteI2C Class Reference
LidarLiteI2C Class Reference
#include <LidarLiteI2C.h>
Public Member Functions
LidarLiteI2C (int bus, const char *path, uint8_t rotation=distance_sensor_s::ROTATION_DOWNWARD_FACING, int address=LL40LS_BASEADDR)
virtual ~LidarLiteI2C ()
int init () override
ssize_t read (device::file_t *filp, char *buffer, size_t buflen) override
int ioctl (device::file_t *filp, int cmd, unsigned long arg) override
void print_info () override
Diagnostics - print some basic information about the driver.
void print_registers () override
print registers to console
const char * get_dev_name () override
Public Member Functions inherited from LidarLite
LidarLite ()
virtual ~LidarLite ()=default
Protected Member Functions
int probe () override
int read_reg (uint8_t reg, uint8_t &val)
int write_reg (uint8_t reg, uint8_t val)
int measure () override
int reset_sensor () override
Protected Member Functions inherited from LidarLite
void set_minimum_distance (const float min)
Set the min and max distance thresholds if you want the end points of the sensors range to be brought in at all, otherwise it will use the defaults LL40LS_MIN_DISTANCE and LL40LS_MAX_DISTANCE.
void set_maximum_distance (const float max)
float get_minimum_distance () const
float get_maximum_distance () const
uint32_t getMeasureTicks () const
Private Member Functions
int lidar_transfer (const uint8_t *send, unsigned send_len, uint8_t *recv, unsigned recv_len)
LidarLite specific transfer function.
int probe_address (uint8_t address)
Test whether the device supported by the driver is present at a specific address.
void start () override
Initialise the automatic measurement state machine and start it.
void stop () override
Stop the automatic measurement state machine.
void cycle ()
Perform a poll cycle; collect from the previous measurement and start a new one.
int collect () override
LidarLiteI2C (const LidarLiteI2C &copy)=delete
LidarLiteI2C operator= (const LidarLiteI2C &assignment)=delete
Static Private Member Functions
static void cycle_trampoline (void *arg)
Static trampoline from the workq context; because we don't have a generic workq wrapper yet.
Private Attributes
uint8_t _rotation
work_s _work
ringbuffer::RingBuffer * _reports
bool _sensor_ok
bool _collect_phase
int _class_instance
int _orb_class_instance
orb_advert_t _distance_sensor_topic
perf_counter_t _sample_perf
perf_counter_t _comms_errors
perf_counter_t _sensor_resets
perf_counter_t _sensor_zero_resets
uint16_t _last_distance
uint16_t _zero_counter
uint64_t _acquire_time_usec
volatile bool _pause_measurements
uint8_t _hw_version
uint8_t _sw_version
Detailed Description
Definition at line 79 of file LidarLiteI2C.h.
Constructor & Destructor Documentation
LidarLiteI2C::LidarLiteI2C (int bus, const char * path, uint8_t rotation = distance_sensor_s::ROTATION_DOWNWARD_FACING, int address = LL40LS_BASEADDR)
Definition at line 53 of file LidarLiteI2C.cpp.
References _acquire_time_usec, _class_instance, _collect_phase, _comms_errors, _distance_sensor_topic, _hw_version, _last_distance, _orb_class_instance, _pause_measurements, _reports, _sample_perf, _sensor_ok, _sensor_resets, _sensor_zero_resets, _sw_version, _zero_counter, PC_COUNT, PC_ELAPSED, and perf_alloc.
LidarLiteI2C::~LidarLiteI2C () virtual
Definition at line 81 of file LidarLiteI2C.cpp.
References _class_instance, _comms_errors, _reports, _sample_perf, _sensor_resets, _sensor_zero_resets, perf_free(), RANGE_FINDER_BASE_DEVICE_PATH, and stop().
LidarLiteI2C::LidarLiteI2C (const LidarLiteI2C & copy) private delete
Member Function Documentation
int LidarLiteI2C::collect () override private virtual
Implements LidarLite.
Definition at line 388 of file LidarLiteI2C.cpp.
References _acquire_time_usec, _comms_errors, _distance_sensor_topic, _last_distance, _reports, _rotation, _sample_perf, _sensor_resets, _sensor_zero_resets, _zero_counter, distance_sensor_s::covariance, distance_sensor_s::current_distance, DEVICE_DEBUG, f(), LidarLite::get_maximum_distance(), LidarLite::get_minimum_distance(), hrt_absolute_time(), distance_sensor_s::id, lidar_transfer(), LL40LS_AUTO_INCREMENT, LL40LS_CONVERSION_TIMEOUT, LL40LS_DISTHIGH_REG, LL40LS_MIN_DISTANCE, LL40LS_PEAK_STRENGTH_HIGH, LL40LS_PEAK_STRENGTH_LOW, LL40LS_PEAK_STRENGTH_REG, LL40LS_SIGNAL_STRENGTH_LOW, LL40LS_SIGNAL_STRENGTH_REG, math::max(), distance_sensor_s::max_distance, distance_sensor_s::min_distance, OK, ORB_ID, orb_publish(), distance_sensor_s::orientation, perf_begin(), perf_count(), perf_end(), perf_event_count(), PX4_INFO, reset_sensor(), distance_sensor_s::signal_quality, distance_sensor_s::timestamp, and distance_sensor_s::type.
Referenced by cycle(), and read().
void LidarLiteI2C::cycle () private
Perform a poll cycle; collect from the previous measurement and start a new one.
Definition at line 577 of file LidarLiteI2C.cpp.
References _acquire_time_usec, _collect_phase, collect(), cycle_trampoline(), DEVICE_DEBUG, LidarLite::getMeasureTicks(), hrt_absolute_time(), LL40LS_CONVERSION_INTERVAL, LL40LS_CONVERSION_TIMEOUT, measure(), and OK.
Referenced by cycle_trampoline().
void LidarLiteI2C::cycle_trampoline (void * arg) static private
Static trampoline from the workq context; because we don't have a generic workq wrapper yet.
Parameters
arg Instance pointer for the driver that is polling.
Definition at line 570 of file LidarLiteI2C.cpp.
References cycle().
Referenced by cycle(), and start().
const char * LidarLiteI2C::get_dev_name () override virtual
Implements LidarLite.
Definition at line 646 of file LidarLiteI2C.cpp.
int LidarLiteI2C::init () override virtual
Implements LidarLite.
Definition at line 102 of file LidarLiteI2C.cpp.
References _class_instance, _distance_sensor_topic, _orb_class_instance, _reports, _sensor_ok, DEVICE_DEBUG, lis3mdl::init(), measure(), OK, orb_advertise_multi(), ORB_ID, ORB_PRIO_LOW, PX4_ERROR, and RANGE_FINDER_BASE_DEVICE_PATH.
int LidarLiteI2C::ioctl (device::file_t * filp, int cmd, unsigned long arg) override virtual
Reimplemented from LidarLite.
Definition at line 201 of file LidarLiteI2C.cpp.
References _reports, ATOMIC_ENTER, ATOMIC_LEAVE, LidarLite::ioctl(), OK, and SENSORIOCSQUEUEDEPTH.
int LidarLiteI2C::lidar_transfer (const uint8_t * send, unsigned send_len, uint8_t * recv, unsigned recv_len) private
LidarLite specific transfer function.
This is needed to avoid a stop transition with SCL high
Parameters
send Pointer to bytes to send.
send_len Number of bytes to send.
recv Pointer to buffer for bytes received.
recv_len Number of bytes to receive.
Returns
OK if the transfer was successful, -errno otherwise.
Definition at line 153 of file LidarLiteI2C.cpp.
References OK.
Referenced by collect(), measure(), print_registers(), and read_reg().
int LidarLiteI2C::measure () override protected virtual
Implements LidarLite.
Definition at line 293 of file LidarLiteI2C.cpp.
References _acquire_time_usec, _comms_errors, _pause_measurements, _sensor_resets, DEVICE_DEBUG, hrt_absolute_time(), lidar_transfer(), LL40LS_MEASURE_REG, LL40LS_MSRREG_ACQUIRE, OK, perf_count(), perf_event_count(), and reset_sensor().
Referenced by cycle(), init(), and read().
LidarLiteI2C LidarLiteI2C::operator= (const LidarLiteI2C & assignment) private delete
void LidarLiteI2C::print_info () override virtual
Diagnostics - print some basic information about the driver.
Implements LidarLite.
Definition at line 634 of file LidarLiteI2C.cpp.
References _comms_errors, _last_distance, _reports, _sample_perf, _sensor_resets, _sensor_zero_resets, LidarLite::getMeasureTicks(), and perf_print_counter().
void LidarLiteI2C::print_registers () override virtual
print registers to console
Implements LidarLite.
Definition at line 361 of file LidarLiteI2C.cpp.
References _pause_measurements, lidar_transfer(), OK, and usleep().
int LidarLiteI2C::probe () override protected
Definition at line 170 of file LidarLiteI2C.cpp.
References _hw_version, _sw_version, DEVICE_DEBUG, LL40LS_BASEADDR, LL40LS_BASEADDR_OLD, LL40LS_HW_VERSION, LL40LS_SW_VERSION, OK, read_reg(), and reset_sensor().
int LidarLiteI2C::probe_address (uint8_t address) private
Test whether the device supported by the driver is present at a specific address.
Parameters
address The I2C bus address to probe.
Returns
True if the device is present.
ssize_t LidarLiteI2C::read (device::file_t * filp, char * buffer, size_t buflen) override
Definition at line 234 of file LidarLiteI2C.cpp.
References _reports, collect(), LidarLite::getMeasureTicks(), LL40LS_CONVERSION_INTERVAL, measure(), OK, and usleep().
int LidarLiteI2C::read_reg (uint8_t reg, uint8_t & val) protected
Definition at line 138 of file LidarLiteI2C.cpp.
References lidar_transfer().
Referenced by probe().
int LidarLiteI2C::reset_sensor () override protected virtual
Implements LidarLite.
Definition at line 335 of file LidarLiteI2C.cpp.
References LL40LS_MEASURE_REG, LL40LS_MSRREG_RESET, LL40LS_SIG_COUNT_VAL_MAX, LL40LS_SIG_COUNT_VAL_REG, OK, usleep(), and write_reg().
Referenced by collect(), measure(), and probe().
void LidarLiteI2C::start () override private virtual
Initialise the automatic measurement state machine and start it.
Note
This function is called at open and error time. It might make sense to make it more aggressive about resetting the bus in case of errors.
Implements LidarLite.
Definition at line 555 of file LidarLiteI2C.cpp.
References _collect_phase, _reports, and cycle_trampoline().
void LidarLiteI2C::stop () override private virtual
Stop the automatic measurement state machine.
Implements LidarLite.
Definition at line 565 of file LidarLiteI2C.cpp.
Referenced by ~LidarLiteI2C().
int LidarLiteI2C::write_reg (uint8_t reg, uint8_t val) protected
Definition at line 143 of file LidarLiteI2C.cpp.
Referenced by reset_sensor().
Member Data Documentation
uint64_t LidarLiteI2C::_acquire_time_usec private
Definition at line 129 of file LidarLiteI2C.h.
Referenced by collect(), cycle(), LidarLiteI2C(), and measure().
int LidarLiteI2C::_class_instance private
Definition at line 118 of file LidarLiteI2C.h.
Referenced by init(), LidarLiteI2C(), and ~LidarLiteI2C().
bool LidarLiteI2C::_collect_phase private
Definition at line 117 of file LidarLiteI2C.h.
Referenced by cycle(), LidarLiteI2C(), and start().
perf_counter_t LidarLiteI2C::_comms_errors private
Definition at line 124 of file LidarLiteI2C.h.
Referenced by collect(), LidarLiteI2C(), measure(), print_info(), and ~LidarLiteI2C().
orb_advert_t LidarLiteI2C::_distance_sensor_topic private
Definition at line 121 of file LidarLiteI2C.h.
Referenced by collect(), init(), and LidarLiteI2C().
uint8_t LidarLiteI2C::_hw_version private
Definition at line 131 of file LidarLiteI2C.h.
Referenced by LidarLiteI2C(), and probe().
uint16_t LidarLiteI2C::_last_distance private
Definition at line 127 of file LidarLiteI2C.h.
Referenced by collect(), LidarLiteI2C(), and print_info().
int LidarLiteI2C::_orb_class_instance private
Definition at line 119 of file LidarLiteI2C.h.
Referenced by init(), and LidarLiteI2C().
volatile bool LidarLiteI2C::_pause_measurements private
Definition at line 130 of file LidarLiteI2C.h.
Referenced by LidarLiteI2C(), measure(), and print_registers().
ringbuffer::RingBuffer* LidarLiteI2C::_reports private
Definition at line 115 of file LidarLiteI2C.h.
Referenced by collect(), init(), ioctl(), LidarLiteI2C(), print_info(), read(), start(), and ~LidarLiteI2C().
uint8_t LidarLiteI2C::_rotation private
Definition at line 113 of file LidarLiteI2C.h.
Referenced by collect().
perf_counter_t LidarLiteI2C::_sample_perf private
Definition at line 123 of file LidarLiteI2C.h.
Referenced by collect(), LidarLiteI2C(), print_info(), and ~LidarLiteI2C().
bool LidarLiteI2C::_sensor_ok private
Definition at line 116 of file LidarLiteI2C.h.
Referenced by init(), and LidarLiteI2C().
perf_counter_t LidarLiteI2C::_sensor_resets private
Definition at line 125 of file LidarLiteI2C.h.
Referenced by collect(), LidarLiteI2C(), measure(), print_info(), and ~LidarLiteI2C().
perf_counter_t LidarLiteI2C::_sensor_zero_resets private
Definition at line 126 of file LidarLiteI2C.h.
Referenced by collect(), LidarLiteI2C(), print_info(), and ~LidarLiteI2C().
uint8_t LidarLiteI2C::_sw_version private
Definition at line 132 of file LidarLiteI2C.h.
Referenced by LidarLiteI2C(), and probe().
work_s LidarLiteI2C::_work private
Definition at line 114 of file LidarLiteI2C.h.
uint16_t LidarLiteI2C::_zero_counter private
Definition at line 128 of file LidarLiteI2C.h.
Referenced by collect(), and LidarLiteI2C().
The documentation for this class was generated from the following files:
src/drivers/distance_sensor/ll40ls/LidarLiteI2C.h
src/drivers/distance_sensor/ll40ls/LidarLiteI2C.cpp