PX4 Firmware: test_ppm Namespace Reference
test_ppm Namespace Reference
Functions
void start (unsigned channels)
Start the driver.
void stop ()
Stop the driver.
void usage ()
Prints info about the driver argument usage.
void set (unsigned ch, unsigned value)
Variables
TEST_PPM * g_test = nullptr
Function Documentation
set()
void test_ppm::set (unsigned ch, unsigned value)
Definition at line 226 of file test_ppm.cpp.
References TEST_PPM::_channels, TEST_PPM::_gaps, TEST_PPM::_values, and warnx.
Referenced by test_ppm_main().
start()
void test_ppm::start (unsigned channels)
Start the driver.
This function only returns if the driver is up and running or failed to detect the sensor.
Definition at line 180 of file test_ppm.cpp.
References errx, g_test, TEST_PPM::init(), OK, and TEST_PPM::TEST_PPM().
Referenced by test_ppm_main().
stop()
void test_ppm::stop ()
Stop the driver.
Stop the driver.
Definition at line 211 of file test_ppm.cpp.
References g_test, and warnx.
Referenced by test_ppm_main().
usage()
void test_ppm::usage (void)
Prints info about the driver argument usage.
Prints info about the driver argument usage.
Definition at line 241 of file test_ppm.cpp.
References warnx.
Referenced by lis3mdl_main(), rm3100_main(), and test_ppm_main().
Variable Documentation
g_test
TEST_PPM* test_ppm::g_test = nullptr
Definition at line 166 of file test_ppm.cpp.
Referenced by start(), and stop().