PX4 Firmware: DfMS5607Wrapper Class Reference
DfMS5607Wrapper Class Reference
Public Member Functions
DfMS5607Wrapper ()
~DfMS5607Wrapper ()
int start ()
Start automatic measurement.
int stop ()
Stop automatic measurement.
Private Member Functions
int _publish (struct baro_sensor_data &data)
Private Attributes
orb_advert_t _baro_topic
int _baro_orb_class_instance
perf_counter_t _baro_sample_perf
Detailed Description
Definition at line 69 of file df_ms5607_wrapper.cpp.
Constructor & Destructor Documentation
DfMS5607Wrapper()
DfMS5607Wrapper::DfMS5607Wrapper ()
Definition at line 101 of file df_ms5607_wrapper.cpp.
Referenced by df_ms5607_wrapper::start().
~DfMS5607Wrapper()
DfMS5607Wrapper::~DfMS5607Wrapper ()
Definition at line 109 of file df_ms5607_wrapper.cpp.
References _baro_sample_perf, and perf_free().
Member Function Documentation
_publish()
int DfMS5607Wrapper::_publish (struct baro_sensor_data & data) private
Definition at line 147 of file df_ms5607_wrapper.cpp.
References _baro_orb_class_instance, _baro_sample_perf, _baro_topic, hrt_absolute_time(), orb_advertise_multi(), ORB_ID, ORB_PRIO_DEFAULT, orb_publish(), perf_begin(), perf_end(), and sensor_baro_s::timestamp.
start()
int DfMS5607Wrapper::start ()
Start automatic measurement.
Returns
0 on success
Definition at line 114 of file df_ms5607_wrapper.cpp.
References ToneAlarmInterface::init(), and start().
Referenced by df_ms5607_wrapper::start().
stop()
int DfMS5607Wrapper::stop ()
Stop automatic measurement.
Returns
0 on success
Definition at line 134 of file df_ms5607_wrapper.cpp.
References stop().
Referenced by df_ms5607_wrapper::stop().
Member Data Documentation
_baro_orb_class_instance
int DfMS5607Wrapper::_baro_orb_class_instance private
Definition at line 95 of file df_ms5607_wrapper.cpp.
Referenced by _publish().
_baro_sample_perf
perf_counter_t DfMS5607Wrapper::_baro_sample_perf private
Definition at line 97 of file df_ms5607_wrapper.cpp.
Referenced by _publish(), and ~DfMS5607Wrapper().
_baro_topic
orb_advert_t DfMS5607Wrapper::_baro_topic private
Definition at line 93 of file df_ms5607_wrapper.cpp.
Referenced by _publish().
The documentation for this class was generated from the following file:
src/drivers/driver_framework_wrapper/df_ms5607_wrapper/df_ms5607_wrapper.cpp