PX4 Firmware: src/drivers/camera_capture/camera_capture.cpp File Reference
camera_capture.cpp File Reference
Online and offline geotagging from camera feedback.
#include "camera_capture.hpp"
Namespaces
camera_capture
Macros
#define commandParamToInt(n) static_cast<int>(n >= 0 ? n + 0.5f : n - 0.5f)
Functions
static int usage ()
__EXPORT int camera_capture_main (int argc, char *argv[])
Variables
CameraCapture * camera_capture::g_camera_capture {nullptr}
Detailed Description
Online and offline geotagging from camera feedback.
Author
Mohammed Kabir kabir.nosp@m.@uas.nosp@m.ys.io
Definition in file camera_capture.cpp.
Macro Definition Documentation
commandParamToInt
#define commandParamToInt (n) static_cast<int>(n >= 0 ? n + 0.5f : n - 0.5f)
Definition at line 44 of file camera_capture.cpp.
Referenced by CameraCapture::Run().
Function Documentation
camera_capture_main()
int camera_capture_main (int argc, char * argv[])
Definition at line 348 of file camera_capture.cpp.
References CameraCapture::CameraCapture(), camera_capture::g_camera_capture, CameraCapture::reset_statistics(), CameraCapture::set_capture_control(), CameraCapture::start(), CameraCapture::status(), CameraCapture::stop(), and usage().
Referenced by usage().
usage()
static int usage (void) static
Definition at line 340 of file camera_capture.cpp.
References camera_capture_main().
Referenced by camera_capture_main().