PX4 Firmware: src/lib/mathlib/math/matrix_alg.cpp File Reference
matrix_alg.cpp File Reference
Matrix algebra on raw arrays.
#include "matrix_alg.h"
#include <px4_defines.h>
Functions
float * mat_mul (float *A, float *B, uint8_t n)
static void swap (float &a, float &b)
static void mat_pivot (float *A, float *pivot, uint8_t n)
static void mat_forward_sub (float *L, float *out, uint8_t n)
static void mat_back_sub (float *U, float *out, uint8_t n)
static void mat_LU_decompose (float *A, float *L, float *U, float *P, uint8_t n)
bool mat_inverse (float *A, float *inv, uint8_t n)
bool inverse4x4 (float m[], float invOut[])
Detailed Description
Matrix algebra on raw arrays.
Definition in file matrix_alg.cpp.
Function Documentation
bool inverse4x4 (float m[], float invOut[])
Definition at line 260 of file matrix_alg.cpp.
References f(), and matrix::inv().
static void mat_back_sub (float * U, float * out, uint8_t n) static
Definition at line 143 of file matrix_alg.cpp.
Referenced by mat_inverse().
static void mat_forward_sub (float * L, float * out, uint8_t n) static
Definition at line 119 of file matrix_alg.cpp.
Referenced by mat_inverse().
bool mat_inverse (float * A, float * inv, uint8_t n)
Definition at line 215 of file matrix_alg.cpp.
References mat_back_sub(), mat_forward_sub(), mat_LU_decompose(), mat_mul(), and P.
Referenced by run_lm_ellipsoid_fit().
static void mat_LU_decompose (float * A, float * L, float * U, float * P, uint8_t n) static
Definition at line 168 of file matrix_alg.cpp.
References mat_mul(), and mat_pivot().
Referenced by mat_inverse().
float* mat_mul (float * A, float * B, uint8_t n)
Definition at line 53 of file matrix_alg.cpp.
References f().
Referenced by mat_inverse(), and mat_LU_decompose().
static void mat_pivot (float * A, float * pivot, uint8_t n) static
Definition at line 86 of file matrix_alg.cpp.
References swap().
Referenced by mat_LU_decompose().
static void swap (float & a, float & b) inline static
Definition at line 69 of file matrix_alg.cpp.
Referenced by mat_pivot().