PX4 Firmware: ToneAlarm Class Reference
ToneAlarm Class Reference
Public Types
enum { CBRK_OFF = 0, CBRK_ON, CBRK_UNINIT }
enum { CBRK_OFF = 0, CBRK_ON, CBRK_UNINIT }
Public Types inherited from device::Device
enum DeviceBusType { DeviceBusType_UNKNOWN = 0, DeviceBusType_I2C = 1, DeviceBusType_SPI = 2, DeviceBusType_UAVCAN = 3 }
Device bus types for DEVID.
Public Member Functions
ToneAlarm ()
~ToneAlarm ()=default
virtual int init ()
Initialise the driver and make it ready for use.
virtual int ioctl (file *filp, int cmd, unsigned long arg)
virtual ssize_t write (file *filp, const char *buffer, size_t len)
const char * name (int tune)
ToneAlarm ()
~ToneAlarm ()
virtual int init ()
Initialise the driver and make it ready for use.
void status ()
ToneAlarm ()
~ToneAlarm ()=default
virtual int devIOCTL (unsigned long cmd, unsigned long arg)
virtual ssize_t devWrite (const void *buffer, size_t len)
const char * name (int tune)
Public Member Functions inherited from device::CDev
CDev (const char *name, const char *devname)
Constructor.
virtual ~CDev ()
virtual int open (file_t *filep)
Handle an open of the device.
virtual int close (file_t *filep)
Handle a close of the device.
virtual ssize_t read (file_t *filep, char *buffer, size_t buflen)
Perform a read from the device.
virtual ssize_t write (file_t *filep, const char *buffer, size_t buflen)
Perform a write to the device.
virtual off_t seek (file_t *filep, off_t offset, int whence)
Perform a logical seek operation on the device.
virtual int ioctl (file_t *filep, int cmd, unsigned long arg)
Perform an ioctl operation on the device.
virtual int poll (file_t *filep, px4_pollfd_struct_t *fds, bool setup)
Perform a poll setup/teardown operation.
Public Member Functions inherited from device::Device
virtual ~Device ()=default
Destructor.
virtual int read (unsigned address, void *data, unsigned count)
Read directly from the device.
virtual int write (unsigned address, void *data, unsigned count)
Write directly to the device.
virtual int ioctl (unsigned operation, unsigned &arg)
Perform a device-specific operation.
uint8_t get_device_bus ()
Return the bus ID the device is connected to.
DeviceBusType get_device_bus_type ()
Return the bus type the device is connected to.
uint8_t get_device_address ()
Return the bus address of the device.
void set_device_address (int address)
void set_device_type (uint8_t devtype)
Set the device type.
virtual bool external ()
Private Types
enum { MODE_NORMAL, MODE_LEGATO, MODE_STACCATO }
enum { MODE_NORMAL, MODE_LEGATO, MODE_STACCATO }
Private Member Functions
unsigned note_to_divisor (unsigned note)
unsigned note_duration (unsigned &silence, unsigned note_length, unsigned dots)
unsigned rest_duration (unsigned rest_length, unsigned dots)
void start_note (unsigned note)
void stop_note ()
void start_tune (const char *tune)
void next_note ()
int next_char ()
unsigned next_number ()
unsigned next_dots ()
unsigned frequency_to_divisor (unsigned frequency)
void start_note (unsigned frequency)
void stop_note ()
void next_note ()
unsigned note_to_divisor (unsigned note)
unsigned note_duration (unsigned &silence, unsigned note_length, unsigned dots)
unsigned rest_duration (unsigned rest_length, unsigned dots)
void start_note (unsigned note)
void stop_note ()
void start_tune (const char *tune)
void next_note ()
int next_char ()
unsigned next_number ()
unsigned next_dots ()
virtual void _measure ()
Static Private Member Functions
static void next_trampoline (void *arg)
static void next_trampoline (void *arg)
static void next_trampoline (void *arg)
Private Attributes
const char * _default_tunes [TONE_NUMBER_OF_TUNES]
const char * _tune_names [TONE_NUMBER_OF_TUNES]
unsigned _default_tune_number
const char * _user_tune
const char * _tune
const char * _next
unsigned _tempo
unsigned _note_length
enum ToneAlarm:: { ... } _note_mode
unsigned _octave
unsigned _silence_length
bool _repeat
int _cbrk
if true, no audio output
hrt_call _note_call
volatile bool _running
volatile bool _should_run
bool _play_tone
Tunes _tunes
int _tune_control_sub
tune_control_s _tune
enum ToneAlarm:: { ... } _note_mode
Static Private Attributes
static const unsigned _tune_max = 1024 * 8
static const uint8_t _note_tab [] = {9, 11, 0, 2, 4, 5, 7}
static work_s _work
Additional Inherited Members
Protected Member Functions inherited from device::CDev
virtual pollevent_t poll_state (file_t *filep)
Check the current state of the device for poll events from the perspective of the file.
virtual void poll_notify (pollevent_t events)
Report new poll events.
virtual void poll_notify_one (px4_pollfd_struct_t *fds, pollevent_t events)
Internal implementation of poll_notify.
virtual int open_first (file_t *filep)
Notification of the first open.
virtual int close_last (file_t *filep)
Notification of the last close.
virtual int register_class_devname (const char *class_devname)
Register a class device name, automatically adding device class instance suffix if need be.
virtual int unregister_class_devname (const char *class_devname, unsigned class_instance)
Register a class device name, automatically adding device class instance suffix if need be.
const char * get_devname ()
Get the device name.
void lock ()
Take the driver lock.
void unlock ()
Release the driver lock.
Protected Member Functions inherited from device::Device
Device (const char *name)
Device (DeviceBusType bus_type, uint8_t bus, uint8_t address, uint8_t devtype=0)
Device (const Device &)=delete
Device & operator= (const Device &)=delete
Device (Device &&)=delete
Device & operator= (Device &&)=delete
Protected Attributes inherited from device::CDev
px4_sem_t _lock
lock to protect access to all class members (also for derived classes)
bool _pub_blocked {false}
true if publishing should be blocked
Protected Attributes inherited from device::Device
union DeviceId _device_id
device identifier information
const char * _name
driver name
bool _debug_enabled {false}
if true, debug messages are printed
Static Protected Attributes inherited from device::CDev
static const px4_file_operations_t fops = {}
Pointer to the default cdev file operations table; useful for registering clone devices etc.
Detailed Description
Definition at line 198 of file tone_alarm.cpp.
Member Enumeration Documentation
anonymous enum private
Enumerator
MODE_NORMAL
MODE_LEGATO
MODE_STACCATO
Definition at line 144 of file tone_alarm.cpp.
anonymous enum
Enumerator
CBRK_OFF
CBRK_ON
CBRK_UNINIT
Definition at line 213 of file tone_alarm.cpp.
anonymous enum private
Enumerator
MODE_NORMAL
MODE_LEGATO
MODE_STACCATO
Definition at line 234 of file tone_alarm.cpp.
anonymous enum
Enumerator
CBRK_OFF
CBRK_ON
CBRK_UNINIT
Definition at line 311 of file tone_alarm.cpp.
Constructor & Destructor Documentation
ToneAlarm::ToneAlarm ()
Definition at line 302 of file tone_alarm.cpp.
References _default_tunes, _tune_names, TONE_ARMING_FAILURE_TUNE, TONE_ARMING_WARNING_TUNE, TONE_BARO_WARNING_TUNE, TONE_BATTERY_WARNING_FAST_TUNE, TONE_BATTERY_WARNING_SLOW_TUNE, TONE_EKF_WARNING_TUNE, TONE_ERROR_TUNE, TONE_GPS_WARNING_TUNE, TONE_HOME_SET, TONE_NOTIFY_NEGATIVE_TUNE, TONE_NOTIFY_NEUTRAL_TUNE, TONE_NOTIFY_POSITIVE_TUNE, TONE_PARACHUTE_RELEASE_TUNE, TONE_SINGLE_BEEP_TUNE, and TONE_STARTUP_TUNE.
Referenced by _measure(), and tone_alarm_main().
ToneAlarm::~ToneAlarm () default
Definition at line 377 of file tone_alarm.cpp.
References _running, _should_run, counter, DEVICE_DEBUG, GPIO_TONE_ALARM_IDLE, GPIO_TONE_ALARM_NEG, lis3mdl::init(), init(), next_trampoline(), OK, rBDTR, rCCER, rCCMR1, rCCMR2, rCR1, rCR2, rDCR, rDIER, rPSC, rSMCR, and usleep().
ToneAlarm::ToneAlarm ()
ToneAlarm::~ToneAlarm ()
ToneAlarm::ToneAlarm ()
ToneAlarm::~ToneAlarm () default
Member Function Documentation
virtual void ToneAlarm::_measure (void) inline private virtual
Definition at line 201 of file tone_alarm.cpp.
References _note_tab, f(), note_duration(), note_to_divisor(), rest_duration(), tone_alarm_main(), TONE_ARMING_FAILURE_TUNE, TONE_ARMING_WARNING_TUNE, TONE_BARO_WARNING_TUNE, TONE_BATTERY_WARNING_FAST_TUNE, TONE_BATTERY_WARNING_SLOW_TUNE, TONE_EKF_WARNING_TUNE, TONE_ERROR_TUNE, TONE_GPS_WARNING_TUNE, TONE_HOME_SET, TONE_NOTIFY_NEGATIVE_TUNE, TONE_NOTIFY_NEUTRAL_TUNE, TONE_NOTIFY_POSITIVE_TUNE, TONE_PARACHUTE_RELEASE_TUNE, TONE_SINGLE_BEEP_TUNE, TONE_STARTUP_TUNE, ToneAlarm(), and TONEALARM0_DEVICE_PATH.
int ToneAlarm::devIOCTL (unsigned long cmd, unsigned long arg) virtual
Definition at line 644 of file tone_alarm.cpp.
References OK, PX4_DEBUG, PX4_INFO, TONE_NUMBER_OF_TUNES, TONE_SET_ALARM, and TONE_STOP_TUNE.
ssize_t ToneAlarm::devWrite (const void * buffer, size_t len) virtual
Definition at line 691 of file tone_alarm.cpp.
References ets_airspeed::g_dev, OK, PX4_WARN, TONE_SET_ALARM, and TONEALARM0_DEVICE_PATH.
unsigned ToneAlarm::frequency_to_divisor (unsigned frequency) private
Definition at line 449 of file tone_alarm.cpp.
References _cbrk, _play_tone, _running, _should_run, _silence_length, _tune, _tune_control_sub, _tunes, CBRK_BUZZER_KEY, CBRK_OFF, CBRK_UNINIT, circuit_breaker_enabled(), f(), ets_airspeed::g_dev, Tunes::get_maximum_update_interval(), Tunes::get_next_tune(), GPIO_TONE_ALARM, GPIO_TONE_ALARM_IDLE, next_note(), next_trampoline(), orb_check(), orb_copy(), ORB_ID, orb_subscribe(), orb_unsubscribe(), rARR, rCCER, rEGR, rPSC, Tunes::set_control(), start_note(), stop_note(), tone_alarm_usage(), and tune_control.
int ToneAlarm::init () virtual
Initialise the driver and make it ready for use.
Returns
OK if the driver initialized OK, negative errno otherwise;
Reimplemented from device::CDev.
Definition at line 346 of file tone_alarm.cpp.
References _REG, DEVICE_DEBUG, GPIO_TONE_ALARM_IDLE, GPIO_TONE_ALARM_NEG, lis3mdl::init(), OK, rCNSC, rCNT, rCNV, rCOMBINE, rCONF, rFILTER, rMOD, rPOL, rQDCTRL, rSC, rSTATUS, STATUS, TONE_ALARM_COUNTER_PERIOD, TONE_ALARM_SIM_SCGC2_TPM, and TONE_ALARM_TIMER_PRESCALE.
Referenced by ~ToneAlarm().
virtual int ToneAlarm::init () virtual
Initialise the driver and make it ready for use.
Returns
OK if the driver initialized OK, negative errno otherwise;
Reimplemented from device::CDev.
int ToneAlarm::ioctl (file * filp, int cmd, unsigned long arg) virtual
Definition at line 806 of file tone_alarm.cpp.
References _default_tune_number, _default_tunes, _next, _repeat, _tune, DEVICE_DEBUG, OK, start_tune(), TONE_NUMBER_OF_TUNES, TONE_SET_ALARM, and TONE_STOP_TUNE.
Referenced by write().
const char* ToneAlarm::name (int tune) inline
Definition at line 124 of file tone_alarm.cpp.
References TONE_NUMBER_OF_TUNES.
const char* ToneAlarm::name (int tune) inline
Definition at line 208 of file tone_alarm.cpp.
References _tune_names.
int ToneAlarm::next_char () private
int ToneAlarm::next_char () private
Definition at line 756 of file tone_alarm.cpp.
References _next.
Referenced by do_something(), next_dots(), next_note(), and next_number().
unsigned ToneAlarm::next_dots () private
unsigned ToneAlarm::next_dots () private
Definition at line 784 of file tone_alarm.cpp.
References _next, and next_char().
Referenced by do_something(), and next_note().
void ToneAlarm::next_note () private
void ToneAlarm::next_note () private
Definition at line 545 of file tone_alarm.cpp.
References _default_tune_number, _next, _note_call, _note_length, _note_mode, _note_tab, _octave, _repeat, _silence_length, _tempo, _tune, hrt_abstime, hrt_call_after(), MODE_LEGATO, MODE_NORMAL, MODE_STACCATO, next_char(), next_dots(), next_number(), next_trampoline(), note_duration(), rest_duration(), start_note(), start_tune(), stop_note(), and tune_end.
Referenced by do_something(), frequency_to_divisor(), and next_trampoline().
void ToneAlarm::next_note () private
unsigned ToneAlarm::next_number () private
unsigned ToneAlarm::next_number () private
Definition at line 766 of file tone_alarm.cpp.
References _next, and next_char().
Referenced by do_something(), and next_note().
static void ToneAlarm::next_trampoline (void * arg) static private
void ToneAlarm::next_trampoline (void * arg) static private
Definition at line 797 of file tone_alarm.cpp.
References next_note().
Referenced by do_something(), frequency_to_divisor(), next_note(), start_tune(), and ~ToneAlarm().
static void ToneAlarm::next_trampoline (void * arg) static private
unsigned ToneAlarm::note_duration (unsigned & silence, unsigned note_length, unsigned dots) private
unsigned ToneAlarm::note_duration (unsigned & silence, unsigned note_length, unsigned dots) private
Definition at line 430 of file tone_alarm.cpp.
References _note_mode, _tempo, MODE_LEGATO, MODE_NORMAL, and MODE_STACCATO.
Referenced by _measure(), and next_note().
unsigned ToneAlarm::note_to_divisor (unsigned note) private
unsigned ToneAlarm::note_to_divisor (unsigned note) private
Definition at line 414 of file tone_alarm.cpp.
References f(), and TONE_ALARM_TIMER_FREQ.
Referenced by _measure(), and start_note().
unsigned ToneAlarm::rest_duration (unsigned rest_length, unsigned dots) private
unsigned ToneAlarm::rest_duration (unsigned rest_length, unsigned dots) private
Definition at line 468 of file tone_alarm.cpp.
References _tempo.
Referenced by _measure(), and next_note().
void ToneAlarm::start_note (unsigned note) private
void ToneAlarm::start_note (unsigned note) private
Definition at line 489 of file tone_alarm.cpp.
References _cbrk, CBRK_BUZZER_KEY, CBRK_OFF, CBRK_UNINIT, circuit_breaker_enabled(), GPIO_TONE_ALARM, note_to_divisor(), rCNT, rMOD, and rSC.
Referenced by do_something(), frequency_to_divisor(), and next_note().
void ToneAlarm::start_note (unsigned frequency) private
void ToneAlarm::start_tune (const char * tune) private
void ToneAlarm::start_tune (const char * tune) private
Definition at line 523 of file tone_alarm.cpp.
References _next, _note_call, _note_length, _note_mode, _octave, _repeat, _silence_length, _tempo, _tune, hrt_call_after(), hrt_cancel(), MODE_NORMAL, and next_trampoline().
Referenced by do_something(), ioctl(), next_note(), and write().
void ToneAlarm::status ()
Definition at line 439 of file tone_alarm.cpp.
References _running, and PX4_INFO.
void ToneAlarm::stop_note () private
void ToneAlarm::stop_note () private
Definition at line 511 of file tone_alarm.cpp.
References GPIO_TONE_ALARM_IDLE, and rSC.
Referenced by do_something(), frequency_to_divisor(), and next_note().
void ToneAlarm::stop_note () private
int ToneAlarm::write (file * filp, const char * buffer, size_t len) virtual
Definition at line 858 of file tone_alarm.cpp.
References _next, _tune, _tune_max, _user_tune, device::CDev::close(), err, fd, ets_airspeed::g_dev, ioctl(), OK, device::CDev::open(), start_tune(), TONE_SET_ALARM, and TONEALARM0_DEVICE_PATH.
Member Data Documentation
int ToneAlarm::_cbrk private
if true, no audio output
Definition at line 238 of file tone_alarm.cpp.
Referenced by frequency_to_divisor(), and start_note().
unsigned ToneAlarm::_default_tune_number private
Definition at line 225 of file tone_alarm.cpp.
Referenced by ioctl(), and next_note().
const char * ToneAlarm::_default_tunes private
Definition at line 221 of file tone_alarm.cpp.
Referenced by ioctl(), and ToneAlarm().
const char * ToneAlarm::_next private
Definition at line 230 of file tone_alarm.cpp.
Referenced by ioctl(), next_char(), next_dots(), next_note(), next_number(), start_tune(), and write().
hrt_call ToneAlarm::_note_call private
Definition at line 240 of file tone_alarm.cpp.
Referenced by next_note(), and start_tune().
unsigned ToneAlarm::_note_length private
Definition at line 233 of file tone_alarm.cpp.
Referenced by next_note(), and start_tune().
enum { ... } ToneAlarm::_note_mode
enum { ... } ToneAlarm::_note_mode
Referenced by next_note(), note_duration(), and start_tune().
const uint8_t ToneAlarm::_note_tab = {9, 11, 0, 2, 4, 5, 7} static private
Definition at line 223 of file tone_alarm.cpp.
Referenced by _measure(), and next_note().
unsigned ToneAlarm::_octave private
Definition at line 235 of file tone_alarm.cpp.
Referenced by next_note(), and start_tune().
bool ToneAlarm::_play_tone private
Definition at line 320 of file tone_alarm.cpp.
Referenced by frequency_to_divisor().
bool ToneAlarm::_repeat private
Definition at line 237 of file tone_alarm.cpp.
Referenced by ioctl(), next_note(), and start_tune().
volatile bool ToneAlarm::_running private
Definition at line 318 of file tone_alarm.cpp.
Referenced by frequency_to_divisor(), status(), and ~ToneAlarm().
volatile bool ToneAlarm::_should_run private
Definition at line 319 of file tone_alarm.cpp.
Referenced by frequency_to_divisor(), and ~ToneAlarm().
unsigned ToneAlarm::_silence_length private
Definition at line 236 of file tone_alarm.cpp.
Referenced by frequency_to_divisor(), next_note(), and start_tune().
unsigned ToneAlarm::_tempo private
Definition at line 232 of file tone_alarm.cpp.
Referenced by next_note(), note_duration(), rest_duration(), and start_tune().
const char * ToneAlarm::_tune private
Definition at line 229 of file tone_alarm.cpp.
Referenced by frequency_to_divisor(), ioctl(), next_note(), start_tune(), and write().
tune_control_s ToneAlarm::_tune private
Definition at line 329 of file tone_alarm.cpp.
int ToneAlarm::_tune_control_sub private
Definition at line 327 of file tone_alarm.cpp.
Referenced by frequency_to_divisor().
static const unsigned ToneAlarm::_tune_max = 1024 * 8 static private
Definition at line 220 of file tone_alarm.cpp.
Referenced by write().
const char * ToneAlarm::_tune_names private
Definition at line 222 of file tone_alarm.cpp.
Referenced by name(), and ToneAlarm().
Tunes ToneAlarm::_tunes private
Definition at line 322 of file tone_alarm.cpp.
Referenced by frequency_to_divisor().
const char * ToneAlarm::_user_tune private
Definition at line 227 of file tone_alarm.cpp.
Referenced by write().
work_s ToneAlarm::_work static private
Definition at line 331 of file tone_alarm.cpp.
The documentation for this class was generated from the following file:
src/drivers/kinetis/tone_alarm/tone_alarm.cpp