PX4 Firmware: ParameterTest Class Reference
ParameterTest Class Reference
Public Member Functions
virtual bool run_tests ()
Override to run your unit tests.
ParameterTest ()
Public Member Functions inherited from UnitTest
UnitTest ()=default
virtual ~UnitTest ()=default
void print_results ()
Prints results from running of unit tests.
Private Member Functions
bool _assert_parameter_int_value (param_t param, int32_t expected)
bool _assert_parameter_float_value (param_t param, float expected)
bool _set_all_int_parameters_to (int32_t value)
bool SimpleFind ()
bool ResetAll ()
bool ResetAllExcludesOne ()
bool ResetAllExcludesTwo ()
bool ResetAllExcludesBoundaryCheck ()
bool ResetAllExcludesWildcard ()
bool exportImport ()
bool exportImportAll ()
Private Attributes
param_t p0 {PARAM_INVALID}
param_t p1 {PARAM_INVALID}
param_t p2 {PARAM_INVALID}
param_t p3 {PARAM_INVALID}
param_t p4 {PARAM_INVALID}
Additional Inherited Members
Protected Member Functions inherited from UnitTest
virtual void _init (void)
Run before each unit test. Override to provide custom behavior.
virtual void _cleanup (void)
Run after each unit test. Override to provide custom behavior.
void _print_assert (const char *msg, const char *test, const char *file, int line)
void _print_compare (const char *msg, const char *v1_text, int v1, const char *v2_text, int v2, const char *file, int line)
Protected Attributes inherited from UnitTest
int _tests_run {0}
The number of individual unit tests run.
int _tests_failed {0}
The number of unit tests which failed.
int _tests_passed {0}
The number of unit tests which passed.
int _assertions {0}
Total number of assertions tested by all unit tests.
Detailed Description
Definition at line 6 of file test_parameters.cpp.
Constructor & Destructor Documentation
ParameterTest::ParameterTest () inline
Definition at line 11 of file test_parameters.cpp.
References p0, p1, p2, p3, p4, and param_find().
Member Function Documentation
bool ParameterTest::_assert_parameter_float_value (param_t param, float expected) private
Definition at line 57 of file test_parameters.cpp.
References param_get(), ut_compare, and ut_compare_float.
bool ParameterTest::_assert_parameter_int_value (param_t param, int32_t expected) private
Definition at line 47 of file test_parameters.cpp.
References param_get(), and ut_compare.
Referenced by _set_all_int_parameters_to(), ResetAll(), ResetAllExcludesBoundaryCheck(), ResetAllExcludesOne(), ResetAllExcludesTwo(), and ResetAllExcludesWildcard().
bool ParameterTest::_set_all_int_parameters_to (int32_t value) private
Definition at line 67 of file test_parameters.cpp.
References _assert_parameter_int_value(), p0, p1, p2, p3, and param_set().
Referenced by ResetAll(), ResetAllExcludesBoundaryCheck(), ResetAllExcludesOne(), ResetAllExcludesTwo(), and ResetAllExcludesWildcard().
bool ParameterTest::exportImport () private
Definition at line 183 of file test_parameters.cpp.
References f(), p0, p1, p2, p3, p4, param_get(), param_load_default(), param_save_default(), param_set_no_notification(), param_type(), PARAM_TYPE_FLOAT, PARAM_TYPE_INT32, PX4_ERR, PX4_OK, ut_assert, ut_compare, and ut_compare_float.
Referenced by run_tests().
bool ParameterTest::exportImportAll () private
Definition at line 310 of file test_parameters.cpp.
References fd, param_count(), param_export(), param_for_index(), param_get(), param_import(), PARAM_INVALID, param_load_default(), param_reset_all(), param_save_default(), param_set_no_notification(), param_type(), PARAM_TYPE_FLOAT, PARAM_TYPE_INT32, PX4_ERR, PX4_OK, ut_assert, and ut_compare.
Referenced by run_tests().
bool ParameterTest::ResetAll () private
Definition at line 99 of file test_parameters.cpp.
References _assert_parameter_int_value(), _set_all_int_parameters_to(), p0, p1, p2, p3, and param_reset_all().
Referenced by run_tests().
bool ParameterTest::ResetAllExcludesBoundaryCheck () private
Definition at line 149 of file test_parameters.cpp.
References _assert_parameter_int_value(), _set_all_int_parameters_to(), p0, p1, p2, p3, and param_reset_excludes().
Referenced by run_tests().
bool ParameterTest::ResetAllExcludesOne () private
Definition at line 115 of file test_parameters.cpp.
References _assert_parameter_int_value(), _set_all_int_parameters_to(), p0, p1, p2, p3, and param_reset_excludes().
Referenced by run_tests().
bool ParameterTest::ResetAllExcludesTwo () private
Definition at line 132 of file test_parameters.cpp.
References _assert_parameter_int_value(), _set_all_int_parameters_to(), p0, p1, p2, p3, and param_reset_excludes().
Referenced by run_tests().
bool ParameterTest::ResetAllExcludesWildcard () private
Definition at line 166 of file test_parameters.cpp.
References _assert_parameter_int_value(), _set_all_int_parameters_to(), p0, p1, p2, p3, and param_reset_excludes().
Referenced by run_tests().
bool ParameterTest::run_tests () virtual
Override to run your unit tests.
Unit tests should be called using ut_run_test macro.
Returns
true: all unit tests succeeded, false: one or more unit tests failed
Implements UnitTest.
Definition at line 487 of file test_parameters.cpp.
References UnitTest::_tests_failed, exportImport(), exportImportAll(), param_control_autosave(), ResetAll(), ResetAllExcludesBoundaryCheck(), ResetAllExcludesOne(), ResetAllExcludesTwo(), ResetAllExcludesWildcard(), SimpleFind(), test_parameters(), ut_declare_test_c, and ut_run_test.
bool ParameterTest::SimpleFind () private
Definition at line 84 of file test_parameters.cpp.
References param_find(), param_get(), PARAM_INVALID, ut_assert_true, and ut_compare.
Referenced by run_tests().
Member Data Documentation
param_t ParameterTest::p0 {PARAM_INVALID} private
Definition at line 22 of file test_parameters.cpp.
Referenced by _set_all_int_parameters_to(), exportImport(), ParameterTest(), ResetAll(), ResetAllExcludesBoundaryCheck(), ResetAllExcludesOne(), ResetAllExcludesTwo(), and ResetAllExcludesWildcard().
param_t ParameterTest::p1 {PARAM_INVALID} private
Definition at line 23 of file test_parameters.cpp.
Referenced by _set_all_int_parameters_to(), exportImport(), ParameterTest(), ResetAll(), ResetAllExcludesBoundaryCheck(), ResetAllExcludesOne(), ResetAllExcludesTwo(), and ResetAllExcludesWildcard().
param_t ParameterTest::p2 {PARAM_INVALID} private
Definition at line 24 of file test_parameters.cpp.
Referenced by _set_all_int_parameters_to(), exportImport(), ParameterTest(), ResetAll(), ResetAllExcludesBoundaryCheck(), ResetAllExcludesOne(), ResetAllExcludesTwo(), and ResetAllExcludesWildcard().
param_t ParameterTest::p3 {PARAM_INVALID} private
Definition at line 25 of file test_parameters.cpp.
Referenced by _set_all_int_parameters_to(), exportImport(), ParameterTest(), ResetAll(), ResetAllExcludesBoundaryCheck(), ResetAllExcludesOne(), ResetAllExcludesTwo(), and ResetAllExcludesWildcard().
param_t ParameterTest::p4 {PARAM_INVALID} private
Definition at line 26 of file test_parameters.cpp.
Referenced by exportImport(), and ParameterTest().
The documentation for this class was generated from the following file:
src/systemcmds/tests/test_parameters.cpp