PX4 Firmware: control::BlockP Class Reference
control::BlockP Class Reference
A proportional controller.
#include <BlockP.hpp>
Public Member Functions
BlockP (SuperBlock *parent, const char *name)
virtual ~BlockP ()=default
float update (float input)
float getKP ()
Public Member Functions inherited from control::Block
Block (SuperBlock *parent, const char *name)
virtual ~Block ()=default
Block (const Block &)=delete
Block & operator= (const Block &)=delete
Block (Block &&)=delete
Block & operator= (Block &&)=delete
void getName (char *name, size_t n)
virtual void updateParams ()
virtual void setDt (float dt)
float getDt ()
Public Member Functions inherited from ListNode< Block *>
void setSibling (Block * sibling)
const Block * getSibling () const
Protected Attributes
control::BlockParamFloat _kP
Protected Attributes inherited from control::Block
const char * _name
SuperBlock * _parent
float _dt {0.0f}
List< BlockParamBase * > _params
Protected Attributes inherited from ListNode< Block *>
Block * _list_node_sibling
Additional Inherited Members
Protected Member Functions inherited from control::Block
virtual void updateParamsSubclass ()
SuperBlock * getParent ()
List< BlockParamBase * > & getParams ()
Detailed Description
A proportional controller.
http://en.wikipedia.org/wiki/PID_controller
Definition at line 62 of file BlockP.hpp.
Constructor & Destructor Documentation
BlockP()
control::BlockP::BlockP (SuperBlock * parent, const char * name) inline
Definition at line 66 of file BlockP.hpp.
~BlockP()
virtual control::BlockP::~BlockP () virtual default
Member Function Documentation
getKP()
float control::BlockP::getKP () inline
Definition at line 76 of file BlockP.hpp.
Referenced by control::blockPTest(), and blockPTest().
update()
float control::BlockP::update (float input) inline
Definition at line 71 of file BlockP.hpp.
Referenced by control::blockPTest(), and blockPTest().
Member Data Documentation
_kP
control::BlockParamFloat control::BlockP::_kP protected
Definition at line 78 of file BlockP.hpp.
The documentation for this class was generated from the following file:
src/lib/controllib/BlockP.hpp