PX4 Firmware: src/platforms/px4_getopt.h File Reference
px4_getopt.h File Reference
Thread safe version of getopt.
Functions
__BEGIN_DECLS int px4_getopt (int argc, char *argv[], const char *options, int *myoptind, const char **myoptarg)
Detailed Description
Thread safe version of getopt.
Definition in file px4_getopt.h.
Function Documentation
__BEGIN_DECLS int px4_getopt (int argc, char * argv[], const char * options, int * myoptind, const char ** myoptarg)
Definition at line 144 of file px4_getopt.c.
References isvalidopt(), and reorder().
Referenced by accelsim_main(), bebop_flow_main(), bmi055_main(), bmi160_main(), bmm150_main(), bmp280_main(), events::SendEvent::custom_command(), dataman_main(), df_ak8963_wrapper_main(), df_bebop_rangefinder_wrapper_main(), df_hmc5883_wrapper_main(), df_lsm9ds1_wrapper_main(), df_mpu6050_wrapper_main(), df_mpu9250_wrapper_main(), df_trone_wrapper_main(), esc_calib_main(), ets_airspeed_main(), frsky_telemetry_thread_main(), fxas21002c_main(), fxos8701cq_main(), gpssim_main(), gyrosim_main(), TAP_ESC::instantiate(), px4::logger::Logger::instantiate(), GPS::instantiate(), Sensors::instantiate(), ist8310_main(), l3gd20_main(), led_control_main(), leddar_one_main(), linux_pwm_out_main(), lis3mdl_main(), listener_main(), ll40ls_main(), lps22hb_main(), mb12xx_main(), motor_test_main(), mpl3115a2_main(), mpu6000_main(), mpu9250_main(), mpu9x50_main(), ms4525_airspeed_main(), ms5525_airspeed_main(), ms5611_main(), parse_options(), pwm_main(), rc_receiver_main(), reboot_main(), rgbled_main(), sd_bench_main(), sdp3x_airspeed_main(), sf0x_main(), sf1xx_main(), snapdragon_pwm_out_main(), srf02_main(), px4flow::start(), spektrum_rc::task_main(), Mavlink::task_main(), RCInput::task_spawn(), PX4FMU::task_spawn(), teraranger_main(), test_file2(), tfmini_main(), tune_control_main(), uart_esc_main(), ulanding::ulanding_radar_main(), and vl53lxx_main().