PX4 Firmware: DfBmp280Wrapper Class Reference
DfBmp280Wrapper Class Reference
Public Member Functions
DfBmp280Wrapper ()
~DfBmp280Wrapper ()
int start ()
Start automatic measurement.
int stop ()
Stop automatic measurement.
Public Member Functions inherited from BMP280
BMP280 (bmp280::IBMP280 *interface, const char *path)
virtual ~BMP280 ()
virtual int init ()
Initialise the driver and make it ready for use.
virtual ssize_t read (struct file *filp, char *buffer, size_t buflen)
virtual int ioctl (struct file *filp, int cmd, unsigned long arg)
void print_info ()
Diagnostics - print some basic information about the driver.
Public Member Functions inherited from device::CDev
CDev (const char *name, const char *devname)
Constructor.
virtual ~CDev ()
virtual int open (file_t *filep)
Handle an open of the device.
virtual int close (file_t *filep)
Handle a close of the device.
virtual ssize_t read (file_t *filep, char *buffer, size_t buflen)
Perform a read from the device.
virtual ssize_t write (file_t *filep, const char *buffer, size_t buflen)
Perform a write to the device.
virtual off_t seek (file_t *filep, off_t offset, int whence)
Perform a logical seek operation on the device.
virtual int ioctl (file_t *filep, int cmd, unsigned long arg)
Perform an ioctl operation on the device.
virtual int poll (file_t *filep, px4_pollfd_struct_t *fds, bool setup)
Perform a poll setup/teardown operation.
Public Member Functions inherited from device::Device
virtual ~Device ()=default
Destructor.
virtual int read (unsigned address, void *data, unsigned count)
Read directly from the device.
virtual int write (unsigned address, void *data, unsigned count)
Write directly to the device.
virtual int ioctl (unsigned operation, unsigned &arg)
Perform a device-specific operation.
uint8_t get_device_bus ()
Return the bus ID the device is connected to.
DeviceBusType get_device_bus_type ()
Return the bus type the device is connected to.
uint8_t get_device_address ()
Return the bus address of the device.
void set_device_address (int address)
void set_device_type (uint8_t devtype)
Set the device type.
virtual bool external ()
Private Member Functions
int _publish (struct baro_sensor_data &data)
Private Attributes
orb_advert_t _baro_topic
int _baro_orb_class_instance
perf_counter_t _baro_sample_perf
Additional Inherited Members
Public Types inherited from device::Device
enum DeviceBusType { DeviceBusType_UNKNOWN = 0, DeviceBusType_I2C = 1, DeviceBusType_SPI = 2, DeviceBusType_UAVCAN = 3 }
Device bus types for DEVID.
Protected Member Functions inherited from device::CDev
virtual pollevent_t poll_state (file_t *filep)
Check the current state of the device for poll events from the perspective of the file.
virtual void poll_notify (pollevent_t events)
Report new poll events.
virtual void poll_notify_one (px4_pollfd_struct_t *fds, pollevent_t events)
Internal implementation of poll_notify.
virtual int open_first (file_t *filep)
Notification of the first open.
virtual int close_last (file_t *filep)
Notification of the last close.
virtual int register_class_devname (const char *class_devname)
Register a class device name, automatically adding device class instance suffix if need be.
virtual int unregister_class_devname (const char *class_devname, unsigned class_instance)
Register a class device name, automatically adding device class instance suffix if need be.
const char * get_devname ()
Get the device name.
void lock ()
Take the driver lock.
void unlock ()
Release the driver lock.
Protected Member Functions inherited from device::Device
Device (const char *name)
Device (DeviceBusType bus_type, uint8_t bus, uint8_t address, uint8_t devtype=0)
Device (const Device &)=delete
Device & operator= (const Device &)=delete
Device (Device &&)=delete
Device & operator= (Device &&)=delete
Protected Attributes inherited from device::CDev
px4_sem_t _lock
lock to protect access to all class members (also for derived classes)
bool _pub_blocked {false}
true if publishing should be blocked
Protected Attributes inherited from device::Device
union DeviceId _device_id
device identifier information
const char * _name
driver name
bool _debug_enabled {false}
if true, debug messages are printed
Static Protected Attributes inherited from device::CDev
static const px4_file_operations_t fops = {}
Pointer to the default cdev file operations table; useful for registering clone devices etc.
Detailed Description
Definition at line 72 of file df_bmp280_wrapper.cpp.
Constructor & Destructor Documentation
DfBmp280Wrapper::DfBmp280Wrapper ()
Definition at line 104 of file df_bmp280_wrapper.cpp.
Referenced by df_bmp280_wrapper::start().
DfBmp280Wrapper::~DfBmp280Wrapper ()
Definition at line 112 of file df_bmp280_wrapper.cpp.
References _baro_sample_perf, and perf_free().
Member Function Documentation
int DfBmp280Wrapper::_publish (struct baro_sensor_data & data) private
Definition at line 154 of file df_bmp280_wrapper.cpp.
References _baro_orb_class_instance, _baro_sample_perf, _baro_topic, baro_report, hrt_absolute_time(), orb_advertise_multi(), ORB_ID, ORB_PRIO_DEFAULT, orb_publish(), perf_begin(), and perf_end().
int DfBmp280Wrapper::start ()
Start automatic measurement.
Returns
0 on success
Definition at line 117 of file df_bmp280_wrapper.cpp.
References BMP280::init(), PX4_ERR, PX4_INFO, and start().
Referenced by df_bmp280_wrapper::start().
int DfBmp280Wrapper::stop ()
Stop automatic measurement.
Returns
0 on success
Definition at line 141 of file df_bmp280_wrapper.cpp.
References PX4_ERR, and stop().
Referenced by df_bmp280_wrapper::stop().
Member Data Documentation
int DfBmp280Wrapper::_baro_orb_class_instance private
Definition at line 98 of file df_bmp280_wrapper.cpp.
Referenced by _publish().
perf_counter_t DfBmp280Wrapper::_baro_sample_perf private
Definition at line 100 of file df_bmp280_wrapper.cpp.
Referenced by _publish(), and ~DfBmp280Wrapper().
orb_advert_t DfBmp280Wrapper::_baro_topic private
Definition at line 96 of file df_bmp280_wrapper.cpp.
Referenced by _publish().
The documentation for this class was generated from the following file:
src/platforms/posix/drivers/df_bmp280_wrapper/df_bmp280_wrapper.cpp