PX4 Firmware: src/drivers/drv_pwm_trigger.h File Reference
drv_pwm_trigger.h File Reference
#include <px4_defines.h>
#include <stdint.h>
Functions
__BEGIN_DECLS __EXPORT int up_pwm_trigger_init (uint32_t channel_mask)
Intialise the PWM servo outputs using the specified configuration.
__EXPORT void up_pwm_trigger_deinit (void)
De-initialise the PWM trigger outputs.
__EXPORT void up_pwm_trigger_arm (bool armed)
Arm or disarm trigger outputs.
__EXPORT int up_pwm_trigger_set (unsigned channel, uint16_t value)
Set the current output value for a channel.
Function Documentation
__EXPORT void up_pwm_trigger_arm (bool armed)
Arm or disarm trigger outputs.
Bug:
This function should, but does not, guarantee that any pulse currently in progress is cleanly completed.
Parameters
armed If true, outputs are armed; if false they are disarmed.
Definition at line 105 of file drv_pwm_trigger.c.
References IO_TIMER_ALL_MODES_CHANNELS, io_timer_set_enable(), and IOTimerChanMode_Trigger.
Referenced by up_pwm_trigger_deinit(), and up_pwm_trigger_init().
__EXPORT void up_pwm_trigger_deinit (void)
De-initialise the PWM trigger outputs.
Definition at line 87 of file drv_pwm_trigger.c.
References io_timer_channel_init(), io_timer_get_mode_channels(), IOTimerChanMode_NotUsed, IOTimerChanMode_Trigger, MAX_TIMER_IO_CHANNELS, and up_pwm_trigger_arm().
__BEGIN_DECLS __EXPORT int up_pwm_trigger_init (uint32_t channel_mask)
Intialise the PWM servo outputs using the specified configuration.
Parameters
channel_mask Bitmask of channels (LSB = channel 0) to enable. This allows some of the channels to remain configured as GPIOs or as another function.
Returns
OK on success.
Definition at line 65 of file drv_pwm_trigger.c.
References io_timer_channel_init(), io_timer_free_channel(), io_timer_is_channel_free(), IOTimerChanMode_Trigger, MAX_TIMER_IO_CHANNELS, OK, and up_pwm_trigger_arm().
__EXPORT int up_pwm_trigger_set (unsigned channel, uint16_t value)
Set the current output value for a channel.
Parameters
channel The channel to set.
value The output pulse width in microseconds.
Definition at line 60 of file drv_pwm_trigger.c.
References io_timer_set_ccr().