PX4 Firmware: src/drivers/barometer/lps22hb/lps22hb_main.cpp File Reference
lps22hb_main.cpp File Reference
#include "LPS22HB.hpp"
#include <px4_getopt.h>
#include <cstring>
Classes
struct lps22hb::lps22hb_bus_option
Namespaces
lps22hb
Local functions in support of the shell command.
Macros
#define NUM_BUS_OPTIONS (sizeof(bus_options)/sizeof(bus_options[0]))
Enumerations
enum LPS22HB_BUS { LPS22HB_BUS_ALL = 0, LPS22HB_BUS_I2C_INTERNAL, LPS22HB_BUS_I2C_EXTERNAL, LPS22HB_BUS_SPI }
Functions
__EXPORT int lps22hb_main (int argc, char *argv[])
int lps22hb::start (enum LPS22HB_BUS busid)
Start the driver.
bool lps22hb::start_bus (struct lps22hb_bus_option &bus)
start driver for a specific bus option
struct lps22hb_bus_option & lps22hb::find_bus (enum LPS22HB_BUS busid)
find a bus structure for a busid
int lps22hb::reset (enum LPS22HB_BUS busid)
Reset the driver.
int lps22hb::info ()
Print a little info about the driver.
void lps22hb::usage ()
Prints info about the driver argument usage.
Variables
struct lps22hb::lps22hb_bus_option lps22hb::bus_options []
Macro Definition Documentation
#define NUM_BUS_OPTIONS (sizeof(bus_options)/sizeof(bus_options[0]))
Definition at line 76 of file lps22hb_main.cpp.
Referenced by lps22hb::find_bus(), lps22hb::info(), and lps22hb::start().
Enumeration Type Documentation
enum LPS22HB_BUS
Enumerator
LPS22HB_BUS_ALL
LPS22HB_BUS_I2C_INTERNAL
LPS22HB_BUS_I2C_EXTERNAL
LPS22HB_BUS_SPI
Definition at line 42 of file lps22hb_main.cpp.
Function Documentation
int lps22hb_main (int argc, char * argv[])
Definition at line 242 of file lps22hb_main.cpp.
References lps22hb::lps22hb_bus_option::busid, lps22hb::info(), LPS22HB_BUS_ALL, LPS22HB_BUS_I2C_EXTERNAL, LPS22HB_BUS_I2C_INTERNAL, LPS22HB_BUS_SPI, px4_getopt(), PX4_WARN, lps22hb::reset(), lps22hb::start(), and lps22hb::usage().