PX4 Firmware: df_trone_wrapper Namespace Reference
df_trone_wrapper Namespace Reference
Functions
int start (uint8_t rotation)
int stop ()
Stop the driver.
int info ()
Print a little info about the driver.
int probe ()
Who am i.
void usage ()
Prints info about the driver argument usage.
Variables
DfTROneWrapper * g_dev = nullptr
Function Documentation
info()
int df_trone_wrapper::info ()
Print a little info about the driver.
Definition at line 258 of file df_trone_wrapper.cpp.
Referenced by df_trone_wrapper_main().
probe()
int df_trone_wrapper::probe ()
Who am i.
Definition at line 274 of file df_trone_wrapper.cpp.
References DfTROneWrapper::start().
Referenced by df_trone_wrapper_main().
start()
int df_trone_wrapper::start (uint8_t rotation)
Definition at line 203 of file df_trone_wrapper.cpp.
References DfTROneWrapper::DfTROneWrapper(), and DfTROneWrapper::start().
Referenced by df_trone_wrapper_main().
stop()
int df_trone_wrapper::stop ()
Stop the driver.
Stop the driver.
Definition at line 235 of file df_trone_wrapper.cpp.
References g_dev, and DfTROneWrapper::stop().
Referenced by df_trone_wrapper_main().
usage()
void df_trone_wrapper::usage (void)
Prints info about the driver argument usage.
Prints info about the driver argument usage.
Definition at line 301 of file df_trone_wrapper.cpp.
Referenced by df_trone_wrapper_main().
Variable Documentation
g_dev
DfTROneWrapper* df_trone_wrapper::g_dev = nullptr
Definition at line 195 of file df_trone_wrapper.cpp.
Referenced by stop().