PX4 Firmware: rm3100 Namespace Reference
rm3100 Namespace Reference
Classes
struct rm3100_bus_option
Functions
rm3100_bus_option & find_bus (RM3100_BUS bus_id)
Finds a bus structure for a bus_id.
int info (RM3100_BUS bus_id)
Prints info about the driver.
bool init (RM3100_BUS bus_id)
Initializes the driver – sets defaults and starts a cycle.
bool reset (RM3100_BUS bus_id)
Resets the driver.
bool start_bus (struct rm3100_bus_option &bus, Rotation rotation)
Starts the driver for a specific bus option.
int start (RM3100_BUS bus_id, Rotation rotation)
Starts the driver.
int stop ()
Stop the driver.
bool test (RM3100_BUS bus_id)
Perform some basic functional tests on the driver; make sure we can collect data from the sensor in polled and automatic modes.
void usage ()
Prints info about the driver argument usage.
Variables
struct rm3100::rm3100_bus_option bus_options []
Function Documentation
find_bus()
struct rm3100::rm3100_bus_option & rm3100::find_bus (RM3100_BUS bus_id)
Finds a bus structure for a bus_id.
Definition at line 338 of file rm3100_main.cpp.
References bmp280::bus_options, errx, NUM_BUS_OPTIONS, and RM3100_BUS_ALL.
info()
int rm3100::info (RM3100_BUS bus_id)
Prints info about the driver.
Definition at line 49 of file rm3100_main.cpp.
References rm3100::rm3100_bus_option::bus_id, rm3100::rm3100_bus_option::dev, rm3100::rm3100_bus_option::devpath, bmp280::find_bus(), and RM3100::print_info().
Referenced by rm3100_main().
init()
bool rm3100::init (RM3100_BUS bus_id)
Initializes the driver – sets defaults and starts a cycle.
Definition at line 59 of file rm3100_main.cpp.
References rm3100::rm3100_bus_option::devpath, errx, fd, bmp280::find_bus(), SENSOR_POLLRATE_DEFAULT, and SENSORIOCSPOLLRATE.
Referenced by rm3100_main().
reset()
bool rm3100::reset (RM3100_BUS bus_id)
Resets the driver.
Definition at line 216 of file rm3100_main.cpp.
References rm3100::rm3100_bus_option::devpath, fd, bmp280::find_bus(), SENSOR_POLLRATE_DEFAULT, SENSORIOCRESET, and SENSORIOCSPOLLRATE.
Referenced by rm3100_main().
start()
int rm3100::start (RM3100_BUS bus_id, Rotation rotation)
Starts the driver.
This function call only returns once the driver is either successfully up and running or failed to start.
Definition at line 114 of file rm3100_main.cpp.
References bmp280::bus_options, NUM_BUS_OPTIONS, RM3100_BUS_ALL, and bmp280::start_bus().
Referenced by rm3100_main().
start_bus()
bool rm3100::start_bus (struct rm3100_bus_option & bus, Rotation rotation)
Starts the driver for a specific bus option.
Definition at line 85 of file rm3100_main.cpp.
References rm3100::rm3100_bus_option::dev, errx, OK, and warnx.
stop()
int rm3100::stop ()
Stop the driver.
Stop the driver.
Definition at line 137 of file rm3100_main.cpp.
References bmp280::bus_options, qmc5883::bus_options, bmp280::bmp280_bus_option::dev, qmc5883::qmc5883_bus_option::dev, errx, ms5525_airspeed::g_dev, sdp3x_airspeed::g_dev, pmw3902::g_dev, tfmini::g_dev, cm8jl65::g_dev, pmw3901::g_dev, fxos8701cq::g_dev, df_ltc2946_wrapper::g_dev, df_ms5607_wrapper::g_dev, df_ms5611_wrapper::g_dev, df_bebop_rangefinder_wrapper::g_dev, df_bmp280_wrapper::g_dev, df_isl29501_wrapper::g_dev, df_trone_wrapper::g_dev, ets_airspeed::g_dev, df_bebop_bus_wrapper::g_dev, df_ak8963_wrapper::g_dev, df_hmc5883_wrapper::g_dev, meas_airspeed::g_dev, gpssim::g_dev, radar::g_dev, px4flow::g_dev, mb12xx::g_dev, teraranger::g_dev, mappydot::g_dev, leddar_one::g_dev, ina226::g_dev, srf02::g_dev, sf1xx::g_dev, df_mpu6050_wrapper::g_dev, sf0x::g_dev, df_lsm9ds1_wrapper::g_dev, df_mpu9250_wrapper::g_dev, vl53lxx::g_dev, test_ppm::g_test, ll40ls::instance, NUM_BUS_OPTIONS, DfLtc2946Wrapper::stop(), DfBebopBusWrapper::stop(), DfMS5607Wrapper::stop(), DfMS5611Wrapper::stop(), DfBmp280Wrapper::stop(), DfBebopRangeFinderWrapper::stop(), DfAK8963Wrapper::stop(), DfHmc5883Wrapper::stop(), DfTROneWrapper::stop(), DfISL29501Wrapper::stop(), DfMPU6050Wrapper::stop(), DfLsm9ds1Wrapper::stop(), DfMpu9250Wrapper::stop(), QMC5883::stop(), and warnx.
Referenced by cm8jl65_main(), df_ak8963_wrapper_main(), df_bebop_bus_wrapper_main(), df_bebop_rangefinder_wrapper_main(), df_bmp280_wrapper_main(), df_hmc5883_wrapper_main(), df_isl29501_wrapper_main(), df_lsm9ds1_wrapper_main(), df_ltc2946_wrapper_main(), df_mpu6050_wrapper_main(), df_mpu9250_wrapper_main(), df_ms5607_wrapper_main(), df_ms5611_wrapper_main(), df_trone_wrapper_main(), ets_airspeed_main(), fxos8701cq_main(), gpssim_main(), ina226_main(), leddar_one_main(), ll40ls_main(), mappydot_main(), mb12xx_main(), ms4525_airspeed_main(), ms5525_airspeed_main(), paw3902_main(), pmw3901_main(), px4flow_main(), qmc5883_main(), cm8jl65::reset(), rm3100_main(), sdp3x_airspeed_main(), sf0x_main(), sf1xx_main(), spektrum_rc_main(), srf02_main(), teraranger_main(), test_ppm_main(), tfmini_main(), ulanding_radar_main(), and vl53lxx_main().
test()
bool rm3100::test (RM3100_BUS bus_id)
Perform some basic functional tests on the driver; make sure we can collect data from the sensor in polled and automatic modes.
Definition at line 154 of file rm3100_main.cpp.
References rm3100::rm3100_bus_option::devpath, fd, bmp280::find_bus(), mag_report, MAGIOCGEXTERNAL, and read().
Referenced by rm3100_main().
usage()
void rm3100::usage ()
Prints info about the driver argument usage.
Prints info about the driver argument usage.
Definition at line 242 of file rm3100_main.cpp.
References fxos8701cq_main(), IST8310_BUS_I2C_ADDR, IST8310_BUS_I2C_EXTERNAL, IST8310_BUS_I2C_INTERNAL, MAPPYDOT_BUS_DEFAULT, MB12XX_BUS_DEFAULT, mpu6000_main(), paw3902_main(), SRF02_BUS_DEFAULT, VL53LXX_BUS_DEFAULT, and warnx.
Referenced by ak09916_main(), bmi055_main(), bmi088_main(), bmi160_main(), bmm150_main(), cm8jl65_main(), df_ak8963_wrapper_main(), df_bebop_bus_wrapper_main(), df_bebop_rangefinder_wrapper_main(), df_bmp280_wrapper_main(), df_hmc5883_wrapper_main(), df_isl29501_wrapper_main(), df_lsm9ds1_wrapper_main(), df_ltc2946_wrapper_main(), df_mpu6050_wrapper_main(), df_mpu9250_wrapper_main(), df_ms5607_wrapper_main(), df_ms5611_wrapper_main(), df_trone_wrapper_main(), fxas21002c_main(), fxos8701cq_main(), icm20948_main(), ist8310_main(), l3gd20_main(), leddar_one_main(), ll40ls_main(), lps22hb_main(), lps25h_main(), lsm303agr_main(), lsm303d_main(), mappydot_main(), mb12xx_main(), mpl3115a2_main(), mpu6000_main(), paw3902_main(), pmw3901_main(), px4flow_main(), qmc5883_main(), rm3100_main(), spektrum_rc_main(), srf02_main(), teraranger_main(), test_ppm_main(), tfmini_main(), ulanding_radar_main(), vl53lxx_main(), and voxlpm_main().
Variable Documentation
bus_options
struct rm3100::rm3100_bus_option rm3100::bus_options[]
Initial value:
= {
}