PX4 Firmware: src/drivers/boards/av-x-v1/init.c File Reference
init.c File Reference
#include <px4_config.h>
#include <px4_tasks.h>
#include <px4_log.h>
#include <stdbool.h>
#include <stdio.h>
#include <string.h>
#include <debug.h>
#include <errno.h>
#include "platform/cxxinitialize.h"
#include <nuttx/board.h>
#include <nuttx/spi/spi.h>
#include <nuttx/i2c/i2c_master.h>
#include <nuttx/sdio.h>
#include <nuttx/mmcsd.h>
#include <nuttx/analog/adc.h>
#include <nuttx/mm/gran.h>
#include <chip.h>
#include "board_config.h"
#include <stm32_uart.h>
#include <arch/board/board.h>
#include <drivers/drv_hrt.h>
#include <drivers/drv_board_led.h>
#include <systemlib/px4_macros.h>
#include <systemlib/cpuload.h>
#include <perf/perf_counter.h>
#include <systemlib/err.h>
#include <systemlib/hardfault_log.h>
#include <parameters/param.h>
#include <px4_i2c.h>
#include "up_internal.h"
Functions
static int configure_switch (void)
__EXPORT void board_rc_input (bool invert_on, uint32_t uxart_base)
__EXPORT void board_on_reset (int status)
__EXPORT void stm32_boardinitialize (void)
__EXPORT int board_app_initialize (uintptr_t arg)
Function Documentation
__EXPORT int board_app_initialize (uintptr_t arg)
Definition at line 212 of file init.c.
References BBSRAM_PATH, board_autoled_on(), board_dma_alloc_init, BSRAM_FILE_SIZES, configure_switch(), hardfault_check_status(), HARDFAULT_DISPLAY_FORMAT, hardfault_increment_reboot(), hardfault_rearm(), hardfault_write(), hrt_call_every(), hrt_init(), LED_RED, OK, param_init(), PX4_ERR, stm32_sdio_initialize(), stm32_spi_bus_initialize(), and ts_to_abstime().
__EXPORT void board_on_reset (int status)
Definition at line 147 of file init.c.
References arraySize, board_gpio_init(), and PX4_GPIO_PWM_INIT_LIST.
__EXPORT void board_rc_input (bool invert_on, uint32_t uxart_base)
Definition at line 101 of file init.c.
static int configure_switch (void) static
Definition at line 417 of file init.c.
References PX4_ERR, PX4_ERROR, PX4_I2C_BUS_ONBOARD, and PX4_OK.
Referenced by board_app_initialize().
__EXPORT void stm32_boardinitialize (void)
Definition at line 171 of file init.c.
References arraySize, board_autoled_initialize(), board_gpio_init(), board_on_reset(), PX4_GPIO_INIT_LIST, and stm32_spiinitialize().