PX4 Firmware: src/lib/pwm_limit/pwm_limit.cpp File Reference
pwm_limit.cpp File Reference
#include "pwm_limit.h"
#include <px4_defines.h>
#include <math.h>
#include <stdbool.h>
#include <drivers/drv_hrt.h>
#include <stdio.h>
Macros
#define PROGRESS_INT_SCALING 10000
Functions
void pwm_limit_init (pwm_limit_t *limit)
void pwm_limit_calc (const bool armed, const bool pre_armed, const unsigned num_channels, const uint16_t reverse_mask, const uint16_t *disarmed_pwm, const uint16_t *min_pwm, const uint16_t *max_pwm, const float *output, uint16_t *effective_pwm, pwm_limit_t *limit)
Macro Definition Documentation
#define PROGRESS_INT_SCALING 10000
Definition at line 51 of file pwm_limit.cpp.
Referenced by pwm_limit_calc().
Function Documentation
void pwm_limit_calc (const bool armed, const bool pre_armed, const unsigned num_channels, const uint16_t reverse_mask, const uint16_t * disarmed_pwm, const uint16_t * min_pwm, const uint16_t * max_pwm, const float * output, uint16_t * effective_pwm, pwm_limit_t * limit)
Definition at line 59 of file pwm_limit.cpp.
References hrt_absolute_time(), hrt_abstime, hrt_elapsed_time(), INIT_TIME_US, PROGRESS_INT_SCALING, PWM_LIMIT_STATE_INIT, PWM_LIMIT_STATE_OFF, PWM_LIMIT_STATE_ON, PWM_LIMIT_STATE_RAMP, RAMP_TIME_US, pwm_limit_t::state, and pwm_limit_t::time_armed.
Referenced by PX4FMU::cycle(), mixer_tick(), MixerTest::mixerTest(), linux_pwm_out::task_main(), and snapdragon_pwm::task_main().
void pwm_limit_init (pwm_limit_t * limit)
Definition at line 53 of file pwm_limit.cpp.
References PWM_LIMIT_STATE_INIT, pwm_limit_t::state, and pwm_limit_t::time_armed.
Referenced by PX4FMU::init(), MixerTest::mixerTest(), linux_pwm_out::task_main(), snapdragon_pwm::task_main(), and user_start().