PX4 Firmware: src/modules/uavcan/uavcan_module.hpp File Reference
uavcan_module.hpp File Reference
#include <px4_config.h>
#include <drivers/device/device.h>
Macros
#define UAVCAN_MAX_PATH_LENGTH (128 + 40)
#define UAVCAN_FIRMWARE_PATH "/fs/microsd/fw"
#define UAVCAN_ROMFS_FW_PATH "/etc/firmware/uavcan"
#define UAVCAN_ROMFS_FW_PREFIX "_"
#define UAVCAN_NODE_DB_PATH "/fs/microsd/uavcan.db"
#define UAVCAN_LOG_FILE UAVCAN_NODE_DB_PATH"/trace.log"
#define UAVCAN_DEVICE_PATH "/dev/uavcan/esc"
#define UAVCAN_ESC_DEVICE_PATH "/dev/uavcan/esc"
#define _UAVCAN_IOC(_n) (_IOC(_UAVCAN_IOCBASE, _n))
#define _UAVCAN_IOCBASE (0x4000)
#define UAVCAN_IOCG_NODEID_INPROGRESS _UAVCAN_IOC(1)
#define UAVCAN_IOCS_HARDPOINT_SET _UAVCAN_IOC(10)
Functions
__EXPORT int uavcan_main (int argc, char *argv[])
Macro Definition Documentation
#define _UAVCAN_IOC (_n) (_IOC(_UAVCAN_IOCBASE, _n))
Definition at line 66 of file uavcan_module.hpp.
#define _UAVCAN_IOCBASE (0x4000)
Definition at line 67 of file uavcan_module.hpp.
#define UAVCAN_DEVICE_PATH "/dev/uavcan/esc"
Definition at line 62 of file uavcan_module.hpp.
#define UAVCAN_ESC_DEVICE_PATH "/dev/uavcan/esc"
Definition at line 63 of file uavcan_module.hpp.
#define UAVCAN_FIRMWARE_PATH "/fs/microsd/fw"
Definition at line 52 of file uavcan_module.hpp.
Referenced by UavcanServers::init(), and UavcanServers::run().
#define UAVCAN_IOCG_NODEID_INPROGRESS _UAVCAN_IOC(1)
Definition at line 74 of file uavcan_module.hpp.
Referenced by UavcanNode::ioctl().
#define UAVCAN_IOCS_HARDPOINT_SET _UAVCAN_IOC(10)
Definition at line 79 of file uavcan_module.hpp.
Referenced by UavcanNode::ioctl().
#define UAVCAN_LOG_FILE UAVCAN_NODE_DB_PATH"/trace.log"
Definition at line 58 of file uavcan_module.hpp.
Referenced by UavcanServers::init().
#define UAVCAN_MAX_PATH_LENGTH (128 + 40)
Definition at line 51 of file uavcan_module.hpp.
Referenced by UavcanServers::unpackFwFromROMFS().
#define UAVCAN_NODE_DB_PATH "/fs/microsd/uavcan.db"
Definition at line 57 of file uavcan_module.hpp.
Referenced by UavcanServers::init().
#define UAVCAN_ROMFS_FW_PATH "/etc/firmware/uavcan"
Definition at line 53 of file uavcan_module.hpp.
Referenced by UavcanServers::run().
#define UAVCAN_ROMFS_FW_PREFIX "_"
Definition at line 54 of file uavcan_module.hpp.
Referenced by UavcanServers::unpackFwFromROMFS().
Function Documentation
__EXPORT int uavcan_main (int argc, char * argv[])
Definition at line 1282 of file uavcan_main.cpp.
References UavcanNode::arm_actuators(), UavcanNode::CheckFW, command, errx, UavcanNode::fw_server(), UavcanNode::get_node(), UavcanNode::get_param(), UavcanNode::hardpoint_controller_set(), UavcanServers::instance(), UavcanNode::instance(), UavcanNode::list_params(), param_find(), param_get(), UavcanNode::print_info(), print_usage(), PX4_ERR, PX4_INFO, UavcanNode::reset_node(), UavcanNode::save_params(), UavcanNode::set_param(), UavcanNode::shrink(), UavcanNode::Start, UavcanNode::start(), and UavcanNode::Stop.
Referenced by print_usage().