PX4 Firmware: src/drivers/qurt/fc_addon/uart_esc/uart_esc_main.cpp File Reference
uart_esc_main.cpp File Reference
#include <stdint.h>
#include <px4_platform_common/tasks.h>
#include <px4_platform_common/getopt.h>
#include <px4_platform_common/posix.h>
#include <errno.h>
#include <uORB/uORB.h>
#include <uORB/topics/actuator_controls.h>
#include <uORB/topics/actuator_armed.h>
#include <uORB/topics/actuator_outputs.h>
#include <uORB/topics/parameter_update.h>
#include <drivers/drv_hrt.h>
#include <drivers/drv_mixer.h>
#include <lib/mixer/MixerGroup.hpp>
#include <lib/mixer/mixer_multirotor_normalized.generated.h>
#include <parameters/param.h>
#include <uart_esc.h>
Namespaces
uart_esc
Macros
#define MAX_LEN_DEV_PATH 32
#define UART_ESC_MAX_MOTORS 4
Functions
__EXPORT int uart_esc_main (int argc, char *argv[])
driver 'main' command
void uart_esc::uart_esc_rotate_motors (int16_t *motor_rpm, int num_rotors)
Rotate the motor rpm values based on the motor mappings configuration stored in motor_mapping.
static void uart_esc::usage ()
Print out the usage information.
static void uart_esc::start (const char *device) __attribute__((unused))
uart_esc start
static void uart_esc::stop ()
uart_esc stop
static void uart_esc::task_main_trampoline (int argc, char *argv[])
task main trampoline function
static void uart_esc::task_main (int argc, char *argv[])
uart_esc thread primary entry point
static int uart_esc::initialize_mixer (const char *mixer_filename)
static int uart_esc::mixer_control_callback (uintptr_t handle, uint8_t control_group, uint8_t control_index, float &input)
static void uart_esc::parameters_init ()
static void uart_esc::parameters_update ()
void uart_esc::start ()
Attempt to start driver on all available I2C busses.
Variables
volatile bool uart_esc::_task_should_exit = false
static char uart_esc::_device [MAX_LEN_DEV_PATH]
static bool uart_esc::_is_running = false
static px4_task_t uart_esc::_task_handle = -1
UartEsc * uart_esc::esc
int uart_esc::_controls_sub
int uart_esc::_armed_sub
int uart_esc::_param_sub
static const char * uart_esc::MIXER_FILENAME = "/dev/fs/mixer_config.mix"
orb_advert_t uart_esc::_outputs_pub
actuator_controls_s uart_esc::_controls
actuator_armed_s uart_esc::_armed
parameter_update_s uart_esc::_param_update
actuator_outputs_s uart_esc::_outputs
static MultirotorMixer * uart_esc::mixer
mixer initialization
struct {
int uart_esc::model
int uart_esc::baudrate
int uart_esc::px4_motor_mapping [UART_ESC_MAX_MOTORS]
} uart_esc::_parameters
struct {
param_t uart_esc::model
param_t uart_esc::baudrate
param_t uart_esc::px4_motor_mapping [UART_ESC_MAX_MOTORS]
} uart_esc::_parameter_handles
Macro Definition Documentation
MAX_LEN_DEV_PATH
#define MAX_LEN_DEV_PATH 32
Definition at line 64 of file uart_esc_main.cpp.
Referenced by uart_esc_main().
UART_ESC_MAX_MOTORS
#define UART_ESC_MAX_MOTORS 4
Definition at line 68 of file uart_esc_main.cpp.
Referenced by uart_esc::parameters_init(), uart_esc::parameters_update(), uart_esc::task_main(), and uart_esc::uart_esc_rotate_motors().
Function Documentation
uart_esc_main()
int uart_esc_main (int argc, char * argv[])
driver 'main' command
Definition at line 460 of file uart_esc_main.cpp.
References uart_esc::_device, uart_esc::_is_running, MAX_LEN_DEV_PATH, uart_esc::start(), uart_esc::stop(), and uart_esc::usage().