PX4 Firmware: i2cdetect Namespace Reference
i2cdetect Namespace Reference
Functions
int detect (int bus)
int usage (const char *reason=nullptr)
Print the correct usage.
Function Documentation
detect()
int i2cdetect::detect (int bus)
Definition at line 50 of file i2cdetect.cpp.
References recv_data(), and send_data().
Referenced by i2cdetect_main().
usage()
int i2cdetect::usage (const char * reason = nullptr)
Print the correct usage.
Definition at line 130 of file i2cdetect.cpp.
References i2cdetect_main().
Referenced by rpi_rc_in::RcInput::_measure(), linux_sbus::RcInput::_measure(), i2cdetect_main(), linux_sbus_main(), and rpi_rc_in_main().