PX4 Firmware: src/platforms/common/work_queue/wqueue_test/wqueue_start_posix.cpp File Reference
wqueue_start_posix.cpp File Reference
#include "wqueue_test.h"
#include <px4_app.h>
#include <px4_log.h>
#include <px4_tasks.h>
#include <stdio.h>
#include <string.h>
#include <sched.h>
Functions
__EXPORT int wqueue_test_main (int argc, char *argv[])
Variables
static int daemon_task
Detailed Description
Author
Thomas Gubler thoma.nosp@m.sgub.nosp@m.ler@g.nosp@m.mail.nosp@m..com
Mark Charlebois mchar.nosp@m.leb@.nosp@m.gmail.nosp@m..com
Definition in file wqueue_start_posix.cpp.
Function Documentation
int wqueue_test_main (int argc, char * argv[])
Definition at line 54 of file wqueue_start_posix.cpp.
References WQueueTest::appState, daemon_task, PX4_INFO, PX4_MAIN(), px4_task_spawn_cmd(), px4::AppState::requestExit(), SCHED_DEFAULT, and SCHED_PRIORITY_MAX.
Variable Documentation
int daemon_task static
Definition at line 49 of file wqueue_start_posix.cpp.
Referenced by wqueue_test_main().