PX4 Firmware: uORB::PublicationMultiData< T > Class Template Reference
uORB::PublicationMultiData< T > Class Template Reference
The publication multi class with data embedded.
#include <PublicationMulti.hpp>
Public Member Functions
PublicationMultiData (const orb_metadata *meta, uint8_t priority=ORB_PRIO_DEFAULT)
Constructor.
~PublicationMultiData ()=default
T & get ()
void set (const T &data)
bool update ()
bool update (const T &data)
Public Member Functions inherited from uORB::PublicationMulti< T >
PublicationMulti (const orb_metadata *meta, uint8_t priority=ORB_PRIO_DEFAULT)
Constructor.
~PublicationMulti ()
bool publish (const T &data)
Publish the struct.
Private Attributes
T _data {}
Additional Inherited Members
Protected Attributes inherited from uORB::PublicationMulti< T >
const orb_metadata * _meta
orb_advert_t _handle {nullptr}
const uint8_t _priority
Detailed Description
template<typename T>
class uORB::PublicationMultiData< T >
The publication multi class with data embedded.
Definition at line 103 of file PublicationMulti.hpp.
Constructor & Destructor Documentation
PublicationMultiData()
template<typename T> uORB::PublicationMultiData< T >::PublicationMultiData (const orb_metadata * meta, uint8_t priority = ORB_PRIO_DEFAULT) inline
Constructor.
Parameters
meta The uORB metadata (usually from the ORB_ID() macro) for the topic.
priority The priority for multi pub
Definition at line 112 of file PublicationMulti.hpp.
~PublicationMultiData()
template<typename T> uORB::PublicationMultiData< T >::~PublicationMultiData () default
Member Function Documentation
get()
template<typename T> T& uORB::PublicationMultiData< T >::get () inline
Definition at line 118 of file PublicationMulti.hpp.
Referenced by PX4Magnetometer::ioctl(), PX4Accelerometer::ioctl(), PX4Gyroscope::ioctl(), PX4Rangefinder::print_status(), PX4Barometer::print_status(), PX4Magnetometer::print_status(), PX4Accelerometer::print_status(), PX4Gyroscope::print_status(), PX4Accelerometer::PX4Accelerometer(), PX4Barometer::PX4Barometer(), PX4Gyroscope::PX4Gyroscope(), PX4Magnetometer::PX4Magnetometer(), PX4Rangefinder::set_device_id(), PX4Barometer::set_device_type(), PX4Magnetometer::set_device_type(), PX4Accelerometer::set_device_type(), PX4Gyroscope::set_device_type(), PX4Barometer::set_error_count(), PX4Magnetometer::set_error_count(), PX4Accelerometer::set_error_count(), PX4Gyroscope::set_error_count(), PX4Magnetometer::set_external(), PX4Rangefinder::set_hfov(), PX4Rangefinder::set_max_distance(), PX4Rangefinder::set_min_distance(), PX4Rangefinder::set_orientation(), PX4Magnetometer::set_scale(), PX4Accelerometer::set_scale(), PX4Gyroscope::set_scale(), PX4Barometer::set_temperature(), PX4Magnetometer::set_temperature(), PX4Accelerometer::set_temperature(), PX4Gyroscope::set_temperature(), PX4Rangefinder::set_vfov(), PX4Barometer::update(), PX4Magnetometer::update(), PX4Accelerometer::update(), PX4Gyroscope::update(), and PX4Rangefinder::update().
set()
template<typename T> void uORB::PublicationMultiData< T >::set (const T & data) inline
Definition at line 119 of file PublicationMulti.hpp.
update() [1/2]
template<typename T> bool uORB::PublicationMultiData< T >::update () inline
Definition at line 122 of file PublicationMulti.hpp.
Referenced by PX4Barometer::update(), PX4Magnetometer::update(), PX4Accelerometer::update(), PX4Gyroscope::update(), and PX4Rangefinder::update().
update() [2/2]
template<typename T> bool uORB::PublicationMultiData< T >::update (const T & data) inline
Definition at line 123 of file PublicationMulti.hpp.
Member Data Documentation
_data
template<typename T> T uORB::PublicationMultiData< T >::_data {} private
Definition at line 130 of file PublicationMulti.hpp.
The documentation for this class was generated from the following file:
src/modules/uORB/PublicationMulti.hpp