PX4 Firmware: MavlinkStreamActuatorControlTarget< N > Class Template Reference
MavlinkStreamActuatorControlTarget< N > Class Template Reference
Public Member Functions
const char * get_name () const override
uint16_t get_id () override
unsigned get_size () override
Get maximal total messages size on update.
Public Member Functions inherited from MavlinkStream
MavlinkStream (Mavlink *mavlink)
virtual ~MavlinkStream ()=default
MavlinkStream (const MavlinkStream &)=delete
MavlinkStream & operator= (const MavlinkStream &)=delete
MavlinkStream (MavlinkStream &&)=delete
MavlinkStream & operator= (MavlinkStream &&)=delete
void set_interval (const int interval)
Get the interval.
int get_interval ()
Get the interval.
int update (const hrt_abstime &t)
Update subscriptions and send message if necessary.
virtual bool const_rate ()
virtual unsigned get_size_avg ()
Get the average message size.
bool first_message_sent () const
void reset_last_sent ()
Reset the time of last sent to 0.
Public Member Functions inherited from ListNode< MavlinkStream *>
void setSibling (MavlinkStream * sibling)
const MavlinkStream * getSibling () const
Static Public Member Functions
static const char * get_name_static ()
static uint16_t get_id_static ()
static MavlinkStream * new_instance (Mavlink *mavlink)
Protected Member Functions
MavlinkStreamActuatorControlTarget (Mavlink *mavlink)
bool send (const hrt_abstime t) override
Protected Member Functions inherited from MavlinkStream
virtual void update_data ()
Function to collect/update data for the streams at a high rate independant of actual stream rate.
Private Member Functions
MavlinkStreamActuatorControlTarget (MavlinkStreamActuatorControlTarget &)=delete
MavlinkStreamActuatorControlTarget & operator= (const MavlinkStreamActuatorControlTarget &)=delete
Private Attributes
MavlinkOrbSubscription * _act_ctrl_sub
uint64_t _act_ctrl_time
Additional Inherited Members
Protected Attributes inherited from MavlinkStream
Mavlink *const _mavlink
int _interval {1000000}
if set to negative value = unlimited rate
Protected Attributes inherited from ListNode< MavlinkStream *>
MavlinkStream * _list_node_sibling
Detailed Description
template<int N>
class MavlinkStreamActuatorControlTarget< N >
Definition at line 2964 of file mavlink_messages.cpp.
Constructor & Destructor Documentation
MavlinkStreamActuatorControlTarget() [1/2]
template<int N> MavlinkStreamActuatorControlTarget< N >::MavlinkStreamActuatorControlTarget (MavlinkStreamActuatorControlTarget< N > &) private delete
MavlinkStreamActuatorControlTarget() [2/2]
template<int N> MavlinkStreamActuatorControlTarget< N >::MavlinkStreamActuatorControlTarget (Mavlink * mavlink) inline explicit protected
Definition at line 3018 of file mavlink_messages.cpp.
References MavlinkStream::_mavlink, Mavlink::add_orb_subscription(), and ORB_ID.
Member Function Documentation
get_id()
template<int N> uint16_t MavlinkStreamActuatorControlTarget< N >::get_id () inline override virtual
Implements MavlinkStream.
Definition at line 2994 of file mavlink_messages.cpp.
References MavlinkStreamHeartbeat::get_id_static().
get_id_static()
template<int N> static uint16_t MavlinkStreamActuatorControlTarget< N >::get_id_static () inline static
Definition at line 2989 of file mavlink_messages.cpp.
get_name()
template<int N> const char* MavlinkStreamActuatorControlTarget< N >::get_name () const inline override virtual
Implements MavlinkStream.
Definition at line 2967 of file mavlink_messages.cpp.
References MavlinkStreamActuatorControlTarget< N >::get_name_static().
get_name_static()
template<int N> static const char* MavlinkStreamActuatorControlTarget< N >::get_name_static () inline static
Definition at line 2972 of file mavlink_messages.cpp.
Referenced by MavlinkStreamActuatorControlTarget< N >::get_name().
get_size()
template<int N> unsigned MavlinkStreamActuatorControlTarget< N >::get_size () inline override virtual
Get maximal total messages size on update.
Implements MavlinkStream.
Definition at line 3004 of file mavlink_messages.cpp.
new_instance()
template<int N> static MavlinkStream* MavlinkStreamActuatorControlTarget< N >::new_instance (Mavlink * mavlink) inline static
Definition at line 2999 of file mavlink_messages.cpp.
operator=()
template<int N> MavlinkStreamActuatorControlTarget& MavlinkStreamActuatorControlTarget< N >::operator= (const MavlinkStreamActuatorControlTarget< N > &) private delete
send()
template<int N> bool MavlinkStreamActuatorControlTarget< N >::send (const hrt_abstime t) inline override protected virtual
Implements MavlinkStream.
Definition at line 3042 of file mavlink_messages.cpp.
References MavlinkStream::_mavlink, actuator_controls_s::control, Mavlink::get_channel(), msg, actuator_controls_s::timestamp, and MavlinkOrbSubscription::update().
Member Data Documentation
_act_ctrl_sub
template<int N> MavlinkOrbSubscription* MavlinkStreamActuatorControlTarget< N >::_act_ctrl_sub private
Definition at line 3010 of file mavlink_messages.cpp.
_act_ctrl_time
template<int N> uint64_t MavlinkStreamActuatorControlTarget< N >::_act_ctrl_time private
Definition at line 3011 of file mavlink_messages.cpp.
The documentation for this class was generated from the following file:
src/modules/mavlink/mavlink_messages.cpp