PX4 Firmware: BMA180 Class Reference
BMA180 Class Reference
Public Member Functions
BMA180 (int bus, uint32_t device)
virtual ~BMA180 ()
virtual int init ()
virtual ssize_t read (struct file *filp, char *buffer, size_t buflen)
virtual int ioctl (struct file *filp, int cmd, unsigned long arg)
void print_info ()
Diagnostics - print some basic information about the driver.
Protected Member Functions
virtual int probe ()
Private Member Functions
void start ()
Start automatic measurement.
void stop ()
Stop automatic measurement.
void measure ()
Fetch measurements from the sensor and update the report ring.
uint8_t read_reg (unsigned reg)
Read a register from the BMA180.
void write_reg (unsigned reg, uint8_t value)
Write a register in the BMA180.
void modify_reg (unsigned reg, uint8_t clearbits, uint8_t setbits)
Modify a register in the BMA180.
int set_range (unsigned max_g)
Set the BMA180 measurement range.
int set_lowpass (unsigned frequency)
Set the BMA180 internal lowpass filter frequency.
Static Private Member Functions
static void measure_trampoline (void *arg)
Static trampoline from the hrt_call context; because we don't have a generic hrt wrapper yet.
Private Attributes
struct hrt_call _call
unsigned _call_interval
ringbuffer::RingBuffer * _reports
struct accel_calibration_s _accel_scale
float _accel_range_scale
float _accel_range_m_s2
orb_advert_t _accel_topic
int _class_instance
unsigned _current_lowpass
unsigned _current_range
perf_counter_t _sample_perf
Detailed Description
Definition at line 124 of file bma180.cpp.
Constructor & Destructor Documentation
BMA180::BMA180 (int bus, uint32_t device)
Definition at line 233 of file bma180.cpp.
References _accel_scale, DRV_ACC_DEVTYPE_BMA180, accel_calibration_s::x_offset, accel_calibration_s::x_scale, accel_calibration_s::y_offset, accel_calibration_s::y_scale, accel_calibration_s::z_offset, and accel_calibration_s::z_scale.
Referenced by bma180::start().
BMA180::~BMA180 () virtual
Definition at line 256 of file bma180.cpp.
References _reports, _sample_perf, perf_free(), and stop().
Member Function Documentation
int BMA180::init () virtual
Definition at line 271 of file bma180.cpp.
References _accel_topic, _class_instance, _reports, ACCEL_DEVICE_PATH, accel_report, ADDR_CHIP_ID, ADDR_CTRL_REG0, ADDR_GAIN_Y, ADDR_HIGH_DUR, ADDR_OFFSET_T, ADDR_RESET, ADDR_TCO_Z, CHIP_ID, CLASS_DEVICE_PRIMARY, GAIN_Y_SHADOW_DIS, HIGH_DUR_DIS_I2C, lis3mdl::init(), measure(), modify_reg(), OFFSET_T_READOUT_12BIT, OK, orb_advertise(), ORB_ID, PX4_ERROR, read_reg(), REG0_WRITE_ENABLE, set_lowpass(), set_range(), SOFT_RESET, TCO_Z_MODE_MASK, usleep(), warnx, and write_reg().
Referenced by bma180::start().
int BMA180::ioctl (struct file * filp, int cmd, unsigned long arg) virtual
Definition at line 396 of file bma180.cpp.
References _accel_scale, _call, _call_interval, _current_range, _reports, ACCELIOCGRANGE, ACCELIOCGSAMPLERATE, ACCELIOCGSCALE, ACCELIOCSRANGE, ACCELIOCSSAMPLERATE, ACCELIOCSSCALE, OK, hrt_call::period, SENSOR_POLLRATE_DEFAULT, SENSOR_POLLRATE_EXTERNAL, SENSOR_POLLRATE_MANUAL, SENSOR_POLLRATE_MAX, SENSORIOCGPOLLRATE, SENSORIOCRESET, SENSORIOCSPOLLRATE, SENSORIOCSQUEUEDEPTH, set_range(), start(), and stop().
Referenced by bma180::reset(), bma180::start(), and bma180::test().
void BMA180::measure () private
Fetch measurements from the sensor and update the report ring.
Definition at line 672 of file bma180.cpp.
References _accel_range_scale, _accel_scale, _accel_topic, _reports, _sample_perf, accel_report, ADDR_ACC_X_LSB, hrt_absolute_time(), ORB_ID, orb_publish(), perf_begin(), perf_end(), read_reg(), accel_calibration_s::x_offset, accel_calibration_s::x_scale, accel_calibration_s::y_offset, accel_calibration_s::y_scale, accel_calibration_s::z_offset, and accel_calibration_s::z_scale.
Referenced by init(), measure_trampoline(), and read().
void BMA180::measure_trampoline (void * arg) static private
Static trampoline from the hrt_call context; because we don't have a generic hrt wrapper yet.
Called by the HRT in interrupt context at the specified rate if automatic polling is enabled.
Parameters
arg Instance pointer for the driver that is polling.
Definition at line 663 of file bma180.cpp.
References measure().
Referenced by start().
void BMA180::modify_reg (unsigned reg, uint8_t clearbits, uint8_t setbits) private
Modify a register in the BMA180.
Bits are cleared before bits are set.
Parameters
reg The register to modify.
clearbits Bits in the register to clear.
setbits Bits in the register to set.
Definition at line 531 of file bma180.cpp.
References read_reg(), and write_reg().
Referenced by init(), set_lowpass(), and set_range().
void BMA180::print_info ()
Diagnostics - print some basic information about the driver.
Definition at line 746 of file bma180.cpp.
References _reports, _sample_perf, and perf_print_counter().
Referenced by bma180::info().
int BMA180::probe () protected virtual
Definition at line 340 of file bma180.cpp.
References ADDR_CHIP_ID, CHIP_ID, OK, and read_reg().
ssize_t BMA180::read (struct file * filp, char * buffer, size_t buflen) virtual
Definition at line 353 of file bma180.cpp.
References _call_interval, _reports, accel_report, and measure().
Referenced by bma180::test().
uint8_t BMA180::read_reg (unsigned reg) private
Read a register from the BMA180.
Parameters
The register to read.
Returns
The value that was read.
Definition at line 508 of file bma180.cpp.
References DIR_READ.
Referenced by init(), measure(), modify_reg(), probe(), set_lowpass(), and set_range().
int BMA180::set_lowpass (unsigned frequency) private
Set the BMA180 internal lowpass filter frequency.
Parameters
frequency The internal lowpass filter frequency is set to a value equal or greater to this. Zero selects the highest frequency supported.
Returns
OK if the value can be supported.
Definition at line 597 of file bma180.cpp.
References ADDR_BW_TCS, ADDR_CTRL_REG0, BW_TCS_BW_10HZ, BW_TCS_BW_1200HZ, BW_TCS_BW_150HZ, BW_TCS_BW_20HZ, BW_TCS_BW_300HZ, BW_TCS_BW_40HZ, BW_TCS_BW_600HZ, BW_TCS_BW_75HZ, BW_TCS_BW_MASK, modify_reg(), read_reg(), and REG0_WRITE_ENABLE.
Referenced by init().
int BMA180::set_range (unsigned max_g) private
Set the BMA180 measurement range.
Parameters
max_g The maximum G value the range must support.
Returns
OK if the value can be supported, -ERANGE otherwise.
Definition at line 542 of file bma180.cpp.
References _accel_range_m_s2, _accel_range_scale, _current_range, ADDR_CTRL_REG0, ADDR_OFFSET_LSB1, CONSTANTS_ONE_G, modify_reg(), OFFSET_LSB1_RANGE_16G, OFFSET_LSB1_RANGE_2G, OFFSET_LSB1_RANGE_3G, OFFSET_LSB1_RANGE_4G, OFFSET_LSB1_RANGE_8G, OFFSET_LSB1_RANGE_MASK, read_reg(), and REG0_WRITE_ENABLE.
Referenced by init(), and ioctl().
void BMA180::start () private
Start automatic measurement.
Definition at line 644 of file bma180.cpp.
References _call, _call_interval, _reports, hrt_call_every(), measure_trampoline(), and stop().
Referenced by ioctl().
void BMA180::stop () private
Stop automatic measurement.
Definition at line 657 of file bma180.cpp.
References _call, and hrt_cancel().
Referenced by ioctl(), start(), and ~BMA180().
void BMA180::write_reg (unsigned reg, uint8_t value) private
Write a register in the BMA180.
Parameters
reg The register to write.
value The new value to write.
Definition at line 520 of file bma180.cpp.
References DIR_WRITE.
Referenced by init(), and modify_reg().
Member Data Documentation
float BMA180::_accel_range_m_s2 private
Definition at line 152 of file bma180.cpp.
Referenced by set_range().
float BMA180::_accel_range_scale private
Definition at line 151 of file bma180.cpp.
Referenced by measure(), and set_range().
struct accel_calibration_s BMA180::_accel_scale private
Definition at line 150 of file bma180.cpp.
Referenced by BMA180(), ioctl(), and measure().
orb_advert_t BMA180::_accel_topic private
Definition at line 153 of file bma180.cpp.
Referenced by init(), and measure().
struct hrt_call BMA180::_call private
Definition at line 145 of file bma180.cpp.
Referenced by ioctl(), start(), and stop().
unsigned BMA180::_call_interval private
Definition at line 146 of file bma180.cpp.
Referenced by ioctl(), read(), and start().
int BMA180::_class_instance private
Definition at line 154 of file bma180.cpp.
Referenced by init().
unsigned BMA180::_current_lowpass private
Definition at line 156 of file bma180.cpp.
unsigned BMA180::_current_range private
Definition at line 157 of file bma180.cpp.
Referenced by ioctl(), and set_range().
ringbuffer::RingBuffer* BMA180::_reports private
Definition at line 148 of file bma180.cpp.
Referenced by init(), ioctl(), measure(), print_info(), read(), start(), and ~BMA180().
perf_counter_t BMA180::_sample_perf private
Definition at line 159 of file bma180.cpp.
Referenced by measure(), print_info(), and ~BMA180().
The documentation for this class was generated from the following file:
src/drivers/imu/bma180/bma180.cpp