PX4 Firmware: src/systemcmds/dumpfile/dumpfile.c File Reference
dumpfile.c File Reference
#include <px4_platform_common/px4_config.h>
#include <px4_platform_common/log.h>
#include <px4_platform_common/module.h>
#include <unistd.h>
#include <stdio.h>
#include <string.h>
#include <stdlib.h>
#include <fcntl.h>
#include <termios.h>
#include <systemlib/err.h>
Functions
__EXPORT int dumpfile_main (int argc, char *argv[])
static void print_usage (void)
Detailed Description
Author
Anton Babushkin anton.nosp@m..bab.nosp@m.ushki.nosp@m.n@me.nosp@m..com
Definition in file dumpfile.c.
Function Documentation
dumpfile_main()
int dumpfile_main (int argc, char * argv[])
Definition at line 64 of file dumpfile.c.
References f(), print_usage(), and write().
print_usage()
static void print_usage (void) static
Definition at line 54 of file dumpfile.c.
Referenced by dumpfile_main().