PX4 Firmware: src/drivers/barometer/mpl3115a2/mpl3115a2.cpp File Reference
mpl3115a2.cpp File Reference
FIXME!: This is stubberd out driver for the NXP MPL3115A2 it has bogus code in it and is just being used to verify the i2C buss and WHOAMI.
#include <px4_config.h>
#include <px4_log.h>
#include <sys/types.h>
#include <stdint.h>
#include <stdbool.h>
#include <stdlib.h>
#include <semaphore.h>
#include <string.h>
#include <fcntl.h>
#include <poll.h>
#include <errno.h>
#include <stdio.h>
#include <math.h>
#include <unistd.h>
#include <getopt.h>
#include <nuttx/arch.h>
#include <nuttx/wqueue.h>
#include <nuttx/clock.h>
#include <arch/board/board.h>
#include <board_config.h>
#include <drivers/device/device.h>
#include <drivers/drv_baro.h>
#include <drivers/drv_hrt.h>
#include <drivers/device/ringbuffer.h>
#include <perf/perf_counter.h>
#include <systemlib/err.h>
#include <platforms/px4_getopt.h>
#include "mpl3115a2.h"
Classes
class MPL3115A2
struct mpl3115a2::mpl3115a2_bus_option
Namespaces
mpl3115a2
Local functions in support of the shell command.
Macros
#define INCREMENT(_x, _lim) do { __typeof__(_x) _tmp = _x+1; if (_tmp >= _lim) _tmp = 0; _x = _tmp; } while(0)
#define POW2(_x) ((_x) * (_x))
#define MPL3115A2_CONVERSION_INTERVAL 10000 /* microseconds */
#define MPL3115A2_OSR 0 /* Over Sample rate of 1 6MS Minimum time between data samples */
#define MPL3115A2_CTRL_TRIGGER (CTRL_REG1_OST | CTRL_REG1_OS(MPL3115A2_OSR))
#define MPL3115A2_BARO_DEVICE_PATH_EXT "/dev/mpl3115a2_ext"
#define MPL3115A2_BARO_DEVICE_PATH_INT "/dev/mpl3115a2_int"
#define NUM_BUS_OPTIONS (sizeof(bus_options)/sizeof(bus_options[0]))
Enumerations
enum MPL3115A2_BUS { MPL3115A2_BUS_ALL = 0, MPL3115A2_BUS_I2C_INTERNAL, MPL3115A2_BUS_I2C_EXTERNAL }
Functions
__EXPORT int mpl3115a2_main (int argc, char *argv[])
bool mpl3115a2::start_bus (struct mpl3115a2_bus_option &bus)
Start the driver.
struct mpl3115a2_bus_option & mpl3115a2::find_bus (enum MPL3115A2_BUS busid)
find a bus structure for a busid
void mpl3115a2::start (enum MPL3115A2_BUS busid)
Start the driver.
void mpl3115a2::test (enum MPL3115A2_BUS busid)
Perform some basic functional tests on the driver; make sure we can collect data from the sensor in polled and automatic modes.
void mpl3115a2::reset (enum MPL3115A2_BUS busid)
Reset the driver.
void mpl3115a2::info ()
Print a little info about the driver.
void mpl3115a2::usage ()
Prints info about the driver argument usage.
Variables
struct mpl3115a2::mpl3115a2_bus_option mpl3115a2::bus_options []
Detailed Description
FIXME!: This is stubberd out driver for the NXP MPL3115A2 it has bogus code in it and is just being used to verify the i2C buss and WHOAMI.
Driver for the MPL3115A2 barometric pressure sensor connected via I2C.
Definition in file mpl3115a2.cpp.
Macro Definition Documentation
#define INCREMENT (_x, _lim) do { __typeof__(_x) _tmp = _x+1; if (_tmp >= _lim) _tmp = 0; _x = _tmp; } while(0)
Definition at line 92 of file mpl3115a2.cpp.
#define MPL3115A2_BARO_DEVICE_PATH_EXT "/dev/mpl3115a2_ext"
Definition at line 104 of file mpl3115a2.cpp.
#define MPL3115A2_BARO_DEVICE_PATH_INT "/dev/mpl3115a2_int"
Definition at line 105 of file mpl3115a2.cpp.
#define MPL3115A2_CONVERSION_INTERVAL 10000 /* microseconds */
Definition at line 101 of file mpl3115a2.cpp.
Referenced by MPL3115A2::cycle(), and MPL3115A2::ioctl().
#define MPL3115A2_CTRL_TRIGGER (CTRL_REG1_OST | CTRL_REG1_OS(MPL3115A2_OSR))
Definition at line 103 of file mpl3115a2.cpp.
Referenced by MPL3115A2::measure().
#define MPL3115A2_OSR 0 /* Over Sample rate of 1 6MS Minimum time between data samples */
Definition at line 102 of file mpl3115a2.cpp.
#define NUM_BUS_OPTIONS (sizeof(bus_options)/sizeof(bus_options[0]))
Definition at line 724 of file mpl3115a2.cpp.
Referenced by mpl3115a2::find_bus(), mpl3115a2::info(), and mpl3115a2::start().
#define POW2 (_x) ((_x) * (_x))
Definition at line 95 of file mpl3115a2.cpp.
Enumeration Type Documentation
enum MPL3115A2_BUS
Enumerator
MPL3115A2_BUS_ALL
MPL3115A2_BUS_I2C_INTERNAL
MPL3115A2_BUS_I2C_EXTERNAL
Definition at line 81 of file mpl3115a2.cpp.
Function Documentation
int mpl3115a2_main (int argc, char * argv[])
Definition at line 951 of file mpl3115a2.cpp.
References mpl3115a2::info(), MPL3115A2_BUS_ALL, MPL3115A2_BUS_I2C_EXTERNAL, MPL3115A2_BUS_I2C_INTERNAL, px4_getopt(), mpl3115a2::reset(), mpl3115a2::start(), mpl3115a2::test(), and mpl3115a2::usage().