PX4 Firmware: LPS25H_I2C Class Reference
LPS25H_I2C Class Reference
Public Member Functions
LPS25H_I2C (int bus)
virtual ~LPS25H_I2C ()=default
virtual int read (unsigned address, void *data, unsigned count)
virtual int write (unsigned address, void *data, unsigned count)
virtual int ioctl (unsigned operation, unsigned &arg)
Protected Member Functions
virtual int probe ()
Detailed Description
Definition at line 66 of file lps25h_i2c.cpp.
Constructor & Destructor Documentation
LPS25H_I2C::LPS25H_I2C (int bus)
Definition at line 88 of file lps25h_i2c.cpp.
Referenced by LPS25H_I2C_interface().
virtual LPS25H_I2C::~LPS25H_I2C () virtual default
Member Function Documentation
int LPS25H_I2C::ioctl (unsigned operation, unsigned & arg) virtual
Definition at line 94 of file lps25h_i2c.cpp.
int LPS25H_I2C::probe () protected virtual
Definition at line 111 of file lps25h_i2c.cpp.
References ADDR_WHO_AM_I, DEVICE_DEBUG, ID_WHO_AM_I, OK, and read().
int LPS25H_I2C::read (unsigned address, void * data, unsigned count) virtual
Definition at line 148 of file lps25h_i2c.cpp.
Referenced by probe().
int LPS25H_I2C::write (unsigned address, void * data, unsigned count) virtual
Definition at line 133 of file lps25h_i2c.cpp.
The documentation for this class was generated from the following file:
src/drivers/barometer/lps25h/lps25h_i2c.cpp