PX4 Firmware: PCA8574 Class Reference
PCA8574 Class Reference
Public Member Functions
PCA8574 (int bus, int pca8574)
virtual ~PCA8574 ()=default
virtual int probe ()
virtual int info ()
virtual int ioctl (struct file *filp, int cmd, unsigned long arg)
bool is_running ()
Private Member Functions
void led ()
Main loop function.
int send_led_enable (uint8_t arg)
Sent ENABLE flag to LED driver.
int send_led_values ()
Send 8 outputs.
int get (uint8_t &vals)
Static Private Member Functions
static void led_trampoline (void *arg)
Private Attributes
work_s _work
uint8_t _values_out
uint8_t _values_in
uint8_t _blinking
uint8_t _blink_phase
enum IOX_MODE _mode
bool _running
int _led_interval
bool _should_run
bool _update_out
int _counter
Detailed Description
Definition at line 73 of file pca8574.cpp.
Constructor & Destructor Documentation
PCA8574::PCA8574 (int bus, int pca8574)
Definition at line 118 of file pca8574.cpp.
Referenced by pca8574_main().
virtual PCA8574::~PCA8574 () virtual default
Member Function Documentation
int PCA8574::get (uint8_t & vals) private
Definition at line 344 of file pca8574.cpp.
References _values_in, and OK.
int PCA8574::info () virtual
Definition at line 142 of file pca8574.cpp.
References OK.
int PCA8574::ioctl (struct file * filp, int cmd, unsigned long arg) virtual
Definition at line 150 of file pca8574.cpp.
References _mode, _values_out, IOX_GET_MASK, IOX_MODE_OFF, IOX_MODE_ON, IOX_MODE_TEST_OUT, IOX_SET_MASK, IOX_SET_MODE, IOX_SET_VALUE, OK, position, send_led_enable(), and send_led_values().
Referenced by pca8574_main().
bool PCA8574::is_running () inline
Definition at line 82 of file pca8574.cpp.
References _running.
void PCA8574::led () private
Main loop function.
Definition at line 242 of file pca8574.cpp.
References _blink_phase, _blinking, _counter, _led_interval, _mode, _running, _should_run, _update_out, _values_out, IOX_MODE_OFF, IOX_MODE_TEST_OUT, led_trampoline(), and msg.
Referenced by led_trampoline().
void PCA8574::led_trampoline (void * arg) static private
Definition at line 231 of file pca8574.cpp.
References led().
Referenced by led(), and send_led_values().
int PCA8574::probe () virtual
Definition at line 135 of file pca8574.cpp.
int PCA8574::send_led_enable (uint8_t arg) private
Sent ENABLE flag to LED driver.
Definition at line 318 of file pca8574.cpp.
Referenced by ioctl().
int PCA8574::send_led_values () private
Send 8 outputs.
Definition at line 330 of file pca8574.cpp.
References _running, _update_out, and led_trampoline().
Referenced by ioctl().
Member Data Documentation
uint8_t PCA8574::_blink_phase private
Definition at line 90 of file pca8574.cpp.
Referenced by led().
uint8_t PCA8574::_blinking private
Definition at line 89 of file pca8574.cpp.
Referenced by led().
int PCA8574::_counter private
Definition at line 97 of file pca8574.cpp.
Referenced by led().
int PCA8574::_led_interval private
Definition at line 94 of file pca8574.cpp.
Referenced by led().
enum IOX_MODE PCA8574::_mode private
Definition at line 92 of file pca8574.cpp.
Referenced by ioctl(), and led().
bool PCA8574::_running private
Definition at line 93 of file pca8574.cpp.
Referenced by is_running(), led(), and send_led_values().
bool PCA8574::_should_run private
Definition at line 95 of file pca8574.cpp.
Referenced by led().
bool PCA8574::_update_out private
Definition at line 96 of file pca8574.cpp.
Referenced by led(), and send_led_values().
uint8_t PCA8574::_values_in private
Definition at line 88 of file pca8574.cpp.
Referenced by get().
uint8_t PCA8574::_values_out private
Definition at line 87 of file pca8574.cpp.
Referenced by ioctl(), and led().
work_s PCA8574::_work private
Definition at line 85 of file pca8574.cpp.
The documentation for this class was generated from the following file:
src/drivers/pca8574/pca8574.cpp