PX4 Firmware: src/modules/mc_pos_control/PositionControl/ControlMathTest.cpp File Reference
ControlMathTest.cpp File Reference
#include <gtest/gtest.h>
#include <ControlMath.hpp>
#include <px4_platform_common/defines.h>
Functions
TEST (ControlMathTest, ThrottleAttitudeMapping)
TEST (ControlMathTest, ConstrainXYPriorities)
TEST (ControlMathTest, CrossSphereLine)
Function Documentation
TEST() [1/3]
TEST (ControlMathTest , ThrottleAttitudeMapping)
Definition at line 42 of file ControlMathTest.cpp.
References f(), M_PI_F, and ControlMath::thrustToAttitude().
TEST() [2/3]
TEST (ControlMathTest , ConstrainXYPriorities)
Definition at line 75 of file ControlMathTest.cpp.
References ControlMath::constrainXY(), f(), matrix::max(), and matrix::Matrix< Type, M, N >::zero().
TEST() [3/3]
TEST (ControlMathTest , CrossSphereLine)
Definition at line 108 of file ControlMathTest.cpp.
References ControlMath::cross_sphere_line(), and f().