PX4 Firmware: src/systemcmds/tests/test_dataman.c File Reference
test_dataman.c File Reference
Tests for the data manager.
#include <px4_platform_common/px4_config.h>
#include <px4_platform_common/posix.h>
#include <sys/types.h>
#include <stdio.h>
#include <stdlib.h>
#include <unistd.h>
#include <fcntl.h>
#include <errno.h>
#include <arch/board/board.h>
#include <drivers/drv_board_led.h>
#include <drivers/drv_hrt.h>
#include <semaphore.h>
#include "tests_main.h"
#include "dataman/dataman.h"
Macros
#define NUM_MISSIONS_TEST 50
#define DM_MAX_DATA_SIZE sizeof(struct mission_s)
Functions
int test_dataman (int argc, char *argv[])
static int task_main (int argc, char *argv[])
Variables
static px4_sem_t * sems
static bool * task_returned_error
Detailed Description
Tests for the data manager.
Definition in file test_dataman.c.
Macro Definition Documentation
DM_MAX_DATA_SIZE
#define DM_MAX_DATA_SIZE sizeof(struct mission_s)
Definition at line 66 of file test_dataman.c.
Referenced by task_main(), and test_dataman().
NUM_MISSIONS_TEST
#define NUM_MISSIONS_TEST 50
Definition at line 64 of file test_dataman.c.
Referenced by task_main(), and test_dataman().
Function Documentation
task_main()
static int task_main (int argc, char * argv[]) static
Definition at line 69 of file test_dataman.c.
References DM_KEY_NUM_KEYS, DM_KEY_SAFE_POINTS, DM_KEY_SAFE_POINTS_MAX, DM_KEY_WAYPOINTS_OFFBOARD_1, DM_MAX_DATA_SIZE, DM_PERSIST_IN_FLIGHT_RESET, dm_read(), dm_write(), f(), hrt_absolute_time(), hrt_abstime, NUM_MISSIONS_TEST, sems, and task_returned_error.
Referenced by test_dataman().
test_dataman()
int test_dataman (int argc, char * argv[])
Definition at line 159 of file test_dataman.c.
References DM_INIT_REASON_IN_FLIGHT, DM_INIT_REASON_POWER_ON, DM_KEY_WAYPOINTS_OFFBOARD_1, DM_MAX_DATA_SIZE, dm_read(), dm_restart(), NUM_MISSIONS_TEST, sems, task_main(), and task_returned_error.
Variable Documentation
sems
px4_sem_t* sems static
Definition at line 60 of file test_dataman.c.
Referenced by task_main(), and test_dataman().
task_returned_error
bool* task_returned_error static
Definition at line 61 of file test_dataman.c.
Referenced by task_main(), and test_dataman().