PX4 Firmware: src/lib/flight_tasks/tasks/Utility/ManualVelocitySmoothingXYTest.cpp File Reference
ManualVelocitySmoothingXYTest.cpp File Reference
#include <gtest/gtest.h>
#include <matrix/matrix/math.hpp>
#include "ManualVelocitySmoothingXY.hpp"
Classes
class ManualVelocitySmoothingXYTest
Functions
TEST_F (ManualVelocitySmoothingXYTest, setGet)
TEST_F (ManualVelocitySmoothingXYTest, getCurrentState)
Function Documentation
TEST_F() [1/2]
TEST_F (ManualVelocitySmoothingXYTest , setGet)
Definition at line 53 of file ManualVelocitySmoothingXYTest.cpp.
References f().
TEST_F() [2/2]
TEST_F (ManualVelocitySmoothingXYTest , getCurrentState)
Definition at line 66 of file ManualVelocitySmoothingXYTest.cpp.
References f(), and matrix::Vector3< Type >::xy().