PX4 Firmware: uORB::PublicationBase Class Reference
uORB::PublicationBase Class Reference
Base publication wrapper class, used in list traversal of various publications.
#include <Publication.hpp>
Public Member Functions
PublicationBase (const struct orb_metadata *meta, int priority=-1)
Constructor.
virtual ~PublicationBase ()
PublicationBase (const PublicationBase &)=delete
PublicationBase & operator= (const PublicationBase &)=delete
PublicationBase (PublicationBase &&)=delete
PublicationBase & operator= (PublicationBase &&)=delete
bool update (void *data)
Update the struct.
Protected Attributes
const struct orb_metadata * _meta
const int _priority
orb_advert_t _handle {nullptr}
Detailed Description
Base publication wrapper class, used in list traversal of various publications.
Definition at line 52 of file Publication.hpp.
Constructor & Destructor Documentation
uORB::PublicationBase::PublicationBase (const struct orb_metadata * meta, int priority = -1)
Constructor.
Parameters
meta The uORB metadata (usually from the ORB_ID() macro) for the topic.
priority The priority for multi pub/sub, 0-based, -1 means don't publish as multi
Definition at line 45 of file Publication.cpp.
uORB::PublicationBase::~PublicationBase () virtual
Definition at line 51 of file Publication.cpp.
References _handle, and orb_unadvertise().
uORB::PublicationBase::PublicationBase (const PublicationBase &) delete
uORB::PublicationBase::PublicationBase (PublicationBase &&) delete
Member Function Documentation
PublicationBase& uORB::PublicationBase::operator= (const PublicationBase &) delete
PublicationBase& uORB::PublicationBase::operator= (PublicationBase &&) delete
bool uORB::PublicationBase::update (void * data)
Update the struct.
Parameters
data The uORB message struct we are updating.
Definition at line 56 of file Publication.cpp.
References _handle, _meta, _priority, instance, orb_metadata::o_name, orb_advert_t, orb_advertise(), orb_advertise_multi(), orb_publish(), PX4_ERR, and PX4_OK.
Referenced by uORB::Publication< vehicle_global_position_s >::update().
Member Data Documentation
orb_advert_t uORB::PublicationBase::_handle {nullptr} protected
Definition at line 84 of file Publication.hpp.
Referenced by update(), and ~PublicationBase().
const struct orb_metadata* uORB::PublicationBase::_meta protected
Definition at line 81 of file Publication.hpp.
Referenced by update().
const int uORB::PublicationBase::_priority protected
Definition at line 82 of file Publication.hpp.
Referenced by update().
The documentation for this class was generated from the following files:
src/modules/uORB/Publication.hpp
src/modules/uORB/Publication.cpp