PX4 Firmware: src/drivers/imu/bmi088/bmi088_main.cpp File Reference
bmi088_main.cpp File Reference
#include "BMI088_accel.hpp"
#include "BMI088_gyro.hpp"
Namespaces
bmi088
Enumerations
enum sensor_type {
BMI055_NONE = 0, BMI055_ACCEL = 1, BMI055_GYRO, BMI088_NONE = 0,
BMI088_ACCEL = 1, BMI088_GYRO
}
Functions
__EXPORT int bmi088_main (int argc, char *argv[])
driver 'main' command
void bmi088::start (bool external_bus, enum Rotation rotation, enum sensor_type sensor)
Start the driver.
void bmi088::stop (bool, enum sensor_type)
void bmi088::info (bool external_bus, enum sensor_type sensor)
Print a little info about the driver.
void bmi088::regdump (bool external_bus, enum sensor_type sensor)
Dump the register information.
void bmi088::testerror (bool external_bus, enum sensor_type sensor)
deliberately produce an error to test recovery
void bmi088::usage ()
Prints info about the driver argument usage.
Variables
BMI088_accel * bmi088::g_acc_dev_int
BMI088_accel * bmi088::g_acc_dev_ext
BMI088_gyro * bmi088::g_gyr_dev_int
BMI088_gyro * bmi088::g_gyr_dev_ext
Enumeration Type Documentation
sensor_type
enum sensor_type
Enumerator
BMI055_NONE
BMI055_ACCEL
BMI055_GYRO
BMI088_NONE
BMI088_ACCEL
BMI088_GYRO
Definition at line 40 of file bmi088_main.cpp.
Function Documentation
bmi088_main()
int bmi088_main (int argc, char * argv[])
driver 'main' command
Definition at line 338 of file bmi088_main.cpp.
References BMI088_ACCEL, BMI088_GYRO, BMI088_NONE, bmi088::info(), bmi088::regdump(), ROTATION_NONE, bmi088::start(), bmi088::stop(), bmi088::testerror(), and bmi088::usage().