PX4 Firmware: DfMS5611Wrapper Class Reference
DfMS5611Wrapper Class Reference
Public Member Functions
DfMS5611Wrapper ()
~DfMS5611Wrapper ()
int start ()
Start automatic measurement.
int stop ()
Stop automatic measurement.
Public Member Functions inherited from MS5611
MS5611 (device::Device *interface, ms5611::prom_u &prom_buf, const char *path, enum MS56XX_DEVICE_TYPES device_type)
~MS5611 ()
virtual int init ()
virtual ssize_t read (cdev::file_t *filp, char *buffer, size_t buflen)
Perform a read from the device.
virtual int ioctl (cdev::file_t *filp, int cmd, unsigned long arg)
Perform an ioctl operation on the device.
void print_info ()
Diagnostics - print some basic information about the driver.
Public Member Functions inherited from cdev::CDev
CDev (const char *devname)
Constructor.
CDev (const CDev &)=delete
CDev & operator= (const CDev &)=delete
CDev (CDev &&)=delete
CDev & operator= (CDev &&)=delete
virtual ~CDev ()
virtual int open (file_t *filep)
Handle an open of the device.
virtual int close (file_t *filep)
Handle a close of the device.
virtual ssize_t write (file_t *filep, const char *buffer, size_t buflen)
Perform a write to the device.
virtual off_t seek (file_t *filep, off_t offset, int whence)
Perform a logical seek operation on the device.
virtual int poll (file_t *filep, px4_pollfd_struct_t *fds, bool setup)
Perform a poll setup/teardown operation.
const char * get_devname () const
Get the device name.
Private Member Functions
int _publish (struct baro_sensor_data &data)
Private Attributes
orb_advert_t _baro_topic
int _baro_orb_class_instance
perf_counter_t _baro_sample_perf
Additional Inherited Members
Protected Member Functions inherited from MS5611
void start ()
Initialize the automatic measurement state machine and start it.
void stop ()
Stop the automatic measurement state machine.
void Run () override
Perform a poll cycle; collect from the previous measurement and start a new one.
virtual int measure ()
Issue a measurement command for the current state.
virtual int collect ()
Collect the result of the most recent measurement.
Protected Member Functions inherited from cdev::CDev
virtual pollevent_t poll_state (file_t *filep)
Check the current state of the device for poll events from the perspective of the file.
virtual void poll_notify (pollevent_t events)
Report new poll events.
virtual void poll_notify_one (px4_pollfd_struct_t *fds, pollevent_t events)
Internal implementation of poll_notify.
virtual int open_first (file_t *filep)
Notification of the first open.
virtual int close_last (file_t *filep)
Notification of the last close.
virtual int register_class_devname (const char *class_devname)
Register a class device name, automatically adding device class instance suffix if need be.
virtual int unregister_class_devname (const char *class_devname, unsigned class_instance)
Register a class device name, automatically adding device class instance suffix if need be.
void lock ()
Take the driver lock.
void unlock ()
Release the driver lock.
int unregister_driver_and_memory ()
First, unregisters the driver.
Protected Attributes inherited from MS5611
device::Device * _interface
ms5611::prom_s _prom
unsigned _measure_interval {0}
ringbuffer::RingBuffer * _reports
enum MS56XX_DEVICE_TYPES _device_type
bool _collect_phase
unsigned _measure_phase
int32_t _TEMP
int64_t _OFF
int64_t _SENS
float _P
float _T
orb_advert_t _baro_topic
int _orb_class_instance
int _class_instance
perf_counter_t _sample_perf
perf_counter_t _measure_perf
perf_counter_t _comms_errors
Protected Attributes inherited from cdev::CDev
px4_sem_t _lock
lock to protect access to all class members (also for derived classes)
Static Protected Attributes inherited from cdev::CDev
static const px4_file_operations_t fops = {}
Pointer to the default cdev file operations table; useful for registering clone devices etc.
Detailed Description
Definition at line 69 of file df_ms5611_wrapper.cpp.
Constructor & Destructor Documentation
DfMS5611Wrapper()
DfMS5611Wrapper::DfMS5611Wrapper ()
Definition at line 101 of file df_ms5611_wrapper.cpp.
Referenced by df_ms5611_wrapper::start().
~DfMS5611Wrapper()
DfMS5611Wrapper::~DfMS5611Wrapper ()
Definition at line 109 of file df_ms5611_wrapper.cpp.
References _baro_sample_perf, and perf_free().
Member Function Documentation
_publish()
int DfMS5611Wrapper::_publish (struct baro_sensor_data & data) private
Definition at line 147 of file df_ms5611_wrapper.cpp.
References _baro_orb_class_instance, _baro_sample_perf, _baro_topic, hrt_absolute_time(), orb_advertise_multi(), ORB_ID, ORB_PRIO_DEFAULT, orb_publish(), perf_begin(), perf_end(), and sensor_baro_s::timestamp.
start()
int DfMS5611Wrapper::start ()
Start automatic measurement.
Returns
0 on success
Definition at line 114 of file df_ms5611_wrapper.cpp.
References MS5611::init(), and MS5611::start().
Referenced by df_ms5611_wrapper::start().
stop()
int DfMS5611Wrapper::stop ()
Stop automatic measurement.
Returns
0 on success
Definition at line 134 of file df_ms5611_wrapper.cpp.
References MS5611::stop().
Referenced by df_ms5611_wrapper::stop().
Member Data Documentation
_baro_orb_class_instance
int DfMS5611Wrapper::_baro_orb_class_instance private
Definition at line 95 of file df_ms5611_wrapper.cpp.
Referenced by _publish().
_baro_sample_perf
perf_counter_t DfMS5611Wrapper::_baro_sample_perf private
Definition at line 97 of file df_ms5611_wrapper.cpp.
Referenced by _publish(), and ~DfMS5611Wrapper().
_baro_topic
orb_advert_t DfMS5611Wrapper::_baro_topic private
Definition at line 93 of file df_ms5611_wrapper.cpp.
Referenced by _publish().
The documentation for this class was generated from the following file:
src/drivers/driver_framework_wrapper/df_ms5611_wrapper/df_ms5611_wrapper.cpp