PX4 Firmware: src/systemcmds/topic_listener/topic_listener.hpp File Reference
topic_listener.hpp File Reference
#include <px4_platform_common/defines.h>
#include <drivers/drv_hrt.h>
#include <px4_platform_common/app.h>
#include <px4_platform_common/px4_config.h>
#include <px4_platform_common/log.h>
#include <uORB/uORB.h>
#include <string.h>
#include <stdint.h>
#include <stdio.h>
#include <stdlib.h>
#include <inttypes.h>
Typedefs
typedef int(* listener_print_topic_cb) (const orb_id_t &orb_id, int subscription)
Functions
template<typename T >
int listener_print_topic (const orb_id_t &orb_id, int subscription)
void listener (listener_print_topic_cb cb, const orb_id_t &id, unsigned num_msgs, int topic_instance, unsigned topic_interval)
Typedef Documentation
listener_print_topic_cb
typedef int(* listener_print_topic_cb) (const orb_id_t &orb_id, int subscription)
Definition at line 53 of file topic_listener.hpp.
Function Documentation
listener()
void listener (listener_print_topic_cb cb, const orb_id_t & id, unsigned num_msgs, int topic_instance, unsigned topic_interval)
Definition at line 55 of file listener_main.cpp.
References MESSAGE_TIMEOUT_S, orb_metadata::o_name, orb_exists(), ORB_MULTI_MAX_INSTANCES, orb_set_interval(), orb_subscribe(), orb_subscribe_multi(), orb_unsubscribe(), and read().
Referenced by listener_print_topic().
listener_print_topic()
template<typename T > int listener_print_topic (const orb_id_t & orb_id, int subscription)
Definition at line 56 of file topic_listener.hpp.
References listener(), and orb_copy().