PX4 Firmware: src/drivers/boards/tap-v1/pwr.c File Reference
pwr.c File Reference
#include <px4_config.h>
#include <stdint.h>
#include <stdbool.h>
#include <time.h>
#include <debug.h>
#include <arch/board/board.h>
#include <nuttx/arch.h>
#include "up_arch.h"
#include "board_config.h"
#include <stm32_pwr.h>
Functions
void led_on (int led)
void led_off (int led)
static int default_power_button_state_notification (board_power_button_state_notification_e request)
int board_register_power_state_notification_cb (power_button_state_notification_t cb)
int board_shutdown ()
static int board_button_irq (int irq, FAR void *context, FAR void *args)
void board_pwr_init (int stage)
bool board_pwr_button_down (void)
Variables
static struct timespec time_down
static power_button_state_notification_t power_state_notification = default_power_button_state_notification
Function Documentation
static int board_button_irq (int irq, FAR void * context, FAR void * args) static
Definition at line 108 of file pwr.c.
References board_pwr_button_down(), board_shutdown(), clock_gettime(), led_off(), led_on(), MS_PWR_BUTTON_DOWN, OK, power_state_notification, PWR_BUTTON_DOWN, PWR_BUTTON_IDEL, PWR_BUTTON_REQUEST_SHUT_DOWN, PWR_BUTTON_RESPONSE_SHUT_DOWN_NOW, PWR_BUTTON_UP, and time_down.
Referenced by board_pwr_init().
bool board_pwr_button_down (void)
Definition at line 182 of file pwr.c.
References KEY_AD_GPIO.
Referenced by board_button_irq(), and board_register_power_state_notification_cb().
void board_pwr_init (int stage)
Definition at line 162 of file pwr.c.
References board_button_irq(), KEY_AD_GPIO, and POWER_ON_GPIO.
Referenced by board_app_initialize(), and stm32_boardinitialize().
int board_register_power_state_notification_cb (power_button_state_notification_t cb)
Definition at line 82 of file pwr.c.
References board_pwr_button_down(), OK, power_state_notification, PWR_BUTTON_DOWN, and time_down.
Referenced by Commander::run().
int board_shutdown (void)
Definition at line 94 of file pwr.c.
Referenced by board_button_irq(), px4_shutdown_unlock(), and shutdown_worker().
static int default_power_button_state_notification (board_power_button_state_notification_e request) static
Definition at line 73 of file pwr.c.
References PWR_BUTTON_RESPONSE_SHUT_DOWN_NOW.
void led_off (int led)
Definition at line 97 of file led.c.
Referenced by board_button_irq().
void led_on (int led)
Definition at line 92 of file led.c.
Referenced by board_button_irq().
Variable Documentation
power_button_state_notification_t power_state_notification = default_power_button_state_notification static
Definition at line 80 of file pwr.c.
Referenced by board_button_irq(), and board_register_power_state_notification_cb().
struct timespec time_down static
Definition at line 62 of file pwr.c.
Referenced by board_button_irq(), and board_register_power_state_notification_cb().