PX4 Firmware: src/platforms/px4_param.h File Reference
px4_param.h File Reference
C++ Parameter class.
#include "px4_param_macros.h"
#include <parameters/px4_parameters_public.h>
Classes
class do_not_explicitly_use_this_namespace::Param< T, p >
class do_not_explicitly_use_this_namespace::Param< float, p >
class do_not_explicitly_use_this_namespace::Param< float &, p >
class do_not_explicitly_use_this_namespace::Param< int32_t, p >
class do_not_explicitly_use_this_namespace::Param< int32_t &, p >
class do_not_explicitly_use_this_namespace::Param< bool, p >
class ParamInt< p >
class ParamFloat< p >
Namespaces
do_not_explicitly_use_this_namespace
Macros
#define _DEFINE_SINGLE_PARAMETER(x) do_not_explicitly_use_this_namespace::PAIR(x);
#define _CALL_UPDATE(x) STRIP(x).update();
#define _DEFINE_PARAMETER_UPDATE_METHOD(...)
#define DEFINE_PARAMETERS(...)
#define _DEFINE_PARAMETER_UPDATE_METHOD_CUSTOM_PARENT(parent_class, ...)
#define DEFINE_PARAMETERS_CUSTOM_PARENT(parent_class, ...)
Typedefs
template<px4::params p>
using do_not_explicitly_use_this_namespace::ParamFloat = Param< float, p >
template<px4::params p>
using do_not_explicitly_use_this_namespace::ParamInt = Param< int32_t, p >
template<px4::params p>
using do_not_explicitly_use_this_namespace::ParamExtFloat = Param< float &, p >
template<px4::params p>
using do_not_explicitly_use_this_namespace::ParamExtInt = Param< int32_t &, p >
template<px4::params p>
using do_not_explicitly_use_this_namespace::ParamBool = Param< bool, p >
Functions
static param_t param_handle (px4::params p)
get the parameter handle from a parameter enum
Detailed Description
C++ Parameter class.
Definition in file px4_param.h.
Macro Definition Documentation
#define _CALL_UPDATE (x) STRIP(x).update();
Definition at line 60 of file px4_param.h.
#define _DEFINE_PARAMETER_UPDATE_METHOD (...)
Value:
protected: \
    void updateParamsImpl() final { \
        APPLY_ALL(_CALL_UPDATE, __VA_ARGS__) \
    } \
    private:
Definition at line 65 of file px4_param.h.
#define _DEFINE_PARAMETER_UPDATE_METHOD_CUSTOM_PARENT (parent_class, ...)
Value:
protected: \
    void updateParamsImpl() override { \
        parent_class::updateParamsImpl(); \
        APPLY_ALL(_CALL_UPDATE, __VA_ARGS__) \
    } \
    private:
Definition at line 83 of file px4_param.h.
#define _DEFINE_SINGLE_PARAMETER (x) do_not_explicitly_use_this_namespace::PAIR(x);
Definition at line 57 of file px4_param.h.
#define DEFINE_PARAMETERS (...)
Value:
APPLY_ALL(_DEFINE_SINGLE_PARAMETER, __VA_ARGS__) \
    _DEFINE_PARAMETER_UPDATE_METHOD(__VA_ARGS__)
Definition at line 78 of file px4_param.h.
#define DEFINE_PARAMETERS_CUSTOM_PARENT (parent_class, ...)
Value:
APPLY_ALL(_DEFINE_SINGLE_PARAMETER, __VA_ARGS__) \
    _DEFINE_PARAMETER_UPDATE_METHOD_CUSTOM_PARENT(parent_class, __VA_ARGS__)
Definition at line 91 of file px4_param.h.
Function Documentation
static param_t param_handle (px4::params p) inline static
get the parameter handle from a parameter enum
Definition at line 49 of file px4_param.h.
Referenced by DfMpu9250Wrapper::DfMpu9250Wrapper(), do_not_explicitly_use_this_namespace::Param< float, p >::handle(), do_not_explicitly_use_this_namespace::Param< float &, p >::handle(), do_not_explicitly_use_this_namespace::Param< int32_t, p >::handle(), do_not_explicitly_use_this_namespace::Param< int32_t &, p >::handle(), do_not_explicitly_use_this_namespace::Param< bool, p >::handle(), linux_pwm_out::update_params(), PWMSim::update_params(), snapdragon_pwm::update_params(), UavcanNode::update_params(), and PX4FMU::update_params().