PX4 Firmware: Lock Class Reference
Lock Class Reference
#include <uavcan_virtual_can_driver.hpp>
Public Member Functions
Lock (pthread_mutex_t &m)
~Lock ()
Static Public Member Functions
static int init (pthread_mutex_t &thier_mutex_)
static int deinit (pthread_mutex_t &thier_mutex_)
Private Attributes
pthread_mutex_t & thier_mutex_
Detailed Description
Definition at line 64 of file uavcan_virtual_can_driver.hpp.
Constructor & Destructor Documentation
Lock::Lock (pthread_mutex_t & m) inline
Definition at line 70 of file uavcan_virtual_can_driver.hpp.
References pthread_mutex_lock().
Lock::~Lock () inline
Definition at line 76 of file uavcan_virtual_can_driver.hpp.
References pthread_mutex_unlock().
Member Function Documentation
static int Lock::deinit (pthread_mutex_t & thier_mutex_) inline static
Definition at line 86 of file uavcan_virtual_can_driver.hpp.
References pthread_mutex_destroy().
Referenced by UavcanServers::~UavcanServers(), and VirtualCanDriver::~VirtualCanDriver().
static int Lock::init (pthread_mutex_t & thier_mutex_) inline static
Definition at line 81 of file uavcan_virtual_can_driver.hpp.
References pthread_mutex_init().
Referenced by UavcanServers::init(), and VirtualCanDriver::VirtualCanDriver().
Member Data Documentation
pthread_mutex_t& Lock::thier_mutex_ private
Definition at line 66 of file uavcan_virtual_can_driver.hpp.
The documentation for this class was generated from the following file:
src/modules/uavcan/uavcan_virtual_can_driver.hpp