PX4 Firmware: FlightTaskManualStabilized Class Reference
FlightTaskManualStabilized Class Reference
#include <FlightTaskManualStabilized.hpp>
Public Member Functions
FlightTaskManualStabilized ()=default
virtual ~FlightTaskManualStabilized ()=default
bool activate () override
Call once on the event where you switch to the task.
bool updateInitialize () override
Call before activate() or update() to initialize time and input data.
bool update () override
To be called regularly in the control loop cycle to execute the task.
Public Member Functions inherited from FlightTaskManual
FlightTaskManual ()=default
virtual ~FlightTaskManual ()=default
bool initializeSubscriptions (SubscriptionArray &subscription_array) override
Initialize the uORB subscriptions using an array.
bool applyCommandParameters (const vehicle_command_s &command) override
To be called to adopt parameters from an arrived vehicle command.
Public Member Functions inherited from FlightTask
FlightTask ()
virtual ~FlightTask ()=default
const vehicle_local_position_setpoint_s getPositionSetpoint ()
Get the output data.
const vehicle_constraints_s getConstraints ()
Get vehicle constraints.
const vehicle_trajectory_waypoint_s getAvoidanceWaypoint ()
Get avoidance desired waypoint.
void handleParameterUpdate ()
Call this whenever a parameter update notification is received (parameter_update uORB message)
Public Member Functions inherited from ModuleParams
ModuleParams (ModuleParams *parent)
void setParent (ModuleParams *parent)
Set the parent module.
virtual ~ModuleParams ()=default
ModuleParams (const ModuleParams &)=delete
ModuleParams & operator= (const ModuleParams &)=delete
ModuleParams (ModuleParams &&)=delete
ModuleParams & operator= (ModuleParams &&)=delete
Public Member Functions inherited from ListNode< ModuleParams * >
ListNode ()
ListNode (const ListNode &)=delete
ListNode (ListNode &&)=delete
virtual ~ListNode ()=default
ListNode & operator= (const ListNode &)=delete
ListNode & operator= (ListNode &&)=delete
void setSibling (ModuleParams *sibling)
const ModuleParams * getSibling ()
Protected Member Functions
virtual void _updateSetpoints ()
updates all setpoints
virtual void _scaleSticks ()
scales sticks to yaw and thrust
void _rotateIntoHeadingFrame (matrix::Vector2f &vec)
rotates vector into local frame
Protected Member Functions inherited from FlightTaskManual
float stickDeadzone () const
Protected Member Functions inherited from FlightTask
void _resetSetpoints ()
Reset all setpoints to NAN.
bool _evaluateVehicleLocalPosition ()
virtual void _setDefaultConstraints ()
Set constraints to default values.
Protected Member Functions inherited from ModuleParams
virtual void updateParams ()
Call this whenever the module gets a parameter change notification.
virtual void updateParamsImpl ()
The implementation for this is generated with the macro DEFINE_PARAMETERS()
Private Member Functions
void _updateHeadingSetpoints ()
sets yaw or yaw speed
void _updateThrustSetpoints ()
sets thrust setpoint
float _throttleCurve ()
piecewise linear mapping from stick to throttle
Private Attributes
float _throttle {}
Additional Inherited Members
Static Public Attributes inherited from FlightTask
static const vehicle_local_position_setpoint_s empty_setpoint = {0, NAN, NAN, NAN, NAN, NAN, NAN, NAN, NAN, NAN, NAN, NAN, {NAN, NAN, NAN}}
Empty setpoint.
static const vehicle_constraints_s empty_constraints = {0, NAN, NAN, NAN, NAN, NAN, NAN, NAN, vehicle_constraints_s::GEAR_KEEP, {}}
Empty constraints.
static const vehicle_trajectory_waypoint_s empty_trajectory_waypoint
Empty desired waypoints.
Protected Attributes inherited from FlightTaskManual
bool _sticks_data_required = true
let inherited task-class define if it depends on stick data
matrix::Vector< float, 4 > _sticks
unmodified manual stick inputs
matrix::Vector< float, 4 > _sticks_expo
modified manual sticks using expo function
Protected Attributes inherited from FlightTask
uORB::Subscription< vehicle_local_position_s > * _sub_vehicle_local_position {nullptr}
uORB::Subscription< vehicle_attitude_s > * _sub_attitude {nullptr}
uint8_t _heading_reset_counter {0}
estimator heading reset
float _time = 0
passed time in seconds since the task was activated
float _deltatime = 0
passed time in seconds since the task was last updated
hrt_abstime _time_stamp_activate = 0
time stamp when task was activated
hrt_abstime _time_stamp_current = 0
time stamp at the beginning of the current task update
hrt_abstime _time_stamp_last = 0
time stamp when task was last updated
matrix::Vector3f _position
current vehicle position
matrix::Vector3f _velocity
current vehicle velocity
float _yaw = 0.f
current vehicle yaw heading
float _dist_to_bottom = 0.0f
current height above ground level
matrix::Vector3f _position_setpoint
Setpoints which the position controller has to execute.
matrix::Vector3f _velocity_setpoint
matrix::Vector3f _acceleration_setpoint
matrix::Vector3f _thrust_setpoint
float _yaw_setpoint
float _yawspeed_setpoint
vehicle_constraints_s _constraints
Vehicle constraints.
vehicle_trajectory_waypoint_s _desired_waypoint
Desired waypoints.
Protected Attributes inherited from ListNode< ModuleParams * >
ModuleParams * _sibling
Static Protected Attributes inherited from FlightTask
static constexpr uint64_t _timeout = 500000
maximal time in us before a loop or data times out
Detailed Description
Definition at line 45 of file FlightTaskManualStabilized.hpp.
Constructor & Destructor Documentation
FlightTaskManualStabilized::FlightTaskManualStabilized () default
virtual FlightTaskManualStabilized::~FlightTaskManualStabilized () virtual default
Member Function Documentation
void FlightTaskManualStabilized::_rotateIntoHeadingFrame (matrix::Vector2f & vec) protected
rotates vector into local frame
Definition at line 125 of file FlightTaskManualStabilized.cpp.
References f().
void FlightTaskManualStabilized::_scaleSticks () protected virtual
scales sticks to yaw and thrust
Reimplemented in FlightTaskManualPosition, and FlightTaskManualAltitude.
Definition at line 61 of file FlightTaskManualStabilized.cpp.
References math::radians().
Referenced by FlightTaskManualAltitude::_scaleSticks().
float FlightTaskManualStabilized::_throttleCurve () private
piecewise linear mapping from stick to throttle
Definition at line 139 of file FlightTaskManualStabilized.cpp.
References f().
void FlightTaskManualStabilized::_updateHeadingSetpoints () private
sets yaw or yaw speed
Definition at line 69 of file FlightTaskManualStabilized.cpp.
void FlightTaskManualStabilized::_updateSetpoints () protected virtual
updates all setpoints
Reimplemented in FlightTaskManualPosition, FlightTaskManualPositionSmooth, FlightTaskManualAltitude, and FlightTaskManualAltitudeSmooth.
Definition at line 133 of file FlightTaskManualStabilized.cpp.
Referenced by FlightTaskManualAltitude::_updateSetpoints().
void FlightTaskManualStabilized::_updateThrustSetpoints () private
sets thrust setpoint
Definition at line 93 of file FlightTaskManualStabilized.cpp.
References matrix::Quaternion< Type >::conjugate(), math::constrain(), f(), M_PI_F, and matrix::Vector< Type, M >::norm().
bool FlightTaskManualStabilized::activate () override virtual
Call once on the event where you switch to the task.
Returns
true on success, false on error
Reimplemented from FlightTask.
Reimplemented in FlightTaskSport, and FlightTaskOrbit.
Definition at line 44 of file FlightTaskManualStabilized.cpp.
References FlightTask::activate(), f(), and math::radians().
Referenced by FlightTaskManualAltitude::activate().
bool FlightTaskManualStabilized::update () override virtual
To be called regularly in the control loop cycle to execute the task.
Returns
true on success, false on error
Implements FlightTask.
Reimplemented in FlightTaskOrbit.
Definition at line 153 of file FlightTaskManualStabilized.cpp.
Referenced by FlightTaskOrbit::update().
bool FlightTaskManualStabilized::updateInitialize () override virtual
Call before activate() or update() to initialize time and input data.
Returns
true on success, false on error
Reimplemented from FlightTaskManual.
Definition at line 54 of file FlightTaskManualStabilized.cpp.
References FlightTaskManual::updateInitialize().
Referenced by FlightTaskManualAltitude::updateInitialize().
Member Data Documentation
float FlightTaskManualStabilized::_throttle {} private
Definition at line 65 of file FlightTaskManualStabilized.hpp.
The documentation for this class was generated from the following files:
src/lib/FlightTasks/tasks/ManualStabilized/FlightTaskManualStabilized.hpp
src/lib/FlightTasks/tasks/ManualStabilized/FlightTaskManualStabilized.cpp