PX4 Firmware: Battery Class Reference
Battery Class Reference
#include <battery.h>
Public Member Functions
Battery ()
void reset (battery_status_s *battery_status)
Reset all battery stats and report invalid/nothing.
int cell_count ()
Get the battery cell count.
float empty_cell_voltage ()
Get the empty voltage per cell.
float full_cell_voltage ()
Get the full voltage per cell.
void updateBatteryStatus (hrt_abstime timestamp, float voltage_v, float current_a, bool connected, bool selected_source, int priority, float throttle_normalized, bool armed, battery_status_s *status)
Update current battery status message.
Public Member Functions inherited from ModuleParams
ModuleParams (ModuleParams *parent)
void setParent (ModuleParams *parent)
Set the parent module.
virtual ~ModuleParams ()=default
ModuleParams (const ModuleParams &)=delete
ModuleParams & operator= (const ModuleParams &)=delete
ModuleParams (ModuleParams &&)=delete
ModuleParams & operator= (ModuleParams &&)=delete
Public Member Functions inherited from ListNode< ModuleParams * >
ListNode ()
ListNode (const ListNode &)=delete
ListNode (ListNode &&)=delete
virtual ~ListNode ()=default
ListNode & operator= (const ListNode &)=delete
ListNode & operator= (ListNode &&)=delete
void setSibling (ModuleParams *sibling)
const ModuleParams * getSibling ()
Private Member Functions
void filterVoltage (float voltage_v)
void filterThrottle (float throttle)
void filterCurrent (float current_a)
void sumDischarged (hrt_abstime timestamp, float current_a)
void estimateRemaining (float voltage_v, float current_a, float throttle, bool armed)
void determineWarning (bool connected)
void computeScale ()
DEFINE_PARAMETERS ((ParamFloat< px4::params::BAT_V_EMPTY >) _v_empty,(ParamFloat< px4::params::BAT_V_CHARGED >) _v_charged,(ParamInt< px4::params::BAT_N_CELLS >) _n_cells,(ParamFloat< px4::params::BAT_CAPACITY >) _capacity,(ParamFloat< px4::params::BAT_V_LOAD_DROP >) _v_load_drop,(ParamFloat< px4::params::BAT_R_INTERNAL >) _r_internal,(ParamFloat< px4::params::BAT_LOW_THR >) _low_thr,(ParamFloat< px4::params::BAT_CRIT_THR >) _crit_thr,(ParamFloat< px4::params::BAT_EMERGEN_THR >) _emergency_thr) bool _battery_initialized
Private Attributes
float _voltage_filtered_v = -1.f
float _throttle_filtered = -1.f
float _current_filtered_a = -1.f
float _discharged_mah = 0.f
float _discharged_mah_loop = 0.f
float _remaining_voltage = -1.f
normalized battery charge level remaining based on voltage
float _remaining = -1.f
normalized battery charge level, selected based on config param
float _scale = 1.f
uint8_t _warning
hrt_abstime _last_timestamp
Additional Inherited Members
Protected Member Functions inherited from ModuleParams
virtual void updateParams ()
Call this whenever the module gets a parameter change notification.
virtual void updateParamsImpl ()
The implementation for this is generated with the macro DEFINE_PARAMETERS()
Protected Attributes inherited from ListNode< ModuleParams * >
ModuleParams * _sibling
Detailed Description
Definition at line 49 of file battery.h.
Constructor & Destructor Documentation
Battery::Battery ()
Definition at line 46 of file battery.cpp.
Member Function Documentation
int Battery::cell_count () inline
Get the battery cell count.
Definition at line 62 of file battery.h.
void Battery::computeScale () private
Definition at line 223 of file battery.cpp.
References _remaining_voltage, _scale, and f().
Referenced by full_cell_voltage(), and updateBatteryStatus().
Battery::DEFINE_PARAMETERS ((ParamFloat< px4::params::BAT_V_EMPTY >) _v_empty, (ParamFloat< px4::params::BAT_V_CHARGED >) _v_charged, (ParamInt< px4::params::BAT_N_CELLS >) _n_cells, (ParamFloat< px4::params::BAT_CAPACITY >) _capacity, (ParamFloat< px4::params::BAT_V_LOAD_DROP >) _v_load_drop, (ParamFloat< px4::params::BAT_R_INTERNAL >) _r_internal, (ParamFloat< px4::params::BAT_LOW_THR >) _low_thr, (ParamFloat< px4::params::BAT_CRIT_THR >) _crit_thr, (ParamFloat< px4::params::BAT_EMERGEN_THR >) _emergency_thr) private
Referenced by full_cell_voltage().
void Battery::determineWarning (bool connected) private
Definition at line 206 of file battery.cpp.
References _remaining, and _warning.
Referenced by full_cell_voltage(), and updateBatteryStatus().
float Battery::empty_cell_voltage () inline
Get the empty voltage per cell.
Definition at line 67 of file battery.h.
void Battery::estimateRemaining (float voltage_v, float current_a, float throttle, bool armed) private
Definition at line 167 of file battery.cpp.
References _discharged_mah_loop, _remaining, _remaining_voltage, f(), math::gradual(), and math::max().
Referenced by full_cell_voltage(), and updateBatteryStatus().
void Battery::filterCurrent (float current_a) private
Definition at line 117 of file battery.cpp.
References _current_filtered_a.
Referenced by full_cell_voltage(), and updateBatteryStatus().
void Battery::filterThrottle (float throttle) private
Definition at line 131 of file battery.cpp.
References _throttle_filtered.
Referenced by full_cell_voltage(), and updateBatteryStatus().
void Battery::filterVoltage (float voltage_v) private
Definition at line 102 of file battery.cpp.
References _voltage_filtered_v.
Referenced by full_cell_voltage(), and updateBatteryStatus().
float Battery::full_cell_voltage () inline
Get the full voltage per cell.
Definition at line 72 of file battery.h.
References armed, computeScale(), DEFINE_PARAMETERS(), determineWarning(), estimateRemaining(), filterCurrent(), filterThrottle(), filterVoltage(), hrt_abstime, status, sumDischarged(), and updateBatteryStatus().
void Battery::reset (battery_status_s * battery_status)
Reset all battery stats and report invalid/nothing.
Definition at line 54 of file battery.cpp.
References battery_status_s::cell_count, battery_status_s::connected, battery_status_s::current_a, battery_status_s::remaining, battery_status_s::scale, and battery_status_s::warning.
Referenced by DfLtc2946Wrapper::DfLtc2946Wrapper(), Syslink::task_main(), and updateBatteryStatus().
void Battery::sumDischarged (hrt_abstime timestamp, float current_a) private
Definition at line 145 of file battery.cpp.
References _discharged_mah, _discharged_mah_loop, _last_timestamp, dt, and f().
Referenced by full_cell_voltage(), and updateBatteryStatus().
void Battery::updateBatteryStatus (hrt_abstime timestamp, float voltage_v, float current_a, bool connected, bool selected_source, int priority, float throttle_normalized, bool armed, battery_status_s * status)
Update current battery status message.
Parameters
voltage_v current voltage in V
current_a current current in A
connected Battery is connected
selected_source This battery is on the brick that the selected source for selected_source
priority The brick number -1. The term priority refers to the Vn connection on the LTC4417
throttle_normalized throttle from 0 to 1
Definition at line 67 of file battery.cpp.
References _current_filtered_a, _discharged_mah, _remaining, _scale, _throttle_filtered, _voltage_filtered_v, _warning, computeScale(), battery_status_s::connected, battery_status_s::current_a, battery_status_s::current_filtered_a, determineWarning(), battery_status_s::discharged_mah, estimateRemaining(), f(), filterCurrent(), filterThrottle(), filterVoltage(), battery_status_s::priority, battery_status_s::remaining, reset(), battery_status_s::scale, sumDischarged(), battery_status_s::system_source, battery_status_s::timestamp, battery_status_s::voltage_filtered_v, battery_status_s::voltage_v, and battery_status_s::warning.
Referenced by DfLtc2946Wrapper::_publish(), DfBebopBusWrapper::_publish(), full_cell_voltage(), and Syslink::handle_message().
Member Data Documentation
float Battery::_current_filtered_a = -1.f private
Definition at line 113 of file battery.h.
Referenced by filterCurrent(), and updateBatteryStatus().
float Battery::_discharged_mah = 0.f private
Definition at line 114 of file battery.h.
Referenced by sumDischarged(), and updateBatteryStatus().
float Battery::_discharged_mah_loop = 0.f private
Definition at line 115 of file battery.h.
Referenced by estimateRemaining(), and sumDischarged().
hrt_abstime Battery::_last_timestamp private
Definition at line 120 of file battery.h.
Referenced by sumDischarged().
float Battery::_remaining = -1.f private
normalized battery charge level, selected based on config param
Definition at line 117 of file battery.h.
Referenced by determineWarning(), estimateRemaining(), and updateBatteryStatus().
float Battery::_remaining_voltage = -1.f private
normalized battery charge level remaining based on voltage
Definition at line 116 of file battery.h.
Referenced by computeScale(), and estimateRemaining().
float Battery::_scale = 1.f private
Definition at line 118 of file battery.h.
Referenced by computeScale(), and updateBatteryStatus().
float Battery::_throttle_filtered = -1.f private
Definition at line 112 of file battery.h.
Referenced by filterThrottle(), and updateBatteryStatus().
float Battery::_voltage_filtered_v = -1.f private
Definition at line 111 of file battery.h.
Referenced by filterVoltage(), and updateBatteryStatus().
uint8_t Battery::_warning private
Definition at line 119 of file battery.h.
Referenced by determineWarning(), and updateBatteryStatus().
The documentation for this class was generated from the following files:
src/lib/battery/battery.h
src/lib/battery/battery.cpp