PX4 Firmware: src/drivers/qshell/qurt/qshell_start_qurt.cpp File Reference
qshell_start_qurt.cpp File Reference
Listener for shell commands from posix.
#include "qshell.h"
#include <px4_platform_common/log.h>
#include <px4_platform_common/app.h>
#include <px4_platform_common/tasks.h>
#include <stdio.h>
#include <string.h>
#include <sched.h>
Functions
__EXPORT int qshell_main (int argc, char *argv[])
int qshell_entry (int argc, char **argv)
static void usage ()
Variables
static int daemon_task
Detailed Description
Listener for shell commands from posix.
Author
Nicolas de Palezieux ndepa.nosp@m.l@gm.nosp@m.ail.c.nosp@m.om
Definition in file qshell_start_qurt.cpp.
Function Documentation
qshell_entry()
int qshell_entry (int argc, char ** argv)
Definition at line 55 of file qshell_start_qurt.cpp.
References QShell::main().
Referenced by qshell_main().
qshell_main()
__EXPORT int qshell_main (int argc, char * argv[])
Definition at line 71 of file qshell_start_qurt.cpp.
References QShell::appState, daemon_task, qshell_entry(), and usage().
usage()
static void usage (void) static
Definition at line 67 of file qshell_start_qurt.cpp.
Referenced by qshell_main().
Variable Documentation
daemon_task
int daemon_task static
Definition at line 49 of file qshell_start_qurt.cpp.
Referenced by qshell_main().