PX4 Firmware: MS5611 Class Reference
MS5611 Class Reference
Public Member Functions
MS5611 (device::Device *interface, ms5611::prom_u &prom_buf, const char *path, enum MS56XX_DEVICE_TYPES device_type)
~MS5611 ()
virtual int init ()
Initialise the driver and make it ready for use.
virtual ssize_t read (struct file *filp, char *buffer, size_t buflen)
virtual int ioctl (struct file *filp, int cmd, unsigned long arg)
void print_info ()
Diagnostics - print some basic information about the driver.
Public Member Functions inherited from device::CDev
CDev (const char *name, const char *devname)
Constructor.
virtual ~CDev ()
virtual int open (file_t *filep)
Handle an open of the device.
virtual int close (file_t *filep)
Handle a close of the device.
virtual ssize_t read (file_t *filep, char *buffer, size_t buflen)
Perform a read from the device.
virtual ssize_t write (file_t *filep, const char *buffer, size_t buflen)
Perform a write to the device.
virtual off_t seek (file_t *filep, off_t offset, int whence)
Perform a logical seek operation on the device.
virtual int ioctl (file_t *filep, int cmd, unsigned long arg)
Perform an ioctl operation on the device.
virtual int poll (file_t *filep, px4_pollfd_struct_t *fds, bool setup)
Perform a poll setup/teardown operation.
Public Member Functions inherited from device::Device
virtual ~Device ()=default
Destructor.
virtual int read (unsigned address, void *data, unsigned count)
Read directly from the device.
virtual int write (unsigned address, void *data, unsigned count)
Write directly to the device.
virtual int ioctl (unsigned operation, unsigned &arg)
Perform a device-specific operation.
uint8_t get_device_bus ()
Return the bus ID the device is connected to.
DeviceBusType get_device_bus_type ()
Return the bus type the device is connected to.
uint8_t get_device_address ()
Return the bus address of the device.
void set_device_address (int address)
void set_device_type (uint8_t devtype)
Set the device type.
virtual bool external ()
Protected Member Functions
void start_cycle (unsigned delay_ticks=1)
Initialize the automatic measurement state machine and start it.
void stop_cycle ()
Stop the automatic measurement state machine.
void cycle ()
Perform a poll cycle; collect from the previous measurement and start a new one.
virtual int measure ()
Issue a measurement command for the current state.
virtual int collect ()
Collect the result of the most recent measurement.
Protected Member Functions inherited from device::CDev
virtual pollevent_t poll_state (file_t *filep)
Check the current state of the device for poll events from the perspective of the file.
virtual void poll_notify (pollevent_t events)
Report new poll events.
virtual void poll_notify_one (px4_pollfd_struct_t *fds, pollevent_t events)
Internal implementation of poll_notify.
virtual int open_first (file_t *filep)
Notification of the first open.
virtual int close_last (file_t *filep)
Notification of the last close.
virtual int register_class_devname (const char *class_devname)
Register a class device name, automatically adding device class instance suffix if need be.
virtual int unregister_class_devname (const char *class_devname, unsigned class_instance)
Register a class device name, automatically adding device class instance suffix if need be.
const char * get_devname ()
Get the device name.
void lock ()
Take the driver lock.
void unlock ()
Release the driver lock.
Protected Member Functions inherited from device::Device
Device (const char *name)
Device (DeviceBusType bus_type, uint8_t bus, uint8_t address, uint8_t devtype=0)
Device (const Device &)=delete
Device & operator= (const Device &)=delete
Device (Device &&)=delete
Device & operator= (Device &&)=delete
Static Protected Member Functions
static void cycle_trampoline (void *arg)
Static trampoline from the workq context; because we don't have a generic workq wrapper yet.
Protected Attributes
Device * _interface
ms5611::prom_s _prom
struct work_s _work
unsigned _measure_ticks
ringbuffer::RingBuffer * _reports
enum MS56XX_DEVICE_TYPES _device_type
bool _collect_phase
unsigned _measure_phase
int32_t _TEMP
int64_t _OFF
int64_t _SENS
float _P
float _T
orb_advert_t _baro_topic
int _orb_class_instance
int _class_instance
perf_counter_t _sample_perf
perf_counter_t _measure_perf
perf_counter_t _comms_errors
Protected Attributes inherited from device::CDev
px4_sem_t _lock
lock to protect access to all class members (also for derived classes)
bool _pub_blocked {false}
true if publishing should be blocked
Protected Attributes inherited from device::Device
union DeviceId _device_id
device identifier information
const char * _name
driver name
bool _debug_enabled {false}
if true, debug messages are printed
Additional Inherited Members
Public Types inherited from device::Device
enum DeviceBusType { DeviceBusType_UNKNOWN = 0, DeviceBusType_I2C = 1, DeviceBusType_SPI = 2, DeviceBusType_UAVCAN = 3 }
Device bus types for DEVID.
Static Protected Attributes inherited from device::CDev
static const px4_file_operations_t fops = {}
Pointer to the default cdev file operations table; useful for registering clone devices etc.
Detailed Description
Definition at line 129 of file ms5611.cpp.
Constructor & Destructor Documentation
MS5611::MS5611 (device::Device * interface, ms5611::prom_u & prom_buf, const char * path, enum MS56XX_DEVICE_TYPES device_type)
Definition at line 229 of file ms5611.cpp.
References device::Device::_device_id, _interface, device::Device::DeviceStructure::address, device::Device::DeviceStructure::bus, device::Device::DeviceStructure::bus_type, device::Device::DeviceId::devid_s, and device::Device::DeviceStructure::devtype.
Referenced by ms5611::start_bus().
MS5611::~MS5611 ()
Definition at line 261 of file ms5611.cpp.
References _class_instance, _comms_errors, _interface, _measure_perf, _reports, _sample_perf, device::CDev::get_devname(), perf_free(), stop_cycle(), and device::CDev::unregister_class_devname().
Member Function Documentation
int MS5611::collect () protected virtual
Collect the result of the most recent measurement.
Definition at line 707 of file ms5611.cpp.
References _baro_topic, _comms_errors, device::Device::_device_id, _device_type, _interface, _measure_phase, _OFF, _P, _prom, device::CDev::_pub_blocked, _reports, _sample_perf, _SENS, _T, _TEMP, baro_report, ms5611::prom_s::c1_pressure_sens, ms5611::prom_s::c2_pressure_offset, ms5611::prom_s::c3_temp_coeff_pres_sens, ms5611::prom_s::c4_temp_coeff_pres_offset, ms5611::prom_s::c5_reference_temp, ms5611::prom_s::c6_temp_coeff_temp, device::Device::DeviceId::devid, f(), hrt_absolute_time(), INCREMENT, MS5607_DEVICE, MS5611_DEVICE, MS5611_MEASUREMENT_RATIO, OK, ORB_ID, orb_publish(), P, perf_begin(), perf_count(), perf_end(), perf_event_count(), device::CDev::poll_notify(), and POW2.
Referenced by cycle(), init(), and read().
void MS5611::cycle () protected
Perform a poll cycle; collect from the previous measurement and start a new one.
This is the heart of the measurement state machine. This function alternately starts a measurement, or collects the data from the previous measurement.
When the interval between measurements is greater than the minimum measurement interval, a gap is inserted between collection and measurement to provide the most recent measurement possible at the next interval.
Definition at line 604 of file ms5611.cpp.
References _collect_phase, _interface, _measure_phase, _measure_ticks, collect(), cycle_trampoline(), IOCTL_RESET, measure(), MS5611_CONVERSION_INTERVAL, OK, and start_cycle().
Referenced by cycle_trampoline().
void MS5611::cycle_trampoline (void * arg) static protected
Static trampoline from the workq context; because we don't have a generic workq wrapper yet.
Parameters
arg Instance pointer for the driver that is polling.
Definition at line 596 of file ms5611.cpp.
References cycle().
Referenced by cycle(), and start_cycle().
int MS5611::init () virtual
Initialise the driver and make it ready for use.
Returns
OK if the driver initialized OK, negative errno otherwise;
Reimplemented from device::CDev.
Definition at line 284 of file ms5611.cpp.
References _baro_topic, _class_instance, device::Device::_device_id, _device_type, _interface, _measure_phase, _orb_class_instance, _reports, BARO_BASE_DEVICE_PATH, baro_report, collect(), DEVICE_DEBUG, device::Device::DeviceId::devid, device::Device::DeviceId::devid_s, device::Device::DeviceStructure::devtype, DRV_BARO_DEVTYPE_MS5607, DRV_BARO_DEVTYPE_MS5611, lis3mdl::init(), measure(), MS5607_DEVICE, MS5611_CONVERSION_INTERVAL, MS5611_DEVICE, MS56XX_DEVICE, OK, orb_advertise_multi(), ORB_ID, ORB_PRIO_DEFAULT, ORB_PRIO_HIGH, device::CDev::register_class_devname(), usleep(), and warnx.
Referenced by DfMS5611Wrapper::start().
int MS5611::ioctl (struct file * filp, int cmd, unsigned long arg) virtual
Definition at line 473 of file ms5611.cpp.
References _measure_ticks, _reports, MS5611_CONVERSION_INTERVAL, OK, SENSOR_POLLRATE_DEFAULT, SENSOR_POLLRATE_EXTERNAL, SENSOR_POLLRATE_MANUAL, SENSOR_POLLRATE_MAX, SENSORIOCGPOLLRATE, SENSORIOCRESET, SENSORIOCSPOLLRATE, SENSORIOCSQUEUEDEPTH, start_cycle(), and stop_cycle().
Referenced by ms5611::reset(), ms5611::start_bus(), and ms5611::test().
int MS5611::measure () protected virtual
Issue a measurement command for the current state.
Returns
OK if the measurement command was successful.
Definition at line 681 of file ms5611.cpp.
References _comms_errors, _interface, _measure_perf, _measure_phase, ADDR_CMD_CONVERT_D1, ADDR_CMD_CONVERT_D2, IOCTL_MEASURE, OK, perf_begin(), perf_count(), and perf_end().
Referenced by cycle(), init(), and read().
void MS5611::print_info ()
Diagnostics - print some basic information about the driver.
Definition at line 831 of file ms5611.cpp.
References _comms_errors, _device_type, _measure_ticks, _reports, _sample_perf, MS5611_DEVICE, and perf_print_counter().
Referenced by ms5611::info().
ssize_t MS5611::read (struct file * filp, char * buffer, size_t buflen) virtual
Definition at line 401 of file ms5611.cpp.
References _measure_phase, _measure_ticks, _reports, baro_report, collect(), measure(), MS5611_CONVERSION_INTERVAL, OK, and usleep().
Referenced by ms5611::test().
void MS5611::start_cycle (unsigned delay_ticks = 1) protected
Initialize the automatic measurement state machine and start it.
Parameters
delay_ticks the number of queue ticks before executing the next cycle
Note
This function is called at open and error time. It might make sense to make it more aggressive about resetting the bus in case of errors.
Definition at line 577 of file ms5611.cpp.
References _collect_phase, _measure_phase, _reports, and cycle_trampoline().
Referenced by cycle(), and ioctl().
void MS5611::stop_cycle () protected
Stop the automatic measurement state machine.
Definition at line 590 of file ms5611.cpp.
Referenced by ioctl(), and ~MS5611().
Member Data Documentation
orb_advert_t MS5611::_baro_topic protected
Definition at line 165 of file ms5611.cpp.
Referenced by collect(), and init().
int MS5611::_class_instance protected
Definition at line 167 of file ms5611.cpp.
Referenced by init(), and ~MS5611().
bool MS5611::_collect_phase protected
Definition at line 155 of file ms5611.cpp.
Referenced by cycle(), and start_cycle().
perf_counter_t MS5611::_comms_errors protected
Definition at line 171 of file ms5611.cpp.
Referenced by collect(), measure(), print_info(), and ~MS5611().
enum MS56XX_DEVICE_TYPES MS5611::_device_type protected
Definition at line 154 of file ms5611.cpp.
Referenced by collect(), init(), and print_info().
Device* MS5611::_interface protected
Definition at line 146 of file ms5611.cpp.
Referenced by collect(), cycle(), init(), measure(), MS5611(), and ~MS5611().
perf_counter_t MS5611::_measure_perf protected
Definition at line 170 of file ms5611.cpp.
Referenced by measure(), and ~MS5611().
unsigned MS5611::_measure_phase protected
Definition at line 156 of file ms5611.cpp.
Referenced by collect(), cycle(), init(), measure(), read(), and start_cycle().
unsigned MS5611::_measure_ticks protected
Definition at line 151 of file ms5611.cpp.
Referenced by cycle(), ioctl(), print_info(), and read().
int64_t MS5611::_OFF protected
Definition at line 160 of file ms5611.cpp.
Referenced by collect().
int MS5611::_orb_class_instance protected
Definition at line 166 of file ms5611.cpp.
Referenced by init().
float MS5611::_P protected
Definition at line 162 of file ms5611.cpp.
Referenced by collect().
ms5611::prom_s MS5611::_prom protected
Definition at line 148 of file ms5611.cpp.
Referenced by collect().
ringbuffer::RingBuffer* MS5611::_reports protected
Definition at line 153 of file ms5611.cpp.
Referenced by collect(), init(), ioctl(), print_info(), read(), start_cycle(), and ~MS5611().
perf_counter_t MS5611::_sample_perf protected
Definition at line 169 of file ms5611.cpp.
Referenced by collect(), print_info(), and ~MS5611().
int64_t MS5611::_SENS protected
Definition at line 161 of file ms5611.cpp.
Referenced by collect().
float MS5611::_T protected
Definition at line 163 of file ms5611.cpp.
Referenced by collect().
int32_t MS5611::_TEMP protected
Definition at line 159 of file ms5611.cpp.
Referenced by collect().
struct work_s MS5611::_work protected
Definition at line 150 of file ms5611.cpp.
The documentation for this class was generated from the following file:
src/drivers/barometer/ms5611/ms5611.cpp