PX4 Firmware: src/lib/drivers/led/led.cpp File Reference
led.cpp File Reference
#include <px4_config.h>
#include <drivers/device/device.h>
#include <drivers/drv_board_led.h>
#include <stdio.h>
Classes
class LED
Functions
__BEGIN_DECLS void led_init ()
Ideally we'd be able to get these from up_internal.h, but since we want to be able to disable the NuttX use of leds for system indication at will and there is no separate switch, we need to build independent of the CONFIG_ARCH_LEDS configuration switch.
void led_on (int led)
void led_off (int led)
void led_toggle (int led)
void drv_led_start (void)
Function Documentation
void drv_led_start (void)
Definition at line 116 of file led.cpp.
References LED::LED().
__BEGIN_DECLS void led_init ()
Ideally we'd be able to get these from up_internal.h, but since we want to be able to disable the NuttX use of leds for system indication at will and there is no separate switch, we need to build independent of the CONFIG_ARCH_LEDS configuration switch.
Definition at line 72 of file led.c.
Referenced by LED::_measure(), and LED::init().
void led_off (int led)
Definition at line 97 of file led.c.
Referenced by LED::devIOCTL(), and LED::ioctl().
void led_on (int led)
Definition at line 92 of file led.c.
Referenced by LED::devIOCTL(), and LED::ioctl().
void led_toggle (int led)
Definition at line 102 of file led.c.
Referenced by LED::devIOCTL(), and LED::ioctl().