PX4 Firmware: src/drivers/boards/tap-v1/board_config.h File Reference
board_config.h File Reference
#include <px4_config.h>
#include <nuttx/compiler.h>
#include <stdint.h>
#include "../common/board_common.h"
Macros
#define GPIO_LED1 (GPIO_OUTPUT|GPIO_PUSHPULL|GPIO_SPEED_50MHz|GPIO_OUTPUT_CLEAR|GPIO_PORTC|GPIO_PIN4)
#define GPIO_LED2 (GPIO_OUTPUT|GPIO_PUSHPULL|GPIO_SPEED_50MHz|GPIO_OUTPUT_CLEAR|GPIO_PORTC|GPIO_PIN5)
#define GPIO_BLUE_LED GPIO_LED1
#define GPIO_RED_LED GPIO_LED2
#define GPIO_SPI_CS_SDCARD (GPIO_OUTPUT|GPIO_PUSHPULL|GPIO_SPEED_50MHz|GPIO_OUTPUT_SET|GPIO_PORTB|GPIO_PIN12)
#define GPIO_SPI_SD_SW (GPIO_INPUT|GPIO_PULLUP|GPIO_PORTC|GPIO_PIN2)
#define PX4_I2C_BUS_ONBOARD 1
#define PX4_I2C_BUS_SONAR 2
#define PX4_I2C_BUS_EXPANSION 3
#define PX4_I2C_BUS_ONBOARD_HZ 400000
#define PX4_I2C_BUS_SONAR_HZ 400000
#define PX4_I2C_BUS_EXPANSION_HZ 400000
#define BOARD_NUMBER_I2C_BUSES 3
#define BOARD_I2C_BUS_CLOCK_INIT {PX4_I2C_BUS_ONBOARD_HZ, PX4_I2C_BUS_SONAR_HZ, PX4_I2C_BUS_EXPANSION_HZ}
#define PX4_I2C_MPU6050_ADDR 0x68
#define ADC_CHANNELS (1 << 10)
#define ADC_BATTERY_VOLTAGE_CHANNEL 10
#define ADC_BATTERY_CURRENT_CHANNEL ((uint8_t)(-1))
#define BOARD_BATTERY1_V_DIV (9.0f)
#define TONE_ALARM_TIMER 8 /* timer 8 */
#define TONE_ALARM_CHANNEL 3 /* channel 3 */
#define GPIO_TONE_ALARM_IDLE (GPIO_OUTPUT|GPIO_PUSHPULL|GPIO_SPEED_2MHz|GPIO_OUTPUT_CLEAR|GPIO_PORTC|GPIO_PIN8)
#define GPIO_TONE_ALARM (GPIO_ALT|GPIO_AF2|GPIO_SPEED_2MHz|GPIO_FLOAT|GPIO_PUSHPULL|GPIO_PORTC|GPIO_PIN8)
#define GPIO_TIM3_CH1OUT GPIO_TIM3_CH1OUT_1
#define GPIO_TIM3_CH2OUT GPIO_TIM3_CH2OUT_1
#define GPIO_TIM3_CH3OUT GPIO_TIM3_CH3OUT_1
#define GPIO_TIM3_CH4OUT GPIO_TIM3_CH4OUT_1
#define DIRECT_PWM_OUTPUT_CHANNELS 4
#define GPIO_TIM3_CH1IN GPIO_TIM3_CH1IN_1
#define GPIO_TIM3_CH2IN GPIO_TIM3_CH2IN_1
#define GPIO_TIM3_CH3IN GPIO_TIM3_CH3IN_1
#define GPIO_TIM3_CH4IN GPIO_TIM3_CH4IN_1
#define DIRECT_INPUT_TIMER_CHANNELS 4
#define BOARD_HAS_LED_PWM
#define BOARD_HAS_SHARED_PWM_TIMERS
#define LED_TIM3_CH1OUT GPIO_TIM3_CH1OUT
#define LED_TIM3_CH2OUT GPIO_TIM3_CH2OUT
#define LED_TIM3_CH3OUT GPIO_TIM3_CH3OUT
#define BOARD_PWM_DRIVE_ACTIVE_LOW 1
#define GPIO_OTGFS_VBUS (GPIO_INPUT|GPIO_FLOAT|GPIO_PORTA|GPIO_PIN9)
#define RC_SERIAL_PORT "/dev/ttyS5" /* No HW invert support */
#define HRT_TIMER 1 /* use timer1 for the HRT */
#define HRT_TIMER_CHANNEL 1 /* use capture/compare channel */
#define BOARD_NAME "TAP_V1"
#define BOARD_ADC_USB_CONNECTED (px4_arch_gpioread(GPIO_OTGFS_VBUS))
#define BOARD_ADC_BRICK_VALID (1)
#define BOARD_ADC_SERVO_VALID (1)
#define BOARD_ADC_PERIPH_5V_OC (0)
#define BOARD_ADC_HIPOWER_5V_OC (0)
#define BOARD_HAS_PWM DIRECT_PWM_OUTPUT_CHANNELS
#define BOARD_HAS_POWER_CONTROL 1
#define BOARD_DMA_ALLOC_POOL_SIZE 5120
#define MS_PWR_BUTTON_DOWN 200
#define KEY_AD_GPIO (GPIO_INPUT|GPIO_PULLDOWN|GPIO_EXTI|GPIO_PORTC|GPIO_PIN1)
#define POWER_ON_GPIO (GPIO_OUTPUT|GPIO_PUSHPULL|GPIO_SPEED_2MHz|GPIO_OUTPUT_SET|GPIO_PORTA|GPIO_PIN4)
#define POWER_OFF_GPIO (GPIO_INPUT|GPIO_PULLDOWN|GPIO_PORTA|GPIO_PIN4)
#define GPIO_S0 (GPIO_OUTPUT|GPIO_PUSHPULL|GPIO_SPEED_50MHz|GPIO_OUTPUT_CLEAR|GPIO_PORTC|GPIO_PIN15)
#define GPIO_S1 (GPIO_OUTPUT|GPIO_PUSHPULL|GPIO_SPEED_50MHz|GPIO_OUTPUT_CLEAR|GPIO_PORTC|GPIO_PIN14)
#define GPIO_S2 (GPIO_OUTPUT|GPIO_PUSHPULL|GPIO_SPEED_50MHz|GPIO_OUTPUT_CLEAR|GPIO_PORTC|GPIO_PIN13)
#define GPIO_PCON_RADIO (GPIO_OUTPUT|GPIO_PUSHPULL|GPIO_SPEED_2MHz|GPIO_OUTPUT_SET|GPIO_PORTC|GPIO_PIN3)
#define RF_RADIO_POWER_CONTROL(_on_true) px4_arch_gpiowrite(GPIO_PCON_RADIO, !(_on_true))
#define GPIO_TEMP_CONT (GPIO_OUTPUT|GPIO_PUSHPULL|GPIO_SPEED_2MHz|GPIO_OUTPUT_CLEAR|GPIO_PORTB|GPIO_PIN4)
#define TEMP_CONTROL(_on_true) px4_arch_gpiowrite(GPIO_TEMP_CONT, (_on_true))
#define FLASH_BASED_PARAMS
#define board_spi_reset(ms)
#define board_peripheral_reset(ms)
Functions
__BEGIN_DECLS void stm32_spiinitialize (void)
int stm32_spi_bus_initialize (void)
void stm32_usbinitialize (void)
int board_sdio_initialize (void)
int board_i2c_initialize (void)
void board_pwr_init (int stage)
bool board_pwr_button_down (void)
Macro Definition Documentation
#define ADC_BATTERY_CURRENT_CHANNEL ((uint8_t)(-1))
Definition at line 137 of file board_config.h.
#define ADC_BATTERY_VOLTAGE_CHANNEL 10
Definition at line 136 of file board_config.h.
#define ADC_CHANNELS (1 << 10)
Definition at line 132 of file board_config.h.
#define BOARD_ADC_BRICK_VALID (1)
Definition at line 219 of file board_config.h.
#define BOARD_ADC_HIPOWER_5V_OC (0)
Definition at line 222 of file board_config.h.
#define BOARD_ADC_PERIPH_5V_OC (0)
Definition at line 221 of file board_config.h.
#define BOARD_ADC_SERVO_VALID (1)
Definition at line 220 of file board_config.h.
#define BOARD_ADC_USB_CONNECTED (px4_arch_gpioread(GPIO_OTGFS_VBUS))
Definition at line 218 of file board_config.h.
#define BOARD_BATTERY1_V_DIV (9.0f)
Definition at line 143 of file board_config.h.
#define BOARD_DMA_ALLOC_POOL_SIZE 5120
Definition at line 230 of file board_config.h.
#define BOARD_HAS_LED_PWM
Definition at line 190 of file board_config.h.
#define BOARD_HAS_POWER_CONTROL 1
Definition at line 226 of file board_config.h.
#define BOARD_HAS_PWM DIRECT_PWM_OUTPUT_CHANNELS
Definition at line 224 of file board_config.h.
#define BOARD_HAS_SHARED_PWM_TIMERS
Definition at line 191 of file board_config.h.
#define BOARD_I2C_BUS_CLOCK_INIT {PX4_I2C_BUS_ONBOARD_HZ, PX4_I2C_BUS_SONAR_HZ, PX4_I2C_BUS_EXPANSION_HZ}
Definition at line 106 of file board_config.h.
#define BOARD_NAME "TAP_V1"
Definition at line 212 of file board_config.h.
#define BOARD_NUMBER_I2C_BUSES 3
Definition at line 105 of file board_config.h.
#define board_peripheral_reset (ms)
Definition at line 293 of file board_config.h.
#define BOARD_PWM_DRIVE_ACTIVE_LOW 1
Definition at line 196 of file board_config.h.
#define board_spi_reset (ms)
Definition at line 292 of file board_config.h.
#define DIRECT_INPUT_TIMER_CHANNELS 4
Definition at line 188 of file board_config.h.
#define DIRECT_PWM_OUTPUT_CHANNELS 4
Definition at line 182 of file board_config.h.
#define FLASH_BASED_PARAMS
Definition at line 247 of file board_config.h.
#define GPIO_BLUE_LED GPIO_LED1
Definition at line 65 of file board_config.h.
Referenced by led_init(), led_off(), led_on(), and led_toggle().
#define GPIO_LED1 (GPIO_OUTPUT|GPIO_PUSHPULL|GPIO_SPEED_50MHz|GPIO_OUTPUT_CLEAR|GPIO_PORTC|GPIO_PIN4)
Definition at line 63 of file board_config.h.
#define GPIO_LED2 (GPIO_OUTPUT|GPIO_PUSHPULL|GPIO_SPEED_50MHz|GPIO_OUTPUT_CLEAR|GPIO_PORTC|GPIO_PIN5)
Definition at line 64 of file board_config.h.
#define GPIO_OTGFS_VBUS (GPIO_INPUT|GPIO_FLOAT|GPIO_PORTA|GPIO_PIN9)
Definition at line 203 of file board_config.h.
#define GPIO_PCON_RADIO (GPIO_OUTPUT|GPIO_PUSHPULL|GPIO_SPEED_2MHz|GPIO_OUTPUT_SET|GPIO_PORTC|GPIO_PIN3)
Definition at line 241 of file board_config.h.
Referenced by stm32_boardinitialize().
#define GPIO_RED_LED GPIO_LED2
Definition at line 66 of file board_config.h.
Referenced by led_init(), led_off(), led_on(), and led_toggle().
#define GPIO_S0 (GPIO_OUTPUT|GPIO_PUSHPULL|GPIO_SPEED_50MHz|GPIO_OUTPUT_CLEAR|GPIO_PORTC|GPIO_PIN15)
Definition at line 237 of file board_config.h.
Referenced by tap_esc_common::select_responder(), and stm32_boardinitialize().
#define GPIO_S1 (GPIO_OUTPUT|GPIO_PUSHPULL|GPIO_SPEED_50MHz|GPIO_OUTPUT_CLEAR|GPIO_PORTC|GPIO_PIN14)
Definition at line 238 of file board_config.h.
Referenced by tap_esc_common::select_responder(), and stm32_boardinitialize().
#define GPIO_S2 (GPIO_OUTPUT|GPIO_PUSHPULL|GPIO_SPEED_50MHz|GPIO_OUTPUT_CLEAR|GPIO_PORTC|GPIO_PIN13)
Definition at line 239 of file board_config.h.
Referenced by tap_esc_common::select_responder(), and stm32_boardinitialize().
#define GPIO_SPI_CS_SDCARD (GPIO_OUTPUT|GPIO_PUSHPULL|GPIO_SPEED_50MHz|GPIO_OUTPUT_SET|GPIO_PORTB|GPIO_PIN12)
Definition at line 79 of file board_config.h.
#define GPIO_SPI_SD_SW (GPIO_INPUT|GPIO_PULLUP|GPIO_PORTC|GPIO_PIN2)
Definition at line 80 of file board_config.h.
Referenced by stm32_spi2status(), and stm32_spiinitialize().
#define GPIO_TEMP_CONT (GPIO_OUTPUT|GPIO_PUSHPULL|GPIO_SPEED_2MHz|GPIO_OUTPUT_CLEAR|GPIO_PORTB|GPIO_PIN4)
Definition at line 244 of file board_config.h.
Referenced by stm32_boardinitialize().
#define GPIO_TIM3_CH1IN GPIO_TIM3_CH1IN_1
Definition at line 184 of file board_config.h.
#define GPIO_TIM3_CH1OUT GPIO_TIM3_CH1OUT_1
Definition at line 178 of file board_config.h.
#define GPIO_TIM3_CH2IN GPIO_TIM3_CH2IN_1
Definition at line 185 of file board_config.h.
#define GPIO_TIM3_CH2OUT GPIO_TIM3_CH2OUT_1
Definition at line 179 of file board_config.h.
#define GPIO_TIM3_CH3IN GPIO_TIM3_CH3IN_1
Definition at line 186 of file board_config.h.
#define GPIO_TIM3_CH3OUT GPIO_TIM3_CH3OUT_1
Definition at line 180 of file board_config.h.
#define GPIO_TIM3_CH4IN GPIO_TIM3_CH4IN_1
Definition at line 187 of file board_config.h.
#define GPIO_TIM3_CH4OUT GPIO_TIM3_CH4OUT_1
Definition at line 181 of file board_config.h.
#define GPIO_TONE_ALARM (GPIO_ALT|GPIO_AF2|GPIO_SPEED_2MHz|GPIO_FLOAT|GPIO_PUSHPULL|GPIO_PORTC|GPIO_PIN8)
Definition at line 163 of file board_config.h.
#define GPIO_TONE_ALARM_IDLE (GPIO_OUTPUT|GPIO_PUSHPULL|GPIO_SPEED_2MHz|GPIO_OUTPUT_CLEAR|GPIO_PORTC|GPIO_PIN8)
Definition at line 162 of file board_config.h.
#define HRT_TIMER 1 /* use timer1 for the HRT */
Definition at line 209 of file board_config.h.
#define HRT_TIMER_CHANNEL 1 /* use capture/compare channel */
Definition at line 210 of file board_config.h.
#define KEY_AD_GPIO (GPIO_INPUT|GPIO_PULLDOWN|GPIO_EXTI|GPIO_PORTC|GPIO_PIN1)
Definition at line 233 of file board_config.h.
Referenced by board_pwr_button_down(), and board_pwr_init().
#define LED_TIM3_CH1OUT GPIO_TIM3_CH1OUT
Definition at line 192 of file board_config.h.
#define LED_TIM3_CH2OUT GPIO_TIM3_CH2OUT
Definition at line 193 of file board_config.h.
#define LED_TIM3_CH3OUT GPIO_TIM3_CH3OUT
Definition at line 194 of file board_config.h.
#define MS_PWR_BUTTON_DOWN 200
Definition at line 232 of file board_config.h.
Referenced by board_button_irq().
#define POWER_OFF_GPIO (GPIO_INPUT|GPIO_PULLDOWN|GPIO_PORTA|GPIO_PIN4)
Definition at line 235 of file board_config.h.
#define POWER_ON_GPIO (GPIO_OUTPUT|GPIO_PUSHPULL|GPIO_SPEED_2MHz|GPIO_OUTPUT_SET|GPIO_PORTA|GPIO_PIN4)
Definition at line 234 of file board_config.h.
Referenced by board_pwr_init().
#define PX4_I2C_BUS_EXPANSION 3
Definition at line 99 of file board_config.h.
#define PX4_I2C_BUS_EXPANSION_HZ 400000
Definition at line 103 of file board_config.h.
#define PX4_I2C_BUS_ONBOARD 1
Definition at line 97 of file board_config.h.
#define PX4_I2C_BUS_ONBOARD_HZ 400000
Definition at line 101 of file board_config.h.
#define PX4_I2C_BUS_SONAR 2
Definition at line 98 of file board_config.h.
#define PX4_I2C_BUS_SONAR_HZ 400000
Definition at line 102 of file board_config.h.
#define PX4_I2C_MPU6050_ADDR 0x68
Definition at line 123 of file board_config.h.
#define RC_SERIAL_PORT "/dev/ttyS5" /* No HW invert support */
Definition at line 205 of file board_config.h.
#define RF_RADIO_POWER_CONTROL (_on_true) px4_arch_gpiowrite(GPIO_PCON_RADIO, !(_on_true))
Definition at line 242 of file board_config.h.
Referenced by RCInput::init().
#define TEMP_CONTROL (_on_true) px4_arch_gpiowrite(GPIO_TEMP_CONT, (_on_true))
Definition at line 245 of file board_config.h.
#define TONE_ALARM_CHANNEL 3 /* channel 3 */
Definition at line 161 of file board_config.h.
#define TONE_ALARM_TIMER 8 /* timer 8 */
Definition at line 160 of file board_config.h.
Function Documentation
int board_i2c_initialize (void)
bool board_pwr_button_down (void)
Definition at line 182 of file pwr.c.
References KEY_AD_GPIO.
Referenced by board_button_irq(), and board_register_power_state_notification_cb().
void board_pwr_init (int stage)
Definition at line 162 of file pwr.c.
References board_button_irq(), KEY_AD_GPIO, and POWER_ON_GPIO.
Referenced by board_app_initialize(), and stm32_boardinitialize().
int board_sdio_initialize (void)
Definition at line 101 of file sdio.c.
References message, OK, and spi.
int stm32_spi_bus_initialize (void)
Definition at line 109 of file spi.c.
References message, OK, PX4_BARO_BUS_FIRST_CS, PX4_BARO_BUS_LAST_CS, PX4_ERR, PX4_EXTERNAL1_BUS_FIRST_CS, PX4_EXTERNAL1_BUS_LAST_CS, PX4_EXTERNAL2_BUS_FIRST_CS, PX4_EXTERNAL2_BUS_LAST_CS, PX4_ICM_BUS_FIRST_CS, PX4_ICM_BUS_LAST_CS, PX4_MEMORY_BUS_FIRST_CS, PX4_MEMORY_BUS_LAST_CS, PX4_RAMTRON_BUS_FIRST_CS, PX4_RAMTRON_BUS_LAST_CS, PX4_SENSOR1_BUS_FIRST_CS, PX4_SENSOR1_BUS_LAST_CS, PX4_SENSOR2_BUS_FIRST_CS, PX4_SENSOR2_BUS_LAST_CS, PX4_SENSOR4_BUS_FIRST_CS, PX4_SENSOR4_BUS_LAST_CS, PX4_SENSOR5_BUS_FIRST_CS, PX4_SENSOR5_BUS_LAST_CS, PX4_SENSORS_BUS_FIRST_CS, PX4_SENSORS_BUS_LAST_CS, PX4_SPI_BUS_BARO, PX4_SPI_BUS_EXPANSION, PX4_SPI_BUS_EXTERNAL1, PX4_SPI_BUS_EXTERNAL2, PX4_SPI_BUS_ICM, PX4_SPI_BUS_MEMORY, PX4_SPI_BUS_RAMTRON, PX4_SPI_BUS_SENSOR1, PX4_SPI_BUS_SENSOR2, PX4_SPI_BUS_SENSOR4, PX4_SPI_BUS_SENSOR5, PX4_SPI_BUS_SENSORS, spi_baro, spi_expansion, spi_ext, spi_fram, spi_icm, spi_memory, spi_sensor1, spi_sensor2, spi_sensor4, spi_sensor5, and spi_sensors.
__BEGIN_DECLS void stm32_spiinitialize (void)
Definition at line 71 of file spi.c.
References arraySize, board_get_hw_version(), board_gpio_init(), GPIO_DRDY_HMC5983, GPIO_DRDY_ICM_20608_G, GPIO_DRDY_ICM_2060X, GPIO_DRDY_LIS3MDL, GPIO_DRDY_MPU9250, GPIO_EXTI_ACCEL_DRDY, GPIO_EXTI_GYRO_DRDY, GPIO_EXTI_ICM_2060X_DRDY, GPIO_EXTI_MAG_DRDY, GPIO_EXTI_MPU_DRDY, GPIO_SPI1_CS_PC1, GPIO_SPI1_CS_PC13, GPIO_SPI1_CS_PC15, GPIO_SPI1_CS_PC2, GPIO_SPI1_CS_PD7, GPIO_SPI2_CS_PD10, GPIO_SPI3_CS_BARO, GPIO_SPI4_CS_PC13, GPIO_SPI4_CS_PC15, GPIO_SPI4_GPIO_PC14, GPIO_SPI4_NSS_PE4, GPIO_SPI5_CS, GPIO_SPI6_CS, GPIO_SPI_CS_ACCEL_MAG, GPIO_SPI_CS_BARO, GPIO_SPI_CS_EXT0, GPIO_SPI_CS_FRAM, GPIO_SPI_CS_GYRO, GPIO_SPI_CS_HMC5983, GPIO_SPI_CS_ICM_20608_G, GPIO_SPI_CS_ICM_2060X, GPIO_SPI_CS_LIS3MDL, GPIO_SPI_CS_MEMS, GPIO_SPI_CS_MPU, GPIO_SPI_CS_MPU6500, GPIO_SPI_CS_MPU9250, GPIO_SPI_CS_MS5611, GPIO_SPI_CS_SDCARD, GPIO_SPI_CS_TEMPCAL_EEPROM, GPIO_SPI_SD_SW, PX4_SPIDEV_ACCEL_MAG, PX4_SPIDEV_BARO, PX4_SPIDEV_EXT_ACCEL_MAG, PX4_SPIDEV_EXT_BARO, PX4_SPIDEV_EXT_BMI, PX4_SPIDEV_EXT_GYRO, PX4_SPIDEV_EXT_MPU, PX4_SPIDEV_GYRO, PX4_SPIDEV_HMC, PX4_SPIDEV_ICM_20608, PX4_SPIDEV_MPU, spi1selects_gpio, spi2selects_gpio, spi4selects_gpio, spi5selects_gpio, spi6selects_gpio, stm32_spi1select(), stm32_spi1status(), stm32_spi2select(), stm32_spi2status(), stm32_spi3select(), stm32_spi4select(), and stm32_spi4status().
Referenced by board_spi_reset().
void stm32_usbinitialize (void)
Definition at line 78 of file usb.c.