PX4 Firmware: matrix::typeFunction Namespace Reference
matrix::typeFunction Namespace Reference
Functions
template<typename Type >
Type min (const Type x, const Type y)
template<typename Type >
Type max (const Type x, const Type y)
template<typename Type >
Type constrain (const Type x, const Type lower_bound, const Type upper_bound)
Function Documentation
constrain()
template<typename Type > Type matrix::typeFunction::constrain (const Type x, const Type lower_bound, const Type upper_bound)
Definition at line 618 of file Matrix.hpp.
References max(), and min().
Referenced by matrix::constrain(), and main().
max()
template<typename Type > Type matrix::typeFunction::max (const Type x, const Type y)
Definition at line 602 of file Matrix.hpp.
Referenced by constrain(), main(), and matrix::max().
min()
template<typename Type > Type matrix::typeFunction::min (const Type x, const Type y)
Definition at line 586 of file Matrix.hpp.
Referenced by constrain(), main(), and matrix::min().