PX4 Firmware: MavlinkStreamSysStatus Class Reference
MavlinkStreamSysStatus Class Reference
Public Member Functions
const char * get_name () const
uint16_t get_id ()
unsigned get_size ()
Get maximal total messages size on update.
Public Member Functions inherited from MavlinkStream
MavlinkStream (Mavlink *mavlink)
virtual ~MavlinkStream ()=default
MavlinkStream (const MavlinkStream &)=delete
MavlinkStream & operator= (const MavlinkStream &)=delete
MavlinkStream (MavlinkStream &&)=delete
MavlinkStream & operator= (MavlinkStream &&)=delete
void set_interval (const int interval)
Get the interval.
int get_interval ()
Get the interval.
int update (const hrt_abstime &t)
Update subscriptions and send message if necessary.
virtual bool const_rate ()
virtual unsigned get_size_avg ()
Get the average message size.
bool first_message_sent () const
void reset_last_sent ()
Reset the time of last sent to 0.
Static Public Member Functions
static const char * get_name_static ()
static uint16_t get_id_static ()
static MavlinkStream * new_instance (Mavlink *mavlink)
Protected Member Functions
MavlinkStreamSysStatus (Mavlink *mavlink)
bool send (const hrt_abstime t)
Protected Member Functions inherited from MavlinkStream
virtual void update_data ()
Function to collect/update data for the streams at a high rate independant of actual stream rate.
Private Member Functions
MavlinkStreamSysStatus (MavlinkStreamSysStatus &)=delete
MavlinkStreamSysStatus & operator= (const MavlinkStreamSysStatus &)=delete
Private Attributes
MavlinkOrbSubscription * _status_sub
MavlinkOrbSubscription * _cpuload_sub
MavlinkOrbSubscription * _battery_status_sub
uint64_t _status_timestamp {0}
uint64_t _cpuload_timestamp {0}
uint64_t _battery_status_timestamp {0}
Additional Inherited Members
Public Attributes inherited from MavlinkStream
MavlinkStream * next {nullptr}
Protected Attributes inherited from MavlinkStream
Mavlink *const _mavlink
int _interval {1000000}
if set to negative value = unlimited rate
Detailed Description
Definition at line 498 of file mavlink_messages.cpp.
Constructor & Destructor Documentation
MavlinkStreamSysStatus::MavlinkStreamSysStatus (MavlinkStreamSysStatus &) private delete
MavlinkStreamSysStatus::MavlinkStreamSysStatus (Mavlink * mavlink) inline explicit protected
Definition at line 545 of file mavlink_messages.cpp.
Member Function Documentation
uint16_t MavlinkStreamSysStatus::get_id () inline virtual
Implements MavlinkStream.
Definition at line 516 of file mavlink_messages.cpp.
References MavlinkStreamHeartbeat::get_id_static().
static uint16_t MavlinkStreamSysStatus::get_id_static () inline static
Definition at line 511 of file mavlink_messages.cpp.
const char* MavlinkStreamSysStatus::get_name () const inline virtual
Implements MavlinkStream.
Definition at line 501 of file mavlink_messages.cpp.
References get_name_static().
static const char* MavlinkStreamSysStatus::get_name_static () inline static
Definition at line 506 of file mavlink_messages.cpp.
Referenced by get_name().
unsigned MavlinkStreamSysStatus::get_size () inline virtual
Get maximal total messages size on update.
Implements MavlinkStream.
Definition at line 526 of file mavlink_messages.cpp.
static MavlinkStream* MavlinkStreamSysStatus::new_instance (Mavlink * mavlink) inline static
Definition at line 521 of file mavlink_messages.cpp.
MavlinkStreamSysStatus& MavlinkStreamSysStatus::operator= (const MavlinkStreamSysStatus &) private delete
bool MavlinkStreamSysStatus::send (const hrt_abstime t) inline protected virtual
Implements MavlinkStream.
Definition at line 551 of file mavlink_messages.cpp.
References MavlinkStream::_mavlink, battery_status_s::cell_count, battery_status_s::connected, cpuload, battery_status_s::current_filtered_a, battery_status_s::discharged_mah, f(), Mavlink::get_channel(), cpuload_s::load, msg, vehicle_status_s::onboard_control_sensors_enabled, vehicle_status_s::onboard_control_sensors_health, vehicle_status_s::onboard_control_sensors_present, battery_status_s::remaining, status, battery_status_s::temperature, MavlinkOrbSubscription::update(), battery_status_s::voltage_filtered_v, and battery_status_s::voltage_v.
Member Data Documentation
MavlinkOrbSubscription* MavlinkStreamSysStatus::_battery_status_sub private
Definition at line 534 of file mavlink_messages.cpp.
uint64_t MavlinkStreamSysStatus::_battery_status_timestamp {0} private
Definition at line 538 of file mavlink_messages.cpp.
MavlinkOrbSubscription* MavlinkStreamSysStatus::_cpuload_sub private
Definition at line 533 of file mavlink_messages.cpp.
uint64_t MavlinkStreamSysStatus::_cpuload_timestamp {0} private
Definition at line 537 of file mavlink_messages.cpp.
MavlinkOrbSubscription* MavlinkStreamSysStatus::_status_sub private
Definition at line 532 of file mavlink_messages.cpp.
uint64_t MavlinkStreamSysStatus::_status_timestamp {0} private
Definition at line 536 of file mavlink_messages.cpp.
The documentation for this class was generated from the following file:
src/modules/mavlink/mavlink_messages.cpp