PX4 Firmware: Mavlink Class Reference
Mavlink Class Reference
#include <mavlink_main.h>
Classes
struct mavlink_message_buffer
struct ping_statistics_s
Public Types
enum MAVLINK_MODE {
MAVLINK_MODE_NORMAL = 0, MAVLINK_MODE_CUSTOM, MAVLINK_MODE_ONBOARD, MAVLINK_MODE_OSD,
MAVLINK_MODE_MAGIC, MAVLINK_MODE_CONFIG, MAVLINK_MODE_IRIDIUM, MAVLINK_MODE_MINIMAL
}
enum BROADCAST_MODE { BROADCAST_MODE_OFF = 0, BROADCAST_MODE_ON }
enum FLOW_CONTROL_MODE { FLOW_CONTROL_OFF = 0, FLOW_CONTROL_AUTO, FLOW_CONTROL_ON }
Public Member Functions
Mavlink ()
Constructor.
~Mavlink ()
Destructor, also kills the mavlinks task.
void display_status ()
Display the mavlink status.
void display_status_streams ()
Display the status of all enabled streams.
mavlink_message_t * get_buffer ()
mavlink_status_t * get_status ()
void set_proto_version (unsigned version)
Set the MAVLink version.
int get_uart_fd ()
int get_system_id ()
Get the MAVLink system id.
int get_component_id ()
Get the MAVLink component id.
enum MAVLINK_MODE get_mode ()
bool get_hil_enabled ()
bool get_use_hil_gps ()
bool get_forward_externalsp ()
bool get_flow_control_enabled ()
bool get_forwarding_on ()
bool get_config_link_on ()
void set_config_link_on (bool on)
bool is_connected ()
bool broadcast_enabled ()
unsigned get_free_tx_buf ()
Get the free space in the transmit buffer.
int set_hil_enabled (bool hil_enabled)
Enable / disable Hardware in the Loop simulation mode.
void set_manual_input_mode_generation (bool generation_enabled)
Set manual input generation mode.
void set_protocol (Protocol p)
Set communication protocol for this mavlink instance.
bool get_manual_input_mode_generation ()
Get the manual input generation mode.
void begin_send ()
This is the beginning of a MAVLINK_START_UART_SEND/MAVLINK_END_UART_SEND transaction.
void send_bytes (const uint8_t *buf, unsigned packet_len)
Send bytes out on the link.
int send_packet ()
Flush the transmit buffer and send one MAVLink packet.
void resend_message (mavlink_message_t *msg)
Resend message as is, don't change sequence number and CRC.
void handle_message (const mavlink_message_t *msg)
MavlinkOrbSubscription * add_orb_subscription (const orb_id_t topic, int instance=0, bool disable_sharing=false)
Add a mavlink orb topic subscription while ensuring that only a single object exists for a given topic id and instance.
int get_instance_id ()
int enable_flow_control (enum FLOW_CONTROL_MODE enabled)
Enable / disable hardware flow control.
mavlink_channel_t get_channel ()
void configure_stream_threadsafe (const char *stream_name, float rate=-1.0f)
orb_advert_t * get_mavlink_log_pub ()
void send_statustext_info (const char *string)
Send a status text with loglevel INFO.
void send_statustext_critical (const char *string)
Send a status text with loglevel CRITICAL.
void send_statustext_emergency (const char *string)
Send a status text with loglevel EMERGENCY.
void send_statustext (unsigned char severity, const char *string)
Send a status text with loglevel, the difference from mavlink_log_xxx() is that message sent only on this mavlink connection.
void send_autopilot_capabilites ()
Send the capabilities of this autopilot in terms of the MAVLink spec.
void send_protocol_version ()
Send the protocol version of MAVLink.
MavlinkStream * get_streams () const
float get_rate_mult ()
float get_baudrate ()
void set_has_received_messages (bool received_messages)
bool get_has_received_messages ()
void set_wait_to_transmit (bool wait)
bool get_wait_to_transmit ()
bool should_transmit ()
bool message_buffer_write (const void *ptr, int size)
void lockMessageBufferMutex (void)
void unlockMessageBufferMutex (void)
void count_txerr ()
Count a transmission error.
void count_txbytes (unsigned n)
Count transmitted bytes.
void count_txerrbytes (unsigned n)
Count bytes not transmitted because of errors.
void count_rxbytes (unsigned n)
Count received bytes.
struct telemetry_status_s & get_rx_status ()
Get the receive status of this MAVLink link.
ringbuffer::RingBuffer * get_logbuffer ()
unsigned get_system_type ()
Protocol get_protocol ()
unsigned short get_network_port ()
unsigned short get_remote_port ()
int get_socket_fd ()
bool get_client_source_initialized ()
uint64_t get_start_time ()
bool is_usb_uart ()
bool accepting_commands ()
int get_data_rate ()
void set_data_rate (int rate)
unsigned get_main_loop_delay () const
MavlinkShell * get_shell ()
get the Mavlink shell.
void close_shell ()
close the Mavlink shell if it is open
MavlinkULog * get_ulog_streaming ()
get ulog streaming if active, nullptr otherwise
void try_start_ulog_streaming (uint8_t target_system, uint8_t target_component)
void request_stop_ulog_streaming ()
void set_uorb_main_fd (int fd, unsigned int interval)
bool ftp_enabled () const
struct ping_statistics_s & get_ping_statistics ()
Get the ping statistics of this MAVLink link.
Static Public Member Functions
static int start (int argc, char *argv[])
Start the mavlink task.
static int stream_command (int argc, char *argv[])
static int instance_count ()
static Mavlink * new_instance ()
static Mavlink * get_instance (int instance)
static Mavlink * get_instance_for_device (const char *device_name)
static Mavlink * get_instance_for_network_port (unsigned long port)
static int destroy_all_instances ()
static int get_status_all_instances (bool show_streams_status)
static bool instance_exists (const char *device_name, Mavlink *self)
static void forward_message (const mavlink_message_t *msg, Mavlink *self)
static int get_uart_fd (unsigned index)
static const char * mavlink_mode_str (enum MAVLINK_MODE mode)
static void set_boot_complete ()
Set the boot complete flag on all instances.
static int start_helper (int argc, char *argv[])
static bool boot_complete ()
Public Attributes
const char * _device_name
bool _task_should_exit
if true, mavlink task should exit
Protected Attributes
Mavlink * next
Private Member Functions
void mavlink_update_system ()
int mavlink_open_uart (int baudrate, const char *uart_name, bool force_flow_control)
int configure_stream (const char *stream_name, const float rate=-1.0f)
Configure a single stream.
int configure_streams_to_default (const char *configure_single_stream=nullptr)
Configure default streams according to _mode for either all streams or only a single stream.
void adjust_stream_rates (const float multiplier)
Adjust the stream rates based on the current rate.
int message_buffer_init (int size)
void message_buffer_destroy ()
int message_buffer_count ()
int message_buffer_is_empty ()
int message_buffer_get_ptr (void **ptr, bool *is_part)
void message_buffer_mark_read (int n)
void pass_message (const mavlink_message_t *msg)
void check_radio_config ()
Check the configuration of a connected radio.
void update_rate_mult ()
Update rate mult so total bitrate will be equal to _datarate.
void find_broadcast_address ()
void init_udp ()
int task_main (int argc, char *argv[])
Main mavlink task.
Mavlink (const Mavlink &)
Mavlink operator= (const Mavlink &)
Static Private Member Functions
static int interval_from_rate (float rate)
Private Attributes
int _instance_id
bool _transmitting_enabled
bool _transmitting_enabled_commanded
bool _first_heartbeat_sent {false}
orb_advert_t _mavlink_log_pub
bool _task_running
mavlink_message_t _mavlink_buffer
mavlink_status_t _mavlink_status
bool _hil_enabled
Hardware In the Loop mode.
bool _generate_rc
Generate RC messages from manual input MAVLink messages.
bool _use_hil_gps
Accept GPS HIL messages (for example from an external motion capturing system to fake indoor gps)
bool _forward_externalsp
Forward external setpoint messages to controllers directly if in offboard mode.
bool _is_usb_uart
Port is USB.
bool _wait_to_transmit
Wait to transmit until received messages.
bool _received_messages
Whether we've received valid mavlink messages.
unsigned _main_loop_delay
mainloop delay, depends on data rate
MavlinkOrbSubscription * _subscriptions
MavlinkStream * _streams
MavlinkShell * _mavlink_shell
MavlinkULog * _mavlink_ulog
volatile bool _mavlink_ulog_stop_requested
MAVLINK_MODE _mode
mavlink_channel_t _channel
int32_t _radio_id
ringbuffer::RingBuffer _logbuffer
pthread_t _receive_thread
bool _forwarding_on
bool _ftp_on
int _uart_fd
int _baudrate
int _datarate
data rate for normal streams (attitude, position, etc.)
int _datarate_events
data rate for params, waypoints, text messages
float _rate_mult
hrt_abstime _last_hw_rate_timestamp
unsigned int _mavlink_param_queue_index
If the queue index is not at 0, the queue sending logic will send parameters from the current index to len - 1, the end of the param list.
bool mavlink_link_termination_allowed
char * _subscribe_to_stream
float _subscribe_to_stream_rate
rate of stream to subscribe to (0=disable, -1=unlimited, -2=default)
bool _udp_initialised
enum FLOW_CONTROL_MODE _flow_control_mode
uint64_t _last_write_success_time
uint64_t _last_write_try_time
uint64_t _mavlink_start_time
int32_t _protocol_version_switch
int32_t _protocol_version
unsigned _bytes_tx
unsigned _bytes_txerr
unsigned _bytes_rx
uint64_t _bytes_timestamp
float _rate_tx
float _rate_txerr
float _rate_rx
const char * _interface_name
int _socket_fd
Protocol _protocol
unsigned short _network_port
unsigned short _remote_port
struct telemetry_status_s _rstatus
receive status
struct ping_statistics_s _ping_stats
ping statistics
mavlink_message_buffer _message_buffer
pthread_mutex_t _message_buffer_mutex
pthread_mutex_t _send_mutex
bool _param_initialized
int32_t _broadcast_mode
param_t _param_system_id
param_t _param_component_id
param_t _param_proto_ver
param_t _param_radio_id
param_t _param_system_type
param_t _param_use_hil_gps
param_t _param_forward_externalsp
param_t _param_broadcast
unsigned _system_type
perf_counter_t _loop_perf
loop performance counter
perf_counter_t _txerr_perf
TX error counter.
Static Private Attributes
static bool _boot_complete = false
static constexpr int MAVLINK_MAX_INSTANCES = 4
static constexpr int MAVLINK_MIN_INTERVAL = 1500
static constexpr int MAVLINK_MAX_INTERVAL = 10000
static constexpr float MAVLINK_MIN_MULTIPLIER = 0.0005f
static bool _config_link_on = false
static constexpr unsigned RADIO_BUFFER_CRITICAL_LOW_PERCENTAGE = 25
static constexpr unsigned RADIO_BUFFER_LOW_PERCENTAGE = 35
static constexpr unsigned RADIO_BUFFER_HALF_PERCENTAGE = 50
Detailed Description
Definition at line 86 of file mavlink_main.h.
Member Enumeration Documentation
enum Mavlink::BROADCAST_MODE
Enumerator
BROADCAST_MODE_OFF
BROADCAST_MODE_ON
Definition at line 181 of file mavlink_main.h.
enum Mavlink::FLOW_CONTROL_MODE
Enumerator
FLOW_CONTROL_OFF
FLOW_CONTROL_AUTO
FLOW_CONTROL_ON
Definition at line 186 of file mavlink_main.h.
enum Mavlink::MAVLINK_MODE
Enumerator
MAVLINK_MODE_NORMAL
MAVLINK_MODE_CUSTOM
MAVLINK_MODE_ONBOARD
MAVLINK_MODE_OSD
MAVLINK_MODE_MAGIC
MAVLINK_MODE_CONFIG
MAVLINK_MODE_IRIDIUM
MAVLINK_MODE_MINIMAL
Definition at line 170 of file mavlink_main.h.
Constructor & Destructor Documentation
Mavlink::Mavlink ()
Constructor.
Definition at line 191 of file mavlink_main.cpp.
References _baudrate, _broadcast_mode, _bytes_rx, _bytes_timestamp, _bytes_tx, _bytes_txerr, _channel, _datarate, _datarate_events, _flow_control_mode, _forward_externalsp, _forwarding_on, _ftp_on, _generate_rc, _hil_enabled, _instance_id, _is_usb_uart, _last_hw_rate_timestamp, _last_write_success_time, _last_write_try_time, _logbuffer, _loop_perf, _main_loop_delay, _mavlink_param_queue_index, _mavlink_shell, _mavlink_start_time, _mavlink_status, _mavlink_ulog, _mavlink_ulog_stop_requested, _message_buffer, _message_buffer_mutex, _mode, _network_port, _param_broadcast, _param_component_id, _param_forward_externalsp, _param_initialized, _param_radio_id, _param_system_id, _param_system_type, _param_use_hil_gps, _ping_stats, _protocol, _protocol_version, _protocol_version_switch, _radio_id, _rate_mult, _rate_rx, _rate_tx, _rate_txerr, _receive_thread, _received_messages, _remote_port, _rstatus, _send_mutex, _socket_fd, _streams, _subscribe_to_stream, _subscribe_to_stream_rate, _subscriptions, _system_type, _txerr_perf, _uart_fd, _udp_initialised, _use_hil_gps, _wait_to_transmit, BROADCAST_MODE_OFF, DEFAULT_REMOTE_PORT_UDP, f(), FLOW_CONTROL_OFF, instance_count(), mavlink_link_termination_allowed, MAVLINK_MODE_NORMAL, PARAM_INVALID, PC_COUNT, PC_ELAPSED, perf_alloc, px4_task_exit(), PX4_WARN, SERIAL, and telemetry_status_s::type.
Referenced by start_helper().
Mavlink::~Mavlink ()
Destructor, also kills the mavlinks task.
Definition at line 328 of file mavlink_main.cpp.
References _loop_perf, _task_running, _task_should_exit, _txerr_perf, perf_free(), and usleep().
Mavlink::Mavlink (const Mavlink &) private
Member Function Documentation
bool Mavlink::accepting_commands () inline
Definition at line 462 of file mavlink_main.h.
Referenced by display_status(), MavlinkReceiver::handle_message(), and handle_message().
MavlinkOrbSubscription * Mavlink::add_orb_subscription (const orb_id_t topic, int instance = 0, bool disable_sharing = false)
Add a mavlink orb topic subscription while ensuring that only a single object exists for a given topic id and instance.
Parameters
topic orb topic id
instance topic instance
disable_sharing if true, force creating a new instance
Definition at line 1359 of file mavlink_main.cpp.
References _subscriptions, MavlinkOrbSubscription::get_instance(), MavlinkOrbSubscription::get_topic(), instance, LL_APPEND, and LL_FOREACH.
Referenced by MavlinkStreamActuatorControlTarget< N >::MavlinkStreamActuatorControlTarget(), resend_message(), send_autopilot_capabilites(), and task_main().
void Mavlink::adjust_stream_rates (const float multiplier) private
Adjust the stream rates based on the current rate.
Parameters
multiplier if greater than 1, the transmission rate will increase, if smaller than one decrease
Definition at line 1444 of file mavlink_main.cpp.
References _streams, MavlinkStream::get_interval(), LL_FOREACH, MAVLINK_MAX_INTERVAL, MAVLINK_MIN_INTERVAL, MAVLINK_MIN_MULTIPLIER, and MavlinkStream::set_interval().
void Mavlink::begin_send ()
This is the beginning of a MAVLINK_START_UART_SEND/MAVLINK_END_UART_SEND transaction.
Definition at line 933 of file mavlink_main.cpp.
References _send_mutex, and pthread_mutex_lock().
Referenced by get_manual_input_mode_generation(), and mavlink_start_uart_send().
static bool Mavlink::boot_complete () inline static
Definition at line 458 of file mavlink_main.h.
References _boot_complete.
Referenced by MavlinkReceiver::receive_thread(), and MavlinkParametersManager::send_one().
bool Mavlink::broadcast_enabled () inline
Definition at line 242 of file mavlink_main.h.
References _broadcast_mode, BROADCAST_MODE_OFF, get_free_tx_buf(), set_boot_complete(), set_hil_enabled(), and start_helper().
Referenced by send_packet(), and set_boot_complete().
void Mavlink::check_radio_config () private
Check the configuration of a connected radio.
This convenience function allows to re-configure a connected radio without removing it from the main system harness.
Definition at line 2593 of file mavlink_main.cpp.
References _param_radio_id, _radio_id, _rstatus, _uart_fd, param_set_no_notification(), PX4_WARN, telemetry_status_s::type, and usleep().
Referenced by task_main().
void Mavlink::close_shell ()
close the Mavlink shell if it is open
Definition at line 1664 of file mavlink_main.cpp.
References _mavlink_shell.
Referenced by get_main_loop_delay(), and MavlinkReceiver::handle_message_serial_control().
int Mavlink::configure_stream (const char * stream_name, const float rate = -1.0f) private
Configure a single stream.
Parameters
stream_name
rate streaming rate in Hz, -1 = unlimited rate
Returns
0 on success, <0 on error
Definition at line 1396 of file mavlink_main.cpp.
References _streams, create_mavlink_stream(), MavlinkStream::get_name(), interval_from_rate(), LL_APPEND, LL_DELETE, LL_FOREACH, OK, PX4_DEBUG, PX4_ERROR, PX4_WARN, and MavlinkStream::set_interval().
Referenced by configure_streams_to_default(), set_hil_enabled(), and task_main().
void Mavlink::configure_stream_threadsafe (const char * stream_name, float rate = -1.0f)
Definition at line 1476 of file mavlink_main.cpp.
References _subscribe_to_stream, _subscribe_to_stream_rate, _task_should_exit, MAIN_LOOP_DELAY, and usleep().
Referenced by MavlinkReceiver::handle_message_command_both(), resend_message(), MavlinkReceiver::set_message_interval(), and stream_command().
int Mavlink::configure_streams_to_default (const char * configure_single_stream = nullptr) private
Configure default streams according to _mode for either all streams or only a single stream.
Parameters
configure_single_stream if nullptr, configure all streams, else only a single stream
Returns
0 on success, <0 on error
Definition at line 1757 of file mavlink_main.cpp.
References _mode, configure_stream(), f(), MAVLINK_MODE_CONFIG, MAVLINK_MODE_CUSTOM, MAVLINK_MODE_IRIDIUM, MAVLINK_MODE_MAGIC, MAVLINK_MODE_MINIMAL, MAVLINK_MODE_NORMAL, MAVLINK_MODE_ONBOARD, and MAVLINK_MODE_OSD.
Referenced by task_main().
void Mavlink::count_rxbytes (unsigned n) inline
Count received bytes.
Definition at line 424 of file mavlink_main.h.
References _bytes_rx.
Referenced by MavlinkReceiver::receive_thread().
void Mavlink::count_txbytes (unsigned n) inline
Count transmitted bytes.
Definition at line 414 of file mavlink_main.h.
References _bytes_tx.
Referenced by send_bytes().
void Mavlink::count_txerr ()
Count a transmission error.
Definition at line 370 of file mavlink_main.cpp.
References _txerr_perf, and perf_count().
Referenced by send_bytes(), and unlockMessageBufferMutex().
void Mavlink::count_txerrbytes (unsigned n) inline
Count bytes not transmitted because of errors.
Definition at line 419 of file mavlink_main.h.
References _bytes_txerr.
Referenced by send_bytes().
int Mavlink::destroy_all_instances () static
Definition at line 430 of file mavlink_main.cpp.
References _mavlink_instances, _task_running, _task_should_exit, LL_DELETE, next, OK, PX4_ERR, PX4_ERROR, PX4_INFO, and usleep().
Referenced by get_status(), and mavlink_main().
void Mavlink::display_status ()
Display the mavlink status.
Definition at line 2727 of file mavlink_main.cpp.
References _baudrate, _channel, _datarate, _device_name, _flow_control_mode, _ftp_on, _mavlink_ulog, _mode, _network_port, _ping_stats, _protocol, _protocol_version, _rate_mult, _rate_rx, _rate_tx, _rate_txerr, _remote_port, _rstatus, _transmitting_enabled, accepting_commands(), MavlinkULog::current_data_rate(), Mavlink::ping_statistics_s::dropped_packets, telemetry_status_s::fixed, get_client_source_initialized(), telemetry_status_s::heartbeat_time, hrt_elapsed_time(), Mavlink::ping_statistics_s::last_ping_time, Mavlink::ping_statistics_s::last_rtt, mavlink_mode_str(), Mavlink::ping_statistics_s::max_rtt, MavlinkULog::maximum_data_rate(), Mavlink::ping_statistics_s::mean_rtt, Mavlink::ping_statistics_s::min_rtt, telemetry_status_s::noise, telemetry_status_s::remote_noise, telemetry_status_s::remote_rssi, telemetry_status_s::rssi, telemetry_status_s::rxerrors, SERIAL, TCP, telemetry_status_s::timestamp, telemetry_status_s::txbuf, telemetry_status_s::type, and UDP.
Referenced by get_status_all_instances().
void Mavlink::display_status_streams ()
Display the status of all enabled streams.
Definition at line 2819 of file mavlink_main.cpp.
References _rate_mult, _streams, MavlinkStream::const_rate(), MavlinkStream::get_interval(), MavlinkStream::get_name(), MavlinkStream::get_size(), and LL_FOREACH.
Referenced by get_status_all_instances().
int Mavlink::enable_flow_control (enum FLOW_CONTROL_MODE enabled)
Enable / disable hardware flow control.
Parameters
enabled True if hardware flow control should be enabled
Definition at line 845 of file mavlink_main.cpp.
References _flow_control_mode, _is_usb_uart, _uart_fd, FLOW_CONTROL_OFF, and OK.
Referenced by get_free_tx_buf(), mavlink_open_uart(), and resend_message().
void Mavlink::find_broadcast_address () private
Definition at line 1057 of file mavlink_main.cpp.
References _interface_name, _remote_port, _socket_fd, PX4_DEBUG, PX4_ERR, PX4_INFO, and PX4_WARN.
Referenced by send_packet().
void Mavlink::forward_message (const mavlink_message_t * msg, Mavlink * self) static
Definition at line 519 of file mavlink_main.cpp.
References LL_FOREACH, and pass_message().
Referenced by get_status(), and handle_message().
bool Mavlink::ftp_enabled () const inline
Definition at line 491 of file mavlink_main.h.
References _ftp_on.
Referenced by MavlinkReceiver::receive_thread().
float Mavlink::get_baudrate () inline
Definition at line 392 of file mavlink_main.h.
References _baudrate.
Referenced by MavlinkReceiver::receive_thread().
mavlink_message_t* Mavlink::get_buffer () inline
Definition at line 129 of file mavlink_main.h.
References _mavlink_buffer.
Referenced by mavlink_get_channel_buffer().
mavlink_channel_t Mavlink::get_channel ()
Definition at line 578 of file mavlink_main.cpp.
References _channel.
Referenced by MavlinkFTP::_getServerChannel(), MavlinkLogHandler::_log_send_data(), MavlinkLogHandler::_log_send_listing(), MavlinkFTP::_process_request(), MavlinkFTP::_reply(), MavlinkReceiver::get_message_interval(), MavlinkParametersManager::handle_message(), MavlinkTimesync::handle_message(), MavlinkReceiver::handle_message_heartbeat(), MavlinkReceiver::handle_message_ping(), MavlinkReceiver::handle_message_radio_status(), MavlinkReceiver::receive_thread(), resend_message(), MavlinkStreamHighLatency2::send(), MavlinkStreamHeartbeat::send(), MavlinkStreamStatustext::send(), MavlinkStreamCommandLong::send(), MavlinkStreamSysStatus::send(), MavlinkStreamHighresIMU::send(), MavlinkStreamScaledIMU::send(), MavlinkStreamScaledIMU2::send(), MavlinkStreamScaledIMU3::send(), MavlinkStreamAttitude::send(), MavlinkStreamAttitudeQuaternion::send(), MavlinkStreamVFRHUD::send(), MavlinkStreamGPSRawInt::send(), MavlinkStreamSystemTime::send(), MavlinkStreamTimesync::send(), MavlinkStreamADSBVehicle::send(), MavlinkStreamCollision::send(), MavlinkStreamCameraTrigger::send(), MavlinkStreamCameraImageCaptured::send(), MavlinkStreamGlobalPositionInt::send(), MavlinkStreamVisionPositionEstimate::send(), MavlinkStreamLocalPositionNED::send(), MavlinkStreamLocalPositionNEDCOV::send(), MavlinkStreamEstimatorStatus::send(), MavlinkStreamAttPosMocap::send(), MavlinkStreamHomePosition::send(), MavlinkStreamServoOutputRaw< N >::send(), MavlinkStreamActuatorControlTarget< N >::send(), MavlinkStreamHILActuatorControls::send(), MavlinkStreamPositionTargetGlobalInt::send(), MavlinkStreamLocalPositionSetpoint::send(), MavlinkStreamAttitudeTarget::send(), MavlinkStreamRCChannels::send(), MavlinkStreamManualControl::send(), MavlinkStreamTrajectoryRepresentationWaypoints::send(), MavlinkStreamOpticalFlowRad::send(), MavlinkStreamNamedValueFloat::send(), MavlinkStreamDebug::send(), MavlinkStreamDebugVect::send(), MavlinkStreamNavControllerOutput::send(), MavlinkStreamCameraCapture::send(), MavlinkStreamDistanceSensor::send(), MavlinkStreamExtendedSysState::send(), MavlinkStreamAltitude::send(), MavlinkStreamWind::send(), MavlinkStreamMountOrientation::send(), MavlinkStreamGroundTruth::send(), MavlinkStreamPing::send(), send_autopilot_capabilites(), MavlinkReceiver::send_flight_information(), MavlinkMissionManager::send_mission_ack(), MavlinkMissionManager::send_mission_count(), MavlinkMissionManager::send_mission_current(), MavlinkMissionManager::send_mission_item(), MavlinkMissionManager::send_mission_item_reached(), MavlinkMissionManager::send_mission_request(), MavlinkParametersManager::send_one(), MavlinkParametersManager::send_param(), send_protocol_version(), MavlinkReceiver::send_storage_information(), MavlinkParametersManager::send_uavcan(), and task_main().
bool Mavlink::get_client_source_initialized () inline
Definition at line 453 of file mavlink_main.h.
Referenced by display_status(), get_socket_fd(), MavlinkReceiver::receive_thread(), and send_packet().
int Mavlink::get_component_id ()
Get the MAVLink component id.
Returns
The component ID of this vehicle
Definition at line 652 of file mavlink_main.cpp.
References mavlink_system.
Referenced by MavlinkFTP::_getServerComponentId(), and get_status().
bool Mavlink::get_config_link_on () inline
Definition at line 236 of file mavlink_main.h.
References _config_link_on.
Referenced by MavlinkReceiver::handle_message().
int Mavlink::get_data_rate () inline
Definition at line 464 of file mavlink_main.h.
References _datarate.
Referenced by MavlinkReceiver::handle_message_command_both().
bool Mavlink::get_flow_control_enabled () inline
Definition at line 232 of file mavlink_main.h.
References _flow_control_mode.
Referenced by update_rate_mult().
bool Mavlink::get_forward_externalsp () inline
Definition at line 230 of file mavlink_main.h.
References _forward_externalsp.
Referenced by MavlinkReceiver::handle_message_set_attitude_target(), and MavlinkReceiver::handle_message_set_position_target_local_ned().
bool Mavlink::get_forwarding_on () inline
Definition at line 234 of file mavlink_main.h.
References _forwarding_on.
Referenced by handle_message().
unsigned Mavlink::get_free_tx_buf ()
Get the free space in the transmit buffer.
Returns
free space in the UART TX buffer
Definition at line 895 of file mavlink_main.cpp.
References _flow_control_mode, _last_write_success_time, _last_write_try_time, _uart_fd, enable_flow_control(), FLOW_CONTROL_AUTO, FLOW_CONTROL_DISABLE_THRESHOLD, FLOW_CONTROL_OFF, get_protocol(), hrt_elapsed_time(), TCP, and UDP.
Referenced by broadcast_enabled(), MavlinkFTP::send(), MavlinkParametersManager::send(), MavlinkLogHandler::send(), send_bytes(), MavlinkParametersManager::send_param(), MavlinkParametersManager::send_untransmitted(), and task_main().
bool Mavlink::get_has_received_messages () inline
Definition at line 396 of file mavlink_main.h.
References _received_messages.
bool Mavlink::get_hil_enabled () inline
Definition at line 226 of file mavlink_main.h.
References _hil_enabled.
Referenced by MavlinkReceiver::handle_message().
Mavlink * Mavlink::get_instance (int instance) static
Definition at line 389 of file mavlink_main.cpp.
References get_instance_id(), and LL_FOREACH.
Referenced by get_uart_fd(), mavlink_end_uart_send(), mavlink_get_channel_buffer(), mavlink_get_channel_status(), mavlink_send_uart_bytes(), and mavlink_start_uart_send().
Mavlink * Mavlink::get_instance_for_device (const char * device_name) static
Definition at line 402 of file mavlink_main.cpp.
References _device_name, and LL_FOREACH.
Referenced by stream_command().
Mavlink * Mavlink::get_instance_for_network_port (unsigned long port) static
Definition at line 416 of file mavlink_main.cpp.
References _network_port, and LL_FOREACH.
Referenced by stream_command(), and task_main().
int Mavlink::get_instance_id ()
Definition at line 572 of file mavlink_main.cpp.
References _instance_id.
Referenced by get_instance(), MavlinkReceiver::handle_message_manual_control(), MavlinkReceiver::receive_thread(), and resend_message().
ringbuffer::RingBuffer* Mavlink::get_logbuffer () inline
Definition at line 431 of file mavlink_main.h.
References _logbuffer.
Referenced by MavlinkStreamStatustext::get_size(), and MavlinkStreamStatustext::send().
unsigned Mavlink::get_main_loop_delay () const inline
Definition at line 467 of file mavlink_main.h.
References _main_loop_delay, close_shell(), and get_shell().
Referenced by MavlinkStream::update().
bool Mavlink::get_manual_input_mode_generation () inline
Get the manual input generation mode.
Returns
true if manual inputs should generate RC data
Definition at line 291 of file mavlink_main.h.
References _generate_rc, begin_send(), send_bytes(), and send_packet().
Referenced by MavlinkReceiver::handle_message_manual_control().
orb_advert_t* Mavlink::get_mavlink_log_pub () inline
Definition at line 344 of file mavlink_main.h.
References _mavlink_log_pub, send_autopilot_capabilites(), send_protocol_version(), send_statustext(), send_statustext_critical(), send_statustext_emergency(), and send_statustext_info().
enum MAVLINK_MODE Mavlink::get_mode () inline
Definition at line 224 of file mavlink_main.h.
References _mode.
Referenced by MavlinkMissionManager::check_active_mission(), MavlinkReceiver::handle_message(), MavlinkReceiver::receive_thread(), MavlinkMissionManager::send(), and set_boot_complete().
unsigned short Mavlink::get_network_port () inline
Definition at line 437 of file mavlink_main.h.
References _network_port.
struct ping_statistics_s& Mavlink::get_ping_statistics () inline
Get the ping statistics of this MAVLink link.
Definition at line 506 of file mavlink_main.h.
References _ping_stats.
Referenced by MavlinkReceiver::handle_message_ping().
Protocol Mavlink::get_protocol () inline
Definition at line 435 of file mavlink_main.h.
References _protocol.
Referenced by get_free_tx_buf(), MavlinkReceiver::receive_thread(), MavlinkParametersManager::send(), send_bytes(), send_packet(), set_boot_complete(), and task_main().
float Mavlink::get_rate_mult ()
Definition at line 1635 of file mavlink_main.cpp.
References _rate_mult.
Referenced by get_streams(), and MavlinkStream::update().
unsigned short Mavlink::get_remote_port () inline
Definition at line 439 of file mavlink_main.h.
References _remote_port.
struct telemetry_status_s& Mavlink::get_rx_status () inline
Get the receive status of this MAVLink link.
Definition at line 429 of file mavlink_main.h.
References _rstatus.
Referenced by MavlinkReceiver::handle_message_heartbeat(), MavlinkReceiver::handle_message_radio_status(), MavlinkReceiver::receive_thread(), send_packet(), and update_rate_mult().
MavlinkShell * Mavlink::get_shell ()
get the Mavlink shell.
Create a new one if there isn't one. It is always created via MavlinkReceiver thread. Returns nullptr if shell cannot be created
Definition at line 1641 of file mavlink_main.cpp.
References _mavlink_shell, PX4_ERR, and MavlinkShell::start().
Referenced by get_main_loop_delay(), and MavlinkReceiver::handle_message_serial_control().
int Mavlink::get_socket_fd () inline
Definition at line 441 of file mavlink_main.h.
References _socket_fd, and get_client_source_initialized().
Referenced by MavlinkReceiver::receive_thread().
uint64_t Mavlink::get_start_time () inline
Definition at line 456 of file mavlink_main.h.
References _mavlink_start_time.
Referenced by MavlinkReceiver::receive_thread().
mavlink_status_t* Mavlink::get_status () inline
Definition at line 131 of file mavlink_main.h.
References _mavlink_status, destroy_all_instances(), forward_message(), get_component_id(), get_status_all_instances(), get_system_id(), get_uart_fd(), instance_exists(), msg, and set_proto_version().
Referenced by mavlink_get_channel_status(), MavlinkReceiver::receive_thread(), and set_proto_version().
int Mavlink::get_status_all_instances (bool show_streams_status) static
Definition at line 474 of file mavlink_main.cpp.
References _mavlink_instances, display_status(), display_status_streams(), and next.
Referenced by get_status(), and mavlink_main().
MavlinkStream* Mavlink::get_streams () const inline
Definition at line 388 of file mavlink_main.h.
References _streams, and get_rate_mult().
Referenced by MavlinkReceiver::get_message_interval().
int Mavlink::get_system_id ()
Get the MAVLink system id.
Returns
The system ID of this vehicle
Definition at line 647 of file mavlink_main.cpp.
References mavlink_system.
Referenced by MavlinkFTP::_getServerSystemId(), get_status(), MavlinkReceiver::handle_message_manual_control(), and MavlinkReceiver::handle_message_rc_channels_override().
unsigned Mavlink::get_system_type () inline
Definition at line 433 of file mavlink_main.h.
References _system_type.
Referenced by MavlinkStreamHighLatency2::send(), MavlinkStreamHeartbeat::send(), and MavlinkStreamHILActuatorControls::send().
int Mavlink::get_uart_fd (unsigned index) static
Definition at line 554 of file mavlink_main.cpp.
References get_instance(), and get_uart_fd().
Referenced by get_uart_fd(), and MavlinkReceiver::receive_thread().
int Mavlink::get_uart_fd ()
Definition at line 566 of file mavlink_main.cpp.
References _uart_fd.
Referenced by get_status().
MavlinkULog* Mavlink::get_ulog_streaming () inline
get ulog streaming if active, nullptr otherwise
Definition at line 476 of file mavlink_main.h.
References _mavlink_ulog.
Referenced by MavlinkReceiver::handle_message_logging_ack().
bool Mavlink::get_use_hil_gps () inline
Definition at line 228 of file mavlink_main.h.
References _use_hil_gps.
Referenced by MavlinkReceiver::handle_message().
bool Mavlink::get_wait_to_transmit () inline
Definition at line 398 of file mavlink_main.h.
References _wait_to_transmit.
void Mavlink::handle_message (const mavlink_message_t * msg)
Definition at line 1248 of file mavlink_main.cpp.
References accepting_commands(), forward_message(), and get_forwarding_on().
Referenced by MavlinkReceiver::receive_thread(), and resend_message().
void Mavlink::init_udp () private
Definition at line 1216 of file mavlink_main.cpp.
References _network_port, _remote_port, _socket_fd, PX4_DEBUG, and PX4_WARN.
Referenced by task_main().
int Mavlink::instance_count () static
Definition at line 376 of file mavlink_main.cpp.
References LL_FOREACH.
Referenced by Mavlink(), and start().
bool Mavlink::instance_exists (const char * device_name, Mavlink * self) static
Definition at line 501 of file mavlink_main.cpp.
References _device_name, _mavlink_instances, and next.
Referenced by get_status(), and task_main().
int Mavlink::interval_from_rate (float rate) static private
Definition at line 1382 of file mavlink_main.cpp.
References f().
Referenced by configure_stream().
bool Mavlink::is_connected () inline
Definition at line 240 of file mavlink_main.h.
References _rstatus, telemetry_status_s::heartbeat_time, and hrt_absolute_time().
Referenced by MavlinkStreamStatustext::send().
bool Mavlink::is_usb_uart () inline
Definition at line 460 of file mavlink_main.h.
References _is_usb_uart.
Referenced by MavlinkParametersManager::send().
void Mavlink::lockMessageBufferMutex (void) inline
Definition at line 403 of file mavlink_main.h.
References _message_buffer_mutex, and pthread_mutex_lock().
static const char* Mavlink::mavlink_mode_str (enum MAVLINK_MODE mode) inline static
Definition at line 192 of file mavlink_main.h.
References MAVLINK_MODE_CONFIG, MAVLINK_MODE_CUSTOM, MAVLINK_MODE_IRIDIUM, MAVLINK_MODE_MAGIC, MAVLINK_MODE_MINIMAL, MAVLINK_MODE_NORMAL, MAVLINK_MODE_ONBOARD, and MAVLINK_MODE_OSD.
Referenced by display_status(), and task_main().
int Mavlink::mavlink_open_uart (int baudrate, const char * uart_name, bool force_flow_control) private
Definition at line 657 of file mavlink_main.cpp.
References _baudrate, _is_usb_uart, _mode, _rstatus, _uart_fd, actuator_armed_s::armed, B1000000, B460800, B500000, B921600, enable_flow_control(), FLOW_CONTROL_AUTO, FLOW_CONTROL_ON, hrt_absolute_time(), MAVLINK_MODE_CONFIG, OK, orb_check(), orb_copy(), ORB_ID, orb_subscribe(), orb_unsubscribe(), PX4_ERR, PX4_WARN, telemetry_status_s::type, and usleep().
Referenced by task_main().
void Mavlink::mavlink_update_system () private
Definition at line 583 of file mavlink_main.cpp.
References _broadcast_mode, _forward_externalsp, _param_broadcast, _param_component_id, _param_forward_externalsp, _param_initialized, _param_proto_ver, _param_radio_id, _param_system_id, _param_system_type, _param_use_hil_gps, _protocol_version_switch, _radio_id, _system_type, _use_hil_gps, mavlink_system, param_find(), param_get(), set_proto_version(), and system_id.
Referenced by task_main().
int Mavlink::message_buffer_count () private
Definition at line 1537 of file mavlink_main.cpp.
References _message_buffer, Mavlink::mavlink_message_buffer::read_ptr, Mavlink::mavlink_message_buffer::size, and Mavlink::mavlink_message_buffer::write_ptr.
void Mavlink::message_buffer_destroy () private
Definition at line 1528 of file mavlink_main.cpp.
References _message_buffer, Mavlink::mavlink_message_buffer::data, Mavlink::mavlink_message_buffer::read_ptr, Mavlink::mavlink_message_buffer::size, and Mavlink::mavlink_message_buffer::write_ptr.
Referenced by task_main().
int Mavlink::message_buffer_get_ptr (void ** ptr, bool * is_part) private
Definition at line 1590 of file mavlink_main.cpp.
References _message_buffer, Mavlink::mavlink_message_buffer::data, Mavlink::mavlink_message_buffer::read_ptr, Mavlink::mavlink_message_buffer::size, and Mavlink::mavlink_message_buffer::write_ptr.
Referenced by task_main().
int Mavlink::message_buffer_init (int size) private
Definition at line 1506 of file mavlink_main.cpp.
References _message_buffer, Mavlink::mavlink_message_buffer::data, OK, PX4_ERROR, Mavlink::mavlink_message_buffer::read_ptr, Mavlink::mavlink_message_buffer::size, and Mavlink::mavlink_message_buffer::write_ptr.
Referenced by task_main().
int Mavlink::message_buffer_is_empty () private
Definition at line 1549 of file mavlink_main.cpp.
References _message_buffer, Mavlink::mavlink_message_buffer::read_ptr, and Mavlink::mavlink_message_buffer::write_ptr.
void Mavlink::message_buffer_mark_read (int n) private
Definition at line 1617 of file mavlink_main.cpp.
References _message_buffer, Mavlink::mavlink_message_buffer::read_ptr, and Mavlink::mavlink_message_buffer::size.
Referenced by task_main().
bool Mavlink::message_buffer_write (const void * ptr, int size)
Definition at line 1556 of file mavlink_main.cpp.
References _message_buffer, Mavlink::mavlink_message_buffer::data, Mavlink::mavlink_message_buffer::read_ptr, Mavlink::mavlink_message_buffer::size, and Mavlink::mavlink_message_buffer::write_ptr.
Referenced by pass_message(), and should_transmit().
static Mavlink* Mavlink::new_instance () static
Mavlink Mavlink::operator= (const Mavlink &) private
void Mavlink::pass_message (const mavlink_message_t * msg) private
Definition at line 1623 of file mavlink_main.cpp.
References _forwarding_on, _message_buffer_mutex, message_buffer_write(), pthread_mutex_lock(), and pthread_mutex_unlock().
Referenced by forward_message().
void Mavlink::request_stop_ulog_streaming () inline
Definition at line 483 of file mavlink_main.h.
References _mavlink_ulog, _mavlink_ulog_stop_requested, fd, and set_uorb_main_fd().
Referenced by MavlinkReceiver::handle_message_command_both().
void Mavlink::resend_message (mavlink_message_t * msg) inline
Resend message as is, don't change sequence number and CRC.
Definition at line 316 of file mavlink_main.h.
References _channel, add_orb_subscription(), configure_stream_threadsafe(), enable_flow_control(), f(), get_channel(), get_instance_id(), and handle_message().
Referenced by task_main().
void Mavlink::send_autopilot_capabilites ()
Send the capabilities of this autopilot in terms of the MAVLink spec.
Definition at line 1283 of file mavlink_main.cpp.
References add_orb_subscription(), board_get_uuid32(), CONFIG_CDCACM_PRODUCTID, get_channel(), mavlink_system, msg, ORB_ID, px4_board_version(), px4_firmware_version(), px4_firmware_version_binary(), px4_os_version(), and px4_os_version_binary().
Referenced by get_mavlink_log_pub(), MavlinkReceiver::handle_message_command_both(), and task_main().
void Mavlink::send_bytes (const uint8_t * buf, unsigned packet_len)
Send bytes out on the link.
On a network port these might actually get buffered to form a packet.
Definition at line 1000 of file mavlink_main.cpp.
References _last_write_success_time, _last_write_try_time, _mavlink_start_time, _uart_fd, count_txbytes(), count_txerr(), count_txerrbytes(), get_free_tx_buf(), get_protocol(), hrt_absolute_time(), SERIAL, should_transmit(), and write().
Referenced by get_manual_input_mode_generation(), and mavlink_send_uart_bytes().
int Mavlink::send_packet ()
Flush the transmit buffer and send one MAVLink packet.
Returns
the number of bytes sent or -1 in case of error
Definition at line 941 of file mavlink_main.cpp.
References _mode, _send_mutex, _socket_fd, broadcast_enabled(), find_broadcast_address(), get_client_source_initialized(), get_protocol(), get_rx_status(), telemetry_status_s::heartbeat_time, hrt_elapsed_time(), MAVLINK_MODE_ONBOARD, pthread_mutex_unlock(), PX4_ERR, TCP, and UDP.
Referenced by get_manual_input_mode_generation(), and mavlink_end_uart_send().
void Mavlink::send_protocol_version ()
Send the protocol version of MAVLink.
Definition at line 1338 of file mavlink_main.cpp.
References _protocol_version, get_channel(), msg, px4_mavlink_lib_version_binary(), and set_proto_version().
Referenced by get_mavlink_log_pub(), and MavlinkReceiver::handle_message_command_both().
void Mavlink::send_statustext (unsigned char severity, const char * string)
Send a status text with loglevel, the difference from mavlink_log_xxx() is that message sent only on this mavlink connection.
Useful for reporting communication specific, not system-wide info only to client interested in it. Message will be not sent immediately but queued in buffer as for mavlink_log_xxx().
Parameters
string the message to send (will be capped by mavlink max string length)
severity the log level
Referenced by get_mavlink_log_pub().
void Mavlink::send_statustext_critical (const char * string)
Send a status text with loglevel CRITICAL.
Parameters
string the message to send (will be capped by mavlink max string length)
Definition at line 1271 of file mavlink_main.cpp.
References _mavlink_log_pub, mavlink_log_critical, and PX4_ERR.
Referenced by MavlinkFTP::_workList(), get_mavlink_log_pub(), MavlinkReceiver::handle_message_command_both(), MavlinkMissionManager::handle_mission_ack(), MavlinkMissionManager::handle_mission_clear_all(), MavlinkMissionManager::handle_mission_count(), MavlinkMissionManager::handle_mission_item_both(), MavlinkMissionManager::handle_mission_request_both(), MavlinkMissionManager::handle_mission_request_list(), MavlinkMissionManager::handle_mission_set_current(), MavlinkMissionManager::send(), MavlinkMissionManager::send_mission_current(), MavlinkMissionManager::send_mission_item(), MavlinkMissionManager::send_mission_request(), MavlinkParametersManager::send_one(), MavlinkMissionManager::update_active_mission(), MavlinkMissionManager::update_geofence_count(), and MavlinkMissionManager::update_safepoint_count().
void Mavlink::send_statustext_emergency (const char * string)
Send a status text with loglevel EMERGENCY.
Parameters
string the message to send (will be capped by mavlink max string length)
Definition at line 1278 of file mavlink_main.cpp.
References _mavlink_log_pub, and mavlink_log_emergency.
Referenced by get_mavlink_log_pub().
void Mavlink::send_statustext_info (const char * string)
Send a status text with loglevel INFO.
Parameters
string the message to send (will be capped by mavlink max string length)
Definition at line 1265 of file mavlink_main.cpp.
References _mavlink_log_pub, and mavlink_log_info.
Referenced by get_mavlink_log_pub(), and MavlinkParametersManager::handle_message().
void Mavlink::set_boot_complete () static
Set the boot complete flag on all instances.
Setting the flag unblocks parameter transmissions, which are gated beforehand to ensure that the system is fully initialized.
Definition at line 2963 of file mavlink_main.cpp.
References _boot_complete, broadcast_enabled(), get_mode(), get_protocol(), LL_FOREACH, MAVLINK_MODE_ONBOARD, PX4_INFO, TCP, and UDP.
Referenced by broadcast_enabled(), mavlink_main(), and MavlinkParametersManager::send_one().
void Mavlink::set_config_link_on (bool on) inline
Definition at line 238 of file mavlink_main.h.
References _config_link_on.
Referenced by MavlinkReceiver::handle_message().
void Mavlink::set_data_rate (int rate) inline
Definition at line 465 of file mavlink_main.h.
References _datarate.
Referenced by MavlinkReceiver::set_message_interval().
void Mavlink::set_has_received_messages (bool received_messages) inline
Definition at line 395 of file mavlink_main.h.
References _received_messages.
Referenced by MavlinkReceiver::handle_message().
int Mavlink::set_hil_enabled (bool hil_enabled)
Enable / disable Hardware in the Loop simulation mode.
Parameters
hil_enabled The new HIL enable/disable state.
Returns
OK if the HIL state changed, ERROR if the requested change could not be made or was redundant.
Definition at line 875 of file mavlink_main.cpp.
References _datarate, _hil_enabled, configure_stream(), f(), and OK.
Referenced by broadcast_enabled(), and task_main().
void Mavlink::set_manual_input_mode_generation (bool generation_enabled) inline
Set manual input generation mode.
Set to true to generate RC_INPUT messages on the system bus from MAVLink messages.
Parameters
generation_enabled If set to true, generate RC_INPUT messages
Definition at line 279 of file mavlink_main.h.
References _generate_rc.
Referenced by task_main().
void Mavlink::set_proto_version (unsigned version)
Set the MAVLink version.
Currently supporting v1 and v2
Parameters
version MAVLink version
Definition at line 355 of file mavlink_main.cpp.
References _protocol_version, _protocol_version_switch, and get_status().
Referenced by get_status(), mavlink_update_system(), MavlinkReceiver::receive_thread(), and send_protocol_version().
void Mavlink::set_protocol (Protocol p) inline
Set communication protocol for this mavlink instance.
Definition at line 284 of file mavlink_main.h.
References _protocol.
Referenced by task_main().
void Mavlink::set_uorb_main_fd (int fd, unsigned int interval)
Referenced by request_stop_ulog_streaming().
void Mavlink::set_wait_to_transmit (bool wait) inline
Definition at line 397 of file mavlink_main.h.
References _wait_to_transmit.
bool Mavlink::should_transmit () inline
Definition at line 399 of file mavlink_main.h.
References _boot_complete, _received_messages, _transmitting_enabled, _wait_to_transmit, and message_buffer_write().
Referenced by MavlinkStreamHighLatency2::send(), and send_bytes().
int Mavlink::start (int argc, char * argv[]) static
Start the mavlink task.
Returns
OK on success.
Definition at line 2668 of file mavlink_main.cpp.
References MavlinkCommandSender::initialize(), MavlinkULog::initialize(), instance_count(), MAVLINK_MAX_INSTANCES, PX4_ERR, PX4_ERROR, PX4_OK, px4_task_spawn_cmd(), SCHED_DEFAULT, start_helper(), and usleep().
Referenced by mavlink_main().
int Mavlink::start_helper (int argc, char * argv[]) static
Definition at line 2644 of file mavlink_main.cpp.
References _task_running, instance, Mavlink(), PX4_ERR, and task_main().
Referenced by broadcast_enabled(), and start().
int Mavlink::stream_command (int argc, char * argv[]) static
Definition at line 2853 of file mavlink_main.cpp.
References configure_stream_threadsafe(), DEFAULT_DEVICE_NAME, device_name, f(), get_instance_for_device(), get_instance_for_network_port(), OK, PX4_WARN, and usage().
Referenced by mavlink_main().
int Mavlink::task_main (int argc, char * argv[]) private
Main mavlink task.
Definition at line 1942 of file mavlink_main.cpp.
References _baudrate, _bytes_rx, _bytes_timestamp, _bytes_tx, _bytes_txerr, _channel, _datarate, _device_name, _first_heartbeat_sent, _forwarding_on, _ftp_on, _interface_name, _is_usb_uart, _logbuffer, _loop_perf, _main_loop_delay, _mavlink_log_pub, _mavlink_shell, _mavlink_ulog, _mavlink_ulog_stop_requested, _message_buffer_mutex, _mode, _network_port, _rate_rx, _rate_tx, _rate_txerr, _receive_thread, _remote_port, _rstatus, _send_mutex, _socket_fd, _streams, _subscribe_to_stream, _subscribe_to_stream_rate, _subscriptions, _task_running, _task_should_exit, _transmitting_enabled, _transmitting_enabled_commanded, _uart_fd, _wait_to_transmit, add_orb_subscription(), MavlinkShell::available(), check_radio_config(), vehicle_command_ack_s::command, vehicle_command_s::command, configure_stream(), configure_streams_to_default(), dt, f(), MavlinkStream::first_message_sent(), vehicle_command_ack_s::from_external, vehicle_command_s::from_external, get_channel(), get_free_tx_buf(), MavlinkStream::get_id(), get_instance_for_network_port(), get_protocol(), MavlinkULog::handle_update(), vehicle_status_s::high_latency_data_link_active, vehicle_status_s::hil_state, hrt_absolute_time(), hrt_abstime, init_udp(), instance_exists(), LL_APPEND, LL_FOREACH, MAIN_LOOP_DELAY, mavlink_and_console_log_info, MAVLINK_MAX_INTERVAL, MAVLINK_MIN_INTERVAL, MAVLINK_MODE_CONFIG, MAVLINK_MODE_CUSTOM, MAVLINK_MODE_IRIDIUM, MAVLINK_MODE_MAGIC, MAVLINK_MODE_MINIMAL, MAVLINK_MODE_NORMAL, MAVLINK_MODE_ONBOARD, MAVLINK_MODE_OSD, mavlink_mode_str(), mavlink_open_uart(), mavlink_update_system(), MAX_DATA_RATE, message_buffer_destroy(), message_buffer_get_ptr(), message_buffer_init(), message_buffer_mark_read(), msg, MavlinkOrbSubscription::next, MavlinkStream::next, OK, orb_advert_t, orb_advertise_queue(), ORB_ID, orb_publish(), vehicle_command_s::param1, perf_begin(), perf_end(), pthread_join(), pthread_mutex_destroy(), pthread_mutex_init(), pthread_mutex_lock(), pthread_mutex_unlock(), PX4_DEBUG, PX4_ERR, PX4_ERROR, px4_getopt(), PX4_INFO, PX4_WARN, vehicle_status_s::rc_input_mode, MavlinkShell::read(), MavlinkReceiver::receive_start(), resend_message(), vehicle_command_ack_s::result, vehicle_command_ack_s::result_param1, vehicle_command_ack_s::result_param2, send_autopilot_capabilites(), SERIAL, set_hil_enabled(), set_manual_input_mode_generation(), set_protocol(), vehicle_command_s::source_component, vehicle_command_s::source_system, MavlinkULog::start_ack_received(), MavlinkULog::stop(), MavlinkOrbSubscription::subscribe_from_beginning(), vehicle_command_ack_s::target_component, vehicle_command_ack_s::target_system, vehicle_command_ack_s::timestamp, vehicle_command_s::timestamp, telemetry_status_s::type, UDP, MavlinkOrbSubscription::update(), MavlinkStream::update(), MavlinkOrbSubscription::update_if_changed(), update_rate_mult(), usage(), and usleep().
Referenced by start_helper().
void Mavlink::try_start_ulog_streaming (uint8_t target_system, uint8_t target_component) inline
Definition at line 477 of file mavlink_main.h.
References _datarate, _mavlink_ulog, f(), and MavlinkULog::try_start().
Referenced by MavlinkReceiver::handle_message_command_both().
void Mavlink::unlockMessageBufferMutex (void) inline
Definition at line 404 of file mavlink_main.h.
References _message_buffer_mutex, count_txerr(), and pthread_mutex_unlock().
void Mavlink::update_rate_mult () private
Update rate mult so total bitrate will be equal to _datarate.
Definition at line 1673 of file mavlink_main.cpp.
References _datarate, _last_hw_rate_timestamp, _mavlink_ulog, _rate_mult, _rate_tx, _rate_txerr, _streams, MavlinkStream::const_rate(), MavlinkULog::current_data_rate(), f(), get_flow_control_enabled(), MavlinkStream::get_interval(), get_rx_status(), MavlinkStream::get_size_avg(), LL_FOREACH, RADIO_BUFFER_CRITICAL_LOW_PERCENTAGE, RADIO_BUFFER_HALF_PERCENTAGE, RADIO_BUFFER_LOW_PERCENTAGE, telemetry_status_s::telem_time, telemetry_status_s::txbuf, and telemetry_status_s::type.
Referenced by task_main().
Member Data Documentation
int Mavlink::_baudrate private
Definition at line 559 of file mavlink_main.h.
Referenced by display_status(), get_baudrate(), Mavlink(), mavlink_open_uart(), and task_main().
bool Mavlink::_boot_complete = false static private
Definition at line 519 of file mavlink_main.h.
Referenced by boot_complete(), mavlink_get_channel_buffer(), set_boot_complete(), and should_transmit().
int32_t Mavlink::_broadcast_mode private
Definition at line 629 of file mavlink_main.h.
Referenced by broadcast_enabled(), Mavlink(), and mavlink_update_system().
unsigned Mavlink::_bytes_rx private
Definition at line 587 of file mavlink_main.h.
Referenced by count_rxbytes(), Mavlink(), and task_main().
uint64_t Mavlink::_bytes_timestamp private
Definition at line 588 of file mavlink_main.h.
Referenced by Mavlink(), and task_main().
unsigned Mavlink::_bytes_tx private
Definition at line 585 of file mavlink_main.h.
Referenced by count_txbytes(), Mavlink(), and task_main().
unsigned Mavlink::_bytes_txerr private
Definition at line 586 of file mavlink_main.h.
Referenced by count_txerrbytes(), Mavlink(), and task_main().
mavlink_channel_t Mavlink::_channel private
Definition at line 547 of file mavlink_main.h.
Referenced by display_status(), get_channel(), Mavlink(), resend_message(), and task_main().
bool Mavlink::_config_link_on = false static private
Definition at line 641 of file mavlink_main.h.
Referenced by get_config_link_on(), mavlink_get_channel_buffer(), and set_config_link_on().
int Mavlink::_datarate private
data rate for normal streams (attitude, position, etc.)
Definition at line 560 of file mavlink_main.h.
Referenced by display_status(), get_data_rate(), Mavlink(), set_data_rate(), set_hil_enabled(), task_main(), try_start_ulog_streaming(), and update_rate_mult().
int Mavlink::_datarate_events private
data rate for params, waypoints, text messages
Definition at line 561 of file mavlink_main.h.
Referenced by Mavlink().
const char* Mavlink::_device_name
Definition at line 168 of file mavlink_main.h.
Referenced by display_status(), get_instance_for_device(), instance_exists(), and task_main().
bool Mavlink::_first_heartbeat_sent {false} private
Definition at line 515 of file mavlink_main.h.
Referenced by task_main().
enum FLOW_CONTROL_MODE Mavlink::_flow_control_mode private
Definition at line 578 of file mavlink_main.h.
Referenced by display_status(), enable_flow_control(), get_flow_control_enabled(), get_free_tx_buf(), and Mavlink().
bool Mavlink::_forward_externalsp private
Forward external setpoint messages to controllers directly if in offboard mode.
Definition at line 531 of file mavlink_main.h.
Referenced by get_forward_externalsp(), Mavlink(), and mavlink_update_system().
bool Mavlink::_forwarding_on private
Definition at line 554 of file mavlink_main.h.
Referenced by get_forwarding_on(), Mavlink(), pass_message(), and task_main().
bool Mavlink::_ftp_on private
Definition at line 555 of file mavlink_main.h.
Referenced by display_status(), ftp_enabled(), Mavlink(), and task_main().
bool Mavlink::_generate_rc private
Generate RC messages from manual input MAVLink messages.
Definition at line 529 of file mavlink_main.h.
Referenced by get_manual_input_mode_generation(), Mavlink(), and set_manual_input_mode_generation().
bool Mavlink::_hil_enabled private
Hardware In the Loop mode.
Definition at line 528 of file mavlink_main.h.
Referenced by get_hil_enabled(), Mavlink(), and set_hil_enabled().
int Mavlink::_instance_id private
Definition at line 512 of file mavlink_main.h.
Referenced by get_instance_id(), and Mavlink().
const char* Mavlink::_interface_name private
Definition at line 605 of file mavlink_main.h.
Referenced by find_broadcast_address(), and task_main().
bool Mavlink::_is_usb_uart private
Port is USB.
Definition at line 532 of file mavlink_main.h.
Referenced by enable_flow_control(), is_usb_uart(), Mavlink(), mavlink_open_uart(), and task_main().
hrt_abstime Mavlink::_last_hw_rate_timestamp private
Definition at line 563 of file mavlink_main.h.
Referenced by Mavlink(), and update_rate_mult().
uint64_t Mavlink::_last_write_success_time private
Definition at line 579 of file mavlink_main.h.
Referenced by get_free_tx_buf(), Mavlink(), and send_bytes().
uint64_t Mavlink::_last_write_try_time private
Definition at line 580 of file mavlink_main.h.
Referenced by get_free_tx_buf(), Mavlink(), and send_bytes().
ringbuffer::RingBuffer Mavlink::_logbuffer private
Definition at line 550 of file mavlink_main.h.
Referenced by get_logbuffer(), Mavlink(), and task_main().
perf_counter_t Mavlink::_loop_perf private
loop performance counter
Definition at line 643 of file mavlink_main.h.
Referenced by Mavlink(), task_main(), and ~Mavlink().
unsigned Mavlink::_main_loop_delay private
mainloop delay, depends on data rate
Definition at line 536 of file mavlink_main.h.
Referenced by get_main_loop_delay(), Mavlink(), and task_main().
mavlink_message_t Mavlink::_mavlink_buffer private
Definition at line 524 of file mavlink_main.h.
Referenced by get_buffer().
orb_advert_t Mavlink::_mavlink_log_pub private
Definition at line 517 of file mavlink_main.h.
Referenced by get_mavlink_log_pub(), send_statustext_critical(), send_statustext_emergency(), send_statustext_info(), and task_main().
unsigned int Mavlink::_mavlink_param_queue_index private
If the queue index is not at 0, the queue sending logic will send parameters from the current index to len - 1, the end of the param list.
Definition at line 570 of file mavlink_main.h.
Referenced by Mavlink().
MavlinkShell* Mavlink::_mavlink_shell private
Definition at line 541 of file mavlink_main.h.
Referenced by close_shell(), get_shell(), Mavlink(), and task_main().
uint64_t Mavlink::_mavlink_start_time private
Definition at line 581 of file mavlink_main.h.
Referenced by get_start_time(), Mavlink(), and send_bytes().
mavlink_status_t Mavlink::_mavlink_status private
Definition at line 525 of file mavlink_main.h.
Referenced by get_status(), and Mavlink().
MavlinkULog* Mavlink::_mavlink_ulog private
Definition at line 542 of file mavlink_main.h.
Referenced by display_status(), get_ulog_streaming(), Mavlink(), request_stop_ulog_streaming(), task_main(), try_start_ulog_streaming(), and update_rate_mult().
volatile bool Mavlink::_mavlink_ulog_stop_requested private
Definition at line 543 of file mavlink_main.h.
Referenced by Mavlink(), request_stop_ulog_streaming(), and task_main().
mavlink_message_buffer Mavlink::_message_buffer private
Definition at line 623 of file mavlink_main.h.
Referenced by Mavlink(), message_buffer_count(), message_buffer_destroy(), message_buffer_get_ptr(), message_buffer_init(), message_buffer_is_empty(), message_buffer_mark_read(), and message_buffer_write().
pthread_mutex_t Mavlink::_message_buffer_mutex private
Definition at line 625 of file mavlink_main.h.
Referenced by lockMessageBufferMutex(), Mavlink(), pass_message(), task_main(), and unlockMessageBufferMutex().
MAVLINK_MODE Mavlink::_mode private
Definition at line 545 of file mavlink_main.h.
Referenced by configure_streams_to_default(), display_status(), get_mode(), Mavlink(), mavlink_open_uart(), send_packet(), and task_main().
unsigned short Mavlink::_network_port private
Definition at line 609 of file mavlink_main.h.
Referenced by display_status(), get_instance_for_network_port(), get_network_port(), init_udp(), Mavlink(), and task_main().
param_t Mavlink::_param_broadcast private
Definition at line 638 of file mavlink_main.h.
Referenced by Mavlink(), and mavlink_update_system().
param_t Mavlink::_param_component_id private
Definition at line 632 of file mavlink_main.h.
Referenced by Mavlink(), and mavlink_update_system().
param_t Mavlink::_param_forward_externalsp private
Definition at line 637 of file mavlink_main.h.
Referenced by Mavlink(), and mavlink_update_system().
bool Mavlink::_param_initialized private
Definition at line 628 of file mavlink_main.h.
Referenced by Mavlink(), and mavlink_update_system().
param_t Mavlink::_param_proto_ver private
Definition at line 633 of file mavlink_main.h.
Referenced by mavlink_update_system().
param_t Mavlink::_param_radio_id private
Definition at line 634 of file mavlink_main.h.
Referenced by check_radio_config(), Mavlink(), and mavlink_update_system().
param_t Mavlink::_param_system_id private
Definition at line 631 of file mavlink_main.h.
Referenced by Mavlink(), and mavlink_update_system().
param_t Mavlink::_param_system_type private
Definition at line 635 of file mavlink_main.h.
Referenced by Mavlink(), and mavlink_update_system().
param_t Mavlink::_param_use_hil_gps private
Definition at line 636 of file mavlink_main.h.
Referenced by Mavlink(), and mavlink_update_system().
struct ping_statistics_s Mavlink::_ping_stats private
ping statistics
Definition at line 614 of file mavlink_main.h.
Referenced by display_status(), get_ping_statistics(), and Mavlink().
Protocol Mavlink::_protocol private
Definition at line 608 of file mavlink_main.h.
Referenced by display_status(), get_protocol(), Mavlink(), and set_protocol().
int32_t Mavlink::_protocol_version private
Definition at line 583 of file mavlink_main.h.
Referenced by display_status(), Mavlink(), send_protocol_version(), and set_proto_version().
int32_t Mavlink::_protocol_version_switch private
Definition at line 582 of file mavlink_main.h.
Referenced by Mavlink(), mavlink_update_system(), and set_proto_version().
int32_t Mavlink::_radio_id private
Definition at line 548 of file mavlink_main.h.
Referenced by check_radio_config(), Mavlink(), and mavlink_update_system().
float Mavlink::_rate_mult private
Definition at line 562 of file mavlink_main.h.
Referenced by display_status(), display_status_streams(), get_rate_mult(), Mavlink(), and update_rate_mult().
float Mavlink::_rate_rx private
Definition at line 591 of file mavlink_main.h.
Referenced by display_status(), Mavlink(), and task_main().
float Mavlink::_rate_tx private
Definition at line 589 of file mavlink_main.h.
Referenced by display_status(), Mavlink(), task_main(), and update_rate_mult().
float Mavlink::_rate_txerr private
Definition at line 590 of file mavlink_main.h.
Referenced by display_status(), Mavlink(), task_main(), and update_rate_mult().
pthread_t Mavlink::_receive_thread private
Definition at line 552 of file mavlink_main.h.
Referenced by Mavlink(), and task_main().
bool Mavlink::_received_messages private
Whether we've received valid mavlink messages.
Definition at line 534 of file mavlink_main.h.
Referenced by get_has_received_messages(), Mavlink(), set_has_received_messages(), and should_transmit().
unsigned short Mavlink::_remote_port private
Definition at line 610 of file mavlink_main.h.
Referenced by display_status(), find_broadcast_address(), get_remote_port(), init_udp(), Mavlink(), and task_main().
struct telemetry_status_s Mavlink::_rstatus private
receive status
Definition at line 612 of file mavlink_main.h.
Referenced by check_radio_config(), display_status(), get_rx_status(), is_connected(), Mavlink(), mavlink_open_uart(), and task_main().
pthread_mutex_t Mavlink::_send_mutex private
Definition at line 626 of file mavlink_main.h.
Referenced by begin_send(), Mavlink(), send_packet(), and task_main().
int Mavlink::_socket_fd private
Definition at line 607 of file mavlink_main.h.
Referenced by find_broadcast_address(), get_socket_fd(), init_udp(), Mavlink(), send_packet(), and task_main().
MavlinkStream* Mavlink::_streams private
Definition at line 539 of file mavlink_main.h.
Referenced by adjust_stream_rates(), configure_stream(), display_status_streams(), get_streams(), Mavlink(), task_main(), and update_rate_mult().
char* Mavlink::_subscribe_to_stream private
Definition at line 574 of file mavlink_main.h.
Referenced by configure_stream_threadsafe(), Mavlink(), and task_main().
float Mavlink::_subscribe_to_stream_rate private
rate of stream to subscribe to (0=disable, -1=unlimited, -2=default)
Definition at line 575 of file mavlink_main.h.
Referenced by configure_stream_threadsafe(), Mavlink(), and task_main().
MavlinkOrbSubscription* Mavlink::_subscriptions private
Definition at line 538 of file mavlink_main.h.
Referenced by add_orb_subscription(), Mavlink(), and task_main().
unsigned Mavlink::_system_type private
Definition at line 640 of file mavlink_main.h.
Referenced by get_system_type(), Mavlink(), and mavlink_update_system().
bool Mavlink::_task_running private
Definition at line 518 of file mavlink_main.h.
Referenced by destroy_all_instances(), start_helper(), task_main(), and ~Mavlink().
bool Mavlink::_task_should_exit
if true, mavlink task should exit
Definition at line 342 of file mavlink_main.h.
Referenced by configure_stream_threadsafe(), destroy_all_instances(), MavlinkReceiver::receive_thread(), task_main(), and ~Mavlink().
bool Mavlink::_transmitting_enabled private
Definition at line 513 of file mavlink_main.h.
Referenced by display_status(), should_transmit(), and task_main().
bool Mavlink::_transmitting_enabled_commanded private
Definition at line 514 of file mavlink_main.h.
Referenced by task_main().
perf_counter_t Mavlink::_txerr_perf private
TX error counter.
Definition at line 644 of file mavlink_main.h.
Referenced by count_txerr(), Mavlink(), and ~Mavlink().
int Mavlink::_uart_fd private
Definition at line 557 of file mavlink_main.h.
Referenced by check_radio_config(), enable_flow_control(), get_free_tx_buf(), get_uart_fd(), Mavlink(), mavlink_open_uart(), send_bytes(), and task_main().
bool Mavlink::_udp_initialised private
Definition at line 576 of file mavlink_main.h.
Referenced by Mavlink().
bool Mavlink::_use_hil_gps private
Accept GPS HIL messages (for example from an external motion capturing system to fake indoor gps)
Definition at line 530 of file mavlink_main.h.
Referenced by get_use_hil_gps(), Mavlink(), and mavlink_update_system().
bool Mavlink::_wait_to_transmit private
Wait to transmit until received messages.
Definition at line 533 of file mavlink_main.h.
Referenced by get_wait_to_transmit(), Mavlink(), set_wait_to_transmit(), should_transmit(), and task_main().
bool Mavlink::mavlink_link_termination_allowed private
Definition at line 572 of file mavlink_main.h.
Referenced by Mavlink().
constexpr int Mavlink::MAVLINK_MAX_INSTANCES = 4 static private
Definition at line 520 of file mavlink_main.h.
Referenced by start().
constexpr int Mavlink::MAVLINK_MAX_INTERVAL = 10000 static private
Definition at line 522 of file mavlink_main.h.
Referenced by adjust_stream_rates(), and task_main().
constexpr int Mavlink::MAVLINK_MIN_INTERVAL = 1500 static private
Definition at line 521 of file mavlink_main.h.
Referenced by adjust_stream_rates(), and task_main().
constexpr float Mavlink::MAVLINK_MIN_MULTIPLIER = 0.0005f static private
Definition at line 523 of file mavlink_main.h.
Referenced by adjust_stream_rates().
Mavlink* Mavlink::next protected
Definition at line 509 of file mavlink_main.h.
Referenced by destroy_all_instances(), get_status_all_instances(), and instance_exists().
constexpr unsigned Mavlink::RADIO_BUFFER_CRITICAL_LOW_PERCENTAGE = 25 static private
Definition at line 652 of file mavlink_main.h.
Referenced by update_rate_mult().
constexpr unsigned Mavlink::RADIO_BUFFER_HALF_PERCENTAGE = 50 static private
Definition at line 654 of file mavlink_main.h.
Referenced by update_rate_mult().
constexpr unsigned Mavlink::RADIO_BUFFER_LOW_PERCENTAGE = 35 static private
Definition at line 653 of file mavlink_main.h.
Referenced by update_rate_mult().
The documentation for this class was generated from the following files:
src/modules/mavlink/mavlink_main.h
src/modules/mavlink/mavlink_main.cpp