PX4 Firmware: src/platforms/posix/drivers/df_ak8963_wrapper/df_ak8963_wrapper.cpp File Reference
df_ak8963_wrapper.cpp File Reference
Lightweight driver to access the AK8963 of the DriverFramework.
#include <px4_config.h>
#include <sys/types.h>
#include <sys/stat.h>
#include <stdint.h>
#include <stddef.h>
#include <stdlib.h>
#include <string.h>
#include <math.h>
#include <unistd.h>
#include <px4_getopt.h>
#include <errno.h>
#include <perf/perf_counter.h>
#include <systemlib/err.h>
#include <drivers/drv_mag.h>
#include <drivers/drv_hrt.h>
#include <uORB/topics/parameter_update.h>
#include <board_config.h>
#include <lib/conversion/rotation.h>
#include <ak8963/AK8963.hpp>
#include <DevMgr.hpp>
Classes
class DfAK8963Wrapper
struct DfAK8963Wrapper::mag_calibration_s
Namespaces
df_ak8963_wrapper
Functions
__EXPORT int df_ak8963_wrapper_main (int argc, char *argv[])
int df_ak8963_wrapper::start (enum Rotation rotation)
int df_ak8963_wrapper::stop ()
Stop the driver.
int df_ak8963_wrapper::info ()
Print a little info about the driver.
void df_ak8963_wrapper::usage ()
Prints info about the driver argument usage.
Variables
DfAK8963Wrapper * df_ak8963_wrapper::g_dev = nullptr
Detailed Description
Lightweight driver to access the AK8963 of the DriverFramework.
Definition in file df_ak8963_wrapper.cpp.
Function Documentation
int df_ak8963_wrapper_main (int argc, char * argv[])
Definition at line 412 of file df_ak8963_wrapper.cpp.
References df_ak8963_wrapper::info(), px4_getopt(), ROTATION_NONE, df_ak8963_wrapper::start(), df_ak8963_wrapper::stop(), and df_ak8963_wrapper::usage().