PX4 Firmware: MavlinkStreamScaledIMU2 Class Reference
MavlinkStreamScaledIMU2 Class Reference
Public Member Functions
const char * get_name () const override
uint16_t get_id () override
unsigned get_size () override
Get maximal total messages size on update.
Public Member Functions inherited from MavlinkStream
MavlinkStream (Mavlink *mavlink)
virtual ~MavlinkStream ()=default
MavlinkStream (const MavlinkStream &)=delete
MavlinkStream & operator= (const MavlinkStream &)=delete
MavlinkStream (MavlinkStream &&)=delete
MavlinkStream & operator= (MavlinkStream &&)=delete
void set_interval (const int interval)
Get the interval.
int get_interval ()
Get the interval.
int update (const hrt_abstime &t)
Update subscriptions and send message if necessary.
virtual bool const_rate ()
virtual unsigned get_size_avg ()
Get the average message size.
bool first_message_sent () const
void reset_last_sent ()
Reset the time of last sent to 0.
Public Member Functions inherited from ListNode< MavlinkStream *>
void setSibling (MavlinkStream * sibling)
const MavlinkStream * getSibling () const
Static Public Member Functions
static const char * get_name_static ()
static uint16_t get_id_static ()
static MavlinkStream * new_instance (Mavlink *mavlink)
Protected Member Functions
MavlinkStreamScaledIMU2 (Mavlink *mavlink)
bool send (const hrt_abstime t) override
Protected Member Functions inherited from MavlinkStream
virtual void update_data ()
Function to collect/update data for the streams at a high rate independant of actual stream rate.
Private Member Functions
MavlinkStreamScaledIMU2 (MavlinkStreamScaledIMU2 &)=delete
MavlinkStreamScaledIMU2 & operator= (const MavlinkStreamScaledIMU2 &)=delete
Private Attributes
MavlinkOrbSubscription * _raw_accel_sub
MavlinkOrbSubscription * _raw_gyro_sub
MavlinkOrbSubscription * _raw_mag_sub
uint64_t _raw_accel_time
uint64_t _raw_gyro_time
uint64_t _raw_mag_time
Additional Inherited Members
Protected Attributes inherited from MavlinkStream
Mavlink *const _mavlink
int _interval {1000000}
if set to negative value = unlimited rate
Protected Attributes inherited from ListNode< MavlinkStream *>
MavlinkStream * _list_node_sibling
Detailed Description
Definition at line 995 of file mavlink_messages.cpp.
Constructor & Destructor Documentation
MavlinkStreamScaledIMU2() [1/2]
MavlinkStreamScaledIMU2::MavlinkStreamScaledIMU2 (MavlinkStreamScaledIMU2 &) private delete
MavlinkStreamScaledIMU2() [2/2]
MavlinkStreamScaledIMU2::MavlinkStreamScaledIMU2 (Mavlink * mavlink) inline explicit protected
Definition at line 1042 of file mavlink_messages.cpp.
Member Function Documentation
get_id()
uint16_t MavlinkStreamScaledIMU2::get_id () inline override virtual
Implements MavlinkStream.
Definition at line 1013 of file mavlink_messages.cpp.
References MavlinkStreamHeartbeat::get_id_static().
get_id_static()
static uint16_t MavlinkStreamScaledIMU2::get_id_static () inline static
Definition at line 1008 of file mavlink_messages.cpp.
get_name()
const char* MavlinkStreamScaledIMU2::get_name () const inline override virtual
Implements MavlinkStream.
Definition at line 998 of file mavlink_messages.cpp.
References get_name_static().
get_name_static()
static const char* MavlinkStreamScaledIMU2::get_name_static () inline static
Definition at line 1003 of file mavlink_messages.cpp.
Referenced by get_name().
get_size()
unsigned MavlinkStreamScaledIMU2::get_size () inline override virtual
Get maximal total messages size on update.
Implements MavlinkStream.
Definition at line 1023 of file mavlink_messages.cpp.
new_instance()
static MavlinkStream* MavlinkStreamScaledIMU2::new_instance (Mavlink * mavlink) inline static
Definition at line 1018 of file mavlink_messages.cpp.
operator=()
MavlinkStreamScaledIMU2& MavlinkStreamScaledIMU2::operator= (const MavlinkStreamScaledIMU2 &) private delete
send()
bool MavlinkStreamScaledIMU2::send (const hrt_abstime t) inline override protected virtual
Implements MavlinkStream.
Definition at line 1051 of file mavlink_messages.cpp.
References MavlinkStream::_mavlink, CONSTANTS_ONE_G, Mavlink::get_channel(), msg, sensor_accel_s::timestamp, MavlinkOrbSubscription::update(), sensor_mag_s::x_raw, sensor_accel_s::x_raw, sensor_gyro_s::x_raw, sensor_mag_s::y_raw, sensor_gyro_s::y_raw, sensor_accel_s::y_raw, sensor_mag_s::z_raw, sensor_accel_s::z_raw, and sensor_gyro_s::z_raw.
Member Data Documentation
_raw_accel_sub
MavlinkOrbSubscription* MavlinkStreamScaledIMU2::_raw_accel_sub private
Definition at line 1029 of file mavlink_messages.cpp.
_raw_accel_time
uint64_t MavlinkStreamScaledIMU2::_raw_accel_time private
Definition at line 1033 of file mavlink_messages.cpp.
_raw_gyro_sub
MavlinkOrbSubscription* MavlinkStreamScaledIMU2::_raw_gyro_sub private
Definition at line 1030 of file mavlink_messages.cpp.
_raw_gyro_time
uint64_t MavlinkStreamScaledIMU2::_raw_gyro_time private
Definition at line 1034 of file mavlink_messages.cpp.
_raw_mag_sub
MavlinkOrbSubscription* MavlinkStreamScaledIMU2::_raw_mag_sub private
Definition at line 1031 of file mavlink_messages.cpp.
_raw_mag_time
uint64_t MavlinkStreamScaledIMU2::_raw_mag_time private
Definition at line 1035 of file mavlink_messages.cpp.
The documentation for this class was generated from the following file:
src/modules/mavlink/mavlink_messages.cpp