PX4 Firmware: lsm303d Namespace Reference
lsm303d Namespace Reference
Local functions in support of the shell command.
Functions
void start (bool external_bus, enum Rotation rotation, unsigned range)
Start the driver.
void test ()
Perform some basic functional tests on the driver; make sure we can collect data from the sensor in polled and automatic modes.
void reset ()
Reset the driver.
void info ()
Print a little info about the driver.
void regdump ()
dump registers from device
void usage ()
Prints info about the driver argument usage.
void test_error ()
trigger an error
Variables
LSM303D * g_dev
Detailed Description
Local functions in support of the shell command.
Function Documentation
void lsm303d::info ()
Print a little info about the driver.
Print a little info about the driver.
Definition at line 1978 of file lsm303d.cpp.
References errx, and LSM303D::print_info().
Referenced by lsm303d_main().
void lsm303d::regdump (void)
dump registers from device
Definition at line 1994 of file lsm303d.cpp.
References errx, and LSM303D::print_registers().
Referenced by lsm303d_main().
void lsm303d::reset ()
Reset the driver.
Reset the driver.
Definition at line 1939 of file lsm303d.cpp.
References device::CDev::close(), err, fd, LSM303D_mag::ioctl(), LSM303D_DEVICE_PATH_ACCEL, LSM303D_DEVICE_PATH_MAG, device::CDev::open(), PX4_WARN, SENSOR_POLLRATE_DEFAULT, SENSORIOCRESET, and SENSORIOCSPOLLRATE.
Referenced by lsm303d_main(), and test().
void lsm303d::start (bool external_bus, enum Rotation rotation, unsigned range)
Start the driver.
This function call only returns once the driver is up and running or failed to detect the sensor.
Definition at line 1801 of file lsm303d.cpp.
References ACCELIOCSRANGE, device::CDev::close(), errx, fd, g_dev, LSM303D::init(), LSM303D_mag::ioctl(), LSM303D_mag::LSM303D, LSM303D_DEVICE_PATH_ACCEL, LSM303D_DEVICE_PATH_MAG, OK, device::CDev::open(), PX4_ERR, PX4_SPI_BUS_EXT, PX4_SPI_BUS_SENSORS, PX4_SPIDEV_ACCEL_MAG, PX4_SPIDEV_EXT_ACCEL_MAG, SENSOR_POLLRATE_DEFAULT, and SENSORIOCSPOLLRATE.
Referenced by lsm303d_main().
void lsm303d::test ()
Perform some basic functional tests on the driver; make sure we can collect data from the sensor in polled and automatic modes.
Definition at line 1874 of file lsm303d.cpp.
References accel_report, device::CDev::close(), err, errx, LSM303D_mag::ioctl(), LSM303D_DEVICE_PATH_ACCEL, LSM303D_DEVICE_PATH_MAG, mag_report, MAGIOCGEXTERNAL, device::CDev::open(), PX4_INFO, LSM303D_mag::read(), reset(), SENSOR_POLLRATE_DEFAULT, and SENSORIOCSPOLLRATE.
Referenced by lsm303d_main().
void lsm303d::test_error (void)
trigger an error
Definition at line 2010 of file lsm303d.cpp.
References errx, and LSM303D::test_error().
Referenced by lsm303d_main().
void lsm303d::usage (void)
Prints info about the driver argument usage.
Prints info about the driver argument usage.
Definition at line 2022 of file lsm303d.cpp.
References PX4_INFO.
Referenced by lsm303d_main().
Variable Documentation
LSM303D* lsm303d::g_dev
Definition at line 1784 of file lsm303d.cpp.
Referenced by start().