PX4 Firmware: MavlinkStreamLocalPositionSetpoint Class Reference
MavlinkStreamLocalPositionSetpoint Class Reference
Public Member Functions
const char * get_name () const
uint16_t get_id ()
unsigned get_size ()
Get maximal total messages size on update.
Public Member Functions inherited from MavlinkStream
MavlinkStream (Mavlink *mavlink)
virtual ~MavlinkStream ()=default
MavlinkStream (const MavlinkStream &)=delete
MavlinkStream & operator= (const MavlinkStream &)=delete
MavlinkStream (MavlinkStream &&)=delete
MavlinkStream & operator= (MavlinkStream &&)=delete
void set_interval (const int interval)
Get the interval.
int get_interval ()
Get the interval.
int update (const hrt_abstime &t)
Update subscriptions and send message if necessary.
virtual bool const_rate ()
virtual unsigned get_size_avg ()
Get the average message size.
bool first_message_sent () const
void reset_last_sent ()
Reset the time of last sent to 0.
Static Public Member Functions
static const char * get_name_static ()
static uint16_t get_id_static ()
static MavlinkStream * new_instance (Mavlink *mavlink)
Protected Member Functions
MavlinkStreamLocalPositionSetpoint (Mavlink *mavlink)
bool send (const hrt_abstime t)
Protected Member Functions inherited from MavlinkStream
virtual void update_data ()
Function to collect/update data for the streams at a high rate independant of actual stream rate.
Private Member Functions
MavlinkStreamLocalPositionSetpoint (MavlinkStreamLocalPositionSetpoint &)=delete
MavlinkStreamLocalPositionSetpoint & operator= (const MavlinkStreamLocalPositionSetpoint &)=delete
Private Attributes
MavlinkOrbSubscription * _pos_sp_sub
uint64_t _pos_sp_time
Additional Inherited Members
Public Attributes inherited from MavlinkStream
MavlinkStream * next {nullptr}
Protected Attributes inherited from MavlinkStream
Mavlink *const _mavlink
int _interval {1000000}
if set to negative value = unlimited rate
Detailed Description
Definition at line 2917 of file mavlink_messages.cpp.
Constructor & Destructor Documentation
MavlinkStreamLocalPositionSetpoint::MavlinkStreamLocalPositionSetpoint (MavlinkStreamLocalPositionSetpoint &) private delete
MavlinkStreamLocalPositionSetpoint::MavlinkStreamLocalPositionSetpoint (Mavlink * mavlink) inline explicit protected
Definition at line 2959 of file mavlink_messages.cpp.
Member Function Documentation
uint16_t MavlinkStreamLocalPositionSetpoint::get_id () inline virtual
Implements MavlinkStream.
Definition at line 2935 of file mavlink_messages.cpp.
References MavlinkStreamHeartbeat::get_id_static().
static uint16_t MavlinkStreamLocalPositionSetpoint::get_id_static () inline static
Definition at line 2930 of file mavlink_messages.cpp.
const char* MavlinkStreamLocalPositionSetpoint::get_name () const inline virtual
Implements MavlinkStream.
Definition at line 2920 of file mavlink_messages.cpp.
References get_name_static().
static const char* MavlinkStreamLocalPositionSetpoint::get_name_static () inline static
Definition at line 2925 of file mavlink_messages.cpp.
Referenced by get_name().
unsigned MavlinkStreamLocalPositionSetpoint::get_size () inline virtual
Get maximal total messages size on update.
Implements MavlinkStream.
Definition at line 2945 of file mavlink_messages.cpp.
static MavlinkStream* MavlinkStreamLocalPositionSetpoint::new_instance (Mavlink * mavlink) inline static
Definition at line 2940 of file mavlink_messages.cpp.
MavlinkStreamLocalPositionSetpoint& MavlinkStreamLocalPositionSetpoint::operator= (const MavlinkStreamLocalPositionSetpoint &) private delete
bool MavlinkStreamLocalPositionSetpoint::send (const hrt_abstime t) inline protected virtual
Implements MavlinkStream.
Definition at line 2964 of file mavlink_messages.cpp.
References MavlinkStream::_mavlink, vehicle_local_position_setpoint_s::acc_x, vehicle_local_position_setpoint_s::acc_y, vehicle_local_position_setpoint_s::acc_z, Mavlink::get_channel(), msg, vehicle_local_position_setpoint_s::timestamp, MavlinkOrbSubscription::update(), vehicle_local_position_setpoint_s::vx, vehicle_local_position_setpoint_s::vy, vehicle_local_position_setpoint_s::vz, vehicle_local_position_setpoint_s::x, vehicle_local_position_setpoint_s::y, vehicle_local_position_setpoint_s::yaw, vehicle_local_position_setpoint_s::yawspeed, and vehicle_local_position_setpoint_s::z.
Member Data Documentation
MavlinkOrbSubscription* MavlinkStreamLocalPositionSetpoint::_pos_sp_sub private
Definition at line 2951 of file mavlink_messages.cpp.
uint64_t MavlinkStreamLocalPositionSetpoint::_pos_sp_time private
Definition at line 2952 of file mavlink_messages.cpp.
The documentation for this class was generated from the following file:
src/modules/mavlink/mavlink_messages.cpp