PX4 Firmware: fxas21002c Namespace Reference
fxas21002c Namespace Reference
Local functions in support of the shell command.
Functions
void start (bool external_bus, enum Rotation rotation)
Start the driver.
void test ()
Perform some basic functional tests on the driver; make sure we can collect data from the sensor in polled and automatic modes.
void reset ()
Reset the driver.
void info ()
Print a little info about the driver.
void regdump ()
dump registers from device
void usage ()
Prints info about the driver argument usage.
void test_error ()
trigger an error
Variables
FXAS21002C * g_dev
Detailed Description
Local functions in support of the shell command.
Function Documentation
void fxas21002c::info ()
Print a little info about the driver.
Print a little info about the driver.
Definition at line 1314 of file fxas21002c.cpp.
References FXAS21002C::print_info(), and PX4_ERR.
Referenced by fxas21002c_main().
void fxas21002c::regdump (void)
dump registers from device
Definition at line 1331 of file fxas21002c.cpp.
References FXAS21002C::print_registers(), and PX4_ERR.
Referenced by fxas21002c_main().
void fxas21002c::reset ()
Reset the driver.
Reset the driver.
Definition at line 1286 of file fxas21002c.cpp.
References fd, FXAS21002C_DEVICE_PATH_GYRO, FXAS21002C::ioctl(), PX4_ERR, SENSOR_POLLRATE_DEFAULT, SENSORIOCRESET, and SENSORIOCSPOLLRATE.
Referenced by fxas21002c_main().
void fxas21002c::start (bool external_bus, enum Rotation rotation)
Start the driver.
This function call only returns once the driver is up and running or failed to detect the sensor.
Definition at line 1184 of file fxas21002c.cpp.
References errx, fd, FXAS21002C::FXAS21002C(), FXAS21002C_DEVICE_PATH_GYRO, g_dev, FXAS21002C::init(), FXAS21002C::ioctl(), OK, PX4_ERR, PX4_INFO, PX4_SPI_BUS_EXT, PX4_SPI_BUS_SENSORS, PX4_SPIDEV_EXT_GYRO, PX4_SPIDEV_GYRO, SENSOR_POLLRATE_DEFAULT, and SENSORIOCSPOLLRATE.
Referenced by fxas21002c_main().
void fxas21002c::test ()
Perform some basic functional tests on the driver; make sure we can collect data from the sensor in polled and automatic modes.
Definition at line 1245 of file fxas21002c.cpp.
References err, errx, FXAS21002C_DEVICE_PATH_GYRO, gyro_report, FXAS21002C::ioctl(), FXAS21002C::read(), SENSOR_POLLRATE_DEFAULT, SENSOR_POLLRATE_MANUAL, and SENSORIOCSPOLLRATE.
Referenced by fxas21002c_main().
void fxas21002c::test_error (void)
trigger an error
Definition at line 1348 of file fxas21002c.cpp.
References PX4_ERR, and FXAS21002C::test_error().
Referenced by fxas21002c_main().
void fxas21002c::usage (void)
Prints info about the driver argument usage.
Prints info about the driver argument usage.
Definition at line 1361 of file fxas21002c.cpp.
References PX4_INFO.
Referenced by fxas21002c_main().
Variable Documentation
FXAS21002C* fxas21002c::g_dev
Definition at line 1167 of file fxas21002c.cpp.
Referenced by start().