PX4 Firmware: src/modules/commander/Arming/ArmAuthorization/ArmAuthorization.h File Reference
ArmAuthorization.h File Reference
#include <stdint.h>
#include <drivers/drv_hrt.h>
#include <uORB/uORB.h>
Enumerations
enum arm_auth_methods { ARM_AUTH_METHOD_ARM_REQ = 0, ARM_AUTH_METHOD_TWO_ARM_REQ, ARM_AUTH_METHOD_LAST }
Functions
void arm_auth_init (orb_advert_t *mav_log_pub, uint8_t *system_id)
void arm_auth_update (hrt_abstime now, bool param_update=true)
uint8_t arm_auth_check ()
enum arm_auth_methods arm_auth_method_get ()
Enumeration Type Documentation
arm_auth_methods
enum arm_auth_methods
Enumerator
ARM_AUTH_METHOD_ARM_REQ
ARM_AUTH_METHOD_TWO_ARM_REQ
ARM_AUTH_METHOD_LAST
Definition at line 41 of file ArmAuthorization.h.
Function Documentation
arm_auth_check()
uint8_t arm_auth_check ()
Definition at line 171 of file ArmAuthorization.cpp.
References ARM_AUTH_METHOD_LAST, arm_check_method, and arm_parameters.
Referenced by PreFlightCheck::preArmCheck().
arm_auth_init()
void arm_auth_init (orb_advert_t * mav_log_pub, uint8_t * system_id)
Definition at line 276 of file ArmAuthorization.cpp.
References command_ack_sub, mavlink_log_pub, ORB_ID, orb_subscribe(), param_arm_parameters, and param_find().
Referenced by Commander::run().
arm_auth_method_get()
enum arm_auth_methods arm_auth_method_get ()
Definition at line 284 of file ArmAuthorization.cpp.
References arm_parameters.
arm_auth_update()
void arm_auth_update (hrt_abstime now, bool param_update = true)
Definition at line 180 of file ArmAuthorization.cpp.
References ARM_AUTH_IDLE, ARM_AUTH_MISSION_APPROVED, ARM_AUTH_WAITING_AUTH, ARM_AUTH_WAITING_AUTH_WITH_ACK, arm_parameters, auth_timeout, vehicle_command_ack_s::command, command_ack_sub, mavlink_log_critical, mavlink_log_pub, orb_check(), orb_copy(), ORB_ID, param_arm_parameters, param_get(), vehicle_command_ack_s::result, vehicle_command_ack_s::result_param1, vehicle_command_ack_s::result_param2, state, and vehicle_command_ack_s::target_system.
Referenced by _auth_method_arm_req_check(), and Commander::run().