PX4 Firmware: LocalPositionEstimatorModule Class Reference
LocalPositionEstimatorModule Class Reference
Public Member Functions
virtual ~LocalPositionEstimatorModule ()=default
void run () override
Static Public Member Functions
static int task_spawn (int argc, char *argv[])
static LocalPositionEstimatorModule * instantiate (int argc, char *argv[])
static int custom_command (int argc, char *argv[])
static int print_usage (const char *reason=nullptr)
Private Attributes
BlockLocalPositionEstimator _estimator
Detailed Description
Definition at line 51 of file local_position_estimator_main.cpp.
Constructor & Destructor Documentation
virtual LocalPositionEstimatorModule::~LocalPositionEstimatorModule () virtual default
Member Function Documentation
int LocalPositionEstimatorModule::custom_command (int argc, char * argv[]) static
See also
ModuleBase
Definition at line 95 of file local_position_estimator_main.cpp.
References print_usage().
LocalPositionEstimatorModule * LocalPositionEstimatorModule::instantiate (int argc, char * argv[]) static
See also
ModuleBase
Definition at line 118 of file local_position_estimator_main.cpp.
References instance, and PX4_ERR.
int LocalPositionEstimatorModule::print_usage (const char * reason = nullptr) static
See also
ModuleBase
Definition at line 75 of file local_position_estimator_main.cpp.
References PRINT_MODULE_DESCRIPTION(), PRINT_MODULE_USAGE_COMMAND, PRINT_MODULE_USAGE_DEFAULT_COMMANDS, PRINT_MODULE_USAGE_NAME(), and PX4_WARN.
Referenced by custom_command().
void LocalPositionEstimatorModule::run () override
See also
ModuleBase::run()
Definition at line 129 of file local_position_estimator_main.cpp.
References _estimator, and BlockLocalPositionEstimator::update().
int LocalPositionEstimatorModule::task_spawn (int argc, char * argv[]) static
See also
ModuleBase
Definition at line 101 of file local_position_estimator_main.cpp.
References px4_task_spawn_cmd(), SCHED_DEFAULT, and SCHED_PRIORITY_ESTIMATOR.
Member Data Documentation
BlockLocalPositionEstimator LocalPositionEstimatorModule::_estimator private
Definition at line 72 of file local_position_estimator_main.cpp.
Referenced by run().
The documentation for this class was generated from the following file:
src/modules/local_position_estimator/local_position_estimator_main.cpp