PX4 Firmware: src/lib/ecl/EKF/tests/ringbuffer/ringbuffer.cpp File Reference
ringbuffer.cpp File Reference
#include <stdint.h>
#include <cassert>
#include <EKF/RingBuffer.h>
Classes
struct sample
Functions
int main (int argc, char *argv[])
Function Documentation
int main (int argc, char * argv[])
Definition at line 51 of file ringbuffer.cpp.
References RingBuffer< data_type >::allocate(), sample::data, RingBuffer< data_type >::get_newest(), RingBuffer< data_type >::get_oldest(), RingBuffer< data_type >::pop_first_older_than(), RingBuffer< data_type >::push(), and sample::time_us.