PX4 Firmware: df_mpu9250_wrapper Namespace Reference
df_mpu9250_wrapper Namespace Reference
Functions
int start (bool mag_enabled, enum Rotation rotation)
int stop ()
Stop the driver.
int info ()
Print a little info about the driver.
void usage ()
Prints info about the driver argument usage.
Variables
DfMpu9250Wrapper * g_dev = nullptr
Function Documentation
info()
int df_mpu9250_wrapper::info ()
Print a little info about the driver.
Definition at line 849 of file df_mpu9250_wrapper.cpp.
References DfMpu9250Wrapper::info().
Referenced by df_mpu9250_wrapper_main().
start()
int df_mpu9250_wrapper::start (bool mag_enabled, enum Rotation rotation)
Definition at line 795 of file df_mpu9250_wrapper.cpp.
References DfMpu9250Wrapper::DfMpu9250Wrapper(), and DfMpu9250Wrapper::start().
Referenced by df_mpu9250_wrapper_main().
stop()
int df_mpu9250_wrapper::stop ()
Stop the driver.
Stop the driver.
Definition at line 826 of file df_mpu9250_wrapper.cpp.
References g_dev, and DfMpu9250Wrapper::stop().
Referenced by df_mpu9250_wrapper_main().
usage()
void df_mpu9250_wrapper::usage (void)
Prints info about the driver argument usage.
Prints info about the driver argument usage.
Definition at line 863 of file df_mpu9250_wrapper.cpp.
Referenced by df_mpu9250_wrapper_main().
Variable Documentation
g_dev
DfMpu9250Wrapper* df_mpu9250_wrapper::g_dev = nullptr
Definition at line 788 of file df_mpu9250_wrapper.cpp.
Referenced by stop().