PX4 Firmware: ManualSmoothingXY Class Reference
ManualSmoothingXY Class Reference
#include <ManualSmoothingXY.hpp>
Public Types
enum Intention { Intention::brake, Intention::acceleration, Intention::deceleration, Intention::direction_change }
Public Member Functions
ManualSmoothingXY (ModuleParams *parent, const matrix::Vector2f &vel)
~ManualSmoothingXY ()=default
void updateMaxVelocity (const float &vel_max)
Maximum velocity is required to detect user intention.
void smoothVelocity (matrix::Vector2f &vel_sp, const matrix::Vector2f &vel, const float &yaw, const float &yawrate_sp, const float dt)
Smoothing of velocity setpoint horizontally based on flight direction.
Intention getIntention ()
Get user intention.
void overwriteHoverAcceleration (float acc)
Overwrite methods: Needed if different parameter values than default required.
void overwriteMaxAcceleration (float acc)
void overwriteDecelerationMin (float dec)
void overwriteJerkMax (float jerk)
void overwriteJerkMin (float jerk)
Public Member Functions inherited from ModuleParams
ModuleParams (ModuleParams *parent)
void setParent (ModuleParams *parent)
Set the parent module.
virtual ~ModuleParams ()=default
ModuleParams (const ModuleParams &)=delete
ModuleParams & operator= (const ModuleParams &)=delete
ModuleParams (ModuleParams &&)=delete
ModuleParams & operator= (ModuleParams &&)=delete
Public Member Functions inherited from ListNode< ModuleParams * >
ListNode ()
ListNode (const ListNode &)=delete
ListNode (ListNode &&)=delete
virtual ~ListNode ()=default
ListNode & operator= (const ListNode &)=delete
ListNode & operator= (ListNode &&)=delete
void setSibling (ModuleParams *sibling)
const ModuleParams * getSibling ()
Private Member Functions
void _updateAcceleration (matrix::Vector2f &vel_sp, const matrix::Vector2f &vel, const float &yaw, const float &yawrate_sp, const float dt)
Sets velocity change limits (=acceleration).
Intention _getIntention (const matrix::Vector2f &vel_sp, const matrix::Vector2f &vel, const float &yaw, const float &yawrate_sp)
Gets user intention.
void _setStateAcceleration (const matrix::Vector2f &vel_sp, const matrix::Vector2f &vel, const Intention &intention, const float dt)
Set acceleration depending on Intention.
void _velocitySlewRate (matrix::Vector2f &vel_sp, const float dt)
Limits the velocity setpoint change.
matrix::Vector2f _getWorldToHeadingFrame (const matrix::Vector2f &vec, const float &yaw)
Rotate vector from local frame into heading frame.
matrix::Vector2f _getHeadingToWorldFrame (const matrix::Vector2f &vec, const float &yaw)
Rotate vector from heading frame to local frame.
Private Attributes
Intention _intention {Intention::acceleration}
user intention
float _acc_state_dependent
velocity change limit that depends on Intention
float _jerk_state_dependent
acceleration change limit during brake
float _vel_max {10.0f}
maximum horizontal speed allowed
matrix::Vector2f _vel_sp_prev
previous velocity setpoint
Additional Inherited Members
Protected Member Functions inherited from ModuleParams
virtual void updateParams ()
Call this whenever the module gets a parameter change notification.
virtual void updateParamsImpl ()
The implementation for this is generated with the macro DEFINE_PARAMETERS()
Protected Attributes inherited from ListNode< ModuleParams * >
ModuleParams * _sibling
Detailed Description
Definition at line 53 of file ManualSmoothingXY.hpp.
Member Enumeration Documentation
enum ManualSmoothingXY::Intention strong
Enumerator
brake
acceleration
deceleration
direction_change
Definition at line 84 of file ManualSmoothingXY.hpp.
Constructor & Destructor Documentation
ManualSmoothingXY::ManualSmoothingXY (ModuleParams * parent, const matrix::Vector2f & vel)
Definition at line 43 of file ManualSmoothingXY.cpp.
References _acc_state_dependent, and _jerk_state_dependent.
ManualSmoothingXY::~ManualSmoothingXY () default
Member Function Documentation
matrix::Vector2f ManualSmoothingXY::_getHeadingToWorldFrame (const matrix::Vector2f & vec, const float & yaw) private
Rotate vector from heading frame to local frame.
Parameters
vec is an arbitrary vector in heading frame
yaw is the vehicle yaw
Definition at line 220 of file ManualSmoothingXY.cpp.
References matrix::Quaternion< Type >::conjugate(), and f().
Referenced by overwriteJerkMin().
ManualSmoothingXY::Intention ManualSmoothingXY::_getIntention (const matrix::Vector2f & vel_sp, const matrix::Vector2f & vel, const float & yaw, const float & yawrate_sp) private
Gets user intention.
The intention is deduced from desired velocity setpoint.
Parameters
vel_sp is desired velocity setpoint before slewrate.
vel is vehicle velocity in xy-direction.
yaw is vehicle yaw
yawrate_sp is the desired yaw-speed
Definition at line 72 of file ManualSmoothingXY.cpp.
References _getWorldToHeadingFrame(), _vel_max, _vel_sp_prev, acceleration, brake, deceleration, direction_change, f(), matrix::Vector< Type, M >::length(), and matrix::Vector< Type, M >::normalize().
Referenced by _updateAcceleration(), and overwriteJerkMin().
matrix::Vector2f ManualSmoothingXY::_getWorldToHeadingFrame (const matrix::Vector2f & vec, const float & yaw) private
Rotate vector from local frame into heading frame.
Parameters
vec is an arbitrary vector in local frame
yaw is the vehicle heading
Definition at line 212 of file ManualSmoothingXY.cpp.
References matrix::Quaternion< Type >::conjugate_inversed(), and f().
Referenced by _getIntention(), and overwriteJerkMin().
void ManualSmoothingXY::_setStateAcceleration (const matrix::Vector2f & vel_sp, const matrix::Vector2f & vel, const Intention & intention, const float dt) private
Set acceleration depending on Intention.
Parameters
vel_sp is desired velocity septoint in xy-direction
vel is vehicle velociy in xy-direction
intention is the user intention during flight
dt is delta-time
Definition at line 120 of file ManualSmoothingXY.cpp.
References _acc_state_dependent, _intention, _jerk_state_dependent, _vel_max, _vel_sp_prev, acceleration, brake, deceleration, direction_change, matrix::Vector< Type, M >::length(), and math::min().
Referenced by _updateAcceleration(), and overwriteJerkMin().
void ManualSmoothingXY::_updateAcceleration (matrix::Vector2f & vel_sp, const matrix::Vector2f & vel, const float & yaw, const float & yawrate_sp, const float dt) private
Sets velocity change limits (=acceleration).
Depending on the user intention, the acceleration differs.
Parameters
vel_sp is desired velocity setpoint before slewrate.
vel is current velocity in horizontal direction
yaw is vehicle yaw
yawrate_sp is desired yawspeed
dt is delta-time
Definition at line 61 of file ManualSmoothingXY.cpp.
References _getIntention(), and _setStateAcceleration().
Referenced by overwriteJerkMin(), and smoothVelocity().
void ManualSmoothingXY::_velocitySlewRate (matrix::Vector2f & vel_sp, const float dt) private
Limits the velocity setpoint change.
Parameters
vel_sp that gets limited based on acceleration and previous velocity setpoint
dt is delta-time
Definition at line 197 of file ManualSmoothingXY.cpp.
References _acc_state_dependent, _vel_sp_prev, and matrix::Vector< Type, M >::normalized().
Referenced by overwriteJerkMin(), and smoothVelocity().
Intention ManualSmoothingXY::getIntention () inline
Get user intention.
See also
Intention
Definition at line 94 of file ManualSmoothingXY.hpp.
References _intention.
void ManualSmoothingXY::overwriteDecelerationMin (float dec) inline
Definition at line 102 of file ManualSmoothingXY.hpp.
void ManualSmoothingXY::overwriteHoverAcceleration (float acc) inline
Overwrite methods: Needed if different parameter values than default required.
Definition at line 100 of file ManualSmoothingXY.hpp.
void ManualSmoothingXY::overwriteJerkMax (float jerk) inline
Definition at line 103 of file ManualSmoothingXY.hpp.
void ManualSmoothingXY::overwriteJerkMin (float jerk) inline
Definition at line 104 of file ManualSmoothingXY.hpp.
References _getHeadingToWorldFrame(), _getIntention(), _getWorldToHeadingFrame(), _setStateAcceleration(), _updateAcceleration(), and _velocitySlewRate().
void ManualSmoothingXY::overwriteMaxAcceleration (float acc) inline
Definition at line 101 of file ManualSmoothingXY.hpp.
void ManualSmoothingXY::smoothVelocity (matrix::Vector2f & vel_sp, const matrix::Vector2f & vel, const float & yaw, const float & yawrate_sp, const float dt)
Smoothing of velocity setpoint horizontally based on flight direction.
Parameters
vel_sp velocity setpoint in xy
dt time delta in seconds
Definition at line 52 of file ManualSmoothingXY.cpp.
References _updateAcceleration(), _vel_sp_prev, and _velocitySlewRate().
Referenced by FlightTaskManualPositionSmooth::_updateSetpoints(), and updateMaxVelocity().
void ManualSmoothingXY::updateMaxVelocity (const float & vel_max) inline
Maximum velocity is required to detect user intention.
Maximum velocity depends on flight-task. In order to deduce user intention from velocity, the maximum allowed velocity has to be updated.
Parameters
vel_max corresponds to vehicle constraint
Definition at line 66 of file ManualSmoothingXY.hpp.
References _vel_max, dt, and smoothVelocity().
Referenced by FlightTaskManualPositionSmooth::_updateSetpoints().
Member Data Documentation
float ManualSmoothingXY::_acc_state_dependent private
velocity change limit that depends on Intention
Definition at line 162 of file ManualSmoothingXY.hpp.
Referenced by _setStateAcceleration(), _velocitySlewRate(), and ManualSmoothingXY().
Intention ManualSmoothingXY::_intention {Intention::acceleration} private
user intention
Definition at line 161 of file ManualSmoothingXY.hpp.
Referenced by _setStateAcceleration(), and getIntention().
float ManualSmoothingXY::_jerk_state_dependent private
acceleration change limit during brake
Definition at line 163 of file ManualSmoothingXY.hpp.
Referenced by _setStateAcceleration(), and ManualSmoothingXY().
float ManualSmoothingXY::_vel_max {10.0f} private
maximum horizontal speed allowed
Definition at line 164 of file ManualSmoothingXY.hpp.
Referenced by _getIntention(), _setStateAcceleration(), and updateMaxVelocity().
matrix::Vector2f ManualSmoothingXY::_vel_sp_prev private
previous velocity setpoint
Definition at line 165 of file ManualSmoothingXY.hpp.
Referenced by _getIntention(), _setStateAcceleration(), _velocitySlewRate(), and smoothVelocity().
The documentation for this class was generated from the following files:
src/lib/FlightTasks/tasks/Utility/ManualSmoothingXY.hpp
src/lib/FlightTasks/tasks/Utility/ManualSmoothingXY.cpp