PX4 Firmware: List Struct Reference
List Struct Reference
bus configurations
Public Member Functions
void add (T newNode)
bool remove (T removeNode)
Iterator begin ()
Iterator end ()
const T getHead () const
bool empty () const
size_t size () const
void deleteNode (T node)
void clear ()
Protected Attributes
T _head {nullptr}
Detailed Description
bus configurations
Member Function Documentation
add()
void List::add (T newNode) inline
Definition at line 63 of file List.hpp.
Referenced by Mavlink::add_orb_subscription().
begin()
Iterator List::begin () inline
Definition at line 136 of file List.hpp.
clear()
void List::clear () inline
Definition at line 162 of file List.hpp.
Referenced by Mavlink::task_main().
deleteNode()
void List::deleteNode (T node) inline
Definition at line 154 of file List.hpp.
empty()
bool List::empty () const inline
Definition at line 141 of file List.hpp.
end()
Iterator List::end () inline
Definition at line 137 of file List.hpp.
getHead()
const T List::getHead () const inline
Definition at line 139 of file List.hpp.
remove()
bool List::remove (T removeNode) inline
Definition at line 86 of file List.hpp.
size()
size_t List::size () const inline
Definition at line 143 of file List.hpp.
Referenced by Mavlink::publish_telemetry_status().
Member Data Documentation
_head
T List::_head {nullptr} protected
Definition at line 177 of file List.hpp.
The documentation for this struct was generated from the following files:
src/drivers/magnetometer/rm3100/rm3100_main.h
src/include/containers/List.hpp