PX4 Firmware: RGBLED Class Reference
RGBLED Class Reference
#include <navio_rgbled.h>
Public Member Functions
RGBLED (const char *name)
virtual ~RGBLED ()
int start ()
int stop ()
RGBLED (int bus, int rgbled)
virtual ~RGBLED ()
virtual int init ()
virtual int probe ()
int status ()
Protected Member Functions
void _measure ()
Private Member Functions
void led ()
Main loop function.
int send_led_enable (bool enable)
Sent ENABLE flag to LED driver.
int send_led_rgb ()
Send RGB PWM settings to LED driver according to current color and brightness.
int get (bool &on, bool &powersave, uint8_t &r, uint8_t &g, uint8_t &b)
void update_params ()
Static Private Member Functions
static void led_trampoline (void *arg)
Private Attributes
LedController _led_controller
LinuxGPIO _gpioR
LinuxGPIO _gpioG
LinuxGPIO _gpioB
work_s _work
float _brightness
float _max_brightness
uint8_t _r
uint8_t _g
uint8_t _b
volatile bool _running
volatile bool _should_run
bool _leds_enabled
int _param_sub
Detailed Description
Definition at line 40 of file navio_rgbled.h.
Constructor & Destructor Documentation
RGBLED::RGBLED (const char * name)
Definition at line 44 of file navio_rgbled.cpp.
Referenced by rgbled_main(), and navio_rgbled::start().
RGBLED::~RGBLED () virtual
Definition at line 56 of file navio_rgbled.cpp.
References _led_controller, LedController::led_control_subscription(), and orb_unsubscribe().
Referenced by RGBLED().
RGBLED::RGBLED (int bus, int rgbled)
Definition at line 130 of file rgbled.cpp.
References _b, _brightness, _g, _leds_enabled, _max_brightness, _param_sub, _r, _running, _should_run, counter, f(), usleep(), and ~RGBLED().
virtual RGBLED::~RGBLED () virtual
Member Function Documentation
void RGBLED::_measure (void) protected
Definition at line 153 of file navio_rgbled.cpp.
References _gpioB, _gpioG, _gpioR, _led_controller, LedControlDataSingle::color, LinuxGPIO::HIGH, LedController::init(), LedController::is_init(), led_control, LedControlData::leds, LinuxGPIO::LOW, navio_rgbled_main(), ORB_ID, orb_subscribe(), LedController::update(), and LinuxGPIO::writeValue().
int RGBLED::get (bool & on, bool & powersave, uint8_t & r, uint8_t & g, uint8_t & b) private
Definition at line 382 of file rgbled.cpp.
References OK, SETTING_ENABLE, and SETTING_NOT_POWERSAVE.
int RGBLED::init () virtual
Definition at line 160 of file rgbled.cpp.
References _running, lis3mdl::init(), led_trampoline(), OK, send_led_enable(), send_led_rgb(), and update_params().
void RGBLED::led () private
Main loop function.
Definition at line 245 of file rgbled.cpp.
References _b, _brightness, _g, _led_controller, _param_sub, _r, _running, _should_run, LedControlDataSingle::brightness, LedControlDataSingle::color, LedController::init(), LedController::is_init(), led_control, LedController::led_control_subscription(), led_trampoline(), LedControlData::leds, LedController::maximum_update_interval(), orb_check(), orb_copy(), ORB_ID, orb_subscribe(), orb_unsubscribe(), send_led_enable(), send_led_rgb(), LedController::update(), and update_params().
Referenced by led_trampoline().
void RGBLED::led_trampoline (void * arg) static private
Definition at line 234 of file rgbled.cpp.
References led().
Referenced by init(), and led().
int RGBLED::probe () virtual
this may look strange, but is needed. There is a serial EEPROM (Microchip-24aa01) that responds to a bunch of I2C addresses, including the 0x55 used by this LED device. So we need to do enough operations to be sure we are talking to the right device. These 3 operations seem to be enough, as the 3rd one consistently fails if no RGBLED is on the bus.
Definition at line 183 of file rgbled.cpp.
References OK, and send_led_enable().
int RGBLED::send_led_enable (bool enable) private
Sent ENABLE flag to LED driver.
Definition at line 345 of file rgbled.cpp.
References _leds_enabled, msg, SETTING_ENABLE, SETTING_NOT_POWERSAVE, and SUB_ADDR_SETTINGS.
Referenced by init(), led(), and probe().
int RGBLED::send_led_rgb () private
Send RGB PWM settings to LED driver according to current color and brightness.
Definition at line 370 of file rgbled.cpp.
References _b, _brightness, _g, _max_brightness, _r, f(), msg, SUB_ADDR_PWM0, SUB_ADDR_PWM1, and SUB_ADDR_PWM2.
Referenced by init(), and led().
int RGBLED::start ()
Definition at line 63 of file navio_rgbled.cpp.
References _gpioB, _gpioG, _gpioR, _led_controller, LinuxGPIO::exportPin(), lis3mdl::init(), LedController::maximum_update_interval(), LinuxGPIO::OUT, PX4_ERR, LinuxGPIO::setDirection(), start(), and LinuxGPIO::unexportPin().
Referenced by do_test(), and navio_rgbled::start().
int RGBLED::status ()
Definition at line 213 of file rgbled.cpp.
References DEVICE_LOG, OK, and PX4_WARN.
int RGBLED::stop ()
Definition at line 134 of file navio_rgbled.cpp.
References _gpioB, _gpioG, _gpioR, stop(), and LinuxGPIO::unexportPin().
Referenced by navio_rgbled::stop().
void RGBLED::update_params () private
Definition at line 402 of file rgbled.cpp.
References _max_brightness, param_find(), and param_get().
Referenced by init(), and led().
Member Data Documentation
uint8_t RGBLED::_b private
Definition at line 103 of file rgbled.cpp.
Referenced by led(), RGBLED(), and send_led_rgb().
float RGBLED::_brightness private
Definition at line 98 of file rgbled.cpp.
Referenced by led(), RGBLED(), and send_led_rgb().
uint8_t RGBLED::_g private
Definition at line 102 of file rgbled.cpp.
Referenced by led(), RGBLED(), and send_led_rgb().
LinuxGPIO RGBLED::_gpioB private
Definition at line 56 of file navio_rgbled.h.
Referenced by _measure(), start(), and stop().
LinuxGPIO RGBLED::_gpioG private
Definition at line 55 of file navio_rgbled.h.
Referenced by _measure(), start(), and stop().
LinuxGPIO RGBLED::_gpioR private
Definition at line 54 of file navio_rgbled.h.
Referenced by _measure(), start(), and stop().
LedController RGBLED::_led_controller private
Definition at line 53 of file navio_rgbled.h.
Referenced by _measure(), led(), start(), and ~RGBLED().
bool RGBLED::_leds_enabled private
Definition at line 106 of file rgbled.cpp.
Referenced by RGBLED(), and send_led_enable().
float RGBLED::_max_brightness private
Definition at line 99 of file rgbled.cpp.
Referenced by RGBLED(), send_led_rgb(), and update_params().
int RGBLED::_param_sub private
Definition at line 107 of file rgbled.cpp.
Referenced by led(), and RGBLED().
uint8_t RGBLED::_r private
Definition at line 101 of file rgbled.cpp.
Referenced by led(), RGBLED(), and send_led_rgb().
volatile bool RGBLED::_running private
Definition at line 104 of file rgbled.cpp.
Referenced by init(), led(), and RGBLED().
volatile bool RGBLED::_should_run private
Definition at line 105 of file rgbled.cpp.
Referenced by led(), and RGBLED().
work_s RGBLED::_work private
Definition at line 96 of file rgbled.cpp.
The documentation for this class was generated from the following files:
src/drivers/navio_rgbled/navio_rgbled.h
src/drivers/rgbled/rgbled.cpp
src/drivers/navio_rgbled/navio_rgbled.cpp