PX4 Firmware: src/lib/flight_tasks/tasks/Utility/test_velocity_smoothing.cpp File Reference
test_velocity_smoothing.cpp File Reference
#include "VelocitySmoothing.hpp"
#include <cstdio>
#include <matrix/matrix/math.hpp>
Functions
int main (int argc, char *argv[])
Test code for the Velocity Smoothing library Build and run using: make && .
Function Documentation
main()
int main (int argc, char * argv[])
Test code for the Velocity Smoothing library Build and run using: make && .
/test_velocity_smoothing
Definition at line 43 of file test_velocity_smoothing.cpp.
References matrix::ceil(), dt, VelocitySmoothing::getTotalTime(), VelocitySmoothing::setCurrentAcceleration(), VelocitySmoothing::setCurrentVelocity(), VelocitySmoothing::setMaxAccel(), VelocitySmoothing::setMaxJerk(), VelocitySmoothing::setMaxVel(), t123, VelocitySmoothing::timeSynchronization(), VelocitySmoothing::updateDurations(), and VelocitySmoothing::updateTraj().