PX4 Firmware: src/systemcmds/tests/test_file.c File Reference
test_file.c File Reference
File write test.
#include <px4_platform_common/px4_config.h>
#include <px4_platform_common/posix.h>
#include <sys/stat.h>
#include <poll.h>
#include <dirent.h>
#include <stdio.h>
#include <stddef.h>
#include <systemlib/err.h>
#include <perf/perf_counter.h>
#include <string.h>
#include <drivers/drv_hrt.h>
#include "tests_main.h"
Functions
static int check_user_abort (int fd)
int test_file (int argc, char *argv[])
Detailed Description
File write test.
Author
Lorenz Meier lm@in.nosp@m.f.et.nosp@m.hz.ch
Definition in file test_file.c.
Function Documentation
check_user_abort()
int check_user_abort (int fd) static
Definition at line 58 of file test_file.c.
References OK, read(), and warnx.
Referenced by test_file().
test_file()
int test_file (int argc, char * argv[])
Definition at line 91 of file test_file.c.
References __attribute__(), check_user_abort(), fd, hrt_absolute_time(), hrt_abstime, OK, px4_close(), px4_open(), read(), start(), warn, warnx, and write().