PX4 Firmware: VL53LXX Class Reference
VL53LXX Class Reference
Public Member Functions
VL53LXX (uint8_t rotation=distance_sensor_s::ROTATION_DOWNWARD_FACING, int bus=VL53LXX_BUS_DEFAULT, int address=VL53LXX_BASEADDR)
virtual ~VL53LXX ()
virtual int init ()
virtual ssize_t read (device::file_t *filp, char *buffer, size_t buflen)
virtual int ioctl (device::file_t *filp, int cmd, unsigned long arg)
void print_info ()
Diagnostics - print some basic information about the driver.
Protected Member Functions
virtual int probe ()
Private Member Functions
void start ()
Initialise the automatic measurement state machine and start it.
void stop ()
Stop the automatic measurement state machine.
void cycle ()
Perform a poll cycle; collect from the previous measurement and start a new one.
int measure ()
int collect ()
int readRegister (uint8_t reg_address, uint8_t &value)
int writeRegister (uint8_t reg_address, uint8_t value)
int writeRegisterMulti (uint8_t reg_address, uint8_t *value, uint8_t length)
int readRegisterMulti (uint8_t reg_address, uint8_t *value, uint8_t length)
int sensorInit ()
bool spadCalculations ()
bool sensorTuning ()
bool singleRefCalibration (uint8_t byte)
Static Private Member Functions
static void cycle_trampoline (void *arg)
Static trampoline from the workq context; because we don't have a generic workq wrapper yet.
Private Attributes
uint8_t _rotation
work_s _work
ringbuffer::RingBuffer * _reports
bool _sensor_ok
int _measure_ticks
bool _collect_phase
bool _new_measurement
bool _measurement_started
int _class_instance
int _orb_class_instance
orb_advert_t _distance_sensor_topic
perf_counter_t _sample_perf
perf_counter_t _comms_errors
uint8_t _stop_variable
Detailed Description
Definition at line 108 of file vl53lxx.cpp.
Constructor & Destructor Documentation
VL53LXX::VL53LXX (uint8_t rotation = distance_sensor_s::ROTATION_DOWNWARD_FACING, int bus = VL53LXX_BUS_DEFAULT, int address = VL53LXX_BASEADDR)
Definition at line 196 of file vl53lxx.cpp.
Referenced by vl53lxx::start_bus().
VL53LXX::~VL53LXX () virtual
Definition at line 222 of file vl53lxx.cpp.
References _class_instance, _comms_errors, _distance_sensor_topic, _reports, _sample_perf, orb_unadvertise(), perf_free(), RANGE_FINDER_BASE_DEVICE_PATH, and stop().
Member Function Documentation
int VL53LXX::collect () private
Definition at line 645 of file vl53lxx.cpp.
References _class_instance, _collect_phase, _comms_errors, _distance_sensor_topic, _orb_class_instance, _reports, _rotation, _sample_perf, CLASS_DEVICE_PRIMARY, distance_sensor_s::covariance, distance_sensor_s::current_distance, DEVICE_LOG, f(), hrt_absolute_time(), distance_sensor_s::id, distance_sensor_s::max_distance, distance_sensor_s::min_distance, OK, ORB_ID, ORB_PRIO_DEFAULT, orb_publish_auto(), distance_sensor_s::orientation, perf_begin(), perf_count(), perf_end(), distance_sensor_s::signal_quality, distance_sensor_s::timestamp, distance_sensor_s::type, VL53LXX_MAX_RANGING_DISTANCE, and VL53LXX_MIN_RANGING_DISTANCE.
Referenced by cycle(), and read().
void VL53LXX::cycle () private
Perform a poll cycle; collect from the previous measurement and start a new one.
Definition at line 730 of file vl53lxx.cpp.
References _collect_phase, _measure_ticks, _new_measurement, collect(), cycle_trampoline(), and measure().
Referenced by cycle_trampoline().
void VL53LXX::cycle_trampoline (void * arg) static private
Static trampoline from the workq context; because we don't have a generic workq wrapper yet.
Parameters
arg Instance pointer for the driver that is polling.
Definition at line 721 of file vl53lxx.cpp.
References cycle().
Referenced by cycle(), measure(), and start().
int VL53LXX::init () virtual
Definition at line 301 of file vl53lxx.cpp.
References _class_instance, _reports, _sensor_ok, lis3mdl::init(), OK, PX4_ERROR, RANGE_FINDER_BASE_DEVICE_PATH, and VL53LXX_BASEADDR.
Referenced by vl53lxx::start_bus().
int VL53LXX::ioctl (device::file_t * filp, int cmd, unsigned long arg) virtual
Definition at line 342 of file vl53lxx.cpp.
References _measure_ticks, OK, SENSOR_POLLRATE_DEFAULT, SENSOR_POLLRATE_MANUAL, SENSORIOCSPOLLRATE, start(), stop(), and VL53LXX_SAMPLE_RATE.
Referenced by vl53lxx::start_bus().
int VL53LXX::measure () private
Definition at line 567 of file vl53lxx.cpp.
References _collect_phase, _comms_errors, _measurement_started, _new_measurement, _stop_variable, cycle_trampoline(), DEVICE_LOG, OK, perf_count(), readRegister(), RESULT_INTERRUPT_STATUS_REG, RESULT_RANGE_STATUS_REG, SYSRANGE_START_REG, VL53LXX_US, and writeRegister().
Referenced by cycle(), and read().
void VL53LXX::print_info ()
Diagnostics - print some basic information about the driver.
Definition at line 752 of file vl53lxx.cpp.
References _comms_errors, _measure_ticks, _reports, _sample_perf, and perf_print_counter().
Referenced by vl53lxx::info().
int VL53LXX::probe () protected virtual
Definition at line 331 of file vl53lxx.cpp.
References OK, and sensorInit().
ssize_t VL53LXX::read (device::file_t * filp, char * buffer, size_t buflen) virtual
Definition at line 405 of file vl53lxx.cpp.
References _collect_phase, _measure_ticks, _reports, collect(), measure(), and OK.
Referenced by vl53lxx::test().
int VL53LXX::readRegister (uint8_t reg_address, uint8_t & value) private
Definition at line 465 of file vl53lxx.cpp.
References _comms_errors, OK, and perf_count().
Referenced by measure(), sensorInit(), singleRefCalibration(), and spadCalculations().
int VL53LXX::readRegisterMulti (uint8_t reg_address, uint8_t * value, uint8_t length) private
Definition at line 491 of file vl53lxx.cpp.
References _comms_errors, OK, and perf_count().
Referenced by spadCalculations().
int VL53LXX::sensorInit () private
Definition at line 247 of file vl53lxx.cpp.
References _stop_variable, FINAL_RANGE_CONFIG_MIN_COUNT_RATE_RTN_LIMIT_REG, MSRC_CONFIG_CONTROL_REG, OK, PX4_ERROR, readRegister(), spadCalculations(), SYSTEM_SEQUENCE_CONFIG_REG, VHV_CONFIG_PAD_SCL_SDA_EXTSUP_HW_REG, writeRegister(), and writeRegisterMulti().
Referenced by probe().
bool VL53LXX::sensorTuning () private
Definition at line 856 of file vl53lxx.cpp.
References OK, and writeRegister().
Referenced by spadCalculations().
bool VL53LXX::singleRefCalibration (uint8_t byte) private
Definition at line 945 of file vl53lxx.cpp.
References OK, readRegister(), RESULT_INTERRUPT_STATUS_REG, SYSRANGE_START_REG, SYSTEM_INTERRUPT_CLEAR_REG, and writeRegister().
Referenced by spadCalculations().
bool VL53LXX::spadCalculations () private
Definition at line 762 of file vl53lxx.cpp.
References DYNAMIC_SPAD_NUM_REQUESTED_REF_SPAD_REG, DYNAMIC_SPAD_REF_EN_START_OFFSET_REG, GLOBAL_CONFIG_REF_EN_START_SELECT_REG, GLOBAL_CONFIG_SPAD_ENABLES_REF_0_REG, GPIO_HV_MUX_ACTIVE_HIGH_REG, OK, readRegister(), readRegisterMulti(), sensorTuning(), singleRefCalibration(), SYSTEM_INTERRUPT_CLEAR_REG, SYSTEM_INTERRUPT_CONFIG_GPIO_REG, SYSTEM_SEQUENCE_CONFIG_REG, writeRegister(), and writeRegisterMulti().
Referenced by sensorInit().
void VL53LXX::start () private
Initialise the automatic measurement state machine and start it.
Definition at line 703 of file vl53lxx.cpp.
References _reports, cycle_trampoline(), and VL53LXX_US.
Referenced by ioctl().
void VL53LXX::stop () private
Stop the automatic measurement state machine.
Definition at line 714 of file vl53lxx.cpp.
Referenced by ioctl(), and ~VL53LXX().
int VL53LXX::writeRegister (uint8_t reg_address, uint8_t value) private
Definition at line 517 of file vl53lxx.cpp.
References _comms_errors, OK, and perf_count().
Referenced by measure(), sensorInit(), sensorTuning(), singleRefCalibration(), and spadCalculations().
int VL53LXX::writeRegisterMulti (uint8_t reg_address, uint8_t * value, uint8_t length) private
Definition at line 538 of file vl53lxx.cpp.
References _comms_errors, DEVICE_LOG, OK, perf_count(), and PX4_ERROR.
Referenced by sensorInit(), and spadCalculations().
Member Data Documentation
int VL53LXX::_class_instance private
Definition at line 140 of file vl53lxx.cpp.
Referenced by collect(), init(), and ~VL53LXX().
bool VL53LXX::_collect_phase private
Definition at line 136 of file vl53lxx.cpp.
Referenced by collect(), cycle(), measure(), and read().
perf_counter_t VL53LXX::_comms_errors private
Definition at line 146 of file vl53lxx.cpp.
Referenced by collect(), measure(), print_info(), readRegister(), readRegisterMulti(), writeRegister(), writeRegisterMulti(), and ~VL53LXX().
orb_advert_t VL53LXX::_distance_sensor_topic private
Definition at line 143 of file vl53lxx.cpp.
Referenced by collect(), and ~VL53LXX().
int VL53LXX::_measure_ticks private
Definition at line 135 of file vl53lxx.cpp.
Referenced by cycle(), ioctl(), print_info(), and read().
bool VL53LXX::_measurement_started private
Definition at line 138 of file vl53lxx.cpp.
Referenced by measure().
bool VL53LXX::_new_measurement private
Definition at line 137 of file vl53lxx.cpp.
Referenced by cycle(), and measure().
int VL53LXX::_orb_class_instance private
Definition at line 141 of file vl53lxx.cpp.
Referenced by collect().
ringbuffer::RingBuffer* VL53LXX::_reports private
Definition at line 133 of file vl53lxx.cpp.
Referenced by collect(), init(), print_info(), read(), start(), and ~VL53LXX().
uint8_t VL53LXX::_rotation private
Definition at line 131 of file vl53lxx.cpp.
Referenced by collect().
perf_counter_t VL53LXX::_sample_perf private
Definition at line 145 of file vl53lxx.cpp.
Referenced by collect(), print_info(), and ~VL53LXX().
bool VL53LXX::_sensor_ok private
Definition at line 134 of file vl53lxx.cpp.
Referenced by init().
uint8_t VL53LXX::_stop_variable private
Definition at line 148 of file vl53lxx.cpp.
Referenced by measure(), and sensorInit().
work_s VL53LXX::_work private
Definition at line 132 of file vl53lxx.cpp.
The documentation for this class was generated from the following file:
src/drivers/distance_sensor/vl53lxx/vl53lxx.cpp