PX4 Firmware: src/drivers/px4io/px4io.cpp File Reference
px4io.cpp File Reference
Driver for the PX4IO board.
#include <px4_config.h>
#include <px4_tasks.h>
#include <sys/types.h>
#include <stdint.h>
#include <stdbool.h>
#include <assert.h>
#include <debug.h>
#include <time.h>
#include <queue.h>
#include <errno.h>
#include <string.h>
#include <stdio.h>
#include <stdlib.h>
#include <unistd.h>
#include <fcntl.h>
#include <math.h>
#include <crc32.h>
#include <arch/board/board.h>
#include <drivers/device/device.h>
#include <drivers/drv_rc_input.h>
#include <drivers/drv_pwm_output.h>
#include <drivers/drv_sbus.h>
#include <drivers/drv_gpio.h>
#include <drivers/drv_hrt.h>
#include <drivers/drv_mixer.h>
#include <rc/dsm.h>
#include <lib/mixer/mixer.h>
#include <perf/perf_counter.h>
#include <systemlib/err.h>
#include <parameters/param.h>
#include <circuit_breaker/circuit_breaker.h>
#include <systemlib/mavlink_log.h>
#include <uORB/topics/actuator_controls.h>
#include <uORB/topics/actuator_outputs.h>
#include <uORB/topics/actuator_armed.h>
#include <uORB/topics/safety.h>
#include <uORB/topics/vehicle_control_mode.h>
#include <uORB/topics/vehicle_command.h>
#include <uORB/topics/rc_channels.h>
#include <uORB/topics/servorail_status.h>
#include <uORB/topics/parameter_update.h>
#include <uORB/topics/multirotor_motor_limits.h>
#include <modules/px4iofirmware/protocol.h>
#include "uploader.h"
#include "modules/dataman/dataman.h"
#include "px4io_driver.h"
Classes
class PX4IO
The PX4IO class.
Macros
#define PX4IO_SET_DEBUG _IOC(0xff00, 0)
#define PX4IO_INAIR_RESTART_ENABLE _IOC(0xff00, 1)
#define PX4IO_REBOOT_BOOTLOADER _IOC(0xff00, 2)
#define PX4IO_CHECK_CRC _IOC(0xff00, 3)
#define UPDATE_INTERVAL_MIN 2
#define ORB_CHECK_INTERVAL 200000
#define IO_POLL_INTERVAL 20000
Functions
__EXPORT int px4io_main (int argc, char *argv[])
Detailed Description
Driver for the PX4IO board.
PX4IO is connected via I2C or DMA enabled high-speed UART.
Definition in file px4io.cpp.
Macro Definition Documentation
#define IO_POLL_INTERVAL 20000
Definition at line 107 of file px4io.cpp.
Referenced by PX4IO::task_main().
#define ORB_CHECK_INTERVAL 200000
Definition at line 106 of file px4io.cpp.
Referenced by PX4IO::task_main().
#define PX4IO_CHECK_CRC _IOC(0xff00, 3)
Definition at line 103 of file px4io.cpp.
Referenced by PX4IO::ioctl(), and PX4IO::set_update_rate().
#define PX4IO_INAIR_RESTART_ENABLE _IOC(0xff00, 1)
Definition at line 101 of file px4io.cpp.
Referenced by PX4IO::ioctl(), and px4io_main().
#define PX4IO_REBOOT_BOOTLOADER _IOC(0xff00, 2)
Definition at line 102 of file px4io.cpp.
Referenced by PX4IO::ioctl(), and px4io_main().
#define PX4IO_SET_DEBUG _IOC(0xff00, 0)
Definition at line 100 of file px4io.cpp.
Referenced by PX4IO::ioctl(), and px4io_main().
#define UPDATE_INTERVAL_MIN 2
Definition at line 105 of file px4io.cpp.
Referenced by PX4IO::set_update_rate(), and PX4IO::task_main().
Function Documentation
int px4io_main (int argc, char * argv[])
Definition at line 3354 of file px4io.cpp.
References PX4IO::detect(), errx, fn, ets_airspeed::g_dev, Airspeed::ioctl(), OK, PWM_SERVO_SET_FORCE_SAFETY_OFF, PWM_SERVO_SET_FORCE_SAFETY_ON, PX4_MFT_HW_SUPPORTED, PX4_MFT_PX4IO, PX4IO::PX4IO(), PX4IO_INAIR_RESTART_ENABLE, PX4IO_REBOOT_BOOTLOADER, PX4IO_SET_DEBUG, RC_INPUT_ENABLE_RSSI_ANALOG, RC_INPUT_ENABLE_RSSI_PWM, SBUS_SET_PROTO_VERSION, start(), test, PX4IO_Uploader::upload(), and warnx.
Referenced by PX4IO::set_update_rate().