PX4 Firmware: src/platforms/qurt/tests/hello/hello_start_qurt.cpp File Reference
hello_start_qurt.cpp File Reference
#include "hello_example.h"
#include <px4_log.h>
#include <px4_app.h>
#include <px4_tasks.h>
#include <stdio.h>
#include <string.h>
#include <sched.h>
Functions
__EXPORT int hello_main (int argc, char *argv[])
static void usage ()
Variables
static int daemon_task
Function Documentation
__EXPORT int hello_main (int argc, char * argv[])
Definition at line 58 of file hello_start_qurt.cpp.
References HelloExample::appState, daemon_task, PX4_DEBUG, PX4_MAIN(), px4_task_spawn_cmd(), px4::AppState::requestExit(), SCHED_DEFAULT, SCHED_PRIORITY_MAX, and usage().
static void usage (void) static
Definition at line 54 of file hello_start_qurt.cpp.
References PX4_DEBUG.
Referenced by hello_main().
Variable Documentation
int daemon_task static
Definition at line 48 of file hello_start_qurt.cpp.
Referenced by hello_main().