PX4 Firmware: RTL Class Reference
RTL Class Reference
#include <rtl.h>
Public Types
enum RTLType { RTL_HOME = 0, RTL_LAND, RTL_MISSION }
Public Member Functions
RTL (Navigator *navigator)
~RTL ()=default
void on_inactive () override
This function is called while the mode is inactive.
void on_activation () override
This function is called one time when mode becomes active, pos_sp_triplet must be initialized here.
void on_active () override
This function is called while the mode is active.
void set_return_alt_min (bool min)
int rtl_type () const
Public Member Functions inherited from MissionBlock
MissionBlock (Navigator *navigator)
Constructor.
virtual ~MissionBlock ()=default
MissionBlock (const MissionBlock &)=delete
MissionBlock & operator= (const MissionBlock &)=delete
Public Member Functions inherited from NavigatorMode
NavigatorMode (Navigator *navigator)
virtual ~NavigatorMode ()=default
NavigatorMode (const NavigatorMode &)=delete
NavigatorMode operator= (const NavigatorMode &)=delete
void run (bool active)
virtual void on_inactivation ()
This function is called one time when mode becomes inactive.
Public Member Functions inherited from ModuleParams
ModuleParams (ModuleParams *parent)
void setParent (ModuleParams *parent)
Set the parent module.
virtual ~ModuleParams ()=default
ModuleParams (const ModuleParams &)=delete
ModuleParams & operator= (const ModuleParams &)=delete
ModuleParams (ModuleParams &&)=delete
ModuleParams & operator= (ModuleParams &&)=delete
Public Member Functions inherited from ListNode< ModuleParams * >
ListNode ()
ListNode (const ListNode &)=delete
ListNode (ListNode &&)=delete
virtual ~ListNode ()=default
ListNode & operator= (const ListNode &)=delete
ListNode & operator= (ListNode &&)=delete
void setSibling (ModuleParams *sibling)
const ModuleParams * getSibling ()
Private Types
enum RTLState {
RTL_STATE_NONE = 0, RTL_STATE_CLIMB, RTL_STATE_RETURN, RTL_STATE_TRANSITION_TO_MC,
RTL_STATE_DESCEND, RTL_STATE_LOITER, RTL_STATE_LAND, RTL_STATE_LANDED
}
Private Member Functions
void set_rtl_item ()
Set the RTL item.
void advance_rtl ()
Move to next RTL item.
Private Attributes
enum RTL::RTLState RTL_STATE_NONE
bool _rtl_alt_min {false}
Additional Inherited Members
Static Public Member Functions inherited from MissionBlock
static bool item_contains_position (const mission_item_s &item)
Protected Member Functions inherited from MissionBlock
bool is_mission_item_reached ()
Check if mission item has been reached.
void reset_mission_item_reached ()
Reset all reached flags.
bool mission_item_to_position_setpoint (const mission_item_s &item, position_setpoint_s *sp)
Convert a mission item to a position setpoint.
void set_loiter_item (struct mission_item_s *item, float min_clearance=-1.0f)
Set a loiter mission item, if possible reuse the position setpoint, otherwise take the current position.
void set_takeoff_item (struct mission_item_s *item, float abs_altitude, float min_pitch=0.0f)
Set a takeoff mission item.
void set_land_item (struct mission_item_s *item, bool at_current_location)
Set a land mission item.
void set_idle_item (struct mission_item_s *item)
Set idle mission item.
void set_vtol_transition_item (struct mission_item_s *item, const uint8_t new_mode)
Set vtol transition item.
void mission_apply_limitation (mission_item_s &item)
General function used to adjust the mission item based on vehicle specific limitations.
void issue_command (const mission_item_s &item)
float get_time_inside (const struct mission_item_s &item)
float get_absolute_altitude_for_item (struct mission_item_s &mission_item) const
Protected Member Functions inherited from ModuleParams
virtual void updateParams ()
Call this whenever the module gets a parameter change notification.
virtual void updateParamsImpl ()
The implementation for this is generated with the macro DEFINE_PARAMETERS()
Protected Attributes inherited from MissionBlock
mission_item_s _mission_item {}
bool _waypoint_position_reached {false}
bool _waypoint_yaw_reached {false}
hrt_abstime _time_first_inside_orbit {0}
hrt_abstime _action_start {0}
hrt_abstime _time_wp_reached {0}
orb_advert_t _actuator_pub {nullptr}
Protected Attributes inherited from NavigatorMode
Navigator * _navigator {nullptr}
Protected Attributes inherited from ListNode< ModuleParams * >
ModuleParams * _sibling
Detailed Description
Definition at line 50 of file rtl.h.
Member Enumeration Documentation
enum RTL::RTLState private
Enumerator
RTL_STATE_NONE
RTL_STATE_CLIMB
RTL_STATE_RETURN
RTL_STATE_TRANSITION_TO_MC
RTL_STATE_DESCEND
RTL_STATE_LOITER
RTL_STATE_LAND
RTL_STATE_LANDED
Definition at line 82 of file rtl.h.
enum RTL::RTLType
Enumerator
RTL_HOME
RTL_LAND
RTL_MISSION
Definition at line 53 of file rtl.h.
Constructor & Destructor Documentation
RTL::RTL (Navigator * navigator)
Definition at line 46 of file rtl.cpp.
RTL::~RTL () default
Member Function Documentation
void RTL::advance_rtl () private
Move to next RTL item.
Definition at line 307 of file rtl.cpp.
References NavigatorMode::_navigator, DELAY_SIGMA, Navigator::get_vstatus(), vehicle_status_s::is_rotary_wing, vehicle_status_s::is_vtol, RTL_STATE_CLIMB, RTL_STATE_DESCEND, RTL_STATE_LAND, RTL_STATE_LANDED, RTL_STATE_LOITER, RTL_STATE_RETURN, and RTL_STATE_TRANSITION_TO_MC.
Referenced by on_active().
void RTL::on_activation () override virtual
This function is called one time when mode becomes active, pos_sp_triplet must be initialized here.
Reimplemented from NavigatorMode.
Definition at line 66 of file rtl.cpp.
References NavigatorMode::_navigator, _rtl_alt_min, home_position_s::alt, vehicle_global_position_s::alt, position_setpoint_triplet_s::current, Navigator::get_global_position(), Navigator::get_home_position(), Navigator::get_land_detected(), Navigator::get_position_setpoint_triplet(), vehicle_land_detected_s::landed, Navigator::on_mission_landing(), RTL_LAND, RTL_STATE_CLIMB, RTL_STATE_LAND, RTL_STATE_LANDED, RTL_STATE_RETURN, rtl_type(), set_rtl_item(), position_setpoint_s::type, and position_setpoint_s::valid.
void RTL::on_active () override virtual
This function is called while the mode is active.
Reimplemented from NavigatorMode.
Definition at line 96 of file rtl.cpp.
References advance_rtl(), MissionBlock::is_mission_item_reached(), RTL_STATE_LANDED, and set_rtl_item().
void RTL::on_inactive () override virtual
This function is called while the mode is inactive.
Reimplemented from NavigatorMode.
Definition at line 53 of file rtl.cpp.
References RTL_STATE_NONE.
int RTL::rtl_type () const
Definition at line 60 of file rtl.cpp.
Referenced by Navigator::mission_landing_required(), on_activation(), Navigator::rtl_type(), and set_rtl_item().
void RTL::set_return_alt_min (bool min)
Definition at line 105 of file rtl.cpp.
References _rtl_alt_min, and min().
Referenced by Navigator::check_traffic(), and set_rtl_item().
void RTL::set_rtl_item () private
Set the RTL item.
Definition at line 111 of file rtl.cpp.
References MissionBlock::_mission_item, NavigatorMode::_navigator, mission_item_s::acceptance_radius, home_position_s::alt, vehicle_global_position_s::alt, mission_item_s::altitude, mission_item_s::altitude_is_relative, mission_item_s::autocontinue, position_setpoint_triplet_s::current, Navigator::get_acceptance_radius(), get_bearing_to_next_waypoint(), get_distance_to_next_waypoint(), Navigator::get_global_position(), Navigator::get_home_position(), Navigator::get_local_position(), Navigator::get_loiter_radius(), Navigator::get_mavlink_log_pub(), Navigator::get_position_setpoint_triplet(), MissionBlock::get_time_inside(), Navigator::get_vstatus(), vehicle_status_s::is_vtol, MissionBlock::issue_command(), MissionBlock::item_contains_position(), vehicle_global_position_s::lat, home_position_s::lat, mission_item_s::lat, mission_item_s::loiter_radius, vehicle_global_position_s::lon, home_position_s::lon, mission_item_s::lon, mavlink_and_console_log_info, mavlink_log_critical, math::max(), math::min(), MissionBlock::mission_apply_limitation(), MissionBlock::mission_item_to_position_setpoint(), mission_item_s::nav_cmd, NAV_CMD_LAND, NAV_CMD_LOITER_TIME_LIMIT, NAV_CMD_LOITER_UNLIMITED, NAV_CMD_WAYPOINT, mission_item_s::origin, ORIGIN_ONBOARD, position_setpoint_triplet_s::previous, MissionBlock::reset_mission_item_reached(), RTL_LAND, RTL_STATE_CLIMB, RTL_STATE_DESCEND, RTL_STATE_LAND, RTL_STATE_LANDED, RTL_STATE_LOITER, RTL_STATE_RETURN, RTL_STATE_TRANSITION_TO_MC, rtl_type(), Navigator::set_can_loiter_at_sp(), MissionBlock::set_idle_item(), Navigator::set_position_setpoint_triplet_updated(), set_return_alt_min(), MissionBlock::set_vtol_transition_item(), Navigator::start_mission_landing(), mission_item_s::time_inside, position_setpoint_s::valid, home_position_s::yaw, vehicle_local_position_s::yaw, and mission_item_s::yaw.
Referenced by on_activation(), and on_active().
Member Data Documentation
bool RTL::_rtl_alt_min {false} private
Definition at line 93 of file rtl.h.
Referenced by on_activation(), and set_return_alt_min().
enum RTL::RTLState RTL::RTL_STATE_NONE private
Referenced by on_inactive().
The documentation for this class was generated from the following files:
src/modules/navigator/rtl.h
src/modules/navigator/rtl.cpp