PX4 Firmware: uavcan_kinetis::Mutex Class Reference
uavcan_kinetis::Mutex Class Reference
#include <thread.hpp>
Public Member Functions
Mutex ()
int init ()
int deinit ()
void lock ()
void unlock ()
Private Attributes
pthread_mutex_t mutex_
Detailed Description
Definition at line 47 of file thread.hpp.
Constructor & Destructor Documentation
Mutex()
uavcan_kinetis::Mutex::Mutex () inline
Definition at line 52 of file thread.hpp.
References ToneAlarmInterface::init().
Member Function Documentation
deinit()
int uavcan_kinetis::Mutex::deinit () inline
Definition at line 62 of file thread.hpp.
init()
int uavcan_kinetis::Mutex::init () inline
Definition at line 57 of file thread.hpp.
lock()
void uavcan_kinetis::Mutex::lock () inline
Definition at line 67 of file thread.hpp.
Referenced by uavcan_kinetis::MutexLocker::MutexLocker().
unlock()
void uavcan_kinetis::Mutex::unlock () inline
Definition at line 72 of file thread.hpp.
Referenced by uavcan_kinetis::MutexLocker::~MutexLocker().
Member Data Documentation
mutex_
pthread_mutex_t uavcan_kinetis::Mutex::mutex_ private
Definition at line 49 of file thread.hpp.
The documentation for this class was generated from the following file:
src/drivers/uavcan/uavcan_drivers/kinetis/driver/include/uavcan_kinetis/thread.hpp