PX4 Firmware: ACCELSIM_mag Class Reference
ACCELSIM_mag Class Reference
Helper class implementing the mag driver node.
Public Member Functions
ACCELSIM_mag (ACCELSIM *parent)
~ACCELSIM_mag ()=default
virtual ssize_t devRead (void *buffer, size_t buflen)
virtual int devIOCTL (unsigned long cmd, unsigned long arg)
virtual int start ()
virtual int stop ()
Private Member Functions
virtual void _measure ()
ACCELSIM_mag (const ACCELSIM_mag &)=delete
ACCELSIM_mag operator= (const ACCELSIM_mag &)=delete
Private Attributes
ACCELSIM * _parent
orb_advert_t _mag_topic
int _mag_orb_class_instance
int _mag_class_instance
Friends
class ACCELSIM
Detailed Description
Helper class implementing the mag driver node.
Definition at line 208 of file accelsim.cpp.
Constructor & Destructor Documentation
ACCELSIM_mag::ACCELSIM_mag (ACCELSIM * parent)
Definition at line 958 of file accelsim.cpp.
References DRV_ACC_DEVTYPE_ACCELSIM.
ACCELSIM_mag::~ACCELSIM_mag () default
ACCELSIM_mag::ACCELSIM_mag (const ACCELSIM_mag &) private delete
Member Function Documentation
void ACCELSIM_mag::_measure (void) private virtual
Definition at line 1004 of file accelsim.cpp.
References _parent, and ACCELSIM::mag_measure().
Referenced by ACCELSIM::mag_read().
int ACCELSIM_mag::devIOCTL (unsigned long cmd, unsigned long arg) virtual
Definition at line 976 of file accelsim.cpp.
References _parent, and ACCELSIM::mag_ioctl().
ssize_t ACCELSIM_mag::devRead (void * buffer, size_t buflen) virtual
Definition at line 970 of file accelsim.cpp.
References _parent, and ACCELSIM::mag_read().
ACCELSIM_mag ACCELSIM_mag::operator= (const ACCELSIM_mag &) private delete
int ACCELSIM_mag::start () virtual
Definition at line 992 of file accelsim.cpp.
References start().
Referenced by ACCELSIM::mag_ioctl().
int ACCELSIM_mag::stop () virtual
Definition at line 998 of file accelsim.cpp.
References stop().
Referenced by ACCELSIM::mag_ioctl(), and ACCELSIM::~ACCELSIM().
Friends And Related Function Documentation
friend class ACCELSIM friend
Definition at line 221 of file accelsim.cpp.
Referenced by accelsim::start().
Member Data Documentation
int ACCELSIM_mag::_mag_class_instance private
Definition at line 228 of file accelsim.cpp.
int ACCELSIM_mag::_mag_orb_class_instance private
Definition at line 227 of file accelsim.cpp.
Referenced by ACCELSIM::init().
orb_advert_t ACCELSIM_mag::_mag_topic private
Definition at line 226 of file accelsim.cpp.
Referenced by ACCELSIM::init(), and ACCELSIM::mag_measure().
ACCELSIM* ACCELSIM_mag::_parent private
Definition at line 224 of file accelsim.cpp.
Referenced by _measure(), devIOCTL(), and devRead().
The documentation for this class was generated from the following file:
src/modules/simulator/accelsim/accelsim.cpp