PX4 Firmware: bmi160 Namespace Reference
bmi160 Namespace Reference
Local functions in support of the shell command.
Functions
void start (bool external_bus, enum Rotation rotation)
Start the driver.
void stop (bool)
void test (bool external_bus)
Perform some basic functional tests on the driver; make sure we can collect data from the sensor in polled and automatic modes.
void reset (bool external_bus)
Reset the driver.
void info (bool external_bus)
Print a little info about the driver.
void regdump (bool external_bus)
Dump the register information.
void testerror (bool external_bus)
deliberately produce an error to test recovery
void usage ()
Prints info about the driver argument usage.
Variables
BMI160 * g_dev_int
BMI160 * g_dev_ext
Detailed Description
Local functions in support of the shell command.
Function Documentation
void bmi160::info (bool external_bus)
Print a little info about the driver.
Definition at line 211 of file bmi160_main.cpp.
References errx, and g_dev_int.
Referenced by bmi160_main().
void bmi160::regdump (bool external_bus)
Dump the register information.
Definition at line 229 of file bmi160_main.cpp.
References errx, and g_dev_int.
Referenced by bmi160_main().
void bmi160::reset (bool external_bus)
Reset the driver.
Definition at line 185 of file bmi160_main.cpp.
References BMI160_DEVICE_PATH_ACCEL, BMI160_DEVICE_PATH_ACCEL_EXT, err, fd, SENSOR_POLLRATE_DEFAULT, SENSORIOCRESET, and SENSORIOCSPOLLRATE.
Referenced by bmi160_main(), and test().
void bmi160::start (bool external_bus, enum Rotation rotation)
Start the driver.
This function only returns if the driver is up and running or failed to detect the sensor.
Definition at line 36 of file bmi160_main.cpp.
References BMI160_DEVICE_PATH_ACCEL, BMI160_DEVICE_PATH_ACCEL_EXT, BMI160_DEVICE_PATH_GYRO, BMI160_DEVICE_PATH_GYRO_EXT, errx, fd, g_dev_int, OK, PX4_SPI_BUS_EXT, PX4_SPI_BUS_SENSORS, PX4_SPIDEV_BMI, PX4_SPIDEV_EXT_BMI, SENSOR_POLLRATE_DEFAULT, and SENSORIOCSPOLLRATE.
Referenced by bmi160_main().
void bmi160::stop (bool external_bus)
Definition at line 98 of file bmi160_main.cpp.
References g_dev_int, and warnx.
Referenced by bmi160_main().
void bmi160::test (bool external_bus)
Perform some basic functional tests on the driver; make sure we can collect data from the sensor in polled and automatic modes.
Definition at line 120 of file bmi160_main.cpp.
References accel_report, BMI160_DEVICE_PATH_ACCEL, BMI160_DEVICE_PATH_ACCEL_EXT, BMI160_DEVICE_PATH_GYRO, BMI160_DEVICE_PATH_GYRO_EXT, err, errx, fd, gyro_report, read(), reset(), SENSOR_POLLRATE_DEFAULT, SENSOR_POLLRATE_MANUAL, SENSORIOCSPOLLRATE, and warnx.
Referenced by bmi160_main().
void bmi160::testerror (bool external_bus)
deliberately produce an error to test recovery
Definition at line 248 of file bmi160_main.cpp.
References errx, and g_dev_int.
Referenced by bmi160_main().
void bmi160::usage (void)
Prints info about the driver argument usage.
Prints info about the driver argument usage.
Definition at line 262 of file bmi160_main.cpp.
References warnx.
Referenced by bmi160_main().
Variable Documentation
BMI160* bmi160::g_dev_ext
Definition at line 17 of file bmi160_main.cpp.
BMI160* bmi160::g_dev_int
Definition at line 16 of file bmi160_main.cpp.
Referenced by info(), regdump(), start(), stop(), and testerror().