PX4 Firmware: launchdetection::LaunchDetector Class Reference
launchdetection::LaunchDetector Class Reference
#include <LaunchDetector.h>
Public Member Functions
LaunchDetector (ModuleParams *parent)
~LaunchDetector () override
LaunchDetector (const LaunchDetector &)=delete
LaunchDetector operator= (const LaunchDetector &)=delete
void reset ()
void update (float accel_x)
LaunchDetectionResult getLaunchDetected ()
bool launchDetectionEnabled ()
float getPitchMax (float pitchMaxDefault)
Public Member Functions inherited from ModuleParams
ModuleParams (ModuleParams *parent)
void setParent (ModuleParams *parent)
Set the parent module.
virtual ~ModuleParams ()=default
ModuleParams (const ModuleParams &)=delete
ModuleParams & operator= (const ModuleParams &)=delete
ModuleParams (ModuleParams &&)=delete
ModuleParams & operator= (ModuleParams &&)=delete
Public Member Functions inherited from ListNode< ModuleParams * >
ListNode ()
ListNode (const ListNode &)=delete
ListNode (ListNode &&)=delete
virtual ~ListNode ()=default
ListNode & operator= (const ListNode &)=delete
ListNode & operator= (ListNode &&)=delete
void setSibling (ModuleParams *sibling)
const ModuleParams * getSibling ()
Private Attributes
int _activeLaunchDetectionMethodIndex {-1}
LaunchMethod * _launchMethods [1]
Additional Inherited Members
Protected Member Functions inherited from ModuleParams
virtual void updateParams ()
Call this whenever the module gets a parameter change notification.
virtual void updateParamsImpl ()
The implementation for this is generated with the macro DEFINE_PARAMETERS()
Protected Attributes inherited from ListNode< ModuleParams * >
ModuleParams * _sibling
Detailed Description
Definition at line 50 of file LaunchDetector.h.
Constructor & Destructor Documentation
launchdetection::LaunchDetector::LaunchDetector (ModuleParams * parent)
Definition at line 48 of file LaunchDetector.cpp.
References _launchMethods.
launchdetection::LaunchDetector::~LaunchDetector () override
Definition at line 55 of file LaunchDetector.cpp.
References _launchMethods.
launchdetection::LaunchDetector::LaunchDetector (const LaunchDetector &) delete
Member Function Documentation
LaunchDetectionResult launchdetection::LaunchDetector::getLaunchDetected ()
Definition at line 80 of file LaunchDetector.cpp.
References _activeLaunchDetectionMethodIndex, _launchMethods, launchdetection::LaunchMethod::getLaunchDetected(), launchdetection::LAUNCHDETECTION_RES_NONE, launchDetectionEnabled(), and PX4_INFO.
Referenced by FixedwingPositionControl::control_takeoff().
float launchdetection::LaunchDetector::getPitchMax (float pitchMaxDefault)
Definition at line 101 of file LaunchDetector.cpp.
References _activeLaunchDetectionMethodIndex, _launchMethods, launchdetection::LaunchMethod::getPitchMax(), and launchDetectionEnabled().
Referenced by FixedwingPositionControl::control_takeoff().
bool launchdetection::LaunchDetector::launchDetectionEnabled () inline
Definition at line 63 of file LaunchDetector.h.
Referenced by FixedwingPositionControl::control_takeoff(), getLaunchDetected(), getPitchMax(), and update().
LaunchDetector launchdetection::LaunchDetector::operator= (const LaunchDetector &) delete
void launchdetection::LaunchDetector::reset (void)
Definition at line 60 of file LaunchDetector.cpp.
References _activeLaunchDetectionMethodIndex, and _launchMethods.
Referenced by FixedwingPositionControl::control_takeoff(), and FixedwingPositionControl::reset_takeoff_state().
void launchdetection::LaunchDetector::update (float accel_x)
Definition at line 71 of file LaunchDetector.cpp.
References _launchMethods, and launchDetectionEnabled().
Referenced by FixedwingPositionControl::control_takeoff().
Member Data Documentation
int launchdetection::LaunchDetector::_activeLaunchDetectionMethodIndex {-1} private
Definition at line 75 of file LaunchDetector.h.
Referenced by getLaunchDetected(), getPitchMax(), and reset().
LaunchMethod* launchdetection::LaunchDetector::_launchMethods[1] private
Definition at line 77 of file LaunchDetector.h.
Referenced by getLaunchDetected(), getPitchMax(), LaunchDetector(), reset(), update(), and ~LaunchDetector().
The documentation for this class was generated from the following files:
src/modules/fw_pos_control_l1/launchdetection/LaunchDetector.h
src/modules/fw_pos_control_l1/launchdetection/LaunchDetector.cpp