PX4 Firmware: runwaytakeoff::RunwayTakeoff Class Reference
runwaytakeoff::RunwayTakeoff Class Reference
#include <RunwayTakeoff.h>
Public Member Functions
RunwayTakeoff (ModuleParams *parent)
~RunwayTakeoff ()=default
void init (float yaw, double current_lat, double current_lon)
void update (float airspeed, float alt_agl, double current_lat, double current_lon, orb_advert_t *mavlink_log_pub)
RunwayTakeoffState getState ()
bool isInitialized ()
bool runwayTakeoffEnabled ()
float getMinAirspeedScaling ()
float getInitYaw ()
bool controlYaw ()
bool climbout ()
float getPitch (float tecsPitch)
float getRoll (float navigatorRoll)
float getYaw (float navigatorYaw)
float getThrottle (float tecsThrottle)
bool resetIntegrators ()
float getMinPitch (float sp_min, float climbout_min, float min)
float getMaxPitch (float max)
matrix::Vector2f getStartWP ()
void reset ()
Public Member Functions inherited from ModuleParams
ModuleParams (ModuleParams *parent)
void setParent (ModuleParams *parent)
Set the parent module.
virtual ~ModuleParams ()=default
ModuleParams (const ModuleParams &)=delete
ModuleParams & operator= (const ModuleParams &)=delete
ModuleParams (ModuleParams &&)=delete
ModuleParams & operator= (ModuleParams &&)=delete
Public Member Functions inherited from ListNode< ModuleParams * >
ListNode ()
ListNode (const ListNode &)=delete
ListNode (ListNode &&)=delete
virtual ~ListNode ()=default
ListNode & operator= (const ListNode &)=delete
ListNode & operator= (ListNode &&)=delete
void setSibling (ModuleParams *sibling)
const ModuleParams * getSibling ()
Private Attributes
RunwayTakeoffState _state
state variables
bool _initialized
hrt_abstime _initialized_time
float _init_yaw
bool _climbout
unsigned _throttle_ramp_time
matrix::Vector2f _start_wp
Additional Inherited Members
Protected Member Functions inherited from ModuleParams
virtual void updateParams ()
Call this whenever the module gets a parameter change notification.
virtual void updateParamsImpl ()
The implementation for this is generated with the macro DEFINE_PARAMETERS()
Protected Attributes inherited from ListNode< ModuleParams * >
ModuleParams * _sibling
Detailed Description
Definition at line 65 of file RunwayTakeoff.h.
Constructor & Destructor Documentation
runwaytakeoff::RunwayTakeoff::RunwayTakeoff (ModuleParams * parent)
Definition at line 54 of file RunwayTakeoff.cpp.
runwaytakeoff::RunwayTakeoff::~RunwayTakeoff () default
Member Function Documentation
bool runwaytakeoff::RunwayTakeoff::climbout () inline
Definition at line 82 of file RunwayTakeoff.h.
References max(), min(), and bmp280::reset().
Referenced by FixedwingPositionControl::control_takeoff().
bool runwaytakeoff::RunwayTakeoff::controlYaw ()
Definition at line 131 of file RunwayTakeoff.cpp.
References _state, and runwaytakeoff::CLIMBOUT.
Referenced by FixedwingPositionControl::control_takeoff().
float runwaytakeoff::RunwayTakeoff::getInitYaw () inline
Definition at line 79 of file RunwayTakeoff.h.
float runwaytakeoff::RunwayTakeoff::getMaxPitch (float max)
Definition at line 242 of file RunwayTakeoff.cpp.
References _state, runwaytakeoff::FLY, and max().
Referenced by FixedwingPositionControl::control_takeoff().
float runwaytakeoff::RunwayTakeoff::getMinAirspeedScaling () inline
Definition at line 78 of file RunwayTakeoff.h.
Referenced by FixedwingPositionControl::control_takeoff().
float runwaytakeoff::RunwayTakeoff::getMinPitch (float sp_min, float climbout_min, float min)
Definition at line 226 of file RunwayTakeoff.cpp.
References _state, runwaytakeoff::FLY, math::max(), and min().
Referenced by FixedwingPositionControl::control_takeoff().
float runwaytakeoff::RunwayTakeoff::getPitch (float tecsPitch)
Definition at line 143 of file RunwayTakeoff.cpp.
References _state, runwaytakeoff::CLAMPED_TO_RUNWAY, and math::radians().
Referenced by FixedwingPositionControl::control_takeoff().
float runwaytakeoff::RunwayTakeoff::getRoll (float navigatorRoll)
Definition at line 155 of file RunwayTakeoff.cpp.
References _state, runwaytakeoff::CLIMBOUT, math::constrain(), runwaytakeoff::FLY, and math::radians().
Referenced by FixedwingPositionControl::control_takeoff().
Vector2f runwaytakeoff::RunwayTakeoff::getStartWP ()
Definition at line 257 of file RunwayTakeoff.cpp.
References _start_wp.
Referenced by FixedwingPositionControl::control_takeoff().
RunwayTakeoffState runwaytakeoff::RunwayTakeoff::getState () inline
Definition at line 74 of file RunwayTakeoff.h.
float runwaytakeoff::RunwayTakeoff::getThrottle (float tecsThrottle)
Definition at line 194 of file RunwayTakeoff.cpp.
References _initialized_time, _state, _throttle_ramp_time, runwaytakeoff::CLAMPED_TO_RUNWAY, hrt_elapsed_time(), and runwaytakeoff::THROTTLE_RAMP.
Referenced by FixedwingPositionControl::control_position().
float runwaytakeoff::RunwayTakeoff::getYaw (float navigatorYaw)
Definition at line 178 of file RunwayTakeoff.cpp.
References _init_yaw, _state, and runwaytakeoff::CLIMBOUT.
Referenced by FixedwingPositionControl::control_takeoff().
void runwaytakeoff::RunwayTakeoff::init (float yaw, double current_lat, double current_lon)
Definition at line 65 of file RunwayTakeoff.cpp.
References _climbout, _init_yaw, _initialized, _initialized_time, _start_wp, _state, hrt_absolute_time(), and runwaytakeoff::THROTTLE_RAMP.
Referenced by FixedwingPositionControl::control_takeoff().
bool runwaytakeoff::RunwayTakeoff::isInitialized () inline
Definition at line 75 of file RunwayTakeoff.h.
Referenced by FixedwingPositionControl::control_takeoff().
void runwaytakeoff::RunwayTakeoff::reset (void)
Definition at line 262 of file RunwayTakeoff.cpp.
References _initialized, _state, and runwaytakeoff::THROTTLE_RAMP.
Referenced by FixedwingPositionControl::reset_takeoff_state().
bool runwaytakeoff::RunwayTakeoff::resetIntegrators ()
Definition at line 213 of file RunwayTakeoff.cpp.
References _state, and runwaytakeoff::TAKEOFF.
Referenced by FixedwingPositionControl::control_takeoff().
bool runwaytakeoff::RunwayTakeoff::runwayTakeoffEnabled () inline
Definition at line 77 of file RunwayTakeoff.h.
Referenced by FixedwingPositionControl::control_position(), and FixedwingPositionControl::control_takeoff().
void runwaytakeoff::RunwayTakeoff::update (float airspeed, float alt_agl, double current_lat, double current_lon, orb_advert_t * mavlink_log_pub)
Definition at line 76 of file RunwayTakeoff.cpp.
References _climbout, _initialized_time, _start_wp, _state, _throttle_ramp_time, runwaytakeoff::CLAMPED_TO_RUNWAY, runwaytakeoff::CLIMBOUT, runwaytakeoff::FLY, hrt_elapsed_time(), mavlink_log_info, runwaytakeoff::TAKEOFF, and runwaytakeoff::THROTTLE_RAMP.
Referenced by FixedwingPositionControl::control_takeoff().
Member Data Documentation
bool runwaytakeoff::RunwayTakeoff::_climbout private
Definition at line 100 of file RunwayTakeoff.h.
Referenced by init(), and update().
float runwaytakeoff::RunwayTakeoff::_init_yaw private
Definition at line 99 of file RunwayTakeoff.h.
Referenced by getYaw(), and init().
bool runwaytakeoff::RunwayTakeoff::_initialized private
Definition at line 97 of file RunwayTakeoff.h.
Referenced by init(), and reset().
hrt_abstime runwaytakeoff::RunwayTakeoff::_initialized_time private
Definition at line 98 of file RunwayTakeoff.h.
Referenced by getThrottle(), init(), and update().
matrix::Vector2f runwaytakeoff::RunwayTakeoff::_start_wp private
Definition at line 102 of file RunwayTakeoff.h.
Referenced by getStartWP(), init(), and update().
RunwayTakeoffState runwaytakeoff::RunwayTakeoff::_state private
state variables
Definition at line 96 of file RunwayTakeoff.h.
Referenced by controlYaw(), getMaxPitch(), getMinPitch(), getPitch(), getRoll(), getThrottle(), getYaw(), init(), reset(), resetIntegrators(), and update().
unsigned runwaytakeoff::RunwayTakeoff::_throttle_ramp_time private
Definition at line 101 of file RunwayTakeoff.h.
Referenced by getThrottle(), and update().
The documentation for this class was generated from the following files:
src/modules/fw_pos_control_l1/runway_takeoff/RunwayTakeoff.h
src/modules/fw_pos_control_l1/runway_takeoff/RunwayTakeoff.cpp