PX4 Firmware: src/modules/commander/state_machine_helper.cpp File Reference
state_machine_helper.cpp File Reference
State machine helper functions implementations.
#include <px4_config.h>
#include <uORB/topics/vehicle_command.h>
#include <uORB/topics/vehicle_command_ack.h>
#include <uORB/topics/vehicle_status.h>
#include <systemlib/mavlink_log.h>
#include <drivers/drv_hrt.h>
#include "state_machine_helper.h"
#include "commander_helper.h"
#include "PreflightCheck.h"
#include "arm_auth.h"
Functions
void set_link_loss_nav_state (vehicle_status_s *status, actuator_armed_s *armed, const vehicle_status_flags_s &status_flags, commander_state_s *internal_state, const link_loss_actions_t link_loss_act, uint8_t auto_recovery_nav_state)
void reset_link_loss_globals (actuator_armed_s *armed, const bool old_failsafe, const link_loss_actions_t link_loss_act)
transition_result_t arming_state_transition (vehicle_status_s *status, const battery_status_s &battery, const safety_s &safety, const arming_state_t new_arming_state, actuator_armed_s *armed, const bool fRunPreArmChecks, orb_advert_t *mavlink_log_pub, vehicle_status_flags_s *status_flags, const uint8_t arm_requirements, const hrt_abstime &time_since_boot)
bool is_safe (const safety_s &safety, const actuator_armed_s &armed)
transition_result_t main_state_transition (const vehicle_status_s &status, const main_state_t new_main_state, const vehicle_status_flags_s &status_flags, commander_state_s *internal_state)
transition_result_t hil_state_transition (hil_state_t new_state, orb_advert_t status_pub, vehicle_status_s *current_status, orb_advert_t *mavlink_log_pub)
Transition from one hil state to another.
void enable_failsafe (vehicle_status_s *status, bool old_failsafe, orb_advert_t *mavlink_log_pub, const char *reason)
Enable failsafe and report to user.
bool set_nav_state (vehicle_status_s *status, actuator_armed_s *armed, commander_state_s *internal_state, orb_advert_t *mavlink_log_pub, const link_loss_actions_t data_link_loss_act, const bool mission_finished, const bool stay_in_failsafe, const vehicle_status_flags_s &status_flags, bool landed, const link_loss_actions_t rc_loss_act, const int offb_loss_act, const int offb_loss_rc_act, const int posctl_nav_loss_act)
Check failsafe and main status and set navigation status for navigator accordingly.
bool check_invalid_pos_nav_state (vehicle_status_s *status, bool old_failsafe, orb_advert_t *mavlink_log_pub, const vehicle_status_flags_s &status_flags, const bool use_rc, const bool using_global_pos)
bool prearm_check (orb_advert_t *mavlink_log_pub, const vehicle_status_flags_s &status_flags, const battery_status_s &battery, const safety_s &safety, const uint8_t arm_requirements, const hrt_abstime &time_since_boot)
Variables
static constexpr const char reason_no_rc [] = "no RC"
static constexpr const char reason_no_offboard [] = "no offboard"
static constexpr const char reason_no_rc_and_no_offboard [] = "no RC and no offboard"
static constexpr const char reason_no_local_position [] = "no local position"
static constexpr const char reason_no_global_position [] = "no global position"
static constexpr const char reason_no_datalink [] = "no datalink"
static constexpr const bool arming_transitions [vehicle_status_s::ARMING_STATE_MAX][vehicle_status_s::ARMING_STATE_MAX]
const char *const arming_state_names [vehicle_status_s::ARMING_STATE_MAX]
static hrt_abstime last_preflight_check = 0
initialize so it gets checked immediately
Detailed Description
State machine helper functions implementations.
Author
Thomas Gubler thoma.nosp@m.s@px.nosp@m.4.io
Julian Oes julia.nosp@m.n@oe.nosp@m.s.ch
Sander Smeets sande.nosp@m.r@dr.nosp@m.onesl.nosp@m.ab.c.nosp@m.om
Definition in file state_machine_helper.cpp.
Function Documentation
transition_result_t arming_state_transition (vehicle_status_s * status, const battery_status_s & battery, const safety_s & safety, const arming_state_t new_arming_state, actuator_armed_s * armed, const bool fRunPreArmChecks, orb_advert_t * mavlink_log_pub, vehicle_status_flags_s * status_flags, const uint8_t arm_requirements, const hrt_abstime & time_since_boot)
Definition at line 95 of file state_machine_helper.cpp.
References ARM_REQ_GPS_BIT, actuator_armed_s::armed, actuator_armed_s::armed_time_ms, vehicle_status_s::arming_state, arming_state_names, arming_transitions, vehicle_status_flags_s::condition_system_sensors_initialized, vehicle_status_s::hil_state, hrt_absolute_time(), hrt_elapsed_time(), last_preflight_check, actuator_armed_s::lockdown, mavlink_log_critical, prearm_check(), Preflight::preflightCheck(), actuator_armed_s::ready_to_arm, TRANSITION_CHANGED, TRANSITION_DENIED, and TRANSITION_NOT_CHANGED.
Referenced by arm_disarm(), StateMachineHelperTest::armingStateTransitionTest(), commander_low_prio_loop(), and Commander::run().
bool check_invalid_pos_nav_state (vehicle_status_s * status, bool old_failsafe, orb_advert_t * mavlink_log_pub, const vehicle_status_flags_s & status_flags, const bool use_rc, const bool using_global_pos)
Definition at line 799 of file state_machine_helper.cpp.
References vehicle_status_flags_s::condition_global_position_valid, vehicle_status_flags_s::condition_local_altitude_valid, vehicle_status_flags_s::condition_local_position_valid, vehicle_status_flags_s::condition_local_velocity_valid, enable_failsafe(), vehicle_status_s::is_rotary_wing, vehicle_status_s::nav_state, reason_no_global_position, and reason_no_local_position.
Referenced by set_nav_state().
void enable_failsafe (vehicle_status_s * status, bool old_failsafe, orb_advert_t * mavlink_log_pub, const char * reason)
Enable failsafe and report to user.
Definition at line 433 of file state_machine_helper.cpp.
References vehicle_status_s::arming_state, vehicle_status_s::failsafe, and mavlink_log_critical.
Referenced by check_invalid_pos_nav_state(), and set_nav_state().
transition_result_t hil_state_transition (hil_state_t new_state, orb_advert_t status_pub, vehicle_status_s * current_status, orb_advert_t * mavlink_log_pub)
Transition from one hil state to another.
Definition at line 374 of file state_machine_helper.cpp.
References vehicle_status_s::arming_state, vehicle_status_s::hil_state, hrt_absolute_time(), mavlink_log_critical, mavlink_log_info, ORB_ID, orb_publish(), param_find(), param_get(), PX4_WARN, vehicle_status_s::timestamp, TRANSITION_CHANGED, TRANSITION_DENIED, and TRANSITION_NOT_CHANGED.
Referenced by Commander::handle_command().
bool is_safe (const safety_s & safety, const actuator_armed_s & armed)
Definition at line 232 of file state_machine_helper.cpp.
References actuator_armed_s::armed, actuator_armed_s::lockdown, actuator_armed_s::manual_lockdown, safety_s::safety_off, and safety_s::safety_switch_available.
Referenced by commander_low_prio_loop(), and StateMachineHelperTest::isSafeTest().
transition_result_t main_state_transition (const vehicle_status_s & status, const main_state_t new_main_state, const vehicle_status_flags_s & status_flags, commander_state_s * internal_state)
Definition at line 244 of file state_machine_helper.cpp.
References vehicle_status_flags_s::condition_auto_mission_available, vehicle_status_flags_s::condition_global_position_valid, vehicle_status_flags_s::condition_home_position_valid, vehicle_status_flags_s::condition_local_altitude_valid, vehicle_status_flags_s::condition_local_position_valid, hrt_absolute_time(), vehicle_status_s::is_rotary_wing, commander_state_s::main_state, vehicle_status_flags_s::offboard_control_signal_lost, commander_state_s::timestamp, TRANSITION_CHANGED, TRANSITION_DENIED, and TRANSITION_NOT_CHANGED.
Referenced by commander_main(), Commander::handle_command(), StateMachineHelperTest::mainStateTransitionTest(), Commander::run(), set_link_loss_nav_state(), Commander::set_main_state_override_on(), and Commander::set_main_state_rc().
bool prearm_check (orb_advert_t * mavlink_log_pub, const vehicle_status_flags_s & status_flags, const battery_status_s & battery, const safety_s & safety, const uint8_t arm_requirements, const hrt_abstime & time_since_boot)
Definition at line 920 of file state_machine_helper.cpp.
References arm_auth_check(), ARM_REQ_ARM_AUTH_BIT, ARM_REQ_GPS_BIT, ARM_REQ_MISSION_BIT, vehicle_status_flags_s::circuit_breaker_engaged_power_check, vehicle_status_flags_s::circuit_breaker_engaged_usb_check, vehicle_status_flags_s::condition_auto_mission_available, vehicle_status_flags_s::condition_global_position_valid, vehicle_status_flags_s::condition_power_input_valid, mavlink_log_critical, safety_s::safety_off, safety_s::safety_switch_available, vehicle_status_flags_s::usb_connected, and battery_status_s::warning.
Referenced by arming_state_transition(), and commander_main().
void reset_link_loss_globals (actuator_armed_s * armed, const bool old_failsafe, const link_loss_actions_t link_loss_act)
Definition at line 908 of file state_machine_helper.cpp.
References actuator_armed_s::force_failsafe, actuator_armed_s::lockdown, LOCKDOWN, and TERMINATE.
Referenced by set_nav_state().
void set_link_loss_nav_state (vehicle_status_s * status, actuator_armed_s * armed, const vehicle_status_flags_s & status_flags, commander_state_s * internal_state, const link_loss_actions_t link_loss_act, uint8_t auto_recovery_nav_state)
Definition at line 858 of file state_machine_helper.cpp.
References AUTO_LAND, AUTO_LOITER, AUTO_RECOVER, AUTO_RTL, vehicle_status_flags_s::condition_global_position_valid, vehicle_status_flags_s::condition_home_position_valid, vehicle_status_flags_s::condition_local_altitude_valid, vehicle_status_flags_s::condition_local_position_valid, actuator_armed_s::force_failsafe, vehicle_status_s::is_rotary_wing, actuator_armed_s::lockdown, LOCKDOWN, main_state_transition(), vehicle_status_s::nav_state, and TERMINATE.
Referenced by set_nav_state().
bool set_nav_state (vehicle_status_s * status, actuator_armed_s * armed, commander_state_s * internal_state, orb_advert_t * mavlink_log_pub, const link_loss_actions_t data_link_loss_act, const bool mission_finished, const bool stay_in_failsafe, const vehicle_status_flags_s & status_flags, bool landed, const link_loss_actions_t rc_loss_act, const int offb_loss_act, const int offb_loss_rc_act, const int posctl_nav_loss_act)
Check failsafe and main status and set navigation status for navigator accordingly.
Definition at line 445 of file state_machine_helper.cpp.
References vehicle_status_s::arming_state, check_invalid_pos_nav_state(), vehicle_status_flags_s::condition_global_position_valid, vehicle_status_flags_s::condition_home_position_valid, vehicle_status_flags_s::condition_local_altitude_valid, vehicle_status_s::data_link_lost, DISABLED, enable_failsafe(), vehicle_status_s::engine_failure, vehicle_status_s::failsafe, vehicle_status_s::is_rotary_wing, commander_state_s::main_state, vehicle_status_s::mission_failure, vehicle_status_s::nav_state, vehicle_status_flags_s::offboard_control_loss_timeout, vehicle_status_flags_s::offboard_control_signal_lost, vehicle_status_s::rc_signal_lost, reason_no_datalink, reason_no_offboard, reason_no_rc, reason_no_rc_and_no_offboard, reset_link_loss_globals(), set_link_loss_nav_state(), and vehicle_status_flags_s::vtol_transition_failure.
Referenced by Commander::run().
Variable Documentation
const char* const arming_state_names[vehicle_status_s::ARMING_STATE_MAX]
Initial value:
= {
    "INIT",
    "STANDBY",
    "ARMED",
    "STANDBY_ERROR",
    "REBOOT",
    "IN_AIR_RESTORE",
}
Definition at line 78 of file state_machine_helper.cpp.
Referenced by arming_state_transition(), and print_status().
constexpr const bool arming_transitions[vehicle_status_s::ARMING_STATE_MAX][vehicle_status_s::ARMING_STATE_MAX] static
Initial value:
= {
    {            true,  true,    false, true,          false,  false },
    {         true,  true,    true,  false,         false,  false },
    {           false, true,    true,  false,         false,  true },
    {   true,  true,    true,  true,          false,  false },
    {          true,  true,    false, true,          true,   true },
    {  false, false,   false, false,         false,  false },
}
Definition at line 67 of file state_machine_helper.cpp.
Referenced by arming_state_transition().
hrt_abstime last_preflight_check = 0 static
initialize so it gets checked immediately
Definition at line 87 of file state_machine_helper.cpp.
Referenced by arming_state_transition().
constexpr const char reason_no_datalink[] = "no datalink" static
Definition at line 59 of file state_machine_helper.cpp.
Referenced by set_nav_state().
constexpr const char reason_no_global_position[] = "no global position" static
Definition at line 58 of file state_machine_helper.cpp.
Referenced by check_invalid_pos_nav_state().
constexpr const char reason_no_local_position[] = "no local position" static
Definition at line 57 of file state_machine_helper.cpp.
Referenced by check_invalid_pos_nav_state().
constexpr const char reason_no_offboard[] = "no offboard" static
Definition at line 55 of file state_machine_helper.cpp.
Referenced by set_nav_state().
constexpr const char reason_no_rc[] = "no RC" static
Definition at line 54 of file state_machine_helper.cpp.
Referenced by set_nav_state().
constexpr const char reason_no_rc_and_no_offboard[] = "no RC and no offboard" static
Definition at line 56 of file state_machine_helper.cpp.
Referenced by set_nav_state().