PX4 Firmware: src/drivers/boards/px4-same70xplained-v1/init.c File Reference
init.c File Reference
#include <px4_config.h>
#include <px4_tasks.h>
#include <stdbool.h>
#include <stdio.h>
#include <string.h>
#include <debug.h>
#include <errno.h>
#include "platform/cxxinitialize.h"
#include <nuttx/board.h>
#include <nuttx/spi/spi.h>
#include <nuttx/i2c/i2c_master.h>
#include <nuttx/sdio.h>
#include <nuttx/mmcsd.h>
#include <nuttx/analog/adc.h>
#include <sam_lowputc.h>
#include <sam_gpio.h>
#include <sam_spi.h>
#include <sam_hsmci.h>
#include <sam_pck.h>
#include <arch/board/board.h>
#include <drivers/drv_hrt.h>
#include <drivers/drv_board_led.h>
#include <systemlib/px4_macros.h>
#include <systemlib/cpuload.h>
#include <perf/perf_counter.h>
#include <systemlib/err.h>
#include <systemlib/hardfault_log.h>
#include <parameters/param.h>
Macros
#define message printf
Functions
__BEGIN_DECLS void led_init (void)
void led_on (int led)
void led_off (int led)
__END_DECLS __EXPORT void sam_boardinitialize (void)
__EXPORT int board_app_initialize (uintptr_t arg)
int up_rtc_getdatetime (FAR struct tm *tp)
int up_rtc_initialize (void)
int up_rtc_settime (FAR const struct timespec *tp)
Variables
static struct spi_dev_s * spi0
static struct sdio_dev_s * sdio
volatile bool g_rtc_enabled = false
Macro Definition Documentation
#define message printf
Definition at line 103 of file init.c.
Referenced by board_app_initialize().
Function Documentation
__EXPORT int board_app_initialize (uintptr_t arg)
Definition at line 235 of file init.c.
References board_autoled_on(), board_dma_alloc_init, drv_led_start(), hrt_init(), LED_AMBER, led_off(), led_on(), message, OK, param_init(), PX4_SPI_BUS_MEMORY, PX4_SPI_BUS_SENSORS, PX4_SPIDEV_ACCEL_MAG, PX4_SPIDEV_BARO, PX4_SPIDEV_EXT0, PX4_SPIDEV_EXT1, PX4_SPIDEV_GYRO, PX4_SPIDEV_MPU, sdio, spi0, spi1, and status.
__BEGIN_DECLS void led_init (void)
Definition at line 72 of file led.c.
void led_off (int led)
Definition at line 97 of file led.c.
void led_on (int led)
Definition at line 92 of file led.c.
__END_DECLS __EXPORT void sam_boardinitialize (void)
Definition at line 140 of file init.c.
References board_autoled_initialize(), board_spi_initialize(), sam_sdram_config, and UNUSED.
int up_rtc_getdatetime (FAR struct tm * tp)
Definition at line 350 of file init.c.
int up_rtc_initialize (void)
Definition at line 364 of file init.c.
int up_rtc_settime (FAR const struct timespec * tp)
Definition at line 369 of file init.c.
Variable Documentation
volatile bool g_rtc_enabled = false
Definition at line 347 of file init.c.
struct sdio_dev_s* sdio static
Definition at line 233 of file init.c.
Referenced by board_app_initialize().
struct spi_dev_s* spi0 static
Definition at line 229 of file init.c.
Referenced by board_app_initialize().