PX4 Firmware: src/drivers/distance_sensor/ll40ls/ll40ls.cpp File Reference
ll40ls.cpp File Reference
#include "LidarLiteI2C.h"
#include "LidarLitePWM.h"
#include <board_config.h>
#include <systemlib/err.h>
#include <fcntl.h>
#include <cstdlib>
#include <string.h>
#include <stdio.h>
#include <platforms/px4_getopt.h>
Classes
struct ll40ls_bus_option
Namespaces
ll40ls
Local functions in support of the shell command.
Macros
#define LL40LS_DEVICE_PATH_PWM "/dev/ll40ls_pwm"
Enumerations
enum LL40LS_BUS { LL40LS_BUS_I2C_ALL = 0, LL40LS_BUS_I2C_INTERNAL, LL40LS_BUS_I2C_EXTERNAL, LL40LS_BUS_PWM }
Functions
__EXPORT int ll40ls_main (int argc, char *argv[])
Driver 'main' command.
void ll40ls::start (enum LL40LS_BUS busid, uint8_t rotation)
Starts the driver.
void ll40ls::stop ()
Stops the driver.
void ll40ls::test ()
Performs some basic functional tests on the driver; make sure we can collect data from the sensor in polled and automatic modes.
void ll40ls::reset ()
Resets the driver.
void ll40ls::info ()
Prints status info about the driver.
void ll40ls::regdump ()
Dumps the register information.
void ll40ls::usage ()
Displays driver usage at the console.
Variables
static constexpr struct ll40ls_bus_option bus_options []
LidarLite * ll40ls::instance = nullptr
Detailed Description
Author
Allyson Kreft
Johan Jansen jnsn..nosp@m.joha.nosp@m.n@gma.nosp@m.il.c.nosp@m.om
Ban Siesta bansi.nosp@m.esta.nosp@m.@gmai.nosp@m.l.co.nosp@m.m
James Goppert james.nosp@m..gop.nosp@m.pert@.nosp@m.gmai.nosp@m.l.com
Interface for the PulsedLight Lidar-Lite range finders.
Definition in file ll40ls.cpp.
Macro Definition Documentation
#define LL40LS_DEVICE_PATH_PWM "/dev/ll40ls_pwm"
Definition at line 58 of file ll40ls.cpp.
Referenced by ll40ls::start().
Enumeration Type Documentation
enum LL40LS_BUS
Enumerator
LL40LS_BUS_I2C_ALL
LL40LS_BUS_I2C_INTERNAL
LL40LS_BUS_I2C_EXTERNAL
LL40LS_BUS_PWM
Definition at line 60 of file ll40ls.cpp.
Function Documentation
int ll40ls_main (int argc, char * argv[])
Driver 'main' command.
Definition at line 340 of file ll40ls.cpp.
References ll40ls_bus_option::busid, ll40ls::info(), LL40LS_BUS_I2C_ALL, LL40LS_BUS_I2C_EXTERNAL, LL40LS_BUS_I2C_INTERNAL, LL40LS_BUS_PWM, px4_getopt(), PX4_INFO, ll40ls::regdump(), ll40ls::reset(), ll40ls::start(), ll40ls::stop(), ll40ls::test(), ll40ls::usage(), and warnx.
Variable Documentation
constexpr struct ll40ls_bus_option bus_options[] static
Initial value:
= {
}
Referenced by ll40ls::start().