PX4 Firmware: control::BlockOutput Class Reference
control::BlockOutput Class Reference
An output trim/ saturation block.
#include <BlockOutput.hpp>
Public Member Functions
BlockOutput (SuperBlock *parent, const char *name)
virtual ~BlockOutput ()
void update (float input)
float getMin ()
float getMax ()
float getTrim ()
float get ()
Public Member Functions inherited from control::SuperBlock
SuperBlock (SuperBlock *parent, const char *name)
~SuperBlock ()=default
SuperBlock (const SuperBlock &)=delete
SuperBlock & operator= (const SuperBlock &)=delete
SuperBlock (SuperBlock &&)=delete
SuperBlock & operator= (SuperBlock &&)=delete
void setDt (float dt) override
void updateParams () override
void updateSubscriptions () override
void updatePublications () override
Public Member Functions inherited from control::Block
Block (SuperBlock *parent, const char *name)
virtual ~Block ()=default
Block (const Block &)=delete
Block & operator= (const Block &)=delete
Block (Block &&)=delete
Block & operator= (Block &&)=delete
void getName (char *name, size_t n)
float getDt ()
Public Member Functions inherited from ListNode< Block * >
ListNode ()
ListNode (const ListNode &)=delete
ListNode (ListNode &&)=delete
virtual ~ListNode ()=default
ListNode & operator= (const ListNode &)=delete
ListNode & operator= (ListNode &&)=delete
void setSibling (Block *sibling)
const Block * getSibling ()
Private Attributes
control::BlockParamFloat _trim
BlockLimit _limit
float _val
Additional Inherited Members
Protected Member Functions inherited from control::SuperBlock
List< Block * > & getChildren ()
void updateChildParams ()
void updateChildSubscriptions ()
void updateChildPublications ()
Protected Member Functions inherited from control::Block
virtual void updateParamsSubclass ()
SuperBlock * getParent ()
List< uORB::SubscriptionNode * > & getSubscriptions ()
List< uORB::PublicationNode * > & getPublications ()
List< BlockParamBase * > & getParams ()
Protected Attributes inherited from control::SuperBlock
List< Block * > _children
Protected Attributes inherited from control::Block
const char * _name
SuperBlock * _parent
float _dt {0.0f}
List< uORB::SubscriptionNode * > _subscriptions
List< uORB::PublicationNode * > _publications
List< BlockParamBase * > _params
Protected Attributes inherited from ListNode< Block * >
Block * _sibling
Detailed Description
An output trim/ saturation block.
Definition at line 60 of file BlockOutput.hpp.
Constructor & Destructor Documentation
control::BlockOutput::BlockOutput (SuperBlock * parent, const char * name) inline
Definition at line 64 of file BlockOutput.hpp.
virtual control::BlockOutput::~BlockOutput () inline virtual
Definition at line 73 of file BlockOutput.hpp.
Member Function Documentation
float control::BlockOutput::get () inline
Definition at line 82 of file BlockOutput.hpp.
Referenced by control::blockOutputTest(), and blockOutputTest().
float control::BlockOutput::getMax () inline
Definition at line 80 of file BlockOutput.hpp.
Referenced by control::blockOutputTest(), and blockOutputTest().
float control::BlockOutput::getMin () inline
Definition at line 79 of file BlockOutput.hpp.
Referenced by control::blockOutputTest(), and blockOutputTest().
float control::BlockOutput::getTrim () inline
Definition at line 81 of file BlockOutput.hpp.
void control::BlockOutput::update (float input) inline
Definition at line 74 of file BlockOutput.hpp.
Referenced by control::blockOutputTest(), and blockOutputTest().
Member Data Documentation
BlockLimit control::BlockOutput::_limit private
Definition at line 86 of file BlockOutput.hpp.
control::BlockParamFloat control::BlockOutput::_trim private
Definition at line 85 of file BlockOutput.hpp.
float control::BlockOutput::_val private
Definition at line 87 of file BlockOutput.hpp.
The documentation for this class was generated from the following file:
src/lib/controllib/BlockOutput.hpp