PX4 Firmware: control::BlockParamBase Class Reference
control::BlockParamBase Class Reference abstract
#include <BlockParam.hpp>
Public Member Functions
BlockParamBase (Block *parent, const char *name, bool parent_prefix=true)
Instantiate a block param base.
virtual ~BlockParamBase ()=default
virtual bool update ()=0
const char * getName () const
Public Member Functions inherited from ListNode< BlockParamBase * >
ListNode ()
ListNode (const ListNode &)=delete
ListNode (ListNode &&)=delete
virtual ~ListNode ()=default
ListNode & operator= (const ListNode &)=delete
ListNode & operator= (ListNode &&)=delete
void setSibling (BlockParamBase *sibling)
const BlockParamBase * getSibling ()
Protected Attributes
param_t _handle {PARAM_INVALID}
Protected Attributes inherited from ListNode< BlockParamBase * >
BlockParamBase * _sibling
Detailed Description
Definition at line 54 of file BlockParam.hpp.
Constructor & Destructor Documentation
control::BlockParamBase::BlockParamBase (Block * parent, const char * name, bool parent_prefix = true)
Instantiate a block param base.
Parameters
parent_prefix Set to true to include the parent name in the parameter name
Definition at line 49 of file BlockParam.cpp.
References _handle, control::blockNameLengthMax, control::Block::getName(), control::Block::getParams(), param_find(), PARAM_INVALID, and PX4_ERR.
virtual control::BlockParamBase::~BlockParamBase () virtual default
Member Function Documentation
const char* control::BlockParamBase::getName () const inline
Definition at line 66 of file BlockParam.hpp.
References _handle, and param_name().
virtual bool control::BlockParamBase::update () pure virtual
Implemented in control::BlockParam< T >, control::BlockParam< T >, control::BlockParam< float >, and control::BlockParam< T >.
Referenced by control::Block::updateParams().
Member Data Documentation
param_t control::BlockParamBase::_handle {PARAM_INVALID} protected
Definition at line 69 of file BlockParam.hpp.
Referenced by BlockParamBase(), control::BlockParam< float >::commit(), control::BlockParam< float >::commit_no_notification(), getName(), control::BlockParam< T >::update(), and control::BlockParam< float >::update().
The documentation for this class was generated from the following files:
src/lib/controllib/block/BlockParam.hpp
src/lib/controllib/block/BlockParam.cpp