PX4 Firmware: src/platforms/shmem.h File Reference
shmem.h File Reference
Classes
struct shmem_info
Macros
#define MAX_SHMEM_PARAMS 2000
#define PARAM_BUFFER_SIZE (MAX_SHMEM_PARAMS / 8 + 1)
#define MAP_ADDRESS 0xfbfc000
#define MAP_SIZE 16384
#define MAP_MASK (MAP_SIZE - 1)
#define LOCK_OFFSET 0
#define LOCK_SIZE 4
#define LOCK_MEM 1
#define UNLOCK_MEM 2
#define TYPE_MASK 0x1
Functions
struct shmem_info __attribute__ ((packed))
bool handle_in_range (param_t)
Test whether a param_t is value.
Variables
union param_value_u params_val [MAX_SHMEM_PARAMS]
unsigned char krait_changed_index [MAX_SHMEM_PARAMS/8+1]
unsigned char adsp_changed_index [MAX_SHMEM_PARAMS/8+1]
Macro Definition Documentation
#define LOCK_MEM 1
Definition at line 61 of file shmem.h.
#define LOCK_OFFSET 0
Definition at line 59 of file shmem.h.
#define LOCK_SIZE 4
Definition at line 60 of file shmem.h.
#define MAP_ADDRESS 0xfbfc000
Definition at line 54 of file shmem.h.
#define MAP_MASK (MAP_SIZE - 1)
Definition at line 57 of file shmem.h.
#define MAP_SIZE 16384
Definition at line 56 of file shmem.h.
#define MAX_SHMEM_PARAMS 2000
Definition at line 36 of file shmem.h.
#define PARAM_BUFFER_SIZE (MAX_SHMEM_PARAMS / 8 + 1)
Definition at line 38 of file shmem.h.
Referenced by px4muorb::KraitRpcWrapper::Initialize().
#define TYPE_MASK 0x1
Definition at line 64 of file shmem.h.
#define UNLOCK_MEM 2
Definition at line 62 of file shmem.h.
Function Documentation
struct shmem_info __attribute__ ((packed))
Definition at line 55 of file drv_adc.h.
bool handle_in_range (param_t param)
Test whether a param_t is value.
Parameters
param The parameter handle to test.
Returns
True if the handle is valid.
Definition at line 217 of file param_shmem.c.
References get_param_info_count().
Referenced by param_find_internal(), param_foreach(), param_get(), param_get_index(), param_get_value_ptr(), param_hash_check(), param_name(), param_reset(), param_reset_excludes(), param_set_internal(), param_size(), and param_type().
Variable Documentation
unsigned char adsp_changed_index[MAX_SHMEM_PARAMS/8+1]
Definition at line 53 of file shmem.h.
unsigned char krait_changed_index[MAX_SHMEM_PARAMS/8+1]
Definition at line 52 of file shmem.h.
union param_value_u params_val[MAX_SHMEM_PARAMS]
Definition at line 51 of file shmem.h.