PX4 Firmware: src/platforms/qurt/fc_addon/rc_receiver/rc_receiver_main.cpp File Reference
rc_receiver_main.cpp File Reference
#include <px4_getopt.h>
#include <px4_tasks.h>
#include <px4_log.h>
#include <string.h>
#include <drivers/drv_hrt.h>
#include <uORB/topics/input_rc.h>
#include <uORB/topics/parameter_update.h>
#include <drivers/drv_rc_input.h>
#include <semaphore.h>
#include "rc_receiver_api.h"
Namespaces
rc_receiver
Macros
#define MAX_LEN_DEV_PATH 32
#define SIGNAL_LOST_THRESHOLD_MS 500
Threshold value to detect rc receiver signal lost in millisecond.
Functions
__EXPORT int rc_receiver_main (int argc, char *argv[])
driver 'main' command
static void rc_receiver::usage ()
Print out the usage information.
static void rc_receiver::start ()
mpu9x50 start measurement
static void rc_receiver::stop ()
mpu9x50 stop measurement
static void rc_receiver::task_main_trampoline (int argc, char *argv[])
task main trampoline function
static void rc_receiver::task_main (int argc, char *argv[])
mpu9x50 measurement thread primary entry point
static void rc_receiver::parameters_update ()
update all parameters
static void rc_receiver::parameter_update_poll ()
poll parameter update
void rc_receiver::parameters_init ()
Variables
static char rc_receiver::_device [MAX_LEN_DEV_PATH]
serial device path that rc receiver is connected to
static bool rc_receiver::_is_running = false
flag indicating if rc_receiver module is running
static bool rc_receiver::_task_should_exit = false
flag indicating if task thread should exit
static px4_task_t rc_receiver::_task_handle = -1
handle to the task main thread
static enum RC_RECEIVER_TYPES rc_receiver::_rc_receiver_type
RC receiver type.
static uint16_t rc_receiver::rc_inputs [input_rc_s::RC_INPUT_MAX_CHANNELS]
RC input channel value array accomondating up to RC_INPUT_MAX_CHANNELS.
static orb_advert_t rc_receiver::_input_rc_pub = nullptr
rc_input uorb topic publication handle
static struct input_rc_s rc_receiver::_rc_in
rc_input uorb topic data
static int rc_receiver::_params_sub
struct {
param_t rc_receiver::rc_receiver_type
} rc_receiver::_params_handles
parameter handles
Macro Definition Documentation
#define MAX_LEN_DEV_PATH 32
Definition at line 55 of file rc_receiver_main.cpp.
Referenced by rc_receiver_main().
#define SIGNAL_LOST_THRESHOLD_MS 500
Threshold value to detect rc receiver signal lost in millisecond.
Definition at line 61 of file rc_receiver_main.cpp.
Referenced by rc_receiver::task_main().
Function Documentation
int rc_receiver_main (int argc, char * argv[])
driver 'main' command
Definition at line 287 of file rc_receiver_main.cpp.
References rc_receiver::_device, rc_receiver::_is_running, MAX_LEN_DEV_PATH, px4_getopt(), PX4_WARN, rc_receiver::start(), rc_receiver::stop(), and rc_receiver::usage().