PX4 Firmware: NavioADC Class Reference
NavioADC Class Reference
Public Member Functions
NavioADC ()
virtual ~NavioADC ()
virtual int init () override
virtual ssize_t devRead (void *buf, size_t count) override
virtual int devIOCTL (unsigned long request, unsigned long arg) override
Protected Member Functions
virtual void _measure () override
Private Member Functions
int read_channel (px4_adc_msg_t *adc_msg, int channel)
Private Attributes
pthread_mutex_t _samples_lock
int _fd [ADC_MAX_CHAN]
px4_adc_msg_t _samples [ADC_MAX_CHAN]
Detailed Description
Definition at line 77 of file navio_adc.cpp.
Constructor & Destructor Documentation
NavioADC::NavioADC ()
Definition at line 99 of file navio_adc.cpp.
References _fd, _samples_lock, ADC_MAX_CHAN, and pthread_mutex_init().
Referenced by navio_adc_main().
NavioADC::~NavioADC () virtual
Definition at line 109 of file navio_adc.cpp.
References _fd, _samples_lock, ADC_MAX_CHAN, and pthread_mutex_destroy().
Member Function Documentation
void NavioADC::_measure (void) override protected virtual
Definition at line 120 of file navio_adc.cpp.
References _samples, _samples_lock, ADC_BATTERY_CURRENT_CHANNEL, ADC_BATTERY_VOLTAGE_CHANNEL, ADC_MAX_CHAN, NAVIO_ADC_BATTERY_CURRENT_CHANNEL, NAVIO_ADC_BATTERY_VOLTAGE_CHANNEL, pthread_mutex_lock(), pthread_mutex_unlock(), px4_adc_msg_t, PX4_ERR, and read_channel().
int NavioADC::devIOCTL (unsigned long request, unsigned long arg) override virtual
Definition at line 192 of file navio_adc.cpp.
ssize_t NavioADC::devRead (void * buf, size_t count) override virtual
Definition at line 197 of file navio_adc.cpp.
References _samples, _samples_lock, and pthread_mutex_unlock().
Referenced by navio_adc_main().
int NavioADC::init () override virtual
Definition at line 153 of file navio_adc.cpp.
References _fd, ADC_MAX_CHAN, ADC_SYSFS_PATH, err, lis3mdl::init(), PX4_ERR, and PX4_OK.
Referenced by navio_adc_main().
int NavioADC::read_channel (px4_adc_msg_t * adc_msg, int channel) private
Definition at line 218 of file navio_adc.cpp.
References _fd, ADC_MAX_CHAN, PX4_ERR, and read().
Referenced by _measure().
Member Data Documentation
int NavioADC::_fd[ADC_MAX_CHAN] private
Definition at line 95 of file navio_adc.cpp.
Referenced by init(), NavioADC(), read_channel(), and ~NavioADC().
px4_adc_msg_t NavioADC::_samples[ADC_MAX_CHAN] private
Definition at line 96 of file navio_adc.cpp.
Referenced by _measure(), and devRead().
pthread_mutex_t NavioADC::_samples_lock private
Definition at line 94 of file navio_adc.cpp.
Referenced by _measure(), devRead(), NavioADC(), and ~NavioADC().
The documentation for this class was generated from the following file:
src/drivers/navio_adc/navio_adc.cpp