PX4 Firmware: src/lib/circuit_breaker/circuit_breaker.h File Reference
circuit_breaker.h File Reference
#include <stdint.h>
Macros
#define CBRK_SUPPLY_CHK_KEY 894281
#define CBRK_RATE_CTRL_KEY 140253
#define CBRK_IO_SAFETY_KEY 22027
#define CBRK_AIRSPD_CHK_KEY 162128
#define CBRK_FLIGHTTERM_KEY 121212
#define CBRK_ENGINEFAIL_KEY 284953
#define CBRK_GPSFAIL_KEY 240024
#define CBRK_USB_CHK_KEY 197848
#define CBRK_VELPOSERR_KEY 201607
Functions
__BEGIN_DECLS __EXPORT bool circuit_breaker_enabled (const char *breaker, int32_t magic)
Macro Definition Documentation
#define CBRK_AIRSPD_CHK_KEY 162128
Definition at line 55 of file circuit_breaker.h.
Referenced by get_circuit_breaker_params().
#define CBRK_ENGINEFAIL_KEY 284953
Definition at line 57 of file circuit_breaker.h.
Referenced by get_circuit_breaker_params().
#define CBRK_FLIGHTTERM_KEY 121212
Definition at line 56 of file circuit_breaker.h.
Referenced by get_circuit_breaker_params(), and PX4IO::task_main().
#define CBRK_GPSFAIL_KEY 240024
Definition at line 58 of file circuit_breaker.h.
Referenced by get_circuit_breaker_params().
#define CBRK_IO_SAFETY_KEY 22027
Definition at line 54 of file circuit_breaker.h.
Referenced by PX4IO::init(), and PX4FMU::init().
#define CBRK_RATE_CTRL_KEY 140253
Definition at line 53 of file circuit_breaker.h.
Referenced by MulticopterAttitudeControl::parameters_updated().
#define CBRK_SUPPLY_CHK_KEY 894281
Definition at line 52 of file circuit_breaker.h.
Referenced by get_circuit_breaker_params().
#define CBRK_USB_CHK_KEY 197848
Definition at line 59 of file circuit_breaker.h.
Referenced by get_circuit_breaker_params().
#define CBRK_VELPOSERR_KEY 201607
Definition at line 60 of file circuit_breaker.h.
Referenced by get_circuit_breaker_params().
Function Documentation
__BEGIN_DECLS __EXPORT bool circuit_breaker_enabled (const char * breaker, int32_t magic)
Definition at line 50 of file circuit_breaker.cpp.
Referenced by ToneAlarm::frequency_to_divisor(), get_circuit_breaker_params(), PX4IO::init(), PX4FMU::init(), MulticopterAttitudeControl::parameters_updated(), ToneAlarm::start_note(), and PX4IO::task_main().