PX4 Firmware: src/drivers/driver_framework_wrapper/df_hmc5883_wrapper/df_hmc5883_wrapper.cpp File Reference
df_hmc5883_wrapper.cpp File Reference
Lightweight driver to access the HMC5883 of the DriverFramework.
#include <px4_platform_common/px4_config.h>
#include <sys/types.h>
#include <sys/stat.h>
#include <stdint.h>
#include <stddef.h>
#include <stdlib.h>
#include <string.h>
#include <math.h>
#include <unistd.h>
#include <px4_platform_common/getopt.h>
#include <errno.h>
#include <lib/parameters/param.h>
#include <perf/perf_counter.h>
#include <systemlib/err.h>
#include <drivers/drv_mag.h>
#include <drivers/drv_hrt.h>
#include <uORB/topics/parameter_update.h>
#include <board_config.h>
#include <lib/conversion/rotation.h>
#include <hmc5883/HMC5883.hpp>
#include <DevMgr.hpp>
Classes
class DfHmc5883Wrapper
struct DfHmc5883Wrapper::mag_calibration_s
Namespaces
df_hmc5883_wrapper
Functions
__EXPORT int df_hmc5883_wrapper_main (int argc, char *argv[])
int df_hmc5883_wrapper::start (enum Rotation rotation, const char *path)
int df_hmc5883_wrapper::stop ()
Stop the driver.
int df_hmc5883_wrapper::info ()
Print a little info about the driver.
void df_hmc5883_wrapper::usage ()
Prints info about the driver argument usage.
Variables
DfHmc5883Wrapper * df_hmc5883_wrapper::g_dev = nullptr
Detailed Description
Lightweight driver to access the HMC5883 of the DriverFramework.
Author
Julian Oes julia.nosp@m.n@oe.nosp@m.s.ch
Definition in file df_hmc5883_wrapper.cpp.
Function Documentation
df_hmc5883_wrapper_main()
int df_hmc5883_wrapper_main (int argc, char * argv[])
Definition at line 410 of file df_hmc5883_wrapper.cpp.
References df_hmc5883_wrapper::info(), ROTATION_NONE, df_hmc5883_wrapper::start(), df_hmc5883_wrapper::stop(), and df_hmc5883_wrapper::usage().