PX4 Firmware: math::LowPassFilter2p Class Reference
math::LowPassFilter2p Class Reference
#include <LowPassFilter2p.hpp>
Public Member Functions
LowPassFilter2p (float sample_freq, float cutoff_freq)
void set_cutoff_frequency (float sample_freq, float cutoff_freq)
Change filter parameters.
float apply (float sample)
Add a new raw value to the filter.
float get_cutoff_freq () const
Return the cutoff frequency.
float reset (float sample)
Reset the filter state to this value.
Private Attributes
float _cutoff_freq
float _a1
float _a2
float _b0
float _b1
float _b2
float _delay_element_1
float _delay_element_2
Detailed Description
Definition at line 45 of file LowPassFilter2p.hpp.
Constructor & Destructor Documentation
math::LowPassFilter2p::LowPassFilter2p (float sample_freq, float cutoff_freq) inline
Definition at line 49 of file LowPassFilter2p.hpp.
Member Function Documentation
float math::LowPassFilter2p::apply (float sample)
Add a new raw value to the filter.
Returns
retrieve the filtered result
Definition at line 66 of file LowPassFilter2p.cpp.
References _a1, _a2, _b0, _b1, _b2, _cutoff_freq, _delay_element_1, _delay_element_2, and f().
Referenced by DfMpu9250Wrapper::_publish(), MS5525::collect(), SDP3X::collect(), MEASAirspeed::collect(), MEASAirspeedSim::collect(), BMI055_gyro::measure(), BMI055_accel::measure(), FXOS8701CQ::measure(), L3GD20::measure(), MPU6000::measure(), FXAS21002C::measure(), ADIS16448::measure(), LSM303D::measure(), BMI160::measure(), MPU9250::measure(), ADIS16477::publish_accel(), ADIS16477::publish_gyro(), sensors::RCUpdate::rc_poll(), reset(), and control::BlockLowPass2::update().
float math::LowPassFilter2p::get_cutoff_freq () const inline
Return the cutoff frequency.
Definition at line 78 of file LowPassFilter2p.hpp.
References bmp280::reset().
Referenced by ACCELSIM::devIOCTL(), ADIS16477::ioctl(), MPU6000::ioctl(), BMI055_gyro::ioctl(), BMI055_accel::ioctl(), FXOS8701CQ::ioctl(), ADIS16448::ioctl(), L3GD20::ioctl(), FXAS21002C::ioctl(), LSM303D::ioctl(), MPU9250::ioctl(), BMI160::ioctl(), MPU6000::print_info(), MPU9250::print_info(), and control::BlockLowPass2::update().
float math::LowPassFilter2p::reset (float sample)
Reset the filter state to this value.
Definition at line 90 of file LowPassFilter2p.cpp.
References _b0, _b1, _b2, _delay_element_1, _delay_element_2, and apply().
Referenced by MulticopterAttitudeControl::parameters_updated(), and sensors::RCUpdate::update_rc_functions().
void math::LowPassFilter2p::set_cutoff_frequency (float sample_freq, float cutoff_freq)
Change filter parameters.
Definition at line 47 of file LowPassFilter2p.cpp.
References _a1, _a2, _b0, _b1, _b2, _cutoff_freq, f(), and M_PI_F.
Referenced by ACCELSIM::accel_set_driver_lowpass_filter(), FXOS8701CQ::accel_set_driver_lowpass_filter(), LSM303D::accel_set_driver_lowpass_filter(), DfMpu9250Wrapper::DfMpu9250Wrapper(), MPU6000::init(), MPU9250::init(), ADIS16477::ioctl(), MPU6000::ioctl(), BMI055_gyro::ioctl(), BMI055_accel::ioctl(), ADIS16448::ioctl(), MPU9250::ioctl(), BMI160::ioctl(), MulticopterAttitudeControl::parameters_updated(), MulticopterAttitudeControl::run(), L3GD20::set_driver_lowpass_filter(), FXAS21002C::set_driver_lowpass_filter(), control::BlockLowPass2::update(), and sensors::RCUpdate::update_rc_functions().
Member Data Documentation
float math::LowPassFilter2p::_a1 private
Definition at line 90 of file LowPassFilter2p.hpp.
Referenced by apply(), and set_cutoff_frequency().
float math::LowPassFilter2p::_a2 private
Definition at line 91 of file LowPassFilter2p.hpp.
Referenced by apply(), and set_cutoff_frequency().
float math::LowPassFilter2p::_b0 private
Definition at line 92 of file LowPassFilter2p.hpp.
Referenced by apply(), reset(), and set_cutoff_frequency().
float math::LowPassFilter2p::_b1 private
Definition at line 93 of file LowPassFilter2p.hpp.
Referenced by apply(), reset(), and set_cutoff_frequency().
float math::LowPassFilter2p::_b2 private
Definition at line 94 of file LowPassFilter2p.hpp.
Referenced by apply(), reset(), and set_cutoff_frequency().
float math::LowPassFilter2p::_cutoff_freq private
Definition at line 89 of file LowPassFilter2p.hpp.
Referenced by apply(), and set_cutoff_frequency().
float math::LowPassFilter2p::_delay_element_1 private
Definition at line 95 of file LowPassFilter2p.hpp.
Referenced by apply(), and reset().
float math::LowPassFilter2p::_delay_element_2 private
Definition at line 96 of file LowPassFilter2p.hpp.
Referenced by apply(), and reset().
The documentation for this class was generated from the following files:
src/lib/mathlib/math/filter/LowPassFilter2p.hpp
src/lib/mathlib/math/filter/LowPassFilter2p.cpp