PX4 Firmware: src/modules/px4iofirmware/hx_stream.c File Reference
hx_stream.c File Reference
A simple serial line framing protocol based on HDLC with 32-bit CRC protection.
#include <stdint.h>
#include <stdlib.h>
#include <stdbool.h>
#include <crc32.h>
#include <unistd.h>
#include <errno.h>
#include <string.h>
#include <stdio.h>
#include <perf/perf_counter.h>
#include "hx_stream.h"
Classes
struct hx_stream
Macros
#define FBO 0x7e
Frame Boundary Octet.
#define CEO 0x7c
Control Escape Octet.
Functions
static void hx_tx_raw (hx_stream_t stream, uint8_t c)
static int hx_rx_frame (hx_stream_t stream)
hx_stream_t hx_stream_init (int fd, hx_stream_rx_callback callback, void *arg)
Allocate a new hx_stream object.
void hx_stream_free (hx_stream_t stream)
Free a hx_stream object.
void hx_stream_set_counters (hx_stream_t stream, perf_counter_t tx_frames, perf_counter_t rx_frames, perf_counter_t rx_errors)
Set performance counters for the stream.
void hx_stream_reset (hx_stream_t stream)
Reset a stream.
int hx_stream_start (hx_stream_t stream, const void *data, size_t count)
Prepare to send a frame.
int hx_stream_send_next (hx_stream_t stream)
Get the next byte to send for a stream.
int hx_stream_send (hx_stream_t stream, const void *data, size_t count)
Send a frame.
void hx_stream_rx (hx_stream_t stream, uint8_t c)
Handle a byte from the stream.
Detailed Description
A simple serial line framing protocol based on HDLC with 32-bit CRC protection.
Definition in file hx_stream.c.
Macro Definition Documentation
#define CEO 0x7c
Control Escape Octet.
Definition at line 86 of file hx_stream.c.
Referenced by hx_stream_rx(), and hx_stream_send_next().
#define FBO 0x7e
Frame Boundary Octet.
Definition at line 85 of file hx_stream.c.
Referenced by hx_stream_rx(), and hx_stream_send_next().
Function Documentation
static int hx_rx_frame (hx_stream_t stream) static
Definition at line 101 of file hx_stream.c.
References hx_stream::pc_rx_errors, hx_stream::pc_rx_frames, perf_count(), hx_stream::rx_buf, hx_stream::rx_callback, hx_stream::rx_callback_arg, hx_stream::rx_escaped, and hx_stream::rx_frame_bytes.
Referenced by hx_stream_rx().
void hx_stream_free (hx_stream_t stream)
Free a hx_stream object.
Parameters
stream A handle returned from hx_stream_init.
Definition at line 161 of file hx_stream.c.
References hx_stream::pc_rx_errors, hx_stream::pc_rx_frames, hx_stream::pc_tx_frames, and perf_free().
hx_stream_t hx_stream_init (int fd, hx_stream_rx_callback callback, void * arg)
Allocate a new hx_stream object.
Parameters
fd The file handle over which the protocol will communicate, or -1 if the protocol will use hx_stream_start/hx_stream_send_next.
callback Called when a frame is received.
callback_arg Passed to the callback.
Returns
A handle to the stream, or NULL if memory could not be allocated.
Definition at line 142 of file hx_stream.c.
References hx_stream::fd, hx_stream::rx_callback, and hx_stream::rx_callback_arg.
void hx_stream_reset (hx_stream_t stream)
Reset a stream.
Forces the local stream state to idle.
Parameters
stream A handle returned from hx_stream_init.
Definition at line 183 of file hx_stream.c.
References hx_stream::rx_escaped, hx_stream::rx_frame_bytes, hx_stream::tx_buf, hx_stream::TX_IDLE, hx_stream::tx_resid, and hx_stream::tx_state.
void hx_stream_rx (hx_stream_t stream, uint8_t c)
Handle a byte from the stream.
Parameters
stream A handle returned from hx_stream_init.
c The character to process.
Definition at line 299 of file hx_stream.c.
References CEO, FBO, hx_rx_frame(), hx_stream::rx_buf, hx_stream::rx_escaped, and hx_stream::rx_frame_bytes.
int hx_stream_send (hx_stream_t stream, const void * data, size_t count)
Send a frame.
This function will block until all frame bytes are sent if the descriptor passed to hx_stream_init is marked blocking, otherwise it will return -1 (but may transmit a runt frame at the same time).
Todo:
Handling of non-blocking streams needs to be better.
Parameters
stream A handle returned from hx_stream_init.
data Pointer to the data to send.
count The number of bytes to send.
Returns
Zero on success, -errno on error.
Definition at line 270 of file hx_stream.c.
References hx_stream_send_next(), hx_stream_start(), hx_tx_raw(), OK, hx_stream::pc_tx_frames, perf_count(), and hx_stream::tx_error.
int hx_stream_send_next (hx_stream_t stream)
Get the next byte to send for a stream.
This requires that the stream be prepared for sending by calling hx_stream_start first.
Parameters
stream A handle returned from hx_stream_init.
Returns
The byte to send, or -1 if there is nothing left to send.
Definition at line 210 of file hx_stream.c.
References CEO, FBO, hx_stream::tx_buf, hx_stream::tx_crc, hx_stream::TX_IDLE, hx_stream::tx_resid, hx_stream::TX_SEND_DATA, hx_stream::TX_SEND_END, hx_stream::TX_SEND_START, hx_stream::TX_SENT_ESCAPE, and hx_stream::tx_state.
Referenced by hx_stream_send().
void hx_stream_set_counters (hx_stream_t stream, perf_counter_t tx_frames, perf_counter_t rx_frames, perf_counter_t rx_errors)
Set performance counters for the stream.
Any counter may be set to NULL to disable counting that datum.
Parameters
stream A handle returned from hx_stream_init.
tx_frames Counter for transmitted frames.
rx_frames Counter for received frames.
rx_errors Counter for short and corrupt received frames.
Definition at line 172 of file hx_stream.c.
References hx_stream::pc_rx_errors, hx_stream::pc_rx_frames, and hx_stream::pc_tx_frames.
int hx_stream_start (hx_stream_t stream, const void * data, size_t count)
Prepare to send a frame.
Use this in conjunction with hx_stream_send_next to set the frame to be transmitted.
Use hx_stream_send() to write to the stream fd directly.
Parameters
stream A handle returned from hx_stream_init.
data Pointer to the data to send.
count The number of bytes to send.
Returns
Zero on success, -errno on error.
Definition at line 194 of file hx_stream.c.
References data, HX_STREAM_MAX_FRAME, OK, hx_stream::tx_buf, hx_stream::tx_crc, hx_stream::tx_resid, hx_stream::TX_SEND_START, and hx_stream::tx_state.
Referenced by hx_stream_send().
static void hx_tx_raw (hx_stream_t stream, uint8_t c) static
Definition at line 93 of file hx_stream.c.
References hx_stream::fd, hx_stream::tx_error, and write().
Referenced by hx_stream_send().