PX4 Firmware: PX4FMU Class Reference
PX4FMU Class Reference
Classes
struct GPIOConfig
Public Types
enum Mode {
MODE_NONE, MODE_1PWM, MODE_2PWM, MODE_2PWM2CAP,
MODE_3PWM, MODE_3PWM1CAP, MODE_4PWM, MODE_6PWM,
MODE_8PWM, MODE_14PWM, MODE_4CAP, MODE_5CAP,
MODE_6CAP
}
Public Types inherited from device::Device
enum DeviceBusType { DeviceBusType_UNKNOWN = 0, DeviceBusType_I2C = 1, DeviceBusType_SPI = 2, DeviceBusType_UAVCAN = 3 }
Device bus types for DEVID.
Public Member Functions
PX4FMU (bool run_as_task)
virtual ~PX4FMU ()
void run () override
void cycle ()
run the main loop: if running as task, continuously iterate, otherwise execute only one single cycle
int print_status () override
virtual int ioctl (file *filp, int cmd, unsigned long arg)
virtual ssize_t write (file *filp, const char *buffer, size_t len)
virtual int init ()
Initialise the driver and make it ready for use.
int set_mode (Mode mode)
Mode get_mode ()
int set_pwm_alt_rate (unsigned rate)
int set_pwm_alt_channels (uint32_t channels)
void update_pwm_trims ()
Public Member Functions inherited from device::CDev
CDev (const char *name, const char *devname)
Constructor.
virtual ~CDev ()
virtual int open (file_t *filep)
Handle an open of the device.
virtual int close (file_t *filep)
Handle a close of the device.
virtual ssize_t read (file_t *filep, char *buffer, size_t buflen)
Perform a read from the device.
virtual ssize_t write (file_t *filep, const char *buffer, size_t buflen)
Perform a write to the device.
virtual off_t seek (file_t *filep, off_t offset, int whence)
Perform a logical seek operation on the device.
virtual int ioctl (file_t *filep, int cmd, unsigned long arg)
Perform an ioctl operation on the device.
virtual int poll (file_t *filep, px4_pollfd_struct_t *fds, bool setup)
Perform a poll setup/teardown operation.
Public Member Functions inherited from device::Device
virtual ~Device ()=default
Destructor.
virtual int read (unsigned address, void *data, unsigned count)
Read directly from the device.
virtual int write (unsigned address, void *data, unsigned count)
Write directly to the device.
virtual int ioctl (unsigned operation, unsigned &arg)
Perform a device-specific operation.
uint8_t get_device_bus ()
Return the bus ID the device is connected to.
DeviceBusType get_device_bus_type ()
Return the bus type the device is connected to.
uint8_t get_device_address ()
Return the bus address of the device.
void set_device_address (int address)
void set_device_type (uint8_t devtype)
Set the device type.
virtual bool external ()
Static Public Member Functions
static int task_spawn (int argc, char *argv[])
static PX4FMU * instantiate (int argc, char *argv[])
static int custom_command (int argc, char *argv[])
static int print_usage (const char *reason=nullptr)
static int fmu_new_mode (PortMode new_mode)
change the FMU mode of the running module
static int test ()
static int fake (int argc, char *argv[])
static int set_i2c_bus_clock (unsigned bus, unsigned clock_hz)
static void capture_trampoline (void *context, uint32_t chan_index, hrt_abstime edge_time, uint32_t edge_state, uint32_t overflow)
Private Types
enum MotorOrdering : int32_t { MotorOrdering::PX4 = 0, MotorOrdering::Betaflight = 1 }
Private Member Functions
int start ()
void capture_callback (uint32_t chan_index, hrt_abstime edge_time, uint32_t edge_state, uint32_t overflow)
void subscribe ()
int set_pwm_rate (unsigned rate_map, unsigned default_rate, unsigned alt_rate)
int pwm_ioctl (file *filp, int cmd, unsigned long arg)
void update_pwm_rev_mask ()
void update_pwm_out_state (bool on)
void update_params ()
int gpio_reset (void)
int gpio_set_function (uint32_t gpios, int function)
int gpio_write (uint32_t gpios, int function)
int gpio_read (uint32_t *value)
int gpio_ioctl (file *filp, int cmd, unsigned long arg)
int capture_ioctl (file *filp, int cmd, unsigned long arg)
PX4FMU (const PX4FMU &)=delete
PX4FMU operator= (const PX4FMU &)=delete
void safety_check_button (void)
void flash_safety_button (void)
void reorder_outputs (uint16_t values[MAX_ACTUATORS])
Reorder PWM outputs according to _motor_ordering.
Static Private Member Functions
static bool arm_nothrottle ()
static void cycle_trampoline (void *arg)
static int control_callback (uintptr_t handle, uint8_t control_group, uint8_t control_index, float &input)
static void sensor_reset (int ms)
static void peripheral_reset (int ms)
Private Attributes
hrt_abstime _cycle_timestamp = 0
hrt_abstime _last_safety_check = 0
hrt_abstime _time_last_mix = 0
Mode _mode
unsigned _pwm_default_rate
unsigned _pwm_alt_rate
uint32_t _pwm_alt_rate_channels
unsigned _current_update_rate
bool _run_as_task
int _armed_sub
int _param_sub
int _safety_sub
orb_advert_t _outputs_pub
unsigned _num_outputs
int _class_instance
bool _throttle_armed
bool _pwm_on
uint32_t _pwm_mask
bool _pwm_initialized
MixerGroup * _mixers
uint32_t _groups_required
uint32_t _groups_subscribed
int _control_subs [actuator_controls_s::NUM_ACTUATOR_CONTROL_GROUPS]
actuator_controls_s _controls [actuator_controls_s::NUM_ACTUATOR_CONTROL_GROUPS]
orb_id_t _control_topics [actuator_controls_s::NUM_ACTUATOR_CONTROL_GROUPS]
pollfd _poll_fds [actuator_controls_s::NUM_ACTUATOR_CONTROL_GROUPS]
unsigned _poll_fds_num
uint16_t _failsafe_pwm [_max_actuators]
uint16_t _disarmed_pwm [_max_actuators]
uint16_t _min_pwm [_max_actuators]
uint16_t _max_pwm [_max_actuators]
uint16_t _reverse_pwm_mask
unsigned _num_failsafe_set
unsigned _num_disarmed_set
bool _safety_off
State of the safety button from the subscribed safety topic.
bool _safety_btn_off
State of the safety button read from the HW button.
bool _safety_disabled
orb_advert_t _to_safety
orb_advert_t _to_mixer_status
mixer status flags
float _mot_t_max
maximum rise time for motor (slew rate limiting)
float _thr_mdl_fac
thrust to pwm modelling factor
bool _airmode
multicopter air-mode
MotorOrdering _motor_ordering
perf_counter_t _perf_control_latency
Static Private Attributes
static const unsigned _max_actuators = DIRECT_PWM_OUTPUT_CHANNELS
static struct work_s _work = {}
static pwm_limit_t _pwm_limit
static actuator_armed_s _armed = {}
Additional Inherited Members
Protected Member Functions inherited from device::CDev
virtual pollevent_t poll_state (file_t *filep)
Check the current state of the device for poll events from the perspective of the file.
virtual void poll_notify (pollevent_t events)
Report new poll events.
virtual void poll_notify_one (px4_pollfd_struct_t *fds, pollevent_t events)
Internal implementation of poll_notify.
virtual int open_first (file_t *filep)
Notification of the first open.
virtual int close_last (file_t *filep)
Notification of the last close.
virtual int register_class_devname (const char *class_devname)
Register a class device name, automatically adding device class instance suffix if need be.
virtual int unregister_class_devname (const char *class_devname, unsigned class_instance)
Register a class device name, automatically adding device class instance suffix if need be.
const char * get_devname ()
Get the device name.
void lock ()
Take the driver lock.
void unlock ()
Release the driver lock.
Protected Member Functions inherited from device::Device
Device (const char *name)
Device (DeviceBusType bus_type, uint8_t bus, uint8_t address, uint8_t devtype=0)
Device (const Device &)=delete
Device & operator= (const Device &)=delete
Device (Device &&)=delete
Device & operator= (Device &&)=delete
Protected Attributes inherited from device::CDev
px4_sem_t _lock
lock to protect access to all class members (also for derived classes)
bool _pub_blocked {false}
true if publishing should be blocked
Protected Attributes inherited from device::Device
union DeviceId _device_id
device identifier information
const char * _name
driver name
bool _debug_enabled {false}
if true, debug messages are printed
Static Protected Attributes inherited from device::CDev
static const px4_file_operations_t fops = {}
Pointer to the default cdev file operations table; useful for registering clone devices etc.
Detailed Description
Definition at line 99 of file fmu.cpp.
Member Enumeration Documentation
enum PX4FMU::Mode
Enumerator
MODE_NONE
MODE_1PWM
MODE_2PWM
MODE_2PWM2CAP
MODE_3PWM
MODE_3PWM1CAP
MODE_4PWM
MODE_6PWM
MODE_8PWM
MODE_14PWM
MODE_4CAP
MODE_5CAP
MODE_6CAP
Definition at line 102 of file fmu.cpp.
enum PX4FMU::MotorOrdering : int32_t strong private
Enumerator
PX4
Betaflight
Definition at line 171 of file fmu.cpp.
Constructor & Destructor Documentation
PX4FMU::PX4FMU (bool run_as_task)
Definition at line 299 of file fmu.cpp.
References _airmode, _armed, _control_subs, _control_topics, _controls, device::Device::_debug_enabled, _disarmed_pwm, _max_actuators, _max_pwm, _min_pwm, _mot_t_max, _motor_ordering, _num_disarmed_set, _num_failsafe_set, _perf_control_latency, _poll_fds, _reverse_pwm_mask, _safety_btn_off, _safety_disabled, _safety_off, _thr_mdl_fac, _to_mixer_status, _to_safety, actuator_armed_s::armed, f(), actuator_armed_s::force_failsafe, actuator_armed_s::in_esc_calibration_mode, actuator_armed_s::lockdown, ORB_ID, PC_ELAPSED, perf_alloc, actuator_armed_s::prearmed, PWM_DEFAULT_MAX, PWM_DEFAULT_MIN, PX4, and actuator_armed_s::ready_to_arm.
Referenced by cycle_trampoline(), and instantiate().
PX4FMU::~PX4FMU () virtual
Definition at line 372 of file fmu.cpp.
References _armed_sub, _class_instance, _control_subs, _outputs_pub, _param_sub, _perf_control_latency, _safety_sub, _to_mixer_status, _to_safety, orb_unadvertise(), orb_unsubscribe(), perf_free(), PWM_OUTPUT_BASE_DEVICE_PATH, device::CDev::unregister_class_devname(), and up_pwm_servo_deinit().
PX4FMU::PX4FMU (const PX4FMU &) private delete
Member Function Documentation
static bool PX4FMU::arm_nothrottle () inline static private
Definition at line 235 of file fmu.cpp.
References actuator_armed_s::armed, capture_callback(), control_callback(), cycle_trampoline(), file, hrt_abstime, actuator_armed_s::in_esc_calibration_mode, actuator_armed_s::prearmed, pwm_ioctl(), set_pwm_rate(), start(), subscribe(), update_params(), update_pwm_out_state(), and update_pwm_rev_mask().
Referenced by control_callback(), and cycle().
void PX4FMU::capture_callback (uint32_t chan_index, hrt_abstime edge_time, uint32_t edge_state, uint32_t overflow) private
Definition at line 1006 of file fmu.cpp.
Referenced by arm_nothrottle(), and capture_trampoline().
int PX4FMU::capture_ioctl (file * filp, int cmd, unsigned long arg) private
Definition at line 2316 of file fmu.cpp.
References _mode, input_capture_config_t::callback, input_capture_stats_t::chan_in_edges_out, input_capture_config_t::channel, input_capture_config_t::context, input_capture_config_t::edge, input_capture_config_t::filter, INPUT_CAP_GET_CALLBACK, INPUT_CAP_GET_CLR_STATS, INPUT_CAP_GET_COUNT, INPUT_CAP_GET_EDGE, INPUT_CAP_GET_FILTER, INPUT_CAP_GET_STATS, INPUT_CAP_SET, INPUT_CAP_SET_CALLBACK, INPUT_CAP_SET_COUNT, INPUT_CAP_SET_EDGE, INPUT_CAP_SET_FILTER, device::CDev::lock(), MODE_2PWM2CAP, MODE_3PWM1CAP, OK, set_mode(), device::CDev::unlock(), up_input_capture_get_callback(), up_input_capture_get_filter(), up_input_capture_get_stats(), up_input_capture_get_trigger(), up_input_capture_set(), up_input_capture_set_callback(), up_input_capture_set_filter(), and up_input_capture_set_trigger().
Referenced by ioctl().
void PX4FMU::capture_trampoline (void * context, uint32_t chan_index, hrt_abstime edge_time, uint32_t edge_state, uint32_t overflow) static
Definition at line 998 of file fmu.cpp.
References capture_callback().
Referenced by get_mode(), and test().
int PX4FMU::control_callback (uintptr_t handle, uint8_t control_group, uint8_t control_index, float & input) static private
Definition at line 1382 of file fmu.cpp.
References _armed, _pwm_limit, arm_nothrottle(), actuator_controls_s::control, f(), actuator_armed_s::in_esc_calibration_mode, PWM_LIMIT_STATE_RAMP, and pwm_limit_t::state.
Referenced by arm_nothrottle(), and pwm_ioctl().
int PX4FMU::custom_command (int argc, char * argv[]) static
See also
ModuleBase
Definition at line 2830 of file fmu.cpp.
References fake(), fmu_new_mode(), is_running(), peripheral_reset(), PORT_FULL_GPIO, PORT_FULL_PWM, PORT_MODE_UNSET, PORT_PWM1, PORT_PWM2, PORT_PWM2CAP2, PORT_PWM3, PORT_PWM3CAP1, PORT_PWM4, PORT_PWM6, print_usage(), PX4_ERR, PX4_INFO, sensor_reset(), task_spawn(), and test().
void PX4FMU::cycle ()
run the main loop: if running as task, continuously iterate, otherwise execute only one single cycle
Definition at line 1037 of file fmu.cpp.
References _airmode, _armed, _armed_sub, _class_instance, _control_subs, _control_topics, _controls, _current_update_rate, _cycle_timestamp, _disarmed_pwm, _failsafe_pwm, _groups_required, _groups_subscribed, _last_safety_check, _max_actuators, _max_pwm, _min_pwm, _mixers, _mot_t_max, _num_disarmed_set, _num_outputs, _outputs_pub, _param_sub, _perf_control_latency, _poll_fds, _poll_fds_num, _pwm_alt_rate, _pwm_default_rate, _pwm_initialized, _pwm_limit, _pwm_on, _reverse_pwm_mask, _run_as_task, _safety_btn_off, _safety_disabled, _safety_off, _safety_sub, _thr_mdl_fac, _throttle_armed, _time_last_mix, _to_mixer_status, _to_safety, arm_nothrottle(), actuator_armed_s::armed, actuator_controls_s::control, cycle_trampoline(), DEVICE_LOG, dt, f(), MultirotorMixer::saturation_status::flags, flash_safety_button(), actuator_armed_s::force_failsafe, MixerGroup::get_saturation_status(), hrt_absolute_time(), hrt_abstime, actuator_armed_s::in_esc_calibration_mode, instance, actuator_armed_s::lockdown, actuator_armed_s::manual_lockdown, MAX_ACTUATORS, MixerGroup::mix(), actuator_outputs_s::noutputs, orb_advertise_multi(), orb_check(), orb_copy(), ORB_ID, ORB_PRIO_DEFAULT, orb_publish(), orb_publish_auto(), orb_set_interval(), actuator_outputs_s::output, perf_set_elapsed(), pwm_limit_calc(), PWM_LIMIT_STATE_ON, PX4_DEBUG, PX4_MFT_HW_SUPPORTED, PX4_MFT_PX4IO, px4_poll(), reorder_outputs(), safety, safety_check_button(), safety_s::safety_off, safety_s::safety_switch_available, multirotor_motor_limits_s::saturation_status, SCHEDULE_INTERVAL, MixerGroup::set_airmode(), MixerGroup::set_max_delta_out_once(), MixerGroup::set_thrust_factor(), pwm_limit_t::state, subscribe(), multirotor_motor_limits_s::timestamp, safety_s::timestamp, actuator_outputs_s::timestamp, actuator_controls_s::timestamp_sample, up_pwm_servo_set(), up_pwm_update(), update_params(), update_pwm_out_state(), MultirotorMixer::saturation_status::valid, and MultirotorMixer::saturation_status::value.
Referenced by cycle_trampoline(), and run().
void PX4FMU::cycle_trampoline (void * arg) static private
Definition at line 972 of file fmu.cpp.
References cycle(), init(), PX4_ERR, and PX4FMU().
Referenced by arm_nothrottle(), cycle(), and task_spawn().
int PX4FMU::fake (int argc, char * argv[]) static
Definition at line 2782 of file fmu.cpp.
References actuator_armed_s::armed, actuator_controls_s::control, actuator_armed_s::lockdown, orb_advert_t, orb_advertise(), ORB_ID, ORB_ID_VEHICLE_ATTITUDE_CONTROLS, orb_unadvertise(), print_usage(), and PX4_ERR.
Referenced by custom_command().
void PX4FMU::flash_safety_button (void) private
Definition at line 498 of file fmu.cpp.
References _armed, _safety_btn_off, actuator_armed_s::armed, blink_counter, GPIO_LED_SAFETY, LED_PATTERN_FMU_ARMED, LED_PATTERN_FMU_OK_TO_ARM, LED_PATTERN_FMU_REFUSE_TO_ARM, LED_PATTERN_IO_ARMED, LED_PATTERN_IO_FMU_ARMED, PX4_MFT_HW_SUPPORTED, and PX4_MFT_PX4IO.
Referenced by cycle().
int PX4FMU::fmu_new_mode (PortMode new_mode) static
change the FMU mode of the running module
Definition at line 2482 of file fmu.cpp.
References get_mode(), GPIO_RESET, is_running(), MODE_14PWM, MODE_1PWM, MODE_2PWM, MODE_2PWM2CAP, MODE_3PWM, MODE_3PWM1CAP, MODE_4PWM, MODE_6PWM, MODE_8PWM, MODE_NONE, OK, PORT_FULL_GPIO, PORT_FULL_PWM, PORT_MODE_UNSET, PORT_PWM1, PORT_PWM2, PORT_PWM2CAP2, PORT_PWM3, PORT_PWM3CAP1, PORT_PWM4, PORT_PWM6, and set_i2c_bus_clock().
Referenced by custom_command().
Mode PX4FMU::get_mode () inline
Definition at line 156 of file fmu.cpp.
References _mode, capture_trampoline(), hrt_abstime, set_i2c_bus_clock(), set_pwm_alt_channels(), set_pwm_alt_rate(), and update_pwm_trims().
Referenced by fmu_new_mode().
int PX4FMU::gpio_ioctl (file * filp, int cmd, unsigned long arg) private
Definition at line 2451 of file fmu.cpp.
References GPIO_CLEAR, GPIO_RESET, gpio_reset(), GPIO_SET, gpio_set_function(), GPIO_SET_OUTPUT, gpio_write(), device::CDev::lock(), OK, and device::CDev::unlock().
Referenced by ioctl().
int PX4FMU::gpio_read (uint32_t * value) private
Definition at line 2297 of file fmu.cpp.
References OK.
int PX4FMU::gpio_reset (void) private
Definition at line 2222 of file fmu.cpp.
References OK.
Referenced by gpio_ioctl().
int PX4FMU::gpio_set_function (uint32_t gpios, int function) private
Definition at line 2251 of file fmu.cpp.
References GPIO_SET_OUTPUT, and OK.
Referenced by gpio_ioctl().
int PX4FMU::gpio_write (uint32_t gpios, int function) private
Definition at line 2277 of file fmu.cpp.
References GPIO_SET, and OK.
Referenced by gpio_ioctl().
int PX4FMU::init () virtual
Initialise the driver and make it ready for use.
Returns
OK if the driver initialized OK, negative errno otherwise;
Reimplemented from device::CDev.
Definition at line 400 of file fmu.cpp.
References _armed_sub, _class_instance, _current_update_rate, _param_sub, _pwm_limit, _safety_btn_off, _safety_disabled, _safety_off, _safety_sub, CBRK_IO_SAFETY_KEY, circuit_breaker_enabled(), CLASS_DEVICE_PRIMARY, lis3mdl::init(), OK, ORB_ID, orb_subscribe(), pwm_limit_init(), PWM_OUTPUT_BASE_DEVICE_PATH, PX4_ERR, device::CDev::register_class_devname(), safety, and update_params().
Referenced by cycle_trampoline(), and run().
PX4FMU * PX4FMU::instantiate (int argc, char * argv[]) static
See also
ModuleBase
Definition at line 2824 of file fmu.cpp.
References PX4FMU().
int PX4FMU::ioctl (file * filp, int cmd, unsigned long arg) virtual
Definition at line 1425 of file fmu.cpp.
References _mode, capture_ioctl(), gpio_ioctl(), MODE_14PWM, MODE_1PWM, MODE_2PWM, MODE_2PWM2CAP, MODE_3PWM, MODE_3PWM1CAP, MODE_4PWM, MODE_6PWM, MODE_8PWM, pwm_ioctl(), and PX4_DEBUG.
Referenced by test().
PX4FMU PX4FMU::operator= (const PX4FMU &) private delete
void PX4FMU::peripheral_reset (int ms) static private
Definition at line 2212 of file fmu.cpp.
References board_peripheral_reset.
Referenced by custom_command().
int PX4FMU::print_status () override
See also
ModuleBase::print_status()
Definition at line 3025 of file fmu.cpp.
References _current_update_rate, _mode, _run_as_task, _safety_btn_off, fmu_main(), MODE_1PWM, MODE_2PWM, MODE_2PWM2CAP, MODE_3PWM, MODE_3PWM1CAP, MODE_4CAP, MODE_4PWM, MODE_5CAP, MODE_6CAP, MODE_6PWM, MODE_8PWM, MODE_NONE, PX4_INFO, PX4_MFT_HW_SUPPORTED, and PX4_MFT_PX4IO.
int PX4FMU::print_usage (const char * reason = nullptr) static
See also
ModuleBase
Definition at line 2946 of file fmu.cpp.
References PRINT_MODULE_DESCRIPTION(), PRINT_MODULE_USAGE_ARG(), PRINT_MODULE_USAGE_COMMAND, PRINT_MODULE_USAGE_COMMAND_DESCR(), PRINT_MODULE_USAGE_DEFAULT_COMMANDS, PRINT_MODULE_USAGE_NAME(), PRINT_MODULE_USAGE_PARAM_COMMENT(), PRINT_MODULE_USAGE_PARAM_FLAG(), and PX4_WARN.
Referenced by custom_command(), and fake().
int PX4FMU::pwm_ioctl (file * filp, int cmd, unsigned long arg) private
Definition at line 1477 of file fmu.cpp.
References _controls, _disarmed_pwm, _failsafe_pwm, _groups_required, _max_actuators, _max_pwm, _min_pwm, _mixers, _mode, _num_disarmed_set, _num_failsafe_set, _pwm_alt_rate, _pwm_alt_rate_channels, _pwm_default_rate, _safety_btn_off, MixerGroup::add_mixer(), pwm_output_values::channel_count, SimpleMixer::check(), control_callback(), MixerGroup::get_trims(), MixerGroup::groups_required(), MixerGroup::load_from_buf(), device::CDev::lock(), uart_esc::mixer, MIXERIOCADDSIMPLE, MIXERIOCGETOUTPUTCOUNT, MIXERIOCLOADBUF, MIXERIOCRESET, MODE_14PWM, MODE_1PWM, MODE_2PWM, MODE_2PWM2CAP, MODE_3PWM, MODE_3PWM1CAP, MODE_4CAP, MODE_4PWM, MODE_5CAP, MODE_6CAP, MODE_6PWM, MODE_8PWM, MODE_NONE, OK, PWM_HIGHEST_MAX, PWM_HIGHEST_MIN, PWM_LOWEST_MAX, PWM_LOWEST_MIN, PWM_SERVO_ARM, PWM_SERVO_CLEAR_ARM_OK, PWM_SERVO_DISARM, PWM_SERVO_GET, PWM_SERVO_GET_COUNT, PWM_SERVO_GET_DEFAULT_UPDATE_RATE, PWM_SERVO_GET_DISARMED_PWM, PWM_SERVO_GET_FAILSAFE_PWM, PWM_SERVO_GET_MAX_PWM, PWM_SERVO_GET_MIN_PWM, PWM_SERVO_GET_RATEGROUP, PWM_SERVO_GET_SELECT_UPDATE_RATE, PWM_SERVO_GET_TRIM_PWM, PWM_SERVO_GET_UPDATE_RATE, PWM_SERVO_MODE_1PWM, PWM_SERVO_MODE_2PWM, PWM_SERVO_MODE_2PWM2CAP, PWM_SERVO_MODE_3PWM, PWM_SERVO_MODE_3PWM1CAP, PWM_SERVO_MODE_4CAP, PWM_SERVO_MODE_4PWM, PWM_SERVO_MODE_5CAP, PWM_SERVO_MODE_6CAP, PWM_SERVO_MODE_6PWM, PWM_SERVO_MODE_8PWM, PWM_SERVO_MODE_NONE, PWM_SERVO_SET, PWM_SERVO_SET_ARM_OK, PWM_SERVO_SET_COUNT, PWM_SERVO_SET_DISARMED_PWM, PWM_SERVO_SET_FAILSAFE_PWM, PWM_SERVO_SET_FORCE_SAFETY_OFF, PWM_SERVO_SET_FORCE_SAFETY_ON, PWM_SERVO_SET_MAX_PWM, PWM_SERVO_SET_MIN_PWM, PWM_SERVO_SET_MODE, PWM_SERVO_SET_SELECT_UPDATE_RATE, PWM_SERVO_SET_TRIM_PWM, PWM_SERVO_SET_UPDATE_RATE, PX4_DEBUG, set_mode(), set_pwm_rate(), MixerGroup::set_trims(), device::CDev::unlock(), up_pwm_servo_get(), up_pwm_servo_get_rate_group(), up_pwm_servo_set(), update_pwm_out_state(), update_pwm_trims(), and pwm_output_values::values.
Referenced by arm_nothrottle(), and ioctl().
void PX4FMU::reorder_outputs (uint16_t values[MAX_ACTUATORS]) inline private
Reorder PWM outputs according to _motor_ordering.
Parameters
values PWM values to reorder
Definition at line 2174 of file fmu.cpp.
References _motor_ordering, Betaflight, and pwm_output_values::values.
Referenced by cycle(), and write().
void PX4FMU::run () override
See also
ModuleBase::run()
Definition at line 1025 of file fmu.cpp.
References cycle(), init(), and PX4_ERR.
void PX4FMU::safety_check_button (void) private
Definition at line 446 of file fmu.cpp.
References _safety_btn_off, counter, CYCLE_COUNT, GPIO_BTN_SAFETY, PX4_MFT_HW_SUPPORTED, PX4_MFT_PX4IO, and safety_button_pressed.
Referenced by cycle().
void PX4FMU::sensor_reset (int ms) static private
Definition at line 2202 of file fmu.cpp.
References board_spi_reset.
Referenced by custom_command().
int PX4FMU::set_i2c_bus_clock (unsigned bus, unsigned clock_hz) static
Definition at line 793 of file fmu.cpp.
Referenced by fmu_new_mode(), and get_mode().
int PX4FMU::set_mode (Mode mode)
Definition at line 537 of file fmu.cpp.
References _mode, _num_outputs, _pwm_alt_rate, _pwm_alt_rate_channels, _pwm_default_rate, _pwm_initialized, _pwm_mask, DEVICE_DEBUG, MODE_14PWM, MODE_1PWM, MODE_2PWM, MODE_2PWM2CAP, MODE_3PWM, MODE_3PWM1CAP, MODE_4PWM, MODE_6PWM, MODE_8PWM, MODE_NONE, OK, Rising, up_input_capture_set(), and up_pwm_servo_deinit().
Referenced by capture_ioctl(), and pwm_ioctl().
int PX4FMU::set_pwm_alt_channels (uint32_t channels)
Definition at line 787 of file fmu.cpp.
References _pwm_alt_rate, _pwm_default_rate, and set_pwm_rate().
Referenced by get_mode().
int PX4FMU::set_pwm_alt_rate (unsigned rate)
Definition at line 781 of file fmu.cpp.
References _pwm_alt_rate_channels, _pwm_default_rate, and set_pwm_rate().
Referenced by get_mode().
int PX4FMU::set_pwm_rate (unsigned rate_map, unsigned default_rate, unsigned alt_rate) private
Definition at line 715 of file fmu.cpp.
References _max_actuators, _pwm_alt_rate, _pwm_alt_rate_channels, _pwm_default_rate, OK, PX4_DEBUG, PX4_WARN, up_pwm_servo_get_rate_group(), and up_pwm_servo_set_rate_group_update().
Referenced by arm_nothrottle(), pwm_ioctl(), set_pwm_alt_channels(), set_pwm_alt_rate(), and update_pwm_out_state().
int PX4FMU::start () private
Referenced by arm_nothrottle().
void PX4FMU::subscribe () private
Definition at line 799 of file fmu.cpp.
References _control_subs, _control_topics, _groups_required, _groups_subscribed, _poll_fds, _poll_fds_num, DEVICE_DEBUG, orb_subscribe(), and orb_unsubscribe().
Referenced by arm_nothrottle(), and cycle().
int PX4FMU::task_spawn (int argc, char * argv[]) static
See also
ModuleBase
Definition at line 903 of file fmu.cpp.
References cycle_trampoline(), px4_getopt(), PX4_OK, px4_task_spawn_cmd(), PX4_WARN, SCHED_DEFAULT, and SCHED_PRIORITY_ACTUATOR_OUTPUTS.
Referenced by custom_command().
int PX4FMU::test () static
Definition at line 2589 of file fmu.cpp.
References input_capture_config_t::callback, capture_trampoline(), input_capture_stats_t::chan_in_edges_out, device::CDev::close(), input_capture_config_t::context, direction, fd, INPUT_CAP_GET_CALLBACK, INPUT_CAP_GET_COUNT, INPUT_CAP_GET_STATS, INPUT_CAP_SET_CALLBACK, INPUT_CAPTURE_MAX_CHANNELS, ioctl(), device::CDev::open(), device::CDev::poll(), PWM_SERVO_ARM, PWM_SERVO_GET, PWM_SERVO_GET_COUNT, PWM_SERVO_SET, PX4_ERR, PX4_INFO, PX4FMU_DEVICE_PATH, device::CDev::read(), and write().
Referenced by custom_command().
void PX4FMU::update_params () private
Definition at line 1338 of file fmu.cpp.
References _airmode, _mot_t_max, _motor_ordering, _param_sub, _thr_mdl_fac, orb_copy(), ORB_ID, param_find(), param_get(), param_handle(), PARAM_INVALID, PX4_DEBUG, update_pwm_rev_mask(), and update_pwm_trims().
Referenced by arm_nothrottle(), cycle(), and init().
void PX4FMU::update_pwm_out_state (bool on) private
Definition at line 1013 of file fmu.cpp.
References _pwm_alt_rate, _pwm_alt_rate_channels, _pwm_default_rate, _pwm_initialized, _pwm_mask, set_pwm_rate(), up_pwm_servo_arm(), and up_pwm_servo_init().
Referenced by arm_nothrottle(), cycle(), and pwm_ioctl().
void PX4FMU::update_pwm_rev_mask () private
Definition at line 827 of file fmu.cpp.
References _class_instance, _max_actuators, _reverse_pwm_mask, CLASS_DEVICE_PRIMARY, CLASS_DEVICE_SECONDARY, param_find(), param_get(), PARAM_INVALID, and PX4_ERR.
Referenced by arm_nothrottle(), and update_params().
void PX4FMU::update_pwm_trims ()
Definition at line 860 of file fmu.cpp.
References _class_instance, _max_actuators, _mixers, CLASS_DEVICE_PRIMARY, CLASS_DEVICE_SECONDARY, param_find(), param_get(), PARAM_INVALID, PX4_DEBUG, PX4_ERR, and MixerGroup::set_trims().
Referenced by get_mode(), pwm_ioctl(), and update_params().
ssize_t PX4FMU::write (file * filp, const char * buffer, size_t len) virtual
Definition at line 2137 of file fmu.cpp.
References _num_outputs, BOARD_HAS_PWM, MAX_ACTUATORS, PWM_IGNORE_THIS_CHANNEL, reorder_outputs(), up_pwm_servo_set(), and pwm_output_values::values.
Referenced by test().
Member Data Documentation
bool PX4FMU::_airmode private
multicopter air-mode
Definition at line 230 of file fmu.cpp.
Referenced by cycle(), PX4FMU(), and update_params().
actuator_armed_s PX4FMU::_armed = {} static private
Definition at line 214 of file fmu.cpp.
Referenced by control_callback(), cycle(), flash_safety_button(), and PX4FMU().
int PX4FMU::_armed_sub private
Definition at line 190 of file fmu.cpp.
Referenced by cycle(), init(), and ~PX4FMU().
int PX4FMU::_class_instance private
Definition at line 196 of file fmu.cpp.
Referenced by cycle(), init(), update_pwm_rev_mask(), update_pwm_trims(), and ~PX4FMU().
int PX4FMU::_control_subs[actuator_controls_s::NUM_ACTUATOR_CONTROL_GROUPS] private
Definition at line 207 of file fmu.cpp.
Referenced by cycle(), PX4FMU(), subscribe(), and ~PX4FMU().
orb_id_t PX4FMU::_control_topics[actuator_controls_s::NUM_ACTUATOR_CONTROL_GROUPS] private
Definition at line 209 of file fmu.cpp.
Referenced by cycle(), PX4FMU(), and subscribe().
actuator_controls_s PX4FMU::_controls[actuator_controls_s::NUM_ACTUATOR_CONTROL_GROUPS] private
Definition at line 208 of file fmu.cpp.
Referenced by cycle(), pwm_ioctl(), and PX4FMU().
unsigned PX4FMU::_current_update_rate private
Definition at line 186 of file fmu.cpp.
Referenced by cycle(), init(), and print_status().
hrt_abstime PX4FMU::_cycle_timestamp = 0 private
Definition at line 176 of file fmu.cpp.
Referenced by cycle().
uint16_t PX4FMU::_disarmed_pwm[_max_actuators] private
Definition at line 216 of file fmu.cpp.
Referenced by cycle(), pwm_ioctl(), and PX4FMU().
uint16_t PX4FMU::_failsafe_pwm[_max_actuators] private
Definition at line 215 of file fmu.cpp.
Referenced by cycle(), and pwm_ioctl().
uint32_t PX4FMU::_groups_required private
Definition at line 205 of file fmu.cpp.
Referenced by cycle(), pwm_ioctl(), and subscribe().
uint32_t PX4FMU::_groups_subscribed private
Definition at line 206 of file fmu.cpp.
Referenced by cycle(), and subscribe().
hrt_abstime PX4FMU::_last_safety_check = 0 private
Definition at line 177 of file fmu.cpp.
Referenced by cycle().
const unsigned PX4FMU::_max_actuators = DIRECT_PWM_OUTPUT_CHANNELS static private
Definition at line 180 of file fmu.cpp.
Referenced by cycle(), pwm_ioctl(), PX4FMU(), set_pwm_rate(), update_pwm_rev_mask(), and update_pwm_trims().
uint16_t PX4FMU::_max_pwm[_max_actuators] private
Definition at line 218 of file fmu.cpp.
Referenced by cycle(), pwm_ioctl(), and PX4FMU().
uint16_t PX4FMU::_min_pwm[_max_actuators] private
Definition at line 217 of file fmu.cpp.
Referenced by cycle(), pwm_ioctl(), and PX4FMU().
MixerGroup* PX4FMU::_mixers private
Definition at line 203 of file fmu.cpp.
Referenced by cycle(), pwm_ioctl(), and update_pwm_trims().
Mode PX4FMU::_mode private
Definition at line 182 of file fmu.cpp.
Referenced by capture_ioctl(), get_mode(), ioctl(), print_status(), pwm_ioctl(), and set_mode().
float PX4FMU::_mot_t_max private
maximum rise time for motor (slew rate limiting)
Definition at line 228 of file fmu.cpp.
Referenced by cycle(), PX4FMU(), and update_params().
MotorOrdering PX4FMU::_motor_ordering private
Definition at line 231 of file fmu.cpp.
Referenced by PX4FMU(), reorder_outputs(), and update_params().
unsigned PX4FMU::_num_disarmed_set private
Definition at line 221 of file fmu.cpp.
Referenced by cycle(), pwm_ioctl(), and PX4FMU().
unsigned PX4FMU::_num_failsafe_set private
Definition at line 220 of file fmu.cpp.
Referenced by pwm_ioctl(), and PX4FMU().
unsigned PX4FMU::_num_outputs private
Definition at line 195 of file fmu.cpp.
Referenced by cycle(), set_mode(), and write().
orb_advert_t PX4FMU::_outputs_pub private
Definition at line 194 of file fmu.cpp.
Referenced by cycle(), and ~PX4FMU().
int PX4FMU::_param_sub private
Definition at line 191 of file fmu.cpp.
Referenced by cycle(), init(), update_params(), and ~PX4FMU().
perf_counter_t PX4FMU::_perf_control_latency private
Definition at line 233 of file fmu.cpp.
Referenced by cycle(), PX4FMU(), and ~PX4FMU().
pollfd PX4FMU::_poll_fds[actuator_controls_s::NUM_ACTUATOR_CONTROL_GROUPS] private
Definition at line 210 of file fmu.cpp.
Referenced by cycle(), PX4FMU(), and subscribe().
unsigned PX4FMU::_poll_fds_num private
Definition at line 211 of file fmu.cpp.
Referenced by cycle(), and subscribe().
unsigned PX4FMU::_pwm_alt_rate private
Definition at line 184 of file fmu.cpp.
Referenced by cycle(), pwm_ioctl(), set_mode(), set_pwm_alt_channels(), set_pwm_rate(), and update_pwm_out_state().
uint32_t PX4FMU::_pwm_alt_rate_channels private
Definition at line 185 of file fmu.cpp.
Referenced by pwm_ioctl(), set_mode(), set_pwm_alt_rate(), set_pwm_rate(), and update_pwm_out_state().
unsigned PX4FMU::_pwm_default_rate private
Definition at line 183 of file fmu.cpp.
Referenced by cycle(), pwm_ioctl(), set_mode(), set_pwm_alt_channels(), set_pwm_alt_rate(), set_pwm_rate(), and update_pwm_out_state().
bool PX4FMU::_pwm_initialized private
Definition at line 201 of file fmu.cpp.
Referenced by cycle(), set_mode(), and update_pwm_out_state().
pwm_limit_t PX4FMU::_pwm_limit static private
Definition at line 213 of file fmu.cpp.
Referenced by control_callback(), cycle(), and init().
uint32_t PX4FMU::_pwm_mask private
Definition at line 200 of file fmu.cpp.
Referenced by set_mode(), and update_pwm_out_state().
bool PX4FMU::_pwm_on private
Definition at line 199 of file fmu.cpp.
Referenced by cycle().
uint16_t PX4FMU::_reverse_pwm_mask private
Definition at line 219 of file fmu.cpp.
Referenced by cycle(), PX4FMU(), and update_pwm_rev_mask().
bool PX4FMU::_run_as_task private
Definition at line 187 of file fmu.cpp.
Referenced by cycle(), and print_status().
bool PX4FMU::_safety_btn_off private
State of the safety button read from the HW button.
Definition at line 223 of file fmu.cpp.
Referenced by cycle(), flash_safety_button(), init(), print_status(), pwm_ioctl(), PX4FMU(), and safety_check_button().
bool PX4FMU::_safety_disabled private
Definition at line 224 of file fmu.cpp.
Referenced by cycle(), init(), and PX4FMU().
bool PX4FMU::_safety_off private
State of the safety button from the subscribed safety topic.
Definition at line 222 of file fmu.cpp.
Referenced by cycle(), init(), and PX4FMU().
int PX4FMU::_safety_sub private
Definition at line 192 of file fmu.cpp.
Referenced by cycle(), init(), and ~PX4FMU().
float PX4FMU::_thr_mdl_fac private
thrust to pwm modelling factor
Definition at line 229 of file fmu.cpp.
Referenced by cycle(), PX4FMU(), and update_params().
bool PX4FMU::_throttle_armed private
Definition at line 198 of file fmu.cpp.
Referenced by cycle().
hrt_abstime PX4FMU::_time_last_mix = 0 private
Definition at line 178 of file fmu.cpp.
Referenced by cycle().
orb_advert_t PX4FMU::_to_mixer_status private
mixer status flags
Definition at line 226 of file fmu.cpp.
Referenced by cycle(), PX4FMU(), and ~PX4FMU().
orb_advert_t PX4FMU::_to_safety private
Definition at line 225 of file fmu.cpp.
Referenced by cycle(), PX4FMU(), and ~PX4FMU().
work_s PX4FMU::_work = {} static private
Definition at line 188 of file fmu.cpp.
The documentation for this class was generated from the following file:
src/drivers/px4fmu/fmu.cpp