PX4 Firmware: src/drivers/rpi_rc_in/rpi_rc_in.h File Reference
rpi_rc_in.h File Reference
#include <sys/types.h>
#include <sys/stat.h>
#include <sys/ipc.h>
#include <sys/shm.h>
#include <fcntl.h>
#include <stdio.h>
#include <stdint.h>
#include <unistd.h>
#include <px4_platform_common/px4_config.h>
#include <px4_platform_common/px4_work_queue/ScheduledWorkItem.hpp>
#include <px4_platform_common/defines.h>
#include <drivers/drv_hrt.h>
#include <uORB/uORB.h>
#include <uORB/topics/input_rc.h>
Classes
class rpi_rc_in::RcInput
Namespaces
rpi_rc_in
Macros
#define RCINPUT_MEASURE_INTERVAL_US 20000
Functions
static void rpi_rc_in::usage (const char *reason)
Print the correct usage.
__EXPORT int rpi_rc_in_main (int argc, char **argv)
Variables
static RcInput * rpi_rc_in::rc_input = nullptr
Detailed Description
Raspberry Pi driver to publish RC input from shared memory. It requires the ppmdecode program (https://github.com/crossa/raspberry-pi-ppm-rc-in)
Definition in file rpi_rc_in.h.
Macro Definition Documentation
RCINPUT_MEASURE_INTERVAL_US
#define RCINPUT_MEASURE_INTERVAL_US 20000
Definition at line 60 of file rpi_rc_in.h.
Function Documentation
rpi_rc_in_main()
__EXPORT int rpi_rc_in_main (int argc, char ** argv)
Definition at line 146 of file rpi_rc_in.cpp.
References rpi_rc_in::RcInput::is_running(), rpi_rc_in::rc_input, rpi_rc_in::RcInput::RcInput(), rpi_rc_in::RcInput::start(), rpi_rc_in::RcInput::stop(), and rpi_rc_in::usage().