PX4 Firmware: load_mon::LoadMon Class Reference
load_mon::LoadMon Class Reference
Public Member Functions
LoadMon ()
~LoadMon ()
int print_status () override
Static Public Member Functions
static int task_spawn (int argc, char *argv[])
static int custom_command (int argc, char *argv[])
static int print_usage (const char *reason=nullptr)
static void cycle_trampoline (void *arg)
Trampoline for the work queue.
Private Member Functions
void _cycle ()
Do a compute and schedule the next cycle.
void _compute ()
Do a calculation of the CPU load and publish it.
float _ram_used ()
Calculate the memory usage.
Private Attributes
struct work_s _work
struct cpuload_s _cpuload
orb_advert_t _cpuload_pub
hrt_abstime _last_idle_time
perf_counter_t _stack_perf
bool _stack_check_enabled
Detailed Description
Definition at line 74 of file load_mon.cpp.
Constructor & Destructor Documentation
load_mon::LoadMon::LoadMon ()
Definition at line 125 of file load_mon.cpp.
References _cpuload, _cpuload_pub, _last_idle_time, _stack_check_enabled, _stack_perf, param_find(), param_get(), PARAM_INVALID, PC_ELAPSED, perf_alloc, and PX4_INFO.
Referenced by task_spawn().
load_mon::LoadMon::~LoadMon ()
Definition at line 153 of file load_mon.cpp.
References _stack_perf, and perf_free().
Member Function Documentation
void load_mon::LoadMon::_compute () private
Do a calculation of the CPU load and publish it.
Definition at line 201 of file load_mon.cpp.
References _cpuload, _cpuload_pub, _last_idle_time, _ram_used(), _stack_check_enabled, cpuload, hrt_absolute_time(), hrt_abstime, cpuload_s::load, load_mon::LOAD_MON_INTERVAL_US, orb_advertise(), ORB_ID, orb_publish(), cpuload_s::ram_usage, system_load, and cpuload_s::timestamp.
Referenced by _cycle(), and custom_command().
void load_mon::LoadMon::_cycle () private
Do a compute and schedule the next cycle.
Definition at line 188 of file load_mon.cpp.
References _compute(), and cycle_trampoline().
Referenced by custom_command(), and cycle_trampoline().
float load_mon::LoadMon::_ram_used () private
Calculate the memory usage.
Definition at line 233 of file load_mon.cpp.
References _stack_perf, CONFIG_MAX_TASKS, FDS_LOW_WARNING_THRESHOLD, hrt_absolute_time(), orb_advertise_queue(), ORB_ID, orb_publish(), perf_begin(), perf_end(), PX4_WARN, STACK_LOW_WARNING_THRESHOLD, and system_load.
Referenced by _compute(), and custom_command().
static int load_mon::LoadMon::custom_command (int argc, char * argv[]) inline static
See also
ModuleBase
Definition at line 83 of file load_mon.cpp.
References _compute(), _cycle(), _ram_used(), cycle_trampoline(), orb_advert_t, print_status(), and print_usage().
void load_mon::LoadMon::cycle_trampoline (void * arg) static
Trampoline for the work queue.
Definition at line 181 of file load_mon.cpp.
References _cycle().
Referenced by _cycle(), custom_command(), and task_spawn().
int load_mon::LoadMon::print_status () override
See also
ModuleBase::print_status()
Definition at line 341 of file load_mon.cpp.
References _stack_perf, perf_print_counter(), and PX4_INFO.
Referenced by custom_command().
int load_mon::LoadMon::print_usage (const char * reason = nullptr) static
See also
ModuleBase
Definition at line 348 of file load_mon.cpp.
References PRINT_MODULE_DESCRIPTION(), PRINT_MODULE_USAGE_COMMAND_DESCR(), PRINT_MODULE_USAGE_DEFAULT_COMMANDS, PRINT_MODULE_USAGE_NAME(), and PX4_ERR.
Referenced by custom_command().
int load_mon::LoadMon::task_spawn (int argc, char * argv[]) static
Definition at line 158 of file load_mon.cpp.
References _work, cycle_trampoline(), LoadMon(), and PX4_ERR.
Member Data Documentation
struct cpuload_s load_mon::LoadMon::_cpuload private
Definition at line 118 of file load_mon.cpp.
Referenced by _compute(), and LoadMon().
orb_advert_t load_mon::LoadMon::_cpuload_pub private
Definition at line 119 of file load_mon.cpp.
Referenced by _compute(), and LoadMon().
hrt_abstime load_mon::LoadMon::_last_idle_time private
Definition at line 120 of file load_mon.cpp.
Referenced by _compute(), and LoadMon().
bool load_mon::LoadMon::_stack_check_enabled private
Definition at line 122 of file load_mon.cpp.
Referenced by _compute(), and LoadMon().
perf_counter_t load_mon::LoadMon::_stack_perf private
Definition at line 121 of file load_mon.cpp.
Referenced by _ram_used(), LoadMon(), print_status(), and ~LoadMon().
struct work_s load_mon::LoadMon::_work private
Definition at line 116 of file load_mon.cpp.
Referenced by task_spawn().
The documentation for this class was generated from the following file:
src/modules/load_mon/load_mon.cpp