PX4 Firmware: Mixer Class Reference
Mixer Class Reference abstract
Abstract class defining a mixer mixing zero or more inputs to one or more outputs.
#include <mixer.h>
Public Types
typedef int(* ControlCallback) (uintptr_t handle, uint8_t control_group, uint8_t control_index, float &control)
Fetch a control value.
Public Member Functions
Mixer (ControlCallback control_cb, uintptr_t cb_handle)
Constructor.
virtual ~Mixer ()
virtual unsigned mix (float *outputs, unsigned space)=0
Perform the mixing function.
virtual uint16_t get_saturation_status (void)=0
Get the saturation status.
virtual void groups_required (uint32_t &groups)=0
Analyses the mix configuration and updates a bitmask of groups that are required.
virtual void set_max_delta_out_once (float delta_out_max)
Empty method, only implemented for MultirotorMixer and MixerGroup class.
virtual unsigned set_trim (float trim)=0
Set trim offset for this mixer.
virtual unsigned get_trim (float *trim)=0
Get trim offset for this mixer.
virtual void set_thrust_factor (float val)
virtual void set_airmode (bool airmode)
Set airmode.
Public Attributes
Mixer * _next
next mixer in a list
Protected Member Functions
float get_control (uint8_t group, uint8_t index)
Invoke the client callback to fetch a control value.
Static Protected Member Functions
static float scale (const mixer_scaler_s &scaler, float input)
Perform simpler linear scaling.
static int scale_check (struct mixer_scaler_s &scaler)
Validate a scaler.
static const char * findtag (const char *buf, unsigned &buflen, char tag)
Find a tag.
static char findnexttag (const char *buf, unsigned buflen)
Find next tag and return it (0 is returned if no tag is found)
static const char * skipline (const char *buf, unsigned &buflen)
Skip a line.
static bool string_well_formed (const char *buf, unsigned &buflen)
Check wether the string is well formed and suitable for parsing.
Protected Attributes
ControlCallback _control_cb
client-supplied callback used when fetching control values
uintptr_t _cb_handle
Private Member Functions
Mixer (const Mixer &)
Mixer & operator= (const Mixer &)
Detailed Description
Abstract class defining a mixer mixing zero or more inputs to one or more outputs.
Definition at line 140 of file mixer.h.
Member Typedef Documentation
typedef int(* Mixer::ControlCallback) (uintptr_t handle, uint8_t control_group, uint8_t control_index, float &control)
Fetch a control value.
Parameters
handle Token passed when the callback is registered.
control_group The group to fetch the control from.
control_index The group-relative index to fetch the control from.
control The returned control
Returns
Zero if the value was fetched, nonzero otherwise.
Definition at line 155 of file mixer.h.
Constructor & Destructor Documentation
Mixer::Mixer (ControlCallback control_cb, uintptr_t cb_handle)
Constructor.
Parameters
control_cb Callback invoked when reading controls.
Definition at line 48 of file mixer.cpp.
virtual Mixer::~Mixer () inline virtual
Definition at line 166 of file mixer.h.
Mixer::Mixer (const Mixer &) private
Member Function Documentation
char Mixer::findnexttag (const char * buf, unsigned buflen) static protected
Find next tag and return it (0 is returned if no tag is found)
Parameters
buf The buffer to operate on.
buflen length of the buffer.
Definition at line 130 of file mixer.cpp.
Referenced by SimpleMixer::from_text().
const char * Mixer::findtag (const char * buf, unsigned & buflen, char tag) static protected
Find a tag.
Parameters
buf The buffer to operate on.
buflen length of the buffer.
tag character to search for.
Definition at line 115 of file mixer.cpp.
Referenced by HelicopterMixer::from_text(), SimpleMixer::parse_control_scaler(), and SimpleMixer::parse_output_scaler().
float Mixer::get_control (uint8_t group, uint8_t index) protected
Invoke the client callback to fetch a control value.
Parameters
group Control group to fetch from.
index Control index to fetch.
Returns
The control value.
Definition at line 56 of file mixer.cpp.
References _cb_handle, and _control_cb.
Referenced by MultirotorMixer::mix(), and HelicopterMixer::mix().
virtual uint16_t Mixer::get_saturation_status (void) pure virtual
Get the saturation status.
Returns
Integer bitmask containing saturation_status from multirotor_motor_limits.msg.
Implemented in HelicopterMixer, MultirotorMixer, SimpleMixer, NullMixer, and MixerGroup.
Referenced by MixerGroup::get_saturation_status(), and NullMixer::~NullMixer().
virtual unsigned Mixer::get_trim (float * trim) pure virtual
Get trim offset for this mixer.
Returns
the number of outputs this mixer feeds to
Implemented in HelicopterMixer, MultirotorMixer, SimpleMixer, NullMixer, and MixerGroup.
Referenced by MixerGroup::get_trims().
virtual void Mixer::groups_required (uint32_t & groups) pure virtual
Analyses the mix configuration and updates a bitmask of groups that are required.
Parameters
groups A bitmask of groups (0-31) that the mixer requires.
Implemented in HelicopterMixer, MultirotorMixer, SimpleMixer, NullMixer, and MixerGroup.
Referenced by MixerGroup::groups_required(), and NullMixer::~NullMixer().
virtual unsigned Mixer::mix (float * outputs, unsigned space) pure virtual
Perform the mixing function.
Parameters
outputs Array into which mixed output(s) should be placed.
space The number of available entries in the output array;
Returns
The number of entries in the output array that were populated.
Implemented in HelicopterMixer, MultirotorMixer, SimpleMixer, NullMixer, and MixerGroup.
Referenced by MixerGroup::mix(), and NullMixer::~NullMixer().
Mixer& Mixer::operator= (const Mixer &) private
float Mixer::scale (const mixer_scaler_s & scaler, float input) static protected
Perform simpler linear scaling.
Parameters
scaler The scaler configuration.
input The value to be scaled.
Returns
The scaled value.
Definition at line 67 of file mixer.cpp.
References f(), mixer_scaler_s::max_output, mixer_scaler_s::min_output, mixer_scaler_s::negative_scale, mixer_scaler_s::offset, and mixer_scaler_s::positive_scale.
Referenced by SimpleMixer::mix().
int Mixer::scale_check (struct mixer_scaler_s & scaler) static protected
Validate a scaler.
Parameters
scaler The scaler to be validated.
Returns
Zero if good, nonzero otherwise.
Definition at line 89 of file mixer.cpp.
References mixer_scaler_s::max_output, mixer_scaler_s::min_output, and mixer_scaler_s::offset.
Referenced by SimpleMixer::check().
virtual void Mixer::set_airmode (bool airmode) inline virtual
Set airmode.
Airmode allows the mixer to increase the total thrust in order to unsaturate the motors.
Parameters
[in] airmode De/-activate airmode by setting it to false/true
Reimplemented in MultirotorMixer, and MixerGroup.
Definition at line 226 of file mixer.h.
Referenced by MixerGroup::get_trim(), and MixerGroup::set_airmode().
virtual void Mixer::set_max_delta_out_once (float delta_out_max) inline virtual
Empty method, only implemented for MultirotorMixer and MixerGroup class.
Parameters
[in] delta_out_max Maximum delta output.
Reimplemented in MultirotorMixer, and MixerGroup.
Definition at line 198 of file mixer.h.
Referenced by MixerGroup::set_max_delta_out_once().
virtual void Mixer::set_thrust_factor (float val) inline virtual
Reimplemented in MultirotorMixer, and MixerGroup.
Definition at line 219 of file mixer.h.
Referenced by MixerGroup::get_trim(), and MixerGroup::set_thrust_factor().
virtual unsigned Mixer::set_trim (float trim) pure virtual
Set trim offset for this mixer.
Returns
the number of outputs this mixer feeds to
Implemented in HelicopterMixer, MultirotorMixer, SimpleMixer, NullMixer, and MixerGroup.
Referenced by MixerGroup::set_trims().
const char * Mixer::skipline (const char * buf, unsigned & buflen) static protected
Skip a line.
Parameters
buf The buffer to operate on.
buflen length of the buffer.
Returns
0 / OK if a line could be skipped, 1 else
Definition at line 145 of file mixer.cpp.
Referenced by SimpleMixer::from_text(), MultirotorMixer::from_text(), HelicopterMixer::from_text(), SimpleMixer::parse_control_scaler(), and SimpleMixer::parse_output_scaler().
bool Mixer::string_well_formed (const char * buf, unsigned & buflen) static protected
Check wether the string is well formed and suitable for parsing.
Definition at line 160 of file mixer.cpp.
References debug.
Referenced by NullMixer::from_text(), SimpleMixer::from_text(), MultirotorMixer::from_text(), and HelicopterMixer::from_text().
Member Data Documentation
uintptr_t Mixer::_cb_handle protected
Definition at line 231 of file mixer.h.
Referenced by SimpleMixer::check(), get_control(), MixerGroup::load_from_buf(), and SimpleMixer::mix().
ControlCallback Mixer::_control_cb protected
client-supplied callback used when fetching control values
Definition at line 226 of file mixer.h.
Referenced by SimpleMixer::check(), get_control(), MixerGroup::load_from_buf(), and SimpleMixer::mix().
Mixer* Mixer::_next
next mixer in a list
Definition at line 144 of file mixer.h.
Referenced by MixerGroup::add_mixer(), MixerGroup::count(), MixerGroup::get_saturation_status(), MixerGroup::get_trims(), MixerGroup::groups_required(), MixerGroup::mix(), MixerGroup::reset(), MixerGroup::set_airmode(), MixerGroup::set_max_delta_out_once(), MixerGroup::set_thrust_factor(), and MixerGroup::set_trims().
The documentation for this class was generated from the following files:
src/lib/mixer/mixer.h
src/lib/mixer/mixer.cpp