PX4 Firmware: src/platforms/posix/drivers/df_trone_wrapper/df_trone_wrapper.cpp File Reference
df_trone_wrapper.cpp File Reference
Driver to access the TROne of the DriverFramework.
#include <px4_config.h>
#include <sys/types.h>
#include <sys/stat.h>
#include <stdint.h>
#include <stddef.h>
#include <stdlib.h>
#include <string.h>
#include <math.h>
#include <unistd.h>
#include <px4_getopt.h>
#include <errno.h>
#include <string>
#include <perf/perf_counter.h>
#include <systemlib/err.h>
#include <drivers/drv_range_finder.h>
#include <drivers/drv_hrt.h>
#include <uORB/uORB.h>
#include <uORB/topics/distance_sensor.h>
#include <board_config.h>
#include <trone/TROne.hpp>
#include <DevMgr.hpp>
Classes
class DfTROneWrapper
Namespaces
df_trone_wrapper
Functions
__EXPORT int df_trone_wrapper_main (int argc, char *argv[])
int df_trone_wrapper::start (uint8_t rotation)
int df_trone_wrapper::stop ()
Stop the driver.
int df_trone_wrapper::info ()
Print a little info about the driver.
int df_trone_wrapper::probe ()
Who am i.
void df_trone_wrapper::usage ()
Prints info about the driver argument usage.
Variables
DfTROneWrapper * df_trone_wrapper::g_dev = nullptr
Detailed Description
Driver to access the TROne of the DriverFramework.
Author
Nicolas de Palezieux ndepa.nosp@m.l@gm.nosp@m.ail.c.nosp@m.om
Definition in file df_trone_wrapper.cpp.
Function Documentation
int df_trone_wrapper_main (int argc, char * argv[])
Definition at line 310 of file df_trone_wrapper.cpp.
References df_trone_wrapper::info(), df_trone_wrapper::probe(), px4_getopt(), PX4_INFO, df_trone_wrapper::start(), df_trone_wrapper::stop(), and df_trone_wrapper::usage().