PX4 Firmware: src/systemcmds/motor_test/motor_test.cpp File Reference
motor_test.cpp File Reference
#include <drivers/drv_hrt.h>
#include <px4_platform_common/px4_config.h>
#include <px4_platform_common/getopt.h>
#include <px4_platform_common/log.h>
#include <px4_platform_common/module.h>
#include <uORB/PublicationQueued.hpp>
#include <uORB/topics/test_motor.h>
Functions
__EXPORT int motor_test_main (int argc, char *argv[])
static void motor_test (unsigned channel, float value, uint8_t driver_instance, int timeout_ms)
static void usage (const char *reason)
Function Documentation
motor_test()
void motor_test (unsigned channel, float value, uint8_t driver_instance, int timeout_ms) static
Definition at line 54 of file motor_test.cpp.
References hrt_absolute_time(), ORB_ID, timeout_ms, and test_motor_s::timestamp.
Referenced by motor_test_main().
motor_test_main()
int motor_test_main (int argc, char * argv[])
Definition at line 99 of file motor_test.cpp.
References f(), motor_test(), timeout_ms, and usage().
usage()
static void usage (const char * reason) static
Definition at line 75 of file motor_test.cpp.
Referenced by motor_test_main().