PX4 Firmware: src/drivers/magnetometer/bmm150/bmm150.cpp File Reference
bmm150.cpp File Reference
Driver for the Bosch BMM 150 MEMS magnetometer connected via I2C.
#include "bmm150.hpp"
#include <px4_getopt.h>
Namespaces
bmm150
Functions
__EXPORT int bmm150_main (int argc, char *argv[])
driver 'main' command
void bmm150::start (bool external_bus, enum Rotation rotation)
Start the driver.
void bmm150::test (bool)
void bmm150::reset (bool)
void bmm150::info (bool)
void bmm150::regdump (bool external_bus)
Dump the register information.
void bmm150::usage ()
Prints info about the driver argument usage.
Variables
BMM150 * bmm150::g_dev_ext
BMM150 * bmm150::g_dev_int
Detailed Description
Driver for the Bosch BMM 150 MEMS magnetometer connected via I2C.
Definition in file bmm150.cpp.
Function Documentation
int bmm150_main (int argc, char * argv[])
driver 'main' command
Definition at line 1121 of file bmm150.cpp.
References bmm150::info(), px4_getopt(), bmm150::regdump(), bmm150::reset(), ROTATION_NONE, bmm150::start(), bmm150::test(), and bmm150::usage().