PX4 Firmware: ACCELSIM Class Reference
ACCELSIM Class Reference
Public Member Functions
ACCELSIM (const char *path, enum Rotation rotation)
virtual ~ACCELSIM ()
virtual int init ()
virtual ssize_t devRead (void *buffer, size_t buflen)
virtual int devIOCTL (unsigned long cmd, unsigned long arg)
void print_registers ()
dump register values
Protected Member Functions
ssize_t mag_read (void *buffer, size_t buflen)
int mag_ioctl (unsigned long cmd, unsigned long arg)
int transfer (uint8_t *send, uint8_t *recv, unsigned len)
Private Member Functions
virtual int start ()
Override Start automatic measurement.
virtual int stop ()
Override Stop automatic measurement.
virtual void _measure ()
Fetch accel measurements from the sensor and update the report ring.
void mag_measure ()
Fetch mag measurements from the sensor and update the report ring.
int accel_set_range (unsigned max_g)
Set the ACCELSIM accel measurement range.
int mag_set_range (unsigned max_g)
Set the ACCELSIM mag measurement range.
int accel_set_driver_lowpass_filter (float samplerate, float bandwidth)
Set the driver lowpass filter bandwidth.
ACCELSIM (const ACCELSIM &)
ACCELSIM operator= (const ACCELSIM &)
Private Attributes
ACCELSIM_mag * _mag
ringbuffer::RingBuffer * _accel_reports
ringbuffer::RingBuffer * _mag_reports
struct accel_calibration_s _accel_scale
unsigned _accel_range_m_s2
float _accel_range_scale
unsigned _accel_samplerate
unsigned _accel_onchip_filter_bandwith
struct mag_calibration_s _mag_scale
unsigned _mag_range_ga
float _mag_range_scale
unsigned _mag_samplerate
orb_advert_t _accel_topic
int _accel_orb_class_instance
int _accel_class_instance
unsigned _accel_read
unsigned _mag_read
perf_counter_t _accel_sample_perf
perf_counter_t _mag_sample_perf
perf_counter_t _accel_reschedules
perf_counter_t _bad_registers
perf_counter_t _bad_values
math::LowPassFilter2p _accel_filter_x
math::LowPassFilter2p _accel_filter_y
math::LowPassFilter2p _accel_filter_z
enum Rotation _rotation
float _last_accel [3]
uint8_t _constant_accel_count
float _last_temperature
Friends
class ACCELSIM_mag
Detailed Description
Definition at line 86 of file accelsim.cpp.
Constructor & Destructor Documentation
ACCELSIM::ACCELSIM (const char * path, enum Rotation rotation)
Definition at line 238 of file accelsim.cpp.
References _accel_class_instance, _accel_filter_x, _accel_filter_y, _accel_filter_z, _accel_onchip_filter_bandwith, _accel_orb_class_instance, _accel_range_m_s2, _accel_range_scale, _accel_read, _accel_reschedules, _accel_sample_perf, _accel_samplerate, _accel_scale, _accel_topic, _bad_registers, _bad_values, _constant_accel_count, _last_temperature, _mag, _mag_range_ga, _mag_range_scale, _mag_read, _mag_sample_perf, _mag_samplerate, _mag_scale, _rotation, ACCELSIM_ACCEL_DEFAULT_DRIVER_FILTER_FREQ, ACCELSIM_ACCEL_DEFAULT_RATE, DRV_ACC_DEVTYPE_ACCELSIM, DRV_MAG_DEVTYPE_ACCELSIM, f(), PC_COUNT, PC_ELAPSED, perf_alloc, mag_calibration_s::x_offset, accel_calibration_s::x_offset, mag_calibration_s::x_scale, accel_calibration_s::x_scale, mag_calibration_s::y_offset, accel_calibration_s::y_offset, mag_calibration_s::y_scale, accel_calibration_s::y_scale, mag_calibration_s::z_offset, accel_calibration_s::z_offset, mag_calibration_s::z_scale, and accel_calibration_s::z_scale.
ACCELSIM::~ACCELSIM () virtual
Definition at line 292 of file accelsim.cpp.
References _accel_reports, _accel_reschedules, _accel_sample_perf, _bad_registers, _bad_values, _mag, _mag_reports, _mag_sample_perf, perf_free(), stop(), and ACCELSIM_mag::stop().
ACCELSIM::ACCELSIM (const ACCELSIM &) private
Member Function Documentation
void ACCELSIM::_measure (void) private virtual
Fetch accel measurements from the sensor and update the report ring.
Definition at line 781 of file accelsim.cpp.
References _accel_range_scale, _accel_read, _accel_reports, _accel_sample_perf, _accel_topic, _bad_registers, _bad_values, _last_temperature, ACC_READ, accel_report, DIR_READ, hrt_absolute_time(), OK, ORB_ID, orb_publish(), perf_begin(), perf_end(), perf_event_count(), PX4_INFO, status, and transfer().
Referenced by devRead(), and init().
int ACCELSIM::accel_set_driver_lowpass_filter (float samplerate, float bandwidth) private
Set the driver lowpass filter bandwidth.
Parameters
bandwidth The anti-alias filter bandwidth in Hz Zero selects the highest bandwidth
Returns
OK if the value can be supported, -ERANGE otherwise.
Definition at line 744 of file accelsim.cpp.
References _accel_filter_x, _accel_filter_y, _accel_filter_z, OK, and math::LowPassFilter2p::set_cutoff_frequency().
Referenced by devIOCTL().
int ACCELSIM::accel_set_range (unsigned max_g) private
Set the ACCELSIM accel measurement range.
Parameters
max_g The measurement range of the accel is in g (9.81m/s^2) Zero selects the maximum supported range.
Returns
OK if the value can be supported, -ERANGE otherwise.
Definition at line 724 of file accelsim.cpp.
References _accel_range_scale, CONSTANTS_ONE_G, f(), and OK.
Referenced by devIOCTL().
int ACCELSIM::devIOCTL (unsigned long cmd, unsigned long arg) virtual
Definition at line 490 of file accelsim.cpp.
References _accel_filter_x, _accel_range_m_s2, _accel_reports, _accel_samplerate, _accel_scale, accel_set_driver_lowpass_filter(), accel_set_range(), ACCELIOCGRANGE, ACCELIOCGSAMPLERATE, ACCELIOCGSCALE, ACCELIOCSRANGE, ACCELIOCSSAMPLERATE, ACCELIOCSSCALE, ACCELSIM_ACCEL_DEFAULT_RATE, CONSTANTS_ONE_G, f(), math::LowPassFilter2p::get_cutoff_freq(), OK, SENSOR_POLLRATE_DEFAULT, SENSOR_POLLRATE_EXTERNAL, SENSOR_POLLRATE_MANUAL, SENSOR_POLLRATE_MAX, SENSORIOCGPOLLRATE, SENSORIOCRESET, SENSORIOCSPOLLRATE, SENSORIOCSQUEUEDEPTH, start(), stop(), accel_calibration_s::x_scale, accel_calibration_s::y_scale, and accel_calibration_s::z_scale.
Referenced by accelsim::info().
ssize_t ACCELSIM::devRead (void * buffer, size_t buflen) virtual
Definition at line 410 of file accelsim.cpp.
References _accel_reports, _measure(), and accel_report.
int ACCELSIM::init () virtual
Definition at line 318 of file accelsim.cpp.
References _accel_orb_class_instance, _accel_reports, _accel_topic, _mag, ACCELSIM_mag::_mag_orb_class_instance, _mag_reports, ACCELSIM_mag::_mag_topic, _measure(), accel_report, lis3mdl::init(), mag_report, OK, orb_advertise_multi(), ORB_ID, ORB_PRIO_DEFAULT, ORB_PRIO_LOW, and PX4_WARN.
Referenced by accelsim::start().
int ACCELSIM::mag_ioctl (unsigned long cmd, unsigned long arg) protected
Definition at line 611 of file accelsim.cpp.
References _mag, _mag_range_ga, _mag_reports, _mag_samplerate, _mag_scale, mag_set_range(), MAGIOCGEXTERNAL, MAGIOCGRANGE, MAGIOCGSAMPLERATE, MAGIOCGSCALE, MAGIOCSRANGE, MAGIOCSSAMPLERATE, MAGIOCSSCALE, OK, SENSOR_POLLRATE_DEFAULT, SENSOR_POLLRATE_EXTERNAL, SENSOR_POLLRATE_MANUAL, SENSOR_POLLRATE_MAX, SENSORIOCGPOLLRATE, SENSORIOCRESET, SENSORIOCSPOLLRATE, SENSORIOCSQUEUEDEPTH, ACCELSIM_mag::start(), and ACCELSIM_mag::stop().
Referenced by ACCELSIM_mag::devIOCTL().
void ACCELSIM::mag_measure () private
Fetch mag measurements from the sensor and update the report ring.
Definition at line 878 of file accelsim.cpp.
References _last_temperature, _mag, _mag_range_scale, _mag_read, _mag_reports, _mag_sample_perf, ACCELSIM_mag::_mag_topic, _rotation, DIR_READ, hrt_absolute_time(), MAG_READ, mag_report, OK, ORB_ID, orb_publish(), perf_begin(), perf_end(), rotate_3f(), status, and transfer().
Referenced by ACCELSIM_mag::_measure().
ssize_t ACCELSIM::mag_read (void * buffer, size_t buflen) protected
Definition at line 449 of file accelsim.cpp.
References _mag, _mag_reports, ACCELSIM_mag::_measure(), and mag_report.
Referenced by ACCELSIM_mag::devRead().
int ACCELSIM::mag_set_range (unsigned max_g) private
Set the ACCELSIM mag measurement range.
Parameters
max_ga The measurement range of the mag is in Ga Zero selects the maximum supported range.
Returns
OK if the value can be supported, -ERANGE otherwise.
Definition at line 734 of file accelsim.cpp.
References _mag_range_scale, f(), and OK.
Referenced by mag_ioctl().
ACCELSIM ACCELSIM::operator= (const ACCELSIM &) private
void ACCELSIM::print_registers ()
dump register values
int ACCELSIM::start () private virtual
Override Start automatic measurement.
Definition at line 754 of file accelsim.cpp.
References _accel_reports, _mag_reports, PX4_ERR, start(), and stop().
Referenced by devIOCTL().
int ACCELSIM::stop () private virtual
Override Stop automatic measurement.
Definition at line 774 of file accelsim.cpp.
References stop().
Referenced by devIOCTL(), start(), and ~ACCELSIM().
int ACCELSIM::transfer (uint8_t * send, uint8_t * recv, unsigned len) protected
Definition at line 382 of file accelsim.cpp.
References ACC_READ, DIR_READ, Simulator::getInstance(), Simulator::getMagReport(), Simulator::getRawAccelReport(), MAG_READ, and PX4_OK.
Referenced by _measure(), and mag_measure().
Friends And Related Function Documentation
friend class ACCELSIM_mag friend
Definition at line 103 of file accelsim.cpp.
Member Data Documentation
int ACCELSIM::_accel_class_instance private
Definition at line 129 of file accelsim.cpp.
Referenced by ACCELSIM().
math::LowPassFilter2p ACCELSIM::_accel_filter_x private
Definition at line 140 of file accelsim.cpp.
Referenced by accel_set_driver_lowpass_filter(), ACCELSIM(), and devIOCTL().
math::LowPassFilter2p ACCELSIM::_accel_filter_y private
Definition at line 141 of file accelsim.cpp.
Referenced by accel_set_driver_lowpass_filter(), and ACCELSIM().
math::LowPassFilter2p ACCELSIM::_accel_filter_z private
Definition at line 142 of file accelsim.cpp.
Referenced by accel_set_driver_lowpass_filter(), and ACCELSIM().
unsigned ACCELSIM::_accel_onchip_filter_bandwith private
Definition at line 120 of file accelsim.cpp.
Referenced by ACCELSIM().
int ACCELSIM::_accel_orb_class_instance private
Definition at line 128 of file accelsim.cpp.
Referenced by ACCELSIM(), and init().
unsigned ACCELSIM::_accel_range_m_s2 private
Definition at line 117 of file accelsim.cpp.
Referenced by ACCELSIM(), and devIOCTL().
float ACCELSIM::_accel_range_scale private
Definition at line 118 of file accelsim.cpp.
Referenced by _measure(), accel_set_range(), and ACCELSIM().
unsigned ACCELSIM::_accel_read private
Definition at line 131 of file accelsim.cpp.
Referenced by _measure(), and ACCELSIM().
ringbuffer::RingBuffer* ACCELSIM::_accel_reports private
Definition at line 113 of file accelsim.cpp.
Referenced by _measure(), devIOCTL(), devRead(), init(), start(), and ~ACCELSIM().
perf_counter_t ACCELSIM::_accel_reschedules private
Definition at line 136 of file accelsim.cpp.
Referenced by ACCELSIM(), and ~ACCELSIM().
perf_counter_t ACCELSIM::_accel_sample_perf private
Definition at line 134 of file accelsim.cpp.
Referenced by _measure(), ACCELSIM(), and ~ACCELSIM().
unsigned ACCELSIM::_accel_samplerate private
Definition at line 119 of file accelsim.cpp.
Referenced by ACCELSIM(), and devIOCTL().
struct accel_calibration_s ACCELSIM::_accel_scale private
Definition at line 116 of file accelsim.cpp.
Referenced by ACCELSIM(), and devIOCTL().
orb_advert_t ACCELSIM::_accel_topic private
Definition at line 127 of file accelsim.cpp.
Referenced by _measure(), ACCELSIM(), and init().
perf_counter_t ACCELSIM::_bad_registers private
Definition at line 137 of file accelsim.cpp.
Referenced by _measure(), ACCELSIM(), and ~ACCELSIM().
perf_counter_t ACCELSIM::_bad_values private
Definition at line 138 of file accelsim.cpp.
Referenced by _measure(), ACCELSIM(), and ~ACCELSIM().
uint8_t ACCELSIM::_constant_accel_count private
Definition at line 148 of file accelsim.cpp.
Referenced by ACCELSIM().
float ACCELSIM::_last_accel[3] private
Definition at line 147 of file accelsim.cpp.
float ACCELSIM::_last_temperature private
Definition at line 151 of file accelsim.cpp.
Referenced by _measure(), ACCELSIM(), and mag_measure().
ACCELSIM_mag* ACCELSIM::_mag private
Definition at line 111 of file accelsim.cpp.
Referenced by ACCELSIM(), init(), mag_ioctl(), mag_measure(), mag_read(), and ~ACCELSIM().
unsigned ACCELSIM::_mag_range_ga private
Definition at line 123 of file accelsim.cpp.
Referenced by ACCELSIM(), and mag_ioctl().
float ACCELSIM::_mag_range_scale private
Definition at line 124 of file accelsim.cpp.
Referenced by ACCELSIM(), mag_measure(), and mag_set_range().
unsigned ACCELSIM::_mag_read private
Definition at line 132 of file accelsim.cpp.
Referenced by ACCELSIM(), and mag_measure().
ringbuffer::RingBuffer* ACCELSIM::_mag_reports private
Definition at line 114 of file accelsim.cpp.
Referenced by init(), mag_ioctl(), mag_measure(), mag_read(), start(), and ~ACCELSIM().
perf_counter_t ACCELSIM::_mag_sample_perf private
Definition at line 135 of file accelsim.cpp.
Referenced by ACCELSIM(), mag_measure(), and ~ACCELSIM().
unsigned ACCELSIM::_mag_samplerate private
Definition at line 125 of file accelsim.cpp.
Referenced by ACCELSIM(), and mag_ioctl().
struct mag_calibration_s ACCELSIM::_mag_scale private
Definition at line 122 of file accelsim.cpp.
Referenced by ACCELSIM(), and mag_ioctl().
enum Rotation ACCELSIM::_rotation private
Definition at line 144 of file accelsim.cpp.
Referenced by ACCELSIM(), and mag_measure().
The documentation for this class was generated from the following file:
src/modules/simulator/accelsim/accelsim.cpp