PX4 Firmware: src/systemcmds/tests/test_ppm_loopback.c File Reference
test_ppm_loopback.c File Reference
Tests the PWM outputs and PPM input.
#include <px4_platform_common/time.h>
#include <px4_platform_common/px4_config.h>
#include <sys/types.h>
#include <stdio.h>
#include <stdlib.h>
#include <unistd.h>
#include <fcntl.h>
#include <errno.h>
#include <arch/board/board.h>
#include <drivers/drv_pwm_output.h>
#include <drivers/drv_rc_input.h>
#include <uORB/topics/rc_channels.h>
#include <systemlib/err.h>
#include "tests_main.h"
#include <math.h>
#include <float.h>
Functions
int test_ppm_loopback (int argc, char *argv[])
Detailed Description
Tests the PWM outputs and PPM input.
Definition in file test_ppm_loopback.c.
Function Documentation
test_ppm_loopback()
int test_ppm_loopback (int argc, char * argv[])
Definition at line 61 of file test_ppm_loopback.c.
References matrix::abs(), pwm_output_values::channel_count, OK, orb_check(), orb_copy(), ORB_ID, orb_subscribe(), PWM_OUTPUT0_DEVICE_PATH, PWM_SERVO_GET, PWM_SERVO_GET_COUNT, PWM_SERVO_SET, PWM_SERVO_SET_DISARMED_PWM, pwm_output_values::values, input_rc_s::values, and warnx.