PX4 Firmware: src/modules/mc_pos_control/PositionControl/PositionControlTest.cpp File Reference
PositionControlTest.cpp File Reference
#include <gtest/gtest.h>
#include <PositionControl.hpp>
#include <px4_defines.h>
Classes
class PositionControlBasicTest
class PositionControlBasicDirectionTest
Functions
TEST (PositionControlTest, EmptySetpoint)
TEST_F (PositionControlBasicDirectionTest, PositionControlDirectionP)
TEST_F (PositionControlBasicDirectionTest, VelocityControlDirection)
TEST_F (PositionControlBasicTest, PositionControlMaxTilt)
TEST_F (PositionControlBasicTest, PositionControlMaxVelocity)
TEST_F (PositionControlBasicTest, PositionControlThrustLimit)
TEST_F (PositionControlBasicTest, PositionControlFailsafeInput)
Function Documentation
TEST()
TEST (PositionControlTest , EmptySetpoint)
Definition at line 40 of file PositionControlTest.cpp.
References attitude, f(), PositionControl::getAttitudeSetpoint(), and PositionControl::getLocalPositionSetpoint().
TEST_F() [1/6]
TEST_F (PositionControlBasicDirectionTest , PositionControlDirectionP)
Definition at line 136 of file PositionControlTest.cpp.
TEST_F() [2/6]
TEST_F (PositionControlBasicDirectionTest , VelocityControlDirection)
Definition at line 145 of file PositionControlTest.cpp.
TEST_F() [3/6]
TEST_F (PositionControlBasicTest , PositionControlMaxTilt)
Definition at line 154 of file PositionControlTest.cpp.
References matrix::Vector< Type, M >::dot(), and f().
TEST_F() [4/6]
TEST_F (PositionControlBasicTest , PositionControlMaxVelocity)
Definition at line 174 of file PositionControlTest.cpp.
References matrix::abs(), and matrix::Vector< Type, M >::norm().
TEST_F() [5/6]
TEST_F (PositionControlBasicTest , PositionControlThrustLimit)
Definition at line 186 of file PositionControlTest.cpp.
TEST_F() [6/6]
TEST_F (PositionControlBasicTest , PositionControlFailsafeInput)
Definition at line 199 of file PositionControlTest.cpp.