PX4 Firmware: src/drivers/md25/md25.cpp File Reference
md25.cpp File Reference
Driver for MD25 I2C Motor Driver.
#include "md25.hpp"
#include <poll.h>
#include <stdio.h>
#include <math.h>
#include <string.h>
#include <systemlib/err.h>
#include <arch/board/board.h>
#include <systemlib/mavlink_log.h>
#include <uORB/Publication.hpp>
#include <uORB/topics/debug_key_value.h>
#include <drivers/drv_hrt.h>
Enumerations
enum {
REG_SPEED1_RW = 0, REG_SPEED2_RW, REG_ENC1A_R, REG_ENC1B_R,
REG_ENC1C_R, REG_ENC1D_R, REG_ENC2A_R, REG_ENC2B_R,
REG_ENC2C_R, REG_ENC2D_R, REG_BATTERY_VOLTS_R, REG_MOTOR1_CURRENT_R,
REG_MOTOR2_CURRENT_R, REG_SW_VERSION_R, REG_ACCEL_RATE_RW, REG_MODE_RW,
REG_COMMAND_RW
}
Functions
int md25Test (const char *deviceName, uint8_t bus, uint8_t address)
int md25Sine (const char *deviceName, uint8_t bus, uint8_t address, float amplitude, float frequency)
Variables
static orb_advert_t mavlink_log_pub
Detailed Description
Driver for MD25 I2C Motor Driver.
references: http://www.robot-electronics.co.uk/htm/md25tech.htm http://www.robot-electronics.co.uk/files/rpi_md25.c
Definition in file md25.cpp.
Enumeration Type Documentation
anonymous enum
Enumerator
REG_SPEED1_RW
REG_SPEED2_RW
REG_ENC1A_R
REG_ENC1B_R
REG_ENC1C_R
REG_ENC1D_R
REG_ENC2A_R
REG_ENC2B_R
REG_ENC2C_R
REG_ENC2D_R
REG_BATTERY_VOLTS_R
REG_MOTOR1_CURRENT_R
REG_MOTOR2_CURRENT_R
REG_SW_VERSION_R
REG_ACCEL_RATE_RW
REG_MODE_RW
REG_COMMAND_RW
Definition at line 60 of file md25.cpp.
Function Documentation
int md25Sine (const char * deviceName, uint8_t bus, uint8_t address, float amplitude, float frequency)
Definition at line 566 of file md25.cpp.
References dt, MD25::getRevolutions1(), hrt_absolute_time(), ORB_ID, MD25::readData(), MD25::resetEncoders(), MD25::setMotor1Speed(), MD25::setSpeedRegulation(), MD25::setTimeout(), MD25::status(), uORB::Publication< T >::update(), and usleep().
Referenced by md25_main().
int md25Test (const char * deviceName, uint8_t bus, uint8_t address)
Definition at line 459 of file md25.cpp.
References dt, f(), MD25::getRevolutions1(), MD25::getRevolutions2(), MD25::readData(), MD25::resetEncoders(), MD25::setMotor1Speed(), MD25::setMotor2Speed(), MD25::setSpeedRegulation(), MD25::setTimeout(), MD25::status(), and usleep().
Referenced by md25_main().
Variable Documentation
orb_advert_t mavlink_log_pub static
Definition at line 83 of file md25.cpp.
Referenced by do_accel_calibration_measurements(), do_gyro_calibration(), mag_calibrate_all(), and position_estimator_inav_thread_main().