PX4 Firmware: ADIS16448::ADISReport Struct Reference
ADIS16448::ADISReport Struct Reference
Report conversation with in the ADIS16448, including command byte and interrupt status.
Public Member Functions
ADISReport ()
Public Attributes
uint16_t cmd
uint16_t status
uint16_t gyro_x
uint16_t gyro_y
uint16_t gyro_z
uint16_t accel_x
uint16_t accel_y
uint16_t accel_z
uint16_t mag_x
uint16_t mag_y
uint16_t mag_z
uint16_t baro
uint16_t temp
Detailed Description
Report conversation with in the ADIS16448, including command byte and interrupt status.
Definition at line 278 of file adis16448.cpp.
Constructor & Destructor Documentation
ADIS16448::ADISReport::ADISReport () inline
Definition at line 293 of file adis16448.cpp.
References ADIS16448::measure(), ADIS16448::measure_trampoline(), ADIS16448::modify_reg16(), ADIS16448::read_reg16(), ADIS16448::reset(), ADIS16448::start(), ADIS16448::stop(), and ADIS16448::write_reg16().
Member Data Documentation
uint16_t ADIS16448::ADISReport::accel_x
Definition at line 284 of file adis16448.cpp.
uint16_t ADIS16448::ADISReport::accel_y
Definition at line 285 of file adis16448.cpp.
uint16_t ADIS16448::ADISReport::accel_z
Definition at line 286 of file adis16448.cpp.
uint16_t ADIS16448::ADISReport::baro
Definition at line 290 of file adis16448.cpp.
uint16_t ADIS16448::ADISReport::cmd
Definition at line 279 of file adis16448.cpp.
Referenced by ADIS16448::measure().
uint16_t ADIS16448::ADISReport::gyro_x
Definition at line 281 of file adis16448.cpp.
uint16_t ADIS16448::ADISReport::gyro_y
Definition at line 282 of file adis16448.cpp.
uint16_t ADIS16448::ADISReport::gyro_z
Definition at line 283 of file adis16448.cpp.
uint16_t ADIS16448::ADISReport::mag_x
Definition at line 287 of file adis16448.cpp.
uint16_t ADIS16448::ADISReport::mag_y
Definition at line 288 of file adis16448.cpp.
uint16_t ADIS16448::ADISReport::mag_z
Definition at line 289 of file adis16448.cpp.
uint16_t ADIS16448::ADISReport::status
Definition at line 280 of file adis16448.cpp.
uint16_t ADIS16448::ADISReport::temp
Definition at line 291 of file adis16448.cpp.
The documentation for this struct was generated from the following file:
src/drivers/imu/adis16448/adis16448.cpp