PX4 Firmware: px4::Replay Class Reference
px4::Replay Class Reference
Parses an ULog file and replays it in 'real-time'.
#include <replay.hpp>
Classes
class CompatBase
class CompatSensorCombinedDtType
struct Subscription
Public Member Functions
Replay ()=default
virtual ~Replay ()
void run () override
Static Public Member Functions
static int task_spawn (int argc, char *argv[])
static Replay * instantiate (int argc, char *argv[])
static int custom_command (int argc, char *argv[])
static int print_usage (const char *reason=nullptr)
static int applyParams (bool quiet)
Apply the parameters from the log.
static void setupReplayFile (const char *file_name)
Tell the replay module that we want to use replay mode.
static bool isSetup ()
Protected Member Functions
bool publishTopic (Subscription &sub, void *data)
publish an orb topic
virtual void onEnterMainLoop ()
called when entering the main replay loop
virtual void onExitMainLoop ()
called when exiting the main replay loop
virtual void onSubscriptionAdded (Subscription &sub, uint16_t msg_id)
called when a new subscription is added
virtual uint64_t handleTopicDelay (uint64_t next_file_time, uint64_t timestamp_offset)
handle delay until topic can be published.
virtual bool handleTopicUpdate (Subscription &sub, void *data, std::ifstream &replay_file)
handle the publication of a topic update
void readTopicDataToBuffer (const Subscription &sub, std::ifstream &replay_file)
read a topic from the file (offset given by the subscription) into _read_buffer
bool nextDataMessage (std::ifstream &file, Subscription &subscription, int msg_id)
Find next data message for this subscription, starting with the stored file offset.
Static Protected Member Functions
static bool findFieldOffset (const std::string &format, const std::string &field_name, int &offset, int &field_size)
Find the offset & field size in bytes for a given field name.
Protected Attributes
std::vector< Subscription * > _subscriptions
std::vector< uint8_t > _read_buffer
Private Member Functions
bool readFileHeader (std::ifstream &file)
bool readFileDefinitions (std::ifstream &file)
Read definitions section: check formats, apply parameters and store the start of the data section.
bool readFormat (std::ifstream &file, uint16_t msg_size)
file parsing methods. They return false, when further parsing should be aborted.
bool readAndAddSubscription (std::ifstream &file, uint16_t msg_size)
bool readFlagBits (std::ifstream &file, uint16_t msg_size)
bool readDefinitionsAndApplyParams (std::ifstream &file)
Read the file header and definitions sections.
bool readAndHandleAdditionalMessages (std::ifstream &file, std::streampos end_position)
Read and handle additional messages starting at current file position, while position < end_position.
bool readDropout (std::ifstream &file, uint16_t msg_size)
bool readAndApplyParameter (std::ifstream &file, uint16_t msg_size)
void setUserParams (const char *filename)
Static Private Member Functions
static const orb_metadata * findTopic (const std::string &name)
static std::string extractArraySize (const std::string &type_name_full, int &array_size)
get the array size from a type.
static size_t sizeOfType (const std::string &type_name)
get the size of a type that is not an array
static size_t sizeOfFullType (const std::string &type_name_full)
get the size of a type that can be an array
Private Attributes
std::set< std::string > _overridden_params
std::map< std::string, std::string > _file_formats
all formats we read from the file
uint64_t _file_start_time
uint64_t _replay_start_time
std::streampos _data_section_start
first ADD_LOGGED_MSG message
std::streampos _subscription_file_pos = 0
keep track of file position to avoid adding a subscription multiple times.
int64_t _read_until_file_position = 1ULL << 60
read limit if log contains appended data
Static Private Attributes
static char * _replay_file = nullptr
Detailed Description
Parses an ULog file and replays it in 'real-time'.
The timestamp of each replayed message is offset to match the starting time of replay. It keeps a stream for each subscription to find the next message to replay. This is necessary because data messages from different subscriptions don't need to be in monotonic increasing order.
Definition at line 58 of file replay.hpp.
Constructor & Destructor Documentation
px4::Replay::Replay () default
Referenced by applyParams(), and instantiate().
px4::Replay::~Replay () virtual
Definition at line 117 of file replay_main.cpp.
References _subscriptions.
Member Function Documentation
int px4::Replay::applyParams (bool quiet) static
Apply the parameters from the log.
Parameters
quiet do not print an error if true and no log file given via ENV
Returns
0 on success
Definition at line 1202 of file replay_main.cpp.
References _replay_file, isSetup(), PX4_ERR, readDefinitionsAndApplyParams(), and Replay().
Referenced by custom_command().
int px4::Replay::custom_command (int argc, char * argv[]) static
See also
ModuleBase
Definition at line 1128 of file replay_main.cpp.
References applyParams(), print_usage(), and task_spawn().
std::string px4::Replay::extractArraySize (const std::string & type_name_full, int & array_size) static private
get the array size from a type.
eg. float[3] -> return float
Definition at line 653 of file replay_main.cpp.
Referenced by sizeOfFullType().
bool px4::Replay::findFieldOffset (const std::string & format, const std::string & field_name, int & offset, int & field_size) static protected
Find the offset & field size in bytes for a given field name.
Parameters
format format string, as specified by ULog
field_name search for this field
offset returned offset
field_size returned field size
Returns
true if found, false otherwise
Definition at line 443 of file replay_main.cpp.
References sizeOfFullType().
Referenced by readAndAddSubscription().
const orb_metadata * px4::Replay::findTopic (const std::string & name) static private
Definition at line 640 of file replay_main.cpp.
References orb_get_topics(), and orb_topics_count().
Referenced by readAndAddSubscription(), and sizeOfType().
uint64_t px4::Replay::handleTopicDelay (uint64_t next_file_time, uint64_t timestamp_offset) protected virtual
handle delay until topic can be published.
Parameters
next_file_timestamp timestamp of next message to publish
timestamp_offset offset between file start time and replay start time
Returns
timestamp that the message to publish should have
Reimplemented in px4::ReplayEkf2.
Definition at line 867 of file replay_main.cpp.
References _file_start_time, hrt_absolute_time(), and usleep().
Referenced by onSubscriptionAdded(), and run().
bool px4::Replay::handleTopicUpdate (Subscription & sub, void * data, std::ifstream & replay_file) protected virtual
handle the publication of a topic update
Returns
true if published, false otherwise
Reimplemented in px4::ReplayEkf2.
Definition at line 862 of file replay_main.cpp.
References publishTopic().
Referenced by onSubscriptionAdded(), and run().
Replay * px4::Replay::instantiate (int argc, char * argv[]) static
See also
ModuleBase
Definition at line 1231 of file replay_main.cpp.
References instance, PX4_INFO, and Replay().
static bool px4::Replay::isSetup () inline static
Definition at line 94 of file replay.hpp.
References _replay_file.
Referenced by applyParams(), replay_main(), and task_spawn().
bool px4::Replay::nextDataMessage (std::ifstream & file, Subscription & subscription, int msg_id) protected
Find next data message for this subscription, starting with the stored file offset.
Skip the first message, and if found, read the timestamp and store the new file offset. This also takes care of new subscriptions and parameter updates. When reaching EOF, the subscription is set to invalid. File seek position is arbitrary after this call.
Returns
false on file error
Definition at line 556 of file replay_main.cpp.
References _read_until_file_position, ADD_LOGGED_MSG, DATA, DROPOUT, INFO, INFO_MULTIPLE, LOGGING, ulog_message_header_s::msg_size, ulog_message_header_s::msg_type, px4::Replay::Subscription::next_read_pos, px4::Replay::Subscription::next_timestamp, orb_metadata::o_name, orb_metadata::o_size_no_padding, px4::Replay::Subscription::orb_meta, PARAMETER, PX4_ERR, readAndAddSubscription(), REMOVE_LOGGED_MSG, SYNC, px4::Replay::Subscription::timestamp_offset, and ULOG_MSG_HEADER_LEN.
Referenced by px4::ReplayEkf2::findTimestampAndPublish(), onSubscriptionAdded(), readAndAddSubscription(), and run().
virtual void px4::Replay::onEnterMainLoop () inline protected virtual
called when entering the main replay loop
Reimplemented in px4::ReplayEkf2.
Definition at line 168 of file replay.hpp.
Referenced by run().
virtual void px4::Replay::onExitMainLoop () inline protected virtual
called when exiting the main replay loop
Reimplemented in px4::ReplayEkf2.
Definition at line 172 of file replay.hpp.
Referenced by run().
virtual void px4::Replay::onSubscriptionAdded (Subscription & sub, uint16_t msg_id) inline protected virtual
called when a new subscription is added
Reimplemented in px4::ReplayEkf2.
Definition at line 177 of file replay.hpp.
References data, file, handleTopicDelay(), handleTopicUpdate(), nextDataMessage(), and readTopicDataToBuffer().
Referenced by readAndAddSubscription().
int px4::Replay::print_usage (const char * reason = nullptr) static
See also
ModuleBase
Definition at line 1141 of file replay_main.cpp.
References PRINT_MODULE_DESCRIPTION(), PRINT_MODULE_USAGE_COMMAND_DESCR(), PRINT_MODULE_USAGE_DEFAULT_COMMANDS, PRINT_MODULE_USAGE_NAME(), and PX4_WARN.
Referenced by custom_command().
bool px4::Replay::publishTopic (Subscription & sub, void * data) protected
publish an orb topic
Parameters
sub
data
Returns
true if published, false otherwise
Definition at line 883 of file replay_main.cpp.
References _subscriptions, px4::Replay::CompatBase::apply(), px4::Replay::Subscription::compat, instance, px4::Replay::Subscription::multi_id, orb_metadata::o_name, px4::Replay::Subscription::orb_advert, orb_advertise(), orb_advertise_multi(), px4::Replay::Subscription::orb_meta, ORB_PRIO_DEFAULT, orb_publish(), and px4::Replay::Subscription::publication_counter.
Referenced by px4::ReplayEkf2::findTimestampAndPublish(), handleTopicUpdate(), px4::ReplayEkf2::handleTopicUpdate(), and px4::ReplayEkf2::publishEkf2Topics().
bool px4::Replay::readAndAddSubscription (std::ifstream & file, uint16_t msg_size) private
Definition at line 328 of file replay_main.cpp.
References _file_formats, _read_buffer, _subscription_file_pos, _subscriptions, px4::Replay::Subscription::compat, px4::Replay::CompatSensorCombinedDtType::CompatSensorCombinedDtType(), findFieldOffset(), findTopic(), message, px4::Replay::Subscription::multi_id, px4::Replay::Subscription::next_read_pos, nextDataMessage(), orb_metadata::o_fields, orb_metadata::o_name, onSubscriptionAdded(), px4::Replay::Subscription::orb_meta, PX4_DEBUG, PX4_ERR, PX4_WARN, px4::Replay::Subscription::timestamp_offset, and ULOG_MSG_HEADER_LEN.
Referenced by nextDataMessage(), and run().
bool px4::Replay::readAndApplyParameter (std::ifstream & file, uint16_t msg_size) private
Definition at line 506 of file replay_main.cpp.
References _overridden_params, _read_buffer, message, param_find(), PARAM_INVALID, param_name(), param_set(), and PX4_WARN.
Referenced by readAndHandleAdditionalMessages(), and readFileDefinitions().
bool px4::Replay::readAndHandleAdditionalMessages (std::ifstream & file, std::streampos end_position) private
Read and handle additional messages starting at current file position, while position < end_position.
This handles dropout and parameter update messages. We need to handle these separately, because they have no timestamp. We look at the file position instead.
Returns
false on file error
Definition at line 474 of file replay_main.cpp.
References DROPOUT, ulog_message_header_s::msg_size, ulog_message_header_s::msg_type, PARAMETER, readAndApplyParameter(), readDropout(), and ULOG_MSG_HEADER_LEN.
Referenced by run().
bool px4::Replay::readDefinitionsAndApplyParams (std::ifstream & file) private
Read the file header and definitions sections.
Apply the parameters from this section and apply user-defined overridden parameters.
Returns
true on success
Definition at line 707 of file replay_main.cpp.
References PARAMS_OVERRIDE_FILE, PX4_ERR, readFileDefinitions(), readFileHeader(), and setUserParams().
Referenced by applyParams(), and run().
bool px4::Replay::readDropout (std::ifstream & file, uint16_t msg_size) private
Definition at line 547 of file replay_main.cpp.
References PX4_INFO.
Referenced by readAndHandleAdditionalMessages().
bool px4::Replay::readFileDefinitions (std::ifstream & file) private
Read definitions section: check formats, apply parameters and store the start of the data section.
Returns
true on success
Definition at line 201 of file replay_main.cpp.
References _data_section_start, ADD_LOGGED_MSG, FLAG_BITS, FORMAT, INFO, INFO_MULTIPLE, ulog_message_header_s::msg_size, ulog_message_header_s::msg_type, PARAMETER, PX4_ERR, PX4_INFO, readAndApplyParameter(), readFlagBits(), readFormat(), and ULOG_MSG_HEADER_LEN.
Referenced by readDefinitionsAndApplyParams().
bool px4::Replay::readFileHeader (std::ifstream & file) private
Definition at line 178 of file replay_main.cpp.
References _file_start_time, ulog_file_header_s::magic, and ulog_file_header_s::timestamp.
Referenced by readDefinitionsAndApplyParams().
bool px4::Replay::readFlagBits (std::ifstream & file, uint16_t msg_size) private
Definition at line 257 of file replay_main.cpp.
References _read_buffer, _read_until_file_position, message, PX4_ERR, PX4_INFO, and ULOG_INCOMPAT_FLAG0_DATA_APPENDED_MASK.
Referenced by readFileDefinitions().
bool px4::Replay::readFormat (std::ifstream & file, uint16_t msg_size) private
file parsing methods. They return false, when further parsing should be aborted.
Definition at line 303 of file replay_main.cpp.
References _file_formats, _read_buffer, and name.
Referenced by readFileDefinitions().
void px4::Replay::readTopicDataToBuffer (const Subscription & sub, std::ifstream & replay_file) protected
read a topic from the file (offset given by the subscription) into _read_buffer
Definition at line 853 of file replay_main.cpp.
References _read_buffer, px4::Replay::Subscription::next_read_pos, orb_metadata::o_size, orb_metadata::o_size_no_padding, px4::Replay::Subscription::orb_meta, and ULOG_MSG_HEADER_LEN.
Referenced by px4::ReplayEkf2::findTimestampAndPublish(), onSubscriptionAdded(), px4::ReplayEkf2::publishEkf2Topics(), and run().
void px4::Replay::run () override
See also
ModuleBase::run()
Definition at line 737 of file replay_main.cpp.
References _data_section_start, _file_start_time, _read_buffer, _replay_file, _replay_start_time, _subscriptions, handleTopicDelay(), handleTopicUpdate(), hrt_absolute_time(), hrt_elapsed_time(), px4::Replay::Subscription::ignored, ulog_message_header_s::msg_size, px4::Replay::Subscription::next_read_pos, px4::Replay::Subscription::next_timestamp, nextDataMessage(), onEnterMainLoop(), onExitMainLoop(), px4::Replay::Subscription::orb_meta, orb_unadvertise(), PX4_ERR, PX4_INFO, readAndAddSubscription(), readAndHandleAdditionalMessages(), readDefinitionsAndApplyParams(), readTopicDataToBuffer(), px4::Replay::Subscription::timestamp_offset, and ULOG_MSG_HEADER_LEN.
void px4::Replay::setupReplayFile (const char * file_name) static
Tell the replay module that we want to use replay mode.
After that, only 'replay start' must be executed (typically the last step after startup).
Parameters
file_name file name of the used log replay file. Will be copied.
Definition at line 126 of file replay_main.cpp.
References _replay_file.
Referenced by replay_main().
void px4::Replay::setUserParams (const char * filename) private
Definition at line 137 of file replay_main.cpp.
References _overridden_params, param_find(), param_name(), param_set(), param_type(), PARAM_TYPE_FLOAT, PARAM_TYPE_INT32, and PX4_INFO.
Referenced by readDefinitionsAndApplyParams().
size_t px4::Replay::sizeOfFullType (const std::string & type_name_full) static private
get the size of a type that can be an array
Definition at line 700 of file replay_main.cpp.
References extractArraySize(), and sizeOfType().
Referenced by findFieldOffset().
size_t px4::Replay::sizeOfType (const std::string & type_name) static private
get the size of a type that is not an array
Definition at line 667 of file replay_main.cpp.
References findTopic(), orb_metadata::o_size, and PX4_ERR.
Referenced by sizeOfFullType().
int px4::Replay::task_spawn (int argc, char * argv[]) static
See also
ModuleBase
Definition at line 1176 of file replay_main.cpp.
References isSetup(), PX4_ERR, px4_task_spawn_cmd(), SCHED_DEFAULT, and SCHED_PRIORITY_MAX.
Referenced by custom_command().
Member Data Documentation
std::streampos px4::Replay::_data_section_start private
first ADD_LOGGED_MSG message
Definition at line 217 of file replay.hpp.
Referenced by readFileDefinitions(), and run().
std::map<std::string, std::string> px4::Replay::_file_formats private
all formats we read from the file
Definition at line 213 of file replay.hpp.
Referenced by readAndAddSubscription(), and readFormat().
uint64_t px4::Replay::_file_start_time private
Definition at line 215 of file replay.hpp.
Referenced by handleTopicDelay(), readFileHeader(), and run().
std::set<std::string> px4::Replay::_overridden_params private
Definition at line 212 of file replay.hpp.
Referenced by readAndApplyParameter(), and setUserParams().
std::vector<uint8_t> px4::Replay::_read_buffer protected
Definition at line 209 of file replay.hpp.
Referenced by px4::ReplayEkf2::findTimestampAndPublish(), px4::ReplayEkf2::publishEkf2Topics(), readAndAddSubscription(), readAndApplyParameter(), readFlagBits(), readFormat(), readTopicDataToBuffer(), and run().
int64_t px4::Replay::_read_until_file_position = 1ULL << 60 private
read limit if log contains appended data
Definition at line 222 of file replay.hpp.
Referenced by nextDataMessage(), and readFlagBits().
char * px4::Replay::_replay_file = nullptr static private
Definition at line 265 of file replay.hpp.
Referenced by applyParams(), isSetup(), run(), and setupReplayFile().
uint64_t px4::Replay::_replay_start_time private
Definition at line 216 of file replay.hpp.
Referenced by run().
std::streampos px4::Replay::_subscription_file_pos = 0 private
keep track of file position to avoid adding a subscription multiple times.
Definition at line 220 of file replay.hpp.
Referenced by readAndAddSubscription().
std::vector<Subscription *> px4::Replay::_subscriptions protected
Definition at line 208 of file replay.hpp.
Referenced by px4::ReplayEkf2::findTimestampAndPublish(), px4::ReplayEkf2::onExitMainLoop(), px4::ReplayEkf2::publishEkf2Topics(), publishTopic(), readAndAddSubscription(), run(), and ~Replay().
The documentation for this class was generated from the following files:
src/modules/replay/replay.hpp
src/modules/replay/replay_main.cpp