PX4 Firmware: OREOLED Class Reference
OREOLED Class Reference
Public Member Functions
OREOLED (int bus, int i2c_addr, bool autoupdate, bool alwaysupdate)
virtual ~OREOLED ()
virtual int init ()
virtual int probe ()
virtual int info ()
virtual int ioctl (struct file *filp, int cmd, unsigned long arg)
int send_general_call ()
int send_cmd (oreoled_cmd_t sb)
bool is_ready ()
Private Member Functions
void start ()
Start periodic updates to the LEDs.
void stop ()
Stop periodic updates to the LEDs.
void cycle ()
update the colours displayed by the LEDs
int bootloader_app_reset (int led_num)
int bootloader_app_ping (int led_num)
uint16_t bootloader_inapp_checksum (int led_num)
int bootloader_ping (int led_num)
uint8_t bootloader_version (int led_num)
uint16_t bootloader_app_version (int led_num)
uint16_t bootloader_app_checksum (int led_num)
int bootloader_set_colour (int led_num, uint8_t red, uint8_t green)
int bootloader_flash (int led_num)
int bootloader_boot (int led_num)
uint16_t bootloader_fw_checksum (void)
int bootloader_coerce_healthy (void)
Static Private Member Functions
static void cycle_trampoline (void *arg)
static function that is called by worker queue
Private Attributes
work_s _work
work queue for scheduling reads
bool _healthy [OREOLED_NUM_LEDS]
health of each LED
bool _in_boot [OREOLED_NUM_LEDS]
true for each LED that is in bootloader mode
uint8_t _num_healthy
number of healthy LEDs
uint8_t _num_inboot
number of LEDs in bootloader
ringbuffer::RingBuffer * _cmd_queue
buffer of commands to send to LEDs
uint64_t _last_gencall
uint64_t _start_time
system time we first attempt to communicate with battery
bool _autoupdate
true if the driver should update all LEDs
bool _alwaysupdate
true if the driver should update all LEDs
bool _is_bootloading
true if a bootloading operation is in progress
bool _is_ready
set to true once the driver has completly initialised
uint16_t _fw_checksum
the current 16bit XOR checksum of the built in oreoled firmware binary
perf_counter_t _call_perf
perf_counter_t _gcall_perf
perf_counter_t _probe_perf
perf_counter_t _comms_errors
perf_counter_t _reply_errors
Detailed Description
Definition at line 82 of file oreoled.cpp.
Constructor & Destructor Documentation
OREOLED::OREOLED (int bus, int i2c_addr, bool autoupdate, bool alwaysupdate)
Definition at line 171 of file oreoled.cpp.
References _alwaysupdate, _autoupdate, _call_perf, _cmd_queue, _comms_errors, _fw_checksum, _gcall_perf, _healthy, _in_boot, _is_bootloading, _is_ready, _last_gencall, _num_healthy, _num_inboot, _probe_perf, _reply_errors, _start_time, hrt_absolute_time(), PC_COUNT, PC_ELAPSED, and perf_alloc.
Referenced by oreoled_main().
OREOLED::~OREOLED () virtual
Definition at line 200 of file oreoled.cpp.
References _call_perf, _cmd_queue, _comms_errors, _gcall_perf, _probe_perf, _reply_errors, perf_free(), and stop().
Member Function Documentation
uint16_t OREOLED::bootloader_app_checksum (int led_num) private
Definition at line 867 of file oreoled.cpp.
References _is_bootloading, oreoled_cmd_t::buff, oreoled_cmd_t::led_num, oreoled_cmd_t::num_bytes, OEROLED_BOOT_COMMAND_RETRIES, OREOLED_BASE_I2C_ADDR, OREOLED_BOOT_CMD_APP_CRC, OREOLED_CMD_READ_LENGTH_MAX, and warnx.
Referenced by cycle(), and ioctl().
int OREOLED::bootloader_app_ping (int led_num) private
Definition at line 596 of file oreoled.cpp.
References oreoled_cmd_t::buff, oreoled_cmd_t::led_num, oreoled_cmd_t::num_bytes, OEROLED_COMMAND_RETRIES, OK, OREOLED_BASE_I2C_ADDR, OREOLED_CMD_READ_LENGTH_MAX, and OREOLED_PATTERN_OFF.
Referenced by bootloader_coerce_healthy().
int OREOLED::bootloader_app_reset (int led_num) private
Definition at line 546 of file oreoled.cpp.
References _in_boot, _is_bootloading, _num_inboot, oreoled_cmd_t::buff, oreoled_cmd_t::led_num, oreoled_cmd_t::num_bytes, OEROLED_COMMAND_RETRIES, OEROLED_RESET_NONCE, OK, OREOLED_BASE_I2C_ADDR, OREOLED_BOOT_FLASH_WAITMS, OREOLED_CMD_READ_LENGTH_MAX, OREOLED_PARAM_RESET, OREOLED_PATTERN_PARAMUPDATE, and usleep().
Referenced by cycle().
uint16_t OREOLED::bootloader_app_version (int led_num) private
Definition at line 808 of file oreoled.cpp.
References _is_bootloading, oreoled_cmd_t::buff, oreoled_cmd_t::led_num, oreoled_cmd_t::num_bytes, OEROLED_BOOT_COMMAND_RETRIES, OREOLED_BASE_I2C_ADDR, OREOLED_BOOT_CMD_APP_VER, OREOLED_CMD_READ_LENGTH_MAX, and warnx.
Referenced by ioctl().
int OREOLED::bootloader_boot (int led_num) private
Definition at line 1194 of file oreoled.cpp.
References _in_boot, _is_bootloading, _num_inboot, oreoled_cmd_t::buff, oreoled_cmd_t::led_num, oreoled_cmd_t::num_bytes, OEROLED_BOOT_COMMAND_RETRIES, OK, OREOLED_BASE_I2C_ADDR, OREOLED_BOOT_CMD_BOOT_APP, OREOLED_BOOT_CMD_BOOT_NONCE, OREOLED_BOOT_FLASH_WAITMS, OREOLED_CMD_READ_LENGTH_MAX, usleep(), and warnx.
Referenced by cycle(), and ioctl().
int OREOLED::bootloader_coerce_healthy (void) private
Definition at line 1329 of file oreoled.cpp.
References _healthy, _num_healthy, bootloader_app_ping(), OK, and OREOLED_NUM_LEDS.
Referenced by cycle().
int OREOLED::bootloader_flash (int led_num) private
Definition at line 983 of file oreoled.cpp.
References _is_bootloading, bootloader_fw_checksum(), oreoled_cmd_t::buff, errx, fd, oreoled_cmd_t::led_num, oreoled_cmd_t::num_bytes, OEROLED_BOOT_COMMAND_RETRIES, OREOLED_BASE_I2C_ADDR, OREOLED_BOOT_CMD_FINALISE_FLASH, OREOLED_BOOT_CMD_WRITE_FLASH_A, OREOLED_BOOT_CMD_WRITE_FLASH_B, OREOLED_BOOT_FLASH_WAITMS, OREOLED_CMD_READ_LENGTH_MAX, OREOLED_FW_FILE, OREOLED_FW_FILE_HEADER_LENGTH, OREOLED_FW_FILE_SIZE_LIMIT, read(), usleep(), and warnx.
Referenced by cycle(), and ioctl().
uint16_t OREOLED::bootloader_fw_checksum (void) private
Definition at line 1262 of file oreoled.cpp.
References _fw_checksum, fd, OREOLED_FW_FILE, OREOLED_FW_FILE_HEADER_LENGTH, OREOLED_FW_FILE_SIZE_LIMIT, read(), and warnx.
Referenced by bootloader_flash(), and cycle().
uint16_t OREOLED::bootloader_inapp_checksum (int led_num) private
Definition at line 635 of file oreoled.cpp.
References _is_bootloading, oreoled_cmd_t::buff, oreoled_cmd_t::led_num, oreoled_cmd_t::num_bytes, OEROLED_COMMAND_RETRIES, OREOLED_BASE_I2C_ADDR, OREOLED_CMD_READ_LENGTH_MAX, OREOLED_PARAM_APP_CHECKSUM, OREOLED_PATTERN_PARAMUPDATE, and warnx.
Referenced by cycle().
int OREOLED::bootloader_ping (int led_num) private
Definition at line 695 of file oreoled.cpp.
References _is_bootloading, oreoled_cmd_t::buff, oreoled_cmd_t::led_num, oreoled_cmd_t::num_bytes, OEROLED_BOOT_COMMAND_RETRIES, OK, OREOLED_BASE_I2C_ADDR, OREOLED_BOOT_CMD_PING, OREOLED_BOOT_CMD_PING_NONCE, OREOLED_CMD_READ_LENGTH_MAX, and warnx.
Referenced by cycle(), and ioctl().
int OREOLED::bootloader_set_colour (int led_num, uint8_t red, uint8_t green) private
Definition at line 926 of file oreoled.cpp.
References _is_bootloading, oreoled_cmd_t::buff, oreoled_cmd_t::led_num, oreoled_cmd_t::num_bytes, OEROLED_BOOT_COMMAND_RETRIES, OK, OREOLED_BASE_I2C_ADDR, OREOLED_BOOT_CMD_SET_COLOUR, OREOLED_CMD_READ_LENGTH_MAX, and warnx.
Referenced by ioctl().
uint8_t OREOLED::bootloader_version (int led_num) private
Definition at line 752 of file oreoled.cpp.
References _is_bootloading, oreoled_cmd_t::buff, oreoled_cmd_t::led_num, oreoled_cmd_t::num_bytes, OEROLED_BOOT_COMMAND_RETRIES, OREOLED_BASE_I2C_ADDR, OREOLED_BOOT_CMD_BL_VER, OREOLED_BOOT_SUPPORTED_VER, OREOLED_CMD_READ_LENGTH_MAX, and warnx.
Referenced by ioctl().
void OREOLED::cycle () private
update the colours displayed by the LEDs
Definition at line 302 of file oreoled.cpp.
References _alwaysupdate, _autoupdate, _call_perf, _cmd_queue, _comms_errors, _gcall_perf, _healthy, _in_boot, _is_bootloading, _is_ready, _last_gencall, _num_healthy, _num_inboot, _probe_perf, _reply_errors, _start_time, bootloader_app_checksum(), bootloader_app_reset(), bootloader_boot(), bootloader_coerce_healthy(), bootloader_flash(), bootloader_fw_checksum(), bootloader_inapp_checksum(), bootloader_ping(), oreoled_cmd_t::buff, cycle_trampoline(), DEVICE_LOG, hrt_absolute_time(), oreoled_cmd_t::led_num, msg, oreoled_cmd_t::num_bytes, OEROLED_COMMAND_RETRIES, OK, OREOLED_BASE_I2C_ADDR, OREOLED_CMD_LENGTH_MAX, OREOLED_CMD_READ_LENGTH_MAX, OREOLED_GENERALCALL_US, OREOLED_NUM_LEDS, OREOLED_PATTERN_OFF, OREOLED_STARTUP_INTERVAL_US, OREOLED_TIMEOUT_USEC, OREOLED_UPDATE_INTERVAL_US, perf_begin(), perf_count(), perf_end(), and send_general_call().
Referenced by cycle_trampoline().
void OREOLED::cycle_trampoline (void * arg) static private
static function that is called by worker queue
Definition at line 291 of file oreoled.cpp.
References cycle().
Referenced by cycle(), and start().
int OREOLED::info () virtual
Definition at line 255 of file oreoled.cpp.
References _call_perf, _comms_errors, _gcall_perf, _healthy, _probe_perf, _reply_errors, DEVICE_LOG, OK, OREOLED_NUM_LEDS, and perf_print_counter().
int OREOLED::init () virtual
Definition at line 219 of file oreoled.cpp.
References _cmd_queue, lis3mdl::init(), OK, OREOLED_CMD_QUEUE_SIZE, and start().
int OREOLED::ioctl (struct file * filp, int cmd, unsigned long arg) virtual
Definition at line 1349 of file oreoled.cpp.
References _cmd_queue, _healthy, bootloader_app_checksum(), bootloader_app_version(), bootloader_boot(), bootloader_flash(), bootloader_ping(), bootloader_set_colour(), bootloader_version(), oreoled_cmd_t::buff, oreoled_cmd_t::led_num, oreoled_cmd_t::num_bytes, OEROLED_RESET_NONCE, OK, OREOLED_ALL_INSTANCES, OREOLED_BL_APP_CRC, OREOLED_BL_APP_VER, OREOLED_BL_BOOT_APP, OREOLED_BL_FLASH, OREOLED_BL_PING, OREOLED_BL_SET_COLOUR, OREOLED_BL_VER, OREOLED_FORCE_SYNC, OREOLED_NUM_LEDS, OREOLED_PARAM_BIAS_BLUE, OREOLED_PARAM_BIAS_GREEN, OREOLED_PARAM_BIAS_RED, OREOLED_PARAM_MACRO, OREOLED_PARAM_RESET, OREOLED_PATTERN_PARAMUPDATE, OREOLED_RUN_MACRO, OREOLED_SEND_BYTES, OREOLED_SEND_RESET, OREOLED_SET_RGB, send_general_call(), and warnx.
Referenced by oreoled_main().
bool OREOLED::is_ready ()
Definition at line 1593 of file oreoled.cpp.
References _is_ready.
int OREOLED::probe () virtual
Definition at line 245 of file oreoled.cpp.
References OK, and OPEOLED_I2C_RETRYCOUNT.
int OREOLED::send_cmd (oreoled_cmd_t sb)
Definition at line 1574 of file oreoled.cpp.
References _cmd_queue, _healthy, oreoled_cmd_t::led_num, oreoled_cmd_t::num_bytes, OK, OREOLED_BASE_I2C_ADDR, OREOLED_CMD_LENGTH_MAX, and OREOLED_NUM_LEDS.
int OREOLED::send_general_call ()
Definition at line 1551 of file oreoled.cpp.
References _last_gencall, hrt_absolute_time(), msg, and OK.
Referenced by cycle(), and ioctl().
void OREOLED::start () private
Start periodic updates to the LEDs.
Definition at line 278 of file oreoled.cpp.
References cycle_trampoline().
Referenced by init().
void OREOLED::stop () private
Stop periodic updates to the LEDs.
Definition at line 285 of file oreoled.cpp.
Referenced by ~OREOLED().
Member Data Documentation
bool OREOLED::_alwaysupdate private
true if the driver should update all LEDs
Definition at line 147 of file oreoled.cpp.
Referenced by cycle(), and OREOLED().
bool OREOLED::_autoupdate private
true if the driver should update all LEDs
Definition at line 146 of file oreoled.cpp.
Referenced by cycle(), and OREOLED().
perf_counter_t OREOLED::_call_perf private
Definition at line 153 of file oreoled.cpp.
Referenced by cycle(), info(), OREOLED(), and ~OREOLED().
ringbuffer::RingBuffer* OREOLED::_cmd_queue private
buffer of commands to send to LEDs
Definition at line 143 of file oreoled.cpp.
Referenced by cycle(), init(), ioctl(), OREOLED(), send_cmd(), and ~OREOLED().
perf_counter_t OREOLED::_comms_errors private
Definition at line 156 of file oreoled.cpp.
Referenced by cycle(), info(), OREOLED(), and ~OREOLED().
uint16_t OREOLED::_fw_checksum private
the current 16bit XOR checksum of the built in oreoled firmware binary
Definition at line 150 of file oreoled.cpp.
Referenced by bootloader_fw_checksum(), and OREOLED().
perf_counter_t OREOLED::_gcall_perf private
Definition at line 154 of file oreoled.cpp.
Referenced by cycle(), info(), OREOLED(), and ~OREOLED().
bool OREOLED::_healthy[OREOLED_NUM_LEDS] private
health of each LED
Definition at line 139 of file oreoled.cpp.
Referenced by bootloader_coerce_healthy(), cycle(), info(), ioctl(), OREOLED(), and send_cmd().
bool OREOLED::_in_boot[OREOLED_NUM_LEDS] private
true for each LED that is in bootloader mode
Definition at line 140 of file oreoled.cpp.
Referenced by bootloader_app_reset(), bootloader_boot(), cycle(), and OREOLED().
bool OREOLED::_is_bootloading private
true if a bootloading operation is in progress
Definition at line 148 of file oreoled.cpp.
Referenced by bootloader_app_checksum(), bootloader_app_reset(), bootloader_app_version(), bootloader_boot(), bootloader_flash(), bootloader_inapp_checksum(), bootloader_ping(), bootloader_set_colour(), bootloader_version(), cycle(), and OREOLED().
bool OREOLED::_is_ready private
set to true once the driver has completly initialised
Definition at line 149 of file oreoled.cpp.
Referenced by cycle(), is_ready(), and OREOLED().
uint64_t OREOLED::_last_gencall private
Definition at line 144 of file oreoled.cpp.
Referenced by cycle(), OREOLED(), and send_general_call().
uint8_t OREOLED::_num_healthy private
number of healthy LEDs
Definition at line 141 of file oreoled.cpp.
Referenced by bootloader_coerce_healthy(), cycle(), and OREOLED().
uint8_t OREOLED::_num_inboot private
number of LEDs in bootloader
Definition at line 142 of file oreoled.cpp.
Referenced by bootloader_app_reset(), bootloader_boot(), cycle(), and OREOLED().
perf_counter_t OREOLED::_probe_perf private
Definition at line 155 of file oreoled.cpp.
Referenced by cycle(), info(), OREOLED(), and ~OREOLED().
perf_counter_t OREOLED::_reply_errors private
Definition at line 157 of file oreoled.cpp.
Referenced by cycle(), info(), OREOLED(), and ~OREOLED().
uint64_t OREOLED::_start_time private
system time we first attempt to communicate with battery
Definition at line 145 of file oreoled.cpp.
Referenced by cycle(), and OREOLED().
work_s OREOLED::_work private
work queue for scheduling reads
Definition at line 138 of file oreoled.cpp.
The documentation for this class was generated from the following file:
src/drivers/oreoled/oreoled.cpp