PX4 Firmware: FlightTaskManualPositionSmooth Class Reference
FlightTaskManualPositionSmooth Class Reference
#include <FlightTaskManualPositionSmooth.hpp>
Public Member Functions
FlightTaskManualPositionSmooth ()
virtual ~FlightTaskManualPositionSmooth ()=default
Public Member Functions inherited from FlightTaskManualPosition
FlightTaskManualPosition ()
virtual ~FlightTaskManualPosition ()=default
bool activate (vehicle_local_position_setpoint_s last_setpoint) override
Call once on the event where you switch to the task.
bool updateInitialize () override
Call before activate() or update() to initialize time and input data.
void setYawHandler (WeatherVane *yaw_handler) override
Sets an external yaw handler which can be used to implement a different yaw control strategy.
Public Member Functions inherited from FlightTaskManualAltitude
FlightTaskManualAltitude ()=default
virtual ~FlightTaskManualAltitude ()=default
bool update () override
To be called regularly in the control loop cycle to execute the task.
Public Member Functions inherited from FlightTaskManual
FlightTaskManual ()=default
virtual ~FlightTaskManual ()=default
bool applyCommandParameters (const vehicle_command_s &command) override
To be called to adopt parameters from an arrived vehicle command.
Public Member Functions inherited from FlightTask
FlightTask ()
virtual ~FlightTask ()=default
virtual void reActivate ()
Call this to reset an active Flight Task.
virtual bool updateFinalize ()
Call after update() to constrain the generated setpoints in order to comply with the constraints of the current mode.
const vehicle_local_position_setpoint_s getPositionSetpoint ()
Get the output data.
const vehicle_constraints_s & getConstraints ()
Get vehicle constraints.
const landing_gear_s & getGear ()
Get landing gear position.
const vehicle_trajectory_waypoint_s & getAvoidanceWaypoint ()
Get avoidance desired waypoint.
void handleParameterUpdate ()
Call this whenever a parameter update notification is received (parameter_update uORB message)
void updateVelocityControllerIO (const matrix::Vector3f &vel_sp, const matrix::Vector3f &thrust_sp)
Protected Member Functions
virtual void _updateSetpoints () override
updates all setpoints
Protected Member Functions inherited from FlightTaskManualPosition
void _updateXYlock ()
applies position lock based on stick and velocity
void _scaleSticks () override
scales sticks to velocity in z
Protected Member Functions inherited from FlightTaskManualAltitude
void _updateHeadingSetpoints ()
sets yaw or yaw speed
void _ekfResetHandlerHeading (float delta_psi) override
adjust heading setpoint in case of EKF reset event
bool _checkTakeoff () override
Determine when to trigger a takeoff (ignored in flight)
void _rotateIntoHeadingFrame (matrix::Vector2f &vec)
rotates vector into local frame
void _updateAltitudeLock ()
Check and sets for position lock.
DEFINE_PARAMETERS_CUSTOM_PARENT(FlightTaskManual,(ParamFloat< px4::params::MPC_HOLD_MAX_Z >) _param_mpc_hold_max_z,(ParamInt< px4::params::MPC_ALT_MODE >) _param_mpc_alt_mode,(ParamFloat< px4::params::MPC_HOLD_MAX_XY >) _param_mpc_hold_max_xy,(ParamFloat< px4::params::MPC_Z_P >) _param_mpc_z_p,(ParamFloat< px4::params::MPC_MAN_Y_MAX >) _param_mpc_man_y_max,(ParamFloat< px4::params::MPC_MAN_Y_TAU >) _param_mpc_man_y_tau,(ParamFloat< px4::params::MPC_MAN_TILT_MAX >) _param_mpc_man_tilt_max,(ParamFloat< px4::params::MPC_LAND_ALT1 >) _param_mpc_land_alt1,(ParamFloat< px4::params::MPC_LAND_ALT2 >) _param_mpc_land_alt2,(ParamFloat< px4::params::MPC_LAND_SPEED >) _param_mpc_land_speed,(ParamFloat< px4::params::MPC_TKO_SPEED >) _param_mpc_tko_speed) private void _unlockYaw ()
void _lockYaw ()
float _applyYawspeedFilter (float yawspeed_target)
Filter between stick input and yaw setpoint.
void _terrainFollowing (bool apply_brake, bool stopped)
Terrain following.
void _respectMinAltitude ()
Minimum Altitude during range sensor operation.
void _respectMaxAltitude ()
void _respectGroundSlowdown ()
Sets downwards velocity constraint based on the distance to ground.
Protected Member Functions inherited from FlightTaskManual
float stickDeadzone () const
Protected Member Functions inherited from FlightTask
void _resetSetpoints ()
Reset all setpoints to NAN.
void _evaluateVehicleLocalPosition ()
Check and update local position.
virtual void _setDefaultConstraints ()
Set constraints to default values.
void _initEkfResetCounters ()
Monitor the EKF reset counters and call the appropriate handling functions in case of a reset event.
void _checkEkfResetCounters ()
virtual void _ekfResetHandlerPositionXY ()
virtual void _ekfResetHandlerVelocityXY ()
virtual void _ekfResetHandlerPositionZ ()
virtual void _ekfResetHandlerVelocityZ ()
Private Attributes
ManualSmoothingXY _smoothingXY
smoothing for velocity setpoints in xy
ManualSmoothingZ _smoothingZ
smoothing for velocity in z
Additional Inherited Members
Static Public Attributes inherited from FlightTask
static const vehicle_local_position_setpoint_s empty_setpoint = {0, NAN, NAN, NAN, NAN, NAN, NAN, NAN, NAN, {NAN, NAN, NAN}, {NAN, NAN, NAN}, {NAN, NAN, NAN}, {}}
Empty setpoint.
static const vehicle_constraints_s empty_constraints = {0, NAN, NAN, NAN, NAN, NAN, NAN, NAN, false, {}}
Empty constraints.
static const landing_gear_s empty_landing_gear_default_keep = {0, landing_gear_s::GEAR_KEEP, {}}
default landing gear state
Protected Attributes inherited from FlightTaskManualPosition
DEFINE_PARAMETERS_CUSTOM_PARENT(FlightTaskManualAltitude,(ParamFloat< px4::params::MPC_VEL_MANUAL >) _param_mpc_vel_manual,(ParamFloat< px4::params::MPC_ACC_HOR_MAX >) _param_mpc_acc_hor_max,(ParamFloat< px4::params::MPC_HOLD_MAX_XY >) _param_mpc_hold_max_xy,(ParamFloat< px4::params::MPC_ACC_HOR_ESTM >) _param_mpc_acc_hor_estm) private uint8_t _reset_counter {0}
counter for estimator resets in xy-direction
WeatherVane * _weathervane_yaw_handler
external weathervane library, used to implement a yaw control law that turns the vehicle nose into the wind
CollisionPrevention _collision_prevention
collision avoidance setpoint amendment
Protected Attributes inherited from FlightTaskManualAltitude
uORB::SubscriptionData< home_position_s > _sub_home_position {ORB_ID(home_position)}
float _yawspeed_filter_state {}
state of low-pass filter in rad/s
uint8_t _reset_counter = 0
counter for estimator resets in z-direction
float _max_speed_up = 10.0f
float _min_speed_down = 1.0f
bool _terrain_follow {false}
true when the vehicle is following the terrain height
bool _terrain_hold {false}
true when vehicle is controlling height above a static ground position
float _dist_to_ground_lock = NAN
Distance to ground during terrain following.
Protected Attributes inherited from FlightTaskManual
bool _sticks_data_required = true
let inherited task-class define if it depends on stick data
matrix::Vector< float, 4 > _sticks
unmodified manual stick inputs
matrix::Vector< float, 4 > _sticks_expo
modified manual sticks using expo function
int _gear_switch_old = manual_control_setpoint_s::SWITCH_POS_NONE
old switch state
Protected Attributes inherited from FlightTask
uORB::SubscriptionData< vehicle_local_position_s > _sub_vehicle_local_position {ORB_ID(vehicle_local_position)}
uORB::SubscriptionData< vehicle_attitude_s > _sub_attitude {ORB_ID(vehicle_attitude)}
float _time = 0
passed time in seconds since the task was activated
float _deltatime = 0
passed time in seconds since the task was last updated
hrt_abstime _time_stamp_activate = 0
time stamp when task was activated
hrt_abstime _time_stamp_current = 0
time stamp at the beginning of the current task update
hrt_abstime _time_stamp_last = 0
time stamp when task was last updated
matrix::Vector3f _position
current vehicle position
matrix::Vector3f _velocity
current vehicle velocity
float _yaw = 0.f
current vehicle yaw heading
float _dist_to_bottom = 0.0f
current height above ground level
matrix::Vector3f _position_setpoint
Setpoints which the position controller has to execute.
matrix::Vector3f _velocity_setpoint
matrix::Vector3f _acceleration_setpoint
matrix::Vector3f _jerk_setpoint
matrix::Vector3f _thrust_setpoint
float _yaw_setpoint
float _yawspeed_setpoint
matrix::Vector3f _velocity_setpoint_feedback
matrix::Vector3f _thrust_setpoint_feedback
struct {
uint8_t xy = 0
uint8_t vxy = 0
uint8_t z = 0
uint8_t vz = 0
uint8_t quat = 0
} _reset_counters
vehicle_constraints_s _constraints {}
Vehicle constraints.
landing_gear_s _gear {}
vehicle_trajectory_waypoint_s _desired_waypoint {}
Desired waypoints.
Static Protected Attributes inherited from FlightTask
static constexpr uint64_t _timeout = 500000
maximal time in us before a loop or data times out
Detailed Description
Definition at line 46 of file FlightTaskManualPositionSmooth.hpp.
Constructor & Destructor Documentation
FlightTaskManualPositionSmooth()
FlightTaskManualPositionSmooth::FlightTaskManualPositionSmooth ()
Definition at line 42 of file FlightTaskManualPositionSmooth.cpp.
~FlightTaskManualPositionSmooth()
virtual FlightTaskManualPositionSmooth::~FlightTaskManualPositionSmooth () virtual default
Member Function Documentation
_updateSetpoints()
void FlightTaskManualPositionSmooth::_updateSetpoints () override protected virtual
updates all setpoints
Reimplemented from FlightTaskManualPosition.
Definition at line 47 of file FlightTaskManualPositionSmooth.cpp.
References FlightTask::_constraints, FlightTask::_deltatime, _smoothingXY, _smoothingZ, FlightTaskManualAltitude::_updateAltitudeLock(), FlightTaskManualPosition::_updateSetpoints(), FlightTaskManualPosition::_updateXYlock(), FlightTask::_velocity, FlightTask::_velocity_setpoint, FlightTask::_yaw, FlightTask::_yawspeed_setpoint, ManualSmoothingZ::smoothVelFromSticks(), ManualSmoothingXY::smoothVelocity(), vehicle_constraints_s::speed_xy, and ManualSmoothingXY::updateMaxVelocity().
Member Data Documentation
_smoothingXY
ManualSmoothingXY FlightTaskManualPositionSmooth::_smoothingXY private
smoothing for velocity setpoints in xy
Definition at line 58 of file FlightTaskManualPositionSmooth.hpp.
Referenced by _updateSetpoints().
_smoothingZ
ManualSmoothingZ FlightTaskManualPositionSmooth::_smoothingZ private
smoothing for velocity in z
Definition at line 59 of file FlightTaskManualPositionSmooth.hpp.
Referenced by _updateSetpoints().
The documentation for this class was generated from the following files:
src/lib/flight_tasks/tasks/ManualPositionSmooth/FlightTaskManualPositionSmooth.hpp
src/lib/flight_tasks/tasks/ManualPositionSmooth/FlightTaskManualPositionSmooth.cpp