PX4 Firmware: src/systemcmds/tests/test_perf.c File Reference
test_perf.c File Reference
Tests related to the performance counter.
#include <px4_platform_common/px4_config.h>
#include <px4_platform_common/posix.h>
#include <perf/perf_counter.h>
#include "tests_main.h"
Functions
int test_perf (int argc, char *argv[])
Detailed Description
Tests related to the performance counter.
Definition in file test_perf.c.
Function Documentation
test_perf()
int test_perf (int argc, char * argv[])
Definition at line 47 of file test_perf.c.
References OK, PC_COUNT, PC_ELAPSED, perf_alloc, perf_begin(), perf_count(), perf_end(), perf_free(), perf_print_all(), and perf_print_counter().