PX4 Firmware: src/platforms/qurt/tests/muorb/muorb_test_start_qurt.cpp File Reference
muorb_test_start_qurt.cpp File Reference
#include "muorb_test_example.h"
#include <px4_log.h>
#include <px4_app.h>
#include <px4_tasks.h>
#include <stdio.h>
#include <string.h>
#include <sched.h>
Functions
__EXPORT int muorb_test_main (int argc, char *argv[])
int muorb_test_entry (int argc, char **argv)
static void usage ()
Variables
static int daemon_task
Detailed Description
Author
Mark Charlebois mchar.nosp@m.leb@.nosp@m.gmail.nosp@m..com
Definition in file muorb_test_start_qurt.cpp.
Function Documentation
int muorb_test_entry (int argc, char ** argv)
Definition at line 53 of file muorb_test_start_qurt.cpp.
References MuorbTestExample::main(), and PX4_INFO.
Referenced by muorb_test_main().
__EXPORT int muorb_test_main (int argc, char * argv[])
Definition at line 69 of file muorb_test_start_qurt.cpp.
References MuorbTestExample::appState, daemon_task, muorb_test_entry(), PX4_DEBUG, PX4_INFO, px4_task_spawn_cmd(), px4::AppState::requestExit(), SCHED_DEFAULT, SCHED_PRIORITY_MAX, and usage().
static void usage (void) static
Definition at line 65 of file muorb_test_start_qurt.cpp.
References PX4_DEBUG.
Referenced by muorb_test_main().
Variable Documentation
int daemon_task static
Definition at line 47 of file muorb_test_start_qurt.cpp.
Referenced by muorb_test_main().