PX4 Firmware: src/drivers/stm32/drv_io_timer.c File Reference
drv_io_timer.c File Reference
#include <px4_config.h>
#include <nuttx/arch.h>
#include <nuttx/irq.h>
#include <sys/types.h>
#include <stdbool.h>
#include <assert.h>
#include <debug.h>
#include <time.h>
#include <queue.h>
#include <errno.h>
#include <string.h>
#include <stdio.h>
#include <arch/board/board.h>
#include <drivers/drv_pwm_output.h>
#include "drv_io_timer.h"
#include <stm32_gpio.h>
#include <stm32_tim.h>
Macros
#define arraySize(a) (sizeof((a))/sizeof(((a)[0])))
#define BOARD_PWM_FREQ 1000000
#define BOARD_ONESHOT_FREQ 8000000
#define MAX_CHANNELS_PER_TIMER 4
#define _REG32(_base, _reg) (*(volatile uint32_t *)(_base + _reg))
#define REG(_tmr, _reg) _REG32(io_timers[_tmr].base, _reg)
#define rCR1(_tmr) REG(_tmr, STM32_GTIM_CR1_OFFSET)
#define rCR2(_tmr) REG(_tmr, STM32_GTIM_CR2_OFFSET)
#define rSMCR(_tmr) REG(_tmr, STM32_GTIM_SMCR_OFFSET)
#define rDIER(_tmr) REG(_tmr, STM32_GTIM_DIER_OFFSET)
#define rSR(_tmr) REG(_tmr, STM32_GTIM_SR_OFFSET)
#define rEGR(_tmr) REG(_tmr, STM32_GTIM_EGR_OFFSET)
#define rCCMR1(_tmr) REG(_tmr, STM32_GTIM_CCMR1_OFFSET)
#define rCCMR2(_tmr) REG(_tmr, STM32_GTIM_CCMR2_OFFSET)
#define rCCER(_tmr) REG(_tmr, STM32_GTIM_CCER_OFFSET)
#define rCNT(_tmr) REG(_tmr, STM32_GTIM_CNT_OFFSET)
#define rPSC(_tmr) REG(_tmr, STM32_GTIM_PSC_OFFSET)
#define rARR(_tmr) REG(_tmr, STM32_GTIM_ARR_OFFSET)
#define rCCR1(_tmr) REG(_tmr, STM32_GTIM_CCR1_OFFSET)
#define rCCR2(_tmr) REG(_tmr, STM32_GTIM_CCR2_OFFSET)
#define rCCR3(_tmr) REG(_tmr, STM32_GTIM_CCR3_OFFSET)
#define rCCR4(_tmr) REG(_tmr, STM32_GTIM_CCR4_OFFSET)
#define rDCR(_tmr) REG(_tmr, STM32_GTIM_DCR_OFFSET)
#define rDMAR(_tmr) REG(_tmr, STM32_GTIM_DMAR_OFFSET)
#define rBDTR(_tmr) REG(_tmr, STM32_ATIM_BDTR_OFFSET)
#define GTIM_SR_CCIF (GTIM_SR_CC4IF|GTIM_SR_CC3IF|GTIM_SR_CC2IF|GTIM_SR_CC1IF)
#define GTIM_SR_CCOF (GTIM_SR_CC4OF|GTIM_SR_CC3OF|GTIM_SR_CC2OF|GTIM_SR_CC1OF)
#define CCMR_C1_RESET 0x00ff
#define CCMR_C1_NUM_BITS 8
#define CCER_C1_NUM_BITS 4
#define CCMR_C1_CAPTURE_INIT
#define CCMR_C1_PWMOUT_INIT (GTIM_CCMR_MODE_PWM1 << GTIM_CCMR1_OC1M_SHIFT) | GTIM_CCMR1_OC1PE
#define CCMR_C1_PWMIN_INIT 0
#define CCER_C1_INIT GTIM_CCER_CC1E
Typedefs
typedef uint8_t io_timer_allocation_t
Functions
static int io_timer_handler (uint16_t timer_index)
int io_timer_handler0 (int irq, void *context, void *arg)
int io_timer_handler1 (int irq, void *context, void *arg)
int io_timer_handler2 (int irq, void *context, void *arg)
int io_timer_handler3 (int irq, void *context, void *arg)
int io_timer_handler4 (int irq, void *context, void *arg)
static int validate_timer_index (unsigned timer)
static int is_timer_uninitalized (unsigned timer)
static void set_timer_initalized (unsigned timer)
static void set_timer_deinitalized (unsigned timer)
static int channels_timer (unsigned channel)
static int get_timers_firstchannels (unsigned timer)
static uint32_t get_timer_channels (unsigned timer)
static int is_channels_timer_uninitalized (unsigned channel)
int io_timer_is_channel_free (unsigned channel)
int io_timer_validate_channel_index (unsigned channel)
int io_timer_get_mode_channels (io_timer_channel_mode_t mode)
int io_timer_get_channel_mode (unsigned channel)
static int reallocate_channel_resources (uint32_t channels, io_timer_channel_mode_t mode, io_timer_channel_mode_t new_mode)
static int allocate_channel_resource (unsigned channel, io_timer_channel_mode_t mode)
static int free_channel_resource (unsigned channel)
int io_timer_free_channel (unsigned channel)
static int allocate_channel (unsigned channel, io_timer_channel_mode_t mode)
static int timer_set_rate (unsigned timer, unsigned rate)
static void io_timer_set_oneshot_mode (unsigned timer)
static void io_timer_set_PWM_mode (unsigned timer)
void io_timer_trigger (void)
int io_timer_init_timer (unsigned timer)
int io_timer_set_rate (unsigned timer, unsigned rate)
int io_timer_channel_init (unsigned channel, io_timer_channel_mode_t mode, channel_handler_t channel_handler, void *context)
int io_timer_set_enable (bool state, io_timer_channel_mode_t mode, io_timer_channel_allocation_t masks)
int io_timer_set_ccr (unsigned channel, uint16_t value)
uint16_t io_channel_get_ccr (unsigned channel)
uint32_t io_timer_get_group (unsigned timer)
Variables
io_timer_channel_allocation_t channel_allocations [IOTimerChanModeSize] = { UINT8_MAX, 0, 0, 0, 0, 0 }
static io_timer_allocation_t once = 0
Macro Definition Documentation
#define _REG32 (_base, _reg) (*(volatile uint32_t *)(_base + _reg))
Definition at line 85 of file drv_io_timer.c.
Referenced by io_timer_set_enable(), and io_timer_trigger().
#define arraySize (a) (sizeof((a))/sizeof(((a)[0])))
Definition at line 66 of file drv_io_timer.c.
Referenced by io_timer_set_enable().
#define BOARD_ONESHOT_FREQ 8000000
Definition at line 80 of file drv_io_timer.c.
Referenced by io_timer_set_oneshot_mode().
#define BOARD_PWM_FREQ 1000000
Definition at line 76 of file drv_io_timer.c.
Referenced by io_timer_set_PWM_mode(), and timer_set_rate().
#define CCER_C1_INIT GTIM_CCER_CC1E
Definition at line 126 of file drv_io_timer.c.
Referenced by io_timer_channel_init(), and io_timer_set_enable().
#define CCER_C1_NUM_BITS 4
Definition at line 113 of file drv_io_timer.c.
Referenced by io_timer_channel_init(), and io_timer_set_enable().
#define CCMR_C1_CAPTURE_INIT
Value:
(GTIM_CCMR_CCS_CCIN1  << GTIM_CCMR1_CC1S_SHIFT) | \
    (GTIM_CCMR_ICPSC_NOPSC << GTIM_CCMR1_IC1PSC_SHIFT) | \
    (GTIM_CCMR_ICF_NOFILT << GTIM_CCMR1_IC1F_SHIFT)
Definition at line 115 of file drv_io_timer.c.
Referenced by io_timer_channel_init().
#define CCMR_C1_NUM_BITS 8
Definition at line 112 of file drv_io_timer.c.
Referenced by io_timer_channel_init().
#define CCMR_C1_PWMIN_INIT 0
Definition at line 121 of file drv_io_timer.c.
Referenced by io_timer_channel_init().
#define CCMR_C1_PWMOUT_INIT (GTIM_CCMR_MODE_PWM1 << GTIM_CCMR1_OC1M_SHIFT) | GTIM_CCMR1_OC1PE
Definition at line 119 of file drv_io_timer.c.
Referenced by io_timer_channel_init().
#define CCMR_C1_RESET 0x00ff
Definition at line 111 of file drv_io_timer.c.
Referenced by io_timer_channel_init().
#define GTIM_SR_CCIF (GTIM_SR_CC4IF|GTIM_SR_CC3IF|GTIM_SR_CC2IF|GTIM_SR_CC1IF)
Definition at line 108 of file drv_io_timer.c.
Referenced by io_timer_handler().
#define GTIM_SR_CCOF (GTIM_SR_CC4OF|GTIM_SR_CC3OF|GTIM_SR_CC2OF|GTIM_SR_CC1OF)
Definition at line 109 of file drv_io_timer.c.
Referenced by io_timer_handler().
#define MAX_CHANNELS_PER_TIMER 4
Definition at line 83 of file drv_io_timer.c.
Referenced by io_timer_set_enable().
#define rARR (_tmr) REG(_tmr, STM32_GTIM_ARR_OFFSET)
Definition at line 99 of file drv_io_timer.c.
Referenced by io_timer_set_oneshot_mode(), and timer_set_rate().
#define rBDTR (_tmr) REG(_tmr, STM32_ATIM_BDTR_OFFSET)
Definition at line 106 of file drv_io_timer.c.
Referenced by io_timer_init_timer(), and ToneAlarm::~ToneAlarm().
#define rCCER (_tmr) REG(_tmr, STM32_GTIM_CCER_OFFSET)
Definition at line 96 of file drv_io_timer.c.
Referenced by io_timer_channel_init(), and io_timer_init_timer().
#define rCCMR1 (_tmr) REG(_tmr, STM32_GTIM_CCMR1_OFFSET)
Definition at line 94 of file drv_io_timer.c.
Referenced by io_timer_init_timer().
#define rCCMR2 (_tmr) REG(_tmr, STM32_GTIM_CCMR2_OFFSET)
Definition at line 95 of file drv_io_timer.c.
Referenced by io_timer_init_timer().
#define rCCR1 (_tmr) REG(_tmr, STM32_GTIM_CCR1_OFFSET)
Definition at line 100 of file drv_io_timer.c.
Referenced by io_timer_init_timer().
#define rCCR2 (_tmr) REG(_tmr, STM32_GTIM_CCR2_OFFSET)
Definition at line 101 of file drv_io_timer.c.
Referenced by io_timer_init_timer().
#define rCCR3 (_tmr) REG(_tmr, STM32_GTIM_CCR3_OFFSET)
Definition at line 102 of file drv_io_timer.c.
Referenced by io_timer_init_timer().
#define rCCR4 (_tmr) REG(_tmr, STM32_GTIM_CCR4_OFFSET)
Definition at line 103 of file drv_io_timer.c.
Referenced by io_timer_init_timer().
#define rCNT (_tmr) REG(_tmr, STM32_GTIM_CNT_OFFSET)
Definition at line 97 of file drv_io_timer.c.
Referenced by io_timer_handler().
#define rCR1 (_tmr) REG(_tmr, STM32_GTIM_CR1_OFFSET)
Definition at line 88 of file drv_io_timer.c.
Referenced by io_timer_init_timer(), and io_timer_set_enable().
#define rCR2 (_tmr) REG(_tmr, STM32_GTIM_CR2_OFFSET)
Definition at line 89 of file drv_io_timer.c.
Referenced by io_timer_init_timer().
#define rDCR (_tmr) REG(_tmr, STM32_GTIM_DCR_OFFSET)
Definition at line 104 of file drv_io_timer.c.
Referenced by io_timer_init_timer().
#define rDIER (_tmr) REG(_tmr, STM32_GTIM_DIER_OFFSET)
Definition at line 91 of file drv_io_timer.c.
Referenced by io_timer_channel_init(), io_timer_handler(), and io_timer_init_timer().
#define rDMAR (_tmr) REG(_tmr, STM32_GTIM_DMAR_OFFSET)
Definition at line 105 of file drv_io_timer.c.
#define REG (_tmr, _reg) _REG32(io_timers[_tmr].base, _reg)
Definition at line 86 of file drv_io_timer.c.
Referenced by io_channel_get_ccr(), io_timer_channel_init(), and io_timer_set_ccr().
#define rEGR (_tmr) REG(_tmr, STM32_GTIM_EGR_OFFSET)
Definition at line 93 of file drv_io_timer.c.
Referenced by io_timer_set_enable(), io_timer_set_oneshot_mode(), and timer_set_rate().
#define rPSC (_tmr) REG(_tmr, STM32_GTIM_PSC_OFFSET)
Definition at line 98 of file drv_io_timer.c.
Referenced by io_timer_set_oneshot_mode(), and io_timer_set_PWM_mode().
#define rSMCR (_tmr) REG(_tmr, STM32_GTIM_SMCR_OFFSET)
Definition at line 90 of file drv_io_timer.c.
Referenced by io_timer_init_timer().
#define rSR (_tmr) REG(_tmr, STM32_GTIM_SR_OFFSET)
Definition at line 92 of file drv_io_timer.c.
Referenced by io_timer_handler().
Typedef Documentation
typedef uint8_t io_timer_allocation_t
Definition at line 131 of file drv_io_timer.c.
Function Documentation
static int allocate_channel (unsigned channel, io_timer_channel_mode_t mode) static
Definition at line 441 of file drv_io_timer.c.
References allocate_channel_resource(), io_timer_validate_channel_index(), and IOTimerChanMode_NotUsed.
Referenced by io_timer_channel_init().
static int allocate_channel_resource (unsigned channel, io_timer_channel_mode_t mode) inline static
Definition at line 396 of file drv_io_timer.c.
References channel_allocations, io_timer_is_channel_free(), and IOTimerChanMode_NotUsed.
Referenced by allocate_channel().
static int channels_timer (unsigned channel) inline static
Definition at line 267 of file drv_io_timer.c.
References timer_io_channels_t::timer_index, and timer_io_channels.
Referenced by io_channel_get_ccr(), io_timer_channel_init(), io_timer_set_ccr(), io_timer_set_enable(), and is_channels_timer_uninitalized().
static int free_channel_resource (unsigned channel) inline static
Definition at line 410 of file drv_io_timer.c.
References channel_allocations, io_timer_get_channel_mode(), and IOTimerChanMode_NotUsed.
Referenced by io_timer_free_channel().
static uint32_t get_timer_channels (unsigned timer) static
Definition at line 283 of file drv_io_timer.c.
References io_timers_t::first_channel_index, io_timers, MAX_IO_TIMERS, and validate_timer_index().
Referenced by io_timer_get_group(), io_timer_set_rate(), and io_timer_trigger().
static int get_timers_firstchannels (unsigned timer) inline static
Definition at line 272 of file drv_io_timer.c.
References io_timers_t::first_channel_index, io_timers, timer_io_channels_t::timer_channel, timer_io_channels, and validate_timer_index().
uint16_t io_channel_get_ccr (unsigned channel)
Definition at line 892 of file drv_io_timer.c.
References channels_timer(), io_timer_get_channel_mode(), io_timer_validate_channel_index(), IOTimerChanMode_OneShot, IOTimerChanMode_PWMOut, IOTimerChanMode_Trigger, REG, and timer_io_channels.
int io_timer_channel_init (unsigned channel, io_timer_channel_mode_t mode, channel_handler_t channel_handler, void * context)
Definition at line 639 of file drv_io_timer.c.
References allocate_channel(), channel_handler_entry::callback, CCER_C1_INIT, CCER_C1_NUM_BITS, CCMR_C1_CAPTURE_INIT, CCMR_C1_NUM_BITS, CCMR_C1_PWMIN_INIT, CCMR_C1_PWMOUT_INIT, CCMR_C1_RESET, channel_handlers, channels_timer(), CnSC_CAPTURE_INIT, CnSC_PWMOUT_INIT, CnSC_RESET, channel_handler_entry::context, timer_io_channels_t::gpio_in, io_timer_init_timer(), IOTimerChanMode_Capture, IOTimerChanMode_NotUsed, IOTimerChanMode_OneShot, IOTimerChanMode_PWMIn, IOTimerChanMode_PWMOut, IOTimerChanMode_Trigger, rCCER, rDIER, REG, timer_io_channels_t::timer_channel, timer_io_channels, and UNUSED.
int io_timer_free_channel (unsigned channel)
Definition at line 423 of file drv_io_timer.c.
References free_channel_resource(), io_timer_get_channel_mode(), io_timer_set_enable(), io_timer_validate_channel_index(), and IOTimerChanMode_NotUsed.
int io_timer_get_channel_mode (unsigned channel)
Definition at line 357 of file drv_io_timer.c.
References channel_allocations, IOTimerChanMode_NotUsed, and IOTimerChanModeSize.
uint32_t io_timer_get_group (unsigned timer)
Definition at line 909 of file drv_io_timer.c.
References get_timer_channels().
int io_timer_get_mode_channels (io_timer_channel_mode_t mode)
Definition at line 348 of file drv_io_timer.c.
References channel_allocations, and IOTimerChanModeSize.
static int io_timer_handler (uint16_t timer_index) static
Definition at line 153 of file drv_io_timer.c.
References channel_handler_entry::callback, channel_handlers, io_timers_t::first_channel_index, GTIM_SR_CCIF, GTIM_SR_CCOF, hrt_absolute_time(), hrt_abstime, io_timers, channel_stat_t::isr_cout, timer_io_channels_t::masks, channel_stat_t::overflows, rCNT, rDIER, rSR, and timer_io_channels.
Referenced by io_timer_handler0(), io_timer_handler1(), io_timer_handler2(), io_timer_handler3(), and io_timer_handler4().
int io_timer_handler0 (int irq, void * context, void * arg)
Definition at line 211 of file drv_io_timer.c.
References io_timer_handler().
int io_timer_handler1 (int irq, void * context, void * arg)
Definition at line 217 of file drv_io_timer.c.
References io_timer_handler().
int io_timer_handler2 (int irq, void * context, void * arg)
Definition at line 223 of file drv_io_timer.c.
References io_timer_handler().
int io_timer_handler3 (int irq, void * context, void * arg)
Definition at line 229 of file drv_io_timer.c.
References io_timer_handler().
int io_timer_handler4 (int irq, void * context, void * arg)
Definition at line 235 of file drv_io_timer.c.
References io_timer_handler().
int io_timer_init_timer (unsigned timer)
Definition at line 523 of file drv_io_timer.c.
References _REG, io_timers_t::clock_bit, io_timer_set_PWM_mode(), io_timers, is_timer_uninitalized(), rBDTR, rCCER, rCCMR1, rCCMR2, rCCR1, rCCR2, rCCR3, rCCR4, rCNT, rCONF, rCR1, rCR2, rDCR, rDIER, rMODE, rSC, rSMCR, rSYNCONF, set_timer_initalized(), and timer_set_rate().
int io_timer_is_channel_free (unsigned channel)
Definition at line 315 of file drv_io_timer.c.
References channel_allocations, io_timer_validate_channel_index(), and IOTimerChanMode_NotUsed.
int io_timer_set_ccr (unsigned channel, uint16_t value)
Definition at line 869 of file drv_io_timer.c.
References channels_timer(), io_timer_get_channel_mode(), io_timer_validate_channel_index(), IOTimerChanMode_OneShot, IOTimerChanMode_PWMOut, IOTimerChanMode_Trigger, REG, rSC, and timer_io_channels.
int io_timer_set_enable (bool state, io_timer_channel_mode_t mode, io_timer_channel_allocation_t masks)
Definition at line 752 of file drv_io_timer.c.
References _REG, _REG32, arraySize, io_timers_t::base, CCER_C1_INIT, CCER_C1_NUM_BITS, channel_allocations, channels_timer(), CnSC_PWMOUT_INIT, FTM_SYNC, timer_io_channels_t::gpio_out, IO_TIMER_ALL_MODES_CHANNELS, io_timer_validate_channel_index(), io_timers, IOTimerChanMode_Capture, IOTimerChanMode_NotUsed, IOTimerChanMode_OneShot, IOTimerChanMode_PWMIn, IOTimerChanMode_PWMOut, IOTimerChanMode_Trigger, MAX_CHANNELS_PER_TIMER, MAX_IO_TIMERS, MAX_TIMER_IO_CHANNELS, rCR1, rEGR, timer_io_channels_t::timer_channel, and timer_io_channels.
static void io_timer_set_oneshot_mode (unsigned timer) inline static
Definition at line 470 of file drv_io_timer.c.
References BOARD_ONESHOT_FREQ, io_timers_t::clock_freq, io_timers, rARR, rEGR, and rPSC.
Referenced by io_timer_set_rate().
static void io_timer_set_PWM_mode (unsigned timer) inline static
Definition at line 486 of file drv_io_timer.c.
References BOARD_PWM_FREQ, io_timers_t::clock_freq, io_timers, and rPSC.
Referenced by io_timer_init_timer(), and io_timer_set_rate().
int io_timer_set_rate (unsigned timer, unsigned rate)
Definition at line 586 of file drv_io_timer.c.
References channel_allocations, get_timer_channels(), io_timer_set_oneshot_mode(), io_timer_set_PWM_mode(), IOTimerChanMode_NotUsed, IOTimerChanMode_OneShot, IOTimerChanMode_PWMOut, OK, reallocate_channel_resources(), and timer_set_rate().
void io_timer_trigger (void)
Definition at line 491 of file drv_io_timer.c.
References _REG32, io_timers_t::base, FTM_SYNC, get_timer_channels(), io_timer_get_mode_channels(), io_timers, IOTimerChanMode_OneShot, MAX_IO_TIMERS, and validate_timer_index().
int io_timer_validate_channel_index (unsigned channel)
Definition at line 328 of file drv_io_timer.c.
References io_timers, MAX_TIMER_IO_CHANNELS, timer_io_channels_t::timer_index, and timer_io_channels.
static int is_channels_timer_uninitalized (unsigned channel) inline static
Definition at line 310 of file drv_io_timer.c.
References channels_timer(), and is_timer_uninitalized().
static int is_timer_uninitalized (unsigned timer) inline static
Definition at line 246 of file drv_io_timer.c.
References once.
Referenced by io_timer_init_timer(), and is_channels_timer_uninitalized().
static int reallocate_channel_resources (uint32_t channels, io_timer_channel_mode_t mode, io_timer_channel_mode_t new_mode) static
Definition at line 370 of file drv_io_timer.c.
References channel_allocations, and IOTimerChanMode_NotUsed.
Referenced by io_timer_set_rate().
static void set_timer_deinitalized (unsigned timer) inline static
Definition at line 262 of file drv_io_timer.c.
References once.
static void set_timer_initalized (unsigned timer) inline static
Definition at line 257 of file drv_io_timer.c.
References once.
Referenced by io_timer_init_timer().
static int timer_set_rate (unsigned timer, unsigned rate) static
Definition at line 456 of file drv_io_timer.c.
References BOARD_PWM_FREQ, rARR, and rEGR.
Referenced by io_timer_init_timer(), and io_timer_set_rate().
static int validate_timer_index (unsigned timer) inline static
Definition at line 241 of file drv_io_timer.c.
References io_timers, and MAX_IO_TIMERS.
Referenced by get_timer_channels(), get_timers_firstchannels(), and io_timer_trigger().
Variable Documentation
io_timer_channel_allocation_t channel_allocations[IOTimerChanModeSize] = { UINT8_MAX, 0, 0, 0, 0, 0 }
Definition at line 129 of file drv_io_timer.c.
io_timer_allocation_t once = 0 static
Definition at line 133 of file drv_io_timer.c.
Referenced by is_timer_uninitalized(), set_timer_deinitalized(), and set_timer_initalized().