PX4 Firmware: leddar_one Namespace Reference
leddar_one Namespace Reference
Local functions in support of the shell command.
Functions
int start (const char *port=LEDDAR_ONE_DEFAULT_SERIAL_PORT, const uint8_t rotation=distance_sensor_s::ROTATION_DOWNWARD_FACING)
int status ()
Print the driver status.
int stop ()
Stop the driver.
int test (const char *port)
Perform some basic functional tests on the driver; make sure we can collect data from the sensor in polled and automatic modes.
int usage ()
Prints info about the driver argument usage.
Variables
LeddarOne * g_dev
Detailed Description
Local functions in support of the shell command.
Function Documentation
start()
int leddar_one::start (const char * port = LEDDAR_ONE_DEFAULT_SERIAL_PORT, const uint8_t rotation = distance_sensor_s::ROTATION_DOWNWARD_FACING)
Definition at line 457 of file leddar_one.cpp.
References DEVICE_PATH, g_dev, LeddarOne::init(), LeddarOne::LeddarOne(), and LeddarOne::start().
Referenced by leddar_one_main().
status()
int leddar_one::status ()
Print the driver status.
Definition at line 489 of file leddar_one.cpp.
References LeddarOne::print_info().
Referenced by leddar_one_main().
stop()
int leddar_one::stop ()
Stop the driver.
Definition at line 505 of file leddar_one.cpp.
References g_dev.
Referenced by leddar_one_main().
test()
int leddar_one::test (const char * port = LEDDAR_ONE_DEFAULT_SERIAL_PORT)
Perform some basic functional tests on the driver; make sure we can collect data from the sensor in polled and automatic modes.
Definition at line 523 of file leddar_one.cpp.
References cdev::CDev::close(), fd, LEDDAR_ONE_MEASURE_INTERVAL, cdev::CDev::open(), cdev::CDev::read(), request_reading_msg, and cdev::CDev::write().
Referenced by leddar_one_main().
usage()
int leddar_one::usage (void)
Prints info about the driver argument usage.
Definition at line 561 of file leddar_one.cpp.
Referenced by leddar_one_main().
Variable Documentation
g_dev
LeddarOne* leddar_one::g_dev
Definition at line 448 of file leddar_one.cpp.
Referenced by start(), and stop().