PX4 Firmware: src/modules/systemlib/print_load_posix.c File Reference
print_load_posix.c File Reference
Print the current system load.
#include <px4_posix.h>
#include <unistd.h>
#include <string.h>
#include <stdio.h>
#include <stdbool.h>
#include <systemlib/cpuload.h>
#include <systemlib/printload.h>
#include <drivers/drv_hrt.h>
Macros
#define CL "\033[K"
Functions
void init_print_load_s (uint64_t t, struct print_load_s *s)
void print_load (uint64_t t, int fd, struct print_load_s *print_state)
void print_load_buffer (uint64_t t, char *buffer, int buffer_length, print_load_callback_f cb, void *user, struct print_load_s *print_state)
Print load to a buffer, and call cb after each written line (buffer will not include '
')
Variables
struct system_load_s system_load
Detailed Description
Print the current system load.
Author
Lorenz Meier loren.nosp@m.z@px.nosp@m.4.io
Definition in file print_load_posix.c.
Macro Definition Documentation
#define CL "\033[K"
Definition at line 64 of file print_load_posix.c.
Referenced by print_load().
Function Documentation
void init_print_load_s (uint64_t t, struct print_load_s * s)
Definition at line 66 of file print_load_posix.c.
References print_load_s::blocked_count, CONFIG_MAX_TASKS, print_load_s::interval_start_time, print_load_s::interval_time_ms_inv, print_load_s::last_times, print_load_s::new_time, print_load_s::running_count, and print_load_s::total_user_time.
void print_load (uint64_t t, int fd, struct print_load_s * print_state)
Definition at line 84 of file print_load_posix.c.
References print_load_callback_data_s::buffer, CL, print_load_callback_data_s::fd, print_load_buffer(), print_load_callback(), and PX4_WARN.
void print_load_buffer (uint64_t t, char * buffer, int buffer_length, print_load_callback_f cb, void * user, struct print_load_s * print_state)
Print load to a buffer, and call cb after each written line (buffer will not include '
')
Definition at line 178 of file print_load_posix.c.
References print_load_s::blocked_count, board_get_dma_usage, CONFIG_MAX_TASKS, f(), print_load_s::interval_start_time, print_load_s::interval_time_ms_inv, print_load_s::last_times, print_load_s::new_time, print_load_s::running_count, system_load, print_load_s::total_user_time, and tstate_name().
Variable Documentation
struct system_load_s system_load