PX4 Firmware: ManualSmoothingZ Class Reference
ManualSmoothingZ Class Reference
#include <ManualSmoothingZ.hpp>
Public Member Functions
ManualSmoothingZ (ModuleParams *parent, const float &vel, const float &stick)
~ManualSmoothingZ ()=default
void smoothVelFromSticks (float &vel_sp, const float dt)
Smooth velocity setpoint based on flight direction.
float getMaxAcceleration ()
Get max accleration.
ManualIntentionZ getIntention ()
Get user intention.
void overwriteAccelerationUp (float acc_max_up)
void overwriteAccelerationDown (float acc_max_down)
void overwriteJerkMax (float jerk_max)
Public Member Functions inherited from ModuleParams
ModuleParams (ModuleParams *parent)
void setParent (ModuleParams *parent)
Set the parent module.
virtual ~ModuleParams ()=default
ModuleParams (const ModuleParams &)=delete
ModuleParams & operator= (const ModuleParams &)=delete
ModuleParams (ModuleParams &&)=delete
ModuleParams & operator= (ModuleParams &&)=delete
Public Member Functions inherited from ListNode< ModuleParams * >
ListNode ()
ListNode (const ListNode &)=delete
ListNode (ListNode &&)=delete
virtual ~ListNode ()=default
ListNode & operator= (const ListNode &)=delete
ListNode & operator= (ListNode &&)=delete
void setSibling (ModuleParams *sibling)
const ModuleParams * getSibling ()
Private Member Functions
void velocitySlewRate (float &vel_sp, const float dt)
Add delay to velocity setpoint change.
void updateAcceleration (float &vel_sp, const float dt)
Computes the velocity setpoint change limit.
void setMaxAcceleration ()
Set maximum acceleration.
Private Attributes
ManualIntentionZ _intention {ManualIntentionZ::acceleration}
User intention.
const float & _vel
vehicle velocity (dependency injection)
const float & _stick
stick input (dependency injection)
float _acc_state_dependent
acceleration that depends on _intention
float _max_acceleration
can be up or down maximum acceleration
float _vel_sp_prev
previous velocity setpoint
Additional Inherited Members
Protected Member Functions inherited from ModuleParams
virtual void updateParams ()
Call this whenever the module gets a parameter change notification.
virtual void updateParamsImpl ()
The implementation for this is generated with the macro DEFINE_PARAMETERS()
Protected Attributes inherited from ListNode< ModuleParams * >
ModuleParams * _sibling
Detailed Description
Definition at line 55 of file ManualSmoothingZ.hpp.
Constructor & Destructor Documentation
ManualSmoothingZ::ManualSmoothingZ (ModuleParams * parent, const float & vel, const float & stick)
Definition at line 43 of file ManualSmoothingZ.cpp.
References _acc_state_dependent, and _max_acceleration.
ManualSmoothingZ::~ManualSmoothingZ () default
Member Function Documentation
ManualIntentionZ ManualSmoothingZ::getIntention () inline
Get user intention.
See also
ManualIntentionZ
Definition at line 79 of file ManualSmoothingZ.hpp.
Referenced by SmoothZTest::accelerateDownwardFromBrake(), SmoothZTest::accelerateUpwardFromBrake(), SmoothZTest::brakeDownward(), and SmoothZTest::brakeUpward().
float ManualSmoothingZ::getMaxAcceleration () inline
Get max accleration.
Definition at line 73 of file ManualSmoothingZ.hpp.
Referenced by SmoothZTest::accelerateDownwardFromBrake(), SmoothZTest::accelerateUpwardFromBrake(), SmoothZTest::brakeDownward(), SmoothZTest::brakeUpward(), and updateAcceleration().
void ManualSmoothingZ::overwriteAccelerationDown (float acc_max_down) inline
Definition at line 86 of file ManualSmoothingZ.hpp.
Referenced by SmoothZTest::accelerateDownwardFromBrake(), SmoothZTest::accelerateUpwardFromBrake(), SmoothZTest::brakeDownward(), and SmoothZTest::brakeUpward().
void ManualSmoothingZ::overwriteAccelerationUp (float acc_max_up) inline
Definition at line 85 of file ManualSmoothingZ.hpp.
Referenced by SmoothZTest::accelerateDownwardFromBrake(), SmoothZTest::accelerateUpwardFromBrake(), SmoothZTest::brakeDownward(), and SmoothZTest::brakeUpward().
void ManualSmoothingZ::overwriteJerkMax (float jerk_max) inline
Definition at line 87 of file ManualSmoothingZ.hpp.
Referenced by SmoothZTest::accelerateDownwardFromBrake(), SmoothZTest::accelerateUpwardFromBrake(), SmoothZTest::brakeDownward(), and SmoothZTest::brakeUpward().
void ManualSmoothingZ::setMaxAcceleration () private
Set maximum acceleration.
The maximum acceleration depends on the desired direction (up vs down).
See also
_max_acceleration
Definition at line 117 of file ManualSmoothingZ.cpp.
References _max_acceleration, _stick, _vel_sp_prev, and f().
Referenced by updateAcceleration().
void ManualSmoothingZ::smoothVelFromSticks (float & vel_sp, const float dt)
Smooth velocity setpoint based on flight direction.
Parameters
vel_sp[2] array: vel_sp[0] = current velocity set-point; vel_sp[1] = previous velocity set-point vel_sp will contain smoothed current / previous set-point.
dt time delta in seconds
Definition at line 52 of file ManualSmoothingZ.cpp.
References _vel_sp_prev, updateAcceleration(), and velocitySlewRate().
Referenced by FlightTaskManualAltitudeSmooth::_updateSetpoints(), FlightTaskManualPositionSmooth::_updateSetpoints(), SmoothZTest::accelerateDownwardFromBrake(), SmoothZTest::accelerateUpwardFromBrake(), SmoothZTest::brakeDownward(), and SmoothZTest::brakeUpward().
void ManualSmoothingZ::updateAcceleration (float & vel_sp, const float dt) private
Computes the velocity setpoint change limit.
This method computes the limit with which the velocity setpoint change is limited.
See also
velocitySlewRate
Parameters
vel_sp current velocity setpoint
dt delta-time
Definition at line 60 of file ManualSmoothingZ.cpp.
References _acc_state_dependent, _intention, _stick, _vel, _vel_sp_prev, acceleration, brake, getMaxAcceleration(), and setMaxAcceleration().
Referenced by smoothVelFromSticks().
void ManualSmoothingZ::velocitySlewRate (float & vel_sp, const float dt) private
Add delay to velocity setpoint change.
This method is used to smooth the velocity setpoint change.
Parameters
vel_sp current velocity setpoint
dt delta-time
Definition at line 146 of file ManualSmoothingZ.cpp.
References _acc_state_dependent, and _vel_sp_prev.
Referenced by smoothVelFromSticks().
Member Data Documentation
float ManualSmoothingZ::_acc_state_dependent private
acceleration that depends on _intention
Definition at line 124 of file ManualSmoothingZ.hpp.
Referenced by ManualSmoothingZ(), updateAcceleration(), and velocitySlewRate().
ManualIntentionZ ManualSmoothingZ::_intention {ManualIntentionZ::acceleration} private
User intention.
See also
ManualIntentionZ
Definition at line 119 of file ManualSmoothingZ.hpp.
Referenced by updateAcceleration().
float ManualSmoothingZ::_max_acceleration private
can be up or down maximum acceleration
Definition at line 125 of file ManualSmoothingZ.hpp.
Referenced by ManualSmoothingZ(), and setMaxAcceleration().
const float& ManualSmoothingZ::_stick private
stick input (dependency injection)
Definition at line 122 of file ManualSmoothingZ.hpp.
Referenced by setMaxAcceleration(), and updateAcceleration().
const float& ManualSmoothingZ::_vel private
vehicle velocity (dependency injection)
Definition at line 121 of file ManualSmoothingZ.hpp.
Referenced by updateAcceleration().
float ManualSmoothingZ::_vel_sp_prev private
previous velocity setpoint
Definition at line 126 of file ManualSmoothingZ.hpp.
Referenced by setMaxAcceleration(), smoothVelFromSticks(), updateAcceleration(), and velocitySlewRate().
The documentation for this class was generated from the following files:
src/lib/FlightTasks/tasks/Utility/ManualSmoothingZ.hpp
src/lib/FlightTasks/tasks/Utility/ManualSmoothingZ.cpp