PX4 Firmware: ModuleParams Class Reference
ModuleParams Class Reference
#include <px4_module_params.h>
Public Member Functions
ModuleParams (ModuleParams *parent)
void setParent (ModuleParams *parent)
Set the parent module.
virtual ~ModuleParams ()=default
ModuleParams (const ModuleParams &)=delete
ModuleParams & operator= (const ModuleParams &)=delete
ModuleParams (ModuleParams &&)=delete
ModuleParams & operator= (ModuleParams &&)=delete
Public Member Functions inherited from ListNode< ModuleParams * >
ListNode ()
ListNode (const ListNode &)=delete
ListNode (ListNode &&)=delete
virtual ~ListNode ()=default
ListNode & operator= (const ListNode &)=delete
ListNode & operator= (ListNode &&)=delete
void setSibling (ModuleParams *sibling)
const ModuleParams * getSibling ()
Protected Member Functions
virtual void updateParams ()
Call this whenever the module gets a parameter change notification.
virtual void updateParamsImpl ()
The implementation for this is generated with the macro DEFINE_PARAMETERS()
Private Attributes
List< ModuleParams * > _children
Additional Inherited Members
Protected Attributes inherited from ListNode< ModuleParams * >
ModuleParams * _sibling
Detailed Description
Definition at line 46 of file px4_module_params.h.
Constructor & Destructor Documentation
ModuleParams::ModuleParams (ModuleParams * parent) inline
Definition at line 50 of file px4_module_params.h.
References setParent().
Referenced by setParent().
virtual ModuleParams::~ModuleParams () virtual default
Referenced by setParent().
ModuleParams::ModuleParams (const ModuleParams &) delete
ModuleParams::ModuleParams (ModuleParams &&) delete
Member Function Documentation
ModuleParams& ModuleParams::operator= (const ModuleParams &) delete
Referenced by setParent().
ModuleParams& ModuleParams::operator= (ModuleParams &&) delete
void ModuleParams::setParent (ModuleParams * parent) inline
Set the parent module.
This is typically not required, only in cases where the parent cannot be set via constructor.
Definition at line 59 of file px4_module_params.h.
References _children, ModuleParams(), operator=(), and ~ModuleParams().
Referenced by ModuleParams().
virtual void ModuleParams::updateParams () inline protected virtual
Call this whenever the module gets a parameter change notification.
It will automatically call updateParams() for all children, which then call updateParamsImpl().
Reimplemented in PositionControl, and FlightTaskAutoMapper.
Definition at line 79 of file px4_module_params.h.
References _children, ListNode< T >::getSibling(), updateParams(), and updateParamsImpl().
Referenced by TAP_ESC::cycle(), Ekf2::Ekf2(), FlightTask::handleParameterUpdate(), MulticopterAttitudeControl::parameter_update_poll(), Sensors::parameter_update_poll(), MulticopterPositionControl::parameters_update(), FixedwingPositionControl::parameters_update(), Navigator::params_update(), Commander::run(), Ekf2::run(), BlockLocalPositionEstimator::update(), WindEstimatorModule::update_params(), FlightTaskAutoMapper::updateParams(), updateParams(), and PositionControl::updateParams().
virtual void ModuleParams::updateParamsImpl () inline protected virtual
The implementation for this is generated with the macro DEFINE_PARAMETERS()
Definition at line 94 of file px4_module_params.h.
Referenced by updateParams().
Member Data Documentation
List<ModuleParams *> ModuleParams::_children private
Definition at line 97 of file px4_module_params.h.
Referenced by setParent(), and updateParams().
The documentation for this class was generated from the following file:
src/platforms/px4_module_params.h