PX4 Firmware: src/drivers/uavcannode/resources.cpp File Reference
resources.cpp File Reference
#include <px4_platform_common/px4_config.h>
#include <nuttx/progmem.h>
#include <nuttx/compiler.h>
#include <stdlib.h>
#include <syslog.h>
#include <nuttx/arch.h>
#include <systemlib/cpuload.h>
#include "resources.hpp"
Functions
static const char * tstate_name (const tstate_t s)
void stack_check (void)
static void free_getprogmeminfo (struct mallinfo *mem)
void free_check (void)
Function Documentation
free_check()
void free_check (void)
Definition at line 167 of file resources.cpp.
References free_getprogmeminfo().
free_getprogmeminfo()
static void free_getprogmeminfo (struct mallinfo * mem) static
Definition at line 125 of file resources.cpp.
References status.
Referenced by free_check().
stack_check()
void stack_check (void)
Definition at line 83 of file resources.cpp.
References CONFIG_MAX_TASKS, system_load, and tstate_name().
tstate_name()
static const char* tstate_name (const tstate_t s) static
Definition at line 49 of file resources.cpp.
Referenced by stack_check().