PX4 Firmware: DemoOffboardAttitudeSetpoints Class Reference
DemoOffboardAttitudeSetpoints Class Reference
#include <demo_offboard_attitude_setpoints.h>
Public Member Functions
DemoOffboardAttitudeSetpoints ()
~DemoOffboardAttitudeSetpoints ()
int main ()
Protected Attributes
ros::NodeHandle _n
ros::Publisher _attitude_sp_pub
ros::Publisher _thrust_sp_pub
Detailed Description
Definition at line 47 of file demo_offboard_attitude_setpoints.h.
Constructor & Destructor Documentation
DemoOffboardAttitudeSetpoints::DemoOffboardAttitudeSetpoints ()
Definition at line 50 of file demo_offboard_attitude_setpoints.cpp.
DemoOffboardAttitudeSetpoints::~DemoOffboardAttitudeSetpoints () inline
Definition at line 52 of file demo_offboard_attitude_setpoints.h.
References main().
Member Function Documentation
int DemoOffboardAttitudeSetpoints::main ()
Definition at line 58 of file demo_offboard_attitude_setpoints.cpp.
References _attitude_sp_pub, _thrust_sp_pub, f(), px4::get_time_micros(), and px4::Rate::sleep().
Referenced by main(), and ~DemoOffboardAttitudeSetpoints().
Member Data Documentation
ros::Publisher DemoOffboardAttitudeSetpoints::_attitude_sp_pub protected
Definition at line 58 of file demo_offboard_attitude_setpoints.h.
Referenced by main().
ros::NodeHandle DemoOffboardAttitudeSetpoints::_n protected
Definition at line 57 of file demo_offboard_attitude_setpoints.h.
ros::Publisher DemoOffboardAttitudeSetpoints::_thrust_sp_pub protected
Definition at line 59 of file demo_offboard_attitude_setpoints.h.
Referenced by main().
The documentation for this class was generated from the following files:
src/platforms/ros/nodes/demo_offboard_attitude_setpoints/demo_offboard_attitude_setpoints.h
src/platforms/ros/nodes/demo_offboard_attitude_setpoints/demo_offboard_attitude_setpoints.cpp