PX4 Firmware: ListNode< T > Class Template Reference
ListNode< T > Class Template Reference
#include <List.hpp>
Public Member Functions
ListNode ()
virtual ~ListNode ()=default
ListNode (const ListNode &)=delete
ListNode & operator= (const ListNode &)=delete
ListNode (ListNode &&)=delete
ListNode & operator= (ListNode &&)=delete
void setSibling (T sibling)
const T getSibling ()
Protected Attributes
T _sibling
Detailed Description
template<class T>
class ListNode< T >
Definition at line 43 of file List.hpp.
Constructor & Destructor Documentation
template<class T> ListNode< T >::ListNode () inline
Definition at line 46 of file List.hpp.
template<class T> virtual ListNode< T >::~ListNode () virtual default
template<class T> ListNode< T >::ListNode (const ListNode< T > &) delete
template<class T> ListNode< T >::ListNode (ListNode< T > &&) delete
Member Function Documentation
template<class T> const T ListNode< T >::getSibling () inline
Definition at line 56 of file List.hpp.
Referenced by control::SuperBlock::setDt(), px4::NodeHandle::spinOnce(), control::SuperBlock::updateChildParams(), control::SuperBlock::updateChildPublications(), control::SuperBlock::updateChildSubscriptions(), control::Block::updateParams(), ModuleParams::updateParams(), control::Block::updatePublications(), control::Block::updateSubscriptions(), and px4::NodeHandle::~NodeHandle().
template<class T> ListNode& ListNode< T >::operator= (const ListNode< T > &) delete
template<class T> ListNode& ListNode< T >::operator= (ListNode< T > &&) delete
template<class T> void ListNode< T >::setSibling (T sibling) inline
Definition at line 55 of file List.hpp.
Member Data Documentation
template<class T> T ListNode< T >::_sibling protected
Definition at line 59 of file List.hpp.
The documentation for this class was generated from the following file:
src/include/containers/List.hpp