PX4 Firmware: uavcan_stm32::clock Namespace Reference
uavcan_stm32::clock Namespace Reference
Classes
struct UtcSyncParams
UTC clock synchronization parameters.
Functions
void init ()
Starts the clock.
uavcan::MonotonicTime getMonotonic ()
Returns current monotonic time since the moment when clock::init() was called.
void setUtc (uavcan::UtcTime time)
Sets the driver's notion of the system UTC.
uavcan::UtcTime getUtc ()
Returns UTC time if it has been set, otherwise returns zero time.
void adjustUtc (uavcan::UtcDuration adjustment)
Performs UTC phase and frequency adjustment.
float getUtcRateCorrectionPPM ()
Clock rate error.
uavcan::uint32_t getUtcJumpCount ()
Number of non-gradual adjustments performed so far.
bool isUtcLocked ()
Whether UTC is synchronized and locked.
UtcSyncParams getUtcSyncParams ()
UTC sync params get/set.
void setUtcSyncParams (const UtcSyncParams &params)
uavcan::uint64_t getUtcUSecFromCanInterrupt ()
Function Documentation
adjustUtc()
void uavcan_stm32::clock::adjustUtc (uavcan::UtcDuration adjustment)
Performs UTC phase and frequency adjustment.
The UTC time will be zero until first adjustment has been performed. This function is thread safe.
Referenced by uavcan_stm32::SystemClock::adjustUtc().
getMonotonic()
uavcan::MonotonicTime uavcan_stm32::clock::getMonotonic ()
Returns current monotonic time since the moment when clock::init() was called.
This function is thread safe.
Referenced by uavcan_stm32::SystemClock::getMonotonic(), uavcan_stm32::CanIface::receive(), and uavcan_stm32::CanDriver::select().
getUtc()
uavcan::UtcTime uavcan_stm32::clock::getUtc ()
Returns UTC time if it has been set, otherwise returns zero time.
This function is thread safe.
Referenced by uavcan_stm32::SystemClock::getUtc(), and UavcanNode::run().
getUtcJumpCount()
uavcan::uint32_t uavcan_stm32::clock::getUtcJumpCount ()
Number of non-gradual adjustments performed so far.
Ideally should be zero. This function is thread safe.
Referenced by UavcanNode::run(), and uavcan_stm32::clock::UtcSyncParams::UtcSyncParams().
getUtcRateCorrectionPPM()
float uavcan_stm32::clock::getUtcRateCorrectionPPM ()
Clock rate error.
Positive if the hardware timer is slower than reference time. This function is thread safe.
Referenced by UavcanNode::run(), and uavcan_stm32::clock::UtcSyncParams::UtcSyncParams().
getUtcSyncParams()
UtcSyncParams uavcan_stm32::clock::getUtcSyncParams ()
UTC sync params get/set.
Both functions are thread safe.
Referenced by uavcan_stm32::clock::UtcSyncParams::UtcSyncParams().
getUtcUSecFromCanInterrupt()
uavcan::uint64_t uavcan_stm32::clock::getUtcUSecFromCanInterrupt ()
init()
void uavcan_stm32::clock::init ()
Starts the clock.
Can be called multiple times, only the first call will be effective.
isUtcLocked()
bool uavcan_stm32::clock::isUtcLocked ()
Whether UTC is synchronized and locked.
This function is thread safe.
Referenced by UavcanNode::run(), and uavcan_stm32::clock::UtcSyncParams::UtcSyncParams().
setUtc()
void uavcan_stm32::clock::setUtc (uavcan::UtcTime time)
Sets the driver's notion of the system UTC.
It should be called at startup and any time the system clock is updated from an external source that is not the UAVCAN Timesync master. This function is thread safe.
setUtcSyncParams()
void uavcan_stm32::clock::setUtcSyncParams (const UtcSyncParams & params)
Referenced by uavcan_stm32::clock::UtcSyncParams::UtcSyncParams().