PX4 Firmware: MavlinkStreamHighresIMU Class Reference
MavlinkStreamHighresIMU Class Reference
Public Member Functions
const char * get_name () const override
uint16_t get_id () override
unsigned get_size () override
Get maximal total messages size on update.
Public Member Functions inherited from MavlinkStream
MavlinkStream (Mavlink *mavlink)
virtual ~MavlinkStream ()=default
MavlinkStream (const MavlinkStream &)=delete
MavlinkStream & operator= (const MavlinkStream &)=delete
MavlinkStream (MavlinkStream &&)=delete
MavlinkStream & operator= (MavlinkStream &&)=delete
void set_interval (const int interval)
Get the interval.
int get_interval ()
Get the interval.
int update (const hrt_abstime &t)
Update subscriptions and send message if necessary.
virtual bool const_rate ()
virtual unsigned get_size_avg ()
Get the average message size.
bool first_message_sent () const
void reset_last_sent ()
Reset the time of last sent to 0.
Public Member Functions inherited from ListNode< MavlinkStream *>
void setSibling (MavlinkStream * sibling)
const MavlinkStream * getSibling () const
Static Public Member Functions
static const char * get_name_static ()
static uint16_t get_id_static ()
static MavlinkStream * new_instance (Mavlink *mavlink)
Protected Member Functions
MavlinkStreamHighresIMU (Mavlink *mavlink)
bool send (const hrt_abstime t) override
Protected Member Functions inherited from MavlinkStream
virtual void update_data ()
Function to collect/update data for the streams at a high rate independant of actual stream rate.
Private Member Functions
MavlinkStreamHighresIMU (MavlinkStreamHighresIMU &)=delete
MavlinkStreamHighresIMU & operator= (const MavlinkStreamHighresIMU &)=delete
Private Attributes
MavlinkOrbSubscription * _sensor_sub
uint64_t _sensor_time
MavlinkOrbSubscription * _bias_sub
MavlinkOrbSubscription * _differential_pressure_sub
MavlinkOrbSubscription * _magnetometer_sub
MavlinkOrbSubscription * _air_data_sub
uint64_t _accel_timestamp
uint64_t _gyro_timestamp
uint64_t _mag_timestamp
uint64_t _baro_timestamp
uint64_t _dpres_timestamp
Additional Inherited Members
Protected Attributes inherited from MavlinkStream
Mavlink *const _mavlink
int _interval {1000000}
if set to negative value = unlimited rate
Protected Attributes inherited from ListNode< MavlinkStream *>
MavlinkStream * _list_node_sibling
Detailed Description
Definition at line 759 of file mavlink_messages.cpp.
Constructor & Destructor Documentation
MavlinkStreamHighresIMU() [1/2]
MavlinkStreamHighresIMU::MavlinkStreamHighresIMU (MavlinkStreamHighresIMU &) private delete
MavlinkStreamHighresIMU() [2/2]
MavlinkStreamHighresIMU::MavlinkStreamHighresIMU (Mavlink * mavlink) inline explicit protected
Definition at line 812 of file mavlink_messages.cpp.
Member Function Documentation
get_id()
uint16_t MavlinkStreamHighresIMU::get_id () inline override virtual
Implements MavlinkStream.
Definition at line 777 of file mavlink_messages.cpp.
References MavlinkStreamHeartbeat::get_id_static().
get_id_static()
static uint16_t MavlinkStreamHighresIMU::get_id_static () inline static
Definition at line 772 of file mavlink_messages.cpp.
get_name()
const char* MavlinkStreamHighresIMU::get_name () const inline override virtual
Implements MavlinkStream.
Definition at line 762 of file mavlink_messages.cpp.
References get_name_static().
get_name_static()
static const char* MavlinkStreamHighresIMU::get_name_static () inline static
Definition at line 767 of file mavlink_messages.cpp.
Referenced by get_name().
get_size()
unsigned MavlinkStreamHighresIMU::get_size () inline override virtual
Get maximal total messages size on update.
Implements MavlinkStream.
Definition at line 787 of file mavlink_messages.cpp.
new_instance()
static MavlinkStream* MavlinkStreamHighresIMU::new_instance (Mavlink * mavlink) inline static
Definition at line 782 of file mavlink_messages.cpp.
operator=()
MavlinkStreamHighresIMU& MavlinkStreamHighresIMU::operator= (const MavlinkStreamHighresIMU &) private delete
send()
bool MavlinkStreamHighresIMU::send (const hrt_abstime t) inline override protected virtual
Implements MavlinkStream.
Definition at line 826 of file mavlink_messages.cpp.
References MavlinkStream::_mavlink, sensor_bias_s::accel_bias, sensor_combined_s::accelerometer_m_s2, sensor_combined_s::accelerometer_timestamp_relative, vehicle_air_data_s::baro_alt_meter, vehicle_air_data_s::baro_pressure_pa, vehicle_air_data_s::baro_temp_celcius, differential_pressure_s::differential_pressure_raw_pa, Mavlink::get_channel(), sensor_bias_s::gyro_bias, sensor_combined_s::gyro_rad, sensor_bias_s::mag_bias, vehicle_magnetometer_s::magnetometer_ga, msg, differential_pressure_s::timestamp, vehicle_air_data_s::timestamp, vehicle_magnetometer_s::timestamp, sensor_combined_s::timestamp, and MavlinkOrbSubscription::update().
Member Data Documentation
_accel_timestamp
uint64_t MavlinkStreamHighresIMU::_accel_timestamp private
Definition at line 801 of file mavlink_messages.cpp.
_air_data_sub
MavlinkOrbSubscription* MavlinkStreamHighresIMU::_air_data_sub private
Definition at line 799 of file mavlink_messages.cpp.
_baro_timestamp
uint64_t MavlinkStreamHighresIMU::_baro_timestamp private
Definition at line 804 of file mavlink_messages.cpp.
_bias_sub
MavlinkOrbSubscription* MavlinkStreamHighresIMU::_bias_sub private
Definition at line 796 of file mavlink_messages.cpp.
_differential_pressure_sub
MavlinkOrbSubscription* MavlinkStreamHighresIMU::_differential_pressure_sub private
Definition at line 797 of file mavlink_messages.cpp.
_dpres_timestamp
uint64_t MavlinkStreamHighresIMU::_dpres_timestamp private
Definition at line 805 of file mavlink_messages.cpp.
_gyro_timestamp
uint64_t MavlinkStreamHighresIMU::_gyro_timestamp private
Definition at line 802 of file mavlink_messages.cpp.
_mag_timestamp
uint64_t MavlinkStreamHighresIMU::_mag_timestamp private
Definition at line 803 of file mavlink_messages.cpp.
_magnetometer_sub
MavlinkOrbSubscription* MavlinkStreamHighresIMU::_magnetometer_sub private
Definition at line 798 of file mavlink_messages.cpp.
_sensor_sub
MavlinkOrbSubscription* MavlinkStreamHighresIMU::_sensor_sub private
Definition at line 793 of file mavlink_messages.cpp.
_sensor_time
uint64_t MavlinkStreamHighresIMU::_sensor_time private
Definition at line 794 of file mavlink_messages.cpp.
The documentation for this class was generated from the following file:
src/modules/mavlink/mavlink_messages.cpp