PX4 Firmware: linux_sbus::RcInput Class Reference
linux_sbus::RcInput Class Reference
#include <linux_sbus.h>
Public Member Functions
RcInput ()
~RcInput ()
int start (char *device, int channels)
void stop ()
bool isRunning ()
Static Public Member Functions
static void cycle_trampoline (void *arg)
Trampoline for the work queue.
Private Member Functions
void _cycle ()
void _measure ()
int init ()
Private Attributes
bool _shouldExit
bool _isRunning
struct work_s _work
orb_advert_t _rcinput_pub
struct input_rc_s _data
uint8_t _sbusData [25]
int _channels
int _device_fd
int _channels_data [16]
serial port device to read SBUS;
uint8_t _buffer [25]
16 channels support;
char _device [30]
bool _failsafe
bool _rc_loss
Detailed Description
Definition at line 69 of file linux_sbus.h.
Constructor & Destructor Documentation
linux_sbus::RcInput::RcInput () inline
Definition at line 72 of file linux_sbus.h.
References _data, _rcinput_pub, and _sbusData.
Referenced by linux_sbus_main().
linux_sbus::RcInput::~RcInput () inline
Definition at line 83 of file linux_sbus.h.
References _device_fd, _isRunning, cycle_trampoline(), start(), and stop().
Member Function Documentation
void RcInput::_cycle () private
Definition at line 139 of file linux_sbus.cpp.
References _measure(), _shouldExit, cycle_trampoline(), and RCINPUT_MEASURE_INTERVAL_US.
Referenced by cycle_trampoline(), and isRunning().
void RcInput::_measure (void) private
error counter to count the lost frame
Notice: most sbus rx device support sbus1
parse sbus data to pwm
Definition at line 149 of file linux_sbus.cpp.
References _channels, _channels_data, _data, _device_fd, _rcinput_pub, _sbusData, input_rc_s::channel_count, f(), hrt_absolute_time(), input_rc_s::input_source, ORB_ID, orb_publish(), PX4_ERR, PX4_INFO, input_rc_s::rc_failsafe, input_rc_s::rc_lost, input_rc_s::rc_lost_frame_count, input_rc_s::rc_ppm_frame_length, input_rc_s::rc_total_frame_count, RCINPUT_MEASURE_INTERVAL_US, read(), input_rc_s::rssi, SBUS_SCALE_FACTOR, SBUS_SCALE_OFFSET, input_rc_s::timestamp, input_rc_s::timestamp_last_signal, linux_sbus::usage(), usleep(), and input_rc_s::values.
Referenced by _cycle(), and isRunning().
void RcInput::cycle_trampoline (void * arg) static
Trampoline for the work queue.
Definition at line 133 of file linux_sbus.cpp.
References _cycle().
Referenced by _cycle(), start(), and ~RcInput().
int RcInput::init () private
initialize the data of each channel
open the serial port
Setting serial port,8E2, non-blocking.100Kbps
use BOTHER to specify speed directly in c_[io]speed member
Definition at line 38 of file linux_sbus.cpp.
References _data, _device, _device_fd, _rcinput_pub, orb_advertise(), ORB_ID, PX4_ERR, PX4_WARN, and input_rc_s::values.
Referenced by start().
bool linux_sbus::RcInput::isRunning () inline
Definition at line 96 of file linux_sbus.h.
References _cycle(), _isRunning, and _measure().
Referenced by linux_sbus_main().
int RcInput::start (char * device, int channels)
Returns
0 on success, -errno on failure
Definition at line 103 of file linux_sbus.cpp.
References _channels, _device, _isRunning, cycle_trampoline(), init(), PX4_INFO, and PX4_WARN.
Referenced by linux_sbus_main(), and ~RcInput().
void RcInput::stop ()
Definition at line 127 of file linux_sbus.cpp.
References _device_fd, and _shouldExit.
Referenced by linux_sbus_main(), and ~RcInput().
Member Data Documentation
uint8_t linux_sbus::RcInput::_buffer[25] private
16 channels support;
Definition at line 113 of file linux_sbus.h.
int linux_sbus::RcInput::_channels private
Definition at line 110 of file linux_sbus.h.
Referenced by _measure(), and start().
int linux_sbus::RcInput::_channels_data[16] private
serial port device to read SBUS;
Definition at line 112 of file linux_sbus.h.
Referenced by _measure().
struct input_rc_s linux_sbus::RcInput::_data private
Definition at line 108 of file linux_sbus.h.
Referenced by _measure(), init(), and RcInput().
char linux_sbus::RcInput::_device[30] private
Definition at line 114 of file linux_sbus.h.
Referenced by init(), and start().
int linux_sbus::RcInput::_device_fd private
Definition at line 111 of file linux_sbus.h.
Referenced by _measure(), init(), stop(), and ~RcInput().
bool linux_sbus::RcInput::_failsafe private
Definition at line 115 of file linux_sbus.h.
bool linux_sbus::RcInput::_isRunning private
Definition at line 105 of file linux_sbus.h.
Referenced by isRunning(), start(), and ~RcInput().
bool linux_sbus::RcInput::_rc_loss private
Definition at line 116 of file linux_sbus.h.
orb_advert_t linux_sbus::RcInput::_rcinput_pub private
Definition at line 107 of file linux_sbus.h.
Referenced by _measure(), init(), and RcInput().
uint8_t linux_sbus::RcInput::_sbusData[25] private
Definition at line 109 of file linux_sbus.h.
Referenced by _measure(), and RcInput().
bool linux_sbus::RcInput::_shouldExit private
Definition at line 104 of file linux_sbus.h.
Referenced by _cycle(), and stop().
struct work_s linux_sbus::RcInput::_work private
Definition at line 106 of file linux_sbus.h.
The documentation for this class was generated from the following files:
src/drivers/linux_sbus/linux_sbus.h
src/drivers/linux_sbus/linux_sbus.cpp