PX4 Firmware: adis16448 Namespace Reference
adis16448 Namespace Reference
Local functions in support of the shell command.
Functions
void start (enum Rotation rotation)
Start the driver.
void test ()
Perform some basic functional tests on the driver; make sure we can collect data from the sensor in polled and automatic modes.
void reset ()
Reset the driver.
void info ()
Print a little info about the driver.
void info_cal ()
Print a sensor calibration info.
void usage ()
Prints info about the driver argument usage.
Variables
ADIS16448 * g_dev
Detailed Description
Local functions in support of the shell command.
Function Documentation
void adis16448::info ()
Print a little info about the driver.
Print a little info about the driver.
Definition at line 1872 of file adis16448.cpp.
References errx, and ADIS16448::print_info().
Referenced by adis16448_main().
void adis16448::info_cal ()
Print a sensor calibration info.
Definition at line 1888 of file adis16448.cpp.
References errx, and ADIS16448::print_calibration_data().
Referenced by adis16448_main().
void adis16448::reset ()
Reset the driver.
Reset the driver.
Definition at line 1847 of file adis16448.cpp.
References ADIS16448_DEVICE_PATH_ACCEL, device::CDev::close(), err, fd, ADIS16448_mag::ioctl(), device::CDev::open(), SENSOR_POLLRATE_DEFAULT, SENSORIOCRESET, and SENSORIOCSPOLLRATE.
Referenced by adis16448_main(), and test().
void adis16448::start (enum Rotation rotation)
Start the driver.
Definition at line 1719 of file adis16448.cpp.
References ADIS16448_mag::ADIS16448, ADIS16448_DEVICE_PATH_ACCEL, ADIS16448_DEVICE_PATH_GYRO, ADIS16448_DEVICE_PATH_MAG, device::CDev::close(), errx, fd, g_dev, ADIS16448_mag::init(), ADIS16448_mag::ioctl(), OK, device::CDev::open(), PX4_ERR, PX4_SPI_BUS_EXT, PX4_SPIDEV_EXT_MPU, SENSOR_POLLRATE_DEFAULT, and SENSORIOCSPOLLRATE.
Referenced by adis16448_main().
void adis16448::test ()
Perform some basic functional tests on the driver; make sure we can collect data from the sensor in polled and automatic modes.
Definition at line 1775 of file adis16448.cpp.
References accel_report, ADIS16448_DEVICE_PATH_ACCEL, ADIS16448_DEVICE_PATH_GYRO, ADIS16448_DEVICE_PATH_MAG, device::CDev::close(), err, errx, fd, gyro_report, mag_report, device::CDev::open(), ADIS16448_mag::read(), reset(), and warnx.
Referenced by adis16448_main().
void adis16448::usage (void)
Prints info about the driver argument usage.
Prints info about the driver argument usage.
Definition at line 1900 of file adis16448.cpp.
References warnx.
Referenced by adis16448_main().
Variable Documentation
ADIS16448* adis16448::g_dev
Definition at line 1707 of file adis16448.cpp.
Referenced by start().