PX4 Firmware: events::SendEvent Class Reference
events::SendEvent Class Reference
#include <send_event.h>
Public Member Functions
SendEvent ()
~SendEvent ()
Public Member Functions inherited from ModuleParams
ModuleParams (ModuleParams *parent)
void setParent (ModuleParams *parent)
Set the parent module.
virtual ~ModuleParams ()=default
ModuleParams (const ModuleParams &)=delete
ModuleParams & operator= (const ModuleParams &)=delete
ModuleParams (ModuleParams &&)=delete
ModuleParams & operator= (ModuleParams &&)=delete
Public Member Functions inherited from ListNode< ModuleParams * >
ListNode ()
ListNode (const ListNode &)=delete
ListNode (ListNode &&)=delete
virtual ~ListNode ()=default
ListNode & operator= (const ListNode &)=delete
ListNode & operator= (ListNode &&)=delete
void setSibling (ModuleParams *sibling)
const ModuleParams * getSibling ()
Static Public Member Functions
static int task_spawn (int argc, char *argv[])
Initialize class in the same context as the work queue.
static int custom_command (int argc, char *argv[])
static int print_usage (const char *reason=nullptr)
Private Member Functions
int start ()
Start background listening for commands.
void cycle ()
call process_commands() and schedule the next cycle.
void process_commands ()
check for new commands and process them.
void answer_command (const vehicle_command_s &cmd, unsigned result)
return an ACK to a vehicle_command
Static Private Member Functions
static void initialize_trampoline (void *arg)
Trampoline for initialisation.
static void cycle_trampoline (void *arg)
Trampoline for the work queue.
Private Attributes
SubscriberHandler _subscriber_handler
status::StatusDisplay * _status_display = nullptr
rc_loss::RC_Loss_Alarm * _rc_loss_alarm = nullptr
orb_advert_t _command_ack_pub = nullptr
Static Private Attributes
static struct work_s _work
Additional Inherited Members
Protected Member Functions inherited from ModuleParams
virtual void updateParams ()
Call this whenever the module gets a parameter change notification.
virtual void updateParamsImpl ()
The implementation for this is generated with the macro DEFINE_PARAMETERS()
Protected Attributes inherited from ListNode< ModuleParams * >
ModuleParams * _sibling
Detailed Description
Definition at line 44 of file send_event.cpp.
Constructor & Destructor Documentation
events::SendEvent::SendEvent ()
Definition at line 69 of file send_event.cpp.
References _rc_loss_alarm, _status_display, and _subscriber_handler.
Referenced by initialize_trampoline().
events::SendEvent::~SendEvent ()
Definition at line 80 of file send_event.cpp.
References _rc_loss_alarm, and _status_display.
Member Function Documentation
void events::SendEvent::answer_command (const vehicle_command_s & cmd, unsigned result) private
return an ACK to a vehicle_command
Definition at line 194 of file send_event.cpp.
References _command_ack_pub, vehicle_command_ack_s::command, vehicle_command_s::command, hrt_absolute_time(), orb_advertise_queue(), ORB_ID, orb_publish(), vehicle_command_ack_s::result, vehicle_command_s::source_component, vehicle_command_s::source_system, vehicle_command_ack_s::target_component, vehicle_command_ack_s::target_system, and vehicle_command_ack_s::timestamp.
Referenced by process_commands().
int events::SendEvent::custom_command (int argc, char * argv[]) static
See also
ModuleBase
Definition at line 246 of file send_event.cpp.
References vehicle_command_s::command, hrt_absolute_time(), is_running(), orb_advertise_queue(), ORB_ID, vehicle_command_s::param1, vehicle_command_s::param2, vehicle_command_s::param3, vehicle_command_s::param4, vehicle_command_s::param5, vehicle_command_s::param6, vehicle_command_s::param7, print_usage(), PX4_ERR, px4_getopt(), and vehicle_command_s::timestamp.
void events::SendEvent::cycle () private
call process_commands() and schedule the next cycle.
Definition at line 127 of file send_event.cpp.
References _rc_loss_alarm, _status_display, _subscriber_handler, events::SubscriberHandler::check_for_updates(), cycle_trampoline(), events::rc_loss::RC_Loss_Alarm::process(), events::status::StatusDisplay::process(), process_commands(), and events::SubscriberHandler::unsubscribe().
Referenced by cycle_trampoline(), and start().
void events::SendEvent::cycle_trampoline (void * arg) static private
Trampoline for the work queue.
Definition at line 120 of file send_event.cpp.
References cycle().
Referenced by cycle().
void events::SendEvent::initialize_trampoline (void * arg) static private
Trampoline for initialisation.
Definition at line 106 of file send_event.cpp.
References PX4_ERR, SendEvent(), and start().
Referenced by task_spawn().
int events::SendEvent::print_usage (const char * reason = nullptr) static
See also
ModuleBase
Definition at line 213 of file send_event.cpp.
References PRINT_MODULE_DESCRIPTION(), PRINT_MODULE_USAGE_COMMAND_DESCR(), PRINT_MODULE_USAGE_DEFAULT_COMMANDS, PRINT_MODULE_USAGE_NAME(), and PRINT_MODULE_USAGE_PARAM_FLAG().
Referenced by custom_command().
void events::SendEvent::process_commands () private
check for new commands and process them.
Definition at line 151 of file send_event.cpp.
References _subscriber_handler, accel(), answer_command(), baro(), vehicle_command_s::command, events::SubscriberHandler::get_vehicle_command_sub(), gyro(), orb_copy(), ORB_ID, vehicle_command_s::param1, vehicle_command_s::param5, vehicle_command_s::param7, run_temperature_calibration(), and events::SubscriberHandler::vehicle_command_updated().
Referenced by cycle().
int events::SendEvent::start () private
Start background listening for commands.
Returns
0 if successful, <0 on error.
Definition at line 91 of file send_event.cpp.
References _subscriber_handler, cycle(), is_running(), and events::SubscriberHandler::subscribe().
Referenced by initialize_trampoline().
int events::SendEvent::task_spawn (int argc, char * argv[]) static
Initialize class in the same context as the work queue.
And start the background listener.
Returns
0 if successful, <0 on error
Definition at line 50 of file send_event.cpp.
References initialize_trampoline().
Member Data Documentation
orb_advert_t events::SendEvent::_command_ack_pub = nullptr private
Definition at line 94 of file send_event.h.
Referenced by answer_command().
rc_loss::RC_Loss_Alarm* events::SendEvent::_rc_loss_alarm = nullptr private
Definition at line 93 of file send_event.h.
Referenced by cycle(), SendEvent(), and ~SendEvent().
status::StatusDisplay* events::SendEvent::_status_display = nullptr private
Definition at line 92 of file send_event.h.
Referenced by cycle(), SendEvent(), and ~SendEvent().
SubscriberHandler events::SendEvent::_subscriber_handler private
Definition at line 91 of file send_event.h.
Referenced by cycle(), process_commands(), SendEvent(), and start().
struct work_s events::SendEvent::_work static private
Definition at line 90 of file send_event.h.
The documentation for this class was generated from the following files:
src/modules/events/send_event.cpp
src/modules/events/send_event.h