PX4 Firmware: MavlinkStreamManualControl Class Reference
MavlinkStreamManualControl Class Reference
Public Member Functions
const char * get_name () const override
uint16_t get_id () override
unsigned get_size () override
Get maximal total messages size on update.
Public Member Functions inherited from MavlinkStream
MavlinkStream (Mavlink *mavlink)
virtual ~MavlinkStream ()=default
MavlinkStream (const MavlinkStream &)=delete
MavlinkStream & operator= (const MavlinkStream &)=delete
MavlinkStream (MavlinkStream &&)=delete
MavlinkStream & operator= (MavlinkStream &&)=delete
void set_interval (const int interval)
Get the interval.
int get_interval ()
Get the interval.
int update (const hrt_abstime &t)
Update subscriptions and send message if necessary.
virtual bool const_rate ()
virtual unsigned get_size_avg ()
Get the average message size.
bool first_message_sent () const
void reset_last_sent ()
Reset the time of last sent to 0.
Public Member Functions inherited from ListNode< MavlinkStream *>
void setSibling (MavlinkStream * sibling)
const MavlinkStream * getSibling () const
Static Public Member Functions
static const char * get_name_static ()
static uint16_t get_id_static ()
static MavlinkStream * new_instance (Mavlink *mavlink)
Protected Member Functions
MavlinkStreamManualControl (Mavlink *mavlink)
bool send (const hrt_abstime t) override
Protected Member Functions inherited from MavlinkStream
virtual void update_data ()
Function to collect/update data for the streams at a high rate independant of actual stream rate.
Private Member Functions
MavlinkStreamManualControl (MavlinkStreamManualControl &)=delete
MavlinkStreamManualControl & operator= (const MavlinkStreamManualControl &)=delete
Private Attributes
MavlinkOrbSubscription * _manual_sub
uint64_t _manual_time
Additional Inherited Members
Protected Attributes inherited from MavlinkStream
Mavlink *const _mavlink
int _interval {1000000}
if set to negative value = unlimited rate
Protected Attributes inherited from ListNode< MavlinkStream *>
MavlinkStream * _list_node_sibling
Detailed Description
Definition at line 3581 of file mavlink_messages.cpp.
Constructor & Destructor Documentation
MavlinkStreamManualControl() [1/2]
MavlinkStreamManualControl::MavlinkStreamManualControl (MavlinkStreamManualControl &) private delete
MavlinkStreamManualControl() [2/2]
MavlinkStreamManualControl::MavlinkStreamManualControl (Mavlink * mavlink) inline explicit protected
Definition at line 3623 of file mavlink_messages.cpp.
Member Function Documentation
get_id()
uint16_t MavlinkStreamManualControl::get_id () inline override virtual
Implements MavlinkStream.
Definition at line 3599 of file mavlink_messages.cpp.
References MavlinkStreamHeartbeat::get_id_static().
get_id_static()
static uint16_t MavlinkStreamManualControl::get_id_static () inline static
Definition at line 3594 of file mavlink_messages.cpp.
get_name()
const char* MavlinkStreamManualControl::get_name () const inline override virtual
Implements MavlinkStream.
Definition at line 3584 of file mavlink_messages.cpp.
References get_name_static().
get_name_static()
static const char* MavlinkStreamManualControl::get_name_static () inline static
Definition at line 3589 of file mavlink_messages.cpp.
Referenced by get_name().
get_size()
unsigned MavlinkStreamManualControl::get_size () inline override virtual
Get maximal total messages size on update.
Implements MavlinkStream.
Definition at line 3609 of file mavlink_messages.cpp.
new_instance()
static MavlinkStream* MavlinkStreamManualControl::new_instance (Mavlink * mavlink) inline static
Definition at line 3604 of file mavlink_messages.cpp.
operator=()
MavlinkStreamManualControl& MavlinkStreamManualControl::operator= (const MavlinkStreamManualControl &) private delete
send()
bool MavlinkStreamManualControl::send (const hrt_abstime t) inline override protected virtual
Implements MavlinkStream.
Definition at line 3628 of file mavlink_messages.cpp.
References MavlinkStream::_mavlink, manual_control_setpoint_s::acro_switch, Mavlink::get_channel(), manual_control_setpoint_s::loiter_switch, mavlink_system, manual_control_setpoint_s::mode_switch, msg, manual_control_setpoint_s::offboard_switch, manual_control_setpoint_s::posctl_switch, manual_control_setpoint_s::r, manual_control_setpoint_s::return_switch, MavlinkOrbSubscription::update(), manual_control_setpoint_s::x, manual_control_setpoint_s::y, and manual_control_setpoint_s::z.
Member Data Documentation
_manual_sub
MavlinkOrbSubscription* MavlinkStreamManualControl::_manual_sub private
Definition at line 3615 of file mavlink_messages.cpp.
_manual_time
uint64_t MavlinkStreamManualControl::_manual_time private
Definition at line 3616 of file mavlink_messages.cpp.
The documentation for this class was generated from the following file:
src/modules/mavlink/mavlink_messages.cpp