PX4 Firmware: src/drivers/md25/md25.hpp File Reference
md25.hpp File Reference
#include <poll.h>
#include <stdio.h>
#include <uORB/Subscription.hpp>
#include <uORB/topics/actuator_controls.h>
#include <drivers/device/i2c.h>
Classes
class MD25
This is a driver for the MD25 motor controller utilizing the I2C interface.
Functions
int md25Test (const char *deviceName, uint8_t bus, uint8_t address)
int md25Sine (const char *deviceName, uint8_t bus, uint8_t address, float amplitude, float frequency)
Function Documentation
int md25Sine (const char * deviceName, uint8_t bus, uint8_t address, float amplitude, float frequency)
Definition at line 566 of file md25.cpp.
References dt, MD25::getRevolutions1(), hrt_absolute_time(), ORB_ID, MD25::readData(), MD25::resetEncoders(), MD25::setMotor1Speed(), MD25::setSpeedRegulation(), MD25::setTimeout(), MD25::status(), uORB::Publication< T >::update(), and usleep().
Referenced by md25_main().
int md25Test (const char * deviceName, uint8_t bus, uint8_t address)
Definition at line 459 of file md25.cpp.
References dt, f(), MD25::getRevolutions1(), MD25::getRevolutions2(), MD25::readData(), MD25::resetEncoders(), MD25::setMotor1Speed(), MD25::setMotor2Speed(), MD25::setSpeedRegulation(), MD25::setTimeout(), MD25::status(), and usleep().
Referenced by md25_main().