PX4 Firmware: src/drivers/boards/px4fmu-v5/spi.c File Reference
spi.c File Reference
#include <px4_config.h>
#include <px4_log.h>
#include <stdint.h>
#include <stdbool.h>
#include <debug.h>
#include <unistd.h>
#include <nuttx/spi/spi.h>
#include <arch/board/board.h>
#include <systemlib/px4_macros.h>
#include <up_arch.h>
#include <chip.h>
#include <stm32_gpio.h>
#include "board_config.h"
#include <systemlib/err.h>
Functions
__EXPORT void stm32_spiinitialize (void)
__EXPORT int stm32_spi_bus_initialize (void)
__EXPORT void stm32_spi1select (FAR struct spi_dev_s *dev, uint32_t devid, bool selected)
__EXPORT uint8_t stm32_spi1status (FAR struct spi_dev_s *dev, uint32_t devid)
__EXPORT void stm32_spi2select (FAR struct spi_dev_s *dev, uint32_t devid, bool selected)
__EXPORT uint8_t stm32_spi2status (FAR struct spi_dev_s *dev, uint32_t devid)
__EXPORT void stm32_spi4select (FAR struct spi_dev_s *dev, uint32_t devid, bool selected)
__EXPORT uint8_t stm32_spi4status (FAR struct spi_dev_s *dev, uint32_t devid)
__EXPORT void stm32_spi6select (FAR struct spi_dev_s *dev, uint32_t devid, bool selected)
__EXPORT uint8_t stm32_spi6status (FAR struct spi_dev_s *dev, uint32_t devid)
__EXPORT void board_spi_reset (int ms)
Variables
static const uint32_t spi1selects_gpio [] = PX4_SENSOR_BUS_CS_GPIO
static const uint32_t spi2selects_gpio [] = PX4_MEMORY_BUS_CS_GPIO
static const uint32_t spi4selects_gpio [] = PX4_BARO_BUS_CS_GPIO
static const uint32_t spi6selects_gpio [] = PX4_EXTERNAL2_BUS_CS_GPIO
static struct spi_dev_s * spi_sensors
static struct spi_dev_s * spi_memory
static struct spi_dev_s * spi_baro
static struct spi_dev_s * spi_ext
Function Documentation
__EXPORT void board_spi_reset (int ms)
disable SPI bus 1 DRDY */
Definition at line 452 of file spi.c.
References _PIN_OFF, arraySize, GPIO_DRDY_OFF_SPI1_DRDY1_ICM20689, GPIO_DRDY_OFF_SPI1_DRDY2_BMI055_GYRO, GPIO_DRDY_OFF_SPI1_DRDY3_BMI055_ACC, GPIO_DRDY_OFF_SPI1_DRDY4_ICM20602, GPIO_DRDY_OFF_SPI1_DRDY5_BMI055_GYRO, GPIO_DRDY_OFF_SPI1_DRDY6_BMI055_ACC, GPIO_SPI1_DRDY1_ICM20689, GPIO_SPI1_DRDY2_BMI055_GYRO, GPIO_SPI1_DRDY3_BMI055_ACC, GPIO_SPI1_DRDY4_ICM20602, GPIO_SPI1_DRDY5_BMI055_GYRO, GPIO_SPI1_DRDY6_BMI055_ACC, GPIO_SPI1_MISO_OFF, GPIO_SPI1_MOSI_OFF, GPIO_SPI1_SCK_OFF, GPIO_VDD_3V3_SENSORS_EN, spi1selects_gpio, usleep(), and warnx.
__EXPORT void stm32_spi1select (FAR struct spi_dev_s * dev, uint32_t devid, bool selected)
Definition at line 241 of file spi.c.
References arraySize, PX4_SPI_BUS_ID, PX4_SPI_BUS_SENSORS, PX4_SPI_DEV_ID, and spi1selects_gpio.
__EXPORT uint8_t stm32_spi1status (FAR struct spi_dev_s * dev, uint32_t devid)
Definition at line 263 of file spi.c.
__EXPORT void stm32_spi2select (FAR struct spi_dev_s * dev, uint32_t devid, bool selected)
Definition at line 277 of file spi.c.
References arraySize, PX4_SPI_BUS_ID, PX4_SPI_BUS_MEMORY, PX4_SPI_DEV_ID, PX4_SPIDEV_MEMORY, and spi2selects_gpio.
__EXPORT uint8_t stm32_spi2status (FAR struct spi_dev_s * dev, uint32_t devid)
Definition at line 304 of file spi.c.
References arraySize, PX4_SPI_BUS_ID, PX4_SPI_DEV_ID, stm32_spi3select(), and stm32_spi3status().
__EXPORT void stm32_spi4select (FAR struct spi_dev_s * dev, uint32_t devid, bool selected)
Definition at line 353 of file spi.c.
References arraySize, PX4_SPI_BUS_BARO, PX4_SPI_BUS_ID, PX4_SPI_DEV_ID, and spi4selects_gpio.
__EXPORT uint8_t stm32_spi4status (FAR struct spi_dev_s * dev, uint32_t devid)
Definition at line 371 of file spi.c.
References arraySize, PX4_SPI_BUS_EXTERNAL1, PX4_SPI_BUS_ID, PX4_SPI_DEV_ID, spi5selects_gpio, stm32_spi5select(), and stm32_spi5status().
__EXPORT void stm32_spi6select (FAR struct spi_dev_s * dev, uint32_t devid, bool selected)
Definition at line 419 of file spi.c.
References arraySize, PX4_SPI_BUS_EXTERNAL2, PX4_SPI_BUS_ID, PX4_SPI_DEV_ID, and spi6selects_gpio.
Referenced by stm32_spi1status().
__EXPORT uint8_t stm32_spi6status (FAR struct spi_dev_s * dev, uint32_t devid)
Definition at line 439 of file spi.c.
Referenced by stm32_spi1status().
__EXPORT int stm32_spi_bus_initialize (void)
Definition at line 132 of file spi.c.
References OK, PX4_BARO_BUS_FIRST_CS, PX4_BARO_BUS_LAST_CS, PX4_ERR, PX4_EXTERNAL1_BUS_FIRST_CS, PX4_EXTERNAL1_BUS_LAST_CS, PX4_EXTERNAL2_BUS_FIRST_CS, PX4_EXTERNAL2_BUS_LAST_CS, PX4_MEMORY_BUS_FIRST_CS, PX4_MEMORY_BUS_LAST_CS, PX4_SENSORS_BUS_FIRST_CS, PX4_SENSORS_BUS_LAST_CS, PX4_SPI_BUS_BARO, PX4_SPI_BUS_EXTERNAL1, PX4_SPI_BUS_EXTERNAL2, PX4_SPI_BUS_MEMORY, PX4_SPI_BUS_SENSORS, spi_baro, spi_ext, spi_memory, and spi_sensors.
__EXPORT void stm32_spiinitialize (void)
Definition at line 96 of file spi.c.
References arraySize, board_gpio_init(), spi1selects_gpio, spi2selects_gpio, spi4selects_gpio, spi5selects_gpio, and spi6selects_gpio.
Variable Documentation
const uint32_t spi1selects_gpio[] = PX4_SENSOR_BUS_CS_GPIO static
Definition at line 71 of file spi.c.
Referenced by board_spi_reset(), stm32_spi1select(), and stm32_spiinitialize().
const uint32_t spi2selects_gpio[] = PX4_MEMORY_BUS_CS_GPIO static
Definition at line 72 of file spi.c.
Referenced by stm32_spi2select(), and stm32_spiinitialize().
const uint32_t spi4selects_gpio[] = PX4_BARO_BUS_CS_GPIO static
Definition at line 77 of file spi.c.
Referenced by stm32_spi4select(), and stm32_spiinitialize().
const uint32_t spi6selects_gpio[] = PX4_EXTERNAL2_BUS_CS_GPIO static
Definition at line 81 of file spi.c.
Referenced by stm32_spi6select(), and stm32_spiinitialize().
struct spi_dev_s* spi_baro static
Definition at line 129 of file spi.c.
Referenced by stm32_spi_bus_initialize().
struct spi_dev_s* spi_ext static
Definition at line 130 of file spi.c.
Referenced by stm32_spi_bus_initialize().
struct spi_dev_s* spi_memory static
Definition at line 128 of file spi.c.
Referenced by stm32_spi_bus_initialize().
struct spi_dev_s* spi_sensors static
Definition at line 127 of file spi.c.
Referenced by stm32_spi_bus_initialize().