PX4 Firmware: control::BlockRandUniform Class Reference
control::BlockRandUniform Class Reference
A uniform random number generator.
#include <BlockRandUniform.hpp>
Public Member Functions
BlockRandUniform (SuperBlock *parent, const char *name)
virtual ~BlockRandUniform ()=default
float update ()
float getMin ()
float getMax ()
Public Member Functions inherited from control::Block
Block (SuperBlock *parent, const char *name)
virtual ~Block ()=default
Block (const Block &)=delete
Block & operator= (const Block &)=delete
Block (Block &&)=delete
Block & operator= (Block &&)=delete
void getName (char *name, size_t n)
virtual void updateParams ()
virtual void setDt (float dt)
float getDt ()
Public Member Functions inherited from ListNode< Block *>
void setSibling (Block * sibling)
const Block * getSibling () const
Private Attributes
control::BlockParamFloat _min
control::BlockParamFloat _max
Additional Inherited Members
Protected Member Functions inherited from control::Block
virtual void updateParamsSubclass ()
SuperBlock * getParent ()
List< BlockParamBase * > & getParams ()
Protected Attributes inherited from control::Block
const char * _name
SuperBlock * _parent
float _dt {0.0f}
List< BlockParamBase * > _params
Protected Attributes inherited from ListNode< Block *>
Block * _list_node_sibling
Detailed Description
A uniform random number generator.
Definition at line 61 of file BlockRandUniform.hpp.
Constructor & Destructor Documentation
BlockRandUniform()
control::BlockRandUniform::BlockRandUniform (SuperBlock * parent, const char * name) inline
Definition at line 65 of file BlockRandUniform.hpp.
~BlockRandUniform()
virtual control::BlockRandUniform::~BlockRandUniform () virtual default
Member Function Documentation
getMax()
float control::BlockRandUniform::getMax () inline
Definition at line 85 of file BlockRandUniform.hpp.
Referenced by control::blockRandUniformTest(), and blockRandUniformTest().
getMin()
float control::BlockRandUniform::getMin () inline
Definition at line 84 of file BlockRandUniform.hpp.
Referenced by control::blockRandUniformTest(), and blockRandUniformTest().
update()
float control::BlockRandUniform::update () inline
Definition at line 76 of file BlockRandUniform.hpp.
Referenced by control::blockRandUniformTest(), and blockRandUniformTest().
Member Data Documentation
_max
control::BlockParamFloat control::BlockRandUniform::_max private
Definition at line 89 of file BlockRandUniform.hpp.
_min
control::BlockParamFloat control::BlockRandUniform::_min private
Definition at line 88 of file BlockRandUniform.hpp.
The documentation for this class was generated from the following file:
src/lib/controllib/BlockRandUniform.hpp