PX4 Firmware: launchdetection::CatapultLaunchMethod Class Reference
launchdetection::CatapultLaunchMethod Class Reference
#include <CatapultLaunchMethod.h>
Public Member Functions
CatapultLaunchMethod (ModuleParams *parent)
~CatapultLaunchMethod () override=default
void update (float accel_x) override
LaunchDetectionResult getLaunchDetected () const override
void reset () override
float getPitchMax (float pitchMaxDefault) override
Public Member Functions inherited from launchdetection::LaunchMethod
virtual ~LaunchMethod ()=default
Public Member Functions inherited from ModuleParams
ModuleParams (ModuleParams *parent)
void setParent (ModuleParams *parent)
Set the parent module.
virtual ~ModuleParams ()=default
ModuleParams (const ModuleParams &)=delete
ModuleParams & operator= (const ModuleParams &)=delete
ModuleParams (ModuleParams &&)=delete
ModuleParams & operator= (ModuleParams &&)=delete
Public Member Functions inherited from ListNode< ModuleParams * >
ListNode ()
ListNode (const ListNode &)=delete
ListNode (ListNode &&)=delete
virtual ~ListNode ()=default
ListNode & operator= (const ListNode &)=delete
ListNode & operator= (ListNode &&)=delete
void setSibling (ModuleParams *sibling)
const ModuleParams * getSibling ()
Private Attributes
hrt_abstime _last_timestamp {0}
float _integrator {0.0f}
float _motorDelayCounter {0.0f}
LaunchDetectionResult state {LAUNCHDETECTION_RES_NONE}
Additional Inherited Members
Protected Member Functions inherited from ModuleParams
virtual void updateParams ()
Call this whenever the module gets a parameter change notification.
virtual void updateParamsImpl ()
The implementation for this is generated with the macro DEFINE_PARAMETERS()
Protected Attributes inherited from ListNode< ModuleParams * >
ModuleParams * _sibling
Detailed Description
Definition at line 52 of file CatapultLaunchMethod.h.
Constructor & Destructor Documentation
launchdetection::CatapultLaunchMethod::CatapultLaunchMethod (ModuleParams * parent)
Definition at line 49 of file CatapultLaunchMethod.cpp.
References _last_timestamp, and hrt_absolute_time().
launchdetection::CatapultLaunchMethod::~CatapultLaunchMethod () override default
Member Function Documentation
LaunchDetectionResult launchdetection::CatapultLaunchMethod::getLaunchDetected () const override virtual
Implements launchdetection::LaunchMethod.
Definition at line 104 of file CatapultLaunchMethod.cpp.
References state.
float launchdetection::CatapultLaunchMethod::getPitchMax (float pitchMaxDefault) override virtual
Implements launchdetection::LaunchMethod.
Definition at line 116 of file CatapultLaunchMethod.cpp.
References launchdetection::LAUNCHDETECTION_RES_DETECTED_ENABLEMOTORS, and state.
void launchdetection::CatapultLaunchMethod::reset (void) override virtual
Implements launchdetection::LaunchMethod.
Definition at line 109 of file CatapultLaunchMethod.cpp.
References _integrator, _motorDelayCounter, launchdetection::LAUNCHDETECTION_RES_NONE, and state.
Referenced by update().
void launchdetection::CatapultLaunchMethod::update (float accel_x) override virtual
Implements launchdetection::LaunchMethod.
Definition at line 55 of file CatapultLaunchMethod.cpp.
References _integrator, _last_timestamp, _motorDelayCounter, dt, f(), hrt_absolute_time(), hrt_elapsed_time(), launchdetection::LAUNCHDETECTION_RES_DETECTED_ENABLECONTROL, launchdetection::LAUNCHDETECTION_RES_DETECTED_ENABLEMOTORS, launchdetection::LAUNCHDETECTION_RES_NONE, PX4_INFO, PX4_WARN, reset(), and state.
Member Data Documentation
float launchdetection::CatapultLaunchMethod::_integrator {0.0f} private
Definition at line 65 of file CatapultLaunchMethod.h.
Referenced by reset(), and update().
hrt_abstime launchdetection::CatapultLaunchMethod::_last_timestamp {0} private
Definition at line 64 of file CatapultLaunchMethod.h.
Referenced by CatapultLaunchMethod(), and update().
float launchdetection::CatapultLaunchMethod::_motorDelayCounter {0.0f} private
Definition at line 66 of file CatapultLaunchMethod.h.
Referenced by reset(), and update().
LaunchDetectionResult launchdetection::CatapultLaunchMethod::state {LAUNCHDETECTION_RES_NONE} private
Definition at line 68 of file CatapultLaunchMethod.h.
Referenced by getLaunchDetected(), getPitchMax(), reset(), and update().
The documentation for this class was generated from the following files:
src/modules/fw_pos_control_l1/launchdetection/CatapultLaunchMethod.h
src/modules/fw_pos_control_l1/launchdetection/CatapultLaunchMethod.cpp