PX4 Firmware: src/drivers/boards/aerocore2/led.c File Reference
led.c File Reference
#include <px4_config.h>
#include <stdbool.h>
#include "stm32.h"
#include "board_config.h"
#include <arch/board/board.h>
Functions
__BEGIN_DECLS void led_init (void)
Ideally we'd be able to get these from up_internal.h, but since we want to be able to disable the NuttX use of leds for system indication at will and there is no separate switch, we need to build independent of the CONFIG_ARCH_LEDS configuration switch.
void led_on (int led)
void led_off (int led)
void led_toggle (int led)
static void phy_set_led (int led, bool state)
static bool phy_get_led (int led)
Variables
static __END_DECLS uint32_t g_ledmap []
Function Documentation
__BEGIN_DECLS void led_init (void)
Ideally we'd be able to get these from up_internal.h, but since we want to be able to disable the NuttX use of leds for system indication at will and there is no separate switch, we need to build independent of the CONFIG_ARCH_LEDS configuration switch.
Definition at line 72 of file led.c.
Referenced by board_autoled_initialize(), and led_toggle().
void led_off (int led)
Definition at line 97 of file led.c.
void led_on (int led)
Definition at line 92 of file led.c.
__EXPORT void led_toggle (int led)
Definition at line 102 of file led.c.
Referenced by control_status_leds().
static bool phy_get_led (int led) static
Definition at line 86 of file led.c.
References g_ledmap.
Referenced by led_toggle().
static void phy_set_led (int led, bool state) static
Definition at line 80 of file led.c.
References g_ledmap.
Referenced by led_off(), led_on(), and led_toggle().
Variable Documentation
__END_DECLS uint32_t g_ledmap[] static
Initial value:
= {
    GPIO_LED_BLUE,
    GPIO_LED_RED,
    GPIO_LED_SAFETY,
    GPIO_LED_GREEN,
}
Definition at line 65 of file led.c.
Referenced by led_init(), phy_get_led(), and phy_set_led().