PX4 Firmware: src/drivers/boards/common/samv7/board_identity.c File Reference
board_identity.c File Reference
#include <px4_config.h>
#include <stdint.h>
#include <stdio.h>
#include <string.h>
#include <chip/sam_memorymap.h>
#include <chip/sam_eefc.h>
Macros
#define SWAP_UINT32(x) (((x) >> 24) | (((x) & 0x00ff0000) >> 8) | (((x) & 0x0000ff00) << 8) | ((x) << 24))
Functions
void board_get_uuid (uuid_byte_t uuid_bytes)
void board_get_uuid32 (uuid_uint32_t uuid_words)
int board_get_uuid32_formated (char *format_buffer, int size, const char *format, const char *seperator)
int board_get_mfguid (mfguid_t mfgid)
int board_get_mfguid_formated (char *format_buffer, int size)
Variables
const uint32_t DUMMY_SIM_UIDH [4] = {0x12345678, 0x12345678, 0x12345678, 0x12345678 }
Macro Definition Documentation
#define SWAP_UINT32 (x) (((x) >> 24) | (((x) & 0x00ff0000) >> 8) | (((x) & 0x0000ff00) << 8) | ((x) << 24))
Definition at line 47 of file board_identity.c.
Referenced by board_get_uuid().
Function Documentation
int board_get_mfguid (mfguid_t mfgid)
Definition at line 88 of file board_identity.c.
References board_get_uuid().
int board_get_mfguid_formated (char * format_buffer, int size)
Definition at line 94 of file board_identity.c.
References board_get_mfguid().
void board_get_uuid (uuid_byte_t uuid_bytes)
Definition at line 51 of file board_identity.c.
References DUMMY_SIM_UIDH, and SWAP_UINT32.
void board_get_uuid32 (uuid_uint32_t uuid_words)
Definition at line 61 of file board_identity.c.
References board_get_uuid().
int board_get_uuid32_formated (char * format_buffer, int size, const char * format, const char * seperator)
Definition at line 66 of file board_identity.c.
References board_get_uuid32().
Variable Documentation
const uint32_t DUMMY_SIM_UIDH[4] = {0x12345678, 0x12345678, 0x12345678, 0x12345678 }
Definition at line 49 of file board_identity.c.
Referenced by board_get_uuid().