PX4 Firmware: bmp280 Namespace Reference
bmp280 Namespace Reference
Local functions in support of the shell command.
Classes
struct bmp280_bus_option
struct calibration_s
struct data_s
struct fcalibration_s
class IBMP280
Functions
bool start_bus (struct bmp280_bus_option &bus)
Start the driver.
struct bmp280_bus_option & find_bus (enum BMP280_BUS busid)
find a bus structure for a busid
void start (enum BMP280_BUS busid)
Start the driver.
void test (enum BMP280_BUS busid)
Perform some basic functional tests on the driver; make sure we can collect data from the sensor in polled and automatic modes.
void reset (enum BMP280_BUS busid)
Reset the driver.
void info ()
Print a little info about the driver.
void usage ()
Prints info about the driver argument usage.
Variables
struct bmp280::bmp280_bus_option bus_options []
Detailed Description
Local functions in support of the shell command.
Function Documentation
struct bmp280_bus_option & bmp280::find_bus (enum BMP280_BUS busid)
find a bus structure for a busid
Definition at line 700 of file bmp280.cpp.
References BMP280_BUS_ALL, bus_options, NUM_BUS_OPTIONS, and PX4_ERR.
Referenced by lis3mdl::calibrate(), lis3mdl::info(), lis3mdl::init(), lis3mdl::reset(), reset(), lis3mdl::test(), and test().
void bmp280::info ()
Print a little info about the driver.
Definition at line 820 of file bmp280.cpp.
Referenced by bmp280_main(), hardfault_dowrite(), and uORBTest::UnitTest::~UnitTest().
void bmp280::reset (enum BMP280_BUS busid)
Reset the driver.
Definition at line 791 of file bmp280.cpp.
References bmp280::bmp280_bus_option::devpath, fd, find_bus(), BMP280::ioctl(), device::CDev::open(), PX4_ERR, SENSOR_POLLRATE_DEFAULT, SENSORIOCRESET, and SENSORIOCSPOLLRATE.
Referenced by bmp280_main(), runwaytakeoff::RunwayTakeoff::climbout(), Integrator::get_and_filtered(), math::LowPassFilter2p::get_cutoff_freq(), and uORB::DeviceNode::is_published().
void bmp280::start (enum BMP280_BUS busid)
Start the driver.
This function call only returns once the driver is either successfully up and running or failed to start.
Definition at line 667 of file bmp280.cpp.
References BMP280_BUS_ALL, bus_options, NUM_BUS_OPTIONS, PX4_ERR, PX4_WARN, and start_bus().
Referenced by bmp280_main().
bool bmp280::start_bus (struct bmp280_bus_option & bus)
Start the driver.
Definition at line 614 of file bmp280.cpp.
References BMP280::BMP280(), device::CDev::close(), bmp280::bmp280_bus_option::dev, fd, BMP280::ioctl(), OK, device::CDev::open(), PX4_ERR, PX4_WARN, SENSOR_POLLRATE_DEFAULT, and SENSORIOCSPOLLRATE.
Referenced by lis3mdl::start(), and start().
void bmp280::test (enum BMP280_BUS busid)
Perform some basic functional tests on the driver; make sure we can collect data from the sensor in polled and automatic modes.
Definition at line 719 of file bmp280.cpp.
References baro_report, device::CDev::close(), bmp280::bmp280_bus_option::devpath, fd, find_bus(), BMP280::ioctl(), OK, device::CDev::open(), device::CDev::poll(), PX4_ERR, BMP280::read(), SENSORIOCSPOLLRATE, and SENSORIOCSQUEUEDEPTH.
Referenced by bmp280_main().
void bmp280::usage (void)
Prints info about the driver argument usage.
Definition at line 835 of file bmp280.cpp.
References PX4_WARN.
Referenced by bmp280_main().
Variable Documentation
struct bmp280::bmp280_bus_option bmp280::bus_options[]
Initial value:
= {
}
Referenced by find_bus(), ets_airspeed::info(), and start().