PX4 Firmware: src/drivers/differential_pressure/ms4525/ms4525_airspeed.cpp File Reference
ms4525_airspeed.cpp File Reference
#include <px4_config.h>
#include <px4_getopt.h>
#include <drivers/device/i2c.h>
#include <systemlib/err.h>
#include <parameters/param.h>
#include <perf/perf_counter.h>
#include <mathlib/math/filter/LowPassFilter2p.hpp>
#include <drivers/drv_airspeed.h>
#include <drivers/drv_hrt.h>
#include <uORB/uORB.h>
#include <uORB/topics/differential_pressure.h>
#include <uORB/topics/system_power.h>
#include <drivers/airspeed/airspeed.h>
Classes
class MEASAirspeed
Namespaces
meas_airspeed
Local functions in support of the shell command.
Macros
#define I2C_ADDRESS_MS4515DO 0x46
#define I2C_ADDRESS_MS4525DO 0x28
7-bit address.
#define PATH_MS4525 "/dev/ms4525"
#define ADDR_READ_MR 0x00 /* write to this address to start conversion */
#define MEAS_RATE 100
#define MEAS_DRIVER_FILTER_FREQ 1.2f
#define CONVERSION_INTERVAL (1000000 / MEAS_RATE) /* microseconds */
Enumerations
enum MS_DEVICE_TYPE { DEVICE_TYPE_MS4515 = 4515, DEVICE_TYPE_MS4525 = 4525 }
Functions
__EXPORT int ms4525_airspeed_main (int argc, char *argv[])
int meas_airspeed::start ()
Attempt to start driver on all available I2C busses.
int meas_airspeed::start_bus (int i2c_bus, int address)
Start the driver on a specific bus.
int meas_airspeed::stop ()
Stop the driver.
int meas_airspeed::reset ()
Reset the driver.
static void meas_airspeed_usage ()
Variables
MEASAirspeed * meas_airspeed::g_dev = nullptr
Macro Definition Documentation
#define ADDR_READ_MR 0x00 /* write to this address to start conversion */
Definition at line 83 of file ms4525_airspeed.cpp.
#define CONVERSION_INTERVAL (1000000 / MEAS_RATE) /* microseconds */
Definition at line 88 of file ms4525_airspeed.cpp.
Referenced by MEASAirspeed::cycle().
#define I2C_ADDRESS_MS4515DO 0x46
Definition at line 78 of file ms4525_airspeed.cpp.
Referenced by ms4525_airspeed_main().
#define I2C_ADDRESS_MS4525DO 0x28
7-bit address.
Depends on the order code (this is for code "I")
Definition at line 79 of file ms4525_airspeed.cpp.
Referenced by ms4525_airspeed_main(), and meas_airspeed::start().
#define MEAS_DRIVER_FILTER_FREQ 1.2f
Definition at line 87 of file ms4525_airspeed.cpp.
#define MEAS_RATE 100
Definition at line 86 of file ms4525_airspeed.cpp.
#define PATH_MS4525 "/dev/ms4525"
Definition at line 80 of file ms4525_airspeed.cpp.
Referenced by meas_airspeed::reset(), and meas_airspeed::start_bus().
Enumeration Type Documentation
enum MS_DEVICE_TYPE
Enumerator
DEVICE_TYPE_MS4515
DEVICE_TYPE_MS4525
Definition at line 72 of file ms4525_airspeed.cpp.
Function Documentation
static void meas_airspeed_usage () static
Definition at line 497 of file ms4525_airspeed.cpp.
References PX4_I2C_BUS_DEFAULT, and PX4_INFO.
Referenced by ms4525_airspeed_main().
int ms4525_airspeed_main (int argc, char * argv[])
Definition at line 508 of file ms4525_airspeed.cpp.
References DEVICE_TYPE_MS4515, DEVICE_TYPE_MS4525, I2C_ADDRESS_MS4515DO, I2C_ADDRESS_MS4525DO, meas_airspeed_usage(), px4_getopt(), PX4_I2C_BUS_DEFAULT, meas_airspeed::reset(), meas_airspeed::start(), meas_airspeed::start_bus(), and meas_airspeed::stop().