PX4 Firmware: src/drivers/barometer/bmp388/bmp388_main.cpp File Reference
bmp388_main.cpp File Reference
#include <px4_platform_common/px4_config.h>
#include <px4_platform_common/getopt.h>
#include "bmp388.h"
Classes
struct bmp388::bmp388_bus_option
Namespaces
bmp388
Enumerations
enum BMP388_BUS {
BMP388_BUS::ALL = 0, BMP388_BUS::I2C_INTERNAL, BMP388_BUS::I2C_INTERNAL1, BMP388_BUS::I2C_EXTERNAL,
BMP388_BUS::SPI_INTERNAL, BMP388_BUS::SPI_EXTERNAL
}
Functions
static struct bmp388_bus_option * bmp388::find_bus (BMP388_BUS busid)
static bool bmp388::start_bus (bmp388_bus_option &bus)
static int bmp388::start (BMP388_BUS busid)
static int bmp388::stop (BMP388_BUS busid)
static int bmp388::status (BMP388_BUS busid)
static int bmp388::usage ()
int bmp388_main (int argc, char *argv[])
Variables
struct bmp388::bmp388_bus_option bmp388::bus_options []
Enumeration Type Documentation
BMP388_BUS
enum BMP388_BUS strong
Enumerator
ALL
I2C_INTERNAL
I2C_INTERNAL1
I2C_EXTERNAL
SPI_INTERNAL
SPI_EXTERNAL
Definition at line 39 of file bmp388_main.cpp.
Function Documentation
bmp388_main()
int bmp388_main (int argc, char * argv[])
Definition at line 184 of file bmp388_main.cpp.
References ALL, I2C_EXTERNAL, I2C_INTERNAL, I2C_INTERNAL1, SPI_EXTERNAL, SPI_INTERNAL, bmp388::start(), bmp388::status(), bmp388::stop(), and bmp388::usage().