PX4 Firmware: do_not_explicitly_use_this_namespace::Param< bool, p > Class Template Reference
do_not_explicitly_use_this_namespace::Param< bool, p > Class Template Reference
#include <px4_param.h>
Public Member Functions
Param ()
bool get () const
const bool & reference () const
bool commit () const
Store the parameter value to the parameter storage (.
bool commit_no_notification () const
Store the parameter value to the parameter storage, w/o notifying the system (.
void set (bool val)
bool update ()
param_t handle () const
Private Attributes
bool _val
Detailed Description
template<px4::params p>
class do_not_explicitly_use_this_namespace::Param< bool, p >
Definition at line 243 of file px4_param.h.
Constructor & Destructor Documentation
template<px4::params p> do_not_explicitly_use_this_namespace::Param< bool, p >::Param () inline
Definition at line 249 of file px4_param.h.
References param_set_used().
Member Function Documentation
template<px4::params p> bool do_not_explicitly_use_this_namespace::Param< bool, p >::commit () const inline
Store the parameter value to the parameter storage (.
See also
param_set())
Definition at line 260 of file px4_param.h.
References param_set().
template<px4::params p> bool do_not_explicitly_use_this_namespace::Param< bool, p >::commit_no_notification () const inline
Store the parameter value to the parameter storage, w/o notifying the system (.
See also
param_set_no_notification())
Definition at line 267 of file px4_param.h.
References param_set_no_notification().
template<px4::params p> bool do_not_explicitly_use_this_namespace::Param< bool, p >::get () const inline
Definition at line 255 of file px4_param.h.
template<px4::params p> param_t do_not_explicitly_use_this_namespace::Param< bool, p >::handle () const inline
Definition at line 288 of file px4_param.h.
References param_handle().
template<px4::params p> const bool& do_not_explicitly_use_this_namespace::Param< bool, p >::reference () const inline
Definition at line 257 of file px4_param.h.
template<px4::params p> void do_not_explicitly_use_this_namespace::Param< bool, p >::set (bool val) inline
Definition at line 273 of file px4_param.h.
template<px4::params p> bool do_not_explicitly_use_this_namespace::Param< bool, p >::update () inline
Definition at line 275 of file px4_param.h.
References param_get().
Member Data Documentation
template<px4::params p> bool do_not_explicitly_use_this_namespace::Param< bool, p >::_val private
Definition at line 290 of file px4_param.h.
The documentation for this class was generated from the following file:
src/platforms/px4_param.h