PX4 Firmware: HC_SR04 Class Reference
HC_SR04 Class Reference
Classes
struct GPIOConfig
Public Member Functions
HC_SR04 (unsigned sonars=6)
virtual ~HC_SR04 ()
virtual int init ()
Initialise the driver and make it ready for use.
virtual ssize_t read (device::file_t *filp, char *buffer, size_t buflen)
Perform a read from the device.
virtual int ioctl (device::file_t *filp, int cmd, unsigned long arg)
Perform an ioctl operation on the device.
void print_info ()
Diagnostics - print some basic information about the driver.
void interrupt (unsigned time)
Public Member Functions inherited from device::CDev
CDev (const char *name, const char *devname)
Constructor.
virtual ~CDev ()
virtual int open (file_t *filep)
Handle an open of the device.
virtual int close (file_t *filep)
Handle a close of the device.
virtual ssize_t write (file_t *filep, const char *buffer, size_t buflen)
Perform a write to the device.
virtual off_t seek (file_t *filep, off_t offset, int whence)
Perform a logical seek operation on the device.
virtual int poll (file_t *filep, px4_pollfd_struct_t *fds, bool setup)
Perform a poll setup/teardown operation.
Public Member Functions inherited from device::Device
virtual ~Device ()=default
Destructor.
virtual int read (unsigned address, void *data, unsigned count)
Read directly from the device.
virtual int write (unsigned address, void *data, unsigned count)
Write directly to the device.
virtual int ioctl (unsigned operation, unsigned &arg)
Perform a device-specific operation.
uint8_t get_device_bus ()
Return the bus ID the device is connected to.
DeviceBusType get_device_bus_type ()
Return the bus type the device is connected to.
uint8_t get_device_address ()
Return the bus address of the device.
void set_device_address (int address)
void set_device_type (uint8_t devtype)
Set the device type.
virtual bool external ()
Protected Member Functions
virtual int probe ()
Protected Member Functions inherited from device::CDev
virtual pollevent_t poll_state (file_t *filep)
Check the current state of the device for poll events from the perspective of the file.
virtual void poll_notify (pollevent_t events)
Report new poll events.
virtual void poll_notify_one (px4_pollfd_struct_t *fds, pollevent_t events)
Internal implementation of poll_notify.
virtual int open_first (file_t *filep)
Notification of the first open.
virtual int close_last (file_t *filep)
Notification of the last close.
virtual int register_class_devname (const char *class_devname)
Register a class device name, automatically adding device class instance suffix if need be.
virtual int unregister_class_devname (const char *class_devname, unsigned class_instance)
Register a class device name, automatically adding device class instance suffix if need be.
const char * get_devname ()
Get the device name.
void lock ()
Take the driver lock.
void unlock ()
Release the driver lock.
Protected Member Functions inherited from device::Device
Device (const char *name)
Device (DeviceBusType bus_type, uint8_t bus, uint8_t address, uint8_t devtype=0)
Device (const Device &)=delete
Device & operator= (const Device &)=delete
Device (Device &&)=delete
Device & operator= (Device &&)=delete
Private Member Functions
int probe_address (uint8_t address)
Test whether the device supported by the driver is present at a specific address.
void start ()
Initialise the automatic measurement state machine and start it.
void stop ()
Stop the automatic measurement state machine.
void set_minimum_distance (float min)
Set the min and max distance thresholds if you want the end points of the sensors range to be brought in at all, otherwise it will use the defaults MB12XX_MIN_DISTANCE and MB12XX_MAX_DISTANCE.
void set_maximum_distance (float max)
float get_minimum_distance ()
float get_maximum_distance ()
void cycle ()
Perform a poll cycle; collect from the previous measurement and start a new one.
int measure ()
int collect ()
Static Private Member Functions
static void cycle_trampoline (void *arg)
Static trampoline from the workq context; because we don't have a generic workq wrapper yet.
Private Attributes
float _min_distance
float _max_distance
work_s _work
ringbuffer::RingBuffer * _reports
bool _sensor_ok
int _measure_ticks
bool _collect_phase
int _class_instance
int _orb_class_instance
orb_advert_t _distance_sensor_topic
perf_counter_t _sample_perf
perf_counter_t _comms_errors
uint8_t _cycle_counter
int _cycling_rate
uint8_t _index_counter
std::vector< float > _latest_sonar_measurements
unsigned _sonars
unsigned _raising_time
unsigned _falling_time
unsigned _status
Static Private Attributes
static const GPIOConfig _gpio_tab []
Additional Inherited Members
Public Types inherited from device::Device
enum DeviceBusType { DeviceBusType_UNKNOWN = 0, DeviceBusType_I2C = 1, DeviceBusType_SPI = 2, DeviceBusType_UAVCAN = 3 }
Device bus types for DEVID.
Protected Attributes inherited from device::CDev
px4_sem_t _lock
lock to protect access to all class members (also for derived classes)
bool _pub_blocked {false}
true if publishing should be blocked
Protected Attributes inherited from device::Device
union DeviceId _device_id
device identifier information
const char * _name
driver name
bool _debug_enabled {false}
if true, debug messages are printed
Static Protected Attributes inherited from device::CDev
static const px4_file_operations_t fops = {}
Pointer to the default cdev file operations table; useful for registering clone devices etc.
Detailed Description
Definition at line 86 of file hc_sr04.cpp.
Constructor & Destructor Documentation
HC_SR04::HC_SR04 (unsigned sonars = 6)
Definition at line 203 of file hc_sr04.cpp.
References device::Device::_debug_enabled.
Referenced by hc_sr04::start().
HC_SR04::~HC_SR04 () virtual
Definition at line 232 of file hc_sr04.cpp.
References _class_instance, _comms_errors, _reports, _sample_perf, perf_free(), RANGE_FINDER_BASE_DEVICE_PATH, stop(), and device::CDev::unregister_class_devname().
Member Function Documentation
int HC_SR04::collect () private
Definition at line 528 of file hc_sr04.cpp.
References _comms_errors, _cycle_counter, _distance_sensor_topic, _falling_time, _gpio_tab, _latest_sonar_measurements, _raising_time, _reports, _sample_perf, _sonars, _status, DEVICE_DEBUG, get_maximum_distance(), get_minimum_distance(), hrt_absolute_time(), distance_sensor_s::id, OK, ORB_ID, orb_publish(), perf_begin(), perf_end(), perf_event_count(), device::CDev::poll_notify(), SR04_ID_BASE, and distance_sensor_s::timestamp.
Referenced by cycle(), and read().
void HC_SR04::cycle () private
Perform a poll cycle; collect from the previous measurement and start a new one.
Definition at line 643 of file hc_sr04.cpp.
References _cycle_counter, _cycling_rate, _sonars, collect(), cycle_trampoline(), DEVICE_DEBUG, measure(), and OK.
Referenced by cycle_trampoline().
void HC_SR04::cycle_trampoline (void * arg) static private
Static trampoline from the workq context; because we don't have a generic workq wrapper yet.
Parameters
arg Instance pointer for the driver that is polling.
Definition at line 633 of file hc_sr04.cpp.
References cycle().
Referenced by cycle(), and start().
float HC_SR04::get_maximum_distance () private
Definition at line 327 of file hc_sr04.cpp.
References _max_distance.
Referenced by collect().
float HC_SR04::get_minimum_distance () private
Definition at line 321 of file hc_sr04.cpp.
References _min_distance.
Referenced by collect().
int HC_SR04::init () virtual
Initialise the driver and make it ready for use.
Returns
OK if the driver initialized OK, negative errno otherwise;
Reimplemented from device::CDev.
Definition at line 252 of file hc_sr04.cpp.
References _class_instance, _cycling_rate, _distance_sensor_topic, _gpio_tab, _latest_sonar_measurements, _orb_class_instance, _reports, _sensor_ok, _sonars, DEVICE_DEBUG, DEVICE_LOG, lis3mdl::init(), OK, orb_advertise_multi(), ORB_ID, ORB_PRIO_LOW, PX4_ERROR, RANGE_FINDER_BASE_DEVICE_PATH, device::CDev::register_class_devname(), SR04_CONVERSION_INTERVAL, and usleep().
Referenced by hc_sr04::start().
void HC_SR04::interrupt (unsigned time)
Definition at line 332 of file hc_sr04.cpp.
References _falling_time, _raising_time, and _status.
Referenced by sonar_isr().
int HC_SR04::ioctl (device::file_t * filep, int cmd, unsigned long arg) virtual
Perform an ioctl operation on the device.
The default implementation handles DIOC_GETPRIV, and otherwise returns -ENOTTY. Subclasses should call the default implementation for any command they do not handle themselves.
Parameters
filep Pointer to the NuttX file structure.
cmd The ioctl command value.
arg The ioctl argument value.
Returns
OK on success, or -errno otherwise.
Reimplemented from device::CDev.
Definition at line 349 of file hc_sr04.cpp.
References _cycling_rate, _measure_ticks, _reports, ATOMIC_ENTER, ATOMIC_LEAVE, OK, SENSOR_POLLRATE_DEFAULT, SENSOR_POLLRATE_EXTERNAL, SENSOR_POLLRATE_MANUAL, SENSOR_POLLRATE_MAX, SENSORIOCGPOLLRATE, SENSORIOCRESET, SENSORIOCSPOLLRATE, SENSORIOCSQUEUEDEPTH, start(), and stop().
Referenced by hc_sr04::reset(), hc_sr04::start(), and hc_sr04::test().
int HC_SR04::measure () private
Definition at line 509 of file hc_sr04.cpp.
References _cycle_counter, _gpio_tab, _status, OK, sonar_isr(), and usleep().
Referenced by cycle(), read(), and start().
void HC_SR04::print_info ()
Diagnostics - print some basic information about the driver.
Definition at line 673 of file hc_sr04.cpp.
References _comms_errors, _measure_ticks, _reports, _sample_perf, and perf_print_counter().
Referenced by hc_sr04::info().
int HC_SR04::probe () protected virtual
Definition at line 303 of file hc_sr04.cpp.
References OK.
int HC_SR04::probe_address (uint8_t address) private
Test whether the device supported by the driver is present at a specific address.
Parameters
address The I2C bus address to probe.
Returns
True if the device is present.
ssize_t HC_SR04::read (device::file_t * filep, char * buffer, size_t buflen) virtual
Perform a read from the device.
The default implementation returns -ENOSYS.
Parameters
filep Pointer to the NuttX file structure.
buffer Pointer to the buffer into which data should be placed.
buflen The number of bytes to be read.
Returns
The number of bytes read or -errno otherwise.
Reimplemented from device::CDev.
Definition at line 449 of file hc_sr04.cpp.
References _cycling_rate, _measure_ticks, _reports, collect(), measure(), OK, and usleep().
Referenced by hc_sr04::test().
void HC_SR04::set_maximum_distance (float max) private
Definition at line 315 of file hc_sr04.cpp.
References _max_distance, and max().
void HC_SR04::set_minimum_distance (float min) private
Set the min and max distance thresholds if you want the end points of the sensors range to be brought in at all, otherwise it will use the defaults MB12XX_MIN_DISTANCE and MB12XX_MAX_DISTANCE.
Definition at line 309 of file hc_sr04.cpp.
References _min_distance, and min().
void HC_SR04::start () private
Initialise the automatic measurement state machine and start it.
Note
This function is called at open and error time. It might make sense to make it more aggressive about resetting the bus in case of errors.
Definition at line 609 of file hc_sr04.cpp.
References _collect_phase, _cycling_rate, _reports, cycle_trampoline(), and measure().
Referenced by ioctl().
void HC_SR04::stop () private
Stop the automatic measurement state machine.
Definition at line 627 of file hc_sr04.cpp.
Referenced by ioctl(), and ~HC_SR04().
Member Data Documentation
int HC_SR04::_class_instance private
Definition at line 114 of file hc_sr04.cpp.
Referenced by init(), and ~HC_SR04().
bool HC_SR04::_collect_phase private
Definition at line 113 of file hc_sr04.cpp.
Referenced by start().
perf_counter_t HC_SR04::_comms_errors private
Definition at line 120 of file hc_sr04.cpp.
Referenced by collect(), print_info(), and ~HC_SR04().
uint8_t HC_SR04::_cycle_counter private
Definition at line 122 of file hc_sr04.cpp.
Referenced by collect(), cycle(), and measure().
int HC_SR04::_cycling_rate private
Definition at line 123 of file hc_sr04.cpp.
Referenced by cycle(), init(), ioctl(), read(), and start().
orb_advert_t HC_SR04::_distance_sensor_topic private
Definition at line 117 of file hc_sr04.cpp.
Referenced by collect(), and init().
unsigned HC_SR04::_falling_time private
Definition at line 136 of file hc_sr04.cpp.
Referenced by collect(), and interrupt().
const HC_SR04::GPIOConfig HC_SR04::_gpio_tab static private
Initial value:
= {
    {GPIO_GPIO6_OUTPUT,      GPIO_GPIO7_INPUT,       0},
    {GPIO_GPIO6_OUTPUT,      GPIO_GPIO8_INPUT,       0},
    {GPIO_GPIO6_OUTPUT,      GPIO_GPIO9_INPUT,       0},
    {GPIO_GPIO6_OUTPUT,      GPIO_GPIO10_INPUT,       0},
    {GPIO_GPIO6_OUTPUT,      GPIO_GPIO11_INPUT,       0},
    {GPIO_GPIO6_OUTPUT,      GPIO_GPIO12_INPUT,       0}
}
Definition at line 134 of file hc_sr04.cpp.
Referenced by collect(), init(), and measure().
uint8_t HC_SR04::_index_counter private
Definition at line 124 of file hc_sr04.cpp.
std::vector<float> HC_SR04::_latest_sonar_measurements private
Definition at line 127 of file hc_sr04.cpp.
Referenced by collect(), and init().
float HC_SR04::_max_distance private
Definition at line 108 of file hc_sr04.cpp.
Referenced by get_maximum_distance(), and set_maximum_distance().
int HC_SR04::_measure_ticks private
Definition at line 112 of file hc_sr04.cpp.
Referenced by ioctl(), print_info(), and read().
float HC_SR04::_min_distance private
Definition at line 107 of file hc_sr04.cpp.
Referenced by get_minimum_distance(), and set_minimum_distance().
int HC_SR04::_orb_class_instance private
Definition at line 115 of file hc_sr04.cpp.
Referenced by init().
unsigned HC_SR04::_raising_time private
Definition at line 135 of file hc_sr04.cpp.
Referenced by collect(), and interrupt().
ringbuffer::RingBuffer* HC_SR04::_reports private
Definition at line 110 of file hc_sr04.cpp.
Referenced by collect(), init(), ioctl(), print_info(), read(), start(), and ~HC_SR04().
perf_counter_t HC_SR04::_sample_perf private
Definition at line 119 of file hc_sr04.cpp.
Referenced by collect(), print_info(), and ~HC_SR04().
bool HC_SR04::_sensor_ok private
Definition at line 111 of file hc_sr04.cpp.
Referenced by init().
unsigned HC_SR04::_sonars private
Definition at line 128 of file hc_sr04.cpp.
Referenced by collect(), cycle(), and init().
unsigned HC_SR04::_status private
Definition at line 137 of file hc_sr04.cpp.
Referenced by collect(), interrupt(), and measure().
work_s HC_SR04::_work private
Definition at line 109 of file hc_sr04.cpp.
The documentation for this class was generated from the following file:
src/drivers/distance_sensor/hc_sr04/hc_sr04.cpp