PX4 Firmware: MavlinkReceiver Class Reference
MavlinkReceiver Class Reference
#include <mavlink_receiver.h>
Public Member Functions
MavlinkReceiver (Mavlink *parent)
Constructor.
~MavlinkReceiver ()
Destructor, also kills the mavlinks task.
void print_status ()
Display the mavlink status.
Static Public Member Functions
static void receive_start (pthread_t *thread, Mavlink *parent)
Start the receiver thread.
static void * start_helper (void *context)
Private Member Functions
void acknowledge (uint8_t sysid, uint8_t compid, uint16_t command, uint8_t result)
void handle_message (mavlink_message_t *msg)
void handle_message_command_long (mavlink_message_t *msg)
void handle_message_command_int (mavlink_message_t *msg)
template<class T >
void handle_message_command_both (mavlink_message_t *msg, const T &cmd_mavlink, const vehicle_command_s &vehicle_command)
common method to handle both mavlink command types.
void handle_message_command_ack (mavlink_message_t *msg)
void handle_message_optical_flow_rad (mavlink_message_t *msg)
void handle_message_hil_optical_flow (mavlink_message_t *msg)
void handle_message_set_mode (mavlink_message_t *msg)
void handle_message_att_pos_mocap (mavlink_message_t *msg)
void handle_message_vision_position_estimate (mavlink_message_t *msg)
void handle_message_gps_global_origin (mavlink_message_t *msg)
void handle_message_attitude_quaternion_cov (mavlink_message_t *msg)
void handle_message_local_position_ned_cov (mavlink_message_t *msg)
void handle_message_set_position_target_local_ned (mavlink_message_t *msg)
void handle_message_set_actuator_control_target (mavlink_message_t *msg)
void handle_message_set_attitude_target (mavlink_message_t *msg)
void handle_message_radio_status (mavlink_message_t *msg)
void handle_message_manual_control (mavlink_message_t *msg)
void handle_message_rc_channels_override (mavlink_message_t *msg)
void handle_message_heartbeat (mavlink_message_t *msg)
void handle_message_ping (mavlink_message_t *msg)
void handle_message_hil_sensor (mavlink_message_t *msg)
void handle_message_hil_gps (mavlink_message_t *msg)
void handle_message_hil_state_quaternion (mavlink_message_t *msg)
void handle_message_distance_sensor (mavlink_message_t *msg)
void handle_message_follow_target (mavlink_message_t *msg)
void handle_message_landing_target (mavlink_message_t *msg)
void handle_message_adsb_vehicle (mavlink_message_t *msg)
void handle_message_collision (mavlink_message_t *msg)
void handle_message_gps_rtcm_data (mavlink_message_t *msg)
void handle_message_battery_status (mavlink_message_t *msg)
void handle_message_serial_control (mavlink_message_t *msg)
void handle_message_logging_ack (mavlink_message_t *msg)
void handle_message_play_tune (mavlink_message_t *msg)
void handle_message_obstacle_distance (mavlink_message_t *msg)
void handle_message_trajectory_representation_waypoints (mavlink_message_t *msg)
void handle_message_named_value_float (mavlink_message_t *msg)
void handle_message_debug (mavlink_message_t *msg)
void handle_message_debug_vect (mavlink_message_t *msg)
void * receive_thread (void *arg)
Receive data from UART.
int set_message_interval (int msgId, float interval, int data_rate=-1)
Set the interval at which the given message stream is published.
void get_message_interval (int msgId)
switch_pos_t decode_switch_pos (uint16_t buttons, unsigned sw)
Decode a switch position from a bitfield.
int decode_switch_pos_n (uint16_t buttons, unsigned sw)
Decode a switch position from a bitfield and state.
bool evaluate_target_ok (int command, int target_system, int target_component)
void send_flight_information ()
void send_storage_information (int storage_id)
MavlinkReceiver (const MavlinkReceiver &)=delete
MavlinkReceiver operator= (const MavlinkReceiver &)=delete
Private Attributes
Mavlink * _mavlink
MavlinkMissionManager _mission_manager
MavlinkParametersManager _parameters_manager
MavlinkFTP _mavlink_ftp
MavlinkLogHandler _mavlink_log_handler
MavlinkTimesync _mavlink_timesync
mavlink_status_t _status
receiver status, used for mavlink_parse_char()
struct vehicle_local_position_s _hil_local_pos
struct vehicle_land_detected_s _hil_land_detector
struct vehicle_control_mode_s _control_mode
orb_advert_t _global_pos_pub
orb_advert_t _local_pos_pub
orb_advert_t _attitude_pub
orb_advert_t _gps_pub
orb_advert_t _gyro_pub
orb_advert_t _accel_pub
orb_advert_t _mag_pub
orb_advert_t _baro_pub
orb_advert_t _airspeed_pub
orb_advert_t _battery_pub
orb_advert_t _cmd_pub
orb_advert_t _flow_pub
orb_advert_t _hil_distance_sensor_pub
orb_advert_t _flow_distance_sensor_pub
orb_advert_t _distance_sensor_pub
orb_advert_t _offboard_control_mode_pub
orb_advert_t _actuator_controls_pubs [4]
orb_advert_t _att_sp_pub
orb_advert_t _rates_sp_pub
orb_advert_t _pos_sp_triplet_pub
orb_advert_t _att_pos_mocap_pub
orb_advert_t _vision_position_pub
orb_advert_t _vision_attitude_pub
orb_advert_t _telemetry_status_pub
orb_advert_t _ping_pub
orb_advert_t _rc_pub
orb_advert_t _manual_pub
orb_advert_t _obstacle_distance_pub
orb_advert_t _trajectory_waypoint_pub
orb_advert_t _land_detector_pub
orb_advert_t _follow_target_pub
orb_advert_t _landing_target_pose_pub
orb_advert_t _transponder_report_pub
orb_advert_t _collision_report_pub
orb_advert_t _debug_key_value_pub
orb_advert_t _debug_value_pub
orb_advert_t _debug_vect_pub
orb_advert_t _gps_inject_data_pub
orb_advert_t _command_ack_pub
int _control_mode_sub
int _actuator_armed_sub
uint64_t _global_ref_timestamp
int _hil_frames
uint64_t _old_timestamp
bool _hil_local_proj_inited
float _hil_local_alt0
struct map_projection_reference_s _hil_local_proj_ref
struct offboard_control_mode_s _offboard_control_mode
int _orb_class_instance
uint8_t _mom_switch_pos [MOM_SWITCH_COUNT]
uint16_t _mom_switch_state
param_t _p_bat_emergen_thr
param_t _p_bat_crit_thr
param_t _p_bat_low_thr
Static Private Attributes
static const int _gps_inject_data_queue_size = 6
static constexpr unsigned MOM_SWITCH_COUNT = 8
Detailed Description
Definition at line 93 of file mavlink_receiver.h.
Constructor & Destructor Documentation
MavlinkReceiver::MavlinkReceiver (Mavlink * parent)
Constructor.
Definition at line 101 of file mavlink_receiver.cpp.
References _accel_pub, _actuator_armed_sub, _actuator_controls_pubs, _airspeed_pub, _att_pos_mocap_pub, _att_sp_pub, _attitude_pub, _baro_pub, _battery_pub, _cmd_pub, _collision_report_pub, _command_ack_pub, _control_mode, _control_mode_sub, _debug_key_value_pub, _debug_value_pub, _debug_vect_pub, _distance_sensor_pub, _flow_distance_sensor_pub, _flow_pub, _follow_target_pub, _global_pos_pub, _global_ref_timestamp, _gps_inject_data_pub, _gps_pub, _gyro_pub, _hil_distance_sensor_pub, _hil_frames, _hil_land_detector, _hil_local_alt0, _hil_local_pos, _hil_local_proj_inited, _hil_local_proj_ref, _land_detector_pub, _landing_target_pose_pub, _local_pos_pub, _mag_pub, _manual_pub, _mom_switch_pos, _mom_switch_state, _obstacle_distance_pub, _offboard_control_mode, _offboard_control_mode_pub, _old_timestamp, _orb_class_instance, _p_bat_crit_thr, _p_bat_emergen_thr, _p_bat_low_thr, _ping_pub, _pos_sp_triplet_pub, _rates_sp_pub, _rc_pub, _telemetry_status_pub, _trajectory_waypoint_pub, _transponder_report_pub, _vision_attitude_pub, _vision_position_pub, f(), ORB_ID, orb_subscribe(), and param_find().
Referenced by start_helper().
MavlinkReceiver::~MavlinkReceiver ()
Destructor, also kills the mavlinks task.
Definition at line 169 of file mavlink_receiver.cpp.
References _actuator_armed_sub, _control_mode_sub, and orb_unsubscribe().
MavlinkReceiver::MavlinkReceiver (const MavlinkReceiver &) private delete
Member Function Documentation
void MavlinkReceiver::acknowledge (uint8_t sysid, uint8_t compid, uint16_t command, uint8_t result) private
Definition at line 175 of file mavlink_receiver.cpp.
References _command_ack_pub, vehicle_command_ack_s::command, command, hrt_absolute_time(), orb_advertise_queue(), ORB_ID, orb_publish(), vehicle_command_ack_s::result, vehicle_command_ack_s::target_component, vehicle_command_ack_s::target_system, and vehicle_command_ack_s::timestamp.
Referenced by handle_message_command_both().
switch_pos_t MavlinkReceiver::decode_switch_pos (uint16_t buttons, unsigned sw) private
Decode a switch position from a bitfield.
Definition at line 1715 of file mavlink_receiver.cpp.
int MavlinkReceiver::decode_switch_pos_n (uint16_t buttons, unsigned sw) private
Decode a switch position from a bitfield and state.
Definition at line 1722 of file mavlink_receiver.cpp.
References _mom_switch_pos, _mom_switch_state, and MOM_SWITCH_COUNT.
Referenced by handle_message_manual_control().
bool MavlinkReceiver::evaluate_target_ok (int command, int target_system, int target_component) private
Definition at line 396 of file mavlink_receiver.cpp.
References mavlink_system.
Referenced by handle_message_command_both().
void MavlinkReceiver::get_message_interval (int msgId) private
Definition at line 1959 of file mavlink_receiver.cpp.
References _mavlink, Mavlink::get_channel(), MavlinkStream::get_id(), MavlinkStream::get_interval(), Mavlink::get_streams(), and LL_FOREACH.
Referenced by handle_message_command_both().
void MavlinkReceiver::handle_message (mavlink_message_t * msg) private
Definition at line 194 of file mavlink_receiver.cpp.
References _mavlink, Mavlink::accepting_commands(), Mavlink::get_config_link_on(), Mavlink::get_hil_enabled(), Mavlink::get_mode(), Mavlink::get_use_hil_gps(), handle_message_adsb_vehicle(), handle_message_att_pos_mocap(), handle_message_attitude_quaternion_cov(), handle_message_battery_status(), handle_message_collision(), handle_message_command_ack(), handle_message_command_int(), handle_message_command_long(), handle_message_debug(), handle_message_debug_vect(), handle_message_distance_sensor(), handle_message_follow_target(), handle_message_gps_global_origin(), handle_message_gps_rtcm_data(), handle_message_heartbeat(), handle_message_hil_gps(), handle_message_hil_optical_flow(), handle_message_hil_sensor(), handle_message_hil_state_quaternion(), handle_message_landing_target(), handle_message_local_position_ned_cov(), handle_message_logging_ack(), handle_message_manual_control(), handle_message_named_value_float(), handle_message_obstacle_distance(), handle_message_optical_flow_rad(), handle_message_ping(), handle_message_play_tune(), handle_message_radio_status(), handle_message_rc_channels_override(), handle_message_serial_control(), handle_message_set_actuator_control_target(), handle_message_set_attitude_target(), handle_message_set_mode(), handle_message_set_position_target_local_ned(), handle_message_trajectory_representation_waypoints(), handle_message_vision_position_estimate(), Mavlink::MAVLINK_MODE_CONFIG, mavlink_system, Mavlink::set_config_link_on(), and Mavlink::set_has_received_messages().
Referenced by receive_thread().
void MavlinkReceiver::handle_message_adsb_vehicle (mavlink_message_t * msg) private
Definition at line 2199 of file mavlink_receiver.cpp.
References _transponder_report_pub, transponder_report_s::altitude, transponder_report_s::altitude_type, transponder_report_s::callsign, transponder_report_s::emitter_type, transponder_report_s::flags, transponder_report_s::heading, transponder_report_s::hor_velocity, hrt_absolute_time(), transponder_report_s::icao_address, transponder_report_s::lat, transponder_report_s::lon, M_PI_F, orb_advertise_queue(), ORB_ID, orb_publish(), transponder_report_s::squawk, transponder_report_s::timestamp, transponder_report_s::tslc, and transponder_report_s::ver_velocity.
Referenced by handle_message().
void MavlinkReceiver::handle_message_att_pos_mocap (mavlink_message_t * msg) private
Definition at line 837 of file mavlink_receiver.cpp.
References _att_pos_mocap_pub, _mavlink_timesync, hrt_absolute_time(), att_pos_mocap_s::id, orb_advertise(), ORB_ID, orb_publish(), att_pos_mocap_s::q, MavlinkTimesync::sync_stamp(), att_pos_mocap_s::timestamp, att_pos_mocap_s::timestamp_received, att_pos_mocap_s::x, att_pos_mocap_s::y, and att_pos_mocap_s::z.
Referenced by handle_message().
void MavlinkReceiver::handle_message_attitude_quaternion_cov (mavlink_message_t * msg) private
Definition at line 1172 of file mavlink_receiver.cpp.
References _mavlink_timesync, _vision_attitude_pub, ORB_ID, ORB_PRIO_HIGH, orb_publish_auto(), vehicle_attitude_s::pitchspeed, vehicle_attitude_s::q, vehicle_attitude_s::rollspeed, MavlinkTimesync::sync_stamp(), vehicle_attitude_s::timestamp, and vehicle_attitude_s::yawspeed.
Referenced by handle_message().
void MavlinkReceiver::handle_message_battery_status (mavlink_message_t * msg) private
Definition at line 1527 of file mavlink_receiver.cpp.
References _battery_pub, _p_bat_crit_thr, _p_bat_emergen_thr, _p_bat_low_thr, battery_status_s::cell_count, battery_status_s::connected, battery_status_s::current_a, battery_status_s::current_filtered_a, battery_status_s::discharged_mah, hrt_absolute_time(), orb_advertise(), ORB_ID, orb_publish(), param_get(), battery_status_s::remaining, battery_status_s::timestamp, battery_status_s::voltage_filtered_v, battery_status_s::voltage_v, and battery_status_s::warning.
Referenced by handle_message().
void MavlinkReceiver::handle_message_collision (mavlink_message_t * msg) private
Definition at line 2245 of file mavlink_receiver.cpp.
References _collision_report_pub, collision_report_s::action, collision_report_s::altitude_minimum_delta, collision_report_s::horizontal_minimum_delta, hrt_absolute_time(), collision_report_s::id, orb_advertise(), ORB_ID, orb_publish(), collision_report_s::src, collision_report_s::threat_level, collision_report_s::time_to_minimum_delta, and collision_report_s::timestamp.
Referenced by handle_message().
void MavlinkReceiver::handle_message_command_ack (mavlink_message_t * msg) private
Definition at line 627 of file mavlink_receiver.cpp.
References _command_ack_pub, vehicle_command_ack_s::command, vehicle_command_ack_s::from_external, MavlinkCommandSender::handle_mavlink_command_ack(), hrt_absolute_time(), MavlinkCommandSender::instance(), orb_advertise_queue(), ORB_ID, orb_publish(), PX4_WARN, vehicle_command_ack_s::result, vehicle_command_ack_s::result_param1, vehicle_command_ack_s::result_param2, vehicle_command_ack_s::target_component, vehicle_command_ack_s::target_system, and vehicle_command_ack_s::timestamp.
Referenced by handle_message().
template<class T > void MavlinkReceiver::handle_message_command_both (mavlink_message_t * msg, const T & cmd_mavlink, const vehicle_command_s & vehicle_command) private
common method to handle both mavlink command types.
T is one of mavlink_command_int_t or mavlink_command_long_t
Definition at line 541 of file mavlink_receiver.cpp.
References _cmd_pub, _mavlink, acknowledge(), Mavlink::configure_stream_threadsafe(), evaluate_target_ok(), f(), Mavlink::get_data_rate(), get_message_interval(), mavlink_system, orb_advertise_queue(), ORB_ID, orb_publish(), PX4_WARN, Mavlink::request_stop_ulog_streaming(), Mavlink::send_autopilot_capabilites(), send_flight_information(), Mavlink::send_protocol_version(), Mavlink::send_statustext_critical(), send_storage_information(), set_message_interval(), and Mavlink::try_start_ulog_streaming().
Referenced by handle_message_command_int(), and handle_message_command_long().
void MavlinkReceiver::handle_message_command_int (mavlink_message_t * msg) private
Definition at line 512 of file mavlink_receiver.cpp.
References vehicle_command_s::command, vehicle_command_s::confirmation, vehicle_command_s::from_external, handle_message_command_both(), hrt_absolute_time(), vehicle_command_s::param1, vehicle_command_s::param2, vehicle_command_s::param3, vehicle_command_s::param4, vehicle_command_s::param5, vehicle_command_s::param6, vehicle_command_s::param7, vehicle_command_s::source_component, vehicle_command_s::source_system, vehicle_command_s::target_component, vehicle_command_s::target_system, and vehicle_command_s::timestamp.
Referenced by handle_message().
void MavlinkReceiver::handle_message_command_long (mavlink_message_t * msg) private
Definition at line 483 of file mavlink_receiver.cpp.
References vehicle_command_s::command, vehicle_command_s::confirmation, vehicle_command_s::from_external, handle_message_command_both(), hrt_absolute_time(), vehicle_command_s::param1, vehicle_command_s::param2, vehicle_command_s::param3, vehicle_command_s::param4, vehicle_command_s::param5, vehicle_command_s::param6, vehicle_command_s::param7, vehicle_command_s::source_component, vehicle_command_s::source_system, vehicle_command_s::target_component, vehicle_command_s::target_system, and vehicle_command_s::timestamp.
Referenced by handle_message().
void MavlinkReceiver::handle_message_debug (mavlink_message_t * msg) private
Definition at line 2483 of file mavlink_receiver.cpp.
References _debug_value_pub, _mavlink_timesync, debug_value_s::ind, orb_advertise(), ORB_ID, orb_publish(), MavlinkTimesync::sync_stamp(), debug_value_s::timestamp, and debug_value_s::value.
Referenced by handle_message().
void MavlinkReceiver::handle_message_debug_vect (mavlink_message_t * msg) private
Definition at line 2502 of file mavlink_receiver.cpp.
References _debug_vect_pub, _mavlink_timesync, debug_vect_s::name, orb_advertise(), ORB_ID, orb_publish(), MavlinkTimesync::sync_stamp(), debug_vect_s::timestamp, debug_vect_s::x, debug_vect_s::y, and debug_vect_s::z.
Referenced by handle_message().
void MavlinkReceiver::handle_message_distance_sensor (mavlink_message_t * msg) private
TODO Add sensor rotation according to MAV_SENSOR_ORIENTATION enum
Definition at line 807 of file mavlink_receiver.cpp.
References _distance_sensor_pub, _orb_class_instance, distance_sensor_s::covariance, distance_sensor_s::current_distance, f(), distance_sensor_s::id, distance_sensor_s::max_distance, distance_sensor_s::min_distance, orb_advertise_multi(), ORB_ID, ORB_PRIO_HIGH, orb_publish(), distance_sensor_s::orientation, distance_sensor_s::timestamp, and distance_sensor_s::type.
Referenced by handle_message().
void MavlinkReceiver::handle_message_follow_target (mavlink_message_t * msg) private
Definition at line 2155 of file mavlink_receiver.cpp.
References _follow_target_pub, _mavlink_timesync, follow_target_s::alt, follow_target, follow_target_s::lat, follow_target_s::lon, orb_advertise(), ORB_ID, orb_publish(), MavlinkTimesync::sync_stamp(), and follow_target_s::timestamp.
Referenced by handle_message().
void MavlinkReceiver::handle_message_gps_global_origin (mavlink_message_t * msg) private
Definition at line 1157 of file mavlink_receiver.cpp.
References _global_ref_timestamp, f(), globallocalconverter_init(), globallocalconverter_initialized(), and hrt_absolute_time().
Referenced by handle_message().
void MavlinkReceiver::handle_message_gps_rtcm_data (mavlink_message_t * msg) private
Definition at line 2269 of file mavlink_receiver.cpp.
References _gps_inject_data_pub, _gps_inject_data_queue_size, gps_inject_data_s::data, gps_inject_data_s::flags, gps_inject_data_s::len, math::min(), orb_advert_t, orb_advertise_queue(), ORB_ID, and orb_publish().
Referenced by handle_message().
void MavlinkReceiver::handle_message_heartbeat (mavlink_message_t * msg) private
Definition at line 1888 of file mavlink_receiver.cpp.
References _mavlink, _telemetry_status_pub, Mavlink::get_channel(), Mavlink::get_rx_status(), telemetry_status_s::heartbeat_time, hrt_absolute_time(), mavlink_system, orb_advertise_multi(), ORB_ID, ORB_MULTI_MAX_INSTANCES, ORB_PRIO_HIGH, orb_publish(), and telemetry_status_s::timestamp.
Referenced by handle_message().
void MavlinkReceiver::handle_message_hil_gps (mavlink_message_t * msg) private
Definition at line 2114 of file mavlink_receiver.cpp.
References _gps_pub, vehicle_gps_position_s::alt, vehicle_gps_position_s::cog_rad, vehicle_gps_position_s::eph, vehicle_gps_position_s::epv, f(), vehicle_gps_position_s::fix_type, gps, vehicle_gps_position_s::heading, hrt_absolute_time(), vehicle_gps_position_s::lat, vehicle_gps_position_s::lon, orb_advertise(), ORB_ID, orb_publish(), math::radians(), vehicle_gps_position_s::s_variance_m_s, vehicle_gps_position_s::satellites_used, vehicle_gps_position_s::time_utc_usec, vehicle_gps_position_s::timestamp, battery_status_s::timestamp, vehicle_gps_position_s::timestamp_time_relative, vehicle_gps_position_s::vel_d_m_s, vehicle_gps_position_s::vel_e_m_s, vehicle_gps_position_s::vel_m_s, vehicle_gps_position_s::vel_n_m_s, vehicle_gps_position_s::vel_ned_valid, and matrix::wrap_2pi().
Referenced by handle_message().
void MavlinkReceiver::handle_message_hil_optical_flow (mavlink_message_t * msg) private
Definition at line 722 of file mavlink_receiver.cpp.
References _flow_pub, _hil_distance_sensor_pub, _orb_class_instance, distance_sensor_s::covariance, distance_sensor_s::current_distance, optical_flow_s::ground_distance_m, optical_flow_s::gyro_temperature, optical_flow_s::gyro_x_rate_integral, optical_flow_s::gyro_y_rate_integral, optical_flow_s::gyro_z_rate_integral, hrt_absolute_time(), distance_sensor_s::id, optical_flow_s::integration_timespan, distance_sensor_s::max_distance, distance_sensor_s::min_distance, orb_advertise(), orb_advertise_multi(), ORB_ID, ORB_PRIO_HIGH, orb_publish(), distance_sensor_s::orientation, optical_flow_s::pixel_flow_x_integral, optical_flow_s::pixel_flow_y_integral, optical_flow_s::quality, optical_flow_s::sensor_id, optical_flow_s::time_since_last_sonar_update, optical_flow_s::timestamp, distance_sensor_s::timestamp, and distance_sensor_s::type.
Referenced by handle_message().
void MavlinkReceiver::handle_message_hil_sensor (mavlink_message_t * msg) private
Definition at line 1976 of file mavlink_receiver.cpp.
References _accel_pub, _airspeed_pub, _baro_pub, _battery_pub, _gyro_pub, _hil_frames, _mag_pub, _old_timestamp, accel_report, baro_report, calc_indicated_airspeed(), calc_true_airspeed_from_indicated(), CONSTANTS_ONE_G, battery_status_s::current_a, battery_status_s::discharged_mah, gyro_report, hrt_absolute_time(), airspeed_s::indicated_airspeed_m_s, mag_report, orb_advertise(), ORB_ID, orb_publish(), airspeed_s::timestamp, battery_status_s::timestamp, telemetry_status_s::timestamp, airspeed_s::true_airspeed_m_s, battery_status_s::voltage_filtered_v, and battery_status_s::voltage_v.
Referenced by handle_message().
void MavlinkReceiver::handle_message_hil_state_quaternion (mavlink_message_t * msg) private
Definition at line 2294 of file mavlink_receiver.cpp.
References _accel_pub, _airspeed_pub, _attitude_pub, _battery_pub, _global_pos_pub, _hil_land_detector, _hil_local_alt0, _hil_local_pos, _hil_local_proj_inited, _hil_local_proj_ref, _land_detector_pub, _local_pos_pub, accel_report, vehicle_global_position_s::alt, CONSTANTS_ONE_G, matrix::Matrix< Type, M, N >::copyTo(), battery_status_s::current_a, battery_status_s::discharged_mah, vehicle_global_position_s::eph, vehicle_global_position_s::epv, f(), vehicle_local_position_s::hagl_max, vehicle_local_position_s::hagl_min, hrt_absolute_time(), airspeed_s::indicated_airspeed_m_s, vehicle_land_detected_s::landed, vehicle_global_position_s::lat, vehicle_global_position_s::lon, map_projection_init(), map_projection_project(), orb_advertise(), ORB_ID, orb_publish(), vehicle_attitude_s::pitchspeed, matrix::Euler< Type >::psi(), vehicle_attitude_s::q, vehicle_local_position_s::ref_alt, vehicle_local_position_s::ref_lat, vehicle_local_position_s::ref_lon, vehicle_local_position_s::ref_timestamp, vehicle_attitude_s::rollspeed, vehicle_gps_position_s::timestamp, vehicle_global_position_s::timestamp, vehicle_local_position_s::timestamp, vehicle_attitude_s::timestamp, airspeed_s::timestamp, vehicle_land_detected_s::timestamp, battery_status_s::timestamp, airspeed_s::true_airspeed_m_s, vehicle_local_position_s::v_xy_valid, vehicle_local_position_s::v_z_valid, vehicle_global_position_s::vel_d, vehicle_global_position_s::vel_e, vehicle_global_position_s::vel_n, battery_status_s::voltage_filtered_v, battery_status_s::voltage_v, vehicle_local_position_s::vx, vehicle_local_position_s::vxy_max, vehicle_local_position_s::vy, vehicle_local_position_s::vz, vehicle_local_position_s::vz_max, vehicle_local_position_s::x, vehicle_local_position_s::xy_global, vehicle_local_position_s::xy_valid, vehicle_local_position_s::y, vehicle_local_position_s::yaw, vehicle_attitude_s::yawspeed, vehicle_local_position_s::z, vehicle_local_position_s::z_global, and vehicle_local_position_s::z_valid.
Referenced by handle_message().
void MavlinkReceiver::handle_message_landing_target (mavlink_message_t * msg) private
Definition at line 2176 of file mavlink_receiver.cpp.
References _landing_target_pose_pub, _mavlink_timesync, landing_target_pose_s::abs_pos_valid, orb_advertise(), ORB_ID, orb_publish(), MavlinkTimesync::sync_stamp(), landing_target_pose_s::timestamp, landing_target_pose_s::x_abs, landing_target_pose_s::y_abs, and landing_target_pose_s::z_abs.
Referenced by handle_message().
void MavlinkReceiver::handle_message_local_position_ned_cov (mavlink_message_t * msg) private
Definition at line 1198 of file mavlink_receiver.cpp.
References _global_ref_timestamp, _mavlink_timesync, _vision_position_pub, vehicle_local_position_s::dist_bottom_valid, vehicle_local_position_s::eph, vehicle_local_position_s::epv, vehicle_local_position_s::evh, vehicle_local_position_s::evv, globallocalconverter_getref(), globallocalconverter_initialized(), ORB_ID, ORB_PRIO_HIGH, orb_publish_auto(), vehicle_local_position_s::ref_alt, vehicle_local_position_s::ref_lat, vehicle_local_position_s::ref_lon, vehicle_local_position_s::ref_timestamp, MavlinkTimesync::sync_stamp(), vehicle_local_position_s::timestamp, vehicle_local_position_s::v_xy_valid, vehicle_local_position_s::v_z_valid, vehicle_local_position_s::vx, vehicle_local_position_s::vy, vehicle_local_position_s::vz, vehicle_local_position_s::x, vehicle_local_position_s::xy_global, vehicle_local_position_s::xy_valid, vehicle_local_position_s::y, vehicle_local_position_s::z, vehicle_local_position_s::z_global, and vehicle_local_position_s::z_valid.
Referenced by handle_message().
void MavlinkReceiver::handle_message_logging_ack (mavlink_message_t * msg) private
Definition at line 1609 of file mavlink_receiver.cpp.
References _mavlink, Mavlink::get_ulog_streaming(), and MavlinkULog::handle_ack().
Referenced by handle_message().
void MavlinkReceiver::handle_message_manual_control (mavlink_message_t * msg) private
Definition at line 1816 of file mavlink_receiver.cpp.
References _manual_pub, _mavlink, _mom_switch_state, _rc_pub, manual_control_setpoint_s::data_source, decode_switch_pos_n(), Mavlink::get_instance_id(), Mavlink::get_manual_input_mode_generation(), Mavlink::get_system_id(), hrt_absolute_time(), orb_advertise(), ORB_ID, ORB_PRIO_LOW, orb_publish(), orb_publish_auto(), manual_control_setpoint_s::r, RC_INPUT_RSSI_MAX, rc_input_values, manual_control_setpoint_s::timestamp, manual_control_setpoint_s::x, manual_control_setpoint_s::y, and manual_control_setpoint_s::z.
Referenced by handle_message().
void MavlinkReceiver::handle_message_named_value_float (mavlink_message_t * msg) private
Definition at line 2463 of file mavlink_receiver.cpp.
References _debug_key_value_pub, _mavlink_timesync, debug_key_value_s::key, orb_advertise(), ORB_ID, orb_publish(), MavlinkTimesync::sync_stamp(), debug_key_value_s::timestamp, and debug_key_value_s::value.
Referenced by handle_message().
void MavlinkReceiver::handle_message_obstacle_distance (mavlink_message_t * msg) private
Definition at line 1646 of file mavlink_receiver.cpp.
References _mavlink_timesync, _obstacle_distance_pub, obstacle_distance_s::distances, obstacle_distance_s::increment, obstacle_distance_s::max_distance, obstacle_distance_s::min_distance, orb_advertise(), ORB_ID, orb_publish(), obstacle_distance_s::sensor_type, MavlinkTimesync::sync_stamp(), and obstacle_distance_s::timestamp.
Referenced by handle_message().
void MavlinkReceiver::handle_message_optical_flow_rad (mavlink_message_t * msg) private
Definition at line 661 of file mavlink_receiver.cpp.
References _flow_distance_sensor_pub, _flow_pub, _mavlink_timesync, _orb_class_instance, distance_sensor_s::covariance, distance_sensor_s::current_distance, optical_flow_s::ground_distance_m, optical_flow_s::gyro_temperature, optical_flow_s::gyro_x_rate_integral, optical_flow_s::gyro_y_rate_integral, optical_flow_s::gyro_z_rate_integral, distance_sensor_s::id, optical_flow_s::integration_timespan, distance_sensor_s::max_distance, distance_sensor_s::min_distance, orb_advertise(), orb_advertise_multi(), ORB_ID, ORB_PRIO_HIGH, orb_publish(), distance_sensor_s::orientation, param_find(), param_get(), optical_flow_s::pixel_flow_x_integral, optical_flow_s::pixel_flow_y_integral, optical_flow_s::quality, rotate_3f(), optical_flow_s::sensor_id, MavlinkTimesync::sync_stamp(), optical_flow_s::time_since_last_sonar_update, optical_flow_s::timestamp, distance_sensor_s::timestamp, and distance_sensor_s::type.
Referenced by handle_message().
void MavlinkReceiver::handle_message_ping (mavlink_message_t * msg) private
Definition at line 1456 of file mavlink_receiver.cpp.
References _mavlink, _ping_pub, ping_s::component_id, ping_s::dropped_packets, Mavlink::ping_statistics_s::dropped_packets, f(), Mavlink::get_channel(), Mavlink::get_ping_statistics(), hrt_absolute_time(), hrt_abstime, Mavlink::ping_statistics_s::last_ping_seq, Mavlink::ping_statistics_s::last_ping_time, Mavlink::ping_statistics_s::last_rtt, mavlink_system, Mavlink::ping_statistics_s::max_rtt, Mavlink::ping_statistics_s::mean_rtt, Mavlink::ping_statistics_s::min_rtt, orb_advertise_multi(), ORB_ID, ORB_MULTI_MAX_INSTANCES, ORB_PRIO_DEFAULT, orb_publish(), ping_s::ping_sequence, ping_s::ping_time, ping_s::rtt_ms, ping_s::system_id, and ping_s::timestamp.
Referenced by handle_message().
void MavlinkReceiver::handle_message_play_tune (mavlink_message_t * msg) private
Definition at line 1622 of file mavlink_receiver.cpp.
References fd, mavlink_system, px4_close(), PX4_F_WRONLY, px4_open(), px4_write(), and TONEALARM0_DEVICE_PATH.
Referenced by handle_message().
void MavlinkReceiver::handle_message_radio_status (mavlink_message_t * msg) private
Definition at line 1422 of file mavlink_receiver.cpp.
References _mavlink, _telemetry_status_pub, telemetry_status_s::component_id, telemetry_status_s::fixed, Mavlink::get_channel(), Mavlink::get_rx_status(), hrt_absolute_time(), telemetry_status_s::noise, orb_advertise_multi(), ORB_ID, ORB_MULTI_MAX_INSTANCES, ORB_PRIO_HIGH, orb_publish(), telemetry_status_s::remote_noise, telemetry_status_s::remote_rssi, telemetry_status_s::rssi, telemetry_status_s::rxerrors, telemetry_status_s::system_id, telemetry_status_s::telem_time, telemetry_status_s::timestamp, telemetry_status_s::txbuf, and telemetry_status_s::type.
Referenced by handle_message().
void MavlinkReceiver::handle_message_rc_channels_override (mavlink_message_t * msg) private
Definition at line 1758 of file mavlink_receiver.cpp.
References _mavlink, _rc_pub, Mavlink::get_system_id(), hrt_absolute_time(), orb_advertise(), ORB_ID, orb_publish(), RC_INPUT_RSSI_MAX, and rc_input_values.
Referenced by handle_message().
void MavlinkReceiver::handle_message_serial_control (mavlink_message_t * msg) private
Definition at line 1582 of file mavlink_receiver.cpp.
References _mavlink, Mavlink::close_shell(), Mavlink::get_shell(), and MavlinkShell::write().
Referenced by handle_message().
void MavlinkReceiver::handle_message_set_actuator_control_target (mavlink_message_t * msg) private
Definition at line 1047 of file mavlink_receiver.cpp.
References _actuator_controls_pubs, _control_mode, _control_mode_sub, _mavlink_timesync, _offboard_control_mode_pub, actuator_controls_s::control, vehicle_control_mode_s::flag_control_offboard_enabled, hrt_absolute_time(), offboard_control_mode_s::ignore_acceleration_force, offboard_control_mode_s::ignore_attitude, offboard_control_mode_s::ignore_bodyrate, offboard_control_mode_s::ignore_position, offboard_control_mode_s::ignore_thrust, offboard_control_mode_s::ignore_velocity, mavlink_system, orb_advertise(), orb_check(), orb_copy(), ORB_ID, orb_publish(), MavlinkTimesync::sync_stamp(), offboard_control_mode_s::timestamp, and actuator_controls_s::timestamp.
Referenced by handle_message().
void MavlinkReceiver::handle_message_set_attitude_target (mavlink_message_t * msg) private
XXX add support for ignoring individual axes
Definition at line 1288 of file mavlink_receiver.cpp.
References _att_sp_pub, _control_mode, _control_mode_sub, _mavlink, _mavlink_timesync, _offboard_control_mode, _offboard_control_mode_pub, _rates_sp_pub, matrix::Matrix< Type, M, N >::copyTo(), vehicle_control_mode_s::flag_control_offboard_enabled, Mavlink::get_forward_externalsp(), offboard_control_mode_s::ignore_acceleration_force, offboard_control_mode_s::ignore_attitude, offboard_control_mode_s::ignore_bodyrate, offboard_control_mode_s::ignore_position, offboard_control_mode_s::ignore_thrust, offboard_control_mode_s::ignore_velocity, mavlink_system, offboard_control_mode, orb_advertise(), orb_check(), orb_copy(), ORB_ID, orb_publish(), vehicle_rates_setpoint_s::pitch, vehicle_attitude_setpoint_s::pitch_body, vehicle_attitude_s::q, vehicle_attitude_setpoint_s::q_d, vehicle_attitude_setpoint_s::q_d_valid, vehicle_rates_setpoint_s::roll, vehicle_attitude_setpoint_s::roll_body, MavlinkTimesync::sync_stamp(), vehicle_rates_setpoint_s::thrust, vehicle_attitude_setpoint_s::thrust, vehicle_rates_setpoint_s::timestamp, offboard_control_mode_s::timestamp, vehicle_attitude_setpoint_s::timestamp, vehicle_rates_setpoint_s::yaw, vehicle_attitude_setpoint_s::yaw_body, and vehicle_attitude_setpoint_s::yaw_sp_move_rate.
Referenced by handle_message().
void MavlinkReceiver::handle_message_set_mode (mavlink_message_t * msg) private
Definition at line 774 of file mavlink_receiver.cpp.
References _cmd_pub, vehicle_command_s::command, vehicle_command_s::confirmation, px4_custom_mode::data, vehicle_command_s::from_external, hrt_absolute_time(), px4_custom_mode::main_mode, orb_advertise_queue(), ORB_ID, orb_publish(), vehicle_command_s::param1, vehicle_command_s::param2, vehicle_command_s::param3, vehicle_command_s::source_component, vehicle_command_s::source_system, px4_custom_mode::sub_mode, vehicle_command_s::target_component, vehicle_command_s::target_system, and vehicle_command_s::timestamp.
Referenced by handle_message().
void MavlinkReceiver::handle_message_set_position_target_local_ned (mavlink_message_t * msg) private
Definition at line 868 of file mavlink_receiver.cpp.
References _control_mode, _control_mode_sub, _mavlink, _mavlink_timesync, _offboard_control_mode_pub, _pos_sp_triplet_pub, position_setpoint_s::a_x, position_setpoint_s::a_y, position_setpoint_s::a_z, position_setpoint_s::acceleration_is_force, position_setpoint_s::acceleration_valid, position_setpoint_s::alt_valid, position_setpoint_triplet_s::current, vehicle_control_mode_s::flag_control_offboard_enabled, Mavlink::get_forward_externalsp(), offboard_control_mode_s::ignore_acceleration_force, offboard_control_mode_s::ignore_alt_hold, offboard_control_mode_s::ignore_attitude, offboard_control_mode_s::ignore_bodyrate, offboard_control_mode_s::ignore_position, offboard_control_mode_s::ignore_velocity, mavlink_system, position_setpoint_triplet_s::next, orb_advertise(), orb_check(), orb_copy(), ORB_ID, orb_publish(), position_setpoint_s::position_valid, position_setpoint_triplet_s::previous, PX4_WARN, MavlinkTimesync::sync_stamp(), offboard_control_mode_s::timestamp, position_setpoint_triplet_s::timestamp, position_setpoint_s::type, position_setpoint_s::valid, position_setpoint_s::velocity_frame, position_setpoint_s::velocity_valid, position_setpoint_s::vx, position_setpoint_s::vy, position_setpoint_s::vz, position_setpoint_s::x, position_setpoint_s::y, position_setpoint_s::yaw, position_setpoint_s::yaw_valid, position_setpoint_s::yawspeed, position_setpoint_s::yawspeed_valid, and position_setpoint_s::z.
Referenced by handle_message().
void MavlinkReceiver::handle_message_trajectory_representation_waypoints (mavlink_message_t * msg) private
Definition at line 1668 of file mavlink_receiver.cpp.
References _mavlink_timesync, _trajectory_waypoint_pub, trajectory_waypoint_s::acceleration, orb_advertise(), ORB_ID, orb_publish(), trajectory_waypoint_s::point_valid, trajectory_waypoint_s::position, MavlinkTimesync::sync_stamp(), vehicle_trajectory_waypoint_s::timestamp, trajectory_waypoint_s::velocity, vehicle_trajectory_waypoint_s::waypoints, trajectory_waypoint_s::yaw, and trajectory_waypoint_s::yaw_speed.
Referenced by handle_message().
void MavlinkReceiver::handle_message_vision_position_estimate (mavlink_message_t * msg) private
Definition at line 1258 of file mavlink_receiver.cpp.
References _mavlink_timesync, _vision_attitude_pub, _vision_position_pub, matrix::Matrix< Type, M, N >::copyTo(), ORB_ID, ORB_PRIO_DEFAULT, orb_publish_auto(), vehicle_attitude_s::q, MavlinkTimesync::sync_stamp(), vehicle_local_position_s::timestamp, vehicle_attitude_s::timestamp, vehicle_local_position_s::v_xy_valid, vehicle_local_position_s::v_z_valid, vehicle_local_position_s::x, vehicle_local_position_s::xy_valid, vehicle_local_position_s::y, vehicle_local_position_s::z, and vehicle_local_position_s::z_valid.
Referenced by handle_message().
MavlinkReceiver MavlinkReceiver::operator= (const MavlinkReceiver &) private delete
void MavlinkReceiver::print_status ()
Display the mavlink status.
Definition at line 2707 of file mavlink_receiver.cpp.
void MavlinkReceiver::receive_start (pthread_t * thread, Mavlink * parent) static
Start the receiver thread.
Definition at line 2730 of file mavlink_receiver.cpp.
References pthread_attr_destroy(), pthread_attr_getschedparam(), pthread_attr_init(), pthread_attr_setschedparam(), pthread_attr_setstacksize(), pthread_create(), PX4_STACK_ADJUSTED, SCHED_PRIORITY_MAX, and start_helper().
Referenced by Mavlink::task_main().
void * MavlinkReceiver::receive_thread (void * arg) private
Receive data from UART.
Definition at line 2528 of file mavlink_receiver.cpp.
References _mavlink, _mavlink_ftp, _mavlink_log_handler, _mavlink_timesync, _mission_manager, _parameters_manager, _status, Mavlink::_task_should_exit, _telemetry_status_pub, Mavlink::boot_complete(), MavlinkMissionManager::check_active_mission(), Mavlink::count_rxbytes(), fd, Mavlink::ftp_enabled(), Mavlink::get_baudrate(), Mavlink::get_channel(), Mavlink::get_client_source_initialized(), Mavlink::get_instance_id(), Mavlink::get_mode(), Mavlink::get_protocol(), Mavlink::get_rx_status(), Mavlink::get_socket_fd(), Mavlink::get_start_time(), Mavlink::get_status(), Mavlink::get_uart_fd(), MavlinkFTP::handle_message(), MavlinkParametersManager::handle_message(), MavlinkMissionManager::handle_message(), MavlinkLogHandler::handle_message(), MavlinkTimesync::handle_message(), handle_message(), Mavlink::handle_message(), hrt_absolute_time(), hrt_abstime, hrt_elapsed_time(), Mavlink::MAVLINK_MODE_IRIDIUM, msg, orb_advertise_multi(), ORB_ID, ORB_PRIO_HIGH, orb_publish(), PX4_INFO, read(), MavlinkFTP::send(), MavlinkParametersManager::send(), MavlinkMissionManager::send(), MavlinkLogHandler::send(), SERIAL, Mavlink::set_proto_version(), TCP, telemetry_status_s::timestamp, telemetry_status_s::type, UDP, and usleep().
Referenced by start_helper().
void MavlinkReceiver::send_flight_information () private
Definition at line 419 of file mavlink_receiver.cpp.
References _actuator_armed_sub, _mavlink, actuator_armed_s::armed_time_ms, Mavlink::get_channel(), hrt_absolute_time(), orb_copy(), ORB_ID, param_find(), param_get(), PARAM_INVALID, and actuator_armed_s::timestamp.
Referenced by handle_message_command_both().
void MavlinkReceiver::send_storage_information (int storage_id) private
Definition at line 443 of file mavlink_receiver.cpp.
References _mavlink, Mavlink::get_channel(), and hrt_absolute_time().
Referenced by handle_message_command_both().
int MavlinkReceiver::set_message_interval (int msgId, float interval, int data_rate = -1) private
Set the interval at which the given message stream is published.
The rate is the number of messages per second.
Parameters
msgId the message ID of to change the interval of
interval the interval in us to send the message at
data_rate the total link data rate in bytes per second
Returns
PX4_OK on success, PX4_ERROR on fail
Definition at line 1918 of file mavlink_receiver.cpp.
References _mavlink, Mavlink::configure_stream_threadsafe(), f(), get_stream_name(), PX4_ERROR, PX4_OK, and Mavlink::set_data_rate().
Referenced by handle_message_command_both().
void * MavlinkReceiver::start_helper (void * context) static
Definition at line 2712 of file mavlink_receiver.cpp.
References MavlinkReceiver(), PX4_ERR, and receive_thread().
Referenced by receive_start().
Member Data Documentation
orb_advert_t MavlinkReceiver::_accel_pub private
Definition at line 214 of file mavlink_receiver.h.
Referenced by handle_message_hil_sensor(), handle_message_hil_state_quaternion(), and MavlinkReceiver().
int MavlinkReceiver::_actuator_armed_sub private
Definition at line 250 of file mavlink_receiver.h.
Referenced by MavlinkReceiver(), send_flight_information(), and ~MavlinkReceiver().
orb_advert_t MavlinkReceiver::_actuator_controls_pubs[4] private
Definition at line 225 of file mavlink_receiver.h.
Referenced by handle_message_set_actuator_control_target(), and MavlinkReceiver().
orb_advert_t MavlinkReceiver::_airspeed_pub private
Definition at line 217 of file mavlink_receiver.h.
Referenced by handle_message_hil_sensor(), handle_message_hil_state_quaternion(), and MavlinkReceiver().
orb_advert_t MavlinkReceiver::_att_pos_mocap_pub private
Definition at line 229 of file mavlink_receiver.h.
Referenced by handle_message_att_pos_mocap(), and MavlinkReceiver().
orb_advert_t MavlinkReceiver::_att_sp_pub private
Definition at line 226 of file mavlink_receiver.h.
Referenced by handle_message_set_attitude_target(), and MavlinkReceiver().
orb_advert_t MavlinkReceiver::_attitude_pub private
Definition at line 211 of file mavlink_receiver.h.
Referenced by handle_message_hil_state_quaternion(), and MavlinkReceiver().
orb_advert_t MavlinkReceiver::_baro_pub private
Definition at line 216 of file mavlink_receiver.h.
Referenced by handle_message_hil_sensor(), and MavlinkReceiver().
orb_advert_t MavlinkReceiver::_battery_pub private
Definition at line 218 of file mavlink_receiver.h.
Referenced by handle_message_battery_status(), handle_message_hil_sensor(), handle_message_hil_state_quaternion(), and MavlinkReceiver().
orb_advert_t MavlinkReceiver::_cmd_pub private
Definition at line 219 of file mavlink_receiver.h.
Referenced by handle_message_command_both(), handle_message_set_mode(), and MavlinkReceiver().
orb_advert_t MavlinkReceiver::_collision_report_pub private
Definition at line 242 of file mavlink_receiver.h.
Referenced by handle_message_collision(), and MavlinkReceiver().
orb_advert_t MavlinkReceiver::_command_ack_pub private
Definition at line 248 of file mavlink_receiver.h.
Referenced by acknowledge(), handle_message_command_ack(), and MavlinkReceiver().
struct vehicle_control_mode_s MavlinkReceiver::_control_mode private
Definition at line 208 of file mavlink_receiver.h.
Referenced by handle_message_set_actuator_control_target(), handle_message_set_attitude_target(), handle_message_set_position_target_local_ned(), and MavlinkReceiver().
int MavlinkReceiver::_control_mode_sub private
Definition at line 249 of file mavlink_receiver.h.
Referenced by handle_message_set_actuator_control_target(), handle_message_set_attitude_target(), handle_message_set_position_target_local_ned(), MavlinkReceiver(), and ~MavlinkReceiver().
orb_advert_t MavlinkReceiver::_debug_key_value_pub private
Definition at line 243 of file mavlink_receiver.h.
Referenced by handle_message_named_value_float(), and MavlinkReceiver().
orb_advert_t MavlinkReceiver::_debug_value_pub private
Definition at line 244 of file mavlink_receiver.h.
Referenced by handle_message_debug(), and MavlinkReceiver().
orb_advert_t MavlinkReceiver::_debug_vect_pub private
Definition at line 245 of file mavlink_receiver.h.
Referenced by handle_message_debug_vect(), and MavlinkReceiver().
orb_advert_t MavlinkReceiver::_distance_sensor_pub private
Definition at line 223 of file mavlink_receiver.h.
Referenced by handle_message_distance_sensor(), and MavlinkReceiver().
orb_advert_t MavlinkReceiver::_flow_distance_sensor_pub private
Definition at line 222 of file mavlink_receiver.h.
Referenced by handle_message_optical_flow_rad(), and MavlinkReceiver().
orb_advert_t MavlinkReceiver::_flow_pub private
Definition at line 220 of file mavlink_receiver.h.
Referenced by handle_message_hil_optical_flow(), handle_message_optical_flow_rad(), and MavlinkReceiver().
orb_advert_t MavlinkReceiver::_follow_target_pub private
Definition at line 239 of file mavlink_receiver.h.
Referenced by handle_message_follow_target(), and MavlinkReceiver().
orb_advert_t MavlinkReceiver::_global_pos_pub private
Definition at line 209 of file mavlink_receiver.h.
Referenced by handle_message_hil_state_quaternion(), and MavlinkReceiver().
uint64_t MavlinkReceiver::_global_ref_timestamp private
Definition at line 251 of file mavlink_receiver.h.
Referenced by handle_message_gps_global_origin(), handle_message_local_position_ned_cov(), and MavlinkReceiver().
orb_advert_t MavlinkReceiver::_gps_inject_data_pub private
Definition at line 247 of file mavlink_receiver.h.
Referenced by handle_message_gps_rtcm_data(), and MavlinkReceiver().
const int MavlinkReceiver::_gps_inject_data_queue_size = 6 static private
Definition at line 246 of file mavlink_receiver.h.
Referenced by handle_message_gps_rtcm_data().
orb_advert_t MavlinkReceiver::_gps_pub private
Definition at line 212 of file mavlink_receiver.h.
Referenced by handle_message_hil_gps(), and MavlinkReceiver().
orb_advert_t MavlinkReceiver::_gyro_pub private
Definition at line 213 of file mavlink_receiver.h.
Referenced by handle_message_hil_sensor(), and MavlinkReceiver().
orb_advert_t MavlinkReceiver::_hil_distance_sensor_pub private
Definition at line 221 of file mavlink_receiver.h.
Referenced by handle_message_hil_optical_flow(), and MavlinkReceiver().
int MavlinkReceiver::_hil_frames private
Definition at line 252 of file mavlink_receiver.h.
Referenced by handle_message_hil_sensor(), and MavlinkReceiver().
struct vehicle_land_detected_s MavlinkReceiver::_hil_land_detector private
Definition at line 207 of file mavlink_receiver.h.
Referenced by handle_message_hil_state_quaternion(), and MavlinkReceiver().
float MavlinkReceiver::_hil_local_alt0 private
Definition at line 255 of file mavlink_receiver.h.
Referenced by handle_message_hil_state_quaternion(), and MavlinkReceiver().
struct vehicle_local_position_s MavlinkReceiver::_hil_local_pos private
Definition at line 206 of file mavlink_receiver.h.
Referenced by handle_message_hil_state_quaternion(), and MavlinkReceiver().
bool MavlinkReceiver::_hil_local_proj_inited private
Definition at line 254 of file mavlink_receiver.h.
Referenced by handle_message_hil_state_quaternion(), and MavlinkReceiver().
struct map_projection_reference_s MavlinkReceiver::_hil_local_proj_ref private
Definition at line 256 of file mavlink_receiver.h.
Referenced by handle_message_hil_state_quaternion(), and MavlinkReceiver().
orb_advert_t MavlinkReceiver::_land_detector_pub private
Definition at line 238 of file mavlink_receiver.h.
Referenced by handle_message_hil_state_quaternion(), and MavlinkReceiver().
orb_advert_t MavlinkReceiver::_landing_target_pose_pub private
Definition at line 240 of file mavlink_receiver.h.
Referenced by handle_message_landing_target(), and MavlinkReceiver().
orb_advert_t MavlinkReceiver::_local_pos_pub private
Definition at line 210 of file mavlink_receiver.h.
Referenced by handle_message_hil_state_quaternion(), and MavlinkReceiver().
orb_advert_t MavlinkReceiver::_mag_pub private
Definition at line 215 of file mavlink_receiver.h.
Referenced by handle_message_hil_sensor(), and MavlinkReceiver().
orb_advert_t MavlinkReceiver::_manual_pub private
Definition at line 235 of file mavlink_receiver.h.
Referenced by handle_message_manual_control(), and MavlinkReceiver().
Mavlink* MavlinkReceiver::_mavlink private
Definition at line 197 of file mavlink_receiver.h.
Referenced by get_message_interval(), handle_message(), handle_message_command_both(), handle_message_heartbeat(), handle_message_logging_ack(), handle_message_manual_control(), handle_message_ping(), handle_message_radio_status(), handle_message_rc_channels_override(), handle_message_serial_control(), handle_message_set_attitude_target(), handle_message_set_position_target_local_ned(), receive_thread(), send_flight_information(), send_storage_information(), and set_message_interval().
MavlinkFTP MavlinkReceiver::_mavlink_ftp private
Definition at line 201 of file mavlink_receiver.h.
Referenced by receive_thread().
MavlinkLogHandler MavlinkReceiver::_mavlink_log_handler private
Definition at line 202 of file mavlink_receiver.h.
Referenced by receive_thread().
MavlinkTimesync MavlinkReceiver::_mavlink_timesync private
Definition at line 203 of file mavlink_receiver.h.
Referenced by handle_message_att_pos_mocap(), handle_message_attitude_quaternion_cov(), handle_message_debug(), handle_message_debug_vect(), handle_message_follow_target(), handle_message_landing_target(), handle_message_local_position_ned_cov(), handle_message_named_value_float(), handle_message_obstacle_distance(), handle_message_optical_flow_rad(), handle_message_set_actuator_control_target(), handle_message_set_attitude_target(), handle_message_set_position_target_local_ned(), handle_message_trajectory_representation_waypoints(), handle_message_vision_position_estimate(), and receive_thread().
MavlinkMissionManager MavlinkReceiver::_mission_manager private
Definition at line 199 of file mavlink_receiver.h.
Referenced by receive_thread().
uint8_t MavlinkReceiver::_mom_switch_pos[MOM_SWITCH_COUNT] private
Definition at line 262 of file mavlink_receiver.h.
Referenced by decode_switch_pos_n(), and MavlinkReceiver().
uint16_t MavlinkReceiver::_mom_switch_state private
Definition at line 263 of file mavlink_receiver.h.
Referenced by decode_switch_pos_n(), handle_message_manual_control(), and MavlinkReceiver().
orb_advert_t MavlinkReceiver::_obstacle_distance_pub private
Definition at line 236 of file mavlink_receiver.h.
Referenced by handle_message_obstacle_distance(), and MavlinkReceiver().
struct offboard_control_mode_s MavlinkReceiver::_offboard_control_mode private
Definition at line 257 of file mavlink_receiver.h.
Referenced by handle_message_set_attitude_target(), and MavlinkReceiver().
orb_advert_t MavlinkReceiver::_offboard_control_mode_pub private
Definition at line 224 of file mavlink_receiver.h.
Referenced by handle_message_set_actuator_control_target(), handle_message_set_attitude_target(), handle_message_set_position_target_local_ned(), and MavlinkReceiver().
uint64_t MavlinkReceiver::_old_timestamp private
Definition at line 253 of file mavlink_receiver.h.
Referenced by handle_message_hil_sensor(), and MavlinkReceiver().
int MavlinkReceiver::_orb_class_instance private
Definition at line 258 of file mavlink_receiver.h.
Referenced by handle_message_distance_sensor(), handle_message_hil_optical_flow(), handle_message_optical_flow_rad(), and MavlinkReceiver().
param_t MavlinkReceiver::_p_bat_crit_thr private
Definition at line 266 of file mavlink_receiver.h.
Referenced by handle_message_battery_status(), and MavlinkReceiver().
param_t MavlinkReceiver::_p_bat_emergen_thr private
Definition at line 265 of file mavlink_receiver.h.
Referenced by handle_message_battery_status(), and MavlinkReceiver().
param_t MavlinkReceiver::_p_bat_low_thr private
Definition at line 267 of file mavlink_receiver.h.
Referenced by handle_message_battery_status(), and MavlinkReceiver().
MavlinkParametersManager MavlinkReceiver::_parameters_manager private
Definition at line 200 of file mavlink_receiver.h.
Referenced by receive_thread().
orb_advert_t MavlinkReceiver::_ping_pub private
Definition at line 233 of file mavlink_receiver.h.
Referenced by handle_message_ping(), and MavlinkReceiver().
orb_advert_t MavlinkReceiver::_pos_sp_triplet_pub private
Definition at line 228 of file mavlink_receiver.h.
Referenced by handle_message_set_position_target_local_ned(), and MavlinkReceiver().
orb_advert_t MavlinkReceiver::_rates_sp_pub private
Definition at line 227 of file mavlink_receiver.h.
Referenced by handle_message_set_attitude_target(), and MavlinkReceiver().
orb_advert_t MavlinkReceiver::_rc_pub private
Definition at line 234 of file mavlink_receiver.h.
Referenced by handle_message_manual_control(), handle_message_rc_channels_override(), and MavlinkReceiver().
mavlink_status_t MavlinkReceiver::_status private
receiver status, used for mavlink_parse_char()
Definition at line 205 of file mavlink_receiver.h.
Referenced by receive_thread().
orb_advert_t MavlinkReceiver::_telemetry_status_pub private
Definition at line 232 of file mavlink_receiver.h.
Referenced by handle_message_heartbeat(), handle_message_radio_status(), MavlinkReceiver(), and receive_thread().
orb_advert_t MavlinkReceiver::_trajectory_waypoint_pub private
Definition at line 237 of file mavlink_receiver.h.
Referenced by handle_message_trajectory_representation_waypoints(), and MavlinkReceiver().
orb_advert_t MavlinkReceiver::_transponder_report_pub private
Definition at line 241 of file mavlink_receiver.h.
Referenced by handle_message_adsb_vehicle(), and MavlinkReceiver().
orb_advert_t MavlinkReceiver::_vision_attitude_pub private
Definition at line 231 of file mavlink_receiver.h.
Referenced by handle_message_attitude_quaternion_cov(), handle_message_vision_position_estimate(), and MavlinkReceiver().
orb_advert_t MavlinkReceiver::_vision_position_pub private
Definition at line 230 of file mavlink_receiver.h.
Referenced by handle_message_local_position_ned_cov(), handle_message_vision_position_estimate(), and MavlinkReceiver().
constexpr unsigned MavlinkReceiver::MOM_SWITCH_COUNT = 8 static private
Definition at line 260 of file mavlink_receiver.h.
Referenced by decode_switch_pos_n().
The documentation for this class was generated from the following files:
src/modules/mavlink/mavlink_receiver.h
src/modules/mavlink/mavlink_receiver.cpp