PX4 Firmware: src/drivers/distance_sensor/tfmini/tfmini_main.cpp File Reference
tfmini_main.cpp File Reference
#include "TFMINI.hpp"
#include <px4_platform_common/getopt.h>
Namespaces
tfmini
Local functions in support of the shell command.
Functions
int tfmini::start (const char *port, uint8_t rotation)
int tfmini::status ()
int tfmini::stop ()
Stop the driver.
int tfmini::usage ()
Prints info about the driver argument usage.
__EXPORT int tfmini_main (int argc, char *argv[])
Variables
TFMINI * tfmini::g_dev {nullptr}
Function Documentation
tfmini_main()
__EXPORT int tfmini_main (int argc, char * argv[])
Definition at line 142 of file tfmini_main.cpp.
References tfmini::start(), tfmini::status(), tfmini::stop(), TFMINI_DEFAULT_PORT, and tfmini::usage().