PX4 Firmware: sdp3x_airspeed Namespace Reference
sdp3x_airspeed Namespace Reference
Functions
int start ()
Attempt to start driver on all available I2C busses.
int start_bus (uint8_t i2c_bus)
Start the driver on a specific bus.
int stop ()
Stop the driver.
int reset ()
Reset the driver.
Variables
SDP3X * g_dev = nullptr
Function Documentation
int sdp3x_airspeed::reset ()
Reset the driver.
Definition at line 150 of file SDP3X_main.cpp.
References fd, PATH_SDP3X, PX4_ERR, PX4_ERROR, px4_ioctl(), PX4_OK, px4_open(), SENSOR_POLLRATE_DEFAULT, SENSORIOCRESET, and SENSORIOCSPOLLRATE.
Referenced by sdp3x_airspeed_main().
int sdp3x_airspeed::start ()
Attempt to start driver on all available I2C busses.
This function will return as soon as the first sensor is detected on one of the available busses or if no sensors are detected.
Definition at line 59 of file SDP3X_main.cpp.
References i2c_bus_options, PX4_ERROR, PX4_OK, and start_bus().
Referenced by sdp3x_airspeed_main().
int sdp3x_airspeed::start_bus (uint8_t i2c_bus)
Start the driver on a specific bus.
This function call only returns once the driver is up and running or failed to detect the sensor.
Definition at line 77 of file SDP3X_main.cpp.
References fd, g_dev, I2C_ADDRESS_1_SDP3X, I2C_ADDRESS_2_SDP3X, Airspeed::init(), PATH_SDP3X, PX4_ERR, PX4_ERROR, px4_ioctl(), PX4_OK, px4_open(), PX4_WARN, SENSOR_POLLRATE_DEFAULT, and SENSORIOCSPOLLRATE.
Referenced by sdp3x_airspeed_main(), and start().
int sdp3x_airspeed::stop ()
Stop the driver.
Definition at line 135 of file SDP3X_main.cpp.
References g_dev, PX4_ERR, PX4_ERROR, and PX4_OK.
Referenced by sdp3x_airspeed_main().
Variable Documentation
SDP3X* sdp3x_airspeed::g_dev = nullptr
Definition at line 43 of file SDP3X_main.cpp.
Referenced by start_bus(), and stop().