PX4 Firmware: px4::logger::LogWriterFile Class Reference
px4::logger::LogWriterFile Class Reference
Writes logging data to a file.
#include <log_writer_file.h>
Public Member Functions
LogWriterFile (size_t buffer_size)
~LogWriterFile ()
bool init ()
int thread_start ()
start the thread
void thread_stop ()
void start_log (const char *filename)
void stop_log ()
bool is_started () const
int write_message (void *ptr, size_t size, uint64_t dropout_start=0)
void lock ()
void unlock ()
void notify ()
size_t get_total_written () const
size_t get_buffer_size () const
size_t get_buffer_fill_count () const
void set_need_reliable_transfer (bool need_reliable)
bool need_reliable_transfer () const
pthread_t thread_id () const
Private Member Functions
void run ()
size_t get_read_ptr (void **ptr, bool *is_part)
void mark_read (size_t n)
int hardfault_store_filename (const char *log_file)
permanently store the ulog file name for the hardfault crash handler, so that it can append crash logs to the last ulog file.
int write (void *ptr, size_t size, uint64_t dropout_start)
write w/o waiting/blocking
void write_no_check (void *ptr, size_t size)
Write to the buffer but assuming there is enough space.
Static Private Member Functions
static void * run_helper (void *)
Private Attributes
int _fd = -1
uint8_t * _buffer = nullptr
const size_t _buffer_size
size_t _head = 0
next position to write to
size_t _count = 0
number of bytes in _buffer to be written
size_t _total_written = 0
bool _should_run = false
bool _running = false
bool _exit_thread = false
bool _need_reliable_transfer = false
pthread_mutex_t _mtx
pthread_cond_t _cv
perf_counter_t _perf_write
perf_counter_t _perf_fsync
pthread_t _thread = 0
Static Private Attributes
static constexpr size_t _min_write_chunk = 4096
Detailed Description
Writes logging data to a file.
Definition at line 51 of file log_writer_file.h.
Constructor & Destructor Documentation
px4::logger::LogWriterFile::LogWriterFile (size_t buffer_size)
Definition at line 55 of file log_writer_file.cpp.
References _cv, _mtx, _perf_fsync, _perf_write, PC_ELAPSED, perf_alloc, pthread_cond_init(), and pthread_mutex_init().
px4::logger::LogWriterFile::~LogWriterFile ()
Definition at line 72 of file log_writer_file.cpp.
References _buffer, _cv, _fd, _mtx, _perf_fsync, _perf_write, perf_free(), and pthread_mutex_destroy().
Member Function Documentation
size_t px4::logger::LogWriterFile::get_buffer_fill_count () const inline
Definition at line 101 of file log_writer_file.h.
References _count.
Referenced by px4::logger::LogWriter::get_buffer_fill_count_file().
size_t px4::logger::LogWriterFile::get_buffer_size () const inline
Definition at line 96 of file log_writer_file.h.
References _buffer_size.
Referenced by px4::logger::LogWriter::get_buffer_size_file().
size_t px4::logger::LogWriterFile::get_read_ptr (void ** ptr, bool * is_part) private
Definition at line 390 of file log_writer_file.cpp.
References _buffer, _buffer_size, _count, and _head.
Referenced by run(), and thread_id().
size_t px4::logger::LogWriterFile::get_total_written () const inline
Definition at line 91 of file log_writer_file.h.
References _total_written.
Referenced by px4::logger::LogWriter::get_total_written_file().
int px4::logger::LogWriterFile::hardfault_store_filename (const char * log_file) private
permanently store the ulog file name for the hardfault crash handler, so that it can append crash logs to the last ulog file.
Parameters
log_file path to the log file
Returns
0 on success, <0 errno otherwise
Definition at line 131 of file log_writer_file.cpp.
References fd, HARDFAULT_MAX_ULOG_FILE_LEN, HARDFAULT_ULOG_PATH, PX4_ERR, and write().
Referenced by mark_read(), and start_log().
bool px4::logger::LogWriterFile::init ()
Definition at line 67 of file log_writer_file.cpp.
Referenced by px4::logger::LogWriter::init().
bool px4::logger::LogWriterFile::is_started () const inline
Definition at line 71 of file log_writer_file.h.
References _should_run, and write_message().
Referenced by px4::logger::LogWriter::is_started(), and write().
void px4::logger::LogWriterFile::lock () inline
Definition at line 76 of file log_writer_file.h.
References _mtx, and pthread_mutex_lock().
Referenced by px4::logger::LogWriter::lock(), and write_message().
void px4::logger::LogWriterFile::mark_read (size_t n) inline private
Definition at line 125 of file log_writer_file.h.
References _count, hardfault_store_filename(), write(), and write_no_check().
Referenced by run().
bool px4::logger::LogWriterFile::need_reliable_transfer () const inline
Definition at line 111 of file log_writer_file.h.
References _need_reliable_transfer.
Referenced by px4::logger::LogWriter::need_reliable_transfer().
void px4::logger::LogWriterFile::notify () inline
Definition at line 86 of file log_writer_file.h.
References _cv.
Referenced by px4::logger::LogWriter::notify(), start_log(), stop_log(), thread_stop(), and write_message().
void px4::logger::LogWriterFile::run () private
Definition at line 212 of file log_writer_file.cpp.
References _count, _cv, _exit_thread, _fd, _head, _min_write_chunk, _mtx, _perf_fsync, _perf_write, _running, _should_run, _total_written, fsync(), get_read_ptr(), hrt_absolute_time(), hrt_abstime, mark_read(), perf_begin(), perf_end(), pthread_cond_wait(), pthread_mutex_lock(), pthread_mutex_unlock(), PX4_INFO, PX4_WARN, start(), and write().
Referenced by run_helper(), and thread_id().
void * px4::logger::LogWriterFile::run_helper (void * context) static private
Definition at line 204 of file log_writer_file.cpp.
References run().
Referenced by thread_id(), and thread_start().
void px4::logger::LogWriterFile::set_need_reliable_transfer (bool need_reliable) inline
Definition at line 106 of file log_writer_file.h.
References _need_reliable_transfer.
Referenced by px4::logger::LogWriter::set_need_reliable_transfer().
void px4::logger::LogWriterFile::start_log (const char * filename)
Definition at line 88 of file log_writer_file.cpp.
References _buffer, _buffer_size, _count, _fd, _head, _running, _should_run, _total_written, hardfault_store_filename(), notify(), PX4_ERR, and PX4_INFO.
Referenced by px4::logger::LogWriter::start_log_file().
void px4::logger::LogWriterFile::stop_log ()
Definition at line 163 of file log_writer_file.cpp.
References _should_run, and notify().
Referenced by px4::logger::LogWriter::stop_log_file().
pthread_t px4::logger::LogWriterFile::thread_id () const inline
Definition at line 116 of file log_writer_file.h.
References _thread, get_read_ptr(), run(), and run_helper().
Referenced by px4::logger::LogWriter::thread_id_file().
int px4::logger::LogWriterFile::thread_start ()
start the thread
Returns
0 on success, error number otherwise (
See also
pthread_create)
Definition at line 169 of file log_writer_file.cpp.
References _thread, pthread_attr_destroy(), pthread_attr_init(), pthread_attr_setschedparam(), pthread_attr_setstacksize(), pthread_create(), PX4_STACK_ADJUSTED, and run_helper().
Referenced by px4::logger::LogWriter::init().
void px4::logger::LogWriterFile::thread_stop ()
Definition at line 187 of file log_writer_file.cpp.
References _exit_thread, _should_run, _thread, notify(), pthread_join(), and PX4_WARN.
Referenced by px4::logger::LogWriter::thread_stop().
void px4::logger::LogWriterFile::unlock () inline
Definition at line 81 of file log_writer_file.h.
References _mtx, and pthread_mutex_unlock().
Referenced by px4::logger::LogWriter::unlock(), and write_message().
int px4::logger::LogWriterFile::write (void * ptr, size_t size, uint64_t dropout_start) private
write w/o waiting/blocking
Definition at line 338 of file log_writer_file.cpp.
References _buffer_size, _count, ulog_message_dropout_s::duration, hrt_elapsed_time(), is_started(), and write_no_check().
Referenced by hardfault_store_filename(), mark_read(), run(), and write_message().
int px4::logger::LogWriterFile::write_message (void * ptr, size_t size, uint64_t dropout_start = 0)
See also
LogWriter::write_message()
Definition at line 320 of file log_writer_file.cpp.
References _need_reliable_transfer, lock(), notify(), unlock(), usleep(), and write().
Referenced by is_started(), and px4::logger::LogWriter::write_message().
void px4::logger::LogWriterFile::write_no_check (void * ptr, size_t size) inline private
Write to the buffer but assuming there is enough space.
Definition at line 368 of file log_writer_file.cpp.
References _buffer, _buffer_size, _count, and _head.
Referenced by mark_read(), and write().
Member Data Documentation
uint8_t* px4::logger::LogWriterFile::_buffer = nullptr private
Definition at line 152 of file log_writer_file.h.
Referenced by get_read_ptr(), start_log(), write_no_check(), and ~LogWriterFile().
const size_t px4::logger::LogWriterFile::_buffer_size private
Definition at line 153 of file log_writer_file.h.
Referenced by get_buffer_size(), get_read_ptr(), start_log(), write(), and write_no_check().
size_t px4::logger::LogWriterFile::_count = 0 private
number of bytes in _buffer to be written
Definition at line 155 of file log_writer_file.h.
Referenced by get_buffer_fill_count(), get_read_ptr(), mark_read(), run(), start_log(), write(), and write_no_check().
pthread_cond_t px4::logger::LogWriterFile::_cv private
Definition at line 162 of file log_writer_file.h.
Referenced by LogWriterFile(), notify(), run(), and ~LogWriterFile().
bool px4::logger::LogWriterFile::_exit_thread = false private
Definition at line 159 of file log_writer_file.h.
Referenced by run(), and thread_stop().
int px4::logger::LogWriterFile::_fd = -1 private
Definition at line 151 of file log_writer_file.h.
Referenced by run(), start_log(), and ~LogWriterFile().
size_t px4::logger::LogWriterFile::_head = 0 private
next position to write to
Definition at line 154 of file log_writer_file.h.
Referenced by get_read_ptr(), run(), start_log(), and write_no_check().
constexpr size_t px4::logger::LogWriterFile::_min_write_chunk = 4096 static private
Definition at line 149 of file log_writer_file.h.
Referenced by run().
pthread_mutex_t px4::logger::LogWriterFile::_mtx private
Definition at line 161 of file log_writer_file.h.
Referenced by lock(), LogWriterFile(), run(), unlock(), and ~LogWriterFile().
bool px4::logger::LogWriterFile::_need_reliable_transfer = false private
Definition at line 160 of file log_writer_file.h.
Referenced by need_reliable_transfer(), set_need_reliable_transfer(), and write_message().
perf_counter_t px4::logger::LogWriterFile::_perf_fsync private
Definition at line 164 of file log_writer_file.h.
Referenced by LogWriterFile(), run(), and ~LogWriterFile().
perf_counter_t px4::logger::LogWriterFile::_perf_write private
Definition at line 163 of file log_writer_file.h.
Referenced by LogWriterFile(), run(), and ~LogWriterFile().
bool px4::logger::LogWriterFile::_running = false private
Definition at line 158 of file log_writer_file.h.
Referenced by run(), and start_log().
bool px4::logger::LogWriterFile::_should_run = false private
Definition at line 157 of file log_writer_file.h.
Referenced by is_started(), run(), start_log(), stop_log(), and thread_stop().
pthread_t px4::logger::LogWriterFile::_thread = 0 private
Definition at line 165 of file log_writer_file.h.
Referenced by thread_id(), thread_start(), and thread_stop().
size_t px4::logger::LogWriterFile::_total_written = 0 private
Definition at line 156 of file log_writer_file.h.
Referenced by get_total_written(), run(), and start_log().
The documentation for this class was generated from the following files:
src/modules/logger/log_writer_file.h
src/modules/logger/log_writer_file.cpp