PX4 Firmware: ControlMathTest Class Reference
ControlMathTest Class Reference
Public Member Functions
virtual bool run_tests ()
Override to run your unit tests.
Public Member Functions inherited from UnitTest
UnitTest ()=default
virtual ~UnitTest ()=default
void print_results ()
Prints results from running of unit tests.
Private Member Functions
bool testThrAttMapping ()
bool testPrioritizeVector ()
bool crossSphereLineTest ()
Additional Inherited Members
Protected Member Functions inherited from UnitTest
virtual void _init (void)
Run before each unit test. Override to provide custom behavior.
virtual void _cleanup (void)
Run after each unit test. Override to provide custom behavior.
void _print_assert (const char *msg, const char *test, const char *file, int line)
void _print_compare (const char *msg, const char *v1_text, int v1, const char *v2_text, int v2, const char *file, int line)
Protected Attributes inherited from UnitTest
int _tests_run {0}
The number of individual unit tests run.
int _tests_failed {0}
The number of unit tests which failed.
int _tests_passed {0}
The number of unit tests which passed.
int _assertions {0}
Total number of assertions tested by all unit tests.
Detailed Description
Definition at line 6 of file test_controlmath.cpp.
Member Function Documentation
bool ControlMathTest::crossSphereLineTest () private
Definition at line 107 of file test_controlmath.cpp.
References ControlMath::cross_sphere_line(), f(), PX4_WARN, test_controlmath(), ut_assert_false, ut_assert_true, ut_compare_float, and ut_declare_test_c.
Referenced by run_tests().
bool ControlMathTest::run_tests () virtual
Override to run your unit tests.
Unit tests should be called using ut_run_test macro.
Returns
true: all unit tests succeeded, false: one or more unit tests failed
Implements UnitTest.
Definition at line 17 of file test_controlmath.cpp.
References UnitTest::_tests_failed, crossSphereLineTest(), testPrioritizeVector(), testThrAttMapping(), and ut_run_test.
bool ControlMathTest::testPrioritizeVector () private
Definition at line 67 of file test_controlmath.cpp.
References ControlMath::constrainXY(), f(), max(), ut_assert_true, and matrix::Matrix< Type, M, N >::zero().
Referenced by run_tests().
bool ControlMathTest::testThrAttMapping () private
Definition at line 26 of file test_controlmath.cpp.
References f(), M_PI_F, vehicle_attitude_setpoint_s::pitch_body, vehicle_attitude_setpoint_s::roll_body, vehicle_attitude_setpoint_s::thrust, ControlMath::thrustToAttitude(), ut_assert_true, and vehicle_attitude_setpoint_s::yaw_body.
Referenced by run_tests().
The documentation for this class was generated from the following file:
src/systemcmds/tests/test_controlmath.cpp