PX4 Firmware: src/drivers/differential_pressure/sdp3x/SDP3X_main.cpp File Reference
SDP3X_main.cpp File Reference
#include "SDP3X.hpp"
#include <px4_getopt.h>
Namespaces
sdp3x_airspeed
Functions
__EXPORT int sdp3x_airspeed_main (int argc, char *argv[])
int sdp3x_airspeed::start ()
Attempt to start driver on all available I2C busses.
int sdp3x_airspeed::start_bus (uint8_t i2c_bus)
Start the driver on a specific bus.
int sdp3x_airspeed::stop ()
Stop the driver.
int sdp3x_airspeed::reset ()
Reset the driver.
static void sdp3x_airspeed_usage ()
Variables
SDP3X * sdp3x_airspeed::g_dev = nullptr
Function Documentation
int sdp3x_airspeed_main (int argc, char * argv[])
Definition at line 187 of file SDP3X_main.cpp.
References px4_getopt(), PX4_I2C_BUS_DEFAULT, sdp3x_airspeed::reset(), sdp3x_airspeed_usage(), sdp3x_airspeed::start(), sdp3x_airspeed::start_bus(), and sdp3x_airspeed::stop().
static void sdp3x_airspeed_usage () static
Definition at line 176 of file SDP3X_main.cpp.
References PX4_I2C_BUS_DEFAULT, and PX4_INFO.
Referenced by sdp3x_airspeed_main().