PX4 Firmware: src/lib/parameters/flashparams/flashparams.h File Reference
flashparams.h File Reference
#include <stdint.h>
#include <stdbool.h>
#include <sys/types.h>
#include "systemlib/uthash/utarray.h"
Functions
__EXPORT int param_set_external (param_t param, const void *val, bool mark_saved, bool notify_changes)
__EXPORT const void * param_get_value_ptr_external (param_t param)
__EXPORT int flash_param_save (bool only_unsaved)
__EXPORT int flash_param_load ()
__EXPORT int flash_param_import ()
Variables
__BEGIN_DECLS __EXPORT UT_array * param_values
flexible array holding modified parameter values
Function Documentation
flash_param_import()
__EXPORT int flash_param_import ()
Definition at line 369 of file flashparams.cpp.
References param_import_internal().
Referenced by param_import().
flash_param_load()
__EXPORT int flash_param_load ()
Definition at line 363 of file flashparams.cpp.
References param_import_internal(), and param_reset_all().
Referenced by param_load_default().
flash_param_save()
__EXPORT int flash_param_save (bool only_unsaved)
Definition at line 358 of file flashparams.cpp.
References param_export_internal().
param_get_value_ptr_external()
__EXPORT const void* param_get_value_ptr_external (param_t param)
Referenced by param_export_internal(), and param_set_internal().
param_set_external()
__EXPORT int param_set_external (param_t param, const void * val, bool mark_saved, bool notify_changes)
Referenced by param_import_callback(), and param_set_internal().
Variable Documentation
param_values
__BEGIN_DECLS __EXPORT UT_array* param_values
flexible array holding modified parameter values
Definition at line 144 of file parameters.cpp.
Referenced by param_export(), param_export_internal(), param_find_changed(), param_print_status(), param_reset(), param_reset_all_internal(), and param_set_internal().