PX4 Firmware: RestartRequestHandler Class Reference
RestartRequestHandler Class Reference
Private Member Functions
bool handleRestartRequest (uavcan::NodeID request_source) override
bool handleRestartRequest (uavcan::NodeID request_source) override
Detailed Description
Definition at line 289 of file uavcanesc_main.cpp.
Member Function Documentation
bool RestartRequestHandler::handleRestartRequest (uavcan::NodeID request_source) inline override private
Definition at line 291 of file uavcanesc_main.cpp.
References px4_systemreset(), restart_request_handler, and usleep().
bool RestartRequestHandler::handleRestartRequest (uavcan::NodeID request_source) inline override private
Definition at line 318 of file uavcannode_main.cpp.
References UavcanNode::_instance, UavcanNode::_node, UavcanNode::_node_mutex, UavcanNode::_poll_fds, UavcanNode::_poll_fds_num, UavcanNode::_task_should_exit, UavcanNode::_time_sync_slave, UavcanNode::add_poll_fd(), errx, fd, file, UavcanNode::get_node(), init_indication_controller(), init_sim_controller(), UavcanNode::ioctl(), device::CDev::lock(), UavcanNode::node_spin_once(), OK, device::CDev::open(), device::CDev::poll(), UavcanNode::PollTimeoutMs, UavcanNode::print_info(), pthread_mutex_lock(), pthread_mutex_unlock(), PX4_ERR, px4_systemreset(), resources, restart_request_handler, UavcanNode::run(), UavcanNode::teardown(), UAVCAN_NUM_POLL_FDS, device::CDev::unlock(), usleep(), and warnx.
The documentation for this class was generated from the following files:
src/modules/uavcanesc/uavcanesc_main.cpp
src/modules/uavcannode/uavcannode_main.cpp