PX4 Firmware: GroundRoverPositionControl Class Reference
GroundRoverPositionControl Class Reference
#include <GroundRoverPositionControl.hpp>
Public Member Functions
GroundRoverPositionControl ()
~GroundRoverPositionControl ()
GroundRoverPositionControl (const GroundRoverPositionControl &)=delete
GroundRoverPositionControl operator= (const GroundRoverPositionControl &other)=delete
bool task_running ()
Task status.
Static Public Member Functions
static int start ()
Start the sensors task.
Private Types
enum UGV_POSCTRL_MODE { UGV_POSCTRL_MODE_AUTO, UGV_POSCTRL_MODE_OTHER }
Private Member Functions
int parameters_update ()
Update our local parameter cache.
void manual_control_setpoint_poll ()
void position_setpoint_triplet_poll ()
void vehicle_control_mode_poll ()
void gnd_pos_ctrl_status_publish ()
Publish navigation capabilities.
bool control_position (const matrix::Vector2f &global_pos, const matrix::Vector3f &ground_speed, const position_setpoint_triplet_s &_pos_sp_triplet)
Control position.
void task_main ()
Main sensor collection task.
Static Private Member Functions
static int task_main_trampoline (int argc, char *argv[])
Shim for calling task_main from task_create.
Private Attributes
orb_advert_t _attitude_sp_pub {nullptr}
attitude setpoint
orb_advert_t _gnd_pos_ctrl_status_pub {nullptr}
navigation capabilities publication
bool _task_should_exit {false}
if true, sensor task should exit
bool _task_running {false}
if true, task is running in its mainloop
int _control_mode_sub {-1}
control mode subscription
int _global_pos_sub {-1}
int _manual_control_sub {-1}
notification of manual control updates
int _params_sub {-1}
notification of parameter updates
int _pos_sp_triplet_sub {-1}
fw_pos_ctrl_status_s _gnd_pos_ctrl_status {}
navigation capabilities
manual_control_setpoint_s _manual {}
r/c channel data
position_setpoint_triplet_s _pos_sp_triplet {}
triplet of mission items
vehicle_attitude_setpoint_s _att_sp {}
vehicle attitude setpoint
vehicle_control_mode_s _control_mode {}
control mode
vehicle_global_position_s _global_pos {}
global vehicle position
Subscription< vehicle_attitude_s > _sub_attitude
Subscription< sensor_bias_s > _sub_sensors
perf_counter_t _loop_perf
loop performance counter
hrt_abstime _control_position_last_called {0}
last call of control_position
PID_t _speed_ctrl {}
uint8_t _pos_reset_counter {0}
ECL_L1_Pos_Controller _gnd_control
enum GroundRoverPositionControl::UGV_POSCTRL_MODE UGV_POSCTRL_MODE_OTHER
used to check the mode in the last control loop iteration. Use to check if the last iteration was in the same mode.
struct {
float l1_period
float l1_damping
float l1_distance
float gndspeed_trim
float gndspeed_max
int32_t speed_control_mode
float speed_p
float speed_i
float speed_d
float speed_imax
float throttle_speed_scaler
float throttle_min
float throttle_max
float throttle_cruise
float throttle_slew_max
} _parameters
local copies of interesting parameters
struct {
param_t l1_period
param_t l1_damping
param_t l1_distance
param_t gndspeed_trim
param_t gndspeed_max
param_t speed_control_mode
param_t speed_p
param_t speed_i
param_t speed_d
param_t speed_imax
param_t throttle_speed_scaler
param_t throttle_min
param_t throttle_max
param_t throttle_cruise
param_t throttle_slew_max
} _parameter_handles
handles for interesting parameters
Detailed Description
Definition at line 73 of file GroundRoverPositionControl.hpp.
Member Enumeration Documentation
enum GroundRoverPositionControl::UGV_POSCTRL_MODE private
Enumerator
UGV_POSCTRL_MODE_AUTO
UGV_POSCTRL_MODE_OTHER
Definition at line 131 of file GroundRoverPositionControl.hpp.
Constructor & Destructor Documentation
GroundRoverPositionControl::GroundRoverPositionControl ()
Definition at line 66 of file GroundRoverPositionControl.cpp.
References _parameter_handles, param_find(), and parameters_update().
Referenced by task_main_trampoline().
GroundRoverPositionControl::~GroundRoverPositionControl ()
Definition at line 94 of file GroundRoverPositionControl.cpp.
References _control_task, _task_should_exit, gnd_control::g_control, px4_task_delete(), and usleep().
GroundRoverPositionControl::GroundRoverPositionControl (const GroundRoverPositionControl &) delete
Member Function Documentation
bool GroundRoverPositionControl::control_position (const matrix::Vector2f & global_pos, const matrix::Vector3f & ground_speed, const position_setpoint_triplet_s & _pos_sp_triplet) private
Control position.
Definition at line 208 of file GroundRoverPositionControl.cpp.
References _att_sp, _control_mode, _control_position_last_called, _gnd_control, _parameters, _pos_sp_triplet, _speed_ctrl, _sub_attitude, _sub_sensors, sensor_bias_s::accel_x, ECL_L1_Pos_Controller::circle_mode(), math::constrain(), position_setpoint_s::cruising_speed, position_setpoint_s::cruising_throttle, position_setpoint_triplet_s::current, dt, f(), vehicle_control_mode_s::flag_control_auto_enabled, vehicle_attitude_setpoint_s::fw_control_yaw, uORB::Subscription< T >::get(), ECL_L1_Pos_Controller::get_roll_setpoint(), hrt_absolute_time(), hrt_elapsed_time(), position_setpoint_s::lat, position_setpoint_s::loiter_direction, position_setpoint_s::loiter_radius, position_setpoint_s::lon, ECL_L1_Pos_Controller::nav_bearing(), ECL_L1_Pos_Controller::navigate_loiter(), ECL_L1_Pos_Controller::navigate_waypoints(), pid_calculate(), vehicle_attitude_setpoint_s::pitch_body, position_setpoint_triplet_s::previous, vehicle_attitude_s::q, vehicle_attitude_setpoint_s::roll_body, vehicle_attitude_setpoint_s::thrust, position_setpoint_s::type, UGV_POSCTRL_MODE_AUTO, UGV_POSCTRL_MODE_OTHER, position_setpoint_s::valid, vehicle_attitude_setpoint_s::yaw_body, and vehicle_attitude_setpoint_s::yaw_reset_integral.
Referenced by task_main().
void GroundRoverPositionControl::gnd_pos_ctrl_status_publish () private
Publish navigation capabilities.
Definition at line 195 of file GroundRoverPositionControl.cpp.
References _gnd_pos_ctrl_status, _gnd_pos_ctrl_status_pub, hrt_absolute_time(), orb_advertise(), ORB_ID, orb_publish(), and fw_pos_ctrl_status_s::timestamp.
Referenced by parameters_update(), and task_main().
void GroundRoverPositionControl::manual_control_setpoint_poll () private
Definition at line 174 of file GroundRoverPositionControl.cpp.
References _manual, _manual_control_sub, orb_check(), orb_copy(), and ORB_ID.
Referenced by task_main().
GroundRoverPositionControl GroundRoverPositionControl::operator= (const GroundRoverPositionControl & other) delete
int GroundRoverPositionControl::parameters_update () private
Update our local parameter cache.
Definition at line 120 of file GroundRoverPositionControl.cpp.
References _gnd_control, _gnd_pos_ctrl_status, _parameter_handles, _parameters, _speed_ctrl, f(), gnd_pos_ctrl_status_publish(), fw_pos_ctrl_status_s::landing_flare_length, fw_pos_ctrl_status_s::landing_horizontal_slope_displacement, fw_pos_ctrl_status_s::landing_slope_angle_rad, OK, param_get(), pid_init(), PID_MODE_DERIVATIV_CALC, pid_set_parameters(), math::radians(), ECL_L1_Pos_Controller::set_l1_damping(), ECL_L1_Pos_Controller::set_l1_period(), and ECL_L1_Pos_Controller::set_l1_roll_limit().
Referenced by GroundRoverPositionControl(), and task_main().
void GroundRoverPositionControl::position_setpoint_triplet_poll () private
Definition at line 185 of file GroundRoverPositionControl.cpp.
References _pos_sp_triplet, _pos_sp_triplet_sub, orb_check(), orb_copy(), and ORB_ID.
Referenced by task_main().
int GroundRoverPositionControl::start () static
Start the sensors task.
Returns
OK on success.
Definition at line 500 of file GroundRoverPositionControl.cpp.
References _control_task, OK, px4_task_spawn_cmd(), SCHED_DEFAULT, SCHED_PRIORITY_POSITION_CONTROL, task_main_trampoline(), and warn.
Referenced by gnd_pos_control_main().
void GroundRoverPositionControl::task_main () private
Main sensor collection task.
Definition at line 330 of file GroundRoverPositionControl.cpp.
References _att_sp, _attitude_sp_pub, _control_mode, _control_mode_sub, _control_task, _global_pos, _global_pos_sub, _gnd_control, _gnd_pos_ctrl_status, _loop_perf, _manual_control_sub, _parameters, _params_sub, _pos_reset_counter, _pos_sp_triplet, _pos_sp_triplet_sub, _sub_attitude, _sub_sensors, _task_running, _task_should_exit, control_position(), ECL_L1_Pos_Controller::crosstrack_error(), position_setpoint_triplet_s::current, vehicle_control_mode_s::flag_control_acceleration_enabled, vehicle_control_mode_s::flag_control_altitude_enabled, vehicle_control_mode_s::flag_control_manual_enabled, vehicle_control_mode_s::flag_control_offboard_enabled, vehicle_control_mode_s::flag_control_position_enabled, vehicle_control_mode_s::flag_control_velocity_enabled, get_distance_to_next_waypoint(), ECL_L1_Pos_Controller::get_roll_setpoint(), gnd_pos_ctrl_status_publish(), hrt_absolute_time(), hrt_elapsed_time(), vehicle_global_position_s::lat, position_setpoint_s::lat, vehicle_global_position_s::lat_lon_reset_counter, vehicle_global_position_s::lon, position_setpoint_s::lon, manual_control_setpoint_poll(), fw_pos_ctrl_status_s::nav_bearing, ECL_L1_Pos_Controller::nav_bearing(), fw_pos_ctrl_status_s::nav_pitch, fw_pos_ctrl_status_s::nav_roll, orb_advertise(), orb_copy(), ORB_ID, orb_publish(), orb_set_interval(), orb_subscribe(), parameters_update(), perf_begin(), perf_end(), vehicle_attitude_setpoint_s::pitch_body, position_setpoint_triplet_poll(), px4_poll(), vehicle_attitude_setpoint_s::q_d, vehicle_attitude_setpoint_s::q_d_valid, vehicle_attitude_setpoint_s::roll_body, fw_pos_ctrl_status_s::target_bearing, ECL_L1_Pos_Controller::target_bearing(), fw_pos_ctrl_status_s::timestamp, vehicle_attitude_setpoint_s::timestamp, fw_pos_ctrl_status_s::turn_distance, uORB::Subscription< T >::update(), vehicle_control_mode_poll(), vehicle_global_position_s::vel_d, vehicle_global_position_s::vel_e, vehicle_global_position_s::vel_n, warn, warnx, fw_pos_ctrl_status_s::wp_dist, fw_pos_ctrl_status_s::xtrack_error, and vehicle_attitude_setpoint_s::yaw_body.
Referenced by task_main_trampoline().
int GroundRoverPositionControl::task_main_trampoline (int argc, char * argv[]) static private
Shim for calling task_main from task_create.
Definition at line 483 of file GroundRoverPositionControl.cpp.
References gnd_control::g_control, GroundRoverPositionControl(), task_main(), and warnx.
Referenced by start().
bool GroundRoverPositionControl::task_running () inline
Task status.
Returns
true if the mainloop is running
Definition at line 93 of file GroundRoverPositionControl.hpp.
References _task_running.
Referenced by gnd_pos_control_main().
void GroundRoverPositionControl::vehicle_control_mode_poll () private
Definition at line 163 of file GroundRoverPositionControl.cpp.
References _control_mode, _control_mode_sub, orb_check(), orb_copy(), and ORB_ID.
Referenced by task_main().
Member Data Documentation
vehicle_attitude_setpoint_s GroundRoverPositionControl::_att_sp {} private
vehicle attitude setpoint
Definition at line 111 of file GroundRoverPositionControl.hpp.
Referenced by control_position(), and task_main().
orb_advert_t GroundRoverPositionControl::_attitude_sp_pub {nullptr} private
attitude setpoint
Definition at line 96 of file GroundRoverPositionControl.hpp.
Referenced by task_main().
vehicle_control_mode_s GroundRoverPositionControl::_control_mode {} private
control mode
Definition at line 112 of file GroundRoverPositionControl.hpp.
Referenced by control_position(), task_main(), and vehicle_control_mode_poll().
int GroundRoverPositionControl::_control_mode_sub {-1} private
control mode subscription
Definition at line 102 of file GroundRoverPositionControl.hpp.
Referenced by task_main(), and vehicle_control_mode_poll().
hrt_abstime GroundRoverPositionControl::_control_position_last_called {0} private
last call of control_position
Definition at line 120 of file GroundRoverPositionControl.hpp.
Referenced by control_position().
vehicle_global_position_s GroundRoverPositionControl::_global_pos {} private
global vehicle position
Definition at line 113 of file GroundRoverPositionControl.hpp.
Referenced by task_main().
int GroundRoverPositionControl::_global_pos_sub {-1} private
Definition at line 103 of file GroundRoverPositionControl.hpp.
Referenced by task_main().
ECL_L1_Pos_Controller GroundRoverPositionControl::_gnd_control private
Definition at line 129 of file GroundRoverPositionControl.hpp.
Referenced by control_position(), parameters_update(), and task_main().
fw_pos_ctrl_status_s GroundRoverPositionControl::_gnd_pos_ctrl_status {} private
navigation capabilities
Definition at line 108 of file GroundRoverPositionControl.hpp.
Referenced by gnd_pos_ctrl_status_publish(), parameters_update(), and task_main().
orb_advert_t GroundRoverPositionControl::_gnd_pos_ctrl_status_pub {nullptr} private
navigation capabilities publication
Definition at line 97 of file GroundRoverPositionControl.hpp.
Referenced by gnd_pos_ctrl_status_publish().
perf_counter_t GroundRoverPositionControl::_loop_perf private
loop performance counter
Definition at line 118 of file GroundRoverPositionControl.hpp.
Referenced by task_main().
manual_control_setpoint_s GroundRoverPositionControl::_manual {} private
r/c channel data
Definition at line 109 of file GroundRoverPositionControl.hpp.
Referenced by manual_control_setpoint_poll().
int GroundRoverPositionControl::_manual_control_sub {-1} private
notification of manual control updates
Definition at line 104 of file GroundRoverPositionControl.hpp.
Referenced by manual_control_setpoint_poll(), and task_main().
struct { ... } GroundRoverPositionControl::_parameter_handles
handles for interesting parameters
Referenced by GroundRoverPositionControl(), and parameters_update().
struct { ... } GroundRoverPositionControl::_parameters
local copies of interesting parameters
Referenced by control_position(), parameters_update(), and task_main().
int GroundRoverPositionControl::_params_sub {-1} private
notification of parameter updates
Definition at line 105 of file GroundRoverPositionControl.hpp.
Referenced by task_main().
uint8_t GroundRoverPositionControl::_pos_reset_counter {0} private
Definition at line 127 of file GroundRoverPositionControl.hpp.
Referenced by task_main().
position_setpoint_triplet_s GroundRoverPositionControl::_pos_sp_triplet {} private
triplet of mission items
Definition at line 110 of file GroundRoverPositionControl.hpp.
Referenced by control_position(), position_setpoint_triplet_poll(), and task_main().
int GroundRoverPositionControl::_pos_sp_triplet_sub {-1} private
Definition at line 106 of file GroundRoverPositionControl.hpp.
Referenced by position_setpoint_triplet_poll(), and task_main().
PID_t GroundRoverPositionControl::_speed_ctrl {} private
Definition at line 124 of file GroundRoverPositionControl.hpp.
Referenced by control_position(), and parameters_update().
Subscription<vehicle_attitude_s> GroundRoverPositionControl::_sub_attitude private
Definition at line 115 of file GroundRoverPositionControl.hpp.
Referenced by control_position(), and task_main().
Subscription<sensor_bias_s> GroundRoverPositionControl::_sub_sensors private
Definition at line 116 of file GroundRoverPositionControl.hpp.
Referenced by control_position(), and task_main().
bool GroundRoverPositionControl::_task_running {false} private
if true, task is running in its mainloop
Definition at line 100 of file GroundRoverPositionControl.hpp.
Referenced by task_main(), and task_running().
bool GroundRoverPositionControl::_task_should_exit {false} private
if true, sensor task should exit
Definition at line 99 of file GroundRoverPositionControl.hpp.
Referenced by task_main(), and ~GroundRoverPositionControl().
float GroundRoverPositionControl::gndspeed_max
Definition at line 142 of file GroundRoverPositionControl.hpp.
param_t GroundRoverPositionControl::gndspeed_max
Definition at line 164 of file GroundRoverPositionControl.hpp.
float GroundRoverPositionControl::gndspeed_trim
Definition at line 141 of file GroundRoverPositionControl.hpp.
param_t GroundRoverPositionControl::gndspeed_trim
Definition at line 163 of file GroundRoverPositionControl.hpp.
float GroundRoverPositionControl::l1_damping
Definition at line 138 of file GroundRoverPositionControl.hpp.
param_t GroundRoverPositionControl::l1_damping
Definition at line 160 of file GroundRoverPositionControl.hpp.
float GroundRoverPositionControl::l1_distance
Definition at line 139 of file GroundRoverPositionControl.hpp.
param_t GroundRoverPositionControl::l1_distance
Definition at line 161 of file GroundRoverPositionControl.hpp.
float GroundRoverPositionControl::l1_period
Definition at line 137 of file GroundRoverPositionControl.hpp.
param_t GroundRoverPositionControl::l1_period
Definition at line 159 of file GroundRoverPositionControl.hpp.
int32_t GroundRoverPositionControl::speed_control_mode
Definition at line 144 of file GroundRoverPositionControl.hpp.
param_t GroundRoverPositionControl::speed_control_mode
Definition at line 166 of file GroundRoverPositionControl.hpp.
float GroundRoverPositionControl::speed_d
Definition at line 147 of file GroundRoverPositionControl.hpp.
param_t GroundRoverPositionControl::speed_d
Definition at line 170 of file GroundRoverPositionControl.hpp.
float GroundRoverPositionControl::speed_i
Definition at line 146 of file GroundRoverPositionControl.hpp.
param_t GroundRoverPositionControl::speed_i
Definition at line 169 of file GroundRoverPositionControl.hpp.
float GroundRoverPositionControl::speed_imax
Definition at line 148 of file GroundRoverPositionControl.hpp.
param_t GroundRoverPositionControl::speed_imax
Definition at line 171 of file GroundRoverPositionControl.hpp.
float GroundRoverPositionControl::speed_p
Definition at line 145 of file GroundRoverPositionControl.hpp.
param_t GroundRoverPositionControl::speed_p
Definition at line 168 of file GroundRoverPositionControl.hpp.
float GroundRoverPositionControl::throttle_cruise
Definition at line 153 of file GroundRoverPositionControl.hpp.
param_t GroundRoverPositionControl::throttle_cruise
Definition at line 176 of file GroundRoverPositionControl.hpp.
float GroundRoverPositionControl::throttle_max
Definition at line 152 of file GroundRoverPositionControl.hpp.
param_t GroundRoverPositionControl::throttle_max
Definition at line 175 of file GroundRoverPositionControl.hpp.
float GroundRoverPositionControl::throttle_min
Definition at line 151 of file GroundRoverPositionControl.hpp.
param_t GroundRoverPositionControl::throttle_min
Definition at line 174 of file GroundRoverPositionControl.hpp.
float GroundRoverPositionControl::throttle_slew_max
Definition at line 154 of file GroundRoverPositionControl.hpp.
param_t GroundRoverPositionControl::throttle_slew_max
Definition at line 177 of file GroundRoverPositionControl.hpp.
float GroundRoverPositionControl::throttle_speed_scaler
Definition at line 149 of file GroundRoverPositionControl.hpp.
param_t GroundRoverPositionControl::throttle_speed_scaler
Definition at line 172 of file GroundRoverPositionControl.hpp.
enum GroundRoverPositionControl::UGV_POSCTRL_MODE GroundRoverPositionControl::UGV_POSCTRL_MODE_OTHER private
used to check the mode in the last control loop iteration. Use to check if the last iteration was in the same mode.
Referenced by control_position().
The documentation for this class was generated from the following files:
src/modules/gnd_pos_control/GroundRoverPositionControl.hpp
src/modules/gnd_pos_control/GroundRoverPositionControl.cpp