PX4 Firmware: IridiumSBD Class Reference
IridiumSBD Class Reference
The driver for the Rockblock 9602 and 9603 RockBlock module for satellite communication over the Iridium satellite system.
#include <IridiumSBD.h>
Public Member Functions
IridiumSBD ()
int ioctl (struct file *filp, int cmd, unsigned long arg)
Public Member Functions inherited from device::CDev
CDev (const char *name, const char *devname)
Constructor.
virtual ~CDev ()
virtual int init ()
Initialise the driver and make it ready for use.
virtual int open (file_t *filep)
Handle an open of the device.
virtual int close (file_t *filep)
Handle a close of the device.
virtual ssize_t read (file_t *filep, char *buffer, size_t buflen)
Perform a read from the device.
virtual ssize_t write (file_t *filep, const char *buffer, size_t buflen)
Perform a write to the device.
virtual off_t seek (file_t *filep, off_t offset, int whence)
Perform a logical seek operation on the device.
virtual int ioctl (file_t *filep, int cmd, unsigned long arg)
Perform an ioctl operation on the device.
virtual int poll (file_t *filep, px4_pollfd_struct_t *fds, bool setup)
Perform a poll setup/teardown operation.
Public Member Functions inherited from device::Device
virtual ~Device ()=default
Destructor.
virtual int read (unsigned address, void *data, unsigned count)
Read directly from the device.
virtual int write (unsigned address, void *data, unsigned count)
Write directly to the device.
virtual int ioctl (unsigned operation, unsigned &arg)
Perform a device-specific operation.
uint8_t get_device_bus ()
Return the bus ID the device is connected to.
DeviceBusType get_device_bus_type ()
Return the bus type the device is connected to.
uint8_t get_device_address ()
Return the bus address of the device.
void set_device_address (int address)
void set_device_type (uint8_t devtype)
Set the device type.
virtual bool external ()
Static Public Member Functions
static int start (int argc, char *argv[])
static int stop ()
static void status ()
static void test (int argc, char *argv[])
Private Member Functions
void main_loop (int argc, char *argv[])
void standby_loop (void)
void csq_loop (void)
void sbdsession_loop (void)
void test_loop (void)
void start_csq (void)
void start_sbd_session (void)
void start_test (void)
ssize_t write (struct file *filp, const char *buffer, size_t buflen)
ssize_t read (struct file *filp, char *buffer, size_t buflen)
void write_tx_buf ()
void read_rx_buf ()
void write_at (const char *command)
satcom_result_code read_at_command (int16_t timeout=100)
satcom_result_code read_at_msg (int16_t timeout=100)
satcom_result_code read_at (uint8_t *rx_buf, int *rx_len, int16_t timeout=100)
void schedule_test (void)
bool clear_mo_buffer ()
satcom_uart_status open_uart (char *uart_name)
bool is_modem_ready (void)
pollevent_t poll_state (struct file *filp)
void publish_iridium_status (void)
void publish_subsystem_status ()
virtual int open_first (struct file *filep) override
Notification of the first open of CDev.
virtual int close_last (struct file *filep) override
Notification of the last close of CDev.
Static Private Member Functions
static void main_loop_helper (int argc, char *argv[])
Private Attributes
bool _task_should_exit = false
bool _start_completed = false
int uart_fd = -1
int32_t _param_read_interval_s = -1
int32_t _param_session_timeout_s = -1
int32_t _param_stacking_time_ms = -1
hrt_abstime _last_signal_check = 0
uint8_t _signal_quality = 0
uint16_t _failed_sbd_sessions = 0
uint16_t _successful_sbd_sessions = 0
uint16_t _num_tx_buf_reset = 0
bool _writing_mavlink_packet = false
uint16_t _packet_length = 0
orb_advert_t _iridiumsbd_status_pub = nullptr
orb_advert_t _subsystem_pub = nullptr
bool _test_pending = false
char _test_command [32]
hrt_abstime _test_timer = 0
uint8_t _rx_command_buf [SATCOM_RX_COMMAND_BUF_LEN] = {}
int _rx_command_len = 0
uint8_t _rx_msg_buf [SATCOM_RX_MSG_BUF_LEN] = {}
int _rx_msg_end_idx = 0
int _rx_msg_read_idx = 0
uint8_t _tx_buf [SATCOM_TX_BUF_LEN] = {}
int _tx_buf_write_idx = 0
bool _tx_buf_write_pending = false
bool _ring_pending = false
bool _rx_session_pending = false
bool _rx_read_pending = false
bool _tx_session_pending = false
bool _cdev_used = false
hrt_abstime _last_write_time = 0
hrt_abstime _last_read_time = 0
hrt_abstime _last_heartbeat = 0
hrt_abstime _session_start_time = 0
satcom_state _state = SATCOM_STATE_STANDBY
satcom_state _new_state = SATCOM_STATE_STANDBY
pthread_mutex_t _tx_buf_mutex = pthread_mutex_t()
pthread_mutex_t _rx_buf_mutex = pthread_mutex_t()
bool _verbose = false
iridiumsbd_status_s _status = {}
subsystem_info_s _info = {}
Static Private Attributes
static IridiumSBD * instance
static int task_handle
Additional Inherited Members
Public Types inherited from device::Device
enum DeviceBusType { DeviceBusType_UNKNOWN = 0, DeviceBusType_I2C = 1, DeviceBusType_SPI = 2, DeviceBusType_UAVCAN = 3 }
Device bus types for DEVID.
Protected Member Functions inherited from device::CDev
virtual pollevent_t poll_state (file_t *filep)
Check the current state of the device for poll events from the perspective of the file.
virtual void poll_notify (pollevent_t events)
Report new poll events.
virtual void poll_notify_one (px4_pollfd_struct_t *fds, pollevent_t events)
Internal implementation of poll_notify.
virtual int open_first (file_t *filep)
Notification of the first open.
virtual int close_last (file_t *filep)
Notification of the last close.
virtual int register_class_devname (const char *class_devname)
Register a class device name, automatically adding device class instance suffix if need be.
virtual int unregister_class_devname (const char *class_devname, unsigned class_instance)
Register a class device name, automatically adding device class instance suffix if need be.
const char * get_devname ()
Get the device name.
void lock ()
Take the driver lock.
void unlock ()
Release the driver lock.
Protected Member Functions inherited from device::Device
Device (const char *name)
Device (DeviceBusType bus_type, uint8_t bus, uint8_t address, uint8_t devtype=0)
Device (const Device &)=delete
Device & operator= (const Device &)=delete
Device (Device &&)=delete
Device & operator= (Device &&)=delete
Protected Attributes inherited from device::CDev
px4_sem_t _lock
lock to protect access to all class members (also for derived classes)
bool _pub_blocked {false}
true if publishing should be blocked
Protected Attributes inherited from device::Device
union DeviceId _device_id
device identifier information
const char * _name
driver name
bool _debug_enabled {false}
if true, debug messages are printed
Static Protected Attributes inherited from device::CDev
static const px4_file_operations_t fops = {}
Pointer to the default cdev file operations table; useful for registering clone devices etc.
Detailed Description
The driver for the Rockblock 9602 and 9603 RockBlock module for satellite communication over the Iridium satellite system.
The MavLink 1 protocol should be used to ensure that the status message is 50 bytes (RockBlock bills every 50 bytes per transmission).
TODO:
Improve TX buffer handling:
Do not reset the full TX buffer but delete the oldest HIGH_LATENCY2 message if one is in the buffer or delete the oldest message in general
Definition at line 101 of file IridiumSBD.h.
Constructor & Destructor Documentation
IridiumSBD::IridiumSBD ()
Definition at line 59 of file IridiumSBD.cpp.
Referenced by start().
Member Function Documentation
bool IridiumSBD::clear_mo_buffer () private
Definition at line 975 of file IridiumSBD.cpp.
References _rx_command_buf, read_at_command(), SATCOM_RESULT_OK, VERBOSE_INFO, and write_at().
Referenced by standby_loop().
int IridiumSBD::close_last (struct file * filep) override private virtual
Notification of the last close of CDev.
This function is called when the device open count transitions from one to zero. The driver lock is held for the duration of the call.
Notes that CDev is not used anymore and allows stopping the driver.
Parameters
filep Pointer to the NuttX file structure.
Returns
OK if the open should return OK, -errno otherwise.
Definition at line 1153 of file IridiumSBD.cpp.
References _cdev_used.
void IridiumSBD::csq_loop (void) private
Definition at line 441 of file IridiumSBD.cpp.
References _new_state, _rx_command_buf, _signal_quality, read_at_command(), SATCOM_RESULT_NA, SATCOM_RESULT_OK, SATCOM_STATE_STANDBY, and VERBOSE_INFO.
Referenced by main_loop().
int IridiumSBD::ioctl (struct file * filp, int cmd, unsigned long arg)
Definition at line 187 of file IridiumSBD.cpp.
References _rx_msg_end_idx, _rx_msg_read_idx, _tx_buf_write_idx, OK, SATCOM_MAX_MESSAGE_LENGTH, and SATCOM_TX_BUF_LEN.
bool IridiumSBD::is_modem_ready (void) private
Definition at line 1009 of file IridiumSBD.cpp.
References read_at_command(), SATCOM_RESULT_OK, and write_at().
Referenced by read_rx_buf(), start_csq(), start_sbd_session(), start_test(), and write_tx_buf().
void IridiumSBD::main_loop (int argc, char * argv[]) private
Definition at line 230 of file IridiumSBD.cpp.
References _new_state, _param_read_interval_s, _param_session_timeout_s, _param_stacking_time_ms, _rx_buf_mutex, _start_completed, _state, _task_should_exit, _tx_buf_mutex, _verbose, counter, csq_loop(), lis3mdl::init(), open_uart(), param_find(), param_get(), pthread_mutex_init(), publish_iridium_status(), publish_subsystem_status(), PX4_ERR, PX4_WARN, read_at_command(), SATCOM_RESULT_OK, SATCOM_STATE_CSQ, SATCOM_STATE_SBDSESSION, SATCOM_STATE_STANDBY, satcom_state_string, SATCOM_STATE_TEST, SATCOM_UART_OK, sbdsession_loop(), standby_loop(), test_loop(), usleep(), VERBOSE_INFO, and write_at().
Referenced by main_loop_helper().
void IridiumSBD::main_loop_helper (int argc, char * argv[]) static private
Definition at line 216 of file IridiumSBD.cpp.
References device::CDev::close(), instance, main_loop(), PX4_WARN, task_handle, and uart_fd.
Referenced by start().
int IridiumSBD::open_first (struct file * filep) override private virtual
Notification of the first open of CDev.
This function is called when the device open count transitions from zero to one. The driver lock is held for the duration of the call.
Notes that CDev is used and blocks stopping the driver.
Parameters
filep Pointer to the NuttX file structure.
Returns
OK if the open should proceed, -errno otherwise.
Definition at line 1147 of file IridiumSBD.cpp.
References _cdev_used.
satcom_uart_status IridiumSBD::open_uart (char * uart_name) private
Definition at line 987 of file IridiumSBD.cpp.
References device::CDev::open(), SATCOM_UART_OK, SATCOM_UART_OPEN_FAIL, uart_fd, and VERBOSE_INFO.
Referenced by main_loop().
pollevent_t IridiumSBD::poll_state (struct file * filp) private
Definition at line 1021 of file IridiumSBD.cpp.
References _rx_msg_end_idx, _rx_msg_read_idx, _tx_buf_write_idx, and SATCOM_TX_BUF_LEN.
void IridiumSBD::publish_iridium_status (void) private
Definition at line 1036 of file IridiumSBD.cpp.
References _failed_sbd_sessions, _iridiumsbd_status_pub, _last_heartbeat, _num_tx_buf_reset, _ring_pending, _rx_msg_end_idx, _rx_msg_read_idx, _rx_read_pending, _rx_session_pending, _signal_quality, _state, _status, _successful_sbd_sessions, _tx_buf_write_idx, _tx_buf_write_pending, _tx_session_pending, iridiumsbd_status_s::failed_sbd_sessions, hrt_absolute_time(), iridiumsbd_status_s::last_heartbeat, iridiumsbd_status_s::num_tx_buf_reset, orb_advertise(), ORB_ID, orb_publish(), iridiumsbd_status_s::ring_pending, iridiumsbd_status_s::rx_buf_end_index, iridiumsbd_status_s::rx_buf_read_index, iridiumsbd_status_s::rx_read_pending, iridiumsbd_status_s::rx_session_pending, iridiumsbd_status_s::signal_quality, iridiumsbd_status_s::state, iridiumsbd_status_s::successful_sbd_sessions, iridiumsbd_status_s::timestamp, iridiumsbd_status_s::tx_buf_write_index, iridiumsbd_status_s::tx_buf_write_pending, and iridiumsbd_status_s::tx_session_pending.
Referenced by main_loop().
void IridiumSBD::publish_subsystem_status () private
Definition at line 1124 of file IridiumSBD.cpp.
References _info, _status, _subsystem_pub, subsystem_info_s::enabled, hrt_absolute_time(), iridiumsbd_status_s::last_heartbeat, subsystem_info_s::ok, orb_advertise_queue(), ORB_ID, orb_publish(), subsystem_info_s::present, subsystem_info_s::subsystem_type, and subsystem_info_s::timestamp.
Referenced by main_loop().
ssize_t IridiumSBD::read (struct file * filp, char * buffer, size_t buflen) private
Definition at line 751 of file IridiumSBD.cpp.
References _rx_buf_mutex, _rx_msg_buf, _rx_msg_end_idx, _rx_msg_read_idx, pthread_mutex_lock(), pthread_mutex_unlock(), and VERBOSE_INFO.
Referenced by read_at().
satcom_result_code IridiumSBD::read_at (uint8_t * rx_buf, int * rx_len, int16_t timeout = 100) private
Definition at line 905 of file IridiumSBD.cpp.
References _ring_pending, _rx_session_pending, device::CDev::poll(), PX4_WARN, read(), rx_len, SATCOM_RESULT_ERROR, SATCOM_RESULT_HWFAIL, SATCOM_RESULT_NA, SATCOM_RESULT_OK, SATCOM_RESULT_READY, SATCOM_RESULT_SBDRING, uart_fd, and VERBOSE_INFO.
Referenced by read_at_command(), and read_at_msg().
satcom_result_code IridiumSBD::read_at_command (int16_t timeout = 100) private
Definition at line 895 of file IridiumSBD.cpp.
References _rx_command_buf, _rx_command_len, and read_at().
Referenced by clear_mo_buffer(), csq_loop(), is_modem_ready(), main_loop(), sbdsession_loop(), standby_loop(), start_test(), test_loop(), and write_tx_buf().
satcom_result_code IridiumSBD::read_at_msg (int16_t timeout = 100) private
Definition at line 900 of file IridiumSBD.cpp.
References _rx_msg_buf, _rx_msg_end_idx, and read_at().
Referenced by read_rx_buf().
void IridiumSBD::read_rx_buf (void) private
Definition at line 837 of file IridiumSBD.cpp.
References _rx_buf_mutex, _rx_msg_buf, _rx_msg_end_idx, _rx_msg_read_idx, _rx_read_pending, is_modem_ready(), pthread_mutex_lock(), pthread_mutex_unlock(), PX4_ERR, read_at_msg(), SATCOM_RESULT_OK, VERBOSE_INFO, and write_at().
Referenced by standby_loop().
void IridiumSBD::sbdsession_loop (void) private
Definition at line 471 of file IridiumSBD.cpp.
References _failed_sbd_sessions, _last_heartbeat, _last_read_time, _new_state, _param_session_timeout_s, _ring_pending, _rx_command_buf, _rx_read_pending, _rx_session_pending, _session_start_time, _signal_quality, _successful_sbd_sessions, _tx_buf_mutex, _tx_buf_write_idx, _tx_session_pending, hrt_absolute_time(), pthread_mutex_unlock(), PX4_WARN, read_at_command(), SATCOM_RESULT_NA, SATCOM_RESULT_OK, SATCOM_STATE_STANDBY, and VERBOSE_INFO.
Referenced by main_loop().
void IridiumSBD::schedule_test (void) private
Definition at line 970 of file IridiumSBD.cpp.
References _test_pending.
Referenced by test().
void IridiumSBD::standby_loop (void) private
Definition at line 375 of file IridiumSBD.cpp.
References _last_read_time, _last_signal_check, _last_write_time, _new_state, _param_read_interval_s, _param_stacking_time_ms, _rx_msg_end_idx, _rx_msg_read_idx, _rx_read_pending, _rx_session_pending, _signal_quality, _test_command, _test_pending, _test_timer, _tx_buf_write_pending, _tx_session_pending, clear_mo_buffer(), hrt_absolute_time(), read_at_command(), read_rx_buf(), SATCOM_SIGNAL_REFRESH_DELAY, SATCOM_STATE_STANDBY, start_csq(), start_sbd_session(), start_test(), write(), and write_tx_buf().
Referenced by main_loop().
int IridiumSBD::start (int argc, char * argv[]) static
Definition at line 68 of file IridiumSBD.cpp.
References _start_completed, _task_should_exit, counter, IridiumSBD(), main_loop_helper(), PX4_ERROR, PX4_INFO, PX4_OK, px4_task_spawn_cmd(), PX4_WARN, SCHED_DEFAULT, SCHED_PRIORITY_SLOW_DRIVER, task_handle, and usleep().
Referenced by iridiumsbd_main().
void IridiumSBD::start_csq (void) private
Definition at line 600 of file IridiumSBD.cpp.
References _last_signal_check, _new_state, _state, hrt_absolute_time(), is_modem_ready(), SATCOM_STATE_CSQ, SATCOM_STATE_STANDBY, VERBOSE_INFO, and write_at().
Referenced by standby_loop().
void IridiumSBD::start_sbd_session (void) private
Definition at line 621 of file IridiumSBD.cpp.
References _new_state, _ring_pending, _session_start_time, _state, _tx_buf_mutex, hrt_absolute_time(), is_modem_ready(), pthread_mutex_lock(), SATCOM_STATE_SBDSESSION, SATCOM_STATE_STANDBY, VERBOSE_INFO, and write_at().
Referenced by standby_loop().
void IridiumSBD::start_test (void) private
Definition at line 650 of file IridiumSBD.cpp.
References _new_state, _rx_command_buf, _rx_command_len, _state, _test_command, is_modem_ready(), PX4_INFO, PX4_WARN, read_at_command(), SATCOM_RESULT_NA, SATCOM_STATE_STANDBY, SATCOM_STATE_TEST, and write_at().
Referenced by standby_loop().
void IridiumSBD::status () static
Definition at line 145 of file IridiumSBD.cpp.
References _last_heartbeat, _last_signal_check, _rx_read_pending, _rx_session_pending, _signal_quality, _state, _tx_buf_write_idx, _tx_session_pending, hrt_absolute_time(), instance, PX4_INFO, PX4_WARN, and satcom_state_string.
Referenced by iridiumsbd_main().
int IridiumSBD::stop () static
Definition at line 107 of file IridiumSBD.cpp.
References _cdev_used, _task_should_exit, device::CDev::close(), instance, OK, PX4_ERROR, PX4_WARN, task_handle, and uart_fd.
Referenced by iridiumsbd_main().
void IridiumSBD::test (int argc, char * argv[]) static
Definition at line 164 of file IridiumSBD.cpp.
References _state, _test_command, _test_pending, instance, PX4_WARN, SATCOM_STATE_STANDBY, and schedule_test().
Referenced by iridiumsbd_main().
void IridiumSBD::test_loop (void) private
Definition at line 583 of file IridiumSBD.cpp.
References _new_state, _rx_command_buf, _rx_command_len, _test_timer, hrt_absolute_time(), PX4_INFO, PX4_WARN, read_at_command(), SATCOM_RESULT_NA, and SATCOM_STATE_STANDBY.
Referenced by main_loop().
ssize_t IridiumSBD::write (struct file * filp, const char * buffer, size_t buflen) private
Definition at line 691 of file IridiumSBD.cpp.
References _last_write_time, _num_tx_buf_reset, _packet_length, _tx_buf, _tx_buf_mutex, _tx_buf_write_idx, _tx_buf_write_pending, _writing_mavlink_packet, hrt_absolute_time(), pthread_mutex_lock(), pthread_mutex_unlock(), PX4_ERROR, SATCOM_TX_BUF_LEN, and VERBOSE_INFO.
Referenced by standby_loop(), write_at(), and write_tx_buf().
void IridiumSBD::write_at (const char * command) private
Definition at line 887 of file IridiumSBD.cpp.
References uart_fd, VERBOSE_INFO, and write().
Referenced by clear_mo_buffer(), is_modem_ready(), main_loop(), read_rx_buf(), start_csq(), start_sbd_session(), start_test(), and write_tx_buf().
void IridiumSBD::write_tx_buf () private
Definition at line 776 of file IridiumSBD.cpp.
References _rx_command_buf, _tx_buf, _tx_buf_mutex, _tx_buf_write_idx, _tx_buf_write_pending, _tx_session_pending, command, is_modem_ready(), pthread_mutex_lock(), pthread_mutex_unlock(), read_at_command(), SATCOM_RESULT_OK, SATCOM_RESULT_READY, uart_fd, VERBOSE_INFO, write(), and write_at().
Referenced by standby_loop().
Member Data Documentation
bool IridiumSBD::_cdev_used = false private
Definition at line 330 of file IridiumSBD.h.
Referenced by close_last(), open_first(), and stop().
uint16_t IridiumSBD::_failed_sbd_sessions = 0 private
Definition at line 300 of file IridiumSBD.h.
Referenced by publish_iridium_status(), and sbdsession_loop().
subsystem_info_s IridiumSBD::_info = {} private
Definition at line 346 of file IridiumSBD.h.
Referenced by publish_subsystem_status().
orb_advert_t IridiumSBD::_iridiumsbd_status_pub = nullptr private
Definition at line 307 of file IridiumSBD.h.
Referenced by publish_iridium_status().
hrt_abstime IridiumSBD::_last_heartbeat = 0 private
Definition at line 334 of file IridiumSBD.h.
Referenced by publish_iridium_status(), sbdsession_loop(), and status().
hrt_abstime IridiumSBD::_last_read_time = 0 private
Definition at line 333 of file IridiumSBD.h.
Referenced by sbdsession_loop(), and standby_loop().
hrt_abstime IridiumSBD::_last_signal_check = 0 private
Definition at line 298 of file IridiumSBD.h.
Referenced by standby_loop(), start_csq(), and status().
hrt_abstime IridiumSBD::_last_write_time = 0 private
Definition at line 332 of file IridiumSBD.h.
Referenced by standby_loop(), and write().
satcom_state IridiumSBD::_new_state = SATCOM_STATE_STANDBY private
Definition at line 338 of file IridiumSBD.h.
Referenced by csq_loop(), main_loop(), sbdsession_loop(), standby_loop(), start_csq(), start_sbd_session(), start_test(), and test_loop().
uint16_t IridiumSBD::_num_tx_buf_reset = 0 private
Definition at line 302 of file IridiumSBD.h.
Referenced by publish_iridium_status(), and write().
uint16_t IridiumSBD::_packet_length = 0 private
Definition at line 305 of file IridiumSBD.h.
Referenced by write().
int32_t IridiumSBD::_param_read_interval_s = -1 private
Definition at line 294 of file IridiumSBD.h.
Referenced by main_loop(), and standby_loop().
int32_t IridiumSBD::_param_session_timeout_s = -1 private
Definition at line 295 of file IridiumSBD.h.
Referenced by main_loop(), and sbdsession_loop().
int32_t IridiumSBD::_param_stacking_time_ms = -1 private
Definition at line 296 of file IridiumSBD.h.
Referenced by main_loop(), and standby_loop().
bool IridiumSBD::_ring_pending = false private
Definition at line 325 of file IridiumSBD.h.
Referenced by publish_iridium_status(), read_at(), sbdsession_loop(), and start_sbd_session().
pthread_mutex_t IridiumSBD::_rx_buf_mutex = pthread_mutex_t() private
Definition at line 341 of file IridiumSBD.h.
Referenced by main_loop(), read(), and read_rx_buf().
uint8_t IridiumSBD::_rx_command_buf[SATCOM_RX_COMMAND_BUF_LEN] = {} private
Definition at line 314 of file IridiumSBD.h.
Referenced by clear_mo_buffer(), csq_loop(), read_at_command(), sbdsession_loop(), start_test(), test_loop(), and write_tx_buf().
int IridiumSBD::_rx_command_len = 0 private
Definition at line 315 of file IridiumSBD.h.
Referenced by read_at_command(), start_test(), and test_loop().
uint8_t IridiumSBD::_rx_msg_buf[SATCOM_RX_MSG_BUF_LEN] = {} private
Definition at line 317 of file IridiumSBD.h.
Referenced by read(), read_at_msg(), and read_rx_buf().
int IridiumSBD::_rx_msg_end_idx = 0 private
Definition at line 318 of file IridiumSBD.h.
Referenced by ioctl(), poll_state(), publish_iridium_status(), read(), read_at_msg(), read_rx_buf(), and standby_loop().
int IridiumSBD::_rx_msg_read_idx = 0 private
Definition at line 319 of file IridiumSBD.h.
Referenced by ioctl(), poll_state(), publish_iridium_status(), read(), read_rx_buf(), and standby_loop().
bool IridiumSBD::_rx_read_pending = false private
Definition at line 327 of file IridiumSBD.h.
Referenced by publish_iridium_status(), read_rx_buf(), sbdsession_loop(), standby_loop(), and status().
bool IridiumSBD::_rx_session_pending = false private
Definition at line 326 of file IridiumSBD.h.
Referenced by publish_iridium_status(), read_at(), sbdsession_loop(), standby_loop(), and status().
hrt_abstime IridiumSBD::_session_start_time = 0 private
Definition at line 335 of file IridiumSBD.h.
Referenced by sbdsession_loop(), and start_sbd_session().
uint8_t IridiumSBD::_signal_quality = 0 private
Definition at line 299 of file IridiumSBD.h.
Referenced by csq_loop(), publish_iridium_status(), sbdsession_loop(), standby_loop(), and status().
bool IridiumSBD::_start_completed = false private
Definition at line 291 of file IridiumSBD.h.
Referenced by main_loop(), and start().
satcom_state IridiumSBD::_state = SATCOM_STATE_STANDBY private
Definition at line 337 of file IridiumSBD.h.
Referenced by main_loop(), publish_iridium_status(), start_csq(), start_sbd_session(), start_test(), status(), and test().
iridiumsbd_status_s IridiumSBD::_status = {} private
Definition at line 345 of file IridiumSBD.h.
Referenced by publish_iridium_status(), and publish_subsystem_status().
orb_advert_t IridiumSBD::_subsystem_pub = nullptr private
Definition at line 308 of file IridiumSBD.h.
Referenced by publish_subsystem_status().
uint16_t IridiumSBD::_successful_sbd_sessions = 0 private
Definition at line 301 of file IridiumSBD.h.
Referenced by publish_iridium_status(), and sbdsession_loop().
bool IridiumSBD::_task_should_exit = false private
Definition at line 290 of file IridiumSBD.h.
Referenced by main_loop(), start(), and stop().
char IridiumSBD::_test_command[32] private
Definition at line 311 of file IridiumSBD.h.
Referenced by standby_loop(), start_test(), and test().
bool IridiumSBD::_test_pending = false private
Definition at line 310 of file IridiumSBD.h.
Referenced by schedule_test(), standby_loop(), and test().
hrt_abstime IridiumSBD::_test_timer = 0 private
Definition at line 312 of file IridiumSBD.h.
Referenced by standby_loop(), and test_loop().
uint8_t IridiumSBD::_tx_buf[SATCOM_TX_BUF_LEN] = {} private
Definition at line 321 of file IridiumSBD.h.
Referenced by write(), and write_tx_buf().
pthread_mutex_t IridiumSBD::_tx_buf_mutex = pthread_mutex_t() private
Definition at line 340 of file IridiumSBD.h.
Referenced by main_loop(), sbdsession_loop(), start_sbd_session(), write(), and write_tx_buf().
int IridiumSBD::_tx_buf_write_idx = 0 private
Definition at line 322 of file IridiumSBD.h.
Referenced by ioctl(), poll_state(), publish_iridium_status(), sbdsession_loop(), status(), write(), and write_tx_buf().
bool IridiumSBD::_tx_buf_write_pending = false private
Definition at line 324 of file IridiumSBD.h.
Referenced by publish_iridium_status(), standby_loop(), write(), and write_tx_buf().
bool IridiumSBD::_tx_session_pending = false private
Definition at line 328 of file IridiumSBD.h.
Referenced by publish_iridium_status(), sbdsession_loop(), standby_loop(), status(), and write_tx_buf().
bool IridiumSBD::_verbose = false private
Definition at line 343 of file IridiumSBD.h.
Referenced by main_loop().
bool IridiumSBD::_writing_mavlink_packet = false private
Definition at line 304 of file IridiumSBD.h.
Referenced by write().
IridiumSBD * IridiumSBD::instance static private
Definition at line 288 of file IridiumSBD.h.
Referenced by main_loop_helper(), status(), stop(), and test().
int IridiumSBD::task_handle static private
Definition at line 289 of file IridiumSBD.h.
Referenced by main_loop_helper(), start(), and stop().
int IridiumSBD::uart_fd = -1 private
Definition at line 292 of file IridiumSBD.h.
Referenced by main_loop_helper(), open_uart(), read_at(), stop(), write_at(), and write_tx_buf().
The documentation for this class was generated from the following files:
src/drivers/telemetry/iridiumsbd/IridiumSBD.h
src/drivers/telemetry/iridiumsbd/IridiumSBD.cpp