PX4 Firmware: EngineFailure Class Reference
EngineFailure Class Reference
#include <enginefailure.h>
Public Member Functions
EngineFailure (Navigator *navigator)
~EngineFailure ()=default
void on_inactive () override
This function is called while the mode is inactive.
void on_activation () override
This function is called one time when mode becomes active, pos_sp_triplet must be initialized here.
void on_active () override
This function is called while the mode is active.
Public Member Functions inherited from MissionBlock
MissionBlock (Navigator *navigator)
Constructor.
virtual ~MissionBlock ()=default
MissionBlock (const MissionBlock &)=delete
MissionBlock & operator= (const MissionBlock &)=delete
Public Member Functions inherited from NavigatorMode
NavigatorMode (Navigator *navigator)
virtual ~NavigatorMode ()=default
NavigatorMode (const NavigatorMode &)=delete
NavigatorMode operator= (const NavigatorMode &)=delete
void run (bool active)
virtual void on_inactivation ()
This function is called one time when mode becomes inactive.
Private Types
enum EFState { EF_STATE_NONE = 0, EF_STATE_LOITERDOWN = 1 }
Private Member Functions
void set_ef_item ()
Set the DLL item.
void advance_ef ()
Move to next EF item.
Private Attributes
enum EngineFailure::EFState EF_STATE_NONE
Additional Inherited Members
Static Public Member Functions inherited from MissionBlock
static bool item_contains_position (const mission_item_s &item)
Protected Member Functions inherited from MissionBlock
bool is_mission_item_reached ()
Check if mission item has been reached.
void reset_mission_item_reached ()
Reset all reached flags.
bool mission_item_to_position_setpoint (const mission_item_s &item, position_setpoint_s *sp)
Convert a mission item to a position setpoint.
void set_loiter_item (struct mission_item_s *item, float min_clearance=-1.0f)
Set a loiter mission item, if possible reuse the position setpoint, otherwise take the current position.
void set_takeoff_item (struct mission_item_s *item, float abs_altitude, float min_pitch=0.0f)
Set a takeoff mission item.
void set_land_item (struct mission_item_s *item, bool at_current_location)
Set a land mission item.
void set_idle_item (struct mission_item_s *item)
Set idle mission item.
void set_vtol_transition_item (struct mission_item_s *item, const uint8_t new_mode)
Set vtol transition item.
void mission_apply_limitation (mission_item_s &item)
General function used to adjust the mission item based on vehicle specific limitations.
void issue_command (const mission_item_s &item)
float get_time_inside (const struct mission_item_s &item)
float get_absolute_altitude_for_item (struct mission_item_s &mission_item) const
Protected Attributes inherited from MissionBlock
mission_item_s _mission_item {}
bool _waypoint_position_reached {false}
bool _waypoint_yaw_reached {false}
hrt_abstime _time_first_inside_orbit {0}
hrt_abstime _action_start {0}
hrt_abstime _time_wp_reached {0}
orb_advert_t _actuator_pub {nullptr}
Protected Attributes inherited from NavigatorMode
Navigator * _navigator {nullptr}
Detailed Description
Definition at line 47 of file enginefailure.h.
Member Enumeration Documentation
enum EngineFailure::EFState private
Enumerator
EF_STATE_NONE
EF_STATE_LOITERDOWN
Definition at line 58 of file enginefailure.h.
Constructor & Destructor Documentation
EngineFailure::EngineFailure (Navigator * navigator)
Definition at line 55 of file enginefailure.cpp.
EngineFailure::~EngineFailure () default
Member Function Documentation
void EngineFailure::advance_ef () private
Move to next EF item.
Definition at line 127 of file enginefailure.cpp.
References NavigatorMode::_navigator, EF_STATE_LOITERDOWN, EF_STATE_NONE, Navigator::get_mavlink_log_pub(), and mavlink_log_emergency.
Referenced by on_activation(), and on_active().
void EngineFailure::on_activation () override virtual
This function is called one time when mode becomes active, pos_sp_triplet must be initialized here.
Reimplemented from NavigatorMode.
Definition at line 68 of file enginefailure.cpp.
References advance_ef(), EF_STATE_NONE, and set_ef_item().
void EngineFailure::on_active () override virtual
This function is called while the mode is active.
Reimplemented from NavigatorMode.
Definition at line 76 of file enginefailure.cpp.
References advance_ef(), MissionBlock::is_mission_item_reached(), and set_ef_item().
void EngineFailure::on_inactive () override virtual
This function is called while the mode is inactive.
Reimplemented from NavigatorMode.
Definition at line 62 of file enginefailure.cpp.
References EF_STATE_NONE.
void EngineFailure::set_ef_item () private
Set the DLL item.
Definition at line 85 of file enginefailure.cpp.
References MissionBlock::_mission_item, NavigatorMode::_navigator, mission_item_s::acceptance_radius, home_position_s::alt, mission_item_s::altitude, mission_item_s::altitude_is_relative, mission_item_s::autocontinue, position_setpoint_triplet_s::current, EF_STATE_LOITERDOWN, Navigator::get_acceptance_radius(), Navigator::get_global_position(), Navigator::get_home_position(), Navigator::get_loiter_radius(), Navigator::get_position_setpoint_triplet(), vehicle_global_position_s::lat, mission_item_s::lat, mission_item_s::loiter_radius, vehicle_global_position_s::lon, mission_item_s::lon, MissionBlock::mission_apply_limitation(), MissionBlock::mission_item_to_position_setpoint(), mission_item_s::nav_cmd, NAV_CMD_LOITER_UNLIMITED, position_setpoint_triplet_s::next, mission_item_s::origin, ORIGIN_ONBOARD, position_setpoint_triplet_s::previous, MissionBlock::reset_mission_item_reached(), Navigator::set_can_loiter_at_sp(), Navigator::set_position_setpoint_triplet_updated(), position_setpoint_s::valid, and mission_item_s::yaw.
Referenced by on_activation(), and on_active().
Member Data Documentation
enum EngineFailure::EFState EngineFailure::EF_STATE_NONE private
Referenced by advance_ef(), on_activation(), and on_inactive().
The documentation for this class was generated from the following files:
src/modules/navigator/enginefailure.h
src/modules/navigator/enginefailure.cpp