PX4 Firmware: MavlinkStreamScaledIMU3 Class Reference
MavlinkStreamScaledIMU3 Class Reference
Public Member Functions
const char * get_name () const
uint16_t get_id ()
unsigned get_size ()
Get maximal total messages size on update.
Public Member Functions inherited from MavlinkStream
MavlinkStream (Mavlink *mavlink)
virtual ~MavlinkStream ()=default
MavlinkStream (const MavlinkStream &)=delete
MavlinkStream & operator= (const MavlinkStream &)=delete
MavlinkStream (MavlinkStream &&)=delete
MavlinkStream & operator= (MavlinkStream &&)=delete
void set_interval (const int interval)
Get the interval.
int get_interval ()
Get the interval.
int update (const hrt_abstime &t)
Update subscriptions and send message if necessary.
virtual bool const_rate ()
virtual unsigned get_size_avg ()
Get the average message size.
bool first_message_sent () const
void reset_last_sent ()
Reset the time of last sent to 0.
Static Public Member Functions
static const char * get_name_static ()
static uint16_t get_id_static ()
static MavlinkStream * new_instance (Mavlink *mavlink)
Protected Member Functions
MavlinkStreamScaledIMU3 (Mavlink *mavlink)
bool send (const hrt_abstime t)
Protected Member Functions inherited from MavlinkStream
virtual void update_data ()
Function to collect/update data for the streams at a high rate independant of actual stream rate.
Private Member Functions
MavlinkStreamScaledIMU3 (MavlinkStreamScaledIMU3 &)=delete
MavlinkStreamScaledIMU3 & operator= (const MavlinkStreamScaledIMU3 &)=delete
Private Attributes
MavlinkOrbSubscription * _raw_accel_sub
MavlinkOrbSubscription * _raw_gyro_sub
MavlinkOrbSubscription * _raw_mag_sub
uint64_t _raw_accel_time
uint64_t _raw_gyro_time
uint64_t _raw_mag_time
Additional Inherited Members
Public Attributes inherited from MavlinkStream
MavlinkStream * next {nullptr}
Protected Attributes inherited from MavlinkStream
Mavlink *const _mavlink
int _interval {1000000}
if set to negative value = unlimited rate
Detailed Description
Definition at line 944 of file mavlink_messages.cpp.
Constructor & Destructor Documentation
MavlinkStreamScaledIMU3::MavlinkStreamScaledIMU3 (MavlinkStreamScaledIMU3 &) private delete
MavlinkStreamScaledIMU3::MavlinkStreamScaledIMU3 (Mavlink * mavlink) inline explicit protected
Definition at line 991 of file mavlink_messages.cpp.
Member Function Documentation
uint16_t MavlinkStreamScaledIMU3::get_id () inline virtual
Implements MavlinkStream.
Definition at line 962 of file mavlink_messages.cpp.
References MavlinkStreamHeartbeat::get_id_static().
static uint16_t MavlinkStreamScaledIMU3::get_id_static () inline static
Definition at line 957 of file mavlink_messages.cpp.
const char* MavlinkStreamScaledIMU3::get_name () const inline virtual
Implements MavlinkStream.
Definition at line 947 of file mavlink_messages.cpp.
References get_name_static().
static const char* MavlinkStreamScaledIMU3::get_name_static () inline static
Definition at line 952 of file mavlink_messages.cpp.
Referenced by get_name().
unsigned MavlinkStreamScaledIMU3::get_size () inline virtual
Get maximal total messages size on update.
Implements MavlinkStream.
Definition at line 972 of file mavlink_messages.cpp.
static MavlinkStream* MavlinkStreamScaledIMU3::new_instance (Mavlink * mavlink) inline static
Definition at line 967 of file mavlink_messages.cpp.
MavlinkStreamScaledIMU3& MavlinkStreamScaledIMU3::operator= (const MavlinkStreamScaledIMU3 &) private delete
bool MavlinkStreamScaledIMU3::send (const hrt_abstime t) inline protected virtual
Implements MavlinkStream.
Definition at line 1000 of file mavlink_messages.cpp.
References MavlinkStream::_mavlink, CONSTANTS_ONE_G, Mavlink::get_channel(), msg, sensor_accel_s::timestamp, MavlinkOrbSubscription::update(), sensor_mag_s::x_raw, sensor_accel_s::x_raw, sensor_gyro_s::x_raw, sensor_mag_s::y_raw, sensor_gyro_s::y_raw, sensor_accel_s::y_raw, sensor_mag_s::z_raw, sensor_accel_s::z_raw, and sensor_gyro_s::z_raw.
Member Data Documentation
MavlinkOrbSubscription* MavlinkStreamScaledIMU3::_raw_accel_sub private
Definition at line 978 of file mavlink_messages.cpp.
uint64_t MavlinkStreamScaledIMU3::_raw_accel_time private
Definition at line 982 of file mavlink_messages.cpp.
MavlinkOrbSubscription* MavlinkStreamScaledIMU3::_raw_gyro_sub private
Definition at line 979 of file mavlink_messages.cpp.
uint64_t MavlinkStreamScaledIMU3::_raw_gyro_time private
Definition at line 983 of file mavlink_messages.cpp.
MavlinkOrbSubscription* MavlinkStreamScaledIMU3::_raw_mag_sub private
Definition at line 980 of file mavlink_messages.cpp.
uint64_t MavlinkStreamScaledIMU3::_raw_mag_time private
Definition at line 984 of file mavlink_messages.cpp.
The documentation for this class was generated from the following file:
src/modules/mavlink/mavlink_messages.cpp