PX4 Firmware: control::SuperBlock Class Reference
control::SuperBlock Class Reference
#include <Block.hpp>
Public Member Functions
SuperBlock (SuperBlock *parent, const char *name)
~SuperBlock ()=default
SuperBlock (const SuperBlock &)=delete
SuperBlock & operator= (const SuperBlock &)=delete
SuperBlock (SuperBlock &&)=delete
SuperBlock & operator= (SuperBlock &&)=delete
void setDt (float dt) override
void updateParams () override
void updateSubscriptions () override
void updatePublications () override
Public Member Functions inherited from control::Block
Block (SuperBlock *parent, const char *name)
virtual ~Block ()=default
Block (const Block &)=delete
Block & operator= (const Block &)=delete
Block (Block &&)=delete
Block & operator= (Block &&)=delete
void getName (char *name, size_t n)
float getDt ()
Public Member Functions inherited from ListNode< Block * >
ListNode ()
ListNode (const ListNode &)=delete
ListNode (ListNode &&)=delete
virtual ~ListNode ()=default
ListNode & operator= (const ListNode &)=delete
ListNode & operator= (ListNode &&)=delete
void setSibling (Block *sibling)
const Block * getSibling ()
Protected Member Functions
List< Block * > & getChildren ()
void updateChildParams ()
void updateChildSubscriptions ()
void updateChildPublications ()
Protected Member Functions inherited from control::Block
virtual void updateParamsSubclass ()
SuperBlock * getParent ()
List< uORB::SubscriptionNode * > & getSubscriptions ()
List< uORB::PublicationNode * > & getPublications ()
List< BlockParamBase * > & getParams ()
Protected Attributes
List< Block * > _children
Protected Attributes inherited from control::Block
const char * _name
SuperBlock * _parent
float _dt {0.0f}
List< uORB::SubscriptionNode * > _subscriptions
List< uORB::PublicationNode * > _publications
List< BlockParamBase * > _params
Protected Attributes inherited from ListNode< Block * >
Block * _sibling
Friends
class Block
Detailed Description
Definition at line 103 of file Block.hpp.
Constructor & Destructor Documentation
control::SuperBlock::SuperBlock (SuperBlock * parent, const char * name) inline
Definition at line 109 of file Block.hpp.
References dt.
control::SuperBlock::~SuperBlock () default
control::SuperBlock::SuperBlock (const SuperBlock &) delete
control::SuperBlock::SuperBlock (SuperBlock &&) delete
Member Function Documentation
List<Block *>& control::SuperBlock::getChildren () inline protected
Definition at line 141 of file Block.hpp.
Referenced by control::Block::Block().
SuperBlock& control::SuperBlock::operator= (const SuperBlock &) delete
SuperBlock& control::SuperBlock::operator= (SuperBlock &&) delete
void control::SuperBlock::setDt (float dt) override virtual
Reimplemented from control::Block.
Definition at line 139 of file Block.cpp.
References control::blockNameLengthMax, control::Block::getName(), ListNode< T >::getSibling(), control::maxChildrenPerBlock, name, PX4_ERR, and control::Block::setDt().
Referenced by control::blockDerivativeTest(), blockDerivativeTest(), control::blockIntegralTest(), blockIntegralTest(), control::blockIntegralTrapTest(), blockIntegralTrapTest(), blockPDTest(), control::blockPDTest(), blockPIDTest(), control::blockPIDTest(), control::blockPITest(), blockPITest(), MulticopterPositionControl::task_main(), and BlockLocalPositionEstimator::update().
void control::SuperBlock::updateChildParams () protected
Definition at line 158 of file Block.cpp.
References control::blockNameLengthMax, control::Block::getName(), ListNode< T >::getSibling(), control::maxChildrenPerBlock, name, PX4_ERR, and control::Block::updateParams().
void control::SuperBlock::updateChildPublications () protected
Definition at line 194 of file Block.cpp.
References control::blockNameLengthMax, control::Block::getName(), ListNode< T >::getSibling(), control::maxChildrenPerBlock, name, PX4_ERR, and control::Block::updatePublications().
void control::SuperBlock::updateChildSubscriptions () protected
Definition at line 176 of file Block.cpp.
References control::blockNameLengthMax, control::Block::getName(), ListNode< T >::getSibling(), control::maxChildrenPerBlock, name, PX4_ERR, and control::Block::updateSubscriptions().
void control::SuperBlock::updateParams () inline override virtual
Reimplemented from control::Block.
Definition at line 120 of file Block.hpp.
References control::Block::updateParams().
void control::SuperBlock::updatePublications () inline override virtual
Reimplemented from control::Block.
Definition at line 133 of file Block.hpp.
References control::Block::updatePublications().
void control::SuperBlock::updateSubscriptions () inline override virtual
Reimplemented from control::Block.
Definition at line 127 of file Block.hpp.
References control::Block::updateSubscriptions().
Referenced by BlockLocalPositionEstimator::update().
Friends And Related Function Documentation
friend class Block friend
Definition at line 107 of file Block.hpp.
Member Data Documentation
List<Block *> control::SuperBlock::_children protected
Definition at line 146 of file Block.hpp.
The documentation for this class was generated from the following files:
src/lib/controllib/block/Block.hpp
src/lib/controllib/block/Block.cpp