PX4 Firmware: src/drivers/imu/mpu9250/main.cpp File Reference
main.cpp File Reference
#include <px4_config.h>
#include <sys/types.h>
#include <stdint.h>
#include <stdbool.h>
#include <stdlib.h>
#include <fcntl.h>
#include <errno.h>
#include <stdio.h>
#include <px4_getopt.h>
#include <perf/perf_counter.h>
#include <systemlib/err.h>
#include <systemlib/conversions.h>
#include <board_config.h>
#include <drivers/drv_hrt.h>
#include <drivers/device/spi.h>
#include <drivers/device/ringbuffer.h>
#include <drivers/device/integrator.h>
#include <drivers/drv_accel.h>
#include <drivers/drv_gyro.h>
#include <drivers/drv_mag.h>
#include <mathlib/math/filter/LowPassFilter2p.hpp>
#include <lib/conversion/rotation.h>
#include "mpu9250.h"
Classes
struct mpu9250::mpu9250_bus_option
Namespaces
mpu9250
Local functions in support of the shell command.
Macros
#define MPU_DEVICE_PATH_ACCEL "/dev/mpu9250_accel"
#define MPU_DEVICE_PATH_GYRO "/dev/mpu9250_gyro"
#define MPU_DEVICE_PATH_MAG "/dev/mpu9250_mag"
#define MPU_DEVICE_PATH_ACCEL_1 "/dev/mpu9250_accel1"
#define MPU_DEVICE_PATH_GYRO_1 "/dev/mpu9250_gyro1"
#define MPU_DEVICE_PATH_MAG_1 "/dev/mpu9250_mag1"
#define MPU_DEVICE_PATH_ACCEL_EXT "/dev/mpu9250_accel_ext"
#define MPU_DEVICE_PATH_GYRO_EXT "/dev/mpu9250_gyro_ext"
#define MPU_DEVICE_PATH_MAG_EXT "/dev/mpu9250_mag_ext"
#define MPU_DEVICE_PATH_ACCEL_EXT1 "/dev/mpu9250_accel_ext1"
#define MPU_DEVICE_PATH_GYRO_EXT1 "/dev/mpu9250_gyro_ext1"
#define MPU_DEVICE_PATH_MAG_EXT1 "/dev/mpu9250_mag_ext1"
#define MPU_DEVICE_PATH_ACCEL_EXT2 "/dev/mpu9250_accel_ext2"
#define MPU_DEVICE_PATH_GYRO_EXT2 "/dev/mpu9250_gyro_ext2"
#define MPU_DEVICE_PATH_MAG_EXT2 "/dev/mpu9250_mag_ext2"
#define NUM_BUS_OPTIONS (sizeof(bus_options)/sizeof(bus_options[0]))
Enumerations
enum MPU9250_BUS {
MPU9250_BUS_ALL = 0, MPU9250_BUS_I2C_INTERNAL, MPU9250_BUS_I2C_EXTERNAL, MPU9250_BUS_SPI_INTERNAL,
MPU9250_BUS_SPI_INTERNAL2, MPU9250_BUS_SPI_EXTERNAL
}
Functions
__EXPORT int mpu9250_main (int argc, char *argv[])
driver 'main' command
void mpu9250::start (enum MPU9250_BUS busid, enum Rotation rotation, bool external)
Start the driver.
bool mpu9250::start_bus (struct mpu9250_bus_option &bus, enum Rotation rotation, bool external)
start driver for a specific bus option
struct mpu9250_bus_option & mpu9250::find_bus (enum MPU9250_BUS busid)
find a bus structure for a busid
void mpu9250::stop (enum MPU9250_BUS busid)
void mpu9250::test (enum MPU9250_BUS busid)
Perform some basic functional tests on the driver; make sure we can collect data from the sensor in polled and automatic modes.
void mpu9250::reset (enum MPU9250_BUS busid)
Reset the driver.
void mpu9250::info (enum MPU9250_BUS busid)
Print a little info about the driver.
void mpu9250::regdump (enum MPU9250_BUS busid)
Dump the register information.
void mpu9250::testerror (enum MPU9250_BUS busid)
deliberately produce an error to test recovery
void mpu9250::usage ()
Prints info about the driver argument usage.
Variables
struct mpu9250::mpu9250_bus_option mpu9250::bus_options []
Macro Definition Documentation
#define MPU_DEVICE_PATH_ACCEL "/dev/mpu9250_accel"
Definition at line 74 of file main.cpp.
#define MPU_DEVICE_PATH_ACCEL_1 "/dev/mpu9250_accel1"
Definition at line 78 of file main.cpp.
#define MPU_DEVICE_PATH_ACCEL_EXT "/dev/mpu9250_accel_ext"
Definition at line 82 of file main.cpp.
#define MPU_DEVICE_PATH_ACCEL_EXT1 "/dev/mpu9250_accel_ext1"
Definition at line 86 of file main.cpp.
#define MPU_DEVICE_PATH_ACCEL_EXT2 "/dev/mpu9250_accel_ext2"
Definition at line 90 of file main.cpp.
#define MPU_DEVICE_PATH_GYRO "/dev/mpu9250_gyro"
Definition at line 75 of file main.cpp.
#define MPU_DEVICE_PATH_GYRO_1 "/dev/mpu9250_gyro1"
Definition at line 79 of file main.cpp.
#define MPU_DEVICE_PATH_GYRO_EXT "/dev/mpu9250_gyro_ext"
Definition at line 83 of file main.cpp.
#define MPU_DEVICE_PATH_GYRO_EXT1 "/dev/mpu9250_gyro_ext1"
Definition at line 87 of file main.cpp.
#define MPU_DEVICE_PATH_GYRO_EXT2 "/dev/mpu9250_gyro_ext2"
Definition at line 91 of file main.cpp.
#define MPU_DEVICE_PATH_MAG "/dev/mpu9250_mag"
Definition at line 76 of file main.cpp.
#define MPU_DEVICE_PATH_MAG_1 "/dev/mpu9250_mag1"
Definition at line 80 of file main.cpp.
#define MPU_DEVICE_PATH_MAG_EXT "/dev/mpu9250_mag_ext"
Definition at line 84 of file main.cpp.
#define MPU_DEVICE_PATH_MAG_EXT1 "/dev/mpu9250_mag_ext1"
Definition at line 88 of file main.cpp.
#define MPU_DEVICE_PATH_MAG_EXT2 "/dev/mpu9250_mag_ext2"
Definition at line 92 of file main.cpp.
#define NUM_BUS_OPTIONS (sizeof(bus_options)/sizeof(bus_options[0]))
Definition at line 154 of file main.cpp.
Referenced by mpu9250::find_bus(), and mpu9250::start().
Enumeration Type Documentation
enum MPU9250_BUS
Enumerator
MPU9250_BUS_ALL
MPU9250_BUS_I2C_INTERNAL
MPU9250_BUS_I2C_EXTERNAL
MPU9250_BUS_SPI_INTERNAL
MPU9250_BUS_SPI_INTERNAL2
MPU9250_BUS_SPI_EXTERNAL
Definition at line 98 of file main.cpp.
Function Documentation
int mpu9250_main (int argc, char * argv[])
driver 'main' command
Definition at line 494 of file main.cpp.
References mpu9250::mpu9250_bus_option::busid, mpu9250::info(), MPU9250_BUS_ALL, MPU9250_BUS_I2C_EXTERNAL, MPU9250_BUS_I2C_INTERNAL, MPU9250_BUS_SPI_EXTERNAL, MPU9250_BUS_SPI_INTERNAL, MPU9250_BUS_SPI_INTERNAL2, px4_getopt(), mpu9250::regdump(), mpu9250::reset(), ROTATION_NONE, mpu9250::start(), mpu9250::stop(), mpu9250::test(), mpu9250::testerror(), and mpu9250::usage().