PX4 Firmware: src/modules/commander/gyro_calibration.cpp File Reference
gyro_calibration.cpp File Reference
Gyroscope calibration routine.
#include <px4_config.h>
#include "gyro_calibration.h"
#include "calibration_messages.h"
#include "calibration_routines.h"
#include "commander_helper.h"
#include <px4_posix.h>
#include <px4_defines.h>
#include <px4_time.h>
#include <stdio.h>
#include <unistd.h>
#include <fcntl.h>
#include <poll.h>
#include <cmath>
#include <string.h>
#include <drivers/drv_hrt.h>
#include <uORB/topics/sensor_combined.h>
#include <uORB/topics/sensor_correction.h>
#include <drivers/drv_gyro.h>
#include <systemlib/mavlink_log.h>
#include <parameters/param.h>
#include <systemlib/err.h>
Classes
struct gyro_worker_data_t
Data passed to calibration worker routine.
Functions
static calibrate_return gyro_calibration_worker (int cancel_sub, void *data)
int do_gyro_calibration (orb_advert_t *mavlink_log_pub)
Variables
static const char * sensor_name = "gyro"
static const unsigned max_gyros = 3
Detailed Description
Gyroscope calibration routine.
Definition in file gyro_calibration.cpp.
Function Documentation
int do_gyro_calibration (orb_advert_t * mavlink_log_pub)
< sensor thermal corrections
Definition at line 208 of file gyro_calibration.cpp.
References CAL_ERROR_APPLY_CAL_MSG, CAL_ERROR_RESET_CAL_MSG, CAL_QGC_DONE_MSG, CAL_QGC_FAILED_MSG, CAL_QGC_STARTED_MSG, calibrate_cancel_subscribe(), calibrate_cancel_unsubscribe(), calibrate_return_cancelled, calibrate_return_error, calibration_log_critical, calibration_log_info, gyro_worker_data_t::device_id, device_id_primary, device_prio_max, fd, GYRO_BASE_DEVICE_PATH, gyro_calibration_worker(), sensor_correction_s::gyro_mapping, gyro_report, gyro_worker_data_t::gyro_report_0, gyro_worker_data_t::gyro_scale, gyro_worker_data_t::gyro_sensor_sub, GYROIOCSSCALE, gyro_worker_data_t::mavlink_log_pub, mavlink_log_pub, max_gyros, orb_copy(), orb_group_count(), ORB_ID, orb_priority(), orb_subscribe(), orb_subscribe_multi(), orb_unsubscribe(), param_find(), param_get(), param_notify_changes(), param_set_no_notification(), px4_close(), PX4_ERR, PX4_ERROR, px4_ioctl(), PX4_OK, px4_open(), gyro_worker_data_t::sensor_correction_sub, sensor_name, usleep(), gyro_calibration_s::x_offset, gyro_calibration_s::x_scale, gyro_calibration_s::y_offset, gyro_calibration_s::y_scale, gyro_calibration_s::z_offset, and gyro_calibration_s::z_scale.
Referenced by commander_low_prio_loop(), and commander_main().
static calibrate_return gyro_calibration_worker (int cancel_sub, void * data) static
< sensor thermal corrections
Definition at line 77 of file gyro_calibration.cpp.
References CAL_ERROR_SENSOR_MSG, CAL_QGC_PROGRESS_MSG, calibrate_cancel_check(), calibrate_return_cancelled, calibrate_return_error, calibrate_return_ok, calibration_log_critical, calibration_log_info, gyro_worker_data_t::device_id, sensor_correction_s::gyro_offset_0, sensor_correction_s::gyro_offset_1, sensor_correction_s::gyro_offset_2, gyro_report, gyro_worker_data_t::gyro_report_0, gyro_worker_data_t::gyro_scale, sensor_correction_s::gyro_scale_0, sensor_correction_s::gyro_scale_1, sensor_correction_s::gyro_scale_2, gyro_worker_data_t::gyro_sensor_sub, gyro_worker_data_t::mavlink_log_pub, max_gyros, orb_check(), orb_copy(), ORB_ID, px4_poll(), gyro_worker_data_t::sensor_correction_sub, gyro_calibration_s::x_offset, gyro_calibration_s::y_offset, and gyro_calibration_s::z_offset.
Referenced by do_gyro_calibration().
Variable Documentation
const unsigned max_gyros = 3 static
Definition at line 65 of file gyro_calibration.cpp.
Referenced by do_gyro_calibration(), and gyro_calibration_worker().
const char* sensor_name = "gyro" static
Definition at line 63 of file gyro_calibration.cpp.
Referenced by do_gyro_calibration().