PX4 Firmware: control::BlockLimit Class Reference
control::BlockLimit Class Reference
A limiter/ saturation.
#include <BlockLimit.hpp>
Public Member Functions
BlockLimit (SuperBlock *parent, const char *name)
virtual ~BlockLimit ()
float update (float input)
float getMin ()
float getMax ()
Public Member Functions inherited from control::Block
Block (SuperBlock *parent, const char *name)
virtual ~Block ()=default
Block (const Block &)=delete
Block & operator= (const Block &)=delete
Block (Block &&)=delete
Block & operator= (Block &&)=delete
void getName (char *name, size_t n)
virtual void updateParams ()
virtual void updateSubscriptions ()
virtual void updatePublications ()
virtual void setDt (float dt)
float getDt ()
Public Member Functions inherited from ListNode< Block * >
ListNode ()
ListNode (const ListNode &)=delete
ListNode (ListNode &&)=delete
virtual ~ListNode ()=default
ListNode & operator= (const ListNode &)=delete
ListNode & operator= (ListNode &&)=delete
void setSibling (Block *sibling)
const Block * getSibling ()
Protected Attributes
control::BlockParamFloat _min
control::BlockParamFloat _max
Protected Attributes inherited from control::Block
const char * _name
SuperBlock * _parent
float _dt {0.0f}
List< uORB::SubscriptionNode * > _subscriptions
List< uORB::PublicationNode * > _publications
List< BlockParamBase * > _params
Protected Attributes inherited from ListNode< Block * >
Block * _sibling
Additional Inherited Members
Protected Member Functions inherited from control::Block
virtual void updateParamsSubclass ()
SuperBlock * getParent ()
List< uORB::SubscriptionNode * > & getSubscriptions ()
List< uORB::PublicationNode * > & getPublications ()
List< BlockParamBase * > & getParams ()
Detailed Description
A limiter/ saturation.
The output of update is the input, bounded by min/max.
Definition at line 63 of file BlockLimit.hpp.
Constructor & Destructor Documentation
control::BlockLimit::BlockLimit (SuperBlock * parent, const char * name) inline
Definition at line 67 of file BlockLimit.hpp.
virtual control::BlockLimit::~BlockLimit () inline virtual
Definition at line 72 of file BlockLimit.hpp.
Member Function Documentation
float control::BlockLimit::getMax () inline
Definition at line 76 of file BlockLimit.hpp.
Referenced by control::blockLimitTest(), blockLimitTest(), and update().
float control::BlockLimit::getMin () inline
Definition at line 75 of file BlockLimit.hpp.
Referenced by control::blockLimitTest(), blockLimitTest(), and update().
float control::BlockLimit::update (float input)
Definition at line 48 of file BlockLimit.cpp.
References _max, control::BlockParam< T >::get(), getMax(), and getMin().
Referenced by control::blockLimitTest(), and blockLimitTest().
Member Data Documentation
control::BlockParamFloat control::BlockLimit::_max protected
Definition at line 80 of file BlockLimit.hpp.
Referenced by update().
control::BlockParamFloat control::BlockLimit::_min protected
Definition at line 79 of file BlockLimit.hpp.
The documentation for this class was generated from the following files:
src/lib/controllib/BlockLimit.hpp
src/lib/controllib/BlockLimit.cpp