PX4 Firmware: gyrosim Namespace Reference
gyrosim Namespace Reference
Local functions in support of the shell command.
Functions
int start (enum Rotation rotation)
Start the driver.
int stop ()
Stop the driver.
int test ()
Perform some basic functional tests on the driver; make sure we can collect data from the sensor in polled and automatic modes.
int reset ()
Reset the driver.
int info ()
Print a little info about the driver.
int regdump ()
Dump the register information.
void usage ()
Prints info about the driver argument usage.
Variables
GYROSIM * g_dev_sim
Detailed Description
Local functions in support of the shell command.
Function Documentation
int gyrosim::info ()
Print a little info about the driver.
Print a little info about the driver.
Definition at line 1304 of file gyrosim.cpp.
References g_dev_sim, PX4_ERR, and PX4_INFO.
Referenced by gyrosim_main().
int gyrosim::regdump (void)
Dump the register information.
Definition at line 1325 of file gyrosim.cpp.
References g_dev_sim, PX4_ERR, and PX4_INFO.
Referenced by gyrosim_main().
int gyrosim::reset ()
Reset the driver.
Reset the driver.
Definition at line 1273 of file gyrosim.cpp.
References ETS_PATH, fd, MPU_DEVICE_PATH_ACCEL, PX4_ERR, PX4_ERROR, px4_ioctl(), PX4_OK, px4_open(), SENSOR_POLLRATE_DEFAULT, SENSORIOCRESET, and SENSORIOCSPOLLRATE.
Referenced by gyrosim_main(), and test().
int gyrosim::start (enum Rotation rotation)
Start the driver.
This function only returns if the driver is up and running or failed to detect the sensor.
Definition at line 1117 of file gyrosim.cpp.
References g_dev_sim, GYROSIM_gyro::GYROSIM, MPU_DEVICE_PATH_ACCEL, MPU_DEVICE_PATH_GYRO, OK, PX4_WARN, SENSOR_POLLRATE_DEFAULT, and SENSORIOCSPOLLRATE.
Referenced by gyrosim_main().
int gyrosim::stop ()
Stop the driver.
Stop the driver.
Definition at line 1167 of file gyrosim.cpp.
References g_dev_sim, and PX4_WARN.
Referenced by gyrosim_main().
int gyrosim::test ()
Perform some basic functional tests on the driver; make sure we can collect data from the sensor in polled and automatic modes.
Definition at line 1189 of file gyrosim.cpp.
References accel_report, gyro_report, MPU_DEVICE_PATH_ACCEL, MPU_DEVICE_PATH_GYRO, PX4_ERR, PX4_INFO, PX4_WARN, reset(), SENSOR_POLLRATE_MANUAL, and SENSORIOCSPOLLRATE.
Referenced by gyrosim_main().
void gyrosim::usage (void)
Prints info about the driver argument usage.
Prints info about the driver argument usage.
Definition at line 1341 of file gyrosim.cpp.
References PX4_INFO.
Referenced by gyrosim_main().
Variable Documentation
GYROSIM* gyrosim::g_dev_sim
Definition at line 1100 of file gyrosim.cpp.
Referenced by info(), regdump(), start(), and stop().