PX4 Firmware: navio_sysfs_rc_in::RcInput Class Reference
navio_sysfs_rc_in::RcInput Class Reference
Public Member Functions
RcInput ()
~RcInput ()
int start ()
void stop ()
bool isRunning ()
Static Public Member Functions
static void cycle_trampoline (void *arg)
Private Member Functions
void _cycle ()
void _measure ()
int navio_rc_init ()
Private Attributes
bool _shouldExit
bool _isRunning
struct work_s _work
orb_advert_t _rcinput_pub
int _channels
int _ch_fd [input_rc_s::RC_INPUT_MAX_CHANNELS]
struct input_rc_s _data
Detailed Description
Definition at line 60 of file navio_sysfs_rc_in.cpp.
Constructor & Destructor Documentation
navio_sysfs_rc_in::RcInput::RcInput () inline
Definition at line 63 of file navio_sysfs_rc_in.cpp.
References _ch_fd, _channels, _data, and _rcinput_pub.
Referenced by navio_sysfs_rc_in::navio_sysfs_rc_in_main().
navio_sysfs_rc_in::RcInput::~RcInput () inline
Definition at line 73 of file navio_sysfs_rc_in.cpp.
References _isRunning, cycle_trampoline(), start(), and stop().
Member Function Documentation
void navio_sysfs_rc_in::RcInput::_cycle () private
Definition at line 170 of file navio_sysfs_rc_in.cpp.
References _measure(), _shouldExit, cycle_trampoline(), and RCINPUT_MEASURE_INTERVAL_US.
Referenced by cycle_trampoline(), and isRunning().
void navio_sysfs_rc_in::RcInput::_measure (void) private
Definition at line 180 of file navio_sysfs_rc_in.cpp.
References _ch_fd, _channels, _data, _rcinput_pub, input_rc_s::channel_count, hrt_absolute_time(), input_rc_s::input_source, ORB_ID, orb_publish(), input_rc_s::rc_failsafe, input_rc_s::rc_lost, input_rc_s::rc_lost_frame_count, input_rc_s::rc_ppm_frame_length, input_rc_s::rc_total_frame_count, input_rc_s::rssi, input_rc_s::timestamp, input_rc_s::timestamp_last_signal, navio_sysfs_rc_in::usage(), and input_rc_s::values.
Referenced by _cycle(), and isRunning().
void navio_sysfs_rc_in::RcInput::cycle_trampoline (void * arg) static
Definition at line 164 of file navio_sysfs_rc_in.cpp.
References _cycle().
Referenced by _cycle(), start(), and ~RcInput().
bool navio_sysfs_rc_in::RcInput::isRunning () inline
Definition at line 88 of file navio_sysfs_rc_in.cpp.
References _cycle(), _isRunning, and _measure().
Referenced by navio_sysfs_rc_in::navio_sysfs_rc_in_main().
int navio_sysfs_rc_in::RcInput::navio_rc_init () private
Definition at line 107 of file navio_sysfs_rc_in.cpp.
References _ch_fd, _channels, _data, _rcinput_pub, fd, orb_advertise(), ORB_ID, PX4_WARN, RCINPUT_DEVICE_PATH_BASE, and input_rc_s::values.
Referenced by start().
int navio_sysfs_rc_in::RcInput::start ()
Definition at line 138 of file navio_sysfs_rc_in.cpp.
References _isRunning, cycle_trampoline(), navio_rc_init(), and PX4_WARN.
Referenced by navio_sysfs_rc_in::navio_sysfs_rc_in_main(), and ~RcInput().
void navio_sysfs_rc_in::RcInput::stop ()
Definition at line 159 of file navio_sysfs_rc_in.cpp.
References _shouldExit.
Referenced by navio_sysfs_rc_in::navio_sysfs_rc_in_main(), and ~RcInput().
Member Data Documentation
int navio_sysfs_rc_in::RcInput::_ch_fd[input_rc_s::RC_INPUT_MAX_CHANNELS] private
Definition at line 101 of file navio_sysfs_rc_in.cpp.
Referenced by _measure(), navio_rc_init(), and RcInput().
int navio_sysfs_rc_in::RcInput::_channels private
Definition at line 100 of file navio_sysfs_rc_in.cpp.
Referenced by _measure(), navio_rc_init(), and RcInput().
struct input_rc_s navio_sysfs_rc_in::RcInput::_data private
Definition at line 102 of file navio_sysfs_rc_in.cpp.
Referenced by _measure(), navio_rc_init(), and RcInput().
bool navio_sysfs_rc_in::RcInput::_isRunning private
Definition at line 95 of file navio_sysfs_rc_in.cpp.
Referenced by isRunning(), start(), and ~RcInput().
orb_advert_t navio_sysfs_rc_in::RcInput::_rcinput_pub private
Definition at line 98 of file navio_sysfs_rc_in.cpp.
Referenced by _measure(), navio_rc_init(), and RcInput().
bool navio_sysfs_rc_in::RcInput::_shouldExit private
Definition at line 94 of file navio_sysfs_rc_in.cpp.
Referenced by _cycle(), and stop().
struct work_s navio_sysfs_rc_in::RcInput::_work private
Definition at line 96 of file navio_sysfs_rc_in.cpp.
The documentation for this class was generated from the following file:
src/drivers/navio_sysfs_rc_in/navio_sysfs_rc_in.cpp