PX4 Firmware: df_ltc2946_wrapper Namespace Reference
df_ltc2946_wrapper Namespace Reference
Functions
int start ()
Attempt to start driver on all available I2C busses.
int stop ()
Stop the driver.
int info ()
Print a little info about the driver.
void usage ()
Prints info about the driver argument usage.
Variables
DfLtc2946Wrapper * g_dev = nullptr
Function Documentation
int df_ltc2946_wrapper::info ()
Print a little info about the driver.
Print a little info about the driver.
Definition at line 212 of file df_ltc2946_wrapper.cpp.
References PX4_DEBUG, and PX4_ERR.
Referenced by df_ltc2946_wrapper_main().
int df_ltc2946_wrapper::start ()
Attempt to start driver on all available I2C busses.
This function will return as soon as the first sensor is detected on one of the available busses or if no sensors are detected.
Attempt to start driver on all available I2C busses.
Definition at line 166 of file df_ltc2946_wrapper.cpp.
References DfLtc2946Wrapper::DfLtc2946Wrapper(), PX4_ERR, PX4_INFO, PX4_WARN, and DfLtc2946Wrapper::start().
Referenced by df_ltc2946_wrapper_main().
int df_ltc2946_wrapper::stop ()
Stop the driver.
Stop the driver.
Definition at line 189 of file df_ltc2946_wrapper.cpp.
References g_dev, PX4_ERR, and DfLtc2946Wrapper::stop().
Referenced by df_ltc2946_wrapper_main().
void df_ltc2946_wrapper::usage (void)
Prints info about the driver argument usage.
Prints info about the driver argument usage.
Definition at line 225 of file df_ltc2946_wrapper.cpp.
References PX4_WARN.
Referenced by df_ltc2946_wrapper_main().
Variable Documentation
DfLtc2946Wrapper* df_ltc2946_wrapper::g_dev = nullptr
Definition at line 159 of file df_ltc2946_wrapper.cpp.
Referenced by stop().