PX4 Firmware: HelloExample Class Reference
HelloExample Class Reference
#include <hello_example.h>
Public Member Functions
HelloExample ()
~HelloExample ()
int main ()
HelloExample ()
~HelloExample ()
int main ()
Static Public Attributes
static px4::AppState appState
Detailed Description
Definition at line 44 of file hello_example.h.
Constructor & Destructor Documentation
HelloExample::HelloExample () inline
Definition at line 47 of file hello_example.h.
HelloExample::~HelloExample () inline
Definition at line 49 of file hello_example.h.
References main().
HelloExample::HelloExample () inline
Definition at line 47 of file hello_example.h.
HelloExample::~HelloExample () inline
Definition at line 49 of file hello_example.h.
References appState, and main().
Member Function Documentation
int HelloExample::main ()
Definition at line 48 of file hello_example.cpp.
References appState, px4::AppState::exitRequested(), and px4::AppState::setRunning().
Referenced by PX4_MAIN(), and ~HelloExample().
int HelloExample::main ()
Member Data Documentation
static px4::AppState HelloExample::appState static
Definition at line 53 of file hello_example.h.
Referenced by hello_main(), main(), and ~HelloExample().
The documentation for this class was generated from the following files:
src/platforms/posix/tests/hello/hello_example.h
src/platforms/posix/tests/hello/hello_example.cpp