PX4 Firmware: do_not_explicitly_use_this_namespace::Param< float &, p > Class Template Reference
do_not_explicitly_use_this_namespace::Param< float &, p > Class Template Reference
#include <px4_param.h>
Public Member Functions
Param (float &external_val)
float get () const
const float & reference () const
bool commit () const
Store the parameter value to the parameter storage (.
bool commit_no_notification () const
Store the parameter value to the parameter storage, w/o notifying the system (.
void set (float val)
bool update ()
param_t handle () const
Private Attributes
float & _val
Detailed Description
template<px4::params p>
class do_not_explicitly_use_this_namespace::Param< float &, p >
Definition at line 144 of file px4_param.h.
Constructor & Destructor Documentation
template<px4::params p> do_not_explicitly_use_this_namespace::Param< float &, p >::Param (float & external_val) inline
Definition at line 150 of file px4_param.h.
References param_set_used().
Member Function Documentation
template<px4::params p> bool do_not_explicitly_use_this_namespace::Param< float &, p >::commit () const inline
Store the parameter value to the parameter storage (.
See also
param_set())
Definition at line 162 of file px4_param.h.
References param_set().
template<px4::params p> bool do_not_explicitly_use_this_namespace::Param< float &, p >::commit_no_notification () const inline
Store the parameter value to the parameter storage, w/o notifying the system (.
See also
param_set_no_notification())
Definition at line 165 of file px4_param.h.
References param_set_no_notification().
template<px4::params p> float do_not_explicitly_use_this_namespace::Param< float &, p >::get () const inline
Definition at line 157 of file px4_param.h.
template<px4::params p> param_t do_not_explicitly_use_this_namespace::Param< float &, p >::handle () const inline
Definition at line 171 of file px4_param.h.
References param_handle().
template<px4::params p> const float& do_not_explicitly_use_this_namespace::Param< float &, p >::reference () const inline
Definition at line 159 of file px4_param.h.
template<px4::params p> void do_not_explicitly_use_this_namespace::Param< float &, p >::set (float val) inline
Definition at line 167 of file px4_param.h.
template<px4::params p> bool do_not_explicitly_use_this_namespace::Param< float &, p >::update () inline
Definition at line 169 of file px4_param.h.
References param_get().
Member Data Documentation
template<px4::params p> float& do_not_explicitly_use_this_namespace::Param< float &, p >::_val private
Definition at line 173 of file px4_param.h.
The documentation for this class was generated from the following file:
src/platforms/px4_param.h