PX4 Firmware: bmm150 Namespace Reference
bmm150 Namespace Reference
Functions
void start (bool external_bus, enum Rotation rotation)
Start the driver.
void test (bool)
void reset (bool)
void info (bool)
void regdump (bool external_bus)
Dump the register information.
void usage ()
Prints info about the driver argument usage.
Variables
BMM150 * g_dev_ext
BMM150 * g_dev_int
Function Documentation
void bmm150::info (bool external_bus)
Definition at line 202 of file bmm150.cpp.
References g_dev_int, and PX4_ERR.
Referenced by bmm150_main().
void bmm150::regdump (bool external_bus)
Dump the register information.
Definition at line 222 of file bmm150.cpp.
References g_dev_int, and PX4_ERR.
Referenced by bmm150_main().
void bmm150::reset (bool external_bus)
Definition at line 177 of file bmm150.cpp.
References BMM150_DEVICE_PATH_MAG, BMM150_DEVICE_PATH_MAG_EXT, fd, path, PX4_ERR, SENSOR_POLLRATE_DEFAULT, SENSORIOCRESET, and SENSORIOCSPOLLRATE.
Referenced by bmm150_main().
void bmm150::start (bool external_bus, enum Rotation rotation)
Start the driver.
This function only returns if the driver is up and running or failed to detect the sensor.
Definition at line 66 of file bmm150.cpp.
References BMM150_DEVICE_PATH_MAG, BMM150_DEVICE_PATH_MAG_EXT, fd, g_dev_int, OK, path, PX4_ERR, PX4_I2C_BUS_EXPANSION, SENSOR_POLLRATE_DEFAULT, and SENSORIOCSPOLLRATE.
Referenced by bmm150_main().
void bmm150::test (bool external_bus)
Definition at line 130 of file bmm150.cpp.
References BMM150_DEVICE_PATH_MAG, BMM150_DEVICE_PATH_MAG_EXT, fd, mag_report, path, PX4_ERR, PX4_WARN, read(), SENSOR_POLLRATE_MAX, and SENSORIOCSPOLLRATE.
Referenced by bmm150_main().
void bmm150::usage (void)
Prints info about the driver argument usage.
Prints info about the driver argument usage.
Definition at line 238 of file bmm150.cpp.
References PX4_WARN.
Referenced by bmm150_main().
Variable Documentation
BMM150* bmm150::g_dev_ext
Definition at line 49 of file bmm150.cpp.
BMM150* bmm150::g_dev_int
Definition at line 50 of file bmm150.cpp.
Referenced by info(), regdump(), and start().