PX4 Firmware: src/drivers/imu/bmi160/bmi160_main.cpp File Reference
bmi160_main.cpp File Reference
#include "bmi160.hpp"
Namespaces
bmi160
Local functions in support of the shell command.
Functions
__EXPORT int bmi160_main (int argc, char *argv[])
driver 'main' command
void bmi160::start (bool external_bus, enum Rotation rotation)
Start the driver.
void bmi160::stop (bool)
void bmi160::info (bool external_bus)
Print a little info about the driver.
void bmi160::regdump (bool external_bus)
Dump the register information.
void bmi160::testerror (bool external_bus)
deliberately produce an error to test recovery
void bmi160::usage ()
Prints info about the driver argument usage.
Variables
BMI160 * bmi160::g_dev_int
BMI160 * bmi160::g_dev_ext
Function Documentation
bmi160_main()
int bmi160_main (int argc, char * argv[])
driver 'main' command
Definition at line 191 of file bmi160_main.cpp.
References bmi160::info(), bmi160::regdump(), ROTATION_NONE, bmi160::start(), bmi160::stop(), bmi160::testerror(), and bmi160::usage().