PX4 Firmware: LSM303D_mag Class Reference
LSM303D_mag Class Reference
Helper class implementing the mag driver node.
Public Member Functions
LSM303D_mag (LSM303D *parent)
~LSM303D_mag ()
virtual ssize_t read (struct file *filp, char *buffer, size_t buflen)
virtual int ioctl (struct file *filp, int cmd, unsigned long arg)
virtual int init ()
Initialise the driver and make it ready for use.
Public Member Functions inherited from device::CDev
CDev (const char *name, const char *devname)
Constructor.
virtual ~CDev ()
virtual int open (file_t *filep)
Handle an open of the device.
virtual int close (file_t *filep)
Handle a close of the device.
virtual ssize_t read (file_t *filep, char *buffer, size_t buflen)
Perform a read from the device.
virtual ssize_t write (file_t *filep, const char *buffer, size_t buflen)
Perform a write to the device.
virtual off_t seek (file_t *filep, off_t offset, int whence)
Perform a logical seek operation on the device.
virtual int ioctl (file_t *filep, int cmd, unsigned long arg)
Perform an ioctl operation on the device.
virtual int poll (file_t *filep, px4_pollfd_struct_t *fds, bool setup)
Perform a poll setup/teardown operation.
Public Member Functions inherited from device::Device
virtual ~Device ()=default
Destructor.
virtual int read (unsigned address, void *data, unsigned count)
Read directly from the device.
virtual int write (unsigned address, void *data, unsigned count)
Write directly to the device.
virtual int ioctl (unsigned operation, unsigned &arg)
Perform a device-specific operation.
uint8_t get_device_bus ()
Return the bus ID the device is connected to.
DeviceBusType get_device_bus_type ()
Return the bus type the device is connected to.
uint8_t get_device_address ()
Return the bus address of the device.
void set_device_address (int address)
void set_device_type (uint8_t devtype)
Set the device type.
virtual bool external ()
Protected Member Functions
void parent_poll_notify ()
Protected Member Functions inherited from device::CDev
virtual pollevent_t poll_state (file_t *filep)
Check the current state of the device for poll events from the perspective of the file.
virtual void poll_notify (pollevent_t events)
Report new poll events.
virtual void poll_notify_one (px4_pollfd_struct_t *fds, pollevent_t events)
Internal implementation of poll_notify.
virtual int open_first (file_t *filep)
Notification of the first open.
virtual int close_last (file_t *filep)
Notification of the last close.
virtual int register_class_devname (const char *class_devname)
Register a class device name, automatically adding device class instance suffix if need be.
virtual int unregister_class_devname (const char *class_devname, unsigned class_instance)
Register a class device name, automatically adding device class instance suffix if need be.
const char * get_devname ()
Get the device name.
void lock ()
Take the driver lock.
void unlock ()
Release the driver lock.
Protected Member Functions inherited from device::Device
Device (const char *name)
Device (DeviceBusType bus_type, uint8_t bus, uint8_t address, uint8_t devtype=0)
Device (const Device &)=delete
Device & operator= (const Device &)=delete
Device (Device &&)=delete
Device & operator= (Device &&)=delete
Private Member Functions
void measure ()
void measure_trampoline (void *arg)
LSM303D_mag (const LSM303D_mag &)
LSM303D_mag operator= (const LSM303D_mag &)
Private Attributes
LSM303D * _parent
orb_advert_t _mag_topic
int _mag_orb_class_instance
int _mag_class_instance
Friends
class LSM303D
Additional Inherited Members
Public Types inherited from device::Device
enum DeviceBusType { DeviceBusType_UNKNOWN = 0, DeviceBusType_I2C = 1, DeviceBusType_SPI = 2, DeviceBusType_UAVCAN = 3 }
Device bus types for DEVID.
Protected Attributes inherited from device::CDev
px4_sem_t _lock
lock to protect access to all class members (also for derived classes)
bool _pub_blocked {false}
true if publishing should be blocked
Protected Attributes inherited from device::Device
union DeviceId _device_id
device identifier information
const char * _name
driver name
bool _debug_enabled {false}
if true, debug messages are printed
Static Protected Attributes inherited from device::CDev
static const px4_file_operations_t fops = {}
Pointer to the default cdev file operations table; useful for registering clone devices etc.
Detailed Description
Helper class implementing the mag driver node.
Definition at line 487 of file lsm303d.cpp.
Constructor & Destructor Documentation
LSM303D_mag::LSM303D_mag (LSM303D * parent)
Definition at line 1708 of file lsm303d.cpp.
LSM303D_mag::~LSM303D_mag ()
Definition at line 1717 of file lsm303d.cpp.
References _mag_class_instance, MAG_BASE_DEVICE_PATH, and device::CDev::unregister_class_devname().
LSM303D_mag::LSM303D_mag (const LSM303D_mag &) private
Member Function Documentation
int LSM303D_mag::init () virtual
Initialise the driver and make it ready for use.
Returns
OK if the driver initialized OK, negative errno otherwise;
Reimplemented from device::CDev.
Definition at line 1725 of file lsm303d.cpp.
References _mag_class_instance, lis3mdl::init(), MAG_BASE_DEVICE_PATH, OK, and device::CDev::register_class_devname().
Referenced by LSM303D::init().
int LSM303D_mag::ioctl (struct file * filp, int cmd, unsigned long arg) virtual
Definition at line 1754 of file lsm303d.cpp.
References _parent, and LSM303D::mag_ioctl().
Referenced by lsm303d::reset(), lsm303d::start(), and lsm303d::test().
void LSM303D_mag::measure () private
Definition at line 1767 of file lsm303d.cpp.
References _parent, and LSM303D::mag_measure().
Referenced by LSM303D::mag_read().
void LSM303D_mag::measure_trampoline (void * arg) private
Definition at line 1773 of file lsm303d.cpp.
References _parent, and LSM303D::mag_measure_trampoline().
LSM303D_mag LSM303D_mag::operator= (const LSM303D_mag &) private
void LSM303D_mag::parent_poll_notify () protected
Definition at line 1742 of file lsm303d.cpp.
References device::CDev::poll_notify().
ssize_t LSM303D_mag::read (struct file * filp, char * buffer, size_t buflen) virtual
Definition at line 1748 of file lsm303d.cpp.
References _parent, and LSM303D::mag_read().
Referenced by lsm303d::test().
Friends And Related Function Documentation
friend class LSM303D friend
Definition at line 499 of file lsm303d.cpp.
Referenced by lsm303d::start().
Member Data Documentation
int LSM303D_mag::_mag_class_instance private
Definition at line 507 of file lsm303d.cpp.
Referenced by init(), and ~LSM303D_mag().
int LSM303D_mag::_mag_orb_class_instance private
Definition at line 506 of file lsm303d.cpp.
Referenced by LSM303D::init().
orb_advert_t LSM303D_mag::_mag_topic private
Definition at line 505 of file lsm303d.cpp.
Referenced by LSM303D::init(), and LSM303D::mag_measure().
LSM303D* LSM303D_mag::_parent private
Definition at line 503 of file lsm303d.cpp.
Referenced by ioctl(), measure(), measure_trampoline(), and read().
The documentation for this class was generated from the following file:
src/drivers/imu/lsm303d/lsm303d.cpp