PX4 Firmware: src/lib/mathlib/math/matrix_alg.h File Reference
matrix_alg.h File Reference
Matrix algebra on raw arrays.
#include <inttypes.h>
#include <string.h>
#include <math.h>
Functions
float * mat_mul (float *A, float *B, uint8_t n)
bool mat_inverse (float *A, float *inv, uint8_t n)
bool inverse4x4 (float m[], float invOut[])
Detailed Description
Matrix algebra on raw arrays.
Definition in file matrix_alg.h.
Function Documentation
inverse4x4()
bool inverse4x4 (float m[], float invOut[])
Definition at line 260 of file matrix_alg.cpp.
mat_inverse()
bool mat_inverse (float * A, float * inv, uint8_t n)
Definition at line 215 of file matrix_alg.cpp.
mat_mul()
float* mat_mul (float * A, float * B, uint8_t n)
Definition at line 53 of file matrix_alg.cpp.
References f().
Referenced by mat_inverse(), and mat_LU_decompose().