PX4 Firmware: src/drivers/optical_flow/paw3902/paw3902_main.cpp File Reference
paw3902_main.cpp File Reference
#include "PAW3902.hpp"
Namespaces
pmw3902
Local functions in support of the shell command.
Functions
void pmw3902::start (int spi_bus)
Start the driver.
void pmw3902::stop ()
Stop the driver.
void pmw3902::test ()
Perform some basic functional tests on the driver; make sure we can collect data from the sensor in polled and automatic modes.
void pmw3902::reset ()
Reset the driver.
void pmw3902::info ()
Print a little info about the driver.
void pmw3902::usage ()
Print a little info about how to start/stop/use the driver.
__EXPORT int paw3902_main (int argc, char *argv[])
Variables
PAW3902 * pmw3902::g_dev
Function Documentation
paw3902_main()
int paw3902_main (int argc, char * argv[])
Definition at line 134 of file paw3902_main.cpp.
References pmw3902::info(), pmw3902::start(), pmw3902::stop(), and pmw3902::usage().
Referenced by pmw3902::usage().