PX4 Firmware: src/drivers/distance_sensor/sf0x/sf0x.cpp File Reference
sf0x.cpp File Reference
#include <px4_platform_common/px4_config.h>
#include <px4_platform_common/getopt.h>
#include <px4_platform_common/px4_work_queue/ScheduledWorkItem.hpp>
#include <sys/types.h>
#include <stdint.h>
#include <stdlib.h>
#include <stdbool.h>
#include <semaphore.h>
#include <string.h>
#include <fcntl.h>
#include <poll.h>
#include <errno.h>
#include <stdio.h>
#include <math.h>
#include <unistd.h>
#include <termios.h>
#include <perf/perf_counter.h>
#include <drivers/drv_hrt.h>
#include <drivers/drv_range_finder.h>
#include <drivers/device/device.h>
#include <drivers/device/ringbuffer.h>
#include <lib/parameters/param.h>
#include <uORB/uORB.h>
#include <uORB/topics/distance_sensor.h>
#include "sf0x_parser.h"
Classes
class SF0X
Namespaces
sf0x
Local functions in support of the shell command.
Macros
#define SF0X_TAKE_RANGE_REG 'd'
#define SF0X_DEFAULT_PORT "/dev/ttyS6"
Functions
__EXPORT int sf0x_main (int argc, char *argv[])
int sf0x::start (const char *port, uint8_t rotation)
Start the driver.
int sf0x::stop ()
Stop the driver.
int sf0x::test ()
Perform some basic functional tests on the driver; make sure we can collect data from the sensor in polled and automatic modes.
int sf0x::reset ()
Reset the driver.
int sf0x::info ()
Print a little info about the driver.
Variables
SF0X * sf0x::g_dev
Detailed Description
Author
Lorenz Meier lm@in.nosp@m.f.et.nosp@m.hz.ch
Greg Hulands
Driver for the Lightware SF0x laser rangefinder series
Definition in file sf0x.cpp.
Macro Definition Documentation
SF0X_DEFAULT_PORT
#define SF0X_DEFAULT_PORT "/dev/ttyS6"
Definition at line 78 of file sf0x.cpp.
Referenced by sf0x_main().
SF0X_TAKE_RANGE_REG
#define SF0X_TAKE_RANGE_REG 'd'
Definition at line 75 of file sf0x.cpp.
Referenced by SF0X::measure().
Function Documentation
sf0x_main()
int sf0x_main (int argc, char * argv[])
Definition at line 859 of file sf0x.cpp.
References sf0x::info(), sf0x::reset(), SF0X_DEFAULT_PORT, sf0x::start(), sf0x::stop(), and sf0x::test().