PX4 Firmware: StreamListItem Class Reference
StreamListItem Class Reference
#include <mavlink_messages.h>
Public Member Functions
StreamListItem (MavlinkStream *(*inst)(Mavlink *mavlink), const char *(*name)(), uint16_t(*id)())
Public Attributes
MavlinkStream *(* new_instance)(Mavlink *mavlink)
const char *(* get_name)()
uint16_t(* get_id)()
Detailed Description
Definition at line 46 of file mavlink_messages.h.
Constructor & Destructor Documentation
StreamListItem::StreamListItem (MavlinkStream *(*)(Mavlink *mavlink) inst, const char *(*)() name, uint16_t(*)() id) inline
Definition at line 54 of file mavlink_messages.h.
References create_mavlink_stream(), get_mavlink_navigation_mode(), get_stream_name(), and status.
Member Data Documentation
uint16_t(* StreamListItem::get_id) ()
Definition at line 52 of file mavlink_messages.h.
const char*(* StreamListItem::get_name) ()
Definition at line 51 of file mavlink_messages.h.
MavlinkStream*(* StreamListItem::new_instance) (Mavlink *mavlink)
Definition at line 50 of file mavlink_messages.h.
The documentation for this class was generated from the following file:
src/modules/mavlink/mavlink_messages.h