PX4 Firmware: CDevExample Class Reference
CDevExample Class Reference
#include <cdevtest_example.h>
Public Member Functions
CDevExample ()
~CDevExample ()
int main ()
Static Public Attributes
static px4::AppState appState
Private Member Functions
int do_poll (int fd, int timeout, int iterations, int delayms_after_poll)
Private Attributes
CDevNode * _node
Detailed Description
Definition at line 46 of file cdevtest_example.h.
Constructor & Destructor Documentation
CDevExample()
CDevExample::CDevExample () inline
Definition at line 49 of file cdevtest_example.h.
References main(), and ~CDevExample().
~CDevExample()
CDevExample::~CDevExample ()
Definition at line 186 of file cdevtest_example.cpp.
Referenced by CDevExample().
Member Function Documentation
do_poll()
int CDevExample::do_poll (int fd, int timeout, int iterations, int delayms_after_poll) private
Definition at line 194 of file cdevtest_example.cpp.
References fd, px4_poll(), and px4_read().
main()
int CDevExample::main ()
Definition at line 247 of file cdevtest_example.cpp.
References fd, g_exit, px4_close(), px4_open(), TESTDEV, and writer_main().
Referenced by CDevExample(), and PX4_MAIN().
Member Data Documentation
_node
CDevNode* CDevExample::_node private
Definition at line 60 of file cdevtest_example.h.
appState
px4::AppState CDevExample::appState static
Definition at line 55 of file cdevtest_example.h.
Referenced by cdev_test_main().
The documentation for this class was generated from the following files:
src/lib/cdev/test/cdevtest_example.h
src/lib/cdev/test/cdevtest_example.cpp