PX4 Firmware: uavcan_kinetis::CanIface Class Reference
uavcan_kinetis::CanIface Class Reference
Single CAN iface.
#include <can.hpp>
Classes
class RxQueue
struct Timings
struct TxItem
Public Types
enum { MaxRxQueueCapacity = 254 }
enum OperatingMode { NormalMode, SilentMode }
Public Member Functions
CanIface (flexcan::CanType *can, BusEvent &update_event, uavcan::uint8_t self_index, CanRxItem *rx_queue_buffer, uavcan::uint8_t rx_queue_capacity)
int init (const uavcan::uint32_t bitrate, const OperatingMode mode)
Initializes the hardware CAN controller.
void handleTxInterrupt (uavcan::uint32_t tx_iflags, uavcan::uint64_t utc_usec)
void handleRxInterrupt (uavcan::uint32_t rx_iflags, uavcan::uint64_t utc_usec)
void pollErrorFlagsFromISR ()
This method is used to count errors and abort transmission on error if necessary.
void discardTimedOutTxMailboxes (uavcan::MonotonicTime current_time)
bool canAcceptNewTxFrame (const uavcan::CanFrame &frame) const
bool isRxBufferEmpty () const
uavcan::uint32_t getRxQueueOverflowCount () const
Number of RX frames lost due to queue overflow.
virtual uavcan::uint64_t getErrorCount () const
Total number of hardware failures and other kinds of errors (e.g.
uavcan::uint32_t getVoluntaryTxAbortCount () const
Number of times the driver exercised library's requirement to abort transmission on first error.
unsigned getRxQueueLength () const
Returns the number of frames pending in the RX queue.
bool hadActivity ()
Whether this iface had at least one successful IO since the previous call of this method.
uavcan::uint8_t getPeakNumTxMailboxesUsed () const
Peak number of TX mailboxes used concurrently since initialization.
Private Types
enum { NumTxMesgBuffers = 6 }
enum { NumFilters = 16 }
Private Member Functions
int computeTimings (uavcan::uint32_t target_bitrate, Timings &out_timings)
virtual uavcan::int16_t send (const uavcan::CanFrame &frame, uavcan::MonotonicTime tx_deadline, uavcan::CanIOFlags flags)
virtual uavcan::int16_t receive (uavcan::CanFrame &out_frame, uavcan::MonotonicTime &out_ts_monotonic, uavcan::UtcTime &out_ts_utc, uavcan::CanIOFlags &out_flags)
virtual uavcan::int16_t configureFilters (const uavcan::CanFilterConfig *filter_configs, uavcan::uint16_t num_configs)
virtual uavcan::uint16_t getNumFilters () const
void handleTxMailboxInterrupt (uavcan::uint8_t mailbox_index, bool txok, uavcan::uint64_t utc_usec)
bool waitMCRChange (uavcan::uint32_t mask, bool target_state)
void setMCR (uavcan::uint32_t mask, bool target_state)
bool setEnable (bool enable_true)
uavcan::int16_t doReset (Timings timings)
bool waitFreezeAckChange (bool target_state)
void setFreeze (bool freeze_true)
Private Attributes
const uavcan::uint32_t FIFO_IFLAG1 = flexcan::CAN_FIFO_NE | flexcan::CAN_FIFO_WARN | flexcan::CAN_FIFO_OV
uavcan::uint8_t MaxMB
RxQueue rx_queue_
flexcan::CanType *const can_
uavcan::uint64_t error_cnt_
uavcan::uint64_t fifo_warn_cnt_
uavcan::uint32_t pending_aborts_
uavcan::uint32_t served_aborts_cnt_
BusEvent & update_event_
TxItem pending_tx_ [NumTxMesgBuffers]
uavcan::uint8_t peak_tx_mailbox_index_
const uavcan::uint8_t self_index_
bool had_activity_
Detailed Description
Single CAN iface.
The application shall not use this directly.
Definition at line 50 of file can.hpp.
Member Enumeration Documentation
anonymous enum
anonymous enum private
Enumerator
NumTxMesgBuffers
Definition at line 123 of file can.hpp.
anonymous enum
anonymous enum private
Enumerator
NumFilters
Definition at line 124 of file can.hpp.
anonymous enum
anonymous enum
Enumerator
MaxRxQueueCapacity
Definition at line 167 of file can.hpp.
OperatingMode
enum uavcan_kinetis::CanIface::OperatingMode
Enumerator
NormalMode
SilentMode
Definition at line 169 of file can.hpp.
Constructor & Destructor Documentation
CanIface()
uavcan_kinetis::CanIface::CanIface (flexcan::CanType * can, BusEvent & update_event, uavcan::uint8_t self_index, CanRxItem * rx_queue_buffer, uavcan::uint8_t rx_queue_capacity) inline
Definition at line 174 of file can.hpp.
References uavcan_kinetis::CanRxItem::frame, and ToneAlarmInterface::init().
Member Function Documentation
canAcceptNewTxFrame()
bool uavcan_kinetis::CanIface::canAcceptNewTxFrame (const uavcan::CanFrame & frame) const
Definition at line 758 of file uc_kinetis_flexcan.cpp.
References uavcan_kinetis::flexcan::ESR2_IMB, uavcan_kinetis::flexcan::ESR2_VPS, and MicroBenchHRT::lock().
computeTimings()
int uavcan_kinetis::CanIface::computeTimings (uavcan::uint32_t target_bitrate, Timings & out_timings) private
Definition at line 138 of file uc_kinetis_flexcan.cpp.
References uavcan_kinetis::flexcan::canclk, uavcan_kinetis::ErrInvalidBitRate, math::min(), uavcan_kinetis::CanIface::Timings::prescaler, uavcan_kinetis::CanIface::Timings::propseg, uavcan_kinetis::CanIface::Timings::pseg1, uavcan_kinetis::CanIface::Timings::pseg2, and uavcan_kinetis::CanIface::Timings::rjw.
configureFilters()
uavcan::int16_t uavcan_kinetis::CanIface::configureFilters (const uavcan::CanFilterConfig * filter_configs, uavcan::uint16_t num_configs) private virtual
Definition at line 318 of file uc_kinetis_flexcan.cpp.
References uavcan_kinetis::ErrFilterNumConfigs, uavcan_kinetis::ErrMcrFRZACKAckNotCleared, uavcan_kinetis::ErrMcrFRZACKAckNotSet, uavcan_kinetis::flexcan::FilterType::ext, uavcan_kinetis::flexcan::FirstFilter, uavcan_kinetis::flexcan::FilterType::ide, MicroBenchHRT::lock(), uavcan_kinetis::flexcan::FilterType::rtr, uavcan_kinetis::flexcan::FilterType::std, and uavcan_kinetis::flexcan::FilterType::w.
discardTimedOutTxMailboxes()
void uavcan_kinetis::CanIface::discardTimedOutTxMailboxes (uavcan::MonotonicTime current_time)
Definition at line 743 of file uc_kinetis_flexcan.cpp.
References uavcan_kinetis::CanIface::TxItem::deadline, MicroBenchHRT::lock(), uavcan_kinetis::flexcan::NumMBinFiFoAndFilters, uavcan_kinetis::CanIface::TxItem::pending, and uavcan_kinetis::flexcan::TxMbAbort.
doReset()
uavcan::int16_t uavcan_kinetis::CanIface::doReset (Timings timings) private
Definition at line 441 of file uc_kinetis_flexcan.cpp.
References uavcan_kinetis::flexcan::busclck, uavcan_kinetis::flexcan::canclk, uavcan_kinetis::flexcan::CTRL2_EACEN, uavcan_kinetis::flexcan::CTRL2_RRS, uavcan_kinetis::flexcan::CTRL2_TASD_MASK, uavcan_kinetis::flexcan::CTRL2_TASD_SHIFT, uavcan_kinetis::ErrMcrSOFTRSTNotCleared, uavcan_kinetis::flexcan::HWMaxMB, uavcan_kinetis::flexcan::MCR_AEN, uavcan_kinetis::flexcan::MCR_IRMQ, uavcan_kinetis::flexcan::MCR_MAXMB_MASK, uavcan_kinetis::flexcan::MCR_MAXMB_SHIFT, uavcan_kinetis::flexcan::MCR_RFEN, uavcan_kinetis::flexcan::MCR_SLFWAK, uavcan_kinetis::flexcan::MCR_SOFTRST, uavcan_kinetis::flexcan::MCR_SRXDIS, uavcan_kinetis::flexcan::MCR_SUPV, uavcan_kinetis::flexcan::MCR_WAKSRC, uavcan_kinetis::flexcan::MCR_WRNEN, uavcan_kinetis::flexcan::numberFIFOFilters, uavcan_kinetis::CanIface::Timings::prescaler, uavcan_kinetis::CanIface::Timings::propseg, uavcan_kinetis::CanIface::Timings::pseg1, uavcan_kinetis::CanIface::Timings::pseg2, and uavcan_kinetis::flexcan::useFIFO.
getErrorCount()
uavcan::uint64_t uavcan_kinetis::CanIface::getErrorCount () const virtual
Total number of hardware failures and other kinds of errors (e.g.
queue overruns). May increase continuously if the interface is not connected to the bus.
Definition at line 793 of file uc_kinetis_flexcan.cpp.
References MicroBenchHRT::lock().
getNumFilters()
virtual uavcan::uint16_t uavcan_kinetis::CanIface::getNumFilters () const inline private virtual
Definition at line 151 of file can.hpp.
References uavcan_kinetis::CanRxItem::utc_usec.
getPeakNumTxMailboxesUsed()
uavcan::uint8_t uavcan_kinetis::CanIface::getPeakNumTxMailboxesUsed () const inline
Peak number of TX mailboxes used concurrently since initialization.
Range is [1, 3]. Value of 3 suggests that priority inversion could be taking place.
Definition at line 259 of file can.hpp.
getRxQueueLength()
unsigned uavcan_kinetis::CanIface::getRxQueueLength () const
Returns the number of frames pending in the RX queue.
This is intended for debug use only.
Definition at line 799 of file uc_kinetis_flexcan.cpp.
References MicroBenchHRT::lock().
getRxQueueOverflowCount()
uavcan::uint32_t uavcan_kinetis::CanIface::getRxQueueOverflowCount () const inline
Number of RX frames lost due to queue overflow.
This is an atomic read, it doesn't require a critical section.
Definition at line 221 of file can.hpp.
References uavcan_kinetis::CanIface::RxQueue::getOverflowCount().
getVoluntaryTxAbortCount()
uavcan::uint32_t uavcan_kinetis::CanIface::getVoluntaryTxAbortCount () const inline
Number of times the driver exercised library's requirement to abort transmission on first error.
This is an atomic read, it doesn't require a critical section. See uavcan::CanIOFlagAbortOnError.
Definition at line 237 of file can.hpp.
hadActivity()
bool uavcan_kinetis::CanIface::hadActivity ()
Whether this iface had at least one successful IO since the previous call of this method.
This is designed for use with iface activity LEDs.
Definition at line 805 of file uc_kinetis_flexcan.cpp.
References MicroBenchHRT::lock().
handleRxInterrupt()
void uavcan_kinetis::CanIface::handleRxInterrupt (uavcan::uint32_t rx_iflags, uavcan::uint64_t utc_usec)
Definition at line 644 of file uc_kinetis_flexcan.cpp.
References uavcan_kinetis::flexcan::DataType::b0, uavcan_kinetis::flexcan::DataType::b1, uavcan_kinetis::flexcan::DataType::b2, uavcan_kinetis::flexcan::DataType::b3, uavcan_kinetis::flexcan::DataType::b4, uavcan_kinetis::flexcan::DataType::b5, uavcan_kinetis::flexcan::DataType::b6, uavcan_kinetis::flexcan::DataType::b7, uavcan_kinetis::flexcan::CAN_FIFO_NE, uavcan_kinetis::flexcan::CAN_FIFO_OV, uavcan_kinetis::flexcan::CAN_FIFO_WARN, uavcan_kinetis::flexcan::RxFiFoType::CS, uavcan_kinetis::flexcan::RxFiFoType::data, uavcan_kinetis::flexcan::FIFOcsType::dlc, uavcan_kinetis::flexcan::IDType::ext, uavcan_kinetis::flexcan::FiFo, uavcan_kinetis::flexcan::RxFiFoType::ID, uavcan_kinetis::flexcan::FIFOcsType::ide, uavcan_kinetis::flexcan::FIFOcsType::rtr, uavcan_kinetis::flexcan::IDType::std, and UNUSED.
handleTxInterrupt()
void uavcan_kinetis::CanIface::handleTxInterrupt (uavcan::uint32_t tx_iflags, uavcan::uint64_t utc_usec)
Definition at line 596 of file uc_kinetis_flexcan.cpp.
References uavcan_kinetis::flexcan::NumMBinFiFoAndFilters, and uavcan_kinetis::flexcan::TxMbAbort.
handleTxMailboxInterrupt()
void uavcan_kinetis::CanIface::handleTxMailboxInterrupt (uavcan::uint8_t mailbox_index, bool txok, uavcan::uint64_t utc_usec) private
Definition at line 581 of file uc_kinetis_flexcan.cpp.
References uavcan_kinetis::CanIface::TxItem::frame, uavcan_kinetis::CanIface::TxItem::loopback, and uavcan_kinetis::CanIface::TxItem::pending.
init()
int uavcan_kinetis::CanIface::init (const uavcan::uint32_t bitrate, const OperatingMode mode)
Initializes the hardware CAN controller.
Assumes:
Iface clock is enabled
Iface has been resetted via RCC
Caller will configure NVIC by itself
Definition at line 484 of file uc_kinetis_flexcan.cpp.
References uavcan_kinetis::flexcan::CLOCKSEL, uavcan_kinetis::flexcan::CTRL1_CLKSRC, uavcan_kinetis::flexcan::CTRL1_ERRMSK, uavcan_kinetis::flexcan::CTRL1_LOM, uavcan_kinetis::flexcan::CTRL1_PRESDIV_SHIFT, uavcan_kinetis::flexcan::CTRL1_PSEG1_SHIFT, uavcan_kinetis::flexcan::CTRL1_PSEG2_SHIFT, uavcan_kinetis::flexcan::CTRL1_RJW_SHIFT, uavcan_kinetis::flexcan::CTRL1_ROPSEG_SHIFT, uavcan_kinetis::flexcan::CTRL1_RWRNMSK, uavcan_kinetis::flexcan::CTRL1_TWRNMSK, uavcan_kinetis::ErrMcrFRZACKAckNotCleared, uavcan_kinetis::ErrMcrLPMAckNotCleared, uavcan_kinetis::ErrMcrLPMAckNotSet, uavcan_kinetis::flexcan::FirstFilter, uavcan_kinetis::flexcan::HWMaxMB, uavcan_kinetis::flexcan::NumHWFilters, uavcan_kinetis::CanIface::Timings::prescaler, uavcan_kinetis::CanIface::Timings::propseg, uavcan_kinetis::CanIface::Timings::pseg1, uavcan_kinetis::CanIface::Timings::pseg2, uavcan_kinetis::CanIface::Timings::rjw, uavcan_kinetis::flexcan::TXMBMask, UAVCAN_KINETIS_LOG, and uavcan_kinetis::flexcan::FilterType::w.
isRxBufferEmpty()
bool uavcan_kinetis::CanIface::isRxBufferEmpty () const
Definition at line 787 of file uc_kinetis_flexcan.cpp.
References MicroBenchHRT::lock().
Referenced by uavcan_kinetis::CanInitHelper< RxQueueCapacity >::init().
pollErrorFlagsFromISR()
void uavcan_kinetis::CanIface::pollErrorFlagsFromISR ()
This method is used to count errors and abort transmission on error if necessary.
This functionality used to be implemented in the SCE interrupt handler, but that approach was generating too much processing overhead, especially on disconnected interfaces.
Should be called from RX ISR, TX ISR, and select(); interrupts must be enabled.
Definition at line 712 of file uc_kinetis_flexcan.cpp.
References uavcan_kinetis::CanIface::TxItem::abort_on_error, uavcan_kinetis::flexcan::ESR1_ACKERR, uavcan_kinetis::flexcan::ESR1_BIT0ERR, uavcan_kinetis::flexcan::ESR1_BIT1ERR, uavcan_kinetis::flexcan::ESR1_CRCERR, uavcan_kinetis::flexcan::ESR1_FRMERR, uavcan_kinetis::flexcan::ESR1_STFERR, uavcan_kinetis::flexcan::NumMBinFiFoAndFilters, uavcan_kinetis::CanIface::TxItem::pending, and uavcan_kinetis::flexcan::TxMbAbort.
receive()
uavcan::int16_t uavcan_kinetis::CanIface::receive (uavcan::CanFrame & out_frame, uavcan::MonotonicTime & out_ts_monotonic, uavcan::UtcTime & out_ts_utc, uavcan::CanIOFlags & out_flags) private virtual
Definition at line 300 of file uc_kinetis_flexcan.cpp.
References uavcan_kinetis::clock::getMonotonic(), and MicroBenchHRT::lock().
send()
uavcan::int16_t uavcan_kinetis::CanIface::send (const uavcan::CanFrame & frame, uavcan::MonotonicTime tx_deadline, uavcan::CanIOFlags flags) private virtual
Definition at line 207 of file uc_kinetis_flexcan.cpp.
References uavcan_kinetis::CanIface::TxItem::abort_on_error, uavcan_kinetis::flexcan::DataType::b0, uavcan_kinetis::flexcan::DataType::b1, uavcan_kinetis::flexcan::DataType::b2, uavcan_kinetis::flexcan::DataType::b3, uavcan_kinetis::flexcan::DataType::b4, uavcan_kinetis::flexcan::DataType::b5, uavcan_kinetis::flexcan::DataType::b6, uavcan_kinetis::flexcan::DataType::b7, uavcan_kinetis::flexcan::MBcsType::code, uavcan_kinetis::flexcan::MessageBufferType::CS, uavcan_kinetis::flexcan::MessageBufferType::data, uavcan_kinetis::CanIface::TxItem::deadline, uavcan_kinetis::flexcan::MBcsType::dlc, uavcan_kinetis::ErrUnsupportedFrame, uavcan_kinetis::flexcan::ESR2_IMB, uavcan_kinetis::flexcan::ESR2_LPTM_MASK, uavcan_kinetis::flexcan::ESR2_LPTM_SHIFT, uavcan_kinetis::flexcan::ESR2_VPS, uavcan_kinetis::flexcan::IDType::ext, uavcan_kinetis::CanIface::TxItem::frame, uavcan_kinetis::flexcan::MessageBufferType::ID, uavcan_kinetis::flexcan::MBcsType::ide, MicroBenchHRT::lock(), uavcan_kinetis::CanIface::TxItem::loopback, math::max(), uavcan_kinetis::flexcan::NumMBinFiFoAndFilters, uavcan_kinetis::CanIface::TxItem::pending, uavcan_kinetis::flexcan::MBcsType::rtr, uavcan_kinetis::flexcan::IDType::std, uavcan_kinetis::flexcan::TxMbDataOrRemote, and uavcan_kinetis::flexcan::TxMbInactive.
setEnable()
bool uavcan_kinetis::CanIface::setEnable (bool enable_true) private
Definition at line 436 of file uc_kinetis_flexcan.cpp.
References uavcan_kinetis::flexcan::MCR_LPMACK, and uavcan_kinetis::flexcan::MCR_MDIS.
setFreeze()
void uavcan_kinetis::CanIface::setFreeze (bool freeze_true) private
Definition at line 418 of file uc_kinetis_flexcan.cpp.
References MicroBenchHRT::lock(), uavcan_kinetis::flexcan::MCR_FRZ, and uavcan_kinetis::flexcan::MCR_HALT.
setMCR()
void uavcan_kinetis::CanIface::setMCR (uavcan::uint32_t mask, bool target_state) private
Definition at line 402 of file uc_kinetis_flexcan.cpp.
waitFreezeAckChange()
bool uavcan_kinetis::CanIface::waitFreezeAckChange (bool target_state) private
Definition at line 413 of file uc_kinetis_flexcan.cpp.
References uavcan_kinetis::flexcan::MCR_FRZACK.
waitMCRChange()
bool uavcan_kinetis::CanIface::waitMCRChange (uavcan::uint32_t mask, bool target_state) private
Definition at line 385 of file uc_kinetis_flexcan.cpp.
References state.
Member Data Documentation
can_
flexcan::CanType* const uavcan_kinetis::CanIface::can_ private
Definition at line 129 of file can.hpp.
error_cnt_
uavcan::uint64_t uavcan_kinetis::CanIface::error_cnt_ private
Definition at line 130 of file can.hpp.
FIFO_IFLAG1
const uavcan::uint32_t uavcan_kinetis::CanIface::FIFO_IFLAG1 = flexcan::CAN_FIFO_NE | flexcan::CAN_FIFO_WARN | flexcan::CAN_FIFO_OV private
Definition at line 53 of file can.hpp.
fifo_warn_cnt_
uavcan::uint64_t uavcan_kinetis::CanIface::fifo_warn_cnt_ private
Definition at line 131 of file can.hpp.
had_activity_
bool uavcan_kinetis::CanIface::had_activity_ private
Definition at line 138 of file can.hpp.
MaxMB
uavcan::uint8_t uavcan_kinetis::CanIface::MaxMB private
Definition at line 126 of file can.hpp.
peak_tx_mailbox_index_
uavcan::uint8_t uavcan_kinetis::CanIface::peak_tx_mailbox_index_ private
Definition at line 136 of file can.hpp.
pending_aborts_
uavcan::uint32_t uavcan_kinetis::CanIface::pending_aborts_ private
Definition at line 132 of file can.hpp.
pending_tx_
TxItem uavcan_kinetis::CanIface::pending_tx_[NumTxMesgBuffers] private
Definition at line 135 of file can.hpp.
rx_queue_
RxQueue uavcan_kinetis::CanIface::rx_queue_ private
Definition at line 128 of file can.hpp.
self_index_
const uavcan::uint8_t uavcan_kinetis::CanIface::self_index_ private
Definition at line 137 of file can.hpp.
served_aborts_cnt_
uavcan::uint32_t uavcan_kinetis::CanIface::served_aborts_cnt_ private
Definition at line 133 of file can.hpp.
update_event_
BusEvent& uavcan_kinetis::CanIface::update_event_ private
Definition at line 134 of file can.hpp.
The documentation for this class was generated from the following files:
src/drivers/uavcan/uavcan_drivers/kinetis/driver/include/uavcan_kinetis/can.hpp
src/drivers/uavcan/uavcan_drivers/kinetis/driver/src/uc_kinetis_flexcan.cpp