PX4 Firmware: ManualInput Class Reference
ManualInput Class Reference
#include <manual_input.h>
Public Member Functions
ManualInput ()
~ManualInput ()
Protected Types
enum MAIN_STATE {
MAIN_STATE_MANUAL = 0, MAIN_STATE_ALTCTL, MAIN_STATE_POSCTL, MAIN_STATE_AUTO_MISSION,
MAIN_STATE_AUTO_LOITER, MAIN_STATE_AUTO_RTL, MAIN_STATE_OFFBOARD, MAIN_STATE_MAX
}
Protected Member Functions
void JoyCallback (const sensor_msgs::JoyConstPtr &msg)
Takes ROS joystick message and converts/publishes to px4 manual control setpoint topic.
void MapAxis (const sensor_msgs::JoyConstPtr &msg, int map_index, double scale, double offset, double deadzone, float &out)
Helper function to map and scale joystick axis.
void MapButtons (const sensor_msgs::JoyConstPtr &msg, px4::manual_control_setpoint &msg_mc_sp)
Helper function to map joystick buttons.
Protected Attributes
ros::NodeHandle _n
ros::Subscriber _joy_sub
ros::Publisher _man_ctrl_sp_pub
int _param_buttons_map [MAIN_STATE_MAX]
joystick button mapping, order according to MAIN_STATE
bool _buttons_state [MAIN_STATE_MAX]
joystick button state of last iteration, order according to MAIN_STATE
int _param_axes_map [4]
double _param_axes_scale [4]
double _param_axes_offset [4]
double _param_axes_dz [4]
px4::manual_control_setpoint _msg_mc_sp
Detailed Description
Definition at line 47 of file manual_input.h.
Member Enumeration Documentation
enum ManualInput::MAIN_STATE protected
Enumerator
MAIN_STATE_MANUAL
MAIN_STATE_ALTCTL
MAIN_STATE_POSCTL
MAIN_STATE_AUTO_MISSION
MAIN_STATE_AUTO_LOITER
MAIN_STATE_AUTO_RTL
MAIN_STATE_OFFBOARD
MAIN_STATE_MAX
Definition at line 75 of file manual_input.h.
Constructor & Destructor Documentation
ManualInput::ManualInput ()
Definition at line 45 of file manual_input.cpp.
References _msg_mc_sp, _n, _param_axes_dz, _param_axes_map, _param_axes_offset, _param_axes_scale, and _param_buttons_map.
ManualInput::~ManualInput () inline
Definition at line 52 of file manual_input.h.
References math::deadzone(), JoyCallback(), MapAxis(), MapButtons(), and msg.
Member Function Documentation
void ManualInput::JoyCallback (const sensor_msgs::JoyConstPtr & msg) protected
Takes ROS joystick message and converts/publishes to px4 manual control setpoint topic.
Definition at line 93 of file manual_input.cpp.
References _man_ctrl_sp_pub, _msg_mc_sp, _param_axes_dz, _param_axes_map, _param_axes_offset, _param_axes_scale, px4::get_time_micros(), MapAxis(), and MapButtons().
Referenced by ~ManualInput().
void ManualInput::MapAxis (const sensor_msgs::JoyConstPtr & msg, int map_index, double scale, double offset, double deadzone, float & out) protected
Helper function to map and scale joystick axis.
Definition at line 112 of file manual_input.cpp.
Referenced by JoyCallback(), and ~ManualInput().
void ManualInput::MapButtons (const sensor_msgs::JoyConstPtr & msg, px4::manual_control_setpoint & msg_mc_sp) protected
Helper function to map joystick buttons.
Definition at line 125 of file manual_input.cpp.
References _buttons_state, _param_buttons_map, MAIN_STATE_ALTCTL, MAIN_STATE_MANUAL, MAIN_STATE_OFFBOARD, and MAIN_STATE_POSCTL.
Referenced by JoyCallback(), and ~ManualInput().
Member Data Documentation
bool ManualInput::_buttons_state[MAIN_STATE_MAX] protected
joystick button state of last iteration, order according to MAIN_STATE
Definition at line 88 of file manual_input.h.
Referenced by MapButtons().
ros::Subscriber ManualInput::_joy_sub protected
Definition at line 71 of file manual_input.h.
ros::Publisher ManualInput::_man_ctrl_sp_pub protected
Definition at line 72 of file manual_input.h.
Referenced by JoyCallback().
px4::manual_control_setpoint ManualInput::_msg_mc_sp protected
Definition at line 96 of file manual_input.h.
Referenced by JoyCallback(), and ManualInput().
ros::NodeHandle ManualInput::_n protected
Definition at line 70 of file manual_input.h.
Referenced by ManualInput().
double ManualInput::_param_axes_dz[4] protected
Definition at line 94 of file manual_input.h.
Referenced by JoyCallback(), and ManualInput().
int ManualInput::_param_axes_map[4] protected
Definition at line 91 of file manual_input.h.
Referenced by JoyCallback(), and ManualInput().
double ManualInput::_param_axes_offset[4] protected
Definition at line 93 of file manual_input.h.
Referenced by JoyCallback(), and ManualInput().
double ManualInput::_param_axes_scale[4] protected
Definition at line 92 of file manual_input.h.
Referenced by JoyCallback(), and ManualInput().
int ManualInput::_param_buttons_map[MAIN_STATE_MAX] protected
joystick button mapping, order according to MAIN_STATE
Definition at line 87 of file manual_input.h.
Referenced by ManualInput(), and MapButtons().
The documentation for this class was generated from the following files:
src/platforms/ros/nodes/manual_input/manual_input.h
src/platforms/ros/nodes/manual_input/manual_input.cpp