PX4 Firmware: src/modules/uORB/uORB.h File Reference
uORB.h File Reference
API for the uORB lightweight object broker.
#include <sys/types.h>
#include <stdint.h>
#include <stdbool.h>
Classes
struct orb_metadata
Object metadata.
Macros
#define ORB_MULTI_MAX_INSTANCES 4
Maximum number of multi topic instances.
#define ORB_ID(_name) &__orb_##_name
Generates a pointer to the uORB metadata structure for a given topic.
#define ORB_DECLARE(_name) extern const struct orb_metadata __orb_##_name __EXPORT
Declare (prototype) the uORB metadata for a topic (used by code generators).
#define ORB_DEFINE(_name, _struct, _size_no_padding, _fields)
Define (instantiate) the uORB metadata for a topic.
#define ORB_ID_VEHICLE_ATTITUDE_CONTROLS ORB_ID(actuator_controls_0)
Typedefs
typedef const struct orb_metadata * orb_id_t
typedef uint8_t arming_state_t
typedef uint8_t main_state_t
typedef uint8_t hil_state_t
typedef uint8_t navigation_state_t
typedef uint8_t switch_pos_t
Enumerations
enum ORB_PRIO {
ORB_PRIO_MIN = 1, ORB_PRIO_VERY_LOW = 25, ORB_PRIO_LOW = 50, ORB_PRIO_DEFAULT = 75,
ORB_PRIO_HIGH = 100, ORB_PRIO_VERY_HIGH = 125, ORB_PRIO_MAX = 255
}
Topic priority.
Functions
orb_advert_t orb_advertise (const struct orb_metadata *meta, const void *data) __EXPORT
orb_advert_t orb_advertise_queue (const struct orb_metadata *meta, const void *data, unsigned int queue_size) __EXPORT
orb_advert_t orb_advertise_multi (const struct orb_metadata *meta, const void *data, int *instance, int priority) __EXPORT
orb_advert_t orb_advertise_multi_queue (const struct orb_metadata *meta, const void *data, int *instance, int priority, unsigned int queue_size) __EXPORT
int orb_unadvertise (orb_advert_t handle) __EXPORT
int orb_publish (const struct orb_metadata *meta, orb_advert_t handle, const void *data) __EXPORT
static int orb_publish_auto (const struct orb_metadata *meta, orb_advert_t *handle, const void *data, int *instance, int priority)
Advertise as the publisher of a topic.
int orb_subscribe (const struct orb_metadata *meta) __EXPORT
int orb_subscribe_multi (const struct orb_metadata *meta, unsigned instance) __EXPORT
int orb_unsubscribe (int handle) __EXPORT
int orb_copy (const struct orb_metadata *meta, int handle, void *buffer) __EXPORT
int orb_check (int handle, bool *updated) __EXPORT
int orb_stat (int handle, uint64_t *time) __EXPORT
int orb_exists (const struct orb_metadata *meta, int instance) __EXPORT
int orb_group_count (const struct orb_metadata *meta) __EXPORT
Get the number of published instances of a topic group.
int orb_priority (int handle, int32_t *priority) __EXPORT
int orb_set_interval (int handle, unsigned interval) __EXPORT
int orb_get_interval (int handle, unsigned *interval) __EXPORT
Variables
__BEGIN_DECLS typedef void * orb_advert_t
ORB topic advertiser handle.
Detailed Description
API for the uORB lightweight object broker.
Definition in file uORB.h.
Macro Definition Documentation
#define ORB_DECLARE (_name) extern const struct orb_metadata __orb_##_name __EXPORT
Declare (prototype) the uORB metadata for a topic (used by code generators).
Parameters
_name The name of the topic.
Definition at line 97 of file uORB.h.
#define ORB_DEFINE (_name, _struct, _size_no_padding, _fields)
Value:
const struct orb_metadata __orb_##_name = { \
        #_name,                 \
        sizeof(_struct),        \
        _size_no_padding,           \
        _fields                 \
    }; struct hack
Define (instantiate) the uORB metadata for a topic.
The uORB metadata is used to help ensure that updates and copies are accessing the right data.
Note that there must be no more than one instance of this macro for each topic.
Parameters
_name The name of the topic.
_struct The structure the topic provides.
_size_no_padding Struct size w/o padding at the end
_fields All fields in a semicolon separated list e.g: "float[3] position;bool armed"
Definition at line 114 of file uORB.h.
#define ORB_ID (_name) &__orb_##_name
Generates a pointer to the uORB metadata structure for a given topic.
The topic must have been declared previously in scope with ORB_DECLARE().
Parameters
_name The name of the topic.
Definition at line 87 of file uORB.h.
Referenced by vmount::InputMavlinkCmdMount::_ack_vehicle_command(), vmount::OutputBase::_calculate_output_angles(), landing_target_estimator::LandingTargetEstimator::_check_params(), land_detector::LandDetector::_check_params(), load_mon::LoadMon::_compute(), land_detector::LandDetector::_cycle(), vmount::OutputBase::_handle_position_update(), land_detector::VtolLandDetector::_initialize_topics(), land_detector::FixedwingLandDetector::_initialize_topics(), land_detector::MulticopterLandDetector::_initialize_topics(), landing_target_estimator::LandingTargetEstimator::_initialize_topics(), RGBLED::_measure(), rpi_rc_in::RcInput::_measure(), navio_sysfs_rc_in::RcInput::_measure(), linux_sbus::RcInput::_measure(), MPU9250_mag::_measure(), ACCELSIM::_measure(), GYROSIM::_measure(), _param_notify_changes(), DfLtc2946Wrapper::_publish(), DfMS5607Wrapper::_publish(), DfMS5611Wrapper::_publish(), DfBmp280Wrapper::_publish(), DfBebopRangeFinderWrapper::_publish(), DfAK8963Wrapper::_publish(), DfHmc5883Wrapper::_publish(), DfTROneWrapper::_publish(), DfISL29501Wrapper::_publish(), DfMPU6050Wrapper::_publish(), DfLsm9ds1Wrapper::_publish(), DfBebopBusWrapper::_publish(), DfMpu9250Wrapper::_publish(), leddar_one::_publish(), load_mon::LoadMon::_ram_used(), vmount::InputMavlinkROI::_read_control_data_from_position_setpoint_sub(), vmount::InputRC::_read_control_data_from_subscription(), QShell::_send_cmd(), land_detector::VtolLandDetector::_update_topics(), land_detector::FixedwingLandDetector::_update_topics(), land_detector::MulticopterLandDetector::_update_topics(), landing_target_estimator::LandingTargetEstimator::_update_topics(), FlightTasks::_updateCommand(), QShell::_wait_for_retval(), sensors::VotedSensorsUpdate::accel_poll(), px4::logger::Logger::ack_vehicle_command(), MavlinkReceiver::acknowledge(), VtolAttitudeControl::actuator_controls_fw_poll(), VtolAttitudeControl::actuator_controls_mc_poll(), Sensors::adc_poll(), Preflight::airspeedCheck(), events::SendEvent::answer_command(), answer_command(), arm_auth_init(), arm_auth_request_msg_send(), arm_auth_update(), sensors::VotedSensorsUpdate::baro_poll(), MulticopterAttitudeControl::battery_status_poll(), GroundRoverAttitudeControl::battery_status_poll(), UavcanGnssBridge::broadcast_from_orb(), build_eam_response(), build_gam_response(), build_gps_response(), buzzer_init(), calibrate_cancel_check(), calibrate_cancel_subscribe(), calibrate_from_orientation(), CameraTrigger::CameraTrigger(), UavcanServers::cb_getset(), sensors::VotedSensorsUpdate::check_failover(), events::rc_loss::RC_Loss_Alarm::check_for_updates(), events::status::StatusDisplay::check_for_updates(), Navigator::check_traffic(), MS5525::collect(), ETSAirspeed::collect(), SDP3X::collect(), MEASAirspeed::collect(), MEASAirspeedSim::collect(), BAROSIM::collect(), BMP280::collect(), TFMINI::collect(), SF0X::collect(), SF1XX::collect(), LSM303AGR::collect(), VL53LXX::collect(), PMW3901::collect(), TERARANGER::collect(), LidarLiteI2C::collect(), HC_SR04::collect(), SRF02::collect(), MB12XX::collect(), PX4FLOW::collect(), LPS22HB::collect(), MPL3115A2::collect(), LIS3MDL::collect(), MS5611::collect(), BMM150::collect(), LPS25H::collect(), HMC5883::collect(), IST8310::collect(), commander_low_prio_loop(), mpu9x50::create_pubs(), events::SendEvent::custom_command(), WindEstimatorModule::cycle(), RCInput::cycle(), TAP_ESC::cycle(), PX4FMU::cycle(), px4::bst::BST::cycle(), CameraTrigger::cycle_trampoline(), MuorbTestExample::DefaultTest(), detect_orientation(), DfLtc2946Wrapper::DfLtc2946Wrapper(), Sensors::diff_pres_poll(), do_accel_calibration(), do_accel_calibration_measurements(), do_airspeed_calibration(), do_esc_calibration(), do_gyro_calibration(), do_level_calibration(), do_trim_calibration(), GPS::dumpGpsData(), Ekf2::Ekf2(), Preflight::ekf2Check(), CameraTrigger::engage(), PX4FMU::fake(), Navigator::fake_traffic(), VtolAttitudeControl::fill_fw_att_rates_sp(), VtolAttitudeControl::fill_mc_att_rates_sp(), ToneAlarm::frequency_to_divisor(), frsky_init(), frsky_telemetry_thread_main(), frsky_update_topics(), FixedwingPositionControl::fw_pos_ctrl_status_publish(), Navigator::fw_pos_ctrl_status_update(), VtolAttitudeControl::fw_virtual_att_sp_poll(), px4::logger::Logger::get_log_time(), Ekf2::getRangeSubIndex(), FixedwingAttitudeControl::global_pos_poll(), Navigator::global_position_update(), GroundRoverPositionControl::gnd_pos_ctrl_status_publish(), gpio_led_cycle(), gpio_led_start(), Navigator::gps_position_update(), gyro_calibration_worker(), sensors::VotedSensorsUpdate::gyro_poll(), Commander::handle_command(), VtolAttitudeControl::handle_command(), MavlinkParametersManager::handle_message(), Syslink::handle_message(), MavlinkTimesync::handle_message(), Simulator::handle_message(), MavlinkReceiver::handle_message_adsb_vehicle(), MavlinkReceiver::handle_message_att_pos_mocap(), MavlinkReceiver::handle_message_attitude_quaternion_cov(), MavlinkReceiver::handle_message_battery_status(), MavlinkReceiver::handle_message_collision(), MavlinkReceiver::handle_message_command_ack(), MavlinkReceiver::handle_message_command_both(), MavlinkReceiver::handle_message_debug(), MavlinkReceiver::handle_message_debug_vect(), MavlinkReceiver::handle_message_distance_sensor(), MavlinkReceiver::handle_message_follow_target(), MavlinkReceiver::handle_message_gps_rtcm_data(), MavlinkReceiver::handle_message_heartbeat(), MavlinkReceiver::handle_message_hil_gps(), MavlinkReceiver::handle_message_hil_optical_flow(), MavlinkReceiver::handle_message_hil_sensor(), MavlinkReceiver::handle_message_hil_state_quaternion(), MavlinkReceiver::handle_message_landing_target(), MavlinkReceiver::handle_message_local_position_ned_cov(), MavlinkReceiver::handle_message_manual_control(), MavlinkReceiver::handle_message_named_value_float(), MavlinkReceiver::handle_message_obstacle_distance(), MavlinkReceiver::handle_message_optical_flow_rad(), MavlinkReceiver::handle_message_ping(), MavlinkReceiver::handle_message_radio_status(), MavlinkReceiver::handle_message_rc_channels_override(), MavlinkReceiver::handle_message_set_actuator_control_target(), MavlinkReceiver::handle_message_set_attitude_target(), MavlinkReceiver::handle_message_set_mode(), MavlinkReceiver::handle_message_set_position_target_local_ned(), MavlinkReceiver::handle_message_trajectory_representation_waypoints(), MavlinkReceiver::handle_message_vision_position_estimate(), Syslink::handle_raw(), MavlinkULog::handle_update(), GPS::handleInjectDataTopic(), px4::ReplayEkf2::handleTopicUpdate(), hil_state_transition(), Navigator::home_position_update(), PCA9685::i2cpwm(), Preflight::imuConsistencyCheck(), Airspeed::init(), LidarLitePWM::init(), sensors::RCUpdate::init(), ADIS16477::init(), AirspeedSim::init(), LidarLiteI2C::init(), BAROSIM::init(), TFMINI::init(), SF0X::init(), SF1XX::init(), HC_SR04::init(), ACCELSIM::init(), RCInput::init(), BMP280::init(), MPU9250_mag::init(), SRF02::init(), MB12XX::init(), TERARANGER::init(), TAP_ESC::init(), ulanding::Radar::init(), MPL3115A2::init(), PX4FLOW::init(), linux_sbus::RcInput::init(), GYROSIM::init(), BMA180::init(), MS5611::init(), PX4IO::init(), MPU6000::init(), BMI055_gyro::init(), PX4FMU::init(), BMI055_accel::init(), FXOS8701CQ::init(), ADIS16448::init(), BMM150::init(), L3GD20::init(), BATT_SMBUS::init(), FXAS21002C::init(), LSM303D::init(), MPU9250::init(), BMI160::init(), init_sub_messages(), vmount::InputMavlinkROI::initialize(), vmount::InputRC::initialize(), vmount::OutputBase::initialize(), vmount::InputMavlinkCmdMount::initialize(), sensors::VotedSensorsUpdate::initialize_sensors(), GPS::initializeCommunicationDump(), FlightTaskOffboard::initializeSubscriptions(), FlightTaskManual::initializeSubscriptions(), FlightTask::initializeSubscriptions(), FlightTaskAuto::initializeSubscriptions(), PX4IO::io_handle_status(), PX4IO::io_handle_vservo(), PX4IO::io_publish_pwm_outputs(), PX4IO::io_publish_raw_rc(), PX4IO::io_set_arming_state(), PX4IO::io_set_control_state(), MissionBlock::issue_command(), VtolAttitudeControl::land_detected_poll(), RGBLED_PWM::led(), RGBLED::led(), BlinkM::led(), led_init(), Navigator::local_position_update(), mag_calibrate_all(), mag_calibration_worker(), ACCELSIM::mag_measure(), FXOS8701CQ::mag_measure(), LSM303D::mag_measure(), sensors::VotedSensorsUpdate::mag_poll(), Preflight::magConsistencyCheck(), QShell::main(), GroundRoverAttitudeControl::manual_control_setpoint_poll(), GroundRoverPositionControl::manual_control_setpoint_poll(), FixedwingPositionControl::manual_control_setpoint_poll(), Mavlink::mavlink_open_uart(), mavlink_vasprintf(), MavlinkMissionManager::MavlinkMissionManager(), MavlinkReceiver::MavlinkReceiver(), MavlinkStreamActuatorControlTarget< N >::MavlinkStreamActuatorControlTarget(), MavlinkULog::MavlinkULog(), VtolAttitudeControl::mc_virtual_att_sp_poll(), md25Sine(), LidarLitePWM::measure(), BMA180::measure(), BMI055_gyro::measure(), BMI055_accel::measure(), FXOS8701CQ::measure(), L3GD20::measure(), MPU6000::measure(), FXAS21002C::measure(), ADIS16448::measure(), LSM303D::measure(), BMI160::measure(), MPU9250::measure(), Commander::mission_init(), motor_test(), navio_sysfs_rc_in::RcInput::navio_rc_init(), nshterm_main(), FollowTarget::on_activation(), PrecLand::on_activation(), GpsFailure::on_active(), FollowTarget::on_active(), PrecLand::on_active(), px4::ReplayEkf2::onEnterMainLoop(), px4::ReplayEkf2::onSubscriptionAdded(), UavcanEscController::orb_pub_timer_cb(), MulticopterAttitudeControl::parameter_update_poll(), rc_receiver::parameter_update_poll(), mpu9x50::parameter_update_poll(), Sensors::parameter_update_poll(), sensors::VotedSensorsUpdate::parameters_update(), MulticopterPositionControl::parameters_update(), Simulator::parameters_update(), Navigator::params_update(), MuorbTestExample::PingPongTest(), MK::play_beep(), events::rc_loss::RC_Loss_Alarm::play_tune(), MulticopterPositionControl::poll_subscriptions(), Commander::poll_telemetry_status(), Simulator::pollForMAVLinkMessages(), VtolAttitudeControl::pos_sp_triplet_poll(), position_estimator_inav_thread_main(), GroundRoverPositionControl::position_setpoint_triplet_poll(), FixedwingPositionControl::position_setpoint_triplet_poll(), power_button_state_notification_cb(), Preflight::powerCheck(), UavcanNode::print_info(), WindEstimatorModule::print_status(), events::SendEvent::process_commands(), UavcanGnssBridge::process_fixx(), uORBTest::UnitTest::pub_test_multi2_main(), uORBTest::UnitTest::pub_test_queue_main(), events::status::StatusDisplay::publish(), vmount::OutputBase::publish(), GPS::publish(), ADIS16477::publish_accel(), MavlinkULog::publish_ack(), Ekf2::publish_attitude(), MulticopterPositionControl::publish_avoidance_desired_waypoint(), Simulator::publish_distance_topic(), Simulator::publish_ev_topic(), Simulator::publish_flow_topic(), publish_gam_message(), Navigator::publish_geofence_result(), ADIS16477::publish_gyro(), IridiumSBD::publish_iridium_status(), TemperatureCalibration::publish_led_control(), publish_led_control(), MulticopterPositionControl::publish_local_pos_sp(), px4::logger::LogWriterMavlink::publish_message(), Navigator::publish_mission_result(), Navigator::publish_position_setpoint_triplet(), mpu9x50::publish_reports(), Simulator::publish_sensor_topics(), IridiumSBD::publish_subsystem_status(), publish_tune_control(), Navigator::publish_vehicle_cmd(), Navigator::publish_vehicle_command_ack(), Ekf2::publish_wind_estimate(), GPS::publishSatelliteInfo(), uORBTest::UnitTest::pubsublatency_main(), PWMSim::PWMSim(), px4_log_initialize(), px4_log_modulename(), PX4FMU::PX4FMU(), sensors::RCUpdate::rc_parameter_map_poll(), sensors::RCUpdate::rc_poll(), read_accelerometer_avg(), IRLOCK::read_device(), MavlinkReceiver::receive_thread(), MavlinkParametersManager::request_next_uavcan_parameter(), rgbled_set_color_and_mode(), PWMSim::run(), MulticopterAttitudeControl::run(), Commander::run(), FixedwingAttitudeControl::run(), Navigator::run(), Ekf2::run(), UavcanServers::run(), px4::logger::Logger::run(), GPS::run(), FixedwingPositionControl::run(), UavcanNode::run(), Sensors::run(), MavlinkMissionManager::send(), CRSFTelemetry::send_attitude(), Mavlink::send_autopilot_capabilites(), CRSFTelemetry::send_battery(), MavlinkReceiver::send_flight_information(), CRSFTelemetry::send_flight_mode(), CRSFTelemetry::send_gps(), Simulator::send_mavlink_message(), MavlinkParametersManager::send_uavcan(), MavlinkParametersManager::send_untransmitted(), send_vehicle_command(), MulticopterAttitudeControl::sensor_bias_poll(), MulticopterAttitudeControl::sensor_correction_poll(), sensors::VotedSensorsUpdate::sensors_poll(), Commander::set_home_position(), set_tune(), set_tune_override(), Simulator::Simulator(), sPort_init(), sPort_update_topics(), DfAK8963Wrapper::start(), DfHmc5883Wrapper::start(), DfMPU6050Wrapper::start(), DfLsm9ds1Wrapper::start(), DfMpu9250Wrapper::start(), px4::bst::BST::start(), PMW3901::start(), px4::logger::LogWriterMavlink::start_log(), events::SubscriberHandler::subscribe(), linux_pwm_out::subscribe(), snapdragon_pwm::subscribe(), TAP_ESC::TAP_ESC(), spektrum_rc::task_main(), TemperatureCalibration::task_main(), AttitudeEstimatorQ::task_main(), rc_receiver::task_main(), uart_esc::task_main(), CameraFeedback::task_main(), linux_pwm_out::task_main(), ulanding::Radar::task_main(), GPSSIM::task_main(), snapdragon_pwm::task_main(), GroundRoverAttitudeControl::task_main(), mpu9x50::task_main(), Syslink::task_main(), MK::task_main(), GroundRoverPositionControl::task_main(), VtolAttitudeControl::task_main(), MulticopterPositionControl::task_main(), df_bebop_bus_wrapper::task_main(), PX4IO::task_main(), Mavlink::task_main(), VtolAttitudeControl::tecs_status_poll(), FixedwingPositionControl::tecs_update_pitch_throttle(), TemperatureCalibrationAccel::TemperatureCalibrationAccel(), TemperatureCalibrationBaro::TemperatureCalibrationBaro(), CameraTrigger::test(), uORBTest::UnitTest::test_multi(), uORBTest::UnitTest::test_multi2(), uORBTest::UnitTest::test_multi_reversed(), test_ppm_loopback(), uORBTest::UnitTest::test_queue(), uORBTest::UnitTest::test_queue_poll_notify(), test_rc(), uORBTest::UnitTest::test_single(), uORBTest::UnitTest::test_unadvertise(), UavcanNode::UavcanNode(), vmount::OutputMavlink::update(), vmount::OutputRC::update(), landing_target_estimator::LandingTargetEstimator::update(), LedController::update(), MavlinkMissionManager::update_active_mission(), CameraTrigger::update_distance(), vmount::InputMavlinkROI::update_impl(), vmount::InputMavlinkCmdMount::update_impl(), Mission::update_offboard_mission(), UavcanEscController::update_outputs(), AttitudeEstimatorQ::update_parameters(), PX4FMU::update_params(), TemperatureCalibrationAccel::update_sensor_instance(), TemperatureCalibrationGyro::update_sensor_instance(), TemperatureCalibrationBaro::update_sensor_instance(), MicroBenchORB::ut_declare_test_c(), VtolAttitudeControl::vehicle_airspeed_poll(), MulticopterAttitudeControl::vehicle_attitude_poll(), VtolAttitudeControl::vehicle_attitude_poll(), FixedwingPositionControl::vehicle_attitude_poll(), MulticopterAttitudeControl::vehicle_attitude_setpoint_poll(), GroundRoverAttitudeControl::vehicle_attitude_setpoint_poll(), VtolAttitudeControl::vehicle_cmd_poll(), FixedwingPositionControl::vehicle_command_poll(), MulticopterAttitudeControl::vehicle_control_mode_poll(), GroundRoverAttitudeControl::vehicle_control_mode_poll(), GroundRoverPositionControl::vehicle_control_mode_poll(), VtolAttitudeControl::vehicle_control_mode_poll(), Sensors::vehicle_control_mode_poll(), FixedwingAttitudeControl::vehicle_control_mode_poll(), FixedwingPositionControl::vehicle_control_mode_poll(), MulticopterAttitudeControl::vehicle_land_detected_poll(), FixedwingAttitudeControl::vehicle_land_detected_poll(), FixedwingPositionControl::vehicle_land_detected_poll(), Navigator::vehicle_land_detected_update(), VtolAttitudeControl::vehicle_local_pos_poll(), VtolAttitudeControl::vehicle_local_pos_sp_poll(), MulticopterAttitudeControl::vehicle_manual_poll(), VtolAttitudeControl::vehicle_manual_poll(), FixedwingAttitudeControl::vehicle_manual_poll(), MulticopterAttitudeControl::vehicle_motor_limits_poll(), MulticopterAttitudeControl::vehicle_rates_setpoint_poll(), FixedwingAttitudeControl::vehicle_setpoint_poll(), MulticopterAttitudeControl::vehicle_status_poll(), FixedwingAttitudeControl::vehicle_status_poll(), FixedwingPositionControl::vehicle_status_poll(), Navigator::vehicle_status_update(), vmount_thread_main(), MEASAirspeed::voltage_correction(), and WindEstimatorModule::WindEstimatorModule().
#define ORB_ID_VEHICLE_ATTITUDE_CONTROLS ORB_ID(actuator_controls_0)
Definition at line 256 of file uORB.h.
Referenced by esc_calib_main(), PX4FMU::fake(), position_estimator_inav_thread_main(), prepare(), Commander::run(), GroundRoverAttitudeControl::task_main(), and MK::task_main().
#define ORB_MULTI_MAX_INSTANCES 4
Maximum number of multi topic instances.
Definition at line 62 of file uORB.h.
Referenced by Commander::data_link_checks(), Ekf2::Ekf2(), Ekf2::getRangeSubIndex(), Commander::handle_command(), MavlinkReceiver::handle_message_heartbeat(), MavlinkReceiver::handle_message_ping(), MavlinkReceiver::handle_message_radio_status(), uORB::DeviceMaster::ioctl(), px4::logger::LoggerSubscription::LoggerSubscription(), Commander::poll_telemetry_status(), position_estimator_inav_thread_main(), px4::logger::Logger::run(), usage(), px4::logger::Logger::write_all_add_logged_msg(), and Ekf2::~Ekf2().
Typedef Documentation
typedef uint8_t arming_state_t
Definition at line 257 of file uORB.h.
typedef uint8_t hil_state_t
Definition at line 259 of file uORB.h.
typedef uint8_t main_state_t
Definition at line 258 of file uORB.h.
typedef uint8_t navigation_state_t
Definition at line 260 of file uORB.h.
typedef const struct orb_metadata* orb_id_t
Definition at line 57 of file uORB.h.
typedef uint8_t switch_pos_t
Definition at line 261 of file uORB.h.
Enumeration Type Documentation
enum ORB_PRIO
Topic priority.
Relevant for multi-topics / topic groups
Enumerator
ORB_PRIO_MIN
ORB_PRIO_VERY_LOW
ORB_PRIO_LOW
ORB_PRIO_DEFAULT
ORB_PRIO_HIGH
ORB_PRIO_VERY_HIGH
ORB_PRIO_MAX
Definition at line 68 of file uORB.h.
Function Documentation
orb_advert_t orb_advertise (const struct orb_metadata * meta, const void * data)
See also
uORB::Manager::orb_advertise()
Definition at line 43 of file uORB.cpp.
References uORB::Manager::get_instance(), and uORB::Manager::orb_advertise().
Referenced by load_mon::LoadMon::_compute(), _param_notify_changes(), DfBebopBusWrapper::_publish(), leddar_one::_publish(), arm_auth_request_msg_send(), buzzer_init(), CameraTrigger::CameraTrigger(), UavcanServers::cb_getset(), PMW3901::collect(), PX4FLOW::collect(), BATT_SMBUS::cycle(), MuorbTestExample::DefaultTest(), PX4FMU::fake(), VtolAttitudeControl::fill_fw_att_rates_sp(), VtolAttitudeControl::fill_mc_att_rates_sp(), FixedwingPositionControl::fw_pos_ctrl_status_publish(), GroundRoverPositionControl::gnd_pos_ctrl_status_publish(), Commander::handle_command(), MavlinkParametersManager::handle_message(), Syslink::handle_message(), MavlinkReceiver::handle_message_att_pos_mocap(), MavlinkReceiver::handle_message_battery_status(), MavlinkReceiver::handle_message_collision(), MavlinkReceiver::handle_message_debug(), MavlinkReceiver::handle_message_debug_vect(), MavlinkReceiver::handle_message_follow_target(), MavlinkReceiver::handle_message_hil_gps(), MavlinkReceiver::handle_message_hil_optical_flow(), MavlinkReceiver::handle_message_hil_sensor(), MavlinkReceiver::handle_message_hil_state_quaternion(), MavlinkReceiver::handle_message_landing_target(), MavlinkReceiver::handle_message_manual_control(), MavlinkReceiver::handle_message_named_value_float(), MavlinkReceiver::handle_message_obstacle_distance(), MavlinkReceiver::handle_message_optical_flow_rad(), MavlinkReceiver::handle_message_rc_channels_override(), MavlinkReceiver::handle_message_set_actuator_control_target(), MavlinkReceiver::handle_message_set_attitude_target(), MavlinkReceiver::handle_message_set_position_target_local_ned(), MavlinkReceiver::handle_message_trajectory_representation_waypoints(), Syslink::handle_raw(), AirspeedSim::init(), TAP_ESC::init(), linux_sbus::RcInput::init(), BMA180::init(), PX4IO::io_handle_vservo(), MissionBlock::issue_command(), uORBTest::UnitTest::latency_test(), Commander::mission_init(), navio_sysfs_rc_in::RcInput::navio_rc_init(), GpsFailure::on_active(), UavcanEscController::orb_pub_timer_cb(), MuorbTestExample::PingPongTest(), events::rc_loss::RC_Loss_Alarm::play_tune(), position_estimator_inav_thread_main(), MavlinkULog::publish_ack(), MulticopterPositionControl::publish_attitude(), MulticopterPositionControl::publish_avoidance_desired_waypoint(), publish_gam_message(), Navigator::publish_geofence_result(), IridiumSBD::publish_iridium_status(), MulticopterPositionControl::publish_local_pos_sp(), Navigator::publish_mission_result(), Navigator::publish_position_setpoint_triplet(), publish_tune_control(), px4::Replay::publishTopic(), PWMSim::run(), Commander::run(), MulticopterAttitudeControl::run(), FixedwingAttitudeControl::run(), Navigator::run(), Ekf2::run(), FixedwingPositionControl::run(), Sensors::run(), sensors::VotedSensorsUpdate::sensors_poll(), Commander::set_home_position(), PMW3901::start(), spektrum_rc::task_main(), rc_receiver::task_main(), uart_esc::task_main(), linux_pwm_out::task_main(), GPSSIM::task_main(), snapdragon_pwm::task_main(), GroundRoverAttitudeControl::task_main(), MK::task_main(), GroundRoverPositionControl::task_main(), VtolAttitudeControl::task_main(), df_bebop_bus_wrapper::task_main(), FixedwingPositionControl::tecs_update_pitch_throttle(), uORBTest::UnitTest::test_single(), landing_target_estimator::LandingTargetEstimator::update(), uORB::PublicationBase::update(), MavlinkMissionManager::update_active_mission(), and FixedwingAttitudeControl::vehicle_manual_poll().
orb_advert_t orb_advertise_multi (const struct orb_metadata * meta, const void * data, int * instance, int priority)
See also
uORB::Manager::orb_advertise_multi()
Definition at line 53 of file uORB.cpp.
References uORB::Manager::get_instance(), and uORB::Manager::orb_advertise_multi().
Referenced by rpi_rc_in::RcInput::_measure(), DfMS5607Wrapper::_publish(), DfMS5611Wrapper::_publish(), DfBmp280Wrapper::_publish(), DfBebopRangeFinderWrapper::_publish(), DfHmc5883Wrapper::_publish(), DfTROneWrapper::_publish(), DfAK8963Wrapper::_publish(), DfISL29501Wrapper::_publish(), DfMPU6050Wrapper::_publish(), DfBebopBusWrapper::_publish(), DfMpu9250Wrapper::_publish(), LSM303AGR::collect(), LPS22HB::collect(), LIS3MDL::collect(), LPS25H::collect(), HMC5883::collect(), IST8310::collect(), mpu9x50::create_pubs(), PX4FMU::cycle(), MavlinkTimesync::handle_message(), MavlinkReceiver::handle_message_distance_sensor(), MavlinkReceiver::handle_message_heartbeat(), MavlinkReceiver::handle_message_hil_optical_flow(), MavlinkReceiver::handle_message_optical_flow_rad(), MavlinkReceiver::handle_message_ping(), MavlinkReceiver::handle_message_radio_status(), Airspeed::init(), LidarLitePWM::init(), ADIS16477::init(), LidarLiteI2C::init(), BAROSIM::init(), TFMINI::init(), SF0X::init(), SF1XX::init(), HC_SR04::init(), ACCELSIM::init(), BMP280::init(), MPU9250_mag::init(), MB12XX::init(), SRF02::init(), TERARANGER::init(), ulanding::Radar::init(), MPL3115A2::init(), PX4FLOW::init(), GYROSIM::init(), MS5611::init(), MPU6000::init(), BMI055_gyro::init(), BMI055_accel::init(), FXOS8701CQ::init(), ADIS16448::init(), BMM150::init(), L3GD20::init(), FXAS21002C::init(), LSM303D::init(), MPU9250::init(), BMI160::init(), PX4IO::io_handle_status(), orb_publish_auto(), uORBTest::UnitTest::pub_test_multi2_main(), UavcanCDevSensorBridgeBase::publish(), px4::Replay::publishTopic(), IRLOCK::read_device(), MavlinkReceiver::receive_thread(), DfLsm9ds1Wrapper::start(), DfMpu9250Wrapper::start(), MK::task_main(), uORBTest::UnitTest::test_multi(), uORBTest::UnitTest::test_multi_reversed(), uORBTest::UnitTest::test_unadvertise(), uORB::PublicationBase::update(), and UavcanEscController::update_outputs().
orb_advert_t orb_advertise_multi_queue (const struct orb_metadata * meta, const void * data, int * instance, int priority, unsigned int queue_size)
See also
uORB::Manager::orb_advertise_multi()
Definition at line 59 of file uORB.cpp.
References uORB::Manager::get_instance(), and uORB::Manager::orb_advertise_multi().
Referenced by GPS::initializeCommunicationDump().
orb_advert_t orb_advertise_queue (const struct orb_metadata * meta, const void * data, unsigned int queue_size)
See also
uORB::Manager::orb_advertise()
Definition at line 48 of file uORB.cpp.
References uORB::Manager::get_instance(), and uORB::Manager::orb_advertise().
Referenced by vmount::InputMavlinkCmdMount::_ack_vehicle_command(), load_mon::LoadMon::_ram_used(), FlightTasks::_updateCommand(), px4::logger::Logger::ack_vehicle_command(), MavlinkReceiver::acknowledge(), events::SendEvent::answer_command(), answer_command(), sensors::VotedSensorsUpdate::check_failover(), events::SendEvent::custom_command(), CameraTrigger::cycle_trampoline(), Navigator::fake_traffic(), VtolAttitudeControl::handle_command(), MavlinkReceiver::handle_message_adsb_vehicle(), MavlinkReceiver::handle_message_command_ack(), MavlinkReceiver::handle_message_command_both(), MavlinkReceiver::handle_message_gps_rtcm_data(), MavlinkReceiver::handle_message_set_mode(), PX4IO::init(), led_init(), mavlink_vasprintf(), motor_test(), uORBTest::UnitTest::pub_test_queue_main(), events::status::StatusDisplay::publish(), publish_led_control(), TemperatureCalibration::publish_led_control(), px4::logger::LogWriterMavlink::publish_message(), IridiumSBD::publish_subsystem_status(), Navigator::publish_vehicle_cmd(), Navigator::publish_vehicle_command_ack(), px4_log_initialize(), MavlinkParametersManager::request_next_uavcan_parameter(), UavcanServers::run(), send_vehicle_command(), px4::logger::LogWriterMavlink::start_log(), Mavlink::task_main(), CameraTrigger::test(), uORBTest::UnitTest::test_queue(), and vmount::OutputMavlink::update().
int orb_check (int handle, bool * updated)
See also
uORB::Manager::orb_check()
Definition at line 95 of file uORB.cpp.
References uORB::Manager::get_instance(), and uORB::Manager::orb_check().
Referenced by landing_target_estimator::LandingTargetEstimator::_check_params(), land_detector::LandDetector::_check_params(), vmount::OutputBase::_handle_position_update(), landing_target_estimator::LandingTargetEstimator::_orb_update(), land_detector::LandDetector::_orb_update(), DfAK8963Wrapper::_publish(), DfHmc5883Wrapper::_publish(), DfMPU6050Wrapper::_publish(), DfLsm9ds1Wrapper::_publish(), DfMpu9250Wrapper::_publish(), FlightTasks::_updateCommand(), QShell::_wait_for_retval(), sensors::VotedSensorsUpdate::accel_poll(), VtolAttitudeControl::actuator_controls_fw_poll(), VtolAttitudeControl::actuator_controls_mc_poll(), arm_auth_update(), sensors::VotedSensorsUpdate::baro_poll(), MulticopterAttitudeControl::battery_status_poll(), GroundRoverAttitudeControl::battery_status_poll(), UavcanGnssBridge::broadcast_from_orb(), build_gps_response(), calibrate_cancel_subscribe(), events::SubscriberHandler::check_for_updates(), Navigator::check_traffic(), px4::logger::Logger::copy_if_updated_multi(), WindEstimatorModule::cycle(), RCInput::cycle(), TAP_ESC::cycle(), PX4FMU::cycle(), px4::bst::BST::cycle(), CameraTrigger::cycle_trampoline(), MuorbTestExample::DefaultTest(), Sensors::diff_pres_poll(), do_esc_calibration(), do_trim_calibration(), esc_calib_main(), VtolAttitudeControl::fill_fw_att_rates_sp(), VtolAttitudeControl::fill_mc_att_rates_sp(), ToneAlarm::frequency_to_divisor(), frsky_telemetry_thread_main(), frsky_update_topics(), Navigator::fw_pos_ctrl_status_update(), VtolAttitudeControl::fw_virtual_att_sp_poll(), Ekf2::getRangeSubIndex(), FixedwingAttitudeControl::global_pos_poll(), gpio_led_cycle(), gyro_calibration_worker(), sensors::VotedSensorsUpdate::gyro_poll(), MavlinkReceiver::handle_message_set_actuator_control_target(), MavlinkReceiver::handle_message_set_attitude_target(), MavlinkReceiver::handle_message_set_position_target_local_ned(), MavlinkULog::handle_update(), GPS::handleInjectDataTopic(), Navigator::home_position_update(), PCA9685::i2cpwm(), PX4IO::init(), PX4IO::io_set_control_state(), MavlinkOrbSubscription::is_published(), VtolAttitudeControl::land_detected_poll(), RGBLED::led(), BlinkM::led(), listener(), sensors::VotedSensorsUpdate::mag_poll(), GroundRoverAttitudeControl::manual_control_setpoint_poll(), GroundRoverPositionControl::manual_control_setpoint_poll(), FixedwingPositionControl::manual_control_setpoint_poll(), Mavlink::mavlink_open_uart(), MavlinkULog::MavlinkULog(), VtolAttitudeControl::mc_virtual_att_sp_poll(), nshterm_main(), FollowTarget::on_active(), PrecLand::on_active(), Mission::on_active(), Mission::on_inactive(), orb_publish_auto(), MulticopterAttitudeControl::parameter_update_poll(), rc_receiver::parameter_update_poll(), mpu9x50::parameter_update_poll(), Sensors::parameter_update_poll(), MulticopterPositionControl::parameters_update(), Simulator::parameters_update(), MuorbTestExample::PingPongTest(), MulticopterPositionControl::poll_subscriptions(), Commander::poll_telemetry_status(), VtolAttitudeControl::pos_sp_triplet_poll(), position_estimator_inav_thread_main(), GroundRoverPositionControl::position_setpoint_triplet_poll(), FixedwingPositionControl::position_setpoint_triplet_poll(), prepare(), sensors::RCUpdate::rc_parameter_map_poll(), sensors::RCUpdate::rc_poll(), read_accelerometer_avg(), PWMSim::run(), Commander::run(), FixedwingAttitudeControl::run(), Navigator::run(), Ekf2::run(), UavcanServers::run(), px4::logger::Logger::run(), FixedwingPositionControl::run(), UavcanNode::run(), MavlinkMissionManager::send(), Simulator::send_mavlink_message(), MavlinkParametersManager::send_uavcan(), MavlinkParametersManager::send_untransmitted(), MulticopterAttitudeControl::sensor_bias_poll(), MulticopterAttitudeControl::sensor_correction_poll(), sPort_update_topics(), AttitudeEstimatorQ::task_main(), uart_esc::task_main(), CameraFeedback::task_main(), linux_pwm_out::task_main(), snapdragon_pwm::task_main(), MK::task_main(), VtolAttitudeControl::task_main(), df_bebop_bus_wrapper::task_main(), PX4IO::task_main(), VtolAttitudeControl::tecs_status_poll(), FixedwingPositionControl::tecs_update_pitch_throttle(), uORBTest::UnitTest::test_multi2(), test_ppm_loopback(), uORBTest::UnitTest::test_queue(), test_rc(), uORBTest::UnitTest::test_single(), LedController::update(), MavlinkOrbSubscription::update_if_changed(), AttitudeEstimatorQ::update_parameters(), TemperatureCalibrationAccel::update_sensor_instance(), TemperatureCalibrationGyro::update_sensor_instance(), TemperatureCalibrationBaro::update_sensor_instance(), uORB::SubscriptionBase::updated(), MicroBenchORB::ut_declare_test_c(), VtolAttitudeControl::vehicle_airspeed_poll(), MulticopterAttitudeControl::vehicle_attitude_poll(), VtolAttitudeControl::vehicle_attitude_poll(), FixedwingPositionControl::vehicle_attitude_poll(), MulticopterAttitudeControl::vehicle_attitude_setpoint_poll(), GroundRoverAttitudeControl::vehicle_attitude_setpoint_poll(), VtolAttitudeControl::vehicle_cmd_poll(), FixedwingPositionControl::vehicle_command_poll(), MulticopterAttitudeControl::vehicle_control_mode_poll(), GroundRoverAttitudeControl::vehicle_control_mode_poll(), GroundRoverPositionControl::vehicle_control_mode_poll(), VtolAttitudeControl::vehicle_control_mode_poll(), Sensors::vehicle_control_mode_poll(), FixedwingAttitudeControl::vehicle_control_mode_poll(), FixedwingPositionControl::vehicle_control_mode_poll(), MulticopterAttitudeControl::vehicle_land_detected_poll(), FixedwingAttitudeControl::vehicle_land_detected_poll(), FixedwingPositionControl::vehicle_land_detected_poll(), VtolAttitudeControl::vehicle_local_pos_poll(), VtolAttitudeControl::vehicle_local_pos_sp_poll(), MulticopterAttitudeControl::vehicle_manual_poll(), VtolAttitudeControl::vehicle_manual_poll(), MulticopterAttitudeControl::vehicle_motor_limits_poll(), MulticopterAttitudeControl::vehicle_rates_setpoint_poll(), FixedwingAttitudeControl::vehicle_setpoint_poll(), MulticopterAttitudeControl::vehicle_status_poll(), FixedwingAttitudeControl::vehicle_status_poll(), FixedwingPositionControl::vehicle_status_poll(), vmount_thread_main(), and MEASAirspeed::voltage_correction().
int orb_copy (const struct orb_metadata * meta, int handle, void * buffer)
See also
uORB::Manager::orb_copy()
Definition at line 90 of file uORB.cpp.
References uORB::Manager::get_instance(), and uORB::Manager::orb_copy().
Referenced by vmount::OutputBase::_calculate_output_angles(), landing_target_estimator::LandingTargetEstimator::_check_params(), land_detector::LandDetector::_check_params(), vmount::OutputBase::_handle_position_update(), landing_target_estimator::LandingTargetEstimator::_orb_update(), land_detector::LandDetector::_orb_update(), DfLtc2946Wrapper::_publish(), DfAK8963Wrapper::_publish(), DfHmc5883Wrapper::_publish(), DfMPU6050Wrapper::_publish(), DfLsm9ds1Wrapper::_publish(), DfMpu9250Wrapper::_publish(), vmount::InputMavlinkROI::_read_control_data_from_position_setpoint_sub(), vmount::InputRC::_read_control_data_from_subscription(), FlightTasks::_updateCommand(), QShell::_wait_for_retval(), sensors::VotedSensorsUpdate::accel_poll(), VtolAttitudeControl::actuator_controls_fw_poll(), VtolAttitudeControl::actuator_controls_mc_poll(), Sensors::adc_poll(), Preflight::airspeedCheck(), arm_auth_update(), sensors::VotedSensorsUpdate::baro_poll(), MulticopterAttitudeControl::battery_status_poll(), GroundRoverAttitudeControl::battery_status_poll(), UavcanGnssBridge::broadcast_from_orb(), build_eam_response(), build_gam_response(), build_gps_response(), calibrate_cancel_check(), calibrate_cancel_subscribe(), events::rc_loss::RC_Loss_Alarm::check_for_updates(), events::status::StatusDisplay::check_for_updates(), Navigator::check_traffic(), commander_low_prio_loop(), px4::logger::Logger::copy_if_updated_multi(), WindEstimatorModule::cycle(), RCInput::cycle(), TAP_ESC::cycle(), PX4FMU::cycle(), px4::bst::BST::cycle(), CameraTrigger::cycle_trampoline(), MuorbTestExample::DefaultTest(), detect_orientation(), Sensors::diff_pres_poll(), do_accel_calibration(), do_accel_calibration_measurements(), do_airspeed_calibration(), do_esc_calibration(), do_gyro_calibration(), do_level_calibration(), do_trim_calibration(), Preflight::ekf2Check(), esc_calib_main(), VtolAttitudeControl::fill_fw_att_rates_sp(), VtolAttitudeControl::fill_mc_att_rates_sp(), uORB::Subscription< vehicle_land_detected_s >::forcedUpdate(), ToneAlarm::frequency_to_divisor(), frsky_telemetry_thread_main(), frsky_update_topics(), Navigator::fw_pos_ctrl_status_update(), VtolAttitudeControl::fw_virtual_att_sp_poll(), px4::logger::Logger::get_log_time(), Ekf2::getRangeSubIndex(), FixedwingAttitudeControl::global_pos_poll(), Navigator::global_position_update(), gpio_led_cycle(), Navigator::gps_position_update(), gyro_calibration_worker(), sensors::VotedSensorsUpdate::gyro_poll(), MavlinkReceiver::handle_message_set_actuator_control_target(), MavlinkReceiver::handle_message_set_attitude_target(), MavlinkReceiver::handle_message_set_position_target_local_ned(), MavlinkULog::handle_update(), GPS::handleInjectDataTopic(), px4::ReplayEkf2::handleTopicUpdate(), Navigator::home_position_update(), PCA9685::i2cpwm(), Preflight::imuConsistencyCheck(), PX4IO::init(), PX4IO::io_set_arming_state(), PX4IO::io_set_control_state(), VtolAttitudeControl::land_detected_poll(), RGBLED::led(), BlinkM::led(), listener(), Navigator::local_position_update(), mag_calibrate_all(), mag_calibration_worker(), sensors::VotedSensorsUpdate::mag_poll(), Preflight::magConsistencyCheck(), QShell::main(), GroundRoverAttitudeControl::manual_control_setpoint_poll(), GroundRoverPositionControl::manual_control_setpoint_poll(), FixedwingPositionControl::manual_control_setpoint_poll(), Mavlink::mavlink_open_uart(), MavlinkULog::MavlinkULog(), VtolAttitudeControl::mc_virtual_att_sp_poll(), nshterm_main(), FollowTarget::on_active(), PrecLand::on_active(), orb_publish_auto(), MulticopterAttitudeControl::parameter_update_poll(), rc_receiver::parameter_update_poll(), mpu9x50::parameter_update_poll(), Sensors::parameter_update_poll(), sensors::VotedSensorsUpdate::parameters_update(), MulticopterPositionControl::parameters_update(), Simulator::parameters_update(), Navigator::params_update(), MuorbTestExample::PingPongTest(), MulticopterPositionControl::poll_subscriptions(), Commander::poll_telemetry_status(), VtolAttitudeControl::pos_sp_triplet_poll(), position_estimator_inav_thread_main(), GroundRoverPositionControl::position_setpoint_triplet_poll(), FixedwingPositionControl::position_setpoint_triplet_poll(), Preflight::powerCheck(), prepare(), UavcanNode::print_info(), events::SendEvent::process_commands(), px4::logger::LogWriterMavlink::publish_message(), uORBTest::UnitTest::pubsublatency_main(), sensors::RCUpdate::rc_parameter_map_poll(), sensors::RCUpdate::rc_poll(), read_accelerometer_avg(), PWMSim::run(), MulticopterAttitudeControl::run(), Commander::run(), FixedwingAttitudeControl::run(), Navigator::run(), Ekf2::run(), UavcanServers::run(), px4::logger::Logger::run(), FixedwingPositionControl::run(), UavcanNode::run(), MavlinkMissionManager::send(), CRSFTelemetry::send_attitude(), CRSFTelemetry::send_battery(), MavlinkReceiver::send_flight_information(), CRSFTelemetry::send_flight_mode(), CRSFTelemetry::send_gps(), Simulator::send_mavlink_message(), MavlinkParametersManager::send_uavcan(), MavlinkParametersManager::send_untransmitted(), MulticopterAttitudeControl::sensor_bias_poll(), MulticopterAttitudeControl::sensor_correction_poll(), sPort_update_topics(), px4::logger::LogWriterMavlink::start_log(), TemperatureCalibration::task_main(), AttitudeEstimatorQ::task_main(), uart_esc::task_main(), CameraFeedback::task_main(), linux_pwm_out::task_main(), snapdragon_pwm::task_main(), GroundRoverAttitudeControl::task_main(), Syslink::task_main(), MK::task_main(), GroundRoverPositionControl::task_main(), VtolAttitudeControl::task_main(), MulticopterPositionControl::task_main(), df_bebop_bus_wrapper::task_main(), PX4IO::task_main(), VtolAttitudeControl::tecs_status_poll(), FixedwingPositionControl::tecs_update_pitch_throttle(), uORBTest::UnitTest::test_multi(), uORBTest::UnitTest::test_multi2(), uORBTest::UnitTest::test_multi_reversed(), test_ppm_loopback(), uORBTest::UnitTest::test_queue(), uORBTest::UnitTest::test_queue_poll_notify(), test_rc(), uORBTest::UnitTest::test_single(), MavlinkOrbSubscription::update(), uORB::SubscriptionBase::update(), LedController::update(), CameraTrigger::update_distance(), vmount::InputMavlinkROI::update_impl(), vmount::InputMavlinkCmdMount::update_impl(), Mission::update_offboard_mission(), AttitudeEstimatorQ::update_parameters(), PX4FMU::update_params(), TemperatureCalibrationAccel::update_sensor_instance(), TemperatureCalibrationGyro::update_sensor_instance(), TemperatureCalibrationBaro::update_sensor_instance(), MicroBenchORB::ut_declare_test_c(), VtolAttitudeControl::vehicle_airspeed_poll(), MulticopterAttitudeControl::vehicle_attitude_poll(), VtolAttitudeControl::vehicle_attitude_poll(), FixedwingPositionControl::vehicle_attitude_poll(), MulticopterAttitudeControl::vehicle_attitude_setpoint_poll(), GroundRoverAttitudeControl::vehicle_attitude_setpoint_poll(), VtolAttitudeControl::vehicle_cmd_poll(), FixedwingPositionControl::vehicle_command_poll(), MulticopterAttitudeControl::vehicle_control_mode_poll(), GroundRoverAttitudeControl::vehicle_control_mode_poll(), GroundRoverPositionControl::vehicle_control_mode_poll(), VtolAttitudeControl::vehicle_control_mode_poll(), Sensors::vehicle_control_mode_poll(), FixedwingAttitudeControl::vehicle_control_mode_poll(), FixedwingPositionControl::vehicle_control_mode_poll(), MulticopterAttitudeControl::vehicle_land_detected_poll(), FixedwingAttitudeControl::vehicle_land_detected_poll(), FixedwingPositionControl::vehicle_land_detected_poll(), Navigator::vehicle_land_detected_update(), VtolAttitudeControl::vehicle_local_pos_poll(), VtolAttitudeControl::vehicle_local_pos_sp_poll(), MulticopterAttitudeControl::vehicle_manual_poll(), VtolAttitudeControl::vehicle_manual_poll(), FixedwingAttitudeControl::vehicle_manual_poll(), MulticopterAttitudeControl::vehicle_motor_limits_poll(), MulticopterAttitudeControl::vehicle_rates_setpoint_poll(), FixedwingAttitudeControl::vehicle_setpoint_poll(), MulticopterAttitudeControl::vehicle_status_poll(), FixedwingAttitudeControl::vehicle_status_poll(), FixedwingPositionControl::vehicle_status_poll(), Navigator::vehicle_status_update(), vmount_thread_main(), and MEASAirspeed::voltage_correction().
int orb_exists (const struct orb_metadata * meta, int instance)
See also
uORB::Manager::orb_exists()
Definition at line 105 of file uORB.cpp.
References uORB::Manager::get_instance(), and uORB::Manager::orb_exists().
Referenced by px4::logger::Logger::add_topic(), sensors::VotedSensorsUpdate::init_sensor_class(), MavlinkOrbSubscription::is_published(), listener(), orb_group_count(), orb_publish_auto(), px4::logger::Logger::try_to_subscribe_topic(), and MicroBenchORB::ut_declare_test_c().
int orb_get_interval (int handle, unsigned * interval)
See also
uORB::Manager::orb_get_interval()
Definition at line 131 of file uORB.cpp.
References uORB::Manager::get_instance(), and uORB::Manager::orb_get_interval().
Referenced by orb_publish_auto(), and px4::logger::Logger::try_to_subscribe_topic().
int orb_group_count (const struct orb_metadata * meta)
Get the number of published instances of a topic group.
Parameters
meta ORB topic metadata.
Returns
The number of published instances of this topic
Definition at line 110 of file uORB.cpp.
References uORB::Manager::get_instance(), instance, OK, and orb_exists().
Referenced by do_accel_calibration_measurements(), do_gyro_calibration(), mag_calibrate_all(), orb_publish_auto(), MulticopterAttitudeControl::run(), TemperatureCalibration::task_main(), TemperatureCalibrationAccel::TemperatureCalibrationAccel(), and TemperatureCalibrationBaro::TemperatureCalibrationBaro().
int orb_priority (int handle, int32_t * priority)
See also
uORB::Manager::orb_priority()
Definition at line 121 of file uORB.cpp.
References uORB::Manager::get_instance(), and uORB::Manager::orb_priority().
Referenced by sensors::VotedSensorsUpdate::accel_poll(), sensors::VotedSensorsUpdate::baro_poll(), do_accel_calibration_measurements(), do_gyro_calibration(), sensors::VotedSensorsUpdate::gyro_poll(), mag_calibrate_all(), sensors::VotedSensorsUpdate::mag_poll(), orb_publish_auto(), and uORBTest::UnitTest::test_multi().
int orb_publish (const struct orb_metadata * meta, orb_advert_t handle, const void * data)
See also
uORB::Manager::orb_publish()
Definition at line 70 of file uORB.cpp.
References uORB::Manager::get_instance(), and uORB::Manager::orb_publish().
Referenced by vmount::InputMavlinkCmdMount::_ack_vehicle_command(), load_mon::LoadMon::_compute(), rpi_rc_in::RcInput::_measure(), navio_sysfs_rc_in::RcInput::_measure(), linux_sbus::RcInput::_measure(), MPU9250_mag::_measure(), ACCELSIM::_measure(), GYROSIM::_measure(), _param_notify_changes(), DfMS5607Wrapper::_publish(), DfMS5611Wrapper::_publish(), DfBmp280Wrapper::_publish(), DfBebopRangeFinderWrapper::_publish(), DfHmc5883Wrapper::_publish(), DfAK8963Wrapper::_publish(), DfTROneWrapper::_publish(), DfISL29501Wrapper::_publish(), DfMPU6050Wrapper::_publish(), DfLsm9ds1Wrapper::_publish(), DfBebopBusWrapper::_publish(), DfMpu9250Wrapper::_publish(), leddar_one::_publish(), load_mon::LoadMon::_ram_used(), FlightTasks::_updateCommand(), px4::logger::Logger::ack_vehicle_command(), MavlinkReceiver::acknowledge(), events::SendEvent::answer_command(), answer_command(), arm_auth_request_msg_send(), UavcanServers::cb_getset(), sensors::VotedSensorsUpdate::check_failover(), MS5525::collect(), ETSAirspeed::collect(), SDP3X::collect(), MEASAirspeed::collect(), MEASAirspeedSim::collect(), BAROSIM::collect(), BMP280::collect(), TFMINI::collect(), SF0X::collect(), SF1XX::collect(), LSM303AGR::collect(), PMW3901::collect(), TERARANGER::collect(), LidarLiteI2C::collect(), HC_SR04::collect(), MB12XX::collect(), SRF02::collect(), PX4FLOW::collect(), LPS22HB::collect(), MPL3115A2::collect(), LIS3MDL::collect(), MS5611::collect(), BMM150::collect(), LPS25H::collect(), HMC5883::collect(), IST8310::collect(), TAP_ESC::cycle(), PX4FMU::cycle(), BATT_SMBUS::cycle(), CameraTrigger::cycle_trampoline(), MuorbTestExample::DefaultTest(), GPS::dumpGpsData(), CameraTrigger::engage(), VtolAttitudeControl::fill_fw_att_rates_sp(), VtolAttitudeControl::fill_mc_att_rates_sp(), FixedwingPositionControl::fw_pos_ctrl_status_publish(), GroundRoverPositionControl::gnd_pos_ctrl_status_publish(), Commander::handle_command(), VtolAttitudeControl::handle_command(), MavlinkParametersManager::handle_message(), Syslink::handle_message(), MavlinkTimesync::handle_message(), MavlinkReceiver::handle_message_adsb_vehicle(), MavlinkReceiver::handle_message_att_pos_mocap(), MavlinkReceiver::handle_message_battery_status(), MavlinkReceiver::handle_message_collision(), MavlinkReceiver::handle_message_command_ack(), MavlinkReceiver::handle_message_command_both(), MavlinkReceiver::handle_message_debug(), MavlinkReceiver::handle_message_debug_vect(), MavlinkReceiver::handle_message_distance_sensor(), MavlinkReceiver::handle_message_follow_target(), MavlinkReceiver::handle_message_gps_rtcm_data(), MavlinkReceiver::handle_message_heartbeat(), MavlinkReceiver::handle_message_hil_gps(), MavlinkReceiver::handle_message_hil_optical_flow(), MavlinkReceiver::handle_message_hil_sensor(), MavlinkReceiver::handle_message_hil_state_quaternion(), MavlinkReceiver::handle_message_landing_target(), MavlinkReceiver::handle_message_manual_control(), MavlinkReceiver::handle_message_named_value_float(), MavlinkReceiver::handle_message_obstacle_distance(), MavlinkReceiver::handle_message_optical_flow_rad(), MavlinkReceiver::handle_message_ping(), MavlinkReceiver::handle_message_radio_status(), MavlinkReceiver::handle_message_rc_channels_override(), MavlinkReceiver::handle_message_set_actuator_control_target(), MavlinkReceiver::handle_message_set_attitude_target(), MavlinkReceiver::handle_message_set_mode(), MavlinkReceiver::handle_message_set_position_target_local_ned(), MavlinkReceiver::handle_message_trajectory_representation_waypoints(), Syslink::handle_raw(), hil_state_transition(), PX4IO::init(), PX4IO::io_handle_status(), PX4IO::io_handle_vservo(), MissionBlock::issue_command(), uORBTest::UnitTest::latency_test(), ACCELSIM::mag_measure(), FXOS8701CQ::mag_measure(), LSM303D::mag_measure(), mavlink_vasprintf(), LidarLitePWM::measure(), BMA180::measure(), BMI055_gyro::measure(), BMI055_accel::measure(), FXOS8701CQ::measure(), L3GD20::measure(), MPU6000::measure(), FXAS21002C::measure(), ADIS16448::measure(), LSM303D::measure(), BMI160::measure(), MPU9250::measure(), motor_test(), GpsFailure::on_active(), UavcanEscController::orb_pub_timer_cb(), orb_publish_auto(), MuorbTestExample::PingPongTest(), MK::play_beep(), events::rc_loss::RC_Loss_Alarm::play_tune(), position_estimator_inav_thread_main(), power_button_state_notification_cb(), uORBTest::UnitTest::pub_test_multi2_main(), uORBTest::UnitTest::pub_test_queue_main(), events::status::StatusDisplay::publish(), UavcanCDevSensorBridgeBase::publish(), ADIS16477::publish_accel(), MavlinkULog::publish_ack(), MulticopterPositionControl::publish_attitude(), MulticopterPositionControl::publish_avoidance_desired_waypoint(), publish_gam_message(), Navigator::publish_geofence_result(), ADIS16477::publish_gyro(), IridiumSBD::publish_iridium_status(), publish_led_control(), TemperatureCalibration::publish_led_control(), MulticopterPositionControl::publish_local_pos_sp(), px4::logger::LogWriterMavlink::publish_message(), Navigator::publish_mission_result(), Navigator::publish_position_setpoint_triplet(), mpu9x50::publish_reports(), IridiumSBD::publish_subsystem_status(), publish_tune_control(), Navigator::publish_vehicle_cmd(), Navigator::publish_vehicle_command_ack(), px4::Replay::publishTopic(), px4_log_modulename(), IRLOCK::read_device(), MavlinkReceiver::receive_thread(), MavlinkParametersManager::request_next_uavcan_parameter(), rgbled_set_color_and_mode(), PWMSim::run(), Commander::run(), MulticopterAttitudeControl::run(), FixedwingAttitudeControl::run(), Navigator::run(), Ekf2::run(), UavcanServers::run(), FixedwingPositionControl::run(), Sensors::run(), sensors::VotedSensorsUpdate::sensors_poll(), Commander::set_home_position(), set_tune(), set_tune_override(), PMW3901::start(), spektrum_rc::task_main(), rc_receiver::task_main(), uart_esc::task_main(), linux_pwm_out::task_main(), ulanding::Radar::task_main(), GPSSIM::task_main(), snapdragon_pwm::task_main(), GroundRoverAttitudeControl::task_main(), MK::task_main(), GroundRoverPositionControl::task_main(), VtolAttitudeControl::task_main(), df_bebop_bus_wrapper::task_main(), Mavlink::task_main(), FixedwingPositionControl::tecs_update_pitch_throttle(), uORBTest::UnitTest::test_multi(), uORBTest::UnitTest::test_multi_reversed(), uORBTest::UnitTest::test_queue(), uORBTest::UnitTest::test_single(), vmount::OutputMavlink::update(), landing_target_estimator::LandingTargetEstimator::update(), uORB::PublicationBase::update(), MavlinkMissionManager::update_active_mission(), UavcanEscController::update_outputs(), and FixedwingAttitudeControl::vehicle_manual_poll().
static int orb_publish_auto (const struct orb_metadata * meta, orb_advert_t * handle, const void * data, int * instance, int priority) inline static
Advertise as the publisher of a topic.
This performs the initial advertisement of a topic; it creates the topic node in /obj if required and publishes the initial data.
See also
uORB::Manager::orb_advertise_multi() for meaning of the individual parameters
Definition at line 177 of file uORB.h.
References __END_DECLS, __EXPORT, instance, orb_advertise_multi(), orb_check(), orb_copy(), orb_exists(), orb_get_interval(), orb_group_count(), orb_priority(), orb_publish(), orb_set_interval(), orb_stat(), orb_subscribe(), orb_subscribe_multi(), and orb_unsubscribe().
Referenced by land_detector::LandDetector::_cycle(), DfLtc2946Wrapper::_publish(), QShell::_send_cmd(), Sensors::adc_poll(), VL53LXX::collect(), WindEstimatorModule::cycle(), RCInput::cycle(), PX4FMU::cycle(), Sensors::diff_pres_poll(), Simulator::handle_message(), MavlinkReceiver::handle_message_attitude_quaternion_cov(), MavlinkReceiver::handle_message_local_position_ned_cov(), MavlinkReceiver::handle_message_manual_control(), MavlinkReceiver::handle_message_vision_position_estimate(), PX4IO::io_publish_pwm_outputs(), PX4IO::io_publish_raw_rc(), QShell::main(), UavcanGnssBridge::process_fixx(), vmount::OutputBase::publish(), GPS::publish(), Ekf2::publish_attitude(), Simulator::publish_distance_topic(), Simulator::publish_ev_topic(), Simulator::publish_flow_topic(), Simulator::publish_sensor_topics(), Ekf2::publish_wind_estimate(), GPS::publishSatelliteInfo(), sensors::RCUpdate::rc_poll(), MulticopterAttitudeControl::run(), FixedwingAttitudeControl::run(), Ekf2::run(), Sensors::run(), AttitudeEstimatorQ::task_main(), CameraFeedback::task_main(), and vmount::OutputRC::update().
int orb_set_interval (int handle, unsigned interval)
See also
uORB::Manager::orb_set_interval()
Definition at line 126 of file uORB.cpp.
References uORB::Manager::get_instance(), and uORB::Manager::orb_set_interval().
Referenced by px4::logger::Logger::add_topic(), TAP_ESC::cycle(), PX4FMU::cycle(), PCA9685::i2cpwm(), vmount::InputMavlinkCmdMount::initialize(), BlinkM::led(), listener(), mag_calibrate_all(), orb_publish_auto(), PWMSim::run(), Navigator::run(), px4::logger::Logger::run(), FixedwingPositionControl::run(), uORB::SubscriptionBase::SubscriptionBase(), MK::task_main(), GroundRoverPositionControl::task_main(), PX4IO::task_main(), and px4::logger::Logger::try_to_subscribe_topic().
int orb_stat (int handle, uint64_t * time)
See also
uORB::Manager::orb_stat()
Definition at line 100 of file uORB.cpp.
References uORB::Manager::get_instance(), and uORB::Manager::orb_stat().
Referenced by orb_publish_auto(), MavlinkOrbSubscription::update(), and MicroBenchORB::ut_declare_test_c().
int orb_subscribe (const struct orb_metadata * meta)
See also
uORB::Manager::orb_subscribe()
Definition at line 75 of file uORB.cpp.
References uORB::Manager::get_instance(), and uORB::Manager::orb_subscribe().
Referenced by land_detector::LandDetector::_cycle(), land_detector::VtolLandDetector::_initialize_topics(), land_detector::FixedwingLandDetector::_initialize_topics(), land_detector::MulticopterLandDetector::_initialize_topics(), landing_target_estimator::LandingTargetEstimator::_initialize_topics(), RGBLED::_measure(), FlightTasks::_updateCommand(), QShell::_wait_for_retval(), px4::logger::Logger::add_topic(), Preflight::airspeedCheck(), arm_auth_init(), UavcanGnssBridge::broadcast_from_orb(), calibrate_cancel_subscribe(), calibrate_from_orientation(), commander_low_prio_loop(), CameraTrigger::cycle_trampoline(), MuorbTestExample::DefaultTest(), DfLtc2946Wrapper::DfLtc2946Wrapper(), do_accel_calibration(), do_accel_calibration_measurements(), do_airspeed_calibration(), do_esc_calibration(), do_gyro_calibration(), do_level_calibration(), do_trim_calibration(), Ekf2::Ekf2(), Preflight::ekf2Check(), esc_calib_main(), ToneAlarm::frequency_to_divisor(), frsky_init(), frsky_telemetry_thread_main(), px4::logger::Logger::get_log_time(), gpio_led_start(), PCA9685::i2cpwm(), Preflight::imuConsistencyCheck(), sensors::RCUpdate::init(), RCInput::init(), TAP_ESC::init(), PX4IO::init(), PX4FMU::init(), init_sub_messages(), vmount::InputMavlinkROI::initialize(), vmount::InputRC::initialize(), vmount::OutputBase::initialize(), vmount::InputMavlinkCmdMount::initialize(), RGBLED_PWM::led(), RGBLED::led(), BlinkM::led(), mag_calibration_worker(), Preflight::magConsistencyCheck(), QShell::main(), Mavlink::mavlink_open_uart(), MavlinkMissionManager::MavlinkMissionManager(), MavlinkReceiver::MavlinkReceiver(), MavlinkULog::MavlinkULog(), nshterm_main(), FollowTarget::on_activation(), PrecLand::on_activation(), px4::ReplayEkf2::onEnterMainLoop(), orb_publish_auto(), MuorbTestExample::PingPongTest(), Simulator::pollForMAVLinkMessages(), position_estimator_inav_thread_main(), Preflight::powerCheck(), prepare(), UavcanNode::print_info(), PWMSim::run(), MulticopterAttitudeControl::run(), Commander::run(), FixedwingAttitudeControl::run(), Navigator::run(), UavcanServers::run(), px4::logger::Logger::run(), GPS::run(), FixedwingPositionControl::run(), UavcanNode::run(), Sensors::run(), MavlinkParametersManager::send_uavcan(), MavlinkParametersManager::send_untransmitted(), Simulator::Simulator(), sPort_init(), DfAK8963Wrapper::start(), DfHmc5883Wrapper::start(), DfMPU6050Wrapper::start(), DfLsm9ds1Wrapper::start(), DfMpu9250Wrapper::start(), px4::bst::BST::start(), px4::logger::LogWriterMavlink::start_log(), events::SubscriberHandler::subscribe(), linux_pwm_out::subscribe(), UavcanNode::subscribe(), snapdragon_pwm::subscribe(), PWMSim::subscribe(), PX4FMU::subscribe(), uORB::SubscriptionBase::SubscriptionBase(), AttitudeEstimatorQ::task_main(), rc_receiver::task_main(), uart_esc::task_main(), CameraFeedback::task_main(), linux_pwm_out::task_main(), snapdragon_pwm::task_main(), GroundRoverAttitudeControl::task_main(), mpu9x50::task_main(), Syslink::task_main(), MK::task_main(), GroundRoverPositionControl::task_main(), VtolAttitudeControl::task_main(), MulticopterPositionControl::task_main(), df_bebop_bus_wrapper::task_main(), PX4IO::task_main(), test_ppm_loopback(), uORBTest::UnitTest::test_queue(), uORBTest::UnitTest::test_queue_poll_notify(), test_rc(), uORBTest::UnitTest::test_single(), CameraTrigger::update_distance(), MicroBenchORB::ut_declare_test_c(), vmount_thread_main(), MEASAirspeed::voltage_correction(), and WindEstimatorModule::WindEstimatorModule().
int orb_subscribe_multi (const struct orb_metadata * meta, unsigned instance)
See also
uORB::Manager::orb_subscribe_multi()
Definition at line 80 of file uORB.cpp.
References uORB::Manager::get_instance(), and uORB::Manager::orb_subscribe_multi().
Referenced by do_accel_calibration_measurements(), do_gyro_calibration(), Ekf2::Ekf2(), sensors::VotedSensorsUpdate::init_sensor_class(), MavlinkOrbSubscription::is_published(), listener(), mag_calibrate_all(), orb_publish_auto(), Commander::poll_telemetry_status(), Simulator::pollForMAVLinkMessages(), position_estimator_inav_thread_main(), uORBTest::UnitTest::pubsublatency_main(), MulticopterAttitudeControl::run(), uORB::SubscriptionBase::SubscriptionBase(), TemperatureCalibration::task_main(), TemperatureCalibrationAccel::TemperatureCalibrationAccel(), TemperatureCalibrationBaro::TemperatureCalibrationBaro(), uORBTest::UnitTest::test_multi(), uORBTest::UnitTest::test_multi2(), uORBTest::UnitTest::test_multi_reversed(), and px4::logger::Logger::try_to_subscribe_topic().
int orb_unadvertise (orb_advert_t handle)
See also
uORB::Manager::orb_unadvertise()
Definition at line 65 of file uORB.cpp.
References uORB::Manager::get_instance(), and uORB::Manager::orb_unadvertise().
Referenced by buzzer_deinit(), PX4FMU::fake(), Navigator::fake_traffic(), uORBTest::UnitTest::latency_test(), led_deinit(), Commander::mission_init(), uORBTest::UnitTest::pub_test_multi2_main(), uORBTest::UnitTest::pub_test_queue_main(), px4::Replay::run(), px4::logger::Logger::run(), GPS::run(), Sensors::run(), spektrum_rc::task_main(), GPSSIM::task_main(), PX4IO::task_main(), uORBTest::UnitTest::test_queue(), uORBTest::UnitTest::test_single(), uORBTest::UnitTest::test_unadvertise(), Airspeed::~Airspeed(), BMM150::~BMM150(), BMP280::~BMP280(), leddar_one::~leddar_one(), px4::logger::LogWriterMavlink::~LogWriterMavlink(), MavlinkMissionManager::~MavlinkMissionManager(), MavlinkParametersManager::~MavlinkParametersManager(), MavlinkTimesync::~MavlinkTimesync(), MavlinkULog::~MavlinkULog(), MPU6000::~MPU6000(), MPU9250::~MPU9250(), MPU9250_mag::~MPU9250_mag(), vmount::OutputBase::~OutputBase(), vmount::OutputMavlink::~OutputMavlink(), vmount::OutputRC::~OutputRC(), uORB::PublicationBase::~PublicationBase(), PX4FMU::~PX4FMU(), ulanding::Radar::~Radar(), RCInput::~RCInput(), SF1XX::~SF1XX(), TAP_ESC::~TAP_ESC(), VL53LXX::~VL53LXX(), and WindEstimatorModule::~WindEstimatorModule().
int orb_unsubscribe (int handle)
See also
uORB::Manager::orb_unsubscribe()
Definition at line 85 of file uORB.cpp.
References uORB::Manager::get_instance(), and uORB::Manager::orb_unsubscribe().
Referenced by px4::logger::Logger::add_topic(), Preflight::airspeedCheck(), calibrate_cancel_unsubscribe(), sensors::RCUpdate::deinit(), sensors::VotedSensorsUpdate::deinit(), do_accel_calibration(), do_accel_calibration_measurements(), do_esc_calibration(), do_gyro_calibration(), Preflight::ekf2Check(), ToneAlarm::frequency_to_divisor(), frsky_deinit(), px4::logger::Logger::get_log_time(), gpio_led_cycle(), Preflight::imuConsistencyCheck(), TAP_ESC::init(), RGBLED_PWM::led(), RGBLED::led(), listener(), mag_calibrate_all(), Preflight::magConsistencyCheck(), Mavlink::mavlink_open_uart(), px4::ReplayEkf2::onExitMainLoop(), orb_publish_auto(), Preflight::powerCheck(), UavcanNode::print_info(), uORBTest::UnitTest::pubsublatency_main(), PWMSim::run(), MulticopterAttitudeControl::run(), Navigator::run(), px4::logger::Logger::run(), GPS::run(), UavcanNode::run(), Sensors::run(), sPort_deinit(), UavcanNode::subscribe(), PWMSim::subscribe(), PX4FMU::subscribe(), TemperatureCalibration::task_main(), AttitudeEstimatorQ::task_main(), linux_pwm_out::task_main(), snapdragon_pwm::task_main(), df_bebop_bus_wrapper::task_main(), UavcanNode::teardown(), uORBTest::UnitTest::test_multi(), uORBTest::UnitTest::test_multi2(), test_rc(), uORBTest::UnitTest::test_single(), events::SubscriberHandler::unsubscribe(), MicroBenchORB::ut_declare_test_c(), vmount_thread_main(), CRSFTelemetry::~CRSFTelemetry(), DfLtc2946Wrapper::~DfLtc2946Wrapper(), Ekf2::~Ekf2(), vmount::InputMavlinkCmdMount::~InputMavlinkCmdMount(), vmount::InputMavlinkROI::~InputMavlinkROI(), vmount::InputRC::~InputRC(), px4::logger::LogWriterMavlink::~LogWriterMavlink(), MavlinkMissionManager::~MavlinkMissionManager(), MavlinkOrbSubscription::~MavlinkOrbSubscription(), MavlinkParametersManager::~MavlinkParametersManager(), MavlinkReceiver::~MavlinkReceiver(), MavlinkULog::~MavlinkULog(), vmount::OutputBase::~OutputBase(), PX4FMU::~PX4FMU(), RCInput::~RCInput(), RGBLED::~RGBLED(), uORB::SubscriptionBase::~SubscriptionBase(), TAP_ESC::~TAP_ESC(), TemperatureCalibrationAccel::~TemperatureCalibrationAccel(), TemperatureCalibrationBaro::~TemperatureCalibrationBaro(), UavcanGnssBridge::~UavcanGnssBridge(), UavcanNode::~UavcanNode(), and WindEstimatorModule::~WindEstimatorModule().
Variable Documentation
__BEGIN_DECLS typedef void* orb_advert_t
ORB topic advertiser handle.
Advertiser handles are global; once obtained they can be shared freely and do not need to be closed or released.
This permits publication from interrupt context and other contexts where a file-descriptor-based handle would not otherwise be in scope for the publisher.
Definition at line 134 of file uORB.h.
Referenced by Sensors::adc_poll(), px4::logger::Logger::can_start_mavlink_log(), commander_low_prio_loop(), load_mon::LoadMon::custom_command(), MuorbTestExample::DefaultTest(), PX4FMU::fake(), Navigator::fake_traffic(), MavlinkReceiver::handle_message_gps_rtcm_data(), PX4IO::init(), uORBTest::UnitTest::latency_test(), QShell::main(), Commander::mission_init(), uORB::Manager::orb_advertise(), uORB::Manager::orb_advertise_multi(), MuorbTestExample::PingPongTest(), position_estimator_inav_thread_main(), uORBTest::UnitTest::pub_test_multi2_main(), uORBTest::UnitTest::pub_test_queue_main(), Commander::run(), px4::logger::Logger::run(), send_vehicle_command(), DfBebopBusWrapper::set_last_throttle(), spektrum_rc::task_main(), Mavlink::task_main(), uORBTest::UnitTest::test_queue(), uORBTest::UnitTest::test_single(), and uORB::PublicationBase::update().