PX4 Firmware: vl53lxx Namespace Reference
vl53lxx Namespace Reference
Local functions in support of the shell command.
Functions
int reset ()
Reset the driver.
int start (const uint8_t rotation)
Attempt to start driver on all available I2C busses.
int start_bus (const uint8_t rotation, const int i2c_bus)
Start the driver on a specific bus.
int status ()
Print the driver status.
int stop ()
Stop the driver.
int test ()
Perform some basic functional tests on the driver; make sure we can collect data from the sensor in polled and automatic modes.
int usage ()
Prints info about the driver argument usage.
Variables
VL53LXX * g_dev
Detailed Description
Local functions in support of the shell command.
Function Documentation
reset()
int vl53lxx::reset ()
Reset the driver.
Definition at line 811 of file vl53lxx.cpp.
References VL53LXX::start(), and VL53LXX::stop().
Referenced by vl53lxx_main().
start()
int vl53lxx::start (const uint8_t rotation)
Attempt to start driver on all available I2C busses.
This function will return as soon as the first sensor is detected on one of the available busses or if no sensors are detected.
Definition at line 832 of file vl53lxx.cpp.
References i2c_bus_options, NUM_I2C_BUS_OPTIONS, and start_bus().
Referenced by vl53lxx_main().
start_bus()
int vl53lxx::start_bus (const uint8_t rotation, const int i2c_bus)
Start the driver on a specific bus.
This function only returns if the sensor is up and running or could not be detected successfully.
Definition at line 850 of file vl53lxx.cpp.
References g_dev, VL53LXX::init(), VL53LXX::start(), and VL53LXX::VL53LXX().
Referenced by start(), and vl53lxx_main().
status()
int vl53lxx::status ()
Print the driver status.
Definition at line 882 of file vl53lxx.cpp.
References VL53LXX::print_info().
Referenced by vl53lxx_main().
stop()
int vl53lxx::stop ()
Stop the driver.
Stop the driver.
Definition at line 898 of file vl53lxx.cpp.
References g_dev.
Referenced by vl53lxx_main().
test()
int vl53lxx::test ()
Perform some basic functional tests on the driver; make sure we can collect data from the sensor in polled and automatic modes.
Definition at line 916 of file vl53lxx.cpp.
References fd, px4_close(), px4_open(), VL53LXX::read(), and VL53LXX_DEVICE_PATH.
Referenced by vl53lxx_main().
usage()
int vl53lxx::usage (void)
Prints info about the driver argument usage.
Prints info about the driver argument usage.
Definition at line 943 of file vl53lxx.cpp.
References VL53LXX_BUS_DEFAULT.
Referenced by vl53lxx_main().
Variable Documentation
g_dev
VL53LXX* vl53lxx::g_dev
Definition at line 797 of file vl53lxx.cpp.
Referenced by start_bus(), and stop().