PX4 Firmware: src/lib/matrix/test/least_squares.cpp File Reference
least_squares.cpp File Reference
#include "test_macros.hpp"
#include <matrix/math.hpp>
Functions
int test_4x3 (void)
template<typename Type >
int test_4x4 (void)
int test_4x4_type_double (void)
int test_div_zero (void)
int main ()
Function Documentation
main()
int main ()
Definition at line 11 of file least_squares.cpp.
References test_4x3(), and test_div_zero().
test_4x3()
int test_4x3 (void)
Definition at line 30 of file least_squares.cpp.
References data, matrix::isEqual(), matrix::LeastSquaresSolver< Type, M, N >::solve(), and TEST.
Referenced by main().
test_4x4()
template<typename Type > int test_4x4 (void)
Definition at line 56 of file least_squares.cpp.
References data, matrix::isEqual(), matrix::LeastSquaresSolver< Type, M, N >::solve(), and TEST.
test_4x4_type_double()
int test_4x4_type_double (void)
test_div_zero()
int test_div_zero (void)
Definition at line 82 of file least_squares.cpp.
References data, matrix::isEqual(), matrix::LeastSquaresSolver< Type, M, N >::solve(), and TEST.
Referenced by main().