PX4 Firmware: bebop_flow Namespace Reference
bebop_flow Namespace Reference
Functions
int start ()
Attempt to start driver on all available I2C busses.
int stop ()
Stop the driver.
int info ()
Print a little info about the driver.
int trigger (int count)
int clear_errors ()
Clear errors present on the Bebop hardware.
void usage ()
Prints info about the driver argument usage.
void task_main (int argc, char *argv[])
Variables
MT9V117 * image_sensor = nullptr
VideoDevice * g_dev = nullptr
volatile bool _task_should_exit = false
static bool _is_running = false
static px4_task_t _task_handle = -1
volatile unsigned int _trigger = 0
const char * dev_name = "/dev/video0"
Function Documentation
int bebop_flow::clear_errors ()
Clear errors present on the Bebop hardware.
Definition at line 560 of file df_bebop_bus_wrapper.cpp.
References DfBebopBusWrapper::clear_errors(), PX4_DEBUG, and PX4_ERR.
Referenced by df_bebop_bus_wrapper_main().
int bebop_flow::info ()
Print a little info about the driver.
Print a little info about the driver.
Definition at line 232 of file bebop_flow.cpp.
References VideoDevice::print_info(), PX4_DEBUG, and PX4_ERR.
Referenced by bebop_flow_main().
int bebop_flow::start ()
Attempt to start driver on all available I2C busses.
This function will return as soon as the first sensor is detected on one of the available busses or if no sensors are detected.
Attempt to start driver on all available I2C busses.
Definition at line 130 of file bebop_flow.cpp.
References PX4_ERR, px4_task_spawn_cmd(), PX4_WARN, SCHED_DEFAULT, VideoDevice::start(), and task_main().
Referenced by bebop_flow_main().
int bebop_flow::stop ()
Stop the driver.
Stop the driver.
Definition at line 183 of file bebop_flow.cpp.
References g_dev, image_sensor, PX4_ERR, PX4_INFO, VideoDevice::stop(), and usleep().
Referenced by bebop_flow_main().
void bebop_flow::task_main (int argc, char * argv[])
Definition at line 74 of file bebop_flow.cpp.
References _trigger, frame_data::bytes, frame_data::data, dump_pgm(), VideoDevice::get_frame(), VideoDevice::put_frame(), PX4_ERR, PX4_INFO, PX4_WARN, frame_data::seq, frame_data::timestamp, and usleep().
Referenced by start().
int bebop_flow::trigger (int count)
Definition at line 251 of file bebop_flow.cpp.
References OK, and PX4_WARN.
Referenced by bebop_flow_main(), and CameraTrigger::engage().
void bebop_flow::usage (void)
Prints info about the driver argument usage.
Prints info about the driver argument usage.
Definition at line 264 of file bebop_flow.cpp.
References PX4_INFO.
Referenced by bebop_flow_main().
Variable Documentation
bool bebop_flow::_is_running = false static
Definition at line 60 of file bebop_flow.cpp.
px4_task_t bebop_flow::_task_handle = -1 static
Definition at line 61 of file bebop_flow.cpp.
volatile bool bebop_flow::_task_should_exit = false
Definition at line 59 of file bebop_flow.cpp.
volatile unsigned int bebop_flow::_trigger = 0
Definition at line 62 of file bebop_flow.cpp.
Referenced by task_main().
const char* bebop_flow::dev_name = "/dev/video0"
Definition at line 64 of file bebop_flow.cpp.
VideoDevice* bebop_flow::g_dev = nullptr
Definition at line 58 of file bebop_flow.cpp.
Referenced by stop().
MT9V117* bebop_flow::image_sensor = nullptr
Definition at line 57 of file bebop_flow.cpp.
Referenced by stop().