PX4 Firmware: src/lib/parameters/flashparams/flashfs.h File Reference
flashfs.h File Reference
#include <stdint.h>
#include <stdbool.h>
Classes
struct flash_file_token_t
struct sector_descriptor_t
Macros
#define PARAMETER_BUFFER_SIZE 512
Typedefs
typedef struct flash_file_token_t flash_file_token_t
typedef struct sector_descriptor_t sector_descriptor_t
Functions
__EXPORT int parameter_flashfs_init (sector_descriptor_t *fconfig, uint8_t *buffer, uint16_t size)
__EXPORT int parameter_flashfs_read (flash_file_token_t ft, uint8_t **buffer, size_t *buf_size)
__EXPORT int parameter_flashfs_write (flash_file_token_t ft, uint8_t *buffer, size_t buf_size)
__EXPORT int parameter_flashfs_erase (void)
__EXPORT int parameter_flashfs_alloc (flash_file_token_t ft, uint8_t **buffer, size_t *buf_size)
__EXPORT void parameter_flashfs_free (void)
Variables
__BEGIN_DECLS typedef uint32_t flash_file_tokens_t
__EXPORT const flash_file_token_t parameters_token
Macro Definition Documentation
PARAMETER_BUFFER_SIZE
#define PARAMETER_BUFFER_SIZE 512
Definition at line 63 of file flashfs.h.
Typedef Documentation
flash_file_token_t
typedef struct flash_file_token_t flash_file_token_t
sector_descriptor_t
typedef struct sector_descriptor_t sector_descriptor_t
Function Documentation
parameter_flashfs_alloc()
__EXPORT int parameter_flashfs_alloc (flash_file_token_t ft, uint8_t ** buffer, size_t * buf_size)
Referenced by param_export_internal().
parameter_flashfs_erase()
__EXPORT int parameter_flashfs_erase (void)
parameter_flashfs_free()
__EXPORT void parameter_flashfs_free (void)
Referenced by param_export_internal().
parameter_flashfs_init()
__EXPORT int parameter_flashfs_init (sector_descriptor_t * fconfig, uint8_t * buffer, uint16_t size)
parameter_flashfs_read()
__EXPORT int parameter_flashfs_read (flash_file_token_t ft, uint8_t ** buffer, size_t * buf_size)
Referenced by param_export_internal(), and param_import_internal().
parameter_flashfs_write()
__EXPORT int parameter_flashfs_write (flash_file_token_t ft, uint8_t * buffer, size_t buf_size)
Referenced by param_export_internal().
Variable Documentation
flash_file_tokens_t
__BEGIN_DECLS typedef uint32_t flash_file_tokens_t
Definition at line 73 of file flashfs.h.
parameters_token
__EXPORT const flash_file_token_t parameters_token
Referenced by param_export_internal(), and param_import_internal().