PX4 Firmware: Simulator Class Reference
Simulator Class Reference
#include <simulator.h>
Classes
struct sample
Public Types
enum sim_dev_t { SIM_GYRO, SIM_ACCEL, SIM_MAG }
Public Member Functions
bool getRawAccelReport (uint8_t *buf, int len)
bool getMagReport (uint8_t *buf, int len)
bool getMPUReport (uint8_t *buf, int len)
bool getBaroSample (uint8_t *buf, int len)
bool getGPSSample (uint8_t *buf, int len)
bool getAirspeedSample (uint8_t *buf, int len)
void write_MPU_data (void *buf)
void write_accel_data (void *buf)
void write_mag_data (void *buf)
void write_baro_data (void *buf)
void write_gps_data (void *buf)
void write_airspeed_data (void *buf)
bool isInitialized ()
Public Member Functions inherited from ModuleParams
ModuleParams (ModuleParams *parent)
void setParent (ModuleParams *parent)
Set the parent module.
virtual ~ModuleParams ()=default
ModuleParams (const ModuleParams &)=delete
ModuleParams & operator= (const ModuleParams &)=delete
ModuleParams (ModuleParams &&)=delete
ModuleParams & operator= (ModuleParams &&)=delete
Public Member Functions inherited from ListNode< ModuleParams * >
ListNode ()
ListNode (const ListNode &)=delete
ListNode (ListNode &&)=delete
virtual ~ListNode ()=default
ListNode & operator= (const ListNode &)=delete
ListNode & operator= (ListNode &&)=delete
void setSibling (ModuleParams *sibling)
const ModuleParams * getSibling ()
Static Public Member Functions
static Simulator * getInstance ()
static int start (int argc, char *argv[])
Private Member Functions
Simulator ()
~Simulator ()
void initializeSensorData ()
int publish_sensor_topics (mavlink_hil_sensor_t *imu)
int publish_flow_topic (mavlink_hil_optical_flow_t *flow)
int publish_ev_topic (mavlink_vision_position_estimate_t *ev_mavlink)
int publish_distance_topic (mavlink_distance_sensor_t *dist)
DEFINE_PARAMETERS ((ParamFloat< px4::params::SIM_BAT_DRAIN >) _battery_drain_interval_s) void poll_topics()
void handle_message (mavlink_message_t *msg, bool publish)
void send_controls ()
void pollForMAVLinkMessages (bool publish, int udp_port)
void pack_actuator_message (mavlink_hil_actuator_controls_t &actuator_msg, unsigned index)
void send_mavlink_message (const mavlink_message_t &aMsg)
void update_sensors (mavlink_hil_sensor_t *imu)
void update_gps (mavlink_hil_gps_t *gps_sim)
void parameters_update (bool force)
void send ()
Static Private Member Functions
static void * sending_trampoline (void *)
Private Attributes
simulator::Report< simulator::RawAccelData > _accel
simulator::Report< simulator::RawMPUData > _mpu
simulator::Report< simulator::RawBaroData > _baro
simulator::Report< simulator::RawMagData > _mag
simulator::Report< simulator::RawGPSData > _gps
simulator::Report< simulator::RawAirspeedData > _airspeed
perf_counter_t _perf_accel
perf_counter_t _perf_mpu
perf_counter_t _perf_baro
perf_counter_t _perf_mag
perf_counter_t _perf_gps
perf_counter_t _perf_airspeed
perf_counter_t _perf_sim_delay
perf_counter_t _perf_sim_interval
orb_advert_t _accel_pub
orb_advert_t _baro_pub
orb_advert_t _gyro_pub
orb_advert_t _mag_pub
orb_advert_t _flow_pub
orb_advert_t _vision_position_pub
orb_advert_t _vision_attitude_pub
orb_advert_t _dist_pub
orb_advert_t _battery_pub
orb_advert_t _irlock_report_pub
int _param_sub
bool _initialized
double _realtime_factor
How fast the simulation runs in comparison to real system time.
hrt_abstime _last_sim_timestamp
hrt_abstime _last_sitl_timestamp
Battery _battery
battery_status_s _battery_status {}
int32_t _system_type
orb_advert_t _rc_channels_pub
orb_advert_t _attitude_pub
orb_advert_t _gpos_pub
orb_advert_t _lpos_pub
int _actuator_outputs_sub [ORB_MULTI_MAX_INSTANCES]
int _vehicle_attitude_sub
int _manual_sub
int _vehicle_status_sub
struct map_projection_reference_s _hil_local_proj_ref
bool _hil_local_proj_inited
double _hil_ref_lat
double _hil_ref_lon
float _hil_ref_alt
uint64_t _hil_ref_timestamp
struct rc_input_values _rc_input
struct actuator_outputs_s _actuators [ORB_MULTI_MAX_INSTANCES]
struct vehicle_attitude_s _attitude
struct manual_control_setpoint_s _manual
struct vehicle_status_s _vehicle_status
Static Private Attributes
static Simulator * _instance = nullptr
Additional Inherited Members
Protected Member Functions inherited from ModuleParams
virtual void updateParams ()
Call this whenever the module gets a parameter change notification.
virtual void updateParamsImpl ()
The implementation for this is generated with the macro DEFINE_PARAMETERS()
Protected Attributes inherited from ListNode< ModuleParams * >
ModuleParams * _sibling
Detailed Description
Definition at line 189 of file simulator.h.
Member Enumeration Documentation
enum Simulator::sim_dev_t
Enumerator
SIM_GYRO
SIM_ACCEL
SIM_MAG
Definition at line 194 of file simulator.h.
Constructor & Destructor Documentation
Simulator::Simulator () inline private
Definition at line 227 of file simulator.h.
References uart_esc::_param_sub, simulator::RawGPSData::eph, hrt_absolute_time(), ORB_ID, orb_subscribe(), param_find(), and param_get().
Simulator::~Simulator () inline private
Definition at line 297 of file simulator.h.
Member Function Documentation
Simulator::DEFINE_PARAMETERS ((ParamFloat< px4::params::SIM_BAT_DRAIN >) _battery_drain_interval_s) private
Parameters
_battery_drain_interval_s battery drain interval
bool Simulator::getAirspeedSample (uint8_t * buf, int len)
Definition at line 90 of file simulator.cpp.
Referenced by AirspeedSim::transfer().
bool Simulator::getBaroSample (uint8_t * buf, int len)
Definition at line 80 of file simulator.cpp.
Referenced by BAROSIM::collect().
bool Simulator::getGPSSample (uint8_t * buf, int len)
Definition at line 85 of file simulator.cpp.
Referenced by GPSSIM::receive().
Simulator * Simulator::getInstance () static
Definition at line 60 of file simulator.cpp.
Referenced by BAROSIM::collect(), GPSSIM::receive(), simulator_main(), ACCELSIM::transfer(), AirspeedSim::transfer(), and GYROSIM::transfer().
bool Simulator::getMagReport (uint8_t * buf, int len)
Definition at line 75 of file simulator.cpp.
References mpu9x50::_mag.
Referenced by ACCELSIM::transfer().
bool Simulator::getMPUReport (uint8_t * buf, int len)
Definition at line 65 of file simulator.cpp.
Referenced by GYROSIM::transfer().
bool Simulator::getRawAccelReport (uint8_t * buf, int len)
Definition at line 70 of file simulator.cpp.
References mpu9x50::_accel.
Referenced by ACCELSIM::transfer().
void Simulator::handle_message (mavlink_message_t * msg, bool publish) private
Definition at line 280 of file simulator_mavlink.cpp.
References vehicle_global_position_s::alt, armed, batt_sim_start, matrix::Matrix< Type, M, N >::copyTo(), f(), fill_rc_input_msg(), math::gradual(), vehicle_local_position_s::hagl_max, vehicle_local_position_s::hagl_min, hrt_absolute_time(), hrt_abstime, hrt_elapsed_time(), vehicle_global_position_s::lat, vehicle_global_position_s::lon, map_projection_init(), map_projection_project(), math::min(), ORB_ID, ORB_PRIO_HIGH, orb_publish_auto(), perf_count(), perf_set_elapsed(), vehicle_attitude_s::pitchspeed, irlock_report_s::pos_x, irlock_report_s::pos_y, matrix::Euler< Type >::psi(), px4_clock_gettime, px4_sim_start_delay(), px4_sim_stop_delay(), vehicle_attitude_s::q, rc_channels, vehicle_local_position_s::ref_alt, vehicle_local_position_s::ref_lat, vehicle_local_position_s::ref_lon, vehicle_local_position_s::ref_timestamp, vehicle_attitude_s::rollspeed, irlock_report_s::signature, irlock_report_s::size_x, irlock_report_s::size_y, vehicle_global_position_s::timestamp, vehicle_attitude_s::timestamp, vehicle_local_position_s::timestamp, irlock_report_s::timestamp, ts_to_abstime(), usleep(), vehicle_local_position_s::v_xy_valid, vehicle_local_position_s::v_z_valid, vehicle_global_position_s::vel_d, vehicle_global_position_s::vel_e, vehicle_global_position_s::vel_n, vehicle_local_position_s::vx, vehicle_local_position_s::vxy_max, vehicle_local_position_s::vy, vehicle_local_position_s::vz, vehicle_local_position_s::vz_max, vehicle_local_position_s::x, vehicle_local_position_s::xy_global, vehicle_local_position_s::xy_valid, vehicle_local_position_s::y, vehicle_local_position_s::yaw, vehicle_attitude_s::yawspeed, vehicle_local_position_s::z, vehicle_local_position_s::z_global, and vehicle_local_position_s::z_valid.
void Simulator::initializeSensorData () private
Definition at line 628 of file simulator_mavlink.cpp.
References accel(), simulator::RawMPUData::accel_z, baro(), CONSTANTS_ONE_G, mag(), simulator::RawBaroData::pressure, simulator::RawBaroData::temperature, simulator::RawMagData::x, simulator::RawMagData::y, simulator::RawAccelData::z, and simulator::RawMagData::z.
bool Simulator::isInitialized () inline
Definition at line 224 of file simulator.h.
void Simulator::pack_actuator_message (mavlink_hil_actuator_controls_t & actuator_msg, unsigned index) private
Definition at line 80 of file simulator_mavlink.cpp.
References armed, hrt_absolute_time(), mode_flag_armed, mode_flag_custom, PWM_DEFAULT_MAX, and PWM_DEFAULT_MIN.
void Simulator::parameters_update (bool force) private
Definition at line 125 of file simulator.cpp.
References uart_esc::_param_sub, orb_check(), orb_copy(), and ORB_ID.
void Simulator::pollForMAVLinkMessages (bool publish, int udp_port) private
Definition at line 660 of file simulator_mavlink.cpp.
References _addrlen, _buf, _fd, _srcaddr, B460800, B921600, hrt_reset(), hrt_system_time(), message, msg, ORB_ID, orb_subscribe(), orb_subscribe_multi(), param_find(), param_get(), pthread_attr_destroy(), pthread_attr_getschedparam(), pthread_attr_init(), pthread_attr_setschedparam(), pthread_attr_setstacksize(), pthread_create(), pthread_self(), PX4_ERR, px4_exit_requested(), PX4_INFO, px4_sim_start_delay(), px4_sim_stop_delay(), PX4_STACK_ADJUSTED, PX4_WARN, read(), sending_trampoline(), sim_delay, usleep(), and warnx.
int Simulator::publish_distance_topic (mavlink_distance_sensor_t * dist) private
Definition at line 1161 of file simulator_mavlink.cpp.
References distance_sensor_s::covariance, distance_sensor_s::current_distance, hrt_absolute_time(), distance_sensor_s::id, distance_sensor_s::max_distance, distance_sensor_s::min_distance, OK, ORB_ID, ORB_PRIO_HIGH, orb_publish_auto(), distance_sensor_s::orientation, distance_sensor_s::signal_quality, vehicle_attitude_s::timestamp, distance_sensor_s::timestamp, and distance_sensor_s::type.
int Simulator::publish_ev_topic (mavlink_vision_position_estimate_t * ev_mavlink) private
Definition at line 1131 of file simulator_mavlink.cpp.
References matrix::Matrix< Type, M, N >::copyTo(), hrt_absolute_time(), OK, ORB_ID, ORB_PRIO_HIGH, orb_publish_auto(), vehicle_attitude_s::q, optical_flow_s::timestamp, vehicle_attitude_s::timestamp, vehicle_local_position_s::timestamp, vehicle_local_position_s::v_xy_valid, vehicle_local_position_s::v_z_valid, vehicle_local_position_s::x, vehicle_local_position_s::xy_valid, vehicle_local_position_s::y, vehicle_local_position_s::z, and vehicle_local_position_s::z_valid.
int Simulator::publish_flow_topic (mavlink_hil_optical_flow_t * flow) private
Definition at line 1082 of file simulator_mavlink.cpp.
References optical_flow_s::frame_count_since_last_readout, optical_flow_s::ground_distance_m, optical_flow_s::gyro_temperature, optical_flow_s::gyro_x_rate_integral, optical_flow_s::gyro_y_rate_integral, optical_flow_s::gyro_z_rate_integral, hrt_absolute_time(), optical_flow_s::integration_timespan, optical_flow_s::max_flow_rate, optical_flow_s::max_ground_distance, optical_flow_s::min_ground_distance, OK, ORB_ID, ORB_PRIO_HIGH, orb_publish_auto(), param_find(), param_get(), optical_flow_s::pixel_flow_x_integral, optical_flow_s::pixel_flow_y_integral, optical_flow_s::quality, rotate_3f(), optical_flow_s::sensor_id, optical_flow_s::time_since_last_sonar_update, and optical_flow_s::timestamp.
int Simulator::publish_sensor_topics (mavlink_hil_sensor_t * imu) private
Definition at line 990 of file simulator_mavlink.cpp.
References mpu9x50::_accel_pub, mpu9x50::_gyro_pub, mpu9x50::_mag_pub, accel_report, baro_report, CONSTANTS_ONE_G, gyro_report, hrt_absolute_time(), mag_report, OK, ORB_ID, ORB_PRIO_HIGH, orb_publish_auto(), and PX4_DEBUG.
void Simulator::send () private
Definition at line 588 of file simulator_mavlink.cpp.
References mpu9x50::parameters_update(), pthread_self(), px4_poll(), and PX4_WARN.
void Simulator::send_controls () private
Definition at line 169 of file simulator_mavlink.cpp.
References message, and vehicle_status_s::timestamp.
void Simulator::send_mavlink_message (const mavlink_message_t & aMsg) private
Definition at line 545 of file simulator_mavlink.cpp.
References _addrlen, _fd, _srcaddr, orb_check(), orb_copy(), ORB_ID, and PX4_WARN.
void * Simulator::sending_trampoline (void *) static private
Definition at line 582 of file simulator_mavlink.cpp.
Referenced by pollForMAVLinkMessages().
int Simulator::start (int argc, char * argv[]) static
Definition at line 142 of file simulator.cpp.
References drv_led_start(), and PX4_WARN.
Referenced by simulator_main().
void Simulator::update_gps (mavlink_hil_gps_t * gps_sim) private
Definition at line 260 of file simulator_mavlink.cpp.
References simulator::RawGPSData::alt, simulator::RawGPSData::cog, simulator::RawGPSData::eph, simulator::RawGPSData::epv, simulator::RawGPSData::fix_type, gps, simulator::RawGPSData::lat, simulator::RawGPSData::lon, simulator::RawGPSData::satellites_visible, simulator::RawGPSData::timestamp, simulator::RawGPSData::vd, simulator::RawGPSData::ve, simulator::RawGPSData::vel, and simulator::RawGPSData::vn.
void Simulator::update_sensors (mavlink_hil_sensor_t * imu) private
Definition at line 213 of file simulator_mavlink.cpp.
References accel(), simulator::RawMPUData::accel_x, simulator::RawMPUData::accel_y, simulator::RawMPUData::accel_z, baro(), simulator::RawAirspeedData::diff_pressure, simulator::RawMPUData::gyro_x, simulator::RawMPUData::gyro_y, simulator::RawMPUData::gyro_z, hrt_absolute_time(), mag(), perf_begin(), simulator::RawBaroData::pressure, simulator::RawMPUData::temp, simulator::RawBaroData::temperature, simulator::RawAirspeedData::temperature, simulator::RawAccelData::x, simulator::RawMagData::x, simulator::RawAccelData::y, simulator::RawMagData::y, simulator::RawAccelData::z, and simulator::RawMagData::z.
void Simulator::write_accel_data (void * buf)
Definition at line 100 of file simulator.cpp.
References mpu9x50::_accel.
void Simulator::write_airspeed_data (void * buf)
Definition at line 120 of file simulator.cpp.
void Simulator::write_baro_data (void * buf)
Definition at line 110 of file simulator.cpp.
void Simulator::write_gps_data (void * buf)
Definition at line 115 of file simulator.cpp.
void Simulator::write_mag_data (void * buf)
Definition at line 105 of file simulator.cpp.
References mpu9x50::_mag.
void Simulator::write_MPU_data (void * buf)
Definition at line 95 of file simulator.cpp.
Member Data Documentation
simulator::Report<simulator::RawAccelData> Simulator::_accel private
Definition at line 311 of file simulator.h.
orb_advert_t Simulator::_accel_pub private
Definition at line 328 of file simulator.h.
int Simulator::_actuator_outputs_sub[ORB_MULTI_MAX_INSTANCES] private
Definition at line 367 of file simulator.h.
struct actuator_outputs_s Simulator::_actuators[ORB_MULTI_MAX_INSTANCES] private
Definition at line 382 of file simulator.h.
simulator::Report<simulator::RawAirspeedData> Simulator::_airspeed private
Definition at line 316 of file simulator.h.
struct vehicle_attitude_s Simulator::_attitude private
Definition at line 383 of file simulator.h.
orb_advert_t Simulator::_attitude_pub private
Definition at line 362 of file simulator.h.
simulator::Report<simulator::RawBaroData> Simulator::_baro private
Definition at line 313 of file simulator.h.
orb_advert_t Simulator::_baro_pub private
Definition at line 329 of file simulator.h.
Battery Simulator::_battery private
Definition at line 347 of file simulator.h.
orb_advert_t Simulator::_battery_pub private
Definition at line 336 of file simulator.h.
battery_status_s Simulator::_battery_status {} private
Definition at line 348 of file simulator.h.
orb_advert_t Simulator::_dist_pub private
Definition at line 335 of file simulator.h.
orb_advert_t Simulator::_flow_pub private
Definition at line 332 of file simulator.h.
orb_advert_t Simulator::_gpos_pub private
Definition at line 363 of file simulator.h.
simulator::Report<simulator::RawGPSData> Simulator::_gps private
Definition at line 315 of file simulator.h.
orb_advert_t Simulator::_gyro_pub private
Definition at line 330 of file simulator.h.
bool Simulator::_hil_local_proj_inited private
Definition at line 374 of file simulator.h.
struct map_projection_reference_s Simulator::_hil_local_proj_ref private
Definition at line 373 of file simulator.h.
float Simulator::_hil_ref_alt private
Definition at line 377 of file simulator.h.
double Simulator::_hil_ref_lat private
Definition at line 375 of file simulator.h.
double Simulator::_hil_ref_lon private
Definition at line 376 of file simulator.h.
uint64_t Simulator::_hil_ref_timestamp private
Definition at line 378 of file simulator.h.
bool Simulator::_initialized private
Definition at line 341 of file simulator.h.
Simulator * Simulator::_instance = nullptr static private
Definition at line 308 of file simulator.h.
orb_advert_t Simulator::_irlock_report_pub private
Definition at line 337 of file simulator.h.
hrt_abstime Simulator::_last_sim_timestamp private
Definition at line 343 of file simulator.h.
hrt_abstime Simulator::_last_sitl_timestamp private
Definition at line 344 of file simulator.h.
orb_advert_t Simulator::_lpos_pub private
Definition at line 364 of file simulator.h.
simulator::Report<simulator::RawMagData> Simulator::_mag private
Definition at line 314 of file simulator.h.
orb_advert_t Simulator::_mag_pub private
Definition at line 331 of file simulator.h.
struct manual_control_setpoint_s Simulator::_manual private
Definition at line 384 of file simulator.h.
int Simulator::_manual_sub private
Definition at line 369 of file simulator.h.
simulator::Report<simulator::RawMPUData> Simulator::_mpu private
Definition at line 312 of file simulator.h.
int Simulator::_param_sub private
Definition at line 339 of file simulator.h.
perf_counter_t Simulator::_perf_accel private
Definition at line 318 of file simulator.h.
perf_counter_t Simulator::_perf_airspeed private
Definition at line 323 of file simulator.h.
perf_counter_t Simulator::_perf_baro private
Definition at line 320 of file simulator.h.
perf_counter_t Simulator::_perf_gps private
Definition at line 322 of file simulator.h.
perf_counter_t Simulator::_perf_mag private
Definition at line 321 of file simulator.h.
perf_counter_t Simulator::_perf_mpu private
Definition at line 319 of file simulator.h.
perf_counter_t Simulator::_perf_sim_delay private
Definition at line 324 of file simulator.h.
perf_counter_t Simulator::_perf_sim_interval private
Definition at line 325 of file simulator.h.
orb_advert_t Simulator::_rc_channels_pub private
Definition at line 361 of file simulator.h.
struct rc_input_values Simulator::_rc_input private
Definition at line 381 of file simulator.h.
double Simulator::_realtime_factor private
How fast the simulation runs in comparison to real system time.
Definition at line 342 of file simulator.h.
int32_t Simulator::_system_type private
Definition at line 351 of file simulator.h.
int Simulator::_vehicle_attitude_sub private
Definition at line 368 of file simulator.h.
struct vehicle_status_s Simulator::_vehicle_status private
Definition at line 385 of file simulator.h.
int Simulator::_vehicle_status_sub private
Definition at line 370 of file simulator.h.
orb_advert_t Simulator::_vision_attitude_pub private
Definition at line 334 of file simulator.h.
orb_advert_t Simulator::_vision_position_pub private
Definition at line 333 of file simulator.h.
The documentation for this class was generated from the following files:
src/modules/simulator/simulator.h
src/modules/simulator/simulator.cpp
src/modules/simulator/simulator_mavlink.cpp