PX4 Firmware: GroundRoverAttitudeControl Class Reference
GroundRoverAttitudeControl Class Reference
#include <GroundRoverAttitudeControl.hpp>
Public Member Functions
GroundRoverAttitudeControl ()
~GroundRoverAttitudeControl ()
int start ()
bool task_running ()
Private Member Functions
void parameters_update ()
void vehicle_control_mode_poll ()
void manual_control_setpoint_poll ()
void vehicle_attitude_setpoint_poll ()
void battery_status_poll ()
void task_main ()
Static Private Member Functions
static int task_main_trampoline (int argc, char *argv[])
Private Attributes
bool _task_should_exit {false}
if true, attitude control task should exit
bool _task_running {false}
if true, task is running in its mainloop
int _control_task {-1}
task handle
int _att_sp_sub {-1}
vehicle attitude setpoint
int _battery_status_sub {-1}
battery status subscription
int _att_sub {-1}
control state subscription
int _manual_sub {-1}
notification of manual control updates
int _params_sub {-1}
notification of parameter updates
int _vcontrol_mode_sub {-1}
vehicle status subscription
orb_advert_t _actuators_0_pub {nullptr}
actuator control group 0 setpoint
actuator_controls_s _actuators {}
actuator control inputs
battery_status_s _battery_status {}
battery status
manual_control_setpoint_s _manual {}
r/c channel data
vehicle_attitude_s _att {}
control state
vehicle_attitude_setpoint_s _att_sp {}
vehicle attitude setpoint
vehicle_control_mode_s _vcontrol_mode {}
vehicle control mode
perf_counter_t _loop_perf
loop performance counter
perf_counter_t _nonfinite_input_perf
performance counter for non finite input
perf_counter_t _nonfinite_output_perf
performance counter for non finite output
bool _debug {false}
if set to true, print debug output
struct {
float w_p
Proportional gain of the steering controller.
float w_i
Integral gain of the steering controller.
float w_d
Derivative of the steering controller.
float w_imax
maximum integrator level of the steering controller
float trim_yaw
float man_yaw_scale
scale factor applied to yaw actuator control in pure manual mode
int32_t bat_scale_en
Battery scaling enabled.
} _parameters
local copies of interesting parameters
struct {
param_t w_p
param_t w_i
param_t w_d
param_t w_imax
param_t trim_yaw
param_t man_yaw_scale
param_t bat_scale_en
} _parameter_handles
handles for interesting parameters
PID_t _steering_ctrl {}
Detailed Description
Definition at line 68 of file GroundRoverAttitudeControl.hpp.
Constructor & Destructor Documentation
GroundRoverAttitudeControl::GroundRoverAttitudeControl ()
Definition at line 58 of file GroundRoverAttitudeControl.cpp.
References _parameter_handles, param_find(), and parameters_update().
Referenced by gnd_att_control_main().
GroundRoverAttitudeControl::~GroundRoverAttitudeControl ()
Definition at line 80 of file GroundRoverAttitudeControl.cpp.
References _control_task, _loop_perf, _nonfinite_input_perf, _nonfinite_output_perf, _task_should_exit, att_gnd_control::g_control, perf_free(), px4_task_delete(), and usleep().
Member Function Documentation
void GroundRoverAttitudeControl::battery_status_poll () private
Definition at line 166 of file GroundRoverAttitudeControl.cpp.
References _battery_status, _battery_status_sub, orb_check(), orb_copy(), and ORB_ID.
Referenced by task_main().
void GroundRoverAttitudeControl::manual_control_setpoint_poll () private
Definition at line 144 of file GroundRoverAttitudeControl.cpp.
References _manual, _manual_sub, orb_check(), orb_copy(), and ORB_ID.
Referenced by task_main().
void GroundRoverAttitudeControl::parameters_update () private
Definition at line 110 of file GroundRoverAttitudeControl.cpp.
References _parameter_handles, _parameters, _steering_ctrl, f(), param_get(), pid_init(), PID_MODE_DERIVATIV_SET, and pid_set_parameters().
Referenced by GroundRoverAttitudeControl(), and task_main().
int GroundRoverAttitudeControl::start ()
Definition at line 353 of file GroundRoverAttitudeControl.cpp.
References _control_task, PX4_OK, px4_task_spawn_cmd(), SCHED_DEFAULT, SCHED_PRIORITY_MAX, task_main_trampoline(), and warn.
Referenced by gnd_att_control_main().
void GroundRoverAttitudeControl::task_main () private
Definition at line 185 of file GroundRoverAttitudeControl.cpp.
References _actuators, _actuators_0_pub, _att, _att_sp, _att_sp_sub, _att_sub, _battery_status, _battery_status_sub, _control_task, _debug, _loop_perf, _manual, _manual_sub, _nonfinite_output_perf, _parameters, _params_sub, _steering_ctrl, _task_running, _task_should_exit, _vcontrol_mode, _vcontrol_mode_sub, battery_status_poll(), math::constrain(), actuator_controls_s::control, f(), vehicle_control_mode_s::flag_control_attitude_enabled, vehicle_control_mode_s::flag_control_manual_enabled, vehicle_control_mode_s::flag_control_rates_enabled, hrt_absolute_time(), manual_control_setpoint_poll(), orb_advertise(), orb_copy(), ORB_ID, ORB_ID_VEHICLE_ATTITUDE_CONTROLS, orb_publish(), orb_subscribe(), parameters_update(), perf_begin(), perf_count(), perf_end(), pid_calculate(), px4_poll(), vehicle_attitude_s::q, manual_control_setpoint_s::r, battery_status_s::scale, vehicle_attitude_setpoint_s::thrust, vehicle_attitude_s::timestamp, actuator_controls_s::timestamp, actuator_controls_s::timestamp_sample, vehicle_attitude_setpoint_poll(), vehicle_control_mode_poll(), warn, warnx, manual_control_setpoint_s::x, manual_control_setpoint_s::y, vehicle_attitude_setpoint_s::yaw_body, vehicle_attitude_s::yawspeed, and manual_control_setpoint_s::z.
Referenced by task_main_trampoline().
int GroundRoverAttitudeControl::task_main_trampoline (int argc, char * argv[]) static private
Definition at line 178 of file GroundRoverAttitudeControl.cpp.
References att_gnd_control::g_control, and task_main().
Referenced by start().
bool GroundRoverAttitudeControl::task_running () inline
Definition at line 75 of file GroundRoverAttitudeControl.hpp.
References _task_running.
Referenced by gnd_att_control_main().
void GroundRoverAttitudeControl::vehicle_attitude_setpoint_poll () private
Definition at line 155 of file GroundRoverAttitudeControl.cpp.
References _att_sp, _att_sp_sub, orb_check(), orb_copy(), and ORB_ID.
Referenced by task_main().
void GroundRoverAttitudeControl::vehicle_control_mode_poll () private
Definition at line 133 of file GroundRoverAttitudeControl.cpp.
References _vcontrol_mode, _vcontrol_mode_sub, orb_check(), orb_copy(), and ORB_ID.
Referenced by task_main().
Member Data Documentation
actuator_controls_s GroundRoverAttitudeControl::_actuators {} private
actuator control inputs
Definition at line 92 of file GroundRoverAttitudeControl.hpp.
Referenced by task_main().
orb_advert_t GroundRoverAttitudeControl::_actuators_0_pub {nullptr} private
actuator control group 0 setpoint
Definition at line 90 of file GroundRoverAttitudeControl.hpp.
Referenced by task_main().
vehicle_attitude_s GroundRoverAttitudeControl::_att {} private
control state
Definition at line 95 of file GroundRoverAttitudeControl.hpp.
Referenced by task_main().
vehicle_attitude_setpoint_s GroundRoverAttitudeControl::_att_sp {} private
vehicle attitude setpoint
Definition at line 96 of file GroundRoverAttitudeControl.hpp.
Referenced by task_main(), and vehicle_attitude_setpoint_poll().
int GroundRoverAttitudeControl::_att_sp_sub {-1} private
vehicle attitude setpoint
Definition at line 83 of file GroundRoverAttitudeControl.hpp.
Referenced by task_main(), and vehicle_attitude_setpoint_poll().
int GroundRoverAttitudeControl::_att_sub {-1} private
control state subscription
Definition at line 85 of file GroundRoverAttitudeControl.hpp.
Referenced by task_main().
battery_status_s GroundRoverAttitudeControl::_battery_status {} private
battery status
Definition at line 93 of file GroundRoverAttitudeControl.hpp.
Referenced by battery_status_poll(), and task_main().
int GroundRoverAttitudeControl::_battery_status_sub {-1} private
battery status subscription
Definition at line 84 of file GroundRoverAttitudeControl.hpp.
Referenced by battery_status_poll(), and task_main().
int GroundRoverAttitudeControl::_control_task {-1} private
task handle
Definition at line 81 of file GroundRoverAttitudeControl.hpp.
Referenced by start(), task_main(), and ~GroundRoverAttitudeControl().
bool GroundRoverAttitudeControl::_debug {false} private
if set to true, print debug output
Definition at line 103 of file GroundRoverAttitudeControl.hpp.
Referenced by task_main().
perf_counter_t GroundRoverAttitudeControl::_loop_perf private
loop performance counter
Definition at line 99 of file GroundRoverAttitudeControl.hpp.
Referenced by task_main(), and ~GroundRoverAttitudeControl().
manual_control_setpoint_s GroundRoverAttitudeControl::_manual {} private
r/c channel data
Definition at line 94 of file GroundRoverAttitudeControl.hpp.
Referenced by manual_control_setpoint_poll(), and task_main().
int GroundRoverAttitudeControl::_manual_sub {-1} private
notification of manual control updates
Definition at line 86 of file GroundRoverAttitudeControl.hpp.
Referenced by manual_control_setpoint_poll(), and task_main().
perf_counter_t GroundRoverAttitudeControl::_nonfinite_input_perf private
performance counter for non finite input
Definition at line 100 of file GroundRoverAttitudeControl.hpp.
Referenced by ~GroundRoverAttitudeControl().
perf_counter_t GroundRoverAttitudeControl::_nonfinite_output_perf private
performance counter for non finite output
Definition at line 101 of file GroundRoverAttitudeControl.hpp.
Referenced by task_main(), and ~GroundRoverAttitudeControl().
struct { ... } GroundRoverAttitudeControl::_parameter_handles
handles for interesting parameters
Referenced by GroundRoverAttitudeControl(), and parameters_update().
struct { ... } GroundRoverAttitudeControl::_parameters
local copies of interesting parameters
Referenced by parameters_update(), and task_main().
int GroundRoverAttitudeControl::_params_sub {-1} private
notification of parameter updates
Definition at line 87 of file GroundRoverAttitudeControl.hpp.
Referenced by task_main().
PID_t GroundRoverAttitudeControl::_steering_ctrl {} private
Definition at line 131 of file GroundRoverAttitudeControl.hpp.
Referenced by parameters_update(), and task_main().
bool GroundRoverAttitudeControl::_task_running {false} private
if true, task is running in its mainloop
Definition at line 80 of file GroundRoverAttitudeControl.hpp.
Referenced by task_main(), and task_running().
bool GroundRoverAttitudeControl::_task_should_exit {false} private
if true, attitude control task should exit
Definition at line 79 of file GroundRoverAttitudeControl.hpp.
Referenced by task_main(), and ~GroundRoverAttitudeControl().
vehicle_control_mode_s GroundRoverAttitudeControl::_vcontrol_mode {} private
vehicle control mode
Definition at line 97 of file GroundRoverAttitudeControl.hpp.
Referenced by task_main(), and vehicle_control_mode_poll().
int GroundRoverAttitudeControl::_vcontrol_mode_sub {-1} private
vehicle status subscription
Definition at line 88 of file GroundRoverAttitudeControl.hpp.
Referenced by task_main(), and vehicle_control_mode_poll().
int32_t GroundRoverAttitudeControl::bat_scale_en
Battery scaling enabled.
Definition at line 114 of file GroundRoverAttitudeControl.hpp.
param_t GroundRoverAttitudeControl::bat_scale_en
Definition at line 127 of file GroundRoverAttitudeControl.hpp.
float GroundRoverAttitudeControl::man_yaw_scale
scale factor applied to yaw actuator control in pure manual mode
Definition at line 112 of file GroundRoverAttitudeControl.hpp.
param_t GroundRoverAttitudeControl::man_yaw_scale
Definition at line 125 of file GroundRoverAttitudeControl.hpp.
float GroundRoverAttitudeControl::trim_yaw
Definition at line 111 of file GroundRoverAttitudeControl.hpp.
param_t GroundRoverAttitudeControl::trim_yaw
Definition at line 124 of file GroundRoverAttitudeControl.hpp.
float GroundRoverAttitudeControl::w_d
Derivative of the steering controller.
Definition at line 108 of file GroundRoverAttitudeControl.hpp.
param_t GroundRoverAttitudeControl::w_d
Definition at line 121 of file GroundRoverAttitudeControl.hpp.
float GroundRoverAttitudeControl::w_i
Integral gain of the steering controller.
Definition at line 107 of file GroundRoverAttitudeControl.hpp.
param_t GroundRoverAttitudeControl::w_i
Definition at line 120 of file GroundRoverAttitudeControl.hpp.
float GroundRoverAttitudeControl::w_imax
maximum integrator level of the steering controller
Definition at line 109 of file GroundRoverAttitudeControl.hpp.
param_t GroundRoverAttitudeControl::w_imax
Definition at line 122 of file GroundRoverAttitudeControl.hpp.
float GroundRoverAttitudeControl::w_p
Proportional gain of the steering controller.
Definition at line 106 of file GroundRoverAttitudeControl.hpp.
param_t GroundRoverAttitudeControl::w_p
Definition at line 119 of file GroundRoverAttitudeControl.hpp.
The documentation for this class was generated from the following files:
src/modules/gnd_att_control/GroundRoverAttitudeControl.hpp
src/modules/gnd_att_control/GroundRoverAttitudeControl.cpp