PX4 Firmware: Airspeed Class Reference
Airspeed Class Reference abstract
#include <airspeed.h>
Public Member Functions
Airspeed (int bus, int address, unsigned conversion_interval, const char *path)
virtual ~Airspeed ()
virtual int init ()
virtual int ioctl (device::file_t *filp, int cmd, unsigned long arg)
Protected Member Functions
virtual int probe ()
virtual void cycle ()=0
Perform a poll cycle; collect from the previous measurement and start a new one.
virtual int measure ()=0
virtual int collect ()=0
void start ()
Initialise the automatic measurement state machine and start it.
void stop ()
Stop the automatic measurement state machine.
void new_report (const differential_pressure_s &report)
add a new report to the reports queue
Static Protected Member Functions
static void cycle_trampoline (void *arg)
Static trampoline from the workq context; because we don't have a generic workq wrapper yet.
Protected Attributes
work_s _work
bool _sensor_ok
int _measure_ticks
bool _collect_phase
float _diff_pres_offset
orb_advert_t _airspeed_pub
int _airspeed_orb_class_instance
int _class_instance
unsigned _conversion_interval
perf_counter_t _sample_perf
perf_counter_t _comms_errors
Private Member Functions
Airspeed (const Airspeed &)
Airspeed & operator= (const Airspeed &)
Detailed Description
Definition at line 50 of file airspeed.h.
Constructor & Destructor Documentation
Airspeed::Airspeed (int bus, int address, unsigned conversion_interval, const char * path)
Definition at line 59 of file airspeed.cpp.
Airspeed::~Airspeed () virtual
Definition at line 79 of file airspeed.cpp.
References _airspeed_pub, _class_instance, _comms_errors, _sample_perf, AIRSPEED_BASE_DEVICE_PATH, orb_unadvertise(), perf_free(), and stop().
Airspeed::Airspeed (const Airspeed &) private
Member Function Documentation
virtual int Airspeed::collect () protected pure virtual
Implemented in MEASAirspeed, SDP3X, ETSAirspeed, and MS5525.
virtual void Airspeed::cycle () protected pure virtual
Perform a poll cycle; collect from the previous measurement and start a new one.
Implemented in MEASAirspeed, SDP3X, ETSAirspeed, and MS5525.
Referenced by cycle_trampoline().
void Airspeed::cycle_trampoline (void * arg) static protected
Static trampoline from the workq context; because we don't have a generic workq wrapper yet.
Parameters
arg Instance pointer for the driver that is polling.
Definition at line 248 of file airspeed.cpp.
References cycle().
Referenced by MS5525::cycle(), ETSAirspeed::cycle(), SDP3X::cycle(), MEASAirspeed::cycle(), and start().
int Airspeed::init () virtual
Definition at line 96 of file airspeed.cpp.
References _airspeed_orb_class_instance, _airspeed_pub, _class_instance, AIRSPEED_BASE_DEVICE_PATH, lis3mdl::init(), measure(), orb_advertise_multi(), ORB_ID, ORB_PRIO_HIGH, PX4_ERROR, PX4_OK, and PX4_WARN.
Referenced by PX4IO::set_update_rate(), sdp3x_airspeed::start_bus(), ms5525_airspeed::start_bus(), ets_airspeed::start_bus(), meas_airspeed::start_bus(), and tone_alarm_main().
int Airspeed::ioctl (device::file_t * filp, int cmd, unsigned long arg) virtual
Definition at line 137 of file airspeed.cpp.
References _conversion_interval, _diff_pres_offset, _measure_ticks, AIRSPEEDIOCGSCALE, AIRSPEEDIOCSSCALE, airspeed_scale::offset_pa, OK, airspeed_scale::scale, SENSOR_POLLRATE_DEFAULT, SENSOR_POLLRATE_EXTERNAL, SENSOR_POLLRATE_MANUAL, SENSOR_POLLRATE_MAX, SENSORIOCGPOLLRATE, SENSORIOCRESET, SENSORIOCSPOLLRATE, start(), and stop().
Referenced by px4io_main(), and PX4IO::set_update_rate().
virtual int Airspeed::measure () protected pure virtual
Implemented in MEASAirspeed, SDP3X, ETSAirspeed, and MS5525.
Referenced by init(), and probe().
void Airspeed::new_report (const differential_pressure_s & report) protected
add a new report to the reports queue
Parameters
report differential_pressure_s report
Airspeed& Airspeed::operator= (const Airspeed &) private
int Airspeed::probe () protected virtual
Reimplemented in SDP3X.
Definition at line 122 of file airspeed.cpp.
References measure().
void Airspeed::start () protected
Initialise the automatic measurement state machine and start it.
Note
This function is called at open and error time. It might make sense to make it more aggressive about resetting the bus in case of errors.
Definition at line 232 of file airspeed.cpp.
References _collect_phase, and cycle_trampoline().
Referenced by MS5525::cycle(), ETSAirspeed::cycle(), MEASAirspeed::cycle(), and ioctl().
void Airspeed::stop () protected
Stop the automatic measurement state machine.
Definition at line 242 of file airspeed.cpp.
Referenced by ioctl(), and ~Airspeed().
Member Data Documentation
int Airspeed::_airspeed_orb_class_instance protected
Definition at line 83 of file airspeed.h.
Referenced by init().
orb_advert_t Airspeed::_airspeed_pub protected
Definition at line 82 of file airspeed.h.
Referenced by MS5525::collect(), ETSAirspeed::collect(), SDP3X::collect(), MEASAirspeed::collect(), init(), and ~Airspeed().
int Airspeed::_class_instance protected
Definition at line 85 of file airspeed.h.
Referenced by init(), and ~Airspeed().
bool Airspeed::_collect_phase protected
Definition at line 79 of file airspeed.h.
Referenced by MS5525::cycle(), ETSAirspeed::cycle(), MEASAirspeed::cycle(), and start().
perf_counter_t Airspeed::_comms_errors protected
Definition at line 90 of file airspeed.h.
Referenced by MS5525::collect(), ETSAirspeed::collect(), SDP3X::collect(), MEASAirspeed::collect(), ETSAirspeed::cycle(), MS5525::init_ms5525(), SDP3X::init_sdp3x(), MS5525::measure(), ETSAirspeed::measure(), MEASAirspeed::measure(), and ~Airspeed().
unsigned Airspeed::_conversion_interval protected
Definition at line 87 of file airspeed.h.
Referenced by ioctl().
float Airspeed::_diff_pres_offset protected
Definition at line 80 of file airspeed.h.
Referenced by MS5525::collect(), ETSAirspeed::collect(), SDP3X::collect(), MEASAirspeed::collect(), and ioctl().
int Airspeed::_measure_ticks protected
Definition at line 78 of file airspeed.h.
Referenced by MS5525::cycle(), ETSAirspeed::cycle(), MEASAirspeed::cycle(), and ioctl().
perf_counter_t Airspeed::_sample_perf protected
Definition at line 89 of file airspeed.h.
Referenced by MS5525::collect(), ETSAirspeed::collect(), SDP3X::collect(), MEASAirspeed::collect(), and ~Airspeed().
bool Airspeed::_sensor_ok protected
Definition at line 77 of file airspeed.h.
Referenced by MS5525::cycle(), ETSAirspeed::cycle(), SDP3X::cycle(), and MEASAirspeed::cycle().
work_s Airspeed::_work protected
Definition at line 76 of file airspeed.h.
The documentation for this class was generated from the following files:
src/lib/drivers/airspeed/airspeed.h
src/lib/drivers/airspeed/airspeed.cpp