PX4 Firmware: ETSAirspeed Class Reference
ETSAirspeed Class Reference
Public Member Functions
ETSAirspeed (int bus, int address=I2C_ADDRESS, const char *path=ETS_PATH)
Public Member Functions inherited from Airspeed
Airspeed (int bus, int address, unsigned conversion_interval, const char *path)
virtual ~Airspeed ()
virtual int init ()
virtual int ioctl (device::file_t *filp, int cmd, unsigned long arg)
Protected Member Functions
virtual void cycle ()
Perform a poll cycle; collect from the previous measurement and start a new one.
virtual int measure ()
virtual int collect ()
Protected Member Functions inherited from Airspeed
virtual int probe ()
void start ()
Initialise the automatic measurement state machine and start it.
void stop ()
Stop the automatic measurement state machine.
void new_report (const differential_pressure_s &report)
add a new report to the reports queue
Additional Inherited Members
Static Protected Member Functions inherited from Airspeed
static void cycle_trampoline (void *arg)
Static trampoline from the workq context; because we don't have a generic workq wrapper yet.
Protected Attributes inherited from Airspeed
work_s _work
bool _sensor_ok
int _measure_ticks
bool _collect_phase
float _diff_pres_offset
orb_advert_t _airspeed_pub
int _airspeed_orb_class_instance
int _class_instance
unsigned _conversion_interval
perf_counter_t _sample_perf
perf_counter_t _comms_errors
Detailed Description
Definition at line 76 of file ets_airspeed.cpp.
Constructor & Destructor Documentation
ETSAirspeed::ETSAirspeed (int bus, int address = I2C_ADDRESS, const char * path = ETS_PATH)
Definition at line 98 of file ets_airspeed.cpp.
References DRV_DIFF_PRESS_DEVTYPE_MS4525.
Referenced by ets_airspeed::start_bus().
Member Function Documentation
int ETSAirspeed::collect () protected virtual
Implements Airspeed.
Definition at line 123 of file ets_airspeed.cpp.
References Airspeed::_airspeed_pub, Airspeed::_comms_errors, Airspeed::_diff_pres_offset, Airspeed::_sample_perf, differential_pressure_s::device_id, differential_pressure_s::differential_pressure_filtered_pa, differential_pressure_s::differential_pressure_raw_pa, differential_pressure_s::error_count, hrt_absolute_time(), OK, ORB_ID, orb_publish(), perf_begin(), perf_count(), perf_end(), perf_event_count(), differential_pressure_s::temperature, and differential_pressure_s::timestamp.
Referenced by cycle().
void ETSAirspeed::cycle () protected virtual
Perform a poll cycle; collect from the previous measurement and start a new one.
Implements Airspeed.
Definition at line 177 of file ets_airspeed.cpp.
References Airspeed::_collect_phase, Airspeed::_comms_errors, Airspeed::_measure_ticks, Airspeed::_sensor_ok, collect(), CONVERSION_INTERVAL, Airspeed::cycle_trampoline(), DEVICE_DEBUG, measure(), OK, perf_count(), and Airspeed::start().
int ETSAirspeed::measure () protected virtual
Implements Airspeed.
Definition at line 105 of file ets_airspeed.cpp.
References Airspeed::_comms_errors, OK, perf_count(), and READ_CMD.
Referenced by cycle().
The documentation for this class was generated from the following file:
src/drivers/differential_pressure/ets/ets_airspeed.cpp