PX4 Firmware: src/drivers/driver_framework_wrapper/df_lsm9ds1_wrapper/df_lsm9ds1_wrapper.cpp File Reference
df_lsm9ds1_wrapper.cpp File Reference
Lightweight driver to access the MPU9250 of the DriverFramework.
#include <px4_platform_common/px4_config.h>
#include <sys/types.h>
#include <sys/stat.h>
#include <stdint.h>
#include <stddef.h>
#include <stdlib.h>
#include <string.h>
#include <math.h>
#include <unistd.h>
#include <px4_platform_common/getopt.h>
#include <errno.h>
#include <systemlib/err.h>
#include <lib/parameters/param.h>
#include <perf/perf_counter.h>
#include <systemlib/mavlink_log.h>
#include <drivers/drv_hrt.h>
#include <drivers/drv_accel.h>
#include <drivers/drv_gyro.h>
#include <drivers/drv_mag.h>
#include <drivers/device/integrator.h>
#include <lib/conversion/rotation.h>
#include <uORB/topics/parameter_update.h>
#include <lsm9ds1/LSM9DS1.hpp>
#include <DevMgr.hpp>
Classes
class DfLsm9ds1Wrapper
struct DfLsm9ds1Wrapper::accel_calibration_s
struct DfLsm9ds1Wrapper::gyro_calibration_s
struct DfLsm9ds1Wrapper::mag_calibration_s
Namespaces
df_lsm9ds1_wrapper
Macros
#define LSM9DS1_NEVER_AUTOPUBLISH_US 0
Functions
__EXPORT int df_lsm9ds1_wrapper_main (int argc, char *argv[])
int df_lsm9ds1_wrapper::start (bool mag_enabled, enum Rotation rotation)
int df_lsm9ds1_wrapper::stop ()
Stop the driver.
int df_lsm9ds1_wrapper::info ()
Print a little info about the driver.
void df_lsm9ds1_wrapper::usage ()
Prints info about the driver argument usage.
Variables
DfLsm9ds1Wrapper * df_lsm9ds1_wrapper::g_dev = nullptr
Detailed Description
Lightweight driver to access the MPU9250 of the DriverFramework.
Author
Miguel Arroyo migue.nosp@m.l@ar.nosp@m.royo..nosp@m.me
Definition in file df_lsm9ds1_wrapper.cpp.
Macro Definition Documentation
LSM9DS1_NEVER_AUTOPUBLISH_US
#define LSM9DS1_NEVER_AUTOPUBLISH_US 0
Definition at line 73 of file df_lsm9ds1_wrapper.cpp.
Referenced by DfLsm9ds1Wrapper::DfLsm9ds1Wrapper().
Function Documentation
df_lsm9ds1_wrapper_main()
int df_lsm9ds1_wrapper_main (int argc, char * argv[])
Definition at line 831 of file df_lsm9ds1_wrapper.cpp.
References df_lsm9ds1_wrapper::info(), ROTATION_NONE, df_lsm9ds1_wrapper::start(), df_lsm9ds1_wrapper::stop(), and df_lsm9ds1_wrapper::usage().