PX4 Firmware: src/drivers/boards/common/board_common.h File Reference
board_common.h File Reference
Provide the the common board interfaces.
#include <errno.h>
#include <stdint.h>
#include "board_internal_common.h"
Classes
struct px4_hw_mft_item_t
Macros
#define PX4_SPIDEV_ID(type, index) ((((type) & 0xffff) << 16) | ((index) & 0xffff))
#define PX4_SPI_DEVICE_ID (1 << 12)
#define PX4_MK_SPI_SEL(b, d) PX4_SPIDEV_ID(PX4_SPI_DEVICE_ID, ((((b) & 0xff) << 8) | ((d) & 0xff)))
#define PX4_SPI_BUS_ID(devid) (((devid) >> 8) & 0xff)
#define PX4_SPI_DEV_ID(devid) ((devid) & 0xff)
#define PX4_CHECK_ID(devid) ((devid) & PX4_SPI_DEVICE_ID)
#define BOARD_NUMBER_I2C_BUSES PX4_NUMBER_I2C_BUSES
#define ADC_V5_V_FULL_SCALE (6.6f)
#define ADC_V5_SCALE (2.0f)
#define ADC_3V3_V_FULL_SCALE (3.6f)
#define ADC_3V3_SCALE (2.0f)
#define BOARD_ADC_OPEN_CIRCUIT_V (1.5f)
#define BOARD_VALID_UV (3.7f)
#define BOARD_NUMBER_BRICKS 1
#define BOARD_ADC_BRICK_VALID (1)
#define BOARD_BATT_V_LIST {ADC_BATTERY_VOLTAGE_CHANNEL}
#define BOARD_BATT_I_LIST {ADC_BATTERY_CURRENT_CHANNEL}
#define BOARD_BRICK_VALID_LIST {BOARD_ADC_BRICK_VALID}
#define BOARD_BATTERY1_V_DIV 0.0f
#define BOARD_BATTERY2_V_DIV 0.0f
#define BOARD_BATTERY1_A_PER_V 0.0f
#define BOARD_BATTERY2_A_PER_V 0.0f
#define BOARD_EEPROM_WP_CTRL(on_true)
#define PX4_GUID_BYTE_LENGTH 18
#define PX4_GUID_FORMAT_SIZE ((2*PX4_GUID_BYTE_LENGTH)+1)
#define board_supports_single_wire(_uxart_base) false
#define board_dma_alloc_init() (-EPERM)
#define board_get_dma_usage(dma_total, dma_used, dma_peak_used) (-ENOMEM)
#define INVERT_RC_INPUT(_invert_true, _na) while(0)
#define RC_UXART_BASE 0
#define board_on_reset(status)
#define px4_hw_mft_uninitialized (px4_hw_mft_item) -1
#define px4_hw_mft_unsupported (px4_hw_mft_item) 0
#define PX4_MFT_HW_SUPPORTED(ID) (0)
#define PX4_MFT_HW_REQUIRED(ID) (0)
#define PX4_MFT_HW_IS_ONBOARD(ID) (0)
#define PX4_MFT_HW_IS_OFFBOARD(ID) (0)
#define PX4_MFT_HW_IS_CONNECTION_KNOWN(ID) (0)
#define board_query_manifest(_na) px4_hw_mft_unsupported
#define board_get_hw_type_name() ""
#define board_get_hw_version() (-1)
#define board_get_hw_revision() (-1)
#define px4_i2c_bus_external(bus) true
#define px4_spi_bus_external(bus) false
Typedefs
typedef enum board_reset_e board_reset_e
typedef enum board_power_button_state_notification_e board_power_button_state_notification_e
typedef int(* power_button_state_notification_t) (board_power_button_state_notification_e request)
typedef uint8_t uuid_byte_t[PX4_CPU_UUID_BYTE_LENGTH]
typedef uint32_t uuid_uint32_t[PX4_CPU_UUID_WORD32_LENGTH]
typedef uint8_t mfguid_t[PX4_CPU_MFGUID_BYTE_LENGTH]
typedef uint8_t px4_guid_t[PX4_GUID_BYTE_LENGTH]
typedef const px4_hw_mft_item_t * px4_hw_mft_item
Enumerations
enum board_reset_e { board_reset_normal = 0, board_reset_extended = 1, board_reset_power_off = 2, board_reset_enter_bootloader = 3 }
enum board_power_button_state_notification_e {
PWR_BUTTON_IDEL, PWR_BUTTON_DOWN, PWR_BUTTON_UP, PWR_BUTTON_REQUEST_SHUT_DOWN,
PWR_BUTTON_RESPONSE_SHUT_DOWN_PENDING, PWR_BUTTON_RESPONSE_SHUT_DOWN_NOW
}
enum px4_hw_mft_item_id_t { PX4_MFT_PX4IO = 0 }
enum px4_hw_connection_t { px4_hw_con_unknown = 0, px4_hw_con_onboard = 1, px4_hw_con_conector = 3 }
Functions
int board_read_VBUS_state (void)
__EXPORT void board_system_reset (int status) noreturn_function
__EXPORT int board_set_bootload_mode (board_reset_e mode)
__EXPORT void board_get_uuid (uuid_byte_t uuid_bytes)
__EXPORT void board_get_uuid32 (uuid_uint32_t uuid_words)
__EXPORT int board_get_uuid32_formated (char *format_buffer, int size, const char *format, const char *seperator)
int board_get_mfguid (mfguid_t mfgid)
int board_get_mfguid_formated (char *format_buffer, int size)
int board_get_px4_guid (px4_guid_t guid)
int board_get_px4_guid_formated (char *format_buffer, int size)
__EXPORT int board_mcu_version (char *rev, const char **revstr, const char **errata)
static int board_register_power_state_notification_cb (power_button_state_notification_t cb)
static int board_shutdown (void)
Detailed Description
Provide the the common board interfaces.
Definition in file board_common.h.
Macro Definition Documentation
#define ADC_3V3_SCALE (2.0f)
Definition at line 145 of file board_common.h.
#define ADC_3V3_V_FULL_SCALE (3.6f)
Definition at line 142 of file board_common.h.
#define ADC_V5_SCALE (2.0f)
Definition at line 138 of file board_common.h.
#define ADC_V5_V_FULL_SCALE (6.6f)
Definition at line 135 of file board_common.h.
#define BOARD_ADC_BRICK_VALID (1)
Definition at line 169 of file board_common.h.
#define BOARD_ADC_OPEN_CIRCUIT_V (1.5f)
Definition at line 153 of file board_common.h.
#define BOARD_BATT_I_LIST {ADC_BATTERY_CURRENT_CHANNEL}
Definition at line 177 of file board_common.h.
Referenced by Sensors::adc_poll().
#define BOARD_BATT_V_LIST {ADC_BATTERY_VOLTAGE_CHANNEL}
Definition at line 176 of file board_common.h.
Referenced by Sensors::adc_poll().
#define BOARD_BATTERY1_A_PER_V 0.0f
Definition at line 227 of file board_common.h.
#define BOARD_BATTERY1_V_DIV 0.0f
Definition at line 215 of file board_common.h.
#define BOARD_BATTERY2_A_PER_V 0.0f
Definition at line 231 of file board_common.h.
#define BOARD_BATTERY2_V_DIV 0.0f
Definition at line 219 of file board_common.h.
#define BOARD_BRICK_VALID_LIST {BOARD_ADC_BRICK_VALID}
Definition at line 178 of file board_common.h.
Referenced by Sensors::adc_poll().
#define board_dma_alloc_init () (-EPERM)
Definition at line 465 of file board_common.h.
Referenced by board_app_initialize().
#define BOARD_EEPROM_WP_CTRL (on_true)
Definition at line 266 of file board_common.h.
Referenced by at24c_bwrite(), at24c_eraseall(), and at24c_initialize().
#define board_get_dma_usage (dma_total, dma_used, dma_peak_used) (-ENOMEM)
Definition at line 491 of file board_common.h.
Referenced by print_load_buffer().
#define board_get_hw_revision () (-1)
Definition at line 742 of file board_common.h.
#define board_get_hw_type_name () ""
Definition at line 698 of file board_common.h.
#define board_get_hw_version () (-1)
Definition at line 720 of file board_common.h.
#define BOARD_NUMBER_BRICKS 1
Definition at line 167 of file board_common.h.
#define BOARD_NUMBER_I2C_BUSES PX4_NUMBER_I2C_BUSES
Definition at line 109 of file board_common.h.
#define board_on_reset (status)
Definition at line 566 of file board_common.h.
Referenced by board_system_reset().
#define board_query_manifest (_na) px4_hw_mft_unsupported
Definition at line 678 of file board_common.h.
#define board_supports_single_wire (_uxart_base) false
Definition at line 414 of file board_common.h.
Referenced by RCInput::cycle(), and RCInput::init().
#define BOARD_VALID_UV (3.7f)
Definition at line 161 of file board_common.h.
Referenced by Sensors::adc_poll().
#define INVERT_RC_INPUT (_invert_true, _na) while(0)
Definition at line 536 of file board_common.h.
Referenced by RCInput::fill_rc_in().
#define PX4_CHECK_ID (devid) ((devid) & PX4_SPI_DEVICE_ID)
Definition at line 98 of file board_common.h.
#define PX4_GUID_BYTE_LENGTH 18
Definition at line 365 of file board_common.h.
#define PX4_GUID_FORMAT_SIZE ((2*PX4_GUID_BYTE_LENGTH)+1)
Definition at line 366 of file board_common.h.
#define px4_hw_mft_uninitialized (px4_hw_mft_item) -1
Definition at line 652 of file board_common.h.
#define px4_hw_mft_unsupported (px4_hw_mft_item) 0
Definition at line 653 of file board_common.h.
#define px4_i2c_bus_external (bus) true
Definition at line 1005 of file board_common.h.
Referenced by board_shutdown().
#define PX4_MFT_HW_IS_CONNECTION_KNOWN (ID) (0)
Definition at line 677 of file board_common.h.
#define PX4_MFT_HW_IS_OFFBOARD (ID) (0)
Definition at line 676 of file board_common.h.
#define PX4_MFT_HW_IS_ONBOARD (ID) (0)
Definition at line 675 of file board_common.h.
#define PX4_MFT_HW_REQUIRED (ID) (0)
Definition at line 674 of file board_common.h.
#define PX4_MFT_HW_SUPPORTED (ID) (0)
Definition at line 673 of file board_common.h.
Referenced by PX4FMU::cycle(), PX4FMU::flash_safety_button(), led_init(), PX4FMU::print_status(), px4io_main(), and PX4FMU::safety_check_button().
#define PX4_MK_SPI_SEL (b, d) PX4_SPIDEV_ID(PX4_SPI_DEVICE_ID, ((((b) & 0xff) << 8) | ((d) & 0xff)))
Definition at line 95 of file board_common.h.
#define px4_spi_bus_external (bus) false
Definition at line 1025 of file board_common.h.
#define PX4_SPI_BUS_ID (devid) (((devid) >> 8) & 0xff)
Definition at line 96 of file board_common.h.
Referenced by stm32_spi1select(), stm32_spi2select(), stm32_spi2status(), stm32_spi4select(), stm32_spi4status(), stm32_spi5select(), and stm32_spi6select().
#define PX4_SPI_DEV_ID (devid) ((devid) & 0xff)
Definition at line 97 of file board_common.h.
Referenced by __EXPORT::SPI::init(), stm32_spi1select(), stm32_spi2select(), stm32_spi2status(), stm32_spi4select(), stm32_spi4status(), stm32_spi5select(), and stm32_spi6select().
#define PX4_SPI_DEVICE_ID (1 << 12)
Definition at line 94 of file board_common.h.
#define PX4_SPIDEV_ID (type, index) ((((type) & 0xffff) << 16) | ((index) & 0xffff))
Definition at line 92 of file board_common.h.
#define RC_UXART_BASE 0
Definition at line 537 of file board_common.h.
Typedef Documentation
typedef enum board_power_button_state_notification_e board_power_button_state_notification_e
typedef enum board_reset_e board_reset_e
typedef uint8_t mfguid_t[PX4_CPU_MFGUID_BYTE_LENGTH]
Definition at line 377 of file board_common.h.
typedef int(* power_button_state_notification_t) (board_power_button_state_notification_e request)
Definition at line 322 of file board_common.h.
typedef uint8_t px4_guid_t[PX4_GUID_BYTE_LENGTH]
Definition at line 383 of file board_common.h.
typedef const px4_hw_mft_item_t* px4_hw_mft_item
Definition at line 651 of file board_common.h.
typedef uint8_t uuid_byte_t[PX4_CPU_UUID_BYTE_LENGTH]
Definition at line 369 of file board_common.h.
typedef uint32_t uuid_uint32_t[PX4_CPU_UUID_WORD32_LENGTH]
Definition at line 372 of file board_common.h.
Enumeration Type Documentation
enum board_power_button_state_notification_e
Enumerator
PWR_BUTTON_IDEL
PWR_BUTTON_DOWN
PWR_BUTTON_UP
PWR_BUTTON_REQUEST_SHUT_DOWN
PWR_BUTTON_RESPONSE_SHUT_DOWN_PENDING
PWR_BUTTON_RESPONSE_SHUT_DOWN_NOW
Definition at line 308 of file board_common.h.
enum board_reset_e
Enumerator
board_reset_normal
board_reset_extended
board_reset_power_off
board_reset_enter_bootloader
Definition at line 299 of file board_common.h.
enum px4_hw_connection_t
Enumerator
px4_hw_con_unknown
px4_hw_con_onboard
px4_hw_con_conector
Definition at line 638 of file board_common.h.
enum px4_hw_mft_item_id_t
Enumerator
PX4_MFT_PX4IO
Definition at line 634 of file board_common.h.
Function Documentation
int board_get_mfguid (mfguid_t mfgid)
Definition at line 86 of file board_identity.c.
References board_get_uuid(), and SWAP_UINT32.
Referenced by board_get_mfguid_formated(), UavcanEsc::fill_node_info(), and UavcanNode::getHardwareVersion().
int board_get_mfguid_formated (char * format_buffer, int size)
Definition at line 92 of file board_identity.c.
References board_get_mfguid().
Referenced by ver_main().
int board_get_px4_guid (px4_guid_t guid)
int board_get_px4_guid_formated (char * format_buffer, int size)
__EXPORT void board_get_uuid (uuid_byte_t uuid_bytes)
Definition at line 49 of file board_identity.c.
References board_get_uuid32(), CPU_UUID_BYTE_FORMAT_ORDER, DUMMY_SIM_UIDH, reorder(), and SWAP_UINT32.
Referenced by board_get_mfguid(), and board_get_uuid32().
__EXPORT void board_get_uuid32 (uuid_uint32_t uuid_words)
Definition at line 59 of file board_identity.c.
References board_get_uuid().
Referenced by board_get_uuid(), board_get_uuid32_formated(), and Mavlink::send_autopilot_capabilites().
__EXPORT int board_get_uuid32_formated (char * format_buffer, int size, const char * format, const char * seperator)
Definition at line 64 of file board_identity.c.
References board_get_uuid32().
Referenced by ver_main(), and px4::logger::Logger::write_version().
__EXPORT int board_mcu_version (char * rev, const char ** revstr, const char ** errata)
Definition at line 49 of file board_mcu_version.c.
References DEVID_MASK, ERRATA, MCU_REV_STM32F4_REV_1, MCU_REV_STM32F4_REV_3, MCU_REV_STM32F4_REV_A, MCU_REV_STM32F4_REV_Y, MCU_REV_STM32F4_REV_Z, REVID_MASK, STM32_F4_ERRATA, STM32F103_CON, STM32F103_HD, STM32F103_LD, STM32F103_MD, STM32F103_XLD, STM32F42x_43x, STM32F74xxx_75xxx, and STM32F76xxx_77xxx.
Referenced by ver_main(), and px4::logger::Logger::write_version().
int board_read_VBUS_state (void)
Definition at line 161 of file init.c.
References BOARD_ADC_USB_CONNECTED.
Referenced by usb_connected_main().
static int board_register_power_state_notification_cb (power_button_state_notification_t cb) inline static
Definition at line 987 of file board_common.h.
__EXPORT int board_set_bootload_mode (board_reset_e mode)
Definition at line 45 of file board_reset.c.
References board_reset_enter_bootloader, board_reset_extended, board_reset_normal, OK, and UNUSED.
static int board_shutdown (void) inline static
Definition at line 988 of file board_common.h.
References px4_i2c_bus_external.
__EXPORT void board_system_reset (int status)
Definition at line 68 of file board_reset.c.
References board_on_reset.