PX4 Firmware: MavlinkStreamHomePosition Class Reference
MavlinkStreamHomePosition Class Reference
Public Member Functions
const char * get_name () const override
uint16_t get_id () override
unsigned get_size () override
Get maximal total messages size on update.
Public Member Functions inherited from MavlinkStream
MavlinkStream (Mavlink *mavlink)
virtual ~MavlinkStream ()=default
MavlinkStream (const MavlinkStream &)=delete
MavlinkStream & operator= (const MavlinkStream &)=delete
MavlinkStream (MavlinkStream &&)=delete
MavlinkStream & operator= (MavlinkStream &&)=delete
void set_interval (const int interval)
Get the interval.
int get_interval ()
Get the interval.
int update (const hrt_abstime &t)
Update subscriptions and send message if necessary.
virtual bool const_rate ()
virtual unsigned get_size_avg ()
Get the average message size.
bool first_message_sent () const
void reset_last_sent ()
Reset the time of last sent to 0.
Public Member Functions inherited from ListNode< MavlinkStream *>
void setSibling (MavlinkStream * sibling)
const MavlinkStream * getSibling () const
Static Public Member Functions
static const char * get_name_static ()
static uint16_t get_id_static ()
static MavlinkStream * new_instance (Mavlink *mavlink)
Protected Member Functions
MavlinkStreamHomePosition (Mavlink *mavlink)
bool send (const hrt_abstime t) override
Protected Member Functions inherited from MavlinkStream
virtual void update_data ()
Function to collect/update data for the streams at a high rate independant of actual stream rate.
Private Member Functions
MavlinkStreamHomePosition (MavlinkStreamHomePosition &)=delete
MavlinkStreamHomePosition & operator= (const MavlinkStreamHomePosition &)=delete
Private Attributes
MavlinkOrbSubscription * _home_sub
Additional Inherited Members
Protected Attributes inherited from MavlinkStream
Mavlink *const _mavlink
int _interval {1000000}
if set to negative value = unlimited rate
Protected Attributes inherited from ListNode< MavlinkStream *>
MavlinkStream * _list_node_sibling
Detailed Description
Definition at line 2784 of file mavlink_messages.cpp.
Constructor & Destructor Documentation
MavlinkStreamHomePosition() [1/2]
MavlinkStreamHomePosition::MavlinkStreamHomePosition (MavlinkStreamHomePosition &) private delete
MavlinkStreamHomePosition() [2/2]
MavlinkStreamHomePosition::MavlinkStreamHomePosition (Mavlink * mavlink) inline explicit protected
Definition at line 2825 of file mavlink_messages.cpp.
Member Function Documentation
get_id()
uint16_t MavlinkStreamHomePosition::get_id () inline override virtual
Implements MavlinkStream.
Definition at line 2802 of file mavlink_messages.cpp.
References MavlinkStreamHeartbeat::get_id_static().
get_id_static()
static uint16_t MavlinkStreamHomePosition::get_id_static () inline static
Definition at line 2797 of file mavlink_messages.cpp.
get_name()
const char* MavlinkStreamHomePosition::get_name () const inline override virtual
Implements MavlinkStream.
Definition at line 2787 of file mavlink_messages.cpp.
References get_name_static().
get_name_static()
static const char* MavlinkStreamHomePosition::get_name_static () inline static
Definition at line 2792 of file mavlink_messages.cpp.
Referenced by get_name().
get_size()
unsigned MavlinkStreamHomePosition::get_size () inline override virtual
Get maximal total messages size on update.
Implements MavlinkStream.
Definition at line 2812 of file mavlink_messages.cpp.
References _home_sub.
new_instance()
static MavlinkStream* MavlinkStreamHomePosition::new_instance (Mavlink * mavlink) inline static
Definition at line 2807 of file mavlink_messages.cpp.
operator=()
MavlinkStreamHomePosition& MavlinkStreamHomePosition::operator= (const MavlinkStreamHomePosition &) private delete
send()
bool MavlinkStreamHomePosition::send (const hrt_abstime t) inline override protected virtual
Implements MavlinkStream.
Definition at line 2829 of file mavlink_messages.cpp.
References MavlinkStream::_mavlink, home_position_s::alt, f(), Mavlink::get_channel(), MavlinkOrbSubscription::is_published(), home_position_s::lat, home_position_s::lon, msg, home_position_s::timestamp, MavlinkOrbSubscription::update(), home_position_s::valid_hpos, home_position_s::x, home_position_s::y, home_position_s::yaw, and home_position_s::z.
Member Data Documentation
_home_sub
MavlinkOrbSubscription* MavlinkStreamHomePosition::_home_sub private
Definition at line 2818 of file mavlink_messages.cpp.
The documentation for this class was generated from the following file:
src/modules/mavlink/mavlink_messages.cpp