PX4 Firmware: lps25h Namespace Reference
lps25h Namespace Reference
Local functions in support of the shell command.
Classes
struct lps25h_bus_option
Functions
void start (enum LPS25H_BUS busid)
Start the driver.
bool start_bus (struct lps25h_bus_option &bus)
start driver for a specific bus option
struct lps25h_bus_option & find_bus (enum LPS25H_BUS busid)
find a bus structure for a busid
void test (enum LPS25H_BUS busid)
Perform some basic functional tests on the driver; make sure we can collect data from the sensor in polled and automatic modes.
void reset (enum LPS25H_BUS busid)
Reset the driver.
void info ()
Print a little info about the driver.
void usage ()
Prints info about the driver argument usage.
Variables
struct lps25h::lps25h_bus_option bus_options []
Detailed Description
Local functions in support of the shell command.
Function Documentation
find_bus()
struct lps25h_bus_option & lps25h::find_bus (enum LPS25H_BUS busid)
find a bus structure for a busid
Definition at line 773 of file lps25h.cpp.
References bus_options, errx, LPS25H_BUS_ALL, and NUM_BUS_OPTIONS.
Referenced by reset(), and test().
info()
void lps25h::info ()
Print a little info about the driver.
Definition at line 873 of file lps25h.cpp.
References bus_options, lps25h::lps25h_bus_option::dev, lps25h::lps25h_bus_option::devpath, NUM_BUS_OPTIONS, LPS25H::print_info(), and warnx.
Referenced by lps25h_main().
reset()
void lps25h::reset (enum LPS25H_BUS busid)
Reset the driver.
Definition at line 847 of file lps25h.cpp.
References lps25h::lps25h_bus_option::devpath, err, fd, find_bus(), LPS25H::ioctl(), cdev::CDev::open(), SENSOR_POLLRATE_DEFAULT, SENSORIOCRESET, and SENSORIOCSPOLLRATE.
Referenced by lps25h_main().
start()
void lps25h::start (enum LPS25H_BUS busid)
Start the driver.
This function call only returns once the driver is either successfully up and running or failed to start.
Definition at line 747 of file lps25h.cpp.
References bus_options, LPS25H_BUS_ALL, NUM_BUS_OPTIONS, and start_bus().
Referenced by lps25h_main().
start_bus()
bool lps25h::start_bus (struct lps25h_bus_option & bus)
start driver for a specific bus option
Definition at line 700 of file lps25h.cpp.
References cdev::CDev::close(), lps25h::lps25h_bus_option::dev, errx, fd, LPS25H::ioctl(), LPS25H::LPS25H(), OK, cdev::CDev::open(), SENSOR_POLLRATE_DEFAULT, SENSORIOCSPOLLRATE, and warnx.
Referenced by start().
test()
void lps25h::test (enum LPS25H_BUS busid)
Perform some basic functional tests on the driver; make sure we can collect data from the sensor in polled and automatic modes.
Definition at line 792 of file lps25h.cpp.
References cdev::CDev::close(), lps25h::lps25h_bus_option::devpath, err, errx, fd, find_bus(), cdev::CDev::open(), cdev::CDev::poll(), and LPS25H::read().
Referenced by MavlinkFtpTest::_burst_test(), MavlinkFtpTest::_createdirectory_test(), MavlinkFtpTest::_list_test(), MavlinkFtpTest::_open_terminate_test(), MavlinkFtpTest::_read_test(), MavlinkFtpTest::_removedirectory_test(), MavlinkFtpTest::_removefile_test(), adc_main(), StateMachineHelperTest::armingStateTransitionTest(), lps25h_main(), StateMachineHelperTest::mainStateTransitionTest(), MixingOutput::MixingOutput(), PX4_MAIN(), px4io_main(), ADC::sample(), and PX4IO::set_update_rate().
usage()
void lps25h::usage (void)
Prints info about the driver argument usage.
Definition at line 888 of file lps25h.cpp.
References warnx.
Referenced by lps25h_main().
Variable Documentation
bus_options
struct lps25h::lps25h_bus_option lps25h::bus_options[]
Initial value:
= {
    { LPS25H_BUS_I2C_EXTERNAL, "/dev/lps25h_ext", &LPS25H_I2C_interface, PX4_I2C_BUS_EXPANSION, NULL },
}
Referenced by find_bus(), info(), and start().