PX4 Firmware: src/drivers/kinetis/drv_input_capture.c File Reference
drv_input_capture.c File Reference
#include <px4_config.h>
#include <nuttx/arch.h>
#include <nuttx/irq.h>
#include <sys/types.h>
#include <stdbool.h>
#include <assert.h>
#include <debug.h>
#include <time.h>
#include <queue.h>
#include <errno.h>
#include <string.h>
#include <stdio.h>
#include <arch/board/board.h>
#include <drivers/drv_input_capture.h>
#include "drv_io_timer.h"
#include "drv_input_capture.h"
#include <kinetis.h>
#include "chip/kinetis_sim.h"
#include "chip/kinetis_ftm.h"
Classes
struct channel_handler_entry
Macros
#define _REG(_addr) (*(volatile uint32_t *)(_addr))
#define _REG32(_base, _reg) (*(volatile uint32_t *)(_base + _reg))
#define REG(_tmr, _reg) _REG32(io_timers[_tmr].base, _reg)
#define rFILTER(_tmr) REG(_tmr,KINETIS_FTM_FILTER_OFFSET)
Functions
static void input_capture_chan_handler (void *context, const io_timers_t *timer, uint32_t chan_index, const timer_io_channels_t *chan, hrt_abstime isrs_time, uint16_t isrs_rcnt, uint16_t capture)
static void input_capture_bind (unsigned channel, capture_callback_t callback, void *context)
static void input_capture_unbind (unsigned channel)
int up_input_capture_set (unsigned channel, input_capture_edge edge, capture_filter_t filter, capture_callback_t callback, void *context)
int up_input_capture_get_filter (unsigned channel, capture_filter_t *filter)
int up_input_capture_set_filter (unsigned channel, capture_filter_t filter)
int up_input_capture_get_trigger (unsigned channel, input_capture_edge *edge)
int up_input_capture_set_trigger (unsigned channel, input_capture_edge edge)
int up_input_capture_get_callback (unsigned channel, capture_callback_t *callback, void **context)
int up_input_capture_set_callback (unsigned channel, capture_callback_t callback, void *context)
int up_input_capture_get_stats (unsigned channel, input_capture_stats_t *stats, bool clear)
Variables
static input_capture_stats_t channel_stats [MAX_TIMER_IO_CHANNELS]
static struct channel_handler_entry channel_handlers [MAX_TIMER_IO_CHANNELS]
Macro Definition Documentation
#define _REG (_addr) (*(volatile uint32_t *)(_addr))
Definition at line 84 of file drv_input_capture.c.
#define _REG32 (_base, _reg) (*(volatile uint32_t *)(_base + _reg))
Definition at line 85 of file drv_input_capture.c.
Referenced by input_capture_chan_handler(), up_input_capture_get_trigger(), and up_input_capture_set_trigger().
#define REG (_tmr, _reg) _REG32(io_timers[_tmr].base, _reg)
Definition at line 86 of file drv_input_capture.c.
#define rFILTER (_tmr) REG(_tmr,KINETIS_FTM_FILTER_OFFSET)
Definition at line 91 of file drv_input_capture.c.
Referenced by up_input_capture_get_filter(), and up_input_capture_set_filter().
Function Documentation
static void input_capture_bind (unsigned channel, capture_callback_t callback, void * context) static
Definition at line 131 of file drv_input_capture.c.
References channel_handler_entry::callback, channel_handlers, and channel_handler_entry::context.
Referenced by input_capture_unbind(), up_input_capture_set(), and up_input_capture_set_callback().
static void input_capture_chan_handler (void * context, const io_timers_t * timer, uint32_t chan_index, const timer_io_channels_t * chan, hrt_abstime isrs_time, uint16_t isrs_rcnt, uint16_t capture) static
Definition at line 102 of file drv_input_capture.c.
References _REG32, channel_handler_entry::callback, input_capture_stats_t::chan_in_edges_out, channel_handlers, timer_io_channels_t::gpio_in, input_capture_stats_t::last_edge, input_capture_stats_t::last_time, input_capture_stats_t::latnecy, input_capture_stats_t::overflows, and timer_io_channels_t::timer_channel.
Referenced by up_input_capture_set().
static void input_capture_unbind (unsigned channel) static
Definition at line 139 of file drv_input_capture.c.
References input_capture_bind().
Referenced by up_input_capture_set().
int up_input_capture_get_callback (unsigned channel, capture_callback_t * callback, void ** context)
Definition at line 398 of file drv_input_capture.c.
References channel_handler_entry::callback, channel_handlers, channel_handler_entry::context, io_timer_get_channel_mode(), io_timer_validate_channel_index(), IOTimerChanMode_Capture, and OK.
int up_input_capture_get_filter (unsigned channel, capture_filter_t * filter)
Definition at line 201 of file drv_input_capture.c.
References io_timer_get_channel_mode(), io_timer_validate_channel_index(), IOTimerChanMode_Capture, OK, rFILTER, timer_io_channels_t::timer_index, and timer_io_channels.
int up_input_capture_get_stats (unsigned channel, input_capture_stats_t * stats, bool clear)
Definition at line 441 of file drv_input_capture.c.
References io_timer_validate_channel_index().
int up_input_capture_get_trigger (unsigned channel, input_capture_edge * edge)
Definition at line 310 of file drv_input_capture.c.
References _REG32, Both, Falling, io_timer_get_channel_mode(), io_timer_validate_channel_index(), IOTimerChanMode_Capture, OK, Rising, timer_io_channels_t::timer_index, and timer_io_channels.
int up_input_capture_set (unsigned channel, input_capture_edge edge, capture_filter_t filter, capture_callback_t callback, void * context)
Definition at line 144 of file drv_input_capture.c.
References Both, Disabled, input_capture_bind(), input_capture_chan_handler(), input_capture_unbind(), io_timer_channel_init(), io_timer_free_channel(), io_timer_is_channel_free(), io_timer_set_enable(), io_timer_validate_channel_index(), IOTimerChanMode_Capture, timer_io_channels, up_input_capture_set_filter(), and up_input_capture_set_trigger().
int up_input_capture_set_callback (unsigned channel, capture_callback_t callback, void * context)
Definition at line 422 of file drv_input_capture.c.
References input_capture_bind(), io_timer_get_channel_mode(), io_timer_validate_channel_index(), and IOTimerChanMode_Capture.
int up_input_capture_set_filter (unsigned channel, capture_filter_t filter)
Definition at line 251 of file drv_input_capture.c.
References io_timer_get_channel_mode(), io_timer_validate_channel_index(), IOTimerChanMode_Capture, OK, rFILTER, timer_io_channels_t::timer_index, and timer_io_channels.
Referenced by up_input_capture_set().
int up_input_capture_set_trigger (unsigned channel, input_capture_edge edge)
Definition at line 350 of file drv_input_capture.c.
References _REG32, Both, Disabled, Falling, io_timer_get_channel_mode(), io_timer_validate_channel_index(), IOTimerChanMode_Capture, OK, Rising, timer_io_channels_t::timer_index, and timer_io_channels.
Referenced by up_input_capture_set().
Variable Documentation
struct channel_handler_entry channel_handlers[MAX_TIMER_IO_CHANNELS] static
Referenced by input_capture_bind(), input_capture_chan_handler(), and up_input_capture_get_callback().
input_capture_stats_t channel_stats[MAX_TIMER_IO_CHANNELS] static
Definition at line 93 of file drv_input_capture.c.