PX4 Firmware: src/modules/mavlink/mavlink_simple_analyzer.h File Reference
mavlink_simple_analyzer.h File Reference
#include <float.h>
#include <stdint.h>
Classes
class SimpleAnalyzer
SimpleAnalyzer.
Functions
void convert_limit_safe (float in, uint16_t &out)
void convert_limit_safe (float in, int16_t &out)
Detailed Description
Author
Achermann Florian acflo.nosp@m.ria@.nosp@m.ethz..nosp@m.ch
Definition in file mavlink_simple_analyzer.h.
Function Documentation
convert_limit_safe() [1/2]
void convert_limit_safe (float in, uint16_t & out)
Definition at line 150 of file mavlink_simple_analyzer.cpp.
Referenced by MavlinkStreamHighLatency2::write_fw_ctrl_status(), MavlinkStreamHighLatency2::write_global_position(), and MavlinkStreamHighLatency2::write_tecs_status().
convert_limit_safe() [2/2]
void convert_limit_safe (float in, int16_t & out)
Definition at line 163 of file mavlink_simple_analyzer.cpp.