PX4 Firmware: ak09916 Namespace Reference
ak09916 Namespace Reference
Functions
void start (bool, enum Rotation)
void info (bool)
void usage ()
Prints info about the driver argument usage.
void stop (bool external_bus)
Variables
AK09916 * g_dev_ext
AK09916 * g_dev_int
Function Documentation
info()
void ak09916::info (bool external_bus)
Definition at line 111 of file ak09916.cpp.
References g_dev_ext, and g_dev_int.
Referenced by ak09916_main().
start()
void ak09916::start (bool external_bus, enum Rotation rotation)
Definition at line 62 of file ak09916.cpp.
References AK09916_DEVICE_PATH_MAG, AK09916_DEVICE_PATH_MAG_EXT, g_dev_ext, g_dev_int, and OK.
Referenced by ak09916_main().
stop()
void ak09916::stop (bool external_bus)
Definition at line 96 of file ak09916.cpp.
References g_dev_ext, and g_dev_int.
Referenced by ak09916_main().
usage()
void ak09916::usage (void)
Prints info about the driver argument usage.
Prints info about the driver argument usage.
Definition at line 127 of file ak09916.cpp.
Referenced by ak09916_main().
Variable Documentation
g_dev_ext
AK09916* ak09916::g_dev_ext
Definition at line 55 of file ak09916.cpp.
Referenced by info(), start(), and stop().
g_dev_int
AK09916* ak09916::g_dev_int
Definition at line 56 of file ak09916.cpp.
Referenced by info(), start(), and stop().