PX4 Firmware: src/drivers/px4flow/px4flow.cpp File Reference
px4flow.cpp File Reference
#include <px4_config.h>
#include <px4_defines.h>
#include <px4_getopt.h>
#include <drivers/device/i2c.h>
#include <sys/types.h>
#include <stdint.h>
#include <stdlib.h>
#include <stdbool.h>
#include <semaphore.h>
#include <string.h>
#include <fcntl.h>
#include <poll.h>
#include <errno.h>
#include <stdio.h>
#include <math.h>
#include <unistd.h>
#include <nuttx/arch.h>
#include <nuttx/wqueue.h>
#include <nuttx/clock.h>
#include <perf/perf_counter.h>
#include <systemlib/err.h>
#include <parameters/param.h>
#include <conversion/rotation.h>
#include <drivers/drv_hrt.h>
#include <drivers/drv_px4flow.h>
#include <drivers/drv_range_finder.h>
#include <drivers/device/ringbuffer.h>
#include <uORB/uORB.h>
#include <uORB/topics/optical_flow.h>
#include <uORB/topics/distance_sensor.h>
#include <board_config.h>
#include "i2c_frame.h"
Classes
class PX4FLOW
Namespaces
px4flow
Local functions in support of the shell command.
Macros
#define I2C_FLOW_ADDRESS_DEFAULT 0x42
7-bit address. 8-bit address is 0x84, range 0x42 - 0x49
#define I2C_FLOW_ADDRESS_MIN 0x42
7-bit address.
#define I2C_FLOW_ADDRESS_MAX 0x49
7-bit address.
#define PX4FLOW_REG 0x16
Measure Register 22.
#define PX4FLOW_CONVERSION_INTERVAL_DEFAULT 100000
in microseconds! = 10Hz
#define PX4FLOW_CONVERSION_INTERVAL_MIN 10000
in microseconds! = 100 Hz
#define PX4FLOW_CONVERSION_INTERVAL_MAX 1000000
in microseconds! = 1 Hz
#define PX4FLOW_I2C_MAX_BUS_SPEED 400000
400 KHz maximum speed
#define PX4FLOW_MAX_DISTANCE 5.0f
#define PX4FLOW_MIN_DISTANCE 0.3f
Functions
__EXPORT int px4flow_main (int argc, char *argv[])
int px4flow::start (int argc, char *argv[])
Start the driver.
void px4flow::stop ()
Stop the driver.
void px4flow::test ()
Perform some basic functional tests on the driver; make sure we can collect data from the sensor in polled and automatic modes.
void px4flow::reset ()
Reset the driver.
void px4flow::info ()
Print a little info about the driver.
void px4flow::usage ()
Prints info about the driver argument usage.
Variables
PX4FLOW * px4flow::g_dev = nullptr
bool px4flow::start_in_progress = false
const int px4flow::START_RETRY_COUNT = 5
const int px4flow::START_RETRY_TIMEOUT = 1000
Detailed Description
Author
Dominik Honegger
Ban Siesta bansi.nosp@m.esta.nosp@m.@gmai.nosp@m.l.co.nosp@m.m
Driver for the PX4FLOW module connected via I2C.
Definition in file px4flow.cpp.
Macro Definition Documentation
#define I2C_FLOW_ADDRESS_DEFAULT 0x42
7-bit address. 8-bit address is 0x84, range 0x42 - 0x49
Definition at line 83 of file px4flow.cpp.
Referenced by px4flow::start().
#define I2C_FLOW_ADDRESS_MAX 0x49
7-bit address.
Definition at line 85 of file px4flow.cpp.
Referenced by px4flow::start().
#define I2C_FLOW_ADDRESS_MIN 0x42
7-bit address.
Definition at line 84 of file px4flow.cpp.
#define PX4FLOW_CONVERSION_INTERVAL_DEFAULT 100000
in microseconds! = 10Hz
Definition at line 90 of file px4flow.cpp.
Referenced by px4flow::start().
#define PX4FLOW_CONVERSION_INTERVAL_MAX 1000000
in microseconds! = 1 Hz
Definition at line 92 of file px4flow.cpp.
Referenced by px4flow::start().
#define PX4FLOW_CONVERSION_INTERVAL_MIN 10000
in microseconds! = 100 Hz
Definition at line 91 of file px4flow.cpp.
#define PX4FLOW_I2C_MAX_BUS_SPEED 400000
400 KHz maximum speed
Definition at line 94 of file px4flow.cpp.
#define PX4FLOW_MAX_DISTANCE 5.0f
Definition at line 96 of file px4flow.cpp.
Referenced by PX4FLOW::collect().
#define PX4FLOW_MIN_DISTANCE 0.3f
Definition at line 97 of file px4flow.cpp.
Referenced by PX4FLOW::collect().
#define PX4FLOW_REG 0x16
Measure Register 22.
Definition at line 88 of file px4flow.cpp.
Referenced by PX4FLOW::collect(), and PX4FLOW::measure().
Function Documentation
int px4flow_main (int argc, char * argv[])
Definition at line 985 of file px4flow.cpp.
References px4flow::info(), px4flow::reset(), px4flow::start(), px4flow::stop(), px4flow::test(), and px4flow::usage().