PX4 Firmware: src/systemcmds/tests/tests_main.h File Reference
tests_main.h File Reference
Tests declaration file.
#include <px4_platform_common/px4_config.h>
Functions
__BEGIN_DECLS int test_adc (int argc, char *argv[])
int test_autodeclination (int argc, char *argv[])
int test_bezierQuad (int argc, char *argv[])
int test_bson (int argc, char *argv[])
int test_conv (int argc, char *argv[])
int test_dataman (int argc, char *argv[])
int test_file (int argc, char *argv[])
int test_file2 (int argc, char *argv[])
int test_float (int argc, char *argv[])
int test_hott_telemetry (int argc, char *argv[])
int test_hrt (int argc, char *argv[])
int test_int (int argc, char *argv[])
int test_IntrusiveQueue (int argc, char *argv[])
int test_jig_voltages (int argc, char *argv[])
int test_led (int argc, char *argv[])
int test_List (int argc, char *argv[])
int test_mathlib (int argc, char *argv[])
int test_matrix (int argc, char *argv[])
int test_microbench_hrt (int argc, char *argv[])
int test_microbench_math (int argc, char *argv[])
int test_microbench_matrix (int argc, char *argv[])
int test_microbench_uorb (int argc, char *argv[])
int test_mixer (int argc, char *argv[])
int test_mount (int argc, char *argv[])
int test_param (int argc, char *argv[])
int test_parameters (int argc, char *argv[])
int test_perf (int argc, char *argv[])
int test_ppm (int argc, char *argv[])
int test_ppm_loopback (int argc, char *argv[])
int test_rc (int argc, char *argv[])
int test_search_min (int argc, char *argv[])
int test_servo (int argc, char *argv[])
int test_sleep (int argc, char *argv[])
int test_smooth_z (int argc, char *argv[])
int test_time (int argc, char *argv[])
int test_tone (int argc, char *argv[])
int test_uart_baudchange (int argc, char *argv[])
int test_uart_break (int argc, char *argv[])
int test_uart_console (int argc, char *argv[])
int test_uart_loopback (int argc, char *argv[])
int test_uart_send (int argc, char *argv[])
int test_versioning (int argc, char *argv[])
int commander_tests_main (int argc, char *argv[])
int mavlink_tests_main (int argc, char *argv[])
int controllib_test_main (int argc, char *argv[])
int uorb_tests_main (int argc, char *argv[])
int rc_tests_main (int argc, char *argv[])
int sf0x_tests_main (int argc, char *argv[])
Detailed Description
Tests declaration file.
Definition in file tests_main.h.
Function Documentation
commander_tests_main()
int commander_tests_main (int argc, char * argv[])
Definition at line 49 of file commander_tests.cpp.
References stateMachineHelperTest().
controllib_test_main()
int controllib_test_main (int argc, char * argv[])
Definition at line 532 of file controllib_test_main.cpp.
References control::basicBlocksTest().
Referenced by blockDelayTest().
mavlink_tests_main()
int mavlink_tests_main (int argc, char * argv[])
Definition at line 44 of file mavlink_tests.cpp.
References mavlink_ftp_test().
rc_tests_main()
int rc_tests_main (int argc, char * argv[])
sf0x_tests_main()
int sf0x_tests_main (int argc, char * argv[])
test_adc()
__BEGIN_DECLS int test_adc (int argc, char * argv[])
Definition at line 56 of file test_adc.c.
References ADC0_DEVICE_PATH, data, fd, OK, px4_adc_msg_t, px4_close(), PX4_MAX_ADC_CHANNELS, px4_open(), and px4_read().
test_autodeclination()
int test_autodeclination (int argc, char * argv[])
Referenced by AutoDeclinationTest::run_tests().
test_bezierQuad()
int test_bezierQuad (int argc, char * argv[])
Referenced by BezierQuadTest::random().
test_bson()
int test_bson (int argc, char * argv[])
Definition at line 262 of file test_bson.cpp.
References bson_decoder_init_buf(), bson_encoder_buf_data(), bson_encoder_buf_size(), bson_encoder_init_buf(), bson_decoder_s::buf, decode(), decode_callback(), and encode().
test_conv()
int test_conv (int argc, char * argv[])
Definition at line 56 of file test_conv.cpp.
References f(), FLOAT_TO_REG, REG_TO_FLOAT, and REG_TO_SIGNED.
test_dataman()
int test_dataman (int argc, char * argv[])
Definition at line 159 of file test_dataman.c.
References DM_INIT_REASON_IN_FLIGHT, DM_INIT_REASON_POWER_ON, DM_KEY_WAYPOINTS_OFFBOARD_1, DM_MAX_DATA_SIZE, dm_read(), dm_restart(), NUM_MISSIONS_TEST, sems, task_main(), and task_returned_error.
test_file()
int test_file (int argc, char * argv[])
Definition at line 91 of file test_file.c.
References __attribute__(), check_user_abort(), fd, hrt_absolute_time(), hrt_abstime, OK, px4_close(), px4_open(), read(), start(), warn, warnx, and write().
test_file2()
int test_file2 (int argc, char * argv[])
Definition at line 173 of file test_file2.c.
References FLAG_FSYNC, FLAG_LSEEK, LOG_PATH, test_corruption(), and usage().
test_float()
int test_float (int argc, char * argv[])
Referenced by FloatTest::run_tests().
test_hott_telemetry()
int test_hott_telemetry (int argc, char * argv[])
Definition at line 94 of file test_hott_telemetry.c.
References fd, open_uart(), read(), send(), and write().
test_hrt()
int test_hrt (int argc, char * argv[])
Definition at line 45 of file test_hrt.cpp.
References hrt_absolute_time(), hrt_abstime, hrt_call_after(), and hrt_called().
test_int()
int test_int (int argc, char * argv[])
Referenced by IntTest::run_tests().
test_IntrusiveQueue()
int test_IntrusiveQueue (int argc, char * argv[])
Referenced by IntrusiveQueueTest::test_remove().
test_jig_voltages()
int test_jig_voltages (int argc, char * argv[])
Definition at line 55 of file test_jig_voltages.c.
References ADC0_DEVICE_PATH, data, fd, OK, px4_adc_msg_t, PX4_MAX_ADC_CHANNELS, and read().
test_led()
int test_led (int argc, char * argv[])
Definition at line 58 of file test_led.c.
References fd, LED0_DEVICE_PATH, LED_AMBER, LED_BLUE, LED_OFF, LED_ON, px4_ioctl(), and px4_open().
test_List()
int test_List (int argc, char * argv[])
Referenced by ListTest::test_range_based_for().
test_mathlib()
int test_mathlib (int argc, char * argv[])
Referenced by MathlibTest::run_tests().
test_matrix()
int test_matrix (int argc, char * argv[])
Referenced by MatrixTest::run_tests().
test_microbench_hrt()
int test_microbench_hrt (int argc, char * argv[])
test_microbench_math()
int test_microbench_math (int argc, char * argv[])
test_microbench_matrix()
int test_microbench_matrix (int argc, char * argv[])
test_microbench_uorb()
int test_microbench_uorb (int argc, char * argv[])
test_mixer()
int test_mixer (int argc, char * argv[])
test_mount()
int test_mount (int argc, char * argv[])
Definition at line 60 of file test_mount.c.
References __attribute__(), abort_tries, fd, fsync_tries, OK, px4_close(), px4_open(), read(), and write().
test_param()
int test_param (int argc, char * argv[])
Definition at line 49 of file test_param.c.
References OK, param_find(), param_get(), PARAM_INVALID, PARAM_MAGIC1, PARAM_MAGIC2, param_reset(), param_set(), param_type(), PARAM_TYPE_INT32, and warnx.
test_parameters()
int test_parameters (int argc, char * argv[])
Referenced by ParameterTest::run_tests().
test_perf()
int test_perf (int argc, char * argv[])
Definition at line 47 of file test_perf.c.
References OK, PC_COUNT, PC_ELAPSED, perf_alloc, perf_begin(), perf_count(), perf_end(), perf_free(), perf_print_all(), and perf_print_counter().
test_ppm()
int test_ppm (int argc, char * argv[])
Definition at line 50 of file test_ppm.cpp.
References ppm_buffer, and ppm_decoded_channels.
test_ppm_loopback()
int test_ppm_loopback (int argc, char * argv[])
Definition at line 61 of file test_ppm_loopback.c.
References matrix::abs(), pwm_output_values::channel_count, OK, orb_check(), orb_copy(), ORB_ID, orb_subscribe(), PWM_OUTPUT0_DEVICE_PATH, PWM_SERVO_GET, PWM_SERVO_GET_COUNT, PWM_SERVO_SET, PWM_SERVO_SET_DISARMED_PWM, pwm_output_values::values, input_rc_s::values, and warnx.
test_rc()
int test_rc (int argc, char * argv[])
Definition at line 61 of file test_rc.c.
References matrix::abs(), input_rc_s::channel_count, hrt_absolute_time(), orb_check(), orb_copy(), ORB_ID, orb_subscribe(), orb_unsubscribe(), input_rc_s::timestamp_last_signal, and input_rc_s::values.
test_search_min()
int test_search_min (int argc, char * argv[])
Referenced by SearchMinTest::_no_extremum().
test_servo()
int test_servo (int argc, char * argv[])
Definition at line 57 of file test_servo.c.
References data, fd, OK, PWM_OUTPUT0_DEVICE_PATH, PWM_OUTPUT_MAX_CHANNELS, PWM_SERVO_ARM, PWM_SERVO_GET, PWM_SERVO_GET_COUNT, PWM_SERVO_SET, PWM_SERVO_SET_ARM_OK, read(), and warnx.
test_sleep()
int test_sleep (int argc, char * argv[])
Definition at line 55 of file test_sleep.c.
References OK.
test_smooth_z()
int test_smooth_z (int argc, char * argv[])
Referenced by SmoothZTest::accelerateDownwardFromBrake().
test_time()
int test_time (int argc, char * argv[])
Definition at line 78 of file test_time.c.
References matrix::abs(), cycletime(), hrt_absolute_time(), and hrt_abstime.
test_tone()
int test_tone (int argc, char * argv[])
Definition at line 49 of file test_tone.cpp.
References orb_advert_t, orb_advertise_queue(), ORB_ID, orb_publish(), orb_unadvertise(), Tunes::set_string(), tune_control, tune_control_pub, tune_control_s::tune_id, and tune_control_s::volume.
test_uart_baudchange()
int test_uart_baudchange (int argc, char * argv[])
Definition at line 59 of file test_uart_baudchange.c.
References OK, and write().
test_uart_break()
int test_uart_break (int argc, char * argv[])
Definition at line 61 of file test_uart_break.c.
References OK, and write().
test_uart_console()
int test_uart_console (int argc, char * argv[])
Definition at line 75 of file test_uart_console.c.
References receive_loop(), and write().
test_uart_loopback()
int test_uart_loopback (int argc, char * argv[])
Definition at line 59 of file test_uart_loopback.c.
References read(), and write().
test_uart_send()
int test_uart_send (int argc, char * argv[])
Definition at line 60 of file test_uart_send.c.
References hrt_absolute_time(), and write().
test_versioning()
int test_versioning (int argc, char * argv[])
Referenced by VersioningTest::run_tests().
uorb_tests_main()
int uorb_tests_main (int argc, char * argv[])
Definition at line 51 of file uORB_tests_main.cpp.
References uORBTest::UnitTest::instance(), uORBTest::UnitTest::latency_test(), OK, uORBTest::UnitTest::test(), and usage().