PX4 Firmware: LidarLitePWM Class Reference
LidarLitePWM Class Reference
#include <LidarLitePWM.h>
Public Member Functions
LidarLitePWM (const char *path, uint8_t rotation=distance_sensor_s::ROTATION_DOWNWARD_FACING)
virtual ~LidarLitePWM ()
int init () override
ssize_t read (device::file_t *filp, char *buffer, size_t buflen) override
Perform a read from the device.
int ioctl (device::file_t *filp, int cmd, unsigned long arg) override
void start () override
void stop () override
void cycle ()
void print_info () override
Diagnostics - print some basic information about the driver.
void print_registers () override
print registers to console
const char * get_dev_name () override
Public Member Functions inherited from LidarLite
LidarLite ()
virtual ~LidarLite ()=default
Public Member Functions inherited from device::CDev
CDev (const char *name, const char *devname)
Constructor.
virtual ~CDev ()
virtual int open (file_t *filep)
Handle an open of the device.
virtual int close (file_t *filep)
Handle a close of the device.
virtual ssize_t write (file_t *filep, const char *buffer, size_t buflen)
Perform a write to the device.
virtual off_t seek (file_t *filep, off_t offset, int whence)
Perform a logical seek operation on the device.
virtual int poll (file_t *filep, px4_pollfd_struct_t *fds, bool setup)
Perform a poll setup/teardown operation.
Public Member Functions inherited from device::Device
virtual ~Device ()=default
Destructor.
virtual int read (unsigned address, void *data, unsigned count)
Read directly from the device.
virtual int write (unsigned address, void *data, unsigned count)
Write directly to the device.
virtual int ioctl (unsigned operation, unsigned &arg)
Perform a device-specific operation.
uint8_t get_device_bus ()
Return the bus ID the device is connected to.
DeviceBusType get_device_bus_type ()
Return the bus type the device is connected to.
uint8_t get_device_address ()
Return the bus address of the device.
void set_device_address (int address)
void set_device_type (uint8_t devtype)
Set the device type.
virtual bool external ()
Static Public Member Functions
static void cycle_trampoline (void *arg)
Static trampoline from the workq context; because we don't have a generic workq wrapper yet.
Protected Member Functions
int measure () override
int collect () override
int reset_sensor () override
void task_main_trampoline (int argc, char *argv[])
Protected Member Functions inherited from LidarLite
void set_minimum_distance (const float min)
Set the min and max distance thresholds if you want the end points of the sensors range to be brought in at all, otherwise it will use the defaults LL40LS_MIN_DISTANCE and LL40LS_MAX_DISTANCE.
void set_maximum_distance (const float max)
float get_minimum_distance () const
float get_maximum_distance () const
uint32_t getMeasureTicks () const
Protected Member Functions inherited from device::CDev
virtual pollevent_t poll_state (file_t *filep)
Check the current state of the device for poll events from the perspective of the file.
virtual void poll_notify (pollevent_t events)
Report new poll events.
virtual void poll_notify_one (px4_pollfd_struct_t *fds, pollevent_t events)
Internal implementation of poll_notify.
virtual int open_first (file_t *filep)
Notification of the first open.
virtual int close_last (file_t *filep)
Notification of the last close.
virtual int register_class_devname (const char *class_devname)
Register a class device name, automatically adding device class instance suffix if need be.
virtual int unregister_class_devname (const char *class_devname, unsigned class_instance)
Register a class device name, automatically adding device class instance suffix if need be.
const char * get_devname ()
Get the device name.
void lock ()
Take the driver lock.
void unlock ()
Release the driver lock.
Protected Member Functions inherited from device::Device
Device (const char *name)
Device (DeviceBusType bus_type, uint8_t bus, uint8_t address, uint8_t devtype=0)
Device (const Device &)=delete
Device & operator= (const Device &)=delete
Device (Device &&)=delete
Device & operator= (Device &&)=delete
Private Attributes
uint8_t _rotation
work_s _work
ringbuffer::RingBuffer * _reports
int _class_instance
int _orb_class_instance
int _pwmSub
struct pwm_input_s _pwm
orb_advert_t _distance_sensor_topic
struct distance_sensor_s _range
perf_counter_t _sample_perf
perf_counter_t _read_errors
perf_counter_t _sensor_zero_resets
Additional Inherited Members
Public Types inherited from device::Device
enum DeviceBusType { DeviceBusType_UNKNOWN = 0, DeviceBusType_I2C = 1, DeviceBusType_SPI = 2, DeviceBusType_UAVCAN = 3 }
Device bus types for DEVID.
Protected Attributes inherited from device::CDev
px4_sem_t _lock
lock to protect access to all class members (also for derived classes)
bool _pub_blocked {false}
true if publishing should be blocked
Protected Attributes inherited from device::Device
union DeviceId _device_id
device identifier information
const char * _name
driver name
bool _debug_enabled {false}
if true, debug messages are printed
Static Protected Attributes inherited from device::CDev
static const px4_file_operations_t fops = {}
Pointer to the default cdev file operations table; useful for registering clone devices etc.
Detailed Description
Definition at line 60 of file LidarLitePWM.h.
Constructor & Destructor Documentation
LidarLitePWM::LidarLitePWM (const char * path, uint8_t rotation = distance_sensor_s::ROTATION_DOWNWARD_FACING)
Definition at line 52 of file LidarLitePWM.cpp.
References _class_instance, _distance_sensor_topic, _orb_class_instance, _pwm, _pwmSub, _range, _read_errors, _reports, _sample_perf, _sensor_zero_resets, PC_COUNT, PC_ELAPSED, and perf_alloc.
LidarLitePWM::~LidarLitePWM () virtual
Definition at line 69 of file LidarLitePWM.cpp.
References _class_instance, _reports, _sample_perf, _sensor_zero_resets, perf_free(), RANGE_FINDER_BASE_DEVICE_PATH, stop(), and device::CDev::unregister_class_devname().
Member Function Documentation
int LidarLitePWM::collect () override protected virtual
Implements LidarLite.
Definition at line 256 of file LidarLitePWM.cpp.
References _pwm, device::CDev::close(), fd, device::CDev::open(), PWMIN0_DEVICE_PATH, PX4_ERROR, PX4_OK, and read().
Referenced by measure().
void LidarLitePWM::cycle ()
Definition at line 153 of file LidarLitePWM.cpp.
References cycle_trampoline(), LidarLite::getMeasureTicks(), and measure().
Referenced by cycle_trampoline().
void LidarLitePWM::cycle_trampoline (void * arg) static
Static trampoline from the workq context; because we don't have a generic workq wrapper yet.
Parameters
arg Instance pointer for the driver that is polling.
Definition at line 146 of file LidarLitePWM.cpp.
References cycle().
Referenced by cycle(), and start().
const char * LidarLitePWM::get_dev_name () override virtual
Implements LidarLite.
Definition at line 287 of file LidarLitePWM.cpp.
References device::CDev::get_devname().
int LidarLitePWM::init () override virtual
Implements LidarLite.
Definition at line 88 of file LidarLitePWM.cpp.
References _class_instance, _distance_sensor_topic, _orb_class_instance, _reports, DEVICE_DEBUG, lis3mdl::init(), measure(), orb_advertise_multi(), ORB_ID, ORB_PRIO_LOW, PX4_ERROR, PX4_OK, RANGE_FINDER_BASE_DEVICE_PATH, and device::CDev::register_class_devname().
int LidarLitePWM::ioctl (device::file_t * filp, int cmd, unsigned long arg) override virtual
Reimplemented from LidarLite.
Definition at line 246 of file LidarLitePWM.cpp.
References LidarLite::ioctl().
Referenced by reset_sensor().
int LidarLitePWM::measure () override protected virtual
Implements LidarLite.
Definition at line 165 of file LidarLitePWM.cpp.
References _distance_sensor_topic, _pwm, _range, _read_errors, _reports, _rotation, _sample_perf, _sensor_zero_resets, collect(), distance_sensor_s::covariance, distance_sensor_s::current_distance, DEVICE_DEBUG, f(), LidarLite::get_maximum_distance(), LidarLite::get_minimum_distance(), hrt_absolute_time(), distance_sensor_s::id, distance_sensor_s::max_distance, distance_sensor_s::min_distance, ORB_ID, orb_publish(), distance_sensor_s::orientation, perf_begin(), perf_count(), perf_end(), device::CDev::poll_notify(), pwm_input_s::pulse_width, PX4_ERROR, PX4_OK, reset_sensor(), distance_sensor_s::timestamp, and distance_sensor_s::type.
Referenced by cycle(), init(), and read().
void LidarLitePWM::print_info () override virtual
Diagnostics - print some basic information about the driver.
Implements LidarLite.
Definition at line 120 of file LidarLitePWM.cpp.
References _range, _read_errors, _sample_perf, _sensor_zero_resets, LidarLite::getMeasureTicks(), perf_print_counter(), and warnx.
void LidarLitePWM::print_registers () override virtual
print registers to console
Implements LidarLite.
Definition at line 130 of file LidarLitePWM.cpp.
ssize_t LidarLitePWM::read (device::file_t * filep, char * buffer, size_t buflen) override virtual
Perform a read from the device.
The default implementation returns -ENOSYS.
Parameters
filep Pointer to the NuttX file structure.
buffer Pointer to the buffer into which data should be placed.
buflen The number of bytes to be read.
Returns
The number of bytes read or -errno otherwise.
Reimplemented from device::CDev.
Definition at line 204 of file LidarLitePWM.cpp.
References _reports, LidarLite::getMeasureTicks(), and measure().
Referenced by collect().
int LidarLitePWM::reset_sensor () override protected virtual
Implements LidarLite.
Definition at line 273 of file LidarLitePWM.cpp.
References device::CDev::close(), fd, ioctl(), device::CDev::open(), PWMIN0_DEVICE_PATH, PX4_ERROR, and SENSORIOCRESET.
Referenced by measure().
void LidarLitePWM::start () override virtual
Implements LidarLite.
Definition at line 135 of file LidarLitePWM.cpp.
References cycle_trampoline().
void LidarLitePWM::stop () override virtual
Implements LidarLite.
Definition at line 141 of file LidarLitePWM.cpp.
Referenced by ~LidarLitePWM().
void LidarLitePWM::task_main_trampoline (int argc, char * argv[]) protected
Member Data Documentation
int LidarLitePWM::_class_instance private
Definition at line 113 of file LidarLitePWM.h.
Referenced by init(), LidarLitePWM(), and ~LidarLitePWM().
orb_advert_t LidarLitePWM::_distance_sensor_topic private
Definition at line 117 of file LidarLitePWM.h.
Referenced by init(), LidarLitePWM(), and measure().
int LidarLitePWM::_orb_class_instance private
Definition at line 114 of file LidarLitePWM.h.
Referenced by init(), and LidarLitePWM().
struct pwm_input_s LidarLitePWM::_pwm private
Definition at line 116 of file LidarLitePWM.h.
Referenced by collect(), LidarLitePWM(), and measure().
int LidarLitePWM::_pwmSub private
Definition at line 115 of file LidarLitePWM.h.
Referenced by LidarLitePWM().
struct distance_sensor_s LidarLitePWM::_range private
Definition at line 118 of file LidarLitePWM.h.
Referenced by LidarLitePWM(), measure(), and print_info().
perf_counter_t LidarLitePWM::_read_errors private
Definition at line 121 of file LidarLitePWM.h.
Referenced by LidarLitePWM(), measure(), and print_info().
ringbuffer::RingBuffer* LidarLitePWM::_reports private
Definition at line 112 of file LidarLitePWM.h.
Referenced by init(), LidarLitePWM(), measure(), read(), and ~LidarLitePWM().
uint8_t LidarLitePWM::_rotation private
Definition at line 110 of file LidarLitePWM.h.
Referenced by measure().
perf_counter_t LidarLitePWM::_sample_perf private
Definition at line 120 of file LidarLitePWM.h.
Referenced by LidarLitePWM(), measure(), print_info(), and ~LidarLitePWM().
perf_counter_t LidarLitePWM::_sensor_zero_resets private
Definition at line 122 of file LidarLitePWM.h.
Referenced by LidarLitePWM(), measure(), print_info(), and ~LidarLitePWM().
work_s LidarLitePWM::_work private
Definition at line 111 of file LidarLitePWM.h.
The documentation for this class was generated from the following files:
src/drivers/distance_sensor/ll40ls/LidarLitePWM.h
src/drivers/distance_sensor/ll40ls/LidarLitePWM.cpp