PX4 Firmware: mpu6000 Namespace Reference
mpu6000 Namespace Reference
Local functions in support of the shell command.
Classes
struct mpu6000_bus_option
Functions
void start (enum MPU6000_BUS busid, enum Rotation rotation, int range, int device_type)
Start the driver.
bool start_bus (struct mpu6000_bus_option &bus, enum Rotation rotation, int range, int device_type)
start driver for a specific bus option
void stop (enum MPU6000_BUS busid)
void test (enum MPU6000_BUS busid)
Perform some basic functional tests on the driver; make sure we can collect data from the sensor in polled and automatic modes.
static struct mpu6000_bus_option & find_bus (enum MPU6000_BUS busid)
find a bus structure for a busid
void reset (enum MPU6000_BUS busid)
Reset the driver.
void info (enum MPU6000_BUS busid)
Print a little info about the driver.
void regdump (enum MPU6000_BUS busid)
Dump the register information.
void testerror (enum MPU6000_BUS busid)
deliberately produce an error to test recovery
void factorytest (enum MPU6000_BUS busid)
Dump the register information.
void usage ()
Prints info about the driver argument usage.
Variables
struct mpu6000::mpu6000_bus_option bus_options []
Detailed Description
Local functions in support of the shell command.
Function Documentation
void mpu6000::factorytest (enum MPU6000_BUS busid)
Dump the register information.
Definition at line 2459 of file mpu6000.cpp.
References mpu6000::mpu6000_bus_option::dev, errx, MPU6000::factory_self_test(), and find_bus().
Referenced by mpu6000_main().
struct mpu6000_bus_option & mpu6000::find_bus (enum MPU6000_BUS busid) static
find a bus structure for a busid
Definition at line 2171 of file mpu6000.cpp.
References bus_options, errx, MPU6000_BUS_ALL, and NUM_BUS_OPTIONS.
Referenced by factorytest(), info(), regdump(), reset(), stop(), test(), and testerror().
void mpu6000::info (enum MPU6000_BUS busid)
Print a little info about the driver.
Definition at line 2403 of file mpu6000.cpp.
References mpu6000::mpu6000_bus_option::dev, errx, find_bus(), and MPU6000::print_info().
Referenced by mpu6000_main().
void mpu6000::regdump (enum MPU6000_BUS busid)
Dump the register information.
Definition at line 2422 of file mpu6000.cpp.
References mpu6000::mpu6000_bus_option::dev, errx, find_bus(), and MPU6000::print_registers().
Referenced by mpu6000_main().
void mpu6000::reset (enum MPU6000_BUS busid)
Reset the driver.
Definition at line 2377 of file mpu6000.cpp.
References mpu6000::mpu6000_bus_option::accelpath, device::CDev::close(), err, fd, find_bus(), MPU6000_gyro::ioctl(), device::CDev::open(), SENSOR_POLLRATE_DEFAULT, SENSORIOCRESET, and SENSORIOCSPOLLRATE.
Referenced by mpu6000_main(), and test().
void mpu6000::start (enum MPU6000_BUS busid, enum Rotation rotation, int range, int device_type)
Start the driver.
This function only returns if the driver is up and running or failed to detect the sensor.
Definition at line 2261 of file mpu6000.cpp.
References bus_options, MPU6000_BUS_ALL, NUM_BUS_OPTIONS, and start_bus().
Referenced by mpu6000_main().
bool mpu6000::start_bus (struct mpu6000_bus_option & bus, enum Rotation rotation, int range, int device_type)
start driver for a specific bus option
Definition at line 2187 of file mpu6000.cpp.
References ACCELIOCSRANGE, device::CDev::close(), mpu6000::mpu6000_bus_option::dev, mpu6000::mpu6000_bus_option::external, fd, MPU6000_gyro::ioctl(), MPU6000_gyro::MPU6000, OK, device::CDev::open(), SENSOR_POLLRATE_DEFAULT, SENSORIOCSPOLLRATE, and warnx.
Referenced by start().
void mpu6000::stop (enum MPU6000_BUS busid)
Definition at line 2290 of file mpu6000.cpp.
References mpu6000::mpu6000_bus_option::dev, find_bus(), and warnx.
Referenced by mpu6000_main().
void mpu6000::test (enum MPU6000_BUS busid)
Perform some basic functional tests on the driver; make sure we can collect data from the sensor in polled and automatic modes.
Definition at line 2313 of file mpu6000.cpp.
References accel_report, mpu6000::mpu6000_bus_option::accelpath, device::CDev::close(), err, errx, fd, find_bus(), gyro_report, mpu6000::mpu6000_bus_option::gyropath, MPU6000_gyro::ioctl(), device::CDev::open(), MPU6000_gyro::read(), reset(), SENSOR_POLLRATE_DEFAULT, SENSOR_POLLRATE_MANUAL, SENSORIOCSPOLLRATE, and warnx.
Referenced by mpu6000_main().
void mpu6000::testerror (enum MPU6000_BUS busid)
deliberately produce an error to test recovery
Definition at line 2441 of file mpu6000.cpp.
References mpu6000::mpu6000_bus_option::dev, errx, find_bus(), and MPU6000::test_error().
Referenced by mpu6000_main().
void mpu6000::usage (void)
Prints info about the driver argument usage.
Prints info about the driver argument usage.
Definition at line 2474 of file mpu6000.cpp.
References warnx.
Referenced by mpu6000_main().
Variable Documentation
struct mpu6000::mpu6000_bus_option mpu6000::bus_options[]
Referenced by find_bus(), and start().