PX4 Firmware: MulticopterAttitudeControl Class Reference
MulticopterAttitudeControl Class Reference
#include <mc_att_control.hpp>
Classes
struct _actuators
actuator controls
struct _battery_status
battery status
struct _manual_control_sp
manual control setpoint
struct _sensor_bias
sensor in-run bias corrections
struct _sensor_correction
sensor thermal corrections
struct _sensor_gyro
gyro data before thermal correctons and ekf bias estimates are applied
struct _v_att
vehicle attitude
struct _v_att_sp
vehicle attitude setpoint
struct _v_control_mode
vehicle control mode
struct _v_rates_sp
vehicle rates setpoint
struct _vehicle_land_detected
struct _vehicle_status
vehicle status
Public Member Functions
MulticopterAttitudeControl ()
virtual ~MulticopterAttitudeControl ()=default
void run () override
Public Member Functions inherited from ModuleParams
ModuleParams (ModuleParams *parent)
void setParent (ModuleParams *parent)
Set the parent module.
virtual ~ModuleParams ()=default
ModuleParams (const ModuleParams &)=delete
ModuleParams & operator= (const ModuleParams &)=delete
ModuleParams (ModuleParams &&)=delete
ModuleParams & operator= (ModuleParams &&)=delete
Public Member Functions inherited from ListNode< ModuleParams * >
ListNode ()
ListNode (const ListNode &)=delete
ListNode (ListNode &&)=delete
virtual ~ListNode ()=default
ListNode & operator= (const ListNode &)=delete
ListNode & operator= (ListNode &&)=delete
void setSibling (ModuleParams *sibling)
const ModuleParams * getSibling ()
Static Public Member Functions
static int task_spawn (int argc, char *argv[])
static MulticopterAttitudeControl * instantiate (int argc, char *argv[])
static int custom_command (int argc, char *argv[])
static int print_usage (const char *reason=nullptr)
Private Member Functions
void parameters_updated ()
initialize some vectors/matrices from parameters
void battery_status_poll ()
Check for parameter update and handle it.
void parameter_update_poll ()
void sensor_bias_poll ()
void vehicle_land_detected_poll ()
void sensor_correction_poll ()
void vehicle_attitude_poll ()
void vehicle_attitude_setpoint_poll ()
void vehicle_control_mode_poll ()
void vehicle_manual_poll ()
void vehicle_motor_limits_poll ()
void vehicle_rates_setpoint_poll ()
void vehicle_status_poll ()
void control_attitude (float dt)
Attitude controller.
void control_attitude_rates (float dt)
Attitude rates controller.
matrix::Vector3f pid_attenuations (float tpa_breakpoint, float tpa_rate)
Throttle PID attenuation.
Private Attributes
int _v_att_sub {-1}
vehicle attitude subscription
int _v_att_sp_sub {-1}
vehicle attitude setpoint subscription
int _v_rates_sp_sub {-1}
vehicle rates setpoint subscription
int _v_control_mode_sub {-1}
vehicle control mode subscription
int _params_sub {-1}
parameter updates subscription
int _manual_control_sp_sub {-1}
manual control setpoint subscription
int _vehicle_status_sub {-1}
vehicle status subscription
int _motor_limits_sub {-1}
motor limits subscription
int _battery_status_sub {-1}
battery status subscription
int _sensor_gyro_sub [MAX_GYRO_COUNT]
gyro data subscription
int _sensor_correction_sub {-1}
sensor thermal correction subscription
int _sensor_bias_sub {-1}
sensor in-run bias correction subscription
int _vehicle_land_detected_sub {-1}
vehicle land detected subscription
unsigned _gyro_count {1}
int _selected_gyro {0}
orb_advert_t _v_rates_sp_pub {nullptr}
rate setpoint publication
orb_advert_t _actuators_0_pub {nullptr}
attitude actuator controls publication
orb_advert_t _controller_status_pub {nullptr}
controller status publication
orb_id_t _rates_sp_id {nullptr}
pointer to correct rates setpoint uORB metadata structure
orb_id_t _actuators_id {nullptr}
pointer to correct actuator controls0 uORB metadata structure
bool _actuators_0_circuit_breaker_enabled {false}
circuit breaker to suppress output
MultirotorMixer::saturation_status _saturation_status {}
perf_counter_t _loop_perf
loop performance counter
math::LowPassFilter2p _lp_filters_d [3]
low-pass filters for D-term (roll, pitch & yaw)
float _loop_update_rate_hz {initial_update_rate_hz}
current rate-controller loop update rate in [Hz]
matrix::Vector3f _rates_prev
angular rates on previous step
matrix::Vector3f _rates_prev_filtered
angular rates on previous step (low-pass filtered)
matrix::Vector3f _rates_sp
angular rates setpoint
matrix::Vector3f _rates_int
angular rates integral error
float _thrust_sp
thrust setpoint
matrix::Vector3f _att_control
attitude control vector
matrix::Dcmf _board_rotation
rotation matrix for the orientation that the board is mounted
DEFINE_PARAMETERS((ParamFloat< px4::params::MC_ROLL_P >) _roll_p,(ParamFloat< px4::params::MC_ROLLRATE_P >) _roll_rate_p,(ParamFloat< px4::params::MC_ROLLRATE_I >) _roll_rate_i,(ParamFloat< px4::params::MC_RR_INT_LIM >) _roll_rate_integ_lim,(ParamFloat< px4::params::MC_ROLLRATE_D >) _roll_rate_d,(ParamFloat< px4::params::MC_ROLLRATE_FF >) _roll_rate_ff,(ParamFloat< px4::params::MC_PITCH_P >) _pitch_p,(ParamFloat< px4::params::MC_PITCHRATE_P >) _pitch_rate_p,(ParamFloat< px4::params::MC_PITCHRATE_I >) _pitch_rate_i,(ParamFloat< px4::params::MC_PR_INT_LIM >) _pitch_rate_integ_lim,(ParamFloat< px4::params::MC_PITCHRATE_D >) _pitch_rate_d,(ParamFloat< px4::params::MC_PITCHRATE_FF >) _pitch_rate_ff,(ParamFloat< px4::params::MC_YAW_P >) _yaw_p,(ParamFloat< px4::params::MC_YAWRATE_P >) _yaw_rate_p,(ParamFloat< px4::params::MC_YAWRATE_I >) _yaw_rate_i,(ParamFloat< px4::params::MC_YR_INT_LIM >) _yaw_rate_integ_lim,(ParamFloat< px4::params::MC_YAWRATE_D >) _yaw_rate_d,(ParamFloat< px4::params::MC_YAWRATE_FF >) _yaw_rate_ff,(ParamFloat< px4::params::MC_DTERM_CUTOFF >) _d_term_cutoff_freq,(ParamFloat< px4::params::MC_TPA_BREAK_P >) _tpa_breakpoint_p,(ParamFloat< px4::params::MC_TPA_BREAK_I >) _tpa_breakpoint_i,(ParamFloat< px4::params::MC_TPA_BREAK_D >) _tpa_breakpoint_d,(ParamFloat< px4::params::MC_TPA_RATE_P >) _tpa_rate_p,(ParamFloat< px4::params::MC_TPA_RATE_I >) _tpa_rate_i,(ParamFloat< px4::params::MC_TPA_RATE_D >) _tpa_rate_d,(ParamFloat< px4::params::MC_ROLLRATE_MAX >) _roll_rate_max,(ParamFloat< px4::params::MC_PITCHRATE_MAX >) _pitch_rate_max,(ParamFloat< px4::params::MC_YAWRATE_MAX >) _yaw_rate_max,(ParamFloat< px4::params::MC_YAWRAUTO_MAX >) _yaw_auto_max,(ParamFloat< px4::params::MC_ACRO_R_MAX >) _acro_roll_max,(ParamFloat< px4::params::MC_ACRO_P_MAX >) _acro_pitch_max,(ParamFloat< px4::params::MC_ACRO_Y_MAX >) _acro_yaw_max,(ParamFloat< px4::params::MC_ACRO_EXPO >) _acro_expo_rp,(ParamFloat< px4::params::MC_ACRO_EXPO_Y >) _acro_expo_y,(ParamFloat< px4::params::MC_ACRO_SUPEXPO >) _acro_superexpo_rp,(ParamFloat< px4::params::MC_ACRO_SUPEXPOY >) _acro_superexpo_y,(ParamFloat< px4::params::MC_RATT_TH >) _rattitude_thres,(ParamBool< px4::params::MC_BAT_SCALE_EN >) _bat_scale_en,(ParamInt< px4::params::SENS_BOARD_ROT >) _board_rotation_param,(ParamFloat< px4::params::SENS_BOARD_X_OFF >) _board_offset_x,(ParamFloat< px4::params::SENS_BOARD_Y_OFF >) _board_offset_y,(ParamFloat< px4::params::SENS_BOARD_Z_OFF >) _board_offset_z,(ParamFloat< px4::params::VT_WV_YAWR_SCL >) _vtol_wv_yaw_rate_scale) matrix matrix::Vector3f _rate_p
< P gain for attitude control
matrix::Vector3f _rate_i
I gain for angular rate error.
matrix::Vector3f _rate_int_lim
integrator state limit for rate loop
matrix::Vector3f _rate_d
D gain for angular rate error.
matrix::Vector3f _rate_ff
Feedforward gain for desired rates.
matrix::Vector3f _mc_rate_max
attitude rate limits in stabilized modes
matrix::Vector3f _auto_rate_max
attitude rate limits in auto modes
matrix::Vector3f _acro_rate_max
max attitude rates in acro mode
Static Private Attributes
static constexpr const float initial_update_rate_hz = 250.f
loop update rate used for initialization
Additional Inherited Members
Protected Member Functions inherited from ModuleParams
virtual void updateParams ()
Call this whenever the module gets a parameter change notification.
virtual void updateParamsImpl ()
The implementation for this is generated with the macro DEFINE_PARAMETERS()
Protected Attributes inherited from ListNode< ModuleParams * >
ModuleParams * _sibling
Detailed Description
Definition at line 68 of file mc_att_control.hpp.
Constructor & Destructor Documentation
MulticopterAttitudeControl::MulticopterAttitudeControl ()
Definition at line 99 of file mc_att_control_main.cpp.
References _att_control, _rates_int, _rates_prev, _rates_prev_filtered, _rates_sp, _sensor_gyro_sub, _thrust_sp, initial_update_rate_hz, MAX_GYRO_COUNT, parameters_updated(), and matrix::Matrix< Type, M, N >::zero().
Referenced by instantiate().
virtual MulticopterAttitudeControl::~MulticopterAttitudeControl () virtual default
Member Function Documentation
void MulticopterAttitudeControl::battery_status_poll () private
Check for parameter update and handle it.
Definition at line 307 of file mc_att_control_main.cpp.
References _battery_status_sub, orb_check(), orb_copy(), and ORB_ID.
Referenced by run().
void MulticopterAttitudeControl::control_attitude (float dt) private
Attitude controller.
Input: 'vehicle_attitude_setpoint' topics (depending on mode) Output: '_rates_sp' vector, '_thrust_sp'
Definition at line 379 of file mc_att_control_main.cpp.
References _auto_rate_max, _mc_rate_max, _rates_int, _rates_sp, _thrust_sp, math::constrain(), matrix::Quaternion< Type >::dcm_z(), matrix::Matrix< Type, M, N >::emult(), f(), matrix::Quaternion< Type >::imag(), matrix::Quaternion< Type >::inversed(), matrix::Vector< Type, M >::normalize(), math::signNoZero(), and vehicle_attitude_setpoint_poll().
Referenced by run().
void MulticopterAttitudeControl::control_attitude_rates (float dt) private
Attitude rates controller.
Definition at line 494 of file mc_att_control_main.cpp.
References _att_control, _board_rotation, _lp_filters_d, _rate_d, _rate_ff, _rate_i, _rate_int_lim, _rate_p, _rates_int, _rates_prev, _rates_prev_filtered, _rates_sp, _saturation_status, _selected_gyro, AXIS_COUNT, AXIS_INDEX_PITCH, AXIS_INDEX_ROLL, AXIS_INDEX_YAW, math::constrain(), dt, matrix::Matrix< Type, M, N >::emult(), f(), MultirotorMixer::saturation_status::flags, math::max(), math::min(), pid_attenuations(), MultirotorMixer::saturation_status::pitch_neg, MultirotorMixer::saturation_status::pitch_pos, MultirotorMixer::saturation_status::roll_neg, MultirotorMixer::saturation_status::roll_pos, MultirotorMixer::saturation_status::yaw_neg, MultirotorMixer::saturation_status::yaw_pos, and matrix::Matrix< Type, M, N >::zero().
Referenced by run().
int MulticopterAttitudeControl::custom_command (int argc, char * argv[]) static
See also
ModuleBase
Definition at line 886 of file mc_att_control_main.cpp.
References print_usage().
MulticopterAttitudeControl * MulticopterAttitudeControl::instantiate (int argc, char * argv[]) static
See also
ModuleBase
Definition at line 881 of file mc_att_control_main.cpp.
References MulticopterAttitudeControl().
void MulticopterAttitudeControl::parameter_update_poll () private
Definition at line 202 of file mc_att_control_main.cpp.
References _params_sub, orb_check(), orb_copy(), ORB_ID, parameters_updated(), and ModuleParams::updateParams().
Referenced by run().
void MulticopterAttitudeControl::parameters_updated () private
initialize some vectors/matrices from parameters
Definition at line 136 of file mc_att_control_main.cpp.
References _acro_rate_max, _actuators_0_circuit_breaker_enabled, _auto_rate_max, _board_rotation, _loop_update_rate_hz, _lp_filters_d, _mc_rate_max, _rate_d, _rate_ff, _rate_i, _rate_int_lim, _rate_p, _rates_prev, CBRK_RATE_CTRL_KEY, circuit_breaker_enabled(), f(), get_rot_matrix(), math::radians(), math::LowPassFilter2p::reset(), and math::LowPassFilter2p::set_cutoff_frequency().
Referenced by MulticopterAttitudeControl(), and parameter_update_poll().
Vector3f MulticopterAttitudeControl::pid_attenuations (float tpa_breakpoint, float tpa_rate) private
Throttle PID attenuation.
Definition at line 474 of file mc_att_control_main.cpp.
References AXIS_INDEX_PITCH, AXIS_INDEX_ROLL, AXIS_INDEX_YAW, f(), and TPA_RATE_LOWER_LIMIT.
Referenced by control_attitude_rates().
int MulticopterAttitudeControl::print_usage (const char * reason = nullptr) static
See also
ModuleBase
Definition at line 65 of file mc_att_control_main.cpp.
References PRINT_MODULE_DESCRIPTION(), PRINT_MODULE_USAGE_COMMAND, PRINT_MODULE_USAGE_DEFAULT_COMMANDS, PRINT_MODULE_USAGE_NAME(), and PX4_WARN.
Referenced by custom_command().
void MulticopterAttitudeControl::run () override
See also
ModuleBase::run()
Definition at line 599 of file mc_att_control_main.cpp.
References _acro_rate_max, _actuators_0_circuit_breaker_enabled, _actuators_0_pub, _actuators_id, _att_control, _battery_status_sub, _controller_status_pub, _gyro_count, _loop_perf, _loop_update_rate_hz, _lp_filters_d, _manual_control_sp_sub, _motor_limits_sub, _params_sub, _rates_int, _rates_prev, _rates_sp, _rates_sp_id, _selected_gyro, _sensor_bias_sub, _sensor_correction_sub, _sensor_gyro_sub, _thrust_sp, _v_att_sp_sub, _v_att_sub, _v_control_mode_sub, _v_rates_sp_pub, _v_rates_sp_sub, _vehicle_land_detected_sub, _vehicle_status_sub, battery_status_poll(), control_attitude(), control_attitude_rates(), dt, matrix::Matrix< Type, M, N >::emult(), f(), hrt_absolute_time(), hrt_abstime, instance, MAX_GYRO_COUNT, math::min(), orb_advertise(), orb_copy(), orb_group_count(), ORB_ID, ORB_PRIO_DEFAULT, orb_publish(), orb_publish_auto(), orb_subscribe(), orb_subscribe_multi(), orb_unsubscribe(), parameter_update_poll(), perf_begin(), perf_end(), rate_ctrl_status_s::pitchspeed, rate_ctrl_status_s::pitchspeed_integ, PX4_ERR, px4_poll(), rate_ctrl_status_s::rollspeed, rate_ctrl_status_s::rollspeed_integ, sensor_bias_poll(), sensor_correction_poll(), math::LowPassFilter2p::set_cutoff_frequency(), math::superexpo(), rate_ctrl_status_s::timestamp, usleep(), vehicle_attitude_poll(), vehicle_control_mode_poll(), vehicle_land_detected_poll(), vehicle_manual_poll(), vehicle_motor_limits_poll(), vehicle_rates_setpoint_poll(), vehicle_status_poll(), rate_ctrl_status_s::yawspeed, rate_ctrl_status_s::yawspeed_integ, and matrix::Matrix< Type, M, N >::zero().
void MulticopterAttitudeControl::sensor_bias_poll () private
Definition at line 348 of file mc_att_control_main.cpp.
References _sensor_bias_sub, orb_check(), orb_copy(), and ORB_ID.
Referenced by run().
void MulticopterAttitudeControl::sensor_correction_poll () private
Definition at line 331 of file mc_att_control_main.cpp.
References _gyro_count, _selected_gyro, _sensor_correction_sub, orb_check(), orb_copy(), and ORB_ID.
Referenced by run().
int MulticopterAttitudeControl::task_spawn (int argc, char * argv[]) static
See also
ModuleBase
Definition at line 864 of file mc_att_control_main.cpp.
References px4_task_spawn_cmd(), SCHED_DEFAULT, and SCHED_PRIORITY_ATTITUDE_CONTROL.
void MulticopterAttitudeControl::vehicle_attitude_poll () private
Definition at line 319 of file mc_att_control_main.cpp.
References _v_att_sub, orb_check(), orb_copy(), and ORB_ID.
Referenced by run().
void MulticopterAttitudeControl::vehicle_attitude_setpoint_poll () private
Definition at line 244 of file mc_att_control_main.cpp.
References _v_att_sp_sub, orb_check(), orb_copy(), and ORB_ID.
Referenced by control_attitude().
void MulticopterAttitudeControl::vehicle_control_mode_poll () private
Definition at line 218 of file mc_att_control_main.cpp.
References _v_control_mode_sub, orb_check(), orb_copy(), and ORB_ID.
Referenced by run().
void MulticopterAttitudeControl::vehicle_land_detected_poll () private
Definition at line 361 of file mc_att_control_main.cpp.
References _vehicle_land_detected_sub, orb_check(), orb_copy(), and ORB_ID.
Referenced by run().
void MulticopterAttitudeControl::vehicle_manual_poll () private
Definition at line 231 of file mc_att_control_main.cpp.
References _manual_control_sp_sub, orb_check(), orb_copy(), and ORB_ID.
Referenced by run().
void MulticopterAttitudeControl::vehicle_motor_limits_poll () private
Definition at line 292 of file mc_att_control_main.cpp.
References _motor_limits_sub, _saturation_status, orb_check(), orb_copy(), ORB_ID, multirotor_motor_limits_s::saturation_status, and MultirotorMixer::saturation_status::value.
Referenced by run().
void MulticopterAttitudeControl::vehicle_rates_setpoint_poll () private
Definition at line 256 of file mc_att_control_main.cpp.
References _v_rates_sp_sub, orb_check(), orb_copy(), and ORB_ID.
Referenced by run().
void MulticopterAttitudeControl::vehicle_status_poll () private
Definition at line 268 of file mc_att_control_main.cpp.
References _actuators_id, _rates_sp_id, _vehicle_status_sub, orb_check(), orb_copy(), and ORB_ID.
Referenced by run().
Member Data Documentation
matrix::Vector3f MulticopterAttitudeControl::_acro_rate_max private
max attitude rates in acro mode
Definition at line 251 of file mc_att_control.hpp.
Referenced by parameters_updated(), and run().
bool MulticopterAttitudeControl::_actuators_0_circuit_breaker_enabled {false} private
circuit breaker to suppress output
Definition at line 153 of file mc_att_control.hpp.
Referenced by parameters_updated(), and run().
orb_advert_t MulticopterAttitudeControl::_actuators_0_pub {nullptr} private
attitude actuator controls publication
Definition at line 147 of file mc_att_control.hpp.
Referenced by run().
orb_id_t MulticopterAttitudeControl::_actuators_id {nullptr} private
pointer to correct actuator controls0 uORB metadata structure
Definition at line 151 of file mc_att_control.hpp.
Referenced by run(), and vehicle_status_poll().
matrix::Vector3f MulticopterAttitudeControl::_att_control private
attitude control vector
Definition at line 181 of file mc_att_control.hpp.
Referenced by control_attitude_rates(), MulticopterAttitudeControl(), and run().
matrix::Vector3f MulticopterAttitudeControl::_auto_rate_max private
attitude rate limits in auto modes
Definition at line 250 of file mc_att_control.hpp.
Referenced by control_attitude(), and parameters_updated().
int MulticopterAttitudeControl::_battery_status_sub {-1} private
battery status subscription
Definition at line 137 of file mc_att_control.hpp.
Referenced by battery_status_poll(), and run().
matrix::Dcmf MulticopterAttitudeControl::_board_rotation private
rotation matrix for the orientation that the board is mounted
Definition at line 183 of file mc_att_control.hpp.
Referenced by control_attitude_rates(), and parameters_updated().
orb_advert_t MulticopterAttitudeControl::_controller_status_pub {nullptr} private
controller status publication
Definition at line 148 of file mc_att_control.hpp.
Referenced by run().
unsigned MulticopterAttitudeControl::_gyro_count {1} private
Definition at line 143 of file mc_att_control.hpp.
Referenced by run(), and sensor_correction_poll().
perf_counter_t MulticopterAttitudeControl::_loop_perf private
loop performance counter
Definition at line 170 of file mc_att_control.hpp.
Referenced by run().
float MulticopterAttitudeControl::_loop_update_rate_hz {initial_update_rate_hz} private
current rate-controller loop update rate in [Hz]
Definition at line 174 of file mc_att_control.hpp.
Referenced by parameters_updated(), and run().
math::LowPassFilter2p MulticopterAttitudeControl::_lp_filters_d[3] private
low-pass filters for D-term (roll, pitch & yaw)
Definition at line 172 of file mc_att_control.hpp.
Referenced by control_attitude_rates(), parameters_updated(), and run().
int MulticopterAttitudeControl::_manual_control_sp_sub {-1} private
manual control setpoint subscription
Definition at line 134 of file mc_att_control.hpp.
Referenced by run(), and vehicle_manual_poll().
matrix::Vector3f MulticopterAttitudeControl::_mc_rate_max private
attitude rate limits in stabilized modes
Definition at line 249 of file mc_att_control.hpp.
Referenced by control_attitude(), and parameters_updated().
int MulticopterAttitudeControl::_motor_limits_sub {-1} private
motor limits subscription
Definition at line 136 of file mc_att_control.hpp.
Referenced by run(), and vehicle_motor_limits_poll().
int MulticopterAttitudeControl::_params_sub {-1} private
parameter updates subscription
Definition at line 133 of file mc_att_control.hpp.
Referenced by parameter_update_poll(), and run().
matrix::Vector3f MulticopterAttitudeControl::_rate_d private
D gain for angular rate error.
Definition at line 246 of file mc_att_control.hpp.
Referenced by control_attitude_rates(), and parameters_updated().
matrix::Vector3f MulticopterAttitudeControl::_rate_ff private
Feedforward gain for desired rates.
Definition at line 247 of file mc_att_control.hpp.
Referenced by control_attitude_rates(), and parameters_updated().
matrix::Vector3f MulticopterAttitudeControl::_rate_i private
I gain for angular rate error.
Definition at line 244 of file mc_att_control.hpp.
Referenced by control_attitude_rates(), and parameters_updated().
matrix::Vector3f MulticopterAttitudeControl::_rate_int_lim private
integrator state limit for rate loop
Definition at line 245 of file mc_att_control.hpp.
Referenced by control_attitude_rates(), and parameters_updated().
DEFINE_PARAMETERS ((ParamFloat<px4::params::MC_ROLL_P>) _roll_p, (ParamFloat<px4::params::MC_ROLLRATE_P>) _roll_rate_p, (ParamFloat<px4::params::MC_ROLLRATE_I>) _roll_rate_i, (ParamFloat<px4::params::MC_RR_INT_LIM>) _roll_rate_integ_lim, (ParamFloat<px4::params::MC_ROLLRATE_D>) _roll_rate_d, (ParamFloat<px4::params::MC_ROLLRATE_FF>) _roll_rate_ff, (ParamFloat<px4::params::MC_PITCH_P>) _pitch_p, (ParamFloat<px4::params::MC_PITCHRATE_P>) _pitch_rate_p, (ParamFloat<px4::params::MC_PITCHRATE_I>) _pitch_rate_i, (ParamFloat<px4::params::MC_PR_INT_LIM>) _pitch_rate_integ_lim, (ParamFloat<px4::params::MC_PITCHRATE_D>) _pitch_rate_d, (ParamFloat<px4::params::MC_PITCHRATE_FF>) _pitch_rate_ff, (ParamFloat<px4::params::MC_YAW_P>) _yaw_p, (ParamFloat<px4::params::MC_YAWRATE_P>) _yaw_rate_p, (ParamFloat<px4::params::MC_YAWRATE_I>) _yaw_rate_i, (ParamFloat<px4::params::MC_YR_INT_LIM>) _yaw_rate_integ_lim, (ParamFloat<px4::params::MC_YAWRATE_D>) _yaw_rate_d, (ParamFloat<px4::params::MC_YAWRATE_FF>) _yaw_rate_ff, (ParamFloat<px4::params::MC_DTERM_CUTOFF>) _d_term_cutoff_freq, (ParamFloat<px4::params::MC_TPA_BREAK_P>) _tpa_breakpoint_p, (ParamFloat<px4::params::MC_TPA_BREAK_I>) _tpa_breakpoint_i, (ParamFloat<px4::params::MC_TPA_BREAK_D>) _tpa_breakpoint_d, (ParamFloat<px4::params::MC_TPA_RATE_P>) _tpa_rate_p, (ParamFloat<px4::params::MC_TPA_RATE_I>) _tpa_rate_i, (ParamFloat<px4::params::MC_TPA_RATE_D>) _tpa_rate_d, (ParamFloat<px4::params::MC_ROLLRATE_MAX>) _roll_rate_max, (ParamFloat<px4::params::MC_PITCHRATE_MAX>) _pitch_rate_max, (ParamFloat<px4::params::MC_YAWRATE_MAX>) _yaw_rate_max, (ParamFloat<px4::params::MC_YAWRAUTO_MAX>) _yaw_auto_max, (ParamFloat<px4::params::MC_ACRO_R_MAX>) _acro_roll_max, (ParamFloat<px4::params::MC_ACRO_P_MAX>) _acro_pitch_max, (ParamFloat<px4::params::MC_ACRO_Y_MAX>) _acro_yaw_max, (ParamFloat<px4::params::MC_ACRO_EXPO>) _acro_expo_rp, (ParamFloat<px4::params::MC_ACRO_EXPO_Y>) _acro_expo_y, (ParamFloat<px4::params::MC_ACRO_SUPEXPO>) _acro_superexpo_rp, (ParamFloat<px4::params::MC_ACRO_SUPEXPOY>) _acro_superexpo_y, (ParamFloat<px4::params::MC_RATT_TH>) _rattitude_thres, (ParamBool<px4::params::MC_BAT_SCALE_EN>) _bat_scale_en, (ParamInt<px4::params::SENS_BOARD_ROT>) _board_rotation_param, (ParamFloat<px4::params::SENS_BOARD_X_OFF>) _board_offset_x, (ParamFloat<px4::params::SENS_BOARD_Y_OFF>) _board_offset_y, (ParamFloat<px4::params::SENS_BOARD_Z_OFF>) _board_offset_z, (ParamFloat<px4::params::VT_WV_YAWR_SCL>) _vtol_wv_yaw_rate_scale) matrix matrix::Vector3f MulticopterAttitudeControl::_rate_p private
< P gain for attitude control
P gain for angular rate error
Definition at line 185 of file mc_att_control.hpp.
Referenced by control_attitude_rates(), and parameters_updated().
matrix::Vector3f MulticopterAttitudeControl::_rates_int private
angular rates integral error
Definition at line 179 of file mc_att_control.hpp.
Referenced by control_attitude(), control_attitude_rates(), MulticopterAttitudeControl(), and run().
matrix::Vector3f MulticopterAttitudeControl::_rates_prev private
angular rates on previous step
Definition at line 176 of file mc_att_control.hpp.
Referenced by control_attitude_rates(), MulticopterAttitudeControl(), parameters_updated(), and run().
matrix::Vector3f MulticopterAttitudeControl::_rates_prev_filtered private
angular rates on previous step (low-pass filtered)
Definition at line 177 of file mc_att_control.hpp.
Referenced by control_attitude_rates(), and MulticopterAttitudeControl().
matrix::Vector3f MulticopterAttitudeControl::_rates_sp private
angular rates setpoint
Definition at line 178 of file mc_att_control.hpp.
Referenced by control_attitude(), control_attitude_rates(), MulticopterAttitudeControl(), and run().
orb_id_t MulticopterAttitudeControl::_rates_sp_id {nullptr} private
pointer to correct rates setpoint uORB metadata structure
Definition at line 150 of file mc_att_control.hpp.
Referenced by run(), and vehicle_status_poll().
MultirotorMixer::saturation_status MulticopterAttitudeControl::_saturation_status {} private
Definition at line 168 of file mc_att_control.hpp.
Referenced by control_attitude_rates(), and vehicle_motor_limits_poll().
int MulticopterAttitudeControl::_selected_gyro {0} private
Definition at line 144 of file mc_att_control.hpp.
Referenced by control_attitude_rates(), run(), and sensor_correction_poll().
int MulticopterAttitudeControl::_sensor_bias_sub {-1} private
sensor in-run bias correction subscription
Definition at line 140 of file mc_att_control.hpp.
Referenced by run(), and sensor_bias_poll().
int MulticopterAttitudeControl::_sensor_correction_sub {-1} private
sensor thermal correction subscription
Definition at line 139 of file mc_att_control.hpp.
Referenced by run(), and sensor_correction_poll().
int MulticopterAttitudeControl::_sensor_gyro_sub[MAX_GYRO_COUNT] private
gyro data subscription
Definition at line 138 of file mc_att_control.hpp.
Referenced by MulticopterAttitudeControl(), and run().
float MulticopterAttitudeControl::_thrust_sp private
thrust setpoint
Definition at line 180 of file mc_att_control.hpp.
Referenced by control_attitude(), MulticopterAttitudeControl(), and run().
int MulticopterAttitudeControl::_v_att_sp_sub {-1} private
vehicle attitude setpoint subscription
Definition at line 130 of file mc_att_control.hpp.
Referenced by run(), and vehicle_attitude_setpoint_poll().
int MulticopterAttitudeControl::_v_att_sub {-1} private
vehicle attitude subscription
Definition at line 129 of file mc_att_control.hpp.
Referenced by run(), and vehicle_attitude_poll().
int MulticopterAttitudeControl::_v_control_mode_sub {-1} private
vehicle control mode subscription
Definition at line 132 of file mc_att_control.hpp.
Referenced by run(), and vehicle_control_mode_poll().
orb_advert_t MulticopterAttitudeControl::_v_rates_sp_pub {nullptr} private
rate setpoint publication
Definition at line 146 of file mc_att_control.hpp.
Referenced by run().
int MulticopterAttitudeControl::_v_rates_sp_sub {-1} private
vehicle rates setpoint subscription
Definition at line 131 of file mc_att_control.hpp.
Referenced by run(), and vehicle_rates_setpoint_poll().
int MulticopterAttitudeControl::_vehicle_land_detected_sub {-1} private
vehicle land detected subscription
Definition at line 141 of file mc_att_control.hpp.
Referenced by run(), and vehicle_land_detected_poll().
int MulticopterAttitudeControl::_vehicle_status_sub {-1} private
vehicle status subscription
Definition at line 135 of file mc_att_control.hpp.
Referenced by run(), and vehicle_status_poll().
constexpr const float MulticopterAttitudeControl::initial_update_rate_hz = 250.f static private
loop update rate used for initialization
Definition at line 173 of file mc_att_control.hpp.
Referenced by MulticopterAttitudeControl().
The documentation for this class was generated from the following files:
src/modules/mc_att_control/mc_att_control.hpp
src/modules/mc_att_control/mc_att_control_main.cpp