PX4 Firmware: src/systemcmds/pwm/pwm.cpp File Reference
pwm.cpp File Reference
#include <px4_config.h>
#include <px4_tasks.h>
#include <px4_posix.h>
#include <px4_getopt.h>
#include <px4_defines.h>
#include <px4_log.h>
#include <px4_module.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <stdbool.h>
#include <unistd.h>
#include <fcntl.h>
#include <poll.h>
#include <sys/ioctl.h>
#include <sys/stat.h>
#include <arch/board/board.h>
#include "systemlib/err.h"
#include <parameters/param.h>
#include "drivers/drv_pwm_output.h"
Functions
static void usage (const char *reason)
__BEGIN_DECLS __EXPORT int pwm_main (int argc, char *argv[])
static unsigned get_parameter_value (const char *option, const char *paramDescription)
Function Documentation
static unsigned get_parameter_value (const char * option, const char * paramDescription) static
Definition at line 157 of file pwm.cpp.
References param_find(), param_get(), PARAM_INVALID, and PX4_ERR.
Referenced by pwm_main().
int pwm_main (int argc, char * argv[])
Definition at line 200 of file pwm.cpp.
References pwm_output_values::channel_count, command, err, fd, get_parameter_value(), idle, OK, PWM_OUTPUT0_DEVICE_PATH, PWM_OUTPUT_MAX_CHANNELS, PWM_SERVO_ARM, PWM_SERVO_DISARM, PWM_SERVO_GET, PWM_SERVO_GET_COUNT, PWM_SERVO_GET_DEFAULT_UPDATE_RATE, PWM_SERVO_GET_DISARMED_PWM, PWM_SERVO_GET_FAILSAFE_PWM, PWM_SERVO_GET_MAX_PWM, PWM_SERVO_GET_MIN_PWM, PWM_SERVO_GET_RATEGROUP, PWM_SERVO_GET_SELECT_UPDATE_RATE, PWM_SERVO_GET_TRIM_PWM, PWM_SERVO_GET_UPDATE_RATE, PWM_SERVO_SET, PWM_SERVO_SET_ARM_OK, PWM_SERVO_SET_DISARMED_PWM, PWM_SERVO_SET_FAILSAFE_PWM, PWM_SERVO_SET_FORCE_FAILSAFE, PWM_SERVO_SET_MAX_PWM, PWM_SERVO_SET_MIN_PWM, PWM_SERVO_SET_SELECT_UPDATE_RATE, PWM_SERVO_SET_TERMINATION_FAILSAFE, PWM_SERVO_SET_UPDATE_RATE, PX4_ERR, px4_getopt(), PX4_INFO, px4_ioctl(), px4_open(), PX4_WARN, read(), up_pwm_update(), usage(), usleep(), and pwm_output_values::values.
static void usage (const char * reason) static
Definition at line 75 of file pwm.cpp.
References PRINT_MODULE_DESCRIPTION(), PRINT_MODULE_USAGE_ARG(), PRINT_MODULE_USAGE_COMMAND_DESCR(), PRINT_MODULE_USAGE_NAME(), PRINT_MODULE_USAGE_PARAM_COMMENT(), PRINT_MODULE_USAGE_PARAM_FLAG(), PRINT_MODULE_USAGE_PARAM_INT(), PRINT_MODULE_USAGE_PARAM_STRING(), and PX4_WARN.
Referenced by pwm_main().