PX4 Firmware: MavlinkStreamCameraCapture Class Reference
MavlinkStreamCameraCapture Class Reference
Public Member Functions
const char * get_name () const
uint16_t get_id ()
unsigned get_size ()
Get maximal total messages size on update.
Public Member Functions inherited from MavlinkStream
MavlinkStream (Mavlink *mavlink)
virtual ~MavlinkStream ()=default
MavlinkStream (const MavlinkStream &)=delete
MavlinkStream & operator= (const MavlinkStream &)=delete
MavlinkStream (MavlinkStream &&)=delete
MavlinkStream & operator= (MavlinkStream &&)=delete
void set_interval (const int interval)
Get the interval.
int get_interval ()
Get the interval.
int update (const hrt_abstime &t)
Update subscriptions and send message if necessary.
virtual bool const_rate ()
virtual unsigned get_size_avg ()
Get the average message size.
bool first_message_sent () const
void reset_last_sent ()
Reset the time of last sent to 0.
Static Public Member Functions
static const char * get_name_static ()
static uint16_t get_id_static ()
static MavlinkStream * new_instance (Mavlink *mavlink)
Protected Member Functions
MavlinkStreamCameraCapture (Mavlink *mavlink)
bool send (const hrt_abstime t)
Protected Member Functions inherited from MavlinkStream
virtual void update_data ()
Function to collect/update data for the streams at a high rate independant of actual stream rate.
Private Member Functions
MavlinkStreamCameraCapture (MavlinkStreamCameraCapture &)=delete
MavlinkStreamCameraCapture & operator= (const MavlinkStreamCameraCapture &)=delete
Private Attributes
MavlinkOrbSubscription * _status_sub
Additional Inherited Members
Public Attributes inherited from MavlinkStream
MavlinkStream * next {nullptr}
Protected Attributes inherited from MavlinkStream
Mavlink *const _mavlink
int _interval {1000000}
if set to negative value = unlimited rate
Detailed Description
Definition at line 3721 of file mavlink_messages.cpp.
Constructor & Destructor Documentation
MavlinkStreamCameraCapture::MavlinkStreamCameraCapture (MavlinkStreamCameraCapture &) private delete
MavlinkStreamCameraCapture::MavlinkStreamCameraCapture (Mavlink * mavlink) inline explicit protected
Definition at line 3762 of file mavlink_messages.cpp.
Member Function Documentation
uint16_t MavlinkStreamCameraCapture::get_id () inline virtual
Implements MavlinkStream.
Definition at line 3739 of file mavlink_messages.cpp.
References MavlinkStreamHeartbeat::get_id_static().
static uint16_t MavlinkStreamCameraCapture::get_id_static () inline static
Definition at line 3734 of file mavlink_messages.cpp.
const char* MavlinkStreamCameraCapture::get_name () const inline virtual
Implements MavlinkStream.
Definition at line 3724 of file mavlink_messages.cpp.
References get_name_static().
static const char* MavlinkStreamCameraCapture::get_name_static () inline static
Definition at line 3729 of file mavlink_messages.cpp.
Referenced by get_name().
unsigned MavlinkStreamCameraCapture::get_size () inline virtual
Get maximal total messages size on update.
Implements MavlinkStream.
Definition at line 3749 of file mavlink_messages.cpp.
static MavlinkStream* MavlinkStreamCameraCapture::new_instance (Mavlink * mavlink) inline static
Definition at line 3744 of file mavlink_messages.cpp.
MavlinkStreamCameraCapture& MavlinkStreamCameraCapture::operator= (const MavlinkStreamCameraCapture &) private delete
bool MavlinkStreamCameraCapture::send (const hrt_abstime t) inline protected virtual
Implements MavlinkStream.
Definition at line 3766 of file mavlink_messages.cpp.
References MavlinkStream::_mavlink, vehicle_status_s::arming_state, Mavlink::get_channel(), msg, status, and MavlinkOrbSubscription::update().
Member Data Documentation
MavlinkOrbSubscription* MavlinkStreamCameraCapture::_status_sub private
Definition at line 3755 of file mavlink_messages.cpp.
The documentation for this class was generated from the following file:
src/modules/mavlink/mavlink_messages.cpp