PX4 Firmware: UavcanBarometerBridge Class Reference
UavcanBarometerBridge Class Reference
#include <baro.hpp>
Public Member Functions
UavcanBarometerBridge (uavcan::INode &node)
const char * get_name () const override
Returns ASCII name of the bridge.
int init () override
Starts the bridge.
Public Member Functions inherited from UavcanCDevSensorBridgeBase
virtual ~UavcanCDevSensorBridgeBase ()
unsigned get_num_redundant_channels () const override
Returns number of active redundancy channels.
void print_status () const override
Prints current status in a human readable format to stdout.
Public Member Functions inherited from IUavcanSensorBridge
virtual ~IUavcanSensorBridge ()=default
Public Member Functions inherited from ListNode< IUavcanSensorBridge *>
void setSibling (IUavcanSensorBridge * sibling)
const IUavcanSensorBridge * getSibling () const
Public Member Functions inherited from device::CDev
CDev (const char *name, const char *devname)
Constructor.
virtual ~CDev ()=default
virtual int ioctl (file_t *filep, int cmd, unsigned long arg)
Perform an ioctl operation on the device.
Public Member Functions inherited from device::Device
Device (const Device &)=delete
Device & operator= (const Device &)=delete
Device (Device &&)=delete
Device & operator= (Device &&)=delete
virtual ~Device ()=default
Destructor.
virtual int read (unsigned address, void *data, unsigned count)
Read directly from the device.
virtual int write (unsigned address, void *data, unsigned count)
Write directly to the device.
virtual int ioctl (unsigned operation, unsigned &arg)
Perform a device-specific operation.
uint32_t get_device_id () const
DeviceBusType get_device_bus_type () const
Return the bus type the device is connected to.
void set_device_bus_type (DeviceBusType bus_type)
uint8_t get_device_bus () const
Return the bus ID the device is connected to.
void set_device_bus (uint8_t bus)
uint8_t get_device_address () const
Return the bus address of the device.
void set_device_address (int address)
uint8_t get_device_type () const
Return the device type.
void set_device_type (uint8_t devtype)
virtual bool external () const
Public Member Functions inherited from cdev::CDev
CDev (const char *devname)
Constructor.
CDev (const CDev &)=delete
CDev & operator= (const CDev &)=delete
CDev (CDev &&)=delete
CDev & operator= (CDev &&)=delete
virtual int open (file_t *filep)
Handle an open of the device.
virtual int close (file_t *filep)
Handle a close of the device.
virtual ssize_t read (file_t *filep, char *buffer, size_t buflen)
Perform a read from the device.
virtual ssize_t write (file_t *filep, const char *buffer, size_t buflen)
Perform a write to the device.
virtual off_t seek (file_t *filep, off_t offset, int whence)
Perform a logical seek operation on the device.
virtual int poll (file_t *filep, px4_pollfd_struct_t *fds, bool setup)
Perform a poll setup/teardown operation.
const char * get_devname () const
Get the device name.
Static Public Attributes
static const char *const NAME = "baro"
Static Public Attributes inherited from IUavcanSensorBridge
static constexpr unsigned MAX_NAME_LEN = 20
Private Types
typedef uavcan::MethodBinder< UavcanBarometerBridge *, void(UavcanBarometerBridge::*)(const uavcan::ReceivedDataStructure< uavcan::equipment::air_data::StaticPressure > &) > AirPressureCbBinder
typedef uavcan::MethodBinder< UavcanBarometerBridge *, void(UavcanBarometerBridge::*)(const uavcan::ReceivedDataStructure< uavcan::equipment::air_data::StaticTemperature > &) > AirTemperatureCbBinder
Private Member Functions
void air_pressure_sub_cb (const uavcan::ReceivedDataStructure< uavcan::equipment::air_data::StaticPressure > &msg)
void air_temperature_sub_cb (const uavcan::ReceivedDataStructure< uavcan::equipment::air_data::StaticTemperature > &msg)
Private Attributes
uavcan::Subscriber< uavcan::equipment::air_data::StaticPressure, AirPressureCbBinder > _sub_air_pressure_data
uavcan::Subscriber< uavcan::equipment::air_data::StaticTemperature, AirTemperatureCbBinder > _sub_air_temperature_data
float last_temperature_kelvin {0.0f}
Additional Inherited Members
Public Types inherited from device::Device
enum DeviceBusType {
DeviceBusType_UNKNOWN = 0, DeviceBusType_I2C = 1, DeviceBusType_SPI = 2, DeviceBusType_UAVCAN = 3,
DeviceBusType_SIMULATION = 4
}
Device bus types for DEVID.
Static Public Member Functions inherited from IUavcanSensorBridge
static void make_all (uavcan::INode &node, List< IUavcanSensorBridge *> &list)
Sensor bridge factory.
Static Public Member Functions inherited from device::Device
static const char * get_device_bus_string (DeviceBusType bus)
static int device_id_print_buffer (char *buffer, int length, uint32_t id)
Print decoded device id string to a buffer.
Protected Member Functions inherited from UavcanCDevSensorBridgeBase
UavcanCDevSensorBridgeBase (const char *name, const char *devname, const char *class_devname, const orb_id_t orb_topic_sensor, const unsigned max_channels=DEFAULT_MAX_CHANNELS)
void publish (const int node_id, const void *report)
Sends one measurement into appropriate ORB topic.
Protected Member Functions inherited from device::Device
Device (const char *name)
Device (const char *name, DeviceBusType bus_type, uint8_t bus, uint8_t address, uint8_t devtype=0)
Device (DeviceBusType bus_type, uint8_t bus, uint8_t address, uint8_t devtype=0)
Protected Member Functions inherited from cdev::CDev
virtual pollevent_t poll_state (file_t *filep)
Check the current state of the device for poll events from the perspective of the file.
virtual void poll_notify (pollevent_t events)
Report new poll events.
virtual void poll_notify_one (px4_pollfd_struct_t *fds, pollevent_t events)
Internal implementation of poll_notify.
virtual int open_first (file_t *filep)
Notification of the first open.
virtual int close_last (file_t *filep)
Notification of the last close.
virtual int register_class_devname (const char *class_devname)
Register a class device name, automatically adding device class instance suffix if need be.
virtual int unregister_class_devname (const char *class_devname, unsigned class_instance)
Register a class device name, automatically adding device class instance suffix if need be.
void lock ()
Take the driver lock.
void unlock ()
Release the driver lock.
int unregister_driver_and_memory ()
First, unregisters the driver.
Protected Attributes inherited from ListNode< IUavcanSensorBridge *>
IUavcanSensorBridge * _list_node_sibling
Protected Attributes inherited from device::CDev
bool _pub_blocked {false}
true if publishing should be blocked
Protected Attributes inherited from device::Device
const char * _name {nullptr}
driver name
bool _debug_enabled {false}
if true, debug messages are printed
Protected Attributes inherited from cdev::CDev
px4_sem_t _lock
lock to protect access to all class members (also for derived classes)
Static Protected Attributes inherited from UavcanCDevSensorBridgeBase
static constexpr unsigned DEFAULT_MAX_CHANNELS = 5
Static Protected Attributes inherited from cdev::CDev
static const px4_file_operations_t fops = {}
Pointer to the default cdev file operations table; useful for registering clone devices etc.
Detailed Description
Author
Pavel Kirienko pavel.nosp@m..kir.nosp@m.ienko.nosp@m.@gma.nosp@m.il.co.nosp@m.m
Definition at line 46 of file baro.hpp.
Member Typedef Documentation
AirPressureCbBinder
typedef uavcan::MethodBinder< UavcanBarometerBridge *, void (UavcanBarometerBridge::*) (const uavcan::ReceivedDataStructure<uavcan::equipment::air_data::StaticPressure> &) > UavcanBarometerBridge::AirPressureCbBinder private
Definition at line 65 of file baro.hpp.
AirTemperatureCbBinder
typedef uavcan::MethodBinder< UavcanBarometerBridge *, void (UavcanBarometerBridge::*) (const uavcan::ReceivedDataStructure<uavcan::equipment::air_data::StaticTemperature> &) > UavcanBarometerBridge::AirTemperatureCbBinder private
Definition at line 70 of file baro.hpp.
Constructor & Destructor Documentation
UavcanBarometerBridge()
UavcanBarometerBridge::UavcanBarometerBridge (uavcan::INode & node)
Definition at line 44 of file baro.cpp.
Member Function Documentation
air_pressure_sub_cb()
void UavcanBarometerBridge::air_pressure_sub_cb (const uavcan::ReceivedDataStructure< uavcan::equipment::air_data::StaticPressure > & msg) private
Definition at line 83 of file baro.cpp.
References hrt_absolute_time(), last_temperature_kelvin, UavcanCDevSensorBridgeBase::publish(), and sensor_baro_s::timestamp.
Referenced by get_name(), and init().
air_temperature_sub_cb()
void UavcanBarometerBridge::air_temperature_sub_cb (const uavcan::ReceivedDataStructure< uavcan::equipment::air_data::StaticTemperature > & msg) private
Definition at line 76 of file baro.cpp.
References last_temperature_kelvin.
Referenced by get_name(), and init().
get_name()
const char* UavcanBarometerBridge::get_name () const inline override virtual
Returns ASCII name of the bridge.
Implements IUavcanSensorBridge.
Definition at line 53 of file baro.hpp.
References air_pressure_sub_cb(), air_temperature_sub_cb(), init(), msg, and NAME.
init()
int UavcanBarometerBridge::init () override virtual
Starts the bridge.
Returns
Non-negative value on success, negative on error.
Implements IUavcanSensorBridge.
Definition at line 50 of file baro.cpp.
References _sub_air_pressure_data, _sub_air_temperature_data, air_pressure_sub_cb(), air_temperature_sub_cb(), DEVICE_LOG, and device::CDev::init().
Referenced by get_name().
Member Data Documentation
_sub_air_pressure_data
uavcan::Subscriber<uavcan::equipment::air_data::StaticPressure, AirPressureCbBinder> UavcanBarometerBridge::_sub_air_pressure_data private
Definition at line 72 of file baro.hpp.
Referenced by init().
_sub_air_temperature_data
uavcan::Subscriber<uavcan::equipment::air_data::StaticTemperature, AirTemperatureCbBinder> UavcanBarometerBridge::_sub_air_temperature_data private
Definition at line 73 of file baro.hpp.
Referenced by init().
last_temperature_kelvin
float UavcanBarometerBridge::last_temperature_kelvin {0.0f} private
Definition at line 75 of file baro.hpp.
Referenced by air_pressure_sub_cb(), and air_temperature_sub_cb().
NAME
const char *const UavcanBarometerBridge::NAME = "baro" static
Author
Pavel Kirienko pavel.nosp@m..kir.nosp@m.ienko.nosp@m.@gma.nosp@m.il.co.nosp@m.m
Definition at line 49 of file baro.hpp.
Referenced by get_name().
The documentation for this class was generated from the following files:
src/drivers/uavcan/sensors/baro.hpp
src/drivers/uavcan/sensors/baro.cpp