PX4 Firmware: src/drivers/stm32/drv_pwm_servo.c File Reference
drv_pwm_servo.c File Reference
#include <px4_config.h>
#include <nuttx/arch.h>
#include <nuttx/irq.h>
#include <sys/types.h>
#include <stdbool.h>
#include <assert.h>
#include <debug.h>
#include <time.h>
#include <queue.h>
#include <errno.h>
#include <string.h>
#include <stdio.h>
#include <arch/board/board.h>
#include <drivers/drv_pwm_output.h>
#include "drv_io_timer.h"
#include "drv_pwm_servo.h"
#include <stm32_tim.h>
Functions
int up_pwm_servo_set (unsigned channel, servo_position_t value)
Set the current output value for a channel.
servo_position_t up_pwm_servo_get (unsigned channel)
Get the current output value for a channel.
int up_pwm_servo_init (uint32_t channel_mask)
Intialise the PWM servo outputs using the specified configuration.
void up_pwm_servo_deinit (void)
De-initialise the PWM servo outputs.
int up_pwm_servo_set_rate_group_update (unsigned group, unsigned rate)
Set the update rate for a given rate group.
void up_pwm_update (void)
Trigger all timer's channels in Oneshot mode to fire the oneshot with updated values.
int up_pwm_servo_set_rate (unsigned rate)
Set the servo update rate for all rate groups.
uint32_t up_pwm_servo_get_rate_group (unsigned group)
Get a bitmap of output channels assigned to a given rate group.
void up_pwm_servo_arm (bool armed)
Arm or disarm servo outputs.
Function Documentation
void up_pwm_servo_arm (bool armed)
Arm or disarm servo outputs.
When disarmed, servos output no pulse.
Bug:
This function should, but does not, guarantee that any pulse currently in progress is cleanly completed.
Parameters
armed If true, outputs are armed; if false they are disarmed.
Definition at line 166 of file drv_pwm_servo.c.
References IO_TIMER_ALL_MODES_CHANNELS, io_timer_set_enable(), IOTimerChanMode_OneShot, and IOTimerChanMode_PWMOut.
Referenced by mixer_tick(), and PX4FMU::update_pwm_out_state().
void up_pwm_servo_deinit (void)
De-initialise the PWM servo outputs.
Definition at line 113 of file drv_pwm_servo.c.
References up_pwm_servo_arm().
Referenced by PX4FMU::set_mode(), MK::task_main(), and PX4FMU::~PX4FMU().
servo_position_t up_pwm_servo_get (unsigned channel)
Get the current output value for a channel.
Parameters
channel The channel to read.
Returns
The output pulse width in microseconds, or zero if outputs are not armed or not configured.
Definition at line 71 of file drv_pwm_servo.c.
References io_channel_get_ccr().
Referenced by PX4FMU::pwm_ioctl().
uint32_t up_pwm_servo_get_rate_group (unsigned group)
Get a bitmap of output channels assigned to a given rate group.
Parameters
group The rate group to query. Rate groups are assigned contiguously starting from zero.
Returns
A bitmap of channels assigned to the rate group, or zero if the group number has no channels.
Definition at line 157 of file drv_pwm_servo.c.
References io_timer_get_group(), io_timer_get_mode_channels(), IOTimerChanMode_OneShot, and IOTimerChanMode_PWMOut.
Referenced by pwm_configure_rates(), PX4FMU::pwm_ioctl(), registers_get(), and PX4FMU::set_pwm_rate().
int up_pwm_servo_init (uint32_t channel_mask)
Intialise the PWM servo outputs using the specified configuration.
Parameters
channel_mask Bitmask of channels (LSB = channel 0) to enable. This allows some of the channels to remain configured as GPIOs or as another function.
Returns
OK on success.
Definition at line 76 of file drv_pwm_servo.c.
References io_timer_channel_init(), io_timer_free_channel(), io_timer_get_mode_channels(), io_timer_is_channel_free(), IOTimerChanMode_OneShot, IOTimerChanMode_PWMOut, MAX_TIMER_IO_CHANNELS, and OK.
Referenced by PX4FMU::update_pwm_out_state(), and user_start().
int up_pwm_servo_set (unsigned channel, servo_position_t value)
Set the current output value for a channel.
Parameters
channel The channel to set.
value The output pulse width in microseconds.
Definition at line 66 of file drv_pwm_servo.c.
References io_timer_set_ccr().
Referenced by PX4FMU::cycle(), mixer_tick(), PX4FMU::pwm_ioctl(), and PX4FMU::write().
int up_pwm_servo_set_rate (unsigned rate)
Set the servo update rate for all rate groups.
Parameters
rate The update rate in Hz to set.
Returns
OK on success, -ERANGE if an unsupported update rate is set.
Definition at line 148 of file drv_pwm_servo.c.
References MAX_IO_TIMERS, and up_pwm_servo_set_rate_group_update().
Referenced by MK::task_main().
int up_pwm_servo_set_rate_group_update (unsigned group, unsigned rate)
Set the update rate for a given rate group.
Parameters
group The rate group whose update rate will be changed.
rate The update rate in Hz.
Returns
OK if the group was adjusted, -ERANGE if an unsupported update rate is set.
Definition at line 119 of file drv_pwm_servo.c.
References io_timer_set_rate(), io_timers, and MAX_IO_TIMERS.
Referenced by pwm_configure_rates(), and PX4FMU::set_pwm_rate().
void up_pwm_update (void)
Trigger all timer's channels in Oneshot mode to fire the oneshot with updated values.
Nothing is done if not in oneshot mode.
Definition at line 143 of file drv_pwm_servo.c.
References io_timer_trigger().
Referenced by PX4FMU::cycle(), mixer_tick(), pwm_main(), and registers_set().