PX4 Firmware: src/modules/simulator/simulator.cpp File Reference
simulator.cpp File Reference
A device simulator.
#include <px4_log.h>
#include <px4_tasks.h>
#include <px4_time.h>
#include <pthread.h>
#include <poll.h>
#include <systemlib/err.h>
#include <errno.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <sys/types.h>
#include <drivers/drv_board_led.h>
#include "simulator.h"
Functions
static void usage ()
__BEGIN_DECLS int simulator_main (int argc, char *argv[])
Variables
static px4_task_t g_sim_task = -1
Detailed Description
A device simulator.
Definition in file simulator.cpp.
Function Documentation
__END_DECLS int simulator_main (int argc, char * argv[])
Definition at line 193 of file simulator.cpp.
References g_sim_task, Simulator::getInstance(), px4_enable_sim_lockstep(), px4_exit_requested(), px4_task_delete(), px4_task_spawn_cmd(), PX4_WARN, SCHED_DEFAULT, SCHED_PRIORITY_MAX, Simulator::start(), usage(), usleep(), and warnx.
Referenced by usage().
static void usage (void) static
Definition at line 179 of file simulator.cpp.
References __BEGIN_DECLS, __END_DECLS, PX4_WARN, and simulator_main().
Referenced by simulator_main().
Variable Documentation
px4_task_t g_sim_task = -1 static
Definition at line 56 of file simulator.cpp.
Referenced by simulator_main().