PX4 Firmware: src/lib/circuit_breaker/circuit_breaker.cpp File Reference
circuit_breaker.cpp File Reference
#include "circuit_breaker.h"
#include <stdint.h>
#include <px4_defines.h>
Functions
bool circuit_breaker_enabled (const char *breaker, int32_t magic)
Function Documentation
bool circuit_breaker_enabled (const char * breaker, int32_t magic)
Definition at line 50 of file circuit_breaker.cpp.
Referenced by ToneAlarm::frequency_to_divisor(), get_circuit_breaker_params(), PX4IO::init(), PX4FMU::init(), MulticopterAttitudeControl::parameters_updated(), ToneAlarm::start_note(), and PX4IO::task_main().