PX4 Firmware: control::BlockIntegralTrap Class Reference
control::BlockIntegralTrap Class Reference
A trapezoidal integrator.
#include <BlockIntegralTrap.hpp>
Public Member Functions
BlockIntegralTrap (SuperBlock *parent, const char *name)
virtual ~BlockIntegralTrap ()
float update (float input)
float getU ()
float getY ()
float getMax ()
void setU (float u)
void setY (float y)
Public Member Functions inherited from control::SuperBlock
SuperBlock (SuperBlock *parent, const char *name)
~SuperBlock ()=default
SuperBlock (const SuperBlock &)=delete
SuperBlock & operator= (const SuperBlock &)=delete
SuperBlock (SuperBlock &&)=delete
SuperBlock & operator= (SuperBlock &&)=delete
void setDt (float dt) override
void updateParams () override
void updateSubscriptions () override
void updatePublications () override
Public Member Functions inherited from control::Block
Block (SuperBlock *parent, const char *name)
virtual ~Block ()=default
Block (const Block &)=delete
Block & operator= (const Block &)=delete
Block (Block &&)=delete
Block & operator= (Block &&)=delete
void getName (char *name, size_t n)
float getDt ()
Public Member Functions inherited from ListNode< Block * >
ListNode ()
ListNode (const ListNode &)=delete
ListNode (ListNode &&)=delete
virtual ~ListNode ()=default
ListNode & operator= (const ListNode &)=delete
ListNode & operator= (ListNode &&)=delete
void setSibling (Block *sibling)
const Block * getSibling ()
Protected Attributes
float _u
previous input
float _y
previous output
BlockLimitSym _limit
limiter
Protected Attributes inherited from control::SuperBlock
List< Block * > _children
Protected Attributes inherited from control::Block
const char * _name
SuperBlock * _parent
float _dt {0.0f}
List< uORB::SubscriptionNode * > _subscriptions
List< uORB::PublicationNode * > _publications
List< BlockParamBase * > _params
Protected Attributes inherited from ListNode< Block * >
Block * _sibling
Additional Inherited Members
Protected Member Functions inherited from control::SuperBlock
List< Block * > & getChildren ()
void updateChildParams ()
void updateChildSubscriptions ()
void updateChildPublications ()
Protected Member Functions inherited from control::Block
virtual void updateParamsSubclass ()
SuperBlock * getParent ()
List< uORB::SubscriptionNode * > & getSubscriptions ()
List< uORB::PublicationNode * > & getPublications ()
List< BlockParamBase * > & getParams ()
Detailed Description
A trapezoidal integrator.
http://en.wikipedia.org/wiki/Trapezoidal_rule A limiter is built into the class to bound the integral's internal state. This is important for windup protection.
See also
Limit
Definition at line 66 of file BlockIntegralTrap.hpp.
Constructor & Destructor Documentation
control::BlockIntegralTrap::BlockIntegralTrap (SuperBlock * parent, const char * name) inline
Definition at line 70 of file BlockIntegralTrap.hpp.
virtual control::BlockIntegralTrap::~BlockIntegralTrap () inline virtual
Definition at line 75 of file BlockIntegralTrap.hpp.
Member Function Documentation
float control::BlockIntegralTrap::getMax () inline
Definition at line 80 of file BlockIntegralTrap.hpp.
Referenced by control::blockIntegralTrapTest(), and blockIntegralTrapTest().
float control::BlockIntegralTrap::getU () inline
Definition at line 78 of file BlockIntegralTrap.hpp.
Referenced by control::blockIntegralTrapTest(), blockIntegralTrapTest(), and update().
float control::BlockIntegralTrap::getY () inline
Definition at line 79 of file BlockIntegralTrap.hpp.
Referenced by control::blockIntegralTrapTest(), blockIntegralTrapTest(), and update().
void control::BlockIntegralTrap::setU (float u) inline
Definition at line 81 of file BlockIntegralTrap.hpp.
Referenced by control::blockIntegralTrapTest(), blockIntegralTrapTest(), and update().
void control::BlockIntegralTrap::setY (float y) inline
Definition at line 82 of file BlockIntegralTrap.hpp.
Referenced by control::blockIntegralTrapTest(), blockIntegralTrapTest(), and update().
float control::BlockIntegralTrap::update (float input)
Definition at line 48 of file BlockIntegralTrap.cpp.
References _limit, f(), control::Block::getDt(), getU(), getY(), setU(), setY(), and control::BlockLimitSym::update().
Referenced by control::blockIntegralTrapTest(), and blockIntegralTrapTest().
Member Data Documentation
BlockLimitSym control::BlockIntegralTrap::_limit protected
limiter
Definition at line 87 of file BlockIntegralTrap.hpp.
Referenced by update().
float control::BlockIntegralTrap::_u protected
previous input
Definition at line 85 of file BlockIntegralTrap.hpp.
float control::BlockIntegralTrap::_y protected
previous output
Definition at line 86 of file BlockIntegralTrap.hpp.
The documentation for this class was generated from the following files:
src/lib/controllib/BlockIntegralTrap.hpp
src/lib/controllib/BlockIntegralTrap.cpp