PX4 Firmware: PWMSim Class Reference
PWMSim Class Reference
#include <PWMSim.hpp>
Public Types
enum Mode { MODE_8PWM, MODE_16PWM, MODE_NONE }
Public Types inherited from device::Device
enum DeviceBusType { DeviceBusType_UNKNOWN = 0, DeviceBusType_I2C = 1, DeviceBusType_SPI = 2, DeviceBusType_UAVCAN = 3 }
Device bus types for DEVID.
Public Member Functions
PWMSim ()
virtual ~PWMSim ()
void run () override
int print_status () override
int ioctl (device::file_t *filp, int cmd, unsigned long arg) override
Perform an ioctl operation on the device.
int set_pwm_rate (unsigned rate)
int set_mode (Mode mode)
Mode get_mode ()
Public Member Functions inherited from device::CDev
CDev (const char *name, const char *devname)
Constructor.
virtual ~CDev ()
virtual int init ()
Initialise the driver and make it ready for use.
virtual int open (file_t *filep)
Handle an open of the device.
virtual int close (file_t *filep)
Handle a close of the device.
virtual ssize_t read (file_t *filep, char *buffer, size_t buflen)
Perform a read from the device.
virtual ssize_t write (file_t *filep, const char *buffer, size_t buflen)
Perform a write to the device.
virtual off_t seek (file_t *filep, off_t offset, int whence)
Perform a logical seek operation on the device.
virtual int poll (file_t *filep, px4_pollfd_struct_t *fds, bool setup)
Perform a poll setup/teardown operation.
Public Member Functions inherited from device::Device
virtual ~Device ()=default
Destructor.
virtual int read (unsigned address, void *data, unsigned count)
Read directly from the device.
virtual int write (unsigned address, void *data, unsigned count)
Write directly to the device.
virtual int ioctl (unsigned operation, unsigned &arg)
Perform a device-specific operation.
uint8_t get_device_bus ()
Return the bus ID the device is connected to.
DeviceBusType get_device_bus_type ()
Return the bus type the device is connected to.
uint8_t get_device_address ()
Return the bus address of the device.
void set_device_address (int address)
void set_device_type (uint8_t devtype)
Set the device type.
virtual bool external ()
Static Public Member Functions
static int task_spawn (int argc, char *argv[])
static PWMSim * instantiate (int argc, char *argv[])
static int custom_command (int argc, char *argv[])
static int print_usage (const char *reason=nullptr)
Private Member Functions
void subscribe ()
void update_params ()
Static Private Member Functions
static int control_callback (uintptr_t handle, uint8_t control_group, uint8_t control_index, float &input)
Private Attributes
Mode _mode {MODE_NONE}
int _update_rate {400}
int _current_update_rate {0}
int _control_subs [actuator_controls_s::NUM_ACTUATOR_CONTROL_GROUPS]
px4_pollfd_struct_t _poll_fds [actuator_controls_s::NUM_ACTUATOR_CONTROL_GROUPS] {}
unsigned _poll_fds_num {0}
int _armed_sub {-1}
actuator_outputs_s _actuator_outputs = {}
orb_advert_t _outputs_pub {nullptr}
unsigned _num_outputs {0}
unsigned _pwm_min [MAX_ACTUATORS] {}
unsigned _pwm_max [MAX_ACTUATORS] {}
uint32_t _groups_required {0}
uint32_t _groups_subscribed {0}
bool _armed {false}
bool _lockdown {false}
bool _failsafe {false}
MixerGroup * _mixers {nullptr}
actuator_controls_s _controls [actuator_controls_s::NUM_ACTUATOR_CONTROL_GROUPS] {}
orb_id_t _control_topics [actuator_controls_s::NUM_ACTUATOR_CONTROL_GROUPS] {}
bool _airmode {false}
multicopter air-mode
perf_counter_t _perf_control_latency
Static Private Attributes
static constexpr uint32_t PWM_SIM_DISARMED_MAGIC = 900
static constexpr uint32_t PWM_SIM_FAILSAFE_MAGIC = 600
static constexpr uint32_t PWM_SIM_PWM_MIN_MAGIC = 1000
static constexpr uint32_t PWM_SIM_PWM_MAX_MAGIC = 2000
static constexpr unsigned MAX_ACTUATORS = 16
Additional Inherited Members
Protected Member Functions inherited from device::CDev
virtual pollevent_t poll_state (file_t *filep)
Check the current state of the device for poll events from the perspective of the file.
virtual void poll_notify (pollevent_t events)
Report new poll events.
virtual void poll_notify_one (px4_pollfd_struct_t *fds, pollevent_t events)
Internal implementation of poll_notify.
virtual int open_first (file_t *filep)
Notification of the first open.
virtual int close_last (file_t *filep)
Notification of the last close.
virtual int register_class_devname (const char *class_devname)
Register a class device name, automatically adding device class instance suffix if need be.
virtual int unregister_class_devname (const char *class_devname, unsigned class_instance)
Register a class device name, automatically adding device class instance suffix if need be.
const char * get_devname ()
Get the device name.
void lock ()
Take the driver lock.
void unlock ()
Release the driver lock.
Protected Member Functions inherited from device::Device
Device (const char *name)
Device (DeviceBusType bus_type, uint8_t bus, uint8_t address, uint8_t devtype=0)
Device (const Device &)=delete
Device & operator= (const Device &)=delete
Device (Device &&)=delete
Device & operator= (Device &&)=delete
Protected Attributes inherited from device::CDev
px4_sem_t _lock
lock to protect access to all class members (also for derived classes)
bool _pub_blocked {false}
true if publishing should be blocked
Protected Attributes inherited from device::Device
union DeviceId _device_id
device identifier information
const char * _name
driver name
bool _debug_enabled {false}
if true, debug messages are printed
Static Protected Attributes inherited from device::CDev
static const px4_file_operations_t fops = {}
Pointer to the default cdev file operations table; useful for registering clone devices etc.
Detailed Description
Definition at line 54 of file PWMSim.hpp.
Member Enumeration Documentation
enum PWMSim::Mode
Enumerator
MODE_8PWM
MODE_16PWM
MODE_NONE
Definition at line 63 of file PWMSim.hpp.
Constructor & Destructor Documentation
PWMSim::PWMSim ()
Definition at line 36 of file PWMSim.cpp.
References _control_subs, _control_topics, _pwm_max, _pwm_min, lis3mdl::init(), MAX_ACTUATORS, MODE_16PWM, ORB_ID, PWM_SIM_PWM_MAX_MAGIC, PWM_SIM_PWM_MIN_MAGIC, and set_mode().
Referenced by instantiate().
PWMSim::~PWMSim () virtual
Definition at line 60 of file PWMSim.cpp.
References _perf_control_latency, and perf_free().
Member Function Documentation
int PWMSim::control_callback (uintptr_t handle, uint8_t control_group, uint8_t control_index, float & input) static private
Definition at line 345 of file PWMSim.cpp.
References actuator_controls_s::control.
Referenced by ioctl().
int PWMSim::custom_command (int argc, char * argv[]) static
See also
ModuleBase
Definition at line 608 of file PWMSim.cpp.
References get_mode(), is_running(), MODE_16PWM, MODE_8PWM, MODE_NONE, print_usage(), and task_spawn().
Mode PWMSim::get_mode () inline
Definition at line 96 of file PWMSim.hpp.
References _mode.
Referenced by custom_command().
PWMSim * PWMSim::instantiate (int argc, char * argv[]) static
See also
ModuleBase
Definition at line 603 of file PWMSim.cpp.
References PWMSim().
int PWMSim::ioctl (device::file_t * filep, int cmd, unsigned long arg) override virtual
Perform an ioctl operation on the device.
The default implementation handles DIOC_GETPRIV, and otherwise returns -ENOTTY. Subclasses should call the default implementation for any command they do not handle themselves.
Parameters
filep Pointer to the NuttX file structure.
cmd The ioctl command value.
arg The ioctl argument value.
Returns
OK on success, or -errno otherwise.
Reimplemented from device::CDev.
Definition at line 355 of file PWMSim.cpp.
References _actuator_outputs, _controls, _current_update_rate, _groups_required, _mixers, _mode, _num_outputs, _pwm_max, _pwm_min, MixerGroup::add_mixer(), pwm_output_values::channel_count, SimpleMixer::check(), control_callback(), MixerGroup::groups_required(), MixerGroup::load_from_buf(), device::CDev::lock(), MAX_ACTUATORS, uart_esc::mixer, MIXERIOCADDSIMPLE, MIXERIOCGETOUTPUTCOUNT, MIXERIOCLOADBUF, MIXERIOCRESET, MODE_16PWM, MODE_8PWM, OK, actuator_outputs_s::output, PWM_OUTPUT_MAX_CHANNELS, PWM_SERVO_ARM, PWM_SERVO_DISARM, PWM_SERVO_GET, PWM_SERVO_GET_COUNT, PWM_SERVO_GET_DEFAULT_UPDATE_RATE, PWM_SERVO_GET_DISARMED_PWM, PWM_SERVO_GET_FAILSAFE_PWM, PWM_SERVO_GET_MAX_PWM, PWM_SERVO_GET_MIN_PWM, PWM_SERVO_GET_RATEGROUP, PWM_SERVO_GET_SELECT_UPDATE_RATE, PWM_SERVO_GET_TRIM_PWM, PWM_SERVO_GET_UPDATE_RATE, PWM_SERVO_SET_MAX_PWM, PWM_SERVO_SET_MIN_PWM, PWM_SERVO_SET_SELECT_UPDATE_RATE, PWM_SERVO_SET_UPDATE_RATE, PWM_SIM_DISARMED_MAGIC, PWM_SIM_FAILSAFE_MAGIC, PWM_SIM_PWM_MAX_MAGIC, PWM_SIM_PWM_MIN_MAGIC, PX4_ERR, set_pwm_rate(), device::CDev::unlock(), and pwm_output_values::values.
int PWMSim::print_status () override
See also
ModuleBase::print_status()
Definition at line 678 of file PWMSim.cpp.
References _current_update_rate, _mode, _poll_fds_num, MODE_16PWM, MODE_8PWM, MODE_NONE, pwm_out_sim_main(), and PX4_INFO.
int PWMSim::print_usage (const char * reason = nullptr) static
See also
ModuleBase
Definition at line 646 of file PWMSim.cpp.
References PRINT_MODULE_DESCRIPTION(), PRINT_MODULE_USAGE_COMMAND_DESCR(), PRINT_MODULE_USAGE_DEFAULT_COMMANDS, PRINT_MODULE_USAGE_NAME(), PRINT_MODULE_USAGE_PARAM_COMMENT(), and PX4_WARN.
Referenced by custom_command().
void PWMSim::run () override
See also
ModuleBase::run()
Definition at line 157 of file PWMSim.cpp.
References _actuator_outputs, _airmode, _armed, _armed_sub, _control_subs, _control_topics, _controls, _current_update_rate, _failsafe, _groups_required, _groups_subscribed, _lockdown, _mixers, _num_outputs, _outputs_pub, _perf_control_latency, _poll_fds, _poll_fds_num, _pwm_max, _pwm_min, _update_rate, actuator_armed_s::armed, actuator_armed_s::force_failsafe, hrt_absolute_time(), hrt_abstime, actuator_armed_s::manual_lockdown, MixerGroup::mix(), actuator_outputs_s::noutputs, orb_advertise(), orb_check(), orb_copy(), ORB_ID, orb_publish(), orb_set_interval(), orb_subscribe(), orb_unsubscribe(), actuator_outputs_s::output, perf_set_elapsed(), PWM_SIM_DISARMED_MAGIC, PWM_SIM_FAILSAFE_MAGIC, PX4_DEBUG, PX4_ERR, PX4_OK, px4_poll(), MixerGroup::set_airmode(), subscribe(), actuator_outputs_s::timestamp, actuator_controls_s::timestamp_sample, and update_params().
int PWMSim::set_mode (Mode mode)
Definition at line 66 of file PWMSim.cpp.
References _mode, _num_outputs, _update_rate, MODE_16PWM, MODE_8PWM, MODE_NONE, OK, and PX4_INFO.
Referenced by PWMSim().
int PWMSim::set_pwm_rate (unsigned rate)
Definition at line 106 of file PWMSim.cpp.
References _update_rate, and OK.
Referenced by ioctl().
void PWMSim::subscribe () private
Definition at line 117 of file PWMSim.cpp.
References _control_subs, _control_topics, _groups_required, _groups_subscribed, _poll_fds, _poll_fds_num, orb_subscribe(), orb_unsubscribe(), and PX4_DEBUG.
Referenced by run().
int PWMSim::task_spawn (int argc, char * argv[]) static
See also
ModuleBase
Definition at line 580 of file PWMSim.cpp.
References PX4_OK, px4_task_spawn_cmd(), SCHED_DEFAULT, and SCHED_PRIORITY_ACTUATOR_OUTPUTS.
Referenced by custom_command().
void PWMSim::update_params () private
Definition at line 144 of file PWMSim.cpp.
References _airmode, param_find(), param_get(), param_handle(), and PARAM_INVALID.
Referenced by run().
Member Data Documentation
actuator_outputs_s PWMSim::_actuator_outputs = {} private
Definition at line 113 of file PWMSim.hpp.
Referenced by ioctl(), and run().
bool PWMSim::_airmode {false} private
multicopter air-mode
Definition at line 133 of file PWMSim.hpp.
Referenced by run(), and update_params().
bool PWMSim::_armed {false} private
Definition at line 124 of file PWMSim.hpp.
Referenced by run().
int PWMSim::_armed_sub {-1} private
Definition at line 111 of file PWMSim.hpp.
Referenced by run().
int PWMSim::_control_subs[actuator_controls_s::NUM_ACTUATOR_CONTROL_GROUPS] private
Definition at line 106 of file PWMSim.hpp.
Referenced by PWMSim(), run(), and subscribe().
orb_id_t PWMSim::_control_topics[actuator_controls_s::NUM_ACTUATOR_CONTROL_GROUPS] {} private
Definition at line 131 of file PWMSim.hpp.
Referenced by PWMSim(), run(), and subscribe().
actuator_controls_s PWMSim::_controls[actuator_controls_s::NUM_ACTUATOR_CONTROL_GROUPS] {} private
Definition at line 130 of file PWMSim.hpp.
Referenced by ioctl(), and run().
int PWMSim::_current_update_rate {0} private
Definition at line 104 of file PWMSim.hpp.
Referenced by ioctl(), print_status(), and run().
bool PWMSim::_failsafe {false} private
Definition at line 126 of file PWMSim.hpp.
Referenced by run().
uint32_t PWMSim::_groups_required {0} private
Definition at line 121 of file PWMSim.hpp.
Referenced by ioctl(), run(), and subscribe().
uint32_t PWMSim::_groups_subscribed {0} private
Definition at line 122 of file PWMSim.hpp.
Referenced by run(), and subscribe().
bool PWMSim::_lockdown {false} private
Definition at line 125 of file PWMSim.hpp.
Referenced by run().
MixerGroup* PWMSim::_mixers {nullptr} private
Definition at line 128 of file PWMSim.hpp.
Referenced by ioctl(), and run().
Mode PWMSim::_mode {MODE_NONE} private
Definition at line 101 of file PWMSim.hpp.
Referenced by get_mode(), ioctl(), print_status(), and set_mode().
unsigned PWMSim::_num_outputs {0} private
Definition at line 116 of file PWMSim.hpp.
Referenced by ioctl(), run(), and set_mode().
orb_advert_t PWMSim::_outputs_pub {nullptr} private
Definition at line 114 of file PWMSim.hpp.
Referenced by run().
perf_counter_t PWMSim::_perf_control_latency private
Definition at line 135 of file PWMSim.hpp.
Referenced by run(), and ~PWMSim().
px4_pollfd_struct_t PWMSim::_poll_fds[actuator_controls_s::NUM_ACTUATOR_CONTROL_GROUPS] {} private
Definition at line 108 of file PWMSim.hpp.
Referenced by run(), and subscribe().
unsigned PWMSim::_poll_fds_num {0} private
Definition at line 109 of file PWMSim.hpp.
Referenced by print_status(), run(), and subscribe().
unsigned PWMSim::_pwm_max[MAX_ACTUATORS] {} private
Definition at line 119 of file PWMSim.hpp.
Referenced by ioctl(), PWMSim(), and run().
unsigned PWMSim::_pwm_min[MAX_ACTUATORS] {} private
Definition at line 118 of file PWMSim.hpp.
Referenced by ioctl(), PWMSim(), and run().
int PWMSim::_update_rate {400} private
Definition at line 103 of file PWMSim.hpp.
Referenced by run(), set_mode(), and set_pwm_rate().
constexpr unsigned PWMSim::MAX_ACTUATORS = 16 static private
Definition at line 99 of file PWMSim.hpp.
Referenced by ioctl(), and PWMSim().
constexpr uint32_t PWMSim::PWM_SIM_DISARMED_MAGIC = 900 static private
Definition at line 56 of file PWMSim.hpp.
Referenced by ioctl(), and run().
constexpr uint32_t PWMSim::PWM_SIM_FAILSAFE_MAGIC = 600 static private
Definition at line 57 of file PWMSim.hpp.
Referenced by ioctl(), and run().
constexpr uint32_t PWMSim::PWM_SIM_PWM_MAX_MAGIC = 2000 static private
Definition at line 59 of file PWMSim.hpp.
Referenced by ioctl(), and PWMSim().
constexpr uint32_t PWMSim::PWM_SIM_PWM_MIN_MAGIC = 1000 static private
Definition at line 58 of file PWMSim.hpp.
Referenced by ioctl(), and PWMSim().
The documentation for this class was generated from the following files:
src/drivers/pwm_out_sim/PWMSim.hpp
src/drivers/pwm_out_sim/PWMSim.cpp