PX4 Firmware: hmc5883 Namespace Reference
hmc5883 Namespace Reference
Local functions in support of the shell command.
Classes
struct hmc5883_bus_option
Functions
void start (enum HMC5883_BUS busid, enum Rotation rotation)
Start the driver.
int stop ()
Stop the driver.
bool start_bus (struct hmc5883_bus_option &bus, enum Rotation rotation)
start driver for a specific bus option
struct hmc5883_bus_option & find_bus (enum HMC5883_BUS busid)
find a bus structure for a busid
void test (enum HMC5883_BUS busid)
Perform some basic functional tests on the driver; make sure we can collect data from the sensor in polled and automatic modes.
void reset (enum HMC5883_BUS busid)
Reset the driver.
int info (enum HMC5883_BUS busid)
Print a little info about the driver.
int calibrate (enum HMC5883_BUS busid)
Automatic scale calibration.
int temp_enable (enum HMC5883_BUS busid, bool enable)
enable/disable temperature compensation
void usage ()
Prints info about the driver argument usage.
Variables
struct hmc5883::hmc5883_bus_option bus_options []
Detailed Description
Local functions in support of the shell command.
Function Documentation
int hmc5883::calibrate (enum HMC5883_BUS busid)
Automatic scale calibration.
Basic idea:
output = (ext field +- 1.1 Ga self-test) * scale factor
and consequently:
1.1 Ga = (excited - normal) * scale factor scale factor = (excited - normal) / 1.1 Ga
sxy = (excited - normal) / 766 | for conf reg. B set to 0x60 / Gain = 3 sz = (excited - normal) / 713 | for conf reg. B set to 0x60 / Gain = 3
By subtracting the non-excited measurement the pure 1.1 Ga reading can be extracted and the sensitivity of all axes can be matched.
SELF TEST OPERATION To check the HMC5883L for proper operation, a self test feature in incorporated in which the sensor offset straps are excited to create a nominal field strength (bias field) to be measured. To implement self test, the least significant bits (MS1 and MS0) of configuration register A are changed from 00 to 01 (positive bias) or 10 (negetive bias), e.g. 0x11 or 0x12. Then, by placing the mode register into single-measurement mode (0x01), two data acquisition cycles will be made on each magnetic vector. The first acquisition will be a set pulse followed shortly by measurement data of the external field. The second acquisition will have the offset strap excited (about 10 mA) in the positive bias mode for X, Y, and Z axes to create about a ±1.1 gauss self test field plus the external field. The first acquisition values will be subtracted from the second acquisition, and the net measurement will be placed into the data output registers. Since self test adds ~1.1 Gauss additional field to the existing field strength, using a reduced gain setting prevents sensor from being saturated and data registers overflowed. For example, if the configuration register B is set to 0x60 (Gain=3), values around +766 LSB (1.16 Ga * 660 LSB/Ga) will be placed in the X and Y data output registers and around +713 (1.08 Ga * 660 LSB/Ga) will be placed in Z data output register. To leave the self test mode, change MS1 and MS0 bit of the configuration register A back to 00 (Normal Measurement Mode), e.g. 0x10. Using the self test method described above, the user can scale sensor
Definition at line 1657 of file hmc5883.cpp.
References device::CDev::close(), hmc5883::hmc5883_bus_option::devpath, err, fd, find_bus(), HMC5883::ioctl(), MAGIOCCALIBRATE, OK, device::CDev::open(), path, and warnx.
Referenced by hmc5883_main(), and lis3mdl_main().
struct hmc5883_bus_option & hmc5883::find_bus (enum HMC5883_BUS busid)
find a bus structure for a busid
Definition at line 1530 of file hmc5883.cpp.
References bus_options, errx, HMC5883_BUS_ALL, and NUM_BUS_OPTIONS.
Referenced by calibrate(), info(), reset(), temp_enable(), and test().
int hmc5883::info (enum HMC5883_BUS busid)
Print a little info about the driver.
Definition at line 1732 of file hmc5883.cpp.
References hmc5883::hmc5883_bus_option::busid, hmc5883::hmc5883_bus_option::dev, hmc5883::hmc5883_bus_option::devpath, find_bus(), HMC5883::print_info(), and warnx.
Referenced by hmc5883_main().
void hmc5883::reset (enum HMC5883_BUS busid)
Reset the driver.
Definition at line 1682 of file hmc5883.cpp.
References hmc5883::hmc5883_bus_option::devpath, err, fd, find_bus(), HMC5883::ioctl(), device::CDev::open(), path, SENSOR_POLLRATE_DEFAULT, SENSORIOCRESET, and SENSORIOCSPOLLRATE.
Referenced by hmc5883_main().
void hmc5883::start (enum HMC5883_BUS busid, enum Rotation rotation)
Start the driver.
This function call only returns once the driver is either successfully up and running or failed to start.
Definition at line 1487 of file hmc5883.cpp.
References bus_options, HMC5883_BUS_ALL, NUM_BUS_OPTIONS, and start_bus().
Referenced by hmc5883_main().
bool hmc5883::start_bus (struct hmc5883_bus_option & bus, enum Rotation rotation)
start driver for a specific bus option
Definition at line 1441 of file hmc5883.cpp.
References device::CDev::close(), hmc5883::hmc5883_bus_option::dev, errx, fd, HMC5883::HMC5883(), HMC5883::ioctl(), OK, device::CDev::open(), SENSOR_POLLRATE_DEFAULT, SENSORIOCSPOLLRATE, and warnx.
Referenced by start().
int hmc5883::stop ()
Stop the driver.
Stop the driver.
Definition at line 1511 of file hmc5883.cpp.
References bus_options, hmc5883::hmc5883_bus_option::dev, NUM_BUS_OPTIONS, and HMC5883::stop().
Referenced by hmc5883_main().
int hmc5883::temp_enable (HMC5883_BUS busid, bool enable)
enable/disable temperature compensation
Definition at line 1709 of file hmc5883.cpp.
References device::CDev::close(), hmc5883::hmc5883_bus_option::devpath, err, fd, find_bus(), HMC5883::ioctl(), MAGIOCSTEMPCOMP, device::CDev::open(), and path.
Referenced by hmc5883_main().
void hmc5883::test (enum HMC5883_BUS busid)
Perform some basic functional tests on the driver; make sure we can collect data from the sensor in polled and automatic modes.
Definition at line 1549 of file hmc5883.cpp.
References hmc5883::hmc5883_bus_option::devpath, err, errx, fd, find_bus(), HMC5883::ioctl(), mag_report, MAGIOCGEXTERNAL, OK, device::CDev::open(), path, device::CDev::poll(), HMC5883::read(), SENSORIOCSPOLLRATE, SENSORIOCSQUEUEDEPTH, and warnx.
Referenced by hmc5883_main().
void hmc5883::usage (void)
Prints info about the driver argument usage.
Prints info about the driver argument usage.
Definition at line 1742 of file hmc5883.cpp.
References warnx.
Referenced by hmc5883_main().
Variable Documentation
struct hmc5883::hmc5883_bus_option hmc5883::bus_options[]
Initial value:
= {
    { HMC5883_BUS_I2C_EXTERNAL, "/dev/hmc5883_ext", &HMC5883_I2C_interface, PX4_I2C_BUS_EXPANSION, NULL },
}
Referenced by find_bus(), start(), and stop().