PX4 Firmware: src/drivers/vmount/vmount.cpp File Reference
vmount.cpp File Reference
#include <stdlib.h>
#include <stdio.h>
#include <stdbool.h>
#include <string.h>
#include <sys/types.h>
#include <fcntl.h>
#include <unistd.h>
#include <systemlib/err.h>
#include <px4_defines.h>
#include <px4_tasks.h>
#include "input_mavlink.h"
#include "input_rc.h"
#include "input_test.h"
#include "output_rc.h"
#include "output_mavlink.h"
#include <uORB/uORB.h>
#include <uORB/topics/parameter_update.h>
#include <px4_config.h>
#include <px4_module.h>
Classes
struct ThreadData
struct Parameters
struct ParameterHandles
Functions
static void usage ()
static void update_params (ParameterHandles &param_handles, Parameters &params, bool &got_changes)
static bool get_params (ParameterHandles &param_handles, Parameters &params)
static int vmount_thread_main (int argc, char *argv[])
__EXPORT int vmount_main (int argc, char *argv[])
The main command function.
Variables
static volatile bool thread_should_exit = false
static volatile bool thread_running = false
static constexpr int input_objs_len_max = 3
static volatile ThreadData * g_thread_data = nullptr
Detailed Description
Author
Leon Müller (thedevleon)
Beat Küng beat-.nosp@m.kuen.nosp@m.g@gmx.nosp@m..net
Julian Oes julia.nosp@m.n@oe.nosp@m.s.ch
Matthew Edwards (mje-nz)
Driver for to control mounts such as gimbals or servos. Inputs for the mounts can RC and/or mavlink commands. Outputs to the mounts can be RC (PWM) output or mavlink.
Definition in file vmount.cpp.
Function Documentation
bool get_params (ParameterHandles & param_handles, Parameters & params) static
Definition at line 566 of file vmount.cpp.
References ParameterHandles::mnt_do_stab, ParameterHandles::mnt_man_pitch, ParameterHandles::mnt_man_roll, ParameterHandles::mnt_man_yaw, ParameterHandles::mnt_mav_compid, ParameterHandles::mnt_mav_sysid, ParameterHandles::mnt_mode_in, ParameterHandles::mnt_mode_out, ParameterHandles::mnt_ob_lock_mode, ParameterHandles::mnt_ob_norm_mode, ParameterHandles::mnt_off_pitch, ParameterHandles::mnt_off_roll, ParameterHandles::mnt_off_yaw, ParameterHandles::mnt_range_pitch, ParameterHandles::mnt_range_roll, ParameterHandles::mnt_range_yaw, param_find(), PARAM_INVALID, and update_params().
Referenced by vmount_thread_main().
void update_params (ParameterHandles & param_handles, Parameters & params, bool & got_changes) static
Definition at line 543 of file vmount.cpp.
References Parameters::mnt_do_stab, ParameterHandles::mnt_do_stab, Parameters::mnt_man_pitch, ParameterHandles::mnt_man_pitch, Parameters::mnt_man_roll, ParameterHandles::mnt_man_roll, Parameters::mnt_man_yaw, ParameterHandles::mnt_man_yaw, Parameters::mnt_mav_compid, ParameterHandles::mnt_mav_compid, Parameters::mnt_mav_sysid, ParameterHandles::mnt_mav_sysid, Parameters::mnt_mode_in, ParameterHandles::mnt_mode_in, Parameters::mnt_mode_out, ParameterHandles::mnt_mode_out, Parameters::mnt_ob_lock_mode, ParameterHandles::mnt_ob_lock_mode, Parameters::mnt_ob_norm_mode, ParameterHandles::mnt_ob_norm_mode, Parameters::mnt_off_pitch, ParameterHandles::mnt_off_pitch, Parameters::mnt_off_roll, ParameterHandles::mnt_off_roll, Parameters::mnt_off_yaw, ParameterHandles::mnt_off_yaw, Parameters::mnt_range_pitch, ParameterHandles::mnt_range_pitch, Parameters::mnt_range_roll, ParameterHandles::mnt_range_roll, Parameters::mnt_range_yaw, ParameterHandles::mnt_range_yaw, and param_get().
Referenced by get_params(), and vmount_thread_main().
static void usage (void) static
Definition at line 155 of file vmount.cpp.
References PRINT_MODULE_DESCRIPTION(), PRINT_MODULE_USAGE_ARG(), PRINT_MODULE_USAGE_COMMAND, PRINT_MODULE_USAGE_COMMAND_DESCR(), PRINT_MODULE_USAGE_DEFAULT_COMMANDS, and PRINT_MODULE_USAGE_NAME().
Referenced by vmount_main(), and vmount_thread_main().
int vmount_main (int argc, char * argv[])
The main command function.
Processes command line arguments and starts the daemon.
Definition at line 454 of file vmount.cpp.
References counter, ThreadData::input_objs, ThreadData::input_objs_len, ThreadData::output_obj, vmount::InputBase::print_status(), vmount::OutputBase::print_status(), PX4_ERR, PX4_INFO, px4_task_spawn_cmd(), PX4_WARN, SCHED_DEFAULT, thread_running, thread_should_exit, usage(), usleep(), and vmount_thread_main().
static int vmount_thread_main (int argc, char * argv[]) static
Definition at line 183 of file vmount.cpp.
References vmount::InputTest::finished(), get_params(), vmount::OutputConfig::gimbal_normal_mode_value, vmount::OutputConfig::gimbal_retracted_mode_value, vmount::OutputBase::initialize(), ThreadData::input_objs, ThreadData::input_objs_len, input_objs_len_max, vmount::OutputConfig::mavlink_comp_id, vmount::OutputConfig::mavlink_sys_id, Parameters::mnt_do_stab, Parameters::mnt_man_pitch, Parameters::mnt_man_roll, Parameters::mnt_man_yaw, Parameters::mnt_mav_compid, Parameters::mnt_mav_sysid, Parameters::mnt_mode_in, Parameters::mnt_mode_out, Parameters::mnt_ob_lock_mode, Parameters::mnt_ob_norm_mode, Parameters::mnt_off_pitch, Parameters::mnt_off_roll, Parameters::mnt_off_yaw, Parameters::mnt_range_pitch, Parameters::mnt_range_roll, Parameters::mnt_range_yaw, orb_check(), orb_copy(), ORB_ID, orb_subscribe(), orb_unsubscribe(), ThreadData::output_obj, vmount::OutputConfig::pitch_offset, vmount::OutputConfig::pitch_scale, vmount::OutputBase::publish(), PX4_ERR, PX4_INFO, vmount::OutputConfig::roll_offset, vmount::OutputConfig::roll_scale, thread_running, thread_should_exit, vmount::InputBase::update(), vmount::OutputBase::update(), update_params(), usage(), usleep(), vmount::OutputConfig::yaw_offset, and vmount::OutputConfig::yaw_scale.
Referenced by vmount_main().
Variable Documentation
volatile ThreadData* g_thread_data = nullptr static
Definition at line 82 of file vmount.cpp.
constexpr int input_objs_len_max = 3 static
Definition at line 75 of file vmount.cpp.
Referenced by vmount_thread_main().
volatile bool thread_running = false static
Definition at line 73 of file vmount.cpp.
Referenced by vmount_main(), and vmount_thread_main().
volatile bool thread_should_exit = false static
Definition at line 72 of file vmount.cpp.
Referenced by vmount_main(), and vmount_thread_main().