PX4 Firmware: MPU9250 Class Reference
MPU9250 Class Reference
#include <mpu9250.h>
Public Member Functions
MPU9250 (device::Device *interface, device::Device *mag_interface, const char *path_accel, const char *path_gyro, const char *path_mag, enum Rotation rotation)
virtual ~MPU9250 ()
virtual int init ()
Initialise the driver and make it ready for use.
virtual ssize_t read (struct file *filp, char *buffer, size_t buflen)
virtual int ioctl (struct file *filp, int cmd, unsigned long arg)
void print_info ()
Diagnostics - print some basic information about the driver.
void print_registers ()
void test_error ()
Public Member Functions inherited from device::CDev
CDev (const char *name, const char *devname)
Constructor.
virtual ~CDev ()
virtual int open (file_t *filep)
Handle an open of the device.
virtual int close (file_t *filep)
Handle a close of the device.
virtual ssize_t read (file_t *filep, char *buffer, size_t buflen)
Perform a read from the device.
virtual ssize_t write (file_t *filep, const char *buffer, size_t buflen)
Perform a write to the device.
virtual off_t seek (file_t *filep, off_t offset, int whence)
Perform a logical seek operation on the device.
virtual int ioctl (file_t *filep, int cmd, unsigned long arg)
Perform an ioctl operation on the device.
virtual int poll (file_t *filep, px4_pollfd_struct_t *fds, bool setup)
Perform a poll setup/teardown operation.
Public Member Functions inherited from device::Device
virtual ~Device ()=default
Destructor.
virtual int read (unsigned address, void *data, unsigned count)
Read directly from the device.
virtual int write (unsigned address, void *data, unsigned count)
Write directly to the device.
virtual int ioctl (unsigned operation, unsigned &arg)
Perform a device-specific operation.
uint8_t get_device_bus ()
Return the bus ID the device is connected to.
DeviceBusType get_device_bus_type ()
Return the bus type the device is connected to.
uint8_t get_device_address ()
Return the bus address of the device.
void set_device_address (int address)
void set_device_type (uint8_t devtype)
Set the device type.
virtual bool external ()
Protected Member Functions
virtual int probe ()
virtual ssize_t gyro_read (struct file *filp, char *buffer, size_t buflen)
virtual int gyro_ioctl (struct file *filp, int cmd, unsigned long arg)
Protected Member Functions inherited from device::CDev
virtual pollevent_t poll_state (file_t *filep)
Check the current state of the device for poll events from the perspective of the file.
virtual void poll_notify (pollevent_t events)
Report new poll events.
virtual void poll_notify_one (px4_pollfd_struct_t *fds, pollevent_t events)
Internal implementation of poll_notify.
virtual int open_first (file_t *filep)
Notification of the first open.
virtual int close_last (file_t *filep)
Notification of the last close.
virtual int register_class_devname (const char *class_devname)
Register a class device name, automatically adding device class instance suffix if need be.
virtual int unregister_class_devname (const char *class_devname, unsigned class_instance)
Register a class device name, automatically adding device class instance suffix if need be.
const char * get_devname ()
Get the device name.
void lock ()
Take the driver lock.
void unlock ()
Release the driver lock.
Protected Member Functions inherited from device::Device
Device (const char *name)
Device (DeviceBusType bus_type, uint8_t bus, uint8_t address, uint8_t devtype=0)
Device (const Device &)=delete
Device & operator= (const Device &)=delete
Device (Device &&)=delete
Device & operator= (Device &&)=delete
Protected Attributes
Device * _interface
Protected Attributes inherited from device::CDev
px4_sem_t _lock
lock to protect access to all class members (also for derived classes)
bool _pub_blocked {false}
true if publishing should be blocked
Protected Attributes inherited from device::Device
union DeviceId _device_id
device identifier information
const char * _name
driver name
bool _debug_enabled {false}
if true, debug messages are printed
Private Member Functions
bool check_null_data (uint32_t *data, uint8_t size)
bool check_duplicate (uint8_t *accel_data)
void start ()
Start automatic measurement.
void stop ()
Stop automatic measurement.
int reset ()
Reset chip.
int reset_mpu ()
Resets the main chip (excluding the magnetometer if any).
bool is_i2c (void)
void measure ()
Fetch measurements from the sensor and update the report buffers.
uint8_t read_reg (unsigned reg, uint32_t speed=MPU9250_LOW_BUS_SPEED)
Read a register from the mpu.
uint16_t read_reg16 (unsigned reg)
void write_reg (unsigned reg, uint8_t value)
Write a register in the mpu.
void modify_reg (unsigned reg, uint8_t clearbits, uint8_t setbits)
Modify a register in the mpu.
void write_checked_reg (unsigned reg, uint8_t value)
Write a register in the mpu, updating _checked_values.
void modify_checked_reg (unsigned reg, uint8_t clearbits, uint8_t setbits)
Modify a checked register in the mpu.
int set_accel_range (unsigned max_g)
Set the mpu measurement range.
uint16_t swap16 (uint16_t val)
Swap a 16-bit value read from the mpu to native byte order.
bool is_external ()
Get the internal / external state.
int self_test ()
Measurement self test.
void _set_dlpf_filter (uint16_t frequency_hz)
void _set_sample_rate (unsigned desired_sample_rate_hz)
void check_registers (void)
MPU9250 (const MPU9250 &)
MPU9250 operator= (const MPU9250 &)
Static Private Member Functions
static void measure_trampoline (void *arg)
Static trampoline from the hrt_call context; because we don't have a generic hrt wrapper yet.
Private Attributes
MPU9250_gyro * _gyro
MPU9250_mag * _mag
uint8_t _whoami
bool _use_hrt
whoami result
struct hrt_call _call
unsigned _call_interval
ringbuffer::RingBuffer * _accel_reports
struct accel_calibration_s _accel_scale
float _accel_range_scale
float _accel_range_m_s2
orb_advert_t _accel_topic
int _accel_orb_class_instance
int _accel_class_instance
ringbuffer::RingBuffer * _gyro_reports
struct gyro_calibration_s _gyro_scale
float _gyro_range_scale
float _gyro_range_rad_s
unsigned _dlpf_freq
unsigned _sample_rate
perf_counter_t _accel_reads
perf_counter_t _gyro_reads
perf_counter_t _sample_perf
perf_counter_t _bad_transfers
perf_counter_t _bad_registers
perf_counter_t _good_transfers
perf_counter_t _reset_retries
perf_counter_t _duplicates
uint8_t _register_wait
uint64_t _reset_wait
math::LowPassFilter2p _accel_filter_x
math::LowPassFilter2p _accel_filter_y
math::LowPassFilter2p _accel_filter_z
math::LowPassFilter2p _gyro_filter_x
math::LowPassFilter2p _gyro_filter_y
math::LowPassFilter2p _gyro_filter_z
Integrator _accel_int
Integrator _gyro_int
enum Rotation _rotation
uint8_t _checked_values [MPU9250_NUM_CHECKED_REGISTERS]
uint8_t _checked_bad [MPU9250_NUM_CHECKED_REGISTERS]
uint8_t _checked_next
float _last_temperature
uint8_t _last_accel_data [6]
bool _got_duplicate
Static Private Attributes
static const uint8_t _checked_registers [MPU9250_NUM_CHECKED_REGISTERS]
Friends
class MPU9250_mag
class MPU9250_gyro
Additional Inherited Members
Public Types inherited from device::Device
enum DeviceBusType { DeviceBusType_UNKNOWN = 0, DeviceBusType_I2C = 1, DeviceBusType_SPI = 2, DeviceBusType_UAVCAN = 3 }
Device bus types for DEVID.
Static Protected Attributes inherited from device::CDev
static const px4_file_operations_t fops = {}
Pointer to the default cdev file operations table; useful for registering clone devices etc.
Detailed Description
Definition at line 243 of file mpu9250.h.
Constructor & Destructor Documentation
MPU9250::MPU9250 (device::Device * interface, device::Device * mag_interface, const char * path_accel, const char * path_gyro, const char * path_mag, enum Rotation rotation)
Definition at line 113 of file mpu9250.cpp.
References _accel_class_instance, _accel_filter_x, _accel_filter_y, _accel_filter_z, _accel_int, _accel_orb_class_instance, _accel_range_m_s2, _accel_range_scale, _accel_reads, _accel_reports, _accel_scale, _accel_topic, _bad_registers, _bad_transfers, _call, _call_interval, _checked_next, device::Device::_debug_enabled, device::Device::_device_id, _dlpf_freq, _duplicates, _good_transfers, _got_duplicate, _gyro, _gyro_filter_x, _gyro_filter_y, _gyro_filter_z, _gyro_int, _gyro_range_rad_s, _gyro_range_scale, _gyro_reads, _gyro_reports, _gyro_scale, _interface, _last_accel_data, _last_temperature, _mag, _register_wait, _reset_retries, _reset_wait, _rotation, _sample_perf, _sample_rate, _use_hrt, device::Device::DeviceStructure::address, device::Device::DeviceStructure::bus, device::Device::DeviceStructure::bus_type, device::Device::DeviceId::devid, device::Device::DeviceId::devid_s, device::Device::DeviceStructure::devtype, DRV_ACC_DEVTYPE_MPU9250, DRV_GYR_DEVTYPE_MPU9250, DRV_MAG_DEVTYPE_MPU9250, f(), MPU9250_ACCEL_DEFAULT_DRIVER_FILTER_FREQ, MPU9250_ACCEL_DEFAULT_RATE, MPU9250_ACCEL_MAX_OUTPUT_RATE, MPU9250_DEFAULT_ONCHIP_FILTER_FREQ, MPU9250_GYRO_DEFAULT_DRIVER_FILTER_FREQ, MPU9250_GYRO_DEFAULT_RATE, MPU9250_GYRO_MAX_OUTPUT_RATE, PC_COUNT, PC_ELAPSED, perf_alloc, accel_calibration_s::x_offset, gyro_calibration_s::x_offset, gyro_calibration_s::x_scale, accel_calibration_s::x_scale, gyro_calibration_s::y_offset, accel_calibration_s::y_offset, accel_calibration_s::y_scale, gyro_calibration_s::y_scale, gyro_calibration_s::z_offset, accel_calibration_s::z_offset, accel_calibration_s::z_scale, and gyro_calibration_s::z_scale.
MPU9250::~MPU9250 () virtual
Definition at line 215 of file mpu9250.cpp.
References _accel_class_instance, _accel_reads, _accel_reports, _accel_topic, _bad_registers, _bad_transfers, _duplicates, _good_transfers, _gyro, _gyro_reads, _gyro_reports, MPU9250_gyro::_gyro_topic, _mag, _reset_retries, _sample_perf, ACCEL_BASE_DEVICE_PATH, orb_unadvertise(), perf_free(), stop(), and device::CDev::unregister_class_devname().
MPU9250::MPU9250 (const MPU9250 &) private
Member Function Documentation
void MPU9250::_set_dlpf_filter (uint16_t frequency_hz) private
Definition at line 579 of file mpu9250.cpp.
References _dlpf_freq, BITS_DLPF_CFG_10HZ, BITS_DLPF_CFG_184HZ, BITS_DLPF_CFG_20HZ, BITS_DLPF_CFG_250HZ, BITS_DLPF_CFG_3600HZ, BITS_DLPF_CFG_41HZ, BITS_DLPF_CFG_5HZ, BITS_DLPF_CFG_92HZ, MPUREG_CONFIG, and write_checked_reg().
Referenced by reset_mpu().
void MPU9250::_set_sample_rate (unsigned desired_sample_rate_hz) private
Definition at line 557 of file mpu9250.cpp.
References _sample_rate, ACCEL_SAMPLERATE_DEFAULT, GYRO_SAMPLERATE_DEFAULT, MPU9250_GYRO_DEFAULT_RATE, MPUREG_SMPLRT_DIV, and write_checked_reg().
Referenced by gyro_ioctl(), ioctl(), and reset_mpu().
bool MPU9250::check_duplicate (uint8_t * accel_data) private
Definition at line 1198 of file mpu9250.cpp.
References _duplicates, _got_duplicate, _last_accel_data, _sample_perf, perf_count(), and perf_end().
Referenced by measure().
bool MPU9250::check_null_data (uint32_t * data, uint8_t size) private
Definition at line 1179 of file mpu9250.cpp.
References _bad_transfers, _good_transfers, _sample_perf, perf_count(), and perf_end().
Referenced by measure().
void MPU9250::check_registers (void) private
Definition at line 1121 of file mpu9250.cpp.
References _bad_registers, _checked_bad, _checked_next, _checked_registers, _checked_values, _register_wait, _reset_wait, BIT_H_RESET, hrt_absolute_time(), MPU9250_HIGH_BUS_SPEED, MPU9250_NUM_CHECKED_REGISTERS, MPU_CLK_SEL_AUTO, MPUREG_PWR_MGMT_1, MPUREG_PWR_MGMT_2, perf_count(), read_reg(), and write_reg().
Referenced by measure().
int MPU9250::gyro_ioctl (struct file * filp, int cmd, unsigned long arg) protected virtual
Definition at line 876 of file mpu9250.cpp.
References _gyro_range_rad_s, _gyro_reports, _gyro_scale, _sample_rate, _set_sample_rate(), GYROIOCGRANGE, GYROIOCGSAMPLERATE, GYROIOCGSCALE, GYROIOCSRANGE, GYROIOCSSAMPLERATE, GYROIOCSSCALE, ioctl(), M_PI_F, OK, SENSORIOCGPOLLRATE, SENSORIOCRESET, SENSORIOCSPOLLRATE, and SENSORIOCSQUEUEDEPTH.
Referenced by MPU9250_gyro::ioctl().
ssize_t MPU9250::gyro_read (struct file * filp, char * buffer, size_t buflen) protected virtual
Definition at line 693 of file mpu9250.cpp.
References _call_interval, _gyro_reads, _gyro_reports, gyro_report, measure(), and perf_count().
Referenced by MPU9250_gyro::read().
int MPU9250::init () virtual
Initialise the driver and make it ready for use.
Returns
OK if the driver initialized OK, negative errno otherwise;
Reimplemented from device::CDev.
Definition at line 254 of file mpu9250.cpp.
References _accel_class_instance, _accel_filter_x, _accel_filter_y, _accel_filter_z, _accel_int, _accel_orb_class_instance, _accel_reports, _accel_scale, _accel_topic, _gyro, _gyro_filter_x, _gyro_filter_y, _gyro_filter_z, _gyro_int, MPU9250_gyro::_gyro_orb_class_instance, _gyro_reports, _gyro_scale, MPU9250_gyro::_gyro_topic, MPU9250_mag::_interface, _interface, _mag, _sample_rate, _whoami, ACCEL_BASE_DEVICE_PATH, accel_report, MPU9250_mag::ak8963_reset(), DEVICE_DEBUG, gyro_report, MPU9250_gyro::init(), lis3mdl::init(), MPU9250_mag::init(), is_external(), is_i2c(), MPU9250_mag::is_passthrough(), measure(), MPU9250_ACCEL_DEFAULT_DRIVER_FILTER_FREQ, MPU9250_ACCEL_DEFAULT_RATE, MPU9250_GYRO_DEFAULT_DRIVER_FILTER_FREQ, MPU9250_GYRO_DEFAULT_RATE, MPU_WHOAMI_9250, MPUIOCGIS_I2C, OK, orb_advertise_multi(), ORB_ID, ORB_PRIO_HIGH, ORB_PRIO_MAX, param_find(), param_get(), PARAM_INVALID, probe(), PX4_ERR, PX4_INFO, PX4_OK, device::CDev::register_class_devname(), reset_mpu(), Integrator::set_autoreset_interval(), math::LowPassFilter2p::set_cutoff_frequency(), accel_calibration_s::x_offset, gyro_calibration_s::x_offset, accel_calibration_s::x_scale, gyro_calibration_s::x_scale, gyro_calibration_s::y_offset, accel_calibration_s::y_offset, accel_calibration_s::y_scale, gyro_calibration_s::y_scale, gyro_calibration_s::z_offset, accel_calibration_s::z_offset, accel_calibration_s::z_scale, and gyro_calibration_s::z_scale.
Referenced by DfMpu9250Wrapper::start().
int MPU9250::ioctl (struct file * filp, int cmd, unsigned long arg) virtual
Definition at line 733 of file mpu9250.cpp.
References _accel_filter_x, _accel_filter_y, _accel_filter_z, _accel_range_m_s2, _accel_reports, _accel_scale, _call, _call_interval, _gyro_filter_x, _gyro_filter_y, _gyro_filter_z, _sample_rate, _set_sample_rate(), ACCELIOCGRANGE, ACCELIOCGSAMPLERATE, ACCELIOCGSCALE, ACCELIOCSRANGE, ACCELIOCSSAMPLERATE, ACCELIOCSSCALE, CONSTANTS_ONE_G, f(), math::LowPassFilter2p::get_cutoff_freq(), MPU9250_ACCEL_DEFAULT_RATE, MPU9250_TIMER_REDUCTION, OK, hrt_call::period, reset(), SENSOR_POLLRATE_DEFAULT, SENSOR_POLLRATE_EXTERNAL, SENSOR_POLLRATE_MANUAL, SENSOR_POLLRATE_MAX, SENSORIOCGPOLLRATE, SENSORIOCRESET, SENSORIOCSPOLLRATE, SENSORIOCSQUEUEDEPTH, set_accel_range(), math::LowPassFilter2p::set_cutoff_frequency(), start(), stop(), accel_calibration_s::x_scale, accel_calibration_s::y_scale, and accel_calibration_s::z_scale.
Referenced by gyro_ioctl().
bool MPU9250::is_external () inline private
Get the internal / external state.
Returns
true if the sensor is not on the main MCU board
Definition at line 493 of file mpu9250.h.
References ACCELIOCGEXTERNAL.
Referenced by init().
bool MPU9250::is_i2c (void) inline private
Definition at line 407 of file mpu9250.h.
References MPU9250_LOW_BUS_SPEED.
Referenced by init(), and reset_mpu().
void MPU9250::measure () private
Fetch measurements from the sensor and update the report buffers.
Definition at line 1223 of file mpu9250.cpp.
References _accel_filter_x, _accel_filter_y, _accel_filter_z, _accel_int, _accel_range_scale, _accel_reports, _accel_scale, _accel_topic, _bad_registers, _bad_transfers, device::Device::_device_id, _gyro, _gyro_filter_x, _gyro_filter_y, _gyro_filter_z, _gyro_int, _gyro_range_scale, _gyro_reports, _gyro_scale, MPU9250_gyro::_gyro_topic, _interface, _last_temperature, _mag, MPU9250_mag::_measure(), device::CDev::_pub_blocked, _register_wait, _reset_wait, _rotation, _sample_perf, accel_report, MPUReport::accel_x, MPUReport::accel_y, MPUReport::accel_z, math::LowPassFilter2p::apply(), check_duplicate(), check_null_data(), check_registers(), device::Device::DeviceId::devid, f(), gyro_report, MPUReport::gyro_x, MPUReport::gyro_y, MPUReport::gyro_z, hrt_absolute_time(), int16_t_from_bytes(), MPU9250_mag::is_passthrough(), MPUReport::mag, MPU9250_mag::measure(), MPU9250_HIGH_BUS_SPEED, MPU9250_SET_SPEED, MPUREG_INT_STATUS, OK, ORB_ID, orb_publish(), MPU9250_gyro::parent_poll_notify(), perf_begin(), perf_end(), perf_event_count(), device::CDev::poll_notify(), Integrator::put(), rotate_3f(), MPUReport::temp, gyro_calibration_s::x_offset, accel_calibration_s::x_offset, gyro_calibration_s::x_scale, accel_calibration_s::x_scale, gyro_calibration_s::y_offset, accel_calibration_s::y_offset, accel_calibration_s::y_scale, gyro_calibration_s::y_scale, accel_calibration_s::z_offset, gyro_calibration_s::z_offset, gyro_calibration_s::z_scale, and accel_calibration_s::z_scale.
Referenced by gyro_read(), init(), measure_trampoline(), MPU9250_mag::read(), read(), self_test(), and stop().
void MPU9250::measure_trampoline (void * arg) static private
Static trampoline from the hrt_call context; because we don't have a generic hrt wrapper yet.
Called by the HRT in interrupt context at the specified rate if automatic polling is enabled.
Parameters
arg Instance pointer for the driver that is polling.
Definition at line 1112 of file mpu9250.cpp.
References measure().
Referenced by start().
void MPU9250::modify_checked_reg (unsigned reg, uint8_t clearbits, uint8_t setbits) private
Modify a checked register in the mpu.
Bits are cleared before bits are set.
Parameters
reg The register to modify.
clearbits Bits in the register to clear.
setbits Bits in the register to set.
Definition at line 976 of file mpu9250.cpp.
References read_reg(), and write_checked_reg().
Referenced by MPU9250_mag::ak8963_setup(), and MPU9250_mag::ak8963_setup_master_i2c().
void MPU9250::modify_reg (unsigned reg, uint8_t clearbits, uint8_t setbits) private
Modify a register in the mpu.
Bits are cleared before bits are set.
Parameters
reg The register to modify.
clearbits Bits in the register to clear.
setbits Bits in the register to set.
Definition at line 965 of file mpu9250.cpp.
References read_reg(), and write_reg().
Referenced by MPU9250_mag::ak8963_setup().
MPU9250 MPU9250::operator= (const MPU9250 &) private
void MPU9250::print_info ()
Diagnostics - print some basic information about the driver.
Definition at line 1444 of file mpu9250.cpp.
References _accel_filter_x, _accel_reads, _accel_reports, _bad_registers, _bad_transfers, _checked_bad, _checked_next, _checked_registers, _checked_values, _duplicates, _good_transfers, _gyro_filter_x, _gyro_reads, _gyro_reports, _last_temperature, _mag, MPU9250_mag::_mag_reports, _reset_retries, _sample_perf, math::LowPassFilter2p::get_cutoff_freq(), MPU9250_HIGH_BUS_SPEED, MPU9250_NUM_CHECKED_REGISTERS, perf_print_counter(), and read_reg().
Referenced by mpu9250::info().
void MPU9250::print_registers ()
Definition at line 1485 of file mpu9250.cpp.
References read_reg().
Referenced by mpu9250::regdump(), and test_error().
int MPU9250::probe () protected virtual
Definition at line 533 of file mpu9250.cpp.
References _checked_bad, _checked_values, _whoami, DEVICE_DEBUG, MPU_WHOAMI_6500, MPU_WHOAMI_9250, MPUREG_WHOAMI, OK, and read_reg().
Referenced by init().
ssize_t MPU9250::read (struct file * filp, char * buffer, size_t buflen) virtual
Definition at line 627 of file mpu9250.cpp.
References _accel_reads, _accel_reports, _call_interval, accel_report, measure(), and perf_count().
uint8_t MPU9250::read_reg (unsigned reg, uint32_t speed = MPU9250_LOW_BUS_SPEED) private
Read a register from the mpu.
Parameters
The register to read.
Returns
The value that was read.
Definition at line 938 of file mpu9250.cpp.
References _interface, and MPU9250_SET_SPEED.
Referenced by check_registers(), modify_checked_reg(), modify_reg(), print_info(), print_registers(), probe(), and reset_mpu().
uint16_t MPU9250::read_reg16 (unsigned reg) private
Definition at line 946 of file mpu9250.cpp.
References _interface, arraySize, and MPU9250_LOW_SPEED_OP.
int MPU9250::reset () private
Reset chip.
Resets the chip and measurements ranges, but not scale and offset.
Definition at line 424 of file mpu9250.cpp.
References _mag, _reset_wait, _whoami, MPU9250_mag::ak8963_reset(), hrt_absolute_time(), MPU_WHOAMI_9250, OK, reset_mpu(), state, and usleep().
Referenced by ioctl().
int MPU9250::reset_mpu () private
Resets the main chip (excluding the magnetometer if any).
Definition at line 458 of file mpu9250.cpp.
References _checked_registers, _checked_values, _gyro_range_rad_s, _gyro_range_scale, _mag, _sample_rate, _set_dlpf_filter(), _set_sample_rate(), ACCEL_RANGE_G, BIT_H_RESET, BIT_I2C_IF_DIS, BIT_INT_ANYRD_2CLEAR, BIT_INT_BYPASS_EN, BIT_RAW_RDY_EN, BITS_ACCEL_CONFIG2_41HZ, BITS_FS_2000DPS, is_i2c(), MPU9250_mag::is_passthrough(), M_PI_F, MPU9250_DEFAULT_ONCHIP_FILTER_FREQ, MPU9250_NUM_CHECKED_REGISTERS, MPU_CLK_SEL_AUTO, MPUREG_ACCEL_CONFIG2, MPUREG_GYRO_CONFIG, MPUREG_INT_ENABLE, MPUREG_INT_PIN_CFG, MPUREG_PWR_MGMT_1, MPUREG_PWR_MGMT_2, MPUREG_USER_CTRL, OK, PX4_ERR, read_reg(), set_accel_range(), usleep(), write_checked_reg(), and write_reg().
Referenced by init(), and reset().
int MPU9250::self_test (void) private
Measurement self test.
Returns
0 on success, 1 on failure
Definition at line 667 of file mpu9250.cpp.
References _sample_perf, measure(), and perf_event_count().
Referenced by MPU9250_mag::is_passthrough().
int MPU9250::set_accel_range (unsigned max_g) private
Set the mpu measurement range.
Parameters
max_g The maximum G value the range must support.
Returns
OK if the value can be supported, -ERANGE otherwise.
Definition at line 1001 of file mpu9250.cpp.
References _accel_range_m_s2, _accel_range_scale, CONSTANTS_ONE_G, MPUREG_ACCEL_CONFIG, OK, and write_checked_reg().
Referenced by ioctl(), and reset_mpu().
void MPU9250::start () private
Start automatic measurement.
Definition at line 1036 of file mpu9250.cpp.
References _accel_reports, _call, _call_interval, _gyro_reports, _mag, MPU9250_mag::_mag_reports, _use_hrt, hrt_call_every(), measure_trampoline(), MPU9250_TIMER_REDUCTION, and stop().
Referenced by ioctl(), and DfMpu9250Wrapper::start().
void MPU9250::stop () private
Stop automatic measurement.
Definition at line 1063 of file mpu9250.cpp.
References _call, _call_interval, _use_hrt, hrt_cancel(), measure(), and MPU9250_TIMER_REDUCTION.
Referenced by ioctl(), start(), DfMpu9250Wrapper::stop(), and ~MPU9250().
uint16_t MPU9250::swap16 (uint16_t val) inline private
Swap a 16-bit value read from the mpu to native byte order.
Definition at line 486 of file mpu9250.h.
void MPU9250::test_error ()
Definition at line 681 of file mpu9250.cpp.
References _interface, data, MPU9250_LOW_BUS_SPEED, MPU9250_SET_SPEED, MPUREG_INT_STATUS, and print_registers().
Referenced by mpu9250::testerror().
void MPU9250::write_checked_reg (unsigned reg, uint8_t value) private
Write a register in the mpu, updating _checked_values.
Parameters
reg The register to write.
value The new value to write.
Definition at line 987 of file mpu9250.cpp.
References _checked_bad, _checked_registers, _checked_values, MPU9250_NUM_CHECKED_REGISTERS, and write_reg().
Referenced by _set_dlpf_filter(), _set_sample_rate(), modify_checked_reg(), reset_mpu(), and set_accel_range().
void MPU9250::write_reg (unsigned reg, uint8_t value) private
Write a register in the mpu.
Parameters
reg The register to write.
value The new value to write.
Definition at line 957 of file mpu9250.cpp.
References _interface, and MPU9250_LOW_SPEED_OP.
Referenced by MPU9250_mag::ak8963_setup(), MPU9250_mag::ak8963_setup_master_i2c(), check_registers(), modify_reg(), MPU9250_mag::passthrough_read(), MPU9250_mag::passthrough_write(), reset_mpu(), MPU9250_mag::set_passthrough(), and write_checked_reg().
Friends And Related Function Documentation
friend class MPU9250_gyro friend
Definition at line 272 of file mpu9250.h.
friend class MPU9250_mag friend
Definition at line 271 of file mpu9250.h.
Member Data Documentation
int MPU9250::_accel_class_instance private
Definition at line 301 of file mpu9250.h.
Referenced by init(), MPU9250(), and ~MPU9250().
math::LowPassFilter2p MPU9250::_accel_filter_x private
Definition at line 324 of file mpu9250.h.
Referenced by init(), ioctl(), measure(), MPU9250(), and print_info().
math::LowPassFilter2p MPU9250::_accel_filter_y private
Definition at line 325 of file mpu9250.h.
Referenced by init(), ioctl(), measure(), and MPU9250().
math::LowPassFilter2p MPU9250::_accel_filter_z private
Definition at line 326 of file mpu9250.h.
Referenced by init(), ioctl(), measure(), and MPU9250().
Integrator MPU9250::_accel_int private
Definition at line 331 of file mpu9250.h.
Referenced by init(), measure(), and MPU9250().
int MPU9250::_accel_orb_class_instance private
Definition at line 300 of file mpu9250.h.
Referenced by init(), and MPU9250().
float MPU9250::_accel_range_m_s2 private
Definition at line 298 of file mpu9250.h.
Referenced by ioctl(), MPU9250(), and set_accel_range().
float MPU9250::_accel_range_scale private
Definition at line 297 of file mpu9250.h.
Referenced by measure(), MPU9250(), and set_accel_range().
perf_counter_t MPU9250::_accel_reads private
Definition at line 312 of file mpu9250.h.
Referenced by MPU9250(), print_info(), read(), and ~MPU9250().
ringbuffer::RingBuffer* MPU9250::_accel_reports private
Definition at line 294 of file mpu9250.h.
Referenced by init(), ioctl(), measure(), MPU9250(), print_info(), read(), start(), and ~MPU9250().
struct accel_calibration_s MPU9250::_accel_scale private
Definition at line 296 of file mpu9250.h.
Referenced by init(), ioctl(), measure(), and MPU9250().
orb_advert_t MPU9250::_accel_topic private
Definition at line 299 of file mpu9250.h.
Referenced by init(), measure(), MPU9250(), and ~MPU9250().
perf_counter_t MPU9250::_bad_registers private
Definition at line 316 of file mpu9250.h.
Referenced by check_registers(), measure(), MPU9250(), print_info(), and ~MPU9250().
perf_counter_t MPU9250::_bad_transfers private
Definition at line 315 of file mpu9250.h.
Referenced by check_null_data(), measure(), MPU9250(), print_info(), and ~MPU9250().
struct hrt_call MPU9250::_call private
Definition at line 291 of file mpu9250.h.
Referenced by ioctl(), MPU9250(), start(), and stop().
unsigned MPU9250::_call_interval private
Definition at line 292 of file mpu9250.h.
Referenced by gyro_read(), ioctl(), MPU9250(), MPU9250_mag::read(), read(), start(), and stop().
uint8_t MPU9250::_checked_bad[MPU9250_NUM_CHECKED_REGISTERS] private
Definition at line 342 of file mpu9250.h.
Referenced by check_registers(), print_info(), probe(), and write_checked_reg().
uint8_t MPU9250::_checked_next private
Definition at line 343 of file mpu9250.h.
Referenced by check_registers(), MPU9250(), and print_info().
const uint8_t MPU9250::_checked_registers static private
Initial value:
= { MPUREG_WHOAMI,
                                         MPUREG_PWR_MGMT_1,
                                         MPUREG_PWR_MGMT_2,
                                         MPUREG_USER_CTRL,
                                         MPUREG_SMPLRT_DIV,
                                         MPUREG_CONFIG,
                                         MPUREG_GYRO_CONFIG,
                                         MPUREG_ACCEL_CONFIG,
                                         MPUREG_ACCEL_CONFIG2,
                                         MPUREG_INT_ENABLE,
                                         MPUREG_INT_PIN_CFG
                                       }
Definition at line 340 of file mpu9250.h.
Referenced by check_registers(), print_info(), reset_mpu(), and write_checked_reg().
uint8_t MPU9250::_checked_values[MPU9250_NUM_CHECKED_REGISTERS] private
Definition at line 341 of file mpu9250.h.
Referenced by check_registers(), print_info(), probe(), reset_mpu(), and write_checked_reg().
unsigned MPU9250::_dlpf_freq private
Definition at line 309 of file mpu9250.h.
Referenced by _set_dlpf_filter(), and MPU9250().
perf_counter_t MPU9250::_duplicates private
Definition at line 319 of file mpu9250.h.
Referenced by check_duplicate(), MPU9250(), print_info(), and ~MPU9250().
perf_counter_t MPU9250::_good_transfers private
Definition at line 317 of file mpu9250.h.
Referenced by check_null_data(), MPU9250(), print_info(), and ~MPU9250().
bool MPU9250::_got_duplicate private
Definition at line 352 of file mpu9250.h.
Referenced by check_duplicate(), and MPU9250().
MPU9250_gyro* MPU9250::_gyro private
Definition at line 278 of file mpu9250.h.
Referenced by init(), measure(), MPU9250(), and ~MPU9250().
math::LowPassFilter2p MPU9250::_gyro_filter_x private
Definition at line 327 of file mpu9250.h.
Referenced by init(), ioctl(), measure(), MPU9250(), and print_info().
math::LowPassFilter2p MPU9250::_gyro_filter_y private
Definition at line 328 of file mpu9250.h.
Referenced by init(), ioctl(), measure(), and MPU9250().
math::LowPassFilter2p MPU9250::_gyro_filter_z private
Definition at line 329 of file mpu9250.h.
Referenced by init(), ioctl(), measure(), and MPU9250().
Integrator MPU9250::_gyro_int private
Definition at line 332 of file mpu9250.h.
Referenced by init(), measure(), and MPU9250().
float MPU9250::_gyro_range_rad_s private
Definition at line 307 of file mpu9250.h.
Referenced by gyro_ioctl(), MPU9250(), and reset_mpu().
float MPU9250::_gyro_range_scale private
Definition at line 306 of file mpu9250.h.
Referenced by measure(), MPU9250(), and reset_mpu().
perf_counter_t MPU9250::_gyro_reads private
Definition at line 313 of file mpu9250.h.
Referenced by gyro_read(), MPU9250(), print_info(), and ~MPU9250().
ringbuffer::RingBuffer* MPU9250::_gyro_reports private
Definition at line 303 of file mpu9250.h.
Referenced by gyro_ioctl(), gyro_read(), init(), measure(), MPU9250(), print_info(), start(), and ~MPU9250().
struct gyro_calibration_s MPU9250::_gyro_scale private
Definition at line 305 of file mpu9250.h.
Referenced by gyro_ioctl(), init(), measure(), and MPU9250().
Device* MPU9250::_interface protected
Definition at line 267 of file mpu9250.h.
Referenced by init(), measure(), MPU9250(), MPU9250_mag::read_block(), read_reg(), read_reg16(), test_error(), and write_reg().
uint8_t MPU9250::_last_accel_data[6] private
Definition at line 351 of file mpu9250.h.
Referenced by check_duplicate(), and MPU9250().
float MPU9250::_last_temperature private
Definition at line 346 of file mpu9250.h.
Referenced by MPU9250_mag::_measure(), measure(), MPU9250(), and print_info().
MPU9250_mag* MPU9250::_mag private
Definition at line 279 of file mpu9250.h.
Referenced by MPU9250_mag::_measure(), init(), measure(), MPU9250(), print_info(), reset(), reset_mpu(), start(), and ~MPU9250().
uint8_t MPU9250::_register_wait private
Definition at line 321 of file mpu9250.h.
Referenced by check_registers(), measure(), and MPU9250().
perf_counter_t MPU9250::_reset_retries private
Definition at line 318 of file mpu9250.h.
Referenced by MPU9250(), print_info(), and ~MPU9250().
uint64_t MPU9250::_reset_wait private
Definition at line 322 of file mpu9250.h.
Referenced by check_registers(), measure(), MPU9250(), and reset().
enum Rotation MPU9250::_rotation private
Definition at line 334 of file mpu9250.h.
Referenced by MPU9250_mag::_measure(), measure(), and MPU9250().
perf_counter_t MPU9250::_sample_perf private
Definition at line 314 of file mpu9250.h.
Referenced by check_duplicate(), check_null_data(), measure(), MPU9250(), print_info(), self_test(), and ~MPU9250().
unsigned MPU9250::_sample_rate private
Definition at line 311 of file mpu9250.h.
Referenced by _set_sample_rate(), gyro_ioctl(), init(), ioctl(), MPU9250(), and reset_mpu().
bool MPU9250::_use_hrt private
whoami result
Definition at line 289 of file mpu9250.h.
Referenced by MPU9250(), start(), and stop().
uint8_t MPU9250::_whoami private
Definition at line 280 of file mpu9250.h.
Referenced by init(), probe(), and reset().
The documentation for this class was generated from the following files:
src/drivers/imu/mpu9250/mpu9250.h
src/drivers/imu/mpu9250/mpu9250.cpp