PX4 Firmware: MavlinkStreamNamedValueFloat Class Reference
MavlinkStreamNamedValueFloat Class Reference
Public Member Functions
const char * get_name () const override
uint16_t get_id () override
unsigned get_size () override
Get maximal total messages size on update.
Public Member Functions inherited from MavlinkStream
MavlinkStream (Mavlink *mavlink)
virtual ~MavlinkStream ()=default
MavlinkStream (const MavlinkStream &)=delete
MavlinkStream & operator= (const MavlinkStream &)=delete
MavlinkStream (MavlinkStream &&)=delete
MavlinkStream & operator= (MavlinkStream &&)=delete
void set_interval (const int interval)
Get the interval.
int get_interval ()
Get the interval.
int update (const hrt_abstime &t)
Update subscriptions and send message if necessary.
virtual bool const_rate ()
virtual unsigned get_size_avg ()
Get the average message size.
bool first_message_sent () const
void reset_last_sent ()
Reset the time of last sent to 0.
Public Member Functions inherited from ListNode< MavlinkStream *>
void setSibling (MavlinkStream * sibling)
const MavlinkStream * getSibling () const
Static Public Member Functions
static const char * get_name_static ()
static uint16_t get_id_static ()
static MavlinkStream * new_instance (Mavlink *mavlink)
Protected Member Functions
MavlinkStreamNamedValueFloat (Mavlink *mavlink)
bool send (const hrt_abstime t) override
Protected Member Functions inherited from MavlinkStream
virtual void update_data ()
Function to collect/update data for the streams at a high rate independant of actual stream rate.
Private Member Functions
MavlinkStreamNamedValueFloat (MavlinkStreamNamedValueFloat &)=delete
MavlinkStreamNamedValueFloat & operator= (const MavlinkStreamNamedValueFloat &)=delete
Private Attributes
MavlinkOrbSubscription * _debug_sub
uint64_t _debug_time
Additional Inherited Members
Protected Attributes inherited from MavlinkStream
Mavlink *const _mavlink
int _interval {1000000}
if set to negative value = unlimited rate
Protected Attributes inherited from ListNode< MavlinkStream *>
MavlinkStream * _list_node_sibling
Detailed Description
Definition at line 3844 of file mavlink_messages.cpp.
Constructor & Destructor Documentation
MavlinkStreamNamedValueFloat() [1/2]
MavlinkStreamNamedValueFloat::MavlinkStreamNamedValueFloat (MavlinkStreamNamedValueFloat &) private delete
MavlinkStreamNamedValueFloat() [2/2]
MavlinkStreamNamedValueFloat::MavlinkStreamNamedValueFloat (Mavlink * mavlink) inline explicit protected
Definition at line 3886 of file mavlink_messages.cpp.
Member Function Documentation
get_id()
uint16_t MavlinkStreamNamedValueFloat::get_id () inline override virtual
Implements MavlinkStream.
Definition at line 3862 of file mavlink_messages.cpp.
References MavlinkStreamHeartbeat::get_id_static().
get_id_static()
static uint16_t MavlinkStreamNamedValueFloat::get_id_static () inline static
Definition at line 3857 of file mavlink_messages.cpp.
get_name()
const char* MavlinkStreamNamedValueFloat::get_name () const inline override virtual
Implements MavlinkStream.
Definition at line 3847 of file mavlink_messages.cpp.
References get_name_static().
get_name_static()
static const char* MavlinkStreamNamedValueFloat::get_name_static () inline static
Definition at line 3852 of file mavlink_messages.cpp.
Referenced by get_name().
get_size()
unsigned MavlinkStreamNamedValueFloat::get_size () inline override virtual
Get maximal total messages size on update.
Implements MavlinkStream.
Definition at line 3872 of file mavlink_messages.cpp.
new_instance()
static MavlinkStream* MavlinkStreamNamedValueFloat::new_instance (Mavlink * mavlink) inline static
Definition at line 3867 of file mavlink_messages.cpp.
operator=()
MavlinkStreamNamedValueFloat& MavlinkStreamNamedValueFloat::operator= (const MavlinkStreamNamedValueFloat &) private delete
send()
bool MavlinkStreamNamedValueFloat::send (const hrt_abstime t) inline override protected virtual
Implements MavlinkStream.
Definition at line 3891 of file mavlink_messages.cpp.
References MavlinkStream::_mavlink, Mavlink::get_channel(), debug_key_value_s::key, msg, debug_key_value_s::timestamp, MavlinkOrbSubscription::update(), and debug_key_value_s::value.
Member Data Documentation
_debug_sub
MavlinkOrbSubscription* MavlinkStreamNamedValueFloat::_debug_sub private
Definition at line 3878 of file mavlink_messages.cpp.
_debug_time
uint64_t MavlinkStreamNamedValueFloat::_debug_time private
Definition at line 3879 of file mavlink_messages.cpp.
The documentation for this class was generated from the following file:
src/modules/mavlink/mavlink_messages.cpp