PX4 Firmware: src/lib/rc/crsf.cpp File Reference
crsf.cpp File Reference
#include <drivers/drv_hrt.h>
#include <termios.h>
#include <string.h>
#include <unistd.h>
#include "crsf.h"
#include "common_rc.h"
Classes
struct crsf_payload_RC_channels_packed_t
Macros
#define CRSF_DEBUG(...)
#define CRSF_VERBOSE(...)
#define MIN(a, b) (((a)<(b))?(a):(b))
#define MAX(a, b) (((a)>(b))?(a):(b))
#define CRSF_BAUDRATE 420000
#define CRSF_SYNC_BYTE 0xC8
Enumerations
enum crsf_frame_type_t : uint8_t {
crsf_frame_type_t::gps = 0x02, crsf_frame_type_t::battery_sensor = 0x08, crsf_frame_type_t::link_statistics = 0x14, crsf_frame_type_t::rc_channels_packed = 0x16,
crsf_frame_type_t::attitude = 0x1E, crsf_frame_type_t::flight_mode = 0x21, crsf_frame_type_t::device_ping = 0x28, crsf_frame_type_t::device_info = 0x29,
crsf_frame_type_t::parameter_settings_entry = 0x2B, crsf_frame_type_t::parameter_read = 0x2C, crsf_frame_type_t::parameter_write = 0x2D, crsf_frame_type_t::command = 0x32
}
enum crsf_payload_size_t : uint8_t {
crsf_payload_size_t::gps = 15, crsf_payload_size_t::battery_sensor = 8, crsf_payload_size_t::link_statistics = 10, crsf_payload_size_t::rc_channels = 22,
crsf_payload_size_t::attitude = 6
}
enum crsf_address_t : uint8_t {
crsf_address_t::broadcast = 0x00, crsf_address_t::usb = 0x10, crsf_address_t::tbs_core_pnp_pro = 0x80, crsf_address_t::reserved1 = 0x8A,
crsf_address_t::current_sensor = 0xC0, crsf_address_t::gps = 0xC2, crsf_address_t::tbs_blackbox = 0xC4, crsf_address_t::flight_controller = 0xC8,
crsf_address_t::reserved2 = 0xCA, crsf_address_t::race_tag = 0xCC, crsf_address_t::radio_transmitter = 0xEA, crsf_address_t::crsf_receiver = 0xEC,
crsf_address_t::crsf_transmitter = 0xEE
}
enum crsf_parser_state_t : uint8_t { crsf_parser_state_t::unsynced = 0, crsf_parser_state_t::synced }
Functions
static bool crsf_parse_buffer (uint16_t *values, uint16_t *num_values, uint16_t max_channels)
parse the current crsf_frame buffer
static uint8_t crc8_dvb_s2 (uint8_t crc, uint8_t a)
static uint8_t crc8_dvb_s2_buf (uint8_t *buf, int len)
uint8_t crsf_frame_CRC (const crsf_frame_t &frame)
int crsf_config (int uart_fd)
Configure an UART port to be used for CRSF.
static uint16_t convert_channel_value (unsigned chan_value)
Convert from RC to PWM value.
bool crsf_parse (const uint64_t now, const uint8_t *frame, unsigned len, uint16_t *values, uint16_t *num_values, uint16_t max_channels)
Parse the CRSF protocol and extract RC channel data.
static void write_uint8_t (uint8_t *buf, int &offset, uint8_t value)
write an uint8_t value to a buffer at a given offset and increment the offset
static void write_uint16_t (uint8_t *buf, int &offset, uint16_t value)
write an uint16_t value to a buffer at a given offset and increment the offset
static void write_uint24_t (uint8_t *buf, int &offset, int value)
write an uint24_t value to a buffer at a given offset and increment the offset
static void write_int32_t (uint8_t *buf, int &offset, int32_t value)
write an int32_t value to a buffer at a given offset and increment the offset
static void write_frame_header (uint8_t *buf, int &offset, crsf_frame_type_t type, uint8_t payload_size)
static void write_frame_crc (uint8_t *buf, int &offset, int buf_size)
bool crsf_send_telemetry_battery (int uart_fd, uint16_t voltage, uint16_t current, int fuel, uint8_t remaining)
Send telemetry battery information.
bool crsf_send_telemetry_gps (int uart_fd, int32_t latitude, int32_t longitude, uint16_t groundspeed, uint16_t gps_heading, uint16_t altitude, uint8_t num_satellites)
Send telemetry GPS information.
bool crsf_send_telemetry_attitude (int uart_fd, int16_t pitch, int16_t roll, int16_t yaw)
Send telemetry Attitude information.
bool crsf_send_telemetry_flight_mode (int uart_fd, const char *flight_mode)
Send telemetry Flight Mode information.
Variables
static crsf_frame_t & crsf_frame = rc_decode_buf.crsf_frame
static unsigned current_frame_position = 0
static crsf_parser_state_t parser_state = crsf_parser_state_t::unsynced
Macro Definition Documentation
#define CRSF_BAUDRATE 420000
Definition at line 58 of file crsf.cpp.
Referenced by crsf_config().
#define CRSF_DEBUG (...)
Definition at line 37 of file crsf.cpp.
Referenced by crsf_parse(), and crsf_parse_buffer().
#define CRSF_SYNC_BYTE 0xC8
Definition at line 60 of file crsf.cpp.
Referenced by write_frame_header().
#define CRSF_VERBOSE (...)
Definition at line 43 of file crsf.cpp.
Referenced by crsf_parse_buffer().
#define MAX (a, b) (((a)>(b))?(a):(b))
Definition at line 55 of file crsf.cpp.
#define MIN (a, b) (((a)<(b))?(a):(b))
Definition at line 54 of file crsf.cpp.
Referenced by crsf_parse(), and crsf_parse_buffer().
Enumeration Type Documentation
enum crsf_address_t : uint8_t strong
Enumerator
broadcast
usb
tbs_core_pnp_pro
reserved1
current_sensor
gps
tbs_blackbox
flight_controller
reserved2
race_tag
radio_transmitter
crsf_receiver
crsf_transmitter
Definition at line 88 of file crsf.cpp.
enum crsf_frame_type_t : uint8_t strong
Enumerator
gps
battery_sensor
link_statistics
rc_channels_packed
attitude
flight_mode
device_ping
device_info
parameter_settings_entry
parameter_read
parameter_write
command
Definition at line 62 of file crsf.cpp.
enum crsf_parser_state_t : uint8_t strong
Enumerator
unsynced
synced
Definition at line 127 of file crsf.cpp.
enum crsf_payload_size_t : uint8_t strong
Enumerator
gps
battery_sensor
link_statistics
rc_channels
11 bits per channel * 16 channels = 22 bytes.
attitude
Definition at line 79 of file crsf.cpp.
Function Documentation
static uint16_t convert_channel_value (unsigned chan_value) static
Convert from RC to PWM value.
Parameters
chan_value channel value in [172, 1811]
Returns
PWM channel value in [1000, 2000]
Definition at line 244 of file crsf.cpp.
References f().
Referenced by crsf_config(), and crsf_parse_buffer().
static uint8_t crc8_dvb_s2 (uint8_t crc, uint8_t a) static
Definition at line 205 of file crsf.cpp.
Referenced by crc8_dvb_s2_buf(), and crsf_frame_CRC().
static uint8_t crc8_dvb_s2_buf (uint8_t * buf, int len) static
Definition at line 221 of file crsf.cpp.
References crc8_dvb_s2().
Referenced by write_frame_crc().
int crsf_config (int uart_fd)
Configure an UART port to be used for CRSF.
Parameters
uart_fd UART file descriptor
Returns
0 on success, -errno otherwise
Definition at line 147 of file crsf.cpp.
References convert_channel_value(), and CRSF_BAUDRATE.
Referenced by RCInput::cycle().
uint8_t crsf_frame_CRC (const crsf_frame_t & frame)
Definition at line 232 of file crsf.cpp.
References crc8_dvb_s2(), crsf_frame_t::header, crsf_frame_header_t::length, crsf_frame_t::payload, and crsf_frame_t::type.
Referenced by crsf_parse_buffer().
bool crsf_parse (const uint64_t now, const uint8_t * frame, unsigned len, uint16_t * values, uint16_t * num_values, uint16_t max_channels)
Parse the CRSF protocol and extract RC channel data.
Parameters
now current time
frame data to parse
len length of frame
values output channel values, each in range [1000, 2000]
num_values set to the number of parsed channels in values
max_channels maximum length of values
Returns
true if channels successfully decoded
Definition at line 166 of file crsf.cpp.
References CRSF_DEBUG, crsf_parse_buffer(), current_frame_position, MIN, and unsynced.
Referenced by RCTest::crsfTest(), and RCInput::cycle().
static bool crsf_parse_buffer (uint16_t * values, uint16_t * num_values, uint16_t max_channels) static
parse the current crsf_frame buffer
Definition at line 257 of file crsf.cpp.
References crsf_payload_RC_channels_packed_t::chan0, crsf_payload_RC_channels_packed_t::chan1, crsf_payload_RC_channels_packed_t::chan10, crsf_payload_RC_channels_packed_t::chan11, crsf_payload_RC_channels_packed_t::chan12, crsf_payload_RC_channels_packed_t::chan13, crsf_payload_RC_channels_packed_t::chan14, crsf_payload_RC_channels_packed_t::chan15, crsf_payload_RC_channels_packed_t::chan2, crsf_payload_RC_channels_packed_t::chan3, crsf_payload_RC_channels_packed_t::chan4, crsf_payload_RC_channels_packed_t::chan5, crsf_payload_RC_channels_packed_t::chan6, crsf_payload_RC_channels_packed_t::chan7, crsf_payload_RC_channels_packed_t::chan8, crsf_payload_RC_channels_packed_t::chan9, convert_channel_value(), CRSF_DEBUG, crsf_frame_CRC(), CRSF_VERBOSE, current_frame_position, crsf_frame_t::header, crsf_frame_header_t::length, MIN, crsf_frame_t::payload, rc_channels, rc_channels_packed, synced, crsf_frame_t::type, and unsynced.
Referenced by crsf_parse().
bool crsf_send_telemetry_attitude (int uart_fd, int16_t pitch, int16_t roll, int16_t yaw)
Send telemetry Attitude information.
Parameters
uart_fd UART file descriptor
pitch Pitch angle [rad * 1e4]
roll Roll angle [rad * 1e4]
yaw Yaw angle [rad * 1e4]
Returns
true on success
Definition at line 478 of file crsf.cpp.
References attitude, write(), write_frame_crc(), write_frame_header(), and write_uint16_t().
Referenced by CRSFTelemetry::send_attitude().
bool crsf_send_telemetry_battery (int uart_fd, uint16_t voltage, uint16_t current, int fuel, uint8_t remaining)
Send telemetry battery information.
Parameters
uart_fd UART file descriptor
voltage Voltage [0.1V]
current Current [0.1A]
fuel drawn mAh
remaining battery remaining [%]
Returns
true on success
Definition at line 449 of file crsf.cpp.
References battery_sensor, write(), write_frame_crc(), write_frame_header(), write_uint16_t(), write_uint24_t(), and write_uint8_t().
Referenced by CRSFTelemetry::send_battery().
bool crsf_send_telemetry_flight_mode (int uart_fd, const char * flight_mode)
Send telemetry Flight Mode information.
Parameters
uart_fd UART file descriptor
flight_mode Flight Mode string (max length = 15)
Returns
true on success
Definition at line 490 of file crsf.cpp.
References flight_mode, write(), write_frame_crc(), and write_frame_header().
Referenced by CRSFTelemetry::send_flight_mode().
bool crsf_send_telemetry_gps (int uart_fd, int32_t latitude, int32_t longitude, uint16_t groundspeed, uint16_t gps_heading, uint16_t altitude, uint8_t num_satellites)
Send telemetry GPS information.
Parameters
uart_fd UART file descriptor
latitude latitude [degree * 1e7]
longitude longitude [degree * 1e7]
groundspeed Ground speed [km/h * 10]
gps_heading GPS heading [degree * 100]
altitude Altitude [meters + 1000m offset]
num_satellites number of satellites used
Returns
true on success
Definition at line 462 of file crsf.cpp.
References gps, write(), write_frame_crc(), write_frame_header(), write_int32_t(), write_uint16_t(), and write_uint8_t().
Referenced by CRSFTelemetry::send_gps().
static void write_frame_crc (uint8_t * buf, int & offset, int buf_size) inline static
Definition at line 440 of file crsf.cpp.
References crc8_dvb_s2_buf(), and write_uint8_t().
Referenced by crsf_send_telemetry_attitude(), crsf_send_telemetry_battery(), crsf_send_telemetry_flight_mode(), and crsf_send_telemetry_gps().
static void write_frame_header (uint8_t * buf, int & offset, crsf_frame_type_t type, uint8_t payload_size) inline static
Definition at line 434 of file crsf.cpp.
References CRSF_SYNC_BYTE, and write_uint8_t().
Referenced by crsf_send_telemetry_attitude(), crsf_send_telemetry_battery(), crsf_send_telemetry_flight_mode(), and crsf_send_telemetry_gps().
static void write_int32_t (uint8_t * buf, int & offset, int32_t value) inline static
write an int32_t value to a buffer at a given offset and increment the offset
Definition at line 424 of file crsf.cpp.
Referenced by crsf_send_telemetry_gps().
static void write_uint16_t (uint8_t * buf, int & offset, uint16_t value) inline static
write an uint16_t value to a buffer at a given offset and increment the offset
Definition at line 402 of file crsf.cpp.
Referenced by crsf_send_telemetry_attitude(), crsf_send_telemetry_battery(), and crsf_send_telemetry_gps().
static void write_uint24_t (uint8_t * buf, int & offset, int value) inline static
write an uint24_t value to a buffer at a given offset and increment the offset
Definition at line 412 of file crsf.cpp.
Referenced by crsf_send_telemetry_battery().
static void write_uint8_t (uint8_t * buf, int & offset, uint8_t value) inline static
write an uint8_t value to a buffer at a given offset and increment the offset
Definition at line 395 of file crsf.cpp.
Referenced by crsf_send_telemetry_battery(), crsf_send_telemetry_gps(), write_frame_crc(), and write_frame_header().
Variable Documentation
crsf_frame_t& crsf_frame = rc_decode_buf.crsf_frame static
Definition at line 132 of file crsf.cpp.
unsigned current_frame_position = 0 static
Definition at line 133 of file crsf.cpp.
Referenced by crsf_parse(), and crsf_parse_buffer().
crsf_parser_state_t parser_state = crsf_parser_state_t::unsynced static
Definition at line 134 of file crsf.cpp.
Referenced by sf0x_parser(), and tfmini_parser().