PX4 Firmware: src/drivers/driver_framework_wrapper/df_ltc2946_wrapper/df_ltc2946_wrapper.cpp File Reference
df_ltc2946_wrapper.cpp File Reference
Driver to access the LTC2946 of the DriverFramework.
#include <string>
#include <px4_platform_common/px4_config.h>
#include <systemlib/err.h>
#include <battery/battery.h>
#include <drivers/drv_hrt.h>
#include <ltc2946/LTC2946.hpp>
#include <uORB/uORB.h>
#include <uORB/topics/battery_status.h>
#include <uORB/topics/actuator_controls.h>
#include <uORB/topics/vehicle_control_mode.h>
Classes
class DfLtc2946Wrapper
Namespaces
df_ltc2946_wrapper
Functions
__EXPORT int df_ltc2946_wrapper_main (int argc, char *argv[])
int df_ltc2946_wrapper::start ()
Attempt to start driver on all available I2C busses.
int df_ltc2946_wrapper::stop ()
Stop the driver.
int df_ltc2946_wrapper::info ()
Print a little info about the driver.
void df_ltc2946_wrapper::usage ()
Prints info about the driver argument usage.
Variables
DfLtc2946Wrapper * df_ltc2946_wrapper::g_dev = nullptr
Detailed Description
Driver to access the LTC2946 of the DriverFramework.
Author
Christoph Tobler chris.nosp@m.toph.nosp@m.@px4..nosp@m.io
Definition in file df_ltc2946_wrapper.cpp.
Function Documentation
df_ltc2946_wrapper_main()
int df_ltc2946_wrapper_main (int argc, char * argv[])
Definition at line 234 of file df_ltc2946_wrapper.cpp.
References df_ltc2946_wrapper::info(), df_ltc2946_wrapper::start(), df_ltc2946_wrapper::stop(), and df_ltc2946_wrapper::usage().