PX4 Firmware: src/lib/ecl/test/test_AlphaFilter.cpp File Reference
test_AlphaFilter.cpp File Reference
#include <gtest/gtest.h>
#include <cmath>
#include <matrix/math.hpp>
#include "EKF/AlphaFilter.hpp"
Classes
class AlphaFilterTest
Functions
TEST_F (AlphaFilterTest, initializeToZero)
TEST_F (AlphaFilterTest, resetToValue)
TEST_F (AlphaFilterTest, runZero)
TEST_F (AlphaFilterTest, runPositive)
TEST_F (AlphaFilterTest, runNegative)
TEST_F (AlphaFilterTest, riseTime)
TEST_F (AlphaFilterTest, convergence)
TEST_F (AlphaFilterTest, convergenceVector3f)
TEST_F (AlphaFilterTest, convergenceVector3fAlpha)
TEST_F (AlphaFilterTest, convergenceVector3fTauDt)
Function Documentation
TEST_F() [1/10]
TEST_F (AlphaFilterTest , initializeToZero)
Definition at line 48 of file test_AlphaFilter.cpp.
References AlphaFilterTest::filter_float, and AlphaFilter< T >::getState().
TEST_F() [2/10]
TEST_F (AlphaFilterTest , resetToValue)
Definition at line 53 of file test_AlphaFilter.cpp.
References AlphaFilterTest::filter_float, AlphaFilter< T >::getState(), and AlphaFilter< T >::reset().
TEST_F() [3/10]
TEST_F (AlphaFilterTest , runZero)
Definition at line 60 of file test_AlphaFilter.cpp.
References AlphaFilterTest::filter_float, AlphaFilter< T >::getState(), and AlphaFilter< T >::update().
TEST_F() [4/10]
TEST_F (AlphaFilterTest , runPositive)
Definition at line 69 of file test_AlphaFilter.cpp.
References AlphaFilterTest::filter_float, AlphaFilter< T >::getState(), and AlphaFilter< T >::update().
TEST_F() [5/10]
TEST_F (AlphaFilterTest , runNegative)
Definition at line 83 of file test_AlphaFilter.cpp.
References AlphaFilterTest::filter_float, AlphaFilter< T >::getState(), and AlphaFilter< T >::update().
TEST_F() [6/10]
TEST_F (AlphaFilterTest , riseTime)
Definition at line 97 of file test_AlphaFilter.cpp.
References AlphaFilterTest::filter_float, AlphaFilter< T >::getState(), and AlphaFilter< T >::update().
TEST_F() [7/10]
TEST_F (AlphaFilterTest , convergence)
Definition at line 111 of file test_AlphaFilter.cpp.
References AlphaFilterTest::filter_float, AlphaFilter< T >::getState(), and AlphaFilter< T >::update().
TEST_F() [8/10]
TEST_F (AlphaFilterTest , convergenceVector3f)
Definition at line 125 of file test_AlphaFilter.cpp.
References f(), AlphaFilterTest::filter_v3, AlphaFilter< T >::getState(), and AlphaFilter< T >::update().
TEST_F() [9/10]
TEST_F (AlphaFilterTest , convergenceVector3fAlpha)
Definition at line 142 of file test_AlphaFilter.cpp.
References dt, f(), AlphaFilterTest::filter_v3, AlphaFilter< T >::getState(), and AlphaFilter< T >::update().
TEST_F() [10/10]
TEST_F (AlphaFilterTest , convergenceVector3fTauDt)
Definition at line 162 of file test_AlphaFilter.cpp.
References dt, f(), AlphaFilterTest::filter_v3, AlphaFilter< T >::getState(), AlphaFilter< T >::reset(), and AlphaFilter< T >::update().