PX4 Firmware: src/drivers/imu/mpu6000/mpu6000.cpp File Reference
mpu6000.cpp File Reference
Driver for the Invensense MPU6000, MPU6050, ICM20608, and ICM20602 connected via SPI or I2C.
#include <px4_config.h>
#include <ecl/geo/geo.h>
#include <sys/types.h>
#include <stdint.h>
#include <stdbool.h>
#include <stddef.h>
#include <stdlib.h>
#include <semaphore.h>
#include <string.h>
#include <fcntl.h>
#include <poll.h>
#include <errno.h>
#include <stdio.h>
#include <math.h>
#include <unistd.h>
#include <px4_getopt.h>
#include <perf/perf_counter.h>
#include <systemlib/err.h>
#include <systemlib/conversions.h>
#include <systemlib/px4_macros.h>
#include <nuttx/arch.h>
#include <nuttx/wqueue.h>
#include <nuttx/clock.h>
#include <board_config.h>
#include <drivers/drv_hrt.h>
#include <drivers/device/spi.h>
#include <drivers/device/i2c.h>
#include <drivers/device/ringbuffer.h>
#include <drivers/device/integrator.h>
#include <drivers/drv_accel.h>
#include <drivers/drv_gyro.h>
#include <mathlib/math/filter/LowPassFilter2p.hpp>
#include <lib/conversion/rotation.h>
#include "mpu6000.h"
Classes
class MPU6000
class MPU6000_gyro
Helper class implementing the gyro driver node.
struct mpu6000::mpu6000_bus_option
Namespaces
mpu6000
Local functions in support of the shell command.
Macros
#define MPU6000_TIMER_REDUCTION 200
#define MPU6000_CHECKED_PRODUCT_ID_INDEX 0
#define MPU6000_NUM_CHECKED_REGISTERS 10
#define NUM_BUS_OPTIONS (sizeof(bus_options)/sizeof(bus_options[0]))
Enumerations
enum MPU_DEVICE_TYPE { MPU_DEVICE_TYPE_MPU6000 = 6000, MPU_DEVICE_TYPE_ICM20602 = 20602, MPU_DEVICE_TYPE_ICM20608 = 20608, MPU_DEVICE_TYPE_ICM20689 = 20689 }
enum MPU6000_BUS {
MPU6000_BUS_ALL = 0, MPU6000_BUS_I2C_INTERNAL, MPU6000_BUS_I2C_EXTERNAL, MPU6000_BUS_SPI_INTERNAL1,
MPU6000_BUS_SPI_INTERNAL2, MPU6000_BUS_SPI_EXTERNAL1, MPU6000_BUS_SPI_EXTERNAL2
}
Functions
__EXPORT int mpu6000_main (int argc, char *argv[])
driver 'main' command
void mpu6000::start (enum MPU6000_BUS busid, enum Rotation rotation, int range, int device_type)
Start the driver.
bool mpu6000::start_bus (struct mpu6000_bus_option &bus, enum Rotation rotation, int range, int device_type)
start driver for a specific bus option
void mpu6000::stop (enum MPU6000_BUS busid)
void mpu6000::test (enum MPU6000_BUS busid)
Perform some basic functional tests on the driver; make sure we can collect data from the sensor in polled and automatic modes.
static struct mpu6000_bus_option & mpu6000::find_bus (enum MPU6000_BUS busid)
find a bus structure for a busid
void mpu6000::reset (enum MPU6000_BUS busid)
Reset the driver.
void mpu6000::info (enum MPU6000_BUS busid)
Print a little info about the driver.
void mpu6000::regdump (enum MPU6000_BUS busid)
Dump the register information.
void mpu6000::testerror (enum MPU6000_BUS busid)
deliberately produce an error to test recovery
void mpu6000::factorytest (enum MPU6000_BUS busid)
Dump the register information.
void mpu6000::usage ()
Prints info about the driver argument usage.
Variables
struct mpu6000::mpu6000_bus_option mpu6000::bus_options []
Detailed Description
Driver for the Invensense MPU6000, MPU6050, ICM20608, and ICM20602 connected via SPI or I2C.
When the device is on the SPI bus the hrt is used to provide thread of execution to the driver.
When the device is on the I2C bus a work queue is used provide thread of execution to the driver.
The I2C code is only included in the build if USE_I2C is defined by the existance of any of PX4_I2C_MPU6050_ADDR, PX4_I2C_MPU6000_ADDR PX4_I2C_ICM_20608_G_ADDR in the board_config.h file.
The command line option -T 6000|20608|20602 (default 6000) selects between MPU60x0, ICM20608G, or ICM20602G;
Author
Andrew Tridgell
Pat Hickey
David Sidrane
Definition in file mpu6000.cpp.
Macro Definition Documentation
#define MPU6000_CHECKED_PRODUCT_ID_INDEX 0
Definition at line 229 of file mpu6000.cpp.
Referenced by MPU6000::check_registers(), and MPU6000::probe().
#define MPU6000_NUM_CHECKED_REGISTERS 10
Definition at line 230 of file mpu6000.cpp.
Referenced by MPU6000::check_registers(), MPU6000::is_external(), MPU6000::print_info(), and MPU6000::write_checked_reg().
#define MPU6000_TIMER_REDUCTION 200
Definition at line 110 of file mpu6000.cpp.
Referenced by MPU6000::ioctl(), MPU6000::start(), and MPU6000::stop().
#define NUM_BUS_OPTIONS (sizeof(bus_options)/sizeof(bus_options[0]))
Definition at line 2153 of file mpu6000.cpp.
Referenced by mpu6000::find_bus(), and mpu6000::start().
Enumeration Type Documentation
enum MPU6000_BUS
Enumerator
MPU6000_BUS_ALL
MPU6000_BUS_I2C_INTERNAL
MPU6000_BUS_I2C_EXTERNAL
MPU6000_BUS_SPI_INTERNAL1
MPU6000_BUS_SPI_INTERNAL2
MPU6000_BUS_SPI_EXTERNAL1
MPU6000_BUS_SPI_EXTERNAL2
Definition at line 119 of file mpu6000.cpp.
enum MPU_DEVICE_TYPE
Enumerator
MPU_DEVICE_TYPE_MPU6000
MPU_DEVICE_TYPE_ICM20602
MPU_DEVICE_TYPE_ICM20608
MPU_DEVICE_TYPE_ICM20689
Definition at line 112 of file mpu6000.cpp.
Function Documentation
int mpu6000_main (int argc, char * argv[])
driver 'main' command
Definition at line 2492 of file mpu6000.cpp.
References mpu6000::factorytest(), mpu6000::info(), MPU6000_ACCEL_DEFAULT_RANGE_G, MPU6000_BUS_ALL, MPU6000_BUS_I2C_EXTERNAL, MPU6000_BUS_I2C_INTERNAL, MPU6000_BUS_SPI_EXTERNAL1, MPU6000_BUS_SPI_EXTERNAL2, MPU6000_BUS_SPI_INTERNAL1, MPU6000_BUS_SPI_INTERNAL2, MPU_DEVICE_TYPE_MPU6000, px4_getopt(), mpu6000::regdump(), mpu6000::reset(), ROTATION_NONE, mpu6000::start(), mpu6000::stop(), mpu6000::test(), mpu6000::testerror(), and mpu6000::usage().