PX4 Firmware: src/lib/mathlib/math/test/test.cpp File Reference
test.cpp File Reference
#include <stdio.h>
#include <math.h>
#include <stdlib.h>
#include <px4_defines.h>
#include "test.hpp"
Functions
bool __EXPORT equal (float a, float b, float epsilon)
bool __EXPORT greater_than (float a, float b)
bool __EXPORT less_than (float a, float b)
bool __EXPORT greater_than_or_equal (float a, float b)
bool __EXPORT less_than_or_equal (float a, float b)
void __EXPORT float2SigExp (const float &num, float &sig, int &exp)
Function Documentation
bool __EXPORT equal (float a, float b, float epsilon)
Definition at line 48 of file test.cpp.
Referenced by control::blockDelayTest(), blockDelayTest(), control::blockDerivativeTest(), blockDerivativeTest(), control::blockHighPassTest(), blockHighPassTest(), blockIntegralTest(), control::blockIntegralTest(), blockIntegralTrapTest(), control::blockIntegralTrapTest(), control::blockLimitSymTest(), blockLimitSymTest(), control::blockLimitTest(), blockLimitTest(), control::blockLowPass2Test(), blockLowPass2Test(), blockLowPassTest(), control::blockLowPassTest(), control::blockOutputTest(), blockOutputTest(), control::blockPDTest(), blockPDTest(), control::blockPIDTest(), blockPIDTest(), control::blockPITest(), blockPITest(), blockPTest(), control::blockPTest(), blockRandGaussTest(), control::blockRandGaussTest(), blockRandUniformTest(), control::blockRandUniformTest(), control::blockStatsTest(), blockStatsTest(), matrix::isEqual(), and matrix::isEqualF().
void __EXPORT float2SigExp (const float & num, float & sig, int & exp)
Definition at line 103 of file test.cpp.
References f().
bool __EXPORT greater_than (float a, float b)
Definition at line 59 of file test.cpp.
bool __EXPORT greater_than_or_equal (float a, float b)
Definition at line 81 of file test.cpp.
Referenced by control::blockRandUniformTest(), and blockRandUniformTest().
bool __EXPORT less_than (float a, float b)
Definition at line 70 of file test.cpp.
bool __EXPORT less_than_or_equal (float a, float b)
Definition at line 92 of file test.cpp.
Referenced by control::blockRandUniformTest(), and blockRandUniformTest().