PX4 Firmware: LedController Class Reference
LedController Class Reference
class LedController Handles the led_control topic: blinking, priorities and state updates.
#include <led.h>
Classes
struct NextState
struct PerLedData
struct PerPriorityData
Public Member Functions
LedController ()=default
~LedController ()=default
int init (int led_control_sub)
initialize.
bool is_init () const
check if already initialized
int maximum_update_interval () const
get maxium time between two consecutive calls to update() in us.
int update (LedControlData &control_data)
Update and retrieve the Led state.
int led_control_subscription () const
Static Public Attributes
static const int BREATHE_INTERVAL = 25 * 1000
single step when in breathe mode
static const int BREATHE_STEPS = 64
number of steps in breathe mode for a full on-off cycle
static const int BLINK_FAST_DURATION = 100 * 1000
duration of half a blinking cycle (on-to-off and off-to-on) in us
static const int BLINK_NORMAL_DURATION = 500 * 1000
duration of half a blinking cycle (on-to-off and off-to-on) in us
static const int BLINK_SLOW_DURATION = 2000 * 1000
duration of half a blinking cycle (on-to-off and off-to-on) in us
Private Member Functions
void get_control_data (LedControlData &control_data)
set control_data based on current Led states
Private Attributes
PerLedData _states [BOARD_MAX_LEDS]
keep current LED states
int _led_control_sub = -1
uorb subscription
hrt_abstime _last_update_call
bool _force_update = true
force an orb_copy in the beginning
bool _breathe_enabled = false
true if at least one of the led's is currently in breathe mode
Detailed Description
class LedController Handles the led_control topic: blinking, priorities and state updates.
Definition at line 61 of file led.h.
Constructor & Destructor Documentation
LedController::LedController () default
LedController::~LedController () default
Member Function Documentation
void LedController::get_control_data (LedControlData & control_data) inline private
set control_data based on current Led states
Definition at line 204 of file led.cpp.
References _breathe_enabled, _states, LedController::PerPriorityData::blink_times_left, BOARD_MAX_LEDS, BREATHE_INTERVAL, BREATHE_STEPS, LedControlDataSingle::brightness, LedControlDataSingle::color, LedController::PerPriorityData::color, counter, LedController::PerLedData::current_blinking_time, LedControlData::leds, LedController::PerPriorityData::mode, and LedController::PerLedData::priority.
Referenced by update().
int LedController::init (int led_control_sub)
initialize.
Call this once before using the object
Parameters
led_control_sub uorb subscription for led_control
Returns
0 on success, <0 on error otherwise
Definition at line 41 of file led.cpp.
References _last_update_call, _led_control_sub, and hrt_absolute_time().
Referenced by RGBLED::_measure(), RGBLED_PWM::led(), and RGBLED::led().
bool LedController::is_init () const inline
check if already initialized
Definition at line 77 of file led.h.
Referenced by RGBLED::_measure(), RGBLED_PWM::led(), and RGBLED::led().
int LedController::led_control_subscription () const inline
Definition at line 105 of file led.h.
Referenced by RGBLED_PWM::led(), RGBLED::led(), and RGBLED::~RGBLED().
int LedController::maximum_update_interval () const inline
get maxium time between two consecutive calls to update() in us.
Definition at line 82 of file led.h.
Referenced by RGBLED_PWM::led(), RGBLED::led(), and RGBLED::start().
int LedController::update (LedControlData & control_data)
Update and retrieve the Led state.
It will do the orb_copy() and needs to be called at least every maximum_update_interval(). In addition a caller might poll on the led_control_sub
Parameters
control_data output structure (will always be set)
Returns
1 if control_data set (state changed), 0 if control_data not changed (state did not change), <0 error otherwise
Definition at line 48 of file led.cpp.
References _force_update, _last_update_call, _led_control_sub, _states, LedController::PerLedData::apply_next_state(), BLINK_FAST_DURATION, BLINK_NORMAL_DURATION, BLINK_SLOW_DURATION, LedController::PerPriorityData::blink_times_left, BOARD_MAX_LEDS, BREATHE_INTERVAL, BREATHE_STEPS, LedController::PerLedData::current_blinking_time, get_control_data(), hrt_absolute_time(), hrt_abstime, led_control, led_control_s::led_mask, LedController::PerPriorityData::mode, LedController::PerLedData::next_state, orb_check(), orb_copy(), ORB_ID, led_control_s::priority, LedController::NextState::priority, LedController::PerLedData::priority, LedController::NextState::reset(), LedController::NextState::set(), and LedController::PerLedData::set().
Referenced by RGBLED::_measure(), RGBLED_PWM::led(), and RGBLED::led().
Member Data Documentation
bool LedController::_breathe_enabled = false private
true if at least one of the led's is currently in breathe mode
Definition at line 192 of file led.h.
Referenced by get_control_data().
bool LedController::_force_update = true private
force an orb_copy in the beginning
Definition at line 191 of file led.h.
Referenced by update().
hrt_abstime LedController::_last_update_call private
Definition at line 190 of file led.h.
Referenced by init(), and update().
int LedController::_led_control_sub = -1 private
uorb subscription
Definition at line 189 of file led.h.
Referenced by init(), and update().
PerLedData LedController::_states[BOARD_MAX_LEDS] private
keep current LED states
Definition at line 187 of file led.h.
Referenced by get_control_data(), and update().
const int LedController::BLINK_FAST_DURATION = 100 * 1000 static
duration of half a blinking cycle (on-to-off and off-to-on) in us
Definition at line 98 of file led.h.
Referenced by update().
const int LedController::BLINK_NORMAL_DURATION = 500 * 1000 static
duration of half a blinking cycle (on-to-off and off-to-on) in us
Definition at line 100 of file led.h.
Referenced by update().
const int LedController::BLINK_SLOW_DURATION = 2000 * 1000 static
duration of half a blinking cycle (on-to-off and off-to-on) in us
Definition at line 102 of file led.h.
Referenced by update().
const int LedController::BREATHE_INTERVAL = 25 * 1000 static
single step when in breathe mode
Definition at line 95 of file led.h.
Referenced by get_control_data(), and update().
const int LedController::BREATHE_STEPS = 64 static
number of steps in breathe mode for a full on-off cycle
Definition at line 96 of file led.h.
Referenced by get_control_data(), and update().
The documentation for this class was generated from the following files:
src/lib/led/led.h
src/lib/led/led.cpp