PX4 Firmware: src/drivers/imu/adis16448/adis16448_main.cpp File Reference
adis16448_main.cpp File Reference
#include "ADIS16448.h"
#include <px4_platform_common/getopt.h>
Namespaces
adis16448
Functions
static int adis16448::start (enum Rotation rotation)
static int adis16448::stop ()
static int adis16448::status ()
static int adis16448::usage ()
int adis16448_main (int argc, char *argv[])
Variables
ADIS16448 * adis16448::g_dev {nullptr}
Function Documentation
adis16448_main()
int adis16448_main (int argc, char * argv[])
Definition at line 110 of file adis16448_main.cpp.
References ROTATION_NONE, adis16448::start(), adis16448::status(), adis16448::stop(), and adis16448::usage().