PX4 Firmware: RCTest Class Reference
RCTest Class Reference
Public Member Functions
bool run_tests () override
Override to run your unit tests.
Public Member Functions inherited from UnitTest
UnitTest ()=default
virtual ~UnitTest ()=default
void print_results ()
Prints results from running of unit tests.
Private Member Functions
bool crsfTest ()
bool dsmTest (const char *filepath, unsigned expected_chancount, unsigned expected_dropcount, unsigned chan0)
bool dsmTest10Ch ()
bool dsmTest12Ch ()
bool sbus2Test ()
bool st24Test ()
bool sumdTest ()
Additional Inherited Members
Protected Member Functions inherited from UnitTest
virtual void _init (void)
Run before each unit test. Override to provide custom behavior.
virtual void _cleanup (void)
Run after each unit test. Override to provide custom behavior.
void _print_assert (const char *msg, const char *test, const char *file, int line)
void _print_compare (const char *msg, const char *v1_text, int v1, const char *v2_text, int v2, const char *file, int line)
Protected Attributes inherited from UnitTest
int _tests_run {0}
The number of individual unit tests run.
int _tests_failed {0}
The number of unit tests which failed.
int _tests_passed {0}
The number of unit tests which passed.
int _assertions {0}
Total number of assertions tested by all unit tests.
Detailed Description
Definition at line 26 of file RCTest.cpp.
Member Function Documentation
crsfTest()
bool RCTest::crsfTest () private
Definition at line 53 of file RCTest.cpp.
References matrix::abs(), crsf_parse(), hrt_absolute_time(), hrt_abstime, TEST_DATA_PATH, ut_compare, and ut_test.
Referenced by run_tests().
dsmTest()
bool RCTest::dsmTest (const char * filepath, unsigned expected_chancount, unsigned expected_dropcount, unsigned chan0) private
Definition at line 149 of file RCTest.cpp.
References matrix::abs(), dsm_frame_drops, dsm_parse(), dsm_proto_init(), f(), ut_compare, and ut_test.
Referenced by dsmTest10Ch(), and dsmTest12Ch().
dsmTest10Ch()
bool RCTest::dsmTest10Ch () private
Definition at line 139 of file RCTest.cpp.
References dsmTest(), and TEST_DATA_PATH.
Referenced by run_tests().
dsmTest12Ch()
bool RCTest::dsmTest12Ch () private
Definition at line 144 of file RCTest.cpp.
References dsmTest(), and TEST_DATA_PATH.
Referenced by run_tests().
run_tests()
bool RCTest::run_tests () override virtual
Override to run your unit tests.
Unit tests should be called using ut_run_test macro.
Returns
true: all unit tests succeeded, false: one or more unit tests failed
Implements UnitTest.
Definition at line 41 of file RCTest.cpp.
References UnitTest::_tests_failed, crsfTest(), dsmTest10Ch(), dsmTest12Ch(), sbus2Test(), st24Test(), sumdTest(), and ut_run_test.
sbus2Test()
bool RCTest::sbus2Test () private
Definition at line 224 of file RCTest.cpp.
References f(), hrt_absolute_time(), hrt_abstime, SBUS_BUFFER_SIZE, sbus_frame_drops, sbus_parse(), TEST_DATA_PATH, and ut_test.
Referenced by run_tests().
st24Test()
bool RCTest::st24Test () private
Definition at line 293 of file RCTest.cpp.
References f(), st24_decode(), TEST_DATA_PATH, and ut_test.
Referenced by run_tests().
sumdTest()
bool RCTest::sumdTest () private
Definition at line 354 of file RCTest.cpp.
References f(), rc_tests_main(), sumd_decode(), TEST_DATA_PATH, ut_declare_test_c, and ut_test.
Referenced by run_tests().
The documentation for this class was generated from the following file:
src/lib/rc/rc_tests/RCTest.cpp