PX4 Firmware: src/drivers/boards/bbblue/init.c File Reference
init.c File Reference
#include <stddef.h>
#include <px4_log.h>
#include <robotcontrol.h>
#include "board_config.h"
Functions
int rc_init (void)
void rc_cleaning (void)
Function Documentation
void rc_cleaning (void)
Definition at line 121 of file init.c.
References data.
Referenced by BBBlueADC::~BBBlueADC().
int rc_init (void)
Definition at line 47 of file init.c.
References f(), PX4_ERR, and PX4_INFO.
Referenced by BBBlueADC::init().