PX4 Firmware: StraightLine Class Reference
StraightLine Class Reference
#include <StraightLine.hpp>
Public Member Functions
StraightLine (ModuleParams *parent, const float &deltatime, const matrix::Vector3f &pos)
~StraightLine ()=default
void setLineFromTo (const matrix::Vector3f &origin, const matrix::Vector3f &target)
void setSpeed (const float &speed)
void setSpeedAtTarget (const float &speed_at_target)
void setAcceleration (const float &acc)
void setDeceleration (const float &dec)
void setAllDefaults ()
Set all parameters to their default value depending on the direction of the line.
float getMaxAcc ()
Get the maximum possible acceleration depending on the direction of the line Respects horizontal and vertical limits.
float getMaxVel ()
Get the maximum possible velocity depending on the direction of the line Respects horizontal and vertical limits.
void generateSetpoints (matrix::Vector3f &position_setpoint, matrix::Vector3f &velocity_setpoint)
Generate setpoints on a straight line according to parameters.
Public Member Functions inherited from ModuleParams
ModuleParams (ModuleParams *parent)
void setParent (ModuleParams *parent)
Set the parent module.
virtual ~ModuleParams ()=default
ModuleParams (const ModuleParams &)=delete
ModuleParams & operator= (const ModuleParams &)=delete
ModuleParams (ModuleParams &&)=delete
ModuleParams & operator= (ModuleParams &&)=delete
Public Member Functions inherited from ListNode< ModuleParams * >
ListNode ()
ListNode (const ListNode &)=delete
ListNode (ListNode &&)=delete
virtual ~ListNode ()=default
ListNode & operator= (const ListNode &)=delete
ListNode & operator= (ListNode &&)=delete
void setSibling (ModuleParams *sibling)
const ModuleParams * getSibling ()
Private Attributes
const float & _deltatime
delta time between last update (dependency injection)
const matrix::Vector3f & _pos
vehicle position (dependency injection)
float _desired_acceleration {0.0f}
acceleration along the straight line
float _desired_deceleration {0.0f}
deceleration along the straight line
float _desired_speed {0.0f}
desired maximum velocity
float _desired_speed_at_target {0.0f}
desired velocity at target point
matrix::Vector3f _target {}
End point of the straight line.
matrix::Vector3f _origin {}
Start point of the straight line.
Additional Inherited Members
Protected Member Functions inherited from ModuleParams
virtual void updateParams ()
Call this whenever the module gets a parameter change notification.
virtual void updateParamsImpl ()
The implementation for this is generated with the macro DEFINE_PARAMETERS()
Protected Attributes inherited from ListNode< ModuleParams * >
ModuleParams * _sibling
Detailed Description
Definition at line 47 of file StraightLine.hpp.
Constructor & Destructor Documentation
StraightLine::StraightLine (ModuleParams * parent, const float & deltatime, const matrix::Vector3f & pos)
Definition at line 47 of file StraightLine.cpp.
StraightLine::~StraightLine () default
Member Function Documentation
void StraightLine::generateSetpoints (matrix::Vector3f & position_setpoint, matrix::Vector3f & velocity_setpoint)
Generate setpoints on a straight line according to parameters.
Parameters
position_setpoint 3D vector with the previous position setpoint
velocity_setpoint 3D vector with the previous velocity setpoint
Definition at line 54 of file StraightLine.cpp.
References _deltatime, _desired_acceleration, _desired_deceleration, _desired_speed, _desired_speed_at_target, _origin, _pos, _target, math::constrain(), f(), math::max(), and VEL_ZERO_THRESHOLD.
float StraightLine::getMaxAcc ()
Get the maximum possible acceleration depending on the direction of the line Respects horizontal and vertical limits.
Definition at line 105 of file StraightLine.cpp.
References _origin, _target, matrix::Matrix< Type, M, N >::data(), and math::min().
Referenced by setAllDefaults().
float StraightLine::getMaxVel ()
Get the maximum possible velocity depending on the direction of the line Respects horizontal and vertical limits.
Definition at line 140 of file StraightLine.cpp.
References _origin, _target, matrix::Matrix< Type, M, N >::data(), and math::min().
Referenced by setAcceleration(), setAllDefaults(), setSpeed(), and setSpeedAtTarget().
void StraightLine::setAcceleration (const float & acc)
Definition at line 219 of file StraightLine.cpp.
References _desired_acceleration, and getMaxVel().
void StraightLine::setAllDefaults ()
Set all parameters to their default value depending on the direction of the line.
Definition at line 175 of file StraightLine.cpp.
References _desired_acceleration, _desired_deceleration, _desired_speed, _desired_speed_at_target, DECELERATION_MAX, getMaxAcc(), and getMaxVel().
Referenced by setLineFromTo().
void StraightLine::setDeceleration (const float & dec)
Definition at line 231 of file StraightLine.cpp.
References _desired_deceleration, and DECELERATION_MAX.
void StraightLine::setLineFromTo (const matrix::Vector3f & origin, const matrix::Vector3f & target)
Definition at line 183 of file StraightLine.cpp.
References _origin, _target, and setAllDefaults().
void StraightLine::setSpeed (const float & speed)
Definition at line 195 of file StraightLine.cpp.
References _desired_speed, and getMaxVel().
void StraightLine::setSpeedAtTarget (const float & speed_at_target)
Definition at line 207 of file StraightLine.cpp.
References _desired_speed_at_target, and getMaxVel().
Member Data Documentation
const float& StraightLine::_deltatime private
delta time between last update (dependency injection)
Definition at line 86 of file StraightLine.hpp.
Referenced by generateSetpoints().
float StraightLine::_desired_acceleration {0.0f} private
acceleration along the straight line
Definition at line 89 of file StraightLine.hpp.
Referenced by generateSetpoints(), setAcceleration(), and setAllDefaults().
float StraightLine::_desired_deceleration {0.0f} private
deceleration along the straight line
Definition at line 90 of file StraightLine.hpp.
Referenced by generateSetpoints(), setAllDefaults(), and setDeceleration().
float StraightLine::_desired_speed {0.0f} private
desired maximum velocity
Definition at line 91 of file StraightLine.hpp.
Referenced by generateSetpoints(), setAllDefaults(), and setSpeed().
float StraightLine::_desired_speed_at_target {0.0f} private
desired velocity at target point
Definition at line 92 of file StraightLine.hpp.
Referenced by generateSetpoints(), setAllDefaults(), and setSpeedAtTarget().
matrix::Vector3f StraightLine::_origin {} private
Start point of the straight line.
Definition at line 95 of file StraightLine.hpp.
Referenced by generateSetpoints(), getMaxAcc(), getMaxVel(), and setLineFromTo().
const matrix::Vector3f& StraightLine::_pos private
vehicle position (dependency injection)
Definition at line 87 of file StraightLine.hpp.
Referenced by generateSetpoints().
matrix::Vector3f StraightLine::_target {} private
End point of the straight line.
Definition at line 94 of file StraightLine.hpp.
Referenced by generateSetpoints(), getMaxAcc(), getMaxVel(), and setLineFromTo().
The documentation for this class was generated from the following files:
src/lib/FlightTasks/tasks/Utility/StraightLine.hpp
src/lib/FlightTasks/tasks/Utility/StraightLine.cpp