PX4 Firmware: df_bmp280_wrapper Namespace Reference
df_bmp280_wrapper Namespace Reference
Functions
int start ()
Attempt to start driver on all available I2C busses.
int stop ()
Stop the driver.
int info ()
Print a little info about the driver.
void usage ()
Prints info about the driver argument usage.
Variables
DfBmp280Wrapper * g_dev = nullptr
Function Documentation
info()
int df_bmp280_wrapper::info ()
Print a little info about the driver.
Definition at line 247 of file df_bmp280_wrapper.cpp.
Referenced by df_bmp280_wrapper_main().
start()
int df_bmp280_wrapper::start ()
Attempt to start driver on all available I2C busses.
This function will return as soon as the first sensor is detected on one of the available busses or if no sensors are detected.
Definition at line 193 of file df_bmp280_wrapper.cpp.
References DfBmp280Wrapper::DfBmp280Wrapper(), and DfBmp280Wrapper::start().
Referenced by df_bmp280_wrapper_main().
stop()
int df_bmp280_wrapper::stop ()
Stop the driver.
Stop the driver.
Definition at line 224 of file df_bmp280_wrapper.cpp.
References g_dev, and DfBmp280Wrapper::stop().
Referenced by df_bmp280_wrapper_main().
usage()
void df_bmp280_wrapper::usage (void)
Prints info about the driver argument usage.
Prints info about the driver argument usage.
Definition at line 260 of file df_bmp280_wrapper.cpp.
Referenced by df_bmp280_wrapper_main().
Variable Documentation
g_dev
DfBmp280Wrapper* df_bmp280_wrapper::g_dev = nullptr
Definition at line 186 of file df_bmp280_wrapper.cpp.
Referenced by stop().