PX4 Firmware: src/modules/muorb/adsp/px4muorb.hpp File Reference
px4muorb.hpp File Reference
#include <stdint.h>
Functions
int px4muorb_orb_initialize () __EXPORT
int px4muorb_set_absolute_time_offset (int32_t time_diff_us) __EXPORT
int px4muorb_get_absolute_time (uint64_t *time_us) __EXPORT
int px4muorb_param_update_to_shmem (uint32_t param, const uint8_t *value, int data_len_in_bytes) __EXPORT
int px4muorb_param_update_index_from_shmem (unsigned char *data, int data_len_in_bytes) __EXPORT
int px4muorb_param_update_value_from_shmem (uint32_t param, const uint8_t *value, int data_len_in_bytes) __EXPORT
int px4muorb_topic_advertised (const char *name) __EXPORT
int px4muorb_topic_unadvertised (const char *name) __EXPORT
int px4muorb_add_subscriber (const char *name) __EXPORT
int px4muorb_remove_subscriber (const char *name) __EXPORT
int px4muorb_send_topic_data (const char *name, const uint8_t *data, int data_len_in_bytes) __EXPORT
int px4muorb_is_subscriber_present (const char *topic_name, int *status) __EXPORT
int px4muorb_receive_msg (int *msg_type, char *topic_name, int topic_name_len, uint8_t *data, int data_len_in_bytes, int *bytes_returned) __EXPORT
int px4muorb_receive_bulk_data (uint8_t *_BulkTransferBuffer, int max_size_in_bytes, int *length_in_bytes, int *topic_count) __EXPORT
int px4muorb_unblock_recieve_msg (void) __EXPORT
Function Documentation
px4muorb_add_subscriber()
int px4muorb_add_subscriber (const char * name)
Definition at line 190 of file px4muorb.cpp.
References uORB::FastRpcChannel::AddRemoteSubscriber(), uORB::FastRpcChannel::GetInstance(), uORB::FastRpcChannel::GetRxHandler(), OK, uORBCommunicator::IChannelRxHandler::process_add_subscription(), and uORB::FastRpcChannel::RemoveRemoteSubscriber().
Referenced by px4muorb::KraitRpcWrapper::AddSubscriber().
px4muorb_get_absolute_time()
int px4muorb_get_absolute_time (uint64_t * time_us)
Definition at line 76 of file px4muorb.cpp.
References hrt_absolute_time().
Referenced by px4muorb::KraitRpcWrapper::Initialize().
px4muorb_is_subscriber_present()
int px4muorb_is_subscriber_present (const char * topic_name, int * status)
Definition at line 246 of file px4muorb.cpp.
References uORB::FastRpcChannel::GetInstance(), and uORB::FastRpcChannel::is_subscriber_present().
Referenced by px4muorb::KraitRpcWrapper::IsSubscriberPresent().
px4muorb_orb_initialize()
int px4muorb_orb_initialize ()
Definition at line 51 of file px4muorb.cpp.
References dspal_main(), uORB::Manager::get_instance(), uORB::FastRpcChannel::GetInstance(), and uORB::Manager::initialize().
Referenced by px4muorb::KraitRpcWrapper::Initialize().
px4muorb_param_update_index_from_shmem()
int px4muorb_param_update_index_from_shmem (unsigned char * data, int data_len_in_bytes)
Definition at line 109 of file px4muorb.cpp.
References param_value_u::i.
px4muorb_param_update_to_shmem()
int px4muorb_param_update_to_shmem (uint32_t param, const uint8_t * value, int data_len_in_bytes)
Definition at line 83 of file px4muorb.cpp.
References param_value.
px4muorb_param_update_value_from_shmem()
int px4muorb_param_update_value_from_shmem (uint32_t param, const uint8_t * value, int data_len_in_bytes)
Definition at line 129 of file px4muorb.cpp.
References param_value.
px4muorb_receive_bulk_data()
int px4muorb_receive_bulk_data (uint8_t * _BulkTransferBuffer, int max_size_in_bytes, int * length_in_bytes, int * topic_count)
Definition at line 275 of file px4muorb.cpp.
References uORB::FastRpcChannel::get_bulk_data(), and uORB::FastRpcChannel::GetInstance().
Referenced by px4muorb::KraitRpcWrapper::ReceiveBulkData().
px4muorb_receive_msg()
int px4muorb_receive_msg (int * msg_type, char * topic_name, int topic_name_len, uint8_t * data, int data_len_in_bytes, int * bytes_returned)
Definition at line 260 of file px4muorb.cpp.
References uORB::FastRpcChannel::get_data(), and uORB::FastRpcChannel::GetInstance().
Referenced by px4muorb::KraitRpcWrapper::ReceiveData().
px4muorb_remove_subscriber()
int px4muorb_remove_subscriber (const char * name)
Definition at line 211 of file px4muorb.cpp.
References uORB::FastRpcChannel::GetInstance(), uORB::FastRpcChannel::GetRxHandler(), uORBCommunicator::IChannelRxHandler::process_remove_subscription(), and uORB::FastRpcChannel::RemoveRemoteSubscriber().
Referenced by px4muorb::KraitRpcWrapper::RemoveSubscriber().
px4muorb_send_topic_data()
int px4muorb_send_topic_data (const char * name, const uint8_t * data, int data_len_in_bytes)
Definition at line 228 of file px4muorb.cpp.
References uORB::FastRpcChannel::GetInstance(), uORB::FastRpcChannel::GetRxHandler(), and uORBCommunicator::IChannelRxHandler::process_received_message().
Referenced by px4muorb::KraitRpcWrapper::SendData().
px4muorb_set_absolute_time_offset()
int px4muorb_set_absolute_time_offset (int32_t time_diff_us)
Definition at line 71 of file px4muorb.cpp.
Referenced by px4muorb::KraitRpcWrapper::Initialize().
px4muorb_topic_advertised()
int px4muorb_topic_advertised (const char * name)
Definition at line 156 of file px4muorb.cpp.
References uORB::FastRpcChannel::GetInstance(), uORB::FastRpcChannel::GetRxHandler(), and uORBCommunicator::IChannelRxHandler::process_remote_topic().
Referenced by px4muorb::KraitRpcWrapper::TopicAdvertised().
px4muorb_topic_unadvertised()
int px4muorb_topic_unadvertised (const char * name)
Definition at line 173 of file px4muorb.cpp.
References uORB::FastRpcChannel::GetInstance(), uORB::FastRpcChannel::GetRxHandler(), and uORBCommunicator::IChannelRxHandler::process_remote_topic().
Referenced by px4muorb::KraitRpcWrapper::TopicUnadvertised().
px4muorb_unblock_recieve_msg()
int px4muorb_unblock_recieve_msg (void)
Definition at line 290 of file px4muorb.cpp.
References uORB::FastRpcChannel::GetInstance(), and uORB::FastRpcChannel::unblock_get_data_method().
Referenced by px4muorb::KraitRpcWrapper::UnblockReceiveData().