PX4 Firmware: src/drivers/boards/px4fmu-v4pro/spi.c File Reference
spi.c File Reference
#include <px4_config.h>
#include <stdint.h>
#include <stdbool.h>
#include <debug.h>
#include <unistd.h>
#include <nuttx/spi/spi.h>
#include <arch/board/board.h>
#include <up_arch.h>
#include <chip.h>
#include <stm32.h>
#include "board_config.h"
#include <systemlib/err.h>
Functions
__EXPORT void stm32_spiinitialize (void)
__EXPORT void stm32_spi1select (FAR struct spi_dev_s *dev, uint32_t devid, bool selected)
__EXPORT uint8_t stm32_spi1status (FAR struct spi_dev_s *dev, uint32_t devid)
__EXPORT void board_spi_reset (int ms)
Function Documentation
__EXPORT void board_spi_reset (int ms)
disable SPI bus 1 DRDY */
Definition at line 224 of file spi.c.
References GPIO_DRDY_ICM_2060X, GPIO_DRDY_LIS3MDL, GPIO_DRDY_MPU9250, GPIO_DRDY_OFF_ICM_2060X, GPIO_DRDY_OFF_LIS3MDL, GPIO_DRDY_OFF_MPU9250, GPIO_SPI1_MISO_OFF, GPIO_SPI1_MOSI_OFF, GPIO_SPI1_SCK_OFF, GPIO_SPI_CS_ICM_2060X, GPIO_SPI_CS_LIS3MDL, GPIO_SPI_CS_MPU9250, GPIO_SPI_CS_MS5611, GPIO_SPI_CS_OFF_ICM_2060X, GPIO_SPI_CS_OFF_LIS3MDL, GPIO_SPI_CS_OFF_MPU9250, GPIO_SPI_CS_OFF_MS5611, GPIO_SPI_CS_TEMPCAL_EEPROM, GPIO_VDD_3V3_SENSORS_EN, usleep(), and warnx.
__EXPORT void stm32_spi1select (FAR struct spi_dev_s * dev, uint32_t devid, bool selected)
Definition at line 98 of file spi.c.
References GPIO_SPI_CS_ICM_2060X, GPIO_SPI_CS_LIS3MDL, GPIO_SPI_CS_MPU9250, GPIO_SPI_CS_MS5611, GPIO_SPI_CS_TEMPCAL_EEPROM, PX4_SPIDEV_BARO, PX4_SPIDEV_EEPROM, PX4_SPIDEV_ICM, PX4_SPIDEV_ICM_20602, PX4_SPIDEV_ICM_20608, PX4_SPIDEV_LIS, and PX4_SPIDEV_MPU.
__EXPORT uint8_t stm32_spi1status (FAR struct spi_dev_s * dev, uint32_t devid)
Definition at line 163 of file spi.c.
References GPIO_SPI5_CS, GPIO_SPI6_CS, GPIO_SPI_CS_FRAM, stm32_spi2select(), stm32_spi2status(), stm32_spi5select(), stm32_spi5status(), stm32_spi6select(), and stm32_spi6status().
__EXPORT void stm32_spiinitialize (void)
Definition at line 72 of file spi.c.
References GPIO_DRDY_ICM_2060X, GPIO_DRDY_LIS3MDL, GPIO_DRDY_MPU9250, GPIO_SPI5_CS, GPIO_SPI6_CS, GPIO_SPI_CS_FRAM, GPIO_SPI_CS_ICM_2060X, GPIO_SPI_CS_LIS3MDL, GPIO_SPI_CS_MPU9250, GPIO_SPI_CS_MS5611, and GPIO_SPI_CS_TEMPCAL_EEPROM.