PX4 Firmware: BMI160 Class Reference
BMI160 Class Reference
#include <bmi160.hpp>
Classes
struct BMIReport
Report conversation within the BMI160, including command byte and interrupt status.
Public Member Functions
BMI160 (int bus, const char *path_accel, const char *path_gyro, uint32_t device, enum Rotation rotation)
virtual ~BMI160 ()
virtual int init ()
virtual ssize_t read (struct file *filp, char *buffer, size_t buflen)
virtual int ioctl (struct file *filp, int cmd, unsigned long arg)
void print_info ()
Diagnostics - print some basic information about the driver.
void print_registers ()
void test_error ()
Protected Member Functions
virtual int probe ()
virtual ssize_t gyro_read (struct file *filp, char *buffer, size_t buflen)
virtual int gyro_ioctl (struct file *filp, int cmd, unsigned long arg)
Private Member Functions
void start ()
Start automatic measurement.
void stop ()
Stop automatic measurement.
int reset ()
Reset chip.
void measure ()
Fetch measurements from the sensor and update the report buffers.
uint8_t read_reg (unsigned reg)
Read a register from the BMI160.
uint16_t read_reg16 (unsigned reg)
void write_reg (unsigned reg, uint8_t value)
Write a register in the BMI160.
void modify_reg (unsigned reg, uint8_t clearbits, uint8_t setbits)
Modify a register in the BMI160.
void write_checked_reg (unsigned reg, uint8_t value)
Write a register in the BMI160, updating _checked_values.
int set_accel_range (unsigned max_g)
Set the BMI160 measurement range.
int set_gyro_range (unsigned max_dps)
uint16_t swap16 (uint16_t val)
Swap a 16-bit value read from the BMI160 to native byte order.
int self_test ()
Measurement self test.
void _set_dlpf_filter (uint16_t frequency_hz)
int accel_set_sample_rate (float desired_sample_rate_hz)
int gyro_set_sample_rate (float desired_sample_rate_hz)
void check_registers (void)
BMI160 (const BMI160 &)
BMI160 operator= (const BMI160 &)
Static Private Member Functions
static void measure_trampoline (void *arg)
Static trampoline from the hrt_call context; because we don't have a generic hrt wrapper yet.
Private Attributes
BMI160_gyro * _gyro
uint8_t _whoami
struct hrt_call _call
whoami result
unsigned _call_interval
ringbuffer::RingBuffer * _accel_reports
struct accel_calibration_s _accel_scale
float _accel_range_scale
float _accel_range_m_s2
orb_advert_t _accel_topic
int _accel_orb_class_instance
int _accel_class_instance
ringbuffer::RingBuffer * _gyro_reports
struct gyro_calibration_s _gyro_scale
float _gyro_range_scale
float _gyro_range_rad_s
unsigned _dlpf_freq
float _accel_sample_rate
float _gyro_sample_rate
perf_counter_t _accel_reads
perf_counter_t _gyro_reads
perf_counter_t _sample_perf
perf_counter_t _bad_transfers
perf_counter_t _bad_registers
perf_counter_t _good_transfers
perf_counter_t _reset_retries
perf_counter_t _duplicates
uint8_t _register_wait
uint64_t _reset_wait
math::LowPassFilter2p _accel_filter_x
math::LowPassFilter2p _accel_filter_y
math::LowPassFilter2p _accel_filter_z
math::LowPassFilter2p _gyro_filter_x
math::LowPassFilter2p _gyro_filter_y
math::LowPassFilter2p _gyro_filter_z
Integrator _accel_int
Integrator _gyro_int
enum Rotation _rotation
uint8_t _checked_values [BMI160_NUM_CHECKED_REGISTERS]
uint8_t _checked_bad [BMI160_NUM_CHECKED_REGISTERS]
uint8_t _checked_next
float _last_temperature
uint16_t _last_accel [3]
bool _got_duplicate
Static Private Attributes
static const uint8_t _checked_registers [BMI160_NUM_CHECKED_REGISTERS]
Friends
class BMI160_gyro
Detailed Description
Definition at line 247 of file bmi160.hpp.
Constructor & Destructor Documentation
BMI160::BMI160 (int bus, const char * path_accel, const char * path_gyro, uint32_t device, enum Rotation rotation)
Definition at line 21 of file bmi160.cpp.
References _accel_class_instance, _accel_filter_x, _accel_filter_y, _accel_filter_z, _accel_int, _accel_orb_class_instance, _accel_range_m_s2, _accel_range_scale, _accel_reads, _accel_reports, _accel_sample_rate, _accel_scale, _accel_topic, _bad_registers, _bad_transfers, _call, _call_interval, _checked_next, device::Device::_device_id, _dlpf_freq, _duplicates, _good_transfers, _got_duplicate, _gyro, _gyro_filter_x, _gyro_filter_y, _gyro_filter_z, _gyro_int, _gyro_range_rad_s, _gyro_range_scale, _gyro_reads, _gyro_reports, _gyro_sample_rate, _gyro_scale, _last_accel, _last_temperature, _register_wait, _reset_retries, _reset_wait, _rotation, _sample_perf, BMI160_ACCEL_DEFAULT_DRIVER_FILTER_FREQ, BMI160_ACCEL_DEFAULT_RATE, BMI160_ACCEL_MAX_PUBLISH_RATE, BMI160_GYRO_DEFAULT_DRIVER_FILTER_FREQ, BMI160_GYRO_DEFAULT_RATE, BMI160_GYRO_MAX_PUBLISH_RATE, device::Device::DeviceId::devid, device::Device::DeviceId::devid_s, device::Device::DeviceStructure::devtype, DRV_ACC_DEVTYPE_BMI160, DRV_GYR_DEVTYPE_BMI160, f(), PC_COUNT, PC_ELAPSED, perf_alloc, accel_calibration_s::x_offset, gyro_calibration_s::x_offset, gyro_calibration_s::x_scale, accel_calibration_s::x_scale, gyro_calibration_s::y_offset, accel_calibration_s::y_offset, accel_calibration_s::y_scale, gyro_calibration_s::y_scale, accel_calibration_s::z_offset, gyro_calibration_s::z_offset, gyro_calibration_s::z_scale, and accel_calibration_s::z_scale.
Referenced by swap16().
BMI160::~BMI160 () virtual
Definition at line 94 of file bmi160.cpp.
References _accel_class_instance, _accel_reads, _accel_reports, _bad_registers, _bad_transfers, _duplicates, _good_transfers, _gyro, _gyro_reads, _gyro_reports, _reset_retries, _sample_perf, ACCEL_BASE_DEVICE_PATH, perf_free(), and stop().
BMI160::BMI160 (const BMI160 &) private
Member Function Documentation
void BMI160::_set_dlpf_filter (uint16_t frequency_hz) private
Definition at line 411 of file bmi160.cpp.
References _dlpf_freq.
Referenced by swap16().
int BMI160::accel_set_sample_rate (float desired_sample_rate_hz) private
Definition at line 293 of file bmi160.cpp.
References _accel_sample_rate, BMI_ACCEL_RATE_100, BMI_ACCEL_RATE_1600, BMI_ACCEL_RATE_200, BMI_ACCEL_RATE_25, BMI_ACCEL_RATE_25_16, BMI_ACCEL_RATE_25_2, BMI_ACCEL_RATE_25_32, BMI_ACCEL_RATE_25_4, BMI_ACCEL_RATE_25_8, BMI_ACCEL_RATE_400, BMI_ACCEL_RATE_50, BMI_ACCEL_RATE_800, BMIREG_ACC_CONF, modify_reg(), and OK.
Referenced by ioctl(), reset(), and swap16().
void BMI160::check_registers (void) private
Definition at line 933 of file bmi160.cpp.
References _bad_registers, _checked_bad, _checked_next, _checked_registers, _checked_values, _register_wait, _reset_wait, BMI160_NUM_CHECKED_REGISTERS, BMI160_SOFT_RESET, BMIREG_CMD, hrt_absolute_time(), perf_count(), read_reg(), and write_reg().
Referenced by measure(), and swap16().
int BMI160::gyro_ioctl (struct file * filp, int cmd, unsigned long arg) protected virtual
Definition at line 695 of file bmi160.cpp.
References _gyro_range_rad_s, _gyro_reports, _gyro_sample_rate, _gyro_scale, gyro_set_sample_rate(), GYROIOCGRANGE, GYROIOCGSAMPLERATE, GYROIOCGSCALE, GYROIOCSRANGE, GYROIOCSSAMPLERATE, GYROIOCSSCALE, ioctl(), M_PI_F, OK, SENSORIOCGPOLLRATE, SENSORIOCRESET, SENSORIOCSPOLLRATE, SENSORIOCSQUEUEDEPTH, and set_gyro_range().
Referenced by BMI160_gyro::ioctl().
ssize_t BMI160::gyro_read (struct file * filp, char * buffer, size_t buflen) protected virtual
Definition at line 507 of file bmi160.cpp.
References _call_interval, _gyro_reads, _gyro_reports, gyro_report, measure(), and perf_count().
Referenced by BMI160_gyro::read().
int BMI160::gyro_set_sample_rate (float desired_sample_rate_hz) private
Definition at line 360 of file bmi160.cpp.
References _gyro_sample_rate, BMI_GYRO_RATE_100, BMI_GYRO_RATE_1600, BMI_GYRO_RATE_200, BMI_GYRO_RATE_25, BMI_GYRO_RATE_3200, BMI_GYRO_RATE_400, BMI_GYRO_RATE_50, BMI_GYRO_RATE_800, BMIREG_GYR_CONF, modify_reg(), and OK.
Referenced by gyro_ioctl(), reset(), and swap16().
int BMI160::init () virtual
Definition at line 127 of file bmi160.cpp.
References _accel_class_instance, _accel_orb_class_instance, _accel_reports, _accel_scale, _accel_topic, _gyro, BMI160_gyro::_gyro_orb_class_instance, _gyro_reports, _gyro_scale, BMI160_gyro::_gyro_topic, ACCEL_BASE_DEVICE_PATH, accel_report, DEVICE_DEBUG, gyro_report, BMI160_gyro::init(), lis3mdl::init(), measure(), OK, orb_advertise_multi(), ORB_ID, ORB_PRIO_HIGH, ORB_PRIO_MAX, reset(), warnx, accel_calibration_s::x_offset, gyro_calibration_s::x_offset, gyro_calibration_s::x_scale, accel_calibration_s::x_scale, gyro_calibration_s::y_offset, accel_calibration_s::y_offset, accel_calibration_s::y_scale, gyro_calibration_s::y_scale, gyro_calibration_s::z_offset, accel_calibration_s::z_offset, gyro_calibration_s::z_scale, and accel_calibration_s::z_scale.
int BMI160::ioctl (struct file * filp, int cmd, unsigned long arg) virtual
Definition at line 548 of file bmi160.cpp.
References _accel_filter_x, _accel_filter_y, _accel_filter_z, _accel_range_m_s2, _accel_reports, _accel_sample_rate, _accel_scale, _call, _call_interval, _gyro_filter_x, _gyro_filter_y, _gyro_filter_z, accel_set_sample_rate(), ACCELIOCGRANGE, ACCELIOCGSAMPLERATE, ACCELIOCGSCALE, ACCELIOCSRANGE, ACCELIOCSSAMPLERATE, ACCELIOCSSCALE, BMI160_ACCEL_DEFAULT_RATE, BMI160_GYRO_DEFAULT_RATE, BMI160_GYRO_MAX_RATE, BMI160_TIMER_REDUCTION, CONSTANTS_ONE_G, f(), math::LowPassFilter2p::get_cutoff_freq(), OK, hrt_call::period, reset(), SENSOR_POLLRATE_DEFAULT, SENSOR_POLLRATE_EXTERNAL, SENSOR_POLLRATE_MANUAL, SENSOR_POLLRATE_MAX, SENSORIOCGPOLLRATE, SENSORIOCRESET, SENSORIOCSPOLLRATE, SENSORIOCSQUEUEDEPTH, set_accel_range(), math::LowPassFilter2p::set_cutoff_frequency(), start(), stop(), accel_calibration_s::x_scale, accel_calibration_s::y_scale, and accel_calibration_s::z_scale.
Referenced by gyro_ioctl().
void BMI160::measure () private
Fetch measurements from the sensor and update the report buffers.
Definition at line 976 of file bmi160.cpp.
References _accel_filter_x, _accel_filter_y, _accel_filter_z, _accel_int, _accel_range_scale, _accel_reports, _accel_scale, _accel_topic, _bad_registers, _bad_transfers, device::Device::_device_id, _duplicates, _good_transfers, _got_duplicate, _gyro, _gyro_filter_x, _gyro_filter_y, _gyro_filter_z, _gyro_int, _gyro_range_scale, _gyro_reports, _gyro_scale, BMI160_gyro::_gyro_topic, _last_accel, _last_temperature, _register_wait, _reset_wait, _rotation, _sample_perf, accel_report, BMI160::BMIReport::accel_x, BMI160::BMIReport::accel_y, BMI160::BMIReport::accel_z, math::LowPassFilter2p::apply(), BMIREG_GYR_X_L, BMIREG_STATUS, BMIREG_TEMP_0, BMIREG_TEMP_1, check_registers(), BMI160::BMIReport::cmd, device::Device::DeviceId::devid, DIR_READ, gyro_report, BMI160::BMIReport::gyro_x, BMI160::BMIReport::gyro_y, BMI160::BMIReport::gyro_z, hrt_absolute_time(), OK, ORB_ID, orb_publish(), BMI160_gyro::parent_poll_notify(), perf_begin(), perf_count(), perf_end(), perf_event_count(), Integrator::put(), read_reg(), rotate_3f(), status, accel_calibration_s::x_offset, gyro_calibration_s::x_offset, gyro_calibration_s::x_scale, accel_calibration_s::x_scale, gyro_calibration_s::y_offset, accel_calibration_s::y_offset, accel_calibration_s::y_scale, gyro_calibration_s::y_scale, accel_calibration_s::z_offset, gyro_calibration_s::z_offset, gyro_calibration_s::z_scale, and accel_calibration_s::z_scale.
Referenced by gyro_read(), init(), measure_trampoline(), read(), and self_test().
void BMI160::measure_trampoline (void * arg) static private
Static trampoline from the hrt_call context; because we don't have a generic hrt wrapper yet.
Called by the HRT in interrupt context at the specified rate if automatic polling is enabled.
Parameters
arg Instance pointer for the driver that is polling.
Definition at line 924 of file bmi160.cpp.
References measure().
Referenced by start().
void BMI160::modify_reg (unsigned reg, uint8_t clearbits, uint8_t setbits) private
Modify a register in the BMI160.
Bits are cleared before bits are set.
Parameters
reg The register to modify.
clearbits Bits in the register to clear.
setbits Bits in the register to set.
Definition at line 783 of file bmi160.cpp.
References read_reg(), and write_checked_reg().
Referenced by accel_set_sample_rate(), gyro_set_sample_rate(), set_accel_range(), and set_gyro_range().
BMI160 BMI160::operator= (const BMI160 &) private
Referenced by swap16().
void BMI160::print_info ()
Diagnostics - print some basic information about the driver.
Definition at line 1195 of file bmi160.cpp.
References _accel_reads, _accel_reports, _bad_registers, _bad_transfers, _checked_bad, _checked_next, _checked_registers, _checked_values, _duplicates, _good_transfers, _gyro_reads, _gyro_reports, _last_temperature, _reset_retries, _sample_perf, BMI160_NUM_CHECKED_REGISTERS, perf_print_counter(), and read_reg().
void BMI160::print_registers ()
Definition at line 1231 of file bmi160.cpp.
References read_reg().
Referenced by test_error().
int BMI160::probe () protected virtual
Definition at line 273 of file bmi160.cpp.
References _checked_bad, _checked_values, _whoami, BMI160_WHO_AM_I, BMIREG_CHIP_ID, DEVICE_DEBUG, OK, and read_reg().
ssize_t BMI160::read (struct file * filp, char * buffer, size_t buflen) virtual
Definition at line 445 of file bmi160.cpp.
References _accel_reads, _accel_reports, _call_interval, accel_report, measure(), and perf_count().
uint8_t BMI160::read_reg (unsigned reg) private
Read a register from the BMI160.
Parameters
The register to read.
Returns
The value that was read.
Definition at line 752 of file bmi160.cpp.
References DIR_READ.
Referenced by check_registers(), measure(), modify_reg(), print_info(), print_registers(), probe(), and reset().
uint16_t BMI160::read_reg16 (unsigned reg) private
Definition at line 762 of file bmi160.cpp.
References DIR_READ.
int BMI160::reset () private
Reset chip.
Resets the chip and measurements ranges, but not scale and offset.
Definition at line 215 of file bmi160.cpp.
References _accel_reads, _checked_registers, _checked_values, _gyro_reads, accel_set_sample_rate(), BMI160_ACCEL_DEFAULT_RANGE_G, BMI160_ACCEL_DEFAULT_RATE, BMI160_GYRO_DEFAULT_RANGE_DPS, BMI160_GYRO_DEFAULT_RATE, BMI160_NUM_CHECKED_REGISTERS, BMI_ACCEL_BWP_NORMAL, BMI_ACCEL_NORMAL_MODE, BMI_ACCEL_US, BMI_AUTO_DIS_SEC, BMI_DRDY_INT1, BMI_DRDY_INT_EN, BMI_GYRO_BWP_NORMAL, BMI_GYRO_NORMAL_MODE, BMI_INT1_EN, BMI_SPI, BMI_SPI_4_WIRE, BMIREG_ACC_CONF, BMIREG_ACC_RANGE, BMIREG_CMD, BMIREG_CONF, BMIREG_GYR_CONF, BMIREG_GYR_RANGE, BMIREG_IF_CONF, BMIREG_INT_EN_1, BMIREG_INT_MAP_1, BMIREG_INT_OUT_CTRL, BMIREG_NV_CONF, gyro_set_sample_rate(), OK, read_reg(), set_accel_range(), set_gyro_range(), write_checked_reg(), and write_reg().
Referenced by init(), ioctl(), and start().
int BMI160::self_test () private
Measurement self test.
Returns
0 on success, 1 on failure
Definition at line 485 of file bmi160.cpp.
References _sample_perf, measure(), and perf_event_count().
Referenced by swap16().
int BMI160::set_accel_range (unsigned max_g) private
Set the BMI160 measurement range.
Parameters
max_g The maximum G value the range must support.
max_dps The maximum DPS value the range must support.
Returns
OK if the value can be supported, -ERANGE otherwise.
Definition at line 807 of file bmi160.cpp.
References _accel_range_m_s2, _accel_range_scale, BMI_ACCEL_RANGE_16_G, BMI_ACCEL_RANGE_2_G, BMI_ACCEL_RANGE_4_G, BMI_ACCEL_RANGE_8_G, BMIREG_ACC_RANGE, CONSTANTS_ONE_G, modify_reg(), and OK.
Referenced by ioctl(), and reset().
int BMI160::set_gyro_range (unsigned max_dps) private
Definition at line 851 of file bmi160.cpp.
References _gyro_range_rad_s, _gyro_range_scale, BMI_GYRO_RANGE_1000_DPS, BMI_GYRO_RANGE_125_DPS, BMI_GYRO_RANGE_2000_DPS, BMI_GYRO_RANGE_250_DPS, BMI_GYRO_RANGE_500_DPS, BMIREG_GYR_RANGE, M_PI_F, modify_reg(), and OK.
Referenced by gyro_ioctl(), and reset().
void BMI160::start () private
Start automatic measurement.
Definition at line 900 of file bmi160.cpp.
References _accel_reports, _call, _call_interval, _gyro_reports, BMI160_TIMER_REDUCTION, hrt_call_every(), measure_trampoline(), reset(), and stop().
Referenced by ioctl().
void BMI160::stop () private
Stop automatic measurement.
Definition at line 918 of file bmi160.cpp.
References _call, and hrt_cancel().
Referenced by ioctl(), start(), and ~BMI160().
uint16_t BMI160::swap16 (uint16_t val) inline private
Swap a 16-bit value read from the BMI160 to native byte order.
Definition at line 424 of file bmi160.hpp.
References _set_dlpf_filter(), accel_set_sample_rate(), BMI160(), check_registers(), gyro_set_sample_rate(), operator=(), and self_test().
void BMI160::test_error ()
Definition at line 499 of file bmi160.cpp.
References BMI160_SOFT_RESET, BMIREG_CMD, print_registers(), and write_reg().
void BMI160::write_checked_reg (unsigned reg, uint8_t value) private
Write a register in the BMI160, updating _checked_values.
Parameters
reg The register to write.
value The new value to write.
Definition at line 794 of file bmi160.cpp.
References _checked_bad, _checked_registers, _checked_values, BMI160_NUM_CHECKED_REGISTERS, and write_reg().
Referenced by modify_reg(), and reset().
void BMI160::write_reg (unsigned reg, uint8_t value) private
Write a register in the BMI160.
Parameters
reg The register to write.
value The new value to write.
Definition at line 772 of file bmi160.cpp.
References DIR_WRITE.
Referenced by check_registers(), reset(), test_error(), and write_checked_reg().
Friends And Related Function Documentation
friend class BMI160_gyro friend
Definition at line 271 of file bmi160.hpp.
Member Data Documentation
int BMI160::_accel_class_instance private
Definition at line 290 of file bmi160.hpp.
Referenced by BMI160(), init(), and ~BMI160().
math::LowPassFilter2p BMI160::_accel_filter_x private
Definition at line 314 of file bmi160.hpp.
Referenced by BMI160(), ioctl(), and measure().
math::LowPassFilter2p BMI160::_accel_filter_y private
Definition at line 315 of file bmi160.hpp.
Referenced by BMI160(), ioctl(), and measure().
math::LowPassFilter2p BMI160::_accel_filter_z private
Definition at line 316 of file bmi160.hpp.
Referenced by BMI160(), ioctl(), and measure().
Integrator BMI160::_accel_int private
Definition at line 321 of file bmi160.hpp.
Referenced by BMI160(), and measure().
int BMI160::_accel_orb_class_instance private
Definition at line 289 of file bmi160.hpp.
Referenced by BMI160(), and init().
float BMI160::_accel_range_m_s2 private
Definition at line 287 of file bmi160.hpp.
Referenced by BMI160(), ioctl(), and set_accel_range().
float BMI160::_accel_range_scale private
Definition at line 286 of file bmi160.hpp.
Referenced by BMI160(), measure(), and set_accel_range().
perf_counter_t BMI160::_accel_reads private
Definition at line 302 of file bmi160.hpp.
Referenced by BMI160(), print_info(), read(), reset(), and ~BMI160().
ringbuffer::RingBuffer* BMI160::_accel_reports private
Definition at line 283 of file bmi160.hpp.
Referenced by BMI160(), init(), ioctl(), measure(), print_info(), read(), start(), and ~BMI160().
float BMI160::_accel_sample_rate private
Definition at line 300 of file bmi160.hpp.
Referenced by accel_set_sample_rate(), BMI160(), and ioctl().
struct accel_calibration_s BMI160::_accel_scale private
Definition at line 285 of file bmi160.hpp.
Referenced by BMI160(), init(), ioctl(), and measure().
orb_advert_t BMI160::_accel_topic private
Definition at line 288 of file bmi160.hpp.
Referenced by BMI160(), init(), and measure().
perf_counter_t BMI160::_bad_registers private
Definition at line 306 of file bmi160.hpp.
Referenced by BMI160(), check_registers(), measure(), print_info(), and ~BMI160().
perf_counter_t BMI160::_bad_transfers private
Definition at line 305 of file bmi160.hpp.
Referenced by BMI160(), measure(), print_info(), and ~BMI160().
struct hrt_call BMI160::_call private
whoami result
Definition at line 280 of file bmi160.hpp.
Referenced by BMI160(), ioctl(), start(), and stop().
unsigned BMI160::_call_interval private
Definition at line 281 of file bmi160.hpp.
Referenced by BMI160(), gyro_read(), ioctl(), read(), and start().
uint8_t BMI160::_checked_bad[BMI160_NUM_CHECKED_REGISTERS] private
Definition at line 332 of file bmi160.hpp.
Referenced by check_registers(), print_info(), probe(), and write_checked_reg().
uint8_t BMI160::_checked_next private
Definition at line 333 of file bmi160.hpp.
Referenced by BMI160(), check_registers(), and print_info().
const uint8_t BMI160::_checked_registers static private
Initial value:
= {    BMIREG_CHIP_ID,
                                          BMIREG_ACC_CONF,
                                          BMIREG_ACC_RANGE,
                                          BMIREG_GYR_CONF,
                                          BMIREG_GYR_RANGE,
                                          BMIREG_INT_EN_1,
                                          BMIREG_INT_OUT_CTRL,
                                          BMIREG_INT_MAP_1,
                                          BMIREG_IF_CONF,
                                          BMIREG_NV_CONF
                                     }
Definition at line 330 of file bmi160.hpp.
Referenced by check_registers(), print_info(), reset(), and write_checked_reg().
uint8_t BMI160::_checked_values[BMI160_NUM_CHECKED_REGISTERS] private
Definition at line 331 of file bmi160.hpp.
Referenced by check_registers(), print_info(), probe(), reset(), and write_checked_reg().
unsigned BMI160::_dlpf_freq private
Definition at line 298 of file bmi160.hpp.
Referenced by _set_dlpf_filter(), and BMI160().
perf_counter_t BMI160::_duplicates private
Definition at line 309 of file bmi160.hpp.
Referenced by BMI160(), measure(), print_info(), and ~BMI160().
perf_counter_t BMI160::_good_transfers private
Definition at line 307 of file bmi160.hpp.
Referenced by BMI160(), measure(), print_info(), and ~BMI160().
bool BMI160::_got_duplicate private
Definition at line 340 of file bmi160.hpp.
Referenced by BMI160(), and measure().
BMI160_gyro* BMI160::_gyro private
Definition at line 277 of file bmi160.hpp.
Referenced by BMI160(), init(), measure(), and ~BMI160().
math::LowPassFilter2p BMI160::_gyro_filter_x private
Definition at line 317 of file bmi160.hpp.
Referenced by BMI160(), ioctl(), and measure().
math::LowPassFilter2p BMI160::_gyro_filter_y private
Definition at line 318 of file bmi160.hpp.
Referenced by BMI160(), ioctl(), and measure().
math::LowPassFilter2p BMI160::_gyro_filter_z private
Definition at line 319 of file bmi160.hpp.
Referenced by BMI160(), ioctl(), and measure().
Integrator BMI160::_gyro_int private
Definition at line 322 of file bmi160.hpp.
Referenced by BMI160(), and measure().
float BMI160::_gyro_range_rad_s private
Definition at line 296 of file bmi160.hpp.
Referenced by BMI160(), gyro_ioctl(), and set_gyro_range().
float BMI160::_gyro_range_scale private
Definition at line 295 of file bmi160.hpp.
Referenced by BMI160(), measure(), and set_gyro_range().
perf_counter_t BMI160::_gyro_reads private
Definition at line 303 of file bmi160.hpp.
Referenced by BMI160(), gyro_read(), print_info(), reset(), and ~BMI160().
ringbuffer::RingBuffer* BMI160::_gyro_reports private
Definition at line 292 of file bmi160.hpp.
Referenced by BMI160(), gyro_ioctl(), gyro_read(), init(), measure(), print_info(), start(), and ~BMI160().
float BMI160::_gyro_sample_rate private
Definition at line 301 of file bmi160.hpp.
Referenced by BMI160(), gyro_ioctl(), and gyro_set_sample_rate().
struct gyro_calibration_s BMI160::_gyro_scale private
Definition at line 294 of file bmi160.hpp.
Referenced by BMI160(), gyro_ioctl(), init(), and measure().
uint16_t BMI160::_last_accel[3] private
Definition at line 339 of file bmi160.hpp.
Referenced by BMI160(), and measure().
float BMI160::_last_temperature private
Definition at line 336 of file bmi160.hpp.
Referenced by BMI160(), measure(), and print_info().
uint8_t BMI160::_register_wait private
Definition at line 311 of file bmi160.hpp.
Referenced by BMI160(), check_registers(), and measure().
perf_counter_t BMI160::_reset_retries private
Definition at line 308 of file bmi160.hpp.
Referenced by BMI160(), print_info(), and ~BMI160().
uint64_t BMI160::_reset_wait private
Definition at line 312 of file bmi160.hpp.
Referenced by BMI160(), check_registers(), and measure().
enum Rotation BMI160::_rotation private
Definition at line 324 of file bmi160.hpp.
Referenced by BMI160(), and measure().
perf_counter_t BMI160::_sample_perf private
Definition at line 304 of file bmi160.hpp.
Referenced by BMI160(), measure(), print_info(), self_test(), and ~BMI160().
uint8_t BMI160::_whoami private
Definition at line 278 of file bmi160.hpp.
Referenced by probe().
The documentation for this class was generated from the following files:
src/drivers/imu/bmi160/bmi160.hpp
src/drivers/imu/bmi160/bmi160.cpp