PX4 Firmware: uORB::PublicationQueued< T > Class Template Reference
uORB::PublicationQueued< T > Class Template Reference
Queued publication with queue length set as a message constant (ORB_QUEUE_LENGTH)
#include <PublicationQueued.hpp>
Public Member Functions
PublicationQueued (const orb_metadata *meta)
Constructor.
~PublicationQueued ()
bool publish (const T &data)
Publish the struct.
Protected Attributes
const orb_metadata * _meta
orb_advert_t _handle {nullptr}
Detailed Description
template<typename T>
class uORB::PublicationQueued< T >
Queued publication with queue length set as a message constant (ORB_QUEUE_LENGTH)
Definition at line 52 of file PublicationQueued.hpp.
Constructor & Destructor Documentation
PublicationQueued()
template<typename T> uORB::PublicationQueued< T >::PublicationQueued (const orb_metadata * meta) inline
Constructor.
Parameters
meta The uORB metadata (usually from the ORB_ID() macro) for the topic.
Definition at line 61 of file PublicationQueued.hpp.
~PublicationQueued()
template<typename T> uORB::PublicationQueued< T >::~PublicationQueued () inline
Definition at line 62 of file PublicationQueued.hpp.
Member Function Documentation
publish()
template<typename T> bool uORB::PublicationQueued< T >::publish (const T & data) inline
Publish the struct.
Parameters
data The uORB message struct we are updating.
Definition at line 71 of file PublicationQueued.hpp.
Referenced by ObstacleAvoidance::_publishVehicleCmdDoLoiter(), CollisionPrevention::_publishVehicleCmdDoLoiter(), FlightTasks::_updateCommand(), MavlinkReceiver::acknowledge(), answer_command(), sensors::VotedSensorsUpdate::checkFailover(), GPS::dumpGpsData(), MavlinkParametersManager::handle_message(), MavlinkReceiver::handle_message_adsb_vehicle(), MavlinkReceiver::handle_message_command_ack(), MavlinkReceiver::handle_message_command_both(), MavlinkReceiver::handle_message_gps_rtcm_data(), MavlinkReceiver::handle_message_set_mode(), MavlinkReceiver::handle_message_utm_global_position(), GPS::initializeCommunicationDump(), events::status::StatusDisplay::publish(), TemperatureCalibration::publish_led_control(), px4::logger::LogWriterMavlink::publish_message(), IridiumSBD::publish_subsystem_status(), Mavlink::publish_telemetry_status(), Navigator::publish_vehicle_cmd(), Navigator::publish_vehicle_command_ack(), MavlinkParametersManager::request_next_uavcan_parameter(), CameraCapture::Run(), UavcanServers::run(), CameraTrigger::Run(), MulticopterPositionControl::send_vehicle_cmd_do(), and vmount::OutputMavlink::update().
Member Data Documentation
_handle
template<typename T> orb_advert_t uORB::PublicationQueued< T >::_handle {nullptr} protected
Definition at line 91 of file PublicationQueued.hpp.
Referenced by uORB::PublicationQueued< vehicle_command_s >::publish().
_meta
template<typename T> const orb_metadata* uORB::PublicationQueued< T >::_meta protected
Definition at line 89 of file PublicationQueued.hpp.
Referenced by uORB::PublicationQueued< vehicle_command_s >::publish().
The documentation for this class was generated from the following file:
src/modules/uORB/PublicationQueued.hpp