PX4 Firmware: src/lib/flight_tasks/tasks/Utility/ObstacleAvoidanceTest.cpp File Reference
ObstacleAvoidanceTest.cpp File Reference
#include <gtest/gtest.h>
#include <ObstacleAvoidance.hpp>
#include <uORB/Subscription.hpp>
Classes
class ObstacleAvoidanceTest
class TestObstacleAvoidance
Functions
TEST_F (ObstacleAvoidanceTest, instantiation)
TEST_F (ObstacleAvoidanceTest, oa_enabled_healthy)
TEST_F (ObstacleAvoidanceTest, oa_enabled_not_healthy)
TEST_F (ObstacleAvoidanceTest, oa_desired)
Function Documentation
TEST_F() [1/4]
TEST_F (ObstacleAvoidanceTest , instantiation)
Definition at line 66 of file ObstacleAvoidanceTest.cpp.
TEST_F() [2/4]
TEST_F (ObstacleAvoidanceTest , oa_enabled_healthy)
Definition at line 68 of file ObstacleAvoidanceTest.cpp.
References empty_trajectory_waypoint, hrt_absolute_time(), ObstacleAvoidance::injectAvoidanceSetpoints(), vehicle_status_s::nav_state, ORB_ID, trajectory_waypoint_s::point_valid, trajectory_waypoint_s::position, vehicle_trajectory_waypoint_s::timestamp, vehicle_trajectory_waypoint_s::type, vehicle_trajectory_waypoint_s::waypoints, and trajectory_waypoint_s::yaw.
TEST_F() [3/4]
TEST_F (ObstacleAvoidanceTest , oa_enabled_not_healthy)
Definition at line 104 of file ObstacleAvoidanceTest.cpp.
References empty_trajectory_waypoint, f(), ObstacleAvoidance::injectAvoidanceSetpoints(), vehicle_status_s::nav_state, ORB_ID, and TestObstacleAvoidance::test_setPosition().
TEST_F() [4/4]
TEST_F (ObstacleAvoidanceTest , oa_desired)
Definition at line 134 of file ObstacleAvoidanceTest.cpp.
References f(), ORB_ID, ObstacleAvoidance::updateAvoidanceDesiredSetpoints(), and ObstacleAvoidance::updateAvoidanceDesiredWaypoints().