PX4 Firmware: TEST_PPM Class Reference
TEST_PPM Class Reference
Public Member Functions
TEST_PPM (unsigned channels)
virtual ~TEST_PPM (void)
virtual int init ()
Public Attributes
unsigned _values [20]
unsigned _gaps [20]
unsigned _channels
unsigned _plus_width
Private Member Functions
void start ()
void stop ()
void do_out ()
Static Private Member Functions
static void loops (void *arg)
Private Attributes
struct hrt_call _call
unsigned _call_times
Detailed Description
Definition at line 68 of file test_ppm.cpp.
Constructor & Destructor Documentation
TEST_PPM()
TEST_PPM::TEST_PPM (unsigned channels)
Definition at line 96 of file test_ppm.cpp.
References _call, _call_times, and _values.
Referenced by test_ppm::start().
~TEST_PPM()
TEST_PPM::~TEST_PPM (void) virtual
Definition at line 111 of file test_ppm.cpp.
References stop().
Member Function Documentation
do_out()
void TEST_PPM::do_out (void) private
Definition at line 147 of file test_ppm.cpp.
References _call, _call_times, _channels, _plus_width, _values, hrt_call_after(), loops(), and TEST_PPM_PIN.
Referenced by loops().
init()
int TEST_PPM::init () virtual
Definition at line 118 of file test_ppm.cpp.
References OK, start(), and TEST_PPM_PIN.
Referenced by test_ppm::start().
loops()
void TEST_PPM::loops (void * arg) static private
Definition at line 141 of file test_ppm.cpp.
References hrt_call::arg, and do_out().
Referenced by do_out(), and start().
start()
void TEST_PPM::start () private
Definition at line 127 of file test_ppm.cpp.
References _call, _call_times, hrt_call_after(), loops(), and stop().
Referenced by init().
stop()
void TEST_PPM::stop () private
Definition at line 135 of file test_ppm.cpp.
References _call, and hrt_cancel().
Referenced by start(), and ~TEST_PPM().
Member Data Documentation
_call
struct hrt_call TEST_PPM::_call private
Definition at line 81 of file test_ppm.cpp.
Referenced by do_out(), start(), stop(), and TEST_PPM().
_call_times
unsigned TEST_PPM::_call_times private
Definition at line 82 of file test_ppm.cpp.
Referenced by do_out(), start(), and TEST_PPM().
_channels
unsigned TEST_PPM::_channels
Definition at line 76 of file test_ppm.cpp.
Referenced by do_out(), and test_ppm::set().
_gaps
unsigned TEST_PPM::_gaps[20]
Definition at line 75 of file test_ppm.cpp.
Referenced by test_ppm::set().
_plus_width
unsigned TEST_PPM::_plus_width
Definition at line 77 of file test_ppm.cpp.
Referenced by do_out().
_values
unsigned TEST_PPM::_values[20]
Definition at line 74 of file test_ppm.cpp.
Referenced by do_out(), test_ppm::set(), and TEST_PPM().
The documentation for this class was generated from the following file:
src/drivers/test_ppm/test_ppm.cpp