PX4 Firmware: src/lib/controllib/controllib_test/controllib_test_main.cpp File Reference
controllib_test_main.cpp File Reference
Unit testing for controllib.
#include <math.h>
#include <stdio.h>
#include <float.h>
#include <controllib/blocks.hpp>
Macros
#define ASSERT_CL(T) if (!(T)) { printf("FAIL\n"); return -1; }
Functions
int basicBlocksTest ()
int blockLimitTest ()
int blockLimitSymTest ()
int blockLowPassTest ()
int blockHighPassTest ()
int blockLowPass2Test ()
int blockIntegralTest ()
int blockIntegralTrapTest ()
int blockDerivativeTest ()
int blockPTest ()
int blockPITest ()
int blockPDTest ()
int blockPIDTest ()
int blockOutputTest ()
int blockRandUniformTest ()
int blockRandGaussTest ()
int blockStatsTest ()
int blockDelayTest ()
__EXPORT int controllib_test_main (int argc, char *argv[])
Detailed Description
Unit testing for controllib.
Author
James Goppert james.nosp@m..gop.nosp@m.pert@.nosp@m.gmai.nosp@m.l.com
Definition in file controllib_test_main.cpp.
Macro Definition Documentation
ASSERT_CL
#define ASSERT_CL (T) if (!(T)) { printf("FAIL\n"); return -1; }
Definition at line 49 of file controllib_test_main.cpp.
Referenced by blockDelayTest(), blockDerivativeTest(), blockHighPassTest(), blockIntegralTest(), blockIntegralTrapTest(), blockLimitSymTest(), blockLimitTest(), blockLowPass2Test(), blockLowPassTest(), blockOutputTest(), blockPDTest(), blockPIDTest(), blockPITest(), blockPTest(), blockRandGaussTest(), blockRandUniformTest(), and blockStatsTest().
Function Documentation
basicBlocksTest()
int basicBlocksTest ()
Definition at line 70 of file controllib_test_main.cpp.
References control::blockDelayTest(), control::blockDerivativeTest(), control::blockHighPassTest(), control::blockIntegralTest(), control::blockIntegralTrapTest(), control::blockLimitSymTest(), control::blockLimitTest(), control::blockLowPass2Test(), control::blockLowPassTest(), control::blockOutputTest(), control::blockPDTest(), control::blockPIDTest(), control::blockPITest(), control::blockPTest(), control::blockRandGaussTest(), control::blockRandUniformTest(), and control::blockStatsTest().
blockDelayTest()
int blockDelayTest ()
Definition at line 502 of file controllib_test_main.cpp.
References ASSERT_CL, controllib_test_main(), equal(), and control::BlockDelay< Type, M, N, LEN >::update().
blockDerivativeTest()
int blockDerivativeTest ()
Definition at line 291 of file controllib_test_main.cpp.
References ASSERT_CL, equal(), f(), control::Block::getDt(), control::BlockDerivative::getLP(), control::BlockDerivative::getU(), control::SuperBlock::setDt(), control::BlockDerivative::setU(), and control::BlockDerivative::update().
blockHighPassTest()
int blockHighPassTest ()
Definition at line 152 of file controllib_test_main.cpp.
References ASSERT_CL, equal(), f(), control::Block::getDt(), control::BlockHighPass::getFCut(), control::BlockHighPass::getU(), control::BlockHighPass::getY(), control::Block::setDt(), control::BlockHighPass::setU(), control::BlockHighPass::setY(), and control::BlockHighPass::update().
blockIntegralTest()
int blockIntegralTest ()
Definition at line 211 of file controllib_test_main.cpp.
References ASSERT_CL, equal(), f(), control::Block::getDt(), control::BlockIntegral::getMax(), control::BlockIntegral::getY(), control::SuperBlock::setDt(), control::BlockIntegral::setY(), and control::BlockIntegral::update().
blockIntegralTrapTest()
int blockIntegralTrapTest ()
Definition at line 248 of file controllib_test_main.cpp.
References ASSERT_CL, equal(), f(), control::Block::getDt(), control::BlockIntegralTrap::getMax(), control::BlockIntegralTrap::getU(), control::BlockIntegralTrap::getY(), control::SuperBlock::setDt(), control::BlockIntegralTrap::setU(), control::BlockIntegralTrap::setY(), and control::BlockIntegralTrap::update().
blockLimitSymTest()
int blockLimitSymTest ()
Definition at line 109 of file controllib_test_main.cpp.
References ASSERT_CL, equal(), f(), control::Block::getDt(), control::BlockLimitSym::getMax(), and control::BlockLimitSym::update().
blockLimitTest()
int blockLimitTest ()
Definition at line 93 of file controllib_test_main.cpp.
References ASSERT_CL, equal(), f(), control::Block::getDt(), control::BlockLimit::getMax(), control::BlockLimit::getMin(), and control::BlockLimit::update().
blockLowPass2Test()
int blockLowPass2Test ()
Definition at line 183 of file controllib_test_main.cpp.
References ASSERT_CL, equal(), f(), control::Block::getDt(), control::BlockLowPass2::getFCutParam(), control::BlockLowPass2::getState(), control::Block::setDt(), control::BlockLowPass2::setState(), and control::BlockLowPass2::update().
blockLowPassTest()
int blockLowPassTest ()
Definition at line 124 of file controllib_test_main.cpp.
References ASSERT_CL, equal(), f(), control::Block::getDt(), control::BlockLowPass::getFCut(), control::BlockLowPass::getState(), control::Block::setDt(), control::BlockLowPass::setState(), and control::BlockLowPass::update().
blockOutputTest()
int blockOutputTest ()
Definition at line 407 of file controllib_test_main.cpp.
References ASSERT_CL, equal(), f(), control::BlockOutput::get(), control::Block::getDt(), control::BlockOutput::getMax(), control::BlockOutput::getMin(), and control::BlockOutput::update().
blockPDTest()
int blockPDTest ()
Definition at line 352 of file controllib_test_main.cpp.
References ASSERT_CL, equal(), f(), control::BlockPD::getDerivative(), control::Block::getDt(), control::BlockPD::getKD(), control::BlockPD::getKP(), control::BlockDerivative::getLP(), control::BlockDerivative::getU(), control::SuperBlock::setDt(), control::BlockDerivative::setU(), control::BlockPD::update(), and control::BlockDerivative::update().
blockPIDTest()
int blockPIDTest ()
Definition at line 377 of file controllib_test_main.cpp.
References ASSERT_CL, equal(), f(), control::BlockPID::getDerivative(), control::Block::getDt(), control::BlockPID::getIntegral(), control::BlockPID::getKD(), control::BlockPID::getKI(), control::BlockPID::getKP(), control::BlockDerivative::getLP(), control::BlockIntegral::getMax(), control::BlockDerivative::getU(), control::BlockIntegral::getY(), control::SuperBlock::setDt(), control::BlockDerivative::setU(), control::BlockIntegral::setY(), control::BlockPID::update(), and control::BlockDerivative::update().
blockPITest()
int blockPITest ()
Definition at line 330 of file controllib_test_main.cpp.
References ASSERT_CL, equal(), f(), control::Block::getDt(), control::BlockPI::getIntegral(), control::BlockPI::getKI(), control::BlockPI::getKP(), control::BlockIntegral::getMax(), control::BlockIntegral::getY(), control::SuperBlock::setDt(), control::BlockIntegral::setY(), and control::BlockPI::update().
blockPTest()
int blockPTest ()
Definition at line 314 of file controllib_test_main.cpp.
References ASSERT_CL, equal(), f(), control::Block::getDt(), control::BlockP::getKP(), control::Block::setDt(), and control::BlockP::update().
blockRandGaussTest()
int blockRandGaussTest ()
Definition at line 455 of file controllib_test_main.cpp.
References ASSERT_CL, equal(), f(), control::Block::getDt(), control::BlockRandGauss::getMean(), control::BlockRandGauss::getStdDev(), and control::BlockRandGauss::update().
blockRandUniformTest()
int blockRandUniformTest ()
Definition at line 429 of file controllib_test_main.cpp.
References ASSERT_CL, equal(), f(), control::Block::getDt(), control::BlockRandUniform::getMax(), control::BlockRandUniform::getMin(), greater_than_or_equal(), less_than_or_equal(), and control::BlockRandUniform::update().
blockStatsTest()
int blockStatsTest ()
Definition at line 485 of file controllib_test_main.cpp.
References ASSERT_CL, equal(), f(), control::BlockStats< Type, M >::getMean(), control::BlockStats< Type, M >::getStdDev(), control::BlockStats< Type, M >::reset(), and control::BlockStats< Type, M >::update().
controllib_test_main()
int controllib_test_main (int argc, char * argv[])
Definition at line 532 of file controllib_test_main.cpp.
References control::basicBlocksTest().
Referenced by blockDelayTest().