PX4 Firmware: src/systemcmds/tests/test_matrix.cpp File Reference
test_matrix.cpp File Reference
Tests for the PX4 matrix math library.
#include <unit_test.h>
#include <matrix/math.hpp>
#include <matrix/filter.hpp>
#include <matrix/integration.hpp>
#include <matrix/Quaternion.hpp>
Classes
class MatrixTest
Functions
Vector< float, 6 > f (float t, const Matrix< float, 6, 1 > &y, const Matrix< float, 3, 1 > &u)
Detailed Description
Tests for the PX4 matrix math library.
Definition in file test_matrix.cpp.
Function Documentation
f()
Vector<float, 6> f (float t, const Matrix< float, 6, 1 > & y, const Matrix< float, 3, 1 > & u)
Definition at line 372 of file test_matrix.cpp.
Referenced by MatrixTest::dcmRenormTests(), MatrixTest::helperTests(), MatrixTest::matrixAssignmentTests(), MatrixTest::run_tests(), MatrixTest::vector2Tests(), MatrixTest::vector3Tests(), and MatrixTest::vectorAssignmentTests().