PX4 Firmware: MicroBenchORB Namespace Reference
MicroBenchORB Namespace Reference
Classes
class MicroBenchORB
Functions
void lock ()
void unlock ()
template<typename T >
T random (T min, T max)
ut_declare_test_c (test_microbench_uorb, MicroBenchORB) bool MicroBenchORB
Function Documentation
lock()
void MicroBenchORB::lock ()
Definition at line 64 of file test_microbench_uorb.cpp.
random()
template<typename T > T MicroBenchORB::random (T min, T max)
Definition at line 120 of file test_microbench_uorb.cpp.
References math::min().
unlock()
void MicroBenchORB::unlock ()
Definition at line 71 of file test_microbench_uorb.cpp.
ut_declare_test_c()
MicroBenchORB::ut_declare_test_c (test_microbench_uorb , MicroBenchORB)
Definition at line 140 of file test_microbench_uorb.cpp.
References orb_check(), orb_copy(), orb_exists(), ORB_ID, orb_stat(), orb_subscribe(), orb_unsubscribe(), PERF, and status.