PX4 Firmware: src/lib/mathlib/math/test/test.cpp File Reference
test.cpp File Reference
Test library code.
#include <stdio.h>
#include <math.h>
#include <stdlib.h>
#include <px4_platform_common/defines.h>
#include "test.hpp"
Functions
bool __EXPORT equal (float a, float b, float epsilon)
bool __EXPORT greater_than (float a, float b)
bool __EXPORT less_than (float a, float b)
bool __EXPORT greater_than_or_equal (float a, float b)
bool __EXPORT less_than_or_equal (float a, float b)
void __EXPORT float2SigExp (const float &num, float &sig, int &exp)
Detailed Description
Test library code.
Definition in file test.cpp.
Function Documentation
equal()
bool __EXPORT equal (float a, float b, float epsilon)
Definition at line 48 of file test.cpp.
Referenced by control::blockDelayTest(), blockDelayTest(), control::blockDerivativeTest(), blockDerivativeTest(), control::blockHighPassTest(), blockHighPassTest(), blockIntegralTest(), control::blockIntegralTest(), blockIntegralTrapTest(), control::blockIntegralTrapTest(), control::blockLimitSymTest(), blockLimitSymTest(), control::blockLimitTest(), blockLimitTest(), control::blockLowPass2Test(), blockLowPass2Test(), blockLowPassTest(), control::blockLowPassTest(), control::blockOutputTest(), blockOutputTest(), control::blockPDTest(), blockPDTest(), blockPIDTest(), control::blockPIDTest(), control::blockPITest(), blockPITest(), control::blockPTest(), blockPTest(), blockRandGaussTest(), control::blockRandGaussTest(), blockRandUniformTest(), control::blockRandUniformTest(), control::blockStatsTest(), and blockStatsTest().
float2SigExp()
void __EXPORT float2SigExp (const float & num, float & sig, int & exp)
Definition at line 103 of file test.cpp.
References matrix::abs(), matrix::ceil(), f(), and matrix::floor().
greater_than()
bool __EXPORT greater_than (float a, float b)
Definition at line 59 of file test.cpp.
greater_than_or_equal()
bool __EXPORT greater_than_or_equal (float a, float b)
Definition at line 81 of file test.cpp.
Referenced by control::blockRandUniformTest(), and blockRandUniformTest().
less_than()
bool __EXPORT less_than (float a, float b)
Definition at line 70 of file test.cpp.
less_than_or_equal()
bool __EXPORT less_than_or_equal (float a, float b)
Definition at line 92 of file test.cpp.
Referenced by control::blockRandUniformTest(), and blockRandUniformTest().