PX4 Firmware: math::trajectory Namespace Reference
math::trajectory Namespace Reference
Functions
float computeMaxSpeedFromDistance (const float jerk, const float accel, const float braking_distance, const float final_speed)
float computeMaxSpeedInWaypoint (const float alpha, const float accel, const float d)
Function Documentation
computeMaxSpeedFromDistance()
float math::trajectory::computeMaxSpeedFromDistance (const float jerk, const float accel, const float braking_distance, const float final_speed) inline
Definition at line 61 of file TrajMath.hpp.
References f().
Referenced by CollisionPrevention::_calculateConstrainedSetpoint(), and FlightTaskAutoLineSmoothVel::_getMaxSpeedFromDistance().
computeMaxSpeedInWaypoint()
float math::trajectory::computeMaxSpeedInWaypoint (const float alpha, const float accel, const float d) inline
Definition at line 86 of file TrajMath.hpp.
References f().
Referenced by FlightTaskAutoLineSmoothVel::_getSpeedAtTarget().