PX4 Firmware: DfBebopRangeFinderWrapper Class Reference
DfBebopRangeFinderWrapper Class Reference
Public Member Functions
DfBebopRangeFinderWrapper ()
~DfBebopRangeFinderWrapper ()=default
int start ()
Start automatic measurement.
int stop ()
Stop automatic measurement.
Private Member Functions
int _publish (struct bebop_range &data)
Private Attributes
orb_advert_t _range_topic
int _orb_class_instance
Detailed Description
Definition at line 73 of file df_bebop_rangefinder_wrapper.cpp.
Constructor & Destructor Documentation
DfBebopRangeFinderWrapper::DfBebopRangeFinderWrapper ()
Definition at line 105 of file df_bebop_rangefinder_wrapper.cpp.
Referenced by df_bebop_rangefinder_wrapper::start().
DfBebopRangeFinderWrapper::~DfBebopRangeFinderWrapper () default
Member Function Documentation
int DfBebopRangeFinderWrapper::_publish (struct bebop_range & data) private
Definition at line 145 of file df_bebop_rangefinder_wrapper.cpp.
References _orb_class_instance, _range_topic, distance_sensor_s::covariance, distance_sensor_s::current_distance, hrt_absolute_time(), distance_sensor_s::id, distance_sensor_s::max_distance, distance_sensor_s::min_distance, orb_advertise_multi(), ORB_ID, ORB_PRIO_DEFAULT, orb_publish(), distance_sensor_s::orientation, distance_sensor_s::signal_quality, distance_sensor_s::timestamp, and distance_sensor_s::type.
int DfBebopRangeFinderWrapper::start ()
Start automatic measurement.
Returns
0 on success
Definition at line 112 of file df_bebop_rangefinder_wrapper.cpp.
References lis3mdl::init(), PX4_ERR, and start().
Referenced by df_bebop_rangefinder_wrapper::start().
int DfBebopRangeFinderWrapper::stop ()
Stop automatic measurement.
Returns
0 on success
Definition at line 132 of file df_bebop_rangefinder_wrapper.cpp.
References PX4_ERR, and stop().
Referenced by df_bebop_rangefinder_wrapper::stop().
Member Data Documentation
int DfBebopRangeFinderWrapper::_orb_class_instance private
Definition at line 99 of file df_bebop_rangefinder_wrapper.cpp.
Referenced by _publish().
orb_advert_t DfBebopRangeFinderWrapper::_range_topic private
Definition at line 97 of file df_bebop_rangefinder_wrapper.cpp.
Referenced by _publish().
The documentation for this class was generated from the following file:
src/platforms/posix/drivers/df_bebop_rangefinder_wrapper/df_bebop_rangefinder_wrapper.cpp