PX4 Firmware: LidarLite Class Reference
LidarLite Class Reference abstract
#include <LidarLite.h>
Public Member Functions
LidarLite ()
virtual ~LidarLite ()=default
virtual int init ()=0
virtual int ioctl (device::file_t *filp, int cmd, unsigned long arg)
virtual void start ()=0
virtual void stop ()=0
virtual void print_info ()=0
Diagnostics - print some basic information about the driver.
virtual void print_registers ()=0
print registers to console
virtual const char * get_dev_name ()=0
Protected Member Functions
void set_minimum_distance (const float min)
Set the min and max distance thresholds if you want the end points of the sensors range to be brought in at all, otherwise it will use the defaults LL40LS_MIN_DISTANCE and LL40LS_MAX_DISTANCE.
void set_maximum_distance (const float max)
float get_minimum_distance () const
float get_maximum_distance () const
uint32_t getMeasureTicks () const
virtual int measure ()=0
virtual int collect ()=0
virtual int reset_sensor ()=0
Private Attributes
float _min_distance
float _max_distance
uint32_t _measure_ticks
Detailed Description
Definition at line 56 of file LidarLite.h.
Constructor & Destructor Documentation
LidarLite::LidarLite ()
Definition at line 44 of file LidarLite.cpp.
virtual LidarLite::~LidarLite () virtual default
Member Function Documentation
virtual int LidarLite::collect () protected pure virtual
Implemented in LidarLiteI2C, and LidarLitePWM.
virtual const char* LidarLite::get_dev_name () pure virtual
Implemented in LidarLiteI2C, and LidarLitePWM.
Referenced by ll40ls::reset(), ll40ls::start(), and ll40ls::test().
float LidarLite::get_maximum_distance () const protected
Definition at line 66 of file LidarLite.cpp.
References _max_distance.
Referenced by LidarLiteI2C::collect(), and LidarLitePWM::measure().
float LidarLite::get_minimum_distance () const protected
Definition at line 61 of file LidarLite.cpp.
References _min_distance.
Referenced by LidarLiteI2C::collect(), and LidarLitePWM::measure().
uint32_t LidarLite::getMeasureTicks () const protected
Definition at line 71 of file LidarLite.cpp.
References _measure_ticks.
Referenced by LidarLitePWM::cycle(), LidarLiteI2C::cycle(), LidarLitePWM::print_info(), LidarLiteI2C::print_info(), LidarLitePWM::read(), and LidarLiteI2C::read().
virtual int LidarLite::init () pure virtual
Implemented in LidarLiteI2C, and LidarLitePWM.
Referenced by ll40ls::start().
int LidarLite::ioctl (device::file_t * filp, int cmd, unsigned long arg) virtual
Reimplemented in LidarLiteI2C, and LidarLitePWM.
Definition at line 76 of file LidarLite.cpp.
References _measure_ticks, LL40LS_CONVERSION_INTERVAL, OK, reset_sensor(), SENSOR_POLLRATE_DEFAULT, SENSOR_POLLRATE_EXTERNAL, SENSOR_POLLRATE_MANUAL, SENSOR_POLLRATE_MAX, SENSORIOCGPOLLRATE, SENSORIOCRESET, SENSORIOCSPOLLRATE, start(), and stop().
Referenced by LidarLitePWM::ioctl(), and LidarLiteI2C::ioctl().
virtual int LidarLite::measure () protected pure virtual
Implemented in LidarLiteI2C, and LidarLitePWM.
virtual void LidarLite::print_info () pure virtual
Diagnostics - print some basic information about the driver.
Implemented in LidarLiteI2C, and LidarLitePWM.
Referenced by ll40ls::info().
virtual void LidarLite::print_registers () pure virtual
print registers to console
Implemented in LidarLiteI2C, and LidarLitePWM.
Referenced by ll40ls::regdump().
virtual int LidarLite::reset_sensor () protected pure virtual
Implemented in LidarLiteI2C, and LidarLitePWM.
Referenced by ioctl().
void LidarLite::set_maximum_distance (const float max) protected
Definition at line 56 of file LidarLite.cpp.
References _max_distance, and max().
void LidarLite::set_minimum_distance (const float min) protected
Set the min and max distance thresholds if you want the end points of the sensors range to be brought in at all, otherwise it will use the defaults LL40LS_MIN_DISTANCE and LL40LS_MAX_DISTANCE.
Definition at line 51 of file LidarLite.cpp.
References _min_distance, and min().
virtual void LidarLite::start () pure virtual
Implemented in LidarLiteI2C, and LidarLitePWM.
Referenced by ioctl().
virtual void LidarLite::stop () pure virtual
Implemented in LidarLiteI2C, and LidarLitePWM.
Referenced by ioctl().
Member Data Documentation
float LidarLite::_max_distance private
Definition at line 105 of file LidarLite.h.
Referenced by get_maximum_distance(), and set_maximum_distance().
uint32_t LidarLite::_measure_ticks private
Definition at line 106 of file LidarLite.h.
Referenced by getMeasureTicks(), and ioctl().
float LidarLite::_min_distance private
Definition at line 104 of file LidarLite.h.
Referenced by get_minimum_distance(), and set_minimum_distance().
The documentation for this class was generated from the following files:
src/drivers/distance_sensor/ll40ls/LidarLite.h
src/drivers/distance_sensor/ll40ls/LidarLite.cpp