PX4 Firmware: PX4FLOW Class Reference
PX4FLOW Class Reference
Public Member Functions
PX4FLOW (int bus, int address=I2C_FLOW_ADDRESS_DEFAULT, enum Rotation rotation=(enum Rotation) 0, int conversion_interval=PX4FLOW_CONVERSION_INTERVAL_DEFAULT, uint8_t sonar_rotation=distance_sensor_s::ROTATION_DOWNWARD_FACING)
virtual ~PX4FLOW ()
virtual int init ()
virtual ssize_t read (struct file *filp, char *buffer, size_t buflen)
virtual int ioctl (struct file *filp, int cmd, unsigned long arg)
void print_info ()
Diagnostics - print some basic information about the driver.
Protected Member Functions
virtual int probe ()
Private Member Functions
int probe_address (uint8_t address)
Test whether the device supported by the driver is present at a specific address.
void start ()
Initialise the automatic measurement state machine and start it.
void stop ()
Stop the automatic measurement state machine.
void cycle ()
Perform a poll cycle; collect from the previous measurement and start a new one.
int measure ()
int collect ()
Static Private Member Functions
static void cycle_trampoline (void *arg)
Static trampoline from the workq context; because we don't have a generic workq wrapper yet.
Private Attributes
uint8_t _sonar_rotation
work_s _work
ringbuffer::RingBuffer * _reports
bool _sensor_ok
int _measure_ticks
bool _collect_phase
int _class_instance
int _orb_class_instance
orb_advert_t _px4flow_topic
orb_advert_t _distance_sensor_topic
perf_counter_t _sample_perf
perf_counter_t _comms_errors
unsigned _conversion_interval
enum Rotation _sensor_rotation
float _sensor_min_range
float _sensor_max_range
float _sensor_max_flow_rate
i2c_frame _frame
i2c_integral_frame _frame_integral
Detailed Description
Definition at line 105 of file px4flow.cpp.
Constructor & Destructor Documentation
PX4FLOW::PX4FLOW (int bus, int address = I2C_FLOW_ADDRESS_DEFAULT, enum Rotation rotation = (enum Rotation)0, int conversion_interval = PX4FLOW_CONVERSION_INTERVAL_DEFAULT, uint8_t sonar_rotation = distance_sensor_s::ROTATION_DOWNWARD_FACING)
Definition at line 196 of file px4flow.cpp.
Referenced by px4flow::start().
PX4FLOW::~PX4FLOW () virtual
Definition at line 219 of file px4flow.cpp.
References _comms_errors, _reports, _sample_perf, perf_free(), and stop().
Member Function Documentation
int PX4FLOW::collect () private
Definition at line 508 of file px4flow.cpp.
References _comms_errors, _distance_sensor_topic, _frame, _frame_integral, _px4flow_topic, _reports, _sample_perf, _sensor_max_flow_rate, _sensor_max_range, _sensor_min_range, _sensor_rotation, _sonar_rotation, distance_sensor_s::covariance, distance_sensor_s::current_distance, DEVICE_DEBUG, f(), optical_flow_s::frame_count_since_last_readout, i2c_integral_frame::frame_count_since_last_readout, i2c_integral_frame::ground_distance, optical_flow_s::ground_distance_m, optical_flow_s::gyro_temperature, i2c_integral_frame::gyro_temperature, optical_flow_s::gyro_x_rate_integral, i2c_integral_frame::gyro_x_rate_integral, optical_flow_s::gyro_y_rate_integral, i2c_integral_frame::gyro_y_rate_integral, optical_flow_s::gyro_z_rate_integral, i2c_integral_frame::gyro_z_rate_integral, hrt_absolute_time(), I2C_FRAME_SIZE, I2C_INTEGRAL_FRAME_SIZE, distance_sensor_s::id, optical_flow_s::integration_timespan, i2c_integral_frame::integration_timespan, distance_sensor_s::max_distance, optical_flow_s::max_flow_rate, optical_flow_s::max_ground_distance, distance_sensor_s::min_distance, optical_flow_s::min_ground_distance, OK, orb_advertise(), ORB_ID, orb_publish(), distance_sensor_s::orientation, perf_begin(), perf_count(), perf_end(), optical_flow_s::pixel_flow_x_integral, i2c_integral_frame::pixel_flow_x_integral, optical_flow_s::pixel_flow_y_integral, i2c_integral_frame::pixel_flow_y_integral, PX4FLOW_MAX_DISTANCE, PX4FLOW_MIN_DISTANCE, PX4FLOW_REG, i2c_integral_frame::qual, optical_flow_s::quality, rotate_3f(), optical_flow_s::sensor_id, distance_sensor_s::signal_quality, i2c_integral_frame::sonar_timestamp, optical_flow_s::time_since_last_sonar_update, optical_flow_s::timestamp, distance_sensor_s::timestamp, and distance_sensor_s::type.
Referenced by cycle(), and read().
void PX4FLOW::cycle () private
Perform a poll cycle; collect from the previous measurement and start a new one.
Definition at line 644 of file px4flow.cpp.
References _measure_ticks, collect(), cycle_trampoline(), DEVICE_DEBUG, measure(), OK, and start().
Referenced by cycle_trampoline().
void PX4FLOW::cycle_trampoline (void * arg) static private
Static trampoline from the workq context; because we don't have a generic workq wrapper yet.
Parameters
arg Instance pointer for the driver that is polling.
Definition at line 636 of file px4flow.cpp.
References cycle().
Referenced by cycle(), and start().
int PX4FLOW::init () virtual
Definition at line 234 of file px4flow.cpp.
References _class_instance, _distance_sensor_topic, _orb_class_instance, _reports, _sensor_max_flow_rate, _sensor_max_range, _sensor_min_range, _sensor_ok, _sensor_rotation, CLASS_DEVICE_PRIMARY, DEVICE_LOG, lis3mdl::init(), OK, orb_advertise_multi(), ORB_ID, ORB_PRIO_HIGH, param_find(), param_get(), PARAM_INVALID, PX4_ERROR, and RANGE_FINDER_BASE_DEVICE_PATH.
Referenced by px4flow::start().
int PX4FLOW::ioctl (struct file * filp, int cmd, unsigned long arg) virtual
Definition at line 330 of file px4flow.cpp.
References _conversion_interval, _measure_ticks, _reports, OK, SENSOR_POLLRATE_DEFAULT, SENSOR_POLLRATE_EXTERNAL, SENSOR_POLLRATE_MANUAL, SENSOR_POLLRATE_MAX, SENSORIOCGPOLLRATE, SENSORIOCRESET, SENSORIOCSPOLLRATE, SENSORIOCSQUEUEDEPTH, start(), and stop().
Referenced by px4flow::reset(), px4flow::start(), and px4flow::test().
int PX4FLOW::measure () private
Definition at line 486 of file px4flow.cpp.
References _comms_errors, DEVICE_DEBUG, OK, perf_count(), and PX4FLOW_REG.
Referenced by cycle(), probe(), and read().
void PX4FLOW::print_info (void)
Diagnostics - print some basic information about the driver.
Definition at line 664 of file px4flow.cpp.
References _comms_errors, _measure_ticks, _reports, _sample_perf, and perf_print_counter().
Referenced by px4flow::info().
int PX4FLOW::probe () protected virtual
Definition at line 313 of file px4flow.cpp.
References I2C_FRAME_SIZE, measure(), and OK.
int PX4FLOW::probe_address (uint8_t address) private
Test whether the device supported by the driver is present at a specific address.
Parameters
address The I2C bus address to probe.
Returns
True if the device is present.
ssize_t PX4FLOW::read (struct file * filp, char * buffer, size_t buflen) virtual
Definition at line 429 of file px4flow.cpp.
References _measure_ticks, _reports, collect(), measure(), and OK.
Referenced by px4flow::test().
void PX4FLOW::start () private
Initialise the automatic measurement state machine and start it.
Note
This function is called at open and error time. It might make sense to make it more aggressive about resetting the bus in case of errors.
Definition at line 619 of file px4flow.cpp.
References _collect_phase, _reports, and cycle_trampoline().
Referenced by cycle(), and ioctl().
void PX4FLOW::stop () private
Stop the automatic measurement state machine.
Definition at line 630 of file px4flow.cpp.
Referenced by ioctl(), and ~PX4FLOW().
Member Data Documentation
int PX4FLOW::_class_instance private
Definition at line 134 of file px4flow.cpp.
Referenced by init().
bool PX4FLOW::_collect_phase private
Definition at line 133 of file px4flow.cpp.
Referenced by start().
perf_counter_t PX4FLOW::_comms_errors private
Definition at line 140 of file px4flow.cpp.
Referenced by collect(), measure(), print_info(), and ~PX4FLOW().
unsigned PX4FLOW::_conversion_interval private
Definition at line 142 of file px4flow.cpp.
Referenced by ioctl().
orb_advert_t PX4FLOW::_distance_sensor_topic private
Definition at line 137 of file px4flow.cpp.
Referenced by collect(), and init().
i2c_frame PX4FLOW::_frame private
Definition at line 149 of file px4flow.cpp.
Referenced by collect().
i2c_integral_frame PX4FLOW::_frame_integral private
Definition at line 150 of file px4flow.cpp.
Referenced by collect().
int PX4FLOW::_measure_ticks private
Definition at line 132 of file px4flow.cpp.
Referenced by cycle(), ioctl(), print_info(), and read().
int PX4FLOW::_orb_class_instance private
Definition at line 135 of file px4flow.cpp.
Referenced by init().
orb_advert_t PX4FLOW::_px4flow_topic private
Definition at line 136 of file px4flow.cpp.
Referenced by collect().
ringbuffer::RingBuffer* PX4FLOW::_reports private
Definition at line 130 of file px4flow.cpp.
Referenced by collect(), init(), ioctl(), print_info(), read(), start(), and ~PX4FLOW().
perf_counter_t PX4FLOW::_sample_perf private
Definition at line 139 of file px4flow.cpp.
Referenced by collect(), print_info(), and ~PX4FLOW().
float PX4FLOW::_sensor_max_flow_rate private
Definition at line 147 of file px4flow.cpp.
Referenced by collect(), and init().
float PX4FLOW::_sensor_max_range private
Definition at line 146 of file px4flow.cpp.
Referenced by collect(), and init().
float PX4FLOW::_sensor_min_range private
Definition at line 145 of file px4flow.cpp.
Referenced by collect(), and init().
bool PX4FLOW::_sensor_ok private
Definition at line 131 of file px4flow.cpp.
Referenced by init().
enum Rotation PX4FLOW::_sensor_rotation private
Definition at line 144 of file px4flow.cpp.
Referenced by collect(), and init().
uint8_t PX4FLOW::_sonar_rotation private
Definition at line 128 of file px4flow.cpp.
Referenced by collect().
work_s PX4FLOW::_work private
Definition at line 129 of file px4flow.cpp.
The documentation for this class was generated from the following file:
src/drivers/px4flow/px4flow.cpp