PX4 Firmware: control::BlockHighPass Class Reference
control::BlockHighPass Class Reference
A high pass filter as described here: http://en.wikipedia.org/wiki/High-pass_filter.
#include <BlockHighPass.hpp>
Public Member Functions
BlockHighPass (SuperBlock *parent, const char *name)
virtual ~BlockHighPass ()
float update (float input)
float getU ()
float getY ()
float getFCut ()
void setU (float u)
void setY (float y)
Public Member Functions inherited from control::Block
Block (SuperBlock *parent, const char *name)
virtual ~Block ()=default
Block (const Block &)=delete
Block & operator= (const Block &)=delete
Block (Block &&)=delete
Block & operator= (Block &&)=delete
void getName (char *name, size_t n)
virtual void updateParams ()
virtual void updateSubscriptions ()
virtual void updatePublications ()
virtual void setDt (float dt)
float getDt ()
Public Member Functions inherited from ListNode< Block * >
ListNode ()
ListNode (const ListNode &)=delete
ListNode (ListNode &&)=delete
virtual ~ListNode ()=default
ListNode & operator= (const ListNode &)=delete
ListNode & operator= (ListNode &&)=delete
void setSibling (Block *sibling)
const Block * getSibling ()
Protected Attributes
float _u
previous input
float _y
previous output
control::BlockParamFloat _fCut
cut-off frequency, Hz
Protected Attributes inherited from control::Block
const char * _name
SuperBlock * _parent
float _dt {0.0f}
List< uORB::SubscriptionNode * > _subscriptions
List< uORB::PublicationNode * > _publications
List< BlockParamBase * > _params
Protected Attributes inherited from ListNode< Block * >
Block * _sibling
Additional Inherited Members
Protected Member Functions inherited from control::Block
virtual void updateParamsSubclass ()
SuperBlock * getParent ()
List< uORB::SubscriptionNode * > & getSubscriptions ()
List< uORB::PublicationNode * > & getPublications ()
List< BlockParamBase * > & getParams ()
Detailed Description
A high pass filter as described here: http://en.wikipedia.org/wiki/High-pass_filter.
Definition at line 62 of file BlockHighPass.hpp.
Constructor & Destructor Documentation
control::BlockHighPass::BlockHighPass (SuperBlock * parent, const char * name) inline
Definition at line 66 of file BlockHighPass.hpp.
virtual control::BlockHighPass::~BlockHighPass () inline virtual
Definition at line 72 of file BlockHighPass.hpp.
Member Function Documentation
float control::BlockHighPass::getFCut () inline
Definition at line 77 of file BlockHighPass.hpp.
Referenced by control::blockHighPassTest(), blockHighPassTest(), and update().
float control::BlockHighPass::getU () inline
Definition at line 75 of file BlockHighPass.hpp.
Referenced by control::blockHighPassTest(), blockHighPassTest(), and update().
float control::BlockHighPass::getY () inline
Definition at line 76 of file BlockHighPass.hpp.
Referenced by control::blockHighPassTest(), blockHighPassTest(), and update().
void control::BlockHighPass::setU (float u) inline
Definition at line 78 of file BlockHighPass.hpp.
Referenced by control::blockHighPassTest(), blockHighPassTest(), and update().
void control::BlockHighPass::setY (float y) inline
Definition at line 79 of file BlockHighPass.hpp.
Referenced by control::blockHighPassTest(), blockHighPassTest(), and update().
float control::BlockHighPass::update (float input)
Definition at line 48 of file BlockHighPass.cpp.
References control::Block::getDt(), getFCut(), getU(), getY(), setU(), and setY().
Referenced by control::blockHighPassTest(), blockHighPassTest(), and BlockLocalPositionEstimator::flowMeasure().
Member Data Documentation
control::BlockParamFloat control::BlockHighPass::_fCut protected
cut-off frequency, Hz
Definition at line 84 of file BlockHighPass.hpp.
float control::BlockHighPass::_u protected
previous input
Definition at line 82 of file BlockHighPass.hpp.
float control::BlockHighPass::_y protected
previous output
Definition at line 83 of file BlockHighPass.hpp.
The documentation for this class was generated from the following files:
src/lib/controllib/BlockHighPass.hpp
src/lib/controllib/BlockHighPass.cpp