PX4 Firmware: MavlinkStreamOrbitStatus Class Reference
MavlinkStreamOrbitStatus Class Reference
Public Member Functions
const char * get_name () const override
uint16_t get_id () override
unsigned get_size () override
Get maximal total messages size on update.
Public Member Functions inherited from MavlinkStream
MavlinkStream (Mavlink *mavlink)
virtual ~MavlinkStream ()=default
MavlinkStream (const MavlinkStream &)=delete
MavlinkStream & operator= (const MavlinkStream &)=delete
MavlinkStream (MavlinkStream &&)=delete
MavlinkStream & operator= (MavlinkStream &&)=delete
void set_interval (const int interval)
Get the interval.
int get_interval ()
Get the interval.
int update (const hrt_abstime &t)
Update subscriptions and send message if necessary.
virtual bool const_rate ()
virtual unsigned get_size_avg ()
Get the average message size.
bool first_message_sent () const
void reset_last_sent ()
Reset the time of last sent to 0.
Public Member Functions inherited from ListNode< MavlinkStream *>
void setSibling (MavlinkStream * sibling)
const MavlinkStream * getSibling () const
Static Public Member Functions
static const char * get_name_static ()
static uint16_t get_id_static ()
static MavlinkStream * new_instance (Mavlink *mavlink)
Protected Member Functions
MavlinkStreamOrbitStatus (Mavlink *mavlink)
bool send (const hrt_abstime t) override
Protected Member Functions inherited from MavlinkStream
virtual void update_data ()
Function to collect/update data for the streams at a high rate independant of actual stream rate.
Private Member Functions
MavlinkStreamOrbitStatus (MavlinkStreamOrbitStatus &)
MavlinkStreamOrbitStatus & operator= (const MavlinkStreamOrbitStatus &)
Private Attributes
MavlinkOrbSubscription * _sub
uint64_t _orbit_status_time
Additional Inherited Members
Protected Attributes inherited from MavlinkStream
Mavlink *const _mavlink
int _interval {1000000}
if set to negative value = unlimited rate
Protected Attributes inherited from ListNode< MavlinkStream *>
MavlinkStream * _list_node_sibling
Detailed Description
Definition at line 4927 of file mavlink_messages.cpp.
Constructor & Destructor Documentation
MavlinkStreamOrbitStatus() [1/2]
MavlinkStreamOrbitStatus::MavlinkStreamOrbitStatus (MavlinkStreamOrbitStatus &) private
MavlinkStreamOrbitStatus() [2/2]
MavlinkStreamOrbitStatus::MavlinkStreamOrbitStatus (Mavlink * mavlink) inline explicit protected
Definition at line 4970 of file mavlink_messages.cpp.
Member Function Documentation
get_id()
uint16_t MavlinkStreamOrbitStatus::get_id () inline override virtual
Implements MavlinkStream.
Definition at line 4945 of file mavlink_messages.cpp.
References MavlinkStreamHeartbeat::get_id_static().
get_id_static()
static uint16_t MavlinkStreamOrbitStatus::get_id_static () inline static
Definition at line 4940 of file mavlink_messages.cpp.
get_name()
const char* MavlinkStreamOrbitStatus::get_name () const inline override virtual
Implements MavlinkStream.
Definition at line 4930 of file mavlink_messages.cpp.
References get_name_static().
get_name_static()
static const char* MavlinkStreamOrbitStatus::get_name_static () inline static
Definition at line 4935 of file mavlink_messages.cpp.
Referenced by get_name().
get_size()
unsigned MavlinkStreamOrbitStatus::get_size () inline override virtual
Get maximal total messages size on update.
Implements MavlinkStream.
Definition at line 4955 of file mavlink_messages.cpp.
new_instance()
static MavlinkStream* MavlinkStreamOrbitStatus::new_instance (Mavlink * mavlink) inline static
Definition at line 4950 of file mavlink_messages.cpp.
operator=()
MavlinkStreamOrbitStatus& MavlinkStreamOrbitStatus::operator= (const MavlinkStreamOrbitStatus &) private
send()
bool MavlinkStreamOrbitStatus::send (const hrt_abstime t) inline override protected virtual
Implements MavlinkStream.
Definition at line 4975 of file mavlink_messages.cpp.
References MavlinkStream::_mavlink, orbit_status_s::frame, Mavlink::get_channel(), orbit_status_s::radius, orbit_status_s::timestamp, MavlinkOrbSubscription::update(), orbit_status_s::x, orbit_status_s::y, and orbit_status_s::z.
Member Data Documentation
_orbit_status_time
uint64_t MavlinkStreamOrbitStatus::_orbit_status_time private
Definition at line 4963 of file mavlink_messages.cpp.
_sub
MavlinkOrbSubscription* MavlinkStreamOrbitStatus::_sub private
Definition at line 4962 of file mavlink_messages.cpp.
The documentation for this class was generated from the following file:
src/modules/mavlink/mavlink_messages.cpp