PX4 Firmware: sensors::RCUpdate Class Reference
sensors::RCUpdate Class Reference
class RCUpdate
#include <rc_update.h>
Public Member Functions
RCUpdate (const Parameters &parameters)
int init ()
initialize subscriptions etc.
void deinit ()
deinitialize the object (we cannot use the destructor because it is called on the wrong thread)
void rc_parameter_map_poll (ParameterHandles &parameter_handles, bool forced=false)
Check for changes in rc_parameter_map.
void update_rc_functions ()
update the RC functions.
void rc_poll (const ParameterHandles &parameter_handles)
Gather and publish RC input data.
Private Member Functions
float get_rc_value (uint8_t func, float min_value, float max_value)
Get and limit value for specified RC function.
switch_pos_t get_rc_sw3pos_position (uint8_t func, float on_th, bool on_inv, float mid_th, bool mid_inv)
Get switch position for specified function.
switch_pos_t get_rc_sw2pos_position (uint8_t func, float on_th, bool on_inv)
void set_params_from_rc (const ParameterHandles &parameter_handles)
Update parameters from RC channels if the functionality is activated and the input has changed since the last update.
Private Attributes
int _rc_sub = -1
raw rc channels data subscription
int _rc_parameter_map_sub = -1
rc parameter map subscription
orb_advert_t _rc_pub = nullptr
raw r/c control topic
orb_advert_t _manual_control_pub = nullptr
manual control signal topic
orb_advert_t _actuator_group_3_pub = nullptr
manual control as actuator topic
struct rc_channels_s _rc
r/c channel data
struct rc_parameter_map_s _rc_parameter_map
float _param_rc_values [rc_parameter_map_s::RC_PARAM_MAP_NCHAN]
parameter values for RC control
const Parameters & _parameters
hrt_abstime _last_rc_to_param_map_time = 0
math::LowPassFilter2p _filter_roll
filters for the main 4 stick inputs
math::LowPassFilter2p _filter_pitch
math::LowPassFilter2p _filter_yaw
we want smooth setpoints as inputs to the controllers
math::LowPassFilter2p _filter_throttle
Detailed Description
class RCUpdate
Handling of RC updates
Definition at line 57 of file rc_update.h.
Constructor & Destructor Documentation
RCUpdate::RCUpdate (const Parameters & parameters)
Parameters
parameters parameter values. These do not have to be initialized when constructing this object. Only when calling init(), they have to be initialized.
Definition at line 52 of file rc_update.cpp.
References _param_rc_values, _rc, and _rc_parameter_map.
Member Function Documentation
void RCUpdate::deinit ()
deinitialize the object (we cannot use the destructor because it is called on the wrong thread)
Definition at line 81 of file rc_update.cpp.
References _rc_parameter_map_sub, _rc_sub, and orb_unsubscribe().
Referenced by Sensors::run().
switch_pos_t RCUpdate::get_rc_sw2pos_position (uint8_t func, float on_th, bool on_inv) private
Definition at line 209 of file rc_update.cpp.
References _rc, rc_channels_s::channels, and rc_channels_s::function.
Referenced by rc_poll().
switch_pos_t RCUpdate::get_rc_sw3pos_position (uint8_t func, float on_th, bool on_inv, float mid_th, bool mid_inv) private
Get switch position for specified function.
Definition at line 188 of file rc_update.cpp.
References _rc, rc_channels_s::channels, and rc_channels_s::function.
Referenced by rc_poll().
float RCUpdate::get_rc_value (uint8_t func, float min_value, float max_value) private
Get and limit value for specified RC function.
Returns NAN if not mapped.
Definition at line 176 of file rc_update.cpp.
References _rc, rc_channels_s::channels, math::constrain(), and rc_channels_s::function.
Referenced by rc_poll(), and set_params_from_rc().
int RCUpdate::init ()
initialize subscriptions etc.
Returns
0 on success, <0 otherwise
Definition at line 64 of file rc_update.cpp.
References _rc_parameter_map_sub, _rc_sub, ORB_ID, and orb_subscribe().
Referenced by Sensors::run().
void RCUpdate::rc_parameter_map_poll (ParameterHandles & parameter_handles, bool forced = false)
Check for changes in rc_parameter_map.
Definition at line 133 of file rc_update.cpp.
References _rc, _rc_parameter_map, _rc_parameter_map_sub, rc_channels_s::function, orb_check(), orb_copy(), ORB_ID, param_find(), param_for_used_index(), rc_parameter_map_s::param_id, rc_parameter_map_s::param_index, PX4_DEBUG, sensors::ParameterHandles::rc_param, rc_parameter_map_s::scale, rc_parameter_map_s::valid, rc_parameter_map_s::value0, rc_parameter_map_s::value_max, and rc_parameter_map_s::value_min.
Referenced by Sensors::run().
void RCUpdate::rc_poll (const ParameterHandles & parameter_handles)
Gather and publish RC input data.
Definition at line 252 of file rc_update.cpp.
References _actuator_group_3_pub, _filter_pitch, _filter_roll, _filter_throttle, _filter_yaw, _last_rc_to_param_map_time, _manual_control_pub, _parameters, _rc, _rc_pub, _rc_sub, manual_control_setpoint_s::acro_switch, math::LowPassFilter2p::apply(), manual_control_setpoint_s::arm_switch, manual_control_setpoint_s::aux1, manual_control_setpoint_s::aux2, manual_control_setpoint_s::aux3, manual_control_setpoint_s::aux4, manual_control_setpoint_s::aux5, rc_channels_s::channel_count, rc_channels_s::channels, math::constrain(), actuator_controls_s::control, manual_control_setpoint_s::data_source, sensors::Parameters::dz, f(), manual_control_setpoint_s::flaps, rc_channels_s::frame_drop_count, rc_channels_s::function, manual_control_setpoint_s::gear_switch, get_rc_sw2pos_position(), get_rc_sw3pos_position(), get_rc_value(), hrt_absolute_time(), hrt_elapsed_time(), instance, manual_control_setpoint_s::kill_switch, manual_control_setpoint_s::loiter_switch, manual_control_setpoint_s::man_switch, sensors::Parameters::max, sensors::Parameters::min, manual_control_setpoint_s::mode_slot, manual_control_setpoint_s::mode_switch, manual_control_setpoint_s::offboard_switch, orb_check(), orb_copy(), ORB_ID, ORB_PRIO_DEFAULT, ORB_PRIO_HIGH, orb_publish_auto(), manual_control_setpoint_s::posctl_switch, manual_control_setpoint_s::r, manual_control_setpoint_s::rattitude_switch, sensors::Parameters::rc_acro_inv, sensors::Parameters::rc_acro_th, sensors::Parameters::rc_armswitch_inv, sensors::Parameters::rc_armswitch_th, sensors::Parameters::rc_assist_inv, sensors::Parameters::rc_assist_th, sensors::Parameters::rc_auto_inv, sensors::Parameters::rc_auto_th, rc_channels, sensors::Parameters::rc_fails_thr, sensors::Parameters::rc_gear_inv, sensors::Parameters::rc_gear_th, rc_input_values, sensors::Parameters::rc_killswitch_inv, sensors::Parameters::rc_killswitch_th, sensors::Parameters::rc_loiter_inv, sensors::Parameters::rc_loiter_th, sensors::Parameters::rc_man_inv, sensors::Parameters::rc_man_th, sensors::Parameters::rc_map_failsafe, sensors::Parameters::rc_map_flightmode, sensors::RC_MAX_CHAN_COUNT, sensors::Parameters::rc_offboard_inv, sensors::Parameters::rc_offboard_th, sensors::Parameters::rc_posctl_inv, sensors::Parameters::rc_posctl_th, sensors::Parameters::rc_rattitude_inv, sensors::Parameters::rc_rattitude_th, sensors::Parameters::rc_return_inv, sensors::Parameters::rc_return_th, sensors::Parameters::rc_stab_inv, sensors::Parameters::rc_stab_th, sensors::Parameters::rc_trans_inv, sensors::Parameters::rc_trans_th, manual_control_setpoint_s::return_switch, sensors::Parameters::rev, rc_channels_s::rssi, set_params_from_rc(), rc_channels_s::signal_lost, manual_control_setpoint_s::stab_switch, actuator_controls_s::timestamp, manual_control_setpoint_s::timestamp, rc_channels_s::timestamp, manual_control_setpoint_s::transition_switch, sensors::Parameters::trim, manual_control_setpoint_s::x, manual_control_setpoint_s::y, and manual_control_setpoint_s::z.
Referenced by Sensors::run().
void RCUpdate::set_params_from_rc (const ParameterHandles & parameter_handles) private
Update parameters from RC channels if the functionality is activated and the input has changed since the last update.
Parameters
Definition at line 227 of file rc_update.cpp.
References _param_rc_values, _rc, _rc_parameter_map, math::constrain(), rc_channels_s::function, get_rc_value(), param_set(), sensors::ParameterHandles::rc_param, rc_parameter_map_s::scale, rc_parameter_map_s::valid, rc_parameter_map_s::value0, rc_parameter_map_s::value_max, and rc_parameter_map_s::value_min.
Referenced by rc_poll().
void RCUpdate::update_rc_functions ()
update the RC functions.
Call this when the parameters change.
Definition at line 87 of file rc_update.cpp.
References _filter_pitch, _filter_roll, _filter_throttle, _filter_yaw, _parameters, _rc, f(), rc_channels_s::function, sensors::Parameters::rc_flt_cutoff, sensors::Parameters::rc_flt_smp_rate, sensors::Parameters::rc_map_acro_sw, sensors::Parameters::rc_map_arm_sw, sensors::Parameters::rc_map_aux1, sensors::Parameters::rc_map_aux2, sensors::Parameters::rc_map_aux3, sensors::Parameters::rc_map_aux4, sensors::Parameters::rc_map_aux5, sensors::Parameters::rc_map_flaps, sensors::Parameters::rc_map_gear_sw, sensors::Parameters::rc_map_kill_sw, sensors::Parameters::rc_map_loiter_sw, sensors::Parameters::rc_map_man_sw, sensors::Parameters::rc_map_mode_sw, sensors::Parameters::rc_map_offboard_sw, sensors::Parameters::rc_map_param, sensors::Parameters::rc_map_pitch, sensors::Parameters::rc_map_posctl_sw, sensors::Parameters::rc_map_rattitude_sw, sensors::Parameters::rc_map_return_sw, sensors::Parameters::rc_map_roll, sensors::Parameters::rc_map_stab_sw, sensors::Parameters::rc_map_throttle, sensors::Parameters::rc_map_trans_sw, sensors::Parameters::rc_map_yaw, math::LowPassFilter2p::reset(), and math::LowPassFilter2p::set_cutoff_frequency().
Referenced by Sensors::parameters_update().
Member Data Documentation
orb_advert_t sensors::RCUpdate::_actuator_group_3_pub = nullptr private
manual control as actuator topic
Definition at line 119 of file rc_update.h.
Referenced by rc_poll().
math::LowPassFilter2p sensors::RCUpdate::_filter_pitch private
Definition at line 131 of file rc_update.h.
Referenced by rc_poll(), and update_rc_functions().
math::LowPassFilter2p sensors::RCUpdate::_filter_roll private
filters for the main 4 stick inputs
Definition at line 130 of file rc_update.h.
Referenced by rc_poll(), and update_rc_functions().
math::LowPassFilter2p sensors::RCUpdate::_filter_throttle private
Definition at line 133 of file rc_update.h.
Referenced by rc_poll(), and update_rc_functions().
math::LowPassFilter2p sensors::RCUpdate::_filter_yaw private
we want smooth setpoints as inputs to the controllers
Definition at line 132 of file rc_update.h.
Referenced by rc_poll(), and update_rc_functions().
hrt_abstime sensors::RCUpdate::_last_rc_to_param_map_time = 0 private
Definition at line 128 of file rc_update.h.
Referenced by rc_poll().
orb_advert_t sensors::RCUpdate::_manual_control_pub = nullptr private
manual control signal topic
Definition at line 118 of file rc_update.h.
Referenced by rc_poll().
float sensors::RCUpdate::_param_rc_values[rc_parameter_map_s::RC_PARAM_MAP_NCHAN] private
parameter values for RC control
Definition at line 124 of file rc_update.h.
Referenced by RCUpdate(), and set_params_from_rc().
const Parameters& sensors::RCUpdate::_parameters private
Definition at line 126 of file rc_update.h.
Referenced by rc_poll(), and update_rc_functions().
struct rc_channels_s sensors::RCUpdate::_rc private
r/c channel data
Definition at line 121 of file rc_update.h.
Referenced by get_rc_sw2pos_position(), get_rc_sw3pos_position(), get_rc_value(), rc_parameter_map_poll(), rc_poll(), RCUpdate(), set_params_from_rc(), and update_rc_functions().
struct rc_parameter_map_s sensors::RCUpdate::_rc_parameter_map private
Definition at line 123 of file rc_update.h.
Referenced by rc_parameter_map_poll(), RCUpdate(), and set_params_from_rc().
int sensors::RCUpdate::_rc_parameter_map_sub = -1 private
rc parameter map subscription
Definition at line 115 of file rc_update.h.
Referenced by deinit(), init(), and rc_parameter_map_poll().
orb_advert_t sensors::RCUpdate::_rc_pub = nullptr private
raw r/c control topic
Definition at line 117 of file rc_update.h.
Referenced by rc_poll().
int sensors::RCUpdate::_rc_sub = -1 private
raw rc channels data subscription
Definition at line 114 of file rc_update.h.
Referenced by deinit(), init(), and rc_poll().
The documentation for this class was generated from the following files:
src/modules/sensors/rc_update.h
src/modules/sensors/rc_update.cpp