PX4 Firmware: MavlinkStreamADSBVehicle Class Reference
MavlinkStreamADSBVehicle Class Reference
Public Member Functions
const char * get_name () const override
uint16_t get_id () override
bool const_rate () override
unsigned get_size () override
Get maximal total messages size on update.
Public Member Functions inherited from MavlinkStream
MavlinkStream (Mavlink *mavlink)
virtual ~MavlinkStream ()=default
MavlinkStream (const MavlinkStream &)=delete
MavlinkStream & operator= (const MavlinkStream &)=delete
MavlinkStream (MavlinkStream &&)=delete
MavlinkStream & operator= (MavlinkStream &&)=delete
void set_interval (const int interval)
Get the interval.
int get_interval ()
Get the interval.
int update (const hrt_abstime &t)
Update subscriptions and send message if necessary.
virtual unsigned get_size_avg ()
Get the average message size.
bool first_message_sent () const
void reset_last_sent ()
Reset the time of last sent to 0.
Public Member Functions inherited from ListNode< MavlinkStream *>
void setSibling (MavlinkStream * sibling)
const MavlinkStream * getSibling () const
Static Public Member Functions
static const char * get_name_static ()
static uint16_t get_id_static ()
static MavlinkStream * new_instance (Mavlink *mavlink)
Protected Member Functions
MavlinkStreamADSBVehicle (Mavlink *mavlink)
bool send (const hrt_abstime t) override
Protected Member Functions inherited from MavlinkStream
virtual void update_data ()
Function to collect/update data for the streams at a high rate independant of actual stream rate.
Private Member Functions
MavlinkStreamADSBVehicle (MavlinkStreamADSBVehicle &)=delete
MavlinkStreamADSBVehicle & operator= (const MavlinkStreamADSBVehicle &)=delete
Private Attributes
MavlinkOrbSubscription * _pos_sub
uint64_t _pos_time
Additional Inherited Members
Protected Attributes inherited from MavlinkStream
Mavlink *const _mavlink
int _interval {1000000}
if set to negative value = unlimited rate
Protected Attributes inherited from ListNode< MavlinkStream *>
MavlinkStream * _list_node_sibling
Detailed Description
Definition at line 1758 of file mavlink_messages.cpp.
Constructor & Destructor Documentation
MavlinkStreamADSBVehicle() [1/2]
MavlinkStreamADSBVehicle::MavlinkStreamADSBVehicle (MavlinkStreamADSBVehicle &) private delete
MavlinkStreamADSBVehicle() [2/2]
MavlinkStreamADSBVehicle::MavlinkStreamADSBVehicle (Mavlink * mavlink) inline explicit protected
Definition at line 1805 of file mavlink_messages.cpp.
Member Function Documentation
const_rate()
bool MavlinkStreamADSBVehicle::const_rate () inline override virtual
Returns
true if steam rate shouldn't be adjusted
Reimplemented from MavlinkStream.
Definition at line 1786 of file mavlink_messages.cpp.
get_id()
uint16_t MavlinkStreamADSBVehicle::get_id () inline override virtual
Implements MavlinkStream.
Definition at line 1776 of file mavlink_messages.cpp.
References MavlinkStreamHeartbeat::get_id_static().
get_id_static()
static uint16_t MavlinkStreamADSBVehicle::get_id_static () inline static
Definition at line 1771 of file mavlink_messages.cpp.
get_name()
const char* MavlinkStreamADSBVehicle::get_name () const inline override virtual
Implements MavlinkStream.
Definition at line 1761 of file mavlink_messages.cpp.
References get_name_static().
get_name_static()
static const char* MavlinkStreamADSBVehicle::get_name_static () inline static
Definition at line 1766 of file mavlink_messages.cpp.
Referenced by get_name().
get_size()
unsigned MavlinkStreamADSBVehicle::get_size () inline override virtual
Get maximal total messages size on update.
Implements MavlinkStream.
Definition at line 1791 of file mavlink_messages.cpp.
new_instance()
static MavlinkStream* MavlinkStreamADSBVehicle::new_instance (Mavlink * mavlink) inline static
Definition at line 1781 of file mavlink_messages.cpp.
operator=()
MavlinkStreamADSBVehicle& MavlinkStreamADSBVehicle::operator= (const MavlinkStreamADSBVehicle &) private delete
send()
bool MavlinkStreamADSBVehicle::send (const hrt_abstime t) inline override protected virtual
Implements MavlinkStream.
Definition at line 1810 of file mavlink_messages.cpp.
References MavlinkStream::_mavlink, transponder_report_s::altitude, transponder_report_s::altitude_type, transponder_report_s::callsign, transponder_report_s::emitter_type, f(), transponder_report_s::flags, Mavlink::get_channel(), transponder_report_s::heading, transponder_report_s::hor_velocity, transponder_report_s::icao_address, transponder_report_s::lat, transponder_report_s::lon, M_PI_F, msg, transponder_report_s::squawk, transponder_report_s::tslc, MavlinkOrbSubscription::update(), and transponder_report_s::ver_velocity.
Member Data Documentation
_pos_sub
MavlinkOrbSubscription* MavlinkStreamADSBVehicle::_pos_sub private
Definition at line 1797 of file mavlink_messages.cpp.
_pos_time
uint64_t MavlinkStreamADSBVehicle::_pos_time private
Definition at line 1798 of file mavlink_messages.cpp.
The documentation for this class was generated from the following file:
src/modules/mavlink/mavlink_messages.cpp