PX4 Firmware: AutoDeclinationTest Class Reference
AutoDeclinationTest Class Reference
Public Member Functions
virtual bool run_tests ()
Override to run your unit tests.
Public Member Functions inherited from UnitTest
UnitTest ()=default
virtual ~UnitTest ()=default
void print_results ()
Prints results from running of unit tests.
Private Member Functions
bool autodeclination_check ()
Additional Inherited Members
Protected Member Functions inherited from UnitTest
virtual void _init (void)
Run before each unit test. Override to provide custom behavior.
virtual void _cleanup (void)
Run after each unit test. Override to provide custom behavior.
void _print_assert (const char *msg, const char *test, const char *file, int line)
void _print_compare (const char *msg, const char *v1_text, int v1, const char *v2_text, int v2, const char *file, int line)
Protected Attributes inherited from UnitTest
int _tests_run {0}
The number of individual unit tests run.
int _tests_failed {0}
The number of unit tests which failed.
int _tests_passed {0}
The number of unit tests which passed.
int _assertions {0}
Total number of assertions tested by all unit tests.
Detailed Description
Definition at line 16 of file test_autodeclination.cpp.
Member Function Documentation
bool AutoDeclinationTest::autodeclination_check () private
Definition at line 25 of file test_autodeclination.cpp.
References get_mag_declination(), and ut_compare_float.
Referenced by run_tests().
bool AutoDeclinationTest::run_tests () virtual
Override to run your unit tests.
Unit tests should be called using ut_run_test macro.
Returns
true: all unit tests succeeded, false: one or more unit tests failed
Implements UnitTest.
Definition at line 516 of file test_autodeclination.cpp.
References UnitTest::_tests_failed, autodeclination_check(), test_autodeclination(), ut_declare_test_c, and ut_run_test.
The documentation for this class was generated from the following file:
src/systemcmds/tests/test_autodeclination.cpp