PX4 Firmware: src/drivers/telemetry/frsky_telemetry/frsky_data.cpp File Reference
frsky_data.cpp File Reference
#include "frsky_data.h"
#include "common.h"
#include <stdlib.h>
#include <stdio.h>
#include <string.h>
#include <stdbool.h>
#include <lib/ecl/geo/geo.h>
#include <math.h>
#include <uORB/topics/battery_status.h>
#include <uORB/topics/sensor_combined.h>
#include <uORB/topics/vehicle_air_data.h>
#include <uORB/topics/vehicle_global_position.h>
#include <uORB/topics/vehicle_gps_position.h>
#include <uORB/topics/vehicle_status.h>
#include <drivers/drv_hrt.h>
Classes
struct frsky_subscription_data_s
Macros
#define frac(f) (f - (int)f)
Functions
bool frsky_init ()
Initializes the uORB subscriptions.
void frsky_deinit ()
static void frsky_send_startstop (int uart)
Sends a 0x5E start/stop byte.
static void frsky_send_byte (int uart, uint8_t value)
Sends one byte, performing byte-stuffing if necessary.
static void frsky_send_data (int uart, uint8_t id, int16_t data)
Sends one data id/value pair.
void frsky_update_topics ()
void frsky_send_frame1 (int uart)
Sends frame 1 (every 200ms): acceleration values, barometer altitude, temperature, battery voltage & current.
static float frsky_format_gps (float dec)
Formats the decimal latitude/longitude to the required degrees/minutes.
void frsky_send_frame2 (int uart)
Sends frame 2 (every 1000ms): GPS course, latitude, longitude, ground speed, GPS altitude, remaining battery level.
void frsky_send_frame3 (int uart)
Sends frame 3 (every 5000ms): GPS date & time.
bool frsky_parse_host (uint8_t *sbuf, int nbytes, struct adc_linkquality *v)
Variables
static struct frsky_subscription_data_s * subscription_data = NULL
Macro Definition Documentation
#define frac (f) (f - (int)f)
Definition at line 63 of file frsky_data.cpp.
Referenced by frsky_send_frame1(), and frsky_send_frame2().
Function Documentation
void frsky_deinit (void)
Definition at line 103 of file frsky_data.cpp.
References frsky_subscription_data_s::battery_status_sub, orb_unsubscribe(), frsky_subscription_data_s::sensor_sub, frsky_subscription_data_s::vehicle_global_position_sub, frsky_subscription_data_s::vehicle_gps_position_sub, and frsky_subscription_data_s::vehicle_status_sub.
Referenced by frsky_telemetry_thread_main().
static float frsky_format_gps (float dec) static
Formats the decimal latitude/longitude to the required degrees/minutes.
Definition at line 245 of file frsky_data.cpp.
References f().
Referenced by frsky_send_frame2().
bool frsky_init (void)
Initializes the uORB subscriptions.
Definition at line 86 of file frsky_data.cpp.
References frsky_subscription_data_s::battery_status, frsky_subscription_data_s::battery_status_sub, ORB_ID, orb_subscribe(), frsky_subscription_data_s::sensor_combined, frsky_subscription_data_s::sensor_sub, frsky_subscription_data_s::vehicle_air_data_sub, frsky_subscription_data_s::vehicle_global_position_sub, frsky_subscription_data_s::vehicle_gps_position, frsky_subscription_data_s::vehicle_gps_position_sub, and frsky_subscription_data_s::vehicle_status_sub.
Referenced by frsky_telemetry_thread_main().
bool frsky_parse_host (uint8_t * sbuf, int nbytes, struct adc_linkquality * v)
Definition at line 332 of file frsky_data.cpp.
References adc_linkquality::ad1, adc_linkquality::ad2, DATA, data, adc_linkquality::linkq, and state.
Referenced by frsky_telemetry_thread_main().
static void frsky_send_byte (int uart, uint8_t value) static
Sends one byte, performing byte-stuffing if necessary.
Definition at line 128 of file frsky_data.cpp.
References write().
Referenced by frsky_send_data().
static void frsky_send_data (int uart, uint8_t id, int16_t data) static
Sends one data id/value pair.
Definition at line 151 of file frsky_data.cpp.
References data, frsky_send_byte(), and frsky_send_startstop().
Referenced by frsky_send_frame1(), frsky_send_frame2(), and frsky_send_frame3().
void frsky_send_frame1 (int uart)
Sends frame 1 (every 200ms): acceleration values, barometer altitude, temperature, battery voltage & current.
Definition at line 216 of file frsky_data.cpp.
References sensor_combined_s::accelerometer_m_s2, frsky_subscription_data_s::airdata, vehicle_air_data_s::baro_alt_meter, frsky_subscription_data_s::battery_status, battery_status_s::current_a, frsky_subscription_data_s::current_flight_mode, vehicle_gps_position_s::fix_type, frac, FRSKY_ID_ACCEL_X, FRSKY_ID_ACCEL_Y, FRSKY_ID_ACCEL_Z, FRSKY_ID_BARO_ALT_AP, FRSKY_ID_BARO_ALT_BP, FRSKY_ID_CURRENT, FRSKY_ID_TEMP1, FRSKY_ID_TEMP2, FRSKY_ID_VFAS, frsky_send_data(), frsky_send_startstop(), get_telemetry_flight_mode(), vehicle_gps_position_s::satellites_used, frsky_subscription_data_s::sensor_combined, subscription_data, frsky_subscription_data_s::vehicle_gps_position, and battery_status_s::voltage_v.
Referenced by frsky_telemetry_thread_main().
void frsky_send_frame2 (int uart)
Sends frame 2 (every 1000ms): GPS course, latitude, longitude, ground speed, GPS altitude, remaining battery level.
Definition at line 255 of file frsky_data.cpp.
References vehicle_global_position_s::alt, vehicle_gps_position_s::alt, frsky_subscription_data_s::battery_status, f(), frac, frsky_format_gps(), FRSKY_ID_FUEL, FRSKY_ID_GPS_ALT_AP, FRSKY_ID_GPS_ALT_BP, FRSKY_ID_GPS_COURS_AP, FRSKY_ID_GPS_COURS_BP, FRSKY_ID_GPS_LAT_AP, FRSKY_ID_GPS_LAT_BP, FRSKY_ID_GPS_LAT_NS, FRSKY_ID_GPS_LONG_AP, FRSKY_ID_GPS_LONG_BP, FRSKY_ID_GPS_LONG_EW, FRSKY_ID_GPS_SEC, FRSKY_ID_GPS_SPEED_AP, FRSKY_ID_GPS_SPEED_BP, frsky_send_data(), frsky_send_startstop(), frsky_subscription_data_s::global_pos, gps, hrt_absolute_time(), vehicle_global_position_s::lat, vehicle_gps_position_s::lat, vehicle_global_position_s::lon, vehicle_gps_position_s::lon, M_PI_F, battery_status_s::remaining, vehicle_gps_position_s::time_utc_usec, vehicle_gps_position_s::timestamp, vehicle_global_position_s::timestamp, frsky_subscription_data_s::vehicle_gps_position, vehicle_global_position_s::vel_e, vehicle_global_position_s::vel_n, and vehicle_global_position_s::yaw.
Referenced by frsky_telemetry_thread_main().
void frsky_send_frame3 (int uart)
Sends frame 3 (every 5000ms): GPS date & time.
Definition at line 317 of file frsky_data.cpp.
References FRSKY_ID_GPS_DAY_MONTH, FRSKY_ID_GPS_HOUR_MIN, FRSKY_ID_GPS_SEC, FRSKY_ID_GPS_YEAR, frsky_send_data(), frsky_send_startstop(), vehicle_gps_position_s::time_utc_usec, and frsky_subscription_data_s::vehicle_gps_position.
Referenced by frsky_telemetry_thread_main().
static void frsky_send_startstop (int uart) static
Sends a 0x5E start/stop byte.
Definition at line 119 of file frsky_data.cpp.
References write().
Referenced by frsky_send_data(), frsky_send_frame1(), frsky_send_frame2(), and frsky_send_frame3().
void frsky_update_topics (void)
Definition at line 163 of file frsky_data.cpp.
References frsky_subscription_data_s::airdata, frsky_subscription_data_s::battery_status, frsky_subscription_data_s::battery_status_sub, frsky_subscription_data_s::current_flight_mode, frsky_subscription_data_s::global_pos, vehicle_status_s::nav_state, orb_check(), orb_copy(), ORB_ID, frsky_subscription_data_s::sensor_combined, frsky_subscription_data_s::sensor_sub, subscription_data, frsky_subscription_data_s::vehicle_air_data_sub, frsky_subscription_data_s::vehicle_global_position_sub, frsky_subscription_data_s::vehicle_gps_position, frsky_subscription_data_s::vehicle_gps_position_sub, and frsky_subscription_data_s::vehicle_status_sub.
Referenced by frsky_telemetry_thread_main().
Variable Documentation
struct frsky_subscription_data_s* subscription_data = NULL static
Definition at line 81 of file frsky_data.cpp.
Referenced by frsky_send_frame1(), and frsky_update_topics().