PX4 Firmware: uavcan_kinetis::clock::UtcSyncParams Struct Reference
uavcan_kinetis::clock::UtcSyncParams Struct Reference
UTC clock synchronization parameters.
#include <clock.hpp>
Public Member Functions
UtcSyncParams ()
Public Attributes
float offset_p
PPM per one usec error.
float rate_i
PPM per one PPM error for second.
float rate_error_corner_freq
float max_rate_correction_ppm
float lock_thres_rate_ppm
uavcan::UtcDuration lock_thres_offset
uavcan::UtcDuration min_jump
Min error to jump rather than change rate.
Detailed Description
UTC clock synchronization parameters.
Definition at line 52 of file clock.hpp.
Constructor & Destructor Documentation
UtcSyncParams()
uavcan_kinetis::clock::UtcSyncParams::UtcSyncParams () inline
Definition at line 61 of file clock.hpp.
References uavcan_kinetis::clock::getUtcJumpCount(), uavcan_kinetis::clock::getUtcRateCorrectionPPM(), uavcan_kinetis::clock::getUtcSyncParams(), uavcan_kinetis::clock::isUtcLocked(), and uavcan_kinetis::clock::setUtcSyncParams().
Member Data Documentation
lock_thres_offset
uavcan::UtcDuration uavcan_kinetis::clock::UtcSyncParams::lock_thres_offset
Definition at line 58 of file clock.hpp.
lock_thres_rate_ppm
float uavcan_kinetis::clock::UtcSyncParams::lock_thres_rate_ppm
Definition at line 57 of file clock.hpp.
max_rate_correction_ppm
float uavcan_kinetis::clock::UtcSyncParams::max_rate_correction_ppm
Definition at line 56 of file clock.hpp.
min_jump
uavcan::UtcDuration uavcan_kinetis::clock::UtcSyncParams::min_jump
Min error to jump rather than change rate.
Definition at line 59 of file clock.hpp.
offset_p
float uavcan_kinetis::clock::UtcSyncParams::offset_p
PPM per one usec error.
Definition at line 53 of file clock.hpp.
rate_error_corner_freq
float uavcan_kinetis::clock::UtcSyncParams::rate_error_corner_freq
Definition at line 55 of file clock.hpp.
rate_i
float uavcan_kinetis::clock::UtcSyncParams::rate_i
PPM per one PPM error for second.
Definition at line 54 of file clock.hpp.
The documentation for this struct was generated from the following file:
src/drivers/uavcan/uavcan_drivers/kinetis/driver/include/uavcan_kinetis/clock.hpp