PX4 Firmware: uavcan_stm32::bxcan Namespace Reference
uavcan_stm32::bxcan Namespace Reference
Classes
struct CanType
struct FilterRegisterType
struct RxMailboxType
struct TxMailboxType
Variables
CanType *const Can [UAVCAN_STM32_NUM_IFACES]
CANx register sets.
constexpr unsigned long MCR_INRQ = (1U << 0)
constexpr unsigned long MCR_SLEEP = (1U << 1)
constexpr unsigned long MCR_TXFP = (1U << 2)
constexpr unsigned long MCR_RFLM = (1U << 3)
constexpr unsigned long MCR_NART = (1U << 4)
constexpr unsigned long MCR_AWUM = (1U << 5)
constexpr unsigned long MCR_ABOM = (1U << 6)
constexpr unsigned long MCR_TTCM = (1U << 7)
constexpr unsigned long MCR_RESET = (1U << 15)
constexpr unsigned long MCR_DBF = (1U << 16)
constexpr unsigned long MSR_INAK = (1U << 0)
constexpr unsigned long MSR_SLAK = (1U << 1)
constexpr unsigned long MSR_ERRI = (1U << 2)
constexpr unsigned long MSR_WKUI = (1U << 3)
constexpr unsigned long MSR_SLAKI = (1U << 4)
constexpr unsigned long MSR_TXM = (1U << 8)
constexpr unsigned long MSR_RXM = (1U << 9)
constexpr unsigned long MSR_SAMP = (1U << 10)
constexpr unsigned long MSR_RX = (1U << 11)
constexpr unsigned long TSR_RQCP0 = (1U << 0)
constexpr unsigned long TSR_TXOK0 = (1U << 1)
constexpr unsigned long TSR_ALST0 = (1U << 2)
constexpr unsigned long TSR_TERR0 = (1U << 3)
constexpr unsigned long TSR_ABRQ0 = (1U << 7)
constexpr unsigned long TSR_RQCP1 = (1U << 8)
constexpr unsigned long TSR_TXOK1 = (1U << 9)
constexpr unsigned long TSR_ALST1 = (1U << 10)
constexpr unsigned long TSR_TERR1 = (1U << 11)
constexpr unsigned long TSR_ABRQ1 = (1U << 15)
constexpr unsigned long TSR_RQCP2 = (1U << 16)
constexpr unsigned long TSR_TXOK2 = (1U << 17)
constexpr unsigned long TSR_ALST2 = (1U << 18)
constexpr unsigned long TSR_TERR2 = (1U << 19)
constexpr unsigned long TSR_ABRQ2 = (1U << 23)
constexpr unsigned long TSR_CODE_SHIFT = (24U)
constexpr unsigned long TSR_CODE_MASK = (3U << TSR_CODE_SHIFT)
constexpr unsigned long TSR_TME0 = (1U << 26)
constexpr unsigned long TSR_TME1 = (1U << 27)
constexpr unsigned long TSR_TME2 = (1U << 28)
constexpr unsigned long TSR_LOW0 = (1U << 29)
constexpr unsigned long TSR_LOW1 = (1U << 30)
constexpr unsigned long TSR_LOW2 = (1U << 31)
constexpr unsigned long RFR_FMP_SHIFT = (0U)
constexpr unsigned long RFR_FMP_MASK = (3U << RFR_FMP_SHIFT)
constexpr unsigned long RFR_FULL = (1U << 3)
constexpr unsigned long RFR_FOVR = (1U << 4)
constexpr unsigned long RFR_RFOM = (1U << 5)
constexpr unsigned long IER_TMEIE = (1U << 0)
constexpr unsigned long IER_FMPIE0 = (1U << 1)
constexpr unsigned long IER_FFIE0 = (1U << 2)
constexpr unsigned long IER_FOVIE0 = (1U << 3)
constexpr unsigned long IER_FMPIE1 = (1U << 4)
constexpr unsigned long IER_FFIE1 = (1U << 5)
constexpr unsigned long IER_FOVIE1 = (1U << 6)
constexpr unsigned long IER_EWGIE = (1U << 8)
constexpr unsigned long IER_EPVIE = (1U << 9)
constexpr unsigned long IER_BOFIE = (1U << 10)
constexpr unsigned long IER_LECIE = (1U << 11)
constexpr unsigned long IER_ERRIE = (1U << 15)
constexpr unsigned long IER_WKUIE = (1U << 16)
constexpr unsigned long IER_SLKIE = (1U << 17)
constexpr unsigned long ESR_EWGF = (1U << 0)
constexpr unsigned long ESR_EPVF = (1U << 1)
constexpr unsigned long ESR_BOFF = (1U << 2)
constexpr unsigned long ESR_LEC_SHIFT = (4U)
constexpr unsigned long ESR_LEC_MASK = (7U << ESR_LEC_SHIFT)
constexpr unsigned long ESR_NOERROR = (0U << ESR_LEC_SHIFT)
constexpr unsigned long ESR_STUFFERROR = (1U << ESR_LEC_SHIFT)
constexpr unsigned long ESR_FORMERROR = (2U << ESR_LEC_SHIFT)
constexpr unsigned long ESR_ACKERROR = (3U << ESR_LEC_SHIFT)
constexpr unsigned long ESR_BRECERROR = (4U << ESR_LEC_SHIFT)
constexpr unsigned long ESR_BDOMERROR = (5U << ESR_LEC_SHIFT)
constexpr unsigned long ESR_CRCERRPR = (6U << ESR_LEC_SHIFT)
constexpr unsigned long ESR_SWERROR = (7U << ESR_LEC_SHIFT)
constexpr unsigned long ESR_TEC_SHIFT = (16U)
constexpr unsigned long ESR_TEC_MASK = (0xFFU << ESR_TEC_SHIFT)
constexpr unsigned long ESR_REC_SHIFT = (24U)
constexpr unsigned long ESR_REC_MASK = (0xFFU << ESR_REC_SHIFT)
constexpr unsigned long BTR_BRP_SHIFT = (0U)
constexpr unsigned long BTR_BRP_MASK = (0x03FFU << BTR_BRP_SHIFT)
constexpr unsigned long BTR_TS1_SHIFT = (16U)
constexpr unsigned long BTR_TS1_MASK = (0x0FU << BTR_TS1_SHIFT)
constexpr unsigned long BTR_TS2_SHIFT = (20U)
constexpr unsigned long BTR_TS2_MASK = (7U << BTR_TS2_SHIFT)
constexpr unsigned long BTR_SJW_SHIFT = (24U)
constexpr unsigned long BTR_SJW_MASK = (3U << BTR_SJW_SHIFT)
constexpr unsigned long BTR_LBKM = (1U << 30)
constexpr unsigned long BTR_SILM = (1U << 31)
constexpr unsigned long BTR_BRP_MAX = (1024U)
constexpr unsigned long BTR_TSEG1_MAX = (16U)
constexpr unsigned long BTR_TSEG2_MAX = (8U)
constexpr unsigned long TIR_TXRQ = (1U << 0)
constexpr unsigned long TIR_RTR = (1U << 1)
constexpr unsigned long TIR_IDE = (1U << 2)
constexpr unsigned long TIR_EXID_SHIFT = (3U)
constexpr unsigned long TIR_EXID_MASK = (0x1FFFFFFFU << TIR_EXID_SHIFT)
constexpr unsigned long TIR_STID_SHIFT = (21U)
constexpr unsigned long TIR_STID_MASK = (0x07FFU << TIR_STID_SHIFT)
constexpr unsigned long TDTR_DLC_SHIFT = (0U)
constexpr unsigned long TDTR_DLC_MASK = (0x0FU << TDTR_DLC_SHIFT)
constexpr unsigned long TDTR_TGT = (1U << 8)
constexpr unsigned long TDTR_TIME_SHIFT = (16U)
constexpr unsigned long TDTR_TIME_MASK = (0xFFFFU << TDTR_TIME_SHIFT)
constexpr unsigned long TDLR_DATA0_SHIFT = (0U)
constexpr unsigned long TDLR_DATA0_MASK = (0xFFU << TDLR_DATA0_SHIFT)
constexpr unsigned long TDLR_DATA1_SHIFT = (8U)
constexpr unsigned long TDLR_DATA1_MASK = (0xFFU << TDLR_DATA1_SHIFT)
constexpr unsigned long TDLR_DATA2_SHIFT = (16U)
constexpr unsigned long TDLR_DATA2_MASK = (0xFFU << TDLR_DATA2_SHIFT)
constexpr unsigned long TDLR_DATA3_SHIFT = (24U)
constexpr unsigned long TDLR_DATA3_MASK = (0xFFU << TDLR_DATA3_SHIFT)
constexpr unsigned long TDHR_DATA4_SHIFT = (0U)
constexpr unsigned long TDHR_DATA4_MASK = (0xFFU << TDHR_DATA4_SHIFT)
constexpr unsigned long TDHR_DATA5_SHIFT = (8U)
constexpr unsigned long TDHR_DATA5_MASK = (0xFFU << TDHR_DATA5_SHIFT)
constexpr unsigned long TDHR_DATA6_SHIFT = (16U)
constexpr unsigned long TDHR_DATA6_MASK = (0xFFU << TDHR_DATA6_SHIFT)
constexpr unsigned long TDHR_DATA7_SHIFT = (24U)
constexpr unsigned long TDHR_DATA7_MASK = (0xFFU << TDHR_DATA7_SHIFT)
constexpr unsigned long RIR_RTR = (1U << 1)
constexpr unsigned long RIR_IDE = (1U << 2)
constexpr unsigned long RIR_EXID_SHIFT = (3U)
constexpr unsigned long RIR_EXID_MASK = (0x1FFFFFFFU << RIR_EXID_SHIFT)
constexpr unsigned long RIR_STID_SHIFT = (21U)
constexpr unsigned long RIR_STID_MASK = (0x07FFU << RIR_STID_SHIFT)
constexpr unsigned long RDTR_DLC_SHIFT = (0U)
constexpr unsigned long RDTR_DLC_MASK = (0x0FU << RDTR_DLC_SHIFT)
constexpr unsigned long RDTR_FM_SHIFT = (8U)
constexpr unsigned long RDTR_FM_MASK = (0xFFU << RDTR_FM_SHIFT)
constexpr unsigned long RDTR_TIME_SHIFT = (16U)
constexpr unsigned long RDTR_TIME_MASK = (0xFFFFU << RDTR_TIME_SHIFT)
constexpr unsigned long RDLR_DATA0_SHIFT = (0U)
constexpr unsigned long RDLR_DATA0_MASK = (0xFFU << RDLR_DATA0_SHIFT)
constexpr unsigned long RDLR_DATA1_SHIFT = (8U)
constexpr unsigned long RDLR_DATA1_MASK = (0xFFU << RDLR_DATA1_SHIFT)
constexpr unsigned long RDLR_DATA2_SHIFT = (16U)
constexpr unsigned long RDLR_DATA2_MASK = (0xFFU << RDLR_DATA2_SHIFT)
constexpr unsigned long RDLR_DATA3_SHIFT = (24U)
constexpr unsigned long RDLR_DATA3_MASK = (0xFFU << RDLR_DATA3_SHIFT)
constexpr unsigned long RDHR_DATA4_SHIFT = (0U)
constexpr unsigned long RDHR_DATA4_MASK = (0xFFU << RDHR_DATA4_SHIFT)
constexpr unsigned long RDHR_DATA5_SHIFT = (8U)
constexpr unsigned long RDHR_DATA5_MASK = (0xFFU << RDHR_DATA5_SHIFT)
constexpr unsigned long RDHR_DATA6_SHIFT = (16U)
constexpr unsigned long RDHR_DATA6_MASK = (0xFFU << RDHR_DATA6_SHIFT)
constexpr unsigned long RDHR_DATA7_SHIFT = (24U)
constexpr unsigned long RDHR_DATA7_MASK = (0xFFU << RDHR_DATA7_SHIFT)
constexpr unsigned long FMR_FINIT = (1U << 0)
Variable Documentation
BTR_BRP_MASK
constexpr unsigned long uavcan_stm32::bxcan::BTR_BRP_MASK = (0x03FFU << BTR_BRP_SHIFT)
Definition at line 181 of file bxcan.hpp.
BTR_BRP_MAX
constexpr unsigned long uavcan_stm32::bxcan::BTR_BRP_MAX = (1024U)
Definition at line 191 of file bxcan.hpp.
BTR_BRP_SHIFT
constexpr unsigned long uavcan_stm32::bxcan::BTR_BRP_SHIFT = (0U)
Definition at line 180 of file bxcan.hpp.
BTR_LBKM
constexpr unsigned long uavcan_stm32::bxcan::BTR_LBKM = (1U << 30)
Definition at line 188 of file bxcan.hpp.
BTR_SILM
constexpr unsigned long uavcan_stm32::bxcan::BTR_SILM = (1U << 31)
Definition at line 189 of file bxcan.hpp.
Referenced by uavcan_stm32::CanIface::init().
BTR_SJW_MASK
constexpr unsigned long uavcan_stm32::bxcan::BTR_SJW_MASK = (3U << BTR_SJW_SHIFT)
Definition at line 187 of file bxcan.hpp.
BTR_SJW_SHIFT
constexpr unsigned long uavcan_stm32::bxcan::BTR_SJW_SHIFT = (24U)
Definition at line 186 of file bxcan.hpp.
BTR_TS1_MASK
constexpr unsigned long uavcan_stm32::bxcan::BTR_TS1_MASK = (0x0FU << BTR_TS1_SHIFT)
Definition at line 183 of file bxcan.hpp.
BTR_TS1_SHIFT
constexpr unsigned long uavcan_stm32::bxcan::BTR_TS1_SHIFT = (16U)
Definition at line 182 of file bxcan.hpp.
BTR_TS2_MASK
constexpr unsigned long uavcan_stm32::bxcan::BTR_TS2_MASK = (7U << BTR_TS2_SHIFT)
Definition at line 185 of file bxcan.hpp.
BTR_TS2_SHIFT
constexpr unsigned long uavcan_stm32::bxcan::BTR_TS2_SHIFT = (20U)
Definition at line 184 of file bxcan.hpp.
BTR_TSEG1_MAX
constexpr unsigned long uavcan_stm32::bxcan::BTR_TSEG1_MAX = (16U)
Definition at line 192 of file bxcan.hpp.
BTR_TSEG2_MAX
constexpr unsigned long uavcan_stm32::bxcan::BTR_TSEG2_MAX = (8U)
Definition at line 193 of file bxcan.hpp.
Can
CanType* const uavcan_stm32::bxcan::Can[UAVCAN_STM32_NUM_IFACES]
Initial value:
= {
    reinterpret_cast<CanType *>(0x40006400)
}
CANx register sets.
Definition at line 74 of file bxcan.hpp.
ESR_ACKERROR
constexpr unsigned long uavcan_stm32::bxcan::ESR_ACKERROR = (3U << ESR_LEC_SHIFT)
Definition at line 168 of file bxcan.hpp.
ESR_BDOMERROR
constexpr unsigned long uavcan_stm32::bxcan::ESR_BDOMERROR = (5U << ESR_LEC_SHIFT)
Definition at line 170 of file bxcan.hpp.
ESR_BOFF
constexpr unsigned long uavcan_stm32::bxcan::ESR_BOFF = (1U << 2)
Definition at line 162 of file bxcan.hpp.
ESR_BRECERROR
constexpr unsigned long uavcan_stm32::bxcan::ESR_BRECERROR = (4U << ESR_LEC_SHIFT)
Definition at line 169 of file bxcan.hpp.
ESR_CRCERRPR
constexpr unsigned long uavcan_stm32::bxcan::ESR_CRCERRPR = (6U << ESR_LEC_SHIFT)
Definition at line 171 of file bxcan.hpp.
ESR_EPVF
constexpr unsigned long uavcan_stm32::bxcan::ESR_EPVF = (1U << 1)
Definition at line 161 of file bxcan.hpp.
ESR_EWGF
constexpr unsigned long uavcan_stm32::bxcan::ESR_EWGF = (1U << 0)
Definition at line 160 of file bxcan.hpp.
ESR_FORMERROR
constexpr unsigned long uavcan_stm32::bxcan::ESR_FORMERROR = (2U << ESR_LEC_SHIFT)
Definition at line 167 of file bxcan.hpp.
ESR_LEC_MASK
constexpr unsigned long uavcan_stm32::bxcan::ESR_LEC_MASK = (7U << ESR_LEC_SHIFT)
Definition at line 164 of file bxcan.hpp.
Referenced by uavcan_stm32::CanIface::pollErrorFlagsFromISR().
ESR_LEC_SHIFT
constexpr unsigned long uavcan_stm32::bxcan::ESR_LEC_SHIFT = (4U)
Definition at line 163 of file bxcan.hpp.
Referenced by uavcan_stm32::CanIface::pollErrorFlagsFromISR().
ESR_NOERROR
constexpr unsigned long uavcan_stm32::bxcan::ESR_NOERROR = (0U << ESR_LEC_SHIFT)
Definition at line 165 of file bxcan.hpp.
ESR_REC_MASK
constexpr unsigned long uavcan_stm32::bxcan::ESR_REC_MASK = (0xFFU << ESR_REC_SHIFT)
Definition at line 176 of file bxcan.hpp.
ESR_REC_SHIFT
constexpr unsigned long uavcan_stm32::bxcan::ESR_REC_SHIFT = (24U)
Definition at line 175 of file bxcan.hpp.
ESR_STUFFERROR
constexpr unsigned long uavcan_stm32::bxcan::ESR_STUFFERROR = (1U << ESR_LEC_SHIFT)
Definition at line 166 of file bxcan.hpp.
ESR_SWERROR
constexpr unsigned long uavcan_stm32::bxcan::ESR_SWERROR = (7U << ESR_LEC_SHIFT)
Definition at line 172 of file bxcan.hpp.
ESR_TEC_MASK
constexpr unsigned long uavcan_stm32::bxcan::ESR_TEC_MASK = (0xFFU << ESR_TEC_SHIFT)
Definition at line 174 of file bxcan.hpp.
ESR_TEC_SHIFT
constexpr unsigned long uavcan_stm32::bxcan::ESR_TEC_SHIFT = (16U)
Definition at line 173 of file bxcan.hpp.
FMR_FINIT
constexpr unsigned long uavcan_stm32::bxcan::FMR_FINIT = (1U << 0)
Definition at line 277 of file bxcan.hpp.
Referenced by uavcan_stm32::CanIface::configureFilters(), and uavcan_stm32::CanIface::init().
IER_BOFIE
constexpr unsigned long uavcan_stm32::bxcan::IER_BOFIE = (1U << 10)
Definition at line 152 of file bxcan.hpp.
IER_EPVIE
constexpr unsigned long uavcan_stm32::bxcan::IER_EPVIE = (1U << 9)
Definition at line 151 of file bxcan.hpp.
IER_ERRIE
constexpr unsigned long uavcan_stm32::bxcan::IER_ERRIE = (1U << 15)
Definition at line 154 of file bxcan.hpp.
IER_EWGIE
constexpr unsigned long uavcan_stm32::bxcan::IER_EWGIE = (1U << 8)
Definition at line 150 of file bxcan.hpp.
IER_FFIE0
constexpr unsigned long uavcan_stm32::bxcan::IER_FFIE0 = (1U << 2)
Definition at line 145 of file bxcan.hpp.
IER_FFIE1
constexpr unsigned long uavcan_stm32::bxcan::IER_FFIE1 = (1U << 5)
Definition at line 148 of file bxcan.hpp.
IER_FMPIE0
constexpr unsigned long uavcan_stm32::bxcan::IER_FMPIE0 = (1U << 1)
Definition at line 144 of file bxcan.hpp.
Referenced by uavcan_stm32::CanIface::init().
IER_FMPIE1
constexpr unsigned long uavcan_stm32::bxcan::IER_FMPIE1 = (1U << 4)
Definition at line 147 of file bxcan.hpp.
Referenced by uavcan_stm32::CanIface::init().
IER_FOVIE0
constexpr unsigned long uavcan_stm32::bxcan::IER_FOVIE0 = (1U << 3)
Definition at line 146 of file bxcan.hpp.
IER_FOVIE1
constexpr unsigned long uavcan_stm32::bxcan::IER_FOVIE1 = (1U << 6)
Definition at line 149 of file bxcan.hpp.
IER_LECIE
constexpr unsigned long uavcan_stm32::bxcan::IER_LECIE = (1U << 11)
Definition at line 153 of file bxcan.hpp.
IER_SLKIE
constexpr unsigned long uavcan_stm32::bxcan::IER_SLKIE = (1U << 17)
Definition at line 156 of file bxcan.hpp.
IER_TMEIE
constexpr unsigned long uavcan_stm32::bxcan::IER_TMEIE = (1U << 0)
Definition at line 143 of file bxcan.hpp.
Referenced by uavcan_stm32::CanIface::init().
IER_WKUIE
constexpr unsigned long uavcan_stm32::bxcan::IER_WKUIE = (1U << 16)
Definition at line 155 of file bxcan.hpp.
MCR_ABOM
constexpr unsigned long uavcan_stm32::bxcan::MCR_ABOM = (1U << 6)
Definition at line 90 of file bxcan.hpp.
Referenced by uavcan_stm32::CanIface::init().
MCR_AWUM
constexpr unsigned long uavcan_stm32::bxcan::MCR_AWUM = (1U << 5)
Definition at line 89 of file bxcan.hpp.
Referenced by uavcan_stm32::CanIface::init().
MCR_DBF
constexpr unsigned long uavcan_stm32::bxcan::MCR_DBF = (1U << 16)
Definition at line 93 of file bxcan.hpp.
MCR_INRQ
constexpr unsigned long uavcan_stm32::bxcan::MCR_INRQ = (1U << 0)
Definition at line 84 of file bxcan.hpp.
Referenced by uavcan_stm32::CanIface::init().
MCR_NART
constexpr unsigned long uavcan_stm32::bxcan::MCR_NART = (1U << 4)
Definition at line 88 of file bxcan.hpp.
MCR_RESET
constexpr unsigned long uavcan_stm32::bxcan::MCR_RESET = (1U << 15)
Definition at line 92 of file bxcan.hpp.
Referenced by uavcan_stm32::CanIface::init().
MCR_RFLM
constexpr unsigned long uavcan_stm32::bxcan::MCR_RFLM = (1U << 3)
Definition at line 87 of file bxcan.hpp.
MCR_SLEEP
constexpr unsigned long uavcan_stm32::bxcan::MCR_SLEEP = (1U << 1)
Definition at line 85 of file bxcan.hpp.
Referenced by uavcan_stm32::CanIface::init().
MCR_TTCM
constexpr unsigned long uavcan_stm32::bxcan::MCR_TTCM = (1U << 7)
Definition at line 91 of file bxcan.hpp.
MCR_TXFP
constexpr unsigned long uavcan_stm32::bxcan::MCR_TXFP = (1U << 2)
Definition at line 86 of file bxcan.hpp.
MSR_ERRI
constexpr unsigned long uavcan_stm32::bxcan::MSR_ERRI = (1U << 2)
Definition at line 99 of file bxcan.hpp.
MSR_INAK
constexpr unsigned long uavcan_stm32::bxcan::MSR_INAK = (1U << 0)
Definition at line 97 of file bxcan.hpp.
Referenced by uavcan_stm32::CanIface::waitMsrINakBitStateChange().
MSR_RX
constexpr unsigned long uavcan_stm32::bxcan::MSR_RX = (1U << 11)
Definition at line 105 of file bxcan.hpp.
MSR_RXM
constexpr unsigned long uavcan_stm32::bxcan::MSR_RXM = (1U << 9)
Definition at line 103 of file bxcan.hpp.
MSR_SAMP
constexpr unsigned long uavcan_stm32::bxcan::MSR_SAMP = (1U << 10)
Definition at line 104 of file bxcan.hpp.
MSR_SLAK
constexpr unsigned long uavcan_stm32::bxcan::MSR_SLAK = (1U << 1)
Definition at line 98 of file bxcan.hpp.
MSR_SLAKI
constexpr unsigned long uavcan_stm32::bxcan::MSR_SLAKI = (1U << 4)
Definition at line 101 of file bxcan.hpp.
MSR_TXM
constexpr unsigned long uavcan_stm32::bxcan::MSR_TXM = (1U << 8)
Definition at line 102 of file bxcan.hpp.
MSR_WKUI
constexpr unsigned long uavcan_stm32::bxcan::MSR_WKUI = (1U << 3)
Definition at line 100 of file bxcan.hpp.
RDHR_DATA4_MASK
constexpr unsigned long uavcan_stm32::bxcan::RDHR_DATA4_MASK = (0xFFU << RDHR_DATA4_SHIFT)
Definition at line 267 of file bxcan.hpp.
RDHR_DATA4_SHIFT
constexpr unsigned long uavcan_stm32::bxcan::RDHR_DATA4_SHIFT = (0U)
Definition at line 266 of file bxcan.hpp.
RDHR_DATA5_MASK
constexpr unsigned long uavcan_stm32::bxcan::RDHR_DATA5_MASK = (0xFFU << RDHR_DATA5_SHIFT)
Definition at line 269 of file bxcan.hpp.
RDHR_DATA5_SHIFT
constexpr unsigned long uavcan_stm32::bxcan::RDHR_DATA5_SHIFT = (8U)
Definition at line 268 of file bxcan.hpp.
RDHR_DATA6_MASK
constexpr unsigned long uavcan_stm32::bxcan::RDHR_DATA6_MASK = (0xFFU << RDHR_DATA6_SHIFT)
Definition at line 271 of file bxcan.hpp.
RDHR_DATA6_SHIFT
constexpr unsigned long uavcan_stm32::bxcan::RDHR_DATA6_SHIFT = (16U)
Definition at line 270 of file bxcan.hpp.
RDHR_DATA7_MASK
constexpr unsigned long uavcan_stm32::bxcan::RDHR_DATA7_MASK = (0xFFU << RDHR_DATA7_SHIFT)
Definition at line 273 of file bxcan.hpp.
RDHR_DATA7_SHIFT
constexpr unsigned long uavcan_stm32::bxcan::RDHR_DATA7_SHIFT = (24U)
Definition at line 272 of file bxcan.hpp.
RDLR_DATA0_MASK
constexpr unsigned long uavcan_stm32::bxcan::RDLR_DATA0_MASK = (0xFFU << RDLR_DATA0_SHIFT)
Definition at line 256 of file bxcan.hpp.
RDLR_DATA0_SHIFT
constexpr unsigned long uavcan_stm32::bxcan::RDLR_DATA0_SHIFT = (0U)
Definition at line 255 of file bxcan.hpp.
RDLR_DATA1_MASK
constexpr unsigned long uavcan_stm32::bxcan::RDLR_DATA1_MASK = (0xFFU << RDLR_DATA1_SHIFT)
Definition at line 258 of file bxcan.hpp.
RDLR_DATA1_SHIFT
constexpr unsigned long uavcan_stm32::bxcan::RDLR_DATA1_SHIFT = (8U)
Definition at line 257 of file bxcan.hpp.
RDLR_DATA2_MASK
constexpr unsigned long uavcan_stm32::bxcan::RDLR_DATA2_MASK = (0xFFU << RDLR_DATA2_SHIFT)
Definition at line 260 of file bxcan.hpp.
RDLR_DATA2_SHIFT
constexpr unsigned long uavcan_stm32::bxcan::RDLR_DATA2_SHIFT = (16U)
Definition at line 259 of file bxcan.hpp.
RDLR_DATA3_MASK
constexpr unsigned long uavcan_stm32::bxcan::RDLR_DATA3_MASK = (0xFFU << RDLR_DATA3_SHIFT)
Definition at line 262 of file bxcan.hpp.
RDLR_DATA3_SHIFT
constexpr unsigned long uavcan_stm32::bxcan::RDLR_DATA3_SHIFT = (24U)
Definition at line 261 of file bxcan.hpp.
RDTR_DLC_MASK
constexpr unsigned long uavcan_stm32::bxcan::RDTR_DLC_MASK = (0x0FU << RDTR_DLC_SHIFT)
Definition at line 247 of file bxcan.hpp.
RDTR_DLC_SHIFT
constexpr unsigned long uavcan_stm32::bxcan::RDTR_DLC_SHIFT = (0U)
Definition at line 246 of file bxcan.hpp.
RDTR_FM_MASK
constexpr unsigned long uavcan_stm32::bxcan::RDTR_FM_MASK = (0xFFU << RDTR_FM_SHIFT)
Definition at line 249 of file bxcan.hpp.
RDTR_FM_SHIFT
constexpr unsigned long uavcan_stm32::bxcan::RDTR_FM_SHIFT = (8U)
Definition at line 248 of file bxcan.hpp.
RDTR_TIME_MASK
constexpr unsigned long uavcan_stm32::bxcan::RDTR_TIME_MASK = (0xFFFFU << RDTR_TIME_SHIFT)
Definition at line 251 of file bxcan.hpp.
RDTR_TIME_SHIFT
constexpr unsigned long uavcan_stm32::bxcan::RDTR_TIME_SHIFT = (16U)
Definition at line 250 of file bxcan.hpp.
RFR_FMP_MASK
constexpr unsigned long uavcan_stm32::bxcan::RFR_FMP_MASK = (3U << RFR_FMP_SHIFT)
Definition at line 136 of file bxcan.hpp.
Referenced by uavcan_stm32::CanIface::handleRxInterrupt().
RFR_FMP_SHIFT
constexpr unsigned long uavcan_stm32::bxcan::RFR_FMP_SHIFT = (0U)
Definition at line 135 of file bxcan.hpp.
RFR_FOVR
constexpr unsigned long uavcan_stm32::bxcan::RFR_FOVR = (1U << 4)
Definition at line 138 of file bxcan.hpp.
Referenced by uavcan_stm32::CanIface::handleRxInterrupt().
RFR_FULL
constexpr unsigned long uavcan_stm32::bxcan::RFR_FULL = (1U << 3)
Definition at line 137 of file bxcan.hpp.
Referenced by uavcan_stm32::CanIface::handleRxInterrupt().
RFR_RFOM
constexpr unsigned long uavcan_stm32::bxcan::RFR_RFOM = (1U << 5)
Definition at line 139 of file bxcan.hpp.
Referenced by uavcan_stm32::CanIface::handleRxInterrupt().
RIR_EXID_MASK
constexpr unsigned long uavcan_stm32::bxcan::RIR_EXID_MASK = (0x1FFFFFFFU << RIR_EXID_SHIFT)
Definition at line 240 of file bxcan.hpp.
RIR_EXID_SHIFT
constexpr unsigned long uavcan_stm32::bxcan::RIR_EXID_SHIFT = (3U)
Definition at line 239 of file bxcan.hpp.
RIR_IDE
constexpr unsigned long uavcan_stm32::bxcan::RIR_IDE = (1U << 2)
Definition at line 238 of file bxcan.hpp.
Referenced by uavcan_stm32::CanIface::configureFilters(), and uavcan_stm32::CanIface::handleRxInterrupt().
RIR_RTR
constexpr unsigned long uavcan_stm32::bxcan::RIR_RTR = (1U << 1)
Definition at line 237 of file bxcan.hpp.
Referenced by uavcan_stm32::CanIface::configureFilters(), and uavcan_stm32::CanIface::handleRxInterrupt().
RIR_STID_MASK
constexpr unsigned long uavcan_stm32::bxcan::RIR_STID_MASK = (0x07FFU << RIR_STID_SHIFT)
Definition at line 242 of file bxcan.hpp.
RIR_STID_SHIFT
constexpr unsigned long uavcan_stm32::bxcan::RIR_STID_SHIFT = (21U)
Definition at line 241 of file bxcan.hpp.
TDHR_DATA4_MASK
constexpr unsigned long uavcan_stm32::bxcan::TDHR_DATA4_MASK = (0xFFU << TDHR_DATA4_SHIFT)
Definition at line 227 of file bxcan.hpp.
TDHR_DATA4_SHIFT
constexpr unsigned long uavcan_stm32::bxcan::TDHR_DATA4_SHIFT = (0U)
Definition at line 226 of file bxcan.hpp.
TDHR_DATA5_MASK
constexpr unsigned long uavcan_stm32::bxcan::TDHR_DATA5_MASK = (0xFFU << TDHR_DATA5_SHIFT)
Definition at line 229 of file bxcan.hpp.
TDHR_DATA5_SHIFT
constexpr unsigned long uavcan_stm32::bxcan::TDHR_DATA5_SHIFT = (8U)
Definition at line 228 of file bxcan.hpp.
TDHR_DATA6_MASK
constexpr unsigned long uavcan_stm32::bxcan::TDHR_DATA6_MASK = (0xFFU << TDHR_DATA6_SHIFT)
Definition at line 231 of file bxcan.hpp.
TDHR_DATA6_SHIFT
constexpr unsigned long uavcan_stm32::bxcan::TDHR_DATA6_SHIFT = (16U)
Definition at line 230 of file bxcan.hpp.
TDHR_DATA7_MASK
constexpr unsigned long uavcan_stm32::bxcan::TDHR_DATA7_MASK = (0xFFU << TDHR_DATA7_SHIFT)
Definition at line 233 of file bxcan.hpp.
TDHR_DATA7_SHIFT
constexpr unsigned long uavcan_stm32::bxcan::TDHR_DATA7_SHIFT = (24U)
Definition at line 232 of file bxcan.hpp.
TDLR_DATA0_MASK
constexpr unsigned long uavcan_stm32::bxcan::TDLR_DATA0_MASK = (0xFFU << TDLR_DATA0_SHIFT)
Definition at line 216 of file bxcan.hpp.
TDLR_DATA0_SHIFT
constexpr unsigned long uavcan_stm32::bxcan::TDLR_DATA0_SHIFT = (0U)
Definition at line 215 of file bxcan.hpp.
TDLR_DATA1_MASK
constexpr unsigned long uavcan_stm32::bxcan::TDLR_DATA1_MASK = (0xFFU << TDLR_DATA1_SHIFT)
Definition at line 218 of file bxcan.hpp.
TDLR_DATA1_SHIFT
constexpr unsigned long uavcan_stm32::bxcan::TDLR_DATA1_SHIFT = (8U)
Definition at line 217 of file bxcan.hpp.
TDLR_DATA2_MASK
constexpr unsigned long uavcan_stm32::bxcan::TDLR_DATA2_MASK = (0xFFU << TDLR_DATA2_SHIFT)
Definition at line 220 of file bxcan.hpp.
TDLR_DATA2_SHIFT
constexpr unsigned long uavcan_stm32::bxcan::TDLR_DATA2_SHIFT = (16U)
Definition at line 219 of file bxcan.hpp.
TDLR_DATA3_MASK
constexpr unsigned long uavcan_stm32::bxcan::TDLR_DATA3_MASK = (0xFFU << TDLR_DATA3_SHIFT)
Definition at line 222 of file bxcan.hpp.
TDLR_DATA3_SHIFT
constexpr unsigned long uavcan_stm32::bxcan::TDLR_DATA3_SHIFT = (24U)
Definition at line 221 of file bxcan.hpp.
TDTR_DLC_MASK
constexpr unsigned long uavcan_stm32::bxcan::TDTR_DLC_MASK = (0x0FU << TDTR_DLC_SHIFT)
Definition at line 208 of file bxcan.hpp.
TDTR_DLC_SHIFT
constexpr unsigned long uavcan_stm32::bxcan::TDTR_DLC_SHIFT = (0U)
Definition at line 207 of file bxcan.hpp.
TDTR_TGT
constexpr unsigned long uavcan_stm32::bxcan::TDTR_TGT = (1U << 8)
Definition at line 209 of file bxcan.hpp.
TDTR_TIME_MASK
constexpr unsigned long uavcan_stm32::bxcan::TDTR_TIME_MASK = (0xFFFFU << TDTR_TIME_SHIFT)
Definition at line 211 of file bxcan.hpp.
TDTR_TIME_SHIFT
constexpr unsigned long uavcan_stm32::bxcan::TDTR_TIME_SHIFT = (16U)
Definition at line 210 of file bxcan.hpp.
TIR_EXID_MASK
constexpr unsigned long uavcan_stm32::bxcan::TIR_EXID_MASK = (0x1FFFFFFFU << TIR_EXID_SHIFT)
Definition at line 201 of file bxcan.hpp.
TIR_EXID_SHIFT
constexpr unsigned long uavcan_stm32::bxcan::TIR_EXID_SHIFT = (3U)
Definition at line 200 of file bxcan.hpp.
TIR_IDE
constexpr unsigned long uavcan_stm32::bxcan::TIR_IDE = (1U << 2)
Definition at line 199 of file bxcan.hpp.
Referenced by uavcan_stm32::CanIface::send().
TIR_RTR
constexpr unsigned long uavcan_stm32::bxcan::TIR_RTR = (1U << 1)
Definition at line 198 of file bxcan.hpp.
Referenced by uavcan_stm32::CanIface::send().
TIR_STID_MASK
constexpr unsigned long uavcan_stm32::bxcan::TIR_STID_MASK = (0x07FFU << TIR_STID_SHIFT)
Definition at line 203 of file bxcan.hpp.
TIR_STID_SHIFT
constexpr unsigned long uavcan_stm32::bxcan::TIR_STID_SHIFT = (21U)
Definition at line 202 of file bxcan.hpp.
TIR_TXRQ
constexpr unsigned long uavcan_stm32::bxcan::TIR_TXRQ = (1U << 0)
Definition at line 197 of file bxcan.hpp.
Referenced by uavcan_stm32::CanIface::send().
TSR_ABRQ0
constexpr unsigned long uavcan_stm32::bxcan::TSR_ABRQ0 = (1U << 7)
Definition at line 113 of file bxcan.hpp.
Referenced by uavcan_stm32::CanIface::RxQueue::reset().
TSR_ABRQ1
constexpr unsigned long uavcan_stm32::bxcan::TSR_ABRQ1 = (1U << 15)
Definition at line 118 of file bxcan.hpp.
Referenced by uavcan_stm32::CanIface::RxQueue::reset().
TSR_ABRQ2
constexpr unsigned long uavcan_stm32::bxcan::TSR_ABRQ2 = (1U << 23)
Definition at line 123 of file bxcan.hpp.
Referenced by uavcan_stm32::CanIface::RxQueue::reset().
TSR_ALST0
constexpr unsigned long uavcan_stm32::bxcan::TSR_ALST0 = (1U << 2)
Definition at line 111 of file bxcan.hpp.
TSR_ALST1
constexpr unsigned long uavcan_stm32::bxcan::TSR_ALST1 = (1U << 10)
Definition at line 116 of file bxcan.hpp.
TSR_ALST2
constexpr unsigned long uavcan_stm32::bxcan::TSR_ALST2 = (1U << 18)
Definition at line 121 of file bxcan.hpp.
TSR_CODE_MASK
constexpr unsigned long uavcan_stm32::bxcan::TSR_CODE_MASK = (3U << TSR_CODE_SHIFT)
Definition at line 125 of file bxcan.hpp.
TSR_CODE_SHIFT
constexpr unsigned long uavcan_stm32::bxcan::TSR_CODE_SHIFT = (24U)
Definition at line 124 of file bxcan.hpp.
TSR_LOW0
constexpr unsigned long uavcan_stm32::bxcan::TSR_LOW0 = (1U << 29)
Definition at line 129 of file bxcan.hpp.
TSR_LOW1
constexpr unsigned long uavcan_stm32::bxcan::TSR_LOW1 = (1U << 30)
Definition at line 130 of file bxcan.hpp.
TSR_LOW2
constexpr unsigned long uavcan_stm32::bxcan::TSR_LOW2 = (1U << 31)
Definition at line 131 of file bxcan.hpp.
TSR_RQCP0
constexpr unsigned long uavcan_stm32::bxcan::TSR_RQCP0 = (1U << 0)
Definition at line 109 of file bxcan.hpp.
Referenced by uavcan_stm32::CanIface::handleTxInterrupt().
TSR_RQCP1
constexpr unsigned long uavcan_stm32::bxcan::TSR_RQCP1 = (1U << 8)
Definition at line 114 of file bxcan.hpp.
Referenced by uavcan_stm32::CanIface::handleTxInterrupt().
TSR_RQCP2
constexpr unsigned long uavcan_stm32::bxcan::TSR_RQCP2 = (1U << 16)
Definition at line 119 of file bxcan.hpp.
Referenced by uavcan_stm32::CanIface::handleTxInterrupt().
TSR_TERR0
constexpr unsigned long uavcan_stm32::bxcan::TSR_TERR0 = (1U << 3)
Definition at line 112 of file bxcan.hpp.
TSR_TERR1
constexpr unsigned long uavcan_stm32::bxcan::TSR_TERR1 = (1U << 11)
Definition at line 117 of file bxcan.hpp.
TSR_TERR2
constexpr unsigned long uavcan_stm32::bxcan::TSR_TERR2 = (1U << 19)
Definition at line 122 of file bxcan.hpp.
TSR_TME0
constexpr unsigned long uavcan_stm32::bxcan::TSR_TME0 = (1U << 26)
Definition at line 126 of file bxcan.hpp.
Referenced by uavcan_stm32::CanIface::canAcceptNewTxFrame(), and uavcan_stm32::CanIface::send().
TSR_TME1
constexpr unsigned long uavcan_stm32::bxcan::TSR_TME1 = (1U << 27)
Definition at line 127 of file bxcan.hpp.
Referenced by uavcan_stm32::CanIface::canAcceptNewTxFrame(), and uavcan_stm32::CanIface::send().
TSR_TME2
constexpr unsigned long uavcan_stm32::bxcan::TSR_TME2 = (1U << 28)
Definition at line 128 of file bxcan.hpp.
Referenced by uavcan_stm32::CanIface::canAcceptNewTxFrame(), and uavcan_stm32::CanIface::send().
TSR_TXOK0
constexpr unsigned long uavcan_stm32::bxcan::TSR_TXOK0 = (1U << 1)
Definition at line 110 of file bxcan.hpp.
Referenced by uavcan_stm32::CanIface::handleTxInterrupt().
TSR_TXOK1
constexpr unsigned long uavcan_stm32::bxcan::TSR_TXOK1 = (1U << 9)
Definition at line 115 of file bxcan.hpp.
Referenced by uavcan_stm32::CanIface::handleTxInterrupt().
TSR_TXOK2
constexpr unsigned long uavcan_stm32::bxcan::TSR_TXOK2 = (1U << 17)
Definition at line 120 of file bxcan.hpp.
Referenced by uavcan_stm32::CanIface::handleTxInterrupt().