PX4 Firmware: UavcanNode Class Reference
UavcanNode Class Reference
A UAVCAN node.
#include <uavcan_main.hpp>
Public Types
enum eServerAction {
None, Start, Stop, CheckFW,
Busy
}
typedef uavcan_stm32::CanInitHelper< RxQueueLenPerIface > CanInitHelper
typedef uavcan::Node< MemPoolSize > Node
typedef uavcan_stm32::CanInitHelper< RxQueueLenPerIface > CanInitHelper
typedef uavcan::protocol::file::BeginFirmwareUpdate BeginFirmwareUpdate
Public Types inherited from device::Device
enum DeviceBusType { DeviceBusType_UNKNOWN = 0, DeviceBusType_I2C = 1, DeviceBusType_SPI = 2, DeviceBusType_UAVCAN = 3 }
Device bus types for DEVID.
Public Member Functions
UavcanNode (uavcan::ICanDriver &can_driver, uavcan::ISystemClock &system_clock)
virtual ~UavcanNode ()
virtual int ioctl (file *filp, int cmd, unsigned long arg)
uavcan::Node & get_node ()
void subscribe ()
int teardown ()
int arm_actuators (bool arm)
void print_info ()
void shrink ()
void hardpoint_controller_set (uint8_t hardpoint_id, uint16_t command)
int fw_server (eServerAction action)
void attachITxQueueInjector (ITxQueueInjector *injector)
int list_params (int remote_node_id)
int save_params (int remote_node_id)
int set_param (int remote_node_id, const char *name, char *value)
int get_param (int remote_node_id, const char *name)
int reset_node (int remote_node_id)
UavcanNode (uavcan::ICanDriver &can_driver, uavcan::ISystemClock &system_clock)
virtual ~UavcanNode ()
virtual int ioctl (file *filp, int cmd, unsigned long arg)
Node & get_node ()
int teardown ()
void print_info ()
Public Member Functions inherited from device::CDev
CDev (const char *name, const char *devname)
Constructor.
virtual ~CDev ()
virtual int init ()
Initialise the driver and make it ready for use.
virtual int open (file_t *filep)
Handle an open of the device.
virtual int close (file_t *filep)
Handle a close of the device.
virtual ssize_t read (file_t *filep, char *buffer, size_t buflen)
Perform a read from the device.
virtual ssize_t write (file_t *filep, const char *buffer, size_t buflen)
Perform a write to the device.
virtual off_t seek (file_t *filep, off_t offset, int whence)
Perform a logical seek operation on the device.
virtual int ioctl (file_t *filep, int cmd, unsigned long arg)
Perform an ioctl operation on the device.
virtual int poll (file_t *filep, px4_pollfd_struct_t *fds, bool setup)
Perform a poll setup/teardown operation.
Public Member Functions inherited from device::Device
virtual ~Device ()=default
Destructor.
virtual int read (unsigned address, void *data, unsigned count)
Read directly from the device.
virtual int write (unsigned address, void *data, unsigned count)
Write directly to the device.
virtual int ioctl (unsigned operation, unsigned &arg)
Perform a device-specific operation.
uint8_t get_device_bus ()
Return the bus ID the device is connected to.
DeviceBusType get_device_bus_type ()
Return the bus type the device is connected to.
uint8_t get_device_address ()
Return the bus address of the device.
void set_device_address (int address)
void set_device_type (uint8_t devtype)
Set the device type.
virtual bool external ()
Static Public Member Functions
static int start (uavcan::NodeID node_id, uint32_t bitrate)
static int control_callback (uintptr_t handle, uint8_t control_group, uint8_t control_index, float &input)
static UavcanNode * instance ()
static int getHardwareVersion (uavcan::protocol::HardwareVersion &hwver)
static int start (uavcan::NodeID node_id, uint32_t bitrate)
static UavcanNode * instance ()
Public Attributes
int32_t active_bitrate
uavcan::TimerEventForwarder< void(*)(const uavcan::TimerEvent &)> _reset_timer
Private Types
typedef uavcan::MethodBinder< UavcanNode *, void(UavcanNode::*)(const uavcan::TimerEvent &)> TimerCallback
typedef uavcan::MethodBinder< UavcanNode *, void(UavcanNode::*)(const uavcan::ServiceCallResult< uavcan::protocol::param::GetSet > &)> GetSetCallback
typedef uavcan::MethodBinder< UavcanNode *, void(UavcanNode::*)(const uavcan::ServiceCallResult< uavcan::protocol::param::ExecuteOpcode > &)> ExecuteOpcodeCallback
typedef uavcan::MethodBinder< UavcanNode *, void(UavcanNode::*)(const uavcan::ServiceCallResult< uavcan::protocol::RestartNode > &)> RestartNodeCallback
typedef uavcan::MethodBinder< UavcanNode *, void(UavcanNode::*)(const uavcan::ReceivedDataStructure< UavcanNode::BeginFirmwareUpdate::Request > &, uavcan::ServiceResponseDataStructure< UavcanNode::BeginFirmwareUpdate::Response > &)> BeginFirmwareUpdateCallBack
Private Member Functions
void fill_node_info ()
int init (uavcan::NodeID node_id)
void node_spin_once ()
int run ()
int add_poll_fd (int fd)
add a fd to poll list, returning index into _poll_fds[]
int start_fw_server ()
int stop_fw_server ()
int request_fw_check ()
int print_params (uavcan::protocol::param::GetSet::Response &resp)
int get_set_param (int nodeid, const char *name, uavcan::protocol::param::GetSet::Request &req)
void update_params ()
void set_setget_response (uavcan::protocol::param::GetSet::Response *resp)
void free_setget_response (void)
void handle_time_sync (const uavcan::TimerEvent &)
void cb_setget (const uavcan::ServiceCallResult< uavcan::protocol::param::GetSet > &result)
void cb_opcode (const uavcan::ServiceCallResult< uavcan::protocol::param::ExecuteOpcode > &result)
void cb_restart (const uavcan::ServiceCallResult< uavcan::protocol::RestartNode > &result)
void fill_node_info ()
int init (uavcan::NodeID node_id)
void node_spin_once ()
int run ()
int add_poll_fd (int fd)
add a fd to poll list, returning index into _poll_fds[]
void cb_beginfirmware_update (const uavcan::ReceivedDataStructure< UavcanNode::BeginFirmwareUpdate::Request > &req, uavcan::ServiceResponseDataStructure< UavcanNode::BeginFirmwareUpdate::Response > &rsp)
Private Attributes
int _task = -1
handle to the OS task
bool _task_should_exit = false
flag to indicate to tear down the CAN driver
volatile eServerAction _fw_server_action
int _fw_server_status
int _armed_sub = -1
uORB subscription of the arming status
actuator_armed_s _armed = {}
the arming request of the system
bool _is_armed = false
the arming status of the actuators on the bus
int _test_motor_sub = -1
uORB subscription of the test_motor status
test_motor_s _test_motor = {}
bool _test_in_progress = false
unsigned _output_count = 0
number of actuators currently available
uavcan_node::Allocator _pool_allocator
uavcan::Node _node
library instance
pthread_mutex_t _node_mutex
px4_sem_t _server_command_sem
UavcanEscController _esc_controller
UavcanHardpointController _hardpoint_controller
uavcan::GlobalTimeSyncMaster _time_sync_master
uavcan::GlobalTimeSyncSlave _time_sync_slave
uavcan::NodeStatusMonitor _node_status_monitor
List< IUavcanSensorBridge * > _sensor_bridges
List of active sensor bridges.
MixerGroup * _mixers = nullptr
ITxQueueInjector * _tx_injector
uint32_t _groups_required = 0
uint32_t _groups_subscribed = 0
int _control_subs [NUM_ACTUATOR_CONTROL_GROUPS_UAVCAN]
actuator_controls_s _controls [NUM_ACTUATOR_CONTROL_GROUPS_UAVCAN] = {}
orb_id_t _control_topics [NUM_ACTUATOR_CONTROL_GROUPS_UAVCAN] = {}
pollfd _poll_fds [UAVCAN_NUM_POLL_FDS] = {}
unsigned _poll_fds_num = 0
int32_t _idle_throttle_when_armed = 0
int _actuator_direct_sub = -1
uORB subscription of the actuator_direct topic
uint8_t _actuator_direct_poll_fd_num = 0
actuator_direct_s _actuator_direct = {}
actuator_outputs_s _outputs = {}
perf_counter_t _perf_control_latency
bool _airmode = false
uint8_t _poll_ids [NUM_ACTUATOR_CONTROL_GROUPS_UAVCAN]
uavcan::TimerEventForwarder< TimerCallback > _master_timer
bool _callback_success
uavcan::protocol::param::GetSet::Response * _setget_response
Node _node
library instance
uavcan::ServiceServer< BeginFirmwareUpdate, BeginFirmwareUpdateCallBack > _fw_update_listner
Static Private Attributes
static constexpr unsigned MaxBitRatePerSec = 1000000
static constexpr unsigned bitPerFrame = 148
static constexpr unsigned FramePerSecond = MaxBitRatePerSec / bitPerFrame
static constexpr unsigned FramePerMSecond = ((FramePerSecond / 1000) + 1)
static constexpr unsigned PollTimeoutMs = 3
static constexpr unsigned RxQueueLenPerIface = FramePerMSecond * PollTimeoutMs
static constexpr unsigned StackSize = 2400
static UavcanNode * _instance
singleton pointer
static constexpr unsigned MemPoolSize = 2048
Additional Inherited Members
Protected Member Functions inherited from device::CDev
virtual pollevent_t poll_state (file_t *filep)
Check the current state of the device for poll events from the perspective of the file.
virtual void poll_notify (pollevent_t events)
Report new poll events.
virtual void poll_notify_one (px4_pollfd_struct_t *fds, pollevent_t events)
Internal implementation of poll_notify.
virtual int open_first (file_t *filep)
Notification of the first open.
virtual int close_last (file_t *filep)
Notification of the last close.
virtual int register_class_devname (const char *class_devname)
Register a class device name, automatically adding device class instance suffix if need be.
virtual int unregister_class_devname (const char *class_devname, unsigned class_instance)
Register a class device name, automatically adding device class instance suffix if need be.
const char * get_devname ()
Get the device name.
void lock ()
Take the driver lock.
void unlock ()
Release the driver lock.
Protected Member Functions inherited from device::Device
Device (const char *name)
Device (DeviceBusType bus_type, uint8_t bus, uint8_t address, uint8_t devtype=0)
Device (const Device &)=delete
Device & operator= (const Device &)=delete
Device (Device &&)=delete
Device & operator= (Device &&)=delete
Protected Attributes inherited from device::CDev
px4_sem_t _lock
lock to protect access to all class members (also for derived classes)
bool _pub_blocked {false}
true if publishing should be blocked
Protected Attributes inherited from device::Device
union DeviceId _device_id
device identifier information
const char * _name
driver name
bool _debug_enabled {false}
if true, debug messages are printed
Static Protected Attributes inherited from device::CDev
static const px4_file_operations_t fops = {}
Pointer to the default cdev file operations table; useful for registering clone devices etc.
Detailed Description
A UAVCAN node.
Definition at line 80 of file uavcan_main.hpp.
Member Typedef Documentation
typedef uavcan::protocol::file::BeginFirmwareUpdate UavcanNode::BeginFirmwareUpdate
Definition at line 95 of file uavcannode_main.hpp.
typedef uavcan::MethodBinder<UavcanNode *, void (UavcanNode::*)(const uavcan::ReceivedDataStructure<UavcanNode::BeginFirmwareUpdate::Request> &, uavcan::ServiceResponseDataStructure<UavcanNode::BeginFirmwareUpdate::Response> &)> UavcanNode::BeginFirmwareUpdateCallBack private
Definition at line 141 of file uavcannode_main.hpp.
typedef uavcan_stm32::CanInitHelper<RxQueueLenPerIface> UavcanNode::CanInitHelper
Definition at line 94 of file uavcannode_main.hpp.
typedef uavcan_stm32::CanInitHelper<RxQueueLenPerIface> UavcanNode::CanInitHelper
Definition at line 106 of file uavcan_main.hpp.
typedef uavcan::MethodBinder<UavcanNode *, void (UavcanNode::*)(const uavcan::ServiceCallResult<uavcan::protocol::param::ExecuteOpcode> &)> UavcanNode::ExecuteOpcodeCallback private
Definition at line 228 of file uavcan_main.hpp.
typedef uavcan::MethodBinder<UavcanNode *, void (UavcanNode::*)(const uavcan::ServiceCallResult<uavcan::protocol::param::GetSet> &)> UavcanNode::GetSetCallback private
Definition at line 226 of file uavcan_main.hpp.
typedef uavcan::Node<MemPoolSize> UavcanNode::Node
Definition at line 93 of file uavcannode_main.hpp.
typedef uavcan::MethodBinder<UavcanNode *, void (UavcanNode::*)(const uavcan::ServiceCallResult<uavcan::protocol::RestartNode> &)> UavcanNode::RestartNodeCallback private
Definition at line 230 of file uavcan_main.hpp.
typedef uavcan::MethodBinder<UavcanNode *, void (UavcanNode::*)(const uavcan::TimerEvent &)> UavcanNode::TimerCallback private
Definition at line 220 of file uavcan_main.hpp.
Member Enumeration Documentation
enum UavcanNode::eServerAction
Enumerator
None
Start
Stop
CheckFW
Busy
Definition at line 107 of file uavcan_main.hpp.
Constructor & Destructor Documentation
UavcanNode::UavcanNode (uavcan::ICanDriver & can_driver, uavcan::ISystemClock & system_clock)
Definition at line 78 of file uavcan_main.cpp.
References _control_subs, _control_topics, _fw_server_action, _fw_server_status, _node_mutex, _server_command_sem, _task_should_exit, _tx_injector, None, NUM_ACTUATOR_CONTROL_GROUPS_UAVCAN, ORB_ID, pthread_mutex_init(), px4_sem_init, px4_sem_setprotocol, and SEM_PRIO_NONE.
Referenced by start().
UavcanNode::~UavcanNode () virtual
Definition at line 120 of file uavcan_main.cpp.
References _actuator_direct_sub, _armed_sub, _instance, _mixers, _node_mutex, _perf_control_latency, _sensor_bridges, _server_command_sem, _task, _task_should_exit, _test_motor_sub, fw_server(), orb_unsubscribe(), perf_free(), pthread_mutex_destroy(), px4_sem_destroy, Stop, and usleep().
UavcanNode::UavcanNode (uavcan::ICanDriver & can_driver, uavcan::ISystemClock & system_clock)
virtual UavcanNode::~UavcanNode () virtual
Member Function Documentation
int UavcanNode::add_poll_fd (int fd) private
add a fd to poll list, returning index into _poll_fds[]
int UavcanNode::add_poll_fd (int fd) private
add a fd to poll list, returning index into _poll_fds[]
Definition at line 693 of file uavcan_main.cpp.
References _poll_fds, _poll_fds_num, errx, fd, and UAVCAN_NUM_POLL_FDS.
Referenced by attachITxQueueInjector(), RestartRequestHandler::handleRestartRequest(), run(), and subscribe().
int UavcanNode::arm_actuators (bool arm)
Definition at line 1036 of file uavcan_main.cpp.
References _esc_controller, _is_armed, UavcanEscController::arm_all_escs(), and OK.
Referenced by get_node(), ioctl(), run(), and uavcan_main().
void UavcanNode::attachITxQueueInjector (ITxQueueInjector * injector) inline
Definition at line 137 of file uavcan_main.hpp.
References _tx_injector, add_poll_fd(), fd, fill_node_info(), get_param(), get_set_param(), device::CDev::init(), list_params(), name, node_spin_once(), print_params(), request_fw_check(), reset_node(), run(), save_params(), set_param(), start_fw_server(), stop_fw_server(), and update_params().
void UavcanNode::cb_beginfirmware_update (const uavcan::ReceivedDataStructure< UavcanNode::BeginFirmwareUpdate::Request > & req, uavcan::ServiceResponseDataStructure< UavcanNode::BeginFirmwareUpdate::Response > & rsp) private
Definition at line 260 of file uavcannode_main.cpp.
References _fw_update_listner, _node, _reset_timer, active_bitrate, App, bootloader_app_shared_write(), bootloader_app_shared_t::bus_speed, cb_reboot(), fill_node_info(), device::CDev::init(), lis3mdl::init(), bootloader_app_shared_t::node_id, OK, and rgb_led().
void UavcanNode::cb_opcode (const uavcan::ServiceCallResult< uavcan::protocol::param::ExecuteOpcode > & result) private
Definition at line 214 of file uavcan_main.cpp.
References _callback_success.
Referenced by save_params().
void UavcanNode::cb_restart (const uavcan::ServiceCallResult< uavcan::protocol::RestartNode > & result) private
Definition at line 245 of file uavcan_main.cpp.
References _callback_success.
Referenced by reset_node().
void UavcanNode::cb_setget (const uavcan::ServiceCallResult< uavcan::protocol::param::GetSet > & result) private
Definition at line 307 of file uavcan_main.cpp.
References _callback_success, and _setget_response.
Referenced by get_set_param().
int UavcanNode::control_callback (uintptr_t handle, uint8_t control_group, uint8_t control_index, float & input) static
Definition at line 1012 of file uavcan_main.cpp.
References actuator_controls_s::control.
Referenced by get_node(), and ioctl().
void UavcanNode::fill_node_info () private
void UavcanNode::fill_node_info () private
Definition at line 594 of file uavcan_main.cpp.
References _node, getHardwareVersion(), and px4_firmware_version_string().
Referenced by attachITxQueueInjector(), cb_beginfirmware_update(), and init().
void UavcanNode::free_setget_response (void) inline private
Definition at line 160 of file uavcan_main.hpp.
References _setget_response.
Referenced by get_param(), list_params(), and set_param().
int UavcanNode::fw_server (eServerAction action)
Definition at line 504 of file uavcan_main.cpp.
References _fw_server_action, _fw_server_status, _server_command_sem, CheckFW, None, px4_sem_wait, Start, and Stop.
Referenced by instance(), uavcan_main(), and ~UavcanNode().
Node& UavcanNode::get_node () inline
Definition at line 105 of file uavcannode_main.hpp.
References _node, print_info(), and teardown().
uavcan::Node& UavcanNode::get_node () inline
Definition at line 117 of file uavcan_main.hpp.
References _node, arm_actuators(), command, control_callback(), hardpoint_controller_set(), print_info(), shrink(), subscribe(), and teardown().
Referenced by RestartRequestHandler::handleRestartRequest(), and uavcan_main().
int UavcanNode::get_param (int remote_node_id, const char * name)
Definition at line 405 of file uavcan_main.cpp.
References free_setget_response(), get_set_param(), print_params(), and set_setget_response().
Referenced by attachITxQueueInjector(), and uavcan_main().
int UavcanNode::get_set_param (int nodeid, const char * name, uavcan::protocol::param::GetSet::Request & req) private
Definition at line 313 of file uavcan_main.cpp.
References _callback_success, _node, cb_setget(), name, and usleep().
Referenced by attachITxQueueInjector(), get_param(), list_params(), and set_param().
int UavcanNode::getHardwareVersion (uavcan::protocol::HardwareVersion & hwver) static
Definition at line 171 of file uavcan_main.cpp.
References board_get_mfguid(), instance(), and px4_board_name().
Referenced by fill_node_info(), UavcanServers::init(), and instance().
void UavcanNode::handle_time_sync (const uavcan::TimerEvent &) private
Definition at line 709 of file uavcan_main.cpp.
References _node, _time_sync_master, and _time_sync_slave.
Referenced by run().
void UavcanNode::hardpoint_controller_set (uint8_t hardpoint_id, uint16_t command)
Definition at line 1263 of file uavcan_main.cpp.
References _hardpoint_controller, _node_mutex, pthread_mutex_lock(), pthread_mutex_unlock(), and UavcanHardpointController::set_command().
Referenced by get_node(), and uavcan_main().
int UavcanNode::init (uavcan::NodeID node_id) private
int UavcanNode::init (uavcan::NodeID node_id) private
Definition at line 618 of file uavcan_main.cpp.
References _esc_controller, _hardpoint_controller, _idle_throttle_when_armed, _node, _sensor_bridges, UavcanEscController::enable_idle_throttle_when_armed(), fill_node_info(), UavcanHardpointController::init(), UavcanEscController::init(), lis3mdl::init(), IUavcanSensorBridge::make_all(), OK, param_find(), param_get(), PX4_ERR, and PX4_INFO.
Referenced by start().
static UavcanNode* UavcanNode::instance () inline static
Definition at line 111 of file uavcannode_main.hpp.
References _instance.
static UavcanNode* UavcanNode::instance () inline static
Definition at line 134 of file uavcan_main.hpp.
References _instance, fw_server(), and getHardwareVersion().
Referenced by getHardwareVersion(), uavcan_main(), and uavcannode_main().
virtual int UavcanNode::ioctl (file * filp, int cmd, unsigned long arg) virtual
int UavcanNode::ioctl (file * filp, int cmd, unsigned long arg) virtual
Definition at line 1070 of file uavcan_main.cpp.
References _controls, _groups_required, _hardpoint_controller, _mixers, _output_count, arm_actuators(), control_callback(), MixerGroup::groups_required(), UavcanServers::guessIfAllDynamicNodesAreAllocated(), UavcanServers::instance(), MixerGroup::load_from_buf(), device::CDev::lock(), MIXERIOCGETOUTPUTCOUNT, MIXERIOCLOADBUF, MIXERIOCRESET, OK, PWM_SERVO_ARM, PWM_SERVO_CLEAR_ARM_OK, PWM_SERVO_DISARM, PWM_SERVO_SET_ARM_OK, PWM_SERVO_SET_FORCE_SAFETY_OFF, PX4_ERR, UavcanHardpointController::set_command(), UAVCAN_IOCG_NODEID_INPROGRESS, UAVCAN_IOCS_HARDPOINT_SET, and device::CDev::unlock().
Referenced by RestartRequestHandler::handleRestartRequest().
int UavcanNode::list_params (int remote_node_id)
Definition at line 276 of file uavcan_main.cpp.
References _callback_success, free_setget_response(), get_set_param(), print_params(), and set_setget_response().
Referenced by attachITxQueueInjector(), and uavcan_main().
void UavcanNode::node_spin_once () private
void UavcanNode::node_spin_once () private
Definition at line 675 of file uavcan_main.cpp.
References _node, _tx_injector, ITxQueueInjector::injectTxFramesInto(), and PX4_ERR.
Referenced by attachITxQueueInjector(), RestartRequestHandler::handleRestartRequest(), and run().
void UavcanNode::print_info ()
void UavcanNode::print_info (void)
Definition at line 1177 of file uavcan_main.cpp.
References _groups_required, _groups_subscribed, _mixers, _node, _node_mutex, _node_status_monitor, _outputs, _poll_fds_num, _pool_allocator, _sensor_bridges, uart_esc::esc, actuator_outputs_s::noutputs, orb_copy(), ORB_ID, orb_subscribe(), orb_unsubscribe(), actuator_outputs_s::output, pthread_mutex_lock(), pthread_mutex_unlock(), and PX4_INFO.
Referenced by get_node(), RestartRequestHandler::handleRestartRequest(), uavcan_main(), and uavcannode_main().
int UavcanNode::print_params (uavcan::protocol::param::GetSet::Response & resp) private
Definition at line 192 of file uavcan_main.cpp.
Referenced by attachITxQueueInjector(), get_param(), and list_params().
int UavcanNode::request_fw_check () private
Definition at line 463 of file uavcan_main.cpp.
References _fw_server_action, _server_command_sem, Busy, UavcanServers::instance(), None, px4_sem_post, and UavcanServers::requestCheckAllNodesFirmwareAndUpdate().
Referenced by attachITxQueueInjector(), and run().
int UavcanNode::reset_node (int remote_node_id)
Definition at line 253 of file uavcan_main.cpp.
References _callback_success, _node, cb_restart(), and usleep().
Referenced by attachITxQueueInjector(), and uavcan_main().
int UavcanNode::run () private
int UavcanNode::run () private
Definition at line 751 of file uavcan_main.cpp.
References _actuator_direct, _actuator_direct_poll_fd_num, _actuator_direct_sub, _airmode, _armed, _armed_sub, _control_subs, _control_topics, _controls, _esc_controller, _fw_server_action, _fw_server_status, _groups_required, _groups_subscribed, _idle_throttle_when_armed, _master_timer, _mixers, _node, _node_mutex, _node_status_monitor, _output_count, _outputs, _perf_control_latency, _poll_fds, _poll_fds_num, _poll_ids, _task_should_exit, _test_in_progress, _test_motor, _test_motor_sub, _time_sync_slave, add_poll_fd(), arm_actuators(), UavcanEscController::arm_single_esc(), actuator_armed_s::armed, CheckFW, device::CDev::close(), DEVICE_LOG, UavcanEscController::enable_idle_throttle_when_armed(), handle_time_sync(), hrt_absolute_time(), hrt_abstime, actuator_armed_s::lockdown, actuator_armed_s::manual_lockdown, MixerGroup::mix(), test_motor_s::motor_number, node_spin_once(), None, actuator_outputs_s::noutputs, actuator_direct_s::nvalues, OK, device::CDev::open(), orb_check(), orb_copy(), ORB_ID, orb_subscribe(), orb_unsubscribe(), actuator_outputs_s::output, perf_set_elapsed(), device::CDev::poll(), PollTimeoutMs, pthread_mutex_lock(), pthread_mutex_unlock(), PX4_ERR, request_fw_check(), MixerGroup::set_airmode(), actuator_armed_s::soft_stop, Start, start_fw_server(), Stop, stop_fw_server(), subscribe(), teardown(), actuator_outputs_s::timestamp, actuator_controls_s::timestamp_sample, UavcanEscController::update_outputs(), update_params(), test_motor_s::value, and actuator_direct_s::values.
Referenced by attachITxQueueInjector(), RestartRequestHandler::handleRestartRequest(), and start().
int UavcanNode::save_params (int remote_node_id)
Definition at line 222 of file uavcan_main.cpp.
References _callback_success, _node, cb_opcode(), and usleep().
Referenced by attachITxQueueInjector(), and uavcan_main().
int UavcanNode::set_param (int remote_node_id, const char * name, char * value)
Definition at line 338 of file uavcan_main.cpp.
References f(), free_setget_response(), get_set_param(), max(), min(), and set_setget_response().
Referenced by attachITxQueueInjector(), and uavcan_main().
void UavcanNode::set_setget_response (uavcan::protocol::param::GetSet::Response * resp) inline private
Definition at line 156 of file uavcan_main.hpp.
References _setget_response.
Referenced by get_param(), list_params(), and set_param().
void UavcanNode::shrink ()
Definition at line 1256 of file uavcan_main.cpp.
References _node_mutex, _pool_allocator, pthread_mutex_lock(), and pthread_mutex_unlock().
Referenced by get_node(), and uavcan_main().
static int UavcanNode::start (uavcan::NodeID node_id, uint32_t bitrate) static
int UavcanNode::start (uavcan::NodeID node_id, uint32_t bitrate) static
Definition at line 529 of file uavcan_main.cpp.
References _instance, _task, init(), instance, OK, PX4_ERR, px4_task_spawn_cmd(), PX4_WARN, run(), SCHED_DEFAULT, SCHED_PRIORITY_ACTUATOR_OUTPUTS, StackSize, and UavcanNode().
Referenced by uavcan_main(), and uavcannode_start().
int UavcanNode::start_fw_server () private
Definition at line 437 of file uavcan_main.cpp.
References _fw_server_action, _node, _server_command_sem, _tx_injector, UavcanServers::attachITxQueueInjector(), Busy, UavcanServers::instance(), None, px4_sem_post, and UavcanServers::start().
Referenced by attachITxQueueInjector(), and run().
int UavcanNode::stop_fw_server () private
Definition at line 480 of file uavcan_main.cpp.
References _fw_server_action, _server_command_sem, _tx_injector, Busy, UavcanServers::instance(), None, px4_sem_post, and UavcanServers::stop().
Referenced by attachITxQueueInjector(), and run().
void UavcanNode::subscribe ()
Definition at line 1044 of file uavcan_main.cpp.
References _control_subs, _control_topics, _groups_required, _groups_subscribed, _poll_ids, add_poll_fd(), orb_subscribe(), orb_unsubscribe(), and PX4_DEBUG.
Referenced by get_node(), and run().
int UavcanNode::teardown ()
int UavcanNode::teardown ()
Definition at line 1021 of file uavcan_main.cpp.
References _armed_sub, _control_subs, _server_command_sem, orb_unsubscribe(), and px4_sem_post.
Referenced by get_node(), RestartRequestHandler::handleRestartRequest(), and run().
void UavcanNode::update_params () private
Definition at line 425 of file uavcan_main.cpp.
References _airmode, param_find(), param_get(), param_handle(), and PARAM_INVALID.
Referenced by attachITxQueueInjector(), and run().
Member Data Documentation
actuator_direct_s UavcanNode::_actuator_direct = {} private
Definition at line 207 of file uavcan_main.hpp.
Referenced by run().
uint8_t UavcanNode::_actuator_direct_poll_fd_num = 0 private
Definition at line 206 of file uavcan_main.hpp.
Referenced by run().
int UavcanNode::_actuator_direct_sub = -1 private
uORB subscription of the actuator_direct topic
Definition at line 205 of file uavcan_main.hpp.
Referenced by run(), and ~UavcanNode().
bool UavcanNode::_airmode = false private
Definition at line 213 of file uavcan_main.hpp.
Referenced by run(), and update_params().
actuator_armed_s UavcanNode::_armed = {} private
the arming request of the system
Definition at line 170 of file uavcan_main.hpp.
Referenced by run().
int UavcanNode::_armed_sub = -1 private
uORB subscription of the arming status
Definition at line 169 of file uavcan_main.hpp.
Referenced by run(), teardown(), and ~UavcanNode().
bool UavcanNode::_callback_success private
Definition at line 223 of file uavcan_main.hpp.
Referenced by cb_opcode(), cb_restart(), cb_setget(), get_set_param(), list_params(), reset_node(), and save_params().
int UavcanNode::_control_subs[NUM_ACTUATOR_CONTROL_GROUPS_UAVCAN] private
Definition at line 198 of file uavcan_main.hpp.
Referenced by run(), subscribe(), teardown(), and UavcanNode().
orb_id_t UavcanNode::_control_topics[NUM_ACTUATOR_CONTROL_GROUPS_UAVCAN] = {} private
Definition at line 200 of file uavcan_main.hpp.
Referenced by run(), subscribe(), and UavcanNode().
actuator_controls_s UavcanNode::_controls[NUM_ACTUATOR_CONTROL_GROUPS_UAVCAN] = {} private
Definition at line 199 of file uavcan_main.hpp.
Referenced by ioctl(), and run().
UavcanEscController UavcanNode::_esc_controller private
Definition at line 186 of file uavcan_main.hpp.
Referenced by arm_actuators(), init(), and run().
volatile eServerAction UavcanNode::_fw_server_action private
Definition at line 167 of file uavcan_main.hpp.
Referenced by fw_server(), request_fw_check(), run(), start_fw_server(), stop_fw_server(), and UavcanNode().
int UavcanNode::_fw_server_status private
Definition at line 168 of file uavcan_main.hpp.
Referenced by fw_server(), run(), and UavcanNode().
uavcan::ServiceServer<BeginFirmwareUpdate, BeginFirmwareUpdateCallBack> UavcanNode::_fw_update_listner private
Definition at line 143 of file uavcannode_main.hpp.
Referenced by cb_beginfirmware_update().
uint32_t UavcanNode::_groups_required = 0 private
Definition at line 196 of file uavcan_main.hpp.
Referenced by ioctl(), print_info(), run(), and subscribe().
uint32_t UavcanNode::_groups_subscribed = 0 private
Definition at line 197 of file uavcan_main.hpp.
Referenced by print_info(), run(), and subscribe().
UavcanHardpointController UavcanNode::_hardpoint_controller private
Definition at line 187 of file uavcan_main.hpp.
Referenced by hardpoint_controller_set(), init(), and ioctl().
int32_t UavcanNode::_idle_throttle_when_armed = 0 private
Definition at line 203 of file uavcan_main.hpp.
Referenced by init(), and run().
static UavcanNode * UavcanNode::_instance static private
singleton pointer
Definition at line 179 of file uavcan_main.hpp.
Referenced by RestartRequestHandler::handleRestartRequest(), instance(), start(), and ~UavcanNode().
bool UavcanNode::_is_armed = false private
the arming status of the actuators on the bus
Definition at line 171 of file uavcan_main.hpp.
Referenced by arm_actuators().
uavcan::TimerEventForwarder<TimerCallback> UavcanNode::_master_timer private
Definition at line 221 of file uavcan_main.hpp.
Referenced by run().
MixerGroup* UavcanNode::_mixers = nullptr private
Definition at line 194 of file uavcan_main.hpp.
Referenced by ioctl(), print_info(), run(), and ~UavcanNode().
Node UavcanNode::_node private
library instance
Definition at line 131 of file uavcannode_main.hpp.
uavcan::Node UavcanNode::_node private
library instance
Definition at line 183 of file uavcan_main.hpp.
Referenced by cb_beginfirmware_update(), fill_node_info(), get_node(), get_set_param(), handle_time_sync(), RestartRequestHandler::handleRestartRequest(), init(), node_spin_once(), print_info(), reset_node(), run(), save_params(), and start_fw_server().
pthread_mutex_t UavcanNode::_node_mutex private
Definition at line 184 of file uavcan_main.hpp.
Referenced by RestartRequestHandler::handleRestartRequest(), hardpoint_controller_set(), print_info(), run(), shrink(), UavcanNode(), and ~UavcanNode().
uavcan::NodeStatusMonitor UavcanNode::_node_status_monitor private
Definition at line 190 of file uavcan_main.hpp.
Referenced by print_info(), and run().
unsigned UavcanNode::_output_count = 0 private
number of actuators currently available
Definition at line 177 of file uavcan_main.hpp.
Referenced by ioctl(), and run().
actuator_outputs_s UavcanNode::_outputs = {} private
Definition at line 209 of file uavcan_main.hpp.
Referenced by print_info(), and run().
perf_counter_t UavcanNode::_perf_control_latency private
Definition at line 211 of file uavcan_main.hpp.
Referenced by run(), and ~UavcanNode().
pollfd UavcanNode::_poll_fds = {} private
Definition at line 201 of file uavcan_main.hpp.
Referenced by add_poll_fd(), RestartRequestHandler::handleRestartRequest(), and run().
unsigned UavcanNode::_poll_fds_num = 0 private
Definition at line 202 of file uavcan_main.hpp.
Referenced by add_poll_fd(), RestartRequestHandler::handleRestartRequest(), print_info(), and run().
uint8_t UavcanNode::_poll_ids[NUM_ACTUATOR_CONTROL_GROUPS_UAVCAN] private
Definition at line 216 of file uavcan_main.hpp.
Referenced by run(), and subscribe().
uavcan_node::Allocator UavcanNode::_pool_allocator private
Definition at line 181 of file uavcan_main.hpp.
Referenced by print_info(), and shrink().
uavcan::TimerEventForwarder<void (*)(const uavcan::TimerEvent &)> UavcanNode::_reset_timer
Definition at line 151 of file uavcannode_main.hpp.
Referenced by cb_beginfirmware_update().
List<IUavcanSensorBridge *> UavcanNode::_sensor_bridges private
List of active sensor bridges.
Definition at line 192 of file uavcan_main.hpp.
Referenced by init(), print_info(), and ~UavcanNode().
px4_sem_t UavcanNode::_server_command_sem private
Definition at line 185 of file uavcan_main.hpp.
Referenced by fw_server(), request_fw_check(), start_fw_server(), stop_fw_server(), teardown(), UavcanNode(), and ~UavcanNode().
uavcan::protocol::param::GetSet::Response* UavcanNode::_setget_response private
Definition at line 224 of file uavcan_main.hpp.
Referenced by cb_setget(), free_setget_response(), and set_setget_response().
int UavcanNode::_task = -1 private
handle to the OS task
Definition at line 165 of file uavcan_main.hpp.
Referenced by start(), and ~UavcanNode().
bool UavcanNode::_task_should_exit = false private
flag to indicate to tear down the CAN driver
Definition at line 166 of file uavcan_main.hpp.
Referenced by RestartRequestHandler::handleRestartRequest(), run(), UavcanNode(), and ~UavcanNode().
bool UavcanNode::_test_in_progress = false private
Definition at line 175 of file uavcan_main.hpp.
Referenced by run().
test_motor_s UavcanNode::_test_motor = {} private
Definition at line 174 of file uavcan_main.hpp.
Referenced by run().
int UavcanNode::_test_motor_sub = -1 private
uORB subscription of the test_motor status
Definition at line 173 of file uavcan_main.hpp.
Referenced by run(), and ~UavcanNode().
uavcan::GlobalTimeSyncMaster UavcanNode::_time_sync_master private
Definition at line 188 of file uavcan_main.hpp.
Referenced by handle_time_sync().
uavcan::GlobalTimeSyncSlave UavcanNode::_time_sync_slave private
Definition at line 189 of file uavcan_main.hpp.
Referenced by handle_time_sync(), RestartRequestHandler::handleRestartRequest(), and run().
ITxQueueInjector* UavcanNode::_tx_injector private
Definition at line 195 of file uavcan_main.hpp.
Referenced by attachITxQueueInjector(), node_spin_once(), start_fw_server(), stop_fw_server(), and UavcanNode().
int32_t UavcanNode::active_bitrate
Definition at line 116 of file uavcannode_main.hpp.
Referenced by cb_beginfirmware_update().
constexpr unsigned UavcanNode::bitPerFrame = 148 static private
Definition at line 83 of file uavcan_main.hpp.
constexpr unsigned UavcanNode::FramePerMSecond = ((FramePerSecond / 1000) + 1) static private
Definition at line 85 of file uavcan_main.hpp.
constexpr unsigned UavcanNode::FramePerSecond = MaxBitRatePerSec / bitPerFrame static private
Definition at line 84 of file uavcan_main.hpp.
constexpr unsigned UavcanNode::MaxBitRatePerSec = 1000000 static private
Definition at line 82 of file uavcan_main.hpp.
constexpr unsigned UavcanNode::MemPoolSize = 2048 static private
Definition at line 71 of file uavcannode_main.hpp.
constexpr unsigned UavcanNode::PollTimeoutMs = 3 static private
Definition at line 87 of file uavcan_main.hpp.
Referenced by RestartRequestHandler::handleRestartRequest(), and run().
static constexpr unsigned UavcanNode::RxQueueLenPerIface = FramePerMSecond * PollTimeoutMs static private
Definition at line 102 of file uavcan_main.hpp.
static constexpr unsigned UavcanNode::StackSize = 2400 static private
Definition at line 103 of file uavcan_main.hpp.
Referenced by start().
The documentation for this class was generated from the following files:
src/modules/uavcan/uavcan_main.hpp
src/modules/uavcannode/uavcannode_main.hpp
src/modules/uavcan/uavcan_main.cpp
src/modules/uavcannode/uavcannode_main.cpp