PX4 Firmware: GYROSIM_gyro Class Reference
GYROSIM_gyro Class Reference
Helper class implementing the gyro driver node.
Public Member Functions
GYROSIM_gyro (GYROSIM *parent, const char *path)
virtual ~GYROSIM_gyro ()=default
virtual ssize_t devRead (void *buffer, size_t buflen)
virtual int devIOCTL (unsigned long cmd, unsigned long arg)
virtual int init ()
Protected Member Functions
virtual void _measure ()
Private Member Functions
GYROSIM_gyro (const GYROSIM_gyro &)=delete
GYROSIM_gyro operator= (const GYROSIM_gyro &)=delete
Private Attributes
GYROSIM * _parent
orb_advert_t _gyro_topic
int _gyro_orb_class_instance
Friends
class GYROSIM
Detailed Description
Helper class implementing the gyro driver node.
Definition at line 260 of file gyrosim.cpp.
Constructor & Destructor Documentation
GYROSIM_gyro::GYROSIM_gyro (GYROSIM * parent, const char * path)
Definition at line 1056 of file gyrosim.cpp.
virtual GYROSIM_gyro::~GYROSIM_gyro () virtual default
GYROSIM_gyro::GYROSIM_gyro (const GYROSIM_gyro &) private delete
Member Function Documentation
virtual void GYROSIM_gyro::_measure (void) inline protected virtual
Definition at line 274 of file gyrosim.cpp.
int GYROSIM_gyro::devIOCTL (unsigned long cmd, unsigned long arg) virtual
Definition at line 1081 of file gyrosim.cpp.
References _parent, and GYROSIM::gyro_ioctl().
ssize_t GYROSIM_gyro::devRead (void * buffer, size_t buflen) virtual
Definition at line 1075 of file gyrosim.cpp.
References _parent, and GYROSIM::gyro_read().
int GYROSIM_gyro::init () virtual
Definition at line 1067 of file gyrosim.cpp.
References lis3mdl::init(), and PX4_DEBUG.
Referenced by GYROSIM::init().
GYROSIM_gyro GYROSIM_gyro::operator= (const GYROSIM_gyro &) private delete
Friends And Related Function Documentation
friend class GYROSIM friend
Definition at line 272 of file gyrosim.cpp.
Referenced by gyrosim::start().
Member Data Documentation
int GYROSIM_gyro::_gyro_orb_class_instance private
Definition at line 278 of file gyrosim.cpp.
Referenced by GYROSIM::init().
orb_advert_t GYROSIM_gyro::_gyro_topic private
Definition at line 277 of file gyrosim.cpp.
Referenced by GYROSIM::_measure(), and GYROSIM::init().
GYROSIM* GYROSIM_gyro::_parent private
Definition at line 276 of file gyrosim.cpp.
Referenced by devIOCTL(), and devRead().
The documentation for this class was generated from the following file:
src/modules/simulator/gyrosim/gyrosim.cpp