PX4 Firmware: mappydot Namespace Reference
mappydot Namespace Reference
Local functions in support of the shell command.
Functions
int start ()
Attempt to start driver on all available I2C busses.
int start_bus (int i2c_bus)
Start the driver on a specific bus.
int status ()
Print the driver status.
int stop ()
Stop the driver.
int usage ()
Print usage information about the driver.
Variables
MappyDot * g_dev
Detailed Description
Local functions in support of the shell command.
Function Documentation
start()
int mappydot::start ()
Attempt to start driver on all available I2C busses.
This function will return as soon as the first sensor is detected on one of the available busses or if no sensors are detected.
Definition at line 458 of file MappyDot.cpp.
References i2c_bus_options, NUM_I2C_BUS_OPTIONS, and start_bus().
Referenced by mappydot_main().
start_bus()
int mappydot::start_bus (int i2c_bus)
Start the driver on a specific bus.
This function only returns if the sensor is up and running or could not be detected successfully.
Definition at line 481 of file MappyDot.cpp.
References g_dev, MappyDot::init(), MappyDot::MappyDot(), and MappyDot::start().
Referenced by mappydot_main(), and start().
status()
int mappydot::status ()
Print the driver status.
Definition at line 514 of file MappyDot.cpp.
References MappyDot::print_info().
Referenced by mappydot_main().
stop()
int mappydot::stop ()
Stop the driver.
Stop the driver.
Definition at line 530 of file MappyDot.cpp.
References g_dev.
Referenced by mappydot_main().
usage()
int mappydot::usage (void)
Print usage information about the driver.
Prints info about the driver argument usage.
Definition at line 546 of file MappyDot.cpp.
References MAPPYDOT_BUS_DEFAULT.
Referenced by mappydot_main().
Variable Documentation
g_dev
MappyDot* mappydot::g_dev
Definition at line 442 of file MappyDot.cpp.
Referenced by start_bus(), and stop().