PX4 Firmware: MPU6000 Class Reference
MPU6000 Class Reference
Public Member Functions
MPU6000 (device::Device *interface, const char *path_accel, const char *path_gyro, enum Rotation rotation, int device_type)
virtual ~MPU6000 ()
virtual int init ()
Initialise the driver and make it ready for use.
virtual ssize_t read (struct file *filp, char *buffer, size_t buflen)
virtual int ioctl (struct file *filp, int cmd, unsigned long arg)
void print_info ()
Diagnostics - print some basic information about the driver.
void print_registers ()
int factory_self_test ()
Test behaviour against factory offsets.
void test_error ()
Public Member Functions inherited from device::CDev
CDev (const char *name, const char *devname)
Constructor.
virtual ~CDev ()
virtual int open (file_t *filep)
Handle an open of the device.
virtual int close (file_t *filep)
Handle a close of the device.
virtual ssize_t read (file_t *filep, char *buffer, size_t buflen)
Perform a read from the device.
virtual ssize_t write (file_t *filep, const char *buffer, size_t buflen)
Perform a write to the device.
virtual off_t seek (file_t *filep, off_t offset, int whence)
Perform a logical seek operation on the device.
virtual int ioctl (file_t *filep, int cmd, unsigned long arg)
Perform an ioctl operation on the device.
virtual int poll (file_t *filep, px4_pollfd_struct_t *fds, bool setup)
Perform a poll setup/teardown operation.
Public Member Functions inherited from device::Device
virtual ~Device ()=default
Destructor.
virtual int read (unsigned address, void *data, unsigned count)
Read directly from the device.
virtual int write (unsigned address, void *data, unsigned count)
Write directly to the device.
virtual int ioctl (unsigned operation, unsigned &arg)
Perform a device-specific operation.
uint8_t get_device_bus ()
Return the bus ID the device is connected to.
DeviceBusType get_device_bus_type ()
Return the bus type the device is connected to.
uint8_t get_device_address ()
Return the bus address of the device.
void set_device_address (int address)
void set_device_type (uint8_t devtype)
Set the device type.
virtual bool external ()
Protected Member Functions
virtual int probe ()
virtual ssize_t gyro_read (struct file *filp, char *buffer, size_t buflen)
virtual int gyro_ioctl (struct file *filp, int cmd, unsigned long arg)
Protected Member Functions inherited from device::CDev
virtual pollevent_t poll_state (file_t *filep)
Check the current state of the device for poll events from the perspective of the file.
virtual void poll_notify (pollevent_t events)
Report new poll events.
virtual void poll_notify_one (px4_pollfd_struct_t *fds, pollevent_t events)
Internal implementation of poll_notify.
virtual int open_first (file_t *filep)
Notification of the first open.
virtual int close_last (file_t *filep)
Notification of the last close.
virtual int register_class_devname (const char *class_devname)
Register a class device name, automatically adding device class instance suffix if need be.
virtual int unregister_class_devname (const char *class_devname, unsigned class_instance)
Register a class device name, automatically adding device class instance suffix if need be.
const char * get_devname ()
Get the device name.
void lock ()
Take the driver lock.
void unlock ()
Release the driver lock.
Protected Member Functions inherited from device::Device
Device (const char *name)
Device (DeviceBusType bus_type, uint8_t bus, uint8_t address, uint8_t devtype=0)
Device (const Device &)=delete
Device & operator= (const Device &)=delete
Device (Device &&)=delete
Device & operator= (Device &&)=delete
Protected Attributes
Device * _interface
Protected Attributes inherited from device::CDev
px4_sem_t _lock
lock to protect access to all class members (also for derived classes)
bool _pub_blocked {false}
true if publishing should be blocked
Protected Attributes inherited from device::Device
union DeviceId _device_id
device identifier information
const char * _name
driver name
bool _debug_enabled {false}
if true, debug messages are printed
Private Member Functions
void start ()
Start automatic measurement.
void stop ()
Stop automatic measurement.
int reset ()
Reset chip.
bool is_icm_device ()
is_icm_device
bool is_mpu_device ()
is_mpu_device
bool is_i2c (void)
int measure ()
Fetch measurements from the sensor and update the report buffers.
uint8_t read_reg (unsigned reg, uint32_t speed=MPU6000_LOW_BUS_SPEED)
Read a register from the MPU6000.
uint16_t read_reg16 (unsigned reg)
int write_reg (unsigned reg, uint8_t value)
Write a register in the MPU6000.
void modify_reg (unsigned reg, uint8_t clearbits, uint8_t setbits)
Modify a register in the MPU6000.
void write_checked_reg (unsigned reg, uint8_t value)
Write a register in the MPU6000, updating _checked_values.
int set_accel_range (unsigned max_g)
Set the MPU6000 measurement range.
uint16_t swap16 (uint16_t val)
Swap a 16-bit value read from the MPU6000 to native byte order.
bool is_external ()
Get the internal / external state.
int self_test ()
Measurement self test.
void _set_dlpf_filter (uint16_t frequency_hz)
void _set_icm_acc_dlpf_filter (uint16_t frequency_hz)
void _set_sample_rate (unsigned desired_sample_rate_hz)
void check_registers (void)
MPU6000 (const MPU6000 &)
MPU6000 operator= (const MPU6000 &)
Static Private Member Functions
static void measure_trampoline (void *arg)
Static trampoline from the hrt_call context; because we don't have a generic hrt wrapper yet.
Private Attributes
int _device_type
MPU6000_gyro * _gyro
uint8_t _product
bool _use_hrt
product code
struct hrt_call _call
unsigned _call_interval
ringbuffer::RingBuffer * _accel_reports
struct accel_calibration_s _accel_scale
float _accel_range_scale
float _accel_range_m_s2
orb_advert_t _accel_topic
int _accel_orb_class_instance
int _accel_class_instance
ringbuffer::RingBuffer * _gyro_reports
struct gyro_calibration_s _gyro_scale
float _gyro_range_scale
float _gyro_range_rad_s
unsigned _sample_rate
perf_counter_t _sample_perf
perf_counter_t _measure_interval
perf_counter_t _bad_transfers
perf_counter_t _bad_registers
perf_counter_t _reset_retries
perf_counter_t _duplicates
uint8_t _register_wait
uint64_t _reset_wait
math::LowPassFilter2p _accel_filter_x
math::LowPassFilter2p _accel_filter_y
math::LowPassFilter2p _accel_filter_z
math::LowPassFilter2p _gyro_filter_x
math::LowPassFilter2p _gyro_filter_y
math::LowPassFilter2p _gyro_filter_z
Integrator _accel_int
Integrator _gyro_int
enum Rotation _rotation
uint8_t _checked_values [MPU6000_NUM_CHECKED_REGISTERS]
uint8_t _checked_next
volatile bool _in_factory_test
float _last_temperature
uint16_t _last_accel [3]
bool _got_duplicate
Static Private Attributes
static const uint8_t _checked_registers [MPU6000_NUM_CHECKED_REGISTERS]
Friends
class MPU6000_gyro
Additional Inherited Members
Public Types inherited from device::Device
enum DeviceBusType { DeviceBusType_UNKNOWN = 0, DeviceBusType_I2C = 1, DeviceBusType_SPI = 2, DeviceBusType_UAVCAN = 3 }
Device bus types for DEVID.
Static Protected Attributes inherited from device::CDev
static const px4_file_operations_t fops = {}
Pointer to the default cdev file operations table; useful for registering clone devices etc.
Detailed Description
Definition at line 131 of file mpu6000.cpp.
Constructor & Destructor Documentation
MPU6000::MPU6000 (device::Device * interface, const char * path_accel, const char * path_gyro, enum Rotation rotation, int device_type)
Definition at line 462 of file mpu6000.cpp.
References _accel_class_instance, _accel_filter_x, _accel_filter_y, _accel_filter_z, _accel_int, _accel_orb_class_instance, _accel_range_m_s2, _accel_range_scale, _accel_reports, _accel_scale, _accel_topic, _bad_registers, _bad_transfers, _call, _call_interval, _checked_next, device::Device::_debug_enabled, device::Device::_device_id, _device_type, _duplicates, _got_duplicate, _gyro, _gyro_filter_x, _gyro_filter_y, _gyro_filter_z, _gyro_int, _gyro_range_rad_s, _gyro_range_scale, _gyro_reports, _gyro_scale, _in_factory_test, _interface, _last_accel, _last_temperature, _measure_interval, _register_wait, _reset_retries, _reset_wait, _rotation, _sample_perf, _sample_rate, _use_hrt, device::Device::DeviceStructure::address, device::Device::DeviceStructure::bus, device::Device::DeviceStructure::bus_type, device::Device::DeviceId::devid, device::Device::DeviceId::devid_s, device::Device::DeviceStructure::devtype, DRV_ACC_DEVTYPE_ICM20602, DRV_ACC_DEVTYPE_ICM20608, DRV_ACC_DEVTYPE_ICM20689, DRV_ACC_DEVTYPE_MPU6000, DRV_GYR_DEVTYPE_ICM20602, DRV_GYR_DEVTYPE_ICM20608, DRV_GYR_DEVTYPE_ICM20689, DRV_GYR_DEVTYPE_MPU6000, f(), MPU6000_ACCEL_DEFAULT_DRIVER_FILTER_FREQ, MPU6000_ACCEL_DEFAULT_RATE, MPU6000_ACCEL_MAX_OUTPUT_RATE, MPU6000_GYRO_DEFAULT_DRIVER_FILTER_FREQ, MPU6000_GYRO_DEFAULT_RATE, MPU6000_GYRO_MAX_OUTPUT_RATE, MPU_DEVICE_TYPE_ICM20602, MPU_DEVICE_TYPE_ICM20608, MPU_DEVICE_TYPE_ICM20689, MPU_DEVICE_TYPE_MPU6000, PC_COUNT, PC_ELAPSED, PC_INTERVAL, perf_alloc, accel_calibration_s::x_offset, gyro_calibration_s::x_offset, gyro_calibration_s::x_scale, accel_calibration_s::x_scale, gyro_calibration_s::y_offset, accel_calibration_s::y_offset, gyro_calibration_s::y_scale, accel_calibration_s::y_scale, accel_calibration_s::z_offset, gyro_calibration_s::z_offset, accel_calibration_s::z_scale, and gyro_calibration_s::z_scale.
Referenced by is_external().
MPU6000::~MPU6000 () virtual
Definition at line 574 of file mpu6000.cpp.
References _accel_class_instance, _accel_reports, _accel_topic, _bad_registers, _bad_transfers, _duplicates, _gyro, _gyro_reports, MPU6000_gyro::_gyro_topic, _measure_interval, _reset_retries, _sample_perf, ACCEL_BASE_DEVICE_PATH, orb_unadvertise(), perf_free(), stop(), and device::CDev::unregister_class_devname().
MPU6000::MPU6000 (const MPU6000 &) private
Member Function Documentation
void MPU6000::_set_dlpf_filter (uint16_t frequency_hz) private
Definition at line 935 of file mpu6000.cpp.
References MPU_GYRO_DLPF_CFG_10HZ, MPU_GYRO_DLPF_CFG_188HZ, MPU_GYRO_DLPF_CFG_20HZ, MPU_GYRO_DLPF_CFG_2100HZ_NOLPF, MPU_GYRO_DLPF_CFG_256HZ_NOLPF2, MPU_GYRO_DLPF_CFG_42HZ, MPU_GYRO_DLPF_CFG_5HZ, MPU_GYRO_DLPF_CFG_98HZ, MPUREG_CONFIG, and write_checked_reg().
Referenced by is_external(), and reset().
void MPU6000::_set_icm_acc_dlpf_filter (uint16_t frequency_hz) private
Definition at line 974 of file mpu6000.cpp.
References ICM_ACC_DLPF_CFG_1046HZ_NOLPF, ICM_ACC_DLPF_CFG_10HZ, ICM_ACC_DLPF_CFG_218HZ, ICM_ACC_DLPF_CFG_21HZ, ICM_ACC_DLPF_CFG_420HZ, ICM_ACC_DLPF_CFG_44HZ, ICM_ACC_DLPF_CFG_5HZ, ICM_ACC_DLPF_CFG_99HZ, ICMREG_ACCEL_CONFIG2, and write_checked_reg().
Referenced by is_external(), and reset().
void MPU6000::_set_sample_rate (unsigned desired_sample_rate_hz) private
Definition at line 913 of file mpu6000.cpp.
References _sample_rate, ACCEL_SAMPLERATE_DEFAULT, GYRO_SAMPLERATE_DEFAULT, MPU6000_GYRO_DEFAULT_RATE, MPUREG_SMPLRT_DIV, and write_checked_reg().
Referenced by gyro_ioctl(), ioctl(), is_external(), and reset().
void MPU6000::check_registers (void) private
Definition at line 1674 of file mpu6000.cpp.
References _bad_registers, _checked_next, _checked_registers, _checked_values, _register_wait, _reset_wait, BIT_H_RESET, hrt_absolute_time(), is_icm_device(), MPU6000_CHECKED_PRODUCT_ID_INDEX, MPU6000_HIGH_BUS_SPEED, MPU6000_NUM_CHECKED_REGISTERS, MPUREG_ICM_UNDOC1, MPUREG_PWR_MGMT_1, perf_count(), read_reg(), and write_reg().
Referenced by is_external(), and measure().
int MPU6000::factory_self_test ()
Test behaviour against factory offsets.
Returns
0 on success, 1 on failure
Definition at line 1067 of file mpu6000.cpp.
References _in_factory_test, _interface, accel(), MPUReport::accel_x, MPUReport::accel_y, MPUReport::accel_z, BITS_FS_250DPS, BITS_GYRO_ST_X, BITS_GYRO_ST_Y, BITS_GYRO_ST_Z, err, f(), gyro(), MPUReport::gyro_x, MPUReport::gyro_y, MPUReport::gyro_z, int16_t_from_bytes(), MPU6000_HIGH_BUS_SPEED, MPU6000_SET_SPEED, MPUREG_ACCEL_CONFIG, MPUREG_GYRO_CONFIG, MPUREG_INT_STATUS, MPUREG_TRIM1, MPUREG_TRIM2, MPUREG_TRIM3, MPUREG_TRIM4, OK, read_reg(), and write_reg().
Referenced by mpu6000::factorytest().
int MPU6000::gyro_ioctl (struct file * filp, int cmd, unsigned long arg) protected virtual
Definition at line 1419 of file mpu6000.cpp.
References _gyro_range_rad_s, _gyro_reports, _gyro_scale, _sample_rate, _set_sample_rate(), GYROIOCGRANGE, GYROIOCGSAMPLERATE, GYROIOCGSCALE, GYROIOCSRANGE, GYROIOCSSAMPLERATE, GYROIOCSSCALE, ioctl(), M_PI_F, OK, SENSORIOCGPOLLRATE, SENSORIOCRESET, SENSORIOCSPOLLRATE, and SENSORIOCSQUEUEDEPTH.
Referenced by MPU6000_gyro::ioctl().
ssize_t MPU6000::gyro_read (struct file * filp, char * buffer, size_t buflen) protected virtual
Definition at line 1231 of file mpu6000.cpp.
References _call_interval, _gyro_reports, gyro_report, and measure().
Referenced by MPU6000_gyro::read().
int MPU6000::init () virtual
Initialise the driver and make it ready for use.
Returns
OK if the driver initialized OK, negative errno otherwise;
Reimplemented from device::CDev.
Definition at line 608 of file mpu6000.cpp.
References _accel_class_instance, _accel_filter_x, _accel_filter_y, _accel_filter_z, _accel_orb_class_instance, _accel_reports, _accel_scale, _accel_topic, _gyro, _gyro_filter_x, _gyro_filter_y, _gyro_filter_z, MPU6000_gyro::_gyro_orb_class_instance, _gyro_reports, _gyro_scale, MPU6000_gyro::_gyro_topic, _interface, ACCEL_BASE_DEVICE_PATH, accel_report, DEVICE_DEBUG, gyro_report, lis3mdl::init(), MPU6000_gyro::init(), is_external(), measure(), MPU6000_ACCEL_DEFAULT_DRIVER_FILTER_FREQ, MPU6000_ACCEL_DEFAULT_RATE, MPU6000_GYRO_DEFAULT_DRIVER_FILTER_FREQ, MPU6000_GYRO_DEFAULT_RATE, MPUIOCGIS_I2C, OK, orb_advertise_multi(), ORB_ID, ORB_PRIO_HIGH, ORB_PRIO_MAX, param_find(), param_get(), PARAM_INVALID, probe(), PX4_ERR, PX4_INFO, PX4_OK, PX4_WARN, device::CDev::register_class_devname(), reset(), math::LowPassFilter2p::set_cutoff_frequency(), accel_calibration_s::x_offset, gyro_calibration_s::x_offset, accel_calibration_s::x_scale, gyro_calibration_s::x_scale, accel_calibration_s::y_offset, gyro_calibration_s::y_offset, gyro_calibration_s::y_scale, accel_calibration_s::y_scale, accel_calibration_s::z_offset, gyro_calibration_s::z_offset, gyro_calibration_s::z_scale, and accel_calibration_s::z_scale.
int MPU6000::ioctl (struct file * filp, int cmd, unsigned long arg) virtual
Definition at line 1269 of file mpu6000.cpp.
References _accel_filter_x, _accel_filter_y, _accel_filter_z, _accel_range_m_s2, _accel_reports, _accel_scale, _call, _call_interval, _gyro_filter_x, _gyro_filter_y, _gyro_filter_z, _interface, _sample_rate, _set_sample_rate(), ACCELIOCGEXTERNAL, ACCELIOCGRANGE, ACCELIOCGSAMPLERATE, ACCELIOCGSCALE, ACCELIOCSRANGE, ACCELIOCSSAMPLERATE, ACCELIOCSSCALE, CONSTANTS_ONE_G, f(), math::LowPassFilter2p::get_cutoff_freq(), is_i2c(), MPU6000_ACCEL_DEFAULT_RATE, MPU6000_TIMER_REDUCTION, OK, hrt_call::period, reset(), SENSOR_POLLRATE_DEFAULT, SENSOR_POLLRATE_EXTERNAL, SENSOR_POLLRATE_MANUAL, SENSOR_POLLRATE_MAX, SENSORIOCGPOLLRATE, SENSORIOCRESET, SENSORIOCSPOLLRATE, SENSORIOCSQUEUEDEPTH, set_accel_range(), math::LowPassFilter2p::set_cutoff_frequency(), start(), stop(), accel_calibration_s::x_scale, accel_calibration_s::y_scale, and accel_calibration_s::z_scale.
Referenced by gyro_ioctl().
bool MPU6000::is_external () inline private
Get the internal / external state.
Returns
true if the sensor is not on the main MCU board
Definition at line 376 of file mpu6000.cpp.
References _checked_registers, _set_dlpf_filter(), _set_icm_acc_dlpf_filter(), _set_sample_rate(), ACCELIOCGEXTERNAL, check_registers(), MPU6000(), MPU6000_NUM_CHECKED_REGISTERS, MPUREG_ACCEL_CONFIG, MPUREG_CONFIG, MPUREG_GYRO_CONFIG, MPUREG_ICM_UNDOC1, MPUREG_INT_ENABLE, MPUREG_INT_PIN_CFG, MPUREG_PRODUCT_ID, MPUREG_PWR_MGMT_1, MPUREG_SMPLRT_DIV, MPUREG_USER_CTRL, operator=(), and self_test().
Referenced by init().
bool MPU6000::is_i2c (void) inline private
Definition at line 302 of file mpu6000.cpp.
References _use_hrt, measure(), measure_trampoline(), modify_reg(), MPU6000_LOW_BUS_SPEED, read_reg(), read_reg16(), set_accel_range(), write_checked_reg(), and write_reg().
Referenced by ioctl(), reset(), start(), and stop().
bool MPU6000::is_icm_device () inline private
is_icm_device
Definition at line 266 of file mpu6000.cpp.
References is_mpu_device().
Referenced by check_registers(), measure(), probe(), and reset().
bool MPU6000::is_mpu_device () inline private
is_mpu_device
Definition at line 270 of file mpu6000.cpp.
References MPU_DEVICE_TYPE_MPU6000.
Referenced by is_icm_device(), probe(), and set_accel_range().
int MPU6000::measure () private
Fetch measurements from the sensor and update the report buffers.
Definition at line 1735 of file mpu6000.cpp.
References _accel_filter_x, _accel_filter_y, _accel_filter_z, _accel_int, _accel_range_scale, _accel_reports, _accel_scale, _accel_topic, _bad_registers, _bad_transfers, device::Device::_device_id, _duplicates, _got_duplicate, _gyro, _gyro_filter_x, _gyro_filter_y, _gyro_filter_z, _gyro_int, _gyro_range_scale, _gyro_reports, _gyro_scale, MPU6000_gyro::_gyro_topic, _in_factory_test, _interface, _last_accel, _last_temperature, _measure_interval, device::CDev::_pub_blocked, _register_wait, _reset_wait, _rotation, _sample_perf, accel_report, MPUReport::accel_x, MPUReport::accel_y, MPUReport::accel_z, math::LowPassFilter2p::apply(), check_registers(), device::Device::DeviceId::devid, f(), gyro_report, MPUReport::gyro_x, MPUReport::gyro_y, MPUReport::gyro_z, hrt_absolute_time(), int16_t_from_bytes(), is_icm_device(), MPU6000_HIGH_BUS_SPEED, MPU6000_SET_SPEED, MPUREG_INT_STATUS, OK, ORB_ID, orb_publish(), MPU6000_gyro::parent_poll_notify(), perf_begin(), perf_count(), perf_end(), perf_event_count(), device::CDev::poll_notify(), Integrator::put(), rotate_3f(), MPUReport::temp, accel_calibration_s::x_offset, gyro_calibration_s::x_offset, gyro_calibration_s::x_scale, accel_calibration_s::x_scale, gyro_calibration_s::y_offset, accel_calibration_s::y_offset, accel_calibration_s::y_scale, gyro_calibration_s::y_scale, gyro_calibration_s::z_offset, accel_calibration_s::z_offset, accel_calibration_s::z_scale, and gyro_calibration_s::z_scale.
Referenced by gyro_read(), init(), is_i2c(), measure_trampoline(), read(), self_test(), and stop().
void MPU6000::measure_trampoline (void * arg) static private
Static trampoline from the hrt_call context; because we don't have a generic hrt wrapper yet.
Called by the HRT in interrupt context at the specified rate if automatic polling is enabled.
Parameters
arg Instance pointer for the driver that is polling.
Definition at line 1666 of file mpu6000.cpp.
References measure().
Referenced by is_i2c(), and start().
void MPU6000::modify_reg (unsigned reg, uint8_t clearbits, uint8_t setbits) private
Modify a register in the MPU6000.
Bits are cleared before bits are set.
Parameters
reg The register to modify.
clearbits Bits in the register to clear.
setbits Bits in the register to set.
Definition at line 1508 of file mpu6000.cpp.
References read_reg(), and write_reg().
Referenced by is_i2c().
MPU6000 MPU6000::operator= (const MPU6000 &) private
Referenced by is_external().
void MPU6000::print_info ()
Diagnostics - print some basic information about the driver.
Definition at line 1990 of file mpu6000.cpp.
References _accel_filter_x, _accel_reports, _bad_registers, _bad_transfers, _checked_next, _checked_registers, _checked_values, _duplicates, _gyro_filter_x, _gyro_reports, _last_temperature, _reset_retries, _sample_perf, math::LowPassFilter2p::get_cutoff_freq(), MPU6000_HIGH_BUS_SPEED, MPU6000_NUM_CHECKED_REGISTERS, perf_print_counter(), and read_reg().
Referenced by mpu6000::info().
void MPU6000::print_registers ()
Definition at line 2020 of file mpu6000.cpp.
References MPUREG_PRODUCT_ID, and read_reg().
Referenced by mpu6000::regdump(), and test_error().
int MPU6000::probe () protected virtual
Definition at line 835 of file mpu6000.cpp.
References _checked_values, _device_type, _product, DEVICE_DEBUG, ICM20602_REV_01, ICM20602_REV_02, ICM20608_REV_FF, ICM20689_REV_03, ICM20689_REV_FE, ICM_WHOAMI_20602, ICM_WHOAMI_20608, ICM_WHOAMI_20689, is_icm_device(), is_mpu_device(), MPU6000_CHECKED_PRODUCT_ID_INDEX, MPU6000_REV_C4, MPU6000_REV_C5, MPU6000_REV_D10, MPU6000_REV_D6, MPU6000_REV_D7, MPU6000_REV_D8, MPU6000_REV_D9, MPU6000ES_REV_C4, MPU6000ES_REV_C5, MPU6000ES_REV_D6, MPU6000ES_REV_D7, MPU6000ES_REV_D8, MPU6050_REV_D8, MPU_DEVICE_TYPE_ICM20602, MPU_DEVICE_TYPE_ICM20608, MPU_DEVICE_TYPE_ICM20689, MPU_DEVICE_TYPE_MPU6000, MPU_WHOAMI_6000, MPUREG_PRODUCT_ID, MPUREG_WHOAMI, OK, PX4_WARN, and read_reg().
Referenced by init().
ssize_t MPU6000::read (struct file * filp, char * buffer, size_t buflen) virtual
Definition at line 1013 of file mpu6000.cpp.
References _accel_reports, _call_interval, accel_report, and measure().
uint8_t MPU6000::read_reg (unsigned reg, uint32_t speed = MPU6000_LOW_BUS_SPEED) private
Read a register from the MPU6000.
Parameters
The register to read.
Returns
The value that was read.
Definition at line 1481 of file mpu6000.cpp.
References _interface, and MPU6000_SET_SPEED.
Referenced by check_registers(), factory_self_test(), is_i2c(), modify_reg(), print_info(), print_registers(), probe(), and reset().
uint16_t MPU6000::read_reg16 (unsigned reg) private
Definition at line 1489 of file mpu6000.cpp.
References _interface, arraySize, and MPU6000_LOW_SPEED_OP.
Referenced by is_i2c().
int MPU6000::reset () private
Reset chip.
Resets the chip and measurements ranges, but not scale and offset.
Definition at line 742 of file mpu6000.cpp.
References _gyro_range_rad_s, _gyro_range_scale, _reset_retries, _reset_wait, _sample_rate, _set_dlpf_filter(), _set_icm_acc_dlpf_filter(), _set_sample_rate(), BIT_H_RESET, BIT_I2C_IF_DIS, BIT_INT_ANYRD_2CLEAR, BIT_RAW_RDY_EN, BITS_FS_2000DPS, hrt_absolute_time(), is_i2c(), is_icm_device(), M_PI_F, MPU6000_ACCEL_DEFAULT_RANGE_G, MPU6000_DEFAULT_ONCHIP_FILTER_FREQ, MPU_CLK_SEL_PLLGYROZ, MPUREG_GYRO_CONFIG, MPUREG_ICM_UNDOC1, MPUREG_ICM_UNDOC1_VALUE, MPUREG_INT_ENABLE, MPUREG_INT_PIN_CFG, MPUREG_PWR_MGMT_1, MPUREG_USER_CTRL, OK, perf_count(), read_reg(), set_accel_range(), state, usleep(), write_checked_reg(), and write_reg().
Referenced by init(), ioctl(), and stop().
int MPU6000::self_test () private
Measurement self test.
Returns
0 on success, 1 on failure
Definition at line 1051 of file mpu6000.cpp.
References _sample_perf, measure(), and perf_event_count().
Referenced by is_external().
int MPU6000::set_accel_range (unsigned max_g) private
Set the MPU6000 measurement range.
Parameters
max_g The maximum G value the range must support.
Returns
OK if the value can be supported, -ERANGE otherwise.
Definition at line 1531 of file mpu6000.cpp.
References _accel_range_m_s2, _accel_range_scale, _product, CONSTANTS_ONE_G, is_mpu_device(), MPU6000_REV_C4, MPU6000_REV_C5, MPU6000ES_REV_C4, MPU6000ES_REV_C5, MPUREG_ACCEL_CONFIG, OK, and write_checked_reg().
Referenced by ioctl(), is_i2c(), and reset().
void MPU6000::start () private
Start automatic measurement.
Definition at line 1580 of file mpu6000.cpp.
References _accel_reports, _call, _call_interval, _gyro_reports, hrt_call_every(), is_i2c(), measure_trampoline(), MPU6000_TIMER_REDUCTION, and stop().
Referenced by ioctl(), and stop().
void MPU6000::stop () private
Stop automatic measurement.
Definition at line 1607 of file mpu6000.cpp.
References _accel_reports, _call, _call_interval, _gyro_reports, _last_accel, hrt_cancel(), is_i2c(), measure(), MPU6000_TIMER_REDUCTION, OK, reset(), and start().
Referenced by ioctl(), start(), and ~MPU6000().
uint16_t MPU6000::swap16 (uint16_t val) inline private
Swap a 16-bit value read from the MPU6000 to native byte order.
Definition at line 369 of file mpu6000.cpp.
void MPU6000::test_error ()
Definition at line 1217 of file mpu6000.cpp.
References _in_factory_test, _interface, data, MPU6000_LOW_BUS_SPEED, MPU6000_SET_SPEED, MPUREG_INT_STATUS, and print_registers().
Referenced by mpu6000::testerror().
void MPU6000::write_checked_reg (unsigned reg, uint8_t value) private
Write a register in the MPU6000, updating _checked_values.
Parameters
reg The register to write.
value The new value to write.
Definition at line 1519 of file mpu6000.cpp.
References _checked_registers, _checked_values, MPU6000_NUM_CHECKED_REGISTERS, and write_reg().
Referenced by _set_dlpf_filter(), _set_icm_acc_dlpf_filter(), _set_sample_rate(), is_i2c(), reset(), and set_accel_range().
int MPU6000::write_reg (unsigned reg, uint8_t value) private
Write a register in the MPU6000.
Parameters
reg The register to write.
value The new value to write.
Definition at line 1500 of file mpu6000.cpp.
References _interface, and MPU6000_LOW_SPEED_OP.
Referenced by check_registers(), factory_self_test(), is_i2c(), modify_reg(), reset(), and write_checked_reg().
Friends And Related Function Documentation
friend class MPU6000_gyro friend
Definition at line 165 of file mpu6000.cpp.
Member Data Documentation
int MPU6000::_accel_class_instance private
Definition at line 194 of file mpu6000.cpp.
Referenced by init(), MPU6000(), and ~MPU6000().
math::LowPassFilter2p MPU6000::_accel_filter_x private
Definition at line 214 of file mpu6000.cpp.
Referenced by init(), ioctl(), measure(), MPU6000(), and print_info().
math::LowPassFilter2p MPU6000::_accel_filter_y private
Definition at line 215 of file mpu6000.cpp.
Referenced by init(), ioctl(), measure(), and MPU6000().
math::LowPassFilter2p MPU6000::_accel_filter_z private
Definition at line 216 of file mpu6000.cpp.
Referenced by init(), ioctl(), measure(), and MPU6000().
Integrator MPU6000::_accel_int private
Definition at line 221 of file mpu6000.cpp.
Referenced by measure(), and MPU6000().
int MPU6000::_accel_orb_class_instance private
Definition at line 193 of file mpu6000.cpp.
Referenced by init(), and MPU6000().
float MPU6000::_accel_range_m_s2 private
Definition at line 191 of file mpu6000.cpp.
Referenced by ioctl(), MPU6000(), and set_accel_range().
float MPU6000::_accel_range_scale private
Definition at line 190 of file mpu6000.cpp.
Referenced by measure(), MPU6000(), and set_accel_range().
ringbuffer::RingBuffer* MPU6000::_accel_reports private
Definition at line 187 of file mpu6000.cpp.
Referenced by init(), ioctl(), measure(), MPU6000(), print_info(), read(), start(), stop(), and ~MPU6000().
struct accel_calibration_s MPU6000::_accel_scale private
Definition at line 189 of file mpu6000.cpp.
Referenced by init(), ioctl(), measure(), and MPU6000().
orb_advert_t MPU6000::_accel_topic private
Definition at line 192 of file mpu6000.cpp.
Referenced by init(), measure(), MPU6000(), and ~MPU6000().
perf_counter_t MPU6000::_bad_registers private
Definition at line 207 of file mpu6000.cpp.
Referenced by check_registers(), measure(), MPU6000(), print_info(), and ~MPU6000().
perf_counter_t MPU6000::_bad_transfers private
Definition at line 206 of file mpu6000.cpp.
Referenced by measure(), MPU6000(), print_info(), and ~MPU6000().
struct hrt_call MPU6000::_call private
Definition at line 184 of file mpu6000.cpp.
Referenced by ioctl(), MPU6000(), start(), and stop().
unsigned MPU6000::_call_interval private
Definition at line 185 of file mpu6000.cpp.
Referenced by gyro_read(), ioctl(), MPU6000(), read(), start(), and stop().
uint8_t MPU6000::_checked_next private
Definition at line 233 of file mpu6000.cpp.
Referenced by check_registers(), MPU6000(), and print_info().
const uint8_t MPU6000::_checked_registers static private
Initial value:
= { MPUREG_PRODUCT_ID,
                                         MPUREG_PWR_MGMT_1,
                                         MPUREG_USER_CTRL,
                                         MPUREG_SMPLRT_DIV,
                                         MPUREG_CONFIG,
                                         MPUREG_GYRO_CONFIG,
                                         MPUREG_ACCEL_CONFIG,
                                         MPUREG_INT_ENABLE,
                                         MPUREG_INT_PIN_CFG,
                                         MPUREG_ICM_UNDOC1
                                       }
Definition at line 231 of file mpu6000.cpp.
Referenced by check_registers(), is_external(), print_info(), and write_checked_reg().
uint8_t MPU6000::_checked_values[MPU6000_NUM_CHECKED_REGISTERS] private
Definition at line 232 of file mpu6000.cpp.
Referenced by check_registers(), print_info(), probe(), and write_checked_reg().
int MPU6000::_device_type private
Definition at line 171 of file mpu6000.cpp.
Referenced by MPU6000(), and probe().
perf_counter_t MPU6000::_duplicates private
Definition at line 209 of file mpu6000.cpp.
Referenced by measure(), MPU6000(), print_info(), and ~MPU6000().
bool MPU6000::_got_duplicate private
Definition at line 244 of file mpu6000.cpp.
Referenced by measure(), and MPU6000().
MPU6000_gyro* MPU6000::_gyro private
Definition at line 172 of file mpu6000.cpp.
Referenced by init(), measure(), MPU6000(), and ~MPU6000().
math::LowPassFilter2p MPU6000::_gyro_filter_x private
Definition at line 217 of file mpu6000.cpp.
Referenced by init(), ioctl(), measure(), MPU6000(), and print_info().
math::LowPassFilter2p MPU6000::_gyro_filter_y private
Definition at line 218 of file mpu6000.cpp.
Referenced by init(), ioctl(), measure(), and MPU6000().
math::LowPassFilter2p MPU6000::_gyro_filter_z private
Definition at line 219 of file mpu6000.cpp.
Referenced by init(), ioctl(), measure(), and MPU6000().
Integrator MPU6000::_gyro_int private
Definition at line 222 of file mpu6000.cpp.
Referenced by measure(), and MPU6000().
float MPU6000::_gyro_range_rad_s private
Definition at line 200 of file mpu6000.cpp.
Referenced by gyro_ioctl(), MPU6000(), and reset().
float MPU6000::_gyro_range_scale private
Definition at line 199 of file mpu6000.cpp.
Referenced by measure(), MPU6000(), and reset().
ringbuffer::RingBuffer* MPU6000::_gyro_reports private
Definition at line 196 of file mpu6000.cpp.
Referenced by gyro_ioctl(), gyro_read(), init(), measure(), MPU6000(), print_info(), start(), stop(), and ~MPU6000().
struct gyro_calibration_s MPU6000::_gyro_scale private
Definition at line 198 of file mpu6000.cpp.
Referenced by gyro_ioctl(), init(), measure(), and MPU6000().
volatile bool MPU6000::_in_factory_test private
Definition at line 237 of file mpu6000.cpp.
Referenced by factory_self_test(), measure(), MPU6000(), and test_error().
Device* MPU6000::_interface protected
Definition at line 161 of file mpu6000.cpp.
Referenced by factory_self_test(), init(), ioctl(), measure(), MPU6000(), read_reg(), read_reg16(), test_error(), and write_reg().
uint16_t MPU6000::_last_accel[3] private
Definition at line 243 of file mpu6000.cpp.
Referenced by measure(), MPU6000(), and stop().
float MPU6000::_last_temperature private
Definition at line 240 of file mpu6000.cpp.
Referenced by measure(), MPU6000(), and print_info().
perf_counter_t MPU6000::_measure_interval private
Definition at line 205 of file mpu6000.cpp.
Referenced by measure(), MPU6000(), and ~MPU6000().
uint8_t MPU6000::_product private
Definition at line 173 of file mpu6000.cpp.
Referenced by probe(), and set_accel_range().
uint8_t MPU6000::_register_wait private
Definition at line 211 of file mpu6000.cpp.
Referenced by check_registers(), measure(), and MPU6000().
perf_counter_t MPU6000::_reset_retries private
Definition at line 208 of file mpu6000.cpp.
Referenced by MPU6000(), print_info(), reset(), and ~MPU6000().
uint64_t MPU6000::_reset_wait private
Definition at line 212 of file mpu6000.cpp.
Referenced by check_registers(), measure(), MPU6000(), and reset().
enum Rotation MPU6000::_rotation private
Definition at line 224 of file mpu6000.cpp.
Referenced by measure(), and MPU6000().
perf_counter_t MPU6000::_sample_perf private
Definition at line 204 of file mpu6000.cpp.
Referenced by measure(), MPU6000(), print_info(), self_test(), and ~MPU6000().
unsigned MPU6000::_sample_rate private
Definition at line 202 of file mpu6000.cpp.
Referenced by _set_sample_rate(), gyro_ioctl(), ioctl(), MPU6000(), and reset().
bool MPU6000::_use_hrt private
product code
Definition at line 182 of file mpu6000.cpp.
Referenced by is_i2c(), and MPU6000().
The documentation for this class was generated from the following file:
src/drivers/imu/mpu6000/mpu6000.cpp