PX4 Firmware: PMW3901 Class Reference
PMW3901 Class Reference
Public Member Functions
PMW3901 (uint8_t rotation=distance_sensor_s::ROTATION_DOWNWARD_FACING, int bus=PMW3901_BUS)
virtual ~PMW3901 ()
virtual int init ()
virtual ssize_t read (device::file_t *filp, char *buffer, size_t buflen)
virtual int ioctl (device::file_t *filp, int cmd, unsigned long arg)
void print_info ()
Diagnostics - print some basic information about the driver.
Protected Member Functions
virtual int probe ()
Private Member Functions
void start ()
Initialise the automatic measurement state machine and start it.
void stop ()
Stop the automatic measurement state machine.
void cycle ()
Perform a poll cycle; collect from the previous measurement and start a new one.
int collect ()
int readRegister (unsigned reg, uint8_t *data, unsigned count)
int writeRegister (unsigned reg, uint8_t data)
int sensorInit ()
int readMotionCount (int16_t &deltaX, int16_t &deltaY)
Static Private Member Functions
static void cycle_trampoline (void *arg)
Static trampoline from the workq context; because we don't have a generic workq wrapper yet.
Private Attributes
uint8_t _rotation
work_s _work
ringbuffer::RingBuffer * _reports
bool _sensor_ok
int _measure_ticks
int _class_instance
int _orb_class_instance
orb_advert_t _optical_flow_pub
orb_advert_t _subsystem_pub
perf_counter_t _sample_perf
perf_counter_t _comms_errors
uint64_t _previous_collect_timestamp
enum Rotation _sensor_rotation
int _flow_sum_x = 0
int _flow_sum_y = 0
uint64_t _flow_dt_sum_usec = 0
Detailed Description
Definition at line 108 of file pmw3901.cpp.
Constructor & Destructor Documentation
PMW3901::PMW3901 (uint8_t rotation = distance_sensor_s::ROTATION_DOWNWARD_FACING, int bus = PMW3901_BUS)
Definition at line 196 of file pmw3901.cpp.
Referenced by pmw3901::start().
PMW3901::~PMW3901 () virtual
Definition at line 219 of file pmw3901.cpp.
References _comms_errors, _reports, _sample_perf, perf_free(), and stop().
Member Function Documentation
int PMW3901::collect () private
Definition at line 552 of file pmw3901.cpp.
References _flow_dt_sum_usec, _flow_sum_x, _flow_sum_y, _optical_flow_pub, _previous_collect_timestamp, _reports, _sample_perf, f(), optical_flow_s::frame_count_since_last_readout, optical_flow_s::gyro_x_rate_integral, optical_flow_s::gyro_y_rate_integral, optical_flow_s::gyro_z_rate_integral, hrt_absolute_time(), optical_flow_s::integration_timespan, OK, orb_advertise(), ORB_ID, orb_publish(), perf_begin(), perf_end(), optical_flow_s::pixel_flow_x_integral, optical_flow_s::pixel_flow_y_integral, optical_flow_s::quality, readMotionCount(), optical_flow_s::sensor_id, and optical_flow_s::timestamp.
Referenced by cycle(), and read().
void PMW3901::cycle () private
Perform a poll cycle; collect from the previous measurement and start a new one.
Definition at line 691 of file pmw3901.cpp.
References collect(), cycle_trampoline(), and PMW3901_SAMPLE_RATE.
Referenced by cycle_trampoline().
void PMW3901::cycle_trampoline (void * arg) static private
Static trampoline from the workq context; because we don't have a generic workq wrapper yet.
Parameters
arg Instance pointer for the driver that is polling.
Definition at line 683 of file pmw3901.cpp.
References cycle().
Referenced by cycle(), and start().
int PMW3901::init () virtual
Definition at line 340 of file pmw3901.cpp.
References _previous_collect_timestamp, _reports, _sensor_ok, hrt_absolute_time(), lis3mdl::init(), OK, PX4_ERROR, and sensorInit().
Referenced by pmw3901::start().
int PMW3901::ioctl (device::file_t * filp, int cmd, unsigned long arg) virtual
Definition at line 389 of file pmw3901.cpp.
References _measure_ticks, OK, PMW3901_SAMPLE_RATE, SENSOR_POLLRATE_DEFAULT, SENSOR_POLLRATE_MANUAL, SENSORIOCSPOLLRATE, start(), and stop().
Referenced by pmw3901::start().
void PMW3901::print_info ()
Diagnostics - print some basic information about the driver.
Definition at line 705 of file pmw3901.cpp.
References _comms_errors, _measure_ticks, _reports, _sample_perf, and perf_print_counter().
Referenced by pmw3901::info().
int PMW3901::probe () protected virtual
Definition at line 372 of file pmw3901.cpp.
References data, OK, and readRegister().
ssize_t PMW3901::read (device::file_t * filp, char * buffer, size_t buflen) virtual
Definition at line 455 of file pmw3901.cpp.
References _measure_ticks, _reports, collect(), and OK.
Referenced by pmw3901::test().
int PMW3901::readMotionCount (int16_t & deltaX, int16_t & deltaY) private
Definition at line 624 of file pmw3901.cpp.
References _comms_errors, data, DEVICE_LOG, DIR_READ, OK, and perf_count().
Referenced by collect().
int PMW3901::readRegister (unsigned reg, uint8_t * data, unsigned count) private
Definition at line 507 of file pmw3901.cpp.
References _comms_errors, DEVICE_LOG, DIR_READ, OK, and perf_count().
Referenced by probe(), and sensorInit().
int PMW3901::sensorInit () private
Definition at line 236 of file pmw3901.cpp.
References data, OK, readRegister(), usleep(), and writeRegister().
Referenced by init().
void PMW3901::start () private
Initialise the automatic measurement state machine and start it.
Note
This function is called at open and error time. It might make sense to make it more aggressive about resetting the bus in case of errors.
Definition at line 651 of file pmw3901.cpp.
References _reports, _subsystem_pub, cycle_trampoline(), subsystem_info_s::enabled, hrt_absolute_time(), subsystem_info_s::ok, orb_advertise(), ORB_ID, orb_publish(), PMW3901_US, subsystem_info_s::present, subsystem_info_s::subsystem_type, and subsystem_info_s::timestamp.
Referenced by ioctl().
void PMW3901::stop () private
Stop the automatic measurement state machine.
Definition at line 677 of file pmw3901.cpp.
Referenced by ioctl(), and ~PMW3901().
int PMW3901::writeRegister (unsigned reg, uint8_t data) private
Definition at line 530 of file pmw3901.cpp.
References _comms_errors, data, DEVICE_LOG, DIR_WRITE, OK, and perf_count().
Referenced by sensorInit().
Member Data Documentation
int PMW3901::_class_instance private
Definition at line 135 of file pmw3901.cpp.
perf_counter_t PMW3901::_comms_errors private
Definition at line 142 of file pmw3901.cpp.
Referenced by print_info(), readMotionCount(), readRegister(), writeRegister(), and ~PMW3901().
uint64_t PMW3901::_flow_dt_sum_usec = 0 private
Definition at line 149 of file pmw3901.cpp.
Referenced by collect().
int PMW3901::_flow_sum_x = 0 private
Definition at line 147 of file pmw3901.cpp.
Referenced by collect().
int PMW3901::_flow_sum_y = 0 private
Definition at line 148 of file pmw3901.cpp.
Referenced by collect().
int PMW3901::_measure_ticks private
Definition at line 134 of file pmw3901.cpp.
Referenced by ioctl(), print_info(), and read().
orb_advert_t PMW3901::_optical_flow_pub private
Definition at line 138 of file pmw3901.cpp.
Referenced by collect().
int PMW3901::_orb_class_instance private
Definition at line 136 of file pmw3901.cpp.
uint64_t PMW3901::_previous_collect_timestamp private
Definition at line 144 of file pmw3901.cpp.
Referenced by collect(), and init().
ringbuffer::RingBuffer* PMW3901::_reports private
Definition at line 132 of file pmw3901.cpp.
Referenced by collect(), init(), print_info(), read(), start(), and ~PMW3901().
uint8_t PMW3901::_rotation private
Definition at line 130 of file pmw3901.cpp.
perf_counter_t PMW3901::_sample_perf private
Definition at line 141 of file pmw3901.cpp.
Referenced by collect(), print_info(), and ~PMW3901().
bool PMW3901::_sensor_ok private
Definition at line 133 of file pmw3901.cpp.
Referenced by init().
enum Rotation PMW3901::_sensor_rotation private
Definition at line 146 of file pmw3901.cpp.
orb_advert_t PMW3901::_subsystem_pub private
Definition at line 139 of file pmw3901.cpp.
Referenced by start().
work_s PMW3901::_work private
Definition at line 131 of file pmw3901.cpp.
The documentation for this class was generated from the following file:
src/drivers/pmw3901/pmw3901.cpp