PX4 Firmware: MavlinkStreamAttitudeQuaternion Class Reference
MavlinkStreamAttitudeQuaternion Class Reference
Public Member Functions
const char * get_name () const override
uint16_t get_id () override
unsigned get_size () override
Get maximal total messages size on update.
Public Member Functions inherited from MavlinkStream
MavlinkStream (Mavlink *mavlink)
virtual ~MavlinkStream ()=default
MavlinkStream (const MavlinkStream &)=delete
MavlinkStream & operator= (const MavlinkStream &)=delete
MavlinkStream (MavlinkStream &&)=delete
MavlinkStream & operator= (MavlinkStream &&)=delete
void set_interval (const int interval)
Get the interval.
int get_interval ()
Get the interval.
int update (const hrt_abstime &t)
Update subscriptions and send message if necessary.
virtual bool const_rate ()
virtual unsigned get_size_avg ()
Get the average message size.
bool first_message_sent () const
void reset_last_sent ()
Reset the time of last sent to 0.
Public Member Functions inherited from ListNode< MavlinkStream *>
void setSibling (MavlinkStream * sibling)
const MavlinkStream * getSibling () const
Static Public Member Functions
static const char * get_name_static ()
static uint16_t get_id_static ()
static MavlinkStream * new_instance (Mavlink *mavlink)
Protected Member Functions
MavlinkStreamAttitudeQuaternion (Mavlink *mavlink)
bool send (const hrt_abstime t) override
Protected Member Functions inherited from MavlinkStream
virtual void update_data ()
Function to collect/update data for the streams at a high rate independant of actual stream rate.
Private Member Functions
MavlinkStreamAttitudeQuaternion (MavlinkStreamAttitudeQuaternion &)=delete
MavlinkStreamAttitudeQuaternion & operator= (const MavlinkStreamAttitudeQuaternion &)=delete
Private Attributes
MavlinkOrbSubscription * _att_sub
MavlinkOrbSubscription * _angular_velocity_sub
MavlinkOrbSubscription * _status_sub
uint64_t _att_time {0}
Additional Inherited Members
Protected Attributes inherited from MavlinkStream
Mavlink *const _mavlink
int _interval {1000000}
if set to negative value = unlimited rate
Protected Attributes inherited from ListNode< MavlinkStream *>
MavlinkStream * _list_node_sibling
Detailed Description
Definition at line 1257 of file mavlink_messages.cpp.
Constructor & Destructor Documentation
MavlinkStreamAttitudeQuaternion() [1/2]
MavlinkStreamAttitudeQuaternion::MavlinkStreamAttitudeQuaternion (MavlinkStreamAttitudeQuaternion &) private delete
MavlinkStreamAttitudeQuaternion() [2/2]
MavlinkStreamAttitudeQuaternion::MavlinkStreamAttitudeQuaternion (Mavlink * mavlink) inline explicit protected
Definition at line 1301 of file mavlink_messages.cpp.
Member Function Documentation
get_id()
uint16_t MavlinkStreamAttitudeQuaternion::get_id () inline override virtual
Implements MavlinkStream.
Definition at line 1275 of file mavlink_messages.cpp.
References MavlinkStreamHeartbeat::get_id_static().
get_id_static()
static uint16_t MavlinkStreamAttitudeQuaternion::get_id_static () inline static
Definition at line 1270 of file mavlink_messages.cpp.
get_name()
const char* MavlinkStreamAttitudeQuaternion::get_name () const inline override virtual
Implements MavlinkStream.
Definition at line 1260 of file mavlink_messages.cpp.
References get_name_static().
get_name_static()
static const char* MavlinkStreamAttitudeQuaternion::get_name_static () inline static
Definition at line 1265 of file mavlink_messages.cpp.
Referenced by get_name().
get_size()
unsigned MavlinkStreamAttitudeQuaternion::get_size () inline override virtual
Get maximal total messages size on update.
Implements MavlinkStream.
Definition at line 1285 of file mavlink_messages.cpp.
new_instance()
static MavlinkStream* MavlinkStreamAttitudeQuaternion::new_instance (Mavlink * mavlink) inline static
Definition at line 1280 of file mavlink_messages.cpp.
operator=()
MavlinkStreamAttitudeQuaternion& MavlinkStreamAttitudeQuaternion::operator= (const MavlinkStreamAttitudeQuaternion &) private delete
send()
bool MavlinkStreamAttitudeQuaternion::send (const hrt_abstime t) inline override protected virtual
Implements MavlinkStream.
Definition at line 1307 of file mavlink_messages.cpp.
References MavlinkStream::_mavlink, matrix::Matrix< Type, M, N >::copyTo(), Mavlink::get_channel(), get_rot_quaternion(), vehicle_status_s::is_vtol, vehicle_status_s::is_vtol_tailsitter, msg, vehicle_attitude_s::q, ROTATION_PITCH_90, status, vehicle_attitude_s::timestamp, MavlinkOrbSubscription::update(), vehicle_status_s::vehicle_type, and VEHICLE_TYPE_FIXED_WING.
Member Data Documentation
_angular_velocity_sub
MavlinkOrbSubscription* MavlinkStreamAttitudeQuaternion::_angular_velocity_sub private
Definition at line 1292 of file mavlink_messages.cpp.
_att_sub
MavlinkOrbSubscription* MavlinkStreamAttitudeQuaternion::_att_sub private
Definition at line 1291 of file mavlink_messages.cpp.
_att_time
uint64_t MavlinkStreamAttitudeQuaternion::_att_time {0} private
Definition at line 1294 of file mavlink_messages.cpp.
_status_sub
MavlinkOrbSubscription* MavlinkStreamAttitudeQuaternion::_status_sub private
Definition at line 1293 of file mavlink_messages.cpp.
The documentation for this class was generated from the following file:
src/modules/mavlink/mavlink_messages.cpp