PX4 Firmware: src/drivers/navio_rgbled/test/main.cpp File Reference
main.cpp File Reference
Functions
int do_test ()
int main ()
Function Documentation
int do_test ()
Definition at line 49 of file test.cpp.
References ets_airspeed::g_dev, RGBLED0_DEVICE_PATH, and RGBLED::start().
Referenced by main().
int main ()
Definition at line 36 of file main.cpp.
References do_test().
Referenced by commander_main(), ekf2_main(), fmu_main(), fw_att_control_main(), fw_pos_control_l1_main(), gps_main(), land_detector::land_detector_main(), load_mon::load_mon_main(), local_position_estimator_main(), logger_main(), mc_att_control_main(), navigator_main(), pwm_out_sim_main(), rc_input_main(), replay_main(), events::send_event_main(), sensors_main(), tap_esc_main(), and wind_estimator_main().