PX4 Firmware: src/modules/simulator/airspeedsim/meas_airspeed_sim.cpp File Reference
meas_airspeed_sim.cpp File Reference
#include <px4_config.h>
#include <sys/types.h>
#include <stdint.h>
#include <stdlib.h>
#include <stdbool.h>
#include <semaphore.h>
#include <string.h>
#include <fcntl.h>
#include <poll.h>
#include <errno.h>
#include <stdio.h>
#include <math.h>
#include <unistd.h>
#include <systemlib/err.h>
#include <parameters/param.h>
#include <perf/perf_counter.h>
#include <mathlib/math/filter/LowPassFilter2p.hpp>
#include <drivers/drv_airspeed.h>
#include <drivers/drv_hrt.h>
#include <uORB/uORB.h>
#include <uORB/topics/differential_pressure.h>
#include <uORB/topics/system_power.h>
#include "airspeedsim.h"
Classes
class MEASAirspeedSim
Namespaces
meas_airspeed_sim
Local functions in support of the shell command.
Macros
#define I2C_ADDRESS_MS4525DO 0x28
7-bit address.
#define PATH_MS4525 "/dev/ms4525"
#define I2C_ADDRESS_MS5525DSO 0x77
#define PATH_MS5525 "/dev/ms5525"
#define ADDR_READ_MR 0x00 /* write to this address to start conversion */
#define MEAS_RATE 100
#define MEAS_DRIVER_FILTER_FREQ 1.2f
#define CONVERSION_INTERVAL (1000000 / MEAS_RATE) /* microseconds */
Functions
__EXPORT int measairspeedsim_main (int argc, char *argv[])
int meas_airspeed_sim::start (int i2c_bus)
Start the driver.
int meas_airspeed_sim::stop ()
Stop the driver.
int meas_airspeed_sim::test ()
Perform some basic functional tests on the driver; make sure we can collect data from the sensor in polled and automatic modes.
int meas_airspeed_sim::reset ()
Reset the driver.
int meas_airspeed_sim::info ()
Print a little info about the driver.
static void meas_airspeed_usage ()
Variables
MEASAirspeedSim * meas_airspeed_sim::g_dev = nullptr
Detailed Description
Author
Lorenz Meier loren.nosp@m.z@px.nosp@m.4.io
Sarthak Kaingade
Simon Wilks
Thomas Gubler
Roman Bapst
Driver for a simulated airspeed sensor.
Definition in file meas_airspeed_sim.cpp.
Macro Definition Documentation
#define ADDR_READ_MR 0x00 /* write to this address to start conversion */
Definition at line 85 of file meas_airspeed_sim.cpp.
#define CONVERSION_INTERVAL (1000000 / MEAS_RATE) /* microseconds */
Definition at line 90 of file meas_airspeed_sim.cpp.
Referenced by MEASAirspeedSim::cycle().
#define I2C_ADDRESS_MS4525DO 0x28
7-bit address.
Depends on the order code (this is for code "I")
Definition at line 78 of file meas_airspeed_sim.cpp.
Referenced by meas_airspeed_sim::start().
#define I2C_ADDRESS_MS5525DSO 0x77
Definition at line 81 of file meas_airspeed_sim.cpp.
Referenced by meas_airspeed_sim::start().
#define MEAS_DRIVER_FILTER_FREQ 1.2f
Definition at line 89 of file meas_airspeed_sim.cpp.
#define MEAS_RATE 100
Definition at line 88 of file meas_airspeed_sim.cpp.
#define PATH_MS4525 "/dev/ms4525"
Definition at line 79 of file meas_airspeed_sim.cpp.
Referenced by meas_airspeed_sim::reset(), meas_airspeed_sim::start(), and meas_airspeed_sim::test().
#define PATH_MS5525 "/dev/ms5525"
Definition at line 82 of file meas_airspeed_sim.cpp.
Referenced by ms5525_airspeed::reset(), meas_airspeed_sim::start(), and ms5525_airspeed::start_bus().
Function Documentation
static void meas_airspeed_usage () static
Definition at line 488 of file meas_airspeed_sim.cpp.
References PX4_WARN.
Referenced by measairspeedsim_main().
int measairspeedsim_main (int argc, char * argv[])
Definition at line 498 of file meas_airspeed_sim.cpp.
References meas_airspeed_sim::info(), meas_airspeed_usage(), meas_airspeed_sim::reset(), meas_airspeed_sim::start(), meas_airspeed_sim::stop(), and meas_airspeed_sim::test().