PX4 Firmware: MPU9250_SPI Class Reference
MPU9250_SPI Class Reference
Public Member Functions
MPU9250_SPI (int bus, uint32_t device)
virtual ~MPU9250_SPI ()=default
virtual int read (unsigned address, void *data, unsigned count)
virtual int write (unsigned address, void *data, unsigned count)
virtual int ioctl (unsigned operation, unsigned &arg)
Protected Member Functions
virtual int probe ()
Private Member Functions
void set_bus_frequency (unsigned &reg_speed_reg_out)
Detailed Description
Definition at line 83 of file mpu9250_spi.cpp.
Constructor & Destructor Documentation
MPU9250_SPI::MPU9250_SPI (int bus, uint32_t device)
Definition at line 121 of file mpu9250_spi.cpp.
References DRV_ACC_DEVTYPE_MPU9250.
virtual MPU9250_SPI::~MPU9250_SPI () virtual default
Member Function Documentation
int MPU9250_SPI::ioctl (unsigned operation, unsigned & arg) virtual
Definition at line 128 of file mpu9250_spi.cpp.
References ACCELIOCGEXTERNAL, and MPUIOCGIS_I2C.
int MPU9250_SPI::probe () protected virtual
Definition at line 230 of file mpu9250_spi.cpp.
References MPU_WHOAMI_6500, MPU_WHOAMI_9250, MPUREG_WHOAMI, OK, PX4_WARN, and read().
int MPU9250_SPI::read (unsigned address, void * data, unsigned count) virtual
Definition at line 185 of file mpu9250_spi.cpp.
References data, DIR_READ, OK, and set_bus_frequency().
Referenced by probe().
void MPU9250_SPI::set_bus_frequency (unsigned & reg_speed_reg_out) private
Definition at line 154 of file mpu9250_spi.cpp.
References MPU9250_HIGH_SPI_BUS_SPEED, MPU9250_IS_HIGH_SPEED, MPU9250_LOW_SPI_BUS_SPEED, and MPU9250_REG.
Referenced by read(), and write().
int MPU9250_SPI::write (unsigned address, void * data, unsigned count) virtual
Definition at line 166 of file mpu9250_spi.cpp.
References DIR_WRITE, MPU_MAX_WRITE_BUFFER_SIZE, and set_bus_frequency().
The documentation for this class was generated from the following file:
src/drivers/imu/mpu9250/mpu9250_spi.cpp