PX4 Firmware: MavlinkOrbSubscription Class Reference
MavlinkOrbSubscription Class Reference
#include <mavlink_orb_subscription.h>
Public Member Functions
MavlinkOrbSubscription (const orb_id_t topic, int instance)
~MavlinkOrbSubscription ()
bool update (uint64_t *time, void *data)
Check if subscription updated based on timestamp.
bool update (void *data)
Copy topic data to given buffer.
bool update_if_changed (void *data)
Check if the subscription has been updated.
bool is_published ()
Check if the topic has been published.
void subscribe_from_beginning (bool from_beginning)
orb_id_t get_topic () const
int get_instance () const
int get_fd ()
Public Attributes
MavlinkOrbSubscription * next {nullptr}
pointer to next subscription in list
Private Member Functions
MavlinkOrbSubscription (const MavlinkOrbSubscription &)
MavlinkOrbSubscription operator= (const MavlinkOrbSubscription &)
Private Attributes
const orb_id_t _topic
topic metadata
const uint8_t _instance
get topic instance
int _fd {-1}
subscription handle
bool _published {false}
topic was ever published
bool _subscribe_from_beginning {false}
we need to subscribe from the beginning, e.g. for vehicle_command_acks
hrt_abstime _last_pub_check {0}
when we checked last
Detailed Description
Definition at line 48 of file mavlink_orb_subscription.h.
Constructor & Destructor Documentation
MavlinkOrbSubscription::MavlinkOrbSubscription (const orb_id_t topic, int instance)
Definition at line 52 of file mavlink_orb_subscription.cpp.
MavlinkOrbSubscription::~MavlinkOrbSubscription ()
Definition at line 58 of file mavlink_orb_subscription.cpp.
References _fd, and orb_unsubscribe().
MavlinkOrbSubscription::MavlinkOrbSubscription (const MavlinkOrbSubscription &) private
Member Function Documentation
int MavlinkOrbSubscription::get_fd () inline
Definition at line 96 of file mavlink_orb_subscription.h.
References _fd.
int MavlinkOrbSubscription::get_instance () const
Definition at line 72 of file mavlink_orb_subscription.cpp.
References _instance.
Referenced by Mavlink::add_orb_subscription().
orb_id_t MavlinkOrbSubscription::get_topic () const
Definition at line 66 of file mavlink_orb_subscription.cpp.
References _topic.
Referenced by Mavlink::add_orb_subscription().
bool MavlinkOrbSubscription::is_published ()
Check if the topic has been published.
This call will return true if the topic was ever published.
Returns
true if the topic has been published at least once. If no data is available the buffer will be filled with zeros.
Definition at line 136 of file mavlink_orb_subscription.cpp.
References _fd, _instance, _last_pub_check, _published, _subscribe_from_beginning, _topic, hrt_absolute_time(), hrt_abstime, orb_check(), orb_exists(), and orb_subscribe_multi().
Referenced by MavlinkStreamHomePosition::send(), update(), and update_if_changed().
MavlinkOrbSubscription MavlinkOrbSubscription::operator= (const MavlinkOrbSubscription &) private
void MavlinkOrbSubscription::subscribe_from_beginning (bool from_beginning)
Definition at line 175 of file mavlink_orb_subscription.cpp.
References _subscribe_from_beginning.
Referenced by Mavlink::task_main().
bool MavlinkOrbSubscription::update (uint64_t * time, void * data)
Check if subscription updated based on timestamp.
Returns
true only if topic was updated based on a timestamp and copied to buffer successfully. If topic was not updated since last check it will return false but still copy the data. If no data available data buffer will be filled with zeros.
Definition at line 78 of file mavlink_orb_subscription.cpp.
References _fd, _topic, is_published(), orb_copy(), orb_stat(), and PX4_OK.
Referenced by MavlinkStreamHeartbeat::send(), MavlinkStreamSysStatus::send(), MavlinkStreamHighresIMU::send(), MavlinkStreamScaledIMU::send(), MavlinkStreamScaledIMU2::send(), MavlinkStreamScaledIMU3::send(), MavlinkStreamAttitude::send(), MavlinkStreamAttitudeQuaternion::send(), MavlinkStreamVFRHUD::send(), MavlinkStreamGPSRawInt::send(), MavlinkStreamADSBVehicle::send(), MavlinkStreamCollision::send(), MavlinkStreamCameraTrigger::send(), MavlinkStreamCameraImageCaptured::send(), MavlinkStreamGlobalPositionInt::send(), MavlinkStreamVisionPositionEstimate::send(), MavlinkStreamLocalPositionNED::send(), MavlinkStreamLocalPositionNEDCOV::send(), MavlinkStreamEstimatorStatus::send(), MavlinkStreamAttPosMocap::send(), MavlinkStreamHomePosition::send(), MavlinkStreamServoOutputRaw< N >::send(), MavlinkStreamActuatorControlTarget< N >::send(), MavlinkStreamHILActuatorControls::send(), MavlinkStreamPositionTargetGlobalInt::send(), MavlinkStreamLocalPositionSetpoint::send(), MavlinkStreamAttitudeTarget::send(), MavlinkStreamRCChannels::send(), MavlinkStreamManualControl::send(), MavlinkStreamTrajectoryRepresentationWaypoints::send(), MavlinkStreamOpticalFlowRad::send(), MavlinkStreamNamedValueFloat::send(), MavlinkStreamDebug::send(), MavlinkStreamDebugVect::send(), MavlinkStreamNavControllerOutput::send(), MavlinkStreamCameraCapture::send(), MavlinkStreamDistanceSensor::send(), MavlinkStreamExtendedSysState::send(), MavlinkStreamAltitude::send(), MavlinkStreamWind::send(), MavlinkStreamMountOrientation::send(), MavlinkStreamGroundTruth::send(), Mavlink::task_main(), MavlinkStreamHighLatency2::update_airspeed(), MavlinkStreamHighLatency2::update_battery_status(), MavlinkStreamHighLatency2::update_global_position(), MavlinkStreamHighLatency2::update_gps(), update_if_changed(), MavlinkStreamHighLatency2::update_tecs_status(), MavlinkStreamHighLatency2::update_vehicle_status(), MavlinkStreamHighLatency2::update_wind_estimate(), MavlinkStreamHighLatency2::write_airspeed(), MavlinkStreamHighLatency2::write_attitude_sp(), MavlinkStreamHighLatency2::write_battery_status(), MavlinkStreamHighLatency2::write_estimator_status(), MavlinkStreamHighLatency2::write_fw_ctrl_status(), MavlinkStreamHighLatency2::write_geofence_result(), MavlinkStreamHighLatency2::write_global_position(), MavlinkStreamHighLatency2::write_mission_result(), MavlinkStreamHighLatency2::write_tecs_status(), MavlinkStreamHighLatency2::write_vehicle_status(), MavlinkStreamHighLatency2::write_vehicle_status_flags(), and MavlinkStreamHighLatency2::write_wind_estimate().
bool MavlinkOrbSubscription::update (void * data)
Copy topic data to given buffer.
Returns
true only if topic data copied successfully.
Definition at line 106 of file mavlink_orb_subscription.cpp.
References _fd, _topic, is_published(), orb_copy(), and PX4_OK.
bool MavlinkOrbSubscription::update_if_changed (void * data)
Check if the subscription has been updated.
Returns
true if there has been an update which has been copied successfully.
Definition at line 120 of file mavlink_orb_subscription.cpp.
References _fd, is_published(), orb_check(), and update().
Referenced by MavlinkStreamCommandLong::send(), and Mavlink::task_main().
Member Data Documentation
int MavlinkOrbSubscription::_fd {-1} private
subscription handle
Definition at line 102 of file mavlink_orb_subscription.h.
Referenced by get_fd(), is_published(), update(), update_if_changed(), and ~MavlinkOrbSubscription().
const uint8_t MavlinkOrbSubscription::_instance private
get topic instance
Definition at line 100 of file mavlink_orb_subscription.h.
Referenced by get_instance(), and is_published().
hrt_abstime MavlinkOrbSubscription::_last_pub_check {0} private
when we checked last
Definition at line 108 of file mavlink_orb_subscription.h.
Referenced by is_published().
bool MavlinkOrbSubscription::_published {false} private
topic was ever published
Definition at line 104 of file mavlink_orb_subscription.h.
Referenced by is_published().
bool MavlinkOrbSubscription::_subscribe_from_beginning {false} private
we need to subscribe from the beginning, e.g. for vehicle_command_acks
Definition at line 106 of file mavlink_orb_subscription.h.
Referenced by is_published(), and subscribe_from_beginning().
const orb_id_t MavlinkOrbSubscription::_topic private
topic metadata
Definition at line 99 of file mavlink_orb_subscription.h.
Referenced by get_topic(), is_published(), and update().
MavlinkOrbSubscription* MavlinkOrbSubscription::next {nullptr}
pointer to next subscription in list
Definition at line 51 of file mavlink_orb_subscription.h.
Referenced by Mavlink::task_main().
The documentation for this class was generated from the following files:
src/modules/mavlink/mavlink_orb_subscription.h
src/modules/mavlink/mavlink_orb_subscription.cpp