PX4 Firmware: uavcan_stm32::SystemClock Class Reference
uavcan_stm32::SystemClock Class Reference
Adapter for uavcan::ISystemClock.
#include <clock.hpp>
Public Member Functions
virtual uavcan::MonotonicTime getMonotonic () const
virtual uavcan::UtcTime getUtc () const
Static Public Member Functions
static SystemClock & instance ()
Calls clock::init() as needed.
Private Member Functions
SystemClock ()
virtual void adjustUtc (uavcan::UtcDuration adjustment)
Detailed Description
Adapter for uavcan::ISystemClock.
Definition at line 103 of file clock.hpp.
Constructor & Destructor Documentation
SystemClock()
uavcan_stm32::SystemClock::SystemClock () inline private
Definition at line 105 of file clock.hpp.
Member Function Documentation
adjustUtc()
virtual void uavcan_stm32::SystemClock::adjustUtc (uavcan::UtcDuration adjustment) inline private virtual
Definition at line 107 of file clock.hpp.
References uavcan_stm32::clock::adjustUtc().
getMonotonic()
virtual uavcan::MonotonicTime uavcan_stm32::SystemClock::getMonotonic () const inline virtual
Definition at line 110 of file clock.hpp.
References uavcan_stm32::clock::getMonotonic().
getUtc()
virtual uavcan::UtcTime uavcan_stm32::SystemClock::getUtc () const inline virtual
Definition at line 111 of file clock.hpp.
References uavcan_stm32::clock::getUtc(), and ll40ls::instance.
instance()
static SystemClock& uavcan_stm32::SystemClock::instance () static
Calls clock::init() as needed.
This function is thread safe.
Referenced by UavcanEsc::start().
The documentation for this class was generated from the following file:
src/drivers/uavcan/uavcan_drivers/stm32/driver/include/uavcan_stm32/clock.hpp