PX4 Firmware: uORB::SubscriptionNode Class Reference
uORB::SubscriptionNode Class Reference abstract
The subscription base class as a list node.
#include <Subscription.hpp>
Public Member Functions
SubscriptionNode (const struct orb_metadata *meta, unsigned interval=0, unsigned instance=0, List< SubscriptionNode * > *list=nullptr)
Constructor.
virtual ~SubscriptionNode () override=default
virtual bool update ()=0
This function is the callback for list traversal updates, a child class must implement it.
virtual bool forcedUpdate ()=0
Like update(), but does not check first if there is data available.
Public Member Functions inherited from uORB::SubscriptionBase
SubscriptionBase (const struct orb_metadata *meta, unsigned interval=0, unsigned instance=0)
Constructor.
virtual ~SubscriptionBase ()
SubscriptionBase (const SubscriptionBase &)=delete
SubscriptionBase & operator= (const SubscriptionBase &)=delete
SubscriptionBase (SubscriptionBase &&)=delete
SubscriptionBase & operator= (SubscriptionBase &&)=delete
bool updated ()
Check if there is a new update.
bool update (void *data)
Update the struct.
int getHandle () const
const orb_metadata * getMeta () const
unsigned getInstance () const
Public Member Functions inherited from ListNode< SubscriptionNode * >
ListNode ()
ListNode (const ListNode &)=delete
ListNode (ListNode &&)=delete
virtual ~ListNode ()=default
ListNode & operator= (const ListNode &)=delete
ListNode & operator= (ListNode &&)=delete
void setSibling (SubscriptionNode *sibling)
const SubscriptionNode * getSibling ()
Additional Inherited Members
Protected Attributes inherited from uORB::SubscriptionBase
const struct orb_metadata * _meta
unsigned _instance
int _handle
Protected Attributes inherited from ListNode< SubscriptionNode * >
SubscriptionNode * _sibling
Detailed Description
The subscription base class as a list node.
Definition at line 105 of file Subscription.hpp.
Constructor & Destructor Documentation
uORB::SubscriptionNode::SubscriptionNode (const struct orb_metadata * meta, unsigned interval = 0, unsigned instance = 0, List< SubscriptionNode * > * list = nullptr)
Constructor.
Parameters
meta The uORB metadata (usually from the ORB_ID() macro) for the topic.
interval The minimum interval in milliseconds between updates
instance The instance for multi sub.
list A pointer to a list of subscriptions that this should be appended to.
Definition at line 99 of file Subscription.cpp.
virtual uORB::SubscriptionNode::~SubscriptionNode () override virtual default
Member Function Documentation
virtual bool uORB::SubscriptionNode::forcedUpdate () pure virtual
Like update(), but does not check first if there is data available.
Implemented in uORB::Subscription< T >, uORB::Subscription< sensor_bias_s >, uORB::Subscription< vehicle_air_data_s >, uORB::Subscription< landing_target_pose_s >, uORB::Subscription< vehicle_attitude_s >, uORB::Subscription< vehicle_local_position_s >, uORB::Subscription< actuator_controls_s >, uORB::Subscription< airspeed_s >, uORB::Subscription< manual_control_setpoint_s >, uORB::Subscription< distance_sensor_s >, uORB::Subscription< parameter_update_s >, uORB::Subscription< home_position_s >, uORB::Subscription< vehicle_gps_position_s >, uORB::Subscription< position_setpoint_triplet_s >, uORB::Subscription< actuator_armed_s >, uORB::Subscription< att_pos_mocap_s >, uORB::Subscription< sensor_combined_s >, uORB::Subscription< optical_flow_s >, and uORB::Subscription< vehicle_land_detected_s >.
Referenced by SubscriptionArray::forcedUpdate().
virtual bool uORB::SubscriptionNode::update () pure virtual
This function is the callback for list traversal updates, a child class must implement it.
Implemented in uORB::Subscription< T >, uORB::Subscription< sensor_bias_s >, uORB::Subscription< vehicle_air_data_s >, uORB::Subscription< landing_target_pose_s >, uORB::Subscription< vehicle_attitude_s >, uORB::Subscription< vehicle_local_position_s >, uORB::Subscription< actuator_controls_s >, uORB::Subscription< airspeed_s >, uORB::Subscription< manual_control_setpoint_s >, uORB::Subscription< distance_sensor_s >, uORB::Subscription< parameter_update_s >, uORB::Subscription< home_position_s >, uORB::Subscription< vehicle_gps_position_s >, uORB::Subscription< position_setpoint_triplet_s >, uORB::Subscription< actuator_armed_s >, uORB::Subscription< att_pos_mocap_s >, uORB::Subscription< sensor_combined_s >, uORB::Subscription< optical_flow_s >, and uORB::Subscription< vehicle_land_detected_s >.
Referenced by SubscriptionArray::update(), and control::Block::updateSubscriptions().
The documentation for this class was generated from the following files:
src/modules/uORB/Subscription.hpp
src/modules/uORB/Subscription.cpp