PX4 Firmware: src/lib/mixer/mixer_load.h File Reference
mixer_load.h File Reference
#include <px4_config.h>
Macros
#define _SYSTEMLIB_MIXER_LOAD_H value
Functions
__BEGIN_DECLS __EXPORT int load_mixer_file (const char *fname, char *buf, unsigned maxlen)
Macro Definition Documentation
#define _SYSTEMLIB_MIXER_LOAD_H value
Definition at line 41 of file mixer_load.h.
Function Documentation
__BEGIN_DECLS __EXPORT int load_mixer_file (const char * fname, char * buf, unsigned maxlen)
Definition at line 48 of file mixer_load.c.
References f(), and warnx.
Referenced by linux_pwm_out::initialize_mixer(), df_bebop_bus_wrapper::initialize_mixers(), load(), and MixerTest::load_mixer().