PX4 Firmware: src/drivers/imu/fxas21002c/fxas21002c_main.cpp File Reference
fxas21002c_main.cpp File Reference
#include "FXAS21002C.hpp"
Namespaces
fxas21002c
Local functions in support of the shell command.
Functions
__EXPORT int fxas21002c_main (int argc, char *argv[])
void fxas21002c::start (bool external_bus, enum Rotation rotation)
Start the driver.
void fxas21002c::info ()
Print a little info about the driver.
void fxas21002c::regdump ()
dump registers from device
void fxas21002c::usage ()
Prints info about the driver argument usage.
void fxas21002c::test_error ()
trigger an error
Variables
FXAS21002C * fxas21002c::g_dev
Function Documentation
fxas21002c_main()
int fxas21002c_main (int argc, char * argv[])
Definition at line 161 of file fxas21002c_main.cpp.
References fxas21002c::info(), fxas21002c::regdump(), ROTATION_NONE, fxas21002c::start(), fxas21002c::test_error(), and fxas21002c::usage().