PX4 Firmware: RTCMParsing Class Reference
RTCMParsing Class Reference
#include <rtcm.h>
Public Member Functions
RTCMParsing ()
~RTCMParsing ()
void reset ()
reset the parsing state
bool addByte (uint8_t b)
add a byte to the message
uint8_t * message () const
uint16_t messageLength () const
Private Attributes
uint8_t * _buffer {nullptr}
uint16_t _buffer_len {}
uint16_t _pos {}
next position in buffer
uint16_t _message_length {}
message length without header & CRC (both 3 bytes)
Detailed Description
Definition at line 43 of file rtcm.h.
Constructor & Destructor Documentation
RTCMParsing()
RTCMParsing::RTCMParsing ()
Definition at line 37 of file rtcm.cpp.
References reset().
~RTCMParsing()
RTCMParsing::~RTCMParsing ()
Definition at line 42 of file rtcm.cpp.
References _buffer.
Member Function Documentation
addByte()
bool RTCMParsing::addByte (uint8_t b)
add a byte to the message
Parameters
b
Returns
true if message complete (use to get it)
Definition at line 60 of file rtcm.cpp.
References _buffer, _buffer_len, _message_length, and _pos.
Referenced by GPSDriverAshtech::parseChar(), GPSDriverSBF::parseChar(), and GPSDriverUBX::parseChar().
message()
uint8_t* RTCMParsing::message () const inline
Definition at line 61 of file rtcm.h.
References _buffer.
Referenced by GPSDriverAshtech::parseChar(), GPSDriverSBF::parseChar(), and GPSDriverUBX::parseChar().
messageLength()
uint16_t RTCMParsing::messageLength () const inline
Definition at line 62 of file rtcm.h.
References _pos.
Referenced by GPSDriverAshtech::parseChar(), GPSDriverSBF::parseChar(), and GPSDriverUBX::parseChar().
reset()
void RTCMParsing::reset ()
reset the parsing state
Definition at line 49 of file rtcm.cpp.
References _buffer, _buffer_len, _message_length, _pos, and RTCM_INITIAL_BUFFER_LENGTH.
Referenced by GPSDriverAshtech::decodeInit(), GPSDriverSBF::decodeInit(), GPSDriverUBX::decodeInit(), and RTCMParsing().
Member Data Documentation
_buffer
uint8_t* RTCMParsing::_buffer {nullptr} private
Definition at line 65 of file rtcm.h.
Referenced by addByte(), message(), reset(), and ~RTCMParsing().
_buffer_len
uint16_t RTCMParsing::_buffer_len {} private
Definition at line 66 of file rtcm.h.
Referenced by addByte(), and reset().
_message_length
uint16_t RTCMParsing::_message_length {} private
message length without header & CRC (both 3 bytes)
Definition at line 68 of file rtcm.h.
Referenced by addByte(), and reset().
_pos
uint16_t RTCMParsing::_pos {} private
next position in buffer
Definition at line 67 of file rtcm.h.
Referenced by addByte(), messageLength(), and reset().
The documentation for this class was generated from the following files:
src/drivers/gps/devices/src/rtcm.h
src/drivers/gps/devices/src/rtcm.cpp