PX4 Firmware: control::BlockStats< Type, M > Class Template Reference
control::BlockStats< Type, M > Class Template Reference
#include <BlockStats.hpp>
Public Member Functions
BlockStats (SuperBlock *parent, const char *name)
virtual ~BlockStats ()=default
void update (const matrix::Vector< Type, M > &u)
void reset ()
size_t getCount ()
matrix::Vector< Type, M > getMean ()
matrix::Vector< Type, M > getVar ()
matrix::Vector< Type, M > getStdDev ()
Public Member Functions inherited from control::Block
Block (SuperBlock *parent, const char *name)
virtual ~Block ()=default
Block (const Block &)=delete
Block & operator= (const Block &)=delete
Block (Block &&)=delete
Block & operator= (Block &&)=delete
void getName (char *name, size_t n)
virtual void updateParams ()
virtual void setDt (float dt)
float getDt ()
Public Member Functions inherited from ListNode< Block *>
void setSibling (Block * sibling)
const Block * getSibling () const
Private Attributes
matrix::Vector< Type, M > _sum
matrix::Vector< Type, M > _sumSq
size_t _count
Additional Inherited Members
Protected Member Functions inherited from control::Block
virtual void updateParamsSubclass ()
SuperBlock * getParent ()
List< BlockParamBase * > & getParams ()
Protected Attributes inherited from control::Block
const char * _name
SuperBlock * _parent
float _dt {0.0f}
List< BlockParamBase * > _params
Protected Attributes inherited from ListNode< Block *>
Block * _list_node_sibling
Detailed Description
template<class Type, size_t M>
class control::BlockStats< Type, M >
Definition at line 58 of file BlockStats.hpp.
Constructor & Destructor Documentation
BlockStats()
template<class Type, size_t M> control::BlockStats< Type, M >::BlockStats (SuperBlock * parent, const char * name) inline
Definition at line 63 of file BlockStats.hpp.
~BlockStats()
template<class Type, size_t M> virtual control::BlockStats< Type, M >::~BlockStats () virtual default
Member Function Documentation
getCount()
template<class Type, size_t M> size_t control::BlockStats< Type, M >::getCount () inline
Definition at line 84 of file BlockStats.hpp.
Referenced by BlockLocalPositionEstimator::baroInit(), BlockLocalPositionEstimator::flowInit(), BlockLocalPositionEstimator::gpsInit(), BlockLocalPositionEstimator::lidarInit(), BlockLocalPositionEstimator::mocapInit(), BlockLocalPositionEstimator::sonarInit(), and BlockLocalPositionEstimator::visionInit().
getMean()
template<class Type, size_t M> matrix::Vector<Type, M> control::BlockStats< Type, M >::getMean () inline
Definition at line 85 of file BlockStats.hpp.
Referenced by BlockLocalPositionEstimator::baroInit(), control::blockStatsTest(), blockStatsTest(), BlockLocalPositionEstimator::flowInit(), BlockLocalPositionEstimator::gpsInit(), BlockLocalPositionEstimator::lidarInit(), BlockLocalPositionEstimator::mocapInit(), BlockLocalPositionEstimator::sonarInit(), and BlockLocalPositionEstimator::visionInit().
getStdDev()
template<class Type, size_t M> matrix::Vector<Type, M> control::BlockStats< Type, M >::getStdDev () inline
Definition at line 90 of file BlockStats.hpp.
Referenced by BlockLocalPositionEstimator::baroInit(), blockStatsTest(), control::blockStatsTest(), BlockLocalPositionEstimator::flowInit(), BlockLocalPositionEstimator::lidarInit(), BlockLocalPositionEstimator::mocapInit(), BlockLocalPositionEstimator::sonarInit(), and BlockLocalPositionEstimator::visionInit().
getVar()
template<class Type, size_t M> matrix::Vector<Type, M> control::BlockStats< Type, M >::getVar () inline
Definition at line 86 of file BlockStats.hpp.
reset()
template<class Type, size_t M> void control::BlockStats< Type, M >::reset (void) inline
Definition at line 77 of file BlockStats.hpp.
Referenced by BlockLocalPositionEstimator::baroCheckTimeout(), BlockLocalPositionEstimator::baroInit(), blockStatsTest(), control::blockStatsTest(), BlockLocalPositionEstimator::flowCheckTimeout(), BlockLocalPositionEstimator::flowInit(), BlockLocalPositionEstimator::gpsCheckTimeout(), BlockLocalPositionEstimator::gpsInit(), BlockLocalPositionEstimator::lidarCheckTimeout(), BlockLocalPositionEstimator::lidarInit(), BlockLocalPositionEstimator::mocapCheckTimeout(), BlockLocalPositionEstimator::mocapInit(), BlockLocalPositionEstimator::sonarCheckTimeout(), BlockLocalPositionEstimator::sonarInit(), BlockLocalPositionEstimator::visionCheckTimeout(), and BlockLocalPositionEstimator::visionInit().
update()
template<class Type, size_t M> void control::BlockStats< Type, M >::update (const matrix::Vector< Type, M > & u) inline
Definition at line 71 of file BlockStats.hpp.
Referenced by BlockLocalPositionEstimator::baroMeasure(), control::blockStatsTest(), blockStatsTest(), BlockLocalPositionEstimator::flowMeasure(), BlockLocalPositionEstimator::gpsMeasure(), BlockLocalPositionEstimator::lidarMeasure(), BlockLocalPositionEstimator::mocapMeasure(), BlockLocalPositionEstimator::sonarMeasure(), and BlockLocalPositionEstimator::visionMeasure().
Member Data Documentation
_count
template<class Type, size_t M> size_t control::BlockStats< Type, M >::_count private
Definition at line 98 of file BlockStats.hpp.
_sum
template<class Type, size_t M> matrix::Vector<Type, M> control::BlockStats< Type, M >::_sum private
Definition at line 96 of file BlockStats.hpp.
_sumSq
template<class Type, size_t M> matrix::Vector<Type, M> control::BlockStats< Type, M >::_sumSq private
Definition at line 97 of file BlockStats.hpp.
The documentation for this class was generated from the following file:
src/lib/controllib/BlockStats.hpp