PX4 Firmware: src/drivers/imu/mpu9250/mpu9250_main.cpp File Reference
mpu9250_main.cpp File Reference
#include <px4_platform_common/px4_config.h>
#include <px4_platform_common/getopt.h>
#include "mpu9250.h"
Classes
struct mpu9250::mpu9250_bus_option
Namespaces
mpu9250
Enumerations
enum MPU9250_BUS {
MPU9250_BUS::ALL = 0, MPU9250_BUS::I2C_INTERNAL, MPU9250_BUS::I2C_EXTERNAL, MPU9250_BUS::SPI_INTERNAL,
MPU9250_BUS::SPI_INTERNAL2, MPU9250_BUS::SPI_EXTERNAL
}
Functions
static struct mpu9250_bus_option * mpu9250::find_bus (MPU9250_BUS busid)
static bool mpu9250::start_bus (mpu9250_bus_option &bus, enum Rotation rotation)
static int mpu9250::start (MPU9250_BUS busid, enum Rotation rotation)
static int mpu9250::stop (MPU9250_BUS busid)
static int mpu9250::status (MPU9250_BUS busid)
static int mpu9250::usage ()
int mpu9250_main (int argc, char *argv[])
Variables
struct mpu9250::mpu9250_bus_option mpu9250::bus_options []
Enumeration Type Documentation
MPU9250_BUS
enum MPU9250_BUS strong
Enumerator
ALL
I2C_INTERNAL
I2C_EXTERNAL
SPI_INTERNAL
SPI_INTERNAL2
SPI_EXTERNAL
Definition at line 39 of file mpu9250_main.cpp.
Function Documentation
mpu9250_main()
int mpu9250_main (int argc, char * argv[])
Definition at line 202 of file mpu9250_main.cpp.
References ALL, I2C_EXTERNAL, I2C_INTERNAL, ROTATION_NONE, SPI_EXTERNAL, SPI_INTERNAL, SPI_INTERNAL2, mpu9250::start(), mpu9250::status(), mpu9250::stop(), and mpu9250::usage().