PX4 Firmware: uavcan_kinetis::SystemClock Class Reference
uavcan_kinetis::SystemClock Class Reference
Adapter for uavcan::ISystemClock.
#include <clock.hpp>
Public Member Functions
virtual uavcan::MonotonicTime getMonotonic () const
virtual uavcan::UtcTime getUtc () const
Static Public Member Functions
static SystemClock & instance ()
Calls clock::init() as needed.
Private Member Functions
SystemClock ()
virtual void adjustUtc (uavcan::UtcDuration adjustment)
Detailed Description
Adapter for uavcan::ISystemClock.
Definition at line 105 of file clock.hpp.
Constructor & Destructor Documentation
SystemClock()
uavcan_kinetis::SystemClock::SystemClock () inline private
Definition at line 108 of file clock.hpp.
Member Function Documentation
adjustUtc()
virtual void uavcan_kinetis::SystemClock::adjustUtc (uavcan::UtcDuration adjustment) inline private virtual
Definition at line 112 of file clock.hpp.
References uavcan_kinetis::clock::adjustUtc().
getMonotonic()
virtual uavcan::MonotonicTime uavcan_kinetis::SystemClock::getMonotonic () const inline virtual
Definition at line 118 of file clock.hpp.
References uavcan_kinetis::clock::getMonotonic().
getUtc()
virtual uavcan::UtcTime uavcan_kinetis::SystemClock::getUtc () const inline virtual
Definition at line 122 of file clock.hpp.
References uavcan_kinetis::clock::getUtc(), and ll40ls::instance.
instance()
static SystemClock& uavcan_kinetis::SystemClock::instance () static
Calls clock::init() as needed.
This function is thread safe.
The documentation for this class was generated from the following file:
src/drivers/uavcan/uavcan_drivers/kinetis/driver/include/uavcan_kinetis/clock.hpp