PX4 Firmware: gpssim Namespace Reference
gpssim Namespace Reference
Local functions in support of the shell command.
Functions
void start (const char *uart_path, bool fake_gps, bool enable_sat_info, int fix_type, int num_sat, int noise_multiplier)
Start the driver.
void stop ()
Stop the driver.
void test ()
Perform some basic functional tests on the driver; make sure we can collect data from the sensor in polled and automatic modes.
void reset ()
Reset the driver.
void info ()
Print the status of the driver.
void usage (const char *reason)
Print the correct usage.
Variables
GPSSIM * g_dev = nullptr
Detailed Description
Local functions in support of the shell command.
Function Documentation
void gpssim::info ()
Print the status of the driver.
Print a little info about the driver.
Definition at line 484 of file gpssim.cpp.
References GPSSIM::print_info(), and PX4_ERR.
Referenced by gpssim_main().
void gpssim::reset ()
Reset the driver.
Reset the driver.
Definition at line 466 of file gpssim.cpp.
References GPSSIM_DEVICE_PATH, PX4_ERR, and SENSORIOCRESET.
Referenced by gpssim_main().
void gpssim::start (const char * uart_path, bool fake_gps, bool enable_sat_info, int fix_type, int num_sat, int noise_multiplier)
Start the driver.
Definition at line 406 of file gpssim.cpp.
References g_dev, GPSSIM::GPSSIM(), GPSSIM_DEVICE_PATH, GPSSIM::init(), OK, and PX4_ERR.
Referenced by gpssim_main().
void gpssim::stop ()
Stop the driver.
Stop the driver.
Definition at line 445 of file gpssim.cpp.
References g_dev.
Referenced by gpssim_main().
void gpssim::test ()
Perform some basic functional tests on the driver; make sure we can collect data from the sensor in polled and automatic modes.
Definition at line 457 of file gpssim.cpp.
References PX4_INFO.
Referenced by gpssim_main().
void gpssim::usage (const char * reason)
Print the correct usage.
Definition at line 495 of file gpssim.cpp.
References PRINT_MODULE_DESCRIPTION(), PRINT_MODULE_USAGE_ARG(), PRINT_MODULE_USAGE_COMMAND, PRINT_MODULE_USAGE_COMMAND_DESCR(), PRINT_MODULE_USAGE_NAME(), PRINT_MODULE_USAGE_PARAM_STRING(), PX4_INFO, and PX4_WARN.
Referenced by rpi_rc_in::RcInput::_measure(), linux_sbus::RcInput::_measure(), gpssim_main(), linux_sbus_main(), and rpi_rc_in_main().
Variable Documentation
GPSSIM* gpssim::g_dev = nullptr
Definition at line 392 of file gpssim.cpp.
Referenced by GPSSIM::GPSSIM(), gpssim_main(), start(), stop(), GPSSIM::task_main_trampoline(), and GPSSIM::~GPSSIM().