PX4 Firmware: device::CDev Class Reference
device::CDev Class Reference
Abstract class for any character device.
#include <CDev.hpp>
Public Member Functions
CDev (const char *name, const char *devname)
Constructor.
virtual ~CDev ()
virtual int init ()
Initialise the driver and make it ready for use.
virtual int open (file_t *filep)
Handle an open of the device.
virtual int close (file_t *filep)
Handle a close of the device.
virtual ssize_t read (file_t *filep, char *buffer, size_t buflen)
Perform a read from the device.
virtual ssize_t write (file_t *filep, const char *buffer, size_t buflen)
Perform a write to the device.
virtual off_t seek (file_t *filep, off_t offset, int whence)
Perform a logical seek operation on the device.
virtual int ioctl (file_t *filep, int cmd, unsigned long arg)
Perform an ioctl operation on the device.
virtual int poll (file_t *filep, px4_pollfd_struct_t *fds, bool setup)
Perform a poll setup/teardown operation.
Public Member Functions inherited from device::Device
virtual ~Device ()=default
Destructor.
virtual int read (unsigned address, void *data, unsigned count)
Read directly from the device.
virtual int write (unsigned address, void *data, unsigned count)
Write directly to the device.
virtual int ioctl (unsigned operation, unsigned &arg)
Perform a device-specific operation.
uint8_t get_device_bus ()
Return the bus ID the device is connected to.
DeviceBusType get_device_bus_type ()
Return the bus type the device is connected to.
uint8_t get_device_address ()
Return the bus address of the device.
void set_device_address (int address)
void set_device_type (uint8_t devtype)
Set the device type.
virtual bool external ()
Protected Member Functions
virtual pollevent_t poll_state (file_t *filep)
Check the current state of the device for poll events from the perspective of the file.
virtual void poll_notify (pollevent_t events)
Report new poll events.
virtual void poll_notify_one (px4_pollfd_struct_t *fds, pollevent_t events)
Internal implementation of poll_notify.
virtual int open_first (file_t *filep)
Notification of the first open.
virtual int close_last (file_t *filep)
Notification of the last close.
virtual int register_class_devname (const char *class_devname)
Register a class device name, automatically adding device class instance suffix if need be.
virtual int unregister_class_devname (const char *class_devname, unsigned class_instance)
Register a class device name, automatically adding device class instance suffix if need be.
const char * get_devname ()
Get the device name.
void lock ()
Take the driver lock.
void unlock ()
Release the driver lock.
Protected Member Functions inherited from device::Device
Device (const char *name)
Device (DeviceBusType bus_type, uint8_t bus, uint8_t address, uint8_t devtype=0)
Device (const Device &)=delete
Device & operator= (const Device &)=delete
Device (Device &&)=delete
Device & operator= (Device &&)=delete
Protected Attributes
px4_sem_t _lock
lock to protect access to all class members (also for derived classes)
bool _pub_blocked {false}
true if publishing should be blocked
Protected Attributes inherited from device::Device
union DeviceId _device_id
device identifier information
const char * _name
driver name
bool _debug_enabled {false}
if true, debug messages are printed
Static Protected Attributes
static const px4_file_operations_t fops = {}
Pointer to the default cdev file operations table; useful for registering clone devices etc.
Private Member Functions
int store_poll_waiter (px4_pollfd_struct_t *fds)
Store a pollwaiter in a slot where we can find it later.
int remove_poll_waiter (px4_pollfd_struct_t *fds)
Remove a poll waiter.
CDev (const CDev &)
CDev operator= (const CDev &)
Private Attributes
const char * _devname
device node name
bool _registered {false}
true if device name was registered
uint8_t _max_pollwaiters {0}
size of the _pollset array
uint16_t _open_count {0}
number of successful opens
px4_pollfd_struct_t ** _pollset {nullptr}
Additional Inherited Members
Public Types inherited from device::Device
enum DeviceBusType { DeviceBusType_UNKNOWN = 0, DeviceBusType_I2C = 1, DeviceBusType_SPI = 2, DeviceBusType_UAVCAN = 3 }
Device bus types for DEVID.
Detailed Description
Abstract class for any character device.
Definition at line 63 of file CDev.hpp.
Constructor & Destructor Documentation
CDev::CDev (const char * name, const char * devname)
Constructor.
Parameters
name Driver name
devname Device node name
Definition at line 56 of file CDev.cpp.
References _lock, DEVICE_DEBUG, px4_sem_init, and PX4_WARN.
CDev::~CDev () virtual
Definition at line 69 of file CDev.cpp.
References _devname, _lock, _pollset, _registered, DEVICE_DEBUG, px4_sem_destroy, and unregister_driver().
device::CDev::CDev (const CDev &) private
Member Function Documentation
int CDev::close (file_t * filep) virtual
Handle a close of the device.
This function is called for every close of the device. The default implementation maintains _open_count and returns OK as long as it is not zero.
Parameters
filep Pointer to the NuttX file structure.
Returns
OK if the close was successful, -errno otherwise.
Reimplemented in VCDevNode, and uORB::DeviceNode.
Definition at line 187 of file CDev.cpp.
References _open_count, close_last(), DEVICE_DEBUG, lock(), PX4_OK, and unlock().
Referenced by leddar_one::_fd_open(), hmc5883::calibrate(), device::cdev_close(), VCDevNode::close(), LidarLitePWM::collect(), TFMINI::init(), SF0X::init(), ulanding::Radar::init(), IridiumSBD::main_loop_helper(), PX4IO::print_debug(), pwmin_reset(), pwmin_test(), px4_close(), meas_airspeed_sim::reset(), fxos8701cq::reset(), adis16448::reset(), lsm303d::reset(), mpu6000::reset(), LidarLitePWM::reset_sensor(), UavcanNode::run(), PX4IO::set_update_rate(), leddar_one::start(), fxos8701cq::start(), adis16448::start(), lsm303d::start(), bmp280::start_bus(), mpl3115a2::start_bus(), lps25h::start_bus(), ms5611::start_bus(), hmc5883::start_bus(), mpu6000::start_bus(), IridiumSBD::stop(), ulanding::Radar::task_main(), hmc5883::temp_enable(), PX4FMU::test(), bmp280::test(), mpl3115a2::test(), lps25h::test(), ms5611::test(), fxos8701cq::test(), adis16448::test(), lsm303d::test(), mpu6000::test(), ToneAlarm::write(), and leddar_one::~leddar_one().
int CDev::close_last (file_t * filep) protected virtual
Notification of the last close.
This function is called when the device open count transitions from one to zero. The driver lock is held for the duration of the call.
The default implementation returns OK.
Parameters
filep Pointer to the NuttX file structure.
Returns
OK if the open should return OK, -errno otherwise.
Definition at line 213 of file CDev.cpp.
References DEVICE_DEBUG, and PX4_OK.
Referenced by close().
const char* device::CDev::get_devname () inline protected
Get the device name.
Returns
the file system string of the device handle
Definition at line 252 of file CDev.hpp.
Referenced by LidarLitePWM::get_dev_name(), MPL3115A2::~MPL3115A2(), and MS5611::~MS5611().
int CDev::init () virtual
Initialise the driver and make it ready for use.
Returns
OK if the driver initialized OK, negative errno otherwise;
Reimplemented from device::Device.
Reimplemented in LSM303D_mag, ADIS16448_mag, MPU6000_gyro, FXOS8701CQ_mag, ADIS16448_gyro, ToneAlarm, MPU9250, PWMIN, ToneAlarm, BATT_SMBUS, LPS25H, SyslinkMemory, SyslinkBridge, PX4FMU, MPU6000, HMC5883, PX4IO, MS5611, LIS3MDL, leddar_one, MPL3115A2, ulanding::Radar, TAP_ESC, MPU9250_mag, BMP280, LPS22HB, HC_SR04, SF0X, TFMINI, AirspeedSim, RGBLED_PWM, LED, LidarLitePWM, LED, UavcanBarometerBridge, UavcanMagnetometerBridge, ADIS16477_gyro, MPU9250_gyro, and BMI160_gyro.
Definition at line 125 of file CDev.cpp.
References _devname, _registered, DEVICE_DEBUG, fops, device::Device::init(), PX4_OK, and register_driver().
Referenced by UavcanNode::attachITxQueueInjector(), UavcanNode::cb_beginfirmware_update(), uORB::Manager::get_device_master(), UavcanMagnetometerBridge::init(), UavcanBarometerBridge::init(), and uORB::DeviceMaster::ioctl().
int CDev::ioctl (file_t * filep, int cmd, unsigned long arg) virtual
Perform an ioctl operation on the device.
The default implementation handles DIOC_GETPRIV, and otherwise returns -ENOTTY. Subclasses should call the default implementation for any command they do not handle themselves.
Parameters
filep Pointer to the NuttX file structure.
cmd The ioctl command value.
arg The ioctl argument value.
Returns
OK on success, or -errno otherwise.
Reimplemented in uORB::DeviceMaster, uORB::DeviceNode, TAP_ESC, HC_SR04, SF0X, TFMINI, PWMSim, AirspeedSim, LidarLitePWM, and LED.
Definition at line 241 of file CDev.cpp.
References device::Device::_device_id, _pub_blocked, DEVICE_DEBUG, device::Device::DeviceId::devid, and PX4_OK.
Referenced by device::cdev_ioctl(), and px4_ioctl().
void device::CDev::lock () inline protected
Take the driver lock.
Each driver instance has its own lock/semaphore.
Note that we must loop as the wait may be interrupted by a signal.
Careful: lock() calls cannot be nested!
Definition at line 263 of file CDev.hpp.
References px4_sem_wait.
Referenced by uORB::DeviceNode::add_internal_subscriber(), PX4FMU::capture_ioctl(), close(), uORB::DeviceMaster::getDeviceNode(), PX4FMU::gpio_ioctl(), RestartRequestHandler::handleRestartRequest(), PWMSim::ioctl(), UavcanEsc::ioctl(), uORB::DeviceNode::ioctl(), UavcanNode::ioctl(), UavcanMagnetometerBridge::mag_sub_cb(), uORB::DeviceNode::open(), open(), uORB::DeviceNode::print_statistics(), uORB::DeviceMaster::printStatistics(), PX4FMU::pwm_ioctl(), UavcanMagnetometerBridge::read(), Mavlink2Dev::read(), RtpsDev::read(), uORB::DeviceNode::remove_internal_subscriber(), uORB::DeviceMaster::showTop(), PX4IO::task_main(), uORB::DeviceNode::write(), Mavlink2Dev::write(), and RtpsDev::write().
int CDev::open (file_t * filep) virtual
Handle an open of the device.
This function is called for every open of the device. The default implementation maintains _open_count and always returns OK.
Parameters
filep Pointer to the NuttX file structure.
Returns
OK if the open is allowed, -errno otherwise.
Reimplemented in VCDevNode, and uORB::DeviceNode.
Definition at line 155 of file CDev.cpp.
References _open_count, DEVICE_DEBUG, lock(), open_first(), PX4_OK, and unlock().
Referenced by leddar_one::_fd_open(), hmc5883::calibrate(), device::cdev_open(), LidarLitePWM::collect(), TFMINI::cycle(), SF0X::cycle(), RestartRequestHandler::handleRestartRequest(), TFMINI::init(), ulanding::Radar::init(), VCDevNode::open(), IridiumSBD::open_uart(), PX4IO::print_debug(), px4_open(), meas_airspeed_sim::reset(), bmp280::reset(), hc_sr04::reset(), mpl3115a2::reset(), sf0x::reset(), lps25h::reset(), ms5611::reset(), hmc5883::reset(), fxos8701cq::reset(), adis16448::reset(), lsm303d::reset(), mpu6000::reset(), LidarLitePWM::reset_sensor(), UavcanEsc::run(), UavcanNode::run(), PX4IO::set_update_rate(), SF0X::SF0X(), hc_sr04::start(), sf0x::start(), fxos8701cq::start(), adis16448::start(), lsm303d::start(), bmp280::start_bus(), mpl3115a2::start_bus(), lps25h::start_bus(), ms5611::start_bus(), hmc5883::start_bus(), mpu6000::start_bus(), ulanding::Radar::task_main(), hmc5883::temp_enable(), PX4FMU::test(), bmp280::test(), hc_sr04::test(), mpl3115a2::test(), sf0x::test(), lps25h::test(), ms5611::test(), hmc5883::test(), fxos8701cq::test(), adis16448::test(), lsm303d::test(), mpu6000::test(), and ToneAlarm::write().
int CDev::open_first (file_t * filep) protected virtual
Notification of the first open.
This function is called when the device open count transitions from zero to one. The driver lock is held for the duration of the call.
The default implementation returns OK.
Parameters
filep Pointer to the NuttX file structure.
Returns
OK if the open should proceed, -errno otherwise.
Definition at line 180 of file CDev.cpp.
References DEVICE_DEBUG, and PX4_OK.
Referenced by open().
CDev device::CDev::operator= (const CDev &) private
int CDev::poll (file_t * filep, px4_pollfd_struct_t * fds, bool setup) virtual
Perform a poll setup/teardown operation.
This is handled internally and should not normally be overridden.
Parameters
filep Pointer to the internal file structure.
fds Poll descriptor being waited on.
setup True if this is establishing a request, false if it is being torn down.
Returns
OK on success, or -errno otherwise.
Definition at line 275 of file CDev.cpp.
References _max_pollwaiters, _pollset, ATOMIC_ENTER, ATOMIC_LEAVE, DEVICE_POLL_DEBUG, poll_state(), PX4_OK, px4_sem_post, remove_poll_waiter(), and store_poll_waiter().
Referenced by LIS3MDL::calibrate(), HMC5883::calibrate(), device::cdev_poll(), RestartRequestHandler::handleRestartRequest(), DevCommon::poll_state(), PX4IO::print_debug(), px4_poll(), IridiumSBD::read_at(), UavcanEsc::run(), UavcanNode::run(), PX4IO::set_update_rate(), uORB::DeviceMaster::showTop(), ulanding::Radar::task_main(), PX4IO::task_main(), PX4FMU::test(), meas_airspeed_sim::test(), bmp280::test(), hc_sr04::test(), mpl3115a2::test(), sf0x::test(), lps25h::test(), ms5611::test(), and hmc5883::test().
void CDev::poll_notify (pollevent_t events) protected virtual
Report new poll events.
This function should be called anytime the state of the device changes in a fashion that might be interesting to a poll waiter.
Parameters
events The new event(s) being announced.
Definition at line 392 of file CDev.cpp.
References _max_pollwaiters, _pollset, ATOMIC_ENTER, ATOMIC_LEAVE, DEVICE_POLL_DEBUG, and poll_notify_one().
Referenced by MPU9250_mag::_measure(), MEASAirspeedSim::collect(), BMP280::collect(), TFMINI::collect(), SF0X::collect(), HC_SR04::collect(), MPL3115A2::collect(), LIS3MDL::collect(), MS5611::collect(), LPS25H::collect(), HMC5883::collect(), LidarLitePWM::measure(), MPU6000::measure(), MPU9250::measure(), BMI160_gyro::parent_poll_notify(), MPU9250_gyro::parent_poll_notify(), ADIS16448_gyro::parent_poll_notify(), FXOS8701CQ_mag::parent_poll_notify(), MPU6000_gyro::parent_poll_notify(), ADIS16448_mag::parent_poll_notify(), LSM303D_mag::parent_poll_notify(), SyslinkBridge::pipe_message(), uORB::DeviceNode::update_deferred(), device::VFile::write(), and uORB::DeviceNode::write().
void CDev::poll_notify_one (px4_pollfd_struct_t * fds, pollevent_t events) protected virtual
Internal implementation of poll_notify.
Parameters
fds A poll waiter to notify.
events The event(s) to send to the waiter.
Reimplemented in uORB::DeviceNode.
Definition at line 409 of file CDev.cpp.
References DEVICE_POLL_DEBUG, and px4_sem_post.
Referenced by poll_notify().
pollevent_t CDev::poll_state (file_t * filep) protected virtual
Check the current state of the device for poll events from the perspective of the file.
This function is called by the default poll() implementation when a poll is set up to determine whether the poll should return immediately.
The default implementation returns no events.
Parameters
filep The file that's interested.
Returns
The current set of poll events.
Reimplemented in uORB::DeviceNode.
Definition at line 424 of file CDev.cpp.
References DEVICE_POLL_DEBUG.
Referenced by poll().
ssize_t CDev::read (file_t * filep, char * buffer, size_t buflen) virtual
Perform a read from the device.
The default implementation returns -ENOSYS.
Parameters
filep Pointer to the NuttX file structure.
buffer Pointer to the buffer into which data should be placed.
buflen The number of bytes to be read.
Returns
The number of bytes read or -errno otherwise.
Reimplemented in VCDevNode, HC_SR04, SF0X, TFMINI, uORB::DeviceNode, AirspeedSim, and LidarLitePWM.
Definition at line 220 of file CDev.cpp.
References DEVICE_DEBUG.
Referenced by device::cdev_read(), PX4IO::print_debug(), px4_read(), PX4IO::set_update_rate(), uORB::DeviceMaster::showTop(), ulanding::Radar::task_main(), PX4FMU::test(), and Mavlink2Dev::~Mavlink2Dev().
int CDev::register_class_devname (const char * class_devname) protected virtual
Register a class device name, automatically adding device class instance suffix if need be.
Parameters
class_devname Device class name
Returns
class_instamce Class instance created, or -errno on failure
Definition at line 85 of file CDev.cpp.
References DEVICE_DEBUG, fops, name, OK, and register_driver().
Referenced by BMI160_gyro::init(), MPU9250_gyro::init(), ADIS16477_gyro::init(), LidarLitePWM::init(), AirspeedSim::init(), TFMINI::init(), SF0X::init(), LPS22HB::init(), HC_SR04::init(), BMP280::init(), MPU9250_mag::init(), ulanding::Radar::init(), MPL3115A2::init(), LIS3MDL::init(), MS5611::init(), HMC5883::init(), MPU6000::init(), PX4FMU::init(), LPS25H::init(), MPU9250::init(), ADIS16448_gyro::init(), FXOS8701CQ_mag::init(), MPU6000_gyro::init(), ADIS16448_mag::init(), and LSM303D_mag::init().
int CDev::remove_poll_waiter (px4_pollfd_struct_t * fds) inline private
Remove a poll waiter.
Returns
OK, or -errno on error.
Definition at line 453 of file CDev.cpp.
References _max_pollwaiters, _pollset, DEVICE_POLL_DEBUG, and PX4_OK.
Referenced by poll().
off_t CDev::seek (file_t * filep, off_t offset, int whence) virtual
Perform a logical seek operation on the device.
The default implementation returns -ENOSYS.
Parameters
filep Pointer to the NuttX file structure.
offset The new file position relative to whence.
whence SEEK_OFS, SEEK_CUR or SEEK_END.
Returns
The previous offset, or -errno otherwise.
Definition at line 234 of file CDev.cpp.
References DEVICE_DEBUG.
Referenced by device::cdev_seek().
int CDev::store_poll_waiter (px4_pollfd_struct_t * fds) inline private
Store a pollwaiter in a slot where we can find it later.
Must be called with the driver locked.
Returns
OK, or -errno on error.
Definition at line 432 of file CDev.cpp.
References _max_pollwaiters, _pollset, DEVICE_POLL_DEBUG, and PX4_OK.
Referenced by poll().
void device::CDev::unlock () inline protected
Release the driver lock.
Definition at line 271 of file CDev.hpp.
References px4_sem_post.
Referenced by uORB::DeviceNode::add_internal_subscriber(), PX4FMU::capture_ioctl(), close(), uORB::DeviceMaster::getDeviceNode(), PX4FMU::gpio_ioctl(), RestartRequestHandler::handleRestartRequest(), PWMSim::ioctl(), UavcanEsc::ioctl(), uORB::DeviceNode::ioctl(), UavcanNode::ioctl(), UavcanMagnetometerBridge::mag_sub_cb(), uORB::DeviceNode::open(), open(), uORB::DeviceNode::print_statistics(), uORB::DeviceMaster::printStatistics(), PX4FMU::pwm_ioctl(), UavcanMagnetometerBridge::read(), Mavlink2Dev::read(), RtpsDev::read(), uORB::DeviceNode::remove_internal_subscriber(), uORB::DeviceMaster::showTop(), PX4IO::task_main(), uORB::DeviceNode::write(), Mavlink2Dev::write(), and RtpsDev::write().
int CDev::unregister_class_devname (const char * class_devname, unsigned class_instance) protected virtual
Register a class device name, automatically adding device class instance suffix if need be.
Parameters
class_devname Device class name
class_instance Device class instance from register_class_devname()
Returns
OK on success, -errno otherwise
Definition at line 116 of file CDev.cpp.
References DEVICE_DEBUG, name, and unregister_driver().
Referenced by ADIS16448_gyro::~ADIS16448_gyro(), ADIS16448_mag::~ADIS16448_mag(), ADIS16477_gyro::~ADIS16477_gyro(), AirspeedSim::~AirspeedSim(), BMI160_gyro::~BMI160_gyro(), BMP280::~BMP280(), FXOS8701CQ_mag::~FXOS8701CQ_mag(), HC_SR04::~HC_SR04(), HMC5883::~HMC5883(), LidarLitePWM::~LidarLitePWM(), LIS3MDL::~LIS3MDL(), LPS22HB::~LPS22HB(), LPS25H::~LPS25H(), LSM303D_mag::~LSM303D_mag(), MPL3115A2::~MPL3115A2(), MPU6000::~MPU6000(), MPU6000_gyro::~MPU6000_gyro(), MPU9250::~MPU9250(), MPU9250_gyro::~MPU9250_gyro(), MPU9250_mag::~MPU9250_mag(), MS5611::~MS5611(), PX4FMU::~PX4FMU(), ulanding::Radar::~Radar(), SF0X::~SF0X(), and TFMINI::~TFMINI().
ssize_t CDev::write (file_t * filep, const char * buffer, size_t buflen) virtual
Perform a write to the device.
The default implementation returns -ENOSYS.
Parameters
filep Pointer to the NuttX file structure.
buffer Pointer to the buffer from which data should be read.
buflen The number of bytes to be written.
Returns
The number of bytes written or -errno otherwise.
Reimplemented in VCDevNode, uORB::DeviceNode, and device::VFile.
Definition at line 227 of file CDev.cpp.
References DEVICE_DEBUG.
Referenced by leddar_one::_request(), device::cdev_write(), SF0X::measure(), px4_write(), and Mavlink2Dev::~Mavlink2Dev().
Member Data Documentation
const char* device::CDev::_devname private
device node name
Definition at line 281 of file CDev.hpp.
Referenced by init(), and ~CDev().
px4_sem_t device::CDev::_lock protected
lock to protect access to all class members (also for derived classes)
Definition at line 276 of file CDev.hpp.
Referenced by CDev(), uORB::DeviceMaster::ioctl(), and ~CDev().
uint8_t device::CDev::_max_pollwaiters {0} private
size of the _pollset array
Definition at line 284 of file CDev.hpp.
Referenced by poll(), poll_notify(), remove_poll_waiter(), and store_poll_waiter().
uint16_t device::CDev::_open_count {0} private
number of successful opens
Definition at line 285 of file CDev.hpp.
Referenced by close(), and open().
px4_pollfd_struct_t** device::CDev::_pollset {nullptr} private
Definition at line 287 of file CDev.hpp.
Referenced by poll(), poll_notify(), remove_poll_waiter(), store_poll_waiter(), and ~CDev().
bool device::CDev::_pub_blocked {false} protected
true if publishing should be blocked
Definition at line 278 of file CDev.hpp.
Referenced by MPU9250_mag::_measure(), MEASAirspeedSim::collect(), BMP280::collect(), LPS22HB::collect(), MPL3115A2::collect(), LIS3MDL::collect(), MS5611::collect(), LPS25H::collect(), HMC5883::collect(), ioctl(), MPU6000::measure(), and MPU9250::measure().
bool device::CDev::_registered {false} private
true if device name was registered
Definition at line 282 of file CDev.hpp.
Referenced by init(), and ~CDev().
const device::px4_file_operations_t CDev::fops = {} static protected
Pointer to the default cdev file operations table; useful for registering clone devices etc.
Definition at line 168 of file CDev.hpp.
Referenced by init(), PX4IO::init(), and register_class_devname().
The documentation for this class was generated from the following files:
src/lib/drivers/device/CDev.hpp
src/lib/drivers/device/CDev.cpp
src/lib/drivers/device/posix/cdev_platform.cpp