PX4 Firmware: src/drivers/imu/lsm303d/lsm303d_main.cpp File Reference
lsm303d_main.cpp File Reference
Driver for the ST LSM303D MEMS accelerometer / magnetometer connected via SPI.
#include "LSM303D.hpp"
#include <px4_platform_common/getopt.h>
Namespaces
lsm303d
Local functions in support of the shell command.
Functions
void lsm303d::start (bool external_bus, enum Rotation rotation, unsigned range)
Start the driver.
void lsm303d::info ()
Print a little info about the driver.
void lsm303d::usage ()
Prints info about the driver argument usage.
int lsm303d_main (int argc, char *argv[])
Variables
LSM303D * lsm303d::g_dev
Detailed Description
Driver for the ST LSM303D MEMS accelerometer / magnetometer connected via SPI.
Definition in file lsm303d_main.cpp.
Function Documentation
lsm303d_main()
int lsm303d_main (int argc, char * argv[])
Definition at line 128 of file lsm303d_main.cpp.
References errx, lsm303d::info(), ROTATION_NONE, lsm303d::start(), and lsm303d::usage().