PX4 Firmware: src/drivers/boards/av-x-v1/spi.c File Reference
spi.c File Reference
#include <px4_config.h>
#include <px4_log.h>
#include <stdint.h>
#include <stdbool.h>
#include <debug.h>
#include <unistd.h>
#include <nuttx/spi/spi.h>
#include <arch/board/board.h>
#include <systemlib/px4_macros.h>
#include <up_arch.h>
#include <chip.h>
#include <stm32_gpio.h>
#include "board_config.h"
#include <systemlib/err.h>
Functions
__EXPORT void stm32_spiinitialize (void)
__EXPORT int stm32_spi_bus_initialize (void)
__EXPORT void stm32_spi1select (FAR struct spi_dev_s *dev, uint32_t devid, bool selected)
__EXPORT uint8_t stm32_spi1status (FAR struct spi_dev_s *dev, uint32_t devid)
__EXPORT void stm32_spi2select (FAR struct spi_dev_s *dev, uint32_t devid, bool selected)
__EXPORT uint8_t stm32_spi2status (FAR struct spi_dev_s *dev, uint32_t devid)
__EXPORT void stm32_spi4select (FAR struct spi_dev_s *dev, uint32_t devid, bool selected)
__EXPORT uint8_t stm32_spi4status (FAR struct spi_dev_s *dev, uint32_t devid)
__EXPORT void stm32_spi5select (FAR struct spi_dev_s *dev, uint32_t devid, bool selected)
__EXPORT uint8_t stm32_spi5status (FAR struct spi_dev_s *dev, uint32_t devid)
__EXPORT void board_spi_reset (int ms)
Variables
static const uint32_t spi1selects_gpio [] = PX4_SENSOR1_BUS_CS_GPIO
static const uint32_t spi2selects_gpio [] = PX4_SENSOR2_BUS_CS_GPIO
static const uint32_t spi4selects_gpio [] = PX4_SENSOR4_BUS_CS_GPIO
static const uint32_t spi5selects_gpio [] = PX4_SENSOR5_BUS_CS_GPIO
static struct spi_dev_s * spi_sensor1
static struct spi_dev_s * spi_sensor2
static struct spi_dev_s * spi_sensor4
static struct spi_dev_s * spi_sensor5
Function Documentation
__EXPORT void board_spi_reset (int ms)
Definition at line 325 of file spi.c.
References _PIN_OFF, arraySize, GPIO_SPI1_MISO_OFF, GPIO_SPI1_MOSI_OFF, GPIO_SPI1_SCK_OFF, GPIO_SPI2_MISO_OFF, GPIO_SPI2_MOSI_OFF, GPIO_SPI2_SCK_OFF, GPIO_SPI4_MISO_OFF, GPIO_SPI4_MOSI_OFF, GPIO_SPI4_SCK_OFF, GPIO_SPI5_MISO_OFF, GPIO_SPI5_MOSI_OFF, GPIO_SPI5_SCK_OFF, PX4_INFO, spi1selects_gpio, spi2selects_gpio, spi4selects_gpio, spi5selects_gpio, and usleep().
__EXPORT void stm32_spi1select (FAR struct spi_dev_s * dev, uint32_t devid, bool selected)
Definition at line 194 of file spi.c.
References arraySize, PX4_SPI_BUS_ID, PX4_SPI_BUS_SENSOR1, PX4_SPI_DEV_ID, and spi1selects_gpio.
__EXPORT uint8_t stm32_spi1status (FAR struct spi_dev_s * dev, uint32_t devid)
Definition at line 214 of file spi.c.
__EXPORT void stm32_spi2select (FAR struct spi_dev_s * dev, uint32_t devid, bool selected)
Definition at line 228 of file spi.c.
References arraySize, PX4_SPI_BUS_ID, PX4_SPI_BUS_SENSOR2, PX4_SPI_DEV_ID, and spi2selects_gpio.
Referenced by stm32_spi1status(), and stm32_spiinitialize().
__EXPORT uint8_t stm32_spi2status (FAR struct spi_dev_s * dev, uint32_t devid)
Definition at line 249 of file spi.c.
Referenced by stm32_spi1status(), and stm32_spiinitialize().
__EXPORT void stm32_spi4select (FAR struct spi_dev_s * dev, uint32_t devid, bool selected)
Definition at line 263 of file spi.c.
References arraySize, PX4_SPI_BUS_ID, PX4_SPI_BUS_SENSOR4, PX4_SPI_DEV_ID, and spi4selects_gpio.
Referenced by stm32_spi3status(), and stm32_spiinitialize().
__EXPORT uint8_t stm32_spi4status (FAR struct spi_dev_s * dev, uint32_t devid)
Definition at line 280 of file spi.c.
Referenced by stm32_spi3status(), and stm32_spiinitialize().
__EXPORT void stm32_spi5select (FAR struct spi_dev_s * dev, uint32_t devid, bool selected)
Definition at line 293 of file spi.c.
References arraySize, PX4_SPI_BUS_ID, PX4_SPI_BUS_SENSOR5, PX4_SPI_DEV_ID, and spi5selects_gpio.
Referenced by stm32_spi1status(), and stm32_spi4status().
__EXPORT uint8_t stm32_spi5status (FAR struct spi_dev_s * dev, uint32_t devid)
Definition at line 311 of file spi.c.
Referenced by stm32_spi1status(), and stm32_spi4status().
__EXPORT int stm32_spi_bus_initialize (void)
Definition at line 109 of file spi.c.
__EXPORT void stm32_spiinitialize (void)
Definition at line 89 of file spi.c.
References arraySize, board_gpio_init(), spi1selects_gpio, spi2selects_gpio, spi4selects_gpio, and spi5selects_gpio.
Variable Documentation
const uint32_t spi1selects_gpio[] = PX4_SENSOR1_BUS_CS_GPIO static
Definition at line 71 of file spi.c.
Referenced by board_spi_reset(), stm32_spi1select(), and stm32_spiinitialize().
const uint32_t spi2selects_gpio[] = PX4_SENSOR2_BUS_CS_GPIO static
Definition at line 72 of file spi.c.
Referenced by board_spi_reset(), stm32_spi2select(), and stm32_spiinitialize().
const uint32_t spi4selects_gpio[] = PX4_SENSOR4_BUS_CS_GPIO static
Definition at line 73 of file spi.c.
Referenced by board_spi_reset(), stm32_spi4select(), and stm32_spiinitialize().
const uint32_t spi5selects_gpio[] = PX4_SENSOR5_BUS_CS_GPIO static
Definition at line 74 of file spi.c.
Referenced by board_spi_reset(), stm32_spi4status(), stm32_spi5select(), and stm32_spiinitialize().
struct spi_dev_s* spi_sensor1 static
Definition at line 104 of file spi.c.
Referenced by stm32_spi_bus_initialize().
struct spi_dev_s* spi_sensor2 static
Definition at line 105 of file spi.c.
Referenced by stm32_spi_bus_initialize().
struct spi_dev_s* spi_sensor4 static
Definition at line 106 of file spi.c.
Referenced by stm32_spi_bus_initialize().
struct spi_dev_s* spi_sensor5 static
Definition at line 107 of file spi.c.
Referenced by stm32_spi_bus_initialize().