PX4 Firmware: landing_target_estimator::KalmanFilter Class Reference
landing_target_estimator::KalmanFilter Class Reference
#include <KalmanFilter.h>
Public Member Functions
KalmanFilter ()
Default constructor, state not initialized.
KalmanFilter (matrix::Vector< float, 2 > &initial, matrix::Matrix< float, 2, 2 > &covInit)
Constructor, initialize state.
virtual ~KalmanFilter ()
Default desctructor.
void init (matrix::Vector< float, 2 > &initial, matrix::Matrix< float, 2, 2 > &covInit)
Initialize filter state.
void init (float initial0, float initial1, float covInit00, float covInit11)
Initialize filter state, only specifying diagonal covariance elements.
void predict (float dt, float acc, float acc_unc)
Predict the state with an external acceleration estimate.
bool update (float meas, float measUnc)
Update the state estimate with a measurement.
void getState (matrix::Vector< float, 2 > &state)
Get the current filter state.
void getState (float &state0, float &state1)
Get the current filter state.
void getCovariance (matrix::Matrix< float, 2, 2 > &covariance)
Get state covariance.
void getCovariance (float &cov00, float &cov11)
Get state variances (diagonal elements)
void getInnovations (float &innov, float &innovCov)
Get measurement innovation and covariance of last update call.
Private Attributes
matrix::Vector< float, 2 > _x
matrix::Matrix< float, 2, 2 > _covariance
float _residual
float _innovCov
Detailed Description
Definition at line 58 of file KalmanFilter.h.
Constructor & Destructor Documentation
landing_target_estimator::KalmanFilter::KalmanFilter () inline
Default constructor, state not initialized.
Definition at line 64 of file KalmanFilter.h.
landing_target_estimator::KalmanFilter::KalmanFilter (matrix::Vector< float, 2 > & initial, matrix::Matrix< float, 2, 2 > & covInit)
Constructor, initialize state.
Definition at line 46 of file KalmanFilter.cpp.
References init().
virtual landing_target_estimator::KalmanFilter::~KalmanFilter () inline virtual
Default desctructor.
Definition at line 74 of file KalmanFilter.h.
References dt, getCovariance(), getInnovations(), getState(), init(), predict(), state, and update().
Member Function Documentation
void landing_target_estimator::KalmanFilter::getCovariance (matrix::Matrix< float, 2, 2 > & covariance)
Get state covariance.
Parameters
covariance Covariance of the state
Definition at line 136 of file KalmanFilter.cpp.
References _covariance.
Referenced by landing_target_estimator::LandingTargetEstimator::update(), and ~KalmanFilter().
void landing_target_estimator::KalmanFilter::getCovariance (float & cov00, float & cov11)
Get state variances (diagonal elements)
Parameters
cov00 Variance of first state
cov11 Variance of second state
Definition at line 141 of file KalmanFilter.cpp.
References _covariance.
void landing_target_estimator::KalmanFilter::getInnovations (float & innov, float & innovCov)
Get measurement innovation and covariance of last update call.
Parameters
innov Measurement innovation
innovCov Measurement innovation covariance
Definition at line 147 of file KalmanFilter.cpp.
References _innovCov, and _residual.
Referenced by landing_target_estimator::LandingTargetEstimator::update(), and ~KalmanFilter().
void landing_target_estimator::KalmanFilter::getState (matrix::Vector< float, 2 > & state)
Get the current filter state.
Parameters
x1 State
Definition at line 125 of file KalmanFilter.cpp.
References _x.
Referenced by landing_target_estimator::LandingTargetEstimator::update(), and ~KalmanFilter().
void landing_target_estimator::KalmanFilter::getState (float & state0, float & state1)
Get the current filter state.
Parameters
state0 First state
state1 Second state
Definition at line 130 of file KalmanFilter.cpp.
References _x.
void landing_target_estimator::KalmanFilter::init (matrix::Vector< float, 2 > & initial, matrix::Matrix< float, 2, 2 > & covInit)
Initialize filter state.
Parameters
initial initial state
covInit initial covariance
Definition at line 51 of file KalmanFilter.cpp.
References _covariance, and _x.
Referenced by init(), KalmanFilter(), landing_target_estimator::LandingTargetEstimator::update(), and ~KalmanFilter().
void landing_target_estimator::KalmanFilter::init (float initial0, float initial1, float covInit00, float covInit11)
Initialize filter state, only specifying diagonal covariance elements.
Parameters
initial0 first initial state
initial1 second initial state
covInit00 initial variance of first state
covinit11 initial variance of second state
Definition at line 57 of file KalmanFilter.cpp.
References init().
void landing_target_estimator::KalmanFilter::predict (float dt, float acc, float acc_unc)
Predict the state with an external acceleration estimate.
Parameters
dt Time delta in seconds since last state change
acc Acceleration estimate
acc_unc Variance of acceleration estimate
Definition at line 69 of file KalmanFilter.cpp.
References _covariance, _x, dt, and matrix::Matrix< Type, M, N >::transpose().
Referenced by landing_target_estimator::LandingTargetEstimator::update(), and ~KalmanFilter().
bool landing_target_estimator::KalmanFilter::update (float meas, float measUnc)
Update the state estimate with a measurement.
Parameters
meas state measeasurement
measUnc measurement uncertainty
Returns
update success (measurement not rejected)
Definition at line 88 of file KalmanFilter.cpp.
References _covariance, _innovCov, _residual, _x, f(), and matrix::Matrix< Type, M, N >::identity().
Referenced by landing_target_estimator::LandingTargetEstimator::update(), and ~KalmanFilter().
Member Data Documentation
matrix::Matrix<float, 2, 2> landing_target_estimator::KalmanFilter::_covariance private
Definition at line 144 of file KalmanFilter.h.
Referenced by getCovariance(), init(), predict(), and update().
float landing_target_estimator::KalmanFilter::_innovCov private
Definition at line 148 of file KalmanFilter.h.
Referenced by getInnovations(), and update().
float landing_target_estimator::KalmanFilter::_residual private
Definition at line 146 of file KalmanFilter.h.
Referenced by getInnovations(), and update().
matrix::Vector<float, 2> landing_target_estimator::KalmanFilter::_x private
Definition at line 142 of file KalmanFilter.h.
Referenced by getState(), init(), predict(), and update().
The documentation for this class was generated from the following files:
src/modules/landing_target_estimator/KalmanFilter.h
src/modules/landing_target_estimator/KalmanFilter.cpp