PX4 Firmware: src/drivers/adc/adc.cpp File Reference
adc.cpp File Reference
Driver for an ADC.
#include <stdint.h>
#include <drivers/drv_adc.h>
#include <drivers/drv_hrt.h>
#include <lib/cdev/CDev.hpp>
#include <lib/perf/perf_counter.h>
#include <px4_arch/adc.h>
#include <px4_platform_common/px4_config.h>
#include <px4_platform_common/log.h>
#include <px4_platform_common/px4_work_queue/ScheduledWorkItem.hpp>
#include <uORB/Publication.hpp>
#include <uORB/topics/adc_report.h>
#include <uORB/topics/system_power.h>
Classes
class ADC
Macros
#define ADC_TOTAL_CHANNELS 32
Functions
__EXPORT int adc_main (int argc, char *argv[])
Detailed Description
Driver for an ADC.
Definition in file adc.cpp.
Macro Definition Documentation
ADC_TOTAL_CHANNELS
#define ADC_TOTAL_CHANNELS 32
Definition at line 60 of file adc.cpp.
Referenced by ADC::ADC(), and ADC::sample().
Function Documentation
adc_main()
int adc_main (int argc, char * argv[])
Definition at line 385 of file adc.cpp.
References ADC::ADC(), OK, and lps25h::test().
Referenced by ADC::sample().