PX4 Firmware: sf0x Namespace Reference
sf0x Namespace Reference
Local functions in support of the shell command.
Functions
void start (const char *port, uint8_t rotation)
Start the driver.
void stop ()
Stop the driver.
void test ()
Perform some basic functional tests on the driver; make sure we can collect data from the sensor in polled and automatic modes.
void reset ()
Reset the driver.
void info ()
Print a little info about the driver.
Variables
SF0X * g_dev
Detailed Description
Local functions in support of the shell command.
Function Documentation
void sf0x::info ()
Print a little info about the driver.
Print a little info about the driver.
Definition at line 918 of file sf0x.cpp.
References errx, and SF0X::print_info().
Referenced by sf0x_main().
void sf0x::reset ()
Reset the driver.
Reset the driver.
Definition at line 895 of file sf0x.cpp.
References err, fd, SF0X::ioctl(), device::CDev::open(), RANGE_FINDER0_DEVICE_PATH, SENSOR_POLLRATE_DEFAULT, SENSORIOCRESET, and SENSORIOCSPOLLRATE.
Referenced by sf0x_main().
void sf0x::start (const char * port, uint8_t rotation)
Start the driver.
Definition at line 768 of file sf0x.cpp.
References errx, fd, g_dev, SF0X::init(), SF0X::ioctl(), OK, device::CDev::open(), RANGE_FINDER0_DEVICE_PATH, SENSOR_POLLRATE_DEFAULT, SENSORIOCSPOLLRATE, SF0X::SF0X(), and warnx.
Referenced by sf0x_main().
void sf0x::stop ()
Stop the driver.
Stop the driver.
Definition at line 814 of file sf0x.cpp.
References errx, and g_dev.
Referenced by sf0x_main().
void sf0x::test ()
Perform some basic functional tests on the driver; make sure we can collect data from the sensor in polled and automatic modes.
Definition at line 833 of file sf0x.cpp.
References err, errx, fd, SF0X::ioctl(), OK, device::CDev::open(), device::CDev::poll(), RANGE_FINDER0_DEVICE_PATH, SF0X::read(), SENSOR_POLLRATE_DEFAULT, SENSORIOCSPOLLRATE, and warnx.
Referenced by sf0x_main().
Variable Documentation
SF0X* sf0x::g_dev
Definition at line 756 of file sf0x.cpp.
Referenced by start(), and stop().