PX4 Firmware: src/lib/mixer/MultirotorMixer/test_mixer_multirotor.cpp File Reference
test_mixer_multirotor.cpp File Reference
#include "MultirotorMixer.hpp"
#include <cstdio>
#include <math.h>
Functions
static int mixer_callback (uintptr_t handle, uint8_t control_group, uint8_t control_index, float &control)
int main (int argc, char *argv[])
Variables
static const unsigned output_max = 16
testing binary that runs the multirotor mixer through test cases given via file or stdin and compares the mixer output against expected values.
static float actuator_controls [output_max] {}
Function Documentation
main()
int main (int argc, char * argv[])
Definition at line 59 of file test_mixer_multirotor.cpp.
References actuator_controls, MultirotorMixer::mix(), uart_esc::mixer, mixer_callback(), output_max, and MultirotorMixer::set_airmode().
mixer_callback()
static int mixer_callback (uintptr_t handle, uint8_t control_group, uint8_t control_index, float & control) static
Definition at line 53 of file test_mixer_multirotor.cpp.
References actuator_controls.
Referenced by main().
Variable Documentation
actuator_controls
float actuator_controls[output_max] {} static
Definition at line 45 of file test_mixer_multirotor.cpp.
Referenced by MavlinkReceiver::handle_message_set_actuator_control_target(), main(), mixer_callback(), Commander::run(), and vmount::OutputRC::update().
output_max
const unsigned output_max = 16 static
testing binary that runs the multirotor mixer through test cases given via file or stdin and compares the mixer output against expected values.
Definition at line 44 of file test_mixer_multirotor.cpp.
Referenced by main().