PX4 Firmware: src/drivers/uavcan/uavcan_drivers/stm32/driver/src/uc_stm32_can.cpp File Reference
uc_stm32_can.cpp File Reference
#include <cassert>
#include <cstring>
#include <uavcan_stm32/can.hpp>
#include <uavcan_stm32/clock.hpp>
#include "internal.hpp"
Namespaces
uavcan_stm32
Functions
UAVCAN_STM32_IRQ_HANDLER (CAN1_TX_IRQHandler)
UAVCAN_STM32_IRQ_HANDLER (CAN1_RX0_IRQHandler)
UAVCAN_STM32_IRQ_HANDLER (CAN1_RX1_IRQHandler)
Function Documentation
UAVCAN_STM32_IRQ_HANDLER() [1/3]
UAVCAN_STM32_IRQ_HANDLER (CAN1_TX_IRQHandler)
Definition at line 1050 of file uc_stm32_can.cpp.
Referenced by uavcan_stm32::CanDriver::hadActivity(), and UAVCAN_STM32_IRQ_HANDLER().
UAVCAN_STM32_IRQ_HANDLER() [2/3]
UAVCAN_STM32_IRQ_HANDLER (CAN1_RX0_IRQHandler)
Definition at line 1058 of file uc_stm32_can.cpp.
References UAVCAN_STM32_IRQ_HANDLER().
UAVCAN_STM32_IRQ_HANDLER() [3/3]
UAVCAN_STM32_IRQ_HANDLER (CAN1_RX1_IRQHandler)
Definition at line 1066 of file uc_stm32_can.cpp.
References UAVCAN_STM32_IRQ_HANDLER().