PX4 Firmware: ll40ls Namespace Reference
ll40ls Namespace Reference
Local functions in support of the shell command.
Functions
void start (enum LL40LS_BUS busid, uint8_t rotation)
Starts the driver.
void stop ()
Stops the driver.
void test ()
Performs some basic functional tests on the driver; make sure we can collect data from the sensor in polled and automatic modes.
void reset ()
Resets the driver.
void info ()
Prints status info about the driver.
void regdump ()
Dumps the register information.
void usage ()
Displays driver usage at the console.
Variables
LidarLite * instance = nullptr
Detailed Description
Local functions in support of the shell command.
Function Documentation
void ll40ls::info ()
Prints status info about the driver.
Print a little info about the driver.
Definition at line 296 of file ll40ls.cpp.
References LidarLite::print_info(), and warnx.
Referenced by ll40ls_main().
void ll40ls::regdump (void)
Dumps the register information.
Definition at line 311 of file ll40ls.cpp.
References LidarLite::print_registers(), and warnx.
Referenced by ll40ls_main().
void ll40ls::reset ()
Resets the driver.
Reset the driver.
Definition at line 265 of file ll40ls.cpp.
References fd, LidarLite::get_dev_name(), px4_close(), PX4_ERR, px4_ioctl(), px4_open(), PX4_WARN, SENSOR_POLLRATE_DEFAULT, SENSORIOCRESET, and SENSORIOCSPOLLRATE.
Referenced by ll40ls_main().
void ll40ls::start (enum LL40LS_BUS busid, uint8_t rotation)
Starts the driver.
Definition at line 111 of file ll40ls.cpp.
References bus_options, ll40ls_bus_option::busnum, ll40ls_bus_option::devname, fd, LidarLite::get_dev_name(), LidarLite::init(), LL40LS_BUS_I2C_ALL, LL40LS_BUS_PWM, LL40LS_DEVICE_PATH_PWM, px4_close(), PX4_ERR, PX4_INFO, px4_ioctl(), PX4_OK, px4_open(), PX4_WARN, SENSOR_POLLRATE_DEFAULT, SENSORIOCSPOLLRATE, and stop().
Referenced by ll40ls_main().
void ll40ls::stop ()
Stops the driver.
Stop the driver.
Definition at line 182 of file ll40ls.cpp.
References instance.
Referenced by ll40ls_main().
void ll40ls::test ()
Performs some basic functional tests on the driver; make sure we can collect data from the sensor in polled and automatic modes.
Definition at line 194 of file ll40ls.cpp.
References fd, LidarLite::get_dev_name(), px4_close(), PX4_ERR, px4_ioctl(), PX4_OK, px4_open(), px4_poll(), px4_read(), PX4_WARN, SENSOR_POLLRATE_DEFAULT, and SENSORIOCSPOLLRATE.
Referenced by ll40ls_main().
void ll40ls::usage (void)
Displays driver usage at the console.
Prints info about the driver argument usage.
Definition at line 326 of file ll40ls.cpp.
References PX4_INFO.
Referenced by ll40ls_main().
Variable Documentation
LidarLite* ll40ls::instance = nullptr
Definition at line 98 of file ll40ls.cpp.
Referenced by stop().