PX4 Firmware: landing_target_estimator Namespace Reference
landing_target_estimator Namespace Reference
Classes
class KalmanFilter
class LandingTargetEstimator
Functions
__EXPORT int landing_target_estimator_main (int argc, char *argv[])
Landing target position estimator app start / stop handling function This makes the module accessible from the nuttx shell.
int landing_target_estimator_thread_main (int argc, char *argv[])
Mainloop of daemon.
Variables
static bool thread_should_exit = false
daemon exit flag
static bool thread_running = false
daemon status flag
static int daemon_task
Handle of daemon task / thread.
static constexpr uint32_t landing_target_estimator_UPDATE_RATE_HZ = 50
Function Documentation
landing_target_estimator_main()
int landing_target_estimator::landing_target_estimator_main (int argc, char * argv[])
Landing target position estimator app start / stop handling function This makes the module accessible from the nuttx shell.
Main entry point for this module.
Definition at line 83 of file landing_target_estimator_main.cpp.
References landing_target_estimator_thread_main().
landing_target_estimator_thread_main()
int landing_target_estimator::landing_target_estimator_thread_main (int argc, char * argv[])
Mainloop of daemon.
Definition at line 133 of file landing_target_estimator_main.cpp.
References landing_target_estimator::LandingTargetEstimator::update().
Referenced by landing_target_estimator_main().
Variable Documentation
daemon_task
int landing_target_estimator::daemon_task static
Handle of daemon task / thread.
Definition at line 63 of file landing_target_estimator_main.cpp.
landing_target_estimator_UPDATE_RATE_HZ
constexpr uint32_t landing_target_estimator::landing_target_estimator_UPDATE_RATE_HZ = 50 static
Definition at line 66 of file landing_target_estimator_main.cpp.
thread_running
bool landing_target_estimator::thread_running = false static
daemon status flag
Definition at line 62 of file landing_target_estimator_main.cpp.
thread_should_exit
bool landing_target_estimator::thread_should_exit = false static
daemon exit flag
Definition at line 61 of file landing_target_estimator_main.cpp.