PX4 Firmware: SF1XX Class Reference
SF1XX Class Reference
Public Member Functions
SF1XX (uint8_t rotation=distance_sensor_s::ROTATION_DOWNWARD_FACING, int bus=SF1XX_BUS_DEFAULT, int address=SF1XX_BASEADDR)
virtual ~SF1XX ()
virtual int init ()
virtual ssize_t read (device::file_t *filp, char *buffer, size_t buflen)
virtual int ioctl (device::file_t *filp, int cmd, unsigned long arg)
void print_info ()
Diagnostics - print some basic information about the driver.
Protected Member Functions
virtual int probe ()
Private Member Functions
int probe_address (uint8_t address)
Test whether the device supported by the driver is present at a specific address.
void start ()
Initialise the automatic measurement state machine and start it.
void stop ()
Stop the automatic measurement state machine.
void set_minimum_distance (float min)
Set the min and max distance thresholds if you want the end points of the sensors range to be brought in at all, otherwise it will use the defaults SF1XX_MIN_DISTANCE and SF1XX_MAX_DISTANCE.
void set_maximum_distance (float max)
float get_minimum_distance ()
float get_maximum_distance ()
void cycle ()
Perform a poll cycle; collect from the previous measurement and start a new one.
int measure ()
int collect ()
Static Private Member Functions
static void cycle_trampoline (void *arg)
Static trampoline from the workq context; because we don't have a generic workq wrapper yet.
Private Attributes
uint8_t _rotation
float _min_distance
float _max_distance
int _conversion_interval
work_s _work
ringbuffer::RingBuffer * _reports
bool _sensor_ok
int _measure_ticks
int _class_instance
int _orb_class_instance
orb_advert_t _distance_sensor_topic
perf_counter_t _sample_perf
perf_counter_t _comms_errors
Detailed Description
Definition at line 85 of file sf1xx.cpp.
Constructor & Destructor Documentation
SF1XX::SF1XX (uint8_t rotation = distance_sensor_s::ROTATION_DOWNWARD_FACING, int bus = SF1XX_BUS_DEFAULT, int address = SF1XX_BASEADDR)
Definition at line 179 of file sf1xx.cpp.
Referenced by sf1xx::start_bus().
SF1XX::~SF1XX () virtual
Definition at line 202 of file sf1xx.cpp.
References _class_instance, _comms_errors, _distance_sensor_topic, _reports, _sample_perf, orb_unadvertise(), perf_free(), RANGE_FINDER_BASE_DEVICE_PATH, and stop().
Member Function Documentation
int SF1XX::collect () private
Definition at line 527 of file sf1xx.cpp.
References _comms_errors, _distance_sensor_topic, _reports, _rotation, _sample_perf, distance_sensor_s::covariance, distance_sensor_s::current_distance, DEVICE_DEBUG, f(), get_maximum_distance(), get_minimum_distance(), hrt_absolute_time(), distance_sensor_s::id, distance_sensor_s::max_distance, distance_sensor_s::min_distance, OK, ORB_ID, orb_publish(), distance_sensor_s::orientation, perf_begin(), perf_count(), perf_end(), distance_sensor_s::signal_quality, distance_sensor_s::timestamp, and distance_sensor_s::type.
Referenced by cycle(), and read().
void SF1XX::cycle () private
Perform a poll cycle; collect from the previous measurement and start a new one.
Definition at line 603 of file sf1xx.cpp.
References _conversion_interval, collect(), cycle_trampoline(), DEVICE_DEBUG, OK, and start().
Referenced by cycle_trampoline().
void SF1XX::cycle_trampoline (void * arg) static private
Static trampoline from the workq context; because we don't have a generic workq wrapper yet.
Parameters
arg Instance pointer for the driver that is polling.
Definition at line 595 of file sf1xx.cpp.
References cycle().
Referenced by cycle(), and start().
float SF1XX::get_maximum_distance () private
Definition at line 338 of file sf1xx.cpp.
References _max_distance.
Referenced by collect().
float SF1XX::get_minimum_distance () private
Definition at line 332 of file sf1xx.cpp.
References _min_distance.
Referenced by collect().
int SF1XX::init () virtual
Definition at line 226 of file sf1xx.cpp.
References _class_instance, _conversion_interval, _distance_sensor_topic, _max_distance, _min_distance, _orb_class_instance, _reports, _sensor_ok, DEVICE_LOG, lis3mdl::init(), measure(), OK, orb_advertise_multi(), ORB_ID, ORB_PRIO_HIGH, param_find(), param_get(), PX4_ERROR, RANGE_FINDER_BASE_DEVICE_PATH, and SF1XX_BASEADDR.
Referenced by sf1xx::start_bus().
int SF1XX::ioctl (device::file_t * filp, int cmd, unsigned long arg) virtual
Definition at line 344 of file sf1xx.cpp.
References _conversion_interval, _measure_ticks, _reports, ATOMIC_ENTER, ATOMIC_LEAVE, OK, SENSOR_POLLRATE_DEFAULT, SENSOR_POLLRATE_EXTERNAL, SENSOR_POLLRATE_MANUAL, SENSOR_POLLRATE_MAX, SENSORIOCGPOLLRATE, SENSORIOCRESET, SENSORIOCSPOLLRATE, SENSORIOCSQUEUEDEPTH, start(), and stop().
Referenced by sf1xx::reset(), sf1xx::start_bus(), and sf1xx::test().
int SF1XX::measure () private
Definition at line 504 of file sf1xx.cpp.
References _comms_errors, DEVICE_DEBUG, OK, and perf_count().
Referenced by init(), probe(), read(), and start().
void SF1XX::print_info ()
Diagnostics - print some basic information about the driver.
Definition at line 623 of file sf1xx.cpp.
References _comms_errors, _measure_ticks, _reports, _sample_perf, and perf_print_counter().
Referenced by sf1xx::info().
int SF1XX::probe () protected virtual
Definition at line 314 of file sf1xx.cpp.
References measure().
int SF1XX::probe_address (uint8_t address) private
Test whether the device supported by the driver is present at a specific address.
Parameters
address The I2C bus address to probe.
Returns
True if the device is present.
ssize_t SF1XX::read (device::file_t * filp, char * buffer, size_t buflen) virtual
Definition at line 444 of file sf1xx.cpp.
References _conversion_interval, _measure_ticks, _reports, collect(), measure(), OK, and usleep().
Referenced by sf1xx::test().
void SF1XX::set_maximum_distance (float max) private
Definition at line 326 of file sf1xx.cpp.
References _max_distance, and max().
void SF1XX::set_minimum_distance (float min) private
Set the min and max distance thresholds if you want the end points of the sensors range to be brought in at all, otherwise it will use the defaults SF1XX_MIN_DISTANCE and SF1XX_MAX_DISTANCE.
Definition at line 320 of file sf1xx.cpp.
References _min_distance, and min().
void SF1XX::start () private
Initialise the automatic measurement state machine and start it.
Note
This function is called at open and error time. It might make sense to make it more aggressive about resetting the bus in case of errors.
Definition at line 576 of file sf1xx.cpp.
References _conversion_interval, _reports, cycle_trampoline(), and measure().
Referenced by cycle(), and ioctl().
void SF1XX::stop () private
Stop the automatic measurement state machine.
Definition at line 589 of file sf1xx.cpp.
Referenced by ioctl(), and ~SF1XX().
Member Data Documentation
int SF1XX::_class_instance private
Definition at line 114 of file sf1xx.cpp.
Referenced by init(), and ~SF1XX().
perf_counter_t SF1XX::_comms_errors private
Definition at line 120 of file sf1xx.cpp.
Referenced by collect(), measure(), print_info(), and ~SF1XX().
int SF1XX::_conversion_interval private
Definition at line 109 of file sf1xx.cpp.
Referenced by cycle(), init(), ioctl(), read(), and start().
orb_advert_t SF1XX::_distance_sensor_topic private
Definition at line 117 of file sf1xx.cpp.
Referenced by collect(), init(), and ~SF1XX().
float SF1XX::_max_distance private
Definition at line 108 of file sf1xx.cpp.
Referenced by get_maximum_distance(), init(), and set_maximum_distance().
int SF1XX::_measure_ticks private
Definition at line 113 of file sf1xx.cpp.
Referenced by ioctl(), print_info(), and read().
float SF1XX::_min_distance private
Definition at line 107 of file sf1xx.cpp.
Referenced by get_minimum_distance(), init(), and set_minimum_distance().
int SF1XX::_orb_class_instance private
Definition at line 115 of file sf1xx.cpp.
Referenced by init().
ringbuffer::RingBuffer* SF1XX::_reports private
Definition at line 111 of file sf1xx.cpp.
Referenced by collect(), init(), ioctl(), print_info(), read(), start(), and ~SF1XX().
uint8_t SF1XX::_rotation private
Definition at line 106 of file sf1xx.cpp.
Referenced by collect().
perf_counter_t SF1XX::_sample_perf private
Definition at line 119 of file sf1xx.cpp.
Referenced by collect(), print_info(), and ~SF1XX().
bool SF1XX::_sensor_ok private
Definition at line 112 of file sf1xx.cpp.
Referenced by init().
work_s SF1XX::_work private
Definition at line 110 of file sf1xx.cpp.
The documentation for this class was generated from the following file:
src/drivers/distance_sensor/sf1xx/sf1xx.cpp