PX4 Firmware: uavcan_kinetis::flexcan Namespace Reference
uavcan_kinetis::flexcan Namespace Reference
Classes
struct CanType
union DataType
union FIFOcsType
union FilterType
union IDType
union MBcsType
struct MessageBufferType
struct RxFiFoType
Enumerations
enum { HWMaxMB = 16 }
enum mb_code_tx {
TxMbInactive = 0x8, TxMbAbort = 0x9, TxMbDataOrRemote = 0xC, TxMbTanswer = 0xE,
TxMbNotUsed = 0xF
}
enum mb_code_rx {
kRxMbInactive = 0x0, kRxMbFull = 0x2, kRxMbEmpty = 0x4, kRxMbOverrun = 0x6,
kRxMbBusy = 0x8, kRxMbRanswer = 0xA, kRxMbNotUsed = 0xF
}
enum { FiFo = 0 }
enum { FirstFilter = 6 }
enum { NumHWFilters = 16 }
enum { NumMBinFiFoAndFilters = 10 }
enum { TXMBMask = (0b111111 << NumMBinFiFoAndFilters) }
Functions
constexpr unsigned long MCR_IDAM_FMTA (0U<< MCR_IDAM_SHIFT)
constexpr unsigned long CAN_MCR_IDAM_FMTB (1U<< MCR_IDAM_SHIFT)
constexpr unsigned long MCR_IDAM_FMTC (2U<< MCR_IDAM_SHIFT)
constexpr unsigned long MCR_IDAM_FMTD (3U<< MCR_IDAM_SHIFT)
constexpr unsigned long CTRL2_RFFN_MASK (15U<< CTRL2_RFFN_SHIFT)
constexpr unsigned long CTRL2_RFFN_8MB (0U<< CTRL2_RFFN_SHIFT)
constexpr unsigned long CTRL2_RFFN_16MB (1U<< CTRL2_RFFN_SHIFT)
constexpr unsigned long CTRL2_RFFN_24MB (2U<< CTRL2_RFFN_SHIFT)
constexpr unsigned long CTRL2_RFFN_32MB (3U<< CTRL2_RFFN_SHIFT)
constexpr unsigned long CTRL2_RFFN_40MB (4U<< CTRL2_RFFN_SHIFT)
constexpr unsigned long CTRL2_RFFN_48MB (5U<< CTRL2_RFFN_SHIFT)
constexpr unsigned long CTRL2_RFFN_56MB (6U<< CTRL2_RFFN_SHIFT)
constexpr unsigned long CTRL2_RFFN_64MB (7U<< CTRL2_RFFN_SHIFT)
constexpr unsigned long CTRL2_RFFN_72MB (8U<< CTRL2_RFFN_SHIFT)
constexpr unsigned long CTRL2_RFFN_80MB (9U<< CTRL2_RFFN_SHIFT)
constexpr unsigned long CTRL2_RFFN_88MB (10U<< CTRL2_RFFN_SHIFT)
constexpr unsigned long CTRL2_RFFN_96MB (11U<< CTRL2_RFFN_SHIFT)
constexpr unsigned long CTRL2_RFFN_104MB (12U<< CTRL2_RFFN_SHIFT)
constexpr unsigned long CTRL2_RFFN_112MB (13U<< CTRL2_RFFN_SHIFT)
constexpr unsigned long CTRL2_RFFN_120MB (14U<< CTRL2_RFFN_SHIFT)
constexpr unsigned long CTRL2_RFFN_128MB (15U<< CTRL2_RFFN_SHIFT)
Variables
CanType *const Can [UAVCAN_KINETIS_NUM_IFACES]
CANx register sets.
constexpr unsigned long MCR_MAXMB_SHIFT = (0)
constexpr unsigned long MCR_MAXMB_MASK = (0x7fU << MCR_MAXMB_SHIFT)
constexpr unsigned long MCR_IDAM_SHIFT = (8)
constexpr unsigned long MCR_IDAM_MASK = (3U << MCR_IDAM_SHIFT)
constexpr unsigned long MCR_AEN = (1U << 12)
constexpr unsigned long MCR_LPRIOEN = (1U << 13)
constexpr unsigned long MCR_IRMQ = (1U << 16)
constexpr unsigned long MCR_SRXDIS = (1U << 17)
constexpr unsigned long MCR_WAKSRC = (1U << 19)
constexpr unsigned long MCR_LPMACK = (1U << 20)
constexpr unsigned long MCR_WRNEN = (1U << 21)
constexpr unsigned long MCR_SLFWAK = (1U << 22)
constexpr unsigned long MCR_SUPV = (1U << 23)
constexpr unsigned long MCR_FRZACK = (1U << 24)
constexpr unsigned long MCR_SOFTRST = (1U << 25)
constexpr unsigned long MCR_WAKMSK = (1U << 26)
constexpr unsigned long MCR_NOTRDY = (1U << 27)
constexpr unsigned long MCR_HALT = (1U << 28)
constexpr unsigned long MCR_RFEN = (1U << 29)
constexpr unsigned long MCR_FRZ = (1U << 30)
constexpr unsigned long MCR_MDIS = (1U << 31)
constexpr unsigned long CTRL1_ROPSEG_SHIFT = (0)
constexpr unsigned long CTRL1_ROPSEG_MASK = (7U << CTRL1_ROPSEG_SHIFT)
constexpr unsigned long CTRL1_LOM = (1U << 3)
constexpr unsigned long CTRL1_LBUF = (1U << 4)
constexpr unsigned long CTRL1_TSYN = (1U << 5)
constexpr unsigned long CTRL1_BOFFREC = (1U << 6)
constexpr unsigned long CTRL1_SMP = (1U << 7)
constexpr unsigned long CTRL1_RWRNMSK = (1U << 10)
constexpr unsigned long CTRL1_TWRNMSK = (1U << 11)
constexpr unsigned long CTRL1_LPB = (1U << 12)
constexpr unsigned long CTRL1_CLKSRC = (1U << 13)
constexpr unsigned long CTRL1_ERRMSK = (1U << 14)
constexpr unsigned long CTRL1_BOFFMSK = (1U << 15)
constexpr unsigned long CTRL1_PSEG2_SHIFT = (16)
constexpr unsigned long CTRL1_PSEG2_MASK = (7U << CTRL1_PSEG2_SHIFT)
constexpr unsigned long CTRL1_PSEG1_SHIFT = (19)
constexpr unsigned long CTRL1_PSEG1_MASK = (7U << CTRL1_PSEG1_SHIFT)
constexpr unsigned long CTRL1_RJW_SHIFT = (22)
constexpr unsigned long CTRL1_RJW_MASK = (3U << CTRL1_RJW_SHIFT)
constexpr unsigned long CTRL1_PRESDIV_SHIFT = (24)
constexpr unsigned long CTRL1_PRESDIV_MASK = (0xff << CTRL1_PRESDIV_SHIFT)
constexpr unsigned long TIMER_SHIFT = (0U)
constexpr unsigned long TIMER_MASK = (0xffffU << TIMER_SHIFT)
constexpr unsigned long RXMGMASK0 = (1U << 0)
constexpr unsigned long RXMGMASK1 = (1U << 1)
constexpr unsigned long RXMGMASK2 = (1U << 2)
constexpr unsigned long RXMGMASK3 = (1U << 3)
constexpr unsigned long RXMGMASK4 = (1U << 4)
constexpr unsigned long RXMGMASK5 = (1U << 5)
constexpr unsigned long RXMGMASK6 = (1U << 6)
constexpr unsigned long RXMGMASK7 = (1U << 7)
constexpr unsigned long RXMGMASK8 = (1U << 8)
constexpr unsigned long RXMGMASK9 = (1U << 9)
constexpr unsigned long RXMGMASK10 = (1U << 10)
constexpr unsigned long RXMGMASK11 = (1U << 11)
constexpr unsigned long RXMGMASK12 = (1U << 12)
constexpr unsigned long RXMGMASK13 = (1U << 13)
constexpr unsigned long RXMGMASK14 = (1U << 14)
constexpr unsigned long RXMGMASK15 = (1U << 15)
constexpr unsigned long RXMGMASK16 = (1U << 16)
constexpr unsigned long RXMGMASK17 = (1U << 17)
constexpr unsigned long RXMGMASK18 = (1U << 18)
constexpr unsigned long RXMGMASK19 = (1U << 19)
constexpr unsigned long RXMGMASK20 = (1U << 20)
constexpr unsigned long RXMGMASK21 = (1U << 21)
constexpr unsigned long RXMGMASK22 = (1U << 22)
constexpr unsigned long RXMGMASK23 = (1U << 23)
constexpr unsigned long RXMGMASK24 = (1U << 24)
constexpr unsigned long RXMGMASK25 = (1U << 25)
constexpr unsigned long RXMGMASK26 = (1U << 26)
constexpr unsigned long RXMGMASK27 = (1U << 27)
constexpr unsigned long RXMGMASK28 = (1U << 28)
constexpr unsigned long RXMGMASK29 = (1U << 29)
constexpr unsigned long RXMGMASK30 = (1U << 30)
constexpr unsigned long RXMGMASK31 = (1U << 31)
constexpr unsigned long RXM14MASK0 = (1U << 0)
constexpr unsigned long RXM14MASK1 = (1U << 1)
constexpr unsigned long RXM14MASK2 = (1U << 2)
constexpr unsigned long RXM14MASK3 = (1U << 3)
constexpr unsigned long RXM14MASK4 = (1U << 4)
constexpr unsigned long RXM14MASK5 = (1U << 5)
constexpr unsigned long RXM14MASK6 = (1U << 6)
constexpr unsigned long RXM14MASK7 = (1U << 7)
constexpr unsigned long RXM14MASK8 = (1U << 8)
constexpr unsigned long RXM14MASK9 = (1U << 9)
constexpr unsigned long RXM14MASK10 = (1U << 10)
constexpr unsigned long RXM14MASK11 = (1U << 11)
constexpr unsigned long RXM14MASK12 = (1U << 12)
constexpr unsigned long RXM14MASK13 = (1U << 13)
constexpr unsigned long RXM14MASK14 = (1U << 14)
constexpr unsigned long RXM14MASK15 = (1U << 15)
constexpr unsigned long RXM14MASK16 = (1U << 16)
constexpr unsigned long RXM14MASK17 = (1U << 17)
constexpr unsigned long RXM14MASK18 = (1U << 18)
constexpr unsigned long RXM14MASK19 = (1U << 19)
constexpr unsigned long RXM14MASK20 = (1U << 20)
constexpr unsigned long RXM14MASK21 = (1U << 21)
constexpr unsigned long RXM14MASK22 = (1U << 22)
constexpr unsigned long RXM14MASK23 = (1U << 23)
constexpr unsigned long RXM14MASK24 = (1U << 24)
constexpr unsigned long RXM14MASK25 = (1U << 25)
constexpr unsigned long RXM14MASK26 = (1U << 26)
constexpr unsigned long RXM14MASK27 = (1U << 27)
constexpr unsigned long RXM14MASK28 = (1U << 28)
constexpr unsigned long RXM14MASK29 = (1U << 29)
constexpr unsigned long RXM14MASK30 = (1U << 30)
constexpr unsigned long RXM14MASK31 = (1U << 31)
constexpr unsigned long RXM15MASK0 = (1U << 0)
constexpr unsigned long RXM15MASK1 = (1U << 1)
constexpr unsigned long RXM15MASK2 = (1U << 2)
constexpr unsigned long RXM15MASK3 = (1U << 3)
constexpr unsigned long RXM15MASK4 = (1U << 4)
constexpr unsigned long RXM15MASK5 = (1U << 5)
constexpr unsigned long RXM15MASK6 = (1U << 6)
constexpr unsigned long RXM15MASK7 = (1U << 7)
constexpr unsigned long RXM15MASK8 = (1U << 8)
constexpr unsigned long RXM15MASK9 = (1U << 9)
constexpr unsigned long RXM15MASK10 = (1U << 10)
constexpr unsigned long RXM15MASK11 = (1U << 11)
constexpr unsigned long RXM15MASK12 = (1U << 12)
constexpr unsigned long RXM15MASK13 = (1U << 13)
constexpr unsigned long RXM15MASK14 = (1U << 14)
constexpr unsigned long RXM15MASK15 = (1U << 15)
constexpr unsigned long RXM15MASK16 = (1U << 16)
constexpr unsigned long RXM15MASK17 = (1U << 17)
constexpr unsigned long RXM15MASK18 = (1U << 18)
constexpr unsigned long RXM15MASK19 = (1U << 19)
constexpr unsigned long RXM15MASK20 = (1U << 20)
constexpr unsigned long RXM15MASK21 = (1U << 21)
constexpr unsigned long RXM15MASK22 = (1U << 22)
constexpr unsigned long RXM15MASK23 = (1U << 23)
constexpr unsigned long RXM15MASK24 = (1U << 24)
constexpr unsigned long RXM15MASK25 = (1U << 25)
constexpr unsigned long RXM15MASK26 = (1U << 26)
constexpr unsigned long RXM15MASK27 = (1U << 27)
constexpr unsigned long RXM15MASK28 = (1U << 28)
constexpr unsigned long RXM15MASK29 = (1U << 29)
constexpr unsigned long RXM15MASK30 = (1U << 30)
constexpr unsigned long RXM15MASK31 = (1U << 31)
constexpr unsigned long ECR_TXERRCNT_SHIFT = (0U)
constexpr unsigned long ECR_TXERRCNT_MASK = (0xff << ECR_TXERRCNT_SHIFT)
constexpr unsigned long ECR_RXERRCNT_SHIFT = (8)
constexpr unsigned long ECR_RXERRCNT_MASK = (0xff << ECR_RXERRCNT_SHIFT)
constexpr unsigned long ESR1_WAKINT = (1U << 0)
constexpr unsigned long ESR1_ERRINT = (1U << 1)
constexpr unsigned long ESR1_BOFFINT = (1U << 2)
constexpr unsigned long ESR1_RX = (1U << 3)
constexpr unsigned long ESR1_FLTCONF_SHIFT = (4U)
constexpr unsigned long ESR1_FLTCONF_MASK = (3U << ESR1_FLTCONF_SHIFT)
constexpr unsigned long ESR1_FLTCONF_ACTV = (0U << ESR1_FLTCONF_SHIFT)
constexpr unsigned long ESR1_FLTCONF_PASV = (1U << ESR1_FLTCONF_SHIFT)
constexpr unsigned long ESR1_FLTCONF_OFF = (2U << ESR1_FLTCONF_SHIFT)
constexpr unsigned long ESR1_TX = (1U << 6)
constexpr unsigned long ESR1_IDLE = (1U << 7)
constexpr unsigned long ESR1_RXWRN = (1U << 8)
constexpr unsigned long ESR1_TXWRN = (1U << 9)
constexpr unsigned long ESR1_STFERR = (1U << 10)
constexpr unsigned long ESR1_FRMERR = (1U << 11)
constexpr unsigned long ESR1_CRCERR = (1U << 12)
constexpr unsigned long ESR1_ACKERR = (1U << 13)
constexpr unsigned long ESR1_BIT0ERR = (1U << 14)
constexpr unsigned long ESR1_BIT1ERR = (1U << 15)
constexpr unsigned long ESR1_RWRNINT = (1U << 16)
constexpr unsigned long ESR1_TWRNINT = (1U << 17)
constexpr unsigned long ESR1_SYNCH = (1U << 18)
constexpr unsigned long CAN_IMASK2_0 = (1U << 0)
constexpr unsigned long CAN_IMASK2_1 = (1U << 1)
constexpr unsigned long CAN_IMASK2_2 = (1U << 2)
constexpr unsigned long CAN_IMASK2_3 = (1U << 3)
constexpr unsigned long CAN_IMASK2_4 = (1U << 4)
constexpr unsigned long CAN_IMASK2_5 = (1U << 5)
constexpr unsigned long CAN_IMASK2_6 = (1U << 6)
constexpr unsigned long CAN_IMASK2_7 = (1U << 7)
constexpr unsigned long CAN_IMASK2_8 = (1U << 8)
constexpr unsigned long CAN_IMASK2_9 = (1U << 9)
constexpr unsigned long CAN_IMASK2_10 = (1U << 10)
constexpr unsigned long CAN_IMASK2_11 = (1U << 11)
constexpr unsigned long CAN_IMASK2_12 = (1U << 12)
constexpr unsigned long CAN_IMASK2_13 = (1U << 13)
constexpr unsigned long CAN_IMASK2_14 = (1U << 14)
constexpr unsigned long CAN_IMASK2_15 = (1U << 15)
constexpr unsigned long CAN_IMASK2_16 = (1U << 16)
constexpr unsigned long CAN_IMASK2_17 = (1U << 17)
constexpr unsigned long CAN_IMASK2_18 = (1U << 18)
constexpr unsigned long CAN_IMASK2_19 = (1U << 19)
constexpr unsigned long CAN_IMASK2_20 = (1U << 20)
constexpr unsigned long CAN_IMASK2_21 = (1U << 21)
constexpr unsigned long CAN_IMASK2_22 = (1U << 22)
constexpr unsigned long CAN_IMASK2_23 = (1U << 23)
constexpr unsigned long CAN_IMASK2_24 = (1U << 24)
constexpr unsigned long CAN_IMASK2_25 = (1U << 25)
constexpr unsigned long CAN_IMASK2_26 = (1U << 26)
constexpr unsigned long CAN_IMASK2_27 = (1U << 27)
constexpr unsigned long CAN_IMASK2_28 = (1U << 28)
constexpr unsigned long CAN_IMASK2_29 = (1U << 29)
constexpr unsigned long CAN_IMASK2_30 = (1U << 30)
constexpr unsigned long CAN_IMASK2_31 = (1U << 31)
constexpr unsigned long CAN_IMASK1_0 = (1U << 0)
constexpr unsigned long CAN_IMASK1_1 = (1U << 1)
constexpr unsigned long CAN_IMASK1_2 = (1U << 2)
constexpr unsigned long CAN_IMASK1_3 = (1U << 3)
constexpr unsigned long CAN_IMASK1_4 = (1U << 4)
constexpr unsigned long CAN_IMASK1_5 = (1U << 5)
constexpr unsigned long CAN_IMASK1_6 = (1U << 6)
constexpr unsigned long CAN_IMASK1_7 = (1U << 7)
constexpr unsigned long CAN_IMASK1_8 = (1U << 8)
constexpr unsigned long CAN_IMASK1_9 = (1U << 9)
constexpr unsigned long CAN_IMASK1_10 = (1U << 10)
constexpr unsigned long CAN_IMASK1_11 = (1U << 11)
constexpr unsigned long CAN_IMASK1_12 = (1U << 12)
constexpr unsigned long CAN_IMASK1_13 = (1U << 13)
constexpr unsigned long CAN_IMASK1_14 = (1U << 14)
constexpr unsigned long CAN_IMASK1_15 = (1U << 15)
constexpr unsigned long CAN_IMASK1_16 = (1U << 16)
constexpr unsigned long CAN_IMASK1_17 = (1U << 17)
constexpr unsigned long CAN_IMASK1_18 = (1U << 18)
constexpr unsigned long CAN_IMASK1_19 = (1U << 19)
constexpr unsigned long CAN_IMASK1_20 = (1U << 20)
constexpr unsigned long CAN_IMASK1_21 = (1U << 21)
constexpr unsigned long CAN_IMASK1_22 = (1U << 22)
constexpr unsigned long CAN_IMASK1_23 = (1U << 23)
constexpr unsigned long CAN_IMASK1_24 = (1U << 24)
constexpr unsigned long CAN_IMASK1_25 = (1U << 25)
constexpr unsigned long CAN_IMASK1_26 = (1U << 26)
constexpr unsigned long CAN_IMASK1_27 = (1U << 27)
constexpr unsigned long CAN_IMASK1_28 = (1U << 28)
constexpr unsigned long CAN_IMASK1_29 = (1U << 29)
constexpr unsigned long CAN_IMASK1_30 = (1U << 30)
constexpr unsigned long CAN_IMASK1_31 = (1U << 31)
constexpr unsigned long CAN_IFLAG2_0 = (1U << 0)
constexpr unsigned long CAN_IFLAG2_1 = (1U << 1)
constexpr unsigned long CAN_IFLAG2_2 = (1U << 2)
constexpr unsigned long CAN_IFLAG2_3 = (1U << 3)
constexpr unsigned long CAN_IFLAG2_4 = (1U << 4)
constexpr unsigned long CAN_IFLAG2_5 = (1U << 5)
constexpr unsigned long CAN_IFLAG2_6 = (1U << 6)
constexpr unsigned long CAN_IFLAG2_7 = (1U << 7)
constexpr unsigned long CAN_IFLAG2_8 = (1U << 8)
constexpr unsigned long CAN_IFLAG2_9 = (1U << 9)
constexpr unsigned long CAN_IFLAG2_10 = (1U << 10)
constexpr unsigned long CAN_IFLAG2_11 = (1U << 11)
constexpr unsigned long CAN_IFLAG2_12 = (1U << 12)
constexpr unsigned long CAN_IFLAG2_13 = (1U << 13)
constexpr unsigned long CAN_IFLAG2_14 = (1U << 14)
constexpr unsigned long CAN_IFLAG2_15 = (1U << 15)
constexpr unsigned long CAN_IFLAG2_16 = (1U << 16)
constexpr unsigned long CAN_IFLAG2_17 = (1U << 17)
constexpr unsigned long CAN_IFLAG2_18 = (1U << 18)
constexpr unsigned long CAN_IFLAG2_19 = (1U << 19)
constexpr unsigned long CAN_IFLAG2_20 = (1U << 20)
constexpr unsigned long CAN_IFLAG2_21 = (1U << 21)
constexpr unsigned long CAN_IFLAG2_22 = (1U << 22)
constexpr unsigned long CAN_IFLAG2_23 = (1U << 23)
constexpr unsigned long CAN_IFLAG2_24 = (1U << 24)
constexpr unsigned long CAN_IFLAG2_25 = (1U << 25)
constexpr unsigned long CAN_IFLAG2_26 = (1U << 26)
constexpr unsigned long CAN_IFLAG2_27 = (1U << 27)
constexpr unsigned long CAN_IFLAG2_28 = (1U << 28)
constexpr unsigned long CAN_IFLAG2_29 = (1U << 29)
constexpr unsigned long CAN_IFLAG2_30 = (1U << 30)
constexpr unsigned long CAN_IFLAG2_31 = (1U << 31)
constexpr unsigned long CAN_IFLAG1_0 = (1U << 0)
constexpr unsigned long CAN_IFLAG1_1 = (1U << 1)
constexpr unsigned long CAN_IFLAG1_2 = (1U << 2)
constexpr unsigned long CAN_IFLAG1_3 = (1U << 3)
constexpr unsigned long CAN_IFLAG1_4 = (1U << 4)
constexpr unsigned long CAN_IFLAG1_5 = (1U << 5)
constexpr unsigned long CAN_FIFO_NE = CAN_IFLAG1_5
constexpr unsigned long CAN_IFLAG1_6 = (1U << 6)
constexpr unsigned long CAN_FIFO_WARN = CAN_IFLAG1_6
constexpr unsigned long CAN_IFLAG1_7 = (1U << 7)
constexpr unsigned long CAN_FIFO_OV = CAN_IFLAG1_7
constexpr unsigned long CAN_IFLAG1_8 = (1U << 8)
constexpr unsigned long CAN_IFLAG1_9 = (1U << 9)
constexpr unsigned long CAN_IFLAG1_10 = (1U << 10)
constexpr unsigned long CAN_IFLAG1_11 = (1U << 11)
constexpr unsigned long CAN_IFLAG1_12 = (1U << 12)
constexpr unsigned long CAN_IFLAG1_13 = (1U << 13)
constexpr unsigned long CAN_IFLAG1_14 = (1U << 14)
constexpr unsigned long CAN_IFLAG1_15 = (1U << 15)
constexpr unsigned long CAN_IFLAG1_16 = (1U << 16)
constexpr unsigned long CAN_IFLAG1_17 = (1U << 17)
constexpr unsigned long CAN_IFLAG1_18 = (1U << 18)
constexpr unsigned long CAN_IFLAG1_19 = (1U << 19)
constexpr unsigned long CAN_IFLAG1_20 = (1U << 20)
constexpr unsigned long CAN_IFLAG1_21 = (1U << 21)
constexpr unsigned long CAN_IFLAG1_22 = (1U << 22)
constexpr unsigned long CAN_IFLAG1_23 = (1U << 23)
constexpr unsigned long CAN_IFLAG1_24 = (1U << 24)
constexpr unsigned long CAN_IFLAG1_25 = (1U << 25)
constexpr unsigned long CAN_IFLAG1_26 = (1U << 26)
constexpr unsigned long CAN_IFLAG1_27 = (1U << 27)
constexpr unsigned long CAN_IFLAG1_28 = (1U << 28)
constexpr unsigned long CAN_IFLAG1_29 = (1U << 29)
constexpr unsigned long CAN_IFLAG1_30 = (1U << 30)
constexpr unsigned long CAN_IFLAG1_31 = (1U << 31)
constexpr unsigned long CTRL2_EACEN = (1U << 16)
constexpr unsigned long CTRL2_RRS = (1U << 17)
constexpr unsigned long CTRL2_MRP = (1U << 18)
constexpr unsigned long CTRL2_TASD_SHIFT = (19)
constexpr unsigned long CTRL2_TASD_MASK = (31U << CTRL2_TASD_SHIFT)
constexpr unsigned long CTRL2_RFFN_SHIFT = (24)
constexpr unsigned long CTRL2_WRMFRZ = (1U << 28U)
constexpr unsigned long ESR2_IMB = (1U << 13)
constexpr unsigned long ESR2_VPS = (1U << 14)
constexpr unsigned long ESR2_LPTM_SHIFT = (16)
constexpr unsigned long ESR2_LPTM_MASK = (0x7fU << ESR2_LPTM_SHIFT)
constexpr unsigned long CRCR_TXCRC_SHIFT = (0U)
constexpr unsigned long CRCR_TXCRC_MASK = (0x7fffU << CRCR_TXCRC_SHIFT)
constexpr unsigned long CRCR_MBCRC_SHIFT = (16)
constexpr unsigned long CRCR_MBCRC_MASK = (0x7fU << CRCR_MBCRC_SHIFT)
constexpr unsigned long RXFIR_IDHIT_SHIFT = (0)
constexpr unsigned long RXFIR_IDHIT_MASK = (0x1ffU << RXFIR_IDHIT_SHIFT)
constexpr unsigned long RXIMR0 = (1U << 0)
constexpr unsigned long RXIMR1 = (1U << 1)
constexpr unsigned long RXIMR2 = (1U << 2)
constexpr unsigned long RXIMR3 = (1U << 3)
constexpr unsigned long RXIMR4 = (1U << 4)
constexpr unsigned long RXIMR5 = (1U << 5)
constexpr unsigned long RXIMR6 = (1U << 6)
constexpr unsigned long RXIMR7 = (1U << 7)
constexpr unsigned long RXIMR8 = (1U << 8)
constexpr unsigned long RXIMR9 = (1U << 9)
constexpr unsigned long RXIMR10 = (1U << 10)
constexpr unsigned long RXIMR11 = (1U << 11)
constexpr unsigned long RXIMR12 = (1U << 12)
constexpr unsigned long RXIMR13 = (1U << 13)
constexpr unsigned long RXIMR14 = (1U << 14)
constexpr unsigned long RXIMR15 = (1U << 15)
constexpr unsigned long RXIMR16 = (1U << 16)
constexpr unsigned long RXIMR17 = (1U << 17)
constexpr unsigned long RXIMR18 = (1U << 18)
constexpr unsigned long RXIMR19 = (1U << 19)
constexpr unsigned long RXIMR20 = (1U << 20)
constexpr unsigned long RXIMR21 = (1U << 21)
constexpr unsigned long RXIMR22 = (1U << 22)
constexpr unsigned long RXIMR23 = (1U << 23)
constexpr unsigned long RXIMR24 = (1U << 24)
constexpr unsigned long RXIMR25 = (1U << 25)
constexpr unsigned long RXIMR26 = (1U << 26)
constexpr unsigned long RXIMR27 = (1U << 27)
constexpr unsigned long RXIMR28 = (1U << 28)
constexpr unsigned long RXIMR29 = (1U << 29)
constexpr unsigned long RXIMR30 = (1U << 30)
constexpr unsigned long RXIMR31 = (1U << 31)
const uavcan::uint32_t OSCERCLK = BOARD_EXTAL_FREQ
const uavcan::uint32_t busclck = BOARD_BUS_FREQ
const uavcan::uint8_t CLOCKSEL = 0
const uavcan::uint32_t canclk = CLOCKSEL ? busclck : OSCERCLK
const uavcan::uint8_t useFIFO = 1
const uavcan::uint32_t numberFIFOFilters = flexcan::CTRL2_RFFN_16MB
Enumeration Type Documentation
anonymous enum
anonymous enum
Enumerator
HWMaxMB
Definition at line 27 of file flexcan.hpp.
anonymous enum
anonymous enum
Enumerator
FiFo
Definition at line 168 of file flexcan.hpp.
anonymous enum
anonymous enum
Enumerator
FirstFilter
Definition at line 175 of file flexcan.hpp.
anonymous enum
anonymous enum
Enumerator
NumHWFilters
Definition at line 180 of file flexcan.hpp.
anonymous enum
anonymous enum
Enumerator
NumMBinFiFoAndFilters
Definition at line 181 of file flexcan.hpp.
anonymous enum
anonymous enum
Enumerator
TXMBMask
Definition at line 190 of file flexcan.hpp.
mb_code_rx
enum uavcan_kinetis::flexcan::mb_code_rx
Enumerator
kRxMbInactive
MB is not active.
kRxMbFull
MB is full.
kRxMbEmpty
MB is active and empty.
kRxMbOverrun
MB is overwritten into a full buffer.
kRxMbBusy
FlexCAN is updating the contents of the MB.
kRxMbRanswer
The CPU must not access the MB. A frame was configured to recognize a Remote Request Frame
kRxMbNotUsed
and transmit a Response Frame in return. Not used.
Definition at line 123 of file flexcan.hpp.
mb_code_tx
enum uavcan_kinetis::flexcan::mb_code_tx
Enumerator
TxMbInactive
MB is not active.
TxMbAbort
MB is aborted.
TxMbDataOrRemote
MB is a TX Data Frame(when MB RTR = 0) or MB is a TX Remote Request Frame (when MB RTR = 1).
TxMbTanswer
MB is a TX Response Request Frame from
TxMbNotUsed
an incoming Remote Request Frame. Not used.
Definition at line 107 of file flexcan.hpp.
Function Documentation
CAN_MCR_IDAM_FMTB()
constexpr unsigned long uavcan_kinetis::flexcan::CAN_MCR_IDAM_FMTB (1U<< MCR_IDAM_SHIFT)
CTRL2_RFFN_104MB()
constexpr unsigned long uavcan_kinetis::flexcan::CTRL2_RFFN_104MB (12U<< CTRL2_RFFN_SHIFT)
CTRL2_RFFN_112MB()
constexpr unsigned long uavcan_kinetis::flexcan::CTRL2_RFFN_112MB (13U<< CTRL2_RFFN_SHIFT)
CTRL2_RFFN_120MB()
constexpr unsigned long uavcan_kinetis::flexcan::CTRL2_RFFN_120MB (14U<< CTRL2_RFFN_SHIFT)
CTRL2_RFFN_128MB()
constexpr unsigned long uavcan_kinetis::flexcan::CTRL2_RFFN_128MB (15U<< CTRL2_RFFN_SHIFT)
CTRL2_RFFN_16MB()
constexpr unsigned long uavcan_kinetis::flexcan::CTRL2_RFFN_16MB (1U<< CTRL2_RFFN_SHIFT)
CTRL2_RFFN_24MB()
constexpr unsigned long uavcan_kinetis::flexcan::CTRL2_RFFN_24MB (2U<< CTRL2_RFFN_SHIFT)
CTRL2_RFFN_32MB()
constexpr unsigned long uavcan_kinetis::flexcan::CTRL2_RFFN_32MB (3U<< CTRL2_RFFN_SHIFT)
CTRL2_RFFN_40MB()
constexpr unsigned long uavcan_kinetis::flexcan::CTRL2_RFFN_40MB (4U<< CTRL2_RFFN_SHIFT)
CTRL2_RFFN_48MB()
constexpr unsigned long uavcan_kinetis::flexcan::CTRL2_RFFN_48MB (5U<< CTRL2_RFFN_SHIFT)
CTRL2_RFFN_56MB()
constexpr unsigned long uavcan_kinetis::flexcan::CTRL2_RFFN_56MB (6U<< CTRL2_RFFN_SHIFT)
CTRL2_RFFN_64MB()
constexpr unsigned long uavcan_kinetis::flexcan::CTRL2_RFFN_64MB (7U<< CTRL2_RFFN_SHIFT)
CTRL2_RFFN_72MB()
constexpr unsigned long uavcan_kinetis::flexcan::CTRL2_RFFN_72MB (8U<< CTRL2_RFFN_SHIFT)
CTRL2_RFFN_80MB()
constexpr unsigned long uavcan_kinetis::flexcan::CTRL2_RFFN_80MB (9U<< CTRL2_RFFN_SHIFT)
CTRL2_RFFN_88MB()
constexpr unsigned long uavcan_kinetis::flexcan::CTRL2_RFFN_88MB (10U<< CTRL2_RFFN_SHIFT)
CTRL2_RFFN_8MB()
constexpr unsigned long uavcan_kinetis::flexcan::CTRL2_RFFN_8MB (0U<< CTRL2_RFFN_SHIFT)
CTRL2_RFFN_96MB()
constexpr unsigned long uavcan_kinetis::flexcan::CTRL2_RFFN_96MB (11U<< CTRL2_RFFN_SHIFT)
CTRL2_RFFN_MASK()
constexpr unsigned long uavcan_kinetis::flexcan::CTRL2_RFFN_MASK (15U<< CTRL2_RFFN_SHIFT)
MCR_IDAM_FMTA()
constexpr unsigned long uavcan_kinetis::flexcan::MCR_IDAM_FMTA (0U<< MCR_IDAM_SHIFT)
MCR_IDAM_FMTC()
constexpr unsigned long uavcan_kinetis::flexcan::MCR_IDAM_FMTC (2U<< MCR_IDAM_SHIFT)
MCR_IDAM_FMTD()
constexpr unsigned long uavcan_kinetis::flexcan::MCR_IDAM_FMTD (3U<< MCR_IDAM_SHIFT)
Variable Documentation
busclck
const uavcan::uint32_t uavcan_kinetis::flexcan::busclck = BOARD_BUS_FREQ
Definition at line 32 of file uc_kinetis_flexcan.cpp.
Referenced by uavcan_kinetis::CanIface::doReset().
Can
CanType* const uavcan_kinetis::flexcan::Can[UAVCAN_KINETIS_NUM_IFACES]
Initial value:
= {
    reinterpret_cast<CanType *>(0x40024000)
}
CANx register sets.
Definition at line 198 of file flexcan.hpp.
Referenced by uavcan_kinetis::can0_irq().
CAN_FIFO_NE
constexpr unsigned long uavcan_kinetis::flexcan::CAN_FIFO_NE = CAN_IFLAG1_5
Definition at line 519 of file flexcan.hpp.
Referenced by uavcan_kinetis::can0_irq(), and uavcan_kinetis::CanIface::handleRxInterrupt().
CAN_FIFO_OV
constexpr unsigned long uavcan_kinetis::flexcan::CAN_FIFO_OV = CAN_IFLAG1_7
Definition at line 523 of file flexcan.hpp.
Referenced by uavcan_kinetis::can0_irq(), and uavcan_kinetis::CanIface::handleRxInterrupt().
CAN_FIFO_WARN
constexpr unsigned long uavcan_kinetis::flexcan::CAN_FIFO_WARN = CAN_IFLAG1_6
Definition at line 521 of file flexcan.hpp.
Referenced by uavcan_kinetis::can0_irq(), and uavcan_kinetis::CanIface::handleRxInterrupt().
CAN_IFLAG1_0
constexpr unsigned long uavcan_kinetis::flexcan::CAN_IFLAG1_0 = (1U << 0)
Definition at line 513 of file flexcan.hpp.
CAN_IFLAG1_1
constexpr unsigned long uavcan_kinetis::flexcan::CAN_IFLAG1_1 = (1U << 1)
Definition at line 514 of file flexcan.hpp.
CAN_IFLAG1_10
constexpr unsigned long uavcan_kinetis::flexcan::CAN_IFLAG1_10 = (1U << 10)
Definition at line 526 of file flexcan.hpp.
CAN_IFLAG1_11
constexpr unsigned long uavcan_kinetis::flexcan::CAN_IFLAG1_11 = (1U << 11)
Definition at line 527 of file flexcan.hpp.
CAN_IFLAG1_12
constexpr unsigned long uavcan_kinetis::flexcan::CAN_IFLAG1_12 = (1U << 12)
Definition at line 528 of file flexcan.hpp.
CAN_IFLAG1_13
constexpr unsigned long uavcan_kinetis::flexcan::CAN_IFLAG1_13 = (1U << 13)
Definition at line 529 of file flexcan.hpp.
CAN_IFLAG1_14
constexpr unsigned long uavcan_kinetis::flexcan::CAN_IFLAG1_14 = (1U << 14)
Definition at line 530 of file flexcan.hpp.
CAN_IFLAG1_15
constexpr unsigned long uavcan_kinetis::flexcan::CAN_IFLAG1_15 = (1U << 15)
Definition at line 531 of file flexcan.hpp.
CAN_IFLAG1_16
constexpr unsigned long uavcan_kinetis::flexcan::CAN_IFLAG1_16 = (1U << 16)
Definition at line 532 of file flexcan.hpp.
CAN_IFLAG1_17
constexpr unsigned long uavcan_kinetis::flexcan::CAN_IFLAG1_17 = (1U << 17)
Definition at line 533 of file flexcan.hpp.
CAN_IFLAG1_18
constexpr unsigned long uavcan_kinetis::flexcan::CAN_IFLAG1_18 = (1U << 18)
Definition at line 534 of file flexcan.hpp.
CAN_IFLAG1_19
constexpr unsigned long uavcan_kinetis::flexcan::CAN_IFLAG1_19 = (1U << 19)
Definition at line 535 of file flexcan.hpp.
CAN_IFLAG1_2
constexpr unsigned long uavcan_kinetis::flexcan::CAN_IFLAG1_2 = (1U << 2)
Definition at line 515 of file flexcan.hpp.
CAN_IFLAG1_20
constexpr unsigned long uavcan_kinetis::flexcan::CAN_IFLAG1_20 = (1U << 20)
Definition at line 536 of file flexcan.hpp.
CAN_IFLAG1_21
constexpr unsigned long uavcan_kinetis::flexcan::CAN_IFLAG1_21 = (1U << 21)
Definition at line 537 of file flexcan.hpp.
CAN_IFLAG1_22
constexpr unsigned long uavcan_kinetis::flexcan::CAN_IFLAG1_22 = (1U << 22)
Definition at line 538 of file flexcan.hpp.
CAN_IFLAG1_23
constexpr unsigned long uavcan_kinetis::flexcan::CAN_IFLAG1_23 = (1U << 23)
Definition at line 539 of file flexcan.hpp.
CAN_IFLAG1_24
constexpr unsigned long uavcan_kinetis::flexcan::CAN_IFLAG1_24 = (1U << 24)
Definition at line 540 of file flexcan.hpp.
CAN_IFLAG1_25
constexpr unsigned long uavcan_kinetis::flexcan::CAN_IFLAG1_25 = (1U << 25)
Definition at line 541 of file flexcan.hpp.
CAN_IFLAG1_26
constexpr unsigned long uavcan_kinetis::flexcan::CAN_IFLAG1_26 = (1U << 26)
Definition at line 542 of file flexcan.hpp.
CAN_IFLAG1_27
constexpr unsigned long uavcan_kinetis::flexcan::CAN_IFLAG1_27 = (1U << 27)
Definition at line 543 of file flexcan.hpp.
CAN_IFLAG1_28
constexpr unsigned long uavcan_kinetis::flexcan::CAN_IFLAG1_28 = (1U << 28)
Definition at line 544 of file flexcan.hpp.
CAN_IFLAG1_29
constexpr unsigned long uavcan_kinetis::flexcan::CAN_IFLAG1_29 = (1U << 29)
Definition at line 545 of file flexcan.hpp.
CAN_IFLAG1_3
constexpr unsigned long uavcan_kinetis::flexcan::CAN_IFLAG1_3 = (1U << 3)
Definition at line 516 of file flexcan.hpp.
CAN_IFLAG1_30
constexpr unsigned long uavcan_kinetis::flexcan::CAN_IFLAG1_30 = (1U << 30)
Definition at line 546 of file flexcan.hpp.
CAN_IFLAG1_31
constexpr unsigned long uavcan_kinetis::flexcan::CAN_IFLAG1_31 = (1U << 31)
Definition at line 547 of file flexcan.hpp.
CAN_IFLAG1_4
constexpr unsigned long uavcan_kinetis::flexcan::CAN_IFLAG1_4 = (1U << 4)
Definition at line 517 of file flexcan.hpp.
CAN_IFLAG1_5
constexpr unsigned long uavcan_kinetis::flexcan::CAN_IFLAG1_5 = (1U << 5)
Definition at line 518 of file flexcan.hpp.
CAN_IFLAG1_6
constexpr unsigned long uavcan_kinetis::flexcan::CAN_IFLAG1_6 = (1U << 6)
Definition at line 520 of file flexcan.hpp.
CAN_IFLAG1_7
constexpr unsigned long uavcan_kinetis::flexcan::CAN_IFLAG1_7 = (1U << 7)
Definition at line 522 of file flexcan.hpp.
CAN_IFLAG1_8
constexpr unsigned long uavcan_kinetis::flexcan::CAN_IFLAG1_8 = (1U << 8)
Definition at line 524 of file flexcan.hpp.
CAN_IFLAG1_9
constexpr unsigned long uavcan_kinetis::flexcan::CAN_IFLAG1_9 = (1U << 9)
Definition at line 525 of file flexcan.hpp.
CAN_IFLAG2_0
constexpr unsigned long uavcan_kinetis::flexcan::CAN_IFLAG2_0 = (1U << 0)
Definition at line 478 of file flexcan.hpp.
CAN_IFLAG2_1
constexpr unsigned long uavcan_kinetis::flexcan::CAN_IFLAG2_1 = (1U << 1)
Definition at line 479 of file flexcan.hpp.
CAN_IFLAG2_10
constexpr unsigned long uavcan_kinetis::flexcan::CAN_IFLAG2_10 = (1U << 10)
Definition at line 488 of file flexcan.hpp.
CAN_IFLAG2_11
constexpr unsigned long uavcan_kinetis::flexcan::CAN_IFLAG2_11 = (1U << 11)
Definition at line 489 of file flexcan.hpp.
CAN_IFLAG2_12
constexpr unsigned long uavcan_kinetis::flexcan::CAN_IFLAG2_12 = (1U << 12)
Definition at line 490 of file flexcan.hpp.
CAN_IFLAG2_13
constexpr unsigned long uavcan_kinetis::flexcan::CAN_IFLAG2_13 = (1U << 13)
Definition at line 491 of file flexcan.hpp.
CAN_IFLAG2_14
constexpr unsigned long uavcan_kinetis::flexcan::CAN_IFLAG2_14 = (1U << 14)
Definition at line 492 of file flexcan.hpp.
CAN_IFLAG2_15
constexpr unsigned long uavcan_kinetis::flexcan::CAN_IFLAG2_15 = (1U << 15)
Definition at line 493 of file flexcan.hpp.
CAN_IFLAG2_16
constexpr unsigned long uavcan_kinetis::flexcan::CAN_IFLAG2_16 = (1U << 16)
Definition at line 494 of file flexcan.hpp.
CAN_IFLAG2_17
constexpr unsigned long uavcan_kinetis::flexcan::CAN_IFLAG2_17 = (1U << 17)
Definition at line 495 of file flexcan.hpp.
CAN_IFLAG2_18
constexpr unsigned long uavcan_kinetis::flexcan::CAN_IFLAG2_18 = (1U << 18)
Definition at line 496 of file flexcan.hpp.
CAN_IFLAG2_19
constexpr unsigned long uavcan_kinetis::flexcan::CAN_IFLAG2_19 = (1U << 19)
Definition at line 497 of file flexcan.hpp.
CAN_IFLAG2_2
constexpr unsigned long uavcan_kinetis::flexcan::CAN_IFLAG2_2 = (1U << 2)
Definition at line 480 of file flexcan.hpp.
CAN_IFLAG2_20
constexpr unsigned long uavcan_kinetis::flexcan::CAN_IFLAG2_20 = (1U << 20)
Definition at line 498 of file flexcan.hpp.
CAN_IFLAG2_21
constexpr unsigned long uavcan_kinetis::flexcan::CAN_IFLAG2_21 = (1U << 21)
Definition at line 499 of file flexcan.hpp.
CAN_IFLAG2_22
constexpr unsigned long uavcan_kinetis::flexcan::CAN_IFLAG2_22 = (1U << 22)
Definition at line 500 of file flexcan.hpp.
CAN_IFLAG2_23
constexpr unsigned long uavcan_kinetis::flexcan::CAN_IFLAG2_23 = (1U << 23)
Definition at line 501 of file flexcan.hpp.
CAN_IFLAG2_24
constexpr unsigned long uavcan_kinetis::flexcan::CAN_IFLAG2_24 = (1U << 24)
Definition at line 502 of file flexcan.hpp.
CAN_IFLAG2_25
constexpr unsigned long uavcan_kinetis::flexcan::CAN_IFLAG2_25 = (1U << 25)
Definition at line 503 of file flexcan.hpp.
CAN_IFLAG2_26
constexpr unsigned long uavcan_kinetis::flexcan::CAN_IFLAG2_26 = (1U << 26)
Definition at line 504 of file flexcan.hpp.
CAN_IFLAG2_27
constexpr unsigned long uavcan_kinetis::flexcan::CAN_IFLAG2_27 = (1U << 27)
Definition at line 505 of file flexcan.hpp.
CAN_IFLAG2_28
constexpr unsigned long uavcan_kinetis::flexcan::CAN_IFLAG2_28 = (1U << 28)
Definition at line 506 of file flexcan.hpp.
CAN_IFLAG2_29
constexpr unsigned long uavcan_kinetis::flexcan::CAN_IFLAG2_29 = (1U << 29)
Definition at line 507 of file flexcan.hpp.
CAN_IFLAG2_3
constexpr unsigned long uavcan_kinetis::flexcan::CAN_IFLAG2_3 = (1U << 3)
Definition at line 481 of file flexcan.hpp.
CAN_IFLAG2_30
constexpr unsigned long uavcan_kinetis::flexcan::CAN_IFLAG2_30 = (1U << 30)
Definition at line 508 of file flexcan.hpp.
CAN_IFLAG2_31
constexpr unsigned long uavcan_kinetis::flexcan::CAN_IFLAG2_31 = (1U << 31)
Definition at line 509 of file flexcan.hpp.
CAN_IFLAG2_4
constexpr unsigned long uavcan_kinetis::flexcan::CAN_IFLAG2_4 = (1U << 4)
Definition at line 482 of file flexcan.hpp.
CAN_IFLAG2_5
constexpr unsigned long uavcan_kinetis::flexcan::CAN_IFLAG2_5 = (1U << 5)
Definition at line 483 of file flexcan.hpp.
CAN_IFLAG2_6
constexpr unsigned long uavcan_kinetis::flexcan::CAN_IFLAG2_6 = (1U << 6)
Definition at line 484 of file flexcan.hpp.
CAN_IFLAG2_7
constexpr unsigned long uavcan_kinetis::flexcan::CAN_IFLAG2_7 = (1U << 7)
Definition at line 485 of file flexcan.hpp.
CAN_IFLAG2_8
constexpr unsigned long uavcan_kinetis::flexcan::CAN_IFLAG2_8 = (1U << 8)
Definition at line 486 of file flexcan.hpp.
CAN_IFLAG2_9
constexpr unsigned long uavcan_kinetis::flexcan::CAN_IFLAG2_9 = (1U << 9)
Definition at line 487 of file flexcan.hpp.
CAN_IMASK1_0
constexpr unsigned long uavcan_kinetis::flexcan::CAN_IMASK1_0 = (1U << 0)
Definition at line 443 of file flexcan.hpp.
CAN_IMASK1_1
constexpr unsigned long uavcan_kinetis::flexcan::CAN_IMASK1_1 = (1U << 1)
Definition at line 444 of file flexcan.hpp.
CAN_IMASK1_10
constexpr unsigned long uavcan_kinetis::flexcan::CAN_IMASK1_10 = (1U << 10)
Definition at line 453 of file flexcan.hpp.
CAN_IMASK1_11
constexpr unsigned long uavcan_kinetis::flexcan::CAN_IMASK1_11 = (1U << 11)
Definition at line 454 of file flexcan.hpp.
CAN_IMASK1_12
constexpr unsigned long uavcan_kinetis::flexcan::CAN_IMASK1_12 = (1U << 12)
Definition at line 455 of file flexcan.hpp.
CAN_IMASK1_13
constexpr unsigned long uavcan_kinetis::flexcan::CAN_IMASK1_13 = (1U << 13)
Definition at line 456 of file flexcan.hpp.
CAN_IMASK1_14
constexpr unsigned long uavcan_kinetis::flexcan::CAN_IMASK1_14 = (1U << 14)
Definition at line 457 of file flexcan.hpp.
CAN_IMASK1_15
constexpr unsigned long uavcan_kinetis::flexcan::CAN_IMASK1_15 = (1U << 15)
Definition at line 458 of file flexcan.hpp.
CAN_IMASK1_16
constexpr unsigned long uavcan_kinetis::flexcan::CAN_IMASK1_16 = (1U << 16)
Definition at line 459 of file flexcan.hpp.
CAN_IMASK1_17
constexpr unsigned long uavcan_kinetis::flexcan::CAN_IMASK1_17 = (1U << 17)
Definition at line 460 of file flexcan.hpp.
CAN_IMASK1_18
constexpr unsigned long uavcan_kinetis::flexcan::CAN_IMASK1_18 = (1U << 18)
Definition at line 461 of file flexcan.hpp.
CAN_IMASK1_19
constexpr unsigned long uavcan_kinetis::flexcan::CAN_IMASK1_19 = (1U << 19)
Definition at line 462 of file flexcan.hpp.
CAN_IMASK1_2
constexpr unsigned long uavcan_kinetis::flexcan::CAN_IMASK1_2 = (1U << 2)
Definition at line 445 of file flexcan.hpp.
CAN_IMASK1_20
constexpr unsigned long uavcan_kinetis::flexcan::CAN_IMASK1_20 = (1U << 20)
Definition at line 463 of file flexcan.hpp.
CAN_IMASK1_21
constexpr unsigned long uavcan_kinetis::flexcan::CAN_IMASK1_21 = (1U << 21)
Definition at line 464 of file flexcan.hpp.
CAN_IMASK1_22
constexpr unsigned long uavcan_kinetis::flexcan::CAN_IMASK1_22 = (1U << 22)
Definition at line 465 of file flexcan.hpp.
CAN_IMASK1_23
constexpr unsigned long uavcan_kinetis::flexcan::CAN_IMASK1_23 = (1U << 23)
Definition at line 466 of file flexcan.hpp.
CAN_IMASK1_24
constexpr unsigned long uavcan_kinetis::flexcan::CAN_IMASK1_24 = (1U << 24)
Definition at line 467 of file flexcan.hpp.
CAN_IMASK1_25
constexpr unsigned long uavcan_kinetis::flexcan::CAN_IMASK1_25 = (1U << 25)
Definition at line 468 of file flexcan.hpp.
CAN_IMASK1_26
constexpr unsigned long uavcan_kinetis::flexcan::CAN_IMASK1_26 = (1U << 26)
Definition at line 469 of file flexcan.hpp.
CAN_IMASK1_27
constexpr unsigned long uavcan_kinetis::flexcan::CAN_IMASK1_27 = (1U << 27)
Definition at line 470 of file flexcan.hpp.
CAN_IMASK1_28
constexpr unsigned long uavcan_kinetis::flexcan::CAN_IMASK1_28 = (1U << 28)
Definition at line 471 of file flexcan.hpp.
CAN_IMASK1_29
constexpr unsigned long uavcan_kinetis::flexcan::CAN_IMASK1_29 = (1U << 29)
Definition at line 472 of file flexcan.hpp.
CAN_IMASK1_3
constexpr unsigned long uavcan_kinetis::flexcan::CAN_IMASK1_3 = (1U << 3)
Definition at line 446 of file flexcan.hpp.
CAN_IMASK1_30
constexpr unsigned long uavcan_kinetis::flexcan::CAN_IMASK1_30 = (1U << 30)
Definition at line 473 of file flexcan.hpp.
CAN_IMASK1_31
constexpr unsigned long uavcan_kinetis::flexcan::CAN_IMASK1_31 = (1U << 31)
Definition at line 474 of file flexcan.hpp.
CAN_IMASK1_4
constexpr unsigned long uavcan_kinetis::flexcan::CAN_IMASK1_4 = (1U << 4)
Definition at line 447 of file flexcan.hpp.
CAN_IMASK1_5
constexpr unsigned long uavcan_kinetis::flexcan::CAN_IMASK1_5 = (1U << 5)
Definition at line 448 of file flexcan.hpp.
CAN_IMASK1_6
constexpr unsigned long uavcan_kinetis::flexcan::CAN_IMASK1_6 = (1U << 6)
Definition at line 449 of file flexcan.hpp.
CAN_IMASK1_7
constexpr unsigned long uavcan_kinetis::flexcan::CAN_IMASK1_7 = (1U << 7)
Definition at line 450 of file flexcan.hpp.
CAN_IMASK1_8
constexpr unsigned long uavcan_kinetis::flexcan::CAN_IMASK1_8 = (1U << 8)
Definition at line 451 of file flexcan.hpp.
CAN_IMASK1_9
constexpr unsigned long uavcan_kinetis::flexcan::CAN_IMASK1_9 = (1U << 9)
Definition at line 452 of file flexcan.hpp.
CAN_IMASK2_0
constexpr unsigned long uavcan_kinetis::flexcan::CAN_IMASK2_0 = (1U << 0)
Definition at line 408 of file flexcan.hpp.
CAN_IMASK2_1
constexpr unsigned long uavcan_kinetis::flexcan::CAN_IMASK2_1 = (1U << 1)
Definition at line 409 of file flexcan.hpp.
CAN_IMASK2_10
constexpr unsigned long uavcan_kinetis::flexcan::CAN_IMASK2_10 = (1U << 10)
Definition at line 418 of file flexcan.hpp.
CAN_IMASK2_11
constexpr unsigned long uavcan_kinetis::flexcan::CAN_IMASK2_11 = (1U << 11)
Definition at line 419 of file flexcan.hpp.
CAN_IMASK2_12
constexpr unsigned long uavcan_kinetis::flexcan::CAN_IMASK2_12 = (1U << 12)
Definition at line 420 of file flexcan.hpp.
CAN_IMASK2_13
constexpr unsigned long uavcan_kinetis::flexcan::CAN_IMASK2_13 = (1U << 13)
Definition at line 421 of file flexcan.hpp.
CAN_IMASK2_14
constexpr unsigned long uavcan_kinetis::flexcan::CAN_IMASK2_14 = (1U << 14)
Definition at line 422 of file flexcan.hpp.
CAN_IMASK2_15
constexpr unsigned long uavcan_kinetis::flexcan::CAN_IMASK2_15 = (1U << 15)
Definition at line 423 of file flexcan.hpp.
CAN_IMASK2_16
constexpr unsigned long uavcan_kinetis::flexcan::CAN_IMASK2_16 = (1U << 16)
Definition at line 424 of file flexcan.hpp.
CAN_IMASK2_17
constexpr unsigned long uavcan_kinetis::flexcan::CAN_IMASK2_17 = (1U << 17)
Definition at line 425 of file flexcan.hpp.
CAN_IMASK2_18
constexpr unsigned long uavcan_kinetis::flexcan::CAN_IMASK2_18 = (1U << 18)
Definition at line 426 of file flexcan.hpp.
CAN_IMASK2_19
constexpr unsigned long uavcan_kinetis::flexcan::CAN_IMASK2_19 = (1U << 19)
Definition at line 427 of file flexcan.hpp.
CAN_IMASK2_2
constexpr unsigned long uavcan_kinetis::flexcan::CAN_IMASK2_2 = (1U << 2)
Definition at line 410 of file flexcan.hpp.
CAN_IMASK2_20
constexpr unsigned long uavcan_kinetis::flexcan::CAN_IMASK2_20 = (1U << 20)
Definition at line 428 of file flexcan.hpp.
CAN_IMASK2_21
constexpr unsigned long uavcan_kinetis::flexcan::CAN_IMASK2_21 = (1U << 21)
Definition at line 429 of file flexcan.hpp.
CAN_IMASK2_22
constexpr unsigned long uavcan_kinetis::flexcan::CAN_IMASK2_22 = (1U << 22)
Definition at line 430 of file flexcan.hpp.
CAN_IMASK2_23
constexpr unsigned long uavcan_kinetis::flexcan::CAN_IMASK2_23 = (1U << 23)
Definition at line 431 of file flexcan.hpp.
CAN_IMASK2_24
constexpr unsigned long uavcan_kinetis::flexcan::CAN_IMASK2_24 = (1U << 24)
Definition at line 432 of file flexcan.hpp.
CAN_IMASK2_25
constexpr unsigned long uavcan_kinetis::flexcan::CAN_IMASK2_25 = (1U << 25)
Definition at line 433 of file flexcan.hpp.
CAN_IMASK2_26
constexpr unsigned long uavcan_kinetis::flexcan::CAN_IMASK2_26 = (1U << 26)
Definition at line 434 of file flexcan.hpp.
CAN_IMASK2_27
constexpr unsigned long uavcan_kinetis::flexcan::CAN_IMASK2_27 = (1U << 27)
Definition at line 435 of file flexcan.hpp.
CAN_IMASK2_28
constexpr unsigned long uavcan_kinetis::flexcan::CAN_IMASK2_28 = (1U << 28)
Definition at line 436 of file flexcan.hpp.
CAN_IMASK2_29
constexpr unsigned long uavcan_kinetis::flexcan::CAN_IMASK2_29 = (1U << 29)
Definition at line 437 of file flexcan.hpp.
CAN_IMASK2_3
constexpr unsigned long uavcan_kinetis::flexcan::CAN_IMASK2_3 = (1U << 3)
Definition at line 411 of file flexcan.hpp.
CAN_IMASK2_30
constexpr unsigned long uavcan_kinetis::flexcan::CAN_IMASK2_30 = (1U << 30)
Definition at line 438 of file flexcan.hpp.
CAN_IMASK2_31
constexpr unsigned long uavcan_kinetis::flexcan::CAN_IMASK2_31 = (1U << 31)
Definition at line 439 of file flexcan.hpp.
CAN_IMASK2_4
constexpr unsigned long uavcan_kinetis::flexcan::CAN_IMASK2_4 = (1U << 4)
Definition at line 412 of file flexcan.hpp.
CAN_IMASK2_5
constexpr unsigned long uavcan_kinetis::flexcan::CAN_IMASK2_5 = (1U << 5)
Definition at line 413 of file flexcan.hpp.
CAN_IMASK2_6
constexpr unsigned long uavcan_kinetis::flexcan::CAN_IMASK2_6 = (1U << 6)
Definition at line 414 of file flexcan.hpp.
CAN_IMASK2_7
constexpr unsigned long uavcan_kinetis::flexcan::CAN_IMASK2_7 = (1U << 7)
Definition at line 415 of file flexcan.hpp.
CAN_IMASK2_8
constexpr unsigned long uavcan_kinetis::flexcan::CAN_IMASK2_8 = (1U << 8)
Definition at line 416 of file flexcan.hpp.
CAN_IMASK2_9
constexpr unsigned long uavcan_kinetis::flexcan::CAN_IMASK2_9 = (1U << 9)
Definition at line 417 of file flexcan.hpp.
canclk
const uavcan::uint32_t uavcan_kinetis::flexcan::canclk = CLOCKSEL ? busclck : OSCERCLK
Definition at line 34 of file uc_kinetis_flexcan.cpp.
Referenced by uavcan_kinetis::CanIface::computeTimings(), and uavcan_kinetis::CanIface::doReset().
CLOCKSEL
const uavcan::uint8_t uavcan_kinetis::flexcan::CLOCKSEL = 0
Definition at line 33 of file uc_kinetis_flexcan.cpp.
Referenced by uavcan_kinetis::CanIface::init().
CRCR_MBCRC_MASK
constexpr unsigned long uavcan_kinetis::flexcan::CRCR_MBCRC_MASK = (0x7fU << CRCR_MBCRC_SHIFT)
Definition at line 593 of file flexcan.hpp.
CRCR_MBCRC_SHIFT
constexpr unsigned long uavcan_kinetis::flexcan::CRCR_MBCRC_SHIFT = (16)
Definition at line 592 of file flexcan.hpp.
CRCR_TXCRC_MASK
constexpr unsigned long uavcan_kinetis::flexcan::CRCR_TXCRC_MASK = (0x7fffU << CRCR_TXCRC_SHIFT)
Definition at line 589 of file flexcan.hpp.
CRCR_TXCRC_SHIFT
constexpr unsigned long uavcan_kinetis::flexcan::CRCR_TXCRC_SHIFT = (0U)
Definition at line 588 of file flexcan.hpp.
CTRL1_BOFFMSK
constexpr unsigned long uavcan_kinetis::flexcan::CTRL1_BOFFMSK = (1U << 15)
Definition at line 253 of file flexcan.hpp.
CTRL1_BOFFREC
constexpr unsigned long uavcan_kinetis::flexcan::CTRL1_BOFFREC = (1U << 6)
Definition at line 245 of file flexcan.hpp.
CTRL1_CLKSRC
constexpr unsigned long uavcan_kinetis::flexcan::CTRL1_CLKSRC = (1U << 13)
Definition at line 251 of file flexcan.hpp.
Referenced by uavcan_kinetis::CanIface::init().
CTRL1_ERRMSK
constexpr unsigned long uavcan_kinetis::flexcan::CTRL1_ERRMSK = (1U << 14)
Definition at line 252 of file flexcan.hpp.
Referenced by uavcan_kinetis::CanIface::init().
CTRL1_LBUF
constexpr unsigned long uavcan_kinetis::flexcan::CTRL1_LBUF = (1U << 4)
Definition at line 243 of file flexcan.hpp.
CTRL1_LOM
constexpr unsigned long uavcan_kinetis::flexcan::CTRL1_LOM = (1U << 3)
Definition at line 242 of file flexcan.hpp.
Referenced by uavcan_kinetis::CanIface::init().
CTRL1_LPB
constexpr unsigned long uavcan_kinetis::flexcan::CTRL1_LPB = (1U << 12)
Definition at line 250 of file flexcan.hpp.
CTRL1_PRESDIV_MASK
constexpr unsigned long uavcan_kinetis::flexcan::CTRL1_PRESDIV_MASK = (0xff << CTRL1_PRESDIV_SHIFT)
Definition at line 261 of file flexcan.hpp.
CTRL1_PRESDIV_SHIFT
constexpr unsigned long uavcan_kinetis::flexcan::CTRL1_PRESDIV_SHIFT = (24)
Definition at line 260 of file flexcan.hpp.
Referenced by uavcan_kinetis::CanIface::init().
CTRL1_PSEG1_MASK
constexpr unsigned long uavcan_kinetis::flexcan::CTRL1_PSEG1_MASK = (7U << CTRL1_PSEG1_SHIFT)
Definition at line 257 of file flexcan.hpp.
CTRL1_PSEG1_SHIFT
constexpr unsigned long uavcan_kinetis::flexcan::CTRL1_PSEG1_SHIFT = (19)
Definition at line 256 of file flexcan.hpp.
Referenced by uavcan_kinetis::CanIface::init().
CTRL1_PSEG2_MASK
constexpr unsigned long uavcan_kinetis::flexcan::CTRL1_PSEG2_MASK = (7U << CTRL1_PSEG2_SHIFT)
Definition at line 255 of file flexcan.hpp.
CTRL1_PSEG2_SHIFT
constexpr unsigned long uavcan_kinetis::flexcan::CTRL1_PSEG2_SHIFT = (16)
Definition at line 254 of file flexcan.hpp.
Referenced by uavcan_kinetis::CanIface::init().
CTRL1_RJW_MASK
constexpr unsigned long uavcan_kinetis::flexcan::CTRL1_RJW_MASK = (3U << CTRL1_RJW_SHIFT)
Definition at line 259 of file flexcan.hpp.
CTRL1_RJW_SHIFT
constexpr unsigned long uavcan_kinetis::flexcan::CTRL1_RJW_SHIFT = (22)
Definition at line 258 of file flexcan.hpp.
Referenced by uavcan_kinetis::CanIface::init().
CTRL1_ROPSEG_MASK
constexpr unsigned long uavcan_kinetis::flexcan::CTRL1_ROPSEG_MASK = (7U << CTRL1_ROPSEG_SHIFT)
Definition at line 241 of file flexcan.hpp.
CTRL1_ROPSEG_SHIFT
constexpr unsigned long uavcan_kinetis::flexcan::CTRL1_ROPSEG_SHIFT = (0)
Definition at line 240 of file flexcan.hpp.
Referenced by uavcan_kinetis::CanIface::init().
CTRL1_RWRNMSK
constexpr unsigned long uavcan_kinetis::flexcan::CTRL1_RWRNMSK = (1U << 10)
Definition at line 248 of file flexcan.hpp.
Referenced by uavcan_kinetis::CanIface::init().
CTRL1_SMP
constexpr unsigned long uavcan_kinetis::flexcan::CTRL1_SMP = (1U << 7)
Definition at line 246 of file flexcan.hpp.
CTRL1_TSYN
constexpr unsigned long uavcan_kinetis::flexcan::CTRL1_TSYN = (1U << 5)
Definition at line 244 of file flexcan.hpp.
CTRL1_TWRNMSK
constexpr unsigned long uavcan_kinetis::flexcan::CTRL1_TWRNMSK = (1U << 11)
Definition at line 249 of file flexcan.hpp.
Referenced by uavcan_kinetis::CanIface::init().
CTRL2_EACEN
constexpr unsigned long uavcan_kinetis::flexcan::CTRL2_EACEN = (1U << 16)
Definition at line 551 of file flexcan.hpp.
Referenced by uavcan_kinetis::CanIface::doReset().
CTRL2_MRP
constexpr unsigned long uavcan_kinetis::flexcan::CTRL2_MRP = (1U << 18)
Definition at line 554 of file flexcan.hpp.
CTRL2_RFFN_SHIFT
constexpr unsigned long uavcan_kinetis::flexcan::CTRL2_RFFN_SHIFT = (24)
Definition at line 557 of file flexcan.hpp.
CTRL2_RRS
constexpr unsigned long uavcan_kinetis::flexcan::CTRL2_RRS = (1U << 17)
Definition at line 553 of file flexcan.hpp.
Referenced by uavcan_kinetis::CanIface::doReset().
CTRL2_TASD_MASK
constexpr unsigned long uavcan_kinetis::flexcan::CTRL2_TASD_MASK = (31U << CTRL2_TASD_SHIFT)
Definition at line 556 of file flexcan.hpp.
Referenced by uavcan_kinetis::CanIface::doReset().
CTRL2_TASD_SHIFT
constexpr unsigned long uavcan_kinetis::flexcan::CTRL2_TASD_SHIFT = (19)
Definition at line 555 of file flexcan.hpp.
Referenced by uavcan_kinetis::CanIface::doReset().
CTRL2_WRMFRZ
constexpr unsigned long uavcan_kinetis::flexcan::CTRL2_WRMFRZ = (1U << 28U)
Definition at line 575 of file flexcan.hpp.
ECR_RXERRCNT_MASK
constexpr unsigned long uavcan_kinetis::flexcan::ECR_RXERRCNT_MASK = (0xff << ECR_RXERRCNT_SHIFT)
Definition at line 378 of file flexcan.hpp.
ECR_RXERRCNT_SHIFT
constexpr unsigned long uavcan_kinetis::flexcan::ECR_RXERRCNT_SHIFT = (8)
Definition at line 377 of file flexcan.hpp.
ECR_TXERRCNT_MASK
constexpr unsigned long uavcan_kinetis::flexcan::ECR_TXERRCNT_MASK = (0xff << ECR_TXERRCNT_SHIFT)
Definition at line 376 of file flexcan.hpp.
ECR_TXERRCNT_SHIFT
constexpr unsigned long uavcan_kinetis::flexcan::ECR_TXERRCNT_SHIFT = (0U)
Definition at line 375 of file flexcan.hpp.
ESR1_ACKERR
constexpr unsigned long uavcan_kinetis::flexcan::ESR1_ACKERR = (1U << 13)
Definition at line 399 of file flexcan.hpp.
Referenced by uavcan_kinetis::CanIface::pollErrorFlagsFromISR().
ESR1_BIT0ERR
constexpr unsigned long uavcan_kinetis::flexcan::ESR1_BIT0ERR = (1U << 14)
Definition at line 400 of file flexcan.hpp.
Referenced by uavcan_kinetis::CanIface::pollErrorFlagsFromISR().
ESR1_BIT1ERR
constexpr unsigned long uavcan_kinetis::flexcan::ESR1_BIT1ERR = (1U << 15)
Definition at line 401 of file flexcan.hpp.
Referenced by uavcan_kinetis::CanIface::pollErrorFlagsFromISR().
ESR1_BOFFINT
constexpr unsigned long uavcan_kinetis::flexcan::ESR1_BOFFINT = (1U << 2)
Definition at line 385 of file flexcan.hpp.
ESR1_CRCERR
constexpr unsigned long uavcan_kinetis::flexcan::ESR1_CRCERR = (1U << 12)
Definition at line 398 of file flexcan.hpp.
Referenced by uavcan_kinetis::CanIface::pollErrorFlagsFromISR().
ESR1_ERRINT
constexpr unsigned long uavcan_kinetis::flexcan::ESR1_ERRINT = (1U << 1)
Definition at line 384 of file flexcan.hpp.
ESR1_FLTCONF_ACTV
constexpr unsigned long uavcan_kinetis::flexcan::ESR1_FLTCONF_ACTV = (0U << ESR1_FLTCONF_SHIFT)
Definition at line 389 of file flexcan.hpp.
ESR1_FLTCONF_MASK
constexpr unsigned long uavcan_kinetis::flexcan::ESR1_FLTCONF_MASK = (3U << ESR1_FLTCONF_SHIFT)
Definition at line 388 of file flexcan.hpp.
ESR1_FLTCONF_OFF
constexpr unsigned long uavcan_kinetis::flexcan::ESR1_FLTCONF_OFF = (2U << ESR1_FLTCONF_SHIFT)
Definition at line 391 of file flexcan.hpp.
ESR1_FLTCONF_PASV
constexpr unsigned long uavcan_kinetis::flexcan::ESR1_FLTCONF_PASV = (1U << ESR1_FLTCONF_SHIFT)
Definition at line 390 of file flexcan.hpp.
ESR1_FLTCONF_SHIFT
constexpr unsigned long uavcan_kinetis::flexcan::ESR1_FLTCONF_SHIFT = (4U)
Definition at line 387 of file flexcan.hpp.
ESR1_FRMERR
constexpr unsigned long uavcan_kinetis::flexcan::ESR1_FRMERR = (1U << 11)
Definition at line 397 of file flexcan.hpp.
Referenced by uavcan_kinetis::CanIface::pollErrorFlagsFromISR().
ESR1_IDLE
constexpr unsigned long uavcan_kinetis::flexcan::ESR1_IDLE = (1U << 7)
Definition at line 393 of file flexcan.hpp.
ESR1_RWRNINT
constexpr unsigned long uavcan_kinetis::flexcan::ESR1_RWRNINT = (1U << 16)
Definition at line 402 of file flexcan.hpp.
ESR1_RX
constexpr unsigned long uavcan_kinetis::flexcan::ESR1_RX = (1U << 3)
Definition at line 386 of file flexcan.hpp.
ESR1_RXWRN
constexpr unsigned long uavcan_kinetis::flexcan::ESR1_RXWRN = (1U << 8)
Definition at line 394 of file flexcan.hpp.
ESR1_STFERR
constexpr unsigned long uavcan_kinetis::flexcan::ESR1_STFERR = (1U << 10)
Definition at line 396 of file flexcan.hpp.
Referenced by uavcan_kinetis::CanIface::pollErrorFlagsFromISR().
ESR1_SYNCH
constexpr unsigned long uavcan_kinetis::flexcan::ESR1_SYNCH = (1U << 18)
Definition at line 404 of file flexcan.hpp.
ESR1_TWRNINT
constexpr unsigned long uavcan_kinetis::flexcan::ESR1_TWRNINT = (1U << 17)
Definition at line 403 of file flexcan.hpp.
ESR1_TX
constexpr unsigned long uavcan_kinetis::flexcan::ESR1_TX = (1U << 6)
Definition at line 392 of file flexcan.hpp.
ESR1_TXWRN
constexpr unsigned long uavcan_kinetis::flexcan::ESR1_TXWRN = (1U << 9)
Definition at line 395 of file flexcan.hpp.
ESR1_WAKINT
constexpr unsigned long uavcan_kinetis::flexcan::ESR1_WAKINT = (1U << 0)
Definition at line 383 of file flexcan.hpp.
ESR2_IMB
constexpr unsigned long uavcan_kinetis::flexcan::ESR2_IMB = (1U << 13)
Definition at line 580 of file flexcan.hpp.
Referenced by uavcan_kinetis::CanIface::canAcceptNewTxFrame(), and uavcan_kinetis::CanIface::send().
ESR2_LPTM_MASK
constexpr unsigned long uavcan_kinetis::flexcan::ESR2_LPTM_MASK = (0x7fU << ESR2_LPTM_SHIFT)
Definition at line 584 of file flexcan.hpp.
Referenced by uavcan_kinetis::CanIface::send().
ESR2_LPTM_SHIFT
constexpr unsigned long uavcan_kinetis::flexcan::ESR2_LPTM_SHIFT = (16)
Definition at line 583 of file flexcan.hpp.
Referenced by uavcan_kinetis::CanIface::send().
ESR2_VPS
constexpr unsigned long uavcan_kinetis::flexcan::ESR2_VPS = (1U << 14)
Definition at line 581 of file flexcan.hpp.
Referenced by uavcan_kinetis::CanIface::canAcceptNewTxFrame(), and uavcan_kinetis::CanIface::send().
MCR_AEN
constexpr unsigned long uavcan_kinetis::flexcan::MCR_AEN = (1U << 12)
Definition at line 218 of file flexcan.hpp.
Referenced by uavcan_kinetis::CanIface::doReset().
MCR_FRZ
constexpr unsigned long uavcan_kinetis::flexcan::MCR_FRZ = (1U << 30)
Definition at line 235 of file flexcan.hpp.
Referenced by uavcan_kinetis::CanIface::setFreeze().
MCR_FRZACK
constexpr unsigned long uavcan_kinetis::flexcan::MCR_FRZACK = (1U << 24)
Definition at line 229 of file flexcan.hpp.
Referenced by uavcan_kinetis::CanIface::waitFreezeAckChange().
MCR_HALT
constexpr unsigned long uavcan_kinetis::flexcan::MCR_HALT = (1U << 28)
Definition at line 233 of file flexcan.hpp.
Referenced by uavcan_kinetis::CanIface::setFreeze().
MCR_IDAM_MASK
constexpr unsigned long uavcan_kinetis::flexcan::MCR_IDAM_MASK = (3U << MCR_IDAM_SHIFT)
Definition at line 212 of file flexcan.hpp.
MCR_IDAM_SHIFT
constexpr unsigned long uavcan_kinetis::flexcan::MCR_IDAM_SHIFT = (8)
Definition at line 211 of file flexcan.hpp.
MCR_IRMQ
constexpr unsigned long uavcan_kinetis::flexcan::MCR_IRMQ = (1U << 16)
Definition at line 221 of file flexcan.hpp.
Referenced by uavcan_kinetis::CanIface::doReset().
MCR_LPMACK
constexpr unsigned long uavcan_kinetis::flexcan::MCR_LPMACK = (1U << 20)
Definition at line 225 of file flexcan.hpp.
Referenced by uavcan_kinetis::CanIface::setEnable().
MCR_LPRIOEN
constexpr unsigned long uavcan_kinetis::flexcan::MCR_LPRIOEN = (1U << 13)
Definition at line 219 of file flexcan.hpp.
MCR_MAXMB_MASK
constexpr unsigned long uavcan_kinetis::flexcan::MCR_MAXMB_MASK = (0x7fU << MCR_MAXMB_SHIFT)
Definition at line 209 of file flexcan.hpp.
Referenced by uavcan_kinetis::CanIface::doReset().
MCR_MAXMB_SHIFT
constexpr unsigned long uavcan_kinetis::flexcan::MCR_MAXMB_SHIFT = (0)
Definition at line 208 of file flexcan.hpp.
Referenced by uavcan_kinetis::CanIface::doReset().
MCR_MDIS
constexpr unsigned long uavcan_kinetis::flexcan::MCR_MDIS = (1U << 31)
Definition at line 236 of file flexcan.hpp.
Referenced by uavcan_kinetis::CanIface::setEnable().
MCR_NOTRDY
constexpr unsigned long uavcan_kinetis::flexcan::MCR_NOTRDY = (1U << 27)
Definition at line 232 of file flexcan.hpp.
MCR_RFEN
constexpr unsigned long uavcan_kinetis::flexcan::MCR_RFEN = (1U << 29)
Definition at line 234 of file flexcan.hpp.
Referenced by uavcan_kinetis::CanIface::doReset().
MCR_SLFWAK
constexpr unsigned long uavcan_kinetis::flexcan::MCR_SLFWAK = (1U << 22)
Definition at line 227 of file flexcan.hpp.
Referenced by uavcan_kinetis::CanIface::doReset().
MCR_SOFTRST
constexpr unsigned long uavcan_kinetis::flexcan::MCR_SOFTRST = (1U << 25)
Definition at line 230 of file flexcan.hpp.
Referenced by uavcan_kinetis::CanIface::doReset().
MCR_SRXDIS
constexpr unsigned long uavcan_kinetis::flexcan::MCR_SRXDIS = (1U << 17)
Definition at line 222 of file flexcan.hpp.
Referenced by uavcan_kinetis::CanIface::doReset().
MCR_SUPV
constexpr unsigned long uavcan_kinetis::flexcan::MCR_SUPV = (1U << 23)
Definition at line 228 of file flexcan.hpp.
Referenced by uavcan_kinetis::CanIface::doReset().
MCR_WAKMSK
constexpr unsigned long uavcan_kinetis::flexcan::MCR_WAKMSK = (1U << 26)
Definition at line 231 of file flexcan.hpp.
MCR_WAKSRC
constexpr unsigned long uavcan_kinetis::flexcan::MCR_WAKSRC = (1U << 19)
Definition at line 224 of file flexcan.hpp.
Referenced by uavcan_kinetis::CanIface::doReset().
MCR_WRNEN
constexpr unsigned long uavcan_kinetis::flexcan::MCR_WRNEN = (1U << 21)
Definition at line 226 of file flexcan.hpp.
Referenced by uavcan_kinetis::CanIface::doReset().
numberFIFOFilters
const uavcan::uint32_t uavcan_kinetis::flexcan::numberFIFOFilters = flexcan::CTRL2_RFFN_16MB
Definition at line 36 of file uc_kinetis_flexcan.cpp.
Referenced by uavcan_kinetis::CanIface::doReset().
OSCERCLK
const uavcan::uint32_t uavcan_kinetis::flexcan::OSCERCLK = BOARD_EXTAL_FREQ
Definition at line 31 of file uc_kinetis_flexcan.cpp.
RXFIR_IDHIT_MASK
constexpr unsigned long uavcan_kinetis::flexcan::RXFIR_IDHIT_MASK = (0x1ffU << RXFIR_IDHIT_SHIFT)
Definition at line 600 of file flexcan.hpp.
RXFIR_IDHIT_SHIFT
constexpr unsigned long uavcan_kinetis::flexcan::RXFIR_IDHIT_SHIFT = (0)
Definition at line 598 of file flexcan.hpp.
RXIMR0
constexpr unsigned long uavcan_kinetis::flexcan::RXIMR0 = (1U << 0)
Definition at line 604 of file flexcan.hpp.
RXIMR1
constexpr unsigned long uavcan_kinetis::flexcan::RXIMR1 = (1U << 1)
Definition at line 605 of file flexcan.hpp.
RXIMR10
constexpr unsigned long uavcan_kinetis::flexcan::RXIMR10 = (1U << 10)
Definition at line 614 of file flexcan.hpp.
RXIMR11
constexpr unsigned long uavcan_kinetis::flexcan::RXIMR11 = (1U << 11)
Definition at line 615 of file flexcan.hpp.
RXIMR12
constexpr unsigned long uavcan_kinetis::flexcan::RXIMR12 = (1U << 12)
Definition at line 616 of file flexcan.hpp.
RXIMR13
constexpr unsigned long uavcan_kinetis::flexcan::RXIMR13 = (1U << 13)
Definition at line 617 of file flexcan.hpp.
RXIMR14
constexpr unsigned long uavcan_kinetis::flexcan::RXIMR14 = (1U << 14)
Definition at line 618 of file flexcan.hpp.
RXIMR15
constexpr unsigned long uavcan_kinetis::flexcan::RXIMR15 = (1U << 15)
Definition at line 619 of file flexcan.hpp.
RXIMR16
constexpr unsigned long uavcan_kinetis::flexcan::RXIMR16 = (1U << 16)
Definition at line 620 of file flexcan.hpp.
RXIMR17
constexpr unsigned long uavcan_kinetis::flexcan::RXIMR17 = (1U << 17)
Definition at line 621 of file flexcan.hpp.
RXIMR18
constexpr unsigned long uavcan_kinetis::flexcan::RXIMR18 = (1U << 18)
Definition at line 622 of file flexcan.hpp.
RXIMR19
constexpr unsigned long uavcan_kinetis::flexcan::RXIMR19 = (1U << 19)
Definition at line 623 of file flexcan.hpp.
RXIMR2
constexpr unsigned long uavcan_kinetis::flexcan::RXIMR2 = (1U << 2)
Definition at line 606 of file flexcan.hpp.
RXIMR20
constexpr unsigned long uavcan_kinetis::flexcan::RXIMR20 = (1U << 20)
Definition at line 624 of file flexcan.hpp.
RXIMR21
constexpr unsigned long uavcan_kinetis::flexcan::RXIMR21 = (1U << 21)
Definition at line 625 of file flexcan.hpp.
RXIMR22
constexpr unsigned long uavcan_kinetis::flexcan::RXIMR22 = (1U << 22)
Definition at line 626 of file flexcan.hpp.
RXIMR23
constexpr unsigned long uavcan_kinetis::flexcan::RXIMR23 = (1U << 23)
Definition at line 627 of file flexcan.hpp.
RXIMR24
constexpr unsigned long uavcan_kinetis::flexcan::RXIMR24 = (1U << 24)
Definition at line 628 of file flexcan.hpp.
RXIMR25
constexpr unsigned long uavcan_kinetis::flexcan::RXIMR25 = (1U << 25)
Definition at line 629 of file flexcan.hpp.
RXIMR26
constexpr unsigned long uavcan_kinetis::flexcan::RXIMR26 = (1U << 26)
Definition at line 630 of file flexcan.hpp.
RXIMR27
constexpr unsigned long uavcan_kinetis::flexcan::RXIMR27 = (1U << 27)
Definition at line 631 of file flexcan.hpp.
RXIMR28
constexpr unsigned long uavcan_kinetis::flexcan::RXIMR28 = (1U << 28)
Definition at line 632 of file flexcan.hpp.
RXIMR29
constexpr unsigned long uavcan_kinetis::flexcan::RXIMR29 = (1U << 29)
Definition at line 633 of file flexcan.hpp.
RXIMR3
constexpr unsigned long uavcan_kinetis::flexcan::RXIMR3 = (1U << 3)
Definition at line 607 of file flexcan.hpp.
RXIMR30
constexpr unsigned long uavcan_kinetis::flexcan::RXIMR30 = (1U << 30)
Definition at line 634 of file flexcan.hpp.
RXIMR31
constexpr unsigned long uavcan_kinetis::flexcan::RXIMR31 = (1U << 31)
Definition at line 635 of file flexcan.hpp.
RXIMR4
constexpr unsigned long uavcan_kinetis::flexcan::RXIMR4 = (1U << 4)
Definition at line 608 of file flexcan.hpp.
RXIMR5
constexpr unsigned long uavcan_kinetis::flexcan::RXIMR5 = (1U << 5)
Definition at line 609 of file flexcan.hpp.
RXIMR6
constexpr unsigned long uavcan_kinetis::flexcan::RXIMR6 = (1U << 6)
Definition at line 610 of file flexcan.hpp.
RXIMR7
constexpr unsigned long uavcan_kinetis::flexcan::RXIMR7 = (1U << 7)
Definition at line 611 of file flexcan.hpp.
RXIMR8
constexpr unsigned long uavcan_kinetis::flexcan::RXIMR8 = (1U << 8)
Definition at line 612 of file flexcan.hpp.
RXIMR9
constexpr unsigned long uavcan_kinetis::flexcan::RXIMR9 = (1U << 9)
Definition at line 613 of file flexcan.hpp.
RXM14MASK0
constexpr unsigned long uavcan_kinetis::flexcan::RXM14MASK0 = (1U << 0)
Definition at line 305 of file flexcan.hpp.
RXM14MASK1
constexpr unsigned long uavcan_kinetis::flexcan::RXM14MASK1 = (1U << 1)
Definition at line 306 of file flexcan.hpp.
RXM14MASK10
constexpr unsigned long uavcan_kinetis::flexcan::RXM14MASK10 = (1U << 10)
Definition at line 315 of file flexcan.hpp.
RXM14MASK11
constexpr unsigned long uavcan_kinetis::flexcan::RXM14MASK11 = (1U << 11)
Definition at line 316 of file flexcan.hpp.
RXM14MASK12
constexpr unsigned long uavcan_kinetis::flexcan::RXM14MASK12 = (1U << 12)
Definition at line 317 of file flexcan.hpp.
RXM14MASK13
constexpr unsigned long uavcan_kinetis::flexcan::RXM14MASK13 = (1U << 13)
Definition at line 318 of file flexcan.hpp.
RXM14MASK14
constexpr unsigned long uavcan_kinetis::flexcan::RXM14MASK14 = (1U << 14)
Definition at line 319 of file flexcan.hpp.
RXM14MASK15
constexpr unsigned long uavcan_kinetis::flexcan::RXM14MASK15 = (1U << 15)
Definition at line 320 of file flexcan.hpp.
RXM14MASK16
constexpr unsigned long uavcan_kinetis::flexcan::RXM14MASK16 = (1U << 16)
Definition at line 321 of file flexcan.hpp.
RXM14MASK17
constexpr unsigned long uavcan_kinetis::flexcan::RXM14MASK17 = (1U << 17)
Definition at line 322 of file flexcan.hpp.
RXM14MASK18
constexpr unsigned long uavcan_kinetis::flexcan::RXM14MASK18 = (1U << 18)
Definition at line 323 of file flexcan.hpp.
RXM14MASK19
constexpr unsigned long uavcan_kinetis::flexcan::RXM14MASK19 = (1U << 19)
Definition at line 324 of file flexcan.hpp.
RXM14MASK2
constexpr unsigned long uavcan_kinetis::flexcan::RXM14MASK2 = (1U << 2)
Definition at line 307 of file flexcan.hpp.
RXM14MASK20
constexpr unsigned long uavcan_kinetis::flexcan::RXM14MASK20 = (1U << 20)
Definition at line 325 of file flexcan.hpp.
RXM14MASK21
constexpr unsigned long uavcan_kinetis::flexcan::RXM14MASK21 = (1U << 21)
Definition at line 326 of file flexcan.hpp.
RXM14MASK22
constexpr unsigned long uavcan_kinetis::flexcan::RXM14MASK22 = (1U << 22)
Definition at line 327 of file flexcan.hpp.
RXM14MASK23
constexpr unsigned long uavcan_kinetis::flexcan::RXM14MASK23 = (1U << 23)
Definition at line 328 of file flexcan.hpp.
RXM14MASK24
constexpr unsigned long uavcan_kinetis::flexcan::RXM14MASK24 = (1U << 24)
Definition at line 329 of file flexcan.hpp.
RXM14MASK25
constexpr unsigned long uavcan_kinetis::flexcan::RXM14MASK25 = (1U << 25)
Definition at line 330 of file flexcan.hpp.
RXM14MASK26
constexpr unsigned long uavcan_kinetis::flexcan::RXM14MASK26 = (1U << 26)
Definition at line 331 of file flexcan.hpp.
RXM14MASK27
constexpr unsigned long uavcan_kinetis::flexcan::RXM14MASK27 = (1U << 27)
Definition at line 332 of file flexcan.hpp.
RXM14MASK28
constexpr unsigned long uavcan_kinetis::flexcan::RXM14MASK28 = (1U << 28)
Definition at line 333 of file flexcan.hpp.
RXM14MASK29
constexpr unsigned long uavcan_kinetis::flexcan::RXM14MASK29 = (1U << 29)
Definition at line 334 of file flexcan.hpp.
RXM14MASK3
constexpr unsigned long uavcan_kinetis::flexcan::RXM14MASK3 = (1U << 3)
Definition at line 308 of file flexcan.hpp.
RXM14MASK30
constexpr unsigned long uavcan_kinetis::flexcan::RXM14MASK30 = (1U << 30)
Definition at line 335 of file flexcan.hpp.
RXM14MASK31
constexpr unsigned long uavcan_kinetis::flexcan::RXM14MASK31 = (1U << 31)
Definition at line 336 of file flexcan.hpp.
RXM14MASK4
constexpr unsigned long uavcan_kinetis::flexcan::RXM14MASK4 = (1U << 4)
Definition at line 309 of file flexcan.hpp.
RXM14MASK5
constexpr unsigned long uavcan_kinetis::flexcan::RXM14MASK5 = (1U << 5)
Definition at line 310 of file flexcan.hpp.
RXM14MASK6
constexpr unsigned long uavcan_kinetis::flexcan::RXM14MASK6 = (1U << 6)
Definition at line 311 of file flexcan.hpp.
RXM14MASK7
constexpr unsigned long uavcan_kinetis::flexcan::RXM14MASK7 = (1U << 7)
Definition at line 312 of file flexcan.hpp.
RXM14MASK8
constexpr unsigned long uavcan_kinetis::flexcan::RXM14MASK8 = (1U << 8)
Definition at line 313 of file flexcan.hpp.
RXM14MASK9
constexpr unsigned long uavcan_kinetis::flexcan::RXM14MASK9 = (1U << 9)
Definition at line 314 of file flexcan.hpp.
RXM15MASK0
constexpr unsigned long uavcan_kinetis::flexcan::RXM15MASK0 = (1U << 0)
Definition at line 340 of file flexcan.hpp.
RXM15MASK1
constexpr unsigned long uavcan_kinetis::flexcan::RXM15MASK1 = (1U << 1)
Definition at line 341 of file flexcan.hpp.
RXM15MASK10
constexpr unsigned long uavcan_kinetis::flexcan::RXM15MASK10 = (1U << 10)
Definition at line 350 of file flexcan.hpp.
RXM15MASK11
constexpr unsigned long uavcan_kinetis::flexcan::RXM15MASK11 = (1U << 11)
Definition at line 351 of file flexcan.hpp.
RXM15MASK12
constexpr unsigned long uavcan_kinetis::flexcan::RXM15MASK12 = (1U << 12)
Definition at line 352 of file flexcan.hpp.
RXM15MASK13
constexpr unsigned long uavcan_kinetis::flexcan::RXM15MASK13 = (1U << 13)
Definition at line 353 of file flexcan.hpp.
RXM15MASK14
constexpr unsigned long uavcan_kinetis::flexcan::RXM15MASK14 = (1U << 14)
Definition at line 354 of file flexcan.hpp.
RXM15MASK15
constexpr unsigned long uavcan_kinetis::flexcan::RXM15MASK15 = (1U << 15)
Definition at line 355 of file flexcan.hpp.
RXM15MASK16
constexpr unsigned long uavcan_kinetis::flexcan::RXM15MASK16 = (1U << 16)
Definition at line 356 of file flexcan.hpp.
RXM15MASK17
constexpr unsigned long uavcan_kinetis::flexcan::RXM15MASK17 = (1U << 17)
Definition at line 357 of file flexcan.hpp.
RXM15MASK18
constexpr unsigned long uavcan_kinetis::flexcan::RXM15MASK18 = (1U << 18)
Definition at line 358 of file flexcan.hpp.
RXM15MASK19
constexpr unsigned long uavcan_kinetis::flexcan::RXM15MASK19 = (1U << 19)
Definition at line 359 of file flexcan.hpp.
RXM15MASK2
constexpr unsigned long uavcan_kinetis::flexcan::RXM15MASK2 = (1U << 2)
Definition at line 342 of file flexcan.hpp.
RXM15MASK20
constexpr unsigned long uavcan_kinetis::flexcan::RXM15MASK20 = (1U << 20)
Definition at line 360 of file flexcan.hpp.
RXM15MASK21
constexpr unsigned long uavcan_kinetis::flexcan::RXM15MASK21 = (1U << 21)
Definition at line 361 of file flexcan.hpp.
RXM15MASK22
constexpr unsigned long uavcan_kinetis::flexcan::RXM15MASK22 = (1U << 22)
Definition at line 362 of file flexcan.hpp.
RXM15MASK23
constexpr unsigned long uavcan_kinetis::flexcan::RXM15MASK23 = (1U << 23)
Definition at line 363 of file flexcan.hpp.
RXM15MASK24
constexpr unsigned long uavcan_kinetis::flexcan::RXM15MASK24 = (1U << 24)
Definition at line 364 of file flexcan.hpp.
RXM15MASK25
constexpr unsigned long uavcan_kinetis::flexcan::RXM15MASK25 = (1U << 25)
Definition at line 365 of file flexcan.hpp.
RXM15MASK26
constexpr unsigned long uavcan_kinetis::flexcan::RXM15MASK26 = (1U << 26)
Definition at line 366 of file flexcan.hpp.
RXM15MASK27
constexpr unsigned long uavcan_kinetis::flexcan::RXM15MASK27 = (1U << 27)
Definition at line 367 of file flexcan.hpp.
RXM15MASK28
constexpr unsigned long uavcan_kinetis::flexcan::RXM15MASK28 = (1U << 28)
Definition at line 368 of file flexcan.hpp.
RXM15MASK29
constexpr unsigned long uavcan_kinetis::flexcan::RXM15MASK29 = (1U << 29)
Definition at line 369 of file flexcan.hpp.
RXM15MASK3
constexpr unsigned long uavcan_kinetis::flexcan::RXM15MASK3 = (1U << 3)
Definition at line 343 of file flexcan.hpp.
RXM15MASK30
constexpr unsigned long uavcan_kinetis::flexcan::RXM15MASK30 = (1U << 30)
Definition at line 370 of file flexcan.hpp.
RXM15MASK31
constexpr unsigned long uavcan_kinetis::flexcan::RXM15MASK31 = (1U << 31)
Definition at line 371 of file flexcan.hpp.
RXM15MASK4
constexpr unsigned long uavcan_kinetis::flexcan::RXM15MASK4 = (1U << 4)
Definition at line 344 of file flexcan.hpp.
RXM15MASK5
constexpr unsigned long uavcan_kinetis::flexcan::RXM15MASK5 = (1U << 5)
Definition at line 345 of file flexcan.hpp.
RXM15MASK6
constexpr unsigned long uavcan_kinetis::flexcan::RXM15MASK6 = (1U << 6)
Definition at line 346 of file flexcan.hpp.
RXM15MASK7
constexpr unsigned long uavcan_kinetis::flexcan::RXM15MASK7 = (1U << 7)
Definition at line 347 of file flexcan.hpp.
RXM15MASK8
constexpr unsigned long uavcan_kinetis::flexcan::RXM15MASK8 = (1U << 8)
Definition at line 348 of file flexcan.hpp.
RXM15MASK9
constexpr unsigned long uavcan_kinetis::flexcan::RXM15MASK9 = (1U << 9)
Definition at line 349 of file flexcan.hpp.
RXMGMASK0
constexpr unsigned long uavcan_kinetis::flexcan::RXMGMASK0 = (1U << 0)
Definition at line 270 of file flexcan.hpp.
RXMGMASK1
constexpr unsigned long uavcan_kinetis::flexcan::RXMGMASK1 = (1U << 1)
Definition at line 271 of file flexcan.hpp.
RXMGMASK10
constexpr unsigned long uavcan_kinetis::flexcan::RXMGMASK10 = (1U << 10)
Definition at line 280 of file flexcan.hpp.
RXMGMASK11
constexpr unsigned long uavcan_kinetis::flexcan::RXMGMASK11 = (1U << 11)
Definition at line 281 of file flexcan.hpp.
RXMGMASK12
constexpr unsigned long uavcan_kinetis::flexcan::RXMGMASK12 = (1U << 12)
Definition at line 282 of file flexcan.hpp.
RXMGMASK13
constexpr unsigned long uavcan_kinetis::flexcan::RXMGMASK13 = (1U << 13)
Definition at line 283 of file flexcan.hpp.
RXMGMASK14
constexpr unsigned long uavcan_kinetis::flexcan::RXMGMASK14 = (1U << 14)
Definition at line 284 of file flexcan.hpp.
RXMGMASK15
constexpr unsigned long uavcan_kinetis::flexcan::RXMGMASK15 = (1U << 15)
Definition at line 285 of file flexcan.hpp.
RXMGMASK16
constexpr unsigned long uavcan_kinetis::flexcan::RXMGMASK16 = (1U << 16)
Definition at line 286 of file flexcan.hpp.
RXMGMASK17
constexpr unsigned long uavcan_kinetis::flexcan::RXMGMASK17 = (1U << 17)
Definition at line 287 of file flexcan.hpp.
RXMGMASK18
constexpr unsigned long uavcan_kinetis::flexcan::RXMGMASK18 = (1U << 18)
Definition at line 288 of file flexcan.hpp.
RXMGMASK19
constexpr unsigned long uavcan_kinetis::flexcan::RXMGMASK19 = (1U << 19)
Definition at line 289 of file flexcan.hpp.
RXMGMASK2
constexpr unsigned long uavcan_kinetis::flexcan::RXMGMASK2 = (1U << 2)
Definition at line 272 of file flexcan.hpp.
RXMGMASK20
constexpr unsigned long uavcan_kinetis::flexcan::RXMGMASK20 = (1U << 20)
Definition at line 290 of file flexcan.hpp.
RXMGMASK21
constexpr unsigned long uavcan_kinetis::flexcan::RXMGMASK21 = (1U << 21)
Definition at line 291 of file flexcan.hpp.
RXMGMASK22
constexpr unsigned long uavcan_kinetis::flexcan::RXMGMASK22 = (1U << 22)
Definition at line 292 of file flexcan.hpp.
RXMGMASK23
constexpr unsigned long uavcan_kinetis::flexcan::RXMGMASK23 = (1U << 23)
Definition at line 293 of file flexcan.hpp.
RXMGMASK24
constexpr unsigned long uavcan_kinetis::flexcan::RXMGMASK24 = (1U << 24)
Definition at line 294 of file flexcan.hpp.
RXMGMASK25
constexpr unsigned long uavcan_kinetis::flexcan::RXMGMASK25 = (1U << 25)
Definition at line 295 of file flexcan.hpp.
RXMGMASK26
constexpr unsigned long uavcan_kinetis::flexcan::RXMGMASK26 = (1U << 26)
Definition at line 296 of file flexcan.hpp.
RXMGMASK27
constexpr unsigned long uavcan_kinetis::flexcan::RXMGMASK27 = (1U << 27)
Definition at line 297 of file flexcan.hpp.
RXMGMASK28
constexpr unsigned long uavcan_kinetis::flexcan::RXMGMASK28 = (1U << 28)
Definition at line 298 of file flexcan.hpp.
RXMGMASK29
constexpr unsigned long uavcan_kinetis::flexcan::RXMGMASK29 = (1U << 29)
Definition at line 299 of file flexcan.hpp.
RXMGMASK3
constexpr unsigned long uavcan_kinetis::flexcan::RXMGMASK3 = (1U << 3)
Definition at line 273 of file flexcan.hpp.
RXMGMASK30
constexpr unsigned long uavcan_kinetis::flexcan::RXMGMASK30 = (1U << 30)
Definition at line 300 of file flexcan.hpp.
RXMGMASK31
constexpr unsigned long uavcan_kinetis::flexcan::RXMGMASK31 = (1U << 31)
Definition at line 301 of file flexcan.hpp.
RXMGMASK4
constexpr unsigned long uavcan_kinetis::flexcan::RXMGMASK4 = (1U << 4)
Definition at line 274 of file flexcan.hpp.
RXMGMASK5
constexpr unsigned long uavcan_kinetis::flexcan::RXMGMASK5 = (1U << 5)
Definition at line 275 of file flexcan.hpp.
RXMGMASK6
constexpr unsigned long uavcan_kinetis::flexcan::RXMGMASK6 = (1U << 6)
Definition at line 276 of file flexcan.hpp.
RXMGMASK7
constexpr unsigned long uavcan_kinetis::flexcan::RXMGMASK7 = (1U << 7)
Definition at line 277 of file flexcan.hpp.
RXMGMASK8
constexpr unsigned long uavcan_kinetis::flexcan::RXMGMASK8 = (1U << 8)
Definition at line 278 of file flexcan.hpp.
RXMGMASK9
constexpr unsigned long uavcan_kinetis::flexcan::RXMGMASK9 = (1U << 9)
Definition at line 279 of file flexcan.hpp.
TIMER_MASK
constexpr unsigned long uavcan_kinetis::flexcan::TIMER_MASK = (0xffffU << TIMER_SHIFT)
Definition at line 266 of file flexcan.hpp.
TIMER_SHIFT
constexpr unsigned long uavcan_kinetis::flexcan::TIMER_SHIFT = (0U)
Definition at line 265 of file flexcan.hpp.
useFIFO
const uavcan::uint8_t uavcan_kinetis::flexcan::useFIFO = 1
Definition at line 35 of file uc_kinetis_flexcan.cpp.
Referenced by uavcan_kinetis::CanIface::doReset().