PX4 Firmware: src/lib/flight_tasks/tasks/Utility/VelocitySmoothingTest.cpp File Reference
VelocitySmoothingTest.cpp File Reference
#include <gtest/gtest.h>
#include <matrix/matrix/math.hpp>
#include "VelocitySmoothing.hpp"
Classes
class VelocitySmoothingTest
Functions
TEST_F (VelocitySmoothingTest, testTimeSynchronization)
TEST_F (VelocitySmoothingTest, testConstantSetpoint)
TEST_F (VelocitySmoothingTest, testZeroSetpoint)
Function Documentation
TEST_F() [1/3]
TEST_F (VelocitySmoothingTest , testTimeSynchronization)
Definition at line 90 of file VelocitySmoothingTest.cpp.
References f().
TEST_F() [2/3]
TEST_F (VelocitySmoothingTest , testConstantSetpoint)
Definition at line 115 of file VelocitySmoothingTest.cpp.
References matrix::ceil(), dt, f(), and t123.
TEST_F() [3/3]
TEST_F (VelocitySmoothingTest , testZeroSetpoint)
Definition at line 153 of file VelocitySmoothingTest.cpp.
References dt, and f().