PX4 Firmware: AttitudeControlConvergenceTest Class Reference
AttitudeControlConvergenceTest Class Reference
Public Member Functions
AttitudeControlConvergenceTest ()
void checkConvergence ()
Quatf adaptAntipodal (const Quatf q)
Public Attributes
AttitudeControl _attitude_control
Quatf _quat_state
Quatf _quat_goal
Detailed Description
Definition at line 47 of file AttitudeControlTest.cpp.
Constructor & Destructor Documentation
AttitudeControlConvergenceTest()
AttitudeControlConvergenceTest::AttitudeControlConvergenceTest () inline
Definition at line 50 of file AttitudeControlTest.cpp.
References f().
Member Function Documentation
adaptAntipodal()
Quatf AttitudeControlConvergenceTest::adaptAntipodal (const Quatf q) inline
Definition at line 80 of file AttitudeControlTest.cpp.
References FLT_EPSILON, and math::sign().
checkConvergence()
void AttitudeControlConvergenceTest::checkConvergence () inline
Definition at line 56 of file AttitudeControlTest.cpp.
References f(), and matrix::Vector< Type, M >::norm().
Member Data Documentation
_attitude_control
AttitudeControl AttitudeControlConvergenceTest::_attitude_control
Definition at line 91 of file AttitudeControlTest.cpp.
_quat_goal
Quatf AttitudeControlConvergenceTest::_quat_goal
Definition at line 93 of file AttitudeControlTest.cpp.
_quat_state
Quatf AttitudeControlConvergenceTest::_quat_state
Definition at line 92 of file AttitudeControlTest.cpp.
The documentation for this class was generated from the following file:
src/modules/mc_att_control/AttitudeControl/AttitudeControlTest.cpp