PX4 Firmware: src/drivers/boards/px4nucleoF767ZI-v1/init.c File Reference
init.c File Reference
#include <px4_config.h>
#include <px4_tasks.h>
#include <stdbool.h>
#include <stdio.h>
#include <string.h>
#include <debug.h>
#include <errno.h>
#include "platform/cxxinitialize.h"
#include <nuttx/board.h>
#include <nuttx/spi/spi.h>
#include <nuttx/i2c/i2c_master.h>
#include <nuttx/sdio.h>
#include <nuttx/mmcsd.h>
#include <nuttx/analog/adc.h>
#include <nuttx/mm/gran.h>
#include <chip.h>
#include "board_config.h"
#include <stm32_uart.h>
#include <arch/board/board.h>
#include <drivers/drv_hrt.h>
#include <drivers/drv_board_led.h>
#include <systemlib/px4_macros.h>
#include <systemlib/cpuload.h>
#include <perf/perf_counter.h>
#include <systemlib/err.h>
#include <systemlib/hardfault_log.h>
#include <parameters/param.h>
#include "up_internal.h"
Macros
#define message printf
Functions
__BEGIN_DECLS void led_init (void)
Ideally we'd be able to get these from up_internal.h, but since we want to be able to disable the NuttX use of leds for system indication at will and there is no separate switch, we need to build independent of the CONFIG_ARCH_LEDS configuration switch.
void led_on (int led)
void led_off (int led)
__END_DECLS __EXPORT void board_peripheral_reset (int ms)
__EXPORT void stm32_boardinitialize (void)
__EXPORT int board_app_initialize (uintptr_t arg)
Macro Definition Documentation
#define message printf
Definition at line 103 of file init.c.
Referenced by board_app_initialize().
Function Documentation
__EXPORT int board_app_initialize (uintptr_t arg)
Definition at line 238 of file init.c.
References BBSRAM_PATH, board_autoled_on(), board_dma_alloc_init, BSRAM_FILE_SIZES, drv_led_start(), hardfault_check_status(), HARDFAULT_DISPLAY_FORMAT, hardfault_increment_reboot(), hardfault_rearm(), hardfault_write(), hrt_call_every(), hrt_init(), LED_BLUE, LED_GREEN, led_off(), LED_RED, message, OK, param_init(), stm32_sdio_initialize(), stm32_spi_bus_initialize(), and ts_to_abstime().
__END_DECLS __EXPORT void board_peripheral_reset (int ms)
Definition at line 132 of file init.c.
References GPIO_PERIPH_3V3_EN, GPIO_SPEKTRUM_PWR_EN, usleep(), and warnx.
__BEGIN_DECLS void led_init (void)
Ideally we'd be able to get these from up_internal.h, but since we want to be able to disable the NuttX use of leds for system indication at will and there is no separate switch, we need to build independent of the CONFIG_ARCH_LEDS configuration switch.
Definition at line 72 of file led.c.
void led_off (int led)
Definition at line 97 of file led.c.
void led_on (int led)
Definition at line 92 of file led.c.
__EXPORT void stm32_boardinitialize (void)
Definition at line 166 of file init.c.
References board_autoled_initialize(), GPIO_8266_GPIO0, GPIO_8266_PD, GPIO_8266_RST, GPIO_BTN_SAFETY, GPIO_CAN1_RX, GPIO_CAN1_TX, GPIO_GPIO0_OUTPUT, GPIO_GPIO1_OUTPUT, GPIO_GPIO2_OUTPUT, GPIO_GPIO3_OUTPUT, GPIO_GPIO4_OUTPUT, GPIO_GPIO5_OUTPUT, GPIO_PERIPH_3V3_EN, GPIO_SBUS_INV, GPIO_SPEKTRUM_PWR_EN, GPIO_VDD_BRICK_VALID, and stm32_spiinitialize().