PX4 Firmware: FXAS21002C Class Reference
FXAS21002C Class Reference
Public Member Functions
FXAS21002C (int bus, const char *path, uint32_t device, enum Rotation rotation)
virtual ~FXAS21002C ()
virtual int init ()
virtual ssize_t read (struct file *filp, char *buffer, size_t buflen)
virtual int ioctl (struct file *filp, int cmd, unsigned long arg)
void print_info ()
Diagnostics - print some basic information about the driver.
void print_registers ()
dump register values
void test_error ()
deliberately trigger an error
Protected Member Functions
virtual int probe ()
Private Member Functions
void start ()
Start automatic measurement.
void stop ()
Stop automatic measurement.
void reset ()
Reset chip.
void disable_i2c ()
disable I2C on the chip
void check_registers (void)
check key registers for correct values
void measure ()
Fetch accel measurements from the sensor and update the report ring.
uint8_t read_reg (unsigned reg)
Read a register from the FXAS21002C.
void write_reg (unsigned reg, uint8_t value)
Write a register in the FXAS21002C.
void modify_reg (unsigned reg, uint8_t clearbits, uint8_t setbits)
Modify a register in the FXAS21002C.
void write_checked_reg (unsigned reg, uint8_t value)
Write a register in the FXAS21002C, updating _checked_values.
int set_range (unsigned max_dps)
Set the FXAS21002C measurement range.
int set_samplerate (unsigned frequency)
Set the FXAS21002C internal sampling frequency.
void set_driver_lowpass_filter (float samplerate, float bandwidth)
Set the lowpass filter of the driver.
int self_test ()
Self test.
FXAS21002C (const FXAS21002C &)
FXAS21002C operator= (const FXAS21002C &)
Static Private Member Functions
static void measure_trampoline (void *arg)
Static trampoline from the hrt_call context; because we don't have a generic hrt wrapper yet.
Private Attributes
struct hrt_call _gyro_call
unsigned _call_interval
ringbuffer::RingBuffer * _reports
struct gyro_calibration_s _gyro_scale
float _gyro_range_scale
float _gyro_range_rad_s
orb_advert_t _gyro_topic
int _orb_class_instance
int _class_instance
unsigned _current_rate
unsigned _orientation
float _last_temperature
unsigned _read
perf_counter_t _sample_perf
perf_counter_t _errors
perf_counter_t _bad_registers
perf_counter_t _duplicates
uint8_t _register_wait
math::LowPassFilter2p _gyro_filter_x
math::LowPassFilter2p _gyro_filter_y
math::LowPassFilter2p _gyro_filter_z
Integrator _gyro_int
enum Rotation _rotation
uint8_t _checked_values [FXAS21002C_NUM_CHECKED_REGISTERS]
uint8_t _checked_next
Static Private Attributes
static const uint8_t _checked_registers [FXAS21002C_NUM_CHECKED_REGISTERS]
Detailed Description
Definition at line 218 of file fxas21002c.cpp.
Constructor & Destructor Documentation
FXAS21002C::FXAS21002C (int bus, const char * path, uint32_t device, enum Rotation rotation)
Definition at line 427 of file fxas21002c.cpp.
References _bad_registers, _call_interval, _checked_next, _checked_values, _duplicates, _errors, _gyro_filter_x, _gyro_filter_y, _gyro_filter_z, _gyro_int, _gyro_range_rad_s, _gyro_range_scale, _gyro_scale, _gyro_topic, _last_temperature, _orb_class_instance, _read, _register_wait, _reports, _rotation, _sample_perf, DRV_GYR_DEVTYPE_FXAS2100C, f(), FXAS21002C_DEFAULT_FILTER_FREQ, FXAS21002C_DEFAULT_RATE, FXAS21002C_MAX_OUTPUT_RATE, PC_COUNT, PC_ELAPSED, perf_alloc, gyro_calibration_s::x_offset, gyro_calibration_s::x_scale, gyro_calibration_s::y_offset, gyro_calibration_s::y_scale, gyro_calibration_s::z_offset, and gyro_calibration_s::z_scale.
Referenced by fxas21002c::start().
FXAS21002C::~FXAS21002C () virtual
Definition at line 469 of file fxas21002c.cpp.
References _bad_registers, _class_instance, _duplicates, _errors, _reports, _sample_perf, GYRO_BASE_DEVICE_PATH, perf_free(), and stop().
FXAS21002C::FXAS21002C (const FXAS21002C &) private
Member Function Documentation
void FXAS21002C::check_registers (void) private
check key registers for correct values
Definition at line 935 of file fxas21002c.cpp.
References _bad_registers, _checked_next, _checked_registers, _checked_values, _register_wait, FXAS21002C_NUM_CHECKED_REGISTERS, perf_count(), read_reg(), and write_reg().
Referenced by measure().
void FXAS21002C::disable_i2c () private
disable I2C on the chip
int FXAS21002C::init () virtual
Definition at line 492 of file fxas21002c.cpp.
References _class_instance, _gyro_topic, _orb_class_instance, _reports, GYRO_BASE_DEVICE_PATH, gyro_report, lis3mdl::init(), measure(), OK, orb_advertise_multi(), ORB_ID, ORB_PRIO_DEFAULT, ORB_PRIO_VERY_HIGH, PX4_ERR, PX4_ERROR, and reset().
Referenced by fxas21002c::start().
int FXAS21002C::ioctl (struct file * filp, int cmd, unsigned long arg) virtual
Definition at line 627 of file fxas21002c.cpp.
References _call_interval, _current_rate, _gyro_call, _gyro_filter_x, _gyro_range_rad_s, _gyro_scale, _reports, FXAS21002C_DEFAULT_RATE, FXAS21002C_TIMER_REDUCTION, math::LowPassFilter2p::get_cutoff_freq(), GYROIOCGRANGE, GYROIOCGSAMPLERATE, GYROIOCGSCALE, GYROIOCSRANGE, GYROIOCSSAMPLERATE, GYROIOCSSCALE, M_PI_F, OK, hrt_call::period, reset(), SENSOR_POLLRATE_DEFAULT, SENSOR_POLLRATE_EXTERNAL, SENSOR_POLLRATE_MANUAL, SENSOR_POLLRATE_MAX, SENSORIOCGPOLLRATE, SENSORIOCRESET, SENSORIOCSPOLLRATE, SENSORIOCSQUEUEDEPTH, set_driver_lowpass_filter(), set_range(), set_samplerate(), start(), and stop().
Referenced by fxas21002c::reset(), fxas21002c::start(), and fxas21002c::test().
void FXAS21002C::measure () private
Fetch accel measurements from the sensor and update the report ring.
Definition at line 966 of file fxas21002c.cpp.
References _bad_registers, _current_rate, _duplicates, _gyro_filter_x, _gyro_filter_y, _gyro_filter_z, _gyro_int, _gyro_range_scale, _gyro_scale, _gyro_topic, _last_temperature, _read, _register_wait, _reports, _rotation, _sample_perf, math::LowPassFilter2p::apply(), check_registers(), DIR_READ, DR_STATUS_ZYXDR, FXAS21002C_STATUS, FXAS21002C_TEMP, gyro_report, hrt_absolute_time(), ORB_ID, orb_publish(), perf_begin(), perf_count(), perf_end(), perf_event_count(), Integrator::put(), read_reg(), rotate_3f(), status, swap16, gyro_calibration_s::x_offset, gyro_calibration_s::x_scale, gyro_calibration_s::y_offset, gyro_calibration_s::y_scale, gyro_calibration_s::z_offset, and gyro_calibration_s::z_scale.
Referenced by init(), measure_trampoline(), and read().
void FXAS21002C::measure_trampoline (void * arg) static private
Static trampoline from the hrt_call context; because we don't have a generic hrt wrapper yet.
Called by the HRT in interrupt context at the specified rate if automatic polling is enabled.
Parameters
arg Instance pointer for the driver that is polling.
Definition at line 926 of file fxas21002c.cpp.
References measure().
Referenced by start().
void FXAS21002C::modify_reg (unsigned reg, uint8_t clearbits, uint8_t setbits) private
Modify a register in the FXAS21002C.
Bits are cleared before bits are set.
Parameters
reg The register to modify.
clearbits Bits in the register to clear.
setbits Bits in the register to set.
Definition at line 792 of file fxas21002c.cpp.
References read_reg(), and write_checked_reg().
Referenced by set_range().
FXAS21002C FXAS21002C::operator= (const FXAS21002C &) private
void FXAS21002C::print_info ()
Diagnostics - print some basic information about the driver.
Definition at line 1094 of file fxas21002c.cpp.
References _bad_registers, _checked_next, _checked_registers, _checked_values, _duplicates, _errors, _last_temperature, _read, _reports, _sample_perf, FXAS21002C_NUM_CHECKED_REGISTERS, perf_print_counter(), and read_reg().
Referenced by fxas21002c::info().
void FXAS21002C::print_registers ()
dump register values
Definition at line 1119 of file fxas21002c.cpp.
References DEF_REG, FXAS21002C_CTRL_REG0, FXAS21002C_CTRL_REG1, FXAS21002C_CTRL_REG2, FXAS21002C_CTRL_REG3, FXAS21002C_DR_STATUS, FXAS21002C_F_EVENT, FXAS21002C_F_SETUP, FXAS21002C_F_STATUS, FXAS21002C_INT_SRC_FLAG, FXAS21002C_OUT_X_LSB, FXAS21002C_OUT_X_MSB, FXAS21002C_OUT_Y_LSB, FXAS21002C_OUT_Y_MSB, FXAS21002C_OUT_Z_LSB, FXAS21002C_OUT_Z_MSB, FXAS21002C_RT_CFG, FXAS21002C_RT_COUNT, FXAS21002C_RT_SRC, FXAS21002C_RT_THS, FXAS21002C_STATUS, FXAS21002C_TEMP, FXAS21002C_WHO_AM_I, name, and read_reg().
Referenced by fxas21002c::regdump().
int FXAS21002C::probe () protected virtual
Definition at line 570 of file fxas21002c.cpp.
References _checked_values, FXAS21002C_WHO_AM_I, OK, read_reg(), and WHO_AM_I.
ssize_t FXAS21002C::read (struct file * filp, char * buffer, size_t buflen) virtual
Definition at line 584 of file fxas21002c.cpp.
References _call_interval, _reports, gyro_report, and measure().
Referenced by fxas21002c::test().
uint8_t FXAS21002C::read_reg (unsigned reg) private
Read a register from the FXAS21002C.
Parameters
The register to read.
Returns
The value that was read.
Definition at line 756 of file fxas21002c.cpp.
References DIR_READ.
Referenced by check_registers(), measure(), modify_reg(), print_info(), print_registers(), and probe().
void FXAS21002C::reset () private
Reset chip.
Resets the chip and measurements ranges, but not scale and offset.
Definition at line 536 of file fxas21002c.cpp.
References _read, CTRL_REG1_ACTIVE, CTRL_REG_DR_800HZ, FXAS21002C_CTRL_REG0, FXAS21002C_CTRL_REG1, FXAS21002C_DEFAULT_FILTER_FREQ, FXAS21002C_DEFAULT_RANGE_DPS, FXAS21002C_DEFAULT_RATE, set_driver_lowpass_filter(), set_range(), set_samplerate(), write_checked_reg(), and write_reg().
Referenced by init(), and ioctl().
int FXAS21002C::self_test () private
Self test.
Returns
0 on success, 1 on failure
Definition at line 746 of file fxas21002c.cpp.
References _read.
void FXAS21002C::set_driver_lowpass_filter (float samplerate, float bandwidth) private
Set the lowpass filter of the driver.
Parameters
samplerate The current samplerate
frequency The cutoff frequency for the lowpass filter
Definition at line 891 of file fxas21002c.cpp.
References _gyro_filter_x, _gyro_filter_y, _gyro_filter_z, and math::LowPassFilter2p::set_cutoff_frequency().
Referenced by ioctl(), and reset().
int FXAS21002C::set_range (unsigned max_dps) private
Set the FXAS21002C measurement range.
Parameters
max_dps The measurement range is set to permit reading at least this rate in degrees per second. Zero selects the maximum supported range.
Returns
OK if the value can be supported, -ERANGE otherwise.
Definition at line 803 of file fxas21002c.cpp.
References _gyro_range_rad_s, _gyro_range_scale, CTRL_REG0_FS_1000_DPS, CTRL_REG0_FS_2000_DPS, CTRL_REG0_FS_250_DPS, CTRL_REG0_FS_500_DPS, CTRL_REG0_FS_MASK, f(), FXAS21002C_CTRL_REG0, M_PI_F, modify_reg(), and OK.
Referenced by ioctl(), and reset().
int FXAS21002C::set_samplerate (unsigned frequency) private
Set the FXAS21002C internal sampling frequency.
Parameters
frequency The internal sampling frequency is set to not less than this value. Zero selects the maximum rate supported.
Returns
OK if the value can be supported.
Definition at line 845 of file fxas21002c.cpp.
References _current_rate, CTRL_REG1_ACTIVE, CTRL_REG1_READY, CTRL_REG_DR_100HZ, CTRL_REG_DR_12_5, CTRL_REG_DR_200HZ, CTRL_REG_DR_25HZ, CTRL_REG_DR_400HZ, CTRL_REG_DR_50HZ, CTRL_REG_DR_800HZ, FXAS21002C_CTRL_REG1, FXAS21002C_DEFAULT_RATE, GYRO_SAMPLERATE_DEFAULT, OK, and write_checked_reg().
Referenced by ioctl(), and reset().
void FXAS21002C::start () private
Start automatic measurement.
Definition at line 900 of file fxas21002c.cpp.
References _call_interval, _gyro_call, _reports, FXAS21002C_TIMER_REDUCTION, hrt_call_every(), measure_trampoline(), and stop().
Referenced by ioctl().
void FXAS21002C::stop () private
Stop automatic measurement.
Definition at line 916 of file fxas21002c.cpp.
References _gyro_call, _reports, and hrt_cancel().
Referenced by ioctl(), start(), and ~FXAS21002C().
void FXAS21002C::test_error ()
deliberately trigger an error
Definition at line 1155 of file fxas21002c.cpp.
References FXAS21002C_CTRL_REG1, and write_reg().
Referenced by fxas21002c::test_error().
void FXAS21002C::write_checked_reg (unsigned reg, uint8_t value) private
Write a register in the FXAS21002C, updating _checked_values.
Parameters
reg The register to write.
value The new value to write.
Definition at line 780 of file fxas21002c.cpp.
References _checked_registers, _checked_values, FXAS21002C_NUM_CHECKED_REGISTERS, and write_reg().
Referenced by modify_reg(), reset(), and set_samplerate().
void FXAS21002C::write_reg (unsigned reg, uint8_t value) private
Write a register in the FXAS21002C.
Parameters
reg The register to write.
value The new value to write.
Definition at line 769 of file fxas21002c.cpp.
References DIR_WRITE.
Referenced by check_registers(), reset(), test_error(), and write_checked_reg().
Member Data Documentation
perf_counter_t FXAS21002C::_bad_registers private
Definition at line 271 of file fxas21002c.cpp.
Referenced by check_registers(), FXAS21002C(), measure(), print_info(), and ~FXAS21002C().
unsigned FXAS21002C::_call_interval private
Definition at line 251 of file fxas21002c.cpp.
Referenced by FXAS21002C(), ioctl(), read(), and start().
uint8_t FXAS21002C::_checked_next private
Definition at line 292 of file fxas21002c.cpp.
Referenced by check_registers(), FXAS21002C(), and print_info().
const uint8_t FXAS21002C::_checked_registers static private
Initial value:
= {
    FXAS21002C_WHO_AM_I,
    FXAS21002C_F_SETUP,
    FXAS21002C_CTRL_REG0,
    FXAS21002C_CTRL_REG1,
    FXAS21002C_CTRL_REG2,
    FXAS21002C_CTRL_REG3,
}
Definition at line 290 of file fxas21002c.cpp.
Referenced by check_registers(), print_info(), and write_checked_reg().
uint8_t FXAS21002C::_checked_values[FXAS21002C_NUM_CHECKED_REGISTERS] private
Definition at line 291 of file fxas21002c.cpp.
Referenced by check_registers(), FXAS21002C(), print_info(), probe(), and write_checked_reg().
int FXAS21002C::_class_instance private
Definition at line 260 of file fxas21002c.cpp.
Referenced by init(), and ~FXAS21002C().
unsigned FXAS21002C::_current_rate private
Definition at line 262 of file fxas21002c.cpp.
Referenced by ioctl(), measure(), and set_samplerate().
perf_counter_t FXAS21002C::_duplicates private
Definition at line 272 of file fxas21002c.cpp.
Referenced by FXAS21002C(), measure(), print_info(), and ~FXAS21002C().
perf_counter_t FXAS21002C::_errors private
Definition at line 270 of file fxas21002c.cpp.
Referenced by FXAS21002C(), print_info(), and ~FXAS21002C().
struct hrt_call FXAS21002C::_gyro_call private
Definition at line 249 of file fxas21002c.cpp.
Referenced by ioctl(), start(), and stop().
math::LowPassFilter2p FXAS21002C::_gyro_filter_x private
Definition at line 276 of file fxas21002c.cpp.
Referenced by FXAS21002C(), ioctl(), measure(), and set_driver_lowpass_filter().
math::LowPassFilter2p FXAS21002C::_gyro_filter_y private
Definition at line 277 of file fxas21002c.cpp.
Referenced by FXAS21002C(), measure(), and set_driver_lowpass_filter().
math::LowPassFilter2p FXAS21002C::_gyro_filter_z private
Definition at line 278 of file fxas21002c.cpp.
Referenced by FXAS21002C(), measure(), and set_driver_lowpass_filter().
Integrator FXAS21002C::_gyro_int private
Definition at line 280 of file fxas21002c.cpp.
Referenced by FXAS21002C(), and measure().
float FXAS21002C::_gyro_range_rad_s private
Definition at line 257 of file fxas21002c.cpp.
Referenced by FXAS21002C(), ioctl(), and set_range().
float FXAS21002C::_gyro_range_scale private
Definition at line 256 of file fxas21002c.cpp.
Referenced by FXAS21002C(), measure(), and set_range().
struct gyro_calibration_s FXAS21002C::_gyro_scale private
Definition at line 255 of file fxas21002c.cpp.
Referenced by FXAS21002C(), ioctl(), and measure().
orb_advert_t FXAS21002C::_gyro_topic private
Definition at line 258 of file fxas21002c.cpp.
Referenced by FXAS21002C(), init(), and measure().
float FXAS21002C::_last_temperature private
Definition at line 264 of file fxas21002c.cpp.
Referenced by FXAS21002C(), measure(), and print_info().
int FXAS21002C::_orb_class_instance private
Definition at line 259 of file fxas21002c.cpp.
Referenced by FXAS21002C(), and init().
unsigned FXAS21002C::_orientation private
Definition at line 263 of file fxas21002c.cpp.
unsigned FXAS21002C::_read private
Definition at line 266 of file fxas21002c.cpp.
Referenced by FXAS21002C(), measure(), print_info(), reset(), and self_test().
uint8_t FXAS21002C::_register_wait private
Definition at line 274 of file fxas21002c.cpp.
Referenced by check_registers(), FXAS21002C(), and measure().
ringbuffer::RingBuffer* FXAS21002C::_reports private
Definition at line 253 of file fxas21002c.cpp.
Referenced by FXAS21002C(), init(), ioctl(), measure(), print_info(), read(), start(), stop(), and ~FXAS21002C().
enum Rotation FXAS21002C::_rotation private
Definition at line 282 of file fxas21002c.cpp.
Referenced by FXAS21002C(), and measure().
perf_counter_t FXAS21002C::_sample_perf private
Definition at line 269 of file fxas21002c.cpp.
Referenced by FXAS21002C(), measure(), print_info(), and ~FXAS21002C().
The documentation for this class was generated from the following file:
src/drivers/imu/fxas21002c/fxas21002c.cpp