PX4 Firmware: L3GD20 Class Reference
L3GD20 Class Reference
Public Member Functions
L3GD20 (int bus, const char *path, uint32_t device, enum Rotation rotation)
virtual ~L3GD20 ()
virtual int init ()
virtual ssize_t read (struct file *filp, char *buffer, size_t buflen)
virtual int ioctl (struct file *filp, int cmd, unsigned long arg)
void print_info ()
Diagnostics - print some basic information about the driver.
void print_registers ()
void test_error ()
Protected Member Functions
virtual int probe ()
Private Member Functions
void start ()
Start automatic measurement.
void stop ()
Stop automatic measurement.
void reset ()
Reset the driver.
void disable_i2c ()
disable I2C on the chip
void check_registers (void)
check key registers for correct values
void measure ()
Fetch measurements from the sensor and update the report ring.
uint8_t read_reg (unsigned reg)
Read a register from the L3GD20.
void write_reg (unsigned reg, uint8_t value)
Write a register in the L3GD20.
void modify_reg (unsigned reg, uint8_t clearbits, uint8_t setbits)
Modify a register in the L3GD20.
void write_checked_reg (unsigned reg, uint8_t value)
Write a register in the L3GD20, updating _checked_values.
int set_range (unsigned max_dps)
Set the L3GD20 measurement range.
int set_samplerate (unsigned frequency)
Set the L3GD20 internal sampling frequency.
void set_driver_lowpass_filter (float samplerate, float bandwidth)
Set the lowpass filter of the driver.
int self_test ()
Self test.
L3GD20 (const L3GD20 &)
L3GD20 operator= (const L3GD20 &)
Static Private Member Functions
static void measure_trampoline (void *arg)
Static trampoline from the hrt_call context; because we don't have a generic hrt wrapper yet.
Private Attributes
struct hrt_call _call
unsigned _call_interval
ringbuffer::RingBuffer * _reports
struct gyro_calibration_s _gyro_scale
float _gyro_range_scale
float _gyro_range_rad_s
orb_advert_t _gyro_topic
int _orb_class_instance
int _class_instance
unsigned _current_rate
unsigned _orientation
unsigned _read
perf_counter_t _sample_perf
perf_counter_t _errors
perf_counter_t _bad_registers
perf_counter_t _duplicates
uint8_t _register_wait
math::LowPassFilter2p _gyro_filter_x
math::LowPassFilter2p _gyro_filter_y
math::LowPassFilter2p _gyro_filter_z
Integrator _gyro_int
bool _is_l3g4200d
enum Rotation _rotation
uint8_t _checked_values [L3GD20_NUM_CHECKED_REGISTERS]
uint8_t _checked_next
Static Private Attributes
static const uint8_t _checked_registers [L3GD20_NUM_CHECKED_REGISTERS]
Detailed Description
Definition at line 195 of file l3gd20.cpp.
Constructor & Destructor Documentation
L3GD20::L3GD20 (int bus, const char * path, uint32_t device, enum Rotation rotation)
Definition at line 395 of file l3gd20.cpp.
References _bad_registers, _call_interval, _checked_next, _class_instance, _current_rate, _duplicates, _errors, _gyro_filter_x, _gyro_filter_y, _gyro_filter_z, _gyro_int, _gyro_range_rad_s, _gyro_range_scale, _gyro_scale, _gyro_topic, _is_l3g4200d, _orb_class_instance, _orientation, _read, _register_wait, _reports, _rotation, _sample_perf, DRV_GYR_DEVTYPE_L3GD20, f(), L3GD20_DEFAULT_FILTER_FREQ, L3GD20_DEFAULT_RATE, L3GD20_MAX_OUTPUT_RATE, PC_COUNT, PC_ELAPSED, perf_alloc, SENSOR_BOARD_ROTATION_DEFAULT, gyro_calibration_s::x_offset, gyro_calibration_s::x_scale, gyro_calibration_s::y_offset, gyro_calibration_s::y_scale, gyro_calibration_s::z_offset, and gyro_calibration_s::z_scale.
Referenced by l3gd20::start().
L3GD20::~L3GD20 () virtual
Definition at line 434 of file l3gd20.cpp.
References _bad_registers, _class_instance, _duplicates, _errors, _reports, _sample_perf, GYRO_BASE_DEVICE_PATH, perf_free(), and stop().
L3GD20::L3GD20 (const L3GD20 &) private
Member Function Documentation
void L3GD20::check_registers (void) private
check key registers for correct values
Definition at line 907 of file l3gd20.cpp.
References _bad_registers, _checked_next, _checked_registers, _checked_values, _register_wait, L3GD20_NUM_CHECKED_REGISTERS, perf_count(), read_reg(), and write_reg().
Referenced by measure().
void L3GD20::disable_i2c (void) private
disable I2C on the chip
Definition at line 848 of file l3gd20.cpp.
References ADDR_LOW_ODR, DEVICE_DEBUG, read_reg(), write_checked_reg(), and write_reg().
Referenced by reset().
int L3GD20::init () virtual
Definition at line 456 of file l3gd20.cpp.
References _class_instance, _gyro_topic, _orb_class_instance, _reports, DEVICE_DEBUG, GYRO_BASE_DEVICE_PATH, gyro_report, lis3mdl::init(), measure(), OK, orb_advertise_multi(), ORB_ID, ORB_PRIO_DEFAULT, ORB_PRIO_VERY_HIGH, PX4_ERROR, and reset().
Referenced by l3gd20::start().
int L3GD20::ioctl (struct file * filp, int cmd, unsigned long arg) virtual
Definition at line 572 of file l3gd20.cpp.
References _call, _call_interval, _current_rate, _gyro_filter_x, _gyro_range_rad_s, _gyro_scale, _is_l3g4200d, _reports, math::LowPassFilter2p::get_cutoff_freq(), GYROIOCGRANGE, GYROIOCGSAMPLERATE, GYROIOCGSCALE, GYROIOCSRANGE, GYROIOCSSAMPLERATE, GYROIOCSSCALE, L3G4200D_DEFAULT_RATE, L3GD20_DEFAULT_RATE, L3GD20_TIMER_REDUCTION, M_PI_F, OK, hrt_call::period, reset(), SENSOR_POLLRATE_DEFAULT, SENSOR_POLLRATE_EXTERNAL, SENSOR_POLLRATE_MANUAL, SENSOR_POLLRATE_MAX, SENSORIOCGPOLLRATE, SENSORIOCRESET, SENSORIOCSPOLLRATE, SENSORIOCSQUEUEDEPTH, set_driver_lowpass_filter(), set_range(), set_samplerate(), start(), and stop().
Referenced by l3gd20::reset(), l3gd20::start(), and l3gd20::test().
void L3GD20::measure () private
Fetch measurements from the sensor and update the report ring.
Definition at line 937 of file l3gd20.cpp.
References _bad_registers, _duplicates, _gyro_filter_x, _gyro_filter_y, _gyro_filter_z, _gyro_int, _gyro_range_scale, _gyro_scale, _gyro_topic, _orientation, _read, _reports, _rotation, _sample_perf, ADDR_INCREMENT, ADDR_OUT_TEMP, math::LowPassFilter2p::apply(), check_registers(), DIR_READ, gyro_report, hrt_absolute_time(), L3GD20_TEMP_OFFSET_CELSIUS, ORB_ID, orb_publish(), perf_begin(), perf_count(), perf_end(), perf_event_count(), Integrator::put(), rotate_3f(), SENSOR_BOARD_ROTATION_000_DEG, SENSOR_BOARD_ROTATION_090_DEG, SENSOR_BOARD_ROTATION_180_DEG, SENSOR_BOARD_ROTATION_270_DEG, status, STATUS_ZYXDA, gyro_calibration_s::x_offset, gyro_calibration_s::x_scale, gyro_calibration_s::y_offset, gyro_calibration_s::y_scale, gyro_calibration_s::z_offset, and gyro_calibration_s::z_scale.
Referenced by init(), measure_trampoline(), and read().
void L3GD20::measure_trampoline (void * arg) static private
Static trampoline from the hrt_call context; because we don't have a generic hrt wrapper yet.
Called by the HRT in interrupt context at the specified rate if automatic polling is enabled.
Parameters
arg Instance pointer for the driver that is polling.
Definition at line 898 of file l3gd20.cpp.
References measure().
Referenced by start().
void L3GD20::modify_reg (unsigned reg, uint8_t clearbits, uint8_t setbits) private
Modify a register in the L3GD20.
Bits are cleared before bits are set.
Parameters
reg The register to modify.
clearbits Bits in the register to clear.
setbits Bits in the register to set.
Definition at line 732 of file l3gd20.cpp.
References read_reg(), and write_checked_reg().
L3GD20 L3GD20::operator= (const L3GD20 &) private
void L3GD20::print_info ()
Diagnostics - print some basic information about the driver.
Definition at line 1065 of file l3gd20.cpp.
References _bad_registers, _checked_next, _checked_registers, _checked_values, _duplicates, _errors, _read, _reports, _sample_perf, L3GD20_NUM_CHECKED_REGISTERS, perf_print_counter(), and read_reg().
Referenced by l3gd20::info().
void L3GD20::print_registers ()
Definition at line 1088 of file l3gd20.cpp.
References read_reg().
Referenced by l3gd20::regdump().
int L3GD20::probe () protected virtual
Definition at line 495 of file l3gd20.cpp.
References _checked_values, _is_l3g4200d, _orientation, ADDR_WHO_AM_I, OK, read_reg(), SENSOR_BOARD_ROTATION_180_DEG, SENSOR_BOARD_ROTATION_DEFAULT, WHO_I_AM, WHO_I_AM_H, and WHO_I_AM_L3G4200D.
ssize_t L3GD20::read (struct file * filp, char * buffer, size_t buflen) virtual
Definition at line 529 of file l3gd20.cpp.
References _call_interval, _reports, gyro_report, and measure().
Referenced by l3gd20::test().
uint8_t L3GD20::read_reg (unsigned reg) private
Read a register from the L3GD20.
Parameters
The register to read.
Returns
The value that was read.
Definition at line 695 of file l3gd20.cpp.
References DIR_READ.
Referenced by check_registers(), disable_i2c(), modify_reg(), print_info(), print_registers(), and probe().
void L3GD20::reset () private
Reset the driver.
Definition at line 871 of file l3gd20.cpp.
References _read, ADDR_CTRL_REG1, ADDR_CTRL_REG2, ADDR_CTRL_REG3, ADDR_CTRL_REG4, ADDR_CTRL_REG5, ADDR_FIFO_CTRL_REG, disable_i2c(), FIFO_CTRL_BYPASS_MODE, L3GD20_DEFAULT_FILTER_FREQ, L3GD20_DEFAULT_RANGE_DPS, L3GD20_DEFAULT_RATE, REG1_POWER_NORMAL, REG1_X_ENABLE, REG1_Y_ENABLE, REG1_Z_ENABLE, REG4_BDU, REG5_FIFO_ENABLE, set_driver_lowpass_filter(), set_range(), set_samplerate(), and write_checked_reg().
Referenced by init(), and ioctl().
int L3GD20::self_test () private
Self test.
Returns
0 on success, 1 on failure
Definition at line 1112 of file l3gd20.cpp.
References _gyro_scale, L3GD20_MAX_OFFSET, gyro_calibration_s::x_offset, gyro_calibration_s::x_scale, gyro_calibration_s::y_offset, gyro_calibration_s::y_scale, gyro_calibration_s::z_offset, and gyro_calibration_s::z_scale.
void L3GD20::set_driver_lowpass_filter (float samplerate, float bandwidth) private
Set the lowpass filter of the driver.
Parameters
samplerate The current samplerate
frequency The cutoff frequency for the lowpass filter
Definition at line 818 of file l3gd20.cpp.
References _gyro_filter_x, _gyro_filter_y, _gyro_filter_z, and math::LowPassFilter2p::set_cutoff_frequency().
Referenced by ioctl(), and reset().
int L3GD20::set_range (unsigned max_dps) private
Set the L3GD20 measurement range.
Parameters
max_dps The measurement range is set to permit reading at least this rate in degrees per second. Zero selects the maximum supported range.
Returns
OK if the value can be supported, -ERANGE otherwise.
Definition at line 743 of file l3gd20.cpp.
References _gyro_range_rad_s, _gyro_range_scale, ADDR_CTRL_REG4, f(), M_PI_F, OK, RANGE_2000DPS, RANGE_250DPS, RANGE_500DPS, REG4_BDU, and write_checked_reg().
Referenced by ioctl(), and reset().
int L3GD20::set_samplerate (unsigned frequency) private
Set the L3GD20 internal sampling frequency.
Parameters
frequency The internal sampling frequency is set to not less than this value. Zero selects the maximum rate supported.
Returns
OK if the value can be supported.
Definition at line 780 of file l3gd20.cpp.
References _current_rate, _is_l3g4200d, ADDR_CTRL_REG1, GYRO_SAMPLERATE_DEFAULT, OK, RATE_190HZ_LP_50HZ, RATE_380HZ_LP_50HZ, RATE_760HZ_LP_50HZ, RATE_95HZ_LP_25HZ, REG1_POWER_NORMAL, REG1_X_ENABLE, REG1_Y_ENABLE, REG1_Z_ENABLE, and write_checked_reg().
Referenced by ioctl(), and reset().
void L3GD20::start () private
Start automatic measurement.
Definition at line 826 of file l3gd20.cpp.
References _call, _call_interval, _reports, hrt_call_every(), L3GD20_TIMER_REDUCTION, measure_trampoline(), and stop().
Referenced by ioctl().
void L3GD20::stop () private
Stop automatic measurement.
Definition at line 842 of file l3gd20.cpp.
References _call, and hrt_cancel().
Referenced by ioctl(), start(), and ~L3GD20().
void L3GD20::test_error ()
Definition at line 1105 of file l3gd20.cpp.
References ADDR_CTRL_REG3, and write_reg().
Referenced by l3gd20::test_error().
void L3GD20::write_checked_reg (unsigned reg, uint8_t value) private
Write a register in the L3GD20, updating _checked_values.
Parameters
reg The register to write.
value The new value to write.
Definition at line 719 of file l3gd20.cpp.
References _checked_registers, _checked_values, L3GD20_NUM_CHECKED_REGISTERS, and write_reg().
Referenced by disable_i2c(), modify_reg(), reset(), set_range(), and set_samplerate().
void L3GD20::write_reg (unsigned reg, uint8_t value) private
Write a register in the L3GD20.
Parameters
reg The register to write.
value The new value to write.
Definition at line 708 of file l3gd20.cpp.
References DIR_WRITE.
Referenced by check_registers(), disable_i2c(), test_error(), and write_checked_reg().
Member Data Documentation
perf_counter_t L3GD20::_bad_registers private
Definition at line 241 of file l3gd20.cpp.
Referenced by check_registers(), L3GD20(), measure(), print_info(), and ~L3GD20().
struct hrt_call L3GD20::_call private
Definition at line 222 of file l3gd20.cpp.
Referenced by ioctl(), start(), and stop().
unsigned L3GD20::_call_interval private
Definition at line 223 of file l3gd20.cpp.
Referenced by ioctl(), L3GD20(), read(), and start().
uint8_t L3GD20::_checked_next private
Definition at line 263 of file l3gd20.cpp.
Referenced by check_registers(), L3GD20(), and print_info().
const uint8_t L3GD20::_checked_registers static private
Initial value:
= { ADDR_WHO_AM_I,
                                       ADDR_CTRL_REG1,
                                       ADDR_CTRL_REG2,
                                       ADDR_CTRL_REG3,
                                       ADDR_CTRL_REG4,
                                       ADDR_CTRL_REG5,
                                       ADDR_FIFO_CTRL_REG,
                                       ADDR_LOW_ODR
                                     }
Definition at line 261 of file l3gd20.cpp.
Referenced by check_registers(), print_info(), and write_checked_reg().
uint8_t L3GD20::_checked_values[L3GD20_NUM_CHECKED_REGISTERS] private
Definition at line 262 of file l3gd20.cpp.
Referenced by check_registers(), print_info(), probe(), and write_checked_reg().
int L3GD20::_class_instance private
Definition at line 232 of file l3gd20.cpp.
Referenced by init(), L3GD20(), and ~L3GD20().
unsigned L3GD20::_current_rate private
Definition at line 234 of file l3gd20.cpp.
Referenced by ioctl(), L3GD20(), and set_samplerate().
perf_counter_t L3GD20::_duplicates private
Definition at line 242 of file l3gd20.cpp.
Referenced by L3GD20(), measure(), print_info(), and ~L3GD20().
perf_counter_t L3GD20::_errors private
Definition at line 240 of file l3gd20.cpp.
Referenced by L3GD20(), print_info(), and ~L3GD20().
math::LowPassFilter2p L3GD20::_gyro_filter_x private
Definition at line 246 of file l3gd20.cpp.
Referenced by ioctl(), L3GD20(), measure(), and set_driver_lowpass_filter().
math::LowPassFilter2p L3GD20::_gyro_filter_y private
Definition at line 247 of file l3gd20.cpp.
Referenced by L3GD20(), measure(), and set_driver_lowpass_filter().
math::LowPassFilter2p L3GD20::_gyro_filter_z private
Definition at line 248 of file l3gd20.cpp.
Referenced by L3GD20(), measure(), and set_driver_lowpass_filter().
Integrator L3GD20::_gyro_int private
Definition at line 250 of file l3gd20.cpp.
Referenced by L3GD20(), and measure().
float L3GD20::_gyro_range_rad_s private
Definition at line 229 of file l3gd20.cpp.
Referenced by ioctl(), L3GD20(), and set_range().
float L3GD20::_gyro_range_scale private
Definition at line 228 of file l3gd20.cpp.
Referenced by L3GD20(), measure(), and set_range().
struct gyro_calibration_s L3GD20::_gyro_scale private
Definition at line 227 of file l3gd20.cpp.
Referenced by ioctl(), L3GD20(), measure(), and self_test().
orb_advert_t L3GD20::_gyro_topic private
Definition at line 230 of file l3gd20.cpp.
Referenced by init(), L3GD20(), and measure().
bool L3GD20::_is_l3g4200d private
Definition at line 253 of file l3gd20.cpp.
Referenced by ioctl(), L3GD20(), probe(), and set_samplerate().
int L3GD20::_orb_class_instance private
Definition at line 231 of file l3gd20.cpp.
Referenced by init(), and L3GD20().
unsigned L3GD20::_orientation private
Definition at line 235 of file l3gd20.cpp.
Referenced by L3GD20(), measure(), and probe().
unsigned L3GD20::_read private
Definition at line 237 of file l3gd20.cpp.
Referenced by L3GD20(), measure(), print_info(), and reset().
uint8_t L3GD20::_register_wait private
Definition at line 244 of file l3gd20.cpp.
Referenced by check_registers(), and L3GD20().
ringbuffer::RingBuffer* L3GD20::_reports private
Definition at line 225 of file l3gd20.cpp.
Referenced by init(), ioctl(), L3GD20(), measure(), print_info(), read(), start(), and ~L3GD20().
enum Rotation L3GD20::_rotation private
Definition at line 255 of file l3gd20.cpp.
Referenced by L3GD20(), and measure().
perf_counter_t L3GD20::_sample_perf private
Definition at line 239 of file l3gd20.cpp.
Referenced by L3GD20(), measure(), print_info(), and ~L3GD20().
The documentation for this class was generated from the following file:
src/drivers/imu/l3gd20/l3gd20.cpp