PX4 Firmware: df_ak8963_wrapper Namespace Reference
df_ak8963_wrapper Namespace Reference
Functions
int start (enum Rotation rotation)
int stop ()
Stop the driver.
int info ()
Print a little info about the driver.
void usage ()
Prints info about the driver argument usage.
Variables
DfAK8963Wrapper * g_dev = nullptr
Function Documentation
info()
int df_ak8963_wrapper::info ()
Print a little info about the driver.
Definition at line 386 of file df_ak8963_wrapper.cpp.
References DfAK8963Wrapper::print_calibration().
Referenced by df_ak8963_wrapper_main().
start()
int df_ak8963_wrapper::start (enum Rotation rotation)
Definition at line 332 of file df_ak8963_wrapper.cpp.
References DfAK8963Wrapper::DfAK8963Wrapper(), and DfAK8963Wrapper::start().
Referenced by df_ak8963_wrapper_main().
stop()
int df_ak8963_wrapper::stop ()
Stop the driver.
Stop the driver.
Definition at line 363 of file df_ak8963_wrapper.cpp.
References g_dev, and DfAK8963Wrapper::stop().
Referenced by df_ak8963_wrapper_main().
usage()
void df_ak8963_wrapper::usage (void)
Prints info about the driver argument usage.
Prints info about the driver argument usage.
Definition at line 401 of file df_ak8963_wrapper.cpp.
Referenced by df_ak8963_wrapper_main().
Variable Documentation
g_dev
DfAK8963Wrapper* df_ak8963_wrapper::g_dev = nullptr
Definition at line 325 of file df_ak8963_wrapper.cpp.
Referenced by stop().