PX4 Firmware: src/platforms/posix/drivers/df_mpu6050_wrapper/df_mpu6050_wrapper.cpp File Reference
df_mpu6050_wrapper.cpp File Reference
Lightweight driver to access the MPU6050 of the DriverFramework.
#include <px4_config.h>
#include <sys/types.h>
#include <sys/stat.h>
#include <stdint.h>
#include <stddef.h>
#include <stdlib.h>
#include <string.h>
#include <math.h>
#include <unistd.h>
#include <px4_getopt.h>
#include <errno.h>
#include <systemlib/err.h>
#include <perf/perf_counter.h>
#include <systemlib/mavlink_log.h>
#include <drivers/drv_hrt.h>
#include <drivers/drv_accel.h>
#include <drivers/drv_gyro.h>
#include <drivers/device/integrator.h>
#include <lib/conversion/rotation.h>
#include <uORB/topics/parameter_update.h>
#include <mpu6050/MPU6050.hpp>
#include <DevMgr.hpp>
Classes
class DfMPU6050Wrapper
struct DfMPU6050Wrapper::accel_calibration_s
struct DfMPU6050Wrapper::gyro_calibration_s
Namespaces
df_mpu6050_wrapper
Macros
#define MPU6050_NEVER_AUTOPUBLISH_US 0
Functions
__EXPORT int df_mpu6050_wrapper_main (int argc, char *argv[])
int df_mpu6050_wrapper::start (enum Rotation rotation)
int df_mpu6050_wrapper::stop ()
Stop the driver.
int df_mpu6050_wrapper::info ()
Print a little info about the driver.
void df_mpu6050_wrapper::usage ()
Prints info about the driver argument usage.
Variables
DfMPU6050Wrapper * df_mpu6050_wrapper::g_dev = nullptr
Detailed Description
Lightweight driver to access the MPU6050 of the DriverFramework.
Definition in file df_mpu6050_wrapper.cpp.
Macro Definition Documentation
#define MPU6050_NEVER_AUTOPUBLISH_US 0
Definition at line 69 of file df_mpu6050_wrapper.cpp.
Referenced by DfMPU6050Wrapper::DfMPU6050Wrapper().
Function Documentation
int df_mpu6050_wrapper_main (int argc, char * argv[])
Definition at line 667 of file df_mpu6050_wrapper.cpp.
References df_mpu6050_wrapper::info(), px4_getopt(), ROTATION_NONE, df_mpu6050_wrapper::start(), df_mpu6050_wrapper::stop(), and df_mpu6050_wrapper::usage().