PX4 Firmware: src/drivers/differential_pressure/ms5525/MS5525_main.cpp File Reference
MS5525_main.cpp File Reference
#include "MS5525.hpp"
Namespaces
ms5525_airspeed
Functions
__EXPORT int ms5525_airspeed_main (int argc, char *argv[])
int ms5525_airspeed::start ()
Attempt to start driver on all available I2C busses.
int ms5525_airspeed::start_bus (uint8_t i2c_bus)
Start the driver on a specific bus.
int ms5525_airspeed::stop ()
Stop the driver.
int ms5525_airspeed::reset ()
Reset the driver.
static void ms5525_airspeed_usage ()
Variables
MS5525 * ms5525_airspeed::g_dev = nullptr
Function Documentation
ms5525_airspeed_main()
int ms5525_airspeed_main (int argc, char * argv[])
Definition at line 173 of file MS5525_main.cpp.
References ms5525_airspeed_usage(), PX4_I2C_BUS_DEFAULT, ms5525_airspeed::reset(), ms5525_airspeed::start(), ms5525_airspeed::start_bus(), and ms5525_airspeed::stop().
ms5525_airspeed_usage()
static void ms5525_airspeed_usage () static
Definition at line 162 of file MS5525_main.cpp.
References PX4_I2C_BUS_DEFAULT.
Referenced by ms5525_airspeed_main().