PX4 Firmware: PCA9685 Class Reference
PCA9685 Class Reference
Public Member Functions
PCA9685 (int bus=PCA9685_BUS, uint8_t address=ADDR)
virtual ~PCA9685 ()=default
virtual int init ()
virtual int ioctl (struct file *filp, int cmd, unsigned long arg)
virtual int info ()
virtual int reset ()
bool is_running ()
Private Member Functions
void i2cpwm ()
Main loop function.
int setPWMFreq (float freq)
Helper function to set the pwm frequency.
int setPWM (uint8_t num, uint16_t on, uint16_t off)
Helper function to set the demanded pwm value.
int setPin (uint8_t num, uint16_t val, bool invert=false)
Sets pin without having to deal with on/off tick placement and properly handles a zero value as completely off.
int read8 (uint8_t addr, uint8_t &value)
int write8 (uint8_t addr, uint8_t value)
Static Private Member Functions
static void i2cpwm_trampoline (void *arg)
Set to true after the first call of i2cpwm in mode IOX_MODE_ON.
Private Attributes
work_s _work
enum IOX_MODE _mode
bool _running
int _i2cpwm_interval
bool _should_run
perf_counter_t _comms_errors
uint8_t _msg [6]
int _actuator_controls_sub
struct actuator_controls_s _actuator_controls
uint16_t _current_values [actuator_controls_s::NUM_ACTUATOR_CONTROLS]
stores the current pwm output values as sent to the setPin()
bool _mode_on_initialized
Detailed Description
Definition at line 111 of file pca9685.cpp.
Constructor & Destructor Documentation
PCA9685::PCA9685 (int bus = PCA9685_BUS, uint8_t address = ADDR)
Definition at line 185 of file pca9685.cpp.
References _current_values, and _msg.
Referenced by pca9685_main().
virtual PCA9685::~PCA9685 () virtual default
Member Function Documentation
void PCA9685::i2cpwm () private
Main loop function.
Definition at line 298 of file pca9685.cpp.
References _actuator_controls, _actuator_controls_sub, _current_values, _i2cpwm_interval, _mode, _mode_on_initialized, _running, _should_run, actuator_controls_s::control, DEVICE_DEBUG, f(), i2cpwm_trampoline(), IOX_MODE_OFF, IOX_MODE_TEST_OUT, M_PI_F, orb_check(), orb_copy(), ORB_ID, orb_set_interval(), orb_subscribe(), PCA9685_PWMCENTER, PCA9685_PWMFREQ, PCA9685_PWMMAX, PCA9685_PWMMIN, PCA9685_SCALE, and setPin().
Referenced by i2cpwm_trampoline().
void PCA9685::i2cpwm_trampoline (void * arg) static private
Set to true after the first call of i2cpwm in mode IOX_MODE_ON.
Definition at line 287 of file pca9685.cpp.
References i2cpwm().
Referenced by i2cpwm(), and ioctl().
int PCA9685::info () virtual
Definition at line 272 of file pca9685.cpp.
References _mode, is_running(), OK, and warnx.
int PCA9685::init () virtual
Definition at line 202 of file pca9685.cpp.
References lis3mdl::init(), OK, PCA9685_PWMFREQ, reset(), and setPWMFreq().
int PCA9685::ioctl (struct file * filp, int cmd, unsigned long arg) virtual
Definition at line 223 of file pca9685.cpp.
References _mode, _running, i2cpwm_trampoline(), IOX_MODE_OFF, IOX_MODE_ON, IOX_MODE_TEST_OUT, IOX_SET_MODE, OK, and warnx.
Referenced by pca9685_main().
bool PCA9685::is_running () inline
Definition at line 122 of file pca9685.cpp.
References _running.
Referenced by info().
int PCA9685::read8 (uint8_t addr, uint8_t & value) private
Definition at line 468 of file pca9685.cpp.
References _comms_errors, DEVICE_LOG, OK, and perf_count().
Referenced by setPWMFreq().
int PCA9685::reset (void) virtual
Definition at line 495 of file pca9685.cpp.
References PCA9685_MODE1, warnx, and write8().
Referenced by init().
int PCA9685::setPin (uint8_t num, uint16_t val, bool invert = false) private
Sets pin without having to deal with on/off tick placement and properly handles a zero value as completely off.
Optional invert parameter supports inverting the pulse for sinking to ground.
Parameters
num pwm output number
val should be a value from 0 to 4095 inclusive.
Definition at line 380 of file pca9685.cpp.
References PX4_ERROR, and setPWM().
Referenced by i2cpwm().
int PCA9685::setPWM (uint8_t num, uint16_t on, uint16_t off) private
Helper function to set the demanded pwm value.
Parameters
num pwm output number
Definition at line 358 of file pca9685.cpp.
References _comms_errors, _msg, DEVICE_LOG, LED0_ON_L, OK, and perf_count().
Referenced by setPin().
int PCA9685::setPWMFreq (float freq) private
Helper function to set the pwm frequency.
Definition at line 418 of file pca9685.cpp.
References f(), OK, PCA9685_MODE1, PCA9685_PRESCALE, read8(), usleep(), and write8().
Referenced by init().
int PCA9685::write8 (uint8_t addr, uint8_t value) private
Definition at line 503 of file pca9685.cpp.
References _comms_errors, _msg, DEVICE_LOG, OK, and perf_count().
Referenced by reset(), and setPWMFreq().
Member Data Documentation
struct actuator_controls_s PCA9685::_actuator_controls private
Definition at line 137 of file pca9685.cpp.
Referenced by i2cpwm().
int PCA9685::_actuator_controls_sub private
Definition at line 136 of file pca9685.cpp.
Referenced by i2cpwm().
perf_counter_t PCA9685::_comms_errors private
Definition at line 132 of file pca9685.cpp.
Referenced by read8(), setPWM(), and write8().
uint16_t PCA9685::_current_values[actuator_controls_s::NUM_ACTUATOR_CONTROLS] private
stores the current pwm output values as sent to the setPin()
Definition at line 138 of file pca9685.cpp.
Referenced by i2cpwm(), and PCA9685().
int PCA9685::_i2cpwm_interval private
Definition at line 130 of file pca9685.cpp.
Referenced by i2cpwm().
enum IOX_MODE PCA9685::_mode private
Definition at line 128 of file pca9685.cpp.
Referenced by i2cpwm(), info(), and ioctl().
bool PCA9685::_mode_on_initialized private
Definition at line 141 of file pca9685.cpp.
Referenced by i2cpwm().
uint8_t PCA9685::_msg[6] private
Definition at line 134 of file pca9685.cpp.
Referenced by PCA9685(), setPWM(), and write8().
bool PCA9685::_running private
Definition at line 129 of file pca9685.cpp.
Referenced by i2cpwm(), ioctl(), and is_running().
bool PCA9685::_should_run private
Definition at line 131 of file pca9685.cpp.
Referenced by i2cpwm().
work_s PCA9685::_work private
Definition at line 125 of file pca9685.cpp.
The documentation for this class was generated from the following file:
src/drivers/pca9685/pca9685.cpp