PX4 Firmware: ADIS16477 Class Reference
ADIS16477 Class Reference
#include <ADIS16477.hpp>
Classes
struct _accel_scale
struct _call
product code
struct _gyro_scale
struct ADISReport
Report conversation with in the ADIS16477, including command byte and interrupt status.
Public Member Functions
ADIS16477 (int bus, const char *path_accel, const char *path_gyro, uint32_t device, enum Rotation rotation)
virtual ~ADIS16477 ()
virtual int init ()
virtual int ioctl (struct file *filp, int cmd, unsigned long arg)
void print_info ()
Protected Member Functions
virtual int probe ()
virtual int gyro_ioctl (struct file *filp, int cmd, unsigned long arg)
Private Member Functions
void start ()
Start automatic measurement.
void stop ()
Stop automatic measurement.
int reset ()
Reset chip.
int measure ()
Fetch measurements from the sensor and update the report buffers.
bool publish_accel (const ADISReport &report)
bool publish_gyro (const ADISReport &report)
uint16_t read_reg16 (uint8_t reg)
void write_reg (uint8_t reg, uint8_t value)
void write_reg16 (uint8_t reg, uint16_t value)
bool self_test ()
void _set_dlpf_filter (uint16_t frequency_hz)
void _set_factory_default ()
void _set_sample_rate (uint16_t desired_sample_rate_hz)
void _set_gyro_dyn_range (uint16_t desired_gyro_dyn_range)
ADIS16477 (const ADIS16477 &)
ADIS16477 operator= (const ADIS16477 &)
Static Private Member Functions
static void measure_trampoline (void *arg)
Static trampoline from the hrt_call context; because we don't have a generic hrt wrapper yet.
Private Attributes
ADIS16477_gyro * _gyro {nullptr}
uint16_t _product {0}
unsigned _call_interval {0}
float _gyro_range_scale {0.025f}
float _gyro_range_rad_s {math::radians(500.0f)}
float _accel_range_scale {1.25f * CONSTANTS_ONE_G / 1000.0f}
float _accel_range_m_s2 {40.0f * CONSTANTS_ONE_G}
orb_advert_t _accel_topic {nullptr}
int _accel_orb_class_instance {-1}
int _accel_class_instance {-1}
unsigned _sample_rate {100}
perf_counter_t _sample_perf
perf_counter_t _bad_transfers
math::LowPassFilter2p _gyro_filter_x {ADIS16477_GYRO_DEFAULT_RATE, ADIS16477_GYRO_DEFAULT_DRIVER_FILTER_FREQ}
math::LowPassFilter2p _gyro_filter_y {ADIS16477_GYRO_DEFAULT_RATE, ADIS16477_GYRO_DEFAULT_DRIVER_FILTER_FREQ}
math::LowPassFilter2p _gyro_filter_z {ADIS16477_GYRO_DEFAULT_RATE, ADIS16477_GYRO_DEFAULT_DRIVER_FILTER_FREQ}
math::LowPassFilter2p _accel_filter_x {ADIS16477_ACCEL_DEFAULT_RATE, ADIS16477_ACCEL_DEFAULT_DRIVER_FILTER_FREQ}
math::LowPassFilter2p _accel_filter_y {ADIS16477_ACCEL_DEFAULT_RATE, ADIS16477_ACCEL_DEFAULT_DRIVER_FILTER_FREQ}
math::LowPassFilter2p _accel_filter_z {ADIS16477_ACCEL_DEFAULT_RATE, ADIS16477_ACCEL_DEFAULT_DRIVER_FILTER_FREQ}
Integrator _accel_int {1000000 / ADIS16477_ACCEL_MAX_OUTPUT_RATE, false}
Integrator _gyro_int {1000000 / ADIS16477_GYRO_MAX_OUTPUT_RATE, true}
enum Rotation _rotation
perf_counter_t _controller_latency_perf
Friends
class ADIS16477_gyro
Detailed Description
Definition at line 64 of file ADIS16477.hpp.
Constructor & Destructor Documentation
ADIS16477::ADIS16477 (int bus, const char * path_accel, const char * path_gyro, uint32_t device, enum Rotation rotation)
Definition at line 77 of file ADIS16477.cpp.
References device::Device::_device_id, _gyro, device::Device::DeviceId::devid, device::Device::DeviceId::devid_s, device::Device::DeviceStructure::devtype, DRV_ACC_DEVTYPE_ADIS16477, DRV_GYR_DEVTYPE_ADIS16477, and GPIO_SPI1_RESET_ADIS16477.
ADIS16477::~ADIS16477 () virtual
Definition at line 111 of file ADIS16477.cpp.
References _accel_class_instance, _bad_transfers, _gyro, _sample_perf, ACCEL_BASE_DEVICE_PATH, perf_free(), and stop().
ADIS16477::ADIS16477 (const ADIS16477 &) private
Member Function Documentation
void ADIS16477::_set_dlpf_filter (uint16_t frequency_hz) private
Definition at line 257 of file ADIS16477.cpp.
void ADIS16477::_set_factory_default () private
Definition at line 270 of file ADIS16477.cpp.
void ADIS16477::_set_gyro_dyn_range (uint16_t desired_gyro_dyn_range) private
Definition at line 277 of file ADIS16477.cpp.
Referenced by gyro_ioctl().
void ADIS16477::_set_sample_rate (uint16_t desired_sample_rate_hz) private
Definition at line 250 of file ADIS16477.cpp.
Referenced by gyro_ioctl(), and ioctl().
int ADIS16477::gyro_ioctl (struct file * filp, int cmd, unsigned long arg) protected virtual
Definition at line 416 of file ADIS16477.cpp.
References _gyro_range_rad_s, _sample_rate, _set_gyro_dyn_range(), _set_sample_rate(), GYROIOCGRANGE, GYROIOCGSAMPLERATE, GYROIOCGSCALE, GYROIOCSRANGE, GYROIOCSSAMPLERATE, GYROIOCSSCALE, ioctl(), M_PI_F, OK, SENSORIOCGPOLLRATE, SENSORIOCRESET, and SENSORIOCSPOLLRATE.
Referenced by ADIS16477_gyro::ioctl().
int ADIS16477::init () virtual
Definition at line 129 of file ADIS16477.cpp.
References _accel_class_instance, _accel_orb_class_instance, _accel_topic, _gyro, ADIS16477_gyro::_gyro_orb_class_instance, ADIS16477_gyro::_gyro_topic, ACCEL_BASE_DEVICE_PATH, accel_report, DEVICE_DEBUG, gyro_report, hrt_absolute_time(), ADIS16477_gyro::init(), lis3mdl::init(), measure(), OK, orb_advertise_multi(), ORB_ID, ORB_PRIO_MAX, PX4_ERR, and PX4_ERROR.
int ADIS16477::ioctl (struct file * filp, int cmd, unsigned long arg) virtual
Definition at line 302 of file ADIS16477.cpp.
References _accel_filter_x, _accel_filter_y, _accel_filter_z, _accel_range_m_s2, _call_interval, _gyro_filter_x, _gyro_filter_y, _gyro_filter_z, _sample_rate, _set_sample_rate(), ACCELIOCGRANGE, ACCELIOCGSAMPLERATE, ACCELIOCGSCALE, ACCELIOCSRANGE, ACCELIOCSSAMPLERATE, ACCELIOCSSCALE, ADIS16477_ACCEL_DEFAULT_RATE, CONSTANTS_ONE_G, f(), math::LowPassFilter2p::get_cutoff_freq(), OK, reset(), SENSOR_POLLRATE_DEFAULT, SENSOR_POLLRATE_EXTERNAL, SENSOR_POLLRATE_MANUAL, SENSOR_POLLRATE_MAX, SENSORIOCGPOLLRATE, SENSORIOCRESET, SENSORIOCSPOLLRATE, math::LowPassFilter2p::set_cutoff_frequency(), start(), stop(), accel_calibration_s::x_scale, accel_calibration_s::y_scale, and accel_calibration_s::z_scale.
Referenced by gyro_ioctl().
int ADIS16477::measure () private
Fetch measurements from the sensor and update the report buffers.
Definition at line 521 of file ADIS16477.cpp.
References _bad_transfers, _sample_perf, ADIS16477::ADISReport::checksum, ADIS16477::ADISReport::cmd, DEVICE_DEBUG, ADIS16477::ADISReport::diag_stat, DIR_READ, GLOB_CMD, OK, perf_begin(), perf_end(), perf_event_count(), publish_accel(), and publish_gyro().
Referenced by init(), and measure_trampoline().
void ADIS16477::measure_trampoline (void * arg) static private
Static trampoline from the hrt_call context; because we don't have a generic hrt wrapper yet.
Called by the HRT in interrupt context at the specified rate if automatic polling is enabled.
Parameters
arg Instance pointer for the driver that is polling.
Definition at line 512 of file ADIS16477.cpp.
References measure().
Referenced by start().
ADIS16477 ADIS16477::operator= (const ADIS16477 &) private
void ADIS16477::print_info ()
Definition at line 676 of file ADIS16477.cpp.
References _bad_transfers, device::Device::_device_id, _gyro, _sample_perf, device::Device::DeviceId::devid, perf_print_counter(), and PX4_INFO.
Referenced by adis16477::info().
int ADIS16477::probe () protected virtual
Definition at line 218 of file ADIS16477.cpp.
References _product, DEVICE_DEBUG, PROD_ID, PROD_ID_ADIS16477, PX4_ERR, PX4_OK, read_reg16(), reset(), and self_test().
bool ADIS16477::publish_accel (const ADISReport & report) private
Definition at line 579 of file ADIS16477.cpp.
References _accel_filter_x, _accel_filter_y, _accel_filter_z, _accel_int, _accel_range_scale, _accel_topic, _bad_transfers, _rotation, accel_report, ADIS16477::ADISReport::accel_x, ADIS16477::ADISReport::accel_y, ADIS16477::ADISReport::accel_z, math::LowPassFilter2p::apply(), hrt_absolute_time(), ORB_ID, orb_publish(), perf_event_count(), Integrator::put(), rotate_3f(), and ADIS16477::ADISReport::temp.
Referenced by measure().
bool ADIS16477::publish_gyro (const ADISReport & report) private
Definition at line 627 of file ADIS16477.cpp.
References _bad_transfers, device::Device::_device_id, _gyro, _gyro_filter_x, _gyro_filter_y, _gyro_filter_z, _gyro_int, _gyro_range_scale, ADIS16477_gyro::_gyro_topic, _rotation, math::LowPassFilter2p::apply(), device::Device::DeviceId::devid, gyro_report, ADIS16477::ADISReport::gyro_x, ADIS16477::ADISReport::gyro_y, ADIS16477::ADISReport::gyro_z, hrt_absolute_time(), ORB_ID, orb_publish(), perf_event_count(), Integrator::put(), math::radians(), rotate_3f(), and ADIS16477::ADISReport::temp.
Referenced by measure().
uint16_t ADIS16477::read_reg16 (uint8_t reg) private
Definition at line 457 of file ADIS16477.cpp.
References DIR_READ, and T_STALL.
Referenced by probe(), and self_test().
int ADIS16477::reset () private
Reset chip.
Resets the chip and measurements ranges, but not scale and offset.
Definition at line 192 of file ADIS16477.cpp.
References DEVICE_DEBUG, GLOB_CMD, GPIO_SPI1_RESET_ADIS16477, OK, and write_reg16().
Referenced by ioctl(), and probe().
bool ADIS16477::self_test () private
Definition at line 282 of file ADIS16477.cpp.
References DEVICE_DEBUG, DIAG_STAT, GLOB_CMD, read_reg16(), and write_reg16().
Referenced by probe().
void ADIS16477::start () private
Start automatic measurement.
Definition at line 494 of file ADIS16477.cpp.
References _call_interval, hrt_call_every(), measure_trampoline(), and stop().
Referenced by ioctl().
void ADIS16477::stop () private
Stop automatic measurement.
Definition at line 506 of file ADIS16477.cpp.
References hrt_cancel().
Referenced by ioctl(), start(), and ~ADIS16477().
void ADIS16477::write_reg (uint8_t reg, uint8_t value) private
Definition at line 471 of file ADIS16477.cpp.
void ADIS16477::write_reg16 (uint8_t reg, uint16_t value) private
Definition at line 480 of file ADIS16477.cpp.
References DIR_WRITE, and T_STALL.
Referenced by reset(), and self_test().
Friends And Related Function Documentation
friend class ADIS16477_gyro friend
Definition at line 79 of file ADIS16477.hpp.
Member Data Documentation
int ADIS16477::_accel_class_instance {-1} private
Definition at line 106 of file ADIS16477.hpp.
Referenced by init(), and ~ADIS16477().
math::LowPassFilter2p ADIS16477::_accel_filter_x {ADIS16477_ACCEL_DEFAULT_RATE, ADIS16477_ACCEL_DEFAULT_DRIVER_FILTER_FREQ} private
Definition at line 117 of file ADIS16477.hpp.
Referenced by ioctl(), and publish_accel().
math::LowPassFilter2p ADIS16477::_accel_filter_y {ADIS16477_ACCEL_DEFAULT_RATE, ADIS16477_ACCEL_DEFAULT_DRIVER_FILTER_FREQ} private
Definition at line 118 of file ADIS16477.hpp.
Referenced by ioctl(), and publish_accel().
math::LowPassFilter2p ADIS16477::_accel_filter_z {ADIS16477_ACCEL_DEFAULT_RATE, ADIS16477_ACCEL_DEFAULT_DRIVER_FILTER_FREQ} private
Definition at line 119 of file ADIS16477.hpp.
Referenced by ioctl(), and publish_accel().
Integrator ADIS16477::_accel_int {1000000 / ADIS16477_ACCEL_MAX_OUTPUT_RATE, false} private
Definition at line 121 of file ADIS16477.hpp.
Referenced by publish_accel().
int ADIS16477::_accel_orb_class_instance {-1} private
Definition at line 105 of file ADIS16477.hpp.
Referenced by init().
float ADIS16477::_accel_range_m_s2 {40.0f * CONSTANTS_ONE_G} private
Definition at line 101 of file ADIS16477.hpp.
Referenced by ioctl().
float ADIS16477::_accel_range_scale {1.25f * CONSTANTS_ONE_G / 1000.0f} private
Definition at line 100 of file ADIS16477.hpp.
Referenced by publish_accel().
orb_advert_t ADIS16477::_accel_topic {nullptr} private
Definition at line 103 of file ADIS16477.hpp.
Referenced by init(), and publish_accel().
perf_counter_t ADIS16477::_bad_transfers private
Definition at line 111 of file ADIS16477.hpp.
Referenced by measure(), print_info(), publish_accel(), publish_gyro(), and ~ADIS16477().
unsigned ADIS16477::_call_interval {0} private
Definition at line 89 of file ADIS16477.hpp.
Referenced by ioctl(), and start().
perf_counter_t ADIS16477::_controller_latency_perf private
Definition at line 126 of file ADIS16477.hpp.
ADIS16477_gyro* ADIS16477::_gyro {nullptr} private
Definition at line 84 of file ADIS16477.hpp.
Referenced by ADIS16477(), init(), print_info(), publish_gyro(), and ~ADIS16477().
math::LowPassFilter2p ADIS16477::_gyro_filter_x {ADIS16477_GYRO_DEFAULT_RATE, ADIS16477_GYRO_DEFAULT_DRIVER_FILTER_FREQ} private
Definition at line 113 of file ADIS16477.hpp.
Referenced by ioctl(), and publish_gyro().
math::LowPassFilter2p ADIS16477::_gyro_filter_y {ADIS16477_GYRO_DEFAULT_RATE, ADIS16477_GYRO_DEFAULT_DRIVER_FILTER_FREQ} private
Definition at line 114 of file ADIS16477.hpp.
Referenced by ioctl(), and publish_gyro().
math::LowPassFilter2p ADIS16477::_gyro_filter_z {ADIS16477_GYRO_DEFAULT_RATE, ADIS16477_GYRO_DEFAULT_DRIVER_FILTER_FREQ} private
Definition at line 115 of file ADIS16477.hpp.
Referenced by ioctl(), and publish_gyro().
Integrator ADIS16477::_gyro_int {1000000 / ADIS16477_GYRO_MAX_OUTPUT_RATE, true} private
Definition at line 122 of file ADIS16477.hpp.
Referenced by publish_gyro().
float ADIS16477::_gyro_range_rad_s {math::radians(500.0f)} private
Definition at line 95 of file ADIS16477.hpp.
Referenced by gyro_ioctl().
float ADIS16477::_gyro_range_scale {0.025f} private
Definition at line 94 of file ADIS16477.hpp.
Referenced by publish_gyro().
uint16_t ADIS16477::_product {0} private
Definition at line 86 of file ADIS16477.hpp.
Referenced by probe().
enum Rotation ADIS16477::_rotation private
Definition at line 124 of file ADIS16477.hpp.
Referenced by publish_accel(), and publish_gyro().
perf_counter_t ADIS16477::_sample_perf private
Definition at line 110 of file ADIS16477.hpp.
Referenced by measure(), print_info(), and ~ADIS16477().
unsigned ADIS16477::_sample_rate {100} private
Definition at line 108 of file ADIS16477.hpp.
Referenced by gyro_ioctl(), and ioctl().
The documentation for this class was generated from the following files:
src/drivers/imu/adis16477/ADIS16477.hpp
src/drivers/imu/adis16477/ADIS16477.cpp