PX4 Firmware: src/lib/parameters/flashparams/flashparams.c File Reference
flashparams.c File Reference
#include <px4_defines.h>
#include <px4_posix.h>
#include <px4_shutdown.h>
#include <string.h>
#include <stdbool.h>
#include <stdint.h>
#include <parameters/param.h>
#include "systemlib/uthash/utarray.h"
#include <parameters/tinybson/tinybson.h>
#include "flashparams.h"
#include "flashfs.h"
Classes
struct param_wbuf_s
Storage for modified parameters.
struct param_import_state
Macros
#define debug(fmt, args...) do { } while(0)
Functions
static int param_export_internal (bool only_unsaved)
static int param_import_callback (bson_decoder_t decoder, void *private, bson_node_t node)
static int param_import_internal (bool mark_saved)
int flash_param_save (void)
int flash_param_load (void)
int flash_param_import (void)
Macro Definition Documentation
#define debug (fmt, args...) do { } while(0)
Definition at line 62 of file flashparams.c.
Referenced by param_export_internal(), param_import_callback(), and param_import_internal().
Function Documentation
int flash_param_import (void)
Definition at line 367 of file flashparams.c.
Referenced by param_import().
int flash_param_load (void)
Definition at line 361 of file flashparams.c.
References param_import_internal(), and param_reset_all().
Referenced by param_load_default().
int flash_param_save (void)
Definition at line 356 of file flashparams.c.
References param_export_internal().
Referenced by param_save_default().
static int param_export_internal (bool only_unsaved) static
Definition at line 76 of file flashparams.c.
References BSON_BIN_BINARY, bson_encoder_append_binary(), bson_encoder_append_double(), bson_encoder_append_int(), bson_encoder_buf_data(), bson_encoder_buf_size(), bson_encoder_fini(), bson_encoder_init_buf(), debug, f(), param_value_u::f, param_value_u::i, OK, param_wbuf_s::param, param_get_value_ptr_external(), param_name(), param_size(), param_type(), PARAM_TYPE_FLOAT, PARAM_TYPE_INT32, PARAM_TYPE_STRUCT, PARAM_TYPE_STRUCT_MAX, param_values, parameter_flashfs_alloc(), parameter_flashfs_free(), parameter_flashfs_read(), parameter_flashfs_write(), parameters_token, PX4_ERR, px4_shutdown_lock(), px4_shutdown_unlock(), param_wbuf_s::unsaved, utarray_next, and param_wbuf_s::val.
Referenced by flash_param_save().
static int param_import_callback (bson_decoder_t decoder, void * private, bson_node_t node) static
Definition at line 212 of file flashparams.c.
References BSON_BIN_BINARY, BSON_BINDATA, bson_decoder_copy_data(), bson_decoder_data_pending(), BSON_DOUBLE, BSON_EOO, BSON_INT32, bson_node_s::d, debug, f(), bson_node_s::i, param_import_state::mark_saved, bson_node_s::name, param_wbuf_s::param, param_find_no_notification(), PARAM_INVALID, param_set_external(), param_size(), param_type(), PARAM_TYPE_FLOAT, PARAM_TYPE_INT32, PX4_WARN, state, bson_node_s::subtype, and bson_node_s::type.
Referenced by param_import_internal().
static int param_import_internal (bool mark_saved) static
Definition at line 325 of file flashparams.c.
References bson_decoder_init_buf(), bson_decoder_next(), debug, param_import_state::mark_saved, param_import_callback(), parameter_flashfs_read(), and parameters_token.
Referenced by flash_param_load().