PX4 Firmware: src/drivers/boards/px4-stm32f4discovery/init.c File Reference
init.c File Reference
#include <px4_config.h>
#include <stdbool.h>
#include <stdio.h>
#include <debug.h>
#include <errno.h>
#include "platform/cxxinitialize.h"
#include <nuttx/board.h>
#include <nuttx/spi/spi.h>
#include <nuttx/i2c/i2c_master.h>
#include <nuttx/sdio.h>
#include <nuttx/mmcsd.h>
#include <nuttx/analog/adc.h>
#include <nuttx/mm/gran.h>
#include <stm32.h>
#include "board_config.h"
#include <stm32_uart.h>
#include <arch/board/board.h>
#include <drivers/drv_hrt.h>
#include <drivers/drv_board_led.h>
#include <systemlib/cpuload.h>
#include <perf/perf_counter.h>
#include <parameters/param.h>
Macros
#define message printf
Functions
__EXPORT void stm32_boardinitialize (void)
__EXPORT int board_app_initialize (uintptr_t arg)
Macro Definition Documentation
#define message printf
Definition at line 95 of file init.c.
Function Documentation
__EXPORT int board_app_initialize (uintptr_t arg)
Definition at line 149 of file init.c.
References hrt_call_every(), hrt_init(), OK, param_init(), and ts_to_abstime().
__EXPORT void stm32_boardinitialize (void)
Definition at line 118 of file init.c.
References board_autoled_initialize().