PX4 Firmware: df_mpu6050_wrapper Namespace Reference
df_mpu6050_wrapper Namespace Reference
Functions
int start (enum Rotation rotation)
int stop ()
Stop the driver.
int info ()
Print a little info about the driver.
void usage ()
Prints info about the driver argument usage.
Variables
DfMPU6050Wrapper * g_dev = nullptr
Function Documentation
info()
int df_mpu6050_wrapper::info ()
Print a little info about the driver.
Definition at line 643 of file df_mpu6050_wrapper.cpp.
References DfMPU6050Wrapper::info().
Referenced by df_mpu6050_wrapper_main().
start()
int df_mpu6050_wrapper::start (enum Rotation rotation)
Definition at line 589 of file df_mpu6050_wrapper.cpp.
References DfMPU6050Wrapper::DfMPU6050Wrapper(), and DfMPU6050Wrapper::start().
Referenced by df_mpu6050_wrapper_main().
stop()
int df_mpu6050_wrapper::stop ()
Stop the driver.
Stop the driver.
Definition at line 620 of file df_mpu6050_wrapper.cpp.
References g_dev, and DfMPU6050Wrapper::stop().
Referenced by df_mpu6050_wrapper_main().
usage()
void df_mpu6050_wrapper::usage (void)
Prints info about the driver argument usage.
Prints info about the driver argument usage.
Definition at line 657 of file df_mpu6050_wrapper.cpp.
Referenced by df_mpu6050_wrapper_main().
Variable Documentation
g_dev
DfMPU6050Wrapper* df_mpu6050_wrapper::g_dev = nullptr
Definition at line 582 of file df_mpu6050_wrapper.cpp.
Referenced by stop().