PX4 Firmware: src/drivers/barometer/ms5611/ms5611_main.cpp File Reference
ms5611_main.cpp File Reference
#include "MS5611.hpp"
#include "ms5611.h"
Classes
struct ms5611::ms5611_bus_option
Namespaces
ms5611
Local functions in support of the shell command.
Macros
#define NUM_BUS_OPTIONS (sizeof(bus_options)/sizeof(bus_options[0]))
Enumerations
enum MS5611_BUS {
MS5611_BUS_ALL = 0, MS5611_BUS_I2C_INTERNAL, MS5611_BUS_I2C_EXTERNAL, MS5611_BUS_SPI_INTERNAL,
MS5611_BUS_SPI_EXTERNAL
}
Functions
__EXPORT int ms5611_main (int argc, char *argv[])
static bool ms5611::start_bus (struct ms5611_bus_option &bus, enum MS56XX_DEVICE_TYPES device_type)
Start the driver.
static int ms5611::start (enum MS5611_BUS busid, enum MS56XX_DEVICE_TYPES device_type)
Start the driver.
static int ms5611::info ()
static int ms5611::usage ()
Variables
struct ms5611::ms5611_bus_option ms5611::bus_options []
Macro Definition Documentation
NUM_BUS_OPTIONS
#define NUM_BUS_OPTIONS (sizeof(bus_options)/sizeof(bus_options[0]))
Definition at line 90 of file ms5611_main.cpp.
Referenced by ms5611::info(), and ms5611::start().
Enumeration Type Documentation
MS5611_BUS
enum MS5611_BUS
Enumerator
MS5611_BUS_ALL
MS5611_BUS_I2C_INTERNAL
MS5611_BUS_I2C_EXTERNAL
MS5611_BUS_SPI_INTERNAL
MS5611_BUS_SPI_EXTERNAL
Definition at line 42 of file ms5611_main.cpp.
Function Documentation
ms5611_main()
int ms5611_main (int argc, char * argv[])
Definition at line 205 of file ms5611_main.cpp.
References ms5611::ms5611_bus_option::busid, ms5611::info(), MS5607_DEVICE, MS5611_BUS_ALL, MS5611_BUS_I2C_EXTERNAL, MS5611_BUS_I2C_INTERNAL, MS5611_BUS_SPI_EXTERNAL, MS5611_BUS_SPI_INTERNAL, MS5611_DEVICE, MS56XX_DEVICE, ms5611::start(), and ms5611::usage().