PX4 Firmware: src/drivers/boards/px4cannode-v1/led.c File Reference
led.c File Reference
#include <px4_config.h>
#include <stdbool.h>
#include <nuttx/board.h>
#include "stm32.h"
#include "board_config.h"
#include <arch/board/board.h>
#include <systemlib/px4_macros.h>
Functions
__BEGIN_DECLS void led_init (void)
Ideally we'd be able to get these from up_internal.h, but since we want to be able to disable the NuttX use of leds for system indication at will and there is no separate switch, we need to build independent of the CONFIG_ARCH_LEDS configuration switch.
void led_on (int led)
void led_off (int led)
void led_toggle (int led)
__EXPORT void board_autoled_initialize (void)
static void phy_set_led (int led, bool state)
static bool phy_get_led (int led)
__EXPORT void board_autoled_on (int led)
__EXPORT void board_autoled_off (int led)
Variables
static __END_DECLS uint16_t g_ledmap []
static bool g_initialized
Function Documentation
__EXPORT void board_autoled_initialize (void)
Definition at line 79 of file led.c.
References led_init().
__EXPORT void board_autoled_off (int led)
Definition at line 151 of file led.c.
References g_initialized, LED_ASSERTION, LED_HEAPALLOCATE, LED_INIRQ, LED_IRQSENABLED, LED_PANIC, LED_SIGNAL, LED_STACKCREATED, LED_STARTED, and phy_set_led().
__EXPORT void board_autoled_on (int led)
Definition at line 116 of file led.c.
References g_initialized, LED_ASSERTION, LED_HEAPALLOCATE, LED_INIRQ, LED_IRQSENABLED, LED_PANIC, LED_SIGNAL, LED_STACKCREATED, LED_STARTED, and phy_set_led().
__BEGIN_DECLS void led_init (void)
Ideally we'd be able to get these from up_internal.h, but since we want to be able to disable the NuttX use of leds for system indication at will and there is no separate switch, we need to build independent of the CONFIG_ARCH_LEDS configuration switch.
Definition at line 71 of file led.c.
References arraySize, and g_ledmap.
void led_off (int led)
Definition at line 101 of file led.c.
References phy_set_led().
void led_on (int led)
Definition at line 96 of file led.c.
References phy_set_led().
void led_toggle (int led)
Definition at line 106 of file led.c.
References phy_get_led(), and phy_set_led().
static bool phy_get_led (int led) static
Definition at line 90 of file led.c.
References g_ledmap.
Referenced by led_toggle().
static void phy_set_led (int led, bool state) static
Definition at line 84 of file led.c.
References g_ledmap.
Referenced by board_autoled_off(), board_autoled_on(), led_off(), led_on(), and led_toggle().
Variable Documentation
bool g_initialized static
Definition at line 112 of file led.c.
Referenced by board_autoled_off(), and board_autoled_on().
__END_DECLS uint16_t g_ledmap[] static
Initial value:
= {
    GPIO_LED_GREEN,
    GPIO_LED_YELLOW,
}
Definition at line 66 of file led.c.
Referenced by led_init(), phy_get_led(), and phy_set_led().