PX4 Firmware: hc_sr04 Namespace Reference
hc_sr04 Namespace Reference
Local functions in support of the shell command.
Functions
void start ()
Start the driver.
void stop ()
Stop the driver.
void test ()
Perform some basic functional tests on the driver; make sure we can collect data from the sensor in polled and automatic modes.
void reset ()
Reset the driver.
void info ()
Print a little info about the driver.
Variables
HC_SR04 * g_dev
Detailed Description
Local functions in support of the shell command.
Function Documentation
void hc_sr04::info ()
Print a little info about the driver.
Definition at line 849 of file hc_sr04.cpp.
References errx, and HC_SR04::print_info().
Referenced by hc_sr04_main().
void hc_sr04::reset ()
Reset the driver.
Definition at line 826 of file hc_sr04.cpp.
References err, fd, HC_SR04::ioctl(), device::CDev::open(), SENSOR_POLLRATE_DEFAULT, SENSORIOCRESET, SENSORIOCSPOLLRATE, and SR04_DEVICE_PATH.
Referenced by hc_sr04_main().
void hc_sr04::start ()
Start the driver.
Attempt to start driver on all available I2C busses.
Definition at line 699 of file hc_sr04.cpp.
References errx, fd, g_dev, HC_SR04::HC_SR04(), HC_SR04::init(), HC_SR04::ioctl(), OK, device::CDev::open(), SENSOR_POLLRATE_DEFAULT, SENSORIOCSPOLLRATE, and SR04_DEVICE_PATH.
Referenced by hc_sr04_main().
void hc_sr04::stop ()
Stop the driver.
Definition at line 744 of file hc_sr04.cpp.
References errx, and g_dev.
Referenced by hc_sr04_main().
void hc_sr04::test ()
Perform some basic functional tests on the driver; make sure we can collect data from the sensor in polled and automatic modes.
Definition at line 763 of file hc_sr04.cpp.
References err, errx, fd, HC_SR04::ioctl(), OK, device::CDev::open(), device::CDev::poll(), HC_SR04::read(), SENSOR_POLLRATE_DEFAULT, SENSORIOCSPOLLRATE, and SR04_DEVICE_PATH.
Referenced by hc_sr04_main().
Variable Documentation
HC_SR04* hc_sr04::g_dev
Definition at line 687 of file hc_sr04.cpp.
Referenced by sonar_isr(), start(), and stop().