PX4 Firmware: FlightTaskAuto Class Reference
FlightTaskAuto Class Reference
#include <FlightTaskAuto.hpp>
Public Member Functions
FlightTaskAuto ()
virtual ~FlightTaskAuto ()=default
bool activate (vehicle_local_position_setpoint_s last_setpoint) override
Call once on the event where you switch to the task.
bool updateInitialize () override
Call before activate() or update() to initialize time and input data.
bool updateFinalize () override
Call after update() to constrain the generated setpoints in order to comply with the constraints of the current mode.
void setYawHandler (WeatherVane *ext_yaw_handler) override
Sets an external yaw handler which can be used to implement a different yaw control strategy.
Public Member Functions inherited from FlightTask
FlightTask ()
virtual ~FlightTask ()=default
virtual void reActivate ()
Call this to reset an active Flight Task.
virtual bool applyCommandParameters (const vehicle_command_s &command)
To be called to adopt parameters from an arrived vehicle command.
virtual bool update ()=0
To be called regularly in the control loop cycle to execute the task.
const vehicle_local_position_setpoint_s getPositionSetpoint ()
Get the output data.
const vehicle_constraints_s & getConstraints ()
Get vehicle constraints.
const landing_gear_s & getGear ()
Get landing gear position.
const vehicle_trajectory_waypoint_s & getAvoidanceWaypoint ()
Get avoidance desired waypoint.
void handleParameterUpdate ()
Call this whenever a parameter update notification is received (parameter_update uORB message)
void updateVelocityControllerIO (const matrix::Vector3f &vel_sp, const matrix::Vector3f &thrust_sp)
Protected Member Functions
void _setDefaultConstraints () override
Set constraints to default values.
matrix::Vector2f _getTargetVelocityXY ()
only used for follow-me and only here because of legacy reason.
void _updateInternalWaypoints ()
Depending on state of vehicle, the internal waypoints might differ from target (for instance if offtrack).
bool _compute_heading_from_2D_vector (float &heading, matrix::Vector2f v)
Computes and sets heading a 2D vector.
DEFINE_PARAMETERS_CUSTOM_PARENT (FlightTask,(ParamFloat< px4::params::MPC_XY_CRUISE >) _param_mpc_xy_cruise,(ParamFloat< px4::params::MPC_CRUISE_90 >) _param_mpc_cruise_90,(ParamFloat< px4::params::NAV_MC_ALT_RAD >) _param_nav_mc_alt_rad,(ParamInt< px4::params::MPC_YAW_MODE >) _param_mpc_yaw_mode,(ParamInt< px4::params::COM_OBS_AVOID >) _param_com_obs_avoid,(ParamFloat< px4::params::MPC_YAWRAUTO_MAX >) _param_mpc_yawrauto_max,(ParamFloat< px4::params::MIS_YAW_ERR >) _param_mis_yaw_err,(ParamBool< px4::params::WV_EN >) _param_wv_en)
Protected Member Functions inherited from FlightTask
void _resetSetpoints ()
Reset all setpoints to NAN.
void _evaluateVehicleLocalPosition ()
Check and update local position.
virtual bool _checkTakeoff ()
Determine when to trigger a takeoff (ignored in flight)
void _initEkfResetCounters ()
Monitor the EKF reset counters and call the appropriate handling functions in case of a reset event.
void _checkEkfResetCounters ()
virtual void _ekfResetHandlerPositionXY ()
virtual void _ekfResetHandlerVelocityXY ()
virtual void _ekfResetHandlerPositionZ ()
virtual void _ekfResetHandlerVelocityZ ()
virtual void _ekfResetHandlerHeading (float delta_psi)
Protected Attributes
matrix::Vector3f _prev_prev_wp {}
Pre-previous waypoint (local frame).
matrix::Vector3f _prev_wp {}
Previous waypoint (local frame).
matrix::Vector3f _target {}
Target waypoint (local frame).
matrix::Vector3f _next_wp {}
The next waypoint after target (local frame).
float _mc_cruise_speed {0.0f}
Requested cruise speed.
WaypointType _type {WaypointType::idle}
Type of current target triplet.
uORB::SubscriptionData< home_position_s > _sub_home_position {ORB_ID(home_position)}
uORB::SubscriptionData< manual_control_setpoint_s > _sub_manual_control_setpoint {ORB_ID(manual_control_setpoint)}
uORB::SubscriptionData< vehicle_status_s > _sub_vehicle_status {ORB_ID(vehicle_status)}
State _current_state {State::none}
float _target_acceptance_radius {0.0f}
Acceptances radius of the target.
int _mission_gear {landing_gear_s::GEAR_KEEP}
float _yaw_sp_prev {NAN}
bool _yaw_sp_aligned {false}
ObstacleAvoidance _obstacle_avoidance
class adjusting setpoints according to external avoidance module's input
Protected Attributes inherited from FlightTask
uORB::SubscriptionData< vehicle_local_position_s > _sub_vehicle_local_position {ORB_ID(vehicle_local_position)}
uORB::SubscriptionData< vehicle_attitude_s > _sub_attitude {ORB_ID(vehicle_attitude)}
float _time = 0
passed time in seconds since the task was activated
float _deltatime = 0
passed time in seconds since the task was last updated
hrt_abstime _time_stamp_activate = 0
time stamp when task was activated
hrt_abstime _time_stamp_current = 0
time stamp at the beginning of the current task update
hrt_abstime _time_stamp_last = 0
time stamp when task was last updated
matrix::Vector3f _position
current vehicle position
matrix::Vector3f _velocity
current vehicle velocity
float _yaw = 0.f
current vehicle yaw heading
float _dist_to_bottom = 0.0f
current height above ground level
matrix::Vector3f _position_setpoint
Setpoints which the position controller has to execute.
matrix::Vector3f _velocity_setpoint
matrix::Vector3f _acceleration_setpoint
matrix::Vector3f _jerk_setpoint
matrix::Vector3f _thrust_setpoint
float _yaw_setpoint
float _yawspeed_setpoint
matrix::Vector3f _velocity_setpoint_feedback
matrix::Vector3f _thrust_setpoint_feedback
struct {
uint8_t xy = 0
uint8_t vxy = 0
uint8_t z = 0
uint8_t vz = 0
uint8_t quat = 0
} _reset_counters
vehicle_constraints_s _constraints {}
Vehicle constraints.
landing_gear_s _gear {}
vehicle_trajectory_waypoint_s _desired_waypoint {}
Desired waypoints.
Private Member Functions
void _limitYawRate ()
Limits the rate of change of the yaw setpoint.
bool _evaluateTriplets ()
Checks and sets triplets.
bool _isFinite (const position_setpoint_s &sp)
Checks if all waypoint triplets are finite.
bool _evaluateGlobalReference ()
Check is global reference is available.
State _getCurrentState ()
Computes the current vehicle state based on the vehicle position and navigator triplets.
void _set_heading_from_mode ()
Private Attributes
matrix::Vector2f _lock_position_xy {NAN, NAN}
if no valid triplet is received, lock positition to current position
bool _yaw_lock {false}
if within acceptance radius, lock yaw to current yaw
uORB::SubscriptionData< position_setpoint_triplet_s > _sub_triplet_setpoint {ORB_ID(position_setpoint_triplet)}
matrix::Vector3f _triplet_target
current triplet from navigator which may differ from the intenal one (_target) depending on the vehicle state.
matrix::Vector3f _triplet_prev_wp
previous triplet from navigator which may differ from the intenal one (_prev_wp) depending on the vehicle state.
matrix::Vector3f _triplet_next_wp
next triplet from navigator which may differ from the intenal one (_next_wp) depending on the vehicle state.
matrix::Vector2f _closest_pt
closest point to the vehicle position on the line previous - target
map_projection_reference_s _reference_position {}
Structure used to project lat/lon setpoint into local frame.
float _reference_altitude {NAN}
Altitude relative to ground.
hrt_abstime _time_stamp_reference {0}
time stamp when last reference update occured.
WeatherVane * _ext_yaw_handler {nullptr}
external weathervane library, used to implement a yaw control law that turns the vehicle nose into the wind
Additional Inherited Members
Static Public Attributes inherited from FlightTask
static const vehicle_local_position_setpoint_s empty_setpoint = {0, NAN, NAN, NAN, NAN, NAN, NAN, NAN, NAN, {NAN, NAN, NAN}, {NAN, NAN, NAN}, {NAN, NAN, NAN}, {}}
Empty setpoint.
static const vehicle_constraints_s empty_constraints = {0, NAN, NAN, NAN, NAN, NAN, NAN, NAN, false, {}}
Empty constraints.
static const landing_gear_s empty_landing_gear_default_keep = {0, landing_gear_s::GEAR_KEEP, {}}
default landing gear state
Static Protected Attributes inherited from FlightTask
static constexpr uint64_t _timeout = 500000
maximal time in us before a loop or data times out
Detailed Description
Definition at line 74 of file FlightTaskAuto.hpp.
Constructor & Destructor Documentation
FlightTaskAuto()
FlightTaskAuto::FlightTaskAuto ()
Definition at line 45 of file FlightTaskAuto.cpp.
~FlightTaskAuto()
virtual FlightTaskAuto::~FlightTaskAuto () virtual default
Member Function Documentation
_compute_heading_from_2D_vector()
bool FlightTaskAuto::_compute_heading_from_2D_vector (float & heading, matrix::Vector2f v) protected
Computes and sets heading a 2D vector.
Definition at line 474 of file FlightTaskAuto.cpp.
References matrix::Vector< Type, M >::length(), matrix::Vector< Type, M >::normalize(), SIGMA_NORM, math::sign(), and matrix::wrap_pi().
Referenced by _set_heading_from_mode().
_evaluateGlobalReference()
bool FlightTaskAuto::_evaluateGlobalReference () private
Check is global reference is available.
Definition at line 346 of file FlightTaskAuto.cpp.
References _reference_altitude, _reference_position, FlightTask::_sub_vehicle_local_position, _time_stamp_reference, uORB::SubscriptionData< T >::get(), map_projection_init(), vehicle_local_position_s::ref_alt, vehicle_local_position_s::ref_lat, vehicle_local_position_s::ref_lon, vehicle_local_position_s::ref_timestamp, vehicle_local_position_s::xy_global, and vehicle_local_position_s::z_global.
Referenced by updateInitialize().
_evaluateTriplets()
bool FlightTaskAuto::_evaluateTriplets () private
Checks and sets triplets.
Definition at line 123 of file FlightTaskAuto.cpp.
References _closest_pt, FlightTask::_constraints, _current_state, _ext_yaw_handler, _getCurrentState(), _isFinite(), _lock_position_xy, _mc_cruise_speed, _mission_gear, _obstacle_avoidance, FlightTask::_position, _prev_prev_wp, _reference_altitude, _reference_position, _set_heading_from_mode(), _sub_triplet_setpoint, _sub_vehicle_status, _target_acceptance_radius, _triplet_next_wp, _triplet_prev_wp, _triplet_target, _type, _updateInternalWaypoints(), FlightTask::_yaw, FlightTask::_yaw_setpoint, FlightTask::_yawspeed_setpoint, position_setpoint_s::acceptance_radius, WeatherVane::activate(), position_setpoint_s::allow_weather_vane, position_setpoint_s::alt, ObstacleAvoidance::checkAvoidanceProgress(), position_setpoint_s::cruising_speed, position_setpoint_triplet_s::current, WeatherVane::deactivate(), f(), follow_target, uORB::SubscriptionData< T >::get(), WeatherVane::get_weathervane_yawrate(), WeatherVane::is_active(), position_setpoint_s::landing_gear, position_setpoint_s::lat, loiter, position_setpoint_s::lon, map_projection_project(), math::min(), position_setpoint_triplet_s::next, position, position_setpoint_triplet_s::previous, matrix::Matrix< Type, M, N >::setAll(), vehicle_constraints_s::speed_xy, position_setpoint_s::type, ObstacleAvoidance::updateAvoidanceDesiredWaypoints(), position_setpoint_s::valid, vehicle_status_s::vehicle_type, position_setpoint_s::yaw, position_setpoint_s::yaw_valid, position_setpoint_s::yawspeed, and position_setpoint_s::yawspeed_valid.
Referenced by updateInitialize().
_getCurrentState()
State FlightTaskAuto::_getCurrentState () private
Computes the current vehicle state based on the vehicle position and navigator triplets.
Definition at line 408 of file FlightTaskAuto.cpp.
References _closest_pt, _mc_cruise_speed, FlightTask::_position, _triplet_prev_wp, _triplet_target, f(), matrix::Vector< Type, M >::length(), none, offtrack, previous_infront, and target_behind.
Referenced by _evaluateTriplets().
_getTargetVelocityXY()
Vector2f FlightTaskAuto::_getTargetVelocityXY () protected
only used for follow-me and only here because of legacy reason.
Definition at line 391 of file FlightTaskAuto.cpp.
References _sub_triplet_setpoint, position_setpoint_triplet_s::current, uORB::SubscriptionData< T >::get(), position_setpoint_s::velocity_valid, position_setpoint_s::vx, and position_setpoint_s::vy.
_isFinite()
bool FlightTaskAuto::_isFinite (const position_setpoint_s & sp) private
Checks if all waypoint triplets are finite.
Definition at line 341 of file FlightTaskAuto.cpp.
References position_setpoint_s::alt, position_setpoint_s::lat, and position_setpoint_s::lon.
Referenced by _evaluateTriplets().
_limitYawRate()
void FlightTaskAuto::_limitYawRate () private
Limits the rate of change of the yaw setpoint.
Definition at line 94 of file FlightTaskAuto.cpp.
References FlightTask::_deltatime, FlightTask::_yaw_setpoint, _yaw_sp_aligned, _yaw_sp_prev, FlightTask::_yawspeed_setpoint, math::constrain(), math::radians(), and matrix::wrap_pi().
Referenced by updateFinalize().
_set_heading_from_mode()
void FlightTaskAuto::_set_heading_from_mode () private
See also
MPC_YAW_MODE
Definition at line 287 of file FlightTaskAuto.cpp.
References _compute_heading_from_2D_vector(), FlightTask::_position, _sub_home_position, _target, _target_acceptance_radius, FlightTask::_yaw, _yaw_lock, FlightTask::_yaw_setpoint, uORB::SubscriptionData< T >::get(), matrix::Vector< Type, M >::length(), matrix::Matrix< Type, M, N >::setAll(), home_position_s::valid_hpos, and home_position_s::x.
Referenced by _evaluateTriplets().
_setDefaultConstraints()
void FlightTaskAuto::_setDefaultConstraints () override protected virtual
Set constraints to default values.
Reimplemented from FlightTask.
Definition at line 381 of file FlightTaskAuto.cpp.
References FlightTask::_constraints, FlightTask::_setDefaultConstraints(), and vehicle_constraints_s::speed_xy.
Referenced by activate().
_updateInternalWaypoints()
void FlightTaskAuto::_updateInternalWaypoints () protected
Depending on state of vehicle, the internal waypoints might differ from target (for instance if offtrack).
Definition at line 436 of file FlightTaskAuto.cpp.
References _closest_pt, _current_state, _next_wp, FlightTask::_position, _prev_wp, _target, _triplet_next_wp, _triplet_prev_wp, _triplet_target, none, offtrack, previous_infront, and target_behind.
Referenced by _evaluateTriplets().
activate()
bool FlightTaskAuto::activate (vehicle_local_position_setpoint_s last_setpoint) override virtual
Call once on the event where you switch to the task.
Parameters
state of the previous task
Returns
true on success, false on error
Reimplemented from FlightTask.
Reimplemented in FlightTaskAutoLineSmoothVel, FlightTaskAutoMapper, and FlightTaskAutoMapper2.
Definition at line 51 of file FlightTaskAuto.cpp.
References FlightTask::_position, FlightTask::_position_setpoint, _setDefaultConstraints(), FlightTask::_velocity, FlightTask::_velocity_setpoint, FlightTask::_yaw, FlightTask::_yaw_setpoint, _yaw_sp_prev, FlightTask::_yawspeed_setpoint, and FlightTask::activate().
Referenced by FlightTaskAutoMapper::activate(), and FlightTaskAutoMapper2::activate().
DEFINE_PARAMETERS_CUSTOM_PARENT()
FlightTaskAuto::DEFINE_PARAMETERS_CUSTOM_PARENT (FlightTask , (ParamFloat< px4::params::MPC_XY_CRUISE >) _param_mpc_xy_cruise, (ParamFloat< px4::params::MPC_CRUISE_90 >) _param_mpc_cruise_90, (ParamFloat< px4::params::NAV_MC_ALT_RAD >) _param_nav_mc_alt_rad, (ParamInt< px4::params::MPC_YAW_MODE >) _param_mpc_yaw_mode, (ParamInt< px4::params::COM_OBS_AVOID >) _param_com_obs_avoid, (ParamFloat< px4::params::MPC_YAWRAUTO_MAX >) _param_mpc_yawrauto_max, (ParamFloat< px4::params::MIS_YAW_ERR >) _param_mis_yaw_err, (ParamBool< px4::params::WV_EN >) _param_wv_en) protected
setYawHandler()
void FlightTaskAuto::setYawHandler (WeatherVane * ext_yaw_handler) inline override virtual
Sets an external yaw handler which can be used to implement a different yaw control strategy.
Reimplemented from FlightTask.
Definition at line 87 of file FlightTaskAuto.hpp.
updateFinalize()
bool FlightTaskAuto::updateFinalize () override virtual
Call after update() to constrain the generated setpoints in order to comply with the constraints of the current mode.
Returns
true on success, false on error
Reimplemented from FlightTask.
Definition at line 84 of file FlightTaskAuto.cpp.
References FlightTask::_checkTakeoff(), FlightTask::_constraints, _limitYawRate(), and vehicle_constraints_s::want_takeoff.
updateInitialize()
bool FlightTaskAuto::updateInitialize () override virtual
Call before activate() or update() to initialize time and input data.
Returns
true on success, false on error
Reimplemented from FlightTask.
Definition at line 62 of file FlightTaskAuto.cpp.
References _evaluateGlobalReference(), _evaluateTriplets(), FlightTask::_position, _sub_home_position, _sub_manual_control_setpoint, _sub_triplet_setpoint, _sub_vehicle_status, FlightTask::_velocity, uORB::SubscriptionData< T >::update(), and FlightTask::updateInitialize().
Member Data Documentation
_closest_pt
matrix::Vector2f FlightTaskAuto::_closest_pt private
closest point to the vehicle position on the line previous - target
Definition at line 139 of file FlightTaskAuto.hpp.
Referenced by _evaluateTriplets(), _getCurrentState(), and _updateInternalWaypoints().
_current_state
State FlightTaskAuto::_current_state {State::none} protected
Definition at line 106 of file FlightTaskAuto.hpp.
Referenced by _evaluateTriplets(), and _updateInternalWaypoints().
_ext_yaw_handler
WeatherVane* FlightTaskAuto::_ext_yaw_handler {nullptr} private
external weathervane library, used to implement a yaw control law that turns the vehicle nose into the wind
Definition at line 145 of file FlightTaskAuto.hpp.
Referenced by _evaluateTriplets().
_lock_position_xy
matrix::Vector2f FlightTaskAuto::_lock_position_xy {NAN, NAN} private
if no valid triplet is received, lock positition to current position
Definition at line 128 of file FlightTaskAuto.hpp.
Referenced by _evaluateTriplets().
_mc_cruise_speed
float FlightTaskAuto::_mc_cruise_speed {0.0f} protected
Requested cruise speed.
If not valid, default cruise speed is used.
Definition at line 99 of file FlightTaskAuto.hpp.
Referenced by _evaluateTriplets(), and _getCurrentState().
_mission_gear
int FlightTaskAuto::_mission_gear {landing_gear_s::GEAR_KEEP} protected
Definition at line 108 of file FlightTaskAuto.hpp.
Referenced by _evaluateTriplets().
_next_wp
matrix::Vector3f FlightTaskAuto::_next_wp {} protected
The next waypoint after target (local frame).
If no next setpoint is available, next is set to target.
Definition at line 98 of file FlightTaskAuto.hpp.
Referenced by _updateInternalWaypoints().
_obstacle_avoidance
ObstacleAvoidance FlightTaskAuto::_obstacle_avoidance protected
class adjusting setpoints according to external avoidance module's input
Definition at line 113 of file FlightTaskAuto.hpp.
Referenced by _evaluateTriplets().
_prev_prev_wp
matrix::Vector3f FlightTaskAuto::_prev_prev_wp {} protected
Pre-previous waypoint (local frame).
This will be used for smoothing trajectories -> not used yet.
Definition at line 95 of file FlightTaskAuto.hpp.
Referenced by _evaluateTriplets().
_prev_wp
matrix::Vector3f FlightTaskAuto::_prev_wp {} protected
Previous waypoint (local frame).
If no previous triplet is available, the prev_wp is set to current position.
Definition at line 96 of file FlightTaskAuto.hpp.
Referenced by _updateInternalWaypoints().
_reference_altitude
float FlightTaskAuto::_reference_altitude {NAN} private
Altitude relative to ground.
Definition at line 142 of file FlightTaskAuto.hpp.
Referenced by _evaluateGlobalReference(), and _evaluateTriplets().
_reference_position
map_projection_reference_s FlightTaskAuto::_reference_position {} private
Structure used to project lat/lon setpoint into local frame.
Definition at line 141 of file FlightTaskAuto.hpp.
Referenced by _evaluateGlobalReference(), and _evaluateTriplets().
_sub_home_position
uORB::SubscriptionData<home_position_s> FlightTaskAuto::_sub_home_position {ORB_ID(home_position)} protected
Definition at line 102 of file FlightTaskAuto.hpp.
Referenced by _set_heading_from_mode(), and updateInitialize().
_sub_manual_control_setpoint
uORB::SubscriptionData<manual_control_setpoint_s> FlightTaskAuto::_sub_manual_control_setpoint {ORB_ID(manual_control_setpoint)} protected
Definition at line 103 of file FlightTaskAuto.hpp.
Referenced by updateInitialize().
_sub_triplet_setpoint
uORB::SubscriptionData<position_setpoint_triplet_s> FlightTaskAuto::_sub_triplet_setpoint {ORB_ID(position_setpoint_triplet)} private
Definition at line 131 of file FlightTaskAuto.hpp.
Referenced by _evaluateTriplets(), _getTargetVelocityXY(), and updateInitialize().
_sub_vehicle_status
uORB::SubscriptionData<vehicle_status_s> FlightTaskAuto::_sub_vehicle_status {ORB_ID(vehicle_status)} protected
Definition at line 104 of file FlightTaskAuto.hpp.
Referenced by _evaluateTriplets(), and updateInitialize().
_target
matrix::Vector3f FlightTaskAuto::_target {} protected
Target waypoint (local frame).
Definition at line 97 of file FlightTaskAuto.hpp.
Referenced by _set_heading_from_mode(), and _updateInternalWaypoints().
_target_acceptance_radius
float FlightTaskAuto::_target_acceptance_radius {0.0f} protected
Acceptances radius of the target.
Definition at line 107 of file FlightTaskAuto.hpp.
Referenced by _evaluateTriplets(), and _set_heading_from_mode().
_time_stamp_reference
hrt_abstime FlightTaskAuto::_time_stamp_reference {0} private
time stamp when last reference update occured.
Definition at line 143 of file FlightTaskAuto.hpp.
Referenced by _evaluateGlobalReference().
_triplet_next_wp
matrix::Vector3f FlightTaskAuto::_triplet_next_wp private
next triplet from navigator which may differ from the intenal one (_next_wp) depending on the vehicle state.
Definition at line 138 of file FlightTaskAuto.hpp.
Referenced by _evaluateTriplets(), and _updateInternalWaypoints().
_triplet_prev_wp
matrix::Vector3f FlightTaskAuto::_triplet_prev_wp private
previous triplet from navigator which may differ from the intenal one (_prev_wp) depending on the vehicle state.
Definition at line 136 of file FlightTaskAuto.hpp.
Referenced by _evaluateTriplets(), _getCurrentState(), and _updateInternalWaypoints().
_triplet_target
matrix::Vector3f FlightTaskAuto::_triplet_target private
current triplet from navigator which may differ from the intenal one (_target) depending on the vehicle state.
Definition at line 134 of file FlightTaskAuto.hpp.
Referenced by _evaluateTriplets(), _getCurrentState(), and _updateInternalWaypoints().
_type
WaypointType FlightTaskAuto::_type {WaypointType::idle} protected
Type of current target triplet.
Definition at line 100 of file FlightTaskAuto.hpp.
Referenced by _evaluateTriplets().
_yaw_lock
bool FlightTaskAuto::_yaw_lock {false} private
if within acceptance radius, lock yaw to current yaw
Definition at line 129 of file FlightTaskAuto.hpp.
Referenced by _set_heading_from_mode().
_yaw_sp_aligned
bool FlightTaskAuto::_yaw_sp_aligned {false} protected
Definition at line 111 of file FlightTaskAuto.hpp.
Referenced by _limitYawRate().
_yaw_sp_prev
float FlightTaskAuto::_yaw_sp_prev {NAN} protected
Definition at line 110 of file FlightTaskAuto.hpp.
Referenced by _limitYawRate(), and activate().
The documentation for this class was generated from the following files:
src/lib/flight_tasks/tasks/Auto/FlightTaskAuto.hpp
src/lib/flight_tasks/tasks/Auto/FlightTaskAuto.cpp