PX4 Firmware: RGBLED_PWM Class Reference
RGBLED_PWM Class Reference
Public Member Functions
RGBLED_PWM ()
virtual ~RGBLED_PWM ()
virtual int init ()
Initialise the driver and make it ready for use.
virtual int probe ()
int status ()
Public Member Functions inherited from device::CDev
CDev (const char *name, const char *devname)
Constructor.
virtual ~CDev ()
virtual int open (file_t *filep)
Handle an open of the device.
virtual int close (file_t *filep)
Handle a close of the device.
virtual ssize_t read (file_t *filep, char *buffer, size_t buflen)
Perform a read from the device.
virtual ssize_t write (file_t *filep, const char *buffer, size_t buflen)
Perform a write to the device.
virtual off_t seek (file_t *filep, off_t offset, int whence)
Perform a logical seek operation on the device.
virtual int ioctl (file_t *filep, int cmd, unsigned long arg)
Perform an ioctl operation on the device.
virtual int poll (file_t *filep, px4_pollfd_struct_t *fds, bool setup)
Perform a poll setup/teardown operation.
Public Member Functions inherited from device::Device
virtual ~Device ()=default
Destructor.
virtual int read (unsigned address, void *data, unsigned count)
Read directly from the device.
virtual int write (unsigned address, void *data, unsigned count)
Write directly to the device.
virtual int ioctl (unsigned operation, unsigned &arg)
Perform a device-specific operation.
uint8_t get_device_bus ()
Return the bus ID the device is connected to.
DeviceBusType get_device_bus_type ()
Return the bus type the device is connected to.
uint8_t get_device_address ()
Return the bus address of the device.
void set_device_address (int address)
void set_device_type (uint8_t devtype)
Set the device type.
virtual bool external ()
Private Member Functions
void led ()
Main loop function.
int send_led_rgb ()
Send RGB PWM settings to LED driver according to current color and brightness.
int get (bool &on, bool &powersave, uint8_t &r, uint8_t &g, uint8_t &b)
Static Private Member Functions
static void led_trampoline (void *arg)
Private Attributes
work_s _work
uint8_t _r
uint8_t _g
uint8_t _b
volatile bool _running
volatile bool _should_run
LedController _led_controller
Additional Inherited Members
Public Types inherited from device::Device
enum DeviceBusType { DeviceBusType_UNKNOWN = 0, DeviceBusType_I2C = 1, DeviceBusType_SPI = 2, DeviceBusType_UAVCAN = 3 }
Device bus types for DEVID.
Protected Member Functions inherited from device::CDev
virtual pollevent_t poll_state (file_t *filep)
Check the current state of the device for poll events from the perspective of the file.
virtual void poll_notify (pollevent_t events)
Report new poll events.
virtual void poll_notify_one (px4_pollfd_struct_t *fds, pollevent_t events)
Internal implementation of poll_notify.
virtual int open_first (file_t *filep)
Notification of the first open.
virtual int close_last (file_t *filep)
Notification of the last close.
virtual int register_class_devname (const char *class_devname)
Register a class device name, automatically adding device class instance suffix if need be.
virtual int unregister_class_devname (const char *class_devname, unsigned class_instance)
Register a class device name, automatically adding device class instance suffix if need be.
const char * get_devname ()
Get the device name.
void lock ()
Take the driver lock.
void unlock ()
Release the driver lock.
Protected Member Functions inherited from device::Device
Device (const char *name)
Device (DeviceBusType bus_type, uint8_t bus, uint8_t address, uint8_t devtype=0)
Device (const Device &)=delete
Device & operator= (const Device &)=delete
Device (Device &&)=delete
Device & operator= (Device &&)=delete
Protected Attributes inherited from device::CDev
px4_sem_t _lock
lock to protect access to all class members (also for derived classes)
bool _pub_blocked {false}
true if publishing should be blocked
Protected Attributes inherited from device::Device
union DeviceId _device_id
device identifier information
const char * _name
driver name
bool _debug_enabled {false}
if true, debug messages are printed
Static Protected Attributes inherited from device::CDev
static const px4_file_operations_t fops = {}
Pointer to the default cdev file operations table; useful for registering clone devices etc.
Detailed Description
Definition at line 72 of file rgbled_pwm.cpp.
Constructor & Destructor Documentation
RGBLED_PWM::RGBLED_PWM ()
Definition at line 115 of file rgbled_pwm.cpp.
References _b, _g, _r, _running, and _should_run.
Referenced by rgbled_pwm_main().
RGBLED_PWM::~RGBLED_PWM () virtual
Definition at line 126 of file rgbled_pwm.cpp.
References _running, _should_run, counter, and usleep().
Member Function Documentation
int RGBLED_PWM::get (bool & on, bool & powersave, uint8_t & r, uint8_t & g, uint8_t & b) private
Definition at line 277 of file rgbled_pwm.cpp.
References _b, _g, _r, and OK.
int RGBLED_PWM::init () virtual
Initialise the driver and make it ready for use.
Returns
OK if the driver initialized OK, negative errno otherwise;
Reimplemented from device::CDev.
Definition at line 137 of file rgbled_pwm.cpp.
References _running, lis3mdl::init(), led_pwm_servo_init(), led_trampoline(), OK, and send_led_rgb().
void RGBLED_PWM::led () private
Main loop function.
Definition at line 189 of file rgbled_pwm.cpp.
References _b, _g, _led_controller, _r, _running, _should_run, LedControlDataSingle::brightness, LedControlDataSingle::color, LedController::init(), LedController::is_init(), led_control, LedController::led_control_subscription(), led_trampoline(), LedControlData::leds, LedController::maximum_update_interval(), ORB_ID, orb_subscribe(), orb_unsubscribe(), send_led_rgb(), and LedController::update().
Referenced by led_trampoline().
void RGBLED_PWM::led_trampoline (void * arg) static private
Definition at line 178 of file rgbled_pwm.cpp.
References led().
Referenced by init(), and led().
int RGBLED_PWM::probe () virtual
Definition at line 172 of file rgbled_pwm.cpp.
References OK.
int RGBLED_PWM::send_led_rgb () private
Send RGB PWM settings to LED driver according to current color and brightness.
Definition at line 259 of file rgbled_pwm.cpp.
References _b, _g, _r, led_pwm_servo_set(), and OK.
Referenced by init(), and led().
int RGBLED_PWM::status ()
Definition at line 152 of file rgbled_pwm.cpp.
References DEVICE_LOG, OK, and PX4_WARN.
Member Data Documentation
uint8_t RGBLED_PWM::_b private
Definition at line 88 of file rgbled_pwm.cpp.
Referenced by get(), led(), RGBLED_PWM(), and send_led_rgb().
uint8_t RGBLED_PWM::_g private
Definition at line 87 of file rgbled_pwm.cpp.
Referenced by get(), led(), RGBLED_PWM(), and send_led_rgb().
LedController RGBLED_PWM::_led_controller private
Definition at line 93 of file rgbled_pwm.cpp.
Referenced by led().
uint8_t RGBLED_PWM::_r private
Definition at line 86 of file rgbled_pwm.cpp.
Referenced by get(), led(), RGBLED_PWM(), and send_led_rgb().
volatile bool RGBLED_PWM::_running private
Definition at line 90 of file rgbled_pwm.cpp.
Referenced by init(), led(), RGBLED_PWM(), and ~RGBLED_PWM().
volatile bool RGBLED_PWM::_should_run private
Definition at line 91 of file rgbled_pwm.cpp.
Referenced by led(), RGBLED_PWM(), and ~RGBLED_PWM().
work_s RGBLED_PWM::_work private
Definition at line 84 of file rgbled_pwm.cpp.
The documentation for this class was generated from the following file:
src/drivers/rgbled_pwm/rgbled_pwm.cpp