PX4 Firmware: land_detector::VtolLandDetector Class Reference
land_detector::VtolLandDetector Class Reference
#include <VtolLandDetector.h>
Public Member Functions
VtolLandDetector ()
Public Member Functions inherited from land_detector::MulticopterLandDetector
MulticopterLandDetector ()
Public Member Functions inherited from land_detector::LandDetector
LandDetector ()
virtual ~LandDetector ()
int print_status () override
LandDetectionState get_state () const
int start ()
Get the work queue going.
Protected Member Functions
void _initialize_topics () override
Called once to initialize uORB topics.
void _update_params () override
Update parameters.
void _update_topics () override
Update uORB topics.
bool _get_landed_state () override
bool _get_maybe_landed_state () override
Protected Member Functions inherited from land_detector::MulticopterLandDetector
bool _get_ground_contact_state () override
bool _get_freefall_state () override
float _get_max_altitude () override
Private Attributes
struct {
param_t maxAirSpeed
} _paramHandle
struct {
float maxAirSpeed
} _params
int _airspeedSub {-1}
int _vehicle_status_sub {-1}
airspeed_s _airspeed {}
vehicle_status_s _vehicle_status {}
bool _was_in_air {false}
indicates whether the vehicle was in the air in the previous iteration
float _airspeed_filtered {0.0f}
low pass filtered airspeed
Additional Inherited Members
Public Types inherited from land_detector::LandDetector
enum LandDetectionState {
LandDetectionState::FLYING = 0, LandDetectionState::LANDED = 1, LandDetectionState::FREEFALL = 2, LandDetectionState::GROUND_CONTACT = 3,
LandDetectionState::MAYBE_LANDED = 4
}
Static Public Member Functions inherited from land_detector::LandDetector
static int task_spawn (int argc, char *argv[])
static int custom_command (int argc, char *argv[])
static int print_usage (const char *reason=nullptr)
Static Protected Member Functions inherited from land_detector::LandDetector
static bool _orb_update (const struct orb_metadata *meta, int handle, void *buffer)
Convenience function for polling uORB subscriptions.
Protected Attributes inherited from land_detector::LandDetector
orb_advert_t _landDetectedPub {nullptr}
vehicle_land_detected_s _landDetected {}
int _parameterSub {-1}
int _armingSub {-1}
LandDetectionState _state {LandDetectionState::LANDED}
systemlib::Hysteresis _freefall_hysteresis {false}
systemlib::Hysteresis _landed_hysteresis {true}
systemlib::Hysteresis _maybe_landed_hysteresis {true}
systemlib::Hysteresis _ground_contact_hysteresis {true}
Static Protected Attributes inherited from land_detector::LandDetector
static constexpr uint32_t LAND_DETECTOR_UPDATE_RATE_HZ = 50
Run main land detector loop at this rate in Hz.
Detailed Description
Definition at line 52 of file VtolLandDetector.h.
Constructor & Destructor Documentation
land_detector::VtolLandDetector::VtolLandDetector ()
Definition at line 49 of file VtolLandDetector.cpp.
References _paramHandle, and param_find().
Member Function Documentation
bool land_detector::VtolLandDetector::_get_landed_state () override protected virtual
Returns
true if UAV is in a landed state.
Reimplemented from land_detector::MulticopterLandDetector.
Definition at line 80 of file VtolLandDetector.cpp.
References _airspeed, _airspeed_filtered, land_detector::MulticopterLandDetector::_get_landed_state(), _params, _vehicle_status, _was_in_air, airspeed_s::confidence, hrt_elapsed_time(), airspeed_s::indicated_airspeed_m_s, vehicle_status_s::is_rotary_wing, airspeed_s::timestamp, and vehicle_status_s::timestamp.
bool land_detector::VtolLandDetector::_get_maybe_landed_state () override protected virtual
Returns
true if UAV is in almost landed state
Reimplemented from land_detector::MulticopterLandDetector.
Definition at line 70 of file VtolLandDetector.cpp.
References land_detector::MulticopterLandDetector::_get_maybe_landed_state(), _vehicle_status, vehicle_status_s::is_rotary_wing, and vehicle_status_s::timestamp.
void land_detector::VtolLandDetector::_initialize_topics () override protected virtual
Called once to initialize uORB topics.
Reimplemented from land_detector::MulticopterLandDetector.
Definition at line 54 of file VtolLandDetector.cpp.
References _airspeedSub, land_detector::MulticopterLandDetector::_initialize_topics(), _vehicle_status_sub, ORB_ID, and orb_subscribe().
void land_detector::VtolLandDetector::_update_params () override protected virtual
Update parameters.
Reimplemented from land_detector::MulticopterLandDetector.
Definition at line 112 of file VtolLandDetector.cpp.
References _paramHandle, _params, land_detector::MulticopterLandDetector::_update_params(), and param_get().
void land_detector::VtolLandDetector::_update_topics () override protected virtual
Update uORB topics.
Reimplemented from land_detector::MulticopterLandDetector.
Definition at line 62 of file VtolLandDetector.cpp.
References _airspeed, _airspeedSub, land_detector::LandDetector::_orb_update(), land_detector::MulticopterLandDetector::_update_topics(), _vehicle_status, _vehicle_status_sub, and ORB_ID.
Member Data Documentation
airspeed_s land_detector::VtolLandDetector::_airspeed {} private
Definition at line 76 of file VtolLandDetector.h.
Referenced by _get_landed_state(), and _update_topics().
float land_detector::VtolLandDetector::_airspeed_filtered {0.0f} private
low pass filtered airspeed
Definition at line 80 of file VtolLandDetector.h.
Referenced by _get_landed_state().
int land_detector::VtolLandDetector::_airspeedSub {-1} private
Definition at line 73 of file VtolLandDetector.h.
Referenced by _initialize_topics(), and _update_topics().
struct { ... } land_detector::VtolLandDetector::_paramHandle
Referenced by _update_params(), and VtolLandDetector().
struct { ... } land_detector::VtolLandDetector::_params
Referenced by _get_landed_state(), and _update_params().
vehicle_status_s land_detector::VtolLandDetector::_vehicle_status {} private
Definition at line 77 of file VtolLandDetector.h.
Referenced by _get_landed_state(), _get_maybe_landed_state(), and _update_topics().
int land_detector::VtolLandDetector::_vehicle_status_sub {-1} private
Definition at line 74 of file VtolLandDetector.h.
Referenced by _initialize_topics(), and _update_topics().
bool land_detector::VtolLandDetector::_was_in_air {false} private
indicates whether the vehicle was in the air in the previous iteration
Definition at line 79 of file VtolLandDetector.h.
Referenced by _get_landed_state().
param_t land_detector::VtolLandDetector::maxAirSpeed
Definition at line 66 of file VtolLandDetector.h.
float land_detector::VtolLandDetector::maxAirSpeed
Definition at line 70 of file VtolLandDetector.h.
The documentation for this class was generated from the following files:
src/modules/land_detector/VtolLandDetector.h
src/modules/land_detector/VtolLandDetector.cpp