PX4 Firmware: rpi_rc_in::RcInput Class Reference
rpi_rc_in::RcInput Class Reference
#include <rpi_rc_in.h>
Public Member Functions
RcInput ()=default
~RcInput ()
int start ()
void stop ()
bool is_running ()
Static Public Member Functions
static void cycle_trampoline (void *arg)
Trampoline for the work queue.
Private Member Functions
void _cycle ()
void _measure ()
int rpi_rc_init ()
Private Attributes
bool _should_exit = false
bool _is_running = false
struct work_s _work = {}
orb_advert_t _rcinput_pub = nullptr
int _channels = 8
struct input_rc_s _data = {}
int * _mem = nullptr
key_t _key = 4096
shared memory key (matches the ppmdecode program's key)
int _shmid = 0
Detailed Description
Definition at line 63 of file rpi_rc_in.h.
Constructor & Destructor Documentation
rpi_rc_in::RcInput::RcInput () default
Referenced by rpi_rc_in_main().
RcInput::~RcInput ()
Definition at line 38 of file rpi_rc_in.cpp.
References _is_running, and _mem.
Member Function Documentation
void RcInput::_cycle () private
Definition at line 103 of file rpi_rc_in.cpp.
References _measure(), _should_exit, cycle_trampoline(), and RCINPUT_MEASURE_INTERVAL_US.
Referenced by cycle_trampoline(), and is_running().
void RcInput::_measure (void) private
Definition at line 113 of file rpi_rc_in.cpp.
References _channels, _data, _mem, _rcinput_pub, input_rc_s::channel_count, hrt_absolute_time(), input_rc_s::input_source, instance, orb_advertise_multi(), ORB_ID, ORB_PRIO_DEFAULT, orb_publish(), PX4_ERR, PX4_INFO, input_rc_s::rc_failsafe, input_rc_s::rc_lost, input_rc_s::rc_lost_frame_count, input_rc_s::rc_ppm_frame_length, input_rc_s::rc_total_frame_count, input_rc_s::rssi, input_rc_s::timestamp, input_rc_s::timestamp_last_signal, rpi_rc_in::usage(), and input_rc_s::values.
Referenced by _cycle(), and is_running().
void RcInput::cycle_trampoline (void * arg) static
Trampoline for the work queue.
Definition at line 97 of file rpi_rc_in.cpp.
References _cycle().
Referenced by _cycle(), and start().
bool rpi_rc_in::RcInput::is_running () inline
Definition at line 79 of file rpi_rc_in.h.
References _cycle(), _is_running, _measure(), and rpi_rc_init().
Referenced by rpi_rc_in_main().
int RcInput::rpi_rc_init () private
Definition at line 49 of file rpi_rc_in.cpp.
References _channels, _data, _key, _mem, _shmid, PX4_WARN, and input_rc_s::values.
Referenced by is_running(), and start().
int RcInput::start ()
Returns
0 on success, -errno on failure
Definition at line 71 of file rpi_rc_in.cpp.
References _is_running, cycle_trampoline(), PX4_WARN, and rpi_rc_init().
Referenced by rpi_rc_in_main().
void RcInput::stop ()
Returns
0 on success, -errno on failure
Definition at line 92 of file rpi_rc_in.cpp.
References _should_exit.
Referenced by rpi_rc_in_main().
Member Data Documentation
int rpi_rc_in::RcInput::_channels = 8 private
Definition at line 94 of file rpi_rc_in.h.
Referenced by _measure(), and rpi_rc_init().
struct input_rc_s rpi_rc_in::RcInput::_data = {} private
Definition at line 95 of file rpi_rc_in.h.
Referenced by _measure(), and rpi_rc_init().
bool rpi_rc_in::RcInput::_is_running = false private
Definition at line 91 of file rpi_rc_in.h.
Referenced by is_running(), start(), and ~RcInput().
key_t rpi_rc_in::RcInput::_key = 4096 private
shared memory key (matches the ppmdecode program's key)
Definition at line 98 of file rpi_rc_in.h.
Referenced by rpi_rc_init().
int* rpi_rc_in::RcInput::_mem = nullptr private
Definition at line 97 of file rpi_rc_in.h.
Referenced by _measure(), rpi_rc_init(), and ~RcInput().
orb_advert_t rpi_rc_in::RcInput::_rcinput_pub = nullptr private
Definition at line 93 of file rpi_rc_in.h.
Referenced by _measure().
int rpi_rc_in::RcInput::_shmid = 0 private
Definition at line 99 of file rpi_rc_in.h.
Referenced by rpi_rc_init().
bool rpi_rc_in::RcInput::_should_exit = false private
Definition at line 90 of file rpi_rc_in.h.
Referenced by _cycle(), and stop().
struct work_s rpi_rc_in::RcInput::_work = {} private
Definition at line 92 of file rpi_rc_in.h.
The documentation for this class was generated from the following files:
src/drivers/rpi_rc_in/rpi_rc_in.h
src/drivers/rpi_rc_in/rpi_rc_in.cpp