PX4 Firmware: src/modules/wind_estimator/wind_estimator_main.cpp File Reference
wind_estimator_main.cpp File Reference
#include <drivers/drv_hrt.h>
#include <ecl/airdata/WindEstimator.hpp>
#include <matrix/math.hpp>
#include <parameters/param.h>
#include <perf/perf_counter.h>
#include <px4_module.h>
#include <px4_module_params.h>
#include <px4_workqueue.h>
#include <uORB/Subscription.hpp>
#include <uORB/topics/airspeed.h>
#include <uORB/topics/parameter_update.h>
#include <uORB/topics/vehicle_attitude.h>
#include <uORB/topics/vehicle_local_position.h>
#include <uORB/topics/wind_estimate.h>
Classes
class WindEstimatorModule
Macros
#define SCHEDULE_INTERVAL 100000
The schedule interval in usec (10 Hz)
Functions
__EXPORT int wind_estimator_main (int argc, char *argv[])
Macro Definition Documentation
#define SCHEDULE_INTERVAL 100000
The schedule interval in usec (10 Hz)
Definition at line 52 of file wind_estimator_main.cpp.
Referenced by WindEstimatorModule::cycle().
Function Documentation
int wind_estimator_main (int argc, char * argv[])
Definition at line 345 of file wind_estimator_main.cpp.
References main(), param_find(), param_get(), and PX4_OK.
Referenced by WindEstimatorModule::print_status().