PX4 Firmware: src/drivers/boards/tap-v1/spi.c File Reference
spi.c File Reference
#include <px4_config.h>
#include <stdint.h>
#include <stdbool.h>
#include <debug.h>
#include <nuttx/spi/spi.h>
#include <arch/board/board.h>
#include "board_config.h"
Functions
__EXPORT void stm32_spiinitialize (void)
__EXPORT void stm32_spi2select (FAR struct spi_dev_s *dev, uint32_t devid, bool selected)
__EXPORT uint8_t stm32_spi2status (FAR struct spi_dev_s *dev, uint32_t devid)
Function Documentation
__EXPORT void stm32_spi2select (FAR struct spi_dev_s * dev, uint32_t devid, bool selected)
Definition at line 75 of file spi.c.
References GPIO_SPI_CS_SDCARD.
__EXPORT uint8_t stm32_spi2status (FAR struct spi_dev_s * dev, uint32_t devid)
Definition at line 81 of file spi.c.
References GPIO_SPI_SD_SW.
__EXPORT void stm32_spiinitialize (void)
Definition at line 68 of file spi.c.
References GPIO_EXTI_ACCEL_DRDY, GPIO_EXTI_GYRO_DRDY, GPIO_EXTI_MAG_DRDY, GPIO_SPI_CS_ACCEL_MAG, GPIO_SPI_CS_BARO, GPIO_SPI_CS_FRAM, GPIO_SPI_CS_GYRO, GPIO_SPI_CS_SDCARD, GPIO_SPI_SD_SW, PX4_SPIDEV_ACCEL_MAG, PX4_SPIDEV_BARO, PX4_SPIDEV_GYRO, stm32_spi1select(), stm32_spi1status(), stm32_spi2select(), stm32_spi2status(), and stm32_spi3select().
Referenced by board_app_initialize(), and stm32_boardinitialize().