PX4 Firmware: VCDevNode Class Reference
VCDevNode Class Reference
Public Member Functions
VCDevNode ()
~VCDevNode ()=default
virtual int open (device::file_t *handlep)
Handle an open of the device.
virtual int close (device::file_t *handlep)
Handle a close of the device.
virtual ssize_t write (device::file_t *handlep, const char *buffer, size_t buflen)
Perform a write to the device.
virtual ssize_t read (device::file_t *handlep, char *buffer, size_t buflen)
Perform a read from the device.
Public Member Functions inherited from device::CDev
CDev (const char *name, const char *devname)
Constructor.
virtual ~CDev ()
virtual int init ()
Initialise the driver and make it ready for use.
virtual off_t seek (file_t *filep, off_t offset, int whence)
Perform a logical seek operation on the device.
virtual int ioctl (file_t *filep, int cmd, unsigned long arg)
Perform an ioctl operation on the device.
virtual int poll (file_t *filep, px4_pollfd_struct_t *fds, bool setup)
Perform a poll setup/teardown operation.
Public Member Functions inherited from device::Device
virtual ~Device ()=default
Destructor.
virtual int read (unsigned address, void *data, unsigned count)
Read directly from the device.
virtual int write (unsigned address, void *data, unsigned count)
Write directly to the device.
virtual int ioctl (unsigned operation, unsigned &arg)
Perform a device-specific operation.
uint8_t get_device_bus ()
Return the bus ID the device is connected to.
DeviceBusType get_device_bus_type ()
Return the bus type the device is connected to.
uint8_t get_device_address ()
Return the bus address of the device.
void set_device_address (int address)
void set_device_type (uint8_t devtype)
Set the device type.
virtual bool external ()
Private Attributes
bool _is_open_for_write
size_t _write_offset
char _buf [1000]
Additional Inherited Members
Public Types inherited from device::Device
enum DeviceBusType { DeviceBusType_UNKNOWN = 0, DeviceBusType_I2C = 1, DeviceBusType_SPI = 2, DeviceBusType_UAVCAN = 3 }
Device bus types for DEVID.
Protected Member Functions inherited from device::CDev
virtual pollevent_t poll_state (file_t *filep)
Check the current state of the device for poll events from the perspective of the file.
virtual void poll_notify (pollevent_t events)
Report new poll events.
virtual void poll_notify_one (px4_pollfd_struct_t *fds, pollevent_t events)
Internal implementation of poll_notify.
virtual int open_first (file_t *filep)
Notification of the first open.
virtual int close_last (file_t *filep)
Notification of the last close.
virtual int register_class_devname (const char *class_devname)
Register a class device name, automatically adding device class instance suffix if need be.
virtual int unregister_class_devname (const char *class_devname, unsigned class_instance)
Register a class device name, automatically adding device class instance suffix if need be.
const char * get_devname ()
Get the device name.
void lock ()
Take the driver lock.
void unlock ()
Release the driver lock.
Protected Member Functions inherited from device::Device
Device (const char *name)
Device (DeviceBusType bus_type, uint8_t bus, uint8_t address, uint8_t devtype=0)
Device (const Device &)=delete
Device & operator= (const Device &)=delete
Device (Device &&)=delete
Device & operator= (Device &&)=delete
Protected Attributes inherited from device::CDev
px4_sem_t _lock
lock to protect access to all class members (also for derived classes)
bool _pub_blocked {false}
true if publishing should be blocked
Protected Attributes inherited from device::Device
union DeviceId _device_id
device identifier information
const char * _name
driver name
bool _debug_enabled {false}
if true, debug messages are printed
Static Protected Attributes inherited from device::CDev
static const px4_file_operations_t fops = {}
Pointer to the default cdev file operations table; useful for registering clone devices etc.
Detailed Description
Definition at line 102 of file vcdevtest_example.cpp.
Constructor & Destructor Documentation
VCDevNode::VCDevNode () inline
Definition at line 105 of file vcdevtest_example.cpp.
References read(), and write().
VCDevNode::~VCDevNode () default
Member Function Documentation
int VCDevNode::close (device::file_t * filep) virtual
Handle a close of the device.
This function is called for every close of the device. The default implementation maintains _open_count and returns OK as long as it is not zero.
Parameters
filep Pointer to the NuttX file structure.
Returns
OK if the close was successful, -errno otherwise.
Reimplemented from device::CDev.
Definition at line 145 of file vcdevtest_example.cpp.
References device::CDev::close(), device::file_t::flags, device::file_t::priv, and PX4_F_WRONLY.
int VCDevNode::open (device::file_t * filep) virtual
Handle an open of the device.
This function is called for every open of the device. The default implementation maintains _open_count and always returns OK.
Parameters
filep Pointer to the NuttX file structure.
Returns
OK if the open is allowed, -errno otherwise.
Reimplemented from device::CDev.
Definition at line 122 of file vcdevtest_example.cpp.
References device::file_t::flags, device::CDev::open(), device::file_t::priv, and PX4_F_WRONLY.
ssize_t VCDevNode::read (device::file_t * filep, char * buffer, size_t buflen) virtual
Perform a read from the device.
The default implementation returns -ENOSYS.
Parameters
filep Pointer to the NuttX file structure.
buffer Pointer to the buffer into which data should be placed.
buflen The number of bytes to be read.
Returns
The number of bytes read or -errno otherwise.
Reimplemented from device::CDev.
Definition at line 172 of file vcdevtest_example.cpp.
References _buf, PrivData::_read_offset, device::file_t::priv, and PX4_INFO.
ssize_t VCDevNode::write (device::file_t * filep, const char * buffer, size_t buflen) virtual
Perform a write to the device.
The default implementation returns -ENOSYS.
Parameters
filep Pointer to the NuttX file structure.
buffer Pointer to the buffer from which data should be read.
buflen The number of bytes to be written.
Returns
The number of bytes written or -errno otherwise.
Reimplemented from device::CDev.
Definition at line 159 of file vcdevtest_example.cpp.
References _buf.
Member Data Documentation
char VCDevNode::_buf[1000] private
Definition at line 119 of file vcdevtest_example.cpp.
bool VCDevNode::_is_open_for_write private
Definition at line 117 of file vcdevtest_example.cpp.
size_t VCDevNode::_write_offset private
Definition at line 118 of file vcdevtest_example.cpp.
The documentation for this class was generated from the following file:
src/platforms/posix/tests/vcdev_test/vcdevtest_example.cpp