PX4 Firmware: MavlinkStreamNavControllerOutput Class Reference
MavlinkStreamNavControllerOutput Class Reference
Public Member Functions
const char * get_name () const override
uint16_t get_id () override
unsigned get_size () override
Get maximal total messages size on update.
Public Member Functions inherited from MavlinkStream
MavlinkStream (Mavlink *mavlink)
virtual ~MavlinkStream ()=default
MavlinkStream (const MavlinkStream &)=delete
MavlinkStream & operator= (const MavlinkStream &)=delete
MavlinkStream (MavlinkStream &&)=delete
MavlinkStream & operator= (MavlinkStream &&)=delete
void set_interval (const int interval)
Get the interval.
int get_interval ()
Get the interval.
int update (const hrt_abstime &t)
Update subscriptions and send message if necessary.
virtual bool const_rate ()
virtual unsigned get_size_avg ()
Get the average message size.
bool first_message_sent () const
void reset_last_sent ()
Reset the time of last sent to 0.
Public Member Functions inherited from ListNode< MavlinkStream *>
void setSibling (MavlinkStream * sibling)
const MavlinkStream * getSibling () const
Static Public Member Functions
static const char * get_name_static ()
static uint16_t get_id_static ()
static MavlinkStream * new_instance (Mavlink *mavlink)
Protected Member Functions
MavlinkStreamNavControllerOutput (Mavlink *mavlink)
bool send (const hrt_abstime t) override
Protected Member Functions inherited from MavlinkStream
virtual void update_data ()
Function to collect/update data for the streams at a high rate independant of actual stream rate.
Private Member Functions
MavlinkStreamNavControllerOutput (MavlinkStreamNavControllerOutput &)=delete
MavlinkStreamNavControllerOutput & operator= (const MavlinkStreamNavControllerOutput &)=delete
Private Attributes
MavlinkOrbSubscription * _pos_ctrl_status_sub
MavlinkOrbSubscription * _tecs_status_sub
uint64_t _pos_ctrl_status_timestamp {0}
uint64_t _tecs_status_timestamp {0}
Additional Inherited Members
Protected Attributes inherited from MavlinkStream
Mavlink *const _mavlink
int _interval {1000000}
if set to negative value = unlimited rate
Protected Attributes inherited from ListNode< MavlinkStream *>
MavlinkStream * _list_node_sibling
Detailed Description
Definition at line 4124 of file mavlink_messages.cpp.
Constructor & Destructor Documentation
MavlinkStreamNavControllerOutput() [1/2]
MavlinkStreamNavControllerOutput::MavlinkStreamNavControllerOutput (MavlinkStreamNavControllerOutput &) private delete
MavlinkStreamNavControllerOutput() [2/2]
MavlinkStreamNavControllerOutput::MavlinkStreamNavControllerOutput (Mavlink * mavlink) inline explicit protected
Definition at line 4170 of file mavlink_messages.cpp.
Member Function Documentation
get_id()
uint16_t MavlinkStreamNavControllerOutput::get_id () inline override virtual
Implements MavlinkStream.
Definition at line 4142 of file mavlink_messages.cpp.
References MavlinkStreamHeartbeat::get_id_static().
get_id_static()
static uint16_t MavlinkStreamNavControllerOutput::get_id_static () inline static
Definition at line 4137 of file mavlink_messages.cpp.
get_name()
const char* MavlinkStreamNavControllerOutput::get_name () const inline override virtual
Implements MavlinkStream.
Definition at line 4127 of file mavlink_messages.cpp.
References get_name_static().
get_name_static()
static const char* MavlinkStreamNavControllerOutput::get_name_static () inline static
Definition at line 4132 of file mavlink_messages.cpp.
Referenced by get_name().
get_size()
unsigned MavlinkStreamNavControllerOutput::get_size () inline override virtual
Get maximal total messages size on update.
Implements MavlinkStream.
Definition at line 4152 of file mavlink_messages.cpp.
new_instance()
static MavlinkStream* MavlinkStreamNavControllerOutput::new_instance (Mavlink * mavlink) inline static
Definition at line 4147 of file mavlink_messages.cpp.
operator=()
MavlinkStreamNavControllerOutput& MavlinkStreamNavControllerOutput::operator= (const MavlinkStreamNavControllerOutput &) private delete
send()
bool MavlinkStreamNavControllerOutput::send (const hrt_abstime t) inline override protected virtual
Implements MavlinkStream.
Definition at line 4175 of file mavlink_messages.cpp.
References MavlinkStream::_mavlink, tecs_status_s::airspeed_filtered, tecs_status_s::airspeed_sp, tecs_status_s::altitude_filtered, tecs_status_s::altitude_sp, math::degrees(), Mavlink::get_channel(), msg, position_controller_status_s::nav_bearing, position_controller_status_s::nav_pitch, position_controller_status_s::nav_roll, position_controller_status_s::target_bearing, MavlinkOrbSubscription::update(), position_controller_status_s::wp_dist, and position_controller_status_s::xtrack_error.
Member Data Documentation
_pos_ctrl_status_sub
MavlinkOrbSubscription* MavlinkStreamNavControllerOutput::_pos_ctrl_status_sub private
Definition at line 4159 of file mavlink_messages.cpp.
_pos_ctrl_status_timestamp
uint64_t MavlinkStreamNavControllerOutput::_pos_ctrl_status_timestamp {0} private
Definition at line 4162 of file mavlink_messages.cpp.
_tecs_status_sub
MavlinkOrbSubscription* MavlinkStreamNavControllerOutput::_tecs_status_sub private
Definition at line 4160 of file mavlink_messages.cpp.
_tecs_status_timestamp
uint64_t MavlinkStreamNavControllerOutput::_tecs_status_timestamp {0} private
Definition at line 4163 of file mavlink_messages.cpp.
The documentation for this class was generated from the following file:
src/modules/mavlink/mavlink_messages.cpp