PX4 Firmware: lsm303agr Namespace Reference
lsm303agr Namespace Reference
Local functions in support of the shell command.
Functions
void start (enum Rotation rotation)
Start the driver.
void info ()
Print a little info about the driver.
void usage ()
Prints info about the driver argument usage.
Variables
LSM303AGR * g_dev
Detailed Description
Local functions in support of the shell command.
Function Documentation
info()
void lsm303agr::info ()
Print a little info about the driver.
Definition at line 113 of file lsm303agr_main.cpp.
References errx, and LSM303AGR::print_info().
Referenced by lsm303agr_main().
start()
void lsm303agr::start (enum Rotation rotation)
Start the driver.
This function call only returns once the driver is up and running or failed to detect the sensor.
Definition at line 63 of file lsm303agr_main.cpp.
References errx, g_dev, LSM303AGR::init(), LSM303AGR_DEVICE_PATH_MAG, OK, px4_close(), px4_ioctl(), px4_open(), SENSOR_POLLRATE_DEFAULT, and SENSORIOCSPOLLRATE.
Referenced by lsm303agr_main().
usage()
void lsm303agr::usage (void)
Prints info about the driver argument usage.
Prints info about the driver argument usage.
Definition at line 126 of file lsm303agr_main.cpp.
Referenced by lsm303agr_main().
Variable Documentation
g_dev
LSM303AGR* lsm303agr::g_dev
Definition at line 50 of file lsm303agr_main.cpp.
Referenced by start().