PX4 Firmware: Tailsitter Class Reference
Tailsitter Class Reference
#include <tailsitter.h>
Public Member Functions
Tailsitter (VtolAttitudeControl *_att_controller)
~Tailsitter () override=default
void update_vtol_state () override
Update vtol state.
void update_transition_state () override
Update transition state.
void update_fw_state () override
Update fixed wing state.
void fill_actuator_outputs () override
Write data to actuator output topic.
void waiting_on_tecs () override
Special handling opportunity for the time right after transition to FW before TECS is running.
Public Member Functions inherited from VtolType
VtolType (VtolAttitudeControl *att_controller)
VtolType (const VtolType &)=delete
VtolType & operator= (const VtolType &)=delete
virtual ~VtolType ()=default
bool init ()
Initialise.
virtual void update_mc_state ()
Update multicopter state.
void check_quadchute_condition ()
Checks for fixed-wing failsafe condition and issues abort request if needed.
bool can_transition_on_ground ()
Returns true if we're allowed to do a mode transition on the ground.
mode get_mode ()
Private Types
enum vtol_mode { vtol_mode::MC_MODE = 0, vtol_mode::TRANSITION_FRONT_P1, vtol_mode::TRANSITION_BACK, vtol_mode::FW_MODE }
Private Member Functions
void parameters_update () override
Private Attributes
struct {
float front_trans_dur_p2
float fw_pitch_sp_offset
} _params_tailsitter
struct {
param_t front_trans_dur_p2
param_t fw_pitch_sp_offset
} _params_handles_tailsitter
struct {
vtol_mode flight_mode
vtol flight mode, defined by enum vtol_mode
hrt_abstime transition_start
absoulte time at which front transition started
} _vtol_schedule
matrix::Quatf _q_trans_start
matrix::Quatf _q_trans_sp
matrix::Vector3f _trans_rot_axis
Additional Inherited Members
Protected Member Functions inherited from VtolType
bool set_idle_mc ()
Sets mc motor minimum pwm to VT_IDLE_PWM_MC which ensures that they are spinning in mc mode.
bool set_idle_fw ()
Sets mc motor minimum pwm to PWM_MIN which ensures that the motors stop spinning on zero throttle in fw mode.
motor_state set_motor_state (const motor_state current_state, const motor_state next_state, const int value=0)
Sets state of a selection of motors, see struct motor_state.
Protected Attributes inherited from VtolType
VtolAttitudeControl * _attc
mode _vtol_mode
struct vehicle_attitude_s * _v_att
struct vehicle_attitude_setpoint_s * _v_att_sp
struct vehicle_attitude_setpoint_s * _mc_virtual_att_sp
struct vehicle_attitude_setpoint_s * _fw_virtual_att_sp
struct vehicle_control_mode_s * _v_control_mode
struct vtol_vehicle_status_s * _vtol_vehicle_status
struct actuator_controls_s * _actuators_out_0
struct actuator_controls_s * _actuators_out_1
struct actuator_controls_s * _actuators_mc_in
struct actuator_controls_s * _actuators_fw_in
struct vehicle_local_position_s * _local_pos
struct vehicle_local_position_setpoint_s * _local_pos_sp
struct airspeed_validated_s * _airspeed_validated
struct tecs_status_s * _tecs_status
struct vehicle_land_detected_s * _land_detected
struct Params * _params
bool flag_idle_mc = false
bool _pusher_active = false
float _mc_roll_weight = 1.0f
float _mc_pitch_weight = 1.0f
float _mc_yaw_weight = 1.0f
float _mc_throttle_weight = 1.0f
float _thrust_transition = 0.0f
float _ra_hrate = 0.0f
float _ra_hrate_sp = 0.0f
bool _flag_was_in_trans_mode = false
hrt_abstime _trans_finished_ts = 0
bool _tecs_running = false
hrt_abstime _tecs_running_ts = 0
motor_state _motor_state = motor_state::DISABLED
Static Protected Attributes inherited from VtolType
static constexpr const int num_outputs_max = 8
Detailed Description
Definition at line 51 of file tailsitter.h.
Member Enumeration Documentation
vtol_mode
enum Tailsitter::vtol_mode strong private
Enumerator
MC_MODE
vtol is in multicopter mode
TRANSITION_FRONT_P1
vtol is in front transition part 1 mode
TRANSITION_BACK
vtol is in back transition mode
FW_MODE
vtol is in fixed wing mode
Definition at line 76 of file tailsitter.h.
Constructor & Destructor Documentation
Tailsitter()
Tailsitter::Tailsitter (VtolAttitudeControl * _att_controller)
Definition at line 52 of file tailsitter.cpp.
References VtolType::_flag_was_in_trans_mode, VtolType::_mc_pitch_weight, VtolType::_mc_roll_weight, VtolType::_mc_yaw_weight, _params_handles_tailsitter, _vtol_schedule, MC_MODE, and param_find().
~Tailsitter()
Tailsitter::~Tailsitter () override default
Member Function Documentation
fill_actuator_outputs()
void Tailsitter::fill_actuator_outputs () override virtual
Write data to actuator output topic.
Implements VtolType.
Definition at line 287 of file tailsitter.cpp.
References VtolType::_actuators_fw_in, VtolType::_actuators_mc_in, VtolType::_actuators_out_0, VtolType::_actuators_out_1, VtolType::_mc_pitch_weight, VtolType::_mc_roll_weight, VtolType::_mc_yaw_weight, VtolType::_params, _vtol_schedule, actuator_controls_s::control, Params::elevons_mc_lock, FW_MODE, hrt_absolute_time(), MC_MODE, actuator_controls_s::timestamp, and actuator_controls_s::timestamp_sample.
parameters_update()
void Tailsitter::parameters_update () override private virtual
Implements VtolType.
Definition at line 69 of file tailsitter.cpp.
References _params_handles_tailsitter, _params_tailsitter, param_get(), and math::radians().
update_fw_state()
void Tailsitter::update_fw_state () override virtual
Update fixed wing state.
Reimplemented from VtolType.
Definition at line 273 of file tailsitter.cpp.
References VtolType::_mc_roll_weight, VtolType::_params, Params::diff_thrust, and VtolType::update_fw_state().
update_transition_state()
void Tailsitter::update_transition_state () override virtual
Update transition state.
Implements VtolType.
Definition at line 189 of file tailsitter.cpp.
References VtolType::_flag_was_in_trans_mode, VtolType::_fw_virtual_att_sp, VtolType::_mc_pitch_weight, VtolType::_mc_roll_weight, VtolType::_mc_virtual_att_sp, VtolType::_mc_yaw_weight, VtolType::_params, _params_tailsitter, _q_trans_sp, _q_trans_start, _trans_rot_axis, VtolType::_v_att, VtolType::_v_att_sp, _vtol_schedule, Params::back_trans_duration, matrix::Matrix< Type, M, N >::copyTo(), matrix::Vector3< Type >::cross(), matrix::Quaternion< Type >::dcm_z(), f(), VtolType::flag_idle_mc, Params::front_trans_duration, hrt_absolute_time(), matrix::Euler< Type >::phi(), vehicle_attitude_setpoint_s::pitch_body, matrix::Euler< Type >::psi(), vehicle_attitude_s::q, vehicle_attitude_setpoint_s::q_d, vehicle_attitude_setpoint_s::q_d_valid, vehicle_attitude_setpoint_s::roll_body, VtolType::set_idle_mc(), matrix::Euler< Type >::theta(), vehicle_attitude_setpoint_s::thrust_body, vehicle_attitude_setpoint_s::timestamp, TRANSITION_BACK, TRANSITION_FRONT_P1, and vehicle_attitude_setpoint_s::yaw_body.
update_vtol_state()
void Tailsitter::update_vtol_state () override virtual
Update vtol state.
Implements VtolType.
Definition at line 81 of file tailsitter.cpp.
References VtolType::_airspeed_validated, VtolType::_attc, VtolType::_flag_was_in_trans_mode, VtolType::_params, VtolType::_v_att, VtolType::_vtol_mode, _vtol_schedule, VtolType::_vtol_vehicle_status, Params::airspeed_disabled, Params::back_trans_duration, VtolType::can_transition_on_ground(), airspeed_validated_s::equivalent_airspeed_m_s, f(), FIXED_WING, FW_MODE, hrt_absolute_time(), VtolAttitudeControl::is_fixed_wing_requested(), MC_MODE, PITCH_TRANSITION_BACK, PITCH_TRANSITION_FRONT_P1, vehicle_attitude_s::q, ROTARY_WING, Params::transition_airspeed, TRANSITION_BACK, TRANSITION_FRONT_P1, TRANSITION_TO_FW, TRANSITION_TO_MC, and vtol_vehicle_status_s::vtol_in_trans_mode.
waiting_on_tecs()
void Tailsitter::waiting_on_tecs () override virtual
Special handling opportunity for the time right after transition to FW before TECS is running.
Reimplemented from VtolType.
Definition at line 267 of file tailsitter.cpp.
References VtolType::_thrust_transition, VtolType::_v_att_sp, and vehicle_attitude_setpoint_s::thrust_body.
Member Data Documentation
_params_handles_tailsitter
struct { ... } Tailsitter::_params_handles_tailsitter
Referenced by parameters_update(), and Tailsitter().
_params_tailsitter
struct { ... } Tailsitter::_params_tailsitter
Referenced by parameters_update(), and update_transition_state().
_q_trans_sp
matrix::Quatf Tailsitter::_q_trans_sp private
Definition at line 89 of file tailsitter.h.
Referenced by update_transition_state().
_q_trans_start
matrix::Quatf Tailsitter::_q_trans_start private
Definition at line 88 of file tailsitter.h.
Referenced by update_transition_state().
_trans_rot_axis
matrix::Vector3f Tailsitter::_trans_rot_axis private
Definition at line 90 of file tailsitter.h.
Referenced by update_transition_state().
_vtol_schedule
struct { ... } Tailsitter::_vtol_schedule
Referenced by fill_actuator_outputs(), Tailsitter(), update_transition_state(), and update_vtol_state().
flight_mode
vtol_mode Tailsitter::flight_mode
vtol flight mode, defined by enum vtol_mode
Definition at line 84 of file tailsitter.h.
front_trans_dur_p2 [1/2]
float Tailsitter::front_trans_dur_p2
Definition at line 67 of file tailsitter.h.
front_trans_dur_p2 [2/2]
param_t Tailsitter::front_trans_dur_p2
Definition at line 72 of file tailsitter.h.
fw_pitch_sp_offset [1/2]
float Tailsitter::fw_pitch_sp_offset
Definition at line 68 of file tailsitter.h.
fw_pitch_sp_offset [2/2]
param_t Tailsitter::fw_pitch_sp_offset
Definition at line 73 of file tailsitter.h.
transition_start
hrt_abstime Tailsitter::transition_start
absoulte time at which front transition started
Definition at line 85 of file tailsitter.h.
The documentation for this class was generated from the following files:
src/modules/vtol_att_control/tailsitter.h
src/modules/vtol_att_control/tailsitter.cpp