PX4 Firmware: GPSSIM Class Reference
GPSSIM Class Reference
Public Member Functions
GPSSIM (const char *uart_path, bool fake_gps, bool enable_sat_info, int fix_type, int num_sat, int noise_multiplier)
virtual ~GPSSIM ()
virtual int init ()
virtual int devIOCTL (unsigned long cmd, unsigned long arg)
void set (int fix_type, int num_sat, int noise_multiplier)
void print_info ()
Diagnostics - print some basic information about the driver.
Protected Member Functions
virtual void _measure ()
Private Member Functions
void config ()
Try to configure the GPS, handle outgoing communication to the GPS.
void task_main ()
Worker task: main GPS thread that configures the GPS and parses incoming data, always running.
int set_baudrate (unsigned baud)
Set the baudrate of the UART to the GPS.
void cmd_reset ()
Send a reset command to the GPS.
int receive (int timeout)
Static Private Member Functions
static int task_main_trampoline (int argc, char *argv[])
Trampoline to the worker task.
Private Attributes
bool _task_should_exit
flag to make the main worker task exit
volatile int _task
worker task
GPS_Sat_Info * _Sat_Info
instance of GPS sat info data object
struct vehicle_gps_position_s _report_gps_pos
uORB topic for gps position
orb_advert_t _report_gps_pos_pub
uORB pub for gps position
struct satellite_info_s * _p_report_sat_info
pointer to uORB topic for satellite info
orb_advert_t _report_sat_info_pub
uORB pub for satellite info
SyncObj _sync
int _fix_type
int _num_sat
int _noise_multiplier
std::default_random_engine _gen
Detailed Description
Definition at line 86 of file gpssim.cpp.
Constructor & Destructor Documentation
GPSSIM::GPSSIM (const char * uart_path, bool fake_gps, bool enable_sat_info, int fix_type, int num_sat, int noise_multiplier)
Definition at line 166 of file gpssim.cpp.
References GPS_Sat_Info::_data, _fix_type, _noise_multiplier, _num_sat, _p_report_sat_info, _report_gps_pos, _report_gps_pos_pub, _report_sat_info_pub, _Sat_Info, gpssim::g_dev, and vehicle_gps_position_s::heading.
Referenced by gpssim::start().
GPSSIM::~GPSSIM () virtual
Definition at line 191 of file gpssim.cpp.
References _Sat_Info, _task, _task_should_exit, gpssim::g_dev, px4_task_delete(), and usleep().
Member Function Documentation
virtual void GPSSIM::_measure (void) inline protected virtual
Definition at line 105 of file gpssim.cpp.
void GPSSIM::cmd_reset () private
Send a reset command to the GPS.
Definition at line 355 of file gpssim.cpp.
Referenced by devIOCTL().
void GPSSIM::config () private
Try to configure the GPS, handle outgoing communication to the GPS.
int GPSSIM::devIOCTL (unsigned long cmd, unsigned long arg) virtual
Definition at line 237 of file gpssim.cpp.
References _sync, cmd_reset(), OK, and SENSORIOCRESET.
int GPSSIM::init () virtual
Definition at line 213 of file gpssim.cpp.
References _task, lis3mdl::init(), OK, PX4_ERR, PX4_ERROR, px4_task_spawn_cmd(), SCHED_DEFAULT, and task_main_trampoline().
Referenced by gpssim::start().
void GPSSIM::print_info (void)
Diagnostics - print some basic information about the driver.
Definition at line 360 of file gpssim.cpp.
References _p_report_sat_info, _report_gps_pos, vehicle_gps_position_s::jamming_indicator, vehicle_gps_position_s::noise_per_ms, PX4_INFO, vehicle_gps_position_s::timestamp, and usleep().
Referenced by gpssim::info().
int GPSSIM::receive (int timeout) private
Definition at line 267 of file gpssim.cpp.
References _fix_type, _gen, _noise_multiplier, _num_sat, _report_gps_pos, vehicle_gps_position_s::alt, simulator::RawGPSData::alt, simulator::RawGPSData::cog, vehicle_gps_position_s::cog_rad, vehicle_gps_position_s::eph, simulator::RawGPSData::eph, vehicle_gps_position_s::epv, simulator::RawGPSData::epv, f(), vehicle_gps_position_s::fix_type, simulator::RawGPSData::fix_type, Simulator::getGPSSample(), Simulator::getInstance(), gps, hrt_absolute_time(), vehicle_gps_position_s::lat, simulator::RawGPSData::lat, vehicle_gps_position_s::lon, simulator::RawGPSData::lon, vehicle_gps_position_s::satellites_used, simulator::RawGPSData::satellites_visible, vehicle_gps_position_s::timestamp, simulator::RawGPSData::timestamp, usleep(), simulator::RawGPSData::vd, simulator::RawGPSData::ve, simulator::RawGPSData::vel, vehicle_gps_position_s::vel_d_m_s, vehicle_gps_position_s::vel_e_m_s, vehicle_gps_position_s::vel_m_s, vehicle_gps_position_s::vel_n_m_s, and simulator::RawGPSData::vn.
Referenced by task_main().
void GPSSIM::set (int fix_type, int num_sat, int noise_multiplier)
Definition at line 378 of file gpssim.cpp.
References _fix_type, _noise_multiplier, _num_sat, and PX4_INFO.
Referenced by gpssim_main().
int GPSSIM::set_baudrate (unsigned baud) private
Set the baudrate of the UART to the GPS.
void GPSSIM::task_main () private
Worker task: main GPS thread that configures the GPS and parses incoming data, always running.
Definition at line 310 of file gpssim.cpp.
References _p_report_sat_info, _report_gps_pos, _report_gps_pos_pub, _report_sat_info_pub, _task, _task_should_exit, orb_advertise(), ORB_ID, orb_publish(), orb_unadvertise(), PX4_INFO, receive(), and TIMEOUT_100MS.
Referenced by task_main_trampoline().
int GPSSIM::task_main_trampoline (int argc, char * argv[]) static private
Trampoline to the worker task.
Definition at line 260 of file gpssim.cpp.
References gpssim::g_dev, and task_main().
Referenced by init().
Member Data Documentation
int GPSSIM::_fix_type private
Definition at line 117 of file gpssim.cpp.
Referenced by GPSSIM(), receive(), and set().
std::default_random_engine GPSSIM::_gen private
Definition at line 121 of file gpssim.cpp.
Referenced by receive().
int GPSSIM::_noise_multiplier private
Definition at line 119 of file gpssim.cpp.
Referenced by GPSSIM(), receive(), and set().
int GPSSIM::_num_sat private
Definition at line 118 of file gpssim.cpp.
Referenced by GPSSIM(), receive(), and set().
struct satellite_info_s* GPSSIM::_p_report_sat_info private
pointer to uORB topic for satellite info
Definition at line 114 of file gpssim.cpp.
Referenced by GPSSIM(), print_info(), and task_main().
struct vehicle_gps_position_s GPSSIM::_report_gps_pos private
uORB topic for gps position
Definition at line 112 of file gpssim.cpp.
Referenced by GPSSIM(), print_info(), receive(), and task_main().
orb_advert_t GPSSIM::_report_gps_pos_pub private
uORB pub for gps position
Definition at line 113 of file gpssim.cpp.
Referenced by GPSSIM(), and task_main().
orb_advert_t GPSSIM::_report_sat_info_pub private
uORB pub for satellite info
Definition at line 115 of file gpssim.cpp.
Referenced by GPSSIM(), and task_main().
GPS_Sat_Info* GPSSIM::_Sat_Info private
instance of GPS sat info data object
Definition at line 111 of file gpssim.cpp.
Referenced by GPSSIM(), and ~GPSSIM().
SyncObj GPSSIM::_sync private
Definition at line 116 of file gpssim.cpp.
Referenced by devIOCTL().
volatile int GPSSIM::_task private
worker task
Definition at line 110 of file gpssim.cpp.
Referenced by init(), task_main(), and ~GPSSIM().
bool GPSSIM::_task_should_exit private
flag to make the main worker task exit
Definition at line 109 of file gpssim.cpp.
Referenced by task_main(), and ~GPSSIM().
The documentation for this class was generated from the following file:
src/modules/simulator/gpssim/gpssim.cpp