PX4 Firmware: mpu9250 Namespace Reference
mpu9250 Namespace Reference
Local functions in support of the shell command.
Classes
struct mpu9250_bus_option
Functions
void start (enum MPU9250_BUS busid, enum Rotation rotation, bool external)
Start the driver.
bool start_bus (struct mpu9250_bus_option &bus, enum Rotation rotation, bool external)
start driver for a specific bus option
struct mpu9250_bus_option & find_bus (enum MPU9250_BUS busid)
find a bus structure for a busid
void stop (enum MPU9250_BUS busid)
void test (enum MPU9250_BUS busid)
Perform some basic functional tests on the driver; make sure we can collect data from the sensor in polled and automatic modes.
void reset (enum MPU9250_BUS busid)
Reset the driver.
void info (enum MPU9250_BUS busid)
Print a little info about the driver.
void regdump (enum MPU9250_BUS busid)
Dump the register information.
void testerror (enum MPU9250_BUS busid)
deliberately produce an error to test recovery
void usage ()
Prints info about the driver argument usage.
Variables
struct mpu9250::mpu9250_bus_option bus_options []
Detailed Description
Local functions in support of the shell command.
Function Documentation
struct mpu9250_bus_option & mpu9250::find_bus (enum MPU9250_BUS busid)
find a bus structure for a busid
Definition at line 171 of file main.cpp.
References bus_options, mpu9250::mpu9250_bus_option::dev, errx, MPU9250_BUS_ALL, and NUM_BUS_OPTIONS.
Referenced by info(), regdump(), reset(), stop(), test(), and testerror().
void mpu9250::info (enum MPU9250_BUS busid)
Print a little info about the driver.
Definition at line 425 of file main.cpp.
References mpu9250::mpu9250_bus_option::dev, errx, find_bus(), and MPU9250::print_info().
Referenced by mpu9250_main().
void mpu9250::regdump (enum MPU9250_BUS busid)
Dump the register information.
Definition at line 444 of file main.cpp.
References mpu9250::mpu9250_bus_option::dev, errx, find_bus(), and MPU9250::print_registers().
Referenced by mpu9250_main().
void mpu9250::reset (enum MPU9250_BUS busid)
Reset the driver.
Definition at line 399 of file main.cpp.
References mpu9250::mpu9250_bus_option::accelpath, err, fd, find_bus(), SENSOR_POLLRATE_DEFAULT, SENSORIOCRESET, and SENSORIOCSPOLLRATE.
Referenced by mpu9250_main(), and test().
void mpu9250::start (enum MPU9250_BUS busid, enum Rotation rotation, bool external)
Start the driver.
This function only returns if the driver is up and running or failed to detect the sensor.
Definition at line 269 of file main.cpp.
References bus_options, mpu9250::mpu9250_bus_option::dev, MPU9250_BUS_ALL, NUM_BUS_OPTIONS, and start_bus().
Referenced by mpu9250_main().
bool mpu9250::start_bus (struct mpu9250_bus_option & bus, enum Rotation rotation, bool external_bus)
start driver for a specific bus option
Definition at line 187 of file main.cpp.
References AK8963_I2C_interface(), mpu9250::mpu9250_bus_option::dev, errx, fd, MPU9250_BUS_I2C_EXTERNAL, MPU9250_BUS_I2C_INTERNAL, OK, SENSOR_POLLRATE_DEFAULT, SENSORIOCSPOLLRATE, and warnx.
Referenced by start().
void mpu9250::stop (enum MPU9250_BUS busid)
Definition at line 293 of file main.cpp.
References mpu9250::mpu9250_bus_option::dev, find_bus(), and warnx.
Referenced by mpu9250_main().
void mpu9250::test (enum MPU9250_BUS busid)
Perform some basic functional tests on the driver; make sure we can collect data from the sensor in polled and automatic modes.
Definition at line 316 of file main.cpp.
References accel_report, mpu9250::mpu9250_bus_option::accelpath, err, errx, fd, find_bus(), gyro_report, mpu9250::mpu9250_bus_option::gyropath, mag_report, mpu9250::mpu9250_bus_option::magpath, read(), reset(), SENSOR_POLLRATE_DEFAULT, SENSOR_POLLRATE_MANUAL, SENSORIOCSPOLLRATE, and warnx.
Referenced by mpu9250_main().
void mpu9250::testerror (enum MPU9250_BUS busid)
deliberately produce an error to test recovery
Definition at line 463 of file main.cpp.
References mpu9250::mpu9250_bus_option::dev, errx, find_bus(), and MPU9250::test_error().
Referenced by mpu9250_main().
void mpu9250::usage (void)
Prints info about the driver argument usage.
Prints info about the driver argument usage.
Definition at line 478 of file main.cpp.
References PX4_INFO.
Referenced by mpu9250_main().
Variable Documentation
struct mpu9250::mpu9250_bus_option mpu9250::bus_options[]
Initial value:
= {
}
Referenced by find_bus(), and start().