PX4 Firmware: src/lib/pid/pid.cpp File Reference
pid.cpp File Reference
#include "pid.h"
#include <math.h>
#include <px4_defines.h>
Macros
#define SIGMA 0.000001f
Functions
__EXPORT void pid_init (PID_t *pid, pid_mode_t mode, float dt_min)
__EXPORT int pid_set_parameters (PID_t *pid, float kp, float ki, float kd, float integral_limit, float output_limit)
__EXPORT float pid_calculate (PID_t *pid, float sp, float val, float val_dot, float dt)
__EXPORT void pid_reset_integral (PID_t *pid)
Macro Definition Documentation
#define SIGMA 0.000001f
Definition at line 55 of file pid.cpp.
Referenced by pid_calculate().
Function Documentation
__EXPORT float pid_calculate (PID_t * pid, float sp, float val, float val_dot, float dt)
Definition at line 113 of file pid.cpp.
References dt, PID_t::dt_min, PID_t::error_previous, PID_t::integral, PID_t::integral_limit, PID_t::kd, PID_t::ki, PID_t::kp, PID_t::last_output, PID_t::mode, PID_t::output_limit, PID_MODE_DERIVATIV_CALC, PID_MODE_DERIVATIV_CALC_NO_SP, PID_MODE_DERIVATIV_SET, and SIGMA.
Referenced by GroundRoverPositionControl::control_position(), and GroundRoverAttitudeControl::task_main().
__EXPORT void pid_init (PID_t * pid, pid_mode_t mode, float dt_min)
Definition at line 57 of file pid.cpp.
References PID_t::dt_min, PID_t::error_previous, PID_t::integral, PID_t::integral_limit, PID_t::kd, PID_t::ki, PID_t::kp, PID_t::last_output, PID_t::mode, and PID_t::output_limit.
Referenced by GroundRoverAttitudeControl::parameters_update(), and GroundRoverPositionControl::parameters_update().
__EXPORT void pid_reset_integral (PID_t * pid)
Definition at line 182 of file pid.cpp.
References PID_t::integral.
__EXPORT int pid_set_parameters (PID_t * pid, float kp, float ki, float kd, float integral_limit, float output_limit)
Definition at line 71 of file pid.cpp.
References PID_t::integral_limit, PID_t::kd, PID_t::ki, PID_t::kp, and PID_t::output_limit.
Referenced by GroundRoverAttitudeControl::parameters_update(), and GroundRoverPositionControl::parameters_update().