PX4 Firmware: src/systemcmds/tests/test_param.c File Reference
test_param.c File Reference
Tests related to the parameter system.
#include <px4_platform_common/defines.h>
#include <stdio.h>
#include "systemlib/err.h"
#include <parameters/param.h>
#include "tests_main.h"
Macros
#define PARAM_MAGIC1 12345678
#define PARAM_MAGIC2 0xa5a5a5a5
Functions
int test_param (int argc, char *argv[])
Detailed Description
Tests related to the parameter system.
Definition in file test_param.c.
Macro Definition Documentation
PARAM_MAGIC1
#define PARAM_MAGIC1 12345678
Definition at line 45 of file test_param.c.
Referenced by test_param().
PARAM_MAGIC2
#define PARAM_MAGIC2 0xa5a5a5a5
Definition at line 46 of file test_param.c.
Referenced by test_param().
Function Documentation
test_param()
int test_param (int argc, char * argv[])
Definition at line 49 of file test_param.c.
References OK, param_find(), param_get(), PARAM_INVALID, PARAM_MAGIC1, PARAM_MAGIC2, param_reset(), param_set(), param_type(), PARAM_TYPE_INT32, and warnx.