PX4 Firmware: src/systemcmds/tests/hrt_test/hrt_test_main.cpp File Reference
hrt_test_main.cpp File Reference
Example for Linux.
#include "hrt_test.h"
#include <stdio.h>
#include <px4_platform_common/app.h>
#include <px4_platform_common/init.h>
Functions
int PX4_MAIN (int argc, char **argv)
Detailed Description
Example for Linux.
Author
Mark Charlebois charl.nosp@m.ebm@.nosp@m.gmail.nosp@m..com
Definition in file hrt_test_main.cpp.
Function Documentation
PX4_MAIN()
int PX4_MAIN (int argc, char ** argv)
Definition at line 48 of file hrt_test_main.cpp.
References ToneAlarmInterface::init(), HRTTest::main(), and lps25h::test().