PX4 Firmware: PositionEstimator Class Reference
PositionEstimator Class Reference
#include <position_estimator.h>
Public Member Functions
PositionEstimator ()
~PositionEstimator ()
Protected Member Functions
void ModelStatesCallback (const gazebo_msgs::ModelStatesConstPtr &msg)
Protected Attributes
ros::NodeHandle _n
ros::Subscriber _sub_modelstates
ros::Publisher _vehicle_position_pub
uint64_t _startup_time
std::string _model_name
Detailed Description
Definition at line 47 of file position_estimator.h.
Constructor & Destructor Documentation
PositionEstimator::PositionEstimator ()
Definition at line 51 of file position_estimator.cpp.
References _model_name, and _n.
PositionEstimator::~PositionEstimator () inline
Definition at line 52 of file position_estimator.h.
References ModelStatesCallback(), and msg.
Member Function Documentation
void PositionEstimator::ModelStatesCallback (const gazebo_msgs::ModelStatesConstPtr & msg) protected
Definition at line 60 of file position_estimator.cpp.
References _model_name, _startup_time, _vehicle_position_pub, and px4::get_time_micros().
Referenced by ~PositionEstimator().
Member Data Documentation
std::string PositionEstimator::_model_name protected
Definition at line 62 of file position_estimator.h.
Referenced by ModelStatesCallback(), and PositionEstimator().
ros::NodeHandle PositionEstimator::_n protected
Definition at line 57 of file position_estimator.h.
Referenced by PositionEstimator().
uint64_t PositionEstimator::_startup_time protected
Definition at line 61 of file position_estimator.h.
Referenced by ModelStatesCallback().
ros::Subscriber PositionEstimator::_sub_modelstates protected
Definition at line 58 of file position_estimator.h.
ros::Publisher PositionEstimator::_vehicle_position_pub protected
Definition at line 59 of file position_estimator.h.
Referenced by ModelStatesCallback().
The documentation for this class was generated from the following files:
src/platforms/ros/nodes/position_estimator/position_estimator.h
src/platforms/ros/nodes/position_estimator/position_estimator.cpp