PX4 Firmware: src/systemcmds/tests/test_sensors.c File Reference
test_sensors.c File Reference
Tests the onboard sensors.
#include <px4_config.h>
#include <px4_posix.h>
#include <sys/types.h>
#include <stdio.h>
#include <stdlib.h>
#include <unistd.h>
#include <fcntl.h>
#include <errno.h>
#include <math.h>
#include <systemlib/err.h>
#include <arch/board/board.h>
#include "tests_main.h"
#include <drivers/drv_gyro.h>
#include <drivers/drv_accel.h>
#include <drivers/drv_mag.h>
#include <drivers/drv_baro.h>
Functions
static int accel (int argc, char *argv[], const char *path)
static int gyro (int argc, char *argv[], const char *path)
static int mag (int argc, char *argv[], const char *path)
static int baro (int argc, char *argv[], const char *path)
int test_sensors (int argc, char *argv[])
Variables
struct {
const char * name
const char * path
int(* test)(int argc, char *argv[],
const char *path)
} sensors []
Detailed Description
Tests the onboard sensors.
Author
Lorenz Meier lm@in.nosp@m.f.et.nosp@m.hz.ch
Definition in file test_sensors.c.
Function Documentation
static int accel (int argc, char * argv[], const char * path) static
Definition at line 87 of file test_sensors.c.
References accel_report, f(), fd, OK, px4_close(), px4_open(), px4_read(), usleep(), and warnx.
Referenced by MPU6000::factory_self_test(), Simulator::initializeSensorData(), events::SendEvent::process_commands(), and Simulator::update_sensors().
static int baro (int argc, char * argv[], const char * path) static
Definition at line 227 of file test_sensors.c.
References baro_report, fd, OK, px4_close(), px4_open(), px4_read(), and usleep().
Referenced by Simulator::initializeSensorData(), main(), ADIS16448::measure(), events::SendEvent::process_commands(), FixedwingPositionControl::tecs_update_pitch_throttle(), and Simulator::update_sensors().
static int gyro (int argc, char * argv[], const char * path) static
Definition at line 137 of file test_sensors.c.
References f(), fd, gyro_report, OK, px4_close(), px4_open(), px4_read(), usleep(), and warnx.
Referenced by MPU6000::factory_self_test(), events::SendEvent::process_commands(), and MicroBenchORB::MicroBenchORB::reset().
static int mag (int argc, char * argv[], const char * path) static
Definition at line 182 of file test_sensors.c.
References f(), fd, mag_report, OK, px4_close(), px4_open(), px4_read(), usleep(), and warnx.
Referenced by FlightTaskManualPosition::_scaleSticks(), PositionControl::_velocityController(), matrix::AxisAngle< Type >::AxisAngle(), EstimatorInterface::get_filter_fault_status(), Ekf::get_quat_reset(), Simulator::initializeSensorData(), main(), and Simulator::update_sensors().
int test_sensors (int argc, char * argv[])
Definition at line 272 of file test_sensors.c.
References name, OK, and path.
Variable Documentation
const char* name
Definition at line 73 of file test_sensors.c.
Referenced by UavcanNode::attachITxQueueInjector(), device::file_t::file_t(), UavcanNode::get_set_param(), MavlinkParametersManager::handle_message(), sensors::initialize_parameter_handles(), px4::ReplayEkf2::onExitMainLoop(), param_export(), param_hash_check(), param_reset_excludes(), FXOS8701CQ::print_registers(), FXAS21002C::print_registers(), LSM303D::print_registers(), px4::Replay::readFormat(), device::CDev::register_class_devname(), register_driver(), control::SuperBlock::setDt(), test_sensors(), device::CDev::unregister_class_devname(), control::SuperBlock::updateChildParams(), control::SuperBlock::updateChildPublications(), control::SuperBlock::updateChildSubscriptions(), control::Block::updateParams(), control::Block::updatePublications(), control::Block::updateSubscriptions(), and px4::logger::Logger::write_info().
const char* path
Definition at line 74 of file test_sensors.c.
Referenced by lis3mdl::calibrate(), ist8310::calibrate(), hmc5883::calibrate(), device::file_t::file_t(), hardfault_commit(), linux_pwm_out::NavioSysfsPWMOut::init(), lis3mdl::init(), uORB::Manager::node_open(), uORB::Manager::orb_exists(), bmm150::reset(), lps22hb::reset(), lis3mdl::reset(), lps25h::reset(), ist8310::reset(), hmc5883::reset(), LinuxGPIO::setDirection(), bmm150::start(), hmc5883::temp_enable(), bmm150::test(), lis3mdl::test(), ist8310::test(), hmc5883::test(), and test_sensors().
struct { ... } sensors[]
Initial value:
= {
    {"accel0",  ACCEL0_DEVICE_PATH, accel},
    {"accel1",  ACCEL1_DEVICE_PATH, accel},
    {"gyro0",   GYRO0_DEVICE_PATH,  gyro},
    {"gyro1",   GYRO1_DEVICE_PATH,  gyro},
    {"mag0",    MAG0_DEVICE_PATH,   mag},
    {"baro0",   BARO0_DEVICE_PATH,  baro},
    {NULL, NULL, NULL}
}
Referenced by AttitudeEstimatorQ::task_main().
int(* test) (int argc, char *argv[], const char *path)
Definition at line 75 of file test_sensors.c.
Referenced by MavlinkFtpTest::_burst_test(), MavlinkFtpTest::_createdirectory_test(), MavlinkFtpTest::_list_test(), MavlinkFtpTest::_open_terminate_test(), MavlinkFtpTest::_read_test(), MavlinkFtpTest::_removedirectory_test(), MavlinkFtpTest::_removefile_test(), StateMachineHelperTest::armingStateTransitionTest(), StateMachineHelperTest::mainStateTransitionTest(), parameter_flashfs_init(), PX4_MAIN(), px4io_main(), PX4IO::set_update_rate(), and uORBTest::UnitTest::~UnitTest().