PX4 Firmware: SubscriptionArray Class Reference
SubscriptionArray Class Reference
#include <SubscriptionArray.hpp>
Public Member Functions
SubscriptionArray ()=default
~SubscriptionArray ()
template<class T >
bool get (const struct orb_metadata *meta, uORB::Subscription< T > *&subscription, unsigned instance=0)
Get a subscription.
void update ()
update all subscriptions (if new data is available)
void forcedUpdate ()
update all subscriptions
Private Member Functions
void cleanup ()
bool resizeSubscriptions ()
Private Attributes
uORB::SubscriptionNode ** _subscriptions {nullptr}
int _subscriptions_count {0}
number of valid subscriptions
int _subscriptions_size {0}
actual size of the _subscriptions array
Detailed Description
Definition at line 46 of file SubscriptionArray.hpp.
Constructor & Destructor Documentation
SubscriptionArray::SubscriptionArray () default
SubscriptionArray::~SubscriptionArray ()
Definition at line 38 of file SubscriptionArray.cpp.
References cleanup().
Member Function Documentation
void SubscriptionArray::cleanup () private
Definition at line 43 of file SubscriptionArray.cpp.
References _subscriptions, and _subscriptions_count.
Referenced by ~SubscriptionArray().
void SubscriptionArray::forcedUpdate ()
update all subscriptions
Definition at line 80 of file SubscriptionArray.cpp.
References _subscriptions, _subscriptions_count, and uORB::SubscriptionNode::forcedUpdate().
Referenced by FlightTasks::switchTask().
template<class T > bool SubscriptionArray::get (const struct orb_metadata * meta, uORB::Subscription< T > *& subscription, unsigned instance = 0)
Get a subscription.
Parameters
meta ORB_ID(topic)
subscription returned subscription (output parameter)
instance topic instance
Returns
true on success, false otherwise (subscription set to nullptr)
Definition at line 84 of file SubscriptionArray.hpp.
References _subscriptions, _subscriptions_count, _subscriptions_size, instance, and resizeSubscriptions().
Referenced by FlightTaskOffboard::initializeSubscriptions(), FlightTaskManual::initializeSubscriptions(), FlightTask::initializeSubscriptions(), and FlightTaskAuto::initializeSubscriptions().
bool SubscriptionArray::resizeSubscriptions () private
Definition at line 53 of file SubscriptionArray.cpp.
References _subscriptions, _subscriptions_count, and _subscriptions_size.
Referenced by get().
void SubscriptionArray::update ()
update all subscriptions (if new data is available)
Definition at line 73 of file SubscriptionArray.cpp.
References _subscriptions, _subscriptions_count, and uORB::SubscriptionNode::update().
Referenced by FlightTasks::update().
Member Data Documentation
uORB::SubscriptionNode** SubscriptionArray::_subscriptions {nullptr} private
Definition at line 77 of file SubscriptionArray.hpp.
Referenced by cleanup(), forcedUpdate(), get(), resizeSubscriptions(), and update().
int SubscriptionArray::_subscriptions_count {0} private
number of valid subscriptions
Definition at line 78 of file SubscriptionArray.hpp.
Referenced by cleanup(), forcedUpdate(), get(), resizeSubscriptions(), and update().
int SubscriptionArray::_subscriptions_size {0} private
actual size of the _subscriptions array
Definition at line 79 of file SubscriptionArray.hpp.
Referenced by get(), and resizeSubscriptions().
The documentation for this class was generated from the following files:
src/lib/FlightTasks/tasks/FlightTask/SubscriptionArray.hpp
src/lib/FlightTasks/tasks/FlightTask/SubscriptionArray.cpp