PX4 Firmware: src/modules/mavlink/mavlink_messages.h File Reference
mavlink_messages.h File Reference
MAVLink 1.0 message formatters definition.
#include "mavlink_stream.h"
Classes
class StreamListItem
Functions
const char * get_stream_name (const uint16_t msg_id)
MavlinkStream * create_mavlink_stream (const char *stream_name, Mavlink *mavlink)
void get_mavlink_navigation_mode (const struct vehicle_status_s *const status, uint8_t *mavlink_base_mode, union px4_custom_mode *custom_mode)
Detailed Description
MAVLink 1.0 message formatters definition.
Author
Anton Babushkin anton.nosp@m..bab.nosp@m.ushki.nosp@m.n@me.nosp@m..com
Definition in file mavlink_messages.h.
Function Documentation
MavlinkStream* create_mavlink_stream (const char * stream_name, Mavlink * mavlink)
Definition at line 4506 of file mavlink_messages.cpp.
Referenced by Mavlink::configure_stream(), and StreamListItem::StreamListItem().
void get_mavlink_navigation_mode (const struct vehicle_status_s *const status, uint8_t * mavlink_base_mode, union px4_custom_mode * custom_mode)
Definition at line 128 of file mavlink_messages.cpp.
References vehicle_status_s::arming_state, px4_custom_mode::data, vehicle_status_s::hil_state, vehicle_status_s::is_rotary_wing, px4_custom_mode::main_mode, vehicle_status_s::nav_state, PX4_CUSTOM_MAIN_MODE_ACRO, PX4_CUSTOM_MAIN_MODE_ALTCTL, PX4_CUSTOM_MAIN_MODE_AUTO, PX4_CUSTOM_MAIN_MODE_MANUAL, PX4_CUSTOM_MAIN_MODE_OFFBOARD, PX4_CUSTOM_MAIN_MODE_POSCTL, PX4_CUSTOM_MAIN_MODE_RATTITUDE, PX4_CUSTOM_MAIN_MODE_STABILIZED, PX4_CUSTOM_SUB_MODE_AUTO_FOLLOW_TARGET, PX4_CUSTOM_SUB_MODE_AUTO_LAND, PX4_CUSTOM_SUB_MODE_AUTO_LOITER, PX4_CUSTOM_SUB_MODE_AUTO_MISSION, PX4_CUSTOM_SUB_MODE_AUTO_PRECLAND, PX4_CUSTOM_SUB_MODE_AUTO_RTGS, PX4_CUSTOM_SUB_MODE_AUTO_RTL, PX4_CUSTOM_SUB_MODE_AUTO_TAKEOFF, and px4_custom_mode::sub_mode.
Referenced by get_mavlink_mode_state(), StreamListItem::StreamListItem(), and MavlinkStreamHighLatency2::write_vehicle_status().
const char* get_stream_name (const uint16_t msg_id)
Definition at line 4494 of file mavlink_messages.cpp.
Referenced by MavlinkReceiver::set_message_interval(), and StreamListItem::StreamListItem().