PX4 Firmware: src/drivers/md25/md25_main.cpp File Reference
md25_main.cpp File Reference
#include <px4_config.h>
#include <unistd.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <math.h>
#include <parameters/param.h>
#include <arch/board/board.h>
#include "md25.hpp"
Functions
__EXPORT int md25_main (int argc, char *argv[])
Deamon management function.
int md25_thread_main (int argc, char *argv[])
Mainloop of deamon.
static void usage (const char *reason)
Print the correct usage.
Variables
static bool thread_should_exit = false
@ file md25.cpp
static bool thread_running = false
Deamon status flag.
static int deamon_task
Handle of deamon task / thread.
Function Documentation
int md25_main (int argc, char * argv[])
Deamon management function.
The deamon app only briefly exists to start the background job.
The stack size assigned in the Makefile does only apply to this management task.
The actual stack size should be set in the call to task_create().
Definition at line 97 of file md25_main.cpp.
References deamon_task, md25_thread_main(), md25Sine(), md25Test(), OK, MD25::probe(), px4_task_spawn_cmd(), SCHED_DEFAULT, SCHED_PRIORITY_MAX, MD25::search(), MD25::setDeviceAddress(), MD25::status(), thread_running, thread_should_exit, and usage().
int md25_thread_main (int argc, char * argv[])
Mainloop of deamon.
Definition at line 278 of file md25_main.cpp.
References thread_running, thread_should_exit, and MD25::update().
Referenced by md25_main().
static void usage (const char * reason) static
Print the correct usage.
Definition at line 79 of file md25_main.cpp.
Referenced by md25_main().
Variable Documentation
int deamon_task static
Handle of deamon task / thread.
Definition at line 61 of file md25_main.cpp.
Referenced by md25_main().
bool thread_running = false static
Deamon status flag.
Definition at line 60 of file md25_main.cpp.
Referenced by md25_main(), and md25_thread_main().
bool thread_should_exit = false static
@ file md25.cpp
Driver for MD25 I2C Motor Driver
references: http://www.robot-electronics.co.uk/htm/md25tech.htm http://www.robot-electronics.co.uk/files/rpi_md25.cDeamon exit flag
Definition at line 59 of file md25_main.cpp.
Referenced by md25_main(), and md25_thread_main().