PX4 Firmware: px4muorb::KraitRpcWrapper Class Reference
px4muorb::KraitRpcWrapper Class Reference
#include <px4muorb_KraitRpcWrapper.hpp>
Public Member Functions
KraitRpcWrapper ()=default
Constructor.
~KraitRpcWrapper ()=default
destructor
bool Initialize ()
Initiatizes the rpc channel px4 muorb.
bool Terminate ()
Terminate to clean up the resources.
int32_t TopicAdvertised (const char *topic)
Muorb related functions to pub/sub of orb topic from krait to adsp.
int32_t TopicUnadvertised (const char *topic)
int32_t AddSubscriber (const char *topic)
int32_t RemoveSubscriber (const char *topic)
int32_t SendData (const char *topic, int32_t length_in_bytes, const uint8_t *data)
int32_t ReceiveData (int32_t *msg_type, char **topic, int32_t *length_in_bytes, uint8_t **data)
int32_t IsSubscriberPresent (const char *topic, int32_t *status)
int32_t ReceiveBulkData (uint8_t **bulk_data, int32_t *length_in_bytes, int32_t *topic_count)
int32_t UnblockReceiveData ()
Detailed Description
Definition at line 42 of file px4muorb_KraitRpcWrapper.hpp.
Constructor & Destructor Documentation
KraitRpcWrapper()
px4muorb::KraitRpcWrapper::KraitRpcWrapper () default
Constructor.
~KraitRpcWrapper()
px4muorb::KraitRpcWrapper::~KraitRpcWrapper () default
destructor
Member Function Documentation
AddSubscriber()
int32_t px4muorb::KraitRpcWrapper::AddSubscriber (const char * topic)
Definition at line 287 of file px4muorb_KraitRpcWrapper.cpp.
References _Initialized, and px4muorb_add_subscriber().
Referenced by uORB::KraitFastRpcChannel::add_subscription().
Initialize()
bool px4muorb::KraitRpcWrapper::Initialize ()
Initiatizes the rpc channel px4 muorb.
Definition at line 148 of file px4muorb_KraitRpcWrapper.cpp.
References _BulkTransferBuffer, _DataBuffer, _Initialized, _MAX_BULK_TRANSFER_BUFFER_SIZE, _MAX_DATA_BUFFER_SIZE, _MAX_TOPIC_NAME_BUFFER, _TopicNameBuffer, adsp_changed_index, calc_timer_diff_to_dsp_us(), hrt_absolute_time(), MUORB_KRAIT_FASTRPC_HEAP_ID, MUORB_KRAIT_FASTRPC_MEM_FLAGS, px4muorb_get_absolute_time(), px4muorb_orb_initialize(), and px4muorb_set_absolute_time_offset().
Referenced by uORB::KraitFastRpcChannel::KraitFastRpcChannel().
IsSubscriberPresent()
int32_t px4muorb::KraitRpcWrapper::IsSubscriberPresent (const char * topic, int32_t * status)
Definition at line 297 of file px4muorb_KraitRpcWrapper.cpp.
References _Initialized, and px4muorb_is_subscriber_present().
Referenced by uORB::KraitFastRpcChannel::send_message().
ReceiveBulkData()
int32_t px4muorb::KraitRpcWrapper::ReceiveBulkData (uint8_t ** bulk_data, int32_t * length_in_bytes, int32_t * topic_count)
Definition at line 335 of file px4muorb_KraitRpcWrapper.cpp.
References _BulkTransferBuffer, _Initialized, _MAX_BULK_TRANSFER_BUFFER_SIZE, and px4muorb_receive_bulk_data().
Referenced by uORB::KraitFastRpcChannel::fastrpc_recv_thread().
ReceiveData()
int32_t px4muorb::KraitRpcWrapper::ReceiveData (int32_t * msg_type, char ** topic, int32_t * length_in_bytes, uint8_t ** data)
Definition at line 310 of file px4muorb_KraitRpcWrapper.cpp.
References _DataBuffer, _Initialized, _MAX_DATA_BUFFER_SIZE, _MAX_TOPIC_NAME_BUFFER, _TopicNameBuffer, and px4muorb_receive_msg().
RemoveSubscriber()
int32_t px4muorb::KraitRpcWrapper::RemoveSubscriber (const char * topic)
Definition at line 292 of file px4muorb_KraitRpcWrapper.cpp.
References _Initialized, and px4muorb_remove_subscriber().
Referenced by uORB::KraitFastRpcChannel::remove_subscription().
SendData()
int32_t px4muorb::KraitRpcWrapper::SendData (const char * topic, int32_t length_in_bytes, const uint8_t * data)
Definition at line 303 of file px4muorb_KraitRpcWrapper.cpp.
References _Initialized, and px4muorb_send_topic_data().
Referenced by uORB::KraitFastRpcChannel::send_message().
Terminate()
bool px4muorb::KraitRpcWrapper::Terminate ()
Terminate to clean up the resources.
This should be called at program exit
Definition at line 251 of file px4muorb_KraitRpcWrapper.cpp.
References _BulkTransferBuffer, _DataBuffer, _Initialized, _TopicNameBuffer, and adsp_changed_index.
TopicAdvertised()
int32_t px4muorb::KraitRpcWrapper::TopicAdvertised (const char * topic)
Muorb related functions to pub/sub of orb topic from krait to adsp.
Definition at line 277 of file px4muorb_KraitRpcWrapper.cpp.
References _Initialized, and px4muorb_topic_advertised().
Referenced by uORB::KraitFastRpcChannel::topic_advertised().
TopicUnadvertised()
int32_t px4muorb::KraitRpcWrapper::TopicUnadvertised (const char * topic)
Definition at line 282 of file px4muorb_KraitRpcWrapper.cpp.
References _Initialized, and px4muorb_topic_unadvertised().
Referenced by uORB::KraitFastRpcChannel::topic_unadvertised().
UnblockReceiveData()
int32_t px4muorb::KraitRpcWrapper::UnblockReceiveData ()
Definition at line 359 of file px4muorb_KraitRpcWrapper.cpp.
References _Initialized, and px4muorb_unblock_recieve_msg().
Referenced by uORB::KraitFastRpcChannel::Stop().
The documentation for this class was generated from the following files:
src/modules/muorb/krait/px4muorb_KraitRpcWrapper.hpp
src/modules/muorb/krait/px4muorb_KraitRpcWrapper.cpp