PX4 Firmware: ORBSet Class Reference
ORBSet Class Reference
#include <ORBSet.hpp>
Classes
struct Node
Public Member Functions
ORBSet ()
~ORBSet ()
void insert (const char *node_name)
bool find (const char *node_name)
bool erase (const char *node_name)
Private Member Functions
void unlinkNext (Node *a)
Private Attributes
Node * _top
Node * _end
Detailed Description
Definition at line 36 of file ORBSet.hpp.
Constructor & Destructor Documentation
ORBSet()
ORBSet::ORBSet () inline
Definition at line 44 of file ORBSet.hpp.
~ORBSet()
ORBSet::~ORBSet () inline
Definition at line 48 of file ORBSet.hpp.
References _top, ORBSet::Node::next, ORBSet::Node::node_name, and unlinkNext().
Member Function Documentation
erase()
bool ORBSet::erase (const char * node_name) inline
Definition at line 99 of file ORBSet.hpp.
References _end, _top, ORBSet::Node::next, ORBSet::Node::node_name, and unlinkNext().
find()
bool ORBSet::find (const char * node_name) inline
Definition at line 84 of file ORBSet.hpp.
References _top, ORBSet::Node::next, and ORBSet::Node::node_name.
insert()
void ORBSet::insert (const char * node_name) inline
Definition at line 60 of file ORBSet.hpp.
References _end, _top, ORBSet::Node::next, and ORBSet::Node::node_name.
unlinkNext()
void ORBSet::unlinkNext (Node * a) inline private
Definition at line 128 of file ORBSet.hpp.
References _end, ORBSet::Node::next, and ORBSet::Node::node_name.
Referenced by erase(), and ~ORBSet().
Member Data Documentation
_end
Node* ORBSet::_end private
Definition at line 144 of file ORBSet.hpp.
Referenced by erase(), insert(), and unlinkNext().
_top
Node* ORBSet::_top private
Definition at line 143 of file ORBSet.hpp.
Referenced by erase(), find(), insert(), and ~ORBSet().
The documentation for this class was generated from the following file:
src/modules/uORB/ORBSet.hpp