PX4 Firmware: src/modules/commander/accelerometer_calibration.h File Reference
accelerometer_calibration.h File Reference
Definition of accelerometer calibration.
#include <stdint.h>
#include <uORB/uORB.h>
Functions
int do_accel_calibration (orb_advert_t *mavlink_log_pub)
int do_level_calibration (orb_advert_t *mavlink_log_pub)
Detailed Description
Definition of accelerometer calibration.
Author
Anton Babushkin anton.nosp@m..bab.nosp@m.ushki.nosp@m.n@me.nosp@m..com
Definition in file accelerometer_calibration.h.
Function Documentation
int do_accel_calibration (orb_advert_t * mavlink_log_pub)
< sensor thermal corrections
Definition at line 172 of file accelerometer_calibration.cpp.
References ACCEL_BASE_DEVICE_PATH, sensor_correction_s::accel_mapping, ACCELIOCSSCALE, CAL_ERROR_APPLY_CAL_MSG, CAL_ERROR_RESET_CAL_MSG, CAL_ERROR_SENSOR_MSG, CAL_ERROR_SET_PARAMS_MSG, CAL_QGC_DONE_MSG, CAL_QGC_FAILED_MSG, CAL_QGC_STARTED_MSG, calibrate_return_cancelled, calibrate_return_ok, calibration_log_critical, calibration_log_info, device_id, device_id_primary, do_accel_calibration_measurements(), fd, get_rot_matrix(), max_accel_sens, orb_copy(), ORB_ID, orb_subscribe(), orb_unsubscribe(), param_find(), param_get(), param_notify_changes(), param_set_no_notification(), px4_close(), PX4_ERR, PX4_ERROR, PX4_INFO, px4_ioctl(), PX4_OK, px4_open(), sensor_name, matrix::Matrix< Type, M, N >::transpose(), usleep(), accel_calibration_s::x_offset, accel_calibration_s::x_scale, accel_calibration_s::y_offset, accel_calibration_s::y_scale, accel_calibration_s::z_offset, and accel_calibration_s::z_scale.
Referenced by commander_low_prio_loop(), and commander_main().
int do_level_calibration (orb_advert_t * mavlink_log_pub)
Definition at line 740 of file accelerometer_calibration.cpp.
References CAL_QGC_DONE_MSG, CAL_QGC_FAILED_MSG, CAL_QGC_PROGRESS_MSG, CAL_QGC_STARTED_MSG, calibration_log_critical, calibration_log_info, counter, f(), hrt_absolute_time(), hrt_abstime, hrt_elapsed_time(), orb_copy(), ORB_ID, orb_subscribe(), param_find(), param_get(), param_notify_changes(), param_set_no_notification(), matrix::Euler< Type >::phi(), px4_poll(), vehicle_attitude_s::q, start(), and matrix::Euler< Type >::theta().
Referenced by commander_low_prio_loop(), and commander_main().