PX4 Firmware: src/drivers/stm32/drv_pwm_trigger.c File Reference
drv_pwm_trigger.c File Reference
#include <px4_config.h>
#include <nuttx/arch.h>
#include <nuttx/irq.h>
#include <sys/types.h>
#include <stdbool.h>
#include <assert.h>
#include <debug.h>
#include <time.h>
#include <queue.h>
#include <errno.h>
#include <string.h>
#include <stdio.h>
#include <arch/board/board.h>
#include <drivers/drv_pwm_trigger.h>
#include "drv_io_timer.h"
#include "drv_pwm_trigger.h"
#include <stm32_tim.h>
Functions
int up_pwm_trigger_set (unsigned channel, uint16_t value)
Set the current output value for a channel.
int up_pwm_trigger_init (uint32_t channel_mask)
Intialise the PWM servo outputs using the specified configuration.
void up_pwm_trigger_deinit ()
De-initialise the PWM trigger outputs.
void up_pwm_trigger_arm (bool armed)
Arm or disarm trigger outputs.
Function Documentation
void up_pwm_trigger_arm (bool armed)
Arm or disarm trigger outputs.
Bug:
This function should, but does not, guarantee that any pulse currently in progress is cleanly completed.
Parameters
armed If true, outputs are armed; if false they are disarmed.
Definition at line 107 of file drv_pwm_trigger.c.
References IO_TIMER_ALL_MODES_CHANNELS, io_timer_set_enable(), and IOTimerChanMode_Trigger.
void up_pwm_trigger_deinit (void)
De-initialise the PWM trigger outputs.
Definition at line 89 of file drv_pwm_trigger.c.
References io_timer_channel_init(), io_timer_get_mode_channels(), IOTimerChanMode_NotUsed, IOTimerChanMode_Trigger, MAX_TIMER_IO_CHANNELS, and up_pwm_trigger_arm().
int up_pwm_trigger_init (uint32_t channel_mask)
Intialise the PWM servo outputs using the specified configuration.
Parameters
channel_mask Bitmask of channels (LSB = channel 0) to enable. This allows some of the channels to remain configured as GPIOs or as another function.
Returns
OK on success.
Definition at line 67 of file drv_pwm_trigger.c.
References io_timer_channel_init(), io_timer_free_channel(), io_timer_is_channel_free(), IOTimerChanMode_Trigger, MAX_TIMER_IO_CHANNELS, OK, and up_pwm_trigger_arm().
int up_pwm_trigger_set (unsigned channel, uint16_t value)
Set the current output value for a channel.
Parameters
channel The channel to set.
value The output pulse width in microseconds.
Definition at line 62 of file drv_pwm_trigger.c.
References io_timer_set_ccr().