PX4 Firmware: MavlinkStreamPing Class Reference
MavlinkStreamPing Class Reference
Public Member Functions
const char * get_name () const
uint16_t get_id ()
unsigned get_size ()
Get maximal total messages size on update.
bool const_rate ()
Public Member Functions inherited from MavlinkStream
MavlinkStream (Mavlink *mavlink)
virtual ~MavlinkStream ()=default
MavlinkStream (const MavlinkStream &)=delete
MavlinkStream & operator= (const MavlinkStream &)=delete
MavlinkStream (MavlinkStream &&)=delete
MavlinkStream & operator= (MavlinkStream &&)=delete
void set_interval (const int interval)
Get the interval.
int get_interval ()
Get the interval.
int update (const hrt_abstime &t)
Update subscriptions and send message if necessary.
virtual unsigned get_size_avg ()
Get the average message size.
bool first_message_sent () const
void reset_last_sent ()
Reset the time of last sent to 0.
Static Public Member Functions
static const char * get_name_static ()
static uint16_t get_id_static ()
static MavlinkStream * new_instance (Mavlink *mavlink)
Protected Member Functions
MavlinkStreamPing (Mavlink *mavlink)
bool send (const hrt_abstime t)
Protected Member Functions inherited from MavlinkStream
virtual void update_data ()
Function to collect/update data for the streams at a high rate independant of actual stream rate.
Private Member Functions
MavlinkStreamPing (MavlinkStreamPing &)=delete
MavlinkStreamPing & operator= (const MavlinkStreamPing &)=delete
Private Attributes
uint32_t _sequence
Additional Inherited Members
Public Attributes inherited from MavlinkStream
MavlinkStream * next {nullptr}
Protected Attributes inherited from MavlinkStream
Mavlink *const _mavlink
int _interval {1000000}
if set to negative value = unlimited rate
Detailed Description
Definition at line 4372 of file mavlink_messages.cpp.
Constructor & Destructor Documentation
MavlinkStreamPing::MavlinkStreamPing (MavlinkStreamPing &) private delete
MavlinkStreamPing::MavlinkStreamPing (Mavlink * mavlink) inline explicit protected
Definition at line 4418 of file mavlink_messages.cpp.
Member Function Documentation
bool MavlinkStreamPing::const_rate () inline virtual
Returns
true if steam rate shouldn't be adjusted
Reimplemented from MavlinkStream.
Definition at line 4405 of file mavlink_messages.cpp.
uint16_t MavlinkStreamPing::get_id () inline virtual
Implements MavlinkStream.
Definition at line 4390 of file mavlink_messages.cpp.
References MavlinkStreamHeartbeat::get_id_static().
static uint16_t MavlinkStreamPing::get_id_static () inline static
Definition at line 4385 of file mavlink_messages.cpp.
const char* MavlinkStreamPing::get_name () const inline virtual
Implements MavlinkStream.
Definition at line 4375 of file mavlink_messages.cpp.
References get_name_static().
static const char* MavlinkStreamPing::get_name_static () inline static
Definition at line 4380 of file mavlink_messages.cpp.
Referenced by get_name().
unsigned MavlinkStreamPing::get_size () inline virtual
Get maximal total messages size on update.
Implements MavlinkStream.
Definition at line 4400 of file mavlink_messages.cpp.
static MavlinkStream* MavlinkStreamPing::new_instance (Mavlink * mavlink) inline static
Definition at line 4395 of file mavlink_messages.cpp.
MavlinkStreamPing& MavlinkStreamPing::operator= (const MavlinkStreamPing &) private delete
bool MavlinkStreamPing::send (const hrt_abstime t) inline protected virtual
Implements MavlinkStream.
Definition at line 4422 of file mavlink_messages.cpp.
References MavlinkStream::_mavlink, Mavlink::get_channel(), hrt_absolute_time(), and msg.
Member Data Documentation
uint32_t MavlinkStreamPing::_sequence private
Definition at line 4411 of file mavlink_messages.cpp.
The documentation for this class was generated from the following file:
src/modules/mavlink/mavlink_messages.cpp