PX4 Firmware: TerrainEstimator Class Reference
TerrainEstimator Class Reference
#include <terrain_estimator.h>
Public Member Functions
TerrainEstimator ()
~TerrainEstimator ()
bool is_valid ()
float get_distance_to_ground ()
float get_velocity ()
void predict (float dt, const struct vehicle_attitude_s *attitude, const struct sensor_combined_s *sensor, const struct distance_sensor_s *distance)
void measurement_update (uint64_t time_ref, const struct vehicle_gps_position_s *gps, const struct distance_sensor_s *distance, const struct vehicle_attitude_s *attitude)
Private Types
enum { n_x = 3 }
Private Member Functions
bool is_distance_valid (float distance)
Private Attributes
float _distance_last
bool _terrain_valid
matrix::Vector< float, n_x > _x
float _u_z
matrix::Matrix< float, 3, 3 > _P
uint64_t _time_last_distance
uint64_t _time_last_gps
Detailed Description
Definition at line 59 of file terrain_estimator.h.
Member Enumeration Documentation
anonymous enum private
Enumerator
n_x
Definition at line 76 of file terrain_estimator.h.
Constructor & Destructor Documentation
TerrainEstimator::TerrainEstimator ()
Definition at line 44 of file terrain_estimator.cpp.
References matrix::Matrix< Type, M, N >::_data, _P, _u_z, _x, and matrix::Matrix< Type, M, N >::setIdentity().
TerrainEstimator::~TerrainEstimator () inline
Definition at line 63 of file terrain_estimator.h.
Member Function Documentation
float TerrainEstimator::get_distance_to_ground () inline
Definition at line 66 of file terrain_estimator.h.
Referenced by position_estimator_inav_thread_main().
float TerrainEstimator::get_velocity () inline
Definition at line 67 of file terrain_estimator.h.
References attitude, dt, and gps.
bool TerrainEstimator::is_distance_valid (float distance) private
Definition at line 55 of file terrain_estimator.cpp.
References f().
Referenced by measurement_update().
bool TerrainEstimator::is_valid () inline
Definition at line 65 of file terrain_estimator.h.
Referenced by position_estimator_inav_thread_main().
void TerrainEstimator::measurement_update (uint64_t time_ref, const struct vehicle_gps_position_s * gps, const struct distance_sensor_s * distance, const struct vehicle_attitude_s * attitude)
Definition at line 99 of file terrain_estimator.cpp.
References matrix::Matrix< Type, M, N >::_data, _distance_last, _P, _terrain_valid, _time_last_distance, _time_last_gps, _x, distance_sensor_s::current_distance, DISTANCE_TIMEOUT, vehicle_gps_position_s::fix_type, is_distance_valid(), n_x, matrix::Euler< Type >::phi(), vehicle_attitude_s::q, matrix::Matrix< Type, M, N >::setZero(), matrix::Euler< Type >::theta(), vehicle_gps_position_s::timestamp, distance_sensor_s::timestamp, matrix::Matrix< Type, M, N >::transpose(), and vehicle_gps_position_s::vel_d_m_s.
Referenced by position_estimator_inav_thread_main().
void TerrainEstimator::predict (float dt, const struct vehicle_attitude_s * attitude, const struct sensor_combined_s * sensor, const struct distance_sensor_s * distance)
Definition at line 60 of file terrain_estimator.cpp.
References _P, _u_z, _x, sensor_combined_s::accelerometer_m_s2, CONSTANTS_ONE_G, dt, vehicle_attitude_s::q, matrix::Matrix< Type, M, N >::setZero(), and matrix::Matrix< Type, M, N >::transpose().
Referenced by position_estimator_inav_thread_main().
Member Data Documentation
float TerrainEstimator::_distance_last private
Definition at line 78 of file terrain_estimator.h.
Referenced by measurement_update().
matrix::Matrix<float, 3, 3> TerrainEstimator::_P private
Definition at line 84 of file terrain_estimator.h.
Referenced by measurement_update(), predict(), and TerrainEstimator().
bool TerrainEstimator::_terrain_valid private
Definition at line 79 of file terrain_estimator.h.
Referenced by measurement_update().
uint64_t TerrainEstimator::_time_last_distance private
Definition at line 87 of file terrain_estimator.h.
Referenced by measurement_update().
uint64_t TerrainEstimator::_time_last_gps private
Definition at line 88 of file terrain_estimator.h.
Referenced by measurement_update().
float TerrainEstimator::_u_z private
Definition at line 83 of file terrain_estimator.h.
Referenced by predict(), and TerrainEstimator().
matrix::Vector<float, n_x> TerrainEstimator::_x private
Definition at line 82 of file terrain_estimator.h.
Referenced by measurement_update(), predict(), and TerrainEstimator().
The documentation for this class was generated from the following files:
src/lib/terrain_estimation/terrain_estimator.h
src/lib/terrain_estimation/terrain_estimator.cpp