PX4 Firmware: uORB::FastRpcChannel::Mutex Class Reference
uORB::FastRpcChannel::Mutex Class Reference
Public Member Functions
Mutex ()
~Mutex ()
void lock ()
void unlock ()
Private Member Functions
Mutex (const Mutex &)
Mutex & operator= (const Mutex &)
Private Attributes
sem_t _Sem
Detailed Description
Definition at line 223 of file uORBFastRpcChannel.hpp.
Constructor & Destructor Documentation
Mutex() [1/2]
uORB::FastRpcChannel::Mutex::Mutex () inline
Definition at line 226 of file uORBFastRpcChannel.hpp.
~Mutex()
uORB::FastRpcChannel::Mutex::~Mutex () inline
Definition at line 230 of file uORBFastRpcChannel.hpp.
Mutex() [2/2]
uORB::FastRpcChannel::Mutex::Mutex (const Mutex &) private
Member Function Documentation
lock()
void uORB::FastRpcChannel::Mutex::lock () inline
Definition at line 234 of file uORBFastRpcChannel.hpp.
Referenced by uORB::FastRpcChannel::control_msg_queue_add(), uORB::FastRpcChannel::get_bulk_data(), uORB::FastRpcChannel::get_data(), and uORB::FastRpcChannel::send_message().
operator=()
Mutex& uORB::FastRpcChannel::Mutex::operator= (const Mutex &) private
unlock()
void uORB::FastRpcChannel::Mutex::unlock () inline
Definition at line 238 of file uORBFastRpcChannel.hpp.
Referenced by uORB::FastRpcChannel::control_msg_queue_add(), uORB::FastRpcChannel::get_bulk_data(), uORB::FastRpcChannel::get_data(), and uORB::FastRpcChannel::send_message().
Member Data Documentation
_Sem
sem_t uORB::FastRpcChannel::Mutex::_Sem private
Definition at line 243 of file uORBFastRpcChannel.hpp.
The documentation for this class was generated from the following file:
src/modules/muorb/adsp/uORBFastRpcChannel.hpp