PX4 Firmware: IRLOCK Class Reference
IRLOCK Class Reference
Public Member Functions
IRLOCK (int bus=IRLOCK_I2C_BUS, int address=IRLOCK_I2C_ADDRESS)
constructor
virtual ~IRLOCK ()
destructor
virtual int init ()
initialise driver to communicate with sensor
virtual int probe ()
probe the device is on the I2C bus
virtual int info ()
display driver info
virtual int test ()
test driver
virtual ssize_t read (struct file *filp, char *buffer, size_t buflen)
Private Member Functions
void start ()
start periodic reads from sensor
void stop ()
stop periodic reads from sensor
void cycle ()
read from device and schedule next read
int read_device ()
low level communication with sensor
bool sync_device ()
sync device to ensure reading starts at new frame
int read_device_word (uint16_t *word)
read a word (two bytes) from sensor
int read_device_block (struct irlock_target_s *block)
read a single block (a full frame) from sensor
Static Private Member Functions
static void cycle_trampoline (void *arg)
static function that is called by worker queue, arg will be pointer to instance of this class
Private Attributes
ringbuffer::RingBuffer * _reports
internal variables
bool _sensor_ok
work_s _work
uint32_t _read_failures
int _orb_class_instance
orb_advert_t _irlock_report_topic
Detailed Description
Definition at line 92 of file irlock.cpp.
Constructor & Destructor Documentation
IRLOCK::IRLOCK (int bus = IRLOCK_I2C_BUS, int address = IRLOCK_I2C_ADDRESS)
constructor
Definition at line 146 of file irlock.cpp.
Referenced by irlock_main().
IRLOCK::~IRLOCK () virtual
destructor
clear reports queue
Definition at line 158 of file irlock.cpp.
References _reports, and stop().
Member Function Documentation
void IRLOCK::cycle () private
read from device and schedule next read
ignoring failure, if we do, we will be back again right away...
schedule the next cycle
Definition at line 294 of file irlock.cpp.
References cycle_trampoline(), IRLOCK_CONVERSION_INTERVAL_US, and read_device().
Referenced by cycle_trampoline().
void IRLOCK::cycle_trampoline (void * arg) static private
static function that is called by worker queue, arg will be pointer to instance of this class
check global irlock reference and cycle
Definition at line 284 of file irlock.cpp.
References cycle().
Referenced by cycle(), and start().
int IRLOCK::info () virtual
display driver info
display reports in queue
Definition at line 210 of file irlock.cpp.
References _read_failures, _reports, _sensor_ok, errx, OK, and warnx.
int IRLOCK::init () virtual
initialise driver to communicate with sensor
initialise I2C bus
allocate buffer storing values read from sensor
start work queue
Definition at line 169 of file irlock.cpp.
References _reports, _sensor_ok, lis3mdl::init(), OK, and start().
int IRLOCK::probe () virtual
probe the device is on the I2C bus
Definition at line 193 of file irlock.cpp.
References OK.
ssize_t IRLOCK::read (struct file * filp, char * buffer, size_t buflen) virtual
try to read
Definition at line 303 of file irlock.cpp.
References _reports.
int IRLOCK::read_device () private
low level communication with sensor
read all available frames from sensor
if we sync, then we are starting a new frame, else fail
Definition at line 351 of file irlock.cpp.
References _irlock_report_topic, _orb_class_instance, _reports, DEVICE_LOG, hrt_absolute_time(), IRLOCK_OBJECTS_MAX, irlock_s::num_targets, OK, orb_advertise_multi(), ORB_ID, ORB_PRIO_LOW, orb_publish(), irlock_report_s::pos_x, irlock_target_s::pos_x, irlock_target_s::pos_y, irlock_report_s::pos_y, read_device_block(), irlock_target_s::signature, irlock_report_s::signature, irlock_report_s::size_x, irlock_target_s::size_x, irlock_target_s::size_y, irlock_report_s::size_y, sync_device(), irlock_s::targets, irlock_report_s::timestamp, and irlock_s::timestamp.
Referenced by cycle().
int IRLOCK::read_device_block (struct irlock_target_s * block) private
read a single block (a full frame) from sensor
crc check
convert to angles
Definition at line 413 of file irlock.cpp.
References _read_failures, IRLOCK_CENTER_X, IRLOCK_CENTER_Y, IRLOCK_TAN_ANG_PER_PIXEL_X, IRLOCK_TAN_ANG_PER_PIXEL_Y, irlock_target_s::pos_x, irlock_target_s::pos_y, irlock_target_s::signature, irlock_report_s::signature, irlock_target_s::size_x, irlock_target_s::size_y, and status.
Referenced by read_device().
int IRLOCK::read_device_word (uint16_t * word) private
read a word (two bytes) from sensor
Definition at line 401 of file irlock.cpp.
References status.
Referenced by sync_device().
void IRLOCK::start () private
start periodic reads from sensor
flush ring and reset state machine
start work queue cycle
Definition at line 269 of file irlock.cpp.
References _reports, and cycle_trampoline().
Referenced by init().
void IRLOCK::stop () private
stop periodic reads from sensor
Definition at line 279 of file irlock.cpp.
Referenced by ~IRLOCK().
bool IRLOCK::sync_device () private
sync device to ensure reading starts at new frame
Definition at line 327 of file irlock.cpp.
References IRLOCK_ADJUST, IRLOCK_RESYNC, IRLOCK_SYNC, OK, and read_device_word().
Referenced by read_device().
int IRLOCK::test () virtual
test driver
exit immediately if driver not running
exit immediately if sensor is not healty
instructions to user
read from sensor for 10 seconds
output all objects found
sleep for 0.05 seconds
Definition at line 229 of file irlock.cpp.
References _reports, _sensor_ok, errx, hrt_absolute_time(), irlock_s::num_targets, OK, irlock_target_s::pos_x, irlock_target_s::pos_y, irlock_target_s::signature, irlock_target_s::size_x, irlock_target_s::size_y, irlock_s::targets, usleep(), and warnx.
Member Data Documentation
orb_advert_t IRLOCK::_irlock_report_topic private
Definition at line 132 of file irlock.cpp.
Referenced by read_device().
int IRLOCK::_orb_class_instance private
Definition at line 131 of file irlock.cpp.
Referenced by read_device().
uint32_t IRLOCK::_read_failures private
Definition at line 129 of file irlock.cpp.
Referenced by info(), and read_device_block().
ringbuffer::RingBuffer* IRLOCK::_reports private
internal variables
Definition at line 126 of file irlock.cpp.
Referenced by info(), init(), read(), read_device(), start(), test(), and ~IRLOCK().
bool IRLOCK::_sensor_ok private
Definition at line 127 of file irlock.cpp.
Referenced by info(), init(), and test().
work_s IRLOCK::_work private
Definition at line 128 of file irlock.cpp.
The documentation for this class was generated from the following file:
src/drivers/irlock/irlock.cpp