PX4 Firmware: UavcanEsc Class Reference
UavcanEsc Class Reference
A UAVCAN node.
#include <uavcanesc_main.hpp>
Public Types
typedef uavcan::Node< MemPoolSize > Node
typedef uavcan_stm32::CanInitHelper< RxQueueLenPerIface > CanInitHelper
typedef uavcan::protocol::file::BeginFirmwareUpdate BeginFirmwareUpdate
Public Types inherited from device::Device
enum DeviceBusType { DeviceBusType_UNKNOWN = 0, DeviceBusType_I2C = 1, DeviceBusType_SPI = 2, DeviceBusType_UAVCAN = 3 }
Device bus types for DEVID.
Public Member Functions
UavcanEsc (uavcan::ICanDriver &can_driver, uavcan::ISystemClock &system_clock)
virtual ~UavcanEsc ()
virtual int ioctl (file *filp, int cmd, unsigned long arg)
Node & get_node ()
int teardown ()
void print_info ()
Public Member Functions inherited from device::CDev
CDev (const char *name, const char *devname)
Constructor.
virtual ~CDev ()
virtual int init ()
Initialise the driver and make it ready for use.
virtual int open (file_t *filep)
Handle an open of the device.
virtual int close (file_t *filep)
Handle a close of the device.
virtual ssize_t read (file_t *filep, char *buffer, size_t buflen)
Perform a read from the device.
virtual ssize_t write (file_t *filep, const char *buffer, size_t buflen)
Perform a write to the device.
virtual off_t seek (file_t *filep, off_t offset, int whence)
Perform a logical seek operation on the device.
virtual int ioctl (file_t *filep, int cmd, unsigned long arg)
Perform an ioctl operation on the device.
virtual int poll (file_t *filep, px4_pollfd_struct_t *fds, bool setup)
Perform a poll setup/teardown operation.
Public Member Functions inherited from device::Device
virtual ~Device ()=default
Destructor.
virtual int read (unsigned address, void *data, unsigned count)
Read directly from the device.
virtual int write (unsigned address, void *data, unsigned count)
Write directly to the device.
virtual int ioctl (unsigned operation, unsigned &arg)
Perform a device-specific operation.
uint8_t get_device_bus ()
Return the bus ID the device is connected to.
DeviceBusType get_device_bus_type ()
Return the bus type the device is connected to.
uint8_t get_device_address ()
Return the bus address of the device.
void set_device_address (int address)
void set_device_type (uint8_t devtype)
Set the device type.
virtual bool external ()
Static Public Member Functions
static int start (uavcan::NodeID node_id, uint32_t bitrate)
static UavcanEsc * instance ()
Public Attributes
int32_t active_bitrate
uavcan::TimerEventForwarder< void(*)(const uavcan::TimerEvent &)> _reset_timer
Private Types
typedef uavcan::MethodBinder< UavcanEsc *, void(UavcanEsc::*)(const uavcan::ReceivedDataStructure< UavcanEsc::BeginFirmwareUpdate::Request > &, uavcan::ServiceResponseDataStructure< UavcanEsc::BeginFirmwareUpdate::Response > &)> BeginFirmwareUpdateCallBack
Private Member Functions
void fill_node_info ()
int init (uavcan::NodeID node_id)
void node_spin_once ()
int run ()
int add_poll_fd (int fd)
add a fd to poll list, returning index into _poll_fds[]
void cb_beginfirmware_update (const uavcan::ReceivedDataStructure< UavcanEsc::BeginFirmwareUpdate::Request > &req, uavcan::ServiceResponseDataStructure< UavcanEsc::BeginFirmwareUpdate::Response > &rsp)
Private Attributes
int _task = -1
handle to the OS task
bool _task_should_exit = false
flag to indicate to tear down the CAN driver
Node _node
library instance
pthread_mutex_t _node_mutex
pollfd _poll_fds [UAVCAN_NUM_POLL_FDS] = {}
unsigned _poll_fds_num = 0
uavcan::ServiceServer< BeginFirmwareUpdate, BeginFirmwareUpdateCallBack > _fw_update_listner
Static Private Attributes
static constexpr unsigned MemPoolSize = 2048
static constexpr unsigned RxQueueLenPerIface = 5
static constexpr unsigned StackSize = 4096
static UavcanEsc * _instance
singleton pointer
Additional Inherited Members
Protected Member Functions inherited from device::CDev
virtual pollevent_t poll_state (file_t *filep)
Check the current state of the device for poll events from the perspective of the file.
virtual void poll_notify (pollevent_t events)
Report new poll events.
virtual void poll_notify_one (px4_pollfd_struct_t *fds, pollevent_t events)
Internal implementation of poll_notify.
virtual int open_first (file_t *filep)
Notification of the first open.
virtual int close_last (file_t *filep)
Notification of the last close.
virtual int register_class_devname (const char *class_devname)
Register a class device name, automatically adding device class instance suffix if need be.
virtual int unregister_class_devname (const char *class_devname, unsigned class_instance)
Register a class device name, automatically adding device class instance suffix if need be.
const char * get_devname ()
Get the device name.
void lock ()
Take the driver lock.
void unlock ()
Release the driver lock.
Protected Member Functions inherited from device::Device
Device (const char *name)
Device (DeviceBusType bus_type, uint8_t bus, uint8_t address, uint8_t devtype=0)
Device (const Device &)=delete
Device & operator= (const Device &)=delete
Device (Device &&)=delete
Device & operator= (Device &&)=delete
Protected Attributes inherited from device::CDev
px4_sem_t _lock
lock to protect access to all class members (also for derived classes)
bool _pub_blocked {false}
true if publishing should be blocked
Protected Attributes inherited from device::Device
union DeviceId _device_id
device identifier information
const char * _name
driver name
bool _debug_enabled {false}
if true, debug messages are printed
Static Protected Attributes inherited from device::CDev
static const px4_file_operations_t fops = {}
Pointer to the default cdev file operations table; useful for registering clone devices etc.
Detailed Description
A UAVCAN node.
Definition at line 57 of file uavcanesc_main.hpp.
Member Typedef Documentation
typedef uavcan::protocol::file::BeginFirmwareUpdate UavcanEsc::BeginFirmwareUpdate
Definition at line 92 of file uavcanesc_main.hpp.
typedef uavcan::MethodBinder<UavcanEsc *, void (UavcanEsc::*)(const uavcan::ReceivedDataStructure<UavcanEsc::BeginFirmwareUpdate::Request> &, uavcan::ServiceResponseDataStructure<UavcanEsc::BeginFirmwareUpdate::Response> &)> UavcanEsc::BeginFirmwareUpdateCallBack private
Definition at line 137 of file uavcanesc_main.hpp.
typedef uavcan_stm32::CanInitHelper<RxQueueLenPerIface> UavcanEsc::CanInitHelper
Definition at line 91 of file uavcanesc_main.hpp.
typedef uavcan::Node<MemPoolSize> UavcanEsc::Node
Definition at line 90 of file uavcanesc_main.hpp.
Constructor & Destructor Documentation
UavcanEsc::UavcanEsc (uavcan::ICanDriver & can_driver, uavcan::ISystemClock & system_clock)
Definition at line 88 of file uavcanesc_main.cpp.
References _node_mutex, and pthread_mutex_init().
Referenced by start().
UavcanEsc::~UavcanEsc () virtual
Definition at line 104 of file uavcanesc_main.cpp.
References _instance, _task, _task_should_exit, and usleep().
Member Function Documentation
int UavcanEsc::add_poll_fd (int fd) private
add a fd to poll list, returning index into _poll_fds[]
Definition at line 313 of file uavcanesc_main.cpp.
References _poll_fds, _poll_fds_num, errx, fd, and UAVCAN_NUM_POLL_FDS.
Referenced by run().
void UavcanEsc::cb_beginfirmware_update (const uavcan::ReceivedDataStructure< UavcanEsc::BeginFirmwareUpdate::Request > & req, uavcan::ServiceResponseDataStructure< UavcanEsc::BeginFirmwareUpdate::Response > & rsp) private
Definition at line 233 of file uavcanesc_main.cpp.
References _node, _reset_timer, active_bitrate, App, bootloader_app_shared_write(), bootloader_app_shared_t::bus_speed, cb_reboot(), bootloader_app_shared_t::node_id, and rgb_led().
Referenced by init().
void UavcanEsc::fill_node_info () private
Definition at line 195 of file uavcanesc_main.cpp.
References _node, AppDescriptor, board_get_mfguid(), app_descriptor_t::image_crc, app_descriptor_t::major_version, app_descriptor_t::minor_version, px4_firmware_version_string(), and PX4_WARN.
Referenced by init().
Node& UavcanEsc::get_node () inline
Definition at line 102 of file uavcanesc_main.hpp.
References _node, print_info(), and teardown().
Referenced by run().
int UavcanEsc::init (uavcan::NodeID node_id) private
Definition at line 258 of file uavcanesc_main.cpp.
References _fw_update_listner, _node, cb_beginfirmware_update(), fill_node_info(), lis3mdl::init(), and OK.
Referenced by start().
static UavcanEsc* UavcanEsc::instance () inline static
Definition at line 108 of file uavcanesc_main.hpp.
References _instance.
Referenced by uavcanesc_main().
int UavcanEsc::ioctl (file * filp, int cmd, unsigned long arg) virtual
Definition at line 402 of file uavcanesc_main.cpp.
References device::CDev::lock(), OK, and device::CDev::unlock().
void UavcanEsc::node_spin_once () private
Definition at line 300 of file uavcanesc_main.cpp.
References _node, and PX4_WARN.
Referenced by run().
void UavcanEsc::print_info (void)
Definition at line 427 of file uavcanesc_main.cpp.
References _instance, _node_mutex, pthread_mutex_lock(), pthread_mutex_unlock(), and PX4_WARN.
Referenced by get_node(), and uavcanesc_main().
int UavcanEsc::run () private
Definition at line 329 of file uavcanesc_main.cpp.
References _node, _node_mutex, _poll_fds, _poll_fds_num, _task_should_exit, add_poll_fd(), get_node(), init_indication_controller(), node_spin_once(), device::CDev::open(), device::CDev::poll(), pthread_mutex_lock(), pthread_mutex_unlock(), PX4_ERR, PX4_WARN, restart_request_handler, and teardown().
Referenced by start().
int UavcanEsc::start (uavcan::NodeID node_id, uint32_t bitrate) static
Definition at line 129 of file uavcanesc_main.cpp.
References _instance, _task, active_bitrate, init(), instance, OK, px4_task_spawn_cmd(), PX4_WARN, run(), SCHED_DEFAULT, SCHED_PRIORITY_ACTUATOR_OUTPUTS, StackSize, and UavcanEsc().
Referenced by uavcannode_start().
int UavcanEsc::teardown ()
Definition at line 394 of file uavcanesc_main.cpp.
Referenced by get_node(), and run().
Member Data Documentation
uavcan::ServiceServer<BeginFirmwareUpdate, BeginFirmwareUpdateCallBack> UavcanEsc::_fw_update_listner private
Definition at line 139 of file uavcanesc_main.hpp.
Referenced by init().
UavcanEsc * UavcanEsc::_instance static private
singleton pointer
Definition at line 127 of file uavcanesc_main.hpp.
Referenced by instance(), print_info(), start(), and ~UavcanEsc().
Node UavcanEsc::_node private
library instance
Definition at line 128 of file uavcanesc_main.hpp.
Referenced by cb_beginfirmware_update(), fill_node_info(), get_node(), init(), node_spin_once(), and run().
pthread_mutex_t UavcanEsc::_node_mutex private
Definition at line 129 of file uavcanesc_main.hpp.
Referenced by print_info(), run(), and UavcanEsc().
pollfd UavcanEsc::_poll_fds[UAVCAN_NUM_POLL_FDS] = {} private
Definition at line 131 of file uavcanesc_main.hpp.
Referenced by add_poll_fd(), and run().
unsigned UavcanEsc::_poll_fds_num = 0 private
Definition at line 132 of file uavcanesc_main.hpp.
Referenced by add_poll_fd(), and run().
uavcan::TimerEventForwarder<void (*)(const uavcan::TimerEvent &)> UavcanEsc::_reset_timer
Definition at line 147 of file uavcanesc_main.hpp.
Referenced by cb_beginfirmware_update().
int UavcanEsc::_task = -1 private
handle to the OS task
Definition at line 124 of file uavcanesc_main.hpp.
Referenced by start(), and ~UavcanEsc().
bool UavcanEsc::_task_should_exit = false private
flag to indicate to tear down the CAN driver
Definition at line 125 of file uavcanesc_main.hpp.
Referenced by run(), and ~UavcanEsc().
int32_t UavcanEsc::active_bitrate
Definition at line 113 of file uavcanesc_main.hpp.
Referenced by cb_beginfirmware_update(), and start().
constexpr unsigned UavcanEsc::MemPoolSize = 2048 static private
Definition at line 68 of file uavcanesc_main.hpp.
constexpr unsigned UavcanEsc::RxQueueLenPerIface = 5 static private
Definition at line 81 of file uavcanesc_main.hpp.
constexpr unsigned UavcanEsc::StackSize = 4096 static private
Definition at line 87 of file uavcanesc_main.hpp.
Referenced by start().
The documentation for this class was generated from the following files:
src/modules/uavcanesc/uavcanesc_main.hpp
src/modules/uavcanesc/uavcanesc_main.cpp