PX4 Firmware: src/modules/commander/mag_calibration.h File Reference
mag_calibration.h File Reference
Barometer calibration routine.
#include <stdint.h>
#include <uORB/uORB.h>
Functions
int do_mag_calibration (orb_advert_t *mavlink_log_pub)
Detailed Description
Barometer calibration routine.
Magnetometer calibration routine.
Definition in file mag_calibration.h.
Function Documentation
int do_mag_calibration (orb_advert_t * mavlink_log_pub)
Definition at line 99 of file mag_calibration.cpp.
References _last_mag_progress, CAL_ERROR_RESET_CAL_MSG, CAL_QGC_DONE_MSG, CAL_QGC_FAILED_MSG, CAL_QGC_PROGRESS_MSG, CAL_QGC_STARTED_MSG, calibrate_return_cancelled, calibrate_return_ok, calibration_log_critical, calibration_log_info, device_ids, fd, MAG_BASE_DEVICE_PATH, mag_calibrate_all(), MAGIOCCALIBRATE, MAGIOCGEXTERNAL, MAGIOCSSCALE, max_mags, param_find(), param_notify_changes(), param_set_no_notification(), px4_close(), PX4_ERR, PX4_ERROR, px4_ioctl(), PX4_OK, px4_open(), sensor_name, usleep(), mag_calibration_s::x_offset, mag_calibration_s::x_scale, mag_calibration_s::y_offset, mag_calibration_s::y_scale, mag_calibration_s::z_offset, and mag_calibration_s::z_scale.
Referenced by commander_low_prio_loop(), and commander_main().