PX4 Firmware: control::BlockParam< T > Class Template Reference
control::BlockParam< T > Class Template Reference final
#include <BlockParam.hpp>
Public Member Functions
BlockParam (Block *block, const char *name, bool parent_prefix=true)
BlockParam (Block *block, const char *name, bool parent_prefix, T &extern_val)
~BlockParam () override=default
BlockParam (const BlockParam &)=delete
BlockParam & operator= (const BlockParam &)=delete
BlockParam (BlockParam &&)=delete
BlockParam & operator= (BlockParam &&)=delete
T get () const
bool commit ()
bool commit_no_notification ()
void set (T val)
bool update () override
template<>
BlockParam (Block *block, const char *name, bool parent_prefix)
template<>
bool update ()
template<>
BlockParam (Block *block, const char *name, bool parent_prefix)
template<>
BlockParam (Block *block, const char *name, bool parent_prefix)
template<>
BlockParam (Block *block, const char *name, bool parent_prefix, int32_t &extern_val)
template<>
BlockParam (Block *block, const char *name, bool parent_prefix, float &extern_val)
template<>
bool update ()
Public Member Functions inherited from control::BlockParamBase
BlockParamBase (Block *parent, const char *name, bool parent_prefix=true)
Instantiate a block param base.
virtual ~BlockParamBase ()=default
const char * getName () const
Public Member Functions inherited from ListNode< BlockParamBase * >
ListNode ()
ListNode (const ListNode &)=delete
ListNode (ListNode &&)=delete
virtual ~ListNode ()=default
ListNode & operator= (const ListNode &)=delete
ListNode & operator= (ListNode &&)=delete
void setSibling (BlockParamBase *sibling)
const BlockParamBase * getSibling ()
Protected Attributes
T _val
Protected Attributes inherited from control::BlockParamBase
param_t _handle {PARAM_INVALID}
Protected Attributes inherited from ListNode< BlockParamBase * >
BlockParamBase * _sibling
Detailed Description
template<class T>
class control::BlockParam< T >
Definition at line 74 of file BlockParam.hpp.
Constructor & Destructor Documentation
template<class T> control::BlockParam< T >::BlockParam (Block * block, const char * name, bool parent_prefix = true)
template<class T> control::BlockParam< T >::BlockParam (Block * block, const char * name, bool parent_prefix, T & extern_val)
template<class T> control::BlockParam< T >::~BlockParam () override default
template<class T> control::BlockParam< T >::BlockParam (const BlockParam< T > &) delete
template<class T> control::BlockParam< T >::BlockParam (BlockParam< T > &&) delete
template<> control::BlockParam< bool >::BlockParam (Block * block, const char * name, bool parent_prefix)
Definition at line 88 of file BlockParam.cpp.
References control::BlockParam< T >::update().
template<> control::BlockParam< int32_t >::BlockParam (Block * block, const char * name, bool parent_prefix)
Definition at line 112 of file BlockParam.cpp.
References control::BlockParam< T >::update().
template<> control::BlockParam< float >::BlockParam (Block * block, const char * name, bool parent_prefix)
Definition at line 120 of file BlockParam.cpp.
References control::BlockParam< T >::update().
template<> control::BlockParam< int32_t & >::BlockParam (Block * block, const char * name, bool parent_prefix, int32_t & extern_val)
Definition at line 128 of file BlockParam.cpp.
References control::BlockParam< T >::update().
template<> control::BlockParam< float & >::BlockParam (Block * block, const char * name, bool parent_prefix, float & extern_val)
Definition at line 136 of file BlockParam.cpp.
References control::BlockParam< T >::update().
Member Function Documentation
template<class T> bool control::BlockParam< T >::commit () inline
Definition at line 91 of file BlockParam.hpp.
template<class T> bool control::BlockParam< T >::commit_no_notification () inline
Definition at line 94 of file BlockParam.hpp.
template<class T> T control::BlockParam< T >::get () const inline
Definition at line 88 of file BlockParam.hpp.
Referenced by control::BlockLimitSym::update(), and control::BlockLimit::update().
template<class T> BlockParam& control::BlockParam< T >::operator= (const BlockParam< T > &) delete
template<class T> BlockParam& control::BlockParam< T >::operator= (BlockParam< T > &&) delete
template<class T> void control::BlockParam< T >::set (T val) inline
Definition at line 96 of file BlockParam.hpp.
template<> bool control::BlockParam< bool >::update () virtual
Implements control::BlockParamBase.
Definition at line 96 of file BlockParam.cpp.
References control::BlockParamBase::_handle, control::BlockParam< T >::_val, param_get(), and PX4_OK.
template<class T> bool control::BlockParam< T >::update () inline override virtual
Implements control::BlockParamBase.
Definition at line 98 of file BlockParam.hpp.
Referenced by control::BlockParam< T >::BlockParam().
template<> bool control::BlockParam< bool >::update () virtual
Implements control::BlockParamBase.
Member Data Documentation
template<class T> T control::BlockParam< T >::_val protected
Definition at line 101 of file BlockParam.hpp.
Referenced by control::BlockParam< T >::update().
The documentation for this class was generated from the following file:
src/lib/controllib/block/BlockParam.hpp