PX4 Firmware: VCDevExample Class Reference
VCDevExample Class Reference
#include <vcdevtest_example.h>
Public Member Functions
VCDevExample ()
~VCDevExample ()
int main ()
Static Public Attributes
static px4::AppState appState
Private Member Functions
int do_poll (int fd, int timeout, int iterations, int delayms_after_poll)
Private Attributes
VCDevNode * _node
Detailed Description
Definition at line 46 of file vcdevtest_example.h.
Constructor & Destructor Documentation
VCDevExample::VCDevExample () inline
Definition at line 49 of file vcdevtest_example.h.
References main(), and ~VCDevExample().
VCDevExample::~VCDevExample ()
Definition at line 187 of file vcdevtest_example.cpp.
Referenced by VCDevExample().
Member Function Documentation
int VCDevExample::do_poll (int fd, int timeout, int iterations, int delayms_after_poll) private
Definition at line 216 of file vcdevtest_example.cpp.
References fd, PX4_ERR, px4_errno, PX4_INFO, px4_poll(), px4_read(), and usleep().
int VCDevExample::main ()
Definition at line 269 of file vcdevtest_example.cpp.
References fd, g_exit, px4_close(), px4_errno, PX4_F_RDONLY, PX4_INFO, px4_ioctl(), PX4_OK, px4_open(), px4_task_spawn_cmd(), SCHED_DEFAULT, SCHED_PRIORITY_MAX, test_pub_block(), TESTDEV, and writer_main().
Referenced by PX4_MAIN(), and VCDevExample().
Member Data Documentation
VCDevNode* VCDevExample::_node private
Definition at line 60 of file vcdevtest_example.h.
px4::AppState VCDevExample::appState static
Definition at line 55 of file vcdevtest_example.h.
Referenced by vcdev_test_main().
The documentation for this class was generated from the following files:
src/platforms/posix/tests/vcdev_test/vcdevtest_example.h
src/platforms/posix/tests/vcdev_test/vcdevtest_example.cpp