PX4 Firmware: BAROSIM Class Reference
BAROSIM Class Reference
Public Member Functions
BAROSIM (const char *path)
virtual ~BAROSIM ()
virtual int init () override
virtual int devIOCTL (unsigned long cmd, unsigned long arg) override
void print_info ()
Diagnostics - print some basic information about the driver.
Protected Member Functions
bool is_external ()
Get the internal / external state.
virtual void _measure () override
virtual int collect ()
Collect the result of the most recent measurement.
Protected Attributes
ringbuffer::RingBuffer * _reports
struct baro_report report
orb_advert_t _baro_topic
int _orb_class_instance
perf_counter_t _sample_perf
perf_counter_t _measure_perf
perf_counter_t _comms_errors
Detailed Description
Definition at line 82 of file baro.cpp.
Constructor & Destructor Documentation
BAROSIM::BAROSIM (const char * path)
Definition at line 132 of file baro.cpp.
References _baro_topic, _comms_errors, _measure_perf, _orb_class_instance, _sample_perf, PC_COUNT, PC_ELAPSED, and perf_alloc.
Referenced by barosim::start().
BAROSIM::~BAROSIM () virtual
Definition at line 144 of file baro.cpp.
References _comms_errors, _measure_perf, _reports, _sample_perf, perf_free(), and stop().
Member Function Documentation
void BAROSIM::_measure (void) override protected virtual
Definition at line 209 of file baro.cpp.
References collect().
int BAROSIM::collect () protected virtual
Collect the result of the most recent measurement.
Definition at line 215 of file baro.cpp.
References _baro_topic, _comms_errors, _reports, _sample_perf, Simulator::getBaroSample(), Simulator::getInstance(), hrt_absolute_time(), OK, ORB_ID, orb_publish(), perf_begin(), perf_count(), perf_end(), perf_event_count(), simulator::RawBaroData::pressure, PX4_DEBUG, PX4_ERR, PX4_WARN, report, status, and simulator::RawBaroData::temperature.
Referenced by _measure().
int BAROSIM::devIOCTL (unsigned long cmd, unsigned long arg) override virtual
Definition at line 201 of file baro.cpp.
int BAROSIM::init () override virtual
Definition at line 162 of file baro.cpp.
References _baro_topic, _orb_class_instance, _reports, baro_report, lis3mdl::init(), is_external(), OK, orb_advertise_multi(), ORB_ID, ORB_PRIO_DEFAULT, ORB_PRIO_HIGH, PX4_ERR, and start().
Referenced by barosim::start().
bool BAROSIM::is_external () inline protected
Get the internal / external state.
Returns
true if the sensor is not on the main MCU board
Definition at line 115 of file baro.cpp.
Referenced by init().
void BAROSIM::print_info (void)
Diagnostics - print some basic information about the driver.
Definition at line 268 of file baro.cpp.
References _comms_errors, _reports, _sample_perf, perf_print_counter(), PX4_INFO, and report.
Referenced by barosim::info().
Member Data Documentation
orb_advert_t BAROSIM::_baro_topic protected
Definition at line 104 of file baro.cpp.
Referenced by BAROSIM(), collect(), and init().
perf_counter_t BAROSIM::_comms_errors protected
Definition at line 109 of file baro.cpp.
Referenced by BAROSIM(), collect(), print_info(), and ~BAROSIM().
perf_counter_t BAROSIM::_measure_perf protected
Definition at line 108 of file baro.cpp.
Referenced by BAROSIM(), and ~BAROSIM().
int BAROSIM::_orb_class_instance protected
Definition at line 105 of file baro.cpp.
Referenced by BAROSIM(), and init().
ringbuffer::RingBuffer* BAROSIM::_reports protected
Definition at line 99 of file baro.cpp.
Referenced by collect(), init(), print_info(), and ~BAROSIM().
perf_counter_t BAROSIM::_sample_perf protected
Definition at line 107 of file baro.cpp.
Referenced by BAROSIM(), collect(), print_info(), and ~BAROSIM().
struct baro_report BAROSIM::report protected
Definition at line 102 of file baro.cpp.
Referenced by collect(), and print_info().
The documentation for this class was generated from the following file:
src/modules/simulator/barosim/baro.cpp