PX4 Firmware: src/drivers/barometer/bmp280/bmp280.cpp File Reference
bmp280.cpp File Reference
Driver for the BMP280 barometric pressure sensor connected via I2C TODO or SPI.
#include <px4_config.h>
#include <sys/types.h>
#include <stdint.h>
#include <stdbool.h>
#include <stdlib.h>
#include <semaphore.h>
#include <string.h>
#include <fcntl.h>
#include <poll.h>
#include <errno.h>
#include <stdio.h>
#include <math.h>
#include <unistd.h>
#include <px4_getopt.h>
#include <px4_log.h>
#include <nuttx/arch.h>
#include <nuttx/wqueue.h>
#include <nuttx/clock.h>
#include <arch/board/board.h>
#include <board_config.h>
#include "bmp280.h"
#include <drivers/device/device.h>
#include <drivers/drv_baro.h>
#include <drivers/drv_hrt.h>
#include <drivers/device/ringbuffer.h>
#include <perf/perf_counter.h>
#include <systemlib/err.h>
Classes
class BMP280
struct bmp280::bmp280_bus_option
Namespaces
bmp280
Local functions in support of the shell command.
Macros
#define NUM_BUS_OPTIONS (sizeof(bus_options)/sizeof(bus_options[0]))
Enumerations
enum BMP280_BUS {
BMP280_BUS_ALL = 0, BMP280_BUS_I2C_INTERNAL, BMP280_BUS_I2C_EXTERNAL, BMP280_BUS_SPI_INTERNAL,
BMP280_BUS_SPI_EXTERNAL
}
Functions
__EXPORT int bmp280_main (int argc, char *argv[])
bool bmp280::start_bus (struct bmp280_bus_option &bus)
Start the driver.
struct bmp280_bus_option & bmp280::find_bus (enum BMP280_BUS busid)
find a bus structure for a busid
void bmp280::start (enum BMP280_BUS busid)
Start the driver.
void bmp280::test (enum BMP280_BUS busid)
Perform some basic functional tests on the driver; make sure we can collect data from the sensor in polled and automatic modes.
void bmp280::reset (enum BMP280_BUS busid)
Reset the driver.
void bmp280::info ()
Print a little info about the driver.
void bmp280::usage ()
Prints info about the driver argument usage.
Variables
struct bmp280::bmp280_bus_option bmp280::bus_options []
Detailed Description
Driver for the BMP280 barometric pressure sensor connected via I2C TODO or SPI.
Definition in file bmp280.cpp.
Macro Definition Documentation
#define NUM_BUS_OPTIONS (sizeof(bus_options)/sizeof(bus_options[0]))
Definition at line 599 of file bmp280.cpp.
Referenced by lis3mdl::find_bus(), bmp280::find_bus(), ets_airspeed::info(), lis3mdl::start(), bmp280::start(), and lis3mdl::stop().
Enumeration Type Documentation
enum BMP280_BUS
Enumerator
BMP280_BUS_ALL
BMP280_BUS_I2C_INTERNAL
BMP280_BUS_I2C_EXTERNAL
BMP280_BUS_SPI_INTERNAL
BMP280_BUS_SPI_EXTERNAL
Definition at line 73 of file bmp280.cpp.
Function Documentation
int bmp280_main (int argc, char * argv[])
Definition at line 848 of file bmp280.cpp.
References BMP280_BUS_ALL, BMP280_BUS_I2C_EXTERNAL, BMP280_BUS_I2C_INTERNAL, BMP280_BUS_SPI_EXTERNAL, BMP280_BUS_SPI_INTERNAL, bmp280::info(), PX4_ERR, px4_getopt(), bmp280::reset(), bmp280::start(), bmp280::test(), and bmp280::usage().