PX4 Firmware: linux_pwm_out::PWMOutBase Class Reference
linux_pwm_out::PWMOutBase Class Reference abstract
class PWMOutBase common abstract PWM output base class
#include <common.h>
Public Member Functions
virtual ~PWMOutBase ()
virtual int init ()=0
virtual int send_output_pwm (const uint16_t *pwm, int num_outputs)=0
Detailed Description
class PWMOutBase common abstract PWM output base class
Definition at line 45 of file common.h.
Constructor & Destructor Documentation
virtual linux_pwm_out::PWMOutBase::~PWMOutBase () inline virtual
Definition at line 49 of file common.h.
References init(), and send_output_pwm().
Member Function Documentation
virtual int linux_pwm_out::PWMOutBase::init () pure virtual
Implemented in linux_pwm_out::PCA9685, linux_pwm_out::BBBlueRcPWMOut, linux_pwm_out::NavioSysfsPWMOut, and linux_pwm_out::OcpocMmapPWMOut.
Referenced by linux_pwm_out::task_main(), and ~PWMOutBase().
virtual int linux_pwm_out::PWMOutBase::send_output_pwm (const uint16_t * pwm, int num_outputs) pure virtual
Implemented in linux_pwm_out::PCA9685, linux_pwm_out::BBBlueRcPWMOut, linux_pwm_out::NavioSysfsPWMOut, and linux_pwm_out::OcpocMmapPWMOut.
Referenced by linux_pwm_out::task_main(), and ~PWMOutBase().
The documentation for this class was generated from the following file:
src/drivers/linux_pwm_out/common.h