PX4 Firmware: src/platforms/posix/drivers/tonealrmsim/tone_alarm.cpp File Reference
tone_alarm.cpp File Reference
#include <px4_config.h>
#include <px4_posix.h>
#include <drivers/device/device.h>
#include <drivers/drv_tone_alarm.h>
#include <sys/types.h>
#include <stdint.h>
#include <stdbool.h>
#include <stdlib.h>
#include <string.h>
#include <fcntl.h>
#include <errno.h>
#include <stdio.h>
#include <unistd.h>
#include <math.h>
#include <ctype.h>
#include <board_config.h>
#include <drivers/drv_hrt.h>
#include <systemlib/err.h>
#include "VirtDevObj.hpp"
Classes
class ToneAlarm
Functions
__EXPORT int tone_alarm_main (int argc, char *argv[])
static void do_something (unsigned x)
Function Documentation
static void do_something (unsigned x) static
Definition at line 328 of file tone_alarm.cpp.
References hrt_abstime, hrt_call_after(), hrt_cancel(), ToneAlarm::next_char(), ToneAlarm::next_dots(), ToneAlarm::next_note(), ToneAlarm::next_number(), ToneAlarm::next_trampoline(), PX4_DEBUG, PX4_ERR, ToneAlarm::start_note(), ToneAlarm::start_tune(), ToneAlarm::stop_note(), and tune_end.
__EXPORT int tone_alarm_main (int argc, char * argv[])
Definition at line 794 of file tone_alarm.cpp.
References fd, ets_airspeed::g_dev, Airspeed::init(), OK, PX4_WARN, TONE_NUMBER_OF_TUNES, and TONE_STOP_TUNE.