PX4 Firmware: src/platforms/common/work_queue/hrt_queue.c File Reference
hrt_queue.c File Reference
#include <px4_config.h>
#include <px4_defines.h>
#include <px4_workqueue.h>
#include <px4_tasks.h>
#include <signal.h>
#include <stdint.h>
#include <queue.h>
#include <stdio.h>
#include <semaphore.h>
#include <drivers/drv_hrt.h>
#include <px4_posix.h>
#include "hrt_work.h"
Functions
int hrt_work_queue (struct work_s *work, worker_t worker, void *arg, uint32_t delay)
Function Documentation
int hrt_work_queue (struct work_s * work, worker_t worker, void * arg, uint32_t delay)
Definition at line 107 of file hrt_queue.c.
References dq_addlast(), g_hrt_work, hrt_absolute_time(), PX4_OK, and px4_task_kill().