PX4 Firmware: ADIS16448_mag Class Reference
ADIS16448_mag Class Reference
Helper class implementing the mag driver node.
Public Member Functions
ADIS16448_mag (ADIS16448 *parent, const char *path)
virtual ~ADIS16448_mag ()
virtual ssize_t read (struct file *filp, char *buffer, size_t buflen)
virtual int ioctl (struct file *filp, int cmd, unsigned long arg)
virtual int init ()
Initialise the driver and make it ready for use.
Public Member Functions inherited from device::CDev
CDev (const char *name, const char *devname)
Constructor.
virtual ~CDev ()
virtual int open (file_t *filep)
Handle an open of the device.
virtual int close (file_t *filep)
Handle a close of the device.
virtual ssize_t read (file_t *filep, char *buffer, size_t buflen)
Perform a read from the device.
virtual ssize_t write (file_t *filep, const char *buffer, size_t buflen)
Perform a write to the device.
virtual off_t seek (file_t *filep, off_t offset, int whence)
Perform a logical seek operation on the device.
virtual int ioctl (file_t *filep, int cmd, unsigned long arg)
Perform an ioctl operation on the device.
virtual int poll (file_t *filep, px4_pollfd_struct_t *fds, bool setup)
Perform a poll setup/teardown operation.
Public Member Functions inherited from device::Device
virtual ~Device ()=default
Destructor.
virtual int read (unsigned address, void *data, unsigned count)
Read directly from the device.
virtual int write (unsigned address, void *data, unsigned count)
Write directly to the device.
virtual int ioctl (unsigned operation, unsigned &arg)
Perform a device-specific operation.
uint8_t get_device_bus ()
Return the bus ID the device is connected to.
DeviceBusType get_device_bus_type ()
Return the bus type the device is connected to.
uint8_t get_device_address ()
Return the bus address of the device.
void set_device_address (int address)
void set_device_type (uint8_t devtype)
Set the device type.
virtual bool external ()
Protected Member Functions
void parent_poll_notify ()
Protected Member Functions inherited from device::CDev
virtual pollevent_t poll_state (file_t *filep)
Check the current state of the device for poll events from the perspective of the file.
virtual void poll_notify (pollevent_t events)
Report new poll events.
virtual void poll_notify_one (px4_pollfd_struct_t *fds, pollevent_t events)
Internal implementation of poll_notify.
virtual int open_first (file_t *filep)
Notification of the first open.
virtual int close_last (file_t *filep)
Notification of the last close.
virtual int register_class_devname (const char *class_devname)
Register a class device name, automatically adding device class instance suffix if need be.
virtual int unregister_class_devname (const char *class_devname, unsigned class_instance)
Register a class device name, automatically adding device class instance suffix if need be.
const char * get_devname ()
Get the device name.
void lock ()
Take the driver lock.
void unlock ()
Release the driver lock.
Protected Member Functions inherited from device::Device
Device (const char *name)
Device (DeviceBusType bus_type, uint8_t bus, uint8_t address, uint8_t devtype=0)
Device (const Device &)=delete
Device & operator= (const Device &)=delete
Device (Device &&)=delete
Device & operator= (Device &&)=delete
Private Member Functions
ADIS16448_mag (const ADIS16448_mag &)
ADIS16448_mag operator= (const ADIS16448_mag &)
Private Attributes
ADIS16448 * _parent
orb_advert_t _mag_topic
int _mag_orb_class_instance
int _mag_class_instance
Friends
class ADIS16448
Additional Inherited Members
Public Types inherited from device::Device
enum DeviceBusType { DeviceBusType_UNKNOWN = 0, DeviceBusType_I2C = 1, DeviceBusType_SPI = 2, DeviceBusType_UAVCAN = 3 }
Device bus types for DEVID.
Protected Attributes inherited from device::CDev
px4_sem_t _lock
lock to protect access to all class members (also for derived classes)
bool _pub_blocked {false}
true if publishing should be blocked
Protected Attributes inherited from device::Device
union DeviceId _device_id
device identifier information
const char * _name
driver name
bool _debug_enabled {false}
if true, debug messages are printed
Static Protected Attributes inherited from device::CDev
static const px4_file_operations_t fops = {}
Pointer to the default cdev file operations table; useful for registering clone devices etc.
Detailed Description
Helper class implementing the mag driver node.
Definition at line 443 of file adis16448.cpp.
Constructor & Destructor Documentation
ADIS16448_mag::ADIS16448_mag (ADIS16448 * parent, const char * path)
Definition at line 1641 of file adis16448.cpp.
ADIS16448_mag::~ADIS16448_mag () virtual
Definition at line 1650 of file adis16448.cpp.
References _mag_class_instance, MAG_BASE_DEVICE_PATH, and device::CDev::unregister_class_devname().
ADIS16448_mag::ADIS16448_mag (const ADIS16448_mag &) private
Member Function Documentation
int ADIS16448_mag::init () virtual
Initialise the driver and make it ready for use.
Returns
OK if the driver initialized OK, negative errno otherwise;
Reimplemented from device::CDev.
Definition at line 1658 of file adis16448.cpp.
References _mag_class_instance, DEVICE_DEBUG, lis3mdl::init(), MAG_BASE_DEVICE_PATH, OK, and device::CDev::register_class_devname().
Referenced by ADIS16448::init(), and adis16448::start().
int ADIS16448_mag::ioctl (struct file * filp, int cmd, unsigned long arg) virtual
Definition at line 1689 of file adis16448.cpp.
References _parent, and ADIS16448::mag_ioctl().
Referenced by adis16448::reset(), and adis16448::start().
ADIS16448_mag ADIS16448_mag::operator= (const ADIS16448_mag &) private
void ADIS16448_mag::parent_poll_notify () protected
Definition at line 1677 of file adis16448.cpp.
References device::CDev::poll_notify().
Referenced by ADIS16448::measure().
ssize_t ADIS16448_mag::read (struct file * filp, char * buffer, size_t buflen) virtual
Definition at line 1683 of file adis16448.cpp.
References _parent, and ADIS16448::mag_read().
Referenced by adis16448::test().
Friends And Related Function Documentation
friend class ADIS16448 friend
Definition at line 454 of file adis16448.cpp.
Referenced by adis16448::start().
Member Data Documentation
int ADIS16448_mag::_mag_class_instance private
Definition at line 461 of file adis16448.cpp.
Referenced by init(), and ~ADIS16448_mag().
int ADIS16448_mag::_mag_orb_class_instance private
Definition at line 460 of file adis16448.cpp.
Referenced by ADIS16448::init().
orb_advert_t ADIS16448_mag::_mag_topic private
Definition at line 459 of file adis16448.cpp.
Referenced by ADIS16448::init(), and ADIS16448::measure().
ADIS16448* ADIS16448_mag::_parent private
Definition at line 458 of file adis16448.cpp.
Referenced by ioctl(), and read().
The documentation for this class was generated from the following file:
src/drivers/imu/adis16448/adis16448.cpp