PX4 Firmware: control::BlockRandGauss Class Reference
control::BlockRandGauss Class Reference
#include <BlockRandGauss.hpp>
Public Member Functions
BlockRandGauss (SuperBlock *parent, const char *name)
virtual ~BlockRandGauss ()=default
float update ()
float getMean ()
float getStdDev ()
Public Member Functions inherited from control::Block
Block (SuperBlock *parent, const char *name)
virtual ~Block ()=default
Block (const Block &)=delete
Block & operator= (const Block &)=delete
Block (Block &&)=delete
Block & operator= (Block &&)=delete
void getName (char *name, size_t n)
virtual void updateParams ()
virtual void setDt (float dt)
float getDt ()
Public Member Functions inherited from ListNode< Block *>
void setSibling (Block * sibling)
const Block * getSibling () const
Private Attributes
control::BlockParamFloat _mean
control::BlockParamFloat _stdDev
Additional Inherited Members
Protected Member Functions inherited from control::Block
virtual void updateParamsSubclass ()
SuperBlock * getParent ()
List< BlockParamBase * > & getParams ()
Protected Attributes inherited from control::Block
const char * _name
SuperBlock * _parent
float _dt {0.0f}
List< BlockParamBase * > _params
Protected Attributes inherited from ListNode< Block *>
Block * _list_node_sibling
Detailed Description
Definition at line 58 of file BlockRandGauss.hpp.
Constructor & Destructor Documentation
BlockRandGauss()
control::BlockRandGauss::BlockRandGauss (SuperBlock * parent, const char * name) inline
Definition at line 62 of file BlockRandGauss.hpp.
~BlockRandGauss()
virtual control::BlockRandGauss::~BlockRandGauss () virtual default
Member Function Documentation
getMean()
float control::BlockRandGauss::getMean () inline
Definition at line 98 of file BlockRandGauss.hpp.
Referenced by control::blockRandGaussTest(), and blockRandGaussTest().
getStdDev()
float control::BlockRandGauss::getStdDev () inline
Definition at line 99 of file BlockRandGauss.hpp.
Referenced by control::blockRandGaussTest(), and blockRandGaussTest().
update()
float control::BlockRandGauss::update () inline
Definition at line 73 of file BlockRandGauss.hpp.
References f().
Referenced by control::blockRandGaussTest(), and blockRandGaussTest().
Member Data Documentation
_mean
control::BlockParamFloat control::BlockRandGauss::_mean private
Definition at line 102 of file BlockRandGauss.hpp.
_stdDev
control::BlockParamFloat control::BlockRandGauss::_stdDev private
Definition at line 103 of file BlockRandGauss.hpp.
The documentation for this class was generated from the following file:
src/lib/controllib/BlockRandGauss.hpp