PX4 Firmware: TAP_ESC Class Reference
TAP_ESC Class Reference
Public Member Functions
TAP_ESC (char const *const device, uint8_t channels_count)
virtual ~TAP_ESC ()
void run () override
virtual int init ()
Initialise the driver and make it ready for use.
virtual int ioctl (device::file_t *filp, int cmd, unsigned long arg)
Perform an ioctl operation on the device.
void cycle ()
Public Member Functions inherited from device::CDev
CDev (const char *name, const char *devname)
Constructor.
virtual ~CDev ()
virtual int open (file_t *filep)
Handle an open of the device.
virtual int close (file_t *filep)
Handle a close of the device.
virtual ssize_t read (file_t *filep, char *buffer, size_t buflen)
Perform a read from the device.
virtual ssize_t write (file_t *filep, const char *buffer, size_t buflen)
Perform a write to the device.
virtual off_t seek (file_t *filep, off_t offset, int whence)
Perform a logical seek operation on the device.
virtual int poll (file_t *filep, px4_pollfd_struct_t *fds, bool setup)
Perform a poll setup/teardown operation.
Public Member Functions inherited from device::Device
virtual ~Device ()=default
Destructor.
virtual int read (unsigned address, void *data, unsigned count)
Read directly from the device.
virtual int write (unsigned address, void *data, unsigned count)
Write directly to the device.
virtual int ioctl (unsigned operation, unsigned &arg)
Perform a device-specific operation.
uint8_t get_device_bus ()
Return the bus ID the device is connected to.
DeviceBusType get_device_bus_type ()
Return the bus type the device is connected to.
uint8_t get_device_address ()
Return the bus address of the device.
void set_device_address (int address)
void set_device_type (uint8_t devtype)
Set the device type.
virtual bool external ()
Public Member Functions inherited from ModuleParams
ModuleParams (ModuleParams *parent)
void setParent (ModuleParams *parent)
Set the parent module.
virtual ~ModuleParams ()=default
ModuleParams (const ModuleParams &)=delete
ModuleParams & operator= (const ModuleParams &)=delete
ModuleParams (ModuleParams &&)=delete
ModuleParams & operator= (ModuleParams &&)=delete
Public Member Functions inherited from ListNode< ModuleParams * >
ListNode ()
ListNode (const ListNode &)=delete
ListNode (ListNode &&)=delete
virtual ~ListNode ()=default
ListNode & operator= (const ListNode &)=delete
ListNode & operator= (ListNode &&)=delete
void setSibling (ModuleParams *sibling)
const ModuleParams * getSibling ()
Static Public Member Functions
static int task_spawn (int argc, char *argv[])
static TAP_ESC * instantiate (int argc, char *argv[])
static int custom_command (int argc, char *argv[])
static int print_usage (const char *reason=nullptr)
Private Member Functions
DEFINE_PARAMETERS ((ParamBool< px4::params::MC_AIRMODE >) _airmode) void subscribe()
void send_esc_outputs (const uint16_t *pwm, const uint8_t motor_cnt)
int control_callback (uint8_t control_group, uint8_t control_index, float &input)
Static Private Member Functions
static int control_callback_trampoline (uintptr_t handle, uint8_t control_group, uint8_t control_index, float &input)
Private Attributes
char _device [DEVICE_ARGUMENT_MAX_LENGTH]
int _uart_fd = -1
bool _is_armed = false
int _armed_sub = -1
int _test_motor_sub = -1
int _params_sub = -1
orb_advert_t _outputs_pub = nullptr
actuator_outputs_s _outputs = {}
actuator_armed_s _armed = {}
perf_counter_t _perf_control_latency
int _control_subs [actuator_controls_s::NUM_ACTUATOR_CONTROL_GROUPS]
actuator_controls_s _controls [actuator_controls_s::NUM_ACTUATOR_CONTROL_GROUPS]
orb_id_t _control_topics [actuator_controls_s::NUM_ACTUATOR_CONTROL_GROUPS]
px4_pollfd_struct_t _poll_fds [actuator_controls_s::NUM_ACTUATOR_CONTROL_GROUPS]
unsigned _poll_fds_num = 0
orb_advert_t _esc_feedback_pub = nullptr
orb_advert_t _to_mixer_status = nullptr
mixer status flags
esc_status_s _esc_feedback = {}
uint8_t _channels_count = 0
nnumber of ESC channels
uint8_t _responding_esc = 0
MixerGroup * _mixers = nullptr
uint32_t _groups_required = 0
uint32_t _groups_subscribed = 0
ESC_UART_BUF _uartbuf = {}
EscPacket _packet = {}
Static Private Attributes
static const uint8_t _device_mux_map [TAP_ESC_MAX_MOTOR_NUM] = ESC_POS
static const uint8_t _device_dir_map [TAP_ESC_MAX_MOTOR_NUM] = ESC_DIR
Additional Inherited Members
Public Types inherited from device::Device
enum DeviceBusType { DeviceBusType_UNKNOWN = 0, DeviceBusType_I2C = 1, DeviceBusType_SPI = 2, DeviceBusType_UAVCAN = 3 }
Device bus types for DEVID.
Protected Member Functions inherited from device::CDev
virtual pollevent_t poll_state (file_t *filep)
Check the current state of the device for poll events from the perspective of the file.
virtual void poll_notify (pollevent_t events)
Report new poll events.
virtual void poll_notify_one (px4_pollfd_struct_t *fds, pollevent_t events)
Internal implementation of poll_notify.
virtual int open_first (file_t *filep)
Notification of the first open.
virtual int close_last (file_t *filep)
Notification of the last close.
virtual int register_class_devname (const char *class_devname)
Register a class device name, automatically adding device class instance suffix if need be.
virtual int unregister_class_devname (const char *class_devname, unsigned class_instance)
Register a class device name, automatically adding device class instance suffix if need be.
const char * get_devname ()
Get the device name.
void lock ()
Take the driver lock.
void unlock ()
Release the driver lock.
Protected Member Functions inherited from device::Device
Device (const char *name)
Device (DeviceBusType bus_type, uint8_t bus, uint8_t address, uint8_t devtype=0)
Device (const Device &)=delete
Device & operator= (const Device &)=delete
Device (Device &&)=delete
Device & operator= (Device &&)=delete
Protected Member Functions inherited from ModuleParams
virtual void updateParams ()
Call this whenever the module gets a parameter change notification.
virtual void updateParamsImpl ()
The implementation for this is generated with the macro DEFINE_PARAMETERS()
Protected Attributes inherited from device::CDev
px4_sem_t _lock
lock to protect access to all class members (also for derived classes)
bool _pub_blocked {false}
true if publishing should be blocked
Protected Attributes inherited from device::Device
union DeviceId _device_id
device identifier information
const char * _name
driver name
bool _debug_enabled {false}
if true, debug messages are printed
Protected Attributes inherited from ListNode< ModuleParams * >
ModuleParams * _sibling
Static Protected Attributes inherited from device::CDev
static const px4_file_operations_t fops = {}
Pointer to the default cdev file operations table; useful for registering clone devices etc.
Detailed Description
Definition at line 85 of file tap_esc.cpp.
Constructor & Destructor Documentation
TAP_ESC::TAP_ESC (char const *const device, uint8_t channels_count)
Definition at line 157 of file tap_esc.cpp.
References _control_subs, _control_topics, _controls, _device, _outputs, _poll_fds, actuator_outputs_s::noutputs, ORB_ID, and actuator_outputs_s::output.
Referenced by instantiate().
TAP_ESC::~TAP_ESC () virtual
Definition at line 184 of file tap_esc.cpp.
References _armed_sub, _control_subs, _esc_feedback_pub, _outputs_pub, _params_sub, _perf_control_latency, _test_motor_sub, _to_mixer_status, _uart_fd, tap_esc_common::deinitialise_uart(), DEVICE_LOG, orb_unadvertise(), orb_unsubscribe(), and perf_free().
Member Function Documentation
int TAP_ESC::control_callback (uint8_t control_group, uint8_t control_index, float & input) inline private
Definition at line 630 of file tap_esc.cpp.
References _armed, _controls, actuator_armed_s::armed, actuator_controls_s::control, f(), and actuator_armed_s::prearmed.
Referenced by control_callback_trampoline().
int TAP_ESC::control_callback_trampoline (uintptr_t handle, uint8_t control_group, uint8_t control_index, float & input) static private
Definition at line 624 of file tap_esc.cpp.
References control_callback().
Referenced by ioctl().
int TAP_ESC::custom_command (int argc, char * argv[]) static
See also
ModuleBase
Definition at line 264 of file tap_esc.cpp.
References print_usage().
void TAP_ESC::cycle ()
Definition at line 407 of file tap_esc.cpp.
References _armed, _armed_sub, _channels_count, _control_subs, _control_topics, _controls, _esc_feedback, _esc_feedback_pub, _groups_required, _groups_subscribed, _is_armed, _mixers, _outputs, _outputs_pub, _packet, _params_sub, _perf_control_latency, _poll_fds, _poll_fds_num, _test_motor_sub, _to_mixer_status, _uart_fd, _uartbuf, actuator_armed_s::armed, RunInfoRepsonse::channelID, math::constrain(), esc_status_s::counter, EscPacket::d, DEVICE_DEBUG, DEVICE_LOG, esc_status_s::esc, esc_status_s::esc_connectiontype, esc_status_s::esc_count, esc_report_s::esc_rpm, esc_report_s::esc_state, esc_report_s::esc_vendor, ESCBUS_MSG_ID_RUN_INFO, RunInfoRepsonse::ESCStatus, MixerGroup::get_saturation_status(), hrt_absolute_time(), hrt_abstime, actuator_armed_s::lockdown, actuator_armed_s::manual_lockdown, MixerGroup::mix(), test_motor_s::motor_number, EscPacket::msg_id, actuator_outputs_s::noutputs, orb_check(), orb_copy(), ORB_ID, orb_publish(), orb_set_interval(), actuator_outputs_s::output, tap_esc_common::parse_tap_esc_feedback(), perf_set_elapsed(), PX4_INFO, px4_poll(), tap_esc_common::read_data_from_uart(), RPMMAX, RPMMIN, RPMSTOPPED, EscPacket::rspRunInfo, multirotor_motor_limits_s::saturation_status, send_esc_outputs(), MixerGroup::set_airmode(), RunInfoRepsonse::speed, linux_pwm_out::subscribe(), TAP_ESC_CTRL_UORB_UPDATE_INTERVAL, TAP_ESC_MAX_MOTOR_NUM, actuator_outputs_s::timestamp, esc_status_s::timestamp, actuator_controls_s::timestamp_sample, ModuleParams::updateParams(), and test_motor_s::value.
Referenced by run().
TAP_ESC::DEFINE_PARAMETERS ((ParamBool< px4::params::MC_AIRMODE >) _airmode) private
Parameters
_airmode multicopter air-mode
int TAP_ESC::init () virtual
Initialise the driver and make it ready for use.
Returns
OK if the driver initialized OK, negative errno otherwise;
Reimplemented from device::CDev.
Definition at line 269 of file tap_esc.cpp.
References _armed_sub, _channels_count, _control_subs, _control_topics, _device, _device_dir_map, _device_mux_map, _esc_feedback, _esc_feedback_pub, _groups_required, _groups_subscribed, _outputs, _outputs_pub, _params_sub, _poll_fds, _poll_fds_num, _test_motor_sub, _to_mixer_status, _uart_fd, BOARD_TAP_ESC_MODE, EscPacket::bytes, EscPacket::d, DEVICE_DEBUG, ESC_MASK_MAP_CHANNEL, ESC_MASK_MAP_RUNNING_DIRECTION, ESCBUS_MSG_ID_CONFIG_BASIC, ESCBUS_MSG_ID_RUN, hrt_absolute_time(), hrt_abstime, lis3mdl::init(), tap_esc_common::initialise_uart(), EscPacket::len, MAX_BOOT_TIME_MS, orb_advertise(), ORB_ID, orb_subscribe(), orb_unsubscribe(), PACKET_HEAD, PX4_ERR, EscPacket::reqConfigInfoBasic, EscPacket::reqRun, RunReq::rpm_flags, RPMMAX, RPMMIN, tap_esc_common::send_packet(), linux_pwm_out::subscribe(), and usleep().
Referenced by instantiate().
TAP_ESC * TAP_ESC::instantiate (int argc, char * argv[]) static
See also
ModuleBase
Definition at line 209 of file tap_esc.cpp.
References init(), print_usage(), PX4_ERR, px4_getopt(), and TAP_ESC().
int TAP_ESC::ioctl (device::file_t * filep, int cmd, unsigned long arg) virtual
Perform an ioctl operation on the device.
The default implementation handles DIOC_GETPRIV, and otherwise returns -ENOTTY. Subclasses should call the default implementation for any command they do not handle themselves.
Parameters
filep Pointer to the NuttX file structure.
cmd The ioctl command value.
arg The ioctl argument value.
Returns
OK on success, or -errno otherwise.
Reimplemented from device::CDev.
Definition at line 655 of file tap_esc.cpp.
References _groups_required, _mixers, control_callback_trampoline(), DEVICE_DEBUG, MixerGroup::groups_required(), MixerGroup::load_from_buf(), MIXERIOCLOADBUF, MIXERIOCRESET, and OK.
int TAP_ESC::print_usage (const char * reason = nullptr) static
See also
ModuleBase
Definition at line 746 of file tap_esc.cpp.
References PRINT_MODULE_DESCRIPTION(), PRINT_MODULE_USAGE_COMMAND_DESCR(), PRINT_MODULE_USAGE_NAME(), PRINT_MODULE_USAGE_PARAM_INT(), PRINT_MODULE_USAGE_PARAM_STRING(), PX4_OK, PX4_WARN, and tap_esc_main().
Referenced by custom_command(), and instantiate().
void TAP_ESC::run () override
See also
ModuleBase::run()
ModuleBase
Definition at line 711 of file tap_esc.cpp.
References cycle().
void TAP_ESC::send_esc_outputs (const uint16_t * pwm, const uint8_t motor_cnt) private
Definition at line 372 of file tap_esc.cpp.
References _channels_count, _responding_esc, _uart_fd, EscPacket::d, ESCBUS_MSG_ID_RUN, EscPacket::len, PACKET_HEAD, PX4_WARN, EscPacket::reqRun, RunReq::rpm_flags, RPMMAX, RPMSTOPPED, RUN_BLUE_LED_ON_MASK, RUN_FEEDBACK_ENABLE_MASK, tap_esc_common::send_packet(), and TAP_ESC_MAX_MOTOR_NUM.
Referenced by cycle().
int TAP_ESC::task_spawn (int argc, char * argv[]) static
See also
ModuleBase
Definition at line 720 of file tap_esc.cpp.
References PX4_ERR, PX4_ERROR, PX4_OK, px4_task_spawn_cmd(), SCHED_DEFAULT, and SCHED_PRIORITY_ACTUATOR_OUTPUTS.
Member Data Documentation
actuator_armed_s TAP_ESC::_armed = {} private
Definition at line 121 of file tap_esc.cpp.
Referenced by control_callback(), and cycle().
int TAP_ESC::_armed_sub = -1 private
Definition at line 116 of file tap_esc.cpp.
Referenced by cycle(), init(), and ~TAP_ESC().
uint8_t TAP_ESC::_channels_count = 0 private
nnumber of ESC channels
Definition at line 134 of file tap_esc.cpp.
Referenced by cycle(), init(), and send_esc_outputs().
int TAP_ESC::_control_subs[actuator_controls_s::NUM_ACTUATOR_CONTROL_GROUPS] private
Definition at line 125 of file tap_esc.cpp.
Referenced by cycle(), init(), TAP_ESC(), and ~TAP_ESC().
orb_id_t TAP_ESC::_control_topics[actuator_controls_s::NUM_ACTUATOR_CONTROL_GROUPS] private
Definition at line 127 of file tap_esc.cpp.
Referenced by cycle(), init(), and TAP_ESC().
actuator_controls_s TAP_ESC::_controls[actuator_controls_s::NUM_ACTUATOR_CONTROL_GROUPS] private
Definition at line 126 of file tap_esc.cpp.
Referenced by control_callback(), cycle(), and TAP_ESC().
char TAP_ESC::_device[DEVICE_ARGUMENT_MAX_LENGTH] private
Definition at line 111 of file tap_esc.cpp.
Referenced by init(), and TAP_ESC().
const uint8_t TAP_ESC::_device_dir_map = ESC_DIR static private
Definition at line 114 of file tap_esc.cpp.
Referenced by init().
const uint8_t TAP_ESC::_device_mux_map = ESC_POS static private
Definition at line 113 of file tap_esc.cpp.
Referenced by init().
esc_status_s TAP_ESC::_esc_feedback = {} private
Definition at line 133 of file tap_esc.cpp.
Referenced by cycle(), and init().
orb_advert_t TAP_ESC::_esc_feedback_pub = nullptr private
Definition at line 131 of file tap_esc.cpp.
Referenced by cycle(), init(), and ~TAP_ESC().
uint32_t TAP_ESC::_groups_required = 0 private
Definition at line 138 of file tap_esc.cpp.
Referenced by cycle(), init(), and ioctl().
uint32_t TAP_ESC::_groups_subscribed = 0 private
Definition at line 139 of file tap_esc.cpp.
Referenced by cycle(), and init().
bool TAP_ESC::_is_armed = false private
Definition at line 115 of file tap_esc.cpp.
Referenced by cycle().
MixerGroup* TAP_ESC::_mixers = nullptr private
Definition at line 137 of file tap_esc.cpp.
Referenced by cycle(), and ioctl().
actuator_outputs_s TAP_ESC::_outputs = {} private
Definition at line 120 of file tap_esc.cpp.
Referenced by cycle(), init(), and TAP_ESC().
orb_advert_t TAP_ESC::_outputs_pub = nullptr private
Definition at line 119 of file tap_esc.cpp.
Referenced by cycle(), init(), and ~TAP_ESC().
EscPacket TAP_ESC::_packet = {} private
Definition at line 141 of file tap_esc.cpp.
Referenced by cycle().
int TAP_ESC::_params_sub = -1 private
Definition at line 118 of file tap_esc.cpp.
Referenced by cycle(), init(), and ~TAP_ESC().
perf_counter_t TAP_ESC::_perf_control_latency private
Definition at line 123 of file tap_esc.cpp.
Referenced by cycle(), and ~TAP_ESC().
px4_pollfd_struct_t TAP_ESC::_poll_fds[actuator_controls_s::NUM_ACTUATOR_CONTROL_GROUPS] private
Definition at line 128 of file tap_esc.cpp.
Referenced by cycle(), init(), and TAP_ESC().
unsigned TAP_ESC::_poll_fds_num = 0 private
Definition at line 129 of file tap_esc.cpp.
Referenced by cycle(), and init().
uint8_t TAP_ESC::_responding_esc = 0 private
Definition at line 135 of file tap_esc.cpp.
Referenced by send_esc_outputs().
int TAP_ESC::_test_motor_sub = -1 private
Definition at line 117 of file tap_esc.cpp.
Referenced by cycle(), init(), and ~TAP_ESC().
orb_advert_t TAP_ESC::_to_mixer_status = nullptr private
mixer status flags
Definition at line 132 of file tap_esc.cpp.
Referenced by cycle(), init(), and ~TAP_ESC().
int TAP_ESC::_uart_fd = -1 private
Definition at line 112 of file tap_esc.cpp.
Referenced by cycle(), init(), send_esc_outputs(), and ~TAP_ESC().
ESC_UART_BUF TAP_ESC::_uartbuf = {} private
Definition at line 140 of file tap_esc.cpp.
Referenced by cycle().
The documentation for this class was generated from the following file:
src/drivers/tap_esc/tap_esc.cpp