PX4 Firmware: device Namespace Reference
device Namespace Reference
Namespace encapsulating all device framework classes, functions and data.
Classes
class CDev
Abstract class for any character device.
class Device
Fundamental base class for all physical drivers (I2C, SPI).
struct device
Character device indirection table.
struct file_operations
struct file_t
class VFile
Typedefs
using px4_file_operations_t = struct file_operations
using file_t = struct file
using mode_t = uint32_t
Functions
static int cdev_open (file_t *filp)
static int cdev_close (file_t *filp)
static ssize_t cdev_read (file_t *filp, char *buffer, size_t buflen)
static ssize_t cdev_write (file_t *filp, const char *buffer, size_t buflen)
static off_t cdev_seek (file_t *filp, off_t offset, int whence)
static int cdev_ioctl (file_t *filp, int cmd, unsigned long arg)
static int cdev_poll (file_t *filp, px4_pollfd_struct_t *fds, bool setup)
Detailed Description
Namespace encapsulating all device framework classes, functions and data.
Typedef Documentation
using device::file_t = typedef struct file
Definition at line 17 of file cdev_platform.hpp.
using device::mode_t = typedef uint32_t
Definition at line 17 of file cdev_platform.hpp.
typedef struct file_operations device::px4_file_operations_t
Definition at line 16 of file cdev_platform.hpp.
Function Documentation
static int device::cdev_close (file_t * filp) static
Definition at line 96 of file cdev_platform.cpp.
References device::CDev::close().
static int device::cdev_ioctl (file_t * filp, int cmd, unsigned long arg) static
Definition at line 128 of file cdev_platform.cpp.
References device::CDev::ioctl().
static int device::cdev_open (file_t * filp) static
Definition at line 88 of file cdev_platform.cpp.
References device::CDev::open().
static int device::cdev_poll (file_t * filp, px4_pollfd_struct_t * fds, bool setup) static
Definition at line 136 of file cdev_platform.cpp.
References device::CDev::poll().
static ssize_t device::cdev_read (file_t * filp, char * buffer, size_t buflen) static
Definition at line 104 of file cdev_platform.cpp.
References device::CDev::read().
static off_t device::cdev_seek (file_t * filp, off_t offset, int whence) static
Definition at line 120 of file cdev_platform.cpp.
References device::CDev::seek().
static ssize_t device::cdev_write (file_t * filp, const char * buffer, size_t buflen) static
Definition at line 112 of file cdev_platform.cpp.
References device::CDev::write().