PX4 Firmware: src/lib/ecl/EKF/matlab/scripts/Inertial Nav EKF/YawCovariance.c File Reference
YawCovariance.c File Reference
Variables
float SG [3] = sq(_state.quat_nominal(0)) - sq(_state.quat_nominal(1)) - sq(_state.quat_nominal(2)) + sq(_state.quat_nominal(3))
float SQ [4] = 0.5f * ((_state.quat_nominal(1)*SG[0]) - (_state.quat_nominal(0)*SG[2]) + (_state.quat_nominal(3)*SG[1]))
const float daYawVar = TBD
P [0][0] = yaw_variance*sq(SQ[2])
Variable Documentation
daYawVar
const float daYawVar = TBD
Definition at line 23 of file YawCovariance.c.
P
P[3][2] = yaw_variance*sq(SQ[2])
Definition at line 27 of file YawCovariance.c.
SG
SG[2] = sq(_state.quat_nominal(0)) - sq(_state.quat_nominal(1)) - sq(_state.quat_nominal(2)) + sq(_state.quat_nominal(3))
Definition at line 11 of file YawCovariance.c.
Referenced by Ekf::increaseQuatYawErrVariance(), and Ekf::predictCovariance().
SQ
SQ[3] = 0.5f * ((_state.quat_nominal(1)*SG[0]) - (_state.quat_nominal(0)*SG[2]) + (_state.quat_nominal(3)*SG[1]))
Definition at line 16 of file YawCovariance.c.
Referenced by Ekf::increaseQuatYawErrVariance(), and Ekf::predictCovariance().