PX4 Firmware: MavlinkStreamEstimatorStatus Class Reference
MavlinkStreamEstimatorStatus Class Reference
Public Member Functions
const char * get_name () const
uint16_t get_id ()
unsigned get_size ()
Get maximal total messages size on update.
Public Member Functions inherited from MavlinkStream
MavlinkStream (Mavlink *mavlink)
virtual ~MavlinkStream ()=default
MavlinkStream (const MavlinkStream &)=delete
MavlinkStream & operator= (const MavlinkStream &)=delete
MavlinkStream (MavlinkStream &&)=delete
MavlinkStream & operator= (MavlinkStream &&)=delete
void set_interval (const int interval)
Get the interval.
int get_interval ()
Get the interval.
int update (const hrt_abstime &t)
Update subscriptions and send message if necessary.
virtual bool const_rate ()
virtual unsigned get_size_avg ()
Get the average message size.
bool first_message_sent () const
void reset_last_sent ()
Reset the time of last sent to 0.
Static Public Member Functions
static const char * get_name_static ()
static uint16_t get_id_static ()
static MavlinkStream * new_instance (Mavlink *mavlink)
Protected Member Functions
MavlinkStreamEstimatorStatus (Mavlink *mavlink)
bool send (const hrt_abstime t)
Protected Member Functions inherited from MavlinkStream
virtual void update_data ()
Function to collect/update data for the streams at a high rate independant of actual stream rate.
Private Member Functions
MavlinkStreamEstimatorStatus (MavlinkStreamEstimatorStatus &)=delete
MavlinkStreamEstimatorStatus & operator= (const MavlinkStreamEstimatorStatus &)=delete
Private Attributes
MavlinkOrbSubscription * _est_sub
uint64_t _est_time
Additional Inherited Members
Public Attributes inherited from MavlinkStream
MavlinkStream * next {nullptr}
Protected Attributes inherited from MavlinkStream
Mavlink *const _mavlink
int _interval {1000000}
if set to negative value = unlimited rate
Detailed Description
Definition at line 2218 of file mavlink_messages.cpp.
Constructor & Destructor Documentation
MavlinkStreamEstimatorStatus::MavlinkStreamEstimatorStatus (MavlinkStreamEstimatorStatus &) private delete
MavlinkStreamEstimatorStatus::MavlinkStreamEstimatorStatus (Mavlink * mavlink) inline explicit protected
Definition at line 2260 of file mavlink_messages.cpp.
Member Function Documentation
uint16_t MavlinkStreamEstimatorStatus::get_id () inline virtual
Implements MavlinkStream.
Definition at line 2236 of file mavlink_messages.cpp.
References MavlinkStreamHeartbeat::get_id_static().
static uint16_t MavlinkStreamEstimatorStatus::get_id_static () inline static
Definition at line 2231 of file mavlink_messages.cpp.
const char* MavlinkStreamEstimatorStatus::get_name () const inline virtual
Implements MavlinkStream.
Definition at line 2221 of file mavlink_messages.cpp.
References get_name_static().
static const char* MavlinkStreamEstimatorStatus::get_name_static () inline static
Definition at line 2226 of file mavlink_messages.cpp.
Referenced by get_name().
unsigned MavlinkStreamEstimatorStatus::get_size () inline virtual
Get maximal total messages size on update.
Implements MavlinkStream.
Definition at line 2246 of file mavlink_messages.cpp.
static MavlinkStream* MavlinkStreamEstimatorStatus::new_instance (Mavlink * mavlink) inline static
Definition at line 2241 of file mavlink_messages.cpp.
MavlinkStreamEstimatorStatus& MavlinkStreamEstimatorStatus::operator= (const MavlinkStreamEstimatorStatus &) private delete
bool MavlinkStreamEstimatorStatus::send (const hrt_abstime t) inline protected virtual
Implements MavlinkStream.
Definition at line 2265 of file mavlink_messages.cpp.
References MavlinkStream::_mavlink, Mavlink::get_channel(), estimator_status_s::hagl_test_ratio, estimator_status_s::hgt_test_ratio, estimator_status_s::mag_test_ratio, msg, estimator_status_s::pos_horiz_accuracy, estimator_status_s::pos_test_ratio, estimator_status_s::pos_vert_accuracy, estimator_status_s::solution_status_flags, estimator_status_s::tas_test_ratio, estimator_status_s::timestamp, MavlinkOrbSubscription::update(), estimator_status_s::vel_test_ratio, and estimator_status_s::vibe.
Member Data Documentation
MavlinkOrbSubscription* MavlinkStreamEstimatorStatus::_est_sub private
Definition at line 2252 of file mavlink_messages.cpp.
uint64_t MavlinkStreamEstimatorStatus::_est_time private
Definition at line 2253 of file mavlink_messages.cpp.
The documentation for this class was generated from the following file:
src/modules/mavlink/mavlink_messages.cpp