PX4 Firmware: TERARANGER Class Reference
TERARANGER Class Reference
Public Member Functions
TERARANGER (uint8_t rotation=distance_sensor_s::ROTATION_DOWNWARD_FACING, int bus=TERARANGER_BUS_DEFAULT, int address=TRONE_BASEADDR)
virtual ~TERARANGER ()
virtual int init ()
virtual ssize_t read (device::file_t *filp, char *buffer, size_t buflen)
virtual int ioctl (device::file_t *filp, int cmd, unsigned long arg)
void print_info ()
Diagnostics - print some basic information about the driver.
Protected Member Functions
virtual int probe ()
Private Member Functions
int probe_address (uint8_t address)
Test whether the device supported by the driver is present at a specific address.
void start ()
Initialise the automatic measurement state machine and start it.
void stop ()
Stop the automatic measurement state machine.
void set_minimum_distance (float min)
Set the min and max distance thresholds if you want the end points of the sensors range to be brought in at all, otherwise it will use the defaults TRONE_MIN_DISTANCE and TRONE_MAX_DISTANCE.
void set_maximum_distance (float max)
float get_minimum_distance ()
float get_maximum_distance ()
void cycle ()
Perform a poll cycle; collect from the previous measurement and start a new one.
int measure ()
int collect ()
Static Private Member Functions
static void cycle_trampoline (void *arg)
Static trampoline from the workq context; because we don't have a generic workq wrapper yet.
Private Attributes
uint8_t _rotation
float _min_distance
float _max_distance
work_s _work
ringbuffer::RingBuffer * _reports
bool _sensor_ok
uint8_t _valid
int _measure_ticks
bool _collect_phase
int _class_instance
int _orb_class_instance
orb_advert_t _distance_sensor_topic
perf_counter_t _sample_perf
perf_counter_t _comms_errors
Detailed Description
Definition at line 98 of file teraranger.cpp.
Constructor & Destructor Documentation
TERARANGER::TERARANGER (uint8_t rotation = distance_sensor_s::ROTATION_DOWNWARD_FACING, int bus = TERARANGER_BUS_DEFAULT, int address = TRONE_BASEADDR)
Definition at line 229 of file teraranger.cpp.
Referenced by teraranger::start_bus().
TERARANGER::~TERARANGER () virtual
Definition at line 255 of file teraranger.cpp.
References _class_instance, _comms_errors, _reports, _sample_perf, perf_free(), RANGE_FINDER_BASE_DEVICE_PATH, and stop().
Member Function Documentation
int TERARANGER::collect () private
Definition at line 606 of file teraranger.cpp.
References _comms_errors, _distance_sensor_topic, _reports, _rotation, _sample_perf, _valid, distance_sensor_s::covariance, crc8(), distance_sensor_s::current_distance, DEVICE_LOG, f(), get_maximum_distance(), get_minimum_distance(), hrt_absolute_time(), distance_sensor_s::id, distance_sensor_s::max_distance, distance_sensor_s::min_distance, OK, ORB_ID, orb_publish(), distance_sensor_s::orientation, perf_begin(), perf_count(), perf_end(), distance_sensor_s::signal_quality, distance_sensor_s::timestamp, and distance_sensor_s::type.
Referenced by cycle(), and read().
void TERARANGER::cycle () private
Perform a poll cycle; collect from the previous measurement and start a new one.
Definition at line 686 of file teraranger.cpp.
References _collect_phase, _measure_ticks, collect(), cycle_trampoline(), DEVICE_LOG, measure(), OK, start(), and TERARANGER_CONVERSION_INTERVAL.
Referenced by cycle_trampoline().
void TERARANGER::cycle_trampoline (void * arg) static private
Static trampoline from the workq context; because we don't have a generic workq wrapper yet.
Parameters
arg Instance pointer for the driver that is polling.
Definition at line 678 of file teraranger.cpp.
References cycle().
Referenced by cycle(), and start().
float TERARANGER::get_maximum_distance () private
Definition at line 419 of file teraranger.cpp.
References _max_distance.
Referenced by collect().
float TERARANGER::get_minimum_distance () private
Definition at line 413 of file teraranger.cpp.
References _min_distance.
Referenced by collect().
int TERARANGER::init () virtual
Definition at line 275 of file teraranger.cpp.
References _class_instance, _distance_sensor_topic, _max_distance, _min_distance, _orb_class_instance, _reports, _sensor_ok, CLASS_DEVICE_PRIMARY, DEVICE_LOG, lis3mdl::init(), measure(), OK, orb_advertise_multi(), ORB_ID, ORB_PRIO_LOW, param_find(), param_get(), PX4_ERROR, RANGE_FINDER_BASE_DEVICE_PATH, TREVO_600HZ_MAX_DISTANCE, TREVO_600HZ_MIN_DISTANCE, TREVO_60M_MAX_DISTANCE, TREVO_60M_MIN_DISTANCE, TREVO_BASEADDR, TRONE_BASEADDR, TRONE_MAX_DISTANCE, and TRONE_MIN_DISTANCE.
Referenced by teraranger::start_bus().
int TERARANGER::ioctl (device::file_t * filp, int cmd, unsigned long arg) virtual
Definition at line 425 of file teraranger.cpp.
References _measure_ticks, _reports, ATOMIC_ENTER, ATOMIC_LEAVE, OK, SENSOR_POLLRATE_DEFAULT, SENSOR_POLLRATE_EXTERNAL, SENSOR_POLLRATE_MANUAL, SENSOR_POLLRATE_MAX, SENSORIOCGPOLLRATE, SENSORIOCRESET, SENSORIOCSPOLLRATE, SENSORIOCSQUEUEDEPTH, start(), stop(), and TERARANGER_CONVERSION_INTERVAL.
Referenced by teraranger::reset(), teraranger::start_bus(), and teraranger::test().
int TERARANGER::measure () private
Definition at line 584 of file teraranger.cpp.
References _comms_errors, DEVICE_LOG, OK, perf_count(), and TERARANGER_MEASURE_REG.
Referenced by cycle(), init(), probe(), and read().
void TERARANGER::print_info ()
Diagnostics - print some basic information about the driver.
Definition at line 734 of file teraranger.cpp.
References _comms_errors, _measure_ticks, _reports, _sample_perf, and perf_print_counter().
Referenced by teraranger::info().
int TERARANGER::probe () protected virtual
Definition at line 379 of file teraranger.cpp.
References DEVICE_DEBUG, measure(), OK, TERARANGER_WHO_AM_I_REG, and TERARANGER_WHO_AM_I_REG_VAL.
int TERARANGER::probe_address (uint8_t address) private
Test whether the device supported by the driver is present at a specific address.
Parameters
address The I2C bus address to probe.
Returns
True if the device is present.
ssize_t TERARANGER::read (device::file_t * filp, char * buffer, size_t buflen) virtual
Definition at line 524 of file teraranger.cpp.
References _measure_ticks, _reports, collect(), measure(), OK, TERARANGER_CONVERSION_INTERVAL, and usleep().
Referenced by teraranger::test().
void TERARANGER::set_maximum_distance (float max) private
Definition at line 407 of file teraranger.cpp.
References _max_distance, and max().
void TERARANGER::set_minimum_distance (float min) private
Set the min and max distance thresholds if you want the end points of the sensors range to be brought in at all, otherwise it will use the defaults TRONE_MIN_DISTANCE and TRONE_MAX_DISTANCE.
Definition at line 401 of file teraranger.cpp.
References _min_distance, and min().
void TERARANGER::start () private
Initialise the automatic measurement state machine and start it.
Note
This function is called at open and error time. It might make sense to make it more aggressive about resetting the bus in case of errors.
Definition at line 661 of file teraranger.cpp.
References _collect_phase, _reports, and cycle_trampoline().
Referenced by cycle(), and ioctl().
void TERARANGER::stop () private
Stop the automatic measurement state machine.
Definition at line 672 of file teraranger.cpp.
Referenced by ioctl(), and ~TERARANGER().
Member Data Documentation
int TERARANGER::_class_instance private
Definition at line 128 of file teraranger.cpp.
Referenced by init(), and ~TERARANGER().
bool TERARANGER::_collect_phase private
Definition at line 127 of file teraranger.cpp.
Referenced by cycle(), and start().
perf_counter_t TERARANGER::_comms_errors private
Definition at line 134 of file teraranger.cpp.
Referenced by collect(), measure(), print_info(), and ~TERARANGER().
orb_advert_t TERARANGER::_distance_sensor_topic private
Definition at line 131 of file teraranger.cpp.
Referenced by collect(), and init().
float TERARANGER::_max_distance private
Definition at line 121 of file teraranger.cpp.
Referenced by get_maximum_distance(), init(), and set_maximum_distance().
int TERARANGER::_measure_ticks private
Definition at line 126 of file teraranger.cpp.
Referenced by cycle(), ioctl(), print_info(), and read().
float TERARANGER::_min_distance private
Definition at line 120 of file teraranger.cpp.
Referenced by get_minimum_distance(), init(), and set_minimum_distance().
int TERARANGER::_orb_class_instance private
Definition at line 129 of file teraranger.cpp.
Referenced by init().
ringbuffer::RingBuffer* TERARANGER::_reports private
Definition at line 123 of file teraranger.cpp.
Referenced by collect(), init(), ioctl(), print_info(), read(), start(), and ~TERARANGER().
uint8_t TERARANGER::_rotation private
Definition at line 119 of file teraranger.cpp.
Referenced by collect().
perf_counter_t TERARANGER::_sample_perf private
Definition at line 133 of file teraranger.cpp.
Referenced by collect(), print_info(), and ~TERARANGER().
bool TERARANGER::_sensor_ok private
Definition at line 124 of file teraranger.cpp.
Referenced by init().
uint8_t TERARANGER::_valid private
Definition at line 125 of file teraranger.cpp.
Referenced by collect().
work_s TERARANGER::_work private
Definition at line 122 of file teraranger.cpp.
The documentation for this class was generated from the following file:
src/drivers/distance_sensor/teraranger/teraranger.cpp