PX4 Firmware: src/platforms/common/px4_log.c File Reference
px4_log.c File Reference
#include <stdlib.h>
#include <string.h>
#include <px4_log.h>
#include <uORB/uORB.h>
#include <uORB/topics/log_message.h>
#include <drivers/drv_hrt.h>
Functions
void px4_log_initialize (void)
initialize the orb logging.
void px4_backtrace ()
__EXPORT void px4_log_modulename (int level, const char *moduleName, const char *fmt,...)
__EXPORT void px4_log_raw (int level, const char *fmt,...)
Variables
static orb_advert_t orb_log_message_pub = NULL
__EXPORT const char * __px4_log_level_str [_PX4_LOG_LEVEL_PANIC+1] = { "DEBUG", "INFO", "WARN", "ERROR", "PANIC" }
__EXPORT const char * __px4_log_level_color [_PX4_LOG_LEVEL_PANIC+1]
Function Documentation
void px4_backtrace (void)
Definition at line 74 of file px4_log.c.
References PX4_INFO.
void px4_log_initialize (void)
initialize the orb logging.
Logging to console still works without or before calling this.
Definition at line 55 of file px4_log.c.
References hrt_absolute_time(), orb_advertise_queue(), ORB_ID, orb_log_message_pub, PX4_ERR, log_message_s::severity, log_message_s::text, and log_message_s::timestamp.
Referenced by do_nothing(), and uorb_main().
__EXPORT void px4_log_modulename (int level, const char * moduleName, const char * fmt, ...)
Definition at line 96 of file px4_log.c.
References __px4__log_level_arg, __px4__log_level_fmt, __px4__log_modulename_pfmt, __px4_log_level_color, _PX4_LOG_LEVEL_INFO, _PX4_LOG_LEVEL_WARN, hrt_absolute_time(), ORB_ID, orb_log_message_pub, orb_publish(), PX4_ANSI_COLOR_GRAY, PX4_ANSI_COLOR_RESET, PX4_LOG_COLOR_END, PX4_LOG_COLOR_MESSAGE, PX4_LOG_COLOR_MODULE, PX4_LOG_COLOR_START, log_message_s::severity, log_message_s::text, and log_message_s::timestamp.
__EXPORT void px4_log_raw (int level, const char * fmt, ...)
Definition at line 202 of file px4_log.c.
References __px4_log_level_color, _PX4_LOG_LEVEL_INFO, PX4_ANSI_COLOR_RESET, PX4_LOG_COLOR_END, PX4_LOG_COLOR_MESSAGE, and PX4_LOG_COLOR_START.
Variable Documentation
__EXPORT const char* __px4_log_level_color[_PX4_LOG_LEVEL_PANIC+1]
Initial value:
=
{ PX4_ANSI_COLOR_GREEN, PX4_ANSI_COLOR_RESET, PX4_ANSI_COLOR_YELLOW, PX4_ANSI_COLOR_RED, PX4_ANSI_COLOR_RED }
Definition at line 51 of file px4_log.c.
Referenced by px4_log_modulename(), and px4_log_raw().
__EXPORT const char* __px4_log_level_str[_PX4_LOG_LEVEL_PANIC+1] = { "DEBUG", "INFO", "WARN", "ERROR", "PANIC" }
Definition at line 50 of file px4_log.c.
orb_advert_t orb_log_message_pub = NULL static
Definition at line 48 of file px4_log.c.
Referenced by px4_log_initialize(), and px4_log_modulename().