PX4 Firmware: MixerGroup Class Reference
MixerGroup Class Reference
Group of mixers, built up from single mixers and processed in order when mixing.
#include <mixer.h>
Public Member Functions
MixerGroup (ControlCallback control_cb, uintptr_t cb_handle)
~MixerGroup ()
virtual unsigned mix (float *outputs, unsigned space)
Perform the mixing function.
virtual uint16_t get_saturation_status (void)
Get the saturation status.
virtual void groups_required (uint32_t &groups)
Analyses the mix configuration and updates a bitmask of groups that are required.
void add_mixer (Mixer *mixer)
Add a mixer to the group.
void reset ()
Remove all the mixers from the group.
unsigned count ()
Count the mixers in the group.
int load_from_buf (const char *buf, unsigned &buflen)
Adds mixers to the group based on a text description in a buffer.
virtual void set_max_delta_out_once (float delta_out_max)
Update slew rate parameter.
unsigned set_trims (int16_t *v, unsigned n)
unsigned set_trim (float trim)
Set trim offset for this mixer.
unsigned get_trims (int16_t *values)
unsigned get_trim (float *trim)
Get trim offset for this mixer.
virtual void set_thrust_factor (float val)
Sets the thrust factor used to calculate mapping from desired thrust to pwm.
virtual void set_airmode (bool airmode)
Set airmode.
Public Member Functions inherited from Mixer
Mixer (ControlCallback control_cb, uintptr_t cb_handle)
Constructor.
virtual ~Mixer ()
Private Member Functions
MixerGroup (const MixerGroup &)
MixerGroup operator= (const MixerGroup &)
Private Attributes
Mixer * _first
linked list of mixers
Additional Inherited Members
Public Types inherited from Mixer
typedef int(* ControlCallback) (uintptr_t handle, uint8_t control_group, uint8_t control_index, float &control)
Fetch a control value.
Public Attributes inherited from Mixer
Mixer * _next
next mixer in a list
Protected Member Functions inherited from Mixer
float get_control (uint8_t group, uint8_t index)
Invoke the client callback to fetch a control value.
Static Protected Member Functions inherited from Mixer
static float scale (const mixer_scaler_s &scaler, float input)
Perform simpler linear scaling.
static int scale_check (struct mixer_scaler_s &scaler)
Validate a scaler.
static const char * findtag (const char *buf, unsigned &buflen, char tag)
Find a tag.
static char findnexttag (const char *buf, unsigned buflen)
Find next tag and return it (0 is returned if no tag is found)
static const char * skipline (const char *buf, unsigned &buflen)
Skip a line.
static bool string_well_formed (const char *buf, unsigned &buflen)
Check wether the string is well formed and suitable for parsing.
Protected Attributes inherited from Mixer
ControlCallback _control_cb
client-supplied callback used when fetching control values
uintptr_t _cb_handle
Detailed Description
Group of mixers, built up from single mixers and processed in order when mixing.
Definition at line 301 of file mixer.h.
Constructor & Destructor Documentation
MixerGroup::MixerGroup (ControlCallback control_cb, uintptr_t cb_handle)
Definition at line 61 of file mixer_group.cpp.
MixerGroup::~MixerGroup ()
Definition at line 67 of file mixer_group.cpp.
References reset().
MixerGroup::MixerGroup (const MixerGroup &) private
Member Function Documentation
void MixerGroup::add_mixer (Mixer * mixer)
Add a mixer to the group.
Parameters
mixer The mixer to be added.
Definition at line 73 of file mixer_group.cpp.
References _first, Mixer::_next, and uart_esc::mixer.
Referenced by PWMSim::ioctl(), load_from_buf(), MK::pwm_ioctl(), and PX4FMU::pwm_ioctl().
unsigned MixerGroup::count (void)
Count the mixers in the group.
Definition at line 216 of file mixer_group.cpp.
References _first, Mixer::_next, and uart_esc::mixer.
Referenced by linux_pwm_out::initialize_mixer(), and MixerTest::load_mixer().
uint16_t MixerGroup::get_saturation_status (void) virtual
Get the saturation status.
Returns
Integer bitmask containing saturation_status from multirotor_motor_limits.msg.
Implements Mixer.
Definition at line 202 of file mixer_group.cpp.
References _first, Mixer::_next, Mixer::get_saturation_status(), and uart_esc::mixer.
Referenced by TAP_ESC::cycle(), PX4FMU::cycle(), and mixer_mix_threadsafe().
unsigned MixerGroup::get_trim (float * trim) inline virtual
Get trim offset for this mixer.
Returns
the number of outputs this mixer feeds to
Implements Mixer.
Definition at line 410 of file mixer.h.
References Mixer::set_airmode(), and Mixer::set_thrust_factor().
unsigned MixerGroup::get_trims (int16_t * values)
Definition at line 155 of file mixer_group.cpp.
References _first, Mixer::_next, Mixer::get_trim(), and uart_esc::mixer.
Referenced by PX4FMU::pwm_ioctl().
void MixerGroup::groups_required (uint32_t & groups) virtual
Analyses the mix configuration and updates a bitmask of groups that are required.
Parameters
groups A bitmask of groups (0-31) that the mixer requires.
Implements Mixer.
Definition at line 230 of file mixer_group.cpp.
References _first, Mixer::_next, Mixer::groups_required(), and uart_esc::mixer.
Referenced by PWMSim::ioctl(), TAP_ESC::ioctl(), UavcanNode::ioctl(), PX4FMU::pwm_ioctl(), and linux_pwm_out::task_main().
int MixerGroup::load_from_buf (const char * buf, unsigned & buflen)
Adds mixers to the group based on a text description in a buffer.
Mixer definitions begin with a single capital letter and a colon. The actual format of the mixer definition varies with the individual mixers; they are summarised here, but see ROMFS/mixers/README for more details.
Null Mixer ..........
The null mixer definition has the form:
Z:
Simple Mixer ............
A simple mixer definition begins with:
M: <control count>=""> O: <-ve scale> <+ve scale> <offset> <lower limit>=""> <upper limit>="">
The second line O: can be omitted. In that case 'O: 10000 10000 0 -10000 10000' is used. The definition continues with <control count>=""> entries describing the control inputs and their scaling, in the form:
S: <group> <index> <-ve scale> <+ve scale> <offset> <lower limit>=""> <upper limit>="">
Multirotor Mixer ................
The multirotor mixer definition is a single line of the form:
R: <geometry> <roll scale>=""> <pitch scale>=""> <yaw scale>=""> <deadband>
Helicopter Mixer ................
The helicopter mixer includes throttle and pitch curves
H: <swash plate="" servo="" count>=""> T: <0> <2500> <5000> <7500> <10000> P: <-10000> <-5000> <0> <5000> <10000>
The definition continues with <swash plate="" servo="" count>=""> entries describing the position of the servo, in the following form:
S: <angle (deg)> <normalized arm="" length>=""> <scale> <offset> <lower limit>=""> <upper limit>="">
Parameters
buf The mixer configuration buffer.
buflen The length of the buffer, updated to reflect bytes as they are consumed.
Returns
Zero on successful load, nonzero otherwise.
Definition at line 241 of file mixer_group.cpp.
References Mixer::_cb_handle, Mixer::_control_cb, add_mixer(), debug, NullMixer::from_text(), SimpleMixer::from_text(), MultirotorMixer::from_text(), and HelicopterMixer::from_text().
Referenced by linux_pwm_out::initialize_mixer(), df_bebop_bus_wrapper::initialize_mixers(), PWMSim::ioctl(), TAP_ESC::ioctl(), UavcanNode::ioctl(), MixerTest::load_mixer(), mixer_handle_text_create_mixer(), MK::pwm_ioctl(), and PX4FMU::pwm_ioctl().
unsigned MixerGroup::mix (float * outputs, unsigned space) virtual
Perform the mixing function.
Parameters
outputs Array into which mixed output(s) should be placed.
space The number of available entries in the output array;
Returns
The number of entries in the output array that were populated.
Implements Mixer.
Definition at line 106 of file mixer_group.cpp.
References _first, Mixer::_next, Mixer::mix(), and uart_esc::mixer.
Referenced by TAP_ESC::cycle(), PX4FMU::cycle(), mixer_mix_threadsafe(), MixerTest::mixerTest(), PWMSim::run(), UavcanNode::run(), linux_pwm_out::task_main(), MK::task_main(), and df_bebop_bus_wrapper::task_main().
MixerGroup MixerGroup::operator= (const MixerGroup &) private
void MixerGroup::reset (void)
Remove all the mixers from the group.
Definition at line 88 of file mixer_group.cpp.
References _first, Mixer::_next, and uart_esc::mixer.
Referenced by MixerTest::load_mixer(), mixer_handle_text(), and ~MixerGroup().
void MixerGroup::set_airmode (bool airmode) virtual
Set airmode.
Airmode allows the mixer to increase the total thrust in order to unsaturate the motors.
Parameters
[in] airmode De/-activate airmode by setting it to false/true
Reimplemented from Mixer.
Definition at line 191 of file mixer_group.cpp.
References _first, Mixer::_next, uart_esc::mixer, and Mixer::set_airmode().
Referenced by TAP_ESC::cycle(), PX4FMU::cycle(), mixer_tick(), PWMSim::run(), UavcanNode::run(), and linux_pwm_out::task_main().
void MixerGroup::set_max_delta_out_once (float delta_out_max) virtual
Update slew rate parameter.
This tells instances of the class MultirotorMixer the maximum allowed change of the output values per cycle. The value is only valid for one cycle, in order to have continuous slew rate limiting this function needs to be called before every call to mix().
Parameters
[in] delta_out_max Maximum delta output.
Reimplemented from Mixer.
Definition at line 308 of file mixer_group.cpp.
References _first, Mixer::_next, uart_esc::mixer, and Mixer::set_max_delta_out_once().
Referenced by PX4FMU::cycle(), mixer_set_failsafe(), and mixer_tick().
void MixerGroup::set_thrust_factor (float val) virtual
Sets the thrust factor used to calculate mapping from desired thrust to pwm.
Parameters
[in] val The value
Reimplemented from Mixer.
Definition at line 180 of file mixer_group.cpp.
References _first, Mixer::_next, uart_esc::mixer, and Mixer::set_thrust_factor().
Referenced by PX4FMU::cycle(), mixer_set_failsafe(), and mixer_tick().
unsigned MixerGroup::set_trim (float trim) inline virtual
Set trim offset for this mixer.
Returns
the number of outputs this mixer feeds to
Implements Mixer.
Definition at line 403 of file mixer.h.
unsigned MixerGroup::set_trims (int16_t * v, unsigned n)
Definition at line 126 of file mixer_group.cpp.
References _first, Mixer::_next, debug, f(), uart_esc::mixer, and Mixer::set_trim().
Referenced by mixer_tick(), PX4FMU::pwm_ioctl(), and PX4FMU::update_pwm_trims().
Member Data Documentation
Mixer* MixerGroup::_first private
linked list of mixers
Definition at line 425 of file mixer.h.
Referenced by add_mixer(), count(), get_saturation_status(), get_trims(), groups_required(), mix(), reset(), set_airmode(), set_max_delta_out_once(), set_thrust_factor(), and set_trims().
The documentation for this class was generated from the following files:
src/lib/mixer/mixer.h
src/lib/mixer/mixer_group.cpp