PX4 Firmware: src/systemcmds/tests/test_rc.c File Reference
test_rc.c File Reference
Tests RC input.
#include <px4_platform_common/px4_config.h>
#include <sys/types.h>
#include <stdio.h>
#include <poll.h>
#include <stdlib.h>
#include <unistd.h>
#include <fcntl.h>
#include <errno.h>
#include <arch/board/board.h>
#include <drivers/drv_pwm_output.h>
#include <drivers/drv_rc_input.h>
#include <drivers/drv_hrt.h>
#include <systemlib/err.h>
#include "tests_main.h"
#include <math.h>
#include <float.h>
Functions
int test_rc (int argc, char *argv[])
Detailed Description
Tests RC input.
Definition in file test_rc.c.
Function Documentation
test_rc()
int test_rc (int argc, char * argv[])
Definition at line 61 of file test_rc.c.
References matrix::abs(), input_rc_s::channel_count, hrt_absolute_time(), orb_check(), orb_copy(), ORB_ID, orb_subscribe(), orb_unsubscribe(), input_rc_s::timestamp_last_signal, and input_rc_s::values.