PX4 Firmware: ets_airspeed Namespace Reference
ets_airspeed Namespace Reference
Local functions in support of the shell command.
Functions
int start ()
Attempt to start driver on all available I2C busses.
int start_bus (int i2c_bus)
Start the driver on a specific bus.
int stop ()
Stop the driver.
int reset ()
Reset the driver.
int info ()
Print a little info about the driver.
Variables
ETSAirspeed * g_dev = nullptr
Detailed Description
Local functions in support of the shell command.
Function Documentation
int ets_airspeed::info ()
Print a little info about the driver.
Print a little info about the driver.
Definition at line 820 of file bmp280.cpp.
References lps22hb::bus_options, bmp280::bus_options, mpl3115a2::bus_options, lps25h::bus_options, ms5611::bus_options, lps22hb::lps22hb_bus_option::dev, mpl3115a2::mpl3115a2_bus_option::dev, lps25h::lps25h_bus_option::dev, ms5611::ms5611_bus_option::dev, ACCELSIM::devIOCTL(), lps22hb::lps22hb_bus_option::devpath, mpl3115a2::mpl3115a2_bus_option::devpath, lps25h::lps25h_bus_option::devpath, ms5611::ms5611_bus_option::devpath, errx, gyrosim::g_dev_sim, DfMPU6050Wrapper::info(), DfLsm9ds1Wrapper::info(), DfMpu9250Wrapper::info(), NUM_BUS_OPTIONS, DfAK8963Wrapper::print_calibration(), VideoDevice::print_info(), ADIS16477::print_info(), LidarLite::print_info(), DfBebopBusWrapper::print_info(), AirspeedSim::print_info(), TFMINI::print_info(), SF0X::print_info(), LPS22HB::print_info(), HC_SR04::print_info(), SF1XX::print_info(), GPSSIM::print_info(), LSM303AGR::print_info(), MB12XX::print_info(), SRF02::print_info(), TERARANGER::print_info(), MPL3115A2::print_info(), PX4FLOW::print_info(), PMW3901::print_info(), VL53LXX::print_info(), BMA180::print_info(), MS5611::print_info(), FXOS8701CQ::print_info(), ADIS16448::print_info(), LPS25H::print_info(), L3GD20::print_info(), FXAS21002C::print_info(), LSM303D::print_info(), PX4_DEBUG, PX4_ERR, PX4_ERROR, PX4_INFO, PX4_OK, PX4_WARN, and warnx.
Referenced by accelsim_main(), adis16448_main(), adis16477_main(), bebop_flow_main(), bma180_main(), bmp280_main(), df_ak8963_wrapper_main(), df_bebop_bus_wrapper_main(), df_bebop_rangefinder_wrapper_main(), df_bmp280_wrapper_main(), df_hmc5883_wrapper_main(), df_isl29501_wrapper_main(), df_lsm9ds1_wrapper_main(), df_ltc2946_wrapper_main(), df_mpu6050_wrapper_main(), df_mpu9250_wrapper_main(), df_ms5607_wrapper_main(), df_ms5611_wrapper_main(), df_trone_wrapper_main(), fxas21002c_main(), fxos8701cq_main(), gpssim_main(), gyrosim_main(), hardfault_dowrite(), hc_sr04_main(), l3gd20_main(), ll40ls_main(), lps22hb_main(), lps25h_main(), lsm303agr_main(), lsm303d_main(), mb12xx_main(), measairspeedsim_main(), mpl3115a2_main(), ms5611_main(), pmw3901_main(), DfBebopBusWrapper::print_info(), px4flow_main(), sf0x_main(), sf1xx_main(), spektrum_rc_main(), srf02_main(), teraranger_main(), tfmini_main(), vl53lxx_main(), and uORBTest::UnitTest::~UnitTest().
int ets_airspeed::reset ()
Reset the driver.
Definition at line 341 of file ets_airspeed.cpp.
Referenced by ets_airspeed_main().
int ets_airspeed::start ()
Attempt to start driver on all available I2C busses.
This function will return as soon as the first sensor is detected on one of the available busses or if no sensors are detected.
Definition at line 257 of file ets_airspeed.cpp.
Referenced by ets_airspeed_main().
int ets_airspeed::start_bus (int i2c_bus)
Start the driver on a specific bus.
This function only returns if the sensor is up and running or could not be detected successfully.
Definition at line 276 of file ets_airspeed.cpp.
References AIRSPEED0_DEVICE_PATH, ETSAirspeed::ETSAirspeed(), fd, g_dev, Airspeed::init(), OK, PX4_ERR, PX4_ERROR, px4_ioctl(), PX4_OK, px4_open(), SENSOR_POLLRATE_DEFAULT, and SENSORIOCSPOLLRATE.
Referenced by ets_airspeed_main(), and spektrum_rc::start().
int ets_airspeed::stop ()
Stop the driver.
Definition at line 323 of file ets_airspeed.cpp.
References g_dev, PX4_ERR, PX4_ERROR, and PX4_OK.
Referenced by ets_airspeed_main().
Variable Documentation
ETSAirspeed* ets_airspeed::g_dev = nullptr
Definition at line 240 of file ets_airspeed.cpp.
Referenced by ToneAlarm::devWrite(), do_test(), ToneAlarm::frequency_to_divisor(), PX4IO::PX4IO(), px4io_main(), PX4IO::set_update_rate(), start_bus(), stop(), PX4IO::task_main_trampoline(), tone_alarm_main(), ToneAlarm::write(), and PX4IO::~PX4IO().