PX4 Firmware: df_hmc5883_wrapper Namespace Reference
df_hmc5883_wrapper Namespace Reference
Functions
int start (enum Rotation rotation, const char *path)
int stop ()
Stop the driver.
int info ()
Print a little info about the driver.
void usage ()
Prints info about the driver argument usage.
Variables
DfHmc5883Wrapper * g_dev = nullptr
Function Documentation
int df_hmc5883_wrapper::info ()
Print a little info about the driver.
Print a little info about the driver.
Definition at line 386 of file df_hmc5883_wrapper.cpp.
References PX4_DEBUG, and PX4_ERR.
Referenced by df_hmc5883_wrapper_main().
int df_hmc5883_wrapper::start (enum Rotation rotation, const char * path)
Definition at line 332 of file df_hmc5883_wrapper.cpp.
References DfHmc5883Wrapper::DfHmc5883Wrapper(), PX4_ERR, and DfHmc5883Wrapper::start().
Referenced by df_hmc5883_wrapper_main().
int df_hmc5883_wrapper::stop ()
Stop the driver.
Stop the driver.
Definition at line 363 of file df_hmc5883_wrapper.cpp.
References g_dev, PX4_ERR, and DfHmc5883Wrapper::stop().
Referenced by df_hmc5883_wrapper_main().
void df_hmc5883_wrapper::usage (void)
Prints info about the driver argument usage.
Prints info about the driver argument usage.
Definition at line 399 of file df_hmc5883_wrapper.cpp.
References PX4_INFO.
Referenced by df_hmc5883_wrapper_main().
Variable Documentation
DfHmc5883Wrapper* df_hmc5883_wrapper::g_dev = nullptr
Definition at line 325 of file df_hmc5883_wrapper.cpp.
Referenced by stop().