PX4 Firmware: PWMIN Class Reference
PWMIN Class Reference
Public Member Functions
PWMIN ()
virtual ~PWMIN ()
virtual int init ()
Initialise the driver and make it ready for use.
virtual int open (struct file *filp)
virtual ssize_t read (struct file *filp, char *buffer, size_t buflen)
virtual int ioctl (struct file *filp, int cmd, unsigned long arg)
void publish (uint16_t status, uint32_t period, uint32_t pulse_width)
void print_info (void)
void hard_reset ()
Private Member Functions
void _timer_init (void)
void _turn_on ()
void _turn_off ()
void _freeze_test ()
Private Member Functions inherited from device::CDev
CDev (const char *name, const char *devname)
Constructor.
virtual ~CDev ()
virtual int open (file_t *filep)
Handle an open of the device.
virtual int close (file_t *filep)
Handle a close of the device.
virtual ssize_t read (file_t *filep, char *buffer, size_t buflen)
Perform a read from the device.
virtual ssize_t write (file_t *filep, const char *buffer, size_t buflen)
Perform a write to the device.
virtual off_t seek (file_t *filep, off_t offset, int whence)
Perform a logical seek operation on the device.
virtual int ioctl (file_t *filep, int cmd, unsigned long arg)
Perform an ioctl operation on the device.
virtual int poll (file_t *filep, px4_pollfd_struct_t *fds, bool setup)
Perform a poll setup/teardown operation.
virtual pollevent_t poll_state (file_t *filep)
Check the current state of the device for poll events from the perspective of the file.
virtual void poll_notify (pollevent_t events)
Report new poll events.
virtual void poll_notify_one (px4_pollfd_struct_t *fds, pollevent_t events)
Internal implementation of poll_notify.
virtual int open_first (file_t *filep)
Notification of the first open.
virtual int close_last (file_t *filep)
Notification of the last close.
virtual int register_class_devname (const char *class_devname)
Register a class device name, automatically adding device class instance suffix if need be.
virtual int unregister_class_devname (const char *class_devname, unsigned class_instance)
Register a class device name, automatically adding device class instance suffix if need be.
const char * get_devname ()
Get the device name.
void lock ()
Take the driver lock.
void unlock ()
Release the driver lock.
Private Member Functions inherited from device::Device
virtual ~Device ()=default
Destructor.
virtual int read (unsigned address, void *data, unsigned count)
Read directly from the device.
virtual int write (unsigned address, void *data, unsigned count)
Write directly to the device.
virtual int ioctl (unsigned operation, unsigned &arg)
Perform a device-specific operation.
uint8_t get_device_bus ()
Return the bus ID the device is connected to.
DeviceBusType get_device_bus_type ()
Return the bus type the device is connected to.
uint8_t get_device_address ()
Return the bus address of the device.
void set_device_address (int address)
void set_device_type (uint8_t devtype)
Set the device type.
virtual bool external ()
Device (const char *name)
Device (DeviceBusType bus_type, uint8_t bus, uint8_t address, uint8_t devtype=0)
Device (const Device &)=delete
Device & operator= (const Device &)=delete
Device (Device &&)=delete
Device & operator= (Device &&)=delete
Private Attributes
uint32_t _error_count
uint32_t _pulses_captured
uint32_t _last_period
uint32_t _last_width
hrt_abstime _last_poll_time
hrt_abstime _last_read_time
ringbuffer::RingBuffer * _reports
bool _timer_started
hrt_call _hard_reset_call
hrt_call _freeze_test_call
Private Attributes inherited from device::CDev
px4_sem_t _lock
lock to protect access to all class members (also for derived classes)
bool _pub_blocked {false}
true if publishing should be blocked
Private Attributes inherited from device::Device
union DeviceId _device_id
device identifier information
const char * _name
driver name
bool _debug_enabled {false}
if true, debug messages are printed
Additional Inherited Members
Private Types inherited from device::Device
enum DeviceBusType { DeviceBusType_UNKNOWN = 0, DeviceBusType_I2C = 1, DeviceBusType_SPI = 2, DeviceBusType_UAVCAN = 3 }
Device bus types for DEVID.
Static Private Attributes inherited from device::CDev
static const px4_file_operations_t fops = {}
Pointer to the default cdev file operations table; useful for registering clone devices etc.
Detailed Description
Definition at line 228 of file pwm_input.cpp.
Constructor & Destructor Documentation
PWMIN::PWMIN ()
Definition at line 273 of file pwm_input.cpp.
Referenced by pwmin_start().
PWMIN::~PWMIN () virtual
Definition at line 284 of file pwm_input.cpp.
References _reports.
Member Function Documentation
void PWMIN::_freeze_test () private
Definition at line 382 of file pwm_input.cpp.
References _last_poll_time, _last_read_time, hard_reset(), hrt_elapsed_time(), TIMEOUT_POLL, and TIMEOUT_READ.
Referenced by init().
void PWMIN::_timer_init (void) private
Definition at line 319 of file pwm_input.cpp.
References _timer_started, GPIO_PWM_IN, GPIO_VDD_RANGEFINDER_EN, pwmin_tim_isr(), rARR, rCCER, rCCMR1, rCCMR2, rCR1, rCR2, rDCR, rDIER, rEGR, rPSC, and rSMCR.
Referenced by ioctl(), and open().
void PWMIN::_turn_off () private
Definition at line 399 of file pwm_input.cpp.
References GPIO_VDD_RANGEFINDER_EN.
Referenced by hard_reset().
void PWMIN::_turn_on () private
Definition at line 392 of file pwm_input.cpp.
References GPIO_VDD_RANGEFINDER_EN.
Referenced by hard_reset().
void PWMIN::hard_reset ()
Definition at line 406 of file pwm_input.cpp.
References _hard_reset_call, _turn_off(), _turn_on(), and hrt_call_after().
Referenced by _freeze_test(), ioctl(), and pwmin_reset().
int PWMIN::init () virtual
Initialise the driver and make it ready for use.
Returns
OK if the driver initialized OK, negative errno otherwise;
Reimplemented from device::CDev.
Definition at line 298 of file pwm_input.cpp.
References _freeze_test(), _freeze_test_call, _reports, hrt_call_every(), lis3mdl::init(), OK, and TIMEOUT_POLL.
Referenced by pwmin_start().
int PWMIN::ioctl (struct file * filp, int cmd, unsigned long arg) virtual
Definition at line 437 of file pwm_input.cpp.
References _reports, _timer_init(), hard_reset(), OK, SENSORIOCRESET, and SENSORIOCSQUEUEDEPTH.
Referenced by pwmin_reset().
int PWMIN::open (struct file * filp) virtual
Definition at line 417 of file pwm_input.cpp.
References _timer_init(), _timer_started, and OK.
Referenced by pwmin_reset(), and pwmin_test().
void PWMIN::print_info (void)
Definition at line 527 of file pwm_input.cpp.
References _last_period, _last_width, _pulses_captured, and _timer_started.
Referenced by pwmin_info().
void PWMIN::publish (uint16_t status, uint32_t period, uint32_t pulse_width)
Definition at line 505 of file pwm_input.cpp.
References _error_count, _last_poll_time, _reports, pwm_input_s::error_count, hrt_absolute_time(), pwm_input_s::period, pwm_input_s::pulse_width, and pwm_input_s::timestamp.
Referenced by pwmin_tim_isr().
ssize_t PWMIN::read (struct file * filp, char * buffer, size_t buflen) virtual
Definition at line 478 of file pwm_input.cpp.
References _last_read_time, _reports, and hrt_absolute_time().
Referenced by pwmin_test().
Member Data Documentation
uint32_t PWMIN::_error_count private
Definition at line 244 of file pwm_input.cpp.
Referenced by publish().
hrt_call PWMIN::_freeze_test_call private
Definition at line 254 of file pwm_input.cpp.
Referenced by init().
hrt_call PWMIN::_hard_reset_call private
Definition at line 253 of file pwm_input.cpp.
Referenced by hard_reset().
uint32_t PWMIN::_last_period private
Definition at line 246 of file pwm_input.cpp.
Referenced by print_info().
hrt_abstime PWMIN::_last_poll_time private
Definition at line 248 of file pwm_input.cpp.
Referenced by _freeze_test(), and publish().
hrt_abstime PWMIN::_last_read_time private
Definition at line 249 of file pwm_input.cpp.
Referenced by _freeze_test(), and read().
uint32_t PWMIN::_last_width private
Definition at line 247 of file pwm_input.cpp.
Referenced by print_info().
uint32_t PWMIN::_pulses_captured private
Definition at line 245 of file pwm_input.cpp.
Referenced by print_info().
ringbuffer::RingBuffer* PWMIN::_reports private
Definition at line 250 of file pwm_input.cpp.
Referenced by init(), ioctl(), publish(), read(), and ~PWMIN().
bool PWMIN::_timer_started private
Definition at line 251 of file pwm_input.cpp.
Referenced by _timer_init(), open(), and print_info().
The documentation for this class was generated from the following file:
src/drivers/pwm_input/pwm_input.cpp