PX4 Firmware: uORB::PublicationMulti< T > Class Template Reference
uORB::PublicationMulti< T > Class Template Reference
Base publication multi wrapper class.
#include <PublicationMulti.hpp>
Public Member Functions
PublicationMulti (const orb_metadata *meta, uint8_t priority=ORB_PRIO_DEFAULT)
Constructor.
~PublicationMulti ()
bool publish (const T &data)
Publish the struct.
Protected Attributes
const orb_metadata * _meta
orb_advert_t _handle {nullptr}
const uint8_t _priority
Detailed Description
template<typename T>
class uORB::PublicationMulti< T >
Base publication multi wrapper class.
Definition at line 52 of file PublicationMulti.hpp.
Constructor & Destructor Documentation
PublicationMulti()
template<typename T> uORB::PublicationMulti< T >::PublicationMulti (const orb_metadata * meta, uint8_t priority = ORB_PRIO_DEFAULT) inline
Constructor.
Parameters
meta The uORB metadata (usually from the ORB_ID() macro) for the topic.
priority The priority for multi pub/sub, 0 means don't publish as multi
Definition at line 62 of file PublicationMulti.hpp.
~PublicationMulti()
template<typename T> uORB::PublicationMulti< T >::~PublicationMulti () inline
Definition at line 67 of file PublicationMulti.hpp.
Member Function Documentation
publish()
template<typename T> bool uORB::PublicationMulti< T >::publish (const T & data) inline
Publish the struct.
Parameters
data The uORB message struct we are updating.
Definition at line 73 of file PublicationMulti.hpp.
Referenced by RCInput::cycle(), MavlinkTimesync::handle_message(), MavlinkReceiver::handle_message_distance_sensor(), MavlinkReceiver::handle_message_hil_optical_flow(), MavlinkReceiver::handle_message_hil_sensor(), MavlinkReceiver::handle_message_hil_state_quaternion(), MavlinkReceiver::handle_message_manual_control(), MavlinkReceiver::handle_message_optical_flow_rad(), MavlinkReceiver::handle_message_ping(), MavlinkReceiver::handle_message_radio_status(), MavlinkReceiver::handle_message_rc_channels_override(), PX4IO::io_publish_pwm_outputs(), PX4IO::io_publish_raw_rc(), UavcanEscController::orb_pub_timer_cb(), UavcanGnssBridge::process_fixx(), Ekf2::publish_wind_estimate(), MixingOutput::publishMixerStatus(), MulticopterRateControl::Run(), FixedwingAttitudeControl::Run(), PAW3902::Run(), PMW3901::Run(), AirspeedModule::select_airspeed_and_publish(), MixingOutput::setAndPublishActuatorOutputs(), and uORB::PublicationMultiData< sensor_baro_s >::update().
Member Data Documentation
_handle
template<typename T> orb_advert_t uORB::PublicationMulti< T >::_handle {nullptr} protected
Definition at line 94 of file PublicationMulti.hpp.
Referenced by uORB::PublicationMulti< rate_ctrl_status_s >::publish(), and uORB::PublicationMulti< rate_ctrl_status_s >::~PublicationMulti().
_meta
template<typename T> const orb_metadata* uORB::PublicationMulti< T >::_meta protected
Definition at line 92 of file PublicationMulti.hpp.
Referenced by uORB::PublicationMulti< rate_ctrl_status_s >::publish().
_priority
template<typename T> const uint8_t uORB::PublicationMulti< T >::_priority protected
Definition at line 96 of file PublicationMulti.hpp.
Referenced by uORB::PublicationMulti< rate_ctrl_status_s >::publish().
The documentation for this class was generated from the following file:
src/modules/uORB/PublicationMulti.hpp