PX4 Firmware: px4::ReplayEkf2 Class Reference
px4::ReplayEkf2 Class Reference
replay specialization for Ekf2 replay
#include <replay.hpp>
Protected Member Functions
void onEnterMainLoop () override
called when entering the main replay loop
void onExitMainLoop () override
called when exiting the main replay loop
uint64_t handleTopicDelay (uint64_t next_file_time, uint64_t timestamp_offset) override
handle delay until topic can be published.
bool handleTopicUpdate (Subscription &sub, void *data, std::ifstream &replay_file) override
handle ekf2 topic publication in ekf2 replay mode
void onSubscriptionAdded (Subscription &sub, uint16_t msg_id) override
called when a new subscription is added
Protected Member Functions inherited from px4::Replay
bool publishTopic (Subscription &sub, void *data)
publish an orb topic
void readTopicDataToBuffer (const Subscription &sub, std::ifstream &replay_file)
read a topic from the file (offset given by the subscription) into _read_buffer
bool nextDataMessage (std::ifstream &file, Subscription &subscription, int msg_id)
Find next data message for this subscription, starting with the stored file offset.
Private Member Functions
bool publishEkf2Topics (const ekf2_timestamps_s &ekf2_timestamps, std::ifstream &replay_file)
bool findTimestampAndPublish (uint64_t timestamp, uint16_t msg_id, std::ifstream &replay_file)
find the next message for a subscription that matches a given timestamp and publish it
Private Attributes
int _vehicle_attitude_sub = -1
uint16_t _airspeed_msg_id = msg_id_invalid
uint16_t _distance_sensor_msg_id = msg_id_invalid
uint16_t _gps_msg_id = msg_id_invalid
uint16_t _optical_flow_msg_id = msg_id_invalid
uint16_t _sensor_combined_msg_id = msg_id_invalid
uint16_t _vehicle_air_data_msg_id = msg_id_invalid
uint16_t _vehicle_magnetometer_msg_id = msg_id_invalid
uint16_t _vehicle_vision_attitude_msg_id = msg_id_invalid
uint16_t _vehicle_vision_position_msg_id = msg_id_invalid
int _topic_counter = 0
Static Private Attributes
static constexpr uint16_t msg_id_invalid = 0xffff
Additional Inherited Members
Public Member Functions inherited from px4::Replay
Replay ()=default
virtual ~Replay ()
void run () override
Static Public Member Functions inherited from px4::Replay
static int task_spawn (int argc, char *argv[])
static Replay * instantiate (int argc, char *argv[])
static int custom_command (int argc, char *argv[])
static int print_usage (const char *reason=nullptr)
static int applyParams (bool quiet)
Apply the parameters from the log.
static void setupReplayFile (const char *file_name)
Tell the replay module that we want to use replay mode.
static bool isSetup ()
Static Protected Member Functions inherited from px4::Replay
static bool findFieldOffset (const std::string &format, const std::string &field_name, int &offset, int &field_size)
Find the offset & field size in bytes for a given field name.
Protected Attributes inherited from px4::Replay
std::vector< Subscription * > _subscriptions
std::vector< uint8_t > _read_buffer
Detailed Description
replay specialization for Ekf2 replay
Definition at line 273 of file replay.hpp.
Member Function Documentation
bool px4::ReplayEkf2::findTimestampAndPublish (uint64_t timestamp, uint16_t msg_id, std::ifstream & replay_file) private
find the next message for a subscription that matches a given timestamp and publish it
Parameters
timestamp in 0.1 ms
msg_id
replay_file file currently replayed (file seek position should be considered arbitrary after this call)
Returns
true if timestamp found and published
Definition at line 1056 of file replay_main.cpp.
References px4::Replay::_read_buffer, px4::Replay::_subscriptions, px4::Replay::Subscription::error_counter, px4::Replay::Subscription::next_timestamp, px4::Replay::nextDataMessage(), orb_metadata::o_name, px4::Replay::Subscription::orb_meta, px4::Replay::publishTopic(), PX4_DEBUG, and px4::Replay::readTopicDataToBuffer().
uint64_t px4::ReplayEkf2::handleTopicDelay (uint64_t next_file_time, uint64_t timestamp_offset) override protected virtual
handle delay until topic can be published.
Parameters
next_file_timestamp timestamp of next message to publish
timestamp_offset offset between file start time and replay start time
Returns
timestamp that the message to publish should have
Reimplemented from px4::Replay.
Definition at line 1121 of file replay_main.cpp.
bool px4::ReplayEkf2::handleTopicUpdate (Subscription & sub, void * data, std::ifstream & replay_file) override protected virtual
handle ekf2 topic publication in ekf2 replay mode
Parameters
sub
data
replay_file file currently replayed (file seek position should be considered arbitrary after this call)
Returns
true if published, false otherwise
Reimplemented from px4::Replay.
Definition at line 932 of file replay_main.cpp.
References orb_metadata::o_size, orb_copy(), ORB_ID, px4::Replay::Subscription::orb_meta, px4::Replay::publishTopic(), PX4_ERR, px4_poll(), PX4_WARN, and usleep().
void px4::ReplayEkf2::onEnterMainLoop () override protected virtual
called when entering the main replay loop
Reimplemented from px4::Replay.
Definition at line 1086 of file replay_main.cpp.
References ORB_ID, and orb_subscribe().
void px4::ReplayEkf2::onExitMainLoop () override protected virtual
called when exiting the main replay loop
Reimplemented from px4::Replay.
Definition at line 1091 of file replay_main.cpp.
References px4::Replay::_subscriptions, px4::Replay::Subscription::error_counter, name, orb_unsubscribe(), px4::Replay::Subscription::publication_counter, and PX4_INFO.
void px4::ReplayEkf2::onSubscriptionAdded (Subscription & sub, uint16_t msg_id) override protected virtual
called when a new subscription is added
Reimplemented from px4::Replay.
Definition at line 978 of file replay_main.cpp.
References px4::Replay::Subscription::ignored, px4::Replay::Subscription::multi_id, ORB_ID, and px4::Replay::Subscription::orb_meta.
bool px4::ReplayEkf2::publishEkf2Topics (const ekf2_timestamps_s & ekf2_timestamps, std::ifstream & replay_file) private
Definition at line 1017 of file replay_main.cpp.
References px4::Replay::_read_buffer, px4::Replay::_subscriptions, ekf2_timestamps_s::airspeed_timestamp_rel, ekf2_timestamps_s::distance_sensor_timestamp_rel, ekf2_timestamps_s::gps_timestamp_rel, ekf2_timestamps_s::optical_flow_timestamp_rel, px4::Replay::publishTopic(), px4::Replay::readTopicDataToBuffer(), ekf2_timestamps_s::timestamp, ekf2_timestamps_s::vehicle_air_data_timestamp_rel, ekf2_timestamps_s::vehicle_magnetometer_timestamp_rel, ekf2_timestamps_s::vision_attitude_timestamp_rel, and ekf2_timestamps_s::vision_position_timestamp_rel.
Member Data Documentation
uint16_t px4::ReplayEkf2::_airspeed_msg_id = msg_id_invalid private
Definition at line 311 of file replay.hpp.
uint16_t px4::ReplayEkf2::_distance_sensor_msg_id = msg_id_invalid private
Definition at line 312 of file replay.hpp.
uint16_t px4::ReplayEkf2::_gps_msg_id = msg_id_invalid private
Definition at line 313 of file replay.hpp.
uint16_t px4::ReplayEkf2::_optical_flow_msg_id = msg_id_invalid private
Definition at line 314 of file replay.hpp.
uint16_t px4::ReplayEkf2::_sensor_combined_msg_id = msg_id_invalid private
Definition at line 315 of file replay.hpp.
int px4::ReplayEkf2::_topic_counter = 0 private
Definition at line 321 of file replay.hpp.
uint16_t px4::ReplayEkf2::_vehicle_air_data_msg_id = msg_id_invalid private
Definition at line 316 of file replay.hpp.
int px4::ReplayEkf2::_vehicle_attitude_sub = -1 private
Definition at line 307 of file replay.hpp.
uint16_t px4::ReplayEkf2::_vehicle_magnetometer_msg_id = msg_id_invalid private
Definition at line 317 of file replay.hpp.
uint16_t px4::ReplayEkf2::_vehicle_vision_attitude_msg_id = msg_id_invalid private
Definition at line 318 of file replay.hpp.
uint16_t px4::ReplayEkf2::_vehicle_vision_position_msg_id = msg_id_invalid private
Definition at line 319 of file replay.hpp.
constexpr uint16_t px4::ReplayEkf2::msg_id_invalid = 0xffff static private
Definition at line 309 of file replay.hpp.
The documentation for this class was generated from the following files:
src/modules/replay/replay.hpp
src/modules/replay/replay_main.cpp