PX4 Firmware: src/systemcmds/config/config.c File Reference
config.c File Reference
#include <px4_config.h>
#include <px4_log.h>
#include <px4_module.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <stdbool.h>
#include <unistd.h>
#include <fcntl.h>
#include <sys/stat.h>
#include <arch/board/board.h>
#include <drivers/drv_gyro.h>
#include <drivers/drv_accel.h>
#include <drivers/drv_mag.h>
#include <drivers/drv_device.h>
#include <parameters/param.h>
Functions
__EXPORT int config_main (int argc, char *argv[])
static int do_gyro (int argc, char *argv[])
static int do_accel (int argc, char *argv[])
static int do_mag (int argc, char *argv[])
static int do_device (int argc, char *argv[])
static void print_usage (void)
Detailed Description
Author
Lorenz Meier lm@in.nosp@m.f.et.nosp@m.hz.ch
Julian Oes joes@.nosp@m.stud.nosp@m.ent.e.nosp@m.thz..nosp@m.ch
config tool. Takes the device name as the first parameter.
Definition in file config.c.
Function Documentation
int config_main (int argc, char * argv[])
Definition at line 72 of file config.c.
References do_accel(), do_device(), do_gyro(), do_mag(), and print_usage().
static int do_accel (int argc, char * argv[]) static
Definition at line 301 of file config.c.
References ACCELIOCGRANGE, ACCELIOCGSAMPLERATE, ACCELIOCSRANGE, ACCELIOCSSAMPLERATE, fd, param_find(), param_get(), print_usage(), PX4_ERR, PX4_INFO, SENSORIOCGPOLLRATE, and SENSORIOCSPOLLRATE.
Referenced by config_main().
static int do_device (int argc, char * argv[]) static
Definition at line 118 of file config.c.
References fd, print_usage(), and PX4_ERR.
Referenced by config_main().
static int do_gyro (int argc, char * argv[]) static
Definition at line 167 of file config.c.
References fd, GYROIOCGRANGE, GYROIOCGSAMPLERATE, GYROIOCSRANGE, GYROIOCSSAMPLERATE, param_find(), param_get(), print_usage(), PX4_ERR, PX4_INFO, SENSORIOCGPOLLRATE, and SENSORIOCSPOLLRATE.
Referenced by config_main().
static int do_mag (int argc, char * argv[]) static
Definition at line 234 of file config.c.
References fd, MAGIOCGRANGE, MAGIOCGSAMPLERATE, MAGIOCSRANGE, MAGIOCSSAMPLERATE, param_find(), param_get(), print_usage(), PX4_ERR, PX4_INFO, SENSORIOCGPOLLRATE, and SENSORIOCSPOLLRATE.
Referenced by config_main().
static void print_usage (void) static
Definition at line 95 of file config.c.
References PRINT_MODULE_DESCRIPTION(), PRINT_MODULE_USAGE_ARG(), PRINT_MODULE_USAGE_COMMAND_DESCR(), PRINT_MODULE_USAGE_NAME(), and PRINT_MODULE_USAGE_PARAM_COMMENT().
Referenced by config_main(), do_accel(), do_device(), do_gyro(), and do_mag().