PX4 Firmware: pmw3902 Namespace Reference
pmw3902 Namespace Reference
Local functions in support of the shell command.
Functions
void start (int spi_bus)
Start the driver.
void stop ()
Stop the driver.
void test ()
Perform some basic functional tests on the driver; make sure we can collect data from the sensor in polled and automatic modes.
void reset ()
Reset the driver.
void info ()
Print a little info about the driver.
void usage ()
Print a little info about how to start/stop/use the driver.
Variables
PAW3902 * g_dev
Detailed Description
Local functions in support of the shell command.
Function Documentation
info()
void pmw3902::info ()
Print a little info about the driver.
Definition at line 105 of file paw3902_main.cpp.
References errx, and PAW3902::print_info().
Referenced by paw3902_main().
reset()
void pmw3902::reset ()
Reset the driver.
Definition at line 319 of file ets_airspeed.cpp.
start()
void pmw3902::start (int spi_bus)
Start the driver.
Definition at line 56 of file paw3902_main.cpp.
References errx, g_dev, PAW3902::init(), and OK.
Referenced by paw3902_main().
stop()
void pmw3902::stop ()
Stop the driver.
Stop the driver.
Definition at line 88 of file paw3902_main.cpp.
References errx, and g_dev.
Referenced by paw3902_main().
test()
void pmw3902::test ()
Perform some basic functional tests on the driver; make sure we can collect data from the sensor in polled and automatic modes.
Definition at line 554 of file mb12xx.cpp.
usage()
void pmw3902::usage (void)
Print a little info about how to start/stop/use the driver.
Prints info about the driver argument usage.
Definition at line 120 of file paw3902_main.cpp.
References paw3902_main().
Referenced by paw3902_main().
Variable Documentation
g_dev
PAW3902* pmw3902::g_dev
Definition at line 42 of file paw3902_main.cpp.
Referenced by start(), and stop().