PX4 Firmware: src/drivers/optical_flow/pmw3901/pmw3901_main.cpp File Reference
pmw3901_main.cpp File Reference
#include "PMW3901.hpp"
Namespaces
pmw3901
Local functions in support of the shell command.
Functions
__EXPORT int pmw3901_main (int argc, char *argv[])
void pmw3901::start (int spi_bus)
Start the driver.
void pmw3901::stop ()
Stop the driver.
void pmw3901::test ()
Perform some basic functional tests on the driver; make sure we can collect data from the sensor in polled and automatic modes.
void pmw3901::reset ()
Reset the driver.
void pmw3901::info ()
Print a little info about the driver.
void pmw3901::usage ()
Print a little info about how to start/stop/use the driver.
Variables
PMW3901 * pmw3901::g_dev
Function Documentation
pmw3901_main()
int pmw3901_main (int argc, char * argv[])
Definition at line 134 of file pmw3901_main.cpp.
References pmw3901::info(), pmw3901::start(), pmw3901::stop(), and pmw3901::usage().