PX4 Firmware: lis3mdl Namespace Reference
lis3mdl Namespace Reference
Classes
struct lis3mdl_bus_option
Functions
lis3mdl_bus_option & find_bus (LIS3MDL_BUS bus_id)
Finds a bus structure for a bus_id.
int calibrate (LIS3MDL_BUS bus_id)
Calibrate and self test.
int info (LIS3MDL_BUS bus_id)
Prints info about the driver.
bool init (LIS3MDL_BUS bus_id)
Initializes the driver – sets defaults and starts a cycle.
bool reset (LIS3MDL_BUS bus_id)
Resets the driver.
bool start_bus (struct lis3mdl_bus_option &bus, Rotation rotation)
Starts the driver for a specific bus option.
int start (LIS3MDL_BUS bus_id, Rotation rotation)
Starts the driver.
int stop ()
Stop the driver.
bool test (LIS3MDL_BUS bus_id)
Perform some basic functional tests on the driver; make sure we can collect data from the sensor in polled and automatic modes.
void usage ()
Prints info about the driver argument usage.
Variables
struct lis3mdl::lis3mdl_bus_option bus_options []
Function Documentation
int lis3mdl::calibrate (LIS3MDL_BUS bus_id)
Calibrate and self test.
Self test feature cannot be used to calculate scale.
SELF TEST OPERATION Note: To check the LIS3MDL for proper operation, a self test feature is incorporated : sensor offset straps are excited to create a nominal field strength (bias field) to be measured. To implement self test, the least significant bits (MS1 and MS0) of configuration register A are changed from 00 to 01 (positive bias). A few measurements are taken and stored with and without the additional magnetic field. According to ST datasheet, those values must stay between thresholds in order to pass the self test.
Definition at line 49 of file lis3mdl_main.cpp.
References lis3mdl::lis3mdl_bus_option::devpath, fd, bmp280::find_bus(), MAGIOCCALIBRATE, OK, path, and PX4_WARN.
Referenced by lis3mdl_main().
struct lis3mdl::lis3mdl_bus_option & lis3mdl::find_bus (LIS3MDL_BUS bus_id)
Finds a bus structure for a bus_id.
Definition at line 395 of file lis3mdl_main.cpp.
References bus_options, errx, LIS3MDL_BUS_ALL, and NUM_BUS_OPTIONS.
int lis3mdl::info (LIS3MDL_BUS bus_id)
Prints info about the driver.
Definition at line 72 of file lis3mdl_main.cpp.
References lis3mdl::lis3mdl_bus_option::bus_id, lis3mdl::lis3mdl_bus_option::dev, lis3mdl::lis3mdl_bus_option::devpath, bmp280::find_bus(), LIS3MDL::print_info(), and PX4_WARN.
Referenced by lis3mdl_main().
bool lis3mdl::init (LIS3MDL_BUS bus_id)
Initializes the driver – sets defaults and starts a cycle.
Definition at line 82 of file lis3mdl_main.cpp.
References lis3mdl::lis3mdl_bus_option::devpath, errx, fd, bmp280::find_bus(), path, PX4_INFO, SENSOR_POLLRATE_DEFAULT, and SENSORIOCSPOLLRATE.
Referenced by LED::_measure(), UavcanNode::cb_beginfirmware_update(), PX4IO::detect(), BMI160_gyro::init(), px4::init(), MPU9250_gyro::init(), ADIS16477_gyro::init(), Airspeed::init(), LED::init(), LidarLitePWM::init(), OcpocADC::init(), MPL3115A2_I2C::init(), ADIS16477::init(), BBBlueADC::init(), RGBLED_PWM::init(), __EXPORT::I2C::init(), __EXPORT::SPI::init(), NavioADC::init(), AirspeedSim::init(), LidarLiteI2C::init(), BAROSIM::init(), AEROFC_ADC::init(), OREOLED::init(), TFMINI::init(), SF0X::init(), RGBLED::init(), SF1XX::init(), ACCELSIM::init(), HC_SR04::init(), LPS22HB::init(), GPSSIM::init(), BMP280::init(), LSM303AGR::init(), IRLOCK::init(), MPU9250_mag::init(), SRF02::init(), MB12XX::init(), TERARANGER::init(), TAP_ESC::init(), ulanding::Radar::init(), PX4FLOW::init(), MPL3115A2::init(), PMW3901::init(), VL53LXX::init(), leddar_one::init(), UavcanEsc::init(), PCA9685::init(), LIS3MDL::init(), px4::bst::BST::init(), GYROSIM::init(), BMA180::init(), MS5611::init(), PX4IO::init(), HMC5883::init(), MPU6000::init(), MK::init(), BlinkM::init(), UavcanNode::init(), BMI055_gyro::init(), PX4FMU::init(), BMI055_accel::init(), FXOS8701CQ::init(), SyslinkBridge::init(), ADIS16448::init(), IST8310::init(), SyslinkMemory::init(), LPS25H::init(), BMM150::init(), L3GD20::init(), BATT_SMBUS::init(), ToneAlarm::init(), FXAS21002C::init(), LSM303D::init(), PWMIN::init(), MPU9250::init(), BMI160::init(), GYROSIM_gyro::init(), ADIS16448_gyro::init(), FXOS8701CQ_mag::init(), MPU6000_gyro::init(), ADIS16448_mag::init(), LSM303D_mag::init(), lis3mdl_main(), main(), IridiumSBD::main_loop(), MD25::MD25(), MK::mk_check_for_blctrl(), PWMSim::PWMSim(), RGBLED::start(), adis16477::start(), DfLtc2946Wrapper::start(), DfBebopBusWrapper::start(), DfMS5607Wrapper::start(), DfAK8963Wrapper::start(), DfBebopRangeFinderWrapper::start(), DfTROneWrapper::start(), DfISL29501Wrapper::start(), DfMPU6050Wrapper::start(), DfLsm9ds1Wrapper::start(), AttitudeEstimatorQ::update(), and ToneAlarm::~ToneAlarm().
bool lis3mdl::reset (LIS3MDL_BUS bus_id)
Resets the driver.
Definition at line 250 of file lis3mdl_main.cpp.
References lis3mdl::lis3mdl_bus_option::devpath, fd, bmp280::find_bus(), path, PX4_WARN, SENSOR_POLLRATE_DEFAULT, SENSORIOCRESET, and SENSORIOCSPOLLRATE.
Referenced by lis3mdl_main().
int lis3mdl::start (LIS3MDL_BUS bus_id, Rotation rotation)
Starts the driver.
This function call only returns once the driver is either successfully up and running or failed to start.
Definition at line 136 of file lis3mdl_main.cpp.
References bus_options, LIS3MDL_BUS_ALL, NUM_BUS_OPTIONS, and bmp280::start_bus().
Referenced by lis3mdl_main().
bool lis3mdl::start_bus (struct lis3mdl_bus_option & bus, Rotation rotation)
Starts the driver for a specific bus option.
Definition at line 108 of file lis3mdl_main.cpp.
References lis3mdl::lis3mdl_bus_option::dev, errx, OK, and warnx.
int lis3mdl::stop ()
Stop the driver.
Stop the driver.
Definition at line 159 of file lis3mdl_main.cpp.
References bus_options, hmc5883::bus_options, hmc5883::hmc5883_bus_option::dev, errx, sdp3x_airspeed::g_dev, ms5525_airspeed::g_dev, bebop_flow::g_dev, df_ltc2946_wrapper::g_dev, df_ms5607_wrapper::g_dev, df_ms5611_wrapper::g_dev, df_bebop_rangefinder_wrapper::g_dev, df_bmp280_wrapper::g_dev, df_isl29501_wrapper::g_dev, df_trone_wrapper::g_dev, navio_rgbled::g_dev, ets_airspeed::g_dev, df_bebop_bus_wrapper::g_dev, meas_airspeed_sim::g_dev, df_ak8963_wrapper::g_dev, df_hmc5883_wrapper::g_dev, meas_airspeed::g_dev, gpssim::g_dev, df_mpu6050_wrapper::g_dev, sf1xx::g_dev, px4flow::g_dev, mb12xx::g_dev, hc_sr04::g_dev, srf02::g_dev, tfmini::g_dev, pmw3901::g_dev, df_lsm9ds1_wrapper::g_dev, teraranger::g_dev, sf0x::g_dev, df_mpu9250_wrapper::g_dev, vl53lxx::g_dev, fxos8701cq::g_dev, gyrosim::g_dev_sim, test_ppm::g_test, bebop_flow::image_sensor, ll40ls::instance, NUM_BUS_OPTIONS, PX4_ERR, PX4_ERROR, PX4_INFO, PX4_OK, PX4_WARN, RGBLED::stop(), VideoDevice::stop(), DfLtc2946Wrapper::stop(), DfBebopBusWrapper::stop(), DfMS5611Wrapper::stop(), DfMS5607Wrapper::stop(), DfBmp280Wrapper::stop(), DfBebopRangeFinderWrapper::stop(), DfAK8963Wrapper::stop(), DfTROneWrapper::stop(), DfHmc5883Wrapper::stop(), DfISL29501Wrapper::stop(), DfMPU6050Wrapper::stop(), DfLsm9ds1Wrapper::stop(), DfMpu9250Wrapper::stop(), HMC5883::stop(), usleep(), and warnx.
Referenced by bebop_flow_main(), df_ak8963_wrapper_main(), df_bebop_bus_wrapper_main(), df_bebop_rangefinder_wrapper_main(), df_bmp280_wrapper_main(), df_hmc5883_wrapper_main(), df_isl29501_wrapper_main(), df_lsm9ds1_wrapper_main(), df_ltc2946_wrapper_main(), df_mpu6050_wrapper_main(), df_mpu9250_wrapper_main(), df_ms5607_wrapper_main(), df_ms5611_wrapper_main(), df_trone_wrapper_main(), ets_airspeed_main(), fxos8701cq_main(), gpssim_main(), gyrosim_main(), hc_sr04_main(), hmc5883_main(), lis3mdl_main(), ll40ls_main(), mb12xx_main(), measairspeedsim_main(), ms4525_airspeed_main(), ms5525_airspeed_main(), navio_rgbled_main(), pmw3901_main(), px4flow_main(), sdp3x_airspeed_main(), sf0x_main(), sf1xx_main(), spektrum_rc_main(), srf02_main(), teraranger_main(), test_ppm_main(), tfmini_main(), and vl53lxx_main().
bool lis3mdl::test (LIS3MDL_BUS bus_id)
Perform some basic functional tests on the driver; make sure we can collect data from the sensor in polled and automatic modes.
Definition at line 176 of file lis3mdl_main.cpp.
References lis3mdl::lis3mdl_bus_option::devpath, fd, bmp280::find_bus(), mag_report, MAGIOCGEXTERNAL, OK, path, PX4_INFO, PX4_WARN, read(), SENSORIOCSPOLLRATE, and SENSORIOCSQUEUEDEPTH.
Referenced by lis3mdl_main().
void lis3mdl::usage (void)
Prints info about the driver argument usage.
Prints info about the driver argument usage.
Definition at line 276 of file lis3mdl_main.cpp.
References IST8310_BUS_I2C_ADDR, IST8310_BUS_I2C_EXTERNAL, IST8310_BUS_I2C_INTERNAL, PX4_INFO, PX4_WARN, and warnx.
Referenced by accelsim_main(), adis16448_main(), adis16477_main(), bebop_flow_main(), bmi055_main(), bmi160_main(), bmm150_main(), bmp280_main(), df_ak8963_wrapper_main(), df_bebop_bus_wrapper_main(), df_bebop_rangefinder_wrapper_main(), df_bmp280_wrapper_main(), df_hmc5883_wrapper_main(), df_isl29501_wrapper_main(), df_lsm9ds1_wrapper_main(), df_ltc2946_wrapper_main(), df_mpu6050_wrapper_main(), df_mpu9250_wrapper_main(), df_ms5607_wrapper_main(), df_ms5611_wrapper_main(), df_trone_wrapper_main(), fxas21002c_main(), fxos8701cq_main(), gyrosim_main(), hmc5883_main(), ist8310_main(), l3gd20_main(), lis3mdl_main(), ll40ls_main(), lps22hb_main(), lps25h_main(), lsm303agr_main(), lsm303d_main(), mpl3115a2_main(), mpu6000_main(), mpu9250_main(), ms5611_main(), navio_rgbled_main(), px4flow_main(), spektrum_rc_main(), syslink_main(), test_ppm_main(), and tfmini_main().
Variable Documentation
struct lis3mdl::lis3mdl_bus_option lis3mdl::bus_options[]
Initial value:
= {
}