PX4 Firmware: px4::SubscriberNode Class Reference
px4::SubscriberNode Class Reference abstract
Because we maintain a list of subscribers we need a node class.
#include <px4_subscriber.h>
Public Member Functions
SubscriberNode (unsigned interval)
virtual ~SubscriberNode ()
virtual void update ()=0
virtual int getUORBHandle ()=0
unsigned get_interval ()
Public Member Functions inherited from ListNode< SubscriberNode * >
ListNode ()
ListNode (const ListNode &)=delete
ListNode (ListNode &&)=delete
virtual ~ListNode ()=default
ListNode & operator= (const ListNode &)=delete
ListNode & operator= (ListNode &&)=delete
void setSibling (SubscriberNode *sibling)
const SubscriberNode * getSibling ()
Protected Attributes
unsigned _interval
Protected Attributes inherited from ListNode< SubscriberNode * >
SubscriberNode * _sibling
Detailed Description
Because we maintain a list of subscribers we need a node class.
Definition at line 159 of file px4_subscriber.h.
Constructor & Destructor Documentation
px4::SubscriberNode::SubscriberNode (unsigned interval) inline
Definition at line 163 of file px4_subscriber.h.
virtual px4::SubscriberNode::~SubscriberNode () inline virtual
Definition at line 168 of file px4_subscriber.h.
Member Function Documentation
unsigned px4::SubscriberNode::get_interval () inline
Definition at line 174 of file px4_subscriber.h.
Referenced by px4::NodeHandle::update_sub_min_interval().
virtual int px4::SubscriberNode::getUORBHandle () pure virtual
Implemented in px4::SubscriberUORB< T >.
Referenced by px4::NodeHandle::spin().
virtual void px4::SubscriberNode::update () pure virtual
Implemented in px4::SubscriberUORBCallback< T >, and px4::SubscriberUORB< T >.
Referenced by px4::NodeHandle::spinOnce().
Member Data Documentation
unsigned px4::SubscriberNode::_interval protected
Definition at line 177 of file px4_subscriber.h.
The documentation for this class was generated from the following file:
src/platforms/px4_subscriber.h