PX4 Firmware: WQueueTest Class Reference
WQueueTest Class Reference
#include <wqueue_test.h>
Public Member Functions
WQueueTest ()
~WQueueTest ()
int main ()
Static Public Attributes
static px4::AppState appState
Private Member Functions
void do_lp_work (void)
void do_hp_work (void)
Static Private Member Functions
static void hp_worker_cb (void *p)
static void lp_worker_cb (void *p)
Private Attributes
bool _lpwork_done
bool _hpwork_done
work_s _lpwork
work_s _hpwork
Detailed Description
Definition at line 46 of file wqueue_test.h.
Constructor & Destructor Documentation
WQueueTest::WQueueTest () inline
Definition at line 49 of file wqueue_test.h.
References _hpwork, and _lpwork.
WQueueTest::~WQueueTest () inline
Definition at line 57 of file wqueue_test.h.
References main().
Member Function Documentation
void WQueueTest::do_hp_work (void) private
Definition at line 79 of file wqueue_test.cpp.
References _hpwork, _hpwork_done, and hp_worker_cb().
Referenced by hp_worker_cb().
void WQueueTest::do_lp_work (void) private
Definition at line 65 of file wqueue_test.cpp.
References _lpwork, _lpwork_done, and lp_worker_cb().
Referenced by lp_worker_cb().
void WQueueTest::hp_worker_cb (void * p) static private
Definition at line 51 of file wqueue_test.cpp.
References do_hp_work().
Referenced by do_hp_work(), and main().
void WQueueTest::lp_worker_cb (void * p) static private
Definition at line 58 of file wqueue_test.cpp.
References do_lp_work().
Referenced by do_lp_work(), and main().
int WQueueTest::main ()
Definition at line 94 of file wqueue_test.cpp.
References _hpwork, _hpwork_done, _lpwork, _lpwork_done, appState, px4::AppState::exitRequested(), hp_worker_cb(), lp_worker_cb(), and px4::AppState::setRunning().
Referenced by PX4_MAIN(), and ~WQueueTest().
Member Data Documentation
work_s WQueueTest::_hpwork private
Definition at line 72 of file wqueue_test.h.
Referenced by do_hp_work(), main(), and WQueueTest().
bool WQueueTest::_hpwork_done private
Definition at line 70 of file wqueue_test.h.
Referenced by do_hp_work(), and main().
work_s WQueueTest::_lpwork private
Definition at line 71 of file wqueue_test.h.
Referenced by do_lp_work(), main(), and WQueueTest().
bool WQueueTest::_lpwork_done private
Definition at line 69 of file wqueue_test.h.
Referenced by do_lp_work(), and main().
px4::AppState WQueueTest::appState static
Definition at line 61 of file wqueue_test.h.
Referenced by main(), and wqueue_test_main().
The documentation for this class was generated from the following files:
src/platforms/common/work_queue/wqueue_test/wqueue_test.h
src/platforms/common/work_queue/wqueue_test/wqueue_test.cpp