PX4 Firmware: bma180 Namespace Reference
bma180 Namespace Reference
Local functions in support of the shell command.
Functions
void start ()
Start the driver.
void test ()
Perform some basic functional tests on the driver; make sure we can collect data from the sensor in polled and automatic modes.
void reset ()
Reset the driver.
void info ()
Print a little info about the driver.
Variables
BMA180 * g_dev
Detailed Description
Local functions in support of the shell command.
Function Documentation
void bma180::info ()
Print a little info about the driver.
Print a little info about the driver.
Definition at line 874 of file bma180.cpp.
References errx, and BMA180::print_info().
Referenced by bma180_main().
void bma180::reset ()
Reset the driver.
Reset the driver.
Definition at line 851 of file bma180.cpp.
References ACCEL_DEVICE_PATH, err, fd, BMA180::ioctl(), SENSOR_POLLRATE_DEFAULT, SENSORIOCRESET, and SENSORIOCSPOLLRATE.
Referenced by bma180_main(), and test().
void bma180::start ()
Start the driver.
Attempt to start driver on all available I2C busses.
Definition at line 769 of file bma180.cpp.
References ACCEL_DEVICE_PATH, BMA180::BMA180(), errx, fd, g_dev, BMA180::init(), BMA180::ioctl(), OK, PX4_SPIDEV_BMA, SENSOR_POLLRATE_DEFAULT, and SENSORIOCSPOLLRATE.
Referenced by bma180_main().
void bma180::test ()
Perform some basic functional tests on the driver; make sure we can collect data from the sensor in polled and automatic modes.
Definition at line 816 of file bma180.cpp.
References ACCEL_DEVICE_PATH, accel_report, err, errx, fd, BMA180::ioctl(), BMA180::read(), reset(), SENSOR_POLLRATE_MANUAL, and SENSORIOCSPOLLRATE.
Referenced by bma180_main().
Variable Documentation
BMA180* bma180::g_dev
Definition at line 758 of file bma180.cpp.
Referenced by start().