PX4 Firmware: src/modules/position_estimator_inav/position_estimator_inav_main.cpp File Reference
position_estimator_inav_main.cpp File Reference
#include <px4_posix.h>
#include <px4_tasks.h>
#include <unistd.h>
#include <stdlib.h>
#include <stdio.h>
#include <stdbool.h>
#include <fcntl.h>
#include <string.h>
#include <px4_config.h>
#include <math.h>
#include <float.h>
#include <uORB/uORB.h>
#include <uORB/topics/parameter_update.h>
#include <uORB/topics/actuator_controls.h>
#include <uORB/topics/actuator_armed.h>
#include <uORB/topics/sensor_combined.h>
#include <uORB/topics/vehicle_attitude.h>
#include <uORB/topics/vehicle_local_position.h>
#include <uORB/topics/vehicle_global_position.h>
#include <uORB/topics/vehicle_gps_position.h>
#include <uORB/topics/vehicle_rates_setpoint.h>
#include <uORB/topics/att_pos_mocap.h>
#include <uORB/topics/optical_flow.h>
#include <uORB/topics/distance_sensor.h>
#include <uORB/topics/vehicle_air_data.h>
#include <poll.h>
#include <systemlib/err.h>
#include <systemlib/mavlink_log.h>
#include <lib/ecl/geo/geo.h>
#include <drivers/drv_hrt.h>
#include <platforms/px4_defines.h>
#include <terrain_estimation/terrain_estimator.h>
#include "position_estimator_inav_params.h"
#include "inertial_filter.h"
Macros
#define MIN_VALID_W 0.00001f
#define PUB_INTERVAL 10000
#define EST_BUF_SIZE 250000 / PUB_INTERVAL
#define MAX_WAIT_FOR_BARO_SAMPLE 3000000
#define write_debug_log(...)
Functions
__EXPORT int position_estimator_inav_main (int argc, char *argv[])
The position_estimator_inav_thread only briefly exists to start the background job.
int position_estimator_inav_thread_main (int argc, char *argv[])
static void usage (const char *reason)
Print the correct usage.
static int min (int val1, int val2)
static int max (int val1, int val2)
int inav_parameters_init (struct position_estimator_inav_param_handles *h)
Initialize all parameter handles and values.
int inav_parameters_update (const struct position_estimator_inav_param_handles *h, struct position_estimator_inav_params *p)
Update all parameters.
Variables
static bool thread_should_exit = false
Deamon exit flag.
static bool thread_running = false
Deamon status flag.
static int position_estimator_inav_task
Handle of deamon task / thread.
static bool inav_verbose_mode = false
static const hrt_abstime vision_topic_timeout = 500000
static const hrt_abstime mocap_topic_timeout = 500000
static const hrt_abstime gps_topic_timeout = 500000
static const hrt_abstime flow_topic_timeout = 1000000
static const hrt_abstime lidar_timeout = 150000
static const hrt_abstime lidar_valid_timeout = 1000000
static const unsigned updates_counter_len = 1000000
static const float max_flow = 1.0f
Macro Definition Documentation
#define EST_BUF_SIZE 250000 / PUB_INTERVAL
Definition at line 80 of file position_estimator_inav_main.cpp.
Referenced by position_estimator_inav_thread_main().
#define MAX_WAIT_FOR_BARO_SAMPLE 3000000
Definition at line 81 of file position_estimator_inav_main.cpp.
Referenced by position_estimator_inav_thread_main().
#define MIN_VALID_W 0.00001f
Definition at line 78 of file position_estimator_inav_main.cpp.
Referenced by position_estimator_inav_thread_main().
#define PUB_INTERVAL 10000
Definition at line 79 of file position_estimator_inav_main.cpp.
Referenced by position_estimator_inav_thread_main().
#define write_debug_log (...)
Definition at line 226 of file position_estimator_inav_main.cpp.
Referenced by position_estimator_inav_main(), and position_estimator_inav_thread_main().
Function Documentation
int inav_parameters_init (struct position_estimator_inav_param_handles * h)
Initialize all parameter handles and values.
Definition at line 1440 of file position_estimator_inav_main.cpp.
References position_estimator_inav_param_handles::att_ext_hdg_m, position_estimator_inav_param_handles::delay_gps, position_estimator_inav_param_handles::disable_mocap, position_estimator_inav_param_handles::enable_lidar_alt_est, position_estimator_inav_param_handles::flow_k, position_estimator_inav_param_handles::flow_module_offset_x, position_estimator_inav_param_handles::flow_module_offset_y, position_estimator_inav_param_handles::flow_q_min, position_estimator_inav_param_handles::land_disp, position_estimator_inav_param_handles::land_t, position_estimator_inav_param_handles::land_thr, position_estimator_inav_param_handles::lidar_calibration_offset, position_estimator_inav_param_handles::lidar_err, position_estimator_inav_param_handles::no_vision, param_find(), position_estimator_inav_param_handles::w_acc_bias, position_estimator_inav_param_handles::w_gps_flow, position_estimator_inav_param_handles::w_mocap_p, position_estimator_inav_param_handles::w_xy_flow, position_estimator_inav_param_handles::w_xy_gps_p, position_estimator_inav_param_handles::w_xy_gps_v, position_estimator_inav_param_handles::w_xy_res_v, position_estimator_inav_param_handles::w_xy_vision_p, position_estimator_inav_param_handles::w_xy_vision_v, position_estimator_inav_param_handles::w_z_baro, position_estimator_inav_param_handles::w_z_gps_p, position_estimator_inav_param_handles::w_z_gps_v, position_estimator_inav_param_handles::w_z_lidar, and position_estimator_inav_param_handles::w_z_vision_p.
Referenced by position_estimator_inav_thread_main().
int inav_parameters_update (const struct position_estimator_inav_param_handles * h, struct position_estimator_inav_params * p)
Update all parameters.
Definition at line 1474 of file position_estimator_inav_main.cpp.
References position_estimator_inav_params::att_ext_hdg_m, position_estimator_inav_param_handles::att_ext_hdg_m, position_estimator_inav_params::delay_gps, position_estimator_inav_param_handles::delay_gps, position_estimator_inav_params::disable_mocap, position_estimator_inav_param_handles::disable_mocap, position_estimator_inav_params::enable_lidar_alt_est, position_estimator_inav_param_handles::enable_lidar_alt_est, position_estimator_inav_params::flow_k, position_estimator_inav_param_handles::flow_k, position_estimator_inav_params::flow_module_offset_x, position_estimator_inav_param_handles::flow_module_offset_x, position_estimator_inav_params::flow_module_offset_y, position_estimator_inav_param_handles::flow_module_offset_y, position_estimator_inav_params::flow_q_min, position_estimator_inav_param_handles::flow_q_min, position_estimator_inav_params::land_disp, position_estimator_inav_param_handles::land_disp, position_estimator_inav_params::land_t, position_estimator_inav_param_handles::land_t, position_estimator_inav_params::land_thr, position_estimator_inav_param_handles::land_thr, position_estimator_inav_params::lidar_calibration_offset, position_estimator_inav_param_handles::lidar_calibration_offset, position_estimator_inav_params::lidar_err, position_estimator_inav_param_handles::lidar_err, position_estimator_inav_params::no_vision, position_estimator_inav_param_handles::no_vision, param_get(), position_estimator_inav_params::w_acc_bias, position_estimator_inav_param_handles::w_acc_bias, position_estimator_inav_params::w_gps_flow, position_estimator_inav_param_handles::w_gps_flow, position_estimator_inav_params::w_mocap_p, position_estimator_inav_param_handles::w_mocap_p, position_estimator_inav_params::w_xy_flow, position_estimator_inav_param_handles::w_xy_flow, position_estimator_inav_params::w_xy_gps_p, position_estimator_inav_param_handles::w_xy_gps_p, position_estimator_inav_params::w_xy_gps_v, position_estimator_inav_param_handles::w_xy_gps_v, position_estimator_inav_params::w_xy_res_v, position_estimator_inav_param_handles::w_xy_res_v, position_estimator_inav_params::w_xy_vision_p, position_estimator_inav_param_handles::w_xy_vision_p, position_estimator_inav_params::w_xy_vision_v, position_estimator_inav_param_handles::w_xy_vision_v, position_estimator_inav_params::w_z_baro, position_estimator_inav_param_handles::w_z_baro, position_estimator_inav_params::w_z_gps_p, position_estimator_inav_param_handles::w_z_gps_p, position_estimator_inav_params::w_z_gps_v, position_estimator_inav_param_handles::w_z_gps_v, position_estimator_inav_params::w_z_lidar, position_estimator_inav_param_handles::w_z_lidar, position_estimator_inav_params::w_z_vision_p, and position_estimator_inav_param_handles::w_z_vision_p.
Referenced by position_estimator_inav_thread_main().
static int max (int val1, int val2) inline static
Definition at line 108 of file position_estimator_inav_main.cpp.
Referenced by BezierQuadTest::_get_arc_length(), BezierQuadTest::_set_bez_from_vel(), TECS::_update_pitch_setpoint(), TECS::_update_speed_states(), FixedwingPositionControl::airspeed_poll(), FixedwingPositionControl::calculate_gndspeed_undershoot(), SimpleAnalyzer::check_limits(), runwaytakeoff::RunwayTakeoff::climbout(), ControlMath::constrainXY(), FixedwingPositionControl::control_position(), FixedwingPositionControl::control_takeoff(), convert_limit_safe(), SimpleAnalyzer::get_scaled(), runwaytakeoff::RunwayTakeoff::getMaxPitch(), MatrixTest::inverseTests(), main(), position_estimator_inav_thread_main(), MPL3115A2_I2C::reset(), ECL_Controller::set_integrator_max(), LidarLite::set_maximum_distance(), TFMINI::set_maximum_distance(), SF0X::set_maximum_distance(), SF1XX::set_maximum_distance(), TERARANGER::set_maximum_distance(), HC_SR04::set_maximum_distance(), MB12XX::set_maximum_distance(), SRF02::set_maximum_distance(), UavcanNode::set_param(), MatrixTest::squareMatrixTests(), FixedwingPositionControl::tecs_update_pitch_throttle(), ControlMathTest::testPrioritizeVector(), and UavcanEscController::update_outputs().
static int min (int val1, int val2) inline static
Definition at line 103 of file position_estimator_inav_main.cpp.
Referenced by BezierQuadTest::_get_arc_length(), TECS::_update_pitch_setpoint(), build_gps_response(), SimpleAnalyzer::check_limits(), runwaytakeoff::RunwayTakeoff::climbout(), FixedwingPositionControl::control_landing(), FixedwingPositionControl::control_position(), convert_limit_safe(), convert_to_degrees_minutes_seconds(), get_lookup_table_index(), SimpleAnalyzer::get_scaled(), runwaytakeoff::RunwayTakeoff::getMinPitch(), main(), position_estimator_inav_thread_main(), SimpleMixer::pwm_input(), MicroBenchMatrix::random(), MicroBenchORB::random(), MicroBenchHRT::random(), MicroBenchMath::random(), LidarLite::set_minimum_distance(), TFMINI::set_minimum_distance(), SF0X::set_minimum_distance(), SF1XX::set_minimum_distance(), TERARANGER::set_minimum_distance(), HC_SR04::set_minimum_distance(), SRF02::set_minimum_distance(), MB12XX::set_minimum_distance(), UavcanNode::set_param(), and RTL::set_return_alt_min().
int position_estimator_inav_main (int argc, char * argv[])
The position_estimator_inav_thread only briefly exists to start the background job.
The stack size assigned in the Makefile does only apply to this management task.
The actual stack size should be set in the call to task_create().
Definition at line 133 of file position_estimator_inav_main.cpp.
References dt, f(), fsync(), hrt_absolute_time(), inav_verbose_mode, msg, position_estimator_inav_task, position_estimator_inav_thread_main(), px4_task_spawn_cmd(), SCHED_DEFAULT, SCHED_PRIORITY_MAX, thread_running, thread_should_exit, usage(), warnx, and write_debug_log.
int position_estimator_inav_thread_main (int argc, char * argv[])
Definition at line 232 of file position_estimator_inav_main.cpp.
References matrix::Matrix< Type, M, N >::_data, sensor_combined_s::accelerometer_m_s2, sensor_combined_s::accelerometer_timestamp_relative, vehicle_global_position_s::alt, vehicle_gps_position_s::alt, position_estimator_inav_params::att_ext_hdg_m, vehicle_air_data_s::baro_alt_meter, CBRK_NO_VISION_KEY, CONSTANTS_ONE_G, distance_sensor_s::current_distance, position_estimator_inav_params::delay_gps, position_estimator_inav_params::disable_mocap, vehicle_local_position_s::dist_bottom, vehicle_local_position_s::dist_bottom_rate, vehicle_local_position_s::dist_bottom_valid, dt, position_estimator_inav_params::enable_lidar_alt_est, vehicle_gps_position_s::eph, vehicle_global_position_s::eph, vehicle_local_position_s::eph, vehicle_gps_position_s::epv, vehicle_global_position_s::epv, vehicle_local_position_s::epv, EST_BUF_SIZE, vehicle_local_position_s::evh, vehicle_local_position_s::evv, f(), vehicle_gps_position_s::fix_type, position_estimator_inav_params::flow_k, position_estimator_inav_params::flow_module_offset_x, position_estimator_inav_params::flow_module_offset_y, position_estimator_inav_params::flow_q_min, flow_topic_timeout, TerrainEstimator::get_distance_to_ground(), gps_topic_timeout, optical_flow_s::gyro_x_rate_integral, optical_flow_s::gyro_y_rate_integral, optical_flow_s::gyro_z_rate_integral, vehicle_local_position_s::hagl_max, vehicle_local_position_s::hagl_min, hrt_absolute_time(), hrt_abstime, inav_parameters_init(), inav_parameters_update(), inav_verbose_mode, inertial_filter_correct(), inertial_filter_predict(), optical_flow_s::integration_timespan, TerrainEstimator::is_valid(), vehicle_global_position_s::lat, vehicle_gps_position_s::lat, position_estimator_inav_params::lidar_calibration_offset, position_estimator_inav_params::lidar_err, lidar_timeout, lidar_valid_timeout, vehicle_global_position_s::lon, vehicle_gps_position_s::lon, map_projection_init(), map_projection_project(), map_projection_reproject(), mavlink_log_info, mavlink_log_pub, max(), distance_sensor_s::max_distance, max_flow, MAX_WAIT_FOR_BARO_SAMPLE, TerrainEstimator::measurement_update(), min(), distance_sensor_s::min_distance, MIN_VALID_W, mocap_topic_timeout, position_estimator_inav_params::no_vision, orb_advert_t, orb_advertise(), orb_check(), orb_copy(), ORB_ID, ORB_ID_VEHICLE_ATTITUDE_CONTROLS, ORB_MULTI_MAX_INSTANCES, orb_publish(), orb_subscribe(), orb_subscribe_multi(), distance_sensor_s::orientation, vehicle_rates_setpoint_s::pitch, vehicle_attitude_s::pitchspeed, optical_flow_s::pixel_flow_x_integral, optical_flow_s::pixel_flow_y_integral, TerrainEstimator::predict(), matrix::Euler< Type >::psi(), PUB_INTERVAL, px4_poll(), PX4_WARN, vehicle_attitude_s::q, optical_flow_s::quality, vehicle_local_position_s::ref_alt, vehicle_local_position_s::ref_lat, vehicle_local_position_s::ref_lon, vehicle_local_position_s::ref_timestamp, vehicle_rates_setpoint_s::roll, vehicle_attitude_s::rollspeed, vehicle_global_position_s::terrain_alt, vehicle_global_position_s::terrain_alt_valid, thread_running, thread_should_exit, vehicle_global_position_s::timestamp, vehicle_local_position_s::timestamp, vehicle_air_data_s::timestamp, vehicle_gps_position_s::timestamp, att_pos_mocap_s::timestamp, sensor_combined_s::timestamp, updates_counter_len, vehicle_local_position_s::v_xy_valid, vehicle_local_position_s::v_z_valid, vehicle_global_position_s::vel_d, vehicle_gps_position_s::vel_d_m_s, vehicle_global_position_s::vel_e, vehicle_gps_position_s::vel_e_m_s, vehicle_global_position_s::vel_n, vehicle_gps_position_s::vel_n_m_s, vehicle_gps_position_s::vel_ned_valid, vision_topic_timeout, vehicle_local_position_s::vx, vehicle_local_position_s::vxy_max, vehicle_local_position_s::vy, vehicle_local_position_s::vz, vehicle_local_position_s::vz_max, position_estimator_inav_params::w_acc_bias, position_estimator_inav_params::w_gps_flow, position_estimator_inav_params::w_mocap_p, position_estimator_inav_params::w_xy_flow, position_estimator_inav_params::w_xy_gps_p, position_estimator_inav_params::w_xy_gps_v, position_estimator_inav_params::w_xy_res_v, position_estimator_inav_params::w_xy_vision_p, position_estimator_inav_params::w_xy_vision_v, position_estimator_inav_params::w_z_baro, position_estimator_inav_params::w_z_gps_p, position_estimator_inav_params::w_z_gps_v, position_estimator_inav_params::w_z_lidar, position_estimator_inav_params::w_z_vision_p, warnx, write_debug_log, att_pos_mocap_s::x, vehicle_local_position_s::x, vehicle_local_position_s::xy_global, vehicle_local_position_s::xy_valid, vehicle_local_position_s::y, att_pos_mocap_s::y, vehicle_rates_setpoint_s::yaw, vehicle_global_position_s::yaw, vehicle_local_position_s::yaw, vehicle_attitude_s::yawspeed, att_pos_mocap_s::z, vehicle_local_position_s::z, vehicle_local_position_s::z_deriv, vehicle_local_position_s::z_global, and vehicle_local_position_s::z_valid.
Referenced by position_estimator_inav_main().
static void usage (const char * reason) static
Print the correct usage.
Definition at line 116 of file position_estimator_inav_main.cpp.
References PX4_INFO.
Referenced by position_estimator_inav_main().
Variable Documentation
const hrt_abstime flow_topic_timeout = 1000000 static
Definition at line 91 of file position_estimator_inav_main.cpp.
Referenced by position_estimator_inav_thread_main().
const hrt_abstime gps_topic_timeout = 500000 static
Definition at line 90 of file position_estimator_inav_main.cpp.
Referenced by position_estimator_inav_thread_main().
bool inav_verbose_mode = false static
Definition at line 86 of file position_estimator_inav_main.cpp.
Referenced by position_estimator_inav_main(), and position_estimator_inav_thread_main().
const hrt_abstime lidar_timeout = 150000 static
Definition at line 92 of file position_estimator_inav_main.cpp.
Referenced by position_estimator_inav_thread_main().
const hrt_abstime lidar_valid_timeout = 1000000 static
Definition at line 93 of file position_estimator_inav_main.cpp.
Referenced by position_estimator_inav_thread_main().
const float max_flow = 1.0f static
Definition at line 95 of file position_estimator_inav_main.cpp.
Referenced by position_estimator_inav_thread_main().
const hrt_abstime mocap_topic_timeout = 500000 static
Definition at line 89 of file position_estimator_inav_main.cpp.
Referenced by position_estimator_inav_thread_main().
int position_estimator_inav_task static
Handle of deamon task / thread.
Definition at line 85 of file position_estimator_inav_main.cpp.
Referenced by position_estimator_inav_main().
bool thread_running = false static
Deamon status flag.
Definition at line 84 of file position_estimator_inav_main.cpp.
Referenced by position_estimator_inav_main(), and position_estimator_inav_thread_main().
bool thread_should_exit = false static
Deamon exit flag.
Definition at line 83 of file position_estimator_inav_main.cpp.
Referenced by position_estimator_inav_main(), and position_estimator_inav_thread_main().
const unsigned updates_counter_len = 1000000 static
Definition at line 94 of file position_estimator_inav_main.cpp.
Referenced by position_estimator_inav_thread_main().
const hrt_abstime vision_topic_timeout = 500000 static
Definition at line 88 of file position_estimator_inav_main.cpp.
Referenced by position_estimator_inav_thread_main().