PX4 Firmware: BMI088 Class Reference
BMI088 Class Reference
#include <BMI088.hpp>
Public Member Functions
BMI088 (const char *name, const char *devname, int bus, uint32_t device, enum spi_mode_e mode, uint32_t frequency, enum Rotation rotation)
virtual ~BMI088 ()=default
Protected Member Functions
virtual uint8_t read_reg (unsigned reg)
Read a register from the BMI088.
virtual uint16_t read_reg16 (unsigned reg)
void write_reg (unsigned reg, uint8_t value)
Write a register in the BMI088.
BMI088 (const BMI088 &)
BMI088 operator= (const BMI088 &)
Protected Attributes
uint8_t _whoami
uint8_t _register_wait
whoami result
uint64_t _reset_wait
enum Rotation _rotation
uint8_t _checked_next
Detailed Description
Definition at line 53 of file BMI088.hpp.
Constructor & Destructor Documentation
BMI088() [1/2]
BMI088::BMI088 (const BMI088 &) protected
BMI088() [2/2]
BMI088::BMI088 (const char * name, const char * devname, int bus, uint32_t device, enum spi_mode_e mode, uint32_t frequency, enum Rotation rotation)
Definition at line 295 of file bmi088_main.cpp.
~BMI088()
virtual BMI088::~BMI088 () virtual default
Member Function Documentation
operator=()
BMI088 BMI088::operator= (const BMI088 &) protected
read_reg()
uint8_t BMI088::read_reg (unsigned reg) protected virtual
Read a register from the BMI088.
Parameters
The register to read.
Returns
The value that was read.
Reimplemented in BMI088_accel.
Definition at line 307 of file bmi088_main.cpp.
References DIR_READ.
Referenced by BMI088_gyro::check_registers(), BMI088_gyro::modify_reg(), BMI088_gyro::print_info(), BMI088_gyro::print_registers(), BMI088_gyro::probe(), and BMI088_gyro::reset().
read_reg16()
uint16_t BMI088::read_reg16 (unsigned reg) protected virtual
Reimplemented in BMI088_accel.
Definition at line 317 of file bmi088_main.cpp.
References DIR_READ.
write_reg()
void BMI088::write_reg (unsigned reg, uint8_t value) protected
Write a register in the BMI088.
Parameters
reg The register to write.
value The new value to write.
Definition at line 327 of file bmi088_main.cpp.
References DIR_WRITE.
Referenced by BMI088_gyro::check_registers(), BMI088_accel::check_registers(), BMI088_gyro::reset(), BMI088_accel::reset(), BMI088_gyro::test_error(), BMI088_accel::test_error(), BMI088_gyro::write_checked_reg(), and BMI088_accel::write_checked_reg().
Member Data Documentation
_checked_next
uint8_t BMI088::_checked_next protected
Definition at line 65 of file BMI088.hpp.
Referenced by BMI088_gyro::check_registers(), BMI088_accel::check_registers(), BMI088_gyro::print_info(), and BMI088_accel::print_info().
_register_wait
uint8_t BMI088::_register_wait protected
whoami result
Definition at line 60 of file BMI088.hpp.
Referenced by BMI088_gyro::check_registers(), BMI088_accel::check_registers(), BMI088_gyro::measure(), and BMI088_accel::measure().
_reset_wait
uint64_t BMI088::_reset_wait protected
Definition at line 61 of file BMI088.hpp.
Referenced by BMI088_gyro::check_registers(), BMI088_accel::check_registers(), BMI088_gyro::measure(), and BMI088_accel::measure().
_rotation
enum Rotation BMI088::_rotation protected
Definition at line 63 of file BMI088.hpp.
_whoami
uint8_t BMI088::_whoami protected
Definition at line 58 of file BMI088.hpp.
Referenced by BMI088_gyro::probe(), and BMI088_accel::probe().
The documentation for this class was generated from the following files:
src/drivers/imu/bmi088/BMI088.hpp
src/drivers/imu/bmi088/bmi088_main.cpp