PX4 Firmware: src/drivers/barometer/bmp280/bmp280_main.cpp File Reference
bmp280_main.cpp File Reference
#include <px4_platform_common/px4_config.h>
#include <px4_platform_common/getopt.h>
#include "BMP280.hpp"
Classes
struct bmp280::bmp280_bus_option
Namespaces
bmp280
Enumerations
enum BMP280_BUS {
BMP280_BUS::ALL = 0, BMP280_BUS::I2C_INTERNAL, BMP280_BUS::I2C_EXTERNAL, BMP280_BUS::SPI_INTERNAL,
BMP280_BUS::SPI_EXTERNAL
}
Functions
static struct bmp280_bus_option * bmp280::find_bus (BMP280_BUS busid)
static bool bmp280::start_bus (bmp280_bus_option &bus)
static int bmp280::start (BMP280_BUS busid)
static int bmp280::stop (BMP280_BUS busid)
static int bmp280::status (BMP280_BUS busid)
static int bmp280::usage ()
int bmp280_main (int argc, char *argv[])
Variables
struct bmp280::bmp280_bus_option bmp280::bus_options []
Enumeration Type Documentation
BMP280_BUS
enum BMP280_BUS strong
Enumerator
ALL
I2C_INTERNAL
I2C_EXTERNAL
SPI_INTERNAL
SPI_EXTERNAL
Definition at line 39 of file bmp280_main.cpp.
Function Documentation
bmp280_main()
int bmp280_main (int argc, char * argv[])
Definition at line 182 of file bmp280_main.cpp.
References ALL, I2C_EXTERNAL, I2C_INTERNAL, SPI_EXTERNAL, SPI_INTERNAL, bmp280::start(), bmp280::status(), bmp280::stop(), and bmp280::usage().