PX4 Firmware: l3gd20 Namespace Reference
l3gd20 Namespace Reference
Local functions in support of the shell command.
Functions
void usage ()
Prints info about the driver argument usage.
void start (bool external_bus, enum Rotation rotation)
Start the driver.
void test ()
Perform some basic functional tests on the driver; make sure we can collect data from the sensor in polled and automatic modes.
void reset ()
Reset the driver.
void info ()
Print a little info about the driver.
void regdump (void)
Dump the register information.
void test_error (void)
trigger an error
Variables
L3GD20 * g_dev
Detailed Description
Local functions in support of the shell command.
Function Documentation
void l3gd20::info ()
Print a little info about the driver.
Print a little info about the driver.
Definition at line 1289 of file l3gd20.cpp.
References errx, and L3GD20::print_info().
Referenced by l3gd20_main().
void l3gd20::regdump (void)
Dump the register information.
Definition at line 1305 of file l3gd20.cpp.
References errx, and L3GD20::print_registers().
Referenced by l3gd20_main().
void l3gd20::reset ()
Reset the driver.
Reset the driver.
Definition at line 1264 of file l3gd20.cpp.
References err, fd, L3GD20::ioctl(), L3GD20_DEVICE_PATH, SENSOR_POLLRATE_DEFAULT, SENSORIOCRESET, and SENSORIOCSPOLLRATE.
Referenced by l3gd20_main().
void l3gd20::start (bool external_bus, enum Rotation rotation)
Start the driver.
This function call only returns once the driver started or failed to detect the sensor.
Definition at line 1165 of file l3gd20.cpp.
References errx, fd, g_dev, L3GD20::init(), L3GD20::ioctl(), L3GD20::L3GD20(), L3GD20_DEVICE_PATH, OK, PX4_SPI_BUS_EXT, PX4_SPI_BUS_SENSORS, PX4_SPIDEV_EXT_GYRO, PX4_SPIDEV_GYRO, SENSOR_POLLRATE_DEFAULT, and SENSORIOCSPOLLRATE.
Referenced by l3gd20_main().
void l3gd20::test ()
Perform some basic functional tests on the driver; make sure we can collect data from the sensor in polled and automatic modes.
Definition at line 1223 of file l3gd20.cpp.
References err, errx, gyro_report, L3GD20::ioctl(), L3GD20_DEVICE_PATH, L3GD20::read(), SENSOR_POLLRATE_DEFAULT, SENSOR_POLLRATE_MANUAL, and SENSORIOCSPOLLRATE.
Referenced by l3gd20_main().
void l3gd20::test_error (void)
trigger an error
Definition at line 1321 of file l3gd20.cpp.
References errx, and L3GD20::test_error().
Referenced by l3gd20_main().
void l3gd20::usage (void)
Prints info about the driver argument usage.
Prints info about the driver argument usage.
Definition at line 1334 of file l3gd20.cpp.
References warnx.
Referenced by l3gd20_main().
Variable Documentation
L3GD20* l3gd20::g_dev
Definition at line 1148 of file l3gd20.cpp.
Referenced by start().