PX4 Firmware: ms5611 Namespace Reference
ms5611 Namespace Reference
Local functions in support of the shell command.
Classes
struct ms5611_bus_option
struct prom_s
Calibration PROM as reported by the device.
union prom_u
Grody hack for crc4()
Functions
bool start_bus (struct ms5611_bus_option &bus, enum MS56XX_DEVICE_TYPES device_type)
Start the driver.
struct ms5611_bus_option & find_bus (enum MS5611_BUS busid)
find a bus structure for a busid
void start (enum MS5611_BUS busid, enum MS56XX_DEVICE_TYPES device_type)
Start the driver.
void test (enum MS5611_BUS busid)
Perform some basic functional tests on the driver; make sure we can collect data from the sensor in polled and automatic modes.
void reset (enum MS5611_BUS busid)
Reset the driver.
void info ()
Print a little info about the driver.
void usage ()
Prints info about the driver argument usage.
bool crc4 (uint16_t *n_prom)
MS5611 crc4 cribbed from the datasheet.
Variables
struct ms5611::ms5611_bus_option bus_options []
Detailed Description
Local functions in support of the shell command.
Function Documentation
bool ms5611::crc4 (uint16_t * n_prom)
MS5611 crc4 cribbed from the datasheet.
Definition at line 893 of file ms5611.cpp.
Referenced by MS5611_I2C::_read_prom().
struct ms5611_bus_option & ms5611::find_bus (enum MS5611_BUS busid)
find a bus structure for a busid
Definition at line 1018 of file ms5611.cpp.
References bus_options, errx, MS5611_BUS_ALL, and NUM_BUS_OPTIONS.
Referenced by reset(), and test().
void ms5611::info ()
Print a little info about the driver.
Definition at line 1127 of file ms5611.cpp.
References bus_options, ms5611::ms5611_bus_option::dev, ms5611::ms5611_bus_option::devpath, NUM_BUS_OPTIONS, MS5611::print_info(), and warnx.
Referenced by ms5611_main().
void ms5611::reset (enum MS5611_BUS busid)
Reset the driver.
Definition at line 1101 of file ms5611.cpp.
References ms5611::ms5611_bus_option::devpath, err, fd, find_bus(), MS5611::ioctl(), device::CDev::open(), SENSOR_POLLRATE_DEFAULT, SENSORIOCRESET, and SENSORIOCSPOLLRATE.
Referenced by ms5611_main().
void ms5611::start (enum MS5611_BUS busid, enum MS56XX_DEVICE_TYPES device_type)
Start the driver.
This function call only returns once the driver is either successfully up and running or failed to start.
Definition at line 987 of file ms5611.cpp.
References bus_options, MS5611_BUS_ALL, NUM_BUS_OPTIONS, and start_bus().
Referenced by ms5611_main().
bool ms5611::start_bus (struct ms5611_bus_option & bus, enum MS56XX_DEVICE_TYPES device_type)
Start the driver.
Definition at line 940 of file ms5611.cpp.
References device::CDev::close(), ms5611::ms5611_bus_option::dev, errx, fd, MS5611::ioctl(), MS5611::MS5611(), OK, device::CDev::open(), SENSOR_POLLRATE_DEFAULT, SENSORIOCSPOLLRATE, and warnx.
Referenced by start().
void ms5611::test (enum MS5611_BUS busid)
Perform some basic functional tests on the driver; make sure we can collect data from the sensor in polled and automatic modes.
Definition at line 1036 of file ms5611.cpp.
References baro_report, device::CDev::close(), ms5611::ms5611_bus_option::devpath, err, errx, fd, find_bus(), MS5611::ioctl(), OK, device::CDev::open(), device::CDev::poll(), MS5611::read(), SENSORIOCSPOLLRATE, and SENSORIOCSQUEUEDEPTH.
Referenced by ms5611_main().
void ms5611::usage (void)
Prints info about the driver argument usage.
Definition at line 1142 of file ms5611.cpp.
References warnx.
Referenced by ms5611_main().
Variable Documentation
struct ms5611::ms5611_bus_option ms5611::bus_options[]
Initial value:
= {
}
Referenced by find_bus(), info(), and start().