PX4 Firmware: src/drivers/rgbled_pwm/rgbled_pwm.cpp File Reference
rgbled_pwm.cpp File Reference
Driver for the onboard RGB LED controller by PWM.
#include <nuttx/config.h>
#include <sys/types.h>
#include <stdint.h>
#include <string.h>
#include <stdlib.h>
#include <stdbool.h>
#include <fcntl.h>
#include <unistd.h>
#include <stdio.h>
#include <ctype.h>
#include <nuttx/wqueue.h>
#include <drivers/drv_hrt.h>
#include <perf/perf_counter.h>
#include <systemlib/err.h>
#include <board_config.h>
#include <drivers/drv_led.h>
#include <lib/led/led.h>
#include <drivers/device/device.h>
Classes
class RGBLED_PWM
Macros
#define RGBLED_ONTIME 120
#define RGBLED_OFFTIME 120
Functions
__EXPORT int rgbled_pwm_main (int argc, char *argv[])
int led_pwm_servo_set (unsigned channel, uint8_t value)
unsigned led_pwm_servo_get (unsigned channel)
int led_pwm_servo_init (void)
void led_pwm_servo_deinit (void)
static void rgbled_usage ()
Detailed Description
Driver for the onboard RGB LED controller by PWM.
this driver is based the PX4 led driver
Definition in file rgbled_pwm.cpp.
Macro Definition Documentation
#define RGBLED_OFFTIME 120
Definition at line 70 of file rgbled_pwm.cpp.
#define RGBLED_ONTIME 120
Definition at line 69 of file rgbled_pwm.cpp.
Function Documentation
void led_pwm_servo_deinit (void)
unsigned led_pwm_servo_get (unsigned channel)
int led_pwm_servo_init (void)
Referenced by RGBLED_PWM::init().
int led_pwm_servo_set (unsigned channel, uint8_t value)
Referenced by RGBLED_PWM::send_led_rgb().
int rgbled_pwm_main (int argc, char * argv[])
Definition at line 294 of file rgbled_pwm.cpp.
References errx, OK, PX4_WARN, RGBLED_PWM::RGBLED_PWM(), and rgbled_usage().
static void rgbled_usage () static
Definition at line 288 of file rgbled_pwm.cpp.
References PX4_INFO.
Referenced by rgbled_pwm_main().