PX4 Firmware: vmount::OutputRC Class Reference
vmount::OutputRC Class Reference
class OutputRC Output via actuator_controls_2 topic
#include <output_rc.h>
Public Member Functions
OutputRC (const OutputConfig &output_config)
virtual ~OutputRC ()
virtual int update (const ControlData *control_data)
Update the output.
virtual void print_status ()
report status to stdout
Public Member Functions inherited from vmount::OutputBase
OutputBase (const OutputConfig &output_config)
virtual ~OutputBase ()
virtual int initialize ()
void publish ()
Publish _angle_outputs as a mount_orientation message.
Private Attributes
orb_advert_t _actuator_controls_pub = nullptr
bool _retract_gimbal = true
Additional Inherited Members
Protected Member Functions inherited from vmount::OutputBase
float _calculate_pitch (double lon, double lat, float altitude, const vehicle_global_position_s &global_position)
void _set_angle_setpoints (const ControlData *control_data)
set angle setpoints, speeds & stabilize flags
void _handle_position_update (bool force_update=false)
check if vehicle position changed and update the setpoint angles if in gps mode
void _calculate_output_angles (const hrt_abstime &t)
calculate the _angle_outputs (with speed) and stabilize if needed
int _get_vehicle_attitude_sub () const
Protected Attributes inherited from vmount::OutputBase
map_projection_reference_s _projection_reference = {}
reference to convert (lon, lat) to local [m]
const OutputConfig & _config
const ControlData * _cur_control_data = nullptr
float _angle_setpoints [3] = { 0.f, 0.f, 0.f }
[rad]
float _angle_speeds [3] = { 0.f, 0.f, 0.f }
bool _stabilize [3] = { false, false, false }
float _angle_outputs [3] = { 0.f, 0.f, 0.f }
calculated output angles (roll, pitch, yaw) [rad]
hrt_abstime _last_update
Detailed Description
class OutputRC Output via actuator_controls_2 topic
Definition at line 55 of file output_rc.h.
Constructor & Destructor Documentation
vmount::OutputRC::OutputRC (const OutputConfig & output_config)
Definition at line 50 of file output_rc.cpp.
vmount::OutputRC::~OutputRC () virtual
Definition at line 54 of file output_rc.cpp.
References _actuator_controls_pub, and orb_unadvertise().
Member Function Documentation
void vmount::OutputRC::print_status () virtual
report status to stdout
Implements vmount::OutputBase.
Definition at line 91 of file output_rc.cpp.
References PX4_INFO.
int vmount::OutputRC::update (const ControlData * control_data) virtual
Update the output.
Parameters
data new command if non null
Returns
0 on success, <0 otherwise
Implements vmount::OutputBase.
Definition at line 61 of file output_rc.cpp.
References _actuator_controls_pub, vmount::OutputBase::_angle_outputs, vmount::OutputBase::_calculate_output_angles(), vmount::OutputBase::_config, vmount::OutputBase::_handle_position_update(), vmount::OutputBase::_last_update, _retract_gimbal, vmount::OutputBase::_set_angle_setpoints(), actuator_controls, actuator_controls_s::control, vmount::OutputConfig::gimbal_normal_mode_value, vmount::OutputConfig::gimbal_retracted_mode_value, vmount::ControlData::gimbal_shutter_retract, hrt_absolute_time(), hrt_abstime, instance, ORB_ID, ORB_PRIO_DEFAULT, orb_publish_auto(), vmount::OutputConfig::pitch_offset, vmount::OutputConfig::pitch_scale, vmount::OutputConfig::roll_offset, vmount::OutputConfig::roll_scale, actuator_controls_s::timestamp, vmount::OutputConfig::yaw_offset, and vmount::OutputConfig::yaw_scale.
Member Data Documentation
orb_advert_t vmount::OutputRC::_actuator_controls_pub = nullptr private
Definition at line 66 of file output_rc.h.
Referenced by update(), and ~OutputRC().
bool vmount::OutputRC::_retract_gimbal = true private
Definition at line 67 of file output_rc.h.
Referenced by update().
The documentation for this class was generated from the following files:
src/drivers/vmount/output_rc.h
src/drivers/vmount/output_rc.cpp