PX4 Firmware: control::BlockPI Class Reference
control::BlockPI Class Reference
A proportional-integral controller.
#include <BlockPI.hpp>
Public Member Functions
BlockPI (SuperBlock *parent, const char *name)
virtual ~BlockPI ()
float update (float input)
float getKP ()
float getKI ()
BlockIntegral & getIntegral ()
Public Member Functions inherited from control::SuperBlock
SuperBlock (SuperBlock *parent, const char *name)
~SuperBlock ()=default
SuperBlock (const SuperBlock &)=delete
SuperBlock & operator= (const SuperBlock &)=delete
SuperBlock (SuperBlock &&)=delete
SuperBlock & operator= (SuperBlock &&)=delete
void setDt (float dt) override
void updateParams () override
void updateSubscriptions () override
void updatePublications () override
Public Member Functions inherited from control::Block
Block (SuperBlock *parent, const char *name)
virtual ~Block ()=default
Block (const Block &)=delete
Block & operator= (const Block &)=delete
Block (Block &&)=delete
Block & operator= (Block &&)=delete
void getName (char *name, size_t n)
float getDt ()
Public Member Functions inherited from ListNode< Block * >
ListNode ()
ListNode (const ListNode &)=delete
ListNode (ListNode &&)=delete
virtual ~ListNode ()=default
ListNode & operator= (const ListNode &)=delete
ListNode & operator= (ListNode &&)=delete
void setSibling (Block *sibling)
const Block * getSibling ()
Private Attributes
BlockIntegral _integral
control::BlockParamFloat _kP
control::BlockParamFloat _kI
Additional Inherited Members
Protected Member Functions inherited from control::SuperBlock
List< Block * > & getChildren ()
void updateChildParams ()
void updateChildSubscriptions ()
void updateChildPublications ()
Protected Member Functions inherited from control::Block
virtual void updateParamsSubclass ()
SuperBlock * getParent ()
List< uORB::SubscriptionNode * > & getSubscriptions ()
List< uORB::PublicationNode * > & getPublications ()
List< BlockParamBase * > & getParams ()
Protected Attributes inherited from control::SuperBlock
List< Block * > _children
Protected Attributes inherited from control::Block
const char * _name
SuperBlock * _parent
float _dt {0.0f}
List< uORB::SubscriptionNode * > _subscriptions
List< uORB::PublicationNode * > _publications
List< BlockParamBase * > _params
Protected Attributes inherited from ListNode< Block * >
Block * _sibling
Detailed Description
A proportional-integral controller.
http://en.wikipedia.org/wiki/PID_controller
Definition at line 62 of file BlockPI.hpp.
Constructor & Destructor Documentation
control::BlockPI::BlockPI (SuperBlock * parent, const char * name) inline
Definition at line 66 of file BlockPI.hpp.
virtual control::BlockPI::~BlockPI () inline virtual
Definition at line 72 of file BlockPI.hpp.
Member Function Documentation
BlockIntegral& control::BlockPI::getIntegral () inline
Definition at line 81 of file BlockPI.hpp.
Referenced by control::blockPITest(), and blockPITest().
float control::BlockPI::getKI () inline
Definition at line 80 of file BlockPI.hpp.
Referenced by control::blockPITest(), and blockPITest().
float control::BlockPI::getKP () inline
Definition at line 79 of file BlockPI.hpp.
Referenced by control::blockPITest(), and blockPITest().
float control::BlockPI::update (float input) inline
Definition at line 73 of file BlockPI.hpp.
Referenced by control::blockPITest(), and blockPITest().
Member Data Documentation
BlockIntegral control::BlockPI::_integral private
Definition at line 83 of file BlockPI.hpp.
control::BlockParamFloat control::BlockPI::_kI private
Definition at line 85 of file BlockPI.hpp.
control::BlockParamFloat control::BlockPI::_kP private
Definition at line 84 of file BlockPI.hpp.
The documentation for this class was generated from the following file:
src/lib/controllib/BlockPI.hpp