PX4 Firmware: QShell Class Reference
QShell Class Reference
#include <qshell.h>
Public Member Functions
QShell ()
~QShell ()
int main (std::vector< std::string > argList)
QShell ()
~QShell ()
int main ()
int run_cmd (const std::vector< std::string > &appargs)
Static Public Attributes
static px4::AppState appState
Private Member Functions
int _send_cmd (std::vector< std::string > &argList)
int _wait_for_retval ()
Private Attributes
struct qshell_req_s m_qshell_req
apps_map_type m_apps
Static Private Attributes
static orb_advert_t _pub_qshell_req = nullptr
static int _sub_qshell_retval = -1
static uint32_t _current_sequence = 0
Detailed Description
Definition at line 48 of file qshell.h.
Constructor & Destructor Documentation
QShell() [1/2]
QShell::QShell () inline
Definition at line 51 of file qshell.h.
~QShell() [1/2]
QShell::~QShell () inline
Definition at line 52 of file qshell.h.
References main().
QShell() [2/2]
QShell::QShell ()
~QShell() [2/2]
QShell::~QShell () inline
Definition at line 53 of file qshell.h.
References appState, main(), and run_cmd().
Member Function Documentation
_send_cmd()
int QShell::_send_cmd (std::vector< std::string > & argList) private
Definition at line 77 of file qshell.cpp.
References _current_sequence, _pub_qshell_req, qshell_req_s::cmd, ll40ls::instance, ORB_ID, ORB_PRIO_DEFAULT, orb_publish_auto(), qshell_req_s::request_sequence, and qshell_req_s::strlen.
Referenced by main().
_wait_for_retval()
int QShell::_wait_for_retval () private
Definition at line 112 of file qshell.cpp.
References _current_sequence, _sub_qshell_retval, hrt_absolute_time(), hrt_abstime, hrt_elapsed_time(), orb_check(), orb_copy(), ORB_ID, orb_subscribe(), qshell_retval_s::return_sequence, and qshell_retval_s::return_value.
Referenced by main().
main() [1/2]
int QShell::main (std::vector< std::string > argList)
Definition at line 58 of file qshell.cpp.
References _send_cmd(), and _wait_for_retval().
Referenced by qshell_entry(), and qshell_main().
main() [2/2]
int QShell::main ()
Definition at line 72 of file qshell.cpp.
References appState, qshell_req_s::cmd, ll40ls::instance, m_qshell_req, orb_advert_t, orb_copy(), ORB_ID, ORB_PRIO_DEFAULT, orb_publish_auto(), orb_subscribe(), px4_poll(), qshell_req_s::request_sequence, qshell_retval_s::return_sequence, qshell_retval_s::return_value, run_cmd(), and qshell_req_s::strlen.
Referenced by ~QShell().
run_cmd()
int QShell::run_cmd (const std::vector< std::string > & appargs)
Definition at line 143 of file qshell.cpp.
References command, m_apps, and MAX_ARGS.
Referenced by main(), and ~QShell().
Member Data Documentation
_current_sequence
uint32_t QShell::_current_sequence = 0 static private
Definition at line 64 of file qshell.h.
Referenced by _send_cmd(), and _wait_for_retval().
_pub_qshell_req
orb_advert_t QShell::_pub_qshell_req = nullptr static private
Definition at line 62 of file qshell.h.
Referenced by _send_cmd().
_sub_qshell_retval
int QShell::_sub_qshell_retval = -1 static private
Definition at line 63 of file qshell.h.
Referenced by _wait_for_retval().
appState
static px4::AppState QShell::appState static
Definition at line 56 of file qshell.h.
Referenced by main(), qshell_main(), and ~QShell().
m_apps
apps_map_type QShell::m_apps private
Definition at line 63 of file qshell.h.
Referenced by run_cmd().
m_qshell_req
struct qshell_req_s QShell::m_qshell_req private
Definition at line 62 of file qshell.h.
Referenced by main().
The documentation for this class was generated from the following files:
src/drivers/qshell/posix/qshell.h
src/drivers/qshell/posix/qshell.cpp