PX4 Firmware: src/lib/perf/perf_counter.c File Reference
perf_counter.c File Reference
Performance measuring tools.
#include <stdlib.h>
#include <stdio.h>
#include <string.h>
#include <sys/queue.h>
#include <drivers/drv_hrt.h>
#include <math.h>
#include <pthread.h>
#include <systemlib/err.h>
#include "perf_counter.h"
Classes
struct perf_ctr_header
Header common to all counters.
struct perf_ctr_count
PC_EVENT counter.
struct perf_ctr_elapsed
PC_ELAPSED counter.
struct perf_ctr_interval
PC_INTERVAL counter.
Functions
perf_counter_t perf_alloc (enum perf_counter_type type, const char *name)
Create a new local counter.
perf_counter_t perf_alloc_once (enum perf_counter_type type, const char *name)
Get the reference to an existing counter or create a new one if it does not exist.
void perf_free (perf_counter_t handle)
Free a counter.
void perf_count (perf_counter_t handle)
Count a performance event.
void perf_begin (perf_counter_t handle)
Begin a performance event.
void perf_end (perf_counter_t handle)
End a performance event.
void perf_set_elapsed (perf_counter_t handle, int64_t elapsed)
Register a measurement.
void perf_set_count (perf_counter_t handle, uint64_t count)
Set a counter.
void perf_cancel (perf_counter_t handle)
Cancel a performance event.
void perf_reset (perf_counter_t handle)
Reset a performance counter.
void perf_print_counter (perf_counter_t handle)
Print one performance counter to stdout.
void perf_print_counter_fd (int fd, perf_counter_t handle)
Print one performance counter to a fd.
int perf_print_counter_buffer (char *buffer, int length, perf_counter_t handle)
Print one performance counter to a buffer.
uint64_t perf_event_count (perf_counter_t handle)
Return current event_count.
void perf_iterate_all (perf_callback cb, void *user)
Iterate over all performance counters using a callback.
void perf_print_all (int fd)
Print all of the performance counters.
void perf_print_latency (int fd)
Print hrt latency counters.
void perf_reset_all (void)
Reset all of the performance counters.
Variables
static sq_queue_t perf_counters = { NULL, NULL }
List of all known counters.
pthread_mutex_t perf_counters_mutex = PTHREAD_MUTEX_INITIALIZER
mutex protecting access to the perf_counters linked list (which is read from & written to by different threads)
const uint16_t latency_bucket_count
uint32_t latency_counters []
const uint16_t latency_buckets []
Detailed Description
Performance measuring tools.
Definition in file perf_counter.c.
Function Documentation
perf_counter_t perf_alloc (enum perf_counter_type type, const char * name)
Create a new local counter.
Parameters
type The type of the new counter.
name The counter name.
Returns
Handle for the new counter, or NULL if a counter could not be allocated.
Definition at line 121 of file perf_counter.c.
Referenced by perf_alloc_once().
perf_counter_t perf_alloc_once (enum perf_counter_type type, const char * name)
Get the reference to an existing counter or create a new one if it does not exist.
Parameters
type The type of the counter.
name The counter name.
Returns
Handle for the counter, or NULL if a counter could not be allocated.
Definition at line 155 of file perf_counter.c.
References perf_ctr_header::link, perf_ctr_header::name, perf_alloc(), perf_counters, perf_counters_mutex, pthread_mutex_lock(), pthread_mutex_unlock(), and perf_ctr_header::type.
Referenced by AttitudeEstimatorQ::task_main(), and WindEstimatorModule::WindEstimatorModule().
void perf_begin (perf_counter_t handle)
Begin a performance event.
This call applies to counters that operate over ranges of time; PC_ELAPSED etc.
Parameters
handle The handle returned from perf_alloc.
Definition at line 256 of file perf_counter.c.
Referenced by leddar_one::_cycle(), land_detector::LandDetector::_cycle(), ACCELSIM::_measure(), GYROSIM::_measure(), DfMS5607Wrapper::_publish(), DfMS5611Wrapper::_publish(), DfBmp280Wrapper::_publish(), DfAK8963Wrapper::_publish(), DfHmc5883Wrapper::_publish(), DfMPU6050Wrapper::_publish(), DfLsm9ds1Wrapper::_publish(), DfMpu9250Wrapper::_publish(), load_mon::LoadMon::_ram_used(), adc_measure(), at24c_bread(), at24c_bwrite(), at24c_initialize(), MS5525::collect(), ETSAirspeed::collect(), SDP3X::collect(), MEASAirspeed::collect(), MEASAirspeedSim::collect(), BAROSIM::collect(), BMP280::collect(), TFMINI::collect(), SF0X::collect(), SF1XX::collect(), LSM303AGR::collect(), VL53LXX::collect(), PMW3901::collect(), TERARANGER::collect(), LidarLiteI2C::collect(), HC_SR04::collect(), MB12XX::collect(), SRF02::collect(), PX4FLOW::collect(), LPS22HB::collect(), MPL3115A2::collect(), LIS3MDL::collect(), MS5611::collect(), BMM150::collect(), LPS25H::collect(), HMC5883::collect(), IST8310::collect(), controls_tick(), WindEstimatorModule::cycle(), RCInput::cycle(), OREOLED::cycle(), dsm_port_input(), ACCELSIM::mag_measure(), FXOS8701CQ::mag_measure(), LSM303D::mag_measure(), LidarLitePWM::measure(), BMP280::measure(), ADIS16477::measure(), BMA180::measure(), MPL3115A2::measure(), MS5611::measure(), BMI055_gyro::measure(), BMI055_accel::measure(), BMM150::measure(), FXOS8701CQ::measure(), L3GD20::measure(), MPU6000::measure(), FXAS21002C::measure(), ADIS16448::measure(), LSM303D::measure(), BMI160::measure(), MPU9250::measure(), param_export(), param_find_internal(), param_get(), param_set_internal(), MulticopterAttitudeControl::run(), FixedwingAttitudeControl::run(), Navigator::run(), Ekf2::run(), px4::logger::LogWriterFile::run(), FixedwingPositionControl::run(), Sensors::run(), rx_dma_callback(), GroundRoverAttitudeControl::task_main(), GroundRoverPositionControl::task_main(), PX4IO::task_main(), Mavlink::task_main(), test_perf(), Simulator::update_sensors(), user_start(), and PX4IO::write().
void perf_cancel (perf_counter_t handle)
Cancel a performance event.
This call applies to counters that operate over ranges of time; PC_ELAPSED etc. It reverts the effect of a previous perf_begin.
Parameters
handle The handle returned from perf_alloc.
Definition at line 378 of file perf_counter.c.
Referenced by leddar_one::_cycle(), BMP280::collect(), BMP280::measure(), and BMM150::measure().
void perf_count (perf_counter_t handle)
Count a performance event.
This call only affects counters that take single events; PC_COUNT, PC_INTERVAL etc.
Parameters
handle The handle returned from perf_alloc.
Definition at line 197 of file perf_counter.c.
Referenced by leddar_one::_cycle(), MPU9250_mag::_measure(), at24c_bread(), at24c_bwrite(), HMC5883::check_conf(), IST8310::check_conf(), MPU9250::check_duplicate(), MPU9250::check_null_data(), HMC5883::check_range(), BMI055_gyro::check_registers(), BMI055_accel::check_registers(), FXOS8701CQ::check_registers(), L3GD20::check_registers(), FXAS21002C::check_registers(), LSM303D::check_registers(), MPU6000::check_registers(), BMI160::check_registers(), MPU9250::check_registers(), MS5525::collect(), ETSAirspeed::collect(), SDP3X::collect(), MEASAirspeed::collect(), MEASAirspeedSim::collect(), BAROSIM::collect(), BMP280::collect(), TFMINI::collect(), SF0X::collect(), SF1XX::collect(), VL53LXX::collect(), TERARANGER::collect(), LidarLiteI2C::collect(), SRF02::collect(), MB12XX::collect(), PX4FLOW::collect(), LPS22HB::collect(), MPL3115A2::collect(), LIS3MDL::collect(), MS5611::collect(), BMM150::collect(), LPS25H::collect(), HMC5883::collect(), IST8310::collect(), Mavlink::count_txerr(), WindEstimatorModule::cycle(), RCInput::cycle(), ETSAirspeed::cycle(), OREOLED::cycle(), GYROSIM::devRead(), GYROSIM::gyro_read(), ADIS16448::gyro_read(), BMI160::gyro_read(), MPU9250::gyro_read(), Simulator::handle_message(), hott_telemetry_thread_main(), hx_rx_frame(), hx_stream_send(), MS5525::init_ms5525(), SDP3X::init_sdp3x(), ADIS16448::mag_read(), MS5525::measure(), ETSAirspeed::measure(), LidarLitePWM::measure(), MEASAirspeed::measure(), MEASAirspeedSim::measure(), LidarLiteI2C::measure(), BMP280::measure(), SF0X::measure(), SF1XX::measure(), VL53LXX::measure(), TERARANGER::measure(), MB12XX::measure(), SRF02::measure(), PX4FLOW::measure(), LPS22HB::measure(), MPL3115A2::measure(), MS5611::measure(), BMI055_gyro::measure(), LIS3MDL::measure(), BMI055_accel::measure(), BMM150::measure(), LPS25H::measure(), HMC5883::measure(), FXOS8701CQ::measure(), L3GD20::measure(), MPU6000::measure(), FXAS21002C::measure(), ADIS16448::measure(), IST8310::measure(), LSM303D::measure(), BMI160::measure(), PX4IO_serial::read(), MPU9250_mag::read(), ADIS16448::read(), MPU9250::read(), BMI160::read(), PCA9685::read8(), PMW3901::readMotionCount(), VL53LXX::readRegister(), PMW3901::readRegister(), VL53LXX::readRegisterMulti(), recv_req_id(), MPU6000::reset(), FixedwingAttitudeControl::run(), rx_handle_packet(), serial_interrupt(), HMC5883::set_excitement(), LIS3MDL::set_excitement(), HMC5883::set_range(), LIS3MDL::set_range(), IST8310::set_selftest(), HMC5883::set_temperature_compensation(), PCA9685::setPWM(), GroundRoverAttitudeControl::task_main(), test_perf(), UavcanEscController::update_outputs(), user_start(), PX4IO_serial::write(), PCA9685::write8(), VL53LXX::writeRegister(), PMW3901::writeRegister(), and VL53LXX::writeRegisterMulti().
void perf_end (perf_counter_t handle)
End a performance event.
This call applies to counters that operate over ranges of time; PC_ELAPSED etc. If a call is made without a corresponding perf_begin call, or if perf_cancel has been called subsequently, no change is made to the counter.
Parameters
handle The handle returned from perf_alloc.
Definition at line 273 of file perf_counter.c.
Referenced by leddar_one::_cycle(), land_detector::LandDetector::_cycle(), ACCELSIM::_measure(), GYROSIM::_measure(), DfMS5607Wrapper::_publish(), DfMS5611Wrapper::_publish(), DfBmp280Wrapper::_publish(), DfHmc5883Wrapper::_publish(), DfAK8963Wrapper::_publish(), DfMPU6050Wrapper::_publish(), DfLsm9ds1Wrapper::_publish(), DfMpu9250Wrapper::_publish(), load_mon::LoadMon::_ram_used(), adc_measure(), at24c_bread(), at24c_bwrite(), at24c_initialize(), MPU9250::check_duplicate(), MPU9250::check_null_data(), MS5525::collect(), ETSAirspeed::collect(), SDP3X::collect(), MEASAirspeed::collect(), MEASAirspeedSim::collect(), BAROSIM::collect(), BMP280::collect(), TFMINI::collect(), SF0X::collect(), SF1XX::collect(), LSM303AGR::collect(), VL53LXX::collect(), PMW3901::collect(), TERARANGER::collect(), LidarLiteI2C::collect(), HC_SR04::collect(), MB12XX::collect(), SRF02::collect(), PX4FLOW::collect(), LPS22HB::collect(), MPL3115A2::collect(), LIS3MDL::collect(), MS5611::collect(), BMM150::collect(), LPS25H::collect(), HMC5883::collect(), IST8310::collect(), controls_tick(), WindEstimatorModule::cycle(), RCInput::cycle(), OREOLED::cycle(), dsm_port_input(), ACCELSIM::mag_measure(), FXOS8701CQ::mag_measure(), LSM303D::mag_measure(), LidarLitePWM::measure(), BMP280::measure(), ADIS16477::measure(), BMA180::measure(), MPL3115A2::measure(), MS5611::measure(), BMI055_gyro::measure(), BMI055_accel::measure(), BMM150::measure(), FXOS8701CQ::measure(), L3GD20::measure(), MPU6000::measure(), FXAS21002C::measure(), ADIS16448::measure(), LSM303D::measure(), BMI160::measure(), MPU9250::measure(), param_export(), param_find_internal(), param_get(), param_set_internal(), MulticopterAttitudeControl::run(), FixedwingAttitudeControl::run(), Navigator::run(), Ekf2::run(), px4::logger::LogWriterFile::run(), FixedwingPositionControl::run(), Sensors::run(), rx_dma_callback(), AttitudeEstimatorQ::task_main(), GroundRoverAttitudeControl::task_main(), GroundRoverPositionControl::task_main(), PX4IO::task_main(), Mavlink::task_main(), test_perf(), user_start(), and PX4IO::write().
uint64_t perf_event_count (perf_counter_t handle)
Return current event_count.
Parameters
handle The counter returned from perf_alloc.
Returns
event_count
Definition at line 545 of file perf_counter.c.
Referenced by MPU9250_mag::_measure(), ACCELSIM::_measure(), MS5525::collect(), ETSAirspeed::collect(), SDP3X::collect(), MEASAirspeed::collect(), MEASAirspeedSim::collect(), BAROSIM::collect(), BMP280::collect(), LSM303AGR::collect(), LidarLiteI2C::collect(), HC_SR04::collect(), LPS22HB::collect(), MPL3115A2::collect(), LIS3MDL::collect(), MS5611::collect(), BMM150::collect(), LPS25H::collect(), HMC5883::collect(), IST8310::collect(), FXOS8701CQ::mag_measure(), LSM303D::mag_measure(), LidarLiteI2C::measure(), ADIS16477::measure(), BMI055_gyro::measure(), BMI055_accel::measure(), FXOS8701CQ::measure(), L3GD20::measure(), MPU6000::measure(), FXAS21002C::measure(), ADIS16448::measure(), LSM303D::measure(), BMI160::measure(), MPU9250::measure(), ADIS16477::publish_accel(), ADIS16477::publish_gyro(), GYROSIM::self_test(), BMI055_gyro::self_test(), BMI055_accel::self_test(), BMM150::self_test(), ADIS16448::self_test(), MPU6000::self_test(), BMI160::self_test(), and MPU9250::self_test().
void perf_free (perf_counter_t handle)
Free a counter.
Parameters
handle The performance counter's handle.
Definition at line 184 of file perf_counter.c.
Referenced by hott_telemetry_thread_main(), hx_stream_free(), linux_pwm_out::task_main(), snapdragon_pwm::task_main(), test_perf(), ACCELSIM::~ACCELSIM(), ADIS16448::~ADIS16448(), ADIS16477::~ADIS16477(), Airspeed::~Airspeed(), AirspeedSim::~AirspeedSim(), BAROSIM::~BAROSIM(), BMA180::~BMA180(), BMI055_accel::~BMI055_accel(), BMI055_gyro::~BMI055_gyro(), BMI160::~BMI160(), BMM150::~BMM150(), BMP280::~BMP280(), DfAK8963Wrapper::~DfAK8963Wrapper(), DfBmp280Wrapper::~DfBmp280Wrapper(), DfHmc5883Wrapper::~DfHmc5883Wrapper(), DfLsm9ds1Wrapper::~DfLsm9ds1Wrapper(), DfMPU6050Wrapper::~DfMPU6050Wrapper(), DfMpu9250Wrapper::~DfMpu9250Wrapper(), DfMS5607Wrapper::~DfMS5607Wrapper(), DfMS5611Wrapper::~DfMS5611Wrapper(), Ekf2::~Ekf2(), FixedwingAttitudeControl::~FixedwingAttitudeControl(), FixedwingPositionControl::~FixedwingPositionControl(), FXAS21002C::~FXAS21002C(), FXOS8701CQ::~FXOS8701CQ(), GroundRoverAttitudeControl::~GroundRoverAttitudeControl(), GYROSIM::~GYROSIM(), HC_SR04::~HC_SR04(), HMC5883::~HMC5883(), IST8310::~IST8310(), L3GD20::~L3GD20(), land_detector::LandDetector::~LandDetector(), leddar_one::~leddar_one(), LidarLiteI2C::~LidarLiteI2C(), LidarLitePWM::~LidarLitePWM(), LIS3MDL::~LIS3MDL(), load_mon::LoadMon::~LoadMon(), px4::logger::LogWriterFile::~LogWriterFile(), LPS22HB::~LPS22HB(), LPS25H::~LPS25H(), LSM303AGR::~LSM303AGR(), LSM303D::~LSM303D(), Mavlink::~Mavlink(), MB12XX::~MB12XX(), MPL3115A2::~MPL3115A2(), MPU6000::~MPU6000(), MPU9250::~MPU9250(), MPU9250_mag::~MPU9250_mag(), MS5611::~MS5611(), OREOLED::~OREOLED(), PMW3901::~PMW3901(), PWMSim::~PWMSim(), PX4FLOW::~PX4FLOW(), PX4FMU::~PX4FMU(), PX4IO::~PX4IO(), PX4IO_serial::~PX4IO_serial(), RCInput::~RCInput(), SF0X::~SF0X(), SF1XX::~SF1XX(), SRF02::~SRF02(), TAP_ESC::~TAP_ESC(), TERARANGER::~TERARANGER(), TFMINI::~TFMINI(), UavcanEscController::~UavcanEscController(), UavcanNode::~UavcanNode(), VL53LXX::~VL53LXX(), and WindEstimatorModule::~WindEstimatorModule().
void perf_iterate_all (perf_callback cb, void * user)
Iterate over all performance counters using a callback.
Caution: This will aquire the mutex, so do not call any other perf_* method that aquire the mutex as well from the callback (If this is needed, configure the mutex to be reentrant).
Parameters
cb callback method
user custom argument for the callback
Definition at line 573 of file perf_counter.c.
Referenced by px4::logger::Logger::write_perf_data().
void perf_print_all (int fd)
Print all of the performance counters.
Parameters
fd File descriptor to print to - e.g. 0 for stdout
Definition at line 587 of file perf_counter.c.
Referenced by perf_main(), and test_perf().
void perf_print_counter (perf_counter_t handle)
Print one performance counter to stdout.
Parameters
handle The counter to print.
Definition at line 435 of file perf_counter.c.
Referenced by hott_telemetry_main(), OREOLED::info(), DfMPU6050Wrapper::info(), DfLsm9ds1Wrapper::info(), DfMpu9250Wrapper::info(), ADIS16477::print_info(), LidarLitePWM::print_info(), AirspeedSim::print_info(), LidarLiteI2C::print_info(), BAROSIM::print_info(), TFMINI::print_info(), SF0X::print_info(), LPS22HB::print_info(), SF1XX::print_info(), HC_SR04::print_info(), BMP280::print_info(), LSM303AGR::print_info(), MB12XX::print_info(), SRF02::print_info(), TERARANGER::print_info(), PX4FLOW::print_info(), MPL3115A2::print_info(), PMW3901::print_info(), VL53LXX::print_info(), LIS3MDL::print_info(), GYROSIM::print_info(), BMA180::print_info(), MS5611::print_info(), MPU6000::print_info(), HMC5883::print_info(), BMI055_gyro::print_info(), BMI055_accel::print_info(), FXOS8701CQ::print_info(), ADIS16448::print_info(), IST8310::print_info(), LPS25H::print_info(), L3GD20::print_info(), BMM150::print_info(), FXAS21002C::print_info(), LSM303D::print_info(), MPU9250::print_info(), BMI160::print_info(), WindEstimatorModule::print_status(), RCInput::print_status(), load_mon::LoadMon::print_status(), Ekf2::print_status(), and test_perf().
int perf_print_counter_buffer (char * buffer, int length, perf_counter_t handle)
Print one performance counter to a buffer.
Parameters
buffer buffer to write to
length buffer length
handle The counter to print.
return number of bytes written
Definition at line 493 of file perf_counter.c.
Referenced by px4::logger::Logger::perf_iterate_callback().
void perf_print_counter_fd (int fd, perf_counter_t handle)
Print one performance counter to a fd.
Parameters
fd File descriptor to print to - e.g. 0 for stdout
handle The counter to print.
Definition at line 445 of file perf_counter.c.
Referenced by perf_print_all(), and perf_print_counter().
void perf_print_latency (int fd)
Print hrt latency counters.
Parameters
fd File descriptor to print to - e.g. 0 for stdout
Definition at line 606 of file perf_counter.c.
References latency_bucket_count, latency_buckets, and latency_counters.
Referenced by perf_main().
void perf_reset (perf_counter_t handle)
Reset a performance counter.
This call resets performance counter to initial state
Parameters
handle The handle returned from perf_alloc.
Definition at line 400 of file perf_counter.c.
Referenced by hott_telemetry_thread_main(), and perf_reset_all().
void perf_reset_all (void)
Reset all of the performance counters.
Definition at line 619 of file perf_counter.c.
Referenced by perf_main(), and px4::logger::Logger::start_log_file().
void perf_set_count (perf_counter_t handle, uint64_t count)
Set a counter.
This call applies to counters of type PC_COUNT. It (re-)sets the count.
Parameters
handle The handle returned from perf_alloc.
count The counter value to be set.
Definition at line 359 of file perf_counter.c.
References PC_COUNT, and perf_ctr_header::type.
Referenced by DfMPU6050Wrapper::_publish(), DfLsm9ds1Wrapper::_publish(), and DfMpu9250Wrapper::_publish().
void perf_set_elapsed (perf_counter_t handle, int64_t elapsed)
Register a measurement.
This call applies to counters that operate over ranges of time; PC_ELAPSED etc. If a call is made without a corresponding perf_begin call. It sets the value provided as argument as a new measurement.
Parameters
handle The handle returned from perf_alloc.
elapsed The time elapsed. Negative values lead to incrementing the overrun counter.
Definition at line 318 of file perf_counter.c.
References dt, perf_ctr_elapsed::event_count, perf_ctr_elapsed::M2, perf_ctr_elapsed::mean, PC_ELAPSED, perf_ctr_elapsed::time_least, perf_ctr_elapsed::time_most, perf_ctr_elapsed::time_start, perf_ctr_elapsed::time_total, and perf_ctr_header::type.
Referenced by TAP_ESC::cycle(), PX4FMU::cycle(), Simulator::handle_message(), PX4IO::io_set_control_state(), PWMSim::run(), UavcanNode::run(), linux_pwm_out::task_main(), and snapdragon_pwm::task_main().
Variable Documentation
const uint16_t latency_bucket_count
Referenced by perf_print_all(), perf_print_latency(), and perf_reset_all().
const uint16_t latency_buckets[]
Referenced by perf_print_all(), and perf_print_latency().
uint32_t latency_counters[]
Referenced by perf_print_all(), perf_print_latency(), and perf_reset_all().
sq_queue_t perf_counters = { NULL, NULL } static
List of all known counters.
Definition at line 106 of file perf_counter.c.
Referenced by perf_alloc(), perf_alloc_once(), perf_free(), perf_iterate_all(), perf_print_all(), and perf_reset_all().
pthread_mutex_t perf_counters_mutex = PTHREAD_MUTEX_INITIALIZER
mutex protecting access to the perf_counters linked list (which is read from & written to by different threads)
Definition at line 111 of file perf_counter.c.
Referenced by perf_alloc(), perf_alloc_once(), perf_free(), perf_iterate_all(), perf_print_all(), and perf_reset_all().