PX4 Firmware: CameraInterface Class Reference
CameraInterface Class Reference
#include <camera_interface.h>
Public Member Functions
CameraInterface ()
Constructor.
virtual ~CameraInterface ()=default
Destructor.
virtual void trigger (bool trigger_on_true)
trigger the camera
virtual void send_toggle_power (bool enable)
send command to turn the camera on/off
virtual void send_keep_alive (bool enable)
send command to prevent the camera from sleeping
virtual void info ()
Display info.
virtual bool has_power_control ()
Checks if the interface has support for camera power control.
virtual bool is_powered_on ()
Checks if the camera connected to the interface is turned on.
Protected Member Functions
virtual void setup ()
setup the interface
void get_pins ()
get the hardware configuration
Protected Attributes
param_t _p_pin
int _pins [6]
Detailed Description
Definition at line 12 of file camera_interface.h.
Constructor & Destructor Documentation
CameraInterface()
CameraInterface::CameraInterface ()
Constructor.
Definition at line 9 of file camera_interface.cpp.
~CameraInterface()
virtual CameraInterface::~CameraInterface () virtual default
Destructor.
Member Function Documentation
get_pins()
void CameraInterface::get_pins () protected
get the hardware configuration
Definition at line 15 of file camera_interface.cpp.
References _p_pin, _pins, arraySize, param_find(), param_get(), and PARAM_INVALID.
Referenced by setup().
has_power_control()
virtual bool CameraInterface::has_power_control () inline virtual
Checks if the interface has support for camera power control.
Returns
true if power control is supported
Definition at line 54 of file camera_interface.h.
Referenced by CameraTrigger::Run(), CameraTrigger::start(), and CameraTrigger::status().
info()
virtual void CameraInterface::info () inline virtual
Display info.
Definition at line 47 of file camera_interface.h.
Referenced by CameraTrigger::status().
is_powered_on()
virtual bool CameraInterface::is_powered_on () inline virtual
Checks if the camera connected to the interface is turned on.
Returns
true if camera is on
Definition at line 61 of file camera_interface.h.
Referenced by CameraTrigger::Run(), CameraTrigger::start(), and CameraTrigger::status().
send_keep_alive()
virtual void CameraInterface::send_keep_alive (bool enable) inline virtual
send command to prevent the camera from sleeping
Parameters
enable
Definition at line 42 of file camera_interface.h.
Referenced by CameraTrigger::keep_alive_down(), and CameraTrigger::keep_alive_up().
send_toggle_power()
virtual void CameraInterface::send_toggle_power (bool enable) inline virtual
send command to turn the camera on/off
Parameters
enable
Definition at line 36 of file camera_interface.h.
Referenced by CameraTrigger::disengage_turn_on_off(), and CameraTrigger::engange_turn_on_off().
setup()
virtual void CameraInterface::setup () inline protected virtual
setup the interface
Definition at line 68 of file camera_interface.h.
References get_pins().
trigger()
virtual void CameraInterface::trigger (bool trigger_on_true) inline virtual
trigger the camera
Parameters
enable
Definition at line 30 of file camera_interface.h.
Referenced by CameraTrigger::disengage(), and CameraTrigger::engage().
Member Data Documentation
_p_pin
param_t CameraInterface::_p_pin protected
Definition at line 75 of file camera_interface.h.
Referenced by get_pins().
_pins
int CameraInterface::_pins[6] protected
Definition at line 77 of file camera_interface.h.
Referenced by get_pins().
The documentation for this class was generated from the following files:
src/drivers/camera_trigger/interfaces/src/camera_interface.h
src/drivers/camera_trigger/interfaces/src/camera_interface.cpp