PX4 Firmware: leddar_one Class Reference
leddar_one Class Reference
Public Member Functions
leddar_one (const char *device_path, const char *serial_port, uint8_t rotation)
virtual ~leddar_one ()
virtual int init ()
Initialise the driver and make it ready for use.
void start ()
void stop ()
virtual ssize_t read (struct file *filp, char *buffer, size_t buflen)
Public Member Functions inherited from device::CDev
CDev (const char *name, const char *devname)
Constructor.
virtual ~CDev ()
virtual int open (file_t *filep)
Handle an open of the device.
virtual int close (file_t *filep)
Handle a close of the device.
virtual ssize_t read (file_t *filep, char *buffer, size_t buflen)
Perform a read from the device.
virtual ssize_t write (file_t *filep, const char *buffer, size_t buflen)
Perform a write to the device.
virtual off_t seek (file_t *filep, off_t offset, int whence)
Perform a logical seek operation on the device.
virtual int ioctl (file_t *filep, int cmd, unsigned long arg)
Perform an ioctl operation on the device.
virtual int poll (file_t *filep, px4_pollfd_struct_t *fds, bool setup)
Perform a poll setup/teardown operation.
Public Member Functions inherited from device::Device
virtual ~Device ()=default
Destructor.
virtual int read (unsigned address, void *data, unsigned count)
Read directly from the device.
virtual int write (unsigned address, void *data, unsigned count)
Write directly to the device.
virtual int ioctl (unsigned operation, unsigned &arg)
Perform a device-specific operation.
uint8_t get_device_bus ()
Return the bus ID the device is connected to.
DeviceBusType get_device_bus_type ()
Return the bus type the device is connected to.
uint8_t get_device_address ()
Return the bus address of the device.
void set_device_address (int address)
void set_device_type (uint8_t devtype)
Set the device type.
virtual bool external ()
Private Types
enum { state_waiting_reading = 0, state_reading_requested }
Private Member Functions
int _fd_open ()
bool _request ()
int _collect ()
void _publish (uint16_t distance_cm)
int _cycle ()
Static Private Member Functions
static void cycle_trampoline (void *arg)
Private Attributes
work_s _work
int _fd = -1
const char * _serial_port
uint8_t _rotation
uint8_t _buffer [sizeof(struct reading_msg)]
uint8_t _buffer_len = 0
orb_advert_t _topic = nullptr
ringbuffer::RingBuffer * _reports = nullptr
enum leddar_one:: { ... } _state = state_waiting_reading
hrt_abstime _timeout_usec = 0
perf_counter_t _collect_timeout_perf
perf_counter_t _comm_error
perf_counter_t _sample_perf
Additional Inherited Members
Public Types inherited from device::Device
enum DeviceBusType { DeviceBusType_UNKNOWN = 0, DeviceBusType_I2C = 1, DeviceBusType_SPI = 2, DeviceBusType_UAVCAN = 3 }
Device bus types for DEVID.
Protected Member Functions inherited from device::CDev
virtual pollevent_t poll_state (file_t *filep)
Check the current state of the device for poll events from the perspective of the file.
virtual void poll_notify (pollevent_t events)
Report new poll events.
virtual void poll_notify_one (px4_pollfd_struct_t *fds, pollevent_t events)
Internal implementation of poll_notify.
virtual int open_first (file_t *filep)
Notification of the first open.
virtual int close_last (file_t *filep)
Notification of the last close.
virtual int register_class_devname (const char *class_devname)
Register a class device name, automatically adding device class instance suffix if need be.
virtual int unregister_class_devname (const char *class_devname, unsigned class_instance)
Register a class device name, automatically adding device class instance suffix if need be.
const char * get_devname ()
Get the device name.
void lock ()
Take the driver lock.
void unlock ()
Release the driver lock.
Protected Member Functions inherited from device::Device
Device (const char *name)
Device (DeviceBusType bus_type, uint8_t bus, uint8_t address, uint8_t devtype=0)
Device (const Device &)=delete
Device & operator= (const Device &)=delete
Device (Device &&)=delete
Device & operator= (Device &&)=delete
Protected Attributes inherited from device::CDev
px4_sem_t _lock
lock to protect access to all class members (also for derived classes)
bool _pub_blocked {false}
true if publishing should be blocked
Protected Attributes inherited from device::Device
union DeviceId _device_id
device identifier information
const char * _name
driver name
bool _debug_enabled {false}
if true, debug messages are printed
Static Protected Attributes inherited from device::CDev
static const px4_file_operations_t fops = {}
Pointer to the default cdev file operations table; useful for registering clone devices etc.
Detailed Description
Definition at line 110 of file leddar_one.cpp.
Member Enumeration Documentation
anonymous enum private
Enumerator
state_waiting_reading
state_reading_requested
Definition at line 136 of file leddar_one.cpp.
Constructor & Destructor Documentation
leddar_one::leddar_one (const char * device_path, const char * serial_port, uint8_t rotation)
Definition at line 244 of file leddar_one.cpp.
References _serial_port.
leddar_one::~leddar_one () virtual
Definition at line 255 of file leddar_one.cpp.
References _collect_timeout_perf, _comm_error, _fd, _reports, _sample_perf, _serial_port, _topic, device::CDev::close(), orb_unadvertise(), perf_free(), and stop().
Member Function Documentation
int leddar_one::_collect () private
Definition at line 460 of file leddar_one.cpp.
References _buffer, _buffer_len, _calc_crc16(), _fd, _publish(), MODBUS_READING_FUNCTION, MODBUS_SLAVE_ADDRESS, msg, and read().
Referenced by _cycle().
int leddar_one::_cycle () private
Definition at line 493 of file leddar_one.cpp.
References _buffer_len, _collect(), _collect_timeout_perf, _comm_error, _request(), _sample_perf, _state, _timeout_usec, COLLECT_USEC_TIMEOUT, hrt_absolute_time(), hrt_abstime, perf_begin(), perf_cancel(), perf_count(), perf_end(), READING_USEC_PERIOD, state_reading_requested, and state_waiting_reading.
Referenced by cycle_trampoline(), and init().
int leddar_one::_fd_open () private
Definition at line 278 of file leddar_one.cpp.
References _fd, _serial_port, device::CDev::close(), device::CDev::open(), PX4_ERR, PX4_ERROR, and PX4_OK.
Referenced by cycle_trampoline(), and init().
void leddar_one::_publish (uint16_t distance_cm) private
Definition at line 403 of file leddar_one.cpp.
References _reports, _rotation, _topic, distance_sensor_s::covariance, distance_sensor_s::current_distance, f(), hrt_absolute_time(), distance_sensor_s::id, MAX_DISTANCE, distance_sensor_s::max_distance, MIN_DISTANCE, distance_sensor_s::min_distance, orb_advertise(), ORB_ID, orb_publish(), distance_sensor_s::orientation, distance_sensor_s::signal_quality, distance_sensor_s::timestamp, and distance_sensor_s::type.
Referenced by _collect().
bool leddar_one::_request () private
Definition at line 427 of file leddar_one.cpp.
References _fd, request_reading_msg, and device::CDev::write().
Referenced by _cycle().
void leddar_one::cycle_trampoline (void * arg) static private
Definition at line 388 of file leddar_one.cpp.
References _cycle(), _fd, _fd_open(), _work, and WORK_USEC_INTERVAL.
Referenced by start().
int leddar_one::init () virtual
Initialise the driver and make it ready for use.
Returns
OK if the driver initialized OK, negative errno otherwise;
Reimplemented from device::CDev.
Definition at line 331 of file leddar_one.cpp.
References _cycle(), _fd_open(), _reports, hrt_absolute_time(), hrt_abstime, lis3mdl::init(), NAME, PROBE_USEC_TIMEOUT, PX4_ERR, PX4_ERROR, PX4_OK, and usleep().
Referenced by leddar_one_main().
ssize_t leddar_one::read (struct file * filp, char * buffer, size_t buflen) virtual
Definition at line 542 of file leddar_one.cpp.
References _reports.
Referenced by _collect().
void leddar_one::start ()
Definition at line 374 of file leddar_one.cpp.
References _fd, device::CDev::close(), cycle_trampoline(), and WORK_USEC_INTERVAL.
Referenced by leddar_one_main().
void leddar_one::stop ()
Definition at line 369 of file leddar_one.cpp.
Referenced by ~leddar_one().
Member Data Documentation
uint8_t leddar_one::_buffer[sizeof(struct reading_msg)] private
Definition at line 130 of file leddar_one.cpp.
Referenced by _collect().
uint8_t leddar_one::_buffer_len = 0 private
Definition at line 131 of file leddar_one.cpp.
Referenced by _collect(), and _cycle().
perf_counter_t leddar_one::_collect_timeout_perf private
Definition at line 142 of file leddar_one.cpp.
Referenced by _cycle(), and ~leddar_one().
perf_counter_t leddar_one::_comm_error private
Definition at line 143 of file leddar_one.cpp.
Referenced by _cycle(), and ~leddar_one().
int leddar_one::_fd = -1 private
Definition at line 125 of file leddar_one.cpp.
Referenced by _collect(), _fd_open(), _request(), cycle_trampoline(), start(), and ~leddar_one().
ringbuffer::RingBuffer* leddar_one::_reports = nullptr private
Definition at line 134 of file leddar_one.cpp.
Referenced by _publish(), init(), read(), and ~leddar_one().
uint8_t leddar_one::_rotation private
Definition at line 128 of file leddar_one.cpp.
Referenced by _publish().
perf_counter_t leddar_one::_sample_perf private
Definition at line 144 of file leddar_one.cpp.
Referenced by _cycle(), and ~leddar_one().
const char* leddar_one::_serial_port private
Definition at line 126 of file leddar_one.cpp.
Referenced by _fd_open(), leddar_one(), and ~leddar_one().
enum { ... } leddar_one::_state
Referenced by _cycle().
hrt_abstime leddar_one::_timeout_usec = 0 private
Definition at line 140 of file leddar_one.cpp.
Referenced by _cycle().
orb_advert_t leddar_one::_topic = nullptr private
Definition at line 133 of file leddar_one.cpp.
Referenced by _publish(), and ~leddar_one().
work_s leddar_one::_work private
Definition at line 123 of file leddar_one.cpp.
Referenced by cycle_trampoline().
The documentation for this class was generated from the following file:
src/drivers/distance_sensor/leddar_one/leddar_one.cpp