PX4 Firmware: MavlinkStreamVFRHUD Class Reference
MavlinkStreamVFRHUD Class Reference
Public Member Functions
const char * get_name () const override
uint16_t get_id () override
unsigned get_size () override
Get maximal total messages size on update.
Public Member Functions inherited from MavlinkStream
MavlinkStream (Mavlink *mavlink)
virtual ~MavlinkStream ()=default
MavlinkStream (const MavlinkStream &)=delete
MavlinkStream & operator= (const MavlinkStream &)=delete
MavlinkStream (MavlinkStream &&)=delete
MavlinkStream & operator= (MavlinkStream &&)=delete
void set_interval (const int interval)
Get the interval.
int get_interval ()
Get the interval.
int update (const hrt_abstime &t)
Update subscriptions and send message if necessary.
virtual bool const_rate ()
virtual unsigned get_size_avg ()
Get the average message size.
bool first_message_sent () const
void reset_last_sent ()
Reset the time of last sent to 0.
Public Member Functions inherited from ListNode< MavlinkStream *>
void setSibling (MavlinkStream * sibling)
const MavlinkStream * getSibling () const
Static Public Member Functions
static const char * get_name_static ()
static uint16_t get_id_static ()
static MavlinkStream * new_instance (Mavlink *mavlink)
Protected Member Functions
MavlinkStreamVFRHUD (Mavlink *mavlink)
bool send (const hrt_abstime t) override
Protected Member Functions inherited from MavlinkStream
virtual void update_data ()
Function to collect/update data for the streams at a high rate independant of actual stream rate.
Private Member Functions
MavlinkStreamVFRHUD (MavlinkStreamVFRHUD &)=delete
MavlinkStreamVFRHUD & operator= (const MavlinkStreamVFRHUD &)=delete
Private Attributes
MavlinkOrbSubscription * _pos_sub
uint64_t _pos_time
MavlinkOrbSubscription * _armed_sub
uint64_t _armed_time
MavlinkOrbSubscription * _act0_sub
MavlinkOrbSubscription * _act1_sub
MavlinkOrbSubscription * _airspeed_sub
uint64_t _airspeed_time
MavlinkOrbSubscription * _air_data_sub
Additional Inherited Members
Protected Attributes inherited from MavlinkStream
Mavlink *const _mavlink
int _interval {1000000}
if set to negative value = unlimited rate
Protected Attributes inherited from ListNode< MavlinkStream *>
MavlinkStream * _list_node_sibling
Detailed Description
Definition at line 1355 of file mavlink_messages.cpp.
Constructor & Destructor Documentation
MavlinkStreamVFRHUD() [1/2]
MavlinkStreamVFRHUD::MavlinkStreamVFRHUD (MavlinkStreamVFRHUD &) private delete
MavlinkStreamVFRHUD() [2/2]
MavlinkStreamVFRHUD::MavlinkStreamVFRHUD (Mavlink * mavlink) inline explicit protected
Definition at line 1409 of file mavlink_messages.cpp.
Member Function Documentation
get_id()
uint16_t MavlinkStreamVFRHUD::get_id () inline override virtual
Implements MavlinkStream.
Definition at line 1374 of file mavlink_messages.cpp.
References MavlinkStreamHeartbeat::get_id_static().
get_id_static()
static uint16_t MavlinkStreamVFRHUD::get_id_static () inline static
Definition at line 1369 of file mavlink_messages.cpp.
get_name()
const char* MavlinkStreamVFRHUD::get_name () const inline override virtual
Implements MavlinkStream.
Definition at line 1359 of file mavlink_messages.cpp.
References get_name_static().
get_name_static()
static const char* MavlinkStreamVFRHUD::get_name_static () inline static
Definition at line 1364 of file mavlink_messages.cpp.
Referenced by get_name().
get_size()
unsigned MavlinkStreamVFRHUD::get_size () inline override virtual
Get maximal total messages size on update.
Implements MavlinkStream.
Definition at line 1384 of file mavlink_messages.cpp.
new_instance()
static MavlinkStream* MavlinkStreamVFRHUD::new_instance (Mavlink * mavlink) inline static
Definition at line 1379 of file mavlink_messages.cpp.
operator=()
MavlinkStreamVFRHUD& MavlinkStreamVFRHUD::operator= (const MavlinkStreamVFRHUD &) private delete
send()
bool MavlinkStreamVFRHUD::send (const hrt_abstime t) inline override protected virtual
Implements MavlinkStream.
Definition at line 1421 of file mavlink_messages.cpp.
References MavlinkStream::_mavlink, actuator_armed_s::armed, armed, vehicle_air_data_s::baro_alt_meter, actuator_controls_s::control, math::degrees(), Mavlink::get_channel(), airspeed_s::indicated_airspeed_m_s, math::max(), msg, vehicle_local_position_s::ref_alt, vehicle_air_data_s::timestamp, MavlinkOrbSubscription::update(), vehicle_local_position_s::v_z_valid, vehicle_local_position_s::vx, vehicle_local_position_s::vy, vehicle_local_position_s::vz, matrix::wrap_2pi(), vehicle_local_position_s::yaw, vehicle_local_position_s::z, vehicle_local_position_s::z_global, and vehicle_local_position_s::z_valid.
Member Data Documentation
_act0_sub
MavlinkOrbSubscription* MavlinkStreamVFRHUD::_act0_sub private
Definition at line 1396 of file mavlink_messages.cpp.
_act1_sub
MavlinkOrbSubscription* MavlinkStreamVFRHUD::_act1_sub private
Definition at line 1397 of file mavlink_messages.cpp.
_air_data_sub
MavlinkOrbSubscription* MavlinkStreamVFRHUD::_air_data_sub private
Definition at line 1402 of file mavlink_messages.cpp.
_airspeed_sub
MavlinkOrbSubscription* MavlinkStreamVFRHUD::_airspeed_sub private
Definition at line 1399 of file mavlink_messages.cpp.
_airspeed_time
uint64_t MavlinkStreamVFRHUD::_airspeed_time private
Definition at line 1400 of file mavlink_messages.cpp.
_armed_sub
MavlinkOrbSubscription* MavlinkStreamVFRHUD::_armed_sub private
Definition at line 1393 of file mavlink_messages.cpp.
_armed_time
uint64_t MavlinkStreamVFRHUD::_armed_time private
Definition at line 1394 of file mavlink_messages.cpp.
_pos_sub
MavlinkOrbSubscription* MavlinkStreamVFRHUD::_pos_sub private
Definition at line 1390 of file mavlink_messages.cpp.
_pos_time
uint64_t MavlinkStreamVFRHUD::_pos_time private
Definition at line 1391 of file mavlink_messages.cpp.
The documentation for this class was generated from the following file:
src/modules/mavlink/mavlink_messages.cpp