PX4 Firmware: LSM303D Class Reference
LSM303D Class Reference
Public Member Functions
LSM303D (int bus, const char *path, uint32_t device, enum Rotation rotation)
virtual ~LSM303D ()
virtual int init ()
virtual ssize_t read (struct file *filp, char *buffer, size_t buflen)
virtual int ioctl (struct file *filp, int cmd, unsigned long arg)
void print_info ()
Diagnostics - print some basic information about the driver.
void print_registers ()
dump register values
void test_error ()
deliberately trigger an error
Protected Member Functions
virtual int probe ()
virtual ssize_t mag_read (struct file *filp, char *buffer, size_t buflen)
virtual int mag_ioctl (struct file *filp, int cmd, unsigned long arg)
Private Member Functions
void start ()
Start automatic measurement.
void stop ()
Stop automatic measurement.
void reset ()
Reset chip.
void disable_i2c ()
disable I2C on the chip
void check_registers (void)
check key registers for correct values
void measure ()
Fetch accel measurements from the sensor and update the report ring.
void mag_measure ()
Fetch mag measurements from the sensor and update the report ring.
uint8_t read_reg (unsigned reg)
Read a register from the LSM303D.
void write_reg (unsigned reg, uint8_t value)
Write a register in the LSM303D.
void modify_reg (unsigned reg, uint8_t clearbits, uint8_t setbits)
Modify a register in the LSM303D.
void write_checked_reg (unsigned reg, uint8_t value)
Write a register in the LSM303D, updating _checked_values.
int accel_set_range (unsigned max_g)
Set the LSM303D accel measurement range.
int mag_set_range (unsigned max_g)
Set the LSM303D mag measurement range.
int accel_set_onchip_lowpass_filter_bandwidth (unsigned bandwidth)
Set the LSM303D on-chip anti-alias filter bandwith.
int accel_set_driver_lowpass_filter (float samplerate, float bandwidth)
Set the driver lowpass filter bandwidth.
int accel_set_samplerate (unsigned frequency)
Set the LSM303D internal accel sampling frequency.
int mag_set_samplerate (unsigned frequency)
Set the LSM303D internal mag sampling frequency.
LSM303D (const LSM303D &)
LSM303D operator= (const LSM303D &)
Static Private Member Functions
static void measure_trampoline (void *arg)
Static trampoline from the hrt_call context; because we don't have a generic hrt wrapper yet.
static void mag_measure_trampoline (void *arg)
Static trampoline for the mag because it runs at a lower rate.
Private Attributes
LSM303D_mag * _mag
struct hrt_call _accel_call
struct hrt_call _mag_call
unsigned _call_accel_interval
unsigned _call_mag_interval
ringbuffer::RingBuffer * _accel_reports
ringbuffer::RingBuffer * _mag_reports
struct accel_calibration_s _accel_scale
unsigned _accel_range_m_s2
float _accel_range_scale
unsigned _accel_samplerate
unsigned _accel_onchip_filter_bandwith
struct mag_calibration_s _mag_scale
unsigned _mag_range_ga
float _mag_range_scale
unsigned _mag_samplerate
orb_advert_t _accel_topic
int _accel_orb_class_instance
int _accel_class_instance
unsigned _accel_read
unsigned _mag_read
perf_counter_t _accel_sample_perf
perf_counter_t _mag_sample_perf
perf_counter_t _bad_registers
perf_counter_t _bad_values
perf_counter_t _accel_duplicates
uint8_t _register_wait
math::LowPassFilter2p _accel_filter_x
math::LowPassFilter2p _accel_filter_y
math::LowPassFilter2p _accel_filter_z
Integrator _accel_int
enum Rotation _rotation
float _last_accel [3]
uint8_t _constant_accel_count
float _last_temperature
uint8_t _checked_values [LSM303D_NUM_CHECKED_REGISTERS]
uint8_t _checked_next
Static Private Attributes
static const uint8_t _checked_registers [LSM303D_NUM_CHECKED_REGISTERS]
Friends
class LSM303D_mag
Detailed Description
Definition at line 223 of file lsm303d.cpp.
Constructor & Destructor Documentation
LSM303D::LSM303D (int bus, const char * path, uint32_t device, enum Rotation rotation)
Definition at line 519 of file lsm303d.cpp.
References _accel_class_instance, _accel_duplicates, _accel_filter_x, _accel_filter_y, _accel_filter_z, _accel_int, _accel_onchip_filter_bandwith, _accel_orb_class_instance, _accel_range_m_s2, _accel_range_scale, _accel_read, _accel_reports, _accel_sample_perf, _accel_samplerate, _accel_scale, _accel_topic, _bad_registers, _bad_values, _call_accel_interval, _call_mag_interval, _checked_next, _constant_accel_count, device::Device::_device_id, _last_temperature, _mag, _mag_call, _mag_range_ga, _mag_range_scale, _mag_read, _mag_reports, _mag_sample_perf, _mag_samplerate, _mag_scale, _register_wait, _rotation, device::Device::DeviceId::devid, device::Device::DeviceId::devid_s, device::Device::DeviceStructure::devtype, DRV_ACC_DEVTYPE_LSM303D, DRV_MAG_DEVTYPE_LSM303D, f(), LSM303D_ACCEL_DEFAULT_DRIVER_FILTER_FREQ, LSM303D_ACCEL_DEFAULT_RATE, LSM303D_ACCEL_MAX_OUTPUT_RATE, PC_COUNT, PC_ELAPSED, perf_alloc, mag_calibration_s::x_offset, accel_calibration_s::x_offset, mag_calibration_s::x_scale, accel_calibration_s::x_scale, mag_calibration_s::y_offset, accel_calibration_s::y_offset, mag_calibration_s::y_scale, accel_calibration_s::y_scale, mag_calibration_s::z_offset, accel_calibration_s::z_offset, mag_calibration_s::z_scale, and accel_calibration_s::z_scale.
LSM303D::~LSM303D () virtual
Definition at line 580 of file lsm303d.cpp.
References _accel_class_instance, _accel_duplicates, _accel_reports, _accel_sample_perf, _bad_registers, _bad_values, _mag, _mag_reports, _mag_sample_perf, ACCEL_BASE_DEVICE_PATH, perf_free(), and stop().
LSM303D::LSM303D (const LSM303D &) private
Member Function Documentation
int LSM303D::accel_set_driver_lowpass_filter (float samplerate, float bandwidth) private
Set the driver lowpass filter bandwidth.
Parameters
bandwidth The anti-alias filter bandwidth in Hz Zero selects the highest bandwidth
Returns
OK if the value can be supported, -ERANGE otherwise.
Definition at line 1224 of file lsm303d.cpp.
References _accel_filter_x, _accel_filter_y, _accel_filter_z, OK, and math::LowPassFilter2p::set_cutoff_frequency().
Referenced by ioctl(), and reset().
int LSM303D::accel_set_onchip_lowpass_filter_bandwidth (unsigned bandwidth) private
Set the LSM303D on-chip anti-alias filter bandwith.
Parameters
bandwidth The anti-alias filter bandwidth in Hz Zero selects the highest bandwidth
Returns
OK if the value can be supported, -ERANGE otherwise.
Definition at line 1189 of file lsm303d.cpp.
References _accel_onchip_filter_bandwith, ADDR_CTRL_REG2, modify_reg(), OK, REG2_AA_FILTER_BW_194HZ_A, REG2_AA_FILTER_BW_362HZ_A, REG2_AA_FILTER_BW_50HZ_A, REG2_AA_FILTER_BW_773HZ_A, and REG2_ANTIALIAS_FILTER_BW_BITS_A.
Referenced by reset().
int LSM303D::accel_set_range (unsigned max_g) private
Set the LSM303D accel measurement range.
Parameters
max_g The measurement range of the accel is in g (9.81m/s^2) Zero selects the maximum supported range.
Returns
OK if the value can be supported, -ERANGE otherwise.
Definition at line 1099 of file lsm303d.cpp.
References _accel_range_m_s2, _accel_range_scale, ADDR_CTRL_REG2, CONSTANTS_ONE_G, f(), modify_reg(), OK, REG2_FULL_SCALE_16G_A, REG2_FULL_SCALE_2G_A, REG2_FULL_SCALE_4G_A, REG2_FULL_SCALE_6G_A, REG2_FULL_SCALE_8G_A, and REG2_FULL_SCALE_BITS_A.
Referenced by ioctl(), and reset().
int LSM303D::accel_set_samplerate (unsigned frequency) private
Set the LSM303D internal accel sampling frequency.
Parameters
frequency The internal accel sampling frequency is set to not less than this value. Zero selects the maximum rate supported.
Returns
OK if the value can be supported.
Definition at line 1234 of file lsm303d.cpp.
References _accel_samplerate, ACCEL_SAMPLERATE_DEFAULT, ADDR_CTRL_REG1, modify_reg(), OK, REG1_RATE_100HZ_A, REG1_RATE_1600HZ_A, REG1_RATE_200HZ_A, REG1_RATE_400HZ_A, REG1_RATE_800HZ_A, and REG1_RATE_BITS_A.
Referenced by ioctl(), and reset().
void LSM303D::check_registers (void) private
check key registers for correct values
Definition at line 1354 of file lsm303d.cpp.
References _bad_registers, _checked_next, _checked_registers, _checked_values, _register_wait, LSM303D_NUM_CHECKED_REGISTERS, perf_count(), read_reg(), and write_reg().
Referenced by measure().
void LSM303D::disable_i2c (void) private
disable I2C on the chip
Definition at line 669 of file lsm303d.cpp.
References read_reg(), and write_reg().
Referenced by reset().
int LSM303D::init () virtual
Definition at line 609 of file lsm303d.cpp.
References _accel_class_instance, _accel_orb_class_instance, _accel_reports, _accel_topic, _mag, LSM303D_mag::_mag_orb_class_instance, _mag_reports, LSM303D_mag::_mag_topic, ACCEL_BASE_DEVICE_PATH, accel_report, lis3mdl::init(), LSM303D_mag::init(), mag_report, measure(), OK, orb_advertise_multi(), ORB_ID, ORB_PRIO_DEFAULT, ORB_PRIO_LOW, ORB_PRIO_VERY_HIGH, PX4_ERR, and reset().
Referenced by lsm303d::start().
int LSM303D::ioctl (struct file * filp, int cmd, unsigned long arg) virtual
Definition at line 812 of file lsm303d.cpp.
References _accel_call, _accel_filter_x, _accel_range_m_s2, _accel_reports, _accel_samplerate, _accel_scale, _call_accel_interval, accel_set_driver_lowpass_filter(), accel_set_range(), accel_set_samplerate(), ACCELIOCGRANGE, ACCELIOCGSAMPLERATE, ACCELIOCGSCALE, ACCELIOCSRANGE, ACCELIOCSSAMPLERATE, ACCELIOCSSCALE, CONSTANTS_ONE_G, f(), math::LowPassFilter2p::get_cutoff_freq(), LSM303D_ACCEL_DEFAULT_RATE, LSM303D_TIMER_REDUCTION, OK, hrt_call::period, reset(), SENSOR_POLLRATE_DEFAULT, SENSOR_POLLRATE_EXTERNAL, SENSOR_POLLRATE_MANUAL, SENSOR_POLLRATE_MAX, SENSORIOCGPOLLRATE, SENSORIOCRESET, SENSORIOCSPOLLRATE, SENSORIOCSQUEUEDEPTH, start(), stop(), accel_calibration_s::x_scale, accel_calibration_s::y_scale, and accel_calibration_s::z_scale.
int LSM303D::mag_ioctl (struct file * filp, int cmd, unsigned long arg) protected virtual
Definition at line 940 of file lsm303d.cpp.
References _call_mag_interval, _mag_call, _mag_reports, _mag_samplerate, _mag_scale, mag_set_samplerate(), MAGIOCGEXTERNAL, MAGIOCGSAMPLERATE, MAGIOCGSCALE, MAGIOCSSAMPLERATE, MAGIOCSSCALE, OK, hrt_call::period, reset(), SENSOR_POLLRATE_DEFAULT, SENSOR_POLLRATE_EXTERNAL, SENSOR_POLLRATE_MANUAL, SENSOR_POLLRATE_MAX, SENSORIOCGPOLLRATE, SENSORIOCRESET, SENSORIOCSPOLLRATE, SENSORIOCSQUEUEDEPTH, start(), and stop().
Referenced by LSM303D_mag::ioctl().
void LSM303D::mag_measure () private
Fetch mag measurements from the sensor and update the report ring.
Definition at line 1533 of file lsm303d.cpp.
References _bad_registers, _bad_values, device::Device::_device_id, _last_temperature, _mag, _mag_range_scale, _mag_read, _mag_reports, _mag_sample_perf, _mag_scale, LSM303D_mag::_mag_topic, _rotation, ADDR_INCREMENT, ADDR_OUT_TEMP_L, device::Device::DeviceId::devid, DIR_READ, hrt_absolute_time(), mag_report, ORB_ID, orb_publish(), perf_begin(), perf_end(), perf_event_count(), rotate_3f(), status, mag_calibration_s::x_offset, mag_calibration_s::x_scale, mag_calibration_s::y_offset, mag_calibration_s::y_scale, mag_calibration_s::z_offset, and mag_calibration_s::z_scale.
Referenced by mag_measure_trampoline(), and LSM303D_mag::measure().
void LSM303D::mag_measure_trampoline (void * arg) static private
Static trampoline for the mag because it runs at a lower rate.
Parameters
arg Instance pointer for the driver that is polling.
Definition at line 1345 of file lsm303d.cpp.
References mag_measure().
Referenced by LSM303D_mag::measure_trampoline(), and start().
ssize_t LSM303D::mag_read (struct file * filp, char * buffer, size_t buflen) protected virtual
Definition at line 771 of file lsm303d.cpp.
References _call_mag_interval, _mag, _mag_reports, mag_report, and LSM303D_mag::measure().
Referenced by LSM303D_mag::read().
int LSM303D::mag_set_range (unsigned max_g) private
Set the LSM303D mag measurement range.
Parameters
max_ga The measurement range of the mag is in Ga Zero selects the maximum supported range.
Returns
OK if the value can be supported, -ERANGE otherwise.
Definition at line 1147 of file lsm303d.cpp.
References _mag_range_ga, _mag_range_scale, ADDR_CTRL_REG6, f(), modify_reg(), OK, REG6_FULL_SCALE_12GA_M, REG6_FULL_SCALE_2GA_M, REG6_FULL_SCALE_4GA_M, REG6_FULL_SCALE_8GA_M, and REG6_FULL_SCALE_BITS_M.
Referenced by reset().
int LSM303D::mag_set_samplerate (unsigned frequency) private
Set the LSM303D internal mag sampling frequency.
Parameters
frequency The internal mag sampling frequency is set to not less than this value. Zero selects the maximum rate supported.
Returns
OK if the value can be supported.
Definition at line 1273 of file lsm303d.cpp.
References _mag_samplerate, ADDR_CTRL_REG5, modify_reg(), OK, REG5_RATE_100HZ_M, REG5_RATE_25HZ_M, REG5_RATE_50HZ_M, and REG5_RATE_BITS_M.
Referenced by mag_ioctl(), and reset().
void LSM303D::measure () private
Fetch accel measurements from the sensor and update the report ring.
Definition at line 1384 of file lsm303d.cpp.
References _accel_duplicates, _accel_filter_x, _accel_filter_y, _accel_filter_z, _accel_int, _accel_range_scale, _accel_read, _accel_reports, _accel_sample_perf, _accel_scale, _accel_topic, _bad_registers, _bad_values, _constant_accel_count, _last_accel, _last_temperature, _register_wait, _rotation, accel_report, ADDR_INCREMENT, ADDR_STATUS_A, math::LowPassFilter2p::apply(), check_registers(), DIR_READ, hrt_absolute_time(), ORB_ID, orb_publish(), perf_begin(), perf_count(), perf_end(), perf_event_count(), Integrator::put(), REG_STATUS_A_NEW_ZYXADA, rotate_3f(), status, accel_calibration_s::x_offset, accel_calibration_s::x_scale, accel_calibration_s::y_offset, accel_calibration_s::y_scale, accel_calibration_s::z_offset, and accel_calibration_s::z_scale.
Referenced by init(), measure_trampoline(), and read().
void LSM303D::measure_trampoline (void * arg) static private
Static trampoline from the hrt_call context; because we don't have a generic hrt wrapper yet.
Called by the HRT in interrupt context at the specified rate if automatic polling is enabled.
Parameters
arg Instance pointer for the driver that is polling.
Definition at line 1336 of file lsm303d.cpp.
References measure().
Referenced by start().
void LSM303D::modify_reg (unsigned reg, uint8_t clearbits, uint8_t setbits) private
Modify a register in the LSM303D.
Bits are cleared before bits are set.
Parameters
reg The register to modify.
clearbits Bits in the register to clear.
setbits Bits in the register to set.
Definition at line 1088 of file lsm303d.cpp.
References read_reg(), and write_checked_reg().
Referenced by accel_set_onchip_lowpass_filter_bandwidth(), accel_set_range(), accel_set_samplerate(), mag_set_range(), and mag_set_samplerate().
LSM303D LSM303D::operator= (const LSM303D &) private
void LSM303D::print_info ()
Diagnostics - print some basic information about the driver.
Definition at line 1616 of file lsm303d.cpp.
References _accel_duplicates, _accel_read, _accel_reports, _accel_sample_perf, _bad_registers, _bad_values, _checked_next, _checked_registers, _checked_values, _last_temperature, _mag_read, _mag_reports, _mag_sample_perf, LSM303D_NUM_CHECKED_REGISTERS, perf_print_counter(), and read_reg().
Referenced by lsm303d::info().
void LSM303D::print_registers ()
dump register values
Definition at line 1644 of file lsm303d.cpp.
References ADDR_ACT_DUR, ADDR_ACT_THS, ADDR_CLICK_CFG, ADDR_CLICK_SRC, ADDR_CLICK_THS, ADDR_CTRL_REG0, ADDR_CTRL_REG1, ADDR_CTRL_REG2, ADDR_CTRL_REG3, ADDR_CTRL_REG4, ADDR_CTRL_REG5, ADDR_CTRL_REG6, ADDR_CTRL_REG7, ADDR_FIFO_CTRL, ADDR_FIFO_SRC, ADDR_IG_CFG1, ADDR_IG_CFG2, ADDR_IG_DUR1, ADDR_IG_DUR2, ADDR_IG_SRC1, ADDR_IG_SRC2, ADDR_IG_THS1, ADDR_IG_THS2, ADDR_INT_CTRL_M, ADDR_INT_SRC_M, ADDR_OUT_TEMP_H, ADDR_OUT_TEMP_L, ADDR_OUT_X_H_A, ADDR_OUT_X_L_A, ADDR_OUT_Y_H_A, ADDR_OUT_Y_L_A, ADDR_OUT_Z_H_A, ADDR_OUT_Z_L_A, ADDR_REFERENCE_X, ADDR_REFERENCE_Y, ADDR_REFERENCE_Z, ADDR_STATUS_A, ADDR_STATUS_M, ADDR_TIME_LATENCY, ADDR_TIME_LIMIT, ADDR_TIME_WINDOW, ADDR_WHO_AM_I, name, and read_reg().
Referenced by lsm303d::regdump().
int LSM303D::probe () protected virtual
Definition at line 715 of file lsm303d.cpp.
References _checked_values, ADDR_WHO_AM_I, OK, read_reg(), and WHO_I_AM.
ssize_t LSM303D::read (struct file * filp, char * buffer, size_t buflen) virtual
Definition at line 732 of file lsm303d.cpp.
References _accel_reports, _call_accel_interval, accel_report, and measure().
uint8_t LSM303D::read_reg (unsigned reg) private
Read a register from the LSM303D.
Parameters
The register to read.
Returns
The value that was read.
Definition at line 1052 of file lsm303d.cpp.
References DIR_READ.
Referenced by check_registers(), disable_i2c(), modify_reg(), print_info(), print_registers(), and probe().
void LSM303D::reset () private
Reset chip.
Resets the chip and measurements ranges, but not scale and offset.
Definition at line 682 of file lsm303d.cpp.
References _accel_read, _mag_read, accel_set_driver_lowpass_filter(), accel_set_onchip_lowpass_filter_bandwidth(), accel_set_range(), accel_set_samplerate(), ADDR_CTRL_REG1, ADDR_CTRL_REG3, ADDR_CTRL_REG4, ADDR_CTRL_REG5, ADDR_CTRL_REG7, disable_i2c(), LSM303D_ACCEL_DEFAULT_DRIVER_FILTER_FREQ, LSM303D_ACCEL_DEFAULT_ONCHIP_FILTER_FREQ, LSM303D_ACCEL_DEFAULT_RANGE_G, LSM303D_ACCEL_DEFAULT_RATE, LSM303D_MAG_DEFAULT_RANGE_GA, LSM303D_MAG_DEFAULT_RATE, mag_set_range(), mag_set_samplerate(), REG1_BDU_UPDATE, REG1_RATE_800HZ_A, REG1_X_ENABLE_A, REG1_Y_ENABLE_A, REG1_Z_ENABLE_A, REG5_ENABLE_T, REG5_RES_HIGH_M, REG7_CONT_MODE_M, and write_checked_reg().
Referenced by init(), ioctl(), and mag_ioctl().
void LSM303D::start () private
Start automatic measurement.
Definition at line 1304 of file lsm303d.cpp.
References _accel_call, _accel_reports, _call_accel_interval, _call_mag_interval, _mag_call, _mag_reports, hrt_call_every(), LSM303D_TIMER_REDUCTION, mag_measure_trampoline(), measure_trampoline(), and stop().
Referenced by ioctl(), and mag_ioctl().
void LSM303D::stop () private
Stop automatic measurement.
Definition at line 1322 of file lsm303d.cpp.
References _accel_call, _accel_reports, _last_accel, _mag_call, _mag_reports, and hrt_cancel().
Referenced by ioctl(), mag_ioctl(), start(), and ~LSM303D().
void LSM303D::test_error ()
deliberately trigger an error
Definition at line 1702 of file lsm303d.cpp.
References ADDR_CTRL_REG3, and write_reg().
Referenced by lsm303d::test_error().
void LSM303D::write_checked_reg (unsigned reg, uint8_t value) private
Write a register in the LSM303D, updating _checked_values.
Parameters
reg The register to write.
value The new value to write.
Definition at line 1076 of file lsm303d.cpp.
References _checked_registers, _checked_values, LSM303D_NUM_CHECKED_REGISTERS, and write_reg().
Referenced by modify_reg(), and reset().
void LSM303D::write_reg (unsigned reg, uint8_t value) private
Write a register in the LSM303D.
Parameters
reg The register to write.
value The new value to write.
Definition at line 1065 of file lsm303d.cpp.
References DIR_WRITE.
Referenced by check_registers(), disable_i2c(), test_error(), and write_checked_reg().
Friends And Related Function Documentation
friend class LSM303D_mag friend
Definition at line 252 of file lsm303d.cpp.
Member Data Documentation
struct hrt_call LSM303D::_accel_call private
Definition at line 261 of file lsm303d.cpp.
Referenced by ioctl(), start(), and stop().
int LSM303D::_accel_class_instance private
Definition at line 283 of file lsm303d.cpp.
Referenced by init(), LSM303D(), and ~LSM303D().
perf_counter_t LSM303D::_accel_duplicates private
Definition at line 292 of file lsm303d.cpp.
Referenced by LSM303D(), measure(), print_info(), and ~LSM303D().
math::LowPassFilter2p LSM303D::_accel_filter_x private
Definition at line 296 of file lsm303d.cpp.
Referenced by accel_set_driver_lowpass_filter(), ioctl(), LSM303D(), and measure().
math::LowPassFilter2p LSM303D::_accel_filter_y private
Definition at line 297 of file lsm303d.cpp.
Referenced by accel_set_driver_lowpass_filter(), LSM303D(), and measure().
math::LowPassFilter2p LSM303D::_accel_filter_z private
Definition at line 298 of file lsm303d.cpp.
Referenced by accel_set_driver_lowpass_filter(), LSM303D(), and measure().
Integrator LSM303D::_accel_int private
Definition at line 300 of file lsm303d.cpp.
Referenced by LSM303D(), and measure().
unsigned LSM303D::_accel_onchip_filter_bandwith private
Definition at line 274 of file lsm303d.cpp.
Referenced by accel_set_onchip_lowpass_filter_bandwidth(), and LSM303D().
int LSM303D::_accel_orb_class_instance private
Definition at line 282 of file lsm303d.cpp.
Referenced by init(), and LSM303D().
unsigned LSM303D::_accel_range_m_s2 private
Definition at line 271 of file lsm303d.cpp.
Referenced by accel_set_range(), ioctl(), and LSM303D().
float LSM303D::_accel_range_scale private
Definition at line 272 of file lsm303d.cpp.
Referenced by accel_set_range(), LSM303D(), and measure().
unsigned LSM303D::_accel_read private
Definition at line 285 of file lsm303d.cpp.
Referenced by LSM303D(), measure(), print_info(), and reset().
ringbuffer::RingBuffer* LSM303D::_accel_reports private
Definition at line 267 of file lsm303d.cpp.
Referenced by init(), ioctl(), LSM303D(), measure(), print_info(), read(), start(), stop(), and ~LSM303D().
perf_counter_t LSM303D::_accel_sample_perf private
Definition at line 288 of file lsm303d.cpp.
Referenced by LSM303D(), measure(), print_info(), and ~LSM303D().
unsigned LSM303D::_accel_samplerate private
Definition at line 273 of file lsm303d.cpp.
Referenced by accel_set_samplerate(), ioctl(), and LSM303D().
struct accel_calibration_s LSM303D::_accel_scale private
Definition at line 270 of file lsm303d.cpp.
Referenced by ioctl(), LSM303D(), and measure().
orb_advert_t LSM303D::_accel_topic private
Definition at line 281 of file lsm303d.cpp.
Referenced by init(), LSM303D(), and measure().
perf_counter_t LSM303D::_bad_registers private
Definition at line 290 of file lsm303d.cpp.
Referenced by check_registers(), LSM303D(), mag_measure(), measure(), print_info(), and ~LSM303D().
perf_counter_t LSM303D::_bad_values private
Definition at line 291 of file lsm303d.cpp.
Referenced by LSM303D(), mag_measure(), measure(), print_info(), and ~LSM303D().
unsigned LSM303D::_call_accel_interval private
Definition at line 264 of file lsm303d.cpp.
Referenced by ioctl(), LSM303D(), read(), and start().
unsigned LSM303D::_call_mag_interval private
Definition at line 265 of file lsm303d.cpp.
Referenced by LSM303D(), mag_ioctl(), mag_read(), and start().
uint8_t LSM303D::_checked_next private
Definition at line 317 of file lsm303d.cpp.
Referenced by check_registers(), LSM303D(), and print_info().
const uint8_t LSM303D::_checked_registers static private
Initial value:
= { ADDR_WHO_AM_I,
                                         ADDR_CTRL_REG1,
                                         ADDR_CTRL_REG2,
                                         ADDR_CTRL_REG3,
                                         ADDR_CTRL_REG4,
                                         ADDR_CTRL_REG5,
                                         ADDR_CTRL_REG6,
                                         ADDR_CTRL_REG7
                                       }
Definition at line 315 of file lsm303d.cpp.
Referenced by check_registers(), print_info(), and write_checked_reg().
uint8_t LSM303D::_checked_values[LSM303D_NUM_CHECKED_REGISTERS] private
Definition at line 316 of file lsm303d.cpp.
Referenced by check_registers(), print_info(), probe(), and write_checked_reg().
uint8_t LSM303D::_constant_accel_count private
Definition at line 306 of file lsm303d.cpp.
Referenced by LSM303D(), and measure().
float LSM303D::_last_accel[3] private
Definition at line 305 of file lsm303d.cpp.
Referenced by measure(), and stop().
float LSM303D::_last_temperature private
Definition at line 309 of file lsm303d.cpp.
Referenced by LSM303D(), mag_measure(), measure(), and print_info().
LSM303D_mag* LSM303D::_mag private
Definition at line 259 of file lsm303d.cpp.
Referenced by init(), LSM303D(), mag_measure(), mag_read(), and ~LSM303D().
struct hrt_call LSM303D::_mag_call private
Definition at line 262 of file lsm303d.cpp.
Referenced by LSM303D(), mag_ioctl(), start(), and stop().
unsigned LSM303D::_mag_range_ga private
Definition at line 277 of file lsm303d.cpp.
Referenced by LSM303D(), and mag_set_range().
float LSM303D::_mag_range_scale private
Definition at line 278 of file lsm303d.cpp.
Referenced by LSM303D(), mag_measure(), and mag_set_range().
unsigned LSM303D::_mag_read private
Definition at line 286 of file lsm303d.cpp.
Referenced by LSM303D(), mag_measure(), print_info(), and reset().
ringbuffer::RingBuffer* LSM303D::_mag_reports private
Definition at line 268 of file lsm303d.cpp.
Referenced by init(), LSM303D(), mag_ioctl(), mag_measure(), mag_read(), print_info(), start(), stop(), and ~LSM303D().
perf_counter_t LSM303D::_mag_sample_perf private
Definition at line 289 of file lsm303d.cpp.
Referenced by LSM303D(), mag_measure(), print_info(), and ~LSM303D().
unsigned LSM303D::_mag_samplerate private
Definition at line 279 of file lsm303d.cpp.
Referenced by LSM303D(), mag_ioctl(), and mag_set_samplerate().
struct mag_calibration_s LSM303D::_mag_scale private
Definition at line 276 of file lsm303d.cpp.
Referenced by LSM303D(), mag_ioctl(), and mag_measure().
uint8_t LSM303D::_register_wait private
Definition at line 294 of file lsm303d.cpp.
Referenced by check_registers(), LSM303D(), and measure().
enum Rotation LSM303D::_rotation private
Definition at line 302 of file lsm303d.cpp.
Referenced by LSM303D(), mag_measure(), and measure().
The documentation for this class was generated from the following file:
src/drivers/imu/lsm303d/lsm303d.cpp