PX4 Firmware: Syslink Class Reference
Syslink Class Reference
#include <syslink_main.h>
Public Member Functions
Syslink ()
int start ()
int set_datarate (uint8_t datarate)
int set_channel (uint8_t channel)
int set_address (uint64_t addr)
int is_good (int i)
Public Attributes
int pktrate
int nullrate
int rxrate
int txrate
Private Member Functions
int open_serial (const char *dev)
void handle_message (syslink_message_t *msg)
void handle_raw (syslink_message_t *sys)
void handle_radio (syslink_message_t *sys)
void handle_bootloader (syslink_message_t *sys)
void handle_raw_other (syslink_message_t *sys)
int send_bytes (const void *data, size_t len)
int send_message (syslink_message_t *msg)
int send_queued_raw_message ()
void update_params (bool force_set)
void task_main ()
Static Private Member Functions
static int task_main_trampoline (int argc, char *argv[])
Private Attributes
int _syslink_task
bool _task_running
bool _bootloader_mode
int _count
int _null_count
int _count_in
int _count_out
hrt_abstime _lasttime
hrt_abstime _lasttxtime
hrt_abstime _lastrxtime
int _fd
ringbuffer::RingBuffer _queue
ringbuffer::RingBuffer _writebuffer
SyslinkBridge * _bridge
SyslinkMemory * _memory
int _params_sub
int32_t _channel
int32_t _rate
uint64_t _addr
hrt_abstime _params_update [3]
hrt_abstime _params_ack [3]
orb_advert_t _battery_pub
orb_advert_t _rc_pub
orb_advert_t _cmd_pub
struct battery_status_s _battery_status
Battery _battery
int32_t _rssi
battery_state _bstate
px4_sem_t memory_sem
syslink_message_t memory_msg
Friends
class SyslinkBridge
class SyslinkMemory
Detailed Description
Definition at line 61 of file syslink_main.h.
Constructor & Destructor Documentation
Syslink::Syslink ()
Definition at line 85 of file syslink_main.cpp.
References memory_sem, px4_sem_init, px4_sem_setprotocol, and SEM_PRIO_NONE.
Referenced by syslink::start().
Member Function Documentation
void Syslink::handle_bootloader (syslink_message_t * sys) private
Definition at line 601 of file syslink_main.cpp.
References _bootloader_mode, and send_message().
Referenced by handle_raw().
void Syslink::handle_message (syslink_message_t * msg) private
Definition at line 386 of file syslink_main.cpp.
References _addr, _battery, _battery_pub, _battery_status, _bstate, _channel, _count, _count_in, _count_out, _lastrxtime, _lasttime, _lasttxtime, _memory, _null_count, _params_ack, _params_update, _queue, _rate, _rssi, BAT_CHARGED, BAT_CHARGING, BAT_DISCHARGING, f(), handle_radio(), handle_raw(), hrt_absolute_time(), hrt_abstime, LED_GREEN, led_off(), led_on(), LED_RX, LED_TX, memory_sem, SyslinkMemory::msgbuf, nullrate, orb_advertise(), ORB_ID, orb_publish(), pktrate, PX4_INFO, px4_sem_post, rxrate, send_message(), set_address(), set_channel(), set_datarate(), SYSLINK_GROUP, SYSLINK_OW, SYSLINK_PM_BATTERY_STATE, SYSLINK_PM_ONOFF_SWITCHOFF, SYSLINK_RADIO, SYSLINK_RADIO_RAW, SYSLINK_RADIO_RSSI, txrate, Battery::updateBatteryStatus(), and battery_status_s::voltage_filtered_v.
Referenced by task_main().
void Syslink::handle_radio (syslink_message_t * sys) private
Definition at line 519 of file syslink_main.cpp.
References _params_ack, hrt_absolute_time(), hrt_abstime, SYSLINK_RADIO_ADDRESS, SYSLINK_RADIO_CHANNEL, and SYSLINK_RADIO_DATARATE.
Referenced by handle_message().
void Syslink::handle_raw (syslink_message_t * sys) private
Definition at line 537 of file syslink_main.cpp.
References _bootloader_mode, _bridge, _count_in, _null_count, _rc_pub, _rssi, CRTP_NULL, CRTP_PORT_COMMANDER, CRTP_PORT_MAVLINK, handle_bootloader(), handle_raw_other(), hrt_absolute_time(), orb_advertise(), ORB_ID, orb_publish(), SyslinkBridge::pipe_message(), rc_input_values, and send_queued_raw_message().
Referenced by handle_message().
void Syslink::handle_raw_other (syslink_message_t * sys) private
Definition at line 629 of file syslink_main.cpp.
References CRTP_PORT_LOG, CRTP_PORT_MEM, CRTP_PORT_PARAM, PX4_INFO, and send_message().
Referenced by handle_raw().
int Syslink::is_good (int i) inline
Definition at line 72 of file syslink_main.h.
References _params_ack.
Referenced by syslink::status().
int Syslink::open_serial (const char * dev) private
Definition at line 235 of file syslink_main.cpp.
References B1000000, fd, px4_close(), PX4_ERR, px4_open(), PX4_WARN, and warnx.
Referenced by task_main().
int Syslink::send_bytes (const void * data, size_t len) private
Definition at line 707 of file syslink_main.cpp.
References _fd, GPIO_NRF_TXEN, and write().
Referenced by send_message().
int Syslink::send_message (syslink_message_t * msg) private
Definition at line 722 of file syslink_main.cpp.
References send_bytes(), syslink_compute_cksum(), and syslink_magic.
Referenced by handle_bootloader(), handle_message(), handle_raw_other(), send_queued_raw_message(), set_address(), set_channel(), and set_datarate().
int Syslink::send_queued_raw_message () private
Definition at line 163 of file syslink_main.cpp.
References _count_out, _lasttxtime, _writebuffer, hrt_absolute_time(), msg, send_message(), and SYSLINK_RADIO_RAW.
Referenced by handle_raw().
int Syslink::set_address (uint64_t addr)
Definition at line 153 of file syslink_main.cpp.
References msg, send_message(), and SYSLINK_RADIO_ADDRESS.
Referenced by handle_message(), and update_params().
int Syslink::set_channel (uint8_t channel)
Definition at line 143 of file syslink_main.cpp.
References msg, send_message(), and SYSLINK_RADIO_CHANNEL.
Referenced by handle_message(), and update_params().
int Syslink::set_datarate (uint8_t datarate)
Definition at line 133 of file syslink_main.cpp.
References msg, send_message(), and SYSLINK_RADIO_DATARATE.
Referenced by handle_message(), and update_params().
int Syslink::start ()
Definition at line 116 of file syslink_main.cpp.
References _syslink_task, _task_running, px4_task_spawn_cmd(), SCHED_DEFAULT, and task_main_trampoline().
Referenced by syslink::start().
void Syslink::task_main () private
Definition at line 290 of file syslink_main.cpp.
References _battery, _battery_status, _bridge, _fd, _memory, _params_sub, _task_running, err, GPIO_NRF_TXEN, handle_message(), SyslinkBridge::init(), SyslinkMemory::init(), msg, open_serial(), orb_copy(), ORB_ID, orb_subscribe(), PX4_ERR, px4_poll(), read(), Battery::reset(), state, syslink_parse_char(), syslink_parse_init(), SyslinkBridge, SyslinkMemory, and update_params().
Referenced by task_main_trampoline().
int Syslink::task_main_trampoline (int argc, char * argv[]) static private
Definition at line 283 of file syslink_main.cpp.
References task_main().
Referenced by start().
void Syslink::update_params (bool force_set) private
Definition at line 183 of file syslink_main.cpp.
References _addr, _channel, _params_ack, _params_update, _rate, hrt_absolute_time(), hrt_abstime, param_find(), param_get(), set_address(), set_channel(), and set_datarate().
Referenced by task_main().
Friends And Related Function Documentation
friend class SyslinkBridge friend
Definition at line 81 of file syslink_main.h.
Referenced by task_main().
friend class SyslinkMemory friend
Definition at line 82 of file syslink_main.h.
Referenced by task_main().
Member Data Documentation
uint64_t Syslink::_addr private
Definition at line 131 of file syslink_main.h.
Referenced by handle_message(), and update_params().
Battery Syslink::_battery private
Definition at line 141 of file syslink_main.h.
Referenced by handle_message(), and task_main().
orb_advert_t Syslink::_battery_pub private
Definition at line 135 of file syslink_main.h.
Referenced by handle_message().
struct battery_status_s Syslink::_battery_status private
Definition at line 139 of file syslink_main.h.
Referenced by handle_message(), and task_main().
bool Syslink::_bootloader_mode private
Definition at line 107 of file syslink_main.h.
Referenced by handle_bootloader(), and handle_raw().
SyslinkBridge* Syslink::_bridge private
Definition at line 124 of file syslink_main.h.
Referenced by handle_raw(), and task_main().
battery_state Syslink::_bstate private
Definition at line 144 of file syslink_main.h.
Referenced by handle_message().
int32_t Syslink::_channel private
Definition at line 130 of file syslink_main.h.
Referenced by handle_message(), and update_params().
orb_advert_t Syslink::_cmd_pub private
Definition at line 137 of file syslink_main.h.
int Syslink::_count private
Definition at line 109 of file syslink_main.h.
Referenced by handle_message().
int Syslink::_count_in private
Definition at line 111 of file syslink_main.h.
Referenced by handle_message(), and handle_raw().
int Syslink::_count_out private
Definition at line 112 of file syslink_main.h.
Referenced by handle_message(), and send_queued_raw_message().
int Syslink::_fd private
Definition at line 117 of file syslink_main.h.
Referenced by send_bytes(), and task_main().
hrt_abstime Syslink::_lastrxtime private
Definition at line 115 of file syslink_main.h.
Referenced by handle_message().
hrt_abstime Syslink::_lasttime private
Definition at line 113 of file syslink_main.h.
Referenced by handle_message().
hrt_abstime Syslink::_lasttxtime private
Definition at line 114 of file syslink_main.h.
Referenced by handle_message(), and send_queued_raw_message().
SyslinkMemory* Syslink::_memory private
Definition at line 125 of file syslink_main.h.
Referenced by handle_message(), and task_main().
int Syslink::_null_count private
Definition at line 110 of file syslink_main.h.
Referenced by handle_message(), and handle_raw().
hrt_abstime Syslink::_params_ack[3] private
Definition at line 133 of file syslink_main.h.
Referenced by handle_message(), handle_radio(), is_good(), and update_params().
int Syslink::_params_sub private
Definition at line 127 of file syslink_main.h.
Referenced by task_main().
hrt_abstime Syslink::_params_update[3] private
Definition at line 132 of file syslink_main.h.
Referenced by handle_message(), and update_params().
ringbuffer::RingBuffer Syslink::_queue private
Definition at line 120 of file syslink_main.h.
Referenced by handle_message(), and SyslinkMemory::sendAndWait().
int32_t Syslink::_rate private
Definition at line 130 of file syslink_main.h.
Referenced by handle_message(), and update_params().
orb_advert_t Syslink::_rc_pub private
Definition at line 136 of file syslink_main.h.
Referenced by handle_raw().
int32_t Syslink::_rssi private
Definition at line 143 of file syslink_main.h.
Referenced by handle_message(), and handle_raw().
int Syslink::_syslink_task private
Definition at line 105 of file syslink_main.h.
Referenced by start().
bool Syslink::_task_running private
Definition at line 106 of file syslink_main.h.
Referenced by start(), and task_main().
ringbuffer::RingBuffer Syslink::_writebuffer private
Definition at line 123 of file syslink_main.h.
Referenced by SyslinkBridge::ioctl(), SyslinkBridge::poll_state(), send_queued_raw_message(), and SyslinkBridge::write().
syslink_message_t Syslink::memory_msg private
Definition at line 148 of file syslink_main.h.
px4_sem_t Syslink::memory_sem private
Definition at line 146 of file syslink_main.h.
Referenced by handle_message(), SyslinkMemory::sendAndWait(), and Syslink().
int Syslink::nullrate
Definition at line 75 of file syslink_main.h.
Referenced by handle_message(), and syslink::status().
int Syslink::pktrate
Definition at line 74 of file syslink_main.h.
Referenced by handle_message(), and syslink::status().
int Syslink::rxrate
Definition at line 76 of file syslink_main.h.
Referenced by handle_message(), and syslink::status().
int Syslink::txrate
Definition at line 77 of file syslink_main.h.
Referenced by handle_message(), and syslink::status().
The documentation for this class was generated from the following files:
src/modules/syslink/syslink_main.h
src/modules/syslink/syslink_main.cpp