PX4 Firmware: src/modules/uavcannode/uavcannode_main.cpp File Reference
uavcannode_main.cpp File Reference
#include <px4_config.h>
#include <px4_log.h>
#include <px4_tasks.h>
#include <px4_workqueue.h>
#include <cstdlib>
#include <cstring>
#include <fcntl.h>
#include <systemlib/err.h>
#include <parameters/param.h>
#include <lib/mixer/mixer.h>
#include <version/version.h>
#include <nuttx/board.h>
#include <arch/chip/chip.h>
#include <drivers/drv_hrt.h>
#include <drivers/drv_pwm_output.h>
#include "uavcannode_main.hpp"
#include "indication_controller.hpp"
#include "sim_controller.hpp"
#include "resources.hpp"
#include "led.hpp"
#include "boot_app_shared.h"
Classes
class RestartRequestHandler
Macros
#define RESOURCE_DEBUG
#define resources(s)
Functions
static void cb_reboot (const uavcan::TimerEvent &)
static void print_usage ()
__EXPORT int uavcannode_start (int argc, char *argv[])
__EXPORT int uavcannode_main (int argc, char *argv[])
Variables
boot_app_shared_section app_descriptor_t AppDescriptor
RestartRequestHandler restart_request_handler
Macro Definition Documentation
#define RESOURCE_DEBUG
Definition at line 76 of file uavcannode_main.cpp.
#define resources (s)
Value:
::syslog(LOG_INFO," %s\n",(s)); \
    if (UavcanNode::instance()) { \
        syslog(LOG_INFO,"UAVCAN  getPeakNumUsedBlocks() in bytes %d\n", \
               UAVCAN_MEM_POOL_BLOCK_SIZE * UavcanNode::instance()->get_node().getAllocator().getPeakNumUsedBlocks()); \
    } \
    free_check(); \
    stack_check();
Definition at line 78 of file uavcannode_main.cpp.
Referenced by RestartRequestHandler::handleRestartRequest(), and uavcannode_start().
Function Documentation
static void cb_reboot (const uavcan::TimerEvent &) static
Definition at line 254 of file uavcannode_main.cpp.
References px4_systemreset().
Referenced by UavcanNode::cb_beginfirmware_update().
static void print_usage (void) static
Definition at line 513 of file uavcannode_main.cpp.
References uavcannode_start(), and warnx.
Referenced by uavcannode_main().
int uavcannode_main (int argc, char * argv[])
Definition at line 569 of file uavcannode_main.cpp.
References errx, UavcanNode::instance(), UavcanNode::print_info(), print_usage(), and uavcannode_start().
Referenced by uavcannode_start().
__EXPORT int uavcannode_start (int argc, char * argv[])
Definition at line 521 of file uavcannode_main.cpp.
References board_app_initialize(), BootLoader, bootloader_app_shared_invalidate(), bootloader_app_shared_read(), bootloader_app_shared_t::bus_speed, bootloader_app_shared_t::node_id, param_find(), param_get(), resources, UavcanNode::start(), uavcannode_main(), and warnx.
Referenced by print_usage(), and uavcannode_main().
Variable Documentation
boot_app_shared_section app_descriptor_t AppDescriptor
Initial value:
= {
    .signature = {APP_DESCRIPTOR_SIGNATURE},
    .image_crc = 0,
    .image_size = 0,
    .vcs_commit = 0,
    .major_version = APP_VERSION_MAJOR,
    .minor_version = APP_VERSION_MINOR,
    .reserved = {0xff, 0xff, 0xff, 0xff, 0xff, 0xff }
}
Definition at line 97 of file uavcannode_main.cpp.
RestartRequestHandler restart_request_handler
Referenced by RestartRequestHandler::handleRestartRequest().