PX4 Firmware: src/drivers/driver_framework_wrapper/df_ms5607_wrapper/df_ms5607_wrapper.cpp File Reference
df_ms5607_wrapper.cpp File Reference
Lightweight driver to access the MS5607 of the DriverFramework.
#include <px4_platform_common/px4_config.h>
#include <sys/types.h>
#include <sys/stat.h>
#include <stdint.h>
#include <stddef.h>
#include <stdlib.h>
#include <string.h>
#include <math.h>
#include <unistd.h>
#include <px4_platform_common/getopt.h>
#include <errno.h>
#include <perf/perf_counter.h>
#include <systemlib/err.h>
#include <drivers/drv_baro.h>
#include <drivers/drv_hrt.h>
#include <board_config.h>
#include <ms5607/MS5607.hpp>
#include <DevMgr.hpp>
Classes
class DfMS5607Wrapper
Namespaces
df_ms5607_wrapper
Functions
__EXPORT int df_ms5607_wrapper_main (int argc, char *argv[])
int df_ms5607_wrapper::start ()
Attempt to start driver on all available I2C busses.
int df_ms5607_wrapper::stop ()
Stop the driver.
int df_ms5607_wrapper::info ()
Print a little info about the driver.
void df_ms5607_wrapper::usage ()
Prints info about the driver argument usage.
Variables
DfMS5607Wrapper * df_ms5607_wrapper::g_dev = nullptr
Detailed Description
Lightweight driver to access the MS5607 of the DriverFramework.
Definition in file df_ms5607_wrapper.cpp.
Function Documentation
df_ms5607_wrapper_main()
int df_ms5607_wrapper_main (int argc, char * argv[])
Definition at line 263 of file df_ms5607_wrapper.cpp.
References df_ms5607_wrapper::info(), df_ms5607_wrapper::start(), df_ms5607_wrapper::stop(), and df_ms5607_wrapper::usage().