PX4 Firmware: MB12XX Class Reference
MB12XX Class Reference
Public Member Functions
MB12XX (uint8_t rotation=distance_sensor_s::ROTATION_DOWNWARD_FACING, int bus=MB12XX_BUS_DEFAULT, int address=MB12XX_BASEADDR)
virtual ~MB12XX ()
virtual int init ()
virtual ssize_t read (device::file_t *filp, char *buffer, size_t buflen)
virtual int ioctl (device::file_t *filp, int cmd, unsigned long arg)
void print_info ()
Diagnostics - print some basic information about the driver.
Protected Member Functions
virtual int probe ()
Private Member Functions
int probe_address (uint8_t address)
Test whether the device supported by the driver is present at a specific address.
void start ()
Initialise the automatic measurement state machine and start it.
void stop ()
Stop the automatic measurement state machine.
void set_minimum_distance (float min)
Set the min and max distance thresholds if you want the end points of the sensors range to be brought in at all, otherwise it will use the defaults MB12XX_MIN_DISTANCE and MB12XX_MAX_DISTANCE.
void set_maximum_distance (float max)
float get_minimum_distance ()
float get_maximum_distance ()
void cycle ()
Perform a poll cycle; collect from the previous measurement and start a new one.
int measure ()
int collect ()
Static Private Member Functions
static void cycle_trampoline (void *arg)
Static trampoline from the workq context; because we don't have a generic workq wrapper yet.
Private Attributes
uint8_t _rotation
float _min_distance
float _max_distance
work_s _work
ringbuffer::RingBuffer * _reports
bool _sensor_ok
int _measure_ticks
bool _collect_phase
int _class_instance
int _orb_class_instance
orb_advert_t _distance_sensor_topic
perf_counter_t _sample_perf
perf_counter_t _comms_errors
uint8_t _cycle_counter
int _cycling_rate
uint8_t _index_counter
std::vector< uint8_t > addr_ind
std::vector< float > _latest_sonar_measurements
Detailed Description
Definition at line 94 of file mb12xx.cpp.
Constructor & Destructor Documentation
MB12XX::MB12XX (uint8_t rotation = distance_sensor_s::ROTATION_DOWNWARD_FACING, int bus = MB12XX_BUS_DEFAULT, int address = MB12XX_BASEADDR)
Definition at line 194 of file mb12xx.cpp.
Referenced by mb12xx::start_bus().
MB12XX::~MB12XX () virtual
Definition at line 220 of file mb12xx.cpp.
References _class_instance, _comms_errors, _reports, _sample_perf, perf_free(), RANGE_FINDER_BASE_DEVICE_PATH, and stop().
Member Function Documentation
int MB12XX::collect () private
Definition at line 530 of file mb12xx.cpp.
References _comms_errors, _distance_sensor_topic, _reports, _rotation, _sample_perf, distance_sensor_s::covariance, distance_sensor_s::current_distance, DEVICE_DEBUG, f(), get_maximum_distance(), get_minimum_distance(), hrt_absolute_time(), distance_sensor_s::id, distance_sensor_s::max_distance, distance_sensor_s::min_distance, OK, ORB_ID, orb_publish(), distance_sensor_s::orientation, perf_begin(), perf_count(), perf_end(), distance_sensor_s::signal_quality, distance_sensor_s::timestamp, and distance_sensor_s::type.
Referenced by cycle(), and read().
void MB12XX::cycle () private
Perform a poll cycle; collect from the previous measurement and start a new one.
Definition at line 608 of file mb12xx.cpp.
References _collect_phase, _cycle_counter, _cycling_rate, _index_counter, _measure_ticks, addr_ind, collect(), cycle_trampoline(), DEVICE_DEBUG, measure(), OK, and start().
Referenced by cycle_trampoline().
void MB12XX::cycle_trampoline (void * arg) static private
Static trampoline from the workq context; because we don't have a generic workq wrapper yet.
Parameters
arg Instance pointer for the driver that is polling.
Definition at line 598 of file mb12xx.cpp.
References cycle().
Referenced by cycle(), and start().
float MB12XX::get_maximum_distance () private
Definition at line 339 of file mb12xx.cpp.
References _max_distance.
Referenced by collect().
float MB12XX::get_minimum_distance () private
Definition at line 333 of file mb12xx.cpp.
References _min_distance.
Referenced by collect().
int MB12XX::init () virtual
Definition at line 240 of file mb12xx.cpp.
References _class_instance, _cycling_rate, _distance_sensor_topic, _index_counter, _latest_sonar_measurements, _orb_class_instance, _reports, _sensor_ok, addr_ind, counter, DEVICE_DEBUG, DEVICE_LOG, lis3mdl::init(), MB12XX_BASEADDR, MB12XX_CONVERSION_INTERVAL, MB12XX_MAX_RANGEFINDERS, measure(), OK, orb_advertise_multi(), ORB_ID, ORB_PRIO_LOW, PX4_ERROR, RANGE_FINDER_BASE_DEVICE_PATH, TICKS_BETWEEN_SUCCESIVE_FIRES, and usleep().
Referenced by mb12xx::start_bus().
int MB12XX::ioctl (device::file_t * filp, int cmd, unsigned long arg) virtual
Definition at line 345 of file mb12xx.cpp.
References _cycling_rate, _measure_ticks, _reports, ATOMIC_ENTER, ATOMIC_LEAVE, OK, SENSOR_POLLRATE_DEFAULT, SENSOR_POLLRATE_EXTERNAL, SENSOR_POLLRATE_MANUAL, SENSOR_POLLRATE_MAX, SENSORIOCGPOLLRATE, SENSORIOCRESET, SENSORIOCSPOLLRATE, SENSORIOCSQUEUEDEPTH, start(), and stop().
Referenced by mb12xx::reset(), mb12xx::start_bus(), and mb12xx::test().
int MB12XX::measure () private
Definition at line 506 of file mb12xx.cpp.
References _comms_errors, DEVICE_DEBUG, MB12XX_TAKE_RANGE_REG, OK, and perf_count().
Referenced by cycle(), init(), probe(), and read().
void MB12XX::print_info ()
Diagnostics - print some basic information about the driver.
Definition at line 671 of file mb12xx.cpp.
References _comms_errors, _measure_ticks, _reports, _sample_perf, and perf_print_counter().
Referenced by mb12xx::info().
int MB12XX::probe () protected virtual
Definition at line 315 of file mb12xx.cpp.
References measure().
int MB12XX::probe_address (uint8_t address) private
Test whether the device supported by the driver is present at a specific address.
Parameters
address The I2C bus address to probe.
Returns
True if the device is present.
ssize_t MB12XX::read (device::file_t * filp, char * buffer, size_t buflen) virtual
Definition at line 445 of file mb12xx.cpp.
References _cycling_rate, _measure_ticks, _reports, collect(), measure(), OK, and usleep().
Referenced by mb12xx::test().
void MB12XX::set_maximum_distance (float max) private
Definition at line 327 of file mb12xx.cpp.
References _max_distance, and max().
void MB12XX::set_minimum_distance (float min) private
Set the min and max distance thresholds if you want the end points of the sensors range to be brought in at all, otherwise it will use the defaults MB12XX_MIN_DISTANCE and MB12XX_MAX_DISTANCE.
Definition at line 321 of file mb12xx.cpp.
References _min_distance, and min().
void MB12XX::start () private
Initialise the automatic measurement state machine and start it.
Note
This function is called at open and error time. It might make sense to make it more aggressive about resetting the bus in case of errors.
Definition at line 580 of file mb12xx.cpp.
References _collect_phase, _reports, and cycle_trampoline().
Referenced by cycle(), and ioctl().
void MB12XX::stop () private
Stop the automatic measurement state machine.
Definition at line 592 of file mb12xx.cpp.
Referenced by ioctl(), and ~MB12XX().
Member Data Documentation
int MB12XX::_class_instance private
Definition at line 123 of file mb12xx.cpp.
Referenced by init(), and ~MB12XX().
bool MB12XX::_collect_phase private
Definition at line 122 of file mb12xx.cpp.
Referenced by cycle(), and start().
perf_counter_t MB12XX::_comms_errors private
Definition at line 129 of file mb12xx.cpp.
Referenced by collect(), measure(), print_info(), and ~MB12XX().
uint8_t MB12XX::_cycle_counter private
Definition at line 131 of file mb12xx.cpp.
Referenced by cycle().
int MB12XX::_cycling_rate private
Definition at line 132 of file mb12xx.cpp.
Referenced by cycle(), init(), ioctl(), and read().
orb_advert_t MB12XX::_distance_sensor_topic private
Definition at line 126 of file mb12xx.cpp.
Referenced by collect(), and init().
uint8_t MB12XX::_index_counter private
Definition at line 133 of file mb12xx.cpp.
Referenced by cycle(), and init().
std::vector<float> MB12XX::_latest_sonar_measurements private
Definition at line 136 of file mb12xx.cpp.
Referenced by init().
float MB12XX::_max_distance private
Definition at line 117 of file mb12xx.cpp.
Referenced by get_maximum_distance(), and set_maximum_distance().
int MB12XX::_measure_ticks private
Definition at line 121 of file mb12xx.cpp.
Referenced by cycle(), ioctl(), print_info(), and read().
float MB12XX::_min_distance private
Definition at line 116 of file mb12xx.cpp.
Referenced by get_minimum_distance(), and set_minimum_distance().
int MB12XX::_orb_class_instance private
Definition at line 124 of file mb12xx.cpp.
Referenced by init().
ringbuffer::RingBuffer* MB12XX::_reports private
Definition at line 119 of file mb12xx.cpp.
Referenced by collect(), init(), ioctl(), print_info(), read(), start(), and ~MB12XX().
uint8_t MB12XX::_rotation private
Definition at line 115 of file mb12xx.cpp.
Referenced by collect().
perf_counter_t MB12XX::_sample_perf private
Definition at line 128 of file mb12xx.cpp.
Referenced by collect(), print_info(), and ~MB12XX().
bool MB12XX::_sensor_ok private
Definition at line 120 of file mb12xx.cpp.
Referenced by init().
work_s MB12XX::_work private
Definition at line 118 of file mb12xx.cpp.
std::vector<uint8_t> MB12XX::addr_ind private
Definition at line 134 of file mb12xx.cpp.
Referenced by cycle(), and init().
The documentation for this class was generated from the following file:
src/drivers/distance_sensor/mb12xx/mb12xx.cpp