PX4 Firmware: src/drivers/imu/bmi055/bmi055_main.cpp File Reference
bmi055_main.cpp File Reference
#include "BMI055_accel.hpp"
#include "BMI055_gyro.hpp"
Namespaces
bmi055
Enumerations
enum sensor_type {
BMI055_NONE = 0, BMI055_ACCEL = 1, BMI055_GYRO, BMI088_NONE = 0,
BMI088_ACCEL = 1, BMI088_GYRO
}
Functions
__EXPORT int bmi055_main (int argc, char *argv[])
driver 'main' command
void bmi055::start (bool external_bus, enum Rotation rotation, enum sensor_type sensor)
Start the driver.
void bmi055::stop (bool, enum sensor_type)
void bmi055::info (bool external_bus, enum sensor_type sensor)
Print a little info about the driver.
void bmi055::regdump (bool external_bus, enum sensor_type sensor)
Dump the register information.
void bmi055::testerror (bool external_bus, enum sensor_type sensor)
deliberately produce an error to test recovery
void bmi055::usage ()
Prints info about the driver argument usage.
Variables
BMI055_accel * bmi055::g_acc_dev_int
BMI055_accel * bmi055::g_acc_dev_ext
BMI055_gyro * bmi055::g_gyr_dev_int
BMI055_gyro * bmi055::g_gyr_dev_ext
Enumeration Type Documentation
sensor_type
enum sensor_type
Enumerator
BMI055_NONE
BMI055_ACCEL
BMI055_GYRO
BMI088_NONE
BMI088_ACCEL
BMI088_GYRO
Definition at line 40 of file bmi055_main.cpp.
Function Documentation
bmi055_main()
int bmi055_main (int argc, char * argv[])
driver 'main' command
Definition at line 337 of file bmi055_main.cpp.
References BMI055_ACCEL, BMI055_GYRO, BMI055_NONE, bmi055::info(), bmi055::regdump(), ROTATION_NONE, bmi055::start(), bmi055::stop(), bmi055::testerror(), and bmi055::usage().