PX4 Firmware: src/platforms/px4_shutdown.h File Reference
px4_shutdown.h File Reference
Power-related API.
#include <stdbool.h>
Functions
__EXPORT int px4_register_shutdown_hook (shutdown_hook_t hook)
Register a method that should be called when powering off (and also on reboot).
__EXPORT int px4_unregister_shutdown_hook (shutdown_hook_t hook)
Unregister a shutdown hook.
__EXPORT int px4_shutdown_request (bool reboot, bool to_bootloader)
Request the system to shut down or reboot.
__EXPORT int px4_shutdown_lock (void)
Grab the shutdown lock.
__EXPORT int px4_shutdown_unlock (void)
Release the shutdown lock.
Variables
__BEGIN_DECLS typedef bool(* shutdown_hook_t)(void)
Shutdown hook callback method (.
Detailed Description
Power-related API.
Definition in file px4_shutdown.h.
Function Documentation
__EXPORT int px4_register_shutdown_hook (shutdown_hook_t hook)
Register a method that should be called when powering off (and also on reboot).
Parameters
hook callback method. It must not block, but return immediately. When the system is requested to shutdown, the registered hooks will be called regularily until either all of them return true, or a timeout is reached.
Returns
0 on success, <0 on error
Definition at line 138 of file shutdown.cpp.
References max_shutdown_hooks, pthread_mutex_lock(), pthread_mutex_unlock(), shutdown_hooks, and shutdown_mutex.
Referenced by px4_shutdown_unlock(), and px4::logger::Logger::run().
__EXPORT int px4_shutdown_lock (void)
Grab the shutdown lock.
It will prevent the system from shutting down until the lock is released. It is safe to call this recursively.
Returns
0 on success, <0 on error
Definition at line 52 of file shutdown.cpp.
References pthread_mutex_lock(), pthread_mutex_unlock(), shutdown_lock_counter, and shutdown_mutex.
Referenced by param_export(), param_export_internal(), and reboot_main().
__EXPORT int px4_shutdown_request (bool reboot, bool to_bootloader)
Request the system to shut down or reboot.
Note the following:
The system might not support to shutdown (or reboot). In that case -EINVAL will be returned.
The system might not shutdown immediately, so expect this method to return even on success.
Parameters
reboot perform a reboot instead of a shutdown
to_bootloader reboot into bootloader mode (only used if reboot is true)
Returns
0 on success, <0 on error
Definition at line 205 of file shutdown.cpp.
References SHUTDOWN_ARG_IN_PROGRESS, SHUTDOWN_ARG_REBOOT, SHUTDOWN_ARG_TO_BOOTLOADER, shutdown_args, and shutdown_worker().
Referenced by commander_low_prio_loop(), px4_shutdown_unlock(), reboot_main(), and Commander::run().
__EXPORT int px4_shutdown_unlock (void)
Release the shutdown lock.
Returns
0 on success, <0 on error
Definition at line 64 of file shutdown.cpp.
References board_shutdown(), pthread_mutex_lock(), pthread_mutex_unlock(), PX4_ERR, px4_register_shutdown_hook(), px4_shutdown_request(), px4_systemreset(), px4_unregister_shutdown_hook(), shutdown_hook_t, shutdown_lock_counter, and shutdown_mutex.
Referenced by param_export(), param_export_internal(), and reboot_main().
__EXPORT int px4_unregister_shutdown_hook (shutdown_hook_t hook)
Unregister a shutdown hook.
Parameters
hook callback method to be removed
Returns
0 on success, <0 on error
Definition at line 154 of file shutdown.cpp.
References max_shutdown_hooks, pthread_mutex_lock(), pthread_mutex_unlock(), shutdown_hooks, and shutdown_mutex.
Referenced by px4_shutdown_unlock(), and px4::logger::Logger::run().
Variable Documentation
__BEGIN_DECLS typedef bool(* shutdown_hook_t) (void)
Shutdown hook callback method (.
See also
px4_register_shutdown_hook()).
Returns
true if it's ok to shutdown, false if more time needed for cleanup
Definition at line 49 of file px4_shutdown.h.
Referenced by px4_shutdown_unlock().