PX4 Firmware: src/lib/matrix/test/attitude.cpp File Reference
attitude.cpp File Reference
#include "test_macros.hpp"
#include <matrix/math.hpp>
#include <iostream>
Namespaces
matrix
Functions
int main ()
Function Documentation
main()
int main ()
Definition at line 21 of file attitude.cpp.
References matrix::AxisAngle< Type >::angle(), matrix::AxisAngle< Type >::axis(), matrix::Quaternion< Type >::canonical(), matrix::Quaternion< Type >::canonicalize(), matrix::Quaternion< Type >::conjugate(), matrix::Quaternion< Type >::conjugate_inversed(), matrix::cos(), matrix::Quaternion< Type >::dcm_z(), matrix::Quaternion< Type >::derivative1(), matrix::Quaternion< Type >::derivative2(), err, f(), matrix::Quaternion< Type >::from_axis_angle(), matrix::Quaternion< Type >::from_dcm(), matrix::Quaternion< Type >::imag(), matrix::Quaternion< Type >::inversed(), matrix::Quaternion< Type >::invert(), matrix::isEqual(), matrix::isEqualF(), M_PI, matrix::Vector< Type, M >::norm(), matrix::Vector< Type, M >::normalize(), matrix::Vector< Type, M >::normalized(), matrix::Dcm< Type >::renormalize(), matrix::Quaternion< Type >::rotate(), matrix::Matrix< Type, M, N >::row(), matrix::Matrix< Type, M, N >::setIdentity(), matrix::sin(), matrix::sqrt(), matrix::Matrix< Type, M, N >::T(), TEST, matrix::Quaternion< Type >::to_axis_angle(), matrix::Quaternion< Type >::to_dcm(), and matrix::Vector< Type, M >::unit().