PX4 Firmware: MavlinkStreamCameraTrigger Class Reference
MavlinkStreamCameraTrigger Class Reference
Public Member Functions
const char * get_name () const
uint16_t get_id ()
bool const_rate ()
unsigned get_size ()
Get maximal total messages size on update.
Public Member Functions inherited from MavlinkStream
MavlinkStream (Mavlink *mavlink)
virtual ~MavlinkStream ()=default
MavlinkStream (const MavlinkStream &)=delete
MavlinkStream & operator= (const MavlinkStream &)=delete
MavlinkStream (MavlinkStream &&)=delete
MavlinkStream & operator= (MavlinkStream &&)=delete
void set_interval (const int interval)
Get the interval.
int get_interval ()
Get the interval.
int update (const hrt_abstime &t)
Update subscriptions and send message if necessary.
virtual unsigned get_size_avg ()
Get the average message size.
bool first_message_sent () const
void reset_last_sent ()
Reset the time of last sent to 0.
Static Public Member Functions
static const char * get_name_static ()
static uint16_t get_id_static ()
static MavlinkStream * new_instance (Mavlink *mavlink)
Protected Member Functions
MavlinkStreamCameraTrigger (Mavlink *mavlink)
bool send (const hrt_abstime t)
Protected Member Functions inherited from MavlinkStream
virtual void update_data ()
Function to collect/update data for the streams at a high rate independant of actual stream rate.
Private Member Functions
MavlinkStreamCameraTrigger (MavlinkStreamCameraTrigger &)=delete
MavlinkStreamCameraTrigger & operator= (const MavlinkStreamCameraTrigger &)=delete
Private Attributes
MavlinkOrbSubscription * _trigger_sub
uint64_t _trigger_time
Additional Inherited Members
Public Attributes inherited from MavlinkStream
MavlinkStream * next {nullptr}
Protected Attributes inherited from MavlinkStream
Mavlink *const _mavlink
int _interval {1000000}
if set to negative value = unlimited rate
Detailed Description
Definition at line 1677 of file mavlink_messages.cpp.
Constructor & Destructor Documentation
MavlinkStreamCameraTrigger::MavlinkStreamCameraTrigger (MavlinkStreamCameraTrigger &) private delete
MavlinkStreamCameraTrigger::MavlinkStreamCameraTrigger (Mavlink * mavlink) inline explicit protected
Definition at line 1724 of file mavlink_messages.cpp.
Member Function Documentation
bool MavlinkStreamCameraTrigger::const_rate () inline virtual
Returns
true if steam rate shouldn't be adjusted
Reimplemented from MavlinkStream.
Definition at line 1705 of file mavlink_messages.cpp.
uint16_t MavlinkStreamCameraTrigger::get_id () inline virtual
Implements MavlinkStream.
Definition at line 1695 of file mavlink_messages.cpp.
References MavlinkStreamHeartbeat::get_id_static().
static uint16_t MavlinkStreamCameraTrigger::get_id_static () inline static
Definition at line 1690 of file mavlink_messages.cpp.
const char* MavlinkStreamCameraTrigger::get_name () const inline virtual
Implements MavlinkStream.
Definition at line 1680 of file mavlink_messages.cpp.
References get_name_static().
static const char* MavlinkStreamCameraTrigger::get_name_static () inline static
Definition at line 1685 of file mavlink_messages.cpp.
Referenced by get_name().
unsigned MavlinkStreamCameraTrigger::get_size () inline virtual
Get maximal total messages size on update.
Implements MavlinkStream.
Definition at line 1710 of file mavlink_messages.cpp.
static MavlinkStream* MavlinkStreamCameraTrigger::new_instance (Mavlink * mavlink) inline static
Definition at line 1700 of file mavlink_messages.cpp.
MavlinkStreamCameraTrigger& MavlinkStreamCameraTrigger::operator= (const MavlinkStreamCameraTrigger &) private delete
bool MavlinkStreamCameraTrigger::send (const hrt_abstime t) inline protected virtual
Implements MavlinkStream.
Definition at line 1729 of file mavlink_messages.cpp.
References MavlinkStream::_mavlink, Mavlink::get_channel(), MavlinkCommandSender::handle_vehicle_command(), hrt_absolute_time(), MavlinkCommandSender::instance(), mavlink_system, msg, camera_trigger_s::seq, camera_trigger_s::timestamp, vehicle_command_s::timestamp, and MavlinkOrbSubscription::update().
Member Data Documentation
MavlinkOrbSubscription* MavlinkStreamCameraTrigger::_trigger_sub private
Definition at line 1716 of file mavlink_messages.cpp.
uint64_t MavlinkStreamCameraTrigger::_trigger_time private
Definition at line 1717 of file mavlink_messages.cpp.
The documentation for this class was generated from the following file:
src/modules/mavlink/mavlink_messages.cpp