PX4 Firmware: src/drivers/boards/px4fmu-v5/init.c File Reference
init.c File Reference
#include <px4_config.h>
#include <px4_tasks.h>
#include <px4_log.h>
#include <stdbool.h>
#include <stdio.h>
#include <string.h>
#include <debug.h>
#include <errno.h>
#include "platform/cxxinitialize.h"
#include <nuttx/board.h>
#include <nuttx/spi/spi.h>
#include <nuttx/i2c/i2c_master.h>
#include <nuttx/sdio.h>
#include <nuttx/mmcsd.h>
#include <nuttx/analog/adc.h>
#include <nuttx/mm/gran.h>
#include <chip.h>
#include "board_config.h"
#include <stm32_uart.h>
#include <arch/board/board.h>
#include <drivers/drv_hrt.h>
#include <drivers/drv_board_led.h>
#include <systemlib/px4_macros.h>
#include <systemlib/cpuload.h>
#include <perf/perf_counter.h>
#include <systemlib/err.h>
#include <systemlib/hardfault_log.h>
#include <parameters/param.h>
#include "up_internal.h"
Functions
__BEGIN_DECLS void led_init (void)
Ideally we'd be able to get these from up_internal.h, but since we want to be able to disable the NuttX use of leds for system indication at will and there is no separate switch, we need to build independent of the CONFIG_ARCH_LEDS configuration switch.
void led_on (int led)
void led_off (int led)
__END_DECLS __EXPORT void board_rc_input (bool invert_on, uint32_t uxart_base)
__EXPORT void board_peripheral_reset (int ms)
__EXPORT void board_on_reset (int status)
__EXPORT void stm32_boardinitialize (void)
__EXPORT int board_app_initialize (uintptr_t arg)
Function Documentation
__EXPORT int board_app_initialize (uintptr_t arg)
Definition at line 266 of file init.c.
References BBSRAM_PATH, board_autoled_on(), board_determine_hw_info(), board_dma_alloc_init, board_get_hw_revision(), board_get_hw_type_name(), board_get_hw_version(), BSRAM_FILE_SIZES, drv_led_start(), hardfault_check_status(), HARDFAULT_DISPLAY_FORMAT, hardfault_increment_reboot(), hardfault_rearm(), hardfault_write(), hrt_call_every(), hrt_init(), LED_BLUE, LED_GREEN, led_off(), LED_RED, OK, param_init(), PX4_ERR, PX4_INFO, stm32_sdio_initialize(), stm32_spi_bus_initialize(), ts_to_abstime(), VDD_3V3_SD_CARD_EN, VDD_3V3_SENSORS_EN, VDD_3V3_SPEKTRUM_POWER_EN, VDD_5V_HIPOWER_EN, VDD_5V_PERIPH_EN, VDD_5V_RC_EN, and VDD_5V_WIFI_EN.
__EXPORT void board_on_reset (int status)
Definition at line 193 of file init.c.
References arraySize, board_gpio_init(), and PX4_GPIO_PWM_INIT_LIST.
__EXPORT void board_peripheral_reset (int ms)
Definition at line 158 of file init.c.
References READ_VDD_3V3_SPEKTRUM_POWER_EN, usleep(), VDD_3V3_SENSORS_EN, VDD_3V3_SPEKTRUM_POWER_EN, VDD_5V_PERIPH_EN, and warnx.
__END_DECLS __EXPORT void board_rc_input (bool invert_on, uint32_t uxart_base)
Definition at line 117 of file init.c.
__BEGIN_DECLS void led_init (void)
Ideally we'd be able to get these from up_internal.h, but since we want to be able to disable the NuttX use of leds for system indication at will and there is no separate switch, we need to build independent of the CONFIG_ARCH_LEDS configuration switch.
Definition at line 72 of file led.c.
void led_off (int led)
Definition at line 97 of file led.c.
void led_on (int led)
Definition at line 92 of file led.c.
__EXPORT void stm32_boardinitialize (void)
Definition at line 217 of file init.c.
References arraySize, board_autoled_initialize(), board_gpio_init(), board_on_reset(), PX4_GPIO_INIT_LIST, stm32_spiinitialize(), and stm32_usbinitialize().