PX4 Firmware: uORB::SubscriptionBase Class Reference
uORB::SubscriptionBase Class Reference
Base subscription wrapper class, used in list traversal of various subscriptions.
#include <Subscription.hpp>
Public Member Functions
SubscriptionBase (const struct orb_metadata *meta, unsigned interval=0, unsigned instance=0)
Constructor.
virtual ~SubscriptionBase ()
SubscriptionBase (const SubscriptionBase &)=delete
SubscriptionBase & operator= (const SubscriptionBase &)=delete
SubscriptionBase (SubscriptionBase &&)=delete
SubscriptionBase & operator= (SubscriptionBase &&)=delete
bool updated ()
Check if there is a new update.
bool update (void *data)
Update the struct.
int getHandle () const
const orb_metadata * getMeta () const
unsigned getInstance () const
Protected Attributes
const struct orb_metadata * _meta
unsigned _instance
int _handle
Detailed Description
Base subscription wrapper class, used in list traversal of various subscriptions.
Definition at line 53 of file Subscription.hpp.
Constructor & Destructor Documentation
uORB::SubscriptionBase::SubscriptionBase (const struct orb_metadata * meta, unsigned interval = 0, unsigned instance = 0)
Constructor.
Parameters
meta The uORB metadata (usually from the ORB_ID() macro) for the topic.
interval The minimum interval in milliseconds between updates
instance The instance for multi sub.
Definition at line 45 of file Subscription.cpp.
References _handle, _meta, orb_metadata::o_name, orb_set_interval(), orb_subscribe(), orb_subscribe_multi(), and PX4_ERR.
uORB::SubscriptionBase::~SubscriptionBase () virtual
Definition at line 92 of file Subscription.cpp.
References _handle, _meta, orb_metadata::o_name, orb_unsubscribe(), PX4_ERR, and PX4_OK.
uORB::SubscriptionBase::SubscriptionBase (const SubscriptionBase &) delete
uORB::SubscriptionBase::SubscriptionBase (SubscriptionBase &&) delete
Member Function Documentation
int uORB::SubscriptionBase::getHandle () const inline
Definition at line 85 of file Subscription.hpp.
Referenced by BlockLocalPositionEstimator::BlockLocalPositionEstimator(), MD25::MD25(), and RoboClaw::RoboClaw().
unsigned uORB::SubscriptionBase::getInstance () const inline
Definition at line 89 of file Subscription.hpp.
const orb_metadata* uORB::SubscriptionBase::getMeta () const inline
Definition at line 87 of file Subscription.hpp.
SubscriptionBase& uORB::SubscriptionBase::operator= (const SubscriptionBase &) delete
SubscriptionBase& uORB::SubscriptionBase::operator= (SubscriptionBase &&) delete
bool uORB::SubscriptionBase::update (void * data)
Update the struct.
Parameters
data The uORB message struct we are updating.
Definition at line 76 of file Subscription.cpp.
References _handle, _meta, orb_metadata::o_name, orb_copy(), PX4_ERR, PX4_OK, and updated().
Referenced by uORB::Subscription< vehicle_land_detected_s >::update(), and px4::SubscriberUORBCallback< T >::update().
bool uORB::SubscriptionBase::updated ()
Check if there is a new update.
Definition at line 65 of file Subscription.cpp.
References _handle, _meta, orb_metadata::o_name, orb_check(), PX4_ERR, and PX4_OK.
Referenced by update(), RoboClaw::update(), BlockLocalPositionEstimator::update(), MD25::update(), and px4::SubscriberUORBCallback< T >::update().
Member Data Documentation
int uORB::SubscriptionBase::_handle protected
Definition at line 94 of file Subscription.hpp.
Referenced by SubscriptionBase(), update(), updated(), and ~SubscriptionBase().
unsigned uORB::SubscriptionBase::_instance protected
Definition at line 93 of file Subscription.hpp.
const struct orb_metadata* uORB::SubscriptionBase::_meta protected
Definition at line 92 of file Subscription.hpp.
Referenced by SubscriptionBase(), update(), updated(), and ~SubscriptionBase().
The documentation for this class was generated from the following files:
src/modules/uORB/Subscription.hpp
src/modules/uORB/Subscription.cpp