PX4 Firmware: src/drivers/roboclaw/roboclaw_main.cpp File Reference
roboclaw_main.cpp File Reference
#include <px4_config.h>
#include <unistd.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <math.h>
#include <parameters/param.h>
#include <arch/board/board.h>
#include "RoboClaw.hpp"
Functions
__EXPORT int roboclaw_main (int argc, char *argv[])
Deamon management function.
int roboclaw_thread_main (int argc, char *argv[])
Mainloop of deamon.
static void usage ()
Print the correct usage.
Variables
static bool thread_should_exit = false
@ file roboclaw_main.cpp
static bool thread_running = false
Deamon status flag.
static int deamon_task
Handle of deamon task / thread.
Function Documentation
int roboclaw_main (int argc, char * argv[])
Deamon management function.
The deamon app only briefly exists to start the background job.
The stack size assigned in the Makefile does only apply to this management task.
The actual stack size should be set in the call to task_create().
Definition at line 91 of file roboclaw_main.cpp.
References deamon_task, px4_task_spawn_cmd(), roboclaw_thread_main(), roboclawTest(), SCHED_DEFAULT, SCHED_PRIORITY_MAX, thread_running, thread_should_exit, and usage().
int roboclaw_thread_main (int argc, char * argv[])
Mainloop of deamon.
Definition at line 162 of file roboclaw_main.cpp.
References thread_running, thread_should_exit, and RoboClaw::update().
Referenced by roboclaw_main().
static void usage (void) static
Print the correct usage.
Definition at line 77 of file roboclaw_main.cpp.
Referenced by roboclaw_main().
Variable Documentation
int deamon_task static
Handle of deamon task / thread.
Definition at line 60 of file roboclaw_main.cpp.
Referenced by roboclaw_main().
bool thread_running = false static
Deamon status flag.
Definition at line 59 of file roboclaw_main.cpp.
Referenced by roboclaw_main(), and roboclaw_thread_main().
bool thread_should_exit = false static
@ file roboclaw_main.cpp
RoboClaw Motor Driver
references: http://downloads.orionrobotics.com/downloads/datasheets/motor_controller_robo_claw_R0401.pdfDeamon exit flag
Definition at line 58 of file roboclaw_main.cpp.
Referenced by roboclaw_main(), and roboclaw_thread_main().