PX4 Firmware: src/systemcmds/top/top.c File Reference
top.c File Reference
Tool similar to UNIX top command.
#include <px4_platform_common/px4_config.h>
#include <stdio.h>
#include <fcntl.h>
#include <stdbool.h>
#include <unistd.h>
#include <string.h>
#include <poll.h>
#include <systemlib/cpuload.h>
#include <systemlib/printload.h>
#include <drivers/drv_hrt.h>
#include <px4_platform_common/module.h>
Functions
__EXPORT int top_main (int argc, char *argv[])
Start the top application.
static void print_usage (void)
Detailed Description
Tool similar to UNIX top command.
See also
http://en.wikipedia.org/wiki/Top_unix
Author
Lorenz Meier loren.nosp@m.z@px.nosp@m.4.io
Definition in file top.c.
Function Documentation
print_usage()
static void print_usage (void) static
Definition at line 61 of file top.c.
Referenced by top_main().
top_main()
int top_main (int argc, char * argv[])
Start the top application.
Definition at line 70 of file top.c.
References hrt_absolute_time(), hrt_abstime, init_print_load_s(), print_load(), print_usage(), and read().