PX4 Firmware: BBBlueADC Class Reference
BBBlueADC Class Reference
Public Member Functions
BBBlueADC ()
virtual ~BBBlueADC ()
virtual int init ()
virtual ssize_t devRead (void *buf, size_t count) override
virtual int devIOCTL (unsigned long request, unsigned long arg) override
Protected Member Functions
virtual void _measure () override
Private Attributes
pthread_mutex_t _samples_lock
px4_adc_msg_t _samples [BBBLUE_MAX_ADC_CHANNELS]
Detailed Description
Definition at line 69 of file bbblue_adc.cpp.
Constructor & Destructor Documentation
BBBlueADC::BBBlueADC ()
Definition at line 88 of file bbblue_adc.cpp.
References _samples_lock, and pthread_mutex_init().
Referenced by bbblue_adc_main().
BBBlueADC::~BBBlueADC () virtual
Definition at line 94 of file bbblue_adc.cpp.
References _samples_lock, pthread_mutex_destroy(), and rc_cleaning().
Member Function Documentation
void BBBlueADC::_measure () override protected virtual
Definition at line 101 of file bbblue_adc.cpp.
References _samples, _samples_lock, BBBLUE_ADC_DC_JACK_VOLTAGE_CHANNEL, BBBLUE_ADC_LIPO_BATTERY_VOLTAGE_CHANNEL, BBBLUE_MAX_ADC_CHANNELS, BBBLUE_MAX_ADC_USER_CHANNELS, pthread_mutex_lock(), pthread_mutex_unlock(), and px4_adc_msg_t.
Referenced by init().
int BBBlueADC::devIOCTL (unsigned long request, unsigned long arg) override virtual
Definition at line 139 of file bbblue_adc.cpp.
ssize_t BBBlueADC::devRead (void * buf, size_t count) override virtual
Definition at line 144 of file bbblue_adc.cpp.
References _samples, _samples_lock, and pthread_mutex_unlock().
Referenced by bbblue_adc_main().
int BBBlueADC::init () virtual
Definition at line 123 of file bbblue_adc.cpp.
References _measure(), lis3mdl::init(), PX4_ERR, PX4_OK, and rc_init().
Referenced by bbblue_adc_main().
Member Data Documentation
px4_adc_msg_t BBBlueADC::_samples[BBBLUE_MAX_ADC_CHANNELS] private
Definition at line 85 of file bbblue_adc.cpp.
Referenced by _measure(), and devRead().
pthread_mutex_t BBBlueADC::_samples_lock private
Definition at line 84 of file bbblue_adc.cpp.
Referenced by _measure(), BBBlueADC(), devRead(), and ~BBBlueADC().
The documentation for this class was generated from the following file:
src/drivers/bbblue_adc/bbblue_adc.cpp