PX4 Firmware: src/drivers/telemetry/iridiumsbd/IridiumSBD.h File Reference
IridiumSBD.h File Reference
#include <stdlib.h>
#include <stdbool.h>
#include <drivers/device/device.h>
#include <drivers/drv_hrt.h>
#include <uORB/uORB.h>
#include <uORB/topics/iridiumsbd_status.h>
#include <uORB/topics/subsystem_info.h>
Classes
class IridiumSBD
The driver for the Rockblock 9602 and 9603 RockBlock module for satellite communication over the Iridium satellite system.
Macros
#define SATCOM_TX_BUF_LEN 340
#define SATCOM_MAX_MESSAGE_LENGTH 50
#define SATCOM_RX_MSG_BUF_LEN 270
#define SATCOM_RX_COMMAND_BUF_LEN 50
#define SATCOM_SIGNAL_REFRESH_DELAY 20000000
Enumerations
enum satcom_status { SATCOM_OK = 0, SATCOM_NO_MSG = -1, SATCOM_ERROR = -255 }
enum satcom_uart_status { SATCOM_UART_OK = 0, SATCOM_UART_OPEN_FAIL = -1 }
enum satcom_read_status { SATCOM_READ_OK = 0, SATCOM_READ_TIMEOUT = -1, SATCOM_READ_PARSING_FAIL = -2 }
enum satcom_result_code {
SATCOM_RESULT_OK, SATCOM_RESULT_ERROR, SATCOM_RESULT_SBDRING, SATCOM_RESULT_READY,
SATCOM_RESULT_HWFAIL, SATCOM_RESULT_NA
}
enum satcom_state { SATCOM_STATE_STANDBY, SATCOM_STATE_CSQ, SATCOM_STATE_SBDSESSION, SATCOM_STATE_TEST }
Functions
__EXPORT int iridiumsbd_main (int argc, char *argv[])
Macro Definition Documentation
#define SATCOM_MAX_MESSAGE_LENGTH 50
Definition at line 88 of file IridiumSBD.h.
Referenced by IridiumSBD::ioctl().
#define SATCOM_RX_COMMAND_BUF_LEN 50
Definition at line 90 of file IridiumSBD.h.
#define SATCOM_RX_MSG_BUF_LEN 270
Definition at line 89 of file IridiumSBD.h.
#define SATCOM_SIGNAL_REFRESH_DELAY 20000000
Definition at line 91 of file IridiumSBD.h.
Referenced by IridiumSBD::standby_loop().
#define SATCOM_TX_BUF_LEN 340
Definition at line 87 of file IridiumSBD.h.
Referenced by IridiumSBD::ioctl(), IridiumSBD::poll_state(), and IridiumSBD::write().
Enumeration Type Documentation
enum satcom_read_status
Enumerator
SATCOM_READ_OK
SATCOM_READ_TIMEOUT
SATCOM_READ_PARSING_FAIL
Definition at line 57 of file IridiumSBD.h.
enum satcom_result_code
Enumerator
SATCOM_RESULT_OK
SATCOM_RESULT_ERROR
SATCOM_RESULT_SBDRING
SATCOM_RESULT_READY
SATCOM_RESULT_HWFAIL
SATCOM_RESULT_NA
Definition at line 63 of file IridiumSBD.h.
enum satcom_state
Enumerator
SATCOM_STATE_STANDBY
SATCOM_STATE_CSQ
SATCOM_STATE_SBDSESSION
SATCOM_STATE_TEST
Definition at line 78 of file IridiumSBD.h.
enum satcom_status
Enumerator
SATCOM_OK
SATCOM_NO_MSG
SATCOM_ERROR
Definition at line 46 of file IridiumSBD.h.
enum satcom_uart_status
Enumerator
SATCOM_UART_OK
SATCOM_UART_OPEN_FAIL
Definition at line 52 of file IridiumSBD.h.
Function Documentation
__EXPORT int iridiumsbd_main (int argc, char * argv[])
Definition at line 1159 of file IridiumSBD.cpp.
References OK, PX4_ERROR, PX4_INFO, IridiumSBD::start(), IridiumSBD::status(), IridiumSBD::stop(), and IridiumSBD::test().