PX4 Firmware: MavlinkTimesync Class Reference
MavlinkTimesync Class Reference
#include <mavlink_timesync.h>
Public Member Functions
MavlinkTimesync (Mavlink *mavlink)
~MavlinkTimesync ()
void handle_message (const mavlink_message_t *msg)
uint64_t sync_stamp (uint64_t usec)
Convert remote timestamp to local hrt time (usec) Use synchronised time if available, monotonic boot time otherwise.
Protected Member Functions
void add_sample (int64_t offset_us)
Online exponential filter to smooth time offset.
bool sync_converged ()
Return true if the timesync algorithm converged to a good estimate, return false otherwise.
void reset_filter ()
Reset the exponential filter and its states.
Protected Attributes
orb_advert_t _timesync_status_pub {nullptr}
uint32_t _sequence {0}
double _time_offset {0}
double _time_skew {0}
double _filter_alpha {ALPHA_GAIN_INITIAL}
double _filter_beta {BETA_GAIN_INITIAL}
uint32_t _high_deviation_count {0}
uint32_t _high_rtt_count {0}
Mavlink *const _mavlink
Private Member Functions
MavlinkTimesync (MavlinkTimesync &)
MavlinkTimesync & operator= (const MavlinkTimesync &)
Detailed Description
Definition at line 97 of file mavlink_timesync.h.
Constructor & Destructor Documentation
MavlinkTimesync::MavlinkTimesync (Mavlink * mavlink) explicit
Definition at line 44 of file mavlink_timesync.cpp.
MavlinkTimesync::~MavlinkTimesync ()
Definition at line 49 of file mavlink_timesync.cpp.
References _timesync_status_pub, and orb_unadvertise().
MavlinkTimesync::MavlinkTimesync (MavlinkTimesync &) private
Member Function Documentation
void MavlinkTimesync::add_sample (int64_t offset_us) protected
Online exponential filter to smooth time offset.
Definition at line 215 of file mavlink_timesync.cpp.
References _filter_alpha, _filter_beta, _sequence, _time_offset, and _time_skew.
Referenced by handle_message().
void MavlinkTimesync::handle_message (const mavlink_message_t * msg)
Definition at line 57 of file mavlink_timesync.cpp.
References _filter_alpha, _filter_beta, _high_deviation_count, _high_rtt_count, _mavlink, _sequence, _time_offset, _timesync_status_pub, add_sample(), ALPHA_GAIN_FINAL, ALPHA_GAIN_INITIAL, BETA_GAIN_FINAL, BETA_GAIN_INITIAL, CONVERGENCE_WINDOW, timesync_status_s::estimated_offset, Mavlink::get_channel(), hrt_absolute_time(), instance, MAX_CONSECUTIVE_HIGH_DEVIATION, MAX_CONSECUTIVE_HIGH_RTT, MAX_DEVIATION_SAMPLE, MAX_RTT_SAMPLE, timesync_status_s::observed_offset, orb_advertise_multi(), ORB_ID, ORB_PRIO_DEFAULT, orb_publish(), px4_clock_gettime, px4_clock_settime, PX4_EPOCH_SECS, PX4_ERR, PX4_WARN, timesync_status_s::remote_timestamp, reset_filter(), timesync_status_s::round_trip_time, sync_converged(), and timesync_status_s::timestamp.
Referenced by MavlinkReceiver::receive_thread().
MavlinkTimesync& MavlinkTimesync::operator= (const MavlinkTimesync &) private
void MavlinkTimesync::reset_filter () protected
Reset the exponential filter and its states.
Definition at line 238 of file mavlink_timesync.cpp.
References _filter_alpha, _filter_beta, _high_deviation_count, _high_rtt_count, _sequence, _time_offset, _time_skew, ALPHA_GAIN_INITIAL, and BETA_GAIN_INITIAL.
Referenced by handle_message().
bool MavlinkTimesync::sync_converged () protected
Return true if the timesync algorithm converged to a good estimate, return false otherwise.
Definition at line 209 of file mavlink_timesync.cpp.
References _sequence, and CONVERGENCE_WINDOW.
Referenced by handle_message(), and sync_stamp().
uint64_t MavlinkTimesync::sync_stamp (uint64_t usec)
Convert remote timestamp to local hrt time (usec) Use synchronised time if available, monotonic boot time otherwise.
Definition at line 197 of file mavlink_timesync.cpp.
References _time_offset, hrt_absolute_time(), and sync_converged().
Referenced by MavlinkReceiver::handle_message_att_pos_mocap(), MavlinkReceiver::handle_message_attitude_quaternion_cov(), MavlinkReceiver::handle_message_debug(), MavlinkReceiver::handle_message_debug_vect(), MavlinkReceiver::handle_message_follow_target(), MavlinkReceiver::handle_message_landing_target(), MavlinkReceiver::handle_message_local_position_ned_cov(), MavlinkReceiver::handle_message_named_value_float(), MavlinkReceiver::handle_message_obstacle_distance(), MavlinkReceiver::handle_message_optical_flow_rad(), MavlinkReceiver::handle_message_set_actuator_control_target(), MavlinkReceiver::handle_message_set_attitude_target(), MavlinkReceiver::handle_message_set_position_target_local_ned(), MavlinkReceiver::handle_message_trajectory_representation_waypoints(), and MavlinkReceiver::handle_message_vision_position_estimate().
Member Data Documentation
double MavlinkTimesync::_filter_alpha {ALPHA_GAIN_INITIAL} protected
Definition at line 144 of file mavlink_timesync.h.
Referenced by add_sample(), handle_message(), and reset_filter().
double MavlinkTimesync::_filter_beta {BETA_GAIN_INITIAL} protected
Definition at line 145 of file mavlink_timesync.h.
Referenced by add_sample(), handle_message(), and reset_filter().
uint32_t MavlinkTimesync::_high_deviation_count {0} protected
Definition at line 148 of file mavlink_timesync.h.
Referenced by handle_message(), and reset_filter().
uint32_t MavlinkTimesync::_high_rtt_count {0} protected
Definition at line 149 of file mavlink_timesync.h.
Referenced by handle_message(), and reset_filter().
Mavlink* const MavlinkTimesync::_mavlink protected
Definition at line 151 of file mavlink_timesync.h.
Referenced by handle_message().
uint32_t MavlinkTimesync::_sequence {0} protected
Definition at line 137 of file mavlink_timesync.h.
Referenced by add_sample(), handle_message(), reset_filter(), and sync_converged().
double MavlinkTimesync::_time_offset {0} protected
Definition at line 140 of file mavlink_timesync.h.
Referenced by add_sample(), handle_message(), reset_filter(), and sync_stamp().
double MavlinkTimesync::_time_skew {0} protected
Definition at line 141 of file mavlink_timesync.h.
Referenced by add_sample(), and reset_filter().
orb_advert_t MavlinkTimesync::_timesync_status_pub {nullptr} protected
Definition at line 135 of file mavlink_timesync.h.
Referenced by handle_message(), and ~MavlinkTimesync().
The documentation for this class was generated from the following files:
src/modules/mavlink/mavlink_timesync.h
src/modules/mavlink/mavlink_timesync.cpp