PX4 Firmware: src/drivers/distance_sensor/srf02/srf02.cpp File Reference
srf02.cpp File Reference
Driver for the SRF02 sonar range finder adapted from the Maxbotix sonar range finder driver (mb12xx).
#include <px4_config.h>
#include <px4_defines.h>
#include <px4_getopt.h>
#include <px4_workqueue.h>
#include <drivers/device/i2c.h>
#include <sys/types.h>
#include <stdint.h>
#include <stdlib.h>
#include <stdbool.h>
#include <semaphore.h>
#include <string.h>
#include <fcntl.h>
#include <poll.h>
#include <stdio.h>
#include <math.h>
#include <unistd.h>
#include <vector>
#include <perf/perf_counter.h>
#include <drivers/drv_hrt.h>
#include <drivers/drv_range_finder.h>
#include <drivers/device/ringbuffer.h>
#include <uORB/uORB.h>
#include <uORB/topics/distance_sensor.h>
#include <board_config.h>
Classes
class SRF02
Namespaces
srf02
Local functions in support of the shell command.
Macros
#define SRF02_BUS_DEFAULT PX4_I2C_BUS_EXPANSION
#define SRF02_BASEADDR 0x70 /* 7-bit address. 8-bit address is 0xE0 */
#define SRF02_DEVICE_PATH "/dev/srf02"
#define SRF02_TAKE_RANGE_REG 0x51 /* Measure range Register */
#define SRF02_SET_ADDRESS_0 0xA0 /* Change address 0 Register */
#define SRF02_SET_ADDRESS_1 0xAA /* Change address 1 Register */
#define SRF02_SET_ADDRESS_2 0xA5 /* Change address 2 Register */
#define SRF02_MIN_DISTANCE (0.20f)
#define SRF02_MAX_DISTANCE (7.65f)
#define SRF02_CONVERSION_INTERVAL 100000 /* 60ms for one sonar */
#define TICKS_BETWEEN_SUCCESIVE_FIRES 100000 /* 30ms between each sonar measurement (watch out for interference!) */
Functions
__EXPORT int srf02_main (int argc, char *argv[])
int srf02::start (uint8_t rotation)
Attempt to start driver on all available I2C busses.
int srf02::start_bus (uint8_t rotation, int i2c_bus)
Start the driver on a specific bus.
int srf02::stop ()
Stop the driver.
int srf02::test ()
Perform some basic functional tests on the driver; make sure we can collect data from the sensor in polled and automatic modes.
int srf02::reset ()
Reset the driver.
int srf02::info ()
Print a little info about the driver.
static void srf02_usage ()
Variables
SRF02 * srf02::g_dev
Detailed Description
Driver for the SRF02 sonar range finder adapted from the Maxbotix sonar range finder driver (mb12xx).
Definition in file srf02.cpp.
Macro Definition Documentation
#define SRF02_BASEADDR 0x70 /* 7-bit address. 8-bit address is 0xE0 */
Definition at line 73 of file srf02.cpp.
Referenced by SRF02::init().
#define SRF02_BUS_DEFAULT PX4_I2C_BUS_EXPANSION
Definition at line 72 of file srf02.cpp.
Referenced by srf02_main(), and srf02_usage().
#define SRF02_CONVERSION_INTERVAL 100000 /* 60ms for one sonar */
Definition at line 87 of file srf02.cpp.
Referenced by SRF02::init().
#define SRF02_DEVICE_PATH "/dev/srf02"
Definition at line 74 of file srf02.cpp.
Referenced by srf02::reset(), srf02::start_bus(), and srf02::test().
#define SRF02_MAX_DISTANCE (7.65f)
Definition at line 85 of file srf02.cpp.
#define SRF02_MIN_DISTANCE (0.20f)
Definition at line 84 of file srf02.cpp.
#define SRF02_SET_ADDRESS_0 0xA0 /* Change address 0 Register */
Definition at line 79 of file srf02.cpp.
#define SRF02_SET_ADDRESS_1 0xAA /* Change address 1 Register */
Definition at line 80 of file srf02.cpp.
#define SRF02_SET_ADDRESS_2 0xA5 /* Change address 2 Register */
Definition at line 81 of file srf02.cpp.
#define SRF02_TAKE_RANGE_REG 0x51 /* Measure range Register */
Definition at line 78 of file srf02.cpp.
Referenced by SRF02::measure().
#define TICKS_BETWEEN_SUCCESIVE_FIRES 100000 /* 30ms between each sonar measurement (watch out for interference!) */
Definition at line 88 of file srf02.cpp.
Referenced by SRF02::init().
Function Documentation
int srf02_main (int argc, char * argv[])
Definition at line 926 of file srf02.cpp.
References srf02::info(), PX4_ERROR, px4_getopt(), PX4_WARN, srf02::reset(), SRF02_BUS_DEFAULT, srf02_usage(), srf02::start(), srf02::start_bus(), srf02::stop(), and srf02::test().
static void srf02_usage () static
Definition at line 914 of file srf02.cpp.
References PX4_INFO, and SRF02_BUS_DEFAULT.
Referenced by srf02_main().